### ISSUE TITLE
Build issue r2.6 with Cuda Compatibility 3.0

### ISSUE THREAD

**Issue by OrazioLombardi** [tensorflow/tensorflow#55621]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.6.3
- Python version: 3.7
- Installed using virtualenv? pip? conda?: No
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): MSVC2019
- CUDA/cuDNN version: 10.1/7.6
- GPU model and memory: Nvidia Quadro K1100M 2GB

**Describe the problem**

Hi,
I'm trying to build Tensorflow 2.6.3 from source on Windows, to support Cuda Compatibility 3.0.`
I follow this procedure [53062](https://github.com/tensorflow/tensorflow/issues/53062), but after few tries i continue to get this error during the compiling:

> Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=146
INFO: Reading rc options for 'build' from c:\users\priva\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/priva/AppData/Local/Programs/Python/Python37/python.exe
INFO: Reading rc options for 'build' from c:\users\priva\tensorflow\.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from c:\users\priva\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/Users/priva/AppData/Local/Programs/Python/Python37/python.exe --action_env PYTHON_LIB_PATH=C:/Users/priva/AppData/Local/Programs/Python/Python37/lib/site-packages --python_path=C:/Users/priva/AppData/Local/Programs/Python/Python37/python.exe --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.0 --config=cuda --define=with_xla_support=false --action_env TF_ENABLE_XLA=0 --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctionsINFO: Found applicable config definition build:short_logs in file c:\users\priva\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file c:\users\priva\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:cuda in file c:\users\priva\tensorflow\.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:windows in file c:\users\priva\tensorflow\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --distinct_host_configuration=falseINFO: Found applicable config definition build:monolithic in file c:\users\priva\tensorflow\.bazelrc: --define framework_shared_object=false
DEBUG: C:/users/priva/_bazel_priva/5lyc5377/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  C:/users/priva/tensorflow/WORKSPACE:23:14: in <toplevel>
  C:/users/priva/tensorflow/tensorflow/workspace0.bzl:108:34: in workspace
  C:/users/priva/_bazel_priva/5lyc5377/external/bazel_toolchains/repositories/repositories.bzl:37:23: in repositories
Repository rule git_repository defined at:
  C:/users/priva/_bazel_priva/5lyc5377/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (441 packages loaded, 32225 targets configured).
INFO: Found 1 target...
ERROR: C:/users/priva/tensorflow/tensorflow/core/kernels/BUILD:1222:18: C++ compilation of rule '//tensorflow/core/kernels:inplace_ops_gpu' failed (Exit 1): python.exe failed: error executing command
  cd C:/users/priva/_bazel_priva/5lyc5377/execroot/org_tensorflow
  SET CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1
    SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
    SET LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\\MSBuild\Current\Bin;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\;;C:\WINDOWS\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Users/priva/AppData/Local/Programs/Python/Python37/python.exe
    SET PYTHON_LIB_PATH=C:/Users/priva/AppData/Local/Programs/Python/Python37/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\priva\AppData\Local\Temp
    SET TF2_BEHAVIOR=1
    SET TF_CUDA_COMPUTE_CAPABILITIES=3.0
    SET TF_ENABLE_XLA=0
    SET TMP=C:\Users\priva\AppData\Local\Temp
  C:/Users/priva/AppData/Local/Programs/Python/Python37/python.exe -B external/local_config_cuda/crosstool/windows/msvc_wrapper_for_nvcc.py /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /bigobj /Zm500 /J /Gy /GF /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /I. /Ibazel-out/x64_windows-opt/bin /Iexternal/com_google_absl /Ibazel-out/x64_windows-opt/bin/external/com_google_absl /Iexternal/nsync /Ibazel-out/x64_windows-opt/bin/external/nsync /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/gif /Ibazel-out/x64_windows-opt/bin/external/gif /Iexternal/libjpeg_turbo /Ibazel-out/x64_windows-opt/bin/external/libjpeg_turbo /Iexternal/com_google_protobuf /Ibazel-out/x64_windows-opt/bin/external/com_google_protobuf /Iexternal/com_googlesource_code_re2 /Ibazel-out/x64_windows-opt/bin/external/com_googlesource_code_re2 /Iexternal/farmhash_archive /Ibazel-out/x64_windows-opt/bin/external/farmhash_archive /Iexternal/fft2d /Ibazel-out/x64_windows-opt/bin/external/fft2d /Iexternal/highwayhash /Ibazel-out/x64_windows-opt/bin/external/highwayhash /Iexternal/zlib /Ibazel-out/x64_windows-opt/bin/external/zlib /Iexternal/double_conversion /Ibazel-out/x64_windows-opt/bin/external/double_conversion /Iexternal/snappy /Ibazel-out/x64_windows-opt/bin/external/snappy /Iexternal/local_config_cuda /Ibazel-out/x64_windows-opt/bin/external/local_config_cuda /Iexternal/local_config_rocm /Ibazel-out/x64_windows-opt/bin/external/local_config_rocm /Iexternal/local_config_tensorrt /Ibazel-out/x64_windows-opt/bin/external/local_config_tensorrt /Iexternal/cudnn_frontend_archive /Ibazel-out/x64_windows-opt/bin/external/cudnn_frontend_archive /Iexternal/mkl_dnn_v1 /Ibazel-out/x64_windows-opt/bin/external/mkl_dnn_v1 /Iexternal/curl /Ibazel-out/x64_windows-opt/bin/external/curl /Iexternal/boringssl /Ibazel-out/x64_windows-opt/bin/external/boringssl /Iexternal/jsoncpp_git /Ibazel-out/x64_windows-opt/bin/external/jsoncpp_git /Ibazel-out/x64_windows-opt/bin/external/local_config_cuda/cuda/_virtual_includes/cuda_headers_virtual /Ibazel-out/x64_windows-opt/bin/external/local_config_tensorrt/_virtual_includes/tensorrt_headers /Ibazel-out/x64_windows-opt/bin/external/local_config_cuda/cuda/_virtual_includes/cudnn_header /Ibazel-out/x64_windows-opt/bin/external/local_config_cuda/cuda/_virtual_includes/cublas_headers_virtual /Ibazel-out/x64_windows-opt/bin/external/cudnn_frontend_archive/_virtual_includes/cudnn_frontend /Ibazel-out/x64_windows-opt/bin/external/local_config_cuda/cuda/_virtual_includes/cufft_headers_virtual /Ibazel-out/x64_windows-opt/bin/external/local_config_cuda/cuda/_virtual_includes/curand_headers_virtual /Iexternal/nsync/public /Ibazel-out/x64_windows-opt/bin/external/nsync/public /Ithird_party/eigen3/mkl_include /Ibazel-out/x64_windows-opt/bin/third_party/eigen3/mkl_include /Iexternal/eigen_archive /Ibazel-out/x64_windows-opt/bin/external/eigen_archive /Iexternal/gif /Ibazel-out/x64_windows-opt/bin/external/gif /Iexternal/gif/windows /Ibazel-out/x64_windows-opt/bin/external/gif/windows /Iexternal/com_google_protobuf/src /Ibazel-out/x64_windows-opt/bin/external/com_google_protobuf/src /Iexternal/farmhash_archive/src /Ibazel-out/x64_windows-opt/bin/external/farmhash_archive/src /Iexternal/zlib /Ibazel-out/x64_windows-opt/bin/external/zlib /Iexternal/double_conversion /Ibazel-out/x64_windows-opt/bin/external/double_conversion /Iexternal/local_config_cuda/cuda /Ibazel-out/x64_windows-opt/bin/external/local_config_cuda/cuda /Iexternal/local_config_cuda/cuda/cuda/include /Ibazel-out/x64_windows-opt/bin/external/local_config_cuda/cuda/cuda/include /Iexternal/local_config_rocm/rocm /Ibazel-out/x64_windows-opt/bin/external/local_config_rocm/rocm /Iexternal/local_config_rocm/rocm/rocm/include /Ibazel-out/x64_windows-opt/bin/external/local_config_rocm/rocm/rocm/include /Iexternal/local_config_rocm/rocm/rocm/include/rocrand /Ibazel-out/x64_windows-opt/bin/external/local_config_rocm/rocm/rocm/include/rocrand /Iexternal/local_config_rocm/rocm/rocm/include/roctracer /Ibazel-out/x64_windows-opt/bin/external/local_config_rocm/rocm/rocm/include/roctracer /Iexternal/local_config_cuda/cuda/cublas/include /Ibazel-out/x64_windows-opt/bin/external/local_config_cuda/cuda/cublas/include /Iexternal/local_config_cuda/cuda/cufft/include /Ibazel-out/x64_windows-opt/bin/external/local_config_cuda/cuda/cufft/include /Iexternal/local_config_cuda/cuda/curand/include /Ibazel-out/x64_windows-opt/bin/external/local_config_cuda/cuda/curand/include /Iexternal/mkl_dnn_v1/include /Ibazel-out/x64_windows-opt/bin/external/mkl_dnn_v1/include /Iexternal/mkl_dnn_v1/src /Ibazel-out/x64_windows-opt/bin/external/mkl_dnn_v1/src /Iexternal/mkl_dnn_v1/src/common /Ibazel-out/x64_windows-opt/bin/external/mkl_dnn_v1/src/common /Iexternal/mkl_dnn_v1/src/common/ittnotify /Ibazel-out/x64_windows-opt/bin/external/mkl_dnn_v1/src/common/ittnotify /Iexternal/mkl_dnn_v1/src/cpu /Ibazel-out/x64_windows-opt/bin/external/mkl_dnn_v1/src/cpu /Iexternal/mkl_dnn_v1/src/cpu/gemm /Ibazel-out/x64_windows-opt/bin/external/mkl_dnn_v1/src/cpu/gemm /Iexternal/mkl_dnn_v1/src/cpu/x64/xbyak /Ibazel-out/x64_windows-opt/bin/external/mkl_dnn_v1/src/cpu/x64/xbyak /Iexternal/curl/include /Ibazel-out/x64_windows-opt/bin/external/curl/include /Iexternal/boringssl/src/include /Ibazel-out/x64_windows-opt/bin/external/boringssl/src/include /Iexternal/jsoncpp_git/include /Ibazel-out/x64_windows-opt/bin/external/jsoncpp_git/include /DTENSORFLOW_USE_CUSTOM_CONTRACTION_KERNEL /DTENSORFLOW_USE_MKLDNN_CONTRACTION_KERNEL /DCURL_STATICLIB /DTF_USE_SNAPPY /DEIGEN_MPL2_ONLY /DEIGEN_MAX_ALIGN_BYTES=64 /showIncludes /MD /O2 /DNDEBUG /W0 /D_USE_MATH_DEFINES -DWIN32_LEAN_AND_MEAN -DNOGDI /experimental:preprocessor /d2ReducedOptimizeHugeFunctions /std:c++14 -x cuda -DGOOGLE_CUDA=1 -Xcuda-fatbinary=--compress-all --no-cuda-include-ptx=all --cuda-include-ptx=sm_30 --cuda-gpu-arch=sm_30 -DGOOGLE_CUDA=1 -DTENSORFLOW_USE_NVCC=1 -DINTEL_MKL -DTENSORFLOW_MONOLITHIC_BUILD /DPLATFORM_WINDOWS /DEIGEN_HAS_C99_MATH /DTENSORFLOW_USE_EIGEN_THREADPOOL /DEIGEN_AVOID_STL_ARRAY /Iexternal/gemmlowp /wd4018 /wd4577 /DNOGDI /DTF_COMPILE_LIBRARY -nvcc_options=relaxed-constexpr -nvcc_options=ftz=true /Fobazel-out/x64_windows-opt/bin/tensorflow/core/kernels/_objs/inplace_ops_gpu/inplace_ops_functor_gpu.cu.obj /c tensorflow/core/kernels/inplace_ops_functor_gpu.cu.cc
Execution platform: @local_execution_config_platform//:platform
cl : warning della riga di comando D9035 : l'opzione 'experimental:preprocessor' è deprecata e verrà rimossa in una futura versione
cl : warning della riga di comando D9036 : utilizzare 'Zc:preprocessor' invece di 'experimental:preprocessor'
cl : warning della riga di comando D9002 : l'opzione sconosciuta '--no-cuda-include-ptx=all' verrà ignorata
cl : warning della riga di comando D9002 : l'opzione sconosciuta '--cuda-include-ptx=sm_30' verrà ignorata
cl : warning della riga di comando D9002 : l'opzione sconosciuta '--cuda-gpu-arch=sm_30' verrà ignorata
C:\users\priva\_bazel_priva\5lyc5377\execroot\org_tensorflow\external\eigen_archive\unsupported\Eigen\CXX11\src/Tensor/TensorBlock.h(245): warning: invalid friend declaration
C:\users\priva\_bazel_priva\5lyc5377\execroot\org_tensorflow\external\eigen_archive\unsupported\Eigen\CXX11\src/Tensor/TensorBlock.h(709): warning: invalid friend declaration
external/com_google_absl\absl/strings/string_view.h(337): warning: expression has no effect
external/com_google_absl\absl/strings/string_view.h(347): warning: expression has no effect
external/com_google_absl\absl/strings/string_view.h(529): warning: expression has no effect
external/com_google_protobuf/src\google/protobuf/map.h(1028): warning: invalid friend declaration
external/com_google_absl\absl/types/internal/span.h(38): error: incomplete type is not allowed
          detected during instantiation of "absl::lts_20210324::span_internal::GetDataImpl" based on template argument <tensorflow::TensorShapeProto>
.\tensorflow/core/framework/tensor_shape.h(376): here
.\tensorflow/core/lib/gtl/flatmap.h(157): warning: invalid friend declaration
.\tensorflow/core/platform/file_system.h(574): warning: overloaded virtual function "tensorflow::FileSystem::FilesExist" is only partially overridden in class "tensorflow::WrappedFileSystem"
.\tensorflow/core/platform/file_system.h(574): warning: overloaded virtual function "tensorflow::FileSystem::CreateDir" is only partially overridden in class "tensorflow::WrappedFileSystem"
.\tensorflow/core/platform/env.h(495): warning: overloaded virtual function "tensorflow::Env::RegisterFileSystem" is only partially overridden in class "tensorflow::EnvWrapper"
external/com_google_absl\absl/types/optional.h(428): warning: expression has no effect
          detected during instantiation of "const T &absl::lts_20210324::optional<T>::operator*() const & [with T=stream_executor::dnn::AlgorithmDesc]"
.\tensorflow/stream_executor/dnn.h(817): here
external/com_google_absl\absl/types/optional.h(428): warning: expression has no effect
          detected during instantiation of "const T &absl::lts_20210324::optional<T>::operator*() const & [with T=size_t]"
.\tensorflow/stream_executor/dnn.h(876): here
1 error detected in the compilation of "C:/Users/priva/AppData/Local/Temp/nvcc_inter_files_tmp_dir/tmpcg3nm8rj/inplace_ops_functor_gpu.cu.cpp1.ii".
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1302.308s, Critical Path: 224.15s
INFO: 4180 processes: 2005 internal, 2175 local.
FAILED: Build did NOT complete successfully

Is this a problem related with the MSVC compiler or something else?
Thanks for the support.

**Comment by sushreebarsa** [comment]
@OrazioLombardi Could you please try to upgrade to latest TF v2.8.0 and refer this [tested build configurations](https://www.tensorflow.org/install/source_windows#tested_build_configurations) , please let us know if it helps?Thanks!

**Comment by OrazioLombardi** [comment]
@sushreebarsa the problem is that cuda 11.2 doesn't support compute capability 3.0.
I can tra to upgrade to 2.8 but I cannot use a tested build configuration as suggest.
I also try the tested build configuration of TF v2.4 but the result it's quite the same.

**Comment by sushreebarsa** [comment]
@OrazioLombardi Thank you for the update!
 From the error log it seems to be an issue with MSVC2019 , could you please  make sure that you are using the right GCC version as mentioned in the tested build configuration ?
Thanks!

**Comment by OrazioLombardi** [comment]
Hi @sushreebarsa. I have GCC installed by Cygwin.
Today I update GCC to the latest version and try to build tensorflow but nothing seems to change in the output.
By the way, in the tested build configuration for Windows, GCC is not metioned (GCC is mentioned only in Linux guide), are you sure that this could influence the building process?
How can I check that the right version of GCC is installed on my computer and that works correctly with MSVC2019?

**Comment by gadagashwini** [comment]
@OrazioLombardi,
Hi, Issue with CUDA compatibility. Tensorflow 2.6 doesn’t support Cuda compatibility 3. 

You need to add the compatibility factor.
`ComputeCapabilityFromString("3.0"), ComputeCapabilityFromString("3.5"), ComputeCapabilityFromString("5.2")};`
Do changes in this [file](https://github.com/tensorflow/tensorflow/blob/r2.6/tensorflow/core/common_runtime/gpu/gpu_device.cc#L1717). Thanks!

**Comment by OrazioLombardi** [comment]
@gadagashwini
Hi, thank you for your answer.
I already edit the `gpu_device.cc` file adding the `ComputeCapabilityFromString("3.0")` statement as already mentioned in my issue description.
I think that the problem is related to MSVC that has problem to compile some of the files.

**Comment by gadagashwini** [comment]
@OrazioLombardi,
```
ERROR: C:/users/priva/tensorflow/tensorflow/core/kernels/BUILD:1222:18: C++ compilation of rule '//tensorflow/core/kernels:inplace_ops_gpu' failed (Exit 1): python.exe failed: error executing command
cd C:/users/priva/_bazel_priva/5lyc5377/execroot/org_tensorflow
```
Looks issue with MSVC2019.

Make sure you followed steps mentioned [here](https://www.tensorflow.org/install/source_windows) and install required packages. Thanks !

**Comment by llv22** [comment]
@OrazioLombardi 

Hi guy, I'm enabling tensorflow 2.8 on mac 10.13.6 with cuda 10.1, cudnn7.3.6 and meeting with the same issue. After investigating with code logic, I figured out the root cause:

you check the implementation of absl::lts_20210324::span_internal::GetDataImpl in https://github.com/abseil/abseil-cpp/blob/1ae9b71c474628d60eb251a3f62967fe64151bb2/absl/types/internal/span.h#L38, you will find 

```c++
template <typename C>
constexpr auto GetDataImpl(C& c, char) noexcept  // NOLINT(runtime/references)
    -> decltype(c.data()) {
  return c.data();
}
```

this function is used to call typename with remember function data(). with keywords decltype and constexpr auto, the compiler could delegate the instantiation phase for type compatibility check-up, saying whether such type has data() function.

However, the trick lies during the instantiation phase. That is if and only if the typename could be found with detailed declaration, otherwise it will fail.

OK, back to the instantiation phase of our case:

```bash
ERROR: /home/jueonpark/tensorflow/tensorflow/core/kernels/image/BUILD:308:18: C++ compilation of rule '//tensorflow/core/kernels/image:resize_nearest_neighbor_op_gpu' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF ... (remaining 216 argument(s) skipped)
external/com_google_absl/absl/types/internal/span.h(38): error: incomplete type is not allowed
          detected during instantiation of "absl::lts_20210324::span_internal::GetDataImpl" based on template argument <tensorflow::TensorShapeProto>
./tensorflow/core/framework/tensor_shape.h(376): here
```
check the implementation of https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor_shape.h#L375
```c++
  static Status BuildTensorShape(const TensorShapeProto& proto,
                                 TensorShape* out) {
    return BuildTensorShapeBase(proto, out);
  }
```
how does TensorShapeProto generate? it is a sort of proto file (protobuf protocol declaration) which will be converted to pb.h file together with its default implementation based on protobuf protocol.

But there is no declaration in resize_nearest_neighbor_op_gpu.cu.cc to let compile understand its detailed type. 
so like https://github.com/tensorflow/tensorflow/blob/6b7b98fa154d57260337e5e5f929f8907f4b23f1/tensorflow/lite/kernels/shim/tf_tensor_view_test.cc, 
just include 

#include "tensorflow/core/framework/tensor_shape.pb.h" 

to your resize_nearest_neighbor_op_gpu.cu.cc
this issue will be settled down.

PS: Regarding why cuda 11.0+ doesn't have such pain, I guess during compilation resize_nearest_neighbor_op_gpu.cu.pic.d may insert tensor_shape.pb.h in advance, so the class type is ready to use during compilation.

Enjoy your hack anyway. ^-^

**Comment by llv22** [comment]
@OrazioLombardi I checked with Line 22 of https://github.com/tensorflow/tensorflow/blob/6b7b98fa154d57260337e5e5f929f8907f4b23f1/tensorflow/lite/kernels/shim/tf_tensor_view_test.cc

#include "tensorflow/core/framework/tensor.pb.h"

check readme.md in https://github.com/tensorflow/tensorflow/tree/6b7b98fa154d57260337e5e5f929f8907f4b23f1/tensorflow/lite/kernels/shim

See **the unit tests tf_tensor_view_test.cc and tflite_tensor_view_test.cc** for more usage.

1. you don't have to include for *_test.cc, as they are unit tests which could be included in framework ^-^. They just serve for the purpose of checking up if the functionalities as expected. Well, also a showcase about how to use the class, check the link above about how to use TensorView, one exactly case. 
2.  inplace_ops_functor_gpu.cu.cc will be compiled and packaged into library. but unfortunately no TensorShapeProto declaration has been found during compilation phase.  I think you need to add #include "tensorflow/core/framework/tensor_shape.pb.h" in it
3. Regarding why cuda 10.1 or older version miss the supposed operation of including proto files in cc file, I still need to compare the default behaviors of old nvcc compilers and the latest one (I suppose so). Unfortunately, now there is no clear clue.... --||
