### ISSUE TITLE
No module named 'tensorflow.contrib.framework.ops'

### ISSUE THREAD

**Issue by 0smilingpig** [tensorflow/tensorflow#55620]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution: win 10 
- TensorFlow installed from (source or binary): I don't remember....
- TensorFlow version: 1.15.0
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.0/7.4
- GPU model and memory: MX330

**Describe the problem**
When i run the train_ssd_network.py in ssd training program there was an error:
=======================================================

 from tensorflow.contrib.framework.ops import variables as contrib_variables

ModuleNotFoundError: No module named 'tensorflow.contrib.framework.ops'

=====================================================

The codes which caused problem are in metrics.py and these are part of the codes:
-----------------------------------------------------------------------------------------
import tensorflow as tf
import numpy as np

_**from tensorflow.contrib.framework.ops import variables as contrib_variables**_
from tensorflow.python.framework import dtypes
from tensorflow.python.framework import ops
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import math_ops
from tensorflow.python.ops import nn
from tensorflow.python.ops import state_ops
from tensorflow.python.ops import variable_scope
from tensorflow.python.ops import variables

from tf_extended import math as tfe_math
----------------------------------------------------------------------------------------------
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**

**Comment by tilakrayal** [comment]
Hello @0smilingpig,

tensorflow.contrib is being removed in version 2.x,I request you to please refer this [document](https://www.tensorflow.org/guide/migrate) to migrate from `TensorFlow 1.x to TensorFlow 2. `

Also I request you to please try to update the latest stable version `2.8` for [here](https://www.tensorflow.org/install/pip).There is a high possibility that any bug fixes with later TF versions.Thanks!

**Comment by 0smilingpig** [comment]
Thank you for your comment, but I said I am using tensorflow version 1.14.0 which doesn't remove tensorflow.contrib and now the error occurred. I wonder why there is no module named tensorflow.contrib.framework.ops in 1.14.0 if tensorflow.contrib is still exist on that version.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月14日(星期四) 晚上10:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tensorflow/tensorflow] No module named &#39;tensorflow.contrib.framework.ops&#39; (Issue #55620)





 
Hello @0smilingpig,
 
tensorflow.contrib is being removed in version 2.x,I request you to please refer this document to migrate from TensorFlow 1.x to TensorFlow 2. 
 
Also I request you to please try to update the latest stable version 2.8 for here.There is a high possibility that any bug fixes with later TF versions.Thanks!

**Comment by tilakrayal** [comment]
@0smilingpig ,
We see that you are using tf version 1.14, where 1.x is not actively supported.Requesting you, please update to latest v2.x and let us know if you are facing same issue.Thanks!

**Comment by 0smilingpig** [comment]
Well, I have tried it on 2.8.0 and 1.15.0 before but they didn't work, then I downgrade to 1.14.0 the problem was still there.&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月18日(星期一) 晚上6:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tensorflow/tensorflow] No module named &#39;tensorflow.contrib.framework.ops&#39; (Issue #55620)





 
@0smilingpig ,
 We see that you are using tf version 1.14, where 1.x is not actively supported.Requesting you, please update to latest v2.x and let us know if you are facing same issue.Thanks!

**Comment by gowthamkpr** [comment]
@0smilingpig Contrib module exists in tensorflow 1.15. Here is my [github gist](https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/contrib/framework/python/ops/variables.py). 

You are importing variables from the wrong path inside contrib module. 
Instead of using from `tensorflow.contrib.framework.ops import variables as contrib_variables`, 
use `from tensorflow.contrib.framework.python.ops import variables as contrib_variables`

**Comment by mihaimaruseac** [comment]
TF 1.15 is out of date. We no longer support it.

**Comment by mihaimaruseac** [comment]
(sorry, closed by mistake)

**Comment by tilakrayal** [comment]
@0smilingpig ,
As suggested 1.15 is not actively supported.Please upgrade to latest version.Also as per [comment](https://github.com/tensorflow/tensorflow/issues/55620#issuecomment-1104139067) I request you,please try to use `from tensorflow.contrib.framework.python.ops import variables as contrib_variables`.Thanks!
