### ISSUE TITLE
`tf.io.write_graph` fails to stip debug nodes

### ISSUE THREAD

**Issue by enaskopelja** [tensorflow/tensorflow#55627]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `macOS Monterey 12.2.1 (m1)`
- TensorFlow installed from (source or binary):  source, following https://developer.apple.com/metal/tensorflow-plugin/
- TensorFlow version (use command below): 
```
tensorflow-deps==2.8.0
tensorflow-macos==2.8.0
tensorflow-metal==0.4.0  
```
(the provided command returns `unknown 2.8.0`)
- Python version: `3.9`

**Describe the current behavior**
Despite having set:`tf.config.optimizer.set_experimental_options({'debug_stripper': True})`, the `.pbtxt` record of a simple `tf.function` graph, generated by `tf.io.write_graph` still contains `assert_shape` nodes.

***Minimal example***:
```python
import tensorflow as tf
tf.config.optimizer.set_experimental_options({'debug_stripper': True})

@tf.function(
    input_signature=[
        tf.TensorSpec(
            shape=(2, 2),
            dtype=tf.int32,
            name="Input",
        ),
    ]
)
def fn(x):
    tf.debugging.assert_shapes(
        [
            (x, (2, 2))
        ]
    )
    return x

tf.io.write_graph(
    fn.get_concrete_function().graph,
    logdir=".",
    name="example.pbtxt",
    as_text=True,
)
```

**Describe the expected behavior**
`assert_shape` nodes should not be present in the final graph.

**Standalone code to reproduce the issue**
Colab notebook: https://colab.research.google.com/drive/1l_P345AjMiHsLUTqG5io2Fjyag-1qIAM?usp=sharing

**Other info / logs**
Resulting `.pbtxt` file: 
```pbtxt
node {
  name: "Input"
  op: "Placeholder"
  attr {
    key: "_user_specified_name"
    value {
      s: "Input"
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 2
        }
        dim {
          size: 2
        }
      }
    }
  }
}
node {
  name: "assert_shapes/Shape"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\002\000\000\000\002\000\000\000"
      }
    }
  }
}
node {
  name: "assert_shapes/assert_rank/rank"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 2
      }
    }
  }
}
node {
  name: "assert_shapes/assert_rank/Shape"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\002\000\000\000\002\000\000\000"
      }
    }
  }
}
node {
  name: "assert_shapes/assert_rank/assert_type/statically_determined_correct_type"
  op: "NoOp"
}
node {
  name: "assert_shapes/assert_rank/static_checks_determined_all_ok"
  op: "NoOp"
}
node {
  name: "group_deps"
  op: "NoOp"
  input: "^assert_shapes/assert_rank/static_checks_determined_all_ok"
}
node {
  name: "Identity"
  op: "Identity"
  input: "Input"
  attr {
    key: "T"
    value {
      type: DT_INT32
    }
  }
}
versions {
  producer: 987
}
```

**Comment by tilakrayal** [comment]
@sachinprasadhs ,
I was able to reproduce the issue in tf v2.7, v2.8 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/7e0af283303d49f7138ecc3fdea2b139/55627.ipynb).

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
