### ISSUE TITLE
fit() with generator and multiprocessing leaks sockets/files

### ISSUE THREAD

**Issue by Mastiff37** [tensorflow/tensorflow#55623]
**System information**
- Have I written custom code - yes
- OS Platform and Distribution - Linux CentOS7
- TensorFlow installed from binary
- TensorFlow version 2.5.0
- Python version: 3.8
- 
**Describe the current behavior**

If I run model.fit() with a generator in a loop, for a long time, I eventually get `OSError: [Errno 24] Too many open files`.

**Describe the expected behavior**

Run stably forever.

The actual code is on an offline machine, but this is the basic idea:

```
while True:
   model.fit(mySeqGen(xx), ..., use_multiprocessing=True, workers=8)
   <stuff>
   model.save_weights(fname)
   gc.collect()
```
This will run for a long time, but eventually it will generate the error every iteration.  The stack trace is all about "python3.8/multiprocessing/..." so I'm sure it's not related to actual files, but rather sockets or whatever the multiprocessor generates.  I thought the `gc.collect()` would solve the problem but does not appear to do so, or it can't keep up.  Each loop iteration takes about a minute as I have it configured now.  Note also that the seqGen is a wrapper around a simulator and does not go to the file system.

**Comment by tilakrayal** [comment]
Hello @Mastiff37 ,
In order to expedite the trouble-shooting process, could you please provide a complete code and the dependencies you are using.Thanks!

**Comment by tilakrayal** [comment]
Also i request  that there is a high possibility that this might fixed with later TF versions. Perhaps you can use latest tf stable version2.8 for your case. Thanks!

**Comment by Mastiff37** [comment]
The actual code is on an offline machine, but I can try to gin up a toy example...

**Comment by tilakrayal** [comment]
@Mastiff37 ,
 Please provide the update?Thanks!

**Comment by Mastiff37** [comment]
I'm running a toy example now to see if I can reproduce.

**Comment by tilakrayal** [comment]
@Mastiff37 ,
In order to expedite the trouble-shooting process, could you please provide a complete code and the dependencies you are using.Thanks!
