### ISSUE TITLE
tensorflow 2.8 distributed training for neural network model (designed by subclass) cannot improve the training runtime on multicore CPUs

### ISSUE THREAD

**Issue by umusa** [tensorflow/tensorflow#55622]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no (the code is too long)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu (18.04.6)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: no
- TensorFlow installed from (source or binary): pip install tensorflow==2.8.0
- TensorFlow version (use command below): 2.8.0
- Python version: 3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

I am trying to train a neural network model built by tf2.8 and keras 2.8.
I would like to train the model with distributed training on multiple CPUs (e.g. EC2 m4.4 with 16 cpu cores) to improve the training performance.
I am using [MirroredStrategy](https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy).
I am following the example at https://www.tensorflow.org/tutorials/distribute/keras
and https://www.tensorflow.org/tutorials/distribute/custom_training
My neural network model is built by subclass (not functional API) of TF2.8 and keras.

But, the training run time  (50 mins per epoch) is not improved significantly compared with non-distributed training (65 mins per epoch) on EC2 m4.4 (16 cpu cores). During the training process, most cores are idle or have very low utilizations (< 5%).
I also got a warning at the end of each epoch:     

**WARNING:tensorflow:Using MirroredStrategy eagerly has significant overhead currently. We will be working on improving this in the future, but for now please wrap `call_for_each_replica` or `experimental_run` or `run` inside a tf.function to get the best performance.**

 But, in my model, there are no "call_for_each_replica", "experimental_run" and "run". 
There are only 

     with mirroredStrategy.scope():
         class model(keras.model):
                 def __init__(self):
                      self.subclass_model1 = model1()
                      self.subclass_model2 = model2() 

                 def  call(self, input, training=True):
                      # call self.subclass_model1  and self.subclass_model2 to run the whole model
      with mirroredStrategy.scope():
          model.compile()
          model.fit()

Please let me know how to improve the training runtime ? 

**Describe the expected behavior**
 The distributed training runtime should be improved greatly compared with non-distributed training.

**Comment by tilakrayal** [comment]
Hello @umusa ,
You have provided multiple links for the code.Can you please confirm the reproducible code link or provide the complete here to reproduce the issue.Thanks!

**Comment by umusa** [comment]
@tilakrayal , please use  https://www.tensorflow.org/tutorials/distribute/keras, my code is based on this example.

**Comment by gowthamkpr** [comment]
@umusa Can you please follow the solutions provided [here](https://stackoverflow.com/questions/66597074/using-multiple-cpu-cores-with-tensorflow) and let me know. Thanks!
