### ISSUE TITLE
tutorial - code

### ISSUE THREAD

**Issue by lordna** [tensorflow/tensorflow#5564]
Hello Team,

Yesterday evening I completed your tutorial (https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#5) to take my first steps with tensorflow. During the process I had to complete the code as in label_image.py there is no import sys line.

Cheers!

**Comment by wolffg** [comment]
Fixed!  Thanks for pointing that out.  It was correct in the gist, but not written in the code.
