### ISSUE TITLE
Enable `unique` bool for `tf.random.uniform`! 

### ISSUE THREAD

**Issue by innat** [tensorflow/tensorflow#55646]
**System information**
- TensorFlow version (you are using): 2.8
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Currently, the `tf.random.uniform`, randomly sample values form given min and max range **without considering the repeating same value**. For example, currently:

```python
tf.random.uniform(shape=[5], maxval=5, dtype=tf.int32, seed=10)
<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 3, 3, 1], dtype=int32)>
````

but if it has a `unique` bool parameter, it would be possible to generate a unique random value. For example:

```python
tf.random.uniform(shape=[5], maxval=5, dtype=tf.int32, seed=10, unique=True)
<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 2, 4, 3, 1], dtype=int32)>
````

**Will this change the current API? How?**

From 

```python
tf.random.uniform(
    shape,
    minval=0,
    maxval=None,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
```

To 

```python
tf.random.uniform(
    shape,
    minval=0,
    maxval=None,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None,
    unique=False
)
```

**Who will benefit from this feature?**

A similar thing is possible with `import random; random.sample`. So, having `unique` bool in `tf.ranom.uniform` might be useful in some special cases. Similar param in [tf.random.uniform_candidate_sampler](https://www.tensorflow.org/api_docs/python/tf/random/uniform_candidate_sampler).

**Any Other info.**

I am not sure if there is any other convenient TensorFlow function that can be used to generate unique random values. I know we can do 

```python
tf.random.shuffle(tf.range(5))
```

But `tf.random.shuffle` has certain limitations to fall back to `while_loop`. That's why we can't use it here. Let me know if I've missed something.

**Comment by wangpengmit** [comment]
Hi @innat, in your use case, will `shape[0]` always equal to `maxval - minval`? If so, we recommend `tf.random.experimental.index_shuffle` or a forthcoming `tf.random.experimental.stateless_shuffle`. If not, the feature is trickier to implement.

**Comment by innat** [comment]
@wangpengmit Thanks for your response. I've tried `tf.random.index_shuffle` and `tf.random.shuffle`.  Both gave 

> WARNING:tensorflow:Using a while_loop for converting RandomIndexShuffle cause has no variant outputs and has no vectorized variant inputs

> WARNING:tensorflow: Using a while_loop for converting RandomShuffle cause has no variant outputs and has no vectorized variant inputs

**Comment by innat** [comment]
Apart from this shuffling function, I think it makes sense to have such a `unique` bool param in `tf.random.uniform` in general. What do you think?

**Comment by wangpengmit** [comment]
I just realized that even if `shape[0] < maxval - minval`, the functionality you need can be achieved via `tf.random.experimental.index_shuffle`:
```
def unique_uniform(num_samples, minval, maxval, seed, dtype):  # maxval is inclusive
  return tf.random.experimental.index_shuffle(tf.range(num_samples, dtype=dtype), seed=seed, max_index=maxval-minval) + minval
```
so no new features are needed. Another reason I'm against adding this feature to `tf.random.uniform` is that "unique uniform sampling" is mathematically closer to shuffling than "uniform sampling".

`tf.vectorized_map` and XLA supports are orthogonal to this issue. We can discuss them in separate issues.

**Comment by innat** [comment]
Yes, it seems like it's a nice workaround. 

```python
def unique_uniform(num_samples, 
                   minval, 
                   maxval, 
                   seed, 
                   shape, 
                   dtype):  # maxval is inclusive

    shuffled_index = tf.random.experimental.index_shuffle(
        tf.range(num_samples, dtype=tf.int32), 
        seed=seed, max_index=maxval-minval
    ) + minval

    return tf.cast(
        tf.reshape(shuffled_index, shape), dtype=dtype
    )
```
```
rng = tf.random.Generator.from_seed(1234)
```
```python
set_seed = tf.reshape(rng.make_seeds(), [-1])

unique_uniform(
    num_samples=20, 
    minval=5, 
    maxval=30, 
    seed=set_seed, 
    shape=[4,5], 
    dtype=tf.float32
)
```
```
<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[10., 27., 23.,  9., 26.],
       [ 5., 11., 18., 30., 16.],
       [21., 15., 25., 13., 17.],
       [14.,  6., 28., 20.,  7.]], dtype=float32)>
```

**Comment by innat** [comment]
@wangpengmit I'm ok with this solution. Please close the issue if you don't wanna add anything. Thanks again.
