### ISSUE TITLE
StatelessRandomBinomial op's  first input (shape) does not support int64

### ISSUE THREAD

**Issue by xuanhuo** [tensorflow/tensorflow#55643]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
```
import tensorflow as tf
shape = tf.constant([1, 1, 1], dtype=tf.int64)
seed = [52, 35]
counts = [10.1]
probs = [0.1]

data = tf.raw_ops.StatelessRandomBinomial(
    shape = shape, seed=seed, counts = counts, probs=probs, dtype=tf.float32
)
print(data)
```
- TensorFlow version (use command below):
 2.6.3

**Describe the current behavior**
```
tensorflow/core/framework/tensor.cc:708] Check failed: dtype() == expected_dtype (9 vs. 3) int32 expected, got int64
Aborted

I think this bug caused by the following code which are only work for int32

for (int64 i = 0; i < num_sample_dims; ++i) {
      samples_per_batch *= shape_tensor.flat<**int32**>()(i);
    }
```

**Comment by tilakrayal** [comment]
Hello @xuanhuo ,
I have tried to execute the given code with another approach.Can you please find the [gist](https://colab.research.google.com/gist/tilakrayal/325755e4c75f32d2efde1c83714d7bbb/55643.ipynb) and let us know if it helps.Thanks!
