### ISSUE TITLE
Not able to encode tensor in any type of image format that other libraries can understand

### ISSUE THREAD

**Issue by rohanmuplara** [tensorflow/tensorflow#55651]
I am trying to write a tensor to an image format As seen in colab in bottom, when I take the encoded bytes and write it a file using python, it doesn't work. Trying opening the image it gets corrupted. I have used gif, png, jpeg
When I use tf.io.write_file it works. I also tried taking a png and using tf.io_decode_png and than tf.io.encoding_png and the image string bytes differ from the original png. I am using tensorflow serving and using this png result through the rest api, where I don't have access to tf.io.write_file so I was wondering what encode  does differently, than traditional encodings.

https://www.loom.com/share/4b32b330a0e742cab2ea3a1a9af11b22
https://colab.research.google.com/drive/13Y4ET8jAHZDq7qwUYgg8nuBkxqniUqGu#scrollTo=IcXVZepnhkW4

**Comment by rohanmuplara** [comment]
@sushreebarsa anything I can do to make the issue more clear

**Comment by sushreebarsa** [comment]
@rohanmuplara 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by rohanmuplara** [comment]
@sushreebarsa I actually think this more of a tensorflow core issue.  I can remove it from there if you prefer as this is a problem I am seeing in tensorflow core and people might encounter this even if they are not using tensorflow serving;

**Comment by sushreebarsa** [comment]
@rohanmuplara Thank you for the update!
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!
