### ISSUE TITLE
Got this BUG while attempting to save the model

### ISSUE THREAD

**Issue by zjk000** [tensorflow/tensorflow#55658]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04.5 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary): I don't know, I ran on a cloud server that I rent
- TensorFlow version (use command below): 2.4.1
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: 11.1.1
- GPU model and memory: GeForce RTX 3090, 23G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

> root@625d1712cc5660deb2f669c7:~# python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
> 2022-04-18 21:15:44.795209: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
> v2.4.0-49-g85c8b2a817f 2.4.1

**Describe the current behavior**
A checkpoint model is supposed to be saved at the 100st iteration, while attempting to save it, this BUG occurred and is shown under **Other info / logs**, and then the process stopped.

**Describe the expected behavior**
After successfully saving the checkpoint model at the 100st iteration, the process should go on training normaly.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): not sure what a PR is
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://drive.google.com/drive/folders/1fKO0aQmXu1KSNBeny_HWt8SiAtvZ4D_b?usp=sharing

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

> [libprotobuf ERROR google/protobuf/wire_format_lite.cc:577] String field 'tensorflow.TensorShapeProto.Dim.name' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
> Traceback (most recent call last):
>   File "train.py", line 77, in <module>
>     train(model)
>   File "train.py", line 24, in train
>     model.optimize()
>   File "/user-data/HyperBox-main/script/model/box_model.py", line 329, in optimize
>     self.save_model(itr)
>   File "/user-data/HyperBox-main/script/model/box_model.py", line 140, in save_model
>     self.saver.save(self.sess, filename)
>   File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1208, in save
>     self.export_meta_graph(
>   File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1254, in export_meta_graph
>     graph_def=ops.get_default_graph().as_graph_def(add_shapes=True),
>   File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3345, in as_graph_def
>     result, _ = self._as_graph_def(from_version, add_shapes)
>   File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3262, in _as_graph_def
>     graph.ParseFromString(compat.as_bytes(data))
> google.protobuf.message.DecodeError: Error parsing message
>

**Comment by sushreebarsa** [comment]
@zjk000 Could you please refer to this [link](https://www.tensorflow.org/tutorials/keras/save_and_load) and try with the latest TF version .Please let us know the outcome?
Thanks!

**Comment by zjk000** [comment]
Hi, I've been studying this problem for the past few days, and here are 2 conclusions so far:
1. For the original problem, that error occoured beacause: protobuf asked for utf-8 data or raw bytes and claimed what was sent to it wasn't one of these 2 types. But the fact is, if you look into the definition of function compat.as_bytes(data):
```
def as_bytes(bytes_or_text, encoding='utf-8'):
  if isinstance(bytes_or_text, bytearray):
    return bytes(bytes_or_text)
  elif isinstance(bytes_or_text, _six.text_type):       # _six.text_type = unicode
    return bytes_or_text.encode(encoding)
  elif isinstance(bytes_or_text, bytes):
    return bytes_or_text
  else:
    raise TypeError('Expected binary or unicode string, got %r' %
                    (bytes_or_text,))
```

We can see that this function makes sure that what will be passed into graph.ParseFromString(which later passed to protobuf) is definitely utf-8 data or bytes, however, the protobuf keeps claiming the data passed to it is not valid utf-8 data. Taking one step back, even if the data was not valid utf-8, it is definitely bytes, which it should take in normally.

Furthermore, I added one line of code before the execution of graph.ParseFromString(compat.as_bytes(data)):
```
      pprint(type(data))
      graph.ParseFromString(compat.as_bytes(data))
```
And the result is : 
> <class 'bytes'>

The data has already been bytes even before it is passed into compat.as_bytes.


2. As recommended, I tried to rewrite the code in TF 2.x style and with TF 2.5.0(the reason I didn't use the latest 2.8.0 as suggested is that this is a project I found on GitHub and it uses TF 2.5.0). Also,  some error occurred: 
```
Traceback (most recent call last):
  File "train.py", line 78, in <module>
    train(model)
  File "train.py", line 24, in train
    model.optimize()
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 763, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3279, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3971, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    /root/autodl-tmp/HyperBox-main/script/model_v2/box_model.py:328 optimize  *
        self.create_optimizer()
    /root/autodl-tmp/HyperBox-main/script/model_v2/box_model.py:139 create_optimizer  *
        self.optimizer = tf.keras.optimizers.Adam(
    /root/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:530 minimize  **
        return self.apply_gradients(grads_and_vars, name=name)
    /root/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:630 apply_gradients
        grads_and_vars = optimizer_utils.filter_empty_gradients(grads_and_vars)
    /root/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/optimizer_v2/utils.py:75 filter_empty_gradients
        raise ValueError("No gradients provided for any variable: %s." %

    ValueError: No gradients provided for any variable: ['rel_bases:0', 'rel_shapes:0', 'rel_multiples:0', 'base_weight_ent_emb:0', 'bump_weight_ent_emb:0', 'ent_emb:0', 'ent_emb_bmp:0'].
```
From what I've learned on the Internet, this error basically says the loss wasn't calculated using the variables in var_list, but I checked, the loss is surely calculated directly or indirectly using all the variables in var_list. And here's the code I rewrote in TF 2.x style, will you have a look at it?https://colab.research.google.com/drive/123KygzfkdQzNje2B6OvZtCCIEAmImckJ?usp=sharing

Some additional information: I am a beginner in this area, and this is my first time with Tensorflow. This project was originally run on English dataset, I ran it on Chinese dataset, not sure if this change would make a difference.

Looking forward to your reply.

**Comment by sushreebarsa** [comment]
@zjk000 I tried to replicate this issue on colab using TF v2.8.0 and faced a different error .Could you please have a look at this [gist](https://colab.research.google.com/gist/sushreebarsa/b07910afd216c9fcb4c941149741fe84/gist55658.ipynb) and confirm the same? Please let me know if I am missing something to reproduce the issue.
Thanks!

**Comment by zjk000** [comment]
Hi, it was some path issue, I modified the code a little bit, now it should be able to replicate the error, https://drive.google.com/drive/folders/1uNZ4ccKKX2p2yIoL3uH01dQDq07VQMdf?usp=sharing. And can you try again with python 3.8? The default python version of Colab is python 3.7, which may cause some error with pickle.

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to replicate the issue on colab , please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/a8888226f457dd8d53d90ad56e1f4ef1/gist55658.ipynb) for reference.Thanks!

**Comment by sachinprasadhs** [comment]
Hi, Could you please try using Tensorflow 2.9 version. Thanks!

**Comment by zjk000** [comment]
Hi, I tried with Tensorflow 2.9.0, same thing happened. But it's ok, I gave up, I have moved on from this problem, you can close this issue now.

**Comment by sachinprasadhs** [comment]
Thanks for confirming that the issue still exists in 2.9.
Looks like the issue could be from keras, Since development of keras moved to separate repository https://github.com/keras-team/keras/issues

Please post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
