### ISSUE TITLE
hlo-legalize-to-linalg is incorrect for mhlo::DotGeneralOp

### ISSUE THREAD

**Issue by srcarroll** [tensorflow/tensorflow#55652]
The usage of `i` in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/legalize_to_linalg.cc#L2945 and https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/legalize_to_linalg.cc#L2970 is incorrect.  You need another index, say `j` that only increments when `assigned_dims[i]` is false.

Suggested fix
```
      for (int i = 0, j = 0; i < lhs_rank; ++i) {
        if (!assigned_dims[i]) {
          lhs_indices[i] =
              rewriter.getAffineDimExpr(j + lhs_batching_dims.size());
              j++;
        }
      }
```

and similarly for the corresponding loop for RHS map.  Here's a test case

```
func.func @dot_general_2(%arg0: tensor<64x16x128x32xf32>,
                  %arg1: tensor<16x256x32x128xf32>) -> tensor<16x32x64x256xf32> {
  %0 = "mhlo.dot_general"(%arg0, %arg1) {
    dot_dimension_numbers = #mhlo.dot<
      lhs_batching_dimensions = [1, 3],
      lhs_contracting_dimensions = [2],
      rhs_batching_dimensions = [0, 2],
      rhs_contracting_dimensions = [3]
    >,
    precision_config = [#mhlo<"precision DEFAULT">, #mhlo<"precision DEFAULT">],
    someattr
  } : (tensor<64x16x128x32xf32>, tensor<16x256x32x128xf32>) -> tensor<16x32x64x256xf32>
  func.return %0 : tensor<16x32x64x256xf32>
}
// The iterations are (Batch Dim, Batch Dim, LHS Other Dim, RHS Other dim, Contracting Dim)
// CHECK: #[[MAP0:.*]] = affine_map<(d0, d1, d2, d3, d4) -> (d2, d0, d4, d1)>
// CHECK: #[[MAP1:.*]] = affine_map<(d0, d1, d2, d3, d4) -> (d0, d3, d1, d4)>
// Output is the iterators excluding contracting
// CHECK: #[[MAP2:.*]] = affine_map<(d0, d1, d2, d3, d4) -> (d0, d1, d2, d3)>
// CHECK: func @dot_general_2(
// CHECK-SAME: %[[ARG0:.*]]: tensor<64x16x128x32xf32>, %[[ARG1:.*]]: tensor<16x256x32x128xf32>)
// CHECK: %[[INIT:.*]] = linalg.init_tensor [16, 32, 64, 256]
// CHECK: %[[FILL:.*]] = linalg.fill ins(%{{.*}}{{.*}}outs(%[[INIT]]
// CHECK: linalg.generic
// CHECK-SAME: indexing_maps = [#[[MAP0]], #[[MAP1]], #[[MAP2]]]
// Only contracting dims are reductions
// CHECK-SAME: iterator_types = ["parallel", "parallel", "parallel", "parallel", "reduction"]
// CHECK-SAME: ins(%[[ARG0]], %[[ARG1]] : tensor<64x16x128x32xf32>, tensor<16x256x32x128xf32>)
// CHECK-SAME: outs(%[[FILL]] : tensor<16x32x64x256xf32>)
// CHECK-SAME: {someattr}
// CHECK:   ^bb0(%[[ARG2:.*]]: f32, %[[ARG3:.*]]: f32, %[[ARG4:.*]]: f32):
// CHECK:     %[[MUL:.*]] = arith.mulf %[[ARG2]], %[[ARG3]] : f32
// CHECK:     %[[SUM:.*]] = arith.addf %[[MUL]], %[[ARG4]] : f32
// CHECK:     linalg.yield %[[SUM]] : f32
// CHECK: } -> tensor<16x32x64x256xf32>
```

It might be worth considering adding even more test cases, as obviously the current coverage isn't enough.

**Comment by tilakrayal** [comment]
Hello @srcarroll ,
I request you,can you please feel free to submit a PR for the requested change is to be made.Thanks!

**Comment by srcarroll** [comment]
Yes I can do that.  However, the issue is that I need to contribute from my work account which will require some amount of bureaucracy.  This is why I decided to post the fix here, since it's a very small change.  If this can wait, I'd be happy to submit a PR after we get things sorted out.

**Comment by tilakrayal** [comment]
@srcarroll ,
As suggested I request you,can you please feel free to submit a PR for the requested change is to be made.Thanks!

**Comment by srcarroll** [comment]
I have been given the go ahead to do this from my personal account so I will submit a PR soon.

**Comment by srcarroll** [comment]
I submitted a PR here already https://github.com/tensorflow/tensorflow/pull/55722

**Comment by tilakrayal** [comment]
@srcarroll ,
The PR has been assigned for reviewing and once it is merged this issue will move to closed status.Thanks!

**Comment by tilakrayal** [comment]
@srcarroll ,
Related PR has been closed.Can you please feel free to move this issue to closed status.Thanks!
