### ISSUE TITLE
The callbacks in the training functions in kernels_experimental.cc unnecessarily transfer ownership of the tensors to the caller

### ISSUE THREAD

**Issue by PatriceVignola** [tensorflow/tensorflow#55659]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 16.04

### Python version

3.9

### Bazel version

5.1.0

### Current Behaviour?

Currently, the callbacks in the `kernels_experimental.cc` file transfer ownership of the tensors to the caller. Although we explain this behavior in the header, this is not intuitive because the tensors don't need to outlive the callback. A better solution would be to automatically free the tensors as soon as the callback returns, thus avoiding instances where callers could mistakenly omit to free the memory themselves.

### Standlone code to reproduce the issue

```c++
void callback(TF_OpKernelContext* ctx, TF_Tensor* source, TF_Tensor* dest) {
  // We are not releasing the memory for `source` and `dest, so memory leak occurs
}

TF_AssignVariable(ctx, 0, 1, callback, status);
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@PatriceVignola  
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
