### ISSUE TITLE
Inconsistent documentation regarding supported input data type and ParameterServerStrategy

### ISSUE THREAD

**Issue by bli00** [tensorflow/tensorflow#55668]
### Issue Type

Documentation Bug

### Current Behaviour?

There is a direct conflict between the `ParameterServerStrategy` [tutorial doc][1], which states:

```
Keras Model.fit with tf.distribute.ParameterServerStrategy can take input data in the form of a tf.data.Dataset, tf.distribute.DistributedDataset, or a tf.keras.utils.experimental.DatasetCreator, with Dataset being the recommended option for ease of use.
```

And these pages:

* [ParameterServerStrategy][2]:

```
When using Model.fit, tf.distribute.experimental.ParameterServerStrategy must be used with a tf.keras.utils.experimental.DatasetCreator, and steps_per_epoch must be specified.
```

* [Distributed Input][3]:

```
Users of tf.distribute.experimental.ParameterServerStrategy with the Model.fit API need to use a tf.keras.utils.experimental.DatasetCreator as the input
```

* [Model.fit][4]:

```
If using tf.distribute.experimental.ParameterServerStrategy, only DatasetCreator type is supported for X
```

**The former recommends using `Dataset` while the latter explicitly states only `DatasetCreator` is supported.**

[1]: https://www.tensorflow.org/tutorials/distribute/parameter_server_training#input_data
[2]: https://www.tensorflow.org/api_docs/python/tf/distribute/experimental/ParameterServerStrategy
[3]: https://www.tensorflow.org/tutorials/distribute/input
[4]: https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit

**Comment by sushreebarsa** [comment]
@bli00 
In order to expedite the trouble-shooting process, could you provide more information on this issue ?
Thanks!
