### ISSUE TITLE
Android - Does not encode a valid TensorFlow Lite model.

### ISSUE THREAD

**Issue by ahmadbajwa8282** [tensorflow/tensorflow#55679]
Previously I was using TensorFlowInferenceInterface to read the model. but I was facing a lot of crashes. As per one of the moderator's recommendation, i replaced the method with the following:

**Code:**
```
 private var sTFInterface: Interpreter? = null
 private const val MODEL_FILE = "file:///android_asset/auto.pb"

sTFInterface = Interpreter(File(MODEL_FILE))
```
But now i see a very strange error and it is unable to read tensorflowlite model. Still "abort" crashes are on spike.

**Error:**
> java.lang.IllegalArgumentException: Contents of /file:/android_asset/auto.pb does not encode a valid TensorFlow Lite model: Could not open '/file:/android_asset/auto.pb'.
> The model allocation is null/empty

Please help

Attached model:
[auto.pb.zip](https://github.com/tensorflow/tensorflow/files/8520578/auto.pb.zip)

**Comment by mohantym** [comment]
Hi @ahmadbajwa8282 ! You should use the below command to convert frozen graph files to tflite . 
```
 converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
  graph_def_file, input_arrays, output_arrays)
tflite_model = converter.convert()
```
But I recommend creating the model in V2 api's and load TF 2.x Lite converter to load the model and convert it smoothly. 
Attaching [TF 1.x Lite converter ](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/lite/TFLiteConverter), [2.x Lite converter ](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter#from_saved_model)guide  for reference.

Thanks!
