### ISSUE TITLE
tf.quantization.fake_quant_with_min_max_vars crashes

### ISSUE THREAD

**Issue by MThalberg** [tensorflow/tensorflow#55688]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

n/a

### Python version

3.9

### Bazel version

n/a

### GCC/Compiler version

n/a

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current Behaviour?

```shell
Session crashes when run the code below.
The code is buggy in that the argument `min_value` and `max_value` of `tf.quantization.fake_quant_with_min_max_vars` should be scalars instead of tensors of shape `(2,)`.
However, we expect the buggy code to be handled with `Exception` instead of just crashes.
```

### Standlone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
input_data = np.random.rand(1,3,3,2).astype(np.float32)
min_value = tf.constant([0.0, -1.0], dtype=tf.float32)
max_value = tf.constant([1.0, 0.0], dtype=tf.float32)
input_tensor = tf.constant(input_data)
output = tf.quantization.fake_quant_with_min_max_vars(input_tensor, min_value, max_value)
```

### Relevant log output

```shell
abort (core dumped)
```
</details>

**Comment by tilakrayal** [comment]
Hello @MThalberg ,
I request you please take a look at this issue #46910 where a similar issue has been raised and it is still open. Can you please follow that issue, since it is already being tracked there? Thanks!

**Comment by MThalberg** [comment]
Thank for pointing to the other issue and indeed it is the same bug. I will close this issue.
