### ISSUE TITLE
Attempt to create quantized tf.constant results in a TypeError

### ISSUE THREAD

**Issue by b0noI** [tensorflow/tensorflow#5568]
### Environment info
Operating System:
MacOS 10.12.1

1. The commit hash (`git rev-parse HEAD`)
f794cd393b1e7821fcc3cdcee9b6a4400f2540bf
2. The output of `bazel version`
Build label: 0.3.1-homebrew
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Sep 27 03:15:13 2016 (1474946113)
Build timestamp: 1474946113
Build timestamp as int: 1474946113

### Repro code
```python
import tensorflow as tf

sess = tf.Session()
with sess.as_default():
     m = tf.constant(3, dtype=tf.qint8)
     print(m.eval())
```
#### result:
```bash
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/b0noI/src/tensorflow/_python_build/tensorflow/python/framework/constant_op.py", line 163, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/Users/b0noI/src/tensorflow/_python_build/tensorflow/python/framework/tensor_util.py", line 354, in make_tensor_proto
    nparray = np.array(values, dtype=np_dt)
TypeError: expected a readable buffer object
```

**Comment by b0noI** [comment]
working on PR

**Comment by sherrym** [comment]
Thanks, @b0noI .

**Comment by b0noI** [comment]
turns out that the root cause of the issue is in the way how quantized Tensors are represented. It is expected that they always will have a tuple as the representation for each of an element. On practice this leads to the inconsistent API like the next one:
```
m = tf.constant(3, dtype=tf.int8) # Evaluates correctly since the type of the tensor is not quantized.
m = tf.constant(3, dtype=tf.qint8) # Throws TypeError since the tensor is a quantized tensor, but the element in the tensor is not tuple.
m = tf.constant((3,), dtype=tf.qint8) # Evaluates correctly since element in the tensor is a tuple.
```

Current representation of the type of elements of a quantized Tensor described by following DTypes:
```
_np_qint8 = np.dtype([("qint8", np.int8, 1)])
_np_quint8 = np.dtype([("quint8", np.uint8, 1)])
_np_qint16 = np.dtype([("qint16", np.int16, 1)])
_np_quint16 = np.dtype([("quint16", np.uint16, 1)])
_np_qint32 = np.dtype([("qint32", np.int32, 1)])
```

One of the possible solutions would be to refactor the sanity checks for the input arguments. Current sanity check assumes that quantized Tensor has same sanity checks as non-quantized Tensor:
```
 dtypes.qint16: _FilterInt,
 dtypes.qint32: _FilterInt,
 dtypes.qint8: _FilterInt,
 dtypes.quint16: _FilterInt,
```

PS: Still working on PR to show the proposal of new sanity checks.

**Comment by b0noI** [comment]
done.
