### ISSUE TITLE
TFLite Tensor name converted by 2.7.0 is much longer than 1.14.0

### ISSUE THREAD

**Issue by jelly0o0** [tensorflow/tensorflow#55698]
### System information

-   **OS Platform and Distribution**: Linux Ubuntu 18.04
-   **Mobile device**: No
-   **TensorFlow installed from (source or binary)**: binary, pip install tensorflow==2.7.0
-   **TensorFlow version**: 2.7.0
-   **Python version**: 3.8.13
-   **Bazel version (if compiling from source)**: None
-   **GCC/Compiler version (if compiling from source)**: None
-   **CUDA/cuDNN version**: None
-   **GPU model and memory**: None
-   **Exact command to reproduce**: None

### Describe the problem
Using tensorflow 1.14.0 convert .pb model to tflite as follows:
```python
import tensorflow as tf

graph_def_file = '/path/to/mobilenet_v1.pb'
input_arrays = ['input']
output_arrays = ['MobilenetV1/Predictions/Reshape_1']
input_shapes = {'input': [1, 224, 224, 3]}

convert = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays, input_shapes)
tflite_model = convert.convert()
with open('mobilenet_v1_tf1.14.tflite', 'wb') as f:
    f.write(tflite_model)
```

After update tensorflow to 2.7.0 and modify scripts as follows:
```python
import tensorflow as tf

graph_def_file = '/path/to/mobilenet_v1.pb'
input_arrays = ['input']
output_arrays = ['MobilenetV1/Predictions/Reshape_1']
input_shapes = {'input': [1, 224, 224, 3]}

convert = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays, input_shapes)
tflite_model = convert.convert()
with open('mobilenet_v1_tf2.7.tflite', 'wb') as f:
    f.write(tflite_model)
```
I found tensor name in `mobilenet_v1_tf2.7.tflite` is much longer than `mobilenet_v1_tf1.14.tflite`. Such a long name caused a lot of trouble when comparing the tflite model with the original model.

However, I also noticed that there will be a new `Attributes` in TFLiteConverter.
```python
convert = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays, input_shapes)
convert.experimental_new_convert = False
tflite_model = convert.convert()
```
But the log as follows warning me that old converter is deprecated:
```shell
WARNING:absl:Please consider switching to the new converter by setting experimental_new_converter=True. The old converter (TOCO) is deprecated.
```
Is is possible to add an attribute in the new version, so that the model conversion name can remain unchanged, and the tensor of folder const can be removed.

**Comment by mohantym** [comment]
Hi @jelly0o0 ! I could not see any difference between the names of tensors from lite files procured from 1.x converter and 2.x converter . Could you post a gist to reproduce the issue? Attaching gist in [1.14 ](https://colab.sandbox.google.com/gist/mohantym/d03b95a958aa2f04fb27f011f79aaa98/tflite.ipynb#scrollTo=v5Zf6G4M-sZz)and [2.8](https://colab.sandbox.google.com/gist/mohantym/4a880ccc5b166fb88b6c1c2a24320165/tflite.ipynb#scrollTo=iE0vSfMXumKI)  for reference.

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue . It is replicating in 2.6.3, 2.7,2.8 and nightly . Attaching gist in [2.6.3](https://colab.sandbox.google.com/gist/mohantym/98f72e5020c3fe782b955b1e98044a6d/git_55698.ipynb#scrollTo=51fXm32GRRcW), [2.7 ](https://colab.sandbox.google.com/gist/mohantym/305e1852d26695e68c995237edd4ca7c/git_55698.ipynb#scrollTo=9HSfKDlvP_hv), [2.8](https://colab.sandbox.google.com/gist/mohantym/96810976a69114e251415266bfb5a36f/git_55698.ipynb#scrollTo=51fXm32GRRcW) and [nightly](https://colab.sandbox.google.com/gist/mohantym/a03eed58f8e8f57ec1e368f462a80c47/git_55698.ipynb#scrollTo=51fXm32GRRcW) for reference.  Thank you!

**Comment by pjpratik** [comment]
I was able to reproduce the issue in TF 2.11 and observed the same in [netron.app](https://netron.app/). Please find the gist [here](https://colab.sandbox.google.com/gist/pjpratik/99bcced02c6966c9cdd3a08b2b8df599/55698.ipynb). Thank you.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
