### ISSUE TITLE
Python 3 Builds in CI are failing

### ISSUE THREAD

**Issue by gunan** [tensorflow/tensorflow#5569]
All our python 3 builds for pull requests on our CI are failing with the following error:
```
ERROR: /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/external/bazel_tools/tools/build_defs/pkg/BUILD:44:1: Converting to Python 3: external/bazel_tools/tools/build_defs/pkg/build_tar.py failed: 2to3 failed: error executing command 
  (cd /var/lib/jenkins/workspace/tensorflow-pull-requests-cpu-python3/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/workspace && \
  exec env - \
  bazel-out/host/bin/external/bazel_tools/tools/python/2to3 --no-diffs --nobackups --write --output-dir bazel-out/host/genfiles/python3/external/bazel_tools/tools/build_defs/pkg --write-unchanged-files external/bazel_tools/tools/build_defs/pkg/build_tar.py): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
```

It seems to be independent of the PR we are testing, and the error message above does not really makes sense. @damienmg , could you help us decode the above error
@benoitsteiner , who is running into this problem.

**Comment by damienmg** [comment]
I need to see more of the output but the problem is coming from depending on @bazel_tools//tools/build_defs/pkg:build_tar which is not py3 compatible and we do not have 2to3 in bazel (we should fix both on bazel side ultimately).

Anyway how is it used?

**Comment by gunan** [comment]
This is happening during testing of PRs #5560 and #5565 
I think one of the changes we made internally is causing an issue with the build.
Here are some build logs, the latter has slightly more information:

https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu-python3/2171/consoleFull
https://ci.tensorflow.org/job/tensorflow-pull-requests-cpu-python3/2172/consoleFull

**Comment by damienmg** [comment]
Can this be bisected? There is a lot of changes in that PR...

**Comment by gunan** [comment]
Found the culprit, it is a new pkg_tar rule.
Are there corresponding issues for the py3 compatilibility of build_tar on bazel side?
Or would you like to keep this open to track that?

**Comment by damienmg** [comment]
I'll follow up on this one.

We need to remove pkg_tar from bazel repository (much like other rules) so
I'll take the action there.
