### ISSUE TITLE
Tensorflow works in command line ipython but not in ipython notebook

### ISSUE THREAD

**Issue by xslittlegrass** [tensorflow/tensorflow#5570]
This is a setup issue. Tensorflow works in ipython command line but not in ipython notebook. When import in ipython notebook, I get error:

```
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by /usr/local/packages/python/2.7.10-anaconda/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so)


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

This is possibly related to https://github.com/tensorflow/tensorflow/issues/5141.
Screenshots of the problem is in http://stackoverflow.com/q/40569279/1363677

### Environment info
Operating System:

Red Hat Enterprise Linux Server release 6.4 (Santiago)
`Linux qb2 2.6.32-358.23.2.el6.x86_64 #1 SMP Sat Sep 14 05:32:37 EDT 2013 x86_64 x86_64 x86_64 GNU/Linux`

Installed version of CUDA and cuDNN: 

```
-rw-r--r-- 1 root root  189170 Oct 11 10:13 libcudadevrt.a
lrwxrwxrwx 1 root root      16 Oct 11 10:13 libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root      19 Oct 11 10:13 libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root  311596 Oct 11 10:13 libcudart.so.7.5.18
-rw-r--r-- 1 root root  558020 Oct 11 10:13 libcudart_static.a
lrwxrwxrwx 1 root root      17 Oct 11 10:13 libcuinj32.so -> libcuinj32.so.7.5
lrwxrwxrwx 1 root root      20 Oct 11 10:13 libcuinj32.so.7.5 -> libcuinj32.so.7.5.18
-rwxr-xr-x 1 root root 5396088 Oct 11 10:13 libcuinj32.so.7.5.18
```

```
python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so.5.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.7.5 locally
0.11.0rc0
```

I'm not sure whether this is relevant, but my ipython kernel is on a remote machine, and the notebook interface is on my local machine. The ipython kernel is started using

`[user@remote ~]$ ipython notebook --no-browser --port=8889`

Then at my local machine, I set up the port forwarding as

`[user@local ~]$ ssh -N -L localhost:8888:localhost:8889 remote`

And the notebook interface is started from the browser at localhost:8888

@drpngx

**Comment by xslittlegrass** [comment]
The system is Red Hat Enterprise Linux Server release 6.4.

I tried Yarosalv's answer to use `/usr/local/packages/python/2.7.10-anaconda/bin/ipython notebook` but it doesn't work for me.

I'm using `anaconda`, but there is only one root environment. From the  error message it seems that the ipython is correctly configured to use anaconda python. Moreover, tensorflow works fine for me in the terminal in ipython, it just breaks in the notebook interface.

**Comment by zafartahirov** [comment]
There was a [problem](https://github.com/ContinuumIO/anaconda-issues/issues/483) in Anaconda that might be related. 

Also, if you see this problem during the build, make sure your [`LD_LIBRARY_PATH`](https://gcc.gnu.org/onlinedocs/libstdc++/faq.html#faq.how_to_set_paths) is set correctly.
Another thing, could you, please, provide the output of the `strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX` - just to check the required version is installed

You could also replace the anaconda's `libstdc++.so.6` with the symlink from the OS. I am not sure where anaconda stores its environments. Make sure you backup though

**Comment by xslittlegrass** [comment]
Indeed it's the problem of `LD_LIBRARY_PATH`. I reported the problem to my system administrator, and he offered a solution that works:

`module load gcc`

Comparing before and after loading gcc, the `LD_LIBRARY_PATH` does change. After loading the module, the following paths have been prepended to the PATH.

/usr/local/compilers/gcc/4.9.0/lib/gcc/x86_64-unknown-linux-gnu/4.9.0
/usr/local/compilers/gcc/4.9.0/lib64
/usr/local/compilers/gcc/4.9.0/lib
