### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not GFile

### ISSUE THREAD

**Issue by kofimokome** [tensorflow/tensorflow#55703]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### OS Platform and Distribution

MacOS 10.15.7

### Python version

3.7

### Current Behaviour?

```shell
Whenever I try to load any TensorFlow model, I get this error TypeError: expected str, bytes or os.PathLike object, not GFile

Loading the model on google collab works without any error. I don't know if it is an OS-specific issue.
I have searched online and I have not seen a case like mine. Please can you help me?
```

### Standalone code to reproduce the issue

```shell
1. Open this google colab https://colab.research.google.com/drive/1gGEk8s2c4H_dHUn5GBPrit1mtTsS4bor?usp=sharing
2. Download the model test.h5
3. Import the model in your code 
  
import tensorflow as tf

model = tf.keras.models.load_model('test.h5')
```

### Relevant log output
```shell
(tf) kofi@Kofis-MacBook-Pro Masters Research % python main.py dataset/mypaperdataset.mp4 -d
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    eyes_model = tf.keras.models.load_model('test.h5')
  File "/Users/kofi/opt/anaconda3/envs/tf/lib/python3.7/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/kofi/opt/anaconda3/envs/tf/lib/python3.7/site-packages/h5py/_hl/files.py", line 309, in __init__
    name = filename_encode(name)
  File "/Users/kofi/opt/anaconda3/envs/tf/lib/python3.7/site-packages/h5py/_hl/compat.py", line 111, in filename_encode
    filename = fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not GFile

```
_No response_</details>

**Comment by tilakrayal** [comment]
@kofimokome ,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here.Thanks!

**Comment by kofimokome** [comment]
I have updated the description

**Comment by tilakrayal** [comment]
Hello @kofimokome ,
I have able to execute the given code without any issue.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/02d1c6265a222ab05356fa996f3cc51d/55703.ipynb).I request can you please create a virtual environment and test your code again. It helps. Thanks!

**Comment by kofimokome** [comment]
I finally saved the model without the .h5 extension and it works now. I don't know why models with .h5 do not work.

**Comment by tilakrayal** [comment]
@kofimokome ,
Could you please confirm if the issue is resolved. if yes, please feel free to move this issue to closed status.Thanks!

**Comment by kofimokome** [comment]
The issue has not been resolved. But I found an alternative method to save the model
