### ISSUE TITLE
Python Linux 3.10 CPU-only wheel not found

### ISSUE THREAD

**Issue by brammerc** [tensorflow/tensorflow#55701]
### Describe the problem
[Link](https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.8.0-cp310-cp310-manylinux2010_x86_64.whl) to **Python Linux 3.10 CPU-only** is not found.

**Comment by chunduriv** [comment]
@brammerc,

Thank you for reporting.

**Comment by chunduriv** [comment]
@brammerc,

`TF2.8.1` is released.  Please can you try to use 2.8.1 wheel https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.8.1-cp310-cp310-manylinux2010_x86_64.whl

Thank you.
