### ISSUE TITLE
The tflite model has a custom layer and cannot achieve variable-length input

### ISSUE THREAD

**Issue by 980202006** [tensorflow/tensorflow#55709]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

tf 2.5

### Custom Code

Yes

### OS Platform and Distribution

ubuntu 20.04

### Python version

3.7

### Current Behaviour?

```shell
A bug happened!I tried the steps as https://github.com/tensorflow/tensorflow/issues/24607, but the input shape of the interpreter is still fixed. The model has two custom layers.
```

### Standalone code to reproduce the issue

```shell
with tf.io.gfile.GFile('model.tflite', 'wb') as f:
    f.write(tflite_model)
    
interpreter = tf.lite.Interpreter(model_path='model.tflite')
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @980202006 ! Could you provide a stand alone to reproduce the issue? I could not replicate above issue though with the above code snippet. Attaching [gist](https://colab.sandbox.google.com/gist/mohantym/ce196d39aa65ed08103d38bb6a5400b1/git_55709.ipynb) for reference. Thanks!

**Comment by 980202006** [comment]
Thank you!
https://colab.research.google.com/drive/1LboEAoyuCD8di5PsdDrcPV0DwUu_YySQ?usp=sharing
The original input of the model has two None, but after converting to tflite, they both become 1. Is it possible to save variable-length input in tflite instead of resizeinput in java.
![image](https://user-images.githubusercontent.com/24452502/165018695-2d158b46-0f02-4a0a-9069-77e55116f395.png)
![image](https://user-images.githubusercontent.com/24452502/165018717-add5aba3-1c0e-4305-92fa-01ed40b596ca.png)

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue? Attaching Gist in [2.5 ](https://colab.sandbox.google.com/gist/mohantym/da0e2a403d66446fb9ed0d64596fee5b/untitled2.ipynb#scrollTo=FLnSmM052LU2) and [2.8](https://colab.sandbox.google.com/gist/mohantym/f5f0d84a86524eafd27db6497de37934/untitled2.ipynb#scrollTo=GA9VU2ku44Qk) for reference. Thanks!

**Comment by karimnosseir** [comment]
The inputs can be resized and the none are converted to '-1' as expected and you can resize the input.

Example
```
[{'name': 'serving_default_input_1:0', 'index': 0, 'shape': array([  1, 128,   1,   1], dtype=int32), 'shape_signature': array([ -1, 128,  -1,   1], dtype=int32),
```
shape_signature is the part that identify which dimensions can be resized.

**Comment by karimnosseir** [comment]
Sorry closed by mistake.

**Comment by karimnosseir** [comment]
Now the issue is that it fails after resizing

**Comment by pjpratik** [comment]
I was able to reproduce this issue with TF 2.11. Please find the gist [here](https://colab.sandbox.google.com/gist/pjpratik/a75492e66214db2fee0798389f4a43f6/55709.ipynb). Thank you.

**Comment by pkgoogle** [comment]
Hi @980202006, we actually don't support dynamic shapes: https://www.tensorflow.org/lite/guide/inference#run_inference_with_dynamic_shape_model. If you have no more open items, please feel free to close as not planned.

**Comment by 980202006** [comment]
Thank you!
