### ISSUE TITLE
Non-OK-status: tensorflow::Env::Default()->DeleteFile(ptx_path) status: Permission denied

### ISSUE THREAD

**Issue by Gandalf401** [tensorflow/tensorflow#55717]
### System information
Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-74-generic x86_64)
TensorFlow 2.0.0 installed by anaconda
gcc (Ubuntu 8.4.0-3ubuntu2) 8.4.0
NVIDIA-SMI 460.80 Driver Version: 460.80 CUDA Version: 11.2 (10.1 installed in fact)

### Describe the problem
When I am running with my tensorflow program, it seems that when it meets some conditions, my program turns out to crash like below, and then I found my root directory has become read-only. But it doesn't happen by accident, for I have repaired my disk with e2fsck for times, but when the same things happened, everything repeated.
Every time the same things happened, new files would appear in the working directory, more details are presented as below:
![1](https://user-images.githubusercontent.com/94270103/164766755-974a2e93-d4a9-4d40-a9f6-9965c1600e83.png)
![2](https://user-images.githubusercontent.com/94270103/164766731-d8cc25d5-2e43-4f9c-b816-f6a9670c0331.png)
I am not sure whether my disk caused the error of my program or the program just caused the disk error.
Logs and part of my code are presented below, thanks for your support!
### Source code / logs
![3](https://user-images.githubusercontent.com/94270103/164767903-10f30ba7-d436-44ac-b186-ce8f89ed1edc.png)
![image](https://user-images.githubusercontent.com/94270103/164768296-173dd2d0-cedc-4510-a8b1-9ae29289c3d6.png)
I use more than one DL framework in my program, and other frameworks seem still work.

**Comment by tilakrayal** [comment]
Hello @Gandalf401 ,
We see that you are using tf version 2.0, which is not actively supported,I request, please update to latest stable version2.8 from [here](https://www.tensorflow.org/install) and let us know if you are facing same issue.Thanks!
