### ISSUE TITLE
TPU Execution Failure

### ISSUE THREAD

**Issue by mosicr** [tensorflow/tensorflow#55713]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

tf 2.6

### Custom Code

Yes

### Mobile device

20.04.1 Ubuntu SMP

### Python version

Python 3.8.10

### Current Behaviour?

```shell
Trying to get Waymo Occupancy Flow Tutorial https://github.com/waymo-research/waymo-open-dataset/blob/master/tutorial/tutorial_occupancy_flow.ipynb
 to run on TPU. It works on CPU, but when I modify code for TPU execution it fails.
```

### Standalone code to reproduce the issue

```shell
162 with strategy.scope():
163     model_inputs = _make_model_inputs(timestep_grids, vis_grids)
164     model = _make_model(model_inputs=model_inputs, config=config)
```

### Relevant log output

```shell
58562022-04-22 10:58:53.161278: I tensorflow/core/tpu/graph_rewrite/encapsulate_tpu_computation\
    s_pass.cc:263] Subgraph fingerprint:7296879430535566001
58572022-04-22 10:58:54.520719: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:801] mo\
    del_pruner failed: Invalid argument: Graph does not contain terminal node Adam/Adam/AssignA\
    ddVariableOp.
```
</details>

**Comment by mosicr** [comment]
[occup5.zip](https://github.com/tensorflow/tensorflow/files/8554299/occup5.zip)
Hi, 
I am not executing in Colab. I am running it on TPU VM. I put it all in one python file. If TPU related statements are omitted, it runs ok ( trains on CPU ). But if I add TPU related statements ( strategy.scope, @tf.function decorator , etc ), it blows up / doesn't start training. 

This version fails with:
2252  File "occup5.py", line 367, in <module>
2253    loss_value = train_step(inputs)
2254  File "occup5.py", line 354, in train_step
2255    optimizer.apply_gradients(zip(grads, model.trainable_weights))
2256  File "/usr/local/lib/python3.8/dist-packages/keras/optimizer_v2/optimizer_v2.py", line 62\
    8, in apply_gradients
2257    self._create_all_weights(var_list)
2258  File "/usr/local/lib/python3.8/dist-packages/keras/optimizer_v2/optimizer_v2.py", line 81\
    5, in _create_all_weights
2259    self._create_slots(var_list)
2260  File "/usr/local/lib/python3.8/dist-packages/keras/optimizer_v2/adam.py", line 117, in _c\
    reate_slots
2261    self.add_slot(var, 'm')
2262  File "/usr/local/lib/python3.8/dist-packages/keras/optimizer_v2/optimizer_v2.py", line 89\
    2, in add_slot
2263    raise ValueError(
2264ValueError: Trying to create optimizer slot variable under the scope for tf.distribute.Stra\
    tegy (<tensorflow.python.distribute.tpu_strategy.TPUStrategyV2 object at 0x7fed71b7aca0>), \
    which is different from the scope used for the original variable (<tf.Variable 'conv1_conv/\
    kernel:0' shape=(7, 7, 23, 64) dtype=float32, numpy=
    array([[[[ 7.60472193e-03,  1.16682872e-02,  6.13643974e-03

**Comment by tilakrayal** [comment]
@chunduriv ,
I was facing different error while executing the code.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/05fe48e38ed84cecbff822c1f4cf37fb/55713.ipynb).

**Comment by mosicr** [comment]
Hi,
Your dataset is empty. You need to copy at least one tfrecord to local location.

**Comment by chunduriv** [comment]
@mosicr,

To replicate the above issue, can you please share all required data files like `training_tfexample`, `validation_scenario_ids.txt`, `testing_scenario_ids.txt`, `validation.tfrecord` etc.

If possible, please feel free to share colab gist of TPU and CPU execution. Thank you!

**Comment by mosicr** [comment]
Hi, 
This is the input file location: 
gs://waymo_open_dataset_motion_v_1_1_0/uncompressed/tf_example/training/training_tfexample.tfrecord-00000-of-01000
The rest of files ( scenario_ids etc ) are not used , you can safely disregard. 
Please find attached CPU exec log. 
TPU exec fails in various modalities depending on what code change I introduce. I mostly played with strategy.scope and tf.function placement. 
[occup.zip](https://github.com/tensorflow/tensorflow/files/8620422/occup.zip)
( occup.zip file is the original code and execution log). 
[occup5.zip](https://github.com/tensorflow/tensorflow/files/8620495/occup5.zip)
occup5.zip is an example of TPU modification and execution.
It seems significant rewrite is needed to run this logic on TPU; simple tf.function decorator won't do.

**Comment by chunduriv** [comment]
@mosicr,

The given `tf record` input file is available in google storage which we are unable to access.To reproduce the issue, can you please attach the tf record file here. So that we can download and try to replicate the issue in our local environment.Thanks!

**Comment by mosicr** [comment]
Hi,
TF record is 500M, can't upload to github compressed. I enabled public access to 
gs://avwaymo/training_tfexample.tfrecord-00000-of-01000
You should be able to download from the Google Cloud ( gsutil cp gs://avwaymo/training_tfexample.tfrecord-00000-of-01000 . ); or perhaps use GCP Storage Browser and download the file .

**Comment by jszaday** [comment]
> ValueError: Trying to create optimizer slot variable under the scope for tf.distribute.Strategy, which is different from the scope used for the original variable

A potential solution to this error may be consolidating model compilation and optimizer creation under `strategy.scope()`:

```
strategy = ...

with strategy.scope():
    optimizer = tf.keras.optimizers.Adam(learning_rate=1e-3)
    model_inputs = _make_model_inputs(timestep_grids, vis_grids)
    model = _make_model(model_inputs=model_inputs, config=config)
    model.compile(optimizer=optimizer)
```

Then, you should be able to train with:

```
num_steps_to_train = 11
step = 0
while step < num_steps_to_train:
  # Iterate over batches of the dataset.
  inputs = next(it)
  loss_value = strategy.run(tf.function(train_step), (inputs,))

  # Log every 10 batches.
  if step % 10 == 0:
    float_loss = float(loss_value)
    print(f'Training loss after step {step}: {float_loss:.4f}')

  step += 1
```

You can try making these changes from a "clean" copy of `tutorial_occupancy_flow.ipynb`.
