### ISSUE TITLE
Tensorflow 2.8.0 Limiting GPU memory growth fails.

### ISSUE THREAD

**Issue by lk1983823** [tensorflow/tensorflow#55710]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 16.04

### Python version

3.7.6

### CUDA/cuDNN version

CUDA 11.3.1 cuDNN 8.2.1

### Current Behaviour?

```shell
My GPU card is Nivida RTX 2080Ti. Follow the GPU usage instruction on the website, I want to limit my gpu memory growth during a HMC test and use the code as follows:
'''
import tensorflow as tf
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  # Restrict TensorFlow to only allocate 1GB of memory on the first GPU
  try:
    tf.config.experimental.set_virtual_device_configuration(
        gpus[0],
        [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)])
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
import jax
import jax.numpy as jnp
import matplotlib.pyplot as plt

# from colabtools import adhoc_import
from contextlib import ExitStack

ADHOC = True
CLIENT = 'fig-export-fig_tree-change-451-3e0a679e9746'

import tensorflow_probability.substrates.jax as tfp
from fun_mc import using_jax as fun_mc
tfd = tfp.distributions



dist = tfd.Normal(0., 1.)
n_chains = 1024
n_super_chains = 4
n_steps = 100
n_sub_chains = n_chains // n_super_chains

def target_log_prob_fn(x):
  return dist.log_prob(x), ()


def kernel(hmc_state, seed):
  hmc_seed, seed = jax.random.split(seed)
  hmc_state, hmc_extra = fun_mc.hamiltonian_monte_carlo_step(
      hmc_state,
      target_log_prob_fn=target_log_prob_fn,
      step_size=0.5,
      num_integrator_steps=1,
      seed=hmc_seed)
  return (hmc_state, seed), (hmc_state.state, hmc_extra.is_accepted)



init_x=dist.sample([n_chains], seed=jax.random.PRNGKey(1))

_, (chain, is_accepted) = fun_mc.trace((fun_mc.hamiltonian_monte_carlo_init(init_x,
    target_log_prob_fn), jax.random.PRNGKey(1)), kernel, 1000)

init_x2 = dist.sample([n_super_chains], seed=jax.random.PRNGKey(3))
init_x2 = jnp.repeat(init_x2, n_sub_chains)
#init_x2 = dist.sample([num_chains], seed=jax.random.PRNGKey(3))
init_x2 = init_x2.reshape([n_super_chains, n_sub_chains])

_, (chain2, is_accepted2) = fun_mc.trace((fun_mc.hamiltonian_monte_carlo_init(init_x2,
    target_log_prob_fn), jax.random.PRNGKey(3)), kernel, 1000)

chain = jnp.concatenate([init_x[jnp.newaxis], chain], 0)
chain2 = jnp.concatenate([init_x2[jnp.newaxis], chain2], 0)
'''
```

### Standalone code to reproduce the issue

```shell
However, I find it failed to control my gpu usage and the code use all the memory in GPU 0. I want to know how to make the limitation works. Thank you !
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@lk1983823 Thank you for raising this issue!
In order to expedite the trouble-shooting process, please provide a complete code snippet to reproduce the issue reported here. 
I tried to reproduce this [issue](https://colab.research.google.com/gist/sushreebarsa/bd3e9c836c73063a58f90f8384d770f8/55710.ipynb) and faced different errors.
Thanks!

**Comment by lk1983823** [comment]
> @lk1983823 Thank you for raising this issue! In order to expedite the trouble-shooting process, please provide a complete code snippet to reproduce the issue reported here. I tried to reproduce this [issue](https://colab.research.google.com/gist/sushreebarsa/bd3e9c836c73063a58f90f8384d770f8/55710.ipynb) and faced different errors. Thanks!

This code import a local file named "fun_mc" in "from fun_mc import using_jax as fun_mc". How can I make this work on colab?
The file can also be downloaded from "https://github.com/tensorflow/probability/tree/main/spinoffs/fun_mc/fun_mc".
And the code above can be found here: https://github.com/lk1983823/google-research/blob/master/nested_rhat/Nested_R_hat.ipynb

**Comment by lk1983823** [comment]
@sushreebarsa 
This code import a local file named "fun_mc" in "from fun_mc import using_jax as fun_mc". How can I make this work on colab?
The file can also be downloaded from "https://github.com/tensorflow/probability/tree/main/spinoffs/fun_mc/fun_mc".
And the code above can be found here: https://github.com/lk1983823/google-research/blob/master/nested_rhat/Nested_R_hat.ipynb

**Comment by lk1983823** [comment]
@sushreebarsa I have updated the code in the colab you offered. Can you find it?

**Comment by sushreebarsa** [comment]
@chunduriv I was able to replicate the issue on colab ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/64325ff384fd6af70f6921ce802b23db/55710.ipynb) for reference.
Thanks!

**Comment by gowthamkpr** [comment]
@lk1983823 Please go through this [doc](https://www.tensorflow.org/guide/gpu) especially, this [part](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) where you can hardcode the limit.

Here's the example code:
`gpus = tf.config.list_physical_devices('GPU')
if gpus:
  # Restrict TensorFlow to only allocate 1GB of memory on the first GPU
  try:
    tf.config.set_logical_device_configuration(
        gpus[0],
        [tf.config.LogicalDeviceConfiguration(memory_limit=1024)])
    logical_gpus = tf.config.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Virtual devices must be set before GPUs have been initialized
    print(e)`

Thanks!
