### ISSUE TITLE
Inconsistent keras model saving and loading

### ISSUE THREAD

**Issue by 980202006** [tensorflow/tensorflow#55727]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.5

### Custom Code

Yes

### OS Platform and Distribution

ubuntu 20.04

### Python version

3.7

### Current Behaviour?

```shell
A bug happened!
I can load and save model parameters through save_weight, but after saving the model with save, load the model and inference, the following error is reported.
ValueError: Dimension 1 in both shapes must be equal, but are 127 and 45. Shapes are [1,127] and [1,45]. for '{{node concat}} = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32](inputs, inputs_1, concat/axis)' with input shapes: [1,127,128], [1,45,128], [] and with computed input tensors: input[2] = <2>.
```

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1AdwLdKwxIBJI_qqAGJOGhHU4WDyjilyT#scrollTo=0DU8b93Twd7i&uniqifier=1
```

### Relevant log output

```shell
InvalidArgumentError: Exception encountered when calling layer "concatenate" (type Concatenate).

ConcatOp : Dimension 1 in both shapes must be equal: shape[0] = [1,127,128] vs. shape[1] = [1,45,128] [Op:ConcatV2] name: concat

Call arguments received:
  • inputs=['tf.Tensor(shape=(1, 127, 128), dtype=float32)', 'tf.Tensor(shape=(1, 45, 128), dtype=float32)']
```
</details>

**Comment by 980202006** [comment]
https://colab.research.google.com/drive/1AdwLdKwxIBJI_qqAGJOGhHU4WDyjilyT?usp=sharing

**Comment by tilakrayal** [comment]
I was able to reproduce the issue in tf [v2.7](https://colab.research.google.com/gist/tilakrayal/beeb742d5ed5ae5a70440d2127efc3e3/55727-2-7.ipynb), [v2.8](https://colab.research.google.com/gist/tilakrayal/0d4a11ef7d5c843668d9cb79800d5362/55727-2-8.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/b96be439672b47e14c5d15b7a2c3e843/55727-nightly.ipynb).Please find the attached gist.
