### ISSUE TITLE
Flatbuffer 2.0.X support

### ISSUE THREAD

**Issue by hmaarrfk** [tensorflow/tensorflow#55740]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.7 but i think 2.8 as well

### Custom Code

Yes

### OS Platform and Distribution

Conda-forge Liux

### Python version

Any

### Bazel version

4

### GCC/Compiler version

10

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### Current Behaviour?

```shell
It seems that some permutations of VerifyField have been removed from flatbuffers 2.0.X.

We were able to build conda-forge tensorflow with flatbuffers 2.0.0 but in some update we hit the bug. I'm attempting to build with 2.0.0 while the issue is resolved.

 https://github.com/Qengineering/TensorFlow_Lite_Pose_RPi_64-bits/issues/3
```

### Standalone code to reproduce the issue

```shell
https://github.com/conda-forge/tensorflow-feedstock/pull/218
```

### Relevant log output
[79-broken_flatbuffers.txt](https://github.com/tensorflow/tensorflow/files/8557928/79-broken_flatbuffers.txt)

</details>

**Comment by hmaarrfk** [comment]
Related to: https://github.com/google/flatbuffers/issues/7272

**Comment by karimnosseir** [comment]
This should been done already. Terry can you please confirm

**Comment by terryheo** [comment]
Right. Let me close this. @hmaarrfk please feel free to reopen it if there is still an issue.
