### ISSUE TITLE
TF Lite (CMake): neon2sse missing license file location

### ISSUE THREAD

**Issue by stewartmiles** [tensorflow/tensorflow#55741]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.0

### Custom Code

No

### OS Platform and Distribution

Linux

### Python version

3.8

### Bazel version

N/A

### GCC/Compiler version

N/A

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### Current Behaviour?

```shell
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/cmake/modules/OverridableFetchContent.cmake tracks licenses for each dependency of an imported module of TensorFlow Lite. This allows projects using TF Lite to build an aggregate license file for redistribution (e.g https://github.com/google-research/falken/blob/e15aea40aec08e1e5858905e7dd6de7da2e4a1ec/sdk/cpp/CMakeLists.txt#L196 )

https://github.com/tensorflow/tensorflow/commit/1485091a6a64989a01cd2db76d53fe71653ae666 caused a regression in TF Lite's CMake dependencies by manually specifying a download URL where the license URL can no longer be inferred by `OverridableFetchContent.cmake`.

I'm happy to provide a fix that:
* Specifies the license URL and downloaded location.
* Enables license file checking in the TF Lite CMake project.
```

### Standalone code to reproduce the issue

```shell
Add `set(OVERRIDABLE_FETCH_CONTENT_LICENSE_CHECK ON)` near the top of `tensorflow/lite/CMakeLists.txt`, configure the project and wait for configuration to fail due to neon2sse missing a license.
```

### Relevant log output

```shell
$ cd tensorflow/lite
$ mkdir build
$ cd build
$ cmake ..
# lots of output
- Could NOT find CLANG_FORMAT: Found unsuitable version "0.0", but required is exact version "9" (found CLANG_FORMAT_EXECUTABLE-NOTFOUND)
--
-- Configured Eigen 3.4.90
--
-- Performing Test FARMHASH_HAS_BUILTIN_EXPECT
-- Performing Test FARMHASH_HAS_BUILTIN_EXPECT - Success
-- Looking for strtof_l
-- Looking for strtof_l - found
-- Looking for strtoull_l
-- Looking for strtoull_l - found
CMake Error at tools/cmake/modules/OverridableFetchContent.cmake:571 (message):
  Required license URL not found for neon2sse
Call Stack (most recent call first):
  tools/cmake/modules/neon2sse.cmake:37 (OverridableFetchContent_Populate)
  tools/cmake/modules/Findneon2sse.cmake:18 (include)
  CMakeLists.txt:148 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/stewart/src/tensorflow/tensorflow/lite/build/CMakeFiles/CMakeOutput.log".
See also "/home/stewart/src/tensorflow/tensorflow/lite/build/CMakeFiles/CMakeError.log".
```
</details>

**Comment by mohantym** [comment]
Hi @stewartmiles ! This issue will be closed once PR #55743 is merged . Thanks!

**Comment by mohantym** [comment]
Hi @stewartmiles !

Just wanted to let you know that I could not find any issue in Colab earlier. 
Might have been clang issue then.

> but required is exact version "9" (found CLANG_FORMAT_EXECUTABLE-NOTFOUND)


Could you check with GCC 7.3 or 9 and let us know.

Thank you!

**Comment by stewartmiles** [comment]
@mohantym I'm not sure what you're referring to w.r.t Colab. This is regarding TF lite not TensorFlow. The issue is at build time, if license checking is enabled (logic I wrote while at Google) the neon2sse module is missing a reference to a license file, I have a pull https://github.com/tensorflow/tensorflow/pull/55743 open to fix this could someone please review?

**Comment by mohantym** [comment]
Ok @stewartmiles !
I found similar results for Tensorflow/lite build too. Attached[ gist](https://colab.sandbox.google.com/gist/mohantym/316167cf749486b7b9b48d141ecb7350/git_55741.ipynb#scrollTo=U_w8WBBoSKQU) for reference. will connect with Team internally on this (just wanted to let you on clang pointer from stacktrace).
Thank you !
