### ISSUE TITLE
About On Device Training case cannot support correlation ops

### ISSUE THREAD

**Issue by YourPeer** [tensorflow/tensorflow#55748]
Hello, I would like to ask a question aboout On Device Training case. When I perform migration learning, I get the following error, which seems to be that these operators are not supported. That is, does the On Device Training case currently not support the use of convolution? How should I go about solving this problem? Looking forward to your reply！

"TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following Select TFop(s): Flex ops: FlexBroadcastGradientArgs, FlexConv2DBackpropFilter, FlexFusedBatchNormGradV3, FlexFusedBatchNormV3, FlexReluGrad"

**Comment by mohantym** [comment]
Hi @YourPeer ! Please include these code snippets before converting them to TFlite model. Attaching relevant [thread](https://www.tensorflow.org/lite/guide/ops_select) for reference .Thank you!

```
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
```

**Comment by YourPeer** [comment]
> Hi @YourPeer ! Please include these code snippets before converting them to TFlite model. Attaching relevant [thread](https://www.tensorflow.org/lite/guide/ops_select) for reference .
> 
> Please provide a minimal stand alone code for further assistance.Thank you!
> 
> ```
> converter.target_spec.supported_ops = [
>   tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
>   tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
> ]
> ```

Thank you for your reply! I have actually added this snippet and I found that it was just a hint and not an error report. But I haven't deployed it to android yet, just called it on PC, and it worked!

**Comment by mohantym** [comment]
Thanks @YourPeer for the confirmation . Please move this issue to closed status if it worked. Thank you!
