### ISSUE TITLE
when path contain '[' and ']'  character, tf.data.experimental.load return an empty dataset

### ISSUE THREAD

**Issue by xianzhuo-sky** [tensorflow/tensorflow#55756]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### CUDA/cuDNN version

11.6

### Current Behaviour?

```shell
when I load a dataset use tf.data.experimental.load , I get an empty dataset, but the dataset actually is not empty, the dataset was saved by tf.data.experimental.save correctly .The save path contains '[' and ']' character. If I remove '[' and ']' character , tf.data.experimental.load works fine.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

tf.data.experimental.load('datasets/build/train[m]_data')
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@xianzhuo-sky 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by xianzhuo-sky** [comment]
@sushreebarsa I change to the latest nightly build version 'tf-nightly-2.10.0.dev20220427', and can't use  tf.data.Dataset.load .
`AttributeError: type object 'DatasetV2' has no attribute 'load'`

**Comment by sushreebarsa** [comment]
@xianzhuo-sky 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by xianzhuo-sky** [comment]
@sushreebarsa https://colab.research.google.com/drive/18hZU3XTB4mRu783IyO6X2l8IjjP709Cp?usp=sharing

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to replicate the issue on colab ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/556b64009d1f823ab3b8f16c9723c091/55756.ipynb) for reference .Thank you!

**Comment by gadagashwini** [comment]
`tf.data.Dataset `has no attribute `load`. 
`tf.data.experimental.save` and `tf.data.experimental.load` are in experimental stage. 

I could able to reproduce the issue
Case1: Path with character `['']`
```
import tempfile
import os
path = os.path.join(tempfile.gettempdir(), "/test[a]")
# Save a dataset
dataset = tf.data.Dataset.range(2)
tf.data.experimental.save(dataset, path)
new_dataset = tf.data.experimental.load(path)
for elem in new_dataset:
  print(elem)
```
**Output**
`Empty `

Case2: Path without character `['']`
```
import tempfile
import os
path = os.path.join(tempfile.gettempdir(), "/test")
# Save a dataset
dataset = tf.data.Dataset.range(2)
tf.data.experimental.save(dataset, path)
new_dataset = tf.data.experimental.load(path)
for elem in new_dataset:
  print(elem)
```
**Output**
```
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
```

**Comment by gowthamkpr** [comment]
Uses tf.data.Dataset.save() and tf.data.Dataset.load() as tf.data.experimental.save() and tf.data.experimental.load() is getting depricated in future tensorflow versions and faced the same issue. Please find the gist [here](https://colab.research.google.com/gist/gowthamkpr/86ceb84722f37210a6582c8cbeb9b84c/untitled359.ipynb). Thanks!
