### ISSUE TITLE
Different behavior between `tf.experimental.numpy.(v/h/d)split` and `np.(v/h/d)split`

### ISSUE THREAD

**Issue by kanghj** [tensorflow/tensorflow#55753]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### Current Behaviour?

I expected Tensorflow to throw a similar exception (`ValueError: array split does not result in an equal division`) as Numpy on invoking the experimental.numpy.*split functions (e.g. `tf.experimental.numpy.dsplit`, `tf.experimental.numpy.hsplit`, `tf.experimental.numpy.vsplit`),
but currently, Tensorflow consumes all RAM and crashes.

I wonder if Tensorflow should perform the validation checks in the same order as numpy (i.e., detect the invalid array split first)?

### Standalone code to reproduce the issue

Here's a colab notebook: https://colab.research.google.com/drive/1zyOtnyGi9KgZLskYc4SRCB74fV73rnyU?usp=sharing

```python
import tensorflow as tf
import numpy as np

x = np.arange(16.0)
tf.experimental.numpy.dsplit(ary=x,indices_or_sections=256000000)  # crashes
```

```python
# In contrast,
np.dsplit(ary=np.arange(16.0),indices_or_sections=128000000) # doesn't crash, but throws an exception instead. This is the expected behavior
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@gowthamkpr I was able to replicate the issue on colab using TF v2.8.0 and tf-nightly ,please find the attached [gist](https://colab.research.google.com/gist/sushreebarsa/53b45538c26b46365fc0a774a18a769b/55753.ipynb)  for reference.Thanks!

**Comment by sachinprasadhs** [comment]
Thanks for reporting bug, PR has been submitted internally, on successful merge, this issue will be closed automatically.
