### ISSUE TITLE
TensorFlow does not use NVLink on Windows

### ISSUE THREAD

**Issue by edwardyehuang** [tensorflow/tensorflow#55757]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

No

### OS Platform and Distribution

Windows 10

### CUDA/cuDNN version

470

### GPU model and memory

Titan RTX ×2 NVLink

### Current Behaviour?

```shell
TensorFlow does not use NVLink on Windows. Seems it is happens on all versions of TensorFlow 2.X
```

### Standalone code to reproduce the issue

It is not possible to provide a colab since it has to be tested on Windows.
However, by running the following simple code in TensorFlow 2.4 (Windows) on GPUs with NVLink, you can find there are no inter-connections between GPUs. (N instead of Y in matrix). 

I don't know how to see if the NVLink is enabled on TensorFlow 2.8, because the inter-connection matrix is removed.

```shell

import tensorflow as tf

tf.constant(1) + 1
```

**Comment by tilakrayal** [comment]
Hello @edwardyehuang ,
Can you please provide the complete error log which helps to debug/analyse the issue.Thanks!
