### ISSUE TITLE
win10 pthread.lib can not be found

### ISSUE THREAD

**Issue by pobingwanghai** [tensorflow/tensorflow#5576]
errot log:
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - found
-- Found Threads: TRUE
how can i fix this problem, i have solved the .h issue ,but the lib issue can be solved in vs by prgma ,but for cmake , i have put prgma in every file related to pthread.h

**Comment by pobingwanghai** [comment]
this is the only error happened during cmake, is it important for the build or i can just igonre this issue .

**Comment by pobingwanghai** [comment]
by ignore this issue ,i msbuild the project ,but stuck in protobuf git and jsoncpp git ,is it related to the pthread issue ,i have successfully installed protobuf and jsoncpp testing by vs.

**Comment by pobingwanghai** [comment]
i think this can be easily solved by adding prgma ,but the problem is where should i add it.

**Comment by mrry** [comment]
This should be a benign error: TensorFlow on Windows does not require pthreads to build or run—instead it uses C++11 threads, which are supported by the Windows C runtime library.

It should be possible to eliminate this error by wrapping the line `find_package (Threads)` in CMakeLists.txt in an `if(UNIX)` block.

**Comment by pobingwanghai** [comment]
@mrry Thanks a lot ,remove the fine_package() is useful for me to remove the error during cmake ,but I have to msbuild it to see whether it works or not .Thanks again
