### ISSUE TITLE
mixed precision support with tensorflow2.4

### ISSUE THREAD

**Issue by shiva1393** [tensorflow/tensorflow#55765]
Problem:  Unable to produce mixed-precision results with TensorFlow 2.4
1) Done mixed-precision set up with cudnn8, Cuda 11 and TensorFlow 2.4 version in A100 and V100 GPU.
    referred following sites for this (https://towardsdatascience.com/whats-new-in-tensorflow-2-4-fe7aee9ac977),(https://developer.nvidia.com/blog/cuda-11-features-revealed/) and many other sites.

2) Followed the following tutorial (https://www.tensorflow.org/guide/mixed_precision) for mixed-precision training.
mixed_precision.py code:
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import mixed_precision

policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_global_policy(policy)

print('Compute dtype: %s' % policy.compute_dtype)
print('Variable dtype: %s' % policy.variable_dtype)
inputs = keras.Input(shape=(4096,), name='digits')
if tf.config.list_physical_devices('GPU'):
  print('The model will run with 4096 units on a GPU')
  num_units = 4096
else:
  # Use fewer units on CPUs so the model finishes in a reasonable amount of time
  print('The model will run with 64 units on a CPU')
  num_units = 64


dense1 = layers.Dense(num_units, activation='relu', name='dense_1')
x = dense1(inputs)
dense2 = layers.Dense(num_units, activation='relu', name='dense_2')
x = dense2(x)
dense3 = layers.Dense(num_units, activation='relu', name='dense_3')
x = dense3(x)
dense4 = layers.Dense(num_units, activation='relu', name='dense_4')
x = dense4(x)
dense5 = layers.Dense(num_units, activation='relu', name='dense_5')
x=dense5(x)
x = layers.Dense(16, name='dense_logits')(x)
outputs = layers.Activation('softmax', dtype='float32', name='predictions')(x)
print('Outputs dtype: %s' % outputs.dtype.name)
model = keras.Model(inputs=inputs, outputs=outputs)
print(model.summary())

optimizer=keras.optimizers.RMSprop()
optimizer=tf.keras.mixed_precision.LossScaleOptimizer(optimizer)
loss_object=tf.keras.losses.SparseCategoricalCrossentropy()
@tf.function
def train_step(x,y):
  with tf.GradientTape() as tape:
    predictions=model(x)
    loss=loss_object(y,predictions)
    scaled_loss=optimizer.get_scaled_loss(loss)
  scaled_gradients=tape.gradient(scaled_loss,model.trainable_variables)
  gradients=optimizer.get_unscaled_gradients(scaled_gradients)
  optimizer.apply_gradients(zip(gradients,model.trainable_variables))
  return loss
@tf.function
def test_step(x):
  return model(x,training=False)
x_train=tf.random.normal([1000000,num_units],dtype=tf.float32)
y_train=tf.random.uniform(shape=(1000000,),minval=0,maxval=15,dtype=tf.int64)
x_test=x_train
y_test=y_train
train_dataset=tf.data.Dataset.from_tensor_slices((x_train,y_train)).batch(512)
test_dataset = tf.data.Dataset.from_tensor_slices((x_test,y_test)).batch(512)
import time
start_time=time.perf_counter()
for epoch in range(10):
  epoch_loss_avg=tf.keras.metrics.Mean()
  test_accuracy=tf.keras.metrics.SparseCategoricalCrossentropy(name='test_accuracy')
  for x,y in train_dataset:
    loss=train_step(x,y)
    epoch_loss_avg(loss)
print("---- Training time in seconds %s --"%(time.perf_counter()-start_time))
start_time=time.perf_counter()
for x,y in test_dataset:
  test_accuracy=tf.keras.metrics.SparseCategoricalCrossentropy(name='test_accuracy')
  predictions=test_step(x)
  test_accuracy.update_state(y,predictions)
print("---- Testing time in seconds %s --"%(time.perf_counter()-start_time))
```

fp32.py code
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import mixed_precision

inputs = keras.Input(shape=(4096,), name='digits')
if tf.config.list_physical_devices('GPU'):
  print('The model will run with 4096 units on a GPU')
  num_units = 4096
else:
  # Use fewer units on CPUs so the model finishes in a reasonable amount of time
  print('The model will run with 64 units on a CPU')
  num_units = 64


dense1 = layers.Dense(num_units, activation='relu', name='dense_1')
x = dense1(inputs)
dense2 = layers.Dense(num_units, activation='relu', name='dense_2')
x = dense2(x)
dense3 = layers.Dense(num_units, activation='relu', name='dense_3')
x = dense3(x)
dense4 = layers.Dense(num_units, activation='relu', name='dense_4')
x = dense4(x)
dense5 = layers.Dense(num_units, activation='relu', name='dense_5')
x=dense5(x)
x = layers.Dense(16, name='dense_logits')(x)
outputs = layers.Activation('softmax', dtype='float32', name='predictions')(x)
print('Outputs dtype: %s' % outputs.dtype.name)
model = keras.Model(inputs=inputs, outputs=outputs)
print(model.summary())

optimizer=keras.optimizers.RMSprop()

loss_object=tf.keras.losses.SparseCategoricalCrossentropy()
@tf.function
def train_step(x,y):
  with tf.GradientTape() as tape:
    predictions=model(x)
    loss=loss_object(y,predictions)
  gradients=tape.gradient(loss,model.trainable_variables)
  optimizer.apply_gradients(zip(gradients,model.trainable_variables))
  return loss
@tf.function
def test_step(x):
  return model(x,training=False)
x_train=tf.random.normal([1000000,num_units],dtype=tf.float32)
y_train=tf.random.uniform(shape=(1000000,),minval=0,maxval=15,dtype=tf.int64)
x_test=x_train
y_test=y_train
train_dataset=tf.data.Dataset.from_tensor_slices((x_train,y_train)).batch(512)
test_dataset = tf.data.Dataset.from_tensor_slices((x_test,y_test)).batch(512)
import time
start_time=time.perf_counter()
for epoch in range(10):
  epoch_loss_avg=tf.keras.metrics.Mean()
  test_accuracy=tf.keras.metrics.SparseCategoricalCrossentropy(name='test_accuracy')
  for x,y in train_dataset:
    loss=train_step(x,y)
    epoch_loss_avg(loss)
print("---- Training time in seconds %s --"%(time.perf_counter()-start_time))
start_time=time.perf_counter()
for x,y in test_dataset:
  test_accuracy=tf.keras.metrics.SparseCategoricalCrossentropy(name='test_accuracy')
  predictions=test_step(x)
  test_accuracy.update_state(y,predictions)
print("---- Testing time in seconds %s --"%(time.perf_counter()-start_time))
```

Questions:
(I)  do we have tensorflow2.4 support for mixed-precision? I saw many issues related to it. But not found the proper solution.
(ii) In above mixed_precision code and fp32 code both are running approximately the same time for training and inference in A100 and V100 GPU. Did I made any mistake?

**Comment by sushreebarsa** [comment]
@shiva1393 I was able to run the tutorial of mixed precision successfully on colab using TF v2.8.0 , please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/937bc1ba926bda63b22690a50e4fa121/mixed_precision.ipynb) for reference.
I tried to replicate the issue with the provided code and faced an [error](https://colab.research.google.com/gist/sushreebarsa/326dbe26a8deffb7068c81511c9a47a4/55765.ipynb) as reported. Please refer to this [thread](https://stackoverflow.com/questions/56879217/is-automatic-mixed-precision-supported-by-tf-keras-in-tensorflow-beta-2-0) and for any further queries please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thanks!

**Comment by shiva1393** [comment]
@sushreebarsa Thanks for your suggestion, you are getting out of a memory issue.  decreasing the num_units from 4096 to lesser, You can run it. I will try with the tf2.8 version, thank you

**Comment by sushreebarsa** [comment]
@shiva1393 Could you please let us know if you have tried with the latest TF version 2.8.0 ?
Thanks!

**Comment by shiva1393** [comment]
Hi @sushreebarsa 
with tf-2.8, cudnn 8.1, cuda 11.2, I'm not getting expected output with A100 GPU. I'm including code also, please give some suggestions

mixed precision.py
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import mixed_precision
import os
#os.environ['TF_ENABLE_AUTO_MIXED_PRECISION'] = '1'
#os.environ['NVIDIA_TF32_OVERRIDE']='1'
#NVIDIA_TF32_OVERRIDE="1"
#export TF_XLA_FLAGS="--tf_xla_auto_jit=2"
#export TF_ENABLE_AUTO_MIXED_PRECISION=1
#############################################
policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_global_policy(policy)
#tf.config.optimizer.set_jit(True)
#mixed_precision.set_global_policy('mixed_float16')
########## tf 2.3 #######
#policy = tf.keras.mixed_precision.experimental.Policy('mixed_float16')
#tf.keras.mixed_precision.experimental.set_policy(policy)

#############################################
print("--- mixed precision enabled -----")
print('Compute dtype: %s' % policy.compute_dtype)
print('Variable dtype: %s' % policy.variable_dtype)
inputs = keras.Input(shape=(2048,), name='digits')
if tf.config.list_physical_devices('GPU'):
  print('The model will run with 4096 units on a GPU')
  num_units =2048
else:
  # Use fewer units on CPUs so the model finishes in a reasonable amount of time
  print('The model will run with 64 units on a CPU')
  num_units = 64
dense1 = layers.Dense(num_units, activation='relu', name='dense_1')
x = dense1(inputs)
dense2 = layers.Dense(num_units, activation='relu', name='dense_2')
x = dense2(x)
dense3 = layers.Dense(num_units, activation='relu', name='dense_3')
x = dense3(x)
dense4 = layers.Dense(num_units, activation='relu', name='dense_4')
x = dense4(x)
dense5 = layers.Dense(num_units, activation='relu', name='dense_5')
x = dense5(x)

dense6 = layers.Dense(num_units, activation='relu', name='dense_6')
x = dense6(x)
# CORRECT: softmax and model output are float32
x = layers.Dense(16, name='dense_logits')(x)
outputs = layers.Activation('softmax', dtype='float32', name='predictions')(x)
print('Outputs dtype: %s' % outputs.dtype.name)
model = keras.Model(inputs=inputs, outputs=outputs)
print(model.summary())
#model.compile(loss='sparse_categorical_crossentropy',
#              optimizer=keras.optimizers.RMSprop(),
#              metrics=['accuracy'])
optimizer = keras.optimizers.RMSprop()
optimizer = mixed_precision.LossScaleOptimizer(optimizer)
#optimizer = tf.train.experimental.enable_mixed_precision_graph_rewrite(optimizer)
#optimizer = tf.keras.mixed_precision.LossScaleOptimizer(optimizer)
#optimizer = tf.train.experimental.enable_mixed_precision_graph_rewrite(
#    optimizer, loss_scale='dynamic'
#)

loss_object = tf.keras.losses.SparseCategoricalCrossentropy()
@tf.function
def train_step(x, y):
  with tf.GradientTape() as tape:
    predictions = model(x)
    loss = loss_object(y, predictions)
    scaled_loss = optimizer.get_scaled_loss(loss)
  scaled_gradients = tape.gradient(scaled_loss, model.trainable_variables)
  gradients = optimizer.get_unscaled_gradients(scaled_gradients)
  optimizer.apply_gradients(zip(gradients, model.trainable_variables))
  return loss


@tf.function
def test_step(x):
  return model(x, training=False)

#(x_train, y_train), (x_test, y_test) =
x_train = tf.random.normal([1000000,2048],dtype=tf.float32)
y_train = tf.random.uniform(shape=(1000000,), minval=0, maxval=15, dtype=tf.int64)
x_test = x_train
y_test=y_train
#train_dataset = (tf.data.Dataset.from_tensor_slices((x_train, y_train).batch(256))
#test_dataset = (tf.data.Dataset.from_tensor_slices((x_test, y_test).batch(256))
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(512)
test_dataset = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(512)
import time
start_time = time.perf_counter()
#history = model.fit(x_train, y_train,
#                    batch_size=256,
#                    epochs=5,
#                    validation_split=0.2)
for epoch in range(10):
  epoch_loss_avg = tf.keras.metrics.Mean()
  test_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(
      name='test_accuracy')
  #temp=0
  for x, y in train_dataset:
    loss = train_step(x, y)
    epoch_loss_avg(loss)
    #print(temp)
    #temp=temp+1
  #print("loss and epoch",loss,epoch)
print("--- Training time in seconds %s---" % (time.perf_counter() - start_time))
start_time = time.perf_counter()
#test_scores = model.evaluate(x_test, y_test, verbose=2)
for x, y in test_dataset:
  test_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(
      name='test_accuracy')
  predictions = test_step(x)
  test_accuracy.update_state(y, predictions)
print("--- Inference time in seconds %s---" % (time.perf_counter() - start_time))
```
log info for mixed precision:
NVIDIA A100-SXM4-40GB, compute capability: 8.0
--- mixed precision enabled -----
Compute dtype: float16
Variable dtype: float32
The model will run with 4096 units on a GPU
Outputs dtype: float32
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 digits (InputLayer)         [(None, 2048)]            0

 dense_1 (Dense)             (None, 2048)              4196352

 dense_2 (Dense)             (None, 2048)              4196352

 dense_3 (Dense)             (None, 2048)              4196352

 dense_4 (Dense)             (None, 2048)              4196352

 dense_5 (Dense)             (None, 2048)              4196352

 dense_6 (Dense)             (None, 2048)              4196352

 dense_logits (Dense)        (None, 16)                32784

 predictions (Activation)    (None, 16)                0

=================================================================
Total params: 25,210,896
Trainable params: 25,210,896
Non-trainable params: 0
_________________________________________________________________
None
--- Training time in seconds 183.56538821800495---
--- Inference time in seconds 14.74218037899118---



fp32.py

import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras import mixed_precision
#policy = mixed_precision.Policy('mixed_float16')
#mixed_precision.set_global_policy(policy)
#print("--- mixed precision enabled -----")
#print('Compute dtype: %s' % policy.compute_dtype)
#print('Variable dtype: %s' % policy.variable_dtype)
inputs = keras.Input(shape=(2048,), name='digits')
if tf.config.list_physical_devices('GPU'):
  print('The model will run with 4096 units on a GPU')
  num_units = 2048
else:
  # Use fewer units on CPUs so the model finishes in a reasonable amount of time
  print('The model will run with 64 units on a CPU')
  num_units = 64
dense1 = layers.Dense(num_units, activation='relu', name='dense_1')
x = dense1(inputs)
dense2 = layers.Dense(num_units, activation='relu', name='dense_2')
x = dense2(x)

dense3 = layers.Dense(num_units, activation='relu', name='dense_3')
x = dense3(x)





dense4 = layers.Dense(num_units, activation='relu', name='dense_4')
x = dense4(x)
dense5 = layers.Dense(num_units, activation='relu', name='dense_5')
x = dense5(x)

dense6 = layers.Dense(num_units, activation='relu', name='dense_6')
x = dense6(x)



# CORRECT: softmax and model output are float32
x = layers.Dense(16, name='dense_logits')(x)
outputs = layers.Activation('softmax', name='predictions')(x)
print('Outputs dtype: %s' % outputs.dtype.name)
model = keras.Model(inputs=inputs, outputs=outputs)
print(model.summary())
#model.compile(loss='sparse_categorical_crossentropy',
#              optimizer=keras.optimizers.RMSprop(),
#              metrics=['accuracy'])
optimizer = keras.optimizers.RMSprop()
#optimizer = mixed_precision.LossScaleOptimizer(optimizer)
loss_object = tf.keras.losses.SparseCategoricalCrossentropy()
@tf.function
def train_step(x, y):
  with tf.GradientTape() as tape:
    predictions = model(x)
    loss = loss_object(y, predictions)
    #scaled_loss = optimizer.get_scaled_loss(loss)
  gradients = tape.gradient(loss, model.trainable_variables)
  #gradients = optimizer.get_unscaled_gradients(scaled_gradients)
  optimizer.apply_gradients(zip(gradients, model.trainable_variables))
  return loss


@tf.function
def test_step(x):
  return model(x, training=False)

#(x_train, y_train), (x_test, y_test) =
x_train = tf.random.normal([1000000,2048],dtype=tf.float32)
y_train = tf.random.uniform(shape=(1000000,), minval=0, maxval=15, dtype=tf.int64)
x_test = x_train
y_test=y_train
#train_dataset = (tf.data.Dataset.from_tensor_slices((x_train, y_train).batch(256))
#test_dataset = (tf.data.Dataset.from_tensor_slices((x_test, y_test).batch(256))
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(512)
test_dataset = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(512)
import time
start_time = time.perf_counter()
#history = model.fit(x_train, y_train,
#                    batch_size=256,
#                    epochs=5,
#                    validation_split=0.2)
for epoch in range(10):
  epoch_loss_avg = tf.keras.metrics.Mean()
  test_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(
      name='test_accuracy')
  for x, y in train_dataset:
    loss = train_step(x, y)
    epoch_loss_avg(loss)
  #print("loss and epoch",loss,epoch)
print("--- Training time in seconds %s---" % (time.perf_counter() - start_time))
start_time = time.perf_counter()
#test_scores = model.evaluate(x_test, y_test, verbose=2)
for x, y in test_dataset:
  test_accuracy = tf.keras.metrics.SparseCategoricalAccuracy(
      name='test_accuracy')
  predictions = test_step(x)
  test_accuracy.update_state(y, predictions)
print("--- Inference time in seconds %s---" %(time.perf_counter() - start_time))

log info: 
NVIDIA A100-SXM4-40GB, compute capability: 8.0
The model will run with 4096 units on a GPU
Outputs dtype: float32
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 digits (InputLayer)         [(None, 2048)]            0

 dense_1 (Dense)             (None, 2048)              4196352

 dense_2 (Dense)             (None, 2048)              4196352

 dense_3 (Dense)             (None, 2048)              4196352

 dense_4 (Dense)             (None, 2048)              4196352

 dense_5 (Dense)             (None, 2048)              4196352

 dense_6 (Dense)             (None, 2048)              4196352

 dense_logits (Dense)        (None, 16)                32784

 predictions (Activation)    (None, 16)                0

=================================================================
Total params: 25,210,896
Trainable params: 25,210,896
Non-trainable params: 0
_________________________________________________________________
2022-05-05 14:25:41.468075: I tensorflow/stream_executor/cuda/cuda_blas.cc:1786] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
None
--- Training time in seconds 132.91190850097337---
--- Inference time in seconds 12.262969995994354---


I tried it with tf2.3, tf2.4 and tf 2.8 version, with tf2.4 mixed precision and fp32 model timings are approximately same but with tf 2.8 fp32 model timings are better than mixed precision. Need some help, am i doing any mistake or tensorflow 2.x versions not supporting for mixed precision?

**Comment by sachinprasadhs** [comment]
Could you please refer to the detailed conversation in the similar issue [here](https://github.com/keras-team/keras/issues/15678) and let us know if that helps. Thanks!

**Comment by shiva1393** [comment]
Hi @sachinprasadhs  In above mentioned link,  they got out of memory issues while running mixed precision codes. 
They solved it using 2 ways
1)  changing the cudnn or cuda versions for particular gpu type
2) using TF_CUDNN_USE_FRONTEND=1 and TF_CUDNN_WORKSPACE_LIMIT_IN_MB=5000 variables while executing code.

In my case I'm not getting any OOM issues, I'm able to train without any erros. But training/inference timings are same for fp32 and mixed precision models. Currently I'm trying with different cuda or cudnn versions. 
Could you please  give some suggestions?

**Comment by sachinprasadhs** [comment]
You can see the details about Mixed precision along with the performance tips in the document [here](https://www.tensorflow.org/guide/mixed_precision#overview).
After testing with different configurations, if you are not satisfied with the result, post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
