### ISSUE TITLE
Quantization models 

### ISSUE THREAD

**Issue by Sara980710** [tensorflow/tensorflow#55778]
I get exactly the same timing for inference using fp16 and fp32 using GPU, shouldn't fp16 give faster computation? And why are the type of the weights in fp32 even if the file-size is different?

int8 does also take longer time to invoke than fp32, is it because of the dequantize quantize implementation for int8 written in the documentation?

(All inherit from the same trained model)

**Comment by tilakrayal** [comment]
Hello @Sara980710 ,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced] or if possible share a colab gist with the issue reported.Thanks!
