### ISSUE TITLE
tflite quantization to fp16 only quantized input

### ISSUE THREAD

**Issue by jinfagang** [tensorflow/tensorflow#55785]
Hi, I have a model which is simply 3 layer fully connnected layers (the first layer will have resample on weights)

but I got a tflite graph that only quantized input:

![image](https://user-images.githubusercontent.com/21303438/165697855-63a99f9a-5de6-4446-a28a-b185bf3d29c7.png)

it only quantized the weights, but all other operations were dequantized and calculate in float32 way.

Why? I want the whole operations inference in fp16 since am runing on ARMv8.2 above CPU!

**Comment by mohantym** [comment]
Hi @jinfagang ! Could you please attach a minimal stand alone code too?

**Comment by jinfagang** [comment]
@mohantym  Hi, I might can only add the tflite model. But Can u point out why it goes like this? the model arch is like this:

[link](https://github.com/sebastianstarke/AI4Animation/blob/master/AI4Animation/SIGGRAPH_2017/TensorFlow/PFNN/PFNNParameter.py)

the whole graph is actually very simple:

https://github.com/sebastianstarke/AI4Animation/blob/e2cd539816b1cb1fa0a57e9d21df21d48467b313/AI4Animation/SIGGRAPH_2017/TensorFlow/PFNN/main.py#L82

**Comment by mohantym** [comment]
@jinfagang ! Could you point towards the location of Input.txt  and Output.txt too?

**Comment by jinfagang** [comment]
@mohantym Hi, the input is jus a random [bs, 1024], and output is just a random of [s, 980].
For exportation, just give it a random input and we can the graph. For the input name, I think you can specific anyname in node

**Comment by sachinprasadhs** [comment]
`float16` weights will be upsampled to `float32` weights prior to first inference to have minimal impact on latency and accuracy and also it reduces the model size significantly.
To know more, refer [this](https://www.tensorflow.org/lite/performance/post_training_float16_quant#overview) document.Thanks!
