### ISSUE TITLE
Documentation unclear for parameter `central_fraction` in `tf.image.central_crop`

### ISSUE THREAD

**Issue by chrisrapson** [tensorflow/tensorflow#55782]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Feature Request

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

```shell
The function `tf.image.central_crop` takes a parameter `central_fraction`. I would have expected that a larger `central_fraction` would mean that more of the image is kept. However, looking at [the code](https://github.com/tensorflow/tensorflow/blob/v2.8.0/tensorflow/python/ops/image_ops_impl.py#L844-L986=) my understanding is that a larger number means that more is cropped out. e.g.

bbox_h_start = int((img_hd - img_hd * central_fraction_static) / 2)
```

Changing the example from the current `central_fraction=0.5` to `central_fraction=0.25` would help clarify this point.
https://github.com/tensorflow/tensorflow/issues/29334
```


### Standalone code to reproduce the issue

```shell
https://www.tensorflow.org/api_docs/python/tf/image/central_crop
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@chrisrapson 
In order to expedite the trouble-shooting process, can you please provide more details on this issue ?Thanks!

**Comment by chrisrapson** [comment]
At the moment, the [documentation](https://www.tensorflow.org/api_docs/python/tf/image/central_crop) gives this example:

```
 --------
|        |
|  XXXX  |
|  XXXX  |
|        |   where "X" is the central 50% of the image.
 --------
```

It is not clear from the description whether `central_fraction=0.25` would look like:

```
 ----------------
|                |
|                |
|                |
|      XXXX      |
|      XXXX      |
|                |
|                |   
|                |
 ----------------
```

or

```
 ----------------
|                |
|    XXXXXXXX    |
|    XXXXXXXX    |
|    XXXXXXXX    |
|    XXXXXXXX    |
|    XXXXXXXX    |
|    XXXXXXXX    |
|                |
 ----------------
```

My initial assumption was the first one, but from the source code it looks like the second one.

**Comment by sachinprasadhs** [comment]
The point is made clear in the [argument](https://www.tensorflow.org/api_docs/python/tf/image/central_crop#args) section where it says 

**central_fraction  |  float (0, 1], fraction of size to crop**

The value between 0,1 will be considered as the fractional size to crop from the given input. That means larger the value of central_fraction larger portion will be cropped. Hope this clarifies your concern. Thanks!

**Comment by chrisrapson** [comment]
Sorry, that's exactly the part that I find unclear. Is the part that is "cropped" the pixels that are removed, or the ones that are left behind? I think people commonly use the word interchangeably, which makes it challenging. I think an example that is not 0.5 would clear it up unambiguously. Adding a sentence like yours: "larger the value of central_fraction larger portion will be cropped" might help, except you would need to exchange the last word for "removed" (or "kept", if my understanding is incorrect).

**Comment by sachinprasadhs** [comment]
[tf.image.central_crop](https://github.com/tensorflow/tensorflow/issues/55782#) returns a Tensor, without modifying the input given to it.
In the example mentioned in the document there are only limited outcome with the different `central_fraction`, even if the `central_fraction` is changed to 0.25, you will get the same output as `central_fraction`= 0.5. 
It is because of the code logic of the bounding_box width and height here.

https://github.com/tensorflow/tensorflow/blob/3f878cff5b698b82eea85db2b60d65a2e320850e/tensorflow/python/ops/image_ops_impl.py#L952-L961


I will create PR to update details in the document. Thanks!

**Comment by chrisrapson** [comment]
I don't think I understand why you would get the same output for `central_fraction=0.25` and `central_fraction=0.5`. Do you mean, because the input in the example is low resolution, and the `bbox_w_start` is cast to an int? Even then, it looks like the input is 8x4, so I would have expected the two outputs to be 2x1 and 4x2 respectively.

Anyway, the modification to the docstring in your PR clears it up nicely. Thanks.

**Comment by sachinprasadhs** [comment]
In the example given in the document, img_h, img_w & img_d are 4.0,4.0 &3.0 respectively.
For different central_fraction 0.25/0.5 when you equate with the below equation it gives the same result.

`bbox_h_start = int((img_hd - img_hd * central_fraction_static) / 2) `

```
1. int((4.0 -4.0*0.25)/2) =1
2. int(4.0 -4.0*0.5)/2)=1
```

For visible result, you can refer the below code and notice the shape difference between different `central_fraction`.

```
import tensorflow as tf
import numpy as np
x = np.random.randint(0, 255, size=(28, 28, 3))
tf.image.central_crop(x, 0.25)
tf.image.central_crop(x, 0.5)
```
