### ISSUE TITLE
fp32 and mixed precision models

### ISSUE THREAD

**Issue by shiva1393** [tensorflow/tensorflow#55784]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

tf 2.4

### Custom Code

No

### Python version

3.6

### CUDA/cuDNN version

cuda 11.2/cuDNN 8.0

### Current Behaviour?

```shell
training mixed-precision models and single precision models with the tf2.4, cudnn 8 and cuda11.2 versions in V100 and A100 GPUs. while training the mixed-precision model it is showing only 16% improvement compared to single precision models. while testing the mixed-precision model showing no improvement compared to single precision model. Mixed precision weights are saving in tf.Variable(dtype=float32) instead of tf.AutoCastVariable. Is this reason for no improvement in inference? do we have support for mixed-precision using tensorflow2.4? I saw many git issues regarding mixed-precision without any conclusions.
```

### Standalone code to reproduce the issue

```shell
-
```

### Relevant log output

```shell
-
```
</details>

**Comment by tilakrayal** [comment]
Hello @shiva1393 ,
 In order to expedite the trouble-shooting process, could you please provide a complete code you are using and also I request, please try to test the code in latest stable tensorflow v2.8 and let us know if you are facing same issue.Thanks!

**Comment by Anyanwu21** [comment]
Good

**Comment by shiva1393** [comment]
@tilakrayal Thanks for your suggestion,  I have the following doubts please clarify to me
(1)what are the exact dependencies(e.g., Cuda, CuDNN) needed for t2.8?
(2)Without CuDNN Can I expect the same results?

**Comment by tilakrayal** [comment]
@shiva1393 ,
Every TensorFlow release is compatible with certain CUDA and cuDNN version, I request to please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#gpu) which delivers the information on compatible versions for tf v2.8.Thanks!

**Comment by shiva1393** [comment]
thank you @tilakrayal @sachinprasadhs(similar issue in other post)  , with tensorflow 2.8 , cudnn8.2 and cuda 11.2/cuda 11.4 versions it worked well. 
Now I'm able to see 2.4 times improvement in mixed precision compared to float 32 model. but unable to get any improvement while testing with mixed precision. The inferance speed is similar to float 32 model.

I have following doubts:
1) I used similar code to save and load the model.
```
checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt")
checkpoint = tf.train.Checkpoint(optimizer=optimizer,
                                 encoder=encoder,
                                 decoder=decoder)
#save the checkpoint 
checkpoint.save(file_prefix=checkpoint_prefix)

# restoring the latest checkpoint in checkpoint_dir
checkpoint.restore(tf.train.latest_checkpoint(checkpoint_dir))  
```
My doubt is if we use mixed precision models do we need to provide any other extra arguments to save and load model. Because when I try to load mixed precision model all parameters are in float 32 type instead of autocastvariable/float 16.
Could you please provide any suggestions?
