### ISSUE TITLE
Autograph crashes when using pythonw.exe on Windows

### ISSUE THREAD

**Issue by jgentil** [tensorflow/tensorflow#55795]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.8.0

### Custom Code

No

### OS Platform and Distribution

Windows

### Python version

3.8

### Current Behaviour?

When using pythonw.exe, if local sources are not available, (e.g. only .pyc files are available), autograph causes a crash by trying to flush sys.stdout.

https://github.com/tensorflow/tensorflow/blob/f39905619ddf75b31e209264673f76ac2c72030e/tensorflow/python/autograph/core/ag_ctx.py#L100-L105
If the source code to Autograph itself isn't available, it emits this warning using ag_logging.warning:

https://github.com/tensorflow/tensorflow/blob/f39905619ddf75b31e209264673f76ac2c72030e/tensorflow/python/autograph/utils/ag_logging.py#L141-L145

For some reason, `warning()` is different than any of the other emitters and flushes the stream.  But when running in pythonw.exe, `sys.stdout` is `None`.  It checks for this using `echo_log_to_stdout` to ensure that it doesn't write to stdout, but then immediately tries to flush it.

This can be remediated to indenting the call to `sys.stdout.flush()` to inside the `if echo_log_to_stdout:` check.

### Standalone code to reproduce the issue

1. Create a virtual environment and install TensorFlow
2. Compile all of your py files in site-packages using the `compileall` module
3. Delete py files from your site-packages
4. Create an example tk-based script or something else that shows a GUI
5. Import tensorflow in your script and execute it using `pythonw.exe` and observe the error, which will not fail when running `python.exe`

### Relevant log output

_No response_</details>

**Comment by sachinprasadhs** [comment]
Thanks for the bug, I have created a PR for the same.
