### ISSUE TITLE
Web pages don't have titles

### ISSUE THREAD

**Issue by aidan-fitz** [tensorflow/tensorflow#558]
None of the web pages at tensorflow.org have titles.

**Comment by rekhajoshm** [comment]
https://github.com/tensorflow/tensorflow/pull/575

**Comment by martinwicke** [comment]
Putting title annotations in the md like that won't work (unfortunately).
We have to fix this here.

**Comment by girving** [comment]
@martinwicke: It looks like the pages have titles now.  Want to mark as fixed?

**Comment by martinwicke** [comment]
Fixed.
