### ISSUE TITLE
Unroll factor for keras.layers.RNN or performance fix for TensorArray / while_loop.

### ISSUE THREAD

**Issue by mcourteaux** [tensorflow/tensorflow#55811]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Tensorflow Version

2.7.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04

### CUDA/cuDNN version

11.5

### GPU model and memory

RTX 2080Ti

</details>

### Feature description

`keras.layers.RNN` supports unrolling, which is great for performance, unless the unrolled time dimension is too long. The XLA compiler takes a ton of time processing a fully unrolled loop (e.g. 240 iterations). Every major compiler supports unrolling a loop for a given factor. The `unroll` argument from `keras.layers.RNN` could instead take an integer telling how many iterations it should unroll, and insert a while loop around the remaining factor. Using an unroll factor of 32 would do miracles for most long time-dimension datasets.

XLA speedups are huge for my custom RNN Cell, so I'd like to use it, but now I'm waiting 5 minutes for XLA/ptxas to finish processing the unrolled loop. On the other hand, if I don't unroll, the while_loop introduces a TensorArray struct takes a tremendous amount of time every time-iteration of the RNN as there is a cuMemcpyD2H of 4 bytes happening between GPU and CPU. The whole CUDA driver pipeline stalls for this 4-byte copy. Performance drops by a factor of 2 to 5 because of this. I don't know if the 4-byte copy is an unintentional performance bug in TensorArray/tf.while_loop or not. But if it's not, I think the unroll factor is a good compromise.

**Comment by tilakrayal** [comment]
Hello @mcourteaux ,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Can you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by mcourteaux** [comment]
Aha, okay! Thank you for pointing that out! Made an issue here: https://github.com/keras-team/keras/issues/16485

**Comment by mcourteaux** [comment]
Although I still think the TensorArray/tf.while_loop 4-byte copy is a performance bug.
