### ISSUE TITLE
Value Assignment by specific indices error in Tensorflow (Assign values using mask)

### ISSUE THREAD

**Issue by Muhammad-Kaleem-Ullah** [tensorflow/tensorflow#55812]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### OS Platform and Distribution

Windows 10

### Python version

3.10.2

### Current Behaviour?

```shell
Hi! I'm trying to build a custom loss function for my model, but whenever I try to convert Tensors into .numpy() arrays with run_eagerly = True, it gives "WARNING: Gradients do not exist for variables ...". So I debugged other custom loss functions implemented using tensorflow. But in my case, I need to apply to mask and splitting index arrays and then use those arrays as indices to apply some sort of arithmetic functions using broadcasting. But I retrieved indices lists after masking, but I just have to access those indices and add specific functions. But I found no way in TensorFlow to implement that in a vectorized way.
```

### Standalone code to reproduce the issue

```shell
In NumPy, I can access it using:
error[i, j] = error[i, j] * 5
But TensorFlow does not provide any support related to this.
Also, I could not implement the custom_loss function by converting arrays to NumPy because it makes Gradient None. And it gives "WARNING: Gradients do not exist for variables ...".
```

### Relevant log output

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [193], in <cell line: 1>()
----> 1 error[i, j]

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\util\traceback_utils.py:153, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    151 except Exception as e:
    152   filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153   raise e.with_traceback(filtered_tb) from None
    154 finally:
    155   del filtered_tb

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\ops\array_ops.py:899, in _check_index(idx)
    894 dtype = getattr(idx, "dtype", None)
    895 if (dtype is None or dtypes.as_dtype(dtype) not in _SUPPORTED_SLICE_DTYPES or
    896     idx.shape and len(idx.shape) == 1):
    897   # TODO(slebedev): IndexError seems more appropriate here, but it
    898   # will break `_slice_helper` contract.
--> 899   raise TypeError(_SLICE_TYPE_ERROR + ", got {!r}".format(idx))

TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got <tf.Tensor: shape=(4797,), dtype=int64, numpy=array([ 0,  0,  0, ..., 26, 26, 26], dtype=int64)>
I tried using other functions provided by TensorFlow too, but those did not work.
```
</details>

**Comment by sushreebarsa** [comment]
@Muhammad-Kaleem-Ullah 
Can you please elaborate about your feature and please specify the use cases for this feature. Thanks!

**Comment by Muhammad-Kaleem-Ullah** [comment]
I'm building a custom loss function while converting Tensors into NumPy arrays by using .numpy(), which results in "Gradients loss". So, I must have to use Tensorflow to manipulate data. Here is what I'm trying:
```
error = y_true - y_false
print(y_true.shape, y_pred.shape)
print(error.shape)
print("Error values: ", error)
```

> Output: 
> Output: (10, 1000), (10, 1000)
> (10, 1000)
> Error values: <tf.Tensor: shape=(10, 1000), dtype=float64, numpy= array([[-10, 0, 8, ..., 3, -1.5, -2.5], ..., [ 2.5, 8 , 6.5, ..., 5.5, 3.5, -0.5]])>

Then, I apply the mask to retrieve indices where y_true > 5 & y_false <=0 to punish these errors.

```
mask = tf.where(y_true > 5)
i = mask[0]
j = mask[1]
print(i[:5])
print(j[:5])
```

> Output: 
> (<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 0, 0, 0, 0], dtype=int64)>,
> <tf.Tensor: shape=(5,), dtype=int64, numpy=array([19, 26, 28, 35, 39], dtype=int64)>)

I'm facing a problem here below when I try to apply this trick (like in NumPy) to assign values against the mask.
`error[i, j] = error[i, j] * 1.5`
**What I want is to replace with new values of error in a specified position after executing the above code and get values like:**

> Error values: <tf.Tensor: shape=(10, 1000), dtype=float64, numpy= array([[-10, 0, 16*, ..., 3, -1.5, -2.5], ..., [ 2.5, 16* , 13*, ..., 11*, 3.5, -0.5]])>
I'm trying to build a custom loss function for my model, but whenever I try to convert Tensors into .numpy() arrays with run_eagerly = True, it gives "WARNING: Gradients do not exist for variables ...". So I debugged other custom loss functions implemented using TensorFlow. But in my case, I need to apply to mask and splitting index arrays and then use those arrays as indices to apply some sort of arithmetic functions using broadcasting. But I retrieved indices lists after masking, but I just have to access those indices and add specific functions. But I found no way in TensorFlow to implement that in a vectorized way.

error = y_true - y_false
print(y_true.shape, y_pred.shape)
print(error.shape)
print("Error values: ", error)
Output: (10, 1000), (10, 1000)

(10, 1000)

Error values: <tf.Tensor: shape=(10, 1000), dtype=float64, numpy= array([[-10, 0, 8, ..., 3, -1.5, -2.5], ..., [ 2.5, 8 , 6.5, ..., 5.5, 3.5, -0.5]])>

mask = tf.where(y_true > 5)
i = mask[0]
j = mask[1]
print(i[:5])
print(j[:5])
Results:

(<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 0, 0, 0, 0], dtype=int64)>,

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([19, 26, 28, 35, 39], dtype=int64)>)

In NumPy, I can access it using:

error[i, j] = error[i, j] * 5
What I want is to replace with new values of error in a specified position after executing the above code and get values like:

Error values: <tf.Tensor: shape=(10, 1000), dtype=float64, numpy= array([[-10, 0, 16*, ..., 3, -1.5, -2.5], ..., [ 2.5, 16* , 13*, ..., 11*, 3.5, -0.5]])>

**But when I try to execute this as Tensors, it gives the following error:**
```
TypeError                                 Traceback (most recent call last)
Input In [193], in <cell line: 1>()
----> 1 error[i, j]

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\util\traceback_utils.py:153, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    151 except Exception as e:
    152   filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153   raise e.with_traceback(filtered_tb) from None
    154 finally:
    155   del filtered_tb

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\ops\array_ops.py:899, in _check_index(idx)
    894 dtype = getattr(idx, "dtype", None)
    895 if (dtype is None or dtypes.as_dtype(dtype) not in _SUPPORTED_SLICE_DTYPES or
    896     idx.shape and len(idx.shape) == 1):
    897   # TODO(slebedev): IndexError seems more appropriate here, but it
    898   # will break `_slice_helper` contract.
--> 899   raise TypeError(_SLICE_TYPE_ERROR + ", got {!r}".format(idx))

TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got <tf.Tensor: shape=(4797,), dtype=int64, numpy=array([ 0,  0,  0, ..., 26, 26, 26], dtype=int64)>
```

**Comment by sachinprasadhs** [comment]
There are multiple reasons for Gradients to become None, in your case it might be due to the operation you are doing could be outside Tensorflow operation or `tf.Variable` gets replaced with `tf.tensor` which is used for gradient calculation.
More details on this can be found [here](https://www.tensorflow.org/guide/autodiff#getting_a_gradient_of_none).
Regarding updating specific index values, you can take a look into tf.Variable operation [scatter_update](https://www.tensorflow.org/api_docs/python/tf/Variable?version=nightly#scatter_update) which assigns [tf.IndexedSlices](https://www.tensorflow.org/api_docs/python/tf/IndexedSlices) values. 
Let me know if this helps. Thanks!

**Comment by Muhammad-Kaleem-Ullah** [comment]
I used run_eagerly in model compile and then call the custom loss function. Then, I just used the above calculation for Tensors. And I got stuck there. Regarding your suggestion to use `scatter_update`, it did not work here.

**Comment by cantonios** [comment]
I think you want a combination of `tf.gather_nd` and `tf.tensor_scatter_nd_update`:
```
# Get the list of indices for some condition 
mask = tf.where(y_true > 5)

# Extract the values from another tensor at those indices
vals = tf.gather_nd(error, mask)

# Update values at the supplied indices based on the old values
tf.tensor_scatter_nd_update(error, mask, 5 * vals)
```

**Comment by sachinprasadhs** [comment]
@Muhammad-Kaleem-Ullah , Could you please refer the above comment and let us know if that helps.
For more details refer, [tf.gather_nd](https://www.tensorflow.org/api_docs/python/tf/gather_nd), [tf.tensor_scatter_nd_update](https://www.tensorflow.org/api_docs/python/tf/tensor_scatter_nd_update?version=nightly)

**Comment by cantonios** [comment]
Or, you could use the multiplexing mask:
```
new_error = tf.where(y_true > 5, 5 * error, error)
```

**Comment by cantonios** [comment]
An RFC to address this has been up for a bit.  Adding a link here in case anyone wants to provide input.

Comments are invited to the [pull request](https://github.com/tensorflow/community/pull/433). You can view the [design doc here](https://github.com/tensorflow/community/blob/77aa8fd5ea9c54bf1f08e9d25113aaa1ea90ba20/rfcs/20221020-tensor-indexed-updates.md), and also [leave comments inline](https://github.com/tensorflow/community/pull/433/files) on the document source.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
