### ISSUE TITLE
`Square` and `Sqrt` ops do not support complex values on GPU

### ISSUE THREAD

**Issue by jmontalt** [tensorflow/tensorflow#55823]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### OS Platform and Distribution

Colab

### Current Behaviour?

Attempting to train a complex64 variable using RMSprop throws a `Cannot assign a device for operation...` error (see full output below).

It seems the issue may be that the `Sqrt` and `Square` ops used during the variable update do not have GPU implementations for complex dtypes. Will these be supported?

Other optimizers (SGD, Adam) work fine as they do not require those ops. It's also possible to work around this by splitting the complex64 variable into two float32 variables representing real and imaginary parts, but this can get surprisingly messy in some circumstances.

### Standalone code to reproduce the issue

Colab: https://colab.research.google.com/drive/1wV3_UoLfGN6pTauD5ttoA5RHZUm9OCPe?usp=sharing

or see below:

```shell
import tensorflow as tf

class BasicLayer(tf.keras.layers.Layer):
  def build(self, input_shape):
    self.w = self.add_weight(name='w', shape=(3,),
                             initializer=tf.keras.initializers.Zeros())

  def call(self, inputs):
    return inputs * self.w

# Input/output data.
x = tf.constant([[1. + 2.j, 2. + 3.j, 3. + 4.j]])
y = x

# Create and compile model caling this layer.
input = tf.keras.Input(shape=(3,), dtype='complex64')
layer = BasicLayer(dtype='complex64')
model = tf.keras.Model(input, layer(input))
model.compile('rmsprop', 'mse')
model.train_on_batch(x, y)
```

### Relevant log output

```shell
InvalidArgumentError: Cannot assign a device for operation model_2/basic_layer_2/mul/ReadVariableOp: Could not satisfy explicit device specification '' because the node {{colocation_node model_2/basic_layer_2/mul/ReadVariableOp}} was colocated with a group of nodes that required incompatible device '/job:localhost/replica:0/task:0/device:GPU:0'. All available devices [/job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:GPU:0]. 
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=2 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU] possible_devices_=[]
RealDiv: GPU CPU 
AssignVariableOp: GPU CPU 
Sub: GPU CPU 
ReadVariableOp: GPU CPU 
_Arg: GPU CPU 
Sqrt: CPU 
Mul: GPU CPU 
Square: CPU 
AddV2: GPU CPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  model_2_basic_layer_2_mul_readvariableop_resource (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  rmsprop_rmsprop_update_mul_readvariableop_resource (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  model_2/basic_layer_2/mul/ReadVariableOp (ReadVariableOp) 
  RMSprop/RMSprop/update/mul/ReadVariableOp (ReadVariableOp) 
  RMSprop/RMSprop/update/mul (Mul) /job:localhost/replica:0/task:0/device:GPU:0
  RMSprop/RMSprop/update/Square (Square) /job:localhost/replica:0/task:0/device:GPU:0
  RMSprop/RMSprop/update/mul_1 (Mul) /job:localhost/replica:0/task:0/device:GPU:0
  RMSprop/RMSprop/update/add (AddV2) /job:localhost/replica:0/task:0/device:GPU:0
  RMSprop/RMSprop/update/AssignVariableOp (AssignVariableOp) /job:localhost/replica:0/task:0/device:GPU:0
  RMSprop/RMSprop/update/mul_2 (Mul) /job:localhost/replica:0/task:0/device:GPU:0
  RMSprop/RMSprop/update/Sqrt/ReadVariableOp (ReadVariableOp) /job:localhost/replica:0/task:0/device:GPU:0
  RMSprop/RMSprop/update/Sqrt (Sqrt) /job:localhost/replica:0/task:0/device:GPU:0
  RMSprop/RMSprop/update/add_1 (AddV2) /job:localhost/replica:0/task:0/device:GPU:0
  RMSprop/RMSprop/update/truediv (RealDiv) /job:localhost/replica:0/task:0/device:GPU:0
  RMSprop/RMSprop/update/ReadVariableOp (ReadVariableOp) 
  RMSprop/RMSprop/update/sub (Sub) /job:localhost/replica:0/task:0/device:GPU:0
  RMSprop/RMSprop/update/AssignVariableOp_1 (AssignVariableOp) /job:localhost/replica:0/task:0/device:GPU:0

	 [[{{node model_2/basic_layer_2/mul/ReadVariableOp}}]] [Op:__inference_train_function_1102]
```
</details>

**Comment by sushreebarsa** [comment]
@jmontalt 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thanks!

**Comment by jmontalt** [comment]
Hi @sushreebarsa, thank you for your reply. Although I was using Keras when I ran into the problem, it is my understanding that the underlying issue is in TF (that `Square` and `Sqrt` ops do not support complex values on GPU). The following code may be helpful:

```
import tensorflow as tf

tf.debugging.set_log_device_placement(True)

x = tf.constant(1.0 + 2.0j, dtype=tf.complex64)
y = tf.constant(1.0 + 2.0j, dtype=tf.complex64)
x = tf.math.sqrt(tf.math.square(x) + tf.math.square(y))
```

This returns:
```
Executing op Square in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Square in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AddV2 in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Sqrt in device /job:localhost/replica:0/task:0/device:CPU:0
```

As you can see, `Square` and `Sqrt` are placed on the CPU, but the `AddV2` in between is placed on the GPU. I'll edit the title to reflect this.

**Comment by sushreebarsa** [comment]
@sachinprasadhs I was able to reproduce this issue on colab , please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/dd05c8de1338abea328d9ca18b9f3c99/square_sqrt_ops.ipynb#scrollTo=eiaunmDpLjTA).Thanks!

**Comment by tilakrayal** [comment]
@jmontalt,
I tried to execute the mentioned code on tensorflow v2.15 and it was executed without any issue/error and the output was **14.333333969116211**. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/b30e585100b3e4f28838d873d7c443c3/untitled1807.ipynb). Thank you!
