### ISSUE TITLE
error duing running transflow model

### ISSUE THREAD

**Issue by roboticsai** [tensorflow/tensorflow#5583]
I am following[ this](https://medium.com/jim-fleming/loading-a-tensorflow-graph-with-the-c-api-4caaff88463f#.azr38581z) tutorial:  But as i try to run the loader.cc file after succesfully building it, i get this error: Not found: models/train.pb
I have already copyed the train.pb file into /transflow/transflow/model folder and i also tried to copy this file inside /transflow/bazel-bin/model but it is locked. So how do i remove this error. even after i unlocked the bazel folder and than copied the train.pb file inside models, it shows the same error.

**Comment by girving** [comment]
If you have to unlock folders, you are presumably putting files in the wrong place.  How are you running loader?

**Comment by roboticsai** [comment]
Ok i have solved this proble. sorry that i didn't closed this question.
