### ISSUE TITLE
tf.data.Dataset.from_generator fails when Tensorflow is imported inside an Abseil app

### ISSUE THREAD

**Issue by JossWhittle** [tensorflow/tensorflow#55889]
### Issue Type

Bug

### Source

binary

### Tensorflow Version

https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.8.0-cp38-cp38-manylinux2010_x86_64.whl

### Custom Code

No

### Python version

3.8

### Current Behaviour?

`tf.data.Dataset.from_generator` fails with `Unable to find FunctionDef for __inference_Dataset_from_generator_generator_next_fn_24 in the registry. [Op:MakeIterator]` when tensorflow is imported within the body of a function when called from an Abseil app.

Works when tensorflow is imported the standard way in the script header then called from within the Abseil app.

Works when imported within a non-Abseil app function called from `__main__`.

Only seems to fail when the import occurs inside a function called within an Abseil app.

Only `tf.data.Dataset.from_generator` seems to be affected. Other pipelines can be used without issue and models can be trained on them.

Tested with CPU-only Tensorflow 2.8.0 (also tested with 2.7.0) installed from prebuilt wheel.
- `https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.8.0-cp38-cp38-manylinux2010_x86_64.whl`
- `https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.7.0-cp38-cp38-manylinux2010_x86_64.whl`

---

#### Tensorflow deferred import in absl app function

```python
from absl import app

def main(argv):
    import tensorflow as tf

    print('tf.data.Dataset.range', list(iter(tf.data.Dataset.range(4))))

    def fn():
        yield from range(4)

    ds = tf.data.Dataset.from_generator(fn, output_types=tf.int32, output_shapes=())
    print('tf.data.Dataset.from_generator', list(iter(ds)))

if __name__ == "__main__":
    app.run(main)
```

```
tf.data.Dataset.range [<tf.Tensor: shape=(), dtype=int64, numpy=0>, <tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=2>, <tf.Tensor: shape=(), dtype=int64, numpy=3>]
Traceback (most recent call last):
  File "examples/test2.py", line 19, in <module>
    app.run(main)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "examples/test2.py", line 16, in main
    print('tf.data.Dataset.from_generator', list(iter(ds)))
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 486, in __iter__
    return iterator_ops.OwnedIterator(self)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 755, in __init__
    self._create_iterator(dataset)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 787, in _create_iterator
    gen_dataset_ops.make_iterator(ds_variant, self._iterator_resource)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/gen_dataset_ops.py", line 3319, in make_iterator
    _ops.raise_from_not_ok_status(e, name)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 7186, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unable to find FunctionDef for __inference_Dataset_from_generator_generator_next_fn_24 in the registry. [Op:MakeIterator]
```

---

#### Tensorflow deferred import in normal python function

```python
def main():
    import tensorflow as tf

    print('tf.data.Dataset.range', list(iter(tf.data.Dataset.range(4))))

    def fn():
        yield from range(4)

    ds = tf.data.Dataset.from_generator(fn, output_types=tf.int32, output_shapes=())
    print('tf.data.Dataset.from_generator', list(iter(ds)))

if __name__ == "__main__":
    main()
```

```
tf.data.Dataset.range [<tf.Tensor: shape=(), dtype=int64, numpy=0>, <tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=2>, <tf.Tensor: shape=(), dtype=int64, numpy=3>]
tf.data.Dataset.from_generator [<tf.Tensor: shape=(), dtype=int32, numpy=0>, <tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=3>]
```

---

#### Tensorflow standard import in header before absl app

```python
from absl import app

import tensorflow as tf

def main(argv):

    print('tf.data.Dataset.range', list(iter(tf.data.Dataset.range(4))))

    def fn():
        yield from range(4)

    ds = tf.data.Dataset.from_generator(fn, output_types=tf.int32, output_shapes=())
    print('tf.data.Dataset.from_generator', list(iter(ds)))


if __name__ == "__main__":
    app.run(main)
```

```
tf.data.Dataset.range [<tf.Tensor: shape=(), dtype=int64, numpy=0>, <tf.Tensor: shape=(), dtype=int64, numpy=1>, <tf.Tensor: shape=(), dtype=int64, numpy=2>, <tf.Tensor: shape=(), dtype=int64, numpy=3>]
tf.data.Dataset.from_generator [<tf.Tensor: shape=(), dtype=int32, numpy=0>, <tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=3>]
```

**Comment by sushreebarsa** [comment]
@JossWhittle I tried to replicate the issue on colab ,could you please find this [gist](https://colab.research.google.com/gist/sushreebarsa/af56a395e31b9e8e42ca9b06f7a5c5eb/55889.ipynb) and confirm the same?
Thanks!

**Comment by JossWhittle** [comment]
@sushreebarsa I dont think this can be replicated directly in collab since the environment is different than when executing the app from the command line. 

If you place those three snippets into separate .py files and then !python test1.py to run them from collab that may be enough.

**Comment by JossWhittle** [comment]
@sushreebarsa Please see the following colab gist: https://colab.research.google.com/gist/JossWhittle/1010a5941911507eb82ac8838f7ccedc/55889.ipynb which reproduces the bug by writing the test scripts to files before executing them on the command line.

**Comment by sushreebarsa** [comment]
@JossWhittle Thank you for the update!

@chunduriv I was able to reproduce the issue on colab , please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/134aeb32e8eb89789e694b3d836908ab/55889.ipynb).Thank you!

**Comment by tilakrayal** [comment]
@JossWhittle ,
I tried to execute the test cases test1, test2, test3 .py files on tensorflow v2.15 and observed that all the 3 test cases were executed without any issue/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/f356416b1d6c0804f20e03048c7e6220/untitled1808.ipynb). Thank you!
