### ISSUE TITLE
Summary overwrite earlier models

### ISSUE THREAD

**Issue by andreydung** [tensorflow/tensorflow#5589]
Summary writer overwrites the previous version of models. For example, when I save any model that has (step + 1) % 100 == 0, then when saving model-1299 model-299 is deleted.

### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
-rw-r--r-- 1 root root 189170 Sep 23  2015 /usr/local/cuda-7.5/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Sep 23  2015 /usr/local/cuda-7.5/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Sep 23  2015 /usr/local/cuda-7.5/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 Sep 23  2015 /usr/local/cuda-7.5/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020 Sep 23  2015 /usr/local/cuda-7.5/lib/libcudart_static.a

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.11.0rc0

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
if (step + 1) % 100 == 0:
  saver.save(sess, 'model', global_step = step)

**Comment by girving** [comment]
The `Saver` class has options that control deleting previous checkpoints.  Please see the documentation for details: https://www.tensorflow.org/versions/r0.11/api_docs/python/state_ops.html#Saver
