### ISSUE TITLE
I only have CUDA 8.0 but Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: 

### ISSUE THREAD

**Issue by zsxgb** [tensorflow/tensorflow#5591]
>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3448] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally

**Comment by ohadle** [comment]
I'd suggest installing cuDNN.

**Comment by zsxgb** [comment]
i have install cdunn and cuda

**Comment by girving** [comment]
@zsxgb What platform are you on?  Have you checked `LD_LIBRARY_PATH` or the equivalent?  What is the right path so the cudnn.so file?

**Comment by willdzeng** [comment]
I had same problem before, easy way to fix is to install cudnn into local using
```
tar xvzf cudnn-8.0-linux-x64-v5.1.tgz
sudo cp -P cuda/include/cudnn.h /usr/local/cuda/include
sudo cp -P cuda/lib64/libcudnn* /usr/local/cuda/lib64
sudo chmod a+r /usr/local/cuda/include/cudnn.h /usr/local/cuda/lib64/libcudnn*
```

**Comment by zhanghan328** [comment]
![6239a9335826955468832cd8f76b6bc7](https://cloud.githubusercontent.com/assets/16316669/20485643/7b3a5282-b037-11e6-9480-86ecd5035376.jpg)
I probably have the same problem.  I could import tensorflow perfectly but in spyder2.7 there are mistakes above:
Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH. Who can help me ?

**Comment by prb12** [comment]
@zsxgb and @zhanghan328 Your LD_LIBRARY_PATH environment variables are not set.  
Please follow the instructions here: https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#optional-linux-enable-gpu-support

Please feel free to reopen this issue if the above instructions do not fix your problem.

**Comment by xapcloud** [comment]
Have you solved the problems? I have set the LD_LIBRARY_PATH environment and also useless....oops

**Comment by zzks** [comment]
Same problem. @prb12  I have set LD_LIBRARY_PATH.
BTW, I can import&use TF successfully 3 weeks ago in the same PC.
I haven't touch cuda related file. Strange...

**Comment by tigerneil** [comment]
Extract the cuDNN archive to a directory of your choice, referred to below as <installpath>.
Then follow the platform-specific instructions as follows.

LINUX

    cd <installpath>
    export LD_LIBRARY_PATH=`pwd`:$LD_LIBRARY_PATH

    Add <installpath> to your build and link process by adding -I<installpath> to your compile
    line and -L<installpath> -lcudnn to your link line.

It works for me.
