### ISSUE TITLE
TfLite for Microcontrollers giving hybrid error

### ISSUE THREAD

**Issue by ttxxdd123** [tensorflow/tensorflow#55928]
I converted my keras .h5 file to a quantized tflite in order to run on the new stm32f746   but when I run it I get an error saying "Hybrid Models are not supported on TFLite Micro."

I'm not sure why my model is appearing as hybrid; the code I used to convert is below:

`      model = keras.models.load_model('2D_2CHAN_32_T1_model_2021-09-17_11-27-55.h5')
       converter = tf.lite.TFLiteConverter.from_keras_model(model)
       converter.optimizations = [tf.lite.Optimize.DEFAULT]
       converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
       tflite_model = converter.convert()
       source_text, header_text = convert_bytes_to_c_source(tflite_model,"best_2Duint8")
           with  open('best_2Duint8.h',  'w')  as  file:
                 file.write(header_text)
           with  open('best_2Duint8.cc',  'w')  as  file:
                 file.write(source_text)`

If I didn't do the quantization, I could have used the input of Float32 to get the right result, but the model was too big and too slow. If I quantify it, I get the same error whether I change the input to uint8_t or uint16_t.

Error message:../tensorflow/tensorflow/lite/micro/kernels/conv.cc Hybrid models are not supported on TFLite Micro. Node CONV_2D (number 4) failed to invoke with status 1

I'd appreciate if someone could guide me if I'm doing something wrong or if there is a better way to convert it.

**Comment by mohantym** [comment]
Ok @ttxxdd123 ! Here are two things I suggest you to try.

1. Use [xxd converter](https://www.tensorflow.org/lite/microcontrollers/build_convert#convert_to_a_c_array) to get the C files from lite models.
2. Fully quantize the model using [post training quantization](https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only) (use a representative Dataset to do so)

Attaching relevant [thread ](https://forums.openmv.io/t/error-while-using-tf-load-on-custom-tflite-model/1917/3)for reference. Thanks!

**Comment by ttxxdd123** [comment]
> 行@ttxxdd123！我建议您试用以下版本转换为两件事情（您使用 2.8 版本转换为精简版文件）
> 
> 1. 使用[xxd视频](https://www.tensorflow.org/lite/microcontrollers/build_convert#convert_to_a_c_array)从lite模型中获取C文件。
> 2. [使用训练后精确](https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only)量化模型（使用典型数据集来执行此）
> 
> 附上相关处理[以](https://forums.openmv.io/t/error-while-using-tf-load-on-custom-tflite-model/1917/3)供参考。谢谢！

Thank you, I have read this useful information. I think quantizing to float16 is the most convenient way, but I'm not sure how to change the input of float32 type to float16 in a microcontroller

**Comment by ttxxdd123** [comment]
> Ok @ttxxdd123 ! Here are two things I suggest you to try (Assuming you are using 2.8 version for conversion to lite file)
> 
> 1. Use [xxd converter](https://www.tensorflow.org/lite/microcontrollers/build_convert#convert_to_a_c_array) to get the C files from lite models.
> 2. Fully quantize the model using [post training quantization](https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only) (use a representative Dataset to do so)
> 
> Attaching relevant [thread ](https://forums.openmv.io/t/error-while-using-tf-load-on-custom-tflite-model/1917/3)for reference. Thanks!

I've run it successfully with full integer quantization, and I'm still using float32 for input and output, reducing the size of the model by more than half and improving the speed by about 30%

**Comment by mohantym** [comment]
@ttxxdd123 ! Thanks for the confirmation . Feel free to move this issue to closed status if it helped . Thanks!

**Comment by ADIsullivanLiu** [comment]
> > Ok @ttxxdd123 ! Here are two things I suggest you to try (Assuming you are using 2.8 version for conversion to lite file)
> > 
> > 1. Use [xxd converter](https://www.tensorflow.org/lite/microcontrollers/build_convert#convert_to_a_c_array) to get the C files from lite models.
> > 2. Fully quantize the model using [post training quantization](https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only) (use a representative Dataset to do so)
> > 
> > Attaching relevant [thread ](https://forums.openmv.io/t/error-while-using-tf-load-on-custom-tflite-model/1917/3)for reference. Thanks!
> 
> I've run it successfully with full integer quantization, and I'm **still using float32 for input and output**, reducing the size of the model by more than half and improving the speed by about 30%

Hi @ttxxdd123, I have the same issue in using hybrid quantization in tflite micro
-  intput & output = float32
-  filter = int8,
could you please share some information of how to use float32 for input and output
