### ISSUE TITLE
Tensorflow GPU Cannot assign a device for operation MatMul

### ISSUE THREAD

**Issue by John-yovoa** [tensorflow/tensorflow#55930]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

1.15.0 gpu version

### Custom Code

No

### OS Platform and Distribution

RHEL 7.9

### Python version

3.7

### GCC/Compiler version

gcc (GCC) 4.8.5 20150623

### CUDA/cuDNN version

cuda 11.0 and driver version: 450.80.02

### Current Behaviour?

```shell
Tensor flow

tensorflow                         2.4.0
tensorflow-estimator               1.15.1
tensorflow-gpu                     1.15.0
tensorflow-io-gcs-filesystem       0.25.0

Below is the code from documentation
```

### Standalone code to reproduce the issue

```shell
Here is the code

import numpy as np
#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import datetime

# Processing Units logs
log_device_placement = True

# Num of multiplications to perform
n = 10

'''
Example: compute A^n + B^n on 2 GPUs
Results on 8 cores with 2 GTX-980:
 * Single GPU computation time: 0:00:11.277449
 * Multi GPU computation time: 0:00:07.131701
'''
# Create random large matrix
A = np.random.rand(2000, 2000).astype('float32')
B = np.random.rand(2000, 2000).astype('float32')

# Create a graph to store results
c1 = []
c2 = []

def matpow(M, n):
    if n < 1: #Abstract cases where n < 1
        return M
    else:
        return tf.matmul(M, matpow(M, n-1))

'''
Single GPU computing
'''
with tf.device('/gpu:0'):
    a = tf.placeholder(tf.float32, [2000, 2000])
    b = tf.placeholder(tf.float32, [2000, 2000])
    # Compute A^n and B^n and store results in c1
    c1.append(matpow(a, n))
    c1.append(matpow(b, n))

with tf.device('/cpu:0'):
    sum = tf.add_n(c1) #Addition of all elements in c1, i.e. A^n + B^n

t1_1 = datetime.datetime.now()
with tf.Session(config=tf.ConfigProto(log_device_placement=log_device_placement)) as sess:
    # Run the op.
    sess.run(sum, {a:A, b:B})
t2_1 = datetime.datetime.now()


'''
Multi GPU computing
'''
# GPU:0 computes A^n
with tf.device('/gpu:0'):
    # Compute A^n and store result in c2
    a = tf.placeholder(tf.float32, [2000, 2000])
    c2.append(matpow(a, n))

# GPU:1 computes B^n
with tf.device('/gpu:1'):
    # Compute B^n and store result in c2
    b = tf.placeholder(tf.float32, [2000, 2000])
    c2.append(matpow(b, n))

with tf.device('/cpu:0'):
    sum = tf.add_n(c2) #Addition of all elements in c2, i.e. A^n + B^n

t1_2 = datetime.datetime.now()
with tf.Session(config=tf.ConfigProto(log_device_placement=log_device_placement)) as sess:
    # Run the op.
    sess.run(sum, {a:A, b:B})
t2_2 = datetime.datetime.now()


print("Single GPU computation time: " + str(t2_1-t1_1))
print("Multi GPU computation time: " + str(t2_2-t1_2))
```

### Relevant log output

After executed the code got following warning message

WARNING:tensorflow:From /opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/compat/v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Device mapping:
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:0 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:1 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:2 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:3 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:4 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:5 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:6 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:7 -> device: XLA_GPU device

then got below error

```shell
Error log:

InvalidArgumentError                      Traceback (most recent call last)
/opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

/opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1347       # Ensure any changes to the graph are reflected in the runtime.
-> 1348       self._extend_graph()
   1349       return self._call_tf_sessionrun(options, feed_dict, fetch_list,

/opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _extend_graph(self)
   1387     with self._graph._session_run_lock():  # pylint: disable=protected-access
-> 1388       tf_session.ExtendSession(self._session)
   1389 

InvalidArgumentError: Cannot assign a device for operation MatMul: {{node MatMul}} was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:1, /job:localhost/replica:0/task:0/device:XLA_GPU:2, /job:localhost/replica:0/task:0/device:XLA_GPU:3, /job:localhost/replica:0/task:0/device:XLA_GPU:4, /job:localhost/replica:0/task:0/device:XLA_GPU:5, /job:localhost/replica:0/task:0/device:XLA_GPU:6, /job:localhost/replica:0/task:0/device:XLA_GPU:7 ]. Make sure the device specification refers to a valid device.
	 [[MatMul]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-1-f301b9bff9d4> in <module>
     47 with tf.Session(config=tf.ConfigProto(log_device_placement=log_device_placement)) as sess:
     48     # Run the op.
---> 49     sess.run(sum, {a:A, b:B})
     50 t2_1 = datetime.datetime.now()
     51 

/opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    954     try:
    955       result = self._run(None, fetches, feed_dict, options_ptr,
--> 956                          run_metadata_ptr)
    957       if run_metadata:
    958         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1178     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1179       results = self._do_run(handle, final_targets, final_fetches,
-> 1180                              feed_dict_tensor, options, run_metadata)
   1181     else:
   1182       results = []

/opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1357     if handle is None:
   1358       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1359                            run_metadata)
   1360     else:
   1361       return self._do_call(_prun_fn, handle, feeds, fetches)

/opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1382                     '\nsession_config.graph_options.rewrite_options.'
   1383                     'disable_meta_optimizer = True')
-> 1384       raise type(e)(node_def, op, message)
   1385 
   1386   def _extend_graph(self):

InvalidArgumentError: Cannot assign a device for operation MatMul: node MatMul (defined at /opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748)  was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:1, /job:localhost/replica:0/task:0/device:XLA_GPU:2, /job:localhost/replica:0/task:0/device:XLA_GPU:3, /job:localhost/replica:0/task:0/device:XLA_GPU:4, /job:localhost/replica:0/task:0/device:XLA_GPU:5, /job:localhost/replica:0/task:0/device:XLA_GPU:6, /job:localhost/replica:0/task:0/device:XLA_GPU:7 ]. Make sure the device specification refers to a valid device.
	 [[MatMul]]
```
</details>

**Comment by chunduriv** [comment]
@John-yovoa,

Here the `GPU` card is not installed properly, so it causes the above issue when you are trying to perform the `MatMul` operation on `/device:GPU:0`.

Please refer to the stack trace for available device mapping.

```
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:0 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:1 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:2 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:3 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:4 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:5 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:6 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:7 -> device: XLA_GPU device
```

> tensorflow                         2.4.0
> tensorflow-estimator               1.15.1
> tensorflow-gpu                     1.15.0

Please uninstall the `TF 2.4.0` version from your machine and try to use `TF1.15.0`, since your code is compatible with `TF1.x`. `cuDNN -7.4`, `CUDA -10` are compatible versions for `TF1.15.0`. For more details, you can refer to [tested build configurations](https://www.tensorflow.org/install/source#gpu) and [GPU Support](https://www.tensorflow.org/install/gpu).

I am successfully able to execute code using `TF1.15.0` on Colab. Please find the [gist](https://colab.research.google.com/gist/chunduriv/ee0e47bdf71f55b792933900a25aa667/55930.ipynb) for reference. Thank you.

**Comment by John-yovoa** [comment]
Hi @chunduriv thank you for the reply! as you mentioned I've uninstalled TF 2.4x and installed TF1.15.0 but still ran into same issue .. Here are my TF versions

pip list |grep -i tensorflow
tensorflow                         1.15.0
tensorflow-estimator         1.15.1
tensorflow-gpu                  1.15.0
tensorflow-io-gcs-filesystem       0.25.0

Code executed:

`import numpy as np
import tensorflow as tf
print(tf.__version__)
#import tensorflow.compat.v1 as tf
#tf.disable_v2_behavior()
import datetime

# Processing Units logs
log_device_placement = True

# Num of multiplications to perform
n = 10

'''
Example: compute A^n + B^n on 2 GPUs
Results on 8 cores with 2 GTX-980:
 * Single GPU computation time: 0:00:11.277449
 * Multi GPU computation time: 0:00:07.131701
'''
# Create random large matrix
A = np.random.rand(5, 5).astype('float32')
B = np.random.rand(5, 5).astype('float32')

# Create a graph to store results
c1 = []
c2 = []

def matpow(M, n):
    if n < 1: #Abstract cases where n < 1
        return M
    else:
        return tf.matmul(M, matpow(M, n-1))

'''
Single GPU computing
'''
with tf.device('/gpu:0'):
    a = tf.placeholder(tf.float32, [5, 5])
    b = tf.placeholder(tf.float32, [5, 5])
    # Compute A^n and B^n and store results in c1
    c1.append(matpow(a, n))
    c1.append(matpow(b, n))

with tf.device('/gpu:0'):
  test=tf.matmul(a, b)

with tf.device('/cpu:0'):
    sum = tf.add_n(c1) #Addition of all elements in c1, i.e. A^n + B^n

t1_1 = datetime.datetime.now()
with tf.Session(config=tf.ConfigProto(log_device_placement=log_device_placement)) as sess:
    # Run the op.
    sess.run(sum, {a:A, b:B})
t2_1 = datetime.datetime.now()

print(c1)
print(test)
print(sum)
print("Single GPU computation time: " + str(t2_1-t1_1))`


Error message:

1.15.0
Device mapping:
/job:localhost/replica:0/task:0/device:XLA_CPU:0 -> device: XLA_CPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:0 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:1 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:2 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:3 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:4 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:5 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:6 -> device: XLA_GPU device
/job:localhost/replica:0/task:0/device:XLA_GPU:7 -> device: XLA_GPU device

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

/opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1347       # Ensure any changes to the graph are reflected in the runtime.
-> 1348       self._extend_graph()
   1349       return self._call_tf_sessionrun(options, feed_dict, fetch_list,

/opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _extend_graph(self)
   1387     with self._graph._session_run_lock():  # pylint: disable=protected-access
-> 1388       tf_session.ExtendSession(self._session)
   1389 

InvalidArgumentError: Cannot assign a device for operation MatMul: {{node MatMul}} was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:1, /job:localhost/replica:0/task:0/device:XLA_GPU:2, /job:localhost/replica:0/task:0/device:XLA_GPU:3, /job:localhost/replica:0/task:0/device:XLA_GPU:4, /job:localhost/replica:0/task:0/device:XLA_GPU:5, /job:localhost/replica:0/task:0/device:XLA_GPU:6, /job:localhost/replica:0/task:0/device:XLA_GPU:7 ]. Make sure the device specification refers to a valid device.
	 [[MatMul]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-1-79c3fd56ef5e> in <module>
     51 with tf.Session(config=tf.ConfigProto(log_device_placement=log_device_placement)) as sess:
     52     # Run the op.
---> 53     sess.run(sum, {a:A, b:B})
     54 t2_1 = datetime.datetime.now()
     55 

/opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    954     try:
    955       result = self._run(None, fetches, feed_dict, options_ptr,
--> 956                          run_metadata_ptr)
    957       if run_metadata:
    958         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1178     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1179       results = self._do_run(handle, final_targets, final_fetches,
-> 1180                              feed_dict_tensor, options, run_metadata)
   1181     else:
   1182       results = []

/opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1357     if handle is None:
   1358       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1359                            run_metadata)
   1360     else:
   1361       return self._do_call(_prun_fn, handle, feeds, fetches)

/opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1382                     '\nsession_config.graph_options.rewrite_options.'
   1383                     'disable_meta_optimizer = True')
-> 1384       raise type(e)(node_def, op, message)
   1385 
   1386   def _extend_graph(self):

InvalidArgumentError: Cannot assign a device for operation MatMul: node MatMul (defined at /opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748)  was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:1, /job:localhost/replica:0/task:0/device:XLA_GPU:2, /job:localhost/replica:0/task:0/device:XLA_GPU:3, /job:localhost/replica:0/task:0/device:XLA_GPU:4, /job:localhost/replica:0/task:0/device:XLA_GPU:5, /job:localhost/replica:0/task:0/device:XLA_GPU:6, /job:localhost/replica:0/task:0/device:XLA_GPU:7 ]. Make sure the device specification refers to a valid device.
	 [[MatMul]]

Thanks again for the help!

**Comment by chunduriv** [comment]
@John-yovoa,

> InvalidArgumentError: Cannot assign a device for operation MatMul: node MatMul (defined at /opt/miniconda3/envs/PY37/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:1, /job:localhost/replica:0/task:0/device:XLA_GPU:2, /job:localhost/replica:0/task:0/device:XLA_GPU:3, /job:localhost/replica:0/task:0/device:XLA_GPU:4, /job:localhost/replica:0/task:0/device:XLA_GPU:5, /job:localhost/replica:0/task:0/device:XLA_GPU:6, /job:localhost/replica:0/task:0/device:XLA_GPU:7 ]. Make sure the device specification refers to a valid device.
> [[MatMul]]

The above error clearly describes the problem here, the `GPU` device is not available to perform the `MatMul` operation.

Can you please run the below code snippet on your machine and let us know the output? 

```
import tensorflow as tf
tf.test.is_gpu_available()
```
Thanks!

**Comment by John-yovoa** [comment]
@chunduriv  I got the output as "false"
![tf-git](https://user-images.githubusercontent.com/63085641/167238668-4fc94e68-b563-46a0-afac-a2db0bd473f3.PNG)

Thank you!

**Comment by chunduriv** [comment]
@John-yovoa,

>@chunduriv I got the output as "false"

This means, the GPU is not installed properly on your machine. Can you let us know your GPU Card details? 

`CUDA - 10.0` and `cuDNN - 7.4` are compatible for `TF1.15`. If you have a different combination of the same, please can you try as mentioned versions, will solve the problem. Thank you.

**Comment by John-yovoa** [comment]
@chunduriv  we have GPU cards installed and we are using GPU cards working for other packages except TF. I tried several different TF versions but none of them worked.. Here is the nvidia-smi output

we are using cuda version: 11
driver version: 450.80
`Mon May  9 12:52:45 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:17.0 Off |                    0 |
| N/A   45C    P0    71W / 149W |    980MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000000:00:18.0 Off |                    0 |
| N/A   54C    P0    60W / 149W |    132MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           Off  | 00000000:00:19.0 Off |                    0 |
| N/A   46C    P0    72W / 149W |    134MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           Off  | 00000000:00:1A.0 Off |                    0 |
| N/A   56C    P0    59W / 149W |    134MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  Tesla K80           Off  | 00000000:00:1B.0 Off |                    0 |
| N/A   43C    P0    71W / 149W |    134MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  Tesla K80           Off  | 00000000:00:1C.0 Off |                    0 |
| N/A   51C    P0    60W / 149W |    134MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  Tesla K80           Off  | 00000000:00:1D.0 Off |                    0 |
| N/A   38C    P0    70W / 149W |    134MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  Tesla K80           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   51C    P0    60W / 149W |    134MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
`

Thank you

**Comment by chunduriv** [comment]
@John-yovoa ,

Every `Tensorflow GPU` release is compatible with certain versions of `CUDA` and `cuDNN`. 

>we are using cuda version: 11

In your case, `TF1.15` is compatible with `CUDA:10.0` and `cuDNN:7.4`. For more details please refer to the [tested build configurations document](https://www.tensorflow.org/install/source#gpu). 

As we are not actively supporting `TF1.x`, please upgrade it to the latest stable version [2.8](https://www.tensorflow.org/install/source#linux) with `CUDA:11.2` and `cuDNN:8.1` and check if you are facing the same error. Thank you.

**Comment by John-yovoa** [comment]
I've installed tensorflow GPU and cpu both 2.8.0 but didn't helped :(

**Comment by chunduriv** [comment]
@John-yovoa,

To investigate further, Could you share steps that you have followed to install TF on your machine? 

Could you run the below code snippet and let us know the output?

```
import tensorflow as tf
print(tf.__version__)
tf.config.list_physical_devices('GPU')
```
Thank you.

**Comment by John-yovoa** [comment]
![image](https://user-images.githubusercontent.com/63085641/170168354-4eb4f5d2-0272-4958-8542-4cf0a2d0d03a.png)

sorry for the delayed response, screenshot attached for reference

I installed TF like 

pip install tensorflow==<version>
pip install tensoorflow-gpu==<version>
[](url)

**Comment by John-yovoa** [comment]
hello, could you please re-open the case
