### ISSUE TITLE
could not download Bazel: HTTP GET https://releases.bazel.build/5.1.1

### ISSUE THREAD

**Issue by catqaq** [tensorflow/tensorflow#55945]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tensorflow from your tensorflow/tensorflow:devel

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04.4 LTS

### Mobile device

android

### Python version

3.8

### Bazel version

no

### GCC/Compiler version

gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 

### CUDA/cuDNN version

no

### GPU model and memory

no cuda

### Current Behaviour?

```shell
Hi, i followed your tutorial<https://www.tensorflow.org/lite/android/lite_build#set_up_build_environment_using_docker> to build tensorflow and tflite in a docker. I got a network error:
+ bazel build -c opt --cxxopt=--std=c++14 --fat_apk_cpu=arm64-v8a,armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain //tmp:tensorflow-lite
2022/05/06 09:48:55 Downloading https://releases.bazel.build/5.1.1/release/bazel-5.1.1-linux-x86_64...
2022/05/06 09:49:00 could not download Bazel: HTTP GET https://releases.bazel.build/5.1.1/release/bazel-5.1.1-linux-x86_64 failed: Get "https://releases.bazel.build/5.1.1/release/bazel-5.1.1-linux-x86_64": read tcp 172.17.0.14:54726->130.211.22.235:443: read: connection reset by peer

I tried to install bazel in advance, but the same problem still occurred. It seems that the bazel installed by myself did not take effect. When running the bazel command, I still tried to download bazel 5.1.1, and then failed due to network problems.
/tensorflow_src# bazel
2022/05/06 09:58:01 Downloading https://releases.bazel.build/5.1.1/release/bazel-5.1.1-linux-x86_64...
2022/05/06 09:58:02 could not download Bazel: HTTP GET https://releases.bazel.build/5.1.1/release/bazel-5.1.1-linux-x86_64 failed: Get "https://releases.bazel.build/5.1.1/release/bazel-5.1.1-linux-x86_64": read tcp 172.17.0.14:54934->130.211.22.235:443: read: connection reset by peer
```

### Standalone code to reproduce the issue

```shell
1.follow your tutorial:https://www.tensorflow.org/lite/android/lite_build#set_up_build_environment_using_docker
2.build:
bash tensorflow/lite/tools/build_aar.sh --input_models=model.tflite --target_archs=arm64-v8a,armeabi-v7a
```

### Relevant log output

_No response_</details>

**Comment by catqaq** [comment]
@mohantym @sachinprasadhs Hi, one more thing **<html>
<body>


tensorflow-2.8.0 | 3.7-3.10 | GCC 7.3.1 | Bazel 4.2.1
-- | -- | -- | --



</body>
</html>**

**Comment by catqaq** [comment]
@karimnosseir @sachinprasadhs @mohantym Hi, I give up to use docker and tried to build tflite aar in windows. Unfortunately, the network problem persists. Any idea to use local file instead of downloading to avoid network error? I tried to use local file, but it seems something wrong.
`
http_archive(
        name = "io_bazel_rules_closure",
        sha256 = "5b00383d08dd71f28503736db0500b6fb4dda47489ff5fc6bed42557c07c6ba9",
        strip_prefix = "rules_closure-308b05b2419edb5c8ee0471b67a40403df940149",
        urls = [
            "file:../tensorflow/third_party:308b05b2419edb5c8ee0471b67a40403df940149.tar.gz",
            "https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz",
            "https://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz",  # 2019-06-13
        ],
    )
http_archive(
        name = "rules_pkg",
        sha256 = "352c090cc3d3f9a6b4e676cf42a6047c16824959b438895a76c2989c6d7c246a",
        urls = [
            "file:../tensorflow/third_party:rules_pkg-0.2.5.tar.gz",
            "https://github.com/bazelbuild/rules_pkg/releases/download/0.2.5/rules_pkg-0.2.5.tar.gz",
            "https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.2.5/rules_pkg-0.2.5.tar.gz",
        ],
    )
http_archive(
    name = "llvm-raw",
    build_file_content = "# empty",
    sha256 = LLVM_SHA256,
    strip_prefix = "llvm-project-" + LLVM_COMMIT,
    urls = [
    "file:///third_party:llvm-project-55c71c9eac9bc7f956a05fa9258fad4f86565450.tar.gz",
    ],
)
tf_http_archive(
        name = "tf_runtime",
        sha256 = TFRT_SHA256,
        strip_prefix = "runtime-{commit}".format(commit = TFRT_COMMIT),
        #urls = tf_mirror_urls("https://github.com/tensorflow/runtime/archive/{commit}.tar.gz".format(commit = TFRT_COMMIT)),
        urls = ["file:../tensorflow/third_party:runtime-c3e082762b7664bbc7ffd2c39e86464928e27c0c.tar.gz"],
        # A patch file can be provided for atomic commits to both TF and TFRT.
        # The job that bumps the TFRT_COMMIT also resets patch_file to 'None'.
        patch_file = None,
    )
`
INFO: Found applicable config definition build:monolithic in file d:\tensorflow\tensorflow-r2.8\.bazelrc: --define framework_shared_object=false
ERROR: Traceback (most recent call last):
        File "D:/tensorflow/tensorflow-r2.8/WORKSPACE", line 11, column 14, in <toplevel>
                tf_workspace3()
        File "D:/tensorflow/tensorflow-r2.8/tensorflow/workspace3.bzl", line 29, column 15, in workspace
                tf_runtime()
        File "D:/tensorflow/tensorflow-r2.8/third_party/tf_runtime/workspace.bzl", line 12, column 20, in repo
                tf_http_archive(
        File "D:/tensorflow/tensorflow-r2.8/third_party/repo.bzl", line 110, column 13, in tf_http_archive
                fail("tf_http_archive(urls) must have redundant URLs.")
Error in fail: tf_http_archive(urls) must have redundant URLs.
ERROR: error loading package '': in D:/tensorflow/tensorflow-r2.8/tensorflow/workspace2.bzl: in D:/tensorflow/tensorflow-r2.8/third_party/llvm/setup.bzl: Encountered error while reading extension file 'utils/bazel/configure.bzl': no such package '@llvm-raw//utils/bazel': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.115s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by catqaq** [comment]
I also tried to build bazel from scratch, but it still Build Bazel with Bazel. So, got the network error too.

root@9e54466822ea:/bazel-4.2.1-dist# env EXTRA_BAZEL_ARGS="--tool_java_runtime_version=**local_jdk**" bash ./compile.sh
🍃  **Building Bazel from scratch**......
🍃  **Building Bazel with Bazel**.
DEBUG: /tmp/bazel_W5uGPzng/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:14: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '3.1.0'
DEBUG: /tmp/bazel_W5uGPzng/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1804_java11 not using checked in configs as detect_java_home was set to True 
DEBUG: /tmp/bazel_W5uGPzng/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:14: 
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '3.1.0'
DEBUG: /tmp/bazel_W5uGPzng/out/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:103:14: rbe_ubuntu1604_java8 not using checked in configs as detect_java_home was set to True 
INFO: Repository remotejdk11_linux instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:52:6: in <toplevel>
  /tmp/bazel_W5uGPzng/out/external/bazel_tools/tools/build_defs/repo/utils.bzl:201:18: in maybe
Repository rule http_archive defined at:
  /tmp/bazel_W5uGPzng/out/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://mirror.bazel.build/openjdk/azul-zulu11.37.17-ca-jdk11.0.6/zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz failed: class java.net.SocketException Connection reset
ERROR: An error occurred during the fetch of repository '**remotejdk11_linux**':
   Traceback (most recent call last):
	File "/tmp/bazel_W5uGPzng/out/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.37.17-ca-jdk11.0.6/zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz] to /tmp/bazel_W5uGPzng/out/external/remotejdk11_linux/temp11030591926562750233/zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz: Connection reset
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/tmp/bazel_W5uGPzng/out/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.37.17-ca-jdk11.0.6/zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz] to /tmp/bazel_W5uGPzng/out/external/remotejdk11_linux/temp11030591926562750233/zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz: Connection reset
ERROR: /tmp/bazel_W5uGPzng/out/external/bazel_tools/tools/jdk/BUILD:490:6: @bazel_tools//tools/jdk:remote_jdk11 depends on @remotejdk11_linux//:jdk in repository @remotejdk11_linux which failed to fetch. no such package '@remotejdk11_linux//': java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.37.17-ca-jdk11.0.6/zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz] to /tmp/bazel_W5uGPzng/out/external/remotejdk11_linux/temp11030591926562750233/zulu11.37.17-ca-jdk11.0.6-linux_x64.tar.gz: Connection reset
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: Analysis failed
INFO: Elapsed time: 19.818s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (333 packages loaded, 8366 targets\
 configured)

ERROR: Could not build Bazel

**Comment by catqaq** [comment]
@karimnosseir @sachinprasadhs @mohantym Hi, Can we download all dependencies at once and load them locally? Currently I can only handle network errors for each package one by one, download the package first, and change the url to a local path, which is too time consuming.

**Comment by sachinprasadhs** [comment]
Hi, Did you follow [this](https://www.tensorflow.org/lite/android/lite_build#set_up_build_environment_without_docker) document to setup build without docker.

**Comment by catqaq** [comment]
Hi, of course I did, but failed for network error.

> Hi, Did you follow [this](https://www.tensorflow.org/lite/android/lite_build#set_up_build_environment_without_docker) document to setup build without docker.

**Comment by pjpratik** [comment]
Hi @catqaq 

I was checking if the issue still persists. Can you try with latest r2.12 version which requires Bazel 5.3.0 as per [build configuration](https://www.tensorflow.org/install/source#tested_build_configurations). 

I have tested on arm64 with Bazel 5.3.0 and able build the `tensorflow-lite.aar` file without any error. Please find the screenshot below.

<img width="560" alt="Screenshot 2023-04-21 at 7 32 13 PM" src="https://user-images.githubusercontent.com/118897289/233656993-131aee82-cb2a-4e12-90f1-26af37a22324.png">

Thanks.
