### ISSUE TITLE
When using Lambda, the output of the 1/x process is very likely to have nan/inf

### ISSUE THREAD

**Issue by Crystal-yyy** [tensorflow/tensorflow#55956]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf2.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-74-generic x86_64)

### GCC/Compiler version

gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

### CUDA/cuDNN version

CUDA Version: 11.2

### Current Behaviour?

```shell
When using Lambda, the output of the 1/x process is very likely to have nan/inf.  In some cases, the operator will not show output-nan/inf, but will show output-nan/inf. Scenarios, where this happens with lambda, are generally: when the lambda expression carried in the lambda operator has certain risks (the operator does not impose certain constraints on its expression).
```

### Standalone code to reproduce the issue

```shell
[{'name': 'ReduceMax', 'params': {'keep_dims': True, 'dim': 1, 'tensor_space': 4}}, {'name': 'Upsample2d', 'params': {'scale_factor': 2, 'mode': 'nearest'}}, {'name': 'Lambda', 'params': {'output_shape': [2, 32, 3], 'function': 'lambda x: 1 / x**0.5 + 1.0'}}, {'name': 'Flatten'}, {'name': 'Dense', 'params': {'in_features': 192, 'out_features': 200}}, {'name': 'Softmax'}]
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@Crystal-yyy 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!
