### ISSUE TITLE
3D SSIM 

### ISSUE THREAD

**Issue by llodds** [tensorflow/tensorflow#55958]
Hi, is it possible to add 3D SSIM (batched) into TensorFlow? We need this feature for 3D inference. Currently `tf.image.ssim` only accepts batched 2D input. 

If not, is there any internal beta version of 3D SSIM for try-out? 

Thanks.

**Comment by tilakrayal** [comment]
@llodds ,
Can you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thanks!

**Comment by llodds** [comment]
@tilakrayal 
Currently `tf.image` only implements 2D SSIM. We need 3D version of SSIM. SSIM is used to infer for the fidelity of the 3D inference output. The alternative solution right now is the `sciki-learn` CPU version of 3D SSIM, which runs very slow (~3000 128x128x128 inference samples and run 3D SSIM for 20 times between each sample and their mean), even after parallelization done on a high-end CPU node. It could be very helpful if the 3D SSIM is implemented in TF, automatically target on GPU, and then we can parallelize the inference and the post-processing step across multiple GPUs directly. Thanks.

**Comment by llodds** [comment]
I wrote a quick solution using `CuPy`. Now is 3D, but could be potentially extended to ND. ~100 times faster on a V100 than skimage on CascadeLake CPU. 

Here is the link for anyone who is also struggling on this topic: 
https://github.com/llodds/HPC_demos/blob/master/ssim3d.py

Feel free to close this ticket.

**Comment by sachinprasadhs** [comment]
Closing this issue as per the above comment, Thanks
