### ISSUE TITLE
how to save checkpoint in between each epochs and retain them after and continue ?

### ISSUE THREAD

**Issue by Sanjay2802** [tensorflow/tensorflow#55972]
how to save checkpoint in Google colab while training for tflite , save checkpoint after  each epochs and continue after...

**Comment by mohantym** [comment]
Hi @Sanjay2802 ! You can use callbacks along ModelCheckPoint to save weights in Checkpoints During training  . Then you will able to call saving part using concrete function during on device training for lite models. Attaching relevant thread for reference.[1](https://stackoverflow.com/questions/61046870/how-to-save-weights-of-keras-model-for-each-epoch#:~:text=To%20save%20weights%20every%20epoch,known%20as%20callbacks%20in%20Keras.&text=checkpoint%20%3D%20ModelCheckpoint) , [2](https://www.tensorflow.org/lite/examples/on_device_training/overview#save_the_trained_weights). Thank you!

**Comment by Sanjay2802** [comment]
But where to include that .... 
Example : https://colab.research.google.com/github/khanhlvg/tflite_raspberry_pi/blob/main/object_detection/Train_custom_model_tutorial.ipynb#scrollTo=l4QQTXHHATDS

**Comment by mohantym** [comment]
@Sanjay2802 ! This approach won't work on TFlite model maker . @sachinprasadhs ! Could please you look at this issue? Thanks

**Comment by Sanjay2802** [comment]
Is there any way

**Comment by sachinprasadhs** [comment]
Hi, for Object detection you can use model maker to load saved checkpoints to your model and continue training.
You can refer [this](https://www.tensorflow.org/lite/tutorials/model_maker_object_detection) document for end to end example and usage. Thanks!

**Comment by Sanjay2802** [comment]
Help me to use that in this example : https://colab.research.google.com/github/khanhlvg/tflite_raspberry_pi/blob/main/object_detection/Train_custom_model_tutorial.ipynb#scrollTo=l4QQTXHHATDS

**Comment by Sanjay2802** [comment]
Found anything ?

**Comment by sachinprasadhs** [comment]
In the spec which you are creating for `efficientdet_lite0`, you can pass `grad_checkpoint=True` to `hparams` parameter, which will save checkpoint for each epoch.
To use the saved checkpoints and continue the training process, you can follow the answer suggested in the post [here](https://stackoverflow.com/questions/69444878/).

**Comment by Sanjay2802** [comment]
Checkpoints saved sucessfully, but can't load checkpoint after interruption 
![Screenshot_20220516-112630](https://user-images.githubusercontent.com/86015315/168528703-05caec7c-bb2f-416f-98ae-0266e3fd4615.jpg)

**Comment by Sanjay2802** [comment]
Please help me with this

**Comment by mohantym** [comment]
Hi @Sanjay2802 !
We are checking to see whether you still need help in this issue .

Could you check the resolved[ gist](https://colab.sandbox.google.com/gist/mohantym/817321bee851de94b22c20c5d09bf6a7/model-maker-object-detection-for-android-figurine.ipynb#scrollTo=R7AuEriD2r84) and let us know whether it solves the query on loading  weights from check points and resume training from that.

Thank you!
