### ISSUE TITLE
pip error: No such file or directory: '/tmp/pip-...-build/setup.py'

### ISSUE THREAD

**Issue by markusdr** [tensorflow/tensorflow#56]
I'm getting the following error when trying to install on a GPU desktop using pip as described in the [tensorflow setup page](http://tensorflow.org/get_started/os_setup.md):

    $ sudo pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
    Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
      Downloading tensorflow-0.5.0-cp27-none-linux_x86_64.whl (50.5Mb): 50.5Mb downloaded
      Running setup.py egg_info for package from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl
        Traceback (most recent call last):
          File "<string>", line 14, in <module>
        IOError: [Errno 2] No such file or directory: '/tmp/pip-kYFqUa-build/setup.py'
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
      File "<string>", line 14, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-kYFqUa-build/setup.py'

See [this Stackoverflow page](http://stackoverflow.com/questions/2204811/pip-install-a-python-package-without-a-setup-py-file) that discusses the problem and indicates that a `setup.py` file is missing in the package.

**Comment by markusdr** [comment]
Upgrading pip to the latest version has solved this issue.

**Comment by vrv** [comment]
@markusdr: do you happen to know which version you had and which version you upgraded to?  We'd love to update our docs to indicate a minimum pip version.

**Comment by markusdr** [comment]
It was pip 1.0 on Ubuntu 12.04. I upgraded to 7.1.2 and it worked.

**Comment by mrob27** [comment]
The command to type is "pip install --upgrade pip", and this should be added to the [http://tensorflow.org/get_started/os_setup.md](instructions) right after where they tell the user to "source bin/activate"

**Comment by fancyerii** [comment]
after pip install --upgrade pip
it still not work. I am using ubuntu 12.04 and pip version is 1.0

**Comment by nishasraj** [comment]
me too after pip upgrade its not working

**Comment by nishasraj** [comment]
how u corrected the error..my pip got upgraded correctly

**Comment by aolang** [comment]
Just like markusdr commented, update the pip using "pip install --upgrade pip", then you can check the pip version "pip2 --version", and then 
"sudo pip2 install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl", maybe it can worded.

**Comment by lijia-xing** [comment]
haha,I have the same problem of window system.

**Comment by usptact** [comment]
I have  pip 9.0.1 installed and still see this error.

**Comment by bkornpob** [comment]
I am trying to get Lapack by
>pip install http://www.netlib.org/lapack/lapack-3.7.0.tgz
and my pip still cannot find setup.py

PS... I already did pip install --upgrade pip.

**Comment by phsimon** [comment]
Hi,

After upgrading pip (9.0.1), I get now this error by installing tensorflow (and do not find any information to fix it) - I use ubuntu 13.04.


Traceback (most recent call last):
  File "/home/ypsa6500/tensorflow/bin/pip", line 9, in <module>
    load_entry_point('pip==9.0.1', 'console_scripts', 'pip')()
  File "/home/ypsa6500/tensorflow/local/lib/python2.7/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/home/ypsa6500/tensorflow/local/lib/python2.7/site-packages/pip/basecommand.py", line 251, in main
    timeout=min(5, options.timeout)) as session:
  File "/home/ypsa6500/tensorflow/local/lib/python2.7/site-packages/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/home/ypsa6500/tensorflow/local/lib/python2.7/site-packages/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/home/ypsa6500/tensorflow/local/lib/python2.7/site-packages/pip/download.py", line 93, in user_agent
    from pip._vendor import distro
  File "/home/ypsa6500/tensorflow/local/lib/python2.7/site-packages/pip/_vendor/distro.py", line 1050, in <module>
    _distro = LinuxDistribution()
  File "/home/ypsa6500/tensorflow/local/lib/python2.7/site-packages/pip/_vendor/distro.py", line 594, in __init__
    if include_lsb else {}
  File "/home/ypsa6500/tensorflow/local/lib/python2.7/site-packages/pip/_vendor/distro.py", line 933, in _get_lsb_release_info
    raise subprocess.CalledProcessError(code, cmd, stdout)
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 134

**Comment by cbarcenas05** [comment]
I am having the same error when installing TensorFlow1.0 in RH7.2
 I am installing as root and I am using the pip install method.

Processing ./tensorflow-1.0.1-cp27-none-linux_x86_64.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build/setup.py'

This the output to my pip - V:
 pip 9.0.1 from /root/anaconda2/lib/python2.7/site-packages (python 2.7)
I have already tried pip install --upgrade

Thanks,

**Comment by liuqi05** [comment]
@usptact ,i meet the same problem. And I have pip 9.0.1 installed and still see this error. So i want to know,if you find new way to solve it, Thanks!

**Comment by liuqi05** [comment]
@markusdr hi, i meet the same problem as you encounter.I update pip 9.0.1, but the problem can not fix.So   can you give me some advice? Thank you.

**Comment by liuqi05** [comment]
@nishasraj  Hi, I update pip to 9.0.1,but its not working. So i want to know if you find a new way to fix this problem. Thank you in advance.

**Comment by srinivasreddy** [comment]
pip 1.1 to upgrading it to 9.0.1 worked well for me

**Comment by srinivasreddy** [comment]
May be this help others as well,
```
Package                Version  
---------------------- ---------
backports.weakref      1.0.post1
bleach                 1.5.0    
funcsigs               1.0.2    
html5lib               0.9999999
Markdown               2.6.9    
mock                   2.0.0    
numpy                  1.13.1   
pbr                    3.1.1    
pip                    9.0.1    
protobuf               3.4.0    
setuptools             0.6rc11  
six                    1.11.0   
tensorflow             1.3.0    
tensorflow-tensorboard 0.1.6    
Werkzeug               0.12.2   
wheel                  0.30.0   

```

**Comment by prameshbajra** [comment]
I am having this error in `pip 19.0.1 from /usr/local/lib/python2.7/dist-packages/pip-19.0.1-py2.7.egg/pip (python 2.7)
` anybody having some clue in how to solve it?

**Comment by akashkrshukla** [comment]
I am having the same error as above . Did anyone got the solution . I am not able to find any so far ?curl

**Comment by cjshowalter** [comment]
I was getting the same issue, and it turned out to be the package was missing a setup.py entirely. Not sure if it's the same for everyone else tho. (pip 20.1.1)

**Comment by slokaanugu** [comment]
> I was getting the same issue, and it turned out to be the package was missing a setup.py entirely. Not sure if it's the same for everyone else tho. (pip 20.1.1)

how did you fix this issue?

**Comment by LucaCappelletti94** [comment]
I have encountered this issue when I had, on a new docker, pip version 9. Upgrading it to version 21 fixed the problem.
