### ISSUE TITLE
Problems Installing on Windows 10

### ISSUE THREAD

**Issue by techjogger** [tensorflow/tensorflow#5600]
I am having trouble building tensorflow on Windows. Here is a detailed list of all the steps I took to get it to build. 

Any help is much appreciated. 

Step-by-step Windows build
 
1. Install the pre-requisites detailed above, and set up your environment.
o   CMake version 3.1 or later, 
  When installing  cmake-3.7.0-rc2-win64-x64.msi , I added CMake to the System Path for all users, in file location C:\Program Files\CMake\
o   Git
  I installed Git-2.10.1-64-bit.exe, selected the option Use Git from the Windows Command Prompt, Checkout Windows-style commit Unix-style line endings, Use Windows default console window
•         Enable both file system caching and git credential Manager
o   SWIG
  I downloaded swigwin-3.0.10 from here http://www.swig.org/download.html , unzipped the folder and placed the contents in “C:\tools”
2. Run vcvarsall.bat
       
•         The instructions say to run this command…
o   D:\temp> "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvarsall.bat"
 
•         However, my "vcvarsall.bat" file was actually in a different location -> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
o   So I ran this command...
o   D:\temp> "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"
 
3. Clone TensorFlow
 
D:\temp> git clone https://github.com/tensorflow/tensorflow.git
D:\temp> cd tensorflow\tensorflow\contrib\cmake
D:\temp\tensorflow\tensorflow\contrib\cmake> mkdir build
D:\temp\tensorflow\tensorflow\contrib\cmake> cd build
D:\temp\tensorflow\tensorflow\contrib\cmake\build>
 
I ran these commands and everything went smoothly.
 
 
4. Invoke CMake to create Visual Studio solution and project files
 
D:\...\build> cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release ^
More? -DSWIG_EXECUTABLE=C:/tools/swigwin-3.0.10/swig.exe ^
More? -DPYTHON_EXECUTABLE=C:/Users/%USERNAME%/AppData/Local/Continuum/Anaconda3/python.exe ^
More? -DPYTHON_LIBRARIES=C:/Users/%USERNAME%/AppData/Local/Continuum/Anaconda3/libs/python35.lib
 
The problem is my python.exe and python35.lib are in totally different file locations.
 
C:\Windows\System32\tensorflow\tensorflow\contrib\cmake\build> cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release ^
More? -DSWIG_EXECUTABLE=C:/tools/swigwin-3.0.10/swig.exe ^
More? -DPYTHON_EXECUTABLE=C:/Program Files/Anaconda3/python.exe ^
More? -DPYTHON_LIBRARIES= C:/Program Files/Anaconda3/libs/python35.lib
 
 
 
Here is the error code…
 
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:5 (project):
  No CMAKE_C_COMPILER could be found.
 
 
 
CMake Error at CMakeLists.txt:5 (project):
  No CMAKE_CXX_COMPILER could be found.
 
 
 
-- Configuring incomplete, errors occurred!
See also "C:/Windows/System32/tensorflow/tensorflow/contrib/cmake/build/CMakeFiles/CMakeOutput.log".
See also "C:/Windows/System32/tensorflow/tensorflow/contrib/cmake/build/CMakeFiles/CMakeError.log".
 
After adding “get.exe” to my path variable and running this command
 
C:\Windows\System32\tensorflow\tensorflow\contrib\cmake\build>cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release ^
More? -DSWIG_EXECUTABLE=C:/tools/swigwin-3.0.10/swig.exe ^
More? -DPYTHON_EXECUTABLE=C:/Program Files/Anaconda3/python.exe ^
More? -DPYTHON_LIBRARIES= C:/Program Files/Anaconda3/libs/python35.lib
 
 
I get this error…
 
CMake Error: The source directory "C:/Windows/System32/tensorflow/tensorflow/contrib/cmake/build/Files/Anaconda3/libs/python35.lib" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
 
C:\Windows\System32\tensorflow\tensorflow\contrib\cmake\build>

**Comment by mrry** [comment]
Judging by the error message, it looks like the space in `C:/Program Files/Anaconda3/libs/python35.lib` is causing the problem, because it's looking for the Python library in `C:/Windows/System32/tensorflow/tensorflow/contrib/cmake/build/Files/Anaconda3/libs/python35.lib`.

(As an aside, I wouldn't generally recommend building software under `C:\Windows`, but that's up to you....)

It might be sufficient to put quotes around the definitions of `PYTHON_EXECUTABLE` and `PYTHON_LIBRARIES`. Can you try that and let us know how you get on?

**Comment by techjogger** [comment]
Thanks for the tip! I moved my project to C:\Users\miles\Documents\TensorflowWork and tried to rebuild tensorflow. 


C:\Users\miles\Documents\TensorflowWork\tensorflow\tensorflow\contrib\cmake\build>cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release ^
More? -DSWIG_EXECUTABLE=C:/tools/swigwin-3.0.10/swig.exe ^
More? -DPYTHON_EXECUTABLE=C:/Users/%USERNAME%/AppData/Local/Continuum/Anaconda3/python.exe ^
More? -DPYTHON_LIBRARIES=C:/Users/%USERNAME%/AppData/Local/Continuum/Anaconda3/libs/python35.lib
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24213.1
-- The CXX compiler identification is MSVC 19.0.24213.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Found PythonInterp: C:/Users/miles/AppData/Local/Continuum/Anaconda3/python.exe (found version "1.4")
CMake Error at tf_python.cmake:25 (message):
  Cannot get Python include directory.  Is distutils installed?
Call Stack (most recent call first):
  CMakeLists.txt:210 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Users/miles/Documents/TensorflowWork/tensorflow/tensorflow/contrib/cmake/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/miles/Documents/TensorflowWork/tensorflow/tensorflow/contrib/cmake/build/CMakeFiles/CMakeError.log".


The build seems to have failed trying to open a filed called 'pthread.h'. Here is the CMakeError.log...


Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/Users/miles/Documents/TensorflowWork/tensorflow/tensorflow/contrib/cmake/build/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_7438f.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25420.1

Copyright (C) Microsoft Corporation. All rights reserved.



Build started 11/16/2016 2:12:11 PM.

Project "C:\Users\miles\Documents\TensorflowWork\tensorflow\tensorflow\contrib\cmake\build\CMakeFiles\CMakeTmp\cmTC_7438f.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_7438f.dir\Debug\".

  Creating directory "C:\Users\miles\Documents\TensorflowWork\tensorflow\tensorflow\contrib\cmake\build\CMakeFiles\CMakeTmp\Debug\".

  Creating directory "cmTC_7438f.dir\Debug\cmTC_7438f.tlog\".

InitializeBuildStatus:

  Creating "cmTC_7438f.dir\Debug\cmTC_7438f.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_7438f.dir\Debug\\" /Fd"cmTC_7438f.dir\Debug\vc140.pdb" /Gd /TC /errorReport:queue C:\Users\miles\Documents\TensorflowWork\tensorflow\tensorflow\contrib\cmake\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c

  Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24213.1 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /D WIN32 /D _WINDOWS /D _DEBUG /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_7438f.dir\Debug\\" /Fd"cmTC_7438f.dir\Debug\vc140.pdb" /Gd /TC /errorReport:queue C:\Users\miles\Documents\TensorflowWork\tensorflow\tensorflow\contrib\cmake\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c

  

  CheckIncludeFile.c

C:\Users\miles\Documents\TensorflowWork\tensorflow\tensorflow\contrib\cmake\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users\miles\Documents\TensorflowWork\tensorflow\tensorflow\contrib\cmake\build\CMakeFiles\CMakeTmp\cmTC_7438f.vcxproj]

Done Building Project "C:\Users\miles\Documents\TensorflowWork\tensorflow\tensorflow\contrib\cmake\build\CMakeFiles\CMakeTmp\cmTC_7438f.vcxproj" (default targets) -- FAILED.



Build FAILED.



"C:\Users\miles\Documents\TensorflowWork\tensorflow\tensorflow\contrib\cmake\build\CMakeFiles\CMakeTmp\cmTC_7438f.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  C:\Users\miles\Documents\TensorflowWork\tensorflow\tensorflow\contrib\cmake\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Users\miles\Documents\TensorflowWork\tensorflow\tensorflow\contrib\cmake\build\CMakeFiles\CMakeTmp\cmTC_7438f.vcxproj]



    0 Warning(s)

    1 Error(s)



Time Elapsed 00:00:00.48

**Comment by mrry** [comment]
I think that failure is a red herring... we don't depend on the availability of pthreads to build on Windows, but the current CMake rules will check for it (and that check will fail without breaking the rest of the build).

Instead I think this is the main error:

```
CMake Error at tf_python.cmake:25 (message):
Cannot get Python include directory. Is distutils installed?
Call Stack (most recent call first):
CMakeLists.txt:210 (include)
```

Can you ensure that `distutils` is installed in the Python environment you're using?

**Comment by gibletto** [comment]
distutils might also be a red herring, I've built this on windows 10 and got exactly the same errors (although I did download pthreads.h...).

Set additional paths for the include files when building
-DPYTHON_INCLUDE_DIR=<PATH_TO_INCLUDE_IN_ANACONDA>

If I remember correctly, you may have to add more that just this (numpy as well I think), I can't remember exactly what I ended up with.

**Comment by mrry** [comment]
Yes, you can avoid the requirement on installing distutils if you specify `-DPYTHON_INCLUDE_DIR` (we [use distutils](https://github.com/tensorflow/tensorflow/blob/99284f4c9eff4bf387dea926c11e06bc513606e7/tensorflow/contrib/cmake/tf_python.cmake#L21) to discover that directory automatically, but won't use it if you specify a dir explicitly).

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. When further information is posted we will reopen this. Thanks.

**Comment by Qiang-Ge** [comment]
You should change the installation location of Anaconda3, because the command line of the space will bring a lot of problems, More? -DPYTHON_EXECUTABLE = C: / Program Files / Anaconda3 / python.exe ^
More? -DPYTHON_LIBRARIES = C: / Program Files / Anaconda3 / libs / python35.lib There are spaces in both commands that may not be recognized, resulting in an error

**Comment by johnsrude** [comment]
What about putting double quotes (") around the paths? For example:
-DPYTHON_EXECUTABLE = "C: / Program Files / Anaconda3 / python.exe" ^

**Comment by johnsrude** [comment]
```
c:\ProgramData\Anaconda3>conda install distutils
Fetching package metadata ...........
PackageNotFoundError: Package missing in current win-64 channels:
  - distutils
```

**Comment by colmantse** [comment]
Dear all,

May I know what exactly would be to include in <PATH_TO_INCLUDE_IN_ANACONDA>?
Is it the path to python for dpython and to numpy for dnumpy or is it the anaconda path?
