### ISSUE TITLE
wide_n_deep_tutorial.py fails with model_type=deep: Shapes (32561, 1) and (32561,) are incompatible

### ISSUE THREAD

**Issue by shirriff** [tensorflow/tensorflow#5601]
The [wide_n_deep tutorial](https://www.tensorflow.org/versions/r0.11/tutorials/wide_and_deep/index.html) fails when run with --model_type=deep
It immediately fails with the error:
Shapes (32561, 1) and (32561,) are incompatible

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
This may be due to #4715 
https://github.com/tensorflow/tensorflow/issues/3776 discusses the same flag, but appears to be an unrelated problem

### Environment info
Operating System: macOS Sierra 10.12.1

Installed version of CUDA and cuDNN: none

1. A link to the pip package you installed:
https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0-py2-none-any.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.11.0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

1. Download the tutorial code [wide_n_deep_tutorial.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/wide_n_deep_tutorial.py)

2: Run with --model_type=deep
python wide_n_deep_tutorial.py --model_type=deep

### What other attempted solutions have you tried?

The example runs with --model_type=wide or --model_type=wide_n_deep. Just the deep model fails.

### Logs or other output that would be helpful
[out.txt](https://github.com/tensorflow/tensorflow/files/590128/out.txt)

The log shows a lot of warnings about API changes, suggesting the tutorial code should be updated. E.g.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.

**Comment by girving** [comment]
@ispirmustafa Can you take a look?

**Comment by willdzeng** [comment]
Same issue as #4715 
Fixed in master branch but not in 0.11.0
