### ISSUE TITLE
NodeDefBuilder for custom OP  will report OpKernel for unknown op: UnwrapDatasetVariant

### ISSUE THREAD

**Issue by yank666** [tensorflow/tensorflow#56026]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

tf 2.6.0

### Custom Code

Yes

### OS Platform and Distribution

macos 11.6

### Python version

python 3.7.6

### Current Behaviour?

```shell
when i test use gtest after developed custom op 'Factt' (just same as op 'Fact'),

using line: TF_EXPECT_OK(NodeDefBuilder("fact_op", "Fact").Finalize(node_def()));
will always report
E tensorflow/core/framework/op_kernel.cc:1623] opKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
```

### Standalone code to reproduce the issue

```shell
//============================src===========================
class FacttOp : public tensorflow::OpKernel {
 public:
  explicit FactOp(tensorflow::OpKernelConstruction *context) : OpKernel(context) {}

  void Compute(tensorflow::OpKernelContext *context) override {
    // Output a scalar string.
    tensorflow::Tensor *output_tensor = nullptr;
    OP_REQUIRES_OK(context, context->allocate_output(0, tensorflow::TensorShape(), &output_tensor));
    using tensorflow::string;
    auto output = output_tensor->template scalar<tensorflow::tstring>();

  }
};

REGISTER_KERNEL_BUILDER(Name("Factt").Device(tensorflow::DEVICE_CPU), FactOp);

//============================gtest===========================
TEST_F(ExampleFacttTest, Compute) {
TF_EXPECT_OK(
      NodeDefBuilder("fact_op", "Factt")
      .Finalize(node_def()));
  TF_EXPECT_OK(InitOpWithGraphVersion(8));
  TF_ASSERT_OK(RunOpKernel());
  Tensor* tensor_output = GetOutput(0);
  EXPECT_TRUE(tensor_output != nullptr);
  LOG(INFO) << "Test ExampleMergeTest : compute SUCCESS";
}
```

### Relevant log output

```shell
2022-05-09 20:22:57.092424: E tensorflow/core/framework/op_kernel.cc:1623] OpKernel ('op: "UnwrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: UnwrapDatasetVariant
2022-05-09 20:22:57.092471: E tensorflow/core/framework/op_kernel.cc:1623] OpKernel ('op: "UnwrapDatasetVariant" device_type: "CPU"') for unknown op: UnwrapDatasetVariant
2022-05-09 20:22:57.092497: E tensorflow/core/framework/op_kernel.cc:1623] OpKernel ('op: "WrapDatasetVariant" device_type: "GPU" host_memory_arg: "input_handle" host_memory_arg: "output_handle"') for unknown op: WrapDatasetVariant
2022-05-09 20:22:57.092518: E tensorflow/core/framework/op_kernel.cc:1623] OpKernel ('op: "WrapDatasetVariant" device_type: "CPU"') for unknown op: WrapDatasetVariant
2022-05-09 20:26:11.601110: I /Users/yankai/Codelib/codes/CNBizAlgoOps/tests/cpp/test_example/test_example_fact.cc:30] Test ExampleMergeTest : compute SUCCESS
```
</details>

**Comment by sachinprasadhs** [comment]
Make sure you register your OP, follow the guide [here](https://www.tensorflow.org/guide/create_op#op_registration).
Also, make sure you follow the folder structure for the specific kernel level for your op, folder structure should be like below if you are using CPU kernel.

```
├── FactOp  # A CPU only op
│   ├── cc
│   │   ├── kernels  # op kernel implementation
│   │   │   └── fact_op_kernels.cc
│   │   └── ops  # op interface definition
│   │       └── fact_op_ops.cc
```

Follow the instructions [here](https://github.com/tensorflow/custom-op) for detailed overview.

**Comment by yank666** [comment]
i make sure register my op correctly, but i don;t follow  structure for you shows 
├── FactOp  # A CPU only op
│   ├── cc
│   │   ├── fact_kernal # op kernel implementation
│   │   │   
│   │   └── ops_defs # all op interface register are here,
i can run my custom op in python Api noramlly, but when i test it in gtest using NodeDefBuilder will report error (details in describe), but it still can run success, why ,and what cause error report

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

To maintain proper organization, make sure your files are placed in the appropriate folders according to the kernel type. For CPU kernels, the folder structure is mentioned in the official document. https://github.com/tensorflow/custom-op

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.
