### ISSUE TITLE
TFLite ios podspecs are fixed to 2.7

### ISSUE THREAD

**Issue by drubinstein** [tensorflow/tensorflow#56030]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

source

### Tensorflow Version

2.8+

### Custom Code

No

### OS Platform and Distribution

iOS

### Mobile device

iOS

### Current Behaviour?

The podspecs for ios all seem to have TF version fixed to 2.7 even though 2.8 has been released and 2.9 is going to be released. I want to check if this is an oversight or if TFLite for iOS has a different versioning scheme.

For example [TensorFlowLiteC's](https://github.com/tensorflow/tensorflow/blob/v2.8.0/tensorflow/lite/ios/TensorFlowLiteC.podspec) podspec begins as 

```
Pod::Spec.new do |s|
  s.name             = 'TensorFlowLiteC'
  s.version          = '2.7.0'
  s.authors          = 'Google Inc.'
  s.license          = { :type => 'Apache' }
  s.homepage         = 'https://github.com/tensorflow/tensorflow'
  s.source           = { :http => "https://dl.google.com/dl/cpdc/6ffa58c2d5bbf5ff/TensorFlowLiteC-#{s.version}.tar.gz" }
  s.summary          = 'TensorFlow Lite'
  s.description      = <<-DESC
```

### Standalone code to reproduce the issue

```shell
See above.
```

### Relevant log output

_No response_</details>

**Comment by sachinprasadhs** [comment]
Hi, Thanks for opening the bug, I have updated the team internally and it will be fixed. Thanks!

**Comment by sachinprasadhs** [comment]
@drubinstein , `TensorFlowLiteC.podspec` version has been updated to Tensorflow version 2.9.1, as of now it is available in nightly version/master build. It will be made available in the next stable release.
Please check the file [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/ios/TensorFlowLiteC.podspec) for reference and move this issue to closed. Thanks!
