### ISSUE TITLE
How to update .tflite 

### ISSUE THREAD

**Issue by Sanjay2802** [tensorflow/tensorflow#56049]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

Tflite

### Custom Code

No

### Current Behaviour?

```shell
How to update tflite i.e after training and exporting , how to add more models in it. Instead of training whole model from first.
```

### Standalone code to reproduce the issue

```shell
Example : https://colab.research.google.com/github/khanhlvg/tflite_raspberry_pi/blob/main/object_detection/Train_custom_model_tutorial.ipynb#scrollTo=l4QQTXHHATDS
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @Sanjay2802 ! TFlite models compressed form of Original model . I am afraid adding a new model in TFlite files won't be possible after training and exporting. But if you want to optimise the lite conversion process for latency, size or sparsity ,  You can use [optimization ](https://www.tensorflow.org/api_docs/python/tf/lite/Optimize)from TFLite converter on a custom multiclass image classification model. Thanks!
