### ISSUE TITLE
The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.

### ISSUE THREAD

**Issue by liuyang77886** [tensorflow/tensorflow#56048]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf2.9

### Custom Code

No

### OS Platform and Distribution

ubuntu20

### Mobile device

ubuntu20

### Python version

3.7

### Bazel version

bazel-5.1.1

### Current Behaviour?

```shell
我的服务器执行shell命令：test@test-VirtualBox:~$ cat /proc/cpuinfo    显示如下指令信息：
flags  : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl pni cx16 hypervisor lahf_lm abm
 如下该如何输入配置：
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]:
 如下该如何输入配置：
./bazel-5.1.1-linux-x86_64 build --config=v1 --copt=-mavx --copt=-mavx2 --copt=-msse --copt=-msse2 --copt=-mssse3   -k //tensorflow/tools/pip_package:build_pip_package
```

### Standalone code to reproduce the issue

```shell
test@test-VirtualBox:/home/soft/tensorflow-master$  ./configure

Found possible Python library paths:
  /home/soft/anaconda3/envs/tf2/lib/python3.7/site-packages
Please input the desired Python library path to use.  Default is [/home/soft/anaconda3/envs/tf2/lib/python3.7/site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: n
No CUDA support will be enabled for TensorFlow.

Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
Clang will not be downloaded.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]:


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n


test@test-VirtualBox:/home/soft/tensorflow-master$ ./bazel-5.1.1-linux-x86_64 build --config=v1 --copt=-mavx --copt=-mavx2 --copt=-msse --copt=-msse2 --copt=-mssse3   -k //tensorflow/tools/pip_package:build_pip_package



=======================
我咨询的问题是：我应该如何选择配置才能支持我的服务器cpu（flags  : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl pni cx16 hypervisor lahf_lm abm）
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @liuyang77886 ! I did not find any issue with Bazel 5.0.0 and 2.9 or Bazel 5.1.1 and Master in Ubuntu 18. Can you check with below command once . 

`bazel build --config=v1 --copt=-mavx --copt=-mavx2 --copt=-msse --copt=-msse2 --copt=-mssse3 -k  //tensorflow/tools/pip_package:build_pip_package`

Attaching [gist ](https://colab.sandbox.google.com/gist/mohantym/21d6df67864910c47ef997beb734f255/tensorflow-ranking.ipynb#scrollTo=XTa3qpBSV00Z)for reference. Thank you!

**Comment by liuyang77886** [comment]
please tell me,  我所提供的cpu架构应该选用参数   like this:--config=v1  --copt=-msse2   

 cpu（flags  : fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl pni cx16 hypervisor lahf_lm abm）

**Comment by liuyang77886** [comment]
我不知道，你让我再次拉取代码是为什么，我编译执行的下载最新代码的时间是2022-05-05， 或者说，你从2022-05-05到05-12日之间提交了新的代码解决这个问题吗

**Comment by mohantym** [comment]
Hi @gadagashwini ! Could you please look at this issue?

**Comment by gadagashwini** [comment]
@liuyang77886,
Tensorflow compiled to use SSE4.1 on x86 builds. The line [here](https://github.com/tensorflow/tensorflow/blob/c4b09b5df79625a70853fd66b5caa7dd92fb4d1f/tensorflow/tensorflow.bzl#L130) in `tensorflow/tensorflow.bzl` is responsible for SSE4.1 instructions. You can delete that line to make Tensorflow build successful. Thanks!

**Comment by 1W2111** [comment]
> Click to expand!
你用conda 重新安装tensorflow就能解决这个问题（已成功），祝你好运~
