### ISSUE TITLE
meta graph complaining *'_Resource' object has no attribute 'name'*

### ISSUE THREAD

**Issue by nrailgun** [tensorflow/tensorflow#56042]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.6

### Custom Code

Yes

### OS Platform and Distribution

Linux

### Python version

3.6

### Current Behaviour?

I used `ops.resources.register_resource` to init my own resource type. But TF complains

WARNING:tensorflow:Issue encountered when serializing resources.
Type is unsupported, or the types of the items don't match field type in CollectionDef. Note this is a warning and probably safe to ignore.
'_Resource' object has no attribute 'name'

But 'name' is not member of `_Resource`.
```python
# ops/resources.py
_Resource = collections.namedtuple("_Resource",
                                    ["handle", "create", "is_initialized"])
```

### Standalone code to reproduce the issue

I wrote a lot of custom code, so it's not easy to make standalone code to reproduce. That's how I register resource.

```python
resources.register_resource(
            x.resource_handle,
            x_init_op,
            x_is_initialized_op)
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@nrailgun 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!
