### ISSUE TITLE
No matching distribution found for tensorflow==2.5.3

### ISSUE THREAD

**Issue by RuofanKong** [tensorflow/tensorflow#56057]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

tensorflow 2.5.3

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 18.04 and Monterey 12.3.1

### Python version

3.7/3.8

### Current Behaviour?

I was trying to install tensorflow 2.5.3 by doing pip install as below, but it failed with no matching version 
```
$ pip install tensorflow==2.5.3
ERROR: Could not find a version that satisfies the requirement tensorflow==2.5.3
ERROR: No matching distribution found for tensorflow==2.5.3
```
However, I do see 2.5.3 is a Pypi public released version https://pypi.org/project/tensorflow/2.5.3/

### Standalone code to reproduce the issue

```
$ pip install tensorflow==2.5.3
ERROR: Could not find a version that satisfies the requirement tensorflow==2.5.3
ERROR: No matching distribution found for tensorflow==2.5.3
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@RuofanKong Could you please follow the steps as mentioned [here](https://www.tensorflow.org/install/source) and refer to the tested build configurations?
Thank you!

**Comment by RuofanKong** [comment]
Hi @sushreebarsa, our workflow requires installing Tensorflow from binary (https://www.tensorflow.org/install/pip), rather than building from source.

**Comment by edwardyehuang** [comment]
1. Try pip install tensorflow==2.5
2. If 1 not work, check your python version by : python -V

**Comment by RuofanKong** [comment]
@edwardyehuang `pip install tensorflow==2.5` installs 2.5.0 only, while the need here is 2.5.3.

**Comment by edwardyehuang** [comment]
Check if ur python version >= 3.7 

![image](https://user-images.githubusercontent.com/3354448/167778404-1434988d-bbb8-4865-a8a0-c3c072c161e5.png)

**Comment by RuofanKong** [comment]
@edwardyehuang Ah I think I accidentally switched to 3.6 env which I didn't realize. After switching to my original 3.8 env, it's working now. Thank You! Closing the ticket now.
