### ISSUE TITLE
Model fails to predict using float16

### ISSUE THREAD

**Issue by hoonkai** [tensorflow/tensorflow#56065]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.8.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.9

### Current Behaviour?

```shell
I'm trying to build a model that uses `float16` in the inputs and outputs. However, I've noticed that none of the toy examples I've tried seems to work.
```

### Standalone code to reproduce the issue

For instance, the model below gives `NaN`:

```python
def total_variation(im1):
    score = tf.image.total_variation(im1)
    return tf.cast(score, tf.float16)

input1 = tf.keras.Input(shape=(512,512,3), batch_size=1, dtype=tf.float16)
output = total_variation(input1)
matrix1 = np.arange(512*512*3,dtype='float16').reshape(1,512,512,3)
model = tf.keras.Model(inputs=[input1], outputs=output, name='test')
x = model.predict([matrix1])
x # NaN
```

However, the following gives the correct result:

```python
def total_variation(im1):
    score = tf.image.total_variation(im1)
    return tf.cast(score, tf.float32)

input1 = tf.keras.Input(shape=(512,512,3), batch_size=1, dtype=tf.float32)
output = total_variation(input1)
matrix1 = np.arange(512*512*3,dtype='float32').reshape(1,512,512,3)
model = tf.keras.Model(inputs=[input1], outputs=output, name='test')
x = model.predict([matrix1])
x # array([1.207955e+09], dtype=float32)
```

Same result if `tf.keras.backend.set_floatx('float16')` was called instead. Does anyone know why this might be the case?
```


### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@chunduriv ,
I was able to reproduce the issue in tf v2.8, v2.7 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/c3eda670cb9e2be58beef6472397f56c/56065.ipynb).

**Comment by sachinprasadhs** [comment]
Thanks for opening this issue. Development of keras moved to separate repository https://github.com/keras-team/keras/issues

Please post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
