### ISSUE TITLE
TFLite C API building in linux didnt create .a files

### ISSUE THREAD

**Issue by chendadon** [tensorflow/tensorflow#56061]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.8

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.9

### Bazel version

5.0.0

### GCC/Compiler version

9.3

### Current Behaviour?

```shell
I've added a custom OP code from mediapipe to tensorflow code and when i build it using 

"bazel build --java_runtime_version=remotejdk_11 -c opt --define=no_tensorflow_py_deps=true --define tflite_with_xnnpack=true //tensorflow/lite/c:libtensorflowlite_c.so"

.so file is created and i can use it for general tflite code but no custom op, in mac/windows in addition to .dylib/.dll it'll also produce .a/.lib for the external libs (absl/flatbuffers etc..) and for mediapipe/delegates which i need for linking against my project.

so my question is, there is a way to produce those static libs in addition to the .so file?
```

### Standalone code to reproduce the issue

```shell
"bazel build --java_runtime_version=remotejdk_11 -c opt --define=no_tensorflow_py_deps=true --define tflite_with_xnnpack=true //tensorflow/lite/c:libtensorflowlite_c.so"

"bazel build --java_runtime_version=remotejdk_11 -c opt --define=no_tensorflow_py_deps=true --define tflite_with_xnnpack=true //tensorflow/lite/c:libtensorflowlite_c.dylib"

"bazel build --java_runtime_version=remotejdk_11 -c opt --define=no_tensorflow_py_deps=true --define tflite_with_xnnpack=true //tensorflow/lite/c:tensorflowlite_c.dll"
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @chendadon ! My idea was to add a custom rule for your custom op with its dependencies in build file  and try again with --linkopt=static flag . Attaching relevant threads for reference. [1](https://stackoverflow.com/questions/56215946/is-there-a-minimum-sample-for-custom-op-for-tensorflow-lite), [2](https://www.tensorflow.org/tfx/serving/custom_op#build_static_library_for_the_op). Thanks!

**Comment by chendadon** [comment]
Hi @mohantym thanks for your answer, Im not sure if i understood you well.
my end goal is to implement my version of mediapipe for that i need to add mediapipe code to tensorflow lite delegate.
tensorflow download/commit: https://github.com/tensorflow/tensorflow/archive/a3419acc751dfc19caf4d34a1594e1f76810ec58.tar.gz

then i apply their patch:
https://github.com/google/mediapipe/blob/master/third_party/org_tensorflow_custom_ops.diff

in addition ive edit tensorflow/lite/c/BUILD so it'll depends on those custom libs:
```
cc_library(
    name = "c_api",
    hdrs = ["c_api.h"],
    copts = tflite_copts(),
    deps = [
        ":c_api_types",
        ":c_api_without_op_resolver",
        "//tensorflow/lite:create_op_resolver_with_builtin_ops",
        "//tensorflow/lite/delegates/gpu/common:model_builder",
        "//tensorflow/lite/delegates/gpu/common/selectors:default_selector",
        "//tensorflow/lite/delegates/gpu/common/transformations:model_transformations",
        "//tensorflow/lite/delegates/gpu/common/mediapipe:custom_transformations",
        "//tensorflow/lite/delegates/gpu/common/mediapipe:landmarks_to_transform_matrix",
        "//tensorflow/lite/delegates/gpu/common/mediapipe:transform_landmarks",
        "//tensorflow/lite/delegates/gpu/common/mediapipe:transform_tensor_bilinear",
    ],
    alwayslink = 1,  # Why?? TODO(b/161243354): eliminate this.
)
```

when i running
```
 bazel build --java_runtime_version=remotejdk_11 -c dbg --define=no_tensorflow_py_deps=true --define tflite_with_xnnpack=true //tensorflow/lite/c:libtensorflowlite_c.so
```
it only produce libtensorflowlite_c.so
but i also need the absl, flatbuffers binaries and in addition object_reader, model_builder and all those mediapipe binaries so i can use this custom code in my project.
again in mac/ios/windows it produce those static libs but not in linux.

from here what are my options?

btw i tried to add --linkopt=static
```
 bazel build --java_runtime_version=remotejdk_11 -c dbg --linkopt=static --define=no_tensorflow_py_deps=true --define tflite_with_xnnpack=true //tensorflow/lite/c:libtensorflowlite_c.so
```
but it crashed:
```
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/24224163d60cc7fbb7934730506469da/external/flatbuffers/BUILD.bazel:65:10: Linking external/flatbuffers/flatc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-dbg/bin/external/flatbuffers/flatc-2.params
gcc: error: static: No such file or directory
```

Thanks !

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue?

**Comment by chendadon** [comment]
any help with this issue? im trying to figure out how to build all the dependent libraries as static. btw i managed to do so with cmake, but for our project we need to compile it using bazel

**Comment by pkgoogle** [comment]
Hi @chendadon,

I was not able to reproduce this because of patch application error:
```
git apply org_tensorflow_custom_ops.diff
error: patch failed: tensorflow/lite/delegates/gpu/common/BUILD:173
error: tensorflow/lite/delegates/gpu/common/BUILD: patch does not apply
```

I cloned tf, and went to that commit:

```
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout a3419a
```

I then cloned the mediapipe repo to get the "org_tensorflow_custom_ops.diff" file and attempted to apply the diff as stated above. Can you provide us exact steps to apply the diff? Also please verify if my steps above replicates the state of your local tensorflow source. Thanks for your help.
