### ISSUE TITLE
Converted tflite file is 30x the size of the original SavedModel

### ISSUE THREAD

**Issue by josephrocca** [tensorflow/tensorflow#56075]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.8.0-0-g3f878cff5b6 2.8.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04.5

### Mobile device

Linux Ubuntu 18.04.5

### Python version

3.7.13

### Current Behaviour?

A SavedModel that is about 4mb turns into a 125mb model when converted into the tflite format.

### Standalone code to reproduce the issue

Minimal Google Colab replication: https://colab.research.google.com/drive/1D25Czt1yKmguObbVVp4eqkfdVKRTh9jA

```python
!wget https://huggingface.co/rocca/lit-web/resolve/main/debug/lit_savedmodel_no_params.zip
!unzip lit_savedmodel_no_params.zip

import tensorflow as tf

folder_name = "lit_savedmodel"

converter = tf.lite.TFLiteConverter.from_saved_model(folder_name)
tflite_model = converter.convert()

with open(folder_name+'.tflite', 'wb') as f:
  f.write(tflite_model)
```

* Input SavedModel: https://huggingface.co/rocca/lit-web/resolve/main/debug/lit_savedmodel_no_params.zip
* Output TFLite file: https://huggingface.co/rocca/lit-web/resolve/main/debug/lit_savedmodel_no_params.tflite

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue? It is replicating in [2.7](https://colab.sandbox.google.com/gist/mohantym/cf800832d3f0aa8cb1cdfb58ee6a40fc/-public-tflite-file-is-30x-size-of-savedmodel.ipynb#scrollTo=O_iAPTDYClTD), [2.8](https://colab.sandbox.google.com/gist/mohantym/8ccf4d652476c707d734463a27cc6957/-public-tflite-file-is-30x-size-of-savedmodel.ipynb#scrollTo=UOT5SAaUDuG1) ,[2.9](https://colab.sandbox.google.com/gist/mohantym/6a0cde2314e6ad1a15da939a425caf21/-public-tflite-file-is-30x-size-of-savedmodel.ipynb#scrollTo=fcgzFwX4a_Fu) and [nightly](https://colab.sandbox.google.com/gist/mohantym/c2914fea9604b756faa9c4aa0e228b19/-public-tflite-file-is-30x-size-of-savedmodel.ipynb#scrollTo=ilAbt3-QMQJb) . Thanks!

**Comment by oliverdutton** [comment]
> A TensorFlow Lite model is represented in a special efficient portable format known as [FlatBuffers](https://google.github.io/flatbuffers/) (identified by the .tflite file extension). This provides several advantages over TensorFlow's protocol buffer model format such as reduced size (small code footprint) and faster inference (data is directly accessed without an extra parsing/unpacking step)

This model is ~a sixth of the size of the parameters. It returns the grad of them. I have a strong feeling it contains a load of constant arrays filled with 1s of shape (768,768) [the parameters shape].

tf.savedmodel holds these as a line of hlo and so doesn’t materialise them. I think tflite does materialise them all.

**Comment by oliverdutton** [comment]
I revise my answer slightly, the size is coming from output tensors known at compile time being materialised (and minorly some intermediate tensors). So in short, I think there's no issue here. tflites working perfectly, doing exactly as intended. I also note the increase in size from an empty model is only ~1/6'th when compared to the parameter size. I'd suggest closing the issue.

Quote from https://github.com/google/jax/issues/9659#issuecomment-1126772073

> LiT grad
> For LiT this [notebook](https://drive.google.com/file/d/1cX2cRC5yNbuPTgGdFEEbPFJTVWgyW-Z9/view?usp=sharing) does build the tflite model (which does end up huge, 893MB, of which ~130MB is the model with rest params) and runs, matching jax output with a reasonable tolerance.
> 
> Model file being 130Mb (without params) makes sense to me as some of the grads on the params are zeros. They’re materialised in the tflite file to read straight away as they have no dependency on input. So, in my view tflite is working exactly as intended and that file size is optimal given tflites design choice to materialise arrays.

**Comment by sachinprasadhs** [comment]
@josephrocca , Could you please refer the details from above comments by @oliverdutton and close this issue. Thanks!

**Comment by josephrocca** [comment]
> tflite is working exactly as intended and that file size is optimal given tflites design choice to materialise arrays.

@sachinprasadhs A 30x size increase over the TensorFlow SavedModel format in a format specifically designed for microcontrollers, mobiles, and other edge devices definitely doesn't seem optimal to me. Within the context of a design choice, it might make sense, but the design choices can be bad.

I'll await further feedback/comments on this.

**Comment by pjpratik** [comment]
I was able to replicate this issue in TF 2.11 as well. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/edb980d17c265eb9bbd2154f63edc770/56075.ipynb). Thank you.

**Comment by pkgoogle** [comment]
An ability to control this so that the user is able to determine their own trade-off between latency and memory-size is probably the better way, however this IS working as currently intended.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.

**Comment by josephrocca** [comment]
Just tested this with tf 2.13.0 and it still produces a ~120mb tflite file:

https://colab.research.google.com/drive/1D25Czt1yKmguObbVVp4eqkfdVKRTh9jA

Just execute all cells in that notebook.

**Comment by LakshmiKalaKadali** [comment]
Hi @josephrocca,

I'm wondering what performance you would get with [AI-Edge-Torch](https://github.com/google-ai-edge/ai-edge-torch)?, you can find more information here: [googleblog](https://developers.googleblog.com/en/ai-edge-torch-high-performance-inference-of-pytorch-models-on-mobile-devices/).

If you want to, you can actually try visualizing the result in [model-explorer](https://github.com/google-ai-edge/model-explorer) as well.

Please try them out and let us know the result. If you still need further help, feel free to open a new issue at a relevant repo.

Thank You
