### ISSUE TITLE
TFLite/GPU `tfl.strided_slice` not supported - docs claim it is.

### ISSUE THREAD

**Issue by sebastian-sz** [tensorflow/tensorflow#56081]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

binary

### Tensorflow Version

v2.8.0-0-g3f878cff5b6 2.8.0

### Custom Code

Yes

### OS Platform and Distribution

Google Colab

### Python version

3.7.13 (Google Colab)

### Current Behaviour?

```shell
According to the [documentation](https://www.tensorflow.org/lite/performance/gpu_advanced#supported_ops), a `strided_slice` operation should be supported when running Tensorflow Lite with a GPU Delegate.

Running sanity check with the [Tensorflow Lite Authoring Tool](https://www.tensorflow.org/lite/guide/authoring#checking_gpu_compatibility) raises Exception. How should one use this op, to benefit from GPU acceleration on Android?
```

### Standalone code to reproduce the issue

```shell
# Colab: https://colab.research.google.com/drive/1ih1I3m1j4ZNnc7RKp7AzkLsM-1Cf9TUn?usp=sharing

import tensorflow as tf

# Declare dummy model with strided_slice op:
@tf.function(input_signature = [tf.TensorSpec(shape=(1, 2), dtype=tf.float32)])
def apply(x):
    return x[0, 0]

# Verify works 
apply(tf.constant([[1., 2.]]))

# Fails on the GPU with authoring tool check
target_spec = tf.lite.TargetSpec()
target_spec.experimental_supported_backends = ["GPU"]
func_to_test = tf.lite.experimental.authoring.compatible(
    apply, converter_target_spec=target_spec, raise_exception=True
)
func_to_test(tf.ones(shape=(1,2)))
```

### Relevant log output

```shell
'tfl.strided_slice' op is not GPU compatible: Slice does not support shrink_axis_mask parameter. 
  - /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082
  - /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/traceback_utils.py:150
  - <ipython-input-32-9f16c67cb20c>:6

COMPATIBILITY WARNING: op 'tfl.strided_slice' aren't compatible with TensorFlow Lite GPU delegate. https://www.tensorflow.org/lite/performance/gpu
```
</details>

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue . It is replicating in [2.8](https://colab.sandbox.google.com/gist/mohantym/d133ce221dd1a1456fd43f832828f33c/tfl_strided_slice_issue.ipynb), [2.9 ](https://colab.sandbox.google.com/gist/mohantym/1e584983175afbc9aea23058d79702a5/tfl_strided_slice_issue.ipynb#scrollTo=znYiYJtf6qWR) and [nightly](https://colab.sandbox.google.com/gist/mohantym/1e584983175afbc9aea23058d79702a5/tfl_strided_slice_issue.ipynb#scrollTo=znYiYJtf6qWR) . Thanks!

**Comment by impjdi** [comment]
TFLite GPU is not 100% compatible with all the ops & options.  As the error message says:

> Slice does not support shrink_axis_mask parameter.

You can look for that string in `//tensorflow/lite/delegates/gpu/common/model_builder.cc`.

**Comment by sebastian-sz** [comment]
@impjdi Are there plans to support this feature? in 2.3.0 such model works correctly in Tensorflow Lite + GPU.

**Comment by impjdi** [comment]
Not being in the TFLite team myself, I have no idea what the process is and how the priorities are set.

re: 

> in 2.3.0 such model works correctly in Tensorflow Lite + GPU.

I'm not sure why it would.  Maybe tflite convert didn't populate those and instead produced different network that didn't require that.  Is it possible for you to be explicit with reshapes to eliminate the axis thingy?

**Comment by sebastian-sz** [comment]
@impjdi Thank you for the response


> Is it possible for you to be explicit with reshapes to eliminate the axis thingy?

I need to access the last N (e. g. 5) elements of a tensor while preserving other dimensions:
`x = inputs[:, :, :5]`
is there a way to achieve this so that it works with Tensorflow Lite GPU Delegate?
