### ISSUE TITLE
Keras Sequential using RNN not working on M1 Max GPU

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [tensorflow/tensorflow#56082]
<details><summary>Click to expand!</summary> 
 
### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8.0

### Custom Code

No

### OS Platform and Distribution

MaxOS 12.3.1 

### Python version

3.9

### GPU model and memory

M1 Max 26 cores GPU

### Current Behaviour?

If using a `Sequential` model, I use a `SimpleRNN` layer, there is no way to use the GPU as device (no problem with the same code on Colab, every runtime works).

The same code using:
```
with tf.device("/device:CPU:0"):
  ...
```
works fine, but takes a while

### Standalone code to reproduce the issue

```shell
from tensorflow import keras
(X_train, y_train), (X_test, y_test) = keras.datasets.imdb.load_data(num_words=10000)
(X_valid, X_test) = X_test[:12500], X_test[12500:]
(y_valid, y_test) = y_test[:12500], y_test[12500:]
word_index = keras.datasets.imdb.get_word_index()
X_train_trim = keras.preprocessing.sequence.pad_sequences(X_train, maxlen=500)
X_test_trim = keras.preprocessing.sequence.pad_sequences(X_test, maxlen=500)
X_valid_trim = keras.preprocessing.sequence.pad_sequences(X_valid, maxlen=500)
model = keras.models.Sequential()
model.add(keras.layers.Embedding(input_dim=10000, output_dim=10))
model.add(keras.layers.SimpleRNN(32))
model.add(keras.layers.Dense(1, "sigmoid"))

model.compile(loss='binary_crossentropy', optimizer="adam", metrics=["accuracy"])

history = model.fit(X_train_trim, y_train,epochs=10, batch_size=128, validation_data=(X_valid_trim, y_valid))
```

### Relevant log output

```shell
Metal device set to: Apple M1 Max
systemMemory: 32.00 GB
maxCacheSize: 10.67 GB
2022-05-12 14:36:06.487099: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-05-12 14:36:06.487233: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2022-05-12 14:36:07.054786: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
Epoch 1/10
2022-05-12 14:36:07.290001: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
  1/196 [..............................] - ETA: 5:01:59 - loss: 0.6936 - accuracy: 0.5469
```
</details>

**Comment by AlbertoSinigaglia** [comment]
The same code using:
```
with tf.device("/device:CPU:0"):
    history = model.fit(X_train_trim, y_train,epochs=10, batch_size=128, validation_data=(X_valid_trim, y_valid))
```
Works fine, so I think it's something related to the hardware

**Comment by sushreebarsa** [comment]
@AlbertoSinigaglia Thank you for the update!
Please move this issue to closed status if it is resolved ?
Thank you!

**Comment by sushreebarsa** [comment]
@AlbertoSinigaglia Thank you for clarifying the confusion.
Could you please try with the latest  tf-nightly and let us know if the issue still persists ?
Thank you!

**Comment by AlbertoSinigaglia** [comment]
How should I install it? 

    pip install tf-nightly

returns:
```
ERROR: Could not find a version that satisfies the requirement tf-nightly (from versions: none)
ERROR: No matching distribution found for tf-nightly
```

and also the whl are not working:
```
pip install tf_nightly-2.10.0.dev20220512-cp39-cp39-macosx_10_14_x86_64.whl 
ERROR: tf_nightly-2.10.0.dev20220512-cp39-cp39-macosx_10_14_x86_64.whl is not a supported wheel on this platform.
```

**Comment by AlbertoSinigaglia** [comment]
By the way, it's literally only `SimpleRNN` that is causing problem, also the same code without the embedding layer works fine, and same for the same code using LSTM instead of `SimpleRNN`

**Comment by AlbertoSinigaglia** [comment]
Tried many other thing, the only solution for the moment is to uninstall `tensorflow-metal` (I tried all the versions, all have the same issue), but it means that everything runs on the CPU (even though for the project I'm doing, the performances are more or less the same, for some reason)

**Comment by gadagashwini** [comment]
@AlbertoSinigaglia, 
Looks like tensorflow-metal or Tensorflow on M1 chip has limited support for GPU. 
Could you check this [link](https://developer.apple.com/metal/tensorflow-plugin/). Thanks!

**Comment by JZ76** [comment]
I got same issue, TensorFlow-metal==0.4.0 TensorFlow-macos==2.8.0 python3.9 M1 max. After fit() function, only shows `2022-06-14 13:47:18.695745: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
Epoch 1/15
2022-06-14 13:47:19.146313: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.` and I can see cpu% is 300 gpu% is 100 , but no progress bar no matter how long I wait. However, if I don't use RNN, for example, only has dense layer in my model, everything works well.
