### ISSUE TITLE
How to dynamically select scope of untied variables during tf.while_loop?

### ISSUE THREAD

**Issue by ethancaballero** [tensorflow/tensorflow#5608]
When using python for loop, one simply creates/selects a new untied variable by using the incrementor to change the scope:
```
for i range(num_untied_layers):  
     with tf.variable_scope("untied_attention_hop" + "/" + str(i)):
          Wt = tf.get_variable("W_t")
          bt = tf.get_variable("bias_t")
```

How would one do this with tf.while_loop?

@DeNeutoy

**Comment by DeNeutoy** [comment]
@ethancaballero As far as I am aware it is not possible to do this, as the `tf.while_loop` is not actually creating a dynamic graph - it is merely an instruction to repeat part of the graph until a condition is satisfied.

However, presumably there is sum upper bound on the number of layers your want your model to have. What you should then do, is create these variables beforehand in a python for loop:

Wt = []
`for i in range(num_untied_layers):
    with tf.variable_scope("W_{}".format(i))
        Wt[i] = tf.get_variable("Wt")
`
Then, you can evaluate these within your loop by using tf.case - this is a bit ugly and there is probably a better way to do it:

`def generate_predicate_function_pair(counter, i):
    return (tf.less(counter, i), function_using_ith_weight(inputs, weights, ...))

predicate_list = [generate_predicate_function_pair(i) for i in range(max_attention_hops)] 

# Now start a while loop which contains a tensor constant called counter which just
# increments the loop .....
result = tf.case(predicate_list, exclusive=True)
`

**Comment by DeNeutoy** [comment]
Another idea would be to use TensorArrays:

As before:
```
Wt = []
with tf.variable_scope("one_weight_to_rule_them_all"):
    large_weight = tf.get_variable("Wt", [max_steps*input_size, output_size])

# The clear_after_read variable must be False, otherwise the TA will only allow you to read from that
# index once.
weight_container = tf.TensorArray(tf.float32, max_steps, clear_after_read=False, dynamic_size=None)

# This initialises the TensorArray with the weights broken up in to pieces.
# The reason this has to be a TensorArray is so that we can index it with a tensor(!)
weight_container = weight_container.unpack(large_weight)

# Now inside the while_loop with a counter variable AND the weight_container as a loop_var:

weight_to_use = weight_container.read(counter)

```
counter needs to be a integer scalar tensor which is incremented by one within the while_loop.

**Comment by ethancaballero** [comment]
@DeNeutoy Thanks for the quick reply.

^Does one of those ideas run faster than the other?

Also, do you have any advice for dealing with asynchronous halting times within a batch. For example, if one member of batch decides to take 20 hops (which finish slower) and the rest of the batch decides to take ≤ 3 hops (which finish quickly), the next batch can't be processed until the longer 20 hop member finishes.

Was this your workaround, and is there a reason that the cost isn't passed with the asynchronous version? :
https://github.com/DeNeutoy/act-rte-inference/blob/master/epoch.py#L108

**Comment by girving** [comment]
This type of question is better suited to StackOverflow.  Github issues are for bug reports and feature requests.
