### ISSUE TITLE
from tensorflow.models.rnn import linear causes error in python3

### ISSUE THREAD

**Issue by jstaker7** [tensorflow/tensorflow#561]
from tensorflow.models.rnn import linear
  File "/Users/Peace/Projects/venvs/allen/lib/python3.5/site-packages/tensorflow/models/rnn/linear.py", line 25, in <module>
    linear = tf.nn.linear
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'linear'

This is using the 0.6 wheel in OS X

**Comment by proflim** [comment]
linear is defined in 
tensorflow-0.6.0/tensorflow/python/ops/rnn_cell.py

**Comment by girving** [comment]
@ebrevdo: I don't think `tf.nn.linear` is supposed to exist, but `models/rnn/linear.py` uses it.  Is this because we're missing a unit test?

**Comment by ebrevdo** [comment]
linear is deprecated and shouldn't be used by external users. I'll look
through and see if we use it anywhere but internally in tf.nn.

**Comment by ebrevdo** [comment]
Closing because folks shouldn't be using linear.  But let me know if this breaks any existing models in python3 and i'll reopen.

**Comment by tle4336** [comment]
@ebrevdo: could you please help reopen linear? I am trying to execute the code provided here by Alex (https://github.com/atpaino/deep-text-corrector), but I keep getting this error message: AttributeError: module 'tensorflow.python.ops.rnn_cell' has no attribute '_linear'.

**Comment by ebrevdo** [comment]
You can find a version of the function _linear in an old version of
tensorflow (check the older version branches).  Copy and paste it into your
own codebase and use it there.  We will not be making it public.
