### ISSUE TITLE
How does TensorflowLite manage memory for GPU?

### ISSUE THREAD

**Issue by Sara980710** [tensorflow/tensorflow#56105]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

tf 2.4?

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04.3 LTS

### Mobile device

Unibap ix5

### GCC/Compiler version

9.3.0

### GPU model and memory

AMD GX-412HC SOC with Radeon(TM) R3E Graphics

### Current Behaviour?
Hello! 
I am wondering how TFLite is handling memory during inference. There are three main questions.

In the code below I have included two methods for putting the tiled image into the input tensor:
- using memcpy
- putting the values one by one

Question 1:
The memcpy-method is however getting an error when I try to use a model with batch size 3, but batch size 1 and 2 works. All batch sizes work for the second method. Why is this and how do I make the memcpy work? 

Question 2:
When does TFLite copy over the image values to the GPU? Is it during the invoke-command or is it when I copy the values to the input tensor (method 1 or 2)? 

Question 3:
What happens during the overall program? When I use top, I see the following behavior on a 10000x10000 image with 1x480x480x3 as model input size:
- During preprocess
  Virual memory: 1.843236 GB
  Resident size: 0.123656 GB
  Shared memory: 71736 KB
  CPU power: 100% 
- During loop for inference
  Virual memory: 2.146136 GB
  Resident size: 0.419956 GB
  Shared memory: 72488 KB
  CPU power: 19.1%

Best regards
Sara Larsson

### Standalone code to reproduce the issue

```shell
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/tools/gen_op_registration.h"
#include "tensorflow/lite/delegates/gpu/delegate.h"

#include <iostream>
#include <opencv2/opencv.hpp>

int main(int argc, char **argv) {
    if (argc != 4) {
        throw std::invalid_argument("Required arguments: \n            "
                                    "-path to TFLite model file \n            "
                                    "-path to image input\n            "
                                    "-method (1 or 2)");
    }
    const char *modelFileName = argv[1];
    const char *imageFileName = argv[2];
    const int method = std::stoi(argv[3]);

    std::unique_ptr< tflite::FlatBufferModel > model;
    tflite::ops::builtin::BuiltinOpResolver resolver;
    std::unique_ptr<tflite::Interpreter> interpreter;

    model = tflite::FlatBufferModel::BuildFromFile(modelFileName);
    if (model == nullptr) {
        throw std::runtime_error("The model was not able to build to tflite::FlatBufferModel");
    }
    
    tflite::InterpreterBuilder(*model, resolver)(&interpreter);
    if (interpreter == nullptr){
        throw std::runtime_error("Failed to initiate the interpreter");
    }

    // Enable use of the GPU delegate, remove below lines to get cpu
    // After TFlite >=2.6, initiate the gpu options
    TfLiteGpuDelegateOptionsV2 gpu_options = TfLiteGpuDelegateOptionsV2Default();

    TfLiteDelegate* delegate = TfLiteGpuDelegateV2Create(&gpu_options);
    if (interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk) {
        throw std::runtime_error("Failed to create GPU deligate");
        exit(-1);
    }

    // Allocating tensors
    if (interpreter->AllocateTensors() != kTfLiteOk){
        throw std::runtime_error("Failed to allocate tensor");
    }
    

    // Read image
    cv::Mat image = cv::imread(imageFileName);
    if (image.empty())
    {
        throw std::runtime_error("Failed to load image");
        exit(-1);
    }
    
    int input = interpreter->inputs()[0];
    int* inDims = interpreter->tensor(input)->dims->data;
    std::vector<cv::Rect> tiles;
    int currentTile;

    // Calculate how to tile image
    for (int x=0; x < image.size().width; x += inDims[2]) {
        for (int y=0; y < image.size().height; y += inDims[1]) {
        // Handle edges
        if (x + inDims[2] >= image.size().width && y + inDims[1] >= image.size().height) {
            tiles.push_back(cv::Rect(image.size().width - inDims[2], image.size().height - inDims[1], inDims[2], inDims[1]));
        } else {
            if (x + inDims[2] >= image.size().width) {
            tiles.push_back(cv::Rect(image.size().width - inDims[2], y, inDims[2], inDims[1]));
            } else if (y + inDims[1] >= image.size().height) {
            tiles.push_back(cv::Rect(x, image.size().height - inDims[1], inDims[2], inDims[1]));
            } else {
            tiles.push_back(cv::Rect(x, y, inDims[2], inDims[1]));
            }
        }
        }
    }

    //Invoke
    while (currentTile != -1) {
        if (method == 1) {
            int tileByteSize = inDims[1] * inDims[2] * inDims[3] * 4;

            for (int i=0; i < inDims[0]; i++) {
                cv::Mat tile = image(tiles[currentTile]);
                tile.convertTo(tile, CV_32F, 1.0 / 255, 0);
                memcpy(interpreter->typed_tensor<float>(0)+tileByteSize*i, tile.data, tileByteSize); 
            }
        } else if (method == 2) {
            for (int i=0; i < inDims[0]; i++) {
                cv::Mat tile = image(tiles[currentTile]);
                float* input_tensor_float = interpreter->typed_tensor<float>(0);
            
                for (int idx = 0; idx < tile.size[1] * tile.size[0]; idx++){
                    int col = idx % tile.size[0];
                    int row = idx / tile.size[0];
                    cv::Vec3b intensity = image.at<cv::Vec3b>(row, col);
                    
                    input_tensor_float[(inDims[1] * inDims[2] * inDims[3]*i+idx*3+0)] = float(intensity.val[0])/ 255; //R <- B
                    input_tensor_float[(inDims[1] * inDims[2] * inDims[3]*i+idx*3+1)] = float(intensity.val[1])/ 255; //G <- G
                    input_tensor_float[(inDims[1] * inDims[2] * inDims[3]*i+idx*3+2)] = float(intensity.val[2])/ 255; //B <- R
                }
            }
        }

        currentTile = inDims[0] + currentTile;
        if (currentTile != -1 && currentTile >= tiles.size()) {
            currentTile = -1;
        }
        m_interpreter->Invoke();
    }
}
```

**Comment by impjdi** [comment]
> The memcpy-method is however getting an error when I try to use a model with batch size 3, but batch size 1 and 2 > works. All batch sizes work for the second method. Why is this and how do I make the memcpy work?

You need to look deeper into `cv::Mat`.  IIRC `cv::Mat` has something called `step`.  You probably have to multiply things by this rather than the dimensions you think you have.  At that point, I don't think you can use `std::memcpy`, as `TfLiteTensor` has to be contiguous.  You can probably use `std::memcpy` block-wise.

> When does TFLite copy over the image values to the GPU? Is it during the invoke-command or is it when I copy the values to the input tensor (method 1 or 2)?

That happens as part of `Interpreter::Invoke`.  

> What happens during the overall program? When I use top, I see the following behavior on a 10000x10000 image with 1x480x480x3 as model input size:

I'm not sure I understand your question.  Are you concerned about the 400MB more memory consumption?

**Comment by Sara980710** [comment]
Hello, thank you for your answer! 

> You need to look deeper into cv::Mat. IIRC cv::Mat has something called step. You probably have to multiply things by this rather than the dimensions you think you have. At that point, I don't think you can use std::memcpy, as TfLiteTensor has to be contiguous. You can probably use std::memcpy block-wise.

Okay, so does this mean that the tensor input memory location is contiguous, but not the memory location for cv::Mat? 

> When does TFLite copy over the image values to the GPU? Is it during the invoke-command or is it when I copy the values to the input tensor (method 1 or 2)?

> > That happens as part of Interpreter::Invoke.
Has TFLite already allocated the memory-space for the input tensor when I first created the interpreter or is it allocated first when I copy the values over to the input tensor? And then when I run the invoke, it copies all values once again to the GPU? 

Does it do it the same way when using CPU? 

> What happens during the overall program? When I use top, I see the following behavior on a 10000x10000 image with 1x480x480x3 as model input size:

> > I'm not sure I understand your question. Are you concerned about the 400MB more memory consumption?

I guess my question is more, what happens in different stages. My guess is:
Preprocess: GPU Deligate + Imported image + tensor allocation = 1.843236 GB VIRT
Inference: GPU Deligate + Imported image + tensor allocation  + cv::Mat tile + ? = 2.146136 GB VIRT

Best regards
Sara Larsson

**Comment by impjdi** [comment]
Sorry, forgot to reply to this one.

> Okay, so does this mean that the tensor input memory location is contiguous, but not the memory location for cv::Mat?

That is correct.

> Does it do it the same way when using CPU?

On the CPU, you don't have a GPU upload / download phase.  I don't think I understand your question.

> Inference: GPU Deligate + Imported image + tensor allocation + cv::Mat tile + ? = 2.146136 GB VIRT

I can't think of anything where GPU delegate would use additional memory beyond initialization.  The memory consumption after `ModifyGraphWithDelegate` should be the same as the memory footprint after `Invoke`.

**Comment by Sara980710** [comment]
No problems, I can show you the graphs I have gotten when measuring a run on CPU and GPU with inference running a 10000x10000 image with 1440x1440 tiles for the input:
![GPUvsCPU](https://user-images.githubusercontent.com/38947347/170702670-e41ce559-7fda-421c-8d27-bfff923d4b88.png)
First graph is the virutal memory, second the resident size, third is the shared memory and the last CPU usage in %. If you look at the blue lines for GPU, it is where it increases in the end that the inference is happening, before it is only creating the delegate it seems. The CPU starts with the inference directly.

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.

**Comment by Sara980710** [comment]
This is not relevant anymore since I asked this more than a years ago....
