### ISSUE TITLE
Type Error in Conversion From Saved Model to TFLite model

### ISSUE THREAD

**Issue by yakupakkaya** [tensorflow/tensorflow#56104]
When I tried to convert a custom saved model (faster rcnn with custom data) to TFLite model I am receiving the following error. What is the possible reason and solution?

ConverterError: <unknown>:0: error: loc(callsite(callsite(fused["Mul:", "MultiLevelMatMulCropAndResize/MultiLevelRoIAlign/mul_17@__inference_call_func_16203"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_19429"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): 'tfl.reshape' op operand #1 must be tensor of 32-bit signless integer values, but got 'tensor<6xi64>'
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from

Model original is trained with TF2 object detection API 

### Source code / logs
import tensorflow as tf

saved_model_path = "/home/exx/TensorFlow/train/models/faster-rcnn-clr/exported-models/saved_model"

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_path) # path to the SavedModel directory
tflite_model = converter.convert()

with open('model_R1.tflite', 'wb') as f:
  f.write(tflite_model)

**Comment by mkxyh** [comment]
The possible reason for this error is : `op operand must be tensor of 32-bit signless integer values, but got 'tensor<6xi64>'` 

It would be nice to see the code for the tensor inputs upstream before saving the model to replicate the error.

Can you try specifying your input to a 32-bit signless integer. See if that works.
ex:
`tf.Tensor([2 4], shape=(2,), dtype=int32) `

**Comment by yakupakkaya** [comment]
I used "TensorFlow/models/research/object_detection/exporter_main_v2.py" to create a saved model. It has the following argument for the input:

--input_type image_tensor

Can be one of the:

 [`image_tensor`, `encoded_image_string_tensor`, '
                    '`tf_example`, `float_image_tensor`

So I modified the function in exporter.py as 

def _image_tensor_input_placeholder(input_shape=None):
  """Returns input placeholder and a 4-D uint8 image tensor."""
  if input_shape is None:
    input_shape = (None, None, None, 3)
  **input_tensor = tf.placeholder(
      dtype=tf.int32, shape=input_shape, name='image_tensor')**
  return input_tensor, input_tensor

I  am still having the same error.

**Comment by mkxyh** [comment]
I was looking at the tfhub.dev link: `https://tfhub.dev/tensorflow/faster_rcnn/resnet152_v1_640x640/1`

I'm curious if you applied batching at training?

The notes on the link above state:
`Inputs

A three-channel image of variable size - the model does NOT support batching. The input tensor is a tf.uint8 tensor with shape [1, height, width, 3] with values in [0, 255].`

maybe try ` tf.uint8 `.

**Comment by yakupakkaya** [comment]
Yes, I used batching.  The batch size is 2 since I have 2 GPU. I don't think that is an issue, but is there sth wrong with that?

tf.uint8 was already default value. I changed it to tf.int32.

**Comment by mkxyh** [comment]
Hey I would change the script back to the original values uint8 and try running it on one gpu without batching, Im sorry to confuse you I hope someone else can help.

**Comment by mohantym** [comment]
Hi @yakupakkaya ! Sorry for the late response. Could you please provide a Colab gist with the above stack trace and model ? Thank you!

**Comment by yakupakkaya** [comment]
Here is the Colab link, https://colab.research.google.com/drive/19JiB0sriIO7uhtyDbrbXRJXW7_P4EXhN?usp=sharing 

and the link for model, https://drive.google.com/drive/folders/1IQ3T83J_TYVoWuLVlvFUJP_WdKy-bXnV?usp=sharing 

Thanks

**Comment by mkxyh** [comment]
Hey I got your model to work on my local machine:

The code is below, please try it out, I am using tf version 2.8 nightly:

`import tensorflow as tf`
`path_to_downloaded_file = "YOURFILELOCATION/Downloads/tf_saved_model-20220517T011545Z-001/tf_saved_model/"
`

`loaded = tf.saved_model.load(path_to_downloaded_file)`
`print(list(loaded.signatures.keys()))  # ["serving_default"]`

`infer = loaded.signatures["serving_default"]`

`print(infer.structured_outputs)`

`# Convert the saved model using TFLiteConverter
SAVED_MODEL_PATH=path_to_downloaded_file
converter = tf.lite.TFLiteConverter.from_saved_model(SAVED_MODEL_PATH)
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops. ----->I think you missed this step (1)
    tf.lite.OpsSet.SELECT_TF_OPS  # enable TensorFlow ops. ---->I think you missed this (2)
]`

`tflite_model = converter.convert()`

`# Print the signatures from the converted model`
`interpreter = tf.lite.Interpreter(model_content=tflite_model)`
`signatures = interpreter.get_signature_list()`
`print(signatures)`



``

``

``

**Comment by mohantym** [comment]
@yakupakkaya !  Could you try instruction here in this [thread](https://towardsdatascience.com/deploying-pretrained-tf-object-detection-models-on-android-25c3de92caab) with [export_tflite_ssd_graph](https://github.com/tensorflow/models/blob/master/research/object_detection/export_tflite_ssd_graph.py) with 2.9 version. You can also check our TFLite model maker thread on [custom object detection ](https://www.tensorflow.org/lite/tutorials/model_maker_object_detection).  Issues has been observed on default TFlite converter with pretrained object detection models . Thank you!

**Comment by yakupakkaya** [comment]
@mohantym  export_tflite_ssd_graph.py does not work for faster_rcnn. How can I convert  my custom model? Do you have any alternative solution?

**Comment by karimnosseir** [comment]
I have a fix for the issue. Will be pushed soon.
Sorry for the trouble.

Thanks
