### ISSUE TITLE
bazel build TensorFlow Lite 2.7.0 with Select TensorFlow operators for iOS failed

### ISSUE THREAD

**Issue by snowuyl** [tensorflow/tensorflow#56113]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.7

### Custom Code

No

### OS Platform and Distribution

macOS 12.3.1

### Mobile device

iPhone

### Python version

3.9.10

### Bazel version

3.7.2

### GCC/Compiler version

Apple clang version 13.1.6

### Current Behaviour?

```shell
bazel build TensorFlow Lite 2.7.0 with Select TensorFlow operators for iOS successfully.
```

### Standalone code to reproduce the issue

```shell
bazel build -c opt --config=ios --ios_multi_cpus=armv7,arm64 //tensorflow/lite/ios:TensorFlowLiteSelectTfOps_framework
```

### Relevant log output

```shell
ERROR: Skipping '//tensorflow/lite/ios:TensorFlowLiteSelectTfOps_framework': no such package 'tensorflow/lite/ios': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.7.0_selops_ios/tensorflow/lite/ios
WARNING: Target pattern parsing failed.
ERROR: no such package 'tensorflow/lite/ios': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.7.0_selops_ios/tensorflow/lite/ios
INFO: Elapsed time: 0.284s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```
</details>

**Comment by snowuyl** [comment]
I have solved BUILD file not found issue as follows.
Run the ./configure script in the root TensorFlow checkout directory, and answer "Yes" when the script asks if you wish to build TensorFlow with iOS support.

**Comment by mohantym** [comment]
Ok @snowuyl ! Glad to see it resolved . Could we move this to closed status then?
