### ISSUE TITLE
bazel build TensorFlow Lite 2.7.0 for iOS failed

### ISSUE THREAD

**Issue by snowuyl** [tensorflow/tensorflow#56114]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.7

### Custom Code

No

### OS Platform and Distribution

macOS 12.3.1

### Mobile device

iPhone

### Python version

3.9.12

### Bazel version

3.7.2

### GCC/Compiler version

Apple clang version 13.1.6

### Current Behaviour?

```shell
bazel build TensorFlow Lite 2.7.0 for iOS successfully.
```

### Standalone code to reproduce the issue

```shell
bazel build --config=ios_fat -c opt //tensorflow/lite/ios:TensorFlowLiteC_framework
```

### Relevant log output

```shell
ERROR: Skipping '//tensorflow/lite/ios:TensorFlowLiteC_framework': no such package 'tensorflow/lite/ios': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.7.0_ios/tensorflow/lite/ios
WARNING: Target pattern parsing failed.
ERROR: no such package 'tensorflow/lite/ios': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.7.0_ios/tensorflow/lite/ios
INFO: Elapsed time: 5.298s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```
</details>

**Comment by snowuyl** [comment]
I have solved BUILD file not found issue as follows.
Run the ./configure script in the root TensorFlow checkout directory, and answer "Yes" when the script asks if you wish to build TensorFlow with iOS support.

**Comment by tilakrayal** [comment]
Hello @snowuyl ,
Looks like this is duplicate of issue #56113.Can you please close this issue, since it is already being tracked there? Thanks!

**Comment by snowuyl** [comment]
But I encounter another issue (env: python: No such file or directory).
ERROR: /Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.7.0_ios/tensorflow/lite/ios/BUILD:104:21: Bundling Preprocessed_TensorFlowLiteC_framework failed (Exit 127): bundletool failed: error executing command bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool bazel-out/darwin-opt/bin/tensorflow/lite/ios/Preprocessed_TensorFlowLiteC_framework-intermediates/bundletool_control.json
env: python: No such file or directory
Target //tensorflow/lite/ios:TensorFlowLiteC_framework failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 382.259s, Critical Path: 37.77s
INFO: 3681 processes: 12 internal, 3669 local.
FAILED: Build did NOT complete successfully

**Comment by snowuyl** [comment]
which python
python: aliased to /usr/bin/python3

**Comment by mohantym** [comment]
Hi @snowuyl ! Can you check this [thread](https://stackoverflow.com/questions/3655306/ubuntu-usr-bin-env-python-no-such-file-or-directory) to rename the path /user/bin/python3 to /user/bin/python ? Thanks!

**Comment by snowuyl** [comment]
I have upgraded TensorFlow to 2.9 and bazel 5.0.0 and building TFLite for iOS successfully.
