### ISSUE TITLE
Tensorflow is failing on Bazel CI (release Bazel + HEAD TF)

### ISSUE THREAD

**Issue by Wyverald** [tensorflow/tensorflow#56118]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

HEAD

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Bazel version

5.1.1

### GCC/Compiler version

7.4.0

### Current Behaviour?

```shell
https://buildkite.com/bazel/tensorflow/builds/7777#1132f1e2-efac-44fc-b57b-b1068aa08662

AttributeError: module 'typing' has no attribute '_SpecialForm'
```

### Standalone code to reproduce the issue

```shell
N/A
```

### Relevant log output

_No response_</details>

**Comment by bhack** [comment]
Is this https://github.com/tensorflow/tensorflow/issues/55829 ?
