### ISSUE TITLE
Bert ModelSpec Export to TFLITE does not work

### ISSUE THREAD

**Issue by philippHeitzer** [tensorflow/tensorflow#56110]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04.3 LTS

### Python version

3.8.10

### GCC/Compiler version

GCC 9.3.0

### CUDA/cuDNN version

V11.6.55

### GPU model and memory

RTX5000, 16 GB

### Current Behaviour?

```shell
The trained Bert Model with the Tensorflow Lite Model Maker works fine, but I cannot export the Model to TFLITE-file. The code window keeps running, but nothing happens (even after 6h waiting). The issue does not appear with the models 'average_word_spec' and 'mobileBert'.
```

### Standalone code to reproduce the issue

```shell
batch_sizes=[512,256,128,64,32,16]
sequence_lengths= [16,32,64,128,256,512]
training_ratio= 0.66

spec = text_classifier.BertClassifierSpec(
                     uri='https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/1',seq_len=sequence_lengths[index],dropout_rate=0.5,default_batch_size=batch_sizes[index],name='Bert')

                data = DataLoader.from_csv(
                      filename='fake_new_dateset_new.csv',
                      text_column='Content',
                      label_column='label',
                      model_spec=spec,
                      is_training=True,
                      shuffle= False)

                train_data,test_data=data.split(training_ratio)
                train_data,validation_data= train_data.split(training_ratio)

                model = text_classifier.create(train_data, model_spec=spec, validation_data=validation_data, epochs=epoch)

                loss_test,acc_test= model.evaluate(test_data)
                loss_val,acc_val= model.evaluate(validation_data)

                model.export(export_dir='Bert_dataset1/', export_format=ExportFormat.TFLITE)
                accuracy_file = model.evaluate_tflite('Bert_dataset1/model.tflite', test_data)

                file_size = os.path.getsize('Bert_dataset1/model.tflite')
```

### Relevant log output

```shell
WARNING:absl:Found untraced functions such as restored_function_body, restored_function_body, restored_function_body, restored_function_body, restored_function_body while saving (showing 5 of 815). These functions will not be directly callable after loading.
```
</details>

**Comment by mohantym** [comment]
Hi @philippHeitzer ! Can you check this [gist](https://colab.sandbox.google.com/gist/mohantym/0c1837c8a219327afbe4680757026522/git_56110.ipynb) for required changes? Thanks!

**Comment by philippHeitzer** [comment]
> Hi @philippHeitzer ! Can you check this [gist](https://colab.sandbox.google.com/gist/mohantym/0c1837c8a219327afbe4680757026522/git_56110.ipynb) for required changes? Thanks!

Thank you for your help. The code seems to work on Google Colab, but not on https://console.paperspace.com/pheitzer/notebook/rsnqh1w7dvedob3
where nothing happens after : "INFO:tensorflow:Assets written to: /tmp/tmp3l2ik0s_/saved_model/assets".
Unfortunately, it is not possible to use Google Colab Pro+ from Austria to get the possibility to use better GPUs.

**Comment by philippHeitzer** [comment]
While installing Tensorflow Lite Model maker by:

!pip install tflite-model-maker

Following error message appears:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dask-cuda 21.12.0 requires numba>=0.53.1, but you have numba 0.53.0 which is incompatible.
cudf 21.12.0a0+293.g0930f712e6 requires numba>=0.53.1, but you have numba 0.53.0 which is incompatible.

Maybe is this reason for the problem?

**Comment by philippHeitzer** [comment]
And at importing things from tflite_model_maker:

/usr/local/lib/python3.8/dist-packages/tensorflow_addons/utils/ensure_tf_install.py:53: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.5.0 and strictly below 2.8.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.8.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version.

**Comment by philippHeitzer** [comment]
> And at importing things from tflite_model_maker:
> 
> /usr/local/lib/python3.8/dist-packages/tensorflow_addons/utils/ensure_tf_install.py:53: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.5.0 and strictly below 2.8.0 (nightly versions are not supported). The versions of TensorFlow you are currently using is 2.8.0 and is not supported. Some things might work, some things might not. If you were to encounter a bug, do not file an issue. If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version.

To solve this problems I installed:  tensorflow-addons==0.16.1,so that this error message does not occur again.

I also followed your instructions with using tensorflow v2.7.0 ("pip install tflite_model_maker tensorflow==2.7").
But unfortunately this also didn't solve the original problem of not exporting the Bert_Model to .tflite. 
It never comes to the step: "INFO:tensorflow:Vocab file and label file are inside the TFLite model with metadata."

![image](https://user-images.githubusercontent.com/72654136/168628641-0c85733f-82c9-4765-84d6-7cbaebd66f5e.png)

**Comment by mohantym** [comment]
Ok @philippHeitzer! Thanks for the update. 
Could you skip the tflite format and try with below commands and let us know. Thank you!
```
TFLITE_FILENAME = 'object_detector.tflite'
SAVE_PATH = './models'

print(f'Exporing the model to {SAVE_PATH}')
model.export(SAVE_PATH, tflite_filename=TFLITE_FILENAME)
```

**Comment by philippHeitzer** [comment]
Unfortunately, nothing changed.
![image](https://user-images.githubusercontent.com/72654136/168821618-027c59b3-f914-4f96-afb1-66dc7b761479.png)

Just the directory "models" was created.

**Comment by philippHeitzer** [comment]
Without executing "apt -y install libusb-1.0-0-dev" I get this error at importin tflite_model_maker libs:

ImportError: libusb-1.0.so.0: cannot open shared object file: No such file or directory

![image](https://user-images.githubusercontent.com/72654136/168823272-018a2952-8f97-450c-b1fd-ad0ab267b914.png)
...
![image](https://user-images.githubusercontent.com/72654136/168823194-f585c549-7f55-4ac4-8cc4-fd4dbf3abd53.png)



Maybe there is something wrong with that metadata. Can this be related?

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue? Attaching [gist ](https://colab.sandbox.google.com/gist/mohantym/0c1837c8a219327afbe4680757026522/git_56110.ipynb)for reference. Thank you!

**Comment by smilingday** [comment]
@ziyeqinghan take a look.

**Comment by ziyeqinghan** [comment]
Can you try first export it to saved_model and then use tf.lite.converter directly to see if it can be converted successfully?
```
model.export('./bert/', export_format=ExportFormat.SAVED_MODEL)
converter =  tf.lite.TFLiteConverter.from_saved_model('./bert/saved_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
```

Meanwhile, may I ask why you want BERT model instead of mobileBERT? We usually recommend mobileBERT model instead since it can achieve similar accuracy result while have much smaller model size and lower latency.

**Comment by philippHeitzer** [comment]
> model.export('./bert/', export_format=ExportFormat.SAVED_MODEL)
> converter =  tf.lite.TFLiteConverter.from_saved_model('./bert/saved_model')
> converter.optimizations = [tf.lite.Optimize.DEFAULT]
> tflite_model = converter.convert()

I am currently analyzing these three proposed models from tflite-model-maker for my bachelor thesis. And since I am already done with data collection for Word Embedding and mobileBert, it is necessary to test BERT under the same circumstances.

**Comment by ziyeqinghan** [comment]
Does the process finish? Or could you see if you can write the tflite_model? 
```
with open('./bert/model.tflite', 'wb') as f:
  f.write(tflite_model)
```

**Comment by philippHeitzer** [comment]
> with open('./bert/model.tflite', 'wb') as f:
>   f.write(tflite_model)

Yes that works, and for my experiments that is enough for now. Nevertheless it would be interesting to know what the problem is in this case for "model.export()" for the TFLITE format.

**Comment by tilakrayal** [comment]
@philippHeitzer,
I tried with the approach for the mentioned code and was executed without any issue/error and also I can see the model.tflite file was available. Kindly find the gist of it [here](https://colab.sandbox.google.com/gist/tilakrayal/b99604a8cf4f73281d11d379711f4abf/git_56110.ipynb).


```
loss, acc = model.evaluate(test_data)
#model.export(export_dir='Bert_dataset1/', export_format=ExportFormat.TFLITE)
#file_size = os.path.getsize('Bert_dataset1/model.tflite')
model.export('./bert/', export_format=ExportFormat.SAVED_MODEL)
converter =  tf.lite.TFLiteConverter.from_saved_model('./bert/saved_model')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

#file_size = os.path.getsize('Bert_dataset1/model.tflite')


with open('./bert/model.tflite', 'wb') as f:
  f.write(tflite_model)
```

![image](https://user-images.githubusercontent.com/81610181/221186018-99a7f851-b809-4937-b354-f695cbadf40c.png)

**Comment by tilakrayal** [comment]
Closing this as stale. Please reopen if this is still a valid request. Thank you!
