### ISSUE TITLE
Is there any way to let TensorFlow support Bitcode on iOS?

### ISSUE THREAD

**Issue by 413029811** [tensorflow/tensorflow#5611]
I'm trying to use TensorFlow on a iOS App, but my team required Bitcode enabled in the project, so I seek for help here.

**Comment by 413029811** [comment]
@petewarden

**Comment by girving** [comment]
@petewarden Is this an easy flag?

**Comment by petewarden** [comment]
It's possible this just requires updating some compiler flags in tensorflow/contrib/makefile/Makefile for the protobuf and tensorflow library builds, but it would require some investigation.

**Comment by girving** [comment]
@413029811 Can you try adding the `-fembed-bitcode` flag to the `Makefile` and see if it solves it for you?

**Comment by 413029811** [comment]
I added -fembed-bitcode in Makefile like this:
       ifeq ($(IOS_ARCH),ARMV7)
		-fembed-bitcode\
		CXXFLAGS += -miphoneos-version-min=$(MIN_SDK_VERSION) \
		-arch armv7 \
		-D__thread= \
		-DUSE_GEMM_FOR_CONV \
		-Wno-c++11-narrowing \
		-mno-thumb \
		-DTF_LEAN_BINARY \
		-D__ANDROID_TYPES_SLIM__ \
		-fno-exceptions \
		-isysroot \
		${IPHONEOS_SYSROOT}
		LDFLAGS := -arch armv7 \
		-miphoneos-version-min=${MIN_SDK_VERSION} \
		-framework Accelerate \
		-Xlinker -S \
		-Xlinker -x \
		-Xlinker -dead_strip \
		-all_load \
		-L$(GENDIR)protobuf_ios/lib \
		-lz
	endif
	ifeq ($(IOS_ARCH),ARMV7S)
		-fembed-bitcode\
		CXXFLAGS += -miphoneos-version-min=$(MIN_SDK_VERSION) \
		-arch armv7s \
		-D__thread= \
		-DUSE_GEMM_FOR_CONV \
		-Wno-c++11-narrowing \
		-mno-thumb \
		-DTF_LEAN_BINARY \
		-D__ANDROID_TYPES_SLIM__ \
		-fno-exceptions \
		-isysroot \
		${IPHONEOS_SYSROOT}
		LDFLAGS := -arch armv7s \
		-miphoneos-version-min=${MIN_SDK_VERSION} \
		-framework Accelerate \
		-Xlinker -S \
		-Xlinker -x \
		-Xlinker -dead_strip \
		-all_load \
		-L$(GENDIR)protobuf_ios/lib \
		-lz
	endif
	ifeq ($(IOS_ARCH),ARM64)
		-fembed-bitcode\
		CXXFLAGS += -miphoneos-version-min=$(MIN_SDK_VERSION) \
		-arch arm64 \
		-D__thread= \
		-DUSE_GEMM_FOR_CONV \
		-Wno-c++11-narrowing \
		-DTF_LEAN_BINARY \
		-D__ANDROID_TYPES_SLIM__ \
		-fno-exceptions \
		-isysroot \
		${IPHONEOS_SYSROOT}
		LDFLAGS := -arch arm64 \
		-miphoneos-version-min=${MIN_SDK_VERSION} \
		-framework Accelerate \
		-Xlinker -S \
		-Xlinker -x \
		-Xlinker -dead_strip \
		-all_load \
		-L$(GENDIR)protobuf_ios/lib \
		-lz
	endif
	ifeq ($(IOS_ARCH),I386)
		-fembed-bitcode\
		CXXFLAGS += -mios-simulator-version-min=$(MIN_SDK_VERSION) \
		-arch i386 \
		-D__thread= \
		-DUSE_GEMM_FOR_CONV \
		-Wno-c++11-narrowing \
		-DTF_LEAN_BINARY \
		-D__ANDROID_TYPES_SLIM__ \
		-fno-exceptions \
		-isysroot \
		${IPHONESIMULATOR_SYSROOT}
		LDFLAGS := -arch i386 \
		-mios-simulator-version-min=${MIN_SDK_VERSION} \
		-framework Accelerate \
		-Xlinker -S \
		-Xlinker -x \
		-Xlinker -dead_strip \
		-all_load \
		-L$(GENDIR)protobuf_ios/lib \
		-lz
	endif
	ifeq ($(IOS_ARCH),X86_64)
		-fembed-bitcode\
		CXXFLAGS += -mios-simulator-version-min=$(MIN_SDK_VERSION) \
		-arch x86_64 \
		-D__thread= \
		-DUSE_GEMM_FOR_CONV \
		-Wno-c++11-narrowing \
		-DTF_LEAN_BINARY \
		-D__ANDROID_TYPES_SLIM__ \
		-fno-exceptions \
		-isysroot \
		${IPHONESIMULATOR_SYSROOT}
		LDFLAGS := -arch x86_64 \
		-mios-simulator-version-min=${MIN_SDK_VERSION} \
		-framework Accelerate \
		-Xlinker -S \
		-Xlinker -x \
		-Xlinker -dead_strip \
		-all_load \
		-L$(GENDIR)protobuf_ios/lib \
		-lz
	endif

When I tried to run compile_ios_tensorflow.sh, command line printed:
/tensorflow/tensorflow/contrib/makefile/gen/lib/ios_ARMV7/libtensorflow-core-armv7.a(version_info.o), archive member 'version_info.o' with length 936 is not mach-o or llvm bitcode for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [tensorflow/tensorflow/contrib/makefile/gen/bin/ios_ARMV7/benchmark] Error 1
+ '[' 2 -ne 0 ']'
+ echo 'armv7 compilation failed.'
armv7 compilation failed.
+ exit 1

**Comment by girving** [comment]
@petewarden Unless you want to tackle this, should I mark it contributions welcome?

**Comment by petewarden** [comment]
I'm not likely to get to this in the short term, so that would be great, thanks.

**Comment by eaigner** [comment]
I adapted the build scripts and got

    ld: -bind_at_load and -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES) cannot be used together

**Comment by eaigner** [comment]
It actually works. Here are the steps:

- Add `export MACOSX_DEPLOYMENT_TARGET="10.12"` to `build_all_ios.sh`, otherwise you'll get a linker error (see above).
- Insert `-fembed-bitcode \` in `compile_ios_protobuf.sh` and `Makefile`
- Run `build_all_ios.sh`

You now have a working TF bitcode enabled iOS build.

**Comment by ankorko** [comment]
`export MACOSX_DEPLOYMENT_TARGET="10.12"` should be added to `compile_ios_protobuf.sh` if used independent of `build_all_ios.sh`.
