### ISSUE TITLE
[Feature Request] Default Keras callback for timing the training loop

### ISSUE THREAD

**Issue by Lokiiiiii** [tensorflow/tensorflow#56115]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

2.8

### Custom Code

No

### Current Behaviour?

```shell
The current Keras progress bar callback displays training latency in time/step. The current recommendation is to disable the progress bar in production workflows.

This poses 2 problems:

1. The metric time/step is not batch size agnostic. While tuning batch size to fit the H/W, metrics represented in terms of samples allow for better head to head comparison. Currently, an additional step of converting step to samples is required.

2. Production workflows that require continuous training will benefit greatly from being able to monitor training latency. A deterioration in training speed could lead to spike in training costs.

I propose:

1. Reporting an additional metric for training latency based on samples.

2. A new verbosity setting that allows for reporting the training latency metrics without the progress bar. This could even be part of an existing verbosity.

I would be happy to create a PR for these changes.
```

### Standalone code to reproduce the issue

```shell
N/A
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@Lokiiiiii 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by Lokiiiiii** [comment]
Migrated to https://github.com/keras-team/keras/issues/16544
