### ISSUE TITLE
TensorFlow Lite 2.9 ARM cross-compilation failed: Cannot find source file: common.c

### ISSUE THREAD

**Issue by distlibs** [tensorflow/tensorflow#56125]
**System information**

* Linux Ubuntu 20.04
* TensorFlow 2.9
* CMake 3.16.3
* gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf ([here](https://www.tensorflow.org/lite/guide/build_cmake_arm#download_toolchain_2))

**Describe the problem**

I trying to cross-compile TensorFlow Lite 2.9 for ARM using CMake. I got error "Cannot find source file: common.c":

```txt
CMake Error at CMakeLists.txt:63 (add_library):
  Cannot find source file:

    common.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at CMakeLists.txt:63 (add_library):
  No SOURCES given to target: tensorflowlite_c

CMake Generate step failed.  Build files cannot be regenerated correctly.
make: *** No targets specified and no makefile found.  Stop.
```

I seet that `.c` files has been renamed to `.cc` but CMakeLists.txt file left unchanged: [CMakeLists.txt](https://github.com/tensorflow/tensorflow/blob/v2.9.0/tensorflow/lite/c/CMakeLists.txt#L66)

I using build instructions provided [here](https://www.tensorflow.org/lite/guide/build_cmake_arm#build_for_armv7_neon_enabled)

**Comment by mohantym** [comment]
Hi @distlibs ! Build is passing for Ubuntu 18 in Colab. Could you check this [gist ](https://colab.sandbox.google.com/gist/mohantym/3609829c7620c200c73036690d166bbf/git_56125.ipynb#scrollTo=GRsHzNThHmpC)once ? Thank you!

**Comment by feliwir** [comment]
I get the same issue when compiling on x86 Linux. Inside the `contrib/tensorflow/tensorflow/lite/c/CMakeLists.txt:63` the non-existing file `common.c` is added. The file is now named `common.cc`

**Comment by distlibs** [comment]
Compilation is working fine after changing `common.c` to `common.cc` in the [CMakeLists.txt](https://github.com/tensorflow/tensorflow/blob/v2.9.0/tensorflow/lite/c/CMakeLists.txt#L66)

**Comment by feliwir** [comment]
Well, that's not really an option when using `tensorflow` as a submodule

**Comment by mohantym** [comment]
Ok @feliwir ! Thanks for update ! This issue will be closed once above [PR ](https://github.com/tensorflow/tensorflow/pull/54566)is merged. Thank you!

**Comment by mrdeveloperdude** [comment]
Can confirm this is a problem on Linux 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux.

Renaming changing from 'common.c' to 'common.cc' in tensorflow/lite/c/CMakeLists.txt fixes the problem.

**Comment by yanorei32** [comment]
one-line workaround for GNU sed systems.

```bash
sed -i 's/common\.c/common\.cc/' ./tensorflow/lite/c/CMakeLists.txt
```

Hopefully the CMakeLists.txt in the release has been corrected.

**Comment by sachinprasadhs** [comment]
The suggested solution is already merged in the PR [here](https://github.com/tensorflow/tensorflow/pull/57134), could you please check it in the nightly version and let us know. Thanks!

**Comment by sachinprasadhs** [comment]
Note: There has been few changes in the CMakeLists.txt since my last comment on this thread, refer the latest commit here https://github.com/tensorflow/tensorflow/commit/17e3646683f0149091384d250b27d6f52556ee78 for the changes and let us know if you still face an issue in the nightly build. Thanks!
