### ISSUE TITLE
Bazel build TensorFlow Lite 2.8.0 for iOS failed

### ISSUE THREAD

**Issue by snowuyl** [tensorflow/tensorflow#56129]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

No

### Mobile device

macOS 12.3.1 M1 (ARM64)

### Python version

3.9.12

### Bazel version

4.2.1

### GCC/Compiler version

Apple clang version 13.1.6

### Current Behaviour?

```shell
Can't build TensorFlow Lite 2.8 for iOS on MacBook Air M1(ARM64 CPU).
```

### Standalone code to reproduce the issue

```shell
bazel build --verbose_failures --config=ios --ios_multi_cpus=armv7,arm64 -c opt //tensorflow/lite/ios:TensorFlowLiteC_framework
```

### Relevant log output

```shell
INFO: Found 1 target...
ERROR: /Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.8.0_ios/tensorflow/lite/ios/BUILD:104:21: Bundling Preprocessed_TensorFlowLiteC_framework failed: (Exit 127): bundletool failed: error executing command 
  (cd /private/var/tmp/_bazel_andyueng/b359781934b2fbee0aeeaf947e072230/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool bazel-out/applebin_ios-ios_armv7-opt-ST-36ad1e8d6baf/bin/tensorflow/lite/ios/Preprocessed_TensorFlowLiteC_framework-intermediates/bundletool_control.json)
Execution platform: @local_execution_config_platform//:platform
env: python: No such file or directory
Target //tensorflow/lite/ios:TensorFlowLiteC_framework failed to build
INFO: Elapsed time: 111.590s, Critical Path: 17.23s
INFO: 2219 processes: 359 internal, 1860 local.
FAILED: Build did NOT complete successfully
```
</details>

**Comment by mohantym** [comment]
Hi @snowuyl ! Sorry for the late response! Did you try again after renaming python 3 to python as in  last [thread](https://github.com/tensorflow/tensorflow/issues/56114#issuecomment-1127201185). Thank you!

**Comment by snowuyl** [comment]
The following is log messages.
INFO: Found 1 target...
ERROR: /Users/andyueng/samba/workspace_TensorFlow2/tensorflow-2.8.0_ios/tensorflow/core/util/BUILD:379:24: Action tensorflow/core/util/version_info.cc failed: (Exit 72): bash failed: error executing command 
  (cd /private/var/tmp/_bazel_andyueng/b359781934b2fbee0aeeaf947e072230/execroot/org_tensorflow && \
  exec env - \
    PATH=/usr/local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/andyueng/mambaforge/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Geany.app/Contents/MacOS:/Users/andyueng/bin \
    PYTHON_BIN_PATH=/opt/homebrew/opt/python@3.9/bin/python3.9 \
    PYTHON_LIB_PATH=/opt/homebrew/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages \
    TF2_BEHAVIOR=1 \
  /bin/bash -c 'bazel-out/ios-arm64-min9.0-applebin_ios-ios_arm64-opt-ST-80976841b7ce/bin/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}' '' external/local_config_git/gen/spec.json external/local_config_git/gen/head external/local_config_git/gen/branch_ref bazel-out/ios-arm64-min9.0-applebin_ios-ios_arm64-opt-ST-1cd14ee91d04/bin/tensorflow/core/util/version_info.cc)
Execution platform: @local_execution_config_platform//:platform
python: error: Failed to locate 'python'.
xcode-select: Failed to locate 'python', requesting installation of command line developer tools.
Target //tensorflow/lite/ios:TensorFlowLiteC_framework failed to build
INFO: Elapsed time: 41.660s, Critical Path: 12.57s
INFO: 559 processes: 178 internal, 381 local.
FAILED: Build did NOT complete successfully
andyueng@jinkangdeMacBook-Air tensorflow-2.8.0_ios % ls -al /usr/local/bin/python 
lrwxr-xr-x  1 root  wheel  16  5 18 13:56 /usr/local/bin/python -> /usr/bin/python3

**Comment by snowuyl** [comment]
When will TensorFlow 2.9.0 release for macOS?

**Comment by sachinprasadhs** [comment]
> When will TensorFlow 2.9.0 release for macOS?

tensorflow-macos 2.9 has been released today, please check

**Comment by snowuyl** [comment]
% pip3 install tensorflow-macos==2.9.0
Successfully installed tensorflow-macos-2.9.0
% python3
Python 3.9.12 (main, May 8 2022, 17:57:49)
[Clang 13.1.6 (clang-1316.0.21.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

import tensorflow as tf
print(tf.version)
2.9.0
from tensorflow.keras import layers
