### ISSUE TITLE
problem with batch production

### ISSUE THREAD

**Issue by Jalil-Mahdizadeh** [tensorflow/tensorflow#56121]
Hi All,
Inspiring by the tutorial called “Text generation with an RNN” (https://www.tensorflow.org/text/tutorials/text_generation), I managed to train a model to generate new molecules in SMILES string format. It has been trained very well and I could generate new molecules either consecutively (one after another) and batch production. However, when I saved the trained model and loaded it again, the batch production fails and ends up with an error. could someone help please?

**Comment by tilakrayal** [comment]
Hello @Jalil-Mahdizadeh ,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you do so as it helps us to analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced] or if possible please share a colab gist with the issue reported.

**Comment by Jalil-Mahdizadeh** [comment]
Hi,
I just directly pressed the button "Run in Google Colab" from this page : **https://www.tensorflow.org/text/tutorials/text_generation** 

The steps that I followed:
1- I trained the model successfully
2- I was able to generate text with a single input using the trained model
3- I was able to generate text with a batched input using the trained model
4- I saved the one-step model successfully
5- I loaded the saved model successfully 
6- I was able to generate text with a single input using the loaded model
7- I **COULD NOT** generate text with a batched input using the loaded model

**Comment by Jalil-Mahdizadeh** [comment]
Here is the error I got:


ValueError                                Traceback (most recent call last)
[<ipython-input-46-53dd475862ad>](https://localhost:8080/#) in <module>()
      4 
      5 for n in range(1000):
----> 6   next_char, states = one_step_reloaded.generate_one_step(next_char, states=states)
      7   result.append(next_char)
      8 

1 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/function_deserialization.py](https://localhost:8080/#) in restored_function_body(*args, **kwargs)
    282           .format(index + 1, _pretty_format_positional(positional), keyword))
    283     raise ValueError(
--> 284         "Could not find matching concrete function to call loaded from the "
    285         f"SavedModel. Got:\n  {_pretty_format_positional(args)}\n  Keyword "
    286         f"arguments: {kwargs}\n\n Expected these arguments to match one of the "

ValueError: Could not find matching concrete function to call loaded from the SavedModel. Got:
  Positional arguments (2 total):
    * Tensor("inputs:0", shape=(2,), dtype=string)
    * None
  Keyword arguments: {}

 Expected these arguments to match one of the following 4 option(s):

Option 1:
  Positional arguments (2 total):
    * TensorSpec(shape=(1,), dtype=tf.string, name='inputs')
    * None
  Keyword arguments: {}

Option 2:
  Positional arguments (2 total):
    * TensorSpec(shape=(1,), dtype=tf.string, name='inputs')
    * TensorSpec(shape=(1, 1024), dtype=tf.float32, name='states')
  Keyword arguments: {}

Option 3:
  Positional arguments (2 total):
    * TensorSpec(shape=(5,), dtype=tf.string, name='inputs')
    * None
  Keyword arguments: {}

Option 4:
  Positional arguments (2 total):
    * TensorSpec(shape=(5,), dtype=tf.string, name='inputs')
    * TensorSpec(shape=(5, 1024), dtype=tf.float32, name='states')
  Keyword arguments: {}

**Comment by Jalil-Mahdizadeh** [comment]
Hi,
I just directly pressed the button "Run in Google Colab" from this page : https://www.tensorflow.org/text/tutorials/text_generation
The steps that I followed:
1- I trained the model successfully
2- I was able to generate text with a single input using the trained model
3- I was able to generate text with a batched input using the trained model
4- I saved the one-step model successfully
5- I loaded the saved model successfully
6- I was able to generate text with a single input using the loaded model
7- I COULD NOT generate text with a batched input using the loaded model


Here is the error I got:


ValueError Traceback (most recent call last)
in ()
4
5 for n in range(1000):
----> 6 next_char, states = one_step_reloaded.generate_one_step(next_char, states=states)
7 result.append(next_char)
8
1 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/saved_model/function_deserialization.py<https://localhost:8080/> in restored_function_body(*args, **kwargs)
282 .format(index + 1, _pretty_format_positional(positional), keyword))
283 raise ValueError(
--> 284 "Could not find matching concrete function to call loaded from the "
285 f"SavedModel. Got:\n {_pretty_format_positional(args)}\n Keyword "
286 f"arguments: {kwargs}\n\n Expected these arguments to match one of the "
ValueError: Could not find matching concrete function to call loaded from the SavedModel. Got:
Positional arguments (2 total):
* Tensor("inputs:0", shape=(2,), dtype=string)
* None
Keyword arguments: {}
Expected these arguments to match one of the following 4 option(s):
Option 1:
Positional arguments (2 total):
* TensorSpec(shape=(1,), dtype=tf.string, name='inputs')
* None
Keyword arguments: {}
Option 2:
Positional arguments (2 total):
* TensorSpec(shape=(1,), dtype=tf.string, name='inputs')
* TensorSpec(shape=(1, 1024), dtype=tf.float32, name='states')
Keyword arguments: {}
Option 3:
Positional arguments (2 total):
* TensorSpec(shape=(5,), dtype=tf.string, name='inputs')
* None
Keyword arguments: {}
Option 4:
Positional arguments (2 total):
* TensorSpec(shape=(5,), dtype=tf.string, name='inputs')
* TensorSpec(shape=(5, 1024), dtype=tf.float32, name='states')
Keyword arguments: {}

**Comment by tilakrayal** [comment]
@Jalil-Mahdizadeh ,
I was able to execute the given code without any issues. Please find the gist of it [here](https://colab.research.google.com/github/tensorflow/text/blob/master/docs/tutorials/text_generation.ipynb).

**Comment by Jalil-Mahdizadeh** [comment]
Hi 
It is still not working when I tried to batched generate text by "one_step_reloaded" [https://colab.research.google.com/gist/tilakrayal/1e3b0be6e3530f5bd0a50ce0e88da509/text_generation.ipynb](url)

**Comment by tilakrayal** [comment]
@gowthamkpr ,
I was able to reproduce the issue in tensorflow [v2.8](https://colab.research.google.com/gist/tilakrayal/1e3b0be6e3530f5bd0a50ce0e88da509/text_generation.ipynb), and in [v2.7](https://colab.research.google.com/gist/tilakrayal/8016913e447c36af168fbf85f98e8d5e/text_generation.ipynb) and nightly the code was failing with different error.Please find the gist.

**Comment by gowthamkpr** [comment]
@Jalil-Mahdizadeh Please take a look at this [issue](https://github.com/tensorflow/hub/issues/837) and try all the suggestions mentioned in it and let me know if it helps. 

Also take a look at the solutions provided [here](https://stackoverflow.com/questions/58575586/could-not-find-matching-function-to-call-loaded-from-the-savedmodel). Thanks!
