### ISSUE TITLE
Issue running Tensorflow

### ISSUE THREAD

**Issue by bullwinkle2059** [tensorflow/tensorflow#5612]
Please forgive me if I use incorrect language - I am very inexperienced utilizing command prompt commands and all similar activities and am trying my best.

I followed the instructions for setting up tensorflow and had it working this afternoon in the command prompt on my Windows machine. This evening I go to start practicing tensorflow and there are issues. When I follow the following directions:

1. Run the docker vm: docker-machine create vdocker -d virtualbox
2. In the command prompt window:
2.A. FOR /f "tokens=*" %i IN ('docker-machine env --shell cmd vdocker') DO %i
2.B.  docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow

everything works until 2.B. Then it talks about Jupyter notebook running at all IP addresses.

If i try using: docker run -it b.gcr.io/tensorflow/tensorflow:latest-devel

it says that it can't read the CA certificate for ...vdocker\\ ca.pem and it can't find the path specified.

Further google searching mentioned something about a bash_profile:

export DOCKER_HOST=tcp://192.168.99.100:2376
export DOCKER_MACHINE_NAME=default
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH=/Users/idanadar/.docker/machine/machines/default

but I have ZERO idea what they are referencing, what the above means, or what to do about it. I can code in python, but the ideas behind the commands to set up tensorflow are above my head. I am currently just googling things to put in the command prompt hoping it will work and I can start practicing tensorflow. Could anyone please provide me very specific instructions for what to do in the command prompt or the Docker QuickStart Terminal so I can resolve this issue? I appreciate your time very much. Sorry for asking such a basic question.

**Comment by girving** [comment]
Basic questions are good, but are better suited to StackOverflow, since then future users will more easily find the answers.  Can you re-ask your question there?
