### ISSUE TITLE
TF 2.9 - CombinedNonMaxSuppression conversion to TFLite not working anymore

### ISSUE THREAD

**Issue by rovinellimarco** [tensorflow/tensorflow#56133]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04.4 LTS

### Python version

3.9

### CUDA/cuDNN version

11.2/8.1

### Current Behaviour?

```shell
In tensorflow 2.8 the provided code didn't raise any error. In tensorflow 2.9 ERROR_NEEDS_FLEX_OPS is raised.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf


class NMSLayer(tf.keras.layers.Layer):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def call(self, inputs, **kwargs):
        boxes, scores = inputs[0], inputs[1]
        boxes, scores, classes, valid_detections = tf.image.combined_non_max_suppression(
            boxes=boxes,
            scores=scores,
            max_output_size_per_class=8,
            max_total_size=8,
            iou_threshold=0.5,
            score_threshold=0.5,
            pad_per_class=False,
            clip_boxes=True,
            name=f'{self.name}/NMS_op'
        )

        return boxes, scores, tf.cast(classes, dtype=tf.int32), valid_detections


def representative_dataset_generator():
    for batch in range(10):
        yield [tf.zeros((1, 10, 1, 4)), tf.zeros((1, 10, 5))]


num_boxes = 10
num_classes = 5

boxes = tf.keras.Input((num_boxes, 1, 4), batch_size=1)
scores = tf.keras.Input((num_boxes, num_classes))

model = tf.keras.Model([boxes, scores], NMSLayer()([boxes, scores]))
# test that the model can run
model(next(representative_dataset_generator()))

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.SELECT_TF_OPS, tf.lite.OpsSet.TFLITE_BUILTINS_INT8
]
converter.representative_dataset = representative_dataset_generator
converter.target_spec.supported_types = [tf.int8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
tflite_model = converter.convert()
```

### Relevant log output

```shell
Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: failed while converting: 'main': 
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: CombinedNonMaxSuppression
Details:
	tf.CombinedNonMaxSuppression(tensor<1x10x1x4xf32>, tensor<?x10x5xf32>, tensor<i32>, tensor<i32>, tensor<f32>, tensor<f32>) -> (tensor<1x8x4xf32>, tensor<1x8xf32>, tensor<1x8xf32>, tensor<1xi32>) : {clip_boxes = true, device = "", pad_per_class = false}
```
</details>

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue ? It is replicating in [2.9](https://colab.sandbox.google.com/gist/mohantym/2757c562c1a3d4df0242ce57a2b8b1ea/git_56133.ipynb) and [nightly](https://colab.sandbox.google.com/gist/mohantym/c983634b29a5501c42c3b06d5b0fda56/git_56133.ipynb#scrollTo=GThUJmy-7VJz). Thank you!

**Comment by rovinellimarco** [comment]
Any updates on this?

**Comment by mohantym** [comment]
Hi @rovinellimarco !
I was able to convert the model to a Tflite model  by skipping this line.

`#converter.target_spec.supported_types = [tf.int8]
`
Attached resolved [gist](https://colab.research.google.com/gist/mohantym/cb685765c00c3a14e901ec8a1263f3c0/git_56133.ipynb#scrollTo=r9H5DnOT7TPA) in nightly for reference.


Thank you!

**Comment by rovinellimarco** [comment]
As far as I know, that line is needed to have fully integer models so it is not an option to remove it.

**Comment by mohantym** [comment]
Ok @rovinellimarco !

Actually original select ops issue was getting resolved with following syntax (skipping `#converter.target_spec.supported_types = [tf.int8]`
) before lite conversion and asking a 4D box tensor when not skipped.
```
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.SELECT_TF_OPS, tf.lite.OpsSet.TFLITE_BUILTINS_INT8
]
converter.allow_custom_ops = True
converter.experimental_new_converter = True
```

Inference input and output type are not int8 types though . But they are int32 type, will that work for your use case.
Thank you!

**Comment by rovinellimarco** [comment]
It seems like the generated TFLite matches the result that I was getting on TF 2.8 so yes this solves the problem, thank you!
