### ISSUE TITLE
How to reduce CPU usage of TensorFlowLite

### ISSUE THREAD

**Issue by Aip-K-O** [tensorflow/tensorflow#56148]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

tflite 2.6.1

### Custom Code

No

### OS Platform and Distribution

yocto Linux

### Bazel version

3.7.1

### Current Behaviour?

```shell
Hello, I have a question about how to reduce CPU usage of TensorFlowLite.

I have 100% CPU utilization when running on ARM.
I want to lower it to about 50% because other processes will not work.
Is there a solution to this problem?
It is already running on 1 core, so the method of reducing the number of cores used will not solve the problem.
```

### Standalone code to reproduce the issue

```shell
-
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @Aip-K-O ! Your device has [XNNPack ](https://towardsdatascience.com/accelerating-tensorflow-lite-with-xnnpack-ece7dc8726d0)support , You can use it and [optimize ](https://www.tensorflow.org/lite/performance/measurement) the performance of your TFlite model. Attached relevant thread for reference. Thank you!

**Comment by mohantym** [comment]
@Aip-K-O ! You can also use multiple threads  along XNNPack . Attached relevant [thread ](https://www.intel.com/content/www/us/en/developer/articles/technical/maximize-tensorflow-performance-on-cpu-considerations-and-recommendations-for-inference.html)for reference. Please [benchmark ](https://www.tensorflow.org/lite/performance/measurement)the performance of lite model and let us know once. Thank you!

`interpreter = tf.lite.Interpreter(model_path="q_model.tflite", num_threads=4)
`or 

using 
`tf.config.threading.set_intra_op_parallelism_threads(4)
`

**Comment by Aip-K-O** [comment]
Thank you mohantym.

I've tried multiple threads, though I haven't used XNNPack yet.

When I set num_threads to 2, the processing time about doubled.
When I set num_threads to 4, the processing time increased by about 4 times
CPU utilization remained 100% in both cases.
I expect that the overhead of increasing the number of threads caused the slowdown.
Since the target CPU core is one.

**Comment by mohantym** [comment]
@Aip-K-O ! Let us know the results after XNN pack usage. Thank you!

**Comment by Aip-K-O** [comment]
Thanks mohantym.

I tried the XNN pack, but that didn't change the result.

I built it with the following options
```
bazel build -c opt \
    --define tflite_with_xnnpack=true \
```
There were no errors, but it may not have built properly.
However, I want to leave the XNN pack thing as is for once.

I think I am failing to communicate what I want to do.
Let me explain again what I want to do.

The computation will run forever, over and over again.
I want to cut the CPU usage in half, even if it takes twice as long per computation.

If the CPU had two cores, I could reduce the number of threads used from two to one, but
I can't do that because I have one CPU.

For example, I want to put in a reasonable amount of idle time during computation.
But I don't know how to do that.

Is there a way to do this?

**Comment by mohantym** [comment]
@Aip-K-O ! Thanks for the update! @sachinprasadhs ! Could you please look at this issue?

**Comment by Aip-K-O** [comment]
Hi sachinprasadhs. thank you.

It is not RAM usage that I want to reduce.
I want to reduce CPU usage.
I want TensorFlowLite's matrix calculation to run slowly and use the free resources for other processing, for example, audio playback.
How can I allow a reasonable amount of idle time for TensorFlowLite's matrix calculations?

Since the target CPU is a single core, reducing the number of threads used is not a solution.

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
