### ISSUE TITLE
[TFLite] On-device training with GPU delegate

### ISSUE THREAD

**Issue by anotheruserofgithub** [tensorflow/tensorflow#56151]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

2.10.0-dev20220427

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04

### Mobile device

Linux Ubuntu 18.04

### Python version

3.10

### Bazel version

5.1.1

### GCC/Compiler version

7.5.0

### CUDA/cuDNN version

CUDA 11.6

### GPU model and memory

NVIDIA GeForce GTX 1650 4BG

### Current Behaviour?

Would it be possible to perform on-device training with TFLite experimental C API using the GPU delegate for inference?
Following [this tutorial](https://www.tensorflow.org/lite/examples/on_device_training/overview#build_a_model_for_on-device_training), after converting the model with the four signatures `infer`, `train`, `save` and `restore`, the interpreter can only be created without any delegates.

When putting only the `infer` signature in the model without the softmax operation, however, it is possible to run inference on the GPU either through this signature or the subgraph 0, and the results are identical as expected.
When adding other operations that require the Flex delegate, it becomes impossible to use the GPU delegate.

Consider for instance putting only the `train` signature in the model, then delegates other than Flex cannot be used, while one would expect the inference part `prediction = model(x)` to be able to run on the GPU and the gradient part to run on the CPU (maybe the loss could also be computed on the GPU, I am not sure of what operators exactly are not supported by the GPU delegate).
Indeed, if the inference can normally be handled by the GPU delegate (e.g. when there is no signatures in the model), then why is it impossible to use it in a signature that contains both an inference part and something else?

It would very great to always be able to run the inference on the GPU since it highly reduces the computation time.
What, do you think, would need to be changed in the code for achieving that?
I personally tried some modifications but was not able to make it work.

Some references indicating that it is already supposed to work:
* [Select Ops](https://www.tensorflow.org/lite/guide/ops_select#updates): Compatibility with hardware accelerated delegates has improved in version 2.4.
* [Issue 42190](https://github.com/tensorflow/tensorflow/issues/42190#issuecomment-697004884): Flex + GPU combination is now working at tf-nightly version if the graph has only static shapes.

The breaking change seems to be the structure with signatures.

### Standalone code to reproduce the issue

Compile the C API with both Flex and GPU delegates using this compilation rule added in `//tensorflow/lite/c/BUILD` (CUDA enabled in `./configure`):
```
tflite_cc_shared_object(
    name = "tensorflowlite_c_gpu_flex",
    per_os_targets = True,
    deps = [
        "//tensorflow/lite/c:c_api_experimental",
        "//tensorflow/lite/delegates/gpu:delegate",
        "//tensorflow/lite/delegates/flex:delegate_symbol",
    ],
)
```

with this bazel command:
```
bazel --output_user_root=build build -c opt --copt -Os --copt -DTFLITE_GPU_BINARY_RELEASE --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 --linkopt -lEGL --linkopt -lGLESv2 --linkopt -s --strip always //tensorflow/lite/c:tensorflowlite_c_gpu_flex --config monolithic --config linux
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @anotheruserofgithub! Have you tried using delegates with [interpreter options ](https://www.tensorflow.org/lite/performance/gpu#tensorflow_lite_interpreter) yet? Thank you!

**Comment by anotheruserofgithub** [comment]
Hi @mohantym, thank you for your reply.

I am actually not using the Java API but the C experimental API on Flutter through the Dart FFI, and running on Ubuntu.
Indeed I initialize delegates with interpreter options using the C API.

What I thought also was that maybe it could work if instead of using interpreter options, I would first create the interpreter and then add the GPU delegate through [`TfLiteInterpreterModifyGraphWithDelegate()`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/c_api_experimental.h#L213), but anyway I think this is what is eventually called internally when creating delegates with interpreter options.

**Comment by mohantym** [comment]
Ok @anotheruserofgithub ! If it is resolved , Could we move this issue to closed status then.

**Comment by mohantym** [comment]
Ok @anotheruserofgithub ! Sorry for the inconvenience. @gowthamkpr ! Could you please look at this issue.

**Comment by anotheruserofgithub** [comment]
Hi @gowthamkpr, would you mind giving your feedback on how we could run signatures (inference part of the training) on the GPU?

**Comment by haozha111** [comment]
GPU support for on-device training is on our long-term roadmap. @karimnosseir do you know what's the status of running a specific signature (e.g. `infer`) on GPU?

**Comment by anotheruserofgithub** [comment]
> GPU support for on-device training is on our long-term roadmap.

Good to know! Thank you for the answer.

> @karimnosseir do you know what's the status of running a specific signature (e.g. `infer`) on GPU?

@karimnosseir I would be grateful if you would comment on that.

**Comment by BenjaminWegener** [comment]
i have forked and patched the gpu delgate with support for python:
https://github.com/BenjaminWegener/tensorflow_lite_gpu_python
inference on arm64 and x64 is no problem with both opencl and opengl. but if i start training using the described way, i get an unspecified runtime error at
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-23-b2c32744c122> in <module>
      9 #delegate = tflite.load_delegate('DELEGATE')
     10 delegate = tflite.load_delegate('./libtensorflowlite_opengl_delegate_arm64_v1.so')
---> 11 generator_lite = tflite.Interpreter(model_content=tflite_model, experimental_delegates=[delegate])
     12 generator_lite.allocate_tensors()
     13 generator_lite_infer = generator_lite.get_signature_runner("infer")

~/.local/lib/python3.9/site-packages/tflite_runtime/interpreter.py in __init__(self, model_path, model_content, experimental_delegates, num_threads, experimental_op_resolver_type, experimental_preserve_all_tensors)
    493       self._delegates = experimental_delegates
    494       for delegate in self._delegates:
--> 495         self._interpreter.ModifyGraphWithDelegate(
    496             delegate._get_native_delegate_pointer())  # pylint: disable=protected-access
    497     self._signature_defs = self.get_signature_list()

RuntimeError: ```

**Comment by karimnosseir** [comment]
Sorry for the late reply. We have it in the plan to support it, but not yet ready.

**Comment by anotheruserofgithub** [comment]
> We have it in the plan to support it, but not yet ready.

Understood, thanks for the answer!

**Comment by BenjaminWegener** [comment]
Any update?

**Comment by anotheruserofgithub** [comment]
@haozha111 @karimnosseir Would you now have a more precise schedule for supporting this feature?

**Comment by haozha111** [comment]
Hi, we have a plan to support this feature in 2023. This is definitely on our road map. Thanks for the patience!

**Comment by haozha111** [comment]
@miaout17 FYI.

**Comment by ahlzouao** [comment]
Hello @haozha111 , 
Do you have any news on the support of this feature ?
Do you plan on supporting only the inference part on the GPU delegates or it will be covering also the training using GPU and other external delegates (For example NPU and EdgeTPU) ?

**Comment by haozha111** [comment]
Hi @ahlzouao ,
We are working on improving GPU capability generally but not prioritizing for on-device training at this moment. Thank you for your interest!

**Comment by martinkorelic** [comment]
@haozha111 
Is there any news on GPU based training being enabled for on device learning for custom models? Not only for inference, but for training TFLite models as well. Or is there any other way this could be implemented?

**Comment by haozha111** [comment]
hi, we don't have plans yet to enable GPU on-device training in TF Lite. Lu (added to the assignee) may offer some additional context. The GPU delegate is also being refreshed so training support may not be supported as of now.
