### ISSUE TITLE
TFLite forcing to run on CPU

### ISSUE THREAD

**Issue by Sara980710** [tensorflow/tensorflow#56157]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

No

### Current Behaviour?

Hello! 
Can I somehow force the TFLite interpreter to run on my CPU instead of GPU? Now it is running on GPU automatically. 

Another question is also if I can use TFLite runtime on GPU? It automatically uses the CPU when I start right now even if it is exactly the same code and computer as when I use TensorFlow complete library. 

Best regards
Sara Larsson

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
interpreter = tf.lite.Interpreter(model_path)

import tflite_runtime.interpreter as tflite
interpreter = tflite.Interpreter(model_path)
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @Sara980710 ! Sorry for the late response.  You can disable GPU usage through below code. Thank you!

```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
gpu_available = tf.test.is_gpu_available() //cross check to see any GPU usage
print(gpu_available)
```

**Comment by Sara980710** [comment]
Thank you! 
How do I turn on GPU for [tensorflow lite runtime](https://www.tensorflow.org/lite/guide/python)? 
`import tflite_runtime.interpreter as tflite
interpreter = tflite.Interpreter(model_path)`

**Comment by Sara980710** [comment]
When I test the code you suggested, it shows that it does not have a GPU even if I do not set os.environ["CUDA_VISIBLE_DEVICES"] = "-1",  but it still is as fast as when I run with C++ GPU delegate. Are you sure that it works with  AMD GPU:s as well? 

When i use c++:
-GPU: 2 min
-CPU: 5 min
When I use python:
- 2 min (should be using GPU right? )

**Comment by mohantym** [comment]
@Sara980710 ! GPU time might be 2 min as CPU time is intended higher (C++ implementation has seen faster processing time compared to Python implementation earlier). Could we move this to closed status then.  Thank you!

**Comment by mohantym** [comment]
@Sara980710 ! GPU time might be 2 min as CPU time is intended higher (C++ implementation has seen faster processing time compared to Python implementation earlier). Could we move this to closed status then. Thank you!

**Comment by Sara980710** [comment]
I want to be able to measure a comparison between the following:
-C++ tensorflow GPU
-C++ tensorflow CPU
-Python tensorflow GPU
-Python tensorflow CPU
-Python tensorflow lite runtime GPU
-Python tensorflow lite runtime CPU

The C++ code I have already written to be able to measure both CPU and GPU, but I am wondering how to do it in Python (both libraries).

**Comment by mohantym** [comment]
@Sara980710 ! You can use[ tf.device](https://www.tensorflow.org/api_docs/python/tf/device) to force the processes to run either in GPU or CPU? Thank you!

**Comment by Sara980710** [comment]
How do i do it with tflite runtime since i do "import tflite_runtime.interpreter as tflite"

**Comment by Sara980710** [comment]
It seems like no matter what I do as settings, it still performs the same in time. 
```
if opt.gpuoff:
        tf.device("/device:CPU:0")
        print("using CPU")
    else:
        tf.device("/GPU:0")
        print("using GPU")
```

It did now however print out " 2022-05-20 12:33:10.555126: I tensorflow/core/common_runtime/process_util.cc:146]   Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance" when i added the device settings. But when i set inter_op_parallelism_threads to 1 it did still measure the same time.

**Comment by mohantym** [comment]
Ok @Sara980710 ! Sorry for the inconvenience . @sachinprasadhs ! Could you please look at this issue? Thank you!

**Comment by sachinprasadhs** [comment]
TFLite will use CPU by default on interpreter, to make use of GPU you can use it on your hardware accelerators  Android or IOS device, for more details check the document [here](https://www.tensorflow.org/lite/performance/delegates). Thanks!

**Comment by Sara980710** [comment]
I have checked the links before, I am however using a satellite computer with AMD64 architecture and ubuntu, not android or ios. For C++, I have managed to get the GPU to work, but for Python I cannot find a way to choose a device.

**Comment by impjdi** [comment]
Unassigned myself, because I'm not familiar with the Python code path =/

**Comment by mohantym** [comment]
Hi @Sara980710 !
In Python, You can force the CPU usage through [tf.device](https://github.com/tensorflow/tensorflow/issues/56157#issuecomment-1132833571) or by disabling the cuda variable through os.

[Ref](https://datascience.stackexchange.com/a/58846).

Can you mark it as duplicate to #56148 and comment there  if it is still not resolved .

Thank you!
