### ISSUE TITLE
cufft plan fails with tf.signal.fft2d

### ISSUE THREAD

**Issue by kt-kbr** [tensorflow/tensorflow#56159]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.1.0 gpu_py37h7db9008_0

### Custom Code

Yes

### OS Platform and Distribution

Windows

### Python version

3.7

### CUDA/cuDNN version

cudatoolkit=10.1.243 cudnn=7.6.5

### GPU model and memory

NVIDIA Quatro RTX 8000 48GB

### Current Behaviour?

```shell
I'm trying to take the 2D FFT of a float32 tensor of shape (100000, 1, 128, 128)

I've tried several suggested solutions on related issues; enabling GPU memory growth, and configuring the tf1 Session

```

### Standalone code to reproduce the issue

```shell
x = tf.random.normal((100000, 1, 128, 128))
out = tf.signal.fft2d(tf.cast(x, tf.complex64))
```

### Relevant log output

```shell
2022-05-18 17:49:40.628964: F tensorflow/stream_executor/cuda/cuda_fft.cc:435] failed to initialize batched cufft plan with customized allocator: 

Process finished with exit code -1073740791 (0xC0000409)
```
</details>

**Comment by sushreebarsa** [comment]
@kt-kbr We see that you are using an older version of TF(2.1.0) which is not actively supported.Please try to upgrade to the latest TF version(2.9.0) and let us know the outcome.
Thank you!

**Comment by kt-kbr** [comment]
My library compatibilities require me use 2.1

**Comment by sushreebarsa** [comment]
@kt-kbr Thank you for the update!
TF v2.1 does not really contain all the changes to prevent code using invalid shapes from crashing the interpreter via CHECK-failures.Its unlikely for TF 2.1 version to receive any bug fixes except when we have security patches. We recommend you to use TF v2.4 or later versions as older versions are not actively supported.
Thank you!
