### ISSUE TITLE
Image name supported by generate_tf_record.py script

### ISSUE THREAD

**Issue by Petros626** [tensorflow/tensorflow#56164]
Hello,

There are now many scripts on the Internet that can be used to create TFRecord files. However, I think I have read from time to time that certain names such as `image_001.jpg `or` image001.jpg` are more likely to lead to errors than `001.jpg`. I have a large data set and want to get everything right when I take the picture. 

So I wonder whether it generally doesn't matter as long as the label files (XML files) are correct, i.e. that the image endings (.jpg or .png) in the CSV files are correct everywhere?

Many thanks for clarifying this mystery

**Comment by sushreebarsa** [comment]
@Petros626 Could you please have a look at this similar SO [thread](https://stackoverflow.com/questions/52870674/how-to-fix-missing-files-or-folder-error-file-generate-tfrecord-py-line-110) to know more on the label files.  This is not a bug or feature request, for any further queries you may open this issue in TF discussion [forum ](https://discuss.tensorflow.org/)as there is a larger community there to get you the right help.
Thank you!

**Comment by Petros626** [comment]
> @Petros626 Could you please have a look at this similar SO [thread](https://stackoverflow.com/questions/52870674/how-to-fix-missing-files-or-folder-error-file-generate-tfrecord-py-line-110) to know more on the label files. This is not a bug or feature request, for any further queries you may open this issue in TF discussion [forum ](https://discuss.tensorflow.org/)as there is a larger community there to get you the right help. Thank you!

Thank you I will take a look and post it in the TF discussion forum

**Comment by sushreebarsa** [comment]
@Petros626 Could you please move this issue to closed status if you have already posted this issue on TF Forum.
Thank you!

**Comment by Petros626** [comment]
@sushreebarsa I will delete it there, the support isn't good enough. I will better let it here ;)

**Comment by gadagashwini** [comment]
Hi @Petros626, Use `tf.io.decode_image()`, which Detects whether an image is a BMP, GIF, JPEG, or PNG, and performs the appropriate operation to convert the input bytes string into a Tensor of type dtype. To convert to `tf.data` use  `tf.data.Dataset.from_tensor_slices`.Finally, write all the features into Tfrecord format using `tf.data.experimental.TFRecordWriter()`. Thank you!

**Comment by Petros626** [comment]
> Hi @Petros626, Use `tf.io.decode_image()`, which Detects whether an image is a BMP, GIF, JPEG, or PNG, and performs the appropriate operation to convert the input bytes string into a Tensor of type dtype. To convert to `tf.data` use `tf.data.Dataset.from_tensor_slices`.Finally, write all the features into Tfrecord format using `tf.data.experimental.TFRecordWriter()`. Thank you!

Thanks for answering. That's okay I guess.
