### ISSUE TITLE
Compile without JAVA

### ISSUE THREAD

**Issue by bulvara** [tensorflow/tensorflow#56168]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.9.0

### Custom Code

No

### OS Platform and Distribution

ArchLinux

### Bazel version

5.1.1

### GCC/Compiler version

12.1

### Current Behaviour?

```shell
When there is any trace of a JDK present on your system but you _don't need any Java support_ or bindings, TensorFlow nevertheless refuses to compile and complains:
_FATAL: Could not find system javabase. Ensure JAVA_HOME is set, or javac is on your PATH._
```

### Standalone code to reproduce the issue

```shell
https://github.com/archlinux/svntogit-community/blob/packages/tensorflow/trunk/PKGBUILD :

  bazel build \
    //tensorflow:libtensorflow.so \
    //tensorflow:libtensorflow_cc.so \
    //tensorflow:install_headers \
    //tensorflow/tools/pip_package:build_pip_package
  bazel-bin/tensorflow/tools/pip_package/build_pip_package "${srcdir}"/tmp
```

### Relevant log output

_No response_</details>

**Comment by gadagashwini** [comment]
Hi @bulvara,
Could you share the complete error log to investigate the root cause of this error. Thank you!
