### ISSUE TITLE
In Pose detection when I use front camera it display opposite mirror how to resolve it? 

### ISSUE THREAD

**Issue by IBSApple** [tensorflow/tensorflow#56178]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML', 'Metal']

### Custom Code

No

### OS Platform and Distribution

MacOS

### Mobile device

iPhone X

### Current Behaviour?

```shell
In Pose detection when I use front camera it display opposite mirror how to resolve it? also camera resolution also need to clear.
```

### Standalone code to reproduce the issue

```shell
Must display proper mirror frame & resolution when front camera start ie. iPhone default camera app front camera mirror & resolution.
```

### Relevant log output

_No response_</details>

**Comment by IBSApple** [comment]
![IMG_6747](https://user-images.githubusercontent.com/71369657/169449994-54e79f1c-2a0a-4826-bc38-77e4b64348d5.PNG)

Display wrong mirror & resolution issue how to fix?

**Comment by IBSApple** [comment]
![IMG_6745](https://user-images.githubusercontent.com/71369657/169450141-a325d48b-cffc-4633-8172-4928b0b0da5a.PNG)
This is exactly  I want like this.

**Comment by IBSApple** [comment]
??

**Comment by mohantym** [comment]
Hi @IBSApple ! Thanks for reporting this issue.  @sachinprasadhs ! Could you please look at this issue?

**Comment by IBSApple** [comment]
Any update?

**Comment by IBSApple** [comment]
??

**Comment by khanhlvg** [comment]
@st-duymai Can you answer this question?

**Comment by tuan4192** [comment]
@IBSApple 
You can flip mirror the image before it is send in the model when using the front camera.


```
     var newPixelBuffer: CVPixelBuffer!
      if self.cameraPosition == .front {
         newPixelBuffer = self.rotate(pixelBuffer)
      } else {
        newPixelBuffer = pixelBuffer
      }
```
Rotate function:

  ```
private func rotate(_ pixelBuffer: CVPixelBuffer) -> CVPixelBuffer? {
    var newPixelBuffer: CVPixelBuffer?
    let error = CVPixelBufferCreate(kCFAllocatorDefault,
                                    CVPixelBufferGetWidth(pixelBuffer),
                                    CVPixelBufferGetHeight(pixelBuffer),
                                    CVPixelBufferGetPixelFormatType(pixelBuffer),
                                    nil,
                                    &newPixelBuffer)
    guard error == kCVReturnSuccess else {
      return nil
    }
    let ciImage = CIImage(cvPixelBuffer: pixelBuffer).oriented(.upMirrored)
    let context = CIContext(options: nil)
    context.render(ciImage, to: newPixelBuffer!)
    return newPixelBuffer
  }
```

**Comment by DemoLV** [comment]
In LegacyCameraConnectionFragment.java under camera.setDisplayOrientation(90);
I put
Matrix matrix = new Matrix();               
matrix.setScale(-1, 1);                       
matrix.postTranslate(textureView.getWidth(), 0);
textureView.setTransform(matrix);

and
if (ci.facing == CameraInfo.CAMERA_FACING_FRONT) 

CameraActivity.java
if (facing != null && facing == CameraCharacteristics.LENS_FACING_BACK) 

The mirror effect is gone but it does not detect the objects as I need and whenever I change everything to back camera everything works fine. 
What could be the problem ?

**Comment by IBSApple** [comment]
Thank you so much, It's worked...

**Comment by DemoLV** [comment]
> Thank you so much, It's worked...

No problem ! 
But with the front camera it detects everything as it should ?
Because on object detection it does not detect precisely on my occasion

**Comment by IBSApple** [comment]
How to resolve this camera issue  in android (Kotlin) app?

**Comment by IBSApple** [comment]
????

**Comment by IBSApple** [comment]
??

**Comment by mohantym** [comment]
Hi @IBSApple !
Sorry for the inconvenience. It seems this issue was resolved in [Java side](https://github.com/tensorflow/tensorflow/issues/56178#issuecomment-1137708472) and you were looking for a solution in Kotlin side.

Latest Android Studio Version has this feature on Auto-conversion from Java to Kotlin .
Attached [sample usage](https://www.geeksforgeeks.org/how-to-convert-java-code-to-kotlin-code-in-android-studio/) on conversion from Java to kotlin for reference.

Thank you!
