### ISSUE TITLE
Xcode 13.3.1 build simple project failed on MacBook Air M1

### ISSUE THREAD

**Issue by snowuyl** [tensorflow/tensorflow#56176]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

No

### OS Platform and Distribution

macOS 

### Mobile device

iPhone 12

### Python version

 3.9.12

### Bazel version

5.0.0

### GCC/Compiler version

Apple clang version 13.1.6

### Current Behaviour?

```shell
Xcode 13.3.1 build simple project failed on MacBook Air M1.
```

### Standalone code to reproduce the issue

```shell
git clone https://github.com/tensorflow/tensorflow tensorflow-2.9.0_ios
git checkout r2.9
cd tensorflow-2.9.0_ios/tensorflow/lite/examples/iOS/simple
pod install
open simple.xcworkspace
open simple.xcodeproj
Using Xcode to build simple project. But the following error occurred.
Use of undeclared identifier 'RegisterSelectedOps'
```

### Relevant log output

```shell
Use of undeclared identifier 'RegisterSelectedOps'
```
</details>

**Comment by sachinprasadhs** [comment]
The main issue exists with the Apple M1, will take a look into it. Thanks for reporting the issue.

**Comment by sachinprasadhs** [comment]
Hi, Apologies for the delayed response. Have you tried all the steps mentioned here https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/ios/README.md.

**Comment by snowuyl** [comment]
% cd examples/lite/examples/image_classification/ios 
 % pod install
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.
open ImageClassification.xcodeproj

But Xcode build error with "No such module TensorFlowLite"

**Comment by sachinprasadhs** [comment]
You should be having directory named` ImageClassification.xcworkspace` and then open it in Xcode using `open ImageClassification.xcworkspace`

**Comment by snowuyl** [comment]
Thanks for your suggestion. Xcode can build sucsscussfully with "open ImageClassification.xcworkspace" command.

**Comment by PayalUmraliya** [comment]
<img width="457" alt="Screenshot 2022-07-27 at 5 14 42 PM" src="https://user-images.githubusercontent.com/14552882/181239038-d95eff4e-be92-4021-9447-9e688efa3484.png">
<img width="779" alt="Screenshot 2022-07-27 at 5 14 54 PM" src="https://user-images.githubusercontent.com/14552882/181239058-f630c89d-ac1e-4000-ad67-422fd76e2e1b.png">

No such module 'TensorFlowLiteCCoreML' getting this error. 
xcode Version 13.4.1 (13F100)
Tried pod install and opening .xcworkspace only. 

Please note that i am getting this error only when i archive the build. Any help would be appreciated!

Thanks,
Payal U.
