### ISSUE TITLE
Xcode 13.3.1 build digit_classifier iOS TensorFlow Lite example failed

### ISSUE THREAD

**Issue by snowuyl** [tensorflow/tensorflow#56174]
git clone https://github.com/tensorflow/examples
cd examples/lite/examples/digit_classifier/iOS
pod install
open DigitClassifier.xcodeproj
Using Xcode to build digit_classifier project. But the following error occurred.
No such module 'Sketch'

**Comment by sachinprasadhs** [comment]
Could you please close this issue since the issue is similar to the issue which you have reported here https://github.com/tensorflow/tensorflow/issues/56176 and it's easier to track and escalate issue, since the underlying problem seems to be same for both the issue. Thanks!

**Comment by snowuyl** [comment]
Does building failed has been solved?

**Comment by snowuyl** [comment]
Does building failed has been solved?

**Comment by snowuyl** [comment]
Xcode can build successfully with "open DigitClassifier.xcworkspace" command.
