### ISSUE TITLE
`tf.image.resize` different result when inside a `tf.function`

### ISSUE THREAD

**Issue by fredo838** [tensorflow/tensorflow#56181]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.9.0-rc2-42-g8a20d54a3c1 2.9.0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8

### Current Behaviour?

```shell
When you put a `tf.image.resize` op inside a `tf.function` whilst using `tf.RaggedTensor`s, the result changes.
```

### Standalone code to reproduce the issue

```python

import numpy as np
import tensorflow as tf
np.random.seed(0)
batch1 = tf.cast(tf.ragged.constant([255*np.random.uniform(size=(2000, 2000))]), tf.uint8)
batch1 = tf.expand_dims(batch1, axis=-1)
batch1 = tf.concat([batch1, batch1, batch1], axis=-1)

sign = tf.RaggedTensorSpec((1, None, None, 3), tf.uint8, 2, tf.int64)

@tf.function(input_signature=(sign,))
def resize_tf(images):
  return tf.image.resize(images, (50, 50)) / 255.
  
def resize_non_tf(images):
  return tf.image.resize(images, (50, 50)) / 255.
  
print(tf.reduce_mean(resize_tf(batch1)))
print(tf.reduce_mean(resize_non_tf(batch1)))

and then run `python3 test.py`
```

### Relevant log output

```shell
tf.Tensor(0.49723607, shape=(), dtype=float32)
tf.Tensor(0.497236, shape=(), dtype=float32)
```
</details>

**Comment by fredo838** [comment]
I tested it with tensorflow `2.10` as well (`tf-nightly`).

**Comment by bhack** [comment]
Can you check if It Is the same case as:
https://github.com/tensorflow/tensorflow/issues/55814#issuecomment-1115034411

/cc @mdanatg

**Comment by bhack** [comment]
E.g:
```python 
options =  tf.config.optimizer.get_experimental_options()
options['disable_meta_optimizer']=True
tf.config.optimizer.set_experimental_options(options)
```

Then, you could play to turn optimizations if you want to identify the root cause of the numerical difference. 
The list is available at:
https://github.com/tensorflow/tensorflow/blob/v2.9.0/tensorflow/python/framework/config.py#L203-L241

**Comment by bhack** [comment]
P.s. for you specific case the root cause of the numerical difference was the constant folding:
```python
options =  tf.config.optimizer.get_experimental_options()
options['constant_folding']=False
tf.config.optimizer.set_experimental_options(options)
```

See more at https://www.tensorflow.org/guide/graph_optimization

**Comment by fredo838** [comment]
This thread is indeed strongly related. The solution is, as per @mdanatg  https://github.com/tensorflow/tensorflow/issues/55814#issuecomment-1115152309 to focus on develeping with `tf.function´, but my use case is porting a model developed in eager mode to graph mode, so I need a graph mode that produces results like eager mode. Does this option: ``` disable_meta_optimizer: Disable the entire meta optimizer. ``` mean "disable all optimization passes"?

**Comment by mdanatg** [comment]
A note that might be less obvious - with the arithmetic simplifications made by the optimizer, the results should be closer to the real mathematical results.

So in practice, I would recommend using tf.function with the arithmetic optimizer enabled and noting that eager's results are slightly different (and likely less accurate), rather than disabling it the optimizer to bring the results in line.

**Comment by bhack** [comment]
> So in practice, I would recommend using tf.function with the arithmetic optimizer enabled and noting that eager's results are slightly different (and likely less accurate), rather than disabling it the optimizer to bring the results in line.

Yes thanks I think that it is something important to repeat as many things that it is just an approximation to make things faster (fooled by the `optimizer` name). 

But also this is the 2nd time in a week and I have seen many of these in my sparse triage activity over the years. 
So probably it is time to find a place to better better promote this knowledge.

If an users/developer have some doubt I think it could be ok to test:
```python
options =  tf.config.optimizer.get_experimental_options()
options['disable_meta_optimizer']=True
tf.config.optimizer.set_experimental_options(options)
```
I don't know if we could have numerical bugs in these optimizations but eventually It would be very hard that we have this kind of report by users.
