### ISSUE TITLE
tf.keras.datasets.cifar10.load_data(path='cifar-10-python.tar.gz')

### ISSUE THREAD

**Issue by BA7LYA** [tensorflow/tensorflow#56182]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

2.8.0

### Custom Code

No

### OS Platform and Distribution

Windows 10

### Python version

3.10

### Current Behaviour?

```shell
The tf.keras.datasets.mnist.load_data(path='/user/.keras/datasets/mnist.npz') works fine, but the tf.keras.datasets.cifar10.load_data() have no path param, which means everytime everyone runs his/her jupyter scripts that requires cifar10 datasets, he/she had to download the datasets from source again, it's really boring and time-consuming :)
```

### Standalone code to reproduce the issue

```shell
import autokeras as ak
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import cifar10

(x_train, y_train), (x_test, y_test) = cifar10.load_data()
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@BA7LYA 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
