### ISSUE TITLE
GPU and NNAPI Delegate not available due to "dynamic-sized tensors "

### ISSUE THREAD

**Issue by francescoyou97** [tensorflow/tensorflow#56180]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

tf 2.5.0

### Custom Code

Yes

### OS Platform and Distribution

Windows 11

### Mobile device

Android 10

### Python version

3.6.0

### CUDA/cuDNN version

Not used. 

### Current Behaviour?

```shell
I am developing an RNN to process some time sequences. I am using both LSTM and GRU and need to convert the trained model to Tflite to use it under Android (version 10).
The problem is that despite my best efforts, I am unable to use the GPU and NNAPI delegates under the android device I am using due to the exception that is thrown:

java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.

I state that I am not using CUDA / cuDNN since the laptop I am using does not have a GPU and the model I train is relatively simple.

I don't know if this depends on the batch size set to None, on the tensorflow version, on the tf.lite.OpsSet.SELECT_TF_OPS option being converted, or simply on the fact that this type of layers (LSTM, GRU) cannot support these types of delegates.
```

### Standalone code to reproduce the issue

```shell
model = tf.keras.models.Sequential([                            
            tf.keras.layers.InputLayer(input_shape=(21 * 3 * 2 * 21, )),
            tf.keras.layers.Reshape((21, 3 * 2 * 21)),        
            tf.keras.layers.LSTM(32, return_sequences=True),
            tf.keras.layers.Dropout(0.40, seed=42),
            tf.keras.layers.LSTM(32),        
            tf.keras.layers.Dropout(0.50, seed=42),             
            tf.keras.layers.Dense(27, activation='softmax')])    
           
    # Model Compile
    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
        history = model.fit(
            X_train,
            y_train,
            epochs=2000,
            batch_size=256,
            validation_data=(X_val, y_val),
            callbacks=callbacks,
            shuffle=True,
        )

    model.save(model_save_path, include_optimizer=False)   
    model = tf.keras.models.load_model(model_save_path)

    converter = tf.lite.TFLiteConverter.from_keras_model(model)  
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.experimental_new_converter=True
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS]

    tflite_quantized_model = converter.convert()

    open(tflite_save_path, 'wb').write(tflite_quantized_model)

    interpreter = tf.lite.Interpreter(model_path=tflite_save_path)
    interpreter.allocate_tensors()
```

### Relevant log output

```shell
java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
```
</details>

**Comment by mohantym** [comment]
Hi @francescoyou97 ! Could you please share the above as a gist (with Dataset)? Thank you!

**Comment by francescoyou97** [comment]
https://gist.github.com/francescoyou97/7675ad6055d5e80ed264042587499a1f

**Comment by francescoyou97** [comment]
[train.zip](https://github.com/tensorflow/tensorflow/files/8737939/train.zip)

**Comment by francescoyou97** [comment]
Is Ok?

**Comment by mohantym** [comment]
@francescoyou97 ! I think this [thread](https://stackoverflow.com/a/66683510/11530462) will answer your question. @sachinprasadhs ! Could you please look at this issue. Attached gist in [2.8](https://colab.sandbox.google.com/gist/mohantym/4f9aa1481b17185d8150213967f74401/git_56180.ipynb#scrollTo=evSgv13-uQCB), [2.9](https://colab.sandbox.google.com/gist/mohantym/ead38bea0e5bec9106b5ae567e3541cc/git_56180.ipynb#scrollTo=NrfPYtJCugud) and [nightly](https://colab.sandbox.google.com/gist/mohantym/fd9bbfae303e3bef79bb5851840bf4c7/git_56180.ipynb) . Thank you!

**Comment by francescoyou97** [comment]
Thanks @mohantym. I will try your solutions.
I have currently managed to find a workaround that worked for me:

    run_model = tf.function(lambda x: model(x))
    input_shape = [1, model.inputs[0].shape[1]]       
    concrete_func = run_model.get_concrete_function(tf.TensorSpec(input_shape, model.inputs[0].dtype))

    model.save(model_save_path, save_format='tf', include_optimizer=False, signatures=concrete_func)
    model = tf.keras.models.load_model(model_save_path)

    converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.experimental_new_converter=True
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS]
    
    tflite_quantized_model = converter.convert()

    open(tflite_save_path, 'wb').write(tflite_quantized_model)

**Comment by sachinprasadhs** [comment]
Hi, Currently NNAPI acceleration is not supported when dynamic sized tensors are used, you can find the details from the tensorflow document [here]([url](https://www.tensorflow.org/lite/android/delegates/nnapi#use_supported_models_and_ops)).
The only way now would be to have workaround solution like you're doing.
