### ISSUE TITLE
Restore non max suppression (nms) support for Tensorflow Lite GPU Delegate.

### ISSUE THREAD

**Issue by sebastian-sz** [tensorflow/tensorflow#56206]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

v2.9.0-rc2-42-g8a20d54a3c1 2.9.0

### Custom Code

Yes

### OS Platform and Distribution

Google Colab

### Python version

3.7.13 (Google Colab)

### Current Behaviour?

```shell
TL;DR: 
Please restore support for NonMaxSuppression for Tensorflow Lite GPU Delegate.  
It was supported before (TF 2.3) and is not supported now.

Background:
Back in Tensorflow version 2.3 one could take and run Object Detection model (e.g. from
Tensorflow Object Detection API) and run it fully on the TFLite with GPU via delegate.

Right now it is impossible - operations that were previously supported (like `NonMaxSuppression`) are now unsupported.

By dropping support to these operations user's are forced-locked to use older Tensorflow version. Please bring back support for `NonMaxSuppression` as it was previously supported.
```

### Standalone code to reproduce the issue

```shell
# Colab link:
# https://colab.research.google.com/drive/1orm0B-5US7Tn5EaAKJl4xGKbHegLtNYm?usp=sharing

# Let's verify support with TFLite's Authoring Tool
import tensorflow as tf

@tf.function(input_signature = [
    tf.TensorSpec(shape=(1, 100, 4), dtype=tf.float32),  # boxes
    tf.TensorSpec(shape=(1, 100, 1), dtype=tf.float32)  # scores
])
def nms(boxes, scores):
    return tf.image.non_max_suppression_padded(
        boxes,
        scores,
        max_output_size=15,
        pad_to_max_output_size=True,
    )

# Verify this works:
boxes = tf.ones(shape=(1, 100, 4))
scores = tf.ones(shape=(1, 100, 1))
selected_indices_padded, num_valid = nms(boxes, scores)

# Verify crashes TFLite GPU Delegate (authoring tool)
target_spec = tf.lite.TargetSpec()
target_spec.experimental_supported_backends = ["GPU"]
func_to_test = tf.lite.experimental.authoring.compatible(
    nms, converter_target_spec=target_spec, raise_exception=True
)
func_to_test(boxes, scores)
```

### Relevant log output

```shell
# The log output is rather long and covers multiple sub ops. I'm only pasting the lower part:

During handling of the above exception, another exception occurred:

CompatibilityError                        Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/authoring/authoring.py in _decode_error(self, err)
    244 
    245     if self._raise_exception and self._log_messages:
--> 246       raise CompatibilityError(f"CompatibilityException at {repr(self._func)}")
    247 
    248   def _log(self, message):

CompatibilityError: CompatibilityException at <tensorflow.python.eager.def_function.Function object at 0x7f70f5780590>
```
</details>

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this feature request. Attached gist in [2.8](https://colab.sandbox.google.com/gist/mohantym/d84be386fecfd5e1dca2676b9ca10400/nms_tflite_gpu_support_feature_request.ipynb#scrollTo=3vc-RCD4uZfD), [2.9 ](https://colab.sandbox.google.com/gist/mohantym/324c447ceb8456c47553d29c288f7f49/nms_tflite_gpu_support_feature_request.ipynb#scrollTo=kPSecSv-pv_x)and [nightly ](https://colab.sandbox.google.com/gist/mohantym/35bb6a18fb1f6f1ce1d5a3dee138bf10/nms_tflite_gpu_support_feature_request.ipynb#scrollTo=3vc-RCD4uZfD)for reference. Thank you!

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.

**Comment by sebastian-sz** [comment]
@pkgoogle thank you for the response. I do not have the resources to investigate atm. As far as I remember the NMS op GPU Delegate worked on an embedded device, but the check itself, on the Python side, failed.

I am closing this issue, and as you mentioned - if the issue persists it would be best to open up a new one.
