### ISSUE TITLE
pod install command can't install TensorFlowLiteSwift 2.9.0 on MacBook Air M1

### ISSUE THREAD

**Issue by snowuyl** [tensorflow/tensorflow#56216]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9

### Custom Code

No

### OS Platform and Distribution

macOS 12.3.1（M1 arm64CPU)

### Mobile device

iPhone 12

### Python version

3.9.12

### Bazel version

5.0.0

### GCC/Compiler version

Apple clang version 13.1.6

### Current Behaviour?

```shell
pod install command can't install TensorFlowLiteSwift 2.9.0
```

### Standalone code to reproduce the issue

```shell
Using Xcode to create TFLiteSwift project
cd TFLiteSwift
pod init
Adding the following command to Podfile
pod 'TensorFlowLiteSwift' '~> 2.9.0'
pod install
```

### Relevant log output

```shell
pod install
Analyzing dependencies
[!] Unable to find a specification for `TensorFlowLiteSwift~> 2.9.0`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```
</details>

**Comment by mohantym** [comment]
Hi @snowuyl! Could you let us know after making changes in Pod file as below once you initialise the Pod (which will select target automatically). Thank you!

```
platform :ios, '12.0'

target 'ObjectDetection' do # it will select project automatically once you do pod init 
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjectDetection

   pod 'TensorFlowLiteSwift', '~> 2.9.0'

end
```

**Comment by snowuyl** [comment]
pod install command can run successfully after modifying Podfile according your suggestion. But Xcode build failed with No such module 'TensorFlowLite'. The following is content of TFLiteSwiftApp.swift.
cat TFLiteSwiftApp.swift 
//
//  TFLiteSwiftApp.swift
//  TFLiteSwift
//
//  Created by  snowuyl on 2022/5/23.
//

import SwiftUI
import  TensorFlowLite

@main
struct TFLiteSwiftApp: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

**Comment by mohantym** [comment]
@snowuyl ! You have to add the dependency too. Please refer to the[ image classification project](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/ios) as a starting point .Thank you!
```
swift_library(
  deps = [
      "//tensorflow/lite/swift:TensorFlowLite",
  ],
)
```

**Comment by snowuyl** [comment]
image classifiication project also has this issue too.
cd examples/lite/examples/image_classification/iOS
open ImageClassification.xcodeproj
Xcode build failed with No such module 'TensorFlowLite'.

**Comment by mohantym** [comment]
Ok @snowuyl ! Thanks for pointing out . @sachinprasadhs ! Could you please look at this issue.

**Comment by snowuyl** [comment]
Thanks for your suggestion. Xcode can build successfully with "open TFLiteSwift.xcworkspace" command.

**Comment by daniaAO** [comment]
> @snowuyl ! You have to add the dependency too. Please refer to the[ image classification project](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/ios) as a starting point .Thank you!
> 
> ```
> swift_library(
>   deps = [
>       "//tensorflow/lite/swift:TensorFlowLite",
>   ],
> )
> ```

Where should I put this?
