### ISSUE TITLE
Cholesky decomposition half precision either does not work or wrong documentation.

### ISSUE THREAD

**Issue by andsmi97** [tensorflow/tensorflow#56226]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### GPU model and memory

Tesla T4

### Current Behaviour?

```shell
Cholesky crashes for half precision while documentation says otherwise. 
Quote from documentation: input	A Tensor. Must be one of the following types: float64, float32, half, complex64, complex128. Shape is [..., M, M].
https://www.tensorflow.org/api_docs/python/tf/linalg/cholesky
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
A = tf.random.normal((32,32), dtype=tf.dtypes.float16) # same for tf.dtypes.half
U = A @ tf.transpose(A)
tf.linalg.cholesky(U)
```

### Relevant log output

```shell
Could not find device for node: {{node Cholesky}} = Cholesky[T=DT_HALF]
All kernels registered for op Cholesky:
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_COMPLEX64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
 [Op:Cholesky]
```
</details>

**Comment by sushreebarsa** [comment]
@andsmi97 Could you please have a look at this [gist](https://colab.research.google.com/gist/sushreebarsa/2473d3c0a7d0a674545ac8b24da61809/56226.ipynb) and confirm the issue?
Thank you!

**Comment by andsmi97** [comment]
> @andsmi97 Could you please have a look at this [gist](https://colab.research.google.com/gist/sushreebarsa/2473d3c0a7d0a674545ac8b24da61809/56226.ipynb) and confirm the issue? Thank you!

Yes, this is the issue. I did exactly the same, but for default tf 2.8 version.

**Comment by chunduriv** [comment]
@andsmi97,

Thank you for reporting the documentation bug. We will submit the fix.

**Comment by sachinprasadhs** [comment]
For the half precision, there will be more deviation in the output due to precision point errors. 
Could you try the OP in float32 and then convert back to dtype half.
