### ISSUE TITLE
Problem in the documentation

### ISSUE THREAD

**Issue by amirj** [tensorflow/tensorflow#5622]
It seems that the documentation has a problem. For example, the most useful functions such as `fit` or `evaluate` in [the documentation of tf.contrib.learn](https://www.tensorflow.org/versions/r0.11/api_docs/python/contrib.learn.html#Estimator) is as follows:

> tf.contrib.learn.Estimator.fit(x=None, y=None, input_fn=None, steps=None, batch_size=None, monitors=None, max_steps=None)
> 
> See Trainable.
> 
> Raises:
> 
> ValueError: If x or y are not None while input_fn is not None.
> ValueError: If both steps and max_steps are not None.
> 

[Trainable](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/trainable.py) does not linked or described in the generated documentation. It's really annoying issue for beginners.

**Comment by girving** [comment]
Assigning to @wicke for further triage.  There are quite a few of these missing links, so some sort of automated or semi-scripted method may be in order.

**Comment by martinwicke** [comment]
I'm publishing the Trainable/Evaluable docs. Sorry about that.
