### ISSUE TITLE
Function similar to torch.nn.functional.grid_sample

### ISSUE THREAD

**Issue by Jove125** [tensorflow/tensorflow#56225]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

2.9.0

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04

### Python version

3.7.10

### Current Behaviour?

```shell
I want to convert a model containing torch.nn.functional.grid_sample function from pytorch format to tensorflow format.
I was able to convert from pytorch format to onnx format (see https://github.com/microsoft/onnxruntime/issues/10232).
To convert from onnx format to tensorflow format, I need to implement this function in the onnx_tf converter.
Is there an analogue of such a function in tensorflow?
If not, are there plans to implement it?
```

### Standalone code to reproduce the issue

```shell
torch.nn.functional.grid_sample
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
Hi @Jove125,
Could you  take a look at this models repo [issue](https://github.com/tensorflow/models/issues/7381)  where a similar feature has been proposed and it is still open. I request to follow the similar feature which has been proposed for the updates on similar request.

Also please take a look at this SO [link](https://stackoverflow.com/questions/52888146/what-is-the-equivalent-of-torch-nn-functional-grid-sample-in-tensorflow-numpy) with the similar request. It helps. Thank you!
