### ISSUE TITLE
BUG: Memory leak bugs due to new reference passed to non-stealing APIs (static analyzer reports)

### ISSUE THREAD

**Issue by Snape3058** [tensorflow/tensorflow#56236]
## Function `PyDict_SetItemString` and `PyDict_SetItem`

`PyDict_SetItemString` does not steal a reference from its third argument.
`PyDict_SetItem` does not steal a reference from its last two arguments.

* Internal Report ID: 7311bd 
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L145

* Internal Report ID: 0bf563
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L147

* Internal Report ID: 107a6c
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L149

* Internal Report ID: 336e4b
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L659

* Internal Report ID: f40c5f 
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L663

* Internal Report ID: 253804
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/toco/python/toco_python_api.cc#L233

* Internal Report ID: 9b7aa7 
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L1057

* Internal Report ID: 66dcb9
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L1058

* Internal Report ID: 327452 
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L1093

* Internal Report ID: c80650
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L1094

* Internal Report ID: 271ec8 
Returning a new reference here:
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L141
Passed to a non-stealing API as the sink:
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L161

* Internal Report ID: c41b64
Returning a new reference here:
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L650
Other usages as the `self` PyObject:
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L666
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L667
Passed to a non-stealing API as the sink:
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L668

* Internal Report ID: 7193e8 
Returning a new reference here:
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L651
Other usages as the `self` PyObject:
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L658
Passed to a non-stealing API as the sink:
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L666

* Internal Report ID: 9dcdd9 
Returning a new reference here:
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L652
Other usages as the `self` PyObject:
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L662
Passed to a non-stealing API as the sink:
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L667

## Other functions

* Internal Report ID: 6a12cf (`PyObject_GetAttr`)
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L1018

* Internal Report ID: 918a9a (`PyBytes_AsString`)
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/lib/core/ndarray_tensor.cc#L90

* Internal Report ID: fffdc2 (`PyCapsule_GetPointer`)
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/lib/core/py_func.cc#L201

* Internal Report ID: 34df8e (`PyCapsule_GetPointer`)
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/lib/core/py_func.cc#L240 

* Internal Report ID: 506234 (`PyCapsule_GetPointer`)
Returning a new reference here:
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L3663
Passed to a non-stealing API as the sink:
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L3666

* Internal Report ID: 9ede7a (`PyType_FromSpecWithBases`)
Returning a new reference here:
https://github.com/tensorflow/tensorflow/blob/eee70a365f5deb9c78e63945756f856fb96847cb/tensorflow/python/eager/pywrap_tensor.cc#L1054
Other usages as the `self` PyObject:
https://github.com/tensorflow/tensorflow/blob/eee70a365f5deb9c78e63945756f856fb96847cb/tensorflow/python/eager/pywrap_tensor.cc#L1055
Passed to a non-stealing API as the sink:
https://github.com/tensorflow/tensorflow/blob/eee70a365f5deb9c78e63945756f856fb96847cb/tensorflow/python/eager/pywrap_tensor.cc#L1085

## Many usages as the `self` PyObject or a C pointer.

* Internal Report ID: 8235b2 
Returning a new reference here:
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/toco/python/toco_python_api.cc#L276
All other usages of this PyObject:
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/toco/python/toco_python_api.cc#L277
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/lite/toco/python/toco_python_api.cc#L278

* Internal Report ID: bf3201
Returning a new reference here:
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/framework/python_api_parameter_converter_wrapper.cc#L33
All other usages of this PyObject:
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/framework/python_api_parameter_converter_wrapper.cc#L34
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/framework/python_api_parameter_converter_wrapper.cc#L35

* Internal Report ID: b665b7
Returning a new reference here:
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L505 
All other usages of this PyObject:
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L507
Other usages in the callee function `ParseStringValue`:
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L324
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L327
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L332
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L334 
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L343

* Internal Report ID: 3eadfd
Returning a new reference here:
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L715
All other usages of this PyObject:
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L717
Other usages in the callee function `ParseStringValue`: 
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L324
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L327
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L332
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L334
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L343

* Internal Report ID: 9e7c5b
Returning a new reference here:
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/util/fast_module_type.cc#L197
All other usages of this PyObject:
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/util/fast_module_type.cc#L201
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/util/fast_module_type.cc#L215
Other usages in the callee function `CallFunc`:
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/util/fast_module_type.cc#L158

**Comment by tilakrayal** [comment]
Hi @Snape3058 ,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue. Thank you!

**Comment by Snape3058** [comment]
I think it is not necessary to provide the information you are collecting in the template, since the reports are from a static analyzer. But if you really want, here is the information I can provide.

* Issue Type: Bug
* Source: source
* Tensorflow Version: analyzer is executed on commit faad219fc46032a0ae9576ccc3076612cc1f5f72 and the bugs are confirmed to be exist in the latest commit 15c26be8f79834ae5a6123939b4885e4d6a112af when I report the bug 
* Custom Code: No
* Python version: 3.9
* Compiler version: static analyzer is developed on the top of Clang Static Analyzer 9.0.0.

**Comment by tilakrayal** [comment]
@Snape3058 ,
We see that you have mentioned multiple files to be changed. Could you feel free to submit a PR for the requested change or share the link where the requested change is to be made. Thank you!

**Comment by Snape3058** [comment]
Replace `PyAPI_NonStealing(..., PyAPI_ReturningNewReference(...))` with
```
PyObject *temp = PyAPI_ReturningNewReference(...);
PyAPI_NonStealing(..., temp);
Py_DECREF(temp);
```
where the `PyAPI_NonStealing` function indicates `PyDict_SetItemString` and so on, and the `PyAPI_ReturningNewReference` function represents those APIs returning a new reference, such as `PyLong_FromSize_t` and so on.

My research on reference leaking can only detect which PyObject has a reference count that should be decreased. Related developers should verify the suggestions for fixing the problem carefully since fixing the problem is not a part of my research.

**Comment by tilakrayal** [comment]
@Snape3058,
As suggested, could you feel free to submit a PR for the requested change or share the link where the requested change is to be made. Thank you!

**Comment by Snape3058** [comment]
My analyzer can only detect which PyObject is leaked. Besides, my research is not fixing the bug. For the sake of not introducing new bugs, I suggest related developers to take over the issue to fix these bugs.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
