### ISSUE TITLE
tensorflow 1 is much slower than 2 with tf.data.Dataset.from_tensor_slices

### ISSUE THREAD

**Issue by zhanglirong1999** [tensorflow/tensorflow#56232]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

tf 1.15.0 vs tf 2.8

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 16

### Python version

3.7

### Current Behaviour?

```shell
It was very slow when I used tf.data.Dataset.from_tensor_slices() in a tf1 environment to create a dataset, but very quickly with tf2. Whether this is an optimization of tf2. If you have to be in a tf1 environment, is there a good alternative?
```

### Standalone code to reproduce the issue

```shell
df = pd.read_csv(train_file, header=None, names=TRAIN_DATA_COLUMNS)
features = collections.OrderedDict()
for col in CONTINUOUS_COLUMNS:
    features[col] = df[col].to_numpy().astype(np.float32)
    print(features[col].dtype)

for col in CATEGORICAL_COLUMNS:
    features[col] = df[col].to_numpy()
    print(features[col].dtype)
labels = df[LABEL_COLUMN].to_numpy()
dataset = tf.data.Dataset.from_tensor_slices((features, labels))
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@zhanglirong1999 ,
Tensorflow  1.x is not actively supported. So we request to use the 2.x version as the latest version is much faster than the older version. Thank you!
