### ISSUE TITLE
non-DMA-copy attempted of tensor type: string error when trying to run roberta-base example from tfhub

### ISSUE THREAD

**Issue by preethiseshadri518** [tensorflow/tensorflow#56230]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

2.5

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.5

### Python version

3.7

### Current Behaviour?

I am trying to run the following example for roberta-base, copied from the documentation on tfhub. However, it seems unhappy with how the input is being fed into the model. I am getting `Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string`. 

```
# define a text embedding model
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string)
preprocessor = hub.KerasLayer("https://tfhub.dev/jeongukjae/roberta_en_cased_preprocess/1")
encoder_inputs = preprocessor(text_input)

encoder = hub.KerasLayer("https://tfhub.dev/jeongukjae/roberta_en_cased_L-12_H-768_A-12/1", trainable=True)
encoder_outputs = encoder(encoder_inputs)
pooled_output = encoder_outputs["pooled_output"]      # [batch_size, 768].
sequence_output = encoder_outputs["sequence_output"]  # [batch_size, seq_length, 768].

model = tf.keras.Model(text_input, pooled_output)

# You can embed your sentences as follows
sentences = tf.constant(["(your text here)"])
print(model(sentences))
```

If I instead use the preprocessor and encoder from BERT instead of RoBERTa, the code above works. 
```
preprocessor = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4", trainable=True)
```
In addition, the code above with the RoBERTa preprocessor/encoder seems to work if I use CPU instead of GPU (adding `with tf.device('/cpu:0')`), but this is not feasible because I need to fine-tune a model on lots of data.  

### Standalone code to reproduce the issue
I am using tensorflow version 2.5 and tensoflow_hub version 0.12. Here is a link to the model on tfhub: https://tfhub.dev/jeongukjae/roberta_en_cased_L-12_H-768_A-12/1.

### Relevant log output

```shell
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  2 root error(s) found.
  (0) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
  (1) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
0 successful operations.
0 derived errors ignored.
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/bpe_sentencepiece_tokenizer/StatefulPartitionedCall/map/TensorArrayUnstack/TensorListFromTensor/_100}}]]
  (1) Invalid argument:  2 root error(s) found.
  (0) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
  (1) Invalid argument: During Variant Host->Device Copy: non-DMA-copy attempted of tensor type: string
0 successful operations.
0 derived errors ignored.
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/bpe_sentencepiece_tokenizer/StatefulPartitionedCall/map/TensorArrayUnstack/TensorListFromTensor/_100}}]]
	 [[StatefulPartitionedCall/StatefulPartitionedCall/bpe_sentencepiece_tokenizer/StatefulPartitionedCall/RaggedFromRowSplits_1/RowPartitionFromRowSplits/control_dependency/_157]]
0 successful operations.
0 derived errors ignored. [Op:__inference_restored_function_body_376768]

Function call stack:
restored_function_body -> restored_function_body
```
</details>

**Comment by sushreebarsa** [comment]
@preethiseshadri518 I was able to replicate the issue on [cpu ](https://colab.research.google.com/gist/sushreebarsa/0ad5cf0d74dc5c51723f2419ac8222f7/cpu-56230.ipynb)and [gpu](https://colab.research.google.com/gist/sushreebarsa/88f2ff2d0dc3dd88b8691e69115ff6bd/cpu-56230.ipynb#scrollTo=GNXfHLJtURz4) runtime. Please find the attached gists and for any further queries kindly post this issue on [hub ](https://github.com/tensorflow/hub/issues) repo to get the right help there. Thank you!

**Comment by preethiseshadri518** [comment]
Thank you, will post there.
