### ISSUE TITLE
GPU can not be identified when using Tensorflow 2.4./2.5 with CUDA11.6

### ISSUE THREAD

**Issue by v3551G** [tensorflow/tensorflow#56235]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.4

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

11.6/

### GPU model and memory

RTX 3080   

### Current Behaviour?

```shell
GPU can not be identified under the tensorflow2.4.0 environment, and the code can only running using CPU. I am wandering whether Tensorflow with higher version (>=2.5) supports GPU, or whether TensorFlow 2.4/2.5 is compatible with CUDA 11.6.

Note that two RTX 3080 GPUs were installed on the machine, and the CUDA and CUDNN are installed properly, since there is no bugs when running other programs written based on Pytorch and GPU can be identified.
```

### Standalone code to reproduce the issue

```shell
This is an environmental problem. The GPU cannot be recognized using tensorflow 2.4 / 2.5 framework, but it can be recognized using pytorch.
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @v3551G !  Could you check with Cuda 11.2 and CudNN 8.1 too on 2.7 or 2.8 . Thank you!

**Comment by v3551G** [comment]
Thank you. On another machine equipped with RTX3080, install with CUDA 11.4, GPU can be identified when using Tensorflow 2.4.x

**Comment by mohantym** [comment]
@v3551G ! Thanks for the update . Cuda 11.6 has stability issues . Please stick with tested configurations for optimum performance and  move this to closed status if it is resolved. Thank you!
