### ISSUE TITLE
Unable to automatically fuse nested loop

### ISSUE THREAD

**Issue by SamKG** [tensorflow/tensorflow#56248]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.10

### CUDA/cuDNN version

11.7

### Current Behaviour?

```shell
I am running the following code with all Grappler optimizations enabled. It should be possible to re-write the code in a way that does a single matrix add for the entire tensor instead of looping - however, I am unable to force Grappler to vectorize the loops. Is there any way to do this in TensorFlow?
```

### Standalone code to reproduce the issue

```shell
@tf.function()
    def somefunc():
        tmp = tf.zeros(shape=(10, 10), dtype=tf.double, name="tmp")
        for i in range(0, 10):
            for j in range(0, 10):
                tmp = tf.tensor_scatter_nd_update(
                    tmp, [[i, j]], [tmp[i][j] + 1.0], name=f"scatter_{i}_{j}"
                )

        return {"output": tmp}
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@SamKG 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!
