### ISSUE TITLE
Remove or bump upper bound for `gast` dependency

### ISSUE THREAD

**Issue by h-vetinari** [tensorflow/tensorflow#56244]
In https://github.com/tensorflow/tensorflow/commit/c762c4501ca017994c1fa5554c3c8e47b7c80b66 @angerson said:
> I also know that gast 0.5.2 breaks one of our tests, so I've pinned the gast
version to 0.4.0 or below, which is what our CI currently installs for testing.

and pinned gast to 0.4.0, which is by now [almost](https://github.com/serge-sans-paille/gast/tags) two years old.

The added `TODO(angerson): File a bug for these incompatible tests and the limitation` eventually got removed in https://github.com/tensorflow/tensorflow/commit/0c8b4f2bed6e22e797f576fb553a9a9a9145711e, but I cannot find an issue for it, hence opening this one.

**Comment by danaepapad** [comment]
I am starting working on it. I will get back to you soon

**Comment by h-vetinari** [comment]
@danaepapad 
Any update on this?

**Comment by nthiery** [comment]
> @danaepapad Any update on this?

This would be very helpful: this is preventing the installation of SageMath (through pythran)
side by side with tensorflow, which we would want to have on our JupyterHub. For a silly
practical reason (we have a fat monoimage for now) and a good reason: encouraging users
to combine machine learning and computer algebra.

Thanks in advance!

**Comment by h-vetinari** [comment]
gast 0.4.0 is coming up on three years old in July and the pin still [exists](https://github.com/tensorflow/tensorflow/blame/master/tensorflow/tools/pip_package/setup.py#L88-L89) on master. Is there some way this can be prioritized?

**Comment by thebaptiste** [comment]
Yes. It's getting more and more problematic to install tensorflow side by side with other packages...

**Comment by h-vetinari** [comment]
Could someone please have a look at raising the cap here?

I know things in FOSS can take time, but this TODO (and issue) is now over a year old, and is creating ever-larger installation problems in a wide variety of scenarios.

CC @yongtang @hawkinsp @akuegel

**Comment by mihaimaruseac** [comment]
Can you send a PR please? This way people can run the tests and if all passes it will be taken in.

I think checking the status of dependencies, sadly, is a low priority for the team.

**Comment by h-vetinari** [comment]
> Can you send a PR please? This way people can run the tests and if all passes it will be taken in.

Done: https://github.com/tensorflow/tensorflow/pull/61134

**Comment by mihaimaruseac** [comment]
Thank you! 🎉

**Comment by mihaimaruseac** [comment]
Thank you for fixing this in #61134!

**Comment by mihaimaruseac** [comment]
Branch cut is in a few weeks, after which the final release should arrive in a month (though the releases in the past year have been delayed more and more, almost 3 months between branch cut and final release for the last release)
