### ISSUE TITLE
Multiple problems building TFLite 2.9.1

### ISSUE THREAD

**Issue by w3sip** [tensorflow/tensorflow#56250]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

iOS

### Current Behaviour?

```shell
1. tensorflow/lite/c/CMakeLists.txt references common.c. Actual file at the referenced location is common.cc
2. With default TFL_MINIMUM_OS_VERSION=9.0 in tensorflow/lite/ios/ios.bzl, there is a compile-time error in Eigen related to thread local storage. Need that value bumped to 10.0 or 11.0 by default.
3. Upon the successful completion of `bazel build --config=ios_fat -c opt //tensorflow/lite/ios:TensorFlowLiteC_static_framework`, the `bazel-bin` folder is empty. The output can be found in `bazel-out/applebin_ios-ios_armv7-opt-ST-5b7531beec20/bin/tensorflow/lite/ios/TensorFlowLiteC_static_framework.zip` instead
4. Why is the hard dependency on Bazel version? Why does it have to be 5.0.0 and can not be 5.1.1? This makes it very unfriendly for CI environment.
```

### Standalone code to reproduce the issue

```shell
Just build it out of the box.
```

### Relevant log output

```shell
INFO: Found 1 target...
Target //tensorflow/lite/ios:TensorFlowLiteC_static_framework up-to-date:
  bazel-out/applebin_ios-ios_armv7-opt-ST-5b7531beec20/bin/tensorflow/lite/ios/TensorFlowLiteC_static_framework.zip
INFO: Elapsed time: 0.280s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

Compared to 2.7.1:
```
Target //tensorflow/lite/ios:TensorFlowLiteC_static_framework up-to-date:
  bazel-bin/tensorflow/lite/ios/TensorFlowLiteC_static_framework.zip
INFO: Elapsed time: 411.210s, Critical Path: 80.19s
INFO: 3901 processes: 227 internal, 3674 local.
INFO: Build completed successfully, 3901 total actions
INFO: Build completed successfully, 3901 total actions
```
```
</details>

**Comment by w3sip** [comment]
P.S. Would it ever be (or is it already) possible to build TFLite for iOS with straight CMake, avoiding bazel?

**Comment by w3sip** [comment]
It looks like the symlinks bazel creates point to a wrong folder:

```
21:27:40 alex@w3sip:~/work/deps/conan-deps-tflite/.build $ ls -la bazel-symlinks/
total 0
drwxr-xr-x  6 alex  staff  192 May 24 21:19 .
drwxr-xr-x  9 alex  staff  288 May 24 21:19 ..
lrwxr-xr-x  1 alex  staff  110 May 24 21:19 bin -> /private/var/tmp/_bazel_alex/6a1d737aeb2b5af2483f6506d1d318a0/execroot/org_tensorflow/bazel-out/darwin-opt/bin
lrwxr-xr-x  1 alex  staff   95 May 24 21:19 out -> /private/var/tmp/_bazel_alex/6a1d737aeb2b5af2483f6506d1d318a0/execroot/org_tensorflow/bazel-out
lrwxr-xr-x  1 alex  staff   85 May 24 21:19 tensorflow -> /private/var/tmp/_bazel_alex/6a1d737aeb2b5af2483f6506d1d318a0/execroot/org_tensorflow
lrwxr-xr-x  1 alex  staff  115 May 24 21:19 testlogs -> /private/var/tmp/_bazel_alex/6a1d737aeb2b5af2483f6506d1d318a0/execroot/org_tensorflow/bazel-out/darwin-opt/testlogs
```

while the actual build product is found here

```
21:25:33 alex@w3sip:~/work/deps/conan-deps-tflite/.build $ find bazel-symlinks/out/ -name "*.zip"
bazel-symlinks/out//applebin_ios-ios_armv7-opt-ST-5b7531beec20/bin/tensorflow/lite/ios/TensorFlowLiteC_static_framework.zip
bazel-symlinks/out//applebin_ios-ios_armv7-opt-ST-5b7531beec20/bin/tensorflow/lite/ios/TensorFlowLiteC_static_framework-intermediates/unprocessed_archive.zip
```

**Comment by mohantym** [comment]
@w3sip ! Thanks for reporting these bugs . @sachinprasadhs ! Could you please look at this issue. Thank you!

**Comment by alegrigoriev-phillips-connect** [comment]
It appears there was a regression in commit 848e84c5a3acda31847457cbd52742436e024984. tensorflow/lite/c/common.c was renamed to common.cc, but tensorflow/lite/c/CMakeLists.txt hasn't been updated to reflect that.

**Comment by w3sip** [comment]
Additionally, once all of the above are patched, and tflite builds, my project (previously successfully linking and running with 2.7.1), now fails to link with

```
Undefined symbols for architecture arm64:
  "absl::lts_20211102::ResourceExhaustedError(std::__1::basic_string_view<char, std::__1::char_traits<char> >)", referenced from:
      l5657 in TensorFlowLiteCMetal
  "absl::lts_20211102::strings_internal::CatPieces(std::initializer_list<std::__1::basic_string_view<char, std::__1::char_traits<char> > >)", referenced from:
[ 92%] Building CXX object plumbing/CMakeFiles/plumbing.dir/__/generated/plumbing/_cs/GetListItem.cpp.o
      l3832 in TensorFlowLiteCMetal
      l3833 in TensorFlowLiteCMetal
  "absl::lts_20211102::InvalidArgumentError(std::__1::basic_string_view<char, std::__1::char_traits<char> >)", referenced from:
      l174 in TensorFlowLiteCMetal
      l244 in TensorFlowLiteCMetal
      l2049 in TensorFlowLiteCMetal
      l2054 in TensorFlowLiteCMetal
      l2055 in TensorFlowLiteCMetal
      l2066 in TensorFlowLiteCMetal
      l3425 in TensorFlowLiteCMetal
      ...
  "absl::lts_20211102::UnknownError(std::__1::basic_string_view<char, std::__1::char_traits<char> >)", referenced from:
      l245 in TensorFlowLiteCMetal
      l247 in TensorFlowLiteCMetal
      l2062 in TensorFlowLiteCMetal
      l2067 in TensorFlowLiteCMetal
      l2076 in TensorFlowLiteCMetal
      l3436 in TensorFlowLiteCMetal
   ```
   (more similar errors wrt absl::lts_20211102 namespace omitted for brevity).

**Comment by w3sip** [comment]
Any help with this, guys? What changed between 2.7.1 and 2.9.1 to cause the absl errors?

**Comment by w3sip** [comment]
Here's an example of symbols in 2.7.1 vs 2.9.1 resulting frameworks:

2.9.1:
```
$ nm ~/.conan/data/tensorflow-lite/2.9.1.16+329b4449/ci/branch_release_2.9/package/c59ee57fe12aba06c09eb42e8369b6b2d726a34b/lib/TensorFlowLiteCMetal.framework/TensorFlowLiteCMetal | grep absl
                 U __ZN4absl12lts_2021110212UnknownErrorENSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE
                 U __ZN4absl12lts_2021110213DataLossErrorENSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE
                 U __ZN4absl12lts_2021110213InternalErrorENSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE
                 U __ZN4absl12lts_2021110213NotFoundErrorENSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE
                 U __ZN4absl12lts_2021110216strings_internal9CatPiecesESt16initializer_listINSt3__117basic_string_viewIcNS3_11char_traitsIcEEEEE
                 U __ZN4absl12lts_2021110218UnimplementedErrorENSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE
                 U __ZN4absl12lts_2021110219substitute_internal24SubstituteAndAppendArrayEPNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS2_17basic_string_viewIcS5_EEPKSB_m
                 U __ZN4absl12lts_2021110220InvalidArgumentErrorENSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE
                 U __ZN4absl12lts_2021110222ResourceExhaustedErrorENSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE
00000000002265eb s __ZZN4absl12lts_2021110218debugging_internalL30IdentifierIsAnonymousNamespaceEPNS1_5StateEiE11anon_prefix
0000000000226939 s __ZZN4absl12lts_202111029SymbolizeEPKvPciE9kEllipsis
```

2.7.1:
```
$ nm ~/.conan/data/tensorflow-lite/2.7.1.14+442738f3/ci/branch_release_2.7/package/3b95326f653baf403ae4d70dae74814d9c4fef8a/lib/TensorFlowLiteCMetal.framework/TensorFlowLiteCMetal | grep absl
00000000001f3e64 s __ZZN4absl12lts_2021032418debugging_internalL30IdentifierIsAnonymousNamespaceEPNS1_5StateEiE11anon_prefix
00000000001f41b1 s __ZZN4absl12lts_202103249SymbolizeEPKvPciE9kEllipsis
```

**Comment by sachinprasadhs** [comment]
@w3sip I'm looking into it, for the first 2 points which you have mentioned, I have created a PR.

**Comment by freedomtan** [comment]
> It looks like the symlinks bazel creates point to a wrong folder:
> 
> ```
> 21:27:40 alex@w3sip:~/work/deps/conan-deps-tflite/.build $ ls -la bazel-symlinks/
> total 0
> drwxr-xr-x  6 alex  staff  192 May 24 21:19 .
> drwxr-xr-x  9 alex  staff  288 May 24 21:19 ..
> lrwxr-xr-x  1 alex  staff  110 May 24 21:19 bin -> /private/var/tmp/_bazel_alex/6a1d737aeb2b5af2483f6506d1d318a0/execroot/org_tensorflow/bazel-out/darwin-opt/bin
> lrwxr-xr-x  1 alex  staff   95 May 24 21:19 out -> /private/var/tmp/_bazel_alex/6a1d737aeb2b5af2483f6506d1d318a0/execroot/org_tensorflow/bazel-out
> lrwxr-xr-x  1 alex  staff   85 May 24 21:19 tensorflow -> /private/var/tmp/_bazel_alex/6a1d737aeb2b5af2483f6506d1d318a0/execroot/org_tensorflow
> lrwxr-xr-x  1 alex  staff  115 May 24 21:19 testlogs -> /private/var/tmp/_bazel_alex/6a1d737aeb2b5af2483f6506d1d318a0/execroot/org_tensorflow/bazel-out/darwin-opt/testlogs
> ```
> 
> while the actual build product is found here
> 
> ```
> 21:25:33 alex@w3sip:~/work/deps/conan-deps-tflite/.build $ find bazel-symlinks/out/ -name "*.zip"
> bazel-symlinks/out//applebin_ios-ios_armv7-opt-ST-5b7531beec20/bin/tensorflow/lite/ios/TensorFlowLiteC_static_framework.zip
> bazel-symlinks/out//applebin_ios-ios_armv7-opt-ST-5b7531beec20/bin/tensorflow/lite/ios/TensorFlowLiteC_static_framework-intermediates/unprocessed_archive.zip
> ```

FYI. I ran into this problem couple months ago, it was caused by bazel 5.x. My workaround is to use `ipa_post_processor` to copy what I wanted to place with definite name, see what I did athttps://github.com/mlcommons/mobile_app_open/pull/268/commits/00cace81827a6927f4531ff2aa4ca2419c536f1a

**Comment by freedomtan** [comment]
> Here's an example of symbols in 2.7.1 vs 2.9.1 resulting frameworks:
> 
> 2.9.1:
> 
> ```
> $ nm ~/.conan/data/tensorflow-lite/2.9.1.16+329b4449/ci/branch_release_2.9/package/c59ee57fe12aba06c09eb42e8369b6b2d726a34b/lib/TensorFlowLiteCMetal.framework/TensorFlowLiteCMetal | grep absl
>                  U __ZN4absl12lts_2021110212UnknownErrorENSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE
>                  U __ZN4absl12lts_2021110213DataLossErrorENSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE
>                  U __ZN4absl12lts_2021110213InternalErrorENSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE
>                  U __ZN4absl12lts_2021110213NotFoundErrorENSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE
>                  U __ZN4absl12lts_2021110216strings_internal9CatPiecesESt16initializer_listINSt3__117basic_string_viewIcNS3_11char_traitsIcEEEEE
>                  U __ZN4absl12lts_2021110218UnimplementedErrorENSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE
>                  U __ZN4absl12lts_2021110219substitute_internal24SubstituteAndAppendArrayEPNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEENS2_17basic_string_viewIcS5_EEPKSB_m
>                  U __ZN4absl12lts_2021110220InvalidArgumentErrorENSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE
>                  U __ZN4absl12lts_2021110222ResourceExhaustedErrorENSt3__117basic_string_viewIcNS1_11char_traitsIcEEEE
> 00000000002265eb s __ZZN4absl12lts_2021110218debugging_internalL30IdentifierIsAnonymousNamespaceEPNS1_5StateEiE11anon_prefix
> 0000000000226939 s __ZZN4absl12lts_202111029SymbolizeEPKvPciE9kEllipsis
> ```
> 
> 2.7.1:
> 
> ```
> $ nm ~/.conan/data/tensorflow-lite/2.7.1.14+442738f3/ci/branch_release_2.7/package/3b95326f653baf403ae4d70dae74814d9c4fef8a/lib/TensorFlowLiteCMetal.framework/TensorFlowLiteCMetal | grep absl
> 00000000001f3e64 s __ZZN4absl12lts_2021032418debugging_internalL30IdentifierIsAnonymousNamespaceEPNS1_5StateEiE11anon_prefix
> 00000000001f41b1 s __ZZN4absl12lts_202103249SymbolizeEPKvPciE9kEllipsis
> ```

ABSL when compiled with different C++ standard (e.g., -std=c++14 vs. -std=c++17) may result in different binary. Some TFLite component changed to used C++17 (e.g., metal delegate), so a quick solution is to add `--cxxopt=-std=c++17 --host_cxxopt=-std=c++17` to you bazel build flags.

**Comment by w3sip** [comment]
> 
> ABSL when compiled with different C++ standard (e.g., -std=c++14 vs. -std=c++17) may result in different binary. Some TFLite component changed to used C++17 (e.g., metal delegate), so a quick solution is to add `--cxxopt=-std=c++17 --host_cxxopt=-std=c++17` to you bazel build flags.

Thanks @freedomtan , that fixed it!
