### ISSUE TITLE
is it possible to calculate Body degree angle using pose estimation

### ISSUE THREAD

**Issue by IBSApple** [tensorflow/tensorflow#56265]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML', 'Metal']

### Custom Code

Yes

### Current Behaviour?

```shell
How to calculate degree of angles using body keyPoints? & Pose angle. ie. 45 degree, 90 degree.
```

### Standalone code to reproduce the issue

```shell
I want to detect human body pose angle is it possible?
```

### Relevant log output

_No response_</details>

**Comment by sachinprasadhs** [comment]
As of now, I don't think there is any direct way to calculate angle using tflite.
However, you can find the angle using your custom functions, you can refer [this](https://learnopencv.com/building-a-body-posture-analysis-system-using-mediapipe/#PREREQUISITES--) code example which was implemented using MediaPipe. 
Let us know if this helps you. Thanks!
