### ISSUE TITLE
Using front camera for android with tensorflow lite

### ISSUE THREAD

**Issue by DemoLV** [tensorflow/tensorflow#56260]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### OS Platform and Distribution

Windows 10

### Mobile device

Android

### Current Behaviour?

```shell
I want to use my android phones front camera (Samsung galaxy S9). I have toggled the camera to be on the front and also I have removed the mirror effect but still. It does not detect the objects. 
1) It does not detect all of the objects;
2) If it detects some object then it like floats away.

The funny thing is whenever I switch to the back camera. Everything works like a charm, so it is not the models problem that is for sure I think.
```

### Standalone code to reproduce the issue

```shell
So to make it happen.

In CameraActivity.java, line 427
if (facing != null && facing == CameraCharacteristics.LENS_FACING_BACK); //To toggle front camera

In LegacyCameraConnectionFragment.java, line 217
if (ci.facing == CameraInfo.CAMERA_FACING_FRONT) //to toggle front camera

In LegacyCameraConnectionFragment.java, under line 181
Matrix matrix = new Matrix();                         
matrix.setScale(-1, 1);                        
matrix.postTranslate(textureView.getWidth(), 0);  
textureView.setTransform(matrix);   

The whole matrix is to remove the mirror efect on the front camera. 
Now that I have made these changes in the code, the front camera does not want to detect all of the objects, if it detects, then the objects just float. Am I missing something ?
```

### Relevant log output

_No response_</details>

**Comment by DemoLV** [comment]
Maybe someone have some ideas on how to resolve the issue ? 
The problem is with the bounding boxes, the front camera does not detect objects precisely if it detects, then it floats somewhere.
Whenever I toggle camera to back, everything works like it should. 
Thank you again !
I will wait for the reply.

**Comment by DemoLV** [comment]
Hello,
You can close this issue.
I resolved it !

**Comment by sachinprasadhs** [comment]
@DemoLV , Could you please mention what changes solved your issue, if it is a workaround, we can keep this issue open and look at the issue in detail. 
Feel free to close the issue if the issue is not a bug from our end. Thanks!

**Comment by DemoLV** [comment]
Sorry for the late response. I was away.
So basically for now it seems that it was a phone issue. I tested it on newest Xiomi and everything works. 
But could that be true ? 
I have samsung galaxy S9 and it did not work.

**Comment by DemoLV** [comment]
@sachinprasadhs @sushreebarsa @mohantym 
I have an idea on this one. Maybe I can create this simple app "Wake Lock ON" and in this app I choose to press the button wake Lock on and then I open the Tensorflow Lite application and then I can lock the phone and everything will work ? 
Or that will not work as I imagined.

**Comment by sachinprasadhs** [comment]
Since you have already created a new issue on the below point here https://github.com/tensorflow/tensorflow/issues/56261, could you please close this issue and track the below request in the new issue, Thanks!
> @sachinprasadhs @sushreebarsa @mohantym I have an idea on this one. Maybe I can create this simple app "Wake Lock ON" and in this app I choose to press the button wake Lock on and then I open the Tensorflow Lite application and then I can lock the phone and everything will work ? Or that will not work as I imagined.

**Comment by DemoLV** [comment]
So close issue #56260 ? 
Sorry did not quite understand.

**Comment by DemoLV** [comment]
Ok, closing this issue.
Please go to this issue where it is opened #56261 about detecting objects while the phone is locked/sleep.
