### ISSUE TITLE
glibc error with tensorflow 0.10.0

### ISSUE THREAD

**Issue by fjanoos** [tensorflow/tensorflow#5626]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

Glibc import error when using the v0.10.0 distribution of tensorflow

`ImportError: /local/dist/x86_64-unknown-linux-gnu/lib/libc.so.6: version GLIBC_2.14 not found (required by /home/fjanoos/conda/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so)
`

However, the version of glibc visible to python is > 2.15:
```
[19:34 - 1.44][firdaus@gsrs3 27] ~/local/cuda-7.5 >python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.libc_ver()
('glibc', '2.2.5')
>>>
```

### Environment info
Operating System:
Debian 7.8

Installed version of CUDA and cuDNN: 
Cuda 7.5
libcudnn : 5.0

If installed from binary pip package, provide:

1. A link to the pip package you installed:
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0-cp35-cp35m-linux_x86_64.whl

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
Cannot import tensorflow.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by Nessphoro** [comment]
Looking at what you have provided, the glibc version is "2.2.5", which according to https://ftp.gnu.org/gnu/glibc/ was released in 2002.

I've had similar issues on an old RHEL6 box, there is a thread about it with a work around; you basically have to setup an environment by exporting LD_* variables to point to a newer version of GLIBC.

**Comment by fjanoos** [comment]
could you point me to that thread.

**Comment by Nessphoro** [comment]
Sure,

I followed these steps:
http://stackoverflow.com/questions/33655731/error-while-importing-tensorflow-in-python2-7-in-ubuntu-12-04-glibc-2-17-not-f/34897674#34897674

**Comment by gunan** [comment]
Is this issue resolved?
Any objections to closing it?

**Comment by fjanoos** [comment]
no. but please close it anyway. thanks
