### ISSUE TITLE
Detecting objects while android phone is locked/sleep

### ISSUE THREAD

**Issue by DemoLV** [tensorflow/tensorflow#56261]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### OS Platform and Distribution

Windows 10

### Mobile device

Android

### Current Behaviour?

```shell
I want to implement a feature where tensorflow lite is still running and detecting objects while the phone is locked, screen is off. I am using ForeGround service but when I lock the phone, the app is not running.
In the Log it shows that the service is running. But whenever I lock the phone the app does not continue to work.
```

### Standalone code to reproduce the issue

```shell
In the examples app I have created a class MyForegroundService.java
public class MyForegroundService extends Service {
@RequiresApi(api = Build.VERSION_CODES.O)
@Override
public int onStartCommand(Intent intent, int flags, int startId) {
    new Thread(
            new Runnable() {
                @Override
                public void run() {
                    while (true) {
                        Log.e("Service", "Service is running...");
                        try {
                            Thread.sleep(2000);
                        } catch (InterruptedException e) {
                            e.printStackTrace();
                        }
                    }
                }
            }
    ).start();

    final String CHANNELID = "Foreground Service ID";
    NotificationChannel channel = new NotificationChannel(
            CHANNELID,
            CHANNELID,
            NotificationManager.IMPORTANCE_LOW
    );

    getSystemService(NotificationManager.class).createNotificationChannel(channel);
    Notification.Builder notification = new Notification.Builder(this, CHANNELID)
            .setContentText("Service is running")
            .setContentTitle("Service is enabled")
            .setSmallIcon(R.drawable.ic_launcher_background);

    startForeground(1001, notification.build());

    return super.onStartCommand(intent, flags, startId);
}

@Nullable
@Override
public IBinder onBind(Intent intent) {
    return null;
}
}

Then in the file CameraActivity.java, I have added
if(!foregroundServiceRunning()){
  Intent serviceIntent = new Intent(this, MyForegroundService.class); 
  startForegroundService(serviceIntent); 
}
AND
public boolean foregroundServiceRunning(){
ActivityManager activityManager = (ActivityManager) getSystemService(Context.ACTIVITY_SERVICE);
for(ActivityManager.RunningServiceInfo service: activityManager.getRunningServices(Integer.MAX_VALUE)){
    if(MyForegroundService.class.getName().equals(service.service.getClassName())){
      return true;
    }
}
return false;
}

And in the androidmanifest.xml

<uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
<service android:name=".MyForegroundService"></service>
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @DemoLV ! Could you try these below two options too.

1. Enable the usage of the concerned app from Batter management from your android setting.
2. Use Wake Locks to embed in code itself to run even in lock/sleep mode. Ref [1](https://stackoverflow.com/questions/7022879/how-to-keep-android-application-running-in-sleep-mode),[ 2](https://stackoverflow.com/questions/14554616/start-an-activity-even-when-android-phone-is-in-locked-mode-on-lock-screen). 

Thank you!

**Comment by DemoLV** [comment]
Hey !

Thank you very much for the response ! 
By adding these lines of code in CameraActivity.java (line 99) would do the trick ?

getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON
        + WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD|
        + WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED|
        + WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON);

![image](https://user-images.githubusercontent.com/73588489/170432309-13cc4fac-53b3-4ea0-a737-d7b5432fe7a6.png)

**Comment by mohantym** [comment]
Ok @DemoLV ! Thanks for the update. Could we move this issue to closed status then .

**Comment by DemoLV** [comment]
Please, do not close it.
I wanted to know if this trick would work
I will try this and then I will respond to you.

**Comment by DemoLV** [comment]
It looks like this 
![image](https://user-images.githubusercontent.com/73588489/170442896-13a699dc-b1fd-4a2e-b435-7484b1aa42ff.png)
Should I need to add something in the manifest file ? 
![image](https://user-images.githubusercontent.com/73588489/170442997-5e7b855c-5d37-4eb3-9963-93d50b610d9d.png)

**Comment by mohantym** [comment]
@DemoLV ! Did you check the thread on [ wake locks](https://stackoverflow.com/a/7022944) too?

**Comment by DemoLV** [comment]
No I have not checked that. 
But where should I add this instance ?

**Comment by mohantym** [comment]
@DemoLV ! You can refer to this [thread](https://www.youtube.com/watch?v=7Pp3E378JxY) to use Wake locks inside your android app. Thank you!

**Comment by DemoLV** [comment]
Oh, you meant that I create a button inside the Tensorflow lite app and when I click the "Wake Lock" button and then I lock my phone it should still detect . I will try it and give an update !
P.S.
Sorry for the late response

**Comment by mohantym** [comment]
@DemoLV ! Could  you update your issue. Thank you!

**Comment by DemoLV** [comment]
I was doing a research on the wake lock. 
Maybe there is a workaround this feature ? Maybe make the whole screen black ? What I mean by that is, when you open the tensorflow lite app, it just opens a black screen. But it detects the objects. Do you understand what I mean by that ?

**Comment by mohantym** [comment]
Sorry @DemoLV ! for the inconvenience. @sachinprasadhs ! Could you please look at this issue.

**Comment by DemoLV** [comment]
I am very keen on to resolve this issue. Because why not implement these feature when your phone goes dark/locked so it does not drain the battery ? 
So basically the screen is black/locked but you still can detect the objects.

**Comment by DemoLV** [comment]
So a little update. I implemented the WAKE LOCK function, following tutorial here [thread](https://www.youtube.com/watch?v=7Pp3E378JxY). I also put the TFL Detect application in my phone settings as (programms which can not be deactivated) and then pressed the Wake lock ON button in the app but when I lock the phone it still shuts down the application.  Like it does not continue to detect the objects.

**Comment by DemoLV** [comment]
@sachinprasadhs Maybe there are some more people which could be added regarding this issue ?
Thanks !

**Comment by DemoLV** [comment]
Hello guys, new week, new ideas ! 
Is there any update on this ? @Xhark @miaout17 @sachinprasadhs

**Comment by DemoLV** [comment]
Hello again ! 
@Xhark @miaout17 @sachinprasadhs @mohantym maybe you have an update on this ?

**Comment by DemoLV** [comment]
Hello guys !
@Xhark @miaout17 @sachinprasadhs @mohantym maybe you have an update on this ?

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
