### ISSUE TITLE
Getting the bounding box coordinates on tensorflow lite 

### ISSUE THREAD

**Issue by DemoLV** [tensorflow/tensorflow#56262]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### OS Platform and Distribution

Windows 10

### Mobile device

Android

### Current Behaviour?

```shell
I am trying to get the bounding box coordinates of each detected object.
```

### Standalone code to reproduce the issue

```shell
I have created a Hashmap.
From hashmap I am reading the count of the objects.

classCount.put(recognition.title, classCount.get(recognition.title) + 1);

How could I get the bounding box coordinates ?
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @DemoLV ! You can get the bounding box coordinates from the output of 

> vis_util.visualize_boxes_and_labels_on_image_array() 

 . 
Attached are relevant threads for reference. [1](https://stackoverflow.com/a/56660514), [2](https://towardsdatascience.com/using-tensorflow-lite-for-object-detection-2a0283f94aed). Thank you!

**Comment by DemoLV** [comment]
Could you advise on how to implement this code in MultiBoxTracker.java ?
If needed I can send a screenshot on how I get the output of the count of classes on the screen.
Thank you !

**Comment by DemoLV** [comment]
Hello

I resolved this issue, you can close it !

**Comment by mohantym** [comment]
@DemoLV ! Thanks for the update. Moving this issue to closed status then.
