### ISSUE TITLE
TensorArray documentation is misleading

### ISSUE THREAD

**Issue by Rocketknight1** [tensorflow/tensorflow#56272]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

No

### Current Behaviour?

The [documentation for TensorArray](https://www.tensorflow.org/api_docs/python/tf/TensorArray) describes it as "write-once", but this is incorrect. For example, the code below executes fine.

The documentation should be clearer about whether TensorArray is write-once at all, or if this constraint only applies in certain contexts, such as when the user wishes to backprop through it.

### Standalone code to reproduce the issue

```python
array = tf.TensorArray(tf.float32, dynamic_size=False, size=16)
for i in range(16):
    array = array.write(i, 5.)
array = array.write(15, 6.)  # Write to already-written position
print(array.concat())  # Overwriting the last position completed successfully
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
Hi @Rocketknight1,
Kindly, please feel free to submit a PR for the requested change to be made. Thank you!

**Comment by Rocketknight1** [comment]
@tilakrayal Sure thing, will do!

**Comment by Rocketknight1** [comment]
@tilakrayal Is there any source on what the actual limits on `TensorArray` are? In testing it seemed like overwriting the array worked fine, but I don't know if that fails e.g. when you try to backprop. It seems to still work okay in graph mode and XLA. If anyone knows, please tell me! If not, I guess I'll try to figure it out by experimentation and document it.

**Comment by Rocketknight1** [comment]
@cantonios Thank you, that actually clarifies things a lot! But, interestingly, I don't think that has anything to do with `TensorArray` being write-once or not. The reason is that your example would still show the same issue even if you follow the write-once rule and never overwrite any position:

```
x = tf.constant(1, dtype=tf.float32)
ta = tf.TensorArray(dtype=tf.float32, size=2)
ta1 = ta.write(0, x)
ta2 = ta1.write(1, 2*x**2)
v1 = ta1.concat()
v2 = ta2.concat()
print(v1)
print(v2)

# Prints
# tf.Tensor([1. 2.], shape=(2,), dtype=float32)
# tf.Tensor([1. 2.], shape=(2,), dtype=float32)
```

In other words, that suggests the real caveat is not that `TensorArray` is write-once, it's that it's **mutable**, much like a Python `list`. Do you agree, or am I missing something?

**Comment by Rocketknight1** [comment]
@cantonios That makes sense, I think! Would you object if I wrote a PR to clarify that in the documentation?

**Comment by cantonios** [comment]
@Rocketknight1 that would be very appreciated.  I also had to double-check what we meant by that write-once comment, so the documentation is obviously not clear atm.  The limitations should be explicitly spelled out.

Thanks :).
