### ISSUE TITLE
Documentation change for 'Adding a new op ShapeFn'

### ISSUE THREAD

**Issue by gibiansky** [tensorflow/tensorflow#5627]
In [Adding a new Op](https://github.com/tensorflow/tensorflow/blob/7f3d8e1f8736f4c812e4a0a96154af3bd3750180/tensorflow/g3doc/how_tos/adding_an_op/index.md) there is the following line of code that describes how to set the shape function:

```python
@tf.RegisterShape("ZeroOut")(common_shapes.call_cpp_shape_fn)
```
I think this is wrong (you do not want the `@` sign since it's not being used as a decorator). Also, having an explicit import would be helpful.

So it would be nice to change this to:
```python
from tensorflow.python.framework import common_shapes
tf.RegisterShape("ZeroOut")(common_shapes.call_cpp_shape_fn)
```

**Comment by girving** [comment]
@gibiansky Would you be up for sending a PR?

**Comment by vrv** [comment]
We can just remove the line now -- by default all ops call their CPP shape function.  (Or at least, they will with the next push).
