### ISSUE TITLE
Is it possible to view or dump full tensor values in Debugger V2 GUI (in TensorBoard)?

### ISSUE THREAD

**Issue by meghendra** [tensorflow/tensorflow#56277]
I am trying to dump/view intermediate tensor values in a model created using the [TF2 ObjectDetector API](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md) 

I am trying to use the `tf.debugging.experimental.enable_dump_debug_info` for this as follows:
```
import argparse
import sys
import os
import pathlib

import absl
import tensorflow as tf
import numpy as np

from object_detection.builders import model_builder
from object_detection.utils import config_util

tf.debugging.experimental.enable_dump_debug_info(
        './dumpdir',
        tensor_debug_mode='SHAPE',
        circular_buffer_size=-1)
  
model_name = 'ssd_mobilenet_v2_320x320_coco17_tpu-8'
pipeline_config = os.path.join('./TFObjDet/models/research/object_detection/configs/tf2/',
                              model_name + '.config')
model_dir = './TFObjDet/models/research/object_detection/test_data/checkpoint/'
configs = config_util.get_configs_from_pipeline_file(pipeline_config)
model_config = configs['model']
detection_model = model_builder.build(model_config=model_config, is_training=False)

  @tf.function
  def detect_fn(model, image):
    """Detect objects in image."""
    
    image, shapes = model.preprocess(image)
    prediction_dict = model.predict(image, shapes)
    detections = model.postprocess(prediction_dict, shapes)
    
    return detections, prediction_dict, tf.reshape(shapes, [-1])

# Evaluation Step
X = np.ones([1, 320, 320, 3])
image = tf.convert_to_tensor(X, dtype=tf.float32)
detections, predictions_dict, shapes = detect_fn(detection_model, image)
print("Model finished executing")
```

I understand that none of the 5 `tensor_debug_mode` options allow for displaying or dumping tensors produced during the Graph execution. At most we can see the datatype, dimesions, shape and size of these tensors. For example, in the image below, we can see these 4 attributes of the tensor `Postprocessor/Decode/get_center_coordinates_and_sizes/sub_1:0`, (which are: float32 1D shape:[1917]  size:1917) :

![image](https://user-images.githubusercontent.com/4872638/170533762-d4a5f3be-efe4-454c-bac8-ec79bde9706e.png)

I am wondering if it is possible to somehow view or dump the actual value of these tensors, i.e.:

1. Is there a way to view or dump the 1917 numeric values present in the tensor: `Postprocessor/Decode/get_center_coordinates_and_sizes/sub_1:0` ? 
2. Is it  possible to do this using the Debugger V2 and TensorBoard?
3. Is it possible to do this in some other way, without modifying the `object_detection` API code?

https://github.com/tensorflow/tensorflow/blob/d8ce9f9c301d021a69953134185ab728c1c248d3/tensorflow/python/debug/lib/dumping_callback.py#L683-L871

**Comment by sushreebarsa** [comment]
@meghendra Please post this issue on [models](https://github.com/tensorflow/models/issues) repo to get the right help on this. Thank you!
