### ISSUE TITLE
no flatbuffer module errors in source of tensorflow

### ISSUE THREAD

**Issue by FengMu1995** [tensorflow/tensorflow#56271]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf2.8

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### GCC/Compiler version

7.5.0

### Current Behaviour?

```shell
When i use the tf-lite c-api to inference my code, it happened!

.../tensorflow/lite/interpreter_builder.h:26: error: flatbuffers/flatbuffers.h: No such file or directory
 #include "flatbuffers/flatbuffers.h"  // from @flatbuffers
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### Standalone code to reproduce the issue

```shell
I build the tf-lite.so successfully by cmake, but I make sure there is no flatbuffer module in tf2.8 source code， only a cmakeLists.txt, 
as the snapshot
```
![file_image](https://user-images.githubusercontent.com/52693361/170504990-730982ec-e3a7-438a-a361-d38fa8acd4dd.png)

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @FengMu1995 ! Please revert the deletion of the dependencies on Flatbuffer package from Cmakelist.txt  and let us know know .Thank you!

**Comment by FengMu1995** [comment]
Hi, you mean only the [download_dependencies.sh] in the path needs to be recovered? 
![image](https://user-images.githubusercontent.com/52693361/170649619-ca89db52-c96f-4a58-b883-86d1a53b64a4.png)

**Comment by mohantym** [comment]
@FengMu1995 ! Could you share the complete steps you followed along a gist .

**Comment by FengMu1995** [comment]
1. git clone --recursive https://github.com/tensorflow/tensorflow git checkout r2.8
2. cd build
3. cmake ../tensorflow_src/tensorflow/lite
4. cmake --build.-j

**Comment by FengMu1995** [comment]
why not giving a reply

**Comment by sachinprasadhs** [comment]
@FengMu1995 , Apologies for the delayed response, Could you please try again with the master build or with the latest stable release i.e 2.9.1 and let us know if you still face the same issue. Thanks!

**Comment by FengMu1995** [comment]
I've solved the problem by changing the link order of the libraries, the pro was built successfully.

**Comment by sachinprasadhs** [comment]
@FengMu1995 , Glad to hear that your issue is resolved, [here](https://colab.sandbox.google.com/gist/sachinprasadhs/25db573d51c15793a65a79c413a2d643/cmake-build-56271.ipynb) is the Gist which shows the successful CMake build by following the steps in the documentation. 
You can close this issue if your issue is resolved. Thanks!
