### ISSUE TITLE
Leak when using Metal delegate

### ISSUE THREAD

**Issue by w3sip** [tensorflow/tensorflow#56287]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.7.3

### Custom Code

Yes

### OS Platform and Distribution

iOS 15.5

### Mobile device

iPad

### Current Behaviour?

```shell
Whenever we enable Metal delegate, a fast memory leak is observed. Using just CoreML delegate, and the same exact app/code, the memory use is steady.

Most of the leaked memory looks like

_objc_rootAllocWithZone		
-[MTLDebugCommandBuffer computeCommandEncoder]		
0x102775ec8		
0x11379ec3c		
tflite::Subgraph::Invoke()		
tflite::Interpreter::Invoke()		
```

The app is a Swift app, that calls into native C/C++ code. Native C++ threads then run inference calling into TFLite C API.

Any insight into what can be tried is appreciated!
```


### Standalone code to reproduce the issue

```shell
n/a
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @w3sip ! Is this issue replicating in the 2.8/2.9 version too? Could you provide a minimal standalone code to reproduce this issue. Thank you!

**Comment by w3sip** [comment]
@mohantym - can't try 2.9 because of https://github.com/tensorflow/tensorflow/issues/56250 

Considering we're on iOS, providing a standalone sample may end up being a project. Is there a sample/demo project for IOS that could be used for that?

**Comment by w3sip** [comment]
I've been able to test with 2.9.1, definitely leaks there as well.

The growth is very linear, and very rapid -- after ~22,000 inferences, the memory is up close to 1.5GB.

**Comment by sachinprasadhs** [comment]
Could you please check the issue here https://github.com/tensorflow/tensorflow/issues/56239 and let us know if this is relevant to your issue. Thanks!

**Comment by w3sip** [comment]
@sachinprasadhs - most definitely not; we only create the model once upon initialization. The leak seems to originate in TfLiteInterpreterInvoke. 
To remind you, the inferences run in native C++ code/threads, but in context of iOS app. Is that something that is covered by TFLite tests?

**Comment by chendadon** [comment]
any update on this issue? for now we wrap the invoke by @autoreleasepool as work around

**Comment by zhihuiloke** [comment]
Any updates? I can't really use auto release pool as everything is written in C++

**Comment by yishuangP** [comment]
Hi, sorry for the delay. Will take a look asap.

**Comment by trinhtranduc** [comment]
Hi @yishuangP any updates on this?

**Comment by yishuangP** [comment]
Hi, just to clarify, are you using the [MetalDelegate.swift](https://github.com/tensorflow/tensorflow/blob/c68a562ce6faa98680c97e9c8404f8d486656b8d/tensorflow/lite/swift/Sources/MetalDelegate.swift) to initialize the metal delegate?

**Comment by trinhtran-markany** [comment]
@yishuangP , yes, correct!

**Comment by trinhtran-markany** [comment]
@yishuangP I got same issue as explained on this ticket https://github.com/tensorflow/tensorflow/issues/57717 but still not find the right way to fix it!

**Comment by yishuangP** [comment]
Does wrapping TfLiteInterpreterInvoke with autoreleasepool solve the issue? I can add it before we figure out the root cause. Thanks!

**Comment by yishuangP** [comment]
Hi, I just tried the pose estimation example with our latest nightly version 0.0.1-nightly.20230405. I don't see this memory leak issue. Could you try our latest version? Thanks!
