### ISSUE TITLE
Library .so file path Custom Ops using C API

### ISSUE THREAD

**Issue by YogaVicky** [tensorflow/tensorflow#56286]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.8

### Custom Code

Yes

### OS Platform and Distribution

Linux 

### Python version

3.9

### Current Behaviour?

```shell
Where is the .so plugin file for ops.h and kernels.h in C API? I am trying to build custom OP using tensorflow C API's and I am facing compilation issues due to path of the headers.
Where are all the headers located?
```

### Standalone code to reproduce the issue

```shell
#include <stdio.h>
#include <tensorflow/c/c_api.h>
#include "tensorflow/c/kernels.h"x
#include "tensorflow/c/ops.h"
int main() {
  printf("Hello from TensorFlow C library version %s\n", TF_Version());
  return 0;
}
```

### Relevant log output

_No response_</details>

**Comment by sachinprasadhs** [comment]
Hi, Please follow the instructions mentioned [here](https://github.com/tensorflow/custom-op), which explains the path for .so file and the relevant kernel and header files. Thanks!
