### ISSUE TITLE
bazel build tensorflow but failed

### ISSUE THREAD

**Issue by Nullptr65535** [tensorflow/tensorflow#56284]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.10.0

### Custom Code

No

### OS Platform and Distribution

ubuntu 20.04

### Mobile device

none

### Python version

3.6.9

### Bazel version

5.1.1

### GCC/Compiler version

9.3.0

### CUDA/cuDNN version

none

### GPU model and memory

none

### Current Behaviour?

```shell
A bug happened!
I git clone a copy of latest tensorflow. Then I run 
"bazel build -c opt --config=android_arm64   //tensorflow/lite/examples/label_image:label_image"
Then I encounterd some errors.
```

### Standalone code to reproduce the issue

```shell
I didn't make any change to source code.
```

### Relevant log output

```shell
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1f06398e96d4508d22f42b760f70eb5d4e7b1dc9.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://github.com/llvm/llvm-project/archive/1f06398e96d4508d22f42b760f70eb5d4e7b1dc9.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: An error occurred during the fetch of repository 'llvm-raw':
   Traceback (most recent call last):
        File "/home/lvhang/tensorflow/tensorflow/third_party/repo.bzl", line 64, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1f06398e96d4508d22f42b760f70eb5d4e7b1dc9.tar.gz, https://github.com/llvm/llvm-project/archive/1f06398e96d4508d22f42b760f70eb5d4e7b1dc9.tar.gz] to /home/lvhang/.cache/bazel/_bazel_lvhang/ce216ca3f79222179e2eb092d40384de/external/llvm-raw/temp14410369499355690125/1f06398e96d4508d22f42b760f70eb5d4e7b1dc9.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: /home/lvhang/tensorflow/tensorflow/WORKSPACE:11:14: fetching _tf_http_archive rule //external:llvm-raw: Traceback (most recent call last):
        File "/home/lvhang/tensorflow/tensorflow/third_party/repo.bzl", line 64, column 33, in _tf_http_archive_impl
                ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1f06398e96d4508d22f42b760f70eb5d4e7b1dc9.tar.gz, https://github.com/llvm/llvm-project/archive/1f06398e96d4508d22f42b760f70eb5d4e7b1dc9.tar.gz] to /home/lvhang/.cache/bazel/_bazel_lvhang/ce216ca3f79222179e2eb092d40384de/external/llvm-raw/temp14410369499355690125/1f06398e96d4508d22f42b760f70eb5d4e7b1dc9.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: no such package '@llvm-raw//utils/bazel': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/1f06398e96d4508d22f42b760f70eb5d4e7b1dc9.tar.gz, https://github.com/llvm/llvm-project/archive/1f06398e96d4508d22f42b760f70eb5d4e7b1dc9.tar.gz] to /home/lvhang/.cache/bazel/_bazel_lvhang/ce216ca3f79222179e2eb092d40384de/external/llvm-raw/temp14410369499355690125/1f06398e96d4508d22f42b760f70eb5d4e7b1dc9.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
</details>

**Comment by tilakrayal** [comment]
Hi @Nullptr65535,
We see that, you are trying to install the `tensorflow v2.10` with python `3.6.9 `which is not compatible. Could you try to install with `python >= 3.7 `version and let us know if you are facing same issue. Thank you!

**Comment by Nullptr65535** [comment]
Same error comes from XNNPACK after I update python3 to python3.8.10:

Error in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/da533e0114f2bf730f17853ae10556d84a3d1e89.zip, https://github.com/google/XNNPACK/archive/da533e0114f2bf730f17853ae10556d84a3d1e89.zip] to /home/lvhang/.cache/bazel/_bazel_lvhang/2ec6f6b47fb2433fcfdb416cf2581e9b/external/XNNPACK/temp5474243553466178902/da533e0114f2bf730f17853ae10556d84a3d1e89.zip: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: tensorflow/lite/delegates/xnnpack/BUILD:107:11: //tensorflow/lite/delegates/xnnpack:xnnpack_delegate depends on @XNNPACK//:xnnpack_for_tflite in repository @XNNPACK which failed to fetch. no such package '@XNNPACK//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/da533e0114f2bf730f17853ae10556d84a3d1e89.zip, https://github.com/google/XNNPACK/archive/da533e0114f2bf730f17853ae10556d84a3d1e89.zip] to /home/lvhang/.cache/bazel/_bazel_lvhang/2ec6f6b47fb2433fcfdb416cf2581e9b/external/XNNPACK/temp5474243553466178902/da533e0114f2bf730f17853ae10556d84a3d1e89.zip: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by Nullptr65535** [comment]
Some error occur when I update python3 to python3.8.10:

ERROR: /home/lvhang/.cache/bazel/_bazel_lvhang/ce216ca3f79222179e2eb092d40384de/external/cpuinfo/BUILD.bazel:100:11: Compiling src/arm/linux/chipset.c failed: (Exit 1): clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target ... (remaining 50 arguments skipped)
external/cpuinfo/src/arm/linux/chipset.c:330:11: error: implicitly declaring library function 'tolower' with type 'int (int)' [-Werror,-Wimplicit-function-declaration]
                int d = tolower((unsigned char)*a) - tolower((unsigned char)*b);
                        ^
external/cpuinfo/src/arm/linux/chipset.c:330:11: note: include the header <ctype.h> or explicitly provide a declaration for 'tolower'
1 error generated.
Target //tensorflow/lite/examples/label_image:label_image failed to build
Use --verbose_failures to see the command lines of failed build steps.

Maybe #include <ctype.h> is one of solutions, but I don't want to do this.

**Comment by gadagashwini** [comment]
Hi @Nullptr65535, Have you tried the above query after trying the `bazel clean --expunge` command. Can you try once and try repeating the above steps. And also make sure you followed steps mentioned [here](https://www.tensorflow.org/install/source).Thank you!

**Comment by Nullptr65535** [comment]
OK, problem solved, thanks a lot

**Comment by gadagashwini** [comment]
Hi @Nullptr65535, Glad that this issue resolved. Could you move this to closed status. Thank you!
