### ISSUE TITLE
The _get_tensor_details() method was crashed while trying to read a tflite model.

### ISSUE THREAD

**Issue by fatcat-z** [tensorflow/tensorflow#56283]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.1 (v2.9.0-18-gd8ce9f9c301)

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.5 LTS

### Mobile device

Ubuntu 18.04.5 LTS

### Python version

3.8.5

### Current Behaviour?

```shell
A bug happened!

After we construct an tf.lite.Interpreter() with the specified tflite model, we tried to call _get_tensor_details() method to get some tensor details. Just found out it will crash with some specified tflite models.

Please use the code below to reproduce the issue.
```

### Standalone code to reproduce the issue

```shell
import os
import tensorflow as tf

from tf2onnx.tflite.Model import Model

# face_detection_full_range_sparse.tflite could be downloaded from: https://github.com/google/mediapipe/tree/master/mediapipe/modules/face_detection/face_detection_full_range_sparse.tflite
# tflite_path = os.path.join(os.path.dirname(__file__), "face_detection_full_range_sparse.tflite")

# pose_detection.tflite could be downloaded from: https://github.com/google/mediapipe/blob/master/mediapipe/modules/pose_detection/pose_detection.tflite
tflite_path = os.path.join(os.path.dirname(__file__), "pose_detection.tflite")

with open(tflite_path, 'rb') as f:
    buf = f.read()
buf = bytearray(buf)
model = Model.GetRootAsModel(buf, 0)

tensor_shapes = {}
interpreter = tf.lite.Interpreter(tflite_path)
interpreter.allocate_tensors()
tensor_cnt = model.Subgraphs(0).TensorsLength()

try:
    for i in range(tensor_cnt):
        name = model.Subgraphs(0).Tensors(i).Name().decode()
        details = interpreter._get_tensor_details(i)
        print("==== name: ", name)
        if "shape_signature" in details:
            tensor_shapes[name] = details["shape_signature"].tolist()
        elif "shape" in details:
            tensor_shapes[name] = details["shape"].tolist()
except Exception as e:
    print("Error loading model into tflite interpreter: %s", e)

print("End")
```

### Relevant log output

```shell
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
==== name:  input_1
==== name:  model_1/model/zero_padding2d/Pad/paddings
==== name:  model_1/model/zero_padding2d/Pad
==== name:  model_1/model/batch_normalization/FusedBatchNormV3
==== name:  model_1/model/batch_normalization/FusedBatchNormV3_dequantize
==== name:  model_1/model/conv2d/Conv2D
==== name:  model_1/model/conv2d/Conv2D_dequantize
==== name:  model_1/model/re_lu/Relu6;model_1/model/batch_normalization/FusedBatchNormV3;model_1/model/batch_normalization_1/FusedBatchNormV3;model_1/model/depthwise_conv2d/depthwise;model_1/model/regressor_person_16_NO_PRUNING/Conv2D;model_1/model/conv2d/Conv2D
==== name:  model_1/model/batch_normalization_1/FusedBatchNormV3
==== name:  model_1/model/batch_normalization_1/FusedBatchNormV3_dequantize
==== name:  model_1/model/batch_normalization_1/FusedBatchNormV3;model_1/model/depthwise_conv2d/depthwise;model_1/model/regressor_person_16_NO_PRUNING/Conv2D
==== name:  model_1/model/batch_normalization_1/FusedBatchNormV3;model_1/model/depthwise_conv2d/depthwise;model_1/model/regressor_person_16_NO_PRUNING/Conv2D_dequantize
==== name:  model_1/model/re_lu_1/Relu6;model_1/model/batch_normalization_1/FusedBatchNormV3;model_1/model/depthwise_conv2d/depthwise;model_1/model/regressor_person_16_NO_PRUNING/Conv2D
==== name:  model_1/model/batch_normalization_2/FusedBatchNormV3;model_1/model/conv2d_1/Conv2D
==== name:  model_1/model/batch_normalization_2/FusedBatchNormV3;model_1/model/conv2d_1/Conv2D_dequantize
Segmentation fault (core dumped)
```
</details>

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you look at this issue. Attached[ 2.8](https://colab.sandbox.google.com/gist/mohantym/958477eb70fcaf151bc60f42dd433ae8/git_56283.ipynb#scrollTo=L6x5ei7Uqnvx), [2.9](https://colab.sandbox.google.com/gist/mohantym/d9c3d055c4c0f05a04bfb900440b8baf/git_56283.ipynb#scrollTo=-h8sT5usKKfr) and [nightly ](https://colab.sandbox.google.com/gist/mohantym/9ca10315e75a0d1b6de8b87819008e52/git_56283.ipynb#scrollTo=v5L-fx40pu_U)for reference. Thank you!

**Comment by sachinprasadhs** [comment]
for `get_tensor_details` method, the tensors has to be valid tensor details. 
Tensors where required information about the tensor is not found are not added to the list. This includes temporary tensors without a name.

**Comment by fatcat-z** [comment]
> for `get_tensor_details` method, the tensors has to be valid tensor details. Tensors where required information about the tensor is not found are not added to the list. This includes temporary tensors without a name.

Do you mean the data in attached tflite models are incomplete?

**Comment by mohantym** [comment]
@fatcat-z ! @sachinprasadhs !

I am able to replicate this issue in  [2.11 version](https://colab.sandbox.google.com/gist/mohantym/b0ebebe4cef057beec652343e156d425/git_56283.ipynb#scrollTo=v5L-fx40pu_U) too.

Thank you!

**Comment by lubagov** [comment]
Yes... 2.12 and in last night builds too... It's the same problem with sparse tensors.

At all, in this line: https://github.com/tensorflow/tensorflow/blob/0010d29d742350048206a312d485ee1245522f2b/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc#L135 `param.block_map` is `nullptr`. When it tries to resolve it, a `segmentation fault` is happened. 
here i can read https://github.com/tensorflow/tensorflow/blob/0010d29d742350048206a312d485ee1245522f2b/tensorflow/lite/schema/schema.fbs#L184

> For an n-dimensional tensor with a k-dimensional block (0 <= k <= n), stores how a block dimension in (dn, ..., dn+k-1) maps to the original tensor dimension in (d0, ..., dn).  It's stored in the order of (dn, ..., dn+k-1). **If not block-sparse, this field is NULL.**

I don't quite understand how this works, but seems it's likely that this parameter could be NULL. Which will lead to the fall...
I try to fix it this way:
```
diff --git a/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc b/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc
index 488b7cee079..2c38ec429b1 100644
--- a/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc
+++ b/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc
@@ -132,9 +132,15 @@ PyObject* PyDictFromSparsityParam(const TfLiteSparsity& param) {
   PyDict_SetItemString(result, "traversal_order",
                        PyArrayFromIntVector(param.traversal_order->data,
                                             param.traversal_order->size));
-  PyDict_SetItemString(
-      result, "block_map",
-      PyArrayFromIntVector(param.block_map->data, param.block_map->size));
+
+  if(param.block_map!=nullptr){
+     PyDict_SetItemString(
+         result, "block_map",
+         PyArrayFromIntVector(param.block_map->data, param.block_map->size));
+  }else{
+     PyDict_SetItemString(result, "block_map", PyArrayFromIntVector(nullptr,0));
+  }
+
   PyObject* dim_metadata = PyList_New(param.dim_metadata_size);
   for (int i = 0; i < param.dim_metadata_size; i++) {
     PyObject* dim_metadata_i = PyDict_New();
```

Now I no longer have, a segmentation fault crash. However, the converter to ONNX did not start working:
```
Traceback (most recent call last):
  File "/home/buldonnx/.conda/envs/condatest/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/buldonnx/.conda/envs/condatest/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/buldonnx/.conda/envs/condatest/lib/python3.10/site-packages/tf2onnx/convert.py", line 706, in <module>
    main()
  File "/home/buldonnx/.conda/envs/condatest/lib/python3.10/site-packages/tf2onnx/convert.py", line 269, in main
    model_proto, _ = _convert_common(
  File "/home/buldonnx/.conda/envs/condatest/lib/python3.10/site-packages/tf2onnx/convert.py", line 164, in _convert_common
    g = process_tf_graph(tf_graph, const_node_values=const_node_values,
  File "/home/buldonnx/.conda/envs/condatest/lib/python3.10/site-packages/tf2onnx/tfonnx.py", line 453, in process_tf_graph
    main_g, subgraphs = graphs_from_tflite(tflite_path, input_names, output_names)
  File "/home/buldonnx/.conda/envs/condatest/lib/python3.10/site-packages/tf2onnx/tflite_utils.py", line 153, in graphs_from_tflite
    parse_tflite_graph(tfl_graph, opcodes, model, prefix, tensor_shapes_from_interpreter)
  File "/home/buldonnx/.conda/envs/condatest/lib/python3.10/site-packages/tf2onnx/tflite_utils.py", line 355, in parse_tflite_graph
    np_data = tensor_util.MakeNdarray(t)
  File "/home/buldonnx/.local/lib/python3.10/site-packages/tensorflow/python/framework/tensor_util.py", line 663, in MakeNdarray
    dtype=dtype).copy().reshape(shape))
ValueError: cannot reshape array of size 96 into shape (16,1,1,24)
```
So far, I do not understand how it works, and what is happening here... I will look later.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

**Comment by pkgoogle** [comment]
Hi @fatcat-z,

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress [here](https://github.com/google-ai-edge/LiteRT/issues/131).

Let us know if you have any questions. Thanks.
