### ISSUE TITLE
Import Locally Cause Resource Leak

### ISSUE THREAD

**Issue by Johnson9009** [tensorflow/tensorflow#56290]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.6.3

### Custom Code

No

### OS Platform and Distribution

X86 linux

### Python version

3.8

### Current Behaviour?

```shell
When the tensorflow is imported locally in a function, it seems the traceback will be stored in tensorflow, and the local variable is not released after the function exit, we found this issue in our RPC test case, it will cause the connection timeout actually the job is already completed.
```

### Standalone code to reproduce the issue

```shell
class A:
    def __init__(self, name):
        self._name = name
    def __del__(self):
        print(f"A obj {self._name} is delete")


def _run_rpc():
    a = A("a")
    import tensorflow
    b = A("b")


if __name__ == "__main__":
    _run_rpc()
    print("another start.")
```

### Relevant log output

```shell
another start.
A obj a is delete
A obj b is delete

The expect ouput:
A obj a is delete
A obj b is delete
another start.
```
</details>

**Comment by tilakrayal** [comment]
@Johnson9009,
I was able to execute the given code without any issues and the result was as expected. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/58a994f67a12b392b714ea511765c277/56290.ipynb).

**Comment by Johnson9009** [comment]
@tilakrayal Thanks for investigate it, I run your gist on colab, I don't know why it behave normally on colab, but I test it on our red hat 7 server, windows WSL2(ubuntu18.04), docker container, all of them can get the wrong output.
Is the colab environment import the tensorflow package ahead?

**Comment by Johnson9009** [comment]
By the way, the python version your gist is 3.7, but I found this issue when the python version is 3.8, can you help to check it using python3.8? Thanks.

**Comment by tilakrayal** [comment]
@Johnson9009,
I tried with python version3.8 and tensorflow v2.8,  and was able to execute the given code without any issues and the result was the same. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/439c566994e93178092d55c3890c1f68/untitled383.ipynb). Thank you!
