### ISSUE TITLE
Error in Ragged Tensor Documentation

### ISSUE THREAD

**Issue by aflah02** [tensorflow/tensorflow#56292]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

2.9

### Custom Code

No

### Current Behaviour?

```shell
When I run the example in the doc to create a RaggedTensor t4 with shape [3, None, 4, 8, None, 2] I get an error
```

### Standalone code to reproduce the issue

```shell
t0 = tf.zeros([1000, 2])                           # Shape:         [1000, 2]
t1 = RaggedTensor.from_row_lengths(t0, [...])      #           [160, None, 2]
t2 = RaggedTensor.from_uniform_row_length(t1, 8)   #         [20, 8, None, 2]
t3 = RaggedTensor.from_uniform_row_length(t2, 4)   #       [5, 4, 8, None, 2]
t4 = RaggedTensor.from_row_lengths(t3, [...])      # [3, None, 4, 8, None, 2]
```
```


### Relevant log output


ValueError: Attempt to convert a value (Ellipsis) with an unsupported type (<class 'ellipsis'>) to a Tensor.

</details>

**Comment by tilakrayal** [comment]
Hi @aflah02,
Kindly feel free to submit a PR for the requested change or share the link where requested change is to be made. Thank you!

**Comment by aflah02** [comment]
Hey @tilakrayal The error is on this page - https://www.tensorflow.org/api_docs/python/tf/RaggedTensor
I'm a bit busy would be great if someone else can take up the fix!

**Comment by tilakrayal** [comment]
@aflah02,
Kindly feel free to submit a PR for the requested change to be made. Thank you!

**Comment by gadagashwini** [comment]
Hi @aflah02, Tf.RaggedTensor does take take argument in the form `[...]`. As error says Ellipsis are unsupported.
Argument `row_lengths` from `tf.RaggedTensor.from_row_lengths` takes A 1-D integer tensor with shape [nrows]. Must be nonnegative. sum(row_lengths) must be nvals.

```
Working sample code
import tensorflow as tf
t0 = tf.constant([3, 1, 4, 1, 5, 9, 2, 6])                          
t1 = tf.RaggedTensor.from_row_lengths(t0, row_lengths=[4, 0, 3, 1, 0])
t2 = tf.RaggedTensor.from_uniform_row_length(t1, 5)   
t3 = tf.RaggedTensor.from_uniform_row_length(t2, 1)
```
**Output**
`<tf.RaggedTensor [[[[3, 1, 4, 1], [], [5, 9, 2], [6], []]]]>`

**Comment by aflah02** [comment]
Ohhh this makes sense @gadagashwini 
Thanks a lot

**Comment by gadagashwini** [comment]
Hi @aflah02, Glad that it helps. Can we close this issue. Thank you!

**Comment by aflah02** [comment]
@gadagashwini Yeah sure closing it
