### ISSUE TITLE
tf.data shard malfunction (drops data) when using from_generator as source

### ISSUE THREAD

**Issue by Daniel595** [tensorflow/tensorflow#56306]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.8.0-rc1-32-g3f878cff5b6 2.8.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8.10

### CUDA/cuDNN version

CUDA 11.6 / cuDNN 8.3.2 (using 22.02 TensorRT NGC container)

### GPU model and memory

Quadro RTX 4000 8GB

### Current Behaviour?

For prediction pipelines I am using tf.data.Dataset fed from queues by using from_generator. I chose this way since I get data from queues and I want the dataset never to terminate.

I need to shard datasets to feed parallel prediction instances and tried using the shard function. It does not work as expected when using from_generator as source. It drops some data and fails with indices. 
It works perfectly fine when using e.g. from_tensor_slices or range to define the dataset.

Minimal example in colab: https://colab.research.google.com/drive/18SLBxl2Qws1GdA7YJ9GOI8DyPNgv_LTn?usp=sharing

I am currently working around this by extracting the tf.data.Dataset and putting it into multiple queues to manually shard and putting it back into tf.data.Dataset - this works but feels very wrong and produces overhead as I assume.

Is this behaviour desired? 
Am I maybe missing something?
Are there other solutions getting infinite Datasets from Queue with shard working?
Would appreciate some help 

### Standalone code to reproduce the issue

```python
import time
from threading import Thread
from queue import Queue
import tensorflow as tf

# Helper function
def iter_data(ds, prefix):
    for data in ds.as_numpy_iterator():
        print(f'{prefix}: {data}')
        

############################################
########## Works as expected ###############
############################################
time.sleep(.1)
print('\nSharding from range as source')

# define dataset
ds = tf.data.Dataset.range(10)
# ds.map(...) # Some processing ...

# shard dataset
ds_even = ds.shard(2, 0)
ds_odd = ds.shard(2, 1)

# extract dataset
t1 = Thread(target=iter_data, args=(ds_even,'even from range'), daemon=True)
t2 = Thread(target=iter_data, args=(ds_odd,'odd from range'), daemon=True)
t1.start()
t2.start()
time.sleep(1)


############################################
########## Works as expected ###############
############################################
time.sleep(.1)
print('\nSharding from from_tensor_slices as source')

# define dataset
ds = tf.data.Dataset.from_tensor_slices(list(range(10)))
# ds.map(...) # Some processing ...

# shard
ds_even = ds.shard(2, 0)
ds_odd = ds.shard(2, 1)

# extract
t1 = Thread(target=iter_data, args=(ds_even,'even from tensor'), daemon=True)
t2 = Thread(target=iter_data, args=(ds_odd,'odd from tensor'), daemon=True)
t1.start()
t2.start()
time.sleep(1)


############################################
########## Some data will be ommited #######
############################################

# create Queue source and fill it with elements as above
q_src = Queue()
for i in range(10):
    q_src.put(i)

# define generator function to bring the queue into tf Dataset
def get_q_gen(q):
    def q_gen():
        while True:
            yield q.get()
    return q_gen
 
# define dataset
ds = tf.data.Dataset.from_generator(get_q_gen(q_src), output_signature=(tf.TensorSpec((None), dtype=tf.int32)))
# ds.map(...) # Some processing ...

# shard - Not working as expected
ds_even = ds.shard(2, 0)
ds_odd = ds.shard(2, 1)

print('\nSharding from generator as source')

# extract
t1 = Thread(target=iter_data, args=(ds_even,'even from gen'), daemon=True)
t2 = Thread(target=iter_data, args=(ds_odd,'odd from gen'), daemon=True)
t1.start()
t2.start()
time.sleep(1)



############################################
########## My currently used workaround ####
############################################

q_src = Queue()
for i in range(10):
    q_src.put(i)
        
ds = tf.data.Dataset.from_generator(get_q_gen(q_src), output_signature=(tf.TensorSpec((None), dtype=tf.int32)))
# ds.map(...) # Some processing ...

# workaround - manually sharding dataset into multiple queues
def to_queue(ds:tf.data.Dataset, queues):
    for i, data in enumerate(ds.as_numpy_iterator()):
        q = queues[i%len(queues)]
        q.put(data)

q1, q2 = Queue(), Queue()
t0 = Thread(target=to_queue, args=(ds, [q1, q2]), daemon=True)
t0.start()

# sharded dataset from queues
ds_even = tf.data.Dataset.from_generator(get_q_gen(q1), output_signature=(tf.TensorSpec((None), dtype=tf.int32)))
ds_odd = tf.data.Dataset.from_generator(get_q_gen(q2), output_signature=(tf.TensorSpec((None), dtype=tf.int32)))

print('\nWorkaround')

t1 = Thread(target=iter_data, args=(ds_even,'even from gen'), daemon=True)
t2 = Thread(target=iter_data, args=(ds_odd,'odd from gen'), daemon=True)
t1.start()
t2.start()
time.sleep(1)

```

### Relevant log output

Sharding from range as source
even from range: 0
even from range: 2
odd from range: 1
even from range: 4
odd from range: 3
even from range: 6
odd from range: 5
odd from range: 7
even from range: 8
odd from range: 9

Sharding from from_tensor_slices as source
even from tensor: 0
odd from tensor: 1
even from tensor: 2
odd from tensor: 3
odd from tensor: 5
odd from tensor: 7
even from tensor: 4
odd from tensor: 9
even from tensor: 6
even from tensor: 8

Sharding from generator as source
even from gen: 0
odd from gen: 2
even from gen: 4
odd from gen: 6
odd from gen: 9

Workaround
odd from gen: 1
even from gen: 0
odd from gen: 3
even from gen: 2
odd from gen: 5
even from gen: 4
even from gen: 6
odd from gen: 7
even from gen: 8
odd from gen: 9

</details>

**Comment by tilakrayal** [comment]
Hi @Daniel595,
From the `tf.data` side, it is expected that the cardinality of `Dataset.from_generator()` is [unknown](https://www.tensorflow.org/api_docs/python/tf/data/experimental#UNKNOWN_CARDINALITY). There's isn't a good way to determine how much data a given generator will produce. 
The generator could be infinite or produce random amounts of data. Thank you!

**Comment by Daniel595** [comment]
@tilakrayal Thank you for the quick response. 

So, just to make sure - it is not expected that `shard` will work correctly for datasets generated by `Dataset.from_generator()`?

Could you then maybe imagine a way of feeding a dataset from a Queue which contigously supplies images where the cardinality is not unknown? 
The final amount of images the Queue will deliver could be known but the data will be only available during runtime. This excludes defining the dataset by something like `from_tensors()`, doesn't it?

Thanks for the help!

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.8, [v2.9](https://colab.research.google.com/gist/tilakrayal/19ae4aa67e9bd80e45a48c655645c724/2-9-56306.ipynb) and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/9b57fa41123123a3c8a1cadfc8c04ebe/2-8-56306.ipynb).

**Comment by aaudiber** [comment]
The [official docs](https://www.tensorflow.org/api_docs/python/tf/data/Dataset?version=nightly#shard) for `shard` say

> Creates a Dataset that includes only 1/num_shards of this dataset.
>
> shard is deterministic. The Dataset produced by A.shard(n, i) will contain all elements of A whose index mod n = i.

Shard doesn't partition a dataset -- rather it reads all the elements from the dataset and drops all but  `1/num_shards` of them. `shard` may be used to partition a dataset **if the dataset can be deterministically iterated through multiple times**. Each `.shard(num_shards, i)` transformation will read its entire input dataset and return only the part of the dataset that belongs to the specified "shard".

In your case, the dataset created by `from_generator` is not deterministic since all iterations share the same Queue. That is why shard isn't working as you expected.

Your workaround is reasonable and I wouldn't expect it to add a detectable amount of overhead. Alternatively, you could consider using a single (unsharded) dataset, and having prediction instances all pull from the same iterator over that dataset. That would result in processing every element exactly once, though it wouldn't be deterministic which thread processes which element.

```python
dataset = ...
iterator = dataset.as_numpy_iterator()

def process_data(iterator):
  for elem in iterator:
    print(elem)

t1 = Thread(target=process_data, args=(iterator), daemon=True)
t2 = Thread(target=process_data, args=(iterator), daemon=True)
t1.start()
t2.start()
```

**Comment by Daniel595** [comment]
Thank you for the good explanations. I think I slightly unterstood the idea. 
In my mind `shard` would have partitioning the dataset by kind of a counter logic or something like that. Reading all elements first actually seems unintuitive to me.

I guess there could be a couple of methods more not working as expected on non deterministic datasets, like `concatenate`. I can imagine that cases like this are common pitfalls for developers and believe now that non deterministic datasets are kind of restricted. Maybe if there aren't some cases where this behaviour could be required, some warnings/errors could help here.

In the minimal example I don't expect a detectable overhead by the workaround either. In my real application I put back the prediction data into datasets. My entire datapipeline uses `as_numpy_iterator()` and `from_generator()` about 10 times or so and I once read instanciation of `Dataset` is quite some overhead.

Your example seems to be usefull to optimize througput. I'll keep that in mind. 
I have 4 parallel instances each expecting to get elements with their indices (0-3) from the queue. My newest approach is to get the 4 elements zipped and run the prediction mapping a numpy_function wrapping the model prediction. This saves me all those custom 'cuts' and right now seems to perform better than the Thread/Queue approaches. 

```python
def pred0(x):
        return tf.numpy_function(model1.predict, [x[0]], tf.float32), *x[1:]
# def pred...
ds_pred = ds_prep.map(lambda a, b, c, d: (pred0(a), pred1(b), pred2(c), pred3(d)), AUTOTUNE)
```

I have no idea if and how AUTOTUNE takes any effect here. The single prediction instances are getting very unbalanced workload (1/12/48). But I think it doesn't really matter, since I have to gather the 4 prediction results for postprocessing anyway.

Anyway, thanks a lot for the help and for resolving my issue!
