### ISSUE TITLE
Tflite model not work correctly on NNAPI-GPU delegate

### ISSUE THREAD

**Issue by francescoyou97** [tensorflow/tensorflow#56301]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.5, 2.6

### Custom Code

Yes

### OS Platform and Distribution

Windows 11

### Mobile device

Huawei Mate 10 Pro

### Python version

3.6.0

### CUDA/cuDNN version

Non disponibile 

### Current Behaviour?

```shell
I have converted a GRU or LSTM based RNN model to TFLite. But I have some issues with using NNAPI delegate on GPU and GPU delegate when using model on device.

In particular I cannot use the GPU for all the operations of the Model Graph, although all the operations (Reshape and LSTM layer)are actually supported as indicated at this link:

https://www.tensorflow.org/lite/performance/gpu_advanced

I tested this working using the apk I downloaded from this page:

https://www.tensorflow.org/lite/performance/measurement

both the "nightly pre-built" version and the version that support TF ops via Flex delegate.

I have experimented with different conversion options such as:
- converter.representative_dataset = representative_data_gen
- converter.experimental_new_quantizer = True
- converter.experimental_enable_resource_variables = True


I expect that if the LSTM, Reshape and Dense layers are usable on GPU, it is possible to use NNAPI delegates on GPU and GPU.
```

### Standalone code to reproduce the issue

```shell
import os
import numpy as np
import tensorflow as tf


def representative_data_gen():
    for input_value in tf.data.Dataset.from_tensor_slices(X_train).batch(1).take(X_train.shape[0]):
    # Model has only one input so each data point has one element.
        yield [input_value]


training = ""
model_save_path = ""

X_train = np.loadtxt(training, delimiter=',', dtype='float32', usecols=list(range(1, (21 * 3 * 2 * 21) + 1)))
y_train = np.loadtxt(training, delimiter=',', dtype='int32', usecols=(0))
    
model = tf.keras.models.Sequential([                            
          tf.keras.layers.InputLayer(input_shape=(21 * 3 * 2 * 21, )),
          tf.keras.layers.Reshape((21, 3 * 2 * 21)),        
          tf.keras.layers.LSTM(8, return_sequences=True, unroll=True),
          tf.keras.layers.Dropout(0.40, seed=42),
          tf.keras.layers.LSTM(8, unroll=True),        
          tf.keras.layers.Dropout(0.50, seed=42),             
          tf.keras.layers.Dense(27, activation='softmax')])    
               
           
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=256,
)

model.save(model_save_path, include_optimizer=False)   
model = tf.keras.models.load_model(model_save_path)

run_model = tf.function(lambda x: model(x))
concrete_func = run_model.get_concrete_function(tf.TensorSpec([1, model.inputs[0].shape[1]], model.inputs[0].dtype))

converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])  
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
#converter.representative_dataset = representative_data_gen
converter.experimental_new_quantizer = True
converter.experimental_enable_resource_variables = True
converter.allow_custom_ops = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tflite_quantized_model = converter.convert()


open("", 'wb').write(tflite_quantized_model)

interpreter = tf.lite.Interpreter(model_path="")
interpreter.allocate_tensors()
```

### Relevant log output

```shell
With tf 2.5 without rappresentative dataset

05-30 13:04:37.451 25935 25935 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/model.tflite --warmup_runs=1 --num_runs=50 --enable_op_profiling=true --use_xnnpack=false --use_nnapi=true
05-30 13:04:37.455 25935 25935 I tflite  : Log parameter values verbosely: [0]
05-30 13:04:37.455 25935 25935 I tflite  : Min num runs: [50]
05-30 13:04:37.455 25935 25935 I tflite  : Min warmup runs: [1]
05-30 13:04:37.455 25935 25935 I tflite  : Graph: [/data/local/tmp/model.tflite]
05-30 13:04:37.455 25935 25935 I tflite  : Enable op profiling: [1]
05-30 13:04:37.455 25935 25935 I tflite  : Use NNAPI: [1]
05-30 13:04:37.460 25935 25935 I tflite  : NNAPI accelerators available: [ipuadaptor,nnapi-reference]
05-30 13:04:37.460 25935 25935 I tflite  : Use xnnpack: [0]
05-30 13:04:37.460 25935 25935 I tflite  : Loaded model /data/local/tmp/model.tflite
05-30 13:04:37.460 25935 25935 I tflite  : Initialized TensorFlow Lite runtime.
05-30 13:04:37.462 25935 25935 I tflite  : Created TensorFlow Lite delegate for NNAPI.
05-30 13:04:37.462 25935 25935 I tflite  : NNAPI delegate created.
05-30 13:04:37.516 25935 25935 I tflite  : Though NNAPI delegate is explicitly applied, the model graph will not be executed by the delegate.
05-30 13:04:37.516 25935 25935 I tflite  : The input model file size (MB): 0.141312
05-30 13:04:37.516 25935 25935 I tflite  : Initialized session in 56.16ms.
05-30 13:04:37.519 25935 25935 I tflite  : Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
05-30 13:04:38.019 25935 25935 I tflite  : count=1156 first=4645 curr=433 min=424 max=4645 avg=431.215 std=124
05-30 13:04:38.019 25935 25935 I tflite  : Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
05-30 13:04:39.020 25935 25935 I tflite  : count=586 first=564 curr=522 min=515 max=949 avg=520.706 std=27
05-30 13:04:39.021 25935 25935 I tflite  : Inference timings in us: Init: 56160, First inference: 4645, Warmup (avg): 431.215, Inference (avg): 520.706
05-30 13:04:39.021 25935 25935 I tflite  : Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
05-30 13:04:39.021 25935 25935 I tflite  : Memory footprint delta from the start of the tool (MB): init=2.03516 overall=2.03516
05-30 13:04:39.021 25935 25935 I tflite  : Profiling Info for Benchmark Initialization:
05-30 13:04:39.021 25935 25935 I tflite  : ============================== Run Order ==============================
05-30 13:04:39.021 25935 25935 I tflite  :                   [node type]          [first]        [avg ms]            [%]          [cdf%]          [mem KB] [times called]   [Name]
05-30 13:04:39.021 25935 25935 I tflite  :       ModifyGraphWithDelegate           54.571          54.571        95.055%         95.055%          1132.000         1        ModifyGraphWithDelegate/0
05-30 13:04:39.021 25935 25935 I tflite  :               AllocateTensors            2.833           1.419         4.945%        100.000%             0.000         2        AllocateTensors/0
05-30 13:04:39.021 25935 25935 I tflite  :
05-30 13:04:39.021 25935 25935 I tflite  : ============================== Top by Computation Time ==============================
05-30 13:04:39.021 25935 25935 I tflite  :                   [node type]          [first]        [avg ms]            [%]          [cdf%]          [mem KB] [times called]   [Name]
05-30 13:04:39.021 25935 25935 I tflite  :       ModifyGraphWithDelegate           54.571          54.571        95.055%         95.055%          1132.000         1        ModifyGraphWithDelegate/0
05-30 13:04:39.021 25935 25935 I tflite  :               AllocateTensors            2.833           1.419         4.945%        100.000%             0.000         2        AllocateTensors/0
05-30 13:04:39.021 25935 25935 I tflite  :
05-30 13:04:39.021 25935 25935 I tflite  : Number of nodes executed: 2
05-30 13:04:39.021 25935 25935 I tflite  : ============================== Summary by node type ==============================
05-30 13:04:39.021 25935 25935 I tflite  :                   [Node type]          [count]         [avg ms]          [avg %]         [cdf %]       [mem KB] [ti
05-30 13:04:39.026 25935 25935 I tflite  : Operator-wise Profiling Info for Regular Benchmark Runs:
05-30 13:04:39.026 25935 25935 I tflite  : ============================== Run Order ==============================
05-30 13:04:39.026 25935 25935 I tflite  :                   [node type]          [first]        [avg ms]            [%]          [cdf%]          [mem KB] [times called]   [Name]
05-30 13:04:39.026 25935 25935 I tflite  :                       RESHAPE            0.001           0.001         0.264%          0.264%             0.000         1        [sequential/lstm/transpose1]:0
05-30 13:04:39.026 25935 25935 I tflite  :                        UNPACK            0.004           0.003         0.651%          0.915%             0.000         1        [sequential/lstm/unstack, sequential/lstm/unstack1, sequential/lstm/unstack2, sequential/lstm/unstack3, sequential/lstm/unstack4, sequential/lstm/unstack5, sequential/lstm/unstack6, sequential/lstm/unstack7, sequential/lstm/unstack8, sequential/lstm/unstack9, sequential/lstm/unstack10, sequential/lstm/unstack11, sequential/lstm/unstack12, sequential/lstm/unstack13, sequential/lstm/unstack14, sequential/lstm/unstack15, sequential/lstm/unstack16, sequential/lstm/unstack17, sequential/lstm/unstack18, sequential/lstm/unstack19, sequential/lstm/unstack20]:1
05-30 13:04:39.026 25935 25935 I tflite  :               FULLY_CONNECTED            0.008

========================================================================================================
========================================================================================================
========================================================================================================
========================================================================================================
========================================================================================================
With tf 2.6.x and full-integer quantization(rappresentative dataset)

05-30 15:16:44.706  3380  3380 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/model.tflite --warmup_runs=1 --num_runs=50 --enable_op_profiling=true --use_xnnpack=false --use_nnapi=true --disable_nnapi_cpu=false
05-30 15:16:44.719  3380  3380 I tflite  : Log parameter values verbosely: [0]
05-30 15:16:44.719  3380  3380 I tflite  : Min num runs: [50]
05-30 15:16:44.719  3380  3380 I tflite  : Min warmup runs: [1]
05-30 15:16:44.719  3380  3380 I tflite  : Graph: [/data/local/tmp/model.tflite]
05-30 15:16:44.719  3380  3380 I tflite  : Enable op profiling: [1]
05-30 15:16:44.720  3380  3380 I tflite  : Use NNAPI: [1]
05-30 15:16:44.731  3380  3380 I tflite  : NNAPI accelerators available: [ipuadaptor,nnapi-reference]
05-30 15:16:44.731  3380  3380 I tflite  : Disable NNAPI cpu: [0]
05-30 15:16:44.731  3380  3380 I tflite  : Use xnnpack: [0]
05-30 15:16:44.732  3380  3380 I tflite  : Loaded model /data/local/tmp/model.tflite
05-30 15:16:44.733  3380  3380 I tflite  : Initialized TensorFlow Lite runtime.
05-30 15:16:44.737  3380  3380 I tflite  : Created TensorFlow Lite delegate for NNAPI.
05-30 15:16:44.737  3380  3380 I tflite  : NNAPI delegate created.
05-30 15:16:44.748  3380  3380 I tflite  : Replacing 504 node(s) with delegate (TfLiteNnapiDelegate) node, yielding 87 partitions.
05-30 15:16:44.857  3380  3380 I tflite  : Explicitly applied NNAPI delegate, and the model graph will be partially executed by the delegate w/ 44 delegate kernels.
05-30 15:16:44.858  3380  3380 I tflite  : The input model file size (MB): 0.113392
05-30 15:16:44.858  3380  3380 I tflite  : Initialized session in 126.059ms.
05-30 15:16:44.858  3380  3380 I tflite  : Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
05-30 15:16:45.362  3380  3380 I tflite  : count=40 first=32942 curr=12594 min=11340 max=32942 avg=12581.9 std=3331
05-30 15:16:45.362  3380  3380 I tflite  : Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
05-30 15:16:46.365  3380  3380 I tflite  : count=75 first=12840 curr=11853 min=11787 max=13649 avg=12167.6 std=325
05-30 15:16:46.366  3380  3380 I tflite  : Inference timings in us: Init: 126059, First inference: 32942, Warmup (avg): 12581.9, Inference (avg): 12167.6
05-30 15:16:46.366  3380  3380 I tflite  : Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
05-30 15:16:46.366  3380  3380 I tflite  : Memory footprint delta from the start of the tool (MB): init=2.01562 overall=4.23438
05-30 15:16:46.366  3380  3380 I tflite  : Profiling Info for Benchmark Initialization:
05-30 15:16:46.366  3380  3380 I tflite  : ============================== Run Order ==============================
05-30 15:16:46.366  3380  3380 I tflite  :                   [node type]          [first]        [avg ms]            [%]          [cdf%]          [mem KB] [times called]   [Name]
05-30 15:16:46.366  3380  3380 I tflite  :       ModifyGraphWithDelegate          119.932         119.932        63.300%         63.300%          1116.000         1        ModifyGraphWithDelegate/0
05-30 15:16:46.366  3380  3380 I tflite  :               AllocateTensors           69.517          34.767        36.700%        100.000%             0.000         2        AllocateTensors/0
05-30 15:16:46.366  3380  3380 I tflite  :
05-30 15:16:46.366  3380  3380 I tflite  : ============================== Top by Computation Time ==============================
05-30 15:16:46.366  3380  3380 I tflite  :                   [node type]          [first]        [avg ms]            [%]          [cdf%]          [mem KB] [times called]   [Name]
05-30 15:16:46.366  3380  3380 I tflite  :       ModifyGraphWithDelegate          119.932         119.932        63.300%         63.300%          1116.000         1        ModifyGraphWithDelegate/0
05-30 15:16:46.366  3380  3380 I tflite  :               AllocateTensors           69.517          34.767        36.700%        100.000%             0.000         2        AllocateTensors/0
05-30 15:16:46.366  3380  3380 I tflite  :
05-30 15:16:46.366  3380  3380 I tflite  : Number of nodes executed: 2
05-30 15:16:46.366  3380  3380 I tflite  : ============================== Summary by node type ==============================
05-30 15:16:46.366  3380  3380 I tflite  :                   [Node type]          [count]         [avg ms]          [avg %]         [cdf %]       [mem KB] [ti
05-30 15:16:46.370  3380  3380 I tflite  : Operator-wise Profiling Info for Regular Benchmark Runs:
05-30 15:16:46.370  3380  3380 I tflite  : ============================== Run Order ==============================
05-30 15:16:46.370  3380  3380 I tflite  :                   [node type]          [first]        [avg ms]            [%]          [cdf%]          [mem KB] [times called]   [Name]
05-30 15:16:46.370  3380  3380 I tflite  :           TfLiteNnapiDelegate            0.228           0.213         1.773%          1.773%             0.000         1        [sequential/lstm/transpose1]:590
05-30 15:16:46.370  3380  3380 I tflite  :                        UNPACK            0.033           0.020         0.168%          1.941%             0.000         1        [sequential/lstm/unstack, sequential/lstm/unstack1, sequential/lstm/unstack2, sequential/lstm/unstack3, sequential/lstm/unstack4, sequential/lstm/unstack5, sequential/lstm/unstack6, sequential/lstm/unstack7, sequential/lstm/unstack8, sequential/lstm/unstack9, sequential/lstm/unstack10, sequential/lstm/unstack11, sequential/lstm/unstack12, sequential/lstm/unstack13, sequential/lstm/unstack14, sequential/lstm/unstack15, sequential/lstm/unstack16, sequential/lstm/unstack17, sequential/lstm/unstack18, sequential/lstm/unstack19, sequential/lstm/unstack20]:1
05-30 15:16:46.370  3380  3380 I tflite  :               FULLY_CONNECTED            0.011
```
</details>

**Comment by francescoyou97** [comment]
[example.zip](https://github.com/tensorflow/tensorflow/files/8798629/example.zip)
[train.zip](https://github.com/tensorflow/tensorflow/files/8798630/train.zip)

The example.zip contains the code, while the train.zip contains the data for training.

**Comment by mohantym** [comment]
Hi @francescoyou97 ! Did you get a chance to test in 2.8/2.9 version too? Thank you!

**Comment by francescoyou97** [comment]
Ok I test using tf2.9, but the results are almost the same.


05-31 10:31:13.006 21767 21767 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/model.tflite --warmup_runs=1 --num_runs=50 --enable_op_profiling=true --use_xnnpack=false --use_nnapi=true
05-31 10:31:13.022 21767 21767 I tflite  : Log parameter values verbosely: [0]
05-31 10:31:13.023 21767 21767 I tflite  : Min num runs: [50]
05-31 10:31:13.023 21767 21767 I tflite  : Min warmup runs: [1]
05-31 10:31:13.023 21767 21767 I tflite  : Graph: [/data/local/tmp/model.tflite]
05-31 10:31:13.023 21767 21767 I tflite  : Enable op profiling: [1]
05-31 10:31:13.023 21767 21767 I tflite  : Use NNAPI: [1]
05-31 10:31:13.036 21767 21767 I tflite  : NNAPI accelerators available: [ipuadaptor,nnapi-reference]
05-31 10:31:13.036 21767 21767 I tflite  : Use xnnpack: [0]
05-31 10:31:13.037 21767 21767 I tflite  : Loaded model /data/local/tmp/model.tflite
05-31 10:31:13.037 21767 21767 I tflite  : Initialized TensorFlow Lite runtime.
05-31 10:31:13.041 21767 21767 I tflite  : Created TensorFlow Lite delegate for NNAPI.
05-31 10:31:13.042 21767 21767 I tflite  : NNAPI delegate created.
05-31 10:31:13.157 21767 21767 I tflite  : Though NNAPI delegate is explicitly applied, the model graph will not be executed by the delegate.
05-31 10:31:13.157 21767 21767 I tflite  : The input model file size (MB): 0.104336
05-31 10:31:13.157 21767 21767 I tflite  : Initialized session in 120.712ms.
05-31 10:31:13.157 21767 21767 I tflite  : Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
05-31 10:31:13.658 21767 21767 I tflite  : count=946 first=4668 curr=512 min=510 max=4668 avg=525.8 std=137
05-31 10:31:13.658 21767 21767 I tflite  : Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
05-31 10:31:14.661 21767 21767 I tflite  : count=226 first=995 curr=807 min=793 max=1438 avg=854.973 std=85
05-31 10:31:14.661 21767 21767 I tflite  : Inference timings in us: Init: 120712, First inference: 4668, Warmup (avg): 525.8, Inference (avg): 854.973
05-31 10:31:14.661 21767 21767 I tflite  : Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
05-31 10:31:14.661 21767 21767 I tflite  : Memory footprint delta from the start of the tool (MB): init=2.12109 overall=2.12109
05-31 10:31:14.662 21767 21767 I tflite  : Profiling Info for Benchmark Initialization:
05-31 10:31:14.662 21767 21767 I tflite  : ============================== Run Order ==============================
05-31 10:31:14.662 21767 21767 I tflite  :                   [node type]          [first]        [avg ms]            [%]          [cdf%]          [mem KB]      [times called]  [Name]
05-31 10:31:14.662 21767 21767 I tflite  :       ModifyGraphWithDelegate          115.047         115.047        96.029%         96.029%          1216.000              1       ModifyGraphWithDelegate/0
05-31 10:31:14.662 21767 21767 I tflite  :               AllocateTensors            4.739           2.379         3.971%        100.000%             0.000              2       AllocateTensors/0
05-31 10:31:14.662 21767 21767 I tflite  :
05-31 10:31:14.662 21767 21767 I tflite  : ============================== Top by Computation Time ==============================
05-31 10:31:14.662 21767 21767 I tflite  :                   [node type]          [first]        [avg ms]            [%]          [cdf%]          [mem KB]      [times called]  [Name]
05-31 10:31:14.662 21767 21767 I tflite  :       ModifyGraphWithDelegate          115.047         115.047        96.029%         96.029%          1216.000              1       ModifyGraphWithDelegate/0
05-31 10:31:14.662 21767 21767 I tflite  :               AllocateTensors            4.739           2.379         3.971%        100.000%             0.000              2       AllocateTensors/0
05-31 10:31:14.662 21767 21767 I tflite  :
05-31 10:31:14.662 21767 21767 I tflite  : Number of nodes executed: 2
05-31 10:31:14.662 21767 21767 I tflite  : ============================== Summary by node type ==============================
05-31 10:31:14.662 21767 21767 I tflite  :                   [Node type]          [count]         [avg ms]          [avg %]         [cdf %]       [mem KB]      [ti
05-31 10:31:14.676 21767 21767 I tflite  : Operator-wise Profiling Info for Regular Benchmark Runs:
05-31 10:31:14.676 21767 21767 I tflite  : ============================== Run Order ==============================
05-31 10:31:14.676 21767 21767 I tflite  :                   [node type]          [first]        [avg ms]            [%]          [cdf%]          [mem KB]      [times called]  [Name]
05-31 10:31:14.676 21767 21767 I tflite  :                       RESHAPE            0.005           0.009         1.234%          1.234%             0.000              1       [sequential/lstm/transpose1]:0
05-31 10:31:14.676 21767 21767 I tflite  :                        UNPACK            0.007           0.011         1.564%          2.798%             0.000              1       [sequential/lstm/unstack, sequential/lstm/unstack1, sequential/lstm/unstack2, sequential/lstm/unstack3, sequential/lstm/unstack4, sequential/lstm/unstack5, sequential/lstm/unstack6, sequential/lstm/unstack7, sequential/lstm/unstack8, sequential/lstm/unstack9, sequential/lstm/unstack10, sequential/lstm/unstack11, sequential/lstm/unstack12, sequential/lstm/unstack13, sequential/lstm/unstack14, sequential/lstm/unstack15, sequential/lstm/unstack16, sequential/lstm/unstack17, sequential/lstm/unstack18, sequential/lstm/unstack19, sequential/lstm/unstack20]:1
05-31 10:31:14.676 21767 21767 I tflite  :               FULLY_CONNECTED            0.005

================================================================================================================================================================================================================================================
Using GPU delegate 

05-31 10:38:42.569 22206 22206 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/model.tflite --warmup_runs=1 --num_runs=50 --enable_op_profiling=true --use_xnnpack=false --use_gpu=true
05-31 10:38:42.582 22206 22206 I tflite  : Log parameter values verbosely: [0]
05-31 10:38:42.583 22206 22206 I tflite  : Min num runs: [50]
05-31 10:38:42.583 22206 22206 I tflite  : Min warmup runs: [1]
05-31 10:38:42.583 22206 22206 I tflite  : Graph: [/data/local/tmp/model.tflite]
05-31 10:38:42.583 22206 22206 I tflite  : Enable op profiling: [1]
05-31 10:38:42.583 22206 22206 I tflite  : Use gpu: [1]
05-31 10:38:42.583 22206 22206 I tflite  : Use xnnpack: [0]
05-31 10:38:42.584 22206 22206 I tflite  : Loaded model /data/local/tmp/model.tflite
05-31 10:38:42.585 22206 22206 I tflite  : Initialized TensorFlow Lite runtime.
05-31 10:38:42.589 22206 22206 I tflite  : Created TensorFlow Lite delegate for GPU.
05-31 10:38:42.589 22206 22206 I tflite  : GPU delegate created.
05-31 10:38:42.607 22206 22206 E tflite  : Following operations are not supported by GPU delegate:
05-31 10:38:42.607 22206 22206 E tflite  : UNPACK: Operation is not supported.
05-31 10:38:42.607 22206 22206 E tflite  : 294 operations will run on the GPU, and the remaining 296 operations will run on the CPU.
05-31 10:38:42.608 22206 22206 I tflite  : Replacing 294 node(s) with delegate (TfLiteGpuDelegateV2) node, yielding 2 partitions.
05-31 10:38:43.825 22206 22206 I tflite  : Initialized OpenCL-based API.
05-31 10:38:43.975 22206 22206 I tflite  : Created 1 GPU delegate kernels.
05-31 10:38:43.978 22206 22206 I tflite  : Explicitly applied GPU delegate, and the model graph will be partially executed by the delegate w/ 1 delegate kernels.
05-31 10:38:43.978 22206 22206 I tflite  : The input model file size (MB): 0.104336
05-31 10:38:43.978 22206 22206 I tflite  : Initialized session in 1394.55ms.
05-31 10:38:43.978 22206 22206 I tflite  : Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
05-31 10:38:44.487 22206 22206 I tflite  : count=32 first=25465 curr=13471 min=13109 max=25465 avg=15866.6 std=2987
05-31 10:38:44.487 22206 22206 I tflite  : Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
05-31 10:38:45.495 22206 22206 I tflite  : count=60 first=13655 curr=13218 min=12861 max=15281 avg=13796.8 std=605
05-31 10:38:45.495 22206 22206 I tflite  : Inference timings in us: Init: 1394548, First inference: 25465, Warmup (avg): 15866.6, Inference (avg): 13796.8
05-31 10:38:45.495 22206 22206 I tflite  : Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
05-31 10:38:45.495 22206 22206 I tflite  : Memory footprint delta from the start of the tool (MB): init=35.0312 overall=36.9297
05-31 10:38:45.496 22206 22206 I tflite  : Profiling Info for Benchmark Initialization:
05-31 10:38:45.496 22206 22206 I tflite  : ============================== Run Order ==============================
05-31 10:38:45.496 22206 22206 I tflite  :                   [node type]          [first]        [avg ms]            [%]          [cdf%]          [mem KB]      [times called]  [Name]
05-31 10:38:45.496 22206 22206 I tflite  :       ModifyGraphWithDelegate         1388.938        1388.938        99.810%         99.810%         34928.000              1       ModifyGraphWithDelegate/0
05-31 10:38:45.496 22206 22206 I tflite  :               AllocateTensors            2.633           1.323         0.190%        100.000%             0.000              2       AllocateTensors/0
05-31 10:38:45.496 22206 22206 I tflite  :
05-31 10:38:45.496 22206 22206 I tflite  : ============================== Top by Computation Time ==============================
05-31 10:38:45.496 22206 22206 I tflite  :                   [node type]          [first]        [avg ms]            [%]          [cdf%]          [mem KB]      [times called]  [Name]
05-31 10:38:45.496 22206 22206 I tflite  :       ModifyGraphWithDelegate         1388.938        1388.938        99.810%         99.810%         34928.000              1       ModifyGraphWithDelegate/0
05-31 10:38:45.496 22206 22206 I tflite  :               AllocateTensors            2.633           1.323         0.190%        100.000%             0.000              2       AllocateTensors/0
05-31 10:38:45.496 22206 22206 I tflite  :
05-31 10:38:45.496 22206 22206 I tflite  : Number of nodes executed: 2
05-31 10:38:45.496 22206 22206 I tflite  : ============================== Summary by node type ==============================
05-31 10:38:45.496 22206 22206 I tflite  :                   [Node type]          [count]         [avg ms]          [avg %]         [cdf %]       [mem KB]      [ti
05-31 10:38:45.504 22206 22206 I tflite  : Operator-wise Profiling Info for Regular Benchmark Runs:
05-31 10:38:45.504 22206 22206 I tflite  : ============================== Run Order ==============================
05-31 10:38:45.504 22206 22206 I tflite  :                   [node type]          [first]        [avg ms]            [%]          [cdf%]          [mem KB]      [times called]  [Name]
05-31 10:38:45.504 22206 22206 I tflite  :                       RESHAPE            0.031           0.021         0.157%          0.157%             0.000              1       [sequential/lstm/transpose1]:0
05-31 10:38:45.504 22206 22206 I tflite  :                        UNPACK            0.070           0.035         0.255%          0.413%             0.000              1       [sequential/lstm/unstack, sequential/lstm/unstack1, sequential/lstm/unstack2, sequential/lstm/unstack3, sequential/lstm/unstack4, sequential/lstm/unstack5, sequential/lstm/unstack6, sequential/lstm/unstack7, sequential/lstm/unstack8, sequential/lstm/unstack9, sequential/lstm/unstack10, sequential/lstm/unstack11, sequential/lstm/unstack12, sequential/lstm/unstack13, sequential/lstm/unstack14, sequential/lstm/unstack15, sequential/lstm/unstack16, sequential/lstm/unstack17, sequential/lstm/unstack18, sequential/lstm/unstack19, sequential/lstm/unstack20]:1
05-31 10:38:45.504 22206 22206 I tflite  :               FULLY_CONNECTED            0.028




As you can see only 294 operations are executed on GPU.

**Comment by francescoyou97** [comment]
You can healp me?

**Comment by mohantym** [comment]
Hi @francescoyou97 !
Could you build the lite model with [Fusion Code lab method ](https://colab.sandbox.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb?hl=pt#scrollTo=tB1NZBUHDogR)too (Please check with 3.8 version )
and post the benchmarking results.


Thank you!
