### ISSUE TITLE
How to full int 8 quantize a yamnet model?

### ISSUE THREAD

**Issue by MATTYGILO** [tensorflow/tensorflow#56313]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8

### Custom Code

Yes

### OS Platform and Distribution

Linux, Mac

### Mobile device

Linux Ubuntu, Mac m1, Mac intel

### Python version

3.7, 3.10, 3.6

### Current Behaviour?

```shell
How to full int 8 QAT quantisation
```

### Standalone code to reproduce the issue

```shell
import tensorflow_model_optimization as tfmot

LastValueQuantizer = tfmot.quantization.keras.quantizers.LastValueQuantizer
MovingAverageQuantizer = tfmot.quantization.keras.quantizers.MovingAverageQuantizer

class DefaultDenseQuantizeConfig(tfmot.quantization.keras.QuantizeConfig):
    # List all of your weights
    weights = {
        "kernel": LastValueQuantizer(num_bits=8, symmetric=True, narrow_range=False, per_axis=False)
    }

    # List of all your activations
    activations = {
        "activation": MovingAverageQuantizer(num_bits=8, symmetric=False, narrow_range=False, per_axis=False)
    }

    # Configure how to quantize weights.
    def get_weights_and_quantizers(self, layer):
        output = []
        for attribute, quantizer in self.weights.items():
            if hasattr(layer, attribute):
                output.append((getattr(layer, attribute), quantizer))

        return output

    # Configure how to quantize activations.
    def get_activations_and_quantizers(self, layer):
        output = []
        for attribute, quantizer in self.activations.items():
            if hasattr(layer, attribute):
                output.append((getattr(layer, attribute), quantizer))

        return output

    def set_quantize_weights(self, layer, quantize_weights):
        # Add this line for each item returned in `get_weights_and_quantizers`
        # , in the same order

        count = 0
        for attribute in self.weights.keys():
            if hasattr(layer, attribute):
                setattr(layer, attribute, quantize_weights[count])
                count += 1

    def set_quantize_activations(self, layer, quantize_activations):
        # Add this line for each item returned in `get_activations_and_quantizers`
        # , in the same order.
        count = 0
        for attribute in self.activations.keys():
            if hasattr(layer, attribute):
                setattr(layer, attribute, quantize_activations[count])
                count += 1

    # Configure how to quantize outputs (may be equivalent to activations).
    def get_output_quantizers(self, layer):
        return []

    def get_config(self):
        return {}


from quant import DefaultDenseQuantizeConfig
from tensorflow_model_optimization.python.core.quantization.keras.quantize import quantize_scope, quantize_apply
import tensorflow_model_optimization as tfmot


with quantize_scope({
    "DefaultDenseQuantizeConfig": DefaultDenseQuantizeConfig,
    "CustomLayer": CustomLayer
}):
    def apply_quantization_to_layer(layer):
        return tfmot.quantization.keras.quantize_annotate_layer(layer, DefaultDenseQuantizeConfig())

    annotated_model = tf.keras.models.clone_model(
        tflite_model,
        clone_function=apply_quantization_to_layer,
    )

    qat_model = tfmot.quantization.keras.quantize_apply(annotated_model)

    qat_model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
        loss="categorical_crossentropy",
        metrics=['accuracy']
    )

    qat_model.summary()
```

### Relevant log output

```shell
When I test the tflite model it predicts completely randomly
```
</details>

**Comment by MATTYGILO** [comment]
I have left an issue here for days now:
[https://github.com/tensorflow/model-optimization/issues/974](https://github.com/tensorflow/model-optimization/issues/974)

There is not info online about full int 8 quantisation for yamnet

**Comment by mohantym** [comment]
Hi @MATTYGILO ! Sorry for the late response. Could you just share the TFlite conversion part of yamnet model as Colab gist. Thank you!

**Comment by MATTYGILO** [comment]
@mohantym This is my gist
<script src="https://gist.github.com/MATTYGILO/9f32ab8837a6ef794360ce1e128e7cc9.js"></script>

**Comment by MATTYGILO** [comment]
I've also done some research into just quantising the spectrogram layer.

Spectrogram output without any quantisation, No QAT:
![IMG_4987](https://user-images.githubusercontent.com/34808802/171358481-231abfac-20a6-44c9-9255-f13192c67bd0.jpeg)

Spectrogram output with quantisation, No QAT:
![IMG_4986](https://user-images.githubusercontent.com/34808802/171358614-0348287e-079a-48d3-b8bf-e745523e6437.jpeg)

QAT spectrogram without quantisation:
![IMG_4988](https://user-images.githubusercontent.com/34808802/171358865-06492a80-18bf-4698-bbf3-afcdc08eedd5.jpeg)

QAT spectrogram with quantisation
![IMG_4989](https://user-images.githubusercontent.com/34808802/171358934-7179efde-ca90-44c4-bae3-fdf2ef3695a2.jpeg)

As you can see with quantisation and QAT the output are just 0's.
￼

**Comment by mohantym** [comment]
@MATTYGILO ! "Quant "  seems not to be working in Colab. Could you please update on this. Attached [gist](https://colab.sandbox.google.com/gist/mohantym/2541a6c0af76fb19025d4980871396a1/git_56313.ipynb)  for reference. Thank you!

**Comment by MATTYGILO** [comment]
@mohantym Oh sorry that was a file I made. I'll try and provide a better example

**Comment by MATTYGILO** [comment]
@mohantym I'm really stuck is it possible if you could provide an example for a working full int 8 quantisation of a yamnet

**Comment by mohantym** [comment]
@MATTYGILO ! I think int8 quantization might not be possible yet. Found a similar issue [here.](https://github.com/tensorflow/tensorflow/issues/53393) But Could you make these changes in the above code and let us know. Thank you!
```

def representative_dataset():
    for _ in range(1000):
        data = np.random.choice([-32768, 0, 1, 32767], size=(88200,))  #give it a  fixed size , Dynamic size is still an obstacle in some cases during TFLite conversion
        yield [data.astype(np.uint8)] # uint8 recommended while trying uint8 quantization


converter = tf.lite.TFLiteConverter.from_keras_model(qat_model)
converter.experimental_new_converter = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.# resolves select ops issues
]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8
tflite_quant_model = converter.convert()
```

**Comment by MATTYGILO** [comment]
Ok using the `data.astype(np.int8)` I get a `ValueError: Cannot set tensor: Got value of type UINT8 but expected type FLOAT32 for input 0`

**Comment by mohantym** [comment]
@MATTYGILO ! Quantized data is not needed normally in the representative dataset.  You should revert to float32 datatype as the error suggests. I am afraid integer quantization might not be possible for Yamnet model yet.
```
def representative_dataset():
    for _ in range(1000):
        data = np.random.choice([-32768, 0, 1, 32767], size=(88200,))  #give it a  fixed size , Dynamic size is still an obstacle in some cases during TFLite conversion
        yield [data.astype(np.float32)] # uint8/int8 recommended while trying uint8 quantization


converter = tf.lite.TFLiteConverter.from_keras_model(qat_model)
converter.experimental_new_converter = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.# resolves select ops issues
]
converter.inference_input_type = tf.float32
converter.inference_output_type = tf.float32
tflite_quant_model = converter.convert()
```

**Comment by MATTYGILO** [comment]
@mohantym Ok the only problem is that I require integer quantisation for tflite micro. So I'm a bit stuck I guess.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
