### ISSUE TITLE
Best image input size for SSD-Models

### ISSUE THREAD

**Issue by Petros626** [tensorflow/tensorflow#56318]
Hello,

I am currently doing a student research project and am concerned with the question of which input variable would be the best to train my object detector.

**SSD models**, according to other users, have a problem detecting smaller objects (too many convolutional layers in the SSD). Therefore, I assumed a relatively good resolution like 512,720 or 800 as a square image. The SSD structure contains a resizer of **300x300 (ssd_mobilenet_v2)**, whereby one should also be careful not to get too strong defomations of the objects if the image is unfavourably chosen, e.g. 600x1024.

Questions:
**Is it important to have a large input size (more information)?**
**Does a smaller one work well, even the same as the resizer of the architecture?**
**What advantages/disadvantages do I have with larger or smaller images?
Is it a problem to train with a fixed size and then apply it to smaller or larger resolutions?
300x300 -> 512x512 or 720x720?**

I would be grateful if someone could tell me good sources to justify the decision.

P.S Enclosed is an example picture (720x720) 2cm cell_size
![image_19](https://user-images.githubusercontent.com/62354721/171372228-966ccf20-79f2-4526-9d28-59e0b523c34b.jpg)

**Comment by tilakrayal** [comment]
Hi @Petros626,
The specific input image sizes of SSD are `300x300` and `512x512`. You can try resizing the images to `512x512` and then training. However, considering that the repo has `300x300` as the default value would probably mean that the model works best when the inputs are of that size.

There are however many other models that allow an input size of `640x640`

In Tensorflow models repo `zoo - version 1`, you have ssd_resnet50_v1 [config file](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync.config) and in [version 2](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md), you have many other variants of SSD and EfficientDet which support `640x640`.

You will probably get better results by training using the above-mentioned models. Also please take a look at this SO [link](https://stackoverflow.com/questions/48929519/mobilenet-ssd-input-image-size/48967587#48967587) which delivers the more information. Thank you!

**Comment by Petros626** [comment]
Thanks I will use 512x512 images and then it's resized to 300x300 by the network.
