### ISSUE TITLE
Tensorflow 2.2 build from source: Executing genrule @local_config_python//:numpy_include failed (Exit 1)

### ISSUE THREAD

**Issue by bergduivel** [tensorflow/tensorflow#56310]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.2

### Custom Code

No

### OS Platform and Distribution

Ubuntu 

### Mobile device

Ubuntu 20.04.4

### Python version

3.8.10

### Bazel version

Bazel 2.0.0

### Current Behaviour?

```shell
I get a numpy_include_failed error. I do have a correct version of numpy installed in the environment that I'm using.
```

### Standalone code to reproduce the issue

```shell
bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.2 --action_env PYTHON_BIN_PATH=/home/brent/Documents/Projects/BenchmarkRCStrategiesSOTA/venv_temp/bin/python  //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```shell
ERROR: /home/brent/.cache/bazel/_bazel_brent/f717514c870df2340554ff84ed4b3c4d/external/local_config_python/BUILD:241:1: Executing genrule @local_config_python//:numpy_include failed (Exit 1)
cp: cannot stat '/home/brent/Documents/Projects/BenchmarkRCStrategiesSOTA/venv_temp/lib/python3.8/site-packages/numpy/core/include/numpy/.doxyfile': No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/brent/Documents/Projects/BenchmarkRCStrategiesSOTA/tensorflow/tensorflow/python/tools/BUILD:82:1 Executing genrule @local_config_python//:numpy_include failed (Exit 1)
INFO: Elapsed time: 272.539s, Critical Path: 68.77s
INFO: 1569 processes: 1569 local.
FAILED: Build did NOT complete successfully
```
</details>

**Comment by sushreebarsa** [comment]
@bergduivel TF 2.2 does not really contain all the changes to prevent code using invalid shapes from crashing the interpreter via CHECK-failures. It's unlikely for TF 2.2 version to receive any bug fixes except when we have security patches. As TF version 2.2 is not actively supported please post this issue on TF [forum](https://discuss.tensorflow.org/), there is a larger community to get you the right help.
Thank you!

**Comment by sushreebarsa** [comment]
@bergduivel Thank you for the update!
Could you please move this issue to closed status if it is resolved?
Thank you!
