### ISSUE TITLE
tf.Print is not an identity op w/ tuples or lists of Tensors; clarify in docs or add warning msg?

### ISSUE THREAD

**Issue by cbockman** [tensorflow/tensorflow#5631]
**Documentation issue with bidirectional_dynamic_rnn:**

For "outputs":

"...It returns a tuple instead of a single concatenated Tensor, unlike in the bidirectional_rnn. If the concatenated one is preferred, the forward and backward outputs can be concatenated as tf.concat(2, outputs)."

This doesn't appear to work.  As a fix:

output, _ = tf.nn.bidirectional_dynamic_rnn(...)
output=tf.concat(2, tf.unpack(output))

...this appears to be necessary because tf.concat does not view the returned tuple as equivalent to a list of Tensors, but rather appears to treat the tuple (effectively) as a Tensor.

**Possible bug in tf.concat:**

Unclear whether tf.concat(2, output) actually should, in fact, return as the initial documentation for bidirectional_dynamic_rnn suggested.

**Comment by girving** [comment]
@cbockman When you say it doesn't work, what error message do you see?  Also, please use code formatting for code (4 space indent) to make it easier to read.

**Comment by cbockman** [comment]
Apologies...

OK, so actually got bitten by an unrelated issue.  This can probably be closed, although maybe worth some light tf.Print documentation clarification.

`output, _ = tf.nn.bidirectional_dynamic_rnn(fw_cell, bw_cell, inputs,lengths,dtype=tf.float32)`
`output=tf.Print(output, [output], "MSG")`
`output = tf.concat(2, output)`

The above created issues for me because tf.Print apparently transforms the tuple of tensors (output) into a single tensor.  This results in tf.concat receiving a single tensor as 'output', rather than a tuple, as was expected.

This may be 100% intended--and, in fact, the documentation for tf.Print is very understandably silent on what happens when a non-Tensor gets passed into tf.Print.  From a quick read of tf.Print as an "identity" op, however, I didn't anticipate that tf.Print could actually transform the input to something else.  (And yes, I now appreciate the internal consistency as to why this is true, given how TF generally tries to cast non-Tensors into Tensors, for convenience).

Maybe worth clarifying, or maybe I'm just dumb...

Certainly somewhat ironic, as I blindedly layered in a tf.Print for debug purposes, and managed to create another problem.

**Comment by cbockman** [comment]
Alternately/additionally, maybe add a light type check on def Print that
flags if type is likely to get transformed?  A little crude, but given this
is essentially just a debug operation, maybe a useful trade off.

**Comment by girving** [comment]
@cbockman I think documentation for `tf.Print` doesn't make sense, since the same machinery applies to any function that takes tensors.  However, better error messages would certainly be good.  I'm not quite sure *why* `tf.Print` would have silently absorbed a list of tensors, unless that's new functionality someone added.  Can you clarify: does it automatically concatenate (same rank) or automatically stack (one higher rank)?

**Comment by cbockman** [comment]
@girving tf.Print will stack.  e.g., tensor tuple of ( \<1, ?, 2\>, \<1, ?, 2\>) ==> \<2, 1, ?, 2\>

re:documentation, I'd push back a little, in that referring to something as an "identity op"--which isn't really an identity op, under certain scenarios--is very confusing to anyone new to the project.  That said, Tensorflow is obviously not my project.  ;)

One potentially simple error msg would be to do a type check within tf.Print itself and echo out a warning msgif instance(list, tuple)...or perhaps if not instance(tensor) (away from command line, can't check if this isinstance(tensor) is supported...I assume it is?).

Yeah, this will only trigger when tf.Print is evaluated symbolically, but I think that will be sufficient for catching vast majority of failure modes related to this...and it is hard for me to foresee too many (any?) scenarios where this causes problems in any production environment (if tf.Print is truly intended as a debug as a debug tool, I don't know who would actually *want* to pass in a list and get a stacked tensor back...if you want that functionality, use another op to do that).

**Comment by girving** [comment]
@cbockman TensorFlow makes an effort where possible to mirror numpy, and merging multiple tensors this way is standard numpy behavior.  `tf.Print` already says it takes a tensor.  Unfortunately, it's impractical to document all the dynamic type conversion behavior of Python code in every tensorflow function.

**Comment by cbockman** [comment]
@girving fair enough.  thanks for looking at this.
