### ISSUE TITLE
Loading tflite model from a buffer instead of .tflite file

### ISSUE THREAD

**Issue by supratimc239** [tensorflow/tensorflow#56316]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 16.04.2 LTS

### Current Behaviour?

```shell
In the example https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/minimal/minimal.cc I can see that we are loading model from a file.
Is it possible to load the model from a character buffer (e.g. xxd -i minimal.tflite > minimal_data.cc) instead of from a file? If so, could you please provide an example?

Thanks
```

### Standalone code to reproduce the issue

```shell
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/minimal/minimal.cc:

int main(int argc, char* argv[]) {
  if (argc != 2) {
    fprintf(stderr, "minimal <tflite model>\n");
    return 1;
  }
  const char* filename = argv[1];

  // Load model
  std::unique_ptr<tflite::FlatBufferModel> model =
      tflite::FlatBufferModel::BuildFromFile(filename);
  TFLITE_MINIMAL_CHECK(model != nullptr);
...
}
```

### Relevant log output

_No response_</details>

**Comment by supratimc239** [comment]
Hi @mohantym,

Thanks for your response. But unfortunately I could not find example of using flatbuffers instead of tflite model inside a tflite code for parsing model and using it inside interpreter.

Thanks

**Comment by mohantym** [comment]
@supratimc239 ! 
Here are the usage details of flatbuffer files (.tflite) in  above code. 
```

int main(int argc, char* argv[]) {
if (argc != 2) {
fprintf(stderr, "minimal \n");
return 1;
}
const char* filename = argv[1];

// Load model
std::unique_ptrtflite::FlatBufferModel model =
tflite::FlatBufferModel::BuildFromFile(filename); // loads the tflite (flatbuffer file)
TFLITE_MINIMAL_CHECK(model != nullptr);
...
}

```
Here are the usage details of loading from a character buffer .
1. convert  character buffer to header file(Refer last part of this[ gist](https://colab.sandbox.google.com/github/instafluff/TensorFlowLiteMicro_MNIST/blob/master/mnist_model_tensorflow_lite_micro.ipynb#scrollTo=b82mVPnj9Lp3))
2. include the header file  in your [C++ inference](https://www.tensorflow.org/lite/microcontrollers/get_started_low_level#run_inference).

**Comment by supratimc239** [comment]
@mohantym,

Thank you for response, I made following changes in my code:
 std::unique_ptr<tflite::FlatBufferModel> model =
          tflite::FlatBufferModel::BuildFromBuffer(g_model_lite_int8_tflite, g_model_lite_int8_tflite_len); //here g_model_lite_int8_tflite refers to the const char array corresponding to the model obtained using xxd command and  g_model_lite_int8_tflite_len refers to the length of that array.

**Comment by mohantym** [comment]
Ok @supratimc239 ! Please give an update if it works. Thank you!
