### ISSUE TITLE
Dataset created from large ragged tensor doesn't copy values

### ISSUE THREAD

**Issue by svenhsia** [tensorflow/tensorflow#56319]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Linux

### Python version

3.9.9

### Current Behaviour?

```shell
<tf.Tensor: shape=(256,), dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.], dtype=float32)>
```

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf

x = np.random.randn(425000, 32, 256).astype('float32')
l = [250] * 1700
ds = tf.data.Dataset.from_tensor_slices(tf.RaggedTensor.from_row_lengths(x, l))

display(next(iter(ds))[0][0])
```

### Relevant log output

_No response_</details>

**Comment by svenhsia** [comment]
The issue only appears with large data. By reducing the data size, issue disappears. 
The issue seems only concern ragged-tensor. By replacing ragged tensor with normal tensor (the same size), the issue also disappears.

**Comment by 0x0L** [comment]
Reproduced on macos python 3.10.4 (conda-forge) tf 2.9.1 (pypi)

This seems to depend on the size of the data and works ok as long as the total size is < 2**31 - 1.
e.g. `x.shape == (2 ** 31 - 2, 1)` is and `x.shape == (2 ** 30, 2)` is not

However for `x.shape == (2 ** 31, 1)`  the construction of the RaggedTensor throws an exception complaining that `Shape output type is 32-bit but dim 0 is 2**31 [Op:Shape]`. It does not work but at least it does not produce a random output silently

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I tried to execute the given code in colab with v 2.8, 2.9, nightly version and noticed that session is being crashed. Please, find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/cc5cecd29ffa57a732d0702434d8c1bf/56319.ipynb). Thank you!

**Comment by tomytsai1** [comment]
The problem is caused by improper int types used in the ragged tensor data preparation. Will look at how to fix it.

**Comment by tomytsai1** [comment]
We are working on a fix in [ragged_tensor_to_variant_op](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/ragged_tensor_to_variant_op.cc).

**Comment by tomytsai1** [comment]
The issue was fixed in [this commit](https://github.com/tensorflow/tensorflow/commit/9166effef59dcc719358026018e5253ddcd001d6). Please see if there is any other problems.
