### ISSUE TITLE
Character-level seq2seq model for translation and beam search.

### ISSUE THREAD

**Issue by VallabhMahajan1** [tensorflow/tensorflow#56327]
I was trying to implement seq2seq translation model at character level along with beam search by referring the tensorflow documentation.

[[https://www.tensorflow.org/addons/tutorials/networks_seq2seq_nmt](https://github.com/tensorflow/addons/issues/url)](url)

For this, I tried to change parameter, 'char_level = True' in tf.keras tokenizer. There was no issue during model training, but I'm getting error for inferences. 

Can someone please help me to solve this issue.

Thank you in advance

![image](https://user-images.githubusercontent.com/25157856/171536625-f0bf3ad4-e51a-40db-a6ae-3e825f95c875.png)

**Comment by sushreebarsa** [comment]
@VallabhMahajan1 
In order to expedite the trouble-shooting process here, could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thank you!

**Comment by VallabhMahajan1** [comment]
Thanks for the reply. I'm a beginner in this field. I tried to concatenate the list to a string inside the tokenize function and I'm getting this error.

    # Step 3 and Step 4
    def tokenize(self, lang):
        # lang = list of sentences in a language

        text = ''
        for s in lang:
          text += s + ""

        print(len(text), "example sentence: {}".format(text[5]))
        lang_tokenizer = tf.keras.preprocessing.text.Tokenizer(filters='', oov_token='<OOV>', char_level = True)
        lang_tokenizer.fit_on_texts(text)
        print(text)

        ## tf.keras.preprocessing.text.Tokenizer.texts_to_sequences converts string (w1, w2, w3, ......, wn) 
        ## to a list of correspoding integer ids of words (id_w1, id_w2, id_w3, ...., id_wn)
        tensor = lang_tokenizer.texts_to_sequences(text) 

        ## tf.keras.preprocessing.sequence.pad_sequences takes argument a list of integer id sequences 
        ## and pads the sequences to match the longest sequences in the given input
        tensor = tf.keras.preprocessing.sequence.pad_sequences(tensor, padding='post')

        return tensor, lang_tokenizer


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-56-ed477fa71f21> in <module>()
      5 
      6 dataset_creator = NMTDataset('en-spa')
----> 7 train_dataset, val_dataset, inp_lang, targ_lang = dataset_creator.call(num_examples, BUFFER_SIZE, BATCH_SIZE)

3 frames
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py in check_consistent_length(*arrays)
    332         raise ValueError(
    333             "Found input variables with inconsistent numbers of samples: %r"
--> 334             % [int(l) for l in lengths]
    335         )
    336 

ValueError: Found input variables with inconsistent numbers of samples: [1038789, 981044]

Can you please help me with this. 
Thank you so much.

**Comment by sushreebarsa** [comment]
@VallabhMahajan1 Thank you for the response!
In order to expedite the trouble-shooting process, please provide a complete code snippet to reproduce the issue reported here. Thank you!
