### ISSUE TITLE
Linking to static libtensorflow-lite.a gives linking errors on Debian x64

### ISSUE THREAD

**Issue by mrdeveloperdude** [tensorflow/tensorflow#56325]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Debian 11 x64

### GCC/Compiler version

g++ (Debian 10.2.1-6) 10.2.1 20210110

### Current Behaviour?

```shell
I build the static tf lite library following documentation here perfectly: https://www.tensorflow.org/lite/guide/build_cmake


sudo apt-get install cmake
git clone https://github.com/tensorflow/tensorflow.git tensorflow_src
mkdir tflite_build
cd tflite_build
cmake ../tensorflow_src/tensorflow/lite
cmake --build . -j


I see that the folder contains a resulting libtensorflow-lite.a indicating success

I then link my existing application to this library and build it. The result is a disappointing list of link errors (see log below)
```

### Standalone code to reproduce the issue

```shell
There is no code, just linking errors.
```

### Relevant log output

```shell
g++ -Wl,--allow-multiple-definition -Wl,--whole-archive -Wl,-rpath,/home/leo/Qt/6.3.0/gcc_64/lib -Wl,-rpath-link,/home/leo/Qt/6.3.0/gcc_64/lib -o Karaoke   main.o [....]   -L/home/leo/Desktop/Projects/Singularity/libs/tflite_build -ltensorflow-lite -ldl /home/leo/Qt/6.3.0/gcc_64/lib/libQt6MultimediaWidgets.so /home/leo/Qt/6.3.0/gcc_64/lib/libQt6Multimedia.so -pthread /home/leo/Qt/6.3.0/gcc_64/lib/libQt6OpenGLWidgets.so /home/leo/Qt/6.3.0/gcc_64/lib/libQt6Widgets.so /home/leo/Qt/6.3.0/gcc_64/lib/libQt6OpenGL.so /home/leo/Qt/6.3.0/gcc_64/lib/libQt6Gui.so /home/leo/Qt/6.3.0/gcc_64/lib/libQt6Network.so /home/leo/Qt/6.3.0/gcc_64/lib/libQt6Sql.so /home/leo/Qt/6.3.0/gcc_64/lib/libQt6Core.so -lpthread -lGL   
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(serialization.cc.o): in function `tflite::delegates::StrFingerprint[abi:cxx11](void const*, unsigned long)':
serialization.cc:(.text+0x7c1): undefined reference to `util::Fingerprint64(char const*, unsigned long)'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(serialization.cc.o): in function `tflite::delegates::Serialization::GetEntryImpl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, TfLiteContext*, TfLiteDelegateParams const*)':
serialization.cc:(.text+0x1760): undefined reference to `util::Fingerprint64(char const*, unsigned long)'
/usr/bin/ld: serialization.cc:(.text+0x1770): undefined reference to `util::Fingerprint64(char const*, unsigned long)'
/usr/bin/ld: serialization.cc:(.text+0x18a4): undefined reference to `util::Fingerprint64(char const*, unsigned long)'
/usr/bin/ld: serialization.cc:(.text+0x1ab7): undefined reference to `util::Fingerprint64(char const*, unsigned long)'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitReluNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, int, TfLiteNode*, TfLiteTensor const*, float, float, std::vector<unsigned int, std::allocator<unsigned int> > const&) [clone .constprop.0]':
xnnpack_delegate.cc:(.text+0x104c): undefined reference to `xnn_define_clamp'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitConcatenationNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, int, TfLiteNode*, TfLiteTensor const*, TfLiteConcatenationParams const*, std::vector<unsigned int, std::allocator<unsigned int> > const&)':
xnnpack_delegate.cc:(.text+0x1594): undefined reference to `xnn_define_concatenate4'
/usr/bin/ld: xnnpack_delegate.cc:(.text+0x15d7): undefined reference to `xnn_define_concatenate2'
/usr/bin/ld: xnnpack_delegate.cc:(.text+0x15f1): undefined reference to `xnn_define_concatenate3'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitMaxPool2DNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, int, TfLiteNode*, TfLiteTensor const*, TfLitePoolParams const*, std::vector<unsigned int, std::allocator<unsigned int> > const&)':
xnnpack_delegate.cc:(.text+0x1a58): undefined reference to `xnn_define_max_pooling_2d'
/usr/bin/ld: xnnpack_delegate.cc:(.text+0x1c8e): undefined reference to `xnn_define_clamp'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitMediaPipeUnpoolingNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, int, TfLiteNode*, TfLiteTensor const*, TfLitePoolParams const*, std::vector<unsigned int, std::allocator<unsigned int> > const&) [clone .constprop.0]':
xnnpack_delegate.cc:(.text+0x2242): undefined reference to `xnn_define_unpooling_2d'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitMediaPipeMaxPoolingNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, int, TfLiteNode*, TfLiteTensor const*, TfLitePoolParams const*, std::vector<unsigned int, std::allocator<unsigned int> > const&) [clone .constprop.0]':
xnnpack_delegate.cc:(.text+0x2940): undefined reference to `xnn_define_argmax_pooling_2d'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitReshapeNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, int, TfLiteNode*, TfLiteTensor const*, TfLiteReshapeParams const*, std::vector<unsigned int, std::allocator<unsigned int> > const&) [clone .constprop.0]':
xnnpack_delegate.cc:(.text+0x2ded): undefined reference to `xnn_define_static_reshape'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitResizeBilinearNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, int, TfLiteNode*, TfLiteTensor const*, TfLiteResizeBilinearParams const*, std::vector<unsigned int, std::allocator<unsigned int> > const&)':
xnnpack_delegate.cc:(.text+0x3635): undefined reference to `xnn_define_static_resize_bilinear_2d'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitPadNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, int, TfLiteNode*, TfLiteTensor const*, std::vector<unsigned int, std::allocator<unsigned int> > const&)':
xnnpack_delegate.cc:(.text+0x3e5a): undefined reference to `xnn_define_static_constant_pad'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitPreluNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, int, TfLiteNode*, TfLiteTensor const*, std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&) [clone .constprop.0]':
xnnpack_delegate.cc:(.text+0x433c): undefined reference to `xnn_define_prelu'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitSplitNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, int, TfLiteNode*, TfLiteTensor const*, TfLiteSplitParams const*, std::vector<unsigned int, std::allocator<unsigned int> > const&) [clone .isra.0]':
xnnpack_delegate.cc:(.text+0x4a88): undefined reference to `xnn_define_even_split2'
/usr/bin/ld: xnnpack_delegate.cc:(.text+0x4ace): undefined reference to `xnn_define_even_split4'
/usr/bin/ld: xnnpack_delegate.cc:(.text+0x4b01): undefined reference to `xnn_define_even_split3'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitFullyConnectedNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, int, TfLiteNode*, TfLiteTensor const*, TfLiteFullyConnectedParams const*, std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&)':
xnnpack_delegate.cc:(.text+0x4cac): undefined reference to `xnn_define_fully_connected'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitTransposeConvNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, int, TfLiteNode*, TfLiteTensor const*, TfLiteTransposeConvParams const*, std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&)':
xnnpack_delegate.cc:(.text+0x5f87): undefined reference to `xnn_define_deconvolution_2d'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitMediaPipeDeconvolutionNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, int, TfLiteNode*, TfLiteTensor const*, TfLiteTransposeConvParams const*, std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&) [clone .constprop.0]':
xnnpack_delegate.cc:(.text+0x67ed): undefined reference to `xnn_define_deconvolution_2d'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitMeanNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, int, TfLiteNode*, TfLiteTensor const*, TfLiteReducerParams const*, std::vector<unsigned int, std::allocator<unsigned int> > const&)':
xnnpack_delegate.cc:(.text+0x6fa1): undefined reference to `xnn_define_global_average_pooling_2d'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitConv2DNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, int, TfLiteNode*, TfLiteTensor const*, TfLiteConvParams const*, std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&)':
xnnpack_delegate.cc:(.text+0x7b13): undefined reference to `xnn_define_convolution_2d'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitDepthwiseConv2DNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, int, TfLiteNode*, TfLiteTensor const*, TfLiteDepthwiseConvParams const*, std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&)':
xnnpack_delegate.cc:(.text+0x866d): undefined reference to `xnn_define_depthwise_convolution_2d'
/usr/bin/ld: /home/leo/Desktop/Projects/Singularity/libs/tflite_build/libtensorflow-lite.a(xnnpack_delegate.cc.o): in function `tflite::xnnpack::(anonymous namespace)::Subgraph::VisitNode(xnn_subgraph*, tflite::xnnpack::(anonymous namespace)::Delegate const&, TfLiteContext*, TfLiteRegistration*, TfLiteNode*, int, std::unordered_set<int, std::hash<int>, std::equal_to<int>, std::allocator<int> > const&, std::vector<unsigned int, std::allocator<unsigned int> > const&)':
xnnpack_delegate.cc:(.text+0x88ec): undefined reference to `xnn_define_hardswish'
/usr/bin/ld: xnnpack_delegate.cc:(.text+0x89e0): undefined reference to `xnn_define_bankers_rounding'
/usr/bin/ld: xnnpack_delegate.cc:(.text+0x8afd): undefined reference to `xnn_define_convert'
/usr/bin/ld: xnnpack_delegate.cc:(.text+0x8c24): undefined reference to `xnn_define_elu'
/usr/bin/ld: xnnpack_delegate.cc:(.text+0x8d28): undefined reference to `xnn_define_ceiling'
/usr/bin/ld: xnnpack_delegate.cc:(.text+0x8e30): undefined reference to `xnn_define_abs'
/usr/bin/ld: xnnpack_delegate.cc:(.text+0x8f8a): undefined reference to 


Too long so truncating
```
</details>

**Comment by mrdeveloperdude** [comment]
I found the answer; In the very documentation I was following this was noted:

> Note: This generates a static library libtensorflow-lite.a in the current directory but the library isn't self-contained since all the transitive dependencies are not included. To use the library properly, you need to create a CMake project. Please refer the ["Create a CMake project which uses TensorFlow Lite"](https://www.tensorflow.org/lite/guide/build_cmake#create_a_cmake_project_which_uses_tensorflow_lite) section.

Unfortunately my project is not based on cmake and so I really only see 4 ways to link to tflite at this point:

1. Convert to CMake (not feasible)
2. Create a CMake library project that wraps tflite and produces one single static library that can be linked from my non-cmake project (feasible but a major PITA
3. Ask niceely for tf to support non cmake projects (probably not going to happen)
4. Hack the hell out of this and just make it work™

In the interest of saving time and not wasting my brilliance on this stuff I went wit option 4. Here is the workaround if you find yourself in a similar situation;

To get additional lib folders ( use with -L during link)
find . -type f -name "*.a" -exec  dirname {} \; | sort -u

To get the list of lib files (use with -l during link)
find . -type f -name "lib*.a" -exec  basename {} \;
NOTE: you have to remove "lib" prefix and ".a" suffix for this to work


The final result for me (Qt6 qmake syntax) looked like this:



LIBS += -L$$PWD/libs/tflite_build -ltensorflow-lite

INCLUDEPATH += $$PWD/libs/tensorflow
INCLUDEPATH += $$PWD/libs
INCLUDEPATH += $$PWD/libs/tflite_build

DEPENDPATH += $$PWD/libs/tflite_build
PRE_TARGETDEPS += $$PWD/libs/tflite_build/libtensorflow-lite.a

PRE_TARGETDEPS += $$PWD/libs/tflite_build/pthreadpool/libpthreadpool.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/cpuinfo-build/libcpuinfo.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/flatbuffers-build/libflatbuffers.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/clog-build/libclog.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/xnnpack-build/libXNNPACK.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/farmhash-build/libfarmhash.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/fft2d-build/libfft2d_fftsg2d.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/fft2d-build/libfft2d_fftsg.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/types/libabsl_bad_optional_access.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/types/libabsl_bad_variant_access.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/status/libabsl_status.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/time/libabsl_civil_time.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/time/libabsl_time_zone.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/time/libabsl_time.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/base/libabsl_throw_delegate.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/base/libabsl_raw_logging_internal.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/base/libabsl_malloc_internal.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/base/libabsl_spinlock_wait.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/base/libabsl_log_severity.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/base/libabsl_base.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/flags/libabsl_flags_commandlineflag_internal.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/flags/libabsl_flags_marshalling.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/flags/libabsl_flags_internal.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/flags/libabsl_flags_config.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/flags/libabsl_flags_program_name.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/flags/libabsl_flags.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/flags/libabsl_flags_commandlineflag.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/flags/libabsl_flags_private_handle_accessor.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/flags/libabsl_flags_reflection.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/hash/libabsl_city.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/hash/libabsl_low_level_hash.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/hash/libabsl_hash.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/numeric/libabsl_int128.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/debugging/libabsl_stacktrace.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/debugging/libabsl_symbolize.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/debugging/libabsl_debugging_internal.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/debugging/libabsl_demangle_internal.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/synchronization/libabsl_synchronization.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/synchronization/libabsl_graphcycles_internal.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/profiling/libabsl_exponential_biased.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/container/libabsl_raw_hash_set.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/container/libabsl_hashtablez_sampler.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/strings/libabsl_cordz_functions.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/strings/libabsl_cordz_handle.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/strings/libabsl_cord_internal.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/strings/libabsl_strings.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/strings/libabsl_strings_internal.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/strings/libabsl_cord.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/strings/libabsl_cordz_info.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/strings/libabsl_str_format_internal.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_ctx.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_block_map.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_apply_multiplier.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/profiler/libruy_profiler_instrumentation.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_allocator.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_tune.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_blocking_counter.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_denormal.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_cpuinfo.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_pack_avx2_fma.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_frontend.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_context.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_thread_pool.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_trmul.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_wait.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_prepacked_cache.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_kernel_avx512.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_kernel_arm.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_pack_arm.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_system_aligned_alloc.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_prepare_packed_matrices.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_pack_avx.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_context_get_ctx.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_have_built_path_for_avx512.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_have_built_path_for_avx.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_kernel_avx.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_pack_avx512.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_kernel_avx2_fma.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/_deps/ruy-build/ruy/libruy_have_built_path_for_avx2_fma.a
PRE_TARGETDEPS += $$PWD/libs/tflite_build/libtensorflow-lite.a

LIBS += -L$$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/base
LIBS += -L$$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/container
LIBS += -L$$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/debugging
LIBS += -L$$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/flags
LIBS += -L$$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/hash
LIBS += -L$$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/numeric
LIBS += -L$$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/profiling
LIBS += -L$$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/status
LIBS += -L$$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/strings
LIBS += -L$$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/synchronization
LIBS += -L$$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/time
LIBS += -L$$PWD/libs/tflite_build/_deps/abseil-cpp-build/absl/types
LIBS += -L$$PWD/libs/tflite_build/_deps/clog-build
LIBS += -L$$PWD/libs/tflite_build/_deps/cpuinfo-build
LIBS += -L$$PWD/libs/tflite_build/_deps/farmhash-build
LIBS += -L$$PWD/libs/tflite_build/_deps/fft2d-build
LIBS += -L$$PWD/libs/tflite_build/_deps/flatbuffers-build
LIBS += -L$$PWD/libs/tflite_build/_deps/ruy-build/ruy
LIBS += -L$$PWD/libs/tflite_build/_deps/ruy-build/ruy/profiler
LIBS += -L$$PWD/libs/tflite_build/_deps/xnnpack-build
LIBS += -L$$PWD/libs/tflite_build/pthreadpool

LIBS += -lpthreadpool
LIBS += -lpthreadpool
LIBS += -lcpuinfo
LIBS += -lflatbuffers
LIBS += -lclog
LIBS += -lXNNPACK
LIBS += -lfarmhash
LIBS += -lfft2d_fftsg2d
LIBS += -lfft2d_fftsg
LIBS += -labsl_bad_optional_access
LIBS += -labsl_bad_variant_access
LIBS += -labsl_status
LIBS += -labsl_civil_time
LIBS += -labsl_time_zone
LIBS += -labsl_time
LIBS += -labsl_throw_delegate
LIBS += -labsl_raw_logging_internal
LIBS += -labsl_malloc_internal
LIBS += -labsl_spinlock_wait
LIBS += -labsl_log_severity
LIBS += -labsl_base
LIBS += -labsl_flags_commandlineflag_internal
LIBS += -labsl_flags_marshalling
LIBS += -labsl_flags_internal
LIBS += -labsl_flags_config
LIBS += -labsl_flags_program_name
LIBS += -labsl_flags
LIBS += -labsl_flags_commandlineflag
LIBS += -labsl_flags_private_handle_accessor
LIBS += -labsl_flags_reflection
LIBS += -labsl_city
LIBS += -labsl_low_level_hash
LIBS += -labsl_hash
LIBS += -labsl_int128
LIBS += -labsl_stacktrace
LIBS += -labsl_symbolize
LIBS += -labsl_debugging_internal
LIBS += -labsl_demangle_internal
LIBS += -labsl_synchronization
LIBS += -labsl_graphcycles_internal
LIBS += -labsl_exponential_biased
LIBS += -labsl_raw_hash_set
LIBS += -labsl_hashtablez_sampler
LIBS += -labsl_cordz_functions
LIBS += -labsl_cordz_handle
LIBS += -labsl_cord_internal
LIBS += -labsl_strings
LIBS += -labsl_strings_internal
LIBS += -labsl_cord
LIBS += -labsl_cordz_info
LIBS += -labsl_str_format_internal
LIBS += -lruy_ctx
LIBS += -lruy_block_map
LIBS += -lruy_apply_multiplier
LIBS += -lruy_profiler_instrumentation
LIBS += -lruy_allocator
LIBS += -lruy_tune
LIBS += -lruy_blocking_counter
LIBS += -lruy_denormal
LIBS += -lruy_cpuinfo
LIBS += -lruy_pack_avx2_fma
LIBS += -lruy_frontend
LIBS += -lruy_context
LIBS += -lruy_thread_pool
LIBS += -lruy_trmul
LIBS += -lruy_wait
LIBS += -lruy_prepacked_cache
LIBS += -lruy_kernel_avx512
LIBS += -lruy_kernel_arm
LIBS += -lruy_pack_arm
LIBS += -lruy_system_aligned_alloc
LIBS += -lruy_prepare_packed_matrices
LIBS += -lruy_pack_avx
LIBS += -lruy_context_get_ctx
LIBS += -lruy_have_built_path_for_avx512
LIBS += -lruy_have_built_path_for_avx
LIBS += -lruy_kernel_avx
LIBS += -lruy_pack_avx512
LIBS += -lruy_kernel_avx2_fma
LIBS += -lruy_have_built_path_for_avx2_fma

LIBS += -ldl

**Comment by FengMu1995** [comment]
@mrdeveloperdude Have you solve this question? I also combined all lib into one folder, Now fewer errors.
But still some errors: 
init.c:-1: error: undefined reference to `cpuinfo_isa'
cpuinfo.cc:-1: error: undefined reference to `cpuinfo_get_processor' 
thread_pool.cc:-1: error: undefined reference to `ruy::BlockingCounter::DecrementCount()'......
Have you met this problem?
