### ISSUE TITLE
Generate SSD anchor box aspect ratios using k-means clustering - Tutorial

### ISSUE THREAD

**Issue by Petros626** [tensorflow/tensorflow#56329]
Does anyone has experience with it? Is it working for TensorFlow 1 or only for 2. Is the point "Upload your own dataset" the point where I'm starting now?

https://colab.research.google.com/github/tensorflow/models/blob/master/research/object_detection/colab_tutorials/generate_ssd_anchor_box_aspect_ratios_using_k_means_clustering.ipynb

**Comment by tsindhuja** [comment]
This code should ideally work with tensorflow 1 as well, provided you have compatible versions of google.protobuf  and object_detection.protos
You can find the compatibility of these versions here -> https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/tensorflow-1.14/

Also, this is one of the helpful articles, https://wandb.ai/wandb/common-ml-errors/reports/How-to-Correctly-Install-TensorFlow-Object-Detection-API--VmlldzozNTM5ODg

Hope this helps :)

**Comment by tilakrayal** [comment]
Hi @Petros626,
Thank you for opening the issue. This issue is more suitable for TensorFlow Models repo. Kindly post the same on the Tensorflow Models repo from [here](https://github.com/tensorflow/models/issues/new/choose). Thank you!

**Comment by Petros626** [comment]
@tilakrayal I did. 
@tsindhuja Thank you for the sources, I will take a look on it, but the first thing I see is that, they recommend protobuf 3.5, but I follow a Tutorial using protobuf 3.4 (maybe the last working version on TF 1.15)

**Comment by tilakrayal** [comment]
@Petros626,
 Could you feel free to move this issue to closed status so that we can track the issue there. Thank you!
