### ISSUE TITLE
Can't build tflite for Java

### ISSUE THREAD

**Issue by drubinstein** [tensorflow/tensorflow#56323]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

macos

### Current Behaviour?

```shell
I've been trying to build tflite for Java using the [build for android guide](https://www.tensorflow.org/lite/android/lite_build). When I try to run 

bazelisk build -c opt --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a \
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
  //tensorflow/lite/java:tensorflow-lite
```
I get the error
```
ERROR: tensorflow/tensorflow/lite/java/BUILD:187:28: While resolving toolchains for target //tensorflow/lite/java:tensorflowlite: no matching toolchains found for types @bazel_tools//tools/android:sdk_toolchain_type
```

Not sure what it means though a similar issu?e I saw in mediapipe claims it has to do with my ANDROID_HOME and ANDROID_NDK_HOME. Any ideas?

### Standalone code to reproduce the issue

```shell
Build command is in the current behavior section.
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @drubinstein ! 
The above error is pointing towards unavailability of SDK tool chain and NDK tool chain during the build process(./configure). If you already have Android studio installed , it will take an existing tool chain from respective folders  else you can download [NDK](https://github.com/android/ndk/wiki/Unsupported-Downloads#ndk-19c-downloads) (19 min version)and [SDK tool](https://developer.android.com/studio/releases/build-tools) (23 min version )chain and export the path before running build process. 

Alternatively you can follow the below process.

0. install Bazel 5.0.0 in macos 
1. git clone https://github.com/tensorflow/tensorflow
2. cd tensorflow
3. git checkout r2.9
4. ./configure or python configure.py
5. say yes to android build when it asks and set path to SDK and NDK.
6. bazelisk build -c opt --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a \
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
  //tensorflow/lite/java:tensorflow-lite

Thank you!
