### ISSUE TITLE
`model.fit(..., verbose=0)` still prints stuff

### ISSUE THREAD

**Issue by m-ahmadi** [tensorflow/tensorflow#56326]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Windows 10 Build 17763

### Python version

3.9

### Current Behaviour?

```shell
I expected to see nothing when calling `model.fit(..., verbose=0)`
```

### Standalone code to reproduce the issue

```python
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
from tensorflow import keras
from keras.layers import InputLayer, Dense

data = [
	[ [0,0], [0] ],
	[ [0,1], [1] ],
	[ [1,0], [1] ],
	[ [1,1], [0] ],
]
x_train = [i[0] for i in data]
y_train = [i[1] for i in data]

model = keras.Sequential([
	InputLayer(2),
	Dense(units=8, activation='sigmoid'),
	Dense(units=1, activation='sigmoid'),
])
model.compile(optimizer=keras.optimizers.SGD(0.6), loss='mean_squared_error')

model.fit(x_train, y_train, batch_size=1, epochs=500, verbose=0)

print(
	model.predict(  [ [0,0], [0,1], [1,0], [1,1] ]  )
)
```
![Untitled](https://user-images.githubusercontent.com/16363767/171522020-7946b036-376b-4ca0-8a55-5150263b5a76.png)

### Relevant log output

_No response_</details>

**Comment by rajivhockey97** [comment]
The method for fit has nothing defined for verbose = 0. Find attached screenshot from tensorflow/tensorflow/python/keras/engine/training.py 

![Keras_verbose](https://user-images.githubusercontent.com/25576606/171609005-7a09d570-e9aa-44fc-afde-2522dcf69400.PNG)

**Comment by tilakrayal** [comment]
Hi @m-ahmadi,
Thank you for opening the issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
