### ISSUE TITLE
Can Tensorflow provide a hardware training/inference standard for hardware accelerator developers?

### ISSUE THREAD

**Issue by streaver91** [tensorflow/tensorflow#56331]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

any

### Custom Code

No

### Current Behaviour?

```shell
It is difficult to compile and run common machine learning libraries on custom SIMD accelerators.
```

### Standalone code to reproduce the issue

```shell
N/A
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @streaver91 !
Deploying through TF Lite is preferred mode for Android, IOS and other edge devices. TFLite is being used other 32 bit memory microcontrollers and consumes very less compared to Original model.

Tested Platforms are mentioned [ here ](https://www.tensorflow.org/lite/microcontrollers#supported_platforms). But Developers are able to deploy in other micrcontrollers through [EdgeImpulse service](https://www.edgeimpulse.com/). (Build with a dataset, test and get your model according to your hardware).

Standard Procedure goes like this . 
1. Convert TF model to TF Lite with suitable [optimization ](https://www.tensorflow.org/model_optimization/api_docs/python/tfmot/quantization)and [quantization](https://www.tensorflow.org/lite/performance/model_optimization) techniques.
2. Get the .cc (Character buffer ),.cpp files  from Lite model using XXD converter.
3. Import those libraries in your respective IDE.
[Ref](https://colab.sandbox.google.com/github/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/examples/hello_world/train/train_hello_world_model.ipynb#scrollTo=JvRy0ZyMhQOX)

Attaching  few existing documentation as reference.

1. Post training[ Integer quantization](https://www.tensorflow.org/lite/performance/post_training_integer_quant) (For  Integer only accelerated hardwares like Edge TPU)
2. [CMake lite](https://www.tensorflow.org/lite/guide/build_cmake) (Cross compiling with other tool chain  is there)
3.  [TFLite-micro ](https://github.com/tensorflow/tflite-micro)(Maintained repo and prefered for microcontrollers.
4.  [Edge TPU documentation.](https://coral.ai/docs/edgetpu/tflite-python/#update-existing-tf-lite-code-for-the-edge-tpu)
5.   [Mediapipe models ](https://google.github.io/mediapipe/) (Highly tuned and optimizes TFlite models and compatible across all kinds of hardware)

Please let us know if you need any other details.

Thank you!
