### ISSUE TITLE
Is it possible to change colour of specific keypoint in iOS

### ISSUE THREAD

**Issue by IBSApple** [tensorflow/tensorflow#56332]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML', 'Metal']

### Custom Code

Yes

### OS Platform and Distribution

MacOS

### Mobile device

iPhone X

### Current Behaviour?

```shell
I want to change colour of specific body landmarks. Is it possible to achieve in iOS using Swift
```

### Standalone code to reproduce the issue

```shell
Multicolor on overlay image
```

### Relevant log output

_No response_</details>

**Comment by IBSApple** [comment]
<img width="659" alt="Screenshot 2022-06-02 at 12 18 11 PM" src="https://user-images.githubusercontent.com/71369657/171570355-66b2c3cd-84c5-462f-9b9a-30910d7cbba6.png">
Like this

**Comment by IBSApple** [comment]
Any update?

**Comment by IBSApple** [comment]
???

**Comment by IBSApple** [comment]
???

**Comment by IBSApple** [comment]
Hello

**Comment by IBSApple** [comment]
I can't understand this...

**Comment by IBSApple** [comment]
??

**Comment by sachinprasadhs** [comment]
Hi, This is something not in our scope, I think it is better to handle it in the UI side. 
From TFLite side, we don't have any plan to support on this. Thanks!

**Comment by mihaimaruseac** [comment]
Not a TF issue, should be closed
