### ISSUE TITLE
`tf.image.resize_with_pad` raises `InvalidArgumentError` but the behavior is not documented

### ISSUE THREAD

**Issue by kyamagu** [tensorflow/tensorflow#56333]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

binary

### Tensorflow Version

v2.9.0-18-gd8ce9f9c301 2.9.1

### Custom Code

No

### OS Platform and Distribution

macOS 12.4

### Python version

3.9

### Current Behaviour?

```shell
The documentation only states `tf.image.resize_with_pad` raises `ValueError`.
https://www.tensorflow.org/api_docs/python/tf/image/resize_with_pad#raises

The function actually raises `InvalidArgumentError` if the resized image becomes too small (zero width or zero height). The function should raise a `ValueError` corresponding to this situation, or at least document that the function raises `InvalidArgumentError`.

The same applies `tf.image.resize` with `preserve_aspect_ratio=True`.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
tf.image.resize_with_pad(tf.ones((1, 100, 1)), target_height=10, target_width=10)
```
```


### Relevant log output

```shell
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/var/folders/xx/0bq30ljn7dz9055_2f5kd2csqm1fwc/T/ipykernel_41817/1900687440.py in <module>
----> 1 tf.image.resize_with_pad(tf.ones((1, 100, 1)), target_height=10, target_width=10)

~/projects/ailab-psd-processing/.venv/lib/python3.7/site-packages/tensorflow/python/util/traceback_utils.py in error_handler(*args, **kwargs)
    151     except Exception as e:
    152       filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153       raise e.with_traceback(filtered_tb) from None
    154     finally:
    155       del filtered_tb

~/projects/ailab-psd-processing/.venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   7162 def raise_from_not_ok_status(e, name):
   7163   e.message += (" name: " + name if name is not None else "")
-> 7164   raise core._status_to_exception(e) from None  # pylint: disable=protected-access
   7165 
   7166 

InvalidArgumentError: output dimensions must be positive [Op:ResizeBilinear]
```
```
</details>

**Comment by sushreebarsa** [comment]
@kyamagu For target width and target height if the value is negative or zero, it is raising value error only. Please refer to this [gist ](https://colab.research.google.com/gist/sushreebarsa/8a8723142c03fdbf4202fa145359871f/56333.ipynb#scrollTo=qJa4hTHSfjca)here. Could you let us know if you want to add the 'InvalidArgumentError' for a specific range in the documentation. 
Thank you!

**Comment by kyamagu** [comment]
@sushreebarsa Yes, I want the documentation to be clear on when `InvalidArgumentError` happens. Target height or width can be invalid when certain positive value is given.

**Comment by sushreebarsa** [comment]
@kyamagu I have created a PR to fix this issue. Please let us know if any further modifications are required.
Thank you!

**Comment by sushreebarsa** [comment]
@kyamagu Sorry for the late response!
I tried to test the range of target height or width. It can be invalid when certain positive value that is given for (target width<100). Could you please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/8a8723142c03fdbf4202fa145359871f/56333.ipynb#scrollTo=VwtYE_MjupJY) and confirm the same?
Thank you!

**Comment by mihaimaruseac** [comment]
Ideally the code would return the same type of error in both cases here.

**Comment by sachinprasadhs** [comment]
As you have mentioned, it throws `InvalidArgumentError` error for very small output value,  but it does not have any standard restriction on the range of values to document it.
