### ISSUE TITLE
module 'tensorflow.python.ops.gen_array_ops' has no attribute '_expand_dims'

### ISSUE THREAD

**Issue by JerryKu009** [tensorflow/tensorflow#5633]
After following CMake build for windows, python cannot be loaded with below error message.
>>> import tensorflow
AttributeError: module 'tensorflow.python.ops.gen_array_ops' has no attribute '_expand_dims'
After checking git history, it's related with checkin from Andrew Selle.
SHA-1: a41f0eae0cca59ff211495bd3e9da0daf4ed01e8

### Environment info
Operating System:
Windows Server 2012 R2

**Comment by mrry** [comment]
It sounds like you have an old copy of `tensorflow/python/ops/gen_array_ops.py` that wasn't generated after updating past a41f0ea (which updates `hidden_ops.txt`). Could you try deleting the `tf_python/` directory and rerunning the build?

**Comment by JerryKu009** [comment]
To install tensorflow on windows, whl file is created at
tensorflow\contrib\cmake\build\tf_python\dist.
I followed below instruction.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md
To build and out whl, below command is necessary.
MSBuild /p:Configuration=Release tf_python_build_pip_package.vcxproj
Still, same error with recent git.


2016-11-16 13:40 GMT+09:00 Derek Murray <notifications@github.com>:

**Comment by mrry** [comment]
Closing this due to lack of recent activity. Please try the pre-built binaries.
