### ISSUE TITLE
How to use tf.data API with multiple inputs of different shapes

### ISSUE THREAD

**Issue by winthropharvey** [tensorflow/tensorflow#56343]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

Yes

### Python version

3.10

### Current Behaviour?

I am trying to make a tensorflow model with two different inputs, one will have shape [9,10], the other will just have shape [8].

I am furthermore trying to use tf.dataset to iterate over my inputs. However, whenever I try to do so it fails with the following error:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shapes of all inputs must match: values[0].shape = [9,10] != values[1].shape = [8]
     [[{{node packed}}]] [Op:IteratorGetNext]
```

But surely it is possible to have differently shaped inputs into different branches! This is exactly the case in the example in tensorflow's functional API guide, however they do not use tf.dataset so I can't simply follow their example.

To give a little more specifics into the problem I am trying to solve and why I am using the tf.dataset api:

I am doing a time-series problem over multiple sites where my inputs are of two types: those that vary with time, and those that do not but do vary by site. For the time being, I'm just trying to estimate the next time step.

First, I get my dynamic covariates and targets in a sliding window using the timeseries_dataset_from_array util.

```
    train_ds = tf.keras.preprocessing.timeseries_dataset_from_array(
        input_data, targets, sequence_length=window_size, batch_size=256)
```

This works perfectly and I can train models using this dataset as is.

However, I want to also use the static covariates from the specific site that the time series data is coming from. The site id is included in the window input data in its own column, though it gets removed before training. Thus, what I am trying to do is grab the static covariates for the site and attach it as a separate input to my dataset.

```
    train_ds = train_ds.map(lambda x, y: (tf.py_function(attach_static_covariates, [x, idindex, colnames], [tf.float64, tf.float64]), y))

    train_ds = train_ds.map(lambda x, y: ({'dynamic': x[0], 'static': x[1]}, y))

```
The code for the attach_static_covariates method is:

```
def attach_static_covariates(x, idindex, colnames):
    id = x[0, idindex].numpy()
    static_cov = static_df.iloc[int(id)]
    #This just filters out the id column, now that it has served its purpose
    x = tf.gather(x, [i for i in range(len(colnames)) if i != idindex])

    return (x, static_cov)
```

I've confirmed that my code can run and train on multiple inputs provided by the above method provided they are the same size (e.g. if I return (x, x) I can run my model on two copies of the dynamic covariates inputted into two different branches of my model). The problem is not due to a mismatch or a bad model definition because I get the same error from the following code:

```
    for feature_batch, label_batch in train_ds.take(1):
        print(feature_batch)
```

I've looked everywhere on google and the tensorflow git and I can't find anyone else with this problem, except for https://github.com/tensorflow/tensorflow/issues/48003, which points to ragged tensors which I don't believe is what I am looking for.  The ragged tensor use case seems to be for variable length entries, but I'm just trying to input two different, but fixed, shapes. And yet it surely MUST be possible to have differently shaped inputs using tf.dataset! I can't imagine that such an incredibly common use case would be completely unsupported. However, I can't find any examples online where someone has multiple inputs of different shapes and uses tf.dataset api. Any help or links to such examples would be greatly appreciated.
```

EDIT: I did find a workaround, which is in the colab, where you embed the py_function step into another mapped function returning the dictionaries, so that no step ever produces a dataset with two different shaped inputs instead of a dict.  Still, I'd be interested in knowing if there is some other canonical way to get past this.


### Standalone code to reproduce the issue


https://colab.research.google.com/drive/1EnaJoUULl-fyAwlcG_5tcWfsRFVCOMtv#scrollTo=PHvsIOx6-Uux
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@chunduriv I was able to replicate the issue on colab using, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/93b1cf5aa85c717c20db2054d1e18844/multipleinput.ipynb#scrollTo=uIVAjq0EJs7R) here for reference. Thank you!

**Comment by gowthamkpr** [comment]
@winthropharvey As mentioned [here](https://github.com/llvm/llvm-project/issues/55386), try using `tf.data.Dataset.from_generator()` or try to zip the dataset to combine various inputs using `tf.data.Dataset.zip`.

**Comment by winthropharvey** [comment]
The link you included doesn't seem related

**Comment by gowthamkpr** [comment]
I'm sorry. Just edited it. PTAL. Thanks!
