### ISSUE TITLE
Tensorflow argsort sometimes produces non-deterministic results

### ISSUE THREAD

**Issue by com98** [tensorflow/tensorflow#56349]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

No

### OS Platform and Distribution

Mac OS Monterey 12.3.1 with M1 Pro CPU 

### Python version

3.9.12

### Current Behaviour?

```shell
Hey there!

I am currently dealing with a very weird tensorflow problem, which I think is a bug. I am trying to develop an inference application and for that purpose I have to apply the `tf.argsort` function. 

I fetch a slice from a 2D tensor from an Embedding layer:


embedding_layer_tensor[index]
```

Which gives me a 1D tensor with shape (n,). Then I want to sort those values in descending order and return their indexes in sort order - hence I use the `tf.argsort function`.

But I sometimes get very weird results. Sometimes it works, sometimes the results just don't make any sense.

Here's an example:

```
# Below is my 1D tensor:
sample_constant = tf.constant([1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 9, 9, 9, 9, 5.171316e-32, 0.000000e+00, 0.000000e+00, 0.000000e+00, 2, 3, 4, 1.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00])

# Now I apply the argsort function on it:
tf.argsort(sample_constant, axis=0)
```

Sometimes the argsort function returns:
```
array([19, 13,  5, 14,  6, 12, 20,  4, 11,  3, 21,  1, 18,  2,  0, 15,  0,
        0,  0,  0,  0,  0], dtype=int32)>
```

But sometimes it also returns this which makes no sense:

```
<tf.Tensor: shape=(22,), dtype=int32, numpy=
array([          7,           9,          10,           8,          17,
                16,          15,           3,          21,           1,
                18,           2,           0,          11,          19,
                13, -1069547520, -1065353216, -1082130432, -2147483648,
       -2147483648, -1082130432], dtype=int32)>
```

Can someone help me out with this or try if you can reproduce this error? 

Thanks! :)
```


### Standalone code to reproduce the issue

```shell
sample_constant = tf.constant([1.000000e+00, 1.000000e+00, 1.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00, 9, 9, 9, 9, 5.171316e-32, 0.000000e+00, 0.000000e+00, 0.000000e+00, 2, 3, 4, 1.000000e+00, 0.000000e+00, 0.000000e+00, 1.000000e+00])

# Needs to be performed many times:
for i in range(0,10):
   tf.argsort(sample_constant, axis=0)
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@com98 Could you try with the latest TF version 2.9.0 and have a look at this[ gist](https://colab.research.google.com/gist/sushreebarsa/eef5999fffabfd0379704387b31b7a01/56349.ipynb) for reference. Please let us know if it helps?
Thank you!

**Comment by sushreebarsa** [comment]
@com98 Thank you for the update!
