### ISSUE TITLE
Locating the numpy include path can "fail" incorrectly

### ISSUE THREAD

**Issue by SnoopJeDi** [tensorflow/tensorflow#56346]
### Description

[`_get_numpy_include()`](https://github.com/tensorflow/tensorflow/blob/d7e521a1ad21681855b439b9c2a05837c804e488/third_party/py/python_configure.bzl#L188-L201) will fail if importing `numpy` causes _anything_ to be written to stderr, even if the command succeeds. I found this while helping a user in #python on the Libera.chat IRC network debug [a failure](https://github.com/google/yggdrasil-decision-forests/issues/19) when building `yggdrasil-decision-forests`. When they import `numpy` on their system, they get the following non-fatal warning:

```
OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
```

Which causes `execute()` to fail. It looks like the `allow_failure` parameter for that function is meant to address this, so adding this argument should fix the issue in this specific case, but I'm not sure what the other implications might be. (as an aside, this parameter is confusingly documented, I have opened #56345 to address that)

Insight from someone who is more familiar with TF's build system would be appreciated, but inspecting stdout/stderr strikes me as a very strange way to work out whether or not the executed process failed. Is there a reason this bit of code does not check the [`return_code`](https://bazel.build/rules/lib/exec_result) of the raw execution?

**Comment by tilakrayal** [comment]
@SnoopJeDi,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue. Thank you!

**Comment by SnoopJeDi** [comment]
Re-filed as #56373 to comply with the above request because there is not a tidy way to add the templated information to an existing ticket.
