### ISSUE TITLE
Seeing E tensorflow/core/grappler/costs/op_level_cost_estimator.cc:1104] Incompatible Matrix dimensions 

### ISSUE THREAD

**Issue by whatdhack** [tensorflow/tensorflow#56355]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

No

### OS Platform and Distribution

Linux

### Python version

3.9.7

### CUDA/cuDNN version

11.6.2

### Current Behaviour?

```shell
Seeing the following errors on enabling profiler. 

2022-06-04 01:32:28.169748: E tensorflow/core/grappler/costs/op_level_cost_estimator.cc:1104] Incompatible Matrix dimensions
```

### Standalone code to reproduce the issue

```shell
Happens with some gemm/mtmul based models.
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
Hi @whatdhack,
To expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thank you!

**Comment by whatdhack** [comment]
@tilakrayal, happens only when the profiler is enabled.

**Comment by gadagashwini** [comment]
Hi @whatdhack, I didn’t see any issue when Profiler is enabled. Take a look at gist [here](https://colab.research.google.com/drive/1_Ow5qz3pXmoDdrCvBtOjGwFaY9sekgLN?usp=sharing). Thanks!

**Comment by whatdhack** [comment]
@gadagashwini ,  saw in GPUs - can you run your gist in GPU ?   It may not be that straightforward to reproduce.

**Comment by gadagashwini** [comment]
Hi @whatdhack, I ran the code with GPU enabled, I didn’t see any issue take a look at [gist](https://colab.research.google.com/drive/1_Ow5qz3pXmoDdrCvBtOjGwFaY9sekgLN?usp=sharing). Thank you!
