### ISSUE TITLE
tf.saved_model.save() excessive function tracing

### ISSUE THREAD

**Issue by thierryherrmann** [tensorflow/tensorflow#56370]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3,8.10

### Current Behaviour?

```shell
This is filed against TF 2.8 but the behavior described appeared when upgrading from TF 2.3 to TF 2.4.

Create a tf.Module subclass containing a tf.keras.models.Model subclass.
Add tf.functions to the tf.Module that call the model.
Saved the tf.Module with tf.saved_model.save() in order to reload and use it in a language other than python.

With TF2.3, the functions are traced only once.
With TF2.4, the functions are traced twice.

With large models, this can almost double the model save time (e.g. up to 40s for a distilbert model with 6 layers).
```

### Standalone code to reproduce the issue

```shell
Execute this same code with TF2.3.2 and TF2.4.4 (output with TF2.8 is the same as for 2.4.4)


import tensorflow as tf
print('tf version', tf.__version__)

import os

F1_SIG=[tf.TensorSpec([None, None], tf.float32, name='inputs_1')]
F2_SIG=[tf.TensorSpec([None], tf.float32, name='inputs_2')]

class CustomModel(tf.keras.models.Model):
    def __init__(self, **kwargs):
        super().__init__(**kwargs) # handles standard args (e.g., name)

    def call(self, x):
        _x = tf.random.normal((2,3,4)) + x 
        return _x

class CustomModule(tf.Module):
    def __init__(self):
        self.model = CustomModel()

    @tf.function(input_signature=F1_SIG)
    def f1(self, x):
        print('tracing f1')
        return self.model(x[0])

    @tf.function(input_signature=F2_SIG)
    def f2(self, x):
        print('tracing f2')
        return self.model(x)

x = tf.random.uniform((2,4))*10

saved_model_dir='saved_model'
os.makedirs(saved_model_dir, exist_ok=True)

module = CustomModule()
signatures = {"serving_default": module.f1.get_concrete_function(*F1_SIG),
              "serve_sig_v2"   : module.f2.get_concrete_function(*F2_SIG),
              }
tf.saved_model.save(module, saved_model_dir, signatures=signatures)
```

Output with tensorflow 2.3.2:
```
tf version 2.3.2
tracing f1
tracing f2
INFO:tensorflow:Assets written to: saved_model/assets
```

Output with tensorflow 2.4.4:
```
tf version 2.4.4
tracing f1
tracing f2
tracing f1
tracing f2
INFO:tensorflow:Assets written to: saved_model/assets
```

Why are the functions traced a second time with TF>=2.4 ?

TF2.3 colab:
https://colab.research.google.com/drive/19iniJKEcFmhkNDVe6sbseOyASWb3oCYC?usp=sharing

TF2.4 colab: 
https://colab.research.google.com/drive/1NVCSiSednJnnZqk_s1VmOsIMSUluaLP7?usp=sharing

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@thierryherrmann tf.function has a mechanism, that lets you control this function tracing, by defining a method __tf_trace_type__. Please have a look at this [link](https://www.tensorflow.org/guide/function#use_the_tracing_protocol) for more details and let us know if it helps?
Thank you!

**Comment by thierryherrmann** [comment]
Thanks but unfortunately that link only covers retracing when calling the function several times with different arguments.
In this issue, tracing (with TF2.4) is done several times for a single invocation (or by calling `pretty_printed_concrete_signatures()` or `get_concrete_function()` like in the colabs).

Things become weirder when we add a `Embedding` layer in the custom model.
This is shown by this simple code, pastable in any colab:
```python
import tensorflow as tf
print('tf version', tf.__version__)
import os

SIG=[tf.TensorSpec([None], tf.int32)]

class CustomModel(tf.keras.models.Model):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.embedding = tf.keras.layers.Embedding(input_dim=3, output_dim=4, mask_zero=True)

    def call(self, x):
        _x = tf.reduce_sum(self.embedding(x))   # <<<< new!
        _x = tf.random.normal((3,)) + _x 
        return _x

class CustomModule(tf.Module):
    def __init__(self):
        self.model = CustomModel()

    @tf.function(input_signature=SIG)
    def f1(self, x):
        print('tracing f1')
        return self.model(x)


module = CustomModule()
# added CustomModel.embedding ==> module.f1 now traced 2 times instead of once (same in TF2.3 and TF2.4)
print('======== pretty_printed_concrete_signatures() ========\n', module.f1.pretty_printed_concrete_signatures())  

# with tf.saved_model.save(), TF2.4 does an extra tracing
print('======= tf.saved_model.save() =======')
module = CustomModule()
os.makedirs('saved_model', exist_ok=True)
signatures = {"serving_default": module.f1.get_concrete_function(*SIG)}
tf.saved_model.save(module, 'saved_model', signatures=signatures) # module.f1() traced 3 times with TF2.4, 2 times with TF2.3
```

Output with TF2.3.2:
```
tf version 2.3.2
tracing f1
tracing f1
======== pretty_printed_concrete_signatures() ========
 f1(x)
  Args:
    x: int32 Tensor, shape=(None,)
  Returns:
    float32 Tensor, shape=(3,)

f1(x)
  Args:
    x: int32 Tensor, shape=(None,)
  Returns:
    float32 Tensor, shape=(3,)
======= tf.saved_model.save() =======
tracing f1
tracing f1
INFO:tensorflow:Assets written to: saved_model/assets
```

Output with TF2.4.4 (same with TF2.8.x):
```
tf version 2.4.4
tracing f1
tracing f1
======== pretty_printed_concrete_signatures() ========
 f1(x)
  Args:
    x: int32 Tensor, shape=(None,)
  Returns:
    float32 Tensor, shape=(3,)

f1(x)
  Args:
    x: int32 Tensor, shape=(None,)
  Returns:
    float32 Tensor, shape=(3,)
======= tf.saved_model.save() =======
tracing f1
tracing f1
tracing f1
INFO:tensorflow:Assets written to: saved_model/assets
```

**Comment by sushreebarsa** [comment]
@chunduriv  I was able to replicate the issue on colab, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/193d28cf87e74c1cc47f47f4451fd606/56370.ipynb#scrollTo=03ntopAhCcPQ) for reference. Thank you!

**Comment by sachinprasadhs** [comment]
@k-w-w , Any inputs on the above comment. Thanks!

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
