### ISSUE TITLE
word2vec_basic global_variables_initializer error

### ISSUE THREAD

**Issue by vkaracic** [tensorflow/tensorflow#5637]
I'm running Tensorflow version 0.11.0 which has [this](https://github.com/tensorflow/tensorflow/commit/4cbdead95f22de74bcbc72a68c9a38d465202db9#diff-ae1a8f7b66539f000615a4ab7e4b2151) commit included and yet I get the following error when running the ``word2vec_basic.py`` script:
```
##################################################
0.11.0
##################################################
Found and verified text8.zip
Data size 17005207
Most common words (+UNK) [['UNK', 418391], ('the', 1061396), ('of', 593677), ('and', 416629), ('one', 411764)]
Sample data [5239, 3084, 12, 6, 195, 2, 3137, 46, 59, 156] ['anarchism', 'originated', 'as', 'a', 'term', 'of', 'abuse', 'first', 'used', 'against']
3084 originated -> 12 as
3084 originated -> 5239 anarchism
12 as -> 6 a
12 as -> 3084 originated
6 a -> 195 term
6 a -> 12 as
195 term -> 6 a
195 term -> 2 of
Traceback (most recent call last):
  File "word2vec_basic.py", line 183, in <module>
    init = tf.global_variables_initializer()
AttributeError: 'module' object has no attribute 'global_variables_initializer'
```

The part at the top with hashtags is something I added to print out the tf version that is used.
When I rename [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/word2vec/word2vec_basic.py#L178) line back to ``initialize_all_variables`` it works.

**Comment by girving** [comment]
@vkaracic I just checked, and it doesn't look like 0.11.0 has that commit.  Are you sure?

**Comment by vkaracic** [comment]
I'm sorry, I was looking at the wrong file. Nevertheless ``word2vec_basic`` script breaks, I guess there is no point in opening a PR reverting that one line back to ``initialize_all_variables`` if that commit is going to be in the next release?

**Comment by girving** [comment]
@vkaracic The 0.11.0 version of `word2vec_basic` already uses `initialize_all_variables`, so I think all is well.  You're trying to run a new version of a tutorial with an old version of tensorflow.
