### ISSUE TITLE
How to install tensorflow v<2.0?

### ISSUE THREAD

**Issue by skyientist** [tensorflow/tensorflow#56376]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.?

### Custom Code

No

### OS Platform and Distribution

mac 12.4

### Python version

3.8.11

### Current Behaviour?

```shell
For code I am running, I need tensorflow<2.0, how do I install this? pip will not let me install <2.2.0
```

### Standalone code to reproduce the issue

```shell
pip install tensorflow==1.4
ERROR: Could not find a version that satisfies the requirement tensorflow==1.4 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1)
ERROR: No matching distribution found for tensorflow==1.4
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@skyientist,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.9 and check if you are facing the same issue.

Kindly take a look at the doc [link](https://www.tensorflow.org/install/source#tensorflow_1x) for the installation of 1.x. Thank you!

**Comment by skyientist** [comment]
Python 3.8.11 (default, Aug  6 2021, 08:56:27) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> tensorflow.__version__
'2.9.1'
>>> import eleanor
>>> star = eleanor.Source(tic=270341214,sector=27,tc=True)
>>> data = eleanor.TargetData(star,height=15,width=15,bkg_size=31,do_psf=True,do_pca=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.8/site-packages/eleanor-2.0.5-py3.8.egg/eleanor/targetdata.py", line 245, in __init__
    self.psf_lightcurve()
  File "/opt/anaconda3/lib/python3.8/site-packages/eleanor-2.0.5-py3.8.egg/eleanor/targetdata.py", line 889, in psf_lightcurve
    tf.logging.set_verbosity(tf.logging.ERROR)
AttributeError: module 'tensorflow' has no attribute 'logging'

**Comment by skyientist** [comment]
bazel build --config=v1 [--config=option] //tensorflow/tools/pip_package:build_pip_package
ERROR: The 'build' command is only supported from within a workspace (below a directory having a WORKSPACE file).
See documentation at https://docs.bazel.build/versions/master/build-ref.html#workspace

**Comment by tilakrayal** [comment]
@skyientist,
Could you provide the complete error log to analyse the issue. Also kindly provide the tensorflow version, CUDA, cuDNN, Bazel version you are trying to install. Thank you!
