### ISSUE TITLE
VRAM-hungry LSTM monster

### ISSUE THREAD

**Issue by MovsisyanM** [tensorflow/tensorflow#56387]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8.10

### CUDA/cuDNN version

11.6

### GPU model and memory

3x RTX 3090 (24Gb of VRAM each)

### Current Behaviour?

```shell
A bug happened!
Compiling a simple model with an lstm cell fills the VRAM to the maximum, before even fitting.
```

### Standalone code to reproduce the issue

```shell
https://github.com/MovsisyanM/sandbox/blob/main/random/LSTM-hell.ipynb
```

### Relevant log output

_No response_</details>

**Comment by MovsisyanM** [comment]
Keywords to make it easier for other people with the same problem to find this:
```
InternalError: Graph execution error:

Failed to call ThenRnnForward with model config
```

**Comment by tilakrayal** [comment]
@MovsisyanM,
While i was trying to execute the given code, I donot find any issue and the code was executed without any errors. Kindly find the [gist](https://colab.research.google.com/gist/tilakrayal/60eed4b77174f3c4eed75384846795f7/untitled16.ipynb) and let me know if we are missing anything. Thank you!

**Comment by MovsisyanM** [comment]
I tried running it on another device and it worked perfectly, but for some reason it doesn't work on this device which is a lambda workstation.

**Comment by MovsisyanM** [comment]
This issue arises when using RNN-based cells (RNN, LSTM, GRU)

**Comment by tilakrayal** [comment]
@gowthamkpr,
I was able to execute the given code without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/60eed4b77174f3c4eed75384846795f7/untitled16.ipynb). 
As mentioned in this [comment](https://github.com/tensorflow/tensorflow/issues/56387#issuecomment-1149568587), the user is facing an issue on lambda workstation. Thank you!

**Comment by MovsisyanM** [comment]
There is a workaround, by running
`export LD_LIBRARY_PATH=/usr/lib/python3/dist-packages/tensorflow`
and then running the lstm training file while supplying that same env variable to it like this:
`LD_LIBRARY_PATH=/usr/lib/python3/dist-packages/tensorflow python3 lstm_model_file.py

Thank you `markd` from lambda labs forums.

**Comment by sachinprasadhs** [comment]
@MovsisyanM , If your issue is resolved by setting the path as mentioned above( specific to lambda workstation). Could you please close this issue. Thanks!
