### ISSUE TITLE
train inception from scratch: imagenet_train not a target

### ISSUE THREAD

**Issue by zzzrpagliari** [tensorflow/tensorflow#5638]
I successfully compiled tensorflow and I was able to run the retrain binary with my own images. 

I'd like to retrain inception from scratch, as described [here](https://github.com/tensorflow/models/tree/master/inception), but the package is not available:

```
$ bazel build inception/imagenet_train
ERROR: no such target '//:inception/imagenet_train': target 'inception/imagenet_train' not declared in package
```

**Comment by girving** [comment]
Note that inception is in a different `models` repository.

**Comment by zzzrpagliari** [comment]
This is what I see under models

```
$ bazel build tensorflow/models/
tensorflow/models/embedding:  tensorflow/models/embedding/  tensorflow/models/image/      tensorflow/models/rnn:        tensorflow/models/rnn/  
```

I don't see imagenet_train

**Comment by girving** [comment]
@zzzrpagliari If you want to find inception in the models repo, please click on your own link from the original comment.
