### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'numpy' while  defining a custom loss

### ISSUE THREAD

**Issue by varungupta31** [tensorflow/tensorflow#56389]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes, a custom loss metric.
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS Linux 7
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: NA
-   **TensorFlow installed from (source or binary)**: pip
-   **TensorFlow version (use command below)**: 2.0.0
-   **Python version**: 3.6.13
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:  CUDA 10.2/ cuDNN 7.6.5
-   **GPU model and memory**:  Nvidia GTX 1080 Ti 12 GB

### Describe the problem
I'm creating a custom loss function in Keras, and am getting the error `AttributeError: 'Tensor' object has no attribute 'numpy'`. As per discussion on [StackOverflow](https://stackoverflow.com/questions/52357542/attributeerror-tensor-object-has-no-attribute-numpy), and Github([#27519](https://github.com/tensorflow/tensorflow/issues/27519),[#35393](https://github.com/tensorflow/tensorflow/issues/35393)), this is due to the code not running in eager execution mode. I have checked, with

`tf.executing_eagerly()`

and my code is indeed runnning in eager execution.
Also, these discussion do not help me solve my issue.

### Source code / logs
My custom metric has these two additional operations -->

```
 y_pred_copy = tf.math.reduce_max(y_pred_copy, axis=-1, keepdims=True)
 y_pred_copy = tf.image.resize(y_pred_copy, (8, 16), method="bilinear")
```
(The loss metric defined without these works without the error. However, my custom loss metric require these operations (calculating max val to reduce tensor channels from 2 to 1, and to resize the tensor using interpolation) to be performed.

Kindly help me out,
thanks. 

**Edit 01 (Adding my Custom loss for further clarity along with the other custom loss that works without error)**

**Custom Metric (Produces Error)**
```
def self_balanced_focal_loss_attention(attention_mask,alpha=3, gamma=2.0):
    
    def loss(y_true, y_pred):
    
    	#loss between predicted_mask and ground_truth mask
        y_pred = backend.softmax(y_pred, -1)
        cross_entropy = backend.categorical_crossentropy(y_true, y_pred)
        
        sample_weights = backend.max(backend.pow(1.0 - y_pred, gamma) * y_true, axis=-1)
        
        pixel_rate = backend.sum(y_true, axis=[1, 2], keepdims=True) / backend.sum(backend.ones_like(y_true),
                                                                                   axis=[1, 2], keepdims=True)
        class_weights = backend.max(backend.pow(backend.ones_like(y_true) * alpha, pixel_rate) * y_true, axis=-1)
        
        final_loss = class_weights * sample_weights * cross_entropy
        loss_gt =  backend.mean(backend.sum(final_loss, axis=[1, 2]))
        
        #loss between predicted_mask and attention_mask        
        y_pred_copy = y_pred

        y_pred_copy = tf.math.reduce_max(y_pred_copy, axis=-1, keepdims=True)
        y_pred_copy = tf.image.resize(y_pred_copy, (8, 16), method="bilinear")

        cross_entropy = backend.categorical_crossentropy(attention_mask, y_pred_copy)

        sample_weights = backend.max(backend.pow(1.0 - y_pred_copy, gamma) * attention_mask, axis=-1)

        pixel_rate = backend.sum(attention_mask, axis=[1, 2], keepdims=True) / backend.sum(backend.ones_like(attention_mask),
                                                                                   axis=[1, 2], keepdims=True)
        class_weights = backend.max(backend.pow(backend.ones_like(attention_mask) * alpha, pixel_rate) * attention_mask, axis=-1)

        final_loss = class_weights * sample_weights * cross_entropy
        loss_attention =  (-1)*backend.mean(backend.sum(final_loss, axis=[1, 2]))
        #combining the two losses
        return ((loss_attention+loss_gt)/2)

    return loss
```
**Custom Metric (Runs without Error)**

```
def self_balanced_focal_loss(alpha=3, gamma=2.0):
    def loss(y_true, y_pred):
        # cross entropy loss
        y_pred = backend.softmax(y_pred, -1)
        cross_entropy = backend.categorical_crossentropy(y_true, y_pred)

        sample_weights = backend.max(backend.pow(1.0 - y_pred, gamma) * y_true, axis=-1)
        pixel_rate = backend.sum(y_true, axis=[1, 2], keepdims=True) / backend.sum(backend.ones_like(y_true),
                                                                                   axis=[1, 2], keepdims=True)
        class_weights = backend.max(backend.pow(backend.ones_like(y_true) * alpha, pixel_rate) * y_true, axis=-1)
        final_loss = class_weights * sample_weights * cross_entropy
        
        return backend.mean(backend.sum(final_loss, axis=[1, 2]))

    return loss
```

**Comment by varungupta31** [comment]
@sushreebarsa Thanks for your reply.
I understand that TF v2.0 is not supported, but my institute's server does not have a compatible GPU (and thus the required CUDA/cuDNN drivers) for the latest version.

I looked at the shared gist, and no it wasn't much helpful.
(I know how to install the latest tensorflow and there didn't seem to any other new info in that gist)

Although, I'm not able to reason why the 2nd code (without attention loss) works, but the 1st one doesn't.
Three major changes introduced in code 1 are --> 1) Tensors are reshaped 2) Additional loss between pred_mask and attention_mask is computed. 3) Losses are combined (averaged) and then returned.

Are these operations causing the problem with eager execution, etc.?

Let me know if anything strikes you as possibly wrong, causing this error.
Thanks again.

**Comment by sushreebarsa** [comment]
@varungupta31 Thank you for you response!
TF 2.0 does not really contain all the changes to prevent code using invalid shapes from crashing the interpreter via CHECK-failures. It is unlikely for TF 2.0 version to receive any bug fixes except when we have security patches. There is a high possibility that this was fixed with later TF versions. As older versions are not actively supported please post this issue on TF [Forum](https://discuss.tensorflow.org/) where, there is a larger community to get you the right help.
Thank you!

**Comment by varungupta31** [comment]
[Turning off the eager execution solved the issue](https://github.com/tensorflow/tensorflow/issues/47311#issuecomment-786116401)

**Comment by sushreebarsa** [comment]
@varungupta31 Thank you for the update!
Glad it is working fine for you. Thank you!
