### ISSUE TITLE
Support item assignment in tensor object.

### ISSUE THREAD

**Issue by pure-rgb** [tensorflow/tensorflow#56381]
Issue Type: Feature Request
Source: binary
Tensorflow Version: 2.9
Custom Code: Yes

# Current Behaviour?

Item assignment is not supported.

Discuss more here. https://github.com/tensorflow/tensorflow/issues/33131

# Standalone code to reproduce the issue

```python
outputs = tf.zeros(..)

for step_index in range(5):
    outputs[step_index,...] = step_index + 1
```

Please support this and make a roadmap for the next version of tensorflow. And kindly don't suggest to cast to `tf.Variable` and use `assign/assgn_add` etc or any other non-intuitive workaround.

**Comment by tilakrayal** [comment]
Hi @Suzan009,
Can you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thank you!

**Comment by cantonios** [comment]
Marking as duplicate - yes, it is on the roadmap, but will not allow direct assignment like that since tensors are immutable.

**Comment by Suzan009** [comment]
@cantonios sorry I didn't wanted to create noise in issue. But I really think there should be intuitive approach to do item assignment. It doesn't need to be same as numpy. The jax also doesn't support item assignment but yet it provides some nice option, mentioned here https://github.com/google/jax/discussions/11035

**Comment by cantonios** [comment]
Right, so as mentioned above, it's on our roadmap.  It will likely look more like jax than regular python index assignment.

**Comment by cantonios** [comment]
An RFC to address this has been up for a bit.  Adding a link here in case anyone wants to provide input.

Comments are invited to the [pull request](https://github.com/tensorflow/community/pull/433). You can view the [design doc here](https://github.com/tensorflow/community/blob/77aa8fd5ea9c54bf1f08e9d25113aaa1ea90ba20/rfcs/20221020-tensor-indexed-updates.md), and also [leave comments inline](https://github.com/tensorflow/community/pull/433/files) on the document source.
