### ISSUE TITLE
Custom Op written in C API compilation Issue

### ISSUE THREAD

**Issue by YogaVicky** [tensorflow/tensorflow#56382]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Feature Request

### Source

binary

### Tensorflow Version

2.8

### Custom Code

Yes

### OS Platform and Distribution

Linux 

### Mobile device

07010841551

### Current Behaviour?

```shell
Hi there!
Is there any example where Custom OP written using C API was compiled successfully and executed after tf_load_library()?
I have referred the entire kernels.h ,ops.h and c_api.h files of the official github tf repo but I am not able to figure it out.
Could someone give the command to execute a C API custom op file along with the code?

Thanks,
Yoga
```

### Standalone code to reproduce the issue

```shell
#include "tensorflow/c/kernels.h"
#include "tensorflow/c/ops.h"
#include "tensorflow/c/tf_tensor.h"
#include "tensorflow/core/framework/common_shape_fns.h"
#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/registration/registration.h"
#include "tensorflow/core/framework/shape_inference.h"
#include "tensorflow/core/platform/macros.h"

// shape inference
void basic_shape_inference_fn(TF_ShapeInferenceContext* ctx,TF_Status* status) {
  TF_ShapeHandle* handle = TF_NewShapeHandle();
  TF_ShapeInferenceContextGetInput(ctx, 0, handle, status);
  TF_ShapeInferenceContextSetOutput(ctx, 0, handle, status);
  TF_DeleteShapeHandle(handle);
  assert(TF_GetCode(status) != TF_OK);
}

typedef struct Basic {
  TF_Tensor* input;
  TF_Tensor* output;
} Basic;

static void* Basic_Create(TF_OpKernelConstruction* context) {
  Basic* k = (Basic*) calloc(1, sizeof(Basic));
  TF_Status* status = TF_NewStatus();
  /* initialize the fields of k as needed */
  assert(TF_GetCode(status) != TF_OK);
  TF_DeleteStatus(status);
  return (void*) k;
  
}

static void Basic_Compute(void* k, TF_OpKernelContext* ctx) { 
  /* compute the result */
  TF_Tensor* input_tensor=NULL;
  TF_Status* status = TF_NewStatus();
  TF_GetInput(ctx, 0, &input_tensor, status);
  TF_SetOutput(ctx, 0, input_tensor, status);
  assert(TF_GetCode(status) != TF_OK);
  TF_DeleteStatus(status);
}

static void Basic_Delete(void* kernel) {
  delete static_cast<Basic*>(kernel);
}

// Op and Kernel Registration

void InitPlugin(){
  TF_Status* status = TF_NewStatus();
  TF_OpDefinitionBuilder* op_builder = TF_NewOpDefinitionBuilder("Basic");
  TF_OpDefinitionBuilderAddInput(op_builder, "to_zero: int32");
  TF_OpDefinitionBuilderAddOutput(op_builder, "zeroed: int32");
  TF_OpDefinitionBuilderSetShapeInferenceFunction(op_builder,&basic_shape_inference_fn);
  TF_RegisterOpDefinition(op_builder, status);
  assert(TF_GetCode(status) != TF_OK);
  TF_DeleteStatus(status);
  TF_Status* status1 = TF_NewStatus();
    auto* builder = TF_NewKernelBuilder("Basic", tensorflow::DEVICE_CPU,
                                        &Basic_Create, &Basic_Compute,
                                        &Basic_Delete);
    TF_RegisterKernelBuilder("Basic", builder, status1);
    assert(TF_OK != TF_GetCode(status1));
  TF_DeleteStatus(status1);
}

// TF_ATTRIBUTE_UNUSED static bool IsBasicKernelRegistered = []() {
//   if (SHOULD_REGISTER_OP_KERNEL("Basic")) {
//     RegisterBasicKernel();
//   }
//   return true;
// }();
```

### Relevant log output

```shell
module '012ff3e36e3c24aefc4a3a7b68a03fedd1e7a7e1' has no attribute 'basic'
```
</details>

**Comment by gadagashwini** [comment]
Hi @YogaVicky, This is a [guide](https://github.com/tensorflow/custom-op) for users who want to write custom c++ op for TensorFlow and distribute the op as a pip package. [Here](https://www.tensorflow.org/guide/create_op) is complete guidelines on how to create custom op and build pip package for your custom op. Thank you!

**Comment by YogaVicky** [comment]
Hi @gadagashwini, The [guide](https://github.com/tensorflow/custom-op) and the Github Repos are for building custom ops in C++ using the TF C++ API's.I'm trying to build custom ops using the C API of tensorflow.
I've tried to write the custom Op on the similar lines of [C API Custom op guide](https://github.com/tensorflow/community/blob/master/rfcs/20190814-kernel-and-op-registration.md) and tried to compile and build the Op on the same lines as we do for C++ custom ops.But there's no python module that's created with the required methods for the compute function to execute.I found that in C++ custom ops the REGISTER_* macros are identified by the tf.load_library() and are built as methods but the non availability of the macros in C API are a problem for tf.load_library().

It would be of great help if there's any documentation or some sort of working code(which has steps for compilation and building too) for writing custom ops using C API.

Thanks!

**Comment by gadagashwini** [comment]
Hi @YogaVicky, Request you to check this [link](https://github.com/AmirulOm/tensorflow_capi_sample) for Deploying Tensorflow as C/C++ executable. Thank you!

**Comment by YogaVicky** [comment]
Hi @gadagashwini Thanks for the link that you've shared.I don't think you'll be able to use an executable and run custom ops since it has to be linked with the tensorflow root dirs.Nevertheless I found out the fix for the problem by adding a trigger function for both the op and the associated kernels(A lambda function actually).
Thanks for the help and follow up :)

**Comment by gadagashwini** [comment]
Hi @YogaVicky, If it is resolved can we close this issue. Thank you!

**Comment by YogaVicky** [comment]
Yeah @gadagashwini, you can close the issue.
