### ISSUE TITLE
DTensor pack/unpack APIs used high device memory

### ISSUE THREAD

**Issue by Young768** [tensorflow/tensorflow#56393]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf.2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04.4

### Python version

3.8.10

### GPU model and memory

V100

### Current Behaviour?

Hi, DTensor developers

I was testing the DTensor features on ResNet-50 on imagenet. I started with the simple data parallel. To do data parallel, I fully replicated the weights and only shard the input data. The input batch sharding is handled by  method. However, I can only run the model with a very small global batch, i.e., 64. If I increased the #step-per-epoch, this number will be further reduced to 32. 

When I used a larger batch size, i.e. 128, from the TF-profiler, I saw that the used device memory kept accumulating and then it hit the OOM within 110 steps.

I spent some times and figured out that ```repack_batch``` method could cause high device memory. If I moved the below [code](https://github.com/Young768/test-dtensor/blob/main/resnet-opt.py#L757-L762) out from the for loop and used a fixed sharded input batch, I can successfully run the model with a global batch size of 1024. I would think that TF would reuse the allocation for the every new batch. But here it seems TF didn't do that. Would you please have a look? Thanks.

```
x = next(train_iter)
images, labels = x
images, labels = repack_batch(
        images, labels, image_layout, label_layout)
t_x = (images, labels)
total_loss += train_step(t_x)
```

### Standalone code to reproduce the issue

This is the [repo](https://github.com/Young768/test-dtensor/blob/main/resnet-opt.py) I used.

### Relevant log output

```shell
2022-05-26 19:20:17.146997: I tensorflow/core/common_runtime/bfc_allocator.cc:1097] total_region_allocated_bytes_: 15348793344 memory_limit_: 15348793344 available bytes: 0 curr_region_allocation_bytes_: 17179869184
2022-05-26 19:20:17.147010: I tensorflow/core/common_runtime/bfc_allocator.cc:1103] Stats: 
Limit:                     15348793344
InUse:                     15344515072
MaxInUse:                  15347394560
NumAllocs:                       23834
MaxAllocSize:               2512388096
Reserved:                            0
PeakReserved:                        0
LargestFreeBlock:                    0
```
</details>

**Comment by Young768** [comment]
CC Bruce @bfontain

**Comment by Young768** [comment]
Btw, I turned off mixed precision training and disabled fusion for BN layers, since it seems DTensor does not support these yet.

**Comment by bfontain** [comment]
Thanks for the info, we will take a look! @rainwoodman @srujun

**Comment by srujun** [comment]
Hi @Young768, thanks for reporting this issue. I believe somewhere in the implementation of `repack_local_tensor` we end up holding on to the GPU tensor handles which causes the memory to not get freed up. I am not able to replicate your code exactly since I don't have access to the exact imagenet dataset you are using which contains `bbox` and other features, but I was able to replace your implementation of `repack_local_tensor` with my own and did not run into any OOM issues. Can you try using this on your end and let me know if this works?

```python
def _split(value, splits, axis=0):
  children = tf.split(value, splits[0], axis=axis)
  if len(splits) > 1:
    splits = splits[1:]
    children = [tf.split(child, splits, axis + 1) for child in children]
  return tf.stack(children)

def pack_tf_tensor(value, layout):
  sharded_tensor = _split(
      value, [layout.num_shards(i) for i in range(layout.rank)])
  flattened = [np.ndarray([])] * layout.mesh.size
  for offset, shard in enumerate(layout.offset_to_shard()):
    flattened[offset] = sharded_tensor[tuple(shard)]
  return dtensor.pack(flattened, layout)

def repack_batch(x, y, x_layout, y_layout):
  x = pack_tf_tensor(x, x_layout)
  y = pack_tf_tensor(y, y_layout)
  return x, y
```

**Comment by Young768** [comment]
Hi @srujun Thanks for your reply. I am using the ```train-val-tfrecord-480``` generated by this [script](https://github.com/NVIDIA/DeepLearningExamples/tree/master/TensorFlow/Classification/ConvNets/resnet50v1.5#quick-start-guide). 

Could you please let me know what this line is trying to do? 
```children = [tf.split(child, splits, axis + 1) for child in children]```

Since I encountered an issue:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Determined shape must either match input shape along split_dim exactly if fully specified, or be less than the size of the input along split_dim if not fully specified.  Got: 3 [Op:SplitV] name: split
```

**Comment by srujun** [comment]
Ah my apologies, that particular line should be:
```
children = [_split(child, splits, axis + 1) for child in children]
```
We want to recursively split on each dimension of the input tensor. Does this fix make it work?

**Comment by Young768** [comment]
Hi @srujun Any update on this? Also I notice that in the [tutorial](https://www.tensorflow.org/tutorials/distribute/dtensor_ml_tutorial#moving_data_to_the_device), it mentions that ```Additional DTensor API to simplify [tf.data](https://www.tensorflow.org/api_docs/python/tf/data) integration is planned```. Do you know the estimated timeline of this?

**Comment by srujun** [comment]
Apologies, I got side-tracked on other projects since my last update. I'll try reproducing the issue with 8 v100 GPUs and get back to you.

As for the DTensor/tf.data API, I'm working on it to be included in the next Tensorflow release. Once I push it to the tensorflow github repository, I'll add an update here too so that you can try it out on a nightly version of Tensorflow.

**Comment by srujun** [comment]
How are you running the [script](https://github.com/tensorflow/models/blob/archive/research/inception/inception/data/build_imagenet_data.py) to build imagenet data? I had to replace the `tensorflow` import with `tensorflow.compat.v1`, but I still run into this error:

```
RuntimeError: tf.placeholder() is not compatible with eager execution.
```

This error is getting triggered on [this line](https://github.com/tensorflow/models/blob/archive/research/inception/inception/data/build_imagenet_data.py#L239).

**Comment by Young768** [comment]
Hi @srujun Did you try this [script](https://github.com/tensorflow/models/blob/master/research/slim/datasets/download_and_convert_imagenet.sh). It should also work.

**Comment by Young768** [comment]
Hi @srujun I verified that this [script](https://github.com/Young768/test-dtensor/blob/main/build_imagenet_data.py) should work.

**Comment by Young768** [comment]
Hi @srujun can you reproduce the issue?

**Comment by srujun** [comment]
Hi @Young768. Yes I am able to reproduce this now using the imagenet data. I am looking at the memory profile and trying to debug the issue. I'll post here ASAP when I have an update.

**Comment by srujun** [comment]
@Young768 have you been able to run this model with the 1024 batch size configuration before (perhaps when not using DTensor)? In the profiles I am looking at, the peak heap memory usage before the first step is over already is close to 14 GiB, which causes the OOM issue. I tried the following configurations too and listed their memory usage stats for the first step:

| Batch Size | Peak Heap Memory Usage | OOM |
| --- | --- | --- |
| 256 | 6.67 GiB | No |
| 512 | 10.72 GiB | No |
| 1024 | 13.64 GiB | Yes |

**Comment by Young768** [comment]
Hi @srujun With the same setup, I was able to run global_batch_size=1024 on 8 GPUs with data parallel, nccl as the communication backend. When using DTensor, the weird thing is that OOM happens around 30-40 steps. It didn't hit the OOM at the very beginning.

**Comment by srujun** [comment]
I should have the same setup on my end too (8 V100 GPUs), but seems like I am seeing different results. Can you try capturing a memory profile of your test and sharing the result?

Batch size = 512
![batch_size=512](https://user-images.githubusercontent.com/536115/181593857-876cd4c5-ff3a-4118-92af-2ec5ed5e7a81.png)

Batch size = 1024
![batch_size=1024](https://user-images.githubusercontent.com/536115/181594847-e8862b90-be75-4d0d-9ee2-2ac710fb4a0c.png)

Here's how I am capturing the traces:
```
  with tf.profiler.experimental.Profile(
      os.path.join('logdir', datetime.datetime.now().strftime("%Y%m%d_%H%M"))):

    for _ in range(nstep_per_epoch):
      global_steps += 1
      if global_steps == 1:
          start_time = time.time()

      with tf.profiler.experimental.Trace("train_step", step_num=global_steps):
          x = next(train_iter)
          images, labels = x
          images, labels = repack_batch(
              images, labels, image_layout, label_layout)
          t_x = (images, labels)
          total_loss += train_step(t_x)

      ...

      if global_steps > 10:
          break
```

**Comment by Young768** [comment]
Hi @srujun This is the memory profile when running with batch_size=1024, using your method to capture.
![1024](https://user-images.githubusercontent.com/7083506/181655381-0d80f7ad-767d-4e49-86b8-9f0c78e73047.png)

Did you try running a larger ```--num_iter``` with batch_size=512. When I ran with batch_size=512., it hit OOM at around step 50-60. And with batch_size=1024., it hit OOM at around step 20-30.

**Comment by Young768** [comment]
The issue was fixed after using the ```dtensor.DTensorDataset``` API.
