### ISSUE TITLE
TF.dataset.cache(path) still uses memory despite the cache file path

### ISSUE THREAD

**Issue by roshan2908** [tensorflow/tensorflow#56404]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.9.0-rc2-42-g8a20d54a3c1 2.9.0

### Custom Code

No

### OS Platform and Distribution

Ubuntu

### Python version

3.8

### CUDA/cuDNN version

11.2 8.1

### Current Behaviour?

```shell
dataset.cache(path) uses the internal ram memory, which keeps increasing. At the same time, it also uses a local cache. In the discussion: https://discuss.tensorflow.org/t/tf-dataset-cache-path-still-uses-memory-despite-the-cache-file-path-is-given-in-tf2-5-2-8/8176?u=roshan
```

### Standalone code to reproduce the issue

```shell
dataset = tf.data.Dataset.from_generator(generator,output_types=(tf.string, tf.float32),
                                            output_shapes=((),(num_cls,)))
dataset = dataset.map(parse_function, num_parallel_calls=AUTOTUNE)
dataset = dataset.cache(path)
dataset = dataset.map(applyMask, num_parallel_calls=AUTOTUNE)
dataset = dataset.shuffle(SHUFFLE_BUFFER_SIZE)
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@roshan2908 
In order to expedite the trouble-shooting process, please provide a complete code snippet to reproduce the issue reported here. Thank you!

**Comment by roshan2908** [comment]
```
import numpy as np
import tensorflow as tf

def train_generator():
    for file in trainfiles:
        x = np.random.rand(640,640,3)
        y = np.random.randint(0,2)
        yield x,y


dataset = tf.data.Dataset.from_generator(train_generator,output_types=(tf.float32, tf.float32),
                                            output_shapes=((640,640,3),()))
dataset = dataset.cache('./tmp/cache')
iterator = dataset.as_numpy_iterator()

while True:
    x,y = iterator.next()
```


Here is the code snippet for the same.
This will create a local cache file while at the same time it will increase the ram memory.

**Comment by sushreebarsa** [comment]
@roshan2908 Thank you for the update!
Reopening this issue. Thank you!

**Comment by sushreebarsa** [comment]
@roshan2908 Could you confirm if [this](https://github.com/tensorflow/tensorflow/issues/56404#issuecomment-1165730608) is the complete code snippet to replicate the issue. I tried to replicate the issue [here](https://colab.research.google.com/gist/sushreebarsa/732c0a70385163b7e18df81e78eaff33/56404.ipynb), please confirm the gist and let me know if I'm missing something to reproduce the issue?
Thank you!

**Comment by roshan2908** [comment]
I am not able to reproduce the same on colab. Seems like it might be because of different version of keras. 
So uninsatalled keras and installed it again, it worked for me. 

pip uninstall keras
pip install keras --upgrade

**Comment by gadagashwini** [comment]
Hi @roshan2908, `Tf v2.9.0-rc2-42-g8a20d54a3c1 2.9.0` is not stable version, may break due to version compatibility. Tf v2.9.0-rc2 is pre-release version. Latest stable `Tensorflow  2.9.1` version is compatible with `Keras 2.9.0`. Thank you!
