### ISSUE TITLE
Error Running TFLite Mobile Benchmark Tool for iOS

### ISSUE THREAD

**Issue by gKurbis** [tensorflow/tensorflow#56405]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9

### Custom Code

No

### OS Platform and Distribution

Mac OS 12.4

### Python version

3.10.4

### Bazel version

5.1.1-homebrew

### Current Behaviour?

```shell
I'm trying to run the TFLite Model Benchmark Tool for iOS devices.
I'm following the following instructions:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark/ios
I've been able to do the following:
- download and configure the TensorFlow repo from source
- install and configure the Bazel workspace

But when I run the "build_benchmark_framework.sh", the shell file doesn't build the benchmark framework for iOS under TFLiteBenchmark/TFLiteBenchmark/Frameworks as expected.

Because of this, when I try to run the Xcode project, it gives the error:
"TensorFlowLiteBenchMarkC/TensorFlowLiteBenchmarkC.h file not found"
```

### Standalone code to reproduce the issue

```shell
I'm following the following instructions:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark/ios
- download and configure the TensorFlow repo from source
- install and configure the Bazel workspace
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @gKurbis !  Did you say yes to IOS support when you run ./configure (After cloning Tensorflow repo) ? Could you please share a complete error stack trace. Thank you!

**Comment by gKurbis** [comment]
Hi @mohantym! 
I did say yes to IOS support with the ./configure was run.
(See below)
<img width="672" alt="Screen Shot 2022-06-09 at 12 09 36 PM" src="https://user-images.githubusercontent.com/97705198/172905007-9a82997b-8325-4309-b040-f642cd13d66f.png">


When running build_benchmark_framework.sh , I get the following output, but the TFLiteBenchmark/TFLiteBenchmark/Frameworks directory remains empty:
  "Saving session...
  ...copying shared history...
  ...saving history...truncating history files...
  ...completed.
  
  [Process completed]"



Additionally, I have attached the full error in Xcode below. Cheers!
<img width="597" alt="Screen Shot 2022-06-09 at 12 06 58 PM" src="https://user-images.githubusercontent.com/97705198/172904573-d33ee911-7f90-49bb-a9bd-c0dc0fd914a0.png">

**Comment by mohantym** [comment]
ok @gKurbis ! Thanks for the update. @sachinprasadhs ! Could you please look at this issue. Thank you!

**Comment by gKurbis** [comment]
Hi @sachinprasadhs, 

Were you able to build this on your end?

I see there was a recent commit (commit 8eb1cba939c2ffaf0474d53f3d63debd458c9a3c)
that seems to address this, but I was still unable to build the benchmark framework on my end.

**Comment by pjpratik** [comment]
Hi @gKurbis 

I was able to build the benchmark framework on latest stable version r2.12 successfully without error. Please find the screenshot below.

<img width="564" alt="Screenshot 2023-04-24 at 9 39 20 PM" src="https://user-images.githubusercontent.com/118897289/234055052-7c298c60-8288-4b17-b369-8f92064b4cec.png">

Could you please on r2.12 and let us know if the issue still persists.

Thanks.
