### ISSUE TITLE
Tanh giving out of range output.

### ISSUE THREAD

**Issue by AdityaPunetha** [tensorflow/tensorflow#56410]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8.2

### Custom Code

No

### Current Behaviour?

```shell
The tanh activation function is supposed to give an output in range [-1,1] but in this instance the output would sometimes have value in range [-9.999...,9.9999...]. Below I have attached a link to a repo where you can see the model architecture, the input and the output of the same, the model is also saved and uploaded in the same repo. The notebook was ran in colab and local environment where I faced similar result
```

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/github/AdityaPunetha/TensorFlow-TanH-Issue/blob/main/TanH_issue.ipynb
https://github.com/AdityaPunetha/TensorFlow-TanH-Issue
```

### Relevant log output

_No response_</details>

**Comment by AdityaPunetha** [comment]
Resolved, They are in scientific notation, Since the numbers after e is negative move the decimal point left. This means that none of the outputs are smaller than -1 or bigger than 1.

**Comment by mohantym** [comment]
@AdityaPunetha ! Also this behavior was not replicating in the second run. I ran a couple of times then after resetting the environment . It did not reappear . Attached [gist ](https://colab.sandbox.google.com/gist/mohantym/b3088d4e44eda5c1f6b1f364254fd55e/tanh-issue.ipynb#scrollTo=BuS8kIGJCcHe)for reference. Thank you!
