### ISSUE TITLE
Could not load dynamic library 'libcudart.so.11.0'

### ISSUE THREAD

**Issue by game-sys** [tensorflow/tensorflow#56413]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20

### Python version

3.7

### CUDA/cuDNN version

CUDA 11.2, CUDNN 8.1.0

### GPU model and memory

GRID T4-8Q 

### Current Behaviour?

```shell
I followed the steps mentioned in the https://www.tensorflow.org/install/pip to install tensorflow 2.9. But unfortunately getting an warning as follows:

2022-06-09 15:50:37.711160: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-09 15:50:37.711178: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

I further investigate and found that "libcudart.so.11.0" is present in /anaconda3/envs/<ENVIRONMENT NAME>/lib. But tensorflow is unable to find it. I tried to export the path to ./bashrc and to verify I ran command "echo $PATH" which return many paths and it include path /home/CAMPUS/<USER NAME>/anaconda3/envs/<ENVIRONMENT NAME>/lib. But still tensorflow is unable to find the "libcudart.so.11.0".

Please help !!!
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @game-sys ! Could you try these two options.
1. conda install cudatoolkit (it will reinstall cuda file at respective conda file locations)
2. Set the environment path for install cuda files if you have not set already .

Attached is relevant [thread](https://github.com/tensorflow/tensorflow/issues/45930#issuecomment-770342299) for reference. 

Thank you!
