### ISSUE TITLE
TFLite - different inference results between Android and python

### ISSUE THREAD

**Issue by ivankrylatskoe** [tensorflow/tensorflow#56425]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

python: 2.7.0; android: 2.4.0

### Custom Code

No

### OS Platform and Distribution

Windows 10; Android 10

### Mobile device

Redmi Note 9

### Python version

3.7.9

### CUDA/cuDNN version

cuda_11.2.r11.2

### Current Behaviour?

```shell
The same tflite model gives different results on Android and in python using the same input data.
Expected behaviour: the results are same.
```

### Standalone code to reproduce the issue

```shell
Google Colab code:
https://colab.research.google.com/drive/1J_gE3JYiqS9MNml9phFiryznI-Bcc3-M

Android code: 
https://github.com/ivankrylatskoe/tfbug

Model file and input data file can be downloaded from here:
https://drive.google.com/file/d/1Ed07YKIZh69Rmso3EL9a7t4dCacJqEs2/view?usp=sharing
https://drive.google.com/file/d/1p2iAJVT8Wc46ho5Hh29O7n4bwLD38h3O/view?usp=sharing

or from here:
https://github.com/ivankrylatskoe/tfbug/tree/main/app/src/main/assets
```

### Relevant log output

```shell
Python output:

File input.dat checksum: 99cc12fcae36b2b07ce8e3afe8c1ed86
File model.tflite checksum: eb302aa27bd246fb2759e768ad3c3bc0
Model output:
[[ 12  13  14  16  10 253]
 [ 12  13  15  17  10 253]
 [ 12  13  15  17  10 253]
 [ 18  17  16  18  10 253]
 [ 18  17  18  21  10 253]
 [ 18  15  20  22  10 253]
 [ 25  18  15  16  10 253]
 [ 25  18  16  18  10 253]
 [ 25  18  17  19  10 253]
 [ 32  18  15  17  10 253]]

Android output:

2022-06-10 23:52:46.146 20317-20317/com.android.tfbug I/TFBug: File input.dat md5: 99cc12fcae36b2b07ce8e3afe8c1ed86
2022-06-10 23:52:46.252 20317-20317/com.android.tfbug I/TFBug: File model.tflite md5: eb302aa27bd246fb2759e768ad3c3bc0
2022-06-10 23:52:46.587 20317-20317/com.android.tfbug I/TFBug: Model output: 
    12 14 14 16 10 253 
    12 14 15 17 10 253 
    12 14 15 17 10 253 
    18 17 16 18 10 253 
    18 17 18 21 10 253 
    18 15 20 23 10 253 
    25 18 15 16 10 253 
    25 18 16 18 10 253 
    25 18 17 19 10 253 
    32 18 15 16 10 253
```

</details>

**Comment by mohantym** [comment]
Hi @ivankrylatskoe ! The results look approximately the same to me. We cannot expect the exact same results for both Lite and Python because of the optimization and quantization process which happens during TFLite conversion . right?

But I suggest using Android version 4.2.1 or above with TF 2.8 version for better results. You can also refer quantization [documentation ](https://www.tensorflow.org/lite/performance/post_training_quantization)to improve the performance .Thank you!

**Comment by ivankrylatskoe** [comment]
Hi, @mohantym!

"Approximately same" is like "almost jumped across an abyss".
It doesn't work that way :) The results are either equal or not equal. 
Actually, it means that the model results are either reproducible across different supported platforms, or they are not.

Unless it is not explicitly told otherwise in the documentation, it is reasonable to suppose that normal behaviour is to get the same results on the same inputs using the same model.

Returning to the issue, I admit that my description was ambiguous.
Actually, Android version is 10. 
2.4.0 is the version of tensorflow library for Android. 
I rechecked the results for tensorflow library 2.8.0 and the results didn't change. So they are still different.

**Comment by mohantym** [comment]
@ivankrylatskoe  ! Thanks for the update. @gowthamkpr ! Could you please look at this issue?

**Comment by gowthamkpr** [comment]
@ivankrylatskoe Please take a look at this [issue](https://github.com/tensorflow/tflite-support/issues/736) which describes why the results are different in python and android. Thanks!

**Comment by ivankrylatskoe** [comment]
@gowthamkpr, thank you for your reply.
Actually, the solution described by @mohantym worked for me. 
I made a mistake during a recheck of results on a different version of TF library.
So, Tensorflow library 2.8.0 gives the same results as the python. 
Thank you.
