### ISSUE TITLE
resource_variable_ops.variable_accessed can not watch a values.DistributedVariable

### ISSUE THREAD

**Issue by MoFHeka** [tensorflow/tensorflow#56429]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

tf 2.6

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

x

### Python version

3.9

### Current Behaviour?

```shell
tensorflow.python.ops.resource_variable_ops.variable_accessed can not watch a tensorflow.python.distribute.values.DistributedVariable

I try to make a custom custom variable and let it could be accessed when distributed training, but fail. Here is the code, and var create from a class inheriting resource_variable_ops.ResourceVariable. Besides, strategy is Mirror.


var_dist = values.DistributedVariable(strategy, var, VariableAggregation.ONLY_FIRST_REPLICA)
resource_variable_ops.variable_accessed(var_dist)
```

And it throw when ran in tape.py: *** SystemError: <built-in method TFE_Py_TapeVariableAccessed of PyCapsule object at 0x7fe053a75480> returned a result with an error set
```


### Standalone code to reproduce the issue

```shell
Sorry, I try.
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@MoFHeka Could you try on the latest TF version 2.9.0 and let us know if the issue still persists?
In order to expedite the trouble-shooting process, please provide a complete code snippet to reproduce the issue reported here. Thank you!

**Comment by MoFHeka** [comment]
I should create a var_list for var in all devices, then wrap them with values.DistributedVariable. It's my fault.
