### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile:

### ISSUE THREAD

**Issue by JinkaiGUAN** [tensorflow/tensorflow#56424]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf2.5

### Custom Code

Yes

### OS Platform and Distribution

Windows 10

### Python version

3.8.5

### Current Behaviour?

```shell
for name, model in models.items():
                                if model is not None:

                                    name_ = "best_model_" + name
                                    # model.save_weights(os.path.join(weights_dir, name_), save_format='tf')
                                    model.save(os.path.join(weights_dir, name_), save_format="tf")

The above is the code I used to save my model, and there is a problem named a subclassing model. It seems that TensorFlow did not solve it, and gives the error below,
```shell
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: with_embedded_layer\sub_data\best_model_label_embedder\variables\variables_temp/part-00000-of-00001.data-00000-of-00001.tempstate7900589316842660676 : The system cannot find the path specified.
```
I did not know why Tensorflow introduces a wrong path delimiter in windows, i.e., `/` in the above path.
```


### Standalone code to reproduce the issue

```shell
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: with_embedded_layer\sub_data\best_model_label_embedder\variables\variables_temp/part-00000-of-00001.data-00000-of-00001.tempstate7900589316842660676 : The system cannot find the path specified.
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@JinkaiGUAN,
Could you try to remove the limit that Windows has on the maximum length of path (which is 260 characters). Set the LongPathsEnabled key in Registry to 1.
Also please take a look at this [issue1](https://stackoverflow.com/questions/45076911/tensorflow-failed-to-create-a-newwriteablefile-when-retraining-inception) and [issue2](https://github.com/tensorflow/tensorflow/issues/40642) with the similar error. Thank you!

**Comment by JinkaiGUAN** [comment]
Cheers, I have changed the save path configuration in my files and it works.

**Comment by tilakrayal** [comment]
@JinkaiGUAN,
Glad the suggestion worked to resolve the issue, kindly feel free to move this to closed status. Thank you!
