### ISSUE TITLE
Issue on building tensorflow-2.9.0 on centos 7.3

### ISSUE THREAD

**Issue by rajeev921** [tensorflow/tensorflow#56422]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.9.0

### Custom Code

No

### OS Platform and Distribution

centos 7.3.1

### Python version

3.8

### Bazel version

5.0.0

### GCC/Compiler version

9.3.1

### CUDA/cuDNN version

11.2/8.1

### Current Behaviour?

```shell
Trying to build tensorflow 2.9.0 with bazel 5.0.0 from source. But always getting same issue while bulding.
I have downloaded the zip file of 2.9.0 and also tried with cloning the repo and checkout 2.9.0. But from both I see the same behaviour.

Command used to build the repo.

bazel build --config=cuda --config=v2 --config=opt --verbose_failures -c opt --cxxopt=-std=c++17 --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow:tensorflow_cc //tensorflow:install_headers tensorflow:tensorflow_framework //tensorflow/tools/..
```

### Standalone code to reproduce the issue

```shell
N/A
```

### Relevant log output

```shell
bazel build --config=cuda --config=v2 --config=opt --verbose_failures -c opt --cxxopt=-std=c++17 --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow:tensorflow_cc //tensorflow:install_headers tensorflow:tensorflow_framework //tensorflow/tools/...

Complete Logs:
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/093ed77f7d50f75b376f40a71ea86e08cedb8b80.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found

DEBUG: 
.cache/bazel/74ec22257a67dd1b8da1cbc24b2c24fb/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:10: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default

WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found

ERROR: /remote/home/rrajeev/tensorflow/tensorflow/tools/toolchains/win_1803/py38/BUILD:9:11: in interpreter_path attribute of py_runtime rule //tensorflow/tools/toolchains/win_1803/py38:py3_runtime: must be an absolute path.

ERROR: /remote/home/rrajeev/tensorflow/tensorflow/tools/toolchains/win_1803/py38/BUILD:9:11: Analysis of target '//tensorflow/tools/toolchains/win_1803/py38:py3_runtime' failed

 Elapsed time: 80.921s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (95 packages loaded, 1584 targets configured)
    currently loading: @com_google_protobuf// ... (8 packages)
    Fetching ...zel_rules_docker; Cloning 9bfcd7dbf0294ed9d11a99da6363fc28df904502 of https://github.com/bazelbuild/rules_docker.git
    Fetching @local_execution_config_python; fetching
    Fetching @local_config_python; fetching
    Fetching @pasta; fetching
    Fetching @speech_commands; fetching
    Fetching https://storage.googleapis.com/download.tensorflow.org/models/inception_v1.zip
    Fetching .../pasta; Extracting .cache/bazel/external/pasta/temp27256293479294320\
98/v0.1.8.tar.gz
    Fetching https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz ... (10 fetches)
```
```
</details>

**Comment by tilakrayal** [comment]
Hi @rajeev921,

Could you try to clear Bazel cache before building Tensorflow.
`bazel clean --expunge.` 
 And also kindly make sure to follow the steps mentioned [here](https://www.tensorflow.org/install/source). Thank you!

**Comment by rajeev921** [comment]
Can someone please reply, as my whole development is stuck due to this build ?

**Comment by rajeev921** [comment]
Hi @gadagashwini, 
I tried below steps -
1. clone the latest code.
2. git checkout v2.9.1 - facing the same issue, so 
3. git checkout origin/master and when I tried same it is throwing the same issue.
Always making this link not found and then error and build stop.
https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/da74868905d61b0e82dace3f833e8f411fae27bc.tar.gz

**Comment by Arnold1** [comment]
@tilakrayal any update on it?

**Comment by rajeev921** [comment]
@gadagashwini @angerson @Arnold1 

Hi Will anyone help me to resolve this. It been long time but no reply ?

**Comment by rajeev921** [comment]
@gadagashwini @angerson @Arnold1

Hi,
Its been a long time on this thread without a reply. Can anyone look into that and help me.

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
