### ISSUE TITLE
Take-dataset

### ISSUE THREAD

**Issue by mrinalraj860** [tensorflow/tensorflow#56438]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8

### Custom Code

Yes

### GCC/Compiler version

clang version 13.1.6

### GPU model and memory

Tesla 

### Current Behaviour?

```shell
A bug happened!
In take dataset when taking dataset more then the limit doesnt show error meanwhile if we train from that dataset it shows error
```

### Standalone code to reproduce the issue

```shell
test_dataset = data_set.take(1000) 
train_dataset = data_set.skip(1000)
lets assume data_set is the batch-dataset of batch size=32 and when we take 1000 then it shows green signal but when someone will try to fit the model with this it will an error
```

### Relevant log output

```shell
ValueError: Unexpected result of `train_function` (Empty logs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.
```
</details>

**Comment by tilakrayal** [comment]
Hi @mrinalraj860,
To expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thank you!
