### ISSUE TITLE
TypeError: run() got an unexpected keyword argument 'argv'

### ISSUE THREAD

**Issue by kopxiong** [tensorflow/tensorflow#5643]
When I followed the TensorFlow Mechanics 101 tutorial  `python fully_connected_feed.py` in `examples/tutorials/mnist` directory, I came across this problem: 
```
Traceback (most recent call last):
  File "fully_connected_feed.py", line 277, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
TypeError: run() got an unexpected keyword argument 'argv'
```
I am using tensorflow 0.11 version in Anaconda environment.

**Comment by girving** [comment]
The `argv` argument was added recently: https://github.com/tensorflow/tensorflow/commit/6812d46b957e32eba37c67384cc2136908d7a1ff.  You are comparing a new version of a tutorial with an old version of tensorflow.

**Comment by marteiro** [comment]
I'm having the same problem. And i'm really using new example with old TF because the pip installation is not placing the examples files, so i've manually copied from sources and placed inside the pip installation. 

I'm using the fallowing:
https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl

what should i use to get TF with examples?

thanks in advance.

**Comment by xinchenxp** [comment]
I've meet the same problem with lastest TF, does sb know how to fix this problem？Is there a new tutorial docuement that i can follow, thanks a lot !

Traceback (most recent call last):
  File "convolutional.py", line 339, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
TypeError: run() got an unexpected keyword argument 'argv'

**Comment by hokjoung** [comment]
Checkout the r0.11 branch instead of the master branch.
Use the tutorial code in that branch.

**Comment by xinchenxp** [comment]
Thanks a lot, i git the r0.11 banch eventually, and it works !

**Comment by marteiro** [comment]
Thanks, it worked.  =D

**Comment by ttytt1978** [comment]
How to checkout the r0.11branch? my system is Ubuntu 16.04 LTS. Thanks.

**Comment by marteiro** [comment]
Use "-b r0.11" with Git clone!

**Comment by ttytt1978** [comment]
Can solve this problem by Update Tensorflow to new version? How to update Tensorflow to new version?

**Comment by ttytt1978** [comment]
@marteiro Thanks,it worked.
Can solve this problem by Update Tensorflow to new version? How to update Tensorflow to new version?

**Comment by ttytt1978** [comment]
@girving 
Can solve this problem by Update Tensorflow to new version? How to update Tensorflow to new version?

**Comment by marteiro** [comment]
@ttytt1978
If your are not contributing to the master branch, just use the r0.11. Not much else to hope for.

**Comment by loretoparisi** [comment]
I have the same error running the example in the `learn` folder:

on latest version 0.12:

https://github.com/tensorflow/tensorflow/blob/r0.12/tensorflow/examples/learn/text_classification.py

```
Traceback (most recent call last):
  File "text_classification.py", line 136, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
TypeError: run() got an unexpected keyword argument 'argv'
```

**Comment by girving** [comment]
@loretoparisi You are not running 0.12 tensorflow: https://github.com/tensorflow/tensorflow/blob/r0.12/tensorflow/python/platform/app.py

**Comment by loretoparisi** [comment]
@girving sorry, didn't get. I'm using the `text_classification.py` example from the `r0.12` blob, where I'm wrong?

**Comment by girving** [comment]
@loretoparisi You are running `text_classification.py` from `0.12` against an older version of TensorFlow, which includes an older version of `app.py` which does not have the flag.

**Comment by loretoparisi** [comment]
@girving ok this makes sense, in fact my `requirements.txt` looks like

```
$ cat requirements.txt 
https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0-py2-none-any.whl
matplotlib
nltk
sklearn
scipy
pandas
```

Thanks going to move to 0.12 nightly, if there is one?

**Comment by jubins** [comment]
I am also getting the same error, how can I upgrade my tensorflow?

**Comment by loretoparisi** [comment]
@jubins for my understanding, the fix is in `0.12` but there is not nightly build in Jenkins already, the latest nightly build is [here](https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=mac-slave/), but it is still on `0.11`, so the only option I see so far is to move to branch [r0.12](https://github.com/tensorflow/tensorflow/tree/r0.12) and compile from the scratch.

**Comment by jubins** [comment]
@loretoparisi I recompiled my code but it now gives another error 'run() got an unexpected keyword argument argv'

**Comment by vrv** [comment]
Prior to 1.0, always make sure the tensorflow example code you run is from the same branch as the binary version you have installed.

So your options are:
1) Upgrade your tensorflow installation (via nightly or source) to use files in the master branch
2) Check out the copy of the example code from the branch you have installed (r0.11 if you have 0.11 installed).

**Comment by ttytt1978** [comment]
I got it and it works,thanks!

**Comment by loretoparisi** [comment]
@ttytt1978 how you achieved that?
@vrv it could be useful a step by step guide, thanks.

**Comment by ttytt1978** [comment]
@loretoparisi 
![branches](https://cloud.githubusercontent.com/assets/8791765/20658225/3d36a244-b576-11e6-9e93-353c7fc26ea2.png)
Select the branch match you tensorflow version.

**Comment by ttytt1978** [comment]
@loretoparisi 
![branche](https://cloud.githubusercontent.com/assets/8791765/20658313/c7e2675c-b576-11e6-801c-99293656b6fe.png
Select the branch match you tensorflow version and download it, run the file in the directory you download.

**Comment by ttytt1978** [comment]
@loretoparisi 
![branche](https://cloud.githubusercontent.com/assets/8791765/20658433/c00eaa8a-b577-11e6-963c-9326a86b8666.png)
Select the branch match you tensorflow version and download it, run the file in the directory you download.

**Comment by marteiro** [comment]
Please Dude, read the topic:

**git clone https://github.com/tensorflow/tensorflow -b r0.11**

**Comment by wei-yuan** [comment]
Thx a lot every one, it works!

**Comment by zcc973784075** [comment]
THX all! It helps a lot

**Comment by GarethZhang** [comment]
@girving Hi, im running tensorflow wheel version 0.10.0 with gpu support (cuda-7.5) and getting the same error. When I tried to branch to r11.0, it successfully installs wheel version 0.11.0 but prompts errors saying that it requires cuda-8.0 libraries. Whereas 0.10.0 only requires cuda-7.5. Do you know if there's another way to fix this error with cuda-7.5 libraries? Thanks!

**Comment by mzx5464** [comment]
Thanks, i try "-b r0.11" with Git clone and it works

**Comment by gowthamcastro** [comment]
where to clone it

**Comment by Zo2m4bie** [comment]
Is this problem relevant to version 1.7.0? I installed tensorflow through pycharm and according to print(tf.__version__) my version is 1.7.0. However I faced the same problem
