### ISSUE TITLE
Tensorflow not working with oneDNN at Win10?

### ISSUE THREAD

**Issue by vsbc2010** [tensorflow/tensorflow#56435]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Win10

### Python version

python-3.7.9-amd64.exe

### Bazel version

bazel-5.0.0-windows-x86_64.exe

### GCC/Compiler version

vs2019

### Current Behaviour?

```shell
I had build tensorflow lite c, But seem not include oneDNN.

bazel build //tensorflow/lite/c:tensorflowlite_c.dll -c opt --define tflite_with_xnnpack=true --config=mkl
```

### Standalone code to reproduce the issue

```shell
Nothing
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @vsbc2010 ! Sorry for the late response. Could you please post the complete error stack trace. Thank you!

**Comment by vsbc2010** [comment]
Nothing error message come with Win10 + vs2019  build. But seem with not include oneDNN aways. Only show message with XNN after test load.

**Comment by mohantym** [comment]
Ok @vsbc2010 ! 
TF-oneDNN ops are disabled by default, but can be enabled by setting an environment variable TF_ENABLE_ONEDNN_OPTS=1. [Reference](https://groups.google.com/a/tensorflow.org/g/build/c/RZhgZst-fgQ/m/w3XK97MlAwAJ).

Could you rebuild with the below command and let us know. Thank you!
```
bazel build //tensorflow/lite/c:tensorflowlite_c -c opt --define tflite_with_xnnpack=true --config=mkl_aarch64 
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '1' //use in python code 
```

**Comment by vsbc2010** [comment]
But i have issue for tensorflowlite_c with C project. And i need lib for Win10 x86 64bit,  mkl_aarch64 for ARM only.

**Comment by mohantym** [comment]
Hi @gowthamkpr ! Could you please look at this issue. Thank you!

**Comment by gadagashwini** [comment]
Hi @vsbc2010, 
Can you try 
`bazel build //tensorflow/lite/c:tensorflowlite_c.dll --config=opt --define tflite_with_xnnpack=true TF_ENABLE_ONEDNN_OPTS=1`

Thank you!

**Comment by vsbc2010** [comment]
*   [oneDNN CPU performance optimizations](https://github.com/tensorflow/community/blob/master/rfcs/20210930-enable-onednn-ops.md)
    are available in Linux x86, Windows x86, and Linux aarch64 packages.

    *   **Linux x86 packages:**
        *   oneDNN optimizations are *enabled by default* on CPUs with
            neural-network-focused hardware features such as AVX512_VNNI,
            AVX512_BF16, AMX, etc.
            ([Intel Cascade Lake](https://www.intel.com/content/www/us/en/products/platforms/details/cascade-lake.html)
            and newer CPUs.)
            *   [Example performance speedups.](https://medium.com/intel-analytics-software/leverage-intel-deep-learning-optimizations-in-tensorflow-129faa80ee07)
        *   For older CPUs, oneDNN optimizations are disabled by default.
    *   **Windows x86 package:** oneDNN optimizations are disabled by default.
    *   **Linux aach64 (`--config=mkl_aarch64`) package:**
        *   Experimental oneDNN optimizations are disabled by default.
        *   If you experience issues with oneDNN optimizations on, we recommend
            turning them off.
    *   To explicitly enable or disable oneDNN optimizations, set the
        environment variable `TF_ENABLE_ONEDNN_OPTS` to `1` (enable) or `0`

**Comment by vsbc2010** [comment]
> Hi @vsbc2010, Can you try `bazel build //tensorflow/lite/c:tensorflowlite_c.dll --config=opt --define tflite_with_xnnpack=true TF_ENABLE_ONEDNN_OPTS=1`
> 
> Thank you!

environment variable TF_ENABLE_ONEDNN_OPTS to 1  for Python only.  But not working with build param.

**Comment by vsbc2010** [comment]
How to build_with_mkldnn_openmp ?

**Comment by vsbc2010** [comment]
bazel build //tensorflow/lite/c:tensorflowlite_c.dll -c opt --config=mkl_threadpool --define build_with_mkl_dnn_v1_only=true

But still not include oneDNN.

**Comment by vsbc2010** [comment]
Can you provide a solution In the latest version 2.11.0?  @terryheo @karimnosseir @gowthamkpr @sachinprasadhs @mohantym

**Comment by pkgoogle** [comment]
Hi @vsbc2010, oneDNN is not part of Tensorflow lite which is why you don't see it. In order to use oneDNN, you need to build Tensorflow. Let us know if that resolves your issue.
