### ISSUE TITLE
TF Lite NNAPI fails to load a model

### ISSUE THREAD

**Issue by MM2932** [tensorflow/tensorflow#56457]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04 (host), Android 11 (mobile device)

### Mobile device

Device based on Qualcomm Snapdragon 6490

### Python version

3.8

### Bazel version

4.2.1

### GCC/Compiler version

8.4.0

### Current Behaviour?

```shell
When selecting TFLite's NNAPI delegate with the accelerator 'qti-dsp', it fails with an error during the model loading stage. For more information on the error please see the log below.
Expected behaviour is the model to be successfully loaded.
```

### Standalone code to reproduce the issue

```shell
Select TFLite's NNAPI delegate with the accelerator 'qti-dsp', while loading the model available at: https://github.com/tensorflow/tensorflow/files/8118439/test_model.zip
```

### Relevant log output

```shell
E/VersionedInterfaces: DeathHandler::serviceDied -- service unexpectedly died!
E/VersionedInterfaces: prepareModel_1_3 on qti-dsp failed because the PreparedModel object is dead
E/tflite: NN API returned error ANEURALNETWORKS_DEAD_OBJECT at line 4662 while completing NNAPI compilation.
```
</details>

**Comment by mohantym** [comment]
Hi @MM2932 !  I tracked the error [here](https://developer.android.com/ndk/reference/group/neural-networks#aneuralnetworksdevice_wait:~:text=ANEURALNETWORKS_DEAD_OBJECT) 
Here are a few things I need to know.
1. Could you confirm whether Android studio is detecting your device in a live state. 
2. Commands to implement qti-dsp delegate specificially.

**Comment by AB5247** [comment]
Hi @mohantym, thank you for your answer.
> 1. Could you confirm whether Android studio is detecting your device in a live state.

Yes, the device is live all the time.

> 2. Commands to implement qti-dsp delegate specificially.

Our current implementation is written in C++ and we simply select `accelerator_name = "qti-dsp"` for `tflite::StatefulNnApiDelegate::Options`. But the issue can also be reproduced with your own tools, for example with your [Inference Diff tool](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/evaluation/tasks/inference_diff) selecting the same accelerator.

A couple other comments:
- This error is triggered by the model @MM2932 linked in the ticket. We tested other models that did not cause this error.
- In case this is helpful for your diagnosis, we actually tracked the error and it looks like it is happening here: https://github.com/tensorflow/tensorflow/blob/d8ce9f9c301d021a69953134185ab728c1c248d3/tensorflow/lite/delegates/nnapi/nnapi_delegate.cc#L4644

**Comment by mohantym** [comment]
@gowthamkpr ! Could you please look at this issue.

**Comment by karimnosseir** [comment]
Miao, can you please have a look

Thanks

**Comment by MM2932** [comment]
Hi @miaowang14 !
Are you taking care of this issue?

Thanks!
Massimo.

**Comment by miaowang14** [comment]
> E/VersionedInterfaces: DeathHandler::serviceDied -- service unexpectedly died!

This indicates that the model somehow has caused the qti-dsp NNAPI driver to crash. Since it is an issue with proprietary driver, I'll forward the issue to our vendor partner.

Could you share the following information:
Device Name, Manufacture, Android version?

**Comment by MM2932** [comment]
Hi @miaowang14 ,

Sorry to keep you waiting.

We are trying to reach out to Qualcomm to report this issue. Please keep the ticket open, so that we can share further updates with you.

Thanks!
Massimo.

**Comment by pkgoogle** [comment]
Hi @MM2932, has Qualcomm gotten back to you?

**Comment by MM2932** [comment]
Hi, we contacted Qualcomm last year, but a fix is not available yet.

They have been working on a new delegate (QNN), that will replace the Hexagon. We hope QNN will enable us to run this model soon.

Thanks!

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
