### ISSUE TITLE
Tensorflow Gfile raises wrong error when trying to delete non existing file on HDFS

### ISSUE THREAD

**Issue by jccarles** [tensorflow/tensorflow#56469]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.5.3

### Custom Code

Yes

### Python version

3.7

### Current Behaviour?

```shell
When I use tf.io.gfile.remove to remove a file which does not exist the error raised is  `tf.errors.UnknownError` instead of `tf.errors.NotFoundError`.

It seems to come from a wrong interpretation of hadoop error code.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
tf.io.gfile.remove("hdfs://myhdfs:9000/NONEXISTENTFILE.txt")
```

### Relevant log output

```shell
22/06/15 15:01:18 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 330, in delete_file_v2
    _pywrap_file_io.DeleteFile(compat.path_to_bytes(path))
tensorflow.python.framework.errors_impl.UnknownError: hdfs://myhdfs:9000/NONEXISTENTFILE.txt; Input/output error
```
</details>

**Comment by Enzo90910** [comment]
Not directly relevant to this project, but this bug cascades into the Transform component of TFX not working because it tries to delete non existing files and does not catch "UnknownError".

**Comment by sushreebarsa** [comment]
@jccarles Could you please find the reproducible gist [here](https://colab.research.google.com/gist/sushreebarsa/c07a7ea781d28bd7481e24959a6e3a74/56469.ipynb) and let me know if I am missing something to replicate the issue?
Thank you!

**Comment by jccarles** [comment]
Hello @sushreebarsa ! I think to replicate in tensorflow >= 2.6 it is needed to install and import tensorflow-io (https://stackoverflow.com/questions/68876693/how-can-i-access-to-hdfs-file-system-in-the-latest-tensorflow-2-6-0). But in both cases (tf >= 2.6 and < 2.6) you need to have hadoop installed and to export its CLASSPATH in the container which tries to access hdfs (https://stackoverflow.com/questions/42307908/running-tensorflow-with-file-on-hdfs-cannot-find-libhdfs-so), you also need to start an hdfs and try to delete a non-existing file inside it...

It requires quite a bit of setup...
