### ISSUE TITLE
Bincount doesn't check the tensor type

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#56499]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

master

### Custom Code

Yes

### OS Platform and Distribution

linux

### Current Behaviour?

With `axis=None` and `binary_output=False` it doesn't check the input tensor type so it is failing calling directly the `bincount` kernel that it doesn't support sparse and ragged inputs:

https://github.com/tensorflow/tensorflow/blob/d8ce9f9c301d021a69953134185ab728c1c248d3/tensorflow/python/ops/bincount_ops.py#L137

### Standalone code to reproduce the issue

```python
import tensorflow as tf
values = tf.constant([1,1,2,3,2,4,4,5])
values = tf.sparse.from_dense(values)
print(tf.math.bincount(values, binary_output=False, axis=0)) # Ok -> specialized sparse kernel
print(tf.math.bincount(values, binary_output=False, axis=None)) # Fail -> bincount kernel
```
```


### Relevant log output

_No response_</details>

**Comment by bhack** [comment]
I don't know why we have the XLA label but it Is a python only bug.

**Comment by gadagashwini** [comment]
Hi @bhack, Associated PR got closed, could you confirm issue still persists or not. Thank you!

**Comment by bhack** [comment]
@gadagashwini What PR?

**Comment by gadagashwini** [comment]
Hi @bhack, Is [this](https://github.com/tensorflow/tensorflow/pull/56276) PR associated with this issue. Thank you!

**Comment by bhack** [comment]
No that one is something different. Check my code gist.

**Comment by SeeForTwo** [comment]
https://github.com/tensorflow/tensorflow/commit/caf5b4d890095df814d8b39d2ac9717aa32ecf1a fixes this, axis=0 and axis=None now consistently use the newer kernel.

If there are still any remaining Bitcount issues, please feel free to file a new bug and bring it to my attention.
