### ISSUE TITLE
ContextManager Error on tf.name_scope: RuntimeError("generator didn't yield")

### ISSUE THREAD

**Issue by cgarciae** [tensorflow/tensorflow#5649]
I have this minimal code that shows the error:

```
scope = tf.name_scope('loss')
with scope as s:
    print s
    
with scope as s:
    print s
```

Is this a bug or done by design?

**Comment by girving** [comment]
@lukaszkaiser Any reason our scopes shouldn't be re-enterable?

**Comment by lukaszkaiser** [comment]
I think name scope is not meant to be used sa object this way, and I don't see why it should. Use variable_scope if you want to capture scope as object and yield.

**Comment by cgarciae** [comment]
@lukaszkaiser The issue is not about if I should use this or that, its if this should be considered a bug or not because solving this is easy for users, but a behaviour like this should be by design given certain criteria or fixed because it can cause un expected errors.
