### ISSUE TITLE
TypeError: a bytes-like object is required, not 'TFLiteSavedModelConverterV2'

### ISSUE THREAD

**Issue by DevOpsThinh** [tensorflow/tensorflow#56491]
2022-06-17 16:52:23.053795: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1777] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following flex op(s):
Flex ops: FlexCast
Details:
        tf.Cast {Truncate = false, device = ""}
Traceback (most recent call last):
  File "convert-fashion-mnist.py", line 17, in <module>
    file.write(model)
TypeError: a bytes-like object is required, not 'TFLiteSavedModelConverterV2'

--------- my file ---------
# %%
import tensorflow as tf

model = tf.lite.TFLiteConverter.from_saved_model(
    '../ImageRecognitionWithTensorFlow2/fashion-2'
)

model.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]

model.convert()

with open('converted-fashion.tflite', 'wb') as file:
  file.write(model)
--------- my file ---------

**Comment by sushreebarsa** [comment]
@DevOpsThinh 
In order to expedite the trouble-shooting process here, could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thank you!
