### ISSUE TITLE
Error: Convert a SavedModel

### ISSUE THREAD

**Issue by DevOpsThinh** [tensorflow/tensorflow#56492]
### 1. System information

- Window 10 pro 21H2
- TensorFlow 2
- TensorFlow library : tf.lite package

### 2. Code

# %%
import tensorflow as tf

model = tf.lite.TFLiteConverter.from_saved_model(
    '../ImageRecognitionWithTensorFlow2/fashion-2'
)

model.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]

model.convert()

with open('converted-fashion.tflite', 'wb') as file:
  file.write(model)
# %%

#### Reference colab notebooks
1)  Reference [TensorFlow Lite converter]
(https://www.tensorflow.org/lite/models/convert/convert_models)

### 3. Failure after conversion
The conversion is successful, but the generated model is wrong, the state what is wrong:
- Model produces wrong results and the file's size = 0

### 5.  Info / logs

(2022-06-17 16:52:23.053795: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1777] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following flex op(s):
Flex ops: FlexCast
Details:
        tf.Cast {Truncate = false, device = ""}
Traceback (most recent call last):
  File "convert-fashion-mnist.py", line 17, in <module>
    file.write(model)
TypeError: a bytes-like object is required, not 'TFLiteSavedModelConverterV2')

**Comment by mohantym** [comment]
Hi @DevOpsThinh! Sorry for the late response . Correct code snippet for conversion will be 
```
import tensorflow as tf
model= tf.lite.TFLiteConverter.from_saved_model(
'/content/mnist'
)

model.target_spec.supported_ops = [
tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]

test_lite = model.convert() // you have to save the converted buffer file in another variable. 

with open('converted-fashion.tflite', 'wb') as file:
  file.write(test_lite)
```

**Comment by DevOpsThinh** [comment]
Thank you so much. Have a good day 😘

**Comment by icexiaoyou** [comment]
Use the recently code, error still exists.

发生异常: ConverterError
<unknown>:0: error: loc(callsite(callsite(fused["Mul:", "MultiLevelMatMulCropAndResize/MultiLevelRoIAlign/mul_17@__inference_call_func_10979"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_12675"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): 'tfl.reshape' op operand #1 must be tensor of 32-bit signless integer values, but got 'tensor<6xi64>'
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from

During handling of the above exception, another exception occurred:

  File "C:\Users\yjz\Desktop\Unihiker\lite\convert_1.py", line 9, in <module>
    test_lite = model.convert() # you have to save the converted buffer file in another variable.

**Comment by DevOpsThinh** [comment]
> 

![completely_converting_a_savedmodel](https://user-images.githubusercontent.com/56128362/175959317-ded7274e-ef28-41fb-a444-b374a9406873.png)
I have completed the conversion, no more errors.

**Comment by DevOpsThinh** [comment]
> Use the recently code, error still exists.
> 
> 发生异常: ConverterError :0: error: loc(callsite(callsite(fused["Mul:", "MultiLevelMatMulCropAndResize/MultiLevelRoIAlign/mul_17@__inference_call_func_10979"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_12675"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): 'tfl.reshape' op operand #1 must be tensor of 32-bit signless integer values, but got 'tensor<6xi64>' :0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
> 
> During handling of the above exception, another exception occurred:
> 
> File "C:\Users\yjz\Desktop\Unihiker\lite\convert_1.py", line 9, in test_lite = model.convert() # you have to save the converted buffer file in another variable.

![completely_converting_a_savedmodel](https://user-images.githubusercontent.com/56128362/175960095-6fcb4347-f168-468d-87ad-fa6781c270c0.png)
I have completed the conversion, no more errors.

**Comment by icexiaoyou** [comment]
![new_bug](https://user-images.githubusercontent.com/95946934/177457482-5ecc354d-95b8-4f4c-bfa6-e26f7e35b250.png)

Still could not Run, thanks for your supports.
