### ISSUE TITLE
Question on the implementation of BMM (batched matmul)

### ISSUE THREAD

**Issue by widiba03304** [tensorflow/tensorflow#56501]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Irrelevant
- TensorFlow installation (pip package or built from source): Irrelevant
- TensorFlow library (version, if pip package or github SHA, if built from source): Irrelevant

### 2. Code

Hi, I am currently working on the transformer models on mobile GPUs.
Because transformer-based models have multi-headed attention, batched matrix multiplication is crucial.

However, I found out that TOCO simply replaces such BMM operators into a bunch of matmul operators.
Is there any rationale behind this? If there is, can you provide some benchmark or evaluation on this?

My guess is that the capacity of the mobile GPU cache or register file is not enough to perform BMM efficiently without register spill or something, so performance would be degraded, but I have not tried such experiments so cannot be sure on this.

Thanks in advance.

**Comment by mohantym** [comment]
Hi @widiba03304 ! You can refer to this [link ](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark)to benchmark your lite models. You can see supported ops [here](https://www.tensorflow.org/lite/guide/ops_compatibility).To use custom ops, you have register them in kernel and[ use custom_ops](https://www.tensorflow.org/lite/guide/ops_custom) = true during conversion. 

Please provide a minimal stand alone code to replicate this issue. 
Thank you!
