### ISSUE TITLE
tf.keras.backend.ctc_decode merging repeated characters by default

### ISSUE THREAD

**Issue by DLumi** [tensorflow/tensorflow#56506]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.7.0

### Custom Code

No

### Current Behaviour?

```shell
The current built-in keras wrapper function does not have an optional agrument "merge_repeated" to pass along to the underlying tensorflow function. I believe this issue was solved in standalone keras as per https://github.com/keras-team/keras/issues/12238
```

### Standalone code to reproduce the issue

```shell
Check https://github.com/keras-team/keras/issues/12238 for the reproduction code
```

### Relevant log output

_No response_</details>

**Comment by DLumi** [comment]
Double-checked documentation, and it turns out there's not 'merge_repeated' argument in tf.nn.ctc_beam_search_decoder anymore!
I wonder if it was intentional to remove it, as I simply don't see why.

**Comment by DLumi** [comment]
> Hi @DLumi, I tried to execute the code with an alternative approach. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/12c2e6c6db50251637e72d657fb300b6/56506.ipynb) and let us know if the workaround helped in this case. Thank you!

As the matter of fact, I did came up with something similar for my test purposes.
Speaking of the code you provided - yes, it certainly works as I intend it to.

**Comment by tilakrayal** [comment]
@DLumi,
As mentioned above, if the provided workaround helped in your case, could you feel free to close this issue. Thank you!
