### ISSUE TITLE
35x difference in performance between windows and linux version

### ISSUE THREAD

**Issue by ivankrylatskoe** [tensorflow/tensorflow#56504]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux, Windows

### Python version

3.10

### CUDA/cuDNN version

cuda_11.2.r11.2 (windows)

### Current Behaviour?

```shell
The inference time of my tflite model is 35 times faster in linux (0.4 sec) than in windows (14 sec).
In both cases the same hardware is used. 
Drivers configuration: GPU is available in windows and not available in linux.
In both cases tensorflow 2.9.1 is used.
```

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/18AWls7w_oWdWk3bRlTdkG2U7pm_w8rn6
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @ivankrylatskoe ! 
Sorry for the late response. It seems you have not used experimental.load_delegate properly . Could you build and load the delgate.so file in interpreter along the lite files and let us know. 

`bazel build -c opt --config mkl_aarch64  tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so` 
#for dynamic library

Attached [Example ](https://www.tensorflow.org/lite/api_docs/python/tf/lite/experimental/load_delegate#example_usage)usage of loading a delegate in interpreter . Thank you!

**Comment by ivankrylatskoe** [comment]
Hi @mohantym!
I have a few questions regarding your response.

1. Is it ok that extension of the delegate file is "so" in windows, not "dll"? 
2. Is it possible to load precompiled delegate file? 
I've installed tensorflow from binaries, and it would be inconvenient to install a whole build system to compile a single file.
3. CPU delegate runs rather fast in linux. Why it is slow in windows?

**Comment by mohantym** [comment]
@ivankrylatskoe ! 

 Sorry! It will be a .dll file for windows machine. What i suggested was a workaround for this issue. I think it is possible to load procompiled delegate file . The team is aware of performance issues in windows machines and working on it. Passing to @sachinprasadhs to have better look at this issue.

Thank you!

**Comment by ivankrylatskoe** [comment]
@impjdi, thank you for your answer.
The problem is not related to GPU at all. It's the problem of CPU only.
So, your answer doesn't explain why the issue is closed.

**Comment by impjdi** [comment]
Ah, I assumed it was a GPU issue because I was assigned to this and I'm only responsible for TFLite GPU at best.  Will re-open and un-assign myself.  Thanks for clarifying.

**Comment by ivankrylatskoe** [comment]
Just to be sure that GPU is not used I added the following lines:

    os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
    print(tf.config.list_physical_devices('GPU'))

and got `[]` in Windows and Linux. So, CPU is used on both of them.
But execution time was still different: 14 sec in Windows, 0.4 sec in Linux.

**Comment by terryheo** [comment]
Could you share how to run the inference on Windows? Did you just use Python API from TF PIP?

**Comment by ivankrylatskoe** [comment]
> Could you share how to run the inference on Windows? Did you just use Python API from TF PIP?

Hello, @terryheo.
To run my example on Windows:
1) Create your_file.py file from the following code: https://colab.research.google.com/drive/18AWls7w_oWdWk3bRlTdkG2U7pm_w8rn6

2) Download data files from here:
https://drive.google.com/file/d/1Ed07YKIZh69Rmso3EL9a7t4dCacJqEs2/view?usp=sharing
https://drive.google.com/file/d/1p2iAJVT8Wc46ho5Hh29O7n4bwLD38h3O/view?usp=sharing

3) If you are on a clean python installation, you may need to install tensorflow: 
`pip install tensorflow==2.9.1`

4) Run your_file.py in python: `python your_file.py`

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
