### ISSUE TITLE
Type INT16 is unsupported by op Rsqrt.Node number 12 (RSQRT) failed to prepare.

### ISSUE THREAD

**Issue by FragrantRookie** [tensorflow/tensorflow#56505]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows10
- TensorFlow installed from (source or binary):                   tensorflow 2.9.1
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
RuntimeError: tensorflow/lite/kernels/elementwise.cc:88 Type INT16 is unsupported by op Rsqrt.Node number 12 (RSQRT) failed to prepare.
```

**Standalone code to reproduce the issue** 
First,I convert the input/output of the model from float32 into int16. Second,I load the new model.Third,I allocate tensors.Then the error reports after run the code "interpreter_2.allocate_tensors()" in real_time_processing_tf_lite.py.
```
interpreter_2 = tf.lite.Interpreter(model_path='F:\\testmodel_2.tflite')
interpreter_2.allocate_tensors()
```
The reported error is as following:
`RuntimeError: tensorflow/lite/kernels/elementwise.cc:88 Type INT16 is unsupported by op Rsqrt.Node number 12 (RSQRT) failed to prepare.`

**Also, please include a link to a GraphDef or the model if possible.**
The target model is here https://github.com/breizhn/DTLN
The inputs format of the model in the link are float32.

**Any other info / logs**

The following are my codes for converting.It has no problem:

In DTLN_model.py:

```
def representative_dataset():
    for _ in range(100):
        data1 = np.random.uniform(-1000, 1000, [1, 2, 128, 2]).astype(np.float32)
        data2 = np.random.uniform(-250, 250, [1, 1, 257]).astype(np.float32)
        #data3 = {'input_2': [data2.astype(np.float32)], 'input_3': [data1.astype(np.float32)]}
        yield [data1.astype(np.float32), data2.astype(np.float32)]

def representative_dataset2():
    for _ in range(100):
        data1 = np.random.uniform(-1000, 1000, [1, 2, 128, 2]).astype(np.float32)
        data2 = np.random.uniform(-250, 250, [1, 1, 512]).astype(np.float32)
        #data3 = {'input_2': [data2.astype(np.float32)], 'input_3': [data1.astype(np.float32)]}
        yield [data2.astype(np.float32), data1.astype(np.float32)]
```
```
if use_dynamic_range_quant:
    #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8]
    converter.inference_input_type = tf.int16
    converter.inference_output_type = tf.int16
    converter.representative_dataset = representative_dataset
    #++++++++++++++++++++++++++++++++++++++++++++++++++++++++
tflite_model = converter.convert()
with tf.io.gfile.GFile(target_name + '_1.tflite', 'wb') as f:
      f.write(tflite_model)
# convert second model    
converter = tf.lite.TFLiteConverter.from_keras_model(model_2)
if use_dynamic_range_quant:
    # ————————————————————————————————————————————————————
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8]
    converter.inference_input_type = tf.int16
    converter.inference_output_type = tf.int16
    converter.representative_dataset = representative_dataset2
    #————————————————————————————————————————————————————
tflite_model = converter.convert() 
```

**Comment by mohantym** [comment]
Hi @FragrantRookie ! 
I was able to load both lite files in the above [github link](https://github.com/breizhn/DTLN)  but was facing an select ops error in Colab for [2.8](https://colab.sandbox.google.com/gist/mohantym/9bff14563e717b5213c4336c815bd130/git_56505.ipynb#scrollTo=P8e3fFL_QNjg), [2.9](https://colab.sandbox.google.com/gist/mohantym/d96c500d31d2ede8b793fe2c0f8728a7/git_56505.ipynb#scrollTo=EeFneGu5zfk4) and [nightly](https://colab.sandbox.google.com/gist/mohantym/7e91e91de9a1619e6cbd58fde7c4b6c1/git_56505.ipynb#scrollTo=_OqJmsSbhnen).  Could you change the conversion code snippet as below and let us know. Thank you!

```
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [
        tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8] // use both select ops and built-ins if it throws any select ops error. 
converter.inference_input_type = tf.float32
converter.inference_output_type = tf.float32
converter.representative_dataset = representative_dataset
```

**Comment by FragrantRookie** [comment]
> 

OK, I'll try it right away

**Comment by FragrantRookie** [comment]
Hi @mohantym 
    It works well with the code you gave me.I can get the converted output with float32 intput and output.

**Comment by FragrantRookie** [comment]
@mohantym 
I don't use "tf.lite.TFLiteConverter.from_saved_model". I used this code `def create_tf_lite_model(self, weights_file, target_name, use_dynamic_range_quant=False):`  define in DTLN_model.py to convert the model into tflite format.

**Comment by mohantym** [comment]
@FragrantRookie !
Thanks for the update. Could you confirm whether it is working with tf.float32 as inference input and output type with tf.tf.lite.TFLiteConverter.from_keras_model . Thank you!

**Comment by FragrantRookie** [comment]
Hi @mohantym
My computer reported the same error as yours when using `tf.lite.TFLiteConverter.from_keras_model`.No matter using this codes or not:
```
        converter.target_spec.supported_ops = [
            tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8]
        converter.inference_input_type = tf.float32
        converter.inference_output_type = tf.float32
        converter.experimental_enable_resource_variables = True
        converter.representative_dataset = representative_dataset
```

**Comment by mohantym** [comment]
@FragrantRookie ! Thanks for the update. Could you add the select ops code snippet and let us know .
```
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)

converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
        tf.lite.OpsSet.SELECT_TF_OPS, # enable TensorFlow ops.
        tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8] // use both select ops and built-ins if it throws any select ops error. 
converter.inference_input_type = tf.float32
converter.inference_output_type = tf.float32
converter.representative_dataset = representative_dataset
```

**Comment by FragrantRookie** [comment]
Hi @mohantym,
 Using your codes,the reported error is as following:

```
RuntimeError: Max and min for dynamic tensors should be recorded during calibration: Failed for tensor serving_default_input_1:0
Empty min/max for tensor serving_default_input_1:0
```

The thing should be noticed is that I modified the function `representative_dataset` as bellow:

```
def representative_dataset():
    for _ in range(100):
        #data1 = np.random.uniform(-1000, 1000, [1, 2, 128, 2])
        data2 = np.random.uniform(-250, 250, [1, 1, 512])
        #data3 = {'input_2': [data2.astype(np.float32)], 'input_3': [data1.astype(np.float32)]}
        #yield [data1.astype(np.float32), data2.astype(np.float32)]
        yield [data2.astype(np.float32)]
```

**Comment by mohantym** [comment]
@FragrantRookie ! Thanks for confirmation on the errors . Passing to @sachinprasadhs for faster resolution. Thank you!

**Comment by sachinprasadhs** [comment]
As the error message says, for some of the OP INT16 is not supported yet in TFLITE.
You can try the solution suggested by @mohantym or you can try with different dtype precision like INT8 and see if that works. Thanks!
