### ISSUE TITLE
tf.linalg.inv does not support "half" datatype

### ISSUE THREAD

**Issue by enor2017** [tensorflow/tensorflow#56519]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.8.2

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04.5 (on Google Colab)

### Python version

3.7.13

### Current Behaviour?

```shell
The `tf.linalg.inv` does not support `half` data type, while the doc on [https://www.tensorflow.org/versions/r2.8/api_docs/python/tf/linalg/inv](https://www.tensorflow.org/versions/r2.8/api_docs/python/tf/linalg/inv) said `half` can be used.

The latest version (tf 2.9) also has this issue.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

x = np.array([[1, 2], [3, 4]], dtype=np.half)
tf.linalg.inv(x)
```

### Relevant log output

```shell
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-1-22e20a75db78> in <module>()
      3 
      4 x = np.array([[1, 2], [3, 4]], dtype=np.half)
----> 5 tf.linalg.inv(x)

2 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     53     ctx.ensure_initialized()
     54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:
     57     if name is not None:

NotFoundError: Could not find device for node: {{node MatrixInverse}} = MatrixInverse[T=DT_HALF, adjoint=false]
All kernels registered for op MatrixInverse:
  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_COMPLEX64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
 [Op:MatrixInverse]
```
</details>

**Comment by sushreebarsa** [comment]
@chunduriv I was able to replicate the issue on colab using TF v2.9.0, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/23c80270ee65c9972928cc42362d2083/56519.ipynb). Thank you!

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue, I have submitted the changes internally.

**Comment by sachinprasadhs** [comment]
for Half `dtype`, some of the tests are failing to due deviation of precision errors more than the defined threshold level.
Is is possible for you to run the op in `float32` and then cast the output to half `dtype`.

**Comment by enor2017** [comment]
@sachinprasadhs It's ok for me currently. However, if the issue is hard to fix, would you like to modify the documentation to remove support for the `half` type? That causes an inconsistency.
