### ISSUE TITLE
What is the role of "WriteToInputTensor" function in tf lite gpu delegate example?

### ISSUE THREAD

**Issue by jyh2378** [tensorflow/tensorflow#56512]
Hi,
I saw the tensorflow lite [gpu delegate tutorial](https://www.tensorflow.org/lite/performance/gpu_advanced?hl=ko) providing gpu delegate inference on android C++ code snippet:
```
// Set up interpreter.
auto model = FlatBufferModel::BuildFromFile(model_path);
if (!model) return false;
ops::builtin::BuiltinOpResolver op_resolver;
std::unique_ptr<Interpreter> interpreter;
InterpreterBuilder(*model, op_resolver)(&interpreter);

// NEW: Prepare GPU delegate.
auto* delegate = TfLiteGpuDelegateV2Create(/*default options=*/nullptr);
if (interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk) return false;

// Run inference.
WriteToInputTensor(interpreter->typed_input_tensor<float>(0));
if (interpreter->Invoke() != kTfLiteOk) return false;
ReadFromOutputTensor(interpreter->typed_output_tensor<float>(0));

// NEW: Clean up.
TfLiteGpuDelegateV2Delete(delegate);
```
But I don't understand the fuction `WriteToInputTensor` & `ReadFromOutputTensor`. What is the role of these function? And where can I find it? I couldn't find any code or information in tenforflow repo.

**Comment by impjdi** [comment]
Its role is ... to write your input data to the interpreter-allocated memory?  It's often a memcpy:
```
std::memcpy(interpreter->typed_input_tensor<float>(0), input_data, size_of_input_data);
```

**Comment by jyh2378** [comment]
Ooh... I misunderstood that is a some function really exists :(
Thank you!

p.s. I think, it would be better if the guide changed clearly.
