### ISSUE TITLE
error: ‘class tflite::Interpreter’ has no member named ‘UseNNAPI’               ^~~~~~~~

### ISSUE THREAD

**Issue by FengMu1995** [tensorflow/tensorflow#56518]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf2.8

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8

### GCC/Compiler version

7.5.0

### Current Behaviour?

```shell
in tflite 2.8 , how to use nnapi C++ api in native linux-x86
I use it like 
interpreter->UseNNAPI(true);
but it is not exists.
"Interpreter’ has no member named ‘UseNNAPI’ "
```

### Standalone code to reproduce the issue

```shell
/
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @FengMu1995 ! 
Please provide a minimal code to replicate the issue.  Attached a code snippet to check whether NNAPI delegate is supported on your platform or not. 
```
using TfLiteDelegatePtr = tflite::Interpreter::TfLiteDelegatePtr;
using TfLiteDelegatePtrMap = std::map<std::string, TfLiteDelegatePtr>;

TfLiteDelegatePtrMap delegates_;

auto delegate = TfLiteDelegatePtr(tflite::NnApiDelegate(), [](TfLiteDelegate*) {});

if (!delegate) {
cout << "NNAPI acceleration is unsupported on this platform.";
} else {
delegates_.emplace("NNAPI", std::move(delegate));
}
for (const auto& delegate : delegates_) {
if (interpreter->ModifyGraphWithDelegate(delegate.second.get()) !=
kTfLiteOk) {
cout << "Failed to apply " << delegate.first << " delegate.";
} else {
cout << "Applied " << delegate.first << " delegate.";
}
}
```
Thank you!

**Comment by FengMu1995** [comment]
ok, I have loaded my code in rvm_tflite2.zip. I tried to add your code to mine, but it reports 
"/rvm_tflite_2/main.cc:58: error: undefined reference to `tflite::NnApiDelegate()'

**Comment by mohantym** [comment]
Hi @gowthamkpr ! Could you please look at this issue. Thank you!

**Comment by FengMu1995** [comment]
I build the tflite2.8 by the following steps:
"""
./configure
bazel build --config=monolithic --config=noaws --config=nohdfs --config=nonccl --config=v2 --define=tflite_convert_with_select_tf_ops=true --define=with_select_tf_ops=true //tensorflow/lite:libtensorflowlite.so
"""
I'm not sure if the lib is built with NNAPI

**Comment by rr191211** [comment]
> Well, I've uploaded my code in rvm_tflite2.zip. I tried to add your code to mine, but it reports: "/rvm_tflite_2/main.cc:58: error: undefined reference to `tflite::NnApiDelegate()'
> 
> I am not sure if the needed .h files or .lib are included. [rvm_tflite_2.zip](https://github.com/tensorflow/tensorflow/files/8953825/rvm_tflite_2.zip)

I am facing this issue with TF 2.11, anyone could help? Thanks.

**Comment by pjpratik** [comment]
Hi @FengMu1995 

The [Android Neural Networks API (NNAPI)](https://developer.android.com/ndk/guides/neuralnetworks) is available on all Android devices running Android 8.1 (API level 27) or higher.

The NNAPI delegate is available with the TensorFlow Lite Interpreter in Java and Kotlin. For Android C APIs, please refer to [Android Native Developer Kit documentation](https://developer.android.com/ndk/guides/neuralnetworks).


Thanks.

**Comment by elvisdukaj** [comment]
> > Well, I've uploaded my code in rvm_tflite2.zip. I tried to add your code to mine, but it reports: "/rvm_tflite_2/main.cc:58: error: undefined reference to `tflite::NnApiDelegate()'
> > I am not sure if the needed .h files or .lib are included. [rvm_tflite_2.zip](https://github.com/tensorflow/tensorflow/files/8953825/rvm_tflite_2.zip)
> 
> I am facing this issue with TF 2.11, anyone could help? Thanks.

Same issue, did you resolve it? I am trying to build for Android.

**Comment by sawantkumar** [comment]
Hi @elvisdukaj ,

You can find the instructions for building tflite for android [here](https://www.tensorflow.org/lite/android/lite_build). Please let me know if this is the one you are looking for.
