### ISSUE TITLE
"Cannot convert a symbolic Tensor ({}) to numpy array"

### ISSUE THREAD

**Issue by rohitvuppala** [tensorflow/tensorflow#56527]
I tried to use the interface from DeepXDE as mentioned here- "https://github.com/tensorflow/tensorflow/issues/48167#issuecomment-966596156" but encountered an error.  While I understand the error, I'm not sure how to resolve it. Any help in this regards is appreciated. 

I'm using:
```
dde.optimizers.config.set_LBFGS_options(maxcor=50,ftol=1*np.finfo(float).eps,maxiter=100000,maxfun=100000,maxls=50)
self.optimizer = dde.optimizers.tfp_optimizer.lbfgs_minimize(self.trainable_var,self.loss)
```                                                     

The error:
"Cannot convert a symbolic Tensor ({}) to numpy array"

It seems like the function only accepts numpy arrays but I have a TF symbolic tensor. Any way to resolve this?

_Originally posted by @rohitvuppala in https://github.com/tensorflow/tensorflow/issues/48167#issuecomment-1162519845_

**Comment by rohitvuppala** [comment]
Accidentally opened an issue in the wrong repo where the comment originated, but this repo/package is unrelated to the issue.

**Comment by rohitvuppala** [comment]
@mohantym Could you please delete the issue?

**Comment by mohantym** [comment]
Hi @rohitvuppala!

 In 2.6 or earlier versions, The error on symbolic tensor was getting resolved when eager execution was disable or numpy version was upgraded to 1.21.5 or downgraded to 1.19.5 . From the 2.8 version onwards, Numpy version has upgraded to 1.21 which solved these issues in most cases. Please create a new issue if you need further assistance. 

Thank you!

**Comment by rohitvuppala** [comment]
@mohantym Thank you didn't realize the bug might be related to tensorflow.
My tensorflow version is 2.8.1, numpy version is 1.22.4 and I did disable eager execution. Is the bug still related to tensorflow?

**Comment by mohantym** [comment]
@rohitvuppala !

Sometimes it can get fixed through Numpy version upgrade/downgrade But Few issues need a code fix on the model side too. Could you update the template  with minimal stand alone code which will help us expedite the issue. 

Thank you!
