### ISSUE TITLE
New quantizer seems to ignore TFLITE_BUILTINS_INT8

### ISSUE THREAD

**Issue by benkli01** [tensorflow/tensorflow#56535]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.7.1 and 2.9.1

### 2. Code

The following script can be run directly to show the issue. A SavedModel is saved before the conversion and a TFLite file afterwards.

```python
import tensorflow as tf
import numpy as np


def create_not_fully_quantizable_model():
    """Set up the model"""
    model = tf.keras.Sequential(
        [
            tf.keras.Input(shape=(5), batch_size=1),
            tf.keras.layers.Dense(5, input_shape=(1, 5)),
            tf.keras.layers.Dense(5),
            tf.keras.layers.Lambda(lambda x: tf.math.floormod(x, 3)),
        ]
    )

    return model


def dataset_generator(shape):
    """Set up the training data"""
    x_train = np.array(
        [
            [0.0, 1.0, 2.0, 3.0, 4.0],
            [2.0, 0.0, 2.0, 3.0, 4.0],
            [0.0, 3.0, 2.0, 3.0, 4.0],
            [4.0, 1.0, 2.0, 3.0, 4.0],
            [5.0, 1.0, 2.0, 3.0, 4.0],
        ],
        dtype="float32",
    )

    def generator():
        """Dataset generator for post-training calibration."""
        for x in x_train:
            yield [np.reshape([x], shape)]

    return generator


def main():
    filename = "test_partial_quant"

    model = create_not_fully_quantizable_model()
    model.save(filename)

    # Post-training conversion.
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    # converter.experimental_new_quantizer = False
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = dataset_generator(model.input_shape)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.target_spec.supported_types = [tf.int8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    tflite_quant_model = converter.convert()

    # Save result
    tflite_file = filename + ".tflite"
    open(tflite_file, "wb").write(tflite_quant_model)
    print(f"TFLite file saved to '{tflite_file}'.")


if __name__ == "__main__":
    main()
```

### 3. Failure after conversion

I would expect (and want) the above script to fail, because the model intentionally contains ops that can not be quantized and I am using the following options:
- `converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]`
- `converter.target_spec.supported_types = [tf.int8]`

From the [TensorFlow docs](https://github.com/tensorflow/tensorflow/blob/v2.9.1/tensorflow/lite/python/convert.py#L159-L197):
```
  # Convert model using only TensorFlow Lite quantized int8 operations.
  # Specifying this will throw an error for operations that do not yet have
  # quantized implementations.
  TFLITE_BUILTINS_INT8 = "TFLITE_BUILTINS_INT8"
```

Instead there are dequant/quant nodes inserted around the unsupported operator and the model is converted without any complaints. In other words: The used options seem to have no effect.

### 4. Tests and observations

- When I use the old quantizer (`converter.experimental_new_quantizer = False`) I am getting the expected error.
- After a quick look into the code there seems to be an option `fully_quantize` for `mlir_quantize()` [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/convert.py#L200), but it seems to be not used [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/lite.py#L621).
- Might be related to [this TODO](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/lite/quantization/lite/quantize_model.cc#L49) in the cpp code.

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue . Attached gist in [2.8](https://colab.sandbox.google.com/gist/mohantym/9e0d761a3dc846b125c5dedbb7af3a6f/git_56535.ipynb#scrollTo=JX-y7E3i5oNI), [2.9](https://colab.sandbox.google.com/gist/mohantym/3e7138ccd451445f9dbbb4119ef27b75/git_56535.ipynb#scrollTo=O0DkR6wyKN_q) and [nightly](https://colab.sandbox.google.com/gist/mohantym/836f19f652092f946fbd55256d4e7d33/git_56535.ipynb#scrollTo=pdhwrSM45tPE) for reference. Thank you!

**Comment by rino20** [comment]
Hi, @abattery  It seems you are already assigned to this issue. 

Could you take a look at this issue? - This is a blocker of ARM side.

**Comment by abattery** [comment]
This behavior just does not throw an exception in the newer version. I wonder how the ARM side can be blocking because of this one.

**Comment by benkli01** [comment]
Hi @abattery. 
Thanks for looking into this. The issue here is that there is no "strict mode". We can not rely on the converter to produce a TFLite graph that only contains int8 operations (which might be required by the hardware).

**Comment by benkli01** [comment]
Hi. I just tested this with TensorFlow 2.10 and the issue seems to be still present. Are there any updates on this?

**Comment by benkli01** [comment]
Hi. This is still an issue in TensorFlow 2.11. Any updates?

**Comment by pjpratik** [comment]
Hi @benkli01 

Th int8 support for `floormod` op has been added with commit https://github.com/tensorflow/tensorflow/commit/2ba376283d387b63d6c24bd48bea4dace386b017. It will be reflected in 2.13 version.

Thanks.

**Comment by benkli01** [comment]
Hi @pjpratik, thanks for the heads-up. I just tried [the latest pre-release version](https://github.com/tensorflow/tensorflow/releases/tag/v2.13.0-rc2) which should have support for int8 in `floor_mod`, but I can still see the error:

![image](https://github.com/tensorflow/tensorflow/assets/66783786/be3bfa9a-1195-468c-8f5a-71b69e281fc2)

And if I switch to the old quantizer, I get the usual error: 
`RuntimeError: Quantization not yet supported for op: 'FLOOR_MOD'.`

**Comment by benkli01** [comment]
I just tested this with TensorFlow 2.13.0 and it is the same result as above, i.e. the error is still there (strangely enough, now that FLOOR_MOD should be supported for int8), @pjpratik .

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
