### ISSUE TITLE
Duplicate logging messages after calling `model.save()`

### ISSUE THREAD

**Issue by jamesdolezal** [tensorflow/tensorflow#56549]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

11.3

### Current Behaviour?
When using a logger from python's `logging` module, messages are duplicated after a model is saved.

For example:

```python

import logging
import tensorflow as tf

logger = logging.getLogger('test')
logger.setLevel(logging.INFO)
logger.addHandler(logging.StreamHandler())
logger.info("Message (1) not duplicated")

model = tf.keras.applications.Xception()
logger.info("Message (2) not duplicated")

model.save('test')
logger.info("Message is duplicated")
```

Will yield (some output not shown):

```
Message (1) not duplicated
Message (2) not duplicated
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 40). These functions will not be directly callable after loading.
Message is duplicated
INFO:test:Message is duplicated
```

Logging is not duplicated if `logging.basicConfig()` is called before model saving:

```python
...
logger.setLevel(logging.INFO)
logger.basicConfig()
logger.info("Message (1) not duplicated")
...
```

This behavior is only observed in Tensorflow 2.9 and does not occur with version <2.8.

I suspect the issue is in `tensorflow.python.saved_model.save:268` where a module-level `logging.warning()` function is called, which may be unintentionally adding a stream handler to the root logger if none is configured.

### Standalone code to reproduce the issue

```python
import logging
import tensorflow as tf

logger = logging.getLogger('test')
logger.setLevel(logging.INFO)
logger.addHandler(logging.StreamHandler())
logger.info("Message (1) not duplicated")

model = tf.keras.applications.Xception()
logger.info("Message (2) not duplicated")

model.save('test')
logger.info("Message is duplicated")
```

### Relevant log output

```shell
Message (1) not duplicated
Message (2) not duplicated
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 40). These functions will not be directly callable after loading.
Message is duplicated
INFO:test:Message is duplicated
```
</details>

**Comment by sushreebarsa** [comment]
@chunduriv I was able to replicate the issue on colab, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/32260f7551fac34eb39746473d71ae74/56549.ipynb). Thank you!

**Comment by chunduriv** [comment]
@jamesdolezal,

Thank you for opening this issue.  Development of keras moved to separate repository https://github.com/keras-team/keras/issues. 

Please post this issue on `keras-team/keras repo`. For more details please refer [here](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999).
