### ISSUE TITLE
Available quantization options in TFL/ TFLM

### ISSUE THREAD

**Issue by stmrwitt** [tensorflow/tensorflow#56546]
Hello,

First, I am not sure where to post this.

Currently, I'm writing my Master’s Thesis, where I'm analysing TFLM inference on a Cortex M4 architecture.
Part of it is a comparison between the different available quantization options.

However, in TFL (version 2.8.0) I could not manage to quantize differently than int8, float16 in post training quantization and int8 in QAT.

When I try to run the models on my device using TFLM (source from 2022-05-13), the float16 quantized model is also not running any more (AllocateTensors() failed).
I've seen in the “c_api_types.h” files that there are technically many tensor types (TfLiteType) like int8, int16, int32, float16, float32 available.

The question is, if I am doing something wrong, or it is simply not supported (jet)?

Thank you in advance,
Marcel

**Comment by mohantym** [comment]
Hi @stmrwitt ! 
We normally prefer [post training integer](https://www.tensorflow.org/lite/performance/post_training_integer_quant) quantization for micro controllers to increase performance and reduce inference time. 
Thank you!

**Comment by stmrwitt** [comment]
Hello @mohantym,

Thanks for the reply!

The int8 post training quantized model is running fine for me.
But I wonder if it is technically possible to quantize to int32/ int16 in TFL, or run the float16 quantized model in TFLM?
What would be the currently supported quantization settings regarding the weights and activations data types?

Thank you!

**Comment by mohantym** [comment]
@stmrwitt !

You might be Float 16 quantization in integer only accelerator devices like Edge-tpu which might have caused above errors.
Attached relevant threads for reference. [1](https://www.tensorflow.org/lite/performance/post_training_integer_quant#:~:text=This%20data%20format%20is%20also%20required%20by%20integer%2Donly%20accelerators%20such%20as%20the%20Edge%20TPU.), [2](https://www.tensorflow.org/lite/performance/post_training_integer_quant_16x8#:~:text=this%20fully%20quantized%20model%20can%20be%20consumed%20by%20integer%2Donly%20hardware%20accelerators.).

Thank you!

**Comment by stmrwitt** [comment]
@mohantym !

If I understand the provided links correctly, there is only 8-bit integer, 18x8 integer and float16 quantization available in TensorFlow Lite.

I have done the provided steps to produce a tflite hex data model, which can be used in TensorFlow Lite Micro on my device.
However, the float16 quantized model it is not running (described above).
I am not using an Edge-tpu and the Cortex M4 comes with a FPU. So, it is not an integer only device and the original float32 model is also running fine.
But I suppose float16 is simply not supported in TensorFlow Lite Micro.

Can you confirm that?

Thank you again!

**Comment by mohantym** [comment]
@stmrwitt ! 
It might be a bug then. Could you also provide any minimal standalone code to replicate this issue. Thank you!

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue. Thank you!

**Comment by stmrwitt** [comment]
Hi again!

It seems like there are different quantizations allowed, depending on which layer and plattform optimization you use.
The fully_connected implementation for cmsis_nn has float32_t, int8_t and int16_t available (see [cmsis_nn/fully_connected.cc](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/kernels/cmsis_nn/fully_connected.cc)).
The standard conv implementation has f32, i16, i64 and i8 available (see [conv.cc](https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/kernels/conv.cc)).

Could you please confirm that?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
