### ISSUE TITLE
EmitIRForReduction fails with "Check failed: !reductions.empty()..."

### ISSUE THREAD

**Issue by iamohcy** [tensorflow/tensorflow#56543]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8.10

### Current Behaviour?

When running evaluate on a modified HloModule loaded directly from text (i.e. without going through the OptimizeHloModule pipeline), the evaluation fails at the EmitIRForReduction step (in ir_emitted_unnested.cc), with the error message:

tensorflow/compiler/xla/service/gpu/ir_emitter_unnested.cc:5025] Check failed: !reductions.empty()  expect at least one reduce instructions.

I managed to reproduce it with a small hlo_module example (see hlo_module text below), and figured out that it was due to an issue in the GroupDisjointReductions function:

```
  std::unique_ptr<HloReachabilityMap> reachability_map =
      HloReachabilityMap::Build(fused_computation);
  for (HloInstruction* instr : fused_computation->instructions()) {
    std::vector<HloInstruction*> reached_output_ids;
    for (HloInstruction* output : roots) {
      if (HloOpcode::kReduce == output->opcode() &&
          (IsBroadcastedConstantOrScalar(*instr))) {
        // Do not group output reduce instructions through broadcasted
        // constants or scalars, as the recomputation should be acceptable.
        VLOG(3) << "Skip broadcasted constant or scalar " << instr->ToString();
        continue;
      }
      // Now group output instructions if they have common predecessors.
      if (reachability_map->IsReachable(instr, output)) {
        VLOG(3) << "Reaching " << output->ToString() << " from "
                << instr->ToString();
        reached_output_ids.push_back(output);
      }
    }
    for (size_t j = 1; j < reached_output_ids.size(); ++j) {
      disjoint_sets[reached_output_ids[0]].Merge(
          &disjoint_sets[reached_output_ids[j]]);
    }
  }

  // Place output instructions in the same set into the same group.
  HloInstructionMap<std::vector<HloInstruction*>> groups;
  for (HloInstruction* root : roots) {
    groups[disjoint_sets[root].Get()].push_back(root);
  }
```
Specifically focusing on the comment "Do not group output reduce instructions through broadcasted constants or scalars, as the recomputation should be acceptable.". This causes broadcasted constants/scalars to be ignored as predecessors when tracing back from output reduce instructions.

The problem comes when the instruction that shares only broadcasted constant/scalars is itself a root of this computation. This causes that instruction to be ignored for grouping with every other instruction, resulting in a reduction group with just that single output instruction (does not have to be a broadcast instruction, e.g. an output add(constant1, constant2) would also show the same error). This causes the above error since that reduction group has no reduce instruction.

One patch that I've tested that works is to replace the bottom for-loop above with:
```
  // Place output instructions in the same set into the same group.
  HloInstructionMap<std::vector<HloInstruction*>> groups;
  for (HloInstruction* root_instr : roots) {
    if (HloOpcode::kReduce != root_instr->opcode() && IsBroadcastedConstantOrScalar(*root_instr)) {

      // We need to maintain the seen list so we don't add to the group twice
      HloInstructionMap<bool> seen;
      for (HloInstruction* output : roots) {
        if (root_instr->unique_id() != output->unique_id()){
          if (reachability_map->IsReachable(root_instr, output)) {
            HloInstruction* disjoint_set_val = disjoint_sets[output].Get();
            // We haven't seen this disjoint representive val yet
            if (seen.count(disjoint_set_val) == 0) {
              groups[disjoint_set_val].push_back(root_instr);
              seen[disjoint_set_val] = true;
            }
          }
        }
      }
    }
    else {
      groups[disjoint_sets[root_instr].Get()].push_back(root_instr);
    }
  }
```
This ensures that any of these "isolated" output instructions get grouped with at least one reduce instruction.

### Standalone code to reproduce the issue

Just load the below HloModule from string and try to Compile and Execute it directly without other changes.
```shell
HloModule input_fused_computation_reduce

%scalar_add_computation (scalar_lhs: f32[], scalar_rhs: f32[]) -> f32[] {
  %scalar_lhs = f32[] parameter(0)
  %scalar_rhs = f32[] parameter(1)
  ROOT %add.1 = f32[] add(f32[] %scalar_lhs, f32[] %scalar_rhs)
}

%fused_reduce.1 () -> (f32[200], f32[200,32]) {
  %constant.0 = f32[] constant(0)
  %broadcast.0 = f32[200,32]{1,0} broadcast(f32[] %constant.0), dimensions={}
  %reduce.0 = f32[200]{0} reduce(f32[200,32]{1,0} %broadcast.0, f32[] %constant.0), dimensions={1}, to_apply=%scalar_add_computation
  ROOT %tuple.0 = (f32[200]{0}, f32[200,32]{1,0}) tuple(f32[200]{0} %reduce.0, f32[200,32]{1,0} %broadcast.0)
}

ENTRY %main.0 (Arg_0.1: f32[200,32]) -> (f32[200], f32[200,32]) {
  %Arg_0.1 = f32[200,32]{1,0} parameter(0)
  ROOT %input_fusion_reduce.9.clone3 = (f32[200]{0}, f32[200,32]{1,0}) fusion(), kind=kInput, calls=%fused_reduce.1
}
```

### Relevant log output

_No response_</details>

**Comment by cheshire** [comment]
Tracked internally in b/237924658, patches welcome as usual :P

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
