### ISSUE TITLE
some questions about tflite with gpu delegates

### ISSUE THREAD

**Issue by FengMu1995** [tensorflow/tensorflow#56558]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf2.8

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Current Behaviour?

```shell
"interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk "
when will this situation happen?
is it when mydevice does not contain gpu?
```

### Standalone code to reproduce the issue

```shell
/
```

### Relevant log output

_No response_</details>

**Comment by FengMu1995** [comment]
Tflite GPU delegates support linux-X86-Destop Nvidia-gpu?

**Comment by mohantym** [comment]
Hi @FengMu1995 ! 

The GPU delegate is currently harnessed from Mobile GPUs only. For desktop purpose, you can build the delegate files using bazel and initialize it with interpreter option after loading  it using [tf.lite.experimental.load_delegate](https://www.tensorflow.org/lite/api_docs/python/tf/lite/experimental/load_delegate).

Thank you!

**Comment by FengMu1995** [comment]
Thank you for your reply.
And I have another question, if (interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk), is it because I run it on no-gpu device?

**Comment by mohantym** [comment]
@FengMu1995 ! 
Few reasons not detecting GPU delegate be from below. 
1. You have not declared Gpu [dependencies](https://www.tensorflow.org/lite/performance/gpu#step_2_edit_appbuildgradle_to_use_the_nightly_gpu_aar) in build.gradle file.
2.  If there is no  Gpu on device 

Could you move this to closed status if it is resolved.

**Comment by FengMu1995** [comment]
ok， thanks
