### ISSUE TITLE
Indexing a ragged tensor over a non-ragged index fails in tf.keras.Model

### ISSUE THREAD

**Issue by pstjohn** [tensorflow/tensorflow#56565]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9.1, nightly

### Custom Code

No

### OS Platform and Distribution

colab

### Python version

3.7

### Bazel version

n/a

### GCC/Compiler version

n/a

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current Behaviour?

```shell
Indexing a ragged tensor over a non-ragged dimension throws an error inside a tf.keras.Model. I'm trying to slice a ragged tensor containing a known amount of features, i.e., with shape (batch_size, ragged_dim, known_feature_dim) by the last axis inside a Keras model, hopefully returning a (batch_size, ragged_dim) tensor of features.

This works in eager mode with a tf.ragged.constant, but a model (that works with a tf.constant) fails when passed the same ragged constant.
```

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1eSEdKidC1A4kw5EYeYimKrSEHkV6EndS?usp=sharing
```

### Relevant log output

```shell
ValueError: Exception encountered when calling layer "tf.__operators__.getitem" "                 f"(type SlicingOpLambda).

TypeError: object of type 'RaggedTensor' has no len()


Call arguments received by layer "tf.__operators__.getitem" "                 f"(type SlicingOpLambda):
  • tensor=<tf.RaggedTensor [[[1, 2, 3],
  [4, 5, 6],
  [7, 8, 9]], [[2, 3, 4],
               [5, 6, 7]], [[3, 4, 5]]]>
  • slice_spec=({'start': 'None', 'stop': 'None', 'step': 'None'}, {'start': 'None', 'stop': 'None', 'step': 'None'}, '0')
  • var=None
```
</details>

**Comment by sushreebarsa** [comment]
@pstjohn 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
