### ISSUE TITLE
how to close the profiler feature

### ISSUE THREAD

**Issue by yuqj1991** [tensorflow/tensorflow#56564]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

binary

### Tensorflow Version

tf2.5

### Custom Code

Yes

### Current Behaviour?

```shell
how to close profiler
```

### Standalone code to reproduce the issue

```shell
how to close profiler
```

### Relevant log output

```shell
how to close profiler
```
</details>

**Comment by tilakrayal** [comment]
Hi @yuqj1991,
Could you try the mentioned code to stop the profiler. Also kindly take a look at this doc link1 and link2 which delivers the information.
```
tf.profiler.experimental.stop(
    save=True
)
```
 Thank you!
