### ISSUE TITLE
Add `cdist` - an analog of `scipy.cdist` | `torch.cdist`

### ISSUE THREAD

**Issue by innat** [tensorflow/tensorflow#56575]
# Feature Request

Source: binary
Tensorflow Version: 2.9
Custom Code: Yes

# Current Behavior

There is no equivalent built-in function of the following two in `TensorFlow`. I need to use this method on large size embedding vectors and require a efficient vectorized implementation.

```python
scipy.spatial.distance.cdist
torch.cdist
```

The same request has been asked several times but closed without any strong reason and no response further to a new commenter. So, kindly **DO NOT CLOSE** without further discussion. 

- https://github.com/tensorflow/tensorflow/issues/30659#
- https://github.com/tensorflow/tensorflow/issues/9745#

**Comment by cantonios** [comment]
>  still I think it would be nice to have it in core tensorflow (same as torch).

We don't necessarily try to mirror pytorch.  We mostly want consistency with numpy and jax.  If an op is heavily used and in large production models, we have more incentive to add it to tensorflow core.

How big are the batch/patch/embedding sizes (in actual numbers)?

**Comment by innat** [comment]
The reason I'm referring pytorch here is because for the end user who may want to translate code from one framework to another.  He will initially look for similar operation.  

Here is the size of two tensor (`[Batch*Patch*Patch, Embedding]`). (Size of the first index may vary depending on the patch size.)

```
1st: ([4096, 1536])
2nd: ([8624, 1536])
```

**Comment by cantonios** [comment]
You can try the following:
```
@tf.function
def cdist(x, y):
  # Calculate distance for a single row of x.
  per_x_dist = lambda i : tf.norm(x[:,i:(i+1),:] - y, axis=2)
  # Compute and stack distances for all rows of x.
  dist = tf.map_fn(fn=per_x_dist, elems=tf.range(tf.shape(x)[1], dtype=tf.int64), fn_output_signature=x.dtype)
  # Re-arrange stacks of distances.
  return tf.transpose(dist, perm=[1, 0, 2])
```
This essentially computes the distance matrix one row at a time (with parallel iterations in graph mode), then re-assembles the full distance matrix.  Memory is bounded by `size(y) * parallel_iterations` , so should never blow up.  Input sizes are the same as in torch.cdist.

**Comment by cantonios** [comment]
Closing, as a work-around has been presented with no response.

**Comment by innat** [comment]
@cantonios Hello. Sorry for long silence. I had to pause the project that caused this ticket. I will revisit it as soon as possible after dealing with [this issue](https://github.com/tensorflow/tensorflow/issues/56934).
