### ISSUE TITLE
How to build tensorflow from source, so that it works similar across INTEL and AMD CPUs (in terms of floating point math precision)

### ISSUE THREAD

**Issue by GChaitanya2001** [tensorflow/tensorflow#56586]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

1.15

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.6.9

### Bazel version

0.26.1

### GCC/Compiler version

7.5.0

### Current Behaviour?

I am trying to build tensorflow from source(v1.15) as I was getting a difference in floating point math precision across INTEL and AMD CPUs(refer to issue #56529). What are the possible options to provide for the build command to fix this? I am looking for a solution for either TF v1.15 or TF v2.3. 

I tried the following build commands, 
```shell
1)  bazel --output_base=/local/mnt/workspace/gsaichai build --config=v1 --config=mkl --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-mfpmath=387 --copt=-mtune=generic --copt=-march=x86-64 --host_copt=-march=x86-64 --verbose_failures //tensorflow/tools/pip_package:build_pip_package

2)  bazel --output_base=/local/mnt/workspace/gsaichai build --config=v1 --config=mkl --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-mfpmath=387 --copt=-march=x86-64 --host_copt=-march=x86-64 --verbose_failures //tensorflow/tools/pip_package:build_pip_package

```
But the difference was still present.

<s>These commands are resulting in the following error,
```shell
ERROR: /local/mnt/workspace/gsaichai/qnn_src/tensorflow/tensorflow/python/BUILD:329:1: C++ compilation of rule '//tensorflow/python:bfloat16_lib' failed (Exit 1)
tensorflow/python/lib/core/bfloat16.cc: In function 'bool tensorflow::{anonymous}::Initialize()':
tensorflow/python/lib/core/bfloat16.cc:634:36: error: no match for call to '(tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>) (const char [6], <unresolved overloaded function type>, const std::array<int, 3>&)'
                       compare_types)) {
                                    ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note: candidate: tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>
                             const std::array<int, 3>& types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note:   no known conversion for argument 2 from '<unresolved overloaded function type>' to 'PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}'
tensorflow/python/lib/core/bfloat16.cc:638:36: error: no match for call to '(tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>) (const char [10], <unresolved overloaded function type>, const std::array<int, 3>&)'
                       compare_types)) {
                                    ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note: candidate: tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>
                             const std::array<int, 3>& types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note:   no known conversion for argument 2 from '<unresolved overloaded function type>' to 'PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}'
tensorflow/python/lib/core/bfloat16.cc:641:77: error: no match for call to '(tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>) (const char [5], <unresolved overloaded function type>, const std::array<int, 3>&)'
   if (!register_ufunc("less", CompareUFunc<Bfloat16LtFunctor>, compare_types)) {
                                                                             ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note: candidate: tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>
                             const std::array<int, 3>& types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note:   no known conversion for argument 2 from '<unresolved overloaded function type>' to 'PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}'
tensorflow/python/lib/core/bfloat16.cc:645:36: error: no match for call to '(tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>) (const char [8], <unresolved overloaded function type>, const std::array<int, 3>&)'
                       compare_types)) {
                                    ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note: candidate: tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>
                             const std::array<int, 3>& types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note:   no known conversion for argument 2 from '<unresolved overloaded function type>' to 'PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}'
tensorflow/python/lib/core/bfloat16.cc:649:36: error: no match for call to '(tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>) (const char [11], <unresolved overloaded function type>, const std::array<int, 3>&)'
                       compare_types)) {
                                    ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note: candidate: tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>
                             const std::array<int, 3>& types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note:   no known conversion for argument 2 from '<unresolved overloaded function type>' to 'PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}'
tensorflow/python/lib/core/bfloat16.cc:653:36: error: no match for call to '(tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>) (const char [14], <unresolved overloaded function type>, const std::array<int, 3>&)'
                       compare_types)) {
                                    ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note: candidate: tensorflow::{anonymous}::Initialize()::<lambda(const char*, PyUFuncGenericFunction, const std::array<int, 3>&)>
                             const std::array<int, 3>& types) {
                                                            ^
tensorflow/python/lib/core/bfloat16.cc:608:60: note:   no known conversion for argument 2 from '<unresolved overloaded function type>' to 'PyUFuncGenericFunction {aka void (*)(char**, const long int*, const long int*, void*)}'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 232.568s, Critical Path: 63.39s
INFO: 1208 processes: 1208 local.
FAILED: Build did NOT complete successfully

``` 
</s>

<b>The above error got resolved after making some changes to my ./configure file. But the resulting tensorflow packages are still resulting in the difference between AMD and INTEL. Please let me know what are the options that I can provide while building Tensorflow from source(for v1.15 or v2.3), so that the floating point math is consistent across AMD and INTEL</b> 
### Standalone code to reproduce the issue

```shell
None
```

### Relevant log output

_No response_</details>

**Comment by GChaitanya2001** [comment]
I updated the issue. Please check. Thank you!

**Comment by mohantym** [comment]
Hi @GChaitanya2001 ! 

Could you check the below command with 2.3 or 2.8 version and let us know the difference. 

Command to build for [AMD wheels ](https://www.tensorflow.org/install/source_windows#install_the_package)is 
`bazel build --config=opt  --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
`Command to build for Intel [OneDNN wheels ](https://www.intel.com/content/www/us/en/developer/articles/guide/optimization-for-tensorflow-installation-guide.html)
`bazel build --config=mkl -c opt --copt=-march=native //tensorflow/tools/pip_package:build_pip_package`

Thank you!

**Comment by GChaitanya2001** [comment]
Hi @mohantym,
Thank you for the response. I actually tried installing TF v2.9 binary using pip. That version wasn't giving any difference across INTEL and AMD. Can you please let me know the commands for v2.3?

**Comment by mohantym** [comment]
@GChaitanya2001 !
You can use the above commands in 2.3 version too. Thank you!

**Comment by GChaitanya2001** [comment]
Hi @mohantym,
I ran the above two commands and I am still able to see the difference between AMD and INTEL. Please let me know about any other flag I can provide. Thank you!

**Comment by mohantym** [comment]
Hi @gadagashwini  ! Could you look at this issue. Thank you!

**Comment by GChaitanya2001** [comment]
Hi all, 
Can I know what does Tensorflow use in the background to perform floating point math operations like sqrt? 
I found this,
TF 2.3 - https://github.com/tensorflow/tensorflow/blob/r2.3/tensorflow/core/kernels/cwise_op_sqrt.cc
TF 2.9 - https://github.com/tensorflow/tensorflow/blob/r2.9/tensorflow/core/kernels/cwise_op_sqrt.cc
There is a slight difference in the implementation. Is that the reason why TF 2.3 and TF 2.9 are behaving differently? (I am comparing these two versions, in a hope that it will help me identify the compiler flags that I can use to build TF from source for TF 2.3)  Please let me know you views on this.

Thank you!

**Comment by mihaimaruseac** [comment]
You can check [the history for the file](https://github.com/tensorflow/tensorflow/commits/r2.9/tensorflow/core/kernels/cwise_op_sqrt.cc). Most likely you will be interested in 7c88fd1dc7ecf720739c4b39a62c81de32071fc3 which is [available from TF 2.5](https://github.com/tensorflow/tensorflow/commit/7c88fd1dc7ecf720739c4b39a62c81de32071fc3)

**Comment by GChaitanya2001** [comment]
Hi @mihaimaruseac,
Thank you for the response! But I am mostly looking around CPU based Op implementations, especially sqrt/rsqrt. I am trying to understand what instructions are used by tensorflow in the backend to perform those ops, as I wanted to build TF from source with proper compiler options to avoid mismatches between AMD and INTEL for floating point ops.  (#56529)
Thank you!

**Comment by GChaitanya2001** [comment]
Is there a way to build TF **without** using basic CPU optimizations like SSE, SSE2 etc on x86-64 CPUs? Looks like using -march=x86-64 enables SSE, SSE2, SSE3 by default which might be resulting in the mismatch. Please let me know any build options which does not allow SSE and other CPU optimizations.

Thank you!

**Comment by mihaimaruseac** [comment]
You need to pass these flags to the compiler itself. Bazel has `--cxxopts`, `--copts`, etc., but you'll need to read your compiler's documentation to find out what flags to send to it to not do these optimizations.

**Comment by SuryanarayanaY** [comment]
@GChaitanya2001 ,

Could you please confirm whether the above [comment-1182124567](https://github.com/tensorflow/tensorflow/issues/56586#issuecomment-1182124567) solved your issue. Eager to know if this is still an issue. Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @GChaitanya2001 ,

Thanks for coming back and confirming that the issue got resolved with a workaround.

Please feel free to close the issue if resolved. Thanks!
