### ISSUE TITLE
How to convert saved model to tflite format model partly?

### ISSUE THREAD

**Issue by njuhang** [tensorflow/tensorflow#56588]
### 1. System information

- WSL (Linux Ubuntu 20.04):
- TensorFlow library version  2.7.0

### 2. Code

```
tflite_convert --output_file=./detection.tflite --saved_model_dir=model_dir --input_arryas=input --output_arrays=output --input_shape=1,224,224,3 --experimental_new_converter=true --allow_custom_ops
```

### 3. Failure after conversion
I could pass convert. But I get the whole graph after conversion. I want to set  intermediate node as output node. What should I do?

**Comment by mohantym** [comment]
Hi @njuhang !
You can specify the desired intermediate nodes in output_arrays to visualize them properly.
```
tflite_convert --output_file=./detection.tflite --saved_model_dir=model_dir --input_arrays=input --output_arrays="output_node,intermediate/node/n1,intermediate/node/n2" --input_shape=1,224,224,3 --experimental_new_converter=true --allow_custom_ops

      
```
Attached relevant[ thread]( https://stackoverflow.com/a/56961776/11530462) for reference. 
Thank you!

**Comment by njuhang** [comment]
I followed this instruction to do conversion. But I got the whole graph in .tflite. I tried to specify some intermediate nodes as output_arrays but failed.  No matter what I specify to parameter output_arrays, even if some meaningless name, there is no difference in .tflite file. 
What I want is to cut a piece from the whole graph.Thanks

**Comment by mohantym** [comment]
Ok @njuhang ! Thanks for the clarification. @sachinprasadhs ! Could you look at this issue. Thank you!

**Comment by njuhang** [comment]
Is there any suggestions?

**Comment by mohantym** [comment]
Hi @njuhang !
I came across this issue where user divided lite model to multiple sub-graphs using below method.
tflite::SubgraphWriter

will that work for you ?
[Reference.](https://github.com/tensorflow/tensorflow/issues/44606)

Thank you!
