### ISSUE TITLE
How to convert my object detection dataset to Tensorflow COCO format

### ISSUE THREAD

**Issue by allansdefreitas** [tensorflow/tensorflow#56583]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

Yes

### Python version

 3.7.13

### Current Behaviour?

```shell
I’m running this Tensorflow implementation of Retinanet (https://keras.io/examples/vision/retinanet/ and I want to adapt it to my own Object Detection dataset.

The problem is that the author gets COCO dataset via tfds.load()
I explored these TFRecords files and I noticed that their image annotations are in a different way (different from default COCO annotations) as shown in this image: https://bit.ly/3yjYHDA

Is there a way to generate TFRecords files in this specific format of annotations for my own dataset (not get a ready-to-use dataset from tfds)?

Thanks a lot!
```

### Standalone code to reproduce the issue

```shell
https://keras.io/examples/vision/retinanet/
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@allansdefreitas,
I was able to execute the provided code without any issues. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3de1672d69ad19067646d45ab9895d1d/retinanet.ipynb).

**Comment by allansdefreitas** [comment]
> @allansdefreitas, I was able to execute the provided code without any issues. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3de1672d69ad19067646d45ab9895d1d/retinanet.ipynb).

@tilakrayal , me too: I ran this code perfectly. The problem is that I don't know how to load my own dataset to this retinanet.

**Comment by tilakrayal** [comment]
@allansdefreitas,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by allansdefreitas** [comment]
> @allansdefreitas, Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues).
> 
> Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues). To know more please refer: https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999 Thank you!

Thanks, @tilakrayal . I just created a new issue in the appropiated place.
If someone can help me, please, feel free: https://github.com/keras-team/keras/issues/16748
