### ISSUE TITLE
ValueError: Duplicate node name in graph: 'model/lambda_16/zeros/packed'

### ISSUE THREAD

**Issue by RMNT** [tensorflow/tensorflow#56589]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

1.15

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

-

### Python version

3.7

### CUDA/cuDNN version

10.0.130

### Current Behaviour?

```shell
Getting error ValueError: Duplicate node name in graph: 'model/lambda_16/zeros/packed' weren't able to find a way to fix it on the net
```

### Standalone code to reproduce the issue

```shell
I ran code from https://github.com/ameraner/dsen2-cr. The code with images and prepared csv file can be found here: https://drive.google.com/drive/folders/13gN68q5nH_h6VQtjga992UOXUsWUZV6m?usp=sharing. It is run with  dsen2-cr/Code/dsen2cr_main.py --predict dsen2-cr/model_SARcarl.hdf5 it run for a long time
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
Hi @RMNT! Older version of TF(1.15) is not actively supported. We recommend you to kindly upgrade to the latest version and let us know the outcome?
Thank you!
