### ISSUE TITLE
Clip weight values when converting to int8 tflite models

### ISSUE THREAD

**Issue by Rahn80643** [tensorflow/tensorflow#56587]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): TF 1.14

### 2. Code

Provide code to help us reproduce your issues using one of the following options:
```
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
            args.pb_path, 
            [args.input_node_name], 
            [args.output_node_name], 
            input_shapes=input_shape
        )
        converter.allow_custom_ops = True
        converter.optimizations = [tf.lite.Optimize.DEFAULT] # require representative dataset
        converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
        converter.inference_input_type = tf.int8 
        converter.inference_output_type = tf.int8 
        converter.default_ranges_stats = (2.3283064e-10, 4294967295) # 2022.06.22: weight clipping

        converter.representative_dataset = representative_data_gen
        tflite_int8_model = converter.convert()
```

### 3. Failure after conversion
Hi, 

I'm trying to limit the range the weight values of tflite models because there are limited supported range of weight values on the  hardware I use. Therefore, I have tried to apply `default_ranges_stats` when converting the trained model to an int8 tflite model. However, the weight values of converted model are not changed.

Is there other methods to limit the range of tflite models during the conversion stage?

Best Regards

**Comment by mohantym** [comment]
Hi @Rahn80643 ! 
1.x versions are not supported any more

Min and Max values  in the tuple of [default_ranges_stats](https://www.tensorflow.org/api_docs/python/tf/compat/v1/lite/TFLiteConverter#:~:text=default_ranges_stats) has to be integer ones. Please test with integer values and let us know if it works.

Thank you!
