### ISSUE TITLE
MKL use cannot be disabled 

### ISSUE THREAD

**Issue by hshazly** [tensorflow/tensorflow#56603]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

TF 2.8.0

### Custom Code

No

### OS Platform and Distribution

Linux CentOS 8

### Python version

3.8.8

### Bazel version

4.2.1

### GCC/Compiler version

8.2.1

### Current Behaviour?

```shell
I'm trying to disable the use of JIT kernels entirely. 
Exporting the environment variable TF_ENABLE_ONEDNN_OPTS=0 does not seem to have any effect, TF still calls: jit_avx512_common_gemm_f32.cpp from _pywrap_tensorflow_internal.so.

P.S.: TensorFlow is built without --config=MKL
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

def test():
    x = [1]*100
    W = tf.Variable(tf.ones(shape=(100,100)), name="W")
    b = tf.Variable(tf.zeros(shape=(100)), name="b")
    return W * x + b

if __name__ == "__main__":
    test()
```

### Relevant log output

_No response_</details>

**Comment by gadagashwini** [comment]
Hi @hshazly, Custom `TF-oneDNN` ops are disabled by default, but can be enabled by setting an environment variable `TF_ENABLE_ONEDNN_OPTS=1`.
You can build with just `--config=opt`.
Thank you!

**Comment by hshazly** [comment]
Thank you @gadagashwini. I built with `--config=opt -c dbg --strip=never` to include the debug info in the binaries and it didn't call `jit_avx512_common_gemm_f32` anymore. It just calls `SetupOrDisableJit`, which I read that it deactivates JIT kernels until it is re-enabled again.
