### ISSUE TITLE
Allow int16 input/output even when not using 16x8 quantization mode

### ISSUE THREAD

**Issue by hguihot** [tensorflow/tensorflow#56615]
Currently the valid types can be either `int16` or `int8`/`uint8`, but not a combination of both. Some models could for example contain a custom op returning an `int16` tensor as model output, and converting such model to TFLite is failing. It looks like always adding `_dtypes.int16` to the list of supported types when [quant_mode.is_integer_quantization()](https://github.com/tensorflow/tensorflow/blob/fd663c96bd88d37174a99a4dbaeb37b9f945505c/tensorflow/lite/python/lite.py#L946) is true would be enough to make it work.

**Comment by mohantym** [comment]
Hi @hguihot ! Could you also share a minimal standalone code too to expedite the issue. Thank you!

**Comment by hguihot** [comment]
Here is an example with 2 convolutions, both with the same 8-bit input but one with 8-bit output and the other with 16-bit output.
```
import tensorflow as tf

def quant(x, num_bits=8):
    return tf.quantization.fake_quant_with_min_max_args(x, -1, 1, num_bits, False)

class QConv(tf.keras.layers.Conv2D):
    def __init__(self, filters, kernel_size, weight_quantizer, activation_quantizer):
        self.weight_quantizer = weight_quantizer
        self.activation_quantizer = activation_quantizer
        super().__init__(filters = filters, kernel_size = kernel_size)

    def call(self, bottom):
        return self.activation_quantizer(self.convolution_op(bottom, self.weight_quantizer(self.kernel)))

tf.keras.backend.set_image_data_format("channels_last")
input_tensor = tf.keras.Input(shape=(64, 64, 3), batch_size=1)
quantized_input_tensor = quant(input_tensor, num_bits=8)

# 8->8bit convolution
layer = QConv(filters=32, kernel_size=3, weight_quantizer=quant, activation_quantizer=lambda x: quant(x, num_bits=8))
output8 = layer(quantized_input_tensor)

# 8->16bit convolution
layer = QConv(filters=32, kernel_size=3, weight_quantizer=quant, activation_quantizer=lambda x: quant(x, num_bits=16))
output16 = layer(quantized_input_tensor)

model = tf.keras.Model(inputs=[input_tensor], outputs=[output8, output16])

train_save_path = "/tmp/debug_model"
convert_model_path = "/tmp/converted.tflite"

model.save(train_save_path)
converter = tf.lite.TFLiteConverter.from_saved_model(train_save_path)
converter.optimizations =[tf.lite.Optimize.DEFAULT]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int16
tflite_model = converter.convert()

with open(convert_model_path, "wb") as f:
    f.write(tflite_model)
```
Two changes were actually required to make the conversion succeed:
- Add `_dtypes.int16` to `all_types` in `_validate_inference_input_output_types` in [tensorflow/lite/python/lite.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/lite.py#L954)
- Add `dtypes.int16` to `_MAP_QUANT_TO_IO_TYPES` in [tensorflow/lite/python/util.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/util.py#L81)

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you look at this feature request. Attached [gist](https://colab.sandbox.google.com/gist/mohantym/5f09ddc3445dd62001a305c26a68d90c/git_56615.ipynb) for reference. Thank you!

**Comment by hguihot** [comment]
Any update?

**Comment by pjpratik** [comment]
We created PR [#59526](https://github.com/tensorflow/tensorflow/pull/59526) to enable support `dtypes.int16`. The issue will be closed once this is merged. Thanks!

**Comment by pjpratik** [comment]
Hi @hguihot 

The support for `int16` has been added with the commit https://github.com/tensorflow/tensorflow/commit/33d76ac43597e48bf3c321ec6d9b0859bb4c94bc. 

Closing this issue as resolved. Please reopen if you'd like to work on this further.
