### ISSUE TITLE
Windows support for tf.contrib libraries in the PIP package.

### ISSUE THREAD

**Issue by laudney** [tensorflow/tensorflow#5662]
Is there any documentation or tutorial on how to include tf.contrib libraries in the PIP package built with cmake on Windows?

Or to install tf.contrib libraries as a separate step?

**Comment by mrry** [comment]
Pull request #5634 re-enables tf.contrib in the Windows/CMake PIP package (it's currently broken because a new package was added and the CMake rules don't reflect it yet). If that doesn't work, please let us know on this issue!

**Comment by laudney** [comment]
I can confirm the PR successfully includes tf.contrib in the PIP package on Windows. @mrry Thank you, sir!
