### ISSUE TITLE
[tflite converter] tflite is empty (zero bytes) after "successful" conversion (no errors)

### ISSUE THREAD

**Issue by josephrocca** [tensorflow/tensorflow#56629]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04 (Google Colab)
- TensorFlow installation (pip package or built from source): Pip
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.8.0 

### 2. Code

Please see this Colab for a minimal reproduction: https://colab.research.google.com/gist/josephrocca/201179c22859aacee123e2505f526089/minimal-empty-tflite-file-produced-by-tfliteconverter-converting-dalle-mini-bart-saved-model.ipynb

Here's the code from that Colab:
```py
!wget https://huggingface.co/rocca/dalle-mini-js/resolve/main/debug/dalle-mini-tfsavedmodel.zip
!unzip dalle-mini-tfsavedmodel.zip
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model("/content/content/dalle-mini-tfsavedmodel")
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_model = converter.convert()
with open('/content/content/dalle-mini.tflite', 'wb') as f:
  f.write(tflite_model)
```

### 3. Failure after conversion
The conversion is "successful" (no errors shown), but the tflite file is empty (zero bytes).

**Comment by mohantym** [comment]
Hi @gowthamkpr ! 
Could you look at this issue. Attached gist in [2.8,](https://colab.sandbox.google.com/gist/mohantym/b30c26993c6e65299986342d77c9858c/minimal-empty-tflite-file-produced-by-tfliteconverter-converting-dalle-mini-bart-saved-model.ipynb#scrollTo=n5ftbSJUM4sz), [2.9](https://colab.sandbox.google.com/gist/mohantym/64288d0dbc91065a827f2a98b06a8012/minimal-empty-tflite-file-produced-by-tfliteconverter-converting-dalle-mini-bart-saved-model.ipynb#scrollTo=yfH6UYUTtcQh) and [nightly](https://colab.sandbox.google.com/gist/mohantym/1df0ce042ef78c37f893e4ea5a408f44/minimal-empty-tflite-file-produced-by-tfliteconverter-converting-dalle-mini-bart-saved-model.ipynb#scrollTo=P9mtilHxbJPu) for reference. Thank you!

**Comment by josephrocca** [comment]
@mohantym @gowthamkpr Something very strange: The above example notebook that I linked squashes the dalle mini encoder and decoder into the same function, but if I separate them out into their own functions and convert them to tflite separately, then the conversion works.

Here's a notebook demonstrating that (you may need Colab Pro+ or use a JupyterLab machine with more memory, else you may get an out-of-memory crash):

https://colab.research.google.com/gist/josephrocca/f427377f76c574f1c1e8e4d6d62c34b6/tflite-dalle-mini-conversion-separated-encoder-and-decoder.ipynb

```py
# This converts successfully.
def encode(text_tokens):
  encoder_state = dalle_bart_encoder_flax_model(text_tokens)
  return encoder_state

# This converts successfully.
def decode(text_tokens, encoder_state, seeded_prng_key):
  image_tokens = dalle_bart_decoder_flax_model.sample_image_tokens(
        text_tokens,
        encoder_state,
        seeded_prng_key,
        params_dalle_bart['decoder'],
    )
  return image_tokens

# This converts "successfully" (no errors), but the resulting file is 0kb
def encode_and_decode(text_tokens, seeded_prng_key):
  encoder_state = encode(text_tokens)
  image_tokens = decode(text_tokens, encoder_state, seeded_prng_key)
  return image_tokens
```

This seems very strange because there's nothing "extra" in `encode_and_decode` - it just joins the `encode` and `decode` functions together, which both separately converted successfully.

**Comment by gowthamkpr** [comment]
@josephrocca I am glad you were able to convert the model by separating encoder and decoder. 
I am attaching the working model colab gist [here](https://colab.research.google.com/gist/josephrocca/f427377f76c574f1c1e8e4d6d62c34b6/tflite-dalle-mini-conversion-separated-encoder-and-decoder.ipynb). 

Can you please attach the entire model for which tf lite conversion yields zero bytes (empty)

**Comment by josephrocca** [comment]
Hi @gowthamkpr, if I understand correctly, you're looking for the Colab link in my first comment on this issue? Here's that link again:

https://colab.research.google.com/gist/josephrocca/201179c22859aacee123e2505f526089/minimal-empty-tflite-file-produced-by-tfliteconverter-converting-dalle-mini-bart-saved-model.ipynb

And here's all the code that this notebook contains:

```py

!wget https://huggingface.co/rocca/dalle-mini-js/resolve/main/debug/dalle-mini-tfsavedmodel.zip
!unzip dalle-mini-tfsavedmodel.zip
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model("/content/content/dalle-mini-tfsavedmodel")
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_model = converter.convert()
with open('/content/content/dalle-mini.tflite', 'wb') as f:
  f.write(tflite_model)
```

As you can see, the model file is located at https://huggingface.co/rocca/dalle-mini-js/resolve/main/debug/dalle-mini-tfsavedmodel.zip

**Comment by gowthamkpr** [comment]
@josephrocca Please share the code where the encoder and decoder is merged together, since that is where the bug is right. Thanks!

**Comment by josephrocca** [comment]
@gowthamkpr Yes, the code in my last comment (and in my original issue comment) has the model where the encoder and the decoder are merged together. If you run the Colab I linked in my last comment, it'll produce a tflite model that has a filesize of zero bytes.

It is only the notebook I linked in [this comment](https://github.com/tensorflow/tensorflow/issues/56629#issuecomment-1172928973) that has the encoder and decoder separated.

If you're looking for the code that generated the TF SavedModel that is used in that example, here you go: https://colab.research.google.com/gist/josephrocca/7dff488a71b55266c8d603709ecffc98/minimal-dalle-mini-inference-and-tflite-conversion-produces-zero-byte-tflite-model.ipynb That converts the JAX model to the TF SavedModel, and then converts the TF SavedModel to a TFLite file (of size zero bytes).

**Comment by sachinprasadhs** [comment]
Could you try saving the model with `model.save` instead of `saved_model.save` to let us know the outcome.

**Comment by josephrocca** [comment]
Hi @sachinprasadhs, `tf.Module` don't have a save method unless I'm mistaken (I just tried it to make sure). Please see the last two cells of this notebook if you'd like to replicate this. Just make any edits you'd like and then click "Runtime > Run all" and you'll see the issue:

https://colab.research.google.com/gist/josephrocca/7dff488a71b55266c8d603709ecffc98/minimal-dalle-mini-inference-and-tflite-conversion-produces-zero-byte-tflite-model.ipynb

(Note that the runtime may crash on the last cell, but just run it again)

**Comment by sachinprasadhs** [comment]
You could try creating the concrete function by something like below code 
```
from_concrete_functions
jax2tf.convert -> tf_function 
tf_function.get_concrete_function()

tflConverter.from_concrete_functions
```
and then load to to TFLite using [Models built from concrete functions](https://www.tensorflow.org/guide/intro_to_graphs)
