### ISSUE TITLE
TF TESTs failures: //tensorflow/lite/kernels:squeeze_test  //tensorflow/lite/kernels:reshape_test

### ISSUE THREAD

**Issue by psunn** [tensorflow/tensorflow#56635]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

latest master branch

### Custom Code

No
</details>

### Current Behaviour?

```shell
TF TESTs failures:
//tensorflow/lite/kernels:squeeze_test
//tensorflow/lite/kernels:reshape_test


tensorflow/lite/kernels/reshape_test.cc:197:1:   required from here
23:16:54  bazel-out/k8-opt/bin/external/flatbuffers/_virtual_includes/flatbuffers/flatbuffers/flatbuffer_builder.h:652:31: error: ‘const class std::initializer_list<int>’ has no member named ‘data’
23:16:54    652 |     return CreateVector(array.data(), array.size());
23:16:54        |                         ~~~~~~^~~~
```
(similar mesg with `squeeze_test`)
```


### Standalone code to reproduce the issue

```shell
bazel test //tensorflow/lite/kernels:squeeze_test
```

**Comment by psunn** [comment]
some analysis from our side:

these TESTs was working as: https://github.com/google/flatbuffers/blob/faadbc10ea4b77bc57960696ef0d1d053536c68a/include/flatbuffers/flatbuffer_builder.h#L668 was called, the std::initializer_list was implicitly converted to a std::vector.
these TESTs now failing due to:
recent updates: [Add CreateVector overload to accept array like](https://github.com/tensorflow/tensorflow/commit/bf0901b663e87f081c7a317fe1ac705ab1a2df8b,)
[Update FlatBuffer to 2.0.6](https://github.com/google/flatbuffers/commit/faadbc10ea4b77bc57960696ef0d1d053536c68a) that is FlatBuffers 2.0.6 add a CreateVector overload.

We notice recent change on FlatBuffer: [Specialize CreateVector with std::initializer_list](https://github.com/google/flatbuffers/commit/7bcd857b87f5e6e2711f66697e486998d0d0419d) would resolve current tests failures. (TF Update FlatBuffer that include this change)
otherwise, changes on current TF would work as well:
<details><summary>Click to expand!</summary> 
```
diff --git a/tensorflow/lite/kernels/reshape_test_common.h b/tensorflow/lite/kernels/reshape_test_common.h
index 662c163b7c0..8901234270f 100644
--- a/tensorflow/lite/kernels/reshape_test_common.h
+++ b/tensorflow/lite/kernels/reshape_test_common.h
@@ -86,7 +86,8 @@ class ReshapeOpModel : public BASE {
         BuiltinOperator_RESHAPE, BuiltinOptions_ReshapeOptions,
         CreateReshapeOptions(
             this->builder_,
-            this->builder_.template CreateVector<int>(shape_data))
+            this->builder_.template CreateVector(
+                reinterpret_cast<const int*>(shape_data.begin()), shape_data.size()))
             .Union());
     this->BuildInterpreter({this->GetShape(input_)});
   }
@@ -102,7 +103,8 @@ class ReshapeOpModel : public BASE {
         BuiltinOperator_RESHAPE, BuiltinOptions_ReshapeOptions,
         CreateReshapeOptions(
             this->builder_,
-            this->builder_.template CreateVector<int>(shape_data))
+            this->builder_.template CreateVector(
+                reinterpret_cast<const int*>(shape_data.begin()), shape_data.size()))
             .Union());
     this->BuildInterpreter(
         {this->GetShape(input_), this->GetShape(shape_input_tensor)});
@@ -122,7 +124,8 @@ class ReshapeOpModel : public BASE {
         BuiltinOperator_RESHAPE, BuiltinOptions_ReshapeOptions,
         CreateReshapeOptions(
             this->builder_,
-            this->builder_.template CreateVector<int>(shape_data))
+            this->builder_.template CreateVector(
+                reinterpret_cast<const int*>(shape_data.begin()), shape_data.size()))
             .Union());
     this->BuildInterpreter({this->GetShape(input_)});
```

</details>

**Comment by mohantym** [comment]
Hi @psunn !
It is replicating only in [2.10.0dev](https://colab.sandbox.google.com/gist/mohantym/ce29e1d903f5120c44daa75ddbacbc4c/tensorflow-ranking.ipynb#scrollTo=i5DTdT870IGD)(nightly) Version. Could we stick to [2.8](https://colab.sandbox.google.com/gist/mohantym/0630e7a45cd406943d7f3eb75473e4a2/tensorflow-ranking.ipynb#scrollTo=Q9GeNN3QzVUq)/[2.9](https://colab.sandbox.google.com/gist/mohantym/296abbeefbd83d0545fcc8c5e0494080/tensorflow-ranking.ipynb#scrollTo=i5DTdT870IGD) version for a while. 
Thank you!
