### ISSUE TITLE
How to convert tf.data.Dataset column which is converted into byte, back to string?

### ISSUE THREAD

**Issue by dexter1729** [tensorflow/tensorflow#56646]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.8.2

### Custom Code

Yes

### Current Behaviour?

```shell
I converted a Pandas dataframe into Tensorflow Dataset using `ratings = tf.data.Dataset.from_tensor_slices(dataframe.to_dict(orient="list"))`. Now, all the values which were in string format in dataframe are converted into byte format. How to convert values of a particular column back to string?
```

### Standalone code to reproduce the issue

```shell
ratings = tf.data.Dataset.from_tensor_slices(dataframe.to_dict(orient="list"))
for x in ratings.take(1).as_numpy_iterator():
  pprint.pprint(x)

Output is : 
'movie_id': b'357',
'movie_title': b"One Flew Over the Cuckoo's Nest (1975)",
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@dexter1729 
In order to expedite the trouble-shooting process, please provide a complete code snippet to reproduce the issue reported here. Thank you!
