### ISSUE TITLE
one function in tensorflow tutorials should be replaced

### ISSUE THREAD

**Issue by BoyuanJiang** [tensorflow/tensorflow#5664]
I'm learning tutorials of tf.contrib.learn Quickstart in this [website](https://www.tensorflow.org/versions/r0.11/tutorials/tflearn/index.html) and found that the function **tf.contrib.learn.datasets.base.load_csv**  isn't existed.So the following codes
`training_set = tf.contrib.learn.datasets.base.load_csv(filename=IRIS_TRAINING,
                                                       target_dtype=np.int)`
`test_set = tf.contrib.learn.datasets.base.load_csv(filename=IRIS_TEST,
                                                   target_dtype=np.int)`
 should be replaced by
`training_set = tf.contrib.learn.datasets.base.load_csv_with_header(filename=IRIS_TRAINING,
                                                       target_dtype=np.int,features_dtype=np.float32)`
`test_set = tf.contrib.learn.datasets.base.load_csv_with_header(filename=IRIS_TEST,
                                                   target_dtype=np.int,features_dtype=np.float32)
`

and my tensorflow version is  (0.11.0rc1)

**Comment by girving** [comment]
@BoyuanJiang Can you try with 0.11?  0.11.0rc1 has 2d4267507e312007a062a90df37997bca8019cfb.

**Comment by BoyuanJiang** [comment]
yeah,I know that def load_csv has been replaced by def load_csv_with_header.I mean that the tutorials of this [website](https://www.tensorflow.org/versions/r0.11/tutorials/tflearn/index.html)should be update,because in the tutorials still use the function load_csv and may confuse the beginners.

(It's my first time use github and not sure where should I issue the problem 0_0

**Comment by girving** [comment]
@BoyuanJiang It looks like the tutorials have also been updated (if you look at the master tutorials), so I think we're good.
