### ISSUE TITLE
Cannot use LSTM with a photo input

### ISSUE THREAD

**Issue by fswalden** [tensorflow/tensorflow#56640]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Windows 10

### Python version

3.9

### Current Behaviour?

```shell
I need to classify MFCC Spectrogram images from collected sound data using an RNN with an LSTM. The input shape of my image casted to a numpy array is (288, 864, 4). The LSTM Model cannot accept a three dimensional input, apparently. What is the solution to this? How can one classify images using an LSTM? I don't know of a great way to convert the 3-D numpy array of an image to a format that works. However, if someone knows a format that is compatible with LSTMs, that would answer my question, along with any way to have a 3-D input shape.
```

### Standalone code to reproduce the issue

```shell
model.add(LSTM(128,input_shape=(288, 864, 4)))
```

### Relevant log output

```shell
ValueError: Input 0 of layer "lstm_1" is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: (None, 288, 864, 4)
```
</details>

**Comment by sunsetcoder** [comment]
Your input needs to be reshaped.

input_shape: A 3D tensor with shape [batch, timesteps, features]

**Comment by sushreebarsa** [comment]
@fswalden Could you refer to the above [comment](https://github.com/tensorflow/tensorflow/issues/56640#issuecomment-1172932851) and this [thread](https://stackoverflow.com/questions/43487828/understanding-input-shape-parameter-in-lstm-with-keras) to know more on the input shape?
Please let us know if it helps.
Thank you!

**Comment by fswalden** [comment]
I understand how the input shape works now. Does anyone have any tips on how they've converted photo inputs to a format compatible with an LSTM?

**Comment by sushreebarsa** [comment]
@fswalden I was able to replicate this issue on colab, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/59fd1a121bfeee76e53173bc53ea579f/git_56640.ipynb).
Could you please refer [this](https://stackoverflow.com/questions/47671732/keras-input-a-3-channel-image-into-lstm) thread to know more on how to convert photo inputs to a format compatible with an LSTM.
`For any further queries` please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
