### ISSUE TITLE
Is there a bug in embedding_attention_seq2seq?

### ISSUE THREAD

**Issue by Syndrome777** [tensorflow/tensorflow#5665]
Hi, all,

I think the code of embedding_attention_seq2seq is confusing. And I can't run this code.

```python
if output_projection is None:
      cell = rnn_cell.OutputProjectionWrapper(cell, num_decoder_symbols)
      output_size = num_decoder_symbols

...

      x = linear([inp] + attns, input_size, True)
      # Run the RNN.
      cell_output, state = cell(x, state)

...

with variable_scope.variable_scope("AttnOutputProjection"):
        output = linear([cell_output] + attns, output_size, True)

```

I don't know what's the meaning of "AttnOutputProjection". The attention information has been used in "x = linear([inp] + attns, input_size, True)", why adding it again?

And meanwhile what is the meaning of "[cell_output] + attns", "cell_output" is equal with num_symbols, so why add attens?

In my experiment, the num_decoder_symbols is 10000 and the hidden size is 32, and I get a matrix 10032*10000 at "AttnOutputProjection". It will be out of memory.
10032 is a confusing number, I don't know the physical meaning of this number.

So I don't know if it's a bug. If it's a bug, I'm really pleasure to make a PR.
Thanks so much.

**Comment by lircal** [comment]
发自网易邮箱大师






On 11/17/2016 22:20， Issac<notifications@github.com>wrote：

Hi, all,

I think the code of embedding_attention_seq2seq is confusing. And I can't run this code.

if output_projection isNone:
      cell = rnn_cell.OutputProjectionWrapper(cell, num_decoder_symbols)
      output_size = num_decoder_symbols

...

      x = linear([inp] + attns, input_size, True)
      # Run the RNN.
      cell_output, state = cell(x, state)

...with variable_scope.variable_scope("AttnOutputProjection"):
        output = linear([cell_output] + attns, output_size, True)


I don't know what's the meaning of "AttnOutputProjection". The attention information has been used in "x = linear([inp] + attns, input_size, True)", why adding it again?

And meanwhile what is the meaning of "[cell_output] + attns", "cell_output" is equal with num_symbols, so why add attens?

In my experiment, the num_decoder_symbols is 10000 and the hidden size is 32, and I get a matrix 10032*10000 at "AttnOutputProjection". It will be out of memory.
What is the meaning of 10032?

So I don't know if it's a bug. If it's a bug, I'm really pleasure to make a PR.
Thanks so much.

**Comment by girving** [comment]
This question is better suited to StackOverflow, since it is a combination of asking how a model works and trying to run too large of a network.  Github issues are for bug reports and feature requests.

**Comment by htt210** [comment]
Hi girving,
I think this is a bug in the code and you did not understand Syndrone777's question correctly. The code here does not implement any attention mechanism I know. 

`      cell_output, state = cell(x, state) # cell_output has the size of batch_size x num_symbols while the correct shape is batch_size x hidden_size 

with variable_scope.variable_scope("AttnOutputProjection"):
        output = linear([cell_output] + attns, output_size, True) # so the linear op here has the weight matrix of (num_symbols + attn_vec_size) x num_symbols. The correct size shoulde be (hidden_size + attn_vec_size) x num_symbols
`

The output of the cell() must be the hidden state, not the projection to the vocabulary. I think this bug was created because the attention model code was derived from the normal seq2seq code in which the output of the decoder is projected directly to the vocabulary space.

I quick fixed it by removing the OutputProjectWrapper in embedding_attention_seq2seq method.
`output_size = None
    if output_projection is None:
      cell = rnn_cell.OutputProjectionWrapper(cell, num_decoder_symbols)
      output_size = num_decoder_symbols
`
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/seq2seq.py#L827

**Comment by girving** [comment]
@lukaszkaiser Can you comment?

**Comment by lukaszkaiser** [comment]
Indeed, there is a bug there, see #4938 for details (and how to work around it). We've decided not to correct it as the whole static seq2seq is going away anyway.

**Comment by lukaszkaiser** [comment]
As for the new version, see #4686 -- it's coming along (no attention at first, but we'll get there).
