### ISSUE TITLE
`tf.scatter_nd` op is placed on the CPU when values are of boolean type

### ISSUE THREAD

**Issue by kvignesh1420** [tensorflow/tensorflow#56655]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

binary

### Tensorflow Version

2.8.2

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.5

### Python version

3.7.13

### CUDA/cuDNN version

NVIDISMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2

### Current Behaviour?

```shell
The `tf.scatter_nd` op is being placed on the CPU when the values are of type bool. However, the op is placed on the GPU for int type.
```

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1R41Ta-j8Qh2hLE-l5BBZsmBlg1CxtjcU?usp=sharing
```

### Relevant log output

```shell
indices = tf.constant([[4], [3], [1], [7]])
updates = tf.constant([True, True, False, False])
shape = tf.constant([8])
scatter = tf.scatter_nd(indices, updates, shape)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ScatterNd in device /job:localhost/replica:0/task:0/device:CPU:0

indices = tf.constant([[4], [3], [1], [7]])
updates = tf.constant([9, 10, 11, 12])
shape = tf.constant([8])
scatter = tf.scatter_nd(indices, updates, shape)

Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op ScatterNd in device /job:localhost/replica:0/task:0/device:GPU:0
```
</details>

**Comment by tilakrayal** [comment]
@gadagashwini,
I was able to reproduce the issue on tensorflow [v2.8](https://colab.research.google.com/gist/tilakrayal/83b8ad731105c223783c022984f56856/untitled414.ipynb), [v2.9](https://colab.research.google.com/gist/tilakrayal/3227d24ff6555ccd6c29b0ea886be499/untitled409.ipynb) and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/0441eafbdaf864767cd7819871cd8738/untitled411.ipynb).

**Comment by gadagashwini** [comment]
Hi @kvignesh1420, 
`tf.scatter_nd` takes `updates` argument .

updates | A Tensor. Values to scatter into the output tensor.
-- | --

Thank you!

**Comment by kvignesh1420** [comment]
@sachinprasadhs I found the reason for the CPU op placement of bool types. It is due to the following code block where bool types are only registered for CPU device placement of the `ScatterNdOp`

https://github.com/tensorflow/tensorflow/blob/769eddaf479c8debead9a59a72617d6ed6f0fe10/tensorflow/core/kernels/scatter_nd_op.cc#L500-L502

However, all the number types are registered with GPU as well:

https://github.com/tensorflow/tensorflow/blob/769eddaf479c8debead9a59a72617d6ed6f0fe10/tensorflow/core/kernels/scatter_nd_op.cc#L667-L671

What you have mentioned is regarding the creation of the Tensor which I think is already being executed on the GPU.

**Comment by kvignesh1420** [comment]
It would be great if we could find out if `TF_CALL_bool(REGISTER_SCATTER_ND_GPU);` is viable or not 🙂 . Thanks!

**Comment by kvignesh1420** [comment]
@sachinprasadhs any update on this?

**Comment by wangpengmit** [comment]
CCing @seefortwo .

**Comment by cantonios** [comment]
@kvignesh1420 you can create a PR to register it if you like and if it is necessary for your application.  We generally only register ops as they are needed, since doing so increases the TensorFlow binary size pip for everyone, and we are subject to some binary size limits.
