### ISSUE TITLE
Grappler Errors with ConvLSTM2D

### ISSUE THREAD

**Issue by acfrock** [tensorflow/tensorflow#56652]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution**: Windows 11 Build 22000
-   **TensorFlow installed from**: pip package
-   **TensorFlow version**: v2.9.0-18-gd8ce9f9c301 2.9.1
-   **Python version**: Python 3.10.4
-   **CUDA/cuDNN version**: CUDA 11.7.0-1
-   **GPU model and memory**: Nvidia 2080 Ti 11GiB Memory
-   **Exact command to reproduce**: `python conv_lstm.py` with [conv_lstm.py](https://github.com/keras-team/keras-io/blob/master/examples/vision/conv_lstm.py) from the official Keras examples

### Describe the problem
Using the ConvLSTM2D layer produces a grappler error: `layout failed: INVALID_ARGUMENT: MutableGraphView::SortTopologically error: detected edge(s) creating cycle(s) ...` when run with a GPU. Interestingly, this does not happen if TensorFlow is forced to run without a GPU.

It is not clear whether this is a problem with grappler, with the implementation of the ConvLSTM2D layer, or a bug in CUDA.

### Source code / logs
I used the example script from the Keras documentation. [[Keras example page](https://keras.io/examples/vision/conv_lstm/)] [[script](https://github.com/keras-team/keras-io/blob/master/examples/vision/conv_lstm.py)]. The logs are here: [output.txt](https://github.com/tensorflow/tensorflow/files/9031236/output.txt).

**Comment by sushreebarsa** [comment]
@acfrock 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by acfrock** [comment]
This is now being tracked in the keras-team/keras repository: [Issue #16754](https://github.com/keras-team/keras/issues/16754)

**Comment by sushreebarsa** [comment]
@acfrock Thank you for the update!
