### ISSUE TITLE
about  this error when i try to run the existing wide_n_deep_tutorial.py

### ISSUE THREAD

**Issue by yidan216home** [tensorflow/tensorflow#5666]
Hello,
I get this error when i try to run the existing wide_n_deep_tutorial.py, any ideas on this?

(tensorflow) xx@ubuntu:~$ python wide_n_deep_tutorial.py --model_type=wide_n_deep

Traceback (most recent call last):
  File "wide_n_deep_tutorial.py", line 208, in <module>
    tf.app.run()
  File "/xxxxxxx/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "wide_n_deep_tutorial.py", line 204, in main
    train_and_eval()
  File "wide_n_deep_tutorial.py", line 196, in train_and_eval
    m = build_estimator(model_dir)
  File "wide_n_deep_tutorial.py", line 80, in build_estimator
    gender = tf.contrib.layers.sparse_column_with_hash_bucket(
AttributeError: 'module' object has no attribute 'sparse_column_with_hash_bucket'

I have no problems with TF installation, and my tensorflow version is 0.9 ,python 2.7  .Last week,the text_cnn.py  examples run just fine.
Thanks!﻿

**Comment by girving** [comment]
@yidan216home TensorFlow 0.9 is very old, and probably doesn't have that function.  Is your copy of the `wide_n_deep_tutorial.py` also from 0.9?

**Comment by yidan216home** [comment]
@girving Thanks! Works like charm!
The latest version is  tensorflow 0.11, but  fisrt   i used  0.7,then update to  0.8  and 0.9  according to the old operation on the Internet,the error  was still not solved.
 Now  i update to 0.11, it works.
