### ISSUE TITLE
Can't pickle optimizer

### ISSUE THREAD

**Issue by 7NoteDancing** [tensorflow/tensorflow#56666]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

source

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Windows 11

### Python version

3.7

### Current Behaviour?

```shell
AttributeError: Can't pickle local object 'make_gradient_clipnorm_fn.<locals>.<lambda>'
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import pickle
output_file=open('save.dat','wb')
pickle.dump(tf.keras.optimizers.Adam(),output_file)
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@7NoteDancing 
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by 7NoteDancing** [comment]
> @7NoteDancing Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) To know more see; https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999 Thank you!

ok

**Comment by sushreebarsa** [comment]
@7NoteDancing Could you please confirm if you have posted this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)?
Thank you!

**Comment by 7NoteDancing** [comment]
> @7NoteDancing Could you please confirm if you have posted this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues)? Thank you!

Yes,I have posted.

**Comment by NoteDancing** [comment]
ok,thank
________________________________
发件人: sushreebarsa ***@***.***>
发送时间: 2022年7月4日 12:23
收件人: tensorflow/tensorflow ***@***.***>
抄送: 7NoteDancing ***@***.***>; Mention ***@***.***>
主题: Re: [tensorflow/tensorflow] Can't pickle optimizer (Issue #56666)


@7NoteDancing<https://github.com/7NoteDancing>
Please post this issue on keras-team/keras repo.<https://github.com/keras-team/keras/issues>
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

―
