### ISSUE TITLE
_self_tracked_trackables in base_layer.py should not record it self

### ISSUE THREAD

**Issue by Li-Jiajie** [tensorflow/tensorflow#56669]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.5.1

### Custom Code

No

### OS Platform and Distribution

linux

### Python version

3.6.5

### Current Behaviour?

My class inherited "tf.keras.Model"，because of some history reason (compatible history code), there is a class variable assigned as "self". like:

class Model(tf.keras.Model):
  def __init__(self, name):
    super().__init__()
    self.model = self  # here
    xxxxxxx

but it will occur infinite loop while some function use 'trainable_variables'

the source is in trainning.py/trainable_weights:
    for trackable_obj in self._self_tracked_trackables:
      trainable_variables += trackable_obj.trainable_variables
if self is in _self_tracked_trackables, here will infinite loop
_self_tracked_trackables was constructed in base_layer, maybe the _self_tracked_trackables  should filter it self?

### Standalone code to reproduce the issue

```shell
class Model(tf.keras.Model):
   def __init__(self, name: str = None):
        super().__init__()
        self.dnn_model = self
        print('here', self.trainable_variables)  # here

test = Model("test")
```

### Relevant log output

```shell
File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 2021, in trainable_weights
    trainable_variables += trackable_obj.trainable_variables
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/training/tracking/data_structures.py", line 816, in __getattribute__
    return object.__getattribute__(self, name)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/training/tracking/data_structures.py", line 285, in trainable_variables
    return self.trainable_weights
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/training/tracking/data_structures.py", line 816, in __getattribute__
    return object.__getattribute__(self, name)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/training/tracking/data_structures.py", line 242, in trainable_weights
    for obj in self._values:
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/training/tracking/data_structures.py", line 816, in __getattribute__
    return object.__getattribute__(self, name)
  File "/usr/local/lib64/python3.6/site-packages/tensorflow/python/training/tracking/data_structures.py", line 841, in _values
    ordered = list(zip(*sorted(self.items(), key=lambda it: it[0])))
RecursionError: maximum recursion depth exceeded while calling a Python object
```
</details>

**Comment by sushreebarsa** [comment]
@Li-Jiajie 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!

**Comment by Li-Jiajie** [comment]
> @Li-Jiajie In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!

run this code:
`
import tensorflow as tf

class Model(tf.keras.Model):
   def __init__(self, name: str = None):
        super().__init__()
        self.dnn_model = self
        print('here', self.trainable_variables)  # here

test = Model("test")`

**Comment by Li-Jiajie** [comment]
> @Li-Jiajie In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!

import tensorflow as tf


class TestModel(tf.keras.Model):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.dnn_model = self
        print('here', self.trainable_variables)  # here


test = TestModel("test")

**Comment by sushreebarsa** [comment]
@Li-Jiajie I tried to replicate the issue on colab and didn’t face the issue reported. Could you please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/a9869f3f87a4a83f0659bb96f791c59c/56669.ipynb) and confirm the same?
Thank you!

**Comment by Li-Jiajie** [comment]
> @Li-Jiajie I tried to replicate the issue on colab using latest TF version and didn’t face the issue reported. Could you please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/a9869f3f87a4a83f0659bb96f791c59c/56669.ipynb) and confirm the same? Thank you!

https://colab.research.google.com/gist/Li-Jiajie/ff5a01f73b95c5f2da1a525540723341/56669.ipynb

**Comment by sushreebarsa** [comment]
@Li-Jiajie I was able to replicate the issue on colab [here](https://colab.research.google.com/gist/sushreebarsa/7b8aeb4726ebaa732956b0c998c31f58/56669-gist.ipynb).
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
