### ISSUE TITLE
TFLiteConverter.experimental_from_jax on a working jax model: "flax.errors.JaxTransformError: Jax transforms and Flax models cannot be mixed."

### ISSUE THREAD

**Issue by josephrocca** [tensorflow/tensorflow#56660]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04 (Google Colab)
- TensorFlow installation (pip package or built from source): Colab's version (Pip?)
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.8.0

### 2. Code

The example linked below demonstrates that a working JAX model (which converts and saves successfully with `tf.saved_model.save` throws the error "flax.errors.JaxTransformError: Jax transforms and Flax models cannot be mixed." when trying to convert it to TFLite using `TFLiteConverter.experimental_from_jax`.

https://colab.research.google.com/gist/josephrocca/b9b7b4e92cb693772cb937302b4946d9/jax-flax-transformations-cannot-be-mixed.ipynb

The `experimental_from_jax` function is of course experimental, and I understand that the jax2tf --> tf saved model --> tflite is the current recommended route, but just reporting this in case it is not expected behavior.

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! 
Could you please at this issue. Attached gist in[ 2.8](https://colab.sandbox.google.com/gist/mohantym/57e9d0dae93515c78383574ca4adfa26/jax-flax-transformations-cannot-be-mixed.ipynb#scrollTo=yfH6UYUTtcQh), [2.9](https://colab.sandbox.google.com/gist/mohantym/f669857379566292bdd7d6f23d78a6f4/jax-flax-transformations-cannot-be-mixed.ipynb#scrollTo=yfH6UYUTtcQh) and [nightly](https://colab.sandbox.google.com/gist/mohantym/fc8ff3b5e7287d4a1eb43f0f6d2b1361/jax-flax-transformations-cannot-be-mixed.ipynb#scrollTo=MVLK3QdhXT1L) for reference.
Thank you!

**Comment by PINTO0309** [comment]
I am not sure if this is a meaningful conversion since **`seed`** is not present in the INPUT OP of saved_model.

>Could you please at this issue. Attached gist in[ 2.8](https://colab.sandbox.google.com/gist/mohantym/57e9d0dae93515c78383574ca4adfa26/jax-flax-transformations-cannot-be-mixed.ipynb#scrollTo=yfH6UYUTtcQh), [2.9](https://colab.sandbox.google.com/gist/mohantym/f669857379566292bdd7d6f23d78a6f4/jax-flax-transformations-cannot-be-mixed.ipynb#scrollTo=yfH6UYUTtcQh) and [nightly](https://colab.sandbox.google.com/gist/mohantym/fc8ff3b5e7287d4a1eb43f0f6d2b1361/jax-flax-transformations-cannot-be-mixed.ipynb#scrollTo=MVLK3QdhXT1L) (2.10.0dev) for reference.

https://colab.sandbox.google.com/gist/mohantym/fc8ff3b5e7287d4a1eb43f0f6d2b1361/jax-flax-transformations-cannot-be-mixed.ipynb#scrollTo=MVLK3QdhXT1L
```bash
$ saved_model_cli show --dir . --all

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['text_tokens'] tensor_info:
        dtype: DT_INT32
        shape: (2, 64)
        name: serving_default_text_tokens:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output_0'] tensor_info:
        dtype: DT_FLOAT
        shape: (2, 64, 1024)
        name: PartitionedCall:0
  Method name is: tensorflow/serving/predict
WARNING:absl:Importing a function (__inference_converted_fun_1862) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.

Concrete Functions:
  Function Name: 'f'
    Option #1
      Callable with:
        Argument #1
          text_tokens: TensorSpec(shape=(2, 64), dtype=tf.int32, name='text_tokens')
```
```bash
$ docker run -it --rm \
-v `pwd`:/home/user/workdir \
ghcr.io/pinto0309/openvino2tensorflow:latest

saved_model_to_tflite \
--saved_model_dir_path . \
--output_no_quant_float32_tflite

Start conversion process from saved_model to tflite ======================================
WARNING:absl:Importing a function (__inference_converted_fun_1862) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.
tflite Float32 convertion started ===================================================
WARNING:absl:Please consider providing the trackable_obj argument in the from_concrete_functions. Providing without the trackable_obj argument is deprecated and it will use the deprecated conversion path.
Estimated count of arithmetic ops: 3.269 G  ops, equivalently 1.635 G  MACs
tflite Float32 convertion complete! - tflite_from_saved_model/model_float32.tflite
All the conversion process is finished! =============================================
```
![image](https://user-images.githubusercontent.com/33194443/177594116-e177a6f8-5491-44e0-b609-cf5f851a3f40.png)

![model_float32 tflite](https://user-images.githubusercontent.com/33194443/177593937-936cfb99-d7ff-44a0-bcf5-a9551e5eac92.png)

**Comment by josephrocca** [comment]
@PINTO0309 I think I might have confused you in the email I sent you - this Github issue is actually just about the encoder side of the model, and doesn't take a `seed` input. I isolated the encoder because I found it to be the source of this particular "Jax transforms and Flax models cannot be mixed" error, and I wanted to try to produce a minimal reproducible example of the error. It is my mistake for not explaining this in the email - sorry!

Hey @sachinprasadhs, this issue is about `tf.lite.TFLiteConverter.experimental_from_jax`, so I do not call `tf.saved_model.save` in the process. Per my original post, please see this notebook for the code that replicates the issue: https://colab.research.google.com/gist/josephrocca/b9b7b4e92cb693772cb937302b4946d9/jax-flax-transformations-cannot-be-mixed.ipynb Thanks!

**Comment by pjpratik** [comment]
I was able to replicate this on  TF 2.11. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/e940d20b4d7219b13ff95ad3f8417b99/56660.ipynb). Thank you.

**Comment by sachinprasadhs** [comment]
This looks like a issue from the model by seeing the error log here
https://flax.readthedocs.io/en/latest/api_reference/flax.errors.html#flax.errors.JaxTransformError which states
`exception flax.errors.JaxTransformError.`
```
JAX transforms and Flax modules cannot be mixed.

JAX’s functional transformations expect pure function. When you want to use JAX transformations inside Flax models, you should make use of the Flax transformation wrappers (e.g.: flax.linen.vmap, flax.linen.scan, etc.).
```
Could you please check if the issue is from the model side. Thanks!
