### ISSUE TITLE
The Height and Width must be changed in tensorflow document on the website 

### ISSUE THREAD

**Issue by tekboart** [tensorflow/tensorflow#56662]
Hi,
In the TF documentation there is a mistake, the order of "Height" and "Width" is wrong, it's (Batch, Width, Height, features) but must be (Batch, Height, Width, features) to comply with channel_last notation (NHWC)

![image](https://user-images.githubusercontent.com/83506388/177032598-e8b01440-5c79-47b2-808d-5cb8df9ad68a.png)
https://www.tensorflow.org/guide/tensor#:~:text=regions%20of%20memory.-,Typical%20axis%20order,-Indexing

**Comment by 8bitmp3** [comment]
> ... feel free to submit a PR for the requested change to be made. Thank you!

https://github.com/tensorflow/docs/pull/2097

**Comment by tilakrayal** [comment]
@tekboart,
The pr has been assigned for reviewing and once it is merged this issue will move to closed status. Thank you!

**Comment by tilakrayal** [comment]
@tekboart,
Respective [PR](https://github.com/tensorflow/docs/pull/2097) was merged. Could you please take a look and please feel free to close this issue. Thank you!
