### ISSUE TITLE
tflite_convert error

### ISSUE THREAD

**Issue by njuhang** [tensorflow/tensorflow#56665]
### 1. System information

- Ubuntu 20.04
- TensorFlow  built from source
- TensorFlow version 2.9):

### 2. Code

bazel run //tensorflow/lite/python:tflite_convert --

### 3. Failure after conversion
ERROR: /home/tensorflow/BUILD:1355:19: Executing genrule //tensorflow:tf_python_api_gen_v2 failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)

ERROR: /home/tensorflow/lite/python/BUILD:68:10 Middleman _middlemen/tensorflow_Slite_Spython_Stflite_Uconvert-runfiles failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument skipped)
INFO: Elapsed time: 2.901s, Critical Path: 0.95s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by mohantym** [comment]
Hi @njuhang !
Could you update the above template with Bazel, Tensorflow ,System details and GCC version too. I was able to run above code in 2.9 version with Bazel 5.0.0 . Attached [gist](https://colab.sandbox.google.com/gist/mohantym/ca9cf22bfd1e0f821f6abbb66819bf0e/tensorflow-ranking.ipynb#scrollTo=tRpGdZ4PsAwp) for reference. 
Thank you!

**Comment by njuhang** [comment]
sorry, tensorflow version is RELEASE 2.10.0, bazel 5.1.1, gcc 9.4.0

**Comment by njuhang** [comment]
I tried bazel5.0.0, but encounter some other errors

**Comment by mohantym** [comment]
Ok @njuhang ! 
Thanks for the update. The build was still passing with Bazel 5.1.1 and TF 2.10.0 with GCC 7.3.1 (default GCC version of colab).  But last line of error stack trace is similar to this [issue](https://github.com/tensorflow/tensorflow/issues/55829#:~:text=ERROR%3A%20/root/tensorflow/tensorflow/lite/python/BUILD%3A68%3A10%20Middleman%20_middlemen/tensorflow_Slite_Spython_Stflite_Uconvert%2Drunfiles%20failed%3A%20(Exit%201)%3A%20bash%20failed%3A%20error%20executing%20command%20/bin/bash%20%2Dc%20...%20(remaining%201%20argument%20skipped)). 

Could you confirm that you are using Python 3.7 or higher.
Thank you!

**Comment by njuhang** [comment]
I use ./configure to change python version from 3.6 to 3.8 now, but it doesn't work.

**Comment by mohantym** [comment]
@njuhang ! 
Could you confirm that you tried in fresh environment with Python 3.8 and the Environment path for Python files has been to updated before running the configure.py file.
Thank you!

**Comment by njuhang** [comment]
I could build example, such as  bazel build tensorflow/examples/label_image/, do these two build share same environment?

**Comment by mohantym** [comment]
@njuhang !
Yeah, Please test the above build in same environment once and let us know. Thank you!

**Comment by njuhang** [comment]
I could pass example building. 
I check python:tflite_convert  build info, it says  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env "PYTHON_LIB_PATH=/usr/local/lib/python3.8/dist-packages --python_path=/usr/bin/python3".
But still failed.

**Comment by njuhang** [comment]
Maybe I missed a package named packaging, then I use pip to install it, then I finished building.

**Comment by mohantym** [comment]
Ok @njuhang ! Thanks for the update. Glad you were able to find the issue.

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
