### ISSUE TITLE
Differing Tensorflow versions when checking

### ISSUE THREAD

**Issue by d287zhan** [tensorflow/tensorflow#56679]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Windows 10

### Python version

3.8.7

### Current Behaviour?

```shell
I recently installed the latest version of Tensorflow (2.9.1) and when I went to check the version in my local Jupyter Notebook, it constantly said 2.4.0. I expected to see 2.9.1, so I don't understand why it is showing 2.4.0. I tried uninstalling and reinstalling Tensorflow, but still got the same issue.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
tf.version.VERSION
!pip show tensorflow
```

### Relevant log output

```shell
C:\Users\danie>pip show tensorflow
Name: tensorflow
Version: 2.9.1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\users\danie\appdata\local\programs\python\python38\lib\site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google-pasta, grpcio, h5py, keras, keras-preprocessing, libclang, numpy, opt-einsum, packaging, protobuf, setuptools, six, tensorboard, tensorflow-estimator, tensorflow-io-gcs-filesystem, termcolor, typing-extensions, wrapt
Required-by: autokeras, scikeras, tensorflow-federated

C:\Users\danie>python -c "import tensorflow as tf; print(tf.__version__)"
2.4.0

C:\Users\danie>python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
v2.4.0-0-gbe3d1f7dcd5 2.4.0
```
</details>

**Comment by mohantym** [comment]
Hi @d287zhan ! 
Could you update the System type too in the template. 
Thank you!

**Comment by bhack** [comment]
Can you test again creating a conda environment as in the official Doc:
https://www.tensorflow.org/install/pip

**Comment by d287zhan** [comment]
Hi @mohantym, by the system type do you mean OS? Which I updated to be Windows 10.

**Comment by d287zhan** [comment]
Hi @bhack, I can try again, but I download all these packages locally using pip, through my terminal. Is there a way to uninstall a certain version of TensorFlow? Could it be related to my local python version?

**Comment by gadagashwini** [comment]
Hi @d287zhan, May be its due to multiple Python version. To install specific Tensorflow version on Jupyter notebook, you launch Jupyter notebook and install tensorflow on Jupyter notebook cell `!pip install tensorflow==2.9.1`.Or you create virtual environment using pip and install specific version of Tensorflow. Thanks you!

**Comment by bhack** [comment]
Please be sure to try this in the conda env as described in the official Doc so we are sure that you are in an isolated fresh environment.

**Comment by gadagashwini** [comment]
Hi @d287zhan, Anaconda has default Tensorflow 2.4 version. Thank you!

**Comment by bhack** [comment]
@mihaimaruseac Now we have conda instead of venv in the official doc to test a clean and reproducible env install.

The multi-python hipotesys has still an high probabilty bere

**Comment by bhack** [comment]
Not anymore (I meant to be sure you have a fresh env).

https://www.tensorflow.org/install/pip

For CPU It is only suggested to skip step 3 (Linux) and 4 (win).

**Comment by mihaimaruseac** [comment]
```
conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/
python3 -m pip install tensorflow
# Verify install:
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
```

Please see how the first line, the conda line, is just for conda whereas the line that install TF (the third one) is `pip`.

**Comment by bhack** [comment]
Yes but I am on the [step-by-step section](https://www.tensorflow.org/install/pip?hl=en#step-by-step_instructions)  of the same page (that was historically the `venv` clean env setup)

> We recommend using Miniconda to create a separate environment to avoid changing any installed software in your system. This is also the easiest way to install the required software, especially for the GPU setup.

Please note "this also" and it Is why we suggest optional GPU only steps.

So for me this is now the official guide to have a "reproducible fresh env" other then with our Docker guide.

**Comment by mihaimaruseac** [comment]
![8EvuzguGH9SR6J6](https://user-images.githubusercontent.com/323199/177838882-1fbcb159-e3bc-4d82-b02f-7abc48eb58fb.png)

**Comment by mihaimaruseac** [comment]
Yes, but this discussion confused @gadagashwini into thinking OP wanted to install via Conda, when Conda is just an orthogonal issue here.

To debug this further, we need the output of the two commands mentioned in https://github.com/tensorflow/tensorflow/issues/56679#issuecomment-1177881334:

```
pip show tensorflow
python -m pip show tensorflow
```

**Comment by gadagashwini** [comment]
Install Tensorflow on specific version of Python

```
conda create --name tf python=3.9
conda activate tf
pip install --upgrade pip
pip install tensorflow
```
