### ISSUE TITLE
can't reduce binary size(tflite)

### ISSUE THREAD

**Issue by JinXiaozhao** [tensorflow/tensorflow#56670]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tensorflow-2.8.2

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.6

### Bazel version

4.2.1

### Current Behaviour?

```shell
I reduce the binary size of my model using selective builds https://www.tensorflow.org/lite/guide/reduce_binary_size.
 It can't reduce the binary size.
folder structure:
tmp/
|-- BUILD
`-- model.tflite
BUILD:
load(
    "@org_tensorflow//tensorflow/lite/delegates/flex:build_def.bzl",
    "tflite_flex_shared_library"
)

# Shared lib target for convenience, pulls in the standard set of TensorFlow
# ops and kernels. The output library name is platform dependent:
#   - Linux/Android: `libtensorflowlite_flex.so`
#   - Mac: `libtensorflowlite_flex.dylib`
#   - Windows: `libtensorflowlite_flex.dll`
tflite_flex_shared_library(
  name = "tensorflowlite_flex",
  models = [
      ":model.tflite",
  ],
)
compile command: bazel build -c opt --config=monolithic //tmp:tensorflowlite_flex
bazel-bin/tmp/libtensorflowlite_flex.so 183M
```

### Standalone code to reproduce the issue

```shell
model.tflite: lstm
ops:builtin_ops+tf_select_ops
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @JinXiaozhao !

Python 3.7 is minimum version. Correct procedure to reduce the file size is to use two lite models built with (different specs like select ops/custom-ops etc) in sh command or declare the path to two lite model in bazel custom rules. 

You can specify a compiler flag like (x86,x86_64,arm64-v8a,armeabi-v7a  etc) in sh command to build it for specific platform.

Attached relevant [document](https://www.tensorflow.org/lite/guide/reduce_binary_size) for reference. 

Thank you!

**Comment by mohantym** [comment]
Hi @JinXiaozhao ! 
That is a not a lite file which you are generating through Bazel (lite file extension is .lite). Those files are flex delegate files will be useful while running lite models with GPU support through[ load_delegates](https://www.tensorflow.org/api_docs/python/tf/lite/experimental/load_delegate) command in Desktops .

 To get a lite file , you need to convert the original saved_model/Jax_model/Keras model to lite file using [TFlite converter](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter#convert). You can use then two different lite files( built with different quantization) in sh command to get aar files (much smaller in size) . You can use them in gradle file of your android project later.

Thank you!
