### ISSUE TITLE
disable_resource_variables is deprecated

### ISSUE THREAD

**Issue by maidang-ee** [tensorflow/tensorflow#56689]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.6.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 16.04

### Python version

3.8.10

### Current Behaviour?

```shell
A bug happened!
I was running my code normally but then all of sudden I received a warning that disturbing my code from compiling and my program completely stop T.T
My source code was written in tf v1 and I've been running it on tf v2 so apparently I need 'tf.disable_resource_variables()' for my programme to work.
```

### Standalone code to reproduce the issue

```shell
I received this WARNING. 
"WARNING:tensorflow:From /home/mdee/.local/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:101: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term"
This is exactly what I received and I read from the tensorflow.org website that if my code needs tf.disable_resource_variables() to be called to work properly, I should file a bug.
Please let me know how can I run my code smoothly again.
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @maidang-ee !
Could you share a minimal stand alone code to replicate the issue.
Thank you!

**Comment by maidang-ee** [comment]
Hi @mohantym!
Thank you for getting back to me.
Absolutely, I will attach some parts of the code. 
I'm not sure if they are useful but please let me know if you need anything more. 
I really appreciate it. 
Since my research is at the critical time so I really need the code to work again ASAP!!!

![image](https://user-images.githubusercontent.com/58720073/177667861-64316f7c-52a7-4dcf-b6fd-6fcf1b2e4ca4.png)
< I used this command to make the script written in tf v1 to run on tf v2>

![image](https://user-images.githubusercontent.com/58720073/177667936-50633624-3ee6-4921-b75f-ce51cb022dc4.png)

![image](https://user-images.githubusercontent.com/58720073/177668015-55a2d922-764e-49fb-8396-604693f2ae78.png)
<This part line 101 is what the warning is about>

Thank you again and I'm looking forward to hearing from you soon.

**Comment by maidang-ee** [comment]
Hi @mohantym,

Just a quick update. 
I got my program to work again. 
Thank you for spending time on looking at my issue. 
You have a good day!

**Comment by mohantym** [comment]
Ok @maidang-ee !
Closing this issue it seems to be resolved from above[ comment](https://github.com/tensorflow/tensorflow/issues/56689#issuecomment-1176943267).
