### ISSUE TITLE
MBv3 conversion: How to turn off hard swish optimization

### ISSUE THREAD

**Issue by mrtpk123** [tensorflow/tensorflow#56686]
### 1. System information

- Windows 11
- pip 
- version 2.8.0

### 2. Code
```
import numpy as np
import tensorflow as tf
import pathlib
from tensorflow.keras import Model, Input

model = tf.keras.applications.MobileNetV3Small()
model.summary()

dataset = np.random.rand(10, 224, 224, 3).astype(np.float32)
def representative_data_gen():
    for input_value in tf.data.Dataset.from_tensor_slices(dataset).batch(1).take(len(dataset)):
        # Model has only one input so each data point has one element.
        yield [input_value]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
tflite_model = converter.convert()

tflite_models_dir = pathlib.Path("./tflite_models/hard_swish/")
tflite_models_dir.mkdir(exist_ok=True, parents=True)

# Save the quantized model:
tflite_model_quant_file = tflite_models_dir/"mbv3.tflite"
tflite_model_quant_file.write_bytes(tflite_model)

```
### 3. Failure after conversion
The model is correctly converted. The hard swish layers (multiple layers- ADD, MUL, RELU6 in TF) are combined into one layer- `hard swish` in TFlite.

![image](https://user-images.githubusercontent.com/76564442/177485487-ed7ffa24-b784-4ba7-bc69-79297b05f93a.png)

I understand that this is by design.

#### Question:
I have a use case where I need to turn off this conversion. That is, when the model is converted to tflite, the layers should not be converted to hard swish layer. Please advise on how to turn off this behavior.

**Comment by mohantym** [comment]
Hi @mrtpk123 !
Have you checked [quantization_debugger ](https://www.tensorflow.org/lite/performance/quantization_debugger)documentation yet. You can skip quantization for some nodes through [selective quantization](https://www.tensorflow.org/lite/performance/quantization_debugger).

Thank you!

**Comment by mrtpk123** [comment]
Thank you @mohantym.
