### ISSUE TITLE
In tensorflow2.6, when in my keras.model uses yaml to load data, it will turn the array into a listener

### ISSUE THREAD

**Issue by jungyin** [tensorflow/tensorflow#56681]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tensorflow 2.6.0

### Custom Code

No

### OS Platform and Distribution

windows 10

### Mobile device

no use phone

### Python version

python3.8.8

### Bazel version

from pip install

### GCC/Compiler version

from pip install

### CUDA/cuDNN version

cuda 11.0

### GPU model and memory

from pip install

### Current Behaviour?

```shell
what bug?:
when i was extends keras.model and in there use yaml load .yaml file, the yaml file array data was changed to listwrapper,but if i not in my model,yaml file was success load array data,if in Same py folder but not in my model class ,yaml file was success load array data
i need what?:
i want in my model the yaml file can be surcess load was array not was listwarpper
```

### Standalone code to reproduce the issue

```shell
class Model(keras.Model):
    def __init__(self,cfg='/models/yolov5s.yaml',ch=3,nc=None):
        super(Model,self).__init__()
        if isinstance(cfg,dict):
            yaml = cfg
        else :
            import yaml as y
            yaml_file=Path(cfg).name
            with open(cfg) as f:
                yaml = y.load(f,Loader=y.FullLoader)
```

### Relevant log output

_No response_</details>

**Comment by jungyin** [comment]
and i was in tensorflow forum report this issues https://discuss.tensorflow.org/t/why-does-an-array-become-a-listwrapper-when-i-read-yaml-in-a-custom-model/10592

**Comment by sushreebarsa** [comment]
@jungyin I tried to replicate the issue on colab using latest TF version, and didn't face any issue.  Could you please check this [gist](https://colab.research.google.com/gist/sushreebarsa/8adea9f9d6e84053234416e7c74095e1/56681.ipynb) and let me know if I'm missing something to replicate the issue?
Thank you!

**Comment by jungyin** [comment]
I tried again, and it seems that I can't reproduce this problem again. Although I'm very unwilling, I will remember this problem, and I will solve it when it reappears

**Comment by sushreebarsa** [comment]
@jungyin Thank you for the update!
Please move this issue to closed status if it is resolved in latest version and feel free to let us know if you still face the issue?
Thank you!

**Comment by sushreebarsa** [comment]
@jungyin Thank you for the update!
Please move this issue to closed status if it is resolved in latest version and feel free to let us know if you still face the issue?
Thank you!
