### ISSUE TITLE
kernel_tests/nn_ops/xent_op_d9m_test.py test fails

### ISSUE THREAD

**Issue by enor2017** [tensorflow/tensorflow#56688]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.5 LTS (on colab)

### Mobile device

N/A

### Python version

3.7.13

### Bazel version

N/A

### GCC/Compiler version

N/A

### CUDA/cuDNN version

CUDA V11.1.105

### GPU model and memory

N/A

### Current Behaviour?

7 tests in python/kernal_tests/nn_ops/xent_op_d9m_test.py fail, it seems there is an InvalidArgumentError

```shell
E     tensorflow.python.framework.errors_impl.InvalidArgumentError: labels must be 1-D, but got shape []
E     	 [[{{node SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]]
```

Not all failures are due to this error, some failures are already tagged as bug by developers.

### Standalone code to reproduce the issue

Use pytest to run: `pytest sparse_xent_op_d9m_test.py`

Or find the gist [here](https://colab.research.google.com/drive/187TKAxXYtltx-7mY-zm2Z-wWYTiftAmz?usp=sharing)

### Relevant log output

The log is too long, I attach a part of it here, you may find the complete one on colab gist above.
```shell
_______________ SparseXentOpDeterministicTest.testScalarHandling _______________

    def _do_call(self, fn, *args):
      try:
>       return fn(*args)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py:1377: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

feed_dict = {<tensorflow.python.client._pywrap_tf_session.TF_Output object at 0x7f2b117351f0>: array([[0]], dtype=int32), <tensorf...t._pywrap_tf_session.TF_Output object at 0x7f2b117356f0>: array([[ 0.5549795, -0.6368797, -0.9563903]], dtype=float32)}
fetch_list = [<tensorflow.python.client._pywrap_tf_session.TF_Output object at 0x7f2b11735030>]
target_list = [], options = None, run_metadata = None

    def _run_fn(feed_dict, fetch_list, target_list, options, run_metadata):
      # Ensure any changes to the graph are reflected in the runtime.
      self._extend_graph()
      return self._call_tf_sessionrun(options, feed_dict, fetch_list,
>                                     target_list, run_metadata)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py:1361: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tensorflow.python.framework.test_util.ErrorLoggingSession object at 0x7f2b11734510>
options = None
feed_dict = {<tensorflow.python.client._pywrap_tf_session.TF_Output object at 0x7f2b117351f0>: array([[0]], dtype=int32), <tensorf...t._pywrap_tf_session.TF_Output object at 0x7f2b117356f0>: array([[ 0.5549795, -0.6368797, -0.9563903]], dtype=float32)}
fetch_list = [<tensorflow.python.client._pywrap_tf_session.TF_Output object at 0x7f2b11735030>]
target_list = [], run_metadata = None

    def _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list,
                            run_metadata):
      return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
                                              fetch_list, target_list,
>                                             run_metadata)
E     tensorflow.python.framework.errors_impl.InvalidArgumentError: labels must be 1-D, but got shape []
E     	 [[{{node SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]]

/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py:1455: InvalidArgumentError

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1377, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1361, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/client/session.py", line 1455, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: labels must be 1-D, but got shape []
	 [[{{node SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]]

During handling of the above exception, another exception occurred:

tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:
```
</details>

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to replicate the issue on colab, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/f954d24cc720043b5fb565bdf6dd7cdc/issue_gist2.ipynb#scrollTo=4edpBpxLQYYU). Thank you!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
