### ISSUE TITLE
tflite_runtime problem on Arm64 linux with multiprocessing

### ISSUE THREAD

**Issue by FSet89** [tensorflow/tensorflow#56683]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: no
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux (Arm64)
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: n/a
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**: 2.4.1
-   **Python version**: 3.6 (PC), 3.7 (embedded Linux)
-   **Bazel version (if compiling from source)**: n/a
-   **GCC/Compiler version (if compiling from source)**: n/a
-   **CUDA/cuDNN version**: 9
-   **GPU model and memory**: Titan xp
-   **Exact command to reproduce**:

### Describe the problem
I trained a neural network using quantization-aware training from tensorflow_model_optimization and converted it to a quantized tflite model. I have a python script that runs on a device with Linux (Arm64, 4 cores) and a NPU. This script uses the tflite_runtime module to make inference on the NPU with the NNAPI delegate:

> INFO: Created TensorFlow Lite delegate for NNAPI.
> Applied NNAPI delegate.

This script uses multiprocessing to perform other operations. The inference is made on the main process while other operations are executed like this:

```
p = Process(target=my_function, args=(my_args,))				
p.start()
```
The problem is that when I start a new process, the inference stops working: the neural network keeps returning the same output, no matter which input I provide. Even when the child process ends, the problem remains. This does not happen if I use threads instead of process.

### Source code / logs

Quantization (on the training PC):
```
import tensorflow as tf
import tensorflow_model_optimization as tfmot
with tfmot.quantization.keras.quantize_scope():
    model = tf.keras.models.load_model(path)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
quantized_tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(quantized_tflite_model)
```

Interpreter initialization (on the embedded linux):

```
import tflite_runtime.interpreter as tflite
interpreter = tflite.Interpreter(model_path=my_path)
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
input_shape = input_details[0]['shape']
```

Inference:

```
interpreter.set_tensor(input_details[0]['index'], my_input)				
interpreter.invoke()			
output = interpreter.get_tensor(output_details[0]['index'])
```

Pseudo-code of the script:

```
initialize_itnerpreter()
while True:
    acquire_input()
    perform_inference()
    if condition:
        p = Process(target=my_function, args=(my_args,))				
        p.start()
```

**Comment by mohantym** [comment]
Hi @FSet89 !
I think you are not using multi-threading in interpreter correctly during inference. You have to pass the number of threads in interpreter too. 
```
import multiprocessing
tf.lite.Interpreter(modelfile, num_threads=multiprocessing.cpu_count()). // modelfile means tflite file
```
Could you also test above syntax with 2.8/2.9 version and Python 3.7/3.8 (Python 3.7 is minimum version now)

Thank you!
