### ISSUE TITLE
tf.sparse.reshape cannot deal with tf.keras.Input(sparse=True)

### ISSUE THREAD

**Issue by KingsleyLiu-NV** [tensorflow/tensorflow#56696]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.8.0

### Custom Code

No

### Current Behaviour?

```shell
tf.sparse.reshape can deal with tf.SparseTensor, however, it cannot deal with tf.keras.Input even if sparse=True is specified for the input.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
inputs = tf.keras.Input(shape=(3, 4), sparse=True, dtype=tf.int64)
output = tf.sparse.reshape(inputs, [-1, 4])
```

### Relevant log output

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [79], in <cell line: 2>()
      1 inputs = tf.keras.Input(shape=(3, 4), sparse=True, dtype=tf.int64)
----> 2 output = tf.sparse.reshape(inputs, [-1, 4])

File /usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/sparse_ops.py:911, in sparse_reshape(sp_input, shape, name)
    861 @tf_export("sparse.reshape", v1=["sparse.reshape", "sparse_reshape"])
    862 @deprecation.deprecated_endpoints("sparse_reshape")
    863 def sparse_reshape(sp_input, shape, name=None):
    864   """Reshapes a `SparseTensor` to represent values in a new dense shape.
    865 
    866   This operation has the same semantics as `reshape` on the represented dense
   (...)
    909     ValueError:  If `shape` has more than one inferred (== -1) dimension.
    910   """
--> 911   sp_input = _convert_to_sparse_tensor(sp_input)
    912   shape = math_ops.cast(shape, dtype=dtypes.int64)
    914   with ops.name_scope(name, "SparseReshape", [sp_input]) as name:

File /usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/sparse_ops.py:67, in _convert_to_sparse_tensor(sp_input)
     65   return sparse_tensor.SparseTensor.from_value(sp_input)
     66 if not isinstance(sp_input, sparse_tensor.SparseTensor):
---> 67   raise TypeError("Input must be a SparseTensor.")
     68 return sp_input

TypeError: Input must be a SparseTensor.
```

**Comment by tilakrayal** [comment]
@chunduriv,
I was able to reproduce the issue on tensorflow v2.8, v.29 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3f5fb3361689ad3144e09f4fc6ffde16/56696-error.ipynb).

**Comment by chunduriv** [comment]
@KingsleyLiu-NV,

Thank you for opening this issue.  Development of keras moved to separate repository https://github.com/keras-team/keras/issues. 

Please post this issue on `keras-team/keras repo`. For more details please refer [here](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999).

**Comment by KingsleyLiu-NV** [comment]
@chunduriv I don't think it should be a keras issue. `tf.sparse.reshape` cannot deal with `tf.keras.Input(shape=(3, 4), sparse=True, dtype=tf.int64`, should not it be a TF issue?

**Comment by KingsleyLiu-NV** [comment]
@penpornk Any progress here?

**Comment by cantonios** [comment]
@KingsleyLiu-NV no I think that's a Keras issue.  Keras is a layer on top of TF, so TF's internals shouldn't need to know anything about keras.  TF only deals directly with Tf tensor types (`Tensor`, `SparseTensor`, `RaggedTensor`, etc...)

**Comment by hertschuh** [comment]
The commit in the last copybara comment fixes the issue.

The fix in now available in tf-nightly. Closing.
