### ISSUE TITLE
`tf.image.rgb_to_hsv` fails on back prop when dtype is double

### ISSUE THREAD

**Issue by VictoriaGriffith** [tensorflow/tensorflow#56694]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

```shell
Cannot compute the gradient for `tf.image.rgb_to_hsv` with `float64` inputs. It is working fine with forward pass.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
images = tf.random.uniform([5, 5, 3], dtype=tf.float64)
x = tf.image.rgb_to_hsv(images) # pass
with tf.GradientTape(persistent=True,) as g:
  g.watch(images)
  x = tf.image.rgb_to_hsv(images, )
grad = g.gradient(x, images) # InvalidArgumentError
```

### Relevant log output

```shell
InvalidArgumentError: cannot compute Mul as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:Mul]
```
</details>

**Comment by tilakrayal** [comment]
@VictoriaGriffith,
The problem is indeed the datatype of your input. By default your model expects float32 but you are passing a float64. Could you please either change the dtype of the model or change the input to float32. Thank you!

**Comment by VictoriaGriffith** [comment]
Hi @tilakrayal , thanks for your reply, indeed the gradient computation does not support `float64`. I just wonder why `tf.image.rgb_to_hsv` can expect a `float64` input if called directly (as in the snippet, and documentation also says it can accept a float64 input), but when I try to compute the gradient then it will complain about the input dtype. Wouldn't it be better if it can support `float64` both in the forward and backward pass?

**Comment by tilakrayal** [comment]
@chunduriv,
I was able to reproduce the issue on tensorflow v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/a043cc478402147d96f96737a25378de/56694.ipynb).
