### ISSUE TITLE
Small typo in documentation

### ISSUE THREAD

**Issue by hholst80** [tensorflow/tensorflow#5669]
In the code example in https://www.tensorflow.org/versions/r0.11/api_docs/python/train.html#replica_device_setter  `tf.replica_device_setter` is used instead of `tf.train.replica_device_setter`.

**Comment by girving** [comment]
Thanks!  Want to submit a quick PR?

**Comment by AnishShah** [comment]
This issue has been fixed. It can be closed. :)

**Comment by Carmezim** [comment]
@hholst80 This issue could be closed now as it's been solved.
