### ISSUE TITLE
Custom Op written in C API errors when requesting GPU_Device stream

### ISSUE THREAD

**Issue by YogaVicky** [tensorflow/tensorflow#56703]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Feature Request

### Source

binary

### Tensorflow Version

2.8

### Custom Code

Yes

### OS Platform and Distribution

Linux 

### Mobile device

07010841551

### Python version

3.9

### Current Behaviour?

```shell
Hi there!

I was trying to write a custom op using the tensorflow C API and in the cuda version I was facing errors while requesting for the GPU_Device stream.
My questions are:
1.Is there any way to convert SP_Stream(returned by TF_GetStream(context,status)) to cudastream?
2.What is the equivalent of eigen_device<GPUDevice>().stream() (c++) for the C API?
3.Where is the implementation of TF_OPKernelContext.

Thanks,
Yoga
```

### Standalone code to reproduce the issue

```shell
// C++ code
cudaStream_t theStream=context->eigen_device<GPUDevice>().stream();

// Equivalent C code
cudaStream_t theStream = TF_GetStream(context,status);
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@YogaVicky,
Could you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thank you!
