### ISSUE TITLE
'tensorflow.core.framework.types_pb2' has no attribute 'DT_RESOURCE'

### ISSUE THREAD

**Issue by laudney** [tensorflow/tensorflow#5671]
I successfully built the PIP package (at HEAD) on Windows with cmake.  When I tried to import it, I met several errors that all boil down to the following:

```
AttributeError: module 'tensorflow.core.framework.types_pb2' has no attribute 'DT_RESOURCE'
AttributeError: module 'tensorflow.core.framework.types_pb2' has no attribute 'DT_RESOURCE_REF'
```

**Comment by laudney** [comment]
Maybe because I had a previous build, git pulled and pb was using the old files?

**Comment by mrry** [comment]
This sounds like a similar problem to #5670. In this case, `protoc` isn't re-running, I'm guessing you've done an earlier build based on an old version of `tensorflow\core\framework\types.proto`, and the PIP package contains a mixture of code based on that old version and new code that expects to see the new types.

Your best bet (in the short term) is probably to delete the entire `tf_python` directory to force a rebuild.

**Comment by laudney** [comment]
@mrry Thank you, sir. I can confirm it's all good!
