### ISSUE TITLE
A error occured when using dense_to_ragged_batch in TFRecordDataset, is't a bug?

### ISSUE THREAD

**Issue by 123mbcz123** [tensorflow/tensorflow#56711]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

tf 2.9.0

### Custom Code

Yes

### OS Platform and Distribution

Windows 10 21H1

### Python version

3.9.12

### Current Behaviour?

```shell
Hi there!
  I was trying to concat var with diffient shapes into batches by using raggedTensor.
  I had preprocessed wav into mfcc and stored it in tfrecords.
  When I loaded them with TFRecordDataset, and tried using dense_to_ragged_batch to stack var into a raggedTensor.
  A error occured and It said "Cannot batch tensors with different shapes in component 0."
  I had tried using tf.data.Dataset to achieve the same thing without preprocessing,and also using dense_to_ragged_batch to stack batches.But it works fun.
Yours,
Soya.
I'm sorry for my poor English.And a mini code shows below.
```

### Standalone code to reproduce the issue

```shell
def parse_tfrecord(proto):
    features = {
        'label': tf.io.FixedLenFeature([], tf.string),
        'mfcc': tf.io.FixedLenFeature([], tf.string)
    }
    out = tf.io.parse_single_example(proto, features)
    mfcc = tf.io.parse_tensor(out['mfcc'], out_type='float32')
    label = out['label']
    return label, mfcc
def parse_tfrecord_data(data_raw):
    line, mfcc = parse_tfrecord(data_raw)
    return mfcc
def get_datasets():
    record_files = [os.path.join(train_record_dir, filename) for filename in os.listdir(train_record_dir)]
    dataset = tf.data.TFRecordDataset(record_files, num_parallel_reads=4).map(parse_tfrecord_data,
                                                                              num_parallel_calls=16)
    dataset = dataset.apply(tf.data.experimental.dense_to_ragged_batch(batch_size=global_batch_size))
    return dataset

if __name__ == '__main__':
    tf.data.experimental.enable_debug_mode()
    dataset = get_datasets()
    batch = next(iter(dataset))
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\a1313\PycharmProjects\ConformerRefactor\dataloader.py", line 66, in <module>
    batch = next(iter(dataset))
  File "C:\Users\a1313\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 766, in __next__
    return self._next_internal()
  File "C:\Users\a1313\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 749, in _next_internal
    ret = gen_dataset_ops.iterator_get_next(
  File "C:\Users\a1313\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 3043, in iterator_get_next
    _ops.raise_from_not_ok_status(e, name)
  File "C:\Users\a1313\AppData\Local\Programs\Python\Python39\lib\site-packages\tensorflow\python\framework\ops.py", line 7164, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot batch tensors with different shapes in component 0. First element had shape [429,128] and element 6 had shape [420,128]. [Op:IteratorGetNext]
```
</details>

**Comment by tilakrayal** [comment]
@123mbcz123,
To expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here.
 Thank you!

**Comment by 123mbcz123** [comment]
@tilakrayal 
I have organized my datasets and codes,and posted it to colab. Could you please have a look at it?  The colab link shows below.
https://colab.research.google.com/drive/1upagbX5ejvr0J_KTrWa0Q4ccJORZsAN-?usp=sharing

**Comment by 123mbcz123** [comment]
@tilakrayal  Thanks! I have checked your code line by line, It seems like you just change the batch_size and the filepath,is it right?  The batch_size bigger than one  still doesn't work in TFRecordDataset.,howerver,it works in tf.data.Dataset. 
    It seems that dense_to_ragged_batch in TFRecordDataset tries stacking tensors into a normal tf.tensor batch instead of a raggedTensor.
    dense_to_ragged_batch in tf.data.Dataset always stacks tensors into a raggedTensor even if batch_size equals to one,But in TFRecordDataset it returns a tf.Tensor when batch_size equals to one,and It throws errors when batch_size is bigger than one. 
Sincerely thanks again.

**Comment by tilakrayal** [comment]
> @tilakrayal Thanks! I have checked your code line by line, It seems like you just change the batch_size and the filepath,is it right? The batch_size bigger than one still doesn't work in TFRecordDataset.,howerver,it works in tf.data.Dataset. It seems that dense_to_ragged_batch in TFRecordDataset tries stacking tensors into a normal tf.tensor batch instead of a raggedTensor. dense_to_ragged_batch in tf.data.Dataset always stacks tensors into a raggedTensor even if batch_size equals to one,But in TFRecordDataset it returns a tf.Tensor when batch_size equals to one,and It throws errors when batch_size is bigger than one. Sincerely thanks again.

Yes. Also please take a look at this doc [link](https://www.tensorflow.org/api_docs/python/tf/data/experimental/dense_to_ragged_batch) which delivers the information on `dense_to_ragged_batch`. Thank you!

**Comment by tilakrayal** [comment]
@123mbcz123,
Could you please confirm if the issue is resolved. if yes, please feel free to move this issue to closed status. Thank you!

**Comment by 123mbcz123** [comment]
@Yes. Thanks!
