### ISSUE TITLE
Issues when updating the code from tf1 to tf2

### ISSUE THREAD

**Issue by nour397** [tensorflow/tensorflow#56719]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

source

### Tensorflow Version

tf2

### Custom Code

Yes

### Python version

3.7.13

### Current Behaviour?

```shell
'keras.api._v1.keras.layers' has no attribute 'conv2d'. I'm trying to change my code from tf1 to tf2, I changed all tf.layers to tf.keras.layers since in tf2 keras is the High level API and I had this error message
```

### Standalone code to reproduce the issue

```shell
Traceback (most recent call last):
  File "baseCNN_dbl_norm.py", line 103, in <module>
    model = Model()
  File "baseCNN_dbl_norm.py", line 46, in __init__
    self.logits = self.build(self.images, self.n_classes)
  File "baseCNN_dbl_norm.py", line 57, in build
    conv1 = tf.keras.layers.conv2d(inputs=features,
  File "C:\Users\LENOVO\.conda\envs\Dchecker1.0\lib\site-packages\tensorflow\python\util\module_wrapper.py", line 232, in _getattr
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'keras.api._v1.keras.layers' has no attribute 'conv2d'
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@nour397 Could you please refer to the migration [doc](https://www.tensorflow.org/guide/migrate) to rewrite the code in TF v2.x style and try with the latest TF version? For any further queries please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
