### ISSUE TITLE
RuntimeError: tensorflow/lite/kernels/concatenation.cc:158 t->dims->data[d] != t0->dims->data[d] (0 != 1)Node number 60 (CONCATENATION) failed to prepare.Failed to apply the default TensorFlow Lite delegate indexed at 0.

### ISSUE THREAD

**Issue by jsw-zorro** [tensorflow/tensorflow#56720]
### 1. System information

- OS Platform and Distribution: Ubuntu 18.04.5 
- TensorFlow installation: 2.8.0 (pip package or built from source):
- TensorFlow library (version, if pip package or github SHA, if built from source):

### 2. Code

Provide code to help us reproduce your issues using one of the following options:
Model can be accessed through link here: https://drive.google.com/file/d/1ucgrKsFkoWiEaZCtk_DmF_fIMqumhH4Z/view?usp=sharing
``` Python
interpreter = tf.lite.Interpreter(model_path="./temp_model.tflite")
interpreter.allocate_tensors()
```

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:
Conversion is successful. But when doing the inference, something wrong. The model can't be loaded.

RuntimeError: tensorflow/lite/kernels/concatenation.cc:158 t->dims->data[d] != t0->dims->data[d] (0 != 1)Node number 60 (CONCATENATION) failed to prepare.Failed to apply the default TensorFlow Lite delegate indexed at 0.

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @jsw-zorro 
Sorry for the late response. This issue does not seem to be replicating in [2.8.2](https://colab.sandbox.google.com/gist/mohantym/1baf7668f9ebf231e064ca1b90241924/git_56720.ipynb),[ 2.9](https://colab.sandbox.google.com/gist/mohantym/2b05938df0f2b9eb4f188426c42dfbfb/git_56720.ipynb#scrollTo=lrFFKjzdExQY) and [nightly](https://colab.sandbox.google.com/gist/mohantym/25399866b69e5e6f65b30abc01269ed6/git_56720.ipynb#scrollTo=rgrdzG4oD_h3). Could you try in 2.9/nightly and let us know.
Thank you!

**Comment by mohantym** [comment]
Ok @jsw-zorro !

Thanks for the update. Could your share your python version and complete error stack trace.
@gowthamkpr ! Could you please look at this issue.

Thank you!

**Comment by gowthamkpr** [comment]
@jsw-zorro Is it possible for you to provide a colab gist of this issue? Thanks!
