### ISSUE TITLE
raw_rnn equivalent in tensorflow 2.0

### ISSUE THREAD

**Issue by DYSIM** [tensorflow/tensorflow#56724]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### Current Behaviour?

```shell
I notice that TF2.0 does not include a raw_rnn api (https://www.tensorflow.org/api_docs/python/tf/compat/v1/nn/raw_rnn) that TF1.0 has. May I know how to achieve the behaviour of being able to control when to start and finish reading the sequence, in TF2.0, while generating variable-length sequence? 

In the text generation example (https://www.tensorflow.org/text/tutorials/text_generation) provided in the docs, to do a one-step prediction, the whole lstm time-steps has to be predicted and we take just the last prediction.

However, in raw_rnn, it is possible to sample one time-step at a time, and ending when a finished condition is true. 

Is there a difference between these two approach to generate variable-length sequence and train the lstm? How do I get the equivalent of raw_rnn functionality in TF2.0?

Thank you.
```

### Standalone code to reproduce the issue

```shell

https://www.tensorflow.org/text/tutorials/text_generation
```

### Relevant log output

_No response_</details>

**Comment by DYSIM** [comment]
@tilakrayal, I have read the documentation before, thanks for linking it.

May I know what is the equivalent of raw_rnn in TF2.0? Or whether it is possible to get "more control over when to start and finish reading the sequence, and what to emit for the output" in TF2.0?

Thank you.

**Comment by chunduriv** [comment]
@DYSIM,

>May I know what is the equivalent of raw_rnn in TF2.0?

`tf.compat.v1.nn.raw_rnn` is the compatible version that works in `TF2.x`

>whether it is possible to get "more control over when to start and finish reading the sequence, and what to emit for the output" in TF2.0?

Yes

Thank you.
