### ISSUE TITLE
Has a conda-forge pull request been submitted for TF 2.9?

### ISSUE THREAD

**Issue by jjl2** [tensorflow/tensorflow#56722]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

2.9

### Custom Code

No

### Current Behaviour?

```shell
In another discussion on May 17 (https://github.com/keras-team/keras/issues/15964), I was informed that a bug fix that I need is available in Tensorflow 2.9.  I have been waiting for TF 2.9 to become available in the conda-forge repository.

The process for adding packages to Anaconda repositories is here: 

https://conda-forge.org/docs/maintainer/adding_pkgs.html

"To submit a package to the conda-forge channel, add its recipe and license to the staged-recipes repository and create a pull request. Once the pull request is merged, the package becomes available on the conda-forge channel."

So it looks like someone on the Tensorflow team is responsible for getting the process started.  Has anyone done so?  Anaconda's package conflict resolution has eliminated the many dreaded compiler and CUDA incompatibility issues with Tensorflow that I experienced in previous years.

Thanks!
```

### Standalone code to reproduce the issue

```shell
No code.  

Just visit https://anaconda.org/search?q=tensorflow, and notice that the default Anaconda channel offers TF 2.6, while the cutting-edge conda-forge channel offers TF 2.8.  I can understand if the default repository continues to offer TF 2.6 if it is more stable, but I hope that 2.9 will be added to conda-forge.
```

### Relevant log output

_No response_</details>

**Comment by jjl2** [comment]
In another discussion on May 17 (https://github.com/keras-team/keras/issues/15964), I was informed that a bug fix that I need is available in Tensorflow 2.9.  I have been waiting for TF 2.9 to become available in the conda-forge repository.

Visit https://anaconda.org/search?q=tensorflow, and notice that the default Anaconda channel offers TF 2.6, while the cutting-edge conda-forge channel offers TF 2.8.  I can understand if the default repository continues to offer TF 2.6 if it is more stable, but I hope that 2.9 will be added to conda-forge.

The process for adding packages to Anaconda repositories is here: 

https://conda-forge.org/docs/maintainer/adding_pkgs.html

"To submit a package to the conda-forge channel, add its recipe and license to the staged-recipes repository and create a pull request. Once the pull request is merged, the package becomes available on the conda-forge channel."

So it looks like someone on the Tensorflow team is responsible for getting the process started.  Has anyone done so?  Anaconda's package conflict resolution has eliminated the many dreaded compiler and CUDA incompatibility issues with Tensorflow that I experienced in previous years.

Thanks!

**Comment by gadagashwini** [comment]
Hi @jjl2, Currently conda-forge has latest stable Tensorflow v2.8.1. As @ngam mentioned [tensorflow v2.9.1 ](https://github.com/conda-forge/tensorflow-feedstock/pull/245) pull request has been raised. 

You can install Tensorflow v2.9.1 using pip 
`pip install tensorflow==2.9.1`.
Thank you!

**Comment by gadagashwini** [comment]
Hi @jjl2, This issue looks more of conda-forge issue, could you raise in [conda-forge repo](https://github.com/conda-forge/tensorflow-feedstock/issues) for better and faster response. Thank you!

**Comment by jjl2** [comment]
@gadagashwini Thanks for your suggestion about installing TF 2.9 using pip, which of course I do know about.  But I'll also want GPU support, and trying to get that done with pip means that I'll have to go back to dealing with CUDA / CUDNN / GPU drivers manually.  That nightmare is the whole reason that I switched to Anaconda.

I will raise the issue with the conda-forge folks as you suggested.  The post from @ngam suggests that they're already working on it.

**Comment by gadagashwini** [comment]
Hi @jjl2, Could you close this issue here, we can track on conda-forge repo. Thank you!
