### ISSUE TITLE
CMAKE has no key to disable the build of python wrapper when building TF lite from source using Xcode or Android Studio

### ISSUE THREAD

**Issue by elsallam-myfiziq** [tensorflow/tensorflow#56735]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

TF2.9

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18 or MacOS

### Current Behaviour?

```shell
CMAKE has no key to disable the build of python wrapper when building TF lite from source using Xcode or Android Studio. 

current cmake in tensorflow/tensorflow/lite with the a non optional python wrapper, which triggers errors when using tensorflow as a submodule in an Xcode or Android studio project 

# Python interpreter wrapper.
add_library(_pywrap_tensorflow_interpreter_wrapper SHARED EXCLUDE_FROM_ALL
  ${TFLITE_SOURCE_DIR}/python/interpreter_wrapper/interpreter_wrapper.cc
  ${TFLITE_SOURCE_DIR}/python/interpreter_wrapper/interpreter_wrapper_pybind11.cc
  ${TFLITE_SOURCE_DIR}/python/interpreter_wrapper/numpy.cc
  ${TFLITE_SOURCE_DIR}/python/interpreter_wrapper/python_error_reporter.cc
  ${TFLITE_SOURCE_DIR}/python/interpreter_wrapper/python_utils.cc
)

# To remove "lib" prefix.
set_target_properties(_pywrap_tensorflow_interpreter_wrapper PROPERTIES PREFIX "")

target_include_directories(_pywrap_tensorflow_interpreter_wrapper
  PUBLIC
    ${TFLITE_INCLUDE_DIRS}
)

target_link_libraries(_pywrap_tensorflow_interpreter_wrapper
  tensorflow-lite
  ${CMAKE_DL_LIBS}
)
target_compile_options(_pywrap_tensorflow_interpreter_wrapper
  PUBLIC ${TFLITE_TARGET_PUBLIC_OPTIONS}
  PRIVATE ${TFLITE_TARGET_PRIVATE_OPTIONS}
)

I would expect a cmake key to enable or disable the python wrapper 
e.g.

if(TFLITE_ENABLE_pywrap)
...
endif()
```

### Standalone code to reproduce the issue

```shell
CMAKE has no key to disable the build of python wrapper when building TF lite from source using Xcode or Android Studio.
```

### Relevant log output

```shell
cannot find Python.h
```
</details>

**Comment by Yoline777** [comment]
get the same problem

**Comment by terryheo** [comment]
I'm not familiar with the process but adding flag should be simple. Is it OK to enable it by default?

**Comment by elsallam-myfiziq** [comment]
a flag to enable/disable would be the best option especially for those who add TensorFlow as a sub-module and don't want the python wrapper .  it could be as simple as this in the CMAKE file in tensorflow/tensorflow/lite

if(TFLITE_ENABLE_pywrap)
  # Python interpreter wrapper.
  add_library(_pywrap_tensorflow_interpreter_wrapper SHARED EXCLUDE_FROM_ALL
    ${TFLITE_SOURCE_DIR}/python/interpreter_wrapper/interpreter_wrapper.cc
    ${TFLITE_SOURCE_DIR}/python/interpreter_wrapper/interpreter_wrapper_pybind11.cc
    ${TFLITE_SOURCE_DIR}/python/interpreter_wrapper/numpy.cc
    ${TFLITE_SOURCE_DIR}/python/interpreter_wrapper/python_error_reporter.cc
    ${TFLITE_SOURCE_DIR}/python/interpreter_wrapper/python_utils.cc
  )
  
   set_target_properties(_pywrap_tensorflow_interpreter_wrapper PROPERTIES PREFIX "")
  
  target_include_directories(_pywrap_tensorflow_interpreter_wrapper
    PUBLIC
      ${TFLITE_INCLUDE_DIRS}
  )
    target_link_libraries(_pywrap_tensorflow_interpreter_wrapper
    tensorflow-lite
    ${CMAKE_DL_LIBS}
  )
  target_compile_options(_pywrap_tensorflow_interpreter_wrapper
    PUBLIC ${TFLITE_TARGET_PUBLIC_OPTIONS}
    PRIVATE ${TFLITE_TARGET_PRIVATE_OPTIONS}
  )
endif()

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
