### ISSUE TITLE
[`tf.data` - `from_generator()` and `.interleave()`] - Funky Behavior

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorflow/tensorflow#56746]
We are trying to combine `N_DATASETS_TO_INTERLEAVE` `from_generator()` Datasets using dataset Interleaving. And it seems that it's absolutely not working.

For some reason, it looks like the print is happening only once. Which could be due to some form of autograph running, but we tried everything we could to stop that, but nothing I could think of works.

You will say, it's just a `print()` what's the problem here. The problem is that if you execute any python code in this `from_generator()` it seems to be executed only once.

Google Colab: https://colab.research.google.com/drive/1WFvSvU8CCc1A1bfVbUb6ck_EzvE9o3sS?usp=sharing

```python
import tensorflow as tf

N_DATASETS_TO_INTERLEAVE = 10

@tf.autograph.experimental.do_not_convert
def hello(idx):
  for j in range(idx):
    yield f"IDX: {idx}"
    

@tf.autograph.experimental.do_not_convert
def interleave_fn(_):
    print("[INFO] Calling Interleave Fn")         # THIS LINE SHOULD BE PRINTED `N_DATASETS_TO_INTERLEAVE` times. Only appears once.
    return tf.data.Dataset.from_generator(
        hello, args=(_,), output_types=tf.string
    )


ds = tf.data.Dataset.range(N_DATASETS_TO_INTERLEAVE).interleave(
    interleave_fn
)

options = tf.data.Options()
options.experimental_optimization.apply_default_optimizations = False
ds = ds.with_options(options)


@tf.autograph.experimental.do_not_convert
def get_dataset(_ds):
    for x in iter(_ds):
        yield x


for x in get_dataset(ds):
  print(x)
```

Output:
```bash
[INFO] Calling Interleave Fn
WARNING:tensorflow:From <ipython-input-1-af809f9fe8c1>:15: calling DatasetV2.from_generator (from tensorflow.python.data.ops.dataset_ops) with output_types is deprecated and will be removed in a future version.
Instructions for updating:
Use output_signature instead
tf.Tensor(b'IDX: 1', shape=(), dtype=string)
tf.Tensor(b'IDX: 2', shape=(), dtype=string)
tf.Tensor(b'IDX: 2', shape=(), dtype=string)
tf.Tensor(b'IDX: 3', shape=(), dtype=string)
tf.Tensor(b'IDX: 3', shape=(), dtype=string)
tf.Tensor(b'IDX: 4', shape=(), dtype=string)
tf.Tensor(b'IDX: 3', shape=(), dtype=string)
tf.Tensor(b'IDX: 4', shape=(), dtype=string)
tf.Tensor(b'IDX: 4', shape=(), dtype=string)
tf.Tensor(b'IDX: 5', shape=(), dtype=string)
tf.Tensor(b'IDX: 4', shape=(), dtype=string)
tf.Tensor(b'IDX: 5', shape=(), dtype=string)
tf.Tensor(b'IDX: 5', shape=(), dtype=string)
tf.Tensor(b'IDX: 6', shape=(), dtype=string)
tf.Tensor(b'IDX: 5', shape=(), dtype=string)
tf.Tensor(b'IDX: 6', shape=(), dtype=string)
tf.Tensor(b'IDX: 5', shape=(), dtype=string)
tf.Tensor(b'IDX: 6', shape=(), dtype=string)
tf.Tensor(b'IDX: 6', shape=(), dtype=string)
tf.Tensor(b'IDX: 7', shape=(), dtype=string)
tf.Tensor(b'IDX: 6', shape=(), dtype=string)
tf.Tensor(b'IDX: 7', shape=(), dtype=string)
tf.Tensor(b'IDX: 6', shape=(), dtype=string)
tf.Tensor(b'IDX: 7', shape=(), dtype=string)
tf.Tensor(b'IDX: 7', shape=(), dtype=string)
tf.Tensor(b'IDX: 8', shape=(), dtype=string)
tf.Tensor(b'IDX: 7', shape=(), dtype=string)
tf.Tensor(b'IDX: 8', shape=(), dtype=string)
tf.Tensor(b'IDX: 7', shape=(), dtype=string)
tf.Tensor(b'IDX: 8', shape=(), dtype=string)
tf.Tensor(b'IDX: 7', shape=(), dtype=string)
tf.Tensor(b'IDX: 8', shape=(), dtype=string)
tf.Tensor(b'IDX: 8', shape=(), dtype=string)
tf.Tensor(b'IDX: 9', shape=(), dtype=string)
tf.Tensor(b'IDX: 8', shape=(), dtype=string)
tf.Tensor(b'IDX: 9', shape=(), dtype=string)
tf.Tensor(b'IDX: 8', shape=(), dtype=string)
tf.Tensor(b'IDX: 9', shape=(), dtype=string)
tf.Tensor(b'IDX: 8', shape=(), dtype=string)
tf.Tensor(b'IDX: 9', shape=(), dtype=string)
tf.Tensor(b'IDX: 9', shape=(), dtype=string)
tf.Tensor(b'IDX: 9', shape=(), dtype=string)
tf.Tensor(b'IDX: 9', shape=(), dtype=string)
tf.Tensor(b'IDX: 9', shape=(), dtype=string)
tf.Tensor(b'IDX: 9', shape=(), dtype=string)
```

Why this matter ?

We are trying to read and interleave multiple files that have a funky format. No native TF OPs can help to do that.
We need to use a generator because the files are massive (dataset 100GB+), we can't load the whole file at once.
We need to use interleaving because we have multiple files to interleave together.

Annnnd ... As you can see ... The python part of this code is only executed once.

We would expect to see (`[INFO] Calling Interleave Fn` printed `N_DATASETS_TO_INTERLEAVE` times).
```python
[INFO] Calling Interleave Fn
[INFO] Calling Interleave Fn
[INFO] Calling Interleave Fn
...
[INFO] Calling Interleave Fn
[INFO] Calling Interleave Fn
[INFO] Calling Interleave Fn
```

My hunch is that `tf.data.from_generator()` does not allow python generator. Only pure tensorflow generators. Any idea how to maybe combine `tf.py_function` in a generator fashion ?

@reedwm in case you have any idea ;)

**Comment by DEKHTIARJonathan** [comment]
I think I found the problem:

```
import tensorflow as tf

from tensorflow.python.data.ops import structured_function


@tf.autograph.experimental.do_not_convert
def hello():
    print("Calling ........")
    return 4
    
for _ in range(5):
    hello()

>>>  Calling ........
>>>  4
>>>  Calling ........
>>>  4
>>>  Calling ........
>>>  4
>>>  Calling ........
>>>  4
>>>  Calling ........
>>>  4

    
wrapped_func = structured_function.StructuredFunctionWrapper(
    hello,
    "reduce()",
    input_structure=(),
    add_to_graph=False
)

>>> Calling ........
    
for _ in range(5):
    wrapped_func._function()

>>>  [<tf.Tensor: shape=(), dtype=int32, numpy=4>]
>>>  [<tf.Tensor: shape=(), dtype=int32, numpy=4>]
>>>  [<tf.Tensor: shape=(), dtype=int32, numpy=4>]
>>>  [<tf.Tensor: shape=(), dtype=int32, numpy=4>]
>>>  [<tf.Tensor: shape=(), dtype=int32, numpy=4>]

**Comment by DEKHTIARJonathan** [comment]
Looks like I found one way to force `autograph` to not execute: `tf.data.experimental.enable_debug_mode()`

@reedwm do you know any other way ? It's kind of weird to be forced to use debug mode ...

```python
import tensorflow as tf

from tensorflow.python.data.ops import structured_function

@tf.autograph.experimental.do_not_convert
class HelloIter(object):
    def __init__(self):
         self._iter = None
         self.reset()
    
    def reset(self):
        print("\nResetting the iterator ...")
        self._iter = iter([1, 2, 3])
        print("Done ...\n")
    
    @tf.autograph.experimental.do_not_convert
    def __call__(self):
        print("Calling Mom ...")
        return next(self._iter)

hello = HelloIter()

for _ in range(3):
    print(hello())

hello.reset()

for _ in range(3):
    print(hello())

tf.data.experimental.enable_debug_mode()

hello_obj = HelloIter()

wrapped_func = structured_function.StructuredFunctionWrapper(
    hello_obj,
    "reduce()",
    input_structure=(),
    # add_to_graph=False,
    use_legacy_function=False
)

hello_obj.reset()  # Must re-initialize the `iter()` because `structured_function.StructuredFunctionWrapper` actually runs the func once

for _ in range(3):
    print(wrapped_func._function())
```

**Comment by sushreebarsa** [comment]
@sachinprasadhs I was able to replicate the issue on colab, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/8ced5f2f54fa9832613a52566a8b8596/untitled1.ipynb#scrollTo=hAf3_rVThdhP). Thank you!

**Comment by reedwm** [comment]
Unfortunately I don't know how to solve this. Dataset methods taking callables like `map` and `interleave` always run the callable in graph mode unless debug_mode is enabled, as you noticed. I am not familiar with StructuredFunctionWrapper but tf.data.Dataset seems to use it to always run the function in graph mode unless debug_mode is used.

I tried to modify the example in the first post, to create an interleave_fn that would use `tf.py_function` to run a function eagerly. It failed with the cryptic error "Could not find callback with key=pyfunc_5 in the registry". I'm not sure what the issue was

```python
@tf.autograph.experimental.do_not_convert
def outer_interleave_fn(_):
  return tf.py_function(interleave_fn, [_], Tout=[tf.data.DatasetSpec(tf.TensorSpec(shape=(), dtype=tf.string))])[0]
```

@aaudiber, any ideas how to run an interleave_fn eagerly?

@DEKHTIARJonathan as a workaround, it might be possible to define a custom iterator to pass to `tf.data.Dataset.from_generator`, where the `iterable.__next__` method calls `tf.py_function`. This would allow you to run Python code from the iterable passed to `tf.data.Dataset.from_generator`.

**Comment by DEKHTIARJonathan** [comment]
> "Could not find callback with key=pyfunc_5 in the registry
Oh yes ! I had the exact same problem, in many ways actually. The way to "avoid" this is to have `block_length=sys.maxsize` (max int). Which is making the whole behavior equivalent to a concatenate, and no more interleaving... Looks like it's failing to fetch a previously define dataset "by key".

**Comment by aaudiber** [comment]
It isn't currently possible to dynamically create `from_generator`-based datasets from inside of `interleave`. The problem is that `py_function` can only return Tensors, but we need it to produce a Python `tf.data.Dataset` object.

Instead, you could work around the issue by creating the `from_generator` datasets ahead of time in Python, and then interleaving them. The example below does what the original post was attempting:

```python
import tensorflow as tf

N_DATASETS_TO_INTERLEAVE = 10

def hello(idx):
  for j in range(idx):
    yield f"IDX: {idx}"

def make_dataset(idx):
    return tf.data.Dataset.from_generator(
        lambda: hello(idx), output_types=tf.string
    )

datasets = [make_dataset(i) for i in range(N_DATASETS_TO_INTERLEAVE)]

ds = tf.data.Dataset.from_tensor_slices(datasets)
ds = ds.interleave(lambda x: x, cycle_length=N_DATASETS_TO_INTERLEAVE)

for x in ds:
  print(x)
```

**Comment by sachinprasadhs** [comment]
@DEKHTIARJonathan , Could you please try the above workaround and let us know if that helps you. Thanks!
