### ISSUE TITLE
Building `tflite` for `manylinux`

### ISSUE THREAD

**Issue by pharmpy-dev-123** [tensorflow/tensorflow#56743]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

NA

### Python version

3.8, 3.9, 3.10

### Bazel version

5.0.0

### Current Behaviour?

```shell
I am trying to build a `tflite` wheel on GitHub Actions (`ubuntu-latest`) with `bash tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh`. How does one request a `manylinux` build? Currently the build completes but produces a `linux_x86_64` suffixed wheel.
```

### Standalone code to reproduce the issue

```shell
Run `bash tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh` on Ubuntu 20.04 on GitHub Actions.
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @pharmpy-dev-123 !
Sorry for the late response.
I checked this [thread](https://discuss.tensorflow.org/t/tensorflow-linux-wheels-are-being-upgraded-to-manylinux2014/8339) which says Tensorflow linux wheels have been upgrade  manylinux 2014 wheel. 
To get a more compatible wheel for your workstation you can run

`tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh native
` 

[Reference.](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package)
Thank you!

**Comment by pharmpy-dev-123** [comment]
Hi @mohantym. As I understand it, a `native` build would produce a less generic binary. I am looking for a more generic binary. I could find some references on how to obtain such a build (`manylinux`) for TensorFlow, but it seems instructions are missing for `tflite`.

**Comment by pkgoogle** [comment]
Hi @pharmpy-dev-123,

To build a more generic binary you can omit the native parameter, is there a reason you need to build it? can you just use the pre-release package?
