### ISSUE TITLE
some numpy operation(FFT,FFT2d,RFFT,RFFT2d) failed when building a model 

### ISSUE THREAD

**Issue by TWTcodeKing** [tensorflow/tensorflow#56748]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.2

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.7

### CUDA/cuDNN version

11.0/8.0

### GPU model and memory

NVIDIA A6000 /48G

### Current Behaviour?

```shell
I want to use API "tf.signal.rfft2d" to create a model, and when I set the shape of the input tensor as (None,None,3), i.e., dynamic shape, tf.signal.rfft2d produce something abnormal. The shape of the output of tf.signal.rfft2d will be [None,None,None,None]. This won't happen when the shape of the input tensor is a constant, e.g.,(1024,1024,3), but this constrains the flexibility of the model. I've tried to use tf.keras.layers.Lambda and tf.raw_ops.RFFT2d but all failed. I also spotted that even if the model can successfully be complied with the input shape as [None,None,3], it failed to produce real value when accepting real data. I'm wondering whether it's because tf.signal.rfft2d only accept tensor or numpy object whose shape has a real value instead of None. Who has met this problem before?
```

### Standalone code to reproduce the issue

```shell
this is my code:
def ResBLock_do_fft_bench(inputs,filters):
    axis = 1
    x = K.permute_dimensions(inputs,(0,3,1,2))
    x = tf.keras.layers.Lambda(lambda v:tf.raw_ops.RFFT2D(input=v,fft_length=(tf.shape(v)[2],tf.shape(v)[3]//2+1)))(x)
    y_imag = tf.compat.v1.imag(x)
    y_real = tf.compat.v1.real(x)
    y_f = tf.concat([y_real, y_imag], axis=axis)
    y_f = tf.keras.layers.Permute((2,3,1))(y_f)
    y = BasicConv_do(y_f,filters*2,kernel_size=1,stride=1,relu=True)
    y = BasicConv_do(y,filters*2,kernel_size=1,stride=1,relu=False)
    y = tf.keras.layers.Permute((3,1,2))(y)
    y_real, y_imag = tf.split(y, 2, axis=axis)
    y = tf.complex(y_real, y_imag)
    y = tf.keras.layers.Lambda(lambda v:tf.raw_ops.IRFFT2D(input=v,fft_length=(-1,-1)))(y)
    y = tf.keras.layers.Permute((2,3,1))(y)
    res = BasicConv_do(inputs,filters,kernel_size=3,stride=1,relu=True)
    res = BasicConv_do(res,filters,kernel_size=3,stride=1,relu=False)
    return res + inputs + y
def FFT_Block():
    input = tf.keras.layers.Input(shape = [None,None,32],name='blur_image')
    out = ResBLock_do_fft_bench(input,32)
    model = tf.keras.models.Model(inputs=input,outputs=out,name='test')
    return model
```

### Relevant log output

```shell
the shape of the x before fft is:
(None, 32, None, None)
after fft:
(None, 32, None, None).

When the model takes a real value,this happens:
Traceback (most recent call last):
  File "D:\Anaconda\envs\AIM\lib\site-packages\tensorflow\python\ops\gen_spectral_ops.py", line 906, in irfft2d
    tld.op_callbacks, input, fft_length, "Treal", Treal)
tensorflow.python.eager.core._FallbackException: This function does not handle the case of the path where all inputs are not already EagerTensors.


if I change tf.raw_ops.RFFT2D to tf.signal.rfft2d, there will be another bug:
the shape of the x before fft:
(None, 32, None, None)
after fft:
(None, None, None, None)
```
</details>

**Comment by sushreebarsa** [comment]
@TWTcodeKing Older version of TF is not actively supported. Could you please upgrade to the latest version and please provide a code snippet to reproduce the issue reported here if the issue still persist? Thank you!

**Comment by TWTcodeKing** [comment]
> @TWTcodeKing Older version of TF is not actively supported. Could you upgrade to the latest version and please provide a code snippet to reproduce the issue reported here if the issue still persists? Thank you!

Yes! I upgrade the tf version to 2.9.1, which is the newest. And I have a brief test on my desktop computer whose Os is Windows and the error still exists, shown below:
before FFT:(None, None, None, 32)
after FFT:(None, None, None, None)
2022-07-14 16:27:34.262034: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-14 16:27:34.610717: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1661 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 Ti Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
Traceback (most recent call last):
  File "C:/Users/19356/Desktop/DeepRFT_tf/layers.py", line 228, in <module>
    model = FFT_Block()
  File "C:/Users/19356/Desktop/DeepRFT_tf/layers.py", line 224, in FFT_Block
    out = ResBlock_do_fft_bench(input,32)
  File "C:/Users/19356/Desktop/DeepRFT_tf/layers.py", line 82, in ResBlock_do_fft_bench
    y = BasicConv_do(y_f,filters*2,kernel_size=1,stride=1,relu=True)
  File "C:/Users/19356/Desktop/DeepRFT_tf/layers.py", line 34, in BasicConv_do
    x = DOConv2D(filters, kernel_size, padding='same', strides=stride, use_bias=bias, groups=groups)(inputs)
  File "D:\Anaconda\envs\TF29\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\19356\Desktop\DeepRFT_tf\doconv_tf.py", line 66, in build
    input_channel = self._get_input_channel(input_shape)
ValueError: The channel dimension of the inputs should be defined. The input_shape received is (None, None, None, None), where axis -1 (0-based) is the channel dimension, which found to be `None`. 
I think it's a tf bug because it appears on both Linux and Windows

**Comment by sushreebarsa** [comment]
@TWTcodeKing 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!

**Comment by TWTcodeKing** [comment]
> @TWTcodeKing In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!

Thank you! I think I've already solved this problem by myself. I am a noob in using tensorflow, my original code was:
def ResBlock_do_fft_bench(inputs,filters):
    axis = 1
    x = inputs
    x = tf.keras.layers.Lambda(lambda v:tf.signal.rfft2d(v))(x)
    y_imag = tf.compat.v1.imag(x)
    y_real = tf.compat.v1.real(x)
    y_f = tf.concat([y_real, y_imag], axis=axis)
    y_f = tf.keras.layers.Permute((2,3,1))(y_f)
    y = BasicConv_do(y_f,filters*2,kernel_size=1,stride=1,relu=True)
    y = BasicConv_do(y,filters*2,kernel_size=1,stride=1,relu=False)
    y = tf.keras.layers.Permute((3,1,2))(y)
    y_real, y_imag = tf.split(y, 2, axis=axis)
    y = tf.complex(y_real, y_imag)
    y = tf.keras.layers.Lambda(lambda v:tf.raw_ops.IRFFT2D(input=v,fft_length=(-1,-1)))(y)
    y = tf.keras.layers.Permute((2,3,1))(y)
    res = BasicConv_do(inputs,filters,kernel_size=3,stride=1,relu=True)
    res = BasicConv_do(res,filters,kernel_size=3,stride=1,relu=False)
    return res + inputs + y

And later I realize that tf can't convince the input shape during compiling but only during training or testing, so it is not right to use tf.signal.rfft2d with a simple function, so I modify my code as below:
class ResBlock_do_fft_bench(keras.models.Model):
    def __init__(self,filters):
        super(ResBlock_do_fft_bench,self).__init__()
        self.filters = filters

    def build(self, input_shape):
        assert len(input_shape) == 4
        shape = (input_shape[-1],)
        self.BasicConvY1 = BasicConv_do(self.filters*2,kernel_size=1,stride=1,relu=True)
        self.BasicConvY2 = BasicConv_do(self.filters*2,kernel_size=1,stride=1,relu=False)

        self.BasicConvRes1 = BasicConv_do(self.filters,kernel_size=3,stride=1,relu=True)
        self.BasicConvRes2 = BasicConv_do(self.filters,kernel_size=3,stride=1,relu=False)

    def call(self,inputs):
        if inputs.shape[-1] == None:
            return inputs
        else:
            axis = 1
            x = tf.signal.rfft2d(inputs)
            y_imag = tf.compat.v1.imag(x)
            y_real = tf.compat.v1.real(x)
            y_f = tf.concat([y_real, y_imag], axis=axis)
            y_f = tf.transpose(y_f,(0,2,3,1))
            y = self.BasicConvY1(y_f)
            y = self.BasicConvY2(y)
            y = tf.transpose(y,(0,3,1,2))(y)
            y_real, y_imag = tf.split(y, 2, axis=axis)
            y = tf.complex(y_real, y_imag)
            y = tf.signal.irfft2d(y)
            y = tf.keras.layers.Permute((2,3,1))(y)
            res = self.BasicConvRes1(y)
            res = self.BasicConvRes2(res)
        return res + inputs + y
Then it finally works, thanks a lot for your comment!

**Comment by sushreebarsa** [comment]
@TWTcodeKing Thank you for the update!
Please move this issue to closed status if it is resolved ?
Thank you!
