### ISSUE TITLE
Cant use GPU when using Tensorflow Lite Model on Custom Object Detection

### ISSUE THREAD

**Issue by JuanJoseMoralesCalvo** [tensorflow/tensorflow#56753]
Hi, im trying to use transferlearning on MobileNetV2 SSD for facial detection. When i run the model on the example provided for Object Detection using CPU it works well but when i use GPU, Android shows me this error:

org.tensorflow.lite.examples.objectdetection E/tflite: Following operations are not supported by GPU delegate:
    CUSTOM TFLite_Detection_PostProcess: TFLite_Detection_PostProcess
    PACK: OP is supported, but tensor type/shape isn't compatible.
    RESHAPE: OP is supported, but tensor type/shape isn't compatible.
    111 operations will run on the GPU, and the remaining 46 operations will run on the CPU. 

And the App stops working.

The code use for converting the saved model to tflite its the following:

import tensorflow as tf

saved_model_dir = 'url'

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
tflite_model = converter.convert()
open("url", "wb").write(tflite_model)

I use libraries and functions:
tf-nightly
export_tflite_graph_tf2.py
tflite_support_nightly

Thanks in advance.

**Comment by JuanJoseMoralesCalvo** [comment]
The model was trained with a batch of 64 images just if you need more info about it.

@impjdi

**Comment by mohantym** [comment]
Hi @JuanJoseMoralesCalvo !

Could try with select ops syntax , Tensorflow-lite-gpu:2.8.0 or higher  dependency in build.gradle file and let us know the difference .
```
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
```

**Comment by JuanJoseMoralesCalvo** [comment]
Same error with those changes:

org.tensorflow.lite.examples.objectdetection E/tflite: Following operations are not supported by GPU delegate:
    CUSTOM TFLite_Detection_PostProcess: TFLite_Detection_PostProcess
    PACK: OP is supported, but tensor type/shape isn't compatible.
    RESHAPE: OP is supported, but tensor type/shape isn't compatible.
    111 operations will run on the GPU, and the remaining 46 operations will run on the CPU.

**Comment by impjdi** [comment]
can you attach the model file?

**Comment by JuanJoseMoralesCalvo** [comment]
Yes, here it is the tflite model with the metadata needed:
[detectlast.zip](https://github.com/tensorflow/tensorflow/files/9109516/detectlast.zip)

**Comment by JuanJoseMoralesCalvo** [comment]
Im a bit knew with these :D, could you guide me a little bit with the solutions? Im sorry for taking your time.

**Comment by sachinprasadhs** [comment]
TFLite now supports 5D in selectV2, could you please try in the latest nightly version or the Tensorflow version 2.10 and confirm. More details can be found here https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md#major-features-and-improvements-1

**Comment by zcase** [comment]
Wanted to see if there was any update here.

I am running tensorflow lite version 2.10.0 and for a native C++ object detection app and getting similar issues when running on the GPU with not only a custom model but a model downloaded straight from the TF2 model zoo.

I have followed the instructions of taking any of the ssd models (mostly the mobilenet models) and running the export script for tf2 and then using python tf converter to create the model.tflite file. 

The tflite model that doesn't given me those pack or reshape errors is the mobilenet_v1 tflite model (with metadata) downloaded from the tfhub site.

Are there any steps to create a .tflite model for object detection on tensorflow 2.10.0 where the pack and reshape issues don't come up and most operations run on the GPU?

**Comment by zcase** [comment]
Please reopen this ticket as the issue is still present

**Comment by impjdi** [comment]
@sachinprasadhs I don't know enough about TF 2.10 or the converter.  Can this be assigned to the owner of TFLite convert?

**Comment by zcase** [comment]
Not sure if this helps give a direction to look for the issue, but I found it one modifies the default pretrained config file (I was using mobilenetV2) and you change the following area to look like this:

`    
anchor_generator {
      multiscale_anchor_generator {
        min_level: 3
        max_level: 3
        anchor_scale: 4.0
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        scales_per_octave: 2
      }
    }
`

i.e change the max_level from 7 to 3 and you change 

The fpn info to look like the following:
` 
fpn {
        min_level: 3
        max_level: 3
        additional_layer_depth: 128
}
`

i.e. change max level from 7 to 3 it didn't give me those errors and in c++ i ended up with the following GPU delegate output:

`
Setting up GPU
Delegate Created!
Checking Delegate
ERROR: Following operations are not supported by GPU delegate:
CUSTOM TFLite_Detection_PostProcess: TFLite_Detection_PostProcess
78 operations will run on the GPU, and the remaining 1 operations will run on the CPU.
INFO: Created 1 GPU delegate kernels.
`
Not doing this or even just stepping down from 7 to 6 or 7 to 5 caused the model to create a nearest_neighbor_upsampling/stack_1 node that had 6 dimensions and appeared to be an issue or cause those PACK and RESHAPE issues:

Here is a part of the model html file created from the visualize.py in the lite/tools folder:



203 | ssd_mobile_net_v2fpn_keras_feature_extractor/FeatureMaps/top_down/nearest_neighbor_upsampling/nearest_neighbor_upsampling/stack_1 | FLOAT32 | [1, 10, 2, 10, 2, 128] | None | 204 | {'details': None, 'details_type': 0, 'max': None, 'min': None, 'quantized_dimension': 0, 'scale': None, 'zero_point': None}
-- | -- | -- | -- | -- | -- | --


`
`

**Comment by zcase** [comment]
Could this issue result from using cuda 11.6? Just asking because I switched back to a commit for the models repo that was back around the time of tensorflow 2.5.0 thinking this would make things work and was seeing about the same issue.

Only difference was that the model that was created and then exported to a .tflite file always seemed to run everything on the GPU except the last output layer where as in 2.10.0 it always seemed to split things between the gpu and cpu.

**Comment by zcase** [comment]
So found out that downgrading to cura 11.2 and cudnn-8.101 does resolve the issues.

Any thoughts?

**Comment by zcase** [comment]
@sachinprasadhs @impjdi @miaout17 I think I have found the issue.
It appears that in the first version of the the export_tflite_ssd_graph.py it called the export_tflite_ssd_graph_lib.py which and a pruning of the h_stack and w_stack tensors that had the shapes I mentioned above.

The export_tflite_graph_lib_tf2.py doesn't seem to have this.

I modifyed the ops.py file found in the models repo (models/research/object_detection/utils/ops.py) so that the nearest_neighbor_upsampling function which was causing the problem looked like the following:

```python
def nearest_neighbor_upsampling(input_tensor, scale=None, height_scale=None,
                                width_scale=None,
                                name='nearest_neighbor_upsampling'):
  """Nearest neighbor upsampling implementation.

  Nearest neighbor upsampling function that maps input tensor with shape
  [batch_size, height, width, channels] to [batch_size, height * scale
  , width * scale, channels]. This implementation only uses reshape and
  broadcasting to make it TPU compatible.

  Args:
    input_tensor: A float32 tensor of size [batch, height_in, width_in,
      channels].
    scale: An integer multiple to scale resolution of input data in both height
      and width dimensions.
    height_scale: An integer multiple to scale the height of input image. This
      option when provided overrides `scale` option.
    width_scale: An integer multiple to scale the width of input image. This
      option when provided overrides `scale` option.
    name: A name for the operation (optional).
  Returns:
    data_up: A float32 tensor of size
      [batch, height_in*scale, width_in*scale, channels].

  Raises:
    ValueError: If both scale and height_scale or if both scale and width_scale
      are None.
  """
  if not scale and (height_scale is None or width_scale is None):
    raise ValueError('Provide either `scale` or `height_scale` and'
                     ' `width_scale`.')
  with tf.name_scope(name):
    h_scale = scale if height_scale is None else height_scale
    w_scale = scale if width_scale is None else width_scale
    (batch_size, height, width,
     channels) = shape_utils.combined_static_and_dynamic_shape(input_tensor)
    # output_tensor = tf.stack([input_tensor] * w_scale, axis=3, name='w_stack')
    # # Adds a reshape op to avoid generating high-dimensional tensors that some
    # # compilers cannot deal with.
    # output_tensor = tf.reshape(output_tensor,
    #                            [batch_size, height, width * w_scale, channels])
    # output_tensor = tf.stack([output_tensor] * h_scale, axis=2, name='h_stack')


    output_tensor = tf.concat([input_tensor] * w_scale, axis=2, name='w_concat')
    # output_tensor = tf.reshape(output_tensor,
    #                               [batch_size, height, width * w_scale, channels])
    output_tensor = tf.concat([output_tensor] * h_scale, axis=1, name='h_concat')
    # output_tensor = tf.reshape(output_tensor,
    #                       [batch_size, height * h_scale, width * w_scale, channels])

    # # My Addition
    # output_tensor = tf.reshape(output_tensor,
    #                   [batch_size, height * h_scale, width * w_scale, channels])
    # return tf.reshape(output_tensor,
    #                   [batch_size, height * h_scale, width * w_scale, channels])
    output_tensor = tf.reshape(output_tensor, [batch_size, height * h_scale, width * w_scale, channels])

    return output_tensor
```

My question here is, doing a tf.concat the same as doing a tf.stack and then a tf.reshape? Also I noticed that the docstring states talks about being TPU compatible, so is what i did above TPU compatable?

**Comment by zcase** [comment]
@miaout17 @sachinprasadhs any thoughts on this???

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
