### ISSUE TITLE
docs: Google Colab button at the top of this page

### ISSUE THREAD

**Issue by ng0177** [tensorflow/tensorflow#56750]
> docs: To follow this tutorial, run the notebook in Google Colab by clicking the button at the top of this page.
https://github.com/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb

Feature request: please add a screenshot or describe in more detail for first time users where amongst many the Google Colab button is located and how to find it. Apparently none of the buttons is named "Google Colab". Thank you!

**Comment by sushreebarsa** [comment]
@ng0177 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thank you!

**Comment by ng0177** [comment]
problem solved: the "button" is an active area called `Run in Google Colab`
