### ISSUE TITLE
cannot import name 'anchor_generator_pb2' from 'object_detection.protos'

### ISSUE THREAD

**Issue by N04H8** [tensorflow/tensorflow#56756]
When running a verification script this error outputs: ImportError: cannot import name 'anchor_generator_pb2' from 'object_detection.protos'
I have been stuck at this error for many days and all the solutions haven't worked.
Any help is greatly appreciated.

**Comment by bhack** [comment]
Is this a dup of https://github.com/tensorflow/models/issues/2930 ?

**Comment by tilakrayal** [comment]
Hi @N04H8,
This issue is more suitable for the TensorFlow Models repo. Please post it on the Tensorflow Models repo from [here](https://github.com/tensorflow/models/issues/new/choose). Thank you!
