### ISSUE TITLE
Wrong forward gradient in `tf.autodiff.ForwardAccumulator` for `tf.sign`

### ISSUE THREAD

**Issue by eeDigitalSeal** [tensorflow/tensorflow#56754]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

```shell
Forward-mode auto grad result for `tf.sign` should be `0.0` with input `0.7887528`, but got `None`.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

x = tf.constant([0.7887528],tf.float32)
with tf.GradientTape(persistent=True,) as g:
  g.watch(x)
  res_backward = tf.sign(x)
print(g.jacobian(res_backward,x))

with tf.autodiff.ForwardAccumulator(x,tf.constant([1.],tf.float32)) as acc:
  res_forward = tf.sign(x)
print(acc.jvp(res_forward))
```

### Relevant log output

```shell
tf.Tensor([[0.]], shape=(1, 1), dtype=float32)
None
```
</details>

**Comment by sushreebarsa** [comment]
@chunduriv I was able to replicate the issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/e65e464bd651c8c80af7def50903fd28/56754.ipynb) here. Thank you!

**Comment by cantonios** [comment]
Looks like TF uses `None` to indicate a static compile-time zero gradient for forward accumulation, so these are actually the same.
