### ISSUE TITLE
Error Tensorflow lite model -android studio

### ISSUE THREAD

**Issue by yasminemrad** [tensorflow/tensorflow#56770]
I'm trying to import a tensorflow lite model ( inception V3 model for detecting a lesions in a retinal images) into my android studio. I've followed a tutorial . i got this erreur , i don't know how to solve it .
my input image :
![0f96c358a250](https://user-images.githubusercontent.com/83914766/178984031-ab655b60-d1e8-40bf-b156-74860052fbd7.png)

i got this error 
java.lang.ArrayIndexOutOfBoundsException
            at android.graphics.Bitmap.checkPixelsAccess(Bitmap.java:1706)
            at android.graphics.Bitmap.getPixels(Bitmap.java:1647)
            at com.example.micro_model.MainActivity.classifyImage(MainActivity.java:133)
            at com.example.micro_model.MainActivity$2.onManagerConnected(MainActivity.java:225)
            at com.example.micro_model.MainActivity$1.onClick(MainActivity.java:192)
            at android.view.View.performClick(View.java:6256)
            at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)

here is my code : 

**public class MainActivity extends AppCompatActivity {

    ImageView imageView;
    Button button;

    TextView result;
    int imageSize=299;

    private static final String TAG = "MainActivity";

    static {
        if (OpenCVLoader.initDebug()) {
            Log.d(TAG, "opencv not load");
        } else {
            Log.d(TAG, "opencv loaded: ");
        }
    }

    public void classifyImage(Bitmap image)
    {
        try {
        ConvertedModel model = ConvertedModel.newInstance(getApplicationContext());
        TensorBuffer inputFeature0 = TensorBuffer.createFixedSize(new int[]{1, 299, 299, 3}, DataType.FLOAT32);
        int width =image.getWidth();
        int height =image.getHeight();
        ByteBuffer byteBuffer= ByteBuffer.allocateDirect(4 * imageSize * imageSize * 3 );
        byteBuffer.order(ByteOrder.nativeOrder());
        int [] intValues= new int [imageSize * imageSize];
        image.getPixels(intValues,0,width, 0, 0 , width,height);
        int pixel=0;
            for(int i = 0; i < imageSize; i++){
                for(int j = 0; j < imageSize; j++){
                    int val = intValues[pixel++];
                    byteBuffer.putFloat(((val >> 16) & 0xFF) * (1.f / 1));
                    byteBuffer.putFloat(((val >> 8) & 0xFF) * (1.f / 1));
                    byteBuffer.putFloat((val  & 0xFF) * (1.f / 1));

                }
            }

        inputFeature0.loadBuffer(byteBuffer);

        ConvertedModel.Outputs outputs = model.process(inputFeature0);
        TensorBuffer outputFeature0 = outputs.getOutputFeature0AsTensorBuffer();
            float[] confidence = outputFeature0.getFloatArray();
            int maxPos = 0;
            float maxConfidence = 0;
            for(int i = 0; i < confidence.length; i++){
                if(confidence[i] > maxConfidence){
                    maxConfidence = confidence[i];
                    maxPos = i;
                }
            }
            String[] classes = {"micro","no-micro"};
            result.setText(classes[maxPos]);

        model.close();

    } catch (IOException e) {
        // TODO Handle the exception
    }
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        imageView = findViewById(R.id.imageView);
        Button btn = findViewById(R.id.button);
        Button slc = findViewById(R.id.button2);
        result =findViewById(R.id.result);

        slc.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                if (!OpenCVLoader.initDebug()) {

                    OpenCVLoader.initAsync(OpenCVLoader.OPENCV_VERSION, getApplicationContext(), baseLoaderCallback1);
                } else
                    baseLoaderCallback1.onManagerConnected(LoaderCallbackInterface.SUCCESS);

            }
        });

        Log.e("", "onCreate: image id" + R.id.image);

    }

    /**
     *
     */

    BaseLoaderCallback baseLoaderCallback1;

    {
        baseLoaderCallback1 = new BaseLoaderCallback(this) {
            @Override
            public void onManagerConnected(int status) {
                super.onManagerConnected(status);
                if (status == LoaderCallbackInterface.SUCCESS) {
                   Mat newImage= new Mat();
                    Bitmap img = BitmapFactory.decodeResource(getResources(),R.drawable.prepm);
                    Utils.bitmapToMat(img,newImage);
                    Imgproc.cvtColor(newImage, newImage, Imgproc.COLOR_RGB2BGR);
                    Bitmap bm = Bitmap.createBitmap(newImage.width(), newImage.height(), Bitmap.Config.ARGB_8888);
                    Utils.matToBitmap(newImage, bm);
                    imageView.setImageBitmap(bm);

                    //result.setText(img.channel);
                    //img=Bitmap.createScaledBitmap(img,imageSize,imageSize, false);
                   classifyImage(bm);

            

}

            }
        };
    }
}

**Comment by mohantym** [comment]
Hi @yasminemrad !
Sorry for the late response.  Could you make the changes as below and let us know
```


int w = img.getWidth(); 
int h = img.getHeight();
int[] data = new int[w * h]; //instead of ImageSize use width and height of images input for inference
img.getPixels(data, 0, w, 0, 0, w, h);
```

Attached relevant threads for reference. [1](https://stackoverflow.com/questions/5900185/android-android-graphics-bitmap-checkpixelsaccess-error) , [2](https://www.tabnine.com/code/java/methods/android.graphics.Bitmap/getPixels) 

Thank you!
