### ISSUE TITLE
Error during fit on distributed dataset with multiple GPUs. "ValueError: When providing a distributed dataset, you must specify the number of steps to run."

### ISSUE THREAD

**Issue by pimorandi** [tensorflow/tensorflow#56773]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9

### Custom Code

No

### OS Platform and Distribution

Linux Debian 4.19.194-3

### Python version

3.8.10

### CUDA/cuDNN version

11.7 / 8.3

### GPU model and memory

Tesla V100-PCIE-32GB x2

### Current Behaviour?

```shell
When trying to train a model on multiple GPUs, we get a ValueError at the start of fit method.
The error is caused by the dataset distribution, done through MirroredStrategy and strategy.experimental_distribute_dataset(). If the distribution is removed from the code, no error occurs, but the dataset is not distributed.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

def _parse_function(example):
    _float_feature = tf.io.FixedLenFeature([], tf.float32, default_value=0.0)
    feature_description = {
        'f1': _float_feature,
        'f2': _float_feature,
        'f3': _float_feature,
        'f4': _float_feature,
        'f5': _float_feature,
        'label': tf.io.FixedLenFeature([], tf.int64, default_value=0),
    }
    samples = tf.io.parse_example(example, feature_description)
    label = samples['label']
    features = tf.stack([
            samples['f1'],
            samples['f2'],
            samples['f3'],
            samples['f4'],
            samples['f5']],
            axis=1)
    return (features, label)

gpus = tf.config.list_logical_devices('GPU')
strategy = tf.distribute.MirroredStrategy(gpus)

batch_size_per_replica = 256
batch_size = batch_size_per_replica * strategy.num_replicas_in_sync

train_filename = './training_data.tfrec'
train_dataset = tf.data.TFRecordDataset([train_filename]
        ).batch(batch_size
        ).map(_parse_function)
val_filename = './val_data.tfrec'
val_dataset = tf.data.TFRecordDataset([val_filename]
        ).batch(batch_size
        ).map(_parse_function)

train_dataset = strategy.experimental_distribute_dataset(train_dataset)
val_dataset = strategy.experimental_distribute_dataset(val_dataset)

with strategy.scope():
    mdl = tf.keras.Sequential([
        tf.keras.layers.InputLayer(input_shape=(5,)),
        tf.keras.layers.Dense(5),
        tf.keras.layers.Dense(1, activation='sigmoid')
        ])
    mdl.compile(tf.keras.optimizers.Adam(),
        loss=tf.keras.losses.BinaryCrossentropy())

h = mdl.fit(
        train_dataset, 
        validation_data=val_dataset,
        verbose=0,
        epochs=50,
        batch_size=batch_size,
        )
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "main.py", line 76, in <module>
    h = mdl.fit(
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/data_adapter.py", line 755, in _validate_args
    raise ValueError("When providing a distributed dataset, you must "
ValueError: When providing a distributed dataset, you must specify the number of steps to run.
```
</details>

**Comment by mohantym** [comment]
Hi @pimorandi !
You can add steps_per_epoch in model.fit to resolve this issue.
Attached relevant [thread](https://stackoverflow.com/a/61495834/11530462)  for reference. 
Thank you!

**Comment by pimorandi** [comment]
Thank you for your response @mohantym
I just tried to add the steps_per_epoch argument to the fit method, now it looks like this:

<pre><code>h = mdl.fit(
        train_dataset, 
        validation_data=val_dataset,
        verbose=0,
        callbacks=[tb_callback], 
        epochs=7,
        batch_size=batch_size,
        steps_per_epoch=50
        )
</code></pre>

But the error still occurs:

<pre><code>Traceback (most recent call last):
  File "main.py", line 79, in <module>
    h = mdl.fit(
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/keras/engine/data_adapter.py", line 755, in _validate_args
    raise ValueError("When providing a distributed dataset, you must "
ValueError: When providing a distributed dataset, you must specify the number of steps to run.
</code></pre>

To better give the context I must say that I execute the code with a singularity container, I don't know if this adds any clue.

**Comment by pimorandi** [comment]
Update:

Just found out that also the argument validation_steps needs to be set, now the training starts and does not give any error.

The problem now is that, no matter how many epochs and how many steps I set, the fit method performs only one iteration and then stops without any error.

Any advise on how to debug this?

**Comment by mohantym** [comment]
@pimorandi !
Thanks for the update . Could  you change verbose=o to verbose=1 .
 
It might be happening because of following conditions.

1. You might be using small dataset  or model is going through complete dataset in one swap. ( Reduce the batch size ,decide epochs and other parameter upon that)
2. Proper image processing through augmentation. ( Keras image generator, or layer.augmentation)
3. Model is not robust enough ( use more hidden layers with proper activation function / weights from a Pretrained model)
For debugging , You can use Tensorboard or debugger in model.fit operation through callback to see origin of issue.

You can also use a custom callback which mentions that it won't stop at this epoch or certain accuracy has been achieved.

Attached relevant thread for reference. [1](https://stackoverflow.com/questions/64095558/deep-neural-network-model-stops-learning-after-one-epoch) , [2](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/Callback)

Thank you!

**Comment by pimorandi** [comment]
Thank you for the hint @mohantym !

I have done some experiments changing the steps_per_epoch argument, following are the logs during and after the fit:

Here, steps_per_epoch is set to 10_000 which is a number not related to the actual size of the dataset
```
[2022-07-15 12:40:30] - Starting fit...
Epoch 1/10
10000/10000 - 10s - loss: 0.5705 - val_loss: 0.4478 - 10s/epoch - 1ms/step
[2022-07-15 12:40:41] - Fit completed
[2022-07-15 12:40:41] - Saving history...
[2022-07-15 12:40:41] - Done
```

In this experiment, steps_per_epoch is set to the exact number
```
[2022-07-15 12:48:27] - Starting fit...
Epoch 1/10
131/131 - 10s - loss: 0.9270 - val_loss: 0.6229 - 10s/epoch - 80ms/step
Epoch 2/10
131/131 - 1s - loss: 0.9270 - val_loss: 0.6229 - 676ms/epoch - 5ms/step
[2022-07-15 12:48:38] - Fit completed
[2022-07-15 12:48:38] - Saving history...
[2022-07-15 12:48:38] - Done
```

And here is multiplied by 10
```
[2022-07-15 12:53:20] - Starting fit...
Epoch 1/10
1310/1310 - 11s - loss: 0.4969 - val_loss: 0.4103 - 11s/epoch - 8ms/step
[2022-07-15 12:53:31] - Fit completed
[2022-07-15 12:53:31] - Saving history...
[2022-07-15 12:53:31] - Done
```

The epoch period in these three experiments stays the same even if the number of steps varies a lot.
What's more strange is that only the first epoch is performed even if the total number of epochs is 10.
To further monitor the experiments I used the tensorboard callback, which plotted only one dot in the loss graphs of the scalar sections.

Any idea on this?

**Comment by mohantym** [comment]
Hi @gadagashwini !
Could you please look at this issue.
Thank you!

**Comment by pimorandi** [comment]
Just found out that the datasets have to be able to provide steps_per_epochs * epochs rounds of data. Now the code to create the datasets looks like this:

```
train_filename = './training_data.tfrec'
train_dataset = tf.data.TFRecordDataset([train_filename]
    ).batch(batch_size
    ).map(_parse_function
    ).repeat()

val_filename = './val_data.tfrec'
val_dataset = tf.data.TFRecordDataset([val_filename]
    ).batch(batch_size
    ).map(_parse_function
    ).repeat()
```

With these changes the code works as expected, thank you

**Comment by sketchmind** [comment]
Why not adaptively traverse to the end like ordinary data sets instead of adding a step parameter.
