### ISSUE TITLE
run bazel build tensorflow/examples/label_image/...  fail

### ISSUE THREAD

**Issue by civilmanxx** [tensorflow/tensorflow#5677]
I just sync the **latest code** and build from source.

https://www.tensorflow.org/versions/r0.11/tutorials/image_recognition/index.html

i run **bazel build tensorflow/examples/label_image/...** get error:

ERROR: /home/scopeserver/RaidDisk/tensorflow/tensorflow/examples/label_image/BUILD:10:1: no such package 'tensorflow/contrib/quantization/kernels': BUILD file not found on package path and referenced by '//tensorflow/examples/label_image:label_image'.
ERROR: Analysis of target '//tensorflow/examples/label_image:label_image' failed; build aborted.
INFO: Elapsed time: 0.116s

**Comment by civilmanxx** [comment]
but i run **bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package** with no errors.

**Comment by girving** [comment]
@civilmanxx You said you synced to the latest code, but you linked to 0.11.  Which version are you using?

**Comment by civilmanxx** [comment]
The link points out the source of the cmd, but not for code version.

I want to build the file for single image prediction. the source code is still the latest one.

**Comment by girving** [comment]
@civilmanxx I don't think you're using up to date TensorFlow.  The version of `label_image/BUILD` that I see makes no mention of quantization: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/BUILD

**Comment by civilmanxx** [comment]
yeah, I just check there are 2 quantization related lines in the build file. I do not why, though I pull the latest code.
