### ISSUE TITLE
python implementation of tf.io.gfile.isdir exhibits different behavior than c++ implementation

### ISSUE THREAD

**Issue by krehm** [tensorflow/tensorflow#56774]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.1 (master branch)

### Custom Code

No

### OS Platform and Distribution

RHEL 8.4

### Mobile device

None

### Python version

3.9

### Bazel version

4.2.1

### GCC/Compiler version

8.4.1

### CUDA/cuDNN version

None

### GPU model and memory

None

### Current Behaviour?

```shell
io.gfile.isdir() is exported from function is_directory_v2() in tensorflow/python/lib/io/file_io.py.  It currently traps all filesystem errors and converts them to 'false'.  

However in C++, function IsDirectory() in tensorflow/core/platform/file_system.h documents that only the FAILED_PRECONDITION error should be trapped and converted to false (object exists and is a file), all other filesystem errors like NOT_FOUND and PERMISSION_DENIED should throw an exception.  This makes sense, if an object does not exist or a directory that can't be accessed, it should not be reported to be a file (return of false).  

m.def "IsDirectory" in tensorflow/python/lib/io/file_io_wrapper.c implements the logic documented in IsDirectory(), mapping only FAILED_PRECONDITION to false and throwing all other errors.

The result is that the 'isdir' python API behaves differently than the C++ API.  I think the C++ implementation is the correct one.  

Function list_directory_v2() in the same file is written assuming the current behavior of is_directory_v2(), it assumes all errors will be mapped to false, it will throw NOT_FOUND if the object is actually a file, or if there is a permissions failure on the directory.

Function walk_v2() also assumes the current behavior of all errors being mapped to false, and so a NOT_FOUND or permissions failure will cause the directory item to be reported as a file.

The fix is to remove the exception clause in is_directory_v2() and fix the documentation.  I believe that list_directory_v2() and walk_v2() in the same file also need tweaks to adapt to the isdir behavior change.
```

### Standalone code to reproduce the issue

```shell
From a python test program in tensorflow/io:

# broken, returns false, expected NOT_FOUND
no_file = tf.io.gfile.join(test_root, "nonexistent")
with self.assertRaises(tf.errors.NotFoundError):
    tf.io.gfile.isdir(no_file)

# broken, returns false, expected NOT_FOUND
file_no_parent = tf.io.gfile.join(test_root, "no_parent", "nonexistent")
with self.assertRaises(tf.errors.NotFoundError):
    tf.io.gfile.isdir(file_no_parent)
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@krehm,
To expedite the trouble-shooting process, could you please provide a complete code you are using. Thank you!

**Comment by tilakrayal** [comment]
@krehm,
I was facing an indentation error while executing the given code. Kindly find the gist of it [here](https://github.com/tensorflow/tensorflow/issues/56774). Thank you!

**Comment by krehm** [comment]
@tilakrayal the problem seems to be this web page.  If you click on the "..." for the code and select "Edit", then the code  indentation is correct.   In Edit mode I tried to add more blanks to each line to fix the indentation, but the web page just removes them again.

**Comment by tilakrayal** [comment]
@krehm,
To reproduce the issue, Could you please provide the web page link which you are referring [here](https://github.com/tensorflow/tensorflow/issues/56774#issuecomment-1187422215). It helps to debug the issue. Thank you!

**Comment by krehm** [comment]
https://github.com/tensorflow/tensorflow/issues/56774#issuecomment-1187422215

**Comment by gowthamkpr** [comment]
@krehm Sorry. Can you please attach a colab gist that reproduces the above error. Thanks!

**Comment by krehm** [comment]
https://colab.research.google.com/drive/15zmcH1QGknTwU5Fe2VH0W-pJRHMSHVnZ?usp=sharing

**Comment by gowthamkpr** [comment]
Thank you!!! Am looking into this!!
