### ISSUE TITLE
Using static_rnn error

### ISSUE THREAD

**Issue by panhu** [tensorflow/tensorflow#56786]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 1.14

### Custom Code

Yes

### OS Platform and Distribution

Linux

### Python version

python 3X

### Current Behaviour?

```shell
Hi,
When i use the static_rnn have some issus,my code like this:
main_input = Input(shape=(1, 42),batch_size=1, name='main_input')

tmp = Dense(24)(main_input)

tmp = tf.unstack(tmp,axis=1)
vad_gru_1 = tf.nn.rnn_cell.GRUCell(48)
init_state = vad_gru_1.zero_state(1, dtype=tf.float32)
vad_gru_2,_ = tf.nn.static_rnn(cell=vad_gru_1,inputs=tmp,initial_state=init_state)
```

### Standalone code to reproduce the issue

```shell
The issus is :

TypeError: This layer ("gru_cell_1") takes an `inputs` argument in `call()`, and only the `inputs` argument may be specified as a positional argument. Pass everything else as a keyword argument (those arguments will not be tracked as inputs to the layer).
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
Hi @panhu,
Tensorflow version 1.x not actively supported. Hence, kindly update to the latest stable version 2.9 and let us know if you are facing the same issue. Thank you!

**Comment by panhu** [comment]
Hi, I have a new questions. this is my code:

input_1 = Input(shape=(1, 42),batch_size=1)

tmp = Dense(24)(input_1)

gru_1 = GRU(24, activation='tanh', recurrent_activation='sigmoid', unroll=True, return_sequences=True, name='vad_gru', kernel_regularizer=regularizers.l2(reg), recurrent_regularizer=regularizers.l2(reg))(tmp)

gru_2 = GRU(48, activation='relu', recurrent_activation='sigmoid',unroll=True, return_sequences=True, name='noise_gru', kernel_regularizer=regularizers.l2(reg), recurrent_regularizer=regularizers.l2(reg))(gru_1)

gru_3=GRU(96, activation='tanh', recurrent_activation='sigmoid',unroll=True, name='denoise_gru', kernel_regularizer=regularizers.l2(reg), recurrent_regularizer=regularizers.l2(reg))(gru_2)

denoise_output = Dense(10, activation='sigmoid', name='denoise_output')(gru_3)

The issus is:
i use "unroll=True" in GRU to unrolled my model, and my file of h5 just 1.3M after training,but when i want ro convert tflite,the meoery is not enough(my memory is 90G),that's weird.

**Comment by tilakrayal** [comment]
@panhu,
I was facing different error while trying to execute the given code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/439803868a5afa046f9176d868fc1ea7/untitled444.ipynb).
