### ISSUE TITLE
GPU much slower than CPU for text processing using tensorflow-macos

### ISSUE THREAD

**Issue by vgkortsas** [tensorflow/tensorflow#56782]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

TF 2.8

### Custom Code

Yes

### OS Platform and Distribution

MacOS 12.4

### Python version

3.8

### Current Behaviour?

```shell
I am trying to run the notebook Text classification with an RNN https://www.tensorflow.org/text/tutorials/text_classification_rnn from the TensorFlow website.
The code has LSTM and Bidirectional layers

Although I get the message "Plugin optimizer for device_type GPU is enabled", the GPU is not used.

When the GPU is “enabled”, although not used,  the time is 56 minutes/epoch.
When I am only using the CPU is 264 seconds/epoch.

I face the same issue when trying to run Transformer model for language understanding https://www.tensorflow.org/text/tutorials/transformer

I am using MacBook Pro 14 (10 CPU cores, 16 GPU cores) and TensorFlow-macos 2.8 with TensorFlow-metal 0.5.0.  I face the same problem for TensorFlow-macos 2.9.2 too.

My environment has:
tensorflow-macos          2.8.0  
tensorflow-metal          0.5.0 
tensorflow-text           2.8.1  
tensorflow-datasets       4.6.0                   
tensorflow-deps           2.8.0                         
tensorflow-hub            0.12.0                      
tensorflow-metadata       1.8.0                    
                   
When I am using CNNs the GPU is fully enabled and 3-4 times faster than when only using the CPU. 
```

### Standalone code to reproduce the issue

```shell
The codes that I have observed the issue are from the TensorFlow website:
https://www.tensorflow.org/text/tutorials/text_classification_rnn
and
https://www.tensorflow.org/text/tutorials/transformer
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@gadagashwini,
I tried to execute the `Text classification with an RNN` on colab with both gpu, cpu and was able to execute without any issues. Kindly find the [gist](https://colab.research.google.com/gist/tilakrayal/d5d46acc7f223cd817d06cc399eff4d5/cpu-text_classification_rnn.ipynb) of it [here](https://colab.research.google.com/gist/tilakrayal/e71c437effaa7fa6615b0c0bd001526a/text_classification_rnn.ipynb).

**Comment by gowthamkpr** [comment]
@vgkortsas GPU kernels are way more slower than CPU cores but the main advantage of GPU is that you can run thousands of threads simultaneously. On CPU you're limited by number of cores and besides even if M1 has 8 cores only 4 of them can work simultaneously. Please take a look at the explanation [here](https://stackoverflow.com/questions/70653251/why-gpu-is-3-5-times-slower-than-the-cpu-on-apple-m1-mac)

**Comment by vgkortsas** [comment]
@gowthamkp
Thank you very much for your response! I am aware of the post in StackOverflow.  I have some questions/comments:

1. Did you have the chance to run the Text classification with an RNN in an M1-based MacBook and did you also observe what I saw?
2. When running the Text classification with an RNN, the GPU is not fully utilized
3. I do not see the same issue when I run a notebook with CNNs. The GPU is fully utilized and is 3-4 times faster then the CPU. 
4. In the case of sequence models, when I am using the GPU it takes more than 1 hour/epoch, while when I am using the CPU only it takes around 250 sec/epoch. That is really not expected.
5. I do not see the same issue when I run the notebooks using NVIDIA GPUs or the Colab. 

All these make me to believe that there must be  a problem with the tensorflow-metal.

**Comment by gowthamkpr** [comment]
@vgkortsas I agree. This issue is specific to M1-based MacBook. Please post this issue [here](https://github.com/apple/tensorflow_macos/issues?q=is%3Aissue+is%3Aclosed). Thanks!

**Comment by vgkortsas** [comment]
@gowthamkpr 
Thanks for your response! The repository in the link you attached has been archived by the owner and is now read-only. Is there any other link I can post MacOS related TensorFlow issues?
