### ISSUE TITLE
Support INT8 for tf.split and tf.one_hot

### ISSUE THREAD

**Issue by olipinski** [tensorflow/tensorflow#56785]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Windows 10 Enterprise 20H2

### Current Behaviour?

```shell
Tensorflow will not work with int8 tensors when using one_hot or splitv.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

int8_tensor = tf.constant([[1, 2],
                           [3, 4],
                           [5, 6]], dtype=tf.int8)
try:
    tf.one_hot(int8_tensor, 3)
except Exception as e:
    print(e)
```

### Relevant log output

```shell
tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'Tlen' of int8 is not in the list of allowed values: int32, int64
	; NodeDef: {{node SplitV}}; Op<name=SplitV; signature=value:T, size_splits:Tlen, split_dim:int32 -> output:num_split*T; attr=num_split:int,min=1; attr=T:type; attr=Tlen:type,default=DT_INT64,allowed=[DT_INT32, DT_INT64]> [Op:SplitV] name: split

tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'TI' of int8 is not in the list of allowed values: uint8, int32, int64
	; NodeDef: {{node OneHot}}; Op<name=OneHot; signature=indices:TI, depth:int32, on_value:T, off_value:T -> output:T; attr=axis:int,default=-1; attr=T:type; attr=TI:type,default=DT_INT64,allowed=[DT_UINT8, DT_INT32, DT_INT64]> [Op:OneHot]
```
</details>

**Comment by sushreebarsa** [comment]
@chunduriv I was able to replicate the issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/4ad5c08f98c653028781b70dc052470c/56785.ipynb#scrollTo=cd0tSbHbFvRv) here. Thank you!

**Comment by cantonios** [comment]
@olipinski why do you need `int8` support?

We can easily add it, but doing so increases TF's already massive binary size.  For this reason, we try to keep registrations minimal.  Will casting to one of the supported types work for you, or are you actually dealing with very large datasets that `int8` is actually required?

**Comment by olipinski** [comment]
@cantonios I wanted `int8` support because I am using a dynamically generated dataset, which for decreasing memory usage uses `int8`. So, I think overall support for `int8` would be useful for smaller/more efficient models.

**Comment by cantonios** [comment]
Do you have a real use-case with proven benefit?  Yes, generally it can lead to smaller memory footprints.  But we need to balance any potentially benefit with the overall overhead of the TF binary package.  Our tensorflow pip size is capped, so adding more registrations for some ops here may mean we can't register other ops while staying under the cap size.

**Comment by olipinski** [comment]
Other than the memory footprint, personally, I would not use it for anything else. A use-case that I could see is for quantised networks and embedded devices, but if the addition of `int8` is unfeasible due to binary size, then feel free to close the issue!

**Comment by cantonios** [comment]
It's not infeasible, I'm just asking if you have a real use-case where the workaround is a significant bottleneck.  If casting back-and-forth works for you and doesn't significantly slow down your model, then that is our preference.  We need to do a cost-benefit analysis to justify these additional registrations (at least in the near-term), so we need something more than a hypothetical savings.

**Comment by olipinski** [comment]
Sorry, I meant if it is not desirable to add it for a single use case of reducing memory consumption. I guess the main reason to do that would be for any local testing of models, which is what my issue was about. I cannot run my models locally, as they are too big in memory usage. 

As for casting — I'm using Ray, so all the code where I would have to cast it back and forth is not really accessible, without some major changes.

Hope this is clearer!

**Comment by cantonios** [comment]
@olipinski Alright, I can buy that.  Do you want to submit an MR to enable them?

**Comment by olipinski** [comment]
@cantonios I have made the pull request - #57056
