### ISSUE TITLE
Android OTG camera access

### ISSUE THREAD

**Issue by Sanjay2802** [tensorflow/tensorflow#56797]
How to use external OTG camera for object detection in Android ,please help me to do as soon as possible

**Comment by mohantym** [comment]
Hi @Sanjay2802 !
Could you check this external thread on [USB camera](https://source.android.com/devices/camera/external-usb-cameras). Attaching relevant thread for reference. [1](https://stackoverflow.com/questions/57846505/accessing-a-usb-camera-using-android-camera2-api), [2](https://github.com/jiangdongguo/AndroidUSBCamera).  
Thank you!

**Comment by Sanjay2802** [comment]
It's just a simple thing ,refer 
  https://github.com/quantum6/Android-USB-OTG-Camera

How to implement and use in tensorflow input ,please help me because it's something more important for me ..

**Comment by Sanjay2802** [comment]
It's just changing fragment , try...

**Comment by mohantym** [comment]
@Sanjay2802 !

Could you post this on TF Forum. 

Thank you!

**Comment by mohantym** [comment]
Hi @Sanjay2802 !
Community is more specific  to Tensorflow/Deep learning and responsive in [TF Forum](https://discuss.tensorflow.org/). Also got a [lead](https://github.com/google/mediapipe/issues/3439#issuecomment-1173577790) from mediapipe for your reference. 

Thank you!

**Comment by sachinprasadhs** [comment]
Hi, I found implementation for Raspberry Pi which should work for USB webcam as well. Please refer this https://www.digikey.com/en/maker/projects/how-to-perform-object-detection-with-tensorflow-lite-on-raspberry-pi/b929e1519c7c43d5b2c6f89984883588.
For additional questions as suggested above, please post it in TF Forum and Stackoverflow which is more relevant forum for these kind of questions. Thanks!
