### ISSUE TITLE
Android use a view as input 

### ISSUE THREAD

**Issue by Sanjay2802** [tensorflow/tensorflow#56798]
How to use a view as input for tensorflow detection instead of camera ? Please help as soon as possible

**Comment by mohantym** [comment]
Hi @Sanjay2802 !
I was going to suggest input as change of state coming from views but it might not work as you need images or videos for image detection. Could you clarify how are you intending to use [views](https://developer.android.com/reference/android/view/View) as input . 
Thank you!

**Comment by Sanjay2802** [comment]
I obtained external USB camera through a view ,so now how to inflate to the fragment

**Comment by mohantym** [comment]
@Sanjay2802 !

Could you comment there in [#56797](https://github.com/tensorflow/tensorflow/issues/56797) for usage of External USB Camera .   I am not sure on using views as input for object detection .Please post on Forum for further assistance . 

Thank you!

**Comment by gowthamkpr** [comment]
@Sanjay2802 Where did you post this issue? Did you post it in tf forum and stackoverflow? Thanks!
