### ISSUE TITLE
TFlite GPU delegate crash on Movenet

### ISSUE THREAD

**Issue by tempstudio** [tensorflow/tensorflow#56795]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.0

### Custom Code

No

### OS Platform and Distribution

Android 12

### Mobile device

Galaxy Fold

### Current Behaviour?

```shell
Creating a TFLite interpreter with the movenet model here https://tfhub.dev/google/movenet/singlepose/lightning/4 with the TFLite GPU delegate crashes immediately.

Using the NNAPI delegate does not crash.
```

### Standalone code to reproduce the issue

```shell
Construct an interpreter with the movenet model and specify GPU Delegate V2 in the interpreter options.
```

### Relevant log output

_No response_</details>

**Comment by madhavarora2002** [comment]
hi @impjdi ,

Same issue, attaching the error log before. **This has been bugging for a while now, will appreciate your help on it!**

> TFLite Warning: Following operations are not supported by GPU delegate:
> ARG_MAX: Operation is not supported.
> CAST: Not supported Cast case. Input type: UINT8 and output type: FLOAT32
> CONCATENATION: OP is supported, but tensor type/shape isn't compatible.
> DEQUANTIZE: 
> FLOOR_DIV: OP is supported, but tensor type/shape isn't compatible.
> GATHER_ND: Operation is not supported.
> MUL: OP is supported, but tensor type/shape isn't compatible.
> PACK: OP is supported, but tensor type/shape isn't compatible.
> RESHAPE: OP is supported, but tensor type/shape isn't compatible.
> SUB: OP is supported, but tensor type/shape isn't compatible.
> 97 operations will run on the GPU, and the remaining 200 operations will run on the CPU.
> UnityEngine.Debug:LogWarning (object)
> TensorFlowLite.ErrorReporter:OnErrorReporter (intptr,string,intptr) 
> TensorFlowLite.Interpreter:.ctor (byte[],TensorFlowLite.InterpreterOptions) 
> TensorFlowLite.BaseImagePredictor`1<sbyte>:.ctor (string,TensorFlowLite.BaseImagePredictor`1/Accelerator<sbyte>)
> TensorFlowLite.MoveNet.MoveNetSinglePose:.ctor (TensorFlowLite.MoveNet.MoveNetSinglePose/Options) (at Assets/MoveNet/MoveNetSinglePose.cs:26)
> MoveNetSinglePoseSample:Start () (at Assets/MoveNet/MoveNetSinglePoseSample.cs:37)

**Comment by impjdi** [comment]
Hm, I'm not too familiar with MoveNet and thus don't know all the ops involved in it, but a short summary:

ARG_MAX: don't know what it does =/
CAST: we generally don't do CAST, your network needs to be in FP16 or FP32.
CONCAT, FLOOR_DIV, MUL, PACK, RESHAPE, SUB: need more details to tell what's going on
DEQUANT: is this a proper floating point model, or a quantized model?  I'm not familiar with int quantization or whether we support it (through some magic through TFLite)
GATHER_ND: we have never supported it and don't have immediate plans to do so.

I know BlazePose works with the GPU delegate.  Can you give that model a try?

**Comment by tempstudio** [comment]
On the topic of movenet vs blazepose:
Blazepose runs at ~30FPS with NNAPI and ~45FPS with GPU
Movenet runs at ~40FPS with NNAPI and crashes with GPU

So we should be able to get ~60FPS with Movenet and GPU, but we cannot.

**Comment by madhavarora2002** [comment]
@tempstudio 
Did you try Movenet (with GPU) in Android Studio?

**Comment by madhavarora2002** [comment]
@impjdi , can we get the team who developed movenet to look into this? 
This issue is preventing it's usage with gpu on android!

**Comment by yangcheng** [comment]
> 

That's great news, is there an issue I can subscribe to?

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

**Comment by whereareu** [comment]
In the demo for android, low Fps maybe of Bitmap created frequently. It's big space to optimize by user.
