### ISSUE TITLE
Build failed in Android Studio

### ISSUE THREAD

**Issue by Yoline777** [tensorflow/tensorflow#56801]
Tensorflow is a great work. I want to study arm64 computation from it. What is a good IDE to read TensorFlow Source Code. I try to build it with cmake in Android Studio. How to fix the error?
`Execution failed for task ':lite:configureCMakeDebug'.
> [CXX1402] /Users/yoline/AndroidStudioProjects/TFLite_Src/lite/src/main/cpp/CMakeLists.txt debug|arm64-v8a : Target all_microkernels::@80588a722c29e322520c produces multiple outputs /Users/yoline/AndroidStudioProjects/TFLite_Src/lite/.cxx/Debug/482v1h6t/arm64-v8a/_deps/xnnpack-build/CMakeFiles/all_microkernels.dir/src/f16-f32-vcvt/gen/vcvt-scalar-x1.c.o, /Users/yoline/AndroidStudioProjects/TFLite_Src/lite/.cxx/Debug/482v1h6t/arm64-v8a/_deps/xnnpack-build/CMakeFiles/all_microkernels.dir/src/f16-f32-vcvt/gen/vcvt-scalar-x2.c.o,`

**Comment by mohantym** [comment]
Hi @Yoline777 !

Could you confirm that you have followed instructions from the [document](https://www.tensorflow.org/lite/guide/build_cmake_arm#build_for_aarch64_arm64). Please share your changes for further assistance. 

Thank you!

**Comment by mohantym** [comment]
Hi @sachinprasadhs !

Could you please look at this issue.

Thank you!

**Comment by sachinprasadhs** [comment]
@Yoline777 , Could you please follow the steps from the document [here](https://www.tensorflow.org/lite/android/lite_build) for the android build.

**Comment by Yoline777** [comment]
@sachinprasadhs I tried this method and it builds successfully. But I want to put compile and call together so I can learn tflite framework better with breakpoints and code jumps.

**Comment by pkgoogle** [comment]
Hi @Yoline777, it seems like your issue is resolved, if you have no more open items please feel free to close the issue as completed.
