### ISSUE TITLE
openCL delegate generates '0' and 'random' values with 'tf.stack'

### ISSUE THREAD

**Issue by Bahar-BM** [tensorflow/tensorflow#56808]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.1, nightly version

### Custom Code

No

### OS Platform and Distribution

Android

### Mobile device

tested on Snapdragon 888, 865

### Current Behaviour?

```shell
Our models with 'tf.stack' ('Pack' in the tflite version) nodes generate wrong results with the openCL delegate. Our experiments show that the output of a 'Pack' node in a tflite model contains lots of 'zeros' and random values when we use openCL delegate. This issue does not happen with other delegates like XNNPACK.
This issue is very similar to the issue that we reported before here:
https://github.com/tensorflow/tensorflow/issues/56732
```

### Standalone code to reproduce the issue

```shell
We have implemented a small tool to reproduce the mentioned issue with the 'tf.stack' node. Here is the link to the repository:
https://github.com/Bahar-BM/tflite-test
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @Bahar-BM !

Does it resolve in this [commit ](https://github.com/tensorflow/tensorflow/commit/56a417633249bef47f94b2754687731e228758d6)too?

Thank you!

**Comment by roserg** [comment]
Hi, can you check it with this commit:
https://github.com/tensorflow/tensorflow/commit/61014f655a18c7de906ad42cb4d95de8252ab0f5

**Comment by roserg** [comment]
If you want to use only GPU delegate, I would recommend to use explicit 4d shapes everywhere. 
Internally every shape converted to 4d shape(and no support of 5d or higher) for GPU delegates.
If you will use 4d explicitly you can omit many problems/issues that can be with non-4d shapes.

**Comment by Bahar-BM** [comment]
Hello @mohantym and @roserg!
The new commit ([61014f6](https://github.com/tensorflow/tensorflow/commit/61014f655a18c7de906ad42cb4d95de8252ab0f5)) has resolved my issue with `tf.stack`. Thank you!
Working with explicit 4d shapes everywhere is not always possible, because in some models we have to add multiple reshape nodes in the model structure and it compromises the performance which is very important for us.
