### ISSUE TITLE
TFlite android inference produces slightly different results for the same input, is it normal?

### ISSUE THREAD

**Issue by catqaq** [tensorflow/tensorflow#56818]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.3.0

### Custom Code

Yes

### OS Platform and Distribution

windows10

### Mobile device

android

### Python version

3.6

### Bazel version

4.2.1

### Current Behaviour?

```shell
I use tflite android api to get sentence embeddings from my tflite model.
`Map<Integer, Object> outputs = new HashMap<>();
outputs.put(0, embeddings);
tflite.runForMultipleInputsOutputs(new Object[]{inputIds, attentionMask}, outputs);`
TFlite android inference produces slightly different results for the same input, is it normal? What causes the small differences？
query: -0.03889307#-0.20992874#-0.012840451...
query: -0.038892966#-0.20992874#-0.012840495...
query: -0.03889298#-0.20992877#-0.012840421...
```

### Standalone code to reproduce the issue

```shell
The code is inconvenient to share, I just want to know if this phenomenon is normal? If it is not normal, is there a way to avoid it?
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @catqaq !

Could you give it a try in Python 3.7/3.8 (Python 3.7 minimum version now) , Bazel 5.0.0 and TF 2.9 and let us know whether the issue still persists.

Thank you!

**Comment by catqaq** [comment]
Hi, @mohantym, sorry for replying so late. I follow your demo code to get output from tflite model. Is there anything to related with float64?
`float[][] embedding = new float[1][64];
Map<Integer, Object> outputs = new HashMap<>();
outputs.put(0, embeddings);
tflite.runForMultipleInputsOutputs(new Object[]{inputIds, attentionMask}, outputs);`

As for your advice about newer version, I will try it later.

**Comment by catqaq** [comment]
About newer versions, I tried python3.7 - tf 2.8 - bazel4.2.1,  the issue still persists. I can't user newer bazel limited by network issues.

**Comment by mohantym** [comment]
No @catqaq !
Just guessed  the datatype from your output . Yes! Please test with Python 3.7/3.8 , Bazel 4.2.1 and TF 2.7 and let us know.
Thank you!

**Comment by catqaq** [comment]
OK, I'll test Python 3.7, Bazel 4.2.1 with several tf versions, but the issue still persists. The precision of float is 6~7 significant digits, I found that the diff generally occurs after 1e-6（after 6 decimal places). I feel like this is more of a float precision issue than a tflite bug( but I can't find **any related issues on tflite float precision**). Anyway, this non-deterministic problem is really troublesome.

**Comment by mohantym** [comment]
@catqaq !
Thanks for the update.

@sachinprasadhs ! Could you please look at this issue.

**Comment by sachinprasadhs** [comment]
The floating point precision error after 6~7 decimal points is expected, for the result to be deterministic, you can round off the value till 5 digits if that works for you.

**Comment by catqaq** [comment]
@sachinprasadhs Hi, Is this really a floating point precision issue? I‘m not sure, because I don't see a similar problem reported in tflite. Anyway, I'll try to round off the value. Thank you!

**Comment by haozha111** [comment]
is there any random ops in your model? Does your model use flex delegate?

**Comment by catqaq** [comment]
@haozha111 Hi, my model does not use flex delegate. And my model is actually a tiny bert model, is there any random ops will be keep in tiny-bert.tflite? like dropout op will be masked in tflite model?

**Comment by haozha111** [comment]
Hi, @catqaq ,

Usually TF Lite model should produce exactly the same results with the same input data, such a small numeric difference should not be expected generally. This could happen if your model contains stateful ops. One thing you can try is, try create a new TF Lite interpreter and then just do one inference with the same data. And repeat this for a couple times (Rather than using the same interpreter instance for multiple invocations in a row). Let me know if you still see the numeric differences.
