### ISSUE TITLE
TF should use protobuf 4

### ISSUE THREAD

**Issue by celestinoxp** [tensorflow/tensorflow#56815]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Windows 11

### Python version

python 3.9.12

### Current Behaviour?

```shell
tensorflow 2.9.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.21.2 which is incompatible.

Tensorflow should update this requirement!
```

### Standalone code to reproduce the issue

```shell
pip install <packages>
```

### Relevant log output

```shell
tensorflow 2.9.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.21.2 which is incompatible.
```
</details>

**Comment by mihaimaruseac** [comment]
For future: please use descriptive titles.

Regarding this issue: there is a big ABI/API breakage with protobuf 4 and TF cannot upgrade due to segfaults in Windows caused by ODR violations. @learning-to-play is working on `cc_shared_library` support and migration past these to then upgrade protobuf

**Comment by chunduriv** [comment]
@celestinoxp,

>tensorflow 2.9.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.21.2 which is incompatible.

Protobuf 4.0 is incompatible with TF. For more details please take a look at https://github.com/tensorflow/tensorflow/issues/56815#issuecomment-1189277185 by @mihaimaruseac.

Thank you.

**Comment by mihaimaruseac** [comment]
Implemented in https://github.com/tensorflow/tensorflow/commit/84f40925e929d05e72ab9234e53c729224e3af38
