### ISSUE TITLE
Different result in tflite conversion

### ISSUE THREAD

**Issue by touristourist** [tensorflow/tensorflow#56820]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.5.0

### 2. Code

![image](https://user-images.githubusercontent.com/28351316/179805179-ed562a87-0bbd-4ca7-9e35-74583cc0b2f8.png)

I use the function above to convert TF fake quantize model to 8 bit tflite model. When I set time=True, which means input shape equals [1, 360, 640, 3], the tflite model in netron is below. It's the right model I want.

![right](https://user-images.githubusercontent.com/28351316/179800350-1673c16d-9491-4d84-ae72-fb09dc626876.png)

But when I set input shape=[1,None,None,3], the converted tflite shows below. It's strange that there are some unexpected op above bilinear upsample op. I found a model performance degradation when I convert the tflite model below, So I want to know how the difference comes. Thanks!

![wrong](https://user-images.githubusercontent.com/28351316/179800787-8103799c-1be3-4378-8b0c-915dfdb4688c.png)

**Comment by mohantym** [comment]
Hi @touristourist!

Thanks for reporting this bug.

But Dynamic shape, batch size  and Tensors are not supported yet . 
If it converts to a lite model, It will probably throw error during inference.

Thank you!

**Comment by touristourist** [comment]
> Hi @touristourist!
> 
> Thanks for reporting this bug.
> 
> But Dynamic shape, batch size and Tensors are not supported yet . If it converts to a lite model, It will probably throw error during inference.
> 
> Could you confirm the same in 2.8/2.9 version too. Please post a minimal stand alone code as Colab gist to replicate this issue.
> 
> Thank you!

OK, thanks for your reply, I will try it later. Do you mean Dynamic Tensors are not supported for all the OPs or just not for Upsampling2D(ResizeBilinear)? If I remove Upsamling2D, can I use Dynamic Tensors with the rest OPs?

**Comment by mohantym** [comment]
@touristourist !
Dynamic tensors are not supported for any op. 
Thank you!

**Comment by mohantym** [comment]
Ok @touristourist 
Thanks for update. @sachinprasadhs ! Could you please look at this issue.

**Comment by mohantym** [comment]
@touristourist !
Could you please put those screenshots in the template or provide a Colab gist. It is bit easier to replicate those issues that way.

**Comment by sachinprasadhs** [comment]
This could be the reason, could you please  train FP32 model then do PTQ-tflite conversion and see if you get satisfactory result.

> ![image](https://user-images.githubusercontent.com/28351316/181025981-36d6fec2-c0f9-4291-9a85-c7503bb05545.png)
> 
> Hi, I found this comment in tensorflow_model_optimization, which may interpret the reason for performance degradation in QAT to tflite conversion. So, is there any other solution to convert the bilinear upsampling model with less performance degradation? Should I first train FP32 model then do PTQ-tflite conversion?
