### ISSUE TITLE
Tensorflow add new device runtime like cuda?

### ISSUE THREAD

**Issue by wangzy0327** [tensorflow/tensorflow#56839]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.6.0

### Custom Code

Yes

### OS Platform and Distribution

ubuntu 18.04

### Bazel version

3.7.2

### GCC/Compiler version

7.5

### CUDA/cuDNN version

11.2

### Current Behaviour?

```shell
how to develop custom tensorflow code in new device runtime?
where are some resources about secondary development documentation?
```

### Standalone code to reproduce the issue

```shell
no
```

### Relevant log output

_No response_</details>

**Comment by chunduriv** [comment]
@wangzy0327,

Can you please elaborate about your issue and please specify the use cases. Thank you.

**Comment by wangzy0327** [comment]
> @wangzy0327,
> 
> Can you please elaborate about your issue and please specify the use cases? Thank you.

I want to add new device runtime sycl-tool-chain[https://github.com/intel/llvm/blob/sycl/sycl/doc/GetStartedGuide.md#build-dpc-toolchain-with-support-for-nvidia-cuda] base tensorflow framework. 
Are there some document resource about tensorflow adding new device runtime for developer?

**Comment by sachinprasadhs** [comment]
Hi, I don't think we have any documentations for the above configurations. 
You can find the details to build from source from the document here  https://www.tensorflow.org/install/source and see if any of the section helps you.
