### ISSUE TITLE
Different outputs at inference when different versions of TensorFlow are used to perform quantization during conversion to .tflite

### ISSUE THREAD

**Issue by farmaker47** [tensorflow/tensorflow#56832]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colaboratory
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): Issue with various versions of TenrorFlow

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

#### Option A: Reference colab notebooks

1)  Reference [TensorFlow Model Colab](https://colab.research.google.com/gist/ymodak/e96a4270b953201d5362c61c1e8b78aa/tensorflow-datasets.ipynb?authuser=1): Demonstrate how to build your TF model.
2)  Reference [TensorFlow Lite Model Colab](https://colab.research.google.com/gist/ymodak/0dfeb28255e189c5c48d9093f296e9a8/tensorflow-lite-debugger-colab.ipynb): Demonstrate how to convert your TF model to a TF Lite model (with quantization, if used) and run TFLite Inference (if possible).

```
(You can paste links or attach files by dragging & dropping them below)
- Provide links to your updated versions of the above two colab notebooks.
- Provide links to your TensorFlow model and (optionally) TensorFlow Lite Model.
```

#### Option B: Paste your code here or provide a link to a custom end-to-end colab

Perform conversion and Dynamic range quantization:
```
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_quant_model = converter.convert()
```
Perform inference with the generated model
```
import numpy as np
import cv2
from matplotlib import pyplot as plt


# load in image, resize and normalize
fn = '/content/114.jpeg'
img = cv2.imread(fn)[..., ::-1]
img = cv2.resize(img, (256, 128), interpolation=cv2.INTER_AREA)
inputs = (img.astype(np.float32) / 127.5) - 1.
inputs = np.expand_dims(inputs, 0)


# load TFLite model and set params
mod_path = '/content/model_converted.tflite'
interpreter = tf.lite.Interpreter(model_path=mod_path)
interpreter.allocate_tensors()
input_index = interpreter.get_input_details()[0]["index"]
output_index = interpreter.get_output_details()[0]["index"]

# run inference
interpreter.set_tensor(input_index, inputs)
interpreter.invoke()
borderi = interpreter.get_tensor(output_index)
print(type(borderi))

border = list(borderi[0])
print(border)
```

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

- The issue here can be reproduced by using different versions of TensorFlow to convert and quantize the model. Check below for the versions and the results:

Version 2.3 result:
[[0.3330792  0.27843374]
 [0.40366906 0.250709  ]
 [0.48135388 0.24179175]
 [0.5636318  0.24119636]
 [0.6400584  0.2480475 ]
 [0.6005912  0.3724205 ]
 [0.5628794  0.3754966 ]
 [0.48778155 0.40332332]
 [0.3985254  0.3810564 ]
 [0.34678322 0.3575413 ]
 [0.52223235 0.3023828 ]
 [0.5825569  0.30930337]]

Version 2.4 result:
[[0.3341408  0.28175732]
 [0.40583873 0.25392115]
 [0.48184934 0.24735713]
 [0.55686283 0.2499246 ]
 [0.63230157 0.26033315]
 [0.6035842  0.37444225]
 [0.5606153  0.37672445]
 [0.4867457  0.39785832]
 [0.4086929  0.38542932]
 [0.35176694 0.3601483 ]
 [0.51643425 0.31068143]
 [0.5710402  0.31282204]]

Version 2.5 result:
[[0.3330438  0.28234786]
 [0.40442967 0.25366008]
 [0.48140293 0.24701637]
 [0.55590045 0.24874169]
 [0.63329554 0.2600382 ]
 [0.60310024 0.373787  ]
 [0.56032354 0.37653822]
 [0.48664606 0.39639705]
 [0.40806895 0.38597408]
 [0.3511423  0.35862684]
 [0.5150639  0.30999073]
 [0.57102746 0.31190303]]

Version 2.7 result:
[[0.3341408  0.28175732]
 [0.40583873 0.25392115]
 [0.48184934 0.24735713]
 [0.55686283 0.2499246 ]
 [0.63230157 0.26033315]
 [0.6035842  0.37444225]
 [0.5606153  0.37672445]
 [0.4867457  0.39785832]
 [0.4086929  0.38542932]
 [0.35176694 0.3601483 ]
 [0.51643425 0.31068143]
 [0.5710402  0.31282204]]

Version 2.8.2 result:
[[0.33199123 0.28214237]
 [0.40430748 0.2546782 ]
 [0.48055232 0.24780622]
 [0.555871   0.2505081 ]
 [0.63259435 0.2612171 ]
 [0.6028995  0.3754816 ]
 [0.5595857  0.37812153]
 [0.48534507 0.397737  ]
 [0.40594587 0.38545215]
 [0.3501406  0.35963872]
 [0.5159489  0.31203791]
 [0.57132494 0.31412107]]

IMPORTANT= This happens only when we apply Dynamic range quantization. Without quantization the outputs are the same for the different versions of TensorFlow and they are:
[[0.33383682 0.28292328]
 [0.40593028 0.2521686 ]
 [0.4803361  0.24693146]
 [0.5551163  0.24844697]
 [0.63013196 0.26205748]
 [0.60453784 0.37450537]
 [0.55849314 0.37527987]
 [0.4858575  0.3947457 ]
 [0.4057536  0.38485324]
 [0.3498182  0.35843956]
 [0.51736057 0.30842167]
 [0.5722974  0.31274813]]

So the question here is why the quantization algorithm is different at the different versions of TensorFlow and in the end which one is correct?

### 4. (optional) RNN conversion support
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by lu-wang-g** [comment]
@karimnosseir may you please help take a look at this issue? Many thanks!

**Comment by mohantym** [comment]
Hi @farmaker47 !

With Option A, I was getting a lot of attribute error saying "AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no copy/astype' initially. So I made changes after merging both model and lite notebooks and got new errors for int8 quantization . But the results in other quantization looked same.  Attached gist in [2.8,](https://colab.research.google.com/gist/mohantym/d44250cee80bd3838a7cef423854af3f/tensorflow-datasets.ipynb#scrollTo=YGJbXdLJPzGp), [2.9](https://colab.research.google.com/gist/manas1988/6a1284207b7d8fb3afa23d0f6237ac77/tensorflow-datasets.ipynb#scrollTo=YGJbXdLJPzGp) and [nightly](https://colab.research.google.com/gist/manas1988/a3b0c1ca226b86cc5a9e0b60983ec7f6/tensorflow-datasets.ipynb#scrollTo=efnCiPO8N8j6) for reference.

Thank you!

**Comment by karimnosseir** [comment]
Jaesung can you please check this

**Comment by abattery** [comment]
I suspect even for the TFLite floating point conversion, these kind of small numerical differences can be found.

There are many reasons to introduce such behaviors due to 1) conversion logic change 2) kernel logic change and so on. It is really impossible to guarantee the numerical exactness. For example, the numerical exactness is hard to achieve in (a+b) * c != a*c + b*c.

Those differences seem minor and looks like the behavior is working as intended.

**Comment by farmaker47** [comment]
Hi @karimnosseir 
I see that you are mentioning something about the option A but I did not provide a colab to check, I just put reference code at option B to show you how simple I convert and perform inference. Apologies for that. I should have deleted the A fields.

Based on @abattery answer I understand the behavior. But I am asking both of you since I see that the results at versions 2.4 and 2.7 are exactly the same...which version of TensorFlow to use to quantize the model during conversion?? Or just upgrade TensorFlow every time there is one so I get the latest results?

**Comment by sachinprasadhs** [comment]
@farmaker47 , It is always preferred to use the latest stable version, we as Tensorflow constantly improve the library with bug fixes and added features. Even though you notice the same behavior in both the mentioned versions above, it is suggested to use the latest stable version. Hope this clarifies your doubt. Thanks!

**Comment by farmaker47** [comment]
Thanks you @sachinprasadhs . I will use the latest version from now on. You can close the issue.
