### ISSUE TITLE
Tensorflow lite examples Java 

### ISSUE THREAD

**Issue by Sanjay2802** [tensorflow/tensorflow#56838]
Where is tensorflow object detection app java project, only kotlin is present

**Comment by mohantym** [comment]
Hi @Sanjay2802 !
If you run the [Java example ](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/objectdetection) on Android studio version 4.1 (Suggest Chipmunk )or above , It will ask to install kotlin dependency and convert to java automatically.

**Comment by Sanjay2802** [comment]
No , can you show me how to do , all files are .kt,then how

**Comment by mohantym** [comment]
Hi @Sanjay2802 !
Just your point configuration to objection_detection/app and run with desired device. if you still want to view java version, you can go to view>tools> Show java bytecode. 
Thank you!
