### ISSUE TITLE
Tflite ios batch_size greater than 1 not working

### ISSUE THREAD

**Issue by weinixuehao** [tensorflow/tensorflow#56835]
My model was trained with Pytorch. Convert this model to tflite model with input shape {1, 3, 256, 256} and is working as expected. But change this model to input shape {4, 3, 256, 256} the inference result is not correct.

**Comment by mohantym** [comment]
Hi @weinixuehao !

Batch size > 1 is not supported yet and work in progress feature .

Thank you!

**Comment by roserg** [comment]
Hi, batch size not equal to 1 must work in Metal/OpenCL delegates.
Is it possible to share your .tflite model for investigation?

**Comment by roserg** [comment]
Metal delegate supports only "static" batch. It means that batch size must be specified in the model. Dynamic batch(different batch sizes) with the same model not supported.
