### ISSUE TITLE
`tf.config.set_logical_device_configuration` not working when attempting to create multiple virtual GPUs

### ISSUE THREAD

**Issue by tallamjr** [tensorflow/tensorflow#56837]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tensorflow-macos v2.8.0 tensorflow-metal v0.5.0 

### Custom Code

No

### OS Platform and Distribution

macOS-12.2.1

### Python version

3.8

### Current Behaviour?

I'm developing on a system with a single GPU (Apple M1 Pro) and trying to simulate multiple GPUs with virtual devices.

Using the examples found here: https://www.tensorflow.org/guide/gpu#using_multiple_gpus I get the following output:

```
systemMemory: 32.00 GB
maxCacheSize: 10.67 GB

1 Physical GPU, 1 Logical GPUs
```

where I was expecting the Logical GPUs to be greater than the Physical GPU count.

I have tested `tf.config.set_logical_device_configuration` for increasing Logical device count for CPUs, and this indeed _does_ work for CPU virtualisation.

### Standalone code to reproduce the issue

Taken from the code snippet found at: https://www.tensorflow.org/guide/gpu#using_multiple_gpus

```
gpus = tf.config.list_physical_devices("GPU")
if gpus:
    # Create 2 virtual GPUs with 1GB memory each
    try:
        tf.config.set_logical_device_configuration(
            gpus[0],
            [
                tf.config.LogicalDeviceConfiguration(memory_limit=1024),
                tf.config.LogicalDeviceConfiguration(memory_limit=1024),
            ],
        )
        logical_gpus = tf.config.list_logical_devices("GPU")
        print(len(gpus), "Physical GPU,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        # Virtual devices must be set before GPUs have been initialized
        print(e)
```

### Relevant log output

```shell
1 Physical GPU, 1 Logical GPUs
```
</details>

**Comment by gadagashwini** [comment]
Hi @tallamjr,
I tried on Ubuntu20.04. I could not reproduce the issue. Its working as expected.
Could you try on other OS platform
<img width="1565" alt="Screen Shot 2022-07-25 at 12 38 41 PM" src="https://user-images.githubusercontent.com/99852755/180718491-6b09ace7-2b7c-4a9d-8960-0c39a05590ab.png">

**Comment by tallamjr** [comment]
Hi @gadagashwini , thanks for looking into this. I tried on a Red Hat Enterprise Linux Server /
Fedora machine and it seems to work fine:

```bash
2.9.1
Num GPUs Available:  1
Tue Jul 26 08:31:00 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:D8:00.0 Off |                    0 |
| N/A   33C    P0    33W / 250W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
¦   ¦   ¦   ¦   ¦   ¦   ¦   ¦   ¦   ¦   ¦   ¦   ¦   ¦   ¦   ¦   ¦   ¦   ¦
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
1 Physical GPU, 2 Logical GPUs
```

Unfortunately I do not have access to a Windows machine for testing, but I wonder if it's a problem
with `tensorflow-macos` / `tensorflow-metal` specifically. Is this repo still the best place to log
such an issue?

I tried again locally on macOS and bumped versions of `tensorflow-macos` to be:
```bash
tensorflow-macos        2.9.2
tensorflow-metal        0.5.0
```
and used Python 3.9, but still same problem as reported before, i.e.
```
1 Physical GPU, 1 Logical GPUs
```

**Comment by gadagashwini** [comment]
Hi @tallamjr, It is working as expected on Windows machine also. Looks like issue with tensorflow-macos multiple GPU. Thank you!

**Comment by tallamjr** [comment]
Thanks @gadagashwini.

I see you have added "awaiting response" label, please can you advise of next steps if this needs to be reported elsewhere, or if this is currently being looked into now we have determined it to be a macOS specific problem?

**Comment by gowthamkpr** [comment]
@tallamjr As mentioned [here](https://github.com/tensorflow/tensorflow/issues/56837#issuecomment-1195243796) this issue is specific to tensorflow-macos.
