### ISSUE TITLE
`tf.math.reduce_std` have wrong gradient when input has only one element

### ISSUE THREAD

**Issue by VictoriaGriffith** [tensorflow/tensorflow#56830]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

n/a

### Python version

3.9

### Current Behaviour?

```shell
A bug happened when compute the gradient of `tf.math.reduce_std`. When the input `x` is a shape `[1]` tensor, the reduced standard deviation is always `0`, so the gradient should be `0` (the numerical gradient computed by `tf.test.compute_gradient` is also `0`). However, the current gradient wrongly gives `nan`.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

x = tf.random.uniform([1], minval=-1, maxval=1, dtype=tf.float64)
print(x)

with tf.GradientTape(persistent=False,) as g:
  g.watch(x)
  y = tf.math.reduce_std(x, axis=0, keepdims=True)
  print(y)
print("gradient", g.gradient(y, x))

@tf.function
def test_func(x):
  return tf.math.reduce_std(x, axis=0, keepdims=True)
theoretical, numerical = tf.test.compute_gradient(test_func, [x])

print("theoretical gradient", theoretical)
print("numerical gradient", numerical)
```

### Relevant log output

```shell
tf.Tensor([-0.83151082], shape=(1,), dtype=float64)
tf.Tensor([0.], shape=(1,), dtype=float64)
gradient tf.Tensor([nan], shape=(1,), dtype=float64)
theoretical gradient (array([[nan]]),)
numerical gradient (array([[0.]]),)
```
</details>

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to replicate the issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/0b45ae84aebb32c0af0ef091f6767a54/56794.ipynb) here.
Thank you!

**Comment by cantonios** [comment]
Hmm.... I may be willing to call this correct?

We don't do symbolic math, so the expression for `reduce_std` for a single element becomes
```
y = sqrt( (x - x)^2 )
```
which _we_ can readily see as uniformly 0, but if we take the derivative of the expression w.r.t. `x` as is, results in
```
dy_dx = 1/2 * (1 / sqrt( (x - x)^2 ) ) * 2 * (x - x) * (1 - 1) = 0 / 0 = NaN
```
You would run into the same case for any tensor of all equal values.  Either we treat the expression generically, resulting in `0/0 = NaN`, or we do special checks that will slow down the generic path.

**Comment by sachinprasadhs** [comment]
@VictoriaGriffith , Could you please move the issue to closed by referring to the above comment. Thanks!

**Comment by VictoriaGriffith** [comment]
Thanks @cantonios and @sachinprasadhs for the explanation! Indeed this numerical unstability issue is introduced by zero std value and is hard to avoid unless we add special checks that will degrade performance. I will close this issue as this is a deliberate choice.
