### ISSUE TITLE
Building the library on Raspberry Pi results in: undefined reference to `google::protobuf::internal::fixed_address_empty_string'

### ISSUE THREAD

**Issue by KjerG** [tensorflow/tensorflow#5684]
Hello,

I was told to post this question here:

I am trying to complete a fresh install of Tensorflow on my Raspberry Pi following a failed previous install. I figured it would be easier trying to start fresh so I could more easily document my progress, and what solutions worked or failed. Additionally the new guide is easier to follow than the old guide I was using.

I am following the guide [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#raspberry-pi) and have been able to complete all of the steps up until the `make -f tensorflow/contrib/makefile/Makefile HOST_OS=PI TARGET=PI OPTFLAGS="-Os" CXX=g++-4.8 `command. NOTE: I did not install the example graph.

However when attempting to run this command I am left with several errors. The full output is rather long, but the main recurring error is similar to:

`test_log.pb.cc:(.text+0x784): undefined reference to `google::protobuf::internal::fixed_address_empty_string'`
This kind of error is repeated several times throughout the output for the `make -f command with test_log.pb.cc:(.text+0x784): ` being replaced with different designations. The output ends with the Following error state:

```
step_stats_collector.cc:(.text+0x46c): undefined reference to `google::protobuf::internal::fixed_address_empty_string'
/home/pi/makevoicedemo/tf/tensorflow/tensorflow/contrib/makefile/gen/lib/libtensorflow-core.a(debug_io_utils.o):debug_io_utils.cc:(.text+0x8e8): more undefined references to `google::protobuf::internal::fixed_address_empty_string' follow
collect2: error: ld returned 1 exit status
tensorflow/contrib/makefile/Makefile:501: recipe for target '/home/pi/makevoicedemo/tf/tensorflow/tensorflow/contrib/makefile/gen/bin/benchmark' failed
make: *** [/home/pi/makevoicedemo/tf/tensorflow/tensorflow/contrib/makefile/gen/bin/benchmark] Error 1
```
I feel like the problem is likely do to an error with protobuf, however I am using the latest version and had no errors installing it. I am using the most recent version of tensorflow and followed the Before you start section in the guide to make sure all dependencies were installed and up to date.

What exactly might be causing this error and how would I go about fixing it?

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

[http://stackoverflow.com/questions/38915709/problems-on-builiding-tensorflow-on-rpi-2](http://stackoverflow.com/questions/38915709/problems-on-builiding-tensorflow-on-rpi-2)

### Environment info
Operating System:
Raspbian Jessie

Installed version of CUDA and cuDNN: 
N/A
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
`ls: cannot access /path/to/cuda/lib/libcud*: No such file or directory
`
If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
`a2d96ca09e9943b4bad65b674d29d380dc6a8327`

2. The output of `bazel version`

```
...........................................................................
Build label: 0.2.1-2016-09-15 (@e7a95e5)
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Sep 16 00:46:39 2016 (1473986799)
Build timestamp: 1473986799
Build timestamp as int: 1473986799

```

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
Steps taken (in order) from pre-created directory /tf:

```
git clone https://github.com/tensorflow/tensorflow.git

cd tensorflow

tensorflow/contrib/makefile/download_dependencies.sh

sudo apt-get install -y autoconf automake libtool gcc-4.8 g++-4.8

cd tensorflow/contrib/makefile/downloads/protobuf/

./autogen.sh

./configure

make

sudo make install

sudo ldconfig

cd ../../../../..

make -f tensorflow/contrib/makefile/Makefile HOST_OS=PI TARGET=PI OPTFLAGS="-Os" CXX=g++-4.8
```
The final command results in the error and is as far as I have been able to progress.

### What other attempted solutions have you tried?
I have not come across any applicable solutions to try. 

Any help would be appreciated.

**Comment by girving** [comment]
@petewarden Can you take a look?

**Comment by petewarden** [comment]
Sorry you're hitting problems! This looks like a mismatch between the protobuf version that's installed in your /usr/local system folders, and the one that was used to create the .pb.cc/.h files. Can you try running this command to build a local copy of the libs?

```
tensorflow/contrib/makefile/compile_linux_protobuf.sh
```

**Comment by KjerG** [comment]
Tried `tensorflow/contrib/makefile/compile_linux_protobuf.sh` then ran `make -f tensorflow/contrib/makefile/Makefile HOST_OS=PI TARGET=PI OPTFLAGS="-Os" CXX=g++-4.8`

Resulted in the same error as before. 

I'm going to retry `tensorflow/contrib/makefile/compile_linux_protobuf.sh` and then run `make -f tensorflow/contrib/makefile/Makefile clean` to clean the makefile before running the make -f command again just to be sure.

**Comment by KjerG** [comment]
Sorry for taking so long to respond. Holiday season was rather busy.

I was looking through the /usr/local/lib folder and I've compiled a list of all the protobuf related files below:

```
libprotobuf.a
libprotobuf.la
libprotobuf-lite.a
libprotobuf-lite.la
libprotobuf-lite.so
libprotobuf-lite.so.11
libprotobuf-lite.so.11.0.0
libprotobuf.so
libprotobuf.so.11
libprotobuf.so.11.0.0
```
Also, according to `protoc --version` I currently have `libprotoc 3.1.0` installed. Could this be causing the mismatch? Should I switch to a different version? As far as I know this is the most up to date version.

**Comment by a7ypically** [comment]
I had this issue and it's probably due to compiling protobuf with a different compiler.
Since for tensorflow we use gcc-4.8 explicitly, we should also compile protobuf with gcc-4.8 as well. This fixed my problem. So just use "make CXX=g++-4.8" when you build protobuf.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by nikwalia** [comment]
Hello,
I had the exact same issue and I had already specified "CXX =g++-4.8" when building using make. I'm also doing the exact same thing as discussed above. Thanks!
