### ISSUE TITLE
How to freeze past of FakeQuantWithMinMaxVars when i fakequatize training?

### ISSUE THREAD

**Issue by C-SJK** [tensorflow/tensorflow#56858]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

TF 1.15

### Custom Code

No

### Current Behaviour?

```shell
The model backbone FakeQuantWithMinMaxVars will be freezed When i fintinue a fakequatize model`s head.
```

### Standalone code to reproduce the issue

```shell
When I finetune the trained fake-quantization model, the FakeQuantWithMinMaxVars in the backbone network will change, relative to my pre-trained model, but I don't want this value to change, how can I modify code to ensure this value will not be change during training.
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@C-SJK Older version of TF (1.x) is not actively supported, we recommend you to kindly upgrade to latest TF version and let us know if the issue still persists? Please refer the migration [doc](https://www.tensorflow.org/guide/migrate) to know more on this. Thank you!
