### ISSUE TITLE
Load tf lite model to XLA 

### ISSUE THREAD

**Issue by Theoo1997** [tensorflow/tensorflow#56851]
Hi,
I would like to know if it possible to take a TF lite model (quarantined) and compile into executable code using XLA/JIT. In this lick you have an example about how to create an executable given an tf model : https://www.tensorflow.org/xla/tfcompile. In other words can I use "tfcompile" with tf lite quarantined models?

**Comment by mohantym** [comment]
@Theoo1997 !

I think XLA is not yet supported directly yet in Lite side. But I was thinking to use model under @tf.function(jit_compile=True) and convert it to TFlite model  using concrete function. Then check the difference with benchmarking with XLA and with out XLA flag.

Thank you!

**Comment by Theoo1997** [comment]
If I do that is it possible to run the tf lite model (e.g. using tflite_quant_model.invoke() or something else) utilizing the **INT8** Kernels of XLA library  i.e. C runtime? For example I have created this piece of code. I didn't find a way to fill in the run_tflite_qmodel(...). 
````
```
# Improvements in speed and memory usage of Int8 tf lite models

import tensorflow as tf

@tf.function(jit_compile=True) ## enable XLA
void run_tflite_qmodel (tflite_quant_model,img) :
    ...........
   #and somehow run this tf lite model utilizing the INT8 Kernels of XLA library  i.e. C runtime
    ..........

class model_loader(tf.Module):
  def __call__(self):
    return tf.keras.models.load_model('/tmp/model')
model = model_loader()
concrete_model = model.__call__.get_concrete_function()

# Convert and Quantize the model.
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_model],
                                                            model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_quant_model = converter.convert()

run_tflite_qmodel(tflite_quant_model,load("img.png"))

**Comment by mohantym** [comment]
@Theoo1997 !

I was kind of suggesting to put the model_loader under tf.function. Putting the updated code below. 
```

import tensorflow as tf
import numpy as np

def run_tflite_qmodel (tflite_quant_model,img) :
    interpreter = tf.lite.Interpreter(tflite_quant_model)
    input_index = interpreter.get_input_details()[0]["index"]
    output_index = interpreter.get_output_details()[0]["index"]

  # Run predictions on every image in the "test" dataset.
    prediction_digits = []
    for i, test_image in enumerate(test_images):
      if i % 1000 == 0:
       print(f"Evaluated on {i} results so far.")
    # Pre-processing: add batch dimension and convert to float32 to match with
    # the model's input data format.
      test_image = np.expand_dims(test_image, axis=0).astype(np.float32)
      interpreter.set_tensor(input_index, img)

      # Run inference.
      interpreter.invoke()

     # Post-processing: remove batch dimension and find the digit with highest
     # probability.
     output = interpreter.tensor(output_index)
     digit = np.argmax(output()[0])
     prediction_digits.append(digit)

     print('\n')
    # Compare prediction results with ground truth labels to calculate accuracy.
     prediction_digits = np.array(prediction_digits)
     accuracy = (prediction_digits == test_labels).mean()
     return accuracy


@tf.function(jit_compile=True) ## enable XLA
class model_loader(tf.Module):
  def __call__(self):
    return tf.keras.models.load_model('/tmp/model')
model = model_loader()
concrete_model = model.__call__.get_concrete_function()

# Convert and Quantize the model.
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_model],
                                                            model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_quant_model = converter.convert()
with open(TFLITE_FILE_PATH, 'wb') as f:
  f.write(tflite_quant_model)

# Load the TFLite model in TFLite Interpreter
interpreter = tf.lite.Interpreter(TFLITE_FILE_PATH)
run_tflite_qmodel(tflite_quant_model,load("img.png"))
```

Please use [benchmarking ](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark)tool with xla flags to see whether it works. 
Passing to @sachinprasadhs  now . Thanks for the feature request.

Thank you!

**Comment by Theoo1997** [comment]
Thanks for the answer @mohantym. I was thinking the same think but there is one problem. The Interpreter will transform the INT8 TF lite mode to a FP one right? Actually we are going to see that in practice.So,  I update the above code to mine and faced the above error in the  **model_loader()** class: 

"TypeError: To be compatible with tf.eager.defun, Python functions must return zero or more Tensors; in compilation of <function model_loader.__call__ at 0x7f17c637ff70>, found return value of type <class 'tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject'>, which is not a Tensor."

I think I am using the wrong load function (also tried with tf.saved_model.load()). How am I suppose to change this in order to return tensors and no Object?

**Comment by mohantym** [comment]
@Theoo1997 !
You can create a custom model through class and call the some functions under tf.function which need to be imported in interpreter through concrete functions.
Attached relevant thread for reference[ 1](https://www.tensorflow.org/guide/keras/custom_layers_and_models), [2](https://www.tensorflow.org/lite/examples/on_device_training/overview)
Thank you!

**Comment by Theoo1997** [comment]
Thanks for the answer @mohantym.

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
