### ISSUE TITLE
How to define a simple LSTM layer?

### ISSUE THREAD

**Issue by njuhang** [tensorflow/tensorflow#56860]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.10.0

### Custom Code

No

### OS Platform and Distribution

ubuntu 20.04

### Mobile device

none

### Python version

3.8

### Bazel version

5.1.1

### GCC/Compiler version

9.3.0

### CUDA/cuDNN version

none

### GPU model and memory

none

### Current Behaviour?

```shell
I want to build a single LSTM-layer model, but got unidirectional-LSTM instead.
```

### Standalone code to reproduce the issue

```shell
#define.py
inputs = layers.Input(shape=(5, 4),batch_size=3)
lstm = layers.LSTM(units=3,return_sequences=True,return_state=True,time_major=True)
out,_,_ = lstm(inputs)
print(out.shape)
model = keras.models.Model(inputs = inputs, outputs = out)
model.save('model')

#tflite_convert 
tflite_convert --output_file /mnt/e/lstm.tflite --saved_model_dir ./model/
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @njuhang !

Could you check these [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb) on Fused LSTM  conversion for converting Bi-directional LSTM to TFlLte model and let us know.

Thank you!

**Comment by njuhang** [comment]
I have checked these links. But they can't help to solve my problem.
There is no bi-directional LSTM in my question, I just want to build a simple LSTM layer. But got Unidirectional LSTM instead, same as this [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb). As you known, they are two different layers in tensorflow lite.

**Comment by njuhang** [comment]
Hello, Is there any help?

**Comment by njuhang** [comment]
I have another question, in unidirectional sequence lstm, there is a input called "model/lstm/zeros". But it says "Tensor data is empty." in its description. So I don't know how this input get zero data.

**Comment by njuhang** [comment]
BTW, I can't get a LSTM model from pytorch->onnx->tflite.

**Comment by gowthamkpr** [comment]
@njuhang You can convert the model from Jaxx. Also I am not sure what a simple LSTM layer is in your case. You can also build a custom layer. Can you please point me out to what LSTM layer are you looking into. Thanks!

**Comment by njuhang** [comment]
In tensorflow/lite/kernels/lstm.cc, there is a full LSTM, it's different from UnidirectionalSequenceLSTM in tensorflow/lite/kernels/unidirectional_sequence_lstm.cc. How to build this type of layer?

**Comment by gowthamkpr** [comment]
@njuhang I don't understand what type of LSTM layer you need. Can you point me to pytorch where they have this LSTM layer. Thanks!

**Comment by njuhang** [comment]
Emm, there is nothing to do with pytorch. 
I need such a LSTM layer, when executing inference, it use functions defined in tensorflow/lite/kernels/lstm.cc. But currently I can only get Unidirectional LSTM layer, which use functions defined in tensorflow/lite/kernels/unidirectional_sequence_lstm.cc. My code has been attached above.
My question is how to get a .tflite model, with such a LSTM layer.

**Comment by njuhang** [comment]
Hello? Is there any progress?

**Comment by gowthamkpr** [comment]
@njuhang Please post this issue in [tensorflow forum](https://discuss.tensorflow.org/tag/tflite) for any help. This is primarily for bug/performance, bulild/install issues. Thanks!
