### ISSUE TITLE
WARNING:tensorflow:AutoGraph could not transform... Unable to locate the source code of...

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [tensorflow/tensorflow#56865]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 12.4
- TensorFlow installation (pip package or built from source): 2.7.0
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.7.0 (shown by `conda list`)

### 2. Code
first jupyter cell:
```
import  tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.preprocessing import MinMaxScaler
NUM_POINTS = 2000
SPLIT = 0.9
EPOCHS = 50
def gen(N):
    theta = np.sqrt(np.random.rand(N))*4*np.pi

    r_a = 2*theta + np.pi
    data_a = np.array([np.cos(theta)*r_a, np.sin(theta)*r_a]).T
    tuples_0 = data_a + np.random.randn(N,2)

    r_b = -2*theta - np.pi
    data_b = np.array([np.cos(theta)*r_b, np.sin(theta)*r_b]).T
    tuples_1 = data_b + np.random.randn(N,2)
    return tuples_0, tuples_1

t0,t1 = gen(int(NUM_POINTS * (1-SPLIT)))
x_train = MinMaxScaler().fit_transform(np.concatenate((t0, t1)))
y_train = np.concatenate((np.repeat(0, int(NUM_POINTS * (1-SPLIT))), np.repeat(1, int(NUM_POINTS * (1-SPLIT))))) * 2 - 1

t0,t1 = gen(int(NUM_POINTS * SPLIT))
x_test = MinMaxScaler().fit_transform(np.concatenate((t0, t1)))
y_test = np.concatenate((np.repeat(0, int(NUM_POINTS * (SPLIT))), np.repeat(0, int(NUM_POINTS * (SPLIT)))))
```

second jupyter cell:
```
scores_lab_unlab = np.exp(-1000 * euclidean_distances(x_test, x_train)**2)
scores_unlab_unlab = np.exp(-1000 * euclidean_distances(x_test, x_test)**2)
vars = [tf.Variable(0.) for _ in x_test]
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)
```

third jupyter cell:
```
%%time
@tf.function
def calc_loss(vars):
    global scores_lab_unlab, y_train, scores_unlab_unlab
    loss_lab_unlab = tf.subtract(tf.expand_dims(vars,1), y_train)**2 * scores_lab_unlab
    loss_unlab_unlab = tf.subtract(tf.expand_dims(vars,1), vars)**2 * scores_unlab_unlab / 2
    return tf.reduce_sum(loss_lab_unlab) + tf.reduce_sum(loss_unlab_unlab)

with tf.device("/device:CPU:0"):
    for e in range(EPOCHS):
        print(f"Epoch: {e} / {EPOCHS}", end="")
        with tf.GradientTape(persistent=True) as tape:
            loss = calc_loss(vars)
        grad = tape.gradient(loss, vars)
        print(f" - Grad: {np.linalg.norm(grad, 1)}")
        optimizer.apply_gradients(zip(grad, vars))
```

### 3. (optional) Any other info / logs
 > WARNING:tensorflow:AutoGraph could not transform <function calc_loss at 0x44e3cfc10> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function calc_loss at 0x44e3cfc10>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <function calc_loss at 0x44e3cfc10> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unable to locate the source code of <function calc_loss at 0x44e3cfc10>. Note that functions defined in certain environments, like the interactive Python shell, do not expose their source code. If that is the case, you should define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.experimental.do_not_convert. Original error: could not get source code
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

**Comment by AlbertoSinigaglia** [comment]
In case you prefer, this is a link to the code in colab (the problematic cell is the last one):
https://colab.research.google.com/drive/12Uqxh0uAAZ9CC-ODKwmb9CkZaAFI6zSu?usp=sharing

**Comment by AlbertoSinigaglia** [comment]
I suspect that it's due to the fact that I'm using variables that are created outsize the jupyter cell, however I would like to know if that's the case and how to tackle that problem, since online I've literally found nothing

**Comment by mohantym** [comment]
Hi @AlbertoSinigaglia !
This issue does not seem to replicating in 2.8.2 . Could you let us know for your end in 2.8.2 / 2.9 .
Thank you!
