### ISSUE TITLE
TF v2.9 Failed to build from source Error: crosstool_wrapper_driver_is_not_gcc failed: error executing command 

### ISSUE THREAD

**Issue by SuperPauly** [tensorflow/tensorflow#56862]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

No

### OS Platform and Distribution

20.04

### Python version

3.8

### Bazel version

5.0

### GCC/Compiler version

9.4

### CUDA/cuDNN version

11.2/8.1

### GPU model and memory

3090Ti

### Current Behaviour?

```shell
When compiling following the build from source instructions I get the following error
```

### Standalone code to reproduce the issue

```shell
I fun ./configure choose the correct fields. No to ROC, No to Android build & No to CLang. I then goto build with.
bazel build --config=cuda //tensorflow/tools/pip_package:build_pip_package

I have Cuda 11.2
```

### Relevant log output

```shell
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/093ed77f7d50f75b376f40a71ea86e08cedb8b80.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: /home/heales/.cache/bazel/_bazel_heales/30fcb60da9c2874c98674721e029dab7/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:10:
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/11b2812d64e49bab9b6c489f79067fc94e69db9f.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1596824487 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /home/heales/tensorflow/WORKSPACE:23:14: in <toplevel>
  /home/heales/tensorflow/tensorflow/workspace0.bzl:107:34: in workspace
  /home/heales/.cache/bazel/_bazel_heales/30fcb60da9c2874c98674721e029dab7/external/bazel_toolchains/repositories/repositories.bzl:35:23: in repositories
Repository rule git_repository defined at:
  /home/heales/.cache/bazel/_bazel_heales/30fcb60da9c2874c98674721e029dab7/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/heales/.cache/bazel/_bazel_heales/30fcb60da9c2874c98674721e029dab7/external/llvm-project/mlir/BUILD.bazel:6997:11: Compiling mlir/lib/Dialect/Linalg/IR/LinalgDialect.cpp failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt-exec-50AE0418/bin/external/llvm-project/mlir/_objs/LinalgOps/LinalgDialect.d ... (remaining 136 arguments skipped)
x86_64-linux-gnu-gcc-9: fatal error: Killed signal terminated program cc1plus
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1503.995s, Critical Path: 280.70s
INFO: 11667 processes: 6515 internal, 5152 local.
FAILED: Build did NOT complete successfully
```
</details>

**Comment by mohantym** [comment]
Hi @SuperPauly !
Either you can switch to GCC 7.3 or  rebuild with below command after pointing your Cuda file location during configure.py process.

`bazel build  --config=cuda --config=opt --per_file_copt=//tensorflow/.*\.cc@-g,-O0 tensorflow/tools/pip_package:build_pip_package`

Ref [1](https://github.com/tensorflow/tensorflow/issues/44692#issuecomment-727179379), [2](https://github.com/tensorflow/tensorflow/issues/44692#issuecomment-917543931).

Thank you!

**Comment by SuperPauly** [comment]
> 

Thanks for the response.

I ran a 'bazel clean' and then ./configure again and I did not need to set my Cuda dir's as it finds them automatically.

I tryied to compile GCC 7.2 sionce it wasn't in my repo and came up with some problems and it did not compile so i ran the line you have above and now I get this error:

`INFO: Found applicable config definition build:short_logs in file /home/heales/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/heales/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:tensorrt in file /home/heales/tensorflow/.bazelrc: --repo_env TF_NEED_TENSORRT=1
INFO: Found applicable config definition build:cuda in file /home/heales/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:cuda in file /home/heales/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:linux in file /home/heales/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changesINFO: Found applicable config definition build:dynamic_kernels in file /home/heales/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Build options --compilation_mode, --cxxopt, and --per_file_copt have changed, discarding analysis cache.
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (0 packages loaded, 35421 targets configured).
INFO: Found 1 target...
ERROR: /home/heales/tensorflow/tensorflow/compiler/mlir/hlo/BUILD:645:11: Compiling tensorflow/compiler/mlir/hlo/lib/Dialect/lhlo/IR/lhlo_ops.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt-exec-50AE0418/bin/tensorflow/compiler/mlir/hlo/_objs/lhlo/lhlo_ops.d ... (remaining 148 arguments skipped)
x86_64-linux-gnu-gcc-9: fatal error: Killed signal terminated program cc1plus
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1769.815s, Critical Path: 239.58s
INFO: 8670 processes: 3170 internal, 5500 local.
FAILED: Build did NOT complete successfully`

**Comment by gadagashwini** [comment]
Hi @SuperPauly,
Looks like version incompatibility. 
Follow these versions For Tensorflow 2.9.


Version | Python version | Compiler | Build tools
-- | -- | -- | --
tensorflow-2.9.0 | 3.7-3.10 | GCC 9.3.1 | Bazel 5.0.0

Let us know if you still face an issue. Thank you!
