### ISSUE TITLE
Building to wasm

### ISSUE THREAD

**Issue by nmgray** [tensorflow/tensorflow#56872]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

v2.9.0+incompatible

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04.4 LTS

### Python version

N/A

### Current Behaviour?

```shell
Applications depending on tensorflow do not build to js operating system and wasm architecture. Does the Tensorflow for golang have wasm support?
```

### Standalone code to reproduce the issue

```shell
Using the following code:


package main

import (
	"fmt"

	tf "github.com/tensorflow/tensorflow/tensorflow/go"
)

func main() {
	var t tf.Tensor
	fmt.Println(t)
}
```
```


### Relevant log output

```shell
Build results:

$GOOS=js GOARCH=wasm go build main.go 
# command-line-arguments
./main.go:10:11: undefined: tensorflow.Tensor
```
```
</details>

**Comment by gadagashwini** [comment]
Hi @nmgray, TensorFlow.js now provides a [WebAssembly](https://webassembly.org/) (WASM) backend for both the browser and for Node.js. Could you go through this [link](https://blog.tensorflow.org/2020/03/introducing-webassembly-backend-for-tensorflow-js.html) for more information. Thank you!

**Comment by nmgray** [comment]
To clarify: there isn't a way to build golang to wasm when utilizing the tf
package and it must be accessed via js to run tf models in the browser?

Thanks,

Nick

**Comment by gadagashwini** [comment]
Hi @nmgray, Please take a look at below comment 

> WebAssembly (Wasm) is a cross-browser binary format that brings near-native code execution speed to the web. Wasm serves as a compilation target for programs written in statically typed high level languages, such as C, C++, Go, and Rust. In TensorFlow.js, we implement our Wasm backend in C++ and compile with Emscripten. The XNNPACK library provides a heavily optimized implementation of neural network operators underneath.

For more information refer this [link ](https://blog.tensorflow.org/2020/09/supercharging-tensorflowjs-webassembly.html). Thank you!
