### ISSUE TITLE
Limit max results 

### ISSUE THREAD

**Issue by Sanjay2802** [tensorflow/tensorflow#56874]
How to limit max results shown on screen in Android object detection JAVA, in latest version its written in kotlin so i just can't understand, so how to set limit of results in JAVA

**Comment by mohantym** [comment]
Hi @Sanjay2802!

You can edit cyclic buffer size from console to reduce number of lines in logcat. You can also see specific section like error, warnings ,verbose from Logcat tab .
Attached relevant thread for reference.  [1](https://stackoverflow.com/questions/27618977/android-studio-maximum-number-of-lines-logcat), [2](https://www.youtube.com/watch?v=smOzLSTaso0).

Thank you!
