### ISSUE TITLE
Are there on-device training with Tensorflow lite in Arduino IDEs???

### ISSUE THREAD

**Issue by 729557989** [tensorflow/tensorflow#56883]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

tf2.8

### Custom Code

No

### OS Platform and Distribution

Windows

### Current Behaviour?

```shell
Is there a way to perform on-device training with Tensorflow lite in Arduino IDE? I see an option for Java and C++ with android but can't find the C++ doc... Seems like C ain't supported too.
```

### Standalone code to reproduce the issue

```shell
No code
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @729557989 !

I do see an implementation of on device training on Arduino [here](https://create.arduino.cc/projecthub/aifes_team/wio-terminal-ai-gesture-recognition-with-on-device-training-13b636) through AIfes arduino manager.  It seems to record the the input and retrain the model.

Please post  in [tflite-micro](https://github.com/tensorflow/tflite-micro) repo for further assistance. 

Thank you!
