### ISSUE TITLE
Reverse-mode autodiff didn't throw error with invalid input shape for API `tf.reduce_max` as expected

### ISSUE THREAD

**Issue by eeDigitalSeal** [tensorflow/tensorflow#56886]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

Reverse-mode autodiff didn't throw any error with **invalid input shape `axis.shape=(1,1)`** on line 13 in the code below. 
Forward-mode autodiff threw the `ValueError` as expected. So the behaviour for `tf.GradientTape` should be the same but not.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

input = tf.constant([0.9165313, 0.9094733], shape=(2,), dtype=tf.float32)

# axis is with invalid shape
axis = tf.constant([[0]], shape=(1, 1), dtype=tf.int32)

res = tf.reduce_max(input,axis=axis,keepdims=False)
print(res)
with tf.GradientTape() as g:
    g.watch(input)
    # should threw ValueError here, but it didn't 
    res_backward = tf.reduce_max(input,axis=axis,keepdims=False)
print(g.gradient(res_backward,input))

with tf.autodiff.ForwardAccumulator(input,tf.constant([1.,0.])) as acc:
    res_forward = tf.reduce_max(input,axis=axis,keepdims=False)
print(acc.jvp(res_forward))
```

### Relevant log output

```shell
ValueError: Shape must be at most rank 1 but is rank 2 for '{{node gradient_tape/Sum}} = Sum[T=DT_FLOAT, Tidx=DT_INT32, keep_dims=false](gradient_tape/Cast, inputs_1)' with input shapes: ?, [1,1].
```
</details>

**Comment by eeDigitalSeal** [comment]
@sushreebarsa Hi, as you replicated, the `ValueError` is thrown by forward-mode auto differentiation at line 17. But the input shape `[2]` is actually invalid so it should throw the same error in reverse-mode at line 13, that is
```python
res_backward = tf.reduce_max(input,axis=axis,keepdims=False)
```
I think it was caused by some missing input validation in reverse-mode autograd.

**Comment by sachinprasadhs** [comment]
Forward and backward gradients are computed in different ways and that is the reason you are seeing different behavior.
Regarding invalid inputs, in gradient calculation, validating of inputs will not be performed in all the cases considering the computation cost which will effect the performance. Thanks!
