### ISSUE TITLE
message "convert_variables_to_constants is deprecated"

### ISSUE THREAD

**Issue by njzjz** [tensorflow/tensorflow#56884]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

binary

### Tensorflow Version

2.8.2

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.9

### Current Behaviour?

`tf.compat.v1.graph_util.convert_variables_to_constants` gives a warning message:

```
WARNING:tensorflow:From <ipython-input-2-d9eca9909494>:2: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
```

It's confusing here: I did use `tf.compat.v1.graph_util.convert_variables_to_constants`. Why did it still give a warning message?

### Standalone code to reproduce the issue

```py
import tensorflow as tf
tf.compat.v1.graph_util.convert_variables_to_constants(tf.compat.v1.Session(), tf.compat.v1.GraphDef(), [])
```

https://colab.research.google.com/gist/njzjz/6cd1af05016aea60e1c4ec258d5897d6/tf-compat-v1-graph_util-convert_variables_to_constants.ipynb

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @chunduriv !
Could you look at this issue. Attached gist in [2.8](https://colab.sandbox.google.com/gist/mohantym/3cbf0910ba926fac52a2b3530afab136/tf-compat-v1-graph_util-convert_variables_to_constants.ipynb#scrollTo=G8bAE-F-ATb4), [2.9](https://colab.sandbox.google.com/gist/mohantym/73930d9bcffc5d5bda7138c7fb7b2d76/tf-compat-v1-graph_util-convert_variables_to_constants.ipynb#scrollTo=wKWfOZPqg_r6) and [nightly](https://colab.sandbox.google.com/gist/mohantym/2fff9ea23aa10a9fcd918d4cb13807fe/tf-compat-v1-graph_util-convert_variables_to_constants.ipynb#scrollTo=wKWfOZPqg_r6) for reference.
Thank you!

**Comment by chunduriv** [comment]
@njzjz,

Thank you for reporting the issue.  

Below functions under  `tf.compat.v1.graph_util.*` are deprecated and will be removed.

- convert_variables_to_constants
- extract_sub_graph
- must_run_on_cpu
- remove_training_nodes
- tensor_shape_from_node_def_name

Please refer [here](https://www.tensorflow.org/api_docs/python/tf/graph_util) for helpers to manipulate a tensor graph in python using Tensorflow 2.



Note:  `Tensorflow 1 ` is deprecated and support will be removed on `August 1, 2022`.
