### ISSUE TITLE
tflite QuantizationDebugger seem haven't support tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8

### ISSUE THREAD

**Issue by Jwy-Leo** [tensorflow/tensorflow#56899]
tflite QuantizationDebugger seem haven't support tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8

I try directly use the mlir_quantize(inference_type=dypes.int16), but it will directly convert full quantized model.

**Comment by mohantym** [comment]
Hi @Jwy-Leo !
Could you provide a minimal stand alone code as gist to replicate this issue.
Thank you!

**Comment by Jwy-Leo** [comment]
Hi @mohantym ,
minimal stand alone code
`


import tensorflow as tf
import tensorflow_addons as tfa
from tensorflow.lite.python import convert as _tf_convert
from tensorflow.lite.toco import types_pb2 as _types_pb2

def representative_data_gen():
        for i in range(10):
            yield [tf.random.normal((1, 640, 480, 3), dtype=tf.float32)]

def main():
    _input = x = tf.keras.layers.Input((640, 480, 3), dtype=tf.float32)
    x = tf.keras.layers.Conv2D(64, kernel_size=3)(x)
    output = tfa.layers.GELU(False, name='gelu')(x)
    tf_model = tf.keras.Model(inputs=[_input], outputs=[output])

    converter = tf.lite.TFLiteConverter.from_keras_model(tf_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [ tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8 ]
    converter.representative_dataset = representative_data_gen
    int16_model = converter.convert()

    converter = tf.lite.TFLiteConverter.from_keras_model(tf_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter._experimental_calibrate_only = True
    converter.representative_dataset = representative_data_gen
    calibrate_model = converter.convert()
    
    # _types_pb2.QUANTIZED_INT16
    quantized_model = _tf_convert.mlir_quantize(calibrate_model, inference_type=_types_pb2.QUANTIZED_INT16, denylisted_ops=['Gelu'])
    
    expect_quantized_model = _tf_convert.mlir_quantize(calibrate_model, denylisted_ops=['Gelu'])

    with open("int16_model.tflite", 'wb') as F:
        F.write(int16_model)

    with open("calibrate_model.tflite", 'wb') as F:
        F.write(calibrate_model)
    
    with open("quantized_model.tflite", 'wb') as F:
        F.write(quantized_model)
    
    with open("expect_quantized_model.tflite", 'wb') as F:
        F.write(expect_quantized_model)

if __name__ == "__main__":
    main()


`
I expected the graph will become and the inference type = tf.int16, thus the output node will become int16 datatype.
![image](https://user-images.githubusercontent.com/32138547/181090902-95331828-b55a-4932-b67f-752c73a6383b.png)
But after the conversion, it will become int8 quantize inspect model

**Comment by mohantym** [comment]
Hi @sachinprasadhs !
Could you please look at this issue . Attached gist in [2.8,](https://colab.sandbox.google.com/gist/mohantym/e6c4b134715a96dbd64ca395b7ffe30b/git_56899.ipynb#scrollTo=2lIfaMRNN-U9),[ 2.9 ](https://colab.sandbox.google.com/gist/mohantym/8263bd5eb719208d49a5b1fd8cddb0df/git_56899.ipynb#scrollTo=mt_9g-2se8-T)and [nightly](https://colab.sandbox.google.com/gist/mohantym/ece50dcd8ac4f5b73e580defa4fd1d01/git_56899.ipynb#scrollTo=U_B9bbZIMbh-) for reference.
Thank you!

**Comment by sachinprasadhs** [comment]
@Jwy-Leo , Could you please use the `QuantizationDebugger` to know if there is any node skipping the quantization which is leading to the unexpected behavior. For more details check https://www.tensorflow.org/lite/performance/quantization_debugger#selective_quantization
