### ISSUE TITLE
SlurmClusterResolver cannot be configured to use no GPUs

### ISSUE THREAD

**Issue by cianciosa** [tensorflow/tensorflow#56894]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux custom cray distribution

### Mobile device

N/A

### Python version

Conda evn installed python 3.10

### Bazel version

N/A

### GCC/Compiler version

N/A

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### Current Behaviour?

```shell
Attempting to use zero GPU's causes an error



Traceback (most recent call last):
  File "test.py", line 17, in <module>
    strategy = tensorflow.distribute.MultiWorkerMirroredStrategy(cluster_resolver=cluster_resolver)
  File "/global/homes/m/markcian/.conda/envs/parallel_tensorflow/lib/python3.10/site-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py", line 189, in __init__
    communication_options=communication_options))
  File "/global/homes/m/markcian/.conda/envs/parallel_tensorflow/lib/python3.10/site-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py", line 327, in __init__
    self._initialize_strategy(self._cluster_resolver)
  File "/global/homes/m/markcian/.conda/envs/parallel_tensorflow/lib/python3.10/site-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py", line 338, in _initialize_strategy
    if cluster_resolver.cluster_spec().as_dict():
  File "/global/homes/m/markcian/.conda/envs/parallel_tensorflow/lib/python3.10/site-packages/tensorflow/python/distribute/cluster_resolver/slurm_cluster_resolver.py", line 327, in cluster_spec
    range(num_tasks), range(0, self._gpus_per_node, self._gpus_per_task)):
ValueError: range() arg 3 must not be zero
```

If I attempt to set gpus_per_task to 1 to fix this error, 

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    auto_set_gpu=False)
  File "/global/homes/m/markcian/.conda/envs/parallel_tensorflow/lib/python3.10/site-packages/tensorflow/python/distribute/cluster_resolver/slurm_cluster_resolver.py", line 271, in __init__
    raise RuntimeError('Requested more GPUs per node then available.')
RuntimeError: Requested more GPUs per node then available.
```

The expected behavior is that I would be able to configure tensorflow to not use GPUs and that it won't even attempt to use them if there are no GPUs on the node especially when installed with `pip install tensorflow_cpu`.
```


### Standalone code to reproduce the issue

```shell
import tensorflow

cluster_resolver = tensorflow.distribute.cluster_resolver.SlurmClusterResolver(gpus_per_node=0,
                                                            gpus_per_task=0,
                                                            tasks_per_node=1,
                                                            auto_set_gpu=False)
```

### Relevant log output

```shell
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
v2.9.0-18-gd8ce9f9c301 2.9.1
```
</details>

**Comment by sushreebarsa** [comment]
@cianciosa 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!

**Comment by cianciosa** [comment]
This simple code should produce the first error message.
```
import tensorflow

cluster_resolver = tensorflow.distribute.cluster_resolver.SlurmClusterResolver(gpus_per_node=0,
                                                            gpus_per_task=0,
                                                            tasks_per_node=1,
                                                            auto_set_gpu=False)
```

**Comment by sushreebarsa** [comment]
@cianciosa Sorry for the late response!
I suspect that gpu is not declared so it’s  not getting detected. 
You have installed Cpu version of tensorflow  using  `pip install tensorflow_cpu` and used  gpu = false in this line  File "test.py", line 6, in <module>
    auto_set_gpu=False) ( Change to True after setting GPU mode)
Could you install cuda tool kit through " Conda install cuda toolkit  " command and also install NVIDIA driver.
then gpu_per_node  = 2 or 4 according to GPU cards. Please let me know if it helps?
Thank you!

**Comment by cianciosa** [comment]
I'm trying to run this on multiple Haswell Nodes at NERSC.
[https://docs.nersc.gov/systems/cori/](https://docs.nersc.gov/systems/cori/)
There's no physical GPUs in the machine Nvidia or otherwise. The problem is stemming from line https://github.com/tensorflow/tensorflow/blob/4c4f4d90edcb2c23d1049e57a99d5fe635b116db/tensorflow/python/distribute/cluster_resolver/slurm_cluster_resolver.py#L323
range needs a non-zero value for the 3rd argument. The code as written assumes there are GPUs available which are not the case on this machine. What the code should do instead is
```
if self._gpus_per_node > 0:
    for port_offset, gpu_offset in zip(range(num_tasks), range(0, self._gpus_per_node, self._gpus_per_task)):

        host_addr = '%s:%d' % (host, self._port_base + port_offset)
        task_list.append(host_addr)
        gpu_id_list = []

        for gpu_id in range(gpu_offset, gpu_offset + self._gpus_per_task):
          gpu_id_list.append(str(gpu_id))

        self._gpu_allocation.append(','.join(gpu_id_list))
```

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue. 
`cluster_resolver` is basically designed for TPU and GPU only, it is not intended to without any of those hardware.
But even with the changes which you have suggested, it may fail in the below condition
```
    if self._auto_set_gpu:
      os.environ['CUDA_VISIBLE_DEVICES'] = self._gpu_allocation[self._rank]
```

above value should be set to 
`os.environ['CUDA_VISIBLE_DEVICES'] = ""`
or 
`os.environ['CUDA_VISIBLE_DEVICES'] = '-1'`
To use CPU only.
