### ISSUE TITLE
Test failures in //tensorflow/java module

### ISSUE THREAD

**Issue by namrata-ibm** [tensorflow/tensorflow#56892]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

Python 3.8.10

### Bazel version

5.1.1

### GCC/Compiler version

9.4.0

### CUDA/cuDNN version

NA

### GPU model and memory

NA

### Current Behaviour?

```shell
Tests fail when run locally.


Tests should pass. 
Checked a few CI builds and observed only //tensorflow/java:source_writer_test is executed. Could someone please share thoughts on this?
```

### Standalone code to reproduce the issue

```shell
bazel --host_jvm_args="-Xms1024m" --host_jvm_args="-Xmx2048m" test //tensorflow/java/...
```

### Relevant log output

```shell
java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: linux, architecture: x86_64.
.
.
java.lang.NoClassDefFoundError: Could not initialize class org.tensorflow.EagerSession
```
</details>

**Comment by tilakrayal** [comment]
Hi @namrata-ibm,
Could you please try after setting `-Dorg.tensorflow.NativeLibrary.DEBUG=1` in the JVM? That will provide additional information about what's missing.

Also please take a look at this [SO](https://stackoverflow.com/questions/46303270/exception-in-thread-main-java-lang-unsatisfiedlinkerror-cannot-find-tensorflo) link and the [issue](https://github.com/tensorflow/tensorflow/issues/42891) with the similar error.

```
<dependency>
    <groupId>org.tensorflow</groupId>
    <artifactId>libtensorflow_jni</artifactId>
    <version>Tensorflow Version</version>
<dependency>
```

Thank you!

**Comment by namrata-ibm** [comment]
@tilakrayal I am not running a separate project. I have built TensorFlow from source and executing test suite. Any environment setting that I am missing?

**Comment by tilakrayal** [comment]
@namrata-ibm,
Could you provide the complete error log to debug the issue. Thank you!

**Comment by namrata-ibm** [comment]
Please find below complete logs:
[testjava_logs.txt](https://github.com/tensorflow/tensorflow/files/9231179/testjava_logs.txt)

**Comment by mohantym** [comment]
Hi @namrata-ibm !

Tests seems to passing with Bazel 5.0.0 , TF 2.9 and GCC 7.3.1 . Attached [gist](https://colab.sandbox.google.com/gist/mohantym/e066b8ffbf2061f5e37c3a54b781c9b9/tensorflow-ranking.ipynb#scrollTo=zN0UDuBtEF4C) for reference. 
Could you test with above config and let us know.

Thank you!

**Comment by namrata-ibm** [comment]
@mohantym thank you for your response.
1. The gist you shared has `Streaming output truncated to the last 5000 lines`, so the passing tests are not visible.
2. Setup: I have `Bazel 5.0.0` and `GCC 7.5.0`. I see you have built using `r2.9 branch` instead of tag, whereas I am trying from `v2.9.1 tag`. Not sure if that would affect but could you please check if you could reproduce with tag.
3. Also as per [matrix](https://www.tensorflow.org/install/source#cpu), gcc 9.3 is recommended. Could you please share whether there is any hard dependency on gcc version?

**Comment by namrata-ibm** [comment]
@mohantym Could you please have a look ?

**Comment by mohantym** [comment]
Hi @namrata-ibm !
It is getting time out here while build , I will run it with a separate account and update you.
Thank you!

**Comment by namrata-ibm** [comment]
@mohantym  did you get a chance to check on this? Thanks!

**Comment by namrata-ibm** [comment]
@mohantym Any updates on this? Thanks!

**Comment by mohantym** [comment]
@namrata-ibm !
Sorry for the late response. I checked this issue in windows machine . Some tests were failing from Lite/java as you mentioned. Was going to update you after checking in Colab (Timed out again).  can confirm that Issue still persists in 2.9. 

Thank you!

**Comment by namrata-ibm** [comment]
Thank you for confirming @mohantym

**Comment by Craigacp** [comment]
The Tensorflow Java API in this repo isn't maintained. The maintained version of TF-Java lives in github.com/tensorflow/java.

**Comment by namrata-ibm** [comment]
Thank you @Craigacp for confirming.
