### ISSUE TITLE
Inconsistent CUDA toolkit path: /usr vs /usr/lib

### ISSUE THREAD

**Issue by jimlloyd** [tensorflow/tensorflow#56895]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.x (tried on 2.9 and 2.4)

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8 (probably not relevant)

### Bazel version

3.7.2, 4.2.2 (probably not relevant)

### GCC/Compiler version

9.4 .0 (probably not relevant)

### CUDA/cuDNN version

CUDA 11.7, cuDNN 8

### GPU model and memory

RTX 3060 (not relevant)

### Current Behaviour?

```shell
I occasionally need to build tensorflow_cc from source so that I can use tensorflow inference in a C++ application. I have done this several times over the last ~5 years using https://github.com/FloopCZ/tensorflow_cc to do the build.

In my most recent attempt to build I ran into this problem while configuring:


Inconsistent CUDA toolkit path: /usr vs /usr/lib
Asking for detailed CUDA configuration...
```

The exception that causes this problem is raised in `tensorflow/third_party/gpus/find_cuda_config.py` at https://github.com/tensorflow/custom-op/blob/e0e681164dc58580987971464c252529252b89e6/gpu/find_cuda_config.py#L289

There is a TODO a few lines earier:

# XLA requires the toolkit path to find ptxas and libdevice.
# TODO(csigg): pass in both directories instead.

I suspect that resolving this TODO would fix the problem.

But what is the problem, exactly?

It seems to me that there are multiple variations in how CUDA + cuDNN can be installed. Some of these variations will trigger the problem because the exact locations of CUDA/cuDNN components do not match those expected.

While searching for clues to how to resolve this problem, I came across this closed issue: https://github.com/tensorflow/tensorflow/issues/40202

In that issue the reporter wrote "A more reliable workaround is to install the cuda toolkit using Nvidia's .run file installer.", which was apparently enough to close the issue.

I'd like to request that this issue be fully resolved by addressing the TODO.

In my case, I am no longer fully blocked by this issue, but I had hoped to be able to use the Lambda Stack to install all of the necessary dependencies. The stack installs CUDA/cuDNN in a layout that triggers this problem.
```


### Standalone code to reproduce the issue

```shell
I believe this may be the most succinct description I can provide for how to reproduce the problem:

1. Start with a fresh install of Ubuntu 20.04.
2. Install Lambda Stack (https://lambdalabs.com/lambda-stack-deep-learning-software)
3. git clone https://github.com/FloopCZ/tensorflow_cc.git 
4. Follow the instructions https://github.com/FloopCZ/tensorflow_cc#3-build-and-install-the-library 

You should see the "Inconsistent ..." error when running `make`.

Notes:

1. I saw the error above when building Tensorflow 2.9, which is the current default specified by https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/PROJECT_VERSION. However, I also tried Tensorflow 2.4.3 with the same result.
```

### Relevant log output

_No response_</details>

**Comment by jimlloyd** [comment]
@mohantym if @chsigg is available to work on this you might want to reassign to him.

**Comment by mohantym** [comment]
Hi @jimlloyd !

Yes! Errors point towards multiple Cuda installations which are causing conflict . Could you delete the existing installations and re-install cuda tool kit freshly (set the path for cuda file locations too) and let us know the result. 

If you are running configure.py , provide cuda file location during that. 

**Tested config**
Bazel 5.0.0 TF 2.9 , GCC 7.3 , Cuda 11.2 ,CudaNN 8.1 
Attached relevant threads for reference [1](https://askubuntu.com/questions/1371949/inconsistent-cuda-toolkit-path-usr-vs-usr-lib-tensorflow-build-from-source), [2](https://www.pugetsystems.com/labs/hpc/How-To-Install-CUDA-10-1-on-Ubuntu-19-04-1405/) (change from 10.1 to 11.2 ).

Thank you!

**Comment by jimlloyd** [comment]
Hi @mohantym : I did some of my testing with a fresh install of Ubuntu 20.04 on which I only installed on version of Cuda.

It is possible that the problem when testing with the Lambda Stack is due to multiple Cuda installs -- I have not looked to see it it installs multiple Cuda versions. But I can say with confidence that the bug can happen with only one Cuda version installed.

But note that I think the Lambda Stack problem is worthy of investigation. The TODO in find_cuda_config.py is one that should be addressed!

I have been struggling the latter half of today after seemingly successfully building TF 2.4.3 onto rediscover a known problem with libcusolver.so.10/11. Meanwhile I gained some evidence that a protobuf problem I had with using TF 9 from Docker was pilot error, so tomorrow I will try again with TF 9.

**Comment by mohantym** [comment]
Ok @jimlloyd !
Thanks for the update. @gadagashwini ! Could you please look at this issue.
Thank you!

**Comment by gadagashwini** [comment]
Hi @jimlloyd, Use conda to install the CUDA, cuDNN.  Conda takes care of Path setting.
I installed Tensorflow with PIP and CUDA, cuDNN with conda without any issue.

`conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0 `

Configure the system paths. You can do it with following command everytime your start a new terminal after activating your conda environment.
`
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/`

Thank you!

**Comment by jimlloyd** [comment]
Hi @mohantym & @gadagashwini,

Thanks for your replies! 

This morning I attempted to again build Tensorflow_cc using Lamba Stack and discovered I had the wrong understanding of what Lamba Stack installs. It does install `cuda` and `cudnn` but for `python` only.

I created a virtual env as directed by Lambda and installed cuda 11.7 and cudnn 8.4.0. I then ensured that the environment variables used by `tensorflow_cc` were correct for my installation:

```
TF_CUDA_COMPUTE_CAPABILITIES=sm_86,compute_86
TF_NCCL_VERSION=2
TF_CUDNN_VERSION=8.4.0
TF_CUDA_VERSION=11.7
TF_CUDA_PATHS=/usr/local/cuda
```

From here, I was able to start building tensorflow from sources. The build is still in progress but I am hopeful that this will work.

I think we can close this issue. I still think it would be preferable to resolve the tech-debt in `find_cuda_config.py`, but it's hard for me to argue that it is urgent enough to assign anyone to do the work.

So, I am closing this issue as is. Thanks!

**Comment by nikolaydyankov** [comment]
> Hi @mohantym & @gadagashwini,
> 
> Thanks for your replies!
> 
> This morning I attempted to again build Tensorflow_cc using Lamba Stack and discovered I had the wrong understanding of what Lamba Stack installs. It does install `cuda` and `cudnn` but for `python` only.
> 
> I created a virtual env as directed by Lambda and installed cuda 11.7 and cudnn 8.4.0. I then ensured that the environment variables used by `tensorflow_cc` were correct for my installation:
> 
> ```
> TF_CUDA_COMPUTE_CAPABILITIES=sm_86,compute_86
> TF_NCCL_VERSION=2
> TF_CUDNN_VERSION=8.4.0
> TF_CUDA_VERSION=11.7
> TF_CUDA_PATHS=/usr/local/cuda
> ```
> 
> From here, I was able to start building tensorflow from sources. The build is still in progress but I am hopeful that this will work.
> 
> I think we can close this issue. I still think it would be preferable to resolve the tech-debt in `find_cuda_config.py`, but it's hard for me to argue that it is urgent enough to assign anyone to do the work.
> 
> So, I am closing this issue as is. Thanks!

I'm also trying to solve this, unfortunately I'm not so advanced and don't understand everything that you did to solve it. I created a virtual env in the tensorflow folder, installed cuda with `pip install cuda-python` but I couldn't figure out how to install cudnn. Also I don't understand how you did this:

> I then ensured that the environment variables used by tensorflow_cc were correct for my installation
