### ISSUE TITLE
TF-TRT failed to convert the key of the savedModel model signature_def inputs

### ISSUE THREAD

**Issue by lixiaolx** [tensorflow/tensorflow#56907]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf2.4.1

### Custom Code

Yes

### OS Platform and Distribution

Ubutun18.04

### Python version

3.6

### Current Behaviour?

```shell
A bug happened

When using tf-trt for model conversion in savedModel format, the model produced by trt changes the input key value of signature_def. The original key value contains uppercase and lowercase names. After trt-tf is output, it becomes all lowercase, and the model cannot be run.

use command： saved_model_cli show

before：

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:
signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['answerWilsonScore'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1)
        name: serving_default_answerWilsonScore:0

after tf-trt：

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:
signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 
signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['answerwilsonscore'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1)
        name: serving_default_answerwilsonscore:0
```

### Standalone code to reproduce the issue

```shell
https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#worflow-with-savedmodel 

from tensorflow.python.compiler.tensorrt import trt_convert as trt
converter = trt.TrtGraphConverterV2(input_saved_model_dir=input_saved_model_dir)
converter.convert()
converter.save(output_saved_model_dir)
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
Hi @lixiaolx,
Tensorflow version 2.4 not actively supported. Hence, kindly update to the latest stable version 2.9 and let us know if you are facing the same issue. Thank you!

**Comment by lixiaolx** [comment]
> Hi @lixiaolx, Tensorflow version 2.4 not actively supported. Hence, kindly update to the latest stable version 2.9 and let us know if you are facing the same issue. Thank you!

I tried tf2.9.1 and found that there is still the same problem, the input [key] in the model converted by tf-trt is all lowercase. please help me solve it, Thank you！

**Comment by lixiaolx** [comment]
Hi @tilakrayal , We found that the _arg_keywords returned here ( https://github.com/tensorflow/tensorflow/blob/v2.9.1/tensorflow/python/framework/convert_to_constants.py#L1076 ) when TF-TRT convert is different from the original model The same is not case sensitive, is there any way to solve this? Hope that helps to resolve the issue

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
