### ISSUE TITLE
tflite_model_maker.object_detector dies with sigkill during import

### ISSUE THREAD

**Issue by NeuroRoboticTech** [tensorflow/tensorflow#56903]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.8.2

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04 LTS

### Python version

3.8.11

### CUDA/cuDNN version

cuda_11.7.r11.7

### GPU model and memory

NVIDIA TITAN X rev a1

### Current Behaviour?

```shell
I am attempting to follow the directions here (https://colab.research.google.com/github/google-coral/tutorials/blob/master/retrain_efficientdet_model_maker_tf2.ipynb#scrollTo=license) to use tflite model_maker to retrain a network. I have created a virtual environment as shown below. When I import the object_detector from tflite_model_maker it pauses for a bit and then I get a sigkill. (Process finished with exit code 132 (interrupted by signal 4: SIGILL). I traced this all the way down into the file scann/scann_ops/py/scan_ops.py. It calls tf.load_op_library for the file cc/_scann_ops.so. When it tries to load this library it dies with the sigkill.
```

### Standalone code to reproduce the issue

```shell
cd my_folder
pyenv local 3.8.11
python -m venv venv --prompt defender
source venv/bin/activate
python3 -m pip install -U pip wheel setuptools
python3 -m pip install --upgrade pip

cd ..
git clone https://github.com/tensorflow/examples
cd examples/tensorflow_examples/lite/model_maker/pip_package
python3 -m pip install -e .

I then try and and run the following code (I have stripped out everything but the import that is causing the issue), I get the sigkill.

from tflite_model_maker import object_detector

output is:
Process finished with exit code 132 (interrupted by signal 4: SIGILL)
```

### Relevant log output

```shell
I am not sure what logs you would need here. If you let me know how to generate any logs I would be happy to provide them.
```
</details>

**Comment by mohantym** [comment]
Hi @NeuroRoboticTech !
Sorry for the late response. I could not find any issue with Python 3.7 and colab environment. It might be an environment issue ( CUDA 11.2 and  CudNN 8.1 are tested configs for 2.8.2). Could you share the complete error log to help expedite the issue.

**Comment by NeuroRoboticTech** [comment]
I also have an Ubuntu 18 LTS HD that can run on the same computer and GPU.
It has python 3.6.9, cuda cuda_11.4.r11.4, and cudnn 8204. It installs
tensorflow 2.6.2. That one worked fine, so it must be something about the
later code and combo of cuda I am using or something. When I run it the
only output I get is the sigkill output. Does tensorflow save a log
somewhere else that I can send you?

**Comment by mohantym** [comment]
@NeuroRoboticTech !
Thanks for the update.  Python 3.7 is minimum version . Could you switch to Python 3.8/3.9 and let us know.
Thank you!

**Comment by NeuroRoboticTech** [comment]
I was just using 3.6.9 and Ubuntu 18 as a test to see if that worked
with my GPU. I would like to get it working on my normal Ubuntu 20 image.
Can you tell me how to generate or find the logs that you are referring to
in your previous email? I would be happy to provide them, but I am not sure
exactly what it is you are looking for.

Thank you for your help.
David

**Comment by sachinprasadhs** [comment]
Could you try with the latest tensorflow version with the below configurations and let us know if that works for you.


Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow-2.9.0 | 3.7-3.10 | GCC 9.3.1 | Bazel 5.0.0 | 8.1 | 11.2
