### ISSUE TITLE
How to register an op of conv?

### ISSUE THREAD

**Issue by acknowledgexiongdei** [tensorflow/tensorflow#56917]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

source

### Tensorflow Version

tf 2.5

### Custom Code

Yes

### Current Behaviour?

```shell
I wanna to registe an REIGSTER_OP(Conv2D_New).
But the `c->set_output(0,c->Matrix())` only support two dimensions.
the conv need four dimensions, i don't know how to do it
```

### Standalone code to reproduce the issue

```shell
c->set_output(0,c->Matrix());
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @acknowledgexiongdei !
Could you refer this document ["create an op"](https://www.tensorflow.org/guide/create_op) to register the op and test it.
Thank you

**Comment by acknowledgexiongdei** [comment]
> Hi @acknowledgexiongdei ! Could you refer this document ["create an op"](https://www.tensorflow.org/guide/create_op) to register the op and test it. Thank you
Thank you, i changed the` c->Matrix` to `c->MakeShape`. then it success with four parameter.
