### ISSUE TITLE
TFLite C API on Android Studio

### ISSUE THREAD

**Issue by acebenson0704** [tensorflow/tensorflow#56922]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: No
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**:2.9.0
-   **Python version**:
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**:

### Describe the problem

I'm currently run tflite model on Android app by C API, I download version 2.9.0 shared library from [TensorFlow Lite AAR hosted at MavenCentral](https://search.maven.org/artifact/org.tensorflow/tensorflow/tensorflow-lite) and include requied header files as [DOC](https://github.com/tensorflow/tensorflow/blob/r2.9/tensorflow/lite/g3doc/guide/android.md) mentioned.

Load tflite model and create interpreter works perfectly. And `TfLiteInterpreterGetSignatureCount` return number is also correct.

But `TfLiteInterpreterGetSignatureKey` shows **undefined reference to `TfLiteInterpreterGetSignatureKey`**.

Does C API support these two function currently?

### Source code / logs

_native-lib.cpp_
```
extern "C" JNIEXPORT jstring JNICALL
Java_com_example_ainl_MainActivity_loadTfliteModelJNI(
        JNIEnv* env,
        jobject /* this */) {


    TfLiteModel* model = TfLiteModelCreateFromFile("/data/data/com.example.ainl/train.tflite");

    TfLiteInterpreter* interpreter = TfLiteInterpreterCreate(model, NULL);
    TfLiteInterpreterAllocateTensors(interpreter);

    const char* tflite_version = TfLiteVersion();
    int num_signature = TfLiteInterpreterGetSignatureCount(interpreter);

    /** Get each signature key */
    const char* signature_key = TfLiteInterpreterGetSignatureKey(interpreter, 0);
    /** Get each signature key input number */
    TfLiteSignatureRunner* runner = TfLiteInterpreterGetSignatureRunner(interpreter, "train");
    int num_input = TfLiteSignatureRunnerGetInputCount(runner);

    char status_string[100];
    sprintf(status_string, "--- tflite version: %s ---\n", tflite_version);
    sprintf(status_string + strlen(status_string), "#Signature: %d\n", num_signature);

    sprintf(status_string + strlen(status_string), "0th signature key: %s\n", signature_key);
    sprintf(status_string + strlen(status_string), "#input of key [train]: %d\n", num_input);

    return env->NewStringUTF(status_string);
}
```

**Comment by mohantym** [comment]
Hi @achalshah20 !
Would it be possible to give a reproducible code in colab too (including the c lib , running with dependent Tensorflow lib files and the above cpp file ).

**Comment by acebenson0704** [comment]
Hi thank you for your reply.
Sorry I cannot provide source code because of company policies.

But It's a basic Android Studio Project based on **Use TFLite C API** in this [doc](https://github.com/tensorflow/tensorflow/blob/r2.9/tensorflow/lite/g3doc/guide/android.md#use-tflite-c-api).

And as the above _native.lib_  code shows, it simply load pre-trained tflite model and get some properties through c api .

More information:
 _CMakeLists.txt_: Add following lines for tflite and add tflite-lib into `target_link_libraries`
```
# ==================== For TFLite ====================
# Specify where to find the header files for TF Lite C++
set(JNI_DIR
        ${CMAKE_CURRENT_SOURCE_DIR}/../jni)
include_directories(${JNI_DIR})

add_library( tflite-lib SHARED IMPORTED )
set_target_properties( tflite-lib PROPERTIES IMPORTED_LOCATION
        ${JNI_DIR}/${ANDROID_ABI}/libtensorflowlite_jni.so )
# ==================== For TFLite ====================
```

_app/src/main/jni/_: Add all header files and shared library as doc (Most of header files is unused here.)

```bash
C:.
│  allocation.h
│  arena_planner.h
│  builtin_ops.h
│  builtin_op_data.h
│  context.h
│  context_util.h
│  create_op_resolver.h
│  error_reporter.h
│  external_cpu_backend_context.h
│  graph_info.h
│  interpreter.h
│  interpreter_builder.h
│  interpreter_options.h
│  interpreter_test_util.h
│  logger.h
│  memory_planner.h
│  minimal_logging.h
│  model.h
│  model_builder.h
│  mutable_op_resolver.h
│  optional_debug_tools.h
│  op_resolver.h
│  portable_type_to_tflitetype.h
│  shared_library.h
│  signature_runner.h
│  simple_memory_arena.h
│  simple_planner.h
│  stateful_error_reporter.h
│  stderr_reporter.h
│  string_type.h
│  string_util.h
│  tensorflow_profiler_logger.h
│  tflite_with_xnnpack_optional.h
│  type_to_tflitetype.h
│  util.h
│  version.h
│  
├─arm64-v8a
│      libtensorflowlite_jni.so
│      
├─armeabi-v7a
│      libtensorflowlite_jni.so
│      
└─c
        builtin_op_data.h
        common.h
        common_internal.h
        c_api.h
        c_api_experimental.h
        c_api_for_testing.h
        c_api_internal.h
        c_api_opaque.h
        c_api_types.h
```

_build.gradle(:app)_: Add abiFilters to cmake
```
android {
    defaultConfig {
        ...
        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17 -frtti -fexceptions'
                abiFilters 'armeabi-v7a', 'arm64-v8a'
            }
        }
        ...
    }
}
```

The rest part is **exactly** the same as Android Studio Native C/C++ Template.

**Comment by pjpratik** [comment]
Hi @acebenson0704 

TFLite C API should support the `TfLiteInterpreterGetSignatureKey` as given in the experimental api:

https://github.com/tensorflow/tensorflow/blob/515dbdd45fdbc288667b3b3c7840b8ab2a527501/tensorflow/lite/core/c/c_api_experimental.cc#L157-L164

Can you please check in latest version and see if the behaviour still exists?

Thanks.
