### ISSUE TITLE
Failure to use selectively build TFLite frameworks on iOS

### ISSUE THREAD

**Issue by emenshoff** [tensorflow/tensorflow#56925]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.6

### Custom Code

No

### OS Platform and Distribution

iOS 14.1 - target build, MacOSX 10.15.7 and XCode 12.4 for building

### Mobile device

Apple iPad, iOS 15.3

### Python version

3.9

### Bazel version

3.4.0

### GCC/Compiler version

Apple clang version 12.0.0 (clang-1200.0.32.29)

### CUDA/cuDNN version

no CUDA used

### GPU model and memory

no GPU

### Current Behaviour?

```shell
I've successfully built TFLite frameworks for my iOS project, following the "Selectively build" instructions.

bash tensorflow/lite/ios/build_frameworks.sh \
  --input_models=modelX.tflite,modelY.tflite \
  --target_archs=arm64

After that, I added both frameworks (TensorFlowLiteSelectTfOps and TensorFlowLiteC) to my XCode project (using Pods) and updated "Other linker options" with "-force_load $(SRCROOT)/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps". 

Project failed to build on the linking stage.

Besides that, the custom-built TensorFlowLiteSelectTfOps.framework binary weights about 1Gb, that is too much comparing with the same custom build (with the same models) for Android which size was only 6 Mb.

Seems like the Bazel build  script for "selective" build with models works wrong and does not build static TensorFlowLiteSelectTfOps library as expected.

Please help!
```

### Standalone code to reproduce the issue

```shell
No custom code. All builds were made using Bazel, according the instructions https://www.tensorflow.org/lite/guide/build_ios#selectively_build_tflite_frameworks
```

### Relevant log output

```shell
Bazel build was successful. XCode build fails with 
with linker error:

Undefined symbols for architecture arm64:
  "google::protobuf::DoubleValue::MergeFrom(google::protobuf::DoubleValue const&)", referenced from:
      tensorflow::MetricEntry::MergeFrom(tensorflow::MetricEntry const&) in TensorFlowLiteSelectTfOps(test_log.pb.o)
  "google::protobuf::DoubleValue::InternalSerializeWithCachedSizesToArray(unsigned char*) const", referenced from:
      tensorflow::MetricEntry::InternalSerializeWithCachedSizesToArray(unsigned char*) const in TensorFlowLiteSelectTfOps(test_log.pb.o)
  "google::protobuf::DoubleValue* google::protobuf::Arena::CreateMaybeMessage<google::protobuf::DoubleValue>(google::protobuf::Arena*)", referenced from:
      tensorflow::MetricEntry::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in TensorFlowLiteSelectTfOps(test_log.pb.o)
      tensorflow::MetricEntry::MergeFrom(tensorflow::MetricEntry const&) in TensorFlowLiteSelectTfOps(test_log.pb.o)
 
**** AND 100+ same signature errors with C++ namespaces referencing google::protobuf library's functions. ****
```
</details>

**Comment by mohantym** [comment]
Hi @emenshoff !
Could you check with below steps and let us know.

1. Go to your Project
2. Select your Target
3. Go to Build Phases
4. Open Link Binary With Libraries
5. Press + to Add the SelectOps.framework 

Attached relevant thread for reference. [1](https://stackoverflow.com/a/33530891), [2](https://docs.sentiance.com/sdk/troubleshooting/ios/error-undefined-symbols-for-architecture-arm64).

Thank you!

**Comment by emenshoff** [comment]
Thank you, @mohantym!

Should I remove "-force_load $(SRCROOT)/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.xcframework/ios-arm64/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps" from Other linker options after adding the framework to linker targets manually?

Thanks in advance!

**Comment by emenshoff** [comment]
After removing -force_load option and adding framework manually (step 6) the project has been built successfully, but I've got runtime error when loading my .tflite model:

"Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
TensorFlow Lite Error: Node number 0 (FlexResizeBilinear) failed to prepare."

Seems like the Custom Ops framework was not initialised correctly on runtime :(

**Comment by mohantym** [comment]
@emenshoff !

You should not remove the force load step too.
Above steps are add-ons for trouble shooting.

Thank you!

**Comment by emenshoff** [comment]
I tried all the options above.
And got another errors:

Undefined symbols for architecture arm64:
  "tflite::logging_internal::MinimalLogger::LogFormatted(tflite::LogSeverity, char const*, char*)", referenced from:
      tflite::StderrReporter::Report(char const*, char*) in TensorFlowLiteSelectTfOps(stderr_reporter.o)
  "tflite::ConvertTensorType(tflite::TensorType, TfLiteType*, tflite::ErrorReporter*)", referenced from:
      tflite::InterpreterBuilder::ParseTensors(flatbuffers::Vector<flatbuffers::Offset<tflite::Buffer> > const*, flatbuffers::Vector<flatbuffers::Offset<tflite::Tensor> > const*, tflite::Subgraph*) in TensorFlowLiteSelectTfOps(interpreter_builder.o)
  "tflite::ParseOpData(tflite::Operator const*, tflite::BuiltinOperator, tflite::ErrorReporter*, tflite::BuiltinDataAllocator*, void**)", referenced from:
      tflite::InterpreterBuilder::ParseNodes(flatbuffers::Vector<flatbuffers::Offset<tflite::Operator> > const*, tflite::Subgraph*) in TensorFlowLiteSelectTfOps(interpreter_builder.o)


****and  100+ same errors referencing tflite:: and ruy::  namespaces  :(

**Comment by sachinprasadhs** [comment]
Hi, For the build flags could you try specifying `--target_archs=x86_64,armv7,arm64` and see if you're able to build static `TensorFlowLiteSelectTfOps` library. Thanks!

**Comment by emenshoff** [comment]
--target_archs=x86_64,armv7,arm64 option does not work, because x86 platform for TensorFlowLiteSelectTfOps are not supported by Google anymore.

**Comment by emenshoff** [comment]
I've found the solution:
in file: /tensorflow/lite/ios/build_frameworks.sh,
in function: generate_flex_framework,
just add option "--config=monolithic" to bazel build options at the end of function:

 bazel build -c opt --config=ios --config=monolithic  --ios_multi_cpus="${TARGET_ARCHS}" "${target}"

After that all build errors were gone (tensorflow v2.9.1), and my app starts and works fine!

Thank you guys!, Have a nice day!

**Comment by sachinprasadhs** [comment]
I'm glad that your issue is resolved, could you please close this issue. Thanks!
