### ISSUE TITLE
Tensorflow, llvmlite, mac M1 and poetry

### ISSUE THREAD

**Issue by oscar-defelice** [tensorflow/tensorflow#56921]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Apple Mac OS 12.5

### Python version

3.9.2

### Current Behaviour?

```shell
I am trying to add tensorflow to my (cross-platform) project. 
I am using poetry and conda.

The "bug" apparently is due to the missing pre-build wheel for m1 architecture of the llvmlite dependency.

**Note**: I cannot add `tensorflow-macos` to the project as it has to be cross-platform.
```

### Standalone code to reproduce the issue

```shell
simply I run `poetry add tensorflow` and I get the following message


note: This error originates from a subprocess, and is likely not a problem with pip.
  error: legacy-install-failure
  
  × Encountered error while trying to install package.
  ╰─> llvmlite
  
  note: This is an issue with the package mentioned above, not pip.
  hint: See above for output from the failure.
```

### Relevant log output

```shell
note: This error originates from a subprocess, and is likely not a problem with pip.
  error: legacy-install-failure
  
  × Encountered error while trying to install package.
  ╰─> llvmlite
  
  note: This is an issue with the package mentioned above, not pip.
  hint: See above for output from the failure.
```
</details>

**Comment by gadagashwini** [comment]
Hi @oscar-defelice, To install llvmlite, follow the workarounds mentioned on similar thread [here](https://github.com/numba/llvmlite/issues/693#issuecomment-909501195). 

For users of Apple M1 computers, it is highly recommended to follow the instructions found [here](https://developer.apple.com/metal/tensorflow-plugin/) for smooth installation.Thank you!

**Comment by oscar-defelice** [comment]
Hello @gadagashwini, I do not have installation problems on my machine. 
I got issues when I install it through poetry (as a dependency for my project). 
The main problem is that I cannot add "tensorflow-macos" as the project has to be multiplatform.

**Comment by PietroAnsidei** [comment]
@oscar-defelice add this to your `pyproject.toml` to make it multiplatform
```
tensorflow = {version = "^2.9.1", platform = "linux"}
tensorflow-macos = {version = "^2.9.2", platform = "darwin"}
```

**Comment by SuryanarayanaY** [comment]
@oscar-defelice ,
Whether the [comment](https://github.com/tensorflow/tensorflow/issues/56921#issuecomment-1259797988) above is of any help to you?

**Comment by oscar-defelice** [comment]
@SuryanarayanaY Thank you for pointing this out. I missed the comment since I simply got rid of poetry as dependency manager because of these difficulties.

I tried just now and it seems to work fine with the comment by @PietroAnsidei.

Thank you both!

**Comment by lamuertepeluda** [comment]
I am joining late this party, however, thanks to precious comment from @PietroAnsidei this worked on my Macbook Pro M1 and Python 3.10.6 (via pyenv).

```bash
poetry add tensorflow-macos@2.9 --platform darwin
poetry add tensorflow-metal@0.5 --platform darwin
poetry add tensorflow@2.9 --platform linux
```

I then run the script on step 4 of https://developer.apple.com/metal/tensorflow-plugin/ to make sure it worked. It didn't with latest TF 2.11, but it did with the versions above (as per Apple compatibility table).
