### ISSUE TITLE
Xcode 13.4.1 - No such module 'TensorFlowLiteCCoreML'  

### ISSUE THREAD

**Issue by PayalUmraliya** [tensorflow/tensorflow#56923]
<img width="457" alt="Screenshot 2022-07-27 at 5 14 42 PM" src="https://user-images.githubusercontent.com/14552882/181239038-d95eff4e-be92-4021-9447-9e688efa3484.png">
<img width="779" alt="Screenshot 2022-07-27 at 5 14 54 PM" src="https://user-images.githubusercontent.com/14552882/181239058-f630c89d-ac1e-4000-ad67-422fd76e2e1b.png">

No such module 'TensorFlowLiteCCoreML' getting this error. 
xcode Version 13.4.1 (13F100)
Tried pod install and opening .xcworkspace only. 

Please note that i am getting this error only when i archive the build. Any help would be appreciated!

Thanks,
Payal U.

**Comment by mohantym** [comment]
Hi @PayalUmraliya ! 

Sorry for the late response.  Could you change the subspec to only ['CoreML']  and try with below code(Swift version, Change to Java version using Android studio)
```

let coreMLDelegate = CoreMLDelegate() # instantiates CoreMLDelegate Object
var interpreter: Interpreter

    // Core ML delegate will only be created for devices with Neural Engine
if coreMLDelegate != nil {
      interpreter = try Interpreter(modelPath: modelPath,
                                    delegates: [coreMLDelegate!]).  # Add the found CoreMLDelegate to interpreter
    } 
else {
      interpreter = try Interpreter(modelPath: modelPath)
    }
  
```

[Reference](https://www.tensorflow.org/lite/performance/coreml_delegate#trying_the_core_ml_delegate_on_your_own_model)

Thank you!
