### ISSUE TITLE
Efficiently get an equal number of per class data point continuously with `tf.data` API. 

### ISSUE THREAD

**Issue by innat** [tensorflow/tensorflow#56934]
[Info]
```
TensorFlow: 2.6
Environment: Kaggle / Colab
Accelerator: TPU / GPU
```

# Current Behaviour

I am trying to get equal number of sample per class within a batch of data from `tf.data` API. With `batch_size = 14` and `sample_per_class = 3`, I'm expecting to get the following output for `num_classes = 5`:

```yaml
1st batch: [1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5]
2nd batch: [5, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5]
```

# Standalone code to reproduce the issue

Here is the standalone code and approach so far.

```python

def dataset_for_class(i):
    i = tf.cast(i, tf.int32)
    return dataset.filter(lambda label: label == i)

num_classes = 1000
num_contiguous_instances = 2

dataset = tf.random.uniform([num_classes], maxval=num_classes, dtype=tf.int32).numpy()
dataset = tf.data.Dataset.from_tensor_slices(dataset)
dataset = tf.data.Dataset.range(num_classes).interleave(
    dataset_for_class,
    cycle_length=num_classes,
    block_length=num_contiguous_instances,
)
dataset = dataset.prefetch(tf.data.AUTOTUNE)
list(dataset.as_numpy_iterator())
[1, 1, 2, 2, 4, 4, 6, 7, 8, 8, 10, 10, 11, 12, ...]
# 6 appears 1 time because of dummy random input.
```
```bash
%%timeit
a = next(iter(dataset))
16.6 ms ± 205 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

The issue arises when `num_classes` gets bigger, for example, **image-net** (1000 classes). It gets too slow to train the model, GPU/TPU both. I'm looking for an efficient solution with `tf.data` API.

**Comment by sushreebarsa** [comment]
@innat I tried to replicate the issue on colab, could you please have a look at the gist [here](https://colab.research.google.com/gist/sushreebarsa/34abae2abf95be8654a6d4515ed6cf3c/untitled698.ipynb#scrollTo=cOMgw6M88GMq) and confirm the same.
Thank you!

**Comment by innat** [comment]
@sushreebarsa Thanks for checking. 
Yes, the code I've shared above, should be run without giving any sort of error. The main problem is, the way we are gathering same class side by side (`[1, 1, 1, 2, 2, 3, 3, ..]`) is too slow in actual training. For example, if you run this code on ImageNet (number of class 1000), you would able to see the effect.

**Comment by innat** [comment]
Any update on this?

**Comment by aaudiber** [comment]
The use of `filter` in `dataset_for_class` means that you will need to iterate through all of the data once per class. Each iteration through the data will drop around 99.9% of the data, so that it can filter out just the one class you are looking for.

Some ideas to make this more efficient:
- Use [Dataset.rejection_resample](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#rejection_resample) to get the desired distribution.
- Store each class separately, so that you don't need to do any filtering.
