### ISSUE TITLE
TEST Failure: //tensorflow/lite/tools/optimize:quantize_model_test 

### ISSUE THREAD

**Issue by psunn** [tensorflow/tensorflow#56931]
### 1. System information
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu

TensorFlow built from latest master https://github.com/tensorflow/tensorflow/commit/113030af3b8add4b4fd94a64d834c273b722e2bf

### 2. Code

`bazel test //tensorflow/lite/tools/optimize:quantize_model_test --test_output=all`

```
[==========] 64 tests from 29 test suites ran. (4 ms total)
[  PASSED  ] 54 tests.
[  FAILED  ] 10 tests, listed below:
[  FAILED  ] QuantizeSoftmaxTest.VerifySoftmaxQuantization
[  FAILED  ] QuantizeAvgPoolTest.VerifyAvgPoolQuantization
[  FAILED  ] QuantizeResourcesModelTest/QuantizeResourcesModelTest.GraphIsFullyQuantized/0, where GetParam() = 8-byte object <09-FF 58-BD 00-00 00-00>
[  FAILED  ] QuantizeResourcesModelTest/QuantizeResourcesModelTest.GraphIsFullyQuantized/1, where GetParam() = 8-byte object <09-FD 58-BD 01-00 00-00>
[  FAILED  ] QuantizeResourcesModelTest/QuantizeResourcesModelTest.GraphIsFullyQuantized/2, where GetParam() = 8-byte object <09-F6 58-BD 02-00 00-00>
[  FAILED  ] QuantizeResourcesModelTest/QuantizeResourcesModelTest.GraphIsFullyQuantized/3, where GetParam() = 8-byte object <09-00 00-00 03-00 00-00>
[  FAILED  ] QuantizeResourcesModelTest/QuantizeResourcesModelTest.GraphIsFullyQuantized/4, where GetParam() = 8-byte object <07-00 00-00 00-00 00-00>
[  FAILED  ] QuantizeResourcesModelTest/QuantizeResourcesModelTest.GraphIsFullyQuantized/5, where GetParam() = 8-byte object <07-5B BE-57 01-00 00-00>
[  FAILED  ] QuantizeResourcesModelTest/QuantizeResourcesModelTest.GraphIsFullyQuantized/6, where GetParam() = 8-byte object <07-FF 58-BD 02-00 00-00>
[  FAILED  ] QuantizeResourcesModelTest/QuantizeResourcesModelTest.GraphIsFullyQuantized/7, where GetParam() = 8-byte object <07-FD 58-BD 03-00 00-00>

10 FAILED TESTS
```

**Comment by psunn** [comment]
TESTs failures seem caused by recent [update of FlatBuffer](https://github.com/tensorflow/tensorflow/commit/625a4045bc0728c0f3d1b63e05749201f8b401dd).

**Comment by mohantym** [comment]
Hi @psunn !

Test is passing with Bazel 5.1.1 and Master branch with Colab.  Attached [gist ](https://colab.sandbox.google.com/gist/mohantym/3d07e0b8e037b3bada964cf33f2af96d/tensorflow-ranking.ipynb#scrollTo=zcLb762uZlQv)for reference. Could you let us know your Bazel version.

Thank you!

**Comment by psunn** [comment]
Hi @mohantym ,

Thank you for response. I re-run your colab, seem those tests fail as reported above. Please have a look.

**Comment by mohantym** [comment]
@psunn ! Thanks for the reply.

@gowthamkpr  ! 
Could you look at this issue. Attached [gist ](https://colab.sandbox.google.com/gist/mohantym/3d07e0b8e037b3bada964cf33f2af96d/tensorflow-ranking.ipynb#scrollTo=skRg4_WPi616)from the master branch for reference. 

Thank you!

**Comment by psunn** [comment]
Closed as tests passed now, thanks.
