### ISSUE TITLE
Tensorflow lite for microcontroller. VAR_HANDLE requires resource variables.

### ISSUE THREAD

**Issue by FragrantRookie** [tensorflow/tensorflow#56932]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

ubuntu20

### Python version

3.9

```shell
A bug happened!
When I run this code
TfLiteTensor* input1 = interpreter1.input(0);

the console return the following text:

VAR_HANDLE requires resource variables. Please create ResourceVariables and pass it to the interpreter.
Node VAR_HANDLE (number 1f) failed to prepare with status 1


I have two tflite models.One of them is OK, but the other cannot run and return this text.
However, I have no problem running both with tensorflow Lite
```

### Standalone code to reproduce the issue

```shell
const tflite::Model* model1 = ::tflite::GetModel(CDEC_1_1600_Zz_tflite);
  if (model1->version() != TFLITE_SCHEMA_VERSION) {
    TF_LITE_REPORT_ERROR(&micro_error_reporter,
                         "Model provided is schema version %d not equal "
                         "to supported version %d.\n",
                         model1->version(), TFLITE_SCHEMA_VERSION);
  }

  tflite::AllOpsResolver micro_op_resolver;
  // Build an interpreter to run the model with.
  tflite::MicroInterpreter interpreter1(model1, micro_op_resolver, tensor_arena,
                                       tensor_arena_size,
                                       &micro_error_reporter);
  interpreter1.AllocateTensors();

  // Get information about the memory area to use for the model's input.
  TfLiteTensor* input1 = interpreter1.input(0);
  TfLiteTensor* input2 = interpreter1.input(1);
  TfLiteTensor* input3 = interpreter1.input(2);
  TfLiteTensor* input4 = interpreter1.input(3);
  TfLiteTensor* input5 = interpreter1.input(4);
  TfLiteTensor* input6 = interpreter1.input(5);
```

### Relevant log output

```shell
VAR_HANDLE requires resource variables. Please create ResourceVariables and pass it to the interpreter.
Node VAR_HANDLE (number 1f) failed to prepare with status 1
```
</details>

**Comment by FragrantRookie** [comment]
Here are the two models.
[https://drive.google.com/drive/folders/1UxQ7P9pVXuE79shGBIIyPI7wgY_FHYwJ?usp=sharing](url)
CDEC_1_1600_Zz.tflite has problem.
model_1.tflite has no problem.

**Comment by mohantym** [comment]
Hi @FragrantRookie !
Sorry for the late response. Could you check below code and let us know the results

 ```
 static tflite::MicroErrorReporter micro_error_reporter;
  error_reporter = &micro_error_reporter;

  // Say something to test error reporter
  error_reporter->Report("STM32 TensorFlow Lite test");

  // Map the model into a usable data structure
  model = tflite::GetModel(<yourmodel>);
  if (model->version() != TFLITE_SCHEMA_VERSION)
  {
    error_reporter->Report("Model version does not match Schema");
    while(1);
  }

  // Pull in only needed operations (should match NN layers). Template parameter
  // <n> is number of ops to be added. Available ops:
  // tensorflow/lite/micro/kernels/micro_ops.h
  static tflite::MicroMutableOpResolver<1> micro_op_resolver;

  // Add dense neural network layer operation
  tflite_status = micro_op_resolver.AddBuiltin(
      tflite::BuiltinOperator_FULLY_CONNECTED,
      tflite::ops::micro::Register_FULLY_CONNECTED());
  if (tflite_status != kTfLiteOk)
  {
    error_reporter->Report("Could not add FULLY CONNECTED op");
    while(1);
  }

  // Build an interpreter to run the model with.
  static tflite::MicroInterpreter static_interpreter(
      model, micro_op_resolver, tensor_arena, kTensorArenaSize, error_reporter);
  interpreter = &static_interpreter;

  // Allocate memory from the tensor_arena for the model's tensors.
  tflite_status = interpreter->AllocateTensors();
  if (tflite_status != kTfLiteOk)
  {
    error_reporter->Report("AllocateTensors() failed");
    while(1);
  }

  // Assign model input and output buffers (tensors) to pointers
  input1 = interpreter->input(0);
  input2 = interpreter->input(1);
  input3 = interpreter->input(2);
  input4= interpreter->input(3);


```

[Reference.](https://www.digikey.com/en/maker/projects/tinyml-getting-started-with-tensorflow-lite-for-microcontrollers/c0cdd850f5004b098d263400aa294023)

**Comment by FragrantRookie** [comment]
Ok，I will try it.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 30, 2022 16:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tensorflow/tensorflow] Tensorflow lite for microcontroller.VAR_HANDLE requires resource variables. (Issue #56932)




 
Hi @FragrantRookie !
 Sorry for the late response. Could you check below code and let us know the results
 static tflite::MicroErrorReporter micro_error_reporter;  error_reporter = &amp;micro_error_reporter;  // Say something to test error reporter  error_reporter-&gt;Report("STM32 TensorFlow Lite test");  // Map the model into a usable data structure  model = tflite::GetModel(<yourmodel&gt;);  if (model-&gt;version() != TFLITE_SCHEMA_VERSION)  {    error_reporter-&gt;Report("Model version does not match Schema");    while(1);  }  // Pull in only needed operations (should match NN layers). Template parameter  // <n&gt; is number of ops to be added. Available ops:  // tensorflow/lite/micro/kernels/micro_ops.h  static tflite::MicroMutableOpResolver<1&gt; micro_op_resolver;  // Add dense neural network layer operation  tflite_status = micro_op_resolver.AddBuiltin(      tflite::BuiltinOperator_FULLY_CONNECTED,      tflite::ops::micro::Register_FULLY_CONNECTED());  if (tflite_status != kTfLiteOk)  {    error_reporter-&gt;Report("Could not add FULLY CONNECTED op");    while(1);  }  // Build an interpreter to run the model with.  static tflite::MicroInterpreter static_interpreter(      model, micro_op_resolver, tensor_arena, kTensorArenaSize, error_reporter);  interpreter = &amp;static_interpreter;  // Allocate memory from the tensor_arena for the model's tensors.  tflite_status = interpreter-&gt;AllocateTensors();  if (tflite_status != kTfLiteOk)  {    error_reporter-&gt;Report("AllocateTensors() failed");    while(1);  }  // Assign model input and output buffers (tensors) to pointers  input1 = interpreter-&gt;input(0);  input2 = interpreter-&gt;input(1);  input3 = interpreter-&gt;input(2);  input4= interpreter-&gt;input(3);  
Reference.

**Comment by FragrantRookie** [comment]
Maybe my version is different from yours. I need to modify some codes in order not to report errors.
When I run the following code：
```
	 tflite_status = micro_op_resolver.AddBuiltin(
	     tflite::BuiltinOperator_FULLY_CONNECTED,
	     tflite::ops::micro::Register_FULLY_CONNECTED());
```
the following error message appears：
`error: ‘Register_FULLY_CONNECTED’ is not a member of ‘tflite::ops::micro’; did you mean ‘tflite::Register_FULLY_CONNECTED’?`

**Comment by FragrantRookie** [comment]
I think of a question. If I open the tflite model with netron, a callonce will be displayed in it.

**Comment by mohantym** [comment]
@FragrantRookie !
Thanks for the update.

@sachinprasadhs !
Could you please look at this issue.

Thank you!

**Comment by FragrantRookie** [comment]
@mohantym @sachinprasadhs 
Thank you.
It has been solved by myself.
When using GRU or LSTM,the tflite will contains VAR_HANDLE layers.To avoid using VAR_HANDLE,the GRU or LSTM should set unroll=True,and stateful=False.

**Comment by FragrantRookie** [comment]
@mohantym @sachinprasadhs 
Thank you.
It has been solved by myself.
When using GRU or LSTM,the tflite will contains VAR_HANDLE layers.To avoid using VAR_HANDLE,the GRU or LSTM should set unroll=True,and stateful=False.
