### ISSUE TITLE
Daily builds of opencl tflite delegate are DOA on older android versions

### ISSUE THREAD

**Issue by lauriebyrum** [tensorflow/tensorflow#56930]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**:  yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Android 9 or 10, NOT reproducible on Android 11
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: Tested on Samsung Galaxy S8 and S9 with qualcomm
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**: daily build
-   **Python version**: N/A
-   **Bazel version (if compiling from source)**: N/A
-   **GCC/Compiler version (if compiling from source)**: N/A
-   **CUDA/cuDNN version**: N/A
-   **GPU model and memory**: Qualcomm
-   **Exact command to reproduce**: 

### Describe the problem
I am attempting to work around https://github.com/tensorflow/tensorflow/issues/56328 by pulling daily builds as recommended in that issue. However, the daily builds are not working on Android 9 or 10. Please either use the above issue to repro OR you probably can use the tests for https://github.com/tensorflow/tensorflow/commit/35b04bb55d3afdde8ac8f8c4a3ba7a055da4217b, which I believe is the breaking commit. 

Attempting to run gives this error: 
Failed to build program executable - Build program failureBC-src-code:68:7: error: no matching builtin function for call to 'native_exp'
    src = native_exp(src);
          ^~~~~~~~~~
    BC-src-code:68:7: note: candidate function not viable: no known conversion from 'half4' to 'float' for 1st argument; 
    src = native_exp(src);
          ^          ~~~
    BC-src-code:68:7: note: candidate function not viable: no known conversion from 'half4' to 'float  __attribute__((ext_vector_type(2)))' for 1st argument; 
    src = native_exp(src);
          ^          ~~~
    BC-src-code:68:7: note: candidate function not viable: no known conversion from 'half4' to 'float  __attribute__((ext_vector_type(3)))' for 1st argument; 
    src = native_exp(src);
          ^          ~~~
    BC-src-code:68:7: note: candidate function not viable: no known conversion from 'half4' to 'float  __attribute__((ext_vector_type(4)))' for 1st argument; 
    src = native_exp(src);
          ^          ~~~
    1 diagnostic(s) generated.

### Source code / logs
See above

**Comment by roserg** [comment]
Hi, should be fixed after this commit:
https://github.com/tensorflow/tensorflow/commit/732b161408bf1a1164599acc3d574c3cbe64a128
Tested on Adreno 304 with sdk version 23

**Comment by lauriebyrum** [comment]
I verified it on my s9 and s8. It's fixed. thanks @roserg !
