### ISSUE TITLE
build tensorflow-lite pip package arch x86_64 script error

### ISSUE THREAD

**Issue by edharman** [tensorflow/tensorflow#56944]
### System information

-   **OS Platform and Distribution  Linux Ubuntu 22.04 LTS
-   X86_64
-   **TensorFlow installed from git clone https://github.com/tensorflow/tensorflow.git tensorflow_src
-   
-   **Python version**: Python 3.10.4 
-   **GCC/Compiler version gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1)
-   **CUDA/cuDNN version**: n/a
-   **GPU model and memory**: n/a
-   **Exact command to reproduce**:
- user@host:~$ cd tensorflow_src/
user@host:~/tensorflow_src$ python3 tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh native
  File "/home/user/tensorflow_src/tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh", line 71
    armhf)
         ^
SyntaxError: unmatched ')'
user@host:~/tensorflow_src$ 

correcting this with an opening '(' on line 70 results in -

user@host:~/tensorflow_src$ python3 tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh native
  File "/home/user/tensorflow_src/tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh", line 18
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
                      ^
SyntaxError: invalid syntax
user@host:~/tensorflow_src$ 

trying to build tensorflow-runtime for x86 platform as package is required by pre-configured code originally destined for an Arm platform, rest of the code works ok.
I'm not a bash expert so didn't want to play further....

Grateful for any assistance you can give...

**Comment by mohantym** [comment]
Hi @edharman !
Could you check with below command with gcc 7.3 after cloning the repo.

`PYTHON=python3 tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh native`

You can also build using Cmake through below command.
```
make -C tensorflow/lite/tools/pip_package docker-build \
  TENSORFLOW_TARGET=armhf PYTHON_VERSION=3.7
```

Thank you!

**Comment by edharman** [comment]
Hi, 
PYTHON=python3 tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh native
...seems to fix the issue!,
Many Thanks

**Comment by edharman** [comment]
Yes, impressed with the speedy resolution, 
Good Work!!
