### ISSUE TITLE
Broken link to model mitigation guide for variable_scope (python)

### ISSUE THREAD

**Issue by afdreher** [tensorflow/tensorflow#56945]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### Current Behaviour?

```shell
The link to the model mitigation guide is broken in the documentation for variable_scope ([https://www.tensorflow.org/api_docs/python/tf/compat/v1/variable_scope]).  In the second paragraph of "Migrate to TF2," the current link points to [https://www.tensorflow.org/api_docs/python/tf/compat/v1/www.tensorflow.org/guide/migrate/model_mapping] instead of [https://www.tensorflow.org/guide/migrate/model_mapping].  The link on Line 2154 just needs "https:" added to prevent it from being treated as a relative URL.
```

### Standalone code to reproduce the issue

```shell
It's live in the current documentation.  https://www.tensorflow.org/api_docs/python/tf/compat/v1/variable_scope
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@afdreher Thank you for raising this issue.
The right link is already reflecting in the master branch
https://github.com/tensorflow/tensorflow/blob/03e6e2af40f53f69e5fab1151235b0880252c21c/tensorflow/python/ops/variable_scope.py#L204

It will reflect soon in the TF documentation. Please let us know if this information helps?
Thank you!
