### ISSUE TITLE
Custom op's quantized version is not called, custom op's input and output are still floating-point

### ISSUE THREAD

**Issue by hguihot** [tensorflow/tensorflow#56950]
_TL;DR_: All the convolution operators are quantized in the TFLite model as expected, but the custom operator is not.

I built TensorFlow from source (SHA: e0032f9d64d22e4b6f20102c35045247fe704596) after adding a new custom operator in `tensorflow/core/user_ops/dummy.cc` (see code below).

I then created the following model with a few convolutions and the custom op. The goal is to have the whole TFLite model being quantized, as showed in this diagram:

```mermaid
  flowchart
    id1(quantized input)-->conv0["Convolution"]
    conv0-->dummy["Dummy Op"]
    dummy-->conv1["Convolution"]
    conv1-->id2(quantized output 0)
    conv0-->conv2["Convolution"]
    conv2-->conv3["Convolution"]
    conv3-->id3(quantized output 1)
    style id1 stroke-width:0px,fill-opacity:0
    style id2 stroke-width:0px,fill-opacity:0
    style id3 stroke-width:0px,fill-opacity:0
```
Instead, I'm getting a TFLite model in which all the convolutions are indeed quantized, but the custom op is still floating-point and the model includes Dequantize/Quantize operators before/after the custom op. **Are quantized custom ops supported? If so, what's missing here to make sure the quantized version of the custom operator ends up in the TFLite model?**
```mermaid
  flowchart
    id1(quantized input)-->conv0["Convolution"]
    conv0-->dequant["Dequantize"]
    dequant--floating-point-->dummy["Dummy Op"]
    dummy--floating-point-->quant["Quantize"]
    quant-->conv1["Convolution"]
    conv1-->id2(quantized output 0)
    conv0-->conv2["Convolution"]
    conv2-->conv3["Convolution"]
    conv3-->id3(quantized output 1)
    style id1 stroke-width:0px,fill-opacity:0
    style id2 stroke-width:0px,fill-opacity:0
    style id3 stroke-width:0px,fill-opacity:0
```

Python code to build and convert model (three TFLite models will be created: one with no optimization, one with floating-point input/outputs with optimizations, and the last one with quantized input/outputs with optimizations, which is the one most relevant to this issue):
```
import tensorflow as tf

def quant(x):
    return tf.quantization.fake_quant_with_min_max_args(x, -1, 1, 8, False)

class QConv(tf.keras.layers.Conv2D):
    def __init__(self, filters, kernel_size = 3):
        super().__init__(filters = filters, kernel_size = kernel_size)

    def call(self, bottom):
        return quant(self.convolution_op(bottom, quant(self.kernel)))

def tflite_model(save_path, tflite_path, input_type = tf.float32, output_type = tf.float32, optimize = False):
    converter = tf.lite.TFLiteConverter.from_saved_model(save_path)
    if optimize:
        converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.allow_custom_ops = True
    converter.inference_input_type = input_type
    converter.inference_output_type = output_type
    tflite_model = converter.convert()
    with open(tflite_path, "wb") as f:
        f.write(tflite_model)
    print(f"TFLite file saved in {tflite_path}")

input_tensor = tf.keras.Input(batch_size=1, shape=(256, 256, 4), name='input')
output = quant(input_tensor)

# First convolution
layer = QConv(filters=32)
output = layer(output)

# Split in the model: DummyOp on one side, convolution on the other
output0 = tf.dummy_op(output)
output0 = quant(output0)

layer = QConv(filters=32)
output1 = layer(output)

# Another convolution
layer = QConv(filters=16)
output0 = layer(output0)

layer = QConv(filters=16)
output1 = layer(output1)

model = tf.keras.Model(inputs=[input_tensor], outputs=[output0, output1])

save_path = "/tmp/dummy_model"
model.save(save_path)

# Floating-point model, not optimized
tflite_model(save_path, "/tmp/dummy_not_optimized.tflite")

# Floating-point model, optimized
tflite_model(save_path, "/tmp/dummy_float32.tflite", optimize=True)

# Quantized model, optimized
tflite_model(save_path, "/tmp/dummy_int8.tflite", input_type=tf.int8, output_type=tf.int8, optimize=True)
```

C++ code for custom operator in `tensorflow/core/user_ops/dummy.cc`:
```
#include "tensorflow/core/framework/common_shape_fns.h"
#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/op_kernel.h"

REGISTER_OP("DummyOp")
    .Attr("T: {int8, qint8, quint8, float}")
    .Input("input: T")
    .Output("output: T")
    .SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
        c->set_output(0, c->input(0));  // Output is same shape as input's.
        return tensorflow::Status::OK();
    });

class DummyOp : public tensorflow::OpKernel {
 public:
  using tensorflow::OpKernel::OpKernel;

  void Compute(tensorflow::OpKernelContext* context) override {
    // Allocates output tensor, does not compute anything.
    const tensorflow::Tensor& input_tensor = context->input(0);
    tensorflow::Tensor* output_tensor = NULL;
    OP_REQUIRES_OK(context, context->allocate_output(0, input_tensor.shape(),
                                                     &output_tensor));
  }
};

REGISTER_KERNEL_BUILDER(Name("DummyOp").Device(tensorflow::DEVICE_CPU).TypeConstraint<int8_t>("T"), DummyOp);
REGISTER_KERNEL_BUILDER(Name("DummyOp").Device(tensorflow::DEVICE_CPU).TypeConstraint<tensorflow::qint8>("T"), DummyOp);
REGISTER_KERNEL_BUILDER(Name("DummyOp").Device(tensorflow::DEVICE_CPU).TypeConstraint<tensorflow::quint8>("T"), DummyOp);
REGISTER_KERNEL_BUILDER(Name("DummyOp").Device(tensorflow::DEVICE_CPU).TypeConstraint<float>("T"), DummyOp);
```

**Comment by hguihot** [comment]
Here is what the TFLite model looks like:
![dummy_int8](https://user-images.githubusercontent.com/77295044/181848711-94ea0acc-77a0-4a16-9273-c2b51c514550.png)

**Comment by mohantym** [comment]
Hi @hguihot !
Could you use a representative dataset and use int8 ops and inference type to get integer quantized model.

```

def representative_data_gen():
  for input_value in tf.data.Dataset.from_tensor_slices(train_images).batch(1).take(100):
    yield [input_value]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
# Ensure that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8] // use tf.lite.OpsSet.SELECT_TF_OPS if you face select ops issue.
# Set the input and output tensors to uint8 (APIs added in r2.3)
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
converter.allow_custom_ops = True // to accomodate custom op
```s 
tflite_model_quant = converter.convert()

**Comment by hguihot** [comment]
I used the following function (from the [TensorFlow post-training quantization page](https://www.tensorflow.org/lite/performance/post_training_quantization)):
```
def representative_data_gen():
    for _ in range(100):
      data = np.random.rand(1, 256, 256, 4)
      yield [data.astype(np.float32)]
```
I also added the following 2 lines in my Python code in the `tflite_model()` function:
```
    converter.representative_dataset = representative_data_gen
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
```
With only those 2 changes it failed to convert the model because `DummyOp` was unknown. I then added the registration of the `DummyOp` TFLite operator in both [register.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/register.cc) and [register_ref.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/register_ref.cc):
```
TfLiteStatus DummyOpPrepare(TfLiteContext* context, TfLiteNode* node) {
  TF_LITE_ENSURE_EQ(context, NumInputs(node), 1);
  TF_LITE_ENSURE_EQ(context, NumOutputs(node), 1);
  auto input = GetInput(context, node, 0);
  auto output = GetOutput(context, node, 0);
  return context->ResizeTensor(context, output, TfLiteIntArrayCopy(input->dims));
}

TfLiteStatus DummyOpEval(TfLiteContext* context, TfLiteNode* node) {
  TfLiteTensor* output;
  TF_LITE_ENSURE_OK(context, GetOutputSafe(context, node, 0, &output));
  memset(output->data.data, 0, output->bytes);
  return kTfLiteOk;
}

TfLiteRegistration* Register_DUMMY_OP() {
  static TfLiteRegistration r = {NULL, NULL, DummyOpPrepare, DummyOpEval};
  return &r;
}
```
And where some other custom ops are currently registered (`Mfcc` for example) I added:
```
  AddCustom("DummyOp", Register_DUMMY_OP());
```
After updating the environment the conversion succeeded (and took a bit longer because of the calibration), but the model still shows the same problem, i.e. the model includes Dequantize/Quantize operators before/after the custom op.

**Comment by mohantym** [comment]
@hguihot ! Thanks for the update.  Could you give one more try with below changes

```
def representative_data_gen():
    for _ in range(100):
      data = np.random.rand(1, 256, 256, 4)
      yield [data.astype(np.int8)]

converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = np.int8
converter.inference_output_type = np.int8
```

You can also find quantization issue from your side using our recently introduced feature ["quantization_debugger"](https://www.tensorflow.org/lite/performance/quantization_debugger)


Thank you!

**Comment by hguihot** [comment]
Using `int8` data for the representative dataset does not work, I get the following error:
```
ValueError: Cannot set tensor: Got value of type INT8 but expected type FLOAT32 for input 0, name: serving_default_input:0 
```

As far as the [quantization debugger](https://www.tensorflow.org/lite/performance/quantization_debugger) is concerned, I couldn't find anything that was relevant to this issue. It seems to be mostly about identifying problematic layers as far as quality/precision is concerned.

**Comment by mohantym** [comment]
Ok @hguihot !
Thanks for the update.

@sachinprasadhs ! 
Could you look at this issue.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
