### ISSUE TITLE
bazel build tflite ：xnnpack/assembly.h not found

### ISSUE THREAD

**Issue by Dclpwos** [tensorflow/tensorflow#56957]
**System information** 
os:win11
tfv ersion:2.9.0
bazel version:5.1.1
python version:3.8.12
android sdk:31
ndk version:21.4.7075529
the build command:
bazel build -c opt  --cxxopt="--std=c++11"  --fat_apk_cpu=arm64-v8a --config=android_arm64 //tensorflow/lite:libtensorflowlite.so --verbose_failures
log:
ERROR: C:/users/dcl/_bazel_dcl/4iqg5dqe/external/XNNPACK/BUILD.bazel:10079:19: Compiling src/f32-gemm/gen/1x12-minmax-aarch64-neonfma-cortex-a53.S failed: (Exit 1): clang failed: error executing command
  cd /d C:/users/dcl/_bazel_dcl/4iqg5dqe/execroot/org_tensorflow
  SET ANDROID_BUILD_TOOLS_VERSION=32.0.0
    SET ANDROID_NDK_API_LEVEL=21
    SET ANDROID_NDK_HOME=D:/sdk/ndk/21.4.7075529
    SET ANDROID_SDK_API_LEVEL=31
    SET ANDROID_SDK_HOME=D:/sdk
    SET PATH=D:\Program Files\msys64\usr\bin;D:\Program Files\msys64\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\WindowsPowerShell\v1.0;D:\ProgramData\Miniconda3;D:\ProgramData\Miniconda3\Library\mingw-w64\bin;D:\ProgramData\Miniconda3\Library\usr\bin;D:\ProgramData\Miniconda3\Library\bin;D:\ProgramData\Miniconda3\Scripts;D:\ProgramData\Miniconda3\bin;D:\ProgramData\Miniconda3\condabin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\libnvvp;D:\ProgramData\Miniconda3;D:\ProgramData\Miniconda3\Library\mingw-w64\bin;D:\ProgramData\Miniconda3\Library\usr\bin;D:\ProgramData\Miniconda3\Library\bin;D:\ProgramData\Miniconda3\Scripts;C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\NVIDIA Corporation\Nsight Compute 2022.1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;D:\Program Files\Java\jdk-11\bin;D:\sdk\platform-tools;D:\Program Files\Sublime Text 3;D:\Program Files\Git\cmd;D:\Program Files\CMake\bin;D:\opencv\opencv\build\install\x64\vc17\bin;F:\mysql-8.0.29-winx64\bin;F:\mysql-8.0.29-winx64;D:\Program Files\msys64;D:\Program Files\msys64\usr\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;%PyCharm%;%PyCharm Community Edition%;%CLion%;D:\Program Files (x86)\Tencent\QQGameTempest\Hall.57795
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=D:/ProgramData/Miniconda3/python.exe
    SET PYTHON_LIB_PATH=D:/ProgramData/Miniconda3/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TF2_BEHAVIOR=1
  external\androidndk\ndk\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 -target aarch64-none-linux-android -fpic -isystemexternal/androidndk/ndk/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -no-canonical-prefixes -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -funwind-tables -fstack-protector-strong -fno-addrsig -Werror=return-type -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=implicit-function-declaration -O2 -g -DNDEBUG -fPIC -w -Iinclude -Isrc -march=armv8.2-a+fp16+dotprod -O2 --sysroot=external/androidndk/ndk/platforms/android-21/arch-arm64 -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem external/androidndk/ndk/sources/android/support/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c external/XNNPACK/src/f32-gemm/gen/1x12-minmax-aarch64-neonfma-cortex-a53.S -o bazel-out/arm64-v8a-opt/bin/external/XNNPACK/_objs/asm_microkernels/0/1x12-minmax-aarch64-neonfma-cortex-a53.pic.o
# Configuration: fa4e536499f276c5e5341ebd18f72405a5590e5d00d27f6a1f39cc52524f9fa1
# Execution platform: @local_execution_config_platform//:platform
external/XNNPACK/src/f32-gemm/gen/1x12-minmax-aarch64-neonfma-cortex-a53.S:10:10: fatal error: 'xnnpack/assembly.h' file not found
#include <xnnpack/assembly.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
ERROR: C:/users/dcl/_bazel_dcl/4iqg5dqe/external/XNNPACK/BUILD.bazel:10079:19: Compiling src/qs8-igemm/gen/4x8-minmax-rndnu-aarch64-neon-mlal-lane-ld64.S failed: (Exit 1): clang failed: error executing command
  cd /d C:/users/dcl/_bazel_dcl/4iqg5dqe/execroot/org_tensorflow
  SET ANDROID_BUILD_TOOLS_VERSION=32.0.0
    SET ANDROID_NDK_API_LEVEL=21
    SET ANDROID_NDK_HOME=D:/sdk/ndk/21.4.7075529
    SET ANDROID_SDK_API_LEVEL=31
    SET ANDROID_SDK_HOME=D:/sdk
    SET PATH=D:\Program Files\msys64\usr\bin;D:\Program Files\msys64\bin;C:\Windows;C:\Windows\System32;C:\Windows\System32\WindowsPowerShell\v1.0;D:\ProgramData\Miniconda3;D:\ProgramData\Miniconda3\Library\mingw-w64\bin;D:\ProgramData\Miniconda3\Library\usr\bin;D:\ProgramData\Miniconda3\Library\bin;D:\ProgramData\Miniconda3\Scripts;D:\ProgramData\Miniconda3\bin;D:\ProgramData\Miniconda3\condabin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\libnvvp;D:\ProgramData\Miniconda3;D:\ProgramData\Miniconda3\Library\mingw-w64\bin;D:\ProgramData\Miniconda3\Library\usr\bin;D:\ProgramData\Miniconda3\Library\bin;D:\ProgramData\Miniconda3\Scripts;C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\NVIDIA Corporation\Nsight Compute 2022.1.0;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;D:\Program Files\Java\jdk-11\bin;D:\sdk\platform-tools;D:\Program Files\Sublime Text 3;D:\Program Files\Git\cmd;D:\Program Files\CMake\bin;D:\opencv\opencv\build\install\x64\vc17\bin;F:\mysql-8.0.29-winx64\bin;F:\mysql-8.0.29-winx64;D:\Program Files\msys64;D:\Program Files\msys64\usr\bin;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;%PyCharm%;%PyCharm Community Edition%;%CLion%;D:\Program Files (x86)\Tencent\QQGameTempest\Hall.57795
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=D:/ProgramData/Miniconda3/python.exe
    SET PYTHON_LIB_PATH=D:/ProgramData/Miniconda3/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TF2_BEHAVIOR=1
  external\androidndk\ndk\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -gcc-toolchain external/androidndk/ndk/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64 -target aarch64-none-linux-android -fpic -isystemexternal/androidndk/ndk/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -no-canonical-prefixes -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -funwind-tables -fstack-protector-strong -fno-addrsig -Werror=return-type -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=implicit-function-declaration -O2 -g -DNDEBUG -fPIC -w -Iinclude -Isrc -march=armv8.2-a+fp16+dotprod -O2 --sysroot=external/androidndk/ndk/platforms/android-21/arch-arm64 -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem external/androidndk/ndk/sources/android/support/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c external/XNNPACK/src/qs8-igemm/gen/4x8-minmax-rndnu-aarch64-neon-mlal-lane-ld64.S -o bazel-out/arm64-v8a-opt/bin/external/XNNPACK/_objs/asm_microkernels/1/4x8-minmax-rndnu-aarch64-neon-mlal-lane-ld64.pic.o
# Configuration: fa4e536499f276c5e5341ebd18f72405a5590e5d00d27f6a1f39cc52524f9fa1
# Execution platform: @local_execution_config_platform//:platform
external/XNNPACK/src/qs8-igemm/gen/4x8-minmax-rndnu-aarch64-neon-mlal-lane-ld64.S:11:10: fatal error: 'xnnpack/assembly.h' file not found
#include <xnnpack/assembly.h>
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.
Target //tensorflow/lite:libtensorflowlite.so failed to build
INFO: Elapsed time: 12.082s, Critical Path: 9.22s
INFO: 45 processes: 18 internal, 27 local.
FAILED: Build did NOT complete successfully

why cant find assembly.h?

**Comment by mohantym** [comment]
Hi @Dclpwos !
Sorry for the late response.
Can you change the backward slash to forward ones and use appropriate path for msys (If you have not set any path for NDK, SDK and other files, Please do so )

`SET PATH=D:/Program Files/msys64/usr/bin;` // Removed extra words ;D:\Program here

Thank you!
