### ISSUE TITLE
How to register an op of conv grad? 

### ISSUE THREAD

**Issue by acknowledgexiongdei** [tensorflow/tensorflow#56955]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

source

### Tensorflow Version

tf 2.5

### Custom Code

Yes

### Current Behaviour?

```shell
I try to register an op of `conv grad` with the code below:

REGISTER_OP("ConvNewGrad")
  .Attr("T: {float, double}")
  .Attr("use_bias: bool=true")
  .Attr("need_pad: bool=false")
  .Attr("stride: int")
#ifdef USE_SGX
  .Attr("eid_low: int")
  .Attr("eid_high: int")
#endif
  .Input("grad: T")
  .Input("input: T")
  .Input("kernel: T")
  .Input("bias: T")
  .Output("grad_input: T")
  .Output("grad_kernel: T")
  .Output("grad_bias: T");
```

but when i run the trainning step, there is an error:
```
tensorflow.python.framwork.errors_impl.InternalError:Recorded operation 'ConvNew' returned too few gradients. Expected 4 but received 3.

```
I wonder where I can see the Grad OP of Conv in TensorFlow，and What four gradients does it need?

Can you help me?
```


### Standalone code to reproduce the issue

```shell
The detailed code of grad hasn't been written yet.
conv_kernel_grad_cc:

REGISTER_OP("ConvNewGrad")
  .Attr("T: {float, double}")
  .Attr("use_bias: bool=true")
  .Attr("need_pad: bool=false")
  .Attr("stride: int")
#ifdef USE_SGX
  .Attr("eid_low: int")
  .Attr("eid_high: int")
#endif
  .Input("grad: T")
  .Input("input: T")
  .Input("kernel: T")
  .Input("bias: T")
//   .Input("out: T")
  .Output("grad_input: T")
  .Output("grad_kernel: T")
  .Output("grad_bias: T");

template <typename Device, typename T>
class ConvNewGradOp : public OpKernel {
public:
    explicit ConvNewGradOp(OpKernelConstruction* context) : OpKernel(context) {
#ifdef USE_SGX
        OP_REQUIRES_OK(context, context->GetAttr("eid_low", &eid_low_));
        OP_REQUIRES_OK(context, context->GetAttr("eid_high", &eid_high_));
        lib = dlopen("layers_sgx.so", RTLD_NOW);
        OP_REQUIRES(context, lib != NULL, errors::Unknown("Unable to load layers_sgx.so!"));
#endif
        OP_REQUIRES_OK(context, context->GetAttr("use_bias", &use_bias_));
        OP_REQUIRES_OK(context, context->GetAttr("stride", &stride_));
        OP_REQUIRES_OK(context, context->GetAttr("need_pad", &need_pad_));
    }
  
    void Compute(OpKernelContext* context) override {
        DCHECK_EQ(context->num_inputs(),4);
    }
  
private:
    bool use_bias_;
    bool need_pad_;
    void *lib;
    int stride_;
#ifdef USE_SGX
    int64 eid_low_;
    int64 eid_high_;
#endif
};

```
conv.py:
```
@ops.RegisterGradient("ConvNew")
def _conv_new_grad_cc(op, grad):
    return lib.conv_new_grad(grad, op.inputs[0], op.inputs[1], op.inputs[2], use_bias=op.get_attr("use_bias"), need_pad=op.get_attr("need_pad"),eid_low=op.get_attr("eid_low"), stride=op.get_attr("stride"),eid_high=op.get_attr("eid_high"))
```
```


### Relevant log output

```shell
tensorflow.python.framwork.errors_impl.InternalError:Recorded operation 'ConvNew' returned too few gradients. Expected 4 but received 3.

```
```
</details>

**Comment by gadagashwini** [comment]
Hi @acknowledgexiongdei, 
Register the new op in a C++ file. Op registration defines an interface (specification) for the op's functionality, which is independent of the op's implementation.
Please follow the guide mentioned [here](https://www.tensorflow.org/guide/create_op). Reference for building custom ops can be found [here](https://github.com/tensorflow/custom-op). Thank you!

**Comment by acknowledgexiongdei** [comment]
> Hi @acknowledgexiongdei, 
> Register the new op in a C++ file. Op registration defines an interface (specification) for the op's functionality, which is independent of the op's implementation.
> Please follow the guide mentioned [here](https://www.tensorflow.org/guide/create_op). Reference for building custom ops can be found [here](https://github.com/tensorflow/custom-op). Thank you!

Thank you very much.
I know how to build an ops and have successfuly registered an op of conv, i wanna to know how to get deal with the grad.
Is there any example?

**Comment by gadagashwini** [comment]
Hi @acknowledgexiongdei, Please this [link](https://blog.birost.com/a?ID=cc6df4be-7062-4f67-b397-c15405746052). This blog explains about **Tensorflow custom op, gradient**. Thank you!

**Comment by acknowledgexiongdei** [comment]
> Hi @acknowledgexiongdei, Please check this [link](https://blog.birost.com/a?ID=cc6df4be-7062-4f67-b397-c15405746052). This blog explains about **Tensorflow custom op, gradient**. Thank you!

Thank you very much! I'll try to read it.
