### ISSUE TITLE
API pages could use some search optimization

### ISSUE THREAD

**Issue by shirriff** [tensorflow/tensorflow#5696]
When I search on Google for Tensorflow methods, the documentation is hard to distinguish in the search results. The API pages have irrelevant titles and aren't as highly ranked as they should be.

To reproduce:
Search for [tf extract_image_patches]
Expected behavior: I get a result with the API documentation: https://www.tensorflow.org/versions/r0.11/api_docs/python/array_ops.html
Observed behavior: this page shows up as result 3 with the mysterious title "tf.pack - TensorFlow"

Another example is EveryN. If I add enough keywords, I get the API page as result 4 (search on [tf EveryN api tf.contrib.learn]). But it has the inscrutable title "tf.contrib.learn.monitors.ExportMonitor.run_on_all_workers - TensorFlow"

This makes it difficult to find the documentation for methods.

Suggested fix: maybe make the page titles more descriptive, and add the word "API"? Maybe have separate pages for each class, like JavaDocs?

**Comment by yaroslavvb** [comment]
I concur, search could use improvement. For example, I go to main API page and search for "segment_max" -- https://www.tensorflow.org/s/results/?q=segment_max&p=%2F

This gives "segment_max" as second result, but when you go there, it has broken images/broken links because it's actually for version 0.10

**Comment by botonchou** [comment]
Another example is "dynamic_rnn" -- [https://www.tensorflow.org/s/results/?q=dynamic_rnn&p=%2F](https://www.tensorflow.org/s/results/?q=dynamic_rnn&p=%2F)

**Comment by Franck-Dernoncourt** [comment]
One more example:

![image](https://cloud.githubusercontent.com/assets/15331/23146994/ad180d1c-f7a9-11e6-9804-7011a1143c12.png)

Each option for `Initializers` links to a different API version.

**Comment by yaroslavvb** [comment]
For some things, gitbook search works better. Latest gitbook is at https://haosdent.gitbooks.io/tensorflow-document/content/api_docs/ and tracking issue for gitbook updates is https://github.com/tensorflow/tensorflow/issues/3810

**Comment by skye** [comment]
Closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest documentation. Thank you.
