### ISSUE TITLE
tf.lookup.StaticHashTable with TextFileInitializer uses a cached version of the file even after the file is changed

### ISSUE THREAD

**Issue by rjchee** [tensorflow/tensorflow#56974]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.8.2

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 18.04

### Python version

3.7.13

### Current Behaviour?

```shell
When I create a tf.lookup.StaticHashTable with tf.lookup.TextFileInitializer, then change the text file and create a new tf.lookup.StaticHashTable, it uses the contents from the original text file. If this caching behavior is expected, it's not clear to me how to clear this cache.
```

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1mJ2rTixQXxaePjkdoEfbRMfNbJjlAFSe?usp=sharing


import tensorflow as tf
import tempfile

f = tempfile.NamedTemporaryFile(delete=False)
csv_data1 = f"""0,0
1,1
2,2
"""
with open(f.name, "w") as csv_file:
  csv_file.write(csv_data1)

!cat {f.name}

table1 = tf.lookup.StaticHashTable(
    initializer=tf.lookup.TextFileInitializer(
        f.name,
        key_dtype=tf.int64, key_index=0,
        value_dtype=tf.int64, value_index=1,
        delimiter=",",
    ),
    default_value=-1,
)

csv_data2 = f"""0,1
1,2
2,3
"""
with open(f.name, "w") as csv_file:
  csv_file.write(csv_data2)

!cat {f.name}

table2 = tf.lookup.StaticHashTable(
    initializer=tf.lookup.TextFileInitializer(
        f.name,
        key_dtype=tf.int64, key_index=0,
        value_dtype=tf.int64, value_index=1,
        delimiter=",",
    ),
    default_value=-1,
)

table1.export(), table2.export()
```
```


### Relevant log output

```shell
0,0
1,1
2,2
0,1
1,2
2,3

((<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 1, 2])>,
  <tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 1, 2])>),
 (<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 1, 2])>,
  <tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 1, 2])>))
```
</details>

**Comment by mohantym** [comment]
Hi @gadagashwini !
Could you look at this issue . Attached gist in[ 2.8](https://colab.sandbox.google.com/gist/mohantym/00599af2eb5dd29317d79f08eb25345d/textfileinitializer-caching.ipynb#scrollTo=yVWpqbZfUL8n), [2.9](https://colab.sandbox.google.com/gist/mohantym/0619985c50f6e1c15fee5df49c4553fe/textfileinitializer-caching.ipynb#scrollTo=c_tB1X6o10KT) and [nightly](https://colab.sandbox.google.com/gist/mohantym/8f39a80508ace44f4110c6d17bd1735a/textfileinitializer-caching.ipynb#scrollTo=c_tB1X6o10KT) for reference.
Thank you!

**Comment by gadagashwini** [comment]
Hi @rjchee, Looks like it is working as expected. There is no cashing 

```
import tensorflow as tf
import tempfile

f = tempfile.NamedTemporaryFile(delete=False)
csv_data1 = f"""0,0
1,1
2,2
"""
with open(f.name, "w") as csv_file:
  csv_file.write(csv_data1)

!cat {f.name}

table1 = tf.lookup.StaticHashTable(
    initializer=tf.lookup.TextFileInitializer(
        f.name,
        key_dtype=tf.int64, key_index=0,
        value_dtype=tf.int64, value_index=1,
        delimiter=",",
    ),
    default_value=-1,
)
table1.export()
```
**Output**
```
0,0
1,1
2,2
(<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 2, 1])>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 2, 1])>)
```

```
f = tempfile.NamedTemporaryFile(delete=False)
csv_data2 = f"""0,1
1,2
2,3
"""
with open(f.name, "w") as csv_file:
  csv_file.write(csv_data2)

!cat {f.name}

table2 = tf.lookup.StaticHashTable(
    initializer=tf.lookup.TextFileInitializer(
        f.name,
        key_dtype=tf.int64, key_index=0,
        value_dtype=tf.int64, value_index=1,
        delimiter=",",
    ),
    default_value=-1,
)

table2.export()
```
**Output**
```
0,1
1,2
2,3
(<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 0])>,
 <tf.Tensor: shape=(3,), dtype=int64, numpy=array([2, 3, 1])>)
```

**Comment by rjchee** [comment]
Hmm, that's strange. The colab notebooks @mohantym [linked](https://github.com/tensorflow/tensorflow/issues/56974#issuecomment-1202346330) also show the issue. Does it depend on the system you're on?

**Comment by gadagashwini** [comment]
Hi @rjchee, On Colab if you are executing both the cases in same cell, we can observe cashing, since both are printing from single cell.
You should execute it in different cell to and print the tables accordingly. Thank you!

**Comment by rjchee** [comment]
@gadagashwini I observe this behavior even if I use different cells in colab. https://colab.research.google.com/drive/1mJ2rTixQXxaePjkdoEfbRMfNbJjlAFSe?usp=sharing.

Also, I don't see why the behavior should be different if they were in the same cell.

**Comment by gadagashwini** [comment]
Hi @rjchee, Even if we execute on single cell, there is no cashing, 
Code is working as expected, Please find the gist [here](https://colab.research.google.com/drive/1NdaeCzBwnan9nJu9o9HE0sK0c3UY6YcQ?usp=sharing). Thank you!

**Comment by rjchee** [comment]
It looks like in the gist, you use a different `NamedTemporaryFile` each time. These are different files with different names, so of course there is no caching. The case I am looking at is if you use the **same** filename for two different `StaticHashTables`. Could you please check that case?

**Comment by gadagashwini** [comment]
HI @rjchee, I am using same file name called `f` in both case. Initialising freshly for second case. Can you verify. Thank you!

**Comment by rjchee** [comment]
`f` is a variable name, not the file name. If you do `f = tempfile.NamedTemporaryFile`, it creates a **new** file with a different name, so writes to it won't affect the first file. I modified your [gist](https://colab.research.google.com/drive/1_wx2Rdqpzt0Spbj5WIKdIB1_WstF1yMZ?usp=sharing) so that it prints the names of the files being used. I also added a version which doesn't create a new `NamedTemporaryFile`. Please refer to the last cell which demonstrates the bug.

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
