### ISSUE TITLE
Ignore certain classes in detection.

### ISSUE THREAD

**Issue by SanjayGhanagiri** [tensorflow/tensorflow#56988]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Feature Request

### Source

binary

### Tensorflow Version

2.9

### Custom Code

No

### OS Platform and Distribution

Ubuntu 16.04

### Mobile device

Android

### Python version

3.9

### Current Behaviour?

```shell
When we run tflite model on android device we provide all classes on trained tflite weights. 

But I dont want to detect all classes in shared weights. Is there any way to detect only required classes while running detections ?
```

### Standalone code to reproduce the issue

```shell
No issues with running the model.
```

### Relevant log output

```shell
No issues with running the model.
```
</details>

**Comment by mohantym** [comment]
Hi @SanjayGhanagiri !
Could you check this [thread](https://discuss.tensorflow.org/t/how-to-exclude-coco-classes-from-model-training-process/7365/4?u=manas_mohanty) which suggests removing the extra classes from label.pbtxt (Coco image dataset) and number of classes in config file to desired number.

Thank you!
