### ISSUE TITLE
Is possible to measure height of person using tensorFlow pose Estimation 

### ISSUE THREAD

**Issue by IBSApple** [tensorflow/tensorflow#56981]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML', 'Metal']

### Custom Code

Yes

### Current Behaviour?

```shell
I want to performe Vertical Jump test & want to measure distance between floor to ankle.
```

### Standalone code to reproduce the issue

```shell
I want to performe Vertical Jump test & want to measure distance between floor to ankle.
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@IBSApple,
Could you please take a look at this [doc1](https://blog.tensorflow.org/2018/05/real-time-human-pose-estimation-in.html) and [doc2](https://www.tensorflow.org/lite/examples/pose_estimation/overview)  for the feature which you are looking for. 

`Pose estimation is the task of using an ML model to estimate the pose of a person from an image or a video by estimating the spatial locations of key body joints`
Thank you!
