### ISSUE TITLE
TensorFlow Lite convert BatchMatMulV2 into Split+multi FullyConnected + Pack

### ISSUE THREAD

**Issue by luchangli03** [tensorflow/tensorflow#56984]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):ub18.04
- TensorFlow installation (pip package or built from source):tf2.9

When I convert a transformer model with BatchMatMulV2 into tflite,  the first input shape of BatchMatMulV2 is [40x1x64],the second input shape   is [64x64], the BatchMatMulV2 is converted into Split+multi FullyConnected + Pack in the tflite model.

**Comment by mohantym** [comment]
Hi @luchangli03 !
TFliteconverter converts model operation into simple [supported operations](https://www.tensorflow.org/lite/guide/ops_compatibility) that can be run in memory constrained devices like Android and micro controllers. If you are facing any issue or want to disable quantisation for any node , you can refer [QuantizationDebugger](https://www.tensorflow.org/api_docs/python/tf/lite/experimental/QuantizationDebugger).

Thank you!
