### ISSUE TITLE
Tensorflow randomly changes the order of the input tensors depending on their names

### ISSUE THREAD

**Issue by dmitry-kabanov** [tensorflow/tensorflow#56985]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.2

### Custom Code

Yes

### OS Platform and Distribution

macOS Monterey 12.5

### Python version

3.10.5

### Current Behaviour?

```shell
I have a Keras model, which has two inputs, and convert it to TFLite format. Depending on how the inputs are named, the order of the input tensors changes. Moreover, it does not seem that the order depends on the alphabetical order of the names.

This behavior is very strange and makes it difficult to integrate with another team that uses the model converted to TFLite format.

*Expected behavior*. The order of the input tensors should be preserved in the way they are ordered in code.
```

### Standalone code to reproduce the issue

```shell
import os

import tensorflow as tf

from pprint import pprint
from tensorflow.keras import Model
from tensorflow.keras.layers import Input, Concatenate, Dense


os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'


def print_input_details_for_model(input_name_1, input_name_2):
    print()
    print("************")
    print("Input names: ", input_name_1, input_name_2)
    x = Input(shape=(7), name=input_name_1)
    y = Input(shape=(17), name=input_name_2)
    x_with_y = Concatenate()([x, y])
    z = Dense(27, name="output")(x_with_y)

    model = Model([x, y], z)

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    tflite_model = converter.convert() 
    interpreter = tf.lite.Interpreter(model_content=tflite_model)
    pprint(interpreter.get_input_details())


if __name__ == "__main__":
    tf.Variable(1.0)
    # The order of tensors is preserved.
    print_input_details_for_model("input_word_ids", "input_bboxes")
    # The order of tensors is changed.
    print_input_details_for_model("input_ids", "bboxes")
```

### Relevant log output

```shell
Metal device set to: Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB


************
Input names:  input_word_ids input_bboxes
[{'dtype': <class 'numpy.float32'>,
  'index': 0,
  'name': 'serving_default_input_word_ids:0',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
                              'scales': array([], dtype=float32),
                              'zero_points': array([], dtype=int32)},
  'shape': array([1, 7], dtype=int32),
  'shape_signature': array([-1,  7], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': <class 'numpy.float32'>,
  'index': 1,
  'name': 'serving_default_input_bboxes:0',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
                              'scales': array([], dtype=float32),
                              'zero_points': array([], dtype=int32)},
  'shape': array([ 1, 17], dtype=int32),
  'shape_signature': array([-1, 17], dtype=int32),
  'sparsity_parameters': {}}]

************
Input names:  input_ids bboxes
[{'dtype': <class 'numpy.float32'>,
  'index': 0,
  'name': 'serving_default_bboxes:0',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
                              'scales': array([], dtype=float32),
                              'zero_points': array([], dtype=int32)},
  'shape': array([ 1, 17], dtype=int32),
  'shape_signature': array([-1, 17], dtype=int32),
  'sparsity_parameters': {}},
 {'dtype': <class 'numpy.float32'>,
  'index': 1,
  'name': 'serving_default_input_ids:0',
  'quantization': (0.0, 0),
  'quantization_parameters': {'quantized_dimension': 0,
                              'scales': array([], dtype=float32),
                              'zero_points': array([], dtype=int32)},
  'shape': array([1, 7], dtype=int32),
  'shape_signature': array([-1,  7], dtype=int32),
  'sparsity_parameters': {}}]
```
</details>

**Comment by mohantym** [comment]
Hi @dmitry-kabanov !
Sorry for the late response.
Could you check with this [comment ](https://github.com/tensorflow/tensorflow/issues/51858#issuecomment-913953465)on specifying [signatures ](https://www.tensorflow.org/lite/guide/signatures ) in model itself instead of relying on tensor indices.

Thank you!

**Comment by dmitry-kabanov** [comment]
Hi @mohantym!

I am sorry for a late reply as well.
I have read the documentation mentioned in the [comment](https://github.com/tensorflow/tensorflow/issues/51858#issuecomment-913953465) but I completely did not understand how to apply it to my situation.

First of all, I would say that the doc page https://www.tensorflow.org/lite/guide/signatures has some use cases, which I do not understand how to translate to my current issue with two inputs to a model.

Second, the documentation on signatures does not say anything about how to save input shapes using signatures and how to retrieve this information from the signatures. With `interpreter.get_input_details()`, it is at least clear how to get this information.

And the bug reported in this issue is about change of order of input tensors that somehow depends on their names, which I find confusing as the names are for humans.

**Comment by mohantym** [comment]
Hi @sachinprasadhs !
Could you please look at this issue.

**Comment by misterBart** [comment]
Several threads exist about this issue. My two work-arounds:
(1) Use tf.compat.v1.lite.TFLiteConverter
(2) Sort output indices
For details see at https://github.com/tensorflow/tensorflow/issues/57043

**Comment by krunalvaghani** [comment]
> Several threads exist about this issue. My two work-arounds: (1) Use tf.compat.v1.lite.TFLiteConverter (2) Sort output indices For details see at #57043

But use of tf.compat.v1.lite.TFLiteConverter, will not support all the ops that is in latest tensorflow version.

**Comment by misterBart** [comment]
> > Several threads exist about this issue. My two work-arounds: (1) Use tf.compat.v1.lite.TFLiteConverter (2) Sort output indices For details see at #57043
> 
> But use of tf.compat.v1.lite.TFLiteConverter, will not support all the ops that is in latest tensorflow version.

That's why I called it a work-around, and not an all-encompassing solution. :)

**Comment by sachinprasadhs** [comment]
Hi, We are investigating on this issue.
Could you please close this issue and track the progress https://github.com/tensorflow/tensorflow/issues/57043#issuecomment-1318333182 in the similar issue.
Along with the linked comment workaround, the suggested way to use is make use of signatures in your model https://www.tensorflow.org/lite/guide/signatures

**Comment by sachinprasadhs** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
