### ISSUE TITLE
 AssertionError: Duplicate registrations for type 'optimizer'  in Keras Optimizer - Tensorflow 2.9.1

### ISSUE THREAD

**Issue by akramIOT** [tensorflow/tensorflow#56980]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

TF  2.9.1

### Custom Code

Yes

### OS Platform and Distribution

MACOS

### Python version

3.9

### Current Behaviour?

```shell
Exception Error in Keras Regualrization and Optimizer 

1) Un-installed and  re-installed Tensorflow, keras from scratch but not luck
2) Created a New ENV  and  started from scracth and used latest  TF  2.9.1 but no luck as
same issue is seen

(IOT_DL) akram@ISHERIFF-M-RBNA Data % 
(IOT_DL) akram@ISHERIFF-M-RBNA Data % python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
v2.9.0-18-gd8ce9f9c301 2.9.1
(IOT_DL) akram@ISHERIFF-M-RBNA Data %
```

### Standalone code to reproduce the issue

```shell
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

from keras.models import Sequential
from keras.layers.recurrent import LSTM
from keras.callbacks import TensorBoard
from keras.callbacks import ModelCheckpoint

from tensorflow.python.keras.layers.core import Reshape,Dense,Dropout,Activation,Flatten

epochs = 100
batch_size = 50

# Each training data point will be length 100-1,
# since the last value in each sequence is the label
sequence_length = 100

# OMP error issue fixing (some machine may show error)
import os

os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'


# Input data generation

def prepare_data(data, train_start, train_end, test_start, test_end):
    print("Length of Data", len(data))

    # training data
    print("Preparaing training data...")

    result = []
    for index in range(train_start, train_end - sequence_length):
        result.append(data[index: index + sequence_length])
    result = np.array(result)
    result, result_mean = normalize(result)

    print("Training data shape  : ", result.shape)

    train = result[train_start:train_end, :]
    np.random.shuffle(train)
    X_train = train[:, :-1]
    y_train = train[:, -1]

    # test data
    print("Creating test data...")

    result = []
    for index in range(test_start, test_end - sequence_length):
        result.append(data[index: index + sequence_length])
    result = np.array(result)
    result, result_mean = normalize(result)

    print("Test data shape  : {}".format(result.shape))

    X_test = result[:, :-1]
    y_test = result[:, -1]

    print("Shape X_train", np.shape(X_train))
    print("Shape X_test", np.shape(X_test))

    X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
    X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))

    return X_train, y_train, X_test, y_test


# Model genration function

def generate_model():
    model = Sequential()

    # First LSTM layer defining the input sequence length
    model.add(LSTM(input_shape=(sequence_length - 1, 1),
                   units=32,
                   return_sequences=True))
    model.add(Dropout(0.2))

    # Second LSTM layer with 128 units
    model.add(LSTM(units=128,
                   return_sequences=True))
    model.add(Dropout(0.2))

    # Third LSTM layer with 100 units
    model.add(LSTM(units=100,
                   return_sequences=False))
    model.add(Dropout(0.2))

    # Densely-connected output layer with the linear activation function
    model.add(Dense(units=1))
    model.add(Activation('linear'))

    model.compile(loss='mean_squared_error', optimizer='rmsprop')

    return model


# Function for result normalisation
def normalize(result):
    result_mean = result.mean()
    result_std = result.std()
    result -= result_mean
    result /= result_std
    return result, result_mean


## Function for running the model

def run_model(model=None, data=None):
    # global_start_time = time.time()

    print('Loading data... ')
    data_b = pd.read_csv('/Users/akram/AKRAM_CODE_FOLDER/IOT_DL/HAR/Data/cpu-utilisation.csv',
                         parse_dates=[0], infer_datetime_format=True)
    data = data_b['cpu utilisation (%)'].as_matrix()

    # train on first 700 samples and test on next 300 samples (test set has anomaly)
    X_train, y_train, X_test, y_test = prepare_data(data, 0, 600, 400, 700)

    # tensor board setting
    tensorboard = TensorBoard(log_dir='./logs',
                              histogram_freq=0,
                              write_graph=True,
                              write_images=True)

    if model is None:
        model = generate_model()

    try:
        print("Training...")
        checkpointer = ModelCheckpoint(filepath="lstm-results/checkpoint-02.hdf5",
                                       verbose=1, save_best_only=True, monitor='loss')
        model.fit(
            X_train, y_train,
            batch_size=batch_size, epochs=epochs, callbacks=[checkpointer, tensorboard], validation_split=0.05)
        print("Predicting...")

        predicted = model.predict(X_test)
        # model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=1, callbacks=[checkpointer, tensorboard])

        print("Reshaping predicted")
        predicted = np.reshape(predicted, (predicted.size,))
    except KeyboardInterrupt:
        print("Prediction exception")
        # print('Training duration:{}'.format(time.time() - global_start_time))
        return model, y_test, 0

    try:
        plt.figure(figsize=(20, 8))
        plt.plot(y_test[:len(y_test)], 'b', label='Observed')
        plt.plot(predicted[:len(y_test)], 'g', label='Predicted')
        plt.plot(((y_test - predicted) ** 2), 'r', label='Root-mean-square deviation')
        plt.legend()
        plt.show()
    except Exception as e:
        print("plotting exception")
        print(str(e))
    # print('Training duration:{}'.format(time.time() - global_start_time))

    return model, y_test, predicted


# Call the run function
model, y_test, predicted = run_model()
```

### Relevant log output

```shell
traceback (most recent call last):
  File "/Users/akram/AKRAM_CODE_FOLDER/IOT_DL/HAR/Models/LSTM_Security_Threat.py", line 6, in <module>
    from keras.models import Sequential
  File "/Users/akram/opt/anaconda3/envs/IOT_DL/lib/python3.9/site-packages/keras/__init__.py", line 25, in <module>
    from keras import models
  File "/Users/akram/opt/anaconda3/envs/IOT_DL/lib/python3.9/site-packages/keras/models/__init__.py", line 18, in <module>
    from keras.engine.functional import Functional
  File "/Users/akram/opt/anaconda3/envs/IOT_DL/lib/python3.9/site-packages/keras/engine/functional.py", line 25, in <module>
    from keras.engine import base_layer
  File "/Users/akram/opt/anaconda3/envs/IOT_DL/lib/python3.9/site-packages/keras/engine/base_layer.py", line 40, in <module>
    from keras.mixed_precision import loss_scale_optimizer
  File "/Users/akram/opt/anaconda3/envs/IOT_DL/lib/python3.9/site-packages/keras/mixed_precision/loss_scale_optimizer.py", line 20, in <module>
    from keras.optimizer_v2 import optimizer_v2
  File "/Users/akram/opt/anaconda3/envs/IOT_DL/lib/python3.9/site-packages/keras/optimizer_v2/optimizer_v2.py", line 1461, in <module>
    tf.__internal__.saved_model.load.register_revived_type(
  File "/Users/akram/opt/anaconda3/envs/IOT_DL/lib/python3.9/site-packages/tensorflow/python/saved_model/revived_types.py", line 133, in register_revived_type
    raise AssertionError(f"Duplicate registrations for type '{identifier}'")
AssertionError: Duplicate registrations for type 'optimizer'
```
</details>

**Comment by akramIOT** [comment]
(IOT_DL) akram@ISHERIFF-M-RBNA Data % 
(IOT_DL) akram@ISHERIFF-M-RBNA Data % pip list | grep keras     
keras                        2.9.0
(IOT_DL) akram@ISHERIFF-M-RBNA Data % 
(IOT_DL) akram@ISHERIFF-M-RBNA Data % 
(IOT_DL) akram@ISHERIFF-M-RBNA Data % pip list | grep keras
keras                        2.9.0
(IOT_DL) akram@ISHERIFF-M-RBNA Data % 
(IOT_DL) akram@ISHERIFF-M-RBNA Data % pip list | grep tensor
tensorboard                  2.9.1
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.9.1
tensorflow-addons            0.17.1
tensorflow-estimator         2.9.0
tensorflow-io-gcs-filesystem 0.26.0
(IOT_DL) akram@ISHERIFF-M-RBNA Data %

**Comment by mohantym** [comment]
Hi @akramIOT !
Could you do following checks and let us know.

1. Uninstall all existing installation of Tensorflow and keras . Only go with Tensorflow 2.9 or nightly  in new environment( Don't install keras again in same environment)

2. If issue still persists , Please check for duplicate optimisation folders in tensoflow.python.keras . If found delete the duplicate ones.

Attached relevant threads for reference.[ 1,](https://www.reddit.com/r/tensorflow/comments/srv3fe/comment/hwu7m8u/?utm_source=share&utm_medium=web2x&context=3) ,[2](https://stackoverflow.com/a/71174155).

Please post on Keras repo for further assistance.

Thank you!

**Comment by akramIOT** [comment]
@mohantym : I did   do  the following  

1)   " pip3 uninstall tensorflow absl-py astunparse flatbuffers gast google-pasta grpcio h5py keras keras-preprocessing libclang numpy opt-einsum protobuf setuptools six tensorboard tensorflow-io-gcs-filesystem termcolor tf-estimator-nightly typing-extensions wrapt "   

2) pip3 install --no-cache-dir tensorflow

and  gave a  run and i am seeing  this issue.  ?

/Users/akram/opt/anaconda3/envs/IOT_DL/bin/python /Users/akram/AKRAM_CODE_FOLDER/IOT_DL/HAR/Models/LSTM_Security_Threat.py
Loading data... 
Traceback (most recent call last):
  File "/Users/akram/AKRAM_CODE_FOLDER/IOT_DL/HAR/Models/LSTM_Security_Threat.py", line 168, in <module>
    model, y_test, predicted = run_model()
  File "/Users/akram/AKRAM_CODE_FOLDER/IOT_DL/HAR/Models/LSTM_Security_Threat.py", line 116, in run_model
    data_b = pd.read_csv('/Users/akram/AKRAM_CODE_FOLDER/IOT_DL/HAR/Data/cpu-utilisation.csv',
  File "/Users/akram/opt/anaconda3/envs/IOT_DL/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/akram/opt/anaconda3/envs/IOT_DL/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/Users/akram/opt/anaconda3/envs/IOT_DL/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/akram/opt/anaconda3/envs/IOT_DL/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/Users/akram/opt/anaconda3/envs/IOT_DL/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1236, in _make_engine
    return mapping[engine](f, **self.options)
  File "/Users/akram/opt/anaconda3/envs/IOT_DL/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 75, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 544, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 633, in pandas._libs.parsers.TextReader._get_header
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1952, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 11: invalid start byte

Process finished with exit code 1

**Comment by mohantym** [comment]
Ok @akramIOT !
Thanks for the update. You can see the stack trace is different now.

1. Could you  create a fresh environment and install Tensorflow 2.9/nightly only.
( No keras, install Keras and Tensorflow together  in same environment creates conflict too)

2. Check for duplicate optimizer files if issue still persists.

**Comment by akramIOT** [comment]
Yes, thanks. I resolved the Pandas  Stac  trace  error  and  we need to   use    " infer_datetime_format=True "' while reading the  .CSV  file.

**Comment by mohantym** [comment]
@akramIOT !
Could we move this to resolved status then.
Thank you!

**Comment by akramIOT** [comment]
> @akramIOT ! Could we move this to resolved status then. Thank you!

Yes, thanks a lot

**Comment by mohantym** [comment]
@akramIOT !
Thanks for confirmation. Moving this closed status as it seems to be resolved from above [comment](https://github.com/tensorflow/tensorflow/issues/56980#issuecomment-1206022091).
Thank you!
