### ISSUE TITLE
tflite.interpreter problem its not opening the model in raspberry pi 4

### ISSUE THREAD

**Issue by Nikoed** [tensorflow/tensorflow#56999]
Hi guys,

I am trying to implement pose estimation with TFlite in raspberry pi so its working in my desktop but when I tried to run it in my raspberry pi its not working.

this is my original libraries:
matplotlib==3.5.2
numpy==1.19.5
opencv_python==4.6.0.66
setuptools==57.0.0
tensorflow==2.4.1

when I tried to install my dependencies and libraries using requirements, its not accepting the tensorflow 2.4.1 so I downloaded 2.8 instead .

my raspberry pi:
bullseye 11
python 3.9
64bits

this is my error:
File "/home/pi/pose1/main.py", line 7, in <module>
    interpreter = tf.lite.Interpreter(model_path="thunder.tflite ")
  File "/home/pi/pose1/pose11-env/lib/python3.9/site-packages/tensorflow/lite/python/interpreter.py", line 456, in __init__
    _interpreter_wrapper.CreateWrapperFromFile(
ValueError: Could not open 'thunder.tflite '.

this is the code for my interpreter:

interpreter = tf.lite.Interpreter(model_path="thunder.tflite ")
interpreter.allocate_tensors()

the model is also in my directory , again its working in my desktop but not in my raspberry pi.  please help thank you so much!!!!

**Comment by mohantym** [comment]
Hi @Nikoed !

Can you put the full path of Tflite model and let us know the results.
If it still persists , Please change the name of TFlite file too.
[Ref](https://fixexception.com/#AwXuShEx7VD36QLx7HQX4x)

Thank you!
