### ISSUE TITLE
AttributeError: '_UserObject' object has no attribute 'add_slot'

### ISSUE THREAD

**Issue by innat** [tensorflow/tensorflow#56997]
Issue Type: Bug
Source: binary
Tensorflow Version: 2.6
Custom Code: Yes

# Current Behaviour?

I have model, saved using `SavedModel` format. The model is trained on Kaggle TPU and saved in the following ways:

```python
# in kaggle tpu, it must be saved in the following way!
save_locally = tf.saved_model.SaveOptions(experimental_io_device='/job:localhost')
final_model.save('./final_model', options=save_locally)
 ```

Now, it seems like, if I try to load this model in the following way, 

```python
model = tf.saved_model.load("final_model")

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_17/3033429325.py in <module>
----> 1 model = tf.saved_model.load("final_model")
...
...
AttributeError: '_UserObject' object has no attribute 'add_slot'
```

But if I do as follows, it works.

```
model = tf.keras.models.load_model("final_model")
```

But for some reason, I need to make `tf.saved_model.load` API work instead `tf.keras.models.load_model` API. What approach should we take here?

**Comment by sushreebarsa** [comment]
@innat 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!

**Comment by innat** [comment]
@sushreebarsa Thanks for checking. [HERE](https://gist.github.com/innat/a964af86590474d848c13f10d863c300) is the reproducible code. I've tested the code on Kaggle platform with TensorFlow 2.4.1. Please do the same to reproduce the issue. (FYI, `kaggle-tpu: tf 2.4`, `kaggle-gpu: 2.6`)

Note, you might get error like this, [Unsolved-Closed](https://github.com/tensorflow/models/issues/8990#issuecomment-735496167) issue.

```
AttributeError: '_UserObject' object has no attribute 'summary'
```

instead of, both inherits from the same API.

```
AttributeError: '_UserObject' object has no attribute 'add_slot'
```

**Comment by innat** [comment]
@kfrancischen 
Please [check](https://www.kaggle.com/competitions/google-universal-image-embedding/discussion/336534#1882377).

**Comment by kfrancischen** [comment]
Hey @innat, I don't think this is considered a bug in Tensorflow and using `tf.keras.models.load_model` can solve the problem. Do you mind closing this issue?

**Comment by innat** [comment]
@kfrancischen yes, you're right. It's not actually bug. Closing it. But would you please take a look into kaggle issue, I mentioned earlier.  Thanks.

**Comment by MariumAZ** [comment]
@kfrancischen in my case the `tf.keras.models.load_model` doesn't solve the pb, for saving the model and loading it with tf 2.9 everything works fine but when I switch to tf 2.6 it is not the case .. for more info I am using the subclassing API to build the model.

**Comment by innat** [comment]
@MariumAZ Is it possible to share reproducible code?

**Comment by mvidyasagar-sc** [comment]
Why is this ticket closed there is no solution i can find :(

**Comment by innat** [comment]
@mvidyasagar-sc If you can provide some reproducible code, we can reopen this ticket.

cc. @kfrancischen

**Comment by uberyb** [comment]
> @mvidyasagar-sc If you can provide some reproducible code, we can reopen this ticket.
> 
> cc. @kfrancischen

Here's a good reproducible example project [https://github.com/cjbayron/autochord](https://github.com/cjbayron/autochord). The author uses the legacy .pb extension for his model, however in Keras 3 this isn't supported and it recommends you to use TFSMLayer(model_dir) instead. If you change line 74 on __init__.py from load_model to keras.layers.TFSMLayer(_CHORD_MODEL_DIR), you get exactly the error that the author is discussing here.

**Comment by daviareias** [comment]
I got a new macbook and when I try to load an old model in the new machine i get this exact error:

**Comment by minevvgoogle** [comment]
Installing `tf-keras` solves the issue in our case. But it doesn't look like a good solution, just a workaround that can help with finding a root cause

**Comment by hassan883** [comment]
@cameronbronstein did you get the any solution because I am getting the same issue, and I don't how to fix this
thanks

**Comment by cameronbronstein** [comment]
@hassan883 I ended up using TF 2.16.1, with tf-keras installed in the environment. Also, I'm using keras 2 in the backend, which requires setting this environment variable before importing tensorflow: 

```os.environ["TF_USE_LEGACY_KERAS"] = "1"```

What also worked for me was loading the model this way:

```
from tensorflow import keras

model = keras.models.load_model(path_to_saved_model, compile=False)
```

Another weird thing I ran into that affected model deserialization. Without this, all of my custom model layers were being interpreted as either TFOpLambdas or SlicingOpLambda, and didn't retain the keras properties/methods I was used to, which broke my code. In the end, this is what fixed that second issue: 

```
from tensorflow.keras import layers
from tensorflow import keras
```

Before, I was importing in this order/fashion. Don't do this!
```
from tensorflow import keras
from keras import layers
```

**Comment by hassan883** [comment]
@cameronbronstein Thank you so much, i just fixed my issue, 
to get rid of this install the tensorflow using this command: 
`# First, remove all existing installations
pip uninstall -y tensorflow tensorflow-cpu keras tf-keras

# Clear pip cache
pip cache purge

# Install specific versions in order
pip install tensorflow==2.16.1
pip install 'keras<3.0.0' --no-deps`

and import the libraries like that; 

`import os

# Set these environment variables before importing tensorflow
os.environ["TF_USE_LEGACY_KERAS"] = "1"
# This helps avoid the load_context error
os.environ["KERAS_BACKEND"] = "tensorflow"
# Add this to bypass the load context issue
os.environ["TF_KERAS"] = "1"

# Import tensorflow first
import tensorflow.compat.v2 as tf


# Patch the internal function before any other imports
def patch_tf_internal():
    if not hasattr(tf.__internal__, "register_load_context_function"):

        def register_load_context_function(func):
            return tf.__internal__.register_call_context_function(func)

        tf.__internal__.register_load_context_function = register_load_context_function


patch_tf_internal()

# Force tensorflow to use its internal keras
from tensorflow.python import keras
from tensorflow.python.keras import layers

import numpy as np
import json
import matplotlib.pyplot as plt`

BTW thanks @cameronbronstein

**Comment by Kayyuri** [comment]
Hi @innat, 
Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

Could you please try using the `tf-keras` package and set `os.environ["TF_USE_LEGACY_KERAS"] = "1"` to enable legacy Keras compatibility and resolve the issue?

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.
Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

Thanks!
