### ISSUE TITLE
How to reduce the size of dependent files?

### ISSUE THREAD

**Issue by panhu** [tensorflow/tensorflow#56996]
Hi, 
    I want to deploy my model on the edge device, but the device space is limited. And the compiled "tensorflowlite.so" depends on three large files (larger than 8M). Is there any way to reduce the size of dependent files?

Thanks!

**Comment by mohantym** [comment]
Hi @panhu! 
You can use [Cmake ](https://www.tensorflow.org/lite/guide/build_cmake)to build the lite files. You can also use [selective build](https://www.tensorflow.org/lite/guide/reduce_binary_size) option with two different lite model t(either using Bazel rules or sh command) o reduce your file size.

Attached relevant [thread ](https://www.digikey.com/en/maker/projects/tinyml-getting-started-with-tensorflow-lite-for-microcontrollers/c0cdd850f5004b098d263400aa294023)for reference.

Thank you!
