### ISSUE TITLE
Runtime Error: Node number 93 (CONCATENATION) failed to prepare

### ISSUE THREAD

**Issue by Alexanderbayer** [tensorflow/tensorflow#57006]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18 LTS
- TensorFlow installation (pip package or built from source): TF 2.9 installed using pip
- TensorFlow library (version, if pip package or github SHA, if built from source): TF 2.9 installed using pip

### 2. Code

```
# -*- coding: utf-8 -*-
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import Sequence
import os
import random
from glob import glob
from PIL import Image
import numpy as np
import pathlib
import cv2
import onnx
from onnx_tf.backend import prepare
base_dir = "/media/sf_C_DRIVE/Users/ML/Desktop/blindbot_main"
modelpath = "/media/sf_C_DRIVE/Users/ML/Desktop/combined_model.onnx"
modelpath_keras = "/media/sf_C_DRIVE/Users/ML/Desktop/combined_model.hdf5"

class Data_Generator(Sequence):

    def __init__(self, image_filenames, batch_size):
        self.image_filenames = image_filenames
        self.batch_size = batch_size

    def __len__(self):
        return int(np.ceil(len(self.image_filenames) / float(self.batch_size)))

    def __getitem__(self, idx):
      batch_x = self.image_filenames[idx * self.batch_size:(idx + 1) * self.batch_size]
      image = (np.array([ np.array(Image.open(file_name).resize(size=(320, 1024)), np.float32) for file_name in batch_x])/255)
      image = np.transpose(image, (0, 3, 2, 1))
      return image

validation_filenames = glob(base_dir + "/**/*.jpg",recursive=True)
random.shuffle(validation_filenames)
val_generator = Data_Generator(image_filenames=validation_filenames, batch_size=1)



def representative_data_gen():
  for i in range(1000):
    imgs = val_generator.__getitem__(i)
    yield [imgs[0:1]]

converter = tf.lite.TFLiteConverter.from_saved_model("/media/sf_C_DRIVE/Users/ML/Desktop/blindbot_main/tfmodel.pb")
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8       # try to implement the model in tensorflow / try with int8 / try release candidate version for tensorflow / try model without concatenation layers / open issue on github of tensorflow / try monodepth tensorflow version
converter.inference_output_type = tf.int8
converter.representative_dataset = representative_data_gen
converter.inference_type = tf.int8

tflite_models_dir = pathlib.Path("/media/sf_ML/Models/tflite_quantisized_models/")
tflite_models_dir.mkdir(exist_ok=True, parents=True)

tflite_model_quant = converter.convert()
tflite_model_quant_file = tflite_models_dir/"model_quant.tflite"
tflite_model_quant_file.write_bytes(tflite_model_quant)
print("done!")
```

### 3.Error: 
The conversion fails with an error: 
```
tensorflow/lite/kernels/concatenation.cc:80 t->dims->data[d] != t0->dims->data[d] (20 != 18)Node number 93 (CONCATENATION) failed to prepare.
  File "/media/sf_ML/Python_Files/converttflite_onnx.py", line 71, in <module>
    tflite_model_quant = converter.convert()
```

The model is a Resnet and upscale image to image network originally saved from PyTorch.
I have read in similar issues that there might be a problem with the way that PyTorch models have a dynamic input dimension which has to be fixed during conversion, but I am not sure on how to diagnose this any further than that.

Does anyone have an idea on how to solve the issue of the dimension mismatch?

Thank you very much for any help on this.

**Comment by mohantym** [comment]
Hi @Alexanderbayer !

It seems to be multi output  model and You can arrange the ascertain the sequence of input and output by implementing [signatures](https://www.tensorflow.org/lite/guide/signatures) in model itself.

Can you check with below code and let us know.

```
def representative_data_gen():
   for i in range(1000):
       imgs = val_generator.getitem(i)
       yield [imgs[0:1].astype(np.int8)] # will yielding a single image will be possible here?

converter = tf.lite.TFLiteConverter.from_saved_model("/media/sf_C_DRIVE/Users/ML/Desktop/blindbot_main/tfmodel.pb")
converter.optimizations = [tf.lite.Optimize.DEFAULT]
#converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.target_spec.supported_ops = [
tf.lite.OpsSet.TFLITE_BUILTINS_INT8, tf.lite.OpsSet.SELECT_TF_OPS   #  tf.lite.OpsSet.TFLITE_BUILTINS_INT8 does not work ,switch to only built ins
]
converter.inference_input_type = np.int8 # try to implement the model in tensorflow / try with int8 / try release candidate 
converter.inference_output_type = np.int8
converter.representative_dataset = representative_data_gen

converter._experimental_lower_tensor_list_ops = False
```

Ref [1](https://github.com/tensorflow/tensorflow/issues/55424#issuecomment-1082821296), [2](https://github.com/tensorflow/tensorflow/issues/46315#issuecomment-822794289)

Thank you!

**Comment by Alexanderbayer** [comment]
Hi @mohantym ,
Than you so much for your fast response!

I had the chance to try converting it with your code now, but unfortunately still the same error occurs when converting the model.

Also I have implemented signatures in the model and I printed the signatures using the following code (after conversion without quantization): 
`
interpreter = tf.lite.Interpreter(model_content=tflite_model_quant)
signatures = interpreter.get_signature_list()
print(signatures)
`

The model I am trying to convert is a ResNet18 encoder with skip connections to form a U-Net with this depth decoder: https://github.com/nianticlabs/monodepth2/blob/master/networks/depth_decoder.py
So it should only be single input and single output.
I am not sure however about whether is the ordering of the dimensions is correct, as mentioned in the reference you provided.

Here you can find the onnx model, the tensorflow model, as well as the unquantized tensorflow lite model: https://drive.google.com/file/d/19l4-gARzdYTbckeiGAiCWc1GnIj-Y72n/view?usp=sharing

Best reagards,
Alex

**Comment by Alexanderbayer** [comment]
sorry, closed it by accident

**Comment by sachinprasadhs** [comment]
Have you tried with float conversion instead of int8 conversion to see if it is failing on both the cases.

**Comment by Alexanderbayer** [comment]
> Have you tried with float conversion instead of int8 conversion to see if it is failing on both the cases.

Yes, I have tried that, and this works as there is no inference on sample images necessary for conversion without quantization.

**Comment by sachinprasadhs** [comment]
This could also be due to the wrong batch size during training and inference time, could you please check it. Thanks!

**Comment by sachinprasadhs** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
