### ISSUE TITLE
Training with GRU is taking more time when i replace the LSTM with same input and Parameters ? Is it Expected?

### ISSUE THREAD

**Issue by yugeshav** [tensorflow/tensorflow#57005]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

binary

### Tensorflow Version

2.7

### Custom Code

No

### Current Behaviour?

```shell
Training with GRU is taking more time when i replace the LSTM with same input and Parameters ? Is it Expected?
```

### Standalone code to reproduce the issue

```shell
self.inter_rnn1 = keras.layers.LSTM(64,activation='tanh',return_sequences=True, implementation = 2)

Able to complete in 20min/epoch and watch -n 0.1 nvidia-smi shows 100% usage of all GPU's



self.inter_rnn1 = keras.layers.GRU(64,activation='tanh',return_sequences=True, implementation = 2)

Able to complete in 4hours/epoch and watch -n 0.1 nvidia-smi shows hardly  15% usage of all GPU's

Can someone help on this?
```

### Relevant log output

_No response_</details>

**Comment by gadagashwini** [comment]
Hi @yugeshav, 
In both the cases, GRU and LSTM, it took almost same GPU memory.
```
inter_rnn1 = keras.layers.LSTM(64,activation='tanh',return_sequences=True, implementation = 2)
Memory usage:   264MiB / 15109MiB
```

```
inter_rnn1 = keras.layers.GRU(64,activation='tanh',return_sequences=True, implementation = 2)
Memory usage:  261MiB / 15109MiB
```

**Comment by yugeshav** [comment]
> Hi @yugeshav, In both the cases, GRU and LSTM, it took almost same GPU memory.
> 
> ```
> inter_rnn1 = keras.layers.LSTM(64,activation='tanh',return_sequences=True, implementation = 2)
> Memory usage:   264MiB / 15109MiB
> ```
> 
> ```
> inter_rnn1 = keras.layers.GRU(64,activation='tanh',return_sequences=True, implementation = 2)
> Memory usage:  261MiB / 15109MiB
> ```

@gadagashwini I also observed the same memory in my GPU for both cases

My question is about training time

LSTM - 20min/ epoch
GRU - 4 hours/epoch

I want to understand why is that  huge difference in training time ?

Regards
Yugesh

**Comment by gadagashwini** [comment]
Hi @yugeshav, I tried with toy example, i didn’t see much difference in time. 
**LSTM**
```
import tensorflow as tf
import time 

start_time = time.time()
inputs = tf.random.normal([32, 10, 8])
lstm = tf.keras.layers.LSTM(4)
output = lstm(inputs)
print(output.shape)
print("--- %s seconds ---" % (time.time() - start_time))
```
**Output**
```
(32, 4)
--- 0.0328984260559082 seconds ---
```

**GRU**
```
import tensorflow as tf
import time 

start_time = time.time()
inputs = tf.random.normal([32, 10, 8])
gru = tf.keras.layers.GRU(4)
output = gru(inputs)
print(output.shape)
print("--- %s seconds ---" % (time.time() - start_time))
```
**Output**
```
(32, 4)
--- 0.03899741172790527 seconds ---
```

Can you share the code snippet to reproduce the issue. Thank you!
