### ISSUE TITLE
Document supported CUDA/cuDNN versions

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorflow#57000]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Feature Request

### Source

binary

### Tensorflow Version

2.9

### Custom Code

No

### Current Behaviour?

```shell
See title
```

### Standalone code to reproduce the issue

```shell
See title
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@danijar 
Could you please elaborate about your feature and please specify the use cases for this feature. Thank you!

**Comment by danijar** [comment]
Happy to clarify! The installation instructions for TensorFlow say that CUDA 11.2 is required for GPU support whereas the TensorFlow pip package actually also supports newer versions (e.g. it works fine with 11.4 for me).

> The following NVIDIA® software are only required for GPU support.
> 
> - NVIDIA® GPU drivers version 450.80.02 or higher.
> - CUDA® Toolkit 11.2.
> - cuDNN SDK 8.1.0.
> - (Optional) TensorRT to improve latency and throughput for inference.

The feature request is to document the supported version range for CUDA and cuDNN. The use case is that in the past my collaborators and I have spent a lot of unnecessary time installing specific CUDA and cuDNN versions. This impacts the usability of TensorFlow.

**Comment by gadagashwini** [comment]
Hi @danijar, You can find the CUDA and cuDNN version details based on Python and OS compatibility [here](https://github.com/tensorflow/toolchains/blob/master/toolchains/remote_config/configs.bzl#L197) .

```
tensorflow_rbe_config(
        name = "ubuntu18.04-clang_manylinux2010-cuda11.4-cudnn8.2-tensorrt7.2",
        compiler = "/clang_r969a51ff363263a3b5f2df55eba6b4d392bf30c0/bin/clang",
        cuda_version = "11.4",
        cudnn_version = "8.2",
        os = "ubuntu18.04-manylinux2010-multipython",
        python_versions = ["3.7", "3.8", "3.9", "3.10"],
        tensorrt_install_path = "/usr",
        tensorrt_version = "7.2",
```

Thank you!

**Comment by danijar** [comment]
Great! Could we add this to the docs? I think this would help many users.

**Comment by gadagashwini** [comment]
Hi @danijar, For every new stable release we will be updating the doc. Currently stable version is Tf v2.9.


Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow-2.9.0 | 3.7-3.10 | GCC 9.3.1 | Bazel 5.0.0 | 8.1 | 11.2

We will update doc. Thank you!

**Comment by danijar** [comment]
Great, thanks! Just to clarify, the updated docs will include the range of supported CUDA versions, not just the `11.2` from the table in your comment?

**Comment by danijar** [comment]
What's the reason for not specifying a range?

**Comment by sachinprasadhs** [comment]
@danijar, Usually these versions are tested by Nvidia and the latest stable CUDA version against the specific Tensorflow version will be published.

**Comment by danijar** [comment]
@sachinprasadhs I see. However, it's really useful information for users to know the range of CUDA versions that will work, not just the newest one. Is it accurate to say that newer CUDA versions will also work? If so, this is important information to mention.

To provide some more background, many users already have a certain CUDA version installed and want to know whether some TensorFlow issue they are getting (usually GPU not detected) is caused by using an incompatible CUDA version or because of a different reason.

It's also important to know the range of versions that will work when installing TF alongside JAX, which has its own supported range of CUDA versions. In contrast to TF, JAX explains this well in the REDAME (as of now it says CUDA 11.1 or newer and cuDNN 8.2 or newer).

**Comment by jondo** [comment]
@gadagashwini, you [wrote](https://github.com/tensorflow/tensorflow/issues/57000#issuecomment-1208900601):

> Hi @danijar, For every new stable release we will be updating the doc. Currently stable version is Tf v2.9.
> Version 	Python version 	Compiler 	Build tools 	cuDNN 	CUDA
> tensorflow-2.9.0 	3.7-3.10 	GCC 9.3.1 	Bazel 5.0.0 	8.1 	11.2
> 
> We will update doc. Thank you!

Where do I find this table in the doc?

**Comment by jondo** [comment]
Ah, sorry, it's [here](https://www.tensorflow.org/install/source#gpu). Please update it to TF 2.11.0.

**Comment by jondo** [comment]
For the record, according to the [TF forum](https://discuss.tensorflow.org/t/cuda-updated-to-11-8/12942), TF 2.12.0 will support CUDA 11.8. (found via https://github.com/tensorflow/tensorflow/issues/51659#issuecomment-1323747056).

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
