### ISSUE TITLE
StringLookup Skips Null Character at the End

### ISSUE THREAD

**Issue by Vikram1802** [tensorflow/tensorflow#57018]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tensorflow==2.8.0

### Custom Code

Yes

### Python version

3.9

### Current Behaviour?

```shell
The null character at the end is skipped when I run tf.keras.layers.experimental.preprocessing.StringLookup(vocabulary=vocab, output_mode='count'). 
Expected = ['[UNK]', 'ab\x00', '\x00ab', 'a\x00b']
Actual Output = ['[UNK]', 'ab', '\x00ab', 'a\x00b']
```

### Standalone code to reproduce the issue

```shell
>>> import tensorflow as tf
>>> vocab = [b'ab\x00', b'\x00ab', b'a\x00b']
>>> vocab_lookup = tf.keras.layers.experimental.preprocessing.StringLookup(vocabulary=vocab, output_mode='count')
>>> print(vocab_lookup.get_vocabulary())
```

### Relevant log output

```shell
['[UNK]', 'ab', '\x00ab', 'a\x00b']
```
</details>

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to replicate the issue on colab, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/14f4bea51869bf20aa763003ea046ce0/57018.ipynb) for reference. Thank you!

**Comment by Vikram1802** [comment]
Hi, any updates on the issue ?

**Comment by sachinprasadhs** [comment]
Thanks for opening this issue. Development of keras moved to separate repository https://github.com/keras-team/keras/issues

Please post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
