### ISSUE TITLE
Problems objection detection api on MacBook M1

### ISSUE THREAD

**Issue by sepi83** [tensorflow/tensorflow#57016]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

2.9.2

### Custom Code

No

### OS Platform and Distribution

MacOs M1

### Current Behaviour?

```shell
Trying run Tensorflow Object Detection API on my Mac and I did try to test my installation with this python object_detection/builders/model_builder_test.py. The API is installed with this guide https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/install.html

!(tensorflow) sepi@Petris-MacBook-Air research % python object_detection/builders/model_builder_test.py
/Users/sepi/opt/miniconda3/envs/tensorflow/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/Users/sepi/opt/miniconda3/envs/tensorflow/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ["[Errno 2] The file to load file system plugin from does not exist.: '/Users/sepi/opt/miniconda3/envs/tensorflow/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so'"]
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/Users/sepi/opt/miniconda3/envs/tensorflow/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/Users/sepi/opt/miniconda3/envs/tensorflow/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ["dlopen(/Users/sepi/opt/miniconda3/envs/tensorflow/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so, 0x0006): tried: '/Users/sepi/opt/miniconda3/envs/tensorflow/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/sepi/opt/miniconda3/envs/tensorflow/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so' (no such file), '/Users/sepi/opt/miniconda3/envs/tensorflow/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so' (no such file)"]
  warnings.warn(f"file system plugins are not loaded: {e}")
```

### Standalone code to reproduce the issue

```shell
python object_detection/builders/model_builder_test.py
```

### Relevant log output

_No response_</details>

**Comment by gadagashwini** [comment]
Hi @sepi83, Could you share the steps that you have followed to install Tensorflow Object detection api on MAC. Thank you!

**Comment by Lennyz1988** [comment]
I am also having this problem. It's not possible to install tensorflow-io on Macbook M1. Running tensorflow-macos 2.9.2. 

Option 1:

pip install tensorflow-io
ERROR: Could not find a version that satisfies the requirement tensorflow-io (from versions: none)
ERROR: No matching distribution found for tensorflow-io

Option 2:

cp object_detection/packages/tf2/setup.py .
pip install --use-feature=2020-resolver .
ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.0rc1 Requires-Python >=3.7,<3.10; 1.7.0rc2 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 2.10.0 Requires-Python >=2.7,<3.0; 2.3.0 Requires-Python >=2.7,<3.0; 2.4.0 Requires-Python >=2.7,<3.0; 2.5.0 Requires-Python >=2.7,<3.0; 2.6.0 Requires-Python >=2.7,<3.0; 2.7.0 Requires-Python >=2.7,<3.0; 2.8.0 Requires-Python >=2.7,<3.0; 2.9.0 Requires-Python >=2.7,<3.0
ERROR: Could not find a version that satisfies the requirement tensorflow_io (from object-detection) (from versions: none)
ERROR: No matching distribution found for tensorflow_io

Option 3:
python setup.py build 
sudo python setup.py install 
error: Could not find suitable distribution for Requirement.parse('tensorflow_io')

**Comment by gadagashwini** [comment]
HI @Lennyz1988, Could you create new issue by providing all the required details. Thank you!
