### ISSUE TITLE
Reducing Ops in Hexagon Delegate Use Wrong Axis Index When Input Tensor <4D

### ISSUE THREAD

**Issue by tc-wolf** [tensorflow/tensorflow#57026]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04 LTS

### Python version

3.10

### Bazel version

5.0.0

### GCC/Compiler version

9.4.0

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### Current Behaviour?

If there is a mean-reducing op that is executed by the Hexagon Delegate, the axis indices are unchanged from the original inputs.  This causes a problem if the tensor being reduced is of rank < 4.

Because Qualcomm's nnlib needs 4D input tensors, the TF code [adds dummy dimensions of size 1](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/builders/op_builder.h#L177-L184) to the shape.  But since the reduction axis is unchanged, the nnlib implementation thinks the wrong axis is [being reduced over](https://source.codeaurora.org/quic/hexagon_nn/nnlib/tree/hexagon/ops/src/op_reducing_mean.c#n268) and so fails a sanity check on the shape of the output tensor.

I.e. on CPU the (correct) behavior is:

Input tensor shape -> [1, 48, 768]
Axis = 2
Output tensor shape -> [1, 48, 1]

but in the hexagon delegate we pad the dimensions to make it 4D so we get:

Input tensor shape -> [1, 1, 48, 768]
Axis = 2
Output tensor shape -> [1, 1, 1, 768]

I've started on a fix in https://github.com/tensorflow/tensorflow/pull/57021 but I need some help with it - this approach creates a new tensor from the original axes tensor, increments the value by the number of dummy dimensions, and then tries to add this new tensor instead of the original.

This runs (as long as the axes_tensor is a list, not a scalar), but it leaks memory, and there is an error relating to trying to add a duplicate tensor (`ERROR: Trying to add duplicate tensor without overwrite, tflite_tensor_id 1, hexagon_node_id 16, hexagon_node_output_id 0`).  I can't modify the original axes tensor directly because it has a read-only allocation type, and trying causes a segmentation fault.

### Standalone code to reproduce the issue

1. Create dummy tflite model using https://colab.research.google.com/drive/1cyjF6dx31T-NxmPgFwOdAXPQcUYD7685?usp=sharing
2. Run with `./benchmark_model_plus_flex --graph=dummy_model_int8.tflite --use_hexagon=true` on a device that can use the Hexagon delegate.

### Relevant log output

The dummy model in the final layers reduces from a tensor of shape (32, 12) to (32, 1) - but because the reduction axis is 1, the downstream code is expected to reduce over (1, 1, 32, 12) for an output of (1, 1, 32, 12).

```shell
----------------
Timestamp: Sat Aug  6 03:20:01 2022


Log
hexagon/ops/src/op_reducing_mean.c:268:Output tensor is of size 32, but expected output tensor of size 384
hexagon/src/execute.c:167:execute() failed on node id=f err=-1
hexagon/src/interface.c:1297:fail in execute_inner()

----------------
ERROR: Failed: Failed to execute graph..
ERROR: Node number 4 (TfLiteHexagonDelegate) failed to invoke.
```
</details>

**Comment by sirakiin** [comment]
Hi @tc-wolf 

I'm having 70c50e734eac50e67317614413da04ea53acd528 to fix the axes issue when input dimension is less than 4. Let me know if it works for you.

Thanks!

**Comment by tc-wolf** [comment]
@sirakiin That looks perfect!  I tested with the rminimum reprex and that works.  I'll test with a larger model and then should be good to close.

**Comment by tc-wolf** [comment]
Confirmed that this works with the non-toy-example / larger model!
