### ISSUE TITLE
Tensorboard interactive demo is down. 

### ISSUE THREAD

**Issue by mrkent** [tensorflow/tensorflow#5702]
https://www.tensorflow.org/tensorboard/index.html retuns:

> Error: Not Found
> The requested URL /tensorboard/index.html was not found on this server.

**Comment by danmane** [comment]
The demo was deliberately turned off.
The new website is supposed to display a nice message explaining that the demo is gone, but transition to the new website has been slow. I'll check if we're going to switch soon, and if not we'll put a better warning message.
