### ISSUE TITLE
`tf.bitwise.right_shift` have different behaviors in cpu and gpu

### ISSUE THREAD

**Issue by fuzzyswan** [tensorflow/tensorflow#57029]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Current Behaviour?

When `y` is negative for `tf.bitwise.right_shift`, according to the [documentation](https://www.tensorflow.org/api_docs/python/tf/bitwise/right_shift) "the result is implementation defined". Currently in the code example, when `y=-1`, the results on CPU and GPU are not the same, I wonder if this is a bug and the implementation on cpu and gpu should be the same?

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
with tf.device("gpu"):
  X = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
  Z = tf.bitwise.right_shift(X, -1)
  print(Z)
with tf.device("cpu"):
  X = tf.constant([[1, 2, 3], [4, 5, 6]], dtype=tf.int32)
  Z = tf.bitwise.right_shift(X, -1)
  print(Z)
```

### Relevant log output

```shell
tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
```
</details>

**Comment by sushreebarsa** [comment]
@fuzzyswan I tried to replicate the issue on colab, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/a990f04103f573131267fa8878f773b2/57029.ipynb) and confirm the issue.
Thank you!

**Comment by fuzzyswan** [comment]
@sushreebarsa Yes, thank you for reproducing the issue on TF 2.9 and nightly!

**Comment by sachinprasadhs** [comment]
Usually, implementation on GPU and CPU will not be same, considering the performance impact, GPU implementation will be having limited validation checks, as opposed to many checks in CPU.

**Comment by cantonios** [comment]
The CPU kernel explicitly clamps `y` to be >= 0 [here](https://github.com/tensorflow/tensorflow/blob/1f54224e10290125632e1adb757156557c44394e/tensorflow/core/kernels/cwise_ops.h#L1243).

The GPU kernel is compiler-generated and uses LLVM MLIR if available, which makes its own decision about what to do.

Different implementations can choose to do different things, which is why it is implementation-defined.  In other words, you shouldn't rely on this behavior.
