### ISSUE TITLE
ValueError: Quantizing a tf.keras Model inside another tf.keras Model is not supported.

### ISSUE THREAD

**Issue by zhenhao-huang** [tensorflow/tensorflow#57034]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.6.0

### Custom Code

No

### Current Behaviour?

```shell
Quantization aware training in Keras incompatible with tf.keras.
```

### Standalone code to reproduce the issue

```shell
import tensorflow_model_optimization as tfmot

quantize_model = tfmot.quantization.keras.quantize_model
q_aware_model = quantize_model(model)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "train.py", line 31, in <module>
    trainer.train(config)
  File "/code/src/trainers/trainer_quant.py", line 161, in train
    q_aware_model = quantize_model(model)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 138, in quantize_model
    annotated_model = quantize_annotate_model(to_quantize)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 211, in quantize_annotate_model
    to_annotate, input_tensors=None, clone_function=_add_quant_wrapper)
  File "/usr/local/lib/python3.6/dist-packages/keras/models.py", line 452, in clone_model
    model, input_tensors=input_tensors, layer_fn=clone_function)
  File "/usr/local/lib/python3.6/dist-packages/keras/models.py", line 192, in _clone_functional_model
    model, new_input_layers, layer_fn)
  File "/usr/local/lib/python3.6/dist-packages/keras/models.py", line 245, in _clone_layers_and_model_config
    model, serialize_layer_fn=_copy_layer)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/functional.py", line 1349, in get_network_config
    layer_config = serialize_layer_fn(layer)
  File "/usr/local/lib/python3.6/dist-packages/keras/models.py", line 241, in _copy_layer
    created_layers[layer.name] = layer_fn(layer)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_model_optimization/python/core/quantization/keras/quantize.py", line 205, in _add_quant_wrapper
    'Quantizing a tf.keras Model inside another tf.keras Model is not supported.'
ValueError: Quantizing a tf.keras Model inside another tf.keras Model is not supported.
```
</details>

**Comment by tilakrayal** [comment]
@zhenhao-huang,
Could you please confirm the API which you are using. If you are trying with `Sequential` API, please try to use `Functional` API.

```
IMG_SHAPE = (224, 224, 3)
base_model = tf.keras.applications.MobileNetV2(input_shape=IMG_SHAPE,
                                                  include_top=False, 
                                                  weights='imagenet')
base_model.trainable = False
x = tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu')(base_model.output)
x = tf.keras.layers.Dropout(0.5)(x)
x = tf.keras.layers.MaxPool2D(pool_size=(2, 2))(x)
x = tf.keras.layers.Flatten()(x)
x = tf.keras.layers.Dense(units=2, activation='softmax')(x)

model = tf.keras.Model(base_model.input, x)
model.summary()
```

The Model summary shows all of the layers including the base_model.

```
quantize_model = tfmot.quantization.keras.quantize_model
q_aware_model = quantize_model(model)
```

Also please take a look at this [comment](https://github.com/tensorflow/model-optimization/issues/377) from the developer with a similar error. Thank you!

**Comment by zhenhao-huang** [comment]
My code is

    import tensorflow as tf
    from tensorflow.keras.models import Model
    
    
    class Mobilenet_v2():
        def __init__(self):
            self._base_model = tf.keras.applications.MobileNetV2(input_shape=(224, 224, 3), include_top=False, weights=None)
    
            _MOBILENET_V2_FPN_SKIP_LAYERS = ['block_2_add', 'block_5_add']
            self.skip_outputs = [
                self._base_model.get_layer(skip_layer_name).output
                for skip_layer_name in _MOBILENET_V2_FPN_SKIP_LAYERS
            ]
    
            self.conv_fpn_d = tf.keras.models.Sequential([
                tf.keras.layers.DepthwiseConv2D(
                    kernel_size=3, padding="same", activation=None),
                tf.keras.layers.Conv2D(
                    filters=24, kernel_size=1, activation=None),
                tf.keras.layers.BatchNormalization(),
                tf.keras.layers.ReLU(),
                tf.keras.layers.Conv2DTranspose(filters=24,
                                                kernel_size=3, padding="same", strides=(2, 2))
            ])
            self.conv_fpn_e = tf.keras.models.Sequential([
                tf.keras.layers.Conv2D(
                    filters=24, kernel_size=1, activation=None),
                tf.keras.layers.BatchNormalization(),
                tf.keras.layers.ReLU()
            ])
    
            self.conv_final = tf.keras.models.Sequential([
                tf.keras.layers.DepthwiseConv2D(
                    kernel_size=3, padding="same", activation=None),
                tf.keras.layers.Conv2D(
                    filters=24, kernel_size=1, activation=None),
                tf.keras.layers.BatchNormalization(),
                tf.keras.layers.ReLU(),
                tf.keras.layers.DepthwiseConv2D(
                    kernel_size=3, padding="same", activation=None)
            ])
    
        def build_model(self):
            fm64 = self.skip_outputs[0]
            fm32 = self.skip_outputs[1]
    
            decode_up = self.conv_fpn_d(fm32)
            encode = self.conv_fpn_e(fm64)
            fuse = encode + decode_up
    
            y = self.conv_final(fuse)
            sigmoid = tf.keras.layers.Activation("sigmoid")(y)
    
            return Model(inputs=self._base_model.input, outputs=sigmoid)
    
    
    if __name__ == '__main__':
        import tensorflow_model_optimization as tfmot
        model = Mobilenet_v2().build_model()
        print(model.summary())
        quantize_model = tfmot.quantization.keras.quantize_model
        q_aware_model = quantize_model(model)
        print(q_aware_model.summary())

Can you check it for me? @tilakrayal

**Comment by tilakrayal** [comment]
@zhenhao-huang,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by zhenhao-huang** [comment]
tfmot don't support `+` sign，but support `tf.keras.layers.Add()`.
