### ISSUE TITLE
Cannot import a package from Tensorflow

### ISSUE THREAD

**Issue by Tharunika-21** [tensorflow/tensorflow#57035]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.0.0-rc2

### Custom Code

Yes

### OS Platform and Distribution

Windows 11

### Python version

3.7

### GCC/Compiler version

PyCharm version: 2019.3 EAP - Build #PY-193.3793.15

### Current Behaviour?

```shell
Cannot import packages from Tensorflow in Pycharm. There is a confusion of whether this error had occured due to the version of IDE or the version of Tensorflow.
```

### Standalone code to reproduce the issue

```shell
CODE:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
```

### Relevant log output

```shell
ERROR:
Cannot find reference 'keras' in '__init__.py'
Unresolved reference 'Conv2D'
```
</details>

**Comment by sushreebarsa** [comment]
@Tharunika-21 I was able to import the packages in latest TF version of TF, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/8f08f75368354124a91ff7bd0eb0baeb/57035.ipynb) for reference. 
Could you please try with the latest and let me know if it helps?
Thank you!

**Comment by Tharunika-21** [comment]
Yes. It worked  with the latest version. Thank you for your support!

**Comment by sushreebarsa** [comment]
@Tharunika-21 Thank you for the update!
Closing this issue as it is resolved in the latest version. Please feel free to reopen the issue if you still have a concern.
Thank you!
