### ISSUE TITLE
multiple definition of `tflite::ops::builtin::BuiltinOpResolver::BuiltinOpResolver()'

### ISSUE THREAD

**Issue by code4lala** [tensorflow/tensorflow#57033]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tensorflow-2.9.1

### Custom Code

No

### OS Platform and Distribution

Ubuntu 22.04 LTS (GNU/Linux 5.15.0-43-generic x86_64)

### Mobile device

android arm64

### Python version

Python 3.10.4

### Bazel version

bazel 5.0.0

### GCC/Compiler version

ndk 21.4.7075529

### CUDA/cuDNN version

NA

### GPU model and memory

NA

### Current Behaviour?

I followed the official document to build tensorflow-lite with select ops from source, ducument url: https://www.tensorflow.org/lite/guide/ops_select?hl=zh-cn#c

The document tell me that:
> 从下面的方案中选择一个：
> 在用 bazel build 命令编译 TensorFlow Lite 时添加 --define=with_select_tf_ops=true 编译标记。
> 在编译依赖中添加 TensorFlow 运算符库依赖 tensorflow/lite/delegates/flex:delegate。

I tried the first, then I got a successful result but also a tensorflow lite shared library which didn't contain select ops, so I tried the second.
I wrote the following build script to cross-compile tensorflow 2.9.1

``` sh
#!/usr/bin/env bash

set -evx

tf=tensorflow-2.9.1

if [ -d "$tf" ]; then
    rm -rf $tf
fi

tar -xf tensorflow-2.9.1.tar.gz
pushd tensorflow-2.9.1
    cat > .tf_configure.bazelrc << EOF
build --action_env ANDROID_NDK_HOME="$ANDROID_NDK_HOME"
build --action_env ANDROID_NDK_API_LEVEL="33"
build --action_env ANDROID_BUILD_TOOLS_VERSION="33.0.0"
build --action_env ANDROID_SDK_API_LEVEL="33"
build --action_env ANDROID_SDK_HOME="$ANDROID_SDK_HOME"
EOF
    cat .tf_configure.bazelrc

    sed -i '1215i "//tensorflow/lite/delegates/flex:delegate",' tensorflow/lite/BUILD

    bazel \
        build \
        -c opt \
        --fat_apk_cpu=arm64-v8a \
        --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
        --config=android_arm64 \
        --config=monolithic \
        --verbose_failures \
        //tensorflow/lite:libtensorflowlite.so
popd
```

and it produces the following failing result:

```
# Configuration: 5b254af6e42f0099eacf2893d40a00ee4bd5ca890db4dfcdc666730641843978
# Execution platform: @local_execution_config_platform//:platform
bazel-out/arm64-v8a-opt/bin/tensorflow/lite/kernels/libbuiltin_ops_all_linked.pic.lo(register.pic.o): In function `~__base':
/proc/self/cwd/tensorflow/lite/kernels/register.cc:36: multiple definition of `tflite::ops::builtin::BuiltinOpResolver::BuiltinOpResolver()'
bazel-out/arm64-v8a-opt/bin/tensorflow/lite/kernels/libbuiltin_ops.pic.a(register.pic.o):/proc/self/cwd/tensorflow/lite/kernels/register.cc:36: first defined here
bazel-out/arm64-v8a-opt/bin/tensorflow/lite/kernels/libbuiltin_ops_all_linked.pic.lo(register.pic.o): In function `~__base':
/proc/self/cwd/tensorflow/lite/kernels/register.cc:36: multiple definition of `tflite::ops::builtin::BuiltinOpResolver::BuiltinOpResolver()'
bazel-out/arm64-v8a-opt/bin/tensorflow/lite/kernels/libbuiltin_ops.pic.a(register.pic.o):/proc/self/cwd/tensorflow/lite/kernels/register.cc:36: first defined here
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow/lite:libtensorflowlite.so failed to build
INFO: Elapsed time: 106.618s, Critical Path: 39.19s
INFO: 4 processes: 2 internal, 2 local.
FAILED: Build did NOT complete successfully
```

Then I took a look at tensorflow/lite/BUILD and found a workaround solution which can solve the double link error: remove the `//tensorflow/lite/kernels:builtin_ops_all_linked` dependency in the deps of `tflite_cc_shared_object`.

So the following building script works:

``` sh
#!/usr/bin/env bash

set -evx

tf=tensorflow-2.9.1

if [ -d "$tf" ]; then
    rm -rf $tf
fi

tar -xf tensorflow-2.9.1.tar.gz
pushd tensorflow-2.9.1
    cat > .tf_configure.bazelrc << EOF
build --action_env ANDROID_NDK_HOME="$ANDROID_NDK_HOME"
build --action_env ANDROID_NDK_API_LEVEL="33"
build --action_env ANDROID_BUILD_TOOLS_VERSION="33.0.0"
build --action_env ANDROID_SDK_API_LEVEL="33"
build --action_env ANDROID_SDK_HOME="$ANDROID_SDK_HOME"
EOF
    cat .tf_configure.bazelrc

    sed -i '1215d' tensorflow/lite/BUILD
    sed -i '1215i "//tensorflow/lite/delegates/flex:delegate",' tensorflow/lite/BUILD

    bazel \
        build \
        -c opt \
        --fat_apk_cpu=arm64-v8a \
        --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
        --config=android_arm64 \
        --config=monolithic \
        --verbose_failures \
        //tensorflow/lite:libtensorflowlite.so
popd
```

### Standalone code to reproduce the issue

```shell
see the above Current Behaviour section
```

### Relevant log output

```shell
see the above Current Behaviour section
```
</details>

**Comment by mohantym** [comment]
Hi @code4lala !
Cross-compiling might be tricky sometimes . It seems to be resolved from your end. Would you clarify the problem you want to address.
Thank you!

**Comment by code4lala** [comment]
I think you may rearrange the dependencies tree to avoid double link, i.e. do not depend on builtin_ops_all_linked again if corss-compiling.

**Comment by sachinprasadhs** [comment]
Could you please confirm the documents against english version and let us know if the steps are same. Thanks!

**Comment by code4lala** [comment]
@sachinprasadhs As your advice, I tried the following command according to the English version document ( https://www.tensorflow.org/lite/guide/ops_select?hl=en-us#cc ), and it worked!
``` sh
bazel\
build\
-c\
opt\
--fat_apk_cpu=arm64-v8a\
--host_crosstool_top=@bazel_tools//tools/cpp:toolchain\
--config=android_arm64\
--config=monolithic\
--verbose_failures\
tensorflow/lite/delegates/flex:tensorflowlite_flex
```
So could you please update the Simplified Chinese document? Thanks!

**Comment by sachinprasadhs** [comment]
Thanks for the confirmation, I will update create a PR for the same.

**Comment by sachinprasadhs** [comment]
Document is now updated in the website, could you please verify the update here https://www.tensorflow.org/lite/guide/ops_select?hl=zh-cn and close the issue. Thanks!

**Comment by code4lala** [comment]
Thanks!
