### ISSUE TITLE
Pip install very slow

### ISSUE THREAD

**Issue by vladimircape** [tensorflow/tensorflow#57037]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

2.6.1

### Custom Code

No

### Mobile device

Ubuntu

### Current Behaviour?

```shell
pip install --upgrade tensorflow==2.6.1
Want normal speed
Country:Belarus.
No VPN
```

### Standalone code to reproduce the issue

```shell
Speed is 80kb/s
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@vladimircape,
I was able to execute the `pip install --upgrade tensorflow==2.6.1` without any issues and time taken to run the `pip` is also very low. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/d70b0f463f056bf845cdcef26d9213e6/untitled475.ipynb).

Could you please create a virtual environment and try to execute the code again.Thank you!

**Comment by vladimircape** [comment]
@tilakrayal please close issues, it was a problem not only with tensorflow, but also another pip packages
