### ISSUE TITLE
Please update the Simplified Chinese documents, or at least set an indicator to tell readers the documents are out of date

### ISSUE THREAD

**Issue by code4lala** [tensorflow/tensorflow#57039]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

NA

### Custom Code

No

### OS Platform and Distribution

NA

### Mobile device

NA

### Python version

NA

### Bazel version

NA

### GCC/Compiler version

NA

### CUDA/cuDNN version

NA

### GPU model and memory

NA

### Current Behaviour?

https://www.tensorflow.org/lite/performance/gpu_advanced?hl=zh-cn#android_cc

> bazel build -c opt --config android_arm64 tensorflow/lite/delegates/gpu:gl_delegate                  # for static library
> bazel build -c opt --config android_arm64 tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_gl.so  # for dynamic library

https://www.tensorflow.org/lite/performance/gpu_advanced?hl=en-us#android_cc

> bazel build -c opt --config android_arm64 tensorflow/lite/delegates/gpu:delegate                           # for static library
> bazel build -c opt --config android_arm64 tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so  # for dynamic library

I read documents in all 20 languages but only the Simplified Chinese version is out of date, and it doesn't have even an indicator to tell me that it is out of date.

The old version library, gl_delegate, its header gl_delegate.h shows

``` c
ABSL_DEPRECATED("Use TfLiteGpuDelegateV2Create defined in delegate.h instead.")
TFL_CAPI_EXPORT TfLiteDelegate* TfLiteGpuDelegateCreate(
    const TfLiteGpuDelegateOptions* options);
```

### Standalone code to reproduce the issue

```shell
NA
```

### Relevant log output

```shell
NA
```
</details>

**Comment by mohantym** [comment]
@code4lala !
Thanks for pointing it out.
@sachinprasadhs !
Could you look at this doc-bug.
Thank you!

**Comment by sachinprasadhs** [comment]
I have created the pull request by making code changes, once the changes reflect in the master, feel free to add few more language specific changes here https://gitlocalize.com/tensorflow/docs-l10n

**Comment by sachinprasadhs** [comment]
@code4lala , The linked PR has been merged, could you please close the issue. Thanks!

**Comment by code4lala** [comment]
@sachinprasadhs Thanks for your help! But the content in the Simplified Chinese documents is still the old one, how long will it take effect?

**Comment by sachinprasadhs** [comment]
It will take few days to take effect, but there will be one more update with the translation with the description as well apart from the code changes submitted in the above PR.

**Comment by sachinprasadhs** [comment]
Document is now updated with the latest code and information inline with the english version. Could you please verify here https://www.tensorflow.org/lite/performance/gpu_advanced?hl=zh-cn#android_cc and close the issue. Thanks!

**Comment by code4lala** [comment]
Thanks!
