### ISSUE TITLE
Run audio recognition model on arduino-like board

### ISSUE THREAD

**Issue by Raunak-Singh-Inventor** [tensorflow/tensorflow#57030]
How can I run an audio recognition model on an arduino-like board using tflite micro. I can convert it to a model.cc, but I don't know how to run it from there on the microcontroller?

Any documentation and clear beginners instructions will be helpful.

Thanks in advance for your help.

**Comment by mohantym** [comment]
Hi @Raunak-Singh-Inventor !

You can train the model and get the respective C++ files using Edge impulse .
Attached relevant [thread](https://www.youtube.com/watch?v=fRSVQ4Fkwjc) from Digi-key for reference.

Thank you!

**Comment by Raunak-Singh-Inventor** [comment]
I want to import my custom model. You can't do that in edge impulse unless you have an corporate account. I'm just a 9th grader, I don't have that privilege. Please suggest a native method through TensorFlow Lite Micro (without using any 3rd party library).

**Comment by mohantym** [comment]
@Raunak-Singh-Inventor !
Please check comment in this [thread](https://github.com/tensorflow/tensorflow/issues/57031#issuecomment-1209116150).
Thank you!
