### ISSUE TITLE
Run object detection model on arduino-like board

### ISSUE THREAD

**Issue by Raunak-Singh-Inventor** [tensorflow/tensorflow#57031]
How can I run an object detection model on an arduino-like board using tflite micro. I can convert it to a model.cc, but I don't know how to run it from there on the microcontroller?

Can you please help with beginners instructions to use a object detection model trained and converted to tflite on a Arduino like board?

Thanks in advance for your help.

**Comment by mohantym** [comment]
Hi @Raunak-Singh-Inventor !


You can train the model  through custom image dataset and get the respective C++ files for including in the Arduino librarary using [Edge impulse ](https://www.edgeimpulse.com/).

Thank you!

**Comment by Raunak-Singh-Inventor** [comment]
I want to use my custom model that I have trained in TensorFlow. You can't do that in edge impulse unless you have an corporate account. I'm just a 9th grader, I don't have that privilege. Please suggest a native method through TensorFlow Lite Micro (without using any 3rd party library).

**Comment by mohantym** [comment]
Hi @Raunak-Singh-Inventor !

I was able to use edge-impulse with my personal account too. 
You can also refer this [document](https://www.tensorflow.org/lite/microcontrollers/get_started_low_level#run_inference) to write loading and inference code after getting .h file from lite using xxd converter in last step mentioned in this [example](https://colab.sandbox.google.com/github/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/examples/hello_world/train/train_hello_world_model.ipynb#scrollTo=j1FB4ieeg0lw).

Thank you!

**Comment by Raunak-Singh-Inventor** [comment]
But how can you import custom TensorFlow models into Edge Impulse. They don't have instructions for that.

**Comment by mohantym** [comment]
Ok @Raunak-Singh-Inventor !
Thanks for clarifying your requirements. Importing an Tensorflow model does not seem to be part of feature yet in Edge impulse ( But the features like Data acquisition, testing etc seems to be  great and beginner friendly) .

But  If you have already evaluated your TFlite model in Colab, You can convert to c array file using xxd converter and import it with other dependencies as mentioned here in this [document ](https://www.tensorflow.org/lite/microcontrollers/get_started_low_level#run_inference)which includes the following steps. 

1. convert your model to Tflite.
2. Convert it to c array using xxd converter.
3. Include Tflite library in Arduino
4. Create a new C++ program ( Please do refer this[ document](https://www.tensorflow.org/lite/microcontrollers/get_started_low_level#train_a_model) which mentions all the steps starting from including the library header files to get the output step)

Thank you!
