### ISSUE TITLE
Shifted/reordered YOLO output layers when converting with TfLite 2.8 or higher

### ISSUE THREAD

**Issue by misterBart** [tensorflow/tensorflow#57043]
System info:
Ubuntu 22.04 LTS
Python: Python 3.10.4
Tensorflow Lite: 2.8 and higher

Our YOLO network has three output layers.

The (correct) output from Keras (on the .h5), TfLite2.5.0, and my company’s custom-made inference engine is:

```
Output layer 0:  1.4805529   0.22662726 ...
Output layer 1:  0.42533997 -0.17623788 ...
Output layer 2: -1.0985005  -0.11061229 ...
```

Converting a YOLO network from .h5 to to .tflite with TfLite2.8 or higher, and then perform inference incorrectly outputs:

```
Output layer 0: -1.0985005  -0.11061229 ...  //== old output layer 2
Output layer 1:  1.4805529   0.22662726 ...  //== old output layer 0
Output layer 2:  0.42533997 -0.17623788 ...  //== old output layer 1
```

As if the output layers have shifted circularly or have reordered.

Work-around:
`converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file("<my_yolo_network>.h5")`
Still, I consider downgrading TfLite or use `tf.compat.v1.lite` not a future-proof fix.

Python code is below. I cannot share the network file, because it’s company IP.

```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '0'  #Notify Tensorflow there is no CUDA GPU
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1'  #Notify Tensorflow to not print info messages

import numpy as np

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import array_to_img

#Load trained Keras model to file
keras_file = "<my_yolo_network>.h5"
keras_model = keras.models.load_model(keras_file, compile=False)

#Set up test image
img = load_img("<my_image>.png", color_mode='grayscale')
img = img.resize((128,128))
img_array = img_to_array(img)
img_array = img_array / 255
img_array = np.expand_dims(img_array, axis=0)

#Infer using Keras
keras_out = keras_model.predict(img_array)
print("Keras output layer 0:", keras_out[0][0][0][0][0], keras_out[0][0][0][0][1])
print("Keras output layer 1:", keras_out[1][0][0][0][0], keras_out[1][0][0][0][1])
print("Keras output layer 2:", keras_out[2][0][0][0][0], keras_out[2][0][0][0][1])

#Convert Keras model to a Tensorflow Lite model
converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
#converter = tf.compat.v1.lite.TFLiteConverter.from_keras_model_file("<my_yolo_network>.h5")
tflite_model = converter.convert()

#Construct Tensorflow Lite interpreter
interpreter = tf.lite.Interpreter(model_content=tflite_model)
#interpreter = tf.lite.Interpreter(model_path="<my_yolo_network>.tflite")

#Set up input layer
input_details = interpreter.get_input_details()
interpreter.resize_tensor_input(input_details[0]['index'], (1,128,128,1))  #Input is one 128x128 grayscale image
interpreter.allocate_tensors()
interpreter.set_tensor(input_details[0]['index'], img_array)  #Copy image data to input layer

#Infer
interpreter.invoke()

#Print output
output_details = interpreter.get_output_details()
tflite_out = interpreter.get_tensor(output_details[0]['index'])  #Yolo has three output layers, so index at 0, 1, or 2
print("TfLite output layer 0:", tflite_out[0][0][0][0], tflite_out[0][0][0][1])
tflite_out = interpreter.get_tensor(output_details[1]['index'])
print("TfLite output layer 1:", tflite_out[0][0][0][0], tflite_out[0][0][0][1])
tflite_out = interpreter.get_tensor(output_details[2]['index'])
print("TfLite output layer 2:", tflite_out[0][0][0][0], tflite_out[0][0][0][1])
```

Similar issues:
https://github.com/tensorflow/tensorflow/issues/51858
https://github.com/tensorflow/tensorflow/issues/47927
https://github.com/tensorflow/tensorflow/issues/33303

**Comment by mohantym** [comment]
Hi @misterBart !
Thanks for bring it up . 

@sachinprasadhs ! 
Could you look at these issues. 

Thank you!

**Comment by misterBart** [comment]
Based on my last reply, a work-around could be:
```
#Work-around incorrect output order
indices = []
indices.append(output_details[0]['index'])  #Yolo has three output layers, so index can be 0, 1, or 2
indices.append(output_details[1]['index'])
indices.append(output_details[2]['index'])
indices.sort()  #Correct output order
print("TfLite model 0:", interpreter.get_tensor(indices[0]))
print("TfLite model 1:", interpreter.get_tensor(indices[1]))
print("TfLite model 2:", interpreter.get_tensor(indices[2]))
```
I'm not very fond of this work-around though, the code is cleaner and more efficient if the output order is correct in the .tflite.

**Comment by misterBart** [comment]
Hmm, more than a week has passed. I believe my post is easy to follow. Several related issues exist about this reordered/shifted output layers, so I would deem it has some importance. Is everybody on holidays?

**Comment by wanfade** [comment]
From many tries, I can understand the output order is related with the layer name.
So my workaround is, 
1. Set A B C to names of yolo three output layers.
2. Convert model.
3. Check real output order, then adjust the names to fit my expected order. (In my case , the final names order is C A B for output0, output1, output2)
4. Re-convert model with new names

**Comment by sachinprasadhs** [comment]
Hi @misterBart , Could you please try using `ExportArchive` https://www.tensorflow.org/api_docs/python/tf/keras/export/ExportArchive which could solve the issue of retain output name in the Keras model.

The other way to make it work is to convert the output value from `tf.Tensor` to `tf.keras.layers` type using `identity` layer, which will retain the output names in the converter model.
Below is the sample example. 

```
scores = tf.keras.layer.Identity(scores, name="scores)
boxes = tf.keras.layer.Identity(boxes, name="boxes)

model = tf.keras.Model({"input": input_tensor}, {"boxes": boxes, "scores": scores})
```
