### ISSUE TITLE
 SIGSEGV(SEGV_MAPERR) with Tensorflow Lite on Android Platform

### ISSUE THREAD

**Issue by syy555** [tensorflow/tensorflow#57049]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.91

### Custom Code

Yes

### OS Platform and Distribution

Android 

### Python version

3.9

### Bazel version

5.2.0

### Current Behaviour?

```shell
Got native crash when using Tensorflow lite on android.
Thes stacktrack has 2 root cause:
first:  crash atorg_tensorflow/external/ruy/ruy/context_get_ctx.cc:25 
second: crash at org_tensorflow/tensorflow/lite/kernels/internal/optimized/neon_tensor_utils.cc:2236
```

### Standalone code to reproduce the issue

```shell
Only a few user got this crash, can't be reproduced on local
```

### Relevant log output

```shell
1:
org_tensorflow/external/ruy/ruy/context_get_ctx.cc:25
org_tensorflow/external/ruy/ruy/ruy.h:47
org_tensorflow/external/ruy/ruy/ruy.h:101
org_tensorflow/./tensorflow/lite/kernels/cpu_backend_gemm_ruy.h:141
org_tensorflow/./tensorflow/lite/kernels/cpu_backend_gemm.h:169
org_tensorflow/./tensorflow/lite/kernels/internal/optimized/optimized_ops.h:299
org_tensorflow/tensorflow/lite/kernels/lstm_eval.cc:59
org_tensorflow/tensorflow/lite/kernels/lstm_eval.cc:206
org_tensorflow/tensorflow/lite/kernels/lstm_eval.cc:913
org_tensorflow/tensorflow/lite/kernels/lstm_eval.cc:1894
org_tensorflow/tensorflow/lite/kernels/unidirectional_sequence_lstm.cc:1332
org_tensorflow/tensorflow/lite/core/subgraph.cc:1013
org_tensorflow/tensorflow/lite/core/subgraph.cc:1280
org_tensorflow/tensorflow/lite/interpreter.cc:230
org_tensorflow/tensorflow/lite/java/src/main/native/nativeinterpreterwrapper_jni.cc:539


2:
org_tensorflow/tensorflow/lite/kernels/internal/optimized/neon_tensor_utils.cc:2236
org_tensorflow/tensorflow/lite/kernels/lstm_eval.cc:893
org_tensorflow/tensorflow/lite/kernels/lstm_eval.cc:1894
org_tensorflow/tensorflow/lite/kernels/unidirectional_sequence_lstm.cc:1332
org_tensorflow/tensorflow/lite/core/subgraph.cc:1013
org_tensorflow/tensorflow/lite/core/subgraph.cc:1280
org_tensorflow/tensorflow/lite/interpreter.cc:230
org_tensorflow/tensorflow/lite/java/src/main/native/nativeinterpreterwrapper_jni.cc:539
```
</details>

**Comment by mohantym** [comment]
Hi @syy555 !
Could you share the steps followed along a minimum standalone code .
Thank you!

**Comment by syy555** [comment]
> Hi @syy555 !
> Could you share the steps followed along a minimum standalone code .
> Thank you!

  val tfFile = TFModelLoader.vipTfLite!!
        val buffer: ByteBuffer = FileInputStream(tfFile).use { inputStream ->
            val fileChannel: FileChannel = inputStream.channel
            fileChannel.map(FileChannel.MapMode.READ_ONLY, 0, tfFile.length())
        }
        val tflLte = Interpreter(buffer)
        currentInput = inputList
        val inputArray = Array(1) { Array(inputList.size) { FloatArray(1) } }
        inputList.forEachIndexed { index, element ->
            inputArray[0][index][0] = element.toFloat()
        }
        val outputArray = Array(1) { FloatArray(1) }
        tflLte.run(inputArray, outputArray)

**Comment by mohantym** [comment]
@syy555 !
Thanks for the update. 

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by RachelLYY** [comment]
Hi, I'm using kotlin to deploy the ai model, the code below also triggered SIGSEGV crash: 
inputTensor?.let { input ->
            interpreter.run(input.tensorBuffer.buffer, outputTensor.buffer)
}
The crash log is:
org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:249)
org.tensorflow.lite.InterpreterImpl.runForMultipleInputsOutputs(InterpreterImpl.java:133)
org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:80)
org.tensorflow.lite.InterpreterImpl.run(InterpreterImpl.java:126)
org.tensorflow.lite.Interpreter.run(Interpreter.java:80)

Is this the same bug? Thanks a lot! 

> @syy555 ! Thanks for the update.
> 
> @sachinprasadhs ! Could you look at this issue.
> 
> Thank you!

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
