### ISSUE TITLE
bazel 0.4 support for tensorflow

### ISSUE THREAD

**Issue by yagnasrinath** [tensorflow/tensorflow#5705]
I am trying to build the tensorflow from source. I get errors like "bazel-out/host/bin/external/grpc/grpc_cpp_plugin: program not found or is not executable". But builds successfully. If bazel 0.4 is not supported, its a documentation bug here https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html to mention that bazel latest version should be downloaded. I could successfully build with bazel 0.3.x.

**Comment by martinwicke** [comment]
I successfully built with 0.4 yesterday -- is this still a problem at head? Or is it 0.11 only?

**Comment by yagnasrinath** [comment]
Sorry for the delayed reply. I was using a commit from head(October 10) https://github.com/tensorflow/tensorflow/commit/8e48ec6ea0492e2cb9fd19c0a2ccf41afc7b4dc6

**Comment by yagnasrinath** [comment]
Building with bazel 0.4 works on tf 0.11.
