### ISSUE TITLE
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice

### ISSUE THREAD

**Issue by wikstorm** [tensorflow/tensorflow#57055]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Windows 10 Home

### Python version

3.10.4

### CUDA/cuDNN version

11.7

### GPU model and memory

Nvidia GeForce 1060 3GB

### Current Behaviour?

Running model_main_tf2.py from object_detection halts with error output:
```shell
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
error: Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice
2022-08-09 14:54:40.390320: W tensorflow/core/framework/op_kernel.cc:1733] UNKNOWN: JIT compilation failed.
```
I've looked through the relevant issues to this but so far I've only seen solutions for linux.
Adding the path C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7 to path variables including creating a new called CUDA_DIR does nothing.

### Standalone code to reproduce the issue
Command used:

```shell
python model_main_tf2.py --model_dir=models/my_efficientdet_d4_coco17_tpu-32 --pipeline_config_path=models/my_efficientdet_d4_coco17_tpu-32/pipeline.config
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @wikstorm !

1. Could you set a path as below.
`export XLA_FLAGS=--xla_gpu_cuda_data_dir=<PATH_TO_CUDA>
`
2. If issue still persists, Please delete existing installation and switch to Cuda 11.2 and CudNN 8.1 (through command
`"conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0  "after installing  Nvidia drivers compatible from their [page](https://www.nvidia.com/download/index.aspx?lang=en-us) )
`
Attached relevant [thread]( https://github.com/tensorflow/models/issues/10739#issuecomment-1209257871) for reference .

Thank you!

**Comment by wikstorm** [comment]
I recently started training the network using my CPU instead, I will try this sometime next week when training is done.

I managed to fix the problem by adding this line to `model_main_tf2.py`:
```
os.environ["XLA_FLAGS"]="--xla_gpu_cuda_data_dir=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7"
```
So in theory it should also work by also executing
```
set XLA_FLAGS=--xla_gpu_cuda_data_dir="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7"
```
in windows CMD. It is worth noting that I'm working with a virtual environment in miniconda3, it may be that this solution doesn't work for that reason. We will see.

**Comment by mohantym** [comment]
Ok @wikstorm !
Thanks for the update. I also suggest to check step 2 in above [comment](https://github.com/tensorflow/tensorflow/issues/57055#issuecomment-1210272066) for windows machine. Please let us know whether it is resolved or not after your trial
Thank you!

**Comment by slavazhulanov** [comment]
i have the same problem on windows. how can i solve it? @wikstorm 
give step by step instructions

**Comment by mohantym** [comment]
@slavazhulanov ! 
Check this [thread](https://github.com/tensorflow/tensorflow/issues/56927#issuecomment-1236291285) once.

**Comment by slavazhulanov** [comment]
@wikstorm I don't understand what it means, because I work from cmd  "root of your python project"

**Comment by wikstorm** [comment]
> I recently started training the network using my CPU instead(OOM on GPU), I will try this sometime next week when training is done.
> 
> I managed to fix the problem by adding this line to `model_main_tf2.py`:
> 
> ```
> os.environ["XLA_FLAGS"]="--xla_gpu_cuda_data_dir=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7"
> ```
> 
> So in theory it should also work by also executing
> 
> ```
> set XLA_FLAGS=--xla_gpu_cuda_data_dir="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.7"
> ```
> 
> in windows CMD. It is worth noting that I'm working with a virtual environment in miniconda3, it may be that this solution doesn't work for that reason. We will see.

@slavazhulanov this is what solved it for me. Of course setting the correct path for where CUDA is located on your machine.

**Comment by ProfDoof** [comment]
So I just had this issue as well and I think that the error message needs to be changed to indicate that the XLA compiler (is that the right term) is not using the environment variable CUDA_DIR but is instead using the XLA variable. My own issue would have been solved much faster if I had known that.

**Comment by sobsdavlatov** [comment]
> So I just had this issue as well and I think that the error message needs to be changed to indicate that the XLA compiler (is that the right term) is not using the environment variable CUDA_DIR but is instead using the XLA variable. My own issue would have been solved much faster if I had known that.

How did you fix it?
