### ISSUE TITLE
GlobalAveragePooling2D-layer in mixed-precision mode and using CPU produces incorrect results

### ISSUE THREAD

**Issue by cgebbe** [tensorflow/tensorflow#57057]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

v2.8.0-rc1-32-g3f878cff5b6 2.8.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04.4 LTS

### Python version

3.8

### Current Behaviour?

```shell
Given a certain input, when applying a GlobalAveragePooling2D-layer in mixed-precision mode and using CPU, then the output is bogus (zeros and nans). When using GPU, all works fine.
```

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf
from tensorflow.keras import mixed_precision

# download the file from https://github.com/cgebbe/random_files/blob/main/x.npy
x = np.load("x.npy")
assert x.shape == (1, 256, 256, 32)

correct_result = np.array(
    [
        [
            0.1556,
            0.1864,
            0.4644,
            -0.2502,
            0.4453,
            0.3118,
            0.835,
            0.4453,
            0.26,
            0.452,
            -0.0783,
            -0.10693,
            0.1621,
            0.1736,
            0.9214,
            0.0373,
            0.2294,
            0.2252,
            0.5415,
            0.1819,
            0.2678,
            0.3835,
            0.0973,
            0.815,
            -0.013306,
            -0.1713,
            0.1719,
            0.577,
            0.3047,
            0.3525,
            0.315,
            1.783,
        ]
    ],
    dtype=np.float16,
)

wrong_result = np.array(
    [
        [
            0.0,
            0.0,
            0.0,
            -0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            -0.0,
            -0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            -0.0,
            -0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            np.nan,
        ]
    ],
    dtype=np.float16,
)

policy = mixed_precision.Policy("mixed_float16")
mixed_precision.set_global_policy(policy)
new_layer = tf.keras.layers.GlobalAveragePooling2D()

with tf.device("/gpu"):
    y1 = new_layer(tf.convert_to_tensor(x))
    np.testing.assert_allclose(y1, correct_result)

with tf.device("/cpu"):
    y2 = new_layer(tf.convert_to_tensor(x))
    np.testing.assert_allclose(y2, wrong_result)
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@cgebbe,
I tried to execute the provided code in an alternative approach and it was executed without any issues. Kindly find the [gist](https://colab.research.google.com/gist/tilakrayal/a40a7d5e9406cf0f17df3586ae754ae7/untitled479.ipynb) of it [here](https://colab.research.google.com/gist/tilakrayal/cbb2e3b50b8a84f84e9b33d16ca1d0a6/untitled480.ipynb). Also could you please try passing `dtype=tf.float32` and let us know if it works. Thank you!

**Comment by cgebbe** [comment]
@tilakrayal : Just to understand you correctly: Do you mean the example ran through? If yes, this is expected.

However, in the second test asserts that the output is close to the `wrong_result`, whereas it should be close to the `correct_result`. Maybe that clears things up?

**Comment by tilakrayal** [comment]
@cgebbe,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
