### ISSUE TITLE
Unable to load model

### ISSUE THREAD

**Issue by ArthurBesse** [tensorflow/tensorflow#57061]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

Windows 10

### Python version

3.9

### Current Behaviour?

```shell
The attached code works on Linux (centos), but when run on Windows 10 it fails with the attached output.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import pickle
import numpy as np

tf.random.set_seed(42)

input_x = np.random.randint(0, 50000, (10000,1))
input_y = np.random.randint(0, 50000, (10000,1))
output = input_x + input_y
input = np.concatenate((input_x, input_y), axis=1)

model = tf.keras.Sequential([
    tf.keras.layers.Dense(2, activation = tf.keras.activations.relu, input_shape=[2]),   
    tf.keras.layers.Dense(2, activation = tf.keras.activations.relu),
    tf.keras.layers.Dense(1),
])

model.compile(loss = tf.keras.losses.mae,
              optimizer=tf.optimizers.Adam(learning_rate=0.00001),
              metrics = ['mse'])
              
model.fit(input, output, epochs = 100)

fl = open('D:/tf/tf.pkl', 'wb')
pickle.dump(model, fl)
fl.close()

fl = open('D:/tf/tf.pkl', 'rb')
model = pickle.load(fl)
print(model.predict([[2.2, 5.1]]))
fl.close()
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "D:\tf\create_model.py", line 29, in <module>
    model = pickle.load(fl)
  File "C:\Users\developer\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\saving\pickle_utils.py", line 48, in deserialize_model_from_bytecode
    model = save_module.load_model(temp_dir)
  File "C:\Users\developer\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\developer\AppData\Roaming\Python\Python39\site-packages\tensorflow\python\saved_model\load.py", line 915, in load_partial
    raise FileNotFoundError(
FileNotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ram://6f4ad55a-d5dc-49ec-8a70-d9987bcb9422/variables/variables
 You may be trying to load on a different device from the computational device. Consider setting the `experimental_io_device` option in `tf.saved_model.LoadOptions` to the io_device such as '/job:localhost'.
```
</details>

**Comment by tilakrayal** [comment]
@ArthurBesse,
Could you please try setting the `experimental_io_device` option in `tf.saved_model.LoadOptions` to the io_device. 
Also Adding `./` in front of the file name like this filename = open("./model3.pkl", "rb") should help. 

 If you are able to load the file in linux, please make sure the file was not corrupted in Windows. Thank you!

**Comment by ArthurBesse** [comment]
@tilakrayal 

> Could you please try setting the experimental_io_device option in tf.saved_model.LoadOptions to the io_device.
Hm, I think I can't. `pickle.load` [does not have](https://docs.python.org/3/library/pickle.html#pickle.load) a suitable argument to pass `tf.saved_model.LoadOptions` .

> Also Adding ./ in front of the file name like this filename = open("./model3.pkl", "rb") should help.
Nothing changed.

> If you are able to load the file in linux, please make sure the file was not corrupted in Windows.
I don't understand what you mean. My code saves the model to a file and then tries to load the model from the same file. So, even if the file is corrupted, I think it will be another subject for investigation.

Thank you,
Arthur

**Comment by tilakrayal** [comment]
@ArthurBesse,
I am unable to reproduce the reported issue. I was able to save and load model. Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/491ca7985664503535700229d6362d39/57061.ipynb). Thank you!
