### ISSUE TITLE
Docker Hub ubuntu version documentation error

### ISSUE THREAD

**Issue by zplizzi** [tensorflow/tensorflow#57072]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

binary

### Tensorflow Version

n/a

### Custom Code

No

### Current Behaviour?

```shell
On docker hub (https://hub.docker.com/r/tensorflow/tensorflow), it says `Images built after May 20 2019 (TF nightly, plus TF versions 1.14 and onward) are based on Ubuntu 18.04. Earlier images are based on Ubuntu 16.04.`

However, if I pull `tensorflow/tensorflow:latest-gpu`, I get:

root@d98e1fb52f91:/# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
```.

The documentation should be fixed to accurately indicate which Ubuntu version you'll get for each image.
```

### Standalone code to reproduce the issue

```shell
n/a
```

### Relevant log output

_No response_</details>

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue. Now the information has been edited at https://hub.docker.com/r/tensorflow/tensorflow, Could you please confirm and close the issue. Thanks!

**Comment by zplizzi** [comment]
Thanks! I can confirm that it's been updated to read `Images built after Sept 2021 are based on Ubuntu 20.04. Earlier images are based on Ubuntu 18.04 or 16.04.`, which seems more in line with what I was seeing.
