### ISSUE TITLE
TensorFlow-lite: "ValueError: Invalid tensor size" when output is a zero-size tensor

### ISSUE THREAD

**Issue by petered** [tensorflow/tensorflow#57084]
**Summary - when the output has zero-size, I get "ValueError: Invalid tensor size" when trying to retrieve the output value - even when the output is supposed to have zero-size.**

### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **MacOS Monterrey 12.2.1**

- TensorFlow installation (pip package or built from source): **`2.8.1`, installed with `conda install -c apple tensorflow==2.8.1`**

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

#### Option B: Paste your code here or provide a link to a custom end-to-end colab

```
import tensorflow as tf

def test_tflite_fails_with_zero_size_output():

    func = tf.where  # Example of function that can potentially have zero-size output

    # With these test arguments, it passes
    # mask = tf.cast([
    #     [1, 0, 0, 1],
    #     [0, 0, 1, 0],
    #     [1, 0, 0, 0]
    # ], dtype=tf.bool)
    # expected_ixs = [(0, 0), (0, 3), (1, 2), (2, 0)]

    # With these (designed to produce zero-size output), it fails on the indicated line below
    mask = tf.cast([
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]
    ], dtype=tf.bool)
    expected_ixs = np.zeros((0, 2))

    # Verify that it works in ordinary tensorflow
    result = func(mask)
    assert np.array_equal(result.numpy(), expected_ixs)

    # Save tflite model
    model_path = os.path.expanduser('~/Downloads/test_model.tflite')
    concrete_func = tf.function(
        input_signature=[tf.TensorSpec(shape=mask.shape, dtype=tf.bool)],
    )(func).get_concrete_function()
    converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
    converter.target_spec.supported_ops = [tf.lite.OpsSet.SELECT_TF_OPS, tf.lite.OpsSet.TFLITE_BUILTINS]  # enable TensorFlow Lite ops.]
    serialized_model = converter.convert()
    with open(model_path, 'wb') as f:
        f.write(serialized_model)
    print(f'Saved model to {model_path}')

    # Load tflite model
    interpreter = tf.lite.Interpreter(model_path=model_path)
    interpreter.allocate_tensors()
    interpreter.set_tensor(0, mask)
    interpreter.invoke()
    result = interpreter.get_tensor(interpreter.get_output_details()[0]['index'])
    # ^^^ ABOVE LINE GIVES "ValueError: Invalid tensor size." WHEN OUTPUT SIZE IS ZERO!
    assert np.array_equal(result, expected_ixs)

```

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

The model gives the error when outputs have zero-size - even when they are expected to have zero-size.

**Comment by mohantym** [comment]
Hi @petered !
Thanks for reporting this bug.

@sachinprasadhs !
Could you look at this issue. Attached gist in [2.8](https://colab.sandbox.google.com/gist/mohantym/6986c3f342476564f621163a07d14388/git_57084.ipynb#scrollTo=ic7RKz9P6Vlk), [2.9](https://colab.sandbox.google.com/gist/mohantym/651cd01c29233329bd040be21ac611b6/git_57084.ipynb#scrollTo=j-o8PBSIejNA) and [nightly](https://colab.sandbox.google.com/gist/mohantym/c354634303060afe58045edc4f5ef838/git_57084.ipynb#scrollTo=j-o8PBSIejNA) for reference.

Thank you!

**Comment by pjpratik** [comment]
I was able to reproduce this issue in TF 2.11 and TF Nightly 2.12.0.dev20230121 as well. 

Please find the gist [here](https://colab.sandbox.google.com/gist/pjpratik/8e30594cf08f15b204269f1db093c769/57084.ipynb). Thank you.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

**Comment by petered** [comment]
Come on - this is no way to track issues.   Why close it if nothing was solved?
