### ISSUE TITLE
Installation of tflite-model-maker 0.4.1. takes forever

### ISSUE THREAD

**Issue by piyushmundhra** [tensorflow/tensorflow#57086]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tflite-model-maker==0.4.1

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.3

### Python version

3.7.13

### Current Behaviour?

```shell
tflite-model-maker==0.4.1 is taking forever to load. A similar issue I have seen is https://github.com/tensorflow/tensorflow/issues/51031.

I am trying to use `searcher`, which is not in the 0.3.2 version so I am trying to donwload 0.4.1. I see that in the solution to the similar issue for 0.3.2, a requirements.txt was provided. Could the same be done with 0.4.1? The requirements.txt file on pypi does not seem to have been updated. Some of the packages pip does not know the version of are: python-slugify, text-unidecode. I am not sure if there are more but this is what my output has shown so far.
```

### Standalone code to reproduce the issue

```shell
! pip install tflite-model-maker==0.4.1
```

### Relevant log output

```shell
INFO: pip is looking at multiple versions of text-unidecode to determine which version is compatible with other requirements. This could take a while.
Collecting text-unidecode>=1.3
  Using cached text_unidecode-1.3-py2.py3-none-any.whl (78 kB)
INFO: pip is looking at multiple versions of python-slugify to determine which version is compatible with other requirements. This could take a while.
Collecting python-slugify
  Using cached python_slugify-6.1.2-py2.py3-none-any.whl (9.4 kB)
  Using cached python_slugify-6.1.1-py2.py3-none-any.whl (9.1 kB)
  Using cached python_slugify-6.1.0-py2.py3-none-any.whl (9.2 kB)
INFO: pip is looking at multiple versions of text-unidecode to determine which version is compatible with other requirements. This could take a while.
  Using cached python_slugify-6.0.1-py2.py3-none-any.whl (9.0 kB)
  Using cached python_slugify-6.0.0-py2.py3-none-any.whl (9.0 kB)
  Using cached python_slugify-5.0.2-py2.py3-none-any.whl (6.7 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached python_slugify-5.0.1-py2.py3-none-any.whl (6.7 kB)
INFO: pip is looking at multiple versions of python-slugify to determine which version is compatible with other requirements. This could take a while.
  Using cached python_slugify-5.0.0-py2.py3-none-any.whl (6.8 kB)
  Using cached python-slugify-4.0.1.tar.gz (11 kB)
  Using cached python-slugify-4.0.0.tar.gz (8.8 kB)
  Using cached python-slugify-3.0.6.tar.gz (8.7 kB)
  Using cached python-slugify-3.0.5.tar.gz (8.7 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached python-slugify-3.0.4.tar.gz (8.1 kB)
  Using cached python-slugify-3.0.3.tar.gz (8.1 kB)
Collecting text-unidecode==1.2
  Using cached text_unidecode-1.2-py2.py3-none-any.whl (77 kB)
Collecting python-slugify
  Using cached python-slugify-3.0.2.tar.gz (7.9 kB)
  Using cached python-slugify-3.0.1.tar.gz (7.9 kB)
  Using cached python-slugify-3.0.0.tar.gz (6.7 kB)
  Using cached python-slugify-2.0.1.tar.gz (6.6 kB)
  Using cached python-slugify-2.0.0.tar.gz (6.5 kB)
  Using cached python-slugify-1.2.6.tar.gz (6.8 kB)
Collecting Unidecode>=0.04.16
  Using cached Unidecode-1.3.4-py3-none-any.whl (235 kB)
INFO: pip is looking at multiple versions of unidecode to determine which version is compatible with other requirements. This could take a while.
  Using cached Unidecode-1.3.3-py3-none-any.whl (235 kB)
  Using cached Unidecode-1.3.2-py3-none-any.whl (235 kB)
  Using cached Unidecode-1.2.0-py2.py3-none-any.whl (241 kB)
  Using cached Unidecode-1.1.2-py2.py3-none-any.whl (239 kB)
  Using cached Unidecode-1.1.1-py2.py3-none-any.whl (238 kB)
  Using cached Unidecode-1.1.0.tar.gz (212 kB)
  Using cached Unidecode-1.0.23-py2.py3-none-any.whl (237 kB)
INFO: pip is looking at multiple versions of unidecode to determine which version is compatible with other requirements. This could take a while.
  Using cached Unidecode-1.0.22-py2.py3-none-any.whl (235 kB)
  Using cached Unidecode-0.04.21-py2.py3-none-any.whl (228 kB)
  Using cached Unidecode-0.04.20-py2.py3-none-any.whl (228 kB)
  Using cached Unidecode-0.04.19.tar.gz (204 kB)
  Using cached Unidecode-0.04.18.tar.gz (206 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. If you want to abort this run, you can press Ctrl + C to do so. To improve how pip performs, tell us what happened here: https://pip.pypa.io/surveys/backtracking
  Using cached Unidecode-0.04.17.tar.gz (201 kB)
  Using cached Unidecode-0.04.16.tar.gz (200 kB)
Collecting python-slugify
  Using cached python-slugify-1.2.5.tar.gz (6.6 kB)
  Using cached python_slugify-1.2.4-py2.py3-none-any.whl (4.7 kB)
  Using cached python-slugify-1.2.3.tar.gz (8.5 kB)
  Using cached python-slugify-1.2.2.tar.gz (7.5 kB)
  Using cached python-slugify-1.2.1.tar.gz (5.3 kB)



(this is not the entire output but it keeps on going like so)
```
</details>

**Comment by piyushmundhra** [comment]
Update: installing the nightly version works fine and I am able to import searcher. I wonder why this installation was easily successful and not the stable package version?

**Comment by mohantym** [comment]
Hi @piyushmundhra !

To use a specific branch, Please follow below syntax
```
!git clone https://github.com/tensorflow/examples
!git checkout tflmm/v0.4.0
%cd examples/tensorflow_examples/lite/model_maker/pip_package
!pip install -e .
```
Thank you!

**Comment by ra9hur** [comment]
To me, neither the stable version nor nightly version was working. However, installations on colab would go through fine. 

Ended up checking python version on colab, created a virtual env with the same python version as in colab. Could install successfully.

**Comment by mohantym** [comment]
Hi @ra9hur !
Could you tell your python version and system details to replicate this issue.
Thank you!

**Comment by ra9hur** [comment]
Local system is on python 3.10. With this, model maker nightly version installation goes into recursive mode.

Created a conda virtual env with python version 3.7. Model maker was installed successfully.

**Comment by idoown** [comment]
Having the same issue
Python 3.10.6
It seems like it is downloading all the archived nightly builds:

Collecting tf-nightly
  Downloading tf_nightly-2.12.0.dev20221216-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (556.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 556.9/556.9 MB 1.5 MB/s eta 0:00:00
  Downloading tf_nightly-2.12.0.dev20221215-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (556.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 556.5/556.5 MB 3.1 MB/s eta 0:00:00
  Downloading tf_nightly-2.12.0.dev20221214-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (556.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 556.4/556.4 MB 3.3 MB/s eta 0:00:00
  Downloading tf_nightly-2.12.0.dev20221213-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (556.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 556.6/556.6 MB 3.2 MB/s eta 0:00:00
  Downloading tf_nightly-2.12.0.dev20221212-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (558.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 558.1/558.1 MB 2.5 MB/s eta 0:00:00
  Downloading tf_nightly-2.12.0.dev20221211-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (558.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 558.1/558.1 MB 2.5 MB/s eta 0:00:00
  Downloading tf_nightly-2.12.0.dev20221210-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (558.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 558.1/558.1 MB 3.3 MB/s eta 0:00:00
  Downloading tf_nightly-2.12.0.dev20221209-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (558.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 558.0/558.0 MB 2.8 MB/s eta 0:00:00
  Downloading tf_nightly-2.12.0.dev20221208-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (557.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.9/557.9 MB 3.1 MB/s eta 0:00:00
  Downloading tf_nightly-2.12.0.dev20221207-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (554.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 554.1/554.1 MB 1.7 MB/s eta 0:00:00
  Downloading tf_nightly-2.12.0.dev20221206-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (553.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 553.9/553.9 MB 2.4 MB/s eta 0:00:00
  Downloading tf_nightly-2.12.0.dev20221205-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (553.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 553.9/553.9 MB 2.4 MB/s eta 0:00:00
  Downloading tf_nightly-2.12.0.dev20221204-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (553.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 553.8/553.8 MB 3.0 MB/s eta 0:00:00

**Comment by Huxwell** [comment]
as of 27.04.2023 it's still not fixed, I am not able to install on colab - this takes 25min+
![image](https://user-images.githubusercontent.com/9086268/234978292-e62c7940-4aab-41df-8247-9fb18c262c5e.png)

**Comment by Marqzz** [comment]
Hi @Huxwell . I am facing the same issue right now.. Did you manage to solve this? Thanks.

**Comment by UsamaHameed1** [comment]
Same isssue cannnot install !pip install -q tflite-model-maker

**Comment by ubaidari** [comment]
> Same isssue cannnot install !pip install -q tflite-model-maker

hey same issue here .. Please tell me what is the solution . Becouse previous month i train and it works fine . but now it took all the disk on colab .. my project now stucks

**Comment by Huxwell** [comment]
@Marqzz unfortunately no, no progress so far, created a separate ticket:
https://github.com/tensorflow/tensorflow/issues/60431#issuecomment-1530981946
