### ISSUE TITLE
How to fix the "undefined reference" problem for the TF Lite? A suggestion.

### ISSUE THREAD

**Issue by DevelopDaily** [tensorflow/tensorflow#57094]
When [CMakeLists.txt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/CMakeLists.txt) is used to build a shared library of TF Lite, it is impossible to link with it because of the "undefined reference" problem.

Those "undefined reference" objects reside on the `tensorflow` main branch, but the following macro `populate_tf_source_vars` has never populated a single line of main Tensorflow code for the TF Lite build, yet the main code is referenced by it. No wonder we see the "undefine reference". 

I did try to use `populate_tf_source_vars` to bring those missing objects to TF Lite. Unfortunately, however, the references will quickly escalate to reference a lot of main Tensorflow stuff. That defeats the very motivation of having a "Lite" version of Tensorflow, doesn't it?

Can you please make TF Lite stop referencing those objects because they don't seem to be important? If you do think they are important, can you make a light version of them just for TF Lite?

https://github.com/tensorflow/tensorflow/blob/d35d3a1614fc8dd34dc181f521cf1d7f472249c1/tensorflow/lite/CMakeLists.txt#L136

**_The problem:_**

```
/usr/bin/ld: /usr/local/lib/libtensorflow-lite.so: undefined reference to `tensorflow::profiler::internal::g_trace_level'
/usr/bin/ld: /usr/local/lib/libtensorflow-lite.so: undefined reference to `tensorflow::profiler::TraceMeRecorder::Record(tensorflow::profiler::TraceMeRecorder::Event&&)'
/usr/bin/ld: /usr/local/lib/libtensorflow-lite.so: undefined reference to `tensorflow::profiler::GetCurrentTimeNanos()'
/usr/bin/ld: /usr/local/lib/libtensorflow-lite.so: undefined reference to `tensorflow::profiler::ScopedMemoryDebugAnnotation::ThreadMemoryDebugAnnotation()'

```

**Comment by pkgoogle** [comment]
Hi @DevelopDaily, can you provide the commands you used to get to those errors?
