### ISSUE TITLE
Take the middle segment of the model as the a model, got this error ValueError: Graph disconnected:

### ISSUE THREAD

**Issue by cl886699** [tensorflow/tensorflow#57098]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

tf2.6

### Custom Code

Yes

### OS Platform and Distribution

windows11 && centos7

### Python version

3.8

### Current Behaviour?

```shell
The code runs normally on Windows, but an error occurs on Linux
```

### Standalone code to reproduce the issue

```shell
import tensorflow.keras.applications as app
from tensorflow.keras import Model
if __name__ == '__main__':
    efficientb4 = getattr(app, 'EfficientNetB4')(include_top=False)
    model = Model(inputs=efficientb4.layers[7].input, outputs=efficientb4.layers[29].output, name="new_model")
    model.summary()
```

### Relevant log output

```shell
ValueError: Graph disconnected: cannot obtain value for tensor KerasTensor(type_spec=TensorSpec(shape=(None, None, None, 3), dtype=tf.float32, name='input_1'), name='input_1', description="created by layer 'input_1'") at layer "rescaling". The following previous layers were accessed without issue: []
```
</details>

**Comment by tilakrayal** [comment]
@cl886699,
I was able to reproduce the issue without any issues/errors. Could you please create a virtual environment with the latest stable v2.9 and test your code again. Thank you!

**Comment by cl886699** [comment]
> 

when update to tf2.7, it is working fine, thank you
