### ISSUE TITLE
cmake build is not installing library

### ISSUE THREAD

**Issue by sconde** [tensorflow/tensorflow#57105]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

master

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04.4 LTS

### Python version

3.8.5

### GCC/Compiler version

9.4

### Current Behaviour?

```shell
Using CMake and specifying a CMAKE_INSTALL_PREFIX, the source compiles library is not being installed in the specified path.
```

### Standalone code to reproduce the issue

```shell
cmake \
      -DBUILD_SHARED_LIBS=ON \
      -DCMAKE_BUILD_TYPE=$build_type\
      -DCMAKE_CXX_COMPILER:FILEPATH=$(which $CXX) \
      -DCMAKE_C_COMPILER:FILEPATH=$(which $CC) \
      -DCMAKE_INSTALL_PREFIX=${pkg_install} \
      -DABSL_PROPAGATE_CXX_STD=ON \
      -DTFLITE_ENABLE_INSTALL=OFF \
      ../tensorflow/lite
```
```


### Relevant log output

_No response_</details>

**Comment by sachinprasadhs** [comment]
Could you please refer this document here https://cmake.org/cmake/help/latest/command/find_package.html to find the package. Let us know if this helps. Thanks!

**Comment by sconde** [comment]
There are no installed files/shared objects in the CMAKE_INSTALL_PREFIX path for the configuration.

**Comment by sconde** [comment]
@sachinprasadhs Is there any help you can offer here? I'm still not able to build from the source using CMake.

**Comment by pkgoogle** [comment]
Hi @sconde,

Thanks for reporting the issue, we don't have access to your exact environment and you are using environment variables in your command, can you please let us know what those are?

specifically: $CXX, $CC, ${pkg_install}, you can output them with this command:

```
echo $CXX
```
