### ISSUE TITLE
Is there a way to convert (or transfer weights from) CuDNNLSTM to TFLiteLSTMCell?

### ISSUE THREAD

**Issue by vighneshhegde** [tensorflow/tensorflow#57118]
### 1. System information

- OS Platform and Distribution: Ubuntu 18.04 (and Android for inference)
- TensorFlow installation: pip
- TensorFlow library: version 1.14.0

### 2. Code

I wish to use `CuDNNLSTM` for a bidirectional LSTM model in order to make use of GPU for training. A short code snippet is below.

```
        forward_layer = tf.compat.v1.keras.layers.CuDNNLSTM(164, return_sequences=True, time_major=True)
        backward_layer = tf.compat.v1.keras.layers.CuDNNLSTM(164, return_sequences=True, time_major=True,
                         go_backwards=True)
        output = tensorflow.keras.layers.Bidirectional(forward_layer, backward_layer=backward_layer)(input_feature)
```
However, this architecture is too heavy to deply on android using TFLite. Also, I need to avoid the Select TF Ops which increase the size of the runtime dramatically. Therefore, I decided to use experimental `TFLiteLSTMCell` in combination with `bidirectional_dynamic_rnn` , which works very well when trained on CPU. 

```
        lstm_forward = tf.compat.v1.lite.experimental.nn.TFLiteLSTMCell(164, use_peepholes=False, name="fw")
        lstm_backward = tf.compat.v1.lite.experimental.nn.TFLiteLSTMCell(164, use_peepholes=False, name="bw")
        infer_output, infer_state =  tensorflow.lite.experimental.examples.lstm.rnn.bidirectional_dynamic_rnn(
                lstm_forward,lstm_backward,lstm_inputs, dtype='float32', time_major=True)
```

I'm using what I believe is a reasonably standard method of conversion:

```
            converter = tf.compat.v1.lite.TFLiteConverter.from_session(sess, [roi], [y_pred])

            converter.experimental_new_converter = True
            converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]

            # converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS], tf.lite.OpsSet.SELECT_TF_OPS]
            # We do not want to use Select TF Ops

            tflite = converter.convert()
```

Is there any way to convert weights from `CuDNNLSTM` to `TFLiteLSTMCell`? Even a way to do it from `LSTM` (non cudnn) to `TFLiteLSTMCell` will be most helpful, becuase transferring weights `CuDNNLSTM` to `LSTM` is well documented and not a big hurdle.

Any other way to convert CuDNNLSTM to TFLite without using Select Ops is also welcome.

Thanks in advance!

**Comment by mohantym** [comment]
Hi @vighneshhegde !
1.x version are not supported any more. I was thinking of using get_weights then set_weights method to transfer the weights from CudNNLSTM to LSTMcell model.

Attached relevant [thread](https://medium.com/howtoai/model-surgery-copy-weights-from-model-to-model-a31b1dec7a7a) for reference.

Please let us know after your trial.

Thank you!

**Comment by vighneshhegde** [comment]
Hi @mohantym , thanks very much for your response!

I have tried manualy transferring the weights (i.e., "model surgery"), but I must be missing something like a transpose operation or some other thing because the results don't come out right. The [documentation](https://docs.w3cub.com/tensorflow~1.15/lite/experimental/nn/tflitelstmcell) I found for TFLiteLSTMCell mentions a transpose operation but was not particularly enlightening. Would you be able to point out to a better source, perchance?

Also, any comments on converting CuDNNLSTM to TFLite without using Select Ops? Thank you!

**Comment by mohantym** [comment]
@vighneshhegde !

Not sure on 1.x apis.  But please feel free to go through this document on[ LSTMFusion Code lab](https://colab.sandbox.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb) (I think it will be possible to convert without select ops with this method)
 
Thank you!

**Comment by vighneshhegde** [comment]
@mohantym this seems to work, even for Bidirectional LSTMs. Thank you very much!
