### ISSUE TITLE
Tensorlow installation issue

### ISSUE THREAD

**Issue by ravikairam** [tensorflow/tensorflow#57129]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

latest

### Custom Code

Yes

### OS Platform and Distribution

windows

### Python version

3,9

### GPU model and memory

Intel (R) UHD Graphics 630

### Current Behaviour?

```shell
@gadagashwini

ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

### Standalone code to reproduce the issue

```shell
pip install tensorflow in virtual environment.
```

### Relevant log output

_No response_</details>

**Comment by gadagashwini** [comment]
Hi @ravikairam, You need to install Tensorflow with conda environment as suggested in the [Tensorflow site](https://www.tensorflow.org/install/pip#windows-native).

```
conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
python3 -m pip install tensorflow
# Verify install:
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
```
Thank you!
