### ISSUE TITLE
[Win] fft2d tries to link m.lib

### ISSUE THREAD

**Issue by kcoul** [tensorflow/tensorflow#57133]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Windows 10

### Current Behaviour?

```shell
Cannot compile tensorflow lite on Windows using CMake build system. Fails at linker stage while trying to link m.lib - the math library is only suitable for linking on macOS and Linux.

Will provide a patch for this issue.
```

### Standalone code to reproduce the issue

```shell
Build on any 2.9.x branch on Windows using CMake - build will fail while trying to link non-existent m.lib at fft2d linking stage.
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@kcoul,
This issue will move to closed status once the respected PR is merged. Thank you!
