### ISSUE TITLE
[Android]: Internal error: Cannot create interpreter: tensorflow/lite/core/subgraph.cc BytesRequired number of elements overflowed.

### ISSUE THREAD

**Issue by jhabr** [tensorflow/tensorflow#57131]
**System information**
- Android Device information (use `adb shell getprop ro.build.fingerprint`
  if possible):  
  (1) google/sdk_gphone64_arm64/emu64a:13/TPB4.220624.004/8808248:userdebug/dev-keys
  (2) Nokia/TA-1012_00WW/NB1:9/PPR1.180610.011/00WW_5_15K:user/release-keys
- TensorFlow Lite in Play Services SDK version (found in `build.gradle`): 2.9.0
- Google Play Services version
  (`Settings` > `Apps` > `Google Play Services` > `App details`):  
  (1) 22.18.21 (190400-453244992)
  (2) 22.26.15 (100400-461192076)

**Standalone code to reproduce the issue**
I'm trying to load a tflite model with dynamic input size of (1, None, None, 1) on _Android_ as follows:

```kotlin
import org.tensorflow.lite.Interpreter

companion object {
   private const val MODEL_PATH = "myModel.tflite"
}

val model = FileUtil.loadMappedFile(context, MODEL_PATH)

val options = Interpreter.Options()
options.numThreads = 5
// not using GPU or NNAPI because of missing dynamic tensor support
interpreter = Interpreter(model, options)
```

When instantiating the `Interpreter` I get the following error:

```
Internal error: Cannot create interpreter: tensorflow/lite/core/subgraph.cc BytesRequired number of elements overflowed.
Node number 0 (CONV_2D) failed to prepare.
```

When I run the exact same model using _Python_ it works as intended:

```python
from tensorflow.lite.python.interpreter import Interpreter

tf_lite_model = Interpreter(model_path=model_path)
tf_lite_model.resize_tensor_input(0, image.shape, strict=True) # image.shape - e.g.: (1, 43, 85, 1)
tf_lite_model.allocate_tensors()
```

When I skip the `resize_tensor_input()` operation in _Python_ (2. line) I get the **exact same error message** as in _Android_ which leads me to believe that the problem might be linked to the _Android_ interpreter's [allocate tensors](https://github.com/tensorflow/tensorflow/blob/4ad6160cf20af654c5e9eb553408cdd606b4da18/tensorflow/lite/java/src/main/java/org/tensorflow/lite/NativeInterpreterWrapper.java#L127) step within its [constructor](https://github.com/tensorflow/tensorflow/blob/4ad6160cf20af654c5e9eb553408cdd606b4da18/tensorflow/lite/java/src/main/java/org/tensorflow/lite/NativeInterpreterWrapper.java#L75) before resizing the input tensor.

**Any other info / logs**
Using _Android's_ ML Binding leads to the exact same error message.

```kotlin
val model = myModel.newInstance(context)
```

TFLite model input details:

```
[
  {
    'name': 'serving_default_image',
    'index': 0,
    'shape': array([1, 1, 1, 1], dtype=int32),
    'shape_signature': array([ 1, -1, -1,  1], dtype=int32),
    'dtype': <class 'numpy.float32'>,
    'quantization': (0.0, 0),
    'quantization_parameters': {
      'scales': array([], dtype=float32), 
      'zero_points': array([], dtype=int32), 
      'quantized_dimension': 0
    },
    'sparsity_parameters': {}
  }
]
```

Extracted from _Python's_ interpreter:

```python
from tensorflow.lite.python.interpreter import Interpreter

tf_lite_model = Interpreter(model_path=model_path)
input_details = tf_lite_model.get_input_details()
```

I do however succeed to instantiate the _Android_ interpreter when I use a static input tensor size, e.g. `(1, 50, 150, 1)`. Resizing the input tensor then to the desired size works as well:

```kotlin
import org.tensorflow.lite.Interpreter

val model = FileUtil.loadMappedFile(context, MODEL_PATH)
val options = Interpreter.Options()
options.numThreads = 5
interpreter = Interpreter(model, options)

interpreter.resizeInput(0, intArrayOf(1, bitmap.height, bitmap.width, 1), false)
interpreter.allocateTensors()
```

Any idea how to solve this (maybe except using static input tensor shape)?

**Comment by mohantym** [comment]
Hi @jhabr !

Sorry for the inconvenience. Dynamic shape, Tensor and Batch size is not supported yet and work in progress feature .
Present work around is go with a fixed shape as you mentioned .

Thank you!

**Comment by jhabr** [comment]
Hi @mohantym 

Thanks for your answer. I was able to make it run. If someone else encounters this problem, here is one way how to solve this:

1. Train the original model with dynamic input size, e.g. `(1, None, None, 1)`
2. During conversion to TFLite model fix the size of the input tensor:

```python
from tensorflow.lite.python.lite import TFLiteConverter

converter = TFLiteConverter.from_saved_model(
  model_path,
  input_shapes={"serving_default_input_4": [1, 50, 150, 1]},
)
```
This will create a TFLite model with the following input details:

```json
{
  'name': 'serving_default_input_4',
  'index': 0,
  'shape': array([  1,  50, 150,   1], dtype=int32),
  'shape_signature': array([  1,  50, 150,   1], dtype=int32),
  'dtype': <class 'numpy.float32'>,
  'quantization': (0.0, 0),
  'quantization_parameters': {
    'scales': array([], dtype=float32),
    'zero_points': array([], dtype=int32),
    'quantized_dimension': 0
  },
  'sparsity_parameters': {}
}
```

3. On _Android_ load the TFLite model using the _Interpreter_ class:

```kotlin
import org.tensorflow.lite.Interpreter

val model = FileUtil.loadMappedFile(context, MODEL_PATH)
val options = Interpreter.Options().apply { this.numThreads = 4 }

interpreter = Interpreter(model, options)

// check the input tensor shape
interpreter.getInputTensor(0).shape() // => [1, 50, 150, 1]
```

4. Resize the input tensor of the _Android_ interpreter to the size of the input image (bitmap):

```kotlin
interpreter.resizeInput(0, intArrayOf(1, bitmap.height, bitmap.width, 1), false)
interpreter.allocateTensors()

// check the input tensor shape
interpreter.getInputTensor(0).shape() // => [1, 118, 525, 1]
```
5. Convert the input image (bitmap) to `ByteBuffer`:

```kotlin
val imageProcessor = ImageProcessor.Builder()
    .add(TransformToGrayscaleOp()) // add transformation to match the number of channels
    .build()

var tensorImage = TensorImage(DataType.FLOAT32)
tensorImage.load(bitmap)

val imageBuffer  = imageProcessor.process(tensorImage).buffer
```

6. Run inference:

```kotlin
// output shape depending on the model output
val output = Array(1) { FloatArray(1) }
interpreter.run(imageBuffer, output)
```

However, for convenience reasons, I would like to use _Android's_ ML Binding to load the model. It would be potentially useful for cases like this to be able to resize the input tensor of the `Interpreter` as well, e.g.:

```kotlin
val myModel = MyModel.newInstance(context)

myModel.model.interpreter.resizeInput(0, intArrayOf(1, bitmap.height, bitmap.width, 1), false)
myModel.model.interpreter.allocateTensors()
```

@mohantym is there any way to use the ML Binding and change the input tensor size of the interpreter (that I missed)?

**Comment by mohantym** [comment]
@jhabr !

You can format the input and output size through Firebase [ML kit](https://firebase.google.com/docs/ml-kit/android/use-custom-models) and [TF hub ](https://towardsdatascience.com/machine-learning-with-android-11-whats-new-e8c829e9452)model binding. Feel free to close this issue if it is resolved.

Thank you!

**Comment by jhabr** [comment]
Thank you for the update @mohantym.
