### ISSUE TITLE
Problem with constructor of tensor

### ISSUE THREAD

**Issue by luliyucoordinate** [tensorflow/tensorflow#57142]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf2.9.1

### Custom Code

Yes

### Current Behaviour?

```shell
https://github.com/tensorflow/tensorflow/blob/v2.9.1/tensorflow/core/framework/tensor.cc#L699

There is a problem with the constructor of tensor, passing datatype to shape.
```

### Standalone code to reproduce the issue

```shell
Tensor::Tensor(DataType type) : shape_(type), buf_(nullptr) {}

https://github.com/tensorflow/tensorflow/blob/v2.9.1/tensorflow/core/framework/tensor.cc#L699
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@luliyucoordinate,
This issue will move to closed status once the respective PR is merged. Thank you!

**Comment by tilakrayal** [comment]
@luliyucoordinate,
The related [PR](https://github.com/tensorflow/tensorflow/pull/57143) which was raised got merged and also the files are also changed with the  **set_dtype(type)**

https://github.com/tensorflow/tensorflow/pull/57143/files


```
Tensor::Tensor(DataType type) : shape_(TensorShape({})), buf_(nullptr) {
  set_dtype(type);
```

Thank you!

**Comment by luliyucoordinate** [comment]
OK
