### ISSUE TITLE
update documentation of tf.abs

### ISSUE THREAD

**Issue by cheyennee** [tensorflow/tensorflow#57150]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

TF2.4

### Custom Code

Yes

### OS Platform and Distribution

win11

### Current Behaviour?

```shell
The input of tf.abs shoule be a Tensor or SparseTensor of type float16, float32, float64, int32, int64, complex64 or complex128 on documentation. That is to say, input doesn't support the type of int8 tensor. So if I input a int8 tensor, it would throw exception. But I find that when I input int8 tensor, it works well. I think it would be better to add an example to illustrate how the code works in the case of int8 or add support for int8 type on documentation.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
results={}
try:
  arg_0 = tf.saturate_cast(tf.random.uniform([], minval=0, maxval=2, dtype=tf.int64), dtype=tf.int8)
  print(arg_0)
  # tf.Tensor(1, shape=(), dtype=int8)
  results["res"] = tf.abs(arg_0,)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)
# {'res': <tf.Tensor: shape=(), dtype=int8, numpy=1>}
```

### Relevant log output

_No response_</details>

**Comment by HarisBalaji** [comment]
hey,@tilakrayal I want to do contribution in this open issue. Can you assign me in this?

**Comment by HarisBalaji** [comment]
I also want to know how you will be assigned by google-ml-butler?
I am a beginner. Please help me.

**Comment by cheyennee** [comment]
> I also want to know how you will be assigned by google-ml-butler? I am a beginner. Please help me.

I didn't assign to him😥 It seems to be automatically assigned by the system bot?

**Comment by cheyennee** [comment]
> I also want to know how you will be assigned by google-ml-butler? I am a beginner. Please help me.

I dont know😥I am also a beginner, I just want to report this issue.

**Comment by HarisBalaji** [comment]
Is the selection by system bot random?

**Comment by HarisBalaji** [comment]
Assignees - @tilakrayal 
How you become assignee?
Please clear my doubt

**Comment by tilakrayal** [comment]
@cheyennee,
It was already mentioned in `math_ops.py` where all the arithmetic operations were included for dtype `int8`. Could you please take a look at the link below.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/math_ops.py

Thank you!

**Comment by cheyennee** [comment]
> @cheyennee, It was already mentioned in `math_ops.py` where all the arithmetic operations were included for dtype `int8`. Could you please take a look at the link below. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/math_ops.py
> 
> Thank you!

Get it. Thanks. I will close this issue👌
