### ISSUE TITLE
TFLite C API in Android: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter

### ISSUE THREAD

**Issue by acebenson0704** [tensorflow/tensorflow#57156]
<details><summary>Click to expand!</summary> 
 
### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

Windows 10

### Mobile device

Android API 31

### Python version

3.9

#### How I bulid android studio project?
As tutorial [here](https://www.tensorflow.org/lite/android/development?hl=de), I create a Android Studio NDK project as following steps:
1. Download arr [here](https://search.maven.org/artifact/org.tensorflow/tensorflow-lite/2.9.0/aar) and unzip it.
2. Put shared library and header files into project and link in CMakeLists.txt as following:

#### Current Behaviour
My TFLite model is for on-device training, so there are signatures including infer and train.
For infer signature, the functions defined in `c_api_experimental.h` work well and generate reasonable result.
But for train signature, I follow the same steps: set input tensors -> TfLiteSignatureRunnerInvoke -> read output tensors.
But the error log shows Select TensorFlow op(s) is not support by this interpreter when running TfLiteSignatureRunnerInvoke.

#### What I tried
1. Download tensorflow-lite-select-tf-ops shared library [here](https://search.maven.org/artifact/org.tensorflow/tensorflow-lite-select-tf-ops/2.9.0/aar), and put it into project and edit CMakeLists.txt as before.
2. I think there is no C API for flex delegate? And #53849 shows we don't need to add it by `TfLiteInterpreterOptionsAddDelegate` explictly?

#### Questions
How to apply/link TFLite select tf ops in Android Studio project in C API?

### Standalone code to reproduce the issue

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.18.1)
project("project_name")

# ==================== For TFLite ====================
# Specify where to find the header files for TF Lite C++
set(JNI_DIR
        ${CMAKE_CURRENT_SOURCE_DIR}/../jni)
include_directories(${JNI_DIR})

add_library( tflite-lib SHARED IMPORTED )
set_target_properties( tflite-lib PROPERTIES IMPORTED_LOCATION
        ${JNI_DIR}/${ANDROID_ABI}/libtensorflowlite_jni.so)

add_library( tflite-flex-lib SHARED IMPORTED )
set_target_properties( tflite-flex-lib PROPERTIES IMPORTED_LOCATION
        ${JNI_DIR}/${ANDROID_ABI}/libtensorflowlite_flex_jni.so)

# ==================== For TFLite ====================

add_library(
        project_name
        SHARED
        tflite.c
        native-lib.cpp)
find_library( # Sets the name of the path variable.
        log-lib
        log)

target_link_libraries( # Specifies the target library.
        project_name
        tflite-lib
        tflite-flex-lib
        ${log-lib})
```

tflite-lib.c
```
// Interpreter
TfLiteModel* model = TfLiteModelCreateFromFile(infer_model_path)
TfLiteInterpreterOptions* options = TfLiteInterpreterOptionsCreate();
TfLiteInterpreter* interpreter = TfLiteInterpreterCreate(model, options);
```

build_model.py
```
// convert tflite model
converter = tf.lite.TFLiteConverter.from_saved_model(temp_dir, signature_keys=list(sign_dict.keys()))
converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
        tf.lite.OpsSet.SELECT_TF_OPS     # enable TensorFlow ops.
]
converter.experimental_enable_resource_variables = True
tflite_model = converter.convert()
```

### Relevant log output

```shell
2022-08-12 03:51:58.303 3854-3854/com.example.project_name E/tflite: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select
2022-08-12 03:51:58.303 3854-3854/com.example.project_name E/tflite: Node number 151 (FlexRestore) failed to prepare.
```

</details>

**Comment by mohantym** [comment]
Hi @acebenson0704 !
Including Flex delegate option in CMake is still a pending Feature request as you pointed out.

You can build local flex delegate  C++ run time  environment using below command.
`bazel build -c opt --config=monolithic tensorflow/lite/delegates/flex:tensorflowlite_flex
`

From Android perspective, You can build your AAR files using sh command and declare Select ops dependency in build Gradle while installing locally built aar files through Maven command.

[Ref ](https://www.tensorflow.org/lite/guide/ops_select#android_aar)

Thank you!

**Comment by acebenson0704** [comment]
Thanks for your reply.

I tried to build tensorflow lite in Windows.

First, I tried first command `bazel build -c opt --config=monolithic tensorflow/lite/delegates/flex:tensorflowlite_flex`
But in windows, it built .dll files.
**Can I build .so files by add some flags or anything else? (For Android C/C++ NDK)**

Second, I also tried the second command follow the ref link. 
`sh .\tensorflow\lite\tools\build_aar.sh --input_models="path\to\model1.tflite","path\to\model2.tflite" --target_archs=arm64-v8a,armeabi-v7a`

But It shows that 
`tensorflow/tmp/BUILD:4:30: gen_selected_ops failed: (Exit -1073741819): generate_op_registrations.exe failed: error executing command`

**I want to know if bazel build tflite is avaliable in Windows?**
**Or how can I use TFLite C/C++ API in Android C/C++ NDK App with Select Ops?**

Thanks!!

**Comment by mohantym** [comment]
@acebenson0704 !
To build .so files , You can either run the same command in linux or Colab.

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by sachinprasadhs** [comment]
For windows systems the equivalent to .so files will be .dll files which will get the linking information from .lib files.
