### ISSUE TITLE
The type of parameter 'device_type' in tf.config.list_logical_devices wrong

### ISSUE THREAD

**Issue by cheyennee** [tensorflow/tensorflow#57153]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

TF2.4

### Custom Code

Yes

### OS Platform and Distribution

win11

### Current Behaviour?

```shell
device_type is optional string on documentation. However, I find that when device_type is list/int/float or other type, code works. It just returns an empty list. So type restrictions should be removed from the documentation.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
results={}
try:
  arg_0 = -51
  results["res"] = tf.config.list_logical_devices(arg_0,)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)
# results = {'res': []}
```

### Relevant log output

_No response_</details>

**Comment by cheyennee** [comment]
Same problem is found in tf.config.list_physical_devices.
```
import tensorflow as tf
results={}
try:
  arg_0 = -1.0
  results["res"] = tf.config.list_physical_devices(arg_0,)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)
# results = {'res': []}
```

**Comment by cheyennee** [comment]
> @cheyennee, Could you please feel free to submit a PR for the requested change or share the link where the requested change is to be made. Thank you!

https://tensorflow.google.cn/api_docs/python/tf/config/list_logical_devices#args
The 'string' constraints should be deleted from the description of device_type. For example, (optional) Only include devices matching this device type. 

https://tensorflow.google.cn/api_docs/python/tf/config/list_physical_devices#args
The 'string' constraints should be deleted from the description of device_type as well. Because not only string type value can be set to device_type, list/bool or other type value can also be set to device_type.

**Comment by tilakrayal** [comment]
@cheyennee,
We would prefer a PR for the validation, Could you please feel free to submit a PR for the requested change to be made. Thank you!
