### ISSUE TITLE
Universal dataset generation toolkit ?

### ISSUE THREAD

**Issue by zuoxingdong** [tensorflow/tensorflow#5716]
Is it feasible to add a build-in universal tool to create a TF dataset from raw source data, e.g. `dataset = tf.CreateDataSet(..RAW_SOURCE_PATH..)`, and then can use it like `dataset.train.next_batch, dataset.validation.epochs_completed` etc..

**Comment by girving** [comment]
This seems a bit too open ended, so I'm going to close.  I'd recommend using the new input pipelines: https://www.tensorflow.org/api_docs/python/tf/contrib/data.
