### ISSUE TITLE
tf.keras.layers.Dense documentation wrong

### ISSUE THREAD

**Issue by cheyennee** [tensorflow/tensorflow#57165]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

TF2.4

### Custom Code

Yes

### Current Behaviour?

```shell
The parameter 'units' is a positive integer on documentation. However, when 'unit' is 0, code works. And when 'unit' is -1, the error message is "Error:Dimension -1 must be >= 0". So 'units' is not a negative integer whose value can be set to positive integer and zero.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
results={}
try:
  arg_0 = 0
  activation = "softmax"
  arg_class = tf.keras.layers.Dense(arg_0,activation=activation,)
  arg_input = tf.random.uniform([3, 50, 1], dtype=tf.float32)
  results["res"] = arg_class(arg_input)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)
'''
results = {'res': <tf.Tensor: shape=(3, 50, 0), dtype=float32, numpy=array([], shape=(3, 50, 0), dtype=float32)>}
'''
```

### Relevant log output

_No response_</details>

**Comment by cheyennee** [comment]
Same problem is found in these APIs:
tf.keras.layers.GRU

**Comment by tilakrayal** [comment]
@cheyennee,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by cheyennee** [comment]
> ```shell
> results = {'res': <tf.Tensor: shape=(3, 50, 0), dtype=float32, numpy=array([], shape=(3, 50, 0), dtype=float32)>}
> ```

Thanks for reminding. I have open this issue on keras repo. 🙂

**Comment by tilakrayal** [comment]
@cheyennee,
Could you please feel free to move this issue to closed status. Thank you!
