### ISSUE TITLE
Error in spec = model_spec.get('efficientdet_lite0')

### ISSUE THREAD

**Issue by Abdullah-208** [tensorflow/tensorflow#57160]
I am making a custom object detection model.
```
spec = model_spec.get('efficientdet_lite0')
```
When I run the above line of code it gives the following error.
AttributeError: module 'keras.api._v2.keras.mixed_precision' has no attribute 'experimental'
I am using the official tensorflow colab notebook's code (in Spyder(anaconda))

**Comment by mohantym** [comment]
Hi @Abdullah-208 !
Could you provide a complete reproducible code to replicate the issue. I can not replicate in 2.8 version .
Attached relevant threads for reference . [Ref](https://discuss.tensorflow.org/t/attributeerror-module-keras-api-v2-keras-mixed-precision-has-no-attribute-experimental/11225/3?u=manas_mohanty) .

Thank you!

**Comment by Abdullah-208** [comment]
Hi @mohantym!
The link to the colab is https://colab.research.google.com/github/khanhlvg/tflite_raspberry_pi/blob/main/object_detection/Train_custom_model_tutorial.ipynb

**Comment by mohantym** [comment]
@Abdullah-208 !
Installation was taking a lot  of time with this below code snippet.
```
!pip install -q tflite-model-maker
!pip install -q tflite-support
```
so changed to
```
!pip install -q --use-deprecated=legacy-resolver tflite-model-maker
!pip install -q tflite-support
```
Attached resolved [gist](https://colab.sandbox.google.com/gist/mohantym/9414890aa9932b426a01999ff0f7dd78/model-maker-object-detection-for-android-figurine.ipynb#scrollTo=wnqktl45PZRy) for reference.

For raspberry inference , Could you give a try the instructions from this [document](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/raspberry_pi).

Thank you!

**Comment by Abdullah-208** [comment]
When I tried running the below code snippet it showed an error.
```
!pip install -q --use-deprecated=legacy-resolver tflite-model-maker
!pip install -q tflite-support
```
The error it gives is 
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
tensorflowjs 3.19.0 requires packaging~=20.9, but you'll have packaging 21.3 which is incompatible.
tensorflowjs 3.19.0 requires protobuf==3.20.0, but you'll have protobuf 3.17.3 which is incompatible.
tflite-support-nightly 0.4.0.dev20220815 requires flatbuffers>=2.0, but you'll have flatbuffers 1.12 which is incompatible.
tflite-support-nightly 0.4.0.dev20220815 requires protobuf<4,>=3.18.0, but you'll have protobuf 3.17.3 which is incompatible.

**Comment by Abdullah-208** [comment]
@mohantym!
thanks for your help!
Problem is solved!
