### ISSUE TITLE
tensorflow.python.framework.errors_impl.UnknownError: JIT compilation failed. [Op:FloorMod]

### ISSUE THREAD

**Issue by whatdhack** [tensorflow/tensorflow#57162]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux

### Python version

3.9.13

### CUDA/cuDNN version

11.6.2

### Current Behaviour?

```shell
Getting the following error.


  File "lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 7164, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.UnknownError: JIT compilation failed. [Op:FloorMod]
```

Can be fixed by setting the following , however that implies XLA being used is some form. 

```
TF_XLA_FLAGS="--tf_xla_auto_jit=-1" XLA_FLAGS="--xla_gpu_cuda_data_dir=${CUDA_PATH}"
```
```


### Standalone code to reproduce the issue

```shell
Not sure how to do that.
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@whatdhack 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!
