### ISSUE TITLE
how to clear tf.function's cache 

### ISSUE THREAD

**Issue by zzq96** [tensorflow/tensorflow#57169]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

tf 2.8.2

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu

### Python version

3.8

### Current Behaviour?

```shell
clear memory used by generating concrete functions
```

### Standalone code to reproduce the issue

```shell
# Now memory is 1.6G.
# Then, I get a concrete function by this:
def test():
    f = train_step._get_concrete_function_garbage_collected(images, labels)
    return f
f = test()

# Now, the memory is 6.4G
#Next, I tried to clear this concrete function to reduce memory. So I clear this concrete function by this:

train_step._stateless_fn._function_cache.clear()
train_step._stateful_fn._function_cache.clear()

#And start gc to flush memory:
import gc
gc.collect()

#But, the memory is still 6.4G.
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@zzq96,
Could you please try to execute the below mentioned to clear the  `tf.function` cache.

`self.call._stateful_fn._function_cache.primary.clear()`

`self.call = tf.function(self.call.python_function)`--That will clear everything; you may want to copy over input_signature and other `tf.function` options if applicable. Thank you!

**Comment by zzq96** [comment]
> @zzq96, Could you please try to execute the below mentioned to clear the `tf.function` cache.
> 
> `self.call._stateful_fn._function_cache.primary.clear()`
> 
> `self.call = tf.function(self.call.python_function)`--That will clear everything; you may want to copy over input_signature and other `tf.function` options if applicable. Thank you!

hi, i have tried it.
although the cache of tf.function is cleared, but the memory isn't cleared:
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/39215341/185018451-b8d8822e-fc6e-4de1-a915-c47a6e63e88d.png">

**Comment by tilakrayal** [comment]
@zzq96,
Could you please try to execute the mentioned to clear the `tf.function `cache. **self.call._stateful_fn._function_cache.primary.clear()**
Also please take a look at this doc [link](https://www.tensorflow.org/guide/function) which provides the information for better performance with `tf.function`. Thank you!

**Comment by zzq96** [comment]
> self.call._stateful_fn._function_cache.primary.clear()

hi, i have tried it, but the memory isn't cleared:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/39215341/186066492-5b1c4acf-0e9b-449f-8b30-8d3a36483cc1.png">
