### ISSUE TITLE
Error while exporting efficientdet_lite0 model to tflite format

### ISSUE THREAD

**Issue by Abdullah-208** [tensorflow/tensorflow#57177]
I have trained a custom object detection model using tflite-model-maker using efficientdet_lite0 architecture but when I try to export the model in tflite format using below code snippet
```
model.export(export_dir='.', tflite_filename='Myhanddetectionmodel.tflite')
```
It gives the below given error
```
 TypeError: EndVector() missing 1 required positional argument: 'vectorNumElems'
```
I am using google colab!

**Comment by mohantym** [comment]
Hi @Abdullah-208 !
Thanks for reporting . We are already tracking this bug here in this issue #57174 . Could you post your comment there.
Thank you!

**Comment by mohantym** [comment]
Thank you!
