### ISSUE TITLE
LeakyRelu in Tensorflow lite with the Hexagon Delegate not supported

### ISSUE THREAD

**Issue by eelcoder** [tensorflow/tensorflow#57171]
When using a tflite model (8-bits quantized via TensorFlow lite conversion framework) that includes the activation function "LeakyRelu", the Hexagon delegate from tensorflow framework cannot perform the DNN inference on the whole graph, but rather it falls back to the CPU/XNNPack delegate. This is due to the fact that 'LeakyRelu' operation is not supported by the Hexagon Delegate (confirmed in TensorFlow doc: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/README.md). When using Relu activation function (and Relu6 as well), we can see below that the TF Hexagon Delegate can process the whole DNN graph, unfortunately, the qualitative results I get are much worse, hence the need of having 'Leaky Relu' implemented in the Hexagon Delegate.

**System information**
- OS Platform and Distribution): Android 10, NDK R21e
- TensorFlow installed from (source or binary): from source using the Release tag '2.9.1'
- TensorFlow version (or github SHA if from source):  2.9.1

**Output of Tensorflow library when running an inference with a model that includes 'LeakyRelu' activation function**

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Initialized TensorFlow Lite runtime.
loaded libcdsprpc.so
INFO: TfLiteHexagonDelegate delegate: 8 nodes delegated out of 53 nodes with 1 partitions.
INFO: Replacing 8 node(s) with delegate (TfLiteHexagonDelegate) node, yielding 1 partitions.
```
As we can see below when replacing 'LeakyRelu' operation by 'Relu', then the TF Hexagon delegate can process the whole DNN graph.

**Output of Tensorflow library when running an inference with a model that includes 'Relu' activation function**

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Initialized TensorFlow Lite runtime.
loaded libcdsprpc.so
INFO: TfLiteHexagonDelegate delegate: 53 nodes delegated out of 53 nodes with 1 partitions.
INFO: Replacing 53 node(s) with delegate (TfLiteHexagonDelegate) node, yielding 1 partitions.
```

Would it be possible to implement 'LeakyRelu' in TF Hexagon Delegate ?

**Comment by mohantym** [comment]
Hi @eelcoder !
Could you also provide a minimal reproducible code .
Thank you!
