### ISSUE TITLE
How to install Tensorflow on Python3 (using Bash on Ubuntu on Windows)

### ISSUE THREAD

**Issue by thirumalaipm** [tensorflow/tensorflow#5717]
Hi,

I have Bash on Ubuntu on Windows (on Windows 10) also I have python 2.7, 3.4 and 3.5 installed. When I follow below url to install tensor flow it installs in python 2.7 only.

http://www.hanselman.com/blog/PlayingWithTensorFlowOnWindows.aspx

I want to install tensorflow on Python 3.5. Please let me know how to install the same. To move to python 3.5, I use python3.5 on the Bash command prompt.

Many Thanks, Thirumalai M

**Comment by prb12** [comment]
I'm afraid this is not a supported configuration.  

Please consider posting your question to StackOverlfow, or even to Scott Hanselmann's blog.
