### ISSUE TITLE
openCL crash in models converted by the newer versions of TF (e.g. TF 2.9)

### ISSUE THREAD

**Issue by Bahar-BM** [tensorflow/tensorflow#57180]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installation (pip package or built from source): source
- TensorFlow library (version, if pip package or github SHA, if built from source): TF 2.8 - TF 2.9 - TF Nightly

### 2. Code

We have implemented a small tool (with a comprehensive ReadMe) to reproduce the mentioned issue. Here is the link to the repository:
https://github.com/Bahar-BM/dense_3D_inputs

### 3. Failure after conversion
Converting models in which there is at least one Dense layer fed by a 3D input should be done using older versions of TensorFlow (we have tested v2.3 and v2.4). Otherwise, the obtained TFLite model will crash with the OpenCL delegate with this error message:

```
ERROR: TfLiteGpuDelegate Init: FULLY_CONNECTED: Amount of input data should match weights width
```

**Comment by mohantym** [comment]
Hi @Bahar-BM !
Could you check this [comment](https://github.com/tensorflow/tensorflow/issues/34525#issuecomment-564755977) from similar [issue ](https://github.com/tensorflow/tensorflow/issues/34525)which suggests using 1x1 convolution.
Thank you!

**Comment by roserg** [comment]
Hi, try after this commit https://github.com/tensorflow/tensorflow/commit/61b98be3c21f0ae40657f62eaaced4bb8e904382

**Comment by Bahar-BM** [comment]
@roserg 
Hi, your new commit resolved my issue. Thanks!
