### ISSUE TITLE
Is there a way to see MatMul tensor shapes in TensorBoard or elsewhere ? 

### ISSUE THREAD

**Issue by whatdhack** [tensorflow/tensorflow#57189]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux

### Python version

3.9

### Current Behaviour?

```shell
How do I find out the final MatMul shapes used by TensorFlow after all the Grappler etc. processing,
```

### Standalone code to reproduce the issue

```shell
Not applicable
```

### Relevant log output

```shell
Not applicable
```
</details>

**Comment by gadagashwini** [comment]
Hi @whatdhack, Output of the Matmul prints the shape along with value.
Please follow the below sample code snippet
```
a is  # 2-D tensor
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])
b  is # 2-D tensor
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])
c = tf.matmul(a, b)
c  # `a` * `b`
```
**Output**
```
<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>
```

**Comment by whatdhack** [comment]
@gadagashwini , thanks for replying.  Some of the Keras layers like LSTM, etc  are  decomposed into matmuls by Grappler.  How would one find the  shapes of  the tensor involved in such operations ?

**Comment by gadagashwini** [comment]
Hi @whatdhack, Using Tensorboard Op-level graph, You can see metadata by clicking on a node. This allows you to see inputs, outputs, shapes and other details. For more details refer this [link](https://www.tensorflow.org/tensorboard/graphs#op-level_graph). Thank you!
