### ISSUE TITLE
Please publish official wheels for Apple Silicon

### ISSUE THREAD

**Issue by rgov** [tensorflow/tensorflow#57185]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

macOS 12

</details>

### Current Behaviour?

Users of Macs with Apple Silicon (M1, M2, etc.) cannot `pip install tensorflow` because wheels for the architecture are not published on PyPI.

The current state of this (August 2022) is that these wheels are published under a different package name, [`tensorflow-macos`](https://pypi.org/project/tensorflow-macos/), which is released separately by Apple.

This makes it more complicated to install software that uses TensorFlow on macOS; e.g., a `requirements.txt` file might have to look something like

```
tensorflow;  sys.platform != 'darwin' or platform.machine != 'arm64'
tensorflow-macos;  sys.platform == 'darwin' and platform.machine == 'arm64'
``` 

Apple's repository, [`tensorflow_macos`](https://github.com/apple/tensorflow_macos) is archived which makes it unclear where users should get support. Is it here?

Moreover, at the time of writing, `tensorflow-macos` is version 3.9.2, which is one bugfix release ahead of the latest official `tensorflow`, so comparing version numbers across the two is difficult.

And it leaves many other unanswered questions: Are these being tested in CI? How soon after an upstream release will `tensorflow-macos` get an update?

Finally, both `tensorflow` and `tensorflow-macos` support Intel-based Macs, which is another potential point of confusion—which is preferred?

cc @kulinseth @jhavukainen

### Standalone code to reproduce the issue

```shell
(.venv) % arch
arm64
(.venv) % python3 -m pip install tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

**Comment by gadagashwini** [comment]
Hi @rgov, Currently there is no official GPU support for running TensorFlow on MacOS. You can get macOS (CPU-only) wheels.


Python 3.7 | https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-2.9.0-cp37-cp37m-macosx_10_14_x86_64.whl
-- | --
Python 3.8 | https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-2.9.0-cp38-cp38-macosx_10_14_x86_64.whl
Python 3.9 | https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-2.9.0-cp39-cp39-macosx_10_14_x86_64.whl
Python 3.10 | https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-2.9.0-cp310-cp310-macosx_10_14_x86_64.whl

Thank you!

**Comment by rgov** [comment]
Hi @gadagashwini thank you but the issue is not about CPU vs GPU wheels, it is about arm64 vs x86_64 wheels. All of the ones you linked are x86_64 wheels.

**Comment by kulinseth** [comment]
@nitins17 , @learning-to-play and @yarri-oss

**Comment by yarri-oss** [comment]
@rgov thank you for summarizing this issue. On behalf of the Apple and Google teams working on this, we are planning official support for Apple Silicon (Aarch64 based) CPUs, and to streamline GPU support. I'll follow up in this issue when we have more to share.

**Comment by BenjaminDEMAILLE** [comment]
> @rgov thank you for summarizing this issue. On behalf of the Apple and Google teams working on this, we are planning official support for Apple Silicon (Aarch64 based) CPUs, and to streamline GPU support. I'll follow up in this issue when we have more to share.

Do you have an approximative estimated date of aviability of the update ?

**Comment by davidxia** [comment]
@rgov 

> Finally, both `tensorflow` and `tensorflow-macos` support Intel-based Macs, which is another potential point of confusion—which is preferred?

`tensorflow-macos` works for Apple silicon devices (e.g. M1, M2, etc) when used with Rosetta (i.e. x86 Python virtualenv). `tensorflow` won't work because it's compiled with AVX extension which [Rosetta doesn't support](https://developer.apple.com/documentation/apple-silicon/about-the-rosetta-translation-environment).

I use `pyenv` to create x86 envs on my M1. I use a lot of other TF/TFX libraries that transitively pull in `tensorflow` not `tensorflow-macos`. To fix this, I run `pip install tensorflow-macos` at the end. The `tensorflow-macos` replaces all the original `tensorflow` files and the `imports` keep working. You'll end up with broken or inconsistent pip environment though. 🤷 

@yarri-oss IMHO the proper fix Google should pursue is to publish macosx-arm64 wheels under the `tensorflow` namespace in various package repos like PyPI and not have a separate `tensorflow-macos` namespace that breaks various Python packaging tooling like `pip`.

**Comment by mikcnt** [comment]
Let's also mention that [Apple's docs](https://developer.apple.com/metal/tensorflow-plugin/) to set up Tensorflow Metal don't mention things like `tensorflow-text`. How do you do that without going crazy? 🤯

**Comment by carlthome** [comment]
Any update on this as of 2.11?

**Comment by sapphire008** [comment]
Getting the CPU-only support out the door will at least help those who needs cross platform compatibility of dependency management. If Tensorflow wants to compete with PyTorch, it probably needs to accelerate this issue soon. See what PyTorch has done already (since Mar 2021) to at least support arm64 CPU:

![Screenshot 2023-01-01 at 5 09 43 PM](https://user-images.githubusercontent.com/3713023/210186024-d0928799-1ec2-4812-b5ed-b0222f1b272e.png)

**Comment by SuryanarayanaY** [comment]
Hi @rgov ,

Update on this. We can use pre built binaries for Apple M1,M2 etc with tf-nightly. Could you please try using command `pip install tf-nightly` and let us know if that solves the purpose.

**Comment by tux-o-matic** [comment]
@SuryanarayanaY, are these nightly builds just arm64 or do they also make use of MPS and/or the neural engine?

**Comment by SuryanarayanaY** [comment]
In fact this is new development for us. I too waiting for more context on same. I am not sure what do you mean by MPS ?
Coming to neural engine are you referring to Apple neural engine ? If it was supported earlier on tensorflow-macos i.e Apple package it is likely to support with tf-nightly also.This is just my personal view, however I am awaiting more information from our development team. Thanks!

**Comment by SuryanarayanaY** [comment]
Please refer the below change in [setup.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py) from master branch.

https://github.com/tensorflow/tensorflow/blob/3ace0c0eb8ef5856acc7a0fe6396b696ff800262/tensorflow/tools/pip_package/setup.py#L155-L159

This refers that the command pip install tf-nightly on mac-os with `Darwin` system and `Arm64` Architecture (i.e Apple silicon) installs the package built by `Apple`.

**Comment by rgov** [comment]
As I understand it the change makes `pip install tensorflow` also include `tensorflow-macos` on Apple Silicon Macs. This is certainly easier for the user.

Judging by the release history of `tf-nightly-macos` it does look like they're being built by CI, so hopefully the releases stay in sync now.
