### ISSUE TITLE
Is the estimate of how big TFLite is on ARM incorrect for iOS?

### ISSUE THREAD

**Issue by drubinstein** [tensorflow/tensorflow#57196]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### Mobile device

iOS

### Current Behaviour?

When trying to link against TFLite for iOS based on the CocoaPods. We noticed a nearly 3-4MB increase in our binary size as opposed to the [documentation](https://www.tensorflow.org/lite/guide) which states that 

```
The TensorFlow Lite binary is ~1MB when all 125+ supported operators are linked (for 32-bit ARM builds), and less than 300KB when using only the operators needed for supporting the common image classification models InceptionV3 and MobileNet.
```
Admittedly this was for 64-bit ARM, but I don't believe that should make a difference?

Per Bloaty, the top symbols came from
```
    FILE SIZE        VM SIZE
 --------------  --------------
  30.1%  1.27Mi  30.1%  1.27Mi    tflite::AcquireFlexDelegate()
  16.9%   728Ki  16.9%   728Ki    _TfLiteXNNPackDelegateDelete
  12.8%   548Ki  12.8%   548Ki    _TfLiteSignatureRunnerDelete
   9.4%   405Ki   9.4%   405Ki    _TfLiteOpaqueNodeGetOutput
   8.7%   372Ki   8.6%   372Ki    _TfLiteDelegateCreate
   6.4%   276Ki   6.4%   276Ki    _TfLiteTensorCopyToBuffer
```
Looking into it further, it looks like the flex delegate [is allowlisted](https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/lite/ios/allowlist_TensorFlowLiteC.txt) though I wouldn't normally expect it to be. I think this leads to an incorrect estimate of the binary size on the TFLite docs linked above.

Is there any reason why the FlexDelegate needs to be linked for iOS (similar question for XNNPack)? Can't they be extras to install like the Metal or CoreML Delegate? Making those two delegates optional would reduce the binary size by nearly 2MB, a near 50% decrease.

### Standalone code to reproduce the issue

```shell
N/A
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @drubinstein !
Could you share any minimal reproducible code to investigate this issue .
Thank you!

**Comment by drubinstein** [comment]
Hi @mohantym . I attached a zipped up xcode project using the tflite 2.9.1 Pod and a tflite file that can be used to build a project that integrates tflite. You'll need to run `pod install` to download the tflite pods as I removed them due to upload
[blah.zip](https://github.com/tensorflow/tensorflow/files/9385494/blah.zip)
 size constraints from github. After building it and running
```
bloaty -d symbols --debug-file=${HOME}/Library/Developer/Xcode/DerivedData/blah-fhhfxsdqwzmuwagvuuczrudbshao/Build/Products/Release-iphonesimulator/blah.app.dSYM/Contents/Resources/DWARF/blah /Users/drubinstein/Library/Developer/Xcode/DerivedData/blah-fhhfxsdqwzmuwagvuuczrudbshao/Build/Products/Release-iphonesimulator/blah.app/blah
```

You'll see the output:
```
    FILE SIZE        VM SIZE
 --------------  --------------
  46.0%  3.66Mi   0.0%       0    [__TEXT,__text]
  15.6%  1.24Mi  29.8%  1.24Mi    tflite::AcquireFlexDelegate()
   6.9%   560Ki  13.1%   560Ki    _TfLiteTensorCopyToBuffer
   5.7%   462Ki  10.8%   462Ki    _TfLiteXNNPackDelegateDelete
   5.0%   410Ki   9.6%   410Ki    _TfLiteSignatureRunnerDelete
   4.6%   377Ki   9.1%   389Ki    [__LINKEDIT]
   4.6%   372Ki   8.7%   372Ki    _TfLiteDelegateCreate
   2.3%   183Ki   4.3%   183Ki    _$s14TensorFlowLite7RuntimeOMa
   1.7%   139Ki   3.4%   145Ki    [958 Others]
   1.6%   133Ki   1.5%  64.0Ki    [__TEXT,__cstring]
   1.6%   133Ki   3.1%   133Ki    _TfLiteTensorCopyFromBuffer
   1.1%  93.5Ki   2.2%  93.5Ki    _$s14TensorFlowLite7RuntimeOMn
   0.8%  67.1Ki   1.6%  67.1Ki    _$s14TensorFlowLite0A0V5ShapeVs25ExpressibleByArrayLiteralAAMA
   0.7%  58.9Ki   0.0%       8    [__TEXT,__const]
   0.4%  33.4Ki   0.8%  33.4Ki    _$s14TensorFlowLite7RuntimeON
   0.3%  23.4Ki   0.0%      97    [__TEXT]
   0.3%  23.1Ki   0.5%  23.1Ki    _$s14TensorFlowLite0A0V5ShapeVAESQAAWL
   0.0%       8   0.5%  22.5Ki    [__DATA]
   0.3%  20.6Ki   0.5%  20.6Ki    [__TEXT,__unwind_info]
   0.2%  18.2Ki   0.0%       0    [Unmapped]
   0.2%  17.4Ki   0.4%  17.4Ki    [__DATA_CONST]
 100.0%  7.96Mi 100.0%  4.17Mi    TOTAL
```

Mirroring my earlier concerns. In this case, the sum of the top 6 items which are tflite related sum to ~3MB. 3x more than what the documentation on the website estimates

**Comment by mohantym** [comment]
@drubinstein !Thanks for the update.

Hi @sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by sachinprasadhs** [comment]
Since ARM64 architecture is different than ARM32 architecture the difference in size could be possible since under the hood there will be changes in the trace requests etc.
Have you checked with the ARM32, if yes, does it come under the size mentioned in the document.

**Comment by Kepnu4** [comment]
I've also encountered much bigger size than documented. It's around 2.2MB  without any delegates, ~4MB with metal delegate, ~5.2MB with metal + coreml delegates. The numbers are also for arm64. For sure arm32 would be smaller but common why do you measure it? All devices with iOS 11+ are arm64 and it's more than 99% of iOS users.

**Comment by drubinstein** [comment]
@sachinprasadhs I haven't checked it and didn't think it was worth the effort since all iPhones since 2013 have been 64-bit/arm64. I tried to get an armv7 build running on my M1 laptop but couldn't figure out a way to do it nor do I have a iPhone5  available to me unfortunately.

**Comment by sachinprasadhs** [comment]
Thanks for clarifying, since the documentation does not have a mention about `ARM64`, it would not be fair to take `ARM32` as a benchmark comparison, we would have to come up with the benchmark results for the `ARM64`.

**Comment by drubinstein** [comment]
So I tried to create a demo app in android (sorry no code), but I did see the following results when using Android Studio's APK Analyzer:

- TFLite 2.9 with Arm64 - 1.2MB Compressed, 3.2MB Uncompressed
- TFLite 2.9 with Armv7 (32-bit) - 1.1MB compressed, 2.2MB Uncompressed

The uncompressed value comes from checking the file size of the JNI .so file inside the aar file distributed by Tensorflow. Unlike in Swift, in Android we dont have the ability to perform any link time optimization since the binary is distributed as a shared object. In the documentation it may be important to distinguish between the compressed and uncompressed file sizes. But also this matches up with what we see in Swift where for arm64, the binary is >=3MB.

**Comment by yishuangP** [comment]
Hi, sorry for the late reply.

> Yes that would make sense, but then it'd also help in the documentation to specify what architecture and operating system the estimate was made for (android vs. iOS).

Sorry the documentation is outdated (the benchmark was done a couple years ago), we are working on updating the documentations. Will update it with new benchmark results.

> Is there any reason why the FlexDelegate needs to be linked for iOS (similar question for XNNPack)? Can't they be extras to install like the Metal or CoreML Delegate? Making those two delegates optional would reduce the binary size by nearly 2MB, a near 50% decrease.

The main idea is to include all the runtime code in the TensorFlowLiteC framework, but maybe we can ship another framework that excludes flex delegate. The TFLite interpreter uses XNNPack by default if CPU kernels are used as it runs faster.

I'll working on the size measurements and see if we can add continuous size watch for TFLite iOS library.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
