### ISSUE TITLE
Integer dtype not supported for tensorflow.math.tan

### ISSUE THREAD

**Issue by RickSanchezStoic** [tensorflow/tensorflow#57192]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

Yes

### Current Behaviour?

```shell
The documentation here https://www.tensorflow.org/api_docs/python/tf/math/tan states that it supports `integers` but it doesn't
```

### Standalone code to reproduce the issue

```shell
import tensorflow

print(tensorflow.math.tan(tensorflow.constant([1,2,3],dtype='int32')))
```
### Extra
It doesn't support any integer type

### Relevant log output

```shell
File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 7164, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Could not find device for node: {{node Tan}} = Tan[T=DT_INT32]
All kernels registered for op Tan:
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_HALF]
 [Op:Tan]
```
</details>

**Comment by HarisBalaji** [comment]
hey @tilakrayal , is the work in progress?
Shall I work on it?

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/775dc8ff4e3d8bb2b7c7dfbac78db7d3/untitled502.ipynb) and the issue was reproducible on all int datatype(**int8, int16, int32, int64)**, but was able to execute without any issue on other datatypes (**bfloat16, half, float32, float64, complex64, complex128)**

**Comment by cantonios** [comment]
Thanks @RickSanchezStoic for reporting.

@HarisBalaji are you offering to fix this?  You can probably just remove integer types from the documentation.

**Comment by sachinprasadhs** [comment]
@cantonios, I have created the PR by removing int dtypes, could you please review it. Thanks!

**Comment by HarisBalaji** [comment]
@cantonios l will fix this

**Comment by sachinprasadhs** [comment]
Hi, Interger dtype was never intended to be supported for `Tan`, the fix has been made and submitted in the commit here https://github.com/tensorflow/tensorflow/commit/fc0095d3ee7dd21b6b61978a8dd2f526c7455605#diff-85cdc6a4e3fb58b63753cb91f5c637e489b4fa481a7e848afe0c02f026181536, showing the supported dtypes. 
Document will be updated in once the Tensorflow 2.12 release is published. Thanks!
