### ISSUE TITLE
env: python: No such file or directory

### ISSUE THREAD

**Issue by zilaiyedaren** [tensorflow/tensorflow#57194]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

TF 2.8

### Custom Code

Yes

### OS Platform and Distribution

macos

### Mobile device

macbook pro

### Python version

3.10

### Bazel version

4.2.1

### Current Behaviour?

```shell
/tensorflow/core/util/BUILD:379:24: Action tensorflow/core/util/version_info.cc failed: (Exit 127): bash failed: error executing command /bin/bash -c 'bazel-out/ios-arm64-min9.0-applebin_ios-ios_arm64-opt-ST-80976841b7ce/bin/tensorflow/tools/git/gen_git_source --generate "$@" --git_tag_override=${GIT_TAG_OVERRIDE:-}' '' ... (remaining 4 argument(s) skipped)
env: python: No such file or directory
Target //tensorflow/lite/ios:TensorFlowLiteC_static_framework failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.010s, Critical Path: 0.06s
INFO: 62 processes: 62 internal.
```

### Standalone code to reproduce the issue

```shell
bazel build --config=ios_fat -c opt \
  //tensorflow/lite/ios:TensorFlowLiteC_static_framework
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @zilaiyedaren !

Can you give confirmation whether you said yes to your python location and IOS build  while running configure.py .
If yes , please add a symlink through the below command
```
whereis python3 # Find location of Python 3
sudo ln -s /usr/bin/python3 /usr/bin/python # Symlink for Python3 to Python
```

**Comment by zilaiyedaren** [comment]
@mohantym `sudo ln -s /usr/bin/python3 /usr/bin/python`
throw an error: ln: /usr/bin/python3: Operation not permitted

**Comment by mohantym** [comment]
Ok @zilaiyedaren !
Thanks for the update. 

Could you try creating the symbolic link in another file location instead of same python file location.
`sudo ln -s /usr/bin/python3.7 /usr/local/bin/python3. # please use exact python location through where is python command.
`

[Ref](https://stackoverflow.com/a/36734569/11530462)

Thank you!
