### ISSUE TITLE
Tutorial doesnt run in CoLabs

### ISSUE THREAD

**Issue by ejboettcher** [tensorflow/tensorflow#57202]
https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/images/transfer_learning.ipynb?force_kitty_mode=1&force_corgi_mode=1#scrollTo=TqOt6Sv7AsMi

This is the second Transfer learning tutorial that does not run in colabs.  I have not had an issue before.  Is there a version I need to set.  
This time the code fails at

```python
image_batch, label_batch = next(iter(train_dataset))
feature_batch = base_model(image_batch)
print(feature_batch.shape)

```

**Comment by ejboettcher** [comment]
I was able to get the tutorial to run if I forced the version to be 2.7.
```python
!pip install tensorflow==2.7
```

I would like to know how to run this tutorial using tensorflow 2.9.  Thank you.

**Comment by tilakrayal** [comment]
@ejboettcher,
I was able to execute the code without any issues on tensorflow v2.9 GPU enabled. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/d84b55677afa88284ac48097d8e60ec6/57202.ipynb).

![image](https://user-images.githubusercontent.com/81610181/185379477-cd1c9ec7-77f8-4653-aa6f-60e1ba539cec.png)


As a workaround for the time being, you may try running **!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2** and let us know if that fixes your issues. Thank you!

**Comment by ejboettcher** [comment]
Thank you @tilakrayal
That did fix the issue of running this in CoLab with TF 2.9 + GPU.
BUT
The tutorial does not run by itself without you injecting code if you are using the GPU as default.
You either have to switch to Non GPU, switch to TF 2.7 or change libcudnn8-dev to libcudnn8.

The purpose of the tutorials is that it should just run in colabs (Google has already built the vm for you) so that you can focus of the material and not trouble shooting the environment. It is really hard to trouble shoot the environment when you are not given a build eg requirements.txt file.

**Comment by tilakrayal** [comment]
@ejboettcher,
Ideally it should run but as there was an issue from google colab side, it was failing with the error which is not related to tensorflow. Please take a look at this [comment](https://github.com/googlecolab/colabtools/issues/2600#issuecomment-1061312120) from the **GoogleColab/ColabTools** team. 

As this is not from the TF related issue, I request please feel free to move this issue to closed status and raise the issue in **GoogleColab/ColabTools** repo for the assistance. Thank you!

**Comment by ejboettcher** [comment]
@tilakrayal 
I thought that you and colab were the same group.  My bad.

Take care, Issue open for me but closed for you.
