### ISSUE TITLE
Hexagon delegate for Qualcomm snapdragon chip APQ8098 (835)

### ISSUE THREAD

**Issue by davwang2019** [tensorflow/tensorflow#57209]
Our product uses Qualcomm snapdragon chip 835 (APQ8098) with android 8.1. We ran our machine learning model on hexagon DSP using hexagon delegate library from Google:

[v1.20.0.1](https://storage.cloud.google.com/download.tensorflow.org/tflite/hexagon_nn_skel_v1.20.0.1.run)

Recently, we updated our android from 8.1 to 10 and hexagon delegation stopped working (our model could only run on CPU now).

I have some question:

libhexagon_nn_skel_v66.so ==> for 'v66' based DSP
libhexagon_nn_skel_v65.so ==> for 'v65' based DSP
libhexagon_nn_skel.so ==> ??

Could you please confirm the right library to use for ADSP in APQ8098?
Our DSP version is v62 and the hexagon tools version are '8.0.08'.

Please advise how to fix this hexagon delegation issue. Thanks a lot.

Regards,

David

**Comment by sushreebarsa** [comment]
@davwang2019 
In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thank you!
