### ISSUE TITLE
Go API instrunctions no longer work

### ISSUE THREAD

**Issue by janpfeifer** [tensorflow/tensorflow#57214]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 22.04, in WSL2

### Current Behaviour?

```shell
The first instruction for the Go API is below, and the error one gets, since Go works differently since a while now:


$ go get -d github.com/tensorflow/tensorflow/tensorflow/go
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

Are there any updated instructions on how to install the go package ?
```


### Standalone code to reproduce the issue

```shell
$ go get -d github.com/tensorflow/tensorflow/tensorflow/go
```

### Relevant log output

```shell
$ go get -d github.com/tensorflow/tensorflow/tensorflow/go
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```
</details>

**Comment by mohantym** [comment]
Hi @janpfeifer !
Could you check the golang build instructions from [Tensorflow/build](https://github.com/tensorflow/build/tree/master/golang_install_guide) repo. 

Thank you!

**Comment by janpfeifer** [comment]
Thanks for the link @mohantym !

So it seems the Go API's [README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/README.md) is out of date.

**Comment by mohantym** [comment]
@janpfeifer !Thanks for the update. 
@gadagashwini ! Could you look at this issue.
Thank you!

**Comment by mihaimaruseac** [comment]
Sadly, there is no one left in TF with Go readability to maintain the bindings. Creating a SIG Go is currently pending on https://github.com/tensorflow/community/pull/407.

**Comment by janpfeifer** [comment]
hi @mohantym , I haven't had the opportunity to use it again so I haven't tried it.

But from what I was told the Go API is no longer maintained and a friend who is actually trying to use it had to patch the current API, and is planning to wrap their TensorFlow needs in a small C code, and create their own Go API for that.

It's quite sad actually, that TensorFlow is dropping the support for various languages outside python.

**Comment by SuryanarayanaY** [comment]
Hi @janpfeifer ,

Unfortunately, Tensorflow drops official support for Go API as per source [here.](https://github.com/tensorflow/build/tree/master/golang_install_guide#:~:text=Important%3A%20TensorFlow%20for%20Go%20is%20no%20longer%20supported%20by%20the%20TensorFlow%20team.%20The%20TensorFlow%20Go%20API%20is%20also%20not%20covered%20by%20the%20TensorFlow%20API%20stability%20guarantees.) Also TensorFlow Go API is also not covered by the TensorFlow [API stability guarantees](https://www.tensorflow.org/guide/versions). I believe there is little we can do here for now. 

However tensorflow referring to the mentioned [community build ](https://github.com/tensorflow/build/tree/master/golang_install_guide#community-build) or build from source using these steps attached [here](https://github.com/tensorflow/build/tree/master/golang_install_guide#build-from-source:~:text=Build%20from%20Source,go%20test%20./...).

I hope this can be of little help to the user you are referring to. Thanks!

**Comment by janpfeifer** [comment]
Thanks @SuryanarayanaY I found some alternative solution in Go, so no worries.

Btw it would be nice to updated the [README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/README.md) file in Go directory under TensorFlow with the contents of your message ? (That is the first page I landed when searching for TensorFlow for Go).

**Comment by SuryanarayanaY** [comment]
@wamuir ,

Could you please confirm that are you still working/maintaining the TF GoLang repo [here](https://github.com/tensorflow/build/tree/master/golang_install_guide). Whether the instructions mentioned there are up to date? Can we refer these instructions at [tensorflow/go/README.MD](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/README.md) ?

**Comment by wamuir** [comment]
@SuryanarayanaY Yes, I maintain the [TensorFlow Go API Installation Guide at tensorflow/build](https://github.com/tensorflow/build/tree/master/golang_install_guide) and update it at each release.

The instructions at [tensorflow/go/README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/README.md) are out of date and should not be used.  These instructions are based on use of the old GOPATH mode, which Go phased out and later removed for Go Modules.  For this reason (and a few others) the instructions simply will not work.  I do think/agree that they should be deleted or, as @janpfeifer states, replaced with direction to follow the [TensorFlow Go API installation guide at tensorflow/build](https://github.com/tensorflow/build/tree/master/golang_install_guide).

**Comment by SuryanarayanaY** [comment]
@wamuir ,
Thanks for confirmation. In that case shall we remove older instructions  at [tensorflow/go/README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/README.md) and provide reference link to reroute to the source that you are maintaining ? or Do you willing to raise PR for modifying the instructions at `tensorflow/go/README`? Could you please confirm ?
