### ISSUE TITLE
Can't pass random value (not tensor) in tensorflow function as a parameter.

### ISSUE THREAD

**Issue by urosjarc** [tensorflow/tensorflow#57212]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Windows 11

### Python version

3.9.0

### Current Behaviour?

```shell
I think I get unexpected behavior...

Stackoverflow source: https://stackoverflow.com/questions/73370248/passing-random-value-in-tensorflow-function-as-a-parameter/73372852#73372852

Tensorflow forum source: https://discuss.tensorflow.org/t/how-to-pass-random-value-not-tensor-in-tensorflow-function-as-a-parameter/11443

I have code in my augmentation tf.data pipeline...


    # BLURE
    filter_size = tf.random.uniform(shape=[], minval=0, maxval=5)
    image = tfa.image.mean_filter2d(image, filter_shape=filter_size)
```

But I'm constantly getting error...

```
 TypeError: The `filter_shape` argument must be a tuple of 2 integers. Received: Tensor("filter_shape:0", shape=(), dtype=int32)
```

I tried getting static value from random tensorflow like this...

```
    # BLURE
    filter_size = tf.get_static_value(tf.random.uniform(shape=[], minval=0, maxval=5))
    image = tfa.image.mean_filter2d(image, filter_shape=(filter_size, filter_size))
```

But I get error...

```
TypeError: The `filter_shape` argument must be a tuple of 2 integers. Received: None
```

I have tryed this also...

```
filter_size = tf.random.uniform(shape=[2], minval=0, maxval=5, dtype=tf.int32)
image = tfa.image.mean_filter2d(image, filter_shape=filter_size)
```
```
filter_size = tf.get_static_value(tf.random.uniform(shape=[], minval=0, maxval=5, dtype=tf.int32))
image = tfa.image.mean_filter2d(image, filter_shape=(filter_size, filter_size))
```

but I get...

```
TypeError: The `filter_shape` argument must be a tuple of 2 integers.
Received: Tensor("filter_shape:0", shape=(2,), dtype=int32)
```

And for the second…

```
ValueError: The `filter_shape` argument must be a tuple of 2 integers.
Received: (None, None) including element None of type <class 'NoneType'>
```
```


### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import tensorflow_addons as tfa
import numpy as np

def test(image):
	filter_size = tf.random.uniform(shape=[], minval=0, maxval=5, dtype=tf.int32)
	image = tfa.image.mean_filter2d(image, filter_shape=filter_size)
	return image

data = tf.data.Dataset.from_tensor_slices(tf.random.uniform([5, 100, 100, 3], 0, 255, dtype=np.int32))
data.map(test)
```

### Relevant log output

```shell
TypeError: The `filter_shape` argument must be a tuple of 2 integers. Received: Tensor("filter_shape:0", shape=(), dtype=int32)
```
</details>

**Comment by gadagashwini** [comment]
Hi @urosjarc, `tfa.image.mean_filter2d`, `filter_shape` takes  an Input : An integer or tuple/list of 2 integers.
In this case,you are using float value for `filetr_shape`.

```
filter_size = tf.random.uniform(shape=[], minval=0, maxval=5)
print(filter_size)
#image = tfa.image.mean_filter2d(img, filter_shape=filter_size)
```
**Output**
`tf.Tensor(0.6196606, shape=(), dtype=float32)`.

You must use tuple or integer value. Thank you!

**Comment by urosjarc** [comment]
Hy @gadagashwini, I want to run this peace of code (minimal example) that is part of my image augmentation pipeline...

```
import tensorflow as tf
import tensorflow_addons as tfa
import numpy as np

def test(image):
	filter_size = tf.random.uniform(shape=[], minval=0, maxval=5)
	image = tfa.image.mean_filter2d(image, filter_shape=filter_size)
	return image

data = tf.data.Dataset.from_tensor_slices(tf.random.uniform([5, 100, 100, 3], 0, 255, dtype=np.int32))
data.map(test)
```

If I run this I get error...

```
TypeError: The `filter_shape` argument must be a tuple of 2 integers. Received: Tensor("filter_shape:0", shape=(), dtype=float32)
```

How can I pass random value to `mean_filter2d` to blure each image at random value?

**Comment by cantonios** [comment]
This is a tf-addons issue.  `tfa.image.mean_filter2d` currently needs a constant filter size.

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
