### ISSUE TITLE
openCL delegate issue with models that output results from their intermediate nodes

### ISSUE THREAD

**Issue by Bahar-BM** [tensorflow/tensorflow#57211]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.1, nightly version

### Custom Code

No

### OS Platform and Distribution

Android

### Mobile device

tested on Snapdragon 888, 865, 855

### Current Behaviour?

```shell
The openCL delegate generates all zero outputs in models that output results from their intermediate nodes. This issue does not happen with other delegates like XNNPACK.
```

### Standalone code to reproduce the issue

```shell
We have implemented a small tool (with comprehensive documentation) to reproduce the mentioned issue. Here is the link to the repository:

https://github.com/Bahar-BM/openCL_test
```

### Relevant log output

_No response_</details>

**Comment by roserg** [comment]
Hi, this is known limitation of GPU delegates. I don't think that you can expect that it will be fixed in the nearest time. 
As a workaround you can add dummy operation like Add with zeroes or identity reshape to make intermediate tensor output not intermediate tensor. Sorry for this inconvenience.

**Comment by Bahar-BM** [comment]
Hi, thank you for your response. Yes, in the documentation of the tool in the attached link, we have pointed out the same workaround for this issue. We wanted to know if there is more systematic way to address this issue from your side but your explanation cleared everything up. Thank you
