### ISSUE TITLE
Can't build for iOS using CMake

### ISSUE THREAD

**Issue by kcoul** [tensorflow/tensorflow#57218]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.x

### Custom Code

No

### OS Platform and Distribution

Any

### Mobile device

iOS

### Current Behaviour?

```shell
During linking, symbols are missing due to signpost_profiler.mm not being compiled when building for iOS using CMake. Patch will be provided.
```

### Standalone code to reproduce the issue

```shell
Use an iOS toolchain such as https://github.com/leetal/ios-cmake to build for iOS. Will fail due to missing symbols since signpost_profiler.mm is not compiled.
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@kcoul Thank you for raising this ticket.
This issue will be closed once the PR is merged.
Thank you!
