### ISSUE TITLE
How to calculate number of MAC's in a custom tensorflow model

### ISSUE THREAD

**Issue by yugeshav** [tensorflow/tensorflow#57225]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.7

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.4

### CUDA/cuDNN version

11.2

### GPU model and memory

NVIDIA RTX A6000

### Current Behaviour?

```shell

Hello 

I have trained one custom tensorflow model using Conv2D's, Batch Normalization and GRU's, i want to know any tool is available in tensorflow for calculating no.of MAC's


Please suggest any tool / library for calculating no.of MACS/FLOPS required for one second for any custom tensorflow model
```

### Standalone code to reproduce the issue

```shell
Any tool or library to calculate no.of macs's required for 1 second?


Please suggest any tool / library for calculating no.of MACS/FLOPS required for one second for any custom tensorflow model
```

### Relevant log output

_No response_</details>

**Comment by gadagashwini** [comment]
Hi @yugeshav, You can use `tf.profiler` to calculate Flops. Follow the workaround mentioned on the similar issue [#32809](https://github.com/tensorflow/tensorflow/issues/32809) and [#941](https://discuss.tensorflow.org/t/calculate-flops-in-tensorflow-and-pytorch-are-not-equal/941/8). Thank you!
