### ISSUE TITLE
Don't imply top_k is nondifferentiable

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#5726]
`top_k` is in the [`Evaluation`](https://www.tensorflow.org/versions/master/api_docs/python/nn.html#evaluation) section of the documentation, which says

> The evaluation ops are useful for measuring the performance of a network. Since they are
> nondifferentiable, they are typically used at evaluation time.

This is confusing, since `top_k` is differentiable.  Pointed out by @nmduc: https://github.com/tensorflow/tensorflow/issues/288#issuecomment-261703608.

**Comment by kkarrancsu** [comment]
Hello, it looks like the latest docs (API r0.12) still has the old documentation that implies that `top_k` is non-differentiable.  See [docs](https://www.tensorflow.org/api_docs/python/nn/evaluation)

**Comment by girving** [comment]
They are fixed at HEAD: https://www.tensorflow.org/versions/master/api_docs/python/nn/evaluation.
