### ISSUE TITLE
Get "argv" error when trying to run mnist_softmax.py example

### ISSUE THREAD

**Issue by kohaugustine** [tensorflow/tensorflow#5728]
Hi,

I am trying to learn tensorflow from the tutorial on [MNIST](https://www.tensorflow.org/versions/r0.11/tutorials/mnist/beginners/index.html). I already have tensorflow installed on my system through conda and have been able to import tensorflow without any problems. Interaction with my GPU is fine when I ran code samples from research paper repositories.

To do so, I cloned the entire tensorflow repo into a local directory, and went into the tutorials/mnist directory. When I try to run the mnist_softmax.py example, I run into the error I have posted below.

`$ python mnist_softmax.py `
`I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally`
`I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally`
`I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally`
`I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally`
`I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally`
`Traceback (most recent call last):`
`  File "mnist_softmax.py", line 78, in <module>`
`    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)`
`TypeError: run() got an unexpected keyword argument 'argv'`

Searching stackoverflow, I haven't found much helpful posts on this subject. The two posts I found were http://stackoverflow.com/questions/40513466/tensorflow-retrain-py-app-run-got-unexpected-keyword-argument-argv and http://stackoverflow.com/questions/40357548/inception-v3-guide-on-tensorflow-broken-for-c-and-python, but they are not really solutions to this problem.

So far I can't think of any reason why this would not work, except that maybe I need to compiler and build Tensorflow from source instead of just installing the binaries via conda.

If anyone could help with this, it would be really appreciated.

Thank you.

**Comment by vrv** [comment]
Try checking out the version of mnist_softmax.py at the branch of the version you have installed.  E.g., if you have r0.11 installed, check out the version of mnist_softmax.py in the r0.11 branch of git.  That should hopefully solve your problems.  Please ping this thread if you feel there's something more to this.

**Comment by kohaugustine** [comment]
Thank you very much @vrv , this solves it!
