### ISSUE TITLE
Hope intermediate state in dynamic_rnn

### ISSUE THREAD

**Issue by Sraw** [tensorflow/tensorflow#5731]
To implement a attention machine, I need the intermediate state to calculate the attention, but dynamic_rnn doesn't return the intermediate states but only final state.
Hope the dynamic_rnn could return intermediate states so that we can implement a attention machine with dynamic network.

**Comment by ebrevdo** [comment]
You can write a variant of the LSTMCell that returns both state tensors as part of the output, if you need both c and h state for each time step.  If you just need the h state, that's the output of reach time step.

**Comment by Sraw** [comment]
@ebrevdo Thanks for reply. Really helpful.

**Comment by WolfNiu** [comment]
@ebrevdo  May I ask a question? For each time step of LSTM there is a memory cell value **_c_**, a hidden state **_h_**, and an output **_y_**. So what you were suggesting is that the **_outputs_** returned by dynamic RNN contain **_h_** rather than _**y**_ for each step? Would that also mean the returned **_output_states_** is actually **_outputs_**[-1]? Thank you.

**Comment by Sraw** [comment]
@WolfNiu I can answer your question.
http://colah.github.io/posts/2015-08-Understanding-LSTMs/
if you look into the structure of LSTM, you will see that the hidden state **h** and the output **y** is the same, they all come from the same line.
So actually, there are only two values at each step, h or y and c.

**Comment by evanthebouncy** [comment]
@ebrevdo 

I tried your suggestion but I ran into such trouble doing it, can you take a look at my stackoverflow post?

https://stackoverflow.com/questions/45528146/tensorflow-create-a-custom-sub-class-of-lstm-cell-with-a-dfferent-call-functi

Thanks

**Comment by dsalaj** [comment]
@Sraw Were you able to accomplish your goal? I am also in need of recording all the LSTM cell gates. However I change the output of the cell call it breaks too much stuff. Do you have an example of what you did?

**Comment by maziarmf** [comment]
@Sraw  am I able to assign specific values for lstm gates? for instance always 1 for input and....
