### ISSUE TITLE
einsum: "ij,ji->" rasing error.

### ISSUE THREAD

**Issue by weinbe58** [tensorflow/tensorflow#5735]
Hi I'm running Linux-64 bit os and I'm getting the following error after running:

```
import tensorflow as tf
I = tf.constant([[1,0,0],[0,1,0],[0,0,1]])
II_tr = tf.einsum('ij,ji->',I,I)
with tf.Session() as sess:
	res = sess.run(II_tr)
	print res
```
`AssertionError: Indices have incorrect format: ij,ji->` Clearly the result here should be 3.

**Comment by drpngx** [comment]
It works in the current version. What version are you using?

**Comment by weinbe58** [comment]
I'm using version 0.11.0

I installed it via pip and https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl

**Comment by drpngx** [comment]
`tf.einsum` is relatively recent and was not fully baked in `0.11`. Please try a newer version.

**Comment by weinbe58** [comment]
Ok I have installed v0.11.0rc2-py27_0 using conda and its still giving me the same error.

**Comment by drpngx** [comment]
`0.11rc2` is earlier than `0.11`, you need `0.12`.

**Comment by weinbe58** [comment]
Is 0.12 released yet? I can't get it via anaconda. If not I can work around it. 

Thanks

**Comment by drpngx** [comment]
My bad, not released yet. You could grab `tensorflow/python/ops/special_math_ops.py` from [HEAD](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/special_math_ops.py#L96).
