### ISSUE TITLE
tf.sub error message for bad types is confusing

### ISSUE THREAD

**Issue by shirriff** [tensorflow/tensorflow#5738]
tf.sub() displays a strange error message if the types don't match:
TypeError: DataType uint8 for attr 'T' not in list of allowed values: float16, float32, float64, int32, int64, complex64, complex128

It's unclear what attr 'T' is.

Expected behavior:
for tf.add(), tf.mul(), tf.div(), the message makes sense:
TypeError: Input 'y' of 'Add' Op has type int64 that does not match type uint8 of argument 'x'.

It seems to me that tf.sub() should print a similar message.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
none

### Environment info
Operating System:
Darwin Kens-MacBook-Pro.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64

Installed version of CUDA and cuDNN: none

1. A link to the pip package you installed:
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.10.0-py2-none-any.whl"

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.11.0

### If possible, provide a minimal reproducible example 

import tensorflow as tf
x0 = tf.constant(1, dtype=tf.uint8)
x1 = tf.constant(255, dtype=tf.int64)
x2 = tf.sub(x0, x1)

**Comment by prb12** [comment]
The error message isn't saying that the types don't match.  It is saying that the Sub operator doesn't accept uint8 for either operand.

Add supports these types: https://github.com/tensorflow/tensorflow/blob/754048a0453a04a761e112ae5d99c149eb9910dd/tensorflow/core/ops/math_ops.cc#L518
Sub supports these:
https://github.com/tensorflow/tensorflow/blob/754048a0453a04a761e112ae5d99c149eb9910dd/tensorflow/core/ops/math_ops.cc#L529

I believe that this is the intended behavior (though I don't know exactly why Sub doesn't support this type  @josh11b Do you know why this is the case?)

**Comment by josh11b** [comment]
@martinwicke actually added the support for uint8 to Add/Mul/Div (in 109027800 "Add convert_image op to convert between types for images (similar to OpenCV's cvtScale).").  Not sure why he didn't also do it for Sub.
