### ISSUE TITLE
TensorFlow building issue

### ISSUE THREAD

**Issue by trungnhat-incoder** [tensorflow/tensorflow#57387]
Description of the bug:
I'm trying to build TensorFlow with TensorRT support on Windows 11.
Devices specs:
Windows 11 Pro
GPU: NVIDIA Quadro P1000
RAM: 16GB
CUDA SDK Version: 11.2
cuDNN version: 8.1 (for cuda 11.2)
Build tool: MSVC build tool 2019 (latest version from VS Installer)
TensorRT version: 8.2
I've gotten no issue when configure the build:
d:\Nghich\tensorflow>python ./configure.py
You have bazel 5.0.0 installed.
Please specify the location of python. [Default is D:\Python39\python.exe]:

Found possible Python library paths:
D:\Python39\lib\site-packages
Please input the desired Python library path to use. Default is [D:\Python39\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: y
TensorRT support will be enabled for TensorFlow.

WARNING: TensorRT support on Windows is experimental

Found CUDA 11.2 in:
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/lib/x64
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/include
Found cuDNN 8 in:
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/lib/x64
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/include
Found TensorRT 8 in:
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/lib
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/include

Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus. Each capability can be specified as "x.y" or "compute_xy" to include both virtual and binary GPU code, or as "sm_xy" to only include the binary code.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]: 6.1

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:

Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]: y
Eigen strong inline overridden.

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
--config=mkl # Build with MKL support.
--config=mkl_aarch64 # Build with oneDNN and Compute Library for the Arm Architecture (ACL).
--config=monolithic # Config for mostly static monolithic build.
--config=numa # Build with NUMA support.
--config=dynamic_kernels # (Experimental) Build kernels into separate shared objects.
--config=v1 # Build with TensorFlow 1 API instead of TF 2 API.
Preconfigured Bazel build configs to DISABLE default on features:
--config=nogcp # Disable GCP support.
--config=nonccl # Disable NVIDIA NCCL support.

I'm getting stuck with the following bugs:
d:\Nghich\tensorflow>bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true --local_ram_resources=8192 --copt=-nvcc_options=disable-warnings //tensorflow/tools/pip_package:build_pip_package
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Reading rc options for 'build' from d:\nghich\tensorflow.bazelrc:
Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
'build' options: --python_path=D:/Python39/python.exe
INFO: Reading rc options for 'build' from d:\nghich\tensorflow.bazelrc:
'build' options: --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false
INFO: Reading rc options for 'build' from d:\nghich\tensorflow.tf_configure.bazelrc:
'build' options: --action_env PYTHON_BIN_PATH=D:/Python39/python.exe --action_env PYTHON_LIB_PATH=D:/Python39/lib/site-packages --python_path=D:/Python39/python.exe --config=tensorrt --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2 --action_env TF_CUDA_COMPUTE_CAPABILITIES=6.1 --config=cuda --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --define=override_eigen_strong_inline=true
INFO: Reading rc options for 'build' from d:\nghich\tensorflow.bazelrc:
'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file d:\nghich\tensorflow.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file d:\nghich\tensorflow.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:tensorrt in file d:\nghich\tensorflow.bazelrc: --repo_env TF_NEED_TENSORRT=1
INFO: Found applicable config definition build:cuda in file d:\nghich\tensorflow.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:opt in file d:\nghich\tensorflow.tf_configure.bazelrc: --copt=/arch:AVX --host_copt=/arch:AVX
INFO: Found applicable config definition build:cuda in file d:\nghich\tensorflow.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:windows in file d:\nghich\tensorflow.bazelrc: --copt=/W0 --host_copt=/W0 --copt=/Zc:__cplusplus --host_copt=/Zc:__cplusplus --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --features=compiler_param_file --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --cxxopt=/std:c++17 --host_cxxopt=/std:c++17 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --features=compiler_param_file --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file d:\nghich\tensorflow.bazelrc: --define framework_shared_object=false --experimental_link_static_libraries_once=false
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/d5a6f80380113295caf442415f506e49cd015145.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/809855b56f06dd7182685f88fbbc64111df9339a.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: D:/nghich/tensorflow/tensorflow/BUILD:1035:21: //tensorflow:libtensorflow_framework.so.2.11.0: no such attribute 'shared_lib_name' in 'cc_shared_library' rule
ERROR: D:/nghich/tensorflow/tensorflow/BUILD:1035:21: //tensorflow:libtensorflow_framework.so.2.11.0: no such attribute 'win_def_file' in 'cc_shared_library' rule
ERROR: D:/nghich/tensorflow/tensorflow/BUILD:1035:21: //tensorflow:libtensorflow_framework.2.11.0.dylib: no such attribute 'shared_lib_name' in 'cc_shared_library' rule
ERROR: D:/nghich/tensorflow/tensorflow/BUILD:1035:21: //tensorflow:libtensorflow_framework.2.11.0.dylib: no such attribute 'win_def_file' in 'cc_shared_library' rule
ERROR: D:/nghich/tensorflow/tensorflow/BUILD:1035:21: //tensorflow:tensorflow_framework.dll: no such attribute 'shared_lib_name' in 'cc_shared_library' rule
ERROR: D:/nghich/tensorflow/tensorflow/BUILD:1035:21: //tensorflow:tensorflow_framework.dll: no such attribute 'win_def_file' in 'cc_shared_library' rule
ERROR: D:/nghich/tensorflow/tensorflow/BUILD:1157:21: //tensorflow:libtensorflow_cc.so.2.11.0: no such attribute 'shared_lib_name' in 'cc_shared_library' rule
ERROR: D:/nghich/tensorflow/tensorflow/BUILD:1157:21: //tensorflow:libtensorflow_cc.so.2.11.0: no such attribute 'win_def_file' in 'cc_shared_library' rule
ERROR: D:/nghich/tensorflow/tensorflow/BUILD:1157:21: //tensorflow:libtensorflow_cc.2.11.0.dylib: no such attribute 'shared_lib_name' in 'cc_shared_library' rule
ERROR: D:/nghich/tensorflow/tensorflow/BUILD:1157:21: //tensorflow:libtensorflow_cc.2.11.0.dylib: no such attribute 'win_def_file' in 'cc_shared_library' rule
ERROR: D:/nghich/tensorflow/tensorflow/BUILD:1157:21: //tensorflow:tensorflow_cc.dll: no such attribute 'shared_lib_name' in 'cc_shared_library' rule
ERROR: D:/nghich/tensorflow/tensorflow/BUILD:1157:21: //tensorflow:tensorflow_cc.dll: no such attribute 'win_def_file' in 'cc_shared_library' rule
ERROR: D:/nghich/tensorflow/tensorflow/tools/pip_package/BUILD:278:10: errors encountered resolving select() keys for //tensorflow/tools/pip_package:build_pip_package
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted:
INFO: Elapsed time: 187.076s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (10 packages loaded, 12 targets configured)
I've followed the link https://www.tensorflow.org/install/source_windows to build and used exactly the same version of equivalent components.

**Comment by tilakrayal** [comment]
@trungnhat-incoder,
 Could you  please try the below commands **`bazel clean --expunge`** followed by bazel sync.

`bazel build --verbose_failures --config=opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.2 --copt=-DINTEL_MKL_ML_ONLY --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package`

Also please let us know the source from where you are trying to build the tensorflow. Thank you!

**Comment by trungnhat-incoder** [comment]
> @trungnhat-incoder, Could you please try the below commands **`bazel clean --expunge`** followed by bazel sync.
> 
> `bazel build --verbose_failures --config=opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.2 --copt=-DINTEL_MKL_ML_ONLY --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" //tensorflow/tools/pip_package:build_pip_package`
> 
> Also please let us know the source from where you are trying to build the tensorflow. Thank you!

Thanks for helping! I cloned from the link https://github.com/tensorflow/tensorflow.git to get the source.
After using your command, I still stuck with that error:
![image](https://user-images.githubusercontent.com/67949446/186371564-beb88fce-6dc6-40e1-9d27-3c2d556b9d0c.png)

**Comment by gadagashwini** [comment]
Hi @trungnhat-incoder, 
`ERROR: D:/nghich/tensorflow/tensorflow/BUILD:1035:21: //tensorflow:libtensorflow_framework.so.2.11.0: no such attribute 'shared_lib_name' in 'cc_shared_library' rule`

Tensorflow master branch has `cc_shared_library rule`. Please take a look at this reference [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorflow.bzl#L2971). 
Could you build Tf master branch and check. Thank you!

**Comment by trungnhat-incoder** [comment]
> Hi @trungnhat-incoder, `ERROR: D:/nghich/tensorflow/tensorflow/BUILD:1035:21: //tensorflow:libtensorflow_framework.so.2.11.0: no such attribute 'shared_lib_name' in 'cc_shared_library' rule`
> 
> Tensorflow master branch has `cc_shared_library rule`. Please take a look at this reference [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorflow.bzl#L2971). Could you build Tf master branch and check. Thank you!

OK, I'll give it a try? I think I know what's happening. Thanks to give me a hint!

**Comment by trungnhat-incoder** [comment]
Problem solved! I've downloaded the release version of TF source and successfully build it.
