### ISSUE TITLE
Tensorflow horovod distributed on a100 mig error

### ISSUE THREAD

**Issue by wukong1992** [tensorflow/tensorflow#57385]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

1.15.4

### Custom Code

Yes

### Current Behaviour?

```shell
Error log: 
```Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA
Fatal Python error: Aborted


### Standalone code to reproduce the issue

```shell
source code:https://github.com/horovod/horovod/blob/master/examples/tensorflow/tensorflow_mnist.py

platform:
hardware: a100, enable mig
docker
env:
NVIDIA_VISIBLE_DEVICES=0:0,0:1

start script:
mpirun -allow-run-as-root -np 2 -H localhost:2 -bind-to none -map-by slot -x NCCL_DEBUG=INFO -x LD_LIBRARY_PATH -x PATH python test.py
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
Hi @wukong1992,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.9.0 and check if you are facing the same issue. Thank you!

**Comment by wukong1992** [comment]
> 

I test with version 2.8 and the error still exists.

**Comment by wukong1992** [comment]
@tilakrayal

**Comment by tilakrayal** [comment]
@wukong1992,
I was facing a different error while trying to execute the mentioned code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/b3fab0a0007caa49cdf96594c0b44dc0/untitled531.ipynb) and share the required dependencies or the colab gist with the error reported. Thank you!

**Comment by wukong1992** [comment]
> ```shell
> https://github.com/horovod/horovod/blob/master/examples/
> ```

Just use [this](https://colab.research.google.com/gist/tilakrayal/b3fab0a0007caa49cdf96594c0b44dc0/untitled531.ipynb#scrollTo=cjxjYPgFPEUY) code, but you have configure gpu resource . The bug only exist in multi mig gpu configuration.

**Comment by tilakrayal** [comment]
@wukong1992,
We can see multiple code files in the repo. Could you please confirm the reproducible code file or the colab gist. Also the above gist consists of the code of tensorflow 1.x version. 
Please provide the code which supports the 2.x version and take a look at this doc [link](https://www.tensorflow.org/guide/migrate) for the apis which migrated from TensorFlow 1.x to TensorFlow 2. Thank you!

**Comment by wukong1992** [comment]
Figure out! Mig does not  support one process multi mig devices: [https://forums.developer.nvidia.com/t/cudagetdevicecount-always-return-1-on-multiple-mig-cis-env/208560](here) .

**Comment by jszaday** [comment]
> Figure out! Mig does not support one process multi mig devices: [https://forums.developer.nvidia.com/t/cudagetdevicecount-always-return-1-on-multiple-mig-cis-env/208560](here) .

Closing this issue since, from this comment, it seems like you have solved the problem 😄 If this interpretation is incorrect, please let us know how we can help from here (and provide the TFv2 colab @tilakrayal requested). Thank you!

**Comment by jszaday** [comment]
> Figure out! Mig does not support one process multi mig devices: [https://forums.developer.nvidia.com/t/cudagetdevicecount-always-return-1-on-multiple-mig-cis-env/208560](here) .

Closing this issue since, from this comment, it seems like you have solved the problem 😄 If this interpretation is incorrect, please let us know how we can help from here (and provide the TFv2 colab @tilakrayal requested). Thank you!
