### ISSUE TITLE
Error in Kronecker product (use of ndim vs. tf.rank)

### ISSUE THREAD

**Issue by dixr** [tensorflow/tensorflow#57390]
When using `tf.experimental.numpy.kron` in graph mode, one gets `AttributeError: 'Tensor' object has no attribute 'ndim'`.

The problem is the use of `a.ndim` instead of `tf.rank(a)` for a and b.

Example:
```python
@tf.function
def kron_error(a,b):
  return tf.experimental.numpy.kron(a,b)
a = tf.constant([[1.,2],[3,4]], dtype=tf.float64)
b = tf.constant([[1.,2.,3.,],[-1,4,5]], dtype=tf.float64)
kron_error(a, b)
```

One can fix it by using `tf.rank`. See this colab:
https://colab.research.google.com/drive/1quS7xqOsCKgak7pobYoG24v05nuEPvWn?usp=sharing

Code reference:
https://github.com/tensorflow/tensorflow/blob/8a20d54a3c1bfa38c03ea99a2ad3c1b0a45dfa95/tensorflow/python/ops/numpy_ops/np_math_ops.py#L383-L411

**Comment by sushreebarsa** [comment]
@dixr 
In order to expedite the trouble-shooting process here, could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) and provide more details.
Thank you!

**Comment by dixr** [comment]
@sushreebarsa 
What additional details do you need, specifically? I already did provide 

- Standalone code to reproduce the issue
- A colab that interactively shows how to reproduce the issue.
- A reference to the exact lines in the source (master) that needs fixing

I do not think that any of the many GCC / TF / compiler version / platform / ... information in the template would help you? The problem should be clear. I think it's just a typo that ndim is used instead of tf.rank

**Comment by sushreebarsa** [comment]
@dixr Thank you for the update!
Please feel free to raise a PR to fix the issue. Thank you!

**Comment by dixr** [comment]
@sushreebarsa I did, #57506

**Comment by sushreebarsa** [comment]
@dixr Thank you for the update!
This issue will be closed once the PR is merged.
Thank you!

**Comment by wangpengmit** [comment]
You need to call `tf.experimental.numpy.experimental_enable_numpy_behavior`, which will add `ndim` to `Tensor`. Please see [the TF NumPy guide](https://www.tensorflow.org/guide/tf_numpy).

**Comment by dixr** [comment]
@wangpengmit Can you justify why this is really the best solution? Why not change the use of `.ndim` in `kron`?

I mean, none of all the other functions in `np_math_ops.py` require `.ndim`, they all call some alternative rank functions that don't produce this error.

If for some reason `kron` really has to use `.ndim` instead of an alternative, then you should make the error message more helpful.

**Comment by wangpengmit** [comment]
Please see comment in #57506.

**Comment by sushreebarsa** [comment]
@dixr Could you please refer to the comment above?
Thank you!

**Comment by dixr** [comment]
I did, I agree that you should use `.shape.rank` instead of `.ndim`.
