### ISSUE TITLE
when will tensorflow support FP8?

### ISSUE THREAD

**Issue by laoshaw** [tensorflow/tensorflow#57395]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

tf2.9

### Custom Code

No

### OS Platform and Distribution

Linux ubuntu 20.04

### Current Behaviour?

```shell
Pytorch added FP8 support, will TF add FP8 support sometime for both E4M3 and E5M2?
```

### Standalone code to reproduce the issue

```shell
No source code, just a feature request question
```

### Relevant log output

_No response_</details>

**Comment by sachinprasadhs** [comment]
@laoshaw , Could you please elaborate more about your feature request. Thanks!

**Comment by pjannaty** [comment]
We have already integrated FP8 GEMM into the XLA backend. Please see a tutorial on [low-level API](https://github.com/NVIDIA/atex/blob/experimental-xla-fp8-layers/experimental/xla-fp8-layers/fp8-tutorial.md) and the original [RFC](https://github.com/openxla/xla/discussions/22).

We have also developed FP8 layers for JAX and TF that we are currently testing.
If interested see [OpenXLA talk](https://www.youtube.com/watch?v=5i7xrBUCD38&list=PLlFotmaRrOzsznwKi-28bOOsANARrSxKw&index=3&t=1763s) and [slides](https://docs.google.com/presentation/d/12A3xs-rG18zvD1nNsuZOdAlld_qjA_Pn9yx4j6elji4/edit?resourcekey=0-w9--wU8abVZ1n6CPUjkK-g#slide=id.g21d929f269c_2_5153) on FP8.
