### ISSUE TITLE
Problem at Tensorflow/Model/Compression

### ISSUE THREAD

**Issue by Viscoo** [tensorflow/tensorflow#5740]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

https://github.com/tensorflow/tensorflow/issues/4772
tensorflow/models/compression does not work,but his problem was not same to me.
### Environment info
Operating System:

Ubuntu 14.04
tensorflow cpu-only version:0.8.0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/common_shapes.py", line 155, in get2d_conv_output_size
    % (row_stride, col_stride, filter_height, filter_width))
ValueError: ('stride must be less than or equal to filter size', 'stride: [2x2] filter: [1x1]')

### What other attempted solutions have you tried?
I have open the common_shapes.py,but don't know how to repair.

**Comment by prb12** [comment]
Please can you report this issue in the tensorflow/models repository, clearly labelling the issue '[Compression]' and providing sufficient information to reproduce (e.g. at least OS version, TensorFlow version and all necessary command lines)
