### ISSUE TITLE
Unable to free memory allocated by OpKernelContext

### ISSUE THREAD

**Issue by shreer1998** [tensorflow/tensorflow#57423]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

2.9

### Custom Code

Yes

### Current Behaviour?

```shell
The OpKernelContext used in custom op's compute method doesn't have an option to free the temporary allocated by it. 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/op_kernel.h doesn't have an API to free the memory allocated by "allocate_temp" method.

Do we have any solution to free the memory allocated using allocate_temp?
```

### Standalone code to reproduce the issue

```shell
Its a request
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@shreer1998,
Could you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thank you!

**Comment by shreer1998** [comment]
Sorry it isn't required
