### ISSUE TITLE
Linker error on Windows with shared build updating to 2.9.1

### ISSUE THREAD

**Issue by prince-chrismc** [tensorflow/tensorflow#57461]
👋 I am [Conan](https://github.com/conan-io) contributor and we've received a PR https://github.com/conan-io/conan-center-index/pull/11477 and there was new patch I'd like to contribute back.

The Windows shared build failed using the CMake build system. There's intentionally duplicate symbols with weak attribute, however I suspect this is not support on windows, so in the DLL both are added.

https://github.com/tensorflow/tensorflow/blob/4bfe5240068d57cb586f2c282c1ce19198e3483d/tensorflow/lite/simple_memory_arena.cc#L190-L191

https://github.com/tensorflow/tensorflow/blob/4bfe5240068d57cb586f2c282c1ce19198e3483d/tensorflow/lite/simple_memory_arena_debug_dump.cc#L132-L133

Our community opted to remove the extra file https://github.com/conan-io/conan-center-index/blob/master/recipes/tensorflow-lite/all/patches/remove_simple_memory_arena_debug_dump.patch

I would love to open a PR if this is acceptable fix ❤️

**Comment by talyz** [comment]
The cause was indeed that MSVC doesn't support `__attribute__((weak))` or similar hints. Never found out why it's only a problem when building a shared library, though.

**Comment by mohantym** [comment]
Hi @prince-chrismc !
Feel free to raise a PR. 
Thank you!

**Comment by talyz** [comment]
Submitted the patch in #57477.

**Comment by mohantym** [comment]
Thank you @talyz for the above PR. This issue will be closed once PR is merged.

**Comment by prince-chrismc** [comment]
Thanks! For keeping it moving forward!

**Comment by pjpratik** [comment]
Hi @prince-chrismc 

The PR #57477 fixes the shared build library on windows with the following lines
https://github.com/tensorflow/tensorflow/blob/7f496c16215ffd4295b129a1320448eec2988485/tensorflow/lite/CMakeLists.txt#L232-L234

Could you please check and close the issue if it is resolved?

Thanks.
