### ISSUE TITLE
incorrect convert PRELU from pb to tflite when input H, W shape set to None in pb

### ISSUE THREAD

**Issue by mayujie** [tensorflow/tensorflow#57467]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): `Ubuntu 20.04.4 LTS`
- TensorFlow installation (pip package or built from source): `pip install tensorflow==2.9.1`
- TensorFlow library (version, if pip package or github SHA, if built from source): `tensorflow==2.9.1`

### 2. Code

PRELU definition: 
```
pos = tf.nn.relu(inputs)
alphas = alphas_constraint(weights=alphas) if alphas_constraint is not None else alphas
neg = -alphas * tf.nn.relu(-inputs)
return pos + neg
```

### 3. Failure after conversion

1. There is no problem when converting the model to PB with set None in H, W such as [1, None, None, 3].
2. But when converting such pb to tflite there will be issue as follow:

- when use `converter.experimental_new_converter = False` gives error `ValueError: None is only supported in the 1st dimension. Tensor 'input_tensor' has invalid shape '[1, None, None, 3]'.`
- when use `converter.experimental_new_converter = True`, the conversion is successful, but the PRELU didn't fusion with conv properly in tflite. 
![image](https://user-images.githubusercontent.com/19303874/186912937-22a74194-f638-49b4-85e8-046312139e02.png)

**PS:**
1. If I convert the model to pb by setting up a fixed input shape (H, W not `None`). Then convert pb to tflite with `converter.experimental_new_converter = False`, the PRELU fusion with conv properly.
![image](https://user-images.githubusercontent.com/19303874/186913508-8a981292-847e-472e-9e99-5a50d711b772.png)

2. If I convert the model to pb by setting up a fixed input shape, Then convert pb to tflite with `converter.experimental_new_converter = True`, the PRELU fusion with conv not properly. 
![image](https://user-images.githubusercontent.com/19303874/186914192-ce4b8a3b-026e-458d-b959-ebd776256576.png)

### 4. Question
Is it possible to convert **pb** (which set up input shape H, W as None) to **tflite** with the PRELU op correctly fuse with CONV?

**Comment by mohantym** [comment]
Hi @mayujie !
Dynamics shapes are not supported yet. Please proceed with a fixed input shape as you mentioned.
Thank you!

**Comment by mayujie** [comment]
so generate the tflite with fixed input shape, later using `model.resize_tensor_input` and `model.allocate_tensors()` during deployment for different input shapes will be the current solution, right?
Will this solution take some overhead of latency?

**Comment by mohantym** [comment]
@mayujie !

You can also use Firebase[ ML kit binding](https://firebase.google.com/docs/ml-kit/android/use-custom-models) / [ML - model binding](https://towardsdatascience.com/machine-learning-with-android-11-whats-new-e8c829e9452) from TF Hub to resize input and output tensors .
Yes , It affects latency ( faster inference compared to dynamic shape). 

Could you move this to closed status if you consider this issue as resolved.

Thank you!
