### ISSUE TITLE
Tensorflow API for Carbon?

### ISSUE THREAD

**Issue by maifeeulasad** [tensorflow/tensorflow#57466]

**Comment by tilakrayal** [comment]
@maifeeulasad,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue. Thank you!

**Comment by maifeeulasad** [comment]
@tilakrayal, I understand it. But I couldn't fit it any of these:
 - Tensorflow Issue Template
 - TensorFlow Lite Converter Issue
 - TensorFlow Lite in Play Services issue
 - TensorFlow Lite Op Request
 - Report a security vulnerability

That's why I created an empty issue.

**Comment by tilakrayal** [comment]
@maifeeulasad,
Could you please try to select [Tensorflow Issue Template](https://github.com/tensorflow/tensorflow/issues/new/choose) and provide the required details. So that it will be easy for us to analyse the issue. Thank you!

**Comment by maifeeulasad** [comment]
@tilakrayal Can you suggest to me a template from the list, as I'm not so sure.

**Comment by sachinprasadhs** [comment]
@maifeeulasad , Could you please elaborate your requirement to understand the problem better. Thanks!
