### ISSUE TITLE
[tf.data.dataset] .take after .shuffle doesn't work as expected

### ISSUE THREAD

**Issue by AustinCStone** [tensorflow/tensorflow#57470]
### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8.0

### Custom Code

No

### OS Platform and Distribution

OSX 12.5.1 and Linux Ubuntu

### Python version

3.9.12

### Current Behaviour?

Performing .take(1).repeat() after .shuffle(N) returns N different elements.

Reproduction instructions:

```
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4])
dataset = dataset.shuffle(4)
dataset = dataset.take(1)
dataset = dataset.repeat()
dataset = dataset.take(10)
for x in dataset:
  print(x)
```
This will print 10 different, random integers in the range 1 - 4.

Expected behavior:

I would have expected this to print only a single unique integer. It appears the early .shuffle interferes with the later .take, which is very counterintuitive.

See this colab:

[Link to colab](https://colab.research.google.com/drive/1UYu3TyzMd2nPs19YyNrViFQZxfSyw8WR?usp=sharing)

### Standalone code to reproduce the issue

[Link to colab](https://colab.research.google.com/drive/1UYu3TyzMd2nPs19YyNrViFQZxfSyw8WR?usp=sharing)

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow [v2.8](https://colab.research.google.com/gist/tilakrayal/a9b7b30e083d13688d65086cd9df7076/2-8.ipynb), [v2.9](https://colab.research.google.com/gist/tilakrayal/18a86196fbc83e3d9f18ea7d72209818/tfdatabug.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/e9b6fd61357445369c776995a61b0106/2-11.ipynb). Kindly find the gist of it here.

**Comment by sachinprasadhs** [comment]
Usually .shuffle() will create a new dataset taht will start by filling up a buffer with the first items of the source dataset.
Then, when it is requested it will pull one out randomly from the buffer and replace it with a fresh one from the source dataset.
Usually, if you mention the buffer size, you can limit the items to be picked from that buffer size.

In the below scenario, when you mention the buffer size as 1, it always picks up the first element from the source dataset and then gets used in the followed up code.

```
dataset = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4])
dataset = dataset.shuffle(1)
dataset = dataset.take(1)
dataset = dataset.repeat()
dataset = dataset.take(4)

for x in dataset:
  print(x)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
```
