### ISSUE TITLE
Can't build Video Classification android app

### ISSUE THREAD

**Issue by ArtanBerisha1** [tensorflow/tensorflow#57479]
I cloned tensorflow/examples repo, 
I am opening video classification app: github.com/tensorflow/examples/tree/master/lite/examples/video_classification/android, but I got the following error:

```
Failed to apply plugin 'com.android.internal.version-check'.
Minimum supported Gradle version is 7.0.2. Current version is 6.8. If using the gradle wrapper, try to change the value in "\gradle\wrapper\gradle-wrapper.properties" to
distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip
```

I solved this by creating gradle-wrapper.properties file, because that file was missing. I am not sure if I only had this issue, or should I create a PR for this ?

**Comment by mohantym** [comment]
Hi @ArtanBerisha1 !
It is asking to upgrade to 7.2.2 while running in Android studio Chip munk. Once upgraded and gradle is synced , It is able to run (but results are not accurate).  Thanks for reporting it and Feel free to raise a PR from your end.

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by sachinprasadhs** [comment]
I could see the gradle version mentioned as 7.0.4 in the file here https://github.com/tensorflow/examples/blob/master/lite/examples/video_classification/android/build.gradle. Are you referring to the same file as me. Thanks!
