### ISSUE TITLE
Bazel build on Windows fails with "Can't do inplace edit without backup." error.

### ISSUE THREAD

**Issue by snarb** [tensorflow/tensorflow#5748]
### Environment info
Operating System: Windows 10

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):  No

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)  - c7edafccc793bf87e29aaec90db64471a7a4bb02
2. The output of `bazel version`: 0.4.0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

Bazel build on Windows fails with "Can't do inplace edit without backup." error.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

$ /d/tf/tensorflow/tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh
+ set -e
++ dirname /d/tf/tensorflow/tensorflow/tools/ci_build/windows/cpu/pip/build_tf_windows.sh
+ script_dir=/d/tf/tensorflow/tensorflow/tools/ci_build/windows/cpu/pip
+ cd /d/tf/tensorflow/
+ export TMPDIR=C:/tmp
+ TMPDIR=C:/tmp
+ export BAZEL_SH=C:/tools/msys64/usr/bin/bash
+ BAZEL_SH=C:/tools/msys64/usr/bin/bash
+ export PYTHON_BIN_PATH=I:/Anaconda3/python
+ PYTHON_BIN_PATH=I:/Anaconda3/python
+ export BAZEL_PYTHON=I:/Anaconda3/python
+ BAZEL_PYTHON=I:/Anaconda3/python
+ export 'BAZEL_VS=E:/Program Files (x86)/Microsoft Visual Studio 14.0'
+ BAZEL_VS='E:/Program Files (x86)/Microsoft Visual Studio 14.0'
+ export 'PATH=/I/Anaconda3:/c/Perl64/site/bin:/c/Perl64/bin:/c/Python27:/c/Python27/Scripts:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/Skype/Phone:/c/Program Files/Git/cmd:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/c/Program Files (x86)/Microsoft SDKs/TypeScript/1.0:/c/Program Files/Microsoft SQL Server/120/Tools/Binn:/c/Users/pavel/.dnx/bin:/c/Program Files/Microsoft DNX/Dnvm:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/WINDOWS/SysWOW64/WindowsPowerShell/v1.0/Modules/TShell/TShell:/c/Program Files/Samsung/AllShare Framework DMS/1.3.23:/c/Program Files/Samsung/AllShare Framework DMS/1.3.23/64bit:/c/Program Files/TortoiseGit/bin:/c/ProgramData/chocolatey/bin:/c/Program Files/CMake/bin:/c/Program Files/Java/jdk1.8.0_112/bin:/usr/bin:/i/Anaconda3:/i/Anaconda3/Scripts:/i/Anaconda3/Library/bin:/c/Users/pavel/AppData/Local/Programs/Python/Python35-32/Scripts:/c/Users/pavel/AppData/Local/Programs/Python/Python35-32:/c/Users/pavel/AppData/Local/Microsoft/WindowsApps:/c/Program Files/CMake/bin:/c/ProgramData/chocolatey/lib/msys2:/:/usr/bin'
+ PATH='/I/Anaconda3:/c/Perl64/site/bin:/c/Perl64/bin:/c/Python27:/c/Python27/Scripts:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/Program Files (x86)/Skype/Phone:/c/Program Files/Git/cmd:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/c/Program Files (x86)/Microsoft SDKs/TypeScript/1.0:/c/Program Files/Microsoft SQL Server/120/Tools/Binn:/c/Users/pavel/.dnx/bin:/c/Program Files/Microsoft DNX/Dnvm:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/WINDOWS/SysWOW64/WindowsPowerShell/v1.0/Modules/TShell/TShell:/c/Program Files/Samsung/AllShare Framework DMS/1.3.23:/c/Program Files/Samsung/AllShare Framework DMS/1.3.23/64bit:/c/Program Files/TortoiseGit/bin:/c/ProgramData/chocolatey/bin:/c/Program Files/CMake/bin:/c/Program Files/Java/jdk1.8.0_112/bin:/usr/bin:/i/Anaconda3:/i/Anaconda3/Scripts:/i/Anaconda3/Library/bin:/c/Users/pavel/AppData/Local/Programs/Python/Python35-32/Scripts:/c/Users/pavel/AppData/Local/Programs/Python/Python35-32:/c/Users/pavel/AppData/Local/Microsoft/WindowsApps:/c/Program Files/CMake/bin:/c/ProgramData/chocolatey/lib/msys2:/:/usr/bin'
+ export TF_NEED_CUDA=0
+ TF_NEED_CUDA=0
+ bazel clean
ERROR: CreateFile(C:\tmp\Bazel\UUElXoeN\install): The system cannot find the file specified.
 (2)
..............
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
++ bazel info output_base
+ output_base=C:/tmp/Bazel/UUElXoeN
+ bazel shutdown
+ sleep 5
+ rm -rf C:/tmp/Bazel/UUElXoeN
+ echo ''
+ ./configure
/d/tf/tensorflow /d/tf/tensorflow
Can't do inplace edit without backup.

**Comment by maccam912** [comment]
I had this issue when I was trying to use the perl I installed on windows. Once I 'pacman -Syu perl' on msys2, this issue was fixed for me.

**Comment by meteorcloudy** [comment]
@maccam912 Thanks!  I never had this error before, @pkonovalov-softheme Can you try the suggested solution?

**Comment by pkonovalov-softheme** [comment]
This problem was solved by running **pacman -Syu perl'** as  @maccam912  suggested AND after uninstalling Windows active Perl.

Now build failes with:
ERROR: D:/tf/tensorflow/tensorflow/contrib/cmake/build/grpc/src/grpc/BUILD:159:1: no such target '//external:libssl': target 'libssl' not declared in package 'external' defined by D:/tf/tensorflow/WORKSPACE and referenced by '//tensorflow/contrib/cmake/build/grpc/src/grpc:grpc'.
ERROR: D:/tf/tensorflow/tensorflow/contrib/cmake/build/grpc/src/grpc/BUILD:159:1: no such target '//external:libssl': target 'libssl' not declared in package 'external' defined by D:/tf/tensorflow/WORKSPACE and referenced by '//tensorflow/contrib/cmake/build/grpc/src/grpc:grpc'.
ERROR: Evaluation of query "deps((//tensorflow/... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.

Looks like that is an other issue.

**Comment by meteorcloudy** [comment]
Looks like you tried to run CMake in the same repository? Can you rebuild from a clean TF repo?

**Comment by pkonovalov-softheme** [comment]
"git clean -fxd" did not help. After I have cloned repos in other place- those errors have gon, but got new error:
ERROR: /DEFAULT.WORKSPACE:11:1: no such package '@local_jdk//': com.google.devtools.build.lib.skyframe.InconsistentFilesystemException: Inconsistent filesystem operations. C:/Program Files/Java/jdk1.8.0_112 is no longer an existing directory. Did you delete it during the build? The results of the build are not guaranteed to be correct. You should probably run 'blaze clean' and investigate the filesystem inconsistency (likely due to filesytem updates concurrent with the build) and referenced by '//external:bootclasspath'.
ERROR: /DEFAULT.WORKSPACE:59:1: no such package '@local_jdk//': com.google.devtools.build.lib.skyframe.InconsistentFilesystemException: Inconsistent filesystem operations. C:/Program Files/Java/jdk1.8.0_112 is no longer an existing directory. Did you delete it during the build? The results of the build are not guaranteed to be correct. You should probably run 'blaze clean' and investigate the filesystem inconsistency (likely due to filesytem updates concurrent with the build) and referenced by '//external:jdk'.
ERROR: Evaluation of query "deps((//tensorflow/... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.

The folder C:/Program Files/Java/jdk1.8.0_112  exists and I have installed jdk-8u112-windows-x64.exe on windows.

**Comment by meteorcloudy** [comment]
Ah, you are hitting this error https://github.com/bazelbuild/bazel/issues/1463, it's already fixed at HEAD, but the fix is not included in 0.4.0. You can work around this by cloning the repo at C drive, or build Bazel from HEAD. And we'll have 0.4.1 release soon, sorry for the trouble.

**Comment by pkonovalov-softheme** [comment]
Thank you @meteorcloudy ! 
I have moved repos to C:\ and now is able to build farther. Now I got:

INFO: All external dependencies fetched successfully.
+ bazel build -c opt --cpu=x64_windows_msvc --host_cpu=x64_windows_msvc --copt=/w --verbose_failures --experimental_ui tensorflow/tools/pip_package:build_pip_package
ERROR: C:/tmp/Bazel/Dlaez6KK/external/local_config_cuda/cuda/BUILD:94:12: in srcs attribute of cc_library rule @local_config_cuda//cuda:cudnn: file '@local_config_cuda//cuda:lib/x64/cudnn.lib' is misplaced here (expected .cc, .cpp, .cxx, .c++, .C, .c, .h, .hh, .hpp, .hxx, .inc, .S, .s, .asm, .a, .pic.a, .lo, .pic.lo, .so, .dylib, .dll, .o or .pic.o)
ERROR: C:/tmp/Bazel/Dlaez6KK/external/local_config_cuda/cuda/BUILD:94:12: in srcs attribute of cc_library rule @local_config_cuda//cuda:cudnn: '@local_config_cuda//cuda:lib/x64/cudnn.lib' does not produce any cc_library srcs files (expected .cc, .cpp, .cxx, .c++, .C, .c, .h, .hh, .hpp, .hxx, .inc, .S, .s, .asm, .a, .pic.a, .lo, .pic.lo, .so, .dylib, .dll, .o or .pic.o)
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted
INFO: Elapsed time: 2.749s
FAILED: Build did NOT complete successfully
+ exit 1

I am building CPU version without CUDA support:
" export TF_NEED_CUDA=0
+ TF_NEED_CUDA=0"

**Comment by meteorcloudy** [comment]
Oh, I see. It's the same error here:
http://ci.tensorflow.org/job/tf-master-win-bzl/77/console

The reason is Bazel 0.4.0 doesn't allow `*.lib` files to be sources of cc_library, this is also fixed at HEAD in Bazel repo. Is it ok for you to build Bazel from HEAD, or you can download the binary built by our ci here:
http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=windows-x86_64/

Thanks for your patience with Bazel, we'll make it better soon!

**Comment by pkonovalov-softheme** [comment]
<Thanks for your patience with Bazel, we'll make it better soon!
Work as software developer taught me to be extra patient :)

I have used the Bazel binary from the link above. And now got error:

ERROR: C:/tmp/_bazel_pavel/bga0GFiy/external/nanopb_git/BUILD:6:1: C++ compilation of rule '@nanopb_git//:nanopb' failed: msvc_cl.bat failed: error executing command
  cd C:/tmp/_bazel_pavel/bga0GFiy/execroot/tensorflow
  SET PATH=external/local_config_cc/wrapper/bin
  external/local_config_cc/wrapper/bin/msvc_cl.bat -m64 /D__inline__=__inline /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /D_USE_MATH_DEFINES /nologo /bigobj /Zm500 /J /Gy /GF /W3 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /DNDEBUG /O2 -Xcompilation-mode=opt /w /Iexternal/nanopb_git /Ibazel-out/vc_14_0_x64-py3-opt/genfiles/external/nanopb_git /Iexternal/bazel_tools /Ibazel-out/vc_14_0_x64-py3-opt/genfiles/external/bazel_tools /Iexternal/nanopb_git /Ibazel-out/vc_14_0_x64-py3-opt/genfiles/external/nanopb_git /Iexternal/bazel_tools/tools/cpp/gcc3 /DEPENDENCY_FILE bazel-out/vc_14_0_x64-py3-opt/bin/external/nanopb_git/_objs/nanopb/external/nanopb_git/pb_encode.d /c external/nanopb_git/pb_encode.c /Fobazel-out/vc_14_0_x64-py3-opt/bin/external/nanopb_git/_objs/nanopb/external/nanopb_git/pb_encode.o: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 2
c:\tmp\_bazel_pavel\bga0gfiy\execroot\tensorflow\external\nanopb_git\pb.h(66): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
ERROR: C:/tmp/_bazel_pavel/bga0GFiy/external/nanopb_git/BUILD:6:1: output 'external/nanopb_git/_objs/nanopb/external/nanopb_git/pb_common.o' was not created
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by meteorcloudy** [comment]
Hmm.. I am not sure why this is happening. Can you try to run `bazel clean --expunge` and then rebuild again? The command will fail with an error saying something like `ERROR: C:/temp/_bazel_pcloudy/Pm9yvx2g/server/jvm.out (Permission denied)`, but you can safely ignore it, we'll fix this.

Here is what I tested with our latest[ Bazel release candidate ](http://ci.bazel.io/view/Bazel%20bootstrap%20and%20maintenance/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=windows-x86_64/1014/) today and I succeeded:

-  Clone TF reop
-  Run `./configure` without enabling GPU support
-  My `~/.bazelrc` file:
```
build -c opt
build --cpu=x64_windows_msvc
build --host_cpu=x64_windows_msvc
build --copt="/w"                  # Suppress some warning messages
build --experimental_ui            # Enable a nice UI
build --verbose_failures
```
- Run `bazel build tensorflow/tools/pip_package:build_pip_package`

And I am not quite familiar with tensorboard, but I thinks it's not working on Windows yet, I'll look into it.

**Comment by pkonovalov-softheme** [comment]
Now bash is just exiting out to windows console during  ./configure command looks something went wrong with python library path.

pavel@brans  /C/tensorflow
$ ./configure
/C/tensorflow /C/tensorflow
Please specify the location of python. [Default is /c/Python27/python]: /i/Anaconda3/python
Found possible Python library paths:
  I:\Anaconda3
  I:\Anaconda3\lib\site-packages
Please input the desired Python library path to use.  Default is [I:\Anaconda3]
/i/Anaconda3/libs/python35.lib


ERROR: Invalid python library path: /i/Anaconda3/libs/python35.lib.

pavel@brans  /C/tensorflow
$ ./configure
/C/tensorflow /C/tensorflow
Please specify the location of python. [Default is /c/Python27/python]: /i/Anaconda3/python
Found possible Python library paths:
  I:\Anaconda3
  I:\Anaconda3\lib\site-packages
Please input the desired Python library path to use.  Default is [I:\Anaconda3]
/i/Anaconda3/libs/
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

**Comment by meteorcloudy** [comment]
Oh, for python library path, you should just use the default one by entering a blank line or enter either `I:\Anaconda3` or `I:\Anaconda3\lib\site-packages`, both places works on my machine.

**Comment by pkonovalov-softheme** [comment]
I have tried that also. If I leaving the blank line - bash exiting to windows. Also I have tried  I:\Anaconda3 and  \i\Anaconda3 paths and got errors:

pavel@brans  C:/tensorflow
$ ./configure
C:/tensorflow C:/tensorflow
Found possible Python library paths:
  I:\Anaconda3
  I:\Anaconda3\lib\site-packages
Please input the desired Python library path to use.  Default is [I:\Anaconda3]
\i\Anaconda3


ERROR: Invalid python library path:i.Anaconda3

pavel@brans  C:/tensorflow
$ ./configure
C:/tensorflow C:/tensorflow
Found possible Python library paths:
  I:\Anaconda3\lib\site-packages
  I:\Anaconda3
Please input the desired Python library path to use.  Default is [I:\Anaconda3\lib\site-packages]
 I:\Anaconda3
ERROR: Invalid python library path: I:Anaconda3.


Also I have tried using export command to set up vars:
pavel@brans  C:/tensorflow
$ export TMPDIR="C:/tmp"

pavel@brans  C:/tensorflow
$ export BAZEL_SH="C:/tools/msys64/usr/bin/bash"

pavel@brans  C:/tensorflow
$ export PYTHON_BIN_PATH="I:/Anaconda3/python"

pavel@brans  C:/tensorflow
$ export BAZEL_PYTHON="I:/Anaconda3/python"

pavel@brans  C:/tensorflow
$ export BAZEL_VS="E:/Program Files (x86)/Microsoft Visual Studio 14.0" __(by the way you can take it from %VS140COMNTOOLS%\..\.. environment var)__

pavel@brans  C:/tensorflow
$ export PATH="/I/Anaconda3:$PATH"

then: 
$ bazel build -c opt --cpu=x64_windows_msvc --host_cpu=x64_windows_msvc --copt="/w" --verbose_failures --experimental_u
i tensorflow/tools/pip_package:build_pip_package
ERROR: CreateFile(C:\tmp\_bazel_pavel\s7kGbK8z\install): The system cannot find the file specified.
 (2)
Killed non-responsive server process (pid=286036)
...............
WARNING: C:/tensorflow/tensorflow/tensorflow.bzl:29:5:
Current Bazel is not a release version, cannot check for compatibility.
WARNING: C:/tensorflow/tensorflow/tensorflow.bzl:30:5: Make sure that you are running at least Bazel 0.3.2.
ERROR: C:/tensorflow/tensorflow/core/BUILD:1117:1: no such target '//tensorflow/tools/git:gen/spec.json': target 'gen/spec.json' not declared in package 'tensorflow/tools/git' defined by C:/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'
ERROR: C:/tensorflow/tensorflow/core/BUILD:1117:1: no such target '//tensorflow/tools/git:gen/head': target 'gen/head' not declared in package 'tensorflow/tools/git' defined by C:/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'
ERROR: C:/tensorflow/tensorflow/core/BUILD:1117:1: no such target '//tensorflow/tools/git:gen/branch_ref': target 'gen/branch_ref' not declared in package 'tensorflow/tools/git' defined by C:/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted
INFO: Elapsed time: 25.718s
FAILED: Build did NOT complete successfully

Maybe Win10 issue?

**Comment by meteorcloudy** [comment]
Can you try `I:\\Anaconda3` or `I:/Anaconda3`, I think it is because we have to escape `\` when running in MSYS.
Once `./configure` succeeds, the bazel failure should go away.

Exporting those environment variables is a good idea.

And thanks for reminding `%VS140COMNTOOLS%` environment variable, that could be very helpful.

**Comment by meteorcloudy** [comment]
Looks like it is the problem:
```
pcloudy@PCLOUDY1-W MSYS ~/meteorcloudy/tensorflow
$ ./configure
~/meteorcloudy/tensorflow ~/meteorcloudy/tensorflow
Please specify the location of python. [Default is /c/Program Files/Anaconda3/python]:
Found possible Python library paths:
  C:\Program Files\Anaconda3\lib\site-packages
  C:\Program Files\Anaconda3
Please input the desired Python library path to use.  Default is [C:\Program Files\Anaconda3\lib\site-packages]
C:\Program Files\Anaconda3


ERROR: Invalid python library path: C:Program FilesAnaconda3.

pcloudy@PCLOUDY1-W MSYS ~/meteorcloudy/tensorflow
$ ./configure
~/meteorcloudy/tensorflow ~/meteorcloudy/tensorflow
Please specify the location of python. [Default is /c/Program Files/Anaconda3/python]:
Found possible Python library paths:
  C:\Program Files\Anaconda3\lib\site-packages
  C:\Program Files\Anaconda3
Please input the desired Python library path to use.  Default is [C:\Program Files\Anaconda3\lib\site-packages]
C:\\Program Files\\Anaconda3
Junction created for util\python\python_include <<===>> C:\Program Files\Anaconda3\include
Junction created for util\python\python_lib <<===>> C:\Program Files\Anaconda3
Junction created for third_party\py\numpy\numpy_include <<===>> C:\Program Files\Anaconda3\lib\site-packages\numpy\core\include
Do you wish to build TensorFlow with GPU support? [y/N] n
No GPU support will be enabled for TensorFlow
Configuration finished
INFO: All external dependencies fetched successfully.

```

**Comment by pkonovalov-softheme** [comment]
I have tried all this many times with no luck :( Bash is exiting after:

Please input the desired Python library path to use.  Default is [I:\Anaconda3]
I:\\Anaconda3
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

**Comment by meteorcloudy** [comment]
OK, at least it's not giving the `Invalid python library path` again.
Can you do
```
export PYTHON_BIN_PATH=I:/Anaconda3/python
export TF_NEED_CUDA=0
```
And then run `echo "" | ./configure` ?

**Comment by meteorcloudy** [comment]
And adding `set -ex` at the beginning of `./configure` will give us more information to debug this. :)

**Comment by pkonovalov-softheme** [comment]
That is strange, but  after
export PYTHON_BIN_PATH=I:/Anaconda3/python
export TF_NEED_CUDA=0
and 
export BAZEL_VS="E:/Program Files (x86)/Microsoft Visual Studio 14.0"
echo "" | ./configure
configure command succeeded.
Build still failed

bazel build tensorflow/tools/pip_package:build_pip_package
Extracting Bazel installation...
Cannot terminate server process with PID 464576
.
INFO: Found 1 target...
ERROR: C:/tmp/_bazel_pavel/s7kGbK8z/external/grpc/BUILD:69:1: C++ compilation of rule '@grpc//:gpr' failed: gcc failed: error executing command C:/tools/msys64/usr/bin/gcc -MD -MF bazel-out/local-py3-fastbuild/bin/external/grpc/_objs/gpr/external/grpc/src/core/lib/support/wrap_memcpy.d -iquote external/grpc -iquote ... (remaining 19 argument(s) skipped): java.io.IOException: CreateProcess(): The system cannot find the file specified.
.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 41.476s, Critical Path: 3.86s

INFO: Found 1 target...
ERROR: C:/tmp/_bazel_pavel/s7kGbK8z/external/grpc/BUILD:69:1: C++ compilation of rule '@grpc//:gpr' failed: gcc failed: error executing command C:/tools/msys64/usr/bin/gcc -MD -MF bazel-out/local-py3-fastbuild/bin/external/grpc/_objs/gpr/external/grpc/src/core/lib/support/wrap_memcpy.d -iquote external/grpc -iquote ... (remaining 19 argument(s) skipped): java.io.IOException: CreateProcess(): The system cannot find the file specified.
.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 41.476s, Critical Path: 3.86s

**Comment by meteorcloudy** [comment]
It's good the configure command succeed.

The build failure is because you are not using MSVC toolchain.
Try
`bazel -c opt  --cpu=x64_windows_msvc --host_cpu=x64_windows_msvc --copt="/w" --experimental_ui --verbose_failures tensorflow/tools/pip_package:build_pip_package`
Or make sure your `~/.bazelrc` is:
```
build -c opt
build --cpu=x64_windows_msvc
build --host_cpu=x64_windows_msvc
build --copt="/w"                  # Suppress some warning messages
build --experimental_ui            # Enable a nice UI
build --verbose_failures

```

**Comment by pkonovalov-softheme** [comment]
$ bazel -c opt --cpu=x64_windows_msvc --host_cpu=x64_windows_msvc --copt="/w" --experimental_ui --verbose_failures tens
orflow/tools/pip_package:build_pip_package
Unknown Bazel startup option: '-c'.
  For more info, run 'Bazel help startup_options'.

$ bazel version
Build label: 0.4.1rc2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 23 08:59:10 2016 (1479891550)
Build timestamp: 1479891550
Build timestamp as int: 1479891550

**Comment by meteorcloudy** [comment]
Sorry, I updated the comment, it's:
`bazel build -c opt  --cpu=x64_windows_msvc --host_cpu=x64_windows_msvc --copt="/w" --experimental_ui --verbose_failures tensorflow/tools/pip_package:build_pip_package`

**Comment by pkonovalov-softheme** [comment]
That helped :)

after "bazel clean --expunge" build still fails with

ERROR: C:/tmp/_bazel_pavel/s7kGbK8z/external/nanopb_git/BUILD:6:1: C++ compilation of rule '@nanopb_git//:nanopb' failed: msvc_cl.bat failed: error executing command
  cd C:/tmp/_bazel_pavel/s7kGbK8z/execroot/tensorflow
  SET PATH=external/local_config_cc/wrapper/bin
  external/local_config_cc/wrapper/bin/msvc_cl.bat -m64 /D__inline__=__inline /DOS_WINDOWS=OS_WINDOWS /DCOMPILER_MSVC /DNOGDI /DNOMINMAX /DPRAGMA_SUPPORTED /D_WIN32_WINNT=0x0600 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS /D_USE_MATH_DEFINES /nologo /bigobj /Zm500 /J /Gy /GF /W3 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /DNDEBUG /O2 -Xcompilation-mode=opt /w /Iexternal/nanopb_git /Ibazel-out/vc_14_0_x64-py3-opt/genfiles/external/nanopb_git /Iexternal/bazel_tools /Ibazel-out/vc_14_0_x64-py3-opt/genfiles/external/bazel_tools /Iexternal/nanopb_git /Ibazel-out/vc_14_0_x64-py3-opt/genfiles/external/nanopb_git /Iexternal/bazel_tools/tools/cpp/gcc3 /DEPENDENCY_FILE bazel-out/vc_14_0_x64-py3-opt/bin/external/nanopb_git/_objs/nanopb/external/nanopb_git/pb_common.d /c external/nanopb_git/pb_common.c /Fobazel-out/vc_14_0_x64-py3-opt/bin/external/nanopb_git/_objs/nanopb/external/nanopb_git/pb_common.o: com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 2
c:\tmp\_bazel_pavel\s7kgbk8z\execroot\tensorflow\external\nanopb_git\pb.h(66): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
ERROR: C:/tmp/_bazel_pavel/s7kGbK8z/external/grpc/BUILD:69:1: output 'external/grpc/_objs/gpr/external/grpc/src/core/lib/support/time.o' was not created
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 96.068s, Critical Path: 2.33s
FAILED: Build did NOT complete successfully

**Comment by meteorcloudy** [comment]
This is weird.. I am guessing maybe there is something wrong with your Visual Studio installation,
I found [this error](https://social.msdn.microsoft.com/Forums/vstudio/en-US/0f580a73-6f11-4aa6-abbe-6bf1438734c2/standard-files-stddefh-stringh-missing-in-visual-studio-2015-rc?forum=vclanguage).
On my machine, `stddef.h` can be found at `C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt`
Can you try to reinstall Visual Studio 2015?

**Comment by pkonovalov-softheme** [comment]
<On my machine, stddef.h can be found at C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt
I also have stddef.h there.

From [https://social.msdn.microsoft.com/Forums/vstudio/en-US/0f580a73-6f11-4aa6-abbe-6bf1438734c2/standard-files-stddefh-stringh-missing-in-visual-studio-2015-rc?forum=vclanguage](the topic you posted)

> "The headers, sources, and libraries are now distributed as part of a separate 
> Universal CRT SDK. This SDK is included with Visual Studio; it is installed by 
> default to C:\Program Files (x86)\Windows Kits\10."

I have installed Windows Kits v10 on my env. in the past, don't you have it? Visual Studio is ok on my env -except Tensorflow hundreds of different solution are building well there.

I am familiar with visual studio and MSBuild pretty well and maybe can find the core of problem with stddef.h. Does bazel invoke VS/msbuild internally during build? Can I reproduce this error with msbuild command? 



---

I have tried to run configure on other env. And got other unclear error:

./configure
./configure: line 2: $'\r': command not found
./configure: line 4: $'\r': command not found
./configure: line 30: syntax error near unexpected token `$'in\r''
'/configure: line 30: `  case $INPUT in

**Comment by tfboyd** [comment]
This issue is quite old and hasn't had recent activity. Be sure to try the latest build instructions (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile) on the latest version of TensorFlow, and please create a new bug if it is still not working. Thank you.
