### ISSUE TITLE
Wrong gradient for `tf.atan` with complex input

### ISSUE THREAD

**Issue by VictoriaGriffith** [tensorflow/tensorflow#57480]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

```shell
The theoretical and numerical gradient are different when input is complex for `tf.atan`
```

### Standalone code to reproduce the issue

```
import tensorflow as tf

def fn(x): return tf.atan(x)
x = tf.complex([[0.]], [[1.1262]])

value = fn(x)

theoretical, numerical = tf.test.compute_gradient(fn, [x])
print(theoretical)
print(numerical)

assert tf.experimental.numpy.allclose(theoretical, numerical)

```

### Relevant log output

```shell
(array([[-3.7268043, -0.       ],
       [ 0.       , -3.7268043]], dtype=float32),)
(array([[1604.7687   ,    0.       ],
       [   0.       ,   -3.7269287]], dtype=float32),)
AssertionError
```
</details>

**Comment by sushreebarsa** [comment]
@VictoriaGriffith I tried to reproduce the issue reported, could you please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/d3af13fa0eded8553a1c8da57af96f62/57480.ipynb#scrollTo=4yYQy-ozuvno) and confirm the same?
Thank you!

**Comment by VictoriaGriffith** [comment]
Hi @sushreebarsa , thanks for reproducing the issue. 

1. Indeed, the bug only appears in **`TF 2.9.1`** because TF 2.8 lack support for `Atan` on `DT_COMPLEX64`.
2. For your workaround, I can see you passed a list of complex numbers instead of tensor. However, that **does not avoid the bug**, because this bug only happens with **a special complex input whose real=0**.
Below is an buggy example that **modifies your workaround example** by changing `[1.+4.563j]` to `[0.+4.563j]` and still raises AssertionError, could you please confirm the same? Thank you!

```
# Run in TF 2.9.1
# !pip install tensorflow==2.9.1
import tensorflow as tf 
print(tf.__version__)

def fn(x): return tf.atan(x)

theoretical, numerical = tf.test.compute_gradient(fn, [0.+4.563j])#The arguments for the function as a list or tuple of values convertible to a Tensor
print(theoretical)
print(numerical)

assert tf.experimental.numpy.allclose(theoretical, numerical) # AssertionError
```

**Comment by sushreebarsa** [comment]
@VictoriaGriffith Thank you for the update!
@gadagashwini I was able to replicate the issue [here](https://colab.research.google.com/gist/sushreebarsa/d3af13fa0eded8553a1c8da57af96f62/57480.ipynb#scrollTo=HMtjbQWBRl4Y). Please find the attached gist for reference. Thank you!

**Comment by sachinprasadhs** [comment]
@VictoriaGriffith , Did you face similar behavior in any dtype other than complex?

**Comment by VictoriaGriffith** [comment]
Hi @sachinprasadhs  this behavior only happens with complex, for example, `float32` will pass:
```
import tensorflow as tf 
print(tf.__version__)

def fn(x): return tf.atan(x)

theoretical, numerical = tf.test.compute_gradient(fn, [0.18])
print(theoretical)
print(numerical)

assert tf.experimental.numpy.allclose(theoretical, numerical) # Pass
```
Oututs:
```
(array([[0.9686168]], dtype=float32),)
(array([[0.9686203]], dtype=float32),)
```

**Comment by sachinprasadhs** [comment]
Could you please refer [this](https://github.com/tensorflow/tensorflow/issues/57357#issuecomment-1245671069) comment and let us know if this is useful for you. Thanks!
