### ISSUE TITLE
`tf.math.bincount` crashes

### ISSUE THREAD

**Issue by VictoriaGriffith** [tensorflow/tensorflow#57487]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

```shell
Session crashes when call bincount: abort (core dumped)
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
arr = tf.random.uniform([2, 4], minval=1.0, maxval=3.0, dtype=tf.float32)
weights = 4
axis = -1

r = tf.math.bincount(arr, weights=weights, axis=axis )
```

### Relevant log output

```shell
abort (core dumped)
```
</details>

**Comment by sushreebarsa** [comment]
@VictoriaGriffith I was able to replicate the issue on colab using TF [v2.9.0](https://colab.research.google.com/gist/sushreebarsa/74aba8980a28187df994a46a4767e42d/57487.ipynb) and faced `InvalidArgumentError`  in [tf-nightly](https://colab.research.google.com/gist/sushreebarsa/98cc75e343cee588a39c307817e2d87c/57487-nightly.ipynb#scrollTo=uAKcHp9WqBhO)(2.11.0.dev2022082907). Please find the attached gists and confirm the same. Thank you!

**Comment by VictoriaGriffith** [comment]
I see, so it's fixed in nightly, thanks you!
