### ISSUE TITLE
How to replace an existing op with a custom op without retraining?

### ISSUE THREAD

**Issue by tianboh** [tensorflow/tensorflow#57491]
### My question

Hi there,

I have an old model whose training code is lost, but I still have the saved_model format file. I want to optimize this model by writing some custom ops and replace the original op because I know it is a BERT-like model. 

My question is, once I have written the custom op, how can I ask the original model to replace its op with my custom op? I only have a driver code written in C++, so I cannot use my custom op retrain a new model.

### Standalone code to reproduce the issue

The driver's code is written in C++. 

```C++
int main(int argc, char** argv)
{
   const string pathToGraph = PATH_TO_PBDIR;
   Status status;
   tensorflow::SessionOptions sessionOptions;
   tensorflow::RunOptions runOptions;
   tensorflow::SavedModelBundle savedModelBundle;
   auto deviceCountMap = sessionOptions.config.mutable_device_count();
   (*deviceCountMap)[string("GPU")] = 1;
   sessionOptions.config.set_log_device_placement(true);
   sessionOptions.config.mutable_graph_options()->mutable_optimizer_options()->set_do_function_inlining(true);
   sessionOptions.config.mutable_experimental()->set_optimize_for_static_graph(true);
   sessionOptions.config.mutable_gpu_options()->set_per_process_gpu_memory_fraction(0.5);
   sessionOptions.config.mutable_gpu_options()->set_allow_growth(true);
  string path = pathToGraph;
  Status ret = LoadSessionBundleOrSavedModelBundle(sessionOptions, runOptions, path, {"serve"}, &savedModelBundle);
  Session* session = savedModelBundle.session.get();
  
  std::vector<std::pair<string, Tensor>> input;
  prepare_inputs(input);

  std::vector<tensorflow::Tensor> normal_answer;
  string tmp = OUTPUT_TENSOR_NAME;
  status = session->Run(input, outname, {}, &normal_answer);

  return 0;
```
  
### Issue Type

Support

### Source

source

### Tensorflow Version

tf 1.15

### Custom Code

Yes

**Comment by mohantym** [comment]
Hi @tianboh !
1.x versions are not supported anymore. But you can go [2.x documentation](https://www.tensorflow.org/guide/create_op) on adding and testing a custom op.
Thank you!

**Comment by tianboh** [comment]
Thank you, I will try it!
