### ISSUE TITLE
Check-fail in MaxPool3DGrad

### ISSUE THREAD

**Issue by shijy16** [tensorflow/tensorflow#57497]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9 and 2.11.0-dev20220828

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10

### CUDA/cuDNN version

CUDA 11.5

### Current Behaviour?

```shell
A check-fail can be triggered in MaxPool3DGrad when some of the inputs' dimension sizes are zero.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
with tf.device("GPU:0"):
    orig_input = tf.random.uniform([19, 10, 0, 7, 19], dtype=tf.float32)
    orig_output = tf.random.uniform([19, 4, 0, 4, 19], dtype=tf.float32)
    grad = tf.random.uniform([19, 4, 0, 4, 19], dtype=tf.float32)
    ksize = [1, 16, 10, 31, 1]
    strides = [1, 3, 1, 2, 1]
    padding = "SAME"
    data_format = "NDHWC"
    res = tf.raw_ops.MaxPool3DGrad(
        orig_input=orig_input,
        orig_output=orig_output,
        grad=grad,
        ksize=ksize,
        strides=strides,
        padding=padding,
        data_format=data_format,
    )
```

### Relevant log output

```shell
2022-08-29 16:23:58.920831: F ./tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (0 vs. 0)
Aborted (core dumped)
```
</details>

**Comment by mohantym** [comment]
Hi @gadagashwini !
Could you look at this issue. It is throwing a segmentation crash with GPU mode in [2.8](https://colab.sandbox.google.com/gist/mohantym/93332370cd076e7d85faf08ecc0f9725/git_57497.ipynb#scrollTo=jVz1qrqGT0U6), [2.9](https://colab.sandbox.google.com/gist/mohantym/519b151cf8f4e9e5718c7bacd4818236/git_57497.ipynb#scrollTo=jVz1qrqGT0U6), [2.10.rc2](https://colab.sandbox.google.com/gist/mohantym/041a586adcf9722c18ef7e2e49099a7c/git_57497.ipynb#scrollTo=jVz1qrqGT0U6) and [nightly](https://colab.sandbox.google.com/gist/mohantym/fd52775dc4e0debe65ba006577726945/git_57497.ipynb#scrollTo=jVz1qrqGT0U6) but running fine in CPU mode.
Thank you!

**Comment by sachinprasadhs** [comment]
There are many cases where the CPU version and GPU version will give different results. Sometimes this is because of different hardware capabilities, other times because of different efficiencies.
Considering the performance in GPU, usually all the validations will not be performed as CPU.

**Comment by shijy16** [comment]
I agree that some validations can be ignored for performance in GPU. But it would be better if such ABORTs are checked in advance with precise EXCEPTIONs.

**Comment by tilakrayal** [comment]
@shijy16,
I tried to execute the mentioned code on both [CPU](https://colab.research.google.com/gist/tilakrayal/7034f557b104c8c1182964212b1e87d5/untitled1427.ipynb) and [GPU](https://colab.research.google.com/gist/tilakrayal/8679a54760d2a3f9dd6d1d53e2677bbb/untitled1425.ipynb) with the tensorflow v2.14 and it was executed without any issue/error or the crash. Kindly find the gist of it here. Thank you!
