### ISSUE TITLE
Floating point exception in MaxPool3DGrad

### ISSUE THREAD

**Issue by shijy16** [tensorflow/tensorflow#57498]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9 and 2.11.0-dev20220828

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current Behaviour?

```shell
An FPE can be triggered when the channel of `orig_input` is zero, which may cause a DoS.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
with tf.device("GPU:0"):
    orig_input = tf.random.uniform([16, 28, 30, 10, 0], dtype=tf.float32)
    orig_output = tf.random.uniform([16, 2, 1, 2, 0], dtype=tf.float32)
    grad = tf.random.uniform([16, 2, 1, 2, 0], dtype=tf.float32)
    ksize = [1, 22, 12, 17, 1]
    strides = [1, 16, 30, 7, 1]
    padding = "SAME"
    data_format = "NDHWC"
    res = tf.raw_ops.MaxPool3DGrad(
        orig_input=orig_input,
        orig_output=orig_output,
        grad=grad,
        ksize=ksize,
        strides=strides,
        padding=padding,
        data_format=data_format,
    )
```

### Relevant log output

```shell
Floating point exception (core dumped)
```
</details>

**Comment by dennyX7** [comment]
Facing the same issue.

**Comment by tilakrayal** [comment]
@shijy16,
Could you please confirm where the issue persists when the code is executed in GPU mode only or CPU too? Thank you!

**Comment by shijy16** [comment]
@tilakrayal 
Thanks for response. This issue seems to be GPU mode only.

**Comment by tilakrayal** [comment]
@shijy16,
Looks like this is a duplicate of issue #57497. Could you please confirm and close this issue, since it is already being tracked there? Thank you!

**Comment by shijy16** [comment]
@tilakrayal 
Hi, issuse #57497 is a `check-fail`, but this one is a `Floating-Point-Exception`, the input are different too. So I donot think they are the same issue.

**Comment by tilakrayal** [comment]
@gadagashwini,
I was able to reproduce the issue on **tensorflow-gpu** v2.8, v2.9 and [nightly](https://colab.research.google.com/gist/tilakrayal/e3bfcb2f7ad17b16752cef49ed3f565a/gpu.ipynb) where it was executed on **tensorflow-cpu** without any error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/65f667ad76b250fc460eecf91c2cb7b9/untitled570.ipynb).

**Comment by tilakrayal** [comment]
@shijy16,
I tried to execute the mentioned code on tf-nightly(2.15.0-dev20230918) and it was executed without any error/issue or the crash. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/1e74fde870fe5468d00f83519b45fa2e/untitled1415.ipynb). Thank you!
