### ISSUE TITLE
Check-fail can be triggered in Conv3DBackpropInputV2

### ISSUE THREAD

**Issue by shijy16** [tensorflow/tensorflow#57495]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9 and 2.11.0-dev20220828

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10

### CUDA/cuDNN version

CUDA 11.5

### Current Behaviour?

```shell
A check-fail happens and may cause a DoS.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

input_sizes = [0, 6, 1, 1, 2]
filter = np.ones([3, 1, 1, 2, 3])
out_backprop = np.ones([0, 4, 1, 1, 3])

strides = [1, 1, 1, 1, 1]
padding = 'VALID'
data_format = 'NDHWC'
dilations = [1, 1, 1, 1, 1]
tf.raw_ops.Conv3DBackpropInputV2(input_sizes=input_sizes,\
    filter=filter,\
    out_backprop=out_backprop,\
    strides=strides,\
    padding=padding,\
    data_format=data_format,\
    dilations=dilations)
```

### Relevant log output

```shell
2022-08-29 16:10:10.644814: F ./tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (0 vs. 0)
Aborted (core dumped)
```
</details>

**Comment by tilakrayal** [comment]
@shijy16,
I was able to execute the provided code without any issues/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/515ce7de2aa90daf72847cf5283464ee/untitled540.ipynb) and let me know if anything is missing here. Thank you!

**Comment by shijy16** [comment]
@tilakrayal 
Sorry, I forgot to mention that GPU must be enabled to reproduce the bug.

Please make sure the code is executed with GPU backend enabled.

**Comment by tilakrayal** [comment]
@gadagashwini,
I was able to reproduce the issue on **tensorflow-gpu** v2.8, v2.9 and [nightly](https://colab.research.google.com/gist/tilakrayal/305eecc80662929e5f999688ce5447f6/untitled564.ipynb) whereas on [tensorflow-cpu](https://colab.research.google.com/gist/tilakrayal/6b893e9c512d4070ab955a433a2cd6f9/untitled564.ipynb) the code was executing without any issues. Kindly find the gist.

**Comment by tilakrayal** [comment]
@shijy16,
I tried to execute the mentioned code on both [CPU](https://colab.research.google.com/gist/tilakrayal/69d702df5af5050eea9d8e84900dafa8/untitled1429.ipynb) and [GPU](https://colab.research.google.com/gist/tilakrayal/8c7d70942a57c508f4110d4698af934c/untitled1428.ipynb) with the tensorflow v2.14 and it was executed without any crash/error and also the output is also the same for both environments. Kindly find the gist of it here. Thank you!
