### ISSUE TITLE
Check-fail in MaxPoolGrad

### ISSUE THREAD

**Issue by shijy16** [tensorflow/tensorflow#57502]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9 and 2.11.0-dev20220828

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10

### CUDA/cuDNN version

CUDA 11.5

### Current Behaviour?

```shell
A check-fail can be triggered in MaxPoolGrad.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
with tf.device("GPU:0"):
    orig_input = tf.random.uniform([6, 32, 6, 13], dtype=tf.float32)
    orig_output = tf.random.uniform([6, 2, 0, 13], dtype=tf.float32)
    grad = tf.random.uniform([6, 2, 0, 13], dtype=tf.float32)
    ksize = [1, 13, 8, 1]
    strides = [1, 18, 7, 1]
    padding = "VALID"
    data_format = "NHWC"
    res = tf.raw_ops.MaxPoolGrad(
        orig_input=orig_input,
        orig_output=orig_output,
        grad=grad,
        ksize=ksize,
        strides=strides,
        padding=padding,
        data_format=data_format,
    )
```

### Relevant log output

```shell
2022-08-29 16:51:12.874955: F tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:636] Check failed: cudnnSetTensorNdDescriptor(handle_.get(), elem_type, nd, dims.data(), strides.data()) == CUDNN_STATUS_SUCCESS (3 vs. 0)batch_descriptor: {count: 6 feature_map_count: 13 spatial: 2 0  value_min: 0.000000 value_max: 0.000000 layout: BatchYXDepth}
Aborted (core dumped)
```
</details>

**Comment by sushreebarsa** [comment]
@shijy16 I tried to replicate the issue on colab, could you please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/8b364141eef923b353c0061b2cc8d2b4/57502.ipynb#scrollTo=UPASBHLgjuT-) and confirm the same?
Thank you!

**Comment by shijy16** [comment]
@sushreebarsa Yes, the same check-fail happens here.

**Comment by sachinprasadhs** [comment]
Usually, Checks on GPU and CPU will not be same considering the performance impact.
In few cases it is documented also.
Check the comment [here](https://github.com/tensorflow/tensorflow/issues/57174#issuecomment-1246288003) for details. Thanks!

**Comment by albertz** [comment]
I assume this is not really fixed? We get the same in `MaxPoolingNoMaskOp`.
