### ISSUE TITLE
Reverse-mode auto differentiation didn't reject invalid `axis` input as expected for API `tf.math.reduce_logsumexp`

### ISSUE THREAD

**Issue by eeDigitalSeal** [tensorflow/tensorflow#57517]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### Current Behaviour?

Input parameter `axis` for API `tf.math.reduce_logsumexp` should be at most rank 1. with input axis=`[[0,1]]`,  which is rank 2 and invalid, It should throw `ValueError` in both line 11 and line 17. Now forward-mode autodiff threw error as expected but reverse mode didn't validate the `axis` parameter and passed.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

input = tf.constant([[0.44943833]])

axis = [[0,1]]

with tf.GradientTape() as g:
    g.watch(input)
    # should throw ValueError here, because axis is rank 2, which is invalid, but didn't
    res = tf.math.reduce_logsumexp(input, axis, keepdims=False)
grad = g.gradient(res,input)
print(grad)

with tf.autodiff.ForwardAccumulator(input,tf.constant(1.,shape=[1,1])) as acc:
    # throw error as expected
    res_fwd = tf.math.reduce_logsumexp(input, axis, keepdims=False)
jvp = acc.jvp(res_fwd)
print(jvp)
```

### Relevant log output

```shell
tf.Tensor([[1.]], shape=(1, 1), dtype=float32)
ValueError: Shape must be at most rank 1 but is rank 2 for '{{node gradient_tape/Sum}} = Sum[T=DT_FLOAT, Tidx=DT_INT32, keep_dims=false](gradient_tape/Cast, inputs_1)' with input shapes: [1,1], [1,2].
```
</details>

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to replicate the issue on colab, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/9f90e508901e7926995bc7bdcd1cb376/57517.ipynb) for reference. Thank you!
