### ISSUE TITLE
tf.abs(tf.int32.min) returns a negative value

### ISSUE THREAD

**Issue by hosford42** [tensorflow/tensorflow#57514]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.9.0-18-gd8ce9f9c301

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04.4 LTS

### Mobile device

n/a

### Python version

Python 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0] on linux

### Bazel version

n/a

### GCC/Compiler version

n/a

### GPU model and memory

n/a

### Current Behaviour?

```shell
`tf.abs(tf.int32.min)` returns the unmodified value of `tf.int32.min`, a negative value.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
tf.debugging.assert_non_negative(tf.abs(tf.int32.min + 1), "Works fine.")
tf.debugging.assert_non_negative(tf.abs(tf.int32.min), "Returns a negative value")
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-dd77e4f67efc>", line 3, in <module>
    tf.debugging.assert_non_negative(tf.abs(tf.int32.min), "Returns a negative value")
  File "/home/hosford42/.local/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/hosford42/.local/lib/python3.8/site-packages/tensorflow/python/ops/check_ops.py", line 407, in _binary_assert
    raise errors.InvalidArgumentError(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Returns a negative value.  
Condition x >= 0 did not hold element-wise:
x (shape=() dtype=int32) = 
-2147483648
```
</details>

**Comment by hosford42** [comment]
I realize it's impossible to represent the correct return value as an int32. Either tf.int32.min should be incremented by 1, or an INVALID_ARGUMENT exception should be raised.

I prefer the former, personally. The current value of tf.int32.min could perhaps be repurposed later as an integer equivalent to nan, which would be very helpful in making ints and floats behave more consistently w.r.t. to each other. For example, tf.pow could return this integer nan instead of raising an exception when passed a negative value. In general, with tensors, it makes sense whenever possible to use error placeholders such as nan instead of actually raising exceptions, since a single error can ruin an entire batch or run. Additionally, it gives the user greater control over the behavior of the system, since it's easy to do an assert_all_finite and raise an exception if that's the desired behavior, whereas it's impossible to catch an unwanted exception and use a placeholder value if that's the default behavior.

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.9, v2.8 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/41eb63bced0d3656b602cbe4a3040893/untitled552.ipynb).

**Comment by sachinprasadhs** [comment]
This has. to be edge case scenario.
`tf.int32.min` and `tf.int32.max` are not the same values, which are `-2147483648` and `2147483647` respectively.
Since, `tf.abs(tf.int32.min)` value which is `tf.abs(-2147483648)` exceeds the `tf.int32.max` value which is `2147483647`. it throws exception in that case.
When `tf.int32.min` is added with 1, it matches the `tf.int32.max` value and works in that case.

**Comment by hosford42** [comment]
Yes, that was my conclusion as well. The question that remains is, how should it be handled? Should tf.int32.min be changed so tf.abs returns a valid result for all tf.int32 values, or should an exception be raised when tf.abs(tf.int32.min) is called?

**Comment by cantonios** [comment]
This is a signed integer overflow issue, which results in undefined behavior (UB).  The fact the result happens to be the initial negative value itself is just a consequence of the 2s complement implementation on (almost) all system - it is not to be relied upon. If you were to run this under UB santizers, it would trigger an error.

> Should tf.int32.min be changed so tf.abs returns a valid result for all tf.int32 values

We shouldn't artificially narrow the range across tensorflow solely for this `tf.math.abs` UB edge-case.  This would also make us inconsistent with pytorch and numpy.

> Either tf.int32.min should be incremented by 1

This would be incorrect as well.  If you needed to account for this use-case, you could clamp your inputs explicitly via `tf.clip_by_value` or `tf.math.maximum` prior to taking the `abs`.  Or you could use the negative result as your "integer NaN" in this one context.

> or  should an exception be raised when tf.abs(tf.int32.min) is called?

This would be quite costly.  `abs` is used in _a lot_, and adding additional error checking would slow everything down, insert additional ops in the graph, and would prevent op-fusion in many context.  We don't generally do error checking on inputs unless they would cause a system crash.  _Many_ functions could trigger a signed-integer overflow (`tf.math.add`, for example), so `abs` is not unique in the way.

The current behavior is the best we can do.  Numpy suffers the same UB issue.

**Comment by hosford42** [comment]
That makes sense. It seems to me that we ought not do error checking for the other integer operations, then, as it leads to misunderstandings and surprises. Whatever the approach, it should be consistent.
