### ISSUE TITLE
When I an tryng to run the model for trainig, I am getting TypeError: 'numpy.float64' object cannot be interpreted as an integer for efficientdet.

### ISSUE THREAD

**Issue by vaibkum-bh** [tensorflow/tensorflow#57524]
I am facing TypeError: 'numpy.float64' object cannot be interpreted as an integer this while training my model.
![Screenshot (22)](https://user-images.githubusercontent.com/109948997/187413527-052e9ec7-19c7-48e3-b684-4b841e76836a.png)

**Comment by sushreebarsa** [comment]
@vaibkum-bh 
In order to expedite the trouble-shooting process here, could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thank you!

**Comment by gadagashwini** [comment]
Hi @vaibkum-bh, This issue is related to Numpy version. Install numpy 1.18.5 and pandas 1.1.5

Update pycocotools version from 2.0.0 to 2.0.1. Thank you!
