### ISSUE TITLE
Tensorboard - Black box for graphs after upgrading to TF 0.11

### ISSUE THREAD

**Issue by xtr33me** [tensorflow/tensorflow#5752]
![tensorboard_issue_0 11](https://cloud.githubusercontent.com/assets/1653419/20492832/46047212-afe4-11e6-8eb0-2938e86390ea.png)

I am currently getting a black box where a graph should be when using Tensorboard. I was previously running TF 0.9 and upgraded last night to 0.11 via the pip link below. When I hover over the black box I do see the onHover messages displaying valid values, but I just can't see anything.

--The error received is below and the same thing shown in the screenshot above:

> All candidate resources failed to load. Media load paused.  127.0.1.1:6006
> Unexpected value  parsing viewBox attribute. d3.js:662:6
> NS_ERROR_FAILURE:  tf-tensorboard.html-28.js:199
> 	LineChart.prototype.setupTooltips/< http://127.0.1.1:6006/dist/tf-tensorboard.html-28.js:199:34
> 	CallbackSet</CallbackSet.prototype.callCallbacks/< http://127.0.1.1:6006/plottable/plottable.js:643:21
> 	Set</Set.prototype.forEach/callbackWrapper http://127.0.1.1:6006/plottable/plottable.js:257:77
> 	forEach self-hosted
> 	Set</Set.prototype.forEach http://127.0.1.1:6006/plottable/plottable.js:258:21
> 	CallbackSet</CallbackSet.prototype.callCallbacks http://127.0.1.1:6006/plottable/plottable.js:642:17
> 	Pointer</Pointer.prototype._handlePointerEvent http://127.0.1.1:6006/plottable/plottable.js:11190:21
> 	Pointer/this._mouseMoveCallback http://127.0.1.1:6006/plottable/plottable.js:11166:65
> 	CallbackSet</CallbackSet.prototype.callCallbacks/< http://127.0.1.1:6006/plottable/plottable.js:643:21
> 	Set</Set.prototype.forEach/callbackWrapper http://127.0.1.1:6006/plottable/plottable.js:257:77
> 	forEach self-hosted
> 	Set</Set.prototype.forEach http://127.0.1.1:6006/plottable/plottable.js:258:21
> 	CallbackSet</CallbackSet.prototype.callCallbacks http://127.0.1.1:6006/plottable/plottable.js:642:17
> 	Mouse</Mouse.prototype._measureAndDispatch http://127.0.1.1:6006/plottable/plottable.js:10501:25
> 	Mouse/processMoveCallback http://127.0.1.1:6006/plottable/plottable.js:10363:65

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
I have not found anyone having this as of yet when performing a search. I was previously running

### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
CUDA 8 and Cudnn 5
output of above ls:

> total 64
> drwxr-xr-x  3 root root 4096 Nov 20 21:59 bin
> drwxr-xr-x  5 root root 4096 Nov 20 21:59 doc
> drwxr-xr-x  5 root root 4096 Nov 20 21:59 extras
> drwxr-xr-x  5 root root 4096 Nov 20 22:19 include
> drwxr-xr-x  5 root root 4096 Nov 20 21:59 jre
> drwxr-xr-x  3 root root 4096 Nov 20 22:19 lib64
> drwxr-xr-x  8 root root 4096 Nov 20 21:59 libnsight
> drwxr-xr-x  7 root root 4096 Nov 20 21:59 libnvvp
> drwxr-xr-x  3 root root 4096 Nov 20 21:59 nvml
> drwxr-xr-x  7 root root 4096 Nov 20 21:59 nvvm
> drwxr-xr-x  2 root root 4096 Nov 20 21:59 pkgconfig
> drwxr-xr-x 11 root root 4096 Nov 20 21:59 samples
> drwxr-xr-x  3 root root 4096 Nov 20 21:59 share
> drwxr-xr-x  2 root root 4096 Nov 20 21:59 src
> drwxr-xr-x  2 root root 4096 Nov 20 21:59 tools
> -rw-r--r--  1 root root   20 Nov 20 21:59 version.txt

If installed from binary pip package, provide:

1. A link to the pip package you installed:
Ubuntu/Linux 64-bit, GPU enabled, Python 2.7
Requires CUDA toolkit 8.0 and CuDNN v5. For other versions, see "Install from sources" below.
TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.11

**Comment by xtr33me** [comment]
I would love to know why this is happening still in FF should anyone have any answers, but I just found that this is working fine in Google Chrome.  I am going to close this since I do have a solution.

**Comment by danmane** [comment]
@xtr33me I've found the issue in Firefox. It will be fixed in the 0.12 release.

**Comment by xtr33me** [comment]
@danmane Thats awesome news! Thanks for the info
