### ISSUE TITLE
TFLite with XNNPack delegate is performing slower than TFLite when XNNPack delegate is set to false

### ISSUE THREAD

**Issue by BhaskarsarmaP** [tensorflow/tensorflow#57523]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

2.8.0

### Custom Code

No

### OS Platform and Distribution

Debian 10.2

### Python version

3.7.3 for python3, python 2.7.16

### Bazel version

5.1.0

### GCC/Compiler version

8.3.0

### CUDA/cuDNN version

NA

### GPU model and memory

NA

### Current Behaviour?

```shell
Expected performance benefit when XNNPack delegate is used as claimed.
But not happening. Tested with quant and float models.
```

### Standalone code to reproduce the issue

```shell
Used tensorflow/lite/examples/label_image/

Modified loop count to 100 and tested with num of threads to max and -1 and observed similar results.

% bazel-bin/tensorflow/lite/examples/label_image/label_image --tflite_model mobilenet_v2_1.0_224.tflite --labels tensorflow/lite/examples/label_image/mobilenet_v1_1.0_224/labels.txt --image tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp --use_xnnpack=true
INFO: Loaded model mobilenet_v2_1.0_224.tflite
INFO: resolved reporter
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
XNNPACK delegate created.
INFO: Applied XNNPACK delegate.


INFO: invoked
INFO: average time: 16.0024 ms
INFO: 0.911344: 653 653:military uniform
INFO: 0.0144661: 835 835:suit, suit of clothes
INFO: 0.00624739: 440 440:bearskin, busby, shako
INFO: 0.00296665: 907 907:Windsor tie
INFO: 0.00269024: 753 753:racket, racquet

% bazel-bin/tensorflow/lite/examples/label_image/label_image --tflite_model mobilenet_v2_1.0_224.tflite --labels tensorflow/lite/examples/label_image/mobilenet_v1_1.0_224/labels.txt --image tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp --use_xnnpack=false
INFO: Loaded model mobilenet_v2_1.0_224.tflite
INFO: resolved reporter
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: invoked
INFO: average time: 3.64675 ms
INFO: 0.911344: 653 653:military uniform
INFO: 0.0144661: 835 835:suit, suit of clothes
INFO: 0.00624739: 440 440:bearskin, busby, shako
INFO: 0.00296665: 907 907:Windsor tie
INFO: 0.00269024: 753 753:racket, racquet
```

### Relevant log output

```shell
With XNNPack
INFO: Loaded model mobilenet_v2_1.0_224.tflite
INFO: resolved reporter
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
XNNPACK delegate created.
INFO: Applied XNNPACK delegate.
INFO: invoked
INFO: average time: 16.0024 ms
INFO: 0.911344: 653 653:military uniform
INFO: 0.0144661: 835 835:suit, suit of clothes
INFO: 0.00624739: 440 440:bearskin, busby, shako
INFO: 0.00296665: 907 907:Windsor tie
INFO: 0.00269024: 753 753:racket, racquet


Without XNNPack
INFO: Loaded model mobilenet_v2_1.0_224.tflite
INFO: resolved reporter
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: invoked
INFO: average time: 3.64675 ms
INFO: 0.911344: 653 653:military uniform
INFO: 0.0144661: 835 835:suit, suit of clothes
INFO: 0.00624739: 440 440:bearskin, busby, shako
INFO: 0.00296665: 907 907:Windsor tie
INFO: 0.00269024: 753 753:racket, racquet
```
</details>

**Comment by mohantym** [comment]
Hi @BhaskarsarmaP !
Sorry for the late response. 
I was getting  

> Average time :51.56 ms with --use_xnnpack=True and Average time: 360.005 ms with --use_xnnpack= False  in TF 2.9 with Ubuntu 18 

Attached [gist](https://colab.sandbox.google.com/gist/mohantym/986a94a34beeb15e2e0f0df2ca453afb/tensorflow-ranking.ipynb#scrollTo=-lrM3hp6vXso) for reference.

Could you check in TF 2.9 and let us know. 
Thank you!

**Comment by BhaskarsarmaP** [comment]
I checked in latest 2.9.2 with python3 version 3.7.3

Still the issue persists.

% bazel-bin/tensorflow/lite/examples/label_image/label_image --tflite_model ./mobilenet_v2_1.0_224.tflite  --labels ./mobilenet_v1_1.0_224/labels.txt --image tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp --xnnpack_delegate=true --use_xnnpack=true
INFO: Loaded model ./mobilenet_v2_1.0_224.tflite
INFO: resolved reporter
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
XNNPACK delegate created.
INFO: Applied XNNPACK delegate.
INFO: invoked
INFO: average time: 15.883 ms
INFO: 0.911344: 653 653:military uniform
INFO: 0.0144661: 835 835:suit, suit of clothes
INFO: 0.00624739: 440 440:bearskin, busby, shako
INFO: 0.00296665: 907 907:Windsor tie
INFO: 0.00269024: 753 753:racket, racquet


[bhpatray@hyd-bhpatray-l:/mathworks/devel/sbs/31/bhpatray.Bdeepcoder.j2026869/tensorflow-2.9.2] ...                                                                                                                % bazel-bin/tensorflow/lite/examples/label_image/label_image --tflite_model ./mobilenet_v2_1.0_224.tflite --labels ./mobilenet_v1_1.0_224/labels.txt --image tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp --xnnpack_delegate=true --use_xnnpack=false
INFO: Loaded model ./mobilenet_v2_1.0_224.tflite
INFO: resolved reporter
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: invoked
INFO: average time: 5.372 ms
INFO: 0.911344: 653 653:military uniform
INFO: 0.0144661: 835 835:suit, suit of clothes
INFO: 0.00624739: 440 440:bearskin, busby, shako
INFO: 0.00296665: 907 907:Windsor tie
INFO: 0.00269024: 753 753:racket, racquet

**Comment by mohantym** [comment]
Ok @BhaskarsarmaP !
Thanks for the update. 
@sachinprasadhs !
Could you please look at this issue.
Thank you!

**Comment by BhaskarsarmaP** [comment]
Also tested on Debian 11.
Still got the same results.
Testing on ubuntu in progress.

% bazel-bin/tensorflow/lite/examples/label_image/label_image --tflite_model ./mobilenet_v2_1.0_224.tflite --labels ./mobilenet_v1_1.0_224/labels.txt --image tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp  --use_xnnpack=true
INFO: Loaded model ./mobilenet_v2_1.0_224.tflite
INFO: resolved reporter
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
XNNPACK delegate created.
INFO: Applied XNNPACK delegate.
INFO: invoked
INFO: average time: 10.333 ms
INFO: 0.911344: 653 653:military uniform
INFO: 0.0144661: 835 835:suit, suit of clothes
INFO: 0.00624739: 440 440:bearskin, busby, shako
INFO: 0.00296665: 907 907:Windsor tie
INFO: 0.00269024: 753 753:racket, racquet

[bhpatray@hyd-hnalla-x:/mathworks/devel/sbs/31/bhpatray.Bdeepcoder.j2026869/tensorflow_2_9_21] ...                                                                                            % bazel-bin/tensorflow/lite/examples/label_image/label_image --tflite_model ./mobilenet_v2_1.0_224.tflite --labels ./mobilenet_v1_1.0_224/labels.txt --image tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp --use_xnnpack=false
INFO: Loaded model ./mobilenet_v2_1.0_224.tflite
INFO: resolved reporter
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: invoked
INFO: average time: 5.167 ms
INFO: 0.911344: 653 653:military uniform
INFO: 0.0144661: 835 835:suit, suit of clothes
INFO: 0.00624739: 440 440:bearskin, busby, shako
INFO: 0.00296665: 907 907:Windsor tie
INFO: 0.00269024: 753 753:racket, racquet

**Comment by sachinprasadhs** [comment]
Disabling the `XNNPack` will make the operations to fallback to the default implementation which is resulting slower performance. 
If there no particular requirement to disable the `XNNPack` then you can build the Tensorflow Lite with build flag, which will enable the `XNNPACK` engine by default.
For all the details about XNNPACK including performance can be found [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/xnnpack/README.md).

**Comment by xiaotongniu** [comment]
> Also tested on Debian 11. Still got the same results. Testing on ubuntu in progress.
> 
> % bazel-bin/tensorflow/lite/examples/label_image/label_image --tflite_model ./mobilenet_v2_1.0_224.tflite --labels ./mobilenet_v1_1.0_224/labels.txt --image tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp --use_xnnpack=true INFO: Loaded model ./mobilenet_v2_1.0_224.tflite INFO: resolved reporter INFO: Created TensorFlow Lite XNNPACK delegate for CPU. XNNPACK delegate created. INFO: Applied XNNPACK delegate. INFO: invoked INFO: average time: 10.333 ms INFO: 0.911344: 653 653:military uniform INFO: 0.0144661: 835 835:suit, suit of clothes INFO: 0.00624739: 440 440:bearskin, busby, shako INFO: 0.00296665: 907 907:Windsor tie INFO: 0.00269024: 753 753:racket, racquet
> 
> [bhpatray@hyd-hnalla-x:/mathworks/devel/sbs/31/bhpatray.Bdeepcoder.j2026869/tensorflow_2_9_21] ... % bazel-bin/tensorflow/lite/examples/label_image/label_image --tflite_model ./mobilenet_v2_1.0_224.tflite --labels ./mobilenet_v1_1.0_224/labels.txt --image tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp --use_xnnpack=false INFO: Loaded model ./mobilenet_v2_1.0_224.tflite INFO: resolved reporter INFO: Created TensorFlow Lite XNNPACK delegate for CPU. INFO: invoked INFO: average time: 5.167 ms INFO: 0.911344: 653 653:military uniform INFO: 0.0144661: 835 835:suit, suit of clothes INFO: 0.00624739: 440 440:bearskin, busby, shako INFO: 0.00296665: 907 907:Windsor tie INFO: 0.00269024: 753 753:racket, racquet
-----------------------------
hello, i have the similar questions,  You Already solve it?
