### ISSUE TITLE
Nonquantized tflite model using tflite_model_maker

### ISSUE THREAD

**Issue by Deepakpy** [tensorflow/tensorflow#57532]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installation (pip package or built from source):
- TensorFlow library (version, if pip package or github SHA, if built from source):

### 2. Code

model.export(export_dir='.', tflite_filename='model_fp16.tflite', quantization_config=config)
How to convert the trained model to tflite which is not quantized for models trained using tmm.

#### Option A: Reference colab notebooks

1)  Reference [TensorFlow Lite Model Colab]: https://www.tensorflow.org/lite/models/modify/model_maker/object_detection(https://colab.research.google.com/gist/ymodak/0dfeb28255e189c5c48d9093f296e9a8/tensorflow-lite-debugger-colab.ipynb): Demonstrate how to convert your TF model to a TF Lite model (with quantization, if used) and run TFLite Inference (if possible).

**Comment by mohantym** [comment]
Hi @Deepakpy !
Sorry for the late reply. 
I am not sure whether we can get a Non-quantised model if we pass quantization_config = None in
below line . By default ,  you will get a integer quantised model if you don't pass the quantization_config parameter. If you pass None, It might not work as expected ( You will be getting a Float32 model if you pass None).
 
`model.export(export_dir='.', tflite_filename='model_fp16.tflite', quantization_config=None)
`

@sachinprasadhs ! Could you comment on this query.

Thank you!

**Comment by sachinprasadhs** [comment]
Model Maker library applies a default `post-training quantization` techique when exporting the model.
But, you can change the options in the [tflite_model_maker.config.QuantizationConfig](https://www.tensorflow.org/lite/api_docs/python/tflite_model_maker/config/QuantizationConfig).
Also, refer to [this](https://www.tensorflow.org/lite/performance/post_training_quantization) post training quantization document for different options and below image to decide the best suited method for your case.
![image](https://user-images.githubusercontent.com/73069040/190330372-dc511020-c024-4822-ba61-ba1aac50c1c8.png)
