### ISSUE TITLE
`tf.pad` fails when executing in `tf.autodiff.ForwardAccumulator`

### ISSUE THREAD

**Issue by VictoriaGriffith** [tensorflow/tensorflow#57534]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

```shell
`tf.pad` fails when executing in `tf.autodiff.ForwardAccumulator` and throws `TypeError`. However, if we run `tf.pad` outside of `ForwardAccumulator` with the same input, it will pass.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

input_tensor = tf.random.uniform([3, 1, 1, 1], minval=2.0, maxval=3.0, dtype=tf.float32)
paddings = tf.random.uniform([4, 2], minval=0, maxval=5, dtype=tf.int64) 
mode = "CONSTANT"
constant_values = 0 
result = tf.pad(input_tensor, paddings, mode=mode, constant_values=constant_values, ) 
print(result.shape) # Pass

tangent = tf.reshape(tf.one_hot(1, tf.size(input_tensor), dtype=input_tensor.dtype), shape=input_tensor.shape)
with tf.autodiff.ForwardAccumulator(input_tensor, tangent) as acc:
    result = tf.pad(input_tensor, paddings, mode=mode, constant_values=constant_values, ) # Fail
```

### Relevant log output

```shell
(8, 3, 8, 4)
TypeError: Input 'y' of 'Sub' Op has type int64 that does not match type int32 of argument 'x'.
```
</details>

**Comment by tilakrayal** [comment]
@VictoriaGriffith,
Could you please try to cast the  arguments to **int32** before passing them to tf.pad. Could you please take a look at the [documentation](https://www.tensorflow.org/api_docs/python/tf/pad#args) of **tf.pad**
```
 tf.pad(
    tensor, paddings, mode='CONSTANT', constant_values=0, name=None
)
```
It seems that it supports dtype of **int32** args. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/c774c12def3aefacef9268ee48c0718a/untitled555.ipynb). Thank you!

**Comment by VictoriaGriffith** [comment]
Hi @tilakrayal , thanks for pointing out that `tf.pad` only accepts `int32`. However, the execution of `tf.pad` on `int64` paddings without gradient computation is successful:

```
import tensorflow as tf

input_tensor = tf.random.uniform([3, 1, 1, 1], minval=2.0, maxval=3.0, dtype=tf.float32)
paddings = tf.random.uniform([4, 2], minval=0, maxval=5, dtype=tf.int64) 
mode = "CONSTANT"
constant_values = 0 
result = tf.pad(input_tensor, paddings, mode=mode, constant_values=constant_values, ) 
print(result.shape) # Pass
```

Therefore, there seems to be an inconsistency of supported dtypes between the direct execution and gradient computation, and this can cause confusion because we often build a model and if the forward pass succeeds, we expect the back propagation to also work. I think it would be better if `tf.pad` either adds support for `int64` in gradient computation (and update doc) or disables the int64 in the direct computation.
