### ISSUE TITLE
I observe TfLiteXNNPackDelegateDelete is called when disable XNNPACK in Tensorflow Lite

### ISSUE THREAD

**Issue by rorocui** [tensorflow/tensorflow#57533]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.4

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Mobile device

ARMV7

### Python version

3.8

### Bazel version

cmake instead of bazel

### GCC/Compiler version

9.3.0

### Current Behaviour?

```shell
Built tensorflow lite with -DTFLITE_ENABLE_XNNPACK=OFF in cmake, and I got tensorflow-lite library as below.
I expected no XNNPack functions be called, am I right?
It looks like Macro DTFLITE_WITHOUT_XNNPACK is not working as expected.



Thanks.
roro
```

### Standalone code to reproduce the issue

```shell
None, just building issue.
```

### Relevant log output

```shell
./recipe-sysroot-native/usr/bin/arm-rdkmllib32-linux-gnueabi/arm-rdkmllib32-linux-gnueabi-readelf -a image/usr/lib/libtensorflow-lite.so |grep XNNPack
0025cd28  00008315 R_ARM_GLOB_DAT    00000000   TfLiteXNNPackDelegateD
0025ea44  00008516 R_ARM_JUMP_SLOT   00000000   TfLiteXNNPackDelegateO
0025ea48  00008416 R_ARM_JUMP_SLOT   00000000   TfLiteXNNPackDelegateC
   131: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND TfLiteXNNPackDelegateDele
   132: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND TfLiteXNNPackDelegateCrea
   133: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND TfLiteXNNPackDelegateOpti
  7898: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND TfLiteXNNPackDelegateDele
  7899: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND TfLiteXNNPackDelegateCrea
  7900: 00000000     0 NOTYPE  GLOBAL DEFAULT  UND TfLiteXNNPackDelegateOpti
```
</details>

**Comment by rorocui** [comment]
External delegate library has been used.

**Comment by rorocui** [comment]
My commit is 
commit 1923123d32ea41d92b70a27a3f6ecf0763b56f6c (HEAD, tag: v2.4.2)
Merge: f1c82005388 a0c809373f6
Author: Mihai Maruseac <mihaimaruseac@google.com>
Date:   Fri Jun 11 09:09:43 2021 -0700

    Merge pull request #50210 from tensorflow/geetachavan1-patch-1
    
    Disable io_test

Running cmake as below.
cmake -DCMAKE_TOOLCHAIN_FILE=../armv7.cmake -DBUILD_SHARED_LIBS=ON -DTFLITE_ENABLE_XNNPACK=OFF -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \../

**Comment by rorocui** [comment]
cat ../armv7.cmake 
# the name of the target operating system
SET(CMAKE_SYSTEM_NAME Linux)
#set(CMAKE_SYSTEM_PROCESSOR armv7)
set(CMAKE_SYSTEM_PROCESSOR armv7l)

# which C and C++ compiler to use
if (USE_CCACHE)
SET(CMAKE_C_COMPILER   ccache arm-linux-gcc)
SET(CMAKE_CXX_COMPILER ccache arm-linux-g++)
else()
SET(CMAKE_C_COMPILER   aarch64-linux-gcc)
SET(CMAKE_CXX_COMPILER aarch64-linux-g++)
endif()

**Comment by mohantym** [comment]
Hi @rorocui !
Sorry for the late reply. Could you check in 2.8/2.9 and let us know.
Thank you!

**Comment by rorocui** [comment]
That is fine, not urgent issue, and I could definitely try newer version, and will let you know.
I recall I tried newer version, and I hit build failure somehow.
Will provide you details later on.

**Comment by mohantym** [comment]
Hi @rorocui !
Sorry for the late response.
Could you confirm that this behaviour is still replicating  in 2.8/2.10 version.
Thank you!

**Comment by rorocui** [comment]
Hi,

I am on vocation this week, could try that next week.

Roro

**Comment by mohantym** [comment]
Hi @rorocui !
Could you confirm whether issue is resolved or not . 
Thank you!

**Comment by rorocui** [comment]
hi, Mohantym

Sorry for late response, I am tight with something, and I can't verify that in newer version now.
Might do that later on, but no sure when.
I am ok if you want to close this, since I have modified the cmake file and disable xnnpack dependency in v2.4.3.

Thanks.
Roro

**Comment by pkgoogle** [comment]
Hi @rorocui, let us know if you are able to test with a newer version, if not please close if you are satisfied with your current resolution.

**Comment by rorocui-brcm** [comment]
Current solution works perfectly for me, so I am going to close this ticket as Canceled.
Thank you for your attention and help.
