### ISSUE TITLE
Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found

### ISSUE THREAD

**Issue by isimsizolan** [tensorflow/tensorflow#57531]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

No

### OS Platform and Distribution

windows 10

### Python version

3.10

### CUDA/cuDNN version

8.1

### GPU model and memory

A5000 

### Current Behaviour?

```shell
After fresh installition of windows 10 and gpu driver, 

I have followed this installition -> https://www.tensorflow.org/install/pip?hl=en#windows-native

Created venv using conda create --name tf python=3.9
Then activated venv and used command conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
Then used, pip install tensorflow

tensorflow successfully detects GPU, however when before starting to training, it gave cudart64_110.dll not found error. I confirmed that cudart64_110.dll is exist inside virtual env in local path "Library\bin"
```

### Standalone code to reproduce the issue

```shell
conda create --name tf python=3.9
conda activate tf
conda install -c conda-forge cudatoolkit=11.2 cudnn=8.1.0
pip install tensorflow

train any word2vec/lstm model and error pops
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@isimsizolan,
There are at least 3 possible scenarios:


```
1. You need to install the MSVC 2019 redistributable.
2. Your CPU does not support AVX2 instructions.
3. Your CPU/Python is on 32 bits.
4. There is a library that is in a different location/not installed on your system that cannot be loaded.
```

Also pip install tensorflow will install a version thats compatible with GPU and CPU. So it gives you that warning message.
If you don't want to see warning messages and want to install the CPU only version, you could - pip install tensorflow-cpu that's a smaller wheel file for the CPU only version. 

Also please take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/57103) with a similar error. 

Thank you!
