### ISSUE TITLE
Saving tensorflow logs to a log file in python

### ISSUE THREAD

**Issue by thomasjv799** [tensorflow/tensorflow#57553]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

tf 2.2

### Custom Code

No

### OS Platform and Distribution

Windows 10

### Python version

3.7

### Current Behaviour?

```shell
While running a script that uses tf, it prints some logs such as info and warning that comes from inside the tensorflow library. Instead of printing this on console how can a user save it into a seperate log file and another log file for other modules. That is saving logs of tensorflow alone into one file and the python logging as per user preference.
```

### Standalone code to reproduce the issue

```shell
import logging

# get TF logger
log = logging.getLogger('tensorflow')
log.setLevel(logging.DEBUG)

# create formatter and add it to the handlers
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

# create file handler which logs even debug messages
fh = logging.FileHandler('tensorflow.log')
fh.setLevel(logging.DEBUG)
fh.setFormatter(formatter)
log.addHandler(fh)
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @wanderer799 !

You can save the command line outputs directly to a log file through below command beside above code snippet. 
`python3 training.py > output.log 
`
Feel free to explore other options from  [ tf.compat.v1.logging ](https://www.tensorflow.org/api_docs/python/tf/compat/v1/logging)  ( like saving logs in each n epochs etc) too.
[Reference.
](https://stackoverflow.com/a/60841276/11530462)
Thank you!

**Comment by wanderer799** [comment]
Thanks for this info. 

The Problem is I am making a module/package from scratch so it will have its own logging. What I need is that there should be two log file one with tensorflow.log and package.log . So I have to set this up inside the main python file on how the logs of tensorflow should be collected and saved.

**Comment by mohantym** [comment]
@wanderer799 !

You can just use a logging function either from python/tf.compat.v1.logging in the package/module to call it by default when some functions are used in the main file save it into package.log . You can use the same logging function in main.py file to save it into tf.log . Attached a sample code below to explain above context.
```

# package.py
class package_1()
   def __init___():
      # take some params and initialize
   def log_data():
     logging.basicConfig(filename = 'package.log',   # confi
                    level = logging.WARNING,
                    format = '%(asctime)s:%(levelname)s:%(name)s:%(message)s')
    #error logs.   
    #error warnings.  
     
  def process_1():
      #some logic     
      log_data() # call the logging function to log warning , errors  etc.   

process_1()
  
#main.py


import tensorflow as tf

def log_data():
     logging.basicConfig(filename = 'package.log',   # confi
                    level = logging.WARNING,
                    format = '%(asctime)s:%(levelname)s:%(name)s:%(message)s')
    #error logs.   
    #error warnings.  
     
ob_test = package_1()
package_1.process_1() # while using functions of package_1 it logged the data for respective package
log_data()
```
Attached relevant [thread](https://machinelearningmastery.com/logging-in-python/) for reference.

Thank you!

**Comment by wanderer799** [comment]
Thanks for this, it helped me though the issue with tensorflow, where its logs and all get displayed in my console is still there, its not able to save it into a file. 

Say for eg: when I import tensorflow
![image](https://user-images.githubusercontent.com/58871163/189281272-2dc6e669-46a0-45d8-ad5d-c5537fc05e63.png)

this log warnings pop up, I just want it to be saved to a file.

As of now I am using sys.stderr to collect the messages coming into the console and redirecting it into a file.

A better solution would be appreciated, Correct me if I am misunderstanding the above solution.

**Comment by mohantym** [comment]
Hi @gadagashwini ! 
Could you look at this issue.
Thank you!

**Comment by gadagashwini** [comment]
Hi @wanderer799, You can use `tf.get_logger()` to get log details by setting log level. 

`tf.get_logger().setLevel('WARN')`

```
_level_names = {
    FATAL: 'FATAL',
    ERROR: 'ERROR',
    WARN: 'WARN',
    INFO: 'INFO',
    DEBUG: 'DEBUG',
}
```
Thank you!

**Comment by wanderer799** [comment]
Can I use tf.get_logger() to store the logs from tensorflow into a seperate
log file rather than making it display on the console?

**Comment by gadagashwini** [comment]
Hi @wanderer799, `tf.get_logger()` used to get the logger instance. Thank you!

**Comment by wanderer799** [comment]
I tried like this

```python
import tensorflow as tf

tf_logs = tf.get_logger()
fh = logging.FileHandler("tf.log")
tf_logs.addHandler(fh)
```

Though the file is getting created its empty and all the warnings are shown in the console itself.

**Comment by gowthamkpr** [comment]
@thomasjv799 Just trying to understand why do you need to log all the warning including import warning? Can you please explain the use case. Thanks!!

**Comment by thomasjv799** [comment]
I am trying to build a python package that mainly uses tensorflow models for predictions. In order to see the progress tqdm is used so that we can see the progress bar in the console. So when I run .py file, all the tensorflow warnings and such comes into the console mainly CUDA warnings and all. For the package part I am using a logging module and its gets saved to a file. I wanna at the same also record the tensorflow warnings and errors like the same way into a file for future reference.

In this way I will will two log files, one log file from my package and the other log file will contain only tensorflow logs. 

Right now I am suppressing the tensorflow messages by raising the log levels as below:
```python
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
```
However what I want is a console where there is no tensorflow warnings or such and gets saved to a seperate log file.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
