### ISSUE TITLE
Why are tensors used after they are freed in a gpu sync operation?

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#57552]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

source

### Tensorflow Version

2.8

### Custom Code

Yes

### OS Platform and Distribution

Linux

### Mobile device

No

### Python version

3.8

### Current Behaviour?

Why are tensors used after they are freed in a gpu sync operation?
example in softmax_op_gpu.cu.cc
```shell
  void Compute(OpKernelContext* context) override {
      ............
      Tensor max_logits;
      Tensor sum_probs;
      OP_REQUIRES_OK(context,
                     context->allocate_temp(DataTypeToEnum<T>::value,
                                            softmax_out->shape(), &max_logits));

      typedef typename softmax_traits<T>::accumulator_type acc_type;
      OP_REQUIRES_OK(context,
                     context->allocate_temp(DataTypeToEnum<acc_type>::value,
                                            softmax_out->shape(), &sum_probs));

        .................
        TF_CHECK_OK(GpuLaunchKernel(
            GenerateNormalizedProb<T, acc_type, kUnroll>, numBlocks,
            numThreadsPerBlock, 0, cu_stream,
            reinterpret_cast<const T*>(logits_in_.flat<T>().data()),
            reinterpret_cast<const acc_type*>(
                sum_probs.flat<acc_type>().data()),
            reinterpret_cast<const T*>(max_logits.flat<T>().data()),
            const_cast<T*>(softmax_out->flat<T>().data()), rows, cols, log_));
        ....................
    }
  }
```

### Standalone code to reproduce the issue

1. ```max_logits ```and ```sum_probs``` will be free when ```Compute``` function over, because they are temporary variant.
2. ```GpuLaunchKernel``` will async use ```max_logits``` and ```sum_probs``` in kernel launch. 
So ```max_logits ```and ```sum_probs``` maybe used after they are freed.

Tensor is a ref and TensorBuffer guaranteed memory/GPU memory is used. but in the above example, when function over and temporary tensor destruct, GPU Memory in TensorBuffer will be freed to BFCAllocator and in sametime this GPU Memory maybe be allocated by other GPU op.
we move Administrative rights from TensorBuffer to BFCAllocator.  Is it the right way?

### Relevant log output

```shell
void Compute(OpKernelContext* context) override {
      ............
      Tensor max_logits;
      Tensor sum_probs;
      OP_REQUIRES_OK(context,
                     context->allocate_temp(DataTypeToEnum<T>::value,
                                            softmax_out->shape(), &max_logits));

      typedef typename softmax_traits<T>::accumulator_type acc_type;
      OP_REQUIRES_OK(context,
                     context->allocate_temp(DataTypeToEnum<acc_type>::value,
                                            softmax_out->shape(), &sum_probs));

        .................
        TF_CHECK_OK(GpuLaunchKernel(
            GenerateNormalizedProb<T, acc_type, kUnroll>, numBlocks,
            numThreadsPerBlock, 0, cu_stream,
            reinterpret_cast<const T*>(logits_in_.flat<T>().data()),
            reinterpret_cast<const acc_type*>(
                sum_probs.flat<acc_type>().data()),
            reinterpret_cast<const T*>(max_logits.flat<T>().data()),
            const_cast<T*>(softmax_out->flat<T>().data()), rows, cols, log_));
        ....................
         TensorRef ref0(max_logits);
         TensorRef ref1(sum_probs);
         auto done = [ref0, ref1](){
           ref0.Unref;
           ref1.Unref;
         };
         device->event_mgr->ThenExecute(device->stream(), done);
    }
  }
```
I found the same behavior in many GPU sync operations, is this the correct approach?
</details>

**Comment by cuiguoxin** [comment]
@zhaozheng09 hi，I also don't understand this. When I wrote my custom gpu kernel and the kernel invoked the allocate_temp method,  the tensor value will be overwritten by other kernel which would cause an error in my program. Has there been any progress on this issue?

**Comment by cuiguoxin** [comment]
@sushreebarsa Please check this question. I think it is very likely a bug.
