### ISSUE TITLE
Not enough flexibility to choose actual accelerator in CoreML delegate

### ISSUE THREAD

**Issue by hguihot** [tensorflow/tensorflow#57566]
Only [two options exist](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/coreml/coreml_delegate.h) when creating a CoreML delegate:
```
typedef enum {
  // Create Core ML delegate only on devices with Apple Neural Engine.
  // Returns nullptr otherwise.
  TfLiteCoreMlDelegateDevicesWithNeuralEngine,
  // Always create Core ML delegate
  TfLiteCoreMlDelegateAllDevices
} TfLiteCoreMlDelegateEnabledDevices;
```

These don't quite fit what's possible with CoreML, [as documented here](https://developer.apple.com/documentation/coreml/mlcomputeunits?changes=latest_major&language=objc). Ideally, we should have a way to specify whether we want to use any accelerator (including neural engine), CPU only, or CPU and GPU (excluding neural engine). iOS 16 will also introduce a way to use CPU and neural engine, i.e. excluding GPU.

Currently the CoreML delegate always uses `MLComputeUnitsAll` in [coreml_executor.mm](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/coreml/coreml_executor.mm).

**Comment by mohantym** [comment]
Hi @hguihot !
You can instantiate the CoreML delegate instance and use it in interpreter option . If it does not support Core ML delegate for any op , It should fall to available GPU delegate or run on CPU mode. 

Please check the below code to run with reference to above statement on fallback policy.

```
    let coreMLDelegate = CoreMLDelegate()
    var delegate = CoreMLDelegate()

    var interpreter: Interpreter

    // Core ML delegate will only be created for devices with Neural Engine
    if coreMLDelegate != nil { # Try with neural engine
      interpreter = try Interpreter(modelPath: modelPath,
                                    delegates: [coreMLDelegate!])
    } 
    else if  {                # else fall back to metal delegate
     delegate = MetalDelegate()
    }

    
    else { # else fallback to cpu mode
      interpreter = try Interpreter(modelPath: modelPath)
    }




```
If you want to run without Neural engine , You can follow below syntax.
```
    var options = CoreMLDelegate.Options()
    options.enabledDevices = .all
    let coreMLDelegate = CoreMLDelegate(options: options)!
    let interpreter = try Interpreter(modelPath: modelPath,
                                      delegates: [coreMLDelegate])
```
       
Could you check  this documentation on [CoreML delegate](https://www.tensorflow.org/lite/performance/coreml_delegate#trying_the_core_ml_delegate_on_your_own_model) for reference and let us know whether it resolves your query.

Thank you!

**Comment by hguihot** [comment]
What you described is a bit different from what I meant.

For example, there is currently no way to use CoreML with only CPU or GPU (not neural engine). This is different from using the Metal delegate, i.e. one may want to use the CoreML delegate explicitly.

In iOS16, there will be no way (with the current interface) to use CoreML with only CPU or neural engine (not GPU).

Basically, I think the `TfLiteCoreMlDelegateEnabledDevices` enum should more closely match the iOS [MLComputeUnits enum](https://developer.apple.com/documentation/coreml/mlcomputeunits?changes=latest_major&language=objc).

**Comment by mohantym** [comment]
Ok @hguihot !
Thanks for the clarification . @sachinprasadhs ! Could you look at this feature request.

**Comment by impjdi** [comment]
Hi Sachin,

This is a delegate I have no knowledge about.  This is probably an issue for @miaout17

**Comment by sachinprasadhs** [comment]
@hguihot , This seems like a minor change, would you be interested to contribute by creating a PR?.Thanks!

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
