### ISSUE TITLE
Where can I find the list of ops from TensorFlow's Python API supported by default in TensorFlowLite

### ISSUE THREAD

**Issue by drubinstein** [tensorflow/tensorflow#57561]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### Current Behaviour?

Hi. I'm trying to figure out what from TensorFlow's Python API is supported by TensorFlowLite. I know there's a list of [supported MLIR ops](https://www.tensorflow.org/mlir/tfl_ops), but that is still one level of indirection from the Python API. I've also found other locations where the builtins are specified e.g. in the [generated schema](https://github.com/tensorflow/tensorflow/blob/681b73dd2e4216d883007139a53beb6c2f60cf94/tensorflow/lite/schema/schema_generated.h#L1231) or say the kernels specified in [tensorflow/lite/kernels/BUILD](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/BUILD#L562) but again, I'm not sure how these names map to TensorFlow's Python API.

Is there a location in the code or a script I can run to find the mapping?

### Standalone code to reproduce the issue

```shell
n/a
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @drubinstein !
You can find the by default lite supported ops from[ here](https://www.tensorflow.org/lite/guide/ops_compatibility) . Select ops list can be found [here](https://www.tensorflow.org/lite/guide/ops_select). To use MLIR ops in lite model , Please use below flags during model to TFLite conversion.

> converter.experimental_new_converter = True
> &  
> converter.experimental_new_quantizer = True

Thank you!

**Comment by drubinstein** [comment]
Thanks @mohantym. While that first link has a lot of good information, it doesn't have quite what I'm looking for. The section [Supported operations and restrictions](https://www.tensorflow.org/lite/guide/ops_compatibility#supported_operations_and_restrictions) links you to the list of supported MLIR ops  I linked to in my original description saying that it provides the `full list of Operations and Limitations`, but that doesn't necessarily translate back to the regular TensorFlow Python API (where I would build a model before conversion). Later in the TensorFlow Lite and TensorFlow operator compatibility page you linked to first, it contains some ops but only with the description that those ops are often fused or optimized out and the list is non-exhaustive.

The select ops page you linked to [contains a page](https://www.tensorflow.org/lite/guide/op_select_allowlist) with the type of information I'm looking for, an exhaustive list of TensorFlow ops supported by TFLite.

**Comment by mohantym** [comment]
Hi @sachinprasadhs !
Could you look at this query.
Thank you!

**Comment by sachinprasadhs** [comment]
I do not think we have builtin ops listed anywhere apart from the sources which is already been linked in the issue above.
But, if you want to check if certain op is supported or not during conversion,  you can include only `tf.lite.OpsSet.TFLITE_BUILTINS` in your converter, if that op is not available in TFLITE builtin, it will throw error.
```
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS]
```

**Comment by drubinstein** [comment]
Thanks @sachinprasadhs . I understand and thanks for the response.
