### ISSUE TITLE
Cannot deserialize keras model using __add__

### ISSUE THREAD

**Issue by froody** [tensorflow/tensorflow#57574]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

v2.9.1-0-gd8ce9f9c301 2.9.1

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.9.13

### Bazel version

5.0.0

### GCC/Compiler version

GCC 9.2

### CUDA/cuDNN version

11.7/8.4.1.50

### GPU model and memory

A100-SXM4-40GB

### Current Behaviour?

When calling `tf.keras.models.load_model("/tmp/my_model")` I get

```
File "/mnt/disks/data/src/conda/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 1078, in op_dispatch_handler
    result = api_dispatcher.Dispatch(args, kwargs)
TypeError: Missing required positional argument
```

I expected the model to load successfully. I trained my model for 2 days and now I can't load it.

### Standalone code to reproduce the issue

```python
import tensorflow as tf
from tensorflow.keras.layers import Dense, Layer

class MyLayer(Layer):
    def __init__(self):
        super().__init__()
        self.dense = Dense(512)
    def __call__(self, X):
        short = X
        X = self.dense(X)
        X = short + X
        return X


def main():
    model = tf.keras.Sequential([MyLayer()])
    model.build([None, 512])
    model.save("/tmp/my_model")

    tf.keras.models.load_model("/tmp/my_model")

if __name__ == "__main__":
    main()
```

### Relevant log output

```shell
api_dispatcher.Dispatch=<bound method PyCapsule.Dispatch of <Dispatch(_add_dispatch): >, args=(<tf.Tensor 'Placeholder:0' shape=(None, 512) dtype=float32>,), kwargs={}
Traceback (most recent call last):
  File "/mnt/disks/data/src/repro.py", line 24, in <module>
    main()
  File "/mnt/disks/data/src/repro.py", line 21, in main
    tf.keras.models.load_model("/tmp/my_model")
  File "/mnt/disks/data/src/conda/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/mnt/disks/data/src/conda/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 1078, in op_dispatch_handler
    result = api_dispatcher.Dispatch(args, kwargs)
TypeError: Missing required positional argument
```
</details>

**Comment by froody** [comment]
Using `tf.keras.layers.Add` results in a different error:

```python
class MyLayer(Layer):
    def __init__(self):
        super().__init__()
        self.dense = Dense(512)
        self.add = Add()
    def __call__(self, X):
        short = X
        X = self.dense(X)
        X = self.add([short , X])
        return X
```

```shell
Traceback (most recent call last):
  File "/mnt/disks/data/src/repro.py", line 24, in <module>
    main()
  File "/mnt/disks/data/src/repro.py", line 21, in main
    tf.keras.models.load_model("/tmp/my_model")
  File "/mnt/disks/data/src/conda/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/mnt/disks/data/src/conda/lib/python3.9/site-packages/keras/layers/merging/base_merge.py", line 115, in call
    raise ValueError(
ValueError: Exception encountered when calling layer "add" (type Add).

A merge layer should be called on a list of inputs. Received: inputs=Tensor("Placeholder:0", shape=(None, 512), dtype=float32) (not a list of tensors)

Call arguments received by layer "add" (type Add):
  • inputs=tf.Tensor(shape=(None, 512), dtype=float32)
```

**Comment by sushreebarsa** [comment]
@froody Could you please confirm if this issue is resolved for you?
Thank you!

**Comment by froody** [comment]
@sushreebarsa No the issue is not resolved, I still can't load a model trained with the original method (subclassing Layer/Model)

**Comment by sushreebarsa** [comment]
@froody 
I was able to replicate the issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/8dc86c2d722124d3fc70fd9e439ddff6/untitled122.ipynb) here.
This issue seems to be Keras issue.  Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) as Keras development is fully moving to [github.com/keras-team/keras](http://github.com/keras-team/keras). All issues and PRs related to keras will be addressed in that repo.
To know more see this TF forum discussion ; 
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
