### ISSUE TITLE
Tried to export a function which references 'untracked' resource Tensor

### ISSUE THREAD

**Issue by dimitreOliveira** [tensorflow/tensorflow#57573]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8.2

### Custom Code

Yes

### OS Platform and Distribution

Colab

### Python version

3.7

### Current Behaviour?

```shell
I am not able to export models with a custom signature that contains preprocessing layers as part of the model graph.

This issue happens for different kinds of layers, in my case it was `Normalization`, `IntegerLookup` and `StringLookup`.
```

### Standalone code to reproduce the issue

```shell
Link for colab: https://colab.research.google.com/drive/15pPBp8uVBMpdHscljUz1kk_OylDp43-G?usp=sharing


def model_fn():
    age_input = L.Input(shape=(1,), dtype=tf.float32, name='age')
    sex_input = L.Input(shape=(1,), dtype=tf.float32, name='sex')
    cp_input = L.Input(shape=(len(cp_vocab),), dtype=tf.float32, name='cp')
    thal_input = L.Input(shape=(len(thal_vocab),), dtype=tf.float32, name='thal')

    concat_inputs = L.Concatenate()([age_input, sex_input, cp_input, thal_input])
    x = L.Dense(32, activation="relu")(concat_inputs)
    x = L.Dropout(0.5)(x)
    output = L.Dense(1, activation="sigmoid")(x)

    return tf.keras.models.Model(inputs=[age_input, sex_input, cp_input, thal_input], outputs=output)

model = model_fn()

def custom_signature(model):
    input_signature = [
        tf.TensorSpec([1,], tf.int64, name="age"), 
        tf.TensorSpec([1,], tf.int64, name="sex"), 
        tf.TensorSpec([1,], tf.int64, name="cp"), 
        tf.TensorSpec([1,], tf.string, name="thal")
    ]
    @tf.function(input_signature=[input_signature])
    def serving_fn(input):
        age_processed = age_preprocessing(input[0])
        sex_processed = tf.cast(sex_preprocessing(input[1]), 
                                dtype=tf.float32)
        cp_processed = cp_preprocessing(input[2])
        thal_processed = thal_preprocessing(input[3])

        preprocessed_inputs = {"age": age_processed, 
                              "sex": sex_processed, 
                              "cp": tf.expand_dims(cp_processed, 0), 
                              "thal": tf.expand_dims(thal_processed, 0)}
        probs = model(preprocessed_inputs)
        return {"probs": probs}

    return serving_fn

tf.saved_model.save(
        obj=model,
        export_dir="signature_model/",
        signatures={
            "serving_default": custom_signature(model)
        },
    )
```
```


### Relevant log output

```shell
AssertionError: Tried to export a function which references 'untracked' resource Tensor("3629:0", shape=(), dtype=resource). TensorFlow objects (e.g. tf.Variable) captured by functions must be 'tracked' by assigning them to an attribute of a tracked object or assigned to an attribute of the main object directly.

 Trackable Python objects referring to this tensor (from gc.get_referrers, limited to two hops):
<tensorflow.python.ops.lookup_ops.StaticHashTable object at 0x7f1d051b2e10>
```
</details>

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to replicate the issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/5652b435efe59da56d28842039e99d1a/sample-signature-error.ipynb#scrollTo=fnUBcfyKhrtT) here. Thank you!

**Comment by gowthamkpr** [comment]
Creating a custom layer with the lookup transformation and then adding that layer to my model will help you solve the issue. Please take a look at solution provided [here](https://stackoverflow.com/questions/63399368/error-with-exporting-tf2-2-0-model-with-tf-lookup-statichashtable-for-serving). Thanks!

**Comment by dimitreOliveira** [comment]
Hi @gowthamkpr , this solution has not solved the issue, here is another [colab link](https://colab.research.google.com/drive/1JenGogaWOgnCr6NkDqP29pT8M9kLxIuC?usp=sharing) that has a more informative code.

Also that solution that uses a custom `StaticHashTable` is not ideal, since `StringLookup` and `IntegerLookup` have different output options that are not easily reproducible with the hash table.

As you can see in the colab link I have tried to adapt that code to match the proposed solution but this still does not work, I am not sure if I am missing something here. Let me know if I can provide more information.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
