### ISSUE TITLE
Memory allocation

### ISSUE THREAD

**Issue by Joeyzhouqihui** [tensorflow/tensorflow#57582]
Hi sorry for bothering. I am just wondering when using multiple streams for model inference. Will the cached memory blocks been shared by different streams? Or they are not shared like in pytorch?

**Comment by tilakrayal** [comment]
@Joeyzhouqihui,
Could you please fill the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose) to analyse the issue.
Also please try to use [tf.config.experimental.get_memory_info](https://www.tensorflow.org/api_docs/python/tf/config/experimental/get_memory_info) to get memory information for the chosen device, as a dict.

```
tf.config.experimental.get_memory_info(
    device
)
```

Thank you!
