### ISSUE TITLE
the edtion of TensorRT for TF-TRT

### ISSUE THREAD

**Issue by JZZ-NOTE** [tensorflow/tensorflow#57581]
<img width="936" alt="image" src="https://user-images.githubusercontent.com/75348594/187877984-f321d97a-92a1-4953-a0fa-703626c106a4.png">
On the website, I can know the edtion of cuda and cudnn, but how can I know the edtion of TensorRT?

**Comment by sushreebarsa** [comment]
@JZZ-NOTE If you want to use GPU support in Tensor-RT you can choose specific cuda and cudnn accordingly.
Could you please follow the instructions from [here](https://docs.nvidia.com/deeplearning/frameworks/tf-trt-user-guide/index.html#benefits). Thank you!
