### ISSUE TITLE
Documentation and error messages for tf.tile, tf.constant leave a lot to be desired

### ISSUE THREAD

**Issue by yaccman** [tensorflow/tensorflow#5758]
I noticed that a protocol buffer did the equivalent of
    tf.tile( x, [] )
and wondered what that actually produced (the documentation was completely unhelpful).  So I tried
    x = tf.Variable([1.,2.,3.,4.])
    y = tf.tile(x,tf.constant(2))
to get started, and got the message "ValueError: Shape () must have rank 1".  So I tried
    y = tf.tile(x,tf.constant([2]))
and got the same message(!).  tf.rank(tf.constant([2])) of course returned the value 1, so the message made no sense at all to me.
In my struggle to get an acceptable empty tensor, I tried
    x = tf.constant(shape=[],dtype="int32")
This produced the memorable message "TypeError: constant() takes at least 1 argument (2 given)"
I eventually discovered that tf.tile returns 1 copy of its tensor when the input is an empty list.  It would have been so helpful if the documentation would have just stated this fact...

Searching for tf.tile bugs produced a number of references to the documentation and a lot of hits relating to roofs.

My OS is Ubuntu 64-bit, TF version .11

**Comment by yaccman** [comment]
As a PS, one would expect that tiling with a multiple of 0 would give an empty tensor as result.  But in fact, tf.tile(1.,[0]) produces an error "Shape () must have rank 1".  And again, tf.rank([0]) returns 1.

**Comment by prb12** [comment]
I'm struggling to follow your confusing issue report, but ... 

With TF 0.11, I get the following output:
```
>>> x = tf.Variable([1.,2.,3.,4.])
>>> y = tf.tile(x,tf.constant(2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/pbar/tensorflow.0.11rc2/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2859, in tile
    name=name)
  File "/usr/local/google/home/pbar/tensorflow.0.11rc2/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/google/home/pbar/tensorflow.0.11rc2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2382, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/google/home/pbar/tensorflow.0.11rc2/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1783, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/google/home/pbar/tensorflow.0.11rc2/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1789, in _TileShape
    multiples_shape = op.inputs[1].get_shape().with_rank(1)
  File "/usr/local/google/home/pbar/tensorflow.0.11rc2/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 650, in with_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape () must have rank 1
```
...as per the [documentation](https://www.tensorflow.org/versions/r0.11/api_docs/python/array_ops.html#tile).  You are passing a scalar and the documentation states that the `multiples` argument must be 1-D.
```
>>> y = tf.tile(x, tf.constant([2]))
>>> 
```
Seems to work for me?

> x = tf.constant(shape=[],dtype="int32")
This produced the memorable message "TypeError: constant() takes at least 1 argument (2 given)"
The signature of `tf.constant` is:
```
def constant(value, dtype=None, shape=None, name="Const"):
```
The [documentation](https://www.tensorflow.org/versions/r0.11/api_docs/python/constant_op.html#constant) states:
```
  Args:
    value:     A constant value (or list) of output type `dtype`.
    dtype:     The type of the elements of the resulting tensor.
    shape:     Optional dimensions of resulting tensor.
    name:      Optional name for the tensor.
  Returns:
    A Constant Tensor.
```
i.e. you *must* pass an argument for the positional argument `value`, and the keyword argument `dtype`

This error message is lamentable, but not TensorFlow's fault. Consider the following simple Python program:
```
>>> def foo(value, dtype=None, shape=None): return value
>>> foo
<function foo at 0x7f2f7ae0bb90>
>>> foo(dtype=2, shape=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: foo() takes at least 1 argument (2 given)
```

> tf.tile(1.,[0]) produces an error "Shape () must have rank 1".

The args to [tf.tile](https://www.tensorflow.org/versions/r0.11/api_docs/python/array_ops.html#tile) are as follows:
```
Args:
input: A Tensor. 1-D or higher.
multiples: A Tensor. Must be one of the following types: int32, int64. 1-D. Length must be the same as the number of dimensions in input
name: A name for the operation (optional).
```
Your error is because you passed a scalar as the input, which is required to be 1-D or higher.

> As a PS, one would expect that tiling with a multiple of 0 would give an empty tensor as result.
```
>>> with tf.Session() as sess: tf.tile([1], [1]).eval()
... 
array([1], dtype=int32)
>>> with tf.Session() as sess: tf.tile([1], [0]).eval()
... 
array([], dtype=int32)
```
...as it does?

Please feel free to reopen if this doesn't solve your problem.

**Comment by yaccman** [comment]
Ah, it makes more sense now.  How in the world am I supposed to look at that traceback and realize that the message relates to tf.constant rather than tf.tile?
And I probably should have realized that the goofy message came from Python...
Thanks for your help...

**Comment by prb12** [comment]
> Ah, it makes more sense now. How in the world am I supposed to look at that traceback and realize that the message relates to tf.constant rather than tf.tile?

In *this* case, the source line in the stack backtrace refers to 'multiples_shape' and 'op.inputs[1]' so it's relatively straightforward.... but I agree that in general, error messages like this are often hard to grok!   
```
  File "/usr/local/google/home/pbar/tensorflow.0.11rc2/local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1789, in _TileShape
    multiples_shape = op.inputs[1].get_shape().with_rank(1)
  File "/usr/local/google/home/pbar/tensorflow.0.11rc2/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 650, in with_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
```
Personally, my usual course of action would be to just head to `[tensorflow/python/ops/array_ops.y:1789](https://github.com/tensorflow/tensorflow/blob/r0.11/tensorflow/python/ops/array_ops.py#L1789)'
