### ISSUE TITLE
Pose estimation line mismatch

### ISSUE THREAD

**Issue by IBSApple** [tensorflow/tensorflow#57580]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

 pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML', 'Metal']

### Custom Code

Yes

### OS Platform and Distribution

MacOS

### Mobile device

iPhone X

### Current Behaviour?

```shell
When I am performing some exercise pose estimation model lines display cross.
```

### Standalone code to reproduce the issue

```shell
When I am performing Squat sometimes lines display cross.
```

### Relevant log output

_No response_</details>

**Comment by IBSApple** [comment]
<img width="273" alt="Screenshot 2022-09-01 at 11 26 15 AM" src="https://user-images.githubusercontent.com/71369657/187842434-556a0c3b-46d8-433c-aff9-0d54f227186e.png">

**Comment by IBSApple** [comment]
How should I resolve this cross line issue?

**Comment by mohantym** [comment]
Hi @sachinprasadhs !
Could you look at this issue.
Thank you!

**Comment by IBSApple** [comment]
If I use only pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML']
then many error occure in code

**Comment by IBSApple** [comment]
??

**Comment by sachinprasadhs** [comment]
Could you please provide the reproducible code to replicate the issue. Thanks!
