### ISSUE TITLE
Tensorflow customized embedding not work on GPU

### ISSUE THREAD

**Issue by Iroski** [tensorflow/tensorflow#57583]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.3.0-rc2-23-gb36436b087 2.3.0

### Custom Code

No

### OS Platform and Distribution

Ubuntu 17.04

### Python version

3.7

### CUDA/cuDNN version

10.1 / 7.6.5

### GPU model and memory

Tesla-V100 32G

### Current Behaviour?

```shell
I made a tensorflow model like following:

class EnhancedEmbedding(tf.keras.layers.Embedding):
    def __init__(self, input_dim, output_dim, embeddings_initializer='uniform', embeddings_regularizer=None, activity_regularizer=None, embeddings_constraint=None, mask_zero=False, input_length=None, **kwargs):
        super().__init__(input_dim, output_dim, embeddings_initializer, embeddings_regularizer, activity_regularizer, embeddings_constraint, mask_zero, input_length, **kwargs)
        self.five=tf.constant(0.5)
        self.zero=tf.constant(0)
    
    def embedding(self,inputs):
        return super().call(inputs)
    
    def map_2(self,tokens):
        identifier=self.embedding(tokens[0])
        cur_word=self.embedding(tokens[2])
        return tf.cond(tf.equal(tf.shape(tokens[0]),self.zero),
                lambda: tf.squeeze(cur_word),
                lambda: tf.squeeze(tf.reduce_mean(identifier)*self.five+cur_word*self.five))


    def map_1(self,inputs):
        return tf.map_fn(fn=lambda x :self.map_2(x),elems=inputs,dtype=tf.float32)

    def call(self, inputs):
        final_embeddings=tf.map_fn(fn=lambda x:self.map_1(x),elems=inputs,dtype=tf.float32)

        return final_embeddings
```
```
class EnhancedModel(Model):
    def __init__(self,  embedding_dim, hidden_dim, vocab_size, label_size,seq_len, pretrained_weight):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.vocab_size = vocab_size
        self.embedding_dim = embedding_dim
        self.label_size = label_size
        self.activation = tf.keras.activations.tanh
        self.num_layers = 1

        self.embedding=EnhancedEmbedding(vocab_size,embedding_dim,embeddings_initializer=keras.initializers.Constant(pretrained_weight))
        self.encoder = Bidirectional(LSTM(hidden_dim, return_sequences=True,input_shape=(seq_len,embedding_dim)))
        self.pool=MaxPool1D(hidden_dim*2)
        self.decoder = Dense(self.label_size)

    def call(self, inputs):
        embeddings = self.embedding(inputs)
        embeddings=tf.reshape(embeddings,[-1,400,32])
        lstm_out = self.encoder(embeddings)
        lstm_out = tf.transpose(lstm_out, perm=[0,2,1])
        pool_out=self.pool(lstm_out)
        out = tf.squeeze(pool_out,[1])
        out = self.decoder(out)
        return out
```
Actually it is a model that cited from others. I only changed the embedding layer and the input.
the input is a RaggedTensor with shape(batch_size,400,3,None), and i use ``` and ```map_2``` function in ```EnhancedEmbedding``` to general final embedding for the following layers. Everything works fine except that the model is not work with GPU. I looked the GPU utilization using ```nvidia-smi``` and the result is about 5%. But CPU-Util is about 100%.

GPU can be used in the virtual env:
```
>>>tf.test.is_gpu_available()
>>>True
```
```


### Standalone code to reproduce the issue

```shell
the training code is here but it cannot be reproduced since the pretrained vectors, the training data are too large.

https://colab.research.google.com/drive/1qdo629GsnIdgbFpqTbIrwOaIHCsfwyJr?usp=sharing
```

### Relevant log output

_No response_</details>

**Comment by Iroski** [comment]
I tried one batch with batch_size=64 on my laptop.The env is: cpu=i7-12700H, tensorflow=2.9.1, cuda=11.6, cudnn=8.4.1.

The code for training is:
```
#both train_x and train_y are list
train_x_enc=tf.ragged.constant(train_x,dtype=tf.int32)
train_y=train_y=tf.convert_to_tensor(train_y,dtype=tf.int32)

with strategy.scope():
    tf.config.run_functions_eagerly(False)
    model = EnhancedModel(EMBEDDING_DIM, HIDDEN_DIM, MAX_TOKENS, LABELS,SEQ_LEN, pretrain_vectors)
    model.compile(optimizer=tf.optimizers.Adam(),loss=tf.keras.losses.SparseCategoricalCrossentropy(),metrics=['accuracy'])
    model.fit(train_x_enc,train_y)
```
I find that it take three minute to run a batch for one ecoch. CPU takes long time and GPU only be used(GPU-Util>50%) for several seconds. CPU-Util is about 20% and GPU is about 17% in most of time.

if I changed the code with ```tf.config.run_functions_eagerly(True)```, I find that the GPU-Util is above 80% all the time with CPU-Util=9%

**Comment by sushreebarsa** [comment]
@Iroski Could you please try with the latest TF version as older versions(2.3 or previous versions) are not actively supported and let us know if the issue still persists?
I tried to replicate the issue on colab and faced dependency issue. Please find the [gist](https://colab.research.google.com/gist/sushreebarsa/0dc00ffd10a709f2af83c387d615690f/untitled124.ipynb) here.
Thank you!

**Comment by Iroski** [comment]
> @Iroski Could you please try with the latest TF version as older versions(2.3 or previous versions) are not actively supported and let us know if the issue still persists? I tried to replicate the issue on colab and faced dependency issue. Please find the [gist](https://colab.research.google.com/gist/sushreebarsa/0dc00ffd10a709f2af83c387d615690f/untitled124.ipynb) here. Thank you!

@sushreebarsa Hi, I don't know if the cuda driver version must newer than the cudatoolkit in conda virtual environment. My cuda driver version is 10.2 and I tried the latest tensorflow 2.9 with cudatoolkit 11.2, but it shows that I cannot use my gpu and it's hard for me to update the driver, so I only use tensorflow 2.3

I don't know how I can share resource in colab so  I just put the resources on google drive [here](https://drive.google.com/drive/folders/1q2oXK4bbqeyWLC0we6lwrNEXsPILv8TB?usp=sharing) . Plz put the 'data' directory to the base dir of colab. 
Thanks!

**Comment by tiruk007** [comment]
@Iroski 
I tried to replicate the issue on colab and it crashes on gpu runtime. Could you please find the gists of [gpu](https://colab.research.google.com/gist/tiruk007/baca0f9d588f0bc6bf1552fa679003e2/57583.ipynb) runtime here? Please confirm the issue ?
Thank you!

**Comment by Iroski** [comment]
> @Iroski I tried to replicate the issue on colab and it crashes on gpu runtime. Could you please find the gist of [gpu](https://colab.research.google.com/gist/tiruk007/baca0f9d588f0bc6bf1552fa679003e2/57583.ipynb) runtime here? Please confirm the issue ? Thank you!

This may because the _train_x_ dataset is too large and when tranfer it to raggerTensor, it ultilize all the memory of the machine.
So I replaced the code 
```
train_x_enc=tf.ragged.constant(train_x,dtype=tf.int32)
train_y=tf.convert_to_tensor(train_y,dtype=tf.int32)
```
with 
```
train_x=train_x[:len(train_x)//2]
train_y=train_y[:len(train_y)//2]
train_x_enc=tf.ragged.constant(train_x,dtype=tf.int32)
train_y=tf.convert_to_tensor(train_y,dtype=tf.int32)
```
This solve the oom problem.
Thank you!

**Comment by tiruk007** [comment]
@gadagashwini 
 The issue was able to reproduce the issue on Colab using TF V2.10, Please find the gist [here](https://colab.research.google.com/gist/tiruk007/879bab427cf4e9e3ef54f677b48449d6/57583.ipynb) for reference .

Thank you!

**Comment by Iroski** [comment]
Hello, may I ask is there any latest development?
