### ISSUE TITLE
Load a model from a memory buffer using Tensorflow 2.x C api

### ISSUE THREAD

**Issue by aliericcantona** [tensorflow/tensorflow#57597]
Hi, 
I was wondering if there is a way to load 2.x model from memory buffer like GraphDef in v1

Thanks

**Comment by sushreebarsa** [comment]
@aliericcantona You may declare the function or model under @tf.function then get_concrete_function().graph.as_graph_def() to save and load as graphdef. For more information please refer [this](https://www.tensorflow.org/api_docs/python/tf/compat/v1/GraphDef#:~:text=If%20you%20would%20like%20to%20create%20a%20GraphDef%20in%20TF2%2C%20use%20tf.function%20and%20get_concrete_function) link. Thank you!

**Comment by aliericcantona** [comment]
I need through C-Api way not a python way. There is no description on that.

**Comment by gowthamkpr** [comment]
@aliericcantona Please take a look at the suggestion provided [here](https://github.com/tensorflow/tensorflow/issues/37570#issuecomment-679026648) to load the model from memory. Also please go through this [article](https://danishshres.medium.com/tensorflow-1-vs-tensorflow-2-c-api-d94982a5eb16) which demonstrates the difference between tensorflow C API 1.x and 2.0
