### ISSUE TITLE
Error running ci_build.sh on docker container mac.

### ISSUE THREAD

**Issue by abhitopia** [tensorflow/tensorflow#5759]
When I run following command to test the ci_build on my mac

`$ tensorflow/tools/ci_build/ci_build.sh CPU bazel test //tensorflow/learn/...`

I get following error - 

WORKSPACE: /Users/<username>/tensorflow
CI_DOCKER_EXTRA_PARAMS:
COMMAND: bazel test //tensorflow/learn/...
CI_COMMAND_PREFIX: ./tensorflow/tools/ci_build/builds/with_the_same_user ./tensorflow/tools/ci_build/builds/configured cpu
CONTAINER_TYPE: cpu
BUILD_TAG: tf_ci
  (docker container name will be tf_ci.cpu)

Building container (tf_ci.cpu)...
Sending build context to Docker daemon 222.7 kB
Step 1 : FROM ubuntu:14.04
 ---> 4d44acee901c
Step 2 : MAINTAINER Jan Prach <jendap@google.com>
 ---> Using cache
 ---> 598ad93f9ec8
Step 3 : COPY install/*.sh /install/
 ---> Using cache
 ---> 2e90718bcd83
Step 4 : RUN /install/install_bootstrap_deb_packages.sh
 ---> Using cache
 ---> 785d8c4ecf96
Step 5 : RUN add-apt-repository -y ppa:openjdk-r/ppa &&     add-apt-repository -y ppa:mc3man/trusty-media &&     add-apt-repository -y ppa:george-edison55/cmake-3.x
 ---> Using cache
 ---> 8bbcbdd9d0e3
Step 6 : RUN /install/install_deb_packages.sh
 ---> Using cache
 ---> ddebcc57fb16
Step 7 : RUN /install/install_pip_packages.sh
 ---> Using cache
 ---> 3f6d70765a8b
Step 8 : RUN /install/install_bazel.sh
 ---> Using cache
 ---> c7e6bab7b915
Step 9 : RUN /install/install_proto3.sh
 ---> Using cache
 ---> 5c754e68ad21
Step 10 : RUN /install/install_buildifier.sh
 ---> Using cache
 ---> 348488be0193
Step 11 : RUN /install/install_auditwheel.sh
 ---> Using cache
 ---> 70ee410ea1cb
Step 12 : COPY install/.bazelrc /root/.bazelrc
 ---> Using cache
 ---> 75649c1f71be
Step 13 : ENV BAZELRC /root/.bazelrc
 ---> Using cache
 ---> 79809615d28e
Successfully built 79809615d28e
Running 'bazel test //tensorflow/learn/...' inside tf_ci.cpu...
id: illegal option -- -
usage: id [user]
       id -A
       id -F [user]
       id -G [-n] [user]
       id -M
       id -P [user]
       id -g [-nr] [user]
       id -p [user]
       id -u [-nr] [user]
id: illegal option -- -
usage: id [user]
       id -A
       id -F [user]
       id -G [-n] [user]
       id -M
       id -P [user]
       id -g [-nr] [user]
       id -p [user]
       id -u [-nr] [user]
dialout:x:20:
adduser: Only one or two names allowed

**Comment by abhitopia** [comment]
cc: @vrv, @ebrevdo

**Comment by abhitopia** [comment]
Found the culprit.
In this line.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/ci_build.sh#L151

`--name` should be replaces by `-n` ( This also works on Ubuntu)

Should I do a PR ?

**Comment by martinwicke** [comment]
Does that also affect L153?

**Comment by caisq** [comment]
@abhitopia A PR will be welcome!

**Comment by abhitopia** [comment]
@caisq - PR created #5784
