### ISSUE TITLE
 what is this http://b/18228951 , i can not find it

### ISSUE THREAD

**Issue by chenliang110** [tensorflow/tensorflow#57604]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.7

### Custom Code

No

### OS Platform and Distribution

no

### Mobile device

no

### Python version

3.7

### Bazel version

no

### GCC/Compiler version

no

### CUDA/cuDNN version

no

### GPU model and memory

111

### Current Behaviour?

```shell
http://b/18228951,i find there are many http://b  in tflite code。But I can not find the url,do you send it?
```

### Standalone code to reproduce the issue

```shell
111111
```

### Relevant log output

```shell
1111
```
</details>

**Comment by tilakrayal** [comment]
@chenliang110,
I tried to access the provided [link](http://b/18228951) and facing an access issue. I suspect it is not related and accessible.
In order to expedite the trouble-shooting process, could you please provide a minimal code snippet and the TensorFlow version you are using. Thank you!

**Comment by mihaimaruseac** [comment]
`b/numbers` is an internal link to Google resources. The contents are private to google.

**Comment by chenliang110** [comment]
> `b/numbers` is an internal link to Google resources. The contents are private to google.
Hello，in tflite2.9 has following code:
size_t TfLiteIntArrayGetSizeInBytes(int size) {
  static TfLiteIntArray dummy;

  size_t computed_size = sizeof(dummy) + sizeof(dummy.data[0]) * size;
#if defined(_MSC_VER)
  // Context for why this is needed is in http://b/189926408#comment21
  computed_size -= sizeof(dummy.data[0]);
#endif
  return computed_size;
}
and

typedef struct TfLiteIntArray {
  int size;
#if defined(_MSC_VER)
  // Context for why this is needed is in http://b/189926408#comment21
  int data[1];
  ....
But in tflite 2.7 has not above parts。 I want to know why in 2.9 make a difference for _MSC_VER,  what is this reason. is it a bug for  _MSC_VER?

**Comment by tilakrayal** [comment]
@chenliang110,
In order to expedite the trouble-shooting process, could you please provide a minimal code snippet you are using. Thank you!
