### ISSUE TITLE
Gather Op on GPU

### ISSUE THREAD

**Issue by williamdias** [tensorflow/tensorflow#57610]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS BigSur 11.6.7 and Android 10 / 11.
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source): v2.10.0-rc2

**Provide the text output from tflite_convert**

```
ERROR: Following operations are not supported by GPU delegate:
1: GATHER: Operation is not supported.
1: 351 operations will run on the GPU, and the remaining 1084 operations will run on the CPU.
```

Hi, 

I have a model that needs to run on GPU but it seems that GATHER Op is not supported by GPU delegate when using tflite C++. Some questions:

1. Is there any particular reason why it is not supported? 
2. Do you have plans to support this Op on GPU?
3. Is there any other Op (or set of Ops) that I could use to replace Gather on the GPU?
4. Is there a way to split the model into different subgraphs and run only the one that contains Gather Op on CPU? (if so, could you point me to some documentation?)

Thank you!

**Comment by mohantym** [comment]
Hi @williamdias !
You can use NNAPI delegate to use gather op . You can create your own fallback policy on delegates with  interpreter so that if its find sany other unsupported op during inference with GPU delegate It should try with NNAPI delegate else fallback to CPU mode (in case it finds exception in any of the delegates)

Attached relevant threads [1](https://stackoverflow.com/a/68475828/11530462), [2](https://www.tensorflow.org/lite/android/delegates/nnapi) for reference.

**Comment by williamdias** [comment]
Hi @mohantym

Thank you, but you didn't answer any of my questions 😞 
If I want to contribute with tflite and implement gather on GPU, could you point me to some reference?

Cheers!

**Comment by mohantym** [comment]
Sorry @williamdias !
For the inconvenience.
@sachinprasadhs !
Could you look at this issue.
Thank you!

**Comment by williamdias** [comment]
Any news?

**Comment by williamdias** [comment]
Hello, @sachinprasadhs. Could you help me with this?

**Comment by sachinprasadhs** [comment]
Apologies for the delayed response, as of now TFLite supports limited number of operations under builtin library.
You can create a custom op and register under GPU kernel to allow the conversion using GPU.
More details can be found [here](https://www.tensorflow.org/lite/guide/ops_custom). Thanks!
