### ISSUE TITLE
tflite_model_maker not exporting to quantised int8

### ISSUE THREAD

**Issue by Scottyy-M** [tensorflow/tensorflow#57619]
### 1. System information
_This error happens both on my PC:_
- OS Platform and Distribution: Windows 10(amd64) v10.0
- TensorFlow installation (pip package or built from source): From pip, TF version v2.9.0-18-gd8ce9f9c301 2.9.1 on Python 3.9
- TensorFlow library: 

_AND on Google Colab_

### 2. Code
_What I am trying to do:_
Train a model and export a quantised int8 version for later use with the TPU USB accelerator. I export a non-quantized version for comparison.

_What I get:_
The model which is supposed to be quantized always exports identically to the un-quantized version, with the same message when running "model.export()" that "Statistics for quantized inputs were expected, but not specified; continuing anyway."
Link to the exported model:
https://drive.google.com/file/d/1Gt4XT1J2Ujt3dXy-vKgwESs2fciTDqFA/view?usp=sharing

```
# import
import tensorflow as tf

assert tf.__version__.startswith('2')
from tflite_model_maker.config import QuantizationConfig
from tflite_model_maker.image_classifier import DataLoader
from tflite_model_maker import model_spec
from tflite_model_maker import image_classifier

# train data folder path to my google drive, all images are .jpeg
data = DataLoader.from_folder(train_data_folder_path)
train_data, val_data = data.split(0.8)
model_spec = model_spec.get('mobilenet_v2')
model = image_classifier.create(
    train_data,
    model_spec=model_spec,
    validation_data=val_data,
)

# test data folder path goes to my google drive, all images are .jpeg
test_data = DataLoader.from_folder(test_data_folder_path)

# First export the model with default settings
tflite_filename = "default_model.tflite"
model.export(export_dir=".", tflite_filename=tflite_filename)

# Then, export as quantized
quant_tflite_filename = "int8_model.tflite"
quantization_config = QuantizationConfig.for_int8(test_data)
model.export(export_dir=".", tflite_filename=quant_tflite_filename, quantization_config=quantization_config)
```

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

- Model does not produce a quantized version. The output files are of identical file size and the log below is the same for both.

### 5. Any other info / logs
>>> model._export_tflite(tflite_filepath=tflite_filename, quantization_config=quantization_config)

INFO:tensorflow:Assets written to: C:\Users\sm251\AppData\Local\Temp\tmpymme3pmk\assets
INFO:tensorflow:Assets written to: C:\Users\sm251\AppData\Local\Temp\tmpymme3pmk\assets
2022-09-06 14:35:11.483922: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-09-06 14:35:11.484556: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
C:\Users\sm251\AppData\Roaming\Python\Python39\site-packages\tensorflow\lite\python\convert.py:766: UserWarning: Statistics for quantized inputs were expected, but not specified; continuing anyway.
  warnings.warn("Statistics for quantized inputs were expected, but not "
2022-09-06 14:35:21.939062: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
2022-09-06 14:35:21.939219: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.
fully_quantize: 0, inference_type: 6, input_inference_type: 3, output_inference_type: 3
INFO:tensorflow:Label file is inside the TFLite model with metadata.
INFO:tensorflow:Label file is inside the TFLite model with metadata.
INFO:tensorflow:Saving labels in C:\Users\sm251\AppData\Local\Temp\tmpf7kb5uh9\labels.txt
INFO:tensorflow:Saving labels in C:\Users\sm251\AppData\Local\Temp\tmpf7kb5uh9\labels.txt

**Comment by mohantym** [comment]
Hi @Scottyy-M !
Could you update the Above QuantizationConfig like below and let us know.
```

QuantizationConfig.for_int8(
               representative_data, # split your current test_data and use yield to return some slices of  data instead of using complete test_data
               quantization_steps=DEFAULT_QUANTIZATION_STEPS,
               inference_input_type=tf.uint8,
               inference_output_type=tf.uint8,
               supported_ops=tf.lite.OpsSet.TFLITE_BUILTINS_INT8) , # use select ops in supported ops  too if you face any select ops error
```

**Comment by Scottyy-M** [comment]
Hi @mohantym 

I tried that however the results were the same. I've copied the output below:

>>> config = QuantizationConfig.for_int8(
...     test_data, # split your current test_data and use yield to return some slices of  data instead of using complete test_data
...     quantization_steps=500,
...     inference_input_type=tf.uint8,
...     inference_output_type=tf.uint8,
...     supported_ops=tf.lite.OpsSet.TFLITE_BUILTINS_INT8)

>>> model.export(export_dir=export_dir, tflite_filename=quant_tflite_filename, quantization_config=config)

INFO:tensorflow:Assets written to: C:\Users\sm251\AppData\Local\Temp\tmptjr3ot07\assets
INFO:tensorflow:Assets written to: C:\Users\sm251\AppData\Local\Temp\tmptjr3ot07\assets
2022-09-06 17:33:48.799026: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-09-06 17:33:48.801333: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
C:\Users\sm251\AppData\Roaming\Python\Python39\site-packages\tensorflow\lite\python\convert.py:766: UserWarning: Statistics for quantized inputs were expected, but not specified; continuing anyway.
  warnings.warn("Statistics for quantized inputs were expected, but not "
2022-09-06 17:33:49.908961: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
2022-09-06 17:33:49.909206: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.
fully_quantize: 0, inference_type: 6, input_inference_type: 3, output_inference_type: 3
INFO:tensorflow:Label file is inside the TFLite model with metadata.
INFO:tensorflow:Label file is inside the TFLite model with metadata.
INFO:tensorflow:Saving labels in C:\Users\sm251\AppData\Local\Temp\tmpd12wqpnj\labels.txt
INFO:tensorflow:Saving labels in C:\Users\sm251\AppData\Local\Temp\tmpd12wqpnj\labels.txt
INFO:tensorflow:TensorFlow Lite model exported successfully: .\Batch2 Germ, Not, Error - First, Balanced TFLite_1 quant.tflite
INFO:tensorflow:TensorFlow Lite model exported successfully: .\Batch2 Germ, Not, Error - First, Balanced TFLite_1 quant.tflite

**Comment by Scottyy-M** [comment]
Hi @mohantym 
Thank you

I have run into issues with this too. Firstly, the line:
`supported_ops=tf.lite.OpsSet.TFLITE_BUILTINS_INT8 , tf.lite.OpsSet.SELECT_TF_OPS`
has an issue with "tf.lite.OpsSet.SELECT_TF_OP":
>SyntaxError: positional argument follows keyword argument

I tried removing that line, and then I got the following error:
>TypeError: for_int8() got an unexpected keyword argument 'experimental_new_quantizer'
Not sure what to do here.

Also, I am not sure how to split my current test data and use yield to return some slices. 
I checked and the default data type of the images is unit8. To change the type I could import the data differently and use something like below?
`img = img.astype(np.int8)`

I also tried specifying the config as the other types:
`config=QuantizationConfig.for_float16()`
and 
`config=QuantizationConfig.for_dynamic()`
Both these methods DONT complain that the

>"Statistics for quantized inputs were expected, but not specified; continuing anyway"

and they DONT have the line

>"fully_quantize: 0, inference_type: 6, input_inference_type: 3, output_inference_type: 3"

However, they do both have the lines:

>W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
>W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.

Also, the output file size of the dynamic model was a bit smaller, so I am confident that it worked, and that the int8() still isnt.

Thanks,
Scott

**Comment by mohantym** [comment]
Ok @Scottyy-M !
Thanks for the update.
@sachinprasadhs ! 
Could you look at this issue.

**Comment by mohantym** [comment]
Yes @Scottyy-M ! Default quantization is integer quantization.

**Comment by Scottyy-M** [comment]
Thanks @mohantym !
That line in the output threw me off thinking it was not working.
Thanks for the code to check the output model too!
