### ISSUE TITLE
Does Distributed TensorFlow can be run in independent filesystem

### ISSUE THREAD

**Issue by ilixiaocui** [tensorflow/tensorflow#57618]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf1.14

### Custom Code

Yes

### OS Platform and Distribution

Debain 10

### Python version

3.9

### Current Behaviour?

I used tensorflow version 1.14 to run distributed training and failed using the **local file system.**

I saw the exchange [post in 2018 on the Internet](https://groups.google.com/a/tensorflow.org/g/discuss/c/-NdsSrWmp8w), saying that the distributed training must use the shared file system at that time, but the local file system will be supported later
![image](https://user-images.githubusercontent.com/15689619/188060748-9bff0805-1799-4009-9cb3-248f7ec8960f.png)

Is there a version that supports running distributed training tasks on the local file system?

### Standalone code to reproduce the issue

I use tf1.14 version of the distributed training framework estimator training data, with 2 ps and 3 workers, which is all configure the local file system, and found that the operation failed.
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/15689619/188532156-463afea5-3522-4212-b9f0-25be5705996e.png">

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @ilixiaocui !
1.x version are not supported anymore.

For 2.x versions, According to this [thread](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras#fault_tolerance) , if you are going for a cluster synchronous training ( master-slave node), the cluster would fail if one of the workers fails and no failure-recovery mechanism exists. 

But if you just want to use distributed computing of [distribution strategy](https://www.tensorflow.org/guide/distributed_training) , you can use a machine with multiple GPU's in your local file system with strategy.scope().

Please post on [TF Forum](https://discuss.tensorflow.org/) for further assistance.

Thank you!
