### ISSUE TITLE
TensorBoard callback does not log `batch_` metrics since v2.8.0

### ISSUE THREAD

**Issue by ebraraktas** [tensorflow/tensorflow#57614]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

No

### OS Platform and Distribution

Ubuntu on Colab

### Python version

3.7.13

### Current Behaviour?

`TensorBoard` callback doesn't log `batch_` metrics even if I set `update_freq=2`. This behavior occurs since v2.8.0 and v2.7.0 works as expected. I am not sure if this is related, but this SO question seems similar to me: https://stackoverflow.com/questions/71594268/tensorboard-not-updating-by-batch-in-google-colab

### Standalone code to reproduce the issue

This colab demonstrates the issue: https://colab.research.google.com/gist/ebraraktas/1c5040b2934c710ac797b67ed98d3622

### Relevant log output

<img width="691" alt="Screen Shot 2022-09-05 at 16 37 34" src="https://user-images.githubusercontent.com/62459770/188462896-15418679-c265-4577-8426-554d528a298e.png">

_No response_</details>

**Comment by tilakrayal** [comment]
@ebraraktas,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by ebraraktas** [comment]
Sorry, I was not aware of that change. There exists [an issue](https://github.com/keras-team/keras/issues/16173), which is same as this one, in keras repository. I am closing this one.
