### ISSUE TITLE
[Build Issue] OSError: [Errno 8] Exec format error  when doing cross compilation of TFLite C library for ARM64

### ISSUE THREAD

**Issue by CarlosYeverino** [tensorflow/tensorflow#57617]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

latest master, commit 71edfa2a963c1ebb624786263ab87052b39095e7)

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Mobile device

Linux Ubuntu 18.04

### Python version

3.6.9

### GCC/Compiler version

Cross compilation with gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu

### Current Behaviour?

```shell
I tried to build tflite from source using cross compilation, however, I got the following issue:

Traceback (most recent call last):
  File "scripts/generate_code.py", line 164, in <module>
    data="monsterdata_test.json",
  File "scripts/generate_code.py", line 82, in flatc
    result = subprocess.run(cmd, cwd=str(cwd), check=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/yeverino/Documents/git/fordos_tilinux/Fnv4VX/tensorflow_src/tflite_build_arm/_deps/flatbuffers-build/flatc'
make[2]: *** [_deps/flatbuffers-build/flatc] Error 1
make[2]: *** Deleting file '_deps/flatbuffers-build/flatc'
make[1]: *** [_deps/flatbuffers-build/CMakeFiles/flatc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

### Standalone code to reproduce the issue

```shell
git clone https://github.com/tensorflow/tensorflow.git tensorflow_src

cd tensorflow_src/

mkdir tflite_build_arm

cd tflite_build_arm

ARMCC_PREFIX=/home/yeverino/titools/toolchain/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-

ARMCC_FLAGS="-funsafe-math-optimizations"

cmake -DCMAKE_C_COMPILER=${ARMCC_PREFIX}gcc  -DCMAKE_CXX_COMPILER=${ARMCC_PREFIX}g++  -DCMAKE_C_FLAGS="${ARMCC_FLAGS}"  -DCMAKE_CXX_FLAGS="${ARMCC_FLAGS}"  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON  -DCMAKE_SYSTEM_NAME=Linux  -DTFLITE_ENABLE_XNNPACK=ON  -DCMAKE_SYSTEM_PROCESSOR=aarch64  -DBUILD_SHARED_LIBS=ON  ../tensorflow/lite/

cmake --build . -j
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "scripts/generate_code.py", line 164, in <module>
    data="monsterdata_test.json",
  File "scripts/generate_code.py", line 82, in flatc
    result = subprocess.run(cmd, cwd=str(cwd), check=True)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/yeverino/Documents/git/fordos_tilinux/Fnv4VX/tensorflow_src/tflite_build_arm/_deps/flatbuffers-build/flatc'
make[2]: *** [_deps/flatbuffers-build/flatc] Error 1
make[2]: *** Deleting file '_deps/flatbuffers-build/flatc'
make[1]: *** [_deps/flatbuffers-build/CMakeFiles/flatc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```
</details>

**Comment by CarlosYeverino** [comment]
**Here attached console output logs when doing cmake configuration and cmake build**

[TfliteARMCmakeConsoleOutput.txt](https://github.com/tensorflow/tensorflow/files/9492332/TfliteARMCmakeConsoleOutput.txt)
[TfliteARMBuildConsoleOutput.txt](https://github.com/tensorflow/tensorflow/files/9492349/TfliteARMBuildConsoleOutput.txt)
[TfliteARMBuildConsoleOutputPart2.txt](https://github.com/tensorflow/tensorflow/files/9492353/TfliteARMBuildConsoleOutputPart2.txt)

**Comment by bob2277** [comment]
Got a similar error, while following the steps here https://www.tensorflow.org/lite/guide/build_cmake for cross compilation of tflite for android using ndk,

Traceback (most recent call last):
  File "scripts/generate_code.py", line 148, in <module>
    flatc(
  File "scripts/generate_code.py", line 82, in flatc
    result = subprocess.run(cmd, cwd=str(cwd), check=True)
  File "/usr/local/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/local/mnt/workspace/bhuyan/tflite_build/_deps/flatbuffers-build/flatc'
gmake[2]: *** [_deps/flatbuffers-build/flatc] Error 1
gmake[2]: *** Deleting file `_deps/flatbuffers-build/flatc'

gmake[1]: *** [_deps/flatbuffers-build/CMakeFiles/flatc.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....

**Comment by mohantym** [comment]
@sachinprasadhs!
Could you look at this issue.

**Comment by WesleyCh3n** [comment]
According to https://github.com/google/flatbuffers/issues/7297#issuecomment-1207311095, 
Change https://github.com/tensorflow/tensorflow/blob/fc9475fa7329745b6fd47747c351894d88370b6e/tensorflow/lite/tools/cmake/modules/flatbuffers.cmake#L26 to latest tag (`v2.0.8`) work for me, error disappeared and cross-compile succeeded.

**Comment by CarlosYeverino** [comment]
The reported OSError issue was fixed following WesleyCh3n comment. However, I'm getting linking issue undefined reference to tflite APIs when trying to use the cross compiled tflite C library. I created a separated ticket https://github.com/tensorflow/tensorflow/issues/57700 I'd appreciate your help on this
