### ISSUE TITLE
Android Tensorflow Lite 2.9.0 AAR InterpreterAPI not found Error 

### ISSUE THREAD

**Issue by MadiTechapps** [tensorflow/tensorflow#57626]
**System information**
- OS Platform and Distribution (: Ubuntu
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source): 2.9.0 AAR

**Issue details**
As per our requirement, I want to add TF Lite AAR file into our project.

So I have downloaded AAR file(2.9.0) from [Maven](https://jarcasting.in/artifacts/org.tensorflow/tensorflow-lite/2.9.0/) and added to my project.Then I can imports the Interpreter and other required things, but when I try to build and run the project I’m getting InterpreterAPI class not found error like this.([please refer the screenshots][2]](https://i.stack.imgur.com/RPMkM.png)[[3]](https://i.stack.imgur.com/Jj9JY.png))

class file for org.tensorflow.lite.InterpreterApi not found

If I add below 2.7.0 version aar files, I’m able to build and run the projects but those are deprecated, I want use latest AAR file only.

Can anyone please help me on this?

Note: I should use AAR only not gradle dependencies

**Comment by mohantym** [comment]
Hi @MadiTechapps !
Did you also mention the location of aar file in builld.gradle file as mentioned in this [document](https://www.tensorflow.org/lite/android/lite_build#add_aar_directly_to_project).  You can also install the AAR file to your local Maven Repo through the below command.
```
mvn install:install-file \
  -Dfile=<location folder containing aar file>/tensorflow-lite.aar \
  -DgroupId=org.tensorflow \
  -DartifactId=tensorflow-lite -Dversion=0.1.100 -Dpackaging=aar
```
Please let us know the results after following the above step.
Thank you!

**Comment by MadiTechapps** [comment]
Yes I did it,
I got Build success message on terminal 
[see this screenshot](https://i.stack.imgur.com/EgUom.png)

**Comment by mohantym** [comment]
@MadiTechapps !
Shall we consider this issue as  resolved then.
Thank you!

**Comment by MadiTechapps** [comment]
I have tried 2.10.0 version too, but getting Cannot find symbol error (see the below screenshots)

Here the error details for 2.7.0 & 2.8.0 &2.9.0 versions
[Screenshot](https://i.stack.imgur.com/Jj9JY.png)

for 2.10.0 version error details
[Screenshot](https://i.stack.imgur.com/I6Ddj.png)

**Comment by mohantym** [comment]
Hi @sachinprasadhs !
Could you look at this issue.
Thank you!
