### ISSUE TITLE
Can't excute ConvNeXt with input_tensor

### ISSUE THREAD

**Issue by Burf** [tensorflow/tensorflow#57633]
When tf.keras.applications.ConvNeXt is executed with input_tensor, it is not executed.
As you can see from [issue](https://github.com/keras-team/keras/issues/16990), it seems to be a problem inside the keras code.
Once the keras issue is resolved, I hope to apply it as soon as possible.
This article is just to inform you that there was such a problem.
Thanks.

**Comment by mohantym** [comment]
Hi @Burf!
Thank you for bringing it up. It seems you have already created issue for this bug in keras repo. 
Please wait while it is getting triaged from keras team.

I could not find the same behaviour in nightly though ( replicating in 2.8 and 2.9).

Thank you!
