### ISSUE TITLE
How can I save model with input/output signatures with TF2?

### ISSUE THREAD

**Issue by ViktorKhLoopMe** [tensorflow/tensorflow#57642]
How can I save model with input/output signatures for using model in TF serving like I used to saved in V1?

```
builder = tf.saved_model.builder.SavedModelBuilder(export_path)

model_input = tf.saved_model.utils.build_tensor_info(model.input)
model_output = tf.saved_model.utils.build_tensor_info(model.output)

prediction_signature = (
    tf.saved_model.signature_def_utils.build_signature_def(
        inputs={'inputs': model_input},
        outputs={'output': model_output},
        method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME))

with K.get_session() as sess:
    builder.add_meta_graph_and_variables(
        sess=sess, tags=[tf.saved_model.tag_constants.SERVING],
        signature_def_map={
            'predict':
                prediction_signature,
        })

    builder.save()
```

I see that in TF2 I need use tf.function but I can't understand how create exactly same save signatures that I used in TF1

I can't use way with `tf.compat.v1.` cause TF serving wont work due to my previous issue
https://github.com/tensorflow/tensorflow/issues/56698

System information
python 3.9
tensorflow-serving-api==2.8.0
tensorflow==2.8.0

**Comment by mohantym** [comment]
Hi @ViktorKhLoopMe !
You have to declare the call and other function of your model under @tf.function with the signature and use concrete function while saving the model.

If you want to use 1.x model weights,  you can transfer the weights to a 2.x model.

Please refer this [document](https://www.tensorflow.org/guide/saved_model#specifying_signatures_during_export) for sample usage of signature while saving model .

Thank you!
