### ISSUE TITLE
Is it possible to use both cameras (FRONT AND BACK) with CameraX for object detection TFLITE *NO HARDWARE LIMITATION*

### ISSUE THREAD

**Issue by JuanJoseMoralesCalvo** [tensorflow/tensorflow#57643]
As the title says i tried to implement an app that with the front detects the driver face and with the back detects cars. I modified the demo object detection for tensorflow lite inrtroducing a new camera fragment and adding the permissions to the new camerabinding. Only 1 camera appears to works, getting in the LOGS that the maximum of Cameras allowed to be open are 1. 

Ive seen apps with camera2  API working both cameras at the same time, so i have the next question:

1. is it possible to use camera2 API with tensorflow lite?
2. is it possible to use 2 cameras simultaniously  with CameraX api?

Thanks in advance.

**Comment by JuanJoseMoralesCalvo** [comment]
Thanks for the reply, right now i wasnt able to use both cameras with CameraX due to "bindToLifecycle()" doesnt let you to use 2 cameraSelector at the same time. I will appretiate if you know any post regarding the use of both cameras with TFlite or any post related with Camera2 and tflite. 

Thanks for the fast reply :D .

**Comment by mohantym** [comment]
Hi @JuanJoseMoralesCalvo !
Camera 2.x does not support accessing both cameras same time as you mentioned earlier . You can opt for [Camera 2](https://developer.android.com/training/camera2/multiple-camera-streams-simultaneously) api 
for accessing dual camera input .Regarding hardware configuration , I think Dual ISP configuration required to access both front and real camera same time. 

[Reference](https://proandroiddev.com/can-we-use-the-front-back-camera-at-the-same-time-on-android-3e6558c1b12a) on Dual ISP .

Please post on [TF forum](https://discuss.tensorflow.org/) for further assistance.

Thank you!

**Comment by JuanJoseMoralesCalvo** [comment]
Ok thanks for the help, i will try from this.

**Comment by mohantym** [comment]
@JuanJoseMoralesCalvo !
Can we consider this as resolved then.
Thank you!

**Comment by mohantym** [comment]
Ok @JuanJoseMoralesCalvo !
Thanks for the nod. Marking this as resolved then.
Thank you!

**Comment by JuanJoseMoralesCalvo** [comment]
Just Completed the task, Camera2 API is the real deal. Thanks for the help

**Comment by mohantym** [comment]
@JuanJoseMoralesCalvo ! 
You are welcome.
