### ISSUE TITLE
Updating TFLite ConvTranspose to make it support dynamic inputs.

### ISSUE THREAD

**Issue by gokulkrishna98** [tensorflow/tensorflow#57650]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubunutu 21.02
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):  tensorflow 2.9.1

**Standalone code to reproduce the issue** 
Converting any ConvTranspose layer from ONNX to TensorflowLite.

**Any other info / logs**
The ONNX does not have requirement for output_shape argument for ConvTranspose layer.
[https://github.com/onnx/onnx/blob/main/docs/Operators.md#ConvTranspose]()
since that can be calculated. 

But in tflite the ConvTranspose layer requires mandatory requirement for output_shape.
[https://github.com/tensorflow/tensorflow/blob/18960c44ad3f5219c22dca55f842912dbce78a07/tensorflow/lite/kernels/transpose_conv.cc#L251-L253]()

So because of this the dynamic reshape happens in wrong way in tflite ConvTranpose, but for ONNX it can be done.
Is it possible to remove the output_shape tensor requirement in tflite and similarly be updated in tflite convertor? or Any other workaround will be appreciated.

**Comment by mohantym** [comment]
Hi @gokulkrishna98 !
You can set the desired input and output shape of model through model binding .
Attached relevant thread for reference.
[1](https://towardsdatascience.com/machine-learning-with-android-11-whats-new-e8c829e9452), [2](https://firebase.google.com/docs/ml-kit/android/use-custom-models#perform-inference-on-input-data:~:text=For%20such%20a%20model%2C%20you%20would%20configure%20the%20model%20interpreter%27s%20input%20and%20output%20as%20shown%20below%3A).

Thank you!
