### ISSUE TITLE
Model Trains on CPU but not on GPU - TensorDot/MatMul error

### ISSUE THREAD

**Issue by willi3by** [tensorflow/tensorflow#57666]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python version

3.9.12

### CUDA/cuDNN version

CUDA=11.2, cuDNN=8.1

### GPU model and memory

RTX 8000 48GB 

### Current Behaviour?

```shell
I am trying to train a model using the GPUs on my computer. The model trains as expected on the CPU but I get the following error when trying to use the GPU:

Node: 'model/final_output/Tensordot/MatMul'
2 root error(s) found.
  (0) INTERNAL:  Blas xGEMV launch failed : a.shape=[1,2628288,150], b.shape=[1,150,1], m=2628288, n=1, k=150
	 [[{{node model/final_output/Tensordot/MatMul}}]]
	 [[Nadam/Nadam/group_deps/_111]]
  (1) INTERNAL:  Blas xGEMV launch failed : a.shape=[1,2628288,150], b.shape=[1,150,1], m=2628288, n=1, k=150
	 [[{{node model/final_output/Tensordot/MatMul}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_29232]
```

I have tried multiple versions of tensorflow gpu (2.5 through 2.10) and get the same error. I would expect the network to train the same on GPU as on CPU.
```


### Standalone code to reproduce the issue

```shell
The network that I have created is a bit cumbersome for posting on this platform. I am happy to send files if needed.
```

### Relevant log output

```shell
Node: 'model/final_output/Tensordot/MatMul'
2 root error(s) found.
  (0) INTERNAL:  Blas xGEMV launch failed : a.shape=[1,2628288,150], b.shape=[1,150,1], m=2628288, n=1, k=150
	 [[{{node model/final_output/Tensordot/MatMul}}]]
	 [[Nadam/Nadam/group_deps/_111]]
  (1) INTERNAL:  Blas xGEMV launch failed : a.shape=[1,2628288,150], b.shape=[1,150,1], m=2628288, n=1, k=150
	 [[{{node model/final_output/Tensordot/MatMul}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_29232]
```
</details>

**Comment by tilakrayal** [comment]
@willi3by,
To expedite the trouble-shooting process, could you please provide a complete code you are using. Thank you!

**Comment by markemus** [comment]
I'm having this bug as well in tf2.10.0, cudatoolkit 11.2. Also failing on a giant matrix.

```
Blas xGEMV launch failed : a.shape=[1,13238742,6], b.shape=[1,6,1], m=13238742, n=1, k=6
	 [[{{node model/attention/dense_2/MatMul}}]] [Op:__inference_train_function_1902]

```

**Comment by willi3by** [comment]
Thanks for the response @tilakrayal  and for the second @markemus. I confirmed this issue by training the network with a batch size of 1 with no issues, as the matrix was smaller than 2^20 with only one sample. I will work on getting the code up soon. 

Thanks

**Comment by markemus** [comment]
@tilakrayal There is a minimal code example here: https://github.com/tensorflow/tensorflow/issues/54463 for recreating the bug. I tried it on my setup and got the exception.

**Comment by tilakrayal** [comment]
@willi3by,
Could you please take a look at this https://github.com/tensorflow/tensorflow/pull/56691 which fixed the `Unable to register cuBLAS` factory error. Please try this and let us know if the issue still persists. Thank you!

**Comment by willi3by** [comment]
@tilakrayal 
Thanks for the link. I am not sure what to try per se. I read through and it looks like this change was committed to the master branch of tensorflow on August 10. I only recently install tensorflow using pip. Does pip pull the most recent tensorflow master or do I have to compile from source? 

Thanks

**Comment by sachinprasadhs** [comment]
@willi3by , You need to install tensorflow nightly version for that PR to be available. Since this PR could not make it at the time of 2.10.0 brach cut. 
It might be included if there is any patch release for 2.10.0 or it will be available in the next release, i.e 2.11.0.

**Comment by willi3by** [comment]
@tilakrayal I apologize for the delay. I updated TF and am still getting the same error. My current version of TF is 2.11.0-dev20220928

**Comment by arvindrajan92** [comment]
Hi @willi3by,
Have you tried downgrading from CUDA 11.2 to CUDA 11.1? 
If you are using conda environment, following installation steps in https://www.tensorflow.org/install/pip, `conda install -c conda-forge cudatoolkit=11.1 cudatoolkit-dev=11.1 cudnn=8.1.0 -y` sets up my environment perfectly. I have been doing this to circumvent the issue with CUDA 11.2 and you might find this helpful as well.

**Comment by willi3by** [comment]
@arvindrajan92 That fixed it!! Thanks very much for your suggestion.
