### ISSUE TITLE
Theoretical Question about model size (parameters)

### ISSUE THREAD

**Issue by Petros626** [tensorflow/tensorflow#57677]
Hi guys,

I would like to know if the model size of a model depends on the data set size, so that for each new training a new model size results?

The parameters in an architecture are fixed and do not change, but is it possible that if the training is bad, not all neurons will be activated and the model size will be smaller?

**Comment by tilakrayal** [comment]
@Petros626,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue. Thank you!

**Comment by Petros626** [comment]
> @Petros626, We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue. Thank you!

The template would make sense if I use Software to list the specifications of the system and the environment, but it's a pure theoretical question, because I didn't find a answer in the web

**Comment by tilakrayal** [comment]
@Petros626,
This is not a TensorFlow bug or feature request, it is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) or Tensorflow discussion [Forum](https://discuss.tensorflow.org/). There is a larger community that reads questions there. Thank you!
