### ISSUE TITLE
tf.profiler.experimental.ProfilerOptions.delay_ms does not work

### ISSUE THREAD

**Issue by forics** [tensorflow/tensorflow#57682]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Debian 11 (bullseye)

### Python version

3.9

### Current Behaviour?

I used tf.profiler.experimental.ProfilerOptions(...) and tf.profiler.experimental.client.trace(...) to profile google cloud TPU. I found TF started to profile immediately without delay for `delay_ms` milliseonds.

### Standalone code to reproduce the issue

```python
# pseudo-code for demonstration
import tensorflow as tf

opt = tf.profiler.experimental.ProfilerOptions(delay_ms=50000)

# some TPU asynchronous calls

service_addr = 'grpc://' + tpu_ip_address + profiler_port
tf.profiler.experimental.client.trace(service_addr=service_addr,
                                      logdir='gs://log',
                                      duration_ms=10000,
                                      options=opt)

```

As mentioned above, profiling starts immediately without waiting for 50s. Then I traced the calling stack, which looks like this:
```shell
tensorflow/core/profiler/rpc/client/capture_profile.cc:209
|-tensorflow/core/profiler/rpc/client/capture_profile.cc:121
  |-tensorflow/core/profiler/rpc/client/remote_profiler_session_manager.cc:69  // `session_created_time`
  |-tensorflow/core/profiler/rpc/client/remote_profiler_session_manager.cc:71
```
At tensorflow/core/profiler/rpc/client/remote_profiler_session_manager.cc:71, deadline of session is calculated by adding `duration_ms` to `session_created_time` without considering `delay_ms`.

I guess this causes the bug. Because I'm new to TF, I just point this out.

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@forics,
I was facing a different issue while executing the given code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/feb6b1d38224ba0131d2bc8fea993c6c/untitled595.ipynb). Thank you!

**Comment by forics** [comment]
> @forics, I was facing a different issue while executing the given code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/feb6b1d38224ba0131d2bc8fea993c6c/untitled595.ipynb). Thank you!

Yes. the initial given code is not runnable, because it's just pseudo-code for demonstration.

I wrote a more concrete code [here](https://gist.github.com/forics/231468ce9821cde50780900d333b0979), you can try it.

P.S., I don not access TPU through Colab, so I can not guarantee the correction of TPU connection part.

**Comment by tilakrayal** [comment]
@forics ,
I was facing a different error while trying to execute the mentioned code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/ad92acc4d472218cec81c86169a9d064/untitled602.ipynb).

**Comment by forics** [comment]
@tilakrayal  ,
Sorry, it's my mistake. I tested the code with `batch_size` 64, but I modified it to 512 without testing again. Maybe related to issue #36136 .

Code has been updated [here](https://gist.github.com/forics/231468ce9821cde50780900d333b0979), running in Colab without errors. You will find that profiling starts without waiting 50s.

**Comment by tilakrayal** [comment]
@forics,
I tried to execute the code changing batch_size to 64 and was able to execute without any error on tensorflow v2.8, where it was failing with a different error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/e93c59d07e5d8ceec1dc28b4efa38317/untitled618.ipynb) and confirm if you are referring to the issue. Thank you!

**Comment by forics** [comment]
@tilakrayal ,
The error is out of the scope of the issue, you can find the issue also exists in TF v2.8.

After a simple search on google, your error may caused by the TF version confliction of host and device. Ref to #39550 and [this](https://stackoverflow.com/questions/55181024/tensorflow-tpu-training-notfounderror-parallelinterleavedataset). Good luck!
