### ISSUE TITLE
TFLite fails to run a model with a dense layer following an Add operator

### ISSUE THREAD

**Issue by Co1lin** [tensorflow/tensorflow#57697]
### 1. System information

```python
❯ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

In [2]: tf.__version__
Out[2]: '2.11.0-dev20220914'
```

### 2. Code

```python
import tensorflow as tf
from keras import layers

def get_tflite_callable(model, inp_dict):
    converter = tf.lite.TFLiteConverter.from_concrete_functions(
        funcs=[model.__call__.get_concrete_function(**inp_dict)],
        trackable_obj=model,
    )
    tflite_bytes = converter.convert()
    interpreter = tf.lite.Interpreter(model_content=tflite_bytes)
    runner = interpreter.get_signature_runner()
    return runner

class MyModule(tf.Module):
    def __init__(self):
        super().__init__()
        self.dense_1 = layers.Dense(1)

    @tf.function
    def __call__(self, i0):
        o0 = tf.add(i0, tf.constant(1.1, shape=[1,1,1,1]))
        o0 = self.dense_1(o0) # a dense layer following an Add operator
        return o0


if __name__ == "__main__":
    inp = { "i0": tf.constant(0.2) }
    m = MyModule()
    runner = get_tflite_callable(m, inp)

    print(m(**inp)) # works fine
    
    print(runner(**inp)) # works fines
```

For TF, the model above works fine. But for TFLite, it raises an error as below.

```python
2022-09-14 10:46:53.593802: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-14 10:46:54.084941: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64::/home/colin/miniconda3/envs/py39/lib/
2022-09-14 10:46:54.085001: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64::/home/colin/miniconda3/envs/py39/lib/
2022-09-14 10:46:54.085008: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

tf.Tensor([[[[0.3788812]]]], shape=(1, 1, 1, 1), dtype=float32) # <--- works fine here for TF !

Traceback (most recent call last):
  File "/home/colin/code/test/scripts/tflite.py", line 39, in <module>
    print(runner(**inp)) # works fines
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/tensorflow/lite/python/interpreter.py", line 251, in __call__
    self._interpreter_wrapper.AllocateTensors(self._subgraph_index)
RuntimeError: tensorflow/lite/kernels/fully_connected.cc:434 input->dims->data[input->dims->size - 1] != SizeOfDimension(filter, 1) (0 != 1)Node number 0 (FULLY_CONNECTED) failed to prepare.
```

**Comment by Co1lin** [comment]
Hi! I dive into the source code, and I think this issue is caused by an illegal memory access.

In the example I provided above, the input tensor is a constant with no shape. However, in [this line](https://github.com/tensorflow/tensorflow/blob/8eaab9c021456dd9a46ea880632aa066a6f22898/tensorflow/lite/kernels/fully_connected.cc#L434), `input->dims->data[input->dims->size - 1]` is accessed while the array `input->dims->data` is empty I think. This illegal access got value `0`, which caused `(0 != 1)` in the error log.

**Comment by mohantym** [comment]
Hi @Co1lin !
Mistake was in declaring  the tf.constants in above code. Attached resolved [gist ](https://colab.sandbox.google.com/gist/mohantym/f3651f1599f0e3f44d43d4677a3b9c9e/git_57697.ipynb)for your reference.
Thank you!

**Comment by Co1lin** [comment]
Thanks for your reply and provided workaround! But I think this issue should be fixed in TFLite for the following reasons.

1. `tf.constant(3.14)` with no shape is a valid usage. For TF itself (but not TFLite), it works with those broadcasting operators. The code and model above can also work fine in TF eager mode, graph execution, or XLA, so TFLite should have a consistent behavior.

2. For `FullyConnected` in TFLite, it doesn't check the shape of the input tensor before trying to access `input->dims->data[input->dims->size - 1]` which is an illegal and dangerous behavior. TF should either check it or don't allow tensor without a shape (but this semantic is not consistent with other cases).

**Comment by mohantym** [comment]
@Co1lin !
Thanks for the update. 
@sachinprasadhs !
Could you look at this issue.
Thank you!

**Comment by Co1lin** [comment]
Ok. Then I think there should be a check for `tf.constant`.

**Comment by Co1lin** [comment]
BTW, I just verified that XLA also support this operation, using tensor without a shape, which is actually a scalar. So I still think TFLite should have a consistent behavior.

```python
2022-09-15 08:32:37.664348: I tensorflow/compiler/jit/xla_compilation_cache.cc:476] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
tf.Tensor([[[[-0.7349793]]]], shape=(1, 1, 1, 1), dtype=float32)
```

**Comment by mohantym** [comment]
@Co1lin @ganler !
I could replicate this issue in 2.11 . Attached gist in [2.11](https://colab.sandbox.google.com/gist/mohantym/b15d46567e309e20d9c86c3459576395/git_57697.ipynb#scrollTo=hTAO3p4D5b1R) for reference.
Thank you!

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
