### ISSUE TITLE
Misformatted documentation after constant_initializer

### ISSUE THREAD

**Issue by WuTheFWasThat** [tensorflow/tensorflow#5769]
The docs for constant_initializer fail to correctly close a code block in one of the examples.  As a result, many other sections are displayed in raw markdown.

See: https://www.tensorflow.org/versions/r0.11/api_docs/python/state_ops.html#constant_initializer

**Comment by Franck-Dernoncourt** [comment]
Is it fixed now? it looks ok to me.
