### ISSUE TITLE
Changing the number of (CPU) threads for cifar10

### ISSUE THREAD

**Issue by daothanhtuan** [tensorflow/tensorflow#577]
Whenever I run the cifar10_eval.py, in creates 32 threads as following:

I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 32

I think this number of threads is the number of threads running on CPUs, but when I check the usage, only 400-500% of CPUs are used. I wonder if there is anyway to change this number of threads?

Thanks

**Comment by jon--lee** [comment]
Did you figure out how to solve this issue?

**Comment by daothanhtuan** [comment]
yes, the answer is here
http://stackoverflow.com/questions/34389945/changing-the-number-of-threads-in-tensorflow-on-cifar10

**Comment by jon--lee** [comment]
Thank you!
