### ISSUE TITLE
`tf.broadcast_to` crashes with JIT

### ISSUE THREAD

**Issue by MThalberg** [tensorflow/tensorflow#57702]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### CUDA/cuDNN version

11.4

### Current Behaviour?

```shell
Session crashes when running the (compiled) `tf.broadcast_to` with an invalid shape, and can potentially trigger a denial of service attack. 
This bug only happens with using `@tf.function(jit_compile=True) `.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
input_tensor = tf.zeros([1, 1], dtype=tf.int32)

@tf.function(jit_compile=True) 
def f(input):
    shape = [-1, 1]
    return tf.broadcast_to(input, shape, ) 

f(input_tensor)
```

### Relevant log output

```shell
F tensorflow/core/framework/tensor_shape.cc:186] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Expected shape dimensions to be non-negative, got -1
abort
```
</details>

**Comment by MThalberg** [comment]
If we don't use JIT, then it will not crash, but throw an exception instead (which is expected). 
Below is the code (removing the JIT), it throws `InvalidArgumentError`.
```
import tensorflow as tf
input_tensor = tf.zeros([1, 1], dtype=tf.int32)


def f(input):
    shape = [-1, 1]
    return tf.broadcast_to(input, shape, ) 

f(input_tensor) # tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension -1 must be >= 0 [Op:BroadcastTo]
```

**Comment by lisalavigne** [comment]
。。

**Comment by tiruk007** [comment]
@MThalberg 
I tried to reproduce the issue in the latest version TF2.10 and the given code is successfully compiled without session crash. Could you please find the gist [here](https://colab.research.google.com/gist/tiruk007/fc7fc1924ec35db40490ad0d046736ab/57702.ipynb) and confirm the same? Please let us know if it helps.

Thank you!

**Comment by MThalberg** [comment]
Hi @tiruk007 , thanks for reproducing, it seems that this issue has been fixed on TF2.10. However, The session crash happens in TF2.9.1.

**Comment by tiruk007** [comment]
@MThalberg 
Could you please close the issue? The issue  is fixed in the latest version TF2.10
Thank you!
