### ISSUE TITLE
tensorflow build from source with bazel failed

### ISSUE THREAD

**Issue by dh-Kang** [tensorflow/tensorflow#57704]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf2.7-rc0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.6.9

### Bazel version

3.7.2

### GCC/Compiler version

7.5.0

### CUDA/cuDNN version

11.2/8.1

### GPU model and memory

N/A

### Current Behaviour?

```shell
I expected build success and I can get smaller size of tensorflow-lite.aar and tensorflow-lite-select-tf-ops.aar
```

### Standalone code to reproduce the issue

```shell
I want to reduce library size.
I checkout v2.7.0-rc0 tag and just followed this link (https://www.tensorflow.org/lite/guide/ops_select#building_the_android_aar).

## Configure
* No CUDA build
* Bazel Optimization flag : -D_GLIBCXX_USE_CXX11_ABI=0 -O3
* Android NDK version : 21.4.7075529
* Android NDK API Level : 21
* Android BuildTool Version : 30.0.3
* Android SDK API Level : 31
```

### Relevant log output

```shell
ERROR: /home/user/BIG/tensorflow/tmp/BUILD:19:28: C++ compilation of rule '//tmp:custom_tensorflowlite_flex_flex_delegate_tensorflow_lib' failed (Exit 1): clang failed: error executing command external/androidndk/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -gcc-toolchain external/androidndk/ndk/toolchains/x86_64-4.9/prebuilt/linux-x86_64 -target x86_64-none-linux-android -fPIC ... (remaining 154 argument(s) skipped)
In file included from tensorflow/core/kernels/list_kernels.cc:22:
In file included from ./tensorflow/core/kernels/list_kernels.h:50:
In file included from ./tensorflow/stream_executor/stream.h:32:
In file included from ./tensorflow/stream_executor/blas.h:46:
In file included from ./tensorflow/stream_executor/dnn.h:33:
./tensorflow/stream_executor/data_type.h:21:10: fatal error: 'tensorflow/stream_executor/dnn.pb.h' file not found
#include "tensorflow/stream_executor/dnn.pb.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Target //tmp:tensorflow-lite-select-tf-ops failed to build
```
</details>

**Comment by mohantym** [comment]
Hi @dh-Kang !
Could you share your build command too. (Colab gist Please)
Thank you!

**Comment by dh-Kang** [comment]
Sorry, I don't know about `Colab gist`
I just run below command with my env(described in issue template).
```
$git checkout v2.7.0-rc0
$./configure 
$bash tensorflow/lite/tools/build_aar.sh --input_models=/path/to/model.tflite --target_archs=x86_64,arm64-v8a
```

**Comment by mohantym** [comment]
@dh-Kang !
It seems to be failing for x86_64 build. 
You can opt for selective build in this case. 
`--target_archs==arm64-v8a,armeabi-v7a 
`

To add in few more pointers. 
1. Could you check again with 2.10.0 ( A lot of bugs has been fixed) and python 3.8/3.9 ( Python 3.7 minimum supported version) 

2. If issue still persists , Please build the flex environment with -D_GLIBCXX_USE_CXX11_ABI=1  and let us know.
Thank you!

**Comment by dh-Kang** [comment]
@mohantym Thank you for answer.

I need x86_64 also, because I need to run app in android emulator.
Is it impossible to build for x86_64?

And, I can't change tf version to 2.10.0, but I can try with other solutions (python version and flex env)
I'll update here.

One more thing..
After the bug, I tried to build below command without clean and I can success.
```
$bazel build //tmp:tensorflow-lite-select-tf-ops --verbose_failures
```

But the output aar is not working properly in android.
```
Failed to run on the given Interpreter: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select
Node number 13 (FlexEqual) failed to prepare.
```

**Comment by dh-Kang** [comment]
@mohantym 
Thank you for answer.

I already tried to build lower size of tflite.aar and tflite-select-tf-ops.aar. 
And I got failure but I could get aar(s) with this command ($bazel build //tmp:tensorflow-lite-select-tf-ops --verbose_failures)
Then, I put this aars in my project and removed maven official depdencies(tflite, select-ops both)
Then, I got error what I told you
```
Failed to run on the given Interpreter: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select
Node number 13 (FlexEqual) failed to prepare.
```

I guess, should I put libtensorflowlite_jni.so and libtensorflowlite_flex_jni.so into my project? I'm not sure..
Anyway I'm trying to run build_aar.sh again with python3.8.5 now.

**Comment by dh-Kang** [comment]
@mohantym 
1. I tried with python 3.8.5 => failed
2. I tried with python3.8.5 + `-D_GLIBCXX_USE_CXX11_ABI=1` => failed

I'm trying to clean build with option 2.

**Comment by dh-Kang** [comment]
And, Build takes over 4 hours.
Is there any faster way?

**Comment by mohantym** [comment]
@dh-Kang !
Thanks for the update.
@sachinprasadhs !
Could you look at this issue.

**Comment by dh-Kang** [comment]
> 2. I tried with python3.8.5 + -D_GLIBCXX_USE_CXX11_ABI=1 => failed

Clean build also failed

**Comment by sachinprasadhs** [comment]
Did you try with the prebuilt [AAR with TensorFlow ops hosted at MavenCentral](https://search.maven.org/artifact/org.tensorflow/tensorflow-lite-select-tf-ops)
