### ISSUE TITLE
Feature request for Cast, Minimum, RealDiv and ResizeNearestNeighbor operations in TensorFlow-Lite 

### ISSUE THREAD

**Issue by prabal27** [tensorflow/tensorflow#57703]
### 1. System information
-Linux Ubuntu 20.04
-TensorFlow installation-pip package
-TensorFlow library 2.10.0

### 2. Code

import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model("exported-model-test")

converter.optimizations = [tf.lite.Optimize.DEFAULT]

tflite_model = converter.convert()
open("exported-model/TF-Lite/DeepLabv3Plus_model_new1.tflite", "wb").write(tflite_model)

### 5. Info / logs

onverterError                            Traceback (most recent call last)
Input In [15], in <cell line: 13>()
      4 #converter.allow_custom_ops = True
      5 # converter.target_spec.supported_ops = [
      6 #   tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
      7 #   tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
      8 # ]
      9 #converter.experimental_new_converter = True
     11 converter.optimizations = [tf.lite.Optimize.DEFAULT]
---> 13 tflite_model = converter.convert()
     14 open("exported-model/TF-Lite/DeepLabv3Plus_model_new1.tflite", "wb").write(tflite_model)

File ~/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py:930, in _export_metrics.<locals>.wrapper(self, *args, **kwargs)
    927 @functools.wraps(convert_func)
    928 def wrapper(self, *args, **kwargs):
    929   # pylint: disable=protected-access
--> 930   return self._convert_and_export_metrics(convert_func, *args, **kwargs)

File ~/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py:908, in TFLiteConverterBase._convert_and_export_metrics(self, convert_func, *args, **kwargs)
    906 self._save_conversion_params_metric()
    907 start_time = time.process_time()
--> 908 result = convert_func(self, *args, **kwargs)
    909 elapsed_time_ms = (time.process_time() - start_time) * 1000
    910 if result:

File ~/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py:1213, in TFLiteSavedModelConverterV2.convert(self)
   1208 else:
   1209   self._debug_info = _get_debug_info(
   1210       _convert_debug_info_func(self._trackable_obj.graph_debug_info),
   1211       graph_def)
-> 1213 return self._convert_from_saved_model(graph_def)

File ~/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/lite.py:1096, in TFLiteConverterBaseV2._convert_from_saved_model(self, graph_def)
   1093 converter_kwargs.update(self._get_base_converter_args())
   1094 converter_kwargs.update(quant_mode.converter_flags())
-> 1096 result = _convert_saved_model(**converter_kwargs)
   1097 return self._optimize_tflite_model(
   1098     result, quant_mode, quant_io=self.experimental_new_quantizer)

File ~/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py:212, in convert_phase.<locals>.actual_decorator.<locals>.wrapper(*args, **kwargs)
    210   else:
    211     report_error_message(str(converter_error))
--> 212   raise converter_error from None  # Re-throws the exception.
    213 except Exception as error:
    214   report_error_message(str(error))

File ~/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert_phase.py:205, in convert_phase.<locals>.actual_decorator.<locals>.wrapper(*args, **kwargs)
    202 @functools.wraps(func)
    203 def wrapper(*args, **kwargs):
    204   try:
--> 205     return func(*args, **kwargs)
    206   except ConverterError as converter_error:
    207     if converter_error.errors:

File ~/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert.py:809, in convert_saved_model(**kwargs)
    807 model_flags = build_model_flags(**kwargs)
    808 conversion_flags = build_conversion_flags(**kwargs)
--> 809 data = convert(
    810     model_flags.SerializeToString(),
    811     conversion_flags.SerializeToString(),
    812     input_data_str=None,
    813     debug_info_str=None,
    814     enable_mlir_converter=True)
    815 return data

File ~/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert.py:311, in convert(model_flags_str, conversion_flags_str, input_data_str, debug_info_str, enable_mlir_converter)
    309     for error_data in _metrics_wrapper.retrieve_collected_errors():
    310       converter_error.append_error(error_data)
--> 311     raise converter_error
    313 return _run_deprecated_conversion_binary(model_flags_str,
    314                                          conversion_flags_str, input_data_str,
    315                                          debug_info_str)

ConverterError: <unknown>:0: error: loc(callsite(callsite(fused["Cast:", "truediv/Cast_1@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): 'tf.Cast' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
<unknown>:0: note: loc(callsite(callsite(fused["Cast:", "truediv/Cast_1@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: loc(callsite(callsite(fused["Cast:", "truediv_1/Cast_1@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): 'tf.Cast' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
<unknown>:0: note: loc(callsite(callsite(fused["Cast:", "truediv_1/Cast_1@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: loc(callsite(callsite(fused["RealDiv:", "truediv@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): 'tf.RealDiv' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
<unknown>:0: note: loc(callsite(callsite(fused["RealDiv:", "truediv@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: loc(callsite(callsite(fused["RealDiv:", "truediv_1@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): 'tf.RealDiv' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
<unknown>:0: note: loc(callsite(callsite(fused["RealDiv:", "truediv_1@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: loc(callsite(callsite(fused["Minimum:", "Minimum@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): 'tf.Minimum' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
<unknown>:0: note: loc(callsite(callsite(fused["Minimum:", "Minimum@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: loc(callsite(callsite(fused["Cast:", "Cast_1@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): 'tf.Cast' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
<unknown>:0: note: loc(callsite(callsite(fused["Cast:", "Cast_1@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: loc(callsite(callsite(fused["ResizeNearestNeighbor:", "resize_align_corners_1/ResizeNearestNeighbor@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): 'tf.ResizeNearestNeighbor' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
<unknown>:0: note: loc(callsite(callsite(fused["ResizeNearestNeighbor:", "resize_align_corners_1/ResizeNearestNeighbor@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: failed while converting: 'main': 
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: Cast, Minimum, RealDiv, ResizeNearestNeighbor
Details:
	tf.Cast(tensor<f64>) -> (tensor<f32>) : {Truncate = false, device = ""}
	tf.Cast(tensor<i32>) -> (tensor<f64>) : {Truncate = false, device = ""}
	tf.Minimum(tensor<f64>, tensor<f64>) -> (tensor<f64>) : {device = ""}
	tf.RealDiv(tensor<f64>, tensor<f64>) -> (tensor<f64>) : {device = ""}
	tf.ResizeNearestNeighbor(tensor<1x?x?x1xi32>, tensor<2xi32>) -> (tensor<1x?x?x1xi32>) : {align_corners = true, device = "", half_pixel_centers = false}

(callsite(fused["Minimum:", "Minimum@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): error: 'tf.Minimum' op is neither a custom op nor a flex op
loc(callsite(callsite(fused["Cast:", "Cast_1@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): error: 'tf.Cast' op is neither a custom op nor a flex op
loc(callsite(callsite(fused["ResizeNearestNeighbor:", "resize_align_corners_1/ResizeNearestNeighbor@__inference___call___6210"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_6889"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): error: 'tf.ResizeNearestNeighbor' op is neither a custom op nor a flex op
error: failed while converting: 'main': 
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: Cast, Minimum, RealDiv, ResizeNearestNeighbor
Details:
	tf.Cast(tensor<f64>) -> (tensor<f32>) : {Truncate = false, device = ""}
	tf.Cast(tensor<i32>) -> (tensor<f64>) : {Truncate = false, device = ""}
	tf.Minimum(tensor<f64>, tensor<f64>) -> (tensor<f64>) : {device = ""}
	tf.RealDiv(tensor<f64>, tensor<f64>) -> (tensor<f64>) : {device = ""}
	tf.ResizeNearestNeighbor(tensor<1x?x?x1xi32>, tensor<2xi32>) -> (tensor<1x?x?x1xi32>) : {align_corners = true, device = "", half_pixel_centers = false}

**Comment by burushuijiaoba** [comment]
hahha

**Comment by mohantym** [comment]
Hi @prabal27 !
Above error "Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select "  is suggesting  to use select ops syntax.
```
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
```
In the template, I can see below code and in error log it seems you might be used select ops syntax.

Could you share the code snippet for the model ( a toy model would also be fine.)

Thank you!

**Comment by prabal27** [comment]
Yeah I have used the above suggested method by enabling to fallback on TensorFlow ops, and I was able to create a tflite model but when I am trying to interpret this model using: 

### Code:
interpreter = tf.lite.Interpreter(model_path="exported-model/TF-Lite/DeepLabv3Plus_model_new1.tflite")
interpreter.allocate_tensors()

### Error:

I am getting following error:

RuntimeError                              Traceback (most recent call last)
Input In [1], in <cell line: 6>()
      4 # Load TFLite model and allocate tensors.
      5 interpreter = tf.lite.Interpreter(model_path="exported-model/TF-Lite/DeepLabv3Plus_model_new1.tflite")
----> 6 interpreter.allocate_tensors()

File ~/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/interpreter.py:513, in Interpreter.allocate_tensors(self)
    511 def allocate_tensors(self):
    512   self._ensure_safe()
--> 513   return self._interpreter.AllocateTensors()

RuntimeError: Encountered unresolved custom op: Cast.
See instructions: https://www.tensorflow.org/lite/guide/ops_custom Node number 9 (Cast) failed to prepare.Encountered unresolved custom op: Cast.
See instructions: https://www.tensorflow.org/lite/guide/ops_custom Node number 9 (Cast) failed to prepare.

### Question

I wanted to ask if we can replace these operations with newer operations which are supported by TFLite or do we need to register these operators to a new TFLite kernel?

**Comment by mohantym** [comment]
Ok @prabal27 !
Thanks for the update.  
Could you run the inference again after  adding custom ops flag before conversion and let us know.Tha
```
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]

converter.allow_custom_ops = True

```
Thank you!

**Comment by prabal27** [comment]
Hello @mohantym,

I added the custom ops flag and I was able to create a model with following warnings:
```
2022-09-16 11:29:59.810343: I tensorflow/cc/saved_model/loader.cc:305] SavedModel load for tags { serve }; Status: success: OK. Took 1065806 microseconds.
2022-09-16 11:30:02.447049: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:1918] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following Select TFop(s):
Flex ops: FlexCast, FlexMinimum, FlexRealDiv, FlexResizeNearestNeighbor
Details:
	tf.Cast(tensor<f64>) -> (tensor<f32>) : {Truncate = false, device = ""}
	tf.Cast(tensor<i32>) -> (tensor<f64>) : {Truncate = false, device = ""}
	tf.Minimum(tensor<f64>, tensor<f64>) -> (tensor<f64>) : {device = ""}
	tf.RealDiv(tensor<f64>, tensor<f64>) -> (tensor<f64>) : {device = ""}
	tf.ResizeNearestNeighbor(tensor<1x?x?x1xi32>, tensor<2xi32>) -> (tensor<1x?x?x1xi32>) : {align_corners = true, device = "", half_pixel_centers = false}
See instructions: https://www.tensorflow.org/lite/guide/ops_select 
```
Then I tried to load the model on my personal machine with Tensorflow version 2.10.0  with following code: 
```
interpreter = tf.lite.Interpreter(model_path="exported-model/TF-Lite/DeepLabv3Plus_model.tflite")
interpreter.allocate_tensors()
```
And it was able to load the model with no errors but when I am doing the same on my edge device which has tflite_runtime.__version__ of 2.4.0, I was getting this error 
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-0add8ba10a38> in <module>
      7 
      8 tidl_delegate = [tflite.load_delegate(os.path.join(os.environ['TIDL_TOOLS_PATH'], 'tidl_model_import_tflite.so'), compile_options)]
----> 9 interpreter = tflite.Interpreter(model_path=tflite_model_path, experimental_delegates=tidl_delegate)
     10 interpreter.allocate_tensors()
     11 

/usr/local/lib/python3.6/dist-packages/tflite_runtime/interpreter.py in __init__(self, model_path, model_content, experimental_delegates, num_threads)
    244       for delegate in self._delegates:
    245         self._interpreter.ModifyGraphWithDelegate(
--> 246             delegate._get_native_delegate_pointer())  # pylint: disable=protected-access
    247 
    248   def __del__(self):

RuntimeError: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.Node number 9 (FlexCast) failed to prepare.
```

**Comment by mohantym** [comment]
ok @prabal27 !
Thanks for the update. 
Tflite_runtime does not have select ops support . Please use full TensorFlow package instead (which will include select ops runtime by default)

[Reference](https://www.tensorflow.org/lite/guide/python#install_just_the_tensorflow_lite_interpreter:~:text=Note%3A%20If,TensorFlow%20package%20instead.). 

Thank you!
