### ISSUE TITLE
Documentation of  tf.extract_image_patches is incomplete and slightly inaccurate

### ISSUE THREAD

**Issue by deeptigp** [tensorflow/tensorflow#5770]
Hi,

The documentation of [tf.extract_image_patches](https://www.tensorflow.org/versions/r0.9/api_docs/python/array_ops.html#extract_image_patches) is unclear and slightly incorrect. 

1. The function call requires the first 5 parameters to be set and throws an error otherwise.The documentation, however, mentions that they are optional parameters.
2. The "out_rows" and "out_cols" are not defined making it hard to make sense of what this function is actually doing. 
3. The definition of "rates" is not clear.. Is patch_size same as k_rows or k_cols?

Running
`test_patches = tf.extract_image_patches(images, padding="SAME",ksizes=[1, 32, 32, 1], strides=[1, 32, 32, 1], rates=[1,1, 1, 1])
`
where images = 1X299x299x3 returns me a tensor (test_patches) of shape 1x10x10x3072. 

1.Is test_patches[0,0,0,:] the first patch test_patches[0,0,1,:] the second patch and so on? 
2. If (1) is true, how was the dimension of a patch reduced from 32x32x3 to 3072, i.e., how exactly should this be reshaped? I tried reshaping test_patches[0,0,0,:] to (32,32,3) and (3,32,32) but the resulting image patch does not make sense. 

Clarifying the documentation of this method would be immensely helpful!

### Environment info
Ubuntu 14.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
-rw-r--r-- 1 root root   558720 Oct 22 01:37 /opt/cuda-8.0/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Oct 22 01:37 /opt/cuda-8.0/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Oct 22 01:37 /opt/cuda-8.0/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rwxr-xr-x 1 root root   415432 Oct 22 01:37 /opt/cuda-8.0/lib64/libcudart.so.8.0.44
-rw-r--r-- 1 root root   775162 Oct 22 01:37 /opt/cuda-8.0/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 79337624 Oct 22 01:48 /opt/cuda-8.0/lib64/libcudnn.so
-rwxr-xr-x 1 root root 79337624 Oct 22 01:48 /opt/cuda-8.0/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 79337624 Oct 22 01:48 /opt/cuda-8.0/lib64/libcudnn.so.5.1.5
-rw-r--r-- 1 root root 69756172 Oct 22 01:48 /opt/cuda-8.0/lib64/libcudnn_static.a

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`)
1f9e1eb186325dc789e7ea28aa5f7ef1e183f6b9
2. The output of `bazel version`

Build label: 0.3.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Oct 7 17:25:10 2016 (1475861110)
Build timestamp: 1475861110
Build timestamp as int: 1475861110

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

Just calling this function would do.

**Comment by aselle** [comment]
I made a change to document these aspects internally, it should make its way externally in a couple of days. Thanks!
