### ISSUE TITLE
Memory issue using Pose Estimation model

### ISSUE THREAD

**Issue by IBSApple** [tensorflow/tensorflow#57717]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML', 'Metal']

### Custom Code

No

### OS Platform and Distribution

MacOS

### Mobile device

iPhone X

### Current Behaviour?

```shell
memory not deallocated once I back to root VC.

App crashes after some time.
```

### Standalone code to reproduce the issue

```shell
I used Tensorflow sample example, and added one empty page before that, on click button will redirect to next camera screen.

This process I done many time so after some time memory issue will be occurred & app crash.
```

### Relevant log output

_No response_</details>

**Comment by IBSApple** [comment]
https://user-images.githubusercontent.com/71369657/190563962-3a001cc0-9178-437e-9c80-8f0ebbb3aceb.mp4

**Comment by IBSApple** [comment]
Also I stop running, in viewWillDisappear  

 override func viewWillDisappear(_ animated: Bool) {
    super.viewWillDisappear(animated)
    cameraFeedManager?.stopRunning()
  }

**Comment by mohantym** [comment]
Ok @IBSApple !
Please clarify my query . Your Sign it button is routing to camera for [pose estimation ](https://github.com/tensorflow/examples/tree/master/lite/examples/pose_estimation/android) and it is exiting camera after 5-10 second.  Right?

Thank you!

**Comment by IBSApple** [comment]
I used  Swift language for iOS app in this used

self.navigationController?.pushViewController(cameraVC, animated: true)

to redirect camera screen.

**Comment by IBSApple** [comment]
??

**Comment by mohantym** [comment]
Hi @IBSApple !
Sorry! I did not get time to replicate this issue yesterday . will update today. 

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by IBSApple** [comment]
any update please...

**Comment by mohantym** [comment]
@IBSApple !
I ran the pose estimation code for android . The memory was constant throughout the operation.
I suspect that it might be specific to IOS 15.5 .  Similar memory leak issues [1](https://github.com/tensorflow/tensorflow/issues/57718), [2](https://github.com/tensorflow/tensorflow/issues/56287).
Thank you!

**Comment by IBSApple** [comment]
Shall I use PoseNet instead of Pose Estimation for iOS app?

**Comment by mohantym** [comment]
Hi @IBSApple !
I would suggest to give a try in [movenet ](https://www.tensorflow.org/hub/tutorials/movenet)( better performance compared to posenet) .
Thank you!

**Comment by IBSApple** [comment]
Okay is there any sample demo available for iOS in swift?

**Comment by trinhtranduc** [comment]
Hi @IBSApple , I got very same issue. Have you found any solution/workaround way on this issue?

**Comment by sachinprasadhs** [comment]
Hi, This seems similar to the issue here https://github.com/tensorflow/tensorflow/issues/56287.
Could you please close this issue and track the progress in the linked issue since there is an ongoing discussion and team is looking into the issue. Thanks!

**Comment by yishuangP** [comment]
Hi, I just updated pose estimation example to use our latest nightly version 0.0.1-nightly.20230405. I don't see this memory issue. Could you double check?

**Comment by sachinprasadhs** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
