### ISSUE TITLE
tf.with_dependencies isn't exposed, but it is used in documentations

### ISSUE THREAD

**Issue by bc-lee** [tensorflow/tensorflow#5771]
There are some examples that uses tf.with_dependencies (ex. [tf.Assert in r0.11](https://www.tensorflow.org/versions/r0.11/api_docs/python/control_flow_ops.html#Assert)) but tf.with_dependencies isn't exposed to tensorflow module.

### Environment info
branch: master branch $ git rev-parse HEAD => c7edafccc

### If possible, provide a minimal reproducible example
```
$ python3 -c "import tensorflow as tf; tf.with_dependencies()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'with_dependencies'
```
Related: (https://github.com/tensorflow/tensorflow/blob/a4c8df209d7413068f4ed3e71c43eb798fbd5580/tensorflow/contrib/layers/python/layers/layers_test.py#L25)

**Comment by prb12** [comment]
Looks like it is maybe being removed by this: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/__init__.py#L241
```
# Remove all extra symbols that don't have a docstring or are not explicitly
# referenced in the whitelist.
remove_undocumented(__name__, _allowed_symbols,
                    [framework_lib, array_ops, client_lib, check_ops,
                     compat, constant_op, control_flow_ops, functional_ops,
                     histogram_ops, io_ops, math_ops, nn, resource_loader,
                     resources, script_ops, session_ops, sparse_ops, state_ops,
                     string_ops, summary, tensor_array_ops, train])
```
@drpngx Is this correct?

**Comment by drpngx** [comment]
We have lots of internal uses for that, so I'm assuming that all commits on master work, but there might be some cherry-picks in 0.11 that don't work. Let's see if I can repro first.

**Comment by drpngx** [comment]
It looks like it was not part of our public API, even though it was documented. Looping internally for a fix. You'll have to upgrade.

**Comment by drpngx** [comment]
Actually, there `tf.control_dependencies` that provides the core functionality, and you should just use that. I'll update the doc.

**Comment by drpngx** [comment]
Submitted change internally to remove the doc example. It'll be pushed to the main repo soon.
