### ISSUE TITLE
tf.quantization.quantize_and_dequantize (and v2) crash (abort)

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#57714]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.11.0-dev20220914

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.4 LTS (x86_64)

### Python version

3.7.6

### CUDA/cuDNN version

N/A

### Current Behaviour?

`tf.quantization.quantize_and_dequantize` and `tf.quantization.quantize_and_dequantize_v2` crash with abortion

Also reproduced in the [gist](https://colab.research.google.com/drive/1gr2mX4G2qWQanate4tslrQNByU-sqI0s?usp=sharing)

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf
tf.quantization.quantize_and_dequantize_v2(input=np.ones((10)),input_min=-1,input_max=[-1,1], range_given=True)
```

### Relevant log output

```shell
2022-09-15 19:54:27.500788: F tensorflow/core/framework/tensor.cc:733] Check failed: 1 == NumElements() (1 vs. 2)Must have a one element tensor
Aborted (core dumped)
```
</details>

**Comment by tilakrayal** [comment]
@gadagashwini,
I was able to reproduce the issue on tensorflow v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/ca24b813866ca784f5b25677e7ec9495/untitled600.ipynb).
