### ISSUE TITLE
tf.keras.backend.eye crash (abort) with large input

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#57711]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.11.0-dev20220914

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.4 LTS (x86_64)

### Python version

3.7.6

### CUDA/cuDNN version

N/A

### Current Behaviour?

`tf.keras.backend.eye` and `tf.eye` crash (abort) with large input

Also reproduced in this [gist](https://colab.research.google.com/drive/1UEeiUYXSKSU1cBqUs01d_M1RkXgSflEw?usp=sharing)

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
tf.keras.backend.eye(size=2752212975)
```

```shell
import tensorflow as tf
tf.eye(2752212975)
```

### Relevant log output

```shell
2022-09-15 18:51:32.477313: F tensorflow/core/framework/tensor_shape.cc:572] Check failed: size >= 0 (0 vs. -1542754321)
Aborted (core dumped)
```
</details>

**Comment by tilakrayal** [comment]
@sachinprasadhs, 
I was able to reproduce the issue on tensorflow v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/1e6f4f263815f9f0a3ab18cc034bbaaa/untitled597.ipynb).

**Comment by sachinprasadhs** [comment]
This is due to the very large input which is causing OOM/ memory overflow with large input, when you try large value like tf.int32.max, you will get the error output.
Below is the error output.

```
import tensorflow as tf
tf.eye(2147483647)

ResourceExhaustedError: OOM when allocating tensor with shape[2147483647,2147483647] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu [Op:MatrixDiagV3] name: diag 
```

**Comment by DNXie** [comment]
@sachinprasadhs  Hi, Thanks for looking into this. With the input I provided, I see a crash (abortion) instead of an OOM error. 

As public APIs, it would be great to have the functions kindly throw exceptions for these cases instead of crashing.

**Comment by yongtang** [comment]
Added a PR #57790 for the fix.
