### ISSUE TITLE
tf.nn.conv2d_transpose crash with abort whtn `output_shape` has negative value

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#57715]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.11.0-dev20220914

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.4 LTS (x86_64)

### Python version

3.7.6

### CUDA/cuDNN version

N/A

### Current Behaviour?

`tf.nn.conv2d_transpose` crash with abort whtn `output_shape` has negative value

Also reproduced in this [gist](https://colab.research.google.com/drive/1Yx5pvWM7HoVpwAmCfzU5DIi1Y9IRsHrP?usp=sharing)

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf
tf.nn.conv2d_transpose(input=np.ones((1,1,1,1)), filters=np.ones((1,1,1,1)), output_shape=[2,-2], strides=[1])
```

### Relevant log output

```shell
2022-09-15 20:35:37.763729: F tensorflow/core/framework/tensor_shape.cc:186] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Expected shape dimensions to be non-negative, got -2
Aborted (core dumped)
```
</details>

**Comment by tiruk007** [comment]
@gadagashwini 
I was able to reproduce the issue on Colab using TF v2.10. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/b4a7e48d9c5111053b5cd3b8a809b464/57715.ipynb) for reference
Thank you!

**Comment by yongtang** [comment]
Created a PR #57787 for the fix.
