### ISSUE TITLE
log, pow, div unsupported in 16x8 precision

### ISSUE THREAD

**Issue by blaine-fs** [tensorflow/tensorflow#57725]
It seems these ops are supported in 8x8 mode, but not in 16x8. The latter is very important for our organization, as it saves a lot of rounding error over 8x8. Is full 16x8 support on the current roadmap? If not, could we help to contribute this feature?

### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 22.04
- TensorFlow installation (pip package or built from source): pip tf-nightly
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.11.0-dev20220916 

### 2. Code

```
import numpy as np
import tensorflow as tf
import keras

def data_generator():
    for x in range(1, 100):
        yield [np.array(x).astype(np.float32)]

def test_layer(layer):
    model = tf.keras.Model(inputs=[in_tensor], outputs=[layer])
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.representative_dataset = data_generator
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8
    ]
    converter.inference_input_type = tf.int16
    converter.inference_output_type = tf.int16
    try:
        tflite_model = converter.convert()
    except Exception as e:
        print("Received exception:\n%s" % str(e))

in_tensor = tf.keras.Input(shape=(1,))
test_layer(tf.math.log(in_tensor))
test_layer(in_tensor ** 3)
test_layer(in_tensor / in_tensor)
```

### 3. Failure after conversion

Conversion fails, with the following error messages:

> Quantization to 16x8-bit not yet supported for op: 'LOG'.
> Quantization to 16x8-bit not yet supported for op: 'POW'.
> Quantization to 16x8-bit not yet supported for op: 'DIV'.

**Comment by mohantym** [comment]
Hi @blaine-fs !
If 16x8 quantization is not supported for some operators in the model, then the model still can be quantized, but unsupported operators kept in float. The following option should be added to the target_spec to allow this.

` converter.target_spec.supported_ops = [tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8,tf.lite.OpsSet.TFLITE_BUILTINS]`

Attached [gist](https://colab.sandbox.google.com/gist/mohantym/f2aa52f22e9ff516bdafa9fbabad98e1/git_57725.ipynb#scrollTo=O5mqA8rMKFUC) for reference.
[
Reference](https://www.tensorflow.org/lite/performance/post_training_quantization#:~:text=If%2016x8%20quantization%20is%20not%20supported%20for%20some%20operators%20in%20the%20model%2C%20then%20the%20model%20still%20can%20be%20quantized%2C%20but%20unsupported%20operators%20kept%20in%20float.%20The%20following%20option%20should%20be%20added%20to%20the%20target_spec%20to%20allow%20this.)
Thank you!

**Comment by blaine-fs** [comment]
Hi @mohantym. 

Thanks for the tip. Keeping those ops in float is better than nothing. At least they don't have weights, so we should be guaranteed that all model parameters are quantized to int8.

In our use case, we are developing a compiler backend for TFLite which targets an inference accelerator.  Like most inference accelerators, it lacks hardware support for floating point, so we would really rather have TFLite code that only consists of fixed-point ops.

We could work around this by doing the float -> fixed conversion in our backend, but it seems like TFLite should be able to do this on its own, and can do it for 8x8 already. So we would like to know if there are any plans to expand 16x8 support, or if it would be open to community contributions.

**Comment by blaine-fs** [comment]
Actually, looking at the MLIR dialect [spec](https://www.tensorflow.org/mlir/tfl_ops), it seems like some of these ops (for example `tfl.log`) do not support fixed point at all. When I try to compile these in 8x8 mode, I seem to silently get floating points ops. Do we always need to allow floating point if we want to use these operators? Or put another way, is full integer quantization only supported for a subset of TFLite?

**Comment by mohantym** [comment]
Ok @blaine-fs !
Thanks for the update. 

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by pjpratik** [comment]
I was able to reproduce the issue in TF 2.11 and TF Nightly. Please find the gist [here](https://colab.sandbox.google.com/gist/pjpratik/67fa76e664982af41ddd3ecb27a84b4e/57725.ipynb). Thank you.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
