### ISSUE TITLE
Meaning of the "FlexErf" node? 

### ISSUE THREAD

**Issue by dgrnd4** [tensorflow/tensorflow#57721]
I'm using the vit_keras.vit.Vit_b32 and I am trying to understand what is the meaning of the "FlexErf" node. 
Can someone explain?

I think that Is probably linked with the ERF (error function) computation...

**Comment by mohantym** [comment]
@dgrnd4 !
It is [gauss error function](https://www.tensorflow.org/lite/guide/op_select_allowlist#:~:text=raw_ops.Equal-,raw_ops.Erf,-raw_ops.Exit) (Erf) and included in select ops list. 

So It might be renaming the node as flexErf. ( flex op Erf)

Thank you!

**Comment by dgrnd4** [comment]
Many thanks, closing the issue

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
