### ISSUE TITLE
`tf.random.learned_unigram_candidate_sampler` crash with segmentation fault

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#57724]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.11.0-dev20220914

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.4 LTS (x86_64)

### Python version

3.7.6

### CUDA/cuDNN version

N/A

### Current Behaviour?

`tf.random.learned_unigram_candidate_sampler` crash with segmentation fault when `batch_size` is large.

Also reproduced in the [gist](https://colab.research.google.com/drive/1sz2P703JMLaq_6DR92jf4R-d5jxs4I52?usp=sharing)

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf
tf.random.learned_unigram_candidate_sampler(true_classes=np.array([[1000000]]), num_true=1,num_sampled=1,unique=False,range_max=1)
```

### Relevant log output

```shell
Segmentation fault (core dumped)
```
</details>

**Comment by tiruk007** [comment]
@gadagashwini 
I was able to reproduce the issue on Colab using TF v2.10.Please find the gist [here](https://colab.research.google.com/gist/tiruk007/8e7b1144e602bf2f6194c3bcfb258d6b/57724.ipynb) for reference .
Thank you!

**Comment by sachinprasadhs** [comment]
Thanks for reporting the bug, it's strange that it works well when the input is provided is of int64 max value and throws error when the input is greater than max int64 value. 
[Here](https://colab.sandbox.google.com/gist/sachinprasadhs/bef0540045f65591a32e4568911c013d/57724.ipynb) is the gist with my observation. 
We will look into it. Thanks!

**Comment by tilakrayal** [comment]
@DNXie,
I tried to execute the mentioned code on tf-nightly(2.17.0-dev20240407) and observed that it was executed without any crash and providing the error message of why it was failing. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/54678db4c23e768c944648f510824c27/untitled1835.ipynb). Thank you!
