### ISSUE TITLE
tf.random.poisson crash(abort)

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#57728]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.11.0-dev20220914

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.4 LTS (x86_64)

### Python version

3.7.6

### CUDA/cuDNN version

N/A

### Current Behaviour?

```shell
tf.random.poisson crash(abort)
```

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf 
tf.random.poisson(lam=np.ones((10,10,11,2)), shape=[27, 187, 229])
```

### Relevant log output

```shell
2022-09-16 19:45:10.220556: F tensorflow/core/util/work_sharder.cc:34] Check failed: total >= 0 (0 vs. -1751281096)
Aborted (core dumped)
```
</details>

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I tried to execute the code in colab with tf v2.8, v2.9 & nightly and noticed that session is being crashed. Kindly find the gist [here](https://colab.research.google.com/gist/tilakrayal/5b51e660cd19f9634949649af9eb0ea5/untitled605.ipynb).

**Comment by DNXie** [comment]
@tilakrayal Thanks for looking into this. With the input I provided, I see a crash (abortion) instead of an OOM error.
As public APIs, it would be great to have the functions kindly throw exceptions for these cases instead of crashing. Also replied in #57711. Thank you!

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/5b51e660cd19f9634949649af9eb0ea5/untitled605.ipynb).

**Comment by yongtang** [comment]
Added a PR #57852 for the fix.
