### ISSUE TITLE
Unable to import hdf5_format  from tensorflow.python.keras.saving

### ISSUE THREAD

**Issue by visionscaper** [tensorflow/tensorflow#57730]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.10.0-rc3-6-g359c3cdfc5f 2.10.0

### Custom Code

Yes

### OS Platform and Distribution

MacOS 12.5.1

### Python version

Python 3.8.9

### Current Behaviour?

In the past I was able to load the `hdf5_format` module as follows:

```
from tensorflow.python.keras.saving import hdf5_format
```

Now this code seems not accessible anymore:

```
ModuleNotFoundError: No module named 'tensorflow.python'
``` 

How to import the `hdf5_format` module in TF2.10.0?

### Standalone code to reproduce the issue

```
from tensorflow.python.keras.saving import hdf5_format
```

### Relevant log output

```
ModuleNotFoundError: No module named 'tensorflow.python'
```
</details>

**Comment by mohantym** [comment]
Hi @visionscaper !
I could not replicate this issue through [colab](https://colab.sandbox.google.com/drive/158f5FfZsPaqzAuvYIZUDSDywwshlpMeC?resourcekey=0-wU9NrFkuWJpTxjstTsgduQ#scrollTo=CVDSNSlGKm3E)  or my mac M1 pro . For Mac OS. Pleas refer [instructions](https://developer.apple.com/metal/tensorflow-plugin/) from Apple forum for Tensorflow installation.
Thank you!

**Comment by visionscaper** [comment]
Hi @mohantym, 

Thanks for your time.

Yesterday evening I found out that this issue occurs when running code, that imports Tensorflow code, within the JetBrains PyCharm IDE. See this JetBrains [issue](https://youtrack.jetbrains.com/issue/PY-34174?_ga=2.242324871.427713854.1663416723-517612459.1663416723&_gl=1*dptnfy*_ga*NTE3NjEyNDU5LjE2NjM0MTY3MjM.*_ga_9J976DJZ68*MTY2MzQxNjcyMy4xLjEuMTY2MzQxNjk5NS4wLjAuMA..)

I will close this issue, but apparently Tensorflow is doing something so exotic with (dynamically) setting up the Python package structure that PyCharms breaks down. For reference, I never had such issues with PyTorch in the PyCharm IDE.

Maybe this could be something to also look in to from the Tensorflow side?

**Comment by mohantym** [comment]
Ok @visionscaper !
Thanks for the feedback. We will update the Team on this insight.

**Comment by sachinprasadhs** [comment]
Update:  New import mechanism for Keras is all set to release in upcoming TensorFlow 2.13. 
Refer the thread here https://github.com/tensorflow/tensorflow/issues/56231#issuecomment-1484041464
