### ISSUE TITLE
error with building with bazel

### ISSUE THREAD

**Issue by blockhead100** [tensorflow/tensorflow#57731]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

pop_os

### Python version

3.9

### Bazel version

0.26.0

### GCC/Compiler version

11.2.0

### Current Behaviour?

```shell
crashes after 10-15 min of compiling. Im running first gen intel so some of the options i have selected cant be run?
```

### Standalone code to reproduce the issue

```shell
i dont know if is repeatable but i ran this: bazel build -c opt --copt=-mfma --copt=-msse4.2 //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```shell
ERROR: /home/bryce/.cache/bazel/_bazel_bryce/bd1d213a6ffc70c3426679580b755b10/external/com_google_absl/absl/synchronization/BUILD.bazel:29:1: C++ compilation of rule '@com_google_absl//absl/synchronization:graphcycles_internal' failed (Exit 1)
```
</details>

**Comment by tilakrayal** [comment]
@blockhead100,
Could you try `bazel clean --expunge` followed by bazel sync and also please confirm if you are trying to follow the instructions mentioned [here](https://www.tensorflow.org/install/source) in the office document. Thank you

**Comment by blockhead100** [comment]
Thanks so much for the response i got it past that point and encountered a new error: ERROR: /home/bryce/Desktop/Neural_Networks/tensorflow/tensorflow/tensorflow/core/BUILD:2762:1: Executing genrule //tensorflow/core:version_info_gen failed (Exit 127)
/usr/bin/env: 'python': No such file or directory

73 Block_head

**Comment by blockhead100** [comment]
i fixed the previous error but theirs a new one:
ERROR: /home/bryce/.cache/bazel/_bazel_bryce/bd1d213a6ffc70c3426679580b755b10/external/com_google_absl/absl/synchronization/BUILD.bazel:29:1: C++ compilation of rule '@com_google_absl//absl/synchronization:graphcycles_internal' failed (Exit 1)
external/com_google_absl/absl/synchronization/internal/graphcycles.cc: In member function 'void absl::synchronization_internal::GraphCycles::RemoveNode(void*)':
external/com_google_absl/absl/synchronization/internal/graphcycles.cc:450:26: error: 'numeric_limits' is not a member of 'std'
  450 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                          ^~~~~~~~~~~~~~
external/com_google_absl/absl/synchronization/internal/graphcycles.cc:450:49: error: expected primary-expression before '>' token
  450 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                                                 ^
external/com_google_absl/absl/synchronization/internal/graphcycles.cc:450:52: error: '::max' has not been declared; did you mean 'std::max'?
  450 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
      |                                                    ^~~
      |                                                    std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from external/com_google_absl/absl/synchronization/internal/graphcycles.cc:38:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: 'std::max' declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 319.010s, Critical Path: 50.61s
INFO: 352 processes: 352 local.
FAILED: Build did NOT complete successfully

**Comment by blockhead100** [comment]
This had been fixed!

**Comment by gadagashwini** [comment]
Hi @blockhead100, Glad that it got fixed, looks like issue with Bazel version, In this case you are using old Bazel version 0.26. For Tensorflow 2.9, you must use Bazel 5.0.0. Thank you!
