### ISSUE TITLE
is it possible to use tf.distribute.MirroredStrategy on Intel Xeon Scalable Processors (with 2 sockets)

### ISSUE THREAD

**Issue by SriramR474** [tensorflow/tensorflow#57743]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04.4

### Python version

3.8.10

### Current Behaviour?

```shell
I am using Intel Xeon Scalable Processor(with 2 sockets - 20 Cores per each Socket). My batch_size = 2048 and total batches = 2600. Is it possible to split the total batches and run 1300 batches in parallel on each CPU socket using tf.distribute.MirroredStrategy?

Here in the below code, even though my server has 2 CPU sockets, the no.of devices getting detected is just 1.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

import numpy as np
import os

print(tf.__version__)

strategy = tf.distribute.MirroredStrategy()
print("strategy:",strategy)

print('Number of devices: {}'.format(strategy.num_replicas_in_sync))
```

### Relevant log output

_No response_</details>

**Comment by gadagashwini** [comment]
Hi @SriramR474, If no GPUs are found, it will use the available CPUs. Note that TensorFlow treats all CPUs on a machine as a single device, and uses threads internally for parallelism. Please take a look at reference [link](https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy?version=nightly). Thank you!

**Comment by ashiqimranintel** [comment]
Hi @SriramR474 , to get the best performance on Intel Xeon Scalable Processors, I would suggest you to use Horovod. you can our blog 
https://www.intel.com/content/www/us/en/developer/articles/technical/distributed-training-on-intel-xeon-scalalable-cpus.html
