### ISSUE TITLE
pow operation gives valid output even the input is invalid

### ISSUE THREAD

**Issue by Ishaan233** [tensorflow/tensorflow#57757]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.8.2

### Custom Code

No

### Current Behaviour?

```shell
Most of the TF operators can produce nan if input contains nan. However, pow cannot do that given certain inputs when compiling with XLA, making it hard to find problems in code.
```

### Standalone code to reproduce the issue

Code below in colab [here](https://colab.research.google.com/drive/1UIPnyZqR_xAfgRzT7zizVrGOww7HUyZE?authuser=1)

```shell

import tensorflow as tf
print(tf.__version__)
from keras import layers


class Network(tf.Module):
    def __init__(self):
        super().__init__()

    @tf.function(jit_compile=True)
    def __call__(self, x):
        y0 = tf.raw_ops.Softmax(logits=x)
        y1 = tf.sqrt(x)
        y2 = tf.pow(y0, y1)
        return y2


net = Network()
x = tf.constant(
    [-0.3523314], dtype=tf.float32,
)

tf.config.run_functions_eagerly(True)
res = net(x)
print(res)
# tf.Tensor([1.], shape=(1,), dtype=float32)
tf.config.run_functions_eagerly(False)

res = net(x)
print(res)
# tf.Tensor([nan], shape=(1,), dtype=float32)
```

### Relevant log output

```shell
2.8.2
tf.Tensor([1.], shape=(1,), dtype=float32)
tf.Tensor([nan], shape=(1,), dtype=float32)
```

_No response_</details>

**Comment by tiruk007** [comment]
@gadagashwini
I was able to reproduce the issue on Colab using TF v2.10. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/287769c0559644f835eb31364d79856d/57757.ipynb) for reference.
Thank you!

**Comment by cantonios** [comment]
`std::pow(1, NaN) = 1` in c++ [[docs](https://en.cppreference.com/w/cpp/numeric/math/pow)].  Looks like XLA is violating this, returning `NaN`.

**Comment by hujiajie** [comment]
Bump

The issue remains reproducible in v2.12.0. Tensorflowers, do you still think `tf.Tensor([1.], shape=(1,), dtype=float32)` is the expected result and XLA should not propagate NaN here?

**Comment by tilakrayal** [comment]
@Ishaan233,
We found out where the difference between XLA:GPU and eager GPU is coming from. In **XLA:GPU**, we set a flag so that **div.full** ptx instructions are emitted (which perform faster, but are not as accurate as the default div). 

If you want to overwrite this behavior, you pass --xla_backend_extra_options=-nvptx-prec-divf32=2 via XLA_FLAGS 
environment variable.

Thank you!
