### ISSUE TITLE
Wrong shape broadcasting during tensor equal check

### ISSUE THREAD

**Issue by creakseek** [tensorflow/tensorflow#57751]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tfnightly

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

when comparing two shape-incompatible tensors (with shape `(3,)` and `(5,)`) using `==` on cpu, tf fails to check shape and silently produce an output. if I switch to CUDA then it has the correct behavior: throws error because the shapes cannot broadcast.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
print(tf.__version__)
with tf.device("cpu"):
  tensor = tf.constant([1, 2, 3, 4, 5])
  print(tf.experimental.numpy.isreal(tensor) == np.array([True, False, False])) # Pass
with tf.device("gpu"):
  tensor = tf.constant([1, 2, 3, 4, 5])
  print(tf.experimental.numpy.isreal(tensor).shape)
  print(np.array([True, False, False]).shape)
  print(tf.experimental.numpy.isreal(tensor) == np.array([True, False, False])) # Fail
```

### Relevant log output

```shell
2.11.0-dev20220919
tf.Tensor(False, shape=(), dtype=bool)
(5,)
(3,)
InvalidArgumentError: {{function_node __wrapped__Equal_device_/job:localhost/replica:0/task:0/device:GPU:0}} required broadcastable shapes [Op:Equal]
```
</details>

**Comment by creakseek** [comment]
Similar issue reproduced in `tf.experimental.numpy.isclose`:
```
import tensorflow as tf
import numpy as np

with tf.device('cpu'):
  input_data = tf.constant([[1, 2, 3], [4, 5, 6]])
  def tf_isclose(input_data):
      return tf.experimental.numpy.isclose(
          input_data, np.array([[3, 0], [2, 5]]))
  output = tf_isclose(input_data)
  print(output)

with tf.device('gpu'):
  input_data = tf.constant([[1, 2, 3], [4, 5, 6]])
  def tf_isclose(input_data):
      return tf.experimental.numpy.isclose(
          input_data, np.array([[3, 0], [2, 5]]))
  output = tf_isclose(input_data)
  print(output)
```
Outputs:
```
tf.Tensor(False, shape=(), dtype=bool)
InvalidArgumentError: {{function_node __wrapped__Equal_device_/job:localhost/replica:0/task:0/device:GPU:0}} required broadcastable shapes [Op:Equal]
```

**Comment by tiruk007** [comment]
@gadagashwini 
I was able to reproduce the issue on Colab using TF v2.10. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/421715c0e16084ca88a697c81783941c/57751gpu.ipynb) for reference.
Thank you!

**Comment by cantonios** [comment]
The CPU behavior is actually intentional to match numpy.  Using `==` between tensors returns False if there is a shape mismatch [doc](https://www.tensorflow.org/api_docs/python/tf/Tensor#__eq__).  If you use `tf.math.equal`, it will assert on incompatible dimensions.

Looks like the GPU behavior is the buggy one.
