### ISSUE TITLE
`UnimplementedError` when calling Conv2D in TF 2.10

### ISSUE THREAD

**Issue by creakseek** [tensorflow/tensorflow#57753]
### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10, tf-nightly

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

The example below is from the [Con2D documentation](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D?hl=en). It fails to execute the basic Conv2D in TensorFlow 2.10 and tf-nightly (on CUDA). This can be reproduced in Colab.

This issue does not happen in TensorFlow 2.9 and 2.8.

### Standalone code to reproduce the issue

```shell
# In Colab:
# !pip install tensorflow==2.10
input_shape = (4, 28, 28, 3)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(
2, 3, activation='relu', input_shape=input_shape[1:])(x)
print(y.shape)
```

### Relevant log output

```shell
UnimplementedError: Exception encountered when calling layer "conv2d_2" "                 f"(type Conv2D).

{{function_node __wrapped__Conv2D_device_/job:localhost/replica:0/task:0/device:GPU:0}} DNN library is not found. [Op:Conv2D]

Call arguments received by layer "conv2d_2" "                 f"(type Conv2D):
  • inputs=tf.Tensor(shape=(4, 28, 28, 3), dtype=float32)
```

**Comment by tilakrayal** [comment]
@creakseek,
When running on GPU (with cuDNN version 7.6.3 or later), `tf.nn.depthwise_conv2d` backprop to filter (and therefore also tf.keras.layers.DepthwiseConv2D) now operate deterministically (and tf.errors.UnimplementedError is no longer thrown) when op-determinism has been enabled via tf.config.experimental.enable_op_determinism.

Could you please try to run the below command before executing the code on tensorflow v2.10. I tried and was able to execute the code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/719a572e39dc8d87cf3e9a6139bec83a/untitled611.ipynb).

**!apt install --allow-change-held-packages libcudnn8=8.1.0.77-1+cuda11.2**
Thank you!

**Comment by creakseek** [comment]
Thank you @tilakrayal ! That solves the problem.
