### ISSUE TITLE
Link to tutorial pages broken

### ISSUE THREAD

**Issue by bc-lee** [tensorflow/tensorflow#5775]
Hi,

It seems every links to tutorial pages like http://tensorflow.org/tutorials/word2vec/index.md or http://tensorflow.org/tutorials/seq2seq/index.md are broken.

Source: https://github.com/tensorflow/tensorflow/blob/754048a0453a04a761e112ae5d99c149eb9910dd/tensorflow/models/rnn/README.md#L5

https://github.com/tensorflow/tensorflow/blob/754048a0453a04a761e112ae5d99c149eb9910dd/tensorflow/models/image/cifar10/README.md#L9

**Comment by prb12** [comment]
None of those links seem broken to me.  Could you please clarify the problem you are seeing?

**Comment by bc-lee** [comment]
Sorry, it was the problem of local ISP.
