### ISSUE TITLE
tf.image.crop_and_resize crash (abort) when given num_boxes=0

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#57754]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.11.0-dev20220916

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.4 LTS (x86_64)

### Python version

3.7.6

### CUDA/cuDNN version

N/A

### Current Behaviour?

```shell
tf.image.crop_and_resize crash (abort) when given num_boxes=0
```

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf
tf.image.crop_and_resize(crop_size=[1,1], box_indices=np.ones((0,1)), boxes=np.ones((0,4)), image=np.ones((2,2,2,2)))
```

### Relevant log output

```shell
2022-09-19 20:55:05.906144: F tensorflow/core/framework/tensor_shape.cc:45] Check failed: NDIMS == dims() (1 vs. 2)Asking for tensor of 1 dimensions from a tensor of 2 dimensions
Aborted (core dumped)
```
</details>

**Comment by tiruk007** [comment]
@DNXie 
I tried to reproduce the issue on Colab using TF v2.10 but Colab crashes. Could you please find the gist [here](https://colab.research.google.com/gist/tiruk007/db2b2a94917c3e04ec473c83aec3bfb2/57754.ipynb) and confirm the issue?
Thank you!

**Comment by yongtang** [comment]
Created a PR #57783 for the fix.

**Comment by tiruk007** [comment]
@DNXie 
This issue is closed when the [PR](https://github.com/tensorflow/tensorflow/pull/57783) is merged.

Thank you!
