### ISSUE TITLE
SparseFillEmptyRowsGrad crash

### ISSUE THREAD

**Issue by Co1lin** [tensorflow/tensorflow#57765]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.11.0.dev20220914

### Custom Code

No

### Current Behaviour?

```shell
When giving empty list into SparseFillEmptyRowsGrad, it crashes with abort. As a public API, it should check it earlier and throw an python exception.
```

### Standalone code to reproduce the issue

Reproduced on CoLab with CUDA backend: https://colab.research.google.com/drive/1nUyX5iKxKRWR2m3NHOZdoeXaUh8s3P6Z?usp=sharing

```python
import tensorflow as tf
print(tf.__version__)

tf.raw_ops.SparseFillEmptyRowsGrad(reverse_index_map=[], grad_values=[])
```

### Relevant log output

```shell
import tensorflow as tf
print(tf.__version__)

tf.raw_ops.SparseFillEmptyRowsGrad(reverse_index_map=[], grad_values=[])

2.8.2
2022-09-20 14:44:40.812917: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2022-09-20 14:44:40.847990: F ./tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (0 vs. 0)
/bin/bash: line 1:   124 Aborted                 (core dumped) python bug.py 2>&1
```
</details>

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.9, v2.10 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3b97ba97e3daacb0fee64eac699b85c1/57765.ipynb).

**Comment by tilakrayal** [comment]
@Co1lin,
I tried to execute the code on the latest tf-nightly(**2.13.0-dev20230215**) and it was executed without any issue/crash. Could you please check the gist of it [here](https://colab.research.google.com/gist/tilakrayal/8960cb65cd36eb4929f287b93697d062/untitled947.ipynb) and let us know if it serves the purpose.

![image](https://user-images.githubusercontent.com/81610181/219082454-0dc7c437-c786-4046-8af4-8cfd26399b40.png)

**Comment by Co1lin** [comment]
@tilakrayal Thanks for your reply! It seems that the newer TF fixed this issue.
