### ISSUE TITLE
GPU detection src location

### ISSUE THREAD

**Issue by shrebhan** [tensorflow/tensorflow#57768]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

source

### Tensorflow Version

2

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### CUDA/cuDNN version

11.7

### GPU model and memory

Tesla V100

### Current Behaviour?

```shell
Hello, 

I'm a student researcher and I am only posting this as I got no response on the Tensorflow Google group. (Please direct me to next place to the answer).

I'm trying to develop a feature where if tensorflow does not detect a local GPU, I direct the binary to my custom application (a GPU virtualization framework) for it to talk to a remote GPU execute the calls.

I want to know, in the large codebase of tensorflow where should I start looking for this? I need source file where it decides "no GPU so use CPU" or something similar.
```

### Standalone code to reproduce the issue

```shell
NA
```

### Relevant log output

```shell
NA
```
</details>

**Comment by shrebhan** [comment]
hello @tiruk007 ! can you help me out finding the source code for where it checks if GPU or required libraries are resent on the system? Or point me someone who can ? or if there is documentation for it anywhere, that would be great, thank you

**Comment by mohantym** [comment]
Hi @shrebhan !

Sorry for the late response. 
While building from source , we normally run `python configure.py`to provide cuda location and other dependencies for custom build.  Link to configure.py is [here.](https://github.com/tensorflow/tensorflow/blob/master/configure.py) .

GPU virtualization might be possible through docker.

Command to check GPU capability is here.
```
physical_devices = tf.config.list_physical_devices('GPU')
print("Num GPUs:", len(physical_devices))
```

Thank you!
