### ISSUE TITLE
Unknown events logged while profiling TensorFlow code using Timeline API

### ISSUE THREAD

**Issue by agupta74** [tensorflow/tensorflow#5776]
I am seeing Unknown events being logged in the Trace logs using APIs from Timeline.py module. Is this a known issue and any ideas on how this could be fixed? I could not find any references to this issue on GITHUB or StackOverFlow.

Here is couple of examples of "Unknown" events:

       {
            "name": "MEMCPYHtoD",
            "ph": "X",
            "ts": 19926542594074346,
            "cat": "Op",
            "args": {
                "name": "unknown",
                "op": "MEMCPYHtoD"
            },
            "pid": 715,
            "tid": 0,
            "dur": 12535
        },

        {
            "tid": 0,
            "ph": "X",
            "name": "unknown",
            "pid": 63,
            "cat": "Op",
            "args": {
                "op": "unknown",
                "name": "unknown"
            },
            "ts": 19926135764459654,
            "dur": 1147
        },

Operating System: CentOS
Installed version of CUDA and cuDNN: 
Cuda 7.5 , cuDNN 5.1.3
TensorFlow version 0.10 and 0.11 rc0

**Comment by rashmimargani** [comment]
Hi agupta74,

can you please specify which PAI did you use in timeline.py and at when you will hit the issue

**Comment by prb12** [comment]
This is a known issue and is due to the current tracing format not being expressive enough to handle graphs which get rewritten during optimization.  

Please see the comments in #3717
