### ISSUE TITLE
flatbuffer -> ModelT -> flatbuffer:  zero length Vectors -> null pointer.

### ISSUE THREAD

**Issue by bensternlieb** [tensorflow/tensorflow#57777]
Folks,

I'm seeing zero length Vectors being converted to null pointers when converting
a tflite model to a flatbuffer tflite ModelT object and back again.

Netron shows the correct graph for the final model, and the tflite runtime seems to execute correctly,
but tools like `tensorflow/lite/python/analyzer_wrapper/model_analyzer.cc` fail when they encounter a null pointer rather
than an empty vector. For instance, this happens when the inputs and outputs of the CALL_ONCE operator are inspected.
The ModelT object seems to have the correct zero length vector data immediately prior to serialization.

My question: Is there a more "correct" way to export a  model in TFLite with empty vectors?  I'm using the pretty simple code shown below.  I'm also using schema_v3b.fbs (2.9.2 branch) and flatbuffers 1.12

git_repository(
    name = "com_github_google_flatbuffers",
    commit = "6df40a2471737b27271bdd9b900ab5f3aec746c7",
    remote = "https://github.com/google/flatbuffers",
    shallow_since = "1584052419 -0700",
)

Backstory - we're splitting TFLite models so that NN components can run on a delegate after which the remainder run on cpu.

### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 22.04
- TensorFlow installation (pip package or built from source):   v2.9.2 
- TensorFlow library (version, if pip package or github SHA, if built from source):   18960c4

### 2. Code
```
#include "flatbuffers/flatbuffers.h"

namespace chain_saw {

tflite::ModelT read_model(const std::string& model_path) {
  std::ifstream infile;
  infile.open(model_path.c_str(), std::ios::binary | std::ios::in);
  infile.seekg(0, std::ios::end);
  auto length = infile.tellg();
  infile.seekg(0, std::ios::beg);
  char *data = new char[length];
  infile.read(data, length);
  infile.close();

  const tflite::Model *m = tflite::GetModel(data);
  tflite::ModelT model_obj;
  m->UnPackTo(&model_obj);
  // not using original model representation anymore, so tidying up.
  delete[] data;

  return model_obj;
}

void write_model(const tflite::ModelT &model, const std::string& model_path) {
  // Serialize into new flatbuffer.
  flatbuffers::FlatBufferBuilder fbb;
  fbb.Finish(tflite::Model::Pack(fbb, &model), "TFL3");
  const uint8_t *buf = fbb.GetBufferPointer();
  int size = fbb.GetSize();  // Returns the size of the buffer that
  std::ofstream outfile;
  outfile.open(model_path.c_str(), std::ios::binary | std::ios::out);
  if (!outfile) {
    LOG(FATAL);
  }
  outfile.write(reinterpret_cast<const char *>(buf), size);
  LOG(INFO) << "Wrote model to " << model_path;
}

#include "schema/schema_v3b_generated.h"

namespace {
const char kSrcModel[] = "models/src.tflite";
const char kDstModel[] = "/tmp/dst.tflite";
}  // namespace

// nominally write back what we read.
int main(int argc, char* argv[]) {

  tflite::ModelT model_obj = chain_saw::read_model(kSrcModel);
  chain_saw::write_model(model_obj, kDstModel);
}
```

**Comment by mohantym** [comment]
Hi @sachinprasadhs !
Could you look at this issue.
Thank you!

**Comment by sachinprasadhs** [comment]
Could you please try again with the latest Tensorflow version 2.10.0 and flatbuffer version and let us know the outcome. Thanks!
