### ISSUE TITLE
How can i use 4 GPUS with tensorflow2.10

### ISSUE THREAD

**Issue by virgo777** [tensorflow/tensorflow#57774]
How can i use 4 GPUS with tensorflow2.10

sorry for my poor english

who can show me an example.

**Comment by cpuimage** [comment]
@virgo777   [distributed_train.py](https://github.com/tensorflow/examples/blob/master/tensorflow_examples/models/densenet/distributed_train.py)

**Comment by sushreebarsa** [comment]
@virgo777 Could you refer this [doc](https://www.tensorflow.org/guide/distributed_training) to know more on the distribution strategy ? Please let us know if it helps?
Thank you!
