### ISSUE TITLE
TESTs Failed: kernels:unsorted_segment_{prod, max, min, sum}_test

### ISSUE THREAD

**Issue by psunn** [tensorflow/tensorflow#57775]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

latest master branch

### Custom Code

No

### OS Platform and Distribution

Ubuntu 9.4.0-1ubuntu1~18.04

</details>

### Current Behaviour?

```shell
TFLite kernel TESTs failing:

//tensorflow/lite/kernels:unsorted_segment_prod_test

//tensorflow/lite/kernels:unsorted_segment_max_test

//tensorflow/lite/kernels:unsorted_segment_min_test

//tensorflow/lite/kernels:unsorted_segment_sum_test
```

### Standalone code to reproduce the issue

```shell
bazel test //tensorflow/lite/kernels:unsorted_segment_min_test --test_output=all
```

### Relevant log output

```shell
(unsorted_segment_min_test as example, similar log for other TESTs)

...
ERROR: /media/WORK/mirror-tensorflow/tensorflow/lite/kernels/BUILD:2850:8: Compiling tensorflow/lite/kernels/unsorted_segment_min_test.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 197 arguments skipped)
tensorflow/lite/kernels/unsorted_segment_min_test.cc:136:67: error: expected constructor, destructor, or type conversion before ';' token
  136 | GTEST_ALLOW_UNINSTANTIATED_PARAMETERIZED_TEST(UnsortedSegmentTest);
      |                                                                   ^
cc1plus: warning: unrecognized command line option '-Wno-array-parameter'
cc1plus: warning: unrecognized command line option '-Wno-unknown-warning'
Target //tensorflow/lite/kernels:unsorted_segment_min_test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 7.023s, Critical Path: 6.42s
INFO: 12 processes: 12 internal.
FAILED: Build did NOT complete successfully
```

**Comment by psunn** [comment]
@LukeBoyer Hi Luke, can you please have a look? Seems relative to your contribution: https://github.com/tensorflow/tensorflow/commit/884acc353437e2fca9f0e2f7aabc8d9adc3ebd17

**Comment by LukeBoyer** [comment]
Sure thing.

**Comment by mohantym** [comment]
Hi @psunn !
I tried to replicate Colab with TF 2.10 and  Bazel 5.1.1 . Builds  passed except unsorted_segment_min_test  (with error "target 'unsorted_segment_min_test' not declared in package") .
Attached[ gist](https://colab.sandbox.google.com/gist/mohantym/34b4175800114976a43262da3a35fc09/tensorflow-ranking.ipynb#scrollTo=ZA2YQB3b5ufh) of 2.10 for reference.

Could you let us know your TF and Bazel version too.

Thank you!

**Comment by psunn** [comment]
Hi @mohantym , thanks for respond and the colab!

We're working on TF master branch.

https://github.com/tensorflow/tensorflow/commit/884acc353437e2fca9f0e2f7aabc8d9adc3ebd17 was not included in 2.10 release ([git log](https://github.com/tensorflow/tensorflow/commits/v2.10.0?after=359c3cdfc5fabac82b3c70b3b6de2b0a8c16874f+85&branch=v2.10.0&qualified_name=refs%2Ftags%2Fv2.10.0))
unsorted_segment_{prod, max,  sum}_test  would pass and target unsorted_segment_min_test is not defined.

If test with current TF masater or https://github.com/tensorflow/tensorflow/commit/884acc353437e2fca9f0e2f7aabc8d9adc3ebd17 onwards, reported TESTs failures would appear.

**Comment by mohantym** [comment]
@psunn !
Thanks for the update. 

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by psunn** [comment]
@LukeBoyer Thank you for https://github.com/tensorflow/tensorflow/commit/8dca3c3ff92b1e1f8d9c11fe277bcd26c2c46cd0 !
It resolved the issue.
