### ISSUE TITLE
Wrong NaN gradient for `tf.acos`

### ISSUE THREAD

**Issue by VictoriaGriffith** [tensorflow/tensorflow#57786]
### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Current Behaviour?

`tf.math.acos` is an element-wise operation, thus the gradient should be`0` when the input and output elements have different indices. However, in the example below, the gradient of `tf.acos(x)[0]` w.r.t. `x[2]` is computed as `nan`, which is wrong. It should be `0`.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
x = tf.constant([-0.5, 0.5, 2.0])
with tf.GradientTape(persistent=True) as tape:
    tape.watch(x)
    y = tf.acos(x)[0:1]
print(tape.gradient(y, x))
```

### Relevant log output

```shell
tf.Tensor([-1.1547005 -0.               nan], shape=(3,), dtype=float32)
```

**Comment by tilakrayal** [comment]
@gadagashwini,
I was able to reproduce the issue on tensorflow v2.8, v2.10 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/39bb48e8cdb38e2abaf41bdfee894c66/57786.ipynb).

**Comment by cantonios** [comment]
We're not just dealing with `acos`, we're also dealing with the gradient of the slice operator and the multiplication of gradients via chain rule.

We have
```
y = slice(acos(x))

dy/dx = dslice(z)/dz  * dacos(x)/dx, evaluated at z = acos(x)
```
in your case, you end up with
```
dy/dx = [ 1 0 0 ] * [  -2/sqrt(3)           0      0;
                               0    -2/sqrt(3)     0;
                               0            0    NaN]
      = [-2/sqrt(3),  0,  NaN]
```

If `dacos(x)/dx` was defined and finite, then the gradient would be 0.  But since we're dealing with IEEE floating point, `0 * NaN` and `0 * inf` are both `NaN`.
