### ISSUE TITLE
tflite gesture_classification int8 model

### ISSUE THREAD

**Issue by nyadla-sys** [tensorflow/tensorflow#57780]
@PaulTR 

For tflite examples, we are seeking for the dataset used to train the gesture classification model.
https://github.com/tensorflow/examples/tree/master/lite/examples/gesture_classification/android

if the dataset is unavailable for some reason, Is the int8 tflite model for gesture classification available for sharing?

Thanks,
Niranjan

**Comment by nyadla-sys** [comment]
@advaitjain Could you please help to get int8 gesture_classification model?
Recently Google released float32 gesture classification tflitemodel.
Please see the below link for more details about float32 model
https://github.com/tensorflow/examples/tree/master/lite/examples/gesture_classification/android

**Comment by PaulTR** [comment]
So I'm not actually sure what other datasets are used for this process. The model used for Android was created using the index.html tool page from the web example (https://github.com/tensorflow/examples/tree/master/lite/examples/gesture_classification/web) and then trained with the images/gestures used in the android readme image. Let me ping Jason Mayes, our web lead for the samples, to see if he has any thoughts.

**Comment by nyadla-sys** [comment]
@PaulTR Thanks for your quick response,Do you have int8 model for the same ?

**Comment by PaulTR** [comment]
Not that I am aware of.

**Comment by mohantym** [comment]
HI @nyadla-sys !
We can create the similar images as this [document](https://github.com/tensorflow/examples/tree/master/lite/examples/gesture_classification/web/assets) using [teachable machine](https://teachablemachine.withgoogle.com/train/image) . Then you can export it as TFlite model else you can take the dataset to TFlite-model-maker to get integer quantization model (default config in TFite model maker).

Thank you!
