### ISSUE TITLE
TensorFlow Lite: Not detecting `DataType` for UINT8 `TensorImage`

### ISSUE THREAD

**Issue by covercash2** [tensorflow/tensorflow#57781]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

No

### Mobile device

Android 12, target SDK 30

### Current Behaviour?

```shell
When trying to run a UINT8 quantized model using the TensorFlow Lite `Interpreter`, the runtime is not able to determine the correct data type for inference. The code is using the `TensorImage` type from the support library with an explicitly set `DataType` of `DataType.UINT8`. 
I've confirmed the shape and type of the input in Netron: "type: uint8[1,224,224,3]"
Inspecting the code, it seems to fail to resolve the type in `TensorImpl.dataTypeOf()`, throwing the above Exception.
```

### Standalone code to reproduce the issue

```shell
val imageProcessor = ImageProcessor.Builder()
	.add(ResizeOp(inputSize.width, inputSize.height, ResizeOp.ResizeMethod.NEAREST_NEIGHBOR))
	.build()

val inputBuffer: TensorImage = run {
	val imageTensorIndex = 0
	val imageDataType = interpreter.getInputTensor(imageTensorIndex).dataType()
	TensorImage(imageDataType)
}

inputBuffer.load(bitmap)
val buffer = imageProcessor.process(inputBuffer)

// passing TensorImage to runtime
interpreter.run(buffer, outputBuffer)

// passing a raw buffer and resizing according to the docs
interpreter.resizeInput(0, intArrayOf(1, inputSize.width, inputSize.height, 3))
interpreter.run(buffer.buffer, outputBuffer)
```

### Relevant log output

```shell
java.lang.IllegalArgumentException: DataType error: cannot resolve DataType of org.tensorflow.lite.support.image.TensorImage
	at org.tensorflow.lite.TensorImpl.dataTypeOf(TensorImpl.java:319)
	at org.tensorflow.lite.TensorImpl.throwIfTypeIsIncompatible(TensorImpl.java:390)
	at org.tensorflow.lite.TensorImpl.getInputShapeIfDifferent(TensorImpl.java:252)
	at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:237)
	at org.tensorflow.lite.InterpreterImpl.runForMultipleInputsOutputs(InterpreterImpl.java:133)
	at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:80)
	at org.tensorflow.lite.InterpreterImpl.run(InterpreterImpl.java:126)
	at org.tensorflow.lite.Interpreter.run(Interpreter.java:80)
```
</details>

**Comment by mohantym** [comment]
@covercash2 !
Would it be possible to share a toy model to replicate this issue.
Thank you!

**Comment by covercash2** [comment]
the debugger confirms that it is a UINT8 DataType. 

<img width="653" alt="Screen Shot 2022-09-22 at 10 45 00" src="https://user-images.githubusercontent.com/1354828/191792646-37bcb6e1-36ce-46a8-b064-3dc4f23e82e6.png">

inspecting the code it looks like it's failing where the type is being checked by its Java class:

<img width="1164" alt="Screen Shot 2022-09-22 at 10 46 37" src="https://user-images.githubusercontent.com/1354828/191793063-76b1fb6f-5f32-406b-a805-734090cc581d.png">

unfortunately, i'll have to check whether we can share a model. we are using a modified version of EfficientNetB0. here's some metadata from the model in Netron:

<img width="480" alt="Screen Shot 2022-09-22 at 10 48 34" src="https://user-images.githubusercontent.com/1354828/191793469-aec96a57-b373-4ef9-baa7-ee31aa83549a.png">

**Comment by covercash2** [comment]
if i change the code to 

```
interpreter.runForMultipleInputsOutputs(arrayOf(buffer.buffer), mapOf(0 to outputBuffer))
```

i get a new error:

```
Cannot convert between a TensorFlowLite tensor with type UINT8 and a Java object of type [[I (which is compatible with the TensorFlowLite type INT32).
```

which means, according to the `TensorImpl.dataTypeOf`, the buffer is being determined as an `IntBuffer` instead of a `ByteBuffer` for some reason.

**Comment by mohantym** [comment]
Ok @covercash2 !
Thanks for the update.

@sachinprasadhs !
Could you look at this issue.
Thank you!

**Comment by covercash2** [comment]
would appreciate any guidance on how to solve if there is a workaround 🙏

**Comment by pjpratik** [comment]
Hi @covercash2 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
