### ISSUE TITLE
[TensorFlow Mechanics 101]: Add conv layers to this tutorial

### ISSUE THREAD

**Issue by zuoxingdong** [tensorflow/tensorflow#5779]
It seems the tutorial in **TensorFlow Mechanics 101** has more beautiful structure in coding, and as it currently only contains fully connected layers. Is it a good addition to include conv layers ? If so, please leave a short comment and I'll submit a pull request soon.

**Comment by prb12** [comment]
I think the point of that specific tutorial is to show general TensorFlow features and usage, rather than to teach people about different kinds of model?

@xmbrst @dr4b  Would you like to comment on this?

**Comment by dr4b** [comment]
Yeah, I think that is correct.  We do have a convolutional neural network tutorial as well in /tensorflow/g3doc/tutorials/deep_cnn/index.md -- does that help for what you're looking for?

**Comment by prb12** [comment]
Closing since I don't think that we want to complicate a beginner tutorial and there are plenty of other tutorials available on convnets.
