### ISSUE TITLE
Process crash caused by check failed in `UnsortedSegmentProd`

### ISSUE THREAD

**Issue by Co1lin** [tensorflow/tensorflow#57798]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.11.0.dev20220914

### Custom Code

No

### Current Behaviour?

```shell
Passing a large number to UnsortedSegmentProd will trigger an i32 overflow, which leads to check failure later and the process will crash.
As a public API, it's better to check the number and throw an exception.
Note that the same issue happens in UnsortedSegmentMax, UnsortedSegmentMin, UnsortedSegmentSum, UnsortedSegmentProd .
```

### Standalone code to reproduce the issue

https://colab.research.google.com/drive/1BIm3xyoJaGMD_YkGyKvDR8Xp9kZKk3OX?usp=sharing

```python
import tensorflow as tf
print(tf.__version__)

class MyModule(tf.Module):
    def __init__(self):
        super().__init__()

    @tf.function
    def __call__(self, x, y, z):
        return tf.raw_ops.UnsortedSegmentProd(
            data=x, segment_ids=y, num_segments=z,
        )


inp = {
    "x": tf.constant([3]),
    "y": tf.constant([1], dtype=tf.int64),
    "z": tf.constant(0x7fffffff + 1, dtype=tf.int64),
}
m = MyModule()

out = m(**inp)  # Error!
print(out)
print(out.shape)
```

### Relevant log output

```shell
2022-09-22 08:41:10.937141: F ./tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (0 vs. -2147483648)
/bin/bash: line 1:   138 Aborted                 (core dumped) python unsorted_seg_bug.py 2>&1
```
</details>

**Comment by tilakrayal** [comment]
@Co1lin,
On GPU, this does not throw an error for out-of-bound indices. On Gpu, out-of-bound indices result in safe but unspecified behavior, which may include ignoring out-of-bound indices or outputting a tensor with a 0 stored in the first dimension of its shape if num_segments is 0. 

Could you please take a look at this official [document](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/unsorted-segment-prod) for more information. Thank you!

**Comment by Co1lin** [comment]
Hi! It seems that the doc says out-of-bound indices for argument `segment_ids` result in safe but unspecified behavior, but the bug I provide above is about giving a very large number to the argument `num_segments`, which results in process crash as represented in the CoLab link. So my suggestion is taking care of `num_segments` to avoid crash for some inputs.

**Comment by tilakrayal** [comment]
@Co1lin,
I tried to execute the code with the alternative approach by changing the **"z": tf.constant(0x7ffffff + 1, dtype=tf.int64)** value. The older **"z"** value was out of the scope which was causing the error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/8a70b8417b72df79a82e678ae8e850f0/untitled627.ipynb). Thank you!

**Comment by Co1lin** [comment]
Yes, the z value I provided is out of i32 scope. But as what I said, "As a public API, it's better to check the number and throw an exception", but not let the process directly crash, which can form a DoS attack. Thanks!

**Comment by tilakrayal** [comment]
@Co1lin,
After the Colab was getting crashed, Could you please refer to the run-time logs available on the same page. 
![image](https://user-images.githubusercontent.com/81610181/193003955-a4d18154-1be9-4618-b557-d6f26f7534c1.png)

It is providing the info for the crash. Thank you!

**Comment by Co1lin** [comment]
@tilakrayal Thanks for providing the information about CoLab logs. Besides, I want to say that there should be a check for this API to avoid process crash triggered by C level checking. It would make TensorFlow more robust if you could fix this crash issue. Thank you!

**Comment by sachinprasadhs** [comment]
For UnsortedSegmentProd, we have below logic implemented and also reason for different implementation on CPU and GPU is:
`num_segments` should equal the number of distinct segment IDs.
On CPU, values in `segment_ids` are always validated to be less than `num_segments`, and an error is thrown 
for out-of-bound indices. 
On GPU, this does not throw an error for out-of-bound indices. On Gpu, out-of-bound indices result in safe but unspecified behavior, which may include ignoring out-of-bound indices or outputting a tensor with a 0 stored in the first
 dimension of its shape if `num_segments` is 0.

**Comment by Co1lin** [comment]
Hi @sachinprasadhs! I understand on GPU, this out-of-bound index results in undefined behavior, but I don't think it's a safe behavior because the program **is aborted**, the process is **crashed**, and the CoLab service is **stopped** due to this error. As a public API, it should raise exception at Python level, or just return something, but not let the process crash.

**Comment by Co1lin** [comment]
Sorry for the late reply. I think process crash is not safe but a dangerous behavior because it can affect the stability of many online services, so please reopen this issue. Thanks! @tilakrayal @sachinprasadhs

**Comment by mihaimaruseac** [comment]
Your example is similar to `malloc(a_huge_number)` written by a programmer in their own code. This has exactly one effect: self-caused denial of service.

This won't occur by default in other models, it's not something TF team should be worried about. Please note that Google's VRP rules ignore denial of service as there are tools and alternatives to protect against them. Also, in this case, this is a user-caused DOS, not something that results from a very small input getting unpacked into something large (as it would be the case in a tar bomb for example, though even there we no longer care about these if they don't manifest in real world models)

**Comment by Co1lin** [comment]
Thanks for the clarification! I noticed the change in Google's VRP rules but thought the GitHub issue was different. Now I understand.
