### ISSUE TITLE
Saving to an existing directory does not overwrite assets

### ISSUE THREAD

**Issue by nvkevihu** [tensorflow/tensorflow#57795]
### Issue Type

Bug

### Tensorflow Version

2.10

### Python version

3.8.10

### Current Behaviour?

Using `tf.saved_model.save` to save a model to a directory where an older version of the model was previously saved only partially overwrites the older SavedModel. Specifically, assets are not overwritten.

I would expect that while saving the model we either completely overwrite the old model, or produce a warning. As is, saving and reloading a model can produce an unexpected state.

It looks like this behavior was previously changed in [d42a6a948](https://github.com/tensorflow/tensorflow/commit/d42a6a948de44954fac3884466e969776dc4480e), but later reverted.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.python.training.tracking import autotrackable

_FILENAME = "file.txt"
_SAVEDIR = "model"

# Write contents to asset file
with open(_FILENAME, 'w') as f:
    f.write("foo")

# First Save
trackable = autotrackable.AutoTrackable()
asset = tf.saved_model.Asset(_FILENAME)
trackable.asset = asset
tf.saved_model.save(trackable, _SAVEDIR)

# Change asset contents
with open(_FILENAME, 'w') as f:
    f.write("bar")

# Second Save
tf.saved_model.save(trackable, _SAVEDIR)

# Load and compare with in-memory trackable
loaded_trackable = tf.saved_model.load(_SAVEDIR)
print("Expected Result: {}".format(tf.io.read_file(trackable.asset)))      # bar
print("Loaded Result: {}".format(tf.io.read_file(loaded_trackable.asset))) # foo
```

### Relevant log output

```
Expected Result: b'bar'
Loaded Result: b'foo'
```

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.8, v2.10 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/16152ab65bf319d367fa612673f83aa1/57795.ipynb).

**Comment by DEKHTIARJonathan** [comment]
@yarri-oss @reedwm @bixia1  FYI

**Comment by DEKHTIARJonathan** [comment]
@liangyaning33 the original committer of the bugfix
