### ISSUE TITLE
How to parse MetaGraphDef with C API

### ISSUE THREAD

**Issue by CarlPoirier** [tensorflow/tensorflow#57802]
Hi,

I have a model with multiple outputs. Using the C API, I need to select outputs according to their names, for example 'detection_boxes' in the following image:
![image](https://user-images.githubusercontent.com/5577772/191764668-ff8a2486-7065-4521-9a3d-b878471c32a5.png)

I found these names are present in the meta_graph_def I get from the [TF_LoadSessionFromSavedModel()](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h#L1240) function. Is there a supported way to parse this meta_graph_def to get the names? If not, is it planned? [This](https://github.com/serizba/cppflow/pull/203) is how I do it for now.

Regards,

Carl

**Comment by gusye1234** [comment]
Any answer? Also stuck here.
