### ISSUE TITLE
ImportError: cannot import name pywrap_tensorflow, not resolved by previous fixes

### ISSUE THREAD

**Issue by amendezleal37** [tensorflow/tensorflow#5781]
I'm getting an error similar to that in #3217, but it's not resolved by switching directories or adding the lines to my bash profile. I'm using a jupyter notebook. Any suggestions?
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-577-fd66eeda4fb7> in <module>()
      2 import pandas as pd
      3 import scipy as sp
----> 4 import tensorflow as tf
      5 import sklearn.preprocessing as Preprocessing
      6 from sklearn.preprocessing import Imputer

/Users/curr_user/anaconda/lib/python2.7/site-packages/tensorflow/__init__.py in <module>()
     21 from __future__ import print_function
     22 
---> 23 from tensorflow.python import *

/Users/curr_user/anaconda/lib/python2.7/site-packages/tensorflow/python/__init__.py in <module>()
     46 _default_dlopen_flags = sys.getdlopenflags()
     47 sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
---> 48 from tensorflow.python import pywrap_tensorflow
     49 sys.setdlopenflags(_default_dlopen_flags)
     50 

ImportError: cannot import name pywrap_tensorflow

**Comment by prb12** [comment]
This is a general support question best suited to StackOverflow.  Please could you re-ask your question there.
