### ISSUE TITLE
Front camera opening in reverse position

### ISSUE THREAD

**Issue by gundubandagar** [tensorflow/tensorflow#57823]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9

### Custom Code

Yes

### Mobile device

Android Q

### Current Behaviour?

```shell
A bug happened! opening front camera in reverse mode. under cameraSource.kt file
```

### Standalone code to reproduce the issue

```shell
A bug happened! opening front camera in reverse mode. under cameraSource.kt file
```

### Relevant log output

```shell
A bug happened! opening front camera in reverse mode. under cameraSource.kt file
```
</details>

**Comment by mohantym** [comment]
@gundubandagar !
Could you point towards the code snippet where you made changes.
Thank you!

**Comment by gundubandagar** [comment]
fun prepareCamera() {
    for (cameraId in cameraManager.cameraIdList) {

        val characteristics = cameraManager.getCameraCharacteristics(cameraId)

        // We don't use a front facing camera in this sample.
        val cameraDirection =
characteristics.get(CameraCharacteristics.LENS_FACING)
        if (cameraDirection != null &&
            cameraDirection == CameraCharacteristics.LENS_FACING_FRONT
        ) {
            continue
        }
        this.cameraId = cameraId
    }


}

**Comment by gundubandagar** [comment]
i want front camera open only, when i change it showing reverse direction

**Comment by sachinprasadhs** [comment]
This does not look like an issue from the TFLite, however you can try to follow these examples/implementation([1](https://github.com/FirebaseExtended/mlkit-material-android/blob/master/app/src/main/java/com/google/firebase/ml/md/kotlin/camera/CameraSource.kt#L257) & [2](https://stackoverflow.com/questions/39022845/android-camera2-api-switch-back-front-cameras)) and see if that helps. Thanks!
