### ISSUE TITLE
SSD mobilenet v2 trained using OD API can't run on Raspberry pi

### ISSUE THREAD

**Issue by UcefMountacer** [tensorflow/tensorflow#57824]
### 1. System information

- OS Platform and Distribution: Raspbian Bullseye
- TensorFlow installation : 
pip package, 2.8.0 for conversion
training tensorflow-gpu 1.15.0
tflite-runtime 2.10.0

### 2. Code

```
import tflite_runtime.interpreter as tflite
interpreter = tflite.Interpreter(model_path,num_threads=4)
interpreter.resize_tensor_input(0,[1,300,300,3])
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
```

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

- Model works using tensoflow 2.8.0 on my laptop using intel i5
- Model doesn't work on the raspberry pi using tflite-runtime

![image](https://user-images.githubusercontent.com/47783157/191978841-0234f50e-573e-4fb7-8305-bf759d4e3546.png)

### when running

```
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model('saved_model/')
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
```

output

```
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
2022-09-23 15:07:39.557389: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:357] Ignored output_format.
2022-09-23 15:07:39.557422: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:360] Ignored drop_control_dependency.
2022-09-23 15:07:39.558537: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: saved_model/saved_model/
2022-09-23 15:07:39.572864: I tensorflow/cc/saved_model/reader.cc:78] Reading meta graph with tags { serve }
2022-09-23 15:07:39.572909: I tensorflow/cc/saved_model/reader.cc:119] Reading SavedModel debug info (if present) from: saved_model/saved_model/
2022-09-23 15:07:39.627548: I tensorflow/cc/saved_model/loader.cc:301] SavedModel load for tags { serve }; Status: success: OK. Took 69018 microseconds.
2022-09-23 15:07:39.809761: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:237] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
loc(fused["TensorArrayV3:", "Preprocessor/map/TensorArray"]): error: 'tf.TensorArrayV3' op is neither a custom op nor a flex op
loc(fused["TensorArrayV3:", "Preprocessor/map/TensorArray_1"]): error: 'tf.TensorArrayV3' op is neither a custom op nor a flex op
.
.
.
.
	tf.TensorArrayWriteV3(tensor<2x!tf_type.resource<tensor<*xf32>>>, tensor<i32>, tensor<?xf32>, tensor<f32>) -> (tensor<f32>) : {_class = ["loc:@Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_1"], device = ""}
	tf.TensorArrayWriteV3(tensor<2x!tf_type.resource<tensor<*xf32>>>, tensor<i32>, tensor<?xf32>, tensor<f32>) -> (tensor<f32>) : {_class = ["loc:@Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/Pad_5"], device = ""}
	tf.TensorArrayWriteV3(tensor<2x!tf_type.resource<tensor<*xi32>>>, tensor<i32>, tensor<3xi32>, tensor<f32>) -> (tensor<f32>) : {_class = ["loc:@Preprocessor/map/while/ResizeImage/stack_1"], device = ""}
	tf.TensorArrayWriteV3(tensor<2x!tf_type.resource<tensor<*xi32>>>, tensor<i32>, tensor<i32>, tensor<f32>) -> (tensor<f32>) : {_class = ["loc:@Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/Select_11"], device = ""}
```

(ps : output was loo long)

#### when using converter.allow_custom_ops = True

the conversion works on tensorflow but not on tflite-runtime

#### the question is:

**why a model provided by google not work on tflite-runtime ?**

I have tested many ssd mobilenet v2 tflite files on the raspberry pi and they work, and they are really good. But when trying to train them on custom dataset and follow the guide provided by Google, they just don't work.
I can't use tensorflow on the raspberry pi !!!

#### appreciate any help !

Thanks

**Comment by mohantym** [comment]
Hi @UcefMountacer !
Select Ops feature is still not there in tflite-run time . You have to shadow clone ( upto last 3 stable branches) and use  2.9/2.10 branch to use select ops functionality.

Can you also  check the raspberry pi wheels from [Pintoo](https://github.com/PINTO0309/Tensorflow-bin)  and let us know the results too.

**Comment by UcefMountacer** [comment]
Hello @mohantym 

Thanks for your answer. The issue is indeed in tflite-runtime, because when I installed a tensorflow wheel on the rpi and it works. the loading time is an issue though.

> You have to shadow clone ( upto last 3 stable branches) and use 2.9/2.10 branch to use select ops functionality.

sorry, I didn't understand this part.

Also, I will check the wheel from pintoo, thanks a lot for your help.

**Comment by mohantym** [comment]
Ok @UcefMountacer !
I was suggesting to pull only the latest 2-3 commits(instead of cloning all branches) through the below command. It will save some space that way in your raspberry pi.

`git clone --depth -3  https://github.com/tensorflow/tensorflow
`
Please let us know after testing with flex delegate wheels from Pinto.


Thank you!

**Comment by UcefMountacer** [comment]
> I was suggesting to pull only the latest 2-3 commits(instead of cloning all branches) through the below command. It will save some space that way in your raspberry pi.

Okey, I get it, thanks. But I installed using a wheel file, because I had to find the right installation for my python version. But thanks for the point.

I'll test it and let you guys know on this thread if it worked or not.

Just some additionnal infos :

**Comment by mohantym** [comment]
@UcefMountacer !
Input size is 300x300 for SSD Mobilenet v2 , Could you point me towards the SSD mobilenet v2 documentation .
Thank you!

**Comment by UcefMountacer** [comment]
@mohantym 
it's the ssd_mobilenet_v2_coco_2018_03_29

http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_coco_2018_03_29.tar.gz

**Comment by mohantym** [comment]
@UcefMountacer !
If you have trained the model in TF 1.x version, You can use compat.v1 model in 2.x use the features from 1.x through below command. ( but results will much better if you can write the code  again in 2.x ).


```
import tf.compat.v1 as tf
tf.disable_v2_behavior()
```

Can we consider this as resolved then (Did the flex delegate wheels for your Pi?)

Thank you!

**Comment by UcefMountacer** [comment]
Great to know @mohantym . I'll test those. I haven't tried yet the wheel files from Pintoo, can you guys leave this issue open? I'll do it ASAP and update you !

Thanks.

**Comment by mohantym** [comment]
Sure @UcefMountacer !
Please share your results once you have tested . 
Thank you!

**Comment by UcefMountacer** [comment]
Hello @mohantym 

I have a question. I don't have the Pinto wheel test result yet, but I have a serious question.

How come the model downloaded from tf2 model zoo can be converted to int8, while using the same code on this model but trained on custom dataset fails.

I am really interested in knowing this. Thanks

**Comment by mohantym** [comment]
@UcefMountacer !
Could you share the error stack trace for [above issue](https://github.com/tensorflow/tensorflow/issues/57824#issuecomment-1260031568) with representative dataset.
Thank you!

**Comment by UcefMountacer** [comment]
@mohantym 
sorry I forgot to follow up, but that issue was solved by setting the representative dataset generator output to float32

Regarding tflite-runtime wheel, I found that using export_tflite_graph_tf2.py function generates a saved model that can be converted to tlite and used without issues with tflite-runtime (installed using pip).

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)

**Comment by AAArpan** [comment]
@UcefMountacer Can you give the steps on how you resolve the issue of flex delegate with tflite-runtime(rpi), as I am also having the same issue for my custom ssd mobilenet model, it will be a great help for me.
