### ISSUE TITLE
Inconsistencies between 2d and 3d ops

### ISSUE THREAD

**Issue by jiannanWang** [tensorflow/tensorflow#57835]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf2.10

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04.6

### Python version

3.7.6

### Current Behaviour?

```shell
Inspired by the document of tf.nn.conv1d which writes "Internally, this op reshapes the input tensors and invokes tf.nn.conv2d", I want to check if the 2d operators can be implemented using their 3d versions by reshaping the input tensors and some arguments. In the following colab link, I compared between Conv2D and Conv3D, MaxPool2D and MaxPool3D, AveragePooling2D and AveragePooling3D. 

I added an extra dimension to the input, strides, and kernel_size/pool_size. The original 2d operators should be equivalent to the version that implements a 2d operator using its 3d version. However, when feeding them with those specific arguments and input, I detect inconsistencies in the output when using the latest version of tensorflow. 

I also checked previous versions, and found in old versions such as tf2.4 and before, those codes will show no inconsistencies between the original 2d version and the version that implemented 2d ops using 3d ops. I believe this may be a bug because of this change between versions.
```

### Standalone code to reproduce the issue

```shell
Colab link: https://colab.research.google.com/drive/15vYN__3x0BT0c5co83k38w7CMCqIqWtC?usp=sharing
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@jiannanWang,
I was facing a different issue while executing the given code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/4c8577035eadd6fc1305bffb23f4f0f7/57835.ipynb).

**Comment by jiannanWang** [comment]
Hi @tilakrayal , thank you for your quick response!

I think I forgot to mention my environment was on CPU. I changed to install tensorflow-cpu instead of tensorflow and then I can see it reproduces my issue. Can you please take a look again?

My updated [gist](https://colab.research.google.com/drive/15vYN__3x0BT0c5co83k38w7CMCqIqWtC?usp=sharing).

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow [v2.8](https://colab.research.google.com/gist/tilakrayal/a2c0c0220d44fc638e66ef4b1cd4aca2/2-8.ipynb), [v2.10](https://colab.research.google.com/gist/tilakrayal/65aef304c4d1ed49d64d9721b9393217/implementing_2d_w_3d.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/b8bac899a45bb12ab1218462100a94e7/nightly.ipynb). Kindly find the gist of it here.

**Comment by sachinprasadhs** [comment]
From Tensorflow 2.3- 2.4 onwards the changes made in `Conv2D` to add outer batch dimension support to `tf.nn.convXd` and `keras.layers.ConvXd`.
One of the related PR is here https://github.com/tensorflow/tensorflow/commit/e06bd939a1e001dc519be7a74e6c0d5f78ccd3d8 which might be the reason for the changes you are observing, which I see as intended behavior.
