### ISSUE TITLE
Adan optimizer

### ISSUE THREAD

**Issue by KarthiAru** [tensorflow/tensorflow#57836]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### Current Behaviour?

```shell
Adan seems to be a superior optimizer compared to Adam and its variants. Can we introduce this in Tf/Keras optimizers?

Please find a few references below:

Adan paper: https://arxiv.org/abs/2208.06677

Pytorch implementation:
- https://github.com/sail-sg/Adan
- https://github.com/lucidrains/Adan-pytorch

Blog article:
- https://wandb.ai/capecape/adan_optimizer/reports/Adan-A-New-Optimizer-That-Challenges-Adam--VmlldzoyNTQ5NjQ5
```

### Standalone code to reproduce the issue

```shell
NA
```

### Relevant log output

_No response_</details>

**Comment by gadagashwini** [comment]
Hi @KarthiAru, Thanks for raising this issue here. Could you elaborate the feature request with context would be more appropriate. Thank you!

**Comment by bhack** [comment]
@KarthiAru  You need to re-open this ticket in the Keras repo.

In the new ticket in you could mention @Rocketknight1 and @cpuimage in the case they want to contribute their own versions to the Keras repo:

https://github.com/Rocketknight1/minimal_lczero/blob/master/tf_adan.py
https://github.com/cpuimage/keras-optimizer/blob/main/optimizer/Adan.py

Thanks

**Comment by KarthiAru** [comment]
> 

Done - https://github.com/keras-team/keras/issues/17085

**Comment by gadagashwini** [comment]
Hi @KarthiAru, Can we close this issue, we can track on keras-team/keras/issues/17085. Thank you!

**Comment by KarthiAru** [comment]
> Hi @KarthiAru, Can we close this issue, we can track resolution on [keras-team/keras/issues/17085](https://github.com/keras-team/keras/issues/17085). Thank you!

Sure

**Comment by DenisVorotyntsev** [comment]
I created Adan optimizer in Tensorflow, have a look - https://github.com/DenisVorotyntsev/Adan
