### ISSUE TITLE
Error getting persistent gradients from model converted from tf1 to tf2 with tfa.seq2seq layers: "'NoneType' object has no attribute 'outer_context'"

### ISSUE THREAD

**Issue by NoAchache** [tensorflow/tensorflow#57833]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 18.04

### Python version

3.9

### CUDA/cuDNN version

None

### Current Behaviour?

After converting a model from tf1 to tf2, I cannot use the tf2 model with tf.GradientTape(persistent=True).

The model uses tfa.seq2seq layers, which are most likely the source of the error (e.g. replacing the content of the function network below with a single tf.compat.v1.layers.Dense works fine)

If anyone could help me that would be great, thank you!

### Standalone code to reproduce the issue
Here are 2 snippets to reproduce the error:
- First run this snippet to create/save the model

```shell
import functools
import tensorflow as tf
import tensorflow_addons as tfa

MODEL_FOLDER = "model"
LSTM_UNITS = 3

def network(input):
    attention_mechanism = tfa.seq2seq.BahdanauAttention(
        1, input, memory_sequence_length=None
    )
    cell = tf.compat.v1.nn.rnn_cell.LSTMCell(
      LSTM_UNITS,
    )
    attention_cell = tfa.seq2seq.AttentionWrapper(
        cell, attention_mechanism, output_attention=False
    )

    embedding_fn = functools.partial(tf.compat.v1.one_hot, depth=10)
    output_layer = tf.compat.v1.layers.Dense(
        10,
    )

    train_helper = tfa.seq2seq.GreedyEmbeddingSampler(embedding_fn)
    decoder = tfa.seq2seq.BasicDecoder(
            cell=attention_cell, sampler=train_helper, output_layer=output_layer
    )
    init_kwargs = {}
    init_kwargs["start_tokens"] = tf.compat.v1.fill([1], 1)
    init_kwargs["end_token"] = 2
    init_kwargs["initial_state"] = attention_cell.get_initial_state(
        batch_size=1, dtype=tf.compat.v1.float32
    )
    outputs, _, output_lengths = tfa.seq2seq.dynamic_decode(
        decoder=decoder,
        output_time_major=False,
        impute_finished=False,
        maximum_iterations=1,
        decoder_init_kwargs=init_kwargs,
    )
    return outputs


def main(_):
    input = tf.compat.v1.placeholder(dtype=tf.compat.v1.float32, shape=[1, 1, LSTM_UNITS])

    fetches = {
        "output": network(input).rnn_output,
    }

    with tf.compat.v1.Session() as sess:
        builder = tf.compat.v1.saved_model.Builder(MODEL_FOLDER)

        sess.run(
            [
                tf.compat.v1.global_variables_initializer(),
                tf.compat.v1.local_variables_initializer(),
                tf.compat.v1.tables_initializer(),
            ]
        )

        sig_def = tf.compat.v1.saved_model.predict_signature_def(
            inputs={"input": input}, outputs=fetches
        )

        builder.add_meta_graph_and_variables(
            sess,
            tags=["serve"],
            signature_def_map={
                tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY: sig_def
            },
        )
        builder.save()

if __name__ == "__main__":

    # Save model
    tf.compat.v1.disable_eager_execution()
    tf.compat.v1.disable_v2_behavior()
    tf.compat.v1.app.run()
```

- Then run this snippet to load/use the model

```
import tensorflow as tf

MODEL_FOLDER = "model"
LSTM_UNITS = 3

if __name__ == "__main__":

    # Load model and use it
    input = tf.ones((1, 1, LSTM_UNITS))
    model = tf.saved_model.load(
        MODEL_FOLDER, tags="serve"
    ).signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]

    with tf.GradientTape():
        print(model(input)) # This works
    with tf.GradientTape(persistent=True):
        print(model(input)) # AttributeError: 'NoneType' object has no attribute 'outer_context'
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@NoAchache I tried to replicate the issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/c31d02275324d3be74c838fd2820e378/57833.ipynb) here and confirm the same?
Thank you!

**Comment by NoAchache** [comment]
Hello, thanks for providing the gist. I fixed it, here is the correct version: https://colab.research.google.com/drive/15p8XmnN0Rkb4-Ho-z8nwr0MGRt_okOUM?usp=sharing

**Comment by NoAchache** [comment]
Thanks for providing the gist. I fixed it: https://colab.research.google.com/drive/15p8XmnN0Rkb4-Ho-z8nwr0MGRt_okOUM#scrollTo=2GN0Z3CWtG8q 
PS: Not exactly sure why the 2nd cell outputs an error, but it correctly saves the model

**Comment by sushreebarsa** [comment]
@NoAchache Please move this issue to closed status if it is resolved ?
Thank you!

**Comment by NoAchache** [comment]
@sushreebarsa I meant I fixed the gist to make it look like the issue I have. The issue is not fixed. Sorry for the misundersranding:

**Comment by NoAchache** [comment]
Is there any update on the issue?

**Comment by NoAchache** [comment]
@sachinprasadhs is there any update on the issue by any chance?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
