### ISSUE TITLE
How to implement state with dynamic shape? How about a VariableArray?

### ISSUE THREAD

**Issue by flixxox** [tensorflow/tensorflow#57843]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8.2

### Current Behaviour?

I try to build a module that has dynamic shaped state and I struggle to do it in Tensorflow with minimal changes to the models.

I have a custom training pipeline and build the model mostly from scratch. My use-case is a Transformer encoder-decoder model used for machine translation. In search it is enough to apply the encoder once, and the decoder for every new input, except for the decoder self-attention module. This module needs to work on the current input and all previous.

Since these models are basically nested modules it would be annoying to pass the state as an argument to __call__ functions. I would need to modify many lines of code and, if I want to use the same search code for models without state, have an unused argument. A better solution would be to have the state as a member variable which can be cleared/reshaped from the outside.

As far as I know tf.Variables are the only object capable of being a member variable? But since they have fixed shape after construction I cannot use them.

Since TensorFlow is huge, I dont know if there are already features or tricks that can do a dynamically shaped state. Does anyone know anything about this? If it is not possible, my feature request is a VariableArray that basically wraps a TensorArray similar to Variables and Tensors.

### Standalone code to reproduce the issue

To illustrate the issue I made a minimal example

```python
import tensorflow as tf
class ModuleLevel2(tf.Module):
    
    def __init__(self):
        self.state = tf.TensorArray(size=0, dynamic_size=True, clear_after_read=False, dtype=tf.float32)

    def __call__(self, x):
        self.state = self.state.write(self.state.size(), x)
        x = self.state.stack()
        x = tf.identity(x) # Some op that requires all saved inputs
        tf.print(x)

class ModuleLevel1(tf.Module):

    def __init__(self):
        self.module2 = ModuleLevel2()

    def __call__(self, x):
        self.module2(x)

class Model(tf.Module):

    def __init__(self):
        self.module1 = ModuleLevel1()

    def __call__(self, x):
        self.module1(x)

model = Model()

@tf.function
def search():
    for i in range(10):
        x = (i*5)+tf.constant([1,2,3,4,5], dtype=tf.float32)
        model(x)

search()
```

The snippet generates the error seen below in "Relevant log output".

If search is not a tf.function the snippet works which is in my opinion undesirable behavior.

What is possible is to create the state outside of the model and pass it as an argument but as seen in the below snippet I have to modify all arguments and return values of modules on upper abstraction levels:

```python
import tensorflow as tf

class ModuleLevel2(tf.Module):
    
    def __init__(self):
        pass

    def __call__(self, x, state):
        state = state.write(state.size(), x)
        x = state.stack()
        x = tf.identity(x) # Some op that requires all saved inputs
        tf.print(x)
        return state

class ModuleLevel1(tf.Module):

    def __init__(self):
        self.module2 = ModuleLevel2()

    def __call__(self, x, state):
        state = self.module2(x, state)
        return state

class Model(tf.Module):

    def __init__(self):
        self.module1 = ModuleLevel1()

    def __call__(self, x, state):
        state = self.module1(x, state)
        return state

model = Model()

@tf.function
def search():
    state = tf.TensorArray(size=0, dynamic_size=True, clear_after_read=False, dtype=tf.float32)
    for i in range(10):
        x = (i*5)+tf.constant([1,2,3,4,5], dtype=tf.float32)
        state = model(x, state)

search()
```

### Relevant log output
```shell
Traceback (most recent call last):
  File "~/snippets/tf_test.py", line 37, in <module>
    search()
  File "~/lib/Python3.8.2/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "~/lib/Python3.8.2/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 1127, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: in user code:

    File "~/snippets/tf_test.py", line 35, in search  *
        model(x)
    File "~/snippets/tf_test.py", line 27, in __call__  *
        self.module1(x)
    File "~/snippets/tf_test.py", line 19, in __call__  *
        self.module2(x)
    File "~/snippets/tf_test.py", line 8, in __call__  *
        self.state = self.state.write(self.state.size(), x)

    OperatorNotAllowedInGraphError: Using a symbolic `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.
```
</details>

**Comment by tilakrayal** [comment]
@flixxox,
The problem might be because pre-processing was returning an array instead of a tuple that is required in the graph. Could you please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/32546#issuecomment-538549035) from the developer and the [issue](https://github.com/tensorflow/tensorflow/issues/33308) with the similar error. Thank you!

**Comment by flixxox** [comment]
Sorry I cannot see where the linked issues relate to my issue. Where do I return an array instead of a tuple? 

I did not append the full error message. Sorry for that. I updated the issue with the full traceback. Does that change something?

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.8, v2.10 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3b5143743ce959af96762d745725d364/untitled635.ipynb).

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
