### ISSUE TITLE
Master build failure on s390x due to TensorFlow Runtime

### ISSUE THREAD

**Issue by namrata-ibm** [tensorflow/tensorflow#57844]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

master

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

NA

### Python version

Python 3.8.10

### Bazel version

5.1.1

### GCC/Compiler version

9.4.0

### CUDA/cuDNN version

NA

### GPU model and memory

NA

### Current Behaviour?

Build from source fails with error: `external/tf_runtime/include/tfrt/host_context/attribute_utils.h:55:5: error: static assertion failed: big-endian not yet supported here
   55 |     ASSERT_LITTLE_ENDIAN();`

**Confirmed that this was caused due to commit f8145fac4**

Since TensorFlow Runtime doesn't support big endian yet and XLA Runtime compilation is optional as mentioned in the commit description, is there a way to build without TensorFlow Runtime?

Appreciate any inputs on this. Thank you!

### Standalone code to reproduce the issue

```shell
git clone https://github.com/tensorflow/tensorflow
cd tensorflow
yes "" | ./configure
bazel --host_jvm_args="-Xms1024m" --host_jvm_args="-Xmx2048m" build  --define=tensorflow_mkldnn_contraction_kernel=0 --define tflite_with_xnnpack=false //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```shell
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (1 packages loaded, 998 targets configured).
INFO: Found 1 target...
ERROR: /home/test/.cache/bazel/_bazel_test/24685d064c07f7346b48c2d13ec3ad69/external/tf_runtime/BUILD:138:16: Compiling lib/host_context/kernel_frame.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 102 arguments skipped)
In file included from external/tf_runtime/include/tfrt/host_context/attribute_utils.h:30,
                 from external/tf_runtime/include/tfrt/host_context/kernel_frame.h:32,
                 from external/tf_runtime/lib/host_context/kernel_frame.cc:20:
external/tf_runtime/include/tfrt/host_context/attribute_utils.h: In constructor 'tfrt::Attribute<T>::Attribute(const void*)':
external/tf_runtime/include/tfrt/host_context/attribute_utils.h:55:5: error: static assertion failed: big-endian not yet supported here
   55 |     ASSERT_LITTLE_ENDIAN();
      |     ^~~~~~~~~~~~~~~~~~~~
external/tf_runtime/include/tfrt/host_context/attribute_utils.h: In constructor 'tfrt::CompilationUnitAttribute::CompilationUnitAttribute(const void*)':
external/tf_runtime/include/tfrt/host_context/attribute_utils.h:130:5: error: static assertion failed: big-endian not yet supported here
  130 |     ASSERT_LITTLE_ENDIAN();
      |     ^~~~~~~~~~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-unused-local-typedef'
cc1plus: warning: unrecognized command line option '-Wno-array-parameter'
cc1plus: warning: unrecognized command line option '-Wno-unknown-warning'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3144.838s, Critical Path: 163.72s
INFO: 4287 processes: 19 internal, 4268 local.
FAILED: Build did NOT complete successfully
```
</details>

**Comment by namrata-ibm** [comment]
@cota any inputs on this issue would be helpful! Thank you..

**Comment by namrata-ibm** [comment]
@tilakrayal could you please help in checking this? or may be point to someone who can help in fixing above. Thank you very much!

**Comment by namrata-ibm** [comment]
@angerson Could you please check?

This issue will be seen on all big endian machines. Also as per [this](https://github.com/tensorflow/tensorflow/blob/9e12018a40b5024f51bbaa4d27dcad047bd8449f/.bazelrc#L686) TFRT integration should be optional as of now. Is there a way to disable it?

**Comment by angerson** [comment]
I don't know about this one, sorry.

**Comment by cota** [comment]
Hi!
Sorry for the breakage, I wasn't aware that big endian machines weren't supported in tfrt.
The dependence on tfrt is fairly minimal, so probably the easiest way to fix this is to extract what we depend on into its own library in tfrt and just depend on that.
I am currently working on a fix.

**Comment by namrata-ibm** [comment]
Thank you @cota

**Comment by cota** [comment]
The fix is not trivial, so here's a possible workaround.

Assuming you don't need XLA, can you please try to build with `--define=with_xla_support=false`?

**Comment by namrata-ibm** [comment]
@cota Thank you, the build passes with above flag. However as some of the XLA functionality is working on s390x, it would be good to catch more failures in master through our CI. Is there a way to disable only TensorFlow Runtime?

**Comment by cota** [comment]
Tensorflow Runtime, in particular the hostcontext library in it, is right now a dependence in order to build XLA. The proper fix for this is to extract some bits out of hostcontext and depend just on those; that is what I'm working on.

Note though that eventually we will remove the dependence on TFRT from Tensorflow, but we are not there yet.

**Comment by namrata-ibm** [comment]
Thank you for sharing, I guess will allow builds to run with above flag for now and I will monitor once above is accomplished. 
Is there some issue to track the same?

**Comment by cota** [comment]
We can just use this issue for that -- I will mark it as fixed once the dependence is removed. Thanks!

**Comment by cota** [comment]
@namrata-ibm: can you please test that you can now build with XLA enabled on s390x? Make sure you check out the repo's HEAD -- I just committed what I believe should be the final fix needed. Thanks!

**Comment by namrata-ibm** [comment]
Thanks @cota , Above reported error doesn't occur anymore. Thank you!
