### ISSUE TITLE
how can i get node name

### ISSUE THREAD

**Issue by hanyanLWD** [tensorflow/tensorflow#57857]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

No

### OS Platform and Distribution

ubuntu 18.04

### Mobile device

ubuntu 18.04

### Python version

3.6

### Bazel version

3.7

### Current Behaviour?

```shell
I can use node_id to get node, use context->GetNodeAndRegistration(context, node_id, &node, &reg)).But i cant not get node_name in node ,how can i get node name
```

### Standalone code to reproduce the issue

```shell
I dont have test case
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@hanyanLWD If it is lite model/ keras model, could you try to use [netron](https://netron.app/) webapp to get the node name and other details. Thank you!

**Comment by hanyanLWD** [comment]
I want to know in source code,  how can i get node name

**Comment by mohantym** [comment]
Hi @sachinprasadhs !
Could you look at this query.
Thank you!

**Comment by sachinprasadhs** [comment]
TFLIte implementation of subgraph references to `node_index` to get the internal pointer to all the Tensorflow lite nodes.
You can see the same implementation in the code [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/core/subgraph.h#L581).
You can get the subgraph name [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/core/subgraph.h#L885).

**Comment by hanyanLWD** [comment]
how can i get every Tensorflow lite node in  Tensorflow lite model

**Comment by hanyanLWD** [comment]
> how can i get every Tensorflow lite node in Tensorflow lite model

**Comment by mohantym** [comment]
Hi @hanyanLWD !
We are checking to see whether you still need help in this issue .  You can get the node name using [get_tensor_details(i)](https://www.tensorflow.org/api_docs/python/tf/lite/Interpreter#get_tensor_details) method (index wise )from interpreter api  .

Thank you!
