### ISSUE TITLE
ValueError: Python inputs incompatible with input_signature:

### ISSUE THREAD

**Issue by Prasun92** [tensorflow/tensorflow#57859]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

Linux

### Python version

3.8

### CUDA/cuDNN version

cuda 11.0.3/cudnn 8

### GPU model and memory

yes

### Current Behaviour?

```shell
A bug happened!
ValueError: Python inputs incompatible with input_signature:
      inputs: (
        Tensor("args_0:0", shape=(), dtype=string))
      input_signature: (
        TensorSpec(shape=(None,), dtype=tf.float32, name=None)).
```

### Standalone code to reproduce the issue

```shell
# Using yamnet transfer learning model for sound classification

yamnet_model_handle = 'https://tfhub.dev/google/yamnet/1'
yamnet_model = hub.load(yamnet_model_handle)

filenames = filtered_pd['Filename']
targets = filtered_pd['Target']
split = filtered_pd['Split']

main_ds = tf.data.Dataset.from_tensor_slices((filenames, targets, split))
print(main_ds.element_spec)

#@tf.function
def load_wav_16k_mono(filename):
    try:
        file_contents = tf.io.read_file(filename)
        wav, sample_rate = tf.audio.decode_wav(file_contents, desired_channels=1)
        wav = tf.squeeze(wav, axis=-1)
        sample_rate = tf.cast(sample_rate, dtype=tf.int64)
        wav = tfio.audio.resample(wav, rate_in=sample_rate, rate_out=16000)
        return wav
    except Exception as e:
        print(filename)
        return str(e)

def load_wav_for_map(filename, label, split):
    print(filename)
    return load_wav_16k_mono(filename), label, split

main_ds = main_ds.map(load_wav_for_map)
#print([x for x in main_ds])

def extract_embedding(wav_data, label, split):
    scores, embeddings, spectrogram = yamnet_model(wav_data)
    num_embeddings = tf.shape(embeddings)[0]
    return (embeddings,
            tf.repeat(label, num_embeddings),
            tf.repeat(split, num_embeddings))

# extract embedding
main_ds = main_ds.map(extract_embedding).unbatch()
main_ds.element_spec

cached_ds = main_ds.cache()
train_ds = cached_ds.filter(lambda embedding, label, split: split == 'train')
val_ds = cached_ds.filter(lambda embedding, label, split: split == 'val')
```

### Relevant log output

```shell
(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None), TensorSpec(shape=(), dtype=tf.string, name=None))
Tensor("args_0:0", shape=(), dtype=string)
WARNING:tensorflow:AutoGraph could not transform <function resample at 0x7f2700550430> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unable to open file: libtensorflow_io.so, from paths: ['/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZNK10tensorflow10FileSystem8BasenameESt17basic_string_viewIcSt11char_traitsIcEE']
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function resample at 0x7f2700550430> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unable to open file: libtensorflow_io.so, from paths: ['/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZNK10tensorflow10FileSystem8BasenameESt17basic_string_viewIcSt11char_traitsIcEE']
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Tensor("args_0:0", shape=(), dtype=string)
Cleaning up all outstanding Run operations, waiting 300.0 seconds
1 items cleaning up...
Cleanup took 0.5498418807983398 seconds
Traceback (most recent call last):
  File "uc3_train_data_prep.py", line 187, in <module>
    main_ds = main_ds.map(extract_embedding).unbatch()
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 2048, in map
    return MapDataset(self, map_func, preserve_cardinality=True, name=name)
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 5243, in __init__
    self._map_func = structured_function.StructuredFunctionWrapper(
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/data/ops/structured_function.py", line 271, in __init__
    self._function = fn_factory()
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2567, in get_concrete_function
    graph_function = self._get_concrete_function_garbage_collected(
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2533, in _get_concrete_function_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2711, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2627, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 1141, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/data/ops/structured_function.py", line 248, in wrapped_fn
    ret = wrapper_helper(*args)
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/data/ops/structured_function.py", line 177, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 692, in wrapper
    raise e.ag_error_metadata.to_exception(e)
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 689, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_filedlxifabg.py", line 10, in tf__extract_embedding
    (scores, embeddings, spectrogram) = ag__.converted_call(ag__.ld(yamnet_model), (ag__.ld(wav_data),), None, fscope)
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 377, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 459, in _call_unconverted
    return f(*args)
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/saved_model/load.py", line 686, in _call_attribute
    return instance.__call__(*args, **kwargs)
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/azureml-envs/azureml_0231a8f3aec1f5ab1653fe92c14fe093/lib/python3.8/site-packages/tensorflow/python/eager/function_spec.py", line 531, in _convert_inputs_to_signature
    raise ValueError("Python inputs incompatible with input_signature:\n"
ValueError: in user code:

    File "uc3_train_data_prep.py", line 177, in extract_embedding  *
        scores, embeddings, spectrogram = yamnet_model(wav_data)

    ValueError: Python inputs incompatible with input_signature:
      inputs: (
        Tensor("args_0:0", shape=(), dtype=string))
      input_signature: (
        TensorSpec(shape=(None,), dtype=tf.float32, name=None)).
```
</details>

**Comment by tilakrayal** [comment]
@Prasun92,
I was facing a different issue while trying to execute the code. Kindly find the gist of it here and provide the complete code & dependencies. 
Also could you try making the input tensor type **uint8** instead of **float32**. Thank you!

**Comment by Prasun92** [comment]
@tilakrayal 
Please find the attached gist of my notebook [here](https://colab.research.google.com/drive/1DfXs6Dg1ErtarBfCXOmvl2pp_vw8oPiG#scrollTo=Buuv5Qm9Kmzd).

**Comment by Prasun92** [comment]
[Audio_data.zip](https://github.com/tensorflow/tensorflow/files/9674292/Audio_data.zip)
Please find the attached sample dataset for regenerating the bug

**Comment by Prasun92** [comment]
@tilakrayal please let me know, what's the issue causing this error... waiting for your response

**Comment by Prasun92** [comment]
Sorry, for inconvenience, please use [this](https://gist.github.com/Prasun92/2e8211823af3ae10ffd8bbc3817be548) link.

**Comment by Prasun92** [comment]
@tilakrayal if still facing the issue with opening the code file, please find the code below

import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_io as tfio
import matplotlib.pyplot as plt
import seaborn as sns

yamnet_model_handle = 'https://tfhub.dev/google/yamnet/1'
yamnet_model = hub.load(yamnet_model_handle)

rows = []
for root_dir, class_name, filename in os.walk('/content/Regenerate_issue/Audio_Data'):
    
    for f in filename:
        file_path = os.path.join(root_dir, f)
        row=[]
        row.append(file_path)
        row.append(root_dir.split('/')[-1])
        rows.append(row)

        
train_df = pd.DataFrame(rows, columns=['Filename','Category'])

train, val = train_test_split(train_df, test_size=0.2, random_state=9, stratify=train_df['Category'])
train['Split'] = 'train'
val['Split'] = 'val'

train_df = pd.concat([train, val], axis=0)

my_classes = train_df['Category'].unique().tolist()
my_classes.sort(key = lambda x: (x is not None,x))
print("my classes", my_classes)

map_class_to_id={}
j=0
for i in my_classes:
    map_class_to_id[i] = j
    j=j+1

train_class_id = train_df['Category'].apply(lambda name: map_class_to_id[name])
filtered_pd = train_df.assign(Target=train_class_id)
print(filtered_pd.head(5))


filenames = filtered_pd['Filename']
targets = filtered_pd['Target']
split = filtered_pd['Split']

#from_tensor_slices creates a dataset with a separate element for each row of the input tensor
main_ds = tf.data.Dataset.from_tensor_slices((filenames, targets, split))
print(main_ds.element_spec)
#print([x for x in main_ds])

#@tf.function
def load_wav_16k_mono(filename):
    try:
        file_contents = tf.io.read_file(filename)
        wav, sample_rate = tf.audio.decode_wav(file_contents, desired_channels=1)
        #Given a tensor input, this operation returns the same type of tensor and removes all dimensions of size 1
        wav = tf.squeeze(wav, axis=-1)
        #cast() function is used to cast a specified Tensor to a new data type
        sample_rate = tf.cast(sample_rate, dtype=tf.int64)
        #wav_8 = tfio.audio.resample(wav, rate_in=sample_rate, rate_out=8000)
        wav = tfio.audio.resample(wav, rate_in=sample_rate, rate_out=16000)
        #print('new_tensor', wav)
        return wav
    except Exception as e:
        print(filename)
        return str(e)

def load_wav_for_map(filename, label, split):
    print(filename)
    return load_wav_16k_mono(filename), label, split

main_ds = main_ds.map(load_wav_for_map)
#print([x for x in main_ds])

def extract_embedding(wav_data, label, split):
    #run YAMNet to extract embedding from the wav data
    scores, embeddings, spectrogram = yamnet_model(wav_data)
    num_embeddings = tf.shape(embeddings)[0]
    #repeat() method of tf.data.Dataset class is used for repeating the tensors in dataset.
    #For each audio file, you'll extract the embeddings using the YAMNet model. For each audio file, YAMNet is executed.
    #The embeddings output is paired with the same label and split
    return (embeddings,
            tf.repeat(label, num_embeddings),
            tf.repeat(split, num_embeddings))

# extract embedding
main_ds = main_ds.map(extract_embedding).unbatch()
main_ds.element_spec
#[print(x) for x in main_ds]

cached_ds = main_ds.cache()
#The tf.data.Dataset.filter() function is used to filter the dataset according to predicate.
train_ds = cached_ds.filter(lambda embedding, label, split: split == 'train')
val_ds = cached_ds.filter(lambda embedding, label, split: split == 'val')

# remove the label column now that it's not needed anymore
remove_fold_column = lambda embedding, label, split: (embedding, label)

train_ds = train_ds.map(remove_fold_column)
val_ds = val_ds.map(remove_fold_column)

#The batch size is a hyperparameter that defines the number of samples to work through before updating the internal model parameters.
train_ds = train_ds.cache().shuffle(1000).batch(32).prefetch(tf.data.AUTOTUNE)
val_ds = val_ds.cache().batch(32).prefetch(tf.data.AUTOTUNE)

**Comment by tilakrayal** [comment]
@Prasun92,
The error stating that **Python inputs incompatible with input_signature** which means the input feed which you are providing for the signature was different. Could you please provide the similar input. And also some corruption might be happened while using the audiofiles which leads to different input sizes.

Kindly open a tensorflow discussion [forum](https://discuss.tensorflow.org/) issue for this as it is not a bug or feature request, Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions.

**Comment by Prasun92** [comment]
@tilakrayal Please provide me the solution, to solve this issue. Is there any wrong input i am providing to the model. you have my code. Do i need to reshape the input but the input signature is None, so i am just passing the audio tensor of undefined shape.
