### ISSUE TITLE
Clarify functionality of deserialized subclassed models in docs

### ISSUE THREAD

**Issue by ascillitoe** [tensorflow/tensorflow#57858]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Feature Request

### Source

binary

### Tensorflow Version

tf 2.9 and 2.10

### Custom Code

Yes

### Current Behaviour?

In the `SavedModel` format documentation [here](https://www.tensorflow.org/guide/keras/save_and_serialize#how_savedmodel_handles_custom_objects), it says:

> In the absence of the model/layer config, the call function is used to create a model that exists like the original model which can be trained, evaluated, and used for inference.

and:

> The first loaded model is loaded using the config and CustomModel class. The second model is loaded by dynamically creating the model class that acts like the original model.

I am finding that when a subclassed model is saved in the `SavedModel` format, upon re-loading it can be trained, evaluated, and used for inference in the same way as the original model. However, other functionality such as the custom `from_config` and `get_config` methods do not work. For example, attempting to clone the loaded model with `loaded_model_clone = loaded_model.from_config(loaded_model.get_config())` leads to errors.

I assume this is because loading a `CustomModel` without passing `custom_objects` (or registering it) gives a `keras.saving.saved_model.load.CustomModel`, which does not contain the full functionality of the original `CustomModel`? It would be helpful if the docs clarified the functional limitations of a `SavedModel` loaded without the `custom_objects` being provided.

The documentation (and example) in [SavedModel format](https://www.tensorflow.org/guide/keras/save_and_serialize#savedmodel_format) also seems to contradict the guidance in [Custom Objects](https://www.tensorflow.org/guide/keras/save_and_serialize#custom_objects). In the former, it suggests a custom `SavedModel` can be loaded without providing the `custom_objects`, albeit with limited functionality, whereas the latter suggests you should always register or pass in the `custom_objects` (i.e. "_Additionally, you should use register the custom object so that Keras is aware of it._").

### Standalone code to reproduce the issue

Extended from example in [SavedModel format](https://www.tensorflow.org/guide/keras/save_and_serialize#savedmodel_format).

Colab notebook gist: https://gist.github.com/ascillitoe/42702d4cab382880b55ab7344c694a23

Code:

```python
import tensorflow as tf
from tensorflow import keras
import numpy as np

class CustomModel(keras.Model):
    def __init__(self, hidden_units):
        #super(CustomModel, self).__init__()
        super().__init__()
        self.hidden_units = hidden_units
        self.dense_layers = [keras.layers.Dense(u) for u in hidden_units]

    def call(self, inputs):
        x = inputs
        for layer in self.dense_layers:
            x = layer(x)
        return x

    def get_config(self):
        return {"hidden_units": self.hidden_units}

    @classmethod
    def from_config(cls, config):
        return cls(**config)


model = CustomModel([16, 16, 10])
# Build the model by calling it
input_arr = tf.random.uniform((1, 5))
outputs = model(input_arr)
model.save("my_model")

# Option 1: Load with the custom_object argument.
loaded_1 = keras.models.load_model(
    "my_model", custom_objects={"CustomModel": CustomModel}
)

# Option 2: Load without the CustomModel class.

# Delete the custom-defined model class to ensure that the loader does not have
# access to it.
del CustomModel

loaded_2 = keras.models.load_model("my_model")
np.testing.assert_allclose(loaded_1(input_arr), outputs)
np.testing.assert_allclose(loaded_2(input_arr), outputs)

print("\nInitial Save/Load\n################################################")
print("Original model:", model)
print("Model Loaded with custom objects:", loaded_1)
print("Model loaded without the custom object class:", loaded_2)

print("\nCloning\n################################################")
cloned_loaded_1 = loaded_1.__class__.from_config(loaded_1.get_config())
print("Clone of Model Loaded with custom objects:", cloned_loaded_1)

cloned_loaded_2 = loaded_2.__class__.from_config(loaded_2.get_config())
print("Clone of Model loaded without the custom object class:", cloned_loaded_2)
```

### Relevant log output

```shell
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.
WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.

Initial Save/Load
###################################
Original model: <__main__.CustomModel object at 0x7fbf613e1950>
Model Loaded with custom objects: <__main__.CustomModel object at 0x7fbf60f34e10>
Model loaded without the custom object class: <keras.saving.saved_model.load.CustomModel object at 0x7fbf60ea7b10>

Cloning
################################################
Clone of Model Loaded with custom objects: <__main__.CustomModel object at 0x7fbf613e89d0>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/keras/engine/training.py in from_config(cls, config, custom_objects)
   3049                 try:
-> 3050                     model = cls(**config)
   3051                 except TypeError as e:

4 frames
TypeError: ('Keyword argument not understood:', 'hidden_units')

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/keras/engine/training.py in from_config(cls, config, custom_objects)
   3051                 except TypeError as e:
   3052                     raise TypeError(
-> 3053                         "Unable to revive model from config. When overriding "
   3054                         "the `get_config()`, make sure that the returned "
   3055                         "config contains all items used as arguments in the "

TypeError: Unable to revive model from config. When overriding the `get_config()`, make sure that the returned config contains all items used as arguments in the constructor to <class 'keras.saving.saved_model.load.CustomModel'>, which is the default behavior. You can override this default behavior by defining a `from_config` method to specify how to create an instance of CustomModel from the config. 

Error encountered during deserialization:
('Keyword argument not understood:', 'hidden_units')
```
</details>

**Comment by tilakrayal** [comment]
@ascillitoe,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by ascillitoe** [comment]
Hi @tilakrayal, done, thanks!
