### ISSUE TITLE
[Keras] `Conv2DTranspose` constfolding issue with variable batch size.

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorflow/tensorflow#57853]
### TF Version
TF 2.10

## Gist of the issue

The `Conv2DTranspose` does not behave the same when batch_size is fixed (e.g. batch_size=32) and when it's variable (e.g. batch_size=None). The problem seems to reside in the way `constant_folding` is working or in the way `input_sizes` is managed (which in this context is actually meaning the output shape).

## Google Colab for Repro

Full repro case in detail: https://colab.research.google.com/drive/1sv3c8KqcK1lcUKmvJAAQheSU9VPiJH6N?usp=sharing

### 1. Let's create the model

Picture the most basic model using `Conv2DTranspose`

```python
def create_model(batch_size=None):
  inputs = keras.layers.Input((128, 128, 3), dtype=tf.float32, batch_size=batch_size)

  net = keras.layers.Conv2DTranspose(filters=32, kernel_size=(3, 3))(inputs)

  model = keras.models.Model(inputs=inputs, outputs=net)
  return model
```

**Fixed BS:**
![image](https://user-images.githubusercontent.com/10923599/192428905-7ac02c41-7acf-4ff1-b254-d511c5fcb860.png)

**Variable BS:**
![image](https://user-images.githubusercontent.com/10923599/192428961-49602fab-72f8-432e-997a-976cdc0ae359.png)

So far so good, everything looks the same ...

### 2. Freeze + ConstFold + Plot

Now let's freeze the graph and plot the resulting graphdef:

**Fixed BS:**
![image](https://user-images.githubusercontent.com/10923599/192429189-04d2f615-a486-46ac-929e-1fd447470b2d.png)

**Variable BS:**
![image](https://user-images.githubusercontent.com/10923599/192429232-7315ce94-ad2a-4a7a-b718-36ac58428d97.png)

## Conclusion

I hope the difference is fairly self explanatory, and that's a problem because that's a very different graph for inference and a lot more complicated graph to optimize by compilers (e.g. TF-TRT, XLA, TF Lite, TVM, etc).

The `input_sizes` tensor **should** have been const folded, it's perfectly independent of input batch size. There's no reason to the best of my knowledge that the const folding behavior changes by changing the BS value. 

My guess is that the shape tensor is seen as variable because of one value being None, however the None dimension is not being used and therefore the slice of the Shape tensor is perfectly static in this case and should have been const folded.

## To go further

It should not be runtime computed when the shape are perfectly static, we should not need to constfold this graph in the first place. This could be perfectly computed in python when all the shapes are defined. This is very expensive to compute over and over at each iteration even in training.

A very similar issue was fixed with a different layer here, we should consider a similar fix here: https://github.com/tensorflow/tensorflow/pull/31450/files

**Comment by DEKHTIARJonathan** [comment]
@reedwm @bixia1 CC

**Comment by sushreebarsa** [comment]
@DEKHTIARJonathan 
This issue seems to be Keras issue.  Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) as Keras development is fully moving to [github.com/keras-team/keras](http://github.com/keras-team/keras). All issues and PRs related to keras will be addressed in that repo.
To know more see this TF forum discussion ; 
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by DEKHTIARJonathan** [comment]
Will do thanks. I keep this one opened for reference

**Comment by sachinprasadhs** [comment]
Could you please refer the comment here https://github.com/keras-team/keras/issues/17094#issuecomment-1284609390 and let us know if you still need assistance. Thanks!
