### ISSUE TITLE
ERROR: Node number 7 (FlexRaggedTensorToTensor) failed to prepare.

### ISSUE THREAD

**Issue by DemoCodeProfile** [tensorflow/tensorflow#57860]
```
func setupInterpreter() {
        var options = Interpreter.Options()
        options.threadCount = 1
        do {
            interpreter = try Interpreter(modelPath: tfModelUrl.path)
            try interpreter.allocateTensors()
        } catch let error {
            return
        }
    }
```
```
let outputTensor: Tensor
        do {
            let inputTensor = try interpreter.input(at: 0)
            try interpreter.copy(data, toInputAt: 0)
            try interpreter.invoke()
            outputTensor = try interpreter.output(at: 0)
        } catch {
            print("Error", error.localizedDescription)
        }
```

Error Must call allocateTensors().

ERROR: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select

Use instruction https://www.tensorflow.org/lite/guide/ops_select

**Comment by mohantym** [comment]
Hi @DemoCodeProfile !
Could you confirm that you have used [select ops syntax](https://www.tensorflow.org/lite/guide/ops_select#convert_a_model) and declared the select ops dependency in[ build.gradle](https://www.tensorflow.org/lite/guide/ops_select#android_aar)  file.

Please share a sample code snippet for the model to replicate this issue.
Thank you!

**Comment by DemoCodeProfile** [comment]
This is iOS

I use pods
    pod 'TensorFlowLiteSwift'
    pod 'TensorFlowLiteSelectTfOps', '~> 0.0.1-nightly'

And add flag to build settings
```-force_load $(SRCROOT)/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.xcframework/ios-arm64/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps```

**Comment by mohantym** [comment]
@DemoCodeProfile !

Could you let us know your Tensorflow version . If version is less than 2.9 , the force load syntax should be 
`-force_load $(SRCROOT)/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps
`

Thank you!

**Comment by DemoCodeProfile** [comment]
Version 2.10.0

For this version correct flag

**Comment by mohantym** [comment]
@DemoCodeProfile !
Would it be possible to share a minimal code or toy model to replicate this issue.
Thank you!

**Comment by DemoCodeProfile** [comment]
https://github.com/DemoCodeProfile/models_tf/blob/main/model_old.tflite

Thanks you!

**Comment by pjpratik** [comment]
Hi @DemoCodeProfile 

The CocoaPods specs for TFLite has been updated with commit https://github.com/tensorflow/tensorflow/commit/d9c5c16bb7b24e2caea426f2bac167ae9df14225.

Could you please check in latest nightly version and let us know if you are still facing the issue?

Thanks.
