### ISSUE TITLE
How to build TensorFlow from source with Clang?

### ISSUE THREAD

**Issue by ganler** [tensorflow/tensorflow#57872]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

v2.10.0

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.8

### Bazel version

5.1.1

### GCC/Compiler version

clang 14

### Current Behaviour?

```shell
I am trying to build TensorFlow with clang and add options for generating coverage information (https://clang.llvm.org/docs/SourceBasedCodeCoverage.html). However, it fails with clang build.
```

### Standalone code to reproduce the issue

```shell
bazel build --verbose_failures //tensorflow/tools/pip_package:build_pip_package --repo_env=CC=clang --copt=-fprofile-instr-generate --copt=-fcoverage-mapping


Removing `--copt=-fprofile-instr-generate --copt=-fcoverage-mapping` also fails.
```

### Relevant log output

```shell
"""
ERROR: /home/jiawei/.cache/bazel/_bazel_jiawei/b619a772dd31287f179cb3c11ac7f523/external/llvm-project/mlir/BUILD.bazel:3204:11: Compiling mlir/lib/Support/IndentedOstream.cpp failed: undeclared inclusion(s) in rule '@llvm-project//mlir:Support':
this rule is missing dependency declarations for the following files included by 'mlir/lib/Support/IndentedOstream.cpp':
  'bazel-out/k8-opt/bin/external/llvm-project/llvm/config.cppmap'
  'bazel-out/k8-opt/bin/external/llvm-project/llvm/Demangle.cppmap'
  'bazel-out/k8-opt/bin/external/llvm_terminfo/terminfo.cppmap'
  'bazel-out/k8-opt/bin/external/llvm_zlib/zlib.cppmap'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 138.453s, Critical Path: 63.33s
INFO: 7649 processes: 4288 internal, 3361 local.
FAILED: Build did NOT complete successfull
"""
```
</details>

**Comment by ganler** [comment]
This seems to be related to:
- https://github.com/tensorflow/tensorflow/issues/55563
- https://github.com/bazelbuild/bazel/issues/15359

**Comment by mohantym** [comment]
Hi @gadagashwini !
Could you look at this issue.
Thank you!

**Comment by lockmatrix** [comment]
I also had the same problem,
I tested tf 2.9, 2.10, 2.11 and master

**Comment by lockmatrix** [comment]
add `--spawn_strategy=sandboxed` solved this problem for me

**Comment by mohantym** [comment]
Hi @ganler !
Command seemed  to be working after excluding clang support in configure.py in master branch and Bazel 5.3.0.
Including clang support in configure.py threw below error in colab.

`ERROR: Config value 'download_clang' is not defined in any .rc file
`

Did you check @lockmatrix's above comment too on testing with. ` --spawn_strategy=sandboxed ` flag as workaround.
Attached [gist](https://colab.sandbox.google.com/gist/mohantym/35d22e582f5d298293fb0f9883094966/tensorflow-ranking.ipynb#scrollTo=pd3q6W4lfpKM) for reference.

But  Adding clang support is still a valid  feature request (currently experimental in 2.11 version) to me.

Thank you!

**Comment by genewitch** [comment]
am i to take:
>WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/2796b3e7ea8a3e7614029f9e307c0113f8d6bb90.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found

as saying that clang builds are not supported, even though ./configure asks if you want to use clang?

i just spent 2 hours trying to figure out why bazel repeatedly says "this rule is missing dependency declarations for the following files included by"

over, and over, and over, for different files. I was apt installing everything it was complaining about, which requires --clean expunge (and sometimes rm -rf ~/.cache/bazel/

Can someone confirm or disconfirm if clang is supported?

**Comment by mohantym** [comment]
Hi @genewitch !
Thanks for the update. Clang is supported and might still be experimental .
Could you share the stacktrace or gist to replicate the above [behavior](https://github.com/tensorflow/tensorflow/issues/57872#issuecomment-1416930093).

Thank you!

**Comment by genewitch** [comment]
> Hi @genewitch ! Thanks for the update. Clang is supported and might still be experimental . Could you share the stacktrace or gist to replicate the above [behavior](https://github.com/tensorflow/tensorflow/issues/57872#issuecomment-1416930093).
> 
> Thank you!

Sure, is the stacktrace everything after the last command executed? or is there a file or command line switch?

**Comment by SuryanarayanaY** [comment]
Hi @ganler ,

Could you please try adding the below flag to the bazel command.

https://github.com/tensorflow/tensorflow/blob/9ae7af468a392c787acb7b7864e545d48569f79d/.bazelrc#L332-L333

Also AFAIK clang will be used for building CUDA kernels. You can find the supported configurations at [.bazelrc](https://github.com/tensorflow/tensorflow/blob/master/.bazelrc) file from source code.

Please have a look at the supported flags and try the build again and let us know if the problem still persists. Thanks!
