### ISSUE TITLE
Computing jacobian for `tf.image.resize` cause Check Failed on cuda

### ISSUE THREAD

**Issue by VictoriaGriffith** [tensorflow/tensorflow#57880]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9, 2.11.0-dev20220927

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

Computing jacobian for `tf.image.resize` cause Check Failed on cuda and session crashes.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
images = tf.zeros([1, 1, 1], dtype=tf.float32)

def f(images):
    size = [224, 224,]
    method = "nearest"
    preserve_aspect_ratio = False
    antialias = False
    return tf.image.resize(images, size, method=method, preserve_aspect_ratio=preserve_aspect_ratio, antialias=antialias, )


with tf.GradientTape(persistent=True) as tape:
    tape.watch(images)
    output = f(images)
print(output.shape) # (222, 224, 1)
g = tape.jacobian(output, [images]) #  Check failed
```

### Relevant log output

```shell
(222, 224, 1)
WARNING:tensorflow:Using a while_loop for converting ResizeNearestNeighborGrad
F ./tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (0 vs. -1822093312)
abort (core dumped)
```
</details>

**Comment by tiruk007** [comment]
@gadagashwini 
I was able to reproduce the issue on Colab by using TF v2.9. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/d938c311bf38e09077cfe91aea15af52/57880.ipynb) for reference.
Thank you!

**Comment by sachinprasadhs** [comment]
We intentionally don't check on GPU, and this is usually documented. On GPU, the check is not worth the extra kernel launch required. Garbage in, garbage out. The calculation has no meaning regardless.

Specifically, quoting from the docs for `scatter_nd`:

> Note that on CPU, if an out of bound index is found, an error is returned. On GPU, if an out of bound index is found, the index is ignored.
