### ISSUE TITLE
Inconsistent behavior of TF eager and XLA in int64 casting

### ISSUE THREAD

**Issue by ganler** [tensorflow/tensorflow#57883]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

'2.11.0-dev20220927' (nightly)

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.8

### Current Behaviour?

```shell
`tf.cast(nan, tf.int64)` has inconsistent behaviour in eager mode and XLA:

- `eager`: -9223372036854775808 (same as numpy)
- `xla`: 0

`xla` should be consistent with TensorFlow eager's behaviour IMO.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np


def fn(x):
    return tf.cast(x, tf.int64)


with tf.device("/GPU:0"):
    print("eager", fn(np.array(np.nan)).numpy())

with tf.device("/GPU:0"):
    print("xla", tf.function(jit_compile=True)(fn)(np.array(np.nan)).numpy())

print("numpy", np.array(np.nan).astype(np.int64))
```

### Relevant log output

```shell
eager -9223372036854775808
xla 0
numpy -9223372036854775808
```
```
</details>

**Comment by dengyinlin** [comment]
I think according to [tf.cast docs](https://www.tensorflow.org/api_docs/python/tf/cast), "casting nan and inf values to integral types has undefined behavior", that's probably why the result is unpredictable.

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow [v2.10](https://colab.research.google.com/gist/tilakrayal/7a4a6e4af0014dc5f8930c6f7979b2b7/untitled630.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/cd7da810dfa22cf21c6226661c3a717e/2-11.ipynb). Kindly find the gist of it here.

**Comment by cheshire** [comment]
This is implementation-defined behavior, so unlikely to have a fix (at least on the XLA side).
