### ISSUE TITLE
Use custom tflite model in flutter, select ops doesn't work on emulator x86

### ISSUE THREAD

**Issue by AntoineChauviere** [tensorflow/tensorflow#57885]
I'm following this : https://www.tensorflow.org/lite/guide/ops_select , in order to convert a model to tflite and use it in flutter (android). 

I added the necessary dependencies but it doesn't work on emulator. I wanted to know if it was only for real devices or if was supposed to work on emulator too?

dependencies {
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
    // This dependency adds the necessary TF op support.
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly-SNAPSHOT'
}

Error : 
[Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference]

**Comment by AntoineChauviere** [comment]
@mohantym any advice? :)

**Comment by mohantym** [comment]
@AntoineChauviere !
I am reinstalling flutter framework in MacOs and will update once I replicate this issue.

Just quick pointer - 
X86 is a desktop Os. You don't need to follow the procedure for Anrdoid/IOS.

Following Python documentation would be fine  as included select ops run time by default in pip package (`pip install tensorflow` , then call tf.lite.Interpreter from it)  

[Reference](https://www.tensorflow.org/lite/guide/ops_select#python)

Thank you!

**Comment by AntoineChauviere** [comment]
@mohantym Thank you for your answer.

But I'm sorry I don't really understand. In fact I converted the model in this way:

#Convert the model
converter = tf.lite.TFLiteConverter.from_keras_model(prediction_model)
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_model = converter.convert()

Then I put the model in the assets folder in flutter and loaded it like this:

 _interpreter = await Interpreter.fromAsset(
        "modele.tflite",
        options: InterpreterOptions()..threads = 4,
      )

Everything is working.

But when I run the inference:

_interpreter.runForMultipleInputs(inputs_cropped, outputs);

I have this error:

Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.

I don't understand how this option can help me (--config=android_arm64 -c opt), where should I add this?

I'm sorry thanks again for your help

**Comment by mohantym** [comment]
Hi @AntoineChauviere !
`--config= c opt  --config=android_arm64` is for building the flex delegate for C++ run time (used when android architecture arm. Command is like below.
`bazel build -c opt --config=android_arm64  tensorflow/lite/delegates/flex:tensorflowlite_flex `

Once built to bazel/bin folder , It will use the select ops runtime automatically.
[Reference.](https://www.tensorflow.org/lite/guide/ops_select#cc)
Thank you!

**Comment by AntoineChauviere** [comment]
Hi @mohantym ! Ok thank's it seems clear. 

I never used bazel, so firstly I have to configure an environment ?

**Comment by mohantym** [comment]
@AntoineChauviere !
Please Check this [sample notebook ](https://colab.sandbox.google.com/gist/mohantym/0ccc54941f7f0c784cc0da5389e540b8/tensorflow-ranking.ipynb#scrollTo=du7ioHkASrt_)for bazel build process and let us know your results after your test.
Thank you!

**Comment by AntoineChauviere** [comment]
Ok @mohantym thank you for your help.

I followed the notebook. I'm on Mac OS When I run this command:

bazel build //tensorflow/tools/lib_package:libtensorflow --spawn_strategy=standalone --verbose_failures

I think everything is ok, I got : 

INFO: Analyzed target //tensorflow/tools/lib_package:libtensorflow (262 packages loaded, 21898 targets configured).
INFO: Found 1 target...
Target //tensorflow/tools/lib_package:libtensorflow up-to-date:
  bazel-bin/tensorflow/tools/lib_package/libtensorflow.tar.gz
INFO: Elapsed time: 8188.005s, Critical Path: 634.09s
INFO: 13955 processes: 2953 internal, 11002 local.
INFO: Build completed successfully, 13955 total actions

So, what is next steps in order to use flex delegate in emulator in flutter? 

Sorry if my questions seem silly, I'm more research oriented than integration.

**Comment by AntoineChauviere** [comment]
@mohantym  This produces a libtensorflow.tar.gz and I don't understand how I can use this in flutter...

**Comment by mohantym** [comment]
@AntoineChauviere !
Sorry for the inconvenience.

The Sample bazel notebook was just to walk you through bazel build processes (Sorry I did not add the exact command for building flex delegate)

`bazel build -c opt --config=android_arm tensorflow/lite/delegates/flex:tensorflowlite_flex`

The interpreter can take this delegate through interpeter option and load_delegate in python.
in C++ , usage is 
Don't know the counter part in flutter (check in official documentation on loading a delegate )

Alternative usages:

For android usage of select ops , Please follow [aar documentation.](https://www.tensorflow.org/lite/guide/ops_select#building_the_android_aar)

For IOS usage of select ops , Please check instructions from [here](https://www.tensorflow.org/lite/guide/ops_select#using_bazel_xcode).

@sachinprasadhs 
Could you look at this issue .

Thank you!

**Comment by AntoineChauviere** [comment]
@sachinprasadhs , @mohantym 

In fact, I would like to know if it is possible to select tf ops on emulator (x86_64) or is it impossible and I need a real device?

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
