### ISSUE TITLE
Feature proposal: bilinear upsampling transposed convolution initialization.

### ISSUE THREAD

**Issue by warmspringwinds** [tensorflow/tensorflow#5790]
Hello,

I have been recently [implementing the FCN-32 network for image segmentation](http://warmspringwinds.github.io/tensorflow/tf-slim/2016/11/22/upsampling-and-image-segmentation-with-tensorflow-and-tf-slim/)
and found out that there is no bilinear upsampling op in Tensorflow or TF-slim.
That would be great if there will be an op that will do that, because that will make it
possible to bilinearly upsample blobs in a differentiable way or initialize upsampling
filter with bilinear kernel.

I have already implemented that and checked correctness.
You can see more if you follow the link. 
If you are interested, I can make a pull request.

Thank you.

**Comment by prb12** [comment]
Feel free to submit a PR.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
