### ISSUE TITLE
why my 'workers=4,use_multiprocessing=True' do not work while training?

### ISSUE THREAD

**Issue by renguote** [tensorflow/tensorflow#57903]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf2.4

### Custom Code

Yes

### Python version

3.9

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import Sequence
from math import ceil
import numpy as np
import numpy as np
import math
import os

class DataGenerator(Sequence):
 
    def __init__(self, x_set, y_set, batch_size):
        self.x, self.y = x_set, y_set
        self.batch_size = batch_size

    def __len__(self):
        return ceil(len(self.x) / self.batch_size)

    def __getitem__(self, idx):
        end = min(self.x.shape[0], (idx + 1)*batch_size)
        return self.x[idx*batch_size:end], self.y[idx*batch_size:end]

batch_size = 32
epochs = 100

(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0
training_generator = DataGenerator(train_images, train_labels, batch_size)


model = models.Sequential()
model.add(layers.Conv2D(320, (3, 3), activation='relu', input_shape=(32, 32, 3)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10))

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

history = model.fit(x=training_generator,
                    steps_per_epoch=train_images.shape[0]//batch_size,
                    validation_data=(train_images, train_labels),
                    epochs=epochs,
                    verbose=1,
                    use_multiprocessing=True,
                    workers=4)
```

### Relevant log output

_No response_</details>

**Comment by renguote** [comment]
<img width="510" alt="1664421143346" src="https://user-images.githubusercontent.com/114635552/192931000-7952b58c-b69c-46da-99e8-3f74233c6e0a.png">

**Comment by renguote** [comment]
![image](https://user-images.githubusercontent.com/114635552/192931201-bcdb5284-ddbb-49be-be4f-84b25ae5bb6f.png)

**Comment by tilakrayal** [comment]
@renguote,
Tensorflow version 2.4 is not actively supported. Hence, kindly update to the latest stable version 2.10 and let us know if you are facing the same issue. Thank you!

**Comment by renguote** [comment]
Still the same issue  when I updated to tensorflow==2.10.0.  Looking forward to your reply, Thank you!

**Comment by tilakrayal** [comment]
@renguote,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by tilakrayal** [comment]
@renguote,
Could you please close this issue, since it is already being tracked there?  Thank you!
