### ISSUE TITLE
Missing ops on using movenet/singlepose/lightning model 

### ISSUE THREAD

**Issue by csn1800** [tensorflow/tensorflow#57907]
**System information**
- Linux (armv7l) with Mali G31 GPU
- TensorFlow installed from (source or binary): Source
- TensorFlow version (or github SHA if from source): 2.6.0

Following is the output on trying to run the movenet singlpose lightning model (FP16 - taken from TFHub) on the device:
```
ERROR: Following operations are not supported by GPU delegate: 
ARG_MAX: Operation is not supported. 
CAST: Not supported cast case
CONCATENATION: OP is supported, but tensor type/shape doesn't supported. 
DEQUANTIZE: 
FLOOR_DIV: OP is supported, but tensor type/shape doesn't supported. 
GATHER_ND: Operation is not supported. 
MUL: OP is supported, but tensor type/shape doesn't supported. 
PACK: OP is supported, but tensor type/shape doesn't supported. 
RESHAPE: OP is supported, but tensor type/shape doesn't supported. 
SUB: OP is supported, but tensor type/shape doesn't supported. 
UNPACK: Operation is not supported. 

97 operations will run on the GPU, and the remaining 200 operations will run on the CPU.
```

On trying to run FP32 model available from TF Hub, following is observed:
```
ERROR: Following operations are not supported by GPU delegate: 

ARG_MAX: Operation is not supported. 
CAST: Not supported cast case 
FLOOR_DIV: OP is supported, but tensor type/shape doesn't supported. 
GATHER_ND: Operation is not supported. 
MUL: OP is supported, but tensor type/shape doesn't supported. 
PACK: OP is supported, but tensor type/shape doesn't supported. 
RESHAPE: OP is supported, but tensor type/shape doesn't supported. 
SUB: OP is supported, but tensor type/shape doesn't supported. 
UNPACK: Operation is not supported. 

97 operations will run on the GPU, and the remaining 45 operations will run on the CPU.
```

**Standalone code to reproduce the issue** 
    Used `TfLiteGpuDelegateCreate `to create TF lite OpenGL delegate with default options and the model is built with `FlatBufferModel::BuildFromFile`.

 Able to run the model though there are missing ops. The model runs slower with single digit FPS. 
1. Could you please confirm if the aforementioned ops are not supported by TF lite?
2. Is it due to the use of OpenGL and/or Mali GPU, or it is unavailable for all backend/platforms?
3. In case if custom ops are to be implemented, are there any references (code segment/doc) you can suggest which implements ops using GPU with OpenGL backend?

**Comment by mohantym** [comment]
Hi @csn1800 !
Sorry for the late response.

In case , It does not find any supported ops for gpu delegate then it can fall back to other delegate like nnapi ,xnnpack then to cpu delegate.

Please refer below thread to set the above fall back policy.
Reference - [fallback policy](https://stackoverflow.com/a/69167553) , [benchmarking](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark#on-android)


Did you check in 2.9/2.10 version yet?

Thank you!

**Comment by csn1800** [comment]
@mohantym Thanks for the response. I understand that there is a fallback to CPU and hence the instructions are running on CPU instead of GPU. With the experiments I have tried with the same model on CPU and GPU, it is seen that the CPU only version has 25% less frame rate than that of GPU version. With more instructions running on GPU it should be able to get a latency improvement. So, could you please provide answers to specific questions:

1. Could you please confirm if the aforementioned ops are not supported by TF lite?
2. Is it due to the **use of OpenGL and/or Mali GPU**, or it is unavailable for all backend/platforms?
3. In case if custom ops are to be implemented, are there any references (code segment/doc) you can suggest which implements **custom ops using GPU with OpenGL backend**?

**Comment by mohantym** [comment]
@csn1800 !
Cast, GatherNd and Unpack are in [Select ops allow list](https://www.tensorflow.org/lite/guide/op_select_allowlist) . As per this thread, GPU acceleration does not work even if you follow the select ops syntax.

For Custom OP impementation, Please refer this [document](https://www.tensorflow.org/lite/guide/ops_custom) here.

Alternatively , You can fallback to XNNPack / NNAPi delegate. 


Thank you!

**Comment by csn1800** [comment]
Thanks @mohantym  for the clarifications.

> Cast, GatherNd and Unpack are in [Select ops allow list](https://www.tensorflow.org/lite/guide/op_select_allowlist) . GPU acceleration does not work even if you follow the select ops syntax
So, you mean to say these ops are not supported on all GPUs (and backends)? 

Could you please suggest a way to make these unsupported ops supported on GPUs (with OpenGL backend), if it is there? Will creating custom ops under custom_parsers.cc, inheriting the NodeShader and overriding the GenerateCode be helpful?

> Alternatively, You can check the performance on XNNPack / NNAPi delegates through [Benchmarking](https://www.tensorflow.org/lite/performance/measurement).

I assume NNAPI works only on Android platform, is that correct? Or is there a way to use NPU on Linux ARM platform?

The benchmark tool ([linux_arm](https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/release/lite/tools/nightly/latest/linux_arm_benchmark_model)) works for CPU (xnnpack, threads etc.) but not for GPU on Linux ARM platform. Still, is there a way to get benchmarking performed on Linux ARM Platform with Mali GPU?

**Comment by mohantym** [comment]
@sachinprasadhs !
Could you look at this query.
Thank you!

**Comment by csn1800** [comment]
@sachinprasadhs Could you please have a look at the above query?

**Comment by sachinprasadhs** [comment]
Yes, NNAPI is specific to android platform.
For details on delegates registering can be found in below code files.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/delegate.h
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/common.h
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/metal_delegate.h

**Comment by csn1800** [comment]
@sachinprasadhs Thank you for the response. Could you please also address the other question I had, quoting it below:

> Could you please suggest a way to make these unsupported ops supported on GPUs (with OpenGL backend), if it is there? Will creating custom ops under custom_parsers.cc, inheriting the NodeShader and overriding the GenerateCode be helpful?

**Comment by csn1800** [comment]
@impjdi / @sachinprasadhs could you please look into the above query?

**Comment by pjpratik** [comment]
Hi @csn1800 

As this [comment](https://github.com/tensorflow/tensorflow/issues/56795#issuecomment-1331259457) suggests, Movenet didn't support GPU and it's non-trivial to do it.

Can you try BlazePose as suggested [here](https://github.com/tensorflow/tensorflow/issues/56795#issuecomment-1327012814) and let us know if that works for your case?

Thanks.

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
