### ISSUE TITLE
Tensorflow Lite edgetpu compilation error: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.

### ISSUE THREAD

**Issue by Shubham-23Joshi** [tensorflow/tensorflow#57905]
Hello, I am having an issue when compiling an image segmentation (U-net) model to run it on edge TPU (Coral Board). 
The model is converted and quantized as .tflite.
Edgetpu compiler error:  Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.

I have inspected the model with Netron and I did not find any dynamic sized tensors nor control-flow ops. 
Kindly check the Netron image and see if I missed out anything? As per the Netron visualization, the model seems to have no dynamic tensors.
Is there anything else I can do to resolve this issue? Please help.

The updated code and netron image is pasted on stackoverflow: https://stackoverflow.com/questions/73874287/how-do-i-resolve-the-error-attempting-to-use-a-delegate-that-only-supports-stat
The model is based on the oxford_pets model: https://keras.io/examples/vision/oxford_pets_image_segmentation/
I have read some closed issues on the similar error and have tried several ways to resolve it but it didnt work. 

Here is the model summary:
![image](https://user-images.githubusercontent.com/103208562/192989304-d4afd320-471a-4340-a66c-be918ea3256e.png)
![image](https://user-images.githubusercontent.com/103208562/192989537-cd92562e-fa83-4827-851f-eca0a68225b4.png)
![image](https://user-images.githubusercontent.com/103208562/192989653-3292f75a-3f54-4cc3-aced-b3df2051edd2.png)
![image](https://user-images.githubusercontent.com/103208562/192989748-2206378a-9709-472b-9c04-c3b27bf520d1.png)
![image](https://user-images.githubusercontent.com/103208562/192989827-ce89f5b6-bc06-4572-897a-7459ea3d6f5d.png)
![image](https://user-images.githubusercontent.com/103208562/192989960-4bb84d2b-8218-4056-9606-c9918d0b2d10.png)
![image](https://user-images.githubusercontent.com/103208562/192990054-4a0fdb9f-5bfc-4314-9608-e0fd789cbb24.png)
![image](https://user-images.githubusercontent.com/103208562/192990151-4379e83c-7a26-4d17-8d54-13363dd5b683.png)

Kindly help me resolve the error. Thank you in advance.

**Comment by mohantym** [comment]
Hi @Shubham-23Joshi !
Can you add below line in TFlite conversion and let us know your inference results.
```
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
# Set the input and output tensors to uint8
converter.target_spec.supported_types = [tf.int8] # extra line missing
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
```
[
Reference. ](https://github.com/google-coral/edgetpu/issues/586#issuecomment-1119842063)

Thank you!

**Comment by Shubham-23Joshi** [comment]
Hallo @mohantym thanks for the tip. I have put in the line and converted the model. 
However, the error still prevails at the compilation time.

**Comment by Shubham-23Joshi** [comment]
And in the netron image, there is no quantization shown at the input, rather two quantization blocks in the output. Why is this? Could anyone help with this?

**Comment by sachinprasadhs** [comment]
Could you please refer the comment here https://github.com/google-coral/edgetpu/issues/453#issuecomment-939091903 to use `converter._experimental_new_quantizer = True`

**Comment by nassimus26** [comment]
I am getting the same issue, here's the colab code : https://colab.research.google.com/drive/1WKSgxQUSZp4Q5dHeq2HgJvjjVzxJUoqA?usp=sharing
