### ISSUE TITLE
representative_dataset error for TFlite converter quantization

### ISSUE THREAD

**Issue by ra9hur** [tensorflow/tensorflow#57904]
### 1. System information

- Colab environment
- Quantization of yolov5s weights
- Successfully generated tflite files with,
     - No quantization
     - Floating Point 16
     - Dynamic range (no representative_dataset option)
- Fails when representative_dataset option is provided
- 

### 2. Code
-# https://github.com/tensorflow/tensorflow/issues/30861
tf.executing_eagerly()

train = []
path = '/currdrive/road_hero/android_figurine/validate/'
for i in range(1, 11):
    filename = os.path.join(path, 'IMG_0501.jpg')
    im = cv2.imread(filename)
    im = im.astype(np.float32, copy=False)
    #input_image = im - mc.BGR_MEANS
    train.append(im)

train = tf.convert_to_tensor(np.array(train, dtype='float32'))
my_ds = tf.data.Dataset.from_tensor_slices((train)).batch(1)

def representative_data_gen():
    for input_value in my_ds.take(10):
        yield [input_value]

file_path = './yolov5s_saved_model'
tf_lite_converter = tf.lite.TFLiteConverter.from_saved_model(file_path, signature_keys=['serving_default'])

tf_lite_converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
tf_lite_converter._experimental_lower_tensor_list_ops = False

tf_lite_converter.optimizations = [tf.lite.Optimize.DEFAULT]
tf_lite_converter.representative_dataset = representative_data_gen

tflite_model = tf_lite_converter.convert()

TF_LITE_MODEL_FILE_NAME = "dynamic2.tflite"

with tf.io.gfile.GFile(TF_LITE_MODEL_FILE_NAME, 'wb') as f:
  f.write(tflite_model)

#### Option A: Reference colab notebooks

1)  Reference [TensorFlow Model Colab](https://colab.research.google.com/drive/12t4TOjMvWnFDyRi9A2xhXtg_b_ITamXn#scrollTo=EukHdiAM-Mt9)

2) Attaching the colab file for your reference.
[yolov5_quantize.zip](https://github.com/tensorflow/tensorflow/files/9671818/yolov5_quantize.zip)

3) Attaching the yolov5s weights used for conversion
[yolov5s.pt.zip](https://github.com/tensorflow/tensorflow/files/9672062/yolov5s.pt.zip)

### 3. Error Log

Importing a function (__inference_pruned_6862) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-23-7cfa8e603e42> in <module>
     41 tf_lite_converter.representative_dataset = representative_data_gen
     42 
---> 43 tflite_model = tf_lite_converter.convert()
     44 
     45 TF_LITE_MODEL_FILE_NAME = "dynamic2.tflite"

11 frames

/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/optimize/calibrator.py in _feed_tensors(self, dataset_gen, resize_input)
    127                                      signature_key)
    128           else:
--> 129             self._calibrator.Prepare([list(s.shape) for s in input_array])
    130         else:
    131           if signature_key is not None:

RuntimeError: tensorflow/lite/kernels/concatenation.cc:158 t->dims->data[d] != t0->dims->data[d] (189 != 40)Node number 123 (CONCATENATION) failed to prepare.

**Comment by mohantym** [comment]
Hi @ra9hur !
Could you also open the access to above colab notebook . 
Thank you!

**Comment by ra9hur** [comment]
Hi @mohantym , have given you the access, please check.

**Comment by mohantym** [comment]
Hi @ra9hur !
A Representative data set is normally used for integer quantization for deploying in integer only accelerated hardware like edge TPU.  For Dynamic range quantisation , Procedure is to go with default converter without using any optimization flag .

I suggest you to follow the syntax with [Post-training integer quantization ](https://www.tensorflow.org/lite/performance/post_training_integer_quant#convert_using_integer-only_quantization)to avoid any run time issues.

Thank you!

**Comment by ra9hur** [comment]
Hi @mohantym , thanks for the analysis.

I just chose "TPU" as runtime option in Colab, still get similar error. Need your help to verify, this is really not hardware related.

### error log

Importing a function (__inference_pruned_6862) with ops with unsaved custom gradients. Will likely fail if a gradient is requested.

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

[<ipython-input-10-69befe633109>](https://localhost:8080/#) in <module>
     41 tf_lite_converter.representative_dataset = representative_data_gen
     42 
---> 43 tflite_model = tf_lite_converter.convert()
     44 
     45 TF_LITE_MODEL_FILE_NAME = "dynamic2.tflite"

11 frames

[/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/optimize/calibrator.py](https://localhost:8080/#) in _feed_tensors(self, dataset_gen, resize_input)
    127                                      signature_key)
    128           else:
--> 129             self._calibrator.Prepare([list(s.shape) for s in input_array])
    130         else:
    131           if signature_key is not None:

RuntimeError: tensorflow/lite/kernels/concatenation.cc:158 t->dims->data[d] != t0->dims->data[d] (189 != 40)Node number 123 (CONCATENATION) failed to prepare.

**Comment by mohantym** [comment]
Hi @ra9hur !
Colab TPU and Edge TPU have different configuration. So It might be hardware specific.
Different behaviour has been seen for same code has been between two different architectures. 
(CPU and GPU, Linux and Windows etc.)
Can we mark this query as resolved then.

Thank you!

**Comment by ra9hur** [comment]
Hi @mohantym ,

I am stuck at the same step on two different problems. Does that mean that we cannot execute below steps in colab notebook at all in spite of using TPU run-time ?
1. Cannot we generate dynamic range quantization weights with representative_dataset ?
2. This is next step to point 1 above. Can we not generate int8 quantization weights ? even this would involve representative_dataset.

If you have seen issues closed with the reason that weights cannot be generated with representative_dataset using colab notebook, please close this issue. Also request you to enclose those issue ids as reference. That would serve as an info , if someone had sighted alternate ideas in the discussion trail.

**Comment by mohantym** [comment]
@sachinprasad!
Could you look at this issue.
Thank you!

**Comment by ra9hur** [comment]
@sachinprasad, - Any update on this issue ?

**Comment by pjpratik** [comment]
Hi @ra9hur 

The representative dataset seems to be incorrectly passed to the generator.

I have tested with 10 images with shape [640, 640, 3] and was able to succesfully convert it into the TFLite format.

```
num_samples = 10
image_shape = (640, 640, 3)

def representative_dataset_generator():
    for _ in range(num_samples):
        # Generate random image
        image = np.random.random_sample(image_shape)
        image = image.astype(np.float32

        # Reshape the image to match the model's input shape
        image = np.expand_dims(image, axis=0)

        yield [image]


file_path = './yolov5s_saved_model'
tf_lite_converter = tf.lite.TFLiteConverter.from_saved_model(file_path, signature_keys=['serving_default'])


tf_lite_converter.optimizations = [tf.lite.Optimize.DEFAULT]
tf_lite_converter.representative_dataset = representative_dataset_generator

tflite_model = tf_lite_converter.convert()

TF_LITE_MODEL_FILE_NAME = "dynamic2.tflite"

with tf.io.gfile.GFile(TF_LITE_MODEL_FILE_NAME, 'wb') as f:
  f.write(tflite_model)
```

Please find the gist [here](https://colab.research.google.com/gist/pjpratik/342eab1c1bf3aca09f8e80fb935efafb/57904.ipynb#scrollTo=EukHdiAM-Mt9).

Thanks.

**Comment by ra9hur** [comment]
@pjpratik , thanks for re-initiating. It has been a while since I have worked on this code. Will check and confirm.
