### ISSUE TITLE
How to hide: failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

### ISSUE THREAD

**Issue by angelcampoverde** [tensorflow/tensorflow#57916]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

3.10.0-1160.71.1.el7.x86_64

### Python version

3.10

### Current Behaviour?

```shell
I do not have a GPU and TF is showing me:

failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

how do I hide this message?
```

### Standalone code to reproduce the issue

```shell
It's not a issue with the code, I cannot give you anything standalone.
```

### Relevant log output

_No response_</details>

**Comment by angelcampoverde** [comment]
OK, I think I found the answer. I have no GPU, therefore I have to:

```bash
pip uninstall tensorflow
pip install     tensorflow-cpu
```
as described here:

https://www.tensorflow.org/install/pip

Cheers

**Comment by mohantym** [comment]
Hi @angelcampoverde !

Those are warnings on no GPU detection . You can hide them through below commmand.
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
#In detail:-
0 = all messages are logged (default behavior)
1 = INFO messages are not printed
2 = INFO and WARNING messages are not printed
3 = INFO, WARNING, and ERROR messages are not printed
```
