### ISSUE TITLE
How do I specify the device of an operator when I load the model using the C API?

### ISSUE THREAD

**Issue by MoFHeka** [tensorflow/tensorflow#57919]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

```shell
How do I specify the device of an operator when I load the model using the C API?
If I have an operator, especially a custom operator, that has both GPU and CPU versions, how do I specify which device it should run on?
I know it's easy to use tf.device, but I'm using the C API loaded SavedModel for model reasoning, so I can't call the Python API.
```

### Standalone code to reproduce the issue

```shell
Using C API load any savedmodel.
```

### Relevant log output

_No response_</details>

**Comment by MoFHeka** [comment]
hello？

**Comment by sachinprasadhs** [comment]
Apologies for the delayed response, if you are looking for the custom OP which has to perform on specific device like CPU, you need to register OP for CPU kernel only. You can refer the template [here](https://github.com/tensorflow/custom-op#template-overview) for reference. Thanks!
