### ISSUE TITLE
pre-trained yolov5s quantized: inference time is very high

### ISSUE THREAD

**Issue by ra9hur** [tensorflow/tensorflow#57913]
### 1. System information

- Colab environment
- Quantization of pre-trained yolov5s weights
- Successfully generated tflite files with,
     - No quantization
     - Floating Point 16 quantization
     - Dynamic range quantization (no representative_dataset option)
- Inference time using weights from dynamic range quantization is extremely high

### 2. Code

file_path = './yolov5s_saved_model'
tf_lite_converter = tf.lite.TFLiteConverter.from_saved_model(file_path, signature_keys=['serving_default'])

tf_lite_converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = tf_lite_converter.convert()

TF_LITE_MODEL_FILE_NAME = "dynamic1.tflite"

with tf.io.gfile.GFile(TF_LITE_MODEL_FILE_NAME, 'wb') as f:
  f.write(tflite_model)

#### Option A: attachments for reference

1)  Reference [TensorFlow Model Colab](https://colab.research.google.com/drive/12t4TOjMvWnFDyRi9A2xhXtg_b_ITamXn#scrollTo=EukHdiAM-Mt9)

2) Attaching the colab file for your reference.
[yolov5_quantize.zip](https://github.com/tensorflow/tensorflow/files/9671818/yolov5_quantize.zip)

3) Attaching the yolov5s weights used for conversion
[yolov5s.pt.zip](https://github.com/tensorflow/tensorflow/files/9672062/yolov5s.pt.zip)

4) Attaching a spreadsheet that shows inference time for noquant, fp16-quant, dynamic range quant (no representative_dataset option) for comparison.
[perf.xlsx](https://github.com/tensorflow/tensorflow/files/9679762/perf.xlsx)

### 3. Execution Log

NO errors. Please observe the inference time taken for each image.
For image 1/13,
- with fp16 quantization, inference time is 382.1ms
- with dynamic range quantization, inference time is 21853.0ms

This is true for CPU and GPU-enabled options.

FP16 quantization
detect: weights=['fp16.tflite'], source=data/images, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v6.2-178-g799e3d0 Python-3.7.14 torch-1.12.1+cu113 CUDA:0 (Tesla T4, 15110MiB)

Loading fp16.tflite for TensorFlow Lite inference...
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
image 1/13 /content/gdrive/MyDrive/yolov5/data/images/NYstreet.jpg: 640x640 2 persons, 4 cars, 1 motorcycle, 382.1ms
image 2/13 /content/gdrive/MyDrive/yolov5/data/images/NYstreet2.jpg: 640x640 3 persons, 6 cars, 292.1ms
image 3/13 /content/gdrive/MyDrive/yolov5/data/images/bus.jpg: 640x640 4 persons, 1 bus, 289.5ms
image 4/13 /content/gdrive/MyDrive/yolov5/data/images/fruits.png: 640x640 6 apples, 6 oranges, 289.7ms
image 5/13 /content/gdrive/MyDrive/yolov5/data/images/market.jpg: 640x640 3 persons, 1 handbag, 1 bowl, 1 banana, 1 dining table, 291.2ms
image 6/13 /content/gdrive/MyDrive/yolov5/data/images/market2.jpg: 640x640 7 persons, 3 handbags, 1 banana, 293.9ms
image 7/13 /content/gdrive/MyDrive/yolov5/data/images/scene1.png: 640x640 1 person, 1 car, 1 dog, 1 skateboard, 292.1ms
image 8/13 /content/gdrive/MyDrive/yolov5/data/images/scene2.jpg: 640x640 6 persons, 4 dogs, 1 handbag, 1 frisbee, 290.8ms
image 9/13 /content/gdrive/MyDrive/yolov5/data/images/scene3.jpg: 640x640 12 persons, 1 sports ball, 297.7ms
image 10/13 /content/gdrive/MyDrive/yolov5/data/images/tennis.jpg: 640x640 2 persons, 1 sports ball, 1 tennis racket, 289.6ms
image 11/13 /content/gdrive/MyDrive/yolov5/data/images/zidane.jpg: 640x640 2 persons, 2 ties, 287.2ms
image 12/13 /content/gdrive/MyDrive/yolov5/data/images/zoo1.jpg: 640x640 1 person, 1 bench, 1 elephant, 301.1ms
image 13/13 /content/gdrive/MyDrive/yolov5/data/images/zoo2.jpg: 640x640 4 persons, 1 giraffe, 288.4ms
Speed: 169.8ms pre-process, 298.9ms inference, 1.3ms NMS per image at shape (1, 3, 640, 640)

Dynamic range quantization
detect: weights=['dynamic1.tflite'], source=data/images, data=data/coco128.yaml, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False, vid_stride=1
YOLOv5 🚀 v6.2-178-g799e3d0 Python-3.7.14 torch-1.12.1+cu113 CUDA:0 (Tesla T4, 15110MiB)

Loading dynamic1.tflite for TensorFlow Lite inference...
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
image 1/13 /content/gdrive/MyDrive/yolov5/data/images/NYstreet.jpg: 640x640 2 persons, 4 cars, 1 motorcycle, 21853.0ms
image 2/13 /content/gdrive/MyDrive/yolov5/data/images/NYstreet2.jpg: 640x640 3 persons, 7 cars, 21944.4ms
image 3/13 /content/gdrive/MyDrive/yolov5/data/images/bus.jpg: 640x640 4 persons, 1 bus, 21801.1ms
image 4/13 /content/gdrive/MyDrive/yolov5/data/images/fruits.png: 640x640 6 apples, 5 oranges, 21895.5ms
image 5/13 /content/gdrive/MyDrive/yolov5/data/images/market.jpg: 640x640 3 persons, 1 handbag, 1 banana, 1 dining table, 22131.7ms
image 6/13 /content/gdrive/MyDrive/yolov5/data/images/market2.jpg: 640x640 7 persons, 3 handbags, 1 banana, 22004.5ms
image 7/13 /content/gdrive/MyDrive/yolov5/data/images/scene1.png: 640x640 1 person, 1 car, 1 dog, 1 skateboard, 21858.2ms
image 8/13 /content/gdrive/MyDrive/yolov5/data/images/scene2.jpg: 640x640 6 persons, 4 dogs, 1 handbag, 1 frisbee, 21810.9ms
image 9/13 /content/gdrive/MyDrive/yolov5/data/images/scene3.jpg: 640x640 12 persons, 1 sports ball, 21925.1ms
image 10/13 /content/gdrive/MyDrive/yolov5/data/images/tennis.jpg: 640x640 2 persons, 1 sports ball, 1 tennis racket, 21963.1ms
image 11/13 /content/gdrive/MyDrive/yolov5/data/images/zidane.jpg: 640x640 2 persons, 1 tie, 21960.4ms
image 12/13 /content/gdrive/MyDrive/yolov5/data/images/zoo1.jpg: 640x640 1 person, 1 bench, 1 elephant, 21673.8ms
image 13/13 /content/gdrive/MyDrive/yolov5/data/images/zoo2.jpg: 640x640 4 persons, 1 giraffe, 21861.5ms
Speed: 165.6ms pre-process, 21898.7ms inference, 1.3ms NMS per image at shape (1, 3, 640, 640)

**Comment by mohantym** [comment]
Ok @ra9hur !
Thanks for reporting this issue.

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by ra9hur** [comment]
@sachinprasadhs ,

Did you get a chance to look into this issue ?

**Comment by ra9hur** [comment]
@haozha111, any update please ?

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
