### ISSUE TITLE
TF board does not show keras metrics. 

### ISSUE THREAD

**Issue by baridfor3** [tensorflow/tensorflow#57920]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.10.1

### Custom Code

Yes

### Current Behaviour?

```shell
I use "self.add_metric(some value)" in customized keras layers and call these layers in customized train_step, but metrics do not appear on TF board. 

Actually, I remember it works in some old versions like 1.x or 2.1.
```

### Standalone code to reproduce the issue

```shell
class some_customized_keras_layers(tf.keras.layers.Layer):
    def call():
         self.add_metric(some value)
```

### Relevant log output

_No response_</details>

**Comment by baridfor3** [comment]
Not an elegant solution, but it works.

class iTensorBoard(tf.keras.callbacks.TensorBoard):
    def on_train_batch_end(self, batch, logs=None):
        with self._train_writer.as_default():
            step =self.model.optimizer.iterations.read_value()
            lr_schedule = getattr(self.model.optimizer, "lr", None)
            if isinstance(lr_schedule, tf.keras.optimizers.schedules.LearningRateSchedule):
                lr = lr_schedule(step)
            elif lr_schedule is not None:
                lr = lr_schedule
            if step % self.update_freq == 0:
                for m in self.model.metrics:
                    tf.summary.scalar(m.name, m.result(),step=step)
                for v,k in logs.items():
                    tf.summary.scalar(v, k,step=step)
            tf.summary.scalar("lr", lr,step=step)
        return super(iTensorBoard, self).on_train_batch_end(batch, logs=logs)

**Comment by baridfor3** [comment]
Not an elegant solution, but it woks.

class iTensorBoard(tf.keras.callbacks.TensorBoard):
    def on_train_batch_end(self, batch, logs=None):
        with self._train_writer.as_default():
            step =self.model.optimizer.iterations.read_value()
            lr_schedule = getattr(self.model.optimizer, "lr", None)
            if isinstance(lr_schedule, tf.keras.optimizers.schedules.LearningRateSchedule):
                lr = lr_schedule(step)
            elif lr_schedule is not None:
                lr = lr_schedule
            if step % self.update_freq == 0:
                for m in self.model.metrics:
                    tf.summary.scalar(m.name, m.result(),step=step)
                for v,k in logs.items():
                    tf.summary.scalar(v, k,step=step)
            tf.summary.scalar("lr", lr,step=step)
        return super(iTensorBoard, self).on_train_batch_end(batch, logs=logs)

**Comment by tilakrayal** [comment]
@baridfor3,
This issue is not related to tensorflow. Could you please post this issue on [tensorboard](https://github.com/tensorflow/tensorboard) repo. Thank you!
