### ISSUE TITLE
I am having a problem when adding new op in tensorflow

### ISSUE THREAD

**Issue by lixinyutfd** [tensorflow/tensorflow#5792]
I just followed the tutorial when trying to add a new op in tensorflow
I would like to add a new op with which the file name is: rec_conv.cc
The code is like:(Input an tensor and just output a string)
```
#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/shape_inference.h"
#include "tensorflow/core/framework/op_kernel.h"
using namespace tensorflow;
	
REGISTER_OP("RecConv")
    .Input("input: int32")
    .Output("output: string")
    .SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
      c->set_output(0, c->input(0));
      return Status::OK();
    });

class RecConvOp: public OpKernel{
 public:
	explicit RecConvOp(OpKernelConstruction* context): OpKernel(context){}

 void Compute(OpKernelContext* context) override {
	//const Tensor& input_tensor = context->input(0);
	Tensor* output_tensor = NULL;
	auto output = output_tensor->template scalar<string>();
	output() = "Output is Rec_conv layer";
 }
}
REGISTER_KERNEL_BUILDER(Name("RecConv").Device(DEVICE_CPU), RecConvOp);
```
-------------------------------------------------
The BUILD file is like:
```
load("//tensorflow:tensorflow.bzl", "tf_custom_op_library")

tf_custom_op_library(
    name = "rec_conv.so",
    srcs = ["rec_conv.cc"],
)
```
---------------------------------------------
However, when I run:
 bazel build -c opt //tensorflow/core/user_ops:rec_conv.so
Error occure like:
```
Server finished RPC without an explicit exit code

lixinyu@lixinyu-PC:~/tensorflow/tensorflow/tensorflow/core/user_ops$ bazel build -c opt //tensorflow/core/user_ops:rec_conv.so
...........
INFO: Found 1 target...
ERROR: /home/lixinyu/tensorflow/tensorflow/tensorflow/core/user_ops/BUILD:3:1: C++ compilation of rule '//tensorflow/core/user_ops:rec_conv.so' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-canonical-system-headers ... (remaining 57 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from tensorflow/core/user_ops/rec_conv.cc:3:0:
./tensorflow/core/framework/op_kernel.h:1097:7: error: expected initializer before 'registrar__body__1__object'
       registrar__body__##ctr##__object(                                 \
       ^
./tensorflow/core/framework/op_kernel.h:1093:3: note: in expansion of macro 'REGISTER_KERNEL_BUILDER_UNIQ'
   REGISTER_KERNEL_BUILDER_UNIQ(ctr, kernel_builder, __VA_ARGS__)
   ^
./tensorflow/core/framework/op_kernel.h:1090:3: note: in expansion of macro 'REGISTER_KERNEL_BUILDER_UNIQ_HELPER'
   REGISTER_KERNEL_BUILDER_UNIQ_HELPER(__COUNTER__, kernel_builder, __VA_ARGS__)
   ^
tensorflow/core/user_ops/rec_conv.cc:32:1: note: in expansion of macro 'REGISTER_KERNEL_BUILDER'
 REGISTER_KERNEL_BUILDER(Name("RecConv").Device(DEVICE_CPU), RecConvOp);
 ^
./tensorflow/core/framework/op_kernel.h:1104:30: error: expected unqualified-id before ')' token
                             });
                              ^
./tensorflow/core/framework/op_kernel.h:1093:3: note: in expansion of macro 'REGISTER_KERNEL_BUILDER_UNIQ'
   REGISTER_KERNEL_BUILDER_UNIQ(ctr, kernel_builder, __VA_ARGS__)
   ^
./tensorflow/core/framework/op_kernel.h:1090:3: note: in expansion of macro 'REGISTER_KERNEL_BUILDER_UNIQ_HELPER'
   REGISTER_KERNEL_BUILDER_UNIQ_HELPER(__COUNTER__, kernel_builder, __VA_ARGS__)
   ^
tensorflow/core/user_ops/rec_conv.cc:32:1: note: in expansion of macro 'REGISTER_KERNEL_BUILDER'
 REGISTER_KERNEL_BUILDER(Name("RecConv").Device(DEVICE_CPU), RecConvOp);
 ^
Target //tensorflow/core/user_ops:rec_conv.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 11.505s, Critical Path: 2.99s
lixinyu@lixinyu-PC:~/tensorflow/tensorflow/tensorflow/core/user_ops$ bazel build -c opt //tensorflow/core/user_ops:rec_conv.so
```
-----------------------------------------------------
Could anyone tell me what type of error it is like and how to debug it cuz I am wondering why there are so many warnings and error promped from the included header file

Thanks in advance

**Comment by prb12** [comment]
Are you missing a semicolon after your class definition?

**Comment by lixinyutfd** [comment]
Oh, god it is.
One more question, I did sucessfully build the op but when I am trying to use it in python,
it shows nothing to reference.
like:Traceback (most recent call last):
  File "new_op_test.py", line 3, in <module>
    zero_out_module = tf.load_op_library('zero_out.so')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: zero_out.so: cannot open shared object file: No such file or directory
Am I missing anymore step?

**Comment by lixinyutfd** [comment]
@prb12

**Comment by prb12** [comment]
@lixinyutfd You will need to make sure that the shared library is on your `LD_LIBRARY_PATH`

**Comment by lixinyutfd** [comment]
@prb12 
Thanks in advance;
I did resolve the problem by passing absolute path of zero_out.so to  tf.load_library()
I am not sure if it is the same problem wrt the LD_LIBRARY_PATH but if so I hope there will be a solution to solve it cuz it is a pain to write such length path in it.
Or I am so sorry that If your solution helps, I didnt quite get it when and how to set LD_LIBRARY_PATH for my self-defined library.

**Comment by prb12** [comment]
There is no standard mechanism for this.

Typically you would either (manually) install your custom ops library in a well-defined place and put that directory on your LD_LIBRARY_PATH, or add `.` to your path if you want to live dangerously.

I normally add the bazel-bin directory where I built the ops library to my path, 
e.g `export LD_LIBRARY_PATH=/path/to/tensorflow-tree/bazel-bin/tensorflow/core/user_ops`

I'm closing this issue now since the reported problem was just a typo.

**Comment by ayushiag17** [comment]
@lixinyutfd : Hey Do you know how to add a header file as a dependency while compiling your new op?
I am also creating a new op and I have a similar build file as yours:
load("//tensorflow:tensorflow.bzl", "tf_custom_op_library")

tf_custom_op_library(
    name = "rec_conv.so",
    srcs = ["rec_conv.cc"],
)

But I also have a "rec_conv.h" file which I am unable to include successfully in the build and Bazel is complaining. 
In case you have worked this out, can you help?

**Comment by mohan1914** [comment]
load("//tensorflow:tensorflow.bzl", "tf_custom_op_library")

tf_custom_op_library(
    name = "rec_conv.so",
    srcs = ["rec_conv.cc,rec_conv.h"],
)

> @lixinyutfd : Hey Do you know how to add a header file as a dependency while compiling your new op?
> I am also creating a new op and I have a similar build file as yours:
> 
> ```
> load("//tensorflow:tensorflow.bzl", "tf_custom_op_library")
> 
> tf_custom_op_library(
>     name = "rec_conv.so",
>     srcs = ["rec_conv.cc"],
> )
> ```
> 
> But I also have a "rec_conv.h" file which I am unable to include successfully in the build and Bazel is complaining.
> In case you have worked this out, can you help?
Add .h files in srcs. If you have gpu_srcs and the same .h file as srcs, you'll have to add it again in gpu_srcs
tf_custom_op_library(
    name = "rec_conv.so",
    srcs = ["rec_conv.cc,rec_conv.h"],
)
