### ISSUE TITLE
Broken `tensorflow/compiler/xla/mlir_hlo/CMakeLists.txt` after `stablehlo` move out of `mlir_hlo`

### ISSUE THREAD

**Issue by brnorris03** [tensorflow/tensorflow#57928]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.11.0 (commit 4247ad4d497157eeb526e6aeeb5ecd15503955aa)

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04.3 

### Python version

3.8

### Bazel version

not using bazel

### GCC/Compiler version

10.0

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### Current Behaviour?

```shell
The `tensorflow/compiler/xla/mlir_hlo/CMakeLists.txt` includes the `stablehlo` subdirectory and various includes from it, assuming it's local. Needs to be updated to reflect the move out `stablehlo` out of the `mlir_hlo` subtree.
```

### Standalone code to reproduce the issue

```shell
Building with cmake as part of llvm (this worked fine prior to the `stablehlo` move):

cmake -G Ninja ../llvm \
		-DLLVM_ENABLE_PROJECTS=mlir \
		-DLLVM_EXTERNAL_PROJECTS="mlir-hlo" \
		-DLLVM_EXTERNAL_MLIR_HLO_SOURCE_DIR=/path/to/tensorflow/tensorflow/compiler/xla/mlir_hlo \
		-DCMAKE_BUILD_TYPE=RelWithDebInfo \
		-DLLVM_ENABLE_ASSERTIONS=ON \
		-DLLVM_TARGETS_TO_BUILD="RISCV;X86" \
		-DMLIR_ENABLE_BINDINGS_PYTHON=ON \
		-DMHLO_ENABLE_BINDINGS_PYTHON=ON 
```
```


### Relevant log output

```shell
Using cmake to build `mlir-hlo` following the README:

CMake Error at <mypath>/tensorflow/tensorflow/compiler/xla/mlir_hlo/CMakeLists.txt:165 (add_subdirectory):
  add_subdirectory given source "stablehlo" which is not an existing
  directory.
```
```
</details>

**Comment by tilakrayal** [comment]
@brnorris03,
Could you please provide the complete error log which helps to analyse the issue. Thank you!

**Comment by brnorris03** [comment]
Cmake logs attached. Thanks!

[CMakeOutput.log](https://github.com/tensorflow/tensorflow/files/9697206/CMakeOutput.log)
[CMakeError.log](https://github.com/tensorflow/tensorflow/files/9697207/CMakeError.log)

**Comment by sachinprasadhs** [comment]
There are few changes made recently in the CMakesLists.txt, latest commit here https://github.com/tensorflow/tensorflow/commit/c21f137bc42450f10f7d04f9d263852827afd079 which is related to moving `mlir_hlo`. 
Also, check the commit history. Let us know if you still face an error in the nightly build. Thanks!

**Comment by brnorris03** [comment]
The specific problem has not been addressed, namely the `add_subdirectory(stablehlo)` line, given that there is no `stablehlo` subdirectory in `tensorflow/compiler/xla/mlir_hlo` (it is in the top-level `third_party` directory).

https://github.com/tensorflow/tensorflow/blob/4a1b6f1b37b992aa9c74683fb1f2af55832812c8/tensorflow/compiler/xla/mlir_hlo/CMakeLists.txt#L171

**Comment by sachinprasadhs** [comment]
Nice catch. 
@ddunl , I think we need to modify the `stablehlo` path from `third_party/tensorflow/compiler/xla/mlir_hlo/` to 
 `third_party/stablehlo/` in the [tensorflow/tensorflow/compiler/xla/mlir_hlo/CMakeLists.txt](https://github.com/tensorflow/tensorflow/blob/4a1b6f1b37b992aa9c74683fb1f2af55832812c8/tensorflow/compiler/xla/mlir_hlo/CMakeLists.txt#L171)

**Comment by ddunl** [comment]
Sorry about the long response time on this! Wondering if using the https://github.com/tensorflow/mlir-hlo in place of the tensorflow repo would solve your problem as it stablehlo at the root of the repo?

**Comment by brnorris03** [comment]
Yes, I have been using the standalone `mlir-hlo` repo, although it has its own CMake build issues (but easier for me to work around). I think if cmake support is not maintainable in the tensorflow tree, then it may be better to just remove it altogether.

**Comment by ddunl** [comment]
Looked into the build issues there and wondering if the CMake build issues you're referring to are related to https://github.com/tensorflow/mlir-hlo/issues/52. Let me know if things are fixed now by the commit I reference in that thread or if there are more build problems beyond what's described in that issue.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
