### ISSUE TITLE
Don't show correct formula 

### ISSUE THREAD

**Issue by jntdst** [tensorflow/tensorflow#57922]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

2.8

### Custom Code

No

### Current Behaviour?

```shell
A bug happened!

Definition:
$$ \mathcal{L}({y}, {s}) =

\sum_i y_i \cdot \log\left(\frac{exp(s_i)}{\sum_j exp(s_j)}\right) $$

https://www.tensorflow.org/ranking/api_docs/python/tfr/keras/losses/SoftmaxLoss
```

### Standalone code to reproduce the issue

```shell
A bug happened!

Definition:
$$ \mathcal{L}({y}, {s}) =

\sum_i y_i \cdot \log\left(\frac{exp(s_i)}{\sum_j exp(s_j)}\right) $$

https://www.tensorflow.org/ranking/api_docs/python/tfr/keras/losses/SoftmaxLoss
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@jntdst,
Could you please feel free to submit a PR for the requested change to be made. The formula mentioned on the document looks good. Pleas provide the changes to be made for the formula.
![image](https://user-images.githubusercontent.com/81610181/193534249-81c88b84-ad5f-4976-9473-2ae2c10f452f.png)

**Comment by gowthamkpr** [comment]
@jntdst I don't see any issue with the formula. Are you mentioning that it should be formatted? Thanks!!

**Comment by lukaskuhn-lku** [comment]
I fixed that in https://github.com/tensorflow/ranking/pull/335
