### ISSUE TITLE
Class GpuDelegateFactory missing in Tensorflow Lite Java

### ISSUE THREAD

**Issue by DorianRudolph** [tensorflow/tensorflow#57934]
It looks like the `GpuDelegateFactory` is missing in the latest version of tflite on Android.

When ipmorting with `org.tensorflow.lite.gpu.GpuDelegateFactory`, compilation fails with `Unresolved reference: GpuDelegateFactory`.

I have imported the following packages:

```
    implementation 'org.tensorflow:tensorflow-lite:2.10.0'
    implementation 'org.tensorflow:tensorflow-lite-api:2.10.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.10.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu-delegate-plugin:0.4.2'
    implementation 'org.tensorflow:tensorflow-lite-support:0.4.2'
```

But none of these seem to contain `GpuDelegateFactory`.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

No

### Current Behaviour?

```shell
It looks like the `GpuDelegateFactory` is missing in the latest version of tflite on Android.

When ipmorting with `org.tensorflow.lite.gpu.GpuDelegateFactory`, compilation fails with `Unresolved reference: GpuDelegateFactory`.

I have imported the following packages:


    implementation 'org.tensorflow:tensorflow-lite:2.10.0'
    implementation 'org.tensorflow:tensorflow-lite-api:2.10.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.10.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu-delegate-plugin:0.4.2'
    implementation 'org.tensorflow:tensorflow-lite-support:0.4.2'
```

But none of these seem to contain `GpuDelegateFactory`.
```


### Standalone code to reproduce the issue

```shell
import org.tensorflow.lite.gpu.GpuDelegateFactory
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @DorianRudolph !
Can you also add below dependencies and let us know.
```
 
    import org.tensorflow.lite.DelegateFactory 
    import org.tensorflow.lite.Delegate
```

[Ref.](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/java/src/main/java/org/tensorflow/lite/gpu/GpuDelegateFactory.java)
Thank you!

**Comment by OleksandrGrument** [comment]
Hi @mohantym . Looks like an issue in 2.10. I'm getting runtime exception with GpuDelegateFactory. Looks like it missing 
![image](https://user-images.githubusercontent.com/20426405/193759568-68eab6fe-3931-4e34-a6dd-2c65867b4ed2.png)

**Comment by mohantym** [comment]
Hi @DorianRudolph !
You forgot to import this line in above imports.
`import org.tensorflow.lite.DelegateFactory 
`

You can see from [here ](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/java/src/main/java/org/tensorflow/lite/gpu/GpuDelegateFactory.java)that GpuDelegateFactory extends the parent class Delegatefactory .

Thank you!

**Comment by DorianRudolph** [comment]
@mohantym importing DelegateFactory does not help. It really does seem like the class is just missing from the AAR, as @Erdemtsynduev points out.

**Comment by vkatz** [comment]
Any fix eta?

**Comment by dmitryfisko** [comment]
Add this line to your build.gradle:
`implementation 'org.tensorflow:tensorflow-lite-gpu-api:2.10.0'`

**Comment by dmitryfisko** [comment]
Developers of library forgotten to include transitive dependency to **tensorflow-lite-gpu-api** from **tensorflow-lite-gpu**

**Comment by OleksandrGrument** [comment]
> 

Thank you! Now it's working!

**Comment by Erdemtsynduev** [comment]
<img width="961" alt="image" src="https://user-images.githubusercontent.com/12883992/194769832-9d212e1b-3190-44b8-bca0-8ee91184cbc2.png">

@dmitryfisko Thank you.

**Comment by sachinprasadhs** [comment]
@DorianRudolph , If your issue is resolved by including implementation `'org.tensorflow:tensorflow-lite-gpu-api:2.10.0'` in your build.gradle file. Could you please close the issue. Thanks!

**Comment by dmitryfisko** [comment]
@sachinprasadhs I'm. guess, that the right solution is in adding transitive dependency from tensorflow-lite-gpu to tensorflow-lite-gpu-api. This is very unobvious, that the consumer of TensorFlow SDK must add an additional dependency.

**Comment by sachinprasadhs** [comment]
@dmitryfisko , Feel free to create a PR for the same, we would be happy to review it.

**Comment by MidhunAkash** [comment]
ERROR: R8: Missing class org.tensorflow.lite.gpu.GpuDelegateFactory$Options$GpuBackend (referenced from: void org.tensorflow.lite.gpu.GpuDelegate.<init>(org.tensorflow.lite.gpu.GpuDelegateFactory$Options))

**Comment by aduonggm** [comment]
Work for me 

 implementation 'org.tensorflow:tensorflow-lite-gpu-api:2.10.0'
