### ISSUE TITLE
Wrong result in `tf.experimental.numpy.floor_divide` and `tf.experimental.numpy.remainder` when divide 0 by 0

### ISSUE THREAD

**Issue by fuzzyswan** [tensorflow/tensorflow#57935]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.11.0-dev20221001

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Current Behaviour?

`tf.experimental.numpy.floor_divide(0, 0)` gives `-1` on CUDA (which is totally wrong), raises `InvalidArgumentError` on CPU. For reference, `np.floor_divide(0, 0)` gives `0`.

Similarly `np.remainder(0, 0)` gives `0`, `tf.experimental.numpy.remainder(0, 0)` also gives `0` on CUDA, but raises `InvalidArgumentError` on CPU.

I think 0/0 results should be `0` on both CPU and CUDA, which is consistent with numpy.

### Standalone code to reproduce the issue
For `floor_divide`: 
```shell
import tensorflow as tf
import numpy as np
x = np.arange(10)
y = np.arange(10) 
print(np.floor_divide(0, 0)) # 0
with tf.device("gpu"):
  print(tf.experimental.numpy.floor_divide(0, 0)) # -1
with tf.device("cpu"):
  print(tf.experimental.numpy.floor_divide(0, 0)) # InvalidArgumentError
```

### Relevant log output

```shell
0
tf.Tensor(-1, shape=(), dtype=int64)
InvalidArgumentError: {{function_node __wrapped__FloorDiv_device_/job:localhost/replica:0/task:0/device:CPU:0}} Integer division by zero [Op:FloorDiv]
```

For `remainder`:

### Code
```
import tensorflow as tf
import numpy as np
print(np.remainder(0, 0)) # 0
with tf.device("gpu"):
  print(tf.experimental.numpy.remainder(0, 0)) # 0
with tf.device("cpu"):
  print(tf.experimental.numpy.remainder(0, 0)) # InvalidArgumentError
```
### Outputs
```
0
tf.Tensor(0, shape=(), dtype=int64)
InvalidArgumentError: {{function_node __wrapped__FloorMod_device_/job:localhost/replica:0/task:0/device:CPU:0}} Integer division by zero [Op:FloorMod]
```
</details>

**Comment by tilakrayal** [comment]
@fuzzyswan,
This is an intended behavior and the same can also be seen in all cases mentioned below

Using math module

```
import math
math.floor(0/0)
```
output:

```
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
[<ipython-input-1-054651c01b6b>](https://localhost:8080/#) in <module>()
      1 import math
      2 
----> 3 math.floor(0/0)

ZeroDivisionError: division by zero
```
Using Python

`print('Floor value for 0/0:',0//0)`
Output:
```

---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
[<ipython-input-4-9fb0c9205c59>](https://localhost:8080/#) in <module>()
----> 1 print('Floor value for 0/0:',0//0)

ZeroDivisionError: integer division or modulo by zero
```
Using tf.math.floordiv

```
x=0
y=0
tf.math.floordiv( x, y, name=None)
```

Output:
```

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-12-e18cb5fc9e77> in <module>()
      3 y=0
      4 tf.math.floordiv(
----> 5     x, y, name=None
      6 )

1 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   7184 def raise_from_not_ok_status(e, name):
   7185   e.message += (" name: " + name if name is not None else "")
-> 7186   raise core._status_to_exception(e) from None  # pylint: disable=protected-access
   7187 
   7188 

InvalidArgumentError: Integer division by zero [Op:FloorDiv]
```

**Comment by fuzzyswan** [comment]
Hi @tilakrayal , I totally agree that an exception is the intended behavior for 0/0. However, the tf divide ops are not giving consistent results: `tf.experimental.numpy.floor_divide` gives **-1** for `0/0` on CUDA (**gives a wrong output without throwing any exceptions**), and `tf.experimental.numpy.remainder` gives `0`.

**Comment by tilakrayal** [comment]
@fuzzyswan,
We see that you're using a tf-nightly version(2.11dev) which is not stable. Could you please try with the stable version 2.10.0 and let us know if you are facing same issue. Thank you!

**Comment by fuzzyswan** [comment]
Hi, @tilakrayal , I checked and the issue also exists in TF2.10.0, thanks!

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.9, v2.10 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/2dcaf684d821d7eed479f954935a9530/untitled711.ipynb).

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
