### ISSUE TITLE
Incorrect Output in windows for few quant models in windows

### ISSUE THREAD

**Issue by bhpatray** [tensorflow/tensorflow#57943]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8.0

### Custom Code

No

### OS Platform and Distribution

Windows 10

### Python version

3.10

### Bazel version

4.2.2

### Current Behaviour?

```shell
A bug happened!
python output and Linux output were matching.
But windows output is different from Linux and producing incorrect results.
Attached the models producing incorrect results
```

### Standalone code to reproduce the issue

```shell
Run label image example for both models and get the output.
```

### Relevant log output

```shell
https://tfhub.dev/tensorflow/lite-model/ssd_mobilenet_v1/1/default/1


https://tfhub.dev/iree/lite-model/mobilenet_v2_100_224/uint8/1
```
</details>

**Comment by bhpatray** [comment]
Any update @tiruk007  @mohantym @tilakrayal

**Comment by tiruk007** [comment]
Hi @bhpatray 
Sorry for the late reply.  Try to resize the tensor according to the hub model and then allocate tensors then invoke to get the output. Could you please refer to this document ([resize_tensor_input](https://www.tensorflow.org/api_docs/python/tf/lite/Interpreter#resize_tensor_input))

Thank you!

**Comment by BhaskarsarmaP** [comment]
Hello, I tried with resized input only.
It seems windows library is producing incorrect results even for basic quant models.
For other OS , It is matching and proper.
This seems a critical bug.
Could you check and resolve ? @tilakrayal @tiruk007 @mohantym

**Comment by BhaskarsarmaP** [comment]
Generate TFLite C++ windows library and run the mentioned models They produce incorrect results .

when I generate TFlite C++ linux library , I was getting proper output

**Comment by bhpatray** [comment]
I followed the same steps and found incorrect results.
I got correct results in LINUX means I have done pre processing correct. 
Just check output using TFLite C++ windows library and compare with python and TFLite C++ linux library

**Comment by bhpatray** [comment]
Still Same issue even in latest 2.10.0
Any Update ?

**Comment by sachinprasadhs** [comment]
Need to investigate on this about why there is a difference in behavior from Linux to Windows. 
Could you please provide the sample reproducible code to investigate further. Thanks!

**Comment by sachinprasadhs** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
