### ISSUE TITLE
Extension file 'tensorflow/core/platform/default/rules_cc.bzl' has errors when install tflite-support-0.4.2 using Bazel 4.2.2

### ISSUE THREAD

**Issue by febrifahmi** [tensorflow/tensorflow#57947]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2

### Custom Code

No

### OS Platform and Distribution

Raspbian Buster

### Python version

3.7

### Bazel version

4.2.2

### Current Behaviour?

```shell
I tried to install tflite-support-0.4.2 using bazel on my Raspberry Pi (Raspbian Buster) since I can't install it directly using pip3. I expected that installing from bazel will result in complete installation of tflite-support. However when I try to build the package it gives me this error. I tried several time but the result is still the same.
 
`
ERROR: Traceback (most recent call last):
        File "/home/pi/.cache/bazel/_bazel_pi/e377461fba63f25ab8757a7080bd56fe/external/org_tensorflow/tensorflow/core/platform/default/rules_cc.bzl", line 6, column 28, in <toplevel>
                _cc_shared_library = native.cc_shared_library
Error: no native function or rule 'cc_shared_library'
ERROR: Analysis of target '//tensorflow_lite_support/tools/pip_package:build_pip_package' failed; build aborted: error loading package '@org_tensorflow//tensorflow': in /home/pi/.cache/bazel/_bazel_pi/e377461fba63f25ab8757a7080bd56fe/external/org_tensorflow/tensorflow/tensorflow.bzl: in /home/pi/.cache/bazel/_bazel_pi/e377461fba63f25ab8757a7080bd56fe/external/org_tensorflow/tensorflow/core/platform/rules_cc.bzl: Extension file 'tensorflow/core/platform/default/rules_cc.bzl' has errors`

The code in 'tensorflow/core/platform/default/rules_cc.bzl' is:

`"""Provides an indirection layer to bazel cc_rules"""

load(
    "//tensorflow/core/platform/default:rules_cc.bzl",
    _cc_binary = "cc_binary",
    _cc_import = "cc_import",
    _cc_library = "cc_library",
    _cc_shared_library = "cc_shared_library",
    _cc_test = "cc_test",
)

cc_binary = _cc_binary
cc_import = _cc_import
cc_library = _cc_library
cc_shared_library = _cc_shared_library
cc_test = _cc_test`
```

### Standalone code to reproduce the issue

```shell
I just use this command (no custom code):

`bazel build -c opt tensorflow_lite_support/tools/pip_package:build_pip_package` that I learned from https://github.com/tensorflow/tflite-support/issues/755

The command runs OK but eventually FAILED: Build did NOT complete successfully (7 packages loaded, 10 targets configured).

Thanks
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @febrifahmi !

Could you check the below command with Bazel 5.1.1 . 

`bazel build -c opt //tensorflow_lite_support/tools/pip_package:build_pip_package` .

Thank you!

**Comment by febrifahmi** [comment]
Unfortunately, I can't install Bazel 5.1.1 on my Raspberry Pi, as per information stated in [Bazel documentation page](https://bazel.build/install) installation on Raspberry Pi is using the latest [Bazel ARM version](https://github.com/koenvervloesem/bazel-on-arm/blob/master/README.md) supported by Bazel on arm package, which is now AFAIK only [support Bazel version 4.2.2](https://github.com/koenvervloesem/bazel-on-arm/blob/master/BAZEL_VERSION).

**Comment by febrifahmi** [comment]
I'm [unable to bootstrap Bazel 5.3.0](https://github.com/bazelbuild/bazel/issues/16416) from the source. I will try another workaround to install tflite-support.

**Comment by mohantym** [comment]
Hi @febrifahmi !
You can also install [tflite-runtime ](https://www.tensorflow.org/lite/guide/python)or check the wheel from[ pintoo.](https://github.com/PINTO0309/TensorflowLite-bin) for rasberry usage.
Thank you!

**Comment by febrifahmi** [comment]
Thanks.. I'll try it. But it seems the binary are only for armv7l while my pi is the old armv6l.

**Comment by mohantym** [comment]
@febrifahmi !
We are checking to see whether you still need help in this issue . There is also documentation on CMake through which you can cross compile with [tool chains](https://www.tensorflow.org/lite/guide/build_cmake_arm) (Including Armv7 and Armv6) different to host os. 

I suggest you to check these channels too ( CMake,Tflite-runtime,Pinto's wheel, TFlite-micro repo) to customize your builds.

Thank you!

**Comment by febrifahmi** [comment]
Still has no luck with the building process of tflite-support using Bazel or Bazel on Arm, and I think I will skip the CMake method since I don't want to download all Tensorflow src to my pi while I only need selected features of tflite-support/tflite-runtime. Also, I cannot install tflite-runtime using virtualenv with both Python 3.7 and Python 3.9, and unfortunately, I don't use microcontrollers in this research project.

**Comment by mohantym** [comment]
@febrifahmi !
Sorry for the inconvenience.

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by pjpratik** [comment]
Hi @febrifahmi

As this [comment](https://github.com/tensorflow/tflite-support/issues/882#issuecomment-1279854267) suggests, the PyPi wheels for tflite-support has been updated and the issue has been fixed.

Could you please try and let us know if you are still facing the issue?

Thanks.

**Comment by febrifahmi** [comment]
I think we can close this issue for now. 

Thanks.

**Comment by pjpratik** [comment]
Thanks for the confirmation. Please reopen if you'd like to work on this further.
