### ISSUE TITLE
https://stackoverflow.com/questions/73934844/issue-with-y-true-argument-that-in-passed-into-customloss-class-while-running

### ISSUE THREAD

**Issue by BhavyaShah1234** [tensorflow/tensorflow#57949]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

ALL

### Mobile device

ALL

### Python version

3.9

### Current Behaviour?

```shell
I expected the code to run flawlessly. But the y_true argument in call method of CustomLoss class gave tensor of shape (None, None, None, None).
```

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1TCE2UZ0buwesGbkh2dhlUEiMfLnR8F88?usp=sharing
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@BhavyaShah1234 Could you please provide the standalone code and other dependencies to replicate this issue?
Thank you!
