### ISSUE TITLE
tf.linalg.matrix_rank has different results with or without @tf.function

### ISSUE THREAD

**Issue by jiannanWang** [tensorflow/tensorflow#57959]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.4 LTS (x86_64)

### Python version

3.7.6

### CUDA/cuDNN version

N/A

### Current Behaviour?

```shell
tf.linalg.matrix_rank has different results with or without @tf.function
```

### Standalone code to reproduce the issue

```shell
# Colab Link: https://colab.research.google.com/drive/1x7GZDd9hyaBA0S6tnUT0QjKdRu0eSFiK?usp=sharing


import numpy as np
import tensorflow as tf

print(tf.__version__)

input = {'name': 'matrix_rank', 'a': np.array([[-7.24721292e+307,  4.66389010e+307, -5.40181227e+307,
         7.28793100e+307,  5.19885794e+307],
       [-5.74381106e+307,  2.21923437e+307,  4.96898538e+307,
         4.26402766e+307,  7.42174751e+307],
       [-2.62810171e+307,  1.71425915e+307, -6.99349881e+307,
        -8.11519519e+307,  4.04358640e+307],
       [-8.52726304e+307,  1.44214314e+307, -4.53927548e+307,
        -4.79571993e+307, -4.59672928e+307]])}

output1 = tf.linalg.matrix_rank(**input)
print(output1)

@tf.function
def fun_wrapper(x):
    return tf.linalg.matrix_rank(**x)

output2 = fun_wrapper(input)
print(output2)
```
```


### Relevant log output

```shell
2.10.0
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
```
</details>

**Comment by tilakrayal** [comment]
@jiannanWang,
**tf.function** -- Compiles a function into a callable TensorFlow graph. I tried to execute the code on tensorflow-gpu and the results are the same in both cases.  Kindly find the gist of it here and also please take a look at this official doc [link1](https://www.tensorflow.org/api_docs/python/tf/function) and [link2](https://www.tensorflow.org/guide/intro_to_graphs) for the reference. Thank you!

**Comment by jiannanWang** [comment]
Hi @tilakrayal ,

I didn't find your gist in your comment. Can you please send the link?

I provided a [gist](https://colab.research.google.com/drive/1x7GZDd9hyaBA0S6tnUT0QjKdRu0eSFiK?usp=sharing) in the reproduction code in case you miss it. I was using tf 2.10 with tensorflow-cpu. You can find inconsistencies in the two results, which may be caused by potential bugs.

**Comment by tilakrayal** [comment]
@jiannanWang,
Sorry for the delay. I tried to execute the code on tensorflow-gpu and the results are the same in both cases. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/76627395e7ec322a3c5b34bbe586c7fb/untitled660.ipynb).

**Comment by jiannanWang** [comment]
Hi @tilakrayal . The inconsistency was in tensorflow-cpu. After installing tensorflow-cpu 2.10.0 and executing the following code, the results will be 
```
2.10.0
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
```
. Comparing to the results from tensorflow-gpu, there might be a bug in tensorflow-cpu's graph mode.

**Comment by SuryanarayanaY** [comment]
Hi @jiannanWang ,

As per the [API](https://www.tensorflow.org/api_docs/python/tf/linalg/matrix_rank#args) document the input to `tf.linalg.matrix_rank()` should be Tensor.

Hence i converted the input used by you to tensor using `tf.convert_to_tensor()` and the result is same with or without @tf.function . Could you please refer the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/14b8a06fb26ba45c0f06c67495a8feb7/57959-nightly.ipynb).

Thankyou!
