### ISSUE TITLE
App attribute missing 

### ISSUE THREAD

**Issue by ShubhAgarwal-dev** [tensorflow/tensorflow#57962]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.7.6

### Current Behaviour?

```shell
File "resnet_main.py", line 18, in <module>
    FLAGS = tf.app.flags.FLAGSAttributeError: module 'tensorflow' has no attribute 'app'
```

### Standalone code to reproduce the issue

```shell
File "resnet_main.py", line 18, in <module>
    FLAGS = tf.app.flags.FLAGSAttributeError: module 'tensorflow' has no attribute 'app'
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @ShubhAgarwal-dev !
You can use Flags using compat.v1 mode using below command.

`tf.compat.v1.flags.FLAGS
`

[Reference](https://www.tensorflow.org/api_docs/python/tf/compat/v1/flags/FLAGS)

Thank you!
