### ISSUE TITLE
tf.nn.gelu raises an exception when 'features'.dtype is not a floating point tensor

### ISSUE THREAD

**Issue by Ingkarat** [tensorflow/tensorflow#57965]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

Yes

### Python version

3.9

### Current Behaviour?

```shell
tf.nn.gelu raises an exception when 'features'.dtype is not a floating point tensor. The documentation does not mention this requirement.
https://www.tensorflow.org/api_docs/python/tf/nn/gelu

A suggestion is to revise the docstring of 'features', or add a 'Raises' section to tf.nn.gelu documentation.
```
Issue[#54475](https://github.com/tensorflow/tensorflow/issues/54475) and PR[#54550](https://github.com/tensorflow/tensorflow/pull/54550) previously discussed about input types. A change was made in the code but not in the documentation.

### Standalone code to reproduce the issue

```shell
x = tf.constant([-3, -1, 0, 1, 3])
y = tf.nn.gelu(x)
```

### Relevant log output

```shell
ValueError: `features.dtype` must be a floating point tensor.Received:features.dtype=<dtype: 'int32'>
```
</details>

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to replicate the issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/a47ca6dc03fec6f90c676daf2033241a/57965.ipynb) here. Thank you!

**Comment by gadagashwini** [comment]
Hi @Ingkarat, Please take a look at this [link](https://github.com/tensorflow/tensorflow/blob/v2.10.0/tensorflow/python/ops/nn_ops.py#L3731-L3736). Thank you!

**Comment by Ingkarat** [comment]
Thank you @gadagashwini. Would it be better to mention this floating requirement in the documentation? maybe as part of `features`'s description?

**Comment by SuryanarayanaY** [comment]
Hi @Ingkarat ,

The document has been updated in Master branch.You may find it here.
https://github.com/tensorflow/tensorflow/blob/b1114184259910626a2c51802be9fd87eac1ad1c/tensorflow/python/ops/nn_ops.py#L3719-L3720

Also find the section Raises which is added in Master branch.

https://github.com/tensorflow/tensorflow/blob/b1114184259910626a2c51802be9fd87eac1ad1c/tensorflow/python/ops/nn_ops.py#L3728-L3729

The changes also may be reflected in tensorflow.org documentation with the next release. 

Thank you for the suggestion and hope this is as per your expectation.Please feel free to close the issue if it resolved the purpose of this issue. Thanks!
