### ISSUE TITLE
tensorflow.keras.layers has no attribute Normalization

### ISSUE THREAD

**Issue by Urkchar** [tensorflow/tensorflow#57963]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

source

### Tensorflow Version

2.10

### Custom Code

No

### OS Platform and Distribution

Microsoft Windows 10 Home ersion 10.0.19043 Build 19043

### Python version

3.9

### CUDA/cuDNN version

CUDA-11.2.2 cuDNN-8.1.0.77

### GPU model and memory

GeForce GTX 1070

### Current Behaviour?

```shell
Following along with this tutorial from the TensorFlow website. https://www.tensorflow.org/tutorials/load_data/csv

This tutorial references a preprocessing layer called Normalization from tensorflow.keras.layers. Does this layer not exist anymore? Was the layer renamed? Maybe the tutorial is outdated?
```

### Standalone code to reproduce the issue

```shell
from tensorflow.keras import layers
normalize = layers.Normalization()
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "c:\Users\urkch\AppData\Local\Programs\Python\Python_Projects\tensorflow\Load CSV data\abalone.py", line 39, in <module>
    normalize = layers.Normalization()
AttributeError: module 'tensorflow.keras.layers' has no attribute 'Normalization'
```
</details>

**Comment by tilakrayal** [comment]
@Urkchar,
I was able to execute the mentioned code without any issues on tensorflow v.2.10. Kindly find the gist of it here also `tf.keras.layers.Normalization` is an attribute in TensorFlow v2.6.0, so might not work on earlier versions: https://www.tensorflow.org/api_docs/python/tf/keras/layers/Normalization

**Comment by Urkchar** [comment]
The wrong Python interpreter was selected so TensorFlow 2.4.0 was running instead of 2.10.0. This issue may be closed.

**Comment by HasithaKutala** [comment]
hello @Urkchar how did you resolve can you please help me im facing this issue from 3 days

**Comment by Urkchar** [comment]
> hello @Urkchar how did you resolve can you please help me im facing this issue from 3 days

From what I recall from 2 years ago, the interpreter I was using was the wrong one. When I made an environment for that tutorial, I didn't switch to it. So the interpreter I was using had an older version of Tensorflow. For you, I would suggest double-checking that the interpreter you're using has the correct version of Tensorflow. Try running the following code to find this out. 
```
import tensorflow
tensorflow.version.VERSION
```
https://stackoverflow.com/questions/38549253/how-to-find-which-version-of-tensorflow-is-installed-in-my-system
Then compare this result with the version you are trying to use.

**Comment by HasithaKutala** [comment]
im suing latest version 

> > hello @Urkchar how did you resolve can you please help me im facing this issue from 3 days
> 
> From what I recall from 2 years ago, the interpreter I was using was the wrong one. When I made an environment for that tutorial, I didn't switch to it. So the interpreter I was using had an older version of Tensorflow. For you, I would suggest double-checking that the interpreter you're using has the correct version of Tensorflow. Try running the following code to find this out.
> 
> ```
> import tensorflow
> tensorflow.version.VERSION
> ```
> 
> https://stackoverflow.com/questions/38549253/how-to-find-which-version-of-tensorflow-is-installed-in-my-system Then compare this result with the version you are trying to use.

im using latest version of tf 2.16.0 and eveyrthing is upgraded and i dont know where im lacking this

**Comment by Urkchar** [comment]
> im suing latest version
> 
> > > hello @Urkchar how did you resolve can you please help me im facing this issue from 3 days
> > 
> > 
> > From what I recall from 2 years ago, the interpreter I was using was the wrong one. When I made an environment for that tutorial, I didn't switch to it. So the interpreter I was using had an older version of Tensorflow. For you, I would suggest double-checking that the interpreter you're using has the correct version of Tensorflow. Try running the following code to find this out.
> > ```
> > import tensorflow
> > tensorflow.version.VERSION
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://stackoverflow.com/questions/38549253/how-to-find-which-version-of-tensorflow-is-installed-in-my-system Then compare this result with the version you are trying to use.
> 
> im using latest version of tf 2.16.0 and eveyrthing is upgraded and i dont know where im lacking this

Did you run the following code in the environment you are trying to use?
```py
import tensorflow
tensorflow.version.VERSION
```
What was the result when you run this?
