### ISSUE TITLE
tf.signal.stft has different results with or without @tf.function

### ISSUE THREAD

**Issue by jiannanWang** [tensorflow/tensorflow#57960]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.4 LTS (x86_64)

### Python version

3.7.6

### CUDA/cuDNN version

N/A

### Current Behaviour?

```shell
tf.signal.stft has different results with or without @tf.function with the following input.
```

### Standalone code to reproduce the issue

```shell
# Colab Link: https://colab.research.google.com/drive/1WleKXby71iZXOL12r8nIN8B_jd2wJQks?usp=sharing


import tensorflow as tf
import numpy as np

print(tf.__version__)

input = {'fft_length': 46, 'frame_step': 19, 'frame_length': 0, 'signals': np.array([[[[-8.75314539e+307, -4.03838038e+307,  8.23775798e+307, -1.32627219e+307,  1.19815521e+307,  4.57117750e+307],
                                                                              [-4.74761327e+307, -4.71580522e+307, -5.88832102e+307, -6.48759076e+307, -4.36028464e+307, -4.77775171e+307],
                                                                              [ 1.20113701e+307, -7.60106094e+307,  7.22716917e+307, 2.17687950e+307, -5.25271143e+306,  5.41182394e+307]]]])}

output1 = tf.signal.stft(**input)

@tf.function
def fun_wrapper(x):
    return tf.signal.stft(**x)

output2 = fun_wrapper(input)

print(np.allclose(output1, output2))
```
```


### Relevant log output

```shell
2.10.0
False
```
</details>

**Comment by tilakrayal** [comment]
@jiannanWang,
I don't find any issue while executing the mentioned code. Could you please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/a771a80086b04dd1ff22a3d8c1bace45/untitled644.ipynb) and let me know if anything is missing here.

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.8, v2.10 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/1121da140f46936e419b7296a124c595/untitled661.ipynb).

**Comment by sachinprasadhs** [comment]
When we find out the difference between the both using` print(np.subtract(output1, output2))`.
The difference between two arrays is very small and it can be ignored as precision error.
