### ISSUE TITLE
tf.signal.inverse_stft has inconsistent results with or without @tf.function

### ISSUE THREAD

**Issue by jiannanWang** [tensorflow/tensorflow#57961]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.4 LTS (x86_64)

### Python version

3.7.6

### CUDA/cuDNN version

N/A

### Current Behaviour?

```shell
tf.signal.inverse_stft has inconsistent results with or without @tf.function for the following input
```

### Standalone code to reproduce the issue

```shell
# Colab Link: https://colab.research.google.com/drive/1MhNfkZgltqQqHw8kKG2zQi8ivwvKfRoj?usp=sharing


import tensorflow as tf
import numpy as np

print(tf.__version__)

input = {'frame_step': 29343, 'frame_length': 61, 'stfts': np.array([[]], dtype=np.complex64)}

output1 = tf.signal.inverse_stft(**input)

@tf.function
def fun_wrapper(x):
    return tf.signal.inverse_stft(**x)

output2 = fun_wrapper(input)

print(np.allclose(output1, output2))
```
```


### Relevant log output

```shell
2.10.0
False
```
</details>

**Comment by sushreebarsa** [comment]
@sachinprasadhs I was able to replicate the issue, please find the gist here. Thank you!

**Comment by sachinprasadhs** [comment]
Could you please refer the comment [here](https://github.com/tensorflow/tensorflow/issues/57960#issuecomment-1301418837). Thanks!
