### ISSUE TITLE
Undocumented explicit padding exceptions in tf.nn.max_pool and tf.nn.max_pool2d

### ISSUE THREAD

**Issue by Ingkarat** [tensorflow/tensorflow#57978]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

Yes

### OS Platform and Distribution

Microsoft Windows 11

### Python version

3.9

### Current Behaviour?

```shell
tf.nn.max_pool raises 2 exceptions that are not mentioned in the documentation.
https://www.tensorflow.org/api_docs/python/tf/nn/max_pool

1. For 'input' tensor of rank 5, explicit padding is not supported.
This requirement is likely to be inferred by most users but maybe a mention in `Raises` section might be useful for some.


2. NCHW_VECT_C is not supported with explicit padding.
This is also the case for tf.nn.max_pool1d and tf.nn.max_pool2d. NCHW_VECT_C is mentioned as a valid option in a 'data_format' docstring of tf.nn.max_pool2d.

For max_pool1d, the documentation is probably ok as it is because users are unlikely to set `data_format` to NCHW_VECT_C.

For max_pool and max_pool2d, a suggestion is to revise the docstring of 'data_format', or add this requirement in a 'Raises' section, or remove NCHW_VECT_C from the documentation if it is not allowed in general.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.python.ops import array_ops

x = array_ops.ones([2, 2, 2, 2, 2])
tf.nn.max_pool(x, ksize=2, strides=2, padding=[[0, 0], [1, 1], [1, 1], [0, 0]])
```

### Relevant log output

```shell
ValueError: Explicit padding is not supported with an input tensor of rank 5. Received: padding=[[0, 0], [1, 1], [1, 1], [0, 0]]
```

### Standalone code to reproduce the issue

```shell
# Modified from max_pool's API doc example
import tensorflow as tf
from tensorflow.python.ops import array_ops

matrix = tf.constant([
    [0, 0, 1, 7],
    [0, 2, 0, 0],
    [5, 2, 0, 0],
    [0, 0, 9, 8],
])
reshaped = tf.reshape(matrix, (1, 4, 4, 1))
result = tf.nn.max_pool2d(reshaped, ksize=2, strides=2, padding=[[0, 0], [1, 1], [1, 1], [0, 0]], data_format="NCHW_VECT_C")
```

### Relevant log output

```shell
ValueError: `data_format='NCHW_VECT_C'` is not supported with explicit padding. Received: padding=[[0, 0], [1, 1], [1, 1], [0, 0]]
```
</details>

**Comment by tilakrayal** [comment]
@Ingkarat,
We would prefer a PR for the validation, Could you please feel free to submit a PR for the requested change to be made. Thank you!

**Comment by Ingkarat** [comment]
Thank you @tilakrayal. I will create a PR.

**Comment by tilakrayal** [comment]
@Ingkarat,
Could you please raise the PR and provide the PR number for the reference. Thank you!

**Comment by Ingkarat** [comment]
@tilakrayal yes I will reference the PR number here when I have it.

**Comment by Ingkarat** [comment]
Hi @tilakrayal, I have crated a PR[#58039](https://github.com/tensorflow/tensorflow/pull/58039).

**Comment by tilakrayal** [comment]
@Ingkarat,
The PR has been assigned for reviewing and once it is merged this issue will move to closed status. Thank you!

**Comment by tilakrayal** [comment]
@Ingkarat,
The related PR #58039 was merged. Could you please take a look at the [comment](https://github.com/tensorflow/tensorflow/pull/58039#issuecomment-1276525361) from the developer and please feel free to move this issue to closed status. Thank you

**Comment by Ingkarat** [comment]
@tilakrayal  Thank you and apologize for missing the requested changes. Closing the issue.
