### ISSUE TITLE
Ram memory leak when using tf.function at tf 2.8,2.9 and 2.10, doesn't happen with tf 2.5

### ISSUE THREAD

**Issue by bgLeon** [tensorflow/tensorflow#57982]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.10

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu, also on Windows

### Python version

3.10 and 3.9

### Current Behaviour?

```shell
Every time I use a tf.function decorator there is a memory leak in the ram, that keeps growing every iteration, I observed this in ubuntu and windows, it didn't happen with tf 2.5 but I had the server updated to python 3.10 and all the version compatible with python 3.10 (tf 2.8,2.9,2.10) have this issue. 
I tried with python 3.9 in my personal device and the issue still occurs. The leak is small but in an RL setting this is a critical issue in RL since we have to call a tf.function to take actions in the environment millions of times during training and without the decorator things go like 10 times slower.

Note that it is not an issue about not passing tensorflow objects to the wrapper, neither about having the shape of the tensor changing.

Please I need this to be fixed as soon as possible.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

@tf.function
def operate(img):
    return img

img = tf.zeros((6,6,7))
for i in range (100000000):
    s= operate(img)
```

### Relevant log output

```shell
just monitor the ram, you will see it growing constantly if you are using tf>=2.8 with tf 2.5.0 ram remains constant for the code above
```
</details>

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.8, v2.10 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/19e9799e2d49389f3cd702c80fb8ca1d/untitled650.ipynb).

**Comment by bgLeon** [comment]
Any updates on this?

**Comment by bgLeon** [comment]
Hi @sampathrajapaksha the only solution I got is to have an script where I periodically save all training data, close everything and restart training. Sadly as you see here there has been no word about a proper fix yet.

**Comment by sampathrajapaksha** [comment]
@bgLeon Yes, that's one possible solution which I also thought about. I saw a few people have posted the same issue in StackOverflow and, unfortunately couldn't find any efficient solution yet

**Comment by tnybny** [comment]
reproducible with 2.11. Possible duplicate of https://github.com/tensorflow/tensorflow/issues/50765.

**Comment by chrisyeh96** [comment]
This issue seems to be fixed for me, as of TF 2.14

```python
import tensorflow as tf
import os, psutil
process = psutil.Process(os.getpid())


@tf.function
def operate(img):
    return img

img = tf.zeros((6,6,7))
rss = 0
for i in range (100000000):
    s= operate(img)
    new_rss = process.memory_info().rss
    if new_rss != rss:
        print(i, new_rss)
        rss = new_rss
```

output:
```
0 893091840
9961 893239296
149961 893251584
```

**Comment by sachinprasadhs** [comment]
@chrisyeh96 , Thanks for validating.

@bgLeon , Even I was able to see the constant memory when I ran your code, could you please verify and close the issue.

![image](https://github.com/tensorflow/tensorflow/assets/73069040/f6973607-369a-4221-b094-6578eecc23d6)

**Comment by bgLeon** [comment]
Wow it took a while, yes I tested with  TF 2.14 and I don't see the error anymore either, it's solved in this version
