### ISSUE TITLE
Another Check-fail in Conv2DBackpropFilter

### ISSUE THREAD

**Issue by shijy16** [tensorflow/tensorflow#57981]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10 and 2.11.0-dev20221005

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

CUDA 11.5

### Current Behaviour?

```shell
In current implementation of Conv2DBackpropFilter, arguments' shapes are not checked carefully. As a result, a check-fail can be triggered, which can lead to crash and DoS.
The bug is similar to #57980, but has different inputs and outputs. So they might have different causes.
```

### Standalone code to reproduce the issue

```shell
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '1'
import tensorflow as tf
print(tf.__version__)
with tf.device("GPU:0"):
    input = tf.random.uniform([1, 1, 1, 1, 1], dtype=tf.bfloat16)
    filter_sizes = tf.saturate_cast(tf.random.uniform([1], minval=-128, maxval=129, dtype=tf.int64), dtype=tf.int32)
    out_backprop = tf.random.uniform([1, 1, 1, 1], dtype=tf.bfloat16)
    strides = [1, 1, 1]
    use_cudnn_on_gpu = True
    padding = "SAME"
    explicit_paddings = []
    data_format = "NHWC"
    dilations = [1, 1, 1, 1]
    res = tf.raw_ops.Conv2DBackpropFilter(
        input=input,
        filter_sizes=filter_sizes,
        out_backprop=out_backprop,
        strides=strides,
        use_cudnn_on_gpu=use_cudnn_on_gpu,
        padding=padding,
        explicit_paddings=explicit_paddings,
        data_format=data_format,
        dilations=dilations,
    )
```

### Relevant log output

```shell
2022-10-05 16:56:46.002944: F ./tensorflow/core/util/tensor_format.h:427] Check failed: index >= 0 && index < num_total_dims Invalid index from the dimension: 3, 0, C
Aborted (core dumped)
```
</details>

**Comment by tilakrayal** [comment]
@shijy16,
PR #57984 was raised for the similar issue #57980. Could you please check and confirm that both issues are similar? Thank you!

**Comment by shijy16** [comment]
I'll check if this bug could be replicated after the PR has been merged.

**Comment by shijy16** [comment]
@tilakrayal The bug can still be replicated on 2.11.0-dev20221010

**Comment by tilakrayal** [comment]
@shijy16,
A similar issue #57980 was already raised and tracked for the PR. Could you please feel free to close this issue, so that we can track the issue there. Thank you!

**Comment by shijy16** [comment]
> @shijy16, A similar issue #57980 was already raised and tracked for the PR. Could you please feel free to close this issue, so that we can track the issue there. Thank you!

Okay.
If the bug can be replicated after PR #57984 was merged into master, I'll reopen this issue.
