### ISSUE TITLE
`tf.gather` outputs wrong result with jit_compile

### ISSUE THREAD

**Issue by MThalberg** [tensorflow/tensorflow#57999]
### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10, tf-nightly

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Current Behaviour?

According to documentation, `tf.gather` should return `0` when `indices` is out of bound on GPU. However, in the code below, the jit compiled function returns `0.2` instead of `0`.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
v = tf.constant([[0.1], [0.2]])
i = tf.constant([[3]])
def f(p):
    return tf.gather(v, indices=i, validate_indices=None, axis=None, batch_dims=0)

print(f(v)) # [[[0. ]]]
f_jitted = tf.function(jit_compile=True)(f)
print(f_jitted(v)) # [[[0.2]]]
```

### Relevant log output
```
tf.Tensor([[[0.]]], shape=(1, 1, 1), dtype=float32)
tf.Tensor([[[0.2]]], shape=(1, 1, 1), dtype=float32)
```

**Comment by tilakrayal** [comment]
@MThalberg,
Could you please provide the doc link where it was mentioned **tf.gather should return 0 when indices is out of bound on GPU**.
It helps to analyse the issue.



validate_indices | Deprecated, does nothing. Indices are always validated on CPU, never validated on GPU.
-- | --


Thank you!

**Comment by MThalberg** [comment]
Hi @tilakrayal, in the [documentation](https://www.tensorflow.org/api_docs/python/tf/gather), it says:

> Caution: On CPU, if an out of bound index is found, an error is raised. On GPU, if an out of bound index is found, a 0 is stored in the corresponding output value.

I can see `validate_indices` is deprecated, but I suppose it just means that indices are always validated on CPU, never validated on GPU, and the "caution" is still a valid statement, because it means "indices never validated on GPU"?

Anyway, I think it's good to make the behavior for OOB index consistent so that users can get the same results/behavior using XLA compilation or just eager computation.

**Comment by tilakrayal** [comment]
@MThalberg,
Could you please try to pass the int32 or int64 datatypes and let us know if you are facing same issue.



indices | The index Tensor. Must be one of the following types: int32, int64. The values must be in range [0, params.shape[axis]).
-- | --


axis | A Tensor. Must be one of the following types: int32, int64. The axis in params to gather indices from. Must be greater than or equal to batch_dims. Defaults to the first non-batch dimension. Supports negative indexes.
-- | --
batch_dims | An integer. The number of batch dimensions. Must be less than or equal to rank(indices).

Also please take a look at this official doc [link](https://www.tensorflow.org/api_docs/python/tf/gather) for the reference. Thank you!
