### ISSUE TITLE
is there any ways I can embed my self-implemented FP8 format (C/C++) into tensorflow, and support current ops automatically?

### ISSUE THREAD

**Issue by mexiQQ** [tensorflow/tensorflow#57990]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

2.10

### Custom Code

Yes

### Current Behaviour?

```shell
It looks like there is no way to include a self-implemented data format (eg. FP8) to support current ops automatically.
```

### Standalone code to reproduce the issue

```shell
It looks like there is no way to include a self-implemented data format (eg. FP8) to support current ops automatically.
```

### Relevant log output

_No response_</details>

**Comment by sachinprasadhs** [comment]
Could you please explain more about what you are trying to achieve so that we can help you with that.
If you are looking for OP registration, please take a loom into the document [here](https://www.tensorflow.org/guide/create_op#op_registration). Thanks!

**Comment by mexiQQ** [comment]
I would like to add a new number format FP8 (support cast, multiply, add, subtract, divide), and is there any interface to let current ops (e.g. batch_matmal, conv2d, max_pooling, ....)  can support this format automatically?

Example:
A = tensor (FP8) #support by uint8 with C++
B = tensor (FP8) #support by unit8 with C++
// cast, multiply, add, is also supported by my customized  fp8 library

C = batch_matmal(A, B) # can this op support two fp8 tensors automatically?

**Comment by sachinprasadhs** [comment]
Right now, we don't have option to support the formats automatically as explained above.
For any specific OP to support any type, it has to be registered in kernels to perform any operations.
