### ISSUE TITLE
No gradient defined for the Reverse op

### ISSUE THREAD

**Issue by dementrock** [tensorflow/tensorflow#58]

**Comment by dementrock** [comment]
This is simple to implement:

```python
@tf.ops.RegisterGradient("Reverse")
def _tf_reverse_grad(op, grad):
    reverse_dims = op.inputs[1]
    return tf.array_ops.reverse(grad, reverse_dims), None

**Comment by girving** [comment]
I do love ops which are their own gradients, or close to it (pack and unpack).

**Comment by martinwicke** [comment]
@dementrock Sorry this took me so long. Did you want to submit a fix yourself (you'd have to go through gerrit on tensorflow.googlesource.com) or should I add this?

**Comment by dementrock** [comment]
@martinwicke You should go ahead and add it. Seems too much trouble for me...

**Comment by martinwicke** [comment]
Will do.
