### ISSUE TITLE
transpose_op_test.py fails with rank 1 complex input on GPU

### ISSUE THREAD

**Issue by wenscarl** [tensorflow/tensorflow#58007]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf2.10

### Custom Code

Yes

### Current Behaviour?

```shell
Tests fails for cases(Same was observed for complex64).

def testComplex128(self):
  self._testBoth(np.array(1 + 2j).astype(np.complex128))
  self._testBoth((1 + 2j) * np.arange(0, 21).astype(np.complex128))
```
It's unclear if it's necessary to conjugate a rank-1 complex input with conjugate=True. Even if passing input to output is the default case, the imag part became 1.999023 instead of 2.0 which could also fail 
`assertAllEqual`.
```


### Standalone code to reproduce the issue

```shell
python tensorflow/python/kernel_tests/math_ops/transpose_op_test.py
```

### Relevant log output

```shell
not equal lhs = array(1.-2.j)
not equal rhs = array(1.+1.99902344j)
Mismatched elements: 1 / 1 (100%)
Max absolute difference: 3.99902344
Max relative difference: 1.78911649
 x: array(1.-2.j)
 y: array(1.+1.999023j)
```
</details>

**Comment by NeilGirdhar** [comment]
Did you mean to @ me?

**Comment by wenscarl** [comment]
> 

Yes. I saw the last relevant commit is[ Fix numpy 1.20 deprecation warning] (https://github.com/tensorflow/tensorflow/commit/8cf6c454f53aa49405f5cb82dfd9a1321f4d2e49).  But free to ignore or redirect to others.

**Comment by NeilGirdhar** [comment]
@wenscarl I'm unsure how my change affected things?

**Comment by wenscarl** [comment]
@NeilGirdhar I don't think it's that PR to blame. I will remove your name. There is a non-defined path for rank-1 complex tensor with conjugate required. Should be easy to fix but I am not sure what should be a reasonable behavior, doing a conjugate or treated as no-op?

**Comment by sachinprasadhs** [comment]
When I ran the tests internally, it all passed without any failure.
`../tensorflow/python/kernel_tests/math_ops:transpose_op_test_cpu PASSED in 301.3s`.
Anyways, will wait for the review of the above linked PR.

**Comment by cantonios** [comment]
From the above MR, this is a GPU kernel issue.  Please specify these details in the bug description - the test in question passes on CPU, but fails on GPU.
