### ISSUE TITLE
Using nested loss functions in graph-mode

### ISSUE THREAD

**Issue by michaelmontalbano** [tensorflow/tensorflow#58009]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.8

### Custom Code

Yes

### Python version

3.8

### Current Behaviour?

```shell
I have a custom loss function in the following form:

def outer_loss(lambda1, lambda2, lambda3):
    def inner_loss(y_true, y_pred):
        # compute loss in loop
        return tf.convert_to_tensor(loss)
    return inner_loss
```
While this syntax works while in eager execution, graphmode throws an error.

However, I need this function to be able to accept parameters (i.e. in outer_loss) so that I can complete a proper hyperparameter execution. Is it possible to write a loss function that accepts both the true and predicted tensor, in addition to multiple parameters, while in graph-mode?
```


### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

def MSE(lambda1, lambda2):
    def mse(y_true, y_pred):
        sq_diff = tf.pow(y_true-y_pred, lambda1)*lambda2
        return tf.reduce_mean(sq_diff)
model = keras.models.Sequential(
    [
        keras.layers.Conv2D(32, (3, 3), activation="relu", input_shape=input_shape),
        keras.layers.Conv2D(64, (3, 3), activation="relu"),
        keras.layers.MaxPooling2D((2, 2)),
        keras.layers.Flatten(),
        keras.layers.Dense(512, activation="relu"),
        keras.layers.Dense(10, activation="softmax"),
    ]
)
loss_f = MSE(lambda1=2, lambda2=3)
model.compile(loss=loss_f,optimizer=tf.keras.optimizers.Adam(0.01))

history = model.fit(x=x_train, y=y_train, epochs=10)
```

### Relevant log output
```
TypeError: To be compatible with tf.eager.defun, Python functions must return zero or more Tensors; in compilation of <function GBETA at 0x2af817ab4dc0>, found return value of type <class 'function'>, which is not a Tensor.
```

**Comment by tilakrayal** [comment]
@michaelmontalbano,
I was facing a different issue while executing the mentioned code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/923565caab7725dbf1078c122930276c/untitled654.ipynb) and share the required dependencies. Thank you!

**Comment by michaelmontalbano** [comment]
@tilakrayal I've updated the [colab](https://colab.research.google.com/gist/michaelmontalbano/f64048ccc5480fef4b89f6352875035b/untitled654.ipynb), but um, it's triggering a broadcastable shape error now. 

Do you know by chance if you are able to use nested functions as shown in the MSE() funct in the colab, while executing in graph_mode? Thanks.

**Comment by tilakrayal** [comment]
@michaelmontalbano,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
