### ISSUE TITLE
Making tensorflow.tile similar to numpy.tile and torch.tile

### ISSUE THREAD

**Issue by RickSanchezStoic** [tensorflow/tensorflow#58002]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

Yes

### Current Behaviour?

```shell
Running this code:
`tf.tile(tf.ones((3,)),(2,1))` will currently give an error for TensorFlow since the dimension length of the input and the multiples is different. Numpy and Pytorch handle this by modifying the dimension of the multiples or the input argument. I believe it would be nice if TensorFlow did this too.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
tf.tile(tf.ones((3,)),(2,1))
```

### Relevant log output

```shell
tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected multiples argument to be a vector of length 1 but got length 2 [Op:Tile]
```
</details>

**Comment by tilakrayal** [comment]
@RickSanchezStoic,
Could you please take a look at doc [link](https://www.tensorflow.org/api_docs/python/tf/tile) for tf.tile which supports **the operation creates a new tensor by replicating input multiples times** and confirm if you are looking for the similar feature. Thank you!

**Comment by RickSanchezStoic** [comment]
Yes, it has the condition `Length must be the same as the number of dimensions in input` which is not the case in `numpy` or `torch`. You can confirm this by running the standalone code provided.

**Comment by RickSanchezStoic** [comment]
any updates @sachinprasadhs ? btw can you explain the `stat:awaiting tensorflower` label :)

**Comment by cantonios** [comment]
`awaiting tensorflower` means they're waiting for a response from someone on the official TensorFlow team at Google to weigh in here (e.g. me).

Sure, I think this would be valuable.  Copy the `numpy.tile` behavior, and promote the two to be the same size by prepending 1s (either to `multiples` or the shape of the input). This is not a high priority for us, so if someone wants to try to tackle this, it would be a welcome contribution.

**Comment by saloni346** [comment]
Is this issue still open for contribution? I look forward to contributing to this issue as my first contribution to the Outreachy internship.

**Comment by cantonios** [comment]
> Is this issue still open for contribution? I look forward to contributing to this issue as my first contribution to the Outreachy internship.

Sounds great to me.  If you create a PR you can ping my username and I will review.

**Comment by raiyaan555** [comment]
Hey I think i Can work this out how do i contribute in this project??

**Comment by mohantym** [comment]
Hi @RickSanchezStoic !
We are checking to see whether you still need help in this issue .
I am able to get a numpy.tile like results using [tensorflow.experimental.numpy ](https://www.tensorflow.org/api_docs/python/tf/experimental/numpy) api

Attached [gist ](https://colab.sandbox.google.com/gist/mohantym/1a4a6ab3467a1a83bff1303a61aef682/git_58002.ipynb)for reference. 

Please let us know the results from your side.

Thank you!
