### ISSUE TITLE
AMD GPU's support for Tensorflow

### ISSUE THREAD

**Issue by ndeepesh** [tensorflow/tensorflow#58021]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux 16.04
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: NA
-   **TensorFlow installed from (source or binary)**: Source
-   **TensorFlow version (use command below)**: 2.4
-   **Python version**: 3.9
-   **Bazel version (if compiling from source)**: NA
-   **GCC/Compiler version (if compiling from source)**: NA
-   **CUDA/cuDNN version**:
-   **GPU model and memory**: AMD ROCm
-   **Exact command to reproduce**: NA

### Describe the problem
Does Tensorflow officially support AMD GPU's ROCm framework? If yes, is the support mature for production use cases at large scale?

**Comment by fsx950223** [comment]
Sure, you could take a look at https://www.amd.com/en/technologies/infinity-hub/tensorflow or https://hub.docker.com/r/rocm/tensorflow/

**Comment by bhack** [comment]
See also https://pypi.org/project/tensorflow-rocm/

**Comment by tilakrayal** [comment]
@ndeepesh,
Could you please take a look at this above [comment](https://github.com/tensorflow/tensorflow/issues/58021#issuecomment-1272276642) from the developer and also this doc [link1](https://rocmdocs.amd.com/en/latest/) and [link2](https://github.com/RadeonOpenCompute/ROCm-docker/blob/master/quick-start.md) which provides that AMD GPU's support for the Tensorflow. Thank you!

**Comment by ndeepesh** [comment]
Thanks everyone for the response and the pointers. I see that ROCm maintains a fork of Tensorflow library [here](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream). Wanted to understand if the official TF support is via the fork or is it from the primary github TF repository.

**Comment by ndeepesh** [comment]
Also are there plans to support TF Serving for ROCm?

**Comment by bhack** [comment]
The the repository is this one as can see with all the [ROCm PRs](https://github.com/tensorflow/tensorflow/pulls?q=is%3Apr+is%3Aopen+rocm) but ROCm binaries are community builds as you can see from the list at https://github.com/tensorflow/build/#community-supported-tensorflow-builds

**Comment by tilakrayal** [comment]
@ndeepesh,
Could you please take a look at this above [comment](https://github.com/tensorflow/tensorflow/issues/58021#issuecomment-1276347127) and let us if it answered the query. Thank you!
