### ISSUE TITLE
`tf.reverse_sequence` crash with abort when seq_axis is negative

### ISSUE THREAD

**Issue by MThalberg** [tensorflow/tensorflow#58027]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Current Behaviour?

```shell
`tf.reverse_sequence` crash with abort when seq_axis is negative
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

def f(input):
    seq_lengths = [7,2,3,5]
    seq_axis = -1
    batch_axis = 0
    return tf.reverse_sequence(input, seq_lengths, seq_axis=seq_axis, batch_axis=batch_axis)

f_jitted = tf.function(jit_compile=True)(f)
input=[[0]*8,[0]*8, [0]*8, [0]*8]
f_jitted(input)
# segfault
```

### Relevant log output

```shell
segmentation fault (core dumped)
```
</details>

**Comment by tilakrayal** [comment]
@MThalberg,
When we are using `tf.reverse_sequence`, the  **seq_axis** we should provide as an **int** and the dimension which is partially reversed and this op first slices input along the dimension batch_axis, and for each slice i, reverses the first seq_lengths[i] elements along the dimension **seq_axis**.

**Comment by MThalberg** [comment]
Hi @tilakrayal, the `seq_axis` is `-1` in the code example. Here, the negative integer value cause crash. This could potentially be used for DoS attack.

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.8, v2.10 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/6288232a905d45a1ca23b9d3556a2ae3/untitled677.ipynb).

**Comment by sachinprasadhs** [comment]
Negative value in the `seq_axis` is handled in the code and it returns the InvalidArgument Error, below is the code and the output for that.
```
import tensorflow as tf
seq_lengths = [7, 2, 3, 5]
input = [[1, 2, 3, 4, 5, 0, 0, 0], [1, 2, 0, 0, 0, 0, 0, 0],
         [1, 2, 3, 4, 0, 0, 0, 0], [1, 2, 3, 4, 5, 6, 7, 8]]
output = tf.reverse_sequence(input, seq_lengths, seq_axis=-1, batch_axis=0)
print(output)
```

`InvalidArgumentError: Invalid seq_dim -1 [Op:ReverseSequence]`
