### ISSUE TITLE
tf.experimental.numpy.argmax/argmin crash with xla with complex input

### ISSUE THREAD

**Issue by MThalberg** [tensorflow/tensorflow#58028]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10, tf-nightly

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Current Behaviour?

```shell
tf.experimental.numpy.argmax/argmin crash with xla with complex input
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

def f(x):
    return tf.experimental.numpy.argmax(x)

f_jitted = tf.function(jit_compile=True)(f)
a = tf.complex([0.],[2.])
f_jitted(a)
```

### Relevant log output

```shell
F tensorflow/compiler/xla/literal_util.cc:200] No min value for given type.  
abort (core dumped)
```
</details>

**Comment by sushreebarsa** [comment]
@MThalberg I tried to replicate the issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/ee428a375b99ee01773ba9b8a9cc1d1c/58028.ipynb) here and confirm the same. Thank you!

**Comment by MThalberg** [comment]
@sushreebarsa yes, thanks for reproducing!

**Comment by sushreebarsa** [comment]
@MThalberg I tried to execute the provided code in tf-nightly, and colab is not crashing now.
I got the different error as follows, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/90e6d9be8d94b61b84e21ccbd5c32a04/58028.ipynb#scrollTo=kh8Rcq4F_wte) and confirm the same?
```
TypeError: Value passed to parameter 'input' has DataType complex64 not in list of allowed values: float32, float64, int32, uint8, int16, int8, int64, bfloat16, uint16, float16, uint32, uint64, qint8, quint8, qint32, qint16, quint16, bool
```
Thank you!
