### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by EwoutH** [tensorflow/tensorflow#58032]
Currently Python 3.11 isn't fully supported in TensorFlow yet, including testing in CI and publishing wheels to PyPI.

Python 3.11 is currently in Release Candidate state and will be released in about two weeks. Major packages like NumPy, Pandas, SciPy and Matplotlib have already uploaded their Python 3.11 wheels to PyPI. 

Python 3.11 new features include:

> - [PEP 657](https://www.python.org/dev/peps/pep-0657/) -- Include Fine-Grained Error Locations in Tracebacks
> - [PEP 654](https://www.python.org/dev/peps/pep-0654/) -- Exception Groups and except*
> - [PEP 673](https://www.python.org/dev/peps/pep-0673/) -- Self Type
> - [PEP 646](https://www.python.org/dev/peps/pep-0646/)-- Variadic Generics
> - [PEP 680](https://www.python.org/dev/peps/pep-0680/)-- tomllib: Support for Parsing TOML in the Standard Library
> - [PEP 675](https://www.python.org/dev/peps/pep-0675/)-- Arbitrary Literal String Type
> - [PEP 655](https://www.python.org/dev/peps/pep-0655/)-- Marking individual TypedDict items as required or potentially-missing
> - [bpo-46752](https://bugs.python.org/issue46752)-- Introduce task groups to asyncio
> - The [Faster Cpython Project](https://github.com/faster-cpython) is already yielding some exciting results: this version of CPython 3.11 is ~ 19% faster on the geometric mean of the [PyPerformance benchmarks](https://speed.python.org/), compared to 3.10.0.

TensorFlow is an import package in the deep learning stack, so support at release will help speed up Python 3.11 adoption.

It would be great to have full Python 3.11 support in TensorFlow by the time Python 3.11.0 gets released, ([expected](https://peps.python.org/pep-0664/) Monday October 6th, 2022). This includes testing in CI and publishing wheels to PyPI.

This issue can be used as a tracking issue. This includes:

- [ ] TensorFlow builds fully on Python 3.11
- [x] All TensorFlow tests pass on Python 3.11
- [ ] All CI is run and green on Python 3.11
- [ ] Wheels are uploaded to PyPI for [tf-nightly](https://pypi.org/project/tf-nightly/#files)
  - [x] Linux
  - [x] macOS
  - [ ] Windows
- [ ] Wheels are uploaded to PyPI for at least one TensorFlow release

**Comment by MartinNowak** [comment]
I guess from the past approach it might only get supported with the next release tf-2.11.
Also depending on support in depdencies.
[Python3.8 support · Issue #33374 · tensorflow/tensorflow](https://github.com/tensorflow/tensorflow/issues/33374)
[Support Python 3.9 · Issue #44485 · tensorflow/tensorflow](https://github.com/tensorflow/tensorflow/issues/44485)
[Building from source failed on Python 3.10 · Issue #51776 · tensorflow/tensorflow](https://github.com/tensorflow/tensorflow/issues/51776#issuecomment-934569048)

Maybe worthwhile to coordinate with TF releases and upstream dependencies early on before next October.
[PEP 693 – Python 3.12 Release Schedule | peps.python.org](https://peps.python.org/pep-0693/)
Would certainly help to swiftly adopt new Python versions.

**Comment by mihaimaruseac** [comment]
See also #57805 (not closing as duplicate, since this one has more relevant content, thank you both for the comments here)

**Comment by njzjz** [comment]
Python 3.11 is released today.

**Comment by johnnynunez** [comment]
Yeah! Python 3.11 support please. It should be the default.
Python 3.11 is between 10-60% faster than Python 3.10. On average, we measured a 1.25x speedup on the standard benchmark suite. See Faster CPython for details.
https://docs.python.org/3.11/whatsnew/3.11.html
https://www.phoronix.com/news/Python-3.11-Released

**Comment by mihaimaruseac** [comment]
We still need for all of our dependencies to have a release on Py3.11.

And, unfortunately, we already cut the branch for the next TF release, so we won't be able to have a TF release with py3.11 support until TF 2.12 (though nightly should get support faster, before branch cut)

**Comment by johnnynunez** [comment]
Benchmark https://www.phoronix.com/review/python-311-performance

**Comment by NewUserHa** [comment]
since https://github.com/tensorflow/tensorflow/pull/58345, Could `tf-nightly` support 3.11 ASAP first?

**Comment by mihaimaruseac** [comment]
The infra team needs to create jobs for the nightly jobs. CC @learning-to-play @angerson @nitins17

**Comment by j-dominguez9** [comment]
Please?

**Comment by reza-ghazi** [comment]
Today is November 27, 2022, and Tensorflow is still not supporting Python 3.11.

**Comment by Liso7150** [comment]
How work proceses for now?

**Comment by learning-to-play** [comment]
Thank you for reaching out! TensorFlow next release will be in Q1 2023.

**Comment by yingjunzou** [comment]
Today is December 3, 2022, and Tensorflow is still not supporting Python 3.11.

**Comment by MinCarve** [comment]
Today is December 4, 2022, and Tensorflow is still not supporting Python 3.11.

**Comment by mihaimaruseac** [comment]
Folks, please stop spamming. `tf-nightly` support will arrive first and then TF 2.12 will have support for Python 3.11

**Comment by bhack** [comment]
And something is already landing on master:

https://github.com/tensorflow/tensorflow/commit/36d86747b159026be77a5eda1e0aff1292b88493

**Comment by mihaimaruseac** [comment]
Update: https://github.com/tensorflow/tensorflow/commit/3de3b132f6d8fdc6d982df9542eff840a6d0e89f adds more support. Next is the build jobs themselves.

**Comment by mihaimaruseac** [comment]
Linux and MacOS wheels now exist in `tf-nightly`: https://pypi.org/project/tf-nightly/#files

**Comment by johnnynunez** [comment]
thanks @mihaimaruseac

**Comment by johnnynunez** [comment]
> @learning-to-play Could you re-open this issue? While great progress is being made, this issue is far from fully resolved (see the tracker above).

@EwoutH I think that python 3.11 compatible will be released with tensorflow 1.12. So install nightly version and be patient

**Comment by EwoutH** [comment]
> @EwoutH I think that python 3.11 compatible will be released with tensorflow 1.12. So install nightly version and be patient

This is my first comment since I opened this discussion on October 10th, I think I'm quite patient. I just would like to keep track of the progress, so everyone looking for Python 3.11 support can exactly see in the checklist above where we stand, what's already available (macOS and Ubuntu nightly wheels) and what's not (Windows wheel and a stable release).

**Comment by jdcrunchman** [comment]
Am I good to go in installing Tensor Flow on my Python 3.11

**Comment by tux-o-matic** [comment]
@jdcrunchman , for one thing, no hardware accelerated training since Apple's last "sort of working" TF release (`tensorflow-macos`) is stuck on 2.9.
So you'll have to wait for a `tensorflow-cpu` release working on Python 3.11 which might be faster thanks to the faster CPython effort on 3.11 but will purely run on the CPU cores of your M1 Mac.

**Comment by johnnynunez** [comment]
Python 3.11 is out in anaconda https://github.com/ContinuumIO/anaconda-issues/issues/13082

**Comment by MarcBresson** [comment]
Hello, any idea of a potential release date ?

**Comment by johnnynunez** [comment]
> Hello, any idea of a potential release date ?

I think when cudnn new release for cuda 12.0

**Comment by jdcrunchman** [comment]
I have python 3.11. A week ago I couldn’t install it using condo. It’s got a bit of David do you support 3.11?Sent from my iPadOn Jan 27, 2023, at 2:44 AM, Johnny ***@***.***> wrote:﻿

Hello, any idea of a potential release date ?

I think when cudnn new release for cuda 12.0

**Comment by johnnynunez** [comment]
> Hey, do you have any idea when TF will be compatible with python 3.11 ? Thank you !

but not with cuda 11.8/12 and cudnn 8.8... :(

**Comment by johnnynunez** [comment]
> Seems that TF [v2.12](https://github.com/tensorflow/tensorflow/releases/tag/v2.12.0-rc0) (currently pre-release) is compatible with Python 3.11.

but not with cuda 11.8/12 and cudnn 8.8... :(

**Comment by johnthagen** [comment]
[Tensorflow `2.12.0rc1` has been released to PyPI with 3.11 wheels](https://pypi.org/project/tensorflow/2.12.0rc1/#files)

**Comment by wqp89324** [comment]
> [Tensorflow `2.12.0rc1` has been released to PyPI with 3.11 wheels](https://pypi.org/project/tensorflow/2.12.0rc1/#files)

Have you tried installing? When I try installing 2.12.0rc1 with poetry with python 3.11, I get incompatibility errors.

**Comment by cclauss** [comment]
Can this issue be closed?  https://github.com/tensorflow/tensorflow/releases

**Comment by mihaimaruseac** [comment]
You're right. Now TF supports Py 3.11

**Comment by johnthagen** [comment]
>@mihaimaruseac You're right. Now TF supports Py 3.11

And also except for `tflite-runtime`

- #60115
- #60182

**Comment by baslia** [comment]
> > @mihaimaruseac You're right. Now TF supports Py 3.11
> 
> [except for macOS arm64](https://github.com/tensorflow/tensorflow/issues/60209) (M1)

Is tensorflow working with python 3.11 on the M1 macs ?
Thanks

**Comment by johnthagen** [comment]
`tflite-runtime-nightly` Python 3.11 wheels are available as of

- [`2.14.0.dev20230612`](https://pypi.org/project/tflite-runtime-nightly/2.14.0.dev20230612/#files)
