### ISSUE TITLE
tf.keras.metrics.CategoricalAccuracy crash with xla on cuda when dtype is set to complex

### ISSUE THREAD

**Issue by MThalberg** [tensorflow/tensorflow#58030]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Current Behaviour?

```shell
tf.keras.metrics.CategoricalAccuracy crash with xla on cuda when dtype is set to copmlex
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
CategoricalAccuracy_class = tf.keras.metrics.CategoricalAccuracy(dtype=tf.complex64)

@tf.function(jit_compile=True)
def f(x0, x1, x2):
    return CategoricalAccuracy_class(x0, x1, x2)
x0 = [[0,0,1],[0,1,0]]
x1 = [[0.1, 0.1, 0.8], [0.05, 0, 0.95]]
x2 = [[0.5], [0.2]]
f(x0, x1, x2)
```

### Relevant log output

```shell
F tensorflow/compiler/xla/literal_util.cc:200] No min value for given type. 
 abort (core dumped)
```
</details>

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.10 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/90d2e4cdda71ef50e1471d6436097e59/untitled655.ipynb).

**Comment by cheshire** [comment]
@MThalberg what is the expected comparison semantics for complex numbers?

@smit-hinsu either way, seems like a bridge issue?

**Comment by smit-hinsu** [comment]
Comparison is undefined for complex types so CategoricalAccuracy doesn't make sense for it. Later TensorFlow versions will remove support for complex types to avoid this crash and have an explicit failure.
