### ISSUE TITLE
[TFLite] Slice-Conv2d Crash

### ISSUE THREAD

**Issue by ganler** [tensorflow/tensorflow#58035]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf-nightly

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Current Behaviour?

Running the following model compiled by `tflite` will crash given `rlim` is `2**31`, but it works perfectly in other settings including TF eager mode. Given that the model is valid and deployable, I think it is worth fixing to make tensorflow lite more secure.

```python
class Model(tf.Module):
    @tf.function
    def __call__(self, x, rlim):
        return tf.raw_ops.Conv2D(
            # `rlim` > index_max means `min(index_max, rlim)` which is still valid in slicing.
            input=x[:, :, :rlim, :],
            filter=tf.zeros([1, 1, 1, 1]),
            strides=[1, 2, 2, 1],
            padding="SAME",
        )
```

Please find the [gist](https://colab.research.google.com/drive/1i2gfQw4Wf218b0uDMSqhBiRvGYfjRh61#scrollTo=oaesGqskdCqw).

Also note that the general slicing semantic in Python allows end > len(a) in a[begin:end] and in such a case a[begin:end] will be regarded as a[begin:min(len(a), end)].

```python
[1,2,3][:2**31] == [1,2,3] # True
```

### Standalone code to reproduce the issue

```shell
!pip install tf-nightly
import tensorflow as tf

class Model(tf.Module):
    @tf.function
    def __call__(self, x, rlim):
        return tf.raw_ops.Conv2D(
            # `rlim` > index_max means `min(index_max, rlim)` in Python.
            input=x[:, :, :rlim, :],
            filter=tf.zeros([1, 1, 1, 1]),
            strides=[1, 2, 2, 1],
            padding="SAME",
        )

model = Model()
inputs = {
    "x": tf.zeros([1, 1, 1, 1]),
    "rlim": tf.constant(2**31, dtype=tf.int64) # 2**31 < int64::max()
}
out = model(**inputs)  # Pass

tflite_bytes = tf.lite.TFLiteConverter.from_concrete_functions(
    funcs=[model.__call__.get_concrete_function(**inputs)], trackable_obj=model
).convert()
interpreter = tf.lite.Interpreter(model_content=tflite_bytes)
runner = interpreter.get_signature_runner()
print("----- TFLite output shape: ", runner(**inputs))  # Crash!!!
```

### Relevant log output

```shell
Crash.
```
</details>

**Comment by tiruk007** [comment]
@ganler 
Could you please refer to these documents([get_signature_runner](https://www.tensorflow.org/lite/api_docs/python/tf/lite/Interpreter#get_signature_runner) & [Signatures in TensorFlow Lite](https://www.tensorflow.org/lite/guide/signatures)). 
Please find the workaround [here](https://colab.research.google.com/gist/tiruk007/6631c9f7b32a3d2580590a700ce7110f/58035.ipynb) and please let us know if it helps.
Thank you!

**Comment by ganler** [comment]
@tiruk007 Thanks for the kind workaround and I understand it. 

I am working on fuzzing TensorFlow and am reporting a potential vulnerbility to TF Lite, which I think it might deserve a fix as this bug causes a TensorFlow Lite program to exit in "an unclean way" (see [security policy](https://github.com/tensorflow/tensorflow/security/policy)) for a well-formed model given some acceptable inputs.

> As a general rule, it is incorrect behavior for TensorFlow to access memory it does not own, or to terminate in an unclean way. Bugs in TensorFlow that lead to such behaviors constitute a vulnerability.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
