### ISSUE TITLE
`Rsqrt` missing in `tensorflow/lite/kernels/internal/reference`

### ISSUE THREAD

**Issue by mrtpk123** [tensorflow/tensorflow#58048]
**System information**
- Linux Ubuntu 16.04
- TensorFlow 2.9.1

Hello,

I converted `tf.keras.layers.LayerNormalization` to `tflite and got the following:

![image](https://user-images.githubusercontent.com/76564442/195016843-088aea0f-6301-4d6e-9ea9-3bbc36a3d744.png)

The code I used is as follows:

```
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8
tflite_quant_model = converter.convert()

tflite_models_dir = pathlib.Path("./tflite_models/")
tflite_models_dir.mkdir(exist_ok=True, parents=True)

tflite_model_quant_file = tflite_models_dir/"model_layer1_encoder.tflite"
tflite_model_quant_file.write_bytes(tflite_quant_model)
```

As you can see I specified that only `tf.lite.OpsSet.TFLITE_BUILTINS_INT8` should be supported and I got a `tflite` without any error. My understanding was that `rsqrt` was not yet supported in int8 (see this [issue](https://github.com/tensorflow/tensorflow/issues/57906)). 

1. Is `rsqrt` supported in `tf.lite.OpsSet.TFLITE_BUILTINS_INT8` spec?

2. I could not find the implementation of `rsqrt` in `tensorflow/lite/kernels/internal/reference`. Can you share a link to the tflite int8 implementation for `rsqrt`?

Thank you for taking the time to answer this. Really appreciate your help. Thanks.

**Comment by mohantym** [comment]
Hi @mrtpk123 !
You find the details on available built-in ops [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/builtin_op_kernels.h).
Thank you!

**Comment by mrtpk123** [comment]
Thank you @mohantym 
https://github.com/tensorflow/tensorflow/blob/b429f6545a8be48b6439f7e1d0feb9896a9e9b5a/tensorflow/lite/kernels/builtin_op_kernels.h#L148
I see that `RSQRT` is a supported built-in op mentioned at `tensorflow/lite/kernels/builtin_op_kernels.h`
This answers my first question.

Can you guide me on finding the implementation of `INT8 RSQRT`?
Is it at `tensorflow/lite/kernels/elementwise.cc` ?
https://github.com/tensorflow/tensorflow/blob/3d32b9fea61196254fde629e86a52193e781a76f/tensorflow/lite/kernels/elementwise.cc#L260

**Comment by mohantym** [comment]
@mrtpk123 !

>  TfLiteStatus RsqrtEvalQuantized(TfLiteContext* context, TfLiteNode* node, ...

That is code snippet for  status check on for Quantization of  Rsqrt 

>  TfLiteRegistration* Register_RSQRT();   

Shows registration of RSQRT in built_in op kernel.


Hi @sachinprasadhs !

Could you look at this query.

Thank you!

**Comment by sachinprasadhs** [comment]
Details on kernel registrations can be found in the code files below.

https://github.com/tensorflow/tensorflow/blob/3d32b9fea61196254fde629e86a52193e781a76f/tensorflow/lite/kernels/register.cc#L247
https://github.com/tensorflow/tensorflow/blob/2fd13f05465037862f07f7b66d75d404275e9ad1/tensorflow/lite/schema/schema_generated.h#L1151

**Comment by mrtpk123** [comment]
Thank you @sachinprasadhs for this.

Can you confirm if this is the int8 implementation of RSQRT ? - https://github.com/tensorflow/tensorflow/blob/3d32b9fea61196254fde629e86a52193e781a76f/tensorflow/lite/kernels/elementwise.cc#L260

Many thanks for your help.

**Comment by sachinprasadhs** [comment]
Yes, that is the implementation for Int8 quantized.

**Comment by mrtpk123** [comment]
Thank you @sachinprasadhs

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
