### ISSUE TITLE
Softlayer Operation with Tflite

### ISSUE THREAD

**Issue by divyajaincs** [tensorflow/tensorflow#58040]
Does Tflite support softlayer operation or need to implement custom Ops as my model is using softlayer as a custom operation and when i'm loading the model that time i'm facing the error. 
![error1](https://user-images.githubusercontent.com/25703066/194878693-694ebed9-d180-45ce-99b0-9072f0feec7c.jpg)

**Comment by tiruk007** [comment]
@divyajaincs 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. 
Thank you!

**Comment by divyajaincs** [comment]
I'm using the below code to load the tflite model.
[https://drive.google.com/file/d/1mhn0ClQEN9Neu85ZK144Ax9tEk4BtNKz/view?usp=sharing](url)
- **tf-nightly 2.11.0.dev20221010**
## code 

import numpy as np
import tensorflow as tf

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="yolo_phase3_model_fp16.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print(input_details)
print(output_details)

**Comment by tiruk007** [comment]
@divyajaincs 
I was able to reproduce the issue in Colab using TF v2.10. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/bb5af88af6e8e4eb68bd4749d55d3e06/58040.ipynb).

Could you please try to add this `converter.allow_custom_ops = True` before converting the model. Please find the documentation ([Custom operators](https://www.tensorflow.org/lite/guide/ops_custom)) for reference and please let us know if it helps.

Thank you!

**Comment by divyajaincs** [comment]
@tiruk007 I'm using the below code for conversion and also using --allow_custom_ops parameter with that because of this i'm able to do the conversion.

```
!tflite_convert --graph_def_file yolo_phase3_model.pb \
    --output_file yolo_phase3_model_fp16.tflite \
    --output_format TFLITE \
    --inference_type FLOAT \
    --inference_input_type FLOAT \
    --input_arrays 'input_1','input_shape' \
    --output_arrays yolo_output/ExpandDims_2 \
    --input_shapes 1,608,608,6:1,2 \
    --post_training_quantize \
    --allow_custom_ops
```

**Comment by tiruk007** [comment]
@divyajaincs 
Could you please provide the yolo phase 3 model.pb file to replicate the issue.
Thank you!

**Comment by tiruk007** [comment]
@divyajaincs 
Thanks for the confirmation. Moving this issue to closed status
Thank you!
