### ISSUE TITLE
Issues running tensorflow 2.10.0 on azure nc4as_t4_v3 Virtual machine with Tesla T4 GPU attached to Ubuntu 20.04

### ISSUE THREAD

**Issue by mai1x9** [tensorflow/tensorflow#58041]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

tf 2.10

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.8.10

### CUDA/cuDNN version

Cuda 11.2, cuDNN 8.1.1.33 (compatible with Cuda 11.2)

### Current Behaviour?

```shell
Unable to run tensor-flow on GPU on ubuntu 20.04.
```

### Standalone code to reproduce the issue

```shell
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
```

Output:
```
2022-10-10 14:59:58.295395: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-10 14:59:59.964199: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-10 15:00:01.498706: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:/usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:
2022-10-10 15:00:01.498789: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:/usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:
2022-10-10 15:00:01.498802: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2022-10-10 15:00:03.290844: E tensorflow/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-10-10 15:00:03.290882: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ml-testserver-1): /proc/driver/nvidia/version does not exist
[]

```

Nvidia 460 is installed using
```
sudo apt install nvidia-driver-460
```

Output:
```
mlserver1@ml-testserver-1:~$ dpkg --list | grep nvidia
ii  libnvidia-cfg1-460:amd64                 460.27.04-0ubuntu1                amd64        NVIDIA binary OpenGL/GLX configuration library
ii  libnvidia-common-460                     460.27.04-0ubuntu1                all          Shared files used by the NVIDIA libraries
ii  libnvidia-compute-460:amd64              460.27.04-0ubuntu1                amd64        NVIDIA libcompute package
ii  libnvidia-decode-460:amd64               460.27.04-0ubuntu1                amd64        NVIDIA Video Decoding runtime libraries
ii  libnvidia-encode-460:amd64               460.27.04-0ubuntu1                amd64        NVENC Video Encoding runtime library
ii  libnvidia-extra-460:amd64                460.27.04-0ubuntu1                amd64        Extra libraries for the NVIDIA driver
ii  libnvidia-fbc1-460:amd64                 460.27.04-0ubuntu1                amd64        NVIDIA OpenGL-based Framebuffer Capture runtime library
ii  libnvidia-gl-460:amd64                   460.27.04-0ubuntu1                amd64        NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
ii  libnvidia-ifr1-460:amd64                 460.27.04-0ubuntu1                amd64        NVIDIA OpenGL-based Inband Frame Readback runtime library
ii  nvidia-compute-utils-460                 460.27.04-0ubuntu1                amd64        NVIDIA compute utilities
iF  nvidia-dkms-460                          460.27.04-0ubuntu1                amd64        NVIDIA DKMS package
iU  nvidia-driver-460                        460.27.04-0ubuntu1                amd64        NVIDIA driver metapackage
ii  nvidia-kernel-common-460                 460.27.04-0ubuntu1                amd64        Shared files used with the kernel module
ii  nvidia-kernel-source-460                 460.27.04-0ubuntu1                amd64        NVIDIA kernel source package
ii  nvidia-modprobe                          460.27.04-0ubuntu1                amd64        Load the NVIDIA kernel driver and create device files
ii  nvidia-prime                             0.8.16~0.20.04.2                  all          Tools to enable NVIDIA's Prime
ii  nvidia-settings                          460.27.04-0ubuntu1                amd64        Tool for configuring the NVIDIA graphics driver
ii  nvidia-utils-460                         460.27.04-0ubuntu1                amd64        NVIDIA driver support binaries
ii  screen-resolution-extra                  0.18build1                        all          Extension for the nvidia-settings control panel
ii  xserver-xorg-video-nvidia-460            460.27.04-0ubuntu1                amd64        NVIDIA binary Xorg driver

```

Cuda is installed using (Ref: https://developer.nvidia.com/cuda-11.2.0-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=2004&target_type=deblocal)

```
wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/11.2.0/local_installers/cuda-repo-ubuntu2004-11-2-local_11.2.0-460.27.04-1_amd64.deb
sudo dpkg -i cuda-repo-ubuntu2004-11-2-local_11.2.0-460.27.04-1_amd64.deb
sudo apt-key add /var/cuda-repo-ubuntu2004-11-2-local/7fa2af80.pub
sudo apt-get update
sudo apt-get -y install cuda
```

I tried couple of ways installing tensorflow 2.7.0 and nvidia drivers 515, cuda 11.6 all of them are in vain. 

Looks like tensorflow only supports Cuda 11.2.
However nvidia-460 does not seem to be run on ubuntu 20.04.

Output of nvidia-smi
```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

```

I have tried couple of weays to fix it on ubuntu 20.04 from nvidia developer forums but in vain. 

Kernel details: 
```
Linux ml-testserver-1 5.15.0-1020-azure #25~20.04.1-Ubuntu SMP Thu Sep 1 19:20:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

I am pretty sure the error
```
2022-10-10 15:00:03.290844: E tensorflow/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-10-10 15:00:03.290882: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ml-testserver-1): /proc/driver/nvidia/version does not exist

```
is because nvidia drivers is not running. Any help over here would be great.

However the other errors,
```
Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:/usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:
2022-10-10 15:00:01.498789: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:/usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:
```
the shared libraries are not isntalled along with Cuda 11.2, how should i be fixing them. ??

Any help is highly appreicated. Kind of stuck since 2 days. Looking for a help.
```


### Relevant log output

_No response_</details>

**Comment by mai1x9** [comment]
Hi, after lot of exploration and deep dive, refering to various nvidia blog discussions, I could find out that, lot of issues where raised upto `5.8` linux kernel version. Looks like the azure vm which is being used uses `5.15` kernel version and most probably, I am unable to run nvidia- 460 drivers. Cuda 11.2 strictly requires nvidia 460 driver. 

I have found work around by downgrading tensorflow to `2.3.0` to use cuda `10.1` version and cudnn `7.6.5`. Fortunately, cuda `10.1` is running with nvidia 515 driver version (which is lates recommened nvidia drivers for ubuntu `20.04`.

Fortunately, `cudnn 7.6.5` is released for ubuntu `18.04` and no files found for `ubuntu 20.04` from nvidia cudnn downloads. To my luck, it indeed worked for ubuntu `20.04`.

I would be glad if someone can assit me in installing `cuda 11.2` with tensorflow `2.10.0` on azure nc4 as t4 virtual machine.

**Comment by mai1x9** [comment]
>

**Comment by mai1x9** [comment]
> 



> Click to expand!
> ### Issue Type
> Build/Install
> 
> ### Source
> binary
> 
> ### Tensorflow Version
> tf 2.10
> 
> ### Custom Code
> No
> 
> ### OS Platform and Distribution
> Ubuntu 20.04
> 
> ### Mobile device
> _No response_
> 
> ### Python version
> 3.8.10
> 
> ### Bazel version
> _No response_
> 
> ### GCC/Compiler version
> _No response_
> 
> ### CUDA/cuDNN version
> Cuda 11.2, cuDNN 8.1.1.33 (compatible with Cuda 11.2)
> 
> ### GPU model and memory
> _No response_
> 
> ### Current Behaviour?
> ```shell
> Unable to run tensor-flow on GPU on ubuntu 20.04.
> ```
> 
> ### Standalone code to reproduce the issue
> ```shell
> python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
> ```
> 
> Output:
> 
> ```
> 2022-10-10 14:59:58.295395: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2022-10-10 14:59:59.964199: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
> 2022-10-10 15:00:01.498706: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:/usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:
> 2022-10-10 15:00:01.498789: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:/usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:
> 2022-10-10 15:00:01.498802: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
> 2022-10-10 15:00:03.290844: E tensorflow/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
> 2022-10-10 15:00:03.290882: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ml-testserver-1): /proc/driver/nvidia/version does not exist
> []
> ```
> 
> Nvidia 460 is installed using
> 
> ```
> sudo apt install nvidia-driver-460
> ```
> 
> Output:
> 
> ```
> mlserver1@ml-testserver-1:~$ dpkg --list | grep nvidia
> ii  libnvidia-cfg1-460:amd64                 460.27.04-0ubuntu1                amd64        NVIDIA binary OpenGL/GLX configuration library
> ii  libnvidia-common-460                     460.27.04-0ubuntu1                all          Shared files used by the NVIDIA libraries
> ii  libnvidia-compute-460:amd64              460.27.04-0ubuntu1                amd64        NVIDIA libcompute package
> ii  libnvidia-decode-460:amd64               460.27.04-0ubuntu1                amd64        NVIDIA Video Decoding runtime libraries
> ii  libnvidia-encode-460:amd64               460.27.04-0ubuntu1                amd64        NVENC Video Encoding runtime library
> ii  libnvidia-extra-460:amd64                460.27.04-0ubuntu1                amd64        Extra libraries for the NVIDIA driver
> ii  libnvidia-fbc1-460:amd64                 460.27.04-0ubuntu1                amd64        NVIDIA OpenGL-based Framebuffer Capture runtime library
> ii  libnvidia-gl-460:amd64                   460.27.04-0ubuntu1                amd64        NVIDIA OpenGL/GLX/EGL/GLES GLVND libraries and Vulkan ICD
> ii  libnvidia-ifr1-460:amd64                 460.27.04-0ubuntu1                amd64        NVIDIA OpenGL-based Inband Frame Readback runtime library
> ii  nvidia-compute-utils-460                 460.27.04-0ubuntu1                amd64        NVIDIA compute utilities
> iF  nvidia-dkms-460                          460.27.04-0ubuntu1                amd64        NVIDIA DKMS package
> iU  nvidia-driver-460                        460.27.04-0ubuntu1                amd64        NVIDIA driver metapackage
> ii  nvidia-kernel-common-460                 460.27.04-0ubuntu1                amd64        Shared files used with the kernel module
> ii  nvidia-kernel-source-460                 460.27.04-0ubuntu1                amd64        NVIDIA kernel source package
> ii  nvidia-modprobe                          460.27.04-0ubuntu1                amd64        Load the NVIDIA kernel driver and create device files
> ii  nvidia-prime                             0.8.16~0.20.04.2                  all          Tools to enable NVIDIA's Prime
> ii  nvidia-settings                          460.27.04-0ubuntu1                amd64        Tool for configuring the NVIDIA graphics driver
> ii  nvidia-utils-460                         460.27.04-0ubuntu1                amd64        NVIDIA driver support binaries
> ii  screen-resolution-extra                  0.18build1                        all          Extension for the nvidia-settings control panel
> ii  xserver-xorg-video-nvidia-460            460.27.04-0ubuntu1                amd64        NVIDIA binary Xorg driver
> ```
> 
> Cuda is installed using (Ref: https://developer.nvidia.com/cuda-11.2.0-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=2004&target_type=deblocal)
> 
> ```
> wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
> sudo mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600
> wget https://developer.download.nvidia.com/compute/cuda/11.2.0/local_installers/cuda-repo-ubuntu2004-11-2-local_11.2.0-460.27.04-1_amd64.deb
> sudo dpkg -i cuda-repo-ubuntu2004-11-2-local_11.2.0-460.27.04-1_amd64.deb
> sudo apt-key add /var/cuda-repo-ubuntu2004-11-2-local/7fa2af80.pub
> sudo apt-get update
> sudo apt-get -y install cuda
> ```
> 
> I tried couple of ways installing tensorflow 2.7.0 and nvidia drivers 515, cuda 11.6 all of them are in vain.
> 
> Looks like tensorflow only supports Cuda 11.2. However nvidia-460 does not seem to be run on ubuntu 20.04.
> 
> Output of nvidia-smi
> 
> ```
> NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
> ```
> 
> I have tried couple of weays to fix it on ubuntu 20.04 from nvidia developer forums but in vain.
> 
> Kernel details:
> 
> ```
> Linux ml-testserver-1 5.15.0-1020-azure #25~20.04.1-Ubuntu SMP Thu Sep 1 19:20:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
> ```
> 
> I am pretty sure the error
> 
> ```
> 2022-10-10 15:00:03.290844: E tensorflow/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
> 2022-10-10 15:00:03.290882: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ml-testserver-1): /proc/driver/nvidia/version does not exist
> ```
> 
> is because nvidia drivers is not running. Any help over here would be great.
> 
> However the other errors,
> 
> ```
> Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:/usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:
> 2022-10-10 15:00:01.498789: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:/usr/local/cuda/lib64:/usr/local/cuda-11.2/lib64:
> ```
> 
> the shared libraries are not isntalled along with Cuda 11.2, how should i be fixing them. ??
> 
> Any help is highly appreicated. Kind of stuck since 2 days. Looking for a help.
> 
> ```
> 
> 
> ### Relevant log output
> 
> _No response_</details>
> ```

**Comment by SuryanarayanaY** [comment]
Hi @mai1x9 ,

I don't think this is still an issue. I have few tests done recently and GPU is able to detectable. I followed officila documentation instructions mentioned [here](https://www.tensorflow.org/install/pip#step-by-step_instructions) and succeeded in detecting GPU. You have to use conda environment and follow the instructions mentioned in attached source.

For reference I am attaching my tested logs with latest versions below.

```
(tf) suryanarayanay@surya-ubuntu22-cuda-test:~$ pip install nvidia-cudnn-cu11==8.6.0.163
Requirement already satisfied: nvidia-cudnn-cu11==8.6.0.163 in ./miniconda3/envs/tf/lib/python3.9/site-packages (8.6.0.163)
Requirement already satisfied: nvidia-cublas-cu11 in ./miniconda3/envs/tf/lib/python3.9/site-packages (from nvidia-cudnn-cu11==8.6.0.163) (11.11.3.6)
(tf) suryanarayanay@surya-ubuntu22-cuda-test:~$ CUDNN_PATH=$(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)"))
(tf) suryanarayanay@surya-ubuntu22-cuda-test:~$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:$CUDNN_PATH/lib
(tf) suryanarayanay@surya-ubuntu22-cuda-test:~$ mkdir -p $CONDA_PREFIX/etc/conda/activate.d
(tf) suryanarayanay@surya-ubuntu22-cuda-test:~$ echo 'CUDNN_PATH=$(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)"))' >> $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh
(tf) suryanarayanay@surya-ubuntu22-cuda-test:~$ echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:$CUDNN_PATH/lib' >> $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh
(tf) suryanarayanay@surya-ubuntu22-cuda-test:~$ python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
2023-04-21 06:12:14.343689: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-04-21 06:12:14.400436: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-21 06:12:15.255386: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

Please cross check with official instructions and let us know if still facing any problem. Thanks!

**Comment by mai1x9** [comment]
@SuryanarayanaY the issue is with Ubuntu 20.04. I believe you were using Ubuntu 22.
I have cleay checked the cuda and nvidia drivers didn't support the kernel version Ubuntu 20.04 running from nvidia official documentation.

**Comment by mai1x9** [comment]
> I tried couple of ways installing tensorflow 2.7.0 and nvidia drivers 515, cuda 11.6 all of them are in vain.
> 
> Looks like tensorflow only supports Cuda 11.2. However nvidia-460 does not seem to be run on ubuntu 20.04.
> 
> Output of nvidia-smi
> 
> ```
> NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
> ```
> 
> I have tried couple of weays to fix it on ubuntu 20.04 from nvidia developer forums but in vain.
> 
> Kernel details:
> 
> ```
> Linux ml-testserver-1 5.15.0-1020-azure #25~20.04.1-Ubuntu SMP Thu Sep 1 19:20:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
> ```
> 
> I am pretty sure the error

@SuryanarayanaY can you recheck on this.

**Comment by SuryanarayanaY** [comment]
Hi @mai1x9 ,

I have already checked the same on Ubuntu20 VM also and able to detect GPU successfully.Please refer to attached logs below.
```
(bazel3) suryanarayanay@surya-ubuntu20:~$ python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"

2023-04-21 11:17:04.499149: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-21 11:17:06.236240: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-04-21 11:17:09.846984: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:997] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-04-21 11:17:10.203917: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:997] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-04-21 11:17:10.205697: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:997] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

**Comment by mai1x9** [comment]
@SuryanarayanaY thanks for the info, I will try again with ubuntu 20 machine from scratch

**Comment by SuryanarayanaY** [comment]
Hi @mai1x9 ,

AFAIK there is no with Ubuntu20 VM with T4 GPU on GCP. Please feel free to close the issue if resolved. Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @mai1x9 ,

I don't have access to Azure VM to test. If there is no problem with GCP VM finding GPU it should work for Azure also unless there is some specific environment or configurations related issue.

But for this case from the attached logs of yours it's clear that nvidia-driver is not up and running. The log below confirms it.

`NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.`

If you have already downloaded `nvidia-driver` suitable for the GPU ensure execute permissions and then run it.The above [comment](https://github.com/tensorflow/tensorflow/issues/58041#issuecomment-1549385415) have an example of how can we do this.

Until you are able to run nvidia driver which can tested with `nvidia-smi` command that outputs driver info along with GPUs Tensorflow can't able to detect GPUs. Please note that installing and enabling nvidia-driver not in Tensorflow scope. Once nvidia-smi is able to output Driver and GPU info and then still you are facing problem then please let us know.

Thanks!

**Comment by sgireddy** [comment]
I wrestled with this issue for many hours, this is not a tensorflow issue esp. on Azure where I had the same issue. Please follow these instructions, looks like it is very sensitive to CUDA and driver versions:
https://learn.microsoft.com/en-us/azure/virtual-machines/linux/n-series-driver-setup
