### ISSUE TITLE
tf.nn.conv2d failed to activate TF-32 mode

### ISSUE THREAD

**Issue by HengjiaLi** [tensorflow/tensorflow#58047]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

2.6.2

### Custom Code

Yes

### OS Platform and Distribution

18.04

### Python version

3.7.5

### CUDA/cuDNN version

CUDA-11.6/cuDNN version 8300

### Current Behaviour?

```shell
I tried to test convolution's accuracy under TF-32 mode on my A100 chips by comparing TF-32's and FP-32's computaitonal results.

Firstly, I tested a simple MatMul example (as given here:https://www.tensorflow.org/api_docs/python/tf/config/experimental/enable_tensor_float_32_execution). TF-32's and FP-32's results are indeed different as expected. It indicates my environment supports TF-32 mode by default.

Then I used tf.nn.conv2d() method fed with randomly generated float32 data(feature map[1,16,7,7], weight(16,16,3,3)), to test acc of convolution under TF-32 mode, but TF-32's and FP-32's results turned to be identical. It seems like tf.nn.conv2d() failed to activate TF-32, and convlution is done in full-precision mode?
```

### Standalone code to reproduce the issue

```shell
fm = np.fromfile(input_fm_bin,dtype=np.float32).reshape([1,16,7,7]).transpose((0,2,3,1))
w = np.fromfile(filter_bin,dtype=np.float32).reshape([16,16,3,3]).transpose(2, 3, 1, 0)
bias = np.fromfile(bias_bin,dtype=np.float32)


fm = tf.convert_to_tensor(fm)
w = tf.convert_to_tensor(w)
bias = tf.convert_to_tensor(bias)
res_tf32 = tf.nn.conv2d(fm, w, [1, 1],[[0, 0], [0, 0], [0, 0], [0, 0]],"NHWC", [1, 2, 2, 1])
res_tf32 = tf.nn.bias_add(res_tf32, bias, data_format="NHWC")

tf.config.experimental.enable_tensor_float_32_execution(False)
res_full = tf.nn.conv2d(fm, w, [1, 1],[[0, 0], [0, 0], [0, 0], [0, 0]],"NHWC", [1, 2, 2, 1])
res_full = tf.nn.bias_add(res_full, bias, data_format="NHWC")
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@HengjiaLi 
I reproduced the code shared but facing a different error .Could you please share the colab gist with all the dependencies to analyze more of it. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/c1c33f2524abdb483924f528a84482e7/58047.ipynb) for reference.

Thank you!

**Comment by HengjiaLi** [comment]
lack of input data, please try the following code instead

import os
import numpy as np
import tensorflow as tf
fm = np.random.rand(1,7,7,16).astype(np.float32)
w = np.random.rand(3,3,16,16).astype(np.float32)
bias = np.random.rand(16).astype(np.float32)
############### conv2d tf 32 result ###############################
tf.config.experimental.enable_tensor_float_32_execution(True)
fm = tf.convert_to_tensor(fm)
w = tf.convert_to_tensor(w)
bias = tf.convert_to_tensor(bias)
res_tf32 = tf.nn.conv2d(fm, w, [1, 1],[[0, 0], [0, 0], [0, 0], [0, 0]],"NHWC", [1, 1, 1, 1])
res_tf32 = tf.nn.bias_add(res_tf32, bias, data_format="NHWC")

################# conv2d FP32 result ##############################
tf.config.experimental.enable_tensor_float_32_execution(False)
res_full = tf.nn.conv2d(fm, w, [1, 1],[[0, 0], [0, 0], [0, 0], [0, 0]],"NHWC", [1, 1, 1, 1])
res_full = tf.nn.bias_add(res_full, bias, data_format="NHWC")

print("convolution results in TF32/FP32 are the same: ", np.all(res_tf32==res_full))

**Comment by HengjiaLi** [comment]
@tiruk007

**Comment by tiruk007** [comment]
@sachinprasadhs 
I was able to reproduce the issue on Colab using tf-nightly-2.11.0.dev20221012. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/2c168486345d436ec8bc4af325c875a8/58047.ipynb) for reference

Thank you!

**Comment by HengjiaLi** [comment]
@tiruk007 
ATM, what can I do to activate TF-32 with convolutions?

thanks.

**Comment by HengjiaLi** [comment]
@sachinprasadhs

**Comment by HengjiaLi** [comment]
@sachinprasadhs 
ATM, what can I do to activate TF-32 with convolutions?

**Comment by HengjiaLi** [comment]
any update on this issue?
@sachinprasadhs @tiruk007
