### ISSUE TITLE
tf.saturate_cast errors for tf.complex type tensor

### ISSUE THREAD

**Issue by huan1372** [tensorflow/tensorflow#58053]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04.5 LTS

### Python version

 3.8.10

### Current Behaviour?

```shell
From code below, the tf.saturate_cast need to check dtype's min
https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/ops/math_ops.py#L713-L743

However, from code below, min is not support for complex64 or complex128
https://github.com/tensorflow/tensorboard/blob/master/tensorboard/compat/tensorflow_stub/dtypes.py#L188-L194

The documentation for tf.saturate_cast said it support any tensor or dtype desired. Therefore, either code or documentation need to be changed
https://github.com/tensorflow/tensorflow/blob/v2.1.0/tensorflow/python/ops/math_ops.py#L716-L729
```

### Standalone code to reproduce the issue

```shell
Code like: 

import tensorflow as tf
arg_0_tensor = tf.complex(tf.random.uniform([2, 1], dtype=tf.float32),tf.random.uniform([2, 1], dtype=tf.float32))
arg_0_tensor = tf.saturate_cast(arg_0_tensor,dtype=tf.float32)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/dtypes.py", line 110, in min
    raise TypeError(f"Cannot find minimum value of {self} with "
TypeError: Cannot find minimum value of <dtype: 'complex64'> with type <dtype: 'complex64'>.
```
</details>

**Comment by huan1372** [comment]
Yes. That is the same issue

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue, I have updated the document with the above PR to show the list of supported dtypes in the args.

**Comment by cantonios** [comment]
We don't have comparisons for complex types, so there is no real "minimum" or "maximum" value at which to saturate.

What is your intention here?

**Comment by huan1372** [comment]
The saturate_cast function will use  minimum value which not implemented in complex type as you said, but in the documentation of saturate_cast, it did not said we cannot use complex dtype. Thats why I suggest change the documentation for saturate_cast.

**Comment by cantonios** [comment]
The documentation doesn't list any types at all.  That doesn't mean it supports all types.  I'm wondering why this is important.  Did you actually intend to use `saturate_cast` on a complex type? and if so, what is your desired outcome?

We don't typically list all the types an op supports unless we have good reason.

**Comment by huan1372** [comment]
Yes,  I am actually doing saturate_cast on the complex type and got an error saying that min value is not supported and when I try to search documentation online, there is little info regarding this function. So I do think it is important to explain more in saturate_cast args otherwise someone else may get an unexpected error from math_ops.py and take time to debug. 

Apart from user side, I am also doing testing with tensorflow api, I found it very hard to collect some type information of inputs for tensorflow library. If there is more documentation available, it will be more helpful to find bugs and doing testing.

Thanks for your consideration!

**Comment by cantonios** [comment]
> and if so, what is your desired outcome?

**Comment by huan1372** [comment]
In the documentation, it said This function casts the input to dtype without applying any scaling.
I want to cast a complex type to float type.

**Comment by cantonios** [comment]
> it said This function casts the input to dtype without applying any scaling.

So does `tf.cast`.  The difference is that if the input doesn't fit within the range of the output, it clips the values into a finite range instead of converting to `inf`.

> I want to cast a complex type to float type.

Casting from complex to real will produce a warning.  If you want the real component, you should use `tf.math.real`.  You can saturate-cast on that if you like, for example if trying to cast from `tf.complex128` to `tf.float32`, you would do:
```
y = tf.saturate_cast(tf.math.real(x), dtype=tf.float32)
```

**Comment by huan1372** [comment]
I totally get your point, but why this could not be added in the documentation?  If not adding in documentation, where could we found those information?

**Comment by cantonios** [comment]
"Cast" has as very specific meaning.  Is the confusion in documentation about what the purpose of "cast" is?  Is the confusion how to extract the real component of a complex tensor?  That's why I'm trying to understand what the use-case is.

Simply listing "cannot be used for complex types" wouldn't help you accomplish what you're trying to do.

**Comment by huan1372** [comment]
The tf.cast documentation does not have any confusion here: https://www.tensorflow.org/api_docs/python/tf/cast
It mentioned everything I need and I am wondering why there is no link to cast from saturate_cast or any explanation like that?:

The operation supports data types (for x and dtype) of uint8, uint16, uint32, uint64, int8, int16, int32, int64, float16, float32, float64, complex64, complex128, bfloat16. In case of casting from complex types (complex64, complex128) to real types, only the real part of x is returned. In case of casting from real types to complex types (complex64, complex128), the imaginary part of the returned value is set to 0. The handling of complex types here matches the behavior of numpy.

Note casting nan and inf values to integral types has undefined behavior.

**Comment by cantonios** [comment]
Again, I don't think listing input types solves the issue.  The problem with doing something like that is that `saturate_cast` is just a composite op that calls other ops, including `tf.maximum` and `tf.cast`.  If we ever modify the valid input types for `tf.maximum` or `tf.cast`, it would implicitly modify the valid input types to `tf.saturate_cast`.  They would all need to be kept synced.

We could add a link to the `tf.cast` documentation for further details.

And perhaps it _should_ work for complex inputs.  Complex to real should do what I described above (although again, would produce a warning just as `tf.cast` does).  Complex to complex should probably saturate-cast the real and imaginary components separately.

**Comment by huan1372** [comment]
I agree with you if you guys could add link of tf. Cast and if could add some instruction of how to use complex type as you said
