### ISSUE TITLE
The repository named 'local_config_cuda' could not be resolved.

### ISSUE THREAD

**Issue by riless** [tensorflow/tensorflow#5805]
I'm trying to use this structure for my project (using tensorflow as a module in my project) and my_project only contains code to build an .so library.
```
my_project
|-- WORKSPACE
|-- my_android_app
|   |-- BUILD
|   `-- ...
|-- tensorflow
|   |-- tensorflow
|   |   |   |-- workspace.bzl
|   |   |   |-- tensorflow.bzl
|   |   |   `-- ...
|   |-- WORKSPACE
|   |-- BUILD
.    `-- ...
```

The content of `my_project/WORKSPACE` is 
```
workspace(name = "my_project")

local_repository(
  name = "org_tensorflow",
  path = "tensorflow/"
)
```

The content of `my_project/my_android_app/BUILD` for now is:

```
package(default_visibility = ["//visibility:public"])
load("@org_tensorflow//tensorflow:tensorflow.bzl", "tf_copts")
tf_copts()
```

When I try build this project with bazel I have this error:

`bazel build -c opt //my_project --crosstool_top=//external:android/crosstool  --cpu=armeabi-v7a  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain`

`ERROR: error loading package 'my_project': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': error loading package 'external': The repository named 'local_config_cuda' could not be resolved.`

NB: I'm successfully building the TensorFlow Android Camera Demo `tensorflow/tenssorflow/examples/android/`

Related Issue: [#2775](https://github.com/tensorflow/tensorflow/issues/2775)

**Comment by prb12** [comment]
@petewarden I can't tell if this is just a generic bazel question, or something specific to the Android platform.  Could you please take a look?

**Comment by petewarden** [comment]
I'm not sure on this one, it looks like a more generic Bazel question rather than something specific to Android?

**Comment by ncoudray** [comment]
Hi,
  I am having a similar issue when trying to run the retraining test (following https://www.tensorflow.org/tutorials/image_retraining):

ERROR: error loading package 'tensorflow/examples/image_retraining': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': error loading package 'external': The repository named 'local_config_cuda' could not be resolved.

Have you been able to solve this issue, and how? 

I'm using cuda 8.0, bazel 0.4.4, python 3.5.3 (also tried with 2.7).

Thanks a lot,
Best,
Nicolas

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
