### ISSUE TITLE
_MklBatchMatMulV2 performs even worse than normal BatchMatMul

### ISSUE THREAD

**Issue by beichengus** [tensorflow/tensorflow#58075]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux 3.10
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: No
-   **TensorFlow installed from (source or binary)**: Source
-   **TensorFlow version (use command below)**: 2.5
-   **Python version**: py3.6
-   **Bazel version (if compiling from source)**:  2.0
-   **GCC/Compiler version (if compiling from source)**:7.3
-   **CUDA/cuDNN version**: N/A
-   **GPU model and memory**: N/A
-   **Exact command to reproduce**: N/A

_MklBatchMatMulV2 performs even worse than normal BatchMatMul.
I installed tensorflow2.5 from source code without any special config. when I set TF_ENABLE_ONEDNN_OPTS=1, tf performed better than baseline(with TF_ENABLE_ONEDNN_OPTS=0) on my recommendation model. Though I found it performed better on some ops like _MklMatMul, _MklNativeFusedMatMul, it worked worse on _MklBatchMatMulV2(160ms vs 110ms on total 150 _MklBatchMatMulV2 ops). Does this result is expected?

I also tried set --config=mkl when I compliled tensorflow2.5 but get the same result. 

I also tried set --config=mkl when I compiled tensorflow2.2, MklBatchMatMul performed better than normal tf2.2(without --config=mkl). The result is 70ms vs 110ms. 

Is there any way to allow me to get better performance on BatchMatMul op using tf2.5? or is there any way to use normal BatchMatMul op rather than _MklBatchMatMulV2 when seting TF_ENABLE_ONEDNN_OPTS=1 because _MklBatchMatMulV2 performed worse but _MklMatMul and _MklNativeFusedMatMul performed much better.

**Comment by sushreebarsa** [comment]
@beichengus 
Could you try to upgrade to latest TF version 2.10 and please provide a code snippet to reproduce the issue reported here if the issue still persists? Thank you!
