### ISSUE TITLE
Cross-build failed tensorflow lite demo minimal

### ISSUE THREAD

**Issue by TUT-jiayou** [tensorflow/tensorflow#58074]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04

### Mobile device

arm32

### GCC/Compiler version

clang 10

### Current Behaviour?

```shell
* I follow the document[https://github.com/tensorflow/tensorflow/blob/v2.10.0/tensorflow/lite/examples/minimal/README.md] to build the minimal demo

mkdir build_minimal
cd build_minimal
cmake  -DCMAKE_TOOLCHAIN_FILE=/home/yons/data/ohos-sdk/linux/native/build/cmake/ohos.toolchain.cmake ../tensorflow/lite/examples/minimal/
cmake --build . -j 20
```

* I got error 
```
Building CXX object CMakeFiles/minimal.dir/minimal.cc.obj
clang++: warning: argument unused during compilation: '--gcc-toolchain=/home/yons/data/ohos-sdk/linux/native/llvm' [-Wunused-command-line-argument]
In file included from /home/yons/data/tensorflow/tensorflow/lite/examples/minimal/minimal.cc:17:
In file included from /home/yons/data/tensorflow/tensorflow/lite/kernels/register.h:18:
In file included from /home/yons/data/tensorflow/tensorflow/lite/model.h:21:
/home/yons/data/tensorflow/tensorflow/lite/interpreter_builder.h:26:10: fatal error: 'flatbuffers/flatbuffers.h' file not found
#include "flatbuffers/flatbuffers.h"  // from @flatbuffers
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
CMakeFiles/minimal.dir/build.make:62: recipe for target 'CMakeFiles/minimal.dir/minimal.cc.obj' failed
make[2]: *** [CMakeFiles/minimal.dir/minimal.cc.obj] Error 1
CMakeFiles/Makefile2:1295: recipe for target 'CMakeFiles/minimal.dir/all' failed
make[1]: *** [CMakeFiles/minimal.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
* Please guide me to configure the include directory!
* thanks for your time!
```


### Standalone code to reproduce the issue

```shell
https://github.com/tensorflow/tensorflow/tree/v2.10.0/tensorflow/lite/examples/minimal


```
* I change the `CMakeLists.txt`
```
cmake_minimum_required(VERSION 3.16)
project(minimal C CXX)

set(TENSORFLOW_SOURCE_DIR "" CACHE PATH
  "Directory that contains the TensorFlow project"
)
if(NOT TENSORFLOW_SOURCE_DIR)
  get_filename_component(TENSORFLOW_SOURCE_DIR
    "${CMAKE_CURRENT_LIST_DIR}/../../../../"
    ABSOLUTE
  )
endif()

add_subdirectory(
  "${TENSORFLOW_SOURCE_DIR}/tensorflow/lite"
  "${CMAKE_CURRENT_BINARY_DIR}/tensorflow-lite"
  EXCLUDE_FROM_ALL
)

message(TARCE "TuT " ${TENSORFLOW_SOURCE_DIR})
include_directories(${TENSORFLOW_SOURCE_DIR}/)
#include_directories(${CMAKE_CURRENT_LIST_DIR}/flatbuffers/include)
set(CMAKE_CXX_STANDARD 17)
add_executable(minimal
  minimal.cc
)
add_library(tf-lite STATIC IMPORTED )
set_target_properties(
    tf-lite
    PROPERTIES IMPORTED_LOCATION
    /home/yons/data/tensorflow/build_lite/libtensorflow-lite.a
    )
target_link_libraries(minimal
  tf-lite
)
```

### Relevant log output

_No response_</details>

**Comment by TUT-jiayou** [comment]
* if I use original ·CMakelists.txt`, I got the error.
![image](https://user-images.githubusercontent.com/21277368/195518211-100a9cae-2d88-433b-92b0-af4852d0da0f.png)

**Comment by mohantym** [comment]
Hi @TUT-jiayou !
Sorry for the late response. 
Actually I was looking for "ohos.toolchain.cmake" tool chain. 

Could you uncomment this line in cmake_list.txt and let us know.
#include_directories(${CMAKE_CURRENT_LIST_DIR}/flatbuffers/include)

Thank you!

**Comment by TUT-jiayou** [comment]
Hi, @mohantym  
thanks for your time.
* The `ohos.toolchain.cmake` toolchain build binary for armv7a. 
 * You can directly view the original `CMakeList.txt` result 
https://github.com/tensorflow/tensorflow/issues/58074#issuecomment-1277090290

**Comment by bhupendrarajput98** [comment]
I have seen this issue and I tried https://stackoverflow.com/questions/72129186/tensorflow-2-8-cmake-static-built-static-library-showing-undefined-reference-for  and it worked

**Comment by mohantym** [comment]
Hi @TUT-jiayou !
Could you confirm whether it works with latest C++ version as suggested in above [thread.](https://github.com/tensorflow/tensorflow/issues/58074#issuecomment-1278546985)
Thank you!

**Comment by mohantym** [comment]
@TUT-jiayou !
Thanks for the confirmation . Moving this issue to resolved status.
Thank you!

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)

**Comment by TUT-jiayou** [comment]
HI,all
@mohantym 
I can compile a hello world demo using cpp 17 and 20. I can not build tensorflow minimal demo. So, please reopen the issue!

**Comment by TUT-jiayou** [comment]
* About flatbuffers library, the macro named `FLATBUFFERS_LOCALE_INDEPENDENT` is set to 0 in  the `flatbuffers/CMakeLists.txt`  file. So symbol `flatbuffers::ClassicLocale::instance_` is undefined.
![image](https://user-images.githubusercontent.com/21277368/196084151-ba64983e-b992-4082-9571-31fe958addc9.png)

**Comment by mohantym** [comment]
Ok @TUT-jiayou!
Sure re-opening as requested.

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by TUT-jiayou** [comment]
Hi ,all
* I fix the bug by comment some flatbuffers code. Detail in the (link)[https://github.com/google/flatbuffers/issues/7587].
* I close the issue.

**Comment by TUT-jiayou** [comment]
Hi ,all
Thanks for your time.
@mohantym @sachinprasadhs @bhupendrarajput98
