### ISSUE TITLE
Fail to serialize EfficientNet model using to_json() method

### ISSUE THREAD

**Issue by ebnertom** [tensorflow/tensorflow#58088]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10

### Custom Code

No

### OS Platform and Distribution

ubuntu 18.04

### Python version

3.9

### CUDA/cuDNN version

CUDA 11.2, cudnn 8.1

### Current Behaviour?

```shell
Calling to_json() method fails on EfficientNet's when using imagenet weights.

It seems the problem occurs when serializing the following layer of efficientnet:

x = layers.Rescaling(1.0 / tf.math.sqrt(IMAGENET_STDDEV_RGB))(x)

The scale parameter seems to be some of type tensorflow.python.framework.ops.EagerTensor, which is not serializable.

The problem was most likely introduced in https://github.com/tensorflow/tensorflow/issues/49930.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from keras.applications import EfficientNetB3

m1 = EfficientNetB3(weights='imagenet')
m1.to_json()
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/tom/whaat.py", line 5, in <module>
    m1.to_json()
  File "/home/.virtualenvs/pypotato-py39/lib/python3.9/site-packages/keras/engine/training.py", line 3087, in to_json
    return json.dumps(
  File "/usr/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/.virtualenvs/pypotato-py39/lib/python3.9/site-packages/keras/saving/saved_model/json_utils.py", line 221, in get_json_type
    raise TypeError(
TypeError: Unable to serialize [2.0896919 2.1128857 2.1081853] to JSON. Unrecognized type <class 'tensorflow.python.framework.ops.EagerTensor'>.

Process finished with exit code 1
```
</details>

**Comment by sushreebarsa** [comment]
@ebnertom I was able to run the code successfully using TF v2.8 and 2.9, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/4c9c7cabef604c486e22865d96925ee1/58088-2-8.ipynb#scrollTo=49uDUiXmyhpU) here. 
I was able to replicate the issue on colab using TF v2.10, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/ce2d63f5ffd0349b39eeacd3c16178b0/58088.ipynb#scrollTo=cju7eBXpX13s) here and confirm the same?
Thank you!

**Comment by ebnertom** [comment]
@sushreebarsa I can confirm that I get the same error.

**Comment by sachinprasadhs** [comment]
As you have mentioned the issue could be due to the previous issue https://github.com/tensorflow/tensorflow/issues/49930, this seems to be keras issue.
Please post this issue on keras-team/keras repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
