### ISSUE TITLE
 got this issue when I run the emotion detection program

### ISSUE THREAD

**Issue by HiraNazir885** [tensorflow/tensorflow#58084]
<img width="956" alt="Capture1" src="https://user-images.githubusercontent.com/75195908/195511477-b86cd1b7-dc65-4b3c-93d7-8551a5c86af0.PNG">
<img width="931" alt="Capture" src="https://user-images.githubusercontent.com/75195908/195511521-f482006b-613c-4852-96d5-45bfdbd84600.PNG">

**Comment by tilakrayal** [comment]
@HiraNazir885,
Kindly fill the issue template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose) and also for debugging the issue, could you please provide code in reproducible format or colab gist and the TensorFlow version you are using. Thank you!
