### ISSUE TITLE
TFLite Interpreter.invoke()- gather index out of boundsNode number 935 (GATHER) failed to invoke.

### ISSUE THREAD

**Issue by divyajaincs** [tensorflow/tensorflow#58085]
Getting this error with the following sample code for prediction: 

Model weights: [https://drive.google.com/file/d/1SXbMtxQKiU-Iavh6U7lwzEZS0lYYNpJy/view?usp=sharing](url)

```
import tensorflow as tf


def run_tflite_model(tflite_file,image_data,y_inp):
    #print('image_data',image_data)
    #print('y_inp',y_inp)
    #feed_f = dict(zip(['input_2', 'input_shape'], (image_data, y_inp)))
    interpreter = tf.lite.Interpreter(model_path=str(tflite_file))
    interpreter.allocate_tensors()
    #print(interpreter.get_input_details())
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    print(input_details)
    print(output_details)
    print(image_data.shape)
    print(y_inp.shape)
    interpreter.set_tensor(input_details[0]["index"],image_data)
    interpreter.set_tensor(input_details[1]["index"],y_inp)
    print('tensor details:',interpreter.get_tensor_details())
    interpreter.resize_tensor_input(input_details[1]['index'], [1,2])
    interpreter.invoke()
    t1=time.time()
    print('yes:',interpreter)
    output = interpreter.get_tensor(output_details[0]["index"])[0]
    print(output)
    t2=time.time()
    print('time:',t2-t1)
    pred = torch.Tensor(output)
    prediction = output.argmax()
    #print(len(prediction))
    return prediction,pred
```

`import cv2
if __name__ == '__main__':

    converted_model = "kvp_converted_model_fp16.tflite"
    image_path = "kvp_test/test_1.png"
    seg_image_path="kvp_test/seg_test_1.png"
    #good_image_path = "datasets/experiment/good/g.png"
    img1 = cv2.imread(image_path)
    img2=cv2.imread(seg_image_path)
    #img = img[None, :, :, :]
    #resized=img
    resized_img = cv2.resize(img1, (608,608)).astype('float32')
    resized_seg_img = cv2.resize(img2, (608,608)).astype('float32')
    #resized=img.astype('float32')
    resized_img = resized_img / 255.
    resized_seg_img = resized_seg_img / 255.
    input_image = np.expand_dims(resized_img, axis=0)
    seg_image= np.expand_dims(resized_seg_img, axis=0)
    #print(test_img)
    image_data = np.concatenate([input_image,seg_image], axis = -1).astype(np.float32)
    y_inp = np.expand_dims(np.array([img1.shape[0], img1.shape[1]]), axis = 0).astype(np.float32)
    
    prediction,pred = run_tflite_model(converted_model,image_data,y_inp)
    print(pred)`

**Error**:
![gather](https://user-images.githubusercontent.com/25703066/195579619-36ab83cc-13d0-4223-b930-5920de2a367e.jpg)

**Comment by tiruk007** [comment]
@mohantym 
I was able to reproduce the  issue on Colab using TF v2.10. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/597b65d2dfde2f8c8ebef0a2668066e9/58085.ipynb) for reference.
Thank you!

**Comment by mohantym** [comment]
@divyajaincs !
Sorry for the late response. 

I changed the order of resizing-set_tensor-invoke to resolve the issue.

Could you check the required changes in this [gist ](https://colab.sandbox.google.com/gist/mohantym/881d108e26ad0714738ae3f65ba541e0/58085.ipynb#scrollTo=IdelZXDDlSbL)for reference.

Thank you!

**Comment by divyajaincs** [comment]
@mohantym when i'm testing with your updated code, colab session is crashing. any idea why this is happening?

**Comment by mohantym** [comment]
@divyajaincs !

You input size in lite model  is (608,608) so I resized the tensor input accordingly , But while using a low resolution image, it crashed the session.

Thank you!

**Comment by divyajaincs** [comment]
@mohantym I'm testing with original image size of (760,1000), with gpu it's working fine but with cpu it's crashing.

**Comment by mohantym** [comment]
ok @divyajaincs !

Thanks for the update. 
It is a bit strange though as I ran the above the code in a cpu-runtime only and it did not surface in my case.

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by pkgoogle** [comment]
Hi @divyajaincs, it seems like your model link is no longer working, can you respond with your updated model link? Thanks!
