### ISSUE TITLE
Nested call from a tf.function decorated method behaves differently on Tensorarray depending if nested method is also decorated

### ISSUE THREAD

**Issue by arishov1** [tensorflow/tensorflow#58096]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

Yes

### Current Behaviour?

```shell
When I am calling test method,in this method tensor_array_with_tf_dec variable has type of Tensor and tensor_array variable has type of TensorArray,so this method gets assertion error,but I think they should have the same type.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf


@tf.function
def return_tensor_array_with_tf_dec():
    ta = tf.TensorArray(tf.float32, size=0, dynamic_size=True, clear_after_read=True)
    return ta


def return_tensor_array():
    ta = tf.TensorArray(tf.float32, size=0, dynamic_size=True, clear_after_read=True)
    return ta


@tf.function
def test():
    tensor_array_with_tf_dec = return_tensor_array_with_tf_dec()
    tensor_array = return_tensor_array()
    assert type(tensor_array_with_tf_dec) == type(tensor_array)

test()
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@arishov1 
I tried an alternative approach. I was able to run the code without any error on Colab using TF v2.10. Please find the gist[here](https://colab.research.google.com/gist/tiruk007/79e6d5d2461925e9192eee06171c0b78/58096.ipynb) for reference.
Thank you!

**Comment by arishov1** [comment]
@tiruk007 Thank you for your suggestion, it works indeed.Nevertheless  I don't fully understand why my initial code doesn't work. Decorating a function call with tf.function and calling it from a tf.function-decorated method should result in the same tracing pattern, isn't it?

**Comment by tiruk007** [comment]
@arishov1 
I try to use attribute to get variable from function. Could you please refer to this [Better performance with tf.function](https://www.tensorflow.org/guide/function) & [Introduction to graphs and tf.function](https://www.tensorflow.org/guide/intro_to_graphs) and let us know if it helps.
Thank you!
