### ISSUE TITLE
How can I make the dataset accept sequences or matrices? PLZ :)

### ISSUE THREAD

**Issue by MinaAku** [tensorflow/tensorflow#58109]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

MACOS

### Python version

Python 3.9

### Current Behaviour?

```shell

- Thank you for your contributions to TensorFlow, your work is remarkable, you are great.

- I am accustomed to using dataframe to perform certain data cleaning work first, and then create a data set through the Dataset.from_tensor_slices() method, which is very efficient.
- Today I was working with a data containing sequences and matrices, and when I used the original method, I would get an error (ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type numpy.ndarray). I understand this is because the data types in my Dataframe is not one of Int, str or float, but some sequence or matrix. I will give the data head in Dataframe below.

- Limited by my code level, I still can't solve this problem after a long time of trying. I really want to be able to solve this problem, can anyone give me some pointers? Thank you very much!

```

### Standalone code to reproduce the issue

```shell
df.head()

         A                  B                     C                   D(target)
0   [2,3,4,5]      [[0.2,-0.1 ...]...]   [[0.3,1.1 ...]...]               1

1    [6,7,8]       [[0.2,-0.1 ...]...]   [[0.3,1.1 ...]...]               0 

2 [9,10,11,12,13]  [[0.2,-0.1 ...]...]   [[0.3,1.1 ...]...]               1
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@MinaAku 
Could you please refer to this document([tf.data: Build TensorFlow input pipelines](https://www.tensorflow.org/guide/data)) and let us know if it helps.
Thank you!

**Comment by MinaAku** [comment]
> @MinaAku
> Could you please refer to this document([tf.data: Build TensorFlow input pipelines](https://www.tensorflow.org/guide/data)) and let us know if it helps.
> Thank you!

Thanks for your reply! But I haven't solved the mass after refer document. (It's my fault T.T)

My case is that, I got some image matrix data and save it in a dataframe, how do I pass it into the dataset as a feature? Using "from_tensor_slices()" method will report "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type numpy.ndarray)." 

Thanks everyone for your help!

**Comment by tiruk007** [comment]
@MinaAku 
Could you please provide a code snippet to replicate the issue reported here.
Thank you!

**Comment by MinaAku** [comment]
> @MinaAku
> Could you please provide a code snippet to replicate the issue reported here.
> Thank you!

Thanks for your reply and patience! I've tried many things these days, but nothing works. You are my only hope now. :)

First, I am using a processed multimodal dataset with three features and a float label. The three features are text\audio\video, where text is represented by a 104-long integer sequence, and audio\video is represented by a float matrix.

Second, I have tried using the .astype method to adjust the types of the three feature columns, but failed. I'll show you this dataset using the .head() method.
The following is the process before the error is reported:

>In   [1]: train_df.dtypes
>Out[1]:
text      object
video     object
audio     object
label    float32
dtype: object

>In   [2]:train_df.head()
>Out[2]:
                                 text                               video                               audio                                                       label
0  [2, 3, 4, 5, 6, 0, 0, 0, 0, 0, ...  [[-1.991939, -1.5613043, 0.2240...  [[1.2337455, -1.2865584, -1.421...   2.40
1  [7, 8, 9, 10, 11, 6, 12, 13, 14...  [[2.3410914, 2.3050823, 1.06210...  [[0.35389948, 0.30429268, -0.11...  -0.80
2  [27, 28, 29, 10, 9, 13, 30, 31,...  [[0.8537923, -0.2358623, -0.155...  [[1.169397, 0.746589, -0.290762...  -1.00
3  [4, 32, 33, 13, 14, 0, 0, 0, 0,...  [[-1.8149365, -0.40606537, -1.4...  [[1.8315508, -0.11712463, -0.72...  -1.75
4  [15, 25, 10, 34, 28, 0, 0, 0, 0...  [[-1.0904845, 1.146731, 0.00874...  [[-0.2464511, 0.37285712, 0.144...   0.00

>In   [3]:train_label = train_df['label']
              train_feature = train_df[['text','audio','video']]
>Out[3]:

>In   [4]:
import tensorflow as tf
train_dataset = tf.data.Dataset.from_tensor_slices((train_feature, train_label))

Traceback (most recent call last):
  File "/Users/jawer/opt/miniconda3/envs/tensorflow29/lib/python3.9/site-packages/tensorflow/python/data/util/structure.py", line 102, in normalize_element
    spec = type_spec_from_value(t, use_fallback=False)
  File "/Users/jawer/opt/miniconda3/envs/tensorflow29/lib/python3.9/site-packages/tensorflow/python/data/util/structure.py", line 485, in type_spec_from_value
    raise TypeError("Could not build a `TypeSpec` for {} with type {}".format(
TypeError: Could not build a `TypeSpec` for                                     text                               audio                               video
0     [2, 3, 4, 5, 6, 0, 0, 0, 0, 0, ...  [[1.2337455, -1.2865584, -1.421...  [[-1.991939, -1.5613043, 0.2240...
1     [7, 8, 9, 10, 11, 6, 12, 13, 14...  [[0.35389948, 0.30429268, -0.11...  [[2.3410914, 2.3050823, 1.06210...
2     [27, 28, 29, 10, 9, 13, 30, 31,...  [[1.169397, 0.746589, -0.290762...  [[0.8537923, -0.2358623, -0.155...
3     [4, 32, 33, 13, 14, 0, 0, 0, 0,...  [[1.8315508, -0.11712463, -0.72...  [[-1.8149365, -0.40606537, -1.4...
4     [15, 25, 10, 34, 28, 0, 0, 0, 0...  [[-0.2464511, 0.37285712, 0.144...  [[-1.0904845, 1.146731, 0.00874...
                                  ...                                 ...                                 ...
1278  [306, 1363, 28, 1945, 4, 681, 3...  [[-0.002663397, -1.2971419, 2.5...  [[-0.09433063, -0.3597318, -1.3...
1279  [1625, 141, 63, 106, 270, 28, 1...  [[1.2584158, -2.3381844, -1.256...  [[-1.5783025, -0.40491882, 0.64...
1280  [2171, 32, 42, 11, 6, 0, 0, 0, ...  [[1.668467, -1.8740685, -1.1285...  [[-0.7878416, 1.9826996, 0.0788...
1281  [1769, 141, 462, 1610, 2172, 37...  [[0.10788689, -1.3585961, 2.241...  [[1.7500647, 1.4413257, 1.58184...
1282  [649, 141, 2008, 480, 306, 74, ...  [[0.17980516, -2.145652, -1.055...  [[0.40465018, 0.8532134, -1.254...
[1283 rows x 3 columns] with type DataFrame
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/jawer/opt/miniconda3/envs/tensorflow29/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-43-463f404e0b5c>", line 3, in <module>
    train_dataset = tf.data.Dataset.from_tensor_slices((train_feature, train_label))
  File "/Users/jawer/opt/miniconda3/envs/tensorflow29/lib/python3.9/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 809, in from_tensor_slices
    return TensorSliceDataset(tensors, name=name)
  File "/Users/jawer/opt/miniconda3/envs/tensorflow29/lib/python3.9/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4551, in __init__
    element = structure.normalize_element(element)
  File "/Users/jawer/opt/miniconda3/envs/tensorflow29/lib/python3.9/site-packages/tensorflow/python/data/util/structure.py", line 107, in normalize_element
    ops.convert_to_tensor(t, name="component_%d" % i))
  File "/Users/jawer/opt/miniconda3/envs/tensorflow29/lib/python3.9/site-packages/tensorflow/python/profiler/trace.py", line 183, in wrapped
    return func(*args, **kwargs)
  File "/Users/jawer/opt/miniconda3/envs/tensorflow29/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 1640, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/jawer/opt/miniconda3/envs/tensorflow29/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 343, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/Users/jawer/opt/miniconda3/envs/tensorflow29/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 267, in constant
    return _constant_impl(value, dtype, shape, name, verify_shape=False,
  File "/Users/jawer/opt/miniconda3/envs/tensorflow29/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 279, in _constant_impl
    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)
  File "/Users/jawer/opt/miniconda3/envs/tensorflow29/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 304, in _constant_eager_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/Users/jawer/opt/miniconda3/envs/tensorflow29/lib/python3.9/site-packages/tensorflow/python/framework/constant_op.py", line 102, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type numpy.ndarray).


Thank you for your help!

**Comment by aaudiber** [comment]
Hi @MinaAku. This doc explains how to use dataframes with tf.data: https://www.tensorflow.org/tutorials/load_data/pandas_dataframe#a_dataframe_as_a_dictionary. The idea is to cast your dataframe as a `dict` before using `from_tensor_slices`.

**Comment by sushreebarsa** [comment]
@MinaAku Could you please refer to the comment above and let us know?
Thank you!
