### ISSUE TITLE
i trained custom pose classification model but its giving error at the time of inference

### ISSUE THREAD

**Issue by akashAD98** [tensorflow/tensorflow#58101]
im using windows 10 system
getting this error, i followed the official blog of Tensorflow 
https://www.tensorflow.org/lite/tutorials/pose_classification  for model training  

this blog hasn't provided inference script
so I tried official https://github.com/tensorflow/examples/tree/master/lite/examples/pose_estimation/raspberry_pi for .tflite inference but getting isse

```Cannot set tensor: Got value of type FLOAT32 but expected type UINT8 for input 0, name: serving_default_input:0```

**Comment by mohantym** [comment]
Hi @akashAD98 !
Sorry for the late response.

You can set inference input and output as float32 as a work around.

```
converter.inference_input_type = tf.float32
converter.inference_output_type = tf.float32
```

[Ref](https://www.tensorflow.org/lite/performance/post_training_integer_quant#convert_using_integer-only_quantization).

Detailed usage can be found [here](https://www.tensorflow.org/lite/tutorials/pose_classification).

Thank you!
