### ISSUE TITLE
Some questions about the converted tflite model

### ISSUE THREAD

**Issue by wwdok** [tensorflow/tensorflow#58119]
Hi, I can successfully convert model to tflite model, i just have some quesitons about the converted model.
1. The conversion log has `fully_quantize: 0, inference_type: 6, input_inference_type: 3, output_inference_type: 3`, What do these numbers (0, 6, 3) mean ?
2. Can we determine the order of model output head or how tflite determine the order of model output head ? Imagine the model have two output heads: `cls-head` and `reg-head`, I find the converted float16 and float 32 model is `cls-head` **first** `reg-head` second, but the converted uint8 model is `reg-head` **first** `cls-head` second.
3. I find the precision metric of uint8 model is better than int8 model, is there any "scientific sense" behind this ?

**Comment by mohantym** [comment]
Hi @wwdok !

Sorry for the late response. 
Full_quantize:0 ( Model is not fully quantized) , It stays  0 or 1 in output 

I deducting the inference below parameter based on these [mappings](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/convert.py#:~:text=mapping%20%3D%20%7B,.COMPLEX128%2C) from converter.py.

> input_inference_type: 3 ( int8 type quantized)
> output_inference_type:3 (int8 type quantized)
> inference_type: 6  ( integer quantized) 

If you want to enforce the inference input and output type to int8/uint8 on the respective output heads. you can use representative dataset with  [post training integer quantization](https://www.tensorflow.org/lite/performance/post_training_integer_quant) syntax .

```

 converter.inference_input_type = tf.uint8      # tf.int8
 converter.inference_output_type = tf.uint8    #tf.int8

```
Logic behind higher precision metric in uint8 might be higher range (including negative mirror numbers compared to int8 range).

Does this answer above query.

Thank you!

**Comment by mohantym** [comment]
Ok @wwdok !
Sorry ! I forgot about the second question.  We can set the order of output by using[ signatures](https://www.tensorflow.org/lite/guide/signatures) in model itself.

Can you post in [TFForum](https://discuss.tensorflow.org/) for further queries.

Thank you!
