### ISSUE TITLE
while processing Pruning by using Densely connected Layer...

### ISSUE THREAD

**Issue by Lee-junseok1025** [tensorflow/tensorflow#58114]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf.2.9.1

### Custom Code

Yes

### OS Platform and Distribution

window, jupyter Lab

### Python version

.3.9

### Current Behaviour?

```shell
I'm trying to bring in the model and proceed with pruning and weight sharing, but I get an error saying  `ValueError: A merge layer should be called on a list of inputs. Received: inputs=Tensor("Placeholder:0", shape=(None, 64), dtype=float32) (not a list of tensors)`
```

### Standalone code to reproduce the issue

```shell
# weight sharing

cluster = tfmot.clustering.keras.cluster_weights

centeroid = tfmot.clustering.keras.CentroidInitialization

cluster_params = {
    'number_of_clusters' : 16,
    'cluster_centroids_init' : centeroid.LINEAR
}

cluster_model = cluster(model,**cluster_params) # Error!
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@Lee-junseok1025 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. 

Thank you!
