### ISSUE TITLE
Android (Kotlin) In Pose detection when I use front camera it display opposite mirror how to resolve it.

### ISSUE THREAD

**Issue by IBSApple** [tensorflow/tensorflow#58117]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

a

### Custom Code

No

### Current Behaviour?

```shell
facing front camera issue in Android kotlin, it's display mirror in camera. How to resolve this issue.
```

### Standalone code to reproduce the issue

```shell
facing front camera issue in Android kotlin, it's display mirror in camera. How to resolve this issue.
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @IBSApple !
Thanks for bringing it up again. This issue is probably duplicate to #58117 and #56178 though.

Could you close this issue as duplicate to them. I will post my findings in #56178 when I get some pointers from Team.

Thank you!
