### ISSUE TITLE
Make EIGEN_MAX_ALIGN_BYTES available from C API

### ISSUE THREAD

**Issue by zmughal** [tensorflow/tensorflow#58112]
### Issue Type

Feature Request

### Source

source

### Tensorflow Version

tf 2.10.0

### Custom Code

No

### OS Platform and Distribution

Linux

### Mobile device

N/A

### Python version

N/A

### Bazel version

5.3.0

### GCC/Compiler version

GCC 12

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### Current Behaviour?

Is there a way to access `EIGEN_MAX_ALIGN_BYTES` from C at runtime (e.g., for use via FFI)?

I am asking because I would like to manage the memory passed in to `TF_NewTensor()` myself (for sharing between libraries), but if `data` is not aligned, it uses `memcpy()` and calls the deallocator. I can use this information to figure out the value of `EIGEN_MAX_ALIGN_BYTES` myself, but it would be nice to not have to do this.

This request is similar to <https://github.com/tensorflow/tensorflow/issues/9690> and Python's `tf.sysconfig.get_compile_flags()`.

### Standalone code to reproduce the issue

```shell
N/A
```

**Comment by tilakrayal** [comment]
@zmughal,
Could you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thank you!

**Comment by zmughal** [comment]
Here is some Perl code that allocates both aligned-to-64-bytes and non-64-byte-aligned memory for a `TF_Tensor` via FFI to `libtensorflow`'s `TF_NewTensor` function:

```perl
#!/usr/bin/env perl

use lib 'lib';
use feature qw(say);
use AI::TensorFlow::Libtensorflow;
use AI::TensorFlow::Libtensorflow::DataType qw(FLOAT);
use AI::TensorFlow::Libtensorflow::Lib qw(arg);
use FFI::Platypus::Memory qw(malloc free);
use List::Util qw(product);

sub main {
	my $ffi = AI::TensorFlow::Libtensorflow::Lib->ffi;
	my $NewTensor = $ffi->function( NewTensor =>
		[
			arg 'TF_DataType' => 'dtype',

			# const int64_t* dims, int num_dims
			arg 'tf_dims_buffer'   => [ qw(dims num_dims) ],

			# void* data, size_t len
			arg 'opaque' => [ qw(data) ],
			arg 'size_t' => [ qw(len) ],

			arg 'opaque'      => 'deallocator',  # tensor_deallocator_t (deallocator)
			arg 'opaque'      => 'deallocator_arg',
		],
		=> 'TF_Tensor' => sub {
			my ($xs,
				$dtype, $dims, $data, $len,
				$deallocator, $deallocator_arg,
			) = @_;
			my $deallocator_closure = $ffi->closure( $deallocator );
			$deallocator_closure->sticky;
			my $deallocator_ptr = $ffi->cast(
				'tensor_deallocator_t', 'opaque',
				$deallocator_closure );

			my $obj = $xs->(
				$dtype,
				$dims,
				$data, $len,
				$deallocator_ptr, $deallocator_arg,
			);

			$obj->{_deallocator_closure} = $deallocator_closure;

			$obj;
		});

	my $alignment = 64;

	my @dims = (16, 16);
	my $tensor_bytes = product(FLOAT->Size, @dims);
	my $data_ptr = malloc( $alignment + $tensor_bytes );

	my ($non_aligned_ptr, $aligned_ptr) =
		$data_ptr % $alignment == 0
		? ( $data_ptr + $alignment / 2, $data_ptr)
		: ( $data_ptr, $data_ptr + ($alignment - $data_ptr % $alignment) );

	my $deallocated = 0;
	my $t_nonaligned = $NewTensor->( FLOAT, \@dims,
		$non_aligned_ptr, $tensor_bytes,
		sub {
			$deallocated = 1;
			say "Deallocated non-aligned data";
		}
	);

	say "t_nonaligned was @{[ $deallocated ? '' : 'NOT ' ]}deallocated on construction";

	$deallocated = 0;
	my $t_aligned = $NewTensor->( FLOAT, \@dims,
		$aligned_ptr, $tensor_bytes,
		sub {
			$deallocated = 1;
			say "Deallocated aligned data";
		}
	);

	say "t_aligned was @{[ $deallocated ? '' : 'NOT ' ]}deallocated on construction";

	free($data_ptr);
}

main;
```

When it is run, the output is:

```
Deallocated non-aligned data
t_nonaligned was deallocated on construction
t_aligned was NOT deallocated on construction
Deallocated aligned data
```

The deallocator callback is being called on the non-aligned-to-64-bytes data [inside of the condition at](https://github.com/tensorflow/tensorflow/blob/v2.10.0/tensorflow/c/tf_tensor.cc#L105-L122):

https://github.com/tensorflow/tensorflow/blob/359c3cdfc5fabac82b3c70b3b6de2b0a8c16874f/tensorflow/c/tf_tensor.cc#L105-L122

---

The reason I would like this feature is so that I can use it to allocate memory that is managed outside of the `libtensorflow` (i.e., I want to use the branch where the buffer is `/*owns_memory=*/false`).

To do this right now, I would have to know the value of `EIGEN_MAX_ALIGN_BYTES` (in this example, `$alignment = 64`) which is not exposed.

**Comment by zmughal** [comment]
@qqfish, apologies for tagging you. I'm looking for somebody who can look at this issue.

I have a workaround where I probe the library for the alignment by using various offsets, but I would appreciate a cleaner solution.

**Comment by cantonios** [comment]
The alignment is currently always 64, necessary for compatibility with aligned AVX512 instructions.  This is hard-coded in the TF build: https://github.com/tensorflow/tensorflow/blob/f12154def538a7093598c870be9dbb374b86bbe3/third_party/eigen3/eigen_archive.BUILD#L42
