### ISSUE TITLE
The distribution package in pypi does not match the official tensorflow website.

### ISSUE THREAD

**Issue by S-O294** [tensorflow/tensorflow#58115]
As you can see in the image below, tensorflow-1.15.0 requires python version 2.7,3.3-3.7, while pypi only has python version 2.7,3.5-3.7 packages on its website.Did you forget to upload the appropriate version,how can I install tensorflow-1.15.0 by pip on python3.4？

<img width="577" alt="图片1" src="https://user-images.githubusercontent.com/60139005/196108404-d4b8cb1b-d0e8-426a-80eb-bf641a249f95.png">

![图片2](https://user-images.githubusercontent.com/60139005/196108846-a17a75ec-b0ec-4047-83c9-cd8145873b27.png)

**Comment by mihaimaruseac** [comment]
TF 1.15 is no longer supported

**Comment by tilakrayal** [comment]
@S-O294,
As mentioned, Tensorflow version 1.x is not supported. Hence, kindly update to the latest stable version 2.10 and let us know if you are facing the same issue. Thank you!

**Comment by S-O294** [comment]
@mihaimaruseac @tilakrayal We are conducting compatibility testing on deep learning frameworks, thank you very much for your response.

**Comment by tilakrayal** [comment]
@S-O294,
Please try to test on latest stable v2.10 and let us know if you are facing the same issue. Thank you!
