### ISSUE TITLE
tf.nn.local_response_normalization lack validation for depth_radius on cpu

### ISSUE THREAD

**Issue by fuzzyswan** [tensorflow/tensorflow#58122]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Current Behaviour?

```shell
tf.nn.local_response_normalization lack validation for depth_radius on cpu. depth_radius needs to be an integer as it is the half-width of the 1-D normalization window. However, on cpu it accepts value `0.1`. By contrast, on gpu it can throw error: `requires depth_radius in [1, 7]`.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
input = tf.constant([[[[1.0, 2.0, 3.0, 4.0], [5.0, 6.0, 7.0, 8.0], [9.0, 10.0, 11.0, 12.0], [13.0, 14.0, 15.0, 16.0]]]])
depth_radius = 0.1
bias = 1.0
alpha = 0.5
beta = 0.5
with tf.device("cpu"):
    output = tf.nn.local_response_normalization(input=input, depth_radius=depth_radius, bias=bias, alpha=alpha, beta=beta)
    print(output) # pass

with tf.device("gpu"):
    output = tf.nn.local_response_normalization(input=input, depth_radius=depth_radius, bias=bias, alpha=alpha, beta=beta)
    print(output) # error
```

### Relevant log output

```shell
tf.Tensor(
[[[[0.8164966 1.1547005 1.2792044 1.3333334]
   [1.3608277 1.3764944 1.3862065 1.3926213]
   [1.3970708 1.40028   1.4026688 1.4044938]
   [1.405919  1.4070529 1.4079696 1.4087214]]]], shape=(1, 1, 4, 4), dtype=float32)
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__LRN_device_/job:localhost/replica:0/task:0/device:GPU:0}} cuDNN requires depth_radius in [1, 7], got: 0 [Op:LRN]
```
</details>

**Comment by tilakrayal** [comment]
@fuzzyswan,
I tried to execute the code with the alternative approach by providing the int for depth_radius and it is executing without any error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/fbe080cda9b10ef436ea7b2de668b32f/untitled694.ipynb).

Also please take a look at the office doc link for the reference. Thank you!

depth_radius | An optional int. Defaults to 5. 0-D. Half-width of the 1-D normalization window
-- | --

**Comment by fuzzyswan** [comment]
Hi @tilakrayal , 
indeed `depth_radius` should be int according to documentation, however, input validity checking is missing on CPU and causing inconsistent behaviour on CPU and on GPU. Specifically, CPU accepts `0.1` which is not an integer, but GPU will not accept it. I think if the argument `depth_radius` has to be an integer, then on CPU the API should do proper checking to avoid API misuse.

**Comment by tilakrayal** [comment]
@fuzzyswan,
Could you please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/56849#issuecomment-1204275739) from the developer where it was mentioned that CPU and GPU gradients return different results if you pass invalid values to the output_image value. output_image must be the correct forward-pass output given the input_image, and if you pass an invalid value for output_image, the op has no well-defined semantics and let us know if this comment serves the purpose. Thank you!

**Comment by fuzzyswan** [comment]
hi @tilakrayal 
I checked the issue you pointed but I think the problem I reported here is not related to gradient computation. Here, the problem is the lack of input validity checking in the forward pass. A simple data type check would help to reject invalid floating `depth_radius`, and no value validity checking is needed (which I assume would be costly).

**Comment by tilakrayal** [comment]
@sushreebarsa,
I was able to reproduce the issue on tensorflow v2.10 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3660292fada1f13b65f92981fe928fb1/untitled736.ipynb).

**Comment by sachinprasadhs** [comment]
Hi, Thanks for reporting the issue.
for CPU, for the argument `depth_radius`, we make conversion of given dtype to `int` using the function below.
https://github.com/tensorflow/tensorflow/blob/8b82a3001153f04fac08b6aa94d5cfbff45bdba0/tensorflow/python/eager/execute.py#L155-L164
So the `depth_radius` value `0.1` will become `0`, and the result is as expected. Thanks!
