### ISSUE TITLE
TF Lite CMake Failes to Download neon2sse on Windows

### ISSUE THREAD

**Issue by nathanmartz** [tensorflow/tensorflow#58126]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.8.0

### Custom Code

No

### OS Platform and Distribution

Windows

### Python version

3.8

### Current Behaviour?

```shell
When building TF Lite from Source via CMake on Windows, the download of neon2sse from storageapis.google.com (defined in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/cmake/modules/neon2sse.cmake)  fails with an SSL error (see log output below).

This failure appears to be specific to Windows, and reproduces in CMake 3.21 and 3.24 (latest stable), which suggests something changed in the googleapis endpoint. Changing the download from https to http works around the issue.
```

### Standalone code to reproduce the issue

```shell
Build TF Lite from source on Windows
```

### Relevant log output

```shell
status_code: 35
            status_string: "SSL connect error"
            log:
            --- LOG BEGIN ---
            timeout on name lookup is not supported
      Trying 64.233.181.128:443...
  
    Connected to storage.googleapis.com (64.233.181.128) port 443 (#0)
  
    schannel: ALPN, offering h2
  
    schannel: ALPN, offering http/1.1
  
    schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE
    (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is
    received (e.g.  handshake failed).  More detail may be available in the
    Windows System event log.
  
    Closing connection 0
  
    schannel: shutting down SSL/TLS connection with storage.googleapis.com port
    443
```
</details>

**Comment by mohantym** [comment]
Hi @nathanmartz ! 
I just checked with Master branch with CMake GUI (V 3.24.2) on my windows machine. Build was successful with some dev warnings.

Could you check against 2.10 or Master branch with Default native  compiler and let us know.

Thank you!

**Comment by nathanmartz** [comment]
I'm no longer able to reproduce, so this appears to be a transient issue on google storage apis. Thanks for taking a look.

**Comment by nathanmartz** [comment]
I actually got this error again today, though it's surprisingly hard to repro.

**Comment by pkgoogle** [comment]
Hi @nathanmartz, we believe this is a transitory issue in your environment as we do not encounter it. If you believe it is resolved now please feel free to close the issue.

**Comment by nathanmartz** [comment]
Seems that way. Closing.
