### ISSUE TITLE
Inconsistent behavior of gpu /cpu/numpy in int32 casting 

### ISSUE THREAD

**Issue by creakseek** [tensorflow/tensorflow#58127]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Current Behaviour?

```shell
`tf.cast(nan, tf.int32)` has inconsistent behaviour on gpu and cpu:
- on cpu: -9223372036854775808, same as numpy
- on gpu: 0

related issue: https://github.com/tensorflow/tensorflow/issues/57883
```

### Standalone code to reproduce the issue

```shell
# For int64 casting, only gpu produces 0
with tf.device('cpu'):
    print(tf.cast(np.nan, np.int32)) 
with tf.device('gpu'):
    print(tf.cast(np.nan, np.int32))
print(np.array(np.nan).astype(np.int32))

# For int64 casting, all results are consistent -9223372036854775808
with tf.device('cpu'):
    print(tf.cast(np.nan, np.int64))
with tf.device('gpu'):
    print(tf.cast(np.nan, np.int64))
print(np.array(np.nan).astype(np.int64))
```

### Relevant log output

```shell
tf.Tensor(-2147483648, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
-2147483648
tf.Tensor(-9223372036854775808, shape=(), dtype=int64)
tf.Tensor(-9223372036854775808, shape=(), dtype=int64)
-9223372036854775808
```
</details>

**Comment by tiruk007** [comment]
@sushreebarsa 
I was able to reproduce the issue on Colab using  TF v2.10. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/3c0438a1b2966ce1ab7e7e5a2dfd1e25/58127.ipynb) for reference.
Thank you!

**Comment by SuryanarayanaY** [comment]
I tried with nightly version and observed same behaviour.please refer nightly [gist](https://colab.research.google.com/gist/SuryanarayanaY/f26dc6f9e74285eeac414df2595058c4/58127-nightly.ipynb).

Also i have tested `tf.math.is_nan([0.])` on both CPU and GPU and both producing `False` as output where as `tf.cast(np.nan, np.int32)` on GPU producing `0` which is the conflict here.

But when i tested `tf.math.is_nan([0])` (observe `0`  as not float here ) getting error as below:
```

 InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double
; NodeDef: {{node IsNan}}; Op<name=IsNan; signature=x:T -> y:bool; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE]> [Op:IsNan]

```
The same can be observed in the gist.
@creakseek do you feel there is any relation with this error to that of GPU behaviour with `tf.cast(np.nan, np.int32)` op ?

**Comment by creakseek** [comment]
hi @SuryanarayanaY, thanks for the reply and sorry for the delayed reply.

> It is recommended to use [tf.convert_to_tensor](https://www.tensorflow.org/api_docs/python/tf/convert_to_tensor) instead of [tf.cast](https://www.tensorflow.org/api_docs/python/tf/cast) for any non-tensor inputs.

Indeed the results are consistent on both CPU & GPU with tensor inputs. From my understanding, if `tf.cast` is likely to produce wrong outputs for non-tensor inputs, wouldn't it be better to raise an exception and reject such non-tensor inputs? "recommend to use“ seems misleading because it suggests that `tf.cast` still works correctly, just not preferable.
