### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.train' has no attribute 'summary_iterator'

### ISSUE THREAD

**Issue by khengyun** [tensorflow/tensorflow#58134]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

window 11 22h

### Python version

3.10

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
this is my code 

import tensorflow as tf

for e in tf.train.summary_iterator("events.out.tfevents.1665558822.NIRAN.13044.0"):
    for v in e.summary.value:
        if v.tag == 'loss' or v.tag == 'accuracy':
            print(v.simple_value)

where i got the code : https://docs.w3cub.com/tensorflow~python/tf/train/summary_iterator
it like the same on this web. but i dont know why it error. i not found this error on internet
```

### Relevant log output

```shell
AttributeError: module 'tensorflow._api.v2.train' has no attribute 'summary_iterator'
```
</details>

**Comment by tiruk007** [comment]
@khengyun 
Try to use 'tf.compat.v1.train.summary_iterator' instead of 'tf.train.summary_iterator'. I was able to run the given code snippet without any error on colab using TF v2.9. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/b4f9b35a4c9c0b2d38b10f551e414411/58134.ipynb) for reference and refer to the this documents ( [tf.compat](https://www.tensorflow.org/api_docs/python/tf/compat) & [tf.compat.v1.train.summary_iterator](https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/summary_iterator) ) 

Thank you!

**Comment by nikhil1111111** [comment]
> @khengyun Try to use 'tf.compat.v1.train.summary_iterator' instead of 'tf.train.summary_iterator'. I was able to run the given code snippet without any error on colab using TF v2.9. Could you please refer to the this documents ( [tf.compat](https://www.tensorflow.org/api_docs/python/tf/compat) & [tf.compat.v1.train.summary_iterator](https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/summary_iterator) ) and find the gist [here](https://colab.research.google.com/gist/tiruk007/b4f9b35a4c9c0b2d38b10f551e414411/58134.ipynb) for reference.
> 
> Thank you!
> Thank you buddy!!

**Comment by nikhil1111111** [comment]
> @khengyun Try to use 'tf.compat.v1.train.summary_iterator' instead of 'tf.train.summary_iterator'. I was able to run the given code snippet without any error on colab using TF v2.9. Could you please refer to the this documents ( [tf.compat](https://www.tensorflow.org/api_docs/python/tf/compat) & [tf.compat.v1.train.summary_iterator](https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/summary_iterator) ) and find the gist [here](https://colab.research.google.com/gist/tiruk007/b4f9b35a4c9c0b2d38b10f551e414411/58134.ipynb) for reference.
> 
> Thank you!

Thank you buddy !!
