### ISSUE TITLE
zeta gives inconsistent results with scipy

### ISSUE THREAD

**Issue by fuzzyswan** [tensorflow/tensorflow#58139]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Current Behaviour?

```shell
`tf.math.zeta` gives inconsistent results with numpy:
- on CPU: gives -148382460000000.0
- on GPU: gives 52.117622
- scipy: gives 74.58897854509347
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
x = 5.
q = -9.59183673
with tf.device('gpu'):
    print(tf.math.zeta(x=x, q=q)) # gives 52.117622
with tf.device('cpu'): 
    print(tf.math.zeta(x=x, q=q)) # gives -148382460000000.0
from scipy.special import zeta
print(zeta(x,q=q)) # gives 74.58897854509347
```

### Relevant log output

```shell
tf.Tensor(52.117622, shape=(), dtype=float32)
tf.Tensor(-148382460000000.0, shape=(), dtype=float32)
74.58897854509347
```
</details>

**Comment by tiruk007** [comment]
@sushreebarsa 
I was able to reproduce the issue on colab using TF v2.10. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/782d7243333ed69cd2ff1dff85c0e7d1/58139.ipynb) for reference.

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @fuzzyswan ,

I tried the same code with `tf.float64` arguments and observed drastic change in behaviour of CPU.With `tf.float64` both `tf.device('CPU')` and `Scipy` both producing same result as `74.58897854509347 ` compared to earlier result of  `-148382460000000.0` vs `74.58897854509347 `. Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/c9e867b569237b1fbf8c91f7ebd39c37/58139_r1.ipynb).

Is it possible that Scipy might be using `float64` as default dtype?
