### ISSUE TITLE
XLA compiler error: left_branch_shape.rank() == right_branch_shape.rank()

### ISSUE THREAD

**Issue by JustASquid** [tensorflow/tensorflow#58135]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Windows 10

### Python version

3.9

### CUDA/cuDNN version

cudatoolkit=11.2 cudnn=8.1.0

### GPU model and memory

GTX 1080 TI

### Current Behaviour?

XLA compiler error for this model when `jit_compile=True`

It's very hard to determine the cause of the error, as the model works fine when running normally.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np


class Chooser(tf.keras.layers.Layer):
    @tf.function
    def call(self, options_input, choices_input_logits):
        choices = tf.nn.softmax(choices_input_logits, axis=2)

        result = tf.linalg.matmul(choices, options_input)
        return result

def get_model():
    options_input = tf.keras.layers.Input(shape=(10,3), name="options")
    choices_input = tf.keras.layers.Input(shape=(5,10), name="choices")

    net = Chooser()(options_input, choices_input)
    net = tf.keras.layers.Flatten()(net)
    net = tf.keras.layers.Dense(1)(net)

    return tf.keras.Model([options_input, choices_input], net)

model = get_model()
model.compile(
    optimizer=tf.keras.optimizers.Adam(0.001),
    loss=tf.keras.losses.MeanAbsoluteError(),
    jit_compile=True
)

def batch_gen():
    while True:
        o = np.random.uniform(low=-1.0, high=1.0, size=(10, 3))
        c = np.random.uniform(low=0.0, high=1.0, size=(5, 10))

        y = 1

        yield {"options": o, "choices": c}, y

dataset = tf.data.Dataset.from_generator(batch_gen, output_types=({"options": tf.float32, "choices": tf.float32}, tf.float32))
dataset = dataset.batch(32)

model.fit(dataset, steps_per_epoch=100, epochs=1)
```

### Relevant log output

```shell
tensorflow/compiler/xla/client/lib/dynamic_shaped_ops.cc:92] Check failed: left_branch_shape.rank() == right_branch_shape.rank() (1 vs. 2)left rank of (1) vs. right rank of (2)
```
</details>

**Comment by mohantym** [comment]
Hi @JustASquid !

Proper way to use XLA with tf.function is enable

>  jit_compile=True 

with tf.function.

Attached resolved [gist ](https://colab.sandbox.google.com/gist/mohantym/2ed4a4568fb7e275030946c24fe7de58/git_58135.ipynb#scrollTo=BKTbS80fOhFm)for reference.

Thank you!

**Comment by JustASquid** [comment]
@mohantym I want to XLA compile the entire model, not just the custom layer. setting `jit_compile=True` on the `@tf.function` while still using `jit_compile=True` on the model compilation results in the same error.

**Comment by mohantym** [comment]
@JustASquid !

You can use XLA-Autoclustering if you want to use XLA on entire model.
Attached [gist](https://colab.sandbox.google.com/gist/mohantym/bc38e2d95f6799868fe6ff1ec5085143/git_58135.ipynb#scrollTo=K2OCMqeuPlNT) for reference.

Thank you!

**Comment by JustASquid** [comment]
Thank you @mohantym 

Is there any reason/documentation why `tf.config.optimizer.set_jit(True)` works here, but `jit_compile=True` in `model.compile()` does not?
