### ISSUE TITLE
Increased memory usage while loading model graph  and observed a drop in performance throughput , When upgrade from TF version 2.8.0 to  either 2.8.1 or 2.9.1

### ISSUE THREAD

**Issue by rrajkumar1990** [tensorflow/tensorflow#58140]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

2.9.1 , 2.8.1

### Custom Code

Yes

### OS Platform and Distribution

Red Hat Enterprise Linux release 8.6 (Ootpa)

### Python version

3.8

### Current Behaviour?

```shell
we have a docker container with memory 1.5GB  where  we load our Custom RetinaNet Model and use it for inference.
We were using the Tensorflow version 2.8.0 and everything was working fine. 

Due to the vulnerabilities ,  we  tried upgrading to Minor version 2.9.1. But we are getting SIGKILL - out of memory error during the load of the model graph. When checked the Docker stats, we could see that the memory usage is crossing the existing 1.5GB.  There is no other code changes other than the version upgrade.

After increasing the pod memory to 4GB we are able to load the model graph and get the inference. The same behaviour is seen when we try to upgrade version 2.8.1 as well.

We also see the  time taken for inference has increased about 40% when we upgrade the version from 2.8 to 2.9.1

```

### Standalone code to reproduce the issue

```shell
1) Load a Retinanet Model  with Tensorflow version 2.8.0 in a docker container with memory 1.5GB
2) Load the same Retinanet model with Tensorflow version 2.8.1/2.9.1  in a docker container with the  memory 1.5GB
3) Load the same Retinanet model with Tensorflow version 2.8.1/2.9.1  in a docker container with the  memory 4GB

In this case you can see that the step1 will succeed and in step2 it will crash due to out of memory. Step3 will succeed.
```

### Relevant log output

```shell
2022-10-12 00:33:08.206766: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
2022-10-12 00:33:08.894968: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 28753920 exceeds 10% of free system memory.
2022-10-12 00:33:09.311896: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 28753920 exceeds 10% of free system memory.
2022-10-12 00:33:12.049115: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 28753920 exceeds 10% of free system memory.
2022-10-12 00:33:12.279661: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 28753920 exceeds 10% of free system memory.
2022-10-12 00:33:13.079146: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 28753920 exceeds 10% of free system memory.
2022-10-12 00:33:16,694 INFO reaped unknown pid 8697 (exit status 0)
Process 'ForkPoolWorker-1' pid:133 exited with 'signal 9 (SIGKILL)'
```
</details>

**Comment by mohantym** [comment]
Hi @rrajkumar1990 !
Can you attach the model loading code snippet too.
Thank you!

**Comment by rrajkumar1990** [comment]
Hi @mohantym ,

We have a frozen model file "model.pb" .  we load it by :
 


 with tf.io.gfile.GFile('model.pb', 'rb') as f:
                graph_def = tf.compat.v1.GraphDef()
                graph_def.ParseFromString(f.read())

            # we load the graph_def in the default graph

  with tf.Graph().as_default() as graph:
              tf.import_graph_def(graph_def,
                                  input_map=None,
                                  return_elements=None,
                                  name="",
                                  op_dict=None,
                                  producer_op_list=None)

##after loading we  try to get tensor by name 

graph = model_graph.graph_frozen
img = graph.get_tensor_by_name("input_img:0")

#exactly when the "get_tesnor_by_name" is called we get the memory error. 

This issue happened only with TF version 2.9.1 or 2.8.1 with 1.5GB . With TF version 2.8.0 able to load the graph and get predictions

**Comment by mohantym** [comment]
Ok @rrajkumar1990 !
Thanks for the update. Would test with a sample frozen graph model and update.
Feel free to test the loading time in 2.10/nighty version too.
Thank you!

**Comment by rrajkumar1990** [comment]
@mohantym , Wanted to try using a stable version, but nightly will have everyday updates rite?

**Comment by mohantym** [comment]
@rrajkumar1990 !
Yeah! Nightly version are updated on daily basis. 
Did you check against 2.10 version lately?
Thank you!

**Comment by rrajkumar1990** [comment]
@mohantym no I haven't tried yet in nightly version , as I want to run in some stable version .
where you able to replicate the issue  in 2.8.1 or 2.9.1?

**Comment by mohantym** [comment]
Sorry @rrajkumar1990 !

Actually, I could not find a  sample .pb from in time to replicate this issue. It have been great if you provide the .pb model and code snippets in a colab gist.

My thought was as  if you are using 1.x version format( .pb)  of models, It will throw compatibility issues while replicating in 2.x version.  So, It is better to recreate and save the model using[ tf.saved_model.save](https://www.tensorflow.org/api_docs/python/tf/saved_model/save) api to get expected results.

@SuryanarayanaY !
Could you look at this issue. 

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @rrajkumar1990 ,

From the error log  as we can see `MLIR V1 optimization pass is not enabled`  as the API  `tf.config.experimental.enable_mlir_graph_optimization` is under development. 

Could you please spare some time to refer the attached [TF Forum](https://discuss.tensorflow.org/t/none-of-the-mlir-optimization-passes-are-enabled/2247/18) link regarding similar issue and please let us know if they works for your case.

Thankyou!

**Comment by rrajkumar1990** [comment]
Hi @SuryanarayanaY ,

I don't think so the memory consumption changes are due to the "MLIR V1 optimization". I remember trying that and still  the pod memory consumption was more in 2.8.1 and 2.9.1. Could you try the steps I have mentioned and let me know

**Comment by SuryanarayanaY** [comment]
Hi @rrajkumar1990 ,

Thanks for quick response.Could you please confirm whether with 2.8v you are getting any logs like those you attached above ?
Is the behaviour tested on latest stable version 2.10 v ? Could you please test and share the logs if any ?

Also could you please share the model graph so that we can try to replicate the problem.

Thankyou!

**Comment by rrajkumar1990** [comment]
Hi @SuryanarayanaY , can you try Retinanet weights from here https://github.com/tensorflow/models/blob/master/official/vision/MODEL_GARDEN.md and try saving it to a .pb file and load it as how I have mentioned above.

**Comment by rrajkumar1990** [comment]
Hi @SuryanarayanaY / @mohantym - were you able to try and replicate? 
Thanks

**Comment by SuryanarayanaY** [comment]
@rrajkumar1990 ,

Sorry for delay.Could you please share exact link from where to download the weights as your attached link in above [comment](https://github.com/tensorflow/tensorflow/issues/58140#issuecomment-1311916555) have so many models with config and ckpt (checkpoint) files.The ckpt file has already saved_model.pb file.Are you using the same file? Please provide exact link for model also confirm which file you are using to convert into Graph?

Also I have doubt why you are using TF 1.x version when TF 2.x is available with pretrained models with much Easier and flexible API to handle Transfer learning?

**Comment by rrajkumar1990** [comment]
@SuryanarayanaY , 
Yesterday I tired with the new 2.10.1 version. Seems like the memory consumption is even higher now.

with 2.8 => I was able to get inference with my container memory as 1.5Gb . 
with 2.9.1 => 1.5GB failed wasn't enough as the memory consumption during the Inference  increased to 3.4 , so my container memory I had increased to 4GB
with 2.10.1 => The memory consumption during inference is 3.76GB

This  memory during loading of the pb file and using it to predict is jus getting higher . Please look Into this.

**Comment by rrajkumar1990** [comment]
> Also I have doubt why you are using TF 1.x version when TF 2.x is available with pretrained models with much Easier and flexible API to handle Transfer learning?

Also I don't see any direct weights available for Retinanet Model,  We have 2.x weights  for base Resnet only . Can you please point me if you  have the pretrained weights for Retinanet in 2.x

**Comment by SuryanarayanaY** [comment]
Hi @rrajkumar1990 ,

Please find the list of pretrained models [here](https://www.tensorflow.org/api_docs/python/tf/keras/applications). Iam not sure which model you are interested in.Hence I have used one of resnet model to give demo on how can you save the weights of the pretrained model.Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/3dddf296db1648728e2832b37b1a8be4/58140.ipynb).
Please refer the attached [doc](https://www.tensorflow.org/api_docs/python/tf/keras/applications/resnet/ResNet101) also for more information on the model arguments and also some demo examples.

Thankyou!

**Comment by rrajkumar1990** [comment]
Hi @SuryanarayanaY ,

I am looking for  Retinanet Model. But keeping that secondary, I would want to focus on  the  main issue, With the stable version 2.10.1 , the memory consumption is even higher. Can you please look into that .

> @SuryanarayanaY , Yesterday I tired with the new 2.10.1 version. Seems like the memory consumption is even higher now.
> 
> with 2.8 => I was able to get inference with my container memory as 1.5Gb . with 2.9.1 => 1.5GB failed wasn't enough as the memory consumption during the Inference increased to 3.4 GB , so my container memory I had increase to 4GB with 2.10.1 => The memory consumption during inference is 3.76GB which is higher than 2.9.1 version.
> 
> This memory during loading of the pb file and using it to predict is jus getting higher . Please look Into this.

**Comment by SuryanarayanaY** [comment]
Hi @rrajkumar1990 ,
Could you please pinpoint which model weights you are using in the attached link in the above [comment](https://github.com/tensorflow/tensorflow/issues/58140#issuecomment-1311916555) as there are many models available and iam a bit confused to choose right one from them.Could you please confirm so that i can try to replicate the issue.
Thankyou!

**Comment by rrajkumar1990** [comment]
<img width="706" alt="TF_PERFORMANCE_ANALYSIS" src="https://user-images.githubusercontent.com/50878243/204196468-2aefa454-f1d9-4156-ad3e-ad3ca5a582fa.png">

Hi @SuryanarayanaY , 
Please see the above performance numbers based on my tests. we see a performance decrease  and memory increase as we go up the version
Also please use the base  weights /pb files  from : http://download.tensorflow.org/models/resnet_v1_50_2016_08_28.tar.gz .

**Comment by rrajkumar1990** [comment]
Hi @SuryanarayanaY , were you able to replicate the issue ?

**Comment by SuryanarayanaY** [comment]
Hi @rrajkumar1990 ,
Iam trying hard to replicate the issue but facing some problems.
I followed the instructions as per documentation here but iam facing the error as below which might be due to MacOS Host. 
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
qemu: uncaught target signal 6 (Aborted) - core dumped
```
I also tried to replicate on download RHEL image as mentioned below:
```
docker pull redhat/ubi8:8.6
docker images
docker run -it --memory=1500m bbfe57da95c7
yum install python3-pip
```
Then i tried to install tensorflow different versions and all giving error as below.

```
[root@64941ca0c428 /]# pip install tensorflow==2.10
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting tensorflow==2.10
  Could not find a version that satisfies the requirement tensorflow==2.10 (from versions: )
No matching distribution found for tensorflow==2.10
[root@64941ca0c428 /]# pip install tensorflow==2.8.0
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting tensorflow==2.8.0
  Could not find a version that satisfies the requirement tensorflow==2.8.0 (from versions: )
No matching distribution found for tensorflow==2.8.0

[root@64941ca0c428 /]# pip install --user tensorflow
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow
```
I checked that the default python version being used is 3.6.x.This might be the issue.
 
Am i missing something here? Iam not an expert at docker/linux commands and hence your help by providing the exact commands you are using along with the exact image ID will be very much appreciated to replicate the issue. 

Thankyou!

**Comment by SuryanarayanaY** [comment]
Hi @rrajkumar1990,

Initially i thought of using TF images only.But when i see the Size of Image i dropped the idea as tf-nightly image itself having  1.49GB . 2.10.1 has 1.46GB and 2.8.1 has 1.36 GB size.As you told you are running your model in 1.5GB memory right? Are you sure we can run on 1.5 GB container? Anyway i will first test the performance on 2.5 GB container then let you know.

Thankyou!

**Comment by SuryanarayanaY** [comment]
Hi @rrajkumar1990 ,

I downloaded the .ckpt file from the attached link in your [comment](https://github.com/tensorflow/tensorflow/issues/58140#issuecomment-1334979801) and saved it as model.pb file. 
Then i checked the code you mentioned here and i felt something missing in the code.Hence i tried it on colab [gist](https://colab.research.google.com/gist/SuryanarayanaY/a91f469e03c925d85c43bd895a37b041/58140-2-10-1.ipynb) and i got error at this line:
`graph = model_graph.graph_frozen`
Error:
`NameError: name 'model_graph' is not defined`

From the code you provided i could find neither `model_graph` nor `graph_frozen`.Could you please cross check and provide the complete code.

Thankyou!

**Comment by rrajkumar1990** [comment]
Hi @SuryanarayanaY  ,
_After you loaded the pb file , with File :_

```
with tf.io.gfile.GFile(frozen_graph_file, 'rb') as f:
                graph_def = tf.compat.v1.GraphDef()
                graph_def.ParseFromString(f.read())

```
we load the graph_def in the default graph

```
with tf.Graph().as_default() as graph:
                tf.import_graph_def(graph_def,
                                    input_map=None,
                                    return_elements=None,
                                    name="",
                                    op_dict=None,
                                    producer_op_list=None)
```


You should have ur graph stored in “graph”.

`Session =  tf.compat.v1.Session(graph= graph)
`
With this session you can use the 

```
img = Session.get_tensor_by_name("input_img:0")
detect_retinanet = Session.get_tensor_by_name("DetResults:0")
```


Then load an image with open cv, and pass to the session 

```
 test_img = cv2.imread(input_image)[:, :, ::-1]

dets_val = Session.run(detect_retinanet, feed_dict={img: test_img})

```

You could see the performance throughput time  and the memory consumption has increased as we go to higher versions from 2.8.0

**Comment by SuryanarayanaY** [comment]
Hi @rrajkumar1990 ,

Iam getting problems running Docker and later I came to know that we can't use Docker on our System as per our internal policy. I believe there are other issues in this repo related to the same problem you mentioned like #58676 where Developer team already involved and definitely will do needful.

Meanwhile as you are using only 1.x Graph for prediction can you please try adding the code `tf.compat.v1.disable_eager_execution()` after TF import statement  which disables Eager Mode that is default from 2.X onwards followed by `print(tf.executing_eagerly())` which should return False which confirms Eager mode disabled.Please test with this statements and let us know the Memory & Performance details.

Thankyou!

**Comment by rrajkumar1990** [comment]
Hi @SuryanarayanaY , 

I'm aware that I'm using a graph for prediction and i have already added the "tf.compat.v1.disable_eager_execution() ", because eager mode is for 2.x models. The memory and performance numbers which I shared is after disabling eager execution.

Please continue your analysis and let me know

**Comment by SuryanarayanaY** [comment]
Hi @rrajkumar1990 ,
Thanks for the confirmation.Inspired from this [comment](https://github.com/tensorflow/tensorflow/issues/58676#issuecomment-1339826291) can you please set the environment below and try with 2.10V and 2.11V. It should work with 2.10V but not sure of 2.11V though.You can refer the mentioned issue which also largely resembles your issue.

```
import os
assert os.getenv('TF_RUN_EAGER_OP_AS_FUNCTION') == 'False'
```
Thankyou!

**Comment by rrajkumar1990** [comment]
Hi @SuryanarayanaY ,

Have tried with the environment flag 'TF_RUN_EAGER_OP_AS_FUNCTION' as False. It's the same behaviour. I tested in 2.9.1 , 2.10 and 2.11 . 
Moreover the other defect which you have mentioned in the defect  , they are using 2.x model "from tensorflow.keras.applications.resnet50 ". The model architecture is completely different for graph based models and models with eager execution. 
Can you please check. Thanks

**Comment by SuryanarayanaY** [comment]
Hi @rrajkumar1990 ,

> Moreover the other defect which you have mentioned in the defect , they are using 2.x model "from tensorflow.keras.applications.resnet50 ". The model architecture is completely different for graph based models and models with eager execution.

The other issue mentioned also related to performance/Memory consumption w.r.t 2.X models only. I just want to clear that we are not supporting 1.X models and still tried to check in the issue. Now similar behaviour observed with 2.X models and issue already taken up by the Development team and Iam certain that they will come up with some solution definitely ASAP. I hope that might works for your case also as you said it works fine with 2.4V.

Thankyou!

**Comment by rrajkumar1990** [comment]
> Hi @rrajkumar1990 ,
> 
> > Moreover the other defect which you have mentioned in the defect , they are using 2.x model "from tensorflow.keras.applications.resnet50 ". The model architecture is completely different for graph based models and models with eager execution.
> 
> The other issue mentioned also related to performance/Memory consumption w.r.t 2.X models only. I just want to clear that we are not supporting 1.X models and still tried to check in the issue. Now similar behaviour observed with 2.X models and issue already taken up by the Development team and Iam certain that they will come up with some solution definitely ASAP. I hope that might works for your case also as you said it works fine with 2.4V.
> 
> Thankyou!

Hi @SuryanarayanaY ,
My model is based on graph execution. I'm not asking support for models with 1.x. I'm already using the model with compat.v1 .  Also , I have never mentioned that there is no memory issue with 2.4V.  I was using 2.8 Version and tried upgrading to higher versions and  observing this issue. 
Can you please assign this defect to the Dev team.

Thanks,

**Comment by SuryanarayanaY** [comment]
Hi @rrajkumar1990 ,

We got an update regarding High memory consumption in recent TF versions. Can you please try passing the input data in the form of `tf.data.Dataset` like below or any suitable method based on your input type as per the Examples in the attached [API](https://www.tensorflow.org/api_docs/python/tf/data/Dataset?version=nightly).Below is just an example but you should choose the suitable method from the `tf.data.Dataset API` based on your input data

```
x_train = tf.data.Dataset.from_tensor_slices(x).batch(32) # batch size of your choice
for _ in range(10000):
    y_True = model.predict(x_train)
```
Since you are using `Session `and `tf.compat.V1 `module i can't assure you performance guarantee even though if i escalate it to next level based on this documentation [source](https://www.tensorflow.org/api_docs/python/tf/compat/v1/Session#expandable-1). Hence please try using your input data in form of tf.data.Dataset and let us know if it helps.Based on this I can escalate the issue to next level

Thankyou!

**Comment by rrajkumar1990** [comment]
Hi , Let me try and update here
