### ISSUE TITLE
XLA CPU performance issues

### ISSUE THREAD

**Issue by lockmatrix** [tensorflow/tensorflow#58142]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

2.10 and 2.11 branch

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.6

### Bazel version

5.3.0

### GCC/Compiler version

12.1

### CUDA/cuDNN version

None

### GPU model and memory

None

### Current Behaviour?

```shell
CPU only.

I try to enable xla on my models, but found it became slower.

I found: without xla, tf can use all cores(8 for my case), there are enough ops to distributed across multiple cores.
but when enable xla, critical path became `_XlaRun`, and it seems to run in single thread.

I tried `--tf_xla_max_cluster_size=10`, and still slower. 

I want to know if this result is as expected, and if there is anyway to make xla utilize all cores.
```

**Comment by tiruk007** [comment]
@lockmatrix 
Could you please provide a minimum code snippet to replicate the issue reported here and refer to this document([XLA: Optimizing Compiler for Machine Learning](https://www.tensorflow.org/xla) )

Thank you.
