### ISSUE TITLE
LeakyRelu in Tensorflow lite with the Hexagon Delegate not supported

### ISSUE THREAD

**Issue by eelcoder** [tensorflow/tensorflow#58156]
When using a tflite model (8-bits quantized via TensorFlow lite conversion framework) that includes the activation function "LeakyRelu", the Hexagon delegate from tensorflow framework cannot perform the DNN inference on the whole graph, but rather it falls back to the CPU/XNNPack delegate. This is due to the fact that 'LeakyRelu' operation is not supported by the Hexagon Delegate (confirmed in TensorFlow doc: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/README.md). When using Relu activation function (and Relu6 as well), we can see below that the TF Hexagon Delegate can process the whole DNN graph, unfortunately, the qualitative results I get are much worse, hence the need of having 'Leaky Relu' implemented in the Hexagon Delegate. We can easily reproduce this behavior by using TensorFlow Benchmark tool (see below)

Could we consider to implement Leaky Relu in tensorflow lite DSP delegate ?

**System information**
- OS Platform and Distribution): Android 10, NDK R21e
- TensorFlow installed from (source or binary): from source using the Release tag '2.9.1'
- TensorFlow version (or github SHA if from source):  2.9.1

**Provide the text output from tflite_convert**

```
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 23). These functions will not be directly callable after loading.
C:\Users\eelfahsi\Miniconda3\envs\ml\lib\site-packages\tensorflow\lite\python\convert.py:766: UserWarning: Statistics for quantized inputs were expected, but not specified; continuing anyway.
  warnings.warn("Statistics for quantized inputs were expected, but not "
2022-10-13 18:13:16.990773: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
2022-10-13 18:13:16.991046: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.
2022-10-13 18:13:16.998334: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: C:\Users\eelfahsi\AppData\Local\Temp\tmp731h7tgk
2022-10-13 18:13:17.027069: I tensorflow/cc/saved_model/reader.cc:81] Reading meta graph with tags { serve }
2022-10-13 18:13:17.027795: I tensorflow/cc/saved_model/reader.cc:122] Reading SavedModel debug info (if present) from: C:\Users\eelfahsi\AppData\Local\Temp\tmp731h7tgk
2022-10-13 18:13:17.269741: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
2022-10-13 18:13:17.291178: I tensorflow/cc/saved_model/loader.cc:228] Restoring SavedModel bundle.
2022-10-13 18:13:18.176412: I tensorflow/cc/saved_model/loader.cc:212] Running initialization op on SavedModel bundle at path: C:\Users\eelfahsi\AppData\Local\Temp\tmp731h7tgk
2022-10-13 18:13:18.475762: I tensorflow/cc/saved_model/loader.cc:301] SavedModel load for tags { serve }; Status: success: OK. Took 1477588 microseconds.
2022-10-13 18:13:19.015757: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:263] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
Found 7390 files belonging to 1 classes.
fully_quantize: 0, inference_type: 6, input_inference_type: 9, output_inference_type: 9

Process finished with exit code 0

```

**Standalone code to reproduce the issue** 
Here is a colab link with the code used to:
- generate the model that include leaky relu op.
- quantize and save the model in int8 ops.

Colab code Link: https://colab.research.google.com/drive/1xmktQACGQ6GnMmrwco3bNXcmJIDjt5PK?usp=sharing

**Link to the quantized model:**
[my_quant_model_leaky_relu.zip](https://github.com/tensorflow/tensorflow/files/9815061/my_quant_model_leaky_relu.zip)

The tool below from Tensorflow allow to run any model, when running the model above, it fails because 'LeakyRelu' is not supported.

**Link to TensorFlow Benchmark**:
https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/release/lite/tools/nightly/latest/android_aarch64_benchmark_model

tflite benchmark command line:
```
./tf_benchmark --graph=/data/local/tmp/my_quant_model_leaky_relu.tflite  --require_full_delegation=true --use_hexagon=true --hexagon_lib_path=/data/local/tmp/

```
When performing the inference on dsp using Tensorflow lite Benchmark tool for android, we get the following error message:
```
./tf_benchmark  --use_hexagon=true --graph=./my_quant_model_leaky_relu.tflite   --require_full_delegation=true --hexagon_lib_path=/data/local/tmp/          <
STARTING!
Log parameter values verbosely: [0]
Graph: [./my_quant_model_leaky_relu.tflite]
Require full delegation: [1]
Use Hexagon: [1]
Hexagon lib path: [/data/local/tmp/]
Loaded model ./my_quant_model_leaky_relu.tflite
INFO: Initialized TensorFlow Lite runtime.
loaded libcdsprpc.so
Hexagon delegate created.
INFO: TfLiteHexagonDelegate delegate: 6 nodes delegated out of 12 nodes with 5 partitions.

VERBOSE: Replacing 6 node(s) with delegate (TfLiteHexagonDelegate) node, yielding 6 partitions.
Disallowed CPU fallback detected.
Benchmarking failed.
```

If I disable the usage of the dsp, then it works properly
tflite benchmark command line:
```
./tf_benchmark --graph=/data/local/tmp/my_quant_model_leaky_relu.tflite 
```
Logs
```
./tf_benchmark  --graph=./my_quant_model_leaky_relu.tflite                                                                          
STARTING!
Log parameter values verbosely: [0]
Graph: [./my_quant_model_leaky_relu.tflite]
Loaded model ./my_quant_model_leaky_relu.tflite
INFO: Initialized TensorFlow Lite runtime.
The input model file size (MB): 0.038384
Initialized session in 0.57ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=1141 first=4613 curr=428 min=427 max=4613 avg=438.004 std=125

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=2311 first=433 curr=428 min=427 max=627 avg=432.374 std=14

Inference timings in us: Init: 570, First inference: 4613, Warmup (avg): 438.004, Inference (avg): 432.374
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Memory footprint delta from the start of the tool (MB): init=0 overall=3.09766
...
```

If I replace leakyRelu by Relu, then it works properly
Here is a colab link with the code used to:
- generate the model that include relu op.
- quantize and save the model in int8 ops.

Colab code Link: https://colab.research.google.com/drive/1PZjt4BkFDP5EXAcVEi5N3Q4mYlfaawQP?usp=sharing

**Link to the quantized model:**
[my_quant_model_relu.zip](https://github.com/tensorflow/tensorflow/files/9815007/my_quant_model_relu.zip)

tflite benchmark command line:
```
./tf_benchmark  --use_hexagon=true --graph=./my_quant_model_relu.tflite   --require_full_delegation=true --hexagon_lib_path=/data/local/tmp/
```
Logs
```
./tf_benchmark  --use_hexagon=true --graph=./my_quant_model_relu.tflite   --require_full_delegation=true --hexagon_lib_path=/data/local/tmp/                                                             <
STARTING!
Log parameter values verbosely: [0]
Graph: [./my_quant_model_relu.tflite]
Require full delegation: [1]
Use Hexagon: [1]
Hexagon lib path: [/data/local/tmp/]
Loaded model ./my_quant_model_relu.tflite
INFO: Initialized TensorFlow Lite runtime.
loaded libcdsprpc.so
Hexagon delegate created.
INFO: TfLiteHexagonDelegate delegate: 8 nodes delegated out of 8 nodes with 1 partitions.

VERBOSE: Replacing 8 node(s) with delegate (TfLiteHexagonDelegate) node, yielding 1 partitions.
Explicitly applied Hexagon delegate, and the model graph will be completely executed by the delegate.
The input model file size (MB): 0.0374
Initialized session in 174.22ms.
Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
count=918 first=796 curr=537 min=324 max=3378 avg=540.937 std=180

Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
count=1754 first=701 curr=537 min=443 max=2552 avg=565.409 std=136

Inference timings in us: Init: 174220, First inference: 796, Warmup (avg): 540.937, Inference (avg): 565.409
Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
Memory footprint delta from the start of the tool (MB): init=3.48047 overall=3.48047


```

**Comment by mohantym** [comment]
@eelcoder !
Thanks for bringing it up again.  

@sachinprasadhs !
Could you look at this feature request.

Thank you!

**Comment by eelcoder** [comment]
Hi,

Thanks for taking into consideration my request.
Any update on your side ?

**Comment by eelcoder** [comment]
Hello @sirakiin ,

Thanks for the tip.
Initially, I tried to implement it using tensorflow ops in python, but the inference time was very slow (4x slower):
![image](https://user-images.githubusercontent.com/3323242/199208868-ba410a93-a13c-4193-b3e2-559d590c9707.png)

But here I guess, I need to modify directly the hexagon delegate, which should hopefully be faster:
I'd like to try it, but since I'm not very familiar with the hexagon delegate code, could you give me an example on where to add the LeakyRelu support in HexagonDelegate code ?
My guess is that I'd need to modify `hexagon/builders/op_builder.cc` and `hexagon/builders/activation_builder.cc`, but not familiar enough with the code to do it properly.

Would be really grateful, if you could guide me in this process :)

Thanks!

**Comment by eelcoder** [comment]
Hello,

Any feedback on this request ?

thanks.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
