### ISSUE TITLE
Linking error when using tflite::StatefulNnApiDelegate 

### ISSUE THREAD

**Issue by NicoZobernig** [tensorflow/tensorflow#58165]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.10

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04 - Android Studio for building

### Mobile device

Android ARM64

### Bazel version

5.1.1

### Current Behaviour?

Hi! I am trying to add a delegate to the interpreter from the C++ native side, but am unable to figure out how to make it work. Any help would be greatly appreciated!

I can successfully build the model, interpreter and tensors needed for inference, but attempting to initialize `tflite::StatefulNnApiDelegate` leads to a linking error when trying to build the apk

```C/C++: ld: error: undefined symbol: tflite::StatefulNnApiDelegate::Data::~Data()```

What confuses me is that all other tflite functions and objects I needed have been found, I can even declare `tflite::StatefulNnApiDelegate::Options` without issue.

1. Am I doing something wrong in the code, from the examples I could find, and looking at the jni code for the java side I believe the code provided should be correct. Could I be missing something completely, like querying for the Nnapi or setting something in the options before creating the delegate?

2. Could it be an issue happening while building `libtensorflowlite.so`? I followed the recipe to build it with bazel for ARM chips [Build TensorFlow Lite for ARM boards](https://www.tensorflow.org/lite/guide/build_arm) with the command:
```
bazel build --config=android_arm64 -c opt //tensorflow/lite:libtensorflowlite.so
```
and also tried 
```
bazel build -c opt --config=android_arm64 //tensorflow/lite/delegates/nnapi:nnapi_delegate
```
to no avail...

I also included the `CMakeLists.txt` to make sure I am not doing something wrong there.

Thank you in advance!

### Standalone code to reproduce the issue

Failing code.
```
//! 1) build model
model_ = tflite::FlatBufferModel::BuildFromBuffer(model_buffer_,
                                                  sizeof(char) * model_size_);

//! 2) resolving model
tflite::ops::builtin::BuiltinOpResolver resolver;
tflite::InterpreterBuilder builder(*model_, resolver);

//! 3) create NNApi delegate
tflite::StatefulNnApiDelegate::Options options = tflite::StatefulNnApiDelegate::Options();
tflite::StatefulNnApiDelegate nnapi_delegate(options); // fails with ld error
builder.AddDelegate(&nnapi_delegate);

//! 4) link to interpreter
builder(&interpreter_);
assert(interpreter_ != nullptr);
```

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.4.1)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=gnu++17")

# Specify where to find the header files for TF Lite C++
set(TF_LITE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../../../tflite-api)
set(INCLUDE_DIRS
        ${TF_LITE_DIR}/include
        ${TF_LITE_DIR}/include/flatbuffers/include)
include_directories(
        ${INCLUDE_DIRS})

add_library(tflite SHARED IMPORTED )
set_target_properties(tflite PROPERTIES IMPORTED_LOCATION
        ${TF_LITE_DIR}/lib/${ANDROID_ABI}/libtensorflowlite.so )

add_library(native-lib SHARED
            native-lib.cpp
            native-tf.cpp)

target_include_directories(native-lib
        PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR})

target_link_libraries(native-lib
        android
        camera2ndk
        mediandk
        log
        tflite
        )
```

**Comment by mohantym** [comment]
Hi @NicoZobernig !
Sorry for the late respone.

I see you are using CMake 3.4.1  version . 
Can you check with CMake 3.14 or hight and post the LD error too.

Thank you!

**Comment by NicoZobernig** [comment]
Hi @mohantym ! Thank you for looking into this.

I am actually using CMake 3.18.1, setting it in the `build.gradle` file. The minimum version is just a remains from android-studio's template as far as I remember...

So the LD error is the same.

I also tried linking `neuralnetworks` in `target_link_libraries` to see if that would change anything:
```
target_link_libraries(native-lib
        android
        neuralnetworks
        camera2ndk
        mediandk
        log
        tflite
        )
```
It didn't...

I can make it work is by using the C API instead after getting `libtensorflowlite_jni.so` from the packaged `.aar` file provided [here](https://search.maven.org/artifact/org.tensorflow/tensorflow-lite/2.10.0/aar).

So my assumption is that the building procedure of the C++ API library is at fault. I cannot say whether the build files have an issue or if I did something wrong there.

**Comment by mohantym** [comment]
@NicoZobernig ! 
Thanks for sharing your observations.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
