### ISSUE TITLE
Tensorflow no library flags

### ISSUE THREAD

**Issue by suggfudge** [tensorflow/tensorflow#58160]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.2.0

### Custom Code

No

### OS Platform and Distribution

Rasbian Buster

### Mobile device

Raspberry Pi 4B

### Python version

3.7.3

### Bazel version

2.0.0- (@non-git)

### GCC/Compiler version

gcc (Raspbian 8.3.0+rpi1) 8.3.0

### CUDA/cuDNN version

not using cuda

### GPU model and memory

no gpu, 8.6gb free out of 28.9gb

### Current Behaviour?

```shell
Wanted to build tensorflow-io 0.14.0 from source as there wasn't a suitable wheel for it, when running configure.sh:

ERROR: Expected exactly one lib and one libdir in tf.sysconfig.get_link_flags() [] []
```
```


### Standalone code to reproduce the issue

```shell
Tensorflow resources used:
https://qengineering.eu/install-tensorflow-2.2.0-on-raspberry-pi-4.html   version 2.2.0
^built official source code with bazel and generated wheels a few times, problem was not solved

Any previous actions taken on this machine: none, it's a fresh os flash.


>>>import tensorflow as tf
>>>lib = tf.sysconfig.get_link_flags()
>>>lib
[]
```
```


### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @suggfudge !
For edge-device purpose , TFlite is suggested way to save space .

Can you check the signature build for raspberry from [here](https://github.com/tensorflow/build/tree/master/raspberry_pi_builds). 
Alternate installation can be through [tflite-runtime](https://www.tensorflow.org/lite/guide/python), [bazel build](https://www.tensorflow.org/lite/guide/build_arm#cross-compilation_for_arm_with_bazel).

Thank you!

**Comment by suggfudge** [comment]
fascinating, tensorflow 2.10 can be installed on the raspberry pi. For the docker method, I tried to follow the guide step by step, but got stuck at "is the daemon running?"

it might take me a day or two to make an actual attempt

**Comment by suggfudge** [comment]
This might not be stackoverflow, but if I could find out how to conjure a one-liner to make a working container (I installed debian image), that would be great.

**Comment by mohantym** [comment]
@suggfudge !

Feel free to check the docker instructions at [Pintoo's  wheels ](https://github.com/PINTO0309/TensorflowLite-bin) in the meantime. 

Thank you!

**Comment by suggfudge** [comment]
these are instructions to build tflite-runtime...?

```pip install tflite-runtime``` already works in the first place, is the official docker instructions also for the same purpose?

I also happen to see that raspberry pi support was discontinued from around 2.3.0rc2, shouldn't tensorflow-io be working fine before this point?

**Comment by suggfudge** [comment]
looking at pintoo's instructions, it seems there are only dockerfiles for 2.8.0 that can be curled.

**Comment by suggfudge** [comment]
pintoo has one confusing section:

```
### Common task
sed -i -e 's/FROM ubuntu:16.04/FROM ubuntu:18.04/g' tensorflow/tools/ci_build/Dockerfile.pi-python38
sed -i -e 's/FROM ubuntu:16.04/FROM ubuntu:18.04/g' tensorflow/tools/ci_build/Dockerfile.pi-python39
sed -i '5a ENV DEBIAN_FRONTEND=noninteractive' tensorflow/tools/ci_build/Dockerfile.pi-python39
sed -i '30a apt-get update && apt-get install -y dirmngr' tensorflow/tools/ci_build/install/install_deb_packages.sh
sed -i -e 's/xenial/bionic/g' tensorflow/tools/ci_build/install/install_pi_python3x_toolchain.sh
sed -i '19a sudo pip3 install setuptools==60.7.0' tensorflow/tools/ci_build/install/install_auditwheel.sh
sed -i '20a sudo pip3 install numpy==1.23.2' tensorflow/tools/ci_build/install/install_auditwheel.sh
cp tensorflow/tools/ci_build/Dockerfile.pi-python39 tensorflow/tools/ci_build/Dockerfile.pi-python310
sed -i -e 's/3.9/3.10/g' tensorflow/tools/ci_build/Dockerfile.pi-python310
```
this comes right before step two of the official build guide. Why are all these python versions flying about?

**Comment by mohantym** [comment]
@suggfudge !
Thanks for the update. Feel free to raise a PR from your end.  

@sachinprasadhs !
Could you look at this issue.

Thank you!

Thank you!

**Comment by suggfudge** [comment]
I'm not sure I understand what a PR is, or what I would ask in the tflite-micro repo.

**Comment by mohantym** [comment]
@suggfudge !

I am suggesting close this issue and just create  one more ticket in TFlite-micro repo too ( for faster update).
I will try to come with a pull request ( update documentation ) once i get feedback from concerned Team.

Keeping this issue open till then. 

Thank you!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
