### ISSUE TITLE
Significant increase in the size of macOS wheel

### ISSUE THREAD

**Issue by learning-to-play** [tensorflow/tensorflow#58164]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf-nightly 2.11

### Custom Code

No

### OS Platform and Distribution

macOS

### Python version

3.7, 3.8, 3.9, 3.10

### Bazel version

5.3.0

### Current Behaviour?

```shell
[PR 55941](https://github.com/tensorflow/tensorflow/pull/55941) refactored and deduplicated TensorFlow C++ dependencies from _pywrap_tensorflow_internal.so into libtensorflow_cc.so. This change increased the size of macOS pip package from 240 MB to 350 MB.
```

### Standalone code to reproduce the issue

```shell
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/rel/macos/cpu_py310_pip.sh
```

### Relevant log output

_No response_</details>

**Comment by trevor-m** [comment]
I think the size increase is from these two copies of `libtensorflow_cc.dylib` in the wheel. It looks like `libtensorflow_framework.dylib` was also duplicated, even before #55941.

To fix this, we can probably change one of them to a symlink or adjust the dependencies to match linux which only uses the major version numbered lib (`libtensorflow_cc.2.dylib` and `libtensorflow_framework.2.dylib`).

```
-rwxr-xr-x   1 tester  admin   488M Oct 12 15:22 libtensorflow_cc.2.11.0.dylib
-rwxr-xr-x   1 tester  admin   488M Oct 12 15:22 libtensorflow_cc.2.dylib
-rwxr-xr-x   1 tester  admin    32M Oct 12 15:22 libtensorflow_framework.2.11.0.dylib
-rwxr-xr-x   1 tester  admin    32M Oct 12 15:22 libtensorflow_framework.2.dylib
-rwxr-xr-x   1 tester  admin    32M Oct 12 15:22 libtensorflow_framework.dylib
```

**Comment by trevor-m** [comment]
Hi @learning-to-play, thanks for filing this issue! I've just opened a PR with a potential fix. Could you check if the wheel size improves for you with this change? On my Mac machine, I'm now seeing 185mb.
