### ISSUE TITLE
BUILD target visibility broken by upcoming Bazel 6.0 release

### ISSUE THREAD

**Issue by brandjon** [tensorflow/tensorflow#58168]
### Issue Type

Build/Install

### Source

source

### Tensorflow Version

Near-HEAD

### Custom Code

No

### Bazel version

pre-6.0

### Current Behaviour?

Tensorflow's build will break in Bazel 6.0 due to a bugfix in the behavior of `package_group`. (See [Bazel CI run](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2693#0183ee6d-d2e0-4305-9e96-ad11089eb101))

The target `//tensorflow/compiler/xla/mlir/transforms/runtime:calling_convention` depends on `//tensorflow/compiler/xla/mlir/ir/runtime:rt`, and is granted visibility via the latter's `default_visibility` of [`@tf_runtime//:friends`](https://github.com/tensorflow/tensorflow/blob/87e65c2d55d8f3edac6fc7fec4c15b8d0dc7e67e/tensorflow/compiler/xla/mlir/ir/runtime/BUILD#L8). This `friends` package group [contains](https://github.com/tensorflow/runtime/blob/57fa01e0e17ead6faa2a98cfc985eff55380c393/BUILD#L19) `//...`, which under pre-6.0 behavior grants visibility to everyone (effectively public). The corrected behavior is that it grants visibility only to all packages within the same repo as that package group, i.e., to packages under @tf_runtime.

If you want the behavior of the package group to be "visible to all packages, everywhere", you can replace `//...` with the special string constant `public`, which is new to Bazel 6.0. This will break compatibility with prior Bazel versions. Note that there is no direct way for a package group to specify "visible to the following packages that live outside of my own repo".

Alternatively, you can rewrite the `default_visibility` in `tensorflow/compiler/xla/mlir/ir/runtime/BUILD` to `//visibility:public`, because that's effectively what it already is; or you can determine a more suitable narrower visibility definition.

Finally, you can opt out of this change for your build by passing `--incompatible_fix_package_group_reporoot_syntax=false` in Bazel 6.0. This is particularly helpful if you want to migrate to use `public` for any package groups in the meantime

See bazelbuild/bazel#16323 for more information.

### Standalone code to reproduce the issue

Build at head Bazel.

### Relevant log output

_No response_</details>

**Comment by fweikert** [comment]
Friendly ping

**Comment by meteorcloudy** [comment]
Looks like this is fixed by https://github.com/tensorflow/tensorflow/commit/4695502cf9ded96ed835ddcb1ec7e7bcb85f3891
