### ISSUE TITLE
Halo exchange is only supported on TPU for DTensor

### ISSUE THREAD

**Issue by jonycastagna** [tensorflow/tensorflow#58161]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

TensorFlow version: 2.12.0-dev20221019

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04.4 LTS

### Python version

3.9.12

### Current Behaviour?

```shell
It fails with "Halo exchange is only supported on TPU". When/if will it work on both CPU and GPU hardware?
```

### Standalone code to reproduce the issue

```shell
from tkinter import W
import tensorflow as tf
import numpy as np

from tensorflow.experimental import dtensor

# set logging
import logging
logger = tf.get_logger()
logger.setLevel(logging.DEBUG)



# ------------------------------------------- make sure is the latest TensorFlow version
print('\n\nTensorFlow version:', tf.__version__)




# ------------------------------- configure devices
DEV            = 'CPU'  # GPU
nDEVz          = 1  # z or batch for single channel images
nDEVy          = 2  # y
nDEVx          = 2  # x
nDEVs          = nDEVz*nDEVy*nDEVx


def configure_virtual_cpus(ncpus):
    phy_devices = tf.config.list_physical_devices(DEV)
    tf.config.set_logical_device_configuration(phy_devices[0], [tf.config.LogicalDeviceConfiguration(),] * ncpus)


def configure_virtual_gpus(ngpus):
    phy_devices = tf.config.list_physical_devices('CPU')
    tf.config.set_logical_device_configuration(phy_devices[0], [tf.config.LogicalDeviceConfiguration(),] * ngpus)

    phy_devices = tf.config.list_physical_devices(DEV)
    for n in range(ngpus):
        tf.config.set_logical_device_configuration(phy_devices[n], [tf.config.LogicalDeviceConfiguration(memory_limit=2000),])


if (DEV=='CPU'):
    configure_virtual_cpus(nDEVs)
    DEVICES = [f'CPU:{i}' for i in range(nDEVs)]

if (DEV == 'GPU'):
    configure_virtual_gpus(nDEVs)
    DEVICES = [f'GPU:{i}' for i in range(nDEVs)]


print(tf.config.list_logical_devices(DEV))


def dtensor_from_array(arr, layout, shape=None, dtype=None):
    """Convert a DTensor from something that looks like an array or Tensor.

    This function is convenient for quick doodling DTensors from a known,
    unsharded data object in a single-client environment. This is not the
    most efficient way of creating a DTensor, but it will do for this
    tutorial.
    """
    if shape is not None or dtype is not None:
        arr = tf.constant(arr, shape=shape, dtype=dtype)

    # replicate the input to the mesh
    a = dtensor.copy_to_mesh(arr, layout=dtensor.Layout.replicated(layout.mesh, rank=layout.rank))

    # shard the copy to the desirable layout
    return dtensor.relayout(a, layout=layout)








# -------------------------------------  tests ------------------------------------------
mesh = dtensor.create_mesh([("batch", nDEVz), ("y", nDEVy), ("x", nDEVx)], devices=DEVICES)

layout_img = dtensor.Layout(["batch", "y", "x", dtensor.UNSHARDED], mesh)
layout_ker = dtensor.Layout([dtensor.UNSHARDED, dtensor.UNSHARDED, dtensor.UNSHARDED, dtensor.UNSHARDED], mesh)  #ex. 3x3x1x32

A = np.arange(2*28*28*1, dtype="float32")
A = np.reshape(A, (2,28,28,1))
A = tf.convert_to_tensor(A)
dA = dtensor_from_array(A, layout_img)

w = np.arange(3*3*1*32, dtype="float32")
w = np.reshape(w, (3,3,1,32))
w = tf.convert_to_tensor(w)
dw = dtensor_from_array(w, layout_ker)

x = tf.nn.conv2d(dA, dw, strides=[1, 1, 1, 1], padding="VALID", data_format="NHWC")

print("\n")
print(dA)

print("\n")
print(dw)

print("\n")
print(x)

exit()
```

### Relevant log output

Halo exchange is only supported on TPU.

**Comment by srujun** [comment]
Convolution on DTensor input that is sharded on spatial dimensions requires performing halo exchange on slices of the different shards of the tensor. This algorithm's current implementation in DTensor depends on the [CollectivePermute op](https://www.tensorflow.org/api_docs/python/tf/raw_ops/CollectivePermute) which is only supported on TPU. We have it in our backlog to update the implementation to use ops that would also work on CPU and GPU.

In the meantime, if possible, you can try to update the `layout_img` Layout to use `dtensor.UNSHARDED` on the width and height dimensions.

**Comment by jonycastagna** [comment]
Hi, thanks for your answer. Do you have an estimation time for your backlog? Unfortunately the dtensor.UNSHARDED does not help us to reduce the memory required per GPU.

**Comment by srujun** [comment]
That is understandable. We are currently planning to address this in 2023Q1. We'll post an update here then.

**Comment by jonycastagna** [comment]
Great! Thanks a lot!

**Comment by apcode** [comment]
+1 Posting on this thread as I am also interested in this update.

I am running 3D convolutions over grids that are too large to fit on a single GPU. I get the same error for the same reason as specified by OP.

Looking forward to the update.

**Comment by sachinprasadhs** [comment]
Keeping this thread open till we have this feature implemented.

**Comment by jonycastagna** [comment]
Hi there, any news on this?

**Comment by billygrahamram** [comment]
Hello, is there any update on this?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
