### ISSUE TITLE
A crash due to check-fail can be triggered in DepthwiseConv2dNativeBackpropFilter

### ISSUE THREAD

**Issue by shijy16** [tensorflow/tensorflow#58180]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9 and 2.12.0-dev20221018

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

CUDA 11.5

### Current Behaviour?

```shell
When execute on CPU with OneDNN enabled, a crash due to check-fail can be triggered in DepthwiseConv2dNativeBackpropFilter.
```

### Standalone code to reproduce the issue

```shell
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '1'
import tensorflow as tf
import numpy as np
print(tf.__version__)
for _ in range(20):
    try:
        with tf.device("CPU"):
            strides_0 = 1
            strides_1 = 1
            strides_2 = 128
            strides_3 = 128
            strides = [strides_0, strides_1, strides_2, strides_3, ]
            padding = "VALID"
            explicit_paddings = []
            data_format = "NCHW"
            dilations_0 = 96
            dilations_1 = 25
            dilations_2 = 10
            dilations = [dilations_0, dilations_1, dilations_2, ]
            input = tf.random.uniform([], dtype=tf.float32)
            filter_sizes = tf.saturate_cast(tf.random.uniform([0], minval=0, maxval=64, dtype=tf.int64), dtype=tf.int32)
            out_backprop = tf.random.uniform([16, 2], dtype=tf.float32)
            res = tf.raw_ops.DepthwiseConv2dNativeBackpropFilter(
                strides=strides,
                padding=padding,
                explicit_paddings=explicit_paddings,
                data_format=data_format,
                dilations=dilations,
                input=input,
                filter_sizes=filter_sizes,
                out_backprop=out_backprop,
            )
    except:
        pass
```

### Relevant log output

```shell
F ./tensorflow/core/util/tensor_format.h:427] Check failed: index >= 0 && index < num_total_dims Invalid index from the dimension: 1, 1, C
Aborted (core dumped)
```
</details>

**Comment by tilakrayal** [comment]
@shijy16,
Probably there is a missing check in the low level API.
Could you please try to reproduce your experiment with the high level API and let us know if you are facing same issue. Thank you!

**Comment by mihaimaruseac** [comment]
This is a real issue that used to be considered a vulnerability but due to large number of occurences versus limited impact it was decided to only consider it a bug. Please don't autoclose these types of issues.

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.9, v2.10 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/e5c83edf3e2e1fd2a263588bf3126613/untitled735.ipynb).

**Comment by SuryanarayanaY** [comment]
Hi @shijy16 ,

This has been fixed already.Tested in TF2.16v and attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/0ff9d0d7ee58bd3916ed08a647fffc9c/58180_nightly_success.ipynb) here. Thanks!
