### ISSUE TITLE
Keras load LSTM/GRU model with constant mask/initial_state will raise error

### ISSUE THREAD

**Issue by RunnerZhong** [tensorflow/tensorflow#58183]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

TF 2.6.3

### Custom Code

Yes

### OS Platform and Distribution

RedHat 7

### Python version

3.8

### Current Behaviour?

```shell
Traceback (most recent call last):
  File "/home/runner/work/sample_code/example.py", line 28, in <module>
    dd = tf.keras.models.load_model("./lstm.h5", compile=False, options=load_options)
  File "/home/runner/anaconda3/envs/latest_env/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/runner/anaconda3/envs/latest_env/lib/python3.8/site-packages/keras/backend.py", line 1470, in int_shape
    shape = x.shape
AttributeError: 'float' object has no attribute 'shape'
```

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf
import tensorflow.keras.backend as K

input_t = tf.keras.Input(shape=(28, 10), batch_size=2, dtype="float32")

rdm_value = np.ones([2, 28]).astype(np.float32)
rdm_value[:, 20:] = 0
mask_value = K.constant(np.array(rdm_value), dtype='bool')

m_state = tf.keras.initializers.GlorotUniform()(shape=[2, 6], dtype='float32')
c_state = tf.keras.initializers.GlorotUniform()(shape=[2, 6], dtype='float32')
init_state_value = [m_state, c_state]

# mask_value = tf.keras.Input(shape=(28), batch_size=2, dtype="bool")

lstm = tf.keras.layers.LSTM(6,
                            return_sequences=True,
                            return_state=True,
                            bias_initializer='random_uniform',
                            time_major=False)(inputs=input_t, mask=mask_value,
                                              training=False,
                                              initial_state=init_state_value)
keras_model = tf.keras.Model([input_t], lstm)
keras_model.save('./lstm.h5')

load_options = tf.saved_model.LoadOptions(allow_partial_checkpoint=True)
dd = tf.keras.models.load_model("./lstm.h5", compile=False, options=load_options)
print(dd.inputs)
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@RunnerZhong,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by RunnerZhong** [comment]
> @RunnerZhong, Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues).
> 
> Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues). To know more please refer: https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999 Thank you!

Sure, thanks your reply.
