### ISSUE TITLE
A crash due to check-fail can be triggered in FixedUnigramCandidateSampler

### ISSUE THREAD

**Issue by shijy16** [tensorflow/tensorflow#58181]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9 and 2.12.0-dev20221018

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

CUDA 11.5

### Current Behaviour?

```shell
A crash due to check fail can be triggered when execute with both CPU and GPU
```

### Standalone code to reproduce the issue

```shell
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import tensorflow as tf
import numpy as np
print(tf.__version__)
for _ in range(20):
    try:
        with tf.device("GPU:0"):
            num_true = 12
            num_sampled = 53
            unique = True
            range_max = 105
            vocab_file = ""
            distortion = 15.07084518523925
            num_reserved_ids = 0
            num_shards = 1
            shard = 0
            unigrams_0 = 45.35209469768597
            unigrams_1 = 73.63755693482213
            unigrams_2 = 51.69763696074902
            unigrams = [unigrams_0, unigrams_1, unigrams_2, ]
            seed = 0
            seed2 = 0
            true_classes = tf.saturate_cast(tf.random.uniform([1, 12], minval=0, maxval=64, dtype=tf.int64), dtype=tf.int64)
            res = tf.raw_ops.FixedUnigramCandidateSampler(
                num_true=num_true,
                num_sampled=num_sampled,
                unique=unique,
                range_max=range_max,
                vocab_file=vocab_file,
                distortion=distortion,
                num_reserved_ids=num_reserved_ids,
                num_shards=num_shards,
                shard=shard,
                unigrams=unigrams,
                seed=seed,
                seed2=seed2,
                true_classes=true_classes,
            )
    except:
        pass
```

### Relevant log output

```shell
Check failed: range == weights_.size() (105 vs. 3)
```
</details>

**Comment by maifeeulasad** [comment]
@shijy16 ,

try this code `with tf.device(str(tf.test.gpu_device_name())):` if you think your device name is going to be changed frequently. Works both on local and cloud environments.

**Comment by shijy16** [comment]
> @shijy16 I tried to execute the code with the alternative approach by changing `tf.device("GPU:0")` to `tf.device("/physical_device:GPU:0")` and it is executing without any error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tiruk007/f7bc69745e4911600ee17e6c98fe6c41/58181.ipynb#scrollTo=SNJs5BEHwWng)
> 
> Thank you!

This works for me! But how does this work?
And when execute with CPU by `with tf.device('CPU')`, the same error shows up.

**Comment by shijy16** [comment]
> @shijy16 ,
> 
> try this code `with tf.device(str(tf.test.gpu_device_name())):` if you think your device name is going to be changed frequently. Works both on local and cloud environments.

Thanks but this doesn't work. And `tf.device("/physical_device:GPU:0")` works. 
And I am curious on the root cause of this bug as  `tf.device("CPU")`  doesn't work, too.

**Comment by tiruk007** [comment]
@shijy16 
`tf.config.list_physical_devices()` by using this we can get the names of the physical devices. `tf.device` takes an argument  `device_name`, which can be fully specified as in "/job:worker/task:1/device:cpu:0", or partially specified, containing only a subset of the "/"-separated fields. Could you please check this gist [here](https://colab.research.google.com/gist/tiruk007/ff13227c8b4086c6c12ad45440f4bc6e/58181.ipynb#scrollTo=PtJAtCDiGn3z) and refer to [tf.device](https://www.tensorflow.org/api_docs/python/tf/device).
Thank you!

**Comment by maifeeulasad** [comment]
@shijy16 , my bad. Not sure why this is not working for you. 

Ref: https://www.kaggle.com/code/maifeeulasad/paddy-doctor-paddy-disease-classification?scriptVersionId=95678277&cellId=11
Env: `TF-2.6.4`

**Comment by shijy16** [comment]
@tiruk007 
Hi,
I've checked the links in your response. I got that the correct device name has to be specified when calling `tf.device` in this issue. 
But I am still confused why something like `tf.device("CPU")` works in other situations, but not this one. And also, if I delete the line `tf.device` and let TF choose device automatically, the bug can sill be replicated.

**Comment by tiruk007** [comment]
@sushreebarsa 
I was able to reproduce the issue on Colab using TF v2.10 in CPU and GPU. Attached gist in [CPU](https://colab.research.google.com/gist/tiruk007/3a562dc0b83e91f1fec204966eb89b15/58181cpu.ipynb) and [GPU](https://colab.research.google.com/gist/tiruk007/a0b6547fbf0407a570860553b045c015/58181gpu.ipynb).

Thank you!

**Comment by cantonios** [comment]
This seems to now be fixed on tf-nightly.  It throws an `InvalidArgumentError` instead of a crash.

If you get the device name wrong, it will auto-select a device.
