### ISSUE TITLE
TensorFlow Lite How to build NNAPI delegate for Android?

### ISSUE THREAD

**Issue by DwayneDuane** [tensorflow/tensorflow#58192]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.10

### Custom Code

No

### OS Platform and Distribution

Android

### Mobile device

N/A

### Python version

N/A

### Bazel version

5.1.1

### GCC/Compiler version

Android NDK 21

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### Current Behaviour?

```shell
I am trying to build TFLite with XNNPACK, GPU (OpenCL), and NNAPI delegate. Please see below for the command I used. The build succeeds, but I cannot find the .so file for the NNAPI delegate. I searched for all the created .so files under `bazel-bin` folder and I only see these:

./tensorflow/lite/libtensorflowlite.so
./tensorflow/lite/libtensorflowlite.so.runfiles/org_tensorflow/tensorflow/lite/libtensorflowlite.so
./tensorflow/lite/delegates/gpu/libtensorflowlite_gpu_delegate.so
./tensorflow/lite/delegates/gpu/libtensorflowlite_gpu_delegate.so.runfiles/org_tensorflow/tensorflow/lite/delegates/gpu/libtensorflowlite_gpu_delegate.so
```
I did `nm -D libtensorflowlite.so | grep Nnapi` to see if perhaps the symbols for NNAPI delegated got baked into libtensorflowlite.so. But that does not appear to be the case.

Am I building NNAPI delegate incorrectly?
```


### Standalone code to reproduce the issue

```shell
bazel build -c opt --config android_arm64 --config=monolithic --copt -DCL_DELEGATE_NO_GL --strip=never //tensorflow/lite:libtensorflowlite.so //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so //tensorflow/lite/delegates/nnapi:nnapi_delegate
```

### Relevant log output

```shell
N/A
```
</details>

**Comment by mohantym** [comment]
Hi @DwayneDuane!

Sorry for the late response. 
Could you skip the other delegate and only use one flag while building Tensorflow lite run time with below command.
Please make sure you have set path for NDK and SDK tool chain and selected android build while running configure.py process( after cloning and checking out master branch).

`bazel build -c opt --config android_arm64 --config=monolithic  --define tflite_with_nnapi=true --strip=never //tensorflow/lite/c:libtensorflowlite_c.so`

Thank you!

**Comment by DwayneDuane** [comment]
@mohantym What you suggested works and allows me to utilise the NNAPI delegate. However, in my use case, I also need to be able to use the GPU delegate. Right now, I am building `libtensorflowlite_gpu_delegate.so` separately, but is there a build flag that allows the GPU delegate to be included within `libtensorflowlite_c.so`? I tried `--define tflite_with_gpu=true` and `--define tflite_with_opencl=true`, but these flags don't seem to work.

**Comment by mohantym** [comment]
@DwayneDuane !

I am not sure on baking all the delegates in to tflite-runtime simultaneously. So my thought was to build them individually and  create a policy to switch to respective delegate when it does not find any supported ops during inference.

But that has not been recommended earlier to avoid any runtime issues.

Thank you!
