### ISSUE TITLE
Quantised fused custom op

### ISSUE THREAD

**Issue by psunn** [tensorflow/tensorflow#58190]
TensorFlow support [converting from composite op to a single fused TFLite custom operation](https://www.tensorflow.org/lite/models/convert/operation_fusion)

We have issues generating fully quantised model containing such fused custom Ops, generated TFLite models from TFLite Converter have fused custom Ops and operations remained as float operation, while have `Quantize` and `Dequantize` nodes in between.
Please review Colab below, we made models to illustrate these issues:
[custom op with multiple inputs and outputs](https://colab.research.google.com/drive/1kVBfxk39NOaWr02abWDeg458HFeyy_gE?usp=sharing)

Any suggestions that we can resolve these issues and make TFLite custom op able to be fully quantised?

**Comment by psunn** [comment]
We did some investigation.
Our team find that when TFLite fusable operator `tfl_fusable_op` was created from custom operator([source code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/lite/transforms/prepare_composite_functions_tf.cc#L115)), the '_tfl_quant_trait' attribute is missing in it.
We then workaround this with a quick fix, by set this attribute to 'tfl_fusable_op' afterwards.

Furthermore, we need to mark the fused tfl.custom op with no side effect, so that 'PruneUnusedOpsWithSideEffect' pass could prune all dangling duplicated tfl.custom ops([source code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/lite/transforms/post_quantize.cc#L357)).
We then workaround this with another quick fix, explicitly make the fused tfl.custom op run through 'PruneUnusedOpsWithSideEffect' pass.

With these updates, both `simple model with custom op` and  `custom op with multiple inputs and outputs` example would work with a generated fully quantised TFLite model.

We are looking for a proper solution for these issues, thus it is able to generate fully quantised model with fused custom ops with API works probably like:
```
def get_implements_signature():
    implements_signature = [
        'name: "custom_op"',
        'attr {key: "tfl_fusable_op" value { b: true } }',
        'attr {key: "_tfl_quant_trait" value { s: "fully_quantizable" } }',
    ]
    return " ".join(implements_signature)

@tf.function(experimental_implements=get_implements_signature())
def custom_op(x):
    ...
```

**Comment by psunn** [comment]
@Tessil, for visibility

**Comment by abattery** [comment]
@haozha111 can you take a look at this feature request at the TFLite converter?

**Comment by rino20** [comment]
@sngyhan FYI

**Comment by psunn** [comment]
https://github.com/tensorflow/tensorflow/pull/58643
We raised our current temporary solution.

We want to explore proper way to mark eligible fused custom operators with NoSideEffect=True
It could be either:
- explicite attribute from Python tf.function API: ‘attr {key: “no_side_effect” value { b : true}}’
- add extra step to traversely verify the custom op graph, i.e., if the fused custom op is composed of operators without side effects, then the fused operator has NoSideEffect=True 

Any suggestions and early reviews are much appreciated.

**Comment by psunn** [comment]
@pkgoogle 
Could you please help reopen this issue?

The issue persists with the latest tf-nightly.
I have attached a Colab notebook [custom op with multiple inputs and outputs](https://colab.research.google.com/drive/1kVBfxk39NOaWr02abWDeg458HFeyy_gE?usp=sharing) that replicates the issue. This notebook is also mentioned above.

**Comment by LakshmiKalaKadali** [comment]
Hi @psunn, 

Could you make an attempt the to resolve your issue by using [AI-Edge-Torch](https://github.com/google-ai-edge/ai-edge-torch), you can find more information here: [googleblog](https://developers.googleblog.com/en/ai-edge-torch-high-performance-inference-of-pytorch-models-on-mobile-devices/).

Here i am putting a sample reference code using ai_edge_pytorch conversion. Can modify as per your requirement
```py

import torch
import torch.nn as nn
import ai_edge_torch

class CustomFusedOp(nn.Module):
    def __init__(self, input_size, hidden_size):
        super(CustomFusedOp, self).__init__()
        # add necessary code here

    def forward(self, input_1, input_2, input_3):
    # Quantization (if qat)
    if self.qat:
      quantized_input_1 = torch.quantize(input_1, dtype=torch.quint8)
      quantized_input_2 = torch.quantize(input_2, dtype=torch.quint8)
      quantized_input_3 = torch.quantize(input_3, dtype=torch.quint8)
      input_1 = quantized_input_1
      input_2 = quantized_input_2
      input_3 = quantized_input_3

    # Pre-custom op
    pre_custom_op_output_1, pre_custom_op_output_2 = self.pre_custom_op(input_1, input_2, input_3)

    # Quantization (if qat)
    if self.qat:
      quantized_pre_custom_op_output_1 = torch.quantize(pre_custom_op_output_1, dtype=torch.quint8)
      pre_custom_op_output_1 = quantized_pre_custom_op_output_1

    # Dummy model
    model_output = self.model(pre_custom_op_output_1)

    # Post-custom op
    output = self.post_custom_op(input_1, pre_custom_op_output_2, model_output)

    # Quantization (if qat)
    if self.qat:
      quantized_output = torch.quantize(output, dtype=torch.quint8)
      output = quantized_output

    return output

sample_input = (torch.randn(1),)

# Convert the model using AI Edge Torch
edge_model = ai_edge_torch.convert(foo.eval(), sample_input)

# Export the model to TFLite format
edge_model.export('Customop_model.tflite')

```

You can try  visualizing the result in [model-explorer](https://github.com/google-ai-edge/model-explorer) as well.

Please try them out and let us know if this resolves your issue. If you still need further help, feel free to open a new issue at the respective repos.

Thank You
