### ISSUE TITLE
error parsing inception v3 file: 64MB python protobuf parsing limit

### ISSUE THREAD

**Issue by ry** [tensorflow/tensorflow#582]
I just upgraded TF to 469b3ddb4bb914a02f496748dd4ee5dbcbd7fce0 and I'm now getting an error importing the inception v3 model provided at https://storage.googleapis.com/download.tensorflow.org/models/inception_dec_2015.zip

I didn't have this problem before the upgrade. Here is the error

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    graph_def.ParseFromString(fileContent)
google.protobuf.message.DecodeError: Error parsing message
```

And this is the code I'm using

```python
import tensorflow as tf

with open("tensorflow_inception_graph.pb", mode='rb') as f:
  fileContent = f.read()
graph_def = tf.GraphDef()
graph_def.ParseFromString(fileContent)

input_layer = tf.placeholder("float", [1, 299, 299, 3])
tf.import_graph_def(graph_def, input_map={ "Mul": input_layer })
```

**Comment by sherrym** [comment]
Could you please try writing fileContent to a file to make sure that you have successfully read the file content? Thanks.

Sherry

**Comment by ry** [comment]
Same code was working before the update. Were you not able to repeat the bug with the above?

**Comment by sherrym** [comment]
I am unable to reproduce the problem.

Sherry

**Comment by ffmpbgrnn** [comment]
Hi, I encountered the same problem with current master, and the whole log are:
```
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcublas.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcudnn.so.6.5 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcurand.so.7.0 locally
[libprotobuf ERROR google/protobuf/src/google/protobuf/io/coded_stream.cc:207] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
Traceback (most recent call last):
  File "classify_image.py", line 214, in <module>
    tf.app.run()
  File "/home/linchaoz/.local/lib/python2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "classify_image.py", line 210, in main
    run_inference_on_image(image)
  File "classify_image.py", line 160, in run_inference_on_image
    create_graph()
  File "classify_image.py", line 142, in create_graph
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message
```

**Comment by ffmpbgrnn** [comment]
However, when I compile `main.cc`, it can load the model. I might be something wrong with the python interface or my python environment. I will update soon.

**Comment by ffmpbgrnn** [comment]
@ry , I got a workaround by changing https://github.com/google/protobuf/blob/master/src/google/protobuf/io/coded_stream.h#L611 to `256 << 20` and then recompile.

**Comment by panmari** [comment]
I run into a similar problem when trying to start the tensorboard on a log generated by a (fairly large) custom network:

```
panmari@pc:~$ tensorboard --logdir PycharmProjects/tensor_stuff/log_render_buffers/
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcublas.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcudnn.so.6.5 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcurand.so.7.0 locally
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/TAG' on path /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/TAG
WARNING:tensorflow:Unable to read TensorBoard tag
Starting TensorBoard  on port 6006
(You can navigate to http://localhost:6006)
[libprotobuf ERROR google/protobuf/src/google/protobuf/io/coded_stream.cc:207] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/event_accumulator.py", line 242, in Update
    self.Reload()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/event_accumulator.py", line 175, in Reload
    for event in self._generator.Load():
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/impl/directory_watcher.py", line 82, in Load
    for event in self._loader.Load():
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/impl/event_file_loader.py", line 53, in Load
    event.ParseFromString(self._reader.record())
DecodeError: Error parsing message
```

The workaround proposed by @ffmpbgrnn fixed it.

**Comment by shicai** [comment]
@ffmpbgrnn it does work. thanks.

**Comment by ry** [comment]
@sherrym, haven't dug into this but still experiencing this bug on 97522f0acd53652baa57e42d06557ebb94bf0c4d and also @ffmpbgrnn's suggestion to change kDefaultTotalBytesLimit did allow me to not crash

**Comment by schmiflo** [comment]
@panmari Same problem here with current master. As soon as the complexity of my graph goes beyond a certain threshold, tensorboard does not pick up any data. It shows the run under runs but there is no graph or summaries. Tensorboard does not show any signs of a complain in the logs. However, if you restart it it fives a similar error message:
```
[libprotobuf ERROR google/protobuf/src/google/protobuf/io/coded_stream.cc:207] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/event_accumulator.py", line 242, in Update
    self.Reload()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/event_accumulator.py", line 175, in Reload
    for event in self._generator.Load():
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/impl/directory_watcher.py", line 82, in Load
    for event in self._loader.Load():
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/summary/impl/event_file_loader.py", line 53, in Load
    event.ParseFromString(self._reader.record())
DecodeError: Error parsing message
```
@ffmpbgrnn Thanks for the fix, works for me

**Comment by kevineger** [comment]
The fix suggested by @ffmpbgrnn resolved the issue for me. It was necessary to increase the size to run `classify_image.py` in `models/image/imagenet`. Thanks for helping out :)

**Comment by raingo** [comment]
Set environment `PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python` would solve this. slower though.

**Comment by sthomp** [comment]
I started receiving the error `A protocol message was rejected because it was too big (more than 67108864 bytes).` after upgrading tensorflow to 0.7.0

**Comment by tmaila** [comment]
I'm experiencing the same issue with the latest 0.7.0 devel docker image when trying to run the image net example

```
docker run -it b.gcr.io/tensorflow/tensorflow:latest-devel
```

```
/tensorflow/tensorflow/models/image/imagenet# python classify_image.py
[libprotobuf ERROR google/protobuf/src/google/protobuf/io/coded_stream.cc:207] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
Traceback (most recent call last):
  File "classify_image.py", line 213, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "classify_image.py", line 209, in main
    run_inference_on_image(image)
  File "classify_image.py", line 159, in run_inference_on_image
    create_graph()
  File "classify_image.py", line 141, in create_graph
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message
```

**Comment by xg1990** [comment]
@raingo 's  solution is also effective !

**Comment by sthomp** [comment]
My solution for now was to downgrade to 0.6.0 and wait for the patch :)

**Comment by saifrahmed** [comment]
@raingo suggestion was the easiest fix

**Comment by vrv** [comment]
FYI, we recently added custom protobuf pip packages that should overcome the 64MiB limit and also provide fast processing in python: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#protobuf-library-related-issues

**Comment by cegeme** [comment]
@vrv 
I got  Segmentation fault (core dumped) after installing protobuf 3.0.0b2.post2. But it works fine with the default protobuf 3.0.0b2. 
```
$ python -c "import tensorflow"
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Segmentation fault (core dumped)
```

**Comment by zxzhijia** [comment]
@ffmpbgrnn 
I'm getting google.protobuf.message.DecodeError: Truncated message. Is this the same problem as "Error parsing message"?
I tried revise the coded_stream.h to 256<<20 and reinstall protobuf. But it still shows me the same error.

**Comment by dzhyeon** [comment]
I've tried solutions listed above: remove tensorflow, protobuf and reinstall with source, reinstall protobuf with 'pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.0.0b2.post2-cp27-none-linux_x86_64.whl'. There is no problem on importing tensorflow. However, when following serving tutorial on https://tensorflow.github.io/serving/serving_basic with my own network, same error occured: [libprotobuf ERROR external/protobuf/src/google/protobuf/io/coded_stream.cc:207] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.

**Comment by haibarasiao** [comment]
@ffmpbgrnn I changed '256<<20' in coded_stream.h,and recompile,but it didn't work. My tensorflow is installed by pip,and then I uninstalled protobuf,download a new one,changed 256<<20,install new protobuf,but,the same error occurred:" A protocol message was rejected because it was too big (more than 67108864 bytes)." Could someone help me? I am crazy...:(
@VDalibard

**Comment by haibarasiao** [comment]
@kevineger Could you show me what you did after you changed 256 << 20 in coded_stream.h? I have done the same thing which did seem not work. Did you reinstall protobuf and tensorflow after you did the 256 changes by bagel?

**Comment by waichee** [comment]
@vrv @raingo  I'm on the latest tensorflow_serving master. We are still having issue with TS serving throwing this error when loading large models. we have tried the various approaches mentioned above and they dont seem to work.

- PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python still getting the same error
- the custom wheel package for protobuf specified here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#protobuf-library-related-issues This doesnt work because bazel installs the submodules (tensorflow and protofbuf) when building tensorflow_serving from source
- `use_fast_cpp_protos=true` and `allow_oversize_protos=true` when running bazel as mentioned here https://github.com/tensorflow/serving/issues/24

Is there any other alternative approaches that doesn't involved manually changing the coded_stream.h file in the bazel cache?

**Comment by vrv** [comment]
@waichee: if building from source and only running in C++, then the protobuf parsing limit should be 2GiB,not 64.  Unfortunately, protobuf doesn't support protos larger than 32-bit (and from my understanding, will not in the near future), so if you have a variable / constant larger than 2GiB, you probably have to manually shard it right now :(

**Comment by waichee** [comment]
@vrv that's bizarre...we are building from source c++ on the following commit hash 59225e413e9680d67ae90196fa536f5271fcf615 from master


this is what we're doing now and we are unable to get it to take in larger than 64Mb model if we remove the sed command on a centos7 base image

```
RUN cd serving && git checkout 59225e413e9680d67ae90196fa536f5271fcf615

RUN cd /app/serving/tensorflow && echo "/usr/lib64/python2.7/site-packages" | ./configure
RUN cd /app/serving && bazel fetch //tensorflow_serving/model_servers:tensorflow_model_server

# Patch Protobuf to allow larger models to be loaded
RUN sed -i 's/64 << 20/512 << 20/g' `find /root/.cache/bazel/_bazel_root/*/external/protobuf/src/google/protobuf/io/coded_stream.h`

# Build Tensor Serving with Bazel
RUN cd /app/serving && bazel build -c opt //tensorflow_serving/model_servers:tensorflow_model_server
```

are we missing something obvious?

**Comment by dpressel** [comment]
Same problem @waichee pointed out here.  I was using Java bindings on the head (as of yesterday).  I patched protobuf as above in the .cache directory and it worked fine after rebuilding.

**Comment by hollinwilkins** [comment]
Hey, I get this same error using Java bindings. Trying the .cache workaround, but would be nice to have an easier, supported way to fix this issue.

**Comment by asimshankar** [comment]
@dpressel @hollinwilkins : FYI #7338 should take care of this since protobuf 3.2.0 raised the limit from 64MB to 2GB

**Comment by dpressel** [comment]
I am still having this problem with Java bindings on latest of r1.0 branch.  A quick look in the tensorflow cache is still showing the 64MB limit.

**Comment by asimshankar** [comment]
Looking at the contents and history of the r1.0 branch (and the `tensorflow/workspace.bzl` file), that change was not included in r1.0, but will be at head and in the 1.1 release.

Hope that helps.

**Comment by dpressel** [comment]
Haha ok, was guessing that was it.  Thanks

**Comment by yvtheja** [comment]
graph_def.ParseFromString(fileContent)
google.protobuf.message.DecodeError: Error parsing message

This error shows up only when tensorflow is used with GPU.
The ParseFromString works fine with CPU with no errors.

**Comment by buaa-luzhi** [comment]
@zxzhijia I have the same question with you, How did you solve it?  Thank you!

**Comment by yvtheja** [comment]
@buaa-luzhi , we had to remove TensorFlow and reinstalled it from the source.

**Comment by buaa-luzhi** [comment]
Thank you for your reply!
You use the tensorflow==0.12.1 version
and my  tensorflow==0.11,
Will there be any impact?
Thank you very much!

在2017-05-19 16:30:38，鹿智by1603117@buaa.edu.cn写道：

@buaa-luzhi , we had to remove TensorFlow and reinstalled it from the source.

**Comment by bushibushi** [comment]
Still encountered a similar issue on 1.4 while using [import_pb_to_tensorboard.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/import_pb_to_tensorboard.py) to analyse a graph. Was able to use it by replacing the graph load from file with a [saved_model load](https://www.tensorflow.org/programmers_guide/saved_model#loading_a_savedmodel_in_python).

**Comment by apple4562251** [comment]
@raingo 's solution is really cool!

**Comment by AlexDag** [comment]
sorry , "https://github.com/google/protobuf/blob/master/src/google/protobuf/io/coded_stream.h#L611 to 256 << 20 and then recompile." - line 611 is one function , what , how must be change this line ?

**Comment by MingtaoGuo** [comment]
just use 'read().strip()'

**Comment by chelseas** [comment]
I'm still having a similar issue, I believe. I tried @raingo 's solution but get this error now: google.protobuf.message.DecodeError: Truncated message.

**Comment by soul-departed** [comment]
> I'm still having a similar issue, I believe. I tried @raingo 's solution but get this error now: google.protobuf.message.DecodeError: Truncated message.

Same here, first got 'DecodeError: Error parsing message', after implementing the env variable, now getting 'DecodeError: Truncated message'

**Comment by yousufj56** [comment]
Actually, i figured out why mine wasn't working. It was because my pb file
was corrupt. So i did the training from the beginning and the new pb file
worked. Could be same issue with yours?

**Comment by duhaime** [comment]
I resolved this by deleting the model I had downloaded and re-downloading.
