### ISSUE TITLE
'tf.AddV2' op is neither a custom op nor a flex op

### ISSUE THREAD

**Issue by galah92** [tensorflow/tensorflow#58208]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): WSL2 (Ubuntu)
- TensorFlow installation (pip package or built from source): 2.10.0
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.10.0

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

```python
import tensorflow as tf
import jax.numpy as jnp


def inc(x):
    return x + 1


x_input = jnp.zeros((1, 28, 28), dtype=jnp.int16)
converter = tf.lite.TFLiteConverter.experimental_from_jax(
    [inc], [[('input1', x_input)]])
tflite_model = converter.convert()
```

I'm getting the following:
```
2022-10-20 22:25:59.199307: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
2022-10-20 22:25:59.199391: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.
2022-10-20 22:25:59.199400: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:371] Ignored change_concat_input_ranges.
loc(fused["xla_computation(inc)/jit(main)/add", "/tmp/ipykernel_30536/2180026997.py":6:0]): error: 'tf.AddV2' op is neither a custom op nor a flex op
error: failed while converting: 'main': 
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: AddV2
Details:
	tf.AddV2(tensor<1x28x28xi16>, tensor<1x28x28xi16>) -> (tensor<1x28x28xi16>)
```

Note that this doesn't happen if I use `dtype=jnp.float32` or `jnp.int32`.
Would appreciate any help here. Thanks!

**Comment by mohantym** [comment]
Hi @galah92 !
I was facing different issue in Colab.
Work around might be to select ops syntax as Addv2 is being supported in select ops list.
```
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
converter.allow_custom_ops = True
```
Thank you!

**Comment by galah92** [comment]
Hi @mohantym , thank you for the answer.
As my final goal is to use TensorFlow Lite Micro, I'm not sure `SELECT_TF_OPS`, custom ops and flex ops are an option for me.
I wonder why can't we use the original "V1" op.

**Comment by mohantym** [comment]
Ok @galah92 !

Thanks for the update. 
By default! Select ops are not enable in tflite-runtime.
You can build with  cmake with select ops support to use select ops operators.

Feel free to take look at [pinto's wheels](https://github.com/PINTO0309/TensorflowLite-bin) which includes select ops support for above issue too.

Thank you!
