### ISSUE TITLE
Input has undefined rank. Received: input_shape=<unknown>

### ISSUE THREAD

**Issue by sleepingcat4** [tensorflow/tensorflow#58211]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.2

### Custom Code

Yes

### OS Platform and Distribution

Google Colab

### Python version

3.7.15

### Current Behaviour?

```shell
A bug happened! I have created a derived version of AlexNet, I think BatchNormalization layers might be the cuprit behind the error. As without BatchNormalization layer it works perfectly fine. 

I don't think it's relevant but I used some custom activation functions. with combination of "relu". Though those functions weren't that different from "relu" so, I don't expect any error. It'll be a great help, if someone can help me to solve this error :)

Relevant pointers and hints will also be appreciated!
```

### Standalone code to reproduce the issue

```shell
# input_shape=(256, 256, 3)
model.build(input_shape=(None, 220, 220, 3))
model.summary()
```

### Relevant log output

```shell
ValueError                                Traceback (most recent call last)
<ipython-input-16-a5158c5140ec> in <module>
      1 # input_shape=(256, 256, 3)
----> 2 model.build(input_shape=(None, 256, 256, 3))
      3 model.summary()

3 frames
/usr/local/lib/python3.7/dist-packages/keras/utils/tf_utils.py in validate_axis(axis, input_shape)
    241   if not rank:
    242     raise ValueError(
--> 243         f'Input has undefined rank. Received: input_shape={input_shape}')
    244 
    245   # Convert axis to list and resolve negatives

ValueError: Input has undefined rank. Received: input_shape=<unknown>
```
</details>

**Comment by mohantym** [comment]
Hi @sleepingcat4 !
Attached relevant [thread](https://stackoverflow.com/questions/69085333/input-has-undefined-rank-tensorshapenone-error-in-building-resnet) for reference. 

Please post this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . 

Thank you!

**Comment by sleepingcat4** [comment]
The issue have been shifted to **Keras Team Repository**
