### ISSUE TITLE
Deep learning : test a small number of images

### ISSUE THREAD

**Issue by HounaidaM** [tensorflow/tensorflow#58213]
Hi everyone,
I work on segmentation of medical images (512 , 512 , 3) on Kaggle notebook.
My private  dataset contains 2 folders : images and labels. Each one is devided on train and test sets.
My U-net code runs correctly (training and testing) on the full dataset.

Now, I want to test the model on a folder containing only 27 images.  
When I execute evaluate function :  _ = model1.evaluate(test_dataset)

I meet this error :

InvalidArgumentError: 2 root error(s) found.
(0) Invalid argument: slice index 1 of dimension 2 out of bounds.
[[{{node strided_slice_1}}]]
[[IteratorGetNext]]
[[IteratorGetNext/_4]]
(1) Invalid argument: slice index 1 of dimension 2 out of bounds.
[[{{node strided_slice_1}}]]
[[IteratorGetNext]]
0 successful operations.
0 derived errors ignored. [Op:__inference_test_function_12429]

Function call stack:
test_function -> test_function

thank you for helps

**Comment by tilakrayal** [comment]
@HounaidaM,
Could you fill issue template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose) and also to expedite the trouble-shooting process, could you please provide a complete code and the TensorFlow version you are using. Thank you!

**Comment by HounaidaM** [comment]
Hello
It's OK, I found the error: The problem was in the type and size of the image.
Thanks a lot
