### ISSUE TITLE
[FEATURE REQUEST] expand decode_csv to work with whole csv files.

### ISSUE THREAD

**Issue by ThaHypnotoad** [tensorflow/tensorflow#5823]
I'm a bit new to tensorflow, so forgive me if this exists and I just missed it, but it seems decode_csv treats csv files exclusively as a set of records, returning a 1D tensor. This makes decoding 2D samples unintuitive (I've yet to figure out how to do so without simply telling numpy to get them and throw them into a placeholder). How much work would it be to either expand the current function or add a new one that works in a similar manner to decode_png?

**Comment by girving** [comment]
`decode_csv` returns what I think you mean by 2-D data as a list of 1-D tensors (two dimensions in total).  I think it should be sufficient, but in any case we can't change it to return a 2-D tensor since (1) it wouldn't handle variable types and (2) it wouldn't be backwards compatible.
