### ISSUE TITLE
No graph trace in tensorboard when using @tf.function(jit_compile=True)

### ISSUE THREAD

**Issue by yz-chen18** [tensorflow/tensorflow#58263]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

Yes

### Current Behaviour?

```shell
I'm trying to trace a model inference. When I turn off jit_compile option, it works fine. However, when I turn it on, no inference graph appears on tensorboard. I wonder what might happen there. Thanks.
```

### Standalone code to reproduce the issue

```shell
logdir = "./xla_dir"

input = np.random.rand(10,3,224,224).astype("float32")

@tf.function(jit_compile=True)
def inf(input):
    # tf_model is a resnet18 model imported from an onnx
    output = tf_model(input_1=input)
    return output

writer = tf.summary.create_file_writer(logdir)
tf.summary.trace_on(graph=True)

inf(input)
with writer.as_default():
    tf.summary.trace_export(
      name="my_func_trace",
      step=0,
      profiler_outdir=logdir)
```

### Relevant log output

_No response_</details>

**Comment by bhack** [comment]
I am tracking also  tracking https://github.com/tensorflow/profiler/issues/503

But the ownership of this issue is still not clear.

/cc @yatbear

**Comment by tilakrayal** [comment]
@yz-chen18,
As mentioned above, Could you please track the issue https://github.com/tensorflow/profiler/issues/503. Thank you!
