### ISSUE TITLE
tflite_runtime.interpreter.Interpreter causes segfault when using delegate

### ISSUE THREAD

**Issue by vn218** [tensorflow/tensorflow#58267]
I am trying to run [label_image.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/python/label_image.py) using tflite-runtime. It works fine without any delegate. However, when I use a delegate, `tflite_runtime.interpreter.Interpreter()` causes a segfault (`tflite_runtime.interpreter.load_delegate()` doesn't cause any problem). I have tried it for the tflite gpu delegate and armnn delegate (for all combinations of backends) with multiple models from the [tflite examples](https://www.tensorflow.org/lite/examples) and it fails for all of them.
The output......

```
(env) odroid@odroid:~/Desktop/project/tflite_sample$ python3 label_image.py   --model_file lite-model_movenet_multipose_lightning_tflite_float16_1.tflite   --label_file labels.txt   --image grace_hopper.bmp -e ../aarch32_build/delegate/libarmnnDelegate.so -o "backends:GpuAcc,CpuAcc,CpuRef;logging-severity:info" 
Loading external delegate from ../aarch32_build/delegate/libarmnnDelegate.so with args: {'backends': 'GpuAcc,CpuAcc,CpuRef', 'logging-severity': 'info'}
Info: ArmNN v30.0.0
Info: Initialization time: 11.71 ms.
INFO: TfLiteArmnnDelegate: Created TfLite ArmNN delegate.
Segmentation fault
```
```
(env) odroid@odroid:~/Desktop/project/tflite_sample$ python3 label_image.py   --model_file lite-model_movenet_multipose_lightning_tflite_float16_1.tflite   --label_file labels.txt   --image grace_hopper.bmp -e ../libtensorflowlite_gpu_delegate.so 
Loading external delegate from ../libtensorflowlite_gpu_delegate.so with args: {}
INFO: Created TensorFlow Lite delegate for GPU.
Segmentation fault
```

I am using an Odroid XU4 board (armv7l) that has a Mali T628 GPU and 2GB RAM running Ubuntu Mate 22.04. I am running the latest version of tflite-runtime, however it fails for all the previous versions as well. Python version is 3.7.14 .

**Comment by mohantym** [comment]
Hi @vn218 !
Could you share the build command used for arm too. 
[CMake procedure ](https://www.tensorflow.org/lite/guide/build_cmake)is recommended to build gpu delegate and benchmark the models for ARM devices.

As Bazel method is not yet enabled for build gpu delegates for ARM devices.
[Ref](https://www.tensorflow.org/lite/guide/build_arm)
Thank you!
