### ISSUE TITLE
A Check Fail can be triggered in GatherNd

### ISSUE THREAD

**Issue by shijy16** [tensorflow/tensorflow#58262]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9 and 2.12.0-dev20221018

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

CUDA 11.5

### Current Behaviour?

```shell
A check-fail can be triggered.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
print(tf.__version__)
for _ in range(20):
    try:
        params = tf.saturate_cast(tf.random.uniform([1, 16, 6, 15, 16, 16], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        indices = tf.saturate_cast(tf.random.uniform([15, 5, 16, 15, 1, 1], minval=0, maxval=64, dtype=tf.int64), dtype=tf.int64)
        res = tf.raw_ops.GatherNd(
            params=params,
            indices=indices,
        )
    except:
        pass
```

### Relevant log output

```shell
F ./tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (0 vs. -1954414592)
Aborted (core dumped)
```
</details>

**Comment by bhack** [comment]
Can you try the same with the high level API?

**Comment by tilakrayal** [comment]
@shijy16,
Probably there is a missing check in the low level API.
Could you please try to reproduce your experiment with the high level API and let us know if you are facing the same issue. Thank you!
