### ISSUE TITLE
A check fail can be triggered in MaxPoolGradWithArgmax

### ISSUE THREAD

**Issue by shijy16** [tensorflow/tensorflow#58272]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9 and 2.12.0-dev20221018

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

CUDA 11.5

### Current Behaviour?

```shell
A crash due to check fail can be triggered in MaxPoolGradWithArgmax.
```

### Standalone code to reproduce the issue

```shell
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import tensorflow as tf
import numpy as np
print(tf.__version__)
for _ in range(20):
    try:
        ksize_0 = 1
        ksize_1 = 2
        ksize_2 = 4
        ksize_3 = 1
        ksize = [ksize_0, ksize_1, ksize_2, ksize_3, ]
        strides_0 = 1
        strides_1 = 2
        strides_2 = 1
        strides_3 = 16
        strides = [strides_0, strides_1, strides_2, strides_3, ]
        padding = "SAME"
        include_batch_in_index = False
        input = tf.saturate_cast(tf.random.uniform([16, 16, 1, 1], minval=0, maxval=64, dtype=tf.int64), dtype=tf.uint64)
        grad = tf.saturate_cast(tf.random.uniform([16, 8, 1, 1], minval=0, maxval=64, dtype=tf.int64), dtype=tf.uint64)
        argmax = tf.saturate_cast(tf.random.uniform([16, 8, 1, 1], minval=0, maxval=64, dtype=tf.int64), dtype=tf.int64)
        res = tf.raw_ops.MaxPoolGradWithArgmax(
            ksize=ksize,
            strides=strides,
            padding=padding,
            include_batch_in_index=include_batch_in_index,
            input=input,
            grad=grad,
            argmax=argmax,
        )
    except:
        pass
```

### Relevant log output

```shell
F tensorflow/core/kernels/maxpooling_op.cc:1065] Check failed: grad_out_index >= output_start && grad_out_index < output_end Invalid output gradient index: 263, 0, 256
Aborted (core dumped)
```
</details>

**Comment by bhack** [comment]
Same as the other issues. Can you try the same with the high level API?

**Comment by tilakrayal** [comment]
@shijy16 ,
Probably there is a missing check in the low level API.
Could you please try to reproduce your experiment with the high level API and let us know if you are facing the same issue. Thank you!

**Comment by bhack** [comment]
@shijy16 More in general if you use the low level API, as in many of your recent tickets, it is expected that the low level API fail on  asserts checks.
E.g. in this case:

https://github.com/tensorflow/tensorflow/blob/69c74d817bc276891bf985aa9b0ab2db96a9f558/tensorflow/core/kernels/maxpooling_op.cc#L1065-L1067

It is also why we recommend to use this in quite restricted use cases:
https://www.tensorflow.org/api_docs/python/tf/raw_ops

> Note: [tf.raw_ops](https://www.tensorflow.org/api_docs/python/tf/raw_ops) provides direct/low level access to all TensorFlow ops. See [the RFC](https://github.com/tensorflow/community/blob/master/rfcs/20181225-tf-raw-ops.md) for details. Unless you are library writer, you likely do not need to use these ops directly.
