### ISSUE TITLE
A check fail can be triggered in ParameterizedTruncatedNormal

### ISSUE THREAD

**Issue by shijy16** [tensorflow/tensorflow#58274]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9 and 2.12.0-dev20221018

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

CUDA 11.5

### Current Behaviour?

```shell
When execute on GPU, a crash due to check fail can be triggered in ParameterizedTruncatedNormal.
```

### Standalone code to reproduce the issue

```shell
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import tensorflow as tf
import numpy as np
print(tf.__version__)
for _ in range(20):
    try:
        seed = 0
        seed2 = 0
        shape_0 = 16
        shape_1 = 9
        shape_2 = 117
        shape_3 = 100
        shape_4 = 71
        shape_5 = 18
        shape = [shape_0, shape_1, shape_2, shape_3, shape_4, shape_5, ]
        means = tf.saturate_cast(tf.random.uniform([], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        stdevs = tf.saturate_cast(tf.random.uniform([], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        minvals = tf.saturate_cast(tf.random.uniform([1], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        maxvals = tf.saturate_cast(tf.random.uniform([], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        res = tf.raw_ops.ParameterizedTruncatedNormal(
            seed=seed,
            seed2=seed2,
            shape=shape,
            means=means,
            stdevs=stdevs,
            minvals=minvals,
            maxvals=maxvals,
        )
    except:
        pass
```

### Relevant log output

```shell
F ./tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (0 vs. -2141792896)
Aborted (core dumped)
```
</details>

**Comment by bhack** [comment]
Probably there is a missing check in the low level API.

@shijy16 Can you try to reproduce your experiment with the high level API 'tf.random.stateless_parameterized_truncated_normal`?

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.9, v2.10 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/237fe6f24e3412bc65a5539a0b5b9105/untitle4.ipynb).

**Comment by sachinprasadhs** [comment]
`tf.random.stateless_parameterized_truncated_normal` is working as expected without any crash. 
Attached the gist [here](https://colab.sandbox.google.com/gist/sachinprasadhs/24d1437331b579595b7ea3ac8f9f549e/58274.ipynb#scrollTo=kzFjhNxprXhz) for reference. 
Basically, `raw_ops` are designed to be consumed by downstream library users, not end users. Refer RFC [here](https://colab.sandbox.google.com/gist/sachinprasadhs/24d1437331b579595b7ea3ac8f9f549e/58274.ipynb#scrollTo=kzFjhNxprXhz). Thanks!
