### ISSUE TITLE
A check fail can be triggered in LSTMBlockCell

### ISSUE THREAD

**Issue by shijy16** [tensorflow/tensorflow#58270]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9 and 2.12.0-dev20221018

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

CUDA 11.5

### Current Behaviour?

```shell
A crash due to check fail can be trigerred.
```

### Standalone code to reproduce the issue

```shell
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import tensorflow as tf
import numpy as np
print(tf.__version__)
for _ in range(20):
    try:
        forget_bias = 112.66590343649887
        cell_clip = 67.12389445926587
        use_peephole = False
        x = tf.saturate_cast(tf.random.uniform([2, 16], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        cs_prev = tf.saturate_cast(tf.random.uniform([2, 0], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        h_prev = tf.saturate_cast(tf.random.uniform([2, 0], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        w = tf.saturate_cast(tf.random.uniform([16, 0], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        wci = tf.saturate_cast(tf.random.uniform([5], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        wcf = tf.saturate_cast(tf.random.uniform([16], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        wco = tf.saturate_cast(tf.random.uniform([13], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        b = tf.saturate_cast(tf.random.uniform([0], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
        res = tf.raw_ops.LSTMBlockCell(
            forget_bias=forget_bias,
            cell_clip=cell_clip,
            use_peephole=use_peephole,
            x=x,
            cs_prev=cs_prev,
            h_prev=h_prev,
            w=w,
            wci=wci,
            wcf=wcf,
            wco=wco,
            b=b,
        )
    except:
        pass
```

### Relevant log output

```shell
F tensorflow/core/kernels/rnn/lstm_ops_gpu.cu.cc:277] Non-OK-status: GpuLaunchKernel( lstm_gates<T, false, gate_layout>, grid_dim_2d, block_dim_2d, 0, cu_stream, gates.data(), b.data(), cs_prev.data(), wci.data(), wcf.data(), wco.data(), o.data(), h.data(), ci.data(), cs.data(), co.data(), i.data(), f.data(), forget_bias, cell_clip, batch_size, cell_size) status: INTERNAL: invalid configuration argument
Aborted (core dumped)
```
</details>

**Comment by bhack** [comment]
Same as the other issues. Can you try the same with the high level API?

**Comment by tiruk007** [comment]
@sushreebarsa 
I was able to reproduce the issue on Colab using TF 2.10 GPU and it works fine inTF 2.10 CPU. Could you please find attached gists [GPU](https://colab.research.google.com/gist/tiruk007/5f7f43c52e93dd077e4ba86c4f80c66a/58270gpu.ipynb) and [CPU](https://colab.research.google.com/gist/tiruk007/594ecff94e3bd7be68e3b2e9e59d3208/58270cpu.ipynb) for reference.

Thank you!

**Comment by sachinprasadhs** [comment]
`tf.raw_ops` are basically designed to be consumed by downstream library users, not end users.
Usually, these APIs are less strict in terms of validation etc which is fine since only library writers are supposed to use these symbols.
If available, please prefer high level API for general use case scenarios. Thanks!

**Comment by mihaimaruseac** [comment]
While these are internal APIs, the check failure could lead to denial of service. In the past this used to be considered a vulnerability, but since the impact is bounded and preventable, now the policy is for these to be files as issues and resolved whenever someone from community wants to pick them up (they're very good first issues). Please don't auto-close these!

**Comment by bhack** [comment]
Same comment as in https://github.com/tensorflow/tensorflow/issues/58271#issuecomment-1344581838

**Comment by mattbahr** [comment]
Hi @mihaimaruseac @bhack would it be alright if I worked on this?

I've been digging around to get familiar with the code, and I can see the log is being made from these lines:
https://github.com/tensorflow/tensorflow/blob/3e009869d30edf899200dda68f98294617a9628f/tensorflow/core/kernels/rnn/lstm_ops_gpu.cu.cc#L269-L283
I tracked the `GpuLaunchKernel` down, and I see where the internal error is being returned, but I haven't been able to find the code for `cudaLaunchKernel`
https://github.com/tensorflow/tensorflow/blob/3e009869d30edf899200dda68f98294617a9628f/tensorflow/core/util/gpu_kernel_helper.h#L102-L116
I'm guessing that I need to add a check of some sort to the `LSTMBlockCellFpropWithCUDA`, but I'm not sure what that check needs to be. Any clues would be appreciated!

**Comment by bhack** [comment]
E.g. check https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sparse_to_dense_op.cc

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sparse_to_dense_op_gpu.cu.cc#L121

**Comment by mattbahr** [comment]
@bhack Ok, I think I see what you're getting at. Instead of using `TF_CHECK_OK`, I could create a function like `LaunchComputeKernels` to return a status, and then use `OP_REQUIRES_OK_ASYNC`. Or is that overcomplicating it? Could I just call `OP_REQUIRES_OK_ASYNC` on the `GpuLaunchKernel` since that returns a status?

**Comment by bhack** [comment]
Yes the problem is that TF_CHECK_OK is an assert.

I think you can try with async. 

/cc @reedwm what do you think?

**Comment by mattbahr** [comment]
@bhack Actually the BlockLSTMOp class inherits from OpKernel and not AsyncOpKernel like in `sparse_to_dense_op.cc` so maybe no async

**Comment by bhack** [comment]
So probably in this case is `OP_REQUIRES_OK`

**Comment by mattbahr** [comment]
@bhack making the switch to `OP_REQUIRES_OK` causes the OP_REQUIRES errors to get logged, but it doesn't crash Python. Do you think I need to add/update any unit tests for this? And if so what file should I be looking in?

**Comment by bhack** [comment]
Have you tried with https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/cudnn_rnn_ops_test.cc ?

**Comment by mattbahr** [comment]
No, I hadn't seen that. I'll check it out. Thanks!

**Comment by mattbahr** [comment]
@bhack I'm a little lost looking at these unit tests. I can see how the tests in the file you linked earlier relate to ops registered in `cudnn_rnn_ops.cc`, but I am having trouble figuring out how I can test my code from this file. Do I need to register a new op? Or did you just intend that as a generic example, in which case should I create a test file specific to `lstm_ops_gpu.cu.cc`? Thanks for your patience. I'm pretty new to C++, and this is my first issue on the project.

**Comment by avd1729** [comment]
[https://colab.research.google.com/drive/1ol-1151DaSH4HTK7MaAC_Ngrv-N2sfhP?usp=sharing](url)
I guess there is no error when running it in google colab , do check this out

**Comment by priyanshu28012002** [comment]
I want to work on this Issue

**Comment by mattbahr** [comment]
I actually already have a solution for this issue. I was just waiting on some guidance on the unit tests. I've been pretty busy over the last few weeks, but I'm planning on putting some time into it this week.

**Comment by AtrikeshM** [comment]
I work on this issue. Please assign me.

**Comment by mihaimaruseac** [comment]
Folks, the way TF (and most OSS projects) work is whoever sends the PR that does the job gets the work. Especially for big projects it is very hard  to keep assigning contributors to issues and then unassign when they turn inactive.

**Comment by jphwang212** [comment]
I am attempting to reproduce the environment. I am using a virtual machine arm64 ubuntu 20.04. When doing a pip install for tensorflow==2.9,
```python
ERROR: Could not find a version that satisfies the requirement tensorflow==2.9.0 (from versions: 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0)
ERROR: No matching distribution found for tensorflow==2.9.0
```
Before moving forward, am I allowed to use a later version like 2.10?
Thank you!

**Comment by mihaimaruseac** [comment]
2.9 is out of life, no longer updated. Always try to fix on master branch, test if the issue reproduces with nightly.

**Comment by jphwang212** [comment]
@mihaimaruseac Understood. Thank you very much!

**Comment by Aadil-Hasun** [comment]
Hey, I was just going through the code, I couldn't locate the `third_party/gpus/cuda/include`  folder. Isn't it supposed to be there?

**Comment by SahilJain8** [comment]
Hello good greetings my name is Sahil and would love to contribute to Tensorflow could anyone help me with it 😊😊

**Comment by CrazyShenanigan** [comment]
The issue can be resolved by disabling the use of oneDNN optimizations in TensorFlow by setting the environment variable "TF_ENABLE_ONEDNN_OPTS" to 0 before importing TensorFlow. (see below code)
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'

Explanation:
The provided code generates random values for inputs to the LSTMBlockCell operation and runs it in a loop for 20 iterations. The LSTMBlockCell operation implements the long short-term memory (LSTM) algorithm, which is a type of recurrent neural network commonly used for sequence processing tasks. The inputs to the LSTMBlockCell operation include the current input values, the previous cell state and output values, and the weights and biases of the LSTM cell.

**Comment by CrazyShenanigan** [comment]
> The issue can be resolved by disabling the use of oneDNN optimizations in TensorFlow by setting the environment variable "TF_ENABLE_ONEDNN_OPTS" to 0 before importing TensorFlow. (see below code) os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
> 
> Explanation: The provided code generates random values for inputs to the LSTMBlockCell operation and runs it in a loop for 20 iterations. The LSTMBlockCell operation implements the long short-term memory (LSTM) algorithm, which is a type of recurrent neural network commonly used for sequence processing tasks. The inputs to the LSTMBlockCell operation include the current input values, the previous cell state and output values, and the weights and biases of the LSTM cell.

assign this issue to me

**Comment by CrazyShenanigan** [comment]
> > The issue can be resolved by disabling the use of oneDNN optimizations in TensorFlow by setting the environment variable "TF_ENABLE_ONEDNN_OPTS" to 0 before importing TensorFlow. (see below code) os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
> > Explanation: The provided code generates random values for inputs to the LSTMBlockCell operation and runs it in a loop for 20 iterations. The LSTMBlockCell operation implements the long short-term memory (LSTM) algorithm, which is a type of recurrent neural network commonly used for sequence processing tasks. The inputs to the LSTMBlockCell operation include the current input values, the previous cell state and output values, and the weights and biases of the LSTM cell.
> 
> assign this issue to me

import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import tensorflow as tf
import numpy as np

# Set random values for inputs
forget_bias = 112.66590343649887
cell_clip = 67.12389445926587
use_peephole = False
x = tf.saturate_cast(tf.random.uniform([2, 16], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
cs_prev = tf.saturate_cast(tf.random.uniform([2, 0], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
h_prev = tf.saturate_cast(tf.random.uniform([2, 0], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
w = tf.saturate_cast(tf.random.uniform([16, 0], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
wci = tf.saturate_cast(tf.random.uniform([5], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
wcf = tf.saturate_cast(tf.random.uniform([16], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
wco = tf.saturate_cast(tf.random.uniform([13], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)
b = tf.saturate_cast(tf.random.uniform([0], minval=0, maxval=64, dtype=tf.int64), dtype=tf.half)

# Run LSTMBlockCell operation in a loop for 20 iterations
for _ in range(20):
    try:
        res = tf.raw_ops.LSTMBlockCell(
            forget_bias=forget_bias,
            cell_clip=cell_clip,
            use_peephole=use_peephole,
            x=x,
            cs_prev=cs_prev,
            h_prev=h_prev,
            w=w,
            wci=wci,
            wcf=wcf,
            wco=wco,
            b=b,
        )
    except:
        pass

This will be the corrected code for this issue.

**Comment by pranjalsrv123** [comment]
@shijy16 is this issue still open? I would like provide solution for the same.

**Comment by varunk47** [comment]
I can contribute if its still not solved

**Comment by anuth212** [comment]
I will also work on this issue.

**Comment by surajraoo** [comment]
I will also work on this issue
