### ISSUE TITLE
Should variables in ExponentialMovingAverage use "get_variable"

### ISSUE THREAD

**Issue by passerbyd** [tensorflow/tensorflow#5827]
zero_debias for moving average was introduced recently on master branches.  (tensorflow/tensorflow/python/training/moving_averages.py)
Variables in func “_zero_debias” is created by "variable_scope.get_variable", while slot_creator creates moving variable with "variables.Variable". This causes some problem when outer scope set “reuse=True”, if we only want to reuse variables of the network but not the moving averages.
At least, the new feature introduces inconsistency on how to maintain moving variables.

**Comment by ppwwyyxx** [comment]
An example I put in #2740:
```python
def f(v):
    ema = tf.train.ExponentialMovingAverage(0.9)
    vema = ema.apply([v])
    return vema

with tf.variable_scope('s'):
    v1 = tf.get_variable('W', shape=[])
    v1 = v1 + 1
    f(v1)
with tf.variable_scope('s', reuse=True):
    v2 = tf.get_variable('W', shape=[])
    v2 = v2 + 1
    f(v2)
```
```
ValueError: Variable s/s_1/s_1/add/ExponentialMovingAverage/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
```

Also, tf.contrib.layers.batch_norm doesn't use debias, thus doesn't have this problem. But should it use it to have a more accurate moving average?

**Comment by joel-shor** [comment]
1) The issue should be fixed currently; zero_debias is no longer the default in ExponentialMovingAverage.
2) There is a strong possibility that is *will* be the default in the future.
3) ExponentialMovingAverage creates variables, so for future safety you might consider using it as if it respected variable scopes (ie don't put it in resuse=True variable scopes that it doesn't need to be in)

**Comment by ppwwyyxx** [comment]
To the 3rd point, EMA always creates variables -- the average itself, why should we make a compromise to the bias variable because it causes problem.

It seems like these variables are created differently: the average is with `create_slot`, and the bias/local_step with `get_variable` which causes the problem. Should we change it so that it doesn't cause problems anymore, instead of not using it?

**Comment by joel-shor** [comment]
Either I'm not understanding your objection, or you've missed my point: if you accept that ExponentialMovingAverage.apply creates variables, and you believe that variables should respect variable scopes, then your example *should* throw an error.

The reason EMAs haven't been broken in this case prior to this because they used the legacy `slot` system, which ignores variable scopes (incorrectly). We might be moving away from this, or incorporating variable scopes into slots (which would also break the code above).

Does that clarify my comment?

**Comment by ppwwyyxx** [comment]
@joel-shor Thanks, now I understand. I didn't know that the slot system is a legacy.
Then the problem would become how to nicely avoid using `reuse=True`. Because currently the paradigm which causes problems is like:
```python
def inference(input):
   # some operations including BatchNorm(with EMA)
   pass
with tf.variable_scope('scope'):
    inference(x1)
with tf.variable_scope('scope', reuse=True):
    inference(x2)
``` 
If we're not supposed to use EMA inside `reuse=True` any more, for `inference(x2)` we'll have to surround a `reuse=True` scope for every operation inside `inference` function except for EMA, right? This could be a lot of work.
One way to work around might be to force `reuse=False` even inside a `reuse=True` scope, which I currently did by
```python
with tf.variable_scope(tf.get_variable_scope(), reuse=False)
```
But I suppose this is not an expected feature?

**Comment by passerbyd** [comment]
ExponentialMovingAverage could be applied either on original variables or on output tensors. It's different from user-defined variables.
If the slot_creator will be replaced in design, there should be a direction for how to maintain averages on mid-output first. (as ppwwyyxx mentioned case)

**Comment by edouardoyallon** [comment]
Hi!
I'm also having this issue when reusing batch normalization layer, and in particular ema:
```
ValueError: Variable deep_net/blabla/moments_6/moments_1/mean/ExponentialMovingAverage/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
```

My objective is to duplicate some variables of a model, to insert them in another model, and then to load them from a check point. Everything works fine except the ema. When I use the trick explained by @ppwwyyxx , by imposing not to reuse variables, I have an issue when I load a model from a checkpoint:

```
NotFoundError (see above for traceback): Key deep_net/blabla/moments_6/moments_1/mean/ExponentialMovingAverage/biased not found in checkpoint
	 [[Node: save_1/RestoreV2_57 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_57/tensor_names, save_1/RestoreV2_57/shape_and_slices)]]
	 [[Node: save_1/RestoreV2_32/_137 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_349_save_1/RestoreV2_32", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
```

Here is the code I use for the BN:

```python
with tf.name_scope(None):
  #with tf.variable_scope():# FIX?
    beta = tf.constant(0.0, shape=[n_out])
    gamma = tf.constant(1.0, shape=[n_out])
    batch_mean, batch_var = tf.nn.moments(x, [0,1,2], name='moments')
    ema=[]
    with tf.variable_scope(tf.get_variable_scope(), reuse=False):
      ema = tf.train.ExponentialMovingAverage(decay=0.99)

    def mean_var_with_update():
      ema_apply_op = ema.apply([batch_mean, batch_var])
      with tf.control_dependencies([ema_apply_op]):
        return tf.identity(batch_mean), tf.identity(batch_var)
    mean, var = tf.cond(phase_train,
      mean_var_with_update,
      lambda: (ema.average(batch_mean), ema.average(batch_var)))

    normed = tf.nn.batch_norm_with_global_normalization(x, mean, var, 
      beta, gamma, 1e-3, affine)
    return normed
```
I guess I'm doing a very newbie error and I would really appreciate any help to fix this!

Thank you very much in advance.

**Comment by hzchenlixin** [comment]
how to solve the problem?
ValueError: Variable deep_net/blabla/moments_6/moments_1/mean/ExponentialMovingAverage/biased does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

**Comment by joel-shor** [comment]
I think this problem should be fixed now. Specifically, in `ExponentialMovingAverage`, `zero_debias=False` by default. If you'd like to experience improved accuracy at the cost of breaking backwards compatibility with old checkpoints, set `zero_bias=True`.

**Comment by kvrd18** [comment]
I get the following error when I use `tf.train.ExponentialMovingAverage` to update `batch_mean` and `batch_var` in batch normalization. This error pops up specifically when I try to restore a checkpoint.

```bash
NotFoundError (see above for traceback): Key D4/cond/D4/moments/moments_1/mean/ExponentialMovingAverage not found in checkpoint 
[[Node: save/RestoreV2_36 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_36/tensor_names, save/RestoreV2_36/shape_and_slices)]] 
[[Node: save/RestoreV2_117/_105 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_561_save/RestoreV2_117", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
```

Do I have to update TensorFlow to the latest version to solve this problem?

**Comment by kvrd18** [comment]
Also, I get this error when I try to train the network in a multi-GPU setting where one would ideally have to reuse variables. How do you solve the issue as specified by @hzchenlixin in https://github.com/tensorflow/tensorflow/issues/5827#issuecomment-280538373?

**Comment by joel-shor** [comment]
Are you synced to head? If so, please copy the code that doesn't work for you.

Also, not that you might experience issues if you are trying to reload checkpoints from a model that was trained with the debias into a model that is not set up to use them.

**Comment by happyyxw511** [comment]
I have seen the same issue when I try to train a new model with ExponentialMovingAverage. I am using tensorflow 1.1.0.

**Comment by physicsrob** [comment]
I'm running into this problem as well while trying to use batch norm on a model across two GPUs.  My use case is basically identical to @ppwwyyxx.  Does anyone have a suggested workaround?

**Comment by ppwwyyxx** [comment]
Oh my solution was just to use `moving_averages.assign_moving_average` without debias factor. But I'd like to see a way with debias as well.

**Comment by shimafoolad** [comment]
On tensorflow 1.12.0, I had the same problem and fixed it by adding the line: 

            with tf.variable_scope(tf.get_variable_scope(), reuse=tf.AUTO_REUSE):

before ema.apply

**Comment by Rajamohanreddyai** [comment]
Hello all,

just follow the below video and export your own model with in a 10 seconds

https://youtu.be/w0Ebsbz7HYA
