### ISSUE TITLE
TinyML (O'Reilly) error running test_hello_world_test

### ISSUE THREAD

**Issue by jepikol** [tensorflow/tensorflow#58275]
Hi,

I cloned (successfully) the git repository (https://github.com/tensorflow/tensorflow.git) from "TinyML" (O'Reilly). But when I run the command:

make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test

I get the following answer:

make: tensorflow/lite/micro/tools/make/Makefile: No such file or directory
make: *** No rule to make target `tensorflow/lite/micro/tools/make/Makefile'.  Stop.

And if I look into the directory "../micro/" I find only a README.md file.

What do I have to do?

Thank you very much for your answer.

André Koller

**Comment by jepikol** [comment]
Hi,

Thanks. I made some progress. Changing zsh for bash, upgrading make to 4.3 and cloned the new repository. But now, when I run:

make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test

I get the following error:

tensorflow/lite/micro/tools/make/flatbuffers_download.sh: line 63: wget: command not found
tensorflow/lite/micro/tools/make/Makefile:489: *** Something went wrong with the flatbuffers download: .  Stop.

Can you help?

Looking forward for your answer

**Comment by bhack** [comment]
I don't know your os but you need to install `wget` e.g. `apt-get install wget` on Debian derived OS

**Comment by jepikol** [comment]
Thanks.
I have macos 12.6 (monterey). I'm not shure to understand your answer. Do I have to use Linux  or can I install wget on my mac, for example with homebrew ?

**Comment by bhack** [comment]
I don't know if the build is official supported on macos so It is better that you open a ticket in the Micro repo directly instead of this repo.

For wget on macos https://stackoverflow.com/questions/33886917/how-to-install-wget-in-macos

**Comment by jepikol** [comment]
WOUWWW!! It worked! I've been stuck on this for days. Many thanks for your help!
 
..
Testing LoadModelAndPerformInference
1/1 tests passed
~~~ALL TESTS PASSED~~~

**Comment by jepikol** [comment]
I juste had to install wget on macos. Befor this I have been reading tens of web pages, nobody never said something about wget.

**Comment by bhack** [comment]
Yes, please open a new Documentation issue in the TF micro repo.
