### ISSUE TITLE
Failed to allocate memory for input tensors - iOS

### ISSUE THREAD

**Issue by DanielZanchi** [tensorflow/tensorflow#58280]
Installed TensorflowLite on an example Xcode project I am using for tests with these version:
```
  - TensorFlowLiteC (2.10.0):
    - TensorFlowLiteC/Core (= 2.10.0)
  - TensorFlowLiteC/Core (2.10.0)
  - TensorFlowLiteSwift (2.10.0):
    - TensorFlowLiteSwift/Core (= 2.10.0)
  - TensorFlowLiteSwift/Core (2.10.0):
    - TensorFlowLiteC (= 2.10.0)
```

When I try to allocate the interpreter:
```
        do {
            try interpreter.allocateTensors()
        } catch {
            print("Error: \(error.localizedDescription)")
        }
```

I get this error:
`Error: Failed to allocate memory for input tensors.
`

The model I am trying to use is the one attached here.

[hifill_inpaint.tflite.zip](https://github.com/tensorflow/tensorflow/files/9852391/hifill_inpaint.tflite.zip)

**Comment by mohantym** [comment]
Hi @DanielZanchi !
Have you checked in nightly version too. Could you let us know your system details too. (Xcode version, OS details ).
Thank you!
