### ISSUE TITLE
Supporting Gather_OP on GPU delegate

### ISSUE THREAD

**Issue by Daveorr** [tensorflow/tensorflow#58295]
**System information**
- OS Platform and Distribution: Ubuntu 20.04.5 LTS
- TensorFlow installed from: source
- TensorFlow version: v2.10.0-rc2 (https://github.com/tensorflow/tensorflow/tree/v2.10.0-rc2)

Hello,

For performance reason I was looking to support `gather_op` on GPU delegate.

After some investigation I've noticed that the shader for such op seems to be already written at 
`/tensorflow/lite/delegates/gpu/common/tasks/gather.cc`

Even tests seems to be already implemented, see:
`/tensorflow/lite/delegates/gpu/common/tasks/gather_test_util.cc`

Is there a particular reason why the support for this op on GPU is not included already? Is it bugged?

I tried to include such op by modifying `model_builder.cc` by adding the operation parser such as:

```
class GatherOperationParser : public TFLiteOperationParser {
 public:
  absl::Status IsSupported(const TfLiteContext* context,
                           const TfLiteNode* tflite_node,
                           const TfLiteRegistration* registration) final {
    return CheckGpuDelegateCompatibility(context, tflite_node, registration);
  }

  absl::Status Parse(const TfLiteNode* tflite_node,
                     const TfLiteRegistration* registration,
                     GraphFloat32* graph, ObjectReader* reader) final {
    Node* node = graph->NewNode();
    node->operation.type = ToString(OperationType::GATHER);
    RETURN_IF_ERROR(reader->AddInput(node, 0));
    RETURN_IF_ERROR(reader->AddInput(node, 1));
    GatherAttributes attr;
    attr.axis = Axis::WIDTH;
    node->operation.attributes = attr;
    return reader->AddOutputs(node);
  }
};
```
after this the gpu_delegate (open_cl) run the gather operations inside my model without complaining and I can even see a sharp increasing in performance in terms of inference time. Only problem is that numerical results are wrong (while they are correct if I run gather on CPU).

Any help, advice?

**Comment by Daveorr** [comment]
Thanks for the insights,

My case is pretty simple, I have
- `index` tensor of shapes `(nxm)`
- `params` tensor of shapes `(1xk)` (basically we sample always from a flat tensor)

expected behaviour would be something like:
'''
## INPUTS ##
params = [a,b,c,d,e,f]
index = [[2,3,1], [1,2,3], [1,4,3]]

## OUTPUT#
out = [[c,d,b],[b,c,d],[b,e,d]]
'''

But I noticed that `gather_OP` for cl GPU delegate is tested only for the case in which `index` and `params` are both flat tensor, do you know by chance if this case is supposed to be supported already so I can better understand how to fix this behavior?

Do you also know by chance what is the expected OOB behavior of this op when running on GPU?

**Comment by yuwenjun1988** [comment]
> "Is there a particular reason why the support for this op on GPU is not included already? Is it bugged?" The reason is very limited support of parameters, it will work correctly only in specific case. Looks like your case is not supported or smt else is wrong.


Is it supported that one of the two inputs of the gather operator is a constant tensor? 
Thanks！

**Comment by yuwenjun1988** [comment]
Has the problem of incorrect accuracy of the gather operator been solved?

**Comment by grantjensen** [comment]
We have just merged a parser for the Gather op for OpenCl. Unfortunately, using a >=1 dimensional index is a narrow use case, and a pain to implement. To me the reward/effort ratio is not there. As such, your example listed above is not supported. If you would like to add support, please submit a PR. Thanks.
