### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by 971766904** [tensorflow/tensorflow#58291]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

Yes

### OS Platform and Distribution

linux ubuntu 22.04

### Python version

3.10

### GCC/Compiler version

11.2.0

### Current Behaviour?

```shell
tensorflow can't be imported in terminal, but can be imported in pycharm.
```

### Standalone code to reproduce the issue

```shell
import tensorflow
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/zy/anaconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/zy/anaconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow10DeviceNameIN5Eigen9GpuDeviceEE5valueB5cxx11E

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zy/anaconda3/envs/tf/lib/python3.10/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/zy/anaconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/zy/anaconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "/home/zy/anaconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: /home/zy/anaconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN10tensorflow10DeviceNameIN5Eigen9GpuDeviceEE5valueB5cxx11E
```
</details>

**Comment by bhack** [comment]
Can you try to make a fresh install from the terminal using the official guide?

https://www.tensorflow.org/install/pip#linux

**Comment by 971766904** [comment]
> Can you try to make a fresh install from the terminal using the official guide?
> 
> https://www.tensorflow.org/install/pip#linux

thanks, the official guide can't help. I got the same importerror.

**Comment by bhack** [comment]
Have you tried to change the name of the Conda environment in "3. Create a conda environment" so you can test the procedure on a fresh one?

**Comment by 971766904** [comment]
> Have you tried to change the name of the Conda environment in "3. Create a conda environment" so you can test the procedure on a fresh one?



> Have you tried to change the name of the Conda environment in "3. Create a conda environment" so you can test the procedure on a fresh one?

Thanks, the problem has been solved by reinstall tensorflow with`conda install tensorflow`. But why `pip install tensorflow` can't work.
