### ISSUE TITLE
Feature request - support tif images in image_dataset_from_directory

### ISSUE THREAD

**Issue by ggous** [tensorflow/tensorflow#58292]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Mint

### Python version

3.9

### Current Behaviour?

```shell
Currently, `image_dataset_from_directory` supports only  `Allowed formats: ('.bmp', '.gif', '.jpeg', '.jpg', '.png')`

So, if you have tif images it won't find them ` No images found in directory `
```

### Standalone code to reproduce the issue

```shell
-
```

### Relevant log output

_No response_</details>

**Comment by bhack** [comment]
This FR has a dependency over `tf.image.decode_image`.
We have a TIF decoder at https://www.tensorflow.org/io/api_docs/python/tfio/experimental/image/decode_tiff but as `image_dataset_from_directory` is a Keras API  that rely on `tf.image.decode_image` that doesn't support TIF images.

You have two options:
- You could edit this ticket title and description to request the extension of `tf.image.decode_image` to support TIF. I don't suggest you to do this as it was rejected recently at https://github.com/tensorflow/tensorflow/issues/54648#issuecomment-1055278551
- You could open [a ticket in the  Keras repo](https://github.com/keras-team/keras) to request the adoption of the `tf.io` dependency to extend the list of supported image in this API.
