### ISSUE TITLE
RNN support in tensorflow slim

### ISSUE THREAD

**Issue by alexgkendall** [tensorflow/tensorflow#5830]
Is there any plan to build RNN support into tf.slim layers? Or is there a road map for tf.slim development that you could please share?

**Comment by reuben** [comment]
See also https://github.com/tensorflow/models/issues/70

**Comment by martinwicke** [comment]
There will be RNN layers in tf.layers. They will likely look like Keras' layers, and similar to the RNNCell objects in contrib/ now.

You may also be interested in DynamicRNNEstimator in contrib/learn.

I guess the answer is that we're working on it. I will close this -- if you have a specific feature request you can open another issue.
