### ISSUE TITLE
Random.stateless_binomial is not available on GPU

### ISSUE THREAD

**Issue by XWarin** [tensorflow/tensorflow#58319]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10

### Custom Code

Yes

### OS Platform and Distribution

Linux

### Mobile device

debian 

### Python version

3.10

### CUDA/cuDNN version

cuda11/cudnn8

### GPU model and memory

Tesla V100-PCIE-16GB

### Current Behaviour?

```shell
In distributed environnement  on  2 GPU 
python    -u mainTest2.py --n_gpu=2
generates a bug generating binomial random sample (works well with normal random)
```

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf
import time
import sys, os
import argparse
import matplotlib

parser = argparse.ArgumentParser()
parser.add_argument('--n_gpus', type=int, default=1)
args = parser.parse_args()
n_gpus = args.n_gpus


device_type = "GPU"
devices = tf.config.experimental.list_physical_devices(
          device_type)
devices_names = [d.name.split('e:')[1] for d in devices]
print("DEVICES ", devices_names)
print("NGPU USED" , n_gpus)
strategy = tf.distribute.MirroredStrategy( devices=devices_names[:n_gpus])


with strategy.scope():   
    optimizerControl= tf.keras.optimizers.Adam(learning_rate = 1e-3)
    modelControl = tf.keras.Sequential([tf.keras.layers.Dense(8, activation = tf.nn.relu),
                                        tf.keras.layers.Dense(1 )])
    # CREATE the random generator under the strategy scope : then using distribute different streams are used
    gen = tf.random.Generator.from_seed(1)

@tf.function
def cal():
    #x= gen.normal( [])
    x= gen.binomial(shape=[1], counts= 100. , probs=0.2)
    return x

x= strategy.run(cal) 
print(" x val ", x)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/gpfsgaia/home/C97830/MASTEREQUATION1D/PYTHON/mainTest2.py", line 36, in <module>
    x= strategy.run(cal) 
  File "/home/C97830/ANACONDA_TF271/envs/TFNEWGPU/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 1315, 
in run
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
  File "/home/C97830/ANACONDA_TF271/envs/TFNEWGPU/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py", line 2891, 
in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)
  File "/home/C97830/ANACONDA_TF271/envs/TFNEWGPU/lib/python3.10/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 676
, in _call_for_each_replica
    return mirrored_run.call_for_each_replica(
  File "/home/C97830/ANACONDA_TF271/envs/TFNEWGPU/lib/python3.10/site-packages/tensorflow/python/distribute/mirrored_run.py", line 83, in c
all_for_each_replica
    return wrapped(args, kwargs)
  File "/home/C97830/ANACONDA_TF271/envs/TFNEWGPU/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in err
or_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/C97830/ANACONDA_TF271/envs/TFNEWGPU/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 54, in quick_execu
te
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation binomial: Could not satisfy explicit dev
ice specification '/job:localhost/replica:0/task:0/device:GPU:0' because no supported kernel for GPU devices is available.
Colocation Debug Info:
Colocation group had the following types and supported devices: 
Root Member(assigned_device_name_index_=1 requested_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' assigned_device_name_='/job
:localhost/replica:0/task:0/device:GPU:0' resource_device_name_='/job:localhost/replica:0/task:0/device:GPU:0' supported_device_types_=[CPU
] possible_devices_=[]
StatefulRandomBinomial: CPU 
_Arg: GPU CPU 

Colocation members, user-requested devices, and framework assigned devices, if any:
  binomial_resource (_Arg)  framework assigned device=/job:localhost/replica:0/task:0/device:GPU:0
  binomial (StatefulRandomBinomial) /job:localhost/replica:0/task:0/device:GPU:0

Op: StatefulRandomBinomial
Node attrs: S=DT_INT32, T=DT_FLOAT, dtype=DT_INT32
Registered kernels:
  device='CPU'; dtype in [DT_INT64]; T in [DT_DOUBLE]
  device='CPU'; dtype in [DT_INT64]; T in [DT_FLOAT]
  device='CPU'; dtype in [DT_INT64]; T in [DT_HALF]
  device='CPU'; dtype in [DT_INT32]; T in [DT_DOUBLE]
  device='CPU'; dtype in [DT_INT32]; T in [DT_FLOAT]
  device='CPU'; dtype in [DT_INT32]; T in [DT_HALF]
  device='CPU'; dtype in [DT_DOUBLE]; T in [DT_DOUBLE]
  device='CPU'; dtype in [DT_DOUBLE]; T in [DT_FLOAT]
  device='CPU'; dtype in [DT_DOUBLE]; T in [DT_HALF]
  device='CPU'; dtype in [DT_FLOAT]; T in [DT_DOUBLE]
  device='CPU'; dtype in [DT_FLOAT]; T in [DT_FLOAT]
  device='CPU'; dtype in [DT_FLOAT]; T in [DT_HALF]
  device='CPU'; dtype in [DT_HALF]; T in [DT_DOUBLE]
  device='CPU'; dtype in [DT_HALF]; T in [DT_FLOAT]
  device='CPU'; dtype in [DT_HALF]; T in [DT_HALF]

	 [[{{node binomial}}]] [Op:__inference_cal_68]
```
</details>

**Comment by bhack** [comment]
> 'Because no supported kernel for GPU devices is available.'ì

It is not related to the distributed scope is that this kernel is registered available only on CPU device:

https://github.com/tensorflow/tensorflow/commit/1dc93053290e0c42f2d5f5515ba6a3577b74dd3e#diff-f1dd8832f1da21ec2f59283757f802d8db2d3951062a12281e5019f24bba016bR528

```python
import tensorflow as tf
tf.config.set_soft_device_placement(False)

counts = [10., 20.]
# Probability of success.
probs = [0.8]
with tf.device("CPU"):
  binomial_samples = tf.random.stateless_binomial(
    shape=[2], seed=[123, 456], counts=counts, probs=probs)
  print("CPU ", binomial_samples)
with tf.device("GPU"):
  binomial_samples = tf.random.stateless_binomial(
    shape=[2], seed=[123, 456], counts=counts, probs=probs)
  print("GPU ", binomial_samples)
```

**Comment by bhack** [comment]
P.s. This is a feature request.

**Comment by Sar-thak-3** [comment]
Hi @sachinprasadhs , I was looking into this bug and I would love to correct it but the "tensorflow/python/ops/gen" file which actually contains the code of stateless_random_binomial is git ignored, so if I can help and contribute to it in any way do let me know!
Also if tensorflow is having any feature requests or bug fixation to be done, kindly let me know I would love to contribute!

**Comment by sachinprasadhs** [comment]
Hi @Sar-thak-3 , Thanks for showing interest to help Tensorflow community.

`gen` files are  autogenerated files during build, original source code for these will be in` .td` files.

You are always welcome to choose any issues which doesn't have any PR linked to create a new one. 

Ideal ones for contributions is to look for "stat:contribution welcome" label. 
[Here](https://github.com/tensorflow/tensorflow/issues?page=1&q=is%3Aopen+is%3Aissue+label%3A%22stat%3Acontribution+welcome%22) is a link for all such issues. Thanks!

**Comment by Sar-thak-3** [comment]
Hi @sachinprasadhs , thanks a lot for your prompt response. It would be great if you can share the contributing guidelines which include the libraries and things that need to be installed priorly. As I was trying to make changes in C++ files, but while running simply as C++ file it is showing a lot of errors. I believe there is a specific procedure to first set up which I can't find and I need your help in the same.

**Comment by sachinprasadhs** [comment]
Please refer: https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
