### ISSUE TITLE
Failed to compile tf2.11.0-rc1 on windows

### ISSUE THREAD

**Issue by henrysky** [tensorflow/tensorflow#58323]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf2.11.0-rc1

### Custom Code

No

### OS Platform and Distribution

Windows 11 22H2 x64

### Mobile device

N/A

### Python version

3.10

### Bazel version

5.3.1

### GCC/Compiler version

MSVC v17.3.6

### CUDA/cuDNN version

cuda 11.8, cudnn 8.6

### GPU model and memory

NVIDIA GTX1650 Mobile

### Current Behaviour?

Failed to compile tf2.11.0-rc1. The same machine can compile tf2.10.0 without any issue.

I suspect the issue is coming from #54276, because I can cherrypick the commit 054fb0b61946b04eee5f26cddbd7abeca06e3691 to undo and the compilation can reach further until it hit with error ``command is longer than CreateProcessW's limit (32768 characters)`` which is a sperate issue

Tensorflow 2.11 rc1 wheel on pypi also did not contain anything (only 1.9kb in size): https://pypi.org/project/tensorflow/2.11.0rc1/#files

### Standalone code to reproduce the issue

```shell
(py310) C:\Users\{redacted}\Downloads\tensorflow-2.11.0-rc1>python ./configure.py
You have bazel 5.3.1 installed.
Please specify the location of python. [Default is C:\Users\{redacted}\miniconda3\envs\py310\python.exe]:


Found possible Python library paths:
  C:\Users\{redacted}\miniconda3\envs\py310\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\{redacted}\miniconda3\envs\py310\lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]:
No TensorRT support will be enabled for TensorFlow.

Found CUDA 11.8 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include
Found cuDNN 8 in:
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/lib/x64
    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include


Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus. Each capability can be specified as "x.y" or "compute_xy" to include both virtual and binary GPU code, or as "sm_xy" to only include the binary code.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]: 7.5,8.6


Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]: /arch:AVX2


Would you like to override eigen strong inline for some C++ compilation to reduce the compilation time? [Y/n]:
Eigen strong inline overridden.

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]:
Not configuring the WORKSPACE for Android builds.

(py310) C:\Users\{redacted}\Downloads\tensorflow-2.11.0-rc1>bazel build //tensorflow/tools/pip_package:build_pip_package --define=no_tensorflow_py_deps=true --config=opt
```

### Relevant log output

https://astro.utoronto.ca/~hleung/shared/tf211_windows_msvccompile.log
</details>

**Comment by tilakrayal** [comment]
@henrysky,
Could you please confirm whether you are compiling the tf v2.11.0-rc1 from [here](https://github.com/tensorflow/tensorflow/tree/v2.11.0-rc1). If you are not following this, requesting to try to compile this and let us know if you are facing the same issue. Thank you!

**Comment by henrysky** [comment]
@tilakrayal 
Yes I compile it from https://github.com/tensorflow/tensorflow/archive/refs/tags/v2.11.0-rc1.zip. 

Moreover, the fact https://pypi.org/project/tensorflow/2.11.0rc1/#files windows wheel contains nothing indicates something is wrong with tensorflow 2.11 compilation on windows even for official release!

**Comment by henrysky** [comment]
Is there any reason why Tensorflow is not supporting native Windows CPU/GPU wheel officially anymore?

**Comment by tilakrayal** [comment]
@henrysky,
The current TensorFlow version, 2.10, is the last TensorFlow release that will support GPU on native-Windows. Starting with TensorFlow 2.11, you will need to install [TensorFlow in WSL2](https://tensorflow.org/install/pip#windows-wsl2), or install tensorflow_cpu and, optionally, try the [TensorFlow-DirectML-Plugin](https://github.com/microsoft/tensorflow-directml-plugin#tensorflow-directml-plugin-). Also please take a look at the official doc [link](https://www.tensorflow.org/install/pip#windows-native) for the reference. Thank you!
