### ISSUE TITLE
Still 0.11.RC0 after upgrading to RC2

### ISSUE THREAD

**Issue by zuoxingdong** [tensorflow/tensorflow#5832]
I've used Anaconda-Pip installation in the tutorial to upgrade my TensorFlow

```
# Ubuntu/Linux 64-bit, CPU only, Python 3.5
(tensorflow)$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0rc2-cp35-cp35m-linux_x86_64.whl

# Python 3
(tensorflow)$ pip3 install --ignore-installed --upgrade $TF_BINARY_URL

....> ipython

In [1]: import tensorflow as tf
In [2]: tf.__version__
Out[2]: '0.11.0rc0'

```

But it seems it is still in RC0, in which doesn't include new method such as `tf.summary.merge_all()`

**Comment by prb12** [comment]
Could you please check the TF version from python3 directly?

**Comment by omtcyfz** [comment]
@prb12 
```
# Ubuntu/Linux 64-bit, CPU only, Python 3.5
(tf) omtcyfz@omtcyfz-VW:~$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0rc2-cp35-cp35m-linux_x86_64.whl
(tf) omtcyfz@omtcyfz-VW:~$ pip3 install --ignore-installed --upgrade $TF_BINARY_URL
Collecting tensorflow==0.11.0rc2 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0rc2-cp35-cp35m-linux_x86_64.whl
(tf) omtcyfz@omtcyfz-VW:~$ python3
Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
[GCC 6.2.0 20160927] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> tensorflow.__version__
'0.11.0rc2'
```
My `__version__` is just fine.

**Comment by zuoxingdong** [comment]
@prb12 

`
...> python3
Python 3.5.2 |Continuum Analytics, Inc.
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'0.11.0rc0'
>>> `

I've tried to show TF version directly on python3, it still returns RC0

**Comment by zuoxingdong** [comment]
@omtcyfz 

Are you using Anaconda virtual environment ?

**Comment by omtcyfz** [comment]
@zuoxingdong No, I am using `virtualenv` installed via pip. python3 is installed via apt-get.

**Comment by omtcyfz** [comment]
@zuoxingdong 

As for

> And it shows above that my GCC version is 4.4.7, and in @omtcyfz 's comment, it shows GCC 6.2.0

This shouldn't have any effect. Basically, 6.2.0 is up-to-date GCC on Ubuntu 16.10 and 4.4.7 is what Anaconda comes with.

**Comment by zuoxingdong** [comment]
@omtcyfz 

Under `..../anaconda3/envs/tensorflow/lib/python3.5/site-packages`, I found 3 related folders
```

/tensorflow
/tensorflow-0.11.0.dist-info
/tensorflow-0.11.0rc2.dist-info
```

**Comment by zuoxingdong** [comment]
@prb12 @omtcyfz 

UPDATE: 
I found there is directory `~/.local/lib/python3.5/site-packages/tensorflow-0.11.0rc0.dist-info`. It seems the import will use this folder for tensorflow. Can I just delete this folder ? I am not sure if it is base file or shouldn't be deleted

**Comment by zuoxingdong** [comment]
FINAL UPDATE:

   Problem resolved. When using Anaconda virtual environment, I need to `pip3 uninstall tensorflow` under vanilla terminal environment, and then `import tensorflow` will search the correct place within the virtual environment. The reason might be because I was installing tensorflow once in vanilla environment. So it is given priority to import.

**Comment by prb12** [comment]
@zuoxingdong Just to check - did you use the `--system-site-packages` flag for `virtualenv`?

**Comment by zuoxingdong** [comment]
@prb12 

I think no. The routine I used is 

```
# Python 3.5
$ conda create -n tensorflow python=3.5
```

`$ source activate tensorflow`

```
# Ubuntu/Linux 64-bit, CPU only, Python 3.5
(tensorflow)$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp35-cp35m-linux_x86_64.whl
```

```
# Python 3
(tensorflow)$ pip3 install --ignore-installed --upgrade $TF_BINARY_URL
```

**Comment by prb12** [comment]
OK - So I'm guessing that the Anaconda method picks up system site packages, but `virtualenv --system-site-packages` doesn't.  
 
I'm going to close this issue now.

**Comment by zuoxingdong** [comment]
@prb12 Thanks for the reply. I guess maybe if it is helpful to add a simple statement in the Installation tutorial -> Anaconda Installation as a note that if anyone has installed tensorflow previously rather than conda environment, it should pip uninstall it for Anaconda to search the correct path to import tensorflow ?
