### ISSUE TITLE
Support for C++ Builder 11.2 

### ISSUE THREAD

**Issue by delphianaus** [tensorflow/tensorflow#58338]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

binary

### Tensorflow Version

TF 2.8

### Custom Code

No

### OS Platform and Distribution

Windows 11 x64

### Current Behaviour?

```shell
Is there anyway to support C++ Builder 11.2 ? current static libs are in a format not supported by C++ Builder. Static libs are only in COFF format so they cant be linked with in C++ builder , they need to be in OMF format for C++ builder to link the static libs. the only way i can solve this is to do a loadlibrary in code and get proc address of each function
```

### Standalone code to reproduce the issue

```shell
No able to link static libs only in MSVC not C++ builder.
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @delphianaus !
Could you close this issue as duplicate to #58298.
Thank you!

**Comment by mohantym** [comment]
Thank you!
