### ISSUE TITLE
@faheemirfan  I changed

### ISSUE THREAD

**Issue by MyRache** [tensorflow/tensorflow#58337]
import tensorflow.compat.v2 as tf
from google3.image.understanding.object_detection.input_readers import input_reader_google_pb2  # pylint: disable=unused-import
from google.protobuf import text_format
from object_detection import export_tflite_graph_lib_tf2
from object_detection.protos import pipeline_pb2

how can ı change mine ı couldn't find

**Comment by bhack** [comment]
Please fill the issue template.

Thanks.

**Comment by tiruk007** [comment]
@MyRache 
Can you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose)
Thank you!

**Comment by mihaimaruseac** [comment]
@tiruk007 you don't need to repeat the same message as before. You can just add the label, if needed.
