### ISSUE TITLE
`GenerateBoundingBoxProposals` does not have cpu implementation

### ISSUE THREAD

**Issue by creakseek** [tensorflow/tensorflow#58349]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### CUDA/cuDNN version

n/a

### Current Behaviour?

```shell
Cannot run Op:GenerateBoundingBoxProposals on CPU
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

scores = np.random.uniform(0.1, 0.9, size=(1, 100, 1))
bbox_deltas = np.random.uniform((- 0.5), 0.5, size=(1, 100, 4))
image_info = np.random.uniform(size=(1, 3))
anchors = np.random.uniform(size=(1, 100, 4))
proposals = tf.image.generate_bounding_box_proposals(scores, bbox_deltas, image_info, anchors, nms_threshold=0.7, pre_nms_topn=6000, min_size=16, post_nms_topn=300)
```

### Relevant log output

```shell
NotFoundError: Could not find device for node: {{node GenerateBoundingBoxProposals}} = GenerateBoundingBoxProposals[post_nms_topn=300]
All kernels registered for op GenerateBoundingBoxProposals:
  device='GPU'
 [Op:GenerateBoundingBoxProposals]
```
</details>

**Comment by tanzhenyu** [comment]
It doesn't seem this is supported on TPU as well. My general question is should we have a kernel to support this at all, or this can be achieved through using other existing ops?

**Comment by tunika78** [comment]
> 

import tensorflow as tf
import numpy as np

scores = np.random.uniform(0.1, 0.9, size=(1, 100, 1))
bbox_deltas = np.random.uniform((- 0.5), 0.5, size=(1, 100, 4))
image_info = np.random.uniform(size=(1, 3))
anchors = np.random.uniform(size=(1, 100, 4))
proposals = tf.image.generate_bounding_box_proposals(scores, bbox_deltas, image_info, anchors, nms_threshold=0.7, pre_nms_topn=6000, min_size=16, post_nms_topn=300)

**Comment by bhack** [comment]
@tanzhenyu The problem is that the GPU Kernel is monolithic/custom:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/image/generate_box_proposals_op.cu.cc

Nobody internally has tried to lower this OP with XLA, so who has analyzed the compatibility/composability of this Tensor program with *HLO? And in the case is compatible do we have still other XLA limits (missing bridge coverage, dynamic shape, tc..)?

P.s. I assume that we could consider the "bridge covered" TF ops a superset that could be mapped to *HLO ops.

I think, more generally, we are still in the perimeter of (@paynecl): 
https://github.com/openxla/xla/discussions/17

**Comment by tanzhenyu** [comment]
> @tanzhenyu The problem is that the GPU Kernel is monolithic/custom: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/image/generate_box_proposals_op.cu.cc
> 
> Nobody internally has tried to lower this OP with XLA, so who has analyzed the compatibility/composability of this Tensor program with *HLO? And in the case is compatible do we have still other XLA limits (missing bridge coverage, dynamic shape, etc..)?
> 
> P.s. I assume that we could consider the "bridge covered" TF ops a superset that could be mapped to *HLO ops.
> 
> I think, more generally, we are still in the perimeter of (@paynecl): [openxla/xla#17](https://github.com/openxla/xla/discussions/17)

I hope the ideal state is most tf ops can be composed of, or lowered to xla, and warn users of those ops which don't and eventually deprecate it. But the selection of those xla ops needs to be very careful so in cases like this the guideline will be clear how to build a logic to create bounding box proposals.
As for this particular issue, I still hope we could get rid of the cuda kernel and see if we can support it using native tf ops.

**Comment by bhack** [comment]
> But the selection of those xla ops needs to be very careful so in cases like this the guideline will be clear how to build a logic to create bounding box proposals.

If you read the Jax claim that I've mentioned in that ticket:
> JAX uses XLA to compile staged-out Python programs, which are represented with MHLO. MHLO offers common operations used in machine learning, such as the dot-product, exponential function, and so on. Unfortunately, sometimes these operations (and compositions of these operations) are not sufficiently expressive or performant and users look to external libraries (Triton, Numba) or hand-written code (CUDA, C/C++) to implement operations for their desired program.

So the real point is: 
- What is the process we want to adopt to interact with XLA as "consumers"? 
- What we will do when we have something that "seems" hard to be expressed or "efficiently expressed" with XLA covered ops?

This is the whole point of https://github.com/openxla/xla/discussions/17

**Comment by tiruk007** [comment]
@sushreebarsa 
I was able to reproduce the issue on Colab using TF v2.10. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/18c2ae158bb95fbd96baf78ed26695d2/58349.ipynb) for reference.

Thank you !

**Comment by sushreebarsa** [comment]
@creakseek I faced `InvalidArgumentError` on colab using tf-nightly, please find the [gist ](https://colab.research.google.com/gist/sushreebarsa/b710692f62e2e8039ba58262f06d1877/58349.ipynb#scrollTo=0mrtSlkhA12f)and confirm the same?
Thank you!
