### ISSUE TITLE
RaggedTensorToVariant abort

### ISSUE THREAD

**Issue by creakseek** [tensorflow/tensorflow#58352]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Current Behaviour?

```shell
`tf.raw_ops.RaggedTensorToVariant` crash with abort with `batched_input=True`.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
input_splits = [[0, 2, 3, 5, 6], [0, 1, 2], [0, 1, 2, 3, 4, 5]]
input_values = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
output_tensor = tf.raw_ops.RaggedTensorToVariant(rt_nested_splits=input_splits, rt_dense_values=input_values, batched_input=True)
```

### Relevant log output

```shell
F tensorflow/core/framework/tensor_shape.cc:186] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Expected shape dimensions to be non-negative, got -1
abort (core dumped)
```
</details>

**Comment by creakseek** [comment]
and there's a related [CVE](https://github.com/tensorflow/tensorflow/security/advisories/GHSA-m6cv-4fmf-66xf)

**Comment by tilakrayal** [comment]
@creakseek,
In tf-nightly no crash observed and displaying only **Invalid Argument error** as the arguments you provided are not valid. Hence the session crash problem was taken care in tf-nightly version. Kindly find the gist of it [here](https://colab.research.google.com/gist/SuryanarayanaY/3a4c4735c7fcc71b90a36cb38a4abd18/58354.ipynb). Thank you!

**Comment by bhack** [comment]
It was already protected in the upcoming release `!pip install tensorflow-cpu==2.11.0rc1` so I think we could close it.
