### ISSUE TITLE
How to enable GSPMD?

### ISSUE THREAD

**Issue by xiaodathereal** [tensorflow/tensorflow#58363]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

tf 2.7

### Custom Code

No

### OS Platform and Distribution

Linux 

### Current Behaviour?

```shell
We are trying to utilize GSPMD on a server with 8 GPUS, we find the ut-test cases as follows:
https://github.com/tensorflow/tensorflow/blob/r2.7/tensorflow/compiler/xla/experimental/xla_sharding/xla_sharding_test.py

To dump the IRs, we enable the environment variables as: TF_DUMP_GRAPH_PREFIX=/tmp/generated \
  TF_XLA_FLAGS="--tf_xla_clustering_debug --tf_xla_auto_jit=2" \
  XLA_FLAGS="--xla_dump_hlo_as_text --xla_dump_to=/tmp/generated" \
    my/tensorflow/program".

But, only 4 IRs are saved: mark_for_compilation.pbtxt, mark_for_compilation_annotated.pbtxt, before_mark_for_compilation.pbtxt, before_increase_dynamism_for_auto_jit_pass.pbtxt. None of them is related to SPMD pass.

It seems that our current run does NOT enable GSPMD functionality at all. Is there any tutorial or instructions for us to follow to enable GSPMD on multiple GPUS?
```

### Standalone code to reproduce the issue

```shell
from tensorflow.compiler.xla.experimental.xla_sharding import xla_sharding
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import math_ops
from tensorflow.python.framework import test_util
from tensorflow.python.framework import dtypes
from tensorflow.python.framework import ops
import numpy as np
from tensorflow.python.eager import def_function


class XlaShardingTest(test_util.TensorFlowTestCase):  
  def test_dot_split(self):
    @def_function.function
    def split_helper(tensor):
      device_mesh = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
      split_tensor = xla_sharding.mesh_split(tensor, device_mesh, [0, 1])
      self.assertIsInstance(split_tensor, ops.Tensor)
      split_sharding = xla_sharding.get_tensor_sharding(split_tensor)
      split_shape = xla_sharding.get_sharding_tile_shape(split_sharding)
      expected_shape = [2, 4]
      self.assertEqual(expected_shape, split_shape)

      y_tensor = array_ops.ones([8, 8], dtype=dtypes.float32)
      y_split = xla_sharding.mesh_split(y_tensor, device_mesh, [0, 1])
      result = math_ops.matmul(split_tensor, y_split)
      device_mesh = np.array([[0, 1], [2, 3], [4, 5], [6, 7]])
      result = xla_sharding.mesh_split(result, device_mesh, [0, 1])
      result = math_ops.sqrt(result)
      result = xla_sharding.mesh_split(result, device_mesh, [1, 0])
      return result

    in_tensor = 2 * np.sqrt(2) * array_ops.ones([8, 8], dtype=dtypes.float32)
    result = split_helper(
        array_ops.ones([8, 8], dtype=dtypes.float32))
    self.assertAllEqual(in_tensor, result)


if __name__ == "__main__":
    xlasharding = XlaShardingTest()
    xlasharding.test_dot_split()
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @xiaodathereal !
Not sure on GSPMD ( General and Scalable Parallelization for ML Computation Graphs). But you can mentions the GPU's  you want to use with [tf.device](https://www.tensorflow.org/guide/gpu) / [distribution strategy](https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy) (Sharing policy is there)

Could you post on [TF forum ](https://discuss.tensorflow.org/)for further assitance.

Thank you!

**Comment by xiaodathereal** [comment]
By GSPMD, we mean this paper: https://arxiv.org/abs/2105.04663.

We use the 'xla_sharding.mesh_split' API, but it seems that GSPMD does not enabled at all.

**Comment by mohantym** [comment]
Ok @xiaodathereal !
Thanks for the update.

@sushreebarsa !
Could you look at this issue.

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @xiaodathereal,
We are not sure of how GSPMD works and i gone through the link you provided and unable to found any useful insights to address your issue.Please check the content of generated files for any insights.

Could you please confirm details like what strategy you used for distribution computing and how you enabled GPUs for tensorflow etc.
We also recommend to refer an old issue [here](https://github.com/tensorflow/tensorflow/issues/33043) incase if useful to you.

We recommend to use this [tensorflow.org/xla]/(https://www.tensorflow.org/xla) document and tutorials there to enable XLA for tensorflow models for current TF versions(2.10) and also use tensorflow distribution strategies as mentioned above and [here](https://www.tensorflow.org/tutorials/distribute/input).If you find any difficulties in above please reachout to us.

Thank you.

**Comment by xiaodathereal** [comment]
Thanks for the answer @SuryanarayanaY. But we still want to reproduce the use cases mentioned in the GSPMD paper. 
@ukoxyz could you please check this question?

**Comment by xiaodathereal** [comment]
Thanks for the answer @ukoxyz 

I see the current limitations of directly utilization of GSPMD on TF. But, is there a plan (or time schedule) to open the APIs for users to directly use GSPMD? or the usages of GSPMD are limited on the encapsulated model zoos?

**Comment by ukoxyz** [comment]
It is already directly usable on TPUs. The codebase I mentioned earlier is an example of using it.  However, I don't work on TensorFlow and am not aware of the progress for GPU APIs. On the other hand, JAX has the same API for all backends.

**Comment by xiaodathereal** [comment]
OK, thanks for the answer @ukoxyz

**Comment by sachinprasadhs** [comment]
@xiaodathereal , Could you please close the issue, if your issue is resolved.
Also, refer to the code directory of XLA compiler SPMD [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/compiler/xla/service/spmd), could be of some help for you. Thanks!

**Comment by xiaodathereal** [comment]
Issue closed, thanks
