### ISSUE TITLE
Failed to apply XNNPACK after quantization aware training

### ISSUE THREAD

**Issue by Janus-Shiau** [tensorflow/tensorflow#58376]
### 1. System information

- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installation (pip package): 2.7.0
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.7.0

### 2. Code

The model has two inputs, where the range of first one is [0, 1.0] and then second one is [-1.0, 1.0].

```python
converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(
    os.path.join(dir_name, "model.pb"), inputs, outputs
)
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,  tf.lite.OpsSet.SELECT_TF_OPS,
]

converter.inference_type = tf.int8
converter.default_ranges_stats = (-128, 127)
converter.quantized_input_stats = {
    inputs[0]: {128, 128},
    **({inputs[1]: {0, 128}} if len(inputs) == 2 else {}),
}
output_path = os.path.join(output_path, name + "_quant.tflite")

tflite_model = converter.convert()
open(output_path, "wb").write(tflite_model)
```

### 3. Failure after conversion

We use quantization-aware training to train our models, and the deploy as `tf.int8` TFLite models. 

Actually, the model is converted successful, and fully functional on Qualcomm's CPU and Hexagon. But it run into errors when using XNNPACK delegate.

We test the model with tflite benchmark with xnnpack enabled, and found the following error messages:

```bash
STARTING!
Log parameter values verbosely: [0]
Min num runs: [250]
Num threads: [3]
Graph: [/data/debug/model_quant.tflite]
Enable op profiling: [1]
#threads used for CPU inference: [3]
Use xnnpack: [1]
Loaded model /data/debug/model_quant.tflite
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
XNNPACK delegate created.
INFO: Replacing 132 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 10 partitions.
ERROR: failed to create XNNPACK Value for tensor 103
ERROR: Node number 147 (TfLiteXNNPackDelegate) failed to prepare.

ERROR: Restored original execution plan after delegate application failure.
Failed to apply XNNPACK delegate.
Benchmarking failed.
```

However, XNNPACK is not always failed. It can run normally in some case:

1. If we deploy the model directly without training, it works.
2. Basically we training the model for 40k steps. if we train it shortly, e.g. only 25k, it works.
3. The backbone of the model is HRNet, If we used another architecture, e.g. Hourglass, it works.

We have been haunted by this strange thing for a month, please kindly let us know what's wrong.

Thank you for your time.

**Comment by mohantym** [comment]
Hi @Janus-Shiau !

Can you check with below code snippet and let us know if it works.
```

converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,  tf.lite.OpsSet.SELECT_TF_OPS,
] // Select ops 

converter.inference_type = tf.int8
converter.optimization = [tf.lite.Optimize.DEFAULT] //added default optimization
converter.default_ranges_stats = (0, 255) // Using uint8 style as in input_stats, you have used 0-128 range
converter.quantized_input_stats = {
    inputs[0]: {128, 128},
    **({inputs[1]: {0, 128}} if len(inputs) == 2 else {}),
}
output_path = os.path.join(output_path, name + "_quant.tflite")

tflite_model = converter.convert()
open(output_path, "wb").write(tflite_model)
```

I would suggest you to save  .pb with tf.saved_model format and reload it using 2.x lite converter api for better results.

Thank you!

**Comment by Janus-Shiau** [comment]
I test the `tf.saved_model` on tensorflow 2.7 and 2.10 with 2.x lite converter API. 
But the error is still not solved.

Our converting code is provided as follows:

```python
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model("./artifacts/SaveModel")
converter.inference_type = tf.int8
converter.quantized_input_stats = {"input_1": {128, 128}, "input_2": {0, 128}}
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

with open("model_quant.tflite", "wb") as f:
    f.write(tflite_model)
```

We still have no idea here, thank you for your time and any comment.

**Comment by mohantym** [comment]
Ok @Janus-Shiau !

Would it be possible to share a sample saved model to replicate the issue. 
Another issue might be usage of dynamic batch size (static batch size or batch size = 1) or invalid data format ( NHWC to NCHW is efficient ) in model itself.
[Ref ](https://blog.tensorflow.org/2022/06/Profiling-XNNPACK-with-TFLite.html#:~:text=inference%20and%20detailed%20performance%20information.%20The%20operator%20name%2C%20data%20layout%20(NHWC%20for%20example)%2C%20datatype%20(FP32)%20and%20microkernel%20type%20(if%20applicable)%20are%20shown.)

Thank you!

**Comment by Janus-Shiau** [comment]
I can provide a tester model for you, which contains similar the above error:

```
STARTING!
Log parameter values verbosely: [0]
Min num runs: [250]
Num threads: [3]
Graph: [/data/debug/model_quant.tflite]
Enable op profiling: [1]
#threads used for CPU inference: [3]
Use xnnpack: [1]
Loaded model /data/debug/model_quant.tflite
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
XNNPACK delegate created.
INFO: Replacing 36 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 6 partitions.
ERROR: failed to create XNNPACK Value for tensor 31
ERROR: Node number 42 (TfLiteXNNPackDelegate) failed to prepare.

ERROR: Restored original execution plan after delegate application failure.
Failed to apply XNNPACK delegate.
Benchmarking failed.
```
The model download link:
https://drive.google.com/file/d/19XB3XwbvfhmsvFJ_SKuDQi_QgN5L--2t/view?usp=share_link

**Comment by Janus-Shiau** [comment]
Is there any update? Thanks!

**Comment by Janus-Shiau** [comment]
This error still happens now. Is there any update? Thanks!

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
