### ISSUE TITLE
Input details changed after converting tf model to tflite model 

### ISSUE THREAD

**Issue by MustafaAlahmid** [tensorflow/tensorflow#58380]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 , 64 bit
- TensorFlow installation (pip package or built from source): 2.10 and 2.5 
- TensorFlow library (version, if pip package or github SHA, if built from source): pip 

### 2. Code

> 
> converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
> converter.target_spec.supported_ops = [
>   tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
>   tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
> ]
> tflite_model = converter.convert()
> open("converted_model.tflite", "wb").write(tflite_model)
> 

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

**After converting the model and printing  input details shows this:**

> input_details = interpreter.get_input_details()
> output_details = interpreter.get_output_details()

> print(input_details)
> 

> [{'name': 'serving_default_input_tensor:0', 'index': 0, 'shape': array([1, 1, 1, 3]), 'shape_signature': array([ 1, -1, -1,  3]), 'dtype': <class 'numpy.uint8'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}]

### 5. (optional) Any other info / logs
**the model is object detection model using Tensorflow object detection API, mobilenet v2 320*320** 

.

**Comment by mohantym** [comment]
Hi @MustafaAlahmid !
This has been known issues (shape distortion during conversion) in model conversion.

Work around is to set input/output using [signatures](https://www.tensorflow.org/lite/guide/signatures)(In tf.function declare the input shape) /[ metadata](https://www.tensorflow.org/lite/inference_with_metadata/lite_support) .

Have you checked in nightly version too (It seems to be addressed in nightly version. )
Ref [1,](https://github.com/tensorflow/tensorflow/issues/58143) [2.](https://github.com/tensorflow/tensorflow/issues/57837) 

Thank you!
