### ISSUE TITLE
Misspelling of the word "argument"

### ISSUE THREAD

**Issue by Germantas-IILTD** [tensorflow/tensorflow#58383]
https://github.com/tensorflow/tensorflow/blob/cdf72454805f790b97ad731f5ea9a400ecbbc26d/tensorflow/lite/python/optimize/calibrator.py#L97

**Comment by tilakrayal** [comment]
@Germantas-IILTD,
The PR #58384 has been assigned for reviewing and once it is merged this issue will move to closed status. Thank you!

**Comment by sharmadhiraj86** [comment]
@tilakrayal @Germantas-IILTD If possible can you please let me take this issue and raise a PR? In my one subject, 30% component is there for open source contribution and I have been looking for some issues that can be solved and found this. Also I have to get the PR raised and get it merged. Without that, I won't get marks. I hope you understand. Please assign this issue to me and let me raise a PR. 

Thanking you!

**Comment by tiruk007** [comment]
@Germantas-IILTD 
The [PR](https://github.com/tensorflow/tensorflow/pull/59974) has been assigned for reviewing and once it is merged this issue will move to closed status. 

Thank you!

**Comment by pkgoogle** [comment]
Hi @Germantas-IILTD, the changes are now here: https://github.com/tensorflow/tensorflow/commit/26612c8623c828c786dcebaa3151c5ea6d9ae0ec

Please feel free to close as completed if you have no more open items regarding this issue.
