### ISSUE TITLE
TFLite won't build using ccmake [vs cmake]

### ISSUE THREAD

**Issue by chunky** [tensorflow/tensorflow#58392]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

commit 50a22ec283d14a9142bbd77cac77750714500768

### Custom Code

No

### OS Platform and Distribution

Ubuntu 22.04.1 LTS

### Python version

3.10.6 [ubuntu default]

### GCC/Compiler version

gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

### Current Behaviour?

```shell
From a fresh clone of tensorflow. If I try to build the TFLite minimal example:
* If I use ccmake, I get an error
* If I use cmake, it compiles successfully

[This is an issue because I'm trying to build another tool that requires TFLite, and doing that without using ccmake or cmake-gui is problematic. I found this inconsistency within just-tensorflow while trying to create a minimal test case]
```

### Standalone code to reproduce the issue

```shell
1. Prepare a fresh clone and go to minimal example dir:

git clone https://github.com/tensorflow/tensorflow.git tensorflow_src
cd tensorflow_src/tensorflow/lite/examples/minimal/

2. Make a build dir, build using cmake:
rm -rf build
mkdir build
cd build
cmake ..
make
# Builds and runs without error

2. Make a build dir, build using ccmake:
rm -rf build
mkdir build
cd build
ccmake ..
[in-tui, hit "c" to configure. If it were to work without error, you would then hit "g" to create the Makefiles, then "q" to quit. But, "g" doesn't work because there are errors during configure]
make
```

### Relevant log output

```shell
CMake Error at build/cpuinfo/CMakeLists.txt:262 (ADD_SUBDIRECTORY):
   ADD_SUBDIRECTORY not given a binary directory but the given source
   directory
   "/home/chunky/src/tensorflow_src/tensorflow/lite/examples/minimal/build/clog-source"
   is not a subdirectory of
   "/home/chunky/src/tensorflow_src/tensorflow/lite/examples/minimal/build/cpuinfo".
   When specifying an out-of-tree source a binary directory must be explicitly
   specified.

 CMake Error at build/cpuinfo/CMakeLists.txt:265 (SET_PROPERTY):
   SET_PROPERTY could not find TARGET clog.  Perhaps it has not yet been
   created.
```
</details>

**Comment by mohantym** [comment]
Hi @chunky !
Thanks for reporting this issue. I could replicate this issue in Colab and local machine too.
It is throwing "Cmakelist.txt not found" error in my case.

@miaout17 !
Could you check this issue. Attached [gist](https://colab.sandbox.google.com/gist/mohantym/575d2dde07500a63162c4974772bb260/git_58392.ipynb#scrollTo=BvLOPDcQdNaF) for reference.

Thank you!

**Comment by bhack** [comment]
@mohantym Your gist has many errors/typo like:
```
[Errno 2] No such file or directory: './tensorflow_src/tensorfow'
/content
fatal: not a git repository (or any of the parent directories): .git
```
and you have not replicated the user output as you have instead:
```
CMake Error: The source directory
 "/content/content/tensorflow_src/tensorflow/lite/examples" does not appear to
 contain CMakeLists.txt.
```
cause you are working on the wrong directory.

@chunky I can use `ccmake` without problems with a reproducible env:
```bash
docker run --rm -it ubuntu /bin/bash
apt-get update
apt-get install -y git cmake-curses-gui g++ clang-format
git clone --depth 1 --single-branch --branch r2.10 https://github.com/tensorflow/tensorflow.git tensorflow_src
mkdir tflite_build
cd tflite_build/
ccmake ../tensorflow_src/tensorflow/lite/
# Please remember to configure with `c` twice and the generate with `g`
make

**Comment by mohantym** [comment]
Ok @bhack !
Thanks for correcting me again.

**Comment by bhack** [comment]
> (it was suggesting to run ccmake.. in same directory)

Yes but it was not the problem, the problem is that you was in a folder where the parent you have referred `..` has no  `CMakeLists.txt` that it is exactly the output message it gives your colab.

So probably you want to do something like `cmake ../..` in your gist instead.  
But it is generally better to build in an external directory as suggested by our official documentation https://www.tensorflow.org/lite/guide/build_cmake so you are not going to mix build and sources.

**Comment by mohantym** [comment]
Hi @chunky !
Can you check again with below syntax.
```
git clone --depth 1 --single-branch --branch r2.10 https://github.com/tensorflow/tensorflow.git tensorflow_src
mkdir tflite_build
cd tflite_build/
ccmake ../tensorflow_src/tensorflow/lite/
# Please remember to configure with `c` twice and the generate with `g`
make
```
[Ref.](https://github.com/tensorflow/tensorflow/issues/58392#issuecomment-1300253682)

Thank you!

**Comment by bhack** [comment]
@chunky This is why I have asked you to try to reproduce the same with a controllable environment like docker so we are for sure exactly on the same page.

If you don't want to use a clean/under control environment please check that your custom env respect the tested build configuration:

https://www.tensorflow.org/install/source#tested_build_configurations

`identification is GNU 11.3.0` is not in the table.

**Comment by mohantym** [comment]
Thanks @chunky!  for the confirmation. 
Marking this issue as resolved as you have confirmed that you could build with tested config in above[ comment](https://github.com/tensorflow/tensorflow/issues/58392#issuecomment-1302357022).
Thank you!
