### ISSUE TITLE
Can't build cocoapods TensorflowLite 2.10 on mac M1

### ISSUE THREAD

**Issue by ductranit** [tensorflow/tensorflow#58395]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

Mac os 12.6

### Mobile device

iphone 12 pro max

### Python version

3.10

### Bazel version

5.3.2

### Current Behaviour?

```shell
I can't build the project after import `TensorFlowLiteSwift` and `TensorFlowLiteSelectTfOps` `2.10` from cocoapods. And it only happens on M1 mac, my other intel mac works fine.
```

### Standalone code to reproduce the issue

```shell
There are a lot of "Undefined symbol" when I try to run on device like this 
https://www.dropbox.com/s/t35ef63rkjp9fwu/tensorflowlite_build_bug.png?raw=1

```

### Relevant log output

_No response_</details>
<img width="391" alt="tensorflowlite_build_bug" src="https://user-images.githubusercontent.com/2063905/199160374-22461cfd-b219-4a9d-8f98-64eab93e87a8.png">

**Comment by mohantym** [comment]
Hi @ductranit !

Could you confirm that you have added the TFLiteswift and TFSelectops to pod file and  force loaded the select ops frame work to your Xcode project (Build Settings -> Other Linker Flags).
[Ref ](https://www.tensorflow.org/lite/guide/ops_select#ios)

Thank you!

**Comment by ductranit** [comment]
hi @mohantym, yes, I did add force load in other linker flags
```
-force_load $(SRCROOT)/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.xcframework/ios-arm64/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps
```
And version `2.6.0` is working fine on my M1 mac. This issue only happens on `2.10`

**Comment by mohantym** [comment]
Ok @ductranit !
Thanks for the update.  Feel free to check in nightly version too.

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by ductranit** [comment]
Just notice that I got the same error on nightly build `0.0.1-nightly.20221102`

**Comment by sachinprasadhs** [comment]
This seems to be taken care in the latest version, could you please verify it in using the latest Nightly version or with the latest stable 2.12 version and let us know if you still have any issue.
https://cocoapods.org/pods/TensorFlowLiteSwift 
Thank you.

**Comment by ductranit** [comment]
That's weird, I still got these errors on nightly build and `2.12.0`
```
'TensorFlowLiteSwift', '~> 0.0.1-nightly'
'TensorFlowLiteSelectTfOps', '~> 0.0.1-nightly'

'TensorFlowLiteSwift', '2.12.0'
'TensorFlowLiteSelectTfOps', '2.12.0'
```

<img width="567" alt="Screenshot 2023-06-17 at 10 10 16" src="https://github.com/tensorflow/tensorflow/assets/2063905/a1bb3c5c-d174-4d9c-a63f-825ebe26ea99">

**Comment by ductranit** [comment]
Has anyone successfully built this on a Mac ARM before?
