### ISSUE TITLE
Inconsistent RMSProp implementation compared with Kingma and Ba paper

### ISSUE THREAD

**Issue by maybeLee** [tensorflow/tensorflow#58412]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

N/A

### Mobile device

N/A

### Python version

N/A

### Bazel version

N/A

### GCC/Compiler version

N/A

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### Current Behaviour?

```shell
The Kingma and Ba paper uses the following line to update parameters when implementing Adam.
$\theta_t ←\theta_{t−1}−\frac{\alpha_t \cdot mt}{(\sqrt{v_t} +\hat{\epsilon})}$
In TensorFlow's documentation (https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/RMSprop), RMSProp follows the same way to apply the epsilon $\epsilon$. However, I notice that the implementation of epsilon in RMSProp https://github.com/tensorflow/tensorflow/blob/57e18f3835c07a3dcdea1c4dcd1723e1b9c5dae3/tensorflow/core/kernels/training_ops.cc#L904 is $\sqrt{v_t+\hat{\epsilon}}$ instead of $\sqrt{v_t}+\hat{\epsilon}$ mentioned in the Adam paper. I cross-checked with TensorFlow's implementation in Adam (https://github.com/tensorflow/tensorflow/blob/57e18f3835c07a3dcdea1c4dcd1723e1b9c5dae3/tensorflow/core/kernels/training_ops.cc#L822) and PyTorch's implementation in RMSProp (https://github.com/pytorch/pytorch/blob/ccf6b558a4c58d1ae92689b2a5064916b42eff05/torch/optim/rmsprop.py#L257), they both use $\sqrt{v_t}+\hat{\epsilon}$ instead of $\sqrt{v_t+\hat{\epsilon}}$ implemented in TensorFlow's RMSProp. May I know if you have special handling about the place of epsilon in RMSProp? If it is possible, I guess it would be better to write $\sqrt{v_t}+\hat{\epsilon}$ instead of the current version: $\sqrt{v_t+\hat{\epsilon}}$.
```

### Standalone code to reproduce the issue

```shell
N/A
```

### Relevant log output

_No response_</details>

**Comment by maybeLee** [comment]
I further check with implementation of RMSProp in Keras: https://github.com/keras-team/keras/blob/5ef06f96f1612eb8ded3d00967d26cb29c953d45/keras/optimizers/optimizer_v2/rmsprop.py#L245

The implementation of epsilon in Keras is: $\sqrt{v_t} +\hat{\epsilon}$ instead of $\sqrt{v_t+\hat{\epsilon}}$ implemented in TensorFlow. I guess the TensorFlow's version can be updated?

**Comment by bhack** [comment]
>  I guess the TensorFlow's version can be updated?

I don't understand. There is no TF vs Keras implementation and now the Keras code is in its own repository at https://github.com/keras-team/keras

**Comment by bhack** [comment]
> TF's code uses equation..

Can you show me the line? I see `epsilon` outside of `sqrt`

**Comment by maybeLee** [comment]
As I mentioned in the main body of this issue, please check this line:
https://github.com/tensorflow/tensorflow/blob/cc3ea640850863e3762bfea824e4459a90d7564d/tensorflow/core/kernels/training_ops.cc#L904

**Comment by bhack** [comment]
But in the optimizer is external.

https://github.com/tensorflow/tensorflow/blob/3759a403a7e00a373e6e5f9154e6a15e291ff123/tensorflow/python/keras/optimizer_v2/rmsprop.py#L270-L272

> epsilon | A small constant for numerical stability. This epsilon is "epsilon hat" in the Kingma and Ba paper (in the formula just before Section 2.1), not the epsilon in Algorithm 1 of the paper. Defaults to 1e-7.

So in the optimizer we are in formula before 2.1. I think in the `training_ops` you are in the Algorithm 1 section of the paper.

**Comment by maybeLee** [comment]
Hi @bhack 

If I understand the code correctly, RMSprop has two mode: with momentum and without momentum. 
If RMSprop is executed without momentum, implementation in the optimizer will be executed where the epsilon is external: https://github.com/tensorflow/tensorflow/blob/3759a403a7e00a373e6e5f9154e6a15e291ff123/tensorflow/python/keras/optimizer_v2/rmsprop.py#L216

If RMSprop is executed with momentum, the optimizer will execute the `gen_training_ops.ResourceApplyRMSProp` or the `gen_training_ops.ResourceApplyCenteredRMSProp` functions where the epsilon is internal:
https://github.com/tensorflow/tensorflow/blob/a8813703ad7d9a57ff70737f7da7c2fd8ea193ec/tensorflow/core/kernels/training_ops.cc#L904

https://github.com/tensorflow/tensorflow/blob/a8813703ad7d9a57ff70737f7da7c2fd8ea193ec/tensorflow/core/kernels/training_ops.cc#L921

I re-checked the paper and I find out that both the equation written in Algorithm 1 and equation before 2.1 are written with an external epsilon instead of internal epsilon. I further check PyTorch's implementation for RMSprop with momentum, it is also implemented with an external epsilon:
https://github.com/pytorch/pytorch/blob/ccf6b558a4c58d1ae92689b2a5064916b42eff05/torch/optim/rmsprop.py#L257

I understand the difference is subtle, but I am worrying that this issue may result in some computation errors which can be reduced.

**Comment by bhack** [comment]
The C++ code there is quite old, let see if we could double check it again to evaluate numerical differences.

**Comment by sushreebarsa** [comment]
@maybeLee 
This issue seems to be Keras issue.  Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) as Keras development is fully moving to [github.com/keras-team/keras](http://github.com/keras-team/keras). All issues and PRs related to keras will be addressed in that repo.
To know more see this TF forum discussion ; 
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
