### ISSUE TITLE
TF 2.11.0-rc2 fails to compile on Linux with GPU support due to error related to CUDA tensorRT

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#58419]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.11.0-rc2

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10.6

### Bazel version

5.3.0

### GCC/Compiler version

11.3.0

### CUDA/cuDNN version

11.8

### GPU model and memory

NVidia GeForce 1080ti, 

### Current Behaviour?

```shell
Error with standard compilation following the directions as per TF documentation.

Using tensorrt library from NVidia, v.8.5.1.7-1+cuda11.8
```

### Standalone code to reproduce the issue

```shell
https://www.tensorflow.org/install/source
```

### Relevant log output

```shell
ERROR: /home/nicola/Software/tensorflow-dir/gpu/tensorflow/tensorflow/compiler/tf2tensorrt/BUILD:562:16: Compiling tensorflow/compiler/tf2tensorrt/convert/weights.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/tensorflow/compiler/tf2tensorrt/_objs/trt_weights/weights.pic.d ... (remaining 182 arguments skipped)
tensorflow/compiler/tf2tensorrt/convert/weights.cc: In member function ‘size_t tensorflow::tensorrt::convert::TRT_ShapedWeights::size_bytes() const’:
tensorflow/compiler/tf2tensorrt/convert/weights.cc:61:10: error: enumeration value ‘kUINT8’ not handled in switch [-Werror=switch]
   61 |   switch (type_) {
      |          ^
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-unknown-warning’ may have been intended to silence earlier diagnostics
cc1plus: some warnings being treated as errors
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 483.410s, Critical Path: 58.83s
INFO: 5043 processes: 2258 internal, 2785 local.
FAILED: Build did NOT complete successfully
```
</details>

**Comment by feranick** [comment]
Note: TensorRT version 8.5.1.7-1+cuda11.8 is the only one available on NVidia's repository, regardless of the CUDA version. This means that this will be the only installable version, and no previous versions are available.

**Comment by feranick** [comment]
BTW compilation proceeds fine when TensorRT support is disabled when running `./configure' before compilation.

**Comment by sachinprasadhs** [comment]
@bixia1 , Could you please look at this issue and provide your input. Thanks!

**Comment by bhack** [comment]
Just to not that the `switch` compiler flag was introduced quite recently in TF:

https://github.com/tensorflow/tensorflow/commit/16e2157e9279541e99dd8fdeb3d5b9e80dcc90b8

**Comment by feranick** [comment]
Indeed, compiling is successful (in the sense that it is completed), without the new `switch` compiler flags in `.bazelrc`.

**Comment by bhack** [comment]
> Indeed, compiling is successful (in the sense that it is completed), without the new switch compiler flags in .bazelrc.

That it is why I've mentioned @MichaelHudgins in the previous comment.

**Comment by MichaelHudgins** [comment]
Thanks for the ping, let me look into it.

**Comment by MichaelHudgins** [comment]
We will look to remove the switch flag in .bazelrc before final release of 2.11 and revisit enabling it after.

**Comment by MichaelHudgins** [comment]
The error switch is removed from the release. With https://github.com/tensorflow/tensorflow/pull/58452.

Upon looking further, it appears that line is fixed in a PR that landed after branch cut. 
https://github.com/tensorflow/tensorflow/pull/57954

**Comment by bhack** [comment]
@MichaelHudgins thanks
