### ISSUE TITLE
Converting model to frozen pb causes original model to go into an "Invalid State"

### ISSUE THREAD

**Issue by matthewfernst** [tensorflow/tensorflow#58411]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

2.4

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8

### Current Behaviour?

I currently am trying to convert a Tensorflow 2 Keras model into a Tensorflow 1 frozen pb. My code is able to accomplish this and freezes the model correctly. I do this by creating my model, then saving it as an h5, then load that models h5 as a separate model and freeze it.

However, if I try to load and freeze the model and then continue on to use the original model (the untouched one), it's put into an "Invalid State". I've tried looking to see if there is an issue with the keras backend session being confused or if the two models have the same reference but they are all separate. 

It's as if the original model and the loaded model are the same one. I'm not sure if this is a bug or more likely user error.

### Standalone code to reproduce the issue

```python
# create, compile, train original model | or load original model 

original_model.save('original_model.h5', save_format='h5')
convert_to_pb('original_model.h5')

original_model.predict(inp) # Error occurs here

-----------------------------------------
# Convert Script

import tensorflow as tf

def convert_to_pb(h5_file):
    with tf.compat.v1.keras.backend.get_session() as sess:
        model = tf.keras.models.load_model(h5_file)

        graph = sess.graph
        output_names = [out.op.name for out in model.outputs]
        input_graph_def = graph.as_graph_def()

        for node in input_graph_def.node:
            node.device = ""
        
        frozen_graph = tf.compat.v1.graph_util.convert_variables_to_constants(sess, input_graph_def, output_names)
        frozen_graph = tf.compat.v1.graph_util.remove_training_nodes(frozen_graph)

        tf.io.write_graph(frozen_graph, '.', 'frozen_model.pb', as_text=False)
```

### Relevant log output

```shell
ValueError: Your Layer or Model is in an invalid state. This can happen for the following cases:
1. You might be interleaving estimator/non-estimator models or interleaving models/layers made in tf.compat.v1.Graph.as_default() with model/layers created outside of it. Converting a model to an estimator (via model_to_estimator) invalidates all models/layers made before the conversion (even if they were not the model converted to an estimator). Similarly, making a layer or a model inside a a tf.compat.v1.Graph invalid$tes all layers/models you previously made outside of the graph. 
2. You might be using a custom keras layer implementation with  custom __init__ which didn't call super().__init__.  Please check the implementation of <class 'tensorflow.python.keras.layers.convolutional.Conv2D'> and its bases.
```
</details>

**Comment by tilakrayal** [comment]
@matthewfernst,
I was facing a different error while executing the mentioned code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/570a37623a387d49de4305e95a96c012/untitled727.ipynb) and share the required dependencies. Thank you!

**Comment by matthewfernst** [comment]
@tilakrayal Sorry about that! I created a gist [here](https://colab.research.google.com/gist/matthewfernst/98743463177ee1d85bb4870bb454b79c/untitled727.ipynb) detailing the issue. This is with TF 2.9.2 and it's still having the same issue. Maybe I'm doing something wrong? Thank you for your help!

**Comment by tilakrayal** [comment]
@matthewfernst,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
