### ISSUE TITLE
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero

### ISSUE THREAD

**Issue by alkatar21** [tensorflow/tensorflow#58428]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04.4 LTS

### Python version

3.8.10

### CUDA/cuDNN version

CUDA Version: 11.6

### GPU model and memory

NVIDIA GeForce RTX 2060

### Current Behaviour?

I want to know why tensorflow always spamms that message in the official docker container (`tensorflow/tensorflow:2.10.0-gpu-jupyter`)?
`I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`

This is probably not a problem at runtime, but it is still very annoying that the output is spammed every time.
I only found #56456 which is closed due to inactivity.

I tried https://github.com/tensorflow/tensorflow/issues/56456#issuecomment-1156008981, which I think means:

```py
gpus = tf.config.list_physical_devices('GPU')
if gpus:
  # Restrict TensorFlow to only allocate 1GB of memory on the first GPU
  try:
    tf.config.set_logical_device_configuration(
        gpus[0],
        [tf.config.LogicalDeviceConfiguration(memory_limit=1024)])
    logical_gpus = tf.config.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Virtual devices must be set before GPUs have been initialized
    print(e)
```
but that does not help.

### Standalone code to reproduce the issue

```py
import tensorflow as tf

print(tf.version.GIT_VERSION, tf.version.VERSION)
print(tf.config.list_physical_devices('GPU'))

print(tf.add(1, 1).numpy())
```

### Relevant log output

```shell
I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
v2.10.0-rc3-6-g359c3cdfc5f 2.10.0
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:980] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1616] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 4582 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 2060, pci bus id: 0000:03:00.0, compute capability: 7.5
2
```
</details>

**Comment by bhack** [comment]
This logic now was moved here:

https://github.com/tensorflow/tensorflow/blob/4432e35cb20a6cc42a14ef539cf7fdc4fefcda29/tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc#L951-L1004

As you can see there is a mentioned internal ticket http://b/18228951 that is not accessible to the external users.

But you could understand a bit the logic of this code with:
https://stackoverflow.com/questions/44232898/memoryerror-in-tensorflow-and-successful-numa-node-read-from-sysfs-had-negativ

**Comment by bhack** [comment]
Check https://github.com/tensorflow/tensorflow/pull/58430

**Comment by alkatar21** [comment]
I'm not sure I understand why this is not set correctly on the PC the container is running on, but I understand where the problem is and the note may help a bit.

**Comment by bhack** [comment]
From https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355

> What:		/sys/bus/pci/devices/.../numa_node
Date:		Oct 2014
Contact:	Prarit Bhargava <prarit@redhat.com>
Description:
		This file contains the NUMA node to which the PCI device is
		attached, or -1 if the node is unknown.  The initial value
		comes from an ACPI _PXM method or a similar firmware
		source.  If that is missing or incorrect, this file can be
		written to override the node.  In that case, please report
		a firmware bug to the system vendor.  Writing to this file
		taints the kernel with TAINT_FIRMWARE_WORKAROUND, which
		reduces the supportability of your system.

**Comment by alkatar21** [comment]
This is the note I meant. I just don't understand why it happens in my case that the file is not correctly filled with 0. Everything should be up to date.

**Comment by bhack** [comment]
As you car read there if you manually access to that sysfs on the host and it is `< 0` it could be a firmware issue. You can use the suggested workaround and report it to your PC/laptop/server vendor as it is probably a firmware bug.
