### ISSUE TITLE
OperatorNotAllowedInGraphError: using random seed in tf.function

### ISSUE THREAD

**Issue by thierryherrmann** [tensorflow/tensorflow#58433]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8.10

### CUDA/cuDNN version

11.1.74 / 8.0.5

### GPU model and memory

NVidia Tesla V100-SXM2-32GB

### Current Behaviour?

`tf.random.set_seed()` in a tf.function doesn't seem to do anything.

### Standalone code to reproduce the issue

For reproducible tests it might be useful to set seeds. When using a distributed strategy, it would be nice to have a different seed for each replica, hence set the seed **inside** the tf.function.

I've done tests (without a distributed strategy for sake of simplicity):

This works:

```python
@tf.function
def f(X):
    tf.random.set_seed(X)

f(tf.constant(1))
```

This works too:
```python
@tf.function
def f(X):
    tf.print(tf.random.normal((2,3)))

f(tf.constant(1))
```

But this fails:
```python
@tf.function
def f(X):
    tf.random.set_seed(X)
    tf.print(tf.random.normal((2,3)))

f(tf.constant(1))
```
... with this error: 

```
File "<ipython-input-165-c6a6c2a4e4db>", line 4, in f  *
        tf.print(tf.random.normal((2,3)))
OperatorNotAllowedInGraphError: Using a symbolic `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.
```

Note that setting a seed in a tf.function doesn't seem to work:

```python
@tf.function
def f():
    tf.random.set_seed(1)
    tf.print(tf.random.normal((2,3)))

f()
f()
``` 
prints different values for the two `f()` invocations

Using an externally provided seed for `tf.random.normal()` also results in a `OperatorNotAllowedInGraphError`:
```python
@tf.function
def f(X):
    tf.print(tf.random.normal((2,3), seed=X))

f(tf.constant(1))
```

Consider this last attempt:
```python
class MyModule(tf.Module):
    def __init__(self, seed):
        self.seed = seed
        self.strategy = tf.distribute.MirroredStrategy()

    def _train(self):
        # this works but all replicas have the same seed.
        tf.print(tf.random.normal((2,3), seed=self.seed))

        if False: # replace with True to test
            # the seed differs but this fails with OperatorNotAllowedInGraphError
            repl_id = tf.distribute.get_replica_context().replica_id_in_sync_group
            print(tf.random.normal((2,3), seed=self.seed + repl_id))
    
    @tf.function
    def distributed_train(self):
        self.strategy.run(self._train)

    
module = MyModule(seed=1)
module.distributed_train()
```

Again, this seems silly but the only purpose of using seeds **inside** a tf.function is to provide each replica with a different seed. 
```

**Comment by bhack** [comment]
```python
@tf.function
def f():
    tf.random.set_seed(1)
    tf.print(tf.random.normal((2,3)))

f()
```
is working for me. See https://colab.research.google.com/gist/bhack/815bd1283b4de03f21702c627919047e/untitled181.ipynb

```
@tf.function
def f(X):
    tf.random.set_seed(X)
    tf.print(tf.random.normal((2,3)))

f(tf.constant(1))
```

Is failing cause autograph is not going to covert correctly this condition

https://github.com/tensorflow/tensorflow/blob/bf22440f8485b5af3823cdd1b32b52cbce15b487/tensorflow/python/framework/random_seed.py#L89-L91

**Comment by bhack** [comment]
Basically It is like

```python

@tf.function
def f(X):
    if X == (0,0):
      return True
    return False

print(f(1))
print(f(tf.constant(1))) # This will not work
```

**Comment by mohantym** [comment]
Hi @thierryherrmann !
I think I found the issue here . Actually, you are passing a non integer seed in the tf.random.set_seed which is causing the issue. If only integer value are passed in above reproducible code snippets, I can get the expected values.

Attached resolved [gist](https://colab.sandbox.google.com/gist/mohantym/48e9fa5b2cc6c43f9c664c29a8503a31/git_58433.ipynb#scrollTo=9gDOcl7wcutQ) for reference.

Thank you!

**Comment by thierryherrmann** [comment]
thanks a lot @bhack for your response. Unfortunately for your first code snippet, you mention it works for you. Indeed it works but if you read carefully my initial comment, if you invoke `f()` several times (without redefining the function), it will give you different random numbers, which is not what we expect, given the `tf.random.set_seed(1)`.
That's why in my snippet, I called `f()` twice after the function definition (this was not a typo).

I realize I should have RTFM: [tf.random.set_seed()'s doc](https://www.tensorflow.org/api_docs/python/tf/random/set_seed) contains much more info than I thought. For a repeatable result calling `f()` several times, there is [tf.random.stateless_normal()](https://www.tensorflow.org/api_docs/python/tf/random/stateless_normal) and other `stateless_xxx()` functions.

E.g. this gives the same result for the two invocations of `f()`:
```python
@tf.function
def f():
    tf.random.set_seed(1)
    tf.print(tf.random.stateless_normal([3], seed=[2,4]))

f()
f()
```

I'm not sure I understand your explanation about `if seeds == (0, 0): `. This is part of the `get_seed()` function and not the `set_seed()` function. But thanks for having taken the time to answer and for the snippets.

**Comment by thierryherrmann** [comment]
Thanks a lot @mohantym for your response. Unfortunately I'm afraid the seed I pass is really an integer.  
If you add this line:
```python
tf.print((self.seed + repl_id).dtype)
```
it'll print `tf.int32`

I saw that you replaced `self.seed + repl_id` with just `self.seed` to make the code work.  
But that addition `+ repl_id` was intentional: if you only use `self.seed` both replicas will generate the same random numbers.
By adding `repl_id` you have a different seed for each replica, but if you re-run the code, those two seeds will remain the same (self.seed + 0 for replica0 and self.seed + 1 for replica1), satisfying the reproducibility requirement. Unfortunately this ends with a `OperatorNotAllowedInGraphError`

But thanks for having taken the time to answer, I appreciate it.

**Comment by thierryherrmann** [comment]
Thanks again @bhack, @mohantym for your contribution. I searched more and the `stateless_xxx()` functions are the solution.

This code satisfies my requirements:
```python
class MyModule(tf.Module):
    def __init__(self, seed):
        self.seed = seed
        self.strategy = tf.distribute.MirroredStrategy()

    def _train(self):
        repl_id = tf.distribute.get_replica_context().replica_id_in_sync_group
        tf.print('replica', repl_id, tf.random.stateless_normal((3,), seed=[self.seed + repl_id, self.seed + repl_id]))
    
    @tf.function
    def distributed_train(self):
        self.strategy.run(self._train)

    
module = MyModule(seed=0)
module.distributed_train()
module.distributed_train()

module = MyModule(seed=3)
module.distributed_train()
module.distributed_train()
```

Output:
```
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
replica 0 [-1.697034 -0.481376708 -0.662236929]
replica 1 [1.66521633 1.36637604 0.778631628]
replica 0 [-1.697034 -0.481376708 -0.662236929]
replica 1 [1.66521633 1.36637604 0.778631628]
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
replica 0 [0.248304084 0.671974301 0.445930719]
replica 1 [-0.991607666 0.0630038455 -0.832075655]
replica 0 [0.248304084 0.671974301 0.445930719]
replica 1 [-0.991607666 0.0630038455 -0.832075655]

```

So with a given seed, the results are reproducible: each replica generates different numbers but a second execution will have the replicas generate the same numbers as with the previous execution.
Changing the seed changes completely the sequences as expected.

The issue can be closed with the RTFM label if that exists!!
Thank you both.

**Comment by mohantym** [comment]
Ok @thierryherrmann !

Thanks for the update. Actually, What I meant seed should be a python integer not an integer Tensorflow Tensor.
Marking this as resolved from above comment.

Thank you!

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)

**Comment by thierryherrmann** [comment]
@mohantym 
> What I meant seed should be a python integer not an integer Tensorflow Tensor.

Actually passing the seed to the tf.function as a tf.constant rather than a python int was intentional. autograph reconstructs a new graph on each invocation with a different python int value. While with a tf.constant, it reuses the same graph.
My simplified example doesn't show the input_signatures I use with the tf.function to restrict inputs and ensure only one graph is generated. This wouldn't be serious in my simple example, but in our real (big) model, graph regeneration would take seconds and consume memory.
Fortunately `tf.random.stateless_xxx()` solves everything.
Thanks for your feedback.

**Comment by bhack** [comment]
> Unfortunately for your first code snippet, you mention it works for you. Indeed it works but if you read carefully my initial comment

Yes sorry is that it seems, without the output, that it was empty. But reading again the "text" it is clear. So the pointer to the stateless version is correct.

P.s. the autograph problem mentioned for the non stateless impl at https://github.com/tensorflow/tensorflow/issues/58433#issuecomment-1302627410 is still valid.
