### ISSUE TITLE
TIMEOUT while running the Bazel Tests on windows

### ISSUE THREAD

**Issue by mraunak** [tensorflow/tensorflow#58442]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.11

### Custom Code

No

### OS Platform and Distribution

Windows 10

### Python version

3.10

### Bazel version

5.1

### GCC/Compiler version

MSVC

### Current Behaviour?

```shell
There are a few test cases that failed due to TIMEOUT 
Errors looks like this:
TIMEOUT: //tensorflow/examples/custom_ops_doc/multiplex_3:multiplex_3_test (Summary)
TIMEOUT: //tensorflow/examples/custom_ops_doc/multiplex_2:multiplex_2_test_cpu
TIMEOUT: //tensorflow/examples/adding_an_op:fact_test (Summary)

Expected behavior: The test cases should pass
```

### Standalone code to reproduce the issue

```shell
Run this bazel command to reproduce the issue:

bazel test --action_env=TEMP=/c/tmp --action_env=TMP=/c/tmp --test_env=TF2_BEHAVIOR=1 --experimental_cc_shared_library --enable_runfiles --nodistinct_host_configuration --dynamic_mode=off --config=xla --config=short_logs --announce_rc --build_tag_filters=-no_windows,-no_oss --build_tests_only --config=monolithic --config=opt -k --keep_going --test_output=errors --test_tag_filters=-no_windows,-no_oss,-gpu,-tpu,-v1only --test_size_filters=small,medium --jobs=64 --test_timeout=300,450,1200,3600 --verbose_failures --flaky_test_attempts=3 -- //tensorflow/... -//tensorflow/java/... -//tensorflow/lite/... -//tensorflow/compiler/xla/python/tpu_driver/... -//tensorflow/compiler/...
```

### Relevant log output

```shell
https://tensorflow-ci.intel.com/job/tf-win-testall/21/artifact/test_run.log
```
</details>

**Comment by bhack** [comment]
Do you have access to the specific log? 

E.g.   `C:/67cictjz/execroot/org_tensorflow/bazel-out/x64_windows-opt/testlogs/tensorflow/examples/custom_ops_doc/multiplex_3/multiplex_3_test/test.log`

**Comment by nitins17** [comment]
@cantonios @MarkDaoust Looks like tests in `//tensorflow/examples/custom_ops_doc/...` and `//tensorflow/examples/...` are timing out on Windows. Can you take a look? Thanks!

**Comment by MarkDaoust** [comment]
The bug report links to this CI run:

https://tensorflow-ci.intel.com/job/tf-win-testall/21/artifact/test_run.log

The logs include strange conflicting output about multiplex tests and a few others. The logs look like the runs are passing, but the summary says they're timing out:

```
==================== Test output for //tensorflow/examples/custom_ops_doc/multiplex_3:multiplex_3_test:
Running tests under Python 3.10.2: C:\Jenkins\workspace\tf-win-testall\venv_py310\Scripts\python.exe
[ RUN      ] MultiplexOpRank1Test.test_multiplex_int
...
[       OK ] MultiplexOpRank1Test.test_sparse_op_same
----------------------------------------------------------------------
Ran 6 tests in 0.373s

OK (skipped=1)
================================================================================
```

But it also says:

```
//tensorflow/examples/custom_ops_doc/multiplex_3:multiplex_3_test       TIMEOUT in 3 out of 3 in 300.9s
  Stats over 3 runs: max = 300.9s, min = 300.1s, avg = 300.5s, dev = 0.3s
  C:/67cictjz/execroot/org_tensorflow/bazel-out/x64_windows-opt/testlogs/tensorflow/examples/custom_ops_doc/multiplex_3/multiplex_3_test/test.log
  C:/67cictjz/execroot/org_tensorflow/bazel-out/x64_windows-opt/testlogs/tensorflow/examples/custom_ops_doc/multiplex_3/multiplex_3_test/test_attempts/attempt_1.log
  C:/67cictjz/execroot/org_tensorflow/bazel-out/x64_windows-opt/testlogs/tensorflow/examples/custom_ops_doc/multiplex_3/multiplex_3_test/test_attempts/attempt_2.log
  ```
  
So  I'm kindof lost. 
  
  
  +1 to @bhack 's comment, is it possible to get one of these logs?
  
 > C:/67cictjz/execroot/org_tensorflow/bazel-out/x64_windows-opt/testlogs/tensorflow/examples/custom_ops_doc/multiplex_3/multiplex_3_test/test.log

**Comment by mraunak** [comment]
Hey @bhack and @MarkDaoust, I have attached the logs, but I didn't find much information in them. I re-run it but got the same output log.
[error_log.docx](https://github.com/tensorflow/tensorflow/files/9958245/error_log.docx)

Please let me know if any further information is needed on my end

**Comment by MarkDaoust** [comment]
Thanks @mraunak. Yeah, I guess we were all hoping there would be more details.

@SeeForTwo adjusted the test size, to see if it somehow just needs more time, but I'l not holding my breath on that one given the strange logs: `Ran 6 tests in 0.373s ...  TIMEOUT in 3 out of 3 in 300.9s`

**Comment by SeeForTwo** [comment]
> @SeeForTwo adjusted the test size, to see if it somehow just needs more time, but I'l not holding my breath on that one given the strange logs: `Ran 6 tests in 0.373s ... TIMEOUT in 3 out of 3 in 300.9s`

My change was for consistency for one of the tests. (One of my general philosophies for debugging is that it is better to fix something that is wrong than to assume it's irrelevant.) It did not necessarily increase a timeout. I would be surprised if it helped.

> TIMEOUT in 3 out of 3 in 300.9s

I am not sure what this 5 minute timeout is. My understanding is that these tests have a 1 minute timeout. My guess is that the timeout is in some second layer that is above the tests. (But I could just be confused about something.)

One thing that seems to be in common with the failing tests but different than the majority of tests is that they use custom ops in the typical OSS way where each test loads a dynamically linked library that contains the op. I wonder if loading these libraries could be related to the problem?

**Comment by mraunak** [comment]
Hi All, the issue of TIMEOUT is resolved now, by changing the jobs '--jobs' from the Bazel command from 64 to a lower value, I have set it as 16.

**Comment by SuryanarayanaY** [comment]
Hi @mraunak ,

Glad that you have found a workaround.I think this might be also related to the memory resources and/or CPU cores. Higher value to the `--jobs` argument means higher concurrent jobs. The number of concurrent jobs that Bazel will run is determined not only by the `--jobs` setting, but also by Bazel's scheduler, which tries to avoid running concurrent jobs that will use up more resources (RAM or CPU) than are available, based on some (very crude) estimates of the resource consumption of each job. The behavior of the scheduler can be controlled by the `--local_ram_resources` option.

May be the flag `--local_ram_resources` also might have some effect here. WDYT ? Shall we consider this as resolved. Please confirm. Thanks!
