### ISSUE TITLE
Not able to convert OpenAI hugging face TF Whisper model to int8 model 

### ISSUE THREAD

**Issue by nyadla-sys** [tensorflow/tensorflow#58451]
### 1. System information
- Linux Ubuntu 16.04:

### 2. Code
Provide code to help us reproduce your issues using one of the following options:

#### Option A: Reference colab notebooks

 Reference [[TensorFlow Lite Model Colab](https://colab.research.google.com/drive/1rApSDy3KMoMMaK3SIQwvu21yPas2VFjx?usp=sharing)]

#### Option B: Paste your code here or provide a link to a custom end-to-end colab
https://colab.research.google.com/drive/1rApSDy3KMoMMaK3SIQwvu21yPas2VFjx?usp=sharing

### 3. Failure after conversion
- Model produces correct results with hybrid model.
- Colab session is getting crashed with int8 model

**Comment by nyadla-sys** [comment]
Adding more information

I was able to convert from Hugging face whisper onnx to tflite(int8) model,however am not sure how to run the inference on this model
Could you please review and let me know if there is anything i am missing in onnx to tflite conversion
https://colab.research.google.com/github/usefulsensors/openai-whisper/blob/main/notebooks/whisper_to_onnx_tflite_int8.ipynb
or
I was able to convert HF tf model to hybrid,however not able to generate quantized model
https://colab.research.google.com/github/usefulsensors/openai-whisper/blob/main/notebooks/tflite_from_huggingface_whisper.ipynb

**Comment by nyadla-sys** [comment]
Here is colab crash APP.log
Timestamp,Level,Message
"Nov 4, 2022, 9:11:46 AM",WARNING,WARNING:root:kernel f8c4a776-358c-4ac4-9933-d386576f666a restarted
"Nov 4, 2022, 9:11:46 AM",WARNING,WARNING:root:kernel f8c4a776-358c-4ac4-9933-d386576f666a restarted
"Nov 4, 2022, 9:11:46 AM",INFO,"KernelRestarter: restarting kernel (1/5), keep random ports"
"Nov 4, 2022, 9:11:45 AM",WARNING,"fully_quantize: 0, inference_type: 6, input_inference_type: 9, output_inference_type: 9"
"Nov 4, 2022, 9:11:34 AM",WARNING,Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x7fe2ff331fd0>
"Nov 4, 2022, 9:11:34 AM",WARNING,Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x7fe2ff331fd0>
"Nov 4, 2022, 9:11:34 AM",WARNING,Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x7fe2ff331fd0>
"Nov 4, 2022, 9:11:34 AM",WARNING,Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x7fe2ff331fd0>
"Nov 4, 2022, 9:11:34 AM",WARNING,Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x7fe2ff331fd0>
"Nov 4, 2022, 9:11:27 AM",WARNING,2022-11-04 16:11:27.257091: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.
"Nov 4, 2022, 9:11:27 AM",WARNING,2022-11-04 16:11:27.257004: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
"Nov 4, 2022, 9:09:13 AM",WARNING,2022-11-04 16:09:13.126567: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.
"Nov 4, 2022, 9:09:13 AM",WARNING,2022-11-04 16:09:13.126473: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
"Nov 4, 2022, 9:06:46 AM",WARNING,2022-11-04 16:06:46.670198: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
"Nov 4, 2022, 9:05:52 AM",INFO,Kernel started: f8c4a776-358c-4ac4-9933-d386576f666a
"Nov 4, 2022, 9:05:45 AM",INFO,Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
"Nov 4, 2022, 9:05:45 AM",INFO,http://172.28.0.2:9000/
"Nov 4, 2022, 9:05:45 AM",INFO,The Jupyter Notebook is running at:
"Nov 4, 2022, 9:05:45 AM",INFO,0 active kernels
"Nov 4, 2022, 9:05:45 AM",INFO,Serving notebooks from local directory: /
"Nov 4, 2022, 9:05:45 AM",INFO,google.colab serverextension initialized.
"Nov 4, 2022, 9:05:45 AM",WARNING,    	/root/.jupyter/jupyter_notebook_config.json
"Nov 4, 2022, 9:05:45 AM",WARNING,    	/root/.local/etc/jupyter/jupyter_notebook_config.json
"Nov 4, 2022, 9:05:45 AM",WARNING,    	/usr/etc/jupyter/jupyter_notebook_config.json
"Nov 4, 2022, 9:05:45 AM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.json
"Nov 4, 2022, 9:05:45 AM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.d/panel-client-jupyter.json
"Nov 4, 2022, 9:05:45 AM",WARNING,    	/etc/jupyter/jupyter_notebook_config.json
"Nov 4, 2022, 9:05:45 AM",INFO,Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
"Nov 4, 2022, 9:05:45 AM",INFO,http://172.28.0.12:9000/
"Nov 4, 2022, 9:05:45 AM",INFO,The Jupyter Notebook is running at:
"Nov 4, 2022, 9:05:45 AM",INFO,Serving notebooks from local directory: /
"Nov 4, 2022, 9:05:45 AM",INFO,google.colab serverextension initialized.
"Nov 4, 2022, 9:05:45 AM",WARNING,    	/root/.jupyter/jupyter_notebook_config.json
"Nov 4, 2022, 9:05:45 AM",WARNING,    	/root/.local/etc/jupyter/jupyter_notebook_config.json
"Nov 4, 2022, 9:05:45 AM",WARNING,    	/usr/etc/jupyter/jupyter_notebook_config.json
"Nov 4, 2022, 9:05:45 AM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.json
"Nov 4, 2022, 9:05:45 AM",WARNING,    	/usr/local/etc/jupyter/jupyter_notebook_config.d/panel-client-jupyter.json
"Nov 4, 2022, 9:05:45 AM",WARNING,    	/etc/jupyter/jupyter_notebook_config.json
"Nov 4, 2022, 9:05:45 AM",INFO,Writing notebook server cookie secret to 
/root/.local/share/jupyter/runtime/notebook_cookie_secret
"Nov 4, 2022, 9:05:45 AM",INFO,Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
"Nov 4, 2022, 9:05:45 AM",WARNING,Notebook version 5 is no longer maintained. Please upgrade to version 6 or later.

**Comment by bhack** [comment]
Just for reference, it was cross posted:
https://discuss.huggingface.co/t/convert-openai-whisper-transformer-model-to-quantized-tflite-model/25488
https://github.com/openai/whisper/discussions/464#discussioncomment-4050705

**Comment by nyadla-sys** [comment]
> Just for reference, it was cross posted: https://discuss.huggingface.co/t/convert-openai-whisper-transformer-model-to-quantized-tflite-model/25488 [openai/whisper#464 (comment)](https://github.com/openai/whisper/discussions/464#discussioncomment-4050705)

This post is in Huggingface

**Comment by bhack** [comment]
> This post is in Huggingface
Yes

**Comment by nyadla-sys** [comment]
If I use something like below getting below error

**RuntimeError: Max and min for dynamic tensors should be recorded during calibration: Failed for tensor cond_2/while/cond_1/cond/mul2
Empty min/max for tensor cond_2/while/cond_1/cond/mul2**

_def representative_dataset():
    for x in range(1):
      inputs = processor(ds[x]["audio"]["array"], return_tensors="tf")
      input_features = inputs.input_features
     # input_features = np.array(input_features, dtype=np.float32).reshape(1,80, 3000)
      #input_features = np.array(input_features, dtype=np.uint8).reshape(1,80, 3000)
     # input_features = np.array(input_features-128, dtype=np.int8)
      yield [input_features]

saved_model_dir = '/content/tf_whisper_saved'
tflite_model_path = 'whisper-int8.tflite'

generate_model = GenerateModel(model=model)
concrete_func = generate_model.serving.get_concrete_function()

converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func], generate_model)
#converter = tf.compat.v1.lite.TFLiteConverter.from_concrete_functions([concrete_func], generate_model)
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8,
tf.lite.OpsSet.TFLITE_BUILTINS]
converter.inference_input_type = tf.float32  # or tf.uint8
converter.inference_output_type = tf.int16  # or tf.uint8
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()_

**Comment by bhack** [comment]
I have some memory limit running your Colab. 
Have you really tried to run it with TF nightly as it seems it was mispelled at the first cell of your colab.

**Comment by nyadla-sys** [comment]
@bhack 
I changed first cell of colab to **!pip install tf-nightly**, but I still see the crash while converting to quantized int8 model

**Comment by bhack** [comment]
Yes it seems we have a segmentation fault on nightly:

```gdb
#0  0x00007f623573d7d3 in mlir::quant::QuantizedType::getExpressedType() const () from /usr/local/lib/python3.9/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
#1  0x00007f623573e1ac in mlir::quant::QuantizedType::castFromExpressedType(mlir::Type) ()
   from /usr/local/lib/python3.9/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so
```

**Comment by nyadla-sys** [comment]
@bhack Thanks for confirming

**Comment by mohantym** [comment]
@nyadla-sys !
Integer quantization is not working as Bhack commented  earlier. 

Hi @sachinprasadhs !
Could you look at this issue.

Attached gist in [2.9](https://colab.sandbox.google.com/gist/mohantym/9dc8ca5f6a462ef0398ab29fed75068e/openai-whisper-toquantized-int8-not-working.ipynb#scrollTo=mqA7Cz4HK5s7), [2.10 ](https://colab.sandbox.google.com/gist/mohantym/7ee01b18f79a00682a6729b980b1648e/openai-whisper-toquantized-int8-not-working.ipynb#scrollTo=1Cu-U5i2d1l4)and [nightly](https://colab.sandbox.google.com/gist/mohantym/55113ea4d705394cc0a8e2a25441abb0/openai-whisper-toquantized-int8-not-working.ipynb#scrollTo=TxSxAnYFK62z) for reference.
Thank you!

**Comment by nyadla-sys** [comment]
@sachinprasadhs @mohantym @bhack do you have any update on this ?

**Comment by nyadla-sys** [comment]
Gentle reminder.!

**Comment by nyadla-sys** [comment]
> @nyadla-sys ! Integer quantization is not working as @bhack commented earlier. It might not be possible to get expected results from int8 models ( because of model architecture itself). So, Work around might be to use hybrid models as you suggested.
> 
> Hi @sachinprasadhs ! Could you look at this issue.
> 
> Attached gist in [2.9](https://colab.sandbox.google.com/gist/mohantym/9dc8ca5f6a462ef0398ab29fed75068e/openai-whisper-toquantized-int8-not-working.ipynb#scrollTo=mqA7Cz4HK5s7), [2.10 ](https://colab.sandbox.google.com/gist/mohantym/7ee01b18f79a00682a6729b980b1648e/openai-whisper-toquantized-int8-not-working.ipynb#scrollTo=1Cu-U5i2d1l4)and [nightly](https://colab.sandbox.google.com/gist/mohantym/55113ea4d705394cc0a8e2a25441abb0/openai-whisper-toquantized-int8-not-working.ipynb#scrollTo=TxSxAnYFK62z) for reference. Thank you!

Hybrid model is not suitable to run on TFLite micro or on fixed point DSP's

**Comment by nyadla-sys** [comment]
> @nyadla-sys ! Integer quantization is not working as @bhack commented earlier. It might not be possible to get expected results from int8 models ( because of model architecture itself). So, Work around might be to use hybrid models as you suggested.
> 
> Hi @sachinprasadhs ! Could you look at this issue.
> 
> Attached gist in [2.9](https://colab.sandbox.google.com/gist/mohantym/9dc8ca5f6a462ef0398ab29fed75068e/openai-whisper-toquantized-int8-not-working.ipynb#scrollTo=mqA7Cz4HK5s7), [2.10 ](https://colab.sandbox.google.com/gist/mohantym/7ee01b18f79a00682a6729b980b1648e/openai-whisper-toquantized-int8-not-working.ipynb#scrollTo=1Cu-U5i2d1l4)and [nightly](https://colab.sandbox.google.com/gist/mohantym/55113ea4d705394cc0a8e2a25441abb0/openai-whisper-toquantized-int8-not-working.ipynb#scrollTo=TxSxAnYFK62z) for reference. Thank you!

Hybrid model is not suitable to run on TFLite micro or on fixed point DSP's

**Comment by bhack** [comment]
I suppose that the nightly crash could still be interesting for the TF-lite team

**Comment by nyadla-sys** [comment]
@arfaian Do you have any update on this ?

**Comment by nyadla-sys** [comment]
I could see below error with [2.9](https://colab.sandbox.google.com/gist/mohantym/9dc8ca5f6a462ef0398ab29fed75068e/openai-whisper-toquantized-int8-not-working.ipynb#scrollTo=mqA7Cz4HK5s7) and [2.10](https://colab.sandbox.google.com/gist/mohantym/7ee01b18f79a00682a6729b980b1648e/openai-whisper-toquantized-int8-not-working.ipynb#scrollTo=1Cu-U5i2d1l4)


RuntimeError: Model resulted in Nan value during calibration. Please make sure model results in all real-values during inference with provided dataset.Node number 8 (MUL) failed to invoke.Node number 5 (IF) failed to invoke.Node number 550 (IF) failed to invoke.Node number 694 (WHILE) failed to invoke.

**Comment by nyadla-sys** [comment]
I don't need my input and output to be in int8. I want them to remain as they are, but only want the kernels and weights to be in int8.

##
concrete_func = generate_model.serving.get_concrete_function()
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func], generate_model)
converter.representative_dataset = representative_dataset
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
tflite_model = converter.convert()
##

**Comment by nyadla-sys** [comment]
@arfaian is there any issue with the whisper TF model model ? is it even possible to convert it to quantize model ?

**Comment by nyadla-sys** [comment]
@arfaian Do you have any update on this ?

**Comment by nyadla-sys** [comment]
I still see below issue with tf-nighty
0x00007fffcb614553 in mlir::quant::QuantizedType::getExpressedType() const () from /home/niranjanyadla/useful_sensors/download_tools/openai-work/adhoc/speech-recognition-experiments/whisper-tflite/venv/lib/python3.10/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so

**Comment by arfaian** [comment]
Hey @nyadla-sys, just wanted to let you know that I'm looking into this. Will get back to you once I have some findings or a fix.

**Comment by nyadla-sys** [comment]
@arfaian Thanks for your information.

**Comment by nyadla-sys** [comment]
I was able to successfully separate the encoder and decoder whisper tflite models, and it would be beneficial if we could implement int8 quantization in the following notebook.
https://colab.research.google.com/github/usefulsensors/openai-whisper/blob/main/notebooks/whisper_encoder_decoder_tflite.ipynb

Thanks in Advance

**Comment by nyadla-sys** [comment]
I apologize for bothering you frequently. I do not have any other options for generating the full int8 model of Whisper apart from relying on the TFLite Converter. Do you have an ETA for this feature to be available?

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

**Comment by pkgoogle** [comment]
Hi @nyadla-sys,

Thanks for raising this issue. Are you aware of [AI-Edge-Torch](https://developers.googleblog.com/en/ai-edge-torch-high-performance-inference-of-pytorch-models-on-mobile-devices/)? As we believe this issue is better supported by and more relevant to AI-Edge-Torch we are moving your issue there. Please follow progress [here](https://github.com/google-ai-edge/ai-edge-torch/issues/394).

Let us know if you have any questions. Thanks.
