### ISSUE TITLE
Download of fresh release of clang fails on TF 2.10.0-2.11.0

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#58453]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.11.0-rc2

### Custom Code

No

### OS Platform and Distribution

MacOS 13.0

### Python version

3.10.6

### Bazel version

5.3.0

### GCC/Compiler version

XCode 14.1

### Current Behaviour?

```shell
When requesting the option during `./configure`:


Do you wish to download a fresh release of clang? (Experimental) [y/N]: y
Clang will be downloaded and used to compile tensorflow.
```

Compilation fails immediately:

```
Starting local Bazel server and connecting to it...
ERROR: Config value 'download_clang' is not defined in any .rc file
```

The issue has been present since 2.5.0 at least, and it is present today in TF 2.10.0 and TF 2.11.0.
```


### Standalone code to reproduce the issue

```shell
When running `./configure`, select `y` when asked:


Do you wish to download a fresh release of clang? (Experimental) [y/N]: y
Clang will be downloaded and used to compile tensorflow.
```

Proceed with regular compilation after completing `.configure`:
`bazel build //tensorflow/tools/pip_package:build_pip_package`
```


### Relevant log output

```shell
The file `.tf_configure_bazelrc`:


build --action_env PYTHON_BIN_PATH="/opt/local/bin/python3"
build --action_env PYTHON_LIB_PATH="/opt/local/Library/Frameworks/Python.framework/Versions/3.10/li>
build --python_path="/opt/local/bin/python3"
build --config=download_clang
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-Wno-sign-compare
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test:v1 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-nomac,-no_mac,-oss_serial
test:v1 --build_tag_filters=-benchmark-test,-no_oss,-gpu,-nomac,-no_mac
test:v2 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-nomac,-no_mac,-oss_serial,-v1only
test:v2 --build_tag_filters=-benchmark-test,-no_oss,-gpu,-nomac,-no_mac,-v1only
```
```
</details>

**Comment by feranick** [comment]
This is a similar issue, but it's now closed due to lack of activity. Since I can't reopen it, I submit it with updated info as this issue. 

https://github.com/tensorflow/tensorflow/issues/46976

**Comment by bhack** [comment]
Yes, It seems it was removed with e70d095050e1d4858b2fcf0a5b55c31a2d631387

**Comment by SuryanarayanaY** [comment]
Hi @feranick,

Please find the attached documentation link specifying the compatibilities of MacOS CPU with Bazel and Clang from xcode. Could you please cross check the installation with these configurations and let us know if problem still persists.

**Comment by feranick** [comment]
Sorry, I don't see any attachment to the original email and in GitHub.

**Comment by SuryanarayanaY** [comment]
@feranick ,
Sorry for missing the attachment link. Please find the Documentation link [here](https://www.tensorflow.org/install/source#cpu_2).

Thankyou!

**Comment by feranick** [comment]
Reading from the documentation, XCode 10.4 is ancient (before 2020) and not sure why it is listed. I don't know what 10.14 refers to, it certainly makes little sense in relation to the actual versions of XCode available today. 

Anyway, Compilation works for TF 2.10.0 Bazel 5.1.1 and Clang from XCode 13.x (the one supported in MacOS 12.x). Compilation fails with XCode 14.1, the one supporting MacOS Ventura. This means that compilation when using MacOS Ventura is not possible.

The same is true for TF 2.11.0-rcx and Bazel 5.3.0.

**Comment by feranick** [comment]
The point of this issue, however, is not what works and what not based on a specific configuration. Rather that there is no way to download a viable compiler, as the `./configure` tool clearly intends to do. 

If I run compilation, I get this error (as stated above):

`ERROR: Config value 'download_clang' is not defined in any .rc file`

In essence, regardless of what works or not, even defining what `download_clang` should do is missing.

**Comment by bhack** [comment]
@feranick Can you make a quick test reintroducing these lines https://github.com/tensorflow/tensorflow/commit/e70d095050e1d4858b2fcf0a5b55c31a2d631387#diff-544556920c45b42cbfe40159b082ce8af6bd929e492d076769226265f215832fL69-L77 ?

**Comment by feranick** [comment]
I am running a compilation test using TF 2.11.0-rc2 codebase with the readded lines. Will keep you posted.

**Comment by feranick** [comment]
Compilation fails just as well. It seem that despite the added lines, bazel still uses the installed version of clang. Log attached.
[fail.txt](https://github.com/tensorflow/tensorflow/files/9983390/fail.txt)

**Comment by bhack** [comment]
I see that `ERROR: Config value 'download_clang' is not defined in any .rc file` disappeared now but still not using the new one.

**Comment by feranick** [comment]
Yes, that is correct.

**Comment by bhack** [comment]
You env varriable is correctly set to pass the condition
https://github.com/tensorflow/tensorflow/blob/1d34295f45965c7090039773dea44c25ac00ec00/third_party/clang_toolchain/cc_configure_clang.bzl#L9-L19

But I suppose that as we are not testing this in the CI the download part is quite unmaintained. 
Last commit and clang updated hash -> Sept. 2019
https://github.com/tensorflow/tensorflow/blob/master/third_party/clang_toolchain/download_clang.bzl

**Comment by feranick** [comment]
Since the option of downloading a new version of clang (experimental) is no longer present, this can be closed.
