### ISSUE TITLE
`tf.raw_ops.SegmentMax` Behaves Differently Under CPU and GPU

### ISSUE THREAD

**Issue by Kristoff-starling** [tensorflow/tensorflow#58469]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python version

3.10

### Current Behaviour?

A test case for `tf.raw_ops.SegmentMax` behaves differently under CPU and GPU.
* Under CPU, the test reports an invalid argument error, with return code 1.
* Under GPU, the test terminates normally with return code 0. Additionally, we use compute sanitizer to run the GPU version and it reports an out-of-bound read error.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

# This is the GPU version test. To use CPU, comment this line and uncomment the next line
device = '/GPU:0'
# device = '/CPU'

def test():
  with tf.device(f'{device}'):
    data_tensor = tf.random.uniform([3, 1, 2, 3], dtype=tf.float32)
    data = tf.identity(data_tensor)
    segment_ids_0 = -9
    segment_ids_1 = -1024
    segment_ids_2 = 0
    segment_ids = [segment_ids_0,segment_ids_1,segment_ids_2,]
    name = None
    _ = tf.raw_ops.SegmentMax(data=data,segment_ids=segment_ids,name=name,)

test()
```

### Relevant log output

```shell
# Under CPU, there's an invalid argument error:

tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__SegmentMax_device_/job:localhost/replica:0/task:0/device:CPU:0}} segment ids are not increasing [Op:SegmentMax]

# Under GPU, nothing happens.

# The error outputs from compute sanitizer are shown as follows:
========= COMPUTE-SANITIZER
========= Invalid __global__ read of size 4 bytes
=========     at 0x3b0 in void tensorflow::SortedSegmentReductionCustomKernel<float, int, (int)8, tensorflow::NonAtomicMaxOpGpu, tensorflow::AtomicMaxOpGpu>(T2, T2, T2, const T2 *, const T1 *, T1 *, T2, T1)
=========     by thread (0,0,0) in block (0,0,0)
=========     Address 0x7fd033ffa700 is out of bounds
=========     and is 22,784 bytes before the nearest allocation at 0x7fd034000000 of size 13,682,147,328 bytes
=========
========= Invalid __global__ read of size 4 bytes
=========     at 0x3b0 in void tensorflow::SortedSegmentReductionCustomKernel<float, int, (int)8, tensorflow::NonAtomicMaxOpGpu, tensorflow::AtomicMaxOpGpu>(T2, T2, T2, const T2 *, const T1 *, T1 *, T2, T1)
=========     by thread (1,0,0) in block (0,0,0)
=========     Address 0x7fd033ffa704 is out of bounds
=========     and is 22,780 bytes before the nearest allocation at 0x7fd034000000 of size 13,682,147,328 bytes
=========
========= Invalid __global__ read of size 4 bytes
=========     at 0x3b0 in void tensorflow::SortedSegmentReductionCustomKernel<float, int, (int)8, tensorflow::NonAtomicMaxOpGpu, tensorflow::AtomicMaxOpGpu>(T2, T2, T2, const T2 *, const T1 *, T1 *, T2, T1)
=========     by thread (2,0,0) in block (0,0,0)
=========     Address 0x7fd033ffa708 is out of bounds
=========     and is 22,776 bytes before the nearest allocation at 0x7fd034000000 of size 13,682,147,328 bytes
=========
========= Invalid __global__ read of size 4 bytes
=========     at 0x3b0 in void tensorflow::SortedSegmentReductionCustomKernel<float, int, (int)8, tensorflow::NonAtomicMaxOpGpu, tensorflow::AtomicMaxOpGpu>(T2, T2, T2, const T2 *, const T1 *, T1 *, T2, T1)
=========     by thread (3,0,0) in block (0,0,0)
=========     Address 0x7fd033ffa70c is out of bounds
=========     and is 22,772 bytes before the nearest allocation at 0x7fd034000000 of size 13,682,147,328 bytes
=========
========= Invalid __global__ read of size 4 bytes
=========     at 0x3b0 in void tensorflow::SortedSegmentReductionCustomKernel<float, int, (int)8, tensorflow::NonAtomicMaxOpGpu, tensorflow::AtomicMaxOpGpu>(T2, T2, T2, const T2 *, const T1 *, T1 *, T2, T1)
=========     by thread (4,0,0) in block (0,0,0)
=========     Address 0x7fd033ffa710 is out of bounds
=========     and is 22,768 bytes before the nearest allocation at 0x7fd034000000 of size 13,682,147,328 bytes
=========
========= Invalid __global__ read of size 4 bytes
=========     at 0x3b0 in void tensorflow::SortedSegmentReductionCustomKernel<float, int, (int)8, tensorflow::NonAtomicMaxOpGpu, tensorflow::AtomicMaxOpGpu>(T2, T2, T2, const T2 *, const T1 *, T1 *, T2, T1)
=========     by thread (5,0,0) in block (0,0,0)
=========     Address 0x7fd033ffa714 is out of bounds
=========     and is 22,764 bytes before the nearest allocation at 0x7fd034000000 of size 13,682,147,328 bytes
=========
========= ERROR SUMMARY: 10 errors
```
</details>

**Comment by bhack** [comment]
https://github.com/tensorflow/tensorflow/blob/bca2f494460b139e529b23b480427f7fdbc6bace/tensorflow/core/api_def/base_api/api_def_SegmentMax.pbtxt#L32-L36

**Comment by Kristoff-starling** [comment]
Hi, @bhack 
Sorry that I didn't notice the 'caution' section in the document.
I'm also curious about whether an out-of-bound read behavior is reasonable when given unsorted indices, since it seems unsafe. Thanks a lot!

**Comment by bhack** [comment]
Have you tried to test these idxs with the memory sanitizer on CPU?:

```python
segment_ids_0 = -1024
segment_ids_1 = -9
segment_ids_2 = 0
```

**Comment by Kristoff-starling** [comment]
I haven't tried to test with sanitizers on CPU because I'm currently unable to build TensorFlow with sanitizers. A relevant issue is #58013 in which I was told that the developers never managed to build OSS TF with sanitizers or debug info.
BTW, even if I use increasing indices, the error still exists (partly because TF segmentation doesn't accept negative values, but not all the negative values trigger an out-of-bound read):
```python
# This test triggers an out-of-bound read error under compute sanitizer.
import tensorflow as tf

device = '/GPU:0'

def test():
  with tf.device(f'{device}'):
    data_tensor = tf.random.uniform([3, 1, 2, 3], dtype=tf.float32)
    data = tf.identity(data_tensor)
    segment_ids_0 = -1024
    segment_ids_1 = 0
    segment_ids_2 = 1
    segment_ids = [segment_ids_0,segment_ids_1,segment_ids_2,]
    name = None
    _ = tf.raw_ops.SegmentMax(data=data,segment_ids=segment_ids,name=name,)

test()
```
```python
# This test exits normally.
import tensorflow as tf

device = '/GPU:0'

def test():
  with tf.device(f'{device}'):
    data_tensor = tf.random.uniform([3, 1, 2, 3], dtype=tf.float32)
    data = tf.identity(data_tensor)
    segment_ids_0 = -1
    segment_ids_1 = 0
    segment_ids_2 = 1
    segment_ids = [segment_ids_0,segment_ids_1,segment_ids_2,]
    name = None
    _ = tf.raw_ops.SegmentMax(data=data,segment_ids=segment_ids,name=name,)

test()
```

**Comment by bhack** [comment]
If I remember correctly we could build single components with debug info. See @reedwm comment at https://github.com/tensorflow/tensorflow/issues/48919#issuecomment-866438774.

From the [high level API doc](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math#about_segmentation) I see:
> `The segment_ids tensor should be the size of the first dimension, d0, with consecutive IDs in the range 0 to k, where k<d0`

Is this an hard constrain that need to validated?

**Comment by mohantym** [comment]
Hi @Kristoff-starling !
Could you reply on above [comment](https://github.com/tensorflow/tensorflow/issues/58469#issuecomment-1305545145).

I could not replicate in Colab environment( Ubuntu 18, Python 3.7).  Attached gist in [2.9](https://colab.sandbox.google.com/gist/mohantym/8e90e70d2574b254b58232f191f15cf6/git_58469.ipynb#scrollTo=pPkg4daEy1SL), [2.10](https://colab.sandbox.google.com/gist/mohantym/ad7c5e99418f9beb070949380c8a4917/git_58469.ipynb#scrollTo=pPkg4daEy1SL) and [nightly](https://colab.sandbox.google.com/gist/mohantym/394654b3199fe2c4d5edcf3fbfd2b675/git_58469.ipynb#scrollTo=pPkg4daEy1SL) for reference.

You can test with [tf.math.segment_max](https://www.tensorflow.org/api_docs/python/tf/math/segment_max) for same.

Thank you!

**Comment by Kristoff-starling** [comment]
Hi, @mohantym and @bhack,
Sorry for the late response since I had some problem entering into colab yesterday.
> If I remember correctly we could build single components with debug info. See @reedwm comment at [#48919 (comment)](https://github.com/tensorflow/tensorflow/issues/48919#issuecomment-866438774).
> 
> From the [high level API doc](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/math#about_segmentation) I see:
> 
> > `The segment_ids tensor should be the size of the first dimension, d0, with consecutive IDs in the range 0 to k, where k<d0`
> 
> Is this an hard constrain that need to validated?

The comment mentioned that adding compiling options to part of the files (by using `--per_file_copt`) may work. I'm still looking for ways to successfully compile TF with sanitizers while instrumenting all the files we're interested in. (Simply adding `--config=msan` or `--copt=-fsanitize=memory` will fail)

I also noticed the restriction mentioned in the high level API doc, which means that an increasing sequence with negative values is also invalid. But I think that it's also unreasonable for some invalid input to trigger out-of-bound read inside the library.

https://colab.research.google.com/drive/1MFcgJmU6RkJP0b9YMMa9XUENUCTJvYTB?usp=sharing

> Hi @Kristoff-starling ! Could you reply on above [comment](https://github.com/tensorflow/tensorflow/issues/58469#issuecomment-1305545145).
> 
> I could not replicate in Colab environment( Ubuntu 18, Python 3.7). Attached gist in [2.9](https://colab.sandbox.google.com/gist/mohantym/8e90e70d2574b254b58232f191f15cf6/git_58469.ipynb#scrollTo=pPkg4daEy1SL), [2.10](https://colab.sandbox.google.com/gist/mohantym/ad7c5e99418f9beb070949380c8a4917/git_58469.ipynb#scrollTo=pPkg4daEy1SL) and [nightly](https://colab.sandbox.google.com/gist/mohantym/394654b3199fe2c4d5edcf3fbfd2b675/git_58469.ipynb#scrollTo=pPkg4daEy1SL) for reference.
> 
> You can test with [tf.math.segment_max](https://www.tensorflow.org/api_docs/python/tf/math/segment_max) for same.
> 
> Thank you!

It seems that on CoLab the error report from compute sanitizer varies from that in my local environment, which may be due to some subtle differences. Here is the [gist](https://colab.research.google.com/drive/1MFcgJmU6RkJP0b9YMMa9XUENUCTJvYTB?usp=sharing) I use. The compute sanitizer says that the application "hit an error when dereferencing Unified Memory from the host". Is that helpful for debugging?

Thanks!

**Comment by mohantym** [comment]
@Kristoff-starling !
Thanks for sharing your observations in gist format.

@SuryanarayanaY !
Could you look at this issue.

Thank you!

**Comment by SuryanarayanaY** [comment]
The test case is tested with CPU runtime with both `tf.raw_ops.SegmentMax()` and `tf.math.segment_max()` in [2.9.2v](https://colab.research.google.com/gist/SuryanarayanaY/d4652c3f229afa2a99d93e0a3b35378f/58469-2-9-2v.ipynb) , [2.10v](https://colab.research.google.com/gist/SuryanarayanaY/c1e44d29bdc66c720ae9ad60ed8f6465/58469-2-10-v.ipynb) & [nightly](https://colab.research.google.com/gist/SuryanarayanaY/b6973e35cc8f51f77bb3207784790fc2/58469-nightly.ipynb#scrollTo=YFsqytO4yX0l) versions.All tests throwing `InvalidArgumentError` on CPU as per attached gists and with GPU no errors observed.

**Comment by bhack** [comment]
> as per attached gists and with GPU no errors observed

I don't see the GPU in your gist. What do you mean?

**Comment by SuryanarayanaY** [comment]
Hi @bhack,

The code tested in GPU for 2.9.2 ,2.10 and nightly versions in above comments by @mohantym .I have gone through those and observed GPU behaviour. Hence i have not attached them again in my comments to avoid repetition.

Thankyou!

**Comment by bhack** [comment]
These test are not always valid with the default soft placement enabled in TF, e.g. are for sure are not for the nightly gist. 

Please add `tf.config.set_soft_device_placement(False)` after import TF in these gists.

**Comment by bhack** [comment]
Just to be a little bit more explicit @mohantym's gist you have reused was running on CPU at least on nightly so you have not observed the GPU behaviour.

**Comment by bhack** [comment]
> I also noticed the restriction mentioned in the high level API doc, which means that an increasing sequence with negative values is also invalid

@Kristoff-starling I don't know if it is really a cosntrain it was more an open question as if you try it is also not validated by the high level API op `tf.math.segment_max`.

**Comment by Kristoff-starling** [comment]
Hi @SuryanarayanaY ,
May be you can refer to this [gist](https://colab.research.google.com/drive/1MFcgJmU6RkJP0b9YMMa9XUENUCTJvYTB?usp=sharing) to see the outputs of compute sanitizers. Maybe we should add some checks on GPU side to avoid unexpected access to memory.
@bhack yes, `tf.math.segment_max` also doesn't accept sequences with negative values. I'm not quite sure about it.

**Comment by bhack** [comment]
> yes, tf.math.segment_max also doesn't accept sequences with negative values. I'm not quite sure about it.

Can you reproduce out of bound with positive values on GPU with the raw op?

**Comment by Kristoff-starling** [comment]
It seems that out-of-bound cannot be reproduced with positive values even if the sequence is non-increasing. Actually we need a negative value small enough locating at the first place in the sequence to trigger the out-of-bound error.

**Comment by Kristoff-starling** [comment]
Thanks for the advice. I'll look into it.
