### ISSUE TITLE
Memory Allocation - Training Bug

### ISSUE THREAD

**Issue by ardamavi** [tensorflow/tensorflow#58462]
<details><summary>Click to see bug report!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.5.2

### Custom Code

Yes

### OS Platform and Distribution

CentOS 7

### Python version

3.6.13

### CUDA/cuDNN version

11.6

### GPU model and memory

NVIDIA V100S - 32 GB

### Current Behaviour?

We are having a training problem while using maximum memory allocation on GPU. Weights of the TF and Keras based Convolutional-LSTM Neural Network model are updating but not training as expected on GPU.
We can train the model as expected on CPU only training and when we try with decreased memory allocation limit of GPU via the command `tf.config.experimental.set_virtual_device_configuration(tf.config.list_physical_devices('GPU')[0], [tf.config.experimental.VirtualDeviceConfiguration( memory_limit = 22400 )])`.

### Standalone code to reproduce the issue

All codes, versions and hardware info, documentation and running directions are in our GitHub repo: [github.com/ardamavi/PI-rCNN](https://github.com/ardamavi/PI-rCNN)

**Comment by SuryanarayanaY** [comment]
Hi @ardamavi,

Thanks for writing us.I think `tf.config.experimental.set_virtual_device_configuration()` is deprecated in current versions. Please use `tf.config.set_logical_device_configuration()` instead.For more information on this API please refer the attached [Documentation Link](https://www.tensorflow.org/api_docs/python/tf/config/set_logical_device_configuration).

Also I request you to update TF version to 2.10 which is currently more stable version and use the attached link [build/install ](https://www.tensorflow.org/install/source#gpu) for checking compatibilities of CUDA,cuDNN. Request you to migrate to new version with compatible CUDA,cuDNN and let us know if problem still persists.

Thankyou !
