### ISSUE TITLE
cmake flatbuffer fail with Findflatbuffers.cmake

### ISSUE THREAD

**Issue by tensorbuffer** [tensorflow/tensorflow#58476]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tot, e.g. master

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04

### Current Behaviour?

```shell
Error message:
CMake Warning at CMakeLists.txt:49 (find_package):
  By not providing "Findflatbuffers.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "flatbuffers", but CMake did not find one.

  Could not find a package configuration file provided by "flatbuffers" with
  any of the following names:

    flatbuffersConfig.cmake
    flatbuffers-config.cmake

Root cause:
I debugged this issue and the root cause is that:
- In this commit, flatbuffer is changed to Flatbuffer: # https://github.com/tensorflow/tensorflow/commit/539438c52dca142c13f244aa0a084698a978bcda
- However this file is not changed: tensorflow/lite/tools/cmake/native_tools/flatbuffers/CMakeLists.txt 
It still says: find_package(flatbuffers)
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/cmake/native_tools/flatbuffers/CMakeLists.txt#L43
```

### Standalone code to reproduce the issue

```shell
Followed the steps here: https://www.tensorflow.org/lite/guide/build_cmake
Error happens when you do:
mkdir flatc-native-build && cd flatc-native-build
cmake ../tensorflow_src/tensorflow/lite/tools/cmake/native_tools/flatbuffers
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
HI @tensorbuffer !
Thanks for reporting this bug. Feel free to raise a PR from your end. I think it will take some time to reflect the change in new builds.
It is replicating [2.8,](https://colab.sandbox.google.com/gist/mohantym/03c9902ddf54bed97d15704dea325969/git_58468.ipynb#scrollTo=szplVG7VZ15X), [2.10](https://colab.sandbox.google.com/gist/mohantym/83e0ffe4b2be0d3d8cade1a2311f0ab4/git_58468.ipynb) and seems to be working in [2.9 version](https://colab.sandbox.google.com/gist/mohantym/c5878fcb32fe977b022964bc52a39959/git_58468.ipynb#scrollTo=szplVG7VZ15X).

@sachinprasadhs !
Could you look at this issue.
Attached gist in [2.9](https://colab.sandbox.google.com/gist/mohantym/c5878fcb32fe977b022964bc52a39959/git_58468.ipynb#scrollTo=szplVG7VZ15X), [2.10](https://colab.sandbox.google.com/gist/mohantym/83e0ffe4b2be0d3d8cade1a2311f0ab4/git_58468.ipynb) and [nightly ](https://colab.sandbox.google.com/gist/mohantym/39704f661b5a07b8905174536402d7ca/git_58468.ipynb#scrollTo=jwnQ8SoubGhD)for reference.

Thank you!

**Comment by sachinprasadhs** [comment]
Could you please refer to the comment here https://github.com/tensorflow/tensorflow/issues/58481#issuecomment-1309256864, could you close this issue and track the progress in the new issue, which you have opened [here](https://github.com/tensorflow/tensorflow/issues/58481). Thanks!

**Comment by tensorbuffer** [comment]
This is a different issue, where the root cause is explained in the description, e.g. just change find_package(flatbuffers) to find_package(Flatbuffers)

**Comment by pjpratik** [comment]
Hi @tensorbuffer 

The build is successful without any error for cross compilation using `r2.12` and the message is shown as a warning.

Please find the gist [here](https://colab.research.google.com/gist/pjpratik/e25ceeb60bb640349a6bf554322cb353/58476.ipynb).

Thanks.
