### ISSUE TITLE
cmake of tensorflowlite for aarch64 failed with EIGEN_STATIC_ASSERT

### ISSUE THREAD

**Issue by tensorbuffer** [tensorflow/tensorflow#58481]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

master

### Custom Code

No

### Current Behaviour?

```shell
My workspace has tensorflow master, last commit:
commit 21b567d26ca4cfa5c02260acd77b8b5f2fd57d84 (HEAD -> master, origin/master, origin/HEAD)
Author: Emilio Cota <ecg@google.com>
Date:   Thu Sep 29 15:14:11 2022 -0700

    Update CMakeLists to reflect the Arithmetic->Arith dialect rename

After fixing https://github.com/tensorflow/tensorflow/issues/58476 I installed flatbuff to a directory and set PATH to include that. Then I can continue to build for the shared tensorflowlite lib, according to https://www.tensorflow.org/lite/guide/build_cmake_arm
Pls refer to the log output for the error logs. I think this commit caused problem but I don't know how to fix: https://github.com/tensorflow/tensorflow/commit/09d49d9f6c9c13679ab8181d1b15480ea8a88da1
```

### Standalone code to reproduce the issue

```shell
ARMCC_PREFIX=... (set to our own toolchain)
ARMCC_FLAGS="-funsafe-math-optimizations"

cmake -DCMAKE_C_COMPILER=${ARMCC_PREFIX}gcc \
  -DCMAKE_CXX_COMPILER=${ARMCC_PREFIX}g++ \
  -DCMAKE_C_FLAGS="${ARMCC_FLAGS}" \
  -DCMAKE_CXX_FLAGS="${ARMCC_FLAGS}" \
  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
  -DCMAKE_SYSTEM_NAME=Linux \
  -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
  ../tensorflow/lite/  -DTFLITE_ENABLE_GPU=ON
cmake --build . -j
```

### Relevant log output

```shell
/opt/workspace/tensorflow/tensorflow/lite/kernels/internal/optimized/multithreaded_conv.h:173:65:   required from here
/opt/workspace/tensorflow/tensorflow/core/kernels/eigen_spatial_convolutions-inl.h:1068:27: error: static assertion failed: YOU_MADE_A_PROGRAMMING_MISTAKE
 1068 |   EIGEN_STATIC_ASSERT((nr == 4), YOU_MADE_A_PROGRAMMING_MISTAKE)
      |                       ~~~~^~~~~
/opt/workspace/tensorflow/tflite_build/eigen/unsupported/Eigen/CXX11/../../../Eigen/src/Core/util/StaticAssert.h:26:50: note: in definition of macro 'EIGEN_STATIC_ASSERT'
   26 | #define EIGEN_STATIC_ASSERT(X,MSG) static_assert(X,#MSG);
      |                                                  ^
```
</details>

**Comment by bhack** [comment]
Is the same as https://github.com/tensorflow/tensorflow/issues/57968  fixed with https://github.com/tensorflow/tensorflow/pull/57969?

/cc @elfringham

**Comment by tensorbuffer** [comment]
No, that commit only changed BUILD file, which is for bazel build, while I am using cmake.
I fixed it by changing the define to 4 in eigen/Eigen/src/Core/arch/NEON/GeneralBlockPanelKernel.h:
 #if EIGEN_ARCH_ARM64

#ifndef EIGEN_NEON_GEBP_NR
#define EIGEN_NEON_GEBP_NR 4
#endif

But I think a better fix would be a similar change in cmake files.

**Comment by sachinprasadhs** [comment]
https://github.com/tensorflow/tensorflow/commit/09d49d9f6c9c13679ab8181d1b15480ea8a88da1 fix had problems with the target `tensorflow/lite/kernels/internal/BUILD `, which was later addressed in https://github.com/tensorflow/tensorflow/commit/888dd68c774ba5d48dbb5181077ee454936822ed with changes `DEIGEN_NEON_GEBP_NR=4` asserts the values anything but 4 in the files https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/eigen_spatial_convolutions-inl.h,
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/eigen_cuboid_convolution.h.

Could you please build against https://github.com/tensorflow/tensorflow/commit/888dd68c774ba5d48dbb5181077ee454936822ed.
If you still face an issue, we may have to include `CMAKE_SYSTEM_PROCESSOR` to detect the target CPU
for `aarch64`.
Refer: https://www.tensorflow.org/lite/guide/build_cmake_arm#run_cmake

**Comment by tensorbuffer** [comment]
Tried this patch, modified the two files and still same result.

**Comment by bhack** [comment]
If you have only patched have you checked that the Eigen hash is aligned https://github.com/tensorflow/tensorflow/commit/09d49d9f6c9c13679ab8181d1b15480ea8a88da1#diff-4d11c067bc6f6eac72690f773f5c5ddc1cbc8020ba3a2752a9ed041986012699R26 ?

**Comment by tensorbuffer** [comment]
Yes that's always the case 
   EIGEN_COMMIT = "b3bf8d6a13585ff248c079402654647d298de60b"
   EIGEN_SHA256 = "2ec7ccfe975d2e05768172b7b98975852e8f739f776ea3ae7ee9fc981dcc38de"

**Comment by bhack** [comment]
Ok, It seems that the def doesn't propagate. Have you tried to put it in `TFLITE_TARGET_PUBLIC_OPTIONS` instead of the private one?

**Comment by tensorbuffer** [comment]
Yes that works!
set(TFLITE_TARGET_PUBLIC_OPTIONS "-DEIGEN_NEON_GEBP_NR=4")

**Comment by bhack** [comment]
Do you want to do this PR?

**Comment by tensorbuffer** [comment]
Sorry no, not sure about company policy...

**Comment by bhack** [comment]
@tensorbuffer Ok I will do it on my side.
