### ISSUE TITLE
release variable memory api ?

### ISSUE THREAD

**Issue by MichoChan** [tensorflow/tensorflow#58487]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

No

### Current Behaviour?

```shell
api can release memory variable
```

### Standalone code to reproduce the issue

```shell
no
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@MichoChan Sorry for the late response!
Could you provide more information on this issue reported here?  Please refer this [link](https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth) to know more on memory usage.
Thank you!
