### ISSUE TITLE
The tutorial Keras SavedModels from TF 2.7 do not load in TF 2.8, 2.9, 2.10

### ISSUE THREAD

**Issue by kennysong** [tensorflow/tensorflow#58485]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

TF 2.7.0 to 2.10.0

### Custom Code

No

### Current Behaviour?

I ran the official Keras tutorial "[Structured data classification from scratch](https://keras.io/examples/structured_data/structured_data_classification_from_scratch/)" in TF 2.7, and saved the model as a SavedModel.

This SavedModel successfully loads in TF 2.7, but cannot be loaded TF 2.8, 2.9, or 2.10. Error message:

```
File ~/.../regressor.py:337, in load_model(filepath, library)
--> 337             model = tf.keras.models.load_model(extract_dir)

File ~/.../env/lib/python3.8/site-packages/keras/utils/traceback_utils.py:67, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     65 except Exception as e:  # pylint: disable=broad-except
     66   filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67   raise e.with_traceback(filtered_tb) from None
     68 finally:
     69   del filtered_tb

File ~/.../env/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py:56, in _SatisfiesTypeConstraint(dtype, attr_def, param_name)
     54 allowed_values = ", ".join(dtypes.as_dtype(x).name for x in allowed_list)
     55 if dtype not in allowed_list:
---> 56   raise TypeError(
     57       f"Value passed to parameter '{param_name}' has DataType "
     58       f"{dtypes.as_dtype(dtype).name} not in list of allowed values: "
     59       f"{allowed_values}")

TypeError: Exception encountered when calling layer "string_lookup" (type StringLookup).

Value passed to parameter 'weights' has DataType string not in list of allowed values: int32, int64, float32, float64

Call arguments received:
  • inputs=tf.Tensor(shape=(None, 1), dtype=string)
```

Based my my tests, here's a compatibility table for saving/loading this model across TF versions:

|                    | Load with TF 2.6 | Load with TF 2.7 | Load with TF 2.8 | Load with TF 2.9 | Load with TF 2.10 |
|--------------------|------------------|------------------|------------------|------------------|-------------------|
| Saved with TF 2.6  | ✅                | ✅                | ❌                | ❌                | ❌                 |
| Saved with TF 2.7  | ❌                | ✅                | ❌                | ❌                | ❌                 |
| Saved with TF 2.8  | ❌                | ❌                | ✅                | ✅                | ✅                 |
| Saved with TF 2.9  | ❌                | ❌                | ✅                | ✅                | ✅                 |
| Saved with TF 2.10 | ❌                | ❌                | ✅                | ✅                | ✅                 |

### Standalone code to reproduce the issue

Colab to train and save the Keras tutorial model: https://colab.research.google.com/drive/1c-UDWPW0OQjbgItijs_4UB4sm-dQ7MdS?usp=sharing

Colab to load the Keras tutorial SavedModel: https://colab.research.google.com/drive/1KM9nUBdsqGFW5zXUuU7b2ZtcKA1BiUXz?usp=sharing

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@kennysong,
Thank you for reporting this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by kennysong** [comment]
Hi @tilakrayal, I've copied the issue to the Keras repo as well: https://github.com/keras-team/keras/issues/17232

If you can post your reproduction of the bug there, that would be helpful!

**Comment by tilakrayal** [comment]
@kennysong,
Could you please move this issue to closed status, since it is already being tracked there in keras repo? Thank you!

**Comment by kennysong** [comment]
Done. Please post your confirmation on the other issue as well!
