### ISSUE TITLE
Running TensorFlow on SHArC processors?

### ISSUE THREAD

**Issue by DanijelDomazet** [tensorflow/tensorflow#58491]
Are there any information on the possibility to compile TensorFlow (Lite C) targeting SHArC processor from Analog Devices?

**Comment by mohantym** [comment]
Hi @DanijelDomazet !

Not Sure whether the [Cmake ](https://www.tensorflow.org/lite/microcontrollers) documentation on lite will suit for Sharc processors with Hexagon DSP support. 

Normally we use Cmake the compile certain example from [tflite/micro](https://github.com/tensorflow/tflite-micro) repo .
Could you post in TFlite-Micro repo / TF Forum for better visibility.
 
Thank you!

**Comment by DanijelDomazet** [comment]
> Not Sure whether the [Cmake ](https://www.tensorflow.org/lite/guide/build_cmake) documentation on lite will suit for Sharc processors with Hexagon DSP support.

I think this requires lots of changes to CMake makefiles. Also, SHArC C++ compiler seems limited. 

> Normally we use CMake to compile certain examples from [tflite/micro](https://github.com/tensorflow/tflite-micro) repo . Implementation is highly feasible when the manufacturer provides an IDE to import the .cc files procured from lite models using XXD converter.

Not sure I understand.

> 
> Could you post in TFlite-Micro repo / TF Forum for further assistance.

https://github.com/tensorflow/tflite-micro/issues/1593
https://discuss.tensorflow.org/c/general-discussion

**Comment by mohantym** [comment]
> Normally we use CMake to compile certain examples from [tflite/micro](https://github.com/tensorflow/tflite-micro) repo . Implementation is highly feasible when the manufacturer provides an IDE to import the .cc files procured from lite models using XXD converter.

On this Part, I was suggesting to go through 15 steps process from [here](https://www.tensorflow.org/lite/microcontrollers/get_started_low_level). Previous [section](https://www.tensorflow.org/lite/microcontrollers/get_started_low_level#train_a_model) covers model to .cc conversion using xxd converter.

**Comment by DanijelDomazet** [comment]
> 



> > Normally we use CMake to compile certain examples from [tflite/micro](https://github.com/tensorflow/tflite-micro) repo . Implementation is highly feasible when the manufacturer provides an IDE to import the .cc files procured from lite models using XXD converter.
> 
> On this Part, I was suggesting to go through 15 steps process from [here](https://www.tensorflow.org/lite/microcontrollers/get_started_low_level). Previous [section](https://www.tensorflow.org/lite/microcontrollers/get_started_low_level#train_a_model) covers model to .cc conversion using xxd converter.


Thanks. 
I don't think I can move any forward before I am able to compile the TF Lite C for SHArC processor architecture. Current cmakefiles don't support SHArC, only Arm, x86, etc.

**Comment by ananddb90** [comment]
Hi @DanijelDomazet Did you find way to compile tf lite c for SHArC processor ? Any suggestion would be of great help. Thank you
