### ISSUE TITLE
Can't build TensorFlowLiteSelectTfOps with -force_load linker flag

### ISSUE THREAD

**Issue by agarip** [tensorflow/tensorflow#58492]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

No

### Current Behaviour?

```shell
I can't build fresh project after adding linker flag -force_load. I use CocoaPods,TensorFlowLiteSwift and TensorFlowLiteSelectTfOps (~> 0.0.1-nightly).
```

### Standalone code to reproduce the issue

```shell
Create a new Xcode project, install pods, add -force_load linker flag as described in the documentation.
```

### Relevant log output

_No response_</details>
![Screen Shot 2022-11-09 at 17 08 15](https://user-images.githubusercontent.com/15905313/200855987-be2f8b1f-fcff-4b8d-8da8-706c413dac71.png)
![Screen Shot 2022-11-09 at 17 09 12](https://user-images.githubusercontent.com/15905313/200856006-5170aec1-24f2-46d5-8c62-4aabae422ca1.png)
![Screen Shot 2022-11-09 at 17 09 47](https://user-images.githubusercontent.com/15905313/200856009-cc187455-6188-4ff5-a13b-13bd2e8e3818.png)

**Comment by sachinprasadhs** [comment]
Could you follow the build instructions for Xcode [here](https://www.tensorflow.org/lite/guide/ops_select#using_bazel_xcode) and [here](https://www.tensorflow.org/lite/guide/build_ios) for iOS and let us know if that helps. Thanks!

**Comment by agarip** [comment]
> Could you follow the build instructions for Xcode [here](https://www.tensorflow.org/lite/guide/ops_select#using_bazel_xcode) and [here](https://www.tensorflow.org/lite/guide/build_ios) for iOS and let us know if that helps. Thanks!

I will try building locally with Bazel. Did you reproduce the issue with the CocoaPods? Is there a way to use TensorFlowLiteSelectTfOps with CocoaPods?

**Comment by sachinprasadhs** [comment]
I could not reproduce from my side since I don't have the setup for this specific build configurations, I can help you with the details which you require for the build failure.
Please follow the documentation here https://www.tensorflow.org/lite/guide/ops_select#ios.
Also, since you are using the Tensorflow version> 2.9.0, I hope you are using the linker flag like mentioned below.
`-force_load $(SRCROOT)/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.xcframework/ios-arm64/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps`

**Comment by agarip** [comment]
> I could not reproduce from my side since I don't have the setup for this specific build configurations, I can help you with the details which you require for the build failure.
> Please follow the documentation here https://www.tensorflow.org/lite/guide/ops_select#ios.
> Also, since you are using the Tensorflow version> 2.9.0, I hope you are using the linker flag like mentioned below.
> `-force_load $(SRCROOT)/Pods/TensorFlowLiteSelectTfOps/Frameworks/TensorFlowLiteSelectTfOps.xcframework/ios-arm64/TensorFlowLiteSelectTfOps.framework/TensorFlowLiteSelectTfOps`

I have tried Bazel built framework, but the result is same. I followed the documentation for both CocoaPods and Bazel. The problem starts just after adding the -force_load linker flag. 

- With the -force_load flag: I can't build the project because of the undefined symbols that I added the issue.
- Without the -force_load flag: I can build the project, but I get the following error:

INFO: Initialized TensorFlow Lite runtime.
TensorFlow Lite Error: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select
TensorFlow Lite Error: Node number 20 (FlexCast) failed to prepare.

**Comment by ted1995** [comment]
i meet the same problem, i solved the peoblem by this:
in podfile:
tensorflowliteC and tensorflowliteobjc's version to 2.7.0
tensorflowliteSelectOps's version to 0.0.1-nightly-20210521.

the tensorflow guide is too old to adapt the latest tensorflowlite version!

**Comment by v-hogood** [comment]
I have the same problem trying to upgrade the SoundClassification iOS example (https://github.com/tensorflow/examples/tree/master/lite/examples/sound_classification/ios) to 2.11.0:
```
Undefined symbols for architecture arm64:
  "_descriptor_table_tensorflow_2ftsl_2fprotobuf_2fhistogram_2eproto", referenced from:
      descriptor_table_tensorflow_2fcore_2fframework_2fsummary_2eproto_deps in TensorFlowLiteSelectTfOps(summary.pb.o)
  "tensorflow::HistogramProto::InternalSerializeWithCachedSizesToArray(unsigned char*) const", referenced from:
      tensorflow::Summary_Value::InternalSerializeWithCachedSizesToArray(unsigned char*) const in TensorFlowLiteSelectTfOps(summary.pb.o)
  "tensorflow::HistogramProto::ByteSizeLong() const", referenced from:
      tensorflow::Summary_Value::ByteSizeLong() const in TensorFlowLiteSelectTfOps(summary.pb.o)
  "tensorflow::HistogramProto* google::protobuf::Arena::CreateMaybeMessage<tensorflow::HistogramProto>(google::protobuf::Arena*)", referenced from:
      void (anonymous namespace)::HistogramSummaryOp_Compute<long long>(void*, TF_OpKernelContext*) in TensorFlowLiteSelectTfOps(histogram_summary_op.o)
      void (anonymous namespace)::HistogramSummaryOp_Compute<unsigned long long>(void*, TF_OpKernelContext*) in TensorFlowLiteSelectTfOps(histogram_summary_op.o)
      void (anonymous namespace)::HistogramSummaryOp_Compute<int>(void*, TF_OpKernelContext*) in TensorFlowLiteSelectTfOps(histogram_summary_op.o)
      void (anonymous namespace)::HistogramSummaryOp_Compute<unsigned int>(void*, TF_OpKernelContext*) in TensorFlowLiteSelectTfOps(histogram_summary_op.o)
      void (anonymous namespace)::HistogramSummaryOp_Compute<unsigned short>(void*, TF_OpKernelContext*) in TensorFlowLiteSelectTfOps(histogram_summary_op.o)
      void (anonymous namespace)::HistogramSummaryOp_Compute<short>(void*, TF_OpKernelContext*) in TensorFlowLiteSelectTfOps(histogram_summary_op.o)
      void (anonymous namespace)::HistogramSummaryOp_Compute<signed char>(void*, TF_OpKernelContext*) in TensorFlowLiteSelectTfOps(histogram_summary_op.o)
      ...
  "tensorflow::HistogramProto::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)", referenced from:
      tensorflow::Summary_Value::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in TensorFlowLiteSelectTfOps(summary.pb.o)
  "_scc_info_HistogramProto_tensorflow_2ftsl_2fprotobuf_2fhistogram_2eproto", referenced from:
      _scc_info_Summary_Value_tensorflow_2fcore_2fframework_2fsummary_2eproto in TensorFlowLiteSelectTfOps(summary.pb.o)
  "tensorflow::HistogramProto::MergeFrom(tensorflow::HistogramProto const&)", referenced from:
      tensorflow::Summary_Value::Summary_Value(tensorflow::Summary_Value const&) in TensorFlowLiteSelectTfOps(summary.pb.o)
      tensorflow::Summary_Value::MergeFrom(tensorflow::Summary_Value const&) in TensorFlowLiteSelectTfOps(summary.pb.o)
  "tensorflow::_HistogramProto_default_instance_", referenced from:
      InitDefaultsscc_info_Summary_Value_tensorflow_2fcore_2fframework_2fsummary_2eproto() in TensorFlowLiteSelectTfOps(summary.pb.o)
      tensorflow::Summary_Value::InitAsDefaultInstance() in TensorFlowLiteSelectTfOps(summary.pb.o)
      tensorflow::Summary_Value::Summary_Value(tensorflow::Summary_Value const&) in TensorFlowLiteSelectTfOps(summary.pb.o)
      tensorflow::Summary_Value::MergeFrom(tensorflow::Summary_Value const&) in TensorFlowLiteSelectTfOps(summary.pb.o)
  "_descriptor_table_tensorflow_2ftsl_2fprotobuf_2ferror_5fcodes_2eproto", referenced from:
      descriptor_table_tensorflow_2fcore_2flib_2fcore_2ferror_5fcodes_2eproto_deps in TensorFlowLiteSelectTfOps(error_codes.pb.o)
      descriptor_table_tensorflow_2fcore_2fprotobuf_2ferror_5fcodes_2eproto_deps in TensorFlowLiteSelectTfOps(error_codes.pb.o)
  "tensorflow::HistogramProto::Clear()", referenced from:
      tsl::histogram::Histogram::EncodeToProto(tensorflow::HistogramProto*, bool) const in TensorFlowLiteSelectTfOps(histogram_21266347677d3a1ba0863af7de511683.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ted1995** [comment]
> I have the same problem trying to upgrade the SoundClassification iOS example (https://github.com/tensorflow/examples/tree/master/lite/examples/sound_classification/ios) to 2.11.0:
> 
> ```
> Undefined symbols for architecture arm64:
>   "_descriptor_table_tensorflow_2ftsl_2fprotobuf_2fhistogram_2eproto", referenced from:
>       descriptor_table_tensorflow_2fcore_2fframework_2fsummary_2eproto_deps in TensorFlowLiteSelectTfOps(summary.pb.o)
>   "tensorflow::HistogramProto::InternalSerializeWithCachedSizesToArray(unsigned char*) const", referenced from:
>       tensorflow::Summary_Value::InternalSerializeWithCachedSizesToArray(unsigned char*) const in TensorFlowLiteSelectTfOps(summary.pb.o)
>   "tensorflow::HistogramProto::ByteSizeLong() const", referenced from:
>       tensorflow::Summary_Value::ByteSizeLong() const in TensorFlowLiteSelectTfOps(summary.pb.o)
>   "tensorflow::HistogramProto* google::protobuf::Arena::CreateMaybeMessage<tensorflow::HistogramProto>(google::protobuf::Arena*)", referenced from:
>       void (anonymous namespace)::HistogramSummaryOp_Compute<long long>(void*, TF_OpKernelContext*) in TensorFlowLiteSelectTfOps(histogram_summary_op.o)
>       void (anonymous namespace)::HistogramSummaryOp_Compute<unsigned long long>(void*, TF_OpKernelContext*) in TensorFlowLiteSelectTfOps(histogram_summary_op.o)
>       void (anonymous namespace)::HistogramSummaryOp_Compute<int>(void*, TF_OpKernelContext*) in TensorFlowLiteSelectTfOps(histogram_summary_op.o)
>       void (anonymous namespace)::HistogramSummaryOp_Compute<unsigned int>(void*, TF_OpKernelContext*) in TensorFlowLiteSelectTfOps(histogram_summary_op.o)
>       void (anonymous namespace)::HistogramSummaryOp_Compute<unsigned short>(void*, TF_OpKernelContext*) in TensorFlowLiteSelectTfOps(histogram_summary_op.o)
>       void (anonymous namespace)::HistogramSummaryOp_Compute<short>(void*, TF_OpKernelContext*) in TensorFlowLiteSelectTfOps(histogram_summary_op.o)
>       void (anonymous namespace)::HistogramSummaryOp_Compute<signed char>(void*, TF_OpKernelContext*) in TensorFlowLiteSelectTfOps(histogram_summary_op.o)
>       ...
>   "tensorflow::HistogramProto::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*)", referenced from:
>       tensorflow::Summary_Value::MergePartialFromCodedStream(google::protobuf::io::CodedInputStream*) in TensorFlowLiteSelectTfOps(summary.pb.o)
>   "_scc_info_HistogramProto_tensorflow_2ftsl_2fprotobuf_2fhistogram_2eproto", referenced from:
>       _scc_info_Summary_Value_tensorflow_2fcore_2fframework_2fsummary_2eproto in TensorFlowLiteSelectTfOps(summary.pb.o)
>   "tensorflow::HistogramProto::MergeFrom(tensorflow::HistogramProto const&)", referenced from:
>       tensorflow::Summary_Value::Summary_Value(tensorflow::Summary_Value const&) in TensorFlowLiteSelectTfOps(summary.pb.o)
>       tensorflow::Summary_Value::MergeFrom(tensorflow::Summary_Value const&) in TensorFlowLiteSelectTfOps(summary.pb.o)
>   "tensorflow::_HistogramProto_default_instance_", referenced from:
>       InitDefaultsscc_info_Summary_Value_tensorflow_2fcore_2fframework_2fsummary_2eproto() in TensorFlowLiteSelectTfOps(summary.pb.o)
>       tensorflow::Summary_Value::InitAsDefaultInstance() in TensorFlowLiteSelectTfOps(summary.pb.o)
>       tensorflow::Summary_Value::Summary_Value(tensorflow::Summary_Value const&) in TensorFlowLiteSelectTfOps(summary.pb.o)
>       tensorflow::Summary_Value::MergeFrom(tensorflow::Summary_Value const&) in TensorFlowLiteSelectTfOps(summary.pb.o)
>   "_descriptor_table_tensorflow_2ftsl_2fprotobuf_2ferror_5fcodes_2eproto", referenced from:
>       descriptor_table_tensorflow_2fcore_2flib_2fcore_2ferror_5fcodes_2eproto_deps in TensorFlowLiteSelectTfOps(error_codes.pb.o)
>       descriptor_table_tensorflow_2fcore_2fprotobuf_2ferror_5fcodes_2eproto_deps in TensorFlowLiteSelectTfOps(error_codes.pb.o)
>   "tensorflow::HistogramProto::Clear()", referenced from:
>       tsl::histogram::Histogram::EncodeToProto(tensorflow::HistogramProto*, bool) const in TensorFlowLiteSelectTfOps(histogram_21266347677d3a1ba0863af7de511683.o)
> ld: symbol(s) not found for architecture arm64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
You can try to adjust the version of tensorflowliteC and tensorflowliteSelectOps, the new version is discompatible each other

**Comment by pjpratik** [comment]
Hi @agarip 

The commit https://github.com/tensorflow/tensorflow/commit/729877ecf4a2a429c95e2930c24081bf75ffd9ee and https://github.com/tensorflow/tensorflow/commit/96d3fdac39039ad1d87e04fa94e771ccf90cd1eb fix the issue with building TensorFlowLiteSelectTfOps_framework.

https://github.com/tensorflow/tensorflow/blob/3885fefb2b57a34d5ba921cdfcd86d8d29634f61/tensorflow/lite/ios/BUILD.apple#L160-L161

Could you please try in nightly version and let us know if the issue still persists. 

Please check the relevant thread #59721 for reference.

Thanks.

**Comment by v-hogood** [comment]
Yes 0.0.1-nightly.20230414 works! 2.12.0 doesn't so I guess the change didn't make it in there.

**Comment by pjpratik** [comment]
Hi @v-hogood 

The changes will be reflected in the 2.13.0 version. Meanwhile the nightly version can be used.

Thanks.

**Comment by johnfhima** [comment]
Hello,
when trying to install nightly 20230424, it say :
```
[!] CocoaPods could not find compatible versions for pod "TensorFlowLiteSwift":
  In Podfile:
    TensorFlowLiteSwift (~> 0.0.1-nightly.20230414)

None of your spec sources contain a spec satisfying the dependency: `TensorFlowLiteSwift (~> 0.0.1-nightly.20230414)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```


The last version I can find is 20230409.
Do you know how to solve it ? 
Thanks
