### ISSUE TITLE
`tf.experimental.numpy.sort` does not `nan` values to the end as numpy document says

### ISSUE THREAD

**Issue by fuzzyswan** [tensorflow/tensorflow#58496]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.2

### Custom Code

Yes

### OS Platform and Distribution

Colab

### Python version

3.7.15

### CUDA/cuDNN version

11.2.152, 8.1.1

### Current Behaviour?

According to the [numpy docs](https://numpy.org/doc/1.16/reference/generated/numpy.sort.html) for `np.sort` (which is mentioned in [tf docs](https://www.tensorflow.org/api_docs/python/tf/experimental/numpy/sort) for `tf.experimental.numpy.sort`), `nan`s should be sorted to the end of an array.

> Previous to numpy 1.4.0 sorting real and complex arrays containing nan values led to undefined behaviour. In numpy versions >= 1.4.0 nan values are sorted to the end. The extended sort order is:
> 
> - Real: [R, nan]
> - Complex: [R + Rj, R + nanj, nan + Rj, nan + nanj]
> 
> where R is a non-nan real value. Complex values with the same nan placements are sorted according to the non-nan part if it exists. Non-nan values are sorted as before.

The CPU and GPU implementations of tf violate this by placing `nan` in the front or in the middle of the array.

### Standalone code to reproduce the issue

```shell
print("numpy", np.sort([1, np.nan, 2, 3]))
with tf.device("/cpu:0"):
  print("CPU", tf.experimental.numpy.sort([1, np.nan, 2, 3]))
with tf.device("/gpu:0"):
  print("GPU", tf.experimental.numpy.sort([1, np.nan, 2, 3]))
```

### Relevant log output

```shell
numpy [ 1.  2.  3. nan]
CPU tf.Tensor([ 1. nan  2.  3.], shape=(4,), dtype=float64)
GPU tf.Tensor([nan  1.  2.  3.], shape=(4,), dtype=float64)
```
</details>

**Comment by bhack** [comment]
Yes it is the underline impl of `tf.sort`

```python
import numpy as np
import tensorflow as tf
tf.config.set_soft_device_placement(False)
with tf.device("/cpu:0"):
  cpu_sorted = tf.sort([1, np.nan, 2, 3])
with tf.device("/gpu:0"):
  gpu_sorted = tf.sort([1, np.nan, 2, 3])
tf.debugging.assert_equal(cpu_sorted, gpu_sorted)
```

Can you contribute a PR add a new test case with `np.nan`?
https://github.com/tensorflow/tensorflow/blob/c9d57288fe985527b85ed554a1d518b9ca03fc25/tensorflow/python/ops/sort_ops_test.py#L41-L48 ?

As the test will fail you must wrap it with `@unittest.expectedFailure` like this one and add a reference to this issue:
https://github.com/tensorflow/tensorflow/blob/25265c134044f645bfb894a5595fa8fafd4165ef/tensorflow/python/kernel_tests/data_structures/lookup_ops_test.py#L3357-L3359

**Comment by bhack** [comment]
@tilakrayal You have not replicated on nightly as it is running on CPU

**Comment by sushreebarsa** [comment]
@fuzzyswan Sorry for the late response!
I faced different outcome while reproducing this issue on colab using tf-nightly(2.12.0.dev20230112), please find the gist for [cpu](https://colab.research.google.com/gist/sushreebarsa/89f8a0d9b465c965b7e56bcf07e61b73/cpu.ipynb) and [gpu](https://colab.research.google.com/gist/sushreebarsa/af8fb84e3dceeb22e712aab5fb4e4054/untitled750.ipynb#scrollTo=Xf61hjva1BKI). Could you please confirm the results?
Thank you!
