### ISSUE TITLE
adding zero-sized layer costs huge amount of memory, but without increasing total # of trainable parameters

### ISSUE THREAD

**Issue by xuancong84** [tensorflow/tensorflow#5850]
In order to make code generic, my code does append a layer with a variable-sized layer which might be of length 0, i.e.
`
tv_concat = tf.concat(1, [tf.reshape(tf.slice(X,[0,time_step,0],[-1,Ncontext,-1]), [tp_current_batch_size,embed_size*Ncontext]), tv_hh])`

In the above code, X is a tensor of shape [batch_size, max_time_step, state_size], tv_hh of shape [batch_size, state_size]. Depending on the value of Ncontext, a differently sized layer will be concatenated with the existing layer tv_hh. So when Ncontext=0, a zero-size layer will be concatenated so that tv_concat will be the same as tv_hh. I have explicitly checked and confirmed that tv_concat is indeed of the same shape as tv_hh. I have also checked that the total number of trainable parameters are the same.

However, when Ncontext=0, the graphics memory consumption is >3G, if I use tv_concat=tv_hh, the graphics memory consumption is only 2G.

So is this behaviour expected?

**Comment by prb12** [comment]
Please can you provide all of the information requested in the issues reporting template.

**Comment by xuancong84** [comment]
1. Operating System:
Ubuntu 14.04.5 LTS

2. Installed version of CUDA and cuDNN:
/usr/local/cuda-8.0
cudnn-8.0-linux-x64-v5.1.tgz

3. It is installed from binary pip package

4. A link to the pip package you installed:
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl

5. The output from python -c "import tensorflow; print(tensorflow.__version__)"
xuancong@wxc-i2r:~/projects/tf-rnnlm$ python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
0.11.0

**Comment by zffchen78** [comment]
Backprop through multiple tf.slice is memory expensive . Try to rearrange
your code to do one tf.split upfront before any per-timestep calculation.

**Comment by xuancong84** [comment]
@zffchen78 I am aware of that backprop through multiple tf.slice is memory expensive. However, slicing out a zero-sized layer should not cost that much memory I presume.

**Comment by michaelisard** [comment]
Does rearranging the code as suggested avoid the high memory cost?

**Comment by xuancong84** [comment]
@michaelisard It is not possible to rearrange the code as suggested because Ncontext is an integer (>=0) parameter to be tuned. Take a closer look at my code, you will find out why.

**Comment by michaelisard** [comment]
@sherrym would you reassign to someone who can take a look?

**Comment by yaroslavvb** [comment]
@xuancong84  btw, it could help troubleshooting if you dumped memory
timeline and checked which op is responsible for this extra 1GB allocation,
using timeline as here:
https://github.com/tensorflow/tensorflow/issues/6019#issuecomment-264544202

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.
