### ISSUE TITLE
Bug in MLP notebook 

### ISSUE THREAD

**Issue by AVON257** [tensorflow/tensorflow#58507]
I have found a problem with a memory explosion on the MLP notebook, if it's configured to use non deterministic Nvidia cuda.

What I found is that the memory usage went up massively, when I last tested it I think using gelu activation functions, instead of relu.

When I tested this it resulted in memory usage increases, until it used up all my system memory (32GB), on Ubuntu 22.10.

This was using python 3.10 and tensorflow 2.10, Nvidia cuda 11.7

Is there any possibility of fixing this?

**Comment by tilakrayal** [comment]
@AVON257,
Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose) and also o expedite the trouble-shooting process, could you please provide a minimal code snippet you are using. Thank you!
