### ISSUE TITLE
`tf.math.negative` negates only the last element in an all-zero 3x3 matrix on CPU

### ISSUE THREAD

**Issue by creakseek** [tensorflow/tensorflow#58515]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10.0, and nightly

### Custom Code

Yes

### OS Platform and Distribution

Colab

### Python version

3.7.15

### CUDA/cuDNN version

11.2.152, 8.1.1

### Current Behaviour?

There is a difference between `0.0` and `-0.0` according to IEEE 754. Negate `0.0` and you should get `-0.0`. If we apply `tf.math.negative` to an all-zero 3x3 matrix, it only negates the last element to `-0.0` and leave the rest as `0.0`.

### Standalone code to reproduce the issue

```shell
with tf.device("/cpu:0"):
  zeros = tf.zeros((3, 3), dtype=tf.float64)
  negs = tf.math.negative(zeros)
  infs = tf.math.reciprocal(negs)
  print(zeros, negs, infs)
```

### Relevant log output

```shell
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float64) tf.Tensor(
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. -0.]], shape=(3, 3), dtype=float64) tf.Tensor(
[[ inf  inf  inf]
 [ inf  inf  inf]
 [ inf  inf -inf]], shape=(3, 3), dtype=float64)
```
</details>

**Comment by creakseek** [comment]
It's strange enough that this does not happen on 2x2 matrices.

**Comment by bhack** [comment]
I suppose we are using:

https://github.com/tensorflow/tensorflow/blob/769eddaf479c8debead9a59a72617d6ed6f0fe10/tensorflow/core/kernels/cwise_ops.h#L886

So this impl behaviour is in the eigen library:
https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Core/functors/UnaryFunctors.h#L678-696

So I don't know if it is related to some SIMD optimizzation of the eigen `internal::preciprocal`:

https://gitlab.com/search?search=preciprocal&nav_source=navbar&project_id=15462818&group_id=6577938&search_code=true&repository_ref=master

/cc @cantonios

**Comment by cantonios** [comment]
It's likely being compiled with fast-math enabled, where the compiler is allowed to ignore differences between 0 and -0.  As for why the 9th component is negated, the first 8 values will use vectorized SIMD instructions, and the 9th element uses the scalar path.

**Comment by cantonios** [comment]
As for why it doesn't happen with 2x2 matrices: the SIMD vector size for AVX instructions is 8 floats.  So for only 4 floats, we're probably using the scalar path for all elements, so it "works" just like the 9th element works in a 3x3 matrix.

**Comment by cantonios** [comment]
nm, I double-checked the Eigen source, and it's because we implement negate as (0 - x), so we get this behavior even in no-fast-math mode.  (+0 - -0) is +0.  I'll change that on the Eigen end.  Will take time to propagate.

**Comment by bhack** [comment]
> nm, I double-checked the Eigen source, and it's because we implement negate as (0 - x), so we get this behavior even in no-fast-math mode. (+0 - -0) is +0. I'll change that on the Eigen end. Will take time to propagate.

Are you talking about https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Core/functors/UnaryFunctors.h#L25 ?

**Comment by cantonios** [comment]
> > nm, I double-checked the Eigen source, and it's because we implement negate as (0 - x), so we get this behavior even in no-fast-math mode. (+0 - -0) is +0. I'll change that on the Eigen end. Will take time to propagate.
> 
> Are you talking about https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Core/functors/UnaryFunctors.h#L25 ?

Specifically only the AVX packet instruction:
https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Core/arch/AVX/PacketMath.h#L547

**Comment by bhack** [comment]
Oh it is for `_mm256_sub_ps`.. and then scalar `return -a; ` is the value that it is already ok.

**Comment by bhack** [comment]
@cantonios PR landed in Eigen https://gitlab.com/libeigen/eigen/-/merge_requests/1116. I think we could close this on merge.

**Comment by creakseek** [comment]
> It's likely being compiled with fast-math enabled, where the compiler is allowed to ignore differences between 0 and -0. As for why the 9th component is negated, the first 8 values will use vectorized SIMD instructions, and the 9th element uses the scalar path.

That is very clear! Thank you for such detailed explanation!

**Comment by tiruk007** [comment]
@creakseek 
Can you please close the issue if it is solved?

Thank you!

**Comment by cantonios** [comment]
@tiruk007 It is not yet solved.  We need to wait until the eigen change propagates into TensorFlow.
