### ISSUE TITLE
XlaRuntimeError: UNKNOWN: Failed to determine best cudnn convolution algorithm for

### ISSUE THREAD

**Issue by deadsoul44** [tensorflow/tensorflow#58534]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.6.4

### Custom Code

Yes

### OS Platform and Distribution

Linux 524ec3303516 5.15.65+ #1 SMP Thu Nov 10 10:13:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Python version

3.7.12

### GPU model and memory

P100

### Current Behaviour?

```shell
Tried to use 1D convolution with JAX/Flax.
```

### Standalone code to reproduce the issue

```shell
import flax
from flax import linen as nn
from flax.training import train_state
from flax import jax_utils
from flax.core.frozen_dict import freeze, unfreeze
import jax
import jax.numpy as jnp
from jax import random, device_get
from typing import Sequence, Tuple, Optional, Callable, Any

ModuleDef = Any

class NN(nn.Module):
    features: Sequence[Sequence[int]]
    kernel_sizes: Sequence[Sequence[Tuple[int, int]]]
    used_rounds: Optional[int] = None
    act: Callable = nn.relu

    @nn.compact
    def __call__(self, x):
        n_rounds = len(self.kernel_sizes) if self.used_rounds == None else self.used_rounds
        if n_rounds < 0:
            round_range = range(len(self.kernel_sizes) + n_rounds)
        else:
            round_range = range(n_rounds)
        
        y_rounds = jnp.zeros((len(list(round_range)), x.shape[0], 1))
        for boosting_round in round_range:
            y = None
            for depth in range(len(self.features[boosting_round])):
                if depth == (len(self.features[boosting_round]) - 1) and boosting_round == (len(list(round_range)) - 1):
                    conv_name = "conv_head"
                    dense_name = "dense_head"
                else:
                    conv_name = f"conv_{boosting_round}_{depth}"
                    dense_name = f"dense_{boosting_round}_{depth}"
                if y is not None:
                    y = jnp.concatenate((x, y), axis=-1)
                else:
                    y = x
                f = self.features[boosting_round][depth]
                k = self.kernel_sizes[boosting_round][depth]
                y = nn.Conv(features=f, kernel_size=k, name=conv_name)(y)
                y = self.act(y)
            
            y_flat = y.reshape((y.shape[0], -1))  # flatten
            y_dense = nn.Dense(features=1, name=dense_name)(y_flat)
            y_rounds = y_rounds.at[boosting_round].set(y_dense)
        return jnp.sum(y_rounds, axis=0)

tree_trial = NN([[2, 3, 4], [2, 3]], [[(2,), (4,), (5,)], [(2,), (4,)]])
params = tree_trial.init(random.PRNGKey(0), jnp.ones([33, 8]))['params']
print(jax.tree_map(lambda x: x.shape, params))
```

### Relevant log output

```shell
---------------------------------------------------------------------------
XlaRuntimeError                           Traceback (most recent call last)
/tmp/ipykernel_23/3353521153.py in <module>
      1 tree_trial = NN([[2, 3, 4], [2, 3]], [[(2,), (4,), (5,)], [(2,), (4,)]])
----> 2 params = tree_trial.init(random.PRNGKey(0), jnp.ones([33, 8]))['params']
      3 print(jax.tree_map(lambda x: x.shape, params))

    [... skipping hidden 9 frame]

/tmp/ipykernel_23/1204994627.py in __call__(self, x)
     29                 f = self.features[boosting_round][depth]
     30                 k = self.kernel_sizes[boosting_round][depth]
---> 31                 y = nn.Conv(features=f, kernel_size=k, name=conv_name)(y)
     32                 y = self.act(y)
     33 

    [... skipping hidden 2 frame]

/opt/conda/lib/python3.7/site-packages/flax/linen/linear.py in __call__(self, inputs)
    442           dimension_numbers=dimension_numbers,
    443           feature_group_count=self.feature_group_count,
--> 444           precision=self.precision
    445       )
    446     else:

    [... skipping hidden 13 frame]


/opt/conda/lib/python3.7/site-packages/jax/_src/dispatch.py in backend_compile(backend, built_c, options, host_callbacks)
    992   # TODO(sharadmv): remove this fallback when all backends allow `compile`
    993   # to take in `host_callbacks`
--> 994   return backend.compile(built_c, compile_options=options)
    995 
    996 # TODO(phawkins): update users.

XlaRuntimeError: UNKNOWN: Failed to determine best cudnn convolution algorithm for:
%cudnn-conv = (f32[1,33,2]{1,2,0}, u8[0]{0}) custom-call(f32[1,34,8]{1,2,0} %copy.3, f32[2,8,2]{0,1,2} %copy.1), window={size=2}, dim_labels=b0f_0io->b0f, custom_call_target="__cudnn$convForward", metadata={op_name="jit(conv_general_dilated)/jit(main)/conv_general_dilated[window_strides=(1,) padding=((0, 1),) lhs_dilation=(1,) rhs_dilation=(1,) dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 2, 1), rhs_spec=(2, 1, 0), out_spec=(0, 2, 1)) feature_group_count=1 batch_group_count=1 lhs_shape=(1, 33, 8) rhs_shape=(2, 8, 2) precision=None preferred_element_type=None]" source_file="/opt/conda/lib/python3.7/site-packages/flax/linen/linear.py" source_line=444}, backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}"

Original error: UNIMPLEMENTED: DNN library is not found.

To ignore this failure and try to use a fallback algorithm (which may have suboptimal performance), use XLA_FLAGS=--xla_gpu_strict_conv_algorithm_picker=false.  Please also file a bug for the root cause of failing autotuning.
```
</details>

**Comment by bhack** [comment]
Is this a JAX, TF or OpenXLA bug?

**Comment by deadsoul44** [comment]
I don't know. I am using the latest Kaggle environment. It can give a hint.

**Comment by AmosChenYQ** [comment]
It Looks like a XLA related bug, but not exactly. In this case XLA wants to transform gpu conv to a new format with best performance, conv instruction will be run on [this](https://github.com/tensorflow/tensorflow/blob/3e3f1ba6dbefcb7643a22409e242b0f0e32e71c5/tensorflow/compiler/xla/service/gpu/gpu_conv_algorithm_picker.cc#L338) function to get a best choice, but it seems that it finally failed. Your log hints that it can't get cuda stream but you can do some workaround as hinted that export environment variable XLA_FLAGS=--xla_gpu_strict_conv_algorithm_picker=false like this or just disable xla autotune using XLA_FLAGS=--xla_gpu_autotune_level=0, hope you may have a try.

**Comment by bhack** [comment]
But I still see `Original error: UNIMPLEMENTED: DNN library is not found.` So it could some problem in the env/installation with cudnn paths or versioning.

I suggest to open this ticket directly in the jax repo like https://github.com/google/jax/issues/4920

**Comment by deadsoul44** [comment]
The same version of the code works with 2D conv. Besides, it is running in Kaggle env. It shouldn't be env/installation issue.
Those XLA flags make the code running as slow as in CPU.

**Comment by bhack** [comment]
If it is a Kaggle env you could check with Kaggle repo/support.

It seems that is running fine with a standard Colab:
https://colab.research.google.com/gist/bhack/9cfeecf51e5e2b49fd51faf69d4f8504/untitled308.ipynb

**Comment by deadsoul44** [comment]
As I said, it is dead slow while running in colab also.

**Comment by bhack** [comment]
> As I said, it is dead slow while running in colab also.

I was just replying to your claim:

> Besides, it is running in Kaggle env. It shouldn't be env/installation issue

Actually I cannot reproduce your original error on a Colab env how you are going to exclusive that it is not an env issue if we cannot reproduce it on Colab?

**Comment by deadsoul44** [comment]
My guess is that it is falling back to one of those flags automatically in colab.

**Comment by bhack** [comment]
> My guess is that it is falling back to one of those flags automatically in colab.

You could check with `print(os.environ)` to see yourself if these envs are set or not on Colab.

**Comment by deadsoul44** [comment]
I tried XLA_FLAGS like this one by one:

```
os.environ["XLA_FLAGS"]="--xla_gpu_strict_conv_algorithm_picker=false"
os.environ["XLA_FLAGS"]="--xla_gpu_autotune_level=0"
```

If I am setting them correctly, in both cases, GPU is not used and CPU is used instead.

**Comment by AmosChenYQ** [comment]
> I tried XLA_FLAGS like this one by one:
> 
> ```
> os.environ["XLA_FLAGS"]="--xla_gpu_strict_conv_algorithm_picker=false"
> os.environ["XLA_FLAGS"]="--xla_gpu_autotune_level=0"
> ```
> 
> If I am setting them correctly, in both cases, GPU is not used and CPU is used instead.

Sorry for my vague reply previous, in this way autotune for conv and gemm is skipped and your program will continue without any error, but the performance is sacrificed. But the reason for the autotune failure requires further investigation..

**Comment by deadsoul44** [comment]
I am trying to understand if I should switch to TF without XLA or wait for a solution. I understand that you cannot make a commitment but do you think a short term solution is possible, maybe within weeks?

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to execute the code without any issue/error and the perfomance is also as expected. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/2c39994dbb1686da43b657b5050f4028/untitled771.ipynb).

**Comment by deadsoul44** [comment]
No error but it doesn't seem to be using GPU. Because, the timing is almost same with CPU and the GPU usage is zero.

**Comment by sachinprasadhs** [comment]
When you set `xla_gpu_strict_conv_algorithm_picker` to True then it will abort immediately when conv algorithm picker fails, rather than logging a warning and proceeding with fallback.

For OneDNN, could you please include the below steps in your code at the starting, i.e before importing Tensorflow for it to take effect.

```
import os
os.environ["TF_ENABLE_ONEDNN_OPTS"]="1"
```

**Comment by mohantym** [comment]
Hi @deadsoul44 !

We are checking to see whether you still need help in this issue  . 
I am able to get results in [2.9](https://colab.sandbox.google.com/gist/mohantym/8218669898302530e205f7d23d4e6dc2/git_58534.ipynb#scrollTo=wuUIMMs0ST20),[ 2.10](https://colab.sandbox.google.com/gist/mohantym/8a38f1052090ae9cb80e3933c36af4d2/git_58534.ipynb) and [2.11](https://colab.sandbox.google.com/gist/mohantym/f845035e4c160ed7dc2d9551ff9379fd/git_58534.ipynb#scrollTo=JZiMOQpzRO6-). 
Could you let us know from your side.

Thank you!
