### ISSUE TITLE
interactive_graphviz reports error "Unable to render graph as URL: FAILED_PRECONDITION: Can't render as URL; no URL renderer was registered"

### ISSUE THREAD

**Issue by shawnwang18** [tensorflow/tensorflow#58538]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

No

### OS Platform and Distribution

Mac OS with M1 

### Current Behaviour?

```shell
When use interactive_graphviz tool in M1 Mac, it reports error:


Unable to render graph as URL: FAILED_PRECONDITION: Can't render as URL; no URL renderer was registered
Trying as HTML...
file:///var/folders/1g/kg1d5zdx5lb4mfqz0qfb5w_r0000gn/T/interactive_graphviz.1668173886537896.html
2022-11-11 21:38:06.543166: I tensorflow/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
```

The generated html file is actually empty.
```


### Standalone code to reproduce the issue

```shell
interactive_graphviz --hlo-text
```

### Relevant log output

_No response_</details>

**Comment by bhack** [comment]
Isn't `--hlo_text`?

https://github.com/tensorflow/tensorflow/blob/3e3f1ba6dbefcb7643a22409e242b0f0e32e71c5/tensorflow/compiler/xla/tools/interactive_graphviz.cc#L106

**Comment by bhack** [comment]
@mohantym Is it `--hlo-text=` or `--hlo_text=`?

**Comment by mohantym** [comment]
@bhack !
My mistake, It is --hlo_txt= .
Thanks for correcting me again. But I could not find proper documentation on above interactive_graphviz command.

@shawnwang18 !
Attached relevant documentation on graphviz usage  for reference. [1](https://blog.jakuba.net/tensorboard-visualization/), [2](https://www.javatpoint.com/how-to-visualize-a-neural-network-in-python-using-graphviz) (for graphviz usage- visualization of Tensorflow operations in graph mode).

Could you confirm whether that above documentation and comment will address this issue.

Thank you!

**Comment by bhack** [comment]
> But I could not find proper documentation on above interactive_graphviz command.

Yes no doc currently. It is only in the usage and in the source code.
