### ISSUE TITLE
old versions of tflite native benchmark binaries

### ISSUE THREAD

**Issue by lkdci** [tensorflow/tensorflow#58536]
Hi, is it possible to download old versions of tflite native benchmark binaries? I can find [here](https://www.tensorflow.org/lite/performance/measurement#download_or_build_the_binary) only the nightly version.

**Comment by mohantym** [comment]
Hi @lkdci !
Sorry for the late response. 
Those are pre-built nightly binaries for immediate use. To build older version, You need to checkout older TF version (2.8, 2.9, 2.10) then use bazel build to build older benchmark binary.

```
bazel build -c opt //tensorflow/lite/tools/benchmark:benchmark_model // on computer
bazel build -c opt --config=android_arm64 \
  //tensorflow/lite/tools/benchmark:benchmark_model. // set path for NDK and SDK toolchain , say yes to Android build then use this command.
```
[ Ref ](https://www.tensorflow.org/lite/performance/measurement#download_or_build_the_binary:~:text=You%20can%20also%20build%20the%20native%20benchmark%20binary%20from%20source%20on%20your%20computer.)

Hope it addresses your query.

Thank you!

**Comment by lkdci** [comment]
Thanks! it works well
