### ISSUE TITLE
Ubuntu 20.04 based Tensorflow images don't include Python 3.9 as indicated in the dockerhub docs

### ISSUE THREAD

**Issue by TaylorZowtuk** [tensorflow/tensorflow#58556]
I believe there is either a build issue or the [dockerhub docs](https://hub.docker.com/r/tensorflow/tensorflow) need to be clarified.

My understanding is that the image for the tensorflow:2.10.0 release (and other recent releases) is guaranteed to include Python 3.9 based on the following excerpts from the dockerhub docs:
- "Images built after Sept 2021 are based on Ubuntu 20.04"
- "... [Python] 3.9 for Ubuntu 20-based images"

When using the 2.10.0 image I find that the OS is correctly Ubuntu 20.04 but that the Python version is 3.8. Running the following commands indicate the absence of Python 3.9:
```shell
root@4fbf1b14a2dd:/# cat /etc/issue
Ubuntu 20.04.5 LTS \n \l
root@4fbf1b14a2dd:/# python3 -V
Python 3.8.10
root@4fbf1b14a2dd:/# ls /usr/bin/python*
/usr/bin/python3  /usr/bin/python3-config  /usr/bin/python3.8  /usr/bin/python3.8-config
```

I looked through the issues/pull requests and through stackoverflow and found no reports of this issue which I find surprising. That most likely means that I am just misinterpreting the guarantees made by the docs - but maybe this is sufficient support to clarify the docs further if that is the case?

### Standalone code to reproduce the issue

```shell
run --rm -it tensorflow/tensorflow:2.10.0 /bin/bash
```

**Comment by SuryanarayanaY** [comment]
Hi @TaylorZowtuk ,
I tried with nightly tag.
```
suryanarayanay-macbookpro:~ suryanarayanay$ docker pull tensorflow/tensorflow:nightly
nightly: Pulling from tensorflow/tensorflow
eaead16dc43b: Already exists 
1b9230cbe322: Pull complete 
167d6208215e: Pull complete 
b96bde8a28a2: Pull complete 
f1bc84f80937: Pull complete 
d36051af5308: Pull complete 
b9cb7e0ecd56: Pull complete 
a0c4a2614767: Pull complete 
Digest: sha256:f67415763624dbde16e5bb52f918c724d2acfaeed1a5d1e428f5177079c3d1b2
Status: Downloaded newer image for tensorflow/tensorflow:nightly
docker.io/tensorflow/tensorflow:nightly
suryanarayanay-macbookpro:~ suryanarayanay$ run --rm -it tensorflow/tensorflow:nightly /bin/bash
-bash: run: command not found
suryanarayanay-macbookpro:~ suryanarayanay$ docker run -it tensorflow/tensorflow:nightly bash
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

________                               _______________                
___  __/__________________________________  ____/__  /________      __
__  /  _  _ \_  __ \_  ___/  __ \_  ___/_  /_   __  /_  __ \_ | /| / /
_  /   /  __/  / / /(__  )/ /_/ /  /   _  __/   _  / / /_/ /_ |/ |/ / 
/_/    \___//_/ /_//____/ \____//_/    /_/      /_/  \____/____/|__/


WARNING: You are running this container as root, which can cause new files in
mounted volumes to be created as the root user on your host machine.

To avoid this, run the container by specifying your user's userid:

$ docker run -u $(id -u):$(id -g) args...

root@3d174a62a5ca:/# cat /etc/issue
Ubuntu 20.04.5 LTS \n \l

root@3d174a62a5ca:/# python3 -V
Python 3.8.10
root@3d174a62a5ca:/# ls /usr/bin/python*
/usr/bin/python3         /usr/bin/python3.8
/usr/bin/python3-config  /usr/bin/python3.8-config
root@3d174a62a5ca:/# 
```
and i could find python 3.8.10 only there. 

Then I have checked the docker documentation [here](https://hub.docker.com/r/tensorflow/tensorflow/) which states:
`Versioned images <= 1.15.0 (1.x) and <= 2.1.0 (2.x) have Python 3 (3.5 for Ubuntu 16-based images; 3.6 for Ubuntu 18-based images; 3.9 for Ubuntu 20-based images) in images tagged "-py3" and Python 2.7 in images without "py" in the tag.`
which states until <= 2.x for Ubuntu 20 OS it is Python 3.9 .

and then i found:
`All newer images are Python 3 only`.
It's not clearly stated which Python Version being used whether 3.8 or 3.9 & higher? Isn't it ?

I will also cross check with concern Team and let you updated.But the thing is it is not confirmed anywhere in the documentation (at least that i have gone through) that 3.9 Version being used in TF latest docker images.Am I missing anything here ? Please let me know.

Thankyou!

**Comment by AriJeannin** [comment]
Got the same issue here, looking forward to get Python 3.9 with Tensorflow >=2.11 

Thankyou! :)

**Comment by TaylorZowtuk** [comment]
@SuryanarayanaY yes your findings and understanding of the docs seem to match mine. 

I should also add another point about the following guarantee:
> Versioned images <= 1.15.0 (1.x) and <= 2.1.0 (2.x) have Python 3 (3.5 for Ubuntu 16-based images; 3.6 for Ubuntu 18-based images; 3.9 for Ubuntu 20-based images) in images tagged "-py3" and Python 2.7 in images without "py" in the tag.

Testing those latest versions specified reveal that they are both Ubuntu 18-based and come with Python 3.6. Here are my findings (tested in a similar manner):
```
tensorflow-2.1.0-py3: Ubuntu 18.04, Python 3.6.9
tensorflow:1.15.0-py3: Ubuntu 18.04, Python 3.6.8
```
Since those are the latest versions specified by that guarantee, and they are Ubuntu-18 based, it doesn't seem like there would be any Ubuntu 20-based versions before that. So why would it be specified? This is what made me think that this guarantee (3.9 for Ubuntu 20-based images) applied to the more recent Tensorflow releases (which are Ubuntu 20-based).


It seems up to that tf version <= 2.1.0 the docs clearly outline what version of Python to expect. And for more recent versions, the docs aren't very clear. So I feel, at a minimum, the docs could be improved by outlining which Python version to expect for more recent versions.

**Comment by SuryanarayanaY** [comment]
@TaylorZowtuk ,

Thanks for all your hardwork and time you put on this issue.We will definitely verify and rectify wherever corrections/clarifications needed and the same will be updated.

Thankyou!

**Comment by sachinprasadhs** [comment]
@angerson , Could you please look into this, it seems like the python versions 3.9 and 3.10 are not included in the published docker images, unlike the version which we publish for the `tf-nightly-gpu` where python version is included from 3.7 - 3.10 here https://pypi.org/project/tf-nightly-gpu/2.12.0.dev20221201/#files.

**Comment by TaylorZowtuk** [comment]
Any updates?

**Comment by angerson** [comment]
Yes, it looks like this was a documentation error. I have fixed it now, and the line in question now reads "Python 3.8".

Thanks for your report & patience.
