### ISSUE TITLE
TF Lite C library fails to build

### ISSUE THREAD

**Issue by stakach** [tensorflow/tensorflow#58550]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

Linux Debian 11 (bullseye)

### Python version

3.9.2

### GCC/Compiler version

10.2.1

### Current Behaviour?

```shell
Trying to build the [TensorFlow Lite C library](https://www.tensorflow.org/lite/guide/build_cmake#build_tensorflow_lite_c_library) following the official guide

errors with:


CMake Error at CMakeLists.txt:63 (add_library):
  Cannot find source file:

    c_api.cc
```
```


### Standalone code to reproduce the issue

```shell
git clone --depth 1 https://github.com/tensorflow/tensorflow
mkdir tflite_build
cd tflite_build
cmake ../tensorflow/tensorflow/lite/c
```
```


### Relevant log output

```shell
CMake Error at CMakeLists.txt:63 (add_library):
  Cannot find source file:

    c_api.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:63 (add_library):
  No SOURCES given to target: tensorflowlite_c


CMake Generate step failed.  Build files cannot be regenerated correctly.
```
</details>

**Comment by stakach** [comment]
The build works if I do the following:
`cp ./tensorflow/tensorflow/lite/core/c/c_api.cc ./tensorflow/tensorflow/lite/c/c_api.cc`

all up this generates the desired output

```
git clone --depth 1 https://github.com/tensorflow/tensorflow
cp ./tensorflow/tensorflow/lite/core/c/c_api.cc ./tensorflow/tensorflow/lite/c/c_api.cc
mkdir tflite_build
cd tflite_build
cmake ../tensorflow/tensorflow/lite/c
cmake --build . -j
```

outputs

```
[ 95%] Building CXX object CMakeFiles/tensorflowlite_c.dir/c_api_experimental.cc.o
[100%] Linking CXX shared library libtensorflowlite_c.so
[100%] Built target tensorflowlite_c
```

as expected

**Comment by mohantym** [comment]
Hi @stakach !
Thanks @stakach for reporting this bug.
I could replicate this issue in master branch. 

Could you raise a PR based on your observations. 

Thank you!

**Comment by terryheo** [comment]
Let me handle this issue.

**Comment by sachinprasadhs** [comment]
@stakach , https://github.com/tensorflow/tensorflow/commit/17e3646683f0149091384d250b27d6f52556ee78 fix should resolve your build issue. Thanks @terryheo for the quick fix.

**Comment by stakach** [comment]
working for me

**Comment by sachinprasadhs** [comment]
Thanks for the confirmation, could you please close the issue as well.
