### ISSUE TITLE
difference between core/grappler/optimizers/graph_optimizer.h and core/common_runtime/graph_optimizer.h

### ISSUE THREAD

**Issue by lsd1994** [tensorflow/tensorflow#58551]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.6

### Custom Code

No

### Current Behaviour?

```shell
This is not a bug report, just a question.
Now I'm learning the source code of tensorflow and I can't understand the difference between these two graph_optimizer.h(core/grappler/optimizers/graph_optimizer.h and core/common_runtime/graph_optimizer.h). Can anyone explain this for me? Thanks.
```

### Standalone code to reproduce the issue

```shell
none
```

### Relevant log output

_No response_</details>

**Comment by pat749** [comment]
The **graph_optimizer.h** file in **core/grappler/optimizers** is used for optimizing the computation graph before it is executed, while the **graph_optimizer.h** file in **core/common_runtime** is used for optimizing the computation graph during execution.

**Comment by lsd1994** [comment]
Thank you for ypur help, I will learn more about that.
