### ISSUE TITLE
Error while Retraining Inception

### ISSUE THREAD

**Issue by Research2** [tensorflow/tensorflow#5857]
On running this command:

python tensorflow/examples/image_retraining/retrain.py \
--bottleneck_dir=/tf_files/bottlenecks \
--how_many_training_steps 500 \
--model_dir=/tf_files/inception \
--output_graph=/tf_files/retrained_graph.pb \
--output_labels=/tf_files/retrained_labels.txt \
--image_dir /tf_files/flower_photos

I am getting: 
IOError: CRC check failed 0x76f1f85e != 0x6caceac0L

**Comment by prb12** [comment]
Please can you provide all of the information requested in the issues reporting template.

**Comment by Research2** [comment]
I am following these steps on the codelabs. (Link : https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#4)

I am getting stuck at Step 5. The error shown is as mentioned in my previous query.
Can you please help?

**Comment by vade** [comment]
https://www.mikeash.com/getting_answers.html

**Comment by allenwang7** [comment]
I'm having this same issue. :(

**Comment by poxvoculi** [comment]
I would like to help, but this kind of open-ended question without providing the background information requested in the issues reporting template poses the prospect that it may take me a long time to run through the codelab myself, in a setup different in unknown ways from yours, and not discover any problem.  This forum is intended for well-characterized bug reports and feature requests.  Usage difficulties should be posted to stackoverflow.

**Comment by taro10h** [comment]
I run into the same issue. Machine: MacOS 10.12.1

I follow the 9-step tutorial to run the 1st Tensorflow 
https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/

Step 1-4 are smooth ( install docker, install tensorflow, retrieve images for training).

Step 5 presents a method to train the imagenet last layer based on local image with the following python command:

python tensorflow/examples/image_retraining/retrain.py 
--bottleneck_dir=/tf_files/bottlenecks 
--how_many_training_steps 500 
--model_dir=/tf_files/inception 
--output_graph=/tf_files/retrained_graph.pb 
--output_labels=/tf_files/retrained_labels.txt 
--image_dir /tf_files/flower_photos

Below is the error log:
Traceback (most recent call last):
  File "tensorflow/examples/image_retraining/retrain.py", line 930, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "tensorflow/examples/image_retraining/retrain.py", line 809, in main
    maybe_download_and_extract()
  File "tensorflow/examples/image_retraining/retrain.py", line 371, in maybe_download_and_extract
    tarfile.open(filepath, 'r:gz').extractall(dest_directory)
  File "/usr/lib/python2.7/tarfile.py", line 2051, in extractall
    self.extract(tarinfo, path)
  File "/usr/lib/python2.7/tarfile.py", line 2088, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/usr/lib/python2.7/tarfile.py", line 2164, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python2.7/tarfile.py", line 2205, in makefile
    copyfileobj(source, target)
  File "/usr/lib/python2.7/tarfile.py", line 265, in copyfileobj
    shutil.copyfileobj(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
  File "/usr/lib/python2.7/tarfile.py", line 818, in read
    buf += self.fileobj.read(size - len(buf))
  File "/usr/lib/python2.7/tarfile.py", line 736, in read
    return self.readnormal(size)
  File "/usr/lib/python2.7/tarfile.py", line 745, in readnormal
    return self.fileobj.read(size)
  File "/usr/lib/python2.7/gzip.py", line 261, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 308, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 347, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0x76f1f85e != 0x6caceac0L

**Comment by Research2** [comment]
I fixed it by installing tensor flow on my Mac and running it through Virtual Environment. Also, I downloaded the inception file manually and pasted it in the tf_files folder manually.

**Comment by MichaelAHood** [comment]
@Research2  "I fixed it by installing tensor flow on my Mac and running it through Virtual Environment. Also, I downloaded the inception file manually and pasted it in the tf_files folder manually."

Works for me.

**Comment by jack-bischoff** [comment]
So it appears this error is thrown when a previous copy of the inception v3 graph is downloaded and you try to run retrain.py (may or may not depend on whether the previous downloaded model is corrupted). 

Solution: `cd` into the `model_dir` folder  (where the model is downloaded) and delete the previously downloaded model + .zip file. My hunch is that Python isn't rewriting the old corrupted files and instead throwing and error if you rerun the retrainer.py (fyi the default directory is `/tmp/imagenet` if you didn't specify a specific `model_dir`).

**Comment by jdpigeon** [comment]
Deleting half complete download + restarting container worked for me

**Comment by bharath96sripathy** [comment]
@delphiy Did you get any solution? Even I'm stuck with that same error. 
retrained_graph.pb and retrained_labels.txt files have problem creating inside tf_files folder
its says : "tensorflow.python.framework.errors_impl.UnknownError: Failed to create a NewWriteableFile: C:/Program Files/Git/tf_files/retrained_graph.pb : Access is denied. ; Input/output error
