### ISSUE TITLE
there is no operator to calculate the matrix's inverse using tflite

### ISSUE THREAD

**Issue by ZYX-MLer** [tensorflow/tensorflow#58599]
tf.raw_ops.MatrixInverse and tf.linalg.svd is not supported in tflite 
BatchMatrixInverse is not available in GraphDef version 1205.

Hence， how to calculate the matrix's inverse using tflite?

I need some Op to calculate the  matrix's inverse

best wishes

**Comment by mohantym** [comment]
Hi @ZYX-MLer !
You can check in [custom Ops documentation ](https://www.tensorflow.org/lite/guide/ops_custom)for registering a custom op (like this case ) which might address this  requirement .
Thank you!

**Comment by ZYX-MLer** [comment]
> Hi @ZYX-MLer ! I can see BatchMatrixInverse in [select ops ](https://www.tensorflow.org/lite/guide/op_select_allowlist)allow list . You can include them in lite model through [select ops](https://www.tensorflow.org/lite/guide/ops_select) syntax.
> 
> ```
> converter.target_spec.supported_ops = [
>   tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
>   tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
> ]
> ```
> 
> You can also check in [custom Ops documentation ](https://www.tensorflow.org/lite/guide/ops_custom)for registering a custom op which might address your requirement.
> 
> @sachinprasadhs ! Could you look at this issue.
> 
> Thank you!

thank you for your replay,

my tf is 2.10, my system is MacOS Monterey, and my code is as follows:

`Ma_t = tf.linalg.matrix_transpose(Ma)
        Ma_i = tf.raw_ops.MatrixInverse(input=tf.matmul(Ma_t, Ma))
        Ma_i = tf.matmul(Ma, Ma_i)` 

then  I got the following error.

"tensorflow.lite.python.convert_phase.ConverterError: <unknown>:0: error: loc(callsite(callsite(fused["MatrixInverse:", "MatrixInverse@__inference_call_78"] at fused["PartitionedCall:", "PartitionedCall@__inference_signature_wrapper_102"]) at fused["PartitionedCall:", "PartitionedCall"])): 'tf.MatrixInverse' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["PartitionedCall:", "PartitionedCall"]): called from
<unknown>:0: note: loc(callsite(callsite(fused["MatrixInverse:", "MatrixInverse@__inference_call_78"] at fused["PartitionedCall:", "PartitionedCall@__inference_signature_wrapper_102"]) at fused["PartitionedCall:", "PartitionedCall"])): Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: failed while converting: 'call': 
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: MatrixInverse
Details:
	tf.MatrixInverse(tensor<3x3xf32>) -> (tensor<3x3xf32>) : {adjoint = false, device = ""}
"

best wishes

**Comment by mohantym** [comment]
@ZYX-MLer !
You got the Select ops error as expected. Just add these two code snippet before conversion.
```
#load the model using load from saved_model or concrete_function, see [TF lite converter.](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter) doc.
.......
#add select ops syntax
......
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_model = converter.convert()

```
Thank you!

**Comment by ZYX-MLer** [comment]
> @ZYX-MLer ! You got the Select ops error as expected. Just add these two code snippet before conversion.
> 
> ```
> #load the model using load from saved_model or concrete_function, see [TF lite converter.](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter) doc.
> .......
> #add select ops syntax
> ......
> converter.target_spec.supported_ops = [
>   tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
>   tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
> ]
> tflite_model = converter.convert()
> ```
> 
> Thank you!

Thank you for your replay, I covert the model successfully, after adding the tf.lite.OpsSet.SELECT_TF_OPS. 

what the different between the TensorFlow lite ops and TensorFlow ops? 

Dose it only increase the size of aar?

By the way, is there some best practice on deploying algorithm on dsp or npu? the ops supported by the nnapi is so limited. I need some matrix ops such as multiplication and inverse.



Best wishes

**Comment by sachinprasadhs** [comment]
Tensorflow Lite operators are TFLite builtin operators, TFLite builtin ops are usually recommended because it is simple to optimize and also it will be lesser in size.
![image](https://user-images.githubusercontent.com/73069040/202538112-5ea7ef96-9209-421e-96a6-f27ec3395fe0.png)

You can refer to the document [here](https://www.tensorflow.org/lite/guide/ops_compatibility) for complete details. 

The list of supported `builtinops` for different data types can be found [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema_generated.h#L909).
Team is working on including more OP under builtin ops, till then you can make use of Select OP. 

For example usage and more details on delegates, refer the document [here](https://www.tensorflow.org/lite/android/delegates/hexagon).
