### ISSUE TITLE
Tflite GPU Delegate error for FULLY_CONNECTED

### ISSUE THREAD

**Issue by macsmy** [tensorflow/tensorflow#58607]
### 1. System information

- OS Platform and Distribution: Ubuntu 20.4
- TensorFlow installation: pip package
- TensorFlow library: 2.10

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

Model is successfully converted. However, during benchmark with GPU delegate (1. using latest benchmark binary: https://www.tensorflow.org/lite/performance/measurement#native_benchmark_binary 2. using older benchmark binary), following error appears: 
1. ERROR: TfLiteGpuDelegate Init: Unrecognized Write selector
2. ERROR: TfLiteGpuDelegate Init: FULLY_CONNECTED: Amount of input data should match weights width

What is more interesting, if i convert the model using tensorflow 2.3.4, everything works as expected - i can run the benchmark without any problems. 
It seems that starting from tf 2.4, some bug was introduced...

**Comment by macsmy** [comment]
i can share the tflite model with this problem, if needed

**Comment by tiruk007** [comment]
@macsmy 
Sorry for the late reply, Could you please share the tflite model to reproduce the issue ?

Thank you!

**Comment by macsmy** [comment]
@tiruk007 
[tmp.zip](https://github.com/tensorflow/tensorflow/files/10067209/tmp.zip)

**Comment by macsmy** [comment]
without GPU delegates, inference is okay

**Comment by tiruk007** [comment]
@macsmy 
Could you please refer to the similar [issue_1](https://github.com/tensorflow/tensorflow/issues/57180) & [issue_2](https://github.com/tensorflow/tensorflow/issues/34525) and let us know if it helps.

Thank you!

**Comment by macsmy** [comment]
thanks, it resolves the issue, i can convert and run the model using tf 2.10. however, surprisingly, when im using gelu as activation, most of the OPs fallback to CPU. other activations, such as swish, work fine. isnt gelu supported on the GPU?

**Comment by tiruk007** [comment]
@macsmy 
Can you please refer to [Supported Select TensorFlow operators](https://www.tensorflow.org/lite/guide/op_select_allowlist) and close the issue if it resolved.

Thank you!
