### ISSUE TITLE
TF2.11 Release Estimate?

### ISSUE THREAD

**Issue by ohadkatz** [tensorflow/tensorflow#58604]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

source

### Tensorflow Version

TF2.11

### Custom Code

No

### Current Behaviour?

```shell
Noticed that there has been activity on the TF2.11 branch for release, and wanted to inquire if there was an ETA on this particular release, or a timeline on when we should expect another RC for TF2.11?
```

### Standalone code to reproduce the issue

```shell
N/A
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @ohadkatz !

That is a good question actually. 
Could you post it on TF forum too. 

Thank you!
