### ISSUE TITLE
gpu metal  lack  ”inference_context_generated.h“

### ISSUE THREAD

**Issue by mengran1234** [tensorflow/tensorflow#58609]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.10 or 2.11

### Custom Code

Yes

### OS Platform and Distribution

ios

### Mobile device

iphone

### Python version

3.7

### Bazel version

no 

### GCC/Compiler version

no

### CUDA/cuDNN version

no

### GPU model and memory

111

### Current Behaviour?

```shell
A bug happened!
#include "tensorflow/lite/delegates/gpu/metal/inference_context_generated.h"
But I can not find the inference_context_generated.h.WHy?
Thanks
```

### Standalone code to reproduce the issue

```shell
111
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @chenliang110 !
Thanks for reporting it.

@sachinprasadhs !
Could you look at this bug.

Thank you!

**Comment by sachinprasadhs** [comment]
`inference_context_generated.h` is automatically generated by the `FlatBuffers compiler`.
