### ISSUE TITLE
Tensorflow 2.10 cannot be installed using `poetry` on linux aarch64

### ISSUE THREAD

**Issue by ColinVDH** [tensorflow/tensorflow#58602]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

linux aarch64

### Python version

3.8

### Current Behaviour?

Poetry parses the endpoint at `https://pypi.org/pypi/tensorflow/2.10.0/json` to get dependency metadata. The endpoint returns:
```shell
[
  "absl-py (>=1.0.0)",
  "astunparse (>=1.6.0)",
  "flatbuffers (>=2.0)",
  "gast (<=0.4.0,>=0.2.1)",
  "google-pasta (>=0.1.1)",
  "h5py (>=2.9.0)",
  "keras-preprocessing (>=1.1.1)",
  "libclang (>=13.0.0)",
  "numpy (>=1.20)",
  "opt-einsum (>=2.3.2)",
  "packaging",
  "protobuf (<3.20,>=3.9.2)",
  "setuptools",
  "six (>=1.12.0)",
  "termcolor (>=1.1.0)",
  "typing-extensions (>=3.6.6)",
  "wrapt (>=1.11.0)",
  "tensorflow-io-gcs-filesystem (>=0.23.1)",
  "grpcio (<2.0,>=1.24.3)",
  "tensorboard (<2.11,>=2.10)",
  "tensorflow-estimator (<2.11,>=2.10.0)",
  "keras (<2.11,>=2.10.0)"
]
```

However, the linux aarch64 wheel has different dependencies, namely `tensorflow-cpu-aws`. Since the dependency metadata is split across wheels, package managers like `poetry` are unable to resolve them correctly. 

**The solution is to have a unified list of dependencies across wheels, with PEP508 environment markers to specify platform-specific dependencies.**

### Standalone code to reproduce the issue

```shell
poetry add tensorflow@2.10.0
poetry shell
python -c "import tensorflow"
```

### Relevant log output

```shell
(app-py3.8) root@53e9f35d6529:/app# python -c "import tensorflow"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
```
</details>

**Comment by SuryanarayanaY** [comment]
Hi @ColinVDH ,

Could you please refer similar issues attached here and see whether they solves your problem.Please refer [TF-48939](https://github.com/tensorflow/tensorflow/issues/48939), [SO](https://stackoverflow.com/questions/70356867/solverproblemerror-on-install-tensorfow-with-poetry) and [python_poetry](https://github.com/python-poetry/poetry/issues/1330) here and let us know if it helps?

Thankyou

**Comment by ColinVDH** [comment]
@SuryanarayanaY The issue can be worked around by adding the following to the `pyproject.toml`:
```
tensorflow = "2.10.0"
tensorflow-cpu-aws = {"version" = "2.10.0", markers = "platform_system == 'Linux' and (platform_machine == 'arm64' or platform_machine == 'aarch64')"}
```

However, this is a workaround. Ideally the correct dependencies should be listed in https://pypi.org/pypi/tensorflow/json in the `requires_dist` section of `info`. Namely, `tensorflow-cpu-aws` should be correctly listed as a dependency in the linux aarch64 environment.

**Comment by SuryanarayanaY** [comment]
Hi @ColinVDH,

Glad that you find a workaround.I will also escalate your suggestion in above [comment](https://github.com/tensorflow/tensorflow/issues/58602#issuecomment-1324045059) to Development team for their review and see what can be done. 

Since your issue got resolved would you like to close the issue ?

**Comment by twerkmeister** [comment]
Hey @SuryanarayanaY, we noticed that the released arm packages for tensorflow 2.10 and 2.11 are broken, or rather empty, which leads to the described problem of not being able to import tensorflow. You can see this on the [pypi downloadable files page for tf 2.10.1](https://pypi.org/project/tensorflow/2.10.1/#files). You see that all the aarch64 packages have a size of only 1.9 kb

**Comment by twerkmeister** [comment]
It seems that tensorflow-cpu-aws then contains the actual tensorflow code for arm which is odd since probably not all arm machines are on aws

**Comment by mihaimaruseac** [comment]
CC @nitins17 @learning-to-play @rishikasinha-tf

**Comment by learning-to-play** [comment]
Hi @elfringham @mseth10 Could you please take a look?

**Comment by elfringham** [comment]
@twerkmeister The released ARM64 packages are neither broken nor empty. They are simple redirects to where the full installs can be found which is why they are so small. You may run 'pip install tensorflow' on AARCH64 and it will install the desired package.
tensorflow-cpu-aws is so named because it is built using AWS resources, the name is not meant to imply that it is only suitable for running on AWS instances.
