### ISSUE TITLE
Compiling libtensorflow for ios issues : can't fine Eigen/Core

### ISSUE THREAD

**Issue by simdax** [tensorflow/tensorflow#58618]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

No

### OS Platform and Distribution

MacOs ventura 13.0

### Bazel version

5.3.2

### GCC/Compiler version

clang 14.0 (Xcode shipped)

### Current Behaviour?

```shell
Hello !

I am not able to build libtensorflow.so for ios.
I just `./configure` and accepted all defaults.

I can build for my mac:
`bazel build -c opt //tensorflow:libtensorflow.so`
but cross compiling for ios
`bazel build -c opt --config=ios //tensorflow:libtensorflow.so`

gives me this error

`
ERROR: /Users/SX/Documents/soundx-ai/vendor/tensorflow/tensorflow/cc/saved_model/BUILD:319:11: Compiling tensorflow/cc/saved_model/metrics.cc failed: (Aborted): wrapped_clang_pp failed: error executing command external/local_config_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 32 arguments skipped)
In file included from tensorflow/cc/saved_model/metrics.cc:16:
In file included from ./tensorflow/cc/saved_model/metrics.h:25:
In file included from ./tensorflow/core/lib/monitoring/counter.h:19:
In file included from ./tensorflow/tsl/lib/monitoring/counter.h:85:
In file included from ./tensorflow/tsl/lib/monitoring/collection_registry.h:109:
In file included from ./tensorflow/tsl/lib/monitoring/collected_metrics.h:28:
In file included from ./tensorflow/tsl/lib/monitoring/metric_def.h:24:
In file included from ./tensorflow/tsl/lib/monitoring/types.h:22:
In file included from ./tensorflow/tsl/platform/types.h:21:
In file included from ./tensorflow/tsl/platform/bfloat16.h:20:
./third_party/eigen3/Eigen/Core:1:10: fatal error: 'Eigen/Core' file not found
#include "Eigen/Core"
```

I have a eigen3 lib installed with brew, in my `/opt/homebrew/Cellar/eigen/3.4.0_1/include/eigen3/Eigen/Core`, but I did not get how I could give this information to bazel. I'm not able to play with the path directly.

Any clue to solve this problem ?

Thank you!
```


### Standalone code to reproduce the issue

```shell
bazel build -c opt --config=ios //tensorflow:libtensorflow.so
```

### Relevant log output

_No response_</details>

**Comment by simdax** [comment]
OK I was able to solve my problem myself. I had to manually call the bazel rule "install_eigen_headers" from third_party/eigen3

Is it normal I have to call it myself ?

**Comment by tilakrayal** [comment]
@simdax,
Could you please try installing TensorFlow v2.10 with compiler `Clang from xcode 10.14` with `Bazel 5.1.1` as those are tested build configurations & please take a look at this official doc [link](https://www.tensorflow.org/install/source#cpu_2) for the reference and check if you are facing the same error. Thank you!

**Comment by simdax** [comment]
I can be even more specific. One of the failing project is 
saved_model:util

`bazel build -c opt //tensorflow/cc/saved_model:util` works
`bazel build -c opt //tensorflow/cc/saved_model:util --config=ios` don't works

**Comment by SuryanarayanaY** [comment]
Hi @simdax ,

Could you please confirm what option you have chosen while configuring `./configure` for below option.

`Do you wish to build TensorFlow with iOS support? [y/N]:`

If you missed choosing `y`  then it might not be supporting IOS. Please cross check and try with `y` option for above configuration part and lets know if still facing issue.

Thankyou!

**Comment by simdax** [comment]
Yes I can confirm that. One of the problem is linked to the "if_mobile" option in bazel. All the sources built with it failed.
I think TF is assuming building for IOS need to be TFlite, which is not my case ?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
