### ISSUE TITLE
from keras.models import load_model raises no module named tensorflow.compat error

### ISSUE THREAD

**Issue by sryu1** [tensorflow/tensorflow#58610]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

2.11

### Custom Code

No

### OS Platform and Distribution

Windoes 11

### Python version

3.7.9

### Current Behaviour?

```shell
When doing  keras.models import load_model, An error saying no module named tensorflow.compat appears
```

### Standalone code to reproduce the issue

```shell
Just open python 3.7 and type  keras.models import load_model
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "c:/Users/Noah Ryu/Coding/AI/Teachable Machine/Guesser3.py", line 1, in <module>
    from keras.models import load_model # TensorFlow is needed for Keras to work
  File "C:\Users\Noah Ryu\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\__init__.py", line 21, in <module>
    from keras import models
  File "C:\Users\Noah Ryu\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\models\__init__.py", line 18, in <module>  
    from keras.engine.functional import Functional
  File "C:\Users\Noah Ryu\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\functional.py", line 24, in <module>
    import tensorflow.compat.v2 as tf
ModuleNotFoundError: No module named 'tensorflow.compat'
```
</details>

**Comment by SuryanarayanaY** [comment]
Hi @sryu1 ,

Instead of `keras.models import load_model`, Please use `from tensorflow.keras.models import load_model` .

**Comment by sryu1** [comment]
I've already tried it previously and it didn't work 
```
Traceback (most recent call last):
  File "c:/Users/Noah Ryu/Coding/AI/Teachable Machine/Guesser.py", line 1, in <module>
    from tensorflow.keras.models import load_model
ModuleNotFoundError: No module named 'tensorflow.keras'
```

**Comment by sryu1** [comment]
Also, I noticed the tf 2.10 tag, for tensorflow 2.10,  `import keras.models import load_model` works but not for 2.11

**Comment by SuryanarayanaY** [comment]
Hi @sryu1 ,
Sorry i didn't noticed your OS earllier. Please refer the note from Documentation.

`Caution: TensorFlow 2.10 was the last TensorFlow release that supported GPU on native-Windows. Starting with TensorFlow 2.11, you will need to install [TensorFlow in WSL2](https://tensorflow.org/install/pip#windows-wsl2), or install tensorflow-cpu and, optionally, try the [TensorFlow-DirectML-Plugin](https://github.com/microsoft/tensorflow-directml-plugin#tensorflow-directml-plugin-)`

Please refer the attached [link](https://www.tensorflow.org/install/pip) for more details.

**Comment by sryu1** [comment]
Ah, ok. Well, if I'm using tensorflow-cpu, it should work, right? It seems like it doesn't though, it gives back the same error...

**Comment by SuryanarayanaY** [comment]
@sryu1,

Could you please check whether the instructions mentioned in documentation followed correctly?Please refer link [here](https://www.tensorflow.org/install/pip#step-by-step_instructions).Please ignore step5 which is for GPU setup.Please cross check again and confirm us if still problem persists.

Thankyou!

**Comment by sryu1** [comment]
Yes, using a conda environment worked... Is there any way to use windows native and tensorflow-cpu though? Or is that the only option for tf 2.11?

**Comment by sryu1** [comment]
Wait, nevermind, using tensorflow-cpu works with windows native now, I tried uninstalling everything related to tensorflow (tensorflow-cpu, tensorflow-intel, keras, etc.) with pip then installed tensorflow-cpu. :)

**Comment by sryu1** [comment]
So, in conclusion:
`from keras.models import load_model` does not work with native windows and tensorflow 2.11
It works with tensorflow-cpu OR tensorflow 2.11 with a conda environment or other sorts of similar.

**Comment by sryu1** [comment]
That's it, thank you so much! I'll open this issue up again if I have any question regarding this...
