### ISSUE TITLE
Gradient return None

### ISSUE THREAD

**Issue by joshuajennysibbu** [tensorflow/tensorflow#58614]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu

### Current Behaviour?

```shell
I implement a model with a custom training loop and custom loss function. Loss function return a float value. But while calculate gradient tf.gradient(loss,model.trainable_weights), It gives None gradient.  I know the issue is way of calculate loss. I tried with custom mse loss. It works fine. I want to implement loss function like count_predition_0's+count_predition_1's/label_0's+label_1's. It's a binary classification problem. I set batch size is 100. So model return 100 batch output. I only consider few batch eg out of 100 batch i only consider or filter it out 40 based on input. Both label and prediction in same shape that is not issue here. That label and prediction pass to custom_loss function.
```

### Standalone code to reproduce the issue

```shell
def custom_loss(self,output,prediction):
        
     correct_count=tf.math.count_nonzero(tf.math.equal(tf.round(prediction),tf.cast(output,tf.float32)))
        incorrect_count=prediction.shape[0]-correct_count

        incorrect_label_count=tf.where(output==0.0).shape[0]
        correct_label_count=tf.where(output==1.0).shape[0]
            
        return tf.math.divide(tf.math.add(correct_count,incorrect_count),output.shape[0])
```

### Relevant log output

```shell
ValueError: No gradients provided for any variable: (['my_model/object/embeddings:0', 'my_model/dense/kernel:0', 'my_model/dense/bias:0', 'my_model/dense_1/kernel:0', 'my_model/dense_1/bias:0', 'my_model/dense_2/kernel:0', 'my_model/dense_2/bias:0', 'my_model/dense_3/kernel:0', 'my_model/dense_3/bias:0', 'my_model/dense_4/kernel:0', 'my_model/dense_4/bias:0', 'my_model/dense_5/kernel:0', 'my_model/dense_5/bias:0', 'my_model/dense_6/kernel:0', 'my_model/dense_6/bias:0', 'my_model/dense_7/kernel:0', 'my_model/dense_7/bias:0'],). Provided `grads_and_vars` is ((None, <tf.Variable 'my_model/object/embeddings:0' shape=(263, 100) dtype=float32, numpy=
```
</details>

**Comment by joshuajennysibbu** [comment]
This is my trainer class

`import tensorflow as tf
import numpy as np

class Trainer():
    def __init__(self,loss,correct_pred,incorrect_pred,correct_label,incorrect_label):  
        lr_scheduler=lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(initial_learning_rate=0.01,decay_steps=100,decay_rate=0.1)
        self.loss=tf.keras.losses.MeanSquaredError()
        self.optimizer=tf.keras.optimizers.Adam(learning_rate=lr_scheduler)
        self.correct_pred,self.incorrect_pred,self.correct_label,self.incorrect_label=correct_pred,incorrect_pred,correct_label,incorrect_label
        self.loss_metric=loss
        
    def train_step(self,model,log_,object_,user_id,time,output,label_):
        
        with tf.GradientTape() as tape:
            predictions = model(log_,object_,user_id, training=True)
            prediction=tf.gather(predictions, output)
            # loss = self.loss(label_,prediction)
            loss=self.custom_loss(label_,prediction)
            self.loss_metric(loss)
            

        gradients = tape.gradient(loss, model.trainable_variables)
        self.optimizer.apply_gradients(zip(gradients, model.trainable_variables))

        return output,predictions
    
        
    def custom_loss(self,output,prediction):
        correct_count=tf.math.count_nonzero(tf.math.equal(tf.round(prediction),tf.cast(output,tf.float32)))
        incorrect_count=prediction.shape[0]-correct_count

        incorrect_label_count=tf.math.reduce_sum(tf.where(output==0.0))
        correct_label_count=tf.math.reduce_sum(tf.where(output==1.0))
            
        return tf.math.divide(tf.math.add(correct_count,incorrect_count),tf.math.add(correct_label_count,incorrect_label_count))
`

**Comment by tiruk007** [comment]
@joshuajennysibbu 
I was able to execute the given code on Colab using TF v2.11 without any error.  Could you please provide the code with all dependencies to replicate the issue and find the gist [here](https://colab.research.google.com/gist/tiruk007/f69f6d2145ce0dfebdd69436b9450b67/untitled29.ipynb) for reference.

Thank you!

**Comment by joshuajennysibbu** [comment]
I update [gist](https://colab.research.google.com/gist/tiruk007/f69f6d2145ce0dfebdd69436b9450b67/untitled29.ipynb) same custom loss with tf expert sample code. Can you please check..

**Comment by tiruk007** [comment]
@sushreebarsa 
I was able to reproduce the issue on Colab using TF v2.11 and TF-nightly. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/808cd34d2bc25a035a5a3e35ab66e234/58614.ipynb) for reference.

Thank you !
