### ISSUE TITLE
Invalid argument in example

### ISSUE THREAD

**Issue by svobora** [tensorflow/tensorflow#58621]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.11

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 22.04.1

### Python version

3.10

### CUDA/cuDNN version

11.2

### GPU model and memory

RTX 3090 24GB

### Current Behaviour?

```shell
This example returns invalid argument message, but it still runs. I wonder if that is a warning or error.

https://www.tensorflow.org/tutorials/images/classification
```

### Standalone code to reproduce the issue

https://www.tensorflow.org/tutorials/images/classification

### Relevant log output

```shell
layout failed: INVALID_ARGUMENT: Size of values 0 does not match size of permutation 4 @ fanin shape insequential_2/dropout/dropout/SelectV2-2-TransposeNHWCToNCHW-LayoutOptimizer
```
</details>

**Comment by tilakrayal** [comment]
@svobora,
I tried to execute the given code in the latest stable version and was able to execute without the [error](https://colab.research.google.com/gist/tilakrayal/55eb4e612b0e4058064fb2f24e418f9f/classification.ipynb). The source code of the mentioned doc link also doesn't contain the error. So the document will get updated soon without the error for the future versions. Thank you!

**Comment by svobora** [comment]
The same warning/error happens to my nets using Dropout in Ubuntu 22.04 with TF 2.11.0 when using GPU. Did not happen with 2.10.0. Cannot confirm on Windows since GPU support was dropped in latest version of TF. Right now it seems it does not affect performance.

**Comment by tilakrayal** [comment]
@svobora,
As mentioned the code was executed without any [issues](https://colab.research.google.com/gist/tilakrayal/55eb4e612b0e4058064fb2f24e418f9f/classification.ipynb) and the document will get updated soon without the error for the future tensorflow  versions. Thank you!

**Comment by svobora** [comment]
Please kindly reopen.

**Comment by tilakrayal** [comment]
@svobora,
I tried with tensorflow v2.11 only and it was executed without any issues. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/976ad5e7f6b5f80b99a6b09cf2a12ba6/classification.ipynb).

![image](https://user-images.githubusercontent.com/81610181/209545393-b22c93fa-353f-4bf6-b19a-ee5d72efda1c.png)

**Comment by svobora** [comment]
Thx, I am no longer able to replicate the issue, without actually knowing what the cause is/was.
