### ISSUE TITLE
tf.distribute.experimental.rpc.Server memory leak on server

### ISSUE THREAD

**Issue by YHL04** [tensorflow/tensorflow#58628]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.11

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

11.2/8.1

### GPU model and memory

Nvidia GeForce RTX 2070 6233MB

### Current Behaviour?

```shell
RPC works fine with CPU but when switched to GPU, memory increases linearly.
(Memory stays constant after awhile with CPU)

When training model, memory will keep increasing until desktop freezes.

Code below to reproduce the issue on Google Colab.
```

### Standalone code to reproduce the issue

```shell
# import os
# os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

import tensorflow as tf
import numpy as np
import portpicker
import matplotlib.pyplot as plt

import time
import os
import psutil
process = psutil.Process(os.getpid())


#tf.debugging.set_log_device_placement(True)


def test_simple():

    @tf.function(input_signature=[
        tf.TensorSpec([], tf.int32),
        tf.TensorSpec([], tf.int32)])
    @tf.autograph.experimental.do_not_convert  
    def remote_fn(a, b):
        return tf.add(a,b)

    port = portpicker.pick_unused_port()
    address = "localhost:{}".format(port)
    server = tf.distribute.experimental.rpc.Server.create("grpc", address)
    server.register("addition", remote_fn)
    server.start()

    client = tf.distribute.experimental.rpc.Client.create("grpc",
                address=address, name="test_client")

    a = np.ones(shape=[100, 256], dtype=np.int32)
    b = np.ones(shape=[100, 256], dtype=np.int32)

    hist = []
    for i in range(100000):
        result = client.call(
            args=[a,b],
            method_name="addition",
            output_specs=tf.TensorSpec((), tf.int32))
        if result.is_ok():
            result.get_value()
        # value = client.addition_blocking(a,b)
        # print(value)

        if i % 1000 == 0:
            print(i, ": ", process.memory_info().rss/1024/1024, "MB")
            hist.append(process.memory_info().rss/1024/1024)

    server.close()
    print("After shutdown: ", process.memory_info().rss/1024/1024)
    plt.plot(hist)
    plt.show()


test_simple()
```

### Relevant log output

```shell
909000 :  1414.50390625 MB
910000 :  1414.5078125 MB
911000 :  1414.5078125 MB
912000 :  1414.5078125 MB
913000 :  1414.5078125 MB
914000 :  1414.5078125 MB
915000 :  1414.51171875 MB
916000 :  1414.51171875 MB
917000 :  1414.51171875 MB
918000 :  1414.515625 MB
919000 :  1415.6640625 MB
920000 :  1416.796875 MB
921000 :  1416.796875 MB
922000 :  1416.796875 MB
923000 :  1417.75 MB
924000 :  1418.7109375 MB
925000 :  1418.7109375 MB
926000 :  1418.7109375 MB
927000 :  1418.7109375 MB
928000 :  1418.71484375 MB
929000 :  1418.84765625 MB
930000 :  1418.84765625 MB
931000 :  1418.8515625 MB
932000 :  1418.85546875 MB
933000 :  1419.62890625 MB
934000 :  1419.87890625 MB
935000 :  1420.37890625 MB
936000 :  1420.53125 MB
937000 :  1420.65625 MB
938000 :  1421.83984375 MB
939000 :  1421.84375 MB
940000 :  1422.74609375 MB
941000 :  1422.84375 MB
942000 :  1422.84375 MB
943000 :  1423.3515625 MB
944000 :  1423.8984375 MB
945000 :  1423.91015625 MB
946000 :  1425.5078125 MB
947000 :  1426.109375 MB
948000 :  1426.34765625 MB
949000 :  1426.34765625 MB
950000 :  1426.3515625 MB
951000 :  1426.3515625 MB
952000 :  1427.05859375 MB
953000 :  1427.37890625 MB
954000 :  1427.3828125 MB
955000 :  1428.90234375 MB
956000 :  1429.69140625 MB
957000 :  1429.6953125 MB
958000 :  1430.3046875 MB
959000 :  1432.421875 MB
960000 :  1432.421875 MB
961000 :  1432.421875 MB
962000 :  1432.82421875 MB
963000 :  1432.82421875 MB
964000 :  1432.82421875 MB
965000 :  1433.1328125 MB
966000 :  1433.1328125 MB
967000 :  1433.1328125 MB
968000 :  1433.1328125 MB
969000 :  1434.60546875 MB
970000 :  1434.60546875 MB
971000 :  1434.640625 MB
972000 :  1435.08203125 MB
973000 :  1435.0859375 MB
974000 :  1435.59765625 MB
975000 :  1436.98828125 MB
976000 :  1436.9921875 MB
977000 :  1437.125 MB
978000 :  1437.98828125 MB
979000 :  1441.01953125 MB
980000 :  1441.96875 MB
981000 :  1441.96875 MB
982000 :  1441.97265625 MB
983000 :  1441.97265625 MB
984000 :  1441.97265625 MB
985000 :  1441.97265625 MB
986000 :  1441.97265625 MB
987000 :  1441.97265625 MB
988000 :  1441.97265625 MB
989000 :  1441.97265625 MB
990000 :  1441.9765625 MB
991000 :  1441.9765625 MB
992000 :  1441.98046875 MB
993000 :  1444.41796875 MB
994000 :  1444.78515625 MB
995000 :  1444.78515625 MB
996000 :  1444.78515625 MB
997000 :  1446.05078125 MB
998000 :  1446.05078125 MB
999000 :  1446.05078125 MB
After shutdown:  1447.05078125
```
</details>

**Comment by tiruk007** [comment]
@YHL04 
I tried to reproduce the issue on Colab by using TF v2.11 but facing a different error. Could you please find the gist [here](https://colab.research.google.com/gist/tiruk007/42c560727caf381e6067e02122d426dc/58628.ipynb) for reference and confirm the same.
Thank you!

**Comment by YHL04** [comment]
If you comment out the two lines it should run without error:

    # server.close()
    # print("After shutdown: ", process.memory_info().rss/1024/1024)

but the graph still shows memory increasing linearly

**Comment by tiruk007** [comment]
@sushreebarsa 
I was able to reproduce the issue on Colab using TF v2.11. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/05a199a20963576f1bf834d3f482f6da/58628.ipynb) for reference.

Thank you!

**Comment by YHL04** [comment]
@sushreebarsa @tiruk007 Just wondering if it will be a quick fix or what the plan is since my project is on a deadline...
Thank you.

**Comment by SuryanarayanaY** [comment]
@YHL04 ,
I tested the code both on CPU and GPU.Even with CPU also i observe continuous increase in memory which is conflicting as you confirmed with CPU: `(Memory stays constant after awhile with CPU)` .Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/2add4fc6212b0f1206b5728fddf736ce/-58628-cpu.ipynb#scrollTo=XEjjhLzBQAsv) where i observed the same behaviour with CPU also.Please go through and confirm whether the CPU behaviour here is also same of GPU ?

**Comment by YHL04** [comment]
Uncommented:

```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
```

TF 2.9 CPU:

![image](https://user-images.githubusercontent.com/57779173/203851276-797203bd-71a0-4d5f-bc78-1f13891758d8.png)

TF 2.11 CPU:

![image](https://user-images.githubusercontent.com/57779173/203852232-846ea5b3-b83a-47a9-af90-f32d6abd7c83.png)

TF 2.11.0 CPU on my desktop:
Commented out:

```
        # if result.is_ok():
        #     result.get_value()
        # value = client.addition_blocking(a,b).numpy()
```

![Figure_1](https://user-images.githubusercontent.com/57779173/203853127-a7c221c6-72aa-45cf-b090-bf6d65270bb3.png)

Not sure why I wasn't able to reproduce the same result...

**Comment by SuryanarayanaY** [comment]
Hi @YHL04 ,
Thanks for coming back again to confirm the behaviour on CPU.As you can also confirm the behaviour on CPU also the Memory is in increasing trend,can we confirm that it is not abnormal ? COuld you share your opinion.
Thankyou!

**Comment by YHL04** [comment]
Hi @SuryanarayanaY, 
I'm not sure why the memory increase would be intended, especially when it ends up freezing the desktop, each Client call is independent and there is no reason to store anything after the Client call.

If the behavior is intended, could you please explain why?

**Comment by SuryanarayanaY** [comment]
Hi @YHL04 ,

Iam not confirming yet it as intended behaviour. My intention is to confirm with you the whether the behaviour of Memory Increase is there both on CPU and GPU?

@sachinprasadhs could you please look at the issue.

Thankyou!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

I tried to execute the mentioned code on tf-nightly and observed the code was provided the output as expected. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/22c38bfab2ff426475790a8ebb7f55f9/58790.ipynb).

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
