### ISSUE TITLE
Feature request: easier access to all variables inside a scope

### ISSUE THREAD

**Issue by erickrf** [tensorflow/tensorflow#5862]
Right now, in order to access the variables inside a scope, AFAIK we have to do the following:

    variables = tf.get_collection(tf.GraphKeys.VARIABLES, scope)

It would be far easier if we could just write

    variables = scope.get_all_variables()

or maybe

    variables = tf.get_scope_variables(scope)

Is it a reasonable request?

**Comment by michaelisard** [comment]
@josh11b can you comment or reassign?

**Comment by firstprayer** [comment]
Would love to work on this if @josh11b doesn't have bandwidth :)

**Comment by lukaszkaiser** [comment]
I think it's not easy to introduce new APIs for TF 1.0 now. Any new API will have to go through a design review, and I don't feel like doing that. On the other hand, we could just add a property to the VariableScope object that would select all variables. That's a very small API change, I think. But I'll wait for Martin to comment more, he knows way more about the API process.

**Comment by martinwicke** [comment]
It's not a problem to add new features, we're a little more conservative in what we accept. This seems like a reasonable request to me, I'd go for the `vars = scope.get_variables()` option.

**Comment by lukaszkaiser** [comment]
I think we should have scope.global_variables() (or just scope.variables() ?)  and scope.trainable_variables() to match the global tf functions.Guys (josh11b/firstprayer), will you send a PR?

**Comment by martinwicke** [comment]
This is done, correct? Closing.

**Comment by lukaszkaiser** [comment]
Yes, done!
