### ISSUE TITLE
 Cannot build with CUDA support on Windows.

### ISSUE THREAD

**Issue by Zhaopudark** [tensorflow/tensorflow#58629]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

TF 2.11

### Custom Code

No

### OS Platform and Distribution

Windows 11

### Python version

3.10

### Bazel version

5.3.2

### GCC/Compiler version

MSVC 14.34.31933

### CUDA/cuDNN version

11.8/8.6

### GPU model and memory

RTX3090 24GB

### Current Behaviour?

```shell
When I'm trying to build the latest stable version TensorFlow-GPU (2.11.0) with CUDA on windows as same as we used to do, I find the following Errors

`WARNING: Cannot build with CUDA support on Windows. Starting in TF 2.11, CUDA build is not supported for Windows. To use TensorFlow GPU on Windows, you will need to build/install TensorFlow in WSL2.`

This error prevents me to set further CUDA and GPU info, as the consequence, I cannot build GPU version but only CPU version.
```

### Standalone code to reproduce the issue

```shell
As a normal compiling procedure:


python .\configure.py
```

### Relevant log output

```shell
You have bazel 5.3.2- (@non-git) installed.
Please specify the location of python. [Default is C:\Users\<username>\miniconda3\envs\compile\python.exe]:

Found possible Python library paths:
  C:\Users\<username>\miniconda3\envs\compile\Lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\<username>\miniconda3\envs\compile\Lib\site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

WARNING: Cannot build with CUDA support on Windows.
Starting in TF 2.11, CUDA build is not supported for Windows. For using TensorFlow GPU on Windows, you will need to build/install TensorFlow in WSL2.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:
```
</details>

**Comment by mohantym** [comment]
Hi @Zhaopudark !
It is correct from 2.11 onwards , You have to rely on Windows Subsystem linux for GPU usage.

Alternatively, you can use [Tensorflow-ml plugin](https://github.com/microsoft/tensorflow-directml-plugin#tensorflow-directml-plugin-) through pip .

Attached relevant [thread ](https://learn.microsoft.com/en-us/windows/ai/directml/gpu-tensorflow-wsl)for reference.

Thank you!

**Comment by Zhaopudark** [comment]
@mohantym  Thanks a lot. 

I have been compiling and using the latest version of TensorFlow GPU on Windows for several years, which can always have all features supported on Linux, such as AVX2, XLA .etc., and can work well with other components, such as PowerShell, MySQL, Python, Conda .etc. It can even benefit from automatic GPU overclocking on Windows.

It may a little bit disappointing that since TF 2.11 onwards, the original Windows Platform will not be supported by TensorFlow GPU.  Anyway, thanks a lot for contributing to TF and making it better and better.

Nowadays, I have totally changed to WSL2, compiling and using TF2.11 GPU successfully. In my practice, there may be approximately a 4-5% performance loss if compared to the one on the original Window. But the cost is still acceptable.

WSL2 may always be a less-than-correct and desirable choice. Because users may well choose WSL2 because some of the codes or components they need are not supported on Windows but are supported on Linux, and these users do not necessarily have two separate platforms. But from my point of view,  for most users, the code and components they want are actually supported on Windows, it just requires them to invest some of their time to learn extra Windows operation and maintenance, such as the running mechanisms, the syntax of PowerShell or CMD, and the command line mode of other tools on Windows, and then, they can find a good way to realize their desired codes or components on Windows well.

That is, the reason for not choosing the Window platform may be to save time, but if the Windows community is also active, users don't need to spend much time. 

For a long time, if a user of a machine learning framework uses the Window platform, he/she will be seen as a unicorn. This is unfair because there is always someone who does not have that much money to support two separate platforms, or even three, and as a researcher, the Windows platform is naturally the most economical choice in order to cope with clerical work simultaneously. These people are even willing to spend more time learning Windows operation and maintenance for better usage of the machine learning frameworks but are often discriminated against for "why don't use Mac and Linux servers?".

Users' choices should not be discriminated against, but unfortunately, this no-longer-supporting for original Windows will make Windows users feel more discriminated, even if it is not the official intent. Even though maintaining one more platform will cost more manpower, I still hope the original Windows support will come back. 

Thanks again and best wishes.

**Comment by mohantym** [comment]
Hi @Zhaopudark !
We are not dropping windows support .
 It will be just maintained by third party colloborators (Intel) considering the effort to maintain the integrity and  diversity  . [Ref](https://blog.tensorflow.org/2022/09/announcing-tensorflow-official-build-collaborators.html?_gl=1*fh5thm*_ga*MTY2ODE2Mjk4MC4xNjY0ODgxMDA0*_ga_W0YLR4190T*MTY2OTI2MTA1OC41Mi4xLjE2NjkyNjEwNjguMC4wLjA.)

You can use Tensorflow-Direct ML plugin in same windows machine as suggested in previous thread. 
(Note: A Windows user myself).

Thank you!

**Comment by Zhaopudark** [comment]
@mohantym, thank you.

I have also tried Tensorflow-Direct ML plugin. Even though it is convenient for its simple configuration, it is still in the development phase with less than complete functionality, such as does not support  XLA, mixed precision .etc. 

So, now the situation may be that it is not available in a short term to use the latest version of Tensorflow-GPU or its equivalent replacement on Windows native platform as same as the original and without performance loss.

Hope this 'painful' period will end soon. 
Thank you again, and thanks to all TensorFlow contributors/maintainers for your efforts.

**Comment by mohantym** [comment]
@Zhaopudark !
Thanks for the update and sharing your concern.

@SuryanarayanaY !
Could you look at this issue.

Thank you!

**Comment by SuryanarayanaY** [comment]
@Zhaopudark,

Your concerns regarding dropping the TF_GPU support on windows native is well noted and will be escalated to the concern team.But at present it is official from the [documentation](https://www.tensorflow.org/install/pip#windows-native) that:
`TensorFlow 2.10 was the last TensorFlow release that supported GPU on native-Windows. Starting with TensorFlow 2.11, you will need to install [TensorFlow in WSL2](https://tensorflow.org/install/pip#windows-wsl2)` and there is little we can do here for now at least. 

I am not sure whether Windows native support can be extended in Future versions or not but also can't deny it. It's all based on requirements from community and Tensorflow Team is keenly watching the observations,concerns,inputs from community and may act accordingly. For time being as there is little we can do now shall we close this issue ? 

Thankyou!

**Comment by Zhaopudark** [comment]
@SuryanarayanaY 
Thanks for your detailed information, I will always look forward to a better and widely supported TensorFlow. 
And, this issue can be closed.
Thank you.
