### ISSUE TITLE
Android 12 TensorFlow ML operations are not supported by GPU delegate

### ISSUE THREAD

**Issue by 8700nd** [tensorflow/tensorflow#58623]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

Android 12 (API 31)

### Mobile device

Google Pixel 4

### Current Behaviour?

```shell
Tensorflow lite pose estimation Crashed when switched to GPU.
It says some TF operations are not supported by GPU delegate.
Interestingly when the API is 30 (Android 11) the app runs fine when changing to GPU CPU or NNAPI. No matter what tf model, Movenet lightning or thunder, int 8 or float 16.

I tried it on the TF lite example post estimation APP, changed the compile and target sdk to 31, it crashed with the same error.
```

### Standalone code to reproduce the issue

```shell
fun create(context: Context, device: Device, modelType: ModelType): MoveNet {
            val options = Interpreter.Options()
            var gpuDelegate: GpuDelegate? = null
            options.setNumThreads(CPU_NUM_THREADS)
            when (device) {
                Device.CPU -> {
                }
                Device.GPU -> {
                    gpuDelegate = GpuDelegate()
                    options.addDelegate(gpuDelegate)
                }
                Device.NNAPI -> options.setUseNNAPI(true)
            }
            return MoveNet(
                Interpreter(
                    FileUtil.loadMappedFile(
                        context,
                        if (modelType == ModelType.Lightning) LIGHTNING_FILENAME
                        else THUNDER_FILENAME
                    ), options
                ),
                gpuDelegate
            )
        }
```

### Relevant log output

```shell
java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Following operations are not supported by GPU delegate:
    ARG_MAX: Operation is not supported.
    CAST: Not supported cast case
    CONCATENATION: OP is supported, but tensor type isn't matched!
    FLOOR_DIV: OP is supported, but tensor type isn't matched!
    GATHER_ND: Operation is not supported.
    MUL: OP is supported, but tensor type isn't matched!
    PACK: OP is supported, but tensor type isn't matched!
    RESHAPE: OP is supported, but tensor type isn't matched!
    SUB: OP
```
</details>

**Comment by 8700nd** [comment]
This is using Interpreter API. I tried the Object dection demo which uses Task API and Baseoptions and such. It worked on the same device Pixel 4 Android 12. However I don't think Task API has pose estimation or movenet support.
https://www.tensorflow.org/lite/inference_with_metadata/task_library/overview

**Comment by mohantym** [comment]
Hi @8700nd !
Thanks for sharing your observations on android 12 w.r.to Movenet (lightning model) and GPU delegates.

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by madhavarora2002** [comment]
Hi, any update on this!

**Comment by 8700nd** [comment]
Hello all, I have found the solution to fix it. [https://issuetracker.google.com/issues/183419289](https://issuetracker.google.com/issues/183419289)

Add the following in AndroidManifest.
```
<uses-native-library
  android:name="libOpenCL-pixel.so"
  android:required="false"/>
```

Looks like it's because since Android 12, we need to explicitly state the non-NDK library  
> Non-NDK native shared libraries that are provided by silicon vendors or device manufacturers are not accessible by default if the app is targeting Android 12 (API level 31) or higher. The libraries are accessible only when they are explicitly requested using the <uses-native-library> tag.
[uses-native-library](https://developer.android.com/guide/topics/manifest/uses-native-library-element)

I'm not sure if there is other smarter way to do it instead of manually list out all the native libraries for each manufacturer or silicon vendor.

**Comment by madhavarora2002** [comment]
hey @8700nd , you're a lifesaver!

1. when you said **"manually list out all the native libraries for each manufacturer or silicon vendor"** 
What were you referring to? Do we just add the snippet attached by you in the AndroidManifest or do we change the "pixel.so" specifically for each manufacturer.

2. What's the on device fps you're getting with movenet now!!

**Comment by 8700nd** [comment]
Hello @madhavarora2002, 
1. I think we might need to add them all to AndroidManifest. What I was saying is it's very hard to manually find out what customized libs each manufacturers use and make our app support them
2. Currently I get with Pixel 4 Snapdragon 855
lightning fp16 CPU: 25~ GPU: 30+
thunder int8 CPU: 15~ GPU: 20~ NNAPI: 20~

**Comment by 8700nd** [comment]
@sachinprasadhs I am not sure if this is a generic walkaround. But it works on my specific device.

**Comment by pkgoogle** [comment]
Hi @8700nd, do you have any open items regarding this issue?

**Comment by 8700nd** [comment]
No. I think it can be closed
