### ISSUE TITLE
Feature request: before throwing OutOfRangeError, dequeue the rest samples from a queue

### ISSUE THREAD

**Issue by wangchuan** [tensorflow/tensorflow#5863]
When using a FIFOQueue as the input for a pipeline, we often encounter the case that `epoch_size % batch_size == M` where `M != 0`. It will lead the following issue:

if we would like to evaluate our model with the entire validation dataset, we cannot test the last `M` samples before getting the exception `OutOfRangeError` if we set `num_epoches` to 1. Even if we set `num_epoches` to `None` to avoid `OutOfRangeError`, we cannot exactly get the result because of the indivisibility issue.

So what I can think of is, we need a feature like this:
1) if `num_epoches` is set to None, we need to dequeue the rest M samples from the queue before every epoch is finished. For example, a dataset's size is 10, saying they are `[a,b,c,d,e,f,g,h,i,j]`, and `batch_size` is 3, the size of dequeued samples would be `[a,b,c], [d,e,f], [g,h,i], [j], [a,b,c], ...`;
2) if `num_epoches` is set to 1, we need to dequeue the rest M samples from the queue before throwing `OutOfRangeError`.For the above example, the result would be `[a,b,c], [d,e,f], [g,h,i], [j], OutOfRangeError`.

**Comment by prb12** [comment]
@mrry I'm not sure how `DequeueMany` and epochs are supposed to interact with `FIFOQueues`.  Seems to me like changing semantics like this is likely to break a lot of other people's code?

**Comment by mrry** [comment]
This is what `FIFOQueue.dequeue_up_to(n)` does. The various wrapper functions for batching have an `allow_small_batch` optional argument that use this op internally.

**Comment by prb12** [comment]
@wangchuan Does this solve your problem?

**Comment by wangchuan** [comment]
I tried `allow_small_batch` option, it meets part of my requirement, i.e. if `num_epoches` is set to an integer, the last iteration will dequeue the rest samples before throwing OutOfRangeError. However, if `num_epoches` is set to None, I think the results would be `[a,b,c], [d,e,f], [g,h,i], [j,a,b], [c,d,e], ...` instead of my expecting `[a,b,c], [d,e,f], [g,h,i], [j], [a,b,c], ...`. Am I correct?

**Comment by mrry** [comment]
You're correct. The queue-based input pipelines (such as `tf.train.batch()` etc.) don't support any form of intermediate punctuation, so only the final batch will be smaller if the dataset size is not divisible by the batch size.

Can you explain your use case for having the intermediate smaller batch? As far as I can tell, the smaller batch isn't a reliable way of detecting the transition from one epoch to the next.

**Comment by mrry** [comment]
Closing this due to lack of response. I doubt we'll implement this in the current input pipeline scheme, which is currently being redesigned, but it would be great if you could still share your use case so that we can take it into account.
