### ISSUE TITLE
Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter.

### ISSUE THREAD

**Issue by rr191211** [tensorflow/tensorflow#58635]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

source

### Tensorflow Version

2.10

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 18.04

### Mobile device

arm64-v8a

### Python version

3.7

### Bazel version

5.3.0

### GCC/Compiler version

7.5

### Current Behaviour?

```shell
Got an error "Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select. Node number 83 (FlexErf) failed to prepare."
```

### Standalone code to reproduce the issue

```shell
Hi, I try to make inference with flex delegate supported tflite model in Android(arm64-v8a) using C++ language. 
I have build tensorflowlite_flex lib and TensorflowLite as below using bazel command on ubuntu system : 
'''
bazel build -c opt --cxxopt=--std=c++17 tensorflow/lite/delegates/flex:tensorflowlite_flex --config=monolithic --config=android_arm64 --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
bazel build -c opt --cxxopt=--std=c++17  //tensorflow/lite:tensorflowlite --config=android_arm64 --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
'''

I linked that two library using CMake on Android Studio(Windows 10). 
Sample CMake snippet:
'''
add_library(tensorflowlite SHARED IMPORTED)
set_target_properties( tensorflowlite PROPERTIES IMPORTED_LOCATION
                    "${CMAKE_CURRENT_SOURCE_DIR}/tflite_cpp/lib/arm64-v8a/libtensorflowlite.so")
add_library(tensorflowlite_flex SHARED IMPORTED)
set_target_properties( tensorflowlite_flex PROPERTIES IMPORTED_LOCATION
                        "${CMAKE_CURRENT_SOURCE_DIR}/tflite_cpp/lib/arm64-v8a/libtensorflowlite_flex.so")
target_link_libraries(
        privacy_cpp
        tensorflowlite
        -Wl,--no-as-needed # Need --no-as-needed to link tensorflowlite_flex
        tensorflowlite_flex
        android)
'''

But the error log shows "Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter." What am I doing wrong here? Thank you.
'''
AAsset *model_fp= AAssetManager_open(mgr, "torch_bert.tflite", AASSET_MODE_STREAMING );
size_t size = AAsset_getLength(model_fp);
char * buf = new char[size];
memmove(buf, AAsset_getBuffer(model_fp), size);
std::unique_ptr<tflite::FlatBufferModel> model = tflite::FlatBufferModel::BuildFromBuffer((const char*)buf, size);
tflite::ops::builtin::BuiltinOpResolver resolver;
tflite::InterpreterBuilder(*model, resolver)(&interpreter);
'''
```

### Relevant log output

_No response_</details>
<img width="908" alt="tflite_error" src="https://user-images.githubusercontent.com/105635332/203116570-e4b7a370-1f07-47c3-93c3-3cc47ec7db7b.png">

**Comment by tiruk007** [comment]
@rr191211 
Could you please add this following line before you convert the model:
 `converter.target_spec.supported_ops = [
                                                   tf.lite.OpsSet.TFLITE_BUILTINS,
                                                     tf.lite.OpsSet.SELECT_TF_OPS ]`
Please refer to the [Select TensorFlow operators](https://www.tensorflow.org/lite/guide/ops_select) and let us know if it helps.

Thank you!

**Comment by rr191211** [comment]
> @rr191211 Could you please add this following line before you convert the model: `converter.target_spec.supported_ops = [ tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS ]` Please refer to the [Select TensorFlow operators](https://www.tensorflow.org/lite/guide/ops_select) and let us know if it helps.
> 
> Thank you!

Thank you for your replay. Yes, I added ”tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS“ when I convert tflite model, but still doesnt work. I am confused  do I need  to ross-compile tensorflowlite_flex？Thanks.

  # tf-->tflite
    converter = tf.lite.TFLiteConverter.from_saved_model(MODEL_TF_PATH)
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
        tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
        ]
    tflite_model = converter.convert()

**Comment by rr191211** [comment]
I found a way to make it work  as per this https://github.com/tensorflow/tensorflow/issues/57033.

**Comment by Beyramayadi** [comment]
> I found a way to make it work as per this #57033.

Having the same error here , and i don't quite understand how that solved the issue ...
