### ISSUE TITLE
tf.io.gfile.rename cause UnicodeError on non-English Windows

### ISSUE THREAD

**Issue by E-train-Liu** [tensorflow/tensorflow#58641]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tensorflow-2.9.1

### Custom Code

No

### OS Platform and Distribution

Windows 10 Family Chinese

### Python version

3.10.6 (conda)

### Current Behaviour?

The problem is first caused by the rename issue at https://github.com/tensorflow/tensorflow/issues/45980

Even when this rename error happen, it should produce 

```
tensorflow.python.framework.errors_impl.UnknownError: Failed to rename: <src> <tar> : Access is denied.
; Input/output error`
```

However, when the language of Windows is set to be non-English language, like Chinese, it cause `UnicodeError` like

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 143: invalid start byte
```

I guess the reason is that, the `"Access is denied"` is actually the error message formatted by Win32 `FormatError()` (https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-formatmessage). When `dwLanguageId` is set to be something like `MAKELANGID(NEUTRAL, SUBLANG_DEFAULT)`, it will produce a Chinese encoding error message `"拒绝访问"` in `cp936` (`gbk`) encoding when the system code page is `936` (Simplified Chinese with `gbk` encoding). When you want to decode it as python string using `utf-8` encoding, it cause this problem. 

Note `"拒绝访问"` in `gbk` is `"\xbe\xdc\xbe\xf8\xb7\xc3\xce\xca"`.

### Standalone code to reproduce the issue

Just follow the official tutorial at https://www.tensorflow.org/tutorials/images/data_augmentation

```
(train_ds, val_ds, test_ds), metadata = tfds.load(
    'tf_flowers',
    split=['train[:80%]', 'train[80%:90%]', 'train[90%:]'],
    with_info=True,
    as_supervised=True,
)
```

### Relevant log output

```
WARNING:tensorflow:From <conda_env_path>\lib\site-packages\tensorflow_datasets\core\file_format_adapter.py:209: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.
Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`

---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
Cell In [2], line 3
      1 # Load Data
----> 3 (train_ds, val_ds, test_ds), metadata = tfds.load(
      4     'tf_flowers',
      5     split = ['train[:80%]', 'train[80%:90%]', 'train[90%:]'],
      6     with_info = True,
      7     as_supervised = True,
      8 )

File <conda_env_path>\lib\site-packages\tensorflow_datasets\core\api_utils.py:52, in disallow_positional_args.<locals>.disallow_positional_args_dec(fn, instance, args, kwargs)
     50 _check_no_positional(fn, args, ismethod, allowed=allowed)
     51 _check_required(fn, kwargs)
---> 52 return fn(*args, **kwargs)

File <conda_env_path>\lib\site-packages\tensorflow_datasets\core\registered.py:300, in load(name, split, data_dir, batch_size, in_memory, shuffle_files, download, as_supervised, decoders, with_info, builder_kwargs, download_and_prepare_kwargs, as_dataset_kwargs, try_gcs)
    298 if download:
    299   download_and_prepare_kwargs = download_and_prepare_kwargs or {}
--> 300   dbuilder.download_and_prepare(**download_and_prepare_kwargs)
    302 if as_dataset_kwargs is None:
    303   as_dataset_kwargs = {}

File <conda_env_path>\lib\site-packages\tensorflow_datasets\core\api_utils.py:52, in disallow_positional_args.<locals>.disallow_positional_args_dec(fn, instance, args, kwargs)
     50 _check_no_positional(fn, args, ismethod, allowed=allowed)
     51 _check_required(fn, kwargs)
---> 52 return fn(*args, **kwargs)

File <conda_env_path>\lib\site-packages\tensorflow_datasets\core\dataset_builder.py:281, in DatasetBuilder.download_and_prepare(self, download_dir, download_config)
    278 self._log_download_bytes()
    280 # Create a tmp dir and rename to self._data_dir on successful exit.
--> 281 with file_format_adapter.incomplete_dir(self._data_dir) as tmp_data_dir:
    282   # Temporarily assign _data_dir to tmp_data_dir to avoid having to forward
    283   # it to every sub function.
    284   with utils.temporary_assignment(self, "_data_dir", tmp_data_dir):
    285     self._download_and_prepare(
    286         dl_manager=dl_manager,
    287         download_config=download_config)

File <conda_env_path>\lib\contextlib.py:142, in _GeneratorContextManager.__exit__(self, typ, value, traceback)
    140 if typ is None:
    141     try:
--> 142         next(self.gen)
    143     except StopIteration:
    144         return False

File <conda_env_path>\lib\site-packages\tensorflow_datasets\core\file_format_adapter.py:200, in incomplete_dir(dirname)
    198 try:
    199   yield tmp_dir
--> 200   tf.io.gfile.rename(tmp_dir, dirname)
    201 finally:
    202   if tf.io.gfile.exists(tmp_dir):

File <conda_env_path>\lib\site-packages\tensorflow\python\lib\io\file_io.py:620, in rename_v2(src, dst, overwrite)
    607 @tf_export("io.gfile.rename")
    608 def rename_v2(src, dst, overwrite=False):
    609   """Rename or move a file / directory.
    610 
    611   Args:
   (...)
    618     errors.OpError: If the operation fails.
    619   """
--> 620   _pywrap_file_io.RenameFile(
    621       compat.path_to_bytes(src), compat.path_to_bytes(dst), overwrite)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbe in position 143: invalid start byte
```
</details>

**Comment by E-train-Liu** [comment]
Update: Do not need to worry about the rename error. It is caused by a very old `tensorflow-datasets` version. After updating the `1.2.0` version from conda to `4.7.0` version from pip, the rename error disappears.

Now we only need to solve the encoding error. Many other file errors can reproduce it. Like, try to rename a non-existing file.

**Comment by tilakrayal** [comment]
@E-train-Liu,
Could you please check if tfds-nightly works for you and also please try this code **pip install tensorflow-datasets==4.7.0** for the latest tfds. 

Could you please raise this issue on the TensorFlow Datasets repository as well?
https://github.com/tensorflow/datasets/issues

Thank you!

**Comment by E-train-Liu** [comment]
I am sorry for misleading. **I am reporting for the encoding error instead of the rename error.**

That is, when there is some filesystem error on windows (including coping a non-existing file or being denied to rename a file), instead of reporting the error normally, it will raise an `UnicodeError` (which may be caused by the encoding mismatch).

For example

```python
tensorflow.io.gfile.copy("non_exist_file", "non_exist_file_2")
```
On `en-US` Windows system (default code page: `1252`), it report the error as expected

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
tensorflow.python.framework.errors_impl.UnknownError: Failed to copy:  non_exist_file :  No such file or directory.
; `Input/output error`
```

On `zh-CN` Windows system (default code page `936`), should work as above. Or if follow the Windows locale, it should work like

 ```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
tensorflow.python.framework.errors_impl.UnknownError: Failed to copy:  non_exist_file :  系统找不到指定的文件。
; `Input/output error`
```

However, it now produce

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda3\envs\sci\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 579, in copy_v2
    _pywrap_file_io.CopyFile(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 58: invalid continuation byte
```

By the way, as my first P.S., I switched to `tensorflow-dataset` `4.7.0`, and the rename error is fixed. But it is not my main content of this issue. Again, sorry for misunderstanding.

**Comment by SuryanarayanaY** [comment]
Hi @E-train-Liu ,
Apologies for delayed response.From error log I see that error originated from the code `tfds.load()`

```
----> 3 (train_ds, val_ds, test_ds), metadata = tfds.load(
      4     'tf_flowers',
      5     split = ['train[:80%]', 'train[80%:90%]', 'train[90%:]'],
      6     with_info = True,
      7     as_supervised = True,
      8 )
```
It seems the error is generated from trying to decode the images. Could you please add the argument 
`tfds.load(decoders={  'image': tfds.decode.SkipDecoding() }) ` and let us know if it works for your case.
