### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'ndim'

### ISSUE THREAD

**Issue by AntoineChauviere** [tensorflow/tensorflow#58644]
Hello,

I'm doing data augmentation on tensorflow. With tf.image it works, but when I add code with tf.keras.preprocessing I have this error:

AttributeError: 'Tensor' object has no attribute 'ndim'

Here is my code :
```
def process_single_sample_train(img_path, label):

    # 1. Read image
    img = tf.io.read_file(img_path)

    # 2. Decode and convert to grayscale
    img = tf.io.decode_png(img, channels=3) # channels = 1 for grayscale

    # 3. Convert to float32 in [0, 1] range
    img = tf.image.convert_image_dtype(img, tf.float32)

    # 4. Resize to the desired size
    img = tf.image.resize(img, [32, 128])
    
    # 5. Augment
    rand_ = tf.random.uniform(shape=(), minval=0, maxval=1)
    if rand_ < 0.8:
        img = tf.image.random_contrast(img, lower=0.7, upper=1)
        
        ## THIS LINE CAUSES THE BUG
        img = tf.convert_to_tensor(tf.keras.preprocessing.image.random_rotation(img, rg=5))
        
    return {"image": img, "label": label}
```
Bug when I run this : 
```
train_dataset = (
    train_dataset.map(
        process_single_sample_train, num_parallel_calls=tf.data.experimental.AUTOTUNE
    )
    .batch(batch_size)
    .prefetch(buffer_size=tf.data.experimental.AUTOTUNE)
)
```

**Comment by pavankumarsai18** [comment]
Hi,

```
## THIS LINE CAUSES THE BUG
        img = tf.convert_to_tensor(tf.keras.preprocessing.image.random_rotation(img, rg=5))
```

The documentation [page](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/random_rotation) tells that `tf.keras.preprocessing.image.random_rotation` is depricated and does not work on tensors. So it is better to use `tf.keras.layers.RandomRotation` instead ([documentation](https://www.tensorflow.org/api_docs/python/tf/keras/layers/RandomRotation), [usage](https://www.tensorflow.org/guide/keras/preprocessing_layers)).

Hope this helps.

**Comment by AntoineChauviere** [comment]
Ok thank you @pavankumarsai18 . This must be used in the network or else it can be used in my process_single_sample_train function?

**Comment by tiruk007** [comment]
@AntoineChauviere 
 Can  you  please try `img = tf.convert_to_tensor(tf.keras.layers.RandomRotation(img, rg=5))` instead of `img = tf.convert_to_tensor(tf.keras.preprocessing.image.random_rotation(img, rg=5))`, please find gist [here](https://colab.research.google.com/gist/tiruk007/dee0b99342ffe7b82808be557f7cc9a7/untitled30.ipynb) for reference and let us know if it helps.

Thank you !

**Comment by AntoineChauviere** [comment]
@pavankumarsai18  I think we have to instantiate the layer like this and apply on an image, for example:

```
layer_rotate = tf.keras.layers.RandomRotation(factor=(-0.3, 0.2))
image_rotate = layer_rotate(image)
```

But I don't see any difference, en faite : 

 image == image_rotate

Can you help me ?

**Comment by pavankumarsai18** [comment]
Hi, 

Following the documentation, we need to augment the data by random rotation ...

```
data_augmentation = tf.keras.Sequential([tf.keras.layers.RandomRotation(factor=(-0.3, 0.2))])
img_rotated       = data_augmentation(img)
```

The good thing about using `tf.keras.Sequential` is that you can use multiple effects, and also batch process. As mentioned in [documentation](https://www.tensorflow.org/guide/keras/preprocessing_layers), we can do random flips, random zoom, and random rotations. You can define all these modifications in `data_augmentation` and batch process `train_dataset`, or if you want to stick with just one image at a time you can follow the code I mentioned earlier.

```
data_augmentation = keras.Sequential(
    [
        layers.RandomFlip("horizontal"),
        layers.RandomRotation(0.1),
        layers.RandomZoom(0.1),
    ]
)
...
...
train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
train_dataset = train_dataset.batch(16).map(lambda x, y: (data_augmentation(x), y))
```

Hope this helps!!!!

**Comment by AntoineChauviere** [comment]
Ok it works perfectly, thank you very much @pavankumarsai18 !

**Comment by tiruk007** [comment]
@AntoineChauviere 
Can you please close the issue if it is resolved.

Thank you!
