### ISSUE TITLE
Inconsistency in connection with setting both clipnorm and global_clipnorm attibute for an optimizer

### ISSUE THREAD

**Issue by gpetho** [tensorflow/tensorflow#58655]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10.0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current Behaviour?

**Basic problem statement:** It is possible to set both the `clipnorm` and the `global_clipnorm` attributes for an optimizer. A model configured with this optimizer can be saved, but loading fails with a ValueError.

**Details:**

It is not possible to instantiate a Keras optimizer with both `clipnorm` and `global_clipnorm` kwargs set, since that produces a value error, e.g.

```shell
adam_opt = tf.keras.optimizers.Adam(learning_rate=0.001, clipnorm=1, global_clipnorm=0.5)

ValueError: Cannot accept both `clipnorm` and `global_clipnorm`. Received: `clipnorm`=1, `global_clipnorm`=0.5.
```
However, it is possible to first instantiate the optimizer with just one of the two settings, and then, likely by accident, set the other via the optimizer's corresponding attribute:
```
adam_opt = tf.keras.optimizers.Adam(learning_rate=0.001, clipnorm=1)
adam_opt.global_clipnorm = 0.5
```

This does not raise any exceptions. An optimizer with both `clipnorm` and `global_clipnorm` set can be set as the optimizer for a Keras model, and the model trains with this optimizer without any problems. The Keras model can also be **saved** along with this optimizer without any warning or error raised. However, when attempting to **load** a Keras model with such an optimizer, the same ValueError as mentioned above is raised as the saved optimizer is instantiated.

One possible solution would be to have the already existing `@clipnorm.setter` method check whether `self._global_clipnorm` is already set and delete the latter setting if it is. Same for `@global_clipnorm.setter` and checking `self._clipnorm`.

However, I believe that the best solution would be to replace this error with a warning. I don't quite understand what the point of raising this exception is in the first place, and why a similar exception is not raised when e.g. you try to assign a value to `clipvalue` when `clipnorm` is also set or vice versa. As far as I can tell, the only place these attributes are used is in `OptimizerV2._transform_gradients()`, which just makes the value of `self._clipnorm` override `self._clipvalue` and then `self._global_clipnorm` override both of these. So setting more than one of these seems to be harmless. It warrants a warning, but not an error.

As a matter of fact, it would be nice if the Keras documentation mentioned this overriding behavior explicitly. I mean, the way the documentation puts it is **technically** correct, but not terribly transparent: "If clipvalue (float) is set, the gradient of each weight is clipped to be no higher than this value. If clipnorm (float) is set, the gradient of each weight is individually clipped so that its norm is no higher than this value. If global_clipnorm (float) is set the gradient of all weights is clipped so that their global norm is no higher than this value."

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

adam_opt = tf.keras.optimizers.Adam(learning_rate=0.001, clipnorm=1)
adam_opt.global_clipnorm = 0.5

def create_model():
  return tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
  ])

model = create_model()
model.compile(optimizer=adam_opt, loss='sparse_categorical_crossentropy')

print(f"{model.optimizer.clipnorm=}, {model.optimizer.global_clipnorm=}")
model.save('mnist_model.tf')

saved_model = tf.keras.models.load_model('mnist_model.tf')
```

### Relevant log output

```shell
model.optimizer.clipnorm=1, model.optimizer.global_clipnorm=0.5
INFO:tensorflow:Assets written to: mnist_model.tf/assets

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [34], in <cell line: 24>()
     21 print(f"{model.optimizer.clipnorm=}, {model.optimizer.global_clipnorm=}")
     22 model.save('mnist_model.tf')
---> 24 saved_model = tf.keras.models.load_model('mnist_model.tf')

File ~/anaconda3/envs/tf2/lib/python3.10/site-packages/keras/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File ~/anaconda3/envs/tf2/lib/python3.10/site-packages/keras/optimizers/optimizer_v2/optimizer_v2.py:427, in OptimizerV2.__init__(self, name, gradient_aggregator, gradient_transformers, **kwargs)
    425 self.global_clipnorm = kwargs.pop("global_clipnorm", None)
    426 if self.clipnorm is not None and self.global_clipnorm is not None:
--> 427     raise ValueError(
    428         "Cannot accept both `clipnorm` and `global_clipnorm`. "
    429         "Received: `clipnorm`={}, `global_clipnorm`={}.".format(
    430             self.clipnorm, self.global_clipnorm
    431         )
    432     )
    433 self.clipvalue = kwargs.pop("clipvalue", None)

ValueError: Cannot accept both `clipnorm` and `global_clipnorm`. Received: `clipnorm`=1, `global_clipnorm`=0.5.
```
</details>

**Comment by tilakrayal** [comment]
@gpetho,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by gpetho** [comment]
Sorry about this, thank you, moved to https://github.com/keras-team/keras/issues/17278
