### ISSUE TITLE
Is there a way to use a tflite-runtime version higher than 2.5.0 on an armv7 development board

### ISSUE THREAD

**Issue by LXF-DX3906** [tensorflow/tensorflow#58651]
### 1. System information

- Linux Ubuntu 18.04
- armv7 board
- python3.6

### 2. question description

I trained a model on my linux server **(ubuntu18.04，Intel(R) Xeon(R) W-2145 CPU)** and exported it to tflite mode, and the model on the server **(tflite-runtime=2.10.0)** works fine.

Now I want to run the model on an **armv7** development board of zynq7000. The operating system running on my board version is ubuntu18.04, and **python3.6** and **tflite-runtime=2.5.0** is installed (2.5.0 seems is the highest version I can get on armv7), but when I run `interpreter = tflite.Interpreter(model_path=my_model)`, it throws `Segmentation fault (core dumped)` error.

After my test, if I downgrade the tflite-runtime on my linux server to version 2.5.0, the same error will be thrown. So I think the reason for the error may be that the version of tflite-runtime is too low.

But I can't get a higher version of tflite-runtime on armv7 board, does anyone know a solution please?

**Comment by mohantym** [comment]
Hi @LXF-DX3906 !
Just quick observation, you are using python 3.6 which is not supported (Minimum is python 3.7 , max  version Python 3.10 as of now) .

You can build a custom tflite-runtime by cross compiliing  with different tool chain through cmake . 
[Ref](https://www.tensorflow.org/lite/guide/build_cmake)

Alternatively, you can convert the model to a character buffer using xxd converter then do the inference in C++ by including dependent libraries.

 Below reference includes complete end to end deployment starting from training and evaluating to inference part(15 steps)
[Reference.](https://www.tensorflow.org/lite/microcontrollers/get_started_low_level#train_a_model).
Thank you!

**Comment by mohantym** [comment]
Ok @LXF-DX3906 !
Thanks for the update.
Please  post on [TF-Forum](https://discuss.tensorflow.org/tag/tflite) for further assistance.

Thank you!
