### ISSUE TITLE
ios armv7 compile fail (cmake)

### ISSUE THREAD

**Issue by mengran1234** [tensorflow/tensorflow#58654]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.10 or 2.11

### Custom Code

No

### OS Platform and Distribution

ios

### Mobile device

ios

### Current Behaviour?

```shell
A bug happen
I compile ios armv7，can not compile ok.
armv7/xnnpack/src/qc8-dwconv/up8x3-minmax-fp32-aarch32-neonv8-mla8-cortex-a35.S:118:9: error: instruction requires: armv8
VCVTN.S32.F32 q12, q12
I find many  error like this.
Thank you very much!

In addition, xnnpack code has following part，
 SET_PROPERTY(SOURCE ${AARCH32_ASM_MICROKERNEL_SRCS} APPEND_STRING PROPERTY COMPILE_FLAGS " -march=armv8.2-a+dotprod -mfpu=neon-fp-armv8 ")
```

### Standalone code to reproduce the issue

```shell
1
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @chenliang110 !
Just quick observation, you seem to be using arm v8 tool chain in armv7.

` -march=armv8.2-a+dotprod -mfpu=neon-fp-armv8 
`

Could you test with armv7 tool chain as mentioned in this [document](https://www.tensorflow.org/lite/guide/build_cmake_arm#run_cmake_2) .

Thank you!

**Comment by chenliang110** [comment]
-march=armv8.2-a+dotprod -mfpu=neon-fp-armv8
these option is set in xnnpack code.

https://github.com/google/XNNPACK/issues/3905#event-7879829849
this reply is 32-bit iOS is no longer supported.

**Comment by pjpratik** [comment]
Hi @mengran1234 

As this [comment](https://github.com/google/XNNPACK/issues/3905#issuecomment-1325501778) suggests, 32-bit iOS is no longer supported. please find the supported architectures [here](https://github.com/google/XNNPACK#supported-architectures).

Can you try with `DTFLITE_ENABLE_XNNPACK=OFF` which is enabled by defult and compile for armv7 on ios ?

Thanks.

**Comment by sachinprasadhs** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
