### ISSUE TITLE
Tensorflow Lite Swift iOS: Cocoapods Integration Broken - No such module 'TensorFlowLiteC'

### ISSUE THREAD

**Issue by yusufoos** [tensorflow/tensorflow#58661]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

Latest from cocoapods

### Custom Code

No

### OS Platform and Distribution

XCode 13.2.1

### Current Behaviour?

```shell
Take the image classification sample app for example:
 https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/ios/Podfile

Replace pod 'TensorFlowLiteTaskVision' with 'TensorFlowLiteSwift'

pod install.

Build for any ios device or try to archive the app.

Result: Compiler Error - No such module 'TensorFlowLiteC'

Expected Result: No Compiler Error.

This issue seems to have been introduced when Tensorflow Lite was distributed via cocoapods using  .XCFramework, it used to work with .framework, you can pin to version "1.14.0" and it works as expected.
```

### Standalone code to reproduce the issue

```shell
platform :ios, '12.0'

target 'SampleApp' do
   use_frameworks!

  pod 'TensorFlowLiteSwift'
end
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @yusufoos !
Just quick observation, Is your Tensorflow version 2.1 ? It is pretty outdated.
You can use 
```
pod 'TensorFlowLiteSwift' : 2.10.0 
or 
pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly'
or 
pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML', 'Metal'] or 

```
@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by yusufoos** [comment]
I just used the latest pod as shown which I believe resolved to 2.10

**Comment by yusufoos** [comment]
@mohantym @sachinprasadhs Gentle bump on this, and reminder this is not 2.1 it's for the latest 2.10.0

**Comment by yishuangP** [comment]
Hi sorry for the late reply, do you see this issue with the latest version v2.11.0?

**Comment by sachinprasadhs** [comment]
@yusufoos , Could you please test your results against `TesroFlowLite Swift` 2.11 version and let us know the outcome.
For details visit here https://cocoapods.org/pods/TensorFlowLiteSwift

**Comment by yishuangP** [comment]
Or can you try the nightly build? I just tried `0.0.1-nightly.20230405` and it is working fine.

**Comment by sachinprasadhs** [comment]
@yusufoos , It is not suggested to change the pod from `'TensorFlowLiteTaskVision'` to `'TensorFlowLiteSwift'`.
`TensorFlowLiteTaskVision`  will be compatible with Swift, whereas swift is more related to runtime.

Please find the below tutorial for reference https://www.tensorflow.org/lite/inference_with_metadata/task_library/image_classifier#run_inference_in_ios
