### ISSUE TITLE
Feature request (TensorFlow Lite): Implement mechanism to load Flex ops in C for Android

### ISSUE THREAD

**Issue by andreasavio** [tensorflow/tensorflow#58669]
### System information

-   **Have I written custom code**: no
-   **OS Platform and Distribution**: macOS Monterey 12.6
-   **TensorFlow installed from**: source
-   **TensorFlow version**: 2.10.0
-   **Python version**: 3.10.8
-   **Bazel version**: 5.1.1
-   **GCC/Compiler version**: Apple clang 14.0.0 (clang-1400.0.29.202)
-   **CUDA/cuDNN version**: Not using CUDA
-   **GPU model and memory**: Not using GPU acceleration
-   **Exact command to reproduce**: Feature request, no 

### Describe the problem

This is a feature request.

In TensorFlow Lite 2.7 and higher, if a model contains Flex ops you must go through Java to load the Flex library (see [NativeInterpreterWrapper.java](https://github.com/tensorflow/tensorflow/blob/3c53121ab319ce3646d3cb5b0152e78ef02c3925/tensorflow/lite/java/src/main/java/org/tensorflow/lite/NativeInterpreterWrapper.java#L542) and [FlexDelegate.java](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/flex/java/src/main/java/org/tensorflow/lite/flex/FlexDelegate.java)).

We develop a cross-platform app where most of the ML inference logic runs in a separate C library. We test that library separately from the rest of the app using GTest, without going through the Android runtime. For our purposes, it would be much more convenient if we could load the Flex library directly in C.

As a tentative implementation, we could move the logic in `NativeInterpreterWrapper.java` to C, so that we could automatically load Flex ops when creating models from the C API with `TfLiteModelCreate`. The existing Java classes could be kept as shallow wrappers to the underlying C implementation. Java and C entry points could be toggled at build time through a flag.

Is this something that you would consider implementing, and, if not, would you accept PRs that go in that direction?

**Comment by mohantym** [comment]
Hi @andreasavio !

You can build the flex delegate in C using Bazel and load it with interpreter  options if necessary. ( but it takes the select ops runtime during inference if already built into bazel bin folder).

[Ref](https://www.tensorflow.org/lite/guide/ops_select#cc)

Thank you!
