### ISSUE TITLE
Feature request (TensorFlow Lite): Strip unneeded kernels when building Flex ops library on platforms other than Android

### ISSUE THREAD

**Issue by andreasavio** [tensorflow/tensorflow#58670]
### System information

-   **Have I written custom code**: no
-   **OS Platform and Distribution**: macOS Monterey 12.6
-   **TensorFlow installed from**: source
-   **TensorFlow version**: 2.10.0
-   **Python version**: 3.10.8
-   **Bazel version**: 5.1.1
-   **GCC/Compiler version**: Apple clang 14.0.0 (clang-1400.0.29.202)
-   **CUDA/cuDNN version**: Not using CUDA
-   **GPU model and memory**: Not using GPU acceleration
-   **Exact command to reproduce**: Feature request, no 

### Describe the problem

This is a feature request.

TensorFlow Lite 2.10 provides a [tool](https://www.tensorflow.org/lite/guide/ops_select#building_the_android_aar) that strips unneeded kernels when building the Flex library, but this is for Android only. On other platforms, the whole set of kernels gets built in, and the flex binary ends up being hundreds of MBs in size. Would you consider implementing a similar tool for other platforms, and, if not, would you accept PRs for it?

**Comment by mohantym** [comment]
Hi @andreasavio !
Feel free to raise a PR from your side for review.

@sachinprasadhs !
Could you look at this feature request.

Thank you!

**Comment by terryheo** [comment]
FYI, we also have a tool for iOS.
https://www.tensorflow.org/lite/guide/build_ios#selectively_build_tflite_frameworks

Which target platform are you considering?
