### ISSUE TITLE
Crashes with exit code 135 in model.fit

### ISSUE THREAD

**Issue by plooney** [tensorflow/tensorflow#58673]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.11

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 22.02

### Python version

Docker image

### Bazel version

Docker image

### GCC/Compiler version

Docker image

### CUDA/cuDNN version

Docker image

### Current Behaviour?

```shell
Crashes in model.fit with no error message but exit code 135

Works fine in 2.9
```

### Standalone code to reproduce the issue

```shell
Calling model.fit() causes a crash
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@plooney 
Can you please give a reproducible code snippet or colab gist to replicate the issue reported here.

Thank you !

**Comment by ethanbonin** [comment]
@plooney -- Did you ever figure this out? I use 1 or 2 GPUs it works fine, but when I use more than 2 it gives an exit code 135 at the same exact spot every single time. 

It crashses at on the first epoch 

```bash
gradients/Reshape_grad/Shape:
gradients/Reshape_1_grad/Shape:
gradients/Reshape_2_grad/Shape:
gradients/Reshape_3_grad/Shape:
gradients/Reshape_4_grad/Shape:
gradients/Reshape_5_grad/Shape:
gradients/Reshape_6_grad/Shape:
```
