### ISSUE TITLE
Tensorflow Lite iOS Interpreter production logs

### ISSUE THREAD

**Issue by lukas-koblmueller** [tensorflow/tensorflow#58683]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

iOS

### Mobile device

iOS

### Current Behaviour?

```shell
The log outputs of the Interpreter cannot be disabled for production use, but we would need that.
See: https://github.com/tensorflow/tensorflow/blob/bb5ff1b22f5d4d6bf937dcd71f8b710064eadce6/tensorflow/lite/core/interpreter.cc#L97

Would be nice if you could introduce another option for the Interpreter where you could set log outputs enabled/disabled or even with LogLevels.
```

### Standalone code to reproduce the issue

```shell
Interpreter(modelPath: path, options: options)
```

### Relevant log output

```shell
Initialized TensorFlow Lite runtime.
```
</details>

**Comment by sachinprasadhs** [comment]
The log output for the Version has been completed in the PR https://github.com/tensorflow/tensorflow/commit/8033edfef8bcd90b025fb66c488164d2b608c4a9 to remove the version dependency, with this change it automatically selects the version instead of `schema_fbs_version` which is deprecated.

**Comment by lukas-koblmueller** [comment]
but will this also affect the Log output from the Interpreter here:
https://github.com/tensorflow/tensorflow/blob/bb5ff1b22f5d4d6bf937dcd71f8b710064eadce6/tensorflow/lite/core/interpreter.cc#L97

**Comment by pjpratik** [comment]
Hi @lukas-koblmueller 

From 2.11, the TfLite includes the TFLite logger options which can be used to set the logging severity levels.

https://github.com/tensorflow/tensorflow/blob/r2.11/tensorflow/lite/logger.h

Does this help in your use case?

thanks.
