### ISSUE TITLE
Instantiating std::complex as static_cast<int16_t>(std::abs<int32_t> in TfLiteStatus AbsInt16EvalImpl() is unspecified

### ISSUE THREAD

**Issue by BitLoose** [tensorflow/tensorflow#58688]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8

### Custom Code

No

### OS Platform and Distribution

Window 10

### Python version

3.9

### GCC/Compiler version

Visual Studio 2022 Nov update

### GPU model and memory

nVidia

### Current Behaviour?

```shell
This is the compiler warning after the latest VS 2022 C++ upgrade:
error C4996: 'std::complex<int32_t>::complex': warning STL4037: The effect of instantiating the template std::complex for any type other than float, double, or long double is unspecified. You can define _SILENCE_NONFLOATING_COMPLEX_DEPRECATION_WARNING to suppress this warning.

Seems that the complex abs function may not give a guarantee for operation with int32_t.
```

### Standalone code to reproduce the issue

```shell
Just compile Tensor flow in VS with the latest updates and standard settings.
```

### Relevant log output

```shell
third_party\tensorflow\tensorflow\lite\kernels\elementwise.cc(169,57): error C4996: 'std::complex<int32_t>::complex': warning STL4037: The effect of instantiating the template std::complex for any type other than float, double, or long double is unspecified. You can define _SILENCE_NONFLOATING_COMPLEX_DEPRECATION_WARNING to suppress this warning.
```
</details>

**Comment by mohantym** [comment]
Hi @BitLoose !
Would it be possible to share the commands too.
Thank you!

**Comment by BitLoose** [comment]
Hi, I looked into it and seems that the latest VC compiler doesn't like static casts for the "complex" functions like abs to anything but float and double.I just changed the casts to standard C (int16_t) to remove the error.On 27 Nov 2022 16:59, Manas Mohanty ***@***.***> wrote:
Hi @BitLoose !
Would it be possible to share the commands too.
Thank you!

**Comment by pkgoogle** [comment]
Hi, @BitLoose 

It seems the offending code is no longer there, can you try again with the latest version?
