### ISSUE TITLE
Protobuf Package Dependency between Google ads and tensorflow

### ISSUE THREAD

**Issue by PavloPanchyshak** [tensorflow/tensorflow#58687]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

2.11

### Custom Code

Yes

### Python version

3.9

### Current Behaviour?

```shell
Hello, would you be so kind to fix TensorFlow 2.11.0 depends on protobuf<3.20 and >=3.9.2 to be more relevant to the google ads package which uses protobuf==4.21.5
```

### Standalone code to reproduce the issue

```shell
protobuf==4.21.5
google-ads==19.0.0
tensorflow==2.11.0
google-api-core==2.10.1
googleapis-common-protos==1.56.4
```

### Relevant log output

```shell
The conflict is caused by:
    The user requested protobuf==4.21.5
    google-ads 19.0.0 depends on protobuf>=4.21.5
    google-api-core 2.10.1 depends on protobuf<5.0.0dev and >=3.20.1
    googleapis-common-protos 1.56.4 depends on protobuf<5.0.0dev and >=3.15.0
    tensorflow 2.11.0 depends on protobuf<3.20 and >=3.9.2
```
</details>

**Comment by learning-to-play** [comment]
Adding @vam-google who is driving TensorFlow protobuf upgrade.

**Comment by alevalentz** [comment]
Hello everyone! Is there any updates on this issue? I see that tensorboard in trying to update their protobuf dependency as well https://github.com/tensorflow/tensorboard/pull/6098

**Comment by mihaimaruseac** [comment]
Same status as before. @vam-google and @learning-to-play can provide more context if there's any

**Comment by vam-google** [comment]
We are actively working on allowing protobuf >= 4 for tensorflow. It seems to be mostly working but there are few more things left (as cc_shared_library seems to be causing problems where we expected i to fix them). I'll provide an update early next week.

**Comment by mihaimaruseac** [comment]
Closing due to https://github.com/tensorflow/tensorflow/commit/84f40925e929d05e72ab9234e53c729224e3af38 Please reopen if that does not fix.
