### ISSUE TITLE
What is the real meaning of 6034766930529145842 in the exception information thrown by the tf.math.cumsum operator?

### ISSUE THREAD

**Issue by triumph-wangyuyang** [tensorflow/tensorflow#58696]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

TF 2.10

### Custom Code

Yes

### OS Platform and Distribution

windows 11

### Python version

3.8.15

### CUDA/cuDNN version

CUDA: 11.3       cuDNN cuDNN 8.6.0

### GPU model and memory

RTX3060

### Current Behaviour?

```shell
I deliberately use illegal parameters to test tf.math.cumsum, and set the parameter axis to an empty string to get exception information, but in the exception information, I am allowed=[DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, 6034766930529145842, DT_UINT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64]; attr=Tidx:type,default=DT_INT32,allowed=[DT_INT32, DT_INT64] Here, I see a string of 6034766930529145842, but this information does not give me any useful information, and then test API, you will not get this long number, so it is recommended to modify the real meaning of 6034766930529145842.
```

### Standalone code to reproduce the issue

```shell
from tensorflow import int32
    import tensorflow as tf
    with tf.device('/CPU'):
        x = tf.random.uniform([2, 4], minval=-256, maxval=257, dtype=tf.int32)
        out = tf.math.cumsum(x, axis="", exclusive=False, reverse=False)
```

### Relevant log output

```shell
tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'Tidx' of string is not in the list of allowed values: int32, int64; NodeDef: {{node Cumsum}}; Op<name=Cumsum; signature=x:T, axis:Tidx -> out:T; attr=exclusive:bool,default=false; attr=reverse:bool,default=false; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, 6034766930529145842, DT_UINT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64]; attr=Tidx:type,default=DT_INT32,allowed=[DT_INT32, DT_INT64]> [Op:Cumsum]
```
</details>

**Comment by tiruk007** [comment]
@sushreebarsa 
I was able to reproduce the issue on Colab using TF v2.11. Please find the  gist [here](https://colab.research.google.com/gist/tiruk007/9bf09f6466ba93b05f608f2f10a9346b/58696.ipynb) for reference.

Thank you!

**Comment by triumph-wangyuyang** [comment]
> @sushreebarsa I was able to reproduce the issue on Colab using TF v2.11. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/9bf09f6466ba93b05f608f2f10a9346b/58696.ipynb) for reference.
> 
> Thank you!

I found that many operators (tf.math.reduce_mean, tf.math.reduce_std, etc.) have this problem, and then using the same code, by comparing the results of Tensorflow2.11 and Tensorflow2.10 versions, I found that
`6034766930529145842` may mean `DT_INT8, DT_COMPLEX64, DT_INT64, DT_QINT8, DT_QUINT8, DT_QINT32, DT_BFLOAT16`.

**Comment by SuryanarayanaY** [comment]
I have cross checked the behaviour with nightly (2.12.0-dev20221213) version and i got different number `10440210506161272279 `in place of `6034766930529145842`.Please refer [gist](https://colab.research.google.com/gist/SuryanarayanaY/4872b9990864ef6ceaa0dd6e7cd7ced5/58696_nightly.ipynb#scrollTo=s6PrjZ1qzm3A) here.

@sachinprasadhs could you please look into issue.

Thanks!

**Comment by sachinprasadhs** [comment]
Initial debug details:
It should raise an error with the following allowed list here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/ops.pbtxt#L12046-L12113.
But it is skipping:
```
        type: DT_INT8
        type: DT_COMPLEX64
        type: DT_INT64
        type: DT_QINT8
        type: DT_QUINT8
        type: DT_QINT32
        type: DT_BFLOAT16 
```
and showing below list with random number included. 
`[DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, 6034766930529145842, DT_UINT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64]`

**Comment by cantonios** [comment]
To answer the question, it was a random fingerprint that we used internally to represent a bunch of types not listed, in order to reduce the length of the string.

It will now report all types.
