### ISSUE TITLE
tf.math.add runs successfully Documentation Unsupported type: uint16

### ISSUE THREAD

**Issue by triumph-wangyuyang** [tensorflow/tensorflow#58693]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

TF 2.10

### Custom Code

Yes

### OS Platform and Distribution

windows 11

### Python version

3.8.15

### CUDA/cuDNN version

CUDA: 11.3       cuDNN cuDNN 8.6.0

### GPU model and memory

RTX3060

### Current Behaviour?

```shell
According to the TensorFlow2.10 documentation, tf.math.add(x, y, name=None), the types of x and y must be A Tensor. types: bfloat16, half, float32, float64, uint8, int8, int16, int32, int64 , complex64, complex128, string.
But when the type of my x and y is input as uint16, I found that the program can run successfully, so I suggest that the document can be modified,or work on adding a type check on the input.
In order to prove that this is not an accidental behavior, I also tested tf.math.exp(x), the type of x needs to be bfloat16, half, float32, float64, complex64, complex128, if I enter int64, an exception will be thrown, indicating In the source code, there is a check on the parameter type.
```

### Standalone code to reproduce the issue

```shell
from tensorflow import int64
    from tensorflow import uint16
    import tensorflow as tf
    with tf.device('/CPU'):
        x = tf.saturate_cast(tf.random.uniform([1, 2, 1, 3], minval=0, maxval=257, dtype=tf.int64), dtype=tf.uint16)
        y = tf.saturate_cast(tf.random.uniform([2, 1, 3, 1], minval=0, maxval=257, dtype=tf.int64), dtype=tf.uint16)
        res = tf.math.add(x, y)
    print(res)
```

### Relevant log output

```shell
Test code result:
tf.Tensor(
  [[[[350 277 296]
   [259 186 205]
   [183 110 129]]

  [[376 204 403]
   [285 113 312]
   [209  37 236]]]


 [[[189 116 135]
   [244 171 190]
   [178 105 124]]

  [[215  43 242]
   [270  98 297]
   [204  32 231]]]], shape=(2, 2, 3, 3), dtype=uint16)
```
</details>

**Comment by triumph-wangyuyang** [comment]
tf.math.cumsum also has such a situation, the official type of the parameter x must be float32, float64, int64, int32, uint8, uint16, int16, int8, complex64, complex128, qint8, quint8, qint32, half, but uint32, etc. can run the code successfully.
code: 
          x = tf.cast(tf.random.uniform([2, 4], minval=0, maxval=2, dtype=tf.int32), dtype=tf.uint32)
          axis = 1
          results["res_cpu"] = tf.math.cumsum(x,axis=axis)

**Comment by triumph-wangyuyang** [comment]
tf.math.floor also has such a situation,  the official type of the parameter x must be  bfloat16, half, float32, float64, etc. can run the code successfully.

code: 
    import tensorflow as tf
    with tf.device('/CPU'):
        x = tf.random.uniform([6, 1], minval=-256, maxval=257, dtype=tf.float16)
        res = tf.floor(x)
    print(res)

**Comment by sanjail3** [comment]
I like to solve this bug  I am  new to open source can anyone guide me?

**Comment by tiruk007** [comment]
@triumph-wangyuyang 
There is internal PR created. Once the PR merged issue will close.

Thank you
