### ISSUE TITLE
The parameter indices in tf.gather are supported int16

### ISSUE THREAD

**Issue by triumph-wangyuyang** [tensorflow/tensorflow#58697]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

TF 2.10

### Custom Code

Yes

### OS Platform and Distribution

windows 11

### Python version

3.8.15

### CUDA/cuDNN version

CUDA: 11.3 cuDNN cuDNN 8.6.0

### GPU model and memory

RTX3060

### Current Behaviour?

```shell
tf.gather(params, indices, validate_indices=None, axis=None, batch_dims=0, name=None) The parameter type requirement for indices in the official document is Tensor, and then the type is int32, int64. For this situation, I deliberately use Unreasonable types are tested. When indices are set to 1.0, it is a float type, but the exception thrown says that this is not int16, int32, int64, which is one more int16 than the official document. Therefore, it is recommended to add int16 to the document. Go up or remove int16 from the source code.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

    with tf.device('/CPU'):
        params = tf.random.uniform([1024, 2], dtype=tf.float64)
        indices = 1.0
        out = tf.gather(params=params, indices=indices)
```

### Relevant log output

```shell
result:tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'Tindices' of float is not in the list of allowed values: int16, int32, int64; NodeDef: {{node GatherV2}}; Op<name=GatherV2; signature=params:Tparams, indices:Tindices, axis:Taxis -> output:Tparams; attr=batch_dims:int,default=0; attr=Tparams:type; attr=Tindices:type,allowed=[DT_INT16, DT_INT32, DT_INT64]; attr=Taxis:type,allowed=[DT_INT32, DT_INT64]> [Op:GatherV2]
```
</details>

**Comment by triumph-wangyuyang** [comment]
tf.gather_nd also has the same problem. The types of indices supported in the official documentation are int32, int64, but the exception thrown says int16, int32, int64 are supported.

code:

    import tensorflow as tf
    with tf.device('/CPU'):
        out = tf.gather_nd(
            batch_dims=1,
            indices=tf.constant([[1], [0]], dtype=tf.int8),
            params=[[['a0', 'b0'],
                     ['c0', 'd0']],
                    [['a1', 'b1'],
                     ['c1', 'd1']]]).numpy()
    print(out)

result:   tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'Tindices' of int8 is not in the list of allowed values: int16, int32, int64; NodeDef: {{node GatherNd}}; Op<name=GatherNd; signature=params:Tparams, indices:Tindices -> output:Tparams; attr=Tparams:type; attr=Tindices:type,allowed=[DT_INT16, DT_INT32, DT_INT64]> [Op:GatherNd]

**Comment by mohantym** [comment]
Hi @triumph-wangyuyang !

I think It is working as intended w.r.to documentation on [tf.gather ](https://www.tensorflow.org/api_docs/python/tf/gather)and [tf.gather_nd](https://www.tensorflow.org/api_docs/python/tf/gather_nd)
Considering float64 for tf.gather and int8 for Gather_nd would be a feature request.

@SuryanarayanaY  !
Could you look at this issue.

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @triumph-wangyuyang ,

Thanks for observing it. I have checked the op with dtype `tf.int16` as `indices` and it is not supported both in 2.9.2V and nightly(2.12.0-dev20221128).Attaching here the [gist](https://colab.research.google.com/gist/SuryanarayanaY/e109a9a324fb5882573582a4b7a25e73/58697-2-9-2-nightly.ipynb#scrollTo=uT8paYsCYbsS) for same.

I think the API seems mentioning correct arguments but we need to correct the error statement. I hope this is what you also meant.Please confirm. 

Also one more observation when i tested with `tf.int16` dtype as `indices` argument it is throwing error as below.

```
NotFoundError: Could not find device for node: {{node GatherV2}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT16, Tparams=DT_DOUBLE, batch_dims=0]
All kernels registered for op GatherV2:
  device='XLA_CPU_JIT'; Taxis in [DT_INT32, DT_INT64]; 
Tparams in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, 
16005131165644881776, DT_UINT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64]; 
Tindices in [DT_INT32, DT_INT16, DT_INT64]
```
I can see DT_INT16 is also in the Tindices list which is also not expected.We have to remove the DT_INT16 from the list generated here and hopefully the Error you got also might be corrected.I hope this is what you are mentioning right?Please confirm once again.

Thankyou!

**Comment by triumph-wangyuyang** [comment]
> Hi @triumph-wangyuyang ,
> 
> Thanks for observing it. I have checked the op with dtype as and it is not supported both in 2.9.2V and nightly(2.12.0-dev20221128).Attaching here the [gist](https://colab.research.google.com/gist/SuryanarayanaY/e109a9a324fb5882573582a4b7a25e73/58697-2-9-2-nightly.ipynb#scrollTo=uT8paYsCYbsS) for same.`tf.int16``indices`
> 
> I think the API seems mentioning correct arguments but we need to correct the error statement. I hope this is what you also meant.Please confirm.
> 
> Also one more observation when i tested with dtype as argument it is throwing error as below.`tf.int16``indices`
> 
> ```
> NotFoundError: Could not find device for node: {{node GatherV2}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT16, Tparams=DT_DOUBLE, batch_dims=0]
> All kernels registered for op GatherV2:
>   device='XLA_CPU_JIT'; Taxis in [DT_INT32, DT_INT64]; 
> Tparams in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, 
> 16005131165644881776, DT_UINT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64]; 
> Tindices in [DT_INT32, DT_INT16, DT_INT64]
> ```
> 
> I can see DT_INT16 is also in the Tindices list which is also not expected.We have to remove the DT_INT16 from the list generated here and hopefully the Error you got also might be corrected.I hope this is what you are mentioning right?Please confirm once again.
> 
> Thankyou!

Thank you for your reply. If DT_INT16 is removed, the returned exception information will match the document information, which can solve my question.

**Comment by SuryanarayanaY** [comment]
Hi @triumph-wangyuyang ,

This [commit](https://github.com/tensorflow/tensorflow/commit/23076cbce805b4d6d57567e3f3d00f151b8f9782) shall address the issue once merged. Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @triumph-wangyuyang ,

Now the API `tf.gather` also supports `int16` data types also and the exception raised with 'float16' matches the supported data types.

Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/6f53c87d325cc242d8e1a63fa2e591e0/58697-tf-nightly-2-13.ipynb) tested with tf-nightly(2.13.0-dev20230305). Could you please check and confirm whether we can close the issue now?

Thanks!

**Comment by SuryanarayanaY** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks.
