### ISSUE TITLE
The information thrown by the tf.saturate_cast operator in different TensorFlow versions does not match the description in the documentation.

### ISSUE THREAD

**Issue by triumph-wangyuyang** [tensorflow/tensorflow#58695]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

TF 2.4, TF 2.10

### Custom Code

Yes

### OS Platform and Distribution

windows 11

### Python version

3.8.15

### CUDA/cuDNN version

CUDA: 11.3 cuDNN cuDNN 8.6.0

### GPU model and memory

RTX3060

### Current Behaviour?

```shell
The tf.clip_by_norm operator in TensorFlow2.4 version is completely consistent with the TensorFlow2.10 version description, and the data type for x is (A Tensor or IndexedSlices. This must be a floating point type.), so I am testing the code , when x is set to uint32, the information thrown is different in TensorFlow2.4 version and TensorFlow2.10 version, especially in TensorFlow2.4 version, the type of exception information description x can be (bfloat16, half, float, double , uint8, int8, uint16, int16, int32, int64, complex64, complex128) are inconsistent with the official description of a floating point type.
```

### Standalone code to reproduce the issue

```shell
from tensorflow import int32
    from tensorflow import uint32
    import tensorflow as tf
    import os

    os.environ['TF_XLA_FLAGS'] = '--tf_xla_enable_xla_devices'
    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
    with tf.device('/CPU'):
        t = tf.saturate_cast(tf.random.uniform([1, 5], minval=0, maxval=257, dtype=tf.int32), dtype=tf.uint32)
        clip_norm = 2.0
        out = tf.clip_by_norm(t, clip_norm)
    print(out)
```

### Relevant log output

```shell
Results running on TensorFlow 2.4:  tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of uint32 is not in the list of allowed values: bfloat16, half, float, double, uint8, int8, uint16, int16, int32, int64, complex64, complex128; NodeDef: {{node Mul}}; Op<name=Mul; signature=x:T, y:T -> z:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_UINT8, DT_INT8, DT_UINT16, DT_INT16, DT_INT32, DT_INT64, DT_COMPLEX64, DT_COMPLEX128]; is_commutative=true> [Op:Mul]

Results running on TensorFlow 2.10:  tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of uint32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]
```
</details>

**Comment by tilakrayal** [comment]
@triumph-wangyuyang,
Could you please feel free to submit a PR for the requested change or share the link where the requested change is to be made. Thank you!

**Comment by triumph-wangyuyang** [comment]
> @triumph-wangyuyang, Could you please feel free to submit a PR for the requested change or share the link where the requested change is to be made. Thank you!

I don't understand what you mean, do you want me to change it?

**Comment by tilakrayal** [comment]
@triumph-wangyuyang,
Could you pleasee feel free to create a pull request from [here](https://github.com/tensorflow/tensorflow/pulls) to update the documentation. In most of these, it is adding text to one of the python docstrings as mentioned below.

https://github.com/tensorflow/tensorflow/blob/abd266147c2e108796a5dbf28b0a8f16297bd98d/tensorflow/python/ops/math_ops.py#L333

Thank you!

**Comment by triumph-wangyuyang** [comment]
> @triumph-wangyuyang, Could you pleasee feel free to create a pull request from [here](https://github.com/tensorflow/tensorflow/pulls) to update the documentation. In most of these, it is adding text to one of the python docstrings as mentioned below.
> 
> https://github.com/tensorflow/tensorflow/blob/abd266147c2e108796a5dbf28b0a8f16297bd98d/tensorflow/python/ops/math_ops.py#L333
> 
> Thank you!

Thanks for your reply, I will try to change it later.
