### ISSUE TITLE
Model Exporting Does not Use optimize_for_inference_lib

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#5869]
Looking at the code in master, It looks like neither [`tensorflow.python.training.saver`](https://github.com/tensorflow/tensorflow/blob/eea96fc81bb1ae22eeb1d2141e47e182cecb7608/tensorflow/python/training/saver.py) nor [`tensorflow.contrib.session_bundle.exporter`](https://github.com/tensorflow/tensorflow/blob/eea96fc81bb1ae22eeb1d2141e47e182cecb7608/tensorflow/contrib/session_bundle/exporter.py) use [`optimize_for_inference_lib`](https://github.com/tensorflow/tensorflow/blob/df871edcff2faf643975b9863100ed41b6da9c3f/tensorflow/python/tools/optimize_for_inference_lib.py) which is described as:
>There are several common transformations ... that help reduce the amount of computation needed when the network is used only for inference.

Further these optimizations are not mentioned / suggested in the tensorflow serving docs:
* https://tensorflow.github.io/serving/
* https://github.com/tensorflow/tensorflow/blob/55cb1b37133e6c0409a708a763fccf566580a90a/tensorflow/contrib/session_bundle/README.md

Arguable the serving logic could be changed to [use frozen models](https://github.com/tensorflow/tensorflow/blob/5a5a25ea3ebef623e07fb9a46419a9df377a37a5/tensorflow/g3doc/how_tos/tool_developers/index.md#freezing) (see [`freeze_graph`](https://github.com/tensorflow/tensorflow/blob/df871edcff2faf643975b9863100ed41b6da9c3f/tensorflow/python/tools/freeze_graph.py)) which calls `convert_variables_to_constants`.

**Comment by alextp** [comment]
They shouldn't use optimize_for_inference_lib by default since not all exportings will be only used for inference.
