### ISSUE TITLE
Android example finally works

### ISSUE THREAD

**Issue by applemuncy** [tensorflow/tensorflow#587]
Finally was able to compile and install to Nexus 7 (2013) Marshmallow 6.0.1 with:
bazel mobile-install //tensorflow/examples/android:tensorflow_demo -c opt --start_app --copt=-mfpu=neon 

Crashes because no camera permission the first run so drop the --start_app  

Simple solution is to use ->settings -> apps -> Tensorflow Demo -> Permissions 
and enable both storage and camera.

So I'm wondering about the --copt=-mfpu=neon 

Tensorflow demo runs amazingly fast (a few seconds) on the Nexus 7 compared to waiting 10 minutes or so for the example label_image to produce results on an older Dell  - Intel(R) Core(TM)2 CPU         T7200  @ 2.00GHz

**Comment by sherrym** [comment]
Thanks for the update. Closing as it's not an issue.
