### ISSUE TITLE
Feature Request: Bivariate/multivariate Gaussian CDF

### ISSUE THREAD

**Issue by yincheng** [tensorflow/tensorflow#5870]
Would it be possible to support computing the CDF of multivariate Gaussian distributions? The multivariate Gaussian implementation under https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/distributions/python/ops doesn't seem to support the CDF for multivariate Gaussian yet.

**Comment by devanshdalal** [comment]
Is this still open? I can work on this.

**Comment by yincheng** [comment]
Hi @devanshdalal , it is still open. Please feel free.

**Comment by YiMX** [comment]
Still open? Can I try it?

**Comment by yincheng** [comment]
Hi @YiMX , please go ahead.
