### ISSUE TITLE
Type restrictions on seeds in the tf.image.stateless_random_hue documentation.

### ISSUE THREAD

**Issue by triumph-wangyuyang** [tensorflow/tensorflow#58703]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

TF 2.4

### Custom Code

Yes

### OS Platform and Distribution

windows 11

### Python version

3.8.15

### CUDA/cuDNN version

CUDA: 11.3    cuDNN 8.6.0

### GPU model and memory

RTX3060

### Current Behaviour?

```shell
The seed in the tf.image.stateless_random_hue(image, max_delta, seed) operator parameter, the requirement in the document is "A shape [2] Tensor, the seed to the random number generator. Must have dtype int32 or int64. (When using XLA, only int32 is allowed.)", you can clearly see ''When using XLA, only int32 is allowed.'', for this situation, I used the official test case, and used XLA, and then set the type of seed It is not designed to be int32, but int64. I found that the program can still run through, so I don't understand why the document is restricted''When using XLA, only int32 is allowed.''
```

### Standalone code to reproduce the issue

```shell
import os
    import tensorflow as tf

    os.environ['TF_XLA_FLAGS'] = '--tf_xla_enable_xla_devices'
    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
    with tf.device("/device:XLA_CPU:0"):
        x = [[[1.0, 2.0, 3.0],
              [4.0, 5.0, 6.0]],
             [[7.0, 8.0, 9.0],
              [10.0, 11.0, 12.0]]]
        seed = tf.constant([1, 2], dtype=tf.int64)
        out = tf.image.stateless_random_hue(x, 0.2, seed)
        print(out)
```

### Relevant log output

```shell
result:
 tf.Tensor(
 [[[ 1.6514893  1.         3.       ]
  [ 4.6514893  4.         6.       ]]

 [[ 7.6514893  7.         9.       ]
  [10.651489  10.        12.       ]]], shape=(2, 2, 3), dtype=float32)
```

tf.image.stateless_random_brightness, tf.image.stateless_sample_distorted_bounding_box, tf.image.stateless_random_flip_up_down, tf.image.stateless_random_flip_left_right, etc. all have the same problem.

</details>

**Comment by tiruk007** [comment]
@triumph-wangyuyang 
This issue is closed when [PR](https://github.com/tensorflow/tensorflow/pull/58725) is merged.
Thank you!

**Comment by tilakrayal** [comment]
@triumph-wangyuyang,
Have you got the chance to have a look at this related PR(https://github.com/tensorflow/tensorflow/pull/58725/files) which was merged and also I checked the official document of tf.image.stateless_random_hue w.r.t v2.14 and v2.4 where the document was updated without **When using XLA, only int32 is allowed** for the seed. Reference [Gist](https://colab.research.google.com/gist/tilakrayal/4b3e334eda78a126f060bcf41a152204/untitled1636.ipynb)

2.14:
https://www.tensorflow.org/api_docs/python/tf/image/stateless_random_hue#args

2.4:
https://www.tensorflow.org/versions/r2.4/api_docs/python/tf/image/stateless_random_hue#args

Thank you!
