### ISSUE TITLE
error occurs when convert a tflite model with uint8 inference_input_type during quantization-aware-training

### ISSUE THREAD

**Issue by fjzhangcr** [tensorflow/tensorflow#58709]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- TensorFlow installation (pip package or built from source): tf 2.8
- TensorFlow library (version, if pip package or github SHA, if built from source): tf2.8

### 2. Code
I want to convert a model by quantization aware training. the fp32 model is simple and it can only be convert to a tflite model with fp32 input/output. how can i convert a fp32 model with uint8 intput and output, since it can be done by post-training quantization by assign the converter.inference_input_type = tf.uint8 and converter.inference_output_type  = tf.uint8.  
if i can not assign inference_input_type or inference_output_type   during quantization-aware-training, how can i convert a tflite model with specified input output dtype?
 Thank you !
**minimum code:**
```
import tensorflow as tf
import numpy as np
from tensorflow.keras.layers import Conv2DTranspose


num_filters=512
inputs=tf.keras.Input((32,32,1024))

outputs= Conv2DTranspose(filters=num_filters,
                    kernel_size=(2, 2), 
                    strides=2, 
                    padding="same",name='convTrans')(inputs)

base_model=tf.keras.Model(inputs=inputs,outputs=outputs,name="test_transConv2D_model")
base_model.summary()
print(base_model.layers[1].weights[0].shape)
print(base_model.layers[1].weights[1].shape)
# (2, 2, 512, 1024)
# (512,)

import tensorflow_model_optimization as tfmot
quant_aware_model = tfmot.quantization.keras.quantize_model(base_model)

x_train = np.random.randn(4,32, 32, 1024).astype(np.float32)
y_train = np.random.randn(4, 64, 64, 512).astype(np.float32)
quant_aware_model.compile(
    loss=tf.keras.losses.categorical_crossentropy,
    optimizer='adam',
    metrics=['accuracy']
)
quant_aware_model.fit(x_train, y_train,epochs=1)
quant_aware_model.summary()

quant_aware_model.input.set_shape((1,) + quant_aware_model.input.shape[1:])

converter = tf.lite.TFLiteConverter.from_keras_model(quant_aware_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

quantized_tflite_model = converter.convert()
tflite_model_filename='test_transConv2D_model_uint8_inout.tflite'
with open(tflite_model_filename, 'wb') as f:
    f.write(quantized_tflite_model)
    print("wirte tflite file done!")
```
**ERRORS:**
```
C:\Users\indeed\.conda\envs\TF28_py37_1\lib\site-packages\tensorflow\lite\python\convert.py:746: UserWarning: Statistics for quantized inputs were expected, but not specified; continuing anyway.
  warnings.warn("Statistics for quantized inputs were expected, but not "
Traceback (most recent call last):

  File "D:\OneDrive\AI_Working_Directory\bio_cv\zz_test_transposcvon2d.py", line 48, in <module>
    quantized_tflite_model = converter.convert()

  File "C:\Users\indeed\.conda\envs\TF28_py37_1\lib\site-packages\tensorflow\lite\python\lite.py", line 803, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)

  File "C:\Users\indeed\.conda\envs\TF28_py37_1\lib\site-packages\tensorflow\lite\python\lite.py", line 789, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)

  File "C:\Users\indeed\.conda\envs\TF28_py37_1\lib\site-packages\tensorflow\lite\python\lite.py", line 1221, in convert
    self).convert(graph_def, input_tensors, output_tensors)

  File "C:\Users\indeed\.conda\envs\TF28_py37_1\lib\site-packages\tensorflow\lite\python\lite.py", line 1010, in convert
    result, self._quant_mode, quant_io=self.experimental_new_quantizer)

  File "C:\Users\indeed\.conda\envs\TF28_py37_1\lib\site-packages\tensorflow\lite\python\convert_phase.py", line 216, in wrapper
    raise error from None  # Re-throws the exception.

  File "C:\Users\indeed\.conda\envs\TF28_py37_1\lib\site-packages\tensorflow\lite\python\convert_phase.py", line 206, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\indeed\.conda\envs\TF28_py37_1\lib\site-packages\tensorflow\lite\python\lite.py", line 759, in _optimize_tflite_model
    model = _modify_model_io_type(model, m_in_type, m_out_type)

  File "C:\Users\indeed\.conda\envs\TF28_py37_1\lib\site-packages\tensorflow\lite\python\util.py", line 979, in modify_model_io_type
    return _convert_model_from_object_to_bytearray(model_object)

  File "C:\Users\indeed\.conda\envs\TF28_py37_1\lib\site-packages\tensorflow\lite\python\util.py", line 561, in _convert_model_from_object_to_bytearray
    model_offset = model_object.Pack(builder)

  File "C:\Users\indeed\.conda\envs\TF28_py37_1\lib\site-packages\tensorflow\lite\python\schema_py_generated.py", line 5890, in Pack
    operatorCodes = builder.EndVector(len(self.operatorCodes))

TypeError: EndVector() takes 1 positional argument but 2 were given
```

Provide code to help us reproduce your issues using one of the following options:

#### Option A: Reference colab notebooks

1)  Reference [TensorFlow Model Colab](https://colab.research.google.com/gist/ymodak/e96a4270b953201d5362c61c1e8b78aa/tensorflow-datasets.ipynb?authuser=1): Demonstrate how to build your TF model.
2)  Reference [TensorFlow Lite Model Colab](https://colab.research.google.com/gist/ymodak/0dfeb28255e189c5c48d9093f296e9a8/tensorflow-lite-debugger-colab.ipynb): Demonstrate how to convert your TF model to a TF Lite model (with quantization, if used) and run TFLite Inference (if possible).

```
(You can paste links or attach files by dragging & dropping them below)
- Provide links to your updated versions of the above two colab notebooks.
- Provide links to your TensorFlow model and (optionally) TensorFlow Lite Model.
```

#### Option B: Paste your code here or provide a link to a custom end-to-end colab

```
(You can paste links or attach files by dragging & dropping them below)
- Include code to invoke the TFLite Converter Python API and the errors.
- Provide links to your TensorFlow model and (optionally) TensorFlow Lite Model.
```

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

- Model produces wrong results and/or has lesser accuracy.
- Model produces correct results, but it is slower than expected.

### 4. (optional) RNN conversion support
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mohantym** [comment]
Hi @fjzhangcr !
I could not replicate the same behaviour in 2.9.2 version (default in colab). Attached [gist ](https://colab.sandbox.google.com/gist/mohantym/759864ce37096fd593a5ad03da52b1e3/git_58709.ipynb#scrollTo=A1x7dJBVTpKC)for reference.
Thank you!

**Comment by fjzhangcr** [comment]
the version of the tf on my pc is 2.8, it shows the converter.convert() goes wrong~~~
but the tf of 2.8 or 2.9 on colabe shows everything goes well...
is it common or wired tf may be install incorrectly on my pc? i was using pip install tensorflow==2.8 on anaconda to setup my virtual env....this env seems ok when i used it.

![sunlogin_20221129102607](https://user-images.githubusercontent.com/102020341/204423883-d828dba4-5379-4c3f-9142-48fe743eae4c.jpg)

**Comment by mohantym** [comment]
Hi @fjzhangcr !
I was able to get a tflite model after following instructions from [windows](https://www.tensorflow.org/install/pip#windows-native)

Could you create a new environment as per above instruction and let us know whether it works.
Thank you!

**Comment by fjzhangcr** [comment]
thank you~~ maybe something went wrong when i installed it~~
