### ISSUE TITLE
Movenet low fps on movenet's official example app - GPU issue

### ISSUE THREAD

**Issue by madhavarora2002** [tensorflow/tensorflow#58706]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.11

### Custom Code

No

### OS Platform and Distribution

Android

### Mobile device

Android Mobile

### Current Behaviour?

```shell
Running example app of movenet on android: https://github.com/tensorflow/examples/tree/master/lite/examples/pose_estimation/android

Movenet's lighning model is giving 20-25 fps instead of the mentioned 50+ fps on mobile device
(tested different android mobiles from mid to high range)
I figure it's likely because it's not using gpu, since the speed is constant with gpu and cpu.
```

### Standalone code to reproduce the issue

```shell
https://github.com/tensorflow/examples/tree/master/lite/examples/pose_estimation/android

Just run this project in android studio and see apk.
```

### Relevant log output

_No response_</details>

**Comment by madhavarora2002** [comment]
https://github.com/tensorflow/examples/pull/324/commits/bcae5ee17e77d866a11151b351191b09f1115cb8

TF team have marked a to do for fixing gpu in the android version a year and half back. Any way you could reach them regarding this, as it's making movenet unsuable for android with low fps!

**Comment by sachinprasadhs** [comment]
Hi, Thanks for highlighting the issue. I have reopened the related issue here https://github.com/tensorflow/tensorflow/issues/56795. 
Could you please close this issue, since it is better to track the progress in a single thread. Thanks!
