### ISSUE TITLE
tf.image.random_flip_left_right failed to run on GPU

### ISSUE THREAD

**Issue by triumph-wangyuyang** [tensorflow/tensorflow#58700]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

TF 2.10

### Custom Code

Yes

### OS Platform and Distribution

windows 11

### Python version

3.8.15

### CUDA/cuDNN version

CUDA: 11.3    cuDNN 8.6.0

### Current Behaviour?

```shell
In the case of tf.image.random_flip_left_right input parameters, but the results are different on CPU and GPU.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

    image = tf.saturate_cast(tf.random.uniform([2, 2, 1, 1], minval=-128, maxval=128, dtype=tf.int64),dtype=tf.int8)
    with tf.device('/CPU'):
        out = tf.image.random_flip_left_right(image)
        print("CPU: ", out)

    with tf.device('/GPU:0'):
        out = tf.image.random_flip_left_right(image)
        print("GPU: ", out)
```

### Relevant log output

```shell
CPU:  tf.Tensor(
[[[[-53]]

  [[ 87]]]


 [[[  7]]

  [[ 30]]]], shape=(2, 2, 1, 1), dtype=int8)

tensorflow.python.framework.errors_impl.UnknownError: {{function_node __wrapped__Sub_device_/job:localhost/replica:0/task:0/device:GPU:0}} JIT compilation failed. [Op:Sub]
```
</details>

**Comment by triumph-wangyuyang** [comment]
This is also the case with tf.image.random_flip_up_down.

code: 

    import tensorflow as tf
    image = tf.saturate_cast(tf.random.uniform([2, 2, 2, 1], minval=0, maxval=256, dtype=tf.int64), dtype=tf.uint8)
    with tf.device('/CPU'):
        out = tf.image.random_flip_up_down(image)
        print("CPU: ", out)

    with tf.device('/GPU:0'):
        out = tf.image.random_flip_up_down(image)
        print("GPU: ", out)

**Comment by mohantym** [comment]
Hi @triumph-wangyuyang !
Could you check with  Cuda 11.2 and CudNN 8.1 and 2.10/2.11
I could not replicate the Same in Colab ( Default config  is 11.2 and 8.1 In Colab).

Thank you!

**Comment by triumph-wangyuyang** [comment]
> Hi @triumph-wangyuyang ! Could you check with Cuda 11.2 and CudNN 8.1 and 2.10/2.11 I could not replicate the Same in [Colab](https://colab.sandbox.google.com/gist/mohantym/66e2dcd943d0111bfbe1bf04eef2e10b/git_58700.ipynb#scrollTo=H1Xtc8dnbi6v) ( Default config is 11.2 and 8.1 In Colab).
> 
> Thank you!

Hello, my experimental environment is CUDA: 11.3 and cuDNN 8.6.0, but I don't have enough network traffic to download the CUDA11.2 version, and I can't reproduce the experiment on CUDA: 11.2 and cuDNN 8.6.0.

**Comment by mohantym** [comment]
@triumph-wangyuyang !
That explains the above behavior then. Thanks for sharing your results.

Please stick to Cuda 11.2 and Cudnn 8.1 for 2.11 for now. 2.12 release is already being prepared for a Cuda upgrade (11.6 ) . [Reference.](https://github.com/tensorflow/tensorflow/pull/53409)

Could we consider this resolved for now then.

Thank you!

**Comment by triumph-wangyuyang** [comment]
> @triumph-wangyuyang ! That explains the above behavior then. Thanks for sharing your results.
> 
> Please stick to Cuda 11.2 and Cudnn 8.1 for 2.11 for now. 2.12 release is already being prepared for a Cuda upgrade (11.6 ) . [Reference.](https://github.com/tensorflow/tensorflow/pull/53409)
> 
> Could we consider this resolved for now then.
> 
> Thank you!

Therefore, tf.image.random_flip_up_down operator and tf.image.random_flip_left_right operator in CUDA: 11.3 cuDNN 8.6.0 are indeed unable to run on GPU, and then the test code can be successfully run in tensorflow 2.11 of Cuda 11.2 and Cudnn 8.1 Yes, did you mean this?

**Comment by mohantym** [comment]
Hi @triumph-wangyuyang !
I meant tested Cuda config is recommended as you said It worked for  Cuda 11.2  and CudNN 8.6 worked for you. We have seen you good amount of GPU issues replicating on Cuda 11.3 or higher version. Tested config always works for most of the cases.

@SuryanarayanaY !
Could you comment on this.

**Comment by SuryanarayanaY** [comment]
Hi @triumph-wangyuyang ,

Actually we recommend users to use tested configurations only as per documentation.Using other configurations may create compatibility issues. Currently TF 2.10 & 2.11 tested on CUDA 11.2 as per [documentation](https://www.tensorflow.org/install/source_windows#gpu) and higher versions of CUDA support not guaranteed on TF2.10 . 

We got update that from 2.12 version(tf-nightly), CUDA 11.8 shall be supported. Because from nightly CUDA support is extended to 11.8, I can't guarantee you that this problem with 11.3 can be considered to resolve or not. Could you please check with tf-nightly along with CUDA 11.8 and if same problem persists  please let us know so that we can resolve this.

Thankyou!

**Comment by triumph-wangyuyang** [comment]
> Hi @triumph-wangyuyang ,
> 
> Actually we recommend users to use tested configurations only as per documentation.Using other configurations may create compatibility issues. Currently TF 2.10 & 2.11 tested on CUDA 11.2 as per [documentation](https://www.tensorflow.org/install/source_windows#gpu) and higher versions of CUDA support not guaranteed on TF2.10 .
> 
> We got update that from 2.12 version(tf-nightly), CUDA 11.8 shall be supported. Because from nightly CUDA support is extended to 11.8, I can't guarantee you that this problem with 11.3 can be considered to resolve or not. Could you please check with tf-nightly along with CUDA 11.8 and if same problem persists please let us know so that we can resolve this.
> 
> Thankyou!

I just ran the above two test codes of tf.image.random_flip_left_right and tf.image.random_flip_up_down in CUDA11.2, cudnn8.1, tensorflow2.11, and found that it can be successful.
In order to test the impact not caused by cuda and cudnn versions, I tested in CUDA11.3, cudnn8.6, tensorflow2.11 and found that it can also run successfully.
According to the above two results, it can be explained that the version of tensorflow caused tf.image.random_flip_left_right and tf.image.random_flip_up_down to run inconsistently on the CPU and GPU. It is guessed that Tensorflow2.11 has fixed the problem that it cannot run on the GPU.

**Comment by SuryanarayanaY** [comment]
Hi @triumph-wangyuyang ,

As i told you we can assure performance guarantees for the tested configurations and if there is problem then sure it will be taken up for resolution. The untested versions may or may not function as intended.Since every time when TF updates versions compatibilities they will be tested and problems if any will be taken care before release itself.

> I just ran the above two test codes of tf.image.random_flip_left_right and tf.image.random_flip_up_down in CUDA11.2, cudnn8.1, tensorflow2.11, and found that it can be successful.

Even in TF 2.10 with CUDA 11.2 and cuDNN 8.1 the code is successful as per colab [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/1cc7abac93e8fb3904402072648989e4/58700-2-10.ipynb) attached.The problem may arises with configurations that are not tested.



> In order to test the impact not caused by cuda and cudnn versions, I tested in CUDA11.3, cudnn8.6, tensorflow2.11 and found that it can also run successfully.

Iam not sure whether TF2.11 V tested on CUDA 11.3 or not but iam quite sure if it is tested definitely it might be documented and updated to everyone.It may possible that there might be some changes between TF versions which might be supporting this configuration.

> According to the above two results, it can be explained that the version of tensorflow caused tf.image.random_flip_left_right and tf.image.random_flip_up_down to run inconsistently on the CPU and GPU. It is guessed that Tensorflow2.11 has fixed the problem that it cannot run on the GPU.
 
I can't confirm which changes made 2.11V works with CUDA 11.3 for this case since it is not tested configuration as per documentation.

Please refer to [update](https://discuss.tensorflow.org/t/cuda-updated-to-11-8/12942) on tf-nightly(2.12 v) compatibility with CUDA 11.8.
Hence i request you to please use tested configurations only.

**Comment by triumph-wangyuyang** [comment]
> Hi @triumph-wangyuyang ,
> 
> As i told you we can assure performance guarantees for the tested configurations and if there is problem then sure it will be taken up for resolution. The untested versions may or may not function as intended.Since every time when TF updates versions compatibilities they will be tested and problems if any will be taken care before release itself.
> 
> > I just ran the above two test codes of tf.image.random_flip_left_right and tf.image.random_flip_up_down in CUDA11.2, cudnn8.1, tensorflow2.11, and found that it can be successful.
> 
> Even in TF 2.10 with CUDA 11.2 and cuDNN 8.1 the code is successful as per colab [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/1cc7abac93e8fb3904402072648989e4/58700-2-10.ipynb) attached.The problem may arises with configurations that are not tested.
> 
> > In order to test the impact not caused by cuda and cudnn versions, I tested in CUDA11.3, cudnn8.6, tensorflow2.11 and found that it can also run successfully.
> 
> Iam not sure whether TF2.11 V tested on CUDA 11.3 or not but iam quite sure if it is tested definitely it might be documented and updated to everyone.It may possible that there might be some changes between TF versions which might be supporting this configuration.
> 
> > According to the above two results, it can be explained that the version of tensorflow caused tf.image.random_flip_left_right and tf.image.random_flip_up_down to run inconsistently on the CPU and GPU. It is guessed that Tensorflow2.11 has fixed the problem that it cannot run on the GPU.
> 
> I can't confirm which changes made 2.11V works with CUDA 11.3 for this case since it is not tested configuration as per documentation.
> 
> Please refer to [update](https://discuss.tensorflow.org/t/cuda-updated-to-11-8/12942) on tf-nightly(2.12 v) compatibility with CUDA 11.8. Hence i request you to please use tested configurations only.
> 
> Thankyou.

Thank you for your reply. I just ran in CUDA 11.2, cudnn8.1.1, tensorflow-gpu 2.10.0, windows 11 environment, and found that the CPU succeeded, but the GPU failed. I don’t understand why you can run successfully. Is it because the operating system is windows?

`python:3.8`
`CUDA:11.2`
`cudnn:8.1.1`
`OS: Windows 11`
`Tensorflow:2.10.0 (pip install tensorflow-gpu==2.10)`

**Comment by SuryanarayanaY** [comment]
@triumph-wangyuyang ,
i tried with `pip install tensorflow-gpu==2.10` in colab and there is no error here as per this [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/5c951b1e95bf5d25436e608cb125585e/58700-2-10-gpu.ipynb).

The difference may be due to the OS.Colab uses Linux environment.I should test this on Windows 11 OS environment.Let me check and confirm.

Thankyou!

**Comment by triumph-wangyuyang** [comment]
> @triumph-wangyuyang , i tried with in colab and there is no error here as per this [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/5c951b1e95bf5d25436e608cb125585e/58700-2-10-gpu.ipynb).`pip install tensorflow-gpu==2.10`
> 
> The difference may be due to the OS.Colab uses Linux environment.I should test this on Windows 11 OS environment.Let me check and confirm.
> 
> Thankyou!

Hello, have you tested it on Windows?

**Comment by SuryanarayanaY** [comment]
@triumph-wangyuyang ,
For a quick checkup I have tested the code on my own Windows PC and i can say that the error persists on Windows OS.

Thankyou!

**Comment by triumph-wangyuyang** [comment]
> @triumph-wangyuyang , For a quick checkup I have tested the code on my own Windows PC and i can say that the error persists on Windows OS.
> 
> Thankyou!

Thank you for your reply, indicating that this error does exist on Windows systems.

**Comment by SuryanarayanaY** [comment]
![Screenshot 58700](https://user-images.githubusercontent.com/116063290/206480691-a7d5256b-1b72-4e61-9cd2-398ff9b42c0f.png)
@sachinprasadhs , Please find the attached screen shot of the problem replicated in Windows PC.

**Comment by cantonios** [comment]
We no longer support Windows GPU builds.  2.10 was the last supported release.

https://www.tensorflow.org/install/pip#windows-native
