### ISSUE TITLE
Not able to download Mac GPU build. 404. 

### ISSUE THREAD

**Issue by bhoomit** [tensorflow/tensorflow#5872]
Link in README is broken.

https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-mac-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-mac/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.11.0-py2-none-any.whl

**Comment by MatthiasWinkelmann** [comment]
It's [https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-mac-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-mac/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.11.0-py2-none-any.whl](https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-mac-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-mac/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.11.0-py2-none-any.whl), see [https://ci.tensorflow.org/view/Nightly/](https://ci.tensorflow.org/view/Nightly/) for other versions.

Or, unless you have a good reason, get something a bit more stable than the nightlies: 
[https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#using-pip](https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#using-pip):


```
# Mac OS X, CPU only, Python 2.7:
(tensorflow)$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0-py2-none-any.whl

# Mac OS X, GPU enabled, Python 2.7:
(tensorflow)$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow-0.11.0-py2-none-any.whl

# Mac OS X, CPU only, Python 3.4 or 3.5:
(tensorflow)$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0-py3-none-any.whl

# Mac OS X, GPU enabled, Python 3.4 or 3.5:
(tensorflow)$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow-0.11.0-py3-none-any.whl
```

**Comment by bhoomit** [comment]
> It's https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-mac-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-mac/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.11.0-py2-none-any.whl, 

gives 404.

**Comment by prb12** [comment]
> Link in README is broken.

Could you please be a little more specific?

**Comment by bhoomit** [comment]
@prb12 

README -> [Installation](https://github.com/tensorflow/tensorflow#installation) -> Mac GPU : [Python 2](https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-mac-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-mac/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.11.0-py2-none-any.whl)

gives 404

**Comment by prb12** [comment]
@yifeif  Looks like this is maybe related to the version change from 0.11.0.rc2 to 0.11.0?

**Comment by yifeif** [comment]
Sorry for the confusion, we updated the names and it is currently only reflected in release branch. Could you use the link from release branch for now https://github.com/tensorflow/tensorflow/tree/r0.12 . We will merge it back to master soon.

**Comment by bhoomit** [comment]
@yifeif Got it. Thanks :)
