### ISSUE TITLE
MultiHeadAttention layer bug with attention_mask computation if we pass attention_axes

### ISSUE THREAD

**Issue by vidyadhar-m** [tensorflow/tensorflow#58726]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.11.0 (GIT version: v2.11.0-rc2-17-gd5b57ca93e5)

### Custom Code

Yes

### OS Platform and Distribution

MacOS 13.0.1

### Python version

3.9.6

### Current Behaviour?

While using MultiHeadAttention module with attention mask, there seems to issue in computing the mask. The following code snippet fails by throwing the error:
```shell
{{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [256,12,2,20,20] vs. [256,12,1,12,20] [Op:AddV2]

Call arguments received by layer 'softmax_16' (type Softmax):
  • inputs=tf.Tensor(shape=(256, 12, 2, 20, 20), dtype=float32)
  • mask=tf.Tensor(shape=(256, 12, 1, 12, 20), dtype=bool)
```
However, the below code works fine when we pass `mask_zero=False` while defining the Embedding layer.

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf
from keras import layers as tfl

class Encoder(tfl.Layer):
    def __init__(self,):
        super().__init__()
        self.embed_layer = tfl.Embedding(4500, 32, mask_zero=True)
        self.attn_layer = tfl.MultiHeadAttention(num_heads=2,
                                                 attention_axes=2,
                                                 key_dim=16)
        return

    def call(self, x):
        # Input shape: (256, 10, 20) (Batch size: 256)
        x = self.embed_layer(x)  # Output: (256, 10, 20, 32)
        x = self.attn_layer(query=x, key=x, value=x)  # Output: (256, 10, 20, 32)
        return x


eg_input = tf.constant(np.random.randint(0, 150, (256, 12, 20)))
enc = Encoder()
enc(eg_input).shape
```

### Relevant log output
```
{{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [256,12,2,20,20] vs. [256,12,1,12,20] [Op:AddV2]

Call arguments received by layer 'softmax_16' (type Softmax):
  • inputs=tf.Tensor(shape=(256, 12, 2, 20, 20), dtype=float32)
  • mask=tf.Tensor(shape=(256, 12, 1, 12, 20), dtype=bool)
```
</details>

**Comment by vidyadhar-m** [comment]
FYI: Adding `x = tf.concat(x, axis=0)` after embedding layer call seems to fix the issue with mask. I am not sure why that is the case. So final code snipper for call function:
```
    def call(self, x):
        # Input shape: (256, 10, 20) (Batch size: 256)
        x = self.embed_layer(x)  # Output: (256, 10, 20, 32)
        x = tf.concat(x, axis=0) # Output: (256, 10, 20, 32)
        x = self.attn_layer(query=x, key=x, value=x)  # Output: (256, 10, 20, 32)
        return x
```

**Comment by sushreebarsa** [comment]
@vidyadhar-m This issue is not reproducible in TF v2.9, I am getting `TensorShape([256, 12, 20, 32])` as output. , please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/1a20d4b246df375540c25de3e66a1ce7/58726-2-9-v.ipynb).
While reproducing this issue I faced the following result in both 2.11 and tf-nightly. You may find the attached gist [here](https://colab.research.google.com/gist/sushreebarsa/ea17a6ea926044f7700b10feb741cf77/untitled751.ipynb#scrollTo=1mH36hyTpxiC).
```
InvalidArgumentError: Exception encountered when calling layer 'softmax' (type Softmax).

{{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:GPU:0}} required broadcastable shapes [Op:AddV2]

Call arguments received by layer 'softmax' (type Softmax):
  • inputs=tf.Tensor(shape=(256, 12, 2, 20, 20), dtype=float32)
  • mask=tf.Tensor(shape=(256, 12, 1, 12, 20), dtype=bool)
``` 
Could you please confirm this and let us know?
Thank you!
