### ISSUE TITLE
Cannot install tensorflow 2.3.0

### ISSUE THREAD

**Issue by Denzeduous** [tensorflow/tensorflow#58723]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

2.3.0

### Custom Code

No

### OS Platform and Distribution

Windows 10

### Python version

3.7

### Current Behaviour?

I cannot, for the life of me, figure out how to install tensorflow 2.3.0. I've downgraded to Python 3.7 and have tried every resource I can. I've upgraded pip, installing via `pip install tensorflow==2.3.0`, and I've even tried downloading the wheels off of the pip site (which gave the explanation that they're not supported on my platform, even though I tried the cp35, cp36, and cp38 windows wheels, which are the only ones I saw).

When running my Python 3.7's pip, I get:
```
pip install tensorflow==2.3.0
ERROR: No matching distribution found for tensorflow==2.3.0
```
As well as:
```
pip install tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```
I specifically need 2.3.0 to work properly with keras-rl. Any help would really be appreciated, as I've scoured every resource on the internet that I can possibly find.
```


### Standalone code to reproduce the issue

```shell
N/A
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @Denzeduous !
Thanks for sharing your observation. I can replicate this issue in my local windows machine.
Supported version list seems to be  restricted to >2.8.0rc1 and < 2.11 now. 

2.3/2.4 version are pretty outdated.
Could you check with 2.8.1 or higher version (<2.11 for pip  or Direct ML plugin for higher version) and let us know.
Attached relevant [thread ](https://www.tensorflow.org/install/pip#windows-native)for reference.

Thank you!

**Comment by Denzeduous** [comment]
Hello mohantym,

Thank you! That seems to be working with keras-rl for now. By chance, do you know what keras version is most compatible with tensorflow 2.8.1? It seems to be having some difficulties now. I know that is technically a different project, so no worries if you can't answer.

**Comment by mohantym** [comment]
@Denzeduous !
You can install 2.8.1 keras for Tensorflow if you are facing any compatibility issues.
Keras and others package version dependencies are mentioned [here](https://github.com/tensorflow/tensorflow/blob/r2.8/tensorflow/tools/pip_package/setup.py) in setup.py file.

Can we consider this as resolved then.

Thank you!

**Comment by Denzeduous** [comment]
Yes, thank you so much mohantym! You were a great help!
