### ISSUE TITLE
How to write to input tensors in custom op?

### ISSUE THREAD

**Issue by Alantlb** [tensorflow/tensorflow#58721]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### Current Behaviour?

```shell
How can I write to input tensors in a custom op? I can read and write to output tensors but only read on inputs. (compiling outputs "assignment of read-only location" error when trying to write to input tensor). I want to write an inplace op, and making it inplace is crucial for my project, as writting the results to an output tensor and then assigning the output to the variable is too slow). Here is a minimal example that just sets the input tensor to zero. What code can I add to this example code so that I can be able to write to the input tensor?
```

### Standalone code to reproduce the issue

```shell
#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/shape_inference.h"
#include "tensorflow/core/framework/op_kernel.h"
#include "tensorflow/core/util/work_sharder.h"

#include <iostream>

using namespace tensorflow;

REGISTER_OP("Example")
    .Input("variable: float")
    ;

class ExampleOp : public OpKernel {
public:
    
    explicit ExampleOp(OpKernelConstruction* context) : OpKernel(context) {}

    void Compute(OpKernelContext* context) override {

        const Tensor& variable_tensor = context->input(0);
        auto variable = variable_tensor.flat<float>();
        
        for(int i = 0; i < variable.size(); ++i)
            variable(i) = 0; 

    };

};


REGISTER_KERNEL_BUILDER(Name("Example").Device(DEVICE_CPU), ExampleOp);
```

### Relevant log output

```shell
minimal.cc: In member function ‘virtual void ExampleOp::Compute(tensorflow::OpKernelContext*)’:
minimal.cc:25:25: error: assignment of read-only location ‘variable.Eigen::TensorMap<Eigen::Tensor<const float, 1, 1, long int>, 16, Eigen::MakePointer>::operator()(((Eigen::TensorMap<Eigen::Tensor<const float, 1, 1, long int>, 16, Eigen::MakePointer>::Index)i))’
   25 |             variable(i) = 0;
      |             ~~~~~~~~~~~~^~~
```
</details>

**Comment by Alantlb** [comment]
How can I write to input tensors in a custom op? I can read and write to output tensors but only read on inputs. (compiling outputs "assignment of read-only location" error when trying to write to input tensor). I want to write an inplace op, and making it inplace is crucial for my project, as writting the results to an output tensor and then assigning the output to the variable is too slow). Here is a minimal example that just sets the input tensor to zero. What code can I add to this example code so that I can be able to write to the input tensor?

**Comment by sushreebarsa** [comment]
@Alantlb Could you please refer to this [link](https://www.tensorflow.org/guide/create_op) and let us know if it helps?
Thank you!

**Comment by sachinprasadhs** [comment]
Hi, If you are looking for assigning value to the Tensor variable, you can do it using `tf.Variable.assign()`. 
Let us know if you are looking for something else. Thanks!
