### ISSUE TITLE
tf.keras.metrics.mean_absolute_error exception information is misleading.

### ISSUE THREAD

**Issue by triumph-wangyuyang** [tensorflow/tensorflow#58737]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

TF 2.11

### Custom Code

Yes

### OS Platform and Distribution

windows 11

### Python version

3.8.15

### CUDA/cuDNN version

CUDA: 11.2    cuDNN 8.1

### GPU model and memory

RTX3060

### Current Behaviour?

```shell
The exceptions thrown by tf.keras.metrics.mean_absolute_error(y_true, y_pred) are different when running the following two test codes.
   In code1, I set y_pred to bool, and the exception message prompts me that bool is not in the legal type (bfloat16, half, float, double, uint8, int8, uint16, int16, int32, int64, complex64, complex128, uint32, uint64) (Remember that it includes uint16, which will be useful later).
   In code2, I set y_pred to uint16, and the exception information reminded me that uint16 is not in the legal type (bfloat16, half, float, double, int8, int16, int32, int64). It is obvious that the exception information before and after is contradictory.
```

### Standalone code to reproduce the issue

```shell
code 1:

    import tensorflow as tf
    y_true = tf.random.uniform([2, 3], minval=-5, maxval=5, dtype=tf.int32)
    y_pred = tf.cast(tf.random.uniform([2, 3], minval=-5, maxval=5, dtype=tf.int32), dtype=tf.bool)
    out = tf.keras.metrics.mean_absolute_error(y_true, y_pred)



code 2:

    import tensorflow as tf
    y_true = tf.random.uniform([2, 3], minval=-5, maxval=5, dtype=tf.int32)
    y_pred = tf.cast(tf.random.uniform([2, 3], minval=-5, maxval=5, dtype=tf.int32), dtype=tf.uint16)
    out = tf.keras.metrics.mean_absolute_error(y_true, y_pred)
```

### Relevant log output

```shell
code1 result : tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of bool is not in the list of allowed values: bfloat16, half, float, double, uint8, int8, uint16, int16, int32, int64, complex64, complex128, uint32, uint64; NodeDef: {{node Sub}}; Op<name=Sub; signature=x:T, y:T -> z:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_UINT8, DT_INT8, DT_UINT16, DT_INT16, DT_INT32, DT_INT64, DT_COMPLEX64, DT_COMPLEX128, DT_UINT32, DT_UINT64]> [Op:Sub]


code2 result : tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of uint16 is not in the list of allowed values: bfloat16, half, float, double, int8, int16, int32, int64; NodeDef: {{node Abs}}; Op<name=Abs; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_INT8, DT_INT16, DT_INT32, DT_INT64]> [Op:Abs]
```
</details>

**Comment by triumph-wangyuyang** [comment]
tf.keras.metrics.mean_absolute_percentage_error has the same behavior.

**Comment by triumph-wangyuyang** [comment]
tf.keras.metrics.mape has the same behavior.

**Comment by triumph-wangyuyang** [comment]
tf.keras.metrics.mean_absolute_percentage_error, tf.keras.metrics.mape, tf.keras.metrics.MAPE, tf.keras.metrics.mae, tf.keras.metrics.MAE have the same performance.

**Comment by triumph-wangyuyang** [comment]
In fact, this kind of problem can be traced back to the operators in the `tf.keras.losses.*` directory.

**Comment by mohantym** [comment]
Hi @triumph-wangyuyang !
Thanks for reporting this bug.

Please post this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . 

Thank you!

**Comment by triumph-wangyuyang** [comment]
tf.losses.mean_absolute_error, tf.losses.mean_absolute_percentage_error, tf.losses.mape, tf.losses.MAPE, tf.losses.mae, tf.losses.MAE; tf.keras.losses.mean_absolute_error, tf.keras.losses. mean_absolute_percentage_error, tf.keras.losses.mape, tf.keras.losses.MAPE, tf.keras.losses.mae, tf.keras.losses.MAE; in addition, you can find this in tf.losses and tf.keras.losses situation.

**Comment by triumph-wangyuyang** [comment]
> Hi @triumph-wangyuyang !
> 
> I agree this is a valid bug. Would it possible to report these observations in Keras repo and mention the tracker here.
> 
> Thank you!

Thanks for your reply, I went to Keras repo to report the bug.

**Comment by mohantym** [comment]
@triumph-wangyuyang !
Thanks for the update. It would be great if you share the Keras tracker here too. 
Closing this issue for now.

Thank you!
