### ISSUE TITLE
tf2.11 tf.profiler.experimental  doesn't generate trace.json.gz and other files compared with tf2.10

### ISSUE THREAD

**Issue by LIONEFAN** [tensorflow/tensorflow#58738]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.11

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

Linux Ubuntu 20.04

### Python version

3.10

### Current Behaviour?

```shell
In tf2.10, when use the tf.profiler.experimental.start(logdir) and tf.profiler.experimental.stop(). It will generate many files as bellow in logdir folder.
.
├── events.out.tfevents.XXXX.profile-empty
└── plugins
    └── profile
        └── 2022_11_29_08_25_43
            ├── XXXX.input_pipeline.pb
            ├── XXXX.kernel_stats.pb
            ├── XXXX.memory_profile.json.gz
            ├── XXXX.overview_page.pb
            ├── XXXX.tensorflow_stats.pb
            ├── XXXX.trace.json
            └── XXXX.xplane.pb

But in tf2.11, it only generate these files.
.
├── events.out.tfevents.XXXX.profile-empty
└── plugins
    └── profile
        ├── 2022_11_29_08_32_10
        │   └── XXXX.xplane.pb

I think the tf2.11 outputs files should be the same as the tf2.10. 
Is this a bug? If not, can you tell me an alternative solution to get them in tf2.11?
```

### Standalone code to reproduce the issue

```shell
import random
import tensorflow as tf
options = tf.profiler.experimental.ProfilerOptions(host_tracer_level = 3,
                                                   python_tracer_level = 1,
                                                   device_tracer_level = 1)
tf.profiler.experimental.start("logdir_simple_tf211(1)", options=options)

""" Simple training model """
def Y(a, x):
    return a*(x**2 + 4)

""" Target model """
def Z(a):
    return a*(4**2 + 4)

lr = 0.01
x = tf.Variable(1.1,name = 'var')
optimizer = tf.keras.optimizers.Adam(lr=0.01)

for _ in range(10000):
    input = random.randint(1,255)
    target = Z(input)
    with tf.GradientTape() as tape:
        pre = Y(input, x)
        loss = abs(pre - target)

    gradient = tape.gradient(loss,x)
    optimizer.apply_gradients([(gradient, x)])

    if _ % 100 == 0:
        print("loss:", loss.numpy())
        
print("x: ", x.numpy())
tf.profiler.experimental.stop(save=True)
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@LIONEFAN,
I tried to execute the mentioned code and was able to fetch the similar output in both tensorflow versions 2.10 and 2.11. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/a6d3f2e5e099ab98b42163b0ad04ba9f/untitled788.ipynb) and the images for the reference.
![image](https://user-images.githubusercontent.com/81610181/204815128-c3146756-412f-469b-8360-af7bcd10111c.png)
 Thank you!

**Comment by LIONEFAN** [comment]
> @LIONEFAN, I tried to execute the mentioned code and was able to fetch the similar output in both tensorflow versions 2.10 and 2.11. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/a6d3f2e5e099ab98b42163b0ad04ba9f/untitled788.ipynb) and the images for the reference. ![image](https://user-images.githubusercontent.com/81610181/204815128-c3146756-412f-469b-8360-af7bcd10111c.png) Thank you!

Hi @tilakrayal,

I also test it in gist [here](https://colab.research.google.com/gist/LIONEFAN/71c572cde6fc644967a514988a30cde0/untitled788.ipynb), but my results are different with you. 
![image](https://user-images.githubusercontent.com/52822833/204971328-0804acaf-11c0-4da0-97f1-37b2450c0b87.png)
I think you maybe run them all in tf2.11. 
I suggest you manually run the tf2.10 pip install and code firstly. Then run the tf2.11 pip install and **restart the runtime in order to use newly installed versions**. And then run the code in tf2.11.

Thanks.

**Comment by LIONEFAN** [comment]
Hi @tilakrayal, can you reproduce this problem?

**Comment by tilakrayal** [comment]
@LIONEFAN,
Sorry for the delay. I tried on tensorflow v2.10 to reproduce the issue but I was not able to fetch the files which are mentioned. Kindly find the [gist](https://colab.research.google.com/gist/tilakrayal/a78bb5afe17b093e69cb489d2281cf12/2-1000000.ipynb) and the image for the reference.

![image](https://user-images.githubusercontent.com/81610181/208050074-5c7115bc-fdaf-47f1-b923-e989b9bb1877.png)

**Comment by LIONEFAN** [comment]
@tilakrayal,

I have run the gist you provided. But it told me an error about the RAM is ran out. Therefore, you can't eventually get the folder of **"plugins"** compared with your first running, because the program **stopped early.** 

I have turned down the size of training epochs from 10000 to 2000
`for _ in range(10000):` -> `for _ in range(2000):`
And  I got the expected results.

**So please you try it again to use following codes, thanks!**
BTW, I added an output to the last line to make sure we know that the program is fully executed.
```
import random
import tensorflow as tf
options = tf.profiler.experimental.ProfilerOptions(host_tracer_level = 3,
                                                   python_tracer_level = 1,
                                                   device_tracer_level = 1)
tf.profiler.experimental.start("logdir_simple_tf211(1)", options=options)

""" Simple training model """
def Y(a, x):
    return a*(x**2 + 4)

""" Target model """
def Z(a):
    return a*(4**2 + 4)

lr = 0.01
x = tf.Variable(1.1,name = 'var')
optimizer = tf.keras.optimizers.Adam(lr=0.01)

for _ in range(2000):
    input = random.randint(1,255)
    target = Z(input)
    with tf.GradientTape() as tape:
        pre = Y(input, x)
        loss = abs(pre - target)

    gradient = tape.gradient(loss,x)
    optimizer.apply_gradients([(gradient, x)])

    if _ % 100 == 0:
        print("loss:", loss.numpy())
        
print("x: ", x.numpy())
tf.profiler.experimental.stop(save=True)
print("End.")
```

**Comment by ztlevi** [comment]
Hi, we have same issue with 2.11 release. @cliveverghese Is there anything equalivant for trace.json. Is the data moved to `ip-xxx.xplane.pb` file?

**Comment by cliveverghese** [comment]
Hi, 

This behavior was updated as part of commit https://github.com/tensorflow/tensorflow/commit/52992fc29f00fc743e07e16067f6418af6c489ff to only save the xplane.pb file as the other files are derived from this. The results are now computed when viewing the analysis results on Tensorboard.  

You can view the trace and other tool results on Tensorboard with the [tensorboard-plugin-profile](https://pypi.org/project/tensorboard-plugin-profile/)[1]. 

Would you like to access the trace.json.gz directly? We would like to know more about your use case. 

1 : [Profiling on colab](https://colab.research.google.com/github/tensorflow/tensorboard/blob/master/docs/tensorboard_profiling_keras.ipynb#scrollTo=vUk1fuxADbxA)

**Comment by ztlevi** [comment]
We just try to figure out the changes for these trace data. Thanks for the reply

**Comment by LIONEFAN** [comment]
@cliveverghese 

Thanks for your reply. Now I can view the trace by using Tensorboard on tf 2.11.

But is there a way to directly generate the trace.json.gz on tf 2.11? Because in some case, I only want to focus on the timeline. And then I can load it in chrome://tracing directly.

**Comment by sachinprasadhs** [comment]
@LIONEFAN , as per the commit mentioned here  https://github.com/tensorflow/tensorflow/commit/52992fc29f00fc743e07e16067f6418af6c489ff, I don't think there is any workaround to generate trace.json.gz file other than the solution mentioned above. 
Even the Test cases has been moved out in the above change.
![image](https://user-images.githubusercontent.com/73069040/216196724-d631275c-b7e5-4fd3-988e-5ea74a3c4df3.png)

**Comment by LIONEFAN** [comment]
Thanks, I don't have any questions.
