### ISSUE TITLE
The input type of the tf.math.sqrt operator parameters does not match the exception information.

### ISSUE THREAD

**Issue by triumph-wangyuyang** [tensorflow/tensorflow#58739]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

TF 2.4

### Custom Code

Yes

### OS Platform and Distribution

windows 11

### Python version

3.8.15

### CUDA/cuDNN version

CUDA: 11.2    cuDNN 8.1

### GPU model and memory

RTX3060

### Current Behaviour?

```shell
In the official document, the input types of tf.math.sqrt operator parameters are bfloat16, half, float32, float64.. It can be seen that the above does not contain complex64 or complex128 types, but in the following test code, the exception thrown In the information, you can see that the input can be of type complex64 or complex128. It is hoped that the documentation can be modified or the exception information can be modified.
```

### Standalone code to reproduce the issue

```shell
    import tensorflow as tf

    input = "True"
    out = tf.math.sqrt(input)
    print(out)
```

### Relevant log output

```shell
tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of string is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]
```
</details>

**Comment by cantonios** [comment]
@triumph-wangyuyang feel free to create a pull request to update the documentation.  In most of these, it's just a matter of adding text to one of the python docstrings, e.g. [here](https://github.com/tensorflow/tensorflow/blob/abd266147c2e108796a5dbf28b0a8f16297bd98d/tensorflow/python/ops/math_ops.py#L333).

**Comment by bhack** [comment]
@cantonios one of these days it could be nice if we could directly generate these from the ops def GT.

**Comment by cantonios** [comment]
> @cantonios one of these days it could be nice if we could directly generate these from the ops def GT.

Yes, I know.  They are generated for some ops - just not ones that have their own python docstrings.  Otherwise, a check to detect when the docs are stale would be useful.

**Comment by triumph-wangyuyang** [comment]
> @triumph-wangyuyang feel free to create a pull request to update the documentation. In most of these, it's just a matter of adding text to one of the python docstrings, e.g. [here](https://github.com/tensorflow/tensorflow/blob/abd266147c2e108796a5dbf28b0a8f16297bd98d/tensorflow/python/ops/math_ops.py#L333).

Thank you for your reply. I will try to update the document in a few days. Should I update the official document with the exception information, or update the exception information with the document?

**Comment by cantonios** [comment]
@triumph-wangyuyang the exception information is auto-generated based on kernel registrations.  You'll need to update the python docstrings.

This kind of thing is bound to happen as people add new kernel registrations to support new types, but they don't update the python docs.

**Comment by triumph-wangyuyang** [comment]
> @triumph-wangyuyang the exception information is auto-generated based on kernel registrations. You'll need to update the python docstrings.
> 
> This kind of thing is bound to happen as people add new kernel registrations to support new types, but they don't update the python docs.

Ok, I've seen what you mean.

**Comment by sunny7712** [comment]
@triumph-wangyuyang I want to contribute to this issue. How do I check what all data types should be added to a particular function's docstring?

**Comment by sunny7712** [comment]
@bhack @cantonios Could you please tell me how to check what all data types should be added to a particular function's docstring?

**Comment by cantonios** [comment]
@sunny7712 looks like there's already a PR for it: #58765 

I think @triumph-wangyuyang was checking the exception information, but the types in general are also specified in the op definition, if you can link the python call directly to an op: https://github.com/tensorflow/tensorflow/blob/501dff79213799c15748c9f7348839de1ea8dbfa/tensorflow/core/ops/ops.pbtxt#L19

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
