### ISSUE TITLE
tensorboard HTTP 404 errors

### ISSUE THREAD

**Issue by apiszcz** [tensorflow/tensorflow#5873]
Observing the following, it seems chromedeveditor is obsolete, is there a recommended replacement library?

INFO:tensorflow:path ../external\core_overlay/core-overlay.html not found, sending 404
INFO:tensorflow:returning 404 to 127.0.0.1 for /core-overlay/core-overlay.html
INFO:tensorflow:path ../external\core_transition/core-transition-css.html not found, sending 404
INFO:tensorflow:returning 404 to 127.0.0.1 for /core-transition/core-transition-css.html
INFO:tensorflow:path ../external\core_media_query/core-media-query.html not found, sending 404
INFO:tensorflow:returning 404 to 127.0.0.1 for /core-media-query/core-media-query.html

**Comment by prb12** [comment]
Please can you provide the information requested in the issue reporting template.

**Comment by apiszcz** [comment]
NOTE: Only file GitHub issues for bugs and feature requests.  All other
topics will be closed.

For general support from the community, see [StackOverflow](
https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close
issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by
searching the web for your problem?

### Environment info
Operating System: Windows 10/64

Installed version of CUDA and cuDNN:
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
8.0, 5.1

If installed from binary pip package, provide:

1. A link to the pip package you installed:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#tensorflow

2. The output from `python -c "import tensorflow;
print(tensorflow.__version__)"`.
0.11.0





If installed from source, provide

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't
have time to read hundreds of lines of your code)


### What other attempted solutions have you tried?


### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by prb12** [comment]
@danmane I'm not sure I understand the bug report at all, but this is probably worth noting:
> Operating System: Windows 10/64

**Comment by apiszcz** [comment]
There appear to be certain JavaScript files required but missing when trying to use tensorboard on windows. Tensorboard supports the graph, however trying to viewi scalars cause the HTTP 404 messages.

**Comment by danmane** [comment]
@apiszcz Is TensorBoard working on Windows except for the console output?

**Comment by apiszcz** [comment]
The GRAPH of the network is fine.
The scalar displays are not working, i followed a few examples that are
supposed to work.
