### ISSUE TITLE
tf.tensor_scatter_nd_updat has different performance on CPU and GPU.

### ISSUE THREAD

**Issue by triumph-wangyuyang** [tensorflow/tensorflow#58748]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

TF 2.11

### Custom Code

Yes

### OS Platform and Distribution

windows 11

### CUDA/cuDNN version

CUDA: 11.2    cuDNN 8.1

### Current Behaviour?

```shell
tf.tensor_scatter_nd_updat has different performance on CPU and GPU.
```

### Standalone code to reproduce the issue

```shell
CPU code:
  import tensorflow as tf
  with tf.device('/CPU'):
    tensor = tf.random.uniform([1, 2, 3], dtype=tf.float32)
    indices = tf.random.uniform([3, 2], minval=-256, maxval=257, dtype=tf.int64)
    updates = tf.random.uniform([3, 3], dtype=tf.float32)
    out = tf.tensor_scatter_nd_update(tensor, indices, updates)
  print(out)


GPU code:
  import tensorflow as tf
  with tf.device('/GPU:0'):
    tensor = tf.random.uniform([1, 2, 3], dtype=tf.float32)
    indices = tf.random.uniform([3, 2], minval=-256, maxval=257, dtype=tf.int64)
    updates = tf.random.uniform([3, 3], dtype=tf.float32)
    out = tf.tensor_scatter_nd_update(tensor, indices, updates)
  print(out)
```

### Relevant log output

```shell
CPU result: InvalidArgumentError: {{function_node __wrapped__TensorScatterUpdate_device_/job:localhost/replica:0/task:0/device:CPU:0}} indices[0] = [-229, -237] does not index into shape [1,2,3] [Op:TensorScatterUpdate]


GPU result: tf.Tensor(
[[[0.88412964 0.6187128  0.3900485 ]
  [0.69401896 0.9752933  0.5505158 ]]], shape=(1, 2, 3), dtype=float32)
```
</details>

**Comment by triumph-wangyuyang** [comment]
The same problem exists with tf.scatter_nd.

CPU test：

    import tensorflow as tf
    with tf.device('/CPU'):
        indices = tf.random.uniform([35, 2], minval=-256, maxval=257, dtype=tf.int64)
        updates = tf.random.uniform([35, 768], dtype=tf.float32)
        shape = [1, 35, 768]
        out = tf.scatter_nd(indices, updates, shape)
    print(out)

GPU test：

    import tensorflow as tf
    with tf.device('/GPU:0'):
        indices = tf.random.uniform([35, 2], minval=-256, maxval=257, dtype=tf.int64)
        updates = tf.random.uniform([35, 768], dtype=tf.float32)
        shape = [1, 35, 768]
        out = tf.scatter_nd(indices, updates, shape)
    print(out)

**Comment by triumph-wangyuyang** [comment]
The same problem exists with tf.nn.embedding_lookup.

CPU test：

    import tensorflow as tf
    with tf.device('/CPU'):
        params = tf.random.uniform([3, 320], dtype=tf.float32)
        ids = tf.random.uniform([2], minval=-256, maxval=257, dtype=tf.int32)
        out = tf.nn.embedding_lookup(params=params, ids=ids)
    print(out)


GPU test：

    import tensorflow as tf
    with tf.device('/GPU:0'):
        params = tf.random.uniform([3, 320], dtype=tf.float32)
        ids = tf.random.uniform([2], minval=-256, maxval=257, dtype=tf.int32)
        out = tf.nn.embedding_lookup(params=params, ids=ids)
    print(out)

**Comment by triumph-wangyuyang** [comment]
The same problem exists with tf.metrics.SparseCategoricalCrossentropy.

CPU test:

    import tensorflow as tf
    with tf.device('/CPU'):
        arg_class = tf.metrics.SparseCategoricalCrossentropy()
        a = tf.random.uniform([2], minval=-256, maxval=257, dtype=tf.int64)
        b = tf.random.uniform([2, 3], dtype=tf.float64)
        out = arg_class(a, b)
    print(out)

GPU test:

    import tensorflow as tf
    with tf.device('/GPU:0'):
        arg_class = tf.metrics.SparseCategoricalCrossentropy()
        a = tf.random.uniform([2], minval=-256, maxval=257, dtype=tf.int64)
        b = tf.random.uniform([2, 3], dtype=tf.float64)
        out = arg_class(a, b)
    print(out)

**Comment by triumph-wangyuyang** [comment]
The same problem exists with tf.losses.SparseCategoricalCrossentropy

GPU test:

    import tensorflow as tf
    with tf.device('/CPU'):
        arg_class = tf.losses.SparseCategoricalCrossentropy(reduction="sum")
        a = [1, 3]
        b = [[1, -5, 0], [-6, 1, -1e+20]]
        out = arg_class(a, b)
    print(out)

GPU test:

    import tensorflow as tf  
    with tf.device('/GPU:0'):
        arg_class = tf.losses.SparseCategoricalCrossentropy(reduction="sum")
        a = [1, 3]
        b = [[1, -5, 0], [-6, 1, -1e+20]]
        out = arg_class(a, b)
    print(out)

**Comment by triumph-wangyuyang** [comment]
The same problem exists with tf.keras.metrics.SparseCategoricalCrossentropy

CPU test

    import tensorflow as tf
    with tf.device('/CPU'):
        m = tf.keras.metrics.SparseCategoricalCrossentropy(axis=0)
        a = tf.random.uniform([2], minval=-256, maxval=257, dtype=tf.int64)
        b = tf.random.uniform([3, 2], dtype=tf.float64)
        out = m(a, b)
    print(out)


GPU test:

    import tensorflow as tf
    with tf.device('/GPU:0'):
        m = tf.keras.metrics.SparseCategoricalCrossentropy(axis=0)
        a = tf.random.uniform([2], minval=-256, maxval=257, dtype=tf.int64)
        b = tf.random.uniform([3, 2], dtype=tf.float64)
        out = m(a, b)
    print(out)

**Comment by triumph-wangyuyang** [comment]
The same problem exists with tf.keras.losses.SparseCategoricalCrossentropy.

CPU test:

    import tensorflow as tf
    with tf.device('/CPU'):
        reduction = "none"
        arg_class = tf.keras.losses.SparseCategoricalCrossentropy(reduction="none")
        a = [-1, 2]
        b = [[1.0, 25.95, -16], [60.1, 3.8, 6.1]]
        out = arg_class(a, b)
    print(out)



GPU test:

    import tensorflow as tf
    with tf.device('/GPU:0'):
        reduction = "none"
        arg_class = tf.keras.losses.SparseCategoricalCrossentropy(reduction="none")
        a = [-1, 2]
        b = [[1.0, 25.95, -16], [60.1, 3.8, 6.1]]
        out = arg_class(a, b)
    print(out)

**Comment by triumph-wangyuyang** [comment]
The same problem exists with tf.keras.layers.MaxPool1D

CPU test:

    import tensorflow as tf
    with tf.device('/CPU'):
        m = tf.keras.layers.MaxPool1D(trainable=True, dtype="float32", strides=[2], pool_size=[2], padding="valid",
                                      data_format="channels_first")
        input = tf.random.uniform([2, 2, 6], dtype=tf.float32)
        out = m(input)



GPU test:

    import tensorflow as tf
    with tf.device('/GPU:0'):
        m = tf.keras.layers.MaxPool1D(trainable=True, dtype="float32", strides=[2], pool_size=[2], padding="valid",
                                      data_format="channels_first")
        input = tf.random.uniform([2, 2, 6], dtype=tf.float32)
        out = m(input)

**Comment by triumph-wangyuyang** [comment]
The same problem exists with tf.keras.layers.Convolution1DTranspose

CPU test:

    import tensorflow as tf
    with tf.device('/CPU'):
        arg_class = tf.keras.layers.Convolution1DTranspose(trainable=True, batch_input_shape=[2, 6, 3], dtype="float32",
                                                           filters=4, kernel_size=[3], strides=[2], padding="valid",
                                                           data_format="channels_last", dilation_rate=[2], groups=1,
                                                           activation="linear", use_bias=True)
        input = tf.random.uniform([1, 6, 3], dtype=tf.float32)
        out = arg_class(input)
    print(out)

GPU test:

    import tensorflow as tf
    with tf.device('/GPU:0'):
        arg_class = tf.keras.layers.Convolution1DTranspose(trainable=True, batch_input_shape=[2, 6, 3], dtype="float32",
                                                           filters=4, kernel_size=[3], strides=[2], padding="valid",
                                                           data_format="channels_last", dilation_rate=[2], groups=1,
                                                           activation="linear", use_bias=True)
        input = tf.random.uniform([1, 6, 3], dtype=tf.float32)
        out = arg_class(input)
    print(out)

**Comment by triumph-wangyuyang** [comment]
The same problem exists with tf.keras.layers.AvgPool1D

CPU test:

    import tensorflow as tf
    with tf.device('/CPU'):
        m = tf.keras.layers.AvgPool1D(data_format="channels_first")
        input = tf.random.uniform([2, 2, 6], dtype=tf.float32)
        out = m(input)

GPU test:

    import tensorflow as tf
    with tf.device('/GPU:0'):
        m = tf.keras.layers.AvgPool1D(data_format="channels_first")
        input = tf.random.uniform([2, 2, 6], dtype=tf.float32)
        out = m(input)

**Comment by triumph-wangyuyang** [comment]
The same problem exists with tf.random.uniform.

CPU test:

    import tensorflow as tf
    with tf.device('/CPU'):
        m = tf.keras.layers.AveragePooling1D(data_format="channels_first")
        input = tf.random.uniform([3, 2, 6], dtype=tf.float32)
        out = m(input)

GPU test:

    import tensorflow as tf
    with tf.device('/GPU:0'):
        m = tf.keras.layers.AveragePooling1D(data_format="channels_first")
        input = tf.random.uniform([3, 2, 6], dtype=tf.float32)
        out = m(input)

**Comment by triumph-wangyuyang** [comment]
The same problem exists with tf.random.uniform

CPU test:

    import tensorflow as tf
    with tf.device('/CPU'):
        a = tf.random.uniform([1, 35, 12, 64], dtype=tf.float32)
        b = tf.random.uniform([5, 1], minval=-256, maxval=257, dtype=tf.int64)
        out = tf.gather_nd(a, b)

GPU test:

    import tensorflow as tf
    with tf.device('/GPU:0'):
        a = tf.random.uniform([1, 35, 12, 64], dtype=tf.float32)
        b = tf.random.uniform([5, 1], minval=-256, maxval=257, dtype=tf.int64)
        out = tf.gather_nd(a, b)

**Comment by mohantym** [comment]
Hi @triumph-wangyuyang !
Thanks for sharing your observations. 

@SuryanarayanaY !
Could you look at this issue.

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @ triumph-wangyuyang,
Thanks for bringing this to our notice.

I tried in TF 2.11V also and the behaviour is same as you mentioned and attached [gist-2.11v](https://colab.research.google.com/gist/SuryanarayanaY/afdc99e1450acce87c00e30581af176e/58748-2-11.ipynb) here for checking same.

I tried to replicate in `nightly(2.12.0-dev20221206)` version also and observed some differences as per attached [gist-nightly](https://colab.research.google.com/gist/SuryanarayanaY/d5e4a120e3cc52732c479341ee348318/58748-nightly-2-12.ipynb) here.

```
1. tf.tensor_scatter_nd_update() - replicated same behaviour (CPU: InvalidArgumentError, GPU:No Error)
2. tf.scatter_nd() - replicated same behaviour (CPU: InvalidArgumentError, GPU:No Error)
3. tf.nn.embedding_lookup() -replicated same behaviour (CPU: InvalidArgumentError, GPU:No Error)
4. tf.metrics.SparseCategoricalCrossentropy() - replicated same behaviour (CPU: InvalidArgumentError, GPU:No Error)
5. tf.metrics.sparse_categorical_crossentropy() -replicated same behaviour (CPU: InvalidArgumentError, GPU:No Error)
6. tf.losses.SparseCategoricalCrossentropy() - replicated same behaviour (CPU: InvalidArgumentError, GPU:No Error)
7. tf.keras.losses.sparse_categorical_crossentropy() - replicated same behaviour (CPU: InvalidArgumentError, GPU:No Error)
8. tf.keras.layers.MaxPooling1D() - Different behaviour (CPU:Invalid Argument error ,GPU:UnimplementedError)
9. tf.keras.layers.MaxPool1D() -  Different behaviour (CPU:Invalid Argument error ,GPU:UnimplementedError)
10. tf.keras.layers.Convolution1DTranspose() - Different behaviour (CPU:Invalid Argument error ,GPU:UnimplementedError)
11. tf.keras.layers.AvgPool1D() - Different behaviour (CPU:Invalid Argument error ,GPU:UnimplementedError)
12. tf.keras.layers.AveragePooling1D() - Different behaviour (CPU:Invalid Argument error ,GPU:UnimplementedError)
```

There is differences in behaviour for the Ops from S.No.8 to 12 from 2.11V to nightly.

Could you please cross check in nightly once again for the Ops S.No.8 to 12 and confirm us?

Thankyou!

**Comment by SuryanarayanaY** [comment]
@sachinprasadhs , could you please look at the issue and do needful.
Thanks!

**Comment by sachinprasadhs** [comment]
Hi, Thanks for your detailed investigation on the OPS, the validation check failure on GPU could be intended behavior, since we don't explicitly do validation checks in most of the cases since it impact the performance. 
We have documented this behavior in some cases like here https://www.tensorflow.org/api_docs/python/tf/gather#args.

**Comment by cantonios** [comment]
Correct, we don't do index validation on GPU - instead we simply ignore bad indices.
