### ISSUE TITLE
TF-lite model with a Conv2DTranspose layer is fail to run on mobile gpu.

### ISSUE THREAD

**Issue by jyh2378** [tensorflow/tensorflow#58746]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 
  - Conversion env: Centos7
  - Test env: Galaxy S10 `(samsung/beyond1lteks/beyond1:10/QP1A.190711.020/G973NKSU4CTE9:user/release-keys)`
- TensorFlow installation (pip package or built from source): pip install
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.10.0

### 2. Code

Provide code to help us reproduce your issues using one of the following options:
```
def get_model():
    inputs = tf.keras.Input(shape=(64, 64, 3))
    x = keras.layers.Conv2D(16, 3, activation="relu", name="conv1")(inputs)
    x = keras.layers.Conv2D(16, 3, activation="relu", name="conv2")(x)
    x = keras.layers.Conv2DTranspose(16, 3, strides=2, activation="relu", name="deconv1")(x)
    x = keras.layers.Conv2DTranspose(16, 3, strides=2, activation="relu", name="deconv2")(x)
    outputs = x
    
    model = keras.Model(inputs=inputs, outputs=outputs, name="custom")

    x = tf.ones((5, 64, 64, 3))
    y = model(x)

    print(x.shape)
    print(y.shape)
    
    return model

def convert_model(saved_model_dir, tflite_save_dir):
    converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_types = [tf.float32]
    tflite_model = converter.convert()

    with open(tflite_save_dir, "wb") as f:
        f.write(tflite_model)

if __name__=="__main__":
    model = get_model()

    current_path = os.path.dirname(os.path.realpath(__file__))
    save_dir = os.path.join(current_path, "custom/1/")
    tf.saved_model.save(model, save_dir)

    tflite_save_dir = os.path.join(current_path, "my_model.tflite")
    convert_model(save_dir, tflite_save_dir)
    test_tflite(tflite_save_dir)
```

### 3. Failure after conversion
TF Lite conversion and run on the mobile phone with cpu is OK, but when running with gpu, an error occurs. (I tested the model in adb shell)
![image](https://user-images.githubusercontent.com/33739495/205008146-3abb7c7e-9fea-4361-88cb-a110b6ca1aaa.png)

**Comment by jyh2378** [comment]
## Reproducible example
- tflite model: [my_model.tflite](https://drive.google.com/file/d/1UHZhc7Oc7KuBOPghSzi9Ga8lskd83U4Z/view?usp=sharing)
- asset: [libc++_shared.so](https://drive.google.com/file/d/10xqlfnqGH-hsrhZVIBN_4amUey7414Vx/view?usp=sharing)
- test_executable_file: [optflow.out](https://drive.google.com/file/d/1QL1DXFq-IdJrp0nBFWQqKNA_xr-s8cJF/view?usp=sharing)

As I mentioned, I tested tflite model on adb shell.
1. Prepare the `my_model.tflite` and `optflow.out`.
2. (When linking the Galaxy S10 device) `adb push my_model.tflite /data/local/tmp`
3. `adb push optflow.out /data/local/tmp`
4. `adb push libc++_shared.so /data/local/tmp`
5. `adb shell` and `cd /data/local/tmp`
6. `export LD_LIBRARY_PATH=./`
7. `chmod 777 optflow.out`
8. `./optflow.out -m my_model.tflite -g 1`

**Comment by jyh2378** [comment]
I found that `tf.compat.v1.layers.conv2d_transpose` works well, but `tf.keras.` don't.
#### tensorflow to tflite conversion code

```
import os

import numpy as np
import tensorflow as tf
import tensorflow.keras as keras

tfv1 = tf.compat.v1


def generate_tflite_model(save_root_dir):
    #### model define ###
    inputs = tf.keras.Input(shape=(64, 64, 3))
    x = keras.layers.Conv2DTranspose(3, 3, strides=2, activation="relu", padding="same", name="deconv1")(inputs)
    outputs = x

    model = keras.Model(inputs=inputs, outputs=outputs, name="custom")

    x = tf.ones((1, 64, 64, 3))
    y = model(x)

    print(x.shape)
    print(y.shape)
    
    ### save as saved_model
    saved_model_dir = os.path.join(save_root_dir, "custom/")
    tf.saved_model.save(model, saved_model_dir)

    ### convert tflite model ###
    converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
    # converter.optimizations = [tf.lite.Optimize.DEFAULT]
    # converter.target_spec.supported_types = [tf.float32]
    tflite_model = converter.convert()

    tflite_save_dir = os.path.join(save_root_dir, "my_model.tflite")
    with open(tflite_save_dir, "wb") as f:
        f.write(tflite_model)

    return


def generate_tflite_model_from_v1(save_root_dir):

    tflite_save_dir = os.path.join(save_root_dir, "my_model_tfv1.tflite")

    with tf.Graph().as_default() as graph:

        inputs = tfv1.placeholder(tf.float32, shape=[1, 64, 64, 3])
        x = tfv1.layers.conv2d_transpose(inputs, 3, 3, strides=2, padding="same", name="deconv1")
        out = tf.nn.relu(x)

        with graph.as_default(), tfv1.Session(graph=graph) as session:
            session.run(tfv1.global_variables_initializer())
            converter = tfv1.lite.TFLiteConverter.from_session(
                session, input_tensors=[inputs], output_tensors=[out])

            with open(tflite_save_dir, "wb") as f:
                f.write(converter.convert())

    return 


if __name__=="__main__":
    current_path = os.path.dirname(os.path.realpath(__file__))
    tflite_save_dir = generate_tflite_model(current_path)
    # tflite_save_dir = generate_tflite_model_from_v1(current_path)
```
I would like to know why this difference exists.
Below is the graph of gererated models.
model.tflite graph | my_model_tfv1.tflite graph
-- | --
![image](https://user-images.githubusercontent.com/33739495/206659639-e2943c53-7f11-49ca-a171-3c01bd225e8d.png) | ![image](https://user-images.githubusercontent.com/33739495/206659716-89a78579-88e1-4003-9888-29e0275bd3a3.png)

**Comment by roserg** [comment]
Conv2DTranspose supported on gpu.
Not supported Pack and Shape that you have in the first case.

**Comment by jyh2378** [comment]
@roserg Thank you for answer.
How can I only use Conv2DTranspose layer without Pack and Shape operation in TF2? As you can see, I created graph only has `keras.layers.Conv2DTranspose` layer but converted graph has Shape and Pack op automatically.

**Comment by pkgoogle** [comment]
Hi @jyh2378, we only currently support static batch sizes (or static shapes in general), as such your solution is the right solution for your case. Do you have any more open items for this issue?
