### ISSUE TITLE
tflite build for armhf crashes in 2.10 and 2.11

### ISSUE THREAD

**Issue by paulhfu** [tensorflow/tensorflow#58745]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04.4 LTS
-   **TensorFlow installed from (source or binary)**: From Source
-   **TensorFlow version (use command below)**: 2.11 and 2.10
-   **Python version**: 3.9.12
-   **Bazel version (if compiling from source)**:5.3.0 (for TF 2.11) and 5.1.1 (for TF 2.10)
-   **GCC/Compiler version (if compiling from source)**:arm-linux-gnueabihf-gcc 8.3.0
-   **CUDA/cuDNN version**: not applicable
-   **GPU model and memory**:not applicable
-   **Exact command to reproduce**:bazel  build --config=elinux_armhf -c opt //tensorflow/lite:libtensorflowlite.so

### Describe the problem
During compilation of tflite, the XNNPACK build fails with *error: unknown type name 'int8x4_t'* and more of similar errors.
*-mfp16-format=ieee* is included in the compile command. This happens with tensorflow 2.10 and 2.11.
The compiler call issued by bazel is:
/home/user/.cache/bazel/_bazel_user/4e14a0b2593db001fc575b67dfb5d02a/external/armhf_linux_toolchain/bin/arm-linux-gnueabihf-gcc -fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/armhf-opt/bin/external/XNNPACK/_objs/armsimd32_prod_microkernels/0/1x2c4-minmax-fp32-armsimd32.pic.d '-frandom-seed=bazel-out/armhf-opt/bin/external/XNNPACK/_objs/armsimd32_prod_microkernels/0/1x2c4-minmax-fp32-armsimd32.pic.o' -fPIC -iquote external/XNNPACK -iquote bazel-out/armhf-opt/bin/external/XNNPACK -isystem external/XNNPACK/include -isystem bazel-out/armhf-opt/bin/external/XNNPACK/include -isystem external/XNNPACK/src -isystem bazel-out/armhf-opt/bin/external/XNNPACK/src -Wno-all -Wno-extra -Wno-deprecated -Wno-deprecated-declarations -Wno-ignored-attributes -Wno-unknown-warning -Wno-array-parameter -Wno-stringop-overflow -Wno-array-bounds -Wunused-result '-Werror=unused-result' -DAUTOLOAD_DYNAMIC_KERNELS '-mfp16-format=ieee' -Iinclude -Isrc -marm '-march=armv6' '-mfpu=vfp' -munaligned-access '-std=c99' -fno-fast-math -fno-math-errno -O2 -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -no-canonical-prefixes -fno-canonical-system-headers -c external/XNNPACK/src/qc8-gemm/gen/1x2c4-minmax-fp32-armsimd32.c -o bazel-out/armhf-opt/bin/external/XNNPACK/_objs/armsimd32_prod_microkernels/0/1x2c4-minmax-fp32-armsimd32.pic.o

**Comment by mohantym** [comment]
Hi @paulhfu !
Sorry for the late reply.

I think the correct command would be.
`bazel build --config=elinux_armhf -c opt //tensorflow/lite/c:libtensorflowlite_c.so`

Seems to be passing with Master branch and bazel 5.3.0 with above command. Attached [gist](https://colab.sandbox.google.com/gist/mohantym/f7e8c5f9bac9c19e85928b21a9db1d32/tensorflow-ranking.ipynb#scrollTo=DtEuxvobaRf5) for reference.
Could you let us know from your end.

Thank you!

**Comment by terryheo** [comment]
This issue looks the same with https://github.com/tensorflow/tensorflow/issues/57364
It's fixed recently with a toolchain update. https://github.com/tensorflow/tensorflow/pull/57585

**Comment by terryheo** [comment]
FYI, if you want to build 2.10, 2.11 you need to disable XNNPACK with `--define=tflite_with_xnnpack=false`
