### ISSUE TITLE
Tensorflow Lite Benchmark tool possible error when specifing input_layer_value_files

### ISSUE THREAD

**Issue by pfk-beta** [tensorflow/tensorflow#58741]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9

### Custom Code

No

### OS Platform and Distribution

linux

### Mobile device

android

### Current Behaviour?

I would like to use benchmark tool, to see the results of inference. So there is an option to specify `input_layer_value_files` and `output_filepath`. When there is one input, it is easy. Problems are, when there are multiple inputs, and you cannot fully control input names, e.g. you need to escape. I think I escaped names, but I'm getting error:

```
Wrong input value file item specified: serving_default_input0\:0:/data/local/tmp/benchmarkomat/tflite/inferences/input__serving_default_input0__0_KYO5LZFG6A.bin
```

my command:

```
/data/local/tmp/tflite/execs/tflite_benchmark --graph=/data/local/tmp/tflite/models/5IZY3TP8V6_model.tflite --input_layer_value_files='serving_default_input0\:0':'/data/local/tmp/tflite/inferences/input__serving_default_input0__0_KYO5LZFG6A.bin','serving_default_input1\:0':'/data/local/tmp/tflite/inferences/input__serving_default_input1__0_KYO5LZFG6A.bin','serving_default_input2\:0':'/data/local/tmp/tflite/inferences/input__serving_default_input2__0_KYO5LZFG6A.bin' --output_filepath=/data/local/tmp/tflite/inferences/output__KYO5LZFG6A.bin
```

Similar problem, when I'm not using single quotes around key and value:
```shell
/data/local/tmp/tflite/execs/tflite_benchmark --graph=/data/local/tmp/tflite/models/3LMD92WLNY_model.tflite --input_layer_value_files=serving_default_input0\:0:/data/local/tmp/tflite/inferences/input__serving_default_input0__0_C3FB3DNGK8.bin,serving_default_input1\:0:/data/local/tmp/tflite/inferences/input__serving_default_input1__0_C3FB3DNGK8.bin,serving_default_input2\:0:/data/local/tmp/tflite/inferences/input__serving_default_input2__0_C3FB3DNGK8.bin --output_filepath=/data/local/tmp/tflite/inferences/output__C3FB3DNGK8.bin --use_xnnpack=false --use_nnapi=false --use_gpu=false --use_hexagon=false --gpu_precision_loss_allowed=true
```

### Standalone code to reproduce the issue

```shell
Code to create simple model:

import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

print(tf.__version__)
input0 = keras.Input(shape=(64,), name="input0") 
input1 = keras.Input(shape=(16,), name="input1")
input2 = keras.Input(shape=(16,), name="input2")

layer0 = layers.Dense(3, activation="relu", name="layer0")(input0)
layer1 = layers.Dense(5, activation="relu", name="layer1")(input1)
layer2 = layers.Dense(7, activation="relu", name="layer2")(input2)

x0 = layers.concatenate([layer0, layer1, layer2])
x1 = layers.concatenate([layer0, layer1, layer2])

x0 = layers.Dense(3, name="output0")(x0)
x1 = layers.Dense(7, name="output1")(x1)

# Instantiate an end-to-end model predicting both priority and department
model = keras.Model(
    inputs=[input0, input1, input2],
    outputs=[x0, x1],
)
model.compile(optimizer='sgd', loss='mean_squared_error')
model.summary()

converter = tf.lite.TFLiteConverter.from_keras_model(model) # path to the SavedModel directory
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

with open('model.tflite', 'wb') as f:
    f.write(tflite_model)
```

### Relevant log output

_No response_</details>

**Comment by pfk-beta** [comment]
Do I need to specify shapes as well?

**Comment by pfk-beta** [comment]
Ok, so I have read source code: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/benchmark_tflite_model.cc#L314

It looks like, documentation is different than source code, or someone has made a mistake. In command description is written: "espace colon with backslash", but in source code "colon is escaped with colon".

**Comment by pfk-beta** [comment]
Then you may need to specify input layers in second argument. Issue can be closed.

**Comment by mohantym** [comment]
@pfk-beta !
Thanks for sharing your observation!

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by pjpratik** [comment]
Hi @pfk-beta

The documentation is now fixed with the commit https://github.com/tensorflow/tensorflow/commit/0502855512e5f52f4db6360c7dfd3fcf19a0fba3.  Please refer to the updated [documentation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/README.md#model-input-parameters) and let us know if it is resolved.

Thanks.

**Comment by pfk-beta** [comment]
LGTM, issue can be closed:)

**Comment by pjpratik** [comment]
Thanks for the confirmation.
