### ISSUE TITLE
Enabling tf.function(jit_compile=True) causes inconsistent results

### ISSUE THREAD

**Issue by YaoJiayi** [tensorflow/tensorflow#58752]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8.8

### CUDA/cuDNN version

CUDA 11.4

### Current Behaviour?

```shell
Executing the following code snippet with and without tf.function produces inconsistent results.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

def main_jit():
  class my_mod(tf.Module):
    def __init__(self,name=None):
      super().__init__(name=name)
    @tf.function(jit_compile=True)
    def __call__(self):
      Input_0 = tf.random.stateless_uniform([2,],seed=(1, 2) ,minval=-5, maxval=5, dtype=tf.float64)
      cosh3 = tf.math.cosh(Input_0)
      cosh6 = tf.math.cosh(cosh3)
      tan11 = tf.math.tan(cosh6)
      return tan11
  mod = my_mod()
  res = mod()
  return res

def main():
  class my_mod(tf.Module):
    def __init__(self,name=None):
      super().__init__(name=name)
    def __call__(self):
      Input_0 = tf.random.stateless_uniform([2,],seed=(1, 2) ,minval=-5, maxval=5, dtype=tf.float64)
      cosh3 = tf.math.cosh(Input_0)
      cosh6 = tf.math.cosh(cosh3)
      tan11 = tf.math.tan(cosh6)
      return tan11
  mod = my_mod()
  res = mod()
  return res

res_jit = main_jit()
res = main()

np_res = np.allclose(res_jit.numpy(),res.numpy(),rtol=1e-1, atol=1e-3, equal_nan=True)
print(res_jit.numpy()-res.numpy())
print(np_res)
```

**Comment by mohantym** [comment]
Hi @YaoJiayi !
Thanks for reporting this bug.

I could replicate this in-consistency in GPU mode , It is giving same results for CPU mode.
Working around is enable XLA thorough Auto-clustering (2nd code block- Assignee suggested in below gists)

@SuryanarayanaY 
Could you look at this bug.
Attached gist in [2.8](https://colab.sandbox.google.com/gist/mohantym/fd0daa4e4297fd3c55dd9c94c2ce22ad/git_58752.ipynb), [2.9](https://colab.sandbox.google.com/gist/mohantym/f571543c40bd611f4d5d3ee016d8d271/git_58752.ipynb), [2.10](https://colab.sandbox.google.com/gist/mohantym/4a607205960cdf648533042234374086/git_58752.ipynb) and [nightly ](https://colab.sandbox.google.com/gist/mohantym/80818d942a40a1d05bf7c3799b4e82a3/git_58752.ipynb#scrollTo=YNGpdEbhu4Qh)for reference.
Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @YaoJiayi ,
Sorry for delayed response.
The API `tf.random.stateless_uniform` for `float` dtypes seems working fine with the default range [0,1) only. Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/6784c0a6b2ae5936faea3e1106d99e2a/58752-gpu.ipynb).
