### ISSUE TITLE
Re-creation of old environment with TF 1.0.1 leads to "No module named _pywrap_tensorflow" issue

### ISSUE THREAD

**Issue by JensWendt** [tensorflow/tensorflow#58757]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

1.0.1

### Custom Code

No

### OS Platform and Distribution

Windows 10 , 64-bit

### Python version

2.7.18

### CUDA/cuDNN version

8.0.61 / 5.1

### GPU model and memory

RTX A 2000 (Laptop GPU) ; 4GB

### Current Behaviour?

Basically I try to re-create an old environment to re-use a scientific publication (https://github.com/okraus/DeepLoc).
I install CUDA 8 and CUDNN 5.1 according to various step-by-step tutorials (primarily https://shawnhymel.com/1961/how-to-install-tensorflow-with-gpu-support-on-windows/#Install_cuDNN).
(I keep the current up to date graphics card driver.)
I then install `tensorflow_gpu-1.0.1-py2-none-any.whl` which I found somewhere in the depths of the net after some research.
Unfortunately even the simple `import tensorflow` will give the error message below.
I have been through various github/stackoverflow issues/threads and cannot find the solution to this.
(relevant) System variables:
```
CUDA_PATH_V8_0 = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
CUDA_PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0 (just to be safe)
PATH = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin ; C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp
```

Regarding the `MSVCP140.DLL` suggestion:
```
(DeepLoc) C:\Users\Jens>where MSVCP140.DLL
C:\Windows\System32\msvcp140.dll
C:\Program Files\HDF_Group\HDF5\1.8.22\bin\msvcp140.dll
C:\ProgramData\Anaconda3\msvcp140.dll
C:\Program Files\Java\jdk-19\bin\msvcp140.dll
```
And I have the `Microsof Visual C++ 2015-2022 Redistributable (x64) - 14.32.31326`, which is the reason - I assume - that I cannot install the Redistributable referenced here https://github.com/tensorflow/tensorflow/issues/8385#issuecomment-286621655

I have no more sensible ideas to try out.
Even though this is one of your first versions and I understand this is not a top priority I would still greatly appreciate any kind of help!

Best,

Jens
```


### Standalone code to reproduce the issue

python
import tensorflow
```

### Relevant log output

```shell
(DeepLoc) C:\Users\Jens>python
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 17:26:54) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> print(os.environ.get('CUDA_PATH'))
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
>>> import tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tf
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jens\.conda\envs\DeepLoc\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\Jens\.conda\envs\DeepLoc\lib\site-packages\tensorflow\python\__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Jens\.conda\envs\DeepLoc\lib\site-packages\tensorflow\python\__init__.py", line 66, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Jens\.conda\envs\DeepLoc\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "C:\Users\Jens\.conda\envs\DeepLoc\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ImportError: No module named _pywrap_tensorflow


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error
```
</details>

**Comment by tilakrayal** [comment]
@JensWendt,
Tensorflow version 1.x is  no longer supported. Hence, kindly update to the latest stable version 2.11 and let us know if you are facing the same issue. Thank you!
