### ISSUE TITLE
AvgPool3D throws if filter size is larger than input size

### ISSUE THREAD

**Issue by Linchenn** [tensorflow/tensorflow#58758]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

MacBook Pro 2019

### Current Behaviour?

```shell
For `AvgPool3D`, if filter size is larger than the tensor size, an error was thrown. Take my code below for example, should `y` be returned with a shape `[1,1,1,0,1]`?
```

### Standalone code to reproduce the issue

```shell
x = tf.ones([1,1,1,1,1],float)
y = tf.raw_ops.AvgPool3D(input=a, ksize=[1,1,1,3,1],strides=[1,1,1,1,1], padding='VALID')
```

### Relevant log output

```shell
2022-12-01 13:27:33.388230: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at pooling_ops_3d.cc:188 : INVALID_ARGUMENT: Computed output size would be negative: -1 [input_size: 1, effective_filter_size: 3, stride: 1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/linchan/miniconda3/lib/python3.9/site-packages/tensorflow/python/util/tf_export.py", line 412, in wrapper
    return f(**kwargs)
  File "/Users/linchan/miniconda3/lib/python3.9/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 342, in avg_pool3d
    _ops.raise_from_not_ok_status(e, name)
  File "/Users/linchan/miniconda3/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 7215, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__AvgPool3D_device_/job:localhost/replica:0/task:0/device:CPU:0}} Computed output size would be negative: -1 [input_size: 1, effective_filter_size: 3, stride: 1] [Op:AvgPool3D]
```
```
</details>

**Comment by Linchenn** [comment]
I mean, over [here](https://github.com/tensorflow/tensorflow/blob/565ba45dfefc056b694e641a1db29ca2a7f4d7f4/tensorflow/core/framework/kernel_shape_util.cc#L36), maybe TensorFlow has to consider the case that filter size is larger than input size.

**Comment by mohantym** [comment]
Hi @Linchenn !
Thanks for sharing your observation on AvgPool3D with respect to Invalid filter size.

@sushreebarsa !
Could you look at this issue. Attached gist in  [2.10](https://colab.sandbox.google.com/gist/mohantym/fdd0f25c166c0437cc3b21e522aef4e8/git_58758.ipynb#scrollTo=0jwQwd9zgHn2), [2.11 ](https://colab.sandbox.google.com/gist/mohantym/2851feb6d10e38865ad9202fb387096e/git_58758.ipynb#scrollTo=2pkZmQLIgLhf)and [nightly ](https://colab.sandbox.google.com/gist/mohantym/e9cbb7fac5a32f6fe7f5752d685bb794/git_58758.ipynb#scrollTo=uWfqOXZVgwEa)for reference.

Thank you!

**Comment by sachinprasadhs** [comment]
Generally, filter size should not be larger than the input size. 
The desired output which you are expecting `[1,1,1,0,1]` is possible on the below condition.
```
import tensorflow as tf
print(tf.__version__)
x = tf.ones([1,1,1,1,1],float)
y = tf.nn.avg_pool3d(input=x, ksize=[1,1,1,2,1],strides=[1,1,1,1,1], padding='VALID')
```

Here, as per the below equation, given the `input_size = 1, effective_filter_size =2, stride = 1
`
```
output_size = (input_size - effective_filter_size + stride) / stride
output_size = (1 - 2 + 1) /1 = 0

```

With the error which you are receiving, the output size would become negative and the proper error message is thrown.
`output_size = (1 - 3 + 1) /1 = -1`
I'm not sure how feasible it would be to add one more case to accept filter size larger than input size.

**Comment by cantonios** [comment]
This is behaving as expected.  There isn't enough input data to satisfy any "valid" pooling region without padding, so there's nothing that can be done.  If you want padding, it needs to be specific in the input parameters by setting `padding=SAME'.
