### ISSUE TITLE
To use the argument `sampling_rate`, you should install tensorflow_io. You can install it via `pip install tensorflow-io`

### ISSUE THREAD

**Issue by SajjadAemmi** [tensorflow/tensorflow#58762]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.11

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu

### Mobile device

22.04

### Python version

3.10

### Current Behaviour?

```shell
A bug happened!
i installed tensorflow-io, but i see this error again:

ImportError: To use the argument `sampling_rate`, you should install tensorflow_io. You can install it via `pip install tensorflow-io`.
```
```


### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.keras.utils import audio_dataset_from_directory

dataset = audio_dataset_from_directory(
    "dataset",
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    batch_size=1,
    sampling_rate=16000,
    output_sequence_length=100,
    ragged=False,
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    follow_links=False,
)
```
```


### Relevant log output

```shell
File ~/.local/lib/python3.10/site-packages/keras/utils/audio_dataset.py:172, in audio_dataset_from_directory(directory, labels, label_mode, class_names, batch_size, sampling_rate, output_sequence_length, ragged, shuffle, seed, validation_split, subset, follow_links)
    166         raise ValueError(
    167             "`sampling_rate` should be higher than 0. "
    168             f"Received: sampling_rate={sampling_rate}"
    169         )
...
    176         )
    178 if labels is None or label_mode is None:
    179     labels = None

ImportError: To use the argument `sampling_rate`, you should install tensorflow_io. You can install it via `pip install tensorflow-io`.
```
</details>

**Comment by krrishdholakia** [comment]
Hmm, you can try installing the Tensorflow-IO library via pip install tensorflow-io (as noted in the error). Alternatively, I think? you can also try setting the 'sampling_rate' argument to 0, as this will force Keras to use the default sampling rate.

Used Clerkie (ai code debugging tool) - https://clerkie.co/, to help me brainstorm on approaches here (still reviewed/investigated feedback before sharing). Hope it helped!
<img width="1524" alt="Screen Shot 2022-12-13 at 1 18 40 PM" src="https://user-images.githubusercontent.com/17561003/207256839-84a87463-d48d-407b-95c0-4a0e9bdab4bb.png">

**Comment by SajjadAemmi** [comment]
@krrishdholakia  i installed Tensorflow-IO, but same error

**Comment by sushreebarsa** [comment]
@SuryanarayanaY I was able to replicate this issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/a1d979730dd181f2ec56a21ac66ce5b1/untitled766.ipynb#scrollTo=b5aU8EL8-iBq) here.
Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @SajjadAemmi ,

The Error coming from this piece of [code](https://github.com/keras-team/keras/blob/r2.11/keras/utils/audio_dataset.py#L171-176).

It is expecting `tensorflow_io` imported as `tfio`.
Could you try adding the import statement like below and confirm whether it works for you ?

`import tensorflow_io as tfio
`

**Comment by SajjadAemmi** [comment]
Hi @SuryanarayanaY 
i import tensorflow_io, but i have same error

![image](https://user-images.githubusercontent.com/42681293/224332891-1ba72ff8-78b7-4928-bf46-80a3257cb63e.png)

**Comment by SuryanarayanaY** [comment]
Hi @SajjadAemmi ,

It seems the version compatibility between tensorflow and tensorflow-io causing the problem.
Can you try installing tensorflow-io alongwith its compatible tensorflow using the below code.

`!pip install tensorflow-io[tensorflow]`

For me the reported Import error gone with above installation code.Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/ad1c1c1af38ca6c5a6a80805751426cb/58762_r2.ipynb).

**Comment by SajjadAemmi** [comment]
Thanks @SuryanarayanaY , it works for me 💪🏻

**Comment by SuryanarayanaY** [comment]
@SajjadAemmi ,

Glad that it works for you. Please feel free to close the issue. Thanks!
