### ISSUE TITLE
TFLite Model Maker changes the order of the outputs for object detection

### ISSUE THREAD

**Issue by krunalvaghani** [tensorflow/tensorflow#58764]
### 1. System information

- Linux Ubuntu 18.04 as Windows subsystem for linux
- TensorFlow installation (pip package or built from source): 2.8.0
- TensorFlow Lite Model maker(0.4.2) installation: Installed all the requirements from [Github repo](https://github.com/tensorflow/examples/blob/master/tensorflow_examples/lite/model_maker/requirements.txt), plus from [prerequisites ](https://www.tensorflow.org/lite/models/modify/model_maker/object_detection#install_the_required_packages)of object detection example

### 2. Code
As described in [example](https://www.tensorflow.org/lite/models/modify/model_maker/object_detection)

### 3. Changes the output order of object detection model.
As per the tflite model maker, the model generated by tflite model maker can be directly used in Task Library.  As per [Model compatibility requirements](https://www.tensorflow.org/lite/inference_with_metadata/task_library/object_detector#model_compatibility_requirements), out put order is already defined. But in tflite model maker case, it changes the output order, in general it should be  location, classes, scores and number of detection, but here it is, score, location, number of detection, classes. Here is the output of generated tflite model meta data from tflite model maker.
``` JSON
{
  "name": "ObjectDetector",
  "description": "Identify which of a known set of objects might be present and provide information about their positions within the given image or a video stream.",
  "subgraph_metadata": [
    {
      "input_tensor_metadata": [
        {
          "name": "image",
          "description": "Input image to be detected.",
          "content": {
            "content_properties_type": "ImageProperties",
            "content_properties": {
              "color_space": "RGB"
            }
          },
          "process_units": [
            {
              "options_type": "NormalizationOptions",
              "options": {
                "mean": [
                  127.0
                ],
                "std": [
                  128.0
                ]
              }
            }
          ],
          "stats": {
            "max": [
              255.0
            ],
            "min": [
              0.0
            ]
          }
        }
      ],
      "output_tensor_metadata": [
        {
          "name": "score",
          "description": "The scores of the detected boxes.",
          "content": {
            "content_properties_type": "FeatureProperties",
            "content_properties": {
            },
            "range": {
              "min": 2,
              "max": 2
            }
          },
          "stats": {
          }
        },
        {
          "name": "location",
          "description": "The locations of the detected boxes.",
          "content": {
            "content_properties_type": "BoundingBoxProperties",
            "content_properties": {
              "index": [
                1,
                0,
                3,
                2
              ],
              "type": "BOUNDARIES"
            },
            "range": {
              "min": 2,
              "max": 2
            }
          },
          "stats": {
          }
        },
        {
          "name": "number of detections",
          "description": "The number of the detected boxes.",
          "content": {
            "content_properties_type": "FeatureProperties",
            "content_properties": {
            }
          },
          "stats": {
          }
        },
        {
          "name": "category",
          "description": "The categories of the detected boxes.",
          "content": {
            "content_properties_type": "FeatureProperties",
            "content_properties": {
            },
            "range": {
              "min": 2,
              "max": 2
            }
          },
          "stats": {
          },
          "associated_files": [
            {
              "name": "labelmap.txt",
              "description": "Labels for categories that the model can recognize.",
              "type": "TENSOR_VALUE_LABELS"
            }
          ]
        }
      ],
      "output_tensor_groups": [
        {
          "name": "detection_result",
          "tensor_names": [
            "location",
            "category",
            "score"
          ]
        }
      ]
    }
  ],
  "min_parser_version": "1.2.0"
}

```

How we can fix the issue with changed output order by TFLite Model Maker.

**Comment by mohantym** [comment]
Hi @krunalvaghani !
Thanks for sharing your observation on changing order of outputs in metadata .
Workaround for this issue is to declare the sequence of outputs explicitly using [metadata writer.](https://www.tensorflow.org/lite/models/convert/metadata_writer_tutorial#object_detectors)

@sachinprasadhs !
Could you look at this bug.

Thank you!

**Comment by krunalvaghani** [comment]
By exploring tflite-model-maker, tensorflow lite, core issue is in tflite model generations using method from [`tf.lite.TfLiteConverter`](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter). It is some how not considering the name of the tensor.

For example, output layers of tensorflow model are,
``` JSON
{'output_1': TensorSpec(shape=(None, 100), dtype=tf.float32, name='output_1'),
 'output_2': TensorSpec(shape=(None, 100), dtype=tf.float32, name='output_2'),
 'output_0': TensorSpec(shape=(None, 100, 4), dtype=tf.float32, name='output_0'),
 'output_3': TensorSpec(shape=(None,), dtype=tf.int32, name='output_3')}
```
TfLiteConverter is not considering the name of tensor, to sort the output order. It converts on random order of output. It also happens with latest stable version TF 2.10.0

**Comment by lu-wang-g** [comment]
This is an expected behavior of TFLite converter. However, you can leverage signatures (https://www.tensorflow.org/lite/guide/signatures) to control your inputs/outputs for both training and inference.

**Comment by sachinprasadhs** [comment]
If the above suggestion does not work for you, could you please check the workaround mentioned here to reorder the output using layer name. 
 https://github.com/tensorflow/tensorflow/issues/57043#issuecomment-1318333182

**Comment by krunalvaghani** [comment]
> If the above suggestion does not work for you, could you please check the workaround mentioned here to reorder the output using layer name. [#57043 (comment)](https://github.com/tensorflow/tensorflow/issues/57043#issuecomment-1318333182)

I have tried as it states in [comment](https://github.com/tensorflow/tensorflow/issues/57043#issuecomment-1318333182) by giving output names to the output layers ([link](https://github.com/tensorflow/tensorflow/issues/58764#issuecomment-1339215516)). That is not working.

**Comment by sachinprasadhs** [comment]
@krunalvaghani , Could you try the comment here https://github.com/tensorflow/tensorflow/issues/47927#issuecomment-1499781808 to try with the `tf.keras.layers.Identity` to retain the output name.

**Comment by RohanEmpire** [comment]
@krunalvaghani 

I have trained a yolov5 model and modified it to get 4 ouput arrays when converted to tflite 

im getting 4 arrays loc,class,score,num_detections

but i have a issue that im getting box upon box issue

so while converting pt to tflite i have included nms to resolve the issue.......issue is gone now but output order got jumbled now im getting loc,score,class,num_detections


My need is a ready made tflite which gives loc,class,score,num_det ...where i need to upload to a camera which takes in this order



so please guide to change the order of tflite
now i hv location,score,class,num_detections
but i need location,class,score,num_detections
