### ISSUE TITLE
How to convert model with multiple input?

### ISSUE THREAD

**Issue by MPolaris** [tensorflow/tensorflow#58760]
### 1. System information

- OS Platform and Distribution (e.g., window 10):
- TensorFlow installation (pip package):
- TensorFlow library (tensorflow 2.9.1):

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

I'm use code as below, what should I change to make convertion success? 
```
import numpy as np
import tensorflow as tf
from tensorflow import keras

# how to write "representative_dataset_gen" function?
def representative_dataset_gen():
    for _ in range(20):
        data1 = np.random.rand(1, 3, 16, 16).astype(np.float32)
        data2 = np.random.rand(1, 3, 16, 16).astype(np.float32)
        yield [data1, data2]

# build model
kinput1 = keras.Input(shape=(16, 16, 3), batch_size=1, name="input_1")
kinput2 = keras.Input(shape=(16, 16, 3), batch_size=1, name="input_2")
conv1 = keras.layers.Conv2D(16, 3, 2)(kinput1)
conv2 = keras.layers.Conv2D(16, 3, 2)(kinput2)
out = conv1 + conv2

keras_model = keras.Model(inputs=[kinput1, kinput2], outputs=out)
keras_model.trainable = False
keras_model.summary()

# convert
converter = tf.lite.TFLiteConverter.from_keras_model(keras_model)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8  # or tf.int8
converter.inference_output_type = tf.uint8  # or tf.int8
converter.representative_dataset = representative_dataset_gen
tflite_model = converter.convert()
with open("./model.tflite", "wb") as fp:
    fp.write(tflite_model)
```

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

- Model produces wrong results and/or has lesser accuracy.
- Model produces correct results, but it is slower than expected.

### 4. (optional) RNN conversion support
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

error info:
```
ValueError: The inference_input_type and inference_output_type must be tf.float32.
```

**Comment by mohantym** [comment]
Hi @MPolaris !
Int8 quantization does not seem to be feasible here. You can skip the below code snippet on inference input and output type as a work around. (Tested with concatenation of outputs and other  flags, checked in 2.11 and nightly too.)
```
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8  # or tf.int8
converter.inference_output_type = tf.uint8
```
Attached [gist ](https://colab.sandbox.google.com/gist/mohantym/3245ae00434c9cf2cfac93646ef0fb02/git_58760.ipynb#scrollTo=xcJl8iAo1-Oy)for reference.

**Comment by MPolaris** [comment]
Hi @mohantym!
Thanks for your response. I think this model is very simple and only owns two input nodes.
It's very confusing for ```tf.lite.TFLiteConverter``` is not support quantization for multiple input model?

**Comment by mohantym** [comment]
@MPolaris !
Thanks for the clarification . (Quantization issue with multiple input model). 
Actually, Model did not pass  for single quantization even with single input for above model (earlier trials)
My guess was merging the outputs of 2 output of two conv2d layers. 

Anyway, You can find the quantization issues through [quantization_debugger ](https://www.tensorflow.org/lite/performance/quantization_debugger)and replace/disable the quantization of respective layers.

@sachinprasadhs !
Could you look at this issue. Attached [gist ](https://colab.sandbox.google.com/gist/mohantym/3245ae00434c9cf2cfac93646ef0fb02/git_58760.ipynb#scrollTo=xcJl8iAo1-Oy)for reference.

Thank you!

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
