### ISSUE TITLE
GraphKeys.VARIABLES deprecated early

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#5877]
`GraphKeys.VARIABLES` was intended to be deprecated next march according to the code.

But [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L4067) it is set as a property. Therefore back-compatibility of `GraphKeys.VARIABLES` is already broken now because one has to use `GraphKeys().VARIABLES` instead.

It should something like a classproperty instead.

**Comment by prb12** [comment]
I believe this was fixed by @ilblackdragon on 11/03.  I'm not sure why it hasn't made it to the public tree yet?

**Comment by ilblackdragon** [comment]
Actually, seems like there was a change from working `@classproperty` to `@property`, and as we changed tests we didn't catch this. Let me fix it up back.

**Comment by terrytangyuan** [comment]
Sorry about that. I overlooked it and didn't notice any test failures. @ilblackdragon
