### ISSUE TITLE
Cannot convert Handwriting recognition model to tflite model

### ISSUE THREAD

**Issue by mehti98** [tensorflow/tensorflow#58778]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installation (pip package or built from source): pip install "tensorflow<2.11"
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.10.1
- Python 3.10

### 2. Code

Used the code from the tutorial on this page:
https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/vision/ipynb/handwriting_recognition.ipynb
And at the end tried converting the prediction model to a TF Lite model using following code:

```
converter = tf.lite.TFLiteConverter.from_keras_model(prediction_model)
tflite_float_model = converter.convert()
```
And then I get the following error:
[error_log_1.txt](https://github.com/tensorflow/tensorflow/files/10149753/error_log_1.txt)
Which basically says that I need to set supported_ops flags. First of all, is there any way I can prevent that? I don't understand what function in the code is using select TensorFlow core operators, I don't want to be using any select TensorFlow core operators since it makes it creates other problems.

And then when I do set these flags:
```
converter = tf.lite.TFLiteConverter.from_keras_model(prediction_model)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
converter._experimental_lower_tensor_list_ops = False
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_float_model = converter.convert()
```

Then I get the following messages, which i'm not sure if these are indicating if something's gone wrong or not:
[error_log_2.txt](https://github.com/tensorflow/tensorflow/files/10149850/error_log_2.txt)

And export the model and import it in my android project using these instructions: https://www.tensorflow.org/lite/guide/ops_select
On Android I then convert the model file to byte buffer and try to pass it to TF Lite Interpreter as follows:
```
val fileDescriptor = context.assets.openFd(filename)
val inputStream = FileInputStream(fileDescriptor.fileDescriptor)
val fileChannel = inputStream.channel
val startOffset = fileDescriptor.startOffset
val declaredLength = fileDescriptor.declaredLength
val byteBuffer = fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength)
val interpreter = org.tensorflow.lite.Interpreter(byteBuffer)
```
I then get a IllegalArgumentException with following message:
`"Model ByteBuffer should be either a MappedByteBuffer of the model file, or a direct ByteBuffer using ByteOrder.nativeOrder() which contains bytes of model content."`
I think there is something wrong with the exported TF Lite model file. 

Best solution would probably be to avoid using select TF operators, would really like to avoid it if possible.
Would appreciate your help!

**Comment by mohantym** [comment]
Hi @mehti98 !
It seems you have sorted out the original select ops issue from your side . 
For second error on bytebuffer Can you make the necessary changes  according to this  [example file](https://github.com/tensorflow/examples/blob/master/lite/codelabs/digit_classifier/android/finish/app/src/main/java/org/tensorflow/lite/codelabs/digitclassifier/DigitClassifier.kt) and let us know. 

 ```
  val byteBuffer = ByteBuffer.allocateDirect(modelInputSize)
  byteBuffer.order(ByteOrder.nativeOrder())
```
Thank you!

**Comment by mehti98** [comment]
Hi @mohantym ,
where does this `modelInputSize` come from?
As I mentioned the exception is thrown at line 64 in the example file you've sent, whilst initializing the Interpreter object:
`val interpreter = Interpreter(model)`
so I'm not able to get the modelInputSize.
But maybe you meant to modify the `convertFileToByteBuffer` method which converts the model file to byte buffer. I modified the method accordingly to:
```
fun convertFileToByteBuffer(assetManager: AssetManager, filename: String): ByteBuffer {
        val fileDescriptor = assetManager.openFd(filename)
        val inputStream = FileInputStream(fileDescriptor.fileDescriptor)
        val fileChannel = inputStream.channel
        val startOffset = fileDescriptor.startOffset
        val declaredLength = fileDescriptor.declaredLength
        val mappedByteBuffer = fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength)
        val byteBuffer = ByteBuffer.allocate(mappedByteBuffer.capacity())
        byteBuffer.order(ByteOrder.nativeOrder())
        return byteBuffer
    }
```

But I'm still getting an exception:
`java.lang.Exception: java.lang.IllegalArgumentException: Model ByteBuffer should be either a MappedByteBuffer of the model file, or a direct ByteBuffer using ByteOrder.nativeOrder() which contains bytes of model content.`

**Comment by mohantym** [comment]
Ok @mehti98 !
Thanks for the update. 

@sachinprasadhs 
Could you look at this issue.

Thank you!

**Comment by mehti98** [comment]
Hi @mohantym , @sachinprasadhs 
Is there any update on this?
Just to add, I just need a hand-recognition model for TF Lite to implement in my Android App, so if you guys have any suggestions, for example if i can download an already trained model and can just download and use it, it would also be just enough

Thank you!

**Comment by mehti98** [comment]
@mohantym @sachinprasadhs 
I modified the `convertFileToByteBuffer` method accordingly:
```
val inputStream = assetManager.open(filename)
val output = ByteArrayOutputStream()
inputStream.copyTo(output, 1024)
val file = output.toByteArray()
val bb = ByteBuffer.allocateDirect(file.size)
bb.order(ByteOrder.nativeOrder())
bb.put(file)
return bb
```
 **AND updated the TF Lite dependencies to the following:**
```
"org.tensorflow:tensorflow-lite:2.11.0"
"org.tensorflow:tensorflow-lite-select-tf-ops:2.11.0"
```
And finally managed to initialize the TF Lite interpreter!
I then ran the interpreter with an input of a bitmap image converted to ByteBuffer, but the output I get is really weird. The output tensor shape is [1,32,81] , an array of floats, which is really weird, I was just expecting the predicted text as output?? 
Maybe I need to decode this? 
Can you please help me out? I have attached the model image
![textRecognitionModel tflite](https://user-images.githubusercontent.com/43731577/206911723-dc421103-5a8b-4c4e-b3a3-707962e95775.png)

**Comment by pjpratik** [comment]
Hi @mehti98 

We have to decode the predictions to get the output text by
```
# A utility function to decode the output of the network
def decode_batch_predictions(pred):
    input_len = np.ones(pred.shape[0]) * pred.shape[1]
    # Use greedy search. For complex tasks, you can use beam search
    results = keras.backend.ctc_decode(pred, input_length=input_len, greedy=True)[0][0][
        :, :max_length
    ]
    # Iterate over the results and get back the text
    output_text = []
    for res in results:
        print(res)
        res = tf.strings.reduce_join(num_to_char(res)).numpy().decode("utf-8")
        output_text.append(res)
    return output_text
```
You may find [this notebook](https://github.com/tulasiram58827/ocr_tflite/blob/main/colabs/captcha_ocr_tflite.ipynb) to be useful in this regard and let us know if it helps.

Thanks.
