### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow (from versions: none)

### ISSUE THREAD

**Issue by rajutechie** [tensorflow/tensorflow#58774]
❯ python --version
Python 3.10.5
❯ pip3 install tensorflow
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

OS: Mac Ventura M1

**Comment by Akul2010** [comment]
are you using anaconda by any chance?

if so, please use pip instead of pip3.

If in case you arent using anaconda, follow these steps.

1. Go to the Pypi page (https://pypi.org/project/tensorflow/)
2. Go to download files
3. Download the one that matches your machine
4. type in pip3 install <downloaded file name>

Hope this helps,
Akul.

**Comment by sushreebarsa** [comment]
@rajutechie Could you confirm the TF version you are using? Please refer to this [link](https://www.tensorflow.org/install/source) to know more on the tested build configurations. Let us know if it helps?
Thank you!

**Comment by rajutechie** [comment]
@sushreebarsa I am trying to install TensorFlow version 2.11.0

**Comment by sushreebarsa** [comment]
@rajutechie Could you refer to this [issue](https://github.com/tensorflow/tensorflow/issues/58459) and try creating another virtual environment. Please let us know if it helps?
Thank you

**Comment by rajutechie** [comment]
@sushreebarsa Now I can install TensorFlow using the new conda env, but I am still facing the issue with tensorflow.keras module import

<img width="657" alt="image" src="https://user-images.githubusercontent.com/68769797/206251827-8b4c1ff4-4e32-4807-b2a1-114a188fe98f.png">

**Comment by sushreebarsa** [comment]
@rajutechie First install the TensorFlow backend, then Keras itself:

```
pip install tensorflow

pip install keras
```
Test the installation:
```
python

>>> import keras
```
The import should succeed without error if the installation is complete.
Please let us know if you still face this issue ? Thank you!

**Comment by rajutechie** [comment]
Thank you worked well.
