### ISSUE TITLE
A error when using tfmot.quantization.keras.quantize_model to quantize keras model

### ISSUE THREAD

**Issue by DuJiahao1996** [tensorflow/tensorflow#58783]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf=2.4.1, tensorflow_model_optimization==0.5.0                                            

### Custom Code

Yes

### Python version

3.6.9

### Current Behaviour?

```shell
A bug happened!
A error when using tfmot.quantization.keras.quantize_model to quantize keras model:
RuntimeError: Layer conv1d:<class 'tensorflow.python.keras.layers.convolutional.Conv1D'> is not supported. You can quantize this layer by passing a `tfmot.quantization.keras.QuantizeConfig` instance to the `quantize_annotate_layer` API.

dose fmot.quantization.keras.quantize_model not support 1DCNN?
```

### Standalone code to reproduce the issue

```shell
LOGGER.info(f"starting")
        prune_low_magnitude = tfmot.sparsity.keras.prune_low_magnitude
        pruning_params = {'pruning_schedule': tfmot.sparsity.keras.ConstantSparsity(target_sparsity=0.30,begin_step=0,end_step=-1)}
        LOGGER.info(f"pruning")
        self._model = prune_low_magnitude(self._model, **pruning_params)
        LOGGER.info(f"compiling")
        self._model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=["accuracy"])
        LOGGER.info(f"fitting")
        history=self._model.fit(x=data, epochs=8, verbose=1, shuffle=True, callbacks=callbacks)

        LOGGER.info(f"striping")
        self._model = tfmot.sparsity.keras.strip_pruning(self._model)

        LOGGER.info(f"quantizing")
        quantize_model = tfmot.quantization.keras.quantize_model
        self._model = quantize_model(self._model)

        LOGGER.info(f"compiling")
        self._model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=["accuracy"])


        LOGGER.info(f"fitting")
        history = self._model.fit(x=data, epochs=2, verbose=1, shuffle=True, callbacks=callbacks)
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @DuJiahao1996 !
Could you check the same with 2.10/ Python 3.8 . (minimum version in python 3.7)
It should be reported in [Tensorflow/model optimization ](https://github.com/tensorflow/model-optimization) repo if not resolved.

Thank you!

**Comment by DuJiahao1996** [comment]
> Is the current version too low to support？



> Hi @DuJiahao1996 ! Could you check the same with 2.10/ Python 3.8 . (minimum version in python 3.7) It should be reported in [Tensorflow/model optimization ](https://github.com/tensorflow/model-optimization) repo if not resolved.
> 
> Thank you!

**Comment by mohantym** [comment]
Yeah @DuJiahao1996 !
Version > 2.8.2 are less buggy compared to 2.4 version.
Thank you!

**Comment by DuJiahao1996** [comment]
> Yeah @DuJiahao1996 ! Version > 2.8.2 are less buggy compared to 2.4 version. Thank you!

Thanks！I have a try.

**Comment by mohantym** [comment]
@DuJiahao1996 !
You can find a compatible Tensorflow_model_optimization version w.r.to Tensorflow in the [release notes.](https://github.com/tensorflow/model-optimization/releases)
Please post on [Tensorflow/model-optimization](https://github.com/tensorflow/model-optimization) /TF-Forum for further assistance.

Thank you!

**Comment by DuJiahao1996** [comment]
> 



> tensorflow_model_optimization==0.5.0

**Comment by DuJiahao1996** [comment]
> @DuJiahao1996 ! You can find a compatible Tensorflow_model_optimization version w.r.to Tensorflow in the [release notes.](https://github.com/tensorflow/model-optimization/releases) Please post on [Tensorflow/model-optimization](https://github.com/tensorflow/model-optimization) /TF-Forum for further assistance.
> 
> Thank you!

After I install the corresponding version, the same error still appears. I use the Tensorflow 2.3.0 and Tensorflow_ model_ Optimization==0.5.0, what is the problem?

here is my model:
tf. keras model
import tensorflow as tf

inputs = tf.keras.Input(shape=(58,))
x=tf.keras.layers.Reshape((58,1))(inputs)

x = tf.keras.layers.Conv1D(8, 1,strides=1,padding='same')(x)
x=tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Activation('relu')(x)

x1 = tf.keras.layers.Conv1D(16, 1,strides=1,padding='same',dilation_rate=3)(x)
x2 = tf.keras.layers.Conv1D(16, 3,strides=1,padding='same',dilation_rate=3)(x)

x1=tf.keras.layers.BatchNormalization()(x1)
x2=tf.keras.layers.BatchNormalization()(x2)

x1 = tf.keras.layers.Activation('relu')(x1)
x2 = tf.keras.layers.Activation('relu')(x2)

x=tf.keras.layers.Concatenate(-1)([x1,x2])

x = tf.keras.layers.Conv1D(16, 1,strides=1,padding='same')(x)
x=tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Activation('relu')(x)

x1 = tf.keras.layers.Conv1D(32, 1,strides=1,padding='same',dilation_rate=3)(x)
x2 = tf.keras.layers.Conv1D(32, 3,strides=1,padding='same',dilation_rate=3)(x)

x1=tf.keras.layers.BatchNormalization()(x1)
x2=tf.keras.layers.BatchNormalization()(x2)

x1 = tf.keras.layers.Activation('relu')(x1)
x2 = tf.keras.layers.Activation('relu')(x2)

x=tf.keras.layers.Concatenate(-1)([x1,x2])

x = tf.keras.layers.Conv1D(32, 1,strides=1,padding='same')(x)
x=tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Activation('relu')(x)

x1 = tf.keras.layers.Conv1D(64, 1,strides=1,padding='same',dilation_rate=3)(x)
x2 = tf.keras.layers.Conv1D(64, 3,strides=1,padding='same',dilation_rate=3)(x)

x1=tf.keras.layers.BatchNormalization()(x1)
x2=tf.keras.layers.BatchNormalization()(x2)

x1 = tf.keras.layers.Activation('relu')(x1)
x2 = tf.keras.layers.Activation('relu')(x2)

x=tf.keras.layers.Concatenate(-1)([x1,x2])

x=tf.keras.layers.Dropout(0.5)(x)

x = tf.keras.layers.Conv1D(128, 4,strides=1,padding='same')(x)
x=tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Activation('relu')(x)

x_shortcut=x

x = tf.keras.layers.Conv1D(128, 1,strides=1,padding='same')(x)
x=tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Activation('relu')(x)

x=tf.keras.layers.SeparableConv1D(128,2,strides=1,padding='same')(x)
x=tf.keras.layers.BatchNormalization()(x)
x = tf.keras.layers.Activation('relu')(x)

se_x = x
se_x=tf.keras.layers.GlobalAveragePooling1D()(se_x)
se_x =tf.keras.layers.Dense(128)(se_x)
se_x= tf.keras.layers.Activation('relu')(se_x)
se_x= tf.keras.layers.Multiply()([x,se_x])
x = tf.keras.layers.add([x,se_x])
x = tf.keras.layers.Activation('relu')(x)

x = tf.keras.layers.add([x,x_shortcut])
x = tf.keras.layers.Activation('relu')(x)

x=tf.keras.layers.GlobalAveragePooling1D()(x)
x=tf.keras.layers.Dropout(0.5)(x)
x =tf.keras.layers.Dense(7)(x)
pred = tf.keras.layers.Activation('softmax')(x)
model = tf.keras.Model(inputs=inputs, outputs=pred)
model.summary()
print(model.to_json())

**Comment by sushreebarsa** [comment]
@DuJiahao1996 If you are using an olader version of TF(2.3.0), then please upgrade to the latest TF version 2.11.
Please find the gist [here](https://colab.sandbox.google.com/gist/sushreebarsa/7d033c0b97deee4ff1926acbc4c8266e/git_58783.ipynb) and confirm the issue?
Thank you
