### ISSUE TITLE
TensorFlow Lite Image Classification - add a new model

### ISSUE THREAD

**Issue by HripsimeS** [tensorflow/tensorflow#58784]
Hello. I tested your TensorFlow Lite Image Classification android app and it works perfect with these models (MobileNet V1, EfficientNet Lite0, EfficientNet Lite1, EfficientNet Lite2) which are downloading automatically by the download.gradle file.

https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android

Then I wanted to add my own classification model which has different labels compared to models mentioned above. I placed my model in **assets** folder app\src\main\assets and then did some modification in **ImageClassifierHelper.kt** file.

val modelName =
            when (currentModel) {
                MODEL_MYMODEL -> "mymodel.tflite"
                MODEL_MOBILENETV1 -> "mobilenetv1.tflite"
                else -> "mymodel.tflite"
            }

companion object {
        const val DELEGATE_CPU = 0
        const val DELEGATE_GPU = 1
        const val DELEGATE_NNAPI = 2
        const val MODEL_MYMODEL = 0
        const val MODEL_MOBILENETV1 = 1
        private const val TAG = "ImageClassifierHelper"
    }

While I build and launch the app, I received the following error:

**Launching 'app' on Xiaomi .....
Install successfully finished in 6 s 117 ms.
$ adb shell am start -n "org.tensorflow.lite.examples.imageclassification/org.tensorflow.lite.examples.imageclassification.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 15146 on device 'xiaomi-......'.**

Can you please let me know how to fix the issue and do I need to do other modification in scripts to make it work with my model. 

Look forward to hearing from you and thank you in advance!

**Comment by mohantym** [comment]
Hi @HripsimeS !
It seems it got installed and deployed to your device even if you put the lite models in asset folder explicity . To  configure from script , Please change the [download_models.gradle](https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android/app/download_models.gradle) file with suitable storage api links for your model. (Test with Hub model links too)

Thank you!

**Comment by HripsimeS** [comment]
@mohantym thanks for your reply. I modified **download_models.gradle** file and add the link to download my model and there is no problem, it downloads in asset folder  https://www.dropbox.com/s/66imklf2veof0af/model.tflite

But when I launch the app, I get exactly the same error mentioned above. So for me it is not clear the problem comes from my converted model from **pth** to **tflite** or I still need to do more modifications in initial scripts of Image Classification app.

May I ask you to check if my model works fine with your app, this model has 130 different classes of dog breeds.
https://github.com/HripsimeS/Projects/blob/main/model.tflite

Look forward to hearing from you!

**Comment by HripsimeS** [comment]
@mohantym please check the errors I am getting while launching the app. Any ideas what is going wrong?

E/QT: [QT]file does not exist
E/MiuiMultiWindowUtils: initFreeFormResolutionArgs failed, device is eos
E/tflite: The model is not a valid Flatbuffer buffer
E/TaskJniUtils: Error getting native address of native library: task_vision_jni
java.lang.IllegalArgumentException: Error occurred when initializing ImageClassifier: The model is not a valid Flatbuffer buffer
E/TaskJniUtils: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1074)
E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.tensorflow.lite.examples.imageclassification, PID: 27776
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:300)

**Comment by mohantym** [comment]
@HripsimeS !
I think the problem is with TFlite model itself. Can you check with another model for hub or lite model.

> E/tflite: The model is not a valid Flatbuffer buffer

Thank you!

**Comment by HripsimeS** [comment]
@mohantym I tested my model with the code below and received the output (1, 300). Seems my model is fine.

interpreter = tf.lite.Interpreter(model_path="../models/model.tflite")
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index']) 
print(output_data.shape)

If you know other ways to check the model, let me know. Thanks in advance!

**Comment by mohantym** [comment]
@HripsimeS !
We can use [tfl.quantization_debugger](https://www.tensorflow.org/lite/performance/quantization_debugger) to see scaling issue and [model_analyzer](https://www.tensorflow.org/lite/guide/model_analyzer) too.

Could you post on TF Forum for further assistance and tag the thread here. 

Thank you!

**Comment by HripsimeS** [comment]
@mohantym @sachinprasadhs Hello!

I checked also your real time object detection app which works fine with the initial models (MobileNet V1, EfficientNet Lite0, EfficientNet Lite1, EfficientNet Lite2). https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android

But I received errors again as soon as I tried to add other model for example yolo5s model trained on COCO dataset which converted from **pt** format to **tflite** with export.py script https://github.com/ultralytics/yolov5/blob/master/export.py

Below are the converted models for yolo5s (fp16 and int8 options) and I already checked they are working fine with detect.py.
https://github.com/HripsimeS/Projects/blob/main/yolov5s-fp16.tflite
https://github.com/HripsimeS/Projects/blob/main/yolov5s-int8.tflite

I don't understand why it is not possible to deploy other models in your real time object detection app, I am sure other users would like to use/add other models also except those initial 4 models mentioned above. Please can you check if you can deploy in your object detection app one of those two models (fp16 or int8) I shared with you above. 

Look forward to hearing from you and thank you in advance!

**Comment by pkgoogle** [comment]
Hi @HripsimeS,

I downloaded your model file and made the same changes in Android studio and then ran an emulator and I get this error in the error log: "java.lang.IllegalArgumentException: Error occurred when initializing ImageClassifier: The input tensor should have dimensions 1 x height x width x 3. Got 1 x 3 x 256 x 256."

Can you check whether your input shapes match the input shapes of these models? (MobileNet V1, EfficientNet Lite0, EfficientNet Lite1, EfficientNet Lite2)

Some APIs require TFLite metadata, does your model have TFLite metadata? https://www.tensorflow.org/lite/models/convert/metadata

Let me know if that helps, thanks!
