### ISSUE TITLE
server used by model reset connection

### ISSUE THREAD

**Issue by JamesDaniel** [tensorflow/tensorflow#5878]
### tensorflow official tutorial link with problem
<a href="https://www.tensorflow.org/versions/r0.11/tutorials/image_recognition/index.html">https://www.tensorflow.org/versions/r0.11/tutorials/image_recognition/index.html</a>

### Environment info
Ubuntu 14 64bit

### Installation
Installed with pip to virtualenv
pip wheel used: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl

### Execution of model
python tensorflow/models/image/imagenet/classify_image.py

### Output
```
python classify_image.py
>> Downloading inception-2015-12-05.tgz 100.0%Traceback (most recent call last):
  File "classify_image.py", line 212, in <module>
    tf.app.run()
  File "/home/user/Documents/virt_env/python-tensorflow-test/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "classify_image.py", line 205, in main
    maybe_download_and_extract()
  File "classify_image.py", line 197, in maybe_download_and_extract
    filepath, _ = urllib.request.urlretrieve(DATA_URL, filepath, _progress)
  File "/usr/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 268, in retrieve
    block = fp.read(bs)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
socket.error: [Errno 104] Connection reset by peer
```

**Comment by prb12** [comment]
The URL in question (i.e. the imagenet dataset download) seems to be working fine for me now.
Perhaps a transient error?  

Could you please try again?  And also try opening the same URL in a web browser:
```
http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz
```

**Comment by JamesDaniel** [comment]
Hey, The link seems to be working now but I don't have time to try it in tensorflow. I can download through the browser to the folder as a bypass if this problem persists for me. It shouldn't fail the CRC check then hopefully. 

Thanks for your help.
- James
