### ISSUE TITLE
Tensorflow Layer Reshape not working for same size arrays

### ISSUE THREAD

**Issue by dpm16** [tensorflow/tensorflow#58786]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.11

### Custom Code

Yes

### OS Platform and Distribution

Windows 10 Pro

### Python version

3.8

### CUDA/cuDNN version

11.8

### Current Behaviour?

```shell
Tensorflow Reshape layer was throwing size mismatch errors when trying to reshape an array to another of the same size.
Sometimes it was working, sometimes not. After testing found examples of Reshape not working for a target array of the exact same shape as input array.

This behaviour only seems to happen on windows and code works on linux
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

tensor = tf.keras.Input(shape=(512, 512, 512, 32))
out = tf.keras.layers.Reshape((512, 512, 512, 32))(tensor)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "d:\Miniconda3\envs\python\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "d:\Miniconda3\envs\python\lib\site-packages\keras\layers\reshaping\reshape.py", line 118, in _fix_unknown_dimension
    raise ValueError(msg)
ValueError: Exception encountered when calling layer "reshape_1" (type Reshape).

total size of new array must be unchanged, input_shape = [512, 512, 512, 32], output_shape = [512, 512, 512, 32]

Call arguments received by layer "reshape_1" (type Reshape):
  • inputs=tf.Tensor(shape=(None, 512, 512, 512, 32), dtype=float32)
```
</details>

**Comment by TushirSahu** [comment]
@dpm16 
Please find the above implementation here [gist](https://gist.github.com/TushirSahu/e2029fddd295c06b53da68a89e890612).
Did you try this same on the Jupyter Notebook?

**Comment by dpm16** [comment]
The error only happens on windows and works on linux. It does work on the Jupyter notebook but not an any Windows machine running it.

**Comment by tiruk007** [comment]
@dpm16 
I was able to reproduce the issue on the windows. Please refer to the snapshot
![Screenshot (8)](https://user-images.githubusercontent.com/111861663/207442784-3e47bec3-46d0-4466-a9a1-cd4981a068f1.png)


This issue seems to be a keras related issue. Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999.

Thank you!
