### ISSUE TITLE
Use cl_khr_integer_dot_product if available

### ISSUE THREAD

**Issue by tomeuv** [tensorflow/tensorflow#58782]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

707f1dcba4c8 (HEAD -> master, origin/master, origin/HEAD) compat: Update forward compatibility horizon to 2022-12-05

### Custom Code

No

### Current Behaviour?

```shell
Are there any plans to make use of cl_khr_integer_dot_product to speed up execution on GPUs that support it?
```

### Standalone code to reproduce the issue

```shell
N/A
```

### Relevant log output

_No response_</details>

**Comment by tomeuv** [comment]
Sure, the idea is to allow TFLite's GPU delegate to make use of those instructions in GPGPUs that optimize the dot product of integers:

https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_Ext.html#_new_opencl_c_functions_2

**Comment by mohantym** [comment]
Hi @tomeuv !
Thanks for feature request on cl_khr_integer_dot_product with supported GPUs.

@SuryanarayanaY !
Could you look at this issue.

Thank you!

**Comment by impjdi** [comment]
I don't think we're doing something extensively with integers.  Can you elaborate where you would like to see this used?
