### ISSUE TITLE
which encoding can i use to parse tensorflow_stats.pb?

### ISSUE THREAD

**Issue by zzq96** [tensorflow/tensorflow#58799]
### Issue Type

Others

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### OS Platform and Distribution

ubuntu 16.04

### Python version

3.8

### Current Behaviour?

i get a tensorflow_stats.pb file by tf.profiler. code like this:
```

            tf.profiler.experimental.start("./logs_dir")
            loss = dnn_model.train_step(batch_data)
            tf.profiler.experimental.stop()
```
I want to read tensorflow_stats.pb in my python code, but i don't know which Encoding this file use.
the file content is:
```
"ä°
pHostUpdateMetricState"UpdateMetricState(1ňŇMbx@9ňŇMbx@AňŇMbx@IňŇMbx@a×ÝťÁ.Ň?i×ÝťÁ.Ň?Unknown
rHostUpdateMetricState"UpdateMetricState_1(11ŹZB@91ŹZB@A1ŹZB@I1ŹZB@ać
[ŤŻóĚ?iĽą´KAŕ?Unknown
BHostIDLE"IDLE1ÁĘĄEś×l@AÁĘĄEś×l@aľśş?iôűŮă?Unknown
rHostUpdateMetricState"UpdateMetricState_2(1ŮÎ÷ób@9ŮÎ÷ób@AŮÎ÷ób@IŮÎ÷ób@aÍÖ×;Öą?iďîĂÉĺ?Unknown
pHostAsyncPushGradient"AsyncPushGradient(1î|?5^BV@9î|?5^BV@Aî|?5^BV@Iî|?5^BV@ać^EĂ¤?iYÝe÷pç?Unknown
dHostEmbOutputTransfer"label(1×Łp=
I@9×Łp=
I@A×Łp=
I@I×Łp=
I@aiśÂ­¤?i[veĐç?Unknown
\HostPrintV2"PrintV2(1+ŮÎF@9+ŮÎF@A+ŮÎF@I+ŮÎF@aâÉ­ß?i[ŮŢbyč?Unknown
HostGlobalNormGrad"Bgradient_tape/simple_dnn_model/global_normalization/GlobalNormGrad(19´Čvž?B@99´Čvž?B@A9´Čvž?B@I9´Čvž?B@aĐţ~[ęć?iRŃşľĚé?Unknown
b	Host
```

**Comment by mohantym** [comment]
Hi @zzq96 !
Not sure on the encoding. But you can load .pb file using [tf.io.gfile.Gfile](url) and parsing using GraphDef
```
with tf.io.gfile.GFile('/tmp/graph.pb', 'rb') as f:
  graph_def = tf.compat.v1.GraphDef()
  graph_def.ParseFromString(f.read())

```
[Reference](https://www.tensorflow.org/api_docs/python/tf/compat/v1/GraphDef)

Thank you!

**Comment by MarkDaoust** [comment]
> parsing using GraphDef

That won't work. 

A .pb contains serialized protos. It could be any proto. You need to know what kind of proto, and use that class to parse it.

**Comment by MarkDaoust** [comment]
Cool.

**Comment by mohantym** [comment]
@MarkDaoust !
Thanks for providing the pointers.
Thank you!
