### ISSUE TITLE
Bug when using TFLite converter - error message suggests to send it to you

### ISSUE THREAD

**Issue by FranciszekNowak** [tensorflow/tensorflow#58797]
I was trying to convert a standard model (properly defined, works just fine when trying to predict stuff) when I encountered this error:

```
WARNING:tensorflow:AutoGraph could not transform <function canonicalize_signatures.<locals>.signature_wrapper at 0x7f7981227160> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: Unknown node type <gast.gast.Expr object at 0x7f79811d2df0>
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert

WARNING: AutoGraph could not transform <function canonicalize_signatures.<locals>.signature_wrapper at 0x7f7981227160> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10) and attach the full output.
Cause: Unknown node type <gast.gast.Expr object at 0x7f79811d2df0>
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
```

I am using a book ,,TinyML: Machine Learning with TensorFlow on Arduino, and Ultra-Low Power Micro-Controllers ", which seems to be written by someone from TF development team.
I follow all the instructions from chapter 4.
If you are interested in my colab code, here it is:
[https://colab.research.google.com/drive/1eyqMB1POAZ9qw3lPCZkiyU7zfQ0Y1OxF#scrollTo=u26RmYUMC3Rw]
Any idea, any help?

UPDATE 06.12.2022
After re-running the entire code the day after I posted the issue (which is today), it worked just fine.
Still, I would like to know what might have caused the problem.
Should I close the issue?

**Comment by sushreebarsa** [comment]
@FranciszekNowak This warning will not hurt performance. If you face this issue in the future you may add this line just before importing tensorflow: tf.autograph.set_verbosity(3, True)?  It will show the additional information along with the warning. 
After re-running your code if the issue doesn't persist now, then please move this issue to closed status.

Thank you!

**Comment by FranciszekNowak** [comment]
Thank you very much!
