### ISSUE TITLE
tf.math.cumsum() propagates Inf or NaN when axis is ragged

### ISSUE THREAD

**Issue by MKimiSH** [tensorflow/tensorflow#58790]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.11

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python version

3.10.6

### CUDA/cuDNN version

CUDA 11.7, cuDNN 8.2.4

### GPU model and memory

RTX 3090 24GiB

### Current Behaviour?

```shell
When using `tf.math.cumsum(ragged_tensor, axis=axis)`, if `axis` is ragged and `ragged_tensor` contains `inf` or `nan`, the output will be `nan` for *all* the following flat values, even for those that are not supposed to be summed with those `nan`s. This doesn't happen for regular `Tensor`s. 

Moreover, the behavior persists when `exlusive=True` or `reverse=True` is passed to `cumsum()`. In the latter case, additional `nan`s occur before the problematic value, instead of after it.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf 
import numpy as np 

# RaggedTensor without NaNs or Infs
rt = tf.ragged.constant([[3, 1, 4], [1, 5], [9, 2], [6, 5, 3]], dtype=tf.float32)
print('tf.math.cumsum(rt, axis=-1) = ', tf.math.cumsum(rt, axis=-1))

# RaggedTensor with Inf
rt2 = tf.ragged.constant([[3, 1, 4], [1, np.inf], [9, 2], [6, 5, 3]], dtype=tf.float32)
print('tf.math.cumsum(rt2, axis=-1) = ', tf.math.cumsum(rt2, axis=-1))
print('tf.math.cumsum(rt2.to_tensor(), axis=-1) = ', tf.math.cumsum(rt2.to_tensor(), axis=-1))
print('tf.math.cumsum(rt2, axis=-1, exclusive=True) = ', tf.math.cumsum(rt2, axis=-1, exclusive=True))
print('tf.math.cumsum(rt2.to_tensor(), axis=-1, exclusive=True) = ', tf.math.cumsum(rt2.to_tensor(), axis=-1, exclusive=True))
print('tf.math.cumsum(rt2, axis=-1, reverse=True) = ', tf.math.cumsum(rt2, axis=-1, reverse=True))
print('tf.math.cumsum(rt2.to_tensor(), axis=-1, reverse=True) = ', tf.math.cumsum(rt2.to_tensor(), axis=-1, reverse=True))

"""Expected output
tf.math.cumsum(rt, axis=-1) =  <tf.RaggedTensor [[3.0, 4.0, 8.0], [1.0, 6.0], [9.0, 11.0], [6.0, 11.0, 14.0]]>
tf.math.cumsum(rt2, axis=-1) =  <tf.RaggedTensor [[3.0, 4.0, 8.0], [1.0, inf],  [9.0, 11.0], [6.0, 11.0, 14.0]]>
tf.math.cumsum(rt2.to_tensor(), axis=-1) =  tf.Tensor(
[[ 3.  4.  8.]
 [ 1. inf inf]
 [ 9. 11. 11.]
 [ 6. 11. 14.]], shape=(4, 3), dtype=float32)
tf.math.cumsum(rt2, axis=-1, exclusive=True) =  <tf.RaggedTensor [[0.0, 3.0, 4.0], [0.0, 1.0], [0.0, 9.0], [0.0, 6.0, 11.0]]>
tf.math.cumsum(rt2.to_tensor(), axis=-1, exclusive=True) =  tf.Tensor(
[[ 0.  3.  4.]
 [ 0.  1. inf]
 [ 0.  9. 11.]
 [ 0.  6. 11.]], shape=(4, 3), dtype=float32)
tf.math.cumsum(rt2, axis=-1, reverse=True) =  <tf.RaggedTensor [[8.0, 5.0, 4.0], [inf, inf], [11.0, 2.0], [14.0, 8.0, 3.0]]>
tf.math.cumsum(rt2.to_tensor(), axis=-1, reverse=True) =  tf.Tensor(
[[ 8.  5.  4.]
 [inf inf  0.]
 [11.  2.  0.]
 [14.  8.  3.]], shape=(4, 3), dtype=float32)
"""

"""Actual output
tf.math.cumsum(rt, axis=-1) =  <tf.RaggedTensor [[3.0, 4.0, 8.0], [1.0, 6.0], [9.0, 11.0], [6.0, 11.0, 14.0]]>
tf.math.cumsum(rt2, axis=-1) =  <tf.RaggedTensor [[3.0, 4.0, 8.0], [1.0, inf], [nan, nan], [nan, nan, nan]]>
tf.math.cumsum(rt2.to_tensor(), axis=-1) =  tf.Tensor(
[[ 3.  4.  8.]
 [ 1. inf inf]
 [ 9. 11. 11.]
 [ 6. 11. 14.]], shape=(4, 3), dtype=float32)
tf.math.cumsum(rt2, axis=-1, exclusive=True) =  <tf.RaggedTensor [[0.0, 3.0, 4.0], [0.0, 1.0], [nan, nan], [nan, nan, nan]]>
tf.math.cumsum(rt2.to_tensor(), axis=-1, exclusive=True) =  tf.Tensor(
[[ 0.  3.  4.]
 [ 0.  1. inf]
 [ 0.  9. 11.]
 [ 0.  6. 11.]], shape=(4, 3), dtype=float32)
tf.math.cumsum(rt2, axis=-1, reverse=True) =  <tf.RaggedTensor [[nan, nan, nan], [inf, inf], [11.0, 2.0], [14.0, 8.0, 3.0]]>
tf.math.cumsum(rt2.to_tensor(), axis=-1, reverse=True) =  tf.Tensor(
[[ 8.  5.  4.]
 [inf inf  0.]
 [11.  2.  0.]
 [14.  8.  3.]], shape=(4, 3), dtype=float32)
"""
```

### Relevant log output

_No response_</details>

**Comment by MKimiSH** [comment]
My guess is that when doing `cumsum` on a ragged dimension, the summation is actually somehow carried out on the entirety of flat values, and then some subtractions based on `row_splits` turn the long `cumsum` list to the result at each dimension. To explain with an example: 

```python
rt = tf.ragged.constant([[3, 1, 4], [1, 5], [9, 2], [6, 5, 3]], dtype=tf.float32)  
# flat values [3, 1, 4, 1, 5, 9, 2, 6, 5, 3]
# row splits [0, 3, 5, 7, 10] 

tf.math.cumsum(rt, axis=-1)  
# first step: cum sum all flat values [3, 4, 8, 9, 14, 23, 25, 31, 36, 39]
# second step: for each row, subtract the last element of the previous row
# [3, 4, 8], [9-8, 14-8], [23-14, 25-14], [31-25, 36-25, 39-25]
# => [3, 4, 8], [1, 6], [9, 11], [6, 11, 14]
```

In this way, we get `inf - inf => nan` when an `inf` appears.

**Comment by MKimiSH** [comment]
Hi again, 

Any updates? I would also be interested in knowing a suggested workaround that doesn't require calling `rt.to_tensor()`.

**Comment by sushreebarsa** [comment]
@MKimiSH I tried to replicate the issue on colab using TF v2.11, and didn't face the error reported. 
Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/9c0f93a4d8ce8801d01f701c6f88022b/58790.ipynb) and let us know if I have missed something to replicate the issue.
Thank you!

**Comment by MKimiSH** [comment]
> @MKimiSH I tried to replicate the issue on colab using TF v2.11, and didn't face the error reported. Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/9c0f93a4d8ce8801d01f701c6f88022b/58790.ipynb) and let us know if I have missed something to replicate the issue. Thank you!

Thanks for looking into it. It looks like you got the same output as I did, actually confirming the bug. 

I think I was not using the term "expected output" correctly, the "expected output" written in the original description is the actual buggy output. I updated the issue, renaming "expected output" to "actual output" and inserted a new "expected output" paragraph with reference to the non-ragged tensor operation output.

**Comment by sushreebarsa** [comment]
@sachinprasadhs I was able to replicate the issue, please find the attached gist [here](https://colab.research.google.com/gist/sushreebarsa/b9627c5fa019036d0874b7d10761ee36/58790.ipynb).
Thank you!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
