### ISSUE TITLE
Deploy yolo5 model into TensorFlow Lite Object Detection Android

### ISSUE THREAD

**Issue by HripsimeS** [tensorflow/tensorflow#58812]
Hello Tensorflow team!

I checked your real time object detection app which works good with the initial models (MobileNet V1, EfficientNet Lite0, EfficientNet Lite1, EfficientNet Lite2). https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android

But I receive errors when I try to add other model for example yolo5s model trained on COCO dataset which converted from **pt** format to **tflite** with export.py script https://github.com/ultralytics/yolov5/blob/master/export.py

Below you can find converted models for yolo5s (fp16 and int8 options), I already checked they are working fine with detect.py.
https://github.com/HripsimeS/Projects/blob/main/yolov5s-fp16.tflite
https://github.com/HripsimeS/Projects/blob/main/yolov5s-int8.tflite

Is it possible to deploy/integrate yolo5 model into your real time object detection app? If yes, can you please check if you can deploy into app one of those two models (fp16 or int8) I shared with you above. In case if it works for you, can you share your experience what did you exactly modify in initial TensorFlow Lite Object Detection app scripts. Thank you in advance!

**Comment by freedomtan** [comment]
The app use models with post-processing part (which includes non-maximum suppression, NMS). You may need to change output processing part and implement NMS.

**Comment by HripsimeS** [comment]
@freedomtan thank you very much for your reply. Can you let me know where I need to change output processing part and implement NMS. If there are some examples how to do it, can you please share with me. Look forward to hearing from you!

**Comment by mohantym** [comment]
Hi @HripsimeS !
Sorry for the late response. 

Please have a look at the relevant[ thread ](https://hansheng0512.medium.com/yolov5-tflite-inferencing-in-mobile-devices-6131a9c0c153)for implementation which suggests both CPU and GPU implementation of Yolo v5 models through [Metadata writer.](https://www.tensorflow.org/lite/models/convert/metadata_writer_tutorial) (Unifies models results with respect to different android architecture)

You can discuss any blockers/results on [TF-Forum](https://discuss.tensorflow.org/t/tensorflow-lite-object-detection-not-possible-to-add-a-new-model/13411) for further assistance.

Thank you!
