### ISSUE TITLE
TensorFlow Lite example label_image run err

### ISSUE THREAD

**Issue by zack-huangzihan** [tensorflow/tensorflow#58810]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  arm64 buildroot
- TensorFlow installation (pip package or built from source):  TensorFlow lite
- TensorFlow library (version, if pip package or github SHA, if built from source):  2.10

### 2. describe

Hi, I am trying to use tensorflow lite on an arm64 device, I compiled using the instructions on this page to compile：https://www.tensorflow.org/lite/guide/build_cmake_arm?hl=zh-cn

`export ARMCC_PREFIX=~/tool_chain/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu- && export ARMCC_FLAGS="-funsafe-math-optimizations"  && cmake -DCMAKE_C_COMPILER=${ARMCC_PREFIX}gcc  -DCMAKE_CXX_COMPILER=${ARMCC_PREFIX}g++  -DCMAKE_C_FLAGS="${ARMCC_FLAGS}"  -DCMAKE_CXX_FLAGS="${ARMCC_FLAGS}" -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON   -DCMAKE_SYSTEM_NAME=Linux   -DCMAKE_SYSTEM_PROCESSOR=aarch64 -DTFLITE_ENABLE_XNNPACK=ON -DTFLITE_ENABLE_GPU=ON ../tensorflow/lite/`

The final compilation libtensorflow-lite.a, label_image , etc.

And then I do this:

scp label_image into my device

and I try to run it:
./label_image --tflite_model testdata/mobilenet_v1_1.0_224.tflite  --labels testdata/labels.txt --image testdata/grace_hopper.bmp
It came up with this log:

INFO: Loaded model testdata/mobilenet_v1_1.0_224.tflite
INFO: resolved reporter
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
ERROR: failed to get XNNPACK profile information.
ERROR: failed to get XNNPACK profile information.
ERROR: failed to get XNNPACK profile information.
ERROR: failed to get XNNPACK profile information.
ERROR: failed to get XNNPACK profile information.
ERROR: failed to get XNNPACK profile information.
INFO: invoked
INFO: average time: 17.374 ms
INFO: 0.860173: 653 653:military uniform
INFO: 0.0481023: 907 907:Windsor tie
INFO: 0.00786704: 466 466:bulletproof vest
INFO: 0.00644933: 514 514:cornet, horn, trumpet, trump
INFO: 0.00608027: 543 543:drumstick

After my driver tests, I found that my device's gpu was not being used,  GPU is mali610, opencl 1.2 is supported, Someone can help me?

**Comment by freedomtan** [comment]
if you `./label_image --help`, you can see there are `-g` and `--use_gpu=true` you can use to enable GPU delegate.

**Comment by zack-huangzihan** [comment]
ok,thank
