### ISSUE TITLE
Tensorflow 2.11 is still using CUDA 11.2 + CuDNN 8.1 that were released 2 years ago

### ISSUE THREAD

**Issue by ShuaiShao93** [tensorflow/tensorflow#58816]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.11

### Custom Code

No

### Current Behaviour?

```shell
Tensorflow 2.11 is still using CUDA 11.2 + CuDNN 8.1 that were released 2 years ago: https://www.tensorflow.org/install/source#gpu. This makes our stack have to use the old CUDA/CuDNN without new features. Is it possible to make new TF version work with newest CUDA/CuDNN?
```

### Standalone code to reproduce the issue

```shell
N/A
```

### Relevant log output

_No response_</details>

**Comment by MarkDaoust** [comment]
I've heard that tensorflow may update to CUDA 11.8 for TensorFlow 2.12.

**Comment by shkarupa-alex** [comment]
+1 waiting for actual cuda version support
