### ISSUE TITLE
How to tell choosen tf.data.AUTOTUNE values? Troubleshooting low parallelism issue

### ISSUE THREAD

**Issue by gilinachum** [tensorflow/tensorflow#58819]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

binary

### Tensorflow Version

2.8

### Custom Code

No

### Current Behaviour?

```shell
How to tell Autotune actual chosen values?  
I'm training a NN on a machine with 1 GPU and 8 vCPUs. I see that the GPU utilization is about 20% and CPU utilization pegs at 200%/800%. Was expecting either of these to be closer to be fully utilized.
I'm using tf.data and set parallelism of different operations [like map(), prefetch()] to -1 (Autotune).  
Based on the 200%/800% cpu usage it seems the degree of parallization isn't high enough, how can I figure out what values were chosen for num_parallel_calls and other parallel parameters that I asked to be auto tune. e.g., Any logging I can turn on?
Before diving into serious profiling work, I would like to check these basic values.
```

### Standalone code to reproduce the issue

```shell
Not necessary in order to address the issue.
```

### Relevant log output

_No response_</details>

**Comment by krrishdholakia** [comment]
To determine the actual chosen values for tf.data.AUTOTUNE, you can use the tf.data.experimental.get_structure() method. This method will provide information about the structure of the data pipeline, including the actual chosen values for the parallelism settings. Additionally, you can use the tf.profiler.experimental.trace_on() and tf.profiler.experimental.trace_off() methods to profile the model and gain insights into how the parallelism is being applied.

You can find more information about this method in the official TensorFlow documentation: https://www.tensorflow.org/api_docs/python/tf/data/experimental/get_structure. The tf.profiler.experimental.trace_on() and tf.profiler.experimental.trace_off() methods can be used to profile and gain insights into the TensorFlow model's parallelism settings. You can find more information about these methods in the official TensorFlow documentation: https://www.tensorflow.org/api_docs/python/tf/profiler/experimental/trace_on and https://www.tensorflow.org/api_docs/python/tf/profiler/experimental/trace_off.

Btw used Clerkie (ai code debugging tool) - https://clerkie.co/, to help me brainstorm on approaches here (still reviewed/investigated feedback before sharing). Hope it helped!
<img width="1513" alt="Screen Shot 2022-12-13 at 1 12 19 PM" src="https://user-images.githubusercontent.com/17561003/207255565-9d5916b0-0964-4d67-8111-165e14c184b7.png">

**Comment by gilinachum** [comment]
If this is a promotion for an AI tool, it's doing it a bad service. 
The answer is not relevant to the question and untested:
get_structure() prints shapes and isn't related to data loader parallelism.
turn on profiler? Profiler is a complex feature that may or may not expose the values I want. (The links you provided for it are dead).
All this answer shows is the current limitations of chatGPU and how how in this case it confidently spits out irrelevant pieces of information.

**Comment by krrishdholakia** [comment]
@gilinachum apologies for that. Removed comment to prevent confusion. No promotion intended. Hope someone can help out!

**Comment by sushreebarsa** [comment]
@gilinachum 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!

**Comment by gilinachum** [comment]
My question is general. How to tell what are the machine picked autotune values?
Relevant code is any code that uses autotune, like the example [here](https://www.tensorflow.org/guide/data_performance).

**Comment by sushreebarsa** [comment]
@gilinachum Sorry for the late response!
In case of data parallelism issues , every augmentation, normalizing and rescaling is a costly operation that will also slow down the process. If you can run all these operations by utilizing all the cores by processing them parallelly, then tf.data.map() can take the user-defined function containing all image augmentations that you want to apply to the dataset.
tf.data.experimental.AutotuneOptions can be used to give the options for autotuning dataset performance.

Thank you!

**Comment by sachinprasadhs** [comment]
As per my knowledge, I don't think we have any logger to find the `AUTOTUNE` value. 
tf.data.AUTOTUNE decides the best possible value based on your system configuration.

If you really want to know what value is getting taken based on your system level, the only way I can think of is to use the python level debugger to trace the code and check what value is getting assigned.
