### ISSUE TITLE
Model size i n c r e a s e s (by up to 45%!) when quantization is applied 

### ISSUE THREAD

**Issue by FranciszekNowak** [tensorflow/tensorflow#58823]
Hello,
I am now learning TFLite (using a book ,TinyML: Machine Learning with TensorFlow Lite on Arduino and Ultra-Low-Power Microcontrollers") and I have a problem with quantization.
It increases the size of my file!

I looked up the quantization example on your webpage(https://www.tensorflow.org/lite/performance/post_training_integer_quant) , but it involves integer quantization, model saving/reading and all other stuff that isn't directly related to quantization per se, which makes it harder for me to solve my particular problem. 
Same thing with code ,,from the book" - its version available on github (https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/hello_world) has been updated quite a lot since the release of the book, which means that I don't know where exactly I made a mistake.

I generally think that the whole problem is rooted in model conversion part of quantization process, because right after it I can see that the size of not-quantized model and quantized model is determined:
![obraz](https://user-images.githubusercontent.com/119885480/206506705-58157e1e-d0fd-4be2-a895-08ac17eeacb6.png)

Can you tell me, how to fix this problem? I really have no clue, despite the fact that I checked your offical documentation and tutorials. I also read the chapter about model making three times, and still, I can't find a solution.
 
Link to both of my projects:
https://colab.research.google.com/drive/1eyqMB1POAZ9qw3lPCZkiyU7zfQ0Y1OxF#scrollTo=_LGjpaXeSsnv
https://colab.research.google.com/drive/1p8Y5UpXZznejXSK7YRYJKCHulAVyKvxy
(first - sine - 1:1 as in the book. Second one - cosine - I tried to apply what I learnt independently).

**Comment by tiruk007** [comment]
@FranciszekNowak 
Could you please provide accessible colab gist or reproducible  code snippet to replicate the issue reported here.
Thank you!

**Comment by tiruk007** [comment]
@mohantym 
I was able to reproduce the issue on Colab using TF v2.11. Please find the gist here ([cosine](https://colab.research.google.com/gist/tiruk007/cf0815717aa06dfe122881388dae66f2/cosine.ipynb) & [sine](https://colab.research.google.com/gist/tiruk007/fa8ce8a907d21d677983fe0d8b75a42b/sine.ipynb)) for reference.

Thank you!

**Comment by FranciszekNowak** [comment]
Thank you very much for your effort!
I have 3 questions:
1. What did you change in my code :) ? It's almost identical.
2. Do you have any idea of why such thing as counter-quantization might have happened?
3. Why does ,,cosine" model still increase its weight after quantization (even in your example)?

**Comment by mohantym** [comment]
Hi @FranciszekNowak !
I could replicate this issue with float32 quantization and the representative dataset (Even it is sliced to batches)  (integer quantization not working).

@sachinprasadhs !
Could you look at this issue. Attached gist in [2.10,](https://colab.sandbox.google.com/gist/mohantym/fabc1b6490f095f4100becd109328974/cosine.ipynb),  [2.11](https://colab.sandbox.google.com/gist/mohantym/ec6dd7357c034bf242693a8b60c9cd5b/cosine.ipynb#scrollTo=76r2jMamhOU8) and [nightly](https://colab.sandbox.google.com/gist/mohantym/e99b9788a90961a4433c47a87559ca91/cosine.ipynb) (2.12dev) for reference.

Thank you!

**Comment by FranciszekNowak** [comment]
Thanks! @mohantym 
Thank you for your time helping beginners :)
Sadly, I got an error here - https://colab.research.google.com/gist/mohantym/e99b9788a90961a4433c47a87559ca91/cosine.ipynb#scrollTo=w68Uns6nj6Mt&line=2&uniqifier=1
I think it's caused by unmatching dtype of ,,x_value" and quantized model architecture (which was meant to accept integers for input). 
Could you send me some resource about integer quantization? I would like to dig deeper down into it.

Also, I am not sure if your solution solves the problem nonethless:

First (not-quantized) model's size is 1684 bytes and second (quantized) model's size is 2208 bytes. That means quantization still hasn't worked properly. 
That leads me to looking for another hint:
**Does anyone know how to get rid of this error message?**
```

WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.
/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert.py:778: UserWarning: Statistics for quantized inputs were expected, but not specified; continuing anyway.
  warnings.warn("Statistics for quantized inputs were expected, but not "
```
It pops up right after both conversions and I think it might be the root of the problem.
**Do you also see it on your machines? And what are the sizes of your models after quantization?**
Please tell me in case of both my original design and your proposed ones.

Also, note that my real path to python interpreter is: C:\Users\fn\miniconda3\envs\py3.7. 
Does it matter and why does colab see it differently? I don't even have a /local folder on my computer.

**Comment by sachinprasadhs** [comment]
You can refer post training quantization here https://www.tensorflow.org/lite/performance/post_training_quantization for full integer quantization.
For post training integer quantization refer the document and example given here https://www.tensorflow.org/lite/performance/post_training_integer_quant.
Hope this helps you. Thanks!

**Comment by FranciszekNowak** [comment]
Thanks, I think I am able to write code with full integer quantization now.
But how would you refer to the rest of the problems mentioned above (for example: python interpreter memory placement or persisting increase in memory)?
Please help, I am hopeless without external advice.

**Comment by grantjensen** [comment]
Using the cosine gist notebook linked above, I saw a small increase in memory size (1.5kB -> 1.9kB).  This increase comes from the representative_dataset.  This increase is expected. The reason why no decrease occurs is due to your model layers. For small Dense layers(your model only uses these), it doesn't make sense to quantize them since the latency is so low for floats anyways. If you wish to see the memory increase, experiment with using larger Dense layers. (I changed the model to use 1->512->10->1, and saw a ~4x reduction in memory).  Secondly, Google Colab does not use your local Python interpreter, so you need not worry about its path.
