### ISSUE TITLE
tf.compat.v1.profiler.profile don't report flops of ops in tf.cond

### ISSUE THREAD

**Issue by zzq96** [tensorflow/tensorflow#58829]
### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.5.1 

### Custom Code

Yes

### Current Behaviour?

A bug happened!
I use a tf.cond op in model:

```
import tensorflow as tf

@tf.function
def model(input, is_train):
    input = tf.cond(is_train, lambda: tf.subtract(input, 2, name="cond_test1"),
                    lambda: tf.multiply(input, 3, name="cond_test2"))
    input = tf.add(input, 3)
    return input


input = tf.ones([3,4])
is_train = tf.constant(1) == 1

output = model(input, is_train)

```
there are a subtract op and a multiply op in tf.cond.

then i  try to get flops of "model":
```
graph = model._list_all_concrete_functions()[-1].graph


builder = tf.compat.v1.profiler.ProfileOptionBuilder
opts = (builder(builder.trainable_variables_parameter()).with_file_output(
    "cond_test_flops.log").with_accounted_types(['.*']).select(["float_ops"
                                                                ]).build())
tfprof_node = tf.compat.v1.profiler.profile(graph, options=opts)
``` 

I print the flops detail log and found the ops in tf.cond are ignored, only an add op's flops is reported
```
Profile:
node name | # float_ops
_TFProfRoot (--/12 flops)
  Add (12/12 flops). // only an Add op 
    Add/y (0/0 flops)
  Identity (0/0 flops)
  cond (0/0 flops)
    cond/Identity (0/0 flops)
  input (0/0 flops)
  is_train (0/0 flops)
```
```

**Comment by rabbitboizaaa** [comment]
> Click to expand!

**Comment by zzq96** [comment]
> > Click to expand!

hi，i have updated

**Comment by sushreebarsa** [comment]
@zzq96 I was able to run the code without any error using TF [v2.5 ](https://colab.research.google.com/gist/sushreebarsa/466a4227adfce62a5b277da24d70d8e2/58829-2-5.ipynb)and faced a warning using TF v[2.11](https://colab.research.google.com/gist/sushreebarsa/82c8ed714385d02a7822b759a5748eb5/untitled766.ipynb#scrollTo=YnuVVdifRVBX) on colab , please find the attached gists. Could you please check and confirm the same?
Thank you!
