### ISSUE TITLE
`mypy` compatibility: missing `py.typed`

### ISSUE THREAD

**Issue by Corwinpro** [tensorflow/tensorflow#58837]
### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

tf 2.8, tf 2.10

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04, macOS Ventura arm

### Python version

3.7, 3.10

### Current Behaviour?

`mypy` is one of the great tools that many people use to run type checking via type annotations. Unfortunatelly, `tensorflow` does not play very nicely with it. As specified in the examples, many `tensorflow`-based objects are seen as `Any` by `mypy`. This can lead to various unexpected (and confusing) behaviour in the code that depends on `tensorflow`.

### Extra change required

IIUC this is an invalid type annotation according to `mypy`:

https://github.com/tensorflow/tensorflow/blob/bff338f421322c2ccd1d7e2c5e24ff6c1b0c133c/tensorflow/python/ops/ragged/dynamic_ragged_shape.py#L206

Changing to 

               static_inner_shape: Any = None):

should solve the problem (of course a more specific type annotation would be better).

### Proposed solution

I suspect that this is because a single file is missing to make `tensorflow` type annotations recognised by `mypy`: `py.typed`. Adding that file resolves the issue, and stops `mypy` from treating tensorflow entities as `Any`.

Please kindly let me know if I missed anything.

### Basic example

```python
import tensorflow as tf

reveal_type(tf.Tensor)
```

Without `py.typed`: 

```console
error: Skipping analyzing "tensorflow": module is installed, but missing library stubs or py.typed marker  [import]
note: Revealed type is "Any"
```

With `py.typed`: 

```console
Revealed type is "def (op: Any, value_index: Any, dtype: Any) -> tensorflow.python.framework.ops.Tensor"
```

### More complicated example

(comments explain what is seen without `py.typed`)

```python
import tensorflow as tf


class A(tf.Module):
    pass


class B(A):
    def foo(self) -> str:
        return "foo"


class C(B):
    def __init__(self, value: int) -> None:
        super().__init__()
        self.value = value


class D1(C):
    pass


class D2(C):
    def __init__(self, value: int) -> None:
        super().__init__(value)

    def do_something(self) -> int:
        return self.value


class D3(C):
    def do_something(self) -> int:
        return self.value


reveal_type(A())  # Reveals 'A' <- OK
reveal_type(B())  # Reveals 'B' <- OK
reveal_type(B().foo)  # Reveals 'str' <- OK
reveal_type(C(1))  # Reveals 'C' <- OK
reveal_type(D1(1))  # Reveals 'C' <- ??? 'D1' expected
reveal_type(D2(1))  # Reveals 'D2' <- OK but why?
reveal_type(D2(1).do_something)  # Reveals 'int` <- OK
reveal_type(D3(1))  # Reveals 'C' <- ??? 'D3' expected
reveal_type(D3(1).do_something)   # Reveals 'Any' <- ??? 'int' expected
```

With `py.typed` everything is as expected:

```console
tf_mypy.py:36: note: Revealed type is "tf_mypy.A"
tf_mypy.py:37: note: Revealed type is "tf_mypy.B"
tf_mypy.py:38: note: Revealed type is "def () -> builtins.str"
tf_mypy.py:39: note: Revealed type is "tf_mypy.C"
tf_mypy.py:40: note: Revealed type is "tf_mypy.D1"
tf_mypy.py:41: note: Revealed type is "tf_mypy.D2"
tf_mypy.py:42: note: Revealed type is "def () -> builtins.int"
tf_mypy.py:43: note: Revealed type is "tf_mypy.D3"
tf_mypy.py:44: note: Revealed type is "def () -> builtins.int"
```

**Comment by tiruk007** [comment]
@sushreebarsa 
I was able to reproduce the issue on Colab using TF v2.11. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/1073413b5c95eb7855e67b37bfc7ec71/58837.ipynb) and [attachment](https://github.com/tensorflow/tensorflow/files/10222234/my.zip) for reference.
Thank you!

**Comment by Corwinpro** [comment]
Could we please have an update for this?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
