### ISSUE TITLE
Tensorflow compilation fails on Raspberry 32bit compute module with message "error: static assertion failed: Source and destination types should have equal sizes."

### ISSUE THREAD

**Issue by schindam** [tensorflow/tensorflow#58845]
I am trying to compile Tensorflow on Rpi 32bit 4GB board and encountered compilation failure after 14 hours. I have been following https://qengineering.eu/install-tensorflow-2.1.0-on-raspberry-pi-4.html and compiled Bezel before this.

Following is the git HEAD of Tensorflow code I sync'ed:

commit fcdf659347024dc5a3130e866ba3dde10bac72b0 (HEAD, tag: v2.5.0-rc3)
Merge: a7b36464407 efe04c1b561
Author: Mihai Maruseac <mihaimaruseac@google.com>
Date:   Tue May 4 16:35:43 2021 -0700

    Merge pull request #48904 from tensorflow-jenkins/version-numbers-2.5.0rc3-13515

    Update version numbers for TensorFlow 2.5.0-rc3

This is the command I used:

$ sudo bazel --host_jvm_args=-Xmx1624m build \
             --config=noaws \
             --config=nogcp \
             --config=nohdfs \
             --config=nonccl \
             --config=monolithic \
             --config=v2 \
             --local_cpu_resources=1 \
             --copt=-mfpu=neon-vfpv4 \
             --copt=-ftree-vectorize \
             --copt=-funsafe-math-optimizations \
             --copt=-ftree-loop-vectorize \
             --copt=-fomit-frame-pointer \
             --copt=-DRASPBERRY_PI \
             --host_copt=-DRASPBERRY_PI \
             --linkopt=-Wl,-latomic \
             --host_linkopt=-Wl,-latomic \
             //tensorflow/tools/pip_package:build_pip_package

Following is the snippet from "lscpu" command output of my Rpi:

Architecture:                    armv7l
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3

Following is the compilation error:

INFO: Found 1 target...
ERROR: tensorflow/tensorflow/compiler/xla/service/llvm_ir/BUILD:64:11: C++ compilation of rule '//tensorflow/compiler/xla/service/llvm_ir:llvm_util' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 180 argument(s) skipped)
In file included from tensorflow/compiler/xla/service/llvm_ir/llvm_util.cc:22:
external/com_google_absl/absl/base/casts.h: In instantiation of 'Dest absl::lts_2020_09_23::bit_cast(const Source&) [with Dest = long long int; Source = void (*)(const char*, long long int); typename std::enable_if<(! absl::lts_2020_09_23::internal_casts::is_bitcastable<Dest, Source>::value), int>::type <anonymous> = 0]':
tensorflow/compiler/xla/service/llvm_ir/llvm_util.cc:382:76:   required from here
external/com_google_absl/absl/base/casts.h:176:30: error: static assertion failed: Source and destination types should have equal sizes.
  176 |   static_assert(sizeof(Dest) == sizeof(Source),
      |                 ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
external/com_google_absl/absl/base/casts.h: In instantiation of 'Dest absl::lts_2020_09_23::bit_cast(const Source&) [with Dest = long long int; Source = const char*; typename std::enable_if<(! absl::lts_2020_09_23::internal_casts::is_bitcastable<Dest, Source>::value), int>::type <anonymous> = 0]':
tensorflow/compiler/xla/service/llvm_ir/llvm_util.cc:384:55:   required from here
external/com_google_absl/absl/base/casts.h:176:30: error: static assertion failed: Source and destination types should have equal sizes.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /media/sharathchandra/databox/sources/tensorflow_compilation/tensorflow/tensorflow/python/tools/BUILD:227:10 C++ compilation of rule '//tensorflow/compiler/xla/service/llvm_ir:llvm_util' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 180 argument(s) skipped)
INFO: Elapsed time: 1457.007s, Critical Path: 136.90s
INFO: 199 processes: 7 internal, 192 local.
FAILED: Build did NOT complete successfully

**Comment by mohantym** [comment]
Hi @schindam !
Sorry for the late response.

Please refer documentations from [TFlite-runtime for linux devices](https://www.tensorflow.org/lite/guide/python) and [Cmake for arm](https://www.tensorflow.org/lite/guide/build_cmake_arm) device to raspberry usage.
It saves space and speed up inference time by using Lite run time (in the edge device).

Thank you!

**Comment by schindam** [comment]
Thank you. As the reference links are changed, a different direction is now pursued. We can close this ticket.
