### ISSUE TITLE
How to calculate the model's flops when I use tensorflow?

### ISSUE THREAD

**Issue by ljw-struggle** [tensorflow/tensorflow#58848]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### Current Behaviour?

```shell
I don't find a good way to calculate the model's flops by tensorflow.
```

### Standalone code to reproduce the issue

```shell
I don't find a good way to calculate the model's flops by tensorflow.
```

### Relevant log output

```shell
I don't find a good way to calculate the model's flops by tensorflow.
```
</details>

**Comment by bhack** [comment]
Check:
https://github.com/keras-team/keras/issues/16699
https://github.com/keras-team/keras/issues/17273

**Comment by tiruk007** [comment]
@ljw-struggle 
Could you please find the gist of work around [here](https://colab.research.google.com/gist/tiruk007/de99bc72b0b2ec27585506a23122e3e0/58848.ipynb) and refer to the above [comment](https://github.com/tensorflow/tensorflow/issues/58848#issuecomment-1345636580) and similar [issue](https://github.com/tensorflow/tensorflow/issues/32809). Let us know if it helps.

Thank you!
