### ISSUE TITLE
Tensor slice is too large to serialize

### ISSUE THREAD

**Issue by ericyue** [tensorflow/tensorflow#5884]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

I have read the realted isssue  https://github.com/tensorflow/tensorflow/issues/4291 , but it's not solved.

### Environment info
centos with cpu support and tensorflow latest version

no cuda or cudnn

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

I am build a 4 layer network (128*64*64*32), input_unit feature size 20000000（sparse feature size）,  when train the model ,it errors that "Tensor slice is too large to serialize".

my training code is like this https://github.com/tobegit3hub/deep_recommend_system/blob/master/a8a_classifier.py

### What other attempted solutions have you tried?

nothing , it's seems that a protobuf limitation , but I want to know how to solve this with changes in my training code 

### Logs or other output that would be helpful
"Tensor slice is too large to serialize"

**Comment by prb12** [comment]
Please can you provide the information requested in the issues reporting template.

**Comment by ericyue** [comment]
@prb12  done

**Comment by poxvoculi** [comment]
In the related thread you cite, there is a suggestion from @concretevitamin:
" a quick workaround is to use, for variables, tf.get_variable(..., partitioner=..), and for non-ref tensors, tf.split(). "

Is this not feasible for your model?

**Comment by concretevitamin** [comment]
+1 to @poxvoculi.  Also, if you use the unofficial 0.12 branch (the official release is coming soon), the Saver and the default checkpoint format have been updated to handle this case.

**Comment by ericyue** [comment]
thanks @poxvoculi , I tried ,but cannot find any documents about the partitioner usage.

**Comment by ericyue** [comment]
@concretevitamin  with 0.12 , it's support large network parameter?  without any modification of my code?   I'll try this version :)

**Comment by ericyue** [comment]
@concretevitamin  thanks, it's worked in 0.12rc

**Comment by concretevitamin** [comment]
@ericyue Great to know it's working now!  (Re your previous question: `tf.get_variable()` has a `partitioner` field.)
