### ISSUE TITLE
Memory leak problem due to multi-line comments

### ISSUE THREAD

**Issue by Armature** [tensorflow/tensorflow#58856]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

None

### Python version

3.8.10

### Bazel version

5.3.2

### GCC/Compiler version

9.4.0

### CUDA/cuDNN version

Used CPU build

### GPU model and memory

Used CPU build

### Current Behaviour?

```shell
Multi-line comments are not ignored by the compiler(?), and loaded to memory.
Both source build installation on local machine and pip binary installation were tested.
I suggest changing all multi-line comments to single line comments.
```

### Standalone code to reproduce the issue

```shell
Following github repo. can reproduce the issue.
https://github.com/Armature/dump_memory
```

### Relevant log output

```shell
15751362 bytes of 35521408 bytes ( 44.3433% ) are alphabets.
```
</details>

**Comment by Armature** [comment]
I found out """...""" expressions are docstrings, not comments. So these expressions are intended.
But if they're using up a significant portion of memory when running ML applications, why should they be included?

**Comment by sachinprasadhs** [comment]
Hi, Thanks for creating an issue.
`Docstrings` are important to record the API behavior and a sample example for the users to start with and the same information is displayed in our TensorFlow website.
To ensure the code readability we limit the number of characters per line to 80.
 For example consider the API `tf.keras.layers.Conv2D`, If users wants to know the details about the API, it will be loaded like below.
![image](https://user-images.githubusercontent.com/73069040/222574277-296cf6df-41c3-44e1-a937-9fde7a0dbe5a.png)
