### ISSUE TITLE
How to reduce power consumption for gpu delegate on android

### ISSUE THREAD

**Issue by mengran1234** [tensorflow/tensorflow#58855]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

2.10 or 2.11

### Custom Code

Yes

### OS Platform and Distribution

android

### Mobile device

android

### Python version

3.7

### Bazel version

no 

### GCC/Compiler version

no

### Current Behaviour?

```shell
Here it is not a bug.
I want to  reduce power consumption for gpu delegate on android,because I find the execution of tflite model using gpu occupys many power（mA）.
I use opencl backend.
Do you have some optimization method in order to reduce power of model. Thank you very much
```

### Standalone code to reproduce the issue

```shell
my configuration is following,
 TfLiteGpuDelegateOptionsV2 gpu_options = TfLiteGpuDelegateOptionsV2Default();
  gpu_options.inference_priority1 =
      TFLITE_GPU_INFERENCE_PRIORITY_MIN_MEMORY_USAGE;
  gpu_options.inference_priority2 = TFLITE_GPU_INFERENCE_PRIORITY_MIN_LATENCY;
  gpu_options.inference_priority3 = TFLITE_GPU_INFERENCE_PRIORITY_MAX_PRECISION;
  gpu_options.experimental_flags |= TFLITE_GPU_EXPERIMENTAL_FLAGS_ENABLE_QUANT;
 gpu_options.inference_preference =
      TFLITE_GPU_INFERENCE_PREFERENCE_FAST_SINGLE_ANSWER;
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @chenliang110 !
You have correctly prioritised the flags for gpu options.
Can you comment out one or two gpu options flag (excluding the min memory usage one) and let us know whether memory usage gets optimised or not 
  ```
 gpu_options.inference_priority1 =
      TFLITE_GPU_INFERENCE_PRIORITY_MIN_MEMORY_USAGE;
  gpu_options.inference_priority2 = TFLITE_GPU_INFERENCE_PRIORITY_MIN_LATENCY;
  #gpu_options.inference_priority3 = TFLITE_GPU_INFERENCE_PRIORITY_MAX_PRECISION;   
 gpu_options.inference_preference =
      TFLITE_GPU_INFERENCE_PREFERENCE_FAST_SINGLE_ANSWER; #comment  it out if necessary
```

Thank you!

**Comment by mengran1234** [comment]
> gpu_options.inference_priority1 =
>     TFLITE_GPU_INFERENCE_PRIORITY_MIN_MEMORY_USAGE;
> gpu_options.inference_priority2 = TFLITE_GPU_INFERENCE_PRIORITY_MIN_LATENCY;
> #gpu_options.inference_priority3 = TFLITE_GPU_INFERENCE_PRIORITY_MAX_PRECISION;   
> gpu_options.inference_preference =
>     TFLITE_GPU_INFERENCE_PREFERENCE_FAST_SINGLE_ANSWER; #comment  it out if necessary

do you mean that I use following options to test?


gpu_options.inference_priority1 = TFLITE_GPU_INFERENCE_PRIORITY_MIN_LATENCY; 
gpu_options.inference_priority2 =
    TFLITE_GPU_INFERENCE_PRIORITY_MIN_MEMORY_USAGE;
gpu_options.inference_preference =
    TFLITE_GPU_INFERENCE_PREFERENCE_FAST_SINGLE_ANSWER;

**Comment by mengran1234** [comment]
I am sorry I've been replying to you for so long。I was busy with other things a while ago。

**Comment by mohantym** [comment]
Hi @mengran1234 !

Could you confirm whether this issue has been resolved with the work around from above [comment](https://github.com/tensorflow/tensorflow/issues/58855#issuecomment-1365683597).
Feel free to re-open if needed.

Thank you!

**Comment by jnasti1** [comment]
> > gpu_options.inference_priority1 =
> > TFLITE_GPU_INFERENCE_PRIORITY_MIN_MEMORY_USAGE;
> > gpu_options.inference_priority2 = TFLITE_GPU_INFERENCE_PRIORITY_MIN_LATENCY;
> > #gpu_options.inference_priority3 = TFLITE_GPU_INFERENCE_PRIORITY_MAX_PRECISION;
> > gpu_options.inference_preference =
> > TFLITE_GPU_INFERENCE_PREFERENCE_FAST_SINGLE_ANSWER; #comment  it out if necessary
> 
> do you mean that I use following options to test?
> 
> gpu_options.inference_priority1 = TFLITE_GPU_INFERENCE_PRIORITY_MIN_LATENCY; gpu_options.inference_priority2 = TFLITE_GPU_INFERENCE_PRIORITY_MIN_MEMORY_USAGE; gpu_options.inference_preference = TFLITE_GPU_INFERENCE_PREFERENCE_FAST_SINGLE_ANSWER;

I think they meant to only set priority1 = MIN_LATENCY, and comment out the priority2 and 3 lines (so instead of specifying them, they use the default which is AUTO)
