### ISSUE TITLE
How to get single UnidirectionalSequenceRnnOp in tflite model

### ISSUE THREAD

**Issue by SlavikMIPT** [tensorflow/tensorflow#58854]
### Issue Type

Support

### Source

source

### Tensorflow Version

2.8

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 18.04

According to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc there is `kUnidirectionalSequenceRnnOp` as a single operation in tflite, could you give a python code example - how can I get this? For example - this code for LSTM gives tflite with one UnidirectionalSequenceLSTM Op.
```py
# NOTE tested with TF 2.8.0
import tensorflow as tf
import numpy as np

from tensorflow import keras


model = keras.Sequential()
shape = (4, 4)

model.add(keras.layers.InputLayer(input_shape=shape, batch_size=1))
model.add(keras.layers.LSTM(2, input_shape=shape))
```
![image](https://user-images.githubusercontent.com/4616940/197647526-59c63de2-df61-46a1-bd61-75baa2688376.png)
How can I do same for UnidirectionalSequenceRnn?

**Comment by mohantym** [comment]
Hi @SlavikMIPT !
Please check with [RNN to TFlite documentation](https://www.tensorflow.org/lite/models/convert/rnn#user-defined_lstm_conversion_examples) /[Fusion code lab](https://colab.sandbox.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb) instructions and let us know whether it address this requirement or not.

Thank you!

**Comment by SlavikMIPT** [comment]
> Hi @SlavikMIPT ! Please check with [RNN to TFlite documentation](https://www.tensorflow.org/lite/models/convert/rnn#user-defined_lstm_conversion_examples) /[Fusion code lab](https://colab.sandbox.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb) instructions and let us know whether it address this requirement or not.
> 
> Thank you!

This works for UnidirectionalSequenceLSTM, but not for UnidirectionalSequenceRNN

**Comment by mohantym** [comment]
@SlavikMIPT !
Could you provide a sample toy model to replicate this issue.
Thank you!
