### ISSUE TITLE
tensorflow installation not working on apple silicon macs

### ISSUE THREAD

**Issue by ameyb22** [tensorflow/tensorflow#58869]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

tf 2.11

### Custom Code

Yes

### OS Platform and Distribution

MacOS 13.0.1 Ventura

### Mobile device

apple silicon m1

### Python version
(major, minor, micro, releaselevel, serial)
(3, 10, 8, 'final', 0)

### Current Behaviour?

```shell
Whenever I'm importing TensorFlow it's giving me an error. it was working fine yesterday when I had tf 2.10 but it's not working with 2.11. I was hoping everything would go smoothly.
```

### Standalone code to reproduce the issue

```shell
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:41:22) [Clang 13.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tf/lib/python3.10/site-packages/tensorflow/__init__.py", line 443, in <module>
    _ll.load_library(_plugin_dir)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/tf/lib/python3.10/site-packages/tensorflow/python/framework/load_library.py", line 151, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/opt/homebrew/Caskroom/miniforge/base/envs/tf/lib/python3.10/site-packages/tensorflow-plugins/libmetal_plugin.dylib, 0x0006): symbol not found in flat namespace '__ZN3tsl8internal10LogMessage16VmoduleActivatedEPKci'
>>> exit()
```

### Relevant log output
== check python ===================================================
python version: 3.10.8
python branch: 
python build version: ('main', 'Nov 22 2022 08:25:29')
python compiler version: Clang 14.0.6 
python implementation: CPython

== check os platform ===============================================

== are we in docker =============================================
No

== compiler =====================================================
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin22.1.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

== check pips ===================================================
numpy                         1.23.2
protobuf                      3.19.4
tensorflow-estimator          2.11.0
tensorflow-macos              2.11.0
tensorflow-metal              0.7.0

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.version.VERSION = 2.11.0
tf.version.GIT_VERSION = unknown
tf.version.COMPILER_VERSION = Apple LLVM 13.1.6 (clang-1316.0.21.1)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
./tensorflow-script.sh: line 147: nvidia-smi: command not found

== cuda libs  ===================================================

== tensorflow installed from info ==================

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 10, 8, 'final', 0)

== bazel version  ===============================================

**Comment by kp3393** [comment]
Hello @ameyb22,
Yes, people are facing issues with 2.11, but it is with the `model.fit()` method. Here, you can read about it https://developer.apple.com/forums/thread/721619.

FYI, there is a newer version 0.7.0 available for [tensorflow-metal](https://pypi.org/project/tensorflow-metal/). Perhaps, also update this package?

**Comment by ameyb22** [comment]
> Hello @ameyb22, Yes, people are facing issues with 2.11, but it is with the `model.fit()` method. Here, you can read about it https://developer.apple.com/forums/thread/721619.
> 
> FYI, there is a newer version 0.7.0 available for [tensorflow-metal](https://pypi.org/project/tensorflow-metal/). Perhaps, also update this package?

right, I fixed the import issue by not installing TensorFlow-dataset and TensorFlow-hub, which were causing compatibility issues. however, now I'm facing the same issue you mentioned... I even tried with a custom training loop, I feel something might be broken in the background.

**Comment by kp3393** [comment]
As mentioned in the developer thread, the problem might be with the new updates in TF 2.11. 
Especially with the changes in Keras Optimizer API [reference 1](https://blog.tensorflow.org/2022/11/whats-new-in-tensorflow-211.html), [reference 2](https://github.com/tensorflow/tensorflow/releases). 
For the time being, the workaround is to use 2.10 or import optimizer from the `tf.keras.optimizers.legacy` namespace.

Hopefully, the TF team will provide us with a better solution.

**Comment by ameyb22** [comment]
> `tf.keras.optimizers.legacy`
Let's see what happens and what does not, thanks for this though...

**Comment by sushreebarsa** [comment]
@ameyb22 Could you please refer to the thread [here](https://stackoverflow.com/questions/72964800/what-is-the-proper-way-to-install-tensorflow-on-apple-m1-in-2022) and check this tested build [configuration](https://www.tensorflow.org/install/source#macos)s?
Please let us know if it helps?
Thank you!
