### ISSUE TITLE
Cannot make use of GPU

### ISSUE THREAD

**Issue by AntouanK** [tensorflow/tensorflow#58875]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

v2.11.0-rc2-17-gd5b57ca93e5

### Custom Code

Yes

### OS Platform and Distribution

Linux Manjaro 6.0.11

### Python version

3.9

### CUDA/cuDNN version

12

### GPU model and memory

RTX 4090

### Current Behaviour?

```shell
Cannot make use of the GPU when trying to use this app ( https://github.com/allo-/virtual_webcam_background ).

I changed the code to test the tensorflow lib and I followed all the steps mentioned here : https://www.tensorflow.org/install/pip . Still not working.

Including a test script below, to see what I mean.

I tried installing all the packages about tf and cuda. Both on my machine and on the conda env ( or pip ).

Any ideas how to solve this?

Thank you.
```

### Standalone code to reproduce the issue

```shell
#!/usr/bin/env python3

import tensorflow as tf
import sys
import os
import yaml

print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

cuda_devices = os.getenv('CUDA_VISIBLE_DEVICES')
print("cuda_devices", cuda_devices)

if cuda_devices is None:
    os.unsetenv('CUDA_VISIBLE_DEVICES')
else:
    os.putenv('CUDA_VISIBLE_DEVICES', cuda_devices)

try:
    import mediapipe as mp
    classifier = mp.solutions.selfie_segmentation.SelfieSegmentation(
            model_selection=1)
    HAS_MEDIAPIPE = True
except ImportError:
    HAS_MEDIAPIPE = False
```

### Relevant log output

```shell
python ./virtual_webcam.py
2022-12-13 11:19:04.927313: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-13 11:19:05.784273: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/antouank/.conda/envs/virtual-webcam/lib/
2022-12-13 11:19:05.784815: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/antouank/.conda/envs/virtual-webcam/lib/
2022-12-13 11:19:05.784829: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Num GPUs Available:  1
cuda_devices None
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```
</details>

**Comment by AntouanK** [comment]
thanks for the answer.

not sure how to do all that.
so far I only installed cuda/tensorflow related packages from pacman ( arch ) or pip/conda ( python ).
I haven't built anything from source.

Could you maybe give me a hint on how to try that?

**Comment by mohantym** [comment]
Hi @AntouanK !
Attached [sample bazel notebook  ](https://colab.research.google.com/gist/mohantym/d7479993bd95a7ad4f2bb028ca5d8d0d/tensorflow-ranking.ipynb?authuser=1#scrollTo=S5Hx3MWN1c5j)for reference. 

Please give us an update after you modify your commands as per above [comment](https://github.com/tensorflow/tensorflow/issues/58875#issuecomment-1350767004).

Thank you!

**Comment by AntouanK** [comment]
@mohantym 
I opened the notebook you mentioned and I connected it to my local runtime.

On the 3rd step I get an error
![image](https://user-images.githubusercontent.com/4569111/208082005-09fe93c7-c5bc-4dd8-8903-79350fa172e6.png)

**Comment by AntouanK** [comment]
@mohantym  got an error on this step

```
!bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu
```


![image](https://user-images.githubusercontent.com/4569111/208084600-f54b6bd9-f20b-4f99-ba23-4fa11b4e19ea.png)

**Comment by AntouanK** [comment]
So, I managed to build it successfully.

![image](https://user-images.githubusercontent.com/4569111/208090788-c450f978-0b29-4cae-a257-a9c15dcb7864.png)

Not sure what the next step is.

Running that executable doesn't do anything.

![image](https://user-images.githubusercontent.com/4569111/208090908-871a2164-d0b9-48df-a1e0-b0ec75790363.png)

**Comment by mohantym** [comment]
@AntouanK !
Thanks for the update on the build the executable.
Could you run the executable along the .pbtxt and selfi-segmentation.py file then
```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/selfie_segmentation/selfie_segmentation_gpu\
  --calculator_graph_config_file=mediapipe/graphs/hand_tracking/selfie_segmentation_desktop_live_gpu.pbtxt
```
Thank you!

**Comment by AntouanK** [comment]
> @AntouanK ! Thanks for the update on the build the executable. Could you run the executable along the .pbtxt and selfi-segmentation.py file then
> 
> ```
> GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/selfie_segmentation/selfie_segmentation_gpu\
>   --calculator_graph_config_file=mediapipe/graphs/hand_tracking/selfie_segmentation_desktop_live_gpu.pbtxt
> ```
> 
> Thank you!

that pbtxt file doesn't exist in my directory

![image](https://user-images.githubusercontent.com/4569111/208233756-f422ee56-3e8a-4642-80cc-58bb9dff8bff.png)


If I change the command to 
```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/selfie_segmentation/selfie_segmentation_gpu\
  --calculator_graph_config_file=mediapipe/graphs/selfie_segmentation/selfie_segmentation_gpu.pbtxt
```
I get a window with my face and a blue background.
FPS is 60 so it works great with GPU.
Logs :

```
GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/selfie_segmentation/selfie_segmentation_gpu\
  --calculator_graph_config_file=mediapipe/graphs/selfie_segmentation/selfie_segmentation_gpu.pbtxt
I20221217 08:44:09.572886  7106 demo_run_graph_main_gpu.cc:52] Get calculator graph config contents: # MediaPipe graph that performs selfie segmentation with TensorFlow Lite on GPU.

# GPU buffer. (GpuBuffer)
input_stream: "input_video"

# Output image with rendered results. (GpuBuffer)
output_stream: "output_video"

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Subgraph that performs selfie segmentation.
node {
  calculator: "SelfieSegmentationGpu"
  input_stream: "IMAGE:throttled_input_video"
  output_stream: "SEGMENTATION_MASK:segmentation_mask"
}


# Colors the selfie segmentation with the color specified in the option.
node {
  calculator: "RecolorCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  input_stream: "MASK_GPU:segmentation_mask"
  output_stream: "IMAGE_GPU:output_video"
  node_options: {
    [type.googleapis.com/mediapipe.RecolorCalculatorOptions] {
      color { r: 0 g: 0 b: 255 }
      mask_channel: RED
      invert_mask: true
      adjust_with_luminance: false
    }
  }
}
I20221217 08:44:09.573503  7106 demo_run_graph_main_gpu.cc:58] Initialize the calculator graph.
I20221217 08:44:09.575413  7106 demo_run_graph_main_gpu.cc:62] Initialize the GPU.
I20221217 08:44:09.586948  7106 gl_context_egl.cc:84] Successfully initialized EGL. Major : 1 Minor: 5
I20221217 08:44:09.631047  7123 gl_context.cc:342] GL version: 3.2 (OpenGL ES 3.2 NVIDIA 525.60.11)
I20221217 08:44:09.631196  7106 demo_run_graph_main_gpu.cc:68] Initialize the camera or load the video.
[ WARN:0@1.143] global /build/opencv/src/opencv-4.6.0/modules/videoio/src/cap_gstreamer.cpp (1405) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
I20221217 08:44:14.342898  7106 demo_run_graph_main_gpu.cc:89] Start running the calculator graph.
I20221217 08:44:14.346335  7106 demo_run_graph_main_gpu.cc:94] Start grabbing and processing frames.
INFO: Created TensorFlow Lite delegate for GPU.
I20221217 08:45:28.767011  7106 demo_run_graph_main_gpu.cc:186] Shutting down.
I20221217 08:45:28.874738  7106 demo_run_graph_main_gpu.cc:200] Success!
```

:+1: 

Now the problem is that I don't know how to use that for my purpose.
All I want is to have a fake background for my webcam when I use it for video calls.
Can I combine this with the python scrips I found on github?


Also, 2 more questions.

1. 
How do I change resolution?
My webcam is 1920x1080 but the window I get has a way smaller resolution.

2.
The area around my face is very pixelated. Is there a way to fine tune this to be smoother or something?


Thank you so much for all the help.
![image](https://user-images.githubusercontent.com/4569111/208234018-ab792281-3007-4979-9e00-7daa4132b7b4.png)

**Comment by mohantym** [comment]
@AntouanK !
You can resize the images using opencv and also do the same w.r.to Medipipe framework and calculators. 

Please check in the closed issue in [Mediapipe ](https://github.com/google/mediapipe)repo/ [TF-forum](https://discuss.tensorflow.org/tag/tflite)  for further assistance.

Marking this issue to resolved now from above [comment](https://github.com/tensorflow/tensorflow/issues/58875#issuecomment-1356124090) as original issue on using GPU is resolved.
Thank you !

**Comment by AntouanK** [comment]
@mohantym 

> You can resize the images using opencv and also do the same w.r.to Medipipe framework and calculators.

I don't understand that at all.
All I have is an executable and a `.pbtxt` file that I don't know what language it's in.
I don't see any way to resize anything or how to configure it or pass the input/output, or use it with python.

I understand that the "can it use the GPU" issue is closed, but I'm totally clueless on how to use that binary that I've built in conjunction with python or js.
Any hint on how to do that?

Thank you.

**Comment by mohantym** [comment]
Hi @AntouanK !
Attached below code snippet for image resizing.
[Ref](https://www.geeksforgeeks.org/image-resizing-using-opencv-python/)

You can use super-resolution api from Tensorflow to clear the pixelation issue.
Ref [1](https://www.tensorflow.org/hub/tutorials/image_enhancing), [2](https://www.tensorflow.org/lite/examples/super_resolution/overview).

Thank you!

**Comment by AntouanK** [comment]
@mohantym thank you for the answer, but I think I'm not clear on my question.

I don't understand how I can combine a python script, with an executable binary that accepts some sort of protobuf(?) graph file.
How am I supposed to use those two together?

That binary I built with bazel, how can it be used from any other python script on my machine?
Can you please point on how to do that?
I've googled a lot but cannot find anything close to an answer.

The tensorflow website is huge, I don't even know where to start in order to understand how to combine the two.

**Comment by mohantym** [comment]
@AntouanK !
Could you try building the delegate using sample bazel notebook and use [load delegate ](https://www.tensorflow.org/api_docs/python/tf/lite/experimental/load_delegate)option to load the same gpu delegates.

Thank you!
