### ISSUE TITLE
[DTensor] Does DTensor work directly under the eager mode?

### ISSUE THREAD

**Issue by aoyulong** [tensorflow/tensorflow#58872]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

binary

### Tensorflow Version

tf 2.11

### Custom Code

No

### Current Behaviour?

```shell
From the [document](https://www.tensorflow.org/tutorials/distribute/dtensor_ml_tutorial), it seems that DTensor only work with tf.function.
```

### Standalone code to reproduce the issue

```shell
The [document](https://www.tensorflow.org/tutorials/distribute/dtensor_ml_tutorial) does not explicitly state whether DTensor works in eager or graph mode.
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @aoyulong !
Most of processes in above  Dtensor  distribute tutorial seems to be running in eager mode except the [Training step](https://www.tensorflow.org/tutorials/distribute/dtensor_ml_tutorial#training_step) to trace the operations and give more flexibility to run in other devices(including mobiles).

Thank you!

**Comment by aoyulong** [comment]
Thanks. So the training step should be traced when using DTensor.

**Comment by mohantym** [comment]
Yeah @aoyulong ! 

Tracing is necessary for Training.
Can we mark your query as resolved then.

Thank you!

**Comment by aoyulong** [comment]
Thanks. The problem was solved.

**Comment by mohantym** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
