### ISSUE TITLE
Convert both model and post processing to tflite model

### ISSUE THREAD

**Issue by AntoineChauviere** [tensorflow/tensorflow#58874]
Hello,

I used TFOD2 to train an SSD model. I can convert it to tflite but I don't have the same results because of pre/post processing.

I was wondering if it was possible to convert the model and pre/post processing to a global tflite model?

Here is my function:

```
 @tf.function
    def detect_fn(image):
        image, shapes = detection_model.preprocess(image)
        prediction_dict = detection_model.predict(image, shapes)
        detections = detection_model.postprocess(prediction_dict, shapes)
        return detections
```

**Comment by tiruk007** [comment]
@AntoineChauviere 
Can you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) and also provide standalone code to reproduce the issue reported here.

Thank you!
