### ISSUE TITLE
TfLite build using CMake fails in official Docker container

### ISSUE THREAD

**Issue by derpda** [tensorflow/tensorflow#58884]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.12.0?

### Custom Code

No

### OS Platform and Distribution

Arch Linux 6.0.12-arch1-1

### Mobile device

Pixel 3a

### Python version

N/A

### Bazel version

cmake 3.16.3

### GCC/Compiler version

NDK r25b

### Current Behaviour?

```shell
I am using `tensorflow/tensorflow:devel` as a base image (see Dockerfile contents below), which seems to ship with tensorflow 2.12.0 (latest version listed in RELEASE.md).

I am following the [official cmake build instructions](https://www.tensorflow.org/lite/guide/build_cmake) for cross-compilation for Android.
During the build step (`cmake --build . -j`), an error occurs (see logs below).

I have also tried this with the the [latest 2.11.0 release](https://github.com/tensorflow/tensorflow/releases/tag/v2.11.0), with the same result.

Using older versions of the NDK causes different errors, about which I can post issues if needed.

If possible, I would like working instructions to build TfLite with CMake (I have unsuccessfully tried the Bazel build as well).
```

### Standalone code to reproduce the issue

Dockerfile:
```dockerfile
FROM tensorflow/tensorflow:devel

RUN apt-get update &&\
    DEBIAN_FRONTEND=noninteractive apt-get install -y cmake
RUN mkdir /downloads
RUN cd /downloads &&\
    curl -s https://dl.google.com/android/repository/android-ndk-r25b-linux.zip \
        --output android-ndk.zip
RUN cd /downloads && unzip android-ndk.zip && mv android-ndk-r25b
```

Build with
```
docker build . -t tflite-build-test
```

Run with
```
docker run -it --rm tflite-build-test bash
```

Inside container
```
mkdir tensorflow_src/build
cd tensorflow_src/build
cmake -DCMAKE_TOOLCHAIN_FILE=../../android-ndk-r25b/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a ../tensorflow/lite
cmake --build . -j
```
```


### Relevant log output

```shell
Traceback (most recent call last):
  File "scripts/generate_code.py", line 148, in <module>
    flatc(
  File "scripts/generate_code.py", line 82, in flatc
    result = subprocess.run(cmd, cwd=str(cwd), check=True)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/tensorflow_src/build/_deps/flatbuffers-build/flatc'
Scanning dependencies of target absl_raw_hash_set
[ 19%] Built target absl_random_seed_sequences
Scanning dependencies of target absl_flags_config
Scanning dependencies of target absl_cordz_info
make[2]: *** [_deps/flatbuffers-build/CMakeFiles/flatc.dir/build.make:521: _deps/flatbuffers-build/flatc] Error 1
make[2]: *** Deleting file '_deps/flatbuffers-build/flatc'
make[1]: *** [CMakeFiles/Makefile2:4962: _deps/flatbuffers-build/CMakeFiles/flatc.dir/all] Error 2
```
</details>

**Comment by derpda** [comment]
Looking into this further, it might be an upstream problem in Flatbuffers, see [this issue](https://github.com/google/flatbuffers/issues/7297). Bumping the Flatbuffers version might do the trick.

**Comment by derpda** [comment]
Bumping the Flatbuffer version from `v2.0.6` to `v2.0.8` does indeed fix this problem.
https://github.com/tensorflow/tensorflow/blob/2b4e2944aa606f5f4c5f40d05234e187ff86c89a/tensorflow/lite/tools/cmake/modules/flatbuffers.cmake#L21-L31

I can make a small PR bumping this version.

**Comment by mohantym** [comment]
Hi @derpda !
I could replicate this issues with 25b NDK tool chain and Issue is not replicating with [19c tool chain](https://colab.sandbox.google.com/gist/mohantym/d5ec90fa76d982b98dbde031ba1716be/tensorflow-ranking.ipynb#scrollTo=Wj068rw8O61s) (Mentioned as outdated in Android [NDK official documentation ](https://developer.android.com/ndk/downloads) )

Created PR#58902  as per your suggestion to give more flexibility to New NDK tool chain users.
Feel free to give your pointers there.

Thank you

**Comment by mohantym** [comment]
@sachinprasadhs !

Could you look at this issue.
Attached gist with [19c ](https://colab.sandbox.google.com/gist/mohantym/d5ec90fa76d982b98dbde031ba1716be/tensorflow-ranking.ipynb#scrollTo=Wj068rw8O61s)and [25 b ](https://colab.sandbox.google.com/gist/mohantym/72111bf65cbc62627bbd3de3de8db7a8/tensorflow-ranking.ipynb#scrollTo=tlf7PgzQ2JtS ) NDK tool chain for reference.

Thank you!

**Comment by derpda** [comment]
Thanks for opening the PR!
Another issue with newer NDK versions is that the bazel build does not work for them because the NDK directory no longer contains the `platforms` directory post NDK 21. I guess that is a separate issue though. 

On the issue not appearing with NDK 19c, the reason I wasn't using 19c (even though it is the recommended version) is that the build fails with
```
clang: error: the clang compiler does not support '-march=armv8.2-a+bf16'
```
My guess is that the clang version is too old for some intrinsics used in the latest TfLite version. 
You can likely reproduce this by changing the Dockerfile I posted to download NDK 19c instead of 25b.

In the meantime I have had success building TfLite 2.10.3 with NDK 19c, so for now I will stick with that combination.
With other TfLite and NDK version combinations, I had the build succeed but the runtime performance being about 5 times slower than official build (tested with benchmark_model).
Maybe some form of CI could help prevent these build issues.

**Comment by pkgoogle** [comment]
Hi @derpda, we currently do not support Android NDK versions greater than NDK 21. it seems you are able to use the supported versions so I believe this issue is actually completed. If you agree, please feel free to close the issue. Thanks!
