### ISSUE TITLE
Bulid TF2.4 in arm architecture, report  an error（crosstool_wrapper_driver_is_not_gcc failed, NvInferLegacyDims.h: No such file or directory）

### ISSUE THREAD

**Issue by 1chang37** [tensorflow/tensorflow#58883]
1、 Describe the problem 

      bazel build -c opt --config=cuda tensorflow/tools/pip_package:build_pip_package

When I executed the above compilation , I encountered the following error.

ERROR: /workspace/tensorflow/t243/tensorflow/tensorflow/compiler/tf2tensorrt/BUILD:39:11: C++ compilation of rule '//tensorflow/compiler/tf2tensorrt:tensorrt_stub' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/host/bin/tensorflow/compiler/tf2tensorrt/_objs/tensorrt_stub/nvinfer_plugin_stub.pic.d ... (remaining 120 argument(s) skipped)
In file included from bazel-out/host/bin/external/local_config_tensorrt/_virtual_includes/tensorrt_headers/third_party/tensorrt/NvInferPlugin.h:53:0,
                 from tensorflow/compiler/tf2tensorrt/stub/nvinfer_plugin_stub.cc:17:
bazel-out/host/bin/external/local_config_tensorrt/_virtual_includes/tensorrt_headers/third_party/tensorrt/NvInfer.h:53:10: fatal error: NvInferLegacyDims.h: No such file or directory
 #include "NvInferLegacyDims.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /workspace/tensorflow/t243/tensorflow/tensorflow/tools/pip_package/BUILD:69:10 C++ compilation of rule '//tensorflow/compiler/tf2tensorrt:tensorrt_stub' failed (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/host/bin/tensorflow/compiler/tf2tensorrt/_objs/tensorrt_stub/nvinfer_stub.pic.d ... (remaining 120 argument(s) skipped)
INFO: Elapsed time: 933.025s, Critical Path: 447.45s
INFO: 17716 processes: 8772 internal, 8944 local.
FAILED: Build did NOT complete successfully

2、System information

OS:  cetos, aarch64
tensorflow version: 2.4.3/2.4
python version: 3.7
bazel version: 3.7.2
gcc version: 7.3.1
cuda version: 11.4
cudnn:8
tensorrt:8.2

**Comment by mohantym** [comment]
Hi @1chang37 !
2.4 is pretty outdated now.  Please use  TensorRT 7.2.3.4 if you are trying to build for 2.10/2.11 branch.
You can use TensorRT 8.4.3 for Nightly  (2.12dev) along Python 3.9.
[
Ref](https://github.com/tensorflow/tensorflow/issues/57679)

Could you also confirm that you have linked the Cudatoolkits while running configure.py  and installed NVIDIA gpu driver as instructed in this [document.](https://www.tensorflow.org/install/source#gpu_support_3)

Thank you!

**Comment by 1chang37** [comment]
Thanks，but no arm architecture for TensorRT 7.2.3.4 ，so use TensorRT 8.0。2.10/2.11 is too new，Inability to meet expectations。


best

**Comment by mohantym** [comment]
@1chang37 !

Thanks for the clarification.
You can use [CMake](https://www.tensorflow.org/lite/guide/build_cmake_arm) for ARM specific requirement. 

For TF 2.4.4, You can test with TensorRT-7.1.3 , Cuda-10.2, CuDNN-8.0.0 , but you have to say yes to TensorRT when you are running configuring the toolchains through configure.py.

Thank you!
