### ISSUE TITLE
No gradient defined for operation 'Round' (op type: Round)

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#5888]
1. A link to the pip package you installed:
https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-linux-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow_gpu-0.11.0-cp27-cp27mu-linux_x86_64.whl

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.11.head

`tf.round` used to have gradients. but now it gives error.
```python
a = tf.get_variable('a', shape=[1])
x = tf.round(a)
g = tf.gradients(x, a)
```

**Comment by ppwwyyxx** [comment]
Seems to be fixed already.

**Comment by chaseaucoin** [comment]
I'm still having this issue on windows.

**Comment by itsmeolivia** [comment]
are you on the latest version of TF?

**Comment by chaseaucoin** [comment]
I'm on 1.0.0 Build #88 GPU Windows

**Comment by outlace** [comment]
This is still not working. No gradient if you use tf.round @ppwwyyxx

**Comment by ppwwyyxx** [comment]
Works for me.

**Comment by amirmazaheri1990** [comment]
Hi,

How do you check if a function has a gradient or not in TensorFlow?
I have a few lines of code and I'm getting the same error. How can I find the line causing the problem?

Sincerely

**Comment by tolsonMDA** [comment]
This appears to be broken. Is there a workaround? I can reproduce it with the following code in v1.3.0
```
import tensorflow as tf
a = tf.get_variable('a', shape=[1])
x = tf.round(a)
g = tf.gradients(x, a)
print 'gradient =', g
print 'version =', tf.__version__
```
Output:
```
gradient = [None]
version = 1.3.0
```

**Comment by ppwwyyxx** [comment]
@tolsonMDA "None" is exactly what the gradient is supposed to be.

**Comment by tolsonMDA** [comment]
@ppwwyyxx Thanks for taking a look. Can you elaborate? I have the same problem using any of `tf.round`, `tf.floor`, `tf.ceil`, and `tf.cast(a, tf.int32)`, but the gradient is fine when I cast it to a floating type. Why shouldn't it work when casting it to an integer?

**Comment by ppwwyyxx** [comment]
"None" means the gradient is zero. And the gradient is [indeed zero](http://www.wolframalpha.com/input/?i=derivative+round(x)).
Same for others.

**Comment by tolsonMDA** [comment]
Ah, guess I'm being dense today. That makes sense. Thanks!
