### ISSUE TITLE
E tensorflow/tsl/lib/monitoring/collection_registry.cc:81] Cannot register 2 metrics with the same name: /tensorflow/core/bfc_allocator_delay

### ISSUE THREAD

**Issue by pkpro** [tensorflow/tensorflow#58889]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.12.0

### Custom Code

No

### OS Platform and Distribution

ubunto 22.04 LTS

### Python version

Python 3.10.6

### Bazel version

5.3.0

### CUDA/cuDNN version

11.8/8.7.0.84

### GPU model and memory

A4000 16G

### Current Behaviour?

```shell
I expected two following commands to not fail.
I'm not sure that the package I build from source is valid now. It would be great if I could fix this by rebulding the tensorflow ...


sdbot@sdbot:~/ttt$ python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
2022-12-14 17:02:31.842114: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-14 17:02:31.955856: E tensorflow/tsl/lib/monitoring/collection_registry.cc:81] Cannot register 2 metrics with the same name: /tensorflow/core/bfc_allocator_delay
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'GIT_VERSION'
sdbot@sdbot:~/ttt$ python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
2022-12-14 17:02:41.867903: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-14 17:02:41.981995: E tensorflow/tsl/lib/monitoring/collection_registry.cc:81] Cannot register 2 metrics with the same name: /tensorflow/core/bfc_allocator_delay
v1.12.1-86312-g4e76e1e1330 2.12.0
```

### Standalone code to reproduce the issue

```shell
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
```

### Relevant log output

```shell
2022-12-14 17:02:41.981995: E tensorflow/tsl/lib/monitoring/collection_registry.cc:81] Cannot register 2 metrics with the same name: /tensorflow/core/bfc_allocator_delay
v1.12.1-86312-g4e76e1e1330 2.12.0
```
</details>

**Comment by mohantym** [comment]
Hi @pkpro !
Thanks for sharing your observation on Ubuntu22 and TF 2.12 on build from source.
  
Are you suggesting any fix for below issue in  git version.
`v1.12.1-86312-g4e76e1e1330 2.12.0`

[Binary wheels](https://colab.sandbox.google.com/gist/mohantym/a604305f00e019cdac96f5846819086b/git_58889.ipynb) seems to working fine. 
I am trying to replicate this issue as mentioned in this [gist](https://colab.sandbox.google.com/gist/mohantym/6061b777a56aa621cc4ab9d904518d19/tensorflow-ranking.ipynb#scrollTo=DtEuxvobaRf5) . Could you share your build commands to replicate the same.

Thank you!

**Comment by pkpro** [comment]
I just followed the installation instructions. One after another: https://www.tensorflow.org/install/source
I need it to be build with CUDA-11.8 support, that is why I'm installing from sources. 
Therefore there is a little difference with your gist:
`
bazel build --config=cuda //tensorflow/tools/pip_package:build_pip_package

`
And of course the wheel has a different file name: tensorflow-2.12.0-cp310-cp310-linux_x86_64.whl

**Comment by mohantym** [comment]
@pkpro !
Thanks for the update.

@SuryanarayanaY !
Could you look at this issue. 

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @pkpro ,

I tried with Pip and found that the error log was replicated when using [tf.nightly](https://colab.sandbox.google.com/gist/mohantym/a604305f00e019cdac96f5846819086b/git_58889.ipynb#scrollTo=tmEc6T0Pzr--) but no such error log in [2.11V](https://colab.research.google.com/gist/SuryanarayanaY/8884a4468197815f94a2b53622b2184d/58889_2-11_pip.ipynb).But in both versions we can see the desired output anyway which makes me to think whether it is safe to ignore it for now.I have tested nightly version on some other codes and it works fine and i have not observed this error log.May be this log is specific to the code you used. 

Can you please do some tests with the built Wheel and let us know if having any issues there.Meanwhile we will have a look at the error log.

Also I tried to replicate the issue in GCP VM as per Documentation for Build from source. Iam struck at this error during `./configure ` step. 

```
(tf) suryanarayanay@surya-ubuntu-2204--x86-64-tf212v:~/tensorflow$ ./configure
You have bazel 5.3.0 installed.
Please specify the location of python. [Default is /home/suryanarayanay/miniconda3/envs/tf/bin/python3]: 


Found possible Python library paths:
  /home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages
Please input the desired Python library path to use.  Default is [/home/suryanarayanay/miniconda3/envs/tf/lib/python3.9/site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: n
No TensorRT support will be enabled for TensorFlow.

Could not find any cuda.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        '/lib'
        '/lib/x86_64-linux-gnu'
        '/usr'
        '/usr/lib/x86_64-linux-gnu/libfakeroot'

Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 11]: 11.7


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 2]: 8.7


Please specify the locally installed NCCL version you want to use. [Leave empty to use http://github.com/nvidia/nccl]: 


Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: 


Could not find any cuda.h matching version '11.7' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        '/lib'
        '/lib/x86_64-linux-gnu'
        '/usr'
        '/usr/lib/x86_64-linux-gnu/libfakeroot'

Asking for detailed CUDA configuration...
```

But Iam getting the below output for the command `nvidia-smi`
```
(tf) suryanarayanay@surya-ubuntu-2204--x86-64-tf212v:~/tensorflow$ nvidia-smi
Sun Dec 18 08:02:48 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.86.01    Driver Version: 515.86.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P0    61W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM...  Off  | 00000000:00:05.0 Off |                    0 |
| N/A   35C    P0    60W / 400W |      0MiB / 40960MiB |      2%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
(tf) suryanarayanay@surya-ubuntu-2204--x86-64-tf212v:~/tensorflow$ 
```
There seems to be some problem with my environment even though i have CUDA11.7 installed but .`/configure` step not able to find it.
Can you please confirm whether you gone through `./configure` step and if so can you confirm what are the options you choose in this step.Also please provide Exact CUDA driver version you installed and the output of `nvidia-smi `command also.

Thankyou!

**Comment by pkpro** [comment]
Hi @SuryanarayanaY ,

> May be this log is specific to the code you used

Unlikely. This log output is independent of the user specific code and appears with tensorflow import in python.

In order to avoid errors related to CUDA,  you will need to install [CUDA toolkit](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) to avoid the errors you have faced.

I have installed NVIDIA [TensorRT](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html) as well.

The error which I have reported seems to not affect the functionality. It may cause some additional latency on tensorflow import (because of an Exception in C++ code), and it is totally unclear without debugging why is there two registration attempts, - this may prove useful to investigate.

With best regards,
Me.

**Comment by SuryanarayanaY** [comment]
Hi @pkpro ,
Could you tried this code `python -c "import tensorflow as tf; print(tf.__version__,tf.__git_version__)" `instead. It works for me.Please refer to attached photograph of same.
<img width="1512" alt="Screenshot 2022-12-29 at 4 35 35 PM" src="https://user-images.githubusercontent.com/116063290/209942885-5b2bc3be-38f5-4dad-8caa-985230a0bc13.png">
Yeah I can see the Error you mentioned in the log with tf-nightly but with TF 2.11v there is no such error in log as per below image.
<img width="1512" alt="Screenshot 2022-12-29 at 4 33 29 PM" src="https://user-images.githubusercontent.com/116063290/209943196-ccf2207a-9d08-417b-8802-21c64b25eecd.png">

But AFAIK that can be safely ignored as i can see that in TF tutorial also [here](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras).Meanwhile i will put forward this to Developer Team. Also you can use Tf 2.11V safely as there is no such error stack there.

Thank you!

**Comment by pkpro** [comment]
Hello @SuryanarayanaY , 
Can it be that you  do not see the error with Tf 2.11v just because you are missing related NVIDIA libs?
Thank you for spending your time to investigate the issue!
And as I said before, the only affected part is the latency on tf import, the functionality seems to be unaffected.
Regards,
Me.

**Comment by SuryanarayanaY** [comment]
Hi @pkpro ,
Thanks for confirmation. I tried with fresh installations with GPU support. With tf-nightly(2.12) the error you pointed observed but with Tf2.11v there is no such error.Request you to cross check and confirm the same with TF 2.11V. 

<img width="1512" alt="Screenshot 2023-01-02 at 1 37 35 PM" src="https://user-images.githubusercontent.com/116063290/210207403-63457b9f-5936-4b21-898f-b6fce0d224b4.png">
<img width="1512" alt="Screenshot 2023-01-02 at 1 39 24 PM" src="https://user-images.githubusercontent.com/116063290/210207413-ad8e0a6f-b4e8-4fc3-8a28-be80edf616a7.png">


The Error log with Tf2.12V will be put forward to developer team.I can observe latency of 0.1 sec from TF2.12v to 2.11v. Is that what you meant to say ?

Thank you!

**Comment by mshavliuk** [comment]
I'm getting the same error while installing tensorflow on a pristine ubuntu 22.04 virtual machine


### Steps to reproduce
```bash

sudo apt update; sudo apt upgrade -y
sudo apt install nvidia-driver-525
sudo apt autoremove -y
sudo reboot

cd /tmp
curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o Miniconda3-latest-Linux-x86_64.sh
yes | bash Miniconda3-latest-Linux-x86_64.sh
~/miniconda3/condabin/conda config --set auto_activate_base false
source ~/.bashrc

mkdir -p ~/project
cd ~/project
conda create --prefix ./.venv python=3.9
conda activate ./.venv
conda install -c conda-forge -y cudatoolkit=11.8 cudnn=8.4
pip install --upgrade tf-nightly setuptools pip nvidia-pyindex nvidia-tensorrt

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:$CONDA_PREFIX/lib/python3.9/site-packages/tensorrt/

python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
```

### Output

```
2023-01-05 11:36:02.456959: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-05 11:36:02.551546: E tensorflow/tsl/lib/monitoring/collection_registry.cc:81] Cannot register 2 metrics with the same name: /tensorflow/core/bfc_allocator_delay
2023-01-05 11:36:03.320374: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:1041] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-01-05 11:36:03.322852: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:1041] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2023-01-05 11:36:03.322978: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:1041] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

```

**Comment by SuryanarayanaY** [comment]
Hi @pkpro ,

I believe this issue is fixed now. I am not seeing any more such error in logs now.Attaching logs for a recent test below. 

```
(tf) suryanarayanay@surya-ubuntu22-cuda-test:~$ python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
2023-04-25 11:22:58.432868: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-04-25 11:22:59.139258: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-25 11:23:00.846374: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

Please cross check from your side also and let us know if this is still an issue ? Thanks
