### ISSUE TITLE
Systeem

### ISSUE THREAD

**Issue by Frama00** [tensorflow/tensorflow#58899]
https://github.com/tensorflow/docs/blob/master/LICENSE

**Comment by SuryanarayanaY** [comment]
Hi @Frama00 ,

Could you please elaborate more on the issue you want to point out. I presume it might be related to Apache License. AFAIK The Apache License is [permissive](https://en.wikipedia.org/wiki/Permissive_free_software_license); unlike [copyleft](https://en.wikipedia.org/wiki/Copyleft) licenses, it does not require a [derivative work](https://en.wikipedia.org/wiki/Derivative_work) of the software, or modifications to the original, to be distributed using the same license as per the [wikipedia](https://en.wikipedia.org/wiki/Apache_License) source.

Your elaboration of issue will better help us in understanding the concern here.

Thankyou!

**Comment by mihaimaruseac** [comment]
Spam account, spam post
