### ISSUE TITLE
API installation instructions don't work for MacOS

### ISSUE THREAD

**Issue by SJaffa** [tensorflow/tensorflow#58891]
The [C API installation guide](https://www.tensorflow.org/install/lang_c#linker) says

> On Linux/macOS, if you extract the TensorFlow C library to a system directory, such as `/usr/local`, configure the linker with `ldconfig`

but this command doesn't seem to exist on mac. Is there an alternative or can this step be skipped?

**Comment by sushreebarsa** [comment]
@SJaffa Thank you for raising this issue.
In order to expedite the trouble-shooting process here,could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose), it would be more helpful for us to analyze this issue.
Thank you!

**Comment by SJaffa** [comment]
Sure, I'll start a new issue using the template now.

I got here by following [this link](https://github.com/tensorflow/tensorflow/issues/new?template=20-documentation-issue.md) from the [Tensorflow docs repo](https://github.com/tensorflow/docs#tensorflow-documentation) which suggested this was the best way to submit an issue with the documentation. It looks like that is trying to point to a template that might not exist, so you probably need to update your contribution guidelines.

**Comment by SJaffa** [comment]
Submitted a [new issue](https://github.com/tensorflow/tensorflow/issues/58901) but that template doesn't seem very relevant for documentation, most of the questions I didn't fill in.

**Comment by sushreebarsa** [comment]
@SJaffa Could you please close this ticket as we will follow up with the other one?
Thank you!

**Comment by SJaffa** [comment]
I've reached the maximum amount of effort I'm willing to donate to this today so if you want to follow up on this in another issue you'll have to submit it yourself.

> I got here by following [this link](https://github.com/tensorflow/tensorflow/issues/new?template=20-documentation-issue.md) from the [Tensorflow docs repo](https://github.com/tensorflow/docs#tensorflow-documentation) which suggested this was the best way to submit an issue with the documentation. It looks like that is trying to point to a template that might not exist, so you probably need to update your contribution guidelines.
