### ISSUE TITLE
C API installation instructions don't work for MacOS

### ISSUE THREAD

**Issue by SJaffa** [tensorflow/tensorflow#58901]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

No

### Current Behaviour?

```shell
The [C API installation guide](https://www.tensorflow.org/install/lang_c#linker) says

> On Linux/macOS, if you extract the TensorFlow C library to a system directory, such as `/usr/local`, configure the linker with `ldconfig`

but this command doesn't seem to exist on mac. Is there an alternative or can this step be skipped?
```

### Standalone code to reproduce the issue

```shell
Look at docs https://www.tensorflow.org/install/lang_c#linker
```

### Relevant log output

_No response_</details>

**Comment by SuryanarayanaY** [comment]
Hi @SJaffa ,

AFAIK you can ignore this command in MacOS as per [source1](https://github.com/protocolbuffers/protobuf/issues/2570#issuecomment-271358087) here. There is this command earlier for MacOS     
`sudo update_dyld_shared_cache` which is deprecated with latest MacOS versions. 

Can you please skip this command and follow the remaining steps and let us know if facing any problems.

Thankyou!
