### ISSUE TITLE
while tflite model has Dequantize, gpu deledate performance is slower on android for  2.10 version

### ISSUE THREAD

**Issue by mengran1234** [tensorflow/tensorflow#58907]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.7 and 2.10

### Custom Code

Yes

### OS Platform and Distribution

android

### Mobile device

android

### Python version

3.7

### Bazel version

no

### GCC/Compiler version

no

### CUDA/cuDNN version

no

### GPU model and memory

111

### Current Behaviour?

```shell
A bug happened!
Here compare performance between 2.7 version  and 2.10 version
the 2.7 version date is 2021/11/10.
tflite model has dequantize operator （for weight and bias ,input is  f16 ,output is fp32）.
Gpu delegate (opencl)performace on 2.10 is slower than 2.7 ,the diffrence is a little big
my model is 128 ms in 2.7 ,but   78ms in 2.10.
I want to know the reason,thanks
```

### Standalone code to reproduce the issue

```shell
If model has dequantize operator,Gpu delegate performace is slower in new version for example 2.10.
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @mengran1234 !
Thanks for sharing your observation on slow performance with models containing Dequantize nodes.
Would it be possible to provide a sample model to replicate this issue.

Thank you!
