### ISSUE TITLE
Dependencies installation failure in rasa due to Tensor flow

### ISSUE THREAD

**Issue by Harthikahari** [tensorflow/tensorflow#58939]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.3.4

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 18.04.6 LTS Kernel: Linux 5.4.0-1090

### Python version

3.7.5

### Current Behaviour?

```shell
During a fresh install of Tensor flow :

ERROR: Could not find a version that satisfies the requirement tensor flow-text<2.4,>=2.3; sys_platform != "win32" (from rasa) (from versions: none) ERROR: No matching distribution found for tensorflow-text<2.4,>=2.3; sys_platform != "win32"

It does not work even after upgrading the tensor flow to 2.9.0
```

### Standalone code to reproduce the issue

```shell
ERROR: Could not find a version that satisfies the requirement tensor flow-text<2.4,>=2.3; sys_platform != "win32" (from rasa) (from versions: none) ERROR: No matching distribution found for tensorflow-text<2.4,>=2.3; sys_platform != "win32"
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@Harthikahari 
Could you please refer to [Install TensorFlow with pip](https://www.tensorflow.org/install/pip#linux) and [Install TensorFlow Text](https://www.tensorflow.org/text/guide/tf_text_intro#install_tensorflow_text) and let us know if it helps.

Thank you !

**Comment by Harthikahari** [comment]
Hi Tirumalesh ,

I am working with RASA data frame 2.4.3. I have already upgraded TensorFlow
but it my rasa version is not compatible with the new TensorFlow version.
If I upgrade RASA according to the new TensorFlow version it will take a
long time. So can you suggest which TensorFlow version is compatible with
the following rasa version(2.4.3)

Rasa Open Source version 2.4.3

Rasa SDK version 2.8.5

Python version 3.7.5

Python Library: Tensor flow 2.3.4

**Comment by tiruk007** [comment]
@Harthikahari 
The above issue is more related to RASA, we request you post on [RasaHQ/rasa repo](https://github.com/RasaHQ/rasa/issues) for quick assistance and also please refer to [Let’s Talk about TensorFlow ](https://rasa.com/blog/let-s-talk-about-tensorflow-2-6/).
Let us know if it helps.

Thank you!
