### ISSUE TITLE
BatchNormalization is not found under `from tensorflow.python.keras.layers`

### ISSUE THREAD

**Issue by cosmir17** [tensorflow/tensorflow#58947]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

No

### OS Platform and Distribution

Mac Monterey

### Python version

3.8

### Current Behaviour?

```shell
I can't import `BatchNormalization`

The following works though.
`from tensorflow.python.keras.layers import Input, Conv2D, Flatten, MaxPooling2D`
```

### Standalone code to reproduce the issue

```shell
from tensorflow.python.keras.layers import BatchNormalization
```

### Relevant log output

```shell
ImportError: cannot import name 'BatchNormalization' from 'tensorflow.python.keras.layers' (/Users/..../PycharmProjects/....../venv/lib/python3.8/site-packages/tensorflow/python/keras/layers/__init__.py)
```
</details>

**Comment by mohantym** [comment]
Hi @cosmir17 !
I can replicate this issue in my local Mac M1 machine for 2.11 version and seeing [protobuf warning](https://user-images.githubusercontent.com/86464649/208831304-63a6ef86-4918-4c2c-8977-6d0e75388c5b.png) for 2.9 and 2.10 after following  metal-plugin instructions. 

Workaround is to import batch normalization from 'tensoflow.keras.layers' instead of  tensorflow.python.keras.layers(not open sourced all the time )

`from tensorflow.keras.layers import BatchNormalization
`

Thank you!

**Comment by cosmir17** [comment]
thank you, mohantym

FYI, my laptop is intel based.

Let me try it after I get back to home next week Thursday. I am on holiday.

feel free to close this page.

**Comment by mohantym** [comment]
Ok @cosmir17 !

Thanks for the confirmation. Marking this resolved as for now.
Feel free to re-open this issue if you need further assistance in future.

Thank you!

**Comment by cosmir17** [comment]
<img width="754" alt="Screenshot 2022-12-28 at 20 33 05" src="https://user-images.githubusercontent.com/2845708/209868978-9b65ee63-fe3a-4b37-b362-1a2f3183de83.png">

@mohantym The path you suggested is not available as you can see on the screenshot. 
I can't reopen the issue. Please reopen it for me.

**Comment by mohantym** [comment]
@cosmir17 !

Could you route this issue to [Keras](https://github.com/keras-team/keras) repo . 

To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . 

Thank you!

**Comment by cosmir17** [comment]
Other Keras components are already under `tensorflow.python.keras.layers`. 
You mentioned `workaround`. Is there a plan to include `BatchNormalization` in `tensorflow.python.keras.layers`?

Will it be added in future Tensorflow versions? Let's say TF 2.11.1 or 2.11.2?

**Comment by ZioPhil** [comment]
@cosmir17 I'm having the same problem, did you solve it?

**Comment by Rajnishkumar000** [comment]
> <img width="754" alt="Screenshot 2022-12-28 at 20 33 05" src="https://user-images.githubusercontent.com/2845708/209868978-9b65ee63-fe3a-4b37-b362-1a2f3183de83.png">
> 
> @mohantym The path you suggested is not available as you can see on the screenshot. 
> I can't reopen the issue. Please reopen it 


Same problem ,
Have you got solution??
