### ISSUE TITLE
tf.custom_gradient with multiple input and output

### ISSUE THREAD

**Issue by jesgosi** [tensorflow/tensorflow#58941]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**:
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 20.04
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:
-   **TensorFlow installed from (source or binary)**:
-   **TensorFlow version (use command below)**: 2.9.2
-   **Python version**: 3.9
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**:

### Describe the problem
I have a function with 4 inputs (x1, x2, x3, x4) and 2 outputs (y1, y2) using Tensorflow. I would like to specify the gradients, since I perform some non-autodiff operations inside the function.

I need to specify the derivatives of the outputs with respect to the inputs. We can see these derivatives as a Jacobian of size (2,4). Regarding this, I have 8 derivatives: dy1_dx1, dy1_dx2, dy1_dx3, dy1_dx4, dy2_dx1, dy2_dx2, dy2_dx3 and dy2_dx4.

However, the grad function used in this tf.custom.gradient needs to have the same length as the inputs, this is 4. So, I do not know how Tensorflow handles with the introduction of the 8 derivatives using just 4 elements. I tried to include them as lists, but it gives the error. Here is a general code to reproduce the error:

```
import tensorflow as tf
@tf.custom_gradient
def bar(x1, x2, x3, x4):
  def grad(dy1, dy2):
    dy1_dx1 = x2**2 * x3**3 * x4**4             #360000
    dy1_dx2 = x1 * 2*x2 * x3**3 * x4**4         #480000
    dy1_dx3 = x1 * x2**2 * 3*x3**2 * x4**4      #540000
    dy1_dx4 = x1 * x2**2 * x3**3 * 4*x4**3      #576000
    dy2_dx1 = x2**2 + x3**3 + x4**4             #698
    dy2_dx2 = x1 + 2*x2 + x3**3 + x4**4         #697
    dy2_dx3 = x1 + x2**2 + 3*x3**2 + x4**4      #684
    dy2_dx4 = x1 + x2**2 + x3**3 + 4*x4**3      #575
    return [dy1_dx1, dy2_dx1], [dy1_dx2, dy2_dx2], [dy1_dx3, dy2_dx3], [dy1_dx4, dy2_dx4]

  y1 = x1 * x2**2 * x3**3 * x4**4
  y2 = x1 + x2**2 + x3**3 + x4**4
  return [y1, y2], grad

x1 = tf.constant(2.0, dtype=tf.float32)
x2 = tf.constant(3.0, dtype=tf.float32)
x3 = tf.constant(4.0, dtype=tf.float32)
x4 = tf.constant(5.0, dtype=tf.float32)
with tf.GradientTape(persistent=True) as tape:
  tape.watch(x1)
  tape.watch(x2)
  tape.watch(x3)
  tape.watch(x4)
  z = bar(x1, x2, x3, x4)

print(tape.gradient(z, x1))             #[dy1_dx1, dy2_dx1]
print(tape.gradient(z, x2))             #[dy1_dx2, dy2_dx2]
print(tape.gradient(z, x3))             #[dy1_dx3, dy2_dx3]
print(tape.gradient(z, x4))             #[dy1_dx4, dy2_dx4]

```

The  error says: "custom_gradient function expected to return 4 gradients, but returned 8 instead".

I expect someway to specify the correspondent 8 derivatives. Thank you in advance!

**Comment by tilakrayal** [comment]
@jesgosi,
I was facing a different issue while executing the mentioned code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/f25494a2af1183a890df75148a7b1553/untitled807.ipynb) and provide the dependencies to debug the issue.

**Comment by tilakrayal** [comment]
Also When we are using the function that takes multiple variables as input, the grad function must also return the same number of variables. Please take a look at this official doc link of **tf.custom_gradient** for the [reference](https://www.tensorflow.org/api_docs/python/tf/custom_gradient). Thank you!

**Comment by tilakrayal** [comment]
@jesgosi,
This type of questions are better asked on [TensorFlow Forum](https://discuss.tensorflow.org/) since it is not a bug or feature request. There is also a larger community that reads and responds to the questions there. Thank you!
