### ISSUE TITLE
unable to save function, WeightNormalization with Conv1DTranspose error

### ISSUE THREAD

**Issue by binbinxue** [tensorflow/tensorflow#58945]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.9.12

### CUDA/cuDNN version

nvidia-cudnn-cu11==8.6.0.163

### GPU model and memory

RTX 3080TI 

### Current Behaviour?

```shell
From the official tutorial on melGAN here: https://keras.io/examples/audio/melgan_spectrogram_inversion/
The problem occurs with addon_layers.WeightNormalization wrapped around Conv1DTranspose layer. The normalization works on other layers such as Conv1D but not the Conv1DTranspose layer. The model trains fine but error arises when saving the model with error message:
ValueError: Unable to save function b'__inference_conv1d_transpose_3_layer_call_and_return_conditional_losses_101006' because it captures graph tensor Tensor("weight_normalization_21/compute_weights/mul:0", shape=(16, 32, 64), dtype=float32) from a parent function which cannot be converted to a constant with `tf.get_static_value`


class ConvBlock(layers.Layer):
    def __init__(self, conv_dim, upsampling_factor):
        super().__init__()
        self.conv_t = addon_layers.WeightNormalization(Conv1DTranspose(conv_dim, 16, upsampling_factor, padding="same"), data_init=False)
        #self.conv_t = Conv1DTranspose(conv_dim, 16, upsampling_factor, padding="same")
        self.res_block = ResidualBlock(conv_dim)

    def call(self, X, training=False):
        t1 = self.conv_t(X, training=training)
        c1 = tf.nn.leaky_relu(t1, 0.3)
        out = self.res_block(c1, training=training) #I've put the leakly_relu activation into res_block
        return out
```
```


### Standalone code to reproduce the issue

```shell
https://keras.io/examples/audio/melgan_spectrogram_inversion/
```

### Relevant log output

```shell
ValueError: Unable to save function b'__inference_conv1d_transpose_3_layer_call_and_return_conditional_losses_101006' because it captures graph tensor Tensor("weight_normalization_21/compute_weights/mul:0", shape=(16, 32, 64), dtype=float32) from a parent function which cannot be converted to a constant with `tf.get_static_value`
```
</details>

**Comment by tilakrayal** [comment]
@binbinxue,
1. The error might be raised because you have declared python lists inside the layers, and those python lists are inaccessible to the **tf computation graph**

2. Is it because you want to export the model for inference?

As a workaround you may want to try to use `tf.saved_model.save(model, name`) and see if that works. Also please try to use **enable_eager_execution()** before executing the code. Thank you!

**Comment by binbinxue** [comment]
> 

@tilakrayal thanks for the quick reply, i have tried using tf.saved_model.save or saving in h5 format, none worked, in response to the two points
1. i have tried using the functional model (official demo code) and the subclassed model. Both give the same error with the conv1dTranspose. If i remove the weightNormalization wrapper around it then it saves fine
2. yes, that was the intend, the model trains fine but gives the value error when saving. 
Any more suggestions please? I tried enable_eager_execution() and nothing changed.

**Comment by binbinxue** [comment]
see the minimum code with WeightNormalization wrapper below:


`
from tensorflow import keras
from tensorflow_addons import layers as addon_layers

model = keras.Sequential([
    addon_layers.WeightNormalization(Conv1DTranspose(32, 16, 2, padding='same'))
])
model.build(input_shape=(None, None, 32))
tf.saved_model.save(model,'./2/')
`
The error message below:
**ValueError: Unable to save function b'__inference_conv1d_transpose_layer_call_and_return_conditional_losses_1421' because it captures graph tensor Tensor("compute_weights/mul:0", shape=(16, 32, 32), dtype=float32) from a parent function which cannot be converted to a constant with `tf.get_static_value`.**

**Comment by tilakrayal** [comment]
@binbinxue,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by binbinxue** [comment]
thanks, i've raised the issue in keras repo here:
https://github.com/keras-team/keras/issues/17370
