### ISSUE TITLE
GPUs only visible for administrators

### ISSUE THREAD

**Issue by ghup1** [tensorflow/tensorflow#58957]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.10

### Custom Code

No

### OS Platform and Distribution

Windows Server 2022

### Python version

3.9

### CUDA/cuDNN version

11.2.2/8.1.1

### GPU model and memory

NVIDIA RTX A5000

### Current Behaviour?

```shell
When executing tf.config.list_physical_devices(), tensorflow returns a list with all installed GPUs only when executed by an admin. Standard user accounts see only CPU devices.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
print(tf.config.list_physical_devices())
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@ghup1,
I donot see any issue/error while executing the mentioned code to check if the GPU's are available or not. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/d663a2ac8104af1f3bdde0fa689ba5e6/untitled812.ipynb) and also please take a look at this official doc link for the [reference](https://www.tensorflow.org/guide/gpu).

**Comment by ghup1** [comment]
The faulty behaviour was due to a corrupt Windows user profile. After recreating this user profile, the issue was solved.
