### ISSUE TITLE
[NVIDIA XLA] XLA generates element-wise fusion kernel with no data locality for GPU

### ISSUE THREAD

**Issue by shawnwang18** [tensorflow/tensorflow#58950]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf r2.11

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 16.4

### Python version

3.8

### Bazel version

5.3.0

### GCC/Compiler version

gcc

### Current Behaviour?

I encountered a case where XLA creates very bad layout for pointwise fused kernel,  the fused kernel are using layout {1,0,2,3},  which leads to almost no data locality across CUDA block threads, and these kernels takes really long time (45% of  training step for Stable Diffusion unit test).  

Can you confirm that this is a layout assignment issue (bug) of XLA?   

Attaching the HLO dumps of before/after optimization. please check fusion fused_computation.1116   the fused graph for fused_computation.1116 is also attached.

Attached files: 
https://drive.google.com/drive/folders/1BRA4BExE_v0xIOm5v-nRf_Xkb6gDoqhH?usp=sharing

### Standalone code to reproduce the issue

In the google drive I shared, there is a unittest to produce the issue. to run it, download the folder `unittest`, and from inside the folder, run `bash r.sh` 

### Relevant log output

_No response_</details>

**Comment by shawnwang18** [comment]
Just noticed that there is a comment that the issue might gone for the latest XLA, let me verify it.

**Comment by shawnwang18** [comment]
Confirmed that with latest XLA, the layout issue still exist

**Comment by tilakrayal** [comment]
@shawnwang18,
I can see that you are using Bazel v3.30 for the tensorflow v2.11 which was not compatible. Could you please try to install with Bazel 5.3.0 and let us know if you are facing a similar issue. Thank you!

**Comment by shawnwang18** [comment]
@tilakrayal   Sorry, this is a typo, I was building using bazel 5.3.0.

**Comment by tilakrayal** [comment]
@shawnwang18,
Could you please provide the complete error stack trace which helps us to debug and analyse the issue. Thank you!

**Comment by shawnwang18** [comment]
@tilakray There is no error stack for this issue, it is a perf problem.   Ｉ think the easiest way for you to analysis is to run the unitest I've shared in the google drive.   We have used NVidia's nsight-compute profiler tool to analysis an issue kernel ` fusion_1116` ,  the cache and global memory access traffic are like below， which obvious shows no data locality. 

![image](https://user-images.githubusercontent.com/35983922/209490876-fad781cd-9ed5-4d8f-ba61-48a23b5859d7.png)


If you try compare the same fusion (`fused_compuation.1116`) but with all inputs and outputs in the row major layout, we can see that we can increase the kernel's perf by around 9X. 

<html>
<body>
<br class="Apple-interchange-newline">

with current layout setting | if inputs/output all use layout [3,2,1,0] | Speedup of using layout [3,2,1,0] |  
-- | -- | -- | --
21.63ms | 2.43ms | 8.9X |  

<br class="Apple-interchange-newline">
</body>
</html>
