### ISSUE TITLE
Cannot import tensorflow using simple Pip installation instructions

### ISSUE THREAD

**Issue by mgavaudan** [tensorflow/tensorflow#5895]
This is the error im getting. I saw the other posts for conda and windows computers, but I have a mac and im not using conda...

$ python
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
dyld: warning, LC_RPATH $ORIGIN/../../_solib_darwin/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Slib in /Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH ../local_config_cuda/cuda/lib in /Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH ../local_config_cuda/cuda/extras/CUPTI/lib in /Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so being ignored in restricted program because it is a relative path
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Library/Python/2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Library/Python/2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 21, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Library/Python/2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _pywrap_tensorflow
>>> exit()

**Comment by martinwicke** [comment]
How did you install tensorflow? 

If you used pip on a Mac, you very likely want to install tensorflow into a virtualenv. MacOS is very protective of its system directories, so pip doesn't always work properly even if used as root.

**Comment by mgavaudan** [comment]
Yes, I only used pip on a Mac. Should I uninstall anything before trying installing tensorflow with virtualenv then? Also it seems weird they would have that instruction set for pip on mac if it didnt work...

**Comment by martinwicke** [comment]
It is at least somewhat confusing, since usually the failure more is that tensorflow doesn't install properly due to permission problems. 

You don't have to uninstall anything, just make a virtualenv and install tensorflow in there.

**Comment by rieram** [comment]
Hi, try to import _pywrap_tensorflow.so in  [PYTHON_INSTALL_DIR]/site-packages/tensorflow/python/_pywrap_tensorflow.so this most of the time provides more specific on why it is not loading. Most of the time this happens is because its not able to link to a dynamic library somewhere in your environment, or a minor version changed from a dynamic lib. After that you can take it from there.
