### ISSUE TITLE
 /home/work/tensorflow/test/tensorflow-2.4.0/tensorflow/compiler/xla/service/cpu/BUILD:695:1: C++ compilation of rule '//tensorflow/compiler/xla/service/cpu:runtime_matmul' failed (Exit 4)

### ISSUE THREAD

**Issue by suzaolin** [tensorflow/tensorflow#58956]
use bazel build --jobs 1 --local_ram_resources=HOST_RAM*0.9 --local_cpu_resources=HOST_CPUS*1  --config=opt //tensorflow:libtensorflow_cc.so

my tensorflow is 2.4.0

ERROR: /home/work/tensorflow/test/tensorflow-2.4.0/tensorflow/compiler/xla/service/cpu/BUILD:695:1: C++ compilation of rule '//tensorflow/compiler/xla/service/cpu:runtime_matmul' failed (Exit 4)
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
Target //tensorflow:libtensorflow_cc.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 32.611s, Critical Path: 21.70s
INFO: 39 processes: 39 local.
FAILED: Build did NOT complete successfully

**Comment by mohantym** [comment]
Hi @suzaolin !
2.4 is bit outdated. 
Could you check with below command , Master branch and Bazel 5.3.0  and let us know.

`!bazel build --jobs 1 --local_ram_resources=HOST_RAM*.9 --local_cpu_resources=HOST_CPUS -c opt //tensorflow:libtensorflow_cc.so`

Attached [gist](https://colab.sandbox.google.com/gist/mohantym/d7479993bd95a7ad4f2bb028ca5d8d0d/tensorflow-ranking.ipynb#scrollTo=DtEuxvobaRf5) for reference. 

Thank you!

**Comment by suzaolin** [comment]
I seem to have found the reason, my machine is out of memory @mohantym Thank you very much

**Comment by mohantym** [comment]
@suzaolin !
Could you confirm that it is resolved in 2.10/2.11 version. 
Thank you!
