### ISSUE TITLE
Validate on entire validation_data if Dataset has length less than validation_steps

### ISSUE THREAD

**Issue by mbarnes13** [tensorflow/tensorflow#58966]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

2.12.0

### Custom Code

No

### Current Behaviour?

```shell
We provide a `tf.data.Dataset` and `validation_steps` to `Model.fit`. The size of our Dataset varies may vary across experiments. If `validation_steps <= len(Dataset)`, then everything works as expected. However, if `validation_steps > len(Dataset)`, validation is only performed _once_ (at the first epoch). In this case, I'd expect that validation is simply performed across the entire dataset every epoch.

A hacky solution around this problem is to use `.repeat()`, but that is a poor solution since it will perform duplicate (unnecessary) evaluations on the same samples.
```

### Standalone code to reproduce the issue

```shell
Simply call `Model.fit` with `validation_steps > len(Dataset)`
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@mbarnes13 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. It will help us to analyze the issue. Thank you!

**Comment by mbarnes13** [comment]
@sushreebarsa The main use case is to validate on `max(max_samples, size(validation_dataset))`. This is useful in settings where the validation dataset varies across runs, and we want to limit validation on excessively large datasets.

**Comment by sachinprasadhs** [comment]
When `validation_steps' > len(Dataset)` as per the existing implementation where it runs validation for first epoch is proper. Otherwise, it would increase the evaluation time when the validation is performed on each epoch for the above scenario.

**Comment by mbarnes13** [comment]
Hi Sachin. The first epoch is correct. The issue is that on subsequent epochs:
If `validation_steps <= len(dataset)`: Restarts validation at beginning of dataset.
If `validation_steps > len(dataset)`: Performs no validation. This is the unexpected behavior. It should restart at the beginning of the dataset.

**Comment by rchao** [comment]
Hello @mbarnes13, yes I was able to repro this - would you be willing to take a look at the issue and contribute a fix? I think it's fair that we continue to have validation in later epochs even if it runs out in the first epoch. We would appreciate a contribution.

**Comment by mbarnes13** [comment]
Hi @rchao. Unfortunately I don't have the cycles to contribute a fix right now. FYI, I'm also FTE at Google. Mostly using this to track the issue.

**Comment by rchao** [comment]
Thanks @mbarnes13! In that case let's keep this issue open for contributions.

**Comment by Aryan-Mishra24** [comment]
Great to see this issue being discussed! I would like to contribute to this project and work on fixing this issue. Please let me know how I can get started and what tasks I can take up. Looking forward to contributing to the project!

**Comment by rchao** [comment]
Thanks @Aryan-Mishra24! I would start with reproducing it and look into the code to find why the validation is only done in the first epoch, and make changes in the code to fix that, with a unit test added.

**Comment by madt2709** [comment]
Hey, I would like to pick this up! However, shout if you're already working on it Aryan (its been over a month so I assume not)

**Comment by madt2709** [comment]
When reproducing this, you see a warning on the first iteration but not on the second.
``` bash
Epoch 1/2
1865/1875 [============================>.] - ETA: 0s - loss: 0.0771 - accuracy: 0.9757WARNING:tensorflow:Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 60001 batches). You may need to use the repeat() function when building your dataset.
1875/1875 [==============================] - 29s 15ms/step - loss: 0.0772 - accuracy: 0.9756 - val_loss: 0.0820 - val_accuracy: 0.9753
Epoch 2/2
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0679 - accuracy: 0.9783
<keras.callbacks.History at 0x7f2a405fd400>
```

Searching for the warning, we see it is raised in 3 different places ([link](https://github.com/tensorflow/tensorflow/search?q=Your+input+ran+out+of+data%3B+interrupting+training.+Make+sure+that+your+dataset+or+generator+can+generate+at+least+%60steps_per_epoch+*+epochs%60+batches))

Next steps: 
- Figure out which warning is raised the first epoch. 
- Work out why the warning is not surfacing in the second epoch
- add extra validation

**Comment by mayureshagashe2105** [comment]
@rchao @sushreebarsa I would like to contribute a fix. `steps_per_epoch` is being inferred by [`DataHandler.infer_steps`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/data_adapter.py#LL1311C5-L1311C5) method. If a user provides a value to the arg `steps_per_epoch`/`validation_steps` it is simply returned by the current method implementation. 
If step_size > `len(dataset)` then this line [`next(iterator)`](https://github.com/tensorflow/tensorflow/blob/720f89ab4606b2be8bd3659a229c23cb2c0cb2ad/tensorflow/python/keras/engine/training.py#L1318)  will throw `StopIteration` error which is causing `DataHandler._insufficient_data` to set to `True` and the training/validation stops.

To solve this, clipping the inferred step value from [`DataHandler.infer_steps`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/data_adapter.py#LL1311C5-L1311C5) to maximum step size possible if it exceeds, is needed. Is the fix in-line with the intended functioning of the engine?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
