### ISSUE TITLE
Support for indexing a container of `Layer`s using index from `Dataset` element inside a `tf.function` or `Layer.call`

### ISSUE THREAD

**Issue by sidward14** [tensorflow/tensorflow#58965]
### Issue Type

Feature Request

### Source

source

### Tensorflow Version

tf 2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8.0

### CUDA/cuDNN version

11.2

### Current Behaviour?

I think One-Hot based indexing / control flow inside a tf.function is a common idea in deep learning. It would be great if the TF team made this easier / doable to implement for efficient computation.

https://stackoverflow.com/questions/74856566/how-to-index-a-list-of-tf-keras-layers-layer-with-a-tensorflow-tensor-inside-a-t?noredirect=1#comment132112356_74856566 

I have a list of `tf.keras.layers.Layer` that I want to index inside a `tf.function` based off of an `index_tensor` (that comes from iterating over a `tf.data.Dataset`). Ideally like this:

```python
import tensorflow as tf
from tensorflow.keras import layers
from typing import List

@tf.function
def compute_single_output(heads: List[layers.Layer], index_tensor: tf.Tensor, input: tf.Tensor):
    logit = heads[index_tensor](input)
    return logit
```

But I get this:

```shell
    TypeError: list indices must be integers or slices, not Tensor
```

Is there any way to set this up so that I can do it? If not, this feature would be very helpful.

### What I've tried:
`tf.gather` won't work for a list of Layers. `tf.lookup` table wouldn't work either. I was able to make `tf.switch_case` work, but it then forces re-trace compile on every iteration of the training loop. I tried using a dict of heads instead of a list, also didn't work.

Only thing that works is to iterate over the list in a Python for loop, but this accumulates CPU RAM per iteration over the loop (because autograph can't convert `heads` into a tensor, it can't use `tf.while_loop`, see https://www.tensorflow.org/guide/function#loops for more info). It's also O(n):

```python
@tf.function
def compute_single_output(heads: List[layers.Layer], index_tensor: tf.Tensor, input: tf.Tensor):
    logit = tf.constant(-1, dtype=tf.float32)
    m = tf.constant(0)
    for head in heads:
        if m == index_tensor:
            logit = head(input)
        else:
            pass
        m += 1
    return logit
```

I expect to be running this function for a long time, so I can't afford to accumulate memory over time.

### Standalone code to reproduce the issue

```python
import tensorflow as tf
from tensorflow.keras import layers
from typing import List

@tf.function
def compute_single_output(heads: List[layers.Layer], index_tensor: tf.Tensor, input: tf.Tensor):
    logit = heads[index_tensor](input)
    return logit

heads = [layers.Dense(3), layers.Dense(4)]
index_tensor = tf.constant(0, dtype=tf.int32)
input = tf.random.uniform((8, 6), dtype=tf.float32)

output = compute_single_output(heads, index_tensor, input)
```

## Some Ideas
How hard is it to implement a "LayerList" or "ModuleList" into TF (that can be indexed with a `Tensor`)? Here's one in pytorch: https://pytorch.org/docs/stable/generated/torch.nn.ModuleList.html 

Or have the Functional API allow for one-hot based control flow

I can try writing a custom op to map `index_tensor` -> `heads[index_tensor]` myself (I know C++), though I've never done that before

**Comment by sushreebarsa** [comment]
@sidward14 I wasn't able to replicate this issue, could you find the gist [here](https://colab.research.google.com/gist/sushreebarsa/71ef75b3f6f2f9b5fd22ff41fc4b8c86/untitled744.ipynb) and let me know if I am missing something?
Thank you!

**Comment by sidward14** [comment]
Yes, I updated the gist: [Link](https://colab.research.google.com/gist/sidward14/a1eaf7be859b01db26a1fd1e1a770835/untitled744.ipynb)

You need to run the function with appropriate inputs

I'll also update the minimum working example to include this
