### ISSUE TITLE
Almost wiped my PC trying to make Tensorboard work on windows Jupyter notebook

### ISSUE THREAD

**Issue by elijah123815** [tensorflow/tensorflow#58969]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

Yes

### Current Behaviour?

```shell
I executed the following code:

logdir = pathlib.Path()
shutil.rmtree(logdir, ignore_errors=True)

I was trying to fix my tensorboard issues and ended up almost wiping my entire PC clean. Is there a way of getting my files back? It seems like there is nothing in the recycle bin. Please help?
```

### Standalone code to reproduce the issue

```shell
Lost over 100GB of files
```

### Relevant log output

```shell
n/a
```
</details>

**Comment by SuryanarayanaY** [comment]
Hi @elijah123815 ,

`shutil.rmtree(logdir, ignore_errors=True)` removes all the directories and sub directories in `logdir` path/directory/File Hence we should be careful in selecting the `logdir` path.

Though I am not sure how this is related to tensorflow.Whether you have find any such instructions in Tensorflow tutorial ? If so please let us know. 

Iam not sure about how to recover those deleted files.You may try your luck referring to below links [link1](https://www.reddit.com/r/learnpython/comments/gxxfho/shutilrmtree_is_recovery_possible/) & [link2](https://stackoverflow.com/questions/62975658/did-i-delete-some-important-files-using-os-and-shutil).

Thank you!
