### ISSUE TITLE
VocabularyProcessor does not work with Chinese

### ISSUE THREAD

**Issue by Samurais** [tensorflow/tensorflow#5896]
In order to train a model with tensorflow, try to use tf.contrib.learn.preprocessing.VocabularyProcessor to get a vocabulary vector. 

```
def create_vocab(input_iter, min_frequency):
  """
  Creates and returns a VocabularyProcessor object with the vocabulary
  for the input iterator.
  """
  vocab_processor = tf.contrib.learn.preprocessing.VocabularyProcessor(
      FLAGS.max_sentence_len,
      min_frequency=min_frequency,
      tokenizer_fn=tokenizer_fn)
  vocab_processor.fit(input_iter)
  return vocab_processor

```

It works well with English. But all the Chinese words are not parsed. They are treated as a single word.

![image](https://cloud.githubusercontent.com/assets/3538629/20660678/cc49a12a-b585-11e6-9018-8f8dc0d628b3.png)

### Environment info
Operating System: Mac OSX, CPU Only
TensorFlow: Version - **0.11.0rc1**

### What other attempted solutions have you tried?
Not yet.

**Comment by Samurais** [comment]
Get a work around http://acepor.github.io/2015/12/17/General-Pipelines/
```
bash -x segment.sh ctb test.csv UTF-8 0 > test.segmenter.csv
```

Then, Chinese words are split with space.

**Comment by poxvoculi** [comment]
Maybe this might help too:

https://github.com/tensorflow/models/blob/master/syntaxnet/syntaxnet/models/parsey_universal/tokenize_zh.sh

**Comment by Samurais** [comment]
@poxvoculi Thanks, I have found several solution to process Chinese, there are a lot tools.
http://eng.snaplingo.net/use-stanford-word-segmenter-to-process-chinese-data/
