### ISSUE TITLE
cannot deepcopy Optimizer class anymore in tf>=2.11

### ISSUE THREAD

**Issue by jschueller** [tensorflow/tensorflow#58973]
### Issue Type

Bug

### Current Behaviour?

from the 2.11 version, we cannot serialize optimizers (the keras.optimizers.optimizer_experimental.optimizer.Optimizer hierarchy) anymore 
due to its _distribution_strategy attribute of singleton type _DefaultDistributionStrategy

### Standalone code to reproduce the issue

this was fine in 2.10.x:

```shell

import tensorflow as tf
from copy import deepcopy

optimizer = tf.keras.optimizers.Adam()
deepcopy(optimizer)
```

with 2.11.0 we have this error:
```
RuntimeError: Should only create a single instance of _DefaultDistributionStrategy
```

### Source

binary

### Tensorflow Version

2.11.0

### OS Platform and Distribution

archlinux/python3.10

<details><summary>Click to expand!</summary> 
 

### Relevant log output

```shell
In [4]: deepcopy(optimizer)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[4], line 1
----> 1 deepcopy(optimizer)

File /usr/lib/python3.10/copy.py:172, in deepcopy(x, memo, _nil)
    170                 y = x
    171             else:
--> 172                 y = _reconstruct(x, memo, *rv)
    174 # If is its own copy, don't memoize.
    175 if y is not x:

File /usr/lib/python3.10/copy.py:271, in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    269 if state is not None:
    270     if deep:
--> 271         state = deepcopy(state, memo)
    272     if hasattr(y, '__setstate__'):
    273         y.__setstate__(state)

File /usr/lib/python3.10/copy.py:146, in deepcopy(x, memo, _nil)
    144 copier = _deepcopy_dispatch.get(cls)
    145 if copier is not None:
--> 146     y = copier(x, memo)
    147 else:
    148     if issubclass(cls, type):

File /usr/lib/python3.10/copy.py:231, in _deepcopy_dict(x, memo, deepcopy)
    229 memo[id(x)] = y
    230 for key, value in x.items():
--> 231     y[deepcopy(key, memo)] = deepcopy(value, memo)
    232 return y

File /usr/lib/python3.10/copy.py:153, in deepcopy(x, memo, _nil)
    151 copier = getattr(x, "__deepcopy__", None)
    152 if copier is not None:
--> 153     y = copier(memo)
    154 else:
    155     reductor = dispatch_table.get(cls)

File /usr/lib/python3.10/site-packages/tensorflow/python/distribute/distribute_lib.py:3598, in _DefaultDistributionStrategy.__deepcopy__(***failed resolving arguments***)
   3596 def __deepcopy__(self, memo):
   3597   del memo
-> 3598   raise RuntimeError("Should only create a single instance of "
   3599                      "_DefaultDistributionStrategy")

RuntimeError: Should only create a single instance of _DefaultDistributionStrategy
```
</details>

**Comment by mohantym** [comment]
Hi @jschueller !
Thanks for sharing your observation with respect to optimizer and Deepcopy.
I could replicate this issue in 2.11 and nightly(2.12 dev) (not replicating in 2.9 and 2.10).

@SuryanarayanaY  !
Could you look at this issue , Attached gist in [2.9](https://colab.sandbox.google.com/gist/mohantym/a20e7b3c8859d68909df1266932d2f74/git_58973_2-9.ipynb), [2.10](https://colab.sandbox.google.com/gist/mohantym/f35f26e9b9801ad9542e3fe6c5ddff1c/git_58973_2-9.ipynb#scrollTo=6KlMIwGndF-E), [2.11 ](https://colab.sandbox.google.com/gist/mohantym/e272bbea90e5c1fe91275e52d61f1877/git_58973_2-9.ipynb#scrollTo=6KlMIwGndF-E)and [2.12](https://colab.sandbox.google.com/gist/mohantym/d80417a0bb4efba193f63b77f1e40361/git_58973_2-9.ipynb#scrollTo=lCOV2ibmbME3) dev for reference. 

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @jschueller ,

Thanks for writing us. Yeah I can see the behaviour you mentioned.Could you please provide more context on how it affects Serialization of Optimizer ? 
I tried a simple `model.fit` and same model saved and loaded again and then trained using `reconstructed_model.fit` and done training again and i could not find any error w.r.t TF2.10 and 2.12(nightly) versions.Please refer to gists [2.10](https://colab.sandbox.google.com/gist/SuryanarayanaY/47ef1e5c038b3a664080bb804b33cd93/58973_2-10.ipynb) and [2.12(nightly)](https://colab.sandbox.google.com/gist/SuryanarayanaY/bab9b32f935c499761a56b275545c395/58973_2-12.ipynb). 

Thank you!

**Comment by jschueller** [comment]
the save/load_model is a nice workaround indeed, but it doesnt apply easily in my case

we use deepcopy in a package called tensap to try incremental changes to our model:
https://github.com/anthony-nouy/tensap/search?q=deepcopy
and the recursive deepcopy of our objects ends up deepcopying a tensorflow Optimizer

**Comment by sachinprasadhs** [comment]
Hi, Could you please try if it is working with the legacy optimizer here https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/legacy/Optimizer and let us know if you still face an error. Thanks!

**Comment by jschueller** [comment]
yes, it works with tf.keras.optimizers.legacy.Adam()

**Comment by sachinprasadhs** [comment]
Thanks for confirming, since the `keras.optimizers` is implemented with new changes and does not have backward compatibility in most of the cases. 
If you want old behavior you can always switch to `tf.keras.optimizers.legacy`.
If your issue is resolved, could you please close this issue. Thanks!

**Comment by jschueller** [comment]
The legacy algorithms will be deprecated at some point right ?
Then I'll have no choice to use the new one and be stuck as well, so what do I do ?

**Comment by sachinprasadhs** [comment]
The previous optimizer code has been moved under `optimizers.legacy` to make use of old behavior, we don't have any plans to deprecate this but the implementations and code fixes will take place in new optimizer.

**Comment by sachinprasadhs** [comment]
Hi @chenmoneygithub, Can we make new optimizer to support deepcopy. Thanks!

**Comment by chenmoneygithub** [comment]
`deepcopy` is not supported due to the restriction on distribution strategy. you can actually bypass the issue by nullifying the `self._distribution_strategy`, i.e.,
```
strategy = old_optimizer._distribution_strategy
old_optimizer._distribution_strategy = None
new_optimizer = deepcopy(old_optimizer)
new_optimizer._distribution_strategy = strategy
```

Also we will not deprecate the old optimizer, but not adding new features to it.

**Comment by uri-granta** [comment]
Possibly a stupid question, but is there a reason why `_DefaultDistributionStrategy` doesn't just return itself (the singleton instance) when deep-copied?

**Comment by sachinprasadhs** [comment]
@jschueller , Since the relevant PR is merged here https://github.com/keras-team/keras/pull/17463, Could you please close this issue. Thanks!
