### ISSUE TITLE
XLA Collapse Documentation: Example Incorrect

### ISSUE THREAD

**Issue by chrisby** [tensorflow/tensorflow#58971]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### Current Behaviour?

```shell
It seems like the XLA documentation for the Collapse operator is wrong. Given a tensor with dimensions `[4,2,3]`, collapsing over dimensions `[0,1]`, should result (as described in the text) in a tensor of dims `[8,3]`. In the example, however, you show the result to be a `[4,6]` tensor.
```

### Standalone code to reproduce the issue

```shell
n/a
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@chrisby,
Could you please feel free to submit a PR for the requested change or share the link where the requested change is to be made. Thank you!

**Comment by ADITYADAS1999** [comment]
> Click to expand!
> ### Issue Type
> Documentation Bug
> 
> ### Source
> source
> 
> ### Tensorflow Version
> 2.9.1
> 
> ### Custom Code
> No
> 
> ### OS Platform and Distribution
> _No response_
> 
> ### Mobile device
> _No response_
> 
> ### Python version
> _No response_
> 
> ### Bazel version
> _No response_
> 
> ### GCC/Compiler version
> _No response_
> 
> ### CUDA/cuDNN version
> _No response_
> 
> ### GPU model and memory
> _No response_
> 
> ### Current Behaviour?
> ```shell
> It seems like the XLA documentation for the Collapse operator is wrong. Given a tensor with dimensions `[4,2,3]`, collapsing over dimensions `[0,1]`, should result (as described in the text) in a tensor of dims `[8,3]`. In the example, however, you show the result to be a `[4,6]` tensor.
> ```
> 
> ### Standalone code to reproduce the issue
> ```shell
> n/a
> ```
> 
> ### Relevant log output
> _No response_

hey [chrisby](https://github.com/chrisby) , Can you share the documentation link here.

**Comment by tilakrayal** [comment]
@chrisby,
The related PR #59132  has been assigned for reviewing and once it is merged this issue will move to closed status. Thank you!

**Comment by tilakrayal** [comment]
@chrisby,
The related PR #59132 was closed and needed your response. Could you please check the PR and respond accordingly. Thank you!

**Comment by chrisby** [comment]
> @chrisby, The related PR #59132 was closed and needed your response. Could you please check the PR and respond accordingly. Thank you!

Will take a look next week. Sorry for this to get stale.
