### ISSUE TITLE
Unsuported fullyconnected operator type by tflite

### ISSUE THREAD

**Issue by RuxandraRusu29** [tensorflow/tensorflow#58987]
**System information**
- Tested on ColabPro
- TensorFlow 2.9.2

**Issue**
Tensorflow lite does not support the following quantized fully_connected operation:
Input parameters:
-input int8
-filter int8
-bias int32
Output:
-output int16

After debugging the library, I have noticed that this case is not supported, moreover, no error is is thrown. During the evaluation step, in the file tensorflow/lite/kernels/fully_connected.cc, the model will take a default case and does not check the input type. Instead of throwing an error it casts the input and the filter to uint8 and evaluates that operator.

```
import numpy as np
import tensorflow as tf

# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="fc.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

#read and reshape input data
input_data = np.fromfile("input_int8.dat", dtype="int8")
input_data = np.int8(np.reshape(input_data, (1, 25)))

output_data = interpreter.get_tensor(output_details[0]['index'])
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

output_data = interpreter.get_tensor(output_details[0]['index'])
print("output type and data")
print(type(output_data[0][0]))
print(output_data)

out_ref = np.fromfile("output_int16.dat", dtype="int8")
print(out_ref)

output_data = interpreter.get_tensor(output_details[0]['index'])
print("output type and data")
print(type(output_data[0][0]))
print(output_data)
```
*Output*
output type and data
<class 'numpy.int16'>
[[ -303 -4117 -2604 -1706  -103 -2236 -2852 -1752 -3658 -2029 -2906 -3052
  -1304  -841 -2676  -568 -1770   220 -1328 -3144   946  -138 -2438 -3258
  -2163   -83 -1152 -1862 -3949   946 -1991 -3275 -3667   869  -513 -4450
  -3700 -1207 -2309 -2831 -2757 -1710  -143 -5043 -2749 -5654 -2191 -4625
   -377 -1835  -369 -4886 -3887 -3610  1371  -564   843  -939 -2472 -3719
  -3490 -2867 -2712 -3368 -2164 -1430 -3685 -1830 -2481   836   211 -4628
  -2289  1850 -2082 -5311  -975 -2097  -113 -6531 -2485 -1459 -2250 -1654
  -3846 -2472 -2383 -2547 -3155 -1895   159  1065  1221 -2099 -2449 -1530
  -3535    -5 -4117 -2345]]
ref output
[ -45    5    8    0  -67   -5   11   -5  121   -6   26  -32  121  -11
 -102   -6   50  -20  121   -1   60  -21   -4  -20   57   21 -114   -8
 -100   -2    7   14  -44   11  -17   -2  -79  -11  -44  -10   40   -5
   56    8   46  -15  -15  -30  112    0   13   16   56   -1   15    3
  -72  -14    7   14  -35   -4  -21   -5  -95   -9 -128   12  -15    2
  -86    1  121   -7  -60   -5   81  -11   65  -16  -63    1 -100    3
   74   -4  108   -9   -6   -3  114   -9 -100   -4   32  -28   46   17
  -51    6  -22   11  116  -17  -78    4 -100  -25    
9    3  -18   -9
   34    5   -9    5   20    2   30    3  101  -35   53   -9   40   -9
   96  -12   61    3   -5    6   80  -19   -4   11    2   -3  -18   10
   63   11   95   -4   70  -22   35   19  -58  -16  -96  -18   37  -17
  -63  -29  -79   -1  -63   -7  -79  -22  -90  -13   16   -5  -50    6
    3  -10   64   20   80   -8 -100  -30  -87   -3   27  -16  -25    9
    3   14  -15   10   26   -9   17    6  -60    6  -83   -1   34   -3
   -3  -13  117  -15]

[fc.zip](https://github.com/tensorflow/tensorflow/files/10287488/fc.zip)
[output_int16.zip](https://github.com/tensorflow/tensorflow/files/10287495/output_int16.zip)

**Comment by tiruk007** [comment]
@mohantym 
I was able to reproduce the issue on colab using TF 2.11 . Please find the gist [here](https://colab.research.google.com/gist/tiruk007/5cb783e354042d48f54a0fe419f6f04e/untitled49.ipynb) for reference.

Thank you!

**Comment by mohantym** [comment]
Hi @RuxandraRusu29 !
Thanks for sharing your results on quantization of  fully connected operator. 

@sachinprasadhs !
Could you look at this issue. Attached gist in [2.9](https://colab.sandbox.google.com/gist/mohantym/00a6ac75a002c23338f9d597c22f4350/untitled49.ipynb#scrollTo=kfBqb7nTrVhS), [2.10](https://colab.sandbox.google.com/gist/mohantym/26acfa26e0feeefeffb7b5d02dc71f78/untitled49.ipynb#scrollTo=VH3_lZtKqTMR), [2.11 ](https://colab.sandbox.google.com/gist/mohantym/dabcfa6ca4179f1931e54884229f1630/untitled49.ipynb#scrollTo=_k0Ur6cZ0fXy)and [nightly ](https://colab.sandbox.google.com/gist/mohantym/a9fcf7be3118a24768f60d8fbec2375f/untitled49.ipynb#scrollTo=mGlBuSNErOzx) for reference.  

Thank you!

**Comment by RuxandraRusu29** [comment]
Hi @sachinprasadhs when is this issue expected to be resolved?

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
