### ISSUE TITLE
NNAPI initialization from cache has hardly any time benefit

### ISSUE THREAD

**Issue by derpda** [tensorflow/tensorflow#58990]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

2.10.1

### Custom Code

Yes

### OS Platform and Distribution

Android 12

### Mobile device

Pixel 3a

### Python version

N/A

### Bazel version

cmake 3.16.3

### GCC/Compiler version

NDK r19c

### Current Behaviour?

I am trying to use compilation caching with the NNAPI delegate to reduce startup time.
To test this, I have written a small program that loads a tflite model from disk, applies the NNAPI delegate and runs invoke once. 
The NNAPI delegate is provided with the necessary settings (`model_token` and `cache_dir`), and indeed on first invocation I as expected receive:
```
ERROR: File /data/local/tmp/model_5156108677284121472.bin couldn't be opened for reading: No such file or directory
```
After this first execution, the relevant file was created and subsequent executions did indeed no longer show the cache miss error.

The problem is that there are no significant time savings.
I ran the test binary produced with the steps below on my Pixel3a and crudely measured the first execution takes 2.62 seconds while the second one takes 2.49 seconds (see logs).
For reference, the same execution takes only 0.29 seconds when not applying the NNAPI delegate (again see logs).

I have tried this with a few different models, but results were always similar.
Note that this same setup works fine with the GPU delegate, where the first execution takes a couple seconds and consecutive executions are drastically faster.

Is this expected behavior with the NNAPI delegate, possibly a bug, or is there something wrong with how I am trying to use compilation caching?

### Standalone code to reproduce the issue
```c++
#include "tensorflow/lite/delegates/nnapi/nnapi_delegate.h"
#include "tensorflow/lite/interpreter_builder.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model_builder.h"

#include <iostream>
#include <memory>

int main() {
  auto model = tflite::FlatBufferModel::BuildFromFile("model.tflite");
  auto resolver = std::make_unique<tflite::ops::builtin::BuiltinOpResolver>();
  auto builder = tflite::InterpreterBuilder(*model, *resolver);
  std::unique_ptr<tflite::Interpreter> interpreter;
  builder(&interpreter);

  tflite::StatefulNnApiDelegate::Options options;
  options.cache_dir = "/data/local/tmp";
  options.model_token = "model";
  auto delegate = tflite::StatefulNnApiDelegate(options);

  if (interpreter->ModifyGraphWithDelegate(&delegate) != kTfLiteOk) {
    std::cerr << "Failed to apply NNAPI delegate." << std::endl;
    return -1;
  };
  if (interpreter->AllocateTensors() != kTfLiteOk) {
    std::cerr << "Failed to allocate tensors." << std::endl;
    return -2;
  }
  if (interpreter->Invoke() != kTfLiteOk) {
    std::cerr << "Failed to invoke." << std::endl;
    return -3;
  }
  std::cout << "Success!" << std::endl;
  return 0;
}
```

To compile, place in same directory with this dockerfile
```dockerfile
FROM tensorflow/tensorflow:devel

RUN apt-get update &&\
    DEBIAN_FRONTEND=noninteractive apt-get install -y cmake

ARG NDK_VERSION=r19c
ARG NDK_DIR=android-ndk-${NDK_VERSION}
ARG NDK_FILE=${NDK_DIR}-linux-x86_64.zip
ARG TENSORFLOW_VERSION=2.10.1
ARG TENSORFLOW_DIR=tensorflow-${TENSORFLOW_VERSION}
RUN curl -s https://dl.google.com/android/repository/${NDK_FILE} \
        --output /${NDK_FILE}
RUN unzip -q /${NDK_FILE}
RUN curl -s https://codeload.github.com/tensorflow/tensorflow/zip/refs/tags/v${TENSORFLOW_VERSION} \
        --output /${TENSORFLOW_DIR}.zip
RUN unzip -q /${TENSORFLOW_DIR}.zip
RUN mkdir /${TENSORFLOW_DIR}/build
RUN cd /${TENSORFLOW_DIR}/build &&\
    cmake -DCMAKE_TOOLCHAIN_FILE=/${NDK_DIR}/build/cmake/android.toolchain.cmake \
        -DANDROID_ABI=arm64-v8a \
        -DTFLITE_ENABLE_GPU=ON \
        /${TENSORFLOW_DIR}/tensorflow/lite &&\
    cd /${TENSORFLOW_DIR}/build &&\
    cmake --build . -j$(nproc)
RUN mkdir /compile_cache_test
RUN find /${TENSORFLOW_DIR}/build -name "*.a" -exec cp {} /compile_cache_test \;
RUN mkdir /compile_cache_test/build
ADD CMakeLists.txt /compile_cache_test
ADD compile_cache_test.cpp /compile_cache_test
RUN cd /compile_cache_test/build &&\
    cmake -DCMAKE_TOOLCHAIN_FILE=/${NDK_DIR}/build/cmake/android.toolchain.cmake \
        -DANDROID_ABI=arm64-v8a \
        /compile_cache_test &&\
    cmake --build .
```

as well as this CMake file 
```cmake
cmake_minimum_required(VERSION 3.16)
project(NNAPICompileCacheTest CXX)
set(CMAKE_CXX_STANDARD 17)

set(TENSORFLOW_DIR /tensorflow-2.10.1)
find_library(TFLite_LIBRARY tensorflow-lite
  PATHS ${CMAKE_SOURCE_DIR} NO_CMAKE_FIND_ROOT_PATH)
file(GLOB_RECURSE TFLite_DEPENDENCIES ${CMAKE_SOURCE_DIR}/*.a)
list(REMOVE_ITEM TFLite_DEPENDENCIES ${TFLite_LIBRARY})
message(STATUS "TFLite_DEPENDENCIES: ${TFLite_DEPENDENCIES}")
add_library(tensorflow-lite UNKNOWN IMPORTED)
set_target_properties(tensorflow-lite PROPERTIES
  IMPORTED_LOCATION "${TFLite_LIBRARY}"
  INTERFACE_INCLUDE_DIRECTORIES
    "${TENSORFLOW_DIR};${TENSORFLOW_DIR}/build/flatbuffers/include"
  INTERFACE_LINK_LIBRARIES "${TFLite_DEPENDENCIES};${TFLite_DEPENDENCIES}"
)

add_executable(compile_cache_test compile_cache_test.cpp)
target_link_libraries(compile_cache_test log tensorflow-lite)
```

It's a bit unorthodox, but building the image will also build the executable. So build with
```
docker build . -t compile_cache_test
```

And then run the below line to extract the binary compiled for android-arm64.
```
docker run -it --rm -v $PWD:/host_dir compile_cache_test cp /compile_cache_test/build/compile_cache_test /host_dir
```

Then, push this binary using `adb push compile_cache_test /data/local/tmp`, and also push some tflite model that can be (at least partially) used with NNAPI.
The timings above were recorded with the tflite model from [here](https://raw.githubusercontent.com/juandes/mobiledet-tflite-nnapi/master/app/src/main/assets/model.tflite), which also needs to be pushed to `/data/local/tmp`.

#### First run. Cache miss as expected.
```shell
sargo:/data/local/tmp $ time ./compile_cache_test                                             
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for NNAPI.
ERROR: File /data/local/tmp/model_17199993934519011812.bin couldn't be opened for reading: No such file or directory
WARNING: NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
VERBOSE: Replacing 108 node(s) with delegate (TfLiteNnapiDelegate) node, yielding 1 partitions.
Success!
    0m02.62s real     0m00.16s user     0m00.06s system
```

#### Second run (cache used?)
```shell
sargo:/data/local/tmp $ time ./compile_cache_test                                             
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for NNAPI.
VERBOSE: Replacing 108 node(s) with delegate (TfLiteNnapiDelegate) node, yielding 1 partitions.
WARNING: NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
Success!
    0m02.49s real     0m00.13s user     0m00.08s system
```

#### Run without NNAPI
```shell
sargo:/data/local/tmp $ time ./compile_cache_test                                             
INFO: Initialized TensorFlow Lite runtime.
Success!
    0m00.29s real     0m00.26s user     0m00.01s system
```
</details>

**Comment by Kottsone** [comment]
@derpda Thanks for reporting the issue. The NNAPI compilation caching behavior depends on the capability of the underlying driver. Based on the provided device info (Pixel 3a Android 12), it is likely that the underlying qti-gpu driver does not implement compilation caching support.

**Comment by derpda** [comment]
Thanks for responding to this! I'll try it on other devices and see if I get any benefit.

Let me just note that I am using qti-default on the Pixel 3a (as in, I don't specify the accelerator name), which I think ends up using the qti-dsp driver.

To check this, I tried specifying qti-gpu and there are no log messages regarding cache usage. Startup is very fast (suspiciously fast...), leading me to believe that the delegate isn't correctly applied. The CPU-like performance supports that as well.
Specifying qti-dsp yields the slow startup but fast inference I laid out in this issue.

For the GPU delegate (not through NnApi), compilation provides significant benefit and works fine.

**Comment by Kottsone** [comment]
Thanks for the additional info! 

Sorry for the confusion. I originally thought you were using qti-gpu because you mentioned GPU delegate as well, but it looks like it is actually using qti-dsp. (qti-gpu is for floating point models and qti-dsp is for quantized models) qti-dsp should have some level of compilation caching support with sufficient driver version, but pixel 3a may not be a supported device variant.

Could you inspect the android logcat to see if there is any useful information?

On Android 12, the following logcat message (when compiling the second time) may indicate compilation caching is not supported:

```
prepareModelFromCache failure (GENERAL_FAILURE): hardware/interfaces/neuralnetworks/1.3/utils/src/Callbacks.cpp:80: model preparation failed with GENERAL_FAILURE
```

Starting from Android 13, you can expect the following logcat when compilation caching is supported:

```
prepareModelFromCache: successfully prepared model from cache
```
