### ISSUE TITLE
Missing interger overflow check in TensorFlow

### ISSUE THREAD

**Issue by edwardyehuang** [tensorflow/tensorflow#58994]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

Yes

### Current Behaviour?

```shell
Tensorflow does not check integer overflow, which is dangerous and can cause bugs for many users.
```

### Standalone code to reproduce the issue

```shell
a = 2147483648
print(tf.convert_to_tensor(a, tf.int32))
```

BUG case:
```shell
print(a* tf.constant(1, tf.int32))

```

### Relevant log output

_No response_</details>

**Comment by Sarvesh-Kesharwani** [comment]
![chrome_1Iqasz0IPA](https://user-images.githubusercontent.com/22115102/209446440-8fff7311-ca7d-4d1e-b1d8-6b3e98475aa6.png)

Hi, edwardyehuang, i tried to run the code you mentioned, but there is no bug in my case, please correct me if i am wrong.

**Comment by Sarvesh-Kesharwani** [comment]
![chrome_s7PB5FSQCP](https://user-images.githubusercontent.com/22115102/209446712-30917be0-85d8-4e09-a9a5-30b3aa39865b.png)

**Comment by mohantym** [comment]
@edwardyehuang !
Thanks for the PR #58996. This issue will be closed once PR is merged.
Thank you!

**Comment by Rishikesh2338** [comment]
If this Pr is not assigned to anyone I can do this.

**Comment by mohantym** [comment]
Sure @Rishikesh2338 !

The Fix has to be replicated in C++ side as per [mihais comment](https://github.com/tensorflow/tensorflow/pull/58996#pullrequestreview-1232167726). 
Possible location is [ops.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/ops.cc).

will post an update by End of week. 

Thank you!

**Comment by mohantym** [comment]
Hi @SuryanarayanaY !
Could you look at this issue.  Attached gist in [2.9](https://colab.sandbox.google.com/gist/mohantym/d817178cd71bd497e1b3484a77f27ffa/git_58994_2-10.ipynb#scrollTo=Lh4zl4w3vGMS), [2.10](https://colab.sandbox.google.com/gist/mohantym/1dc29fda6bb44a8b209db8a8c86b5b9c/git_58994_2-10.ipynb#scrollTo=Lh4zl4w3vGMS), [2.11](https://colab.sandbox.google.com/gist/mohantym/7e36deff1c81517c6db852ef7511d0be/git_58994_2-10.ipynb#scrollTo=poYHdLehv_Pj) for reference.
Thank you!

**Comment by edwardyehuang** [comment]
> Hi @SuryanarayanaY ! Could you look at this issue. Attached gist in [2.9](https://colab.sandbox.google.com/gist/mohantym/d817178cd71bd497e1b3484a77f27ffa/git_58994_2-10.ipynb#scrollTo=Lh4zl4w3vGMS), [2.10](https://colab.sandbox.google.com/gist/mohantym/1dc29fda6bb44a8b209db8a8c86b5b9c/git_58994_2-10.ipynb#scrollTo=Lh4zl4w3vGMS), [2.11](https://colab.sandbox.google.com/gist/mohantym/7e36deff1c81517c6db852ef7511d0be/git_58994_2-10.ipynb#scrollTo=poYHdLehv_Pj) for reference. Thank you!

Note that, this is not only the issue in `tf.convert_to_tensor`.

The example below is also dangerous.

```
import tensorflow as tf

a = 2147483647
a = tf.convert_to_tensor(a, tf.int32)

print(a) # tf.Tensor(2147483647, shape=(), dtype=int32)

b = a + tf.constant(1, tf.int32)

print(b) # tf.Tensor(-2147483648, shape=(), dtype=int32)
```

**Comment by edwardyehuang** [comment]
@mihaimaruseac  @mohantym Could you remove the flag "awaiting PR merge" please?
