### ISSUE TITLE
Missing zip file

### ISSUE THREAD

**Issue by RolWinde** [tensorflow/tensorflow#58991]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

not available, see "Current Behaviour"

### Custom Code

Yes

### OS Platform and Distribution

Windows 11

### Mobile device

-

### Python version

-

### CUDA/cuDNN version

12

### GPU model and memory

NVidia GForce

### Current Behaviour?

```shell
Hi gents

I just tried to load a zip file from your server to enhance grafic speed with GPU
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-2.11.0.zip

Unfortunatly I only get this:

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-2.11.0.zip</Details>
</Error>

Can you fix this?

https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.11.0.zip works!?
although I just saw, that the CPU zip has issues too, some files are missing.


Best regards
Roland Winde
```

### Standalone code to reproduce the issue

```shell
not available
```

### Relevant log output

```shell
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-2.11.0.zip</Details>
</Error>
```
</details>

**Comment by mohantym** [comment]
Hi @RolWinde !

Could you try now. I can download through above zip link.
Attached [gist](https://colab.sandbox.google.com/gist/mohantym/b669a0ef7bd86c7ede7b20117b25ceb7/git_58991.ipynb) for reference.

Thank you!

**Comment by RolWinde** [comment]
Thank you Manas

 

With that attached link I was able to download.

 

best regards

RolWinde

 

Von: Manas Mohanty ***@***.***> 
Gesendet: Sonntag, 25. Dezember 2022 04:03
An: tensorflow/tensorflow ***@***.***>
Cc: RolWinde ***@***.***>; Mention ***@***.***>
Betreff: Re: [tensorflow/tensorflow] Missing zip file (Issue #58991)

 

Hi @RolWinde <https://github.com/RolWinde>  !

Could you try now. I can download through above zip link.
Attached gist <https://colab.sandbox.google.com/gist/mohantym/b669a0ef7bd86c7ede7b20117b25ceb7/git_58991.ipynb>  for reference.

Thank you!

**Comment by mohantym** [comment]
Ok @RolWinde !

Thanks for the confirmation.
Marking this issue as resolved then. 

Thank you!

**Comment by mohantym** [comment]
Hi @RolWinde !

Thanks for bringing out the breakage of windows GPU wheel.  You can put your comments in #59016 as re-opening this issue be duplicating the effort.

Thank you!
