### ISSUE TITLE
How Do I Convert input arg tf.string to string in tf.function 

### ISSUE THREAD

**Issue by zf853109035** [tensorflow/tensorflow#58992]
@tf.function(input_signature=[
        tf.TensorSpec(shape=[], dtype=tf.string, name="key"),
        tf.TensorSpec(shape=[], dtype=tf.string, name="value")
    ])
    def infer(self, key, value):
          tf.print(key)
          xxx

I want to implement universal input, something like this
key: age#gender
value: 0#1
=> 
age_tensor = tf.constant(value=0, name="age")
gender_tensor = tf.constant(value=1,name="gender")

so I want to convert tf.string to string.
use tf.print function can normally print the input args，Do I have any way to simulate the function of tf.print and assign the printed value to a variable to implement tf.string to string?
or
Is there any other way I can do this?

**Comment by tilakrayal** [comment]
@zf853109035,
To manipulate string values in TF, have a look at the [tf.strings namespace](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/strings).

Could you please try to use `tf.strings.substr`:

```
@tf.function
def ppm_to_png(filepath):
  ppm_bytes = tf.io.read_file(filepath)
  bytes_header = tf.strings.substr(ppm_bytes, 0, 13)
  tf.print(bytes_header)

```
tf.slice only operates on the Tensor objects, and doesn't work on their elements. Here, ppm_bytes is a scalar Tensor containing a single element of type tf.string, and whose value is the entire string contents of the file. So when you call tf.slice, it only looks at the scalar bit, and is not smart enough to realize that you actually want to take a slice of that element instead. Thank you!
