### ISSUE TITLE
Error in final step of installation

### ISSUE THREAD

**Issue by jonathanmalkin** [tensorflow/tensorflow#59]
Following the instructions at http://tensorflow.org/get_started/os_setup.md#virtualenv_install

The last command for installation is this -- 
"(tensorflow)unknownb8e85638de86:tensorflow jonathanmalkin$ pip install --upgrade <$url_to_binary.whl>"

I get the following response -- 
"-bash: syntax error near unexpected token `newline'"

**Comment by vrv** [comment]
hi @jonathanmalkin: if you fill in the path to the .whl file for the platform you are building, it should work.

e.g., if you were installing for OS X, you should do:

```bash
pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl
```

**Comment by jonathanmalkin** [comment]
Thanks! That works.

Jonathan Malkin
813-579-7247

**Comment by titubeta** [comment]
@vrv after installing tensorflow with virtualenv on Ubuntu 14.04, the only files I see in the folders are
`bin  include  lib  local`. There is no model folder. How can I run convolution.py?

**Comment by jonathanmalkin** [comment]
I'm having the same issue using virtualenv on Mac OS.



Jonathan Malkin
813-579-7247

**Comment by TheCypher** [comment]
Thank you! pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl works great on virtualenv

**Comment by colinlovefish** [comment]
thank you
