### ISSUE TITLE
pip install does not install the examples folder

### ISSUE THREAD

**Issue by elzurdo** [tensorflow/tensorflow#590]
When doing on my Mac:
sudo pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.6.0-py2-none-any.whl
I got tensorflow to install, but without the `examples`directory. 
There is no mention of that in the setup here:
The page https://www.tensorflow.org/versions/master/get_started/os_setup.html

I needed the `examples` to do this tutorial:
https://www.tensorflow.org/versions/master/tutorials/mnist/beginners/index.html

(for the time being I just downloaded the whole zip of the repository and copy-pasted the folder, and so far appears to work)

Did I miss anything when installing?

**Comment by sukruozan** [comment]
I solved the same problem as follows:

Try by using virtualenv with option --python=python2.7  After that activate the virtual environment. And make the installation with pip2.7. I hope this works!

**Comment by gotope** [comment]
I have the same problem, @sukruozan @elzurdo 
do you run it like？   virtualenv --system-site-packages **--python=python2.7 ** ~/tensorflow

**Comment by sukruozan** [comment]
Yes, and after that I used pip2.7 to install the corresponding wheel file. I worked just fine for me...

**Comment by martinwicke** [comment]
I believe this has been fixed, closing. Comment if it's still a problem in the recent 0.8 release.

**Comment by sleepdeprivation** [comment]
I had this issue with version 6.0.8

**Comment by attibalazs** [comment]
facing this issue using version 0.11 and python 3.5.2 within an anaconda environment

**Comment by xuefeng7** [comment]
still having this issue version 0.12, python 2.7.10

**Comment by xuefeng7** [comment]
while installing with pip, there has no image_training dir under examples dir

**Comment by Noahyt** [comment]
I had this issue Python 2.7.10, tf .12, OSX 10.12.3
