### ISSUE TITLE
Segmentation fault when running tensorflow.python.ops.gen_nn_ops.fused_batch_norm_v3

### ISSUE THREAD

**Issue by cse19922021** [tensorflow/tensorflow#59001]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.4

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.4

### Python version

3.8

### CUDA/cuDNN version

release 11.0, V11.0.194 Build cuda_11.0_bu.TC445_37.28540450_0

### Current Behaviour?

```shell
If tensorflow.python.ops.gen_nn_ops.fused_batch_norm_v3 is given empty scale input tensor, it results in segmentation fault and crash the program.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.python.ops import gen_nn_ops
try:
  try:
    with tf.device('/CPU'):
      arg_0_tensor = tf.random.uniform([1, 2, 1, 6], dtype=tf.float16)
      arg_0 = tf.identity(arg_0_tensor)
      arg_1_tensor = [] 
      arg_1 = tf.identity(arg_1_tensor)
      arg_2_tensor = tf.random.uniform([6], dtype=tf.float32)
      arg_2 = tf.identity(arg_2_tensor)
      arg_3_tensor = tf.random.uniform([6], dtype=tf.float32)
      arg_3 = tf.identity(arg_3_tensor)
      arg_4_tensor = tf.random.uniform([6], dtype=tf.float32)
      arg_4 = tf.identity(arg_4_tensor)
      epsilon = 0.001
      exponential_avg_factor = 1.0
      data_format = "NHWC"
      is_training = False
 gen_nn_ops.fused_batch_norm_v3(arg_0,arg_1,arg_2,arg_3,arg_4,epsilon=epsilon,exponential_avg_factor=exponential_avg_factor,data_format=data_format,is_training=is_training,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      arg_0 = tf.identity(arg_0_tensor)
      arg_0 = tf.cast(arg_0, tf.float16)
      arg_1 = tf.identity(arg_1_tensor)
      arg_1 = tf.cast(arg_1, tf.float32)
      arg_2 = tf.identity(arg_2_tensor)
      arg_2 = tf.cast(arg_2, tf.float32)
      arg_3 = tf.identity(arg_3_tensor)
      arg_3 = tf.cast(arg_3, tf.float32)
      arg_4 = tf.identity(arg_4_tensor)
      arg_4 = tf.cast(arg_4, tf.float32)
gen_nn_ops.fused_batch_norm_v3(arg_0,arg_1,arg_2,arg_3,arg_4,epsilon=epsilon,exponential_avg_factor=exponential_avg_factor,data_format=data_format,is_training=is_training,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```

### Relevant log output

```shell
Segmentation fault (core dumped)
```
</details>

**Comment by tiruk007** [comment]
@cse19922021 
I was able to execute the given code without a session crash or Segmentation fault (core dumped) on Colab using TF v2.11. Could you please try with the latest version which is TF v2.11 and also v2.4 is pretty old, There is a high possibility that this was fixed with later TF versions.
Please find the gist [here](https://colab.research.google.com/gist/tiruk007/92c3f9944a6fc7df75781c224d7747f8/untitled50.ipynb) for reference and let us know if it helps. 
Thank you!

**Comment by nimashiri** [comment]
> @cse19922021 I was able to execute the given code without a session crash or Segmentation fault (core dumped) on Colab using TF v2.11. Could you please try with the latest version which is TF v2.11 and also v2.4 is pretty old, There is a high possibility that this was fixed with later TF versions. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/92c3f9944a6fc7df75781c224d7747f8/untitled50.ipynb) for reference and let us know if it helps. Thank you!

Thanks for the reply. This issue is only for 2.4.

**Comment by mihaimaruseac** [comment]
This seems invalid. Log message does not show claimed crash. Affected version is old.
