### ISSUE TITLE
Crash when running tensorflow.python.ops.gen_linalg_ops.cholesky

### ISSUE THREAD

**Issue by cse19922021** [tensorflow/tensorflow#59002]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.4.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.4

### Python version

3.8

### CUDA/cuDNN version

release 11.0, V11.0.194 Build cuda_11.0_bu.TC445_37.28540450_0

### Current Behaviour?

```shell
If tensorflow.python.ops.gen_linalg_ops.cholesky is given negative input tensor, it results in crash.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.python.ops import gen_linalg_ops
try:
  try:
    with tf.device('/CPU'):
      arg_0_tensor = tf.complex(tf.constant(-1250, shape=[20, 20], dtype=tf.float32,),tf.constant(-1250, shape=[20, 20], dtype=tf.float32,))
      arg_0_tensor = tf.complex(tf.constant([], shape=[20, 20], dtype=tf.float32,),tf.constant([], shape=[20, 20], dtype=tf.float32,))
      arg_0 = tf.identity(arg_0_tensor)
      gen_linalg_ops.cholesky(arg_0,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      arg_0 = tf.identity(arg_0_tensor)
      arg_0 = tf.cast(arg_0, tf.complex64)
      gen_linalg_ops.cholesky(arg_0,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```

### Relevant log output

```shell
Aborted (Core dumped)
```
</details>

**Comment by mohantym** [comment]
Hi @cse19922021 !

I could not replicate this issue in [2.9](https://colab.sandbox.google.com/gist/mohantym/06f51c35554732add2972e3c0004ec54/git_59002.ipynb), [2.10 ](https://colab.sandbox.google.com/gist/mohantym/2fa44cfcb1340e96ed2d24d9ee099939/git_59002.ipynb#scrollTo=6-QWs743zUGb)and [nightly](https://colab.sandbox.google.com/gist/mohantym/fb3b09fa5fa6680bd7cc41206f711fc6/git_59002.ipynb#scrollTo=K4pkoc9LzIi0) .
Could you let us know from your side. 

Thank you!

**Comment by nimashiri** [comment]
> Hi @cse19922021 !
> 
> I could not replicate this issue in [2.9](https://colab.sandbox.google.com/gist/mohantym/06f51c35554732add2972e3c0004ec54/git_59002.ipynb), [2.10 ](https://colab.sandbox.google.com/gist/mohantym/2fa44cfcb1340e96ed2d24d9ee099939/git_59002.ipynb#scrollTo=6-QWs743zUGb)and [2.11](https://colab.sandbox.google.com/gist/mohantym/fb3b09fa5fa6680bd7cc41206f711fc6/git_59002.ipynb#scrollTo=K4pkoc9LzIi0) . Could you let us know from your side.
> 
> Thank you!

Thanks. On my side, I get the issue on 2.4.

**Comment by mihaimaruseac** [comment]
This seems invalid. Log message does not show claimed crash. Affected version is old.
