### ISSUE TITLE
Im2txt: "No variables to save" error at the initial training stage

### ISSUE THREAD

**Issue by sonerdemiray** [tensorflow/tensorflow#5901]
Hi,

I'm trying to train im2txt (show & tell) model with mscoco dataset using tensorflow-0.11.

I successfully completed the downloaded & preprocess steps described in the guide (https://github.com/tensorflow/models/tree/master/im2txt).

I'm using the inception_v3.ckpt model for the initial training process.

But I'm getting "no variables to save" error @ show_and_tell_model.py in function setup_inception_initializer at line 
 saver = tf.train.Saver(self.inception_variables)
I print out self.inception_variables on the line above and I see that it is an empty list.

Below is the complete dump of the error.

Any help would be appreciated.

Thanks.

python train.py \
	--input_file_pattern="/usr/local/tensorflow-models/im2txt/im2txt/data/mscoco/train-?????-of-00256" \
	--inception_checkpoint_file="/usr/local/tensorflow-models/im2txt/im2txt/data/inception_v3.ckpt" \
	--train_dir="/usr/local/tensorflow-models/im2txt/im2txt/model/train" \
	--train_inception=false \
	--number_of_steps=1000000
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally
INFO:tensorflow:Prefetching values from 256 files matching /usr/local/tensorflow-models/im2txt/im2txt/data/mscoco/train-?????-of-00256
Traceback (most recent call last):
  File "train.py", line 117, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train.py", line 67, in main
    model.build()
  File "/usr/local/tensorflow-models/im2txt/im2txt/show_and_tell_model.py", line 361, in build
    self.setup_inception_initializer()
  File "/usr/local/tensorflow-models/im2txt/im2txt/show_and_tell_model.py", line 335, in setup_inception_initializer
    saver = tf.train.Saver(self.inception_variables)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1000, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1021, in build
    raise ValueError("No variables to save")
ValueError: No variables to save

**Comment by poxvoculi** [comment]
@ilblackdragon Looks like there was a recent change to show_and_tell_model.py that renamed tf.GraphKeys.VARIABLES to tf.GraphKeys.GLOBAL_VARIABLES.  Could that be causing this problem?

**Comment by sonerdemiray** [comment]
Thank you Paul!

I changed the statement tf.GraphKeys.VARIABLES to tf.GraphKeys.GLOBAL_VARIABLES in function build_image_embeddings as well as in function setup_global_step. The training process started without any other problem.

Thank you for your help. :)

Best,
Soner
