### ISSUE TITLE
Window only link

### ISSUE THREAD

**Issue by bobbryant** [tensorflow/tensorflow#59016]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

source

### Tensorflow Version

na

### Custom Code

No

### Current Behaviour?

```shell
The Windows Only link is not working
```

### Standalone code to reproduce the issue

```shell
Try and download the Window only version of tensorflow and it fails
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-2.11.0.zip</Details>
</Error>
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@bobbryant 
TensorFlow 2.10 was the last TensorFlow release that supported GPU on native-Windows.We are not maintaining the GPU wheel for tensorflow 2.11.
If you would like to use GPU on windows, we request you to use tensorflow [2.10 GPU]( https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-2.10.0.zip)  

Thank you!
