### ISSUE TITLE
tf.truncatediv not support float, but doc support.

### ISSUE THREAD

**Issue by DavidFFFan** [tensorflow/tensorflow#59018]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

v2.9.1-132-g18960c44ad3 2.9.2

### Custom Code

Yes

### OS Platform and Distribution

colab

### Mobile device

colab

### Python version

3.8

### Current Behaviour?

```shell
The tf.truncatediv documentation shows that float is supported, but the actual test only supports integer types.
document: https://www.tensorflow.org/versions/r2.7/api_docs/python/tf/truncatediv
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

a = np.array([1., 2., 3.])
x = tf.convert_to_tensor(a)
b = np.array([2.])
y = tf.convert_to_tensor(b)
tf.truncatediv(x, y)
```

### Relevant log output

```shell
NotFoundError: Could not find device for node: {{node TruncateDiv}} = TruncateDiv[T=DT_DOUBLE]
All kernels registered for op TruncateDiv:
  device='GPU'; T in [DT_UINT64]
  device='GPU'; T in [DT_UINT32]
  device='GPU'; T in [DT_INT8]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_INT16]
  device='GPU'; T in [DT_UINT16]
  device='GPU'; T in [DT_UINT8]
  device='CPU'; T in [DT_INT64]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_INT16]
  device='CPU'; T in [DT_INT8]
  device='CPU'; T in [DT_UINT64]
  device='CPU'; T in [DT_UINT32]
  device='CPU'; T in [DT_UINT16]
  device='CPU'; T in [DT_UINT8]
 [Op:TruncateDiv]
```
```
</details>

**Comment by tilakrayal** [comment]
@DavidFFFan,
The code mentioned above was able to execute without any issue/error in the tf-nightly version`(2.12.0-dev20221226).` Could you please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/827e2a9d6eab4e8e70b999006f703ee4/untitled823.ipynb) and confirm if it resolves the issue? Thank you!

**Comment by DavidFFFan** [comment]
> @DavidFFFan, The code mentioned above was able to execute without any issue/error in the tf-nightly version`(2.12.0-dev20221226).` Could you please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/827e2a9d6eab4e8e70b999006f703ee4/untitled823.ipynb) and confirm if it resolves the issue? Thank you!
Thanks! tf-nightly does already solve this problem.

**Comment by tilakrayal** [comment]
@DavidFFFan,
Glad the issue is resolved for you, please feel free to move this issue to closed status. Thank you!
