### ISSUE TITLE
tensor_util.py

### ISSUE THREAD

**Issue by korayerbas** [tensorflow/tensorflow#59021]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf.2.9.2

### Custom Code

Yes

### Mobile device

Windows 10

### Python version

3.8

### Current Behaviour?

```shell
A bug happened! Please refer "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/tensor_util.py" line 495, in make_tensor_proto

shape = [int(dim) for dim in shape] gives error. It is not possible to iterate with integer. Needs to be fixed.
```

### Standalone code to reproduce the issue

```shell
https://github.com/korayerbas/HDRCNN.git
It is Eilertsen's HDRCNN work from 2017. I try to rewrite the code; I try to rewrite the code in version 2 Tensorflow. As described above I absorved the bug.
```

### Relevant log output

```shell
TypeError: 'int' object is not iterable
```
</details>

**Comment by sushreebarsa** [comment]
@korayerbas Sorry for the late response!
Could you please provide a simple standalone code to replicate the issue reported?
Thank you!
