### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15.2

### ISSUE THREAD

**Issue by Colabnoob** [tensorflow/tensorflow#59025]
I use google colab and was wondering if anyone can solve this problem, if you want to fix my notebook I will leave a link down below, thanks if you solve it!
https://colab.research.google.com/drive/1ecuUD2sxfuM6IOhjZEW3ls-jvbpJEei4?usp=share_link

**Comment by tilakrayal** [comment]
@Colabnoob,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.11 and check if you are facing the same issue. Thank you!

**Comment by Colabnoob** [comment]
Thanks for the response, so I ran the first set of commands and it worked, when I initialize tacotron2 and waveglow I run into another error unfortunately, this is the error, I would really appreciate if you can help me because I had this problem for a month. 
/content/tacotron2/text/__init__.py:74: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  return s in _symbol_to_id and s is not '_' and s is not '~'
/content/tacotron2/text/__init__.py:74: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  return s in _symbol_to_id and s is not '_' and s is not '~'
/usr/local/lib/python3.8/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1E12g_sREdcH5vuZb44EZYX8JjGWQ9rRp
To: /content/merged.dict.txt
100% 7.94M/7.94M [00:00<00:00, 136MB/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-3-17a77c4b9573>](https://localhost:8080/#) in <module>
     48 
     49 # initialize Tacotron2 with the pretrained model
---> 50 hparams = create_hparams()

[/content/tacotron2/hparams.py](https://localhost:8080/#) in create_hparams(hparams_string, verbose)
      6     """Create model hyperparameters. Parse nondefault from given string."""
      7 
----> 8     hparams = tf.contrib.training.HParams(
      9         ################################
     10         # Experiment Parameters        #

AttributeError: module 'tensorflow' has no attribute 'contrib'

**Comment by tilakrayal** [comment]
@Colabnoob,
`tf.contrib.layers` was deprecated and replaced with [**TF Slim**](https://github.com/google-research/tf-slim) symbols. **tf.contrib** was available on tensorflow 1.x version which was not supported. 
Please take a look at this [guide](https://www.tensorflow.org/guide/migrate) to migrate your code from TensorFlow `1.x to 2.x` and check upgrade to 2.x version. Thank you!

**Comment by Colabnoob** [comment]
Thanks I used the command tf_slim and i have a new error, i did replace tf_slim with tf.contrib just to clarify.
/usr/local/lib/python3.8/dist-packages/gdown/cli.py:121: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1E12g_sREdcH5vuZb44EZYX8JjGWQ9rRp
To: /content/merged.dict.txt
100% 7.94M/7.94M [00:00<00:00, 145MB/s]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-5-da68ef597068>](https://localhost:8080/#) in <module>
     48 
     49 # initialize Tacotron2 with the pretrained model
---> 50 hparams = create_hparams()
     51 get_ipython().system('tf_upgrade_v2    --intree my_project/    --outtree my_project_v2/    --reportfile report.txt')

[/content/tacotron2/hparams.py](https://localhost:8080/#) in create_hparams(hparams_string, verbose)
      6     """Create model hyperparameters. Parse nondefault from given string."""
      7 
----> 8     hparams = tf.slim.layers.training.HParams(
      9         ################################
     10         # Experiment Parameters        #

AttributeError: module 'tensorflow' has no attribute 'slim'

**Comment by tilakrayal** [comment]
@Colabnoob,
The code provided was feasible with tensorflow v1.x which is not supported. Could you please change the code to tensorflow v2.x and check if you are facing the same issue. Thank you!
