### ISSUE TITLE
"Prelu" in Tensorflow lite with the Hexagon Delegate not supported

### ISSUE THREAD

**Issue by kys9503001** [tensorflow/tensorflow#59030]
Hello,

When using a 8-bits quantized tflite model with "Prelu", It was not running successfully.
It seems to be caused by Prelu not supporting it by TfLiteHexagonDelegate.
(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/hexagon/README.md ).
Prelu is supported ops from Hexagon nnlib, but is not supported Tensorflow lite with the Hexagon Delegate.( https://source.codeaurora.org/quic/hexagon_nn/nnlib/tree/docs/ops.txt ).  

If there is a plan to support "prelu" in TfLiteHexagonDelegate,
Could you shared the schedule?

**Comment by kys9503001** [comment]
@ sirakiin 
If you have update there, Could you share me.
Thank you!

**Comment by sirakiin** [comment]
Hi @kys9503001 ,

Thanks for reaching out! Currently we don't have schedule to introduce more ops to hexagon delegate, but it's definitely welcomed if you want to contribute! It will be fairly similar to [this commit](https://github.com/tensorflow/tensorflow/commit/6fc4559676b705de69db973f52e8bf99ecec93ec). Let me know if you are interested and I can share more details.

Thanks!

**Comment by pkgoogle** [comment]
Hi @kys9503001, does the above PR fix your issue?

**Comment by kys9503001** [comment]
>  above PR is helped me al lot.
