### ISSUE TITLE
Can't build tensorflow lite 2.10.0

### ISSUE THREAD

**Issue by kventinel** [tensorflow/tensorflow#59032]
I try to cross-build tensorflow 2.10 to arm32 arch, but get next error:

```
#0 150.8 /tflite-vx-delegate/build/xnnpack/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c: In function 'xnn_qs8_vcvt_ukernel__armv6simd_x8':
#0 150.8 /tflite-vx-delegate/build/xnnpack/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:26:9: error: unknown type name 'int16x2_t'
#0 150.8    const int16x2_t vminus_input_zero_point = (int16x2_t) params->armv6simd.minus_input_zero_point;
```

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.10

### Custom Code

No

### Current Behaviour?

```shell
I try to cross-build tensorflow 2.10 to arm32 arch, but get next error:

#0 150.8 /tflite-vx-delegate/build/xnnpack/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c: In function 'xnn_qs8_vcvt_ukernel__armv6simd_x8':
#0 150.8 /tflite-vx-delegate/build/xnnpack/src/qs8-vcvt/gen/vcvt-armv6simd-x8.c:26:9: error: unknown type name 'int16x2_t'
#0 150.8    const int16x2_t vminus_input_zero_point = (int16x2_t) params->armv6simd.minus_input_zero_point;
```
```


### Standalone code to reproduce the issue

```shell
-
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@kventinel,
Have you got the chance to have a look at this [comment](https://github.com/tensorflow/tensorflow/issues/57364#issuecomment-1234226962) from the contributor and also mentioned that the #https://github.com/tensorflow/tensorflow/pull/57585 was raised for the same. Also please refer to this [comment](https://github.com/tensorflow/tensorflow/issues/57097#issuecomment-1214783498) from the issue. Thank you!

**Comment by renanwille** [comment]
Hi @tilakrayal I was looking into doing the same thing and ended up with the same errors reported by this issue. Maybe the documentation here:
https://www.tensorflow.org/lite/guide/build_cmake_arm#build_for_armv7_neon_enabled
Should be updated to this new compiler.
