### ISSUE TITLE
Training horizontally stacked layers does not happen in parallel

### ISSUE THREAD

**Issue by carlosg-m** [tensorflow/tensorflow#59049]
### Issue Type

Bug

### Source

source

### Tensorflow Version

2.7.0

### Custom Code

Yes

### Current Behaviour?

When using Keras to build a multiple layer model, by stacking layers horizontally instead of vertically (deep network), training happens sequentially, and adding more layers increases each epoch duration linearly, while GPU utilization and memory usage remains the same as a single layer regardless of the number of total layers.

### Standalone code to reproduce the issue

In the example below I would expect that each sub-network called though the `cnn_example()` function, would run in parallel before the `GlobalAveragePooling1D` operation is called. However this does not happen, regardless the number of times the layer is repeated. Is this expected behavior or am I missing something?
```
import tensorflow as tf
from tensorflow.keras import layers

input_img= layers.Input(shape=(112, 112, 3))

x = [cnn_example()(input_img) for _ in range(n_repeats)]
x = layers.Lambda(lambda x: tf.stack(x, axis=1))(x)
x = layers.GlobalAveragePooling1D()(x)
x = layers.Dense(1)(x)

model = tf.keras.Model(input_img, x)
```

**Comment by tiruk007** [comment]
@carlosg-m 
I tried to reproduce the issue on Colab using TF v2.11 but faced a different error. Could you please find the gist [here](https://colab.research.google.com/gist/tiruk007/972580d2556cdd5b0a472239477d46da/untitled59.ipynb) for reference and provide complete code or colab gist to replicate the issue reported here.

Thank you!

**Comment by carlosg-m** [comment]
@tiruk007, sorry about that, I was hoping it would be enough. Anyway, I followed your template and created a Colab notebook, with a complete reproducible example:
 - https://colab.research.google.com/drive/11jtCBrwWqDYbdsuMu04ptRfFXi0sr1EV?usp=sharing

The notebook was running on a GPU with small batch sizes of 32 to keep resource usage low, so when the number of stacked layers increases, there are free resources to allocate, assuming a quasi-parallel execution. However once again that was not the case:
 - 1 model: ~5 seconds epoch
 - 2 models: ~10 seconds epoch
 - 3 models: ~15 seconds epoch

**Comment by tiruk007** [comment]
@carlosg-m 
This issue seems to be a keras related issue. Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999.

Thank you!
