### ISSUE TITLE
Overflow error when running depthwise_conv2d_native_backprop_filter

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59059]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.4

### Python version

3.8

### CUDA/cuDNN version

nvcc: NVIDIA (R) Cuda compiler driver Copyright (c) 2005-2021 NVIDIA Corporation Built on Sun_Feb_14_21:12:58_PST_2021 Cuda compilation tools, release 11.2, V11.2.152 Build cuda_11.2.r11.2/compiler.29618528_0

### Current Behaviour?

```shell
If depthwise_conv2d_native_backprop_filter is given very large tensor, it results overflow error. I encountered this error when running the code in colab.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_nn_ops
try:
  arg_0_tensor = tf.random.uniform([4, 5, 5, 48], dtype=tf.float32)
  arg_0 = tf.identity(arg_0_tensor)
  arg_1_tensor = tf.random.uniform([4], dtype=tf.int32, maxval=1879048192)
  arg_1 = tf.identity(arg_1_tensor)
  arg_2_tensor = tf.random.uniform([4, 5, 5, 96], dtype=tf.float32)
  arg_2 = tf.identity(arg_2_tensor)
  arg_3_0 = 1
  arg_3_1 = 1
  arg_3_2 = 1
  arg_3_3 = 1
  arg_3 = [arg_3_0,arg_3_1,arg_3_2,arg_3_3,]
  arg_4 = "SAME"
  explicit_paddings = []
  data_format = "NHWC"
  dilations_0 = 1
  dilations_1 = 1
  dilations_2 = 1
  dilations_3 = 1
  dilations = [dilations_0,dilations_1,dilations_2,dilations_3,]
  out = gen_nn_ops.depthwise_conv2d_native_backprop_filter(arg_0,arg_1,arg_2,arg_3,arg_4,explicit_paddings=explicit_paddings,data_format=data_format,dilations=dilations,)
except Exception as e:
  print("Error:"+str(e))
```
```

```shell
Error:{{function_node __wrapped__DepthwiseConv2dNativeBackpropFilter_device_/job:localhost/replica:0/task:0/device:CPU:0}} Encountered overflow when multiplying 485389066749118952 with 692120327, result: -1 [Op:DepthwiseConv2dNativeBackpropFilter]
```
</details>

**Comment by tilakrayal** [comment]
@SuryanarayanaY,
I was able to reproduce the issue on tensorflow v2.9, v2.11 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/1e95c7dbb315c184d0c062877310e198/untitled826.ipynb).

**Comment by SuryanarayanaY** [comment]
Hi @nimashiri ,
The error might be due to the larger Tensors which can't be handled by the Available Memory. Could you please try with lower size inputs and let us know the results.I tried with lower size and got different error.Then I have changed the arguments as per [API](https://www.tensorflow.org/api_docs/python/tf/raw_ops/DepthwiseConv2dNativeBackpropFilter) and with smaller Tensor it works fine as per attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/21697c483baa0fa385e26eec68834636/59059.ipynb) here.

Thank you!

**Comment by nimashiri** [comment]
> 

Agree. The lower size works fine. So, the error is expected with larger size tensors? Proper exception handling is not required? for example [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/nn_ops.cc), 

```
REGISTER_OP("DepthwiseConv2dNativeBackpropFilter")
    .Input("input: T")
    .Input("filter_sizes: int32")
    .Input("out_backprop: T")
    .Output("output: T")
    .Attr("T: {half, bfloat16, float, double}")
    .Attr("strides: list(int)")
    .Attr(GetPaddingAttrStringWithExplicit())
    .Attr(GetExplicitPaddingsAttrString())
    .Attr(GetConvnetDataFormatAttrString())
    .Attr("dilations: list(int) = [1, 1, 1, 1]")
    .SetShapeFn([](InferenceContext* c) {
      ShapeHandle s;
      TF_RETURN_IF_ERROR(c->MakeShapeFromShapeTensor(1, &s));
      TF_RETURN_IF_ERROR(c->WithRank(s, 4, &s));
      c->set_output(0, s);
      return OkStatus();
    });
```

**Comment by mihaimaruseac** [comment]
Nope, the overflow is an issue but @SuryanarayanaY gave a wrong answer.

**Comment by mihaimaruseac** [comment]
@learning-to-play

**Comment by sachinprasadhs** [comment]
This is working as intended, Error message being returned as expected, when the tensor size computation in the kernel implementation would lead to an overflow: and is handled in the code below.
https://github.com/tensorflow/tensorflow/blob/48d3e51a1bd128554dd129251a51b6e12918a604/tensorflow/core/kernels/depthwise_conv_grad_op.cc#L1133-L1134

Also, refer the security vulnerability mentioned in the security advisory here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/security/advisory/tfsa-2021-024.md

**Comment by sachinprasadhs** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
