### ISSUE TITLE
StaticHashTable does not support complex values

### ISSUE THREAD

**Issue by SRaent** [tensorflow/tensorflow#59052]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.8

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.10

### Current Behaviour?

```shell
When using a `tf.lookup.KeyValueTensorInitializer` where the `values` argument is a `tf.constant` of datatype `tf.complex64` or `tf.complex128` is passed to a `tf.lookup.StaticHashTable` as the `initializer` argument, an error is thrown
```

### Standalone code to reproduce the issue

```shell
init = tf.lookup.KeyValueTensorInitializer(
                keys=tf.constant(["a","b"]),
                values=tf.constant([1.0,2.0],dtype=tf.complex128))

Table = tf.lookup.StaticHashTable(
                initializer=init,
                default_value=-1)
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@SuryanarayanaY 
I was able to reproduce the issue on Colab using TF v2.11. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/cbb9d02c37e10fde59a1dd7ff009cc7c/untitled60.ipynb) for reference.

Thank you!

**Comment by utkarsh172** [comment]
@SRaent 
I was able to solve this issue on Colab using TF v2.11. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/cbb9d02c37e10fde59a1dd7ff009cc7c/untitled60.ipynb#scrollTo=Pyq9OvA9Kb1X) for reference

**Comment by SuryanarayanaY** [comment]
Hi @SRaent ,
As the error log itself indicates that  `complex dtypes` seems not supported on this Op `tf.lookup.StaticHashTable`.
```
NotFoundError: Could not find device for node: {{node HashTableV2}} = HashTableV2[container="", key_dtype=DT_STRING, shared_name="9", use_node_name_sharing=false, value_dtype=DT_COMPLEX128]
All kernels registered for op HashTableV2:
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_STRING]
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_INT64]
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_INT32]
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_FLOAT]
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_DOUBLE]
  device='CPU'; key_dtype in [DT_STRING]; value_dtype in [DT_BOOL]
  device='CPU'; key_dtype in [DT_INT64]; value_dtype in [DT_STRING]
  device='CPU'; key_dtype in [DT_INT64]; value_dtype in [DT_INT64]
  device='CPU'; key_dtype in [DT_INT64]; value_dtype in [DT_INT32]
  device='CPU'; key_dtype in [DT_INT64]; value_dtype in [DT_FLOAT]
  device='CPU'; key_dtype in [DT_INT64]; value_dtype in [DT_DOUBLE]
  device='CPU'; key_dtype in [DT_INT32]; value_dtype in [DT_STRING]
  device='CPU'; key_dtype in [DT_INT32]; value_dtype in [DT_INT32]
  device='CPU'; key_dtype in [DT_INT32]; value_dtype in [DT_FLOAT]
  device='CPU'; key_dtype in [DT_INT32]; value_dtype in [DT_DOUBLE]
 [Op:HashTableV2] name: hash_table
```
From the Op [API ](https://www.tensorflow.org/api_docs/python/tf/lookup/StaticHashTable#args),the argument `initializer` the dtypes should be of same as HashTable





Args
--
initializer | The table initializer to use. See HashTable kernel for supported key and value types.

@utkarsh172 , Would like to know your workaround but the attached gist is not accessible to me.Please share it as github gist.

Thank you!
