### ISSUE TITLE
Feature request for object detection android app

### ISSUE THREAD

**Issue by HripsimeS** [tensorflow/tensorflow#59051]
Hello,

I deployed my Mobilenet trained model into your object detection android app and the detection looks good.
https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android

I would like to add two features to your app if possible:
1) Show on the phone screen number of detected objects of class X
2) Show on the phone screen the (x, y) coordinated of bounding box for detected objects of class X

Can you please help me to figure out how I can add these two features in the app. Look forward to hearing from you!

**Comment by HripsimeS** [comment]
@tilakrayal @tiruk007 Hello. Any ideas how to progress with these two features I mentioned above?

**Comment by HripsimeS** [comment]
@tiruk007 thanks for your reply. Indeed the object detection android app works good, I tested on my custom model also.
I need your help for the following features that would be possible to integrate in the app. 

1) How is possible to add a choice "Class" below Delegate or ML model and chose a class let's say "person"
2) Show on the screen number of detected objects of class "person"
3) And show on the screen (x, y) coordinates of bounding box for detected objects of class "person"

Look forward to hearing from you!

**Comment by tiruk007** [comment]
@mohantym 
Could you please look into this ?
Thank you!

**Comment by HripsimeS** [comment]
@mohantym can you please take a look to my previous message and let me know if you have an idea about solutions.

**Comment by HripsimeS** [comment]
@sirakiin can you please take a look to my previous message and let me know if you have an idea about solutions.

**Comment by mohantym** [comment]
@HripsimeS !
Thanks for sharing your observations.
Regarding no of detected objects.  

Can you check categories.size parameter and let us know. 
[Ref](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/app/src/androidTest/java/org/tensorflow/lite/examples/objectdetection/TFObjectDetectionTest.kt#:~:text=results%5Bi%5D.categories.size).

It would be awesome see a PR coming (from yourside) for review if it succeeds.

Thank you!

**Comment by HripsimeS** [comment]
@mohantym thanks for your advice. I share below code that shows the number of detected objects for class person.

var i = 0;
        activity?.runOnUiThread {
            var i = 0;
            if(results != null){

                for(item in results){
                    for(category in item.categories){
                        if(category.label == "person"){
                            i++;
                        }
                    }
                }
            }

**Comment by HripsimeS** [comment]
@mohantym Hello. I would like to add a new feature for object detection that allows to track the detected objects. For example, it detects class person and write on the screen (person #1, person #2, person #3, etc). 
Do you have an idea how to make a kind of numerical tracking of each detected object of class "person" ? Thanks in advance!

**Comment by pkgoogle** [comment]
Hi @HripsimeS, this repo is mainly focused on tensorflow and for this part the tensorflow lite frameworks, as such feature requests are meant to be about improving/extending the frameworks. The examples are meant to be simple examples on how to use the tflite framework. As such, supporting what you want to do is out of the scope for this repo. Feel free to copy the example and continue your work, if you want to submit a PR to improve the example, you may also do so. If you have no other open items, please feel free to close the issue as not planned.
