### ISSUE TITLE
tf.image.extract_patches fails with XLA, float32 input and message about int64 input

### ISSUE THREAD

**Issue by shkarupa-alex** [tensorflow/tensorflow#59061]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

2.11

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04, Mac OS X 12.6

### Python version

3.8

### Current Behaviour?

```shell
In some cases (see link below) tf.image.extract_patches with float32 input and enabled XLA says that forward pass OP requested INT64 dtype which is not registered.
But input dtype is float32...
```

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1WJwcmUZMlqQYSz_xwQ6I_5vlnlEmfkp3?usp=sharing
```

### Relevant log output

```shell
Detected unsupported operations when trying to compile graph __inference_run_step_3512[] on XLA_GPU_JIT: ExtractImagePatches (No registered 'ExtractImagePatches' OpKernel for XLA_GPU_JIT devices compatible with node {{node gradient_tape/model_2/temp_2/ExtractImagePatches}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_INT64, ksizes=[1, 16, 16, 1], padding="SAME", rates=[1, 1, 1, 1], strides=[1, 8, 8, 1]){{node gradient_tape/model_2/temp_2/ExtractImagePatches}}
```
</details>

**Comment by tiruk007** [comment]
@sushreebarsa 
I was able to reproduce the issue on colab using TF v2.11. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/37110f6bf5abebad99b2b1588945e570/untitled63.ipynb) for reference.
Thank you !

**Comment by tilakrayal** [comment]
@shkarupa-alex,
I tried to execute the mentioned code on  both GPU and CPU with the tensorflow [v2.14](https://colab.research.google.com/gist/tilakrayal/51c06a861dbfcef49c65a1f54c4aebde/untitled1399.ipynb) & tf-nightly and it was executed without any issue/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/97946ce2d3dc54b65278b7ab67906136/untitled1399.ipynb). Thank you!

**Comment by shkarupa-alex** [comment]
This issue was fixed with https://github.com/tensorflow/tensorflow/pull/59185
