### ISSUE TITLE
the evaluation section pop out error #1

### ISSUE THREAD

**Issue by sarataylor2000** [tensorflow/tensorflow#59062]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

linux

### Current Behaviour?

```shell
hi,
im using a notebook from this github repository:
https://github.com/flogothetis/Abstractive-Summarization-T5-Keras

notebook link:
https://github.com/flogothetis/Abstractive-Summarization-T5-Keras/blob/main/AbstractiveSummarizationT5.ipynb

thanks so much to tensorflow algorithm it works much faster than pytorch and fine but after train in the last section

getSummary("With your permission we and our partners may use precise geolocation
data and identification through device scanning. You may click to consent to our
and our partners’ processing as described above. Alternatively you may access more
detailed information and change your preferences before consenting or to refuse consenting.")

pop out an error and can not generate the result,
Error:
ValueError: Input 2 is incompatible with layer model_2: expected shape=(None, 50), found shape=(None, 51)

so is there any solution for?
Much obliged

full error:

ValueError: in user code:

/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:1478 predict_function  *
    return step_function(self, iterator)
/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:1468 step_function  **
    outputs = model.distribute_strategy.run(run_step, args=(data,))
/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/tpu_strategy.py:540 run
    return self.extended.tpu_run(fn, args, kwargs, options)
/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/tpu_strategy.py:1296 tpu_run
    return func(args, kwargs)
/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/tpu_strategy.py:1364 tpu_function
    xla_options=tpu.XLAOptions(use_spmd_for_xla_partitioning=False))
/opt/conda/lib/python3.7/site-packages/tensorflow/python/tpu/tpu.py:968 replicate
    xla_options=xla_options)[1]
/opt/conda/lib/python3.7/site-packages/tensorflow/python/tpu/tpu.py:1439 split_compile_and_replicate
    outputs = computation(*computation_inputs)
/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/tpu_strategy.py:1325 replicated_fn
    result[0] = fn(*replica_args, **replica_kwargs)
/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:1461 run_step  **
    outputs = model.predict_step(data)
/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:1434 predict_step
    return self(x, training=False)
/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:998 __call__
    input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/input_spec.py:274 assert_input_compatibility
    ', found shape=' + display_shape(x.shape))

**ValueError: Input 2 is incompatible with layer model_2: expected shape=(None, 50), found shape=(None, 51)**
```

### Standalone code to reproduce the issue

```shell
by running this code bug triggers:

getSummary("With your permission we and our partners may use precise geolocation
data and identification through device scanning. You may click to consent to our
and our partners’ processing as described above. Alternatively you may access more
detailed information and change your preferences before consenting or to refuse consenting.")
```

### Relevant log output

_No response_</details>

**Comment by rajivhockey97** [comment]
In the getSummary function, for decoder_inputs_ids and decoder_attention_mask the maxlen must be max_len_sum-1. It works fine once this change is made.

**Comment by mohantym** [comment]
Hi @sarataylor2000 !

Would it be possible to provide a gist. I am facing package conflicts in [Colab](https://colab.sandbox.google.com/gist/mohantym/b7fd55358f9fd27a5c16226500d22662/abstractivesummarizationt5.ipynb#scrollTo=9ekCFXqG6hBT) here. 
Have you checked above [suggestion](https://github.com/tensorflow/tensorflow/issues/59062#issuecomment-1368703849) yet. 

Thank you!

**Comment by sarataylor2000** [comment]
> In the getSummary function, for decoder_inputs_ids and decoder_attention_mask the maxlen must be max_len_sum-1. It works fine once this change is made.

you are amazing! i did what you had told me and it works fine now.

I just have a problem, i wanna run the saved model and run that with generate function of hugging face, the generate 
functions gives this opportunity to use **num_return_sequences and max_len** of generated output

it's the code i use to run saved model with generate() hugging face but it returns trash reply and not a true response!
I.e for summerizing this below text:

getSummary("With your permission we and our partners may use precise geolocation\
  data and identification through device scanning. You may click to consent to our\
  and our partners’ processing as described above. Alternatively you may access more\
   detailed information and change your preferences before consenting or to refuse consenting.")
the getSummary returns something like this:
**We may use geolocation data through device scanning**

but when i use the generate function of hugging face, the code is as below:

**text='''With your permission we and our partners may use precise geolocation
  data and identification through device scanning. You may click to consent to our
  and our partners’ processing as described above. Alternatively you may access more
   detailed information and change your preferences before consenting or to refuse consenting.'''**

tokenizer = T5Tokenizer.from_pretrained('t5-small')
model0 = TFT5ForConditionalGeneration.from_pretrained(to_directory)
inputs = tokenizer([text], return_tensors="tf")
generated = model0.generate(**inputs,decoder_start_token_id=tokenizer.pad_token_id,do_sample=True)

print("Sampling output: ", tokenizer.decode(generated[i]))

# the output is trash like this:
_**_Sampling output:  <pad> kurz Upholster Month citoyenjohnpointviousgren suppression awful Tommy Partners animaux Certain temptationanischadenCenterani FUN awful partager Lexington Üb_**_ 

it generate output but output is trash and no mean!
 if i tray model.generate() without this **decoder_start_token_id=tokenizer.pad_token_id**

generated = model.generate(**inputs,do_sample=True)

it reurns an error as:
decoder_start_token_id or bos_token_id has to be defined for encoder-decoder generation

is there any solotion to lead model.generate() return true reply?

by the way start and end tokens are as below;

print(end_token,tokenizer.eos_token_id)#</s> 1
print(start_token,tokenizer.pad_token_id)#</s> 1

any solutions?
much obliged

**Comment by rajivhockey97** [comment]
@sarataylor2000 Could you provide the pretrained model for the generate task?

**Comment by sarataylor2000** [comment]
> @sarataylor2000 I tried to replicate the generate function and i get meaningful results. Could you provide a gist of your error ?

**Comment by sarataylor2000** [comment]
> @sarataylor2000 I tried to replicate the generate function and i get meaningful results. Could you provide a gist of your error ?

after train model i saved model and save in google drive here is the link:
https://drive.google.com/file/d/1TEFGETISBsbJsKcMGwYzFUcnCjAkPc5-/view
here is my approch:
after tarin i save model it contains:
assets, variables, and saved_model.pb
for executing hugging face generate function it needs config file but model.save() dose not make a config file, so i create a wights.h5 file and then convert it to json it crate a folderthat has multipe .bin file and a config file. 
till now i make any file need to execute the generate() function, 

below is my generate function

text='''With your permission we and our partners may use precise geolocation
data and identification through device scanning. You may click to consent to our
and our partners’ processing as described above. Alternatively you may access more
detailed information and change your preferences before consenting or to refuse consenting.'''

#folder of model=folder contain model i share on google drive and send the link
tokenizer = T5Tokenizer.from_pretrained('t5-small')
model0 = TFT5ForConditionalGeneration.from_pretrained('folder of model')
inputs = tokenizer([text], return_tensors="tf")
generated = model0.generate(**inputs,decoder_start_token_id=tokenizer.pad_token_id,do_sample=True)

print("Sampling output: ", tokenizer.decode(generated[0]))](url)

it runs but make words that doesn't mean :+1: 
like:  **kurz Upholster Month citoyenjohnpointviousgren suppression awful Tommy Partners animaux Certain temptationanischadenCenterani FUN** totally no mean

the getSummary() funnction  in the notebook returns something as below as summary:
**We may use geolocation data through device scanning**

as you said your generate() hugging face function make meaningful results, what is your generate() function how is its structure?
or i did something wrong in the saving model approach? 
**what's the right approach that works for this notebook?**
 
thanks
