### ISSUE TITLE
TypeError: can't pickle weakref objects

### ISSUE THREAD

**Issue by NoteDancing** [tensorflow/tensorflow#59075]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Windows 11

### Python version

3.7

### Current Behaviour?

```shell
TypeError: can't pickle weakref objects
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import pickle
output_file=open('save.dat','wb')
pickle.dump(tf.keras.optimizers.Adam(),output_file)
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@NoteDancing 
Could you please refer to the similar [issue_1](https://github.com/tensorflow/tensorflow/issues/34697) & [issue_2](https://github.com/tensorflow/tensorflow/issues/56967) and find the workaround [here](https://colab.research.google.com/gist/tiruk007/83171c276a4b7ba21eb5496d79bead3e/untitled65.ipynb) and let us know if it helps ?

Thank you!

**Comment by NoteDancing** [comment]
> @NoteDancing Could you please refer to the similar [issue_1](https://github.com/tensorflow/tensorflow/issues/34697) & [issue_2](https://github.com/tensorflow/tensorflow/issues/56967) and find the workaround [here](https://colab.research.google.com/gist/tiruk007/83171c276a4b7ba21eb5496d79bead3e/untitled65.ipynb) and let us know if it helps ?
> 
> Thank you!

Whether the optimizer cannot be pickled？

**Comment by SuryanarayanaY** [comment]
@NoteDancing ,
Please find the workaround to serialize the Optimizer using Pickle [here](https://colab.research.google.com/gist/SuryanarayanaY/20d141683680324d064256a6197b4f64/59075_r1.ipynb).

Please let us know if proposed solution won't work for you.

Thankyou!

**Comment by NoteDancing** [comment]
> @NoteDancing , Please find the workaround to serialize the Optimizer using Pickle [here](https://colab.research.google.com/gist/SuryanarayanaY/20d141683680324d064256a6197b4f64/59075_r1.ipynb).
> 
> Please let us know if proposed solution won't work for you.
> 
> Thankyou!

Is there a way to serialize optimizer instead of opt_config like tensorflow version 2.0.
Thankyou!

**Comment by SuryanarayanaY** [comment]
@NoteDancing , We have tf.keras.optimizers.serialize() API which will convert the optimizer to JSON form.Please find attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/0a612ba3ebc7c3e2bff7fd5cd5b4ba81/59075-testing.ipynb#scrollTo=m0NDS7KgwMog) here.Hope it will solve your purpose.Thanks!

**Comment by NoteDancing** [comment]
> @NoteDancing , We have tf.keras.optimizers.serialize() API which will convert the optimizer to JSON form.Please find attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/0a612ba3ebc7c3e2bff7fd5cd5b4ba81/59075-testing.ipynb#scrollTo=m0NDS7KgwMog) here.Hope it will solve your purpose.Thanks!

How can I restore optimizer from opt_serialized?Thankyou!

**Comment by SuryanarayanaY** [comment]
For restoring the `opt_serialized` TF have [tf.keras.optimizers.deserialize](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/deserialize?version=nightly) API.We can do it like below.

`opt_restored = tf.keras.optimizers.deserialize(opt_serialized)
`

**Comment by NoteDancing** [comment]
@SuryanarayanaY Thank you for your answer.
