### ISSUE TITLE
tflite_model_maker-0.4.2 - Getting nightly for ever

### ISSUE THREAD

**Issue by RonaldoSCouto** [tensorflow/tensorflow#59077]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

tflite_model_maker-0.4.2

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 22.04.1 LTS and Windows 10 (21H1)

### Python version

3.10

### Current Behaviour?

```shell
In Ubuntu and Windows same situation:
COMMAND:
    pip install tflite-model-maker    (as https://pypi.org/project/tflite-model-maker/)

OUTPUT:
    Download, build and install several dependencies, without problem or error.
    Collecting pycocotools>=2.0.2
    Downloading pycocotools-2.0.6.tar.gz (24 kB)
    Installing build dependencies ... done
    Getting requirements to build wheel ... done
    Preparing metadata (pyproject.toml) ... done
    Collecting tflite-model-maker    (<=== DOWNLOADING OLD VERSION ?)
    Downloading tflite_model_maker-0.2.4-py3-none-any.whl (190 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.1/190.1 KB 41.0 MB/s eta 0:00:00
    Downloading tflite_model_maker-0.2.3-py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 KB 28.1 MB/s eta 0:00:00
    Downloading tflite_model_maker-0.2.2-py3-none-any.whl (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.3/103.3 KB 36.0 MB/s eta 0:00:00
    Downloading tflite_model_maker-0.2.1-py3-none-any.whl (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.9/102.9 KB 33.6 MB/s eta 0:00:00
    Downloading tflite_model_maker-0.2.0-py3-none-any.whl (102 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.6/102.6 KB 33.3 MB/s eta 0:00:00
    Downloading tflite_model_maker-0.1.2-py3-none-any.whl (104 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.1/104.1 KB 36.7 MB/s eta 0:00:00

   Collecting tf-nightly
    Downloading tf_nightly-2.12.0.dev20230103-cp310-cp310- 
    manylinux_2_17_x86_64.manylinux2014_x86_64.whl (563.8 MB)
    ...
    Still downloading tf_nightly versions, for ever. I had canceled after 2 months of tf_nightly.

I HAD TRY:
   1) Install Windows e Ubuntu.
   2) Remove all pip package e install minimum necessary
   3) Try on python virtual enviroment
```

### Standalone code to reproduce the issue

```shell
pip install tflite-model-maker
```

### Relevant log output

_No response_</details>

**Comment by RonaldoSCouto** [comment]
Same situation on Jupyter Notebook.

Requirement already satisfied: termcolor in /home/casa/.local/lib/python3.10/site-packages (from tensorflow-datasets>=2.1.0->tflite-model-maker) (2.2.0)
Collecting etils[enp,epath]>=0.9.0
  Using cached etils-0.9.0-py3-none-any.whl (140 kB)
Requirement already satisfied: psutil in /home/casa/.local/lib/python3.10/site-packages (from tensorflow-datasets>=2.1.0->tflite-model-maker) (5.9.4)
Requirement already satisfied: requests>=2.19.0 in /usr/lib/python3/dist-packages (from tensorflow-datasets>=2.1.0->tflite-model-maker) (2.25.1)
Collecting tensorflow-metadata
  Using cached tensorflow_metadata-1.12.0-py3-none-any.whl (52 kB)
Collecting tqdm
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: protobuf>=3.12.2 in /usr/lib/python3/dist-packages (from tensorflow-datasets>=2.1.0->tflite-model-maker) (3.12.4)
Collecting dill
  Using cached dill-0.3.6-py3-none-any.whl (110 kB)
Collecting opencv-python-headless
  Using cached opencv_python_headless-4.7.0.68-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (49.2 MB)
Collecting pycocotools
  Using cached pycocotools-2.0.6.tar.gz (24 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting gin-config
  Using cached gin_config-0.5.0-py3-none-any.whl (61 kB)
Collecting immutabledict
  Using cached immutabledict-2.2.3-py3-none-any.whl (4.0 kB)
Collecting oauth2client
  Using cached oauth2client-4.1.3-py2.py3-none-any.whl (98 kB)
Collecting google-api-python-client>=1.6.7
  Using cached google_api_python_client-2.70.0-py2.py3-none-any.whl (10.7 MB)
Collecting py-cpuinfo>=3.3.0
  Using cached py_cpuinfo-9.0.0-py3-none-any.whl (22 kB)
Collecting pandas>=0.22.0
  Using cached pandas-1.5.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
Collecting tf-slim>=1.1.0
  Using cached tf_slim-1.1.0-py2.py3-none-any.whl (352 kB)
Collecting kaggle>=1.3.9
  Using cached kaggle-1.5.12.tar.gz (58 kB)
  Preparing metadata (setup.py) ... done
Collecting tensorflow-text-nightly
  Using cached tensorflow_text_nightly-2.12.0.dev20230103-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.9 MB)
Collecting sacrebleu
  Using cached sacrebleu-2.3.1-py3-none-any.whl (118 kB)
Collecting scipy>=0.19.1
  Using cached scipy-1.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.7 MB)
Collecting seqeval
  Using cached seqeval-1.2.2.tar.gz (43 kB)
  Preparing metadata (setup.py) ... done
Collecting tf-estimator-nightly~=2.12.0.dev
  Using cached tf_estimator_nightly-2.12.0.dev2023010309-py2.py3-none-any.whl (439 kB)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /home/casa/.local/lib/python3.10/site-packages (from tf-nightly->tflite-model-maker) (0.4.0)
Requirement already satisfied: packaging in /home/casa/.local/lib/python3.10/site-packages (from tf-nightly->tflite-model-maker) (22.0)
Collecting tf-nightly
  Using cached tf_nightly-2.12.0.dev20230102-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (563.8 MB)
  Using cached tf_nightly-2.12.0.dev20230101-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (563.8 MB)
  Downloading tf_nightly-2.12.0.dev20221231-cp310-cp3

**Comment by mohantym** [comment]
Hi @RonaldoSCouto !

Thanks for sharing your observations on lite-model-maker-0.4.2 .
Could you upgrade your pip version to latest version  and let us know know.
[Ref .](https://discuss.tensorflow.org/t/tflite-model-maker-0-4-2-installation-ubuntu-and-windows-10/13943/3?u=manas_mohanty)

Thank you!

**Comment by RonaldoSCouto** [comment]
Hi,
I update from pip 22.0.2 to pip 22.3.1, purge pip cache and ran again.
I had stopped installation on tf_nightly-2.12.0.dev20221229  (7 days).
Nothing changed. Same situation. Looking for tf_nightly.

**Comment by mohantym** [comment]
@RonaldoSCouto !
Could you share your thoughts here #53550 as Re-opening this issue will be a duplicate effort.
Thank you!

**Comment by mohantym** [comment]
@RonaldoSCouto !
Re-opening as instructed.  Normally, these issue gets resolved if the requirement in lite_model_maker are followed. we will give you an update once it is tested in windows.
[Ref](https://github.com/tensorflow/tensorflow/issues/53550#issuecomment-1405460938)
Thank you!

**Comment by sachinprasadhs** [comment]
I tried to reproduce the issue with the colab(Ubuntu OS) but I was able to install successfully without any issues. 
Here is the [Gist](https://colab.sandbox.google.com/gist/sachinprasadhs/5cc92449cad1a29e3c67a02a60a182fc/59077.ipynb) with all the installed files. 

Could you check if you have required permissions to install packages in your system, also can you let us know if you have  successfully  installed any other packages in your env like tf-nightly.

`sudo pip install tflite-model-maker`, if you want to install the package across the system.

or 

`pip install tflite-model-maker --user`,  if you want to install specific to user or env.

**Comment by pozil** [comment]
Hi, I'm facing the same issue: `pip install tflite-model-maker` is fetching nightly builds non-stop.

macOS Ventura 13.1.
pip 23.0 running on python 3.10
I'm using venv for the install (I don't want to use a global install)

**Comment by pozil** [comment]
I was able to install by downgrading to Python 3.9
