### ISSUE TITLE
Crash when running tensorflow.python.ops.gen_nn_ops.max_pool_grad_with_argmax

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59083]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

Yes

### Mobile device

22.04

### Python version

3.9

### CUDA/cuDNN version

Cuda compilation tools, release 11.5, V11.5.119

### Current Behaviour?

```shell
When .max_pool_grad_with_argmax is given negative integer tensor, it crashes.
```

### Standalone code to reproduce the issue

```
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import gen_nn_ops
try:
  try:
    with tf.device('/CPU'):
      arg_0_tensor = tf.constant(-105687333925307, shape=[2, 3, 3, 1], dtype=tf.float32,)
      arg_0 = tf.identity(arg_0_tensor)
      arg_1_tensor = tf.random.uniform([2, 2, 2, 1], dtype=tf.float32)
      arg_1 = tf.identity(arg_1_tensor)
      arg_2_tensor = tf.random.uniform([2, 2, 2, 1], minval=-256, maxval=257, dtype=tf.int64)
      arg_2 = tf.identity(arg_2_tensor)
      ksize_0 = 1
      ksize_1 = 2
      ksize_2 = 2
      ksize_3 = 1
      ksize = [ksize_0,ksize_1,ksize_2,ksize_3,]
      strides_0 = 1
      strides_1 = 1
      strides_2 = 1
      strides_3 = 1
      strides = [strides_0,strides_1,strides_2,strides_3,]
      padding = "VALID"
      include_batch_in_index = False
      out = gen_nn_ops.max_pool_grad_with_argmax(arg_0,arg_1,arg_2,ksize=ksize,strides=strides,padding=padding,include_batch_in_index=include_batch_in_index,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      arg_0 = tf.identity(arg_0_tensor)
      arg_0 = tf.cast(arg_0, tf.float32)
      arg_1 = tf.identity(arg_1_tensor)
      arg_1 = tf.cast(arg_1, tf.float32)
      arg_2 = tf.identity(arg_2_tensor)
      arg_2 = tf.cast(arg_2, tf.int64)
      ksize = [ksize_0,ksize_1,ksize_2,ksize_3,]
      strides = [strides_0,strides_1,strides_2,strides_3,]
      gen_nn_ops.max_pool_grad_with_argmax(arg_0,arg_1,arg_2,ksize=ksize,strides=strides,padding=padding,include_batch_in_index=include_batch_in_index,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```

### Relevant log output

```shell
2023-01-04 00:07:17.297598: F tensorflow/core/kernels/maxpooling_op.cc:1065] Check failed: grad_out_index >= output_start && grad_out_index < output_end Invalid output gradient index: 240, 0, 18
Aborted

```
```
</details>

**Comment by mohantym** [comment]
Hi @nimashiri !
Thanks for reporting the bug on gen_nn_ops.max_pool_grad_with_argmax. 

@SuryanarayanaY !
Could you look at this issue . Attached gist in  [2.10](https://colab.sandbox.google.com/gist/mohantym/277838c44ff23266396356a2c811f27f/git_59083.ipynb), [2.11](https://colab.sandbox.google.com/gist/mohantym/2ec28c0f3c7f9a869a7a3fed6bf63ad5/git_59083.ipynb#scrollTo=sF7eYncqU-6k) and [nightly version](https://colab.sandbox.google.com/gist/mohantym/c5d54ce78bb438e5d0f522c38d9adf83/git_59083.ipynb#scrollTo=sF7eYncqU-6k).

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @nimashiri ,

The mentioned behaviour observed with CPU runtime and from runtime logs i observed an Error first:`E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected` and then Warning: `F tensorflow/core/kernels/maxpooling_op.cc:1076] Check failed: grad_out_index >= output_start && grad_out_index < output_end Invalid output gradient index: 120, 0, 18`.
Looking at the error it is trying to check for a GPU and hence I tried the same code with GPU runtime and there is no crash observed in [2.11v](https://colab.sandbox.google.com/gist/SuryanarayanaY/4e1ac25f2af6cd5c34654e5b8edb894f/59083_gpu-2-11.ipynb) and [nightly](https://colab.sandbox.google.com/gist/SuryanarayanaY/ba7c82fc27577e483e1666c811ba0372/59083_gpu-2-12.ipynb) also.

Need to check why this Op is supporting GPU only.Could you share your thoughts.

**Comment by nimashiri** [comment]
> Hi @nimashiri ,
> 
> The mentioned behaviour observed with CPU runtime and from runtime logs i observed an Error first:`E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected` and then Warning: `F tensorflow/core/kernels/maxpooling_op.cc:1076] Check failed: grad_out_index >= output_start && grad_out_index < output_end Invalid output gradient index: 120, 0, 18`. Looking at the error it is trying to check for a GPU and hence I tried the same code with GPU runtime and there is no crash observed in [2.11v](https://colab.sandbox.google.com/gist/SuryanarayanaY/4e1ac25f2af6cd5c34654e5b8edb894f/59083_gpu-2-11.ipynb) and [nightly](https://colab.sandbox.google.com/gist/SuryanarayanaY/ba7c82fc27577e483e1666c811ba0372/59083_gpu-2-12.ipynb) also.
> 
> Need to check why this Op is supporting GPU only.Could you share your thoughts.

Unfortunately, I have no idea in this regard.

**Comment by nimashiri** [comment]
Also this one:

```
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import gen_nn_ops
try:
  try:
    with tf.device('/CPU'):
      arg_0_tensor = tf.random.uniform([2, 3, 3, 1], dtype=tf.float32)
      arg_0 = tf.identity(arg_0_tensor)
      arg_1_tensor = tf.random.uniform([2, 2, 2, 1], dtype=tf.float32)
      arg_1 = tf.identity(arg_1_tensor)
      arg_2_tensor = tf.random.uniform([2, 2, 2, 1], minval=-256, maxval=257, dtype=tf.int64)
      arg_2 = tf.identity(arg_2_tensor)
      ksize_0 = 1
      ksize_1 = 2
      ksize_2 = 2
      ksize_3 = 1
      ksize = [ksize_0,ksize_1,ksize_2,ksize_3,]
      strides_0 = 1
      strides_1 = 1
      strides_2 = 1
      strides_3 = 1
      strides = [strides_0,strides_1,strides_2,strides_3,]
      padding = "VALID"
      include_batch_in_index = False
      out = gen_nn_ops.max_pool_grad_with_argmax(arg_0,arg_1,arg_2,ksize=ksize,strides=strides,padding=padding,include_batch_in_index=include_batch_in_index,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      arg_0 = tf.identity(arg_0_tensor)
      arg_0 = tf.cast(arg_0, tf.float32)
      arg_1 = tf.identity(arg_1_tensor)
      arg_1 = tf.cast(arg_1, tf.float32)
      arg_2 = tf.identity(arg_2_tensor)
      arg_2 = tf.cast(arg_2, tf.int64)
      ksize = [ksize_0,ksize_1,ksize_2,ksize_3,]
      strides = [strides_0,strides_1,strides_2,strides_3,]
      gen_nn_ops.max_pool_grad_with_argmax(arg_0,arg_1,arg_2,ksize=ksize,strides=strides,padding=padding,include_batch_in_index=include_batch_in_index,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```

**Comment by mihaimaruseac** [comment]
@learning-to-play

**Comment by SuryanarayanaY** [comment]
Still an issue in tf-nighlty(2.15.0-dev20231003). Screen shot attached for reference.

<img width="1503" alt="Screenshot 2023-10-04 at 2 24 05 PM" src="https://github.com/tensorflow/tensorflow/assets/116063290/037e2595-7331-40ae-aefa-334e79d51cf7">
