### ISSUE TITLE
Unexpected error when running math_ops.sparse_segment_sum

### ISSUE THREAD

**Issue by nimashiri** [tensorflow/tensorflow#59086]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

22.04

### Current Behaviour?

```shell
I get illegal memory access error when running .sparse_segment_sum with empty tensor as input. The error is not shown when running the code from colab.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import math_ops
try:
  try:
    with tf.device('/CPU'):
      data_tensor = tf.constant([], shape=[0], dtype=tf.float32,)
      data = tf.identity(data_tensor)
      indices_0 = 8
      indices_1 = 3
      indices_2 = 0
      indices_3 = 9
      indices = [indices_0,indices_1,indices_2,indices_3,]
      segment_ids_0 = 1
      segment_ids_1 = 2
      segment_ids_2 = 2
      segment_ids_3 = 2
      segment_ids = [segment_ids_0,segment_ids_1,segment_ids_2,segment_ids_3,]
      out = math_ops.sparse_segment_sum(data=data,indices=indices,segment_ids=segment_ids,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      data = tf.identity(data_tensor)
      data = tf.cast(data, tf.float32)
      indices = [indices_0,indices_1,indices_2,indices_3,]
      segment_ids = [segment_ids_0,segment_ids_1,segment_ids_2,segment_ids_3,]
      math_ops.sparse_segment_sum(data=data,indices=indices,segment_ids=segment_ids,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
2023-01-04 02:06:54.937121: E tensorflow/compiler/xla/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2023-01-04 02:06:54.937146: F tensorflow/core/common_runtime/device/device_event_mgr.cc:221] Unexpected Event status: 1
Aborted

```
```
</details>

**Comment by mohantym** [comment]
Hi @nimashiri !
Thanks for sharing your observation  on math_ops.
I am getting a different error in windows machine actually. 

`Error:Bad: indices[0] == 8 out of range [0, 0) [Op:SparseSegmentSum]
`

@SuryanarayanaY !
Could you look at this issue.  Attached gist in[ 2.9](https://colab.sandbox.google.com/gist/mohantym/8fea1ea0f631ee7aa8c8d40efe0f7be4/git_59086.ipynb#scrollTo=1pDu66rb1sR5), [2.10](https://colab.sandbox.google.com/gist/mohantym/287e22d24d6ab02e048fe36e46625910/git_59086.ipynb#scrollTo=1pDu66rb1sR5) and [2.11](https://colab.sandbox.google.com/gist/mohantym/443f90901e73b8ff4e79ef388b4893c4/git_59086.ipynb#scrollTo=1pDu66rb1sR5) for reference.

Thank you!

**Comment by nimashiri** [comment]
Illegal memory access on TF 2.10:
```
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import math_ops
try:
  try:
    with tf.device('/CPU'):
      data_tensor = tf.constant([], shape=[0], dtype=tf.float32,)
      data = tf.identity(data_tensor)
      indices_0 = 8
      indices_1 = 3
      indices_2 = 0
      indices_3 = 9
      indices = [indices_0,indices_1,indices_2,indices_3,]
      segment_ids_0 = 1
      segment_ids_1 = 2
      segment_ids_2 = 2
      segment_ids_3 = 2
      segment_ids = [segment_ids_0,segment_ids_1,segment_ids_2,segment_ids_3,]
      out = math_ops.sparse_segment_sum(data=data,indices=indices,segment_ids=segment_ids,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      data = tf.identity(data_tensor)
      data = tf.cast(data, tf.float32)
      indices = [indices_0,indices_1,indices_2,indices_3,]
      segment_ids = [segment_ids_0,segment_ids_1,segment_ids_2,segment_ids_3,]
      results["res_gpu"] = math_ops.sparse_segment_sum(data=data,indices=indices,segment_ids=segment_ids,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```


Log message:
```
Error:{{function_node __wrapped__SparseSegmentSum_device_/job:localhost/replica:0/task:0/device:CPU:0}} Bad: indices[0] == 8 out of range [0, 0) [Op:SparseSegmentSum]
2023-01-05 21:58:42.760715: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2023-01-05 21:58:42.760958: F tensorflow/core/common_runtime/device/device_event_mgr.cc:221] Unexpected Event status: 1
Aborted
```

**Comment by SuryanarayanaY** [comment]
Hi @nimashiri ,
I tried the code on Ubuntu VM with TF 2.11 and i could not get any Illegal Memory Access.I got different error: `Error:Bad: indices[0] == 8 out of range [0, 0) [Op:SparseSegmentSum] `.Please check attached snapshot. Could you please check and confirm?

<img width="1493" alt="Screenshot 2023-01-06 at 12 26 07 PM" src="https://user-images.githubusercontent.com/116063290/210947511-80d51d2f-7398-4d7f-aa11-b55fec798e31.png">

I tried with TF 2.10v also even there there is no such error mentioned by you.Please refer snapshot below.

<img width="1512" alt="Screenshot 2023-01-06 at 12 32 55 PM" src="https://user-images.githubusercontent.com/116063290/210948480-d70d046b-bfb4-465d-9d30-d32672933b83.png">

Could you please check and comeback what is missing here ?

Thankyou.

**Comment by nimashiri** [comment]
> Hi @nimashiri , I tried the code on Ubuntu VM with TF 2.11 and i could not get any Illegal Memory Access.I got different error: `Error:Bad: indices[0] == 8 out of range [0, 0) [Op:SparseSegmentSum] `.Please check attached snapshot. Could you please check and confirm?
> 
> <img alt="Screenshot 2023-01-06 at 12 26 07 PM" width="1493" src="https://user-images.githubusercontent.com/116063290/210947511-80d51d2f-7398-4d7f-aa11-b55fec798e31.png">
> 
> I tried with TF 2.10v also even there there is no such error mentioned by you.Please refer snapshot below.
> 
> <img alt="Screenshot 2023-01-06 at 12 32 55 PM" width="1512" src="https://user-images.githubusercontent.com/116063290/210948480-d70d046b-bfb4-465d-9d30-d32672933b83.png">
> 
> Could you please check and comeback what is missing here ?
> 
> Thankyou.

I can't get illegal memory access anymore on tf-2.10 and tf-2.11. The behavior is very strage since I could get this error on both versions as reported in the issue with log messages.

**Comment by SuryanarayanaY** [comment]
@nimashiri ,
I tried to execute the same code few times again and i can't get the illegal memory error.Please refer to attached snapshot.
<img width="1512" alt="Screenshot 2023-01-08 at 12 38 27 PM" src="https://user-images.githubusercontent.com/116063290/211241317-fb853e62-eae9-4e76-a57f-19077b3e4a9a.png">

As the behaviour is not observed now shall we close the issue now ? Please feel free to report if you find the behaviour again.Awaiting your confirmation.Thank you!

**Comment by nimashiri** [comment]
Ok thanks, it seems only on my config, it throws illegal memory access.

**Comment by SuryanarayanaY** [comment]
Hi @nimashiri ,
The code was tested multiple runs on Ubuntu 22.04 also and couldn't found Illegal Memory Access error.Please refer to snapshot attached below.]

<img width="1512" alt="Screenshot 2023-01-15 at 1 09 32 PM" src="https://user-images.githubusercontent.com/116063290/212633046-2ff9c28f-78c4-46a4-9314-e7c51ce94948.png">

I think the error in this case may be related to you environment.Could you please cross check and close this issue if only related to your environment.

Thank you!
