### ISSUE TITLE
Illegal memory access when running tensorflow.python.ops.gen_math_ops.sparse_segment_sum when running from terminal

### ISSUE THREAD

**Issue by nimashiri** [tensorflow/tensorflow#59089]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

22.04

### Python version

3.9

### Current Behaviour?

```shell
When running the test case from terminal via command  test_case.py, it gives me illegal memory access. The appropriate error message prompted when running from colab.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import gen_math_ops
try:
  try:
    with tf.device('/CPU'):
      data_tensor = tf.constant([], shape=[0], dtype=tf.float32,)
      data = tf.identity(data_tensor)
      indices_0 = 8
      indices_1 = 3
      indices_2 = 0
      indices_3 = 9
      indices = [indices_0,indices_1,indices_2,indices_3,]
      segment_ids_0 = 1
      segment_ids_1 = 2
      segment_ids_2 = 2
      segment_ids_3 = 2
      segment_ids = [segment_ids_0,segment_ids_1,segment_ids_2,segment_ids_3,]
      out = gen_math_ops.sparse_segment_sum(data=data,indices=indices,segment_ids=segment_ids,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      data = tf.identity(data_tensor)
      data = tf.cast(data, tf.float32)
      indices = [indices_0,indices_1,indices_2,indices_3,]
      segment_ids = [segment_ids_0,segment_ids_1,segment_ids_2,segment_ids_3,]
      results["res_gpu"] = gen_math_ops.sparse_segment_sum(data=data,indices=indices,segment_ids=segment_ids,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
2023-01-04 02:36:20.355748: E tensorflow/compiler/xla/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2023-01-04 02:36:20.355774: F tensorflow/core/common_runtime/device/device_event_mgr.cc:221] Unexpected Event status: 1
Aborted

```
```
</details>

**Comment by mohantym** [comment]
Hi @nimashiri !

Thanks for sharing observations on sparse_segment_sum.

@SuryanarayanaY!
Could you look at this issue. Attached gist in[ 2.9](https://colab.sandbox.google.com/gist/mohantym/714e9172225d0417d0078017bc23f44d/git_59089.ipynb), [2.10](https://colab.sandbox.google.com/gist/mohantym/3156478fe6eca9c5f5602db4a17d0adf/git_59089.ipynb#scrollTo=KuiuW13jDQBH) and [2.11 ](https://colab.sandbox.google.com/gist/mohantym/b1f641ab201f6a01dc187de9a5ed56d4/git_59089.ipynb) for reference.

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @nimashiri ,
I tried the code provided and i got error: `Bad: indices[0] == 8 out of range [0, 0) [Op:SparseSegmentSum]`.
Please refer to attached colab [gist](https://colab.research.google.com/gist/SuryanarayanaY/45bc07357a077a56d6b114d7308653c6/59089-cpu.ipynb).Please note that the colab runtime is CPU only as I couldn't access GPU runtime on colab for now.

I tried to replicate the issue on a GCP VM with Ubuntu OS terminal the result is similar to colab and also attached below.
But i found the variable `results` mentioned under `tf.device('GPU')` code not defined anywhere in the code.Hence GPU code causing Name error. Can you cross check and confirm the code as behaviour you mentioned not replicated.

<img width="1506" alt="Screenshot 2023-01-06 at 12 02 47 PM" src="https://user-images.githubusercontent.com/116063290/210944328-5fa3f7b3-f5f6-4672-8a79-c59d8bd7515b.png">

**Comment by nimashiri** [comment]
> Hi @nimashiri , I tried the code provided and i got error: `Bad: indices[0] == 8 out of range [0, 0) [Op:SparseSegmentSum]`. Please refer to attached colab [gist](https://colab.research.google.com/gist/SuryanarayanaY/45bc07357a077a56d6b114d7308653c6/59089-cpu.ipynb).Please note that the colab runtime is CPU only as I couldn't access GPU runtime on colab for now.
> 
> I tried to replicate the issue on a GCP VM with Ubuntu OS terminal the result is similar to colab and also attached below. But i found the variable `results` mentioned under `tf.device('GPU')` code not defined anywhere in the code.Hence GPU code causing Name error. Can you cross check and confirm the code as behaviour you mentioned not replicated.
> 
> <img alt="Screenshot 2023-01-06 at 12 02 47 PM" width="1506" src="https://user-images.githubusercontent.com/116063290/210944328-5fa3f7b3-f5f6-4672-8a79-c59d8bd7515b.png">

I don't get the error anymore on tf-2.10 and tf-2.11 both on CPU and GPU. It seems this error is thrown randomely. Same behavior for other APIs also. Sorry for the ```result``` variable, just edited the code. Thanks.

**Comment by SuryanarayanaY** [comment]
@nimashiri ,
I tried to execute the same code few times and i can't get the illegal memory error.Please refer to attached snapshots.
<img width="1512" alt="Screenshot 2023-01-08 at 12 09 25 PM" src="https://user-images.githubusercontent.com/116063290/211240763-56c94348-eabf-4a23-8c41-a98e96afb2f0.png">
<img width="1512" alt="Screenshot 2023-01-08 at 12 11 39 PM" src="https://user-images.githubusercontent.com/116063290/211240773-1e9bdcbb-4df9-4c2a-a7f8-98b5d3d18bb9.png">

Not sure how you got that earlier. As the behaviour is not observed here shall we close the issue now ? Please feel free to report if you find the behaviour again.Awaiting your confirmation.Thank you!

**Comment by nimashiri** [comment]
> @nimashiri , I tried to execute the same code few times and i can't get the illegal memory error.Please refer to attached snapshots. <img alt="Screenshot 2023-01-08 at 12 09 25 PM" width="1512" src="https://user-images.githubusercontent.com/116063290/211240763-56c94348-eabf-4a23-8c41-a98e96afb2f0.png"> <img alt="Screenshot 2023-01-08 at 12 11 39 PM" width="1512" src="https://user-images.githubusercontent.com/116063290/211240773-1e9bdcbb-4df9-4c2a-a7f8-98b5d3d18bb9.png">
> 
> Not sure how you got that earlier. As the behaviour is not observed here shall we close the issue now ? Please feel free to report if you find the behaviour again.Awaiting your confirmation.Thank you!

Thanks for the reply. I am running my fuzzer script using subprocess.run(), this may be the root cause of illegal memory access. When I simply run the script in the terminal or using vscode, there is no illegal memory access.

**Comment by SuryanarayanaY** [comment]
@nimashiri ,

Thanks for confirmation and same will be informed to developer team.Could you please share the script also to cross check the behaviour ? Thanks.

**Comment by SuryanarayanaY** [comment]
@nimashiri ,
Could you please check with high level API `tf.sparse.segment_sum` and confirm if the problem persists with it also ?
I checked with ot and i can't find the illegal memory access error there.Please refer to log stack from VM terminal.

```
(tf) suryanarayanay@ubuntu-20-04-test-gpu-surya:~$ python 59089_vm_hlapi.py
2023-01-10 06:34:05.807805: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-10 06:34:06.286135: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-01-10 06:34:08.419465: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/suryanarayanay/miniconda3/envs/tf/lib/
2023-01-10 06:34:08.419582: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/suryanarayanay/miniconda3/envs/tf/lib/
2023-01-10 06:34:08.419599: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2.11.0
2023-01-10 06:34:14.643273: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 38285 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:04.0, compute capability: 8.0
2023-01-10 06:34:14.647232: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 38397 MB memory:  -> device: 1, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:05.0, compute capability: 8.0
2023-01-10 06:34:14.649634: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:2 with 38397 MB memory:  -> device: 2, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:06.0, compute capability: 8.0
2023-01-10 06:34:14.652021: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:3 with 38397 MB memory:  -> device: 3, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:07.0, compute capability: 8.0
Error:{{function_node __wrapped__SparseSegmentSum_device_/job:localhost/replica:0/task:0/device:CPU:0}} Bad: indices[0] == 8 out of range [0, 0) [Op:SparseSegmentSum]
(tf) suryanarayanay@ubuntu-20-04-test-gpu-surya:~$ 
```
Also I tested the same in Colab-GPU environment and no Illegal Memory Access error observed.Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/fdf9de7724c2000280bbd49614fb1540/59089_vm_hlapi.ipynb).

For earlier code with `tf.python.ops.gen_math_ops.sparse_segment_sum` Op, I replaced variable 'result' with `_ `  to ensure the Op execution on GPU and did not got Illegal Memory Access error from VM terminal as per log stack below.

```
(tf) suryanarayanay@ubuntu-20-04-test-gpu-surya:~$ python 59089_vm.py
2.11.0
Error:{{function_node __wrapped__SparseSegmentSum_device_/job:localhost/replica:0/task:0/device:CPU:0}} Bad: indices[0] == 8 out of range [0, 0) [Op:SparseSegmentSum]
```
However the same code with `tf.python.ops.gen_math_ops.sparse_segment_sum` when tested on Colab found crashed and from log i can see Illegal Memory Access Error as per snapshot below.
<img width="1512" alt="Screenshot 2023-01-10 at 12 20 46 PM" src="https://user-images.githubusercontent.com/116063290/211482057-53a4af42-2a85-4a92-801e-9cd717554565.png">.

When used high level API `tf.sparse.segment_sum` there is no `Illegal Memory Access Error` but with `tf.python.ops.gen_math_ops.sparse_segment_sum` from Colab encountered `Illegal Memory Access Error` but from VM terminal no Illegal memory access error.Request you to use high level API for now only and if you observe similar error please confirm with us.

**Comment by SuryanarayanaY** [comment]
@nimashiri ,
The code tested on tf-nightly and there no Illegal Memory Access error.Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/d8c8a8137121b56b7b896475c22a6857/59089-gpu.ipynb).

**Comment by SuryanarayanaY** [comment]
Update: On Colab with multiple runs of same code even in nightly-version also I observed session crash with Illegal Memory Access error.Snapshot attached below for logs.
<img width="1503" alt="Screenshot 2023-01-12 at 7 36 32 PM" src="https://user-images.githubusercontent.com/116063290/212088415-a604a477-3db2-4c39-8d57-a8252d67c424.png">

But from VM terminal with Ubuntu 20.04 OS even multiple runs won't able to get that Illegal Memory Access error.Needs more investigation.
