### ISSUE TITLE
run (cd tensorflow/go/op && go generate) error

### ISSUE THREAD

**Issue by kingangelAOA** [tensorflow/tensorflow#59092]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.6.0

### Custom Code

Yes

### Current Behaviour?

```shell
run command success
```

### Standalone code to reproduce the issue

```shell
2023/01/04 23:07:10 failed to process "api_def_MergeV2Checkpoints.pbtxt": Attribute allow_missing_files not defined in base api for MergeV2Checkpoints
exit status 1
generate.go:18: running "go": exit status 1
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @kingangelAOA !

I see the [go documentation](https://github.com/tensorflow/build/tree/master/golang_install_guide) from tensorflow/build has been updated  last month  (mentions TF 2.11)
Could you provide the colab gist to replicate this issue. 

Thank you!
