### ISSUE TITLE
[TF-Lite]Is there a way to profile a model's inference process when using tflite in python

### ISSUE THREAD

**Issue by Disliketalking** [tensorflow/tensorflow#59095]
Is there a way to profile a model's inference process when using tflite in python？

**Comment by sushreebarsa** [comment]
@Disliketalking For using model inference using tf-lite, you need to follow the instructions present [here](https://www.tensorflow.org/lite/guide/inference) in this document.
Could you please have a look at this and let us know if it helps?
Thank you!

**Comment by Disliketalking** [comment]
> @Disliketalking For using model inference using tf-lite, you need to follow the instructions present [here](https://www.tensorflow.org/lite/guide/inference) in this document. Could you please have a look at this and let us know if it helps? Thank you!

Thanks for your answer, I can already use tf-lite for inference, but I don't know how to profile the inference process.

**Comment by sushreebarsa** [comment]
@Disliketalking TensorFlow Lite interpreter runs in the recognizeImage/runInference section.  To run the tflite profile for interference process please refer to this [doc](https://www.tensorflow.org/lite/performance/measurement) and let us know if it helps?
Thank you!
