### ISSUE TITLE
Random error after hundreds of iterations: Aborting RingReduce with Invalid argument: Incompatible shapes: [0,64] vs. [0,256]

### ISSUE THREAD

**Issue by hugo-mrc** [tensorflow/tensorflow#59104]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tensorflow-rocm 2.2

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

ROCm v3.5

### GPU model and memory

2 RX 480 4Go

### Current Behaviour?

```shell
Hello Tensorflow community,

I randomly encounter this bug after few tens of iterations for no apparent reason. Sometimes after t > 400. 
The "incompatible shapes" also differ from execution to execution. It doesn't seems to come from input datas.

I also got those warnings at the execution:
2023-01-05 10:30:46.933216: W tensorflow/core/grappler/optimizers/scoped_allocator_optimizer.cc:435] error: Internal: Complete shape not known for allreduce/CollectiveReduce_5
2023-01-05 10:30:46.933250: W tensorflow/core/grappler/optimizers/scoped_allocator_optimizer.cc:1117] error: Internal: Complete shape not known for allreduce/CollectiveReduce_5
2023-01-05 10:30:46.933351: E tensorflow/core/grappler/optimizers/scoped_allocator_optimizer.cc:1134] ScopedAllocatorOptimizer: Internal: Complete shape not known for allreduce/CollectiveReduce_5
2023-01-05 10:30:46.933359: W tensorflow/core/grappler/optimizers/scoped_allocator_optimizer.cc:907] error: Internal: Complete shape not known for allreduce/CollectiveReduce_5
2023-01-05 10:30:46.934321: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:563] scoped_allocator_optimizer failed: Internal: Complete shape not known for allreduce/CollectiveReduce_5


Thank you for your help.
```

### Standalone code to reproduce the issue

```shell
import os
import random
import time

import numpy as np
import tensorflow as tf
from tqdm import tqdm
from collections import deque

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1'


print(tf.config.experimental.list_physical_devices("GPU"))
mirrored_strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy(tf.distribute.experimental.CollectiveCommunication.RING)

window_size = 5
episodes = 20
batch_size = 32
NAME = f"Blackstonev1-LSTM-32x64x64-{int(time.time())}"
tensorboard = tf.keras.callbacks.TensorBoard(log_dir="logs\{}".format(NAME))

class AIAgent:
    def __init__(self, state_size, action_space=3, model_name=NAME):  # Stay, Buy, Sell
        self.state_size = state_size
        self.action_space = action_space
        self.memory = deque(maxlen=2000)
        self.inventory = []
        self.margin_inventory = []
        self.model_name = model_name

        self.gamma = 0.95
        self.epsilon = 1.0
        self.epsilon_final = 0.05
        self.epsilon_decay = 0.9995

        self.model = self.model_builder()

    def model_builder(self):
        with mirrored_strategy.scope():
            model = tf.keras.models.Sequential()

            model.add(tf.keras.Input(shape=(window_size, 2)))

            model.add(tf.keras.layers.LSTM(units=32, activation='relu', return_sequences=True))
            model.add(tf.keras.layers.LSTM(units=64, activation='relu', return_sequences=True))
            model.add(tf.keras.layers.LSTM(units=64, activation='relu', return_sequences=False))
            model.add(tf.keras.layers.Dense(units=self.action_space, activation='linear'))
            model.compile(loss='mse', optimizer=tf.keras.optimizers.Adam(lr=0.001))

        return model

    def trade(self, state):
        rdm = random.random()
        if rdm <= self.epsilon:
            rdm_act = random.randrange(self.action_space)
            print(f"random: {rdm_act}")
            return rdm_act

        actions = self.model.predict(state)
        argmax = np.argmax(actions[0])
        print(f'model: {argmax}')
        return argmax

    def batch_train(self, batch_size):
        batch = []
        for i in range(len(self.memory) - batch_size + 1, len(self.memory)):
            batch.append(self.memory[i])

        for state, action, reward, next_state, done in batch:
            reward = reward

            if not done:
                reward = reward + self.gamma * np.amax(self.model.predict(next_state)[0])

            target = self.model.predict(state)
            target[0][action] = reward

            self.model.fit(state, target, epochs=1, verbose=0, callbacks=[tensorboard])

        if self.epsilon > self.epsilon_final:
            self.epsilon *= self.epsilon_decay


def state_creator(data, timestep, window_size):
    starting_id = timestep - window_size + 1

    if starting_id >= 0:
        windowed_data = data[starting_id:timestep + 1]
    else:
        windowed_data = - starting_id * [data[0]] + list(data[0:timestep + 1])

    state = windowed_data

    return np.array([state])


def main(batch_size, window_size, episodes):
    data = load_data(stock_name) # Replace with your own input here
    data_samples = len(data) - 1
    agent = AIAgent(window_size)
    agent.model.summary()
    
    
    for episode in range(1, episodes + 1):
        print("Episode: {}/{}".format(episode, episodes))
        state = state_creator(data, 0, window_size)
    
        total_profit = 0
        agent.inventory = []
    
        for t in tqdm(range(data_samples)):
            action = agent.trade(state)
    
            next_state = state_creator(data, t + 1, window_size)
            reward = 0
    
            if action == 1:
                # Do that
                continue
            elif action == 2:
                # Do that
                continue
    
            elif action == 0:
                # Do that
                continue
    
            if t == data_samples - 1:
                done = True
            else:
                done = False
    
            agent.memory.append((state, action, reward, next_state, done))
            state = next_state
    
            if len(agent.memory) > batch_size:
                agent.batch_train(batch_size)
    
        agent.model.save(f"{agent.model_name}_{episode}.h5")
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "main.py", line 207, in <module>
    trader.batch_train(batch_size)
  File "main.py", line 91, in batch_train
    self.model.fit(state, target, epochs=1, verbose=0, callbacks=[tensorboard])
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 611, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1661, in _filtered_call
    return self._call_flat(
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1745, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 593, in call
    outputs = execute.execute(
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Incompatible shapes: [0,64] vs. [0,256]
	 [[{{node gradient_tape/replica_1/sequential/lstm_2/while/replica_1/sequential/lstm_2/while_grad/body/_1459/gradients/lstm_cell_2/mul_grad/BroadcastGradientArgs}}]]
  (1) Invalid argument:  Incompatible shapes: [0,64] vs. [0,256]
	 [[{{node gradient_tape/replica_1/sequential/lstm_2/while/replica_1/sequential/lstm_2/while_grad/body/_1459/gradients/lstm_cell_2/mul_grad/BroadcastGradientArgs}}]]
	 [[Adam/Adam/update_1_1/AssignAddVariableOp/_323]]
0 successful operations.
1 derived errors ignored. [Op:__inference_train_function_10543]

Function call stack:
train_function -> train_function
```
</details>

**Comment by hugo-mrc** [comment]
Other exemple below at t=385:
2023-01-05 12:40:34.394719: E tensorflow/core/common_runtime/ring_alg.cc:279] Aborting RingReduce with Invalid argument: Input to reshape is a tensor with 1 values, but the requested shape has 64
	 [[{{node gradient_tape/mean_squared_error/Reshape}}]]
	 [[div_no_nan/allreduce/CollectiveReduce/_294]]

**Comment by hugo-mrc** [comment]
The issue is probably related to synchronized computing because when running with: `mirrored_strategy = tf.distribute.MirroredStrategy(devices=["/gpu:1"])` the program doesn't appear to crash ever.
Tried as well with 2 GPUs with 'tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.ReductionToOneDevice())' but this caused the same error previously described

**Comment by hugo-mrc** [comment]
Just happened with one GPU, I can confirm it's not related to mirroring

Traceback (most recent call last):
  File "main.py", line 224, in <module>
    trader.batch_train(batch_size)
  File "main.py", line 92, in batch_train
    self.model.fit(state, target, epochs=1, verbose=0, callbacks=[tensorboard])
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 848, in fit
    tmp_logs = train_function(iterator)
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
    result = self._call(*args, **kwds)
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 611, in _call
    return self._stateless_fn(*args, **kwds)  # pylint: disable=not-callable
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2420, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1661, in _filtered_call
    return self._call_flat(
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1745, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 593, in call
    outputs = execute.execute(
  File "/home/hugo/Documents/scripts/blackstone_ai/venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  Incompatible shapes: [0,1027297329] vs. [1,64]
	 [[{{node gradient_tape/sequential/lstm_2/while/sequential/lstm_2/while_grad/body/_495/gradients/lstm_cell_2/mul_1_grad/BroadcastGradientArgs}}]]
	 [[div_no_nan/ReadVariableOp_1/_158]]
  (1) Invalid argument:  Incompatible shapes: [0,1027297329] vs. [1,64]
	 [[{{node gradient_tape/sequential/lstm_2/while/sequential/lstm_2/while_grad/body/_495/gradients/lstm_cell_2/mul_1_grad/BroadcastGradientArgs}}]]
0 successful operations.
1 derived errors ignored. [Op:__inference_train_function_5728]

Function call stack:
train_function -> train_function

**Comment by mohantym** [comment]
Hi @hugo-mrc !

Thanks for sharing your observation dist-strat and 2 gpu cards. 
Just curious on whether you tested with TF > 2.9 version or not . 

@SuryanarayanaY !
Could you look at this issue or not.

Thank you!

**Comment by hugo-mrc** [comment]
Hello @mohantym 
Thanks for your answer.

I also tried with this explicit statement but also got the same error.

Unfortunately, I can't try with tf>2.2 cause my gpus only work with ROCm<=3.5 on my machine.

**Comment by hugo-mrc** [comment]
Also tried with 
`mirrored_strategy = tf.distribute.MirroredStrategy(devices=["GPU:1"], cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())`
And got the same error.

The most surprising thing is that it's purely random ...
Also noticed that my CPU is overloaded, do you think it can affect the program? 

Thank you,

**Comment by hugo-mrc** [comment]
Also got the error by specifying `mirrored_strategy = tf.device('/gpu:1')`
Any idea please ? 
@mohantym 
@SuryanarayanaY

**Comment by SuryanarayanaY** [comment]
Hi @hugo-mrc ,
I tested the code with change in strategy to `mirrored_strategy = tf.distribute.OneDeviceStrategy(device="/gpu:0")` and the code executes fine.Please refer to attached colab [gist](https://colab.research.google.com/gist/SuryanarayanaY/b281f2f26a39c1e51ad19ecfec74d559/59104.ipynb).
If you have Multiple GPUs on same machine then you should use[ tf.distribute.MirroredStrategy](https://www.tensorflow.org/api_docs/python/tf/distribute/MirroredStrategy) only.
If you want to train on Multiple Machines with  GPUs then only you should use [tf.distribute.MultiWorkerMirroredStrategy](https://www.tensorflow.org/api_docs/python/tf/distribute/MultiWorkerMirroredStrategy).

Please refer to attached documentation link for more details.

**Comment by hugo-mrc** [comment]
Hello SuryanarayanaY,
Indeed, might come from my environment ... 

Also tried with tensorflow==2.1.2 and 2.1.6 and python==3.6.15 and got this warning :

WARNING:tensorflow:5 out of the last 5 calls to <function _make_execution_function.<locals>.distributed_function at 0x7ff9884c59e0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings is likely due to passing python objects instead of tensors. Also, tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. Please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.

Maybe that can help!

**Comment by SuryanarayanaY** [comment]
Hi @hugo-mrc ,
The warning mentioned above regarding retracing is safe to ignore which actually comes when we repeatedly call `tf.function` inside code or running the code having `tf.function` multiple times in the same session.AFAIK the error mentioned in the ticket not related to the `tf.function` warning and it has nothing to do with `experimental_relax_shapes=True` . You may also test with `experimental_relax_shapes=True` and confirm if it avoids error.

My ask here is How many systems you are using for model training? Since I can see you are using `MultiWorkerMirroredStrategy` which has to be used only if you want to train the model on Multiple workers(servers/computers).For single system this strategy it may not work as intended and unexpected error may arise in that case you need to use `MirroredStrategy` only. Providing the details like 1.How many systems/servers you are using for training 2.How many GPUs in each etc may help us to reach the root cause of the error.

**Comment by hugo-mrc** [comment]
Thanks for your answer. 
Ok I look furthr about the second issue then.

About the first one, was indeed a mistake to use `MultiWorkerMirroredStrategy`, but it's not what causing the issue, as mentioned earlier : 

> > Also tried with
> mirrored_strategy = tf.distribute.MirroredStrategy(devices=["GPU:1"], cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())
> And got the same error.
> 
> The most surprising thing is that it's purely random ...
> Also noticed that my CPU is overloaded, do you think it can affect the program?
> 
> Thank you,

**Comment by SuryanarayanaY** [comment]
@hugo-mrc ,

`tf.distribute.experimental.CollectiveCommunication.RING` will be used for Cross device communication in MultiWorkerMirroredStrategy only. With single GPU `tf.distribute.OneDeviceStrategy(device="/gpu:1")` there is no need of  arguments like communication and Iam wondering how you are getting this error which is not relevant to `OneDeviceStrategy`. Can you share the exact code you are using with single GPU strategy `tf.distribute.OneDeviceStrategy(device="/gpu:1")`.

Also with tf.distribute.MirroredStrategy(devices=["GPU:1"] as you are using cross_device_ops=tf.distribute.HierarchicalCopyAllReduce()) argument can you try it changing to other options and let us know the behaviour.

It seems the reported behaviour is related to your own environment only.Could you confirm whether you have used ROCM build with the `MirroredStrategy` earlier? What are the configurations you have used earlier ? Can you try to build with latest TF version and let us know if it works.You may found supported configurations of ROCM [here](https://github.com/tensorflow/tensorflow/blob/r2.11/.bazelrc) for latest version.

Thankyou!

**Comment by hugo-mrc** [comment]
I can assure that I get this shapes error with `tf.distribute.OneDeviceStrategy(device="/gpu:1")` ; the code is exactly the same as provided excepted for the mirrored_strategy parameter. 

Will try and give you the result ASAP

It actually can be related to my environment, I found this particular issue: 
[https://github.com/RadeonOpenCompute/ROCm/issues/1203](url)
But already have the setup recommend in this issue (ie. Rocm 3.5.1, python 3.8, tensorflow-rocm 2.2, Ubuntu 20.04)

**Comment by SuryanarayanaY** [comment]
To reduce retracing time you can set `reduce_retracing=True` as argument in `tf.function()`. It may helps in reducing the retracing time.
Also may be the error is related to your environment. To confirm that could you please provide some dummy data.May be that helps in debugging the error.
Thanks!

**Comment by hugo-mrc** [comment]
It was indeed coming from my environment. 
I found that the following versions have finally worked for me: python: 3.7.16, tensorflow-rocm: 2.1.6, rocm: 3.5.1, ubuntu: 20.04 kernel: 5.0.42
if you have the same error, I recommend you this tutorial: 
[](https://github.com/Grench6/RX580-rocM-tensorflow-ubuntu20.4-guide)
Wish you good luck if you have to train with AMD's Polaris card ...

Thank you for your help @SuryanarayanaY
