### ISSUE TITLE
benchmark_model elinux_aarch64 build with define CL_DELEGATE_NO_GL fails

### ISSUE THREAD

**Issue by tensorbuffer** [tensorflow/tensorflow#59112]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.10

### Custom Code

No

### OS Platform and Distribution

Linux ubuntu 18.04

### Bazel version

5.3.0

### CUDA/cuDNN version

NA

### Current Behaviour?

```shell
This is to build benchmark_model to run on linux embedded system.
This command builds fine:     bazel build -c opt --config elinux_aarch64 --config monolithic - tensorflow/lite/tools/benchmark:benchmark_model

However when run on ARM device, there's error:
The GPU delegate compile options are only supported on Android or iOS platforms or when the tool was built with -DCL_DELEGATE_NO_GL.

So building with this defined:
    bazel build -c opt --config elinux_aarch64 --config monolithic --copt -DCL_DELEGATE_NO_GL=true tensorflow/lite/tools/benchmark:benchmark_model

Got compile error:
ERROR: /workspace/tensorflow/tensorflow/lite/tools/delegates/BUILD:113:11: Compiling tensorflow/lite/tools/delegates/hexagon_delegate_provider.cc failed: undeclared inclusion(s) in rule '//tensorflow/lite/tools/delegates:hexagon_delegate_provider':
this rule is missing dependency declarations for the following files included by 'tensorflow/lite/tools/delegates/hexagon_delegate_provider.cc':
  'tensorflow/lite/delegates/gpu/delegate.h'
  'tensorflow/lite/delegates/gpu/delegate_options.h'
In file included from ./tensorflow/lite/tools/evaluation/utils.h:35,
                 from tensorflow/lite/tools/delegates/hexagon_delegate_provider.cc:19:
./tensorflow/lite/delegates/hexagon/hexagon_delegate.h:111:72: warning: 'visibility' attribute ignored on non-class types [-Wattributes]
 TfLiteHexagonDelegateCreate(const TfLiteHexagonDelegateOptions* options);
                                                                        ^

I think this define (CL_DELEGATE_NO_GL) includes new header files which is not in BUILD, for example:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/evaluation/utils.h
```

### Standalone code to reproduce the issue

```shell
NA
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @tensorbuffer !

Thanks for sharing your observations . 
I am able to replicate this issue in [2.9](https://colab.sandbox.google.com/gist/mohantym/a82374c7f71f501e708484bcb5e15cfc/tensorflow-ranking.ipynb#scrollTo=vDXp-0XmqYkc), [2.10](https://colab.sandbox.google.com/gist/mohantym/423d9adc36c23749e211c5dc4405cfc0/tensorflow-ranking.ipynb#scrollTo=Bs_EYa-ZISaW), [2.11](https://colab.sandbox.google.com/gist/mohantym/1f04552e0260a616017b97212f1c6a86/tensorflow-ranking.ipynb#scrollTo=WK0CrEW7jivv) and [2.12 dev ](https://colab.sandbox.google.com/gist/mohantym/902dbb1e585baac7bf5ef260b81f4d3a/tensorflow-ranking.ipynb#scrollTo=WK0CrEW7jivv).

Could you send a PR for review. 

Thank you!
