### ISSUE TITLE
Tensorflow for C Windows GPU install is missing

### ISSUE THREAD

**Issue by jacklion710** [tensorflow/tensorflow#59119]
https://www.tensorflow.org/install/lang_c I just wanted to let it be known that the link for the Windows GPU only tensorflow for C install is broken. I understand that the tensorflow C project isn’t as popular or heavily supported but I feel like somethings amiss. Feels like if it wasn't supposed to exist then there would be no indication via a link. Would love to see this fixed if possible

**Comment by tilakrayal** [comment]
@jacklion710,
Have you got the chance to have a look at this [#2165](https://github.com/tensorflow/docs/pull/2165) where the developer proposed **"Windows GPU libtensorflow C packages are not available in the 2.11 release. To support the community update the same to 2.10."** which is still open and under review process. Thank you!

**Comment by jacklion710** [comment]
@tilakrayal thank you for taking the time to respond and inform me of this! I'll be trying out 2.10 soon.
