### ISSUE TITLE
Segmentation fault when running gen_ragged_array_ops.ragged_cross

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59114]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

22.04

### Current Behaviour?

```shell
When running .ragged_cross with the following input combination, it results in segfault.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_ragged_array_ops
try:
  ragged_values_0_tensor = tf.convert_to_tensor(np.ones([3], dtype=str))
  ragged_values_0 = tf.identity(ragged_values_0_tensor)
  ragged_values = [ragged_values_0,]
  ragged_row_splits_0_tensor = tf.random.uniform([4], minval=-256, maxval=257, dtype=tf.int64)
  ragged_row_splits_0 = tf.identity(ragged_row_splits_0_tensor)
  ragged_row_splits = [ragged_row_splits_0,]
  sparse_indices = []
  sparse_values = []
  sparse_shape = []
  dense_inputs = []
  input_order = "R"
  hashed_output = False
  num_buckets = 0
  hash_key = 956888297470
  out_values_type = 7
  out_row_splits_type = 9
  out = gen_ragged_array_ops.ragged_cross(ragged_values=ragged_values,ragged_row_splits=ragged_row_splits,sparse_indices=sparse_indices,sparse_values=sparse_values,sparse_shape=sparse_shape,dense_inputs=dense_inputs,input_order=input_order,hashed_output=hashed_output,num_buckets=num_buckets,hash_key=hash_key,out_values_type=out_values_type,out_row_splits_type=out_row_splits_type,)
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
The only log message is:


Segmentation fault
```
```
</details>

**Comment by tilakrayal** [comment]
@nimashiri,
**gen_ragged_array_ops.ragged_cross** is the generated OP wrapper.  I tried to execute the code with the alternative approach and it was working as expected. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/ebf1cf103dd28abf059d4533eda80327/untitled839.ipynb) and also please take a look at the high level api of gen_ragged_array_ops.ragged_cross from the doc [link1](https://www.tensorflow.org/api_docs/python/tf/ragged/cross) and [link2](https://www.tensorflow.org/api_docs/python/tf/raw_ops/RaggedCross) for the reference. Thank you!

**Comment by nimashiri** [comment]
> @nimashiri, **gen_ragged_array_ops.ragged_cross** is the generated OP wrapper. I tried to execute the code with the alternative approach and it was working as expected. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/ebf1cf103dd28abf059d4533eda80327/untitled839.ipynb) and also please take a look at the high level api of gen_ragged_array_ops.ragged_cross from the doc [link1](https://www.tensorflow.org/api_docs/python/tf/ragged/cross) and [link2](https://www.tensorflow.org/api_docs/python/tf/raw_ops/RaggedCross) for the reference. Thank you!

Thanks. I get segfault when running from my terminal, ubuntu 22.04:

![Screenshot from 2023-01-06 08-50-14](https://user-images.githubusercontent.com/17060581/211025304-04149d0a-8d7b-4cd4-918e-429fd5fbde2d.png)

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.10, v2.11 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/7cbeeca7fbd730100159b204ee9c5640/untitled868.ipynb).

**Comment by nimashiri** [comment]
> @sachinprasadhs, I was able to reproduce the issue on tensorflow v2.10, v2.11 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/7cbeeca7fbd730100159b204ee9c5640/untitled868.ipynb).

Also this one:

```
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_ragged_array_ops
try:
  ragged_values_0_tensor = tf.convert_to_tensor(np.ones([3], dtype=str))
  ragged_values_0 = tf.identity(ragged_values_0_tensor)
  ragged_values = [ragged_values_0,]
  ragged_row_splits_0_tensor = tf.random.uniform([4], minval=-256, maxval=257, dtype=tf.int64)
  ragged_row_splits_0 = tf.identity(ragged_row_splits_0_tensor)
  ragged_row_splits = [ragged_row_splits_0,]
  sparse_indices = []
  sparse_values = []
  sparse_shape = []
  dense_inputs = []
  input_order = "R"
  hashed_output = False
  num_buckets = 0
  hash_key = 0
  out_values_type = 7
  out_row_splits_type = 9
  out = gen_ragged_array_ops.ragged_cross(ragged_values=ragged_values,ragged_row_splits=ragged_row_splits,sparse_indices=sparse_indices,sparse_values=sparse_values,sparse_shape=sparse_shape,dense_inputs=dense_inputs,input_order=input_order,hashed_output=hashed_output,num_buckets=num_buckets,hash_key=hash_key,out_values_type=out_values_type,out_row_splits_type=out_row_splits_type,)
except Exception as e:
  print("Error:"+str(e))
```

**Comment by mihaimaruseac** [comment]
@learning-to-play

**Comment by yongtang** [comment]
Added a PR #59114 for the fix.
