### ISSUE TITLE
Hang when running tensorflow.python.ops.collective_ops.all_gather_v2

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59125]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
Program hangs when running with very large negative input tensor
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import collective_ops
try:
  arg_0_tensor = tf.constant(-72686848303090, shape=[4], dtype=tf.float32,)
  arg_0 = tf.identity(arg_0_tensor)
  arg_1_tensor = tf.random.uniform([], minval=-256, maxval=257, dtype=tf.int32)
  arg_1 = tf.identity(arg_1_tensor)
  arg_2_tensor = tf.random.uniform([], minval=-256, maxval=257, dtype=tf.int32)
  arg_2 = tf.identity(arg_2_tensor)
  arg_3_tensor = tf.random.uniform([], minval=-256, maxval=257, dtype=tf.int32)
  arg_3 = tf.identity(arg_3_tensor)
  communication_hint = "RING"
  out = collective_ops.all_gather_v2(arg_0,arg_1,arg_2,arg_3,communication_hint=communication_hint,)
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
Hangs
```
</details>

**Comment by tilakrayal** [comment]
@nimashiri,
I tried to execute the code on tf-nightly and was executed with the error. `group_size must be a positive integer but got -253`. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/062d4a7c59c344e31bb36a5072d45235/untitled842.ipynb) and also the colab was not hanged while executing the given code. Thank you!

**Comment by nimashiri** [comment]
> @nimashiri, I tried to execute the code on tf-nightly and was executed with the error. `group_size must be a positive integer but got -253`. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/062d4a7c59c344e31bb36a5072d45235/untitled842.ipynb) and also the colab was not hanged while executing the given code. Thank you!

I just ran the code again from my terminal, and I can't kill the program, it seems it stucks or freezes. 
![Screenshot from 2023-01-06 08-50-14](https://user-images.githubusercontent.com/17060581/211033253-6b2cdf73-976b-4d31-94f2-fffa29a871e9.png)

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.9, v2.11 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/d5f7c7c7ff053b416e1c0378a75037f6/untitled888.ipynb).

**Comment by mihaimaruseac** [comment]
Not a vuln, just wrong API usage, behavior conforming to API contract
