### ISSUE TITLE
Build tflite_runtime with custom ops

### ISSUE THREAD

**Issue by ankitmaurya001** [tensorflow/tensorflow#59127]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf 2.7.2

### Custom Code

No

### Python version

3.7

### Current Behaviour?

```shell
Hi,
Has anybody been able to build(cross-compile) tflite_runtime for aarch64 with custom ops?
I tried running for TF 2.7.2. Ref (https://github.com/tensorflow/tensorflow/tree/r2.7/tensorflow/lite/tools/pip_package)
```

### Standalone code to reproduce the issue

```shell
CI_DOCKER_EXTRA_PARAMS="-e CUSTOM_BAZEL_FLAGS=--define=tflite_pip_with_flex=true"   tensorflow/tools/ci_build/ci_build.sh PI-PYTHON37   tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh aarch64
```

### Relevant log output

```shell
2023-01-06 09:48:04 (74.8 MB/s) - 'get-pip.py' saved [2569500/2569500]

/install/install_pip_packages_by_version.sh: line 24: /usr/local/bin/python3.7: No such file or directory
ln: failed to create symbolic link '/usr/include/python3.7/numpy': No such file or directory
The command '/bin/sh -c /install/install_pi_python3x_toolchain.sh "3.7"' returned a non-zero code: 1
ERROR: docker build failed. Dockerfile is at /home/ubuntu/tensorflow/tensorflow/tools/ci_build/Dockerfile.pi-python37
```
</details>

**Comment by mohantym** [comment]
Hi @ankitmaurya001 !
Thanks for reporting this issue. I could replicate this issue in my local machine.

@arfaian!
Could you look at this bug.

Thank you!

**Comment by ankitmaurya001** [comment]
Hi @mohantym @arfaian thanks for considering this issue. If I could get some guidance, I would really appreciate the opportunity to contribute to fixing this bug. Is that something that could be arranged? Just let me know and I'll do my best to help out. Thank you!

**Comment by pjpratik** [comment]
Hi @ankitmaurya001 

As per the [documentation](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package#caveats), currently custom ops and delegates cannot be registered.

>Caveats
You cannot use TensorFlow Select ops, only TensorFlow Lite builtins.
Currently custom ops and delegates cannot be registered.

Thanks.

**Comment by ankitmaurya001** [comment]
Hi @pjpratik but one of the [examples](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package#enable-tf-op-support-flex-delegate) shows how to enable TF OP support.  Is it not supported for aarch64?

**Comment by pjpratik** [comment]
Hi @ankitmaurya001 

The use of Flex OPs is given in the [example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package#enable-tf-op-support-flex-delegate). It is supported for aarch64 as well. 

https://github.com/tensorflow/tensorflow/blob/056987333d10837ab3f087e86c50ba95d85fd77c/tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh#L176

Can you try in latest version and let us know if the issue still persists?

Thanks.
