### ISSUE TITLE
Check failure when running tensorflow.python.ops.gen_array_ops.matrix_diag_part_v3 when feeding input empty tensor

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59122]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

22.04

### Python version

3.9

### Current Behaviour?

```shell
Check failure when running .python.ops.gen_array_ops.matrix_diag_part_v3 when feeding input empty tensor.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_array_ops
try:
  input_tensor = tf.saturate_cast(tf.random.uniform([], minval=0, maxval=2, dtype=tf.int64), dtype=tf.uint64)
  input = tf.identity(input_tensor)
  k = -20
  padding_value = -20
  align = "RIGHT_LEFT"
  out = gen_array_ops.matrix_diag_part_v3(input=input,k=k,padding_value=padding_value,align=align,)
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
2023-01-05 21:40:09.377252: F ./tensorflow/python/eager/pywrap_tensor_conversion.h:58] Check failed: !PyErr_Occurred() 
Aborted
```
```
</details>

**Comment by tilakrayal** [comment]
@nimashiri,
I was able to execute the mentioned code on tensorflow v2.11 ( both [cpu](https://colab.research.google.com/gist/tilakrayal/7d0f8383bbe4d67394c276263b60a0ed/untitled841.ipynb) & gpu ) and was able to execute without any issue/error and the output was also as expected. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/4212b2c3d4ede31976079649f401eef1/untitled841_gpu.ipynb). Thank you!

**Comment by nimashiri** [comment]
> @nimashiri, I was able to execute the mentioned code on tensorflow v2.11 ( both [cpu](https://colab.research.google.com/gist/tilakrayal/7d0f8383bbe4d67394c276263b60a0ed/untitled841.ipynb) & gpu ) and was able to execute without any issue/error and the output was also as expected. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/4212b2c3d4ede31976079649f401eef1/untitled841_gpu.ipynb). Thank you!

Thanks.

**Comment by mihaimaruseac** [comment]
@sushreebarsa https://github.com/tensorflow/tensorflow/issues/59350#issuecomment-1399378528 does not apply. That comment was about user receiving a valid Python error, whereas here (and in several places where the same canned response was used) the user sees the Python process crashing.

CC @learning-to-play

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow [v2.11](https://colab.research.google.com/gist/tilakrayal/4212b2c3d4ede31976079649f401eef1/untitled841_gpu.ipynb) and nightly and the error was Python process crashing. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/8f3c41bc045d1a3d65f5f692b764f9ca/untitled914.ipynb).

**Comment by manojssmk** [comment]
@dmc1778 
I tried to reproduce with python V2.17 and found that Python process crashing is not occurring. Kindly refer the gist [here](https://colab.research.google.com/gist/manojssmk/235ad6cabd965c57e2264717b5a0d8f8/untitled914.ipynb)
