### ISSUE TITLE
Check failure when running tensorflow.python.ops.stateless_random_ops.stateless_random_normal from terminal

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59124]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
Probably because of feeding empty tensors.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import stateless_random_ops
try:
  try:
    with tf.device('/CPU'):
      seed_tensor = tf.complex(tf.random.uniform([1], dtype=tf.float32),tf.random.uniform([1], dtype=tf.float32))
      seed = tf.identity(seed_tensor)
      shape_tensor = tf.random.uniform([], dtype=tf.float64)
      shape = tf.identity(shape_tensor)
      dtype = tf.uint64
      mean = -40
      stddev = -39
      out = stateless_random_ops.stateless_random_normal(seed=seed,shape=shape,dtype=dtype,mean=mean,stddev=stddev,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      seed = tf.identity(seed_tensor)
      seed = tf.cast(seed, tf.complex64)
      shape = tf.identity(shape_tensor)
      shape = tf.cast(shape, tf.float64)
      dtype = tf.uint64
      results["res_gpu"] = stateless_random_ops.stateless_random_normal(seed=seed,shape=shape,dtype=dtype,mean=mean,stddev=stddev,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
Error:<class 'tensorflow.python.framework.ops.EagerTensor'> returned a result with an error set
2023-01-06 00:39:33.309913: F ./tensorflow/python/eager/pywrap_tensor_conversion.h:58] Check failed: !PyErr_Occurred() 
Aborted

```
```
</details>

**Comment by mohantym** [comment]
Hi @nimashiri !
Thanks for sharing your observation on stateless_random_ops.stateless_random_normal  w.r.to Ubuntu 22 and TF 2.11.

I could not replicate this issue in Colab environment with[ 2.11](https://colab.sandbox.google.com/gist/mohantym/5b8a6c34359d0dbf8060939b4c881272/git_59124.ipynb#scrollTo=EYtN4VCiABY_), Cuda 11.2 and CudNN 8.1.

Could you check with TF nightly version , Cuda 11.7 and CudNN 8.2 (Please make sure that Proper GPU driver is installed from Nvidia site )


Thank you!

**Comment by mohantym** [comment]
Hi @nimashiri !

Could you consider this as resolved as original issue is not surfacing. 
I think the error in above [comment](https://github.com/tensorflow/tensorflow/issues/59124#issuecomment-1375799743) is because of Cuda configuration issue (Tested Cuda config might resolve this issue. 2.11 , Cuda 11.2, CudNN 8.1)

Thank you!

**Comment by sushreebarsa** [comment]
@nimashiri This issue is not replicating in latest TF version, could you please check this [gist](https://colab.research.google.com/gist/sushreebarsa/f254c70fe33188ffcb5a86eb76a0e931/git_59124.ipynb) and confirm the same?
Thank you!

**Comment by nimashiri** [comment]
> @nimashiri This issue is not replicating in latest TF version, could you please check this [gist](https://colab.research.google.com/gist/sushreebarsa/f254c70fe33188ffcb5a86eb76a0e931/git_59124.ipynb) and confirm the same? Thank you!
This one has crash:

```
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import stateless_random_ops
try:
  shape_0 = 125091515651
  shape = [shape_0,]
  seed_0 = 12
  seed_1 = 34
  seed = [seed_0,seed_1,]
  counts = 10.0
  probs = 0.4
  output_dtype = tf.float16
  out = stateless_random_ops.stateless_random_binomial(shape=shape,seed=seed,counts=counts,probs=probs,output_dtype=output_dtype,)
except Exception as e:
  print("Error:"+str(e))
```

**Comment by sushreebarsa** [comment]
@dmc1778 Thank you for the update! 
@sachinprasadhs  The code is crashing in TF v2.11. Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/9d587086b15234867eb0cebde771ec40/59124.ipynb). Thank you!

**Comment by mihaimaruseac** [comment]
This is a vulnerability that needs fixing. Please make sure the stalleness labels are not added as that will result in the issue getting closed before team finds time to look at the vulns (which should not be reported here)

@dmc1778 please stop posting vulns on GitHub. Please consult SECURITY.md for how to properly and ethically disclose them.

**Comment by mihaimaruseac** [comment]
@learning-to-play

**Comment by sachinprasadhs** [comment]
Hi, This issue has been addressed by the commit https://github.com/tensorflow/tensorflow/commit/048ad4bb5a843c320c570a4eaed80f92ed18db95 which allows shape tensor to be flattened to appropriate int type.

**Comment by sachinprasadhs** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
