### ISSUE TITLE
Illegal memory access when running tensorflow.python.ops.gen_sparse_ops.sparse_split

### ISSUE THREAD

**Issue by nimashiri** [tensorflow/tensorflow#59121]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

22.04

### Python version

3.9

### Current Behaviour?

```shell
When .sparse_split is given zero as the first input parameter, I get illegal memory access.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import gen_sparse_ops
try:
  try:
    with tf.device('/CPU'):
      arg_0 = 0
      arg_1_tensor = tf.random.uniform([14, 2], minval=-256, maxval=257, dtype=tf.int64)
      arg_1 = tf.identity(arg_1_tensor)
      arg_2_tensor = tf.random.uniform([14], minval=-256, maxval=257, dtype=tf.int64)
      arg_2 = tf.identity(arg_2_tensor)
      arg_3_tensor = tf.random.uniform([2], minval=-256, maxval=257, dtype=tf.int64)
      arg_3 = tf.identity(arg_3_tensor)
      arg_4 = 4
      out = gen_sparse_ops.sparse_split(arg_0,arg_1,arg_2,arg_3,arg_4,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      arg_1 = tf.identity(arg_1_tensor)
      arg_1 = tf.cast(arg_1, tf.int64)
      arg_2 = tf.identity(arg_2_tensor)
      arg_2 = tf.cast(arg_2, tf.int64)
      arg_3 = tf.identity(arg_3_tensor)
      arg_3 = tf.cast(arg_3, tf.int64)
      results["res_gpu"] = gen_sparse_ops.sparse_split(arg_0,arg_1,arg_2,arg_3,arg_4,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
Error:{{function_node __wrapped__SparseSplit_num_split_4_device_/job:localhost/replica:0/task:0/device:CPU:0}} Slice index 60 is larger than num_split. [Op:SparseSplit]
2023-01-05 21:32:38.376771: E tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2023-01-05 21:32:38.377012: F tensorflow/core/common_runtime/device/device_event_mgr.cc:221] Unexpected Event status: 1
Aborted
```
```
</details>

**Comment by mohantym** [comment]
Hi @nimashiri !

Thanks for sharing your observation w.r.to gen_sparse_ops.sparse_split ops.
I could replicate this issue in [2.9](https://colab.sandbox.google.com/gist/mohantym/23d1f819f420e729624c6de77ef629f0/git_59121.ipynb#scrollTo=RODGH2iqf3R6), [2.10](https://colab.sandbox.google.com/gist/mohantym/a56807e0d0b59df54537c36b724cbd80/git_59121.ipynb#scrollTo=VKL-hhhYgAsK), [2.11](https://colab.sandbox.google.com/gist/mohantym/869d266d91ccc339865c59bf02e08525/git_59121.ipynb#scrollTo=RODGH2iqf3R6) and [nightly](https://colab.sandbox.google.com/gist/mohantym/ba060a1fee8ec884a56ed32ad81b4b21/git_59121.ipynb#scrollTo=0FHcsl5UlhLS) .

Thank you!

**Comment by mohantym** [comment]
@nimashiri !
Could you let us know your Cuda configs. 
Tested Cuda version for TF 2.10 and 2.11 is Cuda 11.2 and CudNN is 8.1

[Reference.](https://www.tensorflow.org/install/source#gpu)

Thank you!
