### ISSUE TITLE
tf.nn.crelu Static shape not defined

### ISSUE THREAD

**Issue by rob-rowe** [tensorflow/tensorflow#5912]
Currently (version 0.11.0) the static shape is not defined for crelu. Minimal example:

    f = tf.random_normal([50, 5, 7, 10])

    f2 = tf.nn.crelu(f)
    print(f2.get_shape().as_list())  # [None, None, None, None]

    f3 = tf.nn.relu(f)
    print(f3.get_shape().as_list()) # [50, 5, 7, 10]

**Comment by poxvoculi** [comment]
Fix applied internally at Google.  Should roll out with a subsequent release (after 0.12).
