### ISSUE TITLE
strip_unused assumes all placeholders are the same type

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#5913]
[`strip_unused`](https://github.com/tensorflow/tensorflow/blob/5657d0dee8d87f4594b3e5902ed3e3ca8d6dfc0a/tensorflow/python/tools/strip_unused.py) assumes that all of the placeholders are of the same type which may not be the case. This method is also used by [`optimize_for_inference`](https://github.com/tensorflow/tensorflow/blob/5657d0dee8d87f4594b3e5902ed3e3ca8d6dfc0a/tensorflow/python/tools/optimize_for_inference_lib.py#L82-L85) which leads to errors when the models is loaded:
```
 msg std::__1::string "Input 0 of node dropout6/cond/Switch was passed float from Placeholder_2:0 incompatible with expected bool." 
```

I suggest having an option to introspect the graph to determine type.

**Comment by cancan101** [comment]
For example why is this line:
```python
      placeholder_node.attr["dtype"].CopyFrom(tf.AttrValue(
          type=placeholder_type_enum))
```
not:
```
      placeholder_node.attr["dtype"].CopyFrom(
          node.attr["dtype"]
      )
```

**Comment by lminerPlaid** [comment]
This is definitely a problem for me. My X placeholder is of type `int32` and my dropout keep probability is of type `float32`, so this is unusable for me.

**Comment by skye** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Comment by cancan101** [comment]
this still looks to be relevant.

**Comment by skye** [comment]
@petewarden do you have any plans to fix this? If not, please unassign yourself and mark contributions welcome (if appropriate).

**Comment by petewarden** [comment]
The new graph transform approach fixes this issue:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms/#strip_unused_nodes

We need to update the documentation and code to mark the old strip_unused.py script as deprecated.

**Comment by skye** [comment]
Thanks, I'll close this then.

**Comment by lissyx** [comment]
@petewarden Is `optimize_for_inference` deprecated as well? I see no mention regarding that not even in `strip_unused.py`, so I'm wondering :/
