### ISSUE TITLE
Elaborate on the support of custom_objects in Saved Model for TFX Serving

### ISSUE THREAD

**Issue by racinmat** [tensorflow/tensorflow#59136]
### Issue Type

Documentation Feature Request

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### Python version

3.9

### Current Behaviour?

I have a tensorflow keras model with lots of custom objects, they are all available in `tf.keras.utils.get_custom_objects()`. I am saving and loading the model without any problem using `model.save(path, save_traces=False)` and `tf.keras.models.load_model(path)`, where `model` is a child class of `tf.keras.Model` and it works fine. 
But when I use `tf.saved_model.save(model, path)`, and then load using `tf.saved_model.load(path)`, the custom class is not loaded.

I somewhat understand this might not be supported, but it would be great to have this explicitly stated in the docs.

I tried to dig into differences between the different ways of saving and loading the model, but I'm confused from the docs, the `tf.keras.models.save_model` https://www.tensorflow.org/api_docs/python/tf/keras/models/save_model state that it's using SavedModel format, and when I explicitly state that the `save_format="tf"` should be used, the loading using `tf.keras.models.load_model` properly loads my custom class. But not when using the `saved_model_load`

In the https://github.com/tensorflow/tensorflow/issues/37439#issuecomment-600290097 I found a mention that keras types can be saved, to the SavedModel format, but I have no clue about the compatibility of these things with TFX Serving etc, which would be great to elaborate more. Does the TFX serving require traced model? Is there a way how to use custom objects in the TFX serving?

### Standalone code to reproduce the issue

any code using custom C++ and python wrappers in tf.keras layers which we add as custom objects, e.g.
```python
>>> model =  <some custom child of tf.keras.Model>
>>> tf.saved_model.save(raw_inference_model, 'out_path/gcs_model')
>>> raw_inference_model2 = tf.saved_model.load('out_path/gcs_model')
>>> raw_inference_model2
<tensorflow.python.saved_model.load.Loader._recreate_base_user_object.<locals>._UserObject at 0x7fcdbb657310>

>>> raw_inference_model.save('out_path/gcs_model_k', save_traces=False, save_format='tf')
>>> raw_inference_model3 = keras.models.load_model('out_path/gcs_model_k')
>>> raw_inference_model3
<wannamodel.model.WannaModel at 0x7fcdb82b80d0>
```

**Comment by tilakrayal** [comment]
@racinmat,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by racinmat** [comment]
Ok, and what about the TFX Serving part of my question? Does it belong here?

**Comment by tilakrayal** [comment]
@racinmat,
For TFX Serving related issues, please try to raise the request in this repo from [here](https://github.com/tensorflow/serving) . Thank you!
