### ISSUE TITLE
 cannot import name 'build_info' from 'tensorflow.python.platform'

### ISSUE THREAD

**Issue by Jaswanth28** [tensorflow/tensorflow#59159]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

windows 11 22h2

### Python version

3.10.6

### Bazel version

no

### GPU model and memory

mx150 2gb vram

### Current Behaviour?

```shell
cannot import name 'build_info' from 'tensorflow.python.platform'
```

### Standalone code to reproduce the issue

```shell
cannot import name 'build_info' from 'tensorflow.python.platform'
import tensorflow as tf
from object_detection.utils import config_util
from object_detection.protos import pipeline_pb2
from google.protobuf import text_format
```

### Relevant log output

_No response_</details>

**Comment by Jaswanth28** [comment]
i am trying to do tensrflow object detection project from this repo having problem can u try out the code and give e any fix
https://youtu.be/yqkISICHH-U
https://github.com/nicknochnack/TFODCourse

**Comment by KushKumarK** [comment]
Hey @mohantym , are you still working on this issue, I would like to take on it if is still up for grabs.

**Comment by sushreebarsa** [comment]
@Jaswanth28 I was able to import the name 'build_info' from 'tensorflow.python.platform' using tf-nightly on colab, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/e6ad9de7873684d5d7cfefef3b7ab961/untitled748.ipynb#scrollTo=SR3tH1cgyXKa) and confirm the same?
Thank you!
