### ISSUE TITLE
[Documentation] raw_ops.Conv3D: strides cannot be a list of ints that has length >= 5

### ISSUE THREAD

**Issue by hmahmood24** [tensorflow/tensorflow#59156]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04.5 LTS WSL2

### Python version

3.8.10

### Current Behaviour?

```shell
The documentation for raw_ops.Conv3D states that strides must be a list of ints that has length >= 5, which is immediately followed by another statement stating that strides must be a 1-D tensor of length 5. Both of these statements are partly contradictory to each other since strides cannot be a list that has length > 5 but instead a list that has length == 5. The latter statement is the correct one while the former one should either be removed from the documentation due to redundancy/false information or corrected if kept.
```

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf

x_in = np.random.randn(1,3,3,3,1)
kernel_in = np.random.randn(3,3,3,1,1)
x = tf.constant(x_in, dtype=tf.float32)
kernel = tf.constant(kernel_in, dtype=tf.float32)

tf.raw_ops.Conv3D(input=x, filter=kernel, strides=[1,1,1,1,1,1], padding="SAME", data_format="NDHWC", dilations=[1,1,1,1,1])
```

### Relevant log output

```shell
InvalidArgumentError: {{function_node __wrapped__Conv3D_device_/job:localhost/replica:0/task:0/device:CPU:0}} Sliding window strides field must specify 5 dimensions [Op:Conv3D]
```
</details>

**Comment by SuryanarayanaY** [comment]
@hmahmood24 ,
Thanks for bringing this document bug to our notice.The document needs correction.Will do that and confirm.

**Comment by SuryanarayanaY** [comment]
Hi @hmahmood24 ,
An internal Ticket has been raised to correct this doc bug which is under review.
Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @hmahmood24 ,
The doc bug already rectified in our internal systems. The change might be reflected in next release.

Please refer to attached snapshot below for the change. 

<img width="695" alt="Screenshot 2023-03-08 at 2 14 32 PM" src="https://user-images.githubusercontent.com/116063290/223666289-c262978b-d752-4a03-a2cf-f75ce5c900d5.png">

Thanks!

**Comment by hmahmood24** [comment]
Hi @SuryanarayanaY,

Awesome! Thanks for keeping me in the loop. Please feel free to close the issue as convenient.
Cheers!

**Comment by SuryanarayanaY** [comment]
Hi @hmahmood24 ,

Thanks for confirmation. Please close the issue if Ok from your side. Thanks!
