### ISSUE TITLE
Crash when running linalg_ops.matrix_solve_ls and gen_linalg_ops.matrix_solve_ls

### ISSUE THREAD

**Issue by nimashiri** [tensorflow/tensorflow#59171]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
Crash when running .matrix_solve_ls
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import linalg_ops
try:
  try:
    with tf.device('/CPU'):
      arg_0_tensor = tf.random.uniform([16, 8, 127], dtype=tf.float64)
      arg_0 = tf.identity(arg_0_tensor)
      arg_1_tensor = tf.random.uniform([16, 8, 127], dtype=tf.float64)
      arg_1 = tf.identity(arg_1_tensor)
      fast = False
      l2_regularizer = -0.1830422440453151
      out = linalg_ops.matrix_solve_ls(arg_0,arg_1,fast=fast,l2_regularizer=l2_regularizer,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      arg_0 = tf.identity(arg_0_tensor)
      arg_0 = tf.cast(arg_0, tf.float64)
      arg_1 = tf.identity(arg_1_tensor)
      arg_1 = tf.cast(arg_1, tf.float64)
      linalg_ops.matrix_solve_ls(arg_0,arg_1,fast=fast,l2_regularizer=l2_regularizer,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```

And:

```
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_linalg_ops
try:
  arg_0_tensor = tf.complex(tf.random.uniform([16, 8, 64], dtype=tf.float64),tf.random.uniform([16, 8, 64], dtype=tf.float64))
  arg_0 = tf.identity(arg_0_tensor)
  arg_1_tensor = tf.complex(tf.random.uniform([16, 8, 64], dtype=tf.float64),tf.random.uniform([16, 8, 64], dtype=tf.float64))
  arg_1 = tf.identity(arg_1_tensor)
  arg_2 = -0.24630198634734735
  fast = False
  out = gen_linalg_ops.matrix_solve_ls(arg_0,arg_1,arg_2,fast=fast,)
except Exception as e:
  print("Error:"+str(e))
```

### Relevant log output

```shell
free(): unaligned chunk detected in tcache 2
Aborted
```
```
</details>

**Comment by sushreebarsa** [comment]
@nimashiri I tried to replicate the issue in colab using tf-nightly, and didn't face the error reported. Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/7b03d41f25b35248e64786f9ca780d1b/untitled746.ipynb#scrollTo=OxVm7UOdycq2) and confirm the same.
Thank you!

**Comment by nimashiri** [comment]
> @nimashiri I tried to replicate the issue in colab using tf-nightly, and didn't face the error reported. Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/7b03d41f25b35248e64786f9ca780d1b/untitled746.ipynb#scrollTo=OxVm7UOdycq2) and confirm the same. Thank you!

This bug is for tf-2.1, did you test on 2.10?

**Comment by sushreebarsa** [comment]
@nimashiri I tested the bug in the latest tf-nightly(2.12.0.dev2023010808). If the bug s for tf-2.1 please upgrade it to latest as older TF versions are not actively supported.
Thank you!

**Comment by nimashiri** [comment]
> @nimashiri I tested the bug in the latest tf-nightly(2.12.0.dev2023010808). If the bug s for tf-2.1 please upgrade it to latest as older TF versions are not actively supported. Thank you!

Just updated my reply. The issue is for 2.10.

**Comment by sushreebarsa** [comment]
@nimashiri  This issue is not replicating in latest version so it will be fixed in the next release.
Thank you!
