### ISSUE TITLE
Segfault when running tensorflow.python.ops.math_ops.sobol_sample

### ISSUE THREAD

**Issue by nimashiri** [tensorflow/tensorflow#59178]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
Segmentation fault on very large input arguments.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import math_ops
try:
  arg_0 = 5
  arg_1 = 125091515651
  dtype = None
  out = math_ops.sobol_sample(arg_0,arg_1,dtype=dtype,)
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@nimashiri Could you please have a look at the outcome I faced while reproducing this issue on tf-nightly. Please find the [gist](https://colab.research.google.com/gist/sushreebarsa/78cf78e559ff5818c568c44d10fe70ca/59178.ipynb#scrollTo=qKgG077I6Fub) as well. 
```
Error:{{function_node __wrapped__SobolSample_device_/job:localhost/replica:0/task:0/device:CPU:0}} num_results*dim must be less than 2147483647 [Op:SobolSample]

```
Thank you!

**Comment by nimashiri** [comment]
> @nimashiri Could you please have a look at the outcome I faced while reproducing this issue on tf-nightly. Please find the [gist](https://colab.research.google.com/gist/sushreebarsa/78cf78e559ff5818c568c44d10fe70ca/59178.ipynb#scrollTo=qKgG077I6Fub) as well.
> 
> ```
> Error:{{function_node __wrapped__SobolSample_device_/job:localhost/replica:0/task:0/device:CPU:0}} num_results*dim must be less than 2147483647 [Op:SobolSample]
> ```
> 
> Thank you!

This issue is for 2.10.
