### ISSUE TITLE
Broken link in "A Tool Developer's Guide..." for graph_metrics.py

### ISSUE THREAD

**Issue by voyageth** [tensorflow/tensorflow#5917]
In [this page](https://www.tensorflow.org/versions/master/how_tos/tool_developers/index.html), 
graph_metrics.py link broken. graph_metrics.py is deleted by [this commit](https://github.com/tensorflow/tensorflow/commit/d8c94dba8f53626077b21f90df309577827a0f18#diff-2839c4fb2e611a1359978388f55f3583).

**Comment by poxvoculi** [comment]
Thanks for the report.  Internal bug opened, but community fix welcome also.

**Comment by AnishShah** [comment]
Is anyone working on this internally? I can work on this. If yes, then should I just remove that line or replace it with a link to some other file?

**Comment by poxvoculi** [comment]
So far as I know, no one is working on it yet.  @danmane ?
