### ISSUE TITLE
Segfault when running tensorflow.python.ops.gen_sparse_ops.sparse_concat

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59177]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
Segfault probably due to dimension mismatch on input tensor parameters.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_sparse_ops
try:
  arg_0 = []
  arg_1_0_tensor = tf.random.uniform([], dtype=tf.float32)
  arg_1_0 = tf.identity(arg_1_0_tensor)
  arg_1_1_tensor = tf.random.uniform([], dtype=tf.float32)
  arg_1_1 = tf.identity(arg_1_1_tensor)
  arg_1 = [arg_1_0,arg_1_1,]
  arg_2_0_tensor = tf.random.uniform([], minval=-256, maxval=257, dtype=tf.int64)
  arg_2_0 = tf.identity(arg_2_0_tensor)
  arg_2_1_tensor = tf.random.uniform([], minval=-256, maxval=257, dtype=tf.int64)
  arg_2_1 = tf.identity(arg_2_1_tensor)
  arg_2 = [arg_2_0,arg_2_1,]
  arg_3 = -2
  out = gen_sparse_ops.sparse_concat(arg_0,arg_1,arg_2,arg_3,)
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
Segmentation fault
```
</details>

**Comment by tilakrayal** [comment]
@nimashiri,
I tried to execute the mentioned code on tensorflow v2.11 and I didn't face any Segfault error as mentioned. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/65704691fbdf88b8b900c915ae6168a2/untitled848.ipynb).

**Comment by tilakrayal** [comment]
@nimashiri,
As it was the bug on tensorflow v2.10, it has been resolved on the latest stable tensorflow v2.11 where we can observe that Segfault error has not arised. Thank you!

**Comment by tilakrayal** [comment]
@nimashiri,
Yeah, As mentioned above it was the bug on tensorflow v2.10 where we were able to receive the SegFault error.
**2.10**: 
![image](https://user-images.githubusercontent.com/81610181/216577624-dcc150f3-5518-4757-bb6e-4f027d9234a8.png)
 
But where as on tensorflow v2.11, the same code was executed without the Segfault error and the output error which was as expected mentioning the arg shapes providing to the tensor are not as required. 
**2.11**:
![image](https://user-images.githubusercontent.com/81610181/216579141-6a5d2f31-c20e-4d07-9158-3753bbbd7fd2.png)

Also please find the gist of the both [v2.10](https://colab.research.google.com/gist/tilakrayal/3bca1a94768e7e14c933ba474dc62cef/2-1000000.ipynb) and [v2.11](https://colab.research.google.com/gist/tilakrayal/adf16a9d8966dd03b10550169587f60b/2-1111111.ipynb) for the reference. Thank you!

**Comment by mihaimaruseac** [comment]
Closing as fixed vuln.

@dmc1778 please stop posting vulns on GitHub. Please consult SECURITY.md for how to properly and ethically disclose them.
