### ISSUE TITLE
add convert_placeholders_to_constants to tensorflow

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#5918]
Add `convert_placeholders_to_constants` which permanently injects a constant to fill in the value of a Placeholder.

Repost from [SO](http://stackoverflow.com/questions/40852729/permanently-inject-constant-into-tensorflow-graph-for-inference/40852855). /CC @mrry

**Comment by alextp** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
