### ISSUE TITLE
Crash when running gen_nn_ops.max_pool

### ISSUE THREAD

**Issue by nimashiri** [tensorflow/tensorflow#59191]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
Check failure with the following input combination.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_nn_ops
try:
  arg_0_tensor = tf.random.uniform([1, 10, 14, 1], dtype=tf.float32)
  arg_0 = tf.identity(arg_0_tensor)
  ksize_0 = 1
  ksize_1 = -1
  ksize_2 = 2
  ksize_3 = 1
  ksize = [ksize_0,ksize_1,ksize_2,ksize_3,]
  strides_0 = 1
  strides_1 = 2
  strides_2 = 2
  strides_3 = 1
  strides = [strides_0,strides_1,strides_2,strides_3,]
  padding = "VALID"
  explicit_paddings = []
  data_format = "NHWC"
  out = gen_nn_ops.max_pool(arg_0,ksize=ksize,strides=strides,padding=padding,explicit_paddings=explicit_paddings,data_format=data_format,)
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
2023-01-09 11:10:47.659984: F tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:958] Check failed: cudnnSetPoolingNdDescriptor( handle_.get(), (pooling_descriptor.mode() == dnn::PoolingMode::kMaximum ? cudnn_max_pooling_mode : CUDNN_POOLING_AVERAGE_COUNT_EXCLUDE_PADDING), propagate_nans ? CUDNN_PROPAGATE_NAN : CUDNN_NOT_PROPAGATE_NAN, nd, shape.data(), padding.data(), strides.data()) == CUDNN_STATUS_SUCCESS (3 vs. 0)
Aborted

```
```
</details>

**Comment by mohantym** [comment]
Hi @nimashiri !
Thanks for sharing your observation w.r.to Ubuntu22 and gen_nn_ops.max_pool .
But I am getting a different error in both Colab 2.11 (CPU) and Ubuntu22 (GPU)

`Error:{{function_node __wrapped__MaxPool_device_/job:localhost/replica:0/task:0/device:CPU:0}} Sliding window ksize for dimension 1 was zero. [Op:MaxPool]`

[Ubuntu22 GCP](https://user-images.githubusercontent.com/86464649/211740616-37d81ff4-763d-4303-a9d1-bc4f66344fb1.png)

for [2.11 GPU ](https://colab.sandbox.google.com/gist/mohantym/ec4a8c69d24e9731a920489e6e4d0e5e/git_59191.ipynb#scrollTo=yEEkgjpLsFRR), Colab runtime is Crashing.

Thank you!
