### ISSUE TITLE
strip_unused should remove Switch Node with Constant Input

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#5919]
`strip_unused` does not appear to remove a `Switch` node with constant input.

**Comment by cancan101** [comment]
I am thinking the solution looks something like this:
```python
nodes = {}
for node in temp_graph_def.node:
    nodes[node.name] = node

for node in temp_graph_def.node:
    if node.op == 'Switch':
        pred = nodes[node.input[1]]
        if pred.op == 'Const' and pred.attr['value'].tensor.bool_val[0] is False:
            pass
```

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by cancan101** [comment]
I think this is still relevant and "active" in that it was referenced by https://github.com/tensorflow/tensorflow/issues/8404.

**Comment by futurely** [comment]
This workaround works for me.
https://stackoverflow.com/a/43627334

**Comment by girving** [comment]
@cancan101 Happy to reopen if you're planning to submit a PR.  Otherwise it looks like this contributions welcome issue is being ignored.

**Comment by zaneoliver6** [comment]
Hey guys! I've been having the same problem trying to make this work on android and I have used some of the solutions from above but none seem to work...here are some of the errors I get back from the various methods of trying to solve this problem...Any Help would be appreciated! 

The models work when I run it on python but doesn't when I run them on android.

Im using the SSD_Mobilenet model from tensorflow object detection api.

**This is from the optimize for inference function:** 
NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: Preprocessor/map/while/add/y = Const[dtype=DT_INT32, value=Tensor<type: int32 shape: [] values: 1>](Preprocessor/map/while/Switch:1)

**This is from renaming Switch to Identify:**
Not a valid TensorFlow Graph serialization: Node 'Preprocessor/map/while/add/y': Connecting to invalid output 1 of source node Preprocessor/map/while/Switch which has 1 outputs

**This last one loads the model but crashes when processing the inputs:**
java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'Switch' with these attrs.  Registered devices: [CPU], Registered kernels:
                                                                    device='GPU'; T in [DT_STRING]
                                                                    device='GPU'; T in [DT_BOOL]
                                                                    device='GPU'; T in [DT_INT32]
                                                                    device='GPU'; T in [DT_FLOAT]
                                                                    device='CPU'; T in [DT_FLOAT]
                                                                    device='CPU'; T in [DT_INT32]
                                                                  
                                                                  	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/PadOrClipBoxList/cond/Switch = Switch[T=DT_BOOL](Postprocessor/BatchMultiClassNonMaxSuppression/PadOrClipBoxList/Greater, Postprocessor/BatchMultiClassNonMaxSuppression/PadOrClipBoxList/Greater)]]
                                                                      
Any ideas guys? I've also tried to recompile tensorflow with the changes from [https://stackoverflow.com/questions/40855271/no-opkernel-was-registered-to-support-op-switch-with-these-attrs-on-ios/43627334#43627334](url) but bazel crashes while compiling :(

**Comment by alextp** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
