### ISSUE TITLE
Double free when running 

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59192]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
Double free.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import nn_ops
try:
  arg_0_tensor = tf.random.uniform([3, 30, 50, 3], dtype=tf.float64)
  arg_0 = tf.identity(arg_0_tensor)
  arg_1_0 = 2
  arg_1_1 = 3
  arg_1_2 = 1
  arg_1_3 = 1
  arg_1 = [arg_1_0,arg_1_1,arg_1_2,arg_1_3,]
  arg_2 = True
  arg_3 = True
  seed = 341261001
  out = nn_ops.fractional_avg_pool_v2(arg_0,arg_1,arg_2,arg_3,seed=seed,)
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
Error:Value for attr 'T' of bool is not in the list of allowed values: float, double, int32, int64
	; NodeDef: {{node FractionalAvgPool}}; Op<name=FractionalAvgPool; signature=value:T -> output:T, row_pooling_sequence:int64, col_pooling_sequence:int64; attr=pooling_ratio:list(float),min=4; attr=pseudo_random:bool,default=false; attr=overlapping:bool,default=false; attr=deterministic:bool,default=false; attr=seed:int,default=0; attr=seed2:int,default=0; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE, DT_INT32, DT_INT64]> [Op:FractionalAvgPool]
Error:Value for attr 'T' of bool is not in the list of allowed values: float, double, int32, int64
	; NodeDef: {{node FractionalAvgPool}}; Op<name=FractionalAvgPool; signature=value:T -> output:T, row_pooling_sequence:int64, col_pooling_sequence:int64; attr=pooling_ratio:list(float),min=4; attr=pseudo_random:bool,default=false; attr=overlapping:bool,default=false; attr=deterministic:bool,default=false; attr=seed:int,default=0; attr=seed2:int,default=0; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE, DT_INT32, DT_INT64]> [Op:FractionalAvgPool]
Error:Value for attr 'T' of bool is not in the list of allowed values: float, double, int32, int64
	; NodeDef: {{node FractionalAvgPool}}; Op<name=FractionalAvgPool; signature=value:T -> output:T, row_pooling_sequence:int64, col_pooling_sequence:int64; attr=pooling_ratio:list(float),min=4; attr=pseudo_random:bool,default=false; attr=overlapping:bool,default=false; attr=deterministic:bool,default=false; attr=seed:int,default=0; attr=seed2:int,default=0; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE, DT_INT32, DT_INT64]> [Op:FractionalAvgPool]
double free or corruption (!prev)
Aborted

```
```
</details>

**Comment by mihaimaruseac** [comment]
This is serious and will need fixing

**Comment by tilakrayal** [comment]
@nimashiri,
I was able to execute the mentioned code without any issue/error on tensorflow v2.11( both [CPU](https://colab.research.google.com/gist/tilakrayal/a329a81c92cb45da3e9c552bbd4229db/untitled860_cpu.ipynb) and GPU). Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/f2ec2dff07e069fe7fcc297d19f57d25/untitled860.ipynb) and let us know. Thank you!

**Comment by nimashiri** [comment]
> @tilakrayal Security issues sometimes manifest by running the code multiple times. If you run the same cell multiple times you will get the session crashing.

Exactly, another case is multiple security issues relates only for one API.

**Comment by SuryanarayanaY** [comment]
Replicated the behaviour on a Ubuntu VM.Please refer to snapshot below.

<img width="1501" alt="Screenshot 2023-01-12 at 8 59 56 PM" src="https://user-images.githubusercontent.com/116063290/212109891-02c240a2-18a6-4edb-ab50-f530da6ce867.png">

**Comment by mihaimaruseac** [comment]
@learning-to-play

**Comment by sachinprasadhs** [comment]
Hi, The issue has been addressed in the commit https://github.com/tensorflow/tensorflow/commit/ee50d1e00f81f62a4517453f721c634bbb478307 and now it throws an error as 
`Error:{{function_node __wrapped__FractionalAvgPool_device_/job:localhost/replica:0/task:0/device:CPU:0}} Fractional average pooling is not yet supported on the batch nor channel dimension. [Op:FractionalAvgPool]`
Please find the attached gist [here](https://gist.github.com/sachinprasadhs/5eef3238b0e6e8f4ee5c6a38045605e5) for reference.
