### ISSUE TITLE
Check failure when running tensorflow.python.ops.gen_sparse_ops.sparse_to_dense

### ISSUE THREAD

**Issue by nimashiri** [tensorflow/tensorflow#59199]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
Check failure.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_sparse_ops
try:
  arg_0_tensor = tf.random.uniform([10], minval=-256, maxval=257, dtype=tf.int32)
  arg_0 = tf.identity(arg_0_tensor)
  arg_1_tensor = tf.random.uniform([], minval=-256, maxval=257, dtype=tf.int32)
  arg_1 = tf.identity(arg_1_tensor)
  arg_2_tensor = tf.saturate_cast(tf.random.uniform([], minval=0, maxval=2, dtype=tf.int64), dtype=tf.uint64)
  arg_2 = tf.identity(arg_2_tensor)
  default_value = -1
  validate_indices = False
  out = gen_sparse_ops.sparse_to_dense(arg_0,arg_1,arg_2,default_value=default_value,validate_indices=validate_indices,)
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
2023-01-09 16:19:19.624081: F ./tensorflow/python/eager/pywrap_tensor_conversion.h:58] Check failed: !PyErr_Occurred() 
Aborted

```
```
</details>

**Comment by mohantym** [comment]
Hi @nimashiri !
Thanks for sharing your observation w.r.to gen_sparse_ops.sparse_to_dense. 

I am getting below error for [2.10](https://colab.sandbox.google.com/gist/mohantym/b2cb24ec5451bf5fc137dda457577d32/git_59199.ipynb#scrollTo=mS_5s6DSIjnR), [2.11](https://colab.sandbox.google.com/gist/mohantym/fd321ab82766a5d6db686956cd79ec0b/git_59199.ipynb#scrollTo=3UlwvZxeLNCB) and [2.12dev](https://colab.sandbox.google.com/gist/mohantym/4629f0781ddb787c01f7c8d432da2528/git_59199.ipynb) for colab and [Ubuntu 22.04  ](https://user-images.githubusercontent.com/86464649/211607512-3baa57d1-5d10-48b6-bd27-ea13f1fb1eb5.png)

`output_shape must be rank 1, got shape []
`

Could you test with high level api "tf.compat.v1.sparse_to_dense" and let us know.

Thank you!
