### ISSUE TITLE
How can I get Bazel to build iteratively?

### ISSUE THREAD

**Issue by cinjon** [tensorflow/tensorflow#592]
In 0.5.0, I could change files (e.g. tensorflow/models/rnn/seq2seq.py) and recompile iteratively with no problem. In 0.6.0, making changes in files like tensorflow/python/ops/rnn_cell.py, etc, gives me pretty long recompile times. I'm not sure that it's doing a full rebuild, but it's def not the snappy few second rebuilds I was experiencing before. I didn't see an issue about this and so I'm wondering if it's something with my setup. Is this a common problem?

**Comment by skearnes** [comment]
AFAIK you don't need to recompile after making changes to python files; the built binary in bazel-bin just points the interpreter at the current version of the source file.

**Comment by cinjon** [comment]
I believe that only applies if you're using bazel straight up to run as well. I am building into a pip pckg.

**Comment by cinjon** [comment]
I now can't seem to reproduce this even though it was happening consistently up till this morning. I'm not sure what's different now :/
