### ISSUE TITLE
Make activation function support sparse tensors

### ISSUE THREAD

**Issue by llhe** [tensorflow/tensorflow#5920]
Usually, the input features need to be normalized, for example, when the feature is *duration of app usage* in *wide and deep* model. Usually you are not clear which normalization function is best for your model when you generate the features. So in the model, an activation function(for example softsign) can be applied to the input first. Currently sparse tensor is not supported. This change can be trivial.

**Comment by leaderj1001** [comment]
I don't know what you say. Because, I can't understand sentence that is 'Currently sparse tensor is not supported.'

You can see website.
https://www.tensorflow.org/versions/r0.12/api_docs/python/sparse_ops/sparse_tensor_representation#SparseTensor

Can you please comment for me?

Thank you.

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
