### ISSUE TITLE
Request: Some way to initialise a dynamically-sized state variable in TFLite

### ISSUE THREAD

**Issue by petered** [tensorflow/tensorflow#59217]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **All**
- TensorFlow installed from (source or binary): **Binary**
- TensorFlow version (or github SHA if from source): **2.9.1**

**Provide the text output from tflite_convert**
```
tensorflow.python.ops.op_selector.UnliftableError: Unable to lift tensor <tf.Tensor 'zeros:0' shape=(None, None) dtype=float32> because it depends transitively on placeholder <tf.Operation 'arr' type=Placeholder> via at least one path, e.g.: zeros (Fill) <- Shape (Shape) <- arr (Placeholder)
```

**Standalone code to reproduce the issue** 

I want to define a stateful graph where the shape of the state variable is defined when model is LOADED, not when it's saved.

As a simple example - lets say I just want to compute a temporal difference - ie. a graph that returns the difference between the input in two consecutive calls. The following should pass:

```
func = load_tflite_model_func(tflite_model_file_path)
runtime_shape = 60, 80
rng = np.random.RandomState(1234)
ims = [rng.randn(*runtime_shape).astype(np.float32) for _ in range(3)]
assert np.allclose(func(ims[0]), ims[0])
assert np.allclose(func(ims[1]), ims[1]-ims[0])
assert np.allclose(func(ims[2]), ims[2]-ims[1])
```

However as far as I know there is not way I can save a model, or define some function `load_tflite_model_func` for loading it, that would make this work for any `runtime_shape`, because variables in the graph can only be saved with a pre-determined size.   

A full stand-alone notebook demonstrating the issue is here:
https://colab.research.google.com/drive/19CwkF1MSGlfMXKxlrndCNqTv7V4fx55Q

**Request is for TFLite to be able to initialise state-variables, where the shape of the initialised variable can depend on the input-shape**

See also https://stackoverflow.com/questions/75052366/how-do-i-to-save-a-stateful-tflite-model-where-shape-of-state-depends-on-input

**Comment by tiruk007** [comment]
@petered 
Given Colab is not accessible. Could you please provide complete code or Colab gist to replicate the issue reported here?
Thank you!

**Comment by petered** [comment]
My mistake - I shared the Colab Notebook

**Comment by petered** [comment]
Great - thank you for following up.  I'm still unsure if there is a way to do this in Tensorflow Lite
- If there is, it would benefit from better documentation
- If there is not, I think it would be a very useful feature to have.

**Comment by mohantym** [comment]
Hi @petered !
We can resize the tensor input by below command which will resize the image inputs automatically according to originals lite input shape. 
`interpreter.resize_tensor_input(0, [30, 40 ])
`
Attached resolved gist in [2.9](https://colab.sandbox.google.com/gist/mohantym/72e22b316aadfa6b055799374a43cfb9/untitled77.ipynb#scrollTo=70cUQbtM_cSb), 2.10 and [2.11](https://colab.sandbox.google.com/gist/mohantym/f03ceabc3840eb474be4d85bc50b19a5/untitled77.ipynb#scrollTo=70cUQbtM_cSb) for reference.

We can do the same using model binding feature from Android studio.  Do you suggest any PR in this [section](https://www.tensorflow.org/lite/guide/inference#running_a_model). 
Thank you!

**Comment by petered** [comment]
Thank you for your response @mohantym.  

I looked at the modified notebook you provided, but I believe it does not resolve the issue.  

The reason it works in [your notebook](https://colab.research.google.com/gist/mohantym/f03ceabc3840eb474be4d85bc50b19a5/untitled77.ipynb#scrollTo=70cUQbtM_cSb) is because you just changed the test so runtime shape to be identical to the compile-time shape.  The desired behaviour is that the function is able to run for any compile-time shape.  I've [modified your notebook](https://colab.research.google.com/drive/1oGrBMWMLwyNNU4iSC3GQTKvVhdnEpGVH#scrollTo=70cUQbtM_cSb) to use a different runtime-shape, and you can see it now fails.  

To clarify... I am looking (in this example) to load a tflite model that can can implement a simple temporal difference, regardless of the shape of the input:
```
runtime_shape = 60, 80
func = load_tflite_model_func(tflite_model_file_path, input_shape=runtime_shape)
rng = np.random.RandomState(1234)
ims = [rng.randn(*runtime_shape).astype(np.float32) for _ in range(3)]
assert np.allclose(func(ims[0]), ims[0])
assert np.allclose(func(ims[1]), ims[1]-ims[0])
assert np.allclose(func(ims[2]), ims[2]-ims[1])
```
If I were to implement it in pure python, the solution would be 
```
class DeltaT:
  def __init__(self): 
    self._last = 0
  def __call__(self, x): 
    delta = x-self._last
    self._last = x 
    return delta 
    
    ...
    func = DeltaT()
```

Is there a way to do this with Tensorflow Lite?

**Comment by mohantym** [comment]
@petered !

Thanks for the update. 

Auto-casting to the original shape in model would be a nice feature to have which are normally doing that through [model binding](https://www.tensorflow.org/lite/inference_with_metadata/codegen#mlbinding) from android studio and  [metadata writer ](https://www.tensorflow.org/lite/models/convert/metadata_writer_tutorial)(by inputting metadata like input shape).


@sachinprasadhs !
Could you look this feature request.

Thank you!

**Comment by petered** [comment]
To clarify - Auto-casting to the original shape in model is not what I'm asking for.  I'm asking for the ability to either initialise a variable in the model according to the input shape - or failing that, resize the saved variable according to the input shape, at time of loading the model.  See the example code above.

I just found out about model-binding in Android studio - from my understanding it just generates wrapper classes for the model.  I'm not sure how this would help - unless you're thinking of modifying the model to return the values of state variables and store them in a Java object instead - feeding them in to each function call - is that what you mean?

**Comment by petered** [comment]
So is there really no way to change the shape of variables in a tflite Interpreter?

**Comment by petered** [comment]
Ok well I found a solution that isn't ideal but does the job: Make the variable the largest size it could conceivably be at runtime, and just take and assign a slice of it.  [Here is a modified notebook](https://colab.research.google.com/drive/1oGrBMWMLwyNNU4iSC3GQTKvVhdnEpGVH?usp=sharing) that does that.

A downside of this approach is that you end up with very large tflite-files (in my case, 24MB of zeros).  

This issue remains - TFLite should provide some way to assign values to variables and reshape the downstream tensors, for example:

```
interpreter.resize_tensor_input(0, input_shape)

index_of_last_input_storage_var: int = 5  # e.g. look this up by name from interpreter.get_tensor_details()
interpreter.assign_variable(index_of_last_input_storage_var, np.zeros(input_shape, dtype=float32)  
# ... the above method does not exist but should

interpreter.allocate_tensors()  # Allocate shapes downstream of both input and variables.
```

**Comment by sachinprasadhs** [comment]
Thanks for sharing your solution, this would help others who will have the same issue. 
Could you please close the issue if you don't have any further question. Thanks

**Comment by pkgoogle** [comment]
Hi @petered,

Because the design philosophy of Tensorflow is to have immutable tensors, implementing this for TFLite which will be consistent with its design philosophy of being lightweight and high performance will be quite a heavy load. As such we do not plan to implement this feature in the near future and will close this issue for now. Please utilize the workaround for now.
