### ISSUE TITLE
tf.debugging.enable_check_numerics() doesn't work with XLA JIT compilation

### ISSUE THREAD

**Issue by JonasAmrich** [tensorflow/tensorflow#59215]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8.10

### CUDA/cuDNN version

CUDA=11.7 CUDNN=8.5.0.96-1

### GPU model and memory

Tesla T4

### Current Behaviour?

```shell
Training fails on following error when `tf.debugging.enable_check_numerics()` is enabled together with JIT compilation of model.

I was able to reproduce this with TF 2.9.2, 2.11.0 and current nightly build, on Tesla T4 and GeForce GTX 1080 Ti.


InvalidArgumentError: Graph execution error:

Detected unsupported operations when trying to compile graph __inference_run_step_1284[] on XLA_GPU_JIT: DebugNumericSummaryV2 (No registered 'DebugNumericSummaryV2' OpKernel for XLA_GPU_JIT devices compatible with node {{node DebugNumericSummaryV2}}){{node DebugNumericSummaryV2}}
```
```


### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

tf.debugging.enable_check_numerics()

# https://keras.io/examples/vision/mnist_convnet/

num_classes = 10
input_shape = (28, 28, 1)
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
x_train = x_train.astype("float32") / 255
x_test = x_test.astype("float32") / 255
x_train = np.expand_dims(x_train, -1)
x_test = np.expand_dims(x_test, -1)
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

model = keras.Sequential(
    [
        keras.Input(shape=input_shape),
        layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
        layers.MaxPooling2D(pool_size=(2, 2)),
        layers.Flatten(),
        layers.Dropout(0.5),
        layers.Dense(num_classes, activation="softmax"),
    ]
)

batch_size = 128
epochs = 15
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"], jit_compile=True)
model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)
```

### Relevant log output

```shell
Epoch 1/15
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-5-1059bcc7b5d0> in <module>
     26 
     27 model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"], jit_compile=True)
---> 28 model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)

1 frames
/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     52   try:
     53     ctx.ensure_initialized()
---> 54     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     55                                         inputs, attrs, num_outputs)
     56   except core._NotOkStatusException as e:

InvalidArgumentError: Graph execution error:

Detected unsupported operations when trying to compile graph __inference_run_step_1284[] on XLA_GPU_JIT: DebugNumericSummaryV2 (No registered 'DebugNumericSummaryV2' OpKernel for XLA_GPU_JIT devices compatible with node {{node DebugNumericSummaryV2}}){{node DebugNumericSummaryV2}}
The op is created at: 
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
  return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
  exec(code, run_globals)
File "/usr/local/lib/python3.8/dist-packages/ipykernel_launcher.py", line 16, in <module>
  app.launch_new_instance()
File "/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py", line 992, in launch_instance
  app.start()
File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelapp.py", line 612, in start
  self.io_loop.start()
File "/usr/local/lib/python3.8/dist-packages/tornado/platform/asyncio.py", line 149, in start
  self.asyncio_loop.run_forever()
File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
  self._run_once()
File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
  handle._run()
File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
  self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 690, in <lambda>
  lambda f: self._run_callback(functools.partial(callback, future))
File "/usr/local/lib/python3.8/dist-packages/tornado/ioloop.py", line 743, in _run_callback
  ret = callback()
File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 787, in inner
  self.run()
File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 748, in run
  yielded = self.gen.send(value)
File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 381, in dispatch_queue
  yield self.process_one()
File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 225, in wrapper
  runner = Runner(result, future, yielded)
File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 714, in __init__
  self.run()
File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 748, in run
  yielded = self.gen.send(value)
File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 365, in process_one
  yield gen.maybe_future(dispatch(*args))
File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 209, in wrapper
  yielded = next(result)
File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
  yield gen.maybe_future(handler(stream, idents, msg))
File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 209, in wrapper
  yielded = next(result)
File "/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py", line 543, in execute_request
  self.do_execute(
File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 209, in wrapper
  yielded = next(result)
File "/usr/local/lib/python3.8/dist-packages/ipykernel/ipkernel.py", line 306, in do_execute
  res = shell.run_cell(code, store_history=store_history, silent=silent)
File "/usr/local/lib/python3.8/dist-packages/ipykernel/zmqshell.py", line 536, in run_cell
  return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 2854, in run_cell
  result = self._run_cell(
File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 2881, in _run_cell
  return runner(coro)
File "/usr/local/lib/python3.8/dist-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
  coro.send(None)
File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3057, in run_cell_async
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3249, in run_ast_nodes
  if (await self.run_code(code, result,  async_=asy)):
File "/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
  exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-5-1059bcc7b5d0>", line 28, in <module>
  model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)
File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 64, in error_handler
  return fn(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1409, in fit
  tmp_logs = self.train_function(iterator)
File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1051, in train_function
  return step_function(self, iterator)
File "/usr/local/lib/python3.8/dist-packages/keras/engine/training.py", line 1040, in step_function
  outputs = model.distribute_strategy.run(run_step, args=(data,))
	 [[StatefulPartitionedCall]] [Op:__inference_train_function_1343]
```
</details>

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.9, v2.11 and tf-nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/1907380ac1884da995d5b6e50da983e0/untitled867.ipynb).

**Comment by sachinprasadhs** [comment]
Hi, As the error suggests: 
`on XLA_GPU_JIT: DebugNumericSummaryV2 (No registered 'DebugNumericSummaryV2' OpKernel for XLA_GPU_JIT devices compatible with node {{node DebugNumericSummaryV2}}){{node DebugNumericSummaryV2}}` it is unimplemented for `tf.debugging.enable_check_numerics()` for `XLA JIT`.

Currently we don't have wide support of XLA JIT across all the APIs. 
We will consider this request to add support in our future implementation. Thanks!

**Comment by JonasAmrich** [comment]
@sachinprasadhs Thanks for this confirmation. The situation is a bit unfortunate as keras optimizers are JIT compiled by default (sice 3ad70f6cab8912860abb1b94c004e84b1114a6f7) and check_numerics therefore doesn't work out of the box on GPU. The workaround (explicitly disabling jit_compile on optimizer) is straightforward, however it took me some time to realize.. Would it make sense to add a note to docs?

**Comment by reedwm** [comment]
@poulsbo, any ideas? As `tf.function(jit_compile=True)` is used in more places in both user code and Keras, it will become increasingly infeasible for users to use `enable_check_numerics`, as doing so will cause an error as long as any jit-compiled tf.function is created. Perhaps we should not insert the check numerics ops in jit-compiled tf.functions, although it would be bad to silently change behavior if a tf.function is jit-compiled.

@cheshire would it be possible to support `enable_check_numerics` in XLA? Could the bridge insert a custom calls after each op that would check for infs/nan, put the result of the check in a boolean, transfer the bool to the CPU, and raise an error if it's true? Of course this would be very very slow and effectively disable fusions.

**Comment by cheshire** [comment]
> would it be possible to support enable_check_numerics in XLA?

Yes. We don't even need custom-calls: can do with if-statements.

> Of course this would be very very slow and effectively disable fusions

But then you are changing numerics, at which point you might as well disable XLA compilation entirely?

What is the goal of using enable_check_numerics? Is it to check the algorithm, or to check TF implementation?

**Comment by reedwm** [comment]
The goal of enable_check_numerics is to debug where Inf/Nan values are coming from, by causing an error be thrown the first time any TF op has an output which is Inf or Nan. Even without XLA, enable_check_numerics can slightly change numerics due to difference in Grappler optimizations. I'm guessing the numeric difference doesn't cause issues in practice.

> Yes. We don't even need custom-calls: can do with if-statements.

How can this be done with XLA today? How do you raise an error in HLO?

**Comment by cheshire** [comment]
A custom-call can return a bad Status, which will be propagated at runtime. But yes then, custom-calls will be required.

**Comment by johnlarkin1** [comment]
Just to be clear, this is still an open issue right? There's no way to be running utilizing GPUs while executing this line: 
```
    tf.debugging.experimental.enable_dump_debug_info(
        debugging_dir, tensor_debug_mode="FULL_HEALTH", circular_buffer_size=-1
    )
```

I have tried to utilize `tf.config.set_soft_device_placement(True)` but that didn't work for me as well. 

The scenario is that my training only falls into Nans at the later stages and I'd 1) love to investigate using the tensorboard logs and 2) need that level of training

**Comment by manojssmk** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
