### ISSUE TITLE
[tflite] Converting a JAX model with `lax.switch` to TFLite fails (related to `StatelessCase` / `tf.Case`)

### ISSUE THREAD

**Issue by josephrocca** [tensorflow/tensorflow#59211]
### 1. System information

- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installation: pip
- TensorFlow library: 2.9.2 

### 2. Code & Minimal Reproduction Colab Notebook

I have the following minimal code (see [this Colab notebook](https://colab.research.google.com/gist/josephrocca/76ab8cb26dc83a0b5fd58945962033a0)) that uses `jax.lax.switch` and tries to convert the model to TFLite:
```py
def test_jax(n, operand):

  def fn1(a):
    return a+2
  
  def fn2(a):
    return a*2

  result = jax.lax.switch(
    n,
    [fn1, fn2],
    operand,
  )

  return result
```

```py
jax.jit(test_jax)(1, 2)  # returns `4`
```

```py
my_model = tf.Module()
my_model.f = tf.function(jax2tf.convert(test_jax, enable_xla=False), jit_compile=True, autograph=False, input_signature=[
    tf.TensorSpec([], tf.uint32, name="n"),
    tf.TensorSpec([], tf.uint32, name="operand"),
])
tf.saved_model.save(my_model, './test')
```

```py
converter = tf.lite.TFLiteConverter.from_saved_model('./test')

converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]

tflite_model = converter.convert()

with open('test.tflite', 'wb') as f:
  f.write(tflite_model)
```

That TFLite conversion code outputs:
```
ConverterError: <unknown>:0: error: loc(callsite(callsite(fused["StatelessCase:", "jax2tf_test_jax_/switch_case/indexed_case@__inference_converted_fun_tf_58"] at fused["PartitionedCall:", "PartitionedCall@__inference_signature_wrapper_66"]) at fused["PartitionedCall:", "PartitionedCall"])): 'tf.Case' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["PartitionedCall:", "PartitionedCall"]): called from
<unknown>:0: note: loc(callsite(callsite(fused["StatelessCase:", "jax2tf_test_jax_/switch_case/indexed_case@__inference_converted_fun_tf_58"] at fused["PartitionedCall:", "PartitionedCall@__inference_signature_wrapper_66"]) at fused["PartitionedCall:", "PartitionedCall"])): Error code: ERROR_NEEDS_CUSTOM_OPS
<unknown>:0: error: failed while converting: 'main': 
Some ops in the model are custom ops, See instructions to implement custom ops: https://www.tensorflow.org/lite/guide/ops_custom 
Custom ops: StatelessCase
Details:
	tf.Case(tensor<i32>, tensor<ui32>) -> (tensor<*xui32>) : {Tin = [ui32], Tout = [ui32], _read_only_resource_inputs = [], _xla_propagate_compile_time_consts = true, branches = [@jax2tf_test_jax__switch_case_indexed_case_branch0_220, @jax2tf_test_jax__switch_case_indexed_case_branch1_230, @jax2tf_test_jax__switch_case_indexed_case_branch2_240, @jax2tf_test_jax__switch_case_indexed_case_branch3_250], device = "", is_stateless = true}
```

And I tried using `experimental_from_jax` ([Colab notebook](https://colab.research.google.com/gist/josephrocca/4317a1db075a6e42ed600dfe23e47a75)), but for some reason it is crashing my notebook.

Thanks!

**Comment by tiruk007** [comment]
@josephrocca 
While I tried to replicate the issue on Colab using TF v2.11, I didn't face crashing but got a different error. Could you please find the gist [here](https://colab.research.google.com/gist/tiruk007/4e5991f2d19b6efdaf24fbc52c016b35/untitled75.ipynb) for reference and confirm the same?
Thank you!

**Comment by josephrocca** [comment]
@tiruk007 In your demo, you're using `experimental_from_jax`, whereas in mine I'm using `from_saved_model`. Either way, the error seems to point to the same `case` problem.

**Comment by tiruk007** [comment]
@mohantym 
I was able to reproduce the issue on Colab using TF v2.11. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/811f7f5587dfedbcd45fdf7c7b0c36d3/untitled79.ipynb) for reference.

Thank you!

**Comment by mohantym** [comment]
@josephrocca !
Thanks for sharing your observation on Jax -lite conversion with Saved_model approach.

I was able to resolve this issue with below changes. Attached gist in [2.11 ](https://colab.sandbox.google.com/gist/mohantym/2c6d49c9631e6e76a13c0029501318e0/untitled79.ipynb#scrollTo=4elXZy82MN5u)for reference.
```
converter = tf.lite.TFLiteConverter.from_saved_model('./test')

converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]

converter.allow_custom_ops = True
tflite_model = converter.convert()

with open('test.tflite', 'wb') as f:
  f.write(tflite_model)
```
Could you update from your side. 

Thank you!

**Comment by josephrocca** [comment]
@mohantym Ah, sorry, I should have mentioned that @Ferev [showed me](https://github.com/google/jax/issues/13416#issuecomment-1379383626) the `allow_custom_ops` workaround on the JAX repo, but there were concerns expressed that something is potentially going wrong here - seems unusual that `Case` is a custom op:

> For some reason this is interpreted as a custom op. Will ask the team investigate why this is the case. I agree this is weird behavior for `Case`.

**Comment by mohantym** [comment]
@josephrocca !
Thanks for the update. I could not find case operator neither in built-in ops /select-ops allowed list though.
Could you consider this as partially resolved as original issue on conversion is resolved. 

Feel free to re-open this issue if you face any challenge during inference. Attached [custom-ops](https://www.tensorflow.org/lite/guide/ops_custom) docs to add those ops in lite kernels for reference.

Thank you!

**Comment by josephrocca** [comment]
Hey @mohantym I'd consider the issue unresolved until we work out why `allow_custom_ops` is required here. I guess we should wait to hear back from @Ferev's investigations to see whether this is indeed expected behavior. It seems to have slightly confused a couple of people on the JAX team, so I think that's enough to keep this open until more info comes in.

**Comment by mohantym** [comment]
@josephrocca !
Thanks for the update.  

@sachinprasadhs !
Could you look at this issue.  

Thank you!

**Comment by haozha111** [comment]
assigning it to @Ferev since he is working on jax support.

**Comment by sachinprasadhs** [comment]
`tf.Case` is not yet part of the allowed list yet, till we work on that, you can consider using `converter.allow_custom_ops = True`, which is a Boolean indicating whether to allow custom operations. When False, any unknown operation is an error. When True, custom ops are created for any op that is unknown. The developer needs to provide these to the TensorFlow Lite runtime with a custom resolver. (default False)

```
converter = tf.lite.TFLiteConverter.from_saved_model('./test')

converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]

converter.allow_custom_ops = True
tflite_model = converter.convert()

with open('test.tflite', 'wb') as f:
  f.write(tflite_model)
```

**Comment by sachinprasadhs** [comment]
Hi, Case operator has been made part of the flex allowlist. Please refer the commit here https://github.com/tensorflow/tensorflow/commit/848f46ab8b89bd1fd64699a1697a212c165be619. Thanks!
