### ISSUE TITLE
Movinet Colab 'TypeError'

### ISSUE THREAD

**Issue by Cdukes30** [tensorflow/tensorflow#59231]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.9.2

### Custom Code

No

### Python version

3.9.16

### Current Behaviour?

```shell
Hello, I'm reporting an issue I'm getting when simply trying to run the extended moving tutorial in google Colab. I'm not entirely sure of the other information, but without changing anything and just trying to run the tutorial, I cannot import from official.projects.movinet.modeling import movinet. The 'TypeError' reads: 'ABCMeta' object not subscriptable and can't find any solution to fixing it.
```

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/github/tensorflow/models/blob/master/official/projects/movinet/movinet_tutorial.ipynb
```

### Relevant log output

_No response_</details>

**Comment by Cdukes30** [comment]
<img width="859" alt="Screen Shot 2023-01-11 at 1 16 29 PM" src="https://user-images.githubusercontent.com/110950777/211908898-7bb6fc8b-f5e1-41c9-9391-0aac2137af02.png">

**Comment by synandi** [comment]
@Cdukes30  I was able to import the  'movinet' from 'official.projects.movinet.modeling' using the stable versions of tf-models-official and tensorflow_datasets on colab, please find the gist [here](https://colab.sandbox.google.com/gist/synandi/b61fa161e3651f248f2361b0fd68ff23/59231.ipynb) and let us know if the issue persists.
Thank you!
