### ISSUE TITLE
Problem with loading example dataset

### ISSUE THREAD

**Issue by rexys777** [tensorflow/tensorflow#59245]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf2.9.2

### Custom Code

No

### OS Platform and Distribution

Google collab 

### Current Behaviour?

```shell
Good afternoon!
I learm the colab notebook, example «Transfer Learning for the Audio Domain with TensorFlow Lite Model Maker» (https://www.tensorflow.org/lite/models/modify/model_maker/audio_classification)
In this example, The Birds dataset cannot be loaded. This link (https://storage.googleapis.com/laurencemoroney-blog.appspot.com/birds_dataset .zip') is invalid.
How can I get this dataset for this example?
```

### Standalone code to reproduce the issue

```shell
Example text from: https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models/modify/model_maker/audio_classification.ipynb#scrollTo=upNRfilkNSmr

birds_dataset_folder = tf.keras.utils.get_file('birds_dataset.zip',
                                                'https://storage.googleapis.com/laurencemoroney-blog.appspot.com/birds_dataset.zip',
                                                cache_dir='./',
                                                cache_subdir='dataset',
                                                extract=True)
                                                

This link (https://storage.googleapis.com/laurencemoroney-blog.appspot.com/birds_dataset .zip') is invalid.
```

### Relevant log output

```shell
Downloading data from https://storage.googleapis.com/laurencemoroney-blog.appspot.com/birds_dataset.zip
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/keras/utils/data_utils.py in get_file(fname, origin, untar, md5_hash, file_hash, cache_subdir, hash_algorithm, extract, archive_format, cache_dir)
    276       try:
--> 277         urlretrieve(origin, fpath, dl_progress)
    278       except urllib.error.HTTPError as e:

8 frames
HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
/usr/local/lib/python3.8/dist-packages/keras/utils/data_utils.py in get_file(fname, origin, untar, md5_hash, file_hash, cache_subdir, hash_algorithm, extract, archive_format, cache_dir)
    277         urlretrieve(origin, fpath, dl_progress)
    278       except urllib.error.HTTPError as e:
--> 279         raise Exception(error_msg.format(origin, e.code, e.msg))
    280       except urllib.error.URLError as e:
    281         raise Exception(error_msg.format(origin, e.errno, e.reason))

Exception: URL fetch failure on https://storage.googleapis.com/laurencemoroney-blog.appspot.com/birds_dataset.zip: 404 -- Not Found
```
</details>

**Comment by rexys777** [comment]
What should be the data structure for this example?

**Comment by synandi** [comment]
@tilakrayal, I was able to replicate the issue on Colab using TF v2.11. Please find the gist [here](https://colab.sandbox.google.com/gist/synandi/7b57f5422d5c700a554ff9ebf6d79caa/59245.ipynb#scrollTo=I55Gn8B6pXjn). Thank you!

**Comment by tilakrayal** [comment]
@rexys777,
Thank you for reporting the issue. This is already a known problem and the developer team is attempting to resolve it. We are tracking this internally (https://buganizer.corp.google.com/issues/231155215) and will update once it gets resolved. Thank you!

**Comment by root50643** [comment]
> What should be the data structure for this example?
I had the same problem and this is my conclusion

.
└── dataset
    └── small_birds_dataset
        ├── test
        │   ├── azaspi1
        │   ├── chcant2
        │   ├── houspa
        │   ├── redcro
        │   └── wbwwre1
        └── train
            ├── azaspi1
            ├── chcant2
            ├── houspa
            ├── redcro
            └── wbwwre1

**Comment by aasthavar** [comment]
Maybe use this website to build your own dataset: https://xeno-canto.org/

**Comment by bitstobreath** [comment]
Hello @rexys777 @synandi @tilakrayal @root50643

Problem solved!

[Scripts](https://github.com/bitstobreath/model_maker_audio_classification_birds_dataset)

Below May not work due to google drive rate limiting, so use the Scripts above to generate your own data.

[Colab Example](https://colab.research.google.com/drive/19ymE8AuM1e-VdHogh6ywTsqnWbbBH1f3?usp=sharing)

[Google Drive 5GB Zip of dataset](https://drive.google.com/drive/folders/1YPDjo_L0TC23a6yDBMeQpeeCKFLwEMNX?usp=sharing)

All audio files are downloaded from xeno-canto.org as of Mar 4 2023 ~3AM EST
All audio files are in the correct format, 1600hz mono audio wav, (MS 16bit PCM)

If somebody has a better way to host this via google services as this is a google product and service.

Colab really should develop it's own predefined storage backend to save them the download time for example projects.
It's ridiculous they are paying for the bandwidth, it costs end users too, if they have an expensive ISP.

**Comment by rexys777** [comment]
Thanks @bitstobreath, great job. 
Perhaps the issue is now definitely closed.

**Comment by bitstobreath** [comment]
@tilakrayal I have solved, it and provided some links, please confirm if this helps you.
Thanks.

**Comment by tilakrayal** [comment]
@bitstobreath & @rexys777,
Yeah, the dataset was able to load and tested the code & working as expected. Also as mentioned [here](https://github.com/tensorflow/tensorflow/issues/59245#issuecomment-1384908351), the internal CL was also closed and the data in the tensorflow.org will also update soon. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/6dd9361b486efc90824c6fdd9cd01409/audio_classification_colab.ipynb). 
![Screenshot 2023-03-04 10 47 46 PM](https://user-images.githubusercontent.com/81610181/222919898-77ad4655-9274-44a1-b72c-dd5a338f25ef.png)

Thank you!
