### ISSUE TITLE
PLZ help.thx.tensorflow constatnly fails to download some packages!

### ISSUE THREAD

**Issue by craftlk** [tensorflow/tensorflow#5924]
On a KNL server, I tried to install Tensorflow by compiling way. I'm not root so I manually set the env in my directory.  And there is no network on the server, so I use SSH FORWARD.
Here is the problem I've met:

ERROR: /home/guest/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@iron_resizable_behavior//': Error downloading from https://github.com/polymerelements/iron-resizable-behavior/archive/v1.0.3.tar.gz to /home/guest/.cache/bazel/_bazel_guest/ac941aabf1be9475583be832ae449128/external/iron_resizable_behavior: Error downloading https://github.com/polymerelements/iron-resizable-behavior/archive/v1.0.3.tar.gz to /home/guest/.cache/bazel/_bazel_guest/ac941aabf1be9475583be832ae449128/external/iron_resizable_behavior/v1.0.3.tar.gz: Timed out connecting to https://github.com/polymerelements/iron-resizable-behavior/archive/v1.0.3.tar.gz : Read timed out and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: /home/guest/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@iron_resizable_behavior//': Error downloading from https://github.com/polymerelements/iron-resizable-behavior/archive/v1.0.3.tar.gz to /home/guest/.cache/bazel/_bazel_guest/ac941aabf1be9475583be832ae449128/external/iron_resizable_behavior: Error downloading https://github.com/polymerelements/iron-resizable-behavior/archive/v1.0.3.tar.gz to /home/guest/.cache/bazel/_bazel_guest/ac941aabf1be9475583be832ae449128/external/iron_resizable_behavior/v1.0.3.tar.gz: Timed out connecting to https://github.com/polymerelements/iron-resizable-behavior/archive/v1.0.3.tar.gz : Read timed out and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: Evaluation of query "deps((//tensorflow/... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.

**Comment by jart** [comment]
A fix to Bazel is going to be pushed soon. It's going to be amazing.

**Comment by jart** [comment]
This has been fixed by https://github.com/bazelbuild/bazel/commit/ed7ced0018dc5c5ebd6fc8afc7158037ac1df00d. Try using Bazel at HEAD. A new Bazel will be cut in a few days. As soon as that happens, the TensorFlow repository will be updated to use multiple mirrors for each external file.
