### ISSUE TITLE
Support Visual Studio 2022 compiler

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#59240]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

No

### OS Platform and Distribution

Windows 11 x64

### Mobile device

N/A

### Python version

3.11.0

### Bazel version

6.0

### GCC/Compiler version

Visual Studio 2022

### CUDA/cuDNN version

11.8/8.7.0

### GPU model and memory

RTX3090

### Current Behaviour?

```shell
only visual studio 2019 compiler supported
```

### Standalone code to reproduce the issue

```shell
build
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@alanpurple 
Can you please elaborate about your Feature and please specify the Use Cases for this feature ?

Thank you!

**Comment by chalakprana** [comment]
no support for VS 2022 yet, possible attach full error screen
https://stackoverflow.com/questions/73129804/cannot-build-tensorflow-on-windows
https://www.tensorflow.org/install/source_windows#install_visual_c_build_tools_2019

**Comment by sachinprasadhs** [comment]
Hi, For the Tensorflow version 2.11 for GPU, as per the tested build configuration we support below configuration.
For the `Tensorflow 2.12` version, we are planning to upgrade `CUDA` version to `11.8` and other build configurations will be published once the next stable release is available. Thanks!

<h3 id="gpu" data-text="GPU" role="presentation" style="box-sizing: inherit; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: ; font-variant-east-asian: ; font-weight: ; font-stretch: ; font-size: ; line-height: ; font-family: ; letter-spacing: normal; margin: var(--devsite-h3-margin); overflow: hidden; text-overflow: ellipsis; margin-inline-end: -40px; padding-inline-end: 40px; color: rgb(32, 33, 36); orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="devsite-heading" role="heading" aria-level="3" style="box-sizing: inherit;">GPU</span><button type="button" class="devsite-heading-link button-flat material-icons" aria-label="Copy link to this section: GPU" data-title="Copy link to this section: GPU" data-id="gpu" style="box-sizing: border-box; appearance: none; background: 0px center; border: 0px; border-radius: var(--devsite-button-border-radius,2px); box-shadow: none; color: var(--devsite-icon-color,var(--devsite-secondary-text-color)); cursor: pointer; display: inline-block; font-style: normal; font-variant-ligatures: ; font-variant-caps: ; font-variant-numeric: ; font-variant-east-asian: ; font-weight: normal; font-stretch: ; font-size: 24px; font-family: &quot;Material Icons&quot;; height: 24px; letter-spacing: normal; line-height: 1; margin: var(--devsite-button-margin,0); margin-inline-end: var(--devsite-button-margin-x-end); max-width: var(--devsite-button-max-width,none); min-width: 36px; outline: 0px; overflow: hidden; padding: 0px 8px; text-align: center; text-decoration: none; text-overflow: ellipsis; text-transform: none; transition: background-color 0.2s ease 0s, border 0.2s ease 0s, box-shadow 0.2s ease 0s; vertical-align: middle; white-space: nowrap; width: var(--devsite-button-width,auto); overflow-wrap: normal; direction: ltr; font-feature-settings: &quot;liga&quot;; -webkit-font-smoothing: antialiased; opacity: 0;"></button></h3><div class="devsite-table-wrapper" style="box-sizing: inherit; margin: var(--devsite-table-margin,16px 0); padding: 0px; overflow: auto; color: rgb(32, 33, 36); font-family: Roboto, &quot;Noto Sans&quot;, &quot;Noto Sans JP&quot;, &quot;Noto Sans KR&quot;, &quot;Noto Naskh Arabic&quot;, &quot;Noto Sans Thai&quot;, &quot;Noto Sans Hebrew&quot;, &quot;Noto Sans Bengali&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow_gpu-2.11.0 | 3.7-3.10 | MSVC 2019 | Bazel 5.3.0 | 8.1 | 11.2

</div>

**Comment by reedwm** [comment]
@learning-to-play, not sure how to handle this. I'm not familiar with the Windows build and am unsure of whether want to officially or unofficially support MSVC 2022 or not.

CC @angerson

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by alanpurple** [comment]
@Venkat6871 

I think this has been fixed since i can see visual studio 2022 in tensorflow build guide

I don't know why any tensorflower haven't closed this issue yet.

I am closing this now
