### ISSUE TITLE
Is there any way to disable remapping optimizer in Tensorflow1.15.0?

### ISSUE THREAD

**Issue by taki-Lee** [tensorflow/tensorflow#59241]
## System information
-   **Centos7**
-   **Python 2.7**
-   **tensorflow1.15.0**
-   **CUDA10.0**
-   **CUDNN7**
-   **GPU: P100**

## Describe the problem
I used `tensorflow.python.client.timeline` tool in tf1.x to profile computation graph execution procedure. Then I find remapping optimizer fuse MatMul, BiasAdd and Elu into _FusedMatMul before graph execution. I also used `tf.config.optimizer.set_experimental_options()` to set remapping false but it didn't work. I don't known if I used it correctly. 

## Source code / logs
Here are my codes:
### Function to set Options
```bash
@contextlib.contextmanager
def graph_optimizer_options(options):
    old_opts = tf.config.optimizer.get_experimental_options()
    tf.config.optimizer.set_experimental_options(options)
    try:
        yield
    finally:
        tf.config.optimizer.set_experimental_options(old_opts)
```
### Options are here:
```bash
    options = {'constant_folding': False,
               'layout_optimizer': False,
               'shape_optimization': False,
               'remapping': False,
               'arithmetic_optimization': False,
               'dependency_optimization': False,
               'loop_optimization': False,
               'function_optimization': False,
               'debug_stripper': False,
               'disable_model_pruning': False,
               'scoped_allocator_optimization': False,
               'pin_to_host_optimization': False,
               'implementation_selector': False,
               'auto_mixed_precision': False,
               'disable_meta_optimizer': False,
               'min_graph_nodes': False}
```
### execute Computational Graph with tf.Session().
```bash
    with tf.Session(graph=graph, config=config) as sess:
        run_options = tf.compat.v1.RunOptions(trace_level = tf.compat.v1.RunOptions.FULL_TRACE)
        run_metadata = tf.compat.v1.RunMetadata()
        tf.graph_util.import_graph_def(graph_def, name="")
        
        @tf.function
        def _run():
            sess.run(outputs_name, feed_dict = feed_dict, options = run_options, run_metadata = run_metadata)

        start_time = time.time()
        with graph_optimizer_options(options):
            print(tf.config.optimizer.get_experimental_options())
            _run()
        end_time = time.time()
        tl = timeline.Timeline(run_metadata.step_stats)
        # TODO better record meassurement
        ctf = tl.generate_chrome_trace_format()
        with open(tl_saved_path, 'w') as f:
            f.write(ctf)
    
    print("finish running on {}, run time: {}".format(device, end_time - start_time))
```
the result of "tf.config.optimizer.get_experimental_options()"
```bash
{'debug_stripper': False, 'function_optimization': False, 'disable_model_pruning': False, 'constant_folding': False, 'implementation_selector': False, 'pin_to_host_optimization': False, 'auto_mixed_precision': False, 'disable_meta_optimizer': False, 'loop_optimization': False, 'scoped_allocator_optimization': False, 'dependency_optimization': False, 'shape_optimization': False, 'remapping': False, 'layout_optimizer': False, 'arithmetic_optimization': False}
```
Remapping seem to be False but _FusedMatMul still exist. Is there any way to disable remapping optimizer in Tensorflow1.15.0?

**Comment by gaikwadrahul8** [comment]
Hi, @taki-Lee 

Apologize for the delay and unfortunately we do not support Tensorflow 1.x anymore so I would suggest you to migrate your code in Tensorflow 2.x by following our official documentation [here](https://www.tensorflow.org/guide/migrate), after migrating your code in Tensorflow 2.x if issue still persists in Tensorflow 2.x please let us know ? In order to expedite the trouble-shooting process, please provide a code snippet or Google Colab notebook to reproduce the issue reported. Thank you!

**Comment by taki-Lee** [comment]
Thanks for reply! I have found another way to set optimizer OFF. 
We use tf.Sesion() to build computational graph. We can set session config to invalidate optimizer. Here is the code.
`
  config = config_pb2.ConfigProto()
  # Grappler might fuse MatMul with BiasAdd in remapper optimizer.
  config.graph_options.rewrite_options.remapping = (rewriter_config_pb2.RewriterConfig.OFF)
  with session.Session(config=config) as sess:
`
And here is my modified code:
`
config = tf.ConfigProto(allow_soft_placement=True, gpu_options=tf.compat.v1.GPUOptions(allow_growth=True))
    config.graph_options.rewrite_options.remapping = (rewriter_config_pb2.RewriterConfig.OFF)
    
    if tl_saved_path == None:
        tl_saved_path = device+"_timeline.json"
    # print(feed_dict['Placeholder_403:0'])
    
    with tf.Session(graph=graph, config=config) as sess:
        run_options = tf.compat.v1.RunOptions(trace_level = tf.compat.v1.RunOptions.FULL_TRACE)
        run_metadata = tf.compat.v1.RunMetadata()
        tf.graph_util.import_graph_def(graph_def, name="")
        
        start_time = time.time()
        sess.run(outputs_name, feed_dict = feed_dict, options = run_options, run_metadata = run_metadata)
        end_time = time.time()
        tl = timeline.Timeline(run_metadata.step_stats)
        # TODO better record meassurement
        ctf = tl.generate_chrome_trace_format()
        with open(tl_saved_path, 'w') as f:
            f.write(ctf)
`
Finally, Matmul, BiasAdd and Elu are not fused.

**Comment by gaikwadrahul8** [comment]
Hi, @taki-Lee 

Good to hear that and thank you for sharing working code snippet with way to disable remapping optimizer so do you need any further assistance ? or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
