### ISSUE TITLE
Conversion of Diffusion model inside Colab generates a non valid .tflite file

### ISSUE THREAD

**Issue by farmaker47** [tensorflow/tensorflow#59259]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab connected to VM of GCP (high RAM is needed)
- TensorFlow installation (pip package or built from source): Version 2.11.0
- TensorFlow library (version, if pip package or github SHA, if built from source):

#### Option B: Paste your code here or provide a link to a custom end-to-end colab

Link for colab notebook to open: 
`https://colab.research.google.com/drive/1I7m4sGWi6U1ODbG0Fln42GU45CEf7Qsk?authuser=1#scrollTo=uGjOTEFoZrDq`
Link for colab notebook to download:
`https://colab.research.google.com/drive/1I7m4sGWi6U1ODbG0Fln42GU45CEf7Qsk?usp=share_link`

- Include code to invoke the TFLite Converter Python API and the errors.
```
converter = tf.lite.TFLiteConverter.from_keras_model(diffusion_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS,
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_model = converter.convert()

# Save the model.
with open('diffusion_model.tflite', 'wb') as f:
  f.write(tflite_model)
```

- Provide links to your TensorFlow model and (optionally) TensorFlow Lite Model.
- https://huggingface.co/fchollet/stable-diffusion/blob/main/kcv_diffusion_model.h5
- https://drive.google.com/file/d/1coWb7CWBYrU7pDFX3SWpmmWUqus68R7w/view?usp=share_link

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

- Model cannot be opened by netron.app and android application. The error is:
"Not valid .tflite flatbuffer file"

### 5. (optional) Any other info / logs
When the default quantization is used 
```
converter = tf.lite.TFLiteConverter.from_keras_model(diffusion_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS,
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_model = converter.convert()

# Save the model.
with open('diffusion_model4.tflite', 'wb') as f:
  f.write(tflite_model)
```

the procedure exits with:
```
" WARNING:absl:Found untraced functions such as conv2d_84_layer_call_fn, conv2d_84_layer_call_and_return_conditional_losses, _jit_compiled_convolution_op, group_normalization_63_layer_call_fn, group_normalization_63_layer_call_and_return_conditional_losses while saving (showing 5 of 1320). These functions will not be directly callable after loading.
INFO:tensorflow:Assets written to: /tmp/tmptbzu7bs5/assets
INFO:tensorflow:Assets written to: /tmp/tmptbzu7bs5/assets
WARNING:absl:Buffer deduplication procedure will be skipped when flatbuffer library is not properly loaded
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-9-c1e1de4224af>](https://localhost:8080/#) in <module>()
      6   tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
      7 ]
----> 8 tflite_model = converter.convert()
      9 
     10 # Save the model.

16 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/importer.py](https://localhost:8080/#) in _import_graph_def_internal(graph_def, input_map, return_elements, validate_colocation_constraints, name, producer_op_list)
    495   # _ProcessNewOps.
    496   with graph._mutation_lock():  # pylint: disable=protected-access
--> 497     with c_api_util.tf_buffer(graph_def.SerializeToString()) as serialized:
    498       try:
    499         with graph._c_graph.get() as c_graph:  # pylint: disable=protected-access

ValueError: Message tensorflow.GraphDef exceeds maximum protobuf size of 2GB: 3440961451 "
```

but per documentation this is supposed to create a 4x times smaller file?? 
ie ~850MB?

`https://www.tensorflow.org/lite/performance/post_training_quantization#optimization_methods`

**Comment by freedomtan** [comment]
Converting Keras Stable Diffusion models to tflite models should just work for fp16 or dynamic range quantization if recent TensorFlow master branch is used. For older TensorFlow versions, you probably need
1. set input batch size, and 
2. remove `tf.lite.OpsSet.SELECT_TF_OPS`

I was able to convert 
1. fp32 models to fp32 tflite models by splitting diffusion_models into two chunks
2. fp32 models to fp16 tflite models, 
3. fp32 models to dynamic range int8, which is what you tried to do
4. full-integer quantized

I also managed to converted fp32 tflite models to performance text-to-image.
See my comments for a keras cv [1] and scripts I used [2].


[1] https://github.com/keras-team/keras-cv/issues/1033
[2] https://github.com/freedomtan/keras_cv_stable_diffusion_to_tflite

**Comment by mohantym** [comment]
Hi @farmaker47 !

Could you give us an update with after testing @freedomtan 's [work around](https://github.com/tensorflow/tensorflow/issues/59259#issuecomment-1399214673) on going with fp16 lite model or full integer quantization.

Thank you!
