### ISSUE TITLE
How to get label of detection after (@tensorflow/tfjs-tflite) predict returns result from a custom tflite model in Reactjs web App

### ISSUE THREAD

**Issue by FlyWong** [tensorflow/tensorflow#59258]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

tfjs@^3.7.0

### Custom Code

No

### OS Platform and Distribution

Windows 10

### Mobile device

Windows laptop

### Python version

2.7

### Current Behaviour?

```shell
I am using 

     import * as tflite from '@tensorflow/tfjs-tflite';


and have successfully loaded a custom tflite model:

     tfliteModel = await tflite.loadTFLiteModel("model/myModel.tflite");

as well as gotten a prediction
     var outputTensor = await tfliteModel.predict(Img);

The code works well when I only have 1 label to detect initially. Now I need to detect multiple labels. I created a new custom model and tested that it is able to detect multiple labels in an Android project, eg. I can get labels 'L1', and 'L2'

Can I detect multi labels using the code above after I load in the new model? If not, what changes do I have to make to detect multi labels and know which label I am detecting (eg. obtain the name of the label)
```

### Standalone code to reproduce the issue

```shell
See above. Not a bug issue.
```

### Relevant log output

```shell
Instance of result, outputTensor's value

outputTensor:
{
  "StatefulPartitionedCall:1": {
    kept: false,
    isDisposedInternal: false,
    shape: [
      1,
      25,
    ],
    dtype: "float32",
    size: 25,
    strides: [
      25,
    ],
    dataId: {
      id: 364,
    },
    id: 364,
    rankType: "2",
  },
  "StatefulPartitionedCall:3": {
    kept: false,
    isDisposedInternal: false,
    shape: [
      1,
      25,
      4,
    ],
    dtype: "float32",
    size: 100,
    strides: [
      100,
      4,
    ],
    dataId: {
      id: 365,
    },
    id: 365,
    rankType: "3",
  },
  "StatefulPartitionedCall:0": {
    kept: false,
    isDisposedInternal: false,
    shape: [
      1,
    ],
    dtype: "float32",
    size: 1,
    strides: [
    ],
    dataId: {
      id: 366,
    },
    id: 366,
    rankType: "1",
  },
  "StatefulPartitionedCall:2": {
    kept: false,
    isDisposedInternal: false,
    shape: [
      1,
      25,
    ],
    dtype: "float32",
    size: 25,
    strides: [
      25,
    ],
    dataId: {
      id: 367,
    },
    id: 367,
    rankType: "2",
  },
}
```
</details>

**Comment by pjpratik** [comment]
@FlyWong OutputTensor will be a tensor holding the scores for each class after receiving the prediction from the model. The class index that best matches the detected label can be located using the `argMax` method, which returns the class index with the highest score. The label index should be mapped to the actual class label using a label map. After that, you may look for the class label using the label index.

**Comment by FlyWong** [comment]
![tfLitePredictionResults](https://user-images.githubusercontent.com/10432466/213037199-d7cc2bf4-0316-4ab4-83c4-4022afdfd239.JPG)
Hi @pjpratik , may I know which is the class index you are referring too? 

also, I tried to call argMax on OutputTensor, but there is no such function:

![argMax Err](https://user-images.githubusercontent.com/10432466/213047678-4c5d5f35-e7a5-47fc-9489-f6490e218997.JPG)

**Comment by pjpratik** [comment]
@FlyWong  The class index I was referring to was the indexes of ground truth class labels. The output of argMax gives us the index at which the value is maximum. That index can be mapped to the index of ground truth class labels to get the name of the label. 

Please refer to the documentation of argMax [here](https://js.tensorflow.org/api/latest/#argMax) and let us know if it helps. Thank you.

**Comment by FlyWong** [comment]
Hi @pjpratik,

I guess the gap is how I can proceed from having a return tensor (outputTensor) from predict() to having a list of 'ground truth class labels'?

**Comment by pjpratik** [comment]
@FlyWong Please refer to this [codelab](https://codelabs.developers.google.com/tensorflowjs-transfer-learning-teachable-machine#13) on using tf.js for using predict() and mapping to list of ground truth class labels to get the label name. 

This is not a bug or feature request, for any further queries you may open this issue in tf discussion [forum](https://discuss.tensorflow.org/) as there is a larger community there. Thanks!

**Comment by FlyWong** [comment]
@pjpratik Thanks. Yes, I think the forum will be a better place to take this discussion further.
