### ISSUE TITLE
Should we use cudnn v5.0 or v5.1?

### ISSUE THREAD

**Issue by davidshen84** [tensorflow/tensorflow#5925]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: osx Sierra

Installed version of CUDA and cuDNN:

- cuda v8.0,
- cudnn v5.0
 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```
lib/libcuda.1.dylib     lib/libcudart.8.0.dylib lib/libcudnn.5.dylib
lib/libcuda.dylib       lib/libcudart.dylib     lib/libcudnn.dylib
lib/libcudadevrt.a      lib/libcudart_static.a  lib/libcudnn_static.a
```

If installed from binary pip package, provide:

1. A link to the pip package you installed: https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow-0.11.0-py3-none-any.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

```
python3 -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.dylib locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.dylib locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.dylib locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.1.dylib locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.dylib locally
0.11.0rc2
```

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

```
cd /usr/local/lib/python3.5/site-packages/tensorflow/models/image/mnist
python3 convolutional.py
````

### What other attempted solutions have you tried?

**Install cudnn v5.1**

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

The code sample failed, complaining about cudnn and tensorflow version mismatch. I lost the original output. It said something like the tensorflow is build with cudnn 51000x, but the loaded cudnn lib is 50000.

Then, I installed cudnn v5.1, and the message is gone, and the sample code runs.

I followed the installation instruction on https://www.tensorflow.org/versions/master/get_started/os_setup.html#pip-installation. I think either the instruction needs update to tell people to install cudnn v5.1; or something mistakenly build tensorflow with cudnn v5.1 and released it.

**Comment by poxvoculi** [comment]
Thanks for the detailed report.  I believe TF version 0.12 introduced support for cudnn v5.1 with cuda 8.0.  It may be required on OSX.

**Comment by gunan** [comment]
In MacOSX, 0.11 (final, non-rc) and 0.12 both require CuDNN 5.1 if you are using our prebuilt packages.
in 0.11 rc versions, we noticed a problem in our builder machines where there were discrepancies in mac cudnn versions, so please install cudnn 5.1, then upgrade to either 0.11.0 (final) or 0.12.0rc0.
