### ISSUE TITLE
Tensorflow eager execution via C++ API

### ISSUE THREAD

**Issue by amitvarshney00** [tensorflow/tensorflow#59257]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.10

### Custom Code

Yes

### OS Platform and Distribution

Linux

### Current Behaviour?

```shell
I was wondering if there is a way to run Tensorflow in eager mode when the Ops are created using the C++ API. For example consider the following code


#include <vector>
#include <iostream>

#include <tensorflow/cc/client/client_session.h>
#include <tensorflow/cc/framework/scope.h>
#include <tensorflow/cc/ops/standard_ops.h>
#include <tensorflow/core/framework/tensor.h>
#include "tensorflow/cc/framework/gradients.h"

using namespace tensorflow;

int main() {
    Scope root = Scope::NewRootScope();
    
    ClientSession session(root);
    
    auto c1 = ops::Const(root, { {1.0, 2.0} });
    auto m = ops::MatMul(root, c1, { {3.0}, {4.0} });
    auto m2 = ops::Exp(root, m);
    auto m3 = ops::ReduceSum(root, m2, -1);
    
    std::vector<Tensor> outputs;
    TF_CHECK_OK(session.Run({m3}, &outputs));
    
    std::cout << "Value: " << outputs[0].DebugString() << std::endl;
    
    return 0;
}
```

In the above example, the tensors `m`, `m2` and `m3` are not computed until the graph is run using the `session.Run(...)` command which makes debugging very hard. Is there a way to enable execution similar to the eager execution in Python so that debugging is easier?
```


### Standalone code to reproduce the issue

```shell
#include <vector>
#include <iostream>

#include <tensorflow/cc/client/client_session.h>
#include <tensorflow/cc/framework/scope.h>
#include <tensorflow/cc/ops/standard_ops.h>
#include <tensorflow/core/framework/tensor.h>
#include "tensorflow/cc/framework/gradients.h"

using namespace tensorflow;

int main() {
    Scope root = Scope::NewRootScope();
    
    ClientSession session(root);
    
    auto c1 = ops::Const(root, { {1.0, 2.0} });
    auto m = ops::MatMul(root, c1, { {3.0}, {4.0} });
    auto m2 = ops::Exp(root, m);
    auto m3 = ops::ReduceSum(root, m2, -1);
    
    std::vector<Tensor> outputs;
    TF_CHECK_OK(session.Run({m3}, &outputs));
    
    std::cout << "Value: " << outputs[0].DebugString() << std::endl;
    
    return 0;
}
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @amitvarshney00 !
You can enable eager execution in C++ using eager executor class.
```
int main() {
    // Enable eager execution
    TF_Status* status = TF_NewStatus();
    tf::EagerExecutor executor(status);
    if (TF_GetCode(status) != TF_OK) {
        std::cerr << "Error enabling eager execution: " << TF_Message(status) << std::endl;
        return 0;
    }

```
Attached relevant[ thread ](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/eager/eager_executor.h#:~:text=class%20EagerExecutor%20%7B)for reference.

Thank you!

**Comment by amitvarshney00** [comment]
Thanks @mohantym 

This looks promising. I looked at the code, and it was not very clear to me how to use the `EagerExecutor` class. Would it be possible for you to outline how can I modify the code that I shared so that the TF code executes eagerly. 

Thank you!

**Comment by mohantym** [comment]
Hi @sachinprasadhs !

Could you look at this query.

Thank you!

**Comment by amitvarshney00** [comment]
Hi @sachinprasadhs - Just curious if you have any update on this?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
