### ISSUE TITLE
CUDA version

### ISSUE THREAD

**Issue by MaxEAB** [tensorflow/tensorflow#59255]
Hi, Which is the CUDA version that is recommended for TF 2.11?

Is CUDA 11.7 compatible?

**Comment by DURGESH716** [comment]
Hello @MaxEAB 

I think CUDA version 11.2 is recommended for TensorFlow 2.11.0

Please refer the below official documentation on TensorFlow versions compatible with CUDA versions 
https://www.tensorflow.org/install/source#gpu

**Comment by DURGESH716** [comment]
@MaxEAB If you have any doubt regarding TensorFlow and CUDA versions, you are free to ask,
Also If not, I request @tiruk007 to close this issue

**Comment by MaxEAB** [comment]
Hi, Thanks for the reply. Are there any known issues with using CUDA 11.7? Or is it the case that it was never tested?

**Comment by DURGESH716** [comment]
I do not have knowledge about CUDA 11.7, whether tested or not. 
But I recommend you to use the specified versions given by the organization, 

i.e, tensorflow-2.11.0 with 11.2

**Comment by DURGESH716** [comment]
@MaxEAB, Hey if you have any other queries you can put them here. 
Else close the issue with completed....

**Comment by tiruk007** [comment]
@MaxEAB 
In addition to @DURGESH716 pointers,

- Could you please refer to the following links:

> 1.[Tested build configurations](https://www.tensorflow.org/install/source_windows#cpu) for Windows.

> 2.[Tested build configurations](https://www.tensorflow.org/install/source#cpu) for Linux.

> 3.[Tested build configurations](https://www.tensorflow.org/install/source#cpu_2) for Macos.
Let us know if it helps.

Thank you!
