### ISSUE TITLE
Update curl to 7.87.0

### ISSUE THREAD

**Issue by RamanSggs** [tensorflow/tensorflow#59251]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

No

### OS Platform and Distribution

Windows

### Python version

3.10

### Current Behaviour?

```shell
Security Vulnerabilities fixed in curl 7.87.0
```

### Standalone code to reproduce the issue

```shell
NA
```

### Relevant log output

_No response_</details>

**Comment by yongtang** [comment]
Curl has already been updated to 7.87.0 in master branch: https://github.com/tensorflow/tensorflow/pull/59164

**Comment by mihaimaruseac** [comment]
Closing as part of #59164. Thank you @yongtang !
