### ISSUE TITLE
issue "could not load dynamic library"

### ISSUE THREAD

**Issue by Kazn3** [tensorflow/tensorflow#59264]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf 2.10

### Custom Code

Yes

### OS Platform and Distribution

Windows 11

### CUDA/cuDNN version

CUDA=11.2 cuDNN=8.1

### Current Behaviour?

```shell
Tf doesn't find the dynamic library so i'm doing my stuff on my cpu. (sorry if there already is an answer, i didn't find anything that helped me)
```

### Standalone code to reproduce the issue

```shell
It happens every time
```

### Relevant log output

_No response_</details>

**Comment by DURGESH716** [comment]
Hello @Kazn3, Here are a few things you can try:

1. Ensure that the library is installed in the correct location. TensorFlow looks for the library in a specific location, so make sure that it is installed in the correct location.

2. Check your environmental variable. sometimes the environmental variable is not set correctly, check and set the path of the library.

3. If you are using a virtual environment, make sure that the library is installed in the virtual environment and not in the global environment.

4. Finally, you can try to reinstall the library and TensorFlow, this could fix any issues you are having.
