### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED while compiling model on GPU

### ISSUE THREAD

**Issue by gauravbaluni** [tensorflow/tensorflow#59269]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

No

### OS Platform and Distribution

Rocky linux

### Python version

3.9

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
CUDNN_STATUS_EXECUTION_FAILED
in tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc(5750): 'cudnnBatchNormalizationForwardTrainingEx( cudnn.handle(), mode, bn_ops, &one, &zero, x_descriptor.handle(), x.opaque(), x_descriptor.handle(), side_input.opaque(), x_descriptor.handle(), y->opaque(), scale_offset_descriptor.handle(), scale.opaque(), offset.opaque(), exponential_average_factor, batch_mean_opaque, batch_var_opaque, epsilon, saved_mean->opaque(), saved_inv_var->opaque(), activation_desc.handle(), workspace.opaque(), workspace.size(), reserve_space.opaque(), reserve_space.size())'
```

### Relevant log output

_No response_</details>

**Comment by UrmilPawar** [comment]
Hello, I am Urmil Pawar. I am just a beginner in open source contribution but I would like to give a try to your issue.Can you please explain me how to approach it

**Comment by DURGESH716** [comment]
Hello @UrmilPawar, Let me help you,
1. Firstly, You have to understand the problem well, it even includes the code provided above.
2. Then recall that whether you have encourtered such issue in your past working projects, if yes then it will become more easy for you to debug it.
3. else, finally confirm the solution from the official TensorFlow documentation and comment it.

**Comment by tilakrayal** [comment]
@gauravbaluni,
Could you please provide the CUDA and cuDNN version you are using and also provide the complete error log which helps us to debug the issue more effectively. Kindly confirm whether you are facing this issue while trying to run any code? Thank you!
