### ISSUE TITLE
Cannot able to install Tensorflow r0.12 in Windows 10 - HTTP error 404

### ISSUE THREAD

**Issue by kishorenayar** [tensorflow/tensorflow#5927]
I was following the documentation of the [tensorflow](https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html#pip-installation-on-windows) with respect to installing tensorflow in windows 10.

When I execute pip command I'm getting following error

**pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl**

Collecting tensorflow==0.12.0rc0 from https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl
  HTTP error 404 while getting https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl
  Could not install requirement tensorflow==0.12.0rc0 from https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl because of error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl
Could not install requirement tensorflow==0.12.0rc0 from https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl because of HTTP error 404 Client Error: Not Found for url: https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl for URL https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl

**Comment by mrry** [comment]
Oops! This file is now in place, so the installation should work if you try again. Please re-open the issue if you continue to have problems!
