### ISSUE TITLE
openCL delegate generates 'inf' values with a sequence of Dense/FullyConnected nodes.

### ISSUE THREAD

**Issue by Bahar-BM** [tensorflow/tensorflow#59276]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.10.1

### Custom Code

No

### OS Platform and Distribution

Android

### Mobile device

tested on Snapdragon 888, 865

### Current Behaviour?

```shell
The openCL delegate has an issue with a sequence of Dense/FullyConnected nodes. Our experiments have revealed that if we use a sequence of Dense layers in a special pattern, the corresponding tflite version of this model will generate a bunch of inf/nan values for some random indices in some runs. This issue happens with both FP16 and FP32 tflite versions. This issue can't be reproduced with the XNNPACK delegate
```

### Standalone code to reproduce the issue

```shell
We have implemented a small tool (with a comprehensive ReadMe) to reproduce the mentioned issue. Here is the link to the repository:
https://github.com/Bahar-BM/test_openCL
```

### Relevant log output

_No response_</details>

**Comment by Bahar-BM** [comment]
Hello, do you have any updates on this issue?

**Comment by grantjensen** [comment]
Hi all, I just ran through the instructions of https://github.com/Bahar-BM/test_openCL with cmake version=3.25.1 & NDK version=22.0.7026061. I ran into the following error when I ran `make`:
[openCL_inf_error_output.txt](https://github.com/tensorflow/tensorflow/files/10819243/openCL_inf_error_output.txt)
 
Please advise. Perhaps a different NDK version needs to be used?

**Comment by grantjensen** [comment]
By downloading your models, I was able to replicate the issue for sample_model_fp32.tflite. Two things. One, opts.is_precision_loss_allowed is obsolete. Two: if you use the default  TfLiteGpuDelegateOptionsV2, you will not obtain these inf issues. By prioritizing MIN_LATENCY, you open yourself up to accuracy issues. Try messing around with different options settings, and good luck with your project!
