### ISSUE TITLE
Missing fp16 ops when converting from TF to TFLite

### ISSUE THREAD

**Issue by longnp91** [tensorflow/tensorflow#59288]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): pip install
- TensorFlow version (or github SHA if from source): 2.11

**Provide the text output from tflite_convert**

```
[full_error.txt](https://github.com/tensorflow/tensorflow/files/10441958/full_error.txt)

error: failed while converting: 'main': 
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: AddV2, Cast, ConcatV2, Conv2D, DepthwiseConv2dNative, Elu, GatherV2, Max, Minimum, Mul, Pad, RealDiv, Relu, Sqrt, Sum, Transpose
```

**Standalone code to reproduce the issue** 
converter = tf.lite.TFLiteConverter.from_saved_model(tf_path)
tflite_model  = converter.convert()

**Comment by pjpratik** [comment]
@longnp91 The TF lite builtin library supports limited set of operators. The TF select ops can be added using [Select ops](https://www.tensorflow.org/lite/guide/ops_select) flags before converting.
```
converter = tf.lite.TFLiteConverter.from_saved_model(tf_path)
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_model = converter.convert()
```
The select ops compatibility list can be found [here](https://www.tensorflow.org/lite/guide/op_select_allowlist). Please refer to them and let us know if it helps. Thank you.

**Comment by longnp91** [comment]
> @longnp91 The TF lite builtin library supports limited set of operators. The TF select ops can be added using [Select ops](https://www.tensorflow.org/lite/guide/ops_select) flags before converting.
> 
> ```
> converter = tf.lite.TFLiteConverter.from_saved_model(tf_path)
> converter.target_spec.supported_ops = [
>   tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
>   tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
> ]
> tflite_model = converter.convert()
> ```
> 
> The select ops compatibility list can be found [here](https://www.tensorflow.org/lite/guide/op_select_allowlist). Please refer to them and let us know if it helps. Thank you.

I only want to use TFLITE_BUILTINS. Is there any way to do it? Do you plan to add these ops to TFLite in the future?

**Comment by pjpratik** [comment]
Hi @longnp91 . Sorry for the delay. 

@mohantym Can you please look at this.

**Comment by mohantym** [comment]
Hello @longnp91 !
Work around might be used lambda function of model and call it as concrete function from TFLite converter as mentioned in  [Fusion code lab instructions](https://colab.sandbox.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb) (  work for LSTM model without using Select ops syntax)

Could you a provide a sample toy model to replicate this issue as the some of ops  in error stack trace seems to be already  in [builtin ops list.](https://www.tensorflow.org/mlir/tfl_ops) . 

Thank you!

**Comment by longnp91** [comment]
> Hello @longnp91 ! Work around might be used lambda function of model and call it as concrete function from TFLite converter as mentioned in [Fusion code lab instructions](https://colab.sandbox.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb) ( work for LSTM model without using Select ops syntax)
> 
> Could you a provide a sample toy model to replicate this issue as the some of ops in error stack trace seems to be already in [builtin ops list.](https://www.tensorflow.org/mlir/tfl_ops) .
> 
> Thank you!

Hi @mohantym , I put the link to the toy model so that you can play with it.
https://1drv.ms/u/s!AqC1KsV1ElWIm641BhPm66XWhrbY9w?e=eBlbmu
I only have pb model folder. Therefore, using lambda function is not feasible for my problem.

Thanks!!

**Comment by mohantym** [comment]
Hi @longnp91 !

Sorry for the late response. 
I am able to get a lite model with select ops syntax. Attached [gist ](https://colab.sandbox.google.com/gist/mohantym/564a381f5b6bda05e6568c3eb9c320da/git_59288.ipynb) for reference.
Please let us know your from your end.

Thank you!

**Comment by longnp91** [comment]
> Hi @longnp91 !
> 
> Sorry for the late response.
> 
> I can see the ops are not created during tflite runtime and returning `op is neither a custom op nor a flex op`.
> 
> we can enable customs ops by adding `converter.allow_custom_ops=True` flag.
> 
> I was able to succesfuly convert into tflite model without using select ops. Please refer the [gist](https://colab.sandbox.google.com/gist/pjpratik/8c9b97a3f2a7a5f6cc1dae88ac78efba/59288.ipynb#scrollTo=VhkfjkQisRoI) and let us know if it helps.
> 
> Thank you!

Hi @mohantym , thanks for your help. I successfully convert this model to tflite. However, when I run this tflite with tflite interpreter. I got this error:
Traceback (most recent call last):
  File "/home/ct-dev/adas/tflite_conversion.py", line 101, in <module>
    interpreter.allocate_tensors()
  File "/home/ct-dev/.venv/lib/python3.8/site-packages/tflite_runtime/interpreter.py", line 513, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: Encountered unresolved custom op: Pad.
See instructions: https://www.tensorflow.org/lite/guide/ops_custom Node number 0 (Pad) failed to prepare.Encountered unresolved custom op: Pad.
See instructions: https://www.tensorflow.org/lite/guide/ops_custom Node number 0 (Pad) failed to prepare.
Do you have any suggestion?

Thank you!!

**Comment by pjpratik** [comment]
Hi @longnp91 

For the custom ops, we need to define the op and register that op in the kernel.

Please refer the [custom operators](https://www.tensorflow.org/lite/guide/ops_custom) for the detailed usage and implementation of custom ops. This is particularly helpful when we need to have specific op which is not available in TFLite builtins.  

Thank you.
