### ISSUE TITLE
Tensorflow data validation-visualize_statistics()-Not working on databricks

### ISSUE THREAD

**Issue by avssridhar** [tensorflow/tensorflow#59284]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf2.8

### Custom Code

Yes

### Current Behaviour?

```shell
I am unable to display the output of tfdv.visualize_statistics() output on databricks where as the same is working on local system.

Is it because that facets are not supported on databricks? Please provide a solution on how I can use modules of tensorflow data validation library on databricks.
```

### Standalone code to reproduce the issue

```shell
tfdv.visualize_statistics()

#link
https://www.tensorflow.org/tfx/data_validation/get_started
```

### Relevant log output

_No response_</details>

**Comment by avssridhar** [comment]
Thanks a lot. It worked. 

Is there any way the output displayed can be consumed as a CSV?

**Comment by tiruk007** [comment]
@avssridhar 
Could you please close the issue if it is resolved ?

Thank you!

**Comment by Deweyave** [comment]
I'm. Coming down Main Street to end well to the highway 



Get BlueMail for Android
