### ISSUE TITLE
No quantized winograd convolution in tflite

### ISSUE THREAD

**Issue by multiverstack-intellif** [tensorflow/tensorflow#59289]
Winograd accelerate convolution both in float and int computation, I'm curious why there is no winograd convolution op in TFLite.  Weight transform is needed before weight quantization to keep accuracy as much as possible and then a new winograd_conv op is needed to handle the quantized transformed weight. 
Is there any concern about adding a winograd conv op?

**Comment by sushreebarsa** [comment]
@multiverstack-intellif Sorry for the late response!
In order to expedite the trouble-shooting process here, could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thanks!

**Comment by sushreebarsa** [comment]
Closing as a stale. Please feel free to reopen if you still have any concern.
Thank you!
