### ISSUE TITLE
checkpoints file's max_to_keep not working

### ISSUE THREAD

**Issue by ericyue** [tensorflow/tensorflow#5929]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

cannot find any related post in the web

### Environment info
Operating System:

centos6.5   , tensorflow 0.11.0 without gpu(cpu only)

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

```
tf.train.Saver(max_to_keep = 5)
then
saver.save(sess, checkpoint_file, global_step=step)
```
### What other attempted solutions have you tried?
***IMPORTANT*** 
I run the same code in my laptop, it's right with only 5 latest checkponits
**but** in the centos server , it generate unlimited checkponits files and the disk almost full

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

no error log

**Comment by ericyue** [comment]
update:
I try the tensorflow 0.12rc   , same problem

**Comment by poxvoculi** [comment]
From your two experiments the problem seems possibly centos6.5 specific, but not TF version specific.  The max_to_keep feature is implemented in this file:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/saver.py
in a function called _MaybeDeleteOldCheckpoints.  It would be interesting to know whether this function is being called correctly, and if so whether the old file recognition or deletion is failing.  Add some print statements?

You might look first in your logs to see whether there are any messages about this.

**Comment by ericyue** [comment]
I found that when run to save.py line 1157, the "checkpoint_prefix" variable has double slash like "checkpoint/adagrad-lr0.01-fs200-b10-u128.64.64.32//checkpoint.ckpt-6700.index"
**simply replace "//" with "/" and it's worked**

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/saver.py#L1157

**Comment by ericyue** [comment]
maybe a bug about file_io?

**Comment by poxvoculi** [comment]
@concretevitamin: can the checkpoint_prefix path component be improved?

**Comment by concretevitamin** [comment]
@ericyue: what's your `checkpoint_path`, when passed to `save()`?  We'd need to figure out whether this is related to the user-passed argument or something inside (e.g. file_io).

**Comment by ericyue** [comment]
checkpoint_path is something like "./checkpoint/model_xxxx//checkpoint.ckpt"
I noticed that the double slash is passed by myself.
but , why this got error on centos , mac works right?

**Comment by concretevitamin** [comment]
My guess is a quirk in the file system.  Since the issue has been identified I'm going to close this.

**Comment by ericyue** [comment]
@concretevitamin   @poxvoculi   can you help me about this issue ?  checkpoint ploblem. https://github.com/tensorflow/tensorflow/issues/6326

**Comment by ericyue** [comment]
@concretevitamin  @poxvoculi  can you help to solve this? also checkpoint ploblem https://github.com/tensorflow/tensorflow/issues/6326f

**Comment by kesinger** [comment]
I ran into the same thing with the same fix using tf 1.2. I noticed that in file_io.py get_matching_files does a string comparison to check files, and I'd put good odds on this (or something similar) being the culprit.

**Comment by jowettcz** [comment]
Also have same problems. More and more big checkpoints easily cause the resource exhausted problems, can someone look into it, thanks a lot!

**Comment by poxvoculi** [comment]
@jowettcz I don't understand what "same problems" is.  This issue was closed a while ago as a quirk of centos handling // in pathnames differently.

**Comment by kesinger** [comment]
@poxvoculi I'm not running centos (ubuntu 16.04) and I ran into this.  

(Also I don't know how I un-assigned @concretevitamin ?)

**Comment by poxvoculi** [comment]
@kesinger I think @concretevitamin is no longer working at Google, but maybe he's still responding to issues on GitHub.  Can you confirm whether, like @ericyue, you are passing a pathname with an unusual construction, like //, that can be avoided?

I see that a significant change to get_matching_files in file_io.py was submitted in May 2017.  Are you using a TF version that has it?

**Comment by yselivonchyk** [comment]
I observe similar behaviour: at some random points in time saver starts to consistently ignore max_to_keep parameter and does not delete older checkpoints.

I wish I could provide more info.

**Comment by smatmo** [comment]
Same here.

In 
`
saver = tf.train.Saver(max_to_keep=1)
`
...
`
saver.save(sess, result_path + "/model.ckpt", global_step=save_num, write_meta_graph=False)
`
The '/' before model.ckpt makes the difference whether my 1 Terrabyte quota is exhausted over night or not. Both on Ubuntu 14 and Scientific Linux 7.
