### ISSUE TITLE
base class order for tensorflow distributions

### ISSUE THREAD

**Issue by dustinvtran** [tensorflow/tensorflow#5930]
this is a feature request for `tf.contrib.distributions`. on master (i.e., beyond version r0.11), tensorflow distributions require that the first parent class is Distribution.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/distributions/python/ops/distribution.py#L136-L138

this is a problem for our work with random variables in edward, which requires that random variable classes are first and Distribution is second:

https://github.com/blei-lab/edward/blob/master/edward/models/random_variable.py#L35
https://github.com/blei-lab/edward/blob/master/edward/models/random_variables.py#L33

i chatted with @ebrevdo and @jvdillon about this a few weeks ago. they said it's possible to change. (i'm adding a GitHub issue to formalize the request.) can i help in any way? it is a high priority to fix for edward as it breaks all random variable support.

**Comment by ebrevdo** [comment]
Testing the fix now.

**Comment by gokceneraslan** [comment]
It works.

**Comment by gokceneraslan** [comment]
Could you please merge https://github.com/tensorflow/tensorflow/commit/77cfa97ac784212130e97bc6fa9e6f8acfc86c08 to `r0.12` branch as well?

**Comment by gokceneraslan** [comment]
Any news? Should we wait until 1.0 release?

**Comment by ebrevdo** [comment]
This is fixed at head and will be in the next rc

**Comment by stonebig** [comment]
excuse me if it's the wrong place to ask. About when do you intend to do Tensorflow-0.13rc ?

**Comment by ebrevdo** [comment]
This should be fixed in the RC.

**Comment by dustinvtran** [comment]
just to confirm, this hasn't been fixed in any of the <1.0.0 releases yet, and is only fixed in the 1.0.0-alpha release.

**Comment by ebrevdo** [comment]
Looks like
