### ISSUE TITLE
Feature Request tf.data.Dataset.from_tensor_slices with np.memmap

### ISSUE THREAD

**Issue by jenkspt** [tensorflow/tensorflow#59306]
I'm interested in being able to do the following
```python
arr = np.memmap('train.bin', dtype=np.uint16)
ds = tf.data.Dataset.from_tensor_slices(arr)
```
without loading the entire array `arr` into memory.

**Comment by gaikwadrahul8** [comment]
Hi, @SuryanarayanaY 

Could you please look into this ? Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @jenkspt ,
tf.data.Dataset has a function `from_generator() `which will take a `generator` as argument and iterates the data generator which makes it possible to not required to load entire dataset into memory during training.Please refer to attached [source](https://www.tensorflow.org/api_docs/python/tf/data/Dataset?version=nightly#from_generator) for more details of this function.The main condition here is the `generator` object should support `iter()` function.

```
arr = np.memmap('train.bin', dtype=np.uint16)
def generator():
    return iter(arr)
dataset = tf.data.Dataset.from_generator(
    generator=generator,
    #output_signature=() #based on the data
)
```

The dataset can be passed to `model.fit(dataset,epoch=3)` for model training.Please refer to the detailed [resource](https://www.tensorflow.org/guide/data) here.

**Comment by jenkspt** [comment]
I'm finding that using the generator is very very slow. 
It seems like the use of a memory mapped array could be a very useful special case of `tf.data.Dataset.from_tensor_slices`.

**Comment by SuryanarayanaY** [comment]
@jenkspt ,
At present `tf.data.Dataset.from_tensor_slices` loads all the data into Memory.If there is a thought in your mind how you want to implement in faster way than using the `from_generator()` please feel free to share.

**Comment by jenkspt** [comment]
I'm finding that in eager mode the memory mapped array is not loaded into memory. Additional documentation on the copy semantics of `tf.data.Dataset.from_tensor_slices` would be helpful -- but I'm fine closing this issue for now.
