### ISSUE TITLE
How to change specific body line colour eg. Hip-Knee-Ankle line in swift 

### ISSUE THREAD

**Issue by IBSApple** [tensorflow/tensorflow#59312]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML', 'Metal']

### Custom Code

Yes

### OS Platform and Distribution

MacOS

### Mobile device

iPhone X

### Current Behaviour?

```shell
Unable to change specific body line colour eg. Hip-Knee-Ankle line in swift
```

### Standalone code to reproduce the issue

```shell
How to change specific body line colour eg. Hip-Knee-Ankle line in swift
```

### Relevant log output

_No response_</details>

**Comment by IBSApple** [comment]
??

**Comment by mohantym** [comment]
Hi @IBSApple ! 
Thanks for bringing it again. Trying to get a working solution based on this [code snippet](https://github.com/tensorflow/examples/blob/master/lite/examples/pose_estimation/ios/PoseEstimation/UI/Views/OverlayView.swift) (we can the change color of keypoints probably  from here).

Will update once it is done.  Keeping it open till then.

(Possible Duplicate to #56332 though )

Thank you!

**Comment by mohantym** [comment]
@IBSApple !
It would be possible to change the color of concerned keypoints once they have been detected from below code 

```
private static let lines = [
    (from: BodyPart.leftWrist, to: BodyPart.leftElbow),
    (from: BodyPart.leftElbow, to: BodyPart.leftShoulder),
    (from: BodyPart.leftShoulder, to: BodyPart.rightShoulder),
    (from: BodyPart.rightShoulder, to: BodyPart.rightElbow),
    (from: BodyPart.rightElbow, to: BodyPart.rightWrist),
    (from: BodyPart.leftShoulder, to: BodyPart.leftHip),
    (from: BodyPart.leftHip, to: BodyPart.rightHip),
    (from: BodyPart.rightHip, to: BodyPart.rightShoulder),
    (from: BodyPart.leftHip, to: BodyPart.leftKnee),
    (from: BodyPart.leftKnee, to: BodyPart.leftAnkle),
    (from: BodyPart.rightHip, to: BodyPart.rightKnee),
    (from: BodyPart.rightKnee, to: BodyPart.rightAnkle),
  ]

```

 and set color of the keypoints using below code snippet

`context.setStrokeColor(UIColor.blue.cgColor)
`
at line 65 .

Would it be possible to close this as duplicate to #56332 and track it there only.

Thank you!
