### ISSUE TITLE
Hey, I created new env with python=3.8.5 but I didn't fix it. Before install detectron2, I installed this packages:

### ISSUE THREAD

**Issue by Aiden2022123** [tensorflow/tensorflow#59329]
Hey, I created new env with python=3.8.5 but I didn't fix it. Before install detectron2, I installed this packages:
```
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
conda install -c bottler nvidiacub
conda install jupyter
pip install scikit-image matplotlib imageio plotly opencv-python
pip install black usort flake8 flake8-bugbear flake8-comprehensions
conda install pytorch3d -c pytorch3d
```
After that I am running this command "python -m pip install 'git+https://github.com/facebookresearch/detectron2.git' "
I get same error.

_Originally posted by @EdibHamzaArslan in https://github.com/facebookresearch/detectron2/issues/4748#issuecomment-1396214415_

**Comment by EdibHamzaArslan** [comment]
Why issue is closed? Did you solve it?
