### ISSUE TITLE
"tflite-model-maker" package is not possible to install on Windows OS

### ISSUE THREAD

**Issue by HripsimeS** [tensorflow/tensorflow#59323]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### Current Behaviour?

```shell
Hello. I am trying to install **tflite-model-maker** package in order to use it for training of mobile models. I found only once source for the installation https://pypi.org/project/tflite-model-maker/

I have tried all 3 methods mentioned there, but every time I try to import the package, there is always some issues or errors.
In all cases the issue is connected mostly with **scann** package.
Could not find a version that satisfies the requirement scann==1.2.6 (from tflite-model-maker) (from versions: none)
No matching distribution found for scann==1.2.6 

Do you know how is possible to successfully install tflite-model-maker package for Windows 11? Thanks a lot in advance!
```

### Standalone code to reproduce the issue

```shell
https://pypi.org/project/tflite-model-maker/
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@HripsimeS 
Please try to install the package using a virtual environment and try to install the package using `pip install --no-dependencies tflite-model-maker`. Could you please refer to the similar [issue_1](https://github.com/tensorflow/tensorflow/issues/59261) & [issue_2](https://github.com/tensorflow/tensorflow/issues/58680) and let us know if it helps.

Thank you!

**Comment by HripsimeS** [comment]
I could install tflite-model-maker with python 3.8 using the following command pip install tflite-model-maker-nightly
And training runs good also for mobile models.

**Comment by tiruk007** [comment]
@HripsimeS 
Could you please close this issue if it is resolved ?
