### ISSUE TITLE
http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz failing to download

### ISSUE THREAD

**Issue by tushu1232** [tensorflow/tensorflow#5933]
sidra@ironheart:/tmp$ wget http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz
--2016-11-29 14:23:24--  http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz
Resolving download.tensorflow.org (download.tensorflow.org)... 216.58.208.240, 2a00:1450:4007:80e::2010
Connecting to download.tensorflow.org (download.tensorflow.org)|216.58.208.240|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 88931400 (85M) [application/x-compressed-tar]
Saving to: ‘inception-2015-12-05.tgz’

inception-2015-12-05.tgz                             0%[                                                                                                                 ]  15.34K  --.-KB/s    in 0.1s    

2016-11-29 14:23:29 (113 KB/s) - Read error at byte 15709/88931400 (Connection reset by peer). Retrying.

--2016-11-29 14:23:30--  (try: 2)  http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz
Connecting to download.tensorflow.org (download.tensorflow.org)|216.58.208.240|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 88931400 (85M), 88915691 (85M) remaining [application/x-compressed-tar]
Saving to: ‘inception-2015-12-05.tgz’

inception-2015-12-05.tgz                             0%[                                                                                                                 ]  30.62K  94.9KB/s    in 0.2s    

2016-11-29 14:23:31 (94.9 KB/s) - Read error at byte 31359/88931400 (Connection reset by peer). Retrying.

--2016-11-29 14:23:33--  (try: 3)  http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz
Connecting to download.tensorflow.org (download.tensorflow.org)|216.58.208.240|:80... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 88931400 (85M), 88900041 (85M) remaining [application/x-compressed-tar]
Saving to: ‘inception-2015-12-05.tgz’

inception-2015-12-05.tgz                             0%[                                                                                                                 ]  45.91K  --.-KB/s    in 0.1s    

2016-11-29 14:23:34 (113 KB/s) - Read error at byte 47009/88931400 (Connection reset by peer). Retrying.

**Comment by jart** [comment]
Will be fixed by a Bazel change being pushed soon.

**Comment by jart** [comment]
This has been fixed by https://github.com/bazelbuild/bazel/commit/ed7ced0018dc5c5ebd6fc8afc7158037ac1df00d. Try using Bazel at HEAD. A new Bazel will be cut in a few days. As soon as that happens, the TensorFlow repository will be updated to use multiple mirrors for each external file.
