### ISSUE TITLE
update python.platform.flags

### ISSUE THREAD

**Issue by haeusser** [tensorflow/tensorflow#5936]
... in particular, merge glags's DEFINE_multi_float etc.

Is this planned for or should I do it and send a PR?

**Comment by mrry** [comment]
This is not planned, and we are no longer encouraging users to depend on TensorFlow's implementation of flag parsing (which is a simple wrapper around `argparse`, used for our example scripts).

If you need specific features from [`python-gflags`](https://github.com/google/python-gflags), we'd encourage you to depend on that library directly.
