### ISSUE TITLE
TFLiteConverter adds (de)quantization blocks before and after operations on a weight variable

### ISSUE THREAD

**Issue by MalekItani** [tensorflow/tensorflow#59390]
Hello

I'm trying to convert a TensorFlow model to TFLite. I want the model to maintain a non-trainable state vector that gets updated at every inference. I've implemented this using `self.add_weight` with `trainable=False`, as shown in the example.

### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux KDE Neon 5.26
- TensorFlow installation (pip package or built from source): pip installation
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.11.0

### 2. Code

```

import tensorflow as tf
from keras import initializers

# Class Definition
class Net(tf.keras.Model):
    def __init__(self):
        super(Net, self).__init__()
        
        self.my_weight = self.add_weight("MyWeight",    
                                         shape=[1, 10, 1],
                                         initializer=initializers.get('Zeros'),
                                         trainable=False)

    @tf.function(input_signature=[tf.TensorSpec(shape=[1, 5, 1], name='MyInput'),])
    def call(self, x):
        x = x + self.my_weight[:, -5:, :]
        self.my_weight.assign(value=tf.concat((self.my_weight[:, -5:, :], x[:, :5, :]), axis=1))

        return x

import numpy as np

X = np.random.random((1, 5, 1)).astype(np.float32)

model = Net()

for i in range(5):
    Y = model(X, training=False)

# Save Model
model_path = "my_saved_model"
tf.saved_model.save(model, model_path)
model.summary()

def representative_dataset():
  for i in range(50):
    yield {
      "MyInput": np.random.random((1, 5, 1)).astype(np.float32)
    }

converter = tf.lite.TFLiteConverter.from_saved_model(model_path)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8  # or tf.uint8

# Convert the model 
tf_lite_model = converter.convert()

# Save the converted model 
open('my_tflite_model.tflite', 'wb').write(tf_lite_model)

```

### 3. Conversion Issue
The conversion process works fine, but when I draw the model on Netron, it seems that the converter adds quantize/dequantize operations everytime the variable is read or updated. Is there a way to tell the converter to quantize this variable from the start, without having to quantize and dequantize everytime it accesses it?

![model](https://user-images.githubusercontent.com/37956289/213896735-1390ffa0-2343-47bd-89aa-358b4297f87b.png)

On another note, my aim is to run such a model on an EdgeTPU, but the EdgeTPU compiler complains about dynamic-sized tensors, without indicating where they are. I believe the culprits are CallOnce, ReadVariable and/or AssignVariable, but I'm not entirely sure how to get around them. Any ideas? Thanks.

**Comment by pjpratik** [comment]
I was able to reproduce this issue on TF 2.11. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/1d2dc72a5339b2f14c96c10e92dc9453/59390.ipynb). 

@mohantym can you please check this issue. Thanks.

**Comment by mohantym** [comment]
Ok @MalekItani !

We can [tfmot ](https://www.tensorflow.org/model_optimization/api_docs/python/tfmot/quantization)api to decide quantization for the layers  for which quantization need to be disabled/enabled. We can also [tfl.quantization_debugger ](https://www.tensorflow.org/lite/performance/quantization_debugger)to disable quantization for suspected layers.

Regarding Dynamic size Tensor issue in Edge TPU. Could you test with  below workarounds.

 #Yield representative dataset dtype as np.int8

```

def representative_dataset():
  for i in range(50):
    yield {
      "MyInput": np.random.random((1, 5, 1)).astype(np.int8)
    }
....
.....
converter.target_spec. supported_types = [ tf.int8 ] # or tf.uint8
```
Reference:

 
Thank you!

**Comment by MalekItani** [comment]
Thanks for the help. I'm not entirely sure I understand what you mean. I don't want to selectively enable/disable quantization. I want the converter to properly quantize all the weights and biases, including the one I've added. From what I understand, TFLiteConverter seems to do this well for other weights (kernel weights in Conv layers, for example), but it strangely doesn't seem to quantize "MyWeight" and instead needs explicit blocks to do it. Is this supposed to happen? Is it specifically because I'm updating the variable?
Also, even if I try to use ```tfmot.quantization.keras.quantize_model```, I get ```ValueError: `to_quantize` can only either be a tf.keras Sequential or Functional model```, which I'm afraid means I can't quantize the model (using tfmot) as is without rewriting it in one of those two formats. Is that it?

Additionally, the workaround you suggested for EdgeTPU gives ```ValueError: Cannot set tensor: Got value of type INT8 but expected type FLOAT32 for input 0, name: serving_default_MyInput:0```.

**Comment by mohantym** [comment]
Ok @MalekItani !
Thanks for the update . Yeah! all the nodes appearing in lite model are decided by TFLite Converter api as you said. 
Could you just test with below snippet in your edge device and let us know .  Normally for integer quantisation , recommended yield type is int8.

```

def representative_dataset():
  for i in range(50):
    yield {
      "MyInput": np.random.random((1, 5, 1)).astype(np.int8)
    }
....
.....
converter.target_spec. supported_types = [ tf.int8 ] # or tf.uint8
```

Thank you!

**Comment by MalekItani** [comment]
I opened [this](https://discuss.tensorflow.org/t/tfliteconverter-adds-de-quantization-blocks-before-and-after-operations-on-a-weight-variable/14479) discussion on the TensorFlow forum. It doesn't seem to be getting any attention. 
Do you know if the behavior I'm getting is expected? If so, how can I fix it?

**Comment by MalekItani** [comment]
Still looking for assistance. Any ideas?

**Comment by zichuan-wei** [comment]
Hi @MalekItani Looking at your code, I think this is expected behaviour. The input and weight to the graph are both float32, and since every time after the execution, you're writing the results back to "My_weight" we have to do the dequant and quant to ensure the datatype and value are still valid.  

If you didn't need to write back to the weight, I would recommend you use tf.const instead for weight. Please let us know this is a valid fix for you

**Comment by MalekItani** [comment]
That is true, I need to write back to the weight after execution. However, I don't see how the input and weights (besides "my_weight") are float32 for the following reasons:

1. I provide a representative dataset to TFLiteConverter, so I expect the converter to perform full integer quantization.
2. I set inference input/output types to np.int8, so the model expects integer input/output.
3. The model does quantization after the read, and dequantization after the operation on the input data. So, if anything, it is the variable "my_weight" that is stored as float32.

Is this line of reasoning correct? Am I missing a particular option to allow "my_weight" to be stored as a np.int8?

**Comment by zichuan-wei** [comment]
1 is correct, for 2, there are some complexities, the original model in keras is taking float32 as input & output, as such "my_weight" has to be float32 to enable the correct execution in keras. as such, when we go to 3, it has to be treated as float even in the quantized execution, because variable tensors are stored as is. 

My understanding is that if you enforce "my_weight" as a int8, then it's no longer a valid graph in keras

**Comment by alankelly** [comment]
The dynamic tensor probably comes from VarHandle. This was fixed [here](https://github.com/tensorflow/tensorflow/commit/42ac9b7ca68a07accac5f6421f6bdbfff8334c7b).

Either wait for TF 2.12 to come out or compile TFLite yourself and the dynamic tensor should go away.

**Comment by MalekItani** [comment]
Thank you @zichuan-wei, now I understand the issue. With typical model weights (i.e. convolution layer weights), this problem doesn't appear, so I'm guessing the converter can successfully map them to int8 constants even though they were initialized as float32 in keras. This leads me to believe that the weight value assignment prevents the converter from initializing the weight as int8. Is there currently any way of maintaining a quantized, writeable state at all, without having to pass the state as input? For example, can the converter produce quantized, stateful LSTMs? If so, how does it maintain this quantized state?

VarHandle does seem to be the issue @alankelly. Thank you very much!

**Comment by pkgoogle** [comment]
Hi @MalekItani, it seems we never closed the loop on this issue -- are you satisfied w/ the above resolution? Thanks.

**Comment by MalekItani** [comment]
I never really found a solution to this, but it is no longer a relevant problem to me.

**Comment by puddly** [comment]
For anyone else still running into this issue, I was able to solve it by enabling experimental variable quantization:

```python
converter._experimental_variable_quantization = True
```
