### ISSUE TITLE
Will the tensorflow support nesterov momentum optimization?

### ISSUE THREAD

**Issue by qixianbiao** [tensorflow/tensorflow#594]
Does anybody have experience about "momentum" and "nesterov momentum"?
 
does the "nesterov momentum" perform much better than than "momentum"?

**Comment by eduardo-elizondo** [comment]
@qixianbiao working on this right now.

**Comment by Ivanopolo** [comment]
@eduardo-elizondo are there any news on that? Probably a branch with a draft implementation?

**Comment by mschonwe** [comment]
+1

**Comment by metap** [comment]
+1

**Comment by beopst** [comment]
+1. Any update on this?

**Comment by suiyuan2009** [comment]
ApplyNesterovMomentumOp's computation of grad is differ from other optimization op, we should overide some functions in optimizer.py

**Comment by siddharth-agrawal** [comment]
@vrv Has this issue been resolved?

**Comment by vrv** [comment]
Yup!
