### ISSUE TITLE
Tensorboard not showing charts after upgrade to 0.12rc0

### ISSUE THREAD

**Issue by oliveirabc** [tensorflow/tensorflow#5941]
Tensorboard charts (scalars, distributions, histograms) don't show up after upgrading to 0.12rc0.
No errors are logged on the server.
Check the images below to get a sense of the problem.

Operating System: Ubuntu 15.10

1. pip installation from here:
Ubuntu/Linux 64-bit, CPU only, Python 3.4
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.0rc0-cp34-cp34m-linux_x86_64.whl

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.12.0-rc0

![tensorboard 0 11](https://cloud.githubusercontent.com/assets/11388492/20718925/46980fda-b652-11e6-852b-09a4abdf20b6.png)
![tensorboard 0 12rc0](https://cloud.githubusercontent.com/assets/11388492/20718926/46aca26a-b652-11e6-842f-873425deeb89.png)

**Comment by danmane** [comment]
@oliveirabc We'll look into this this week.
Can you check if this reproduces using python2?

**Comment by oliveirabc** [comment]
Same thing on python2.

Don't know if this helps or not but here it goes. The images below show the html generated for both cases.

![tensorboard 0 12rc0](https://cloud.githubusercontent.com/assets/11388492/20830633/4ff7f01c-b879-11e6-9adc-ecaedd186592.png)
![tensorboard 0 11](https://cloud.githubusercontent.com/assets/11388492/20830635/50241b24-b879-11e6-95d0-64adf9fd713b.png)

**Comment by oliveirabc** [comment]
I was using an older version of Chromium.
Moved to Firefox and no problems there.
Closing the issue.

**Comment by jart** [comment]
How old was the version of Chromium you were using?

**Comment by oliveirabc** [comment]
I was using: Version 48.0.2564.116 Ubuntu 15.10 (64-bit)
