### ISSUE TITLE
Update Cmake README Doc Reflecting 0.12r

### ISSUE THREAD

**Issue by Carmezim** [tensorflow/tensorflow#5942]
Now with 0.12r would be interesting to update Readme as current status, instructions or simply reference the release?

**Comment by mrry** [comment]
What sort of update were you thinking? Please feel free to send a pull request improving the documentation!

**Comment by Carmezim** [comment]
Do you think updating the current status for officially supported and cleaning up all the requirements and  instructions replacing for your instructions on the finally closed (😄) #17 would be good? It could also  reference your blog post and the release notes.

Is there any unsupported limitations listed on the 0.12r to be kept?

If that looks good to you I can submit a PR with those first changes and gradually update with your feedback

**Comment by Carmezim** [comment]
I am closing this as I think it won't be relevant with the 0.12 release info available. I thought about adding pip instructions to cmake doc at the day after it came out submitting #6002 but isn't necessary.
