### ISSUE TITLE
Crash when running tf.image.combined_non_max_suppression

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59439]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
https://drive.google.com/drive/folders/1_bVEq3GcTqj8XDSmeSsR2cSS8D6_oUcR?usp=share_link
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@nimashiri 
Sorry for the late reply, If setting the `max_total_size` value to a large number may result in OOM error depending on the system workload. it is working as expected on Colab using TFv2.11 when passing a smaller value to the `max_total_size`. Could you please refer to the [tf.image.combined_non_max_suppression](https://www.tensorflow.org/api_docs/python/tf/image/combined_non_max_suppression#args) and find the gist  [here](https://colab.research.google.com/gist/tiruk007/5a9658a125dc93e7d0d30b214c2bab39/59439.ipynb) for reference. 

Thank you!

**Comment by mihaimaruseac** [comment]
@tiruk007 vulnerabilities arise when invalid arguments are passed. So replying with "you are holding it wrong" is not valid.

@nimashiri please report vulnerabilities outside of GitHub. Either via OSS VRP or via the security form. It seems the vulenrabilities reported on GitHub have a tendency of being mistreated by the first responders to these issues. Plus, it's not really good to report vulnerabilities in public directly.

**Comment by mihaimaruseac** [comment]
Not actionable, closing. Please report using the right channels.
