### ISSUE TITLE
How to infer  pose classification on single image?

### ISSUE THREAD

**Issue by aakash-chakraborty1995** [tensorflow/tensorflow#59432]
The first layer of the model needs shape of (None, 51). How to send the image as a feature tensor of 51 feature points which is also nothing but the feature taken as the pose points estimated by  MOVNET?

**Comment by gaikwadrahul8** [comment]
Hi, @aakash-chakraborty1995 

We see that the issue [template]( https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyze the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced. Thanks!
