### ISSUE TITLE
Can't convert custom model to tflite with model config and weights file being separate

### ISSUE THREAD

**Issue by codingzebra333** [tensorflow/tensorflow#59431]
Hi,
I am trying to convert a custom model to tflite with these steps:
```
#creates a custom model that I have previously defined (Resnet50 as a backbone (pretrained weights) + transformer encoder + MLP head)
model = create_model(classes=5)   
#the best weights file obtained after my custom model training
model.load_weights(model_weights_path)
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]  
tfmodel = converter.convert()
with tf.io.gfile.GFile(tf_lite_path +  'tflite_model' + ".tflite", 'wb') as f:
    f.write(tfmodel)
```
I do not get any output on this, no errors as well. The question is - is it possible to convert my custom model with creating the model (without saving it) and then loading the weights the way I have done? Is there any other way how to make my model smaller after training?

**Comment by tiruk007** [comment]
@codingzebra333 
Could you please provide complete code or Colab gist to replicate the issue reported here ?

Thank you!

**Comment by codingzebra333** [comment]
Hey, here is the colab file - https://colab.research.google.com/drive/13KYqJWwNQ-ju0APaqEaZj39wYodN0Uu8?usp=sharing 

Thank you!

**Comment by tiruk007** [comment]
Hi @codingzebra333 ,
 
When I try to execute the given code on Colab using TF v2.11, I get the following error:

`OperatorNotAllowedInGraphError: Exception encountered when calling layer 'tri_q_image_quality_transformer' (type TriQImageQualityTransformer).Using a symbolic tf.Tensor as a Python bool is not allowed: AutoGraph is disabled in this function. Try decorating it directly with @tf.function.`

As per above error decorate the `call` function with @tf.function in transformer_iqa.py file, I was able to convert the model to tflite model without any error. Could you please find the gist [here](https://colab.research.google.com/gist/tiruk007/a5c1f4993f572fa62a7f8cfd4e901957/untitled89.ipynb) for reference. 

Thank you!

**Comment by codingzebra333** [comment]
Hi!
Could you please share the file that you edited, because it is still not working for me? Thank you in advance!

**Comment by tiruk007** [comment]
@codingzebra333 
This is the [transformer_iqa.py](https://github.com/junyongyou/triq/blob/master/src/models/transformer_iqa.py) file where I add the @tf.function at 168th line before the `call` function. Could you please refer to the [screenshot](https://user-images.githubusercontent.com/111861663/215567152-b5cba95a-64f4-4927-802e-36675814f0d3.png) amd let us know if it helps .

Thank you !

**Comment by tiruk007** [comment]
@codingzebra333 
You can evaluate the tflite model by using `model.evaluate_tflite('model.tflite', test_data)`. Please refer to this [doc](https://www.tensorflow.org/lite/models/modify/model_maker/image_classification#:~:text=You%20can%20also%20evaluate%20the%20tflite%20model%20with%20the%20evaluate_tflite%20method.)
Could you please Close the issue if it resolves?

Thank you!

**Comment by codingzebra333** [comment]
Hey, using your suggested evaluation, I got an error: AttributeError: 'Functional' object has no attribute 'evaluate_tflite'. Supposedly, the issue is that the method I am trying to use is not present on the TFLite model class. But I have no idea how to fix it. Would really appreciate your help with this. Thank you in advance!

**Comment by tiruk007** [comment]
@codingzebra333
Could you please give a sample code to reproduce the issue ?

Thank you!

**Comment by tiruk007** [comment]
@codingzebra333
Could you please give a sample code to reproduce the issue ?

Thank you!

**Comment by codingzebra333** [comment]
Hey, [here](https://colab.research.google.com/drive/14zMCm0XaszVrUoWd9bMvBjSXSdPvSWuw#scrollTo=o3lYXU2CwMoG) is the sample code.

**Comment by tiruk007** [comment]
@codingzebra333 
Could you please provide an accessible code to replicate the issue ?

Thank you!

**Comment by codingzebra333** [comment]
You should be able to access it now!

**Comment by codingzebra333** [comment]
Hey, I tried different approach and got ValueError: Could not open tflite model. Here is the code: https://colab.research.google.com/drive/14zMCm0XaszVrUoWd9bMvBjSXSdPvSWuw#scrollTo=o3lYXU2CwMoG

**Comment by codingzebra333** [comment]
Hey, is it possible to get some insights regarding this issue? I even tried a different approach how to convert the model to tflite and I still can't evaluate the accuracy. I also provided both ways how I converted my .h5 file to .tflite in tha colab file.

**Comment by tiruk007** [comment]
@codingzebra333 
This issue is similar to #59684 . This issue will triage on #59684 . Could you please feel free to close this issue?

Thank you!
