### ISSUE TITLE
Crash when running tf.random.fixed_unigram_candidate_sampler

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59449]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
https://drive.google.com/drive/folders/1CAWUAcGHbpmwRCSM9dwRAhEZwMkilyVM?usp=share_link
```

### Relevant log output

_No response_</details>

**Comment by mihaimaruseac** [comment]
Not actionable, closing. Please report using the right channels.
