### ISSUE TITLE
Crash when running tf.math.unsorted_segment_max

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59442]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
https://drive.google.com/drive/folders/1ChGoSvXS7Q6vCZfak7bFBy8VKT-dNgXw?usp=share_link
```

### Relevant log output

_No response_</details>

**Comment by synandi** [comment]
Hi @nimashiri, The code shared above is executing in TF v2.11 and raising an error, without any crash. Please find the gist [here](https://colab.sandbox.google.com/gist/synandi/800944344c8b5eec8706d0c5e93efe3e/59442_2-11.ipynb). 
Please check the error below;
```
InvalidArgumentError: {{function_node __wrapped__UnsortedSegmentMax_device_/job:localhost/replica:0/task:0/device:CPU:0}} Encountered overflow when multiplying 6234597618814140938 with 8, result: -1 [Op:UnsortedSegmentMax]
```
Thank you!

**Comment by mihaimaruseac** [comment]
This is not a real vulnerability. Closing.

@dmc1778 please stop posting vulns on GitHub. Please consult SECURITY.md for how to properly and ethically disclose them.

**Comment by dmc1778** [comment]
Hi, this issues have been reported for a while. I didn't report any
vulnerability recently.

**Comment by mihaimaruseac** [comment]
I just went over these stale reports as the team responsible with security (my former team) has failed to react to them in time.

**Comment by dmc1778** [comment]
Ok. I finished running my fuzzer on tensorflow. Maybe in future I report
issues, I will never post anything about security related issues here
anymore. Anyways, thanks for your help.
