### ISSUE TITLE
Crash when running tf.math.unsorted_segment_min

### ISSUE THREAD

**Issue by nimashiri** [tensorflow/tensorflow#59443]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
https://drive.google.com/drive/folders/16gN6KPEFPRn7eBDb41W6FlJsUVGYl7pp?usp=share_link
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@nimashiri 
Sorry for the late reply,

- As this [comment](https://github.com/tensorflow/tensorflow/issues/59350#issuecomment-1399378528) suggests, the invalid inputs will lead to the crash. 
- It is working as expected on Colab using TFv2.11 when passing a smaller value to the `segment_ids`  and  `num_segments`
- On the CPU, values in segment_ids are always validated to be less than num_segments, or else an error is thrown for out-of-bound indices.  
- Could you please refer to the [tf.math.unsorted_segment_min](https://www.tensorflow.org/api_docs/python/tf/math/unsorted_segment_min) and find the gist [here](https://colab.research.google.com/gist/tiruk007/f99f59807267790aa708047199b99801/59443.ipynb) for reference.

Thank you!

**Comment by nimashiri** [comment]
> @nimashiri Sorry for the late reply,
> 
>     * As this [comment](https://github.com/tensorflow/tensorflow/issues/59350#issuecomment-1399378528) suggests, the invalid inputs will lead to the crash.
> 
>     * It is working as expected on Colab using TFv2.11 when passing a smaller value to the `segment_ids`  and  `num_segments`
> 
>     * On the CPU, values in segment_ids are always validated to be less than num_segments, or else an error is thrown for out-of-bound indices.
> 
>     * Could you please refer to the [tf.math.unsorted_segment_min](https://www.tensorflow.org/api_docs/python/tf/math/unsorted_segment_min) and find the gist [here](https://colab.research.google.com/gist/tiruk007/f99f59807267790aa708047199b99801/59443.ipynb) for reference.
> 
> 
> Thank you!

@tiruk007 Thanks for the reply. Would you please use my exact test case on the specified version and confirm whether you get crash?

**Comment by mihaimaruseac** [comment]
@nimashiri please report vulnerabilities outside of GitHub.

Also, please post code and error directly on Github issue if using this form.

**Comment by mihaimaruseac** [comment]
(finally, please always test against latest TF release, preferably also against latest nightly; this way duplicate reports won't be made)

**Comment by tiruk007** [comment]
@nimashiri 
I was able to reproduce the issue on colab using Tf v2.10 but I was able to execute the given code without crashing on colab using TF v2.11. Could you please use the latest version which is 2.11 and find the gist of [2.10](https://colab.research.google.com/gist/tiruk007/f5f549e92abbde1811ca943a3fdb36b1/59443_v2-10.ipynb#scrollTo=U7-lugLEbyEn) and  [2.11](https://colab.research.google.com/gist/tiruk007/3246ca838b806413a92ab44011788561/59443.ipynb).

Thank you!

**Comment by mihaimaruseac** [comment]
So this was fixed in 2.11 and this is a duplicate report. Closing.

**Comment by TheCrott** [comment]
@dmc1778 what fuzzer you used to find this issue and another crashes?

**Comment by dmc1778** [comment]
My own custom fuzzer.

**Comment by dmc1778** [comment]
This bug is not detected by my fuzzer, it is detected by DocTer.

**Comment by dmc1778** [comment]
> @dmc1778 what fuzzer you used to find this issue and another crashes?

This one is detected by DocTer. For other issues, I used FreeFuzz and my own custom fuzzer.

**Comment by TheCrott** [comment]
> 

Thanks

**Comment by TheCrott** [comment]
> > @dmc1778 what fuzzer you used to find this issue and another crashes?
> 
> This one is detected by DocTer. For other issues, I used FreeFuzz and my own custom fuzzer.

Thanks
