### ISSUE TITLE
Crash when running tf.math.unsorted_segment_sum

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59446]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

22.04

### Python version

3.9

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
https://drive.google.com/drive/folders/1jqZ2LurCCAgkS_IhR-X1DgTfLSsrBhDl?usp=share_link
```

### Relevant log output

_No response_</details>

**Comment by synandi** [comment]
Hi @nimashiri, The code shared above is executing in TF v2.11 and raising an error, without any crash. Kindly find the gist [here](https://colab.sandbox.google.com/gist/synandi/ae14754b8cec4b1bb102342e78fc4266/59446_2-11.ipynb).
Please check the error below;
```
InvalidArgumentError: {{function_node __wrapped__UnsortedSegmentSum_device_/job:localhost/replica:0/task:0/device:CPU:0}} Encountered overflow when multiplying 2675040094430872140 with 20, result: -1 [Op:UnsortedSegmentSum]
```
Thank you!

**Comment by mihaimaruseac** [comment]
Closing as reported wrongly. Not a vuln.
