### ISSUE TITLE
Segfault when running tf.math.unsorted_segment_sqrt_n

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59452]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

No

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
https://drive.google.com/drive/folders/1bRop6yaxdXjnbL8QvqZDg6LVnImpfZI_?usp=share_link
```

### Relevant log output

_No response_</details>

**Comment by gaikwadrahul8** [comment]
Hi, @nimashiri 

Apologize for the delay and I was able to replicate the issue on Google Colab, Here is [gist file](https://colab.research.google.com/gist/gaikwadrahul8/1ff9b95e0b32105838907824b2f4ad4d/-59452.ipynb) and code is getting crashed so I'll dig more into this issue and I'll update here soon. Thank you!

For your reference I have added screenshot of error log below, 

![image](https://user-images.githubusercontent.com/115997457/215553782-40adb551-19d9-4d28-a55e-dcc594fac1c5.png)

**Comment by gaikwadrahul8** [comment]
Hi, @nimashiri 

Please refer this [comment](https://github.com/tensorflow/tensorflow/issues/59448#issuecomment-1409110953) and Could you please help us with code snippet and error report in the issue itself ? Thank you!

**Comment by mihaimaruseac** [comment]
Not actionable, closing. Please report using the right channels.
