### ISSUE TITLE
Release notes indicate summary ops were deprecated

### ISSUE THREAD

**Issue by MadWombat** [tensorflow/tensorflow#5945]
The release notes at https://github.com/tensorflow/tensorflow/releases seem to indicate that scalar_summary and a few other *_summary ops were deprecated. Yet the docs for 0.r12 still list all the *_summary ops and do not mention deprecation. Also, I do not get any warnings when using the *_summary ops.

**Comment by poxvoculi** [comment]
Looks like 'deprecation' in this case is just a documentation feature...for now.  @danmane ?

**Comment by poxvoculi** [comment]
On closer examination, looks like the release notes incorporated meta data about a change that was rolled back.   It may be made in an upcoming release.
