### ISSUE TITLE
Crash when running tf.linalg.diag

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59451]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
https://drive.google.com/drive/folders/14nQzmoaY_GQwfaZd2vX_cHdKvEcF2Eax?usp=share_link
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@dmc1778 
Sorry for the late reply, I was able to reproduce the issue on colab using TF v2.10 but I was able to execute the given with code without crash or segfault in Linux VM on jupyter using TF v2.11. Please find the below screenshot for reference:
 ![screenshot](https://user-images.githubusercontent.com/111861663/217120492-bc783cb8-4d4d-497a-86b8-58ac6037f1b8.png)

Thank you!

**Comment by mihaimaruseac** [comment]
Fixed, duplicated
