### ISSUE TITLE
TFLite performance breakdown on GAN models seems inaccurate (using TFLite benchmarking tool)

### ISSUE THREAD

**Issue by judeharis** [tensorflow/tensorflow#59456]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

TF2.7

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04

### Bazel version

3.7.2

### Current Behaviour?

```shell
My goal in running these models in TFLite was to understand the performance breakdown for each type of layer within the GAN models. 

From the ESRGAN model the benchmarking tool reports the following: 
node type	count	avg_ms	avg %
CONV_2D	169	12217.5	89.00%
CONCATENATION	132	596.505	4.35%
TRANSPOSE_CONV	2	475.784	3.47%
LEAKY_RELU	136	319.739	2.33%
ADD	47	103.243	0.75%
MUL	11	14.042	0.10%

 There is a very limited number of TRANSPOSE_CONV layers which barely affect the model's performance. From my understanding of most GAN models, transposed convolutional layers are usually the bottleneck. Research papers have shown performance (latency) improvements across the network by simply accelerating the transposed convolutional layers, but how does it become so effective if these layers are only a small amount of the performance breakdown?

How reliable is the performance benchmarking tool for TFLite in profiling GAN models? Are these results accurate, or is there potential for error where inference time breakdown is represented accurately?
```

### Standalone code to reproduce the issue

```shell
I used the ERSGAN model and Style Transfer "magenta" model available at:  https://tfhub.dev/captain-pool/lite-model/esrgan-tf2/1  and https://tfhub.dev/google/lite-model/magenta/arbitrary-image-stylization-v1-256/int8/prediction/1 respectively.
I used the Benchmark Model binary available at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark compiled from T2.7 source code.

I simply ran the benchmarking tool with the following parameters:
./benchmark_model  --use_gpu=false //
--num_threads=1 //
--enable_op_profiling=true //
--graph=./models/esrgan.tflite //
--num_runs=2 //
--warmup_runs=0 //
--warmup_min_secs=0 //
--use_vm_sim_delegate=false //
--print_postinvoke_state=true //
--profiling_output_csv_file=test.csv
```

### Relevant log output

_No response_</details>

**Comment by DURGESH716** [comment]
Hi @judeharis 
It's possible that the performance breakdown provided by TFLite's benchmarking tool for GAN models may not be entirely accurate. This can occur due to a variety of factors, such as the complexity of the model, the size of the inputs, and the hardware being used. To obtain a more accurate performance measurement, you may want to consider using alternative benchmarking methods or profiling tools, or fine-tuning the model to optimize its performance for TFLite. Additionally, you can also try running the model on different hardware platforms to see if the results vary.

**Comment by DURGESH716** [comment]
In order to obtain a more accurate performance measurement, you can try the following steps:

1) Increase the number of runs in the benchmarking tool to get more consistent results.
2) Fine-tune the models to optimize their performance for TFLite, including pruning, quantization, and other techniques.

3) Try running the models on different hardware platforms, such as a mobile device, to see if the results vary.

4) Consider using alternative benchmarking methods or profiling tools, such as the TensorFlow Model Analysis library or TensorFlow Profiler.

**Comment by judeharis** [comment]
Thanks for the responses. My current plan of action is as @DURGESH716  suggested point (4) . Running other GAN based models with Tensorflow profiler on and I have seen around 40-50% of latency for "Conv2DBackpropInput", this is range makes more sense. Funny thing is the profiler treats the Conv2DTranspose as "Conv2DBackpropInput", I assume internally CONV2D, CONV2DT and "Conv2DBackpropInput" is very similar. 

Just to confirm I am doing things correctly for profiler using Tensorboard profiler tool I am simply using the code as follows:

`tf.profiler.experimental.start('logdir')
for i in range(100):
    generated_image = generator(noise, training=False)
    decision = discriminator(generated_image)
tf.profiler.experimental.stop()`

This code should profile the inference for both the generative and discriminator models of the GAN?

Additionally I will looking to updating to 2.10+ to see if I will get different results.

**Comment by mohantym** [comment]
Ok @judeharis !

Thanks for the update .  
Could we consider this as partially resolved then and track further work the details in [TF-Forum](https://discuss.tensorflow.org/) (dedicated for machine learning support queries).


Thank you!

**Comment by pkgoogle** [comment]
Hi all, I used the TFLite model found here: https://tfhub.dev/captain-pool/lite-model/esrgan-tf2/1

I used the nightly branch to build the benchmark_model executable with the same options posted originally:

```sh
./benchmark_model --use_gpu=false --num_threads=1 --enable_op_profiling=true --graph=lite-model_esrgan-tf2_1.tflite --num_runs=2 --warmup_runs=0 --warmup_min_secs=0 --use_vm_sim_delegate=false --print_postinvoke_state=true --profiling_output_csv_file=test.csv
```

and here are the current results:

```
node type	                        count	avg_ms	avg %	cdf %	mem KB	times called	
CONV_2D	                                167	532.742	94.49%	94.49%	0	167	
Convolution (NHWC F32) IGEMM	        2	10.382	1.84%	96.33%	0	2
Deconvolution (NHWC F32) Subconv2D	2	8.378	1.49%	97.81%	0	2
Copy (NC X32)	                        1	5.963	1.06%	98.87%	0	99
CONCATENATION	                        33	2.74	0.49%	99.36%	0	33	
Leaky ReLU (NC F32)	                4	2.354	0.42%	99.78%	0	136
Add (ND	F32)	                        3	1.188	0.21%	99.99%	0	47
Multiply (ND F32)	                1	0.08	0.01%	100%	0	11
```

csv for more info
[test.csv](https://github.com/tensorflow/tensorflow/files/13171449/test.csv)

**Comment by pkgoogle** [comment]
Hi @judeharis, it seems like the key is to remove the TRANSPOSE_CONV layer entirely ... joking, I think it's represented here as Convolution (NHWC F32) IGEMM and Deconvolution (NHWC F32) Subconv2D, but I think your original question still stands. I don't really see it as erroneous as while the Transposed Convolution looks more complicated than a regular convolution, I would be surprised if it took exponentially more time if optimized correctly (I would expect it to be on the same order of magnitude close to a regular convolution with the same input size). It could be that previous papers used non-optimal or out-dated frameworks that performed those layers inefficiently, do you know what papers you originally were referring to? For now I would assume that the results are accurate, as I don't see why they wouldn't be from the current evidence presented.
