### ISSUE TITLE
`tf.global_variable_initializer` is misspelled as `tf.global_variable_initializers` (extra 's' at end) in release notes

### ISSUE THREAD

**Issue by samjabrahams** [tensorflow/tensorflow#5946]
In the [release notes for 0.12.0rc0](https://github.com/tensorflow/tensorflow/releases/tag/0.12.0-rc0), the note on the renaming of `tf.initialize_all_variables` to `tf.global_variable_initializer` has a typo, calling it `tf.global_variable_initializers` instead. It's a small typo, but I think it's worth fixing since this is such an important breaking change.

**Comment by gunan** [comment]
Hmm, looks like some of our documents are also wrong:
https://github.com/tensorflow/tensorflow/blob/r0.12/tensorflow/python/ops/variables.py#L90
and the actual method seems to be
`tf.global_variables_initializer` Will send out a PR as a fix.
