### ISSUE TITLE
Segmentation Fault during training

### ISSUE THREAD

**Issue by zndr27** [tensorflow/tensorflow#59461]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.12.0-dev20230125

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.10

### CUDA/cuDNN version

12

### GPU model and memory

RTX 3080ti

### Current Behaviour?

```shell
Docker image: tensorflow/tensorflow:nightly-gpu 

The same issue occurs whether I'm using tensorflow 2.11 or 2.12.0-dev.

I'm getting a "segmentation fault (core dumped)" on the third epoch of my training run. There is no trace, so I have no clue how to debug. I tried adjusting the batch size, but I always get the same issue (it just may occur on a different epoch number).

The other odd thing is that the seg fault always happens at the exact same batch number (e.g. batch 7402 / 7472 in epoch 3).

If the seg fault occurs on epoch 3, I can load the saved model from epoch 2 and continue to train for another 2 epochs (so 4 total), but it will seg fault again on the 3rd epoch. 

How should I proceed?
```

### Standalone code to reproduce the issue

```shell
Too much code to include everything here, I'm not sure which part would be the most useful. But I can add code snippets here as needed.
```

### Relevant log output

```shell
Segmentation fault (core dumped)
```
</details>

**Comment by zndr27** [comment]
How should I go about debugging this issue when there's no trace? Is there any way to get tensorflow to return a trace on a seg fault error?

**Comment by SuryanarayanaY** [comment]
Hi @zndr27 ,
Segmentation faults may occur due to Out Of Bound errors,or Illegal Memory access errors.Tensorflow do provide some logs there unless its OS crash due to failure of memory allocation. There are many issues in Tensorflow repo with same behaviour but different context as per reference [link](https://github.com/tensorflow/tensorflow/issues?q=segmentation+fault+is%3Aclosed) where you may find some useful error info regarding this.However, log trace is unlikely to get AFAIK.
As you reported the behaviour occurs after some epochs which might happen due to Memory release/Memory Fragmentation issues.Providing more context with some repro code might be helpful for us.

Thank you!

**Comment by SuryanarayanaY** [comment]
@zndr27 ,

Sorry, my last comment was incorrect.I did some exploration and find out from Internet resources that when segmentation fault occurs it normally follows core dumped where all the logs store in a file as `core.` file though it will not display in terminal.

Initially you have use the below commands to enable these error trace to be stored.
```
ulimit -c unlimited 
ulimit -a
```

For example on Ubuntu-22 VM I have tested a code that causes segmentation fault.After that I executed a code that causes segfault and I find that these log stored under  `/var/lib/apport/coredump` but stored in Machine language which is not readable. You need to debug this file using `gdb` as Iam not expert at this.You may find some information here at [link1](https://stackoverflow.com/questions/3718998/fixing-segmentation-faults-in-c) and [link2](https://freecoder.dev/segmentation-fault-in-c/). 

Also please note that the location of this core file may vary from OS to OS and with Versions also.

In your case providing code snippet may able to help you. Thanks!
