### ISSUE TITLE
 tf.lite is x40 faster than tflite_runtime.interpreter

### ISSUE THREAD

**Issue by JasseurHadded1** [tensorflow/tensorflow#59467]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### Current Behaviour?

```shell
Hi, I have a tflite qunatized model (int8), The model running with


interpreter = tf.lite.Interpreter(model_path=model_path,
                                experimental_delegates=[])
```

is 40x faster than:

```
import tflite_runtime.interpreter as tflite
interpreter = tflite.Interpreter(model_path=model_path,
                                experimental_delegates=[])
```

Any explications? I have to used the tflite_runtime to run the model with USB google coral

Thanks
```


### Standalone code to reproduce the issue

```shell
The first code:

import tensorflow as tf
interpreter = tf.lite.Interpreter(model_path=model_path,
                                 experimental_delegates=delegates)

=> 80 ms as inference time

The second code:
import tflite_runtime.interpreter as tflite
interpreter = tflite.Interpreter(model_path=model_path,
                                 experimental_delegates=delegates)

=> 3s as inference time
```

### Relevant log output

_No response_</details>

**Comment by pjpratik** [comment]
@JasseurHadded1 Thanks for the observation.

As per the [documentation](https://www.tensorflow.org/lite/guide/python#about_the_tensorflow_lite_runtime_package), the Select TF Ops are not available in tflite_runtime by default which may effect the inference time. 

Please find the similar issue [#59273](https://github.com/tensorflow/tensorflow/issues/59273) on the same thread and let us know if it helps. Thanks.
