### ISSUE TITLE
How to invoke .h5 model instead of .tflite model for pose classification?

### ISSUE THREAD

**Issue by aakash-chakraborty1995** [tensorflow/tensorflow#59470]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.7

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
I need to implement pose_classifier.h5 model instead of pose_classifier.tflite.
```

### Relevant log output

_No response_</details>

**Comment by aakash-chakraborty1995** [comment]
Need to rewrite the classifier.py script in raspberry pi implementation of pose classification.

**Comment by mohantym** [comment]
Hi @aakash-chakraborty1995 !

You can run the bash script from ci_build  after shallow cloning upto last 3 commits .
```
1.  git clone --depth 3  git@github.com:tensorflow/tensorflow.git
2.  tensorflow/tools/ci_build/ci_build.sh PI-PYTHON38 tensorflow/tools/ci_build/pi/build_raspberry_pi.sh 
```
Please let us know above answers your query.

Thank you!
