### ISSUE TITLE
How to switch from TextLineDataset to Dataset.from_generator

### ISSUE THREAD

**Issue by jorispelemans** [tensorflow/tensorflow#59471]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

tf 2.9.0

### Custom Code

Yes

### OS Platform and Distribution

Mac OS X

### Python version

3.7.11

### Current Behaviour?

```shell
I have working code that interleaves TextLineDatasets. However, when I try to do the same with tf.data.Dataset.from_generator (because I want to switch to binary files), I get a TypeError (see below).
```

### Standalone code to reproduce the issue

```shell
def generator(fname):
    with open(fname, 'r') as f:
        for line in f.readlines():
            yield line

def dataset_from_generator(fname):
    return tf.data.Dataset.from_generator(
        lambda: generator(fname),
        output_signature=tf.TensorSpec(shape = (1,), dtype = tf.string)
    )

fnames = ["file1.txt", "file2.txt","file1_fr.txt", "file2_fr.txt"]
dataset = tf.data.Dataset.from_tensor_slices(fnames)

print("before interleave")
for element in dataset:
    print(element)

dataset = dataset.interleave(
    #lambda fname: tf.data.TextLineDataset(fname), # this works
    lambda fname: dataset_from_generator(fname), # this doesn't work
    cycle_length=2)

print()
print("after interleave")

for element in dataset:
    print(element)
```

### Relevant log output

```shell
2023-01-27 12:02:58.363036: W tensorflow/core/framework/op_kernel.cc:1733] INVALID_ARGUMENT: TypeError: expected str, bytes or os.PathLike object, not Tensor
Traceback (most recent call last):

  File "/Users/joris_pelemans/miniconda3/envs/owl3.7/lib/python3.7/site-packages/tensorflow/python/ops/script_ops.py", line 270, in __call__
    ret = func(*args)

  File "/Users/joris_pelemans/miniconda3/envs/owl3.7/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "/Users/joris_pelemans/miniconda3/envs/owl3.7/lib/python3.7/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1030, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "dataset.py", line 13, in generator
    with open(fname, 'r') as f:

TypeError: expected str, bytes or os.PathLike object, not Tensor
```
</details>

**Comment by pjpratik** [comment]
@jorispelemans As per the [documentation](https://www.tensorflow.org/api_docs/python/tf/data/Dataset?version=nightly#from_generator), the `generator` should not take any arguments if `args` is not specified. The fname can be passed as `args` for the generator. Please find the working gist [here](https://colab.research.google.com/gist/pjpratik/c546c9a05f68fa1d92c58caccc3f29a1/59471.ipynb) and let us know if it helps. Thank you.

**Comment by jorispelemans** [comment]
Thanks, that worked! 

I did notice that while `fname` is originally a string, depending on where you are it becomes a Tensor or a byte. Looks like, if you want to work with actual strings instead of bytes you have to decode them inside the generator:
```
def generator(fname):
    fname = fname.decode()
    with open(fname, 'r') as f:
        for line in f.readlines():
            yield line
```
Decoding the args in `tf.data.Dataset.from_generator` doesn't work, because here `fname` is a Tensor and seems like you can't actually get its value with `fname.numpy().decode()`:

`AttributeError: 'Tensor' object has no attribute 'numpy'`

Is this the best way of doing this?

**Comment by pjpratik** [comment]
@jorispelemans Thanks for the information!

You can also decode the args in `tf.data.Dataset.from_generator` using [`tf.strings.uincode_decode`](https://www.tensorflow.org/api_docs/python/tf/strings/unicode_decode). 

The `fname` tensor can be  decoded in the generator function or before passing it to the `Dataset.from_generator` . Please refer to the documentation [here](https://www.tensorflow.org/api_docs/python/tf/strings/unicode_decode) on decoding tensors. Thank you.
