### ISSUE TITLE
graph execution error

### ISSUE THREAD

**Issue by Ataullah128** [tensorflow/tensorflow#59484]
I'm facing an issue that says "graph execution error" tried to solve it but couldn't.

**Comment by synandi** [comment]
Hi @Ataullah128,

We see that the issue [template]( https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyze the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced. Thanks!
