### ISSUE TITLE
Issue created for Rollback of PR #59315: [MacOS][Pluggable Device] Fixes for macos pluggable device.

### ISSUE THREAD

**Issue by sampathweb** [tensorflow/tensorflow#59483]
Merged PR #59315 is rolled back in a8bb5484cada34c6d02c1d02d128d33c0226946f.
Several tests failed on Intel MacOS including //tensorflow/core/framework:tensor_test

Please follow up with the PR Owner and close this issue once its resolved.

**Comment by penpornk** [comment]
Updates: I'm working on bringing them back but it will take a while. / Not sure if it can be back in time for the branch cut.

**Comment by penpornk** [comment]
https://github.com/tensorflow/tensorflow/commit/9b179ef8252414720231b1c8c5e526888be84051 brought the PR back partially. 
Two fixes that were brought back: TensorList guard and MustCompileWithXLA hack.
Still debugging the Eigen buffer alignment issue.

**Comment by tilakrayal** [comment]
@sampathweb,
The CL raised for the Rollback of the PR #59315 has been submitted with the commit https://github.com/tensorflow/tensorflow/commit/a8bb5484cada34c6d02c1d02d128d33c0226946f . Could you please check and confirm the same. Thank you!
