### ISSUE TITLE
Cross Compilation Python 3.8 Rasberry Pi 4 AARCH64 fails

### ISSUE THREAD

**Issue by kaoh** [tensorflow/tensorflow#59488]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

v2.8.4

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.8

### Bazel version

4.2.1

### GCC/Compiler version

9.4.0

### Current Behaviour?

```shell
The compilation succeeds.
```

### Standalone code to reproduce the issue

```shell
tensorflow/tools/ci_build/ci_build.sh PI-PYTHON38 tensorflow/tools/ci_build/pi/build_raspberry_pi.sh AARCH64
```

### Relevant log output

```shell
2023-01-29 18:19:00 (1.55 MB/s) - 'get-pip.py' saved [2569500/2569500]

/install/install_pip_packages_by_version.sh: line 24: /usr/local/bin/python3.8: No such file or directory
ln: failed to create symbolic link '/usr/include/python3.8/numpy': No such file or directory
The command '/bin/sh -c /install/install_pi_python3x_toolchain.sh "3.8"' returned a non-zero code: 1
ERROR: docker build failed. Dockerfile is at /home/foobar/projects/tensorflow/tensorflow/tools/ci_build/Dockerfile.pi-python38
```
</details>

**Comment by gaikwadrahul8** [comment]
Hi, @mohantym 

Could you please look into this issue ? Thank you

**Comment by koh-osug** [comment]
I have updated the used Ubuntu Version in the Docker image to 20.04 and added some missing dependencies (python3-virtualenv, libpython3.8-dev,dirmngr, gpg-agent), but I'm still facing:


> In file included from /usr/include/python3.8/Python.h:8,
>                  from ./tensorflow/python/lib/core/numpy.h:35,
>                  from tensorflow/python/lib/core/numpy.cc:20:
> /usr/include/python3.8/pyconfig.h:9:12: fatal error: aarch64-linux-gnu/python3.8/pyconfig.h: No such file or directory
>  #  include <aarch64-linux-gnu/python3.8/pyconfig.h>

**Comment by mohantym** [comment]
Hi @kaoh!
Could you confirm the same behavior  in 2.11 , Bazel 5.3.0 and Python 3.9  too.
Thank you!

**Comment by kaoh** [comment]
I try to test it. I see in the current tree that the build files have changed, right, it is just `build_raspberry_pi.sh` now? The instructions are the same? But anyway, I need the exact version 2.8.4. This is the dependency used in my current Rasa version.

**Comment by mohantym** [comment]
@kaoh !
Thanks for the update.

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by kaoh** [comment]
I got with v2.11 this error:

> ERROR: /home/widerstand/.cache/bazel/_bazel_widerstand/65bc50a2aeca8de8f79bfe9d2f5bf825/external/boringssl/BUILD:182:11: Compiling src/ssl/bio_ssl.cc failed: (Exit 1): aarch64-linux-gnu-gcc failed: error executing command 
>   (cd /home/widerstand/.cache/bazel/_bazel_widerstand/65bc50a2aeca8de8f79bfe9d2f5bf825/execroot/org_tensorflow && \
>   exec env - \
>     PATH=/home/widerstand/.local/bin:/home/widerstand/.pyenv/shims:/home/widerstand/.nvm/versions/node/v15.0.1/bin:/home/widerstand/gems/bin:/home/widerstand/Programme/dex2jar-2.0/:/home/widerstand/Android/Sdk/build-tools/30.0.3/:/home/widerstand/Android/Sdk/platform-tools/:/home/widerstand/.nix-profile/bin:/home/widerstand/bin:/usr/local/cuda-11/bin:/usr/local/cuda-10.2/NsightCompute-2019.1:/home/widerstand/.local/bin:/home/widerstand/bin:/home/widerstand/.pyenv/bin:/opt/maven/bin:/opt/ant/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/widerstand/.dotnet/tools:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/widerstand/bin:/usr/local/cuda-11/bin:/usr/local/cuda-10.2/NsightCompute-2019.1:/home/widerstand/.local/bin:/home/widerstand/bin:/home/widerstand/.pyenv/bin:/opt/maven/bin:/opt/ant/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/widerstand/.dotnet/tools:/usr/local/go/bin:/home/widerstand/projects/git-cinnabar:/home/widerstand/projects/git-cinnabar \
>     PWD=/proc/self/cwd \
>     PYTHON_BIN_PATH=/home/widerstand/.pyenv/versions/3.8.16/bin/python3 \
>     PYTHON_LIB_PATH=/home/widerstand/.pyenv/versions/3.8.16/lib/python3.8/site-packages \
>     TF2_BEHAVIOR=1 \
>   /home/widerstand/.cache/bazel/_bazel_widerstand/65bc50a2aeca8de8f79bfe9d2f5bf825/external/aarch64_linux_toolchain/bin/aarch64-linux-gnu-gcc -fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -isystem /home/widerstand/.cache/bazel/_bazel_widerstand/65bc50a2aeca8de8f79bfe9d2f5bf825/external/aarch64_linux_toolchain/lib/gcc/aarch64-linux-gnu/8.3.0/include -isystem /home/widerstand/.cache/bazel/_bazel_widerstand/65bc50a2aeca8de8f79bfe9d2f5bf825/external/aarch64_linux_toolchain/lib/gcc/aarch64-linux-gnu/8.3.0/include-fixed -isystem /home/widerstand/.cache/bazel/_bazel_widerstand/65bc50a2aeca8de8f79bfe9d2f5bf825/external/aarch64_linux_toolchain/aarch64-linux-gnu/include/c++/8.3.0/ -isystem /home/widerstand/.cache/bazel/_bazel_widerstand/65bc50a2aeca8de8f79bfe9d2f5bf825/external/aarch64_linux_toolchain/aarch64-linux-gnu/libc/usr/include/ -isystem /usr/include/python3.5 -isystem /usr/include/ -MD -MF bazel-out/aarch64-opt/bin/external/boringssl/_objs/ssl/bio_ssl.pic.d '-frandom-seed=bazel-out/aarch64-opt/bin/external/boringssl/_objs/ssl/bio_ssl.pic.o' -fPIC -iquote external/boringssl -iquote bazel-out/aarch64-opt/bin/external/boringssl -isystem external/boringssl/src/include -isystem bazel-out/aarch64-opt/bin/external/boringssl/src/include -Wno-all -Wno-extra -Wno-deprecated -Wno-deprecated-declarations -Wno-ignored-attributes -Wno-unknown-warning -Wno-array-parameter -Wno-stringop-overflow -Wno-array-bounds -Wunused-result '-Werror=unused-result' -DAUTOLOAD_DYNAMIC_KERNELS '-std=gnu11' -O3 -funsafe-math-optimizations -ftree-vectorize -fomit-frame-pointer '-std=c++17' -Wa,--noexecstack '-D_XOPEN_SOURCE=700' -Wall -Werror '-Wformat=2' -Wsign-compare -Wmissing-field-initializers -Wwrite-strings -Wshadow -fno-common '-std=c++11' -Wmissing-declarations -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -no-canonical-prefixes -fno-canonical-system-headers -c external/boringssl/src/ssl/bio_ssl.cc -o bazel-out/aarch64-opt/bin/external/boringssl/_objs/ssl/bio_ssl.pic.o)
> # Configuration: 937f5c039a0e9cf9e459e05164699e07aa69a5cdb342e38cb96576f4c5a233f9
> # Execution platform: @local_execution_config_platform//:platform
> cc1plus: error: command line option '-std=gnu11' is valid for C/ObjC but not for C++ [-Werror]
> cc1plus: error: unrecognized command line option '-Wno-array-parameter' [-Werror]
> cc1plus: error: unrecognized command line option '-Wno-unknown-warning' [-Werror]
> cc1plus: all warnings being treated as errors
> INFO: Elapsed time: 1841.748s, Critical Path: 269.06s
> INFO: 2027 processes: 399 internal, 1628 local.
> FAILED: Build did NOT complete successfully

**Comment by terryheo** [comment]
I'm not sure if `build_raspberry_pi.sh` is well maintained. You might need to fix the script by yourself.

But TFLite build is well maintained. https://www.tensorflow.org/lite/guide/build_cmake_pip#arm_cross_compilation
You can develop your ML model in x86_64 workstation and deploy it to RPI via TFLite inference engine.
