### ISSUE TITLE
Issue when loading trained model

### ISSUE THREAD

**Issue by danielstankw** [tensorflow/tensorflow#59485]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

tf 2.10

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04 LTS

### Python version

3.9

### Current Behaviour?

I have trained a model using keras, and was able to save it and load it uisng jupyter notebook. But when I try to load it using pycharm it doesnt work for me. 
I am using different virtual envs for jupyter notebook and pycharm, but I have all packages installed so I am unsure why am I getting the problem.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
model = tf.keras.models.load_model('/home/danieln7/Desktop/ML/robot_1_full2')
print(model.summary())
```

### Relevant log output

```shell
File "/home/danieln7/Desktop/RobotCodeDaniel/test.py", line 7, in <module>
    model = tf.keras.models.load_model('/home/danieln7/Desktop/ML/robot_1_full2', compile=True)
  File "/home/danieln7/anaconda3/envs/RobotControl/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/danieln7/anaconda3/envs/RobotControl/lib/python3.9/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 115, in _process_kwargs
    raise TypeError(
TypeError: weight_decay is not a valid argument, kwargs should be empty  for `optimizer_experimental.Optimizer`.
```
</details>

**Comment by tiruk007** [comment]
@danielstankw 
Can you please provide complete code or Colab gist to replicate the issue reported here ?

Thank you!
