### ISSUE TITLE
Move SummaryWriter from `train` to `summary` submodule

### ISSUE THREAD

**Issue by samjabrahams** [tensorflow/tensorflow#5948]
Haven't seen this mentioned yet, so I figured it was worth asking. Since we're moving all of the summary operations to a separate `summary` module, would it make sense to migrate `SummaryWriter` over there as well?

**Comment by danmane** [comment]
This is already done on master; the new location is tf.summary.FileWriter. see https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/summary/summary.py#L61

I haven't removed tf.train.SummaryWriter, but I will before tf 1.0
