### ISSUE TITLE
tf.data: random operation inside map function leads to unexpected results on multi-CPU machines

### ISSUE THREAD

**Issue by nskocabey** [tensorflow/tensorflow#59496]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 16.04

### Python version

3.9

### Current Behaviour?

The following minimal example produces a simple 2x1 image, creates an infinite tf dataset by repeating it and applies a random vertical flip operation. After that it takes 100 elements from the dataset and prints how many of them are flipped:

On my local machine (MacOS with Tensorflow 2.9.2) this code prints the following numbers:

```
44
54
56
52
48
```

However when I run this on my VM on Google Cloud (w/ 8 CPUs and Tensorflow 2.11.0) it always prints either:

```
100
100
100
100
100
```
or

```
0
0
0
0
0
```

What is going on here? What is the correct way to augment images when using tf.data APIs (especially on multi CPU machines)?
```


### Standalone code to reproduce the issue

```shell
import tensorflow as tf

x = tf.constant([0, 1])
x = tf.reshape(x, [1, 2, 1, 1])

augmenter = tf.keras.layers.RandomFlip('vertical')
dataset = tf.data.Dataset.from_tensor_slices(x)
dataset = dataset.repeat()
dataset = dataset.map(augmenter)

def print_dataset(d, n=100):
  ctr = 0
  res = 0
  for x in iter(d):
    if x[0, 0, 0].numpy() > x[1, 0, 0].numpy():
      res += 1
    ctr += 1
    if ctr >= n:
      print(res)
      break

print_dataset(dataset)
print_dataset(dataset)
print_dataset(dataset)
print_dataset(dataset)
print_dataset(dataset)
```

### Relevant log output

_No response_</details>

**Comment by DURGESH716** [comment]
Hello @nskocabey 
The issue with the code is that the `RandomFlip` augmenter is not being applied to each element in the dataset properly. `RandomFlip` is a `Layer` in TensorFlow and it needs to be instantiated before it can be applied to the dataset.

**Comment by DURGESH716** [comment]
With this correction, the `RandomFlip` augmenter will be applied to each element in the dataset properly: 

```
import tensorflow as tf

x = tf.constant([0, 1])
x = tf.reshape(x, [1, 2, 1, 1])

augmenter = tf.keras.layers.RandomFlip('vertical')

def augment(x):
  return augmenter(x)

dataset = tf.data.Dataset.from_tensor_slices(x)
dataset = dataset.repeat()
dataset = dataset.map(augment)

def print_dataset(d, n=100):
  ctr = 0
  res = 0
  for x in iter(d):
    if x[0, 0, 0].numpy() > x[1, 0, 0].numpy():
      res += 1
    ctr += 1
    if ctr >= n:
      print(res)
      break

print_dataset(dataset)
print_dataset(dataset)
print_dataset(dataset)
print_dataset(dataset)
print_dataset(dataset)

```

**Comment by DURGESH716** [comment]
Let me know if it helps ?

**Comment by synandi** [comment]
Hi @nskocabey, I was able to replicate the issue in [TF v2.10](https://colab.sandbox.google.com/gist/synandi/bfbdee12b239deb51b6d79a5a3471ea3/untitled269.ipynb) and [TF v2.11](https://colab.sandbox.google.com/gist/synandi/b53afc850ce60891ffb495c954795861/untitled270.ipynb) in Colab. This issue has been resolved in the recent tf-nightly - 2.12.0.dev20230130. Please check the gist [here](https://colab.sandbox.google.com/gist/synandi/568753ce33b8391b73b692b5d7c407ac/untitled271.ipynb). Could you please try with the tf-nightly version and confirm if the issue persists. Thank you!

**Comment by nskocabey** [comment]
@DURGESH716 Your proposal does **NOT** solve the problem on my machine.

I installed tf-nightly==2.12.0.dev20230201 and can confirm that the issue is resolved there.

**Comment by nskocabey** [comment]
How can we make sure that this bug doesn't reappear in future releases? This setup is one of the augmentation setups mentioned in the [data augmentation tutorial](https://www.tensorflow.org/tutorials/images/data_augmentation) and it is probably used by many developers.

**Comment by synandi** [comment]
> How can we make sure that this bug doesn't reappear in future releases? This setup is one of the augmentation setups mentioned in the [data augmentation tutorial](https://www.tensorflow.org/tutorials/images/data_augmentation) and it is probably used by many developers.

@nskocabey,
The developer team worked on this bug and fixed it in the most recent version of Tensorflow. That means if the bug has been fixed in the latest tf-nightly version, it is likely that the code will work as expected in the next stable release of TensorFlow, which is v2.12. Thank you!
