### ISSUE TITLE
TFLite missing files on TFLITE_PROFILER_SRCS causes undefined reference error.

### ISSUE THREAD

**Issue by turgut-baba** [tensorflow/tensorflow#59500]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.12.0

### Custom Code

Yes

### OS Platform and Distribution

Debian GNU/Linux 11 (bullseye)

### Mobile device

Debian GNU/Linux 11 (bullseye)

### Python version

3.9.2

### Bazel version

3.7.2

### GPU model and memory

Nvidia

### Current Behaviour?

```shell
Following the official documentation about compiling with cmake on https://www.tensorflow.org/lite/guide/build_cmake, after successfully compiling (Without the `-j` flag on the `cmake --build . -j` step), when trying to use tflite with the cmake example provided I'm getting an `Undefined reference error` on multiple instances. The error is not present on all functions/classes, for example `FlatBufferModel::BuildFromFile` builds and runs just file, however when trying to create an interpreter object the make file gives out an ` undefined reference to `tflite::telemetry::TelemetryReportEvent(TfLiteContext*, char const*, TfLiteStatus)'` error. Many of these error are linked to the usage of `Telementry` functions. So following the answer on a question I asked https://stackoverflow.com/questions/75245826/c-tensorflow-lite-undefined-reference-on-some-functions/75291357#75291357 the problem is fixed. So the telementry files should be added to the CMakeLists.txt file. (More information and the exact steps I've followed to build the library can be found in the stackoverflow question link provided.)
```

### Standalone code to reproduce the issue

```shell
cmake_minimum_required(VERSION 3.16)
project(minimal C CXX)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DTFLITE_DISABLE_TELEMETRY=1")

set(TENSORFLOW_SOURCE_DIR "" CACHE PATH
  "Directory that contains the TensorFlow project" )
if(NOT TENSORFLOW_SOURCE_DIR)
  get_filename_component(TENSORFLOW_SOURCE_DIR
    "/home/user/Desktop/tensorflow_src" ABSOLUTE)
endif()

add_subdirectory(
  "${TENSORFLOW_SOURCE_DIR}/tensorflow/lite"
  "${CMAKE_CURRENT_BINARY_DIR}/tensorflow-lite" EXCLUDE_FROM_ALL)

add_executable(minimal main.cpp)
target_link_libraries(minimal tensorflow-lite)
```

### Relevant log output

```shell
[100%] Linking CXX executable minimal
/usr/bin/ld: tensorflow-lite/libtensorflow-lite.a(interpreter.cc.o): in function `tflite::impl::Interpreter::ReportTelemetrySettings(char const*)':
interpreter.cc:(.text+0x292f): undefined reference to `tflite::telemetry::TelemetryReportSettings(TfLiteContext*, char const*, TfLiteTelemetryInterpreterSettings const*)'
/usr/bin/ld: tensorflow-lite/libtensorflow-lite.a(subgraph.cc.o): in function `tflite::Subgraph::Invoke()':
subgraph.cc:(.text+0x41c0): undefined reference to `tflite::telemetry::TelemetryReportEvent(TfLiteContext*, char const*, TfLiteStatus)'
/usr/bin/ld: tensorflow-lite/libtensorflow-lite.a(subgraph.cc.o): in function `tflite::Subgraph::ModifyGraphWithDelegate(TfLiteDelegate*)':
subgraph.cc:(.text+0x6ad0): undefined reference to `tflite::telemetry::TelemetryReportEvent(TfLiteContext*, char const*, TfLiteStatus)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/minimal.dir/build.make:184: minimal] Error 1
make[1]: *** [CMakeFiles/Makefile2:1408: CMakeFiles/minimal.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```
</details>

**Comment by DURGESH716** [comment]
Hi @turgut-baba,
This error occurs when the TFLite Profiler source files are missing from your project, causing a reference to undefined symbols. To resolve this error, ensure that you have included all necessary TFLite Profiler source files in your project and that they are properly linked in your build system. You can find the required source files in the TensorFlow Lite repository.

**Comment by DURGESH716** [comment]
The issue with the `tflite::telemetry::TelemetryReportEvent` function is resolved by including the TensorFlow Lite telemetry source files in your build. This can be done by updating the `CMakeLists.txt` file in your project to include the relevant telemetry source files.

**Comment by DURGESH716** [comment]
Let me know if helps you ?

**Comment by turgut-baba** [comment]
I did solved the problem before opening this issue, however shouldn't the `CMakeLİsts.txt` be updated by default in the repository? I haven't tried this on another computer but I think this can happen on other systems aswell, telementries should be put on there by default IMO.

**Comment by DURGESH716** [comment]
The` CMakeLists.txt` file in TensorFlow Lite is not updated by default. TensorFlow Lite is an open-source project and relies on contributions and pull requests from the community to keep the repository up-to-date and address any issues

**Comment by turgut-baba** [comment]
Update: trying to run a project which I've compiled using the above solution causes me to get an error on runtime: `2023-02-01 16:11:31.556438: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-01 16:11:31.556801: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-02-01 16:11:31.556829: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2023-02-01 16:11:33.720144: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2023-02-01 16:11:33.720202: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: debian
2023-02-01 16:11:33.720222: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: debian
2023-02-01 16:11:33.720339: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 470.161.3
2023-02-01 16:11:33.720387: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 470.161.3
2023-02-01 16:11:33.720407: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 470.161.3
usage: tflite_convert [-h] --output_file OUTPUT_FILE [--saved_model_dir SAVED_MODEL_DIR | --keras_model_file KERAS_MODEL_FILE] [--saved_model_tag_set SAVED_MODEL_TAG_SET]
                      [--saved_model_signature_key SAVED_MODEL_SIGNATURE_KEY] [--enable_v1_converter] [--experimental_new_converter [EXPERIMENTAL_NEW_CONVERTER]]
                      [--experimental_new_quantizer [EXPERIMENTAL_NEW_QUANTIZER]]
tflite_convert: error: the following arguments are required: --output_file`

**Comment by mohantym** [comment]
Hi @turgut-baba !
This issues is not replicating in Colab with [2.12 branch](https://colab.sandbox.google.com/gist/mohantym/6206a888278b477a2866ce2a492494f6/git_59500.ipynb#scrollTo=1PfXe_u6wuxY) (Ubuntu 18)  and  will update after testing in Debian linux 11. 
You mentioned Bazel 3.7.2 for your tests. Could you test with Bazel 5.3.0 and let us know

@DURGESH716 !
Thanks for sharing your [observation](https://github.com/tensorflow/tensorflow/issues/59500#issuecomment-1411882425). 
Do you suggest any PR.

Thank you!

**Comment by turgut-baba** [comment]
It appears the never versions have fixed this issue. Thanks everyone who worked on fixing this.
