### ISSUE TITLE
get error when directly running retrain.py (without build) 

### ISSUE THREAD

**Issue by civilman628** [tensorflow/tensorflow#5950]
I get error when directly running retrain.py, without build it first. I run it without build before, but the latest code does not work.

  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "retrain.py", line 798, in main
    bottleneck_tensor)
  File "retrain.py", line 706, in add_final_training_ops
    variable_summaries(layer_weights)
  File "retrain.py", line 668, in variable_summaries
    tf.summary.histogram('histogram', var)
**AttributeError: 'module' object has no attribute 'histogram'**

**Comment by civilman628** [comment]
python tensorflow/examples/image_retraining/retrain.py (add other parameters)

**Comment by poxvoculi** [comment]
Perhaps it would be a good idea to build it first.  Are you following the instructions here?

https://www.tensorflow.org/versions/r0.12/how_tos/image_retraining/index.html

**Comment by civilman628** [comment]
I want to debug **retrain.py** with my data. once it is build, I can't debug.

**Comment by civilman628** [comment]
i reverse the code to a previous state and i can run this .py file directly without build.
**git rev-parse HEAD
eea96fc81bb1ae22eeb1d2141e47e182cecb7608**

So think this should be a bug.

**Comment by poxvoculi** [comment]
You have not posted the information requested in the new issues template, i.e. the OS, release etc.  What is VS?  Are you trying to run with VisualStudio?  I don't know whether TF is guaranteed to run without going through the build process.

**Comment by civilman628** [comment]
just use the latest code, on Ubuntu 16.04. VS code is not visual studio 2013/2015 for windows, but a Linux version. it can debug python. I think any IDE should be fine.

**Comment by civilman628** [comment]
I want to know how to debug the code. now it can't do this since it needs build to run.

**Comment by poxvoculi** [comment]
I'm labeling community-support for the use of VisualStudio on Ubuntu.  It's not clear to me why you can't debug the python parts of TF after building.

**Comment by civilman628** [comment]
**retrain.py**  is not the entry point of the program. it's more like a "library" which is called by another file.

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.
