### ISSUE TITLE
RuntimeError: tensorflow/lite/kernels/elementwise.cc:88 Type INT16 is unsupported by op Rsqrt.Node number 34 (RSQRT) failed to prepare.Failed to apply the default TensorFlow Lite delegate indexed at 0.

### ISSUE THREAD

**Issue by nyadla-sys** [tensorflow/tensorflow#59506]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installation (pip package or built from source):
- TensorFlow library (version, if pip package or github SHA, if built from source):

### 2. Code

```
!pip install git+https://github.com/openai/whisper.git 
!pip install onnx
!pip install onnx_tf
!git clone https://github.com/usefulsensors/openai-whisper.git
!git clone https://github.com/openai/whisper.git 
%%capture
!pip install optimum[onnxruntime] transformers git+https://github.com/openai/whisper.git
# -*- coding: utf-8 -*-
import warnings
warnings.filterwarnings("ignore")

from optimum.onnxruntime import ORTModelForSpeechSeq2Seq
from transformers import (
    set_seed,
    AutoProcessor
)
from pathlib import Path
import os

SEED = 42

# Export vanilla & optimized onnx model
def export_vanilla_optimized_onnx(model_checkpoint):
    set_seed(SEED)
    processor = AutoProcessor.from_pretrained(model_checkpoint)

    # Vanilla
    model = ORTModelForSpeechSeq2Seq.from_pretrained(model_checkpoint, from_transformers=True, use_cache=True)
    onnx_path = Path(os.path.join("exported_onnx_models/", model_checkpoint))
    model.save_pretrained(onnx_path)
    processor.save_pretrained(onnx_path)


export_vanilla_optimized_onnx('openai/whisper-tiny')
import whisper
import torch
import tensorflow as tf
import onnx
import numpy as np
import argparse
import os
import warnings
import tqdm
from onnx_tf.backend import prepare
from whisper.audio import load_audio, log_mel_spectrogram,pad_or_trim,N_FRAMES, SAMPLE_RATE
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

#load openai->whisper(pytorch)->tiny model
tiny_model = whisper.load_model("tiny")

#Export to onnx format
torch.onnx.export(tiny_model.encoder, torch.randn(1,80,3000).to(device), "./whisper-encoder.onnx")
onnx_model_path = './whisper-encoder.onnx'
tf_model_path = 'model_tf-encoder'

onnx_model = onnx.load(onnx_model_path)
tf_rep = prepare(onnx_model)
tf_rep.export_graph(tf_model_path)
from datasets import load_dataset
ds = load_dataset("hf-internal-testing/librispeech_asr_dummy", "clean", split="validation")
from transformers import WhisperProcessor, TFWhisperForConditionalGeneration

processor = WhisperProcessor.from_pretrained("openai/whisper-tiny")
saved_model_dir = 'model_tf-encoder'
tflite_model_path = 'whisper-encoder-hybrid.tflite'

def representative_dataset_data():
    for x in range(5):
      inputs = processor(ds[x]["audio"]["array"], return_tensors="tf")
      input_features = inputs.input_features
      yield [input_features]

def representative_dataset_random():
    for _ in range(100):
      data = np.random.rand(1, 80, 3000)
      yield [data.astype(np.float32)]

def representative_dataset():
    for _ in range(1):#Change this to 100 and provide 100 different audio files from known dataset 
      mel_from_file = log_mel_spectrogram('/content/whisper/tests/jfk.flac')
      segment = pad_or_trim(mel_from_file, N_FRAMES)
      segment = tf.expand_dims(segment, 0)
      print(segment.shape)
      yield [segment]

# Convert to tflite(int8) model
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.target_spec.supported_ops = [tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8,
                                       tf.lite.OpsSet.SELECT_TF_OPS]
converter.representative_dataset = representative_dataset_data
#converter.inference_input_type = tf.int8  # or tf.uint8
#converter.inference_output_type = tf.int8  # or tf.uint8
converter.inference_input_type = tf.float32
converter.inference_output_type = tf.float32
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()



# Save the model
with open(tflite_model_path, 'wb') as f:
    f.write(tflite_model)

import tensorflow as tf
import numpy as np
tflite_model_path = '/content/whisper-encoder-hybrid.tflite'

# Load the TFLite model and allocate tensors
interpreter_enc = tf.lite.Interpreter(model_path=tflite_model_path)
interpreter_enc.allocate_tensors()

print("== Input details ==")
print("name:", interpreter_enc.get_input_details()[0]['name'])
print("shape:", interpreter_enc.get_input_details()[0]['shape'])
print("type:", interpreter_enc.get_input_details()[0]['dtype'])

print("\nDUMP INPUT")
print(interpreter_enc.get_input_details()[0])

print("\n== Output details ==")
print("name:", interpreter_enc.get_output_details()[0]['name'])
print("shape:", interpreter_enc.get_output_details()[0]['shape'])
print("type:", interpreter_enc.get_output_details()[0]['dtype'])

print("\nDUMP OUTPUT")
print(interpreter_enc.get_output_details()[0])

# Get input and output tensors
input_details = interpreter_enc.get_input_details()
output_details = interpreter_enc.get_output_details()
output_tensor = interpreter_enc.get_output_details()[0]['index']

# Test the model with random data
input_shape = input_details[0]['shape']
mel_from_file = log_mel_spectrogram('/content/whisper/tests/jfk.flac')
input_tensor = pad_or_trim(mel_from_file, N_FRAMES)
input_tensor = tf.expand_dims(input_tensor, 0)

audio = whisper.load_audio('/content/whisper/tests/jfk.flac')
audio = whisper.pad_or_trim(audio)
mel = whisper.log_mel_spectrogram(audio)
mel = np.expand_dims(mel,0)
#input_tensor = np.array(input_tensor-128, dtype=np.int8)
interpreter_enc.set_tensor(input_details[0]['index'], mel)

interpreter_enc.invoke()
print("Whisper Encoder Inference executed successfully\n")
encoder_output_data = interpreter_enc.get_tensor(output_tensor)
print(encoder_output_data.shape)
print(encoder_output_data)
np.savetxt("encoder_output.txt", encoder_output_data.reshape((3,-1)), fmt="%s", header=str(encoder_output_data.shape))

```

#### Option A: Reference colab notebooks

1)  Reference [TensorFlow Model Colab](https://colab.research.google.com/gist/ymodak/e96a4270b953201d5362c61c1e8b78aa/tensorflow-datasets.ipynb?authuser=1): Demonstrate how to build your TF model.
2)  Reference [TensorFlow Lite Model Colab](https://colab.research.google.com/gist/ymodak/0dfeb28255e189c5c48d9093f296e9a8/tensorflow-lite-debugger-colab.ipynb): Demonstrate how to convert your TF model to a TF Lite model (with quantization, if used) and run TFLite Inference (if possible).

```
(You can paste links or attach files by dragging & dropping them below)
- Provide links to your updated versions of the above two colab notebooks.
- Provide links to your TensorFlow model and (optionally) TensorFlow Lite Model.
```

#### Option B: Paste your code here or provide a link to a custom end-to-end colab

```
(You can paste links or attach files by dragging & dropping them below)
- Include code to invoke the TFLite Converter Python API and the errors.
- Provide links to your TensorFlow model and (optionally) TensorFlow Lite Model.
```

### 3. Failure after conversion
Conversion is successful ,however while running the model getting below error
RuntimeError                              Traceback (most recent call last) <ipython-input-32-17a970b6c12f> in <module>       5 # Load the TFLite model and allocate tensors       6 interpreter_enc = tf.lite.Interpreter(model_path=tflite_model_path) ----> 7 interpreter_enc.allocate_tensors()       8        9 print("== Input details ==")  /usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/interpreter.py in allocate_tensors(self)     511   def allocate_tensors(self):     512     self._ensure_safe() --> 513     return self._interpreter.AllocateTensors()     514      515   def _safe_to_run(self):  RuntimeError: tensorflow/lite/kernels/elementwise.cc:88 Type INT16 is unsupported by op Rsqrt.Node number 34 (RSQRT) failed to prepare.Failed to apply the default TensorFlow Lite delegate indexed at 0.

- Model produces wrong results and/or has lesser accuracy.
- Model produces correct results, but it is slower than expected.

### 4. (optional) RNN conversion support
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by DURGESH716** [comment]
Hello @nyadla-sys 
This error message is indicating that the TensorFlow Lite delegate (a library used to optimize TensorFlow models for deployment on mobile and embedded devices) is unable to execute the "Rsqrt" operation on an input tensor with data type INT16. TensorFlow Lite only supports a limited set of data types, and INT16 is not one of the supported types for this operation. To resolve the issue, you can try converting the INT16 tensor to a supported data type (such as float32) before passing it to the TensorFlow Lite delegate.

**Comment by DURGESH716** [comment]
TensorFlow Lite supports the following data types:

float32
float16
int32
uint8
int64
string

Note that the support for specific data types may vary based on the target platform and the operations being performed. It is always a good idea to consult the TensorFlow Lite documentation for the most up-to-date information on supported data types.

**Comment by DURGESH716** [comment]
Let me know if it helps ?

**Comment by nyadla-sys** [comment]
@DURGESH716 The colab notebook I posted in the link clearly demonstrates the conversion of an ONNX model to a TFLite model with int16 activations and int8 weights. I am puzzled as to why the TFLite Converter would convert it to int16 if it is not supported by the TFLite framework. The original operation was SQRT, but the TFLite Converter changed it to RSQRT. I am not certain why the converter made this change, particularly if it does not support the operation.

**Comment by DURGESH716** [comment]
The TFLite Converter changes operations like SQRT to RSQRT for optimization purposes. RSQRT is more computationally efficient than SQRT and can be performed using int16 data types. However, TFLite framework does not support int16 data types for all operations and SQRT is one of those operations. The TFLite Converter's priority is to generate a smaller and faster TFLite model, even if it means using unsupported operations or data types. The final decision on whether to use int16 data types and unsupported operations will depend on the use case and the trade-off between model size and accuracy.

**Comment by nyadla-sys** [comment]
I attempted to convert to a full int8 encoder model, but it produced inaccurate results. That's why I want to try using int16 activations and int8 weights instead

**Comment by synandi** [comment]
@mohantym 
I was able to replicate the issue in Colab in TF v 2.11. Please find the gist [here](https://colab.sandbox.google.com/gist/synandi/7b1492098e695dd2bfd666c5143f2a67/59506.ipynb#scrollTo=B8FsZuGLzxOg). Thank you!

**Comment by mohantym** [comment]
Hi @nyadla-sys !
Could you also test the keras-stable-diffusion to TFlite work around as mentioned in this [thread.](https://github.com/tensorflow/tensorflow/issues/59259#issuecomment-1399214673)

Thank you!

**Comment by nyadla-sys** [comment]
@mohantym I used PTQ(post training quantization )with representative data set and generated int8 model,however it is producing wrong results,Soon I will share colab notebook here

**Comment by mohantym** [comment]
Ok @nyadla-sys !
Thanks for the update.

@sachinprasadhs !
Could you look at this issue . Attached gist in [2.10](https://colab.sandbox.google.com/gist/mohantym/bdd68e280882b7d85df45b368a6fbe01/59506.ipynb), [2.11](https://colab.sandbox.google.com/gist/mohantym/3fcac6c606b0c9846dad9dc8e8c19ac2/59506.ipynb) and [nightly](https://colab.sandbox.google.com/gist/mohantym/961ebca7df27170ff0dd5ad2a326bac1/59506.ipynb) for reference.

Thank you!

**Comment by Burton2000** [comment]
Getting the same as @nyadla-sys when trying to convert the same model.

From [here](https://www.tensorflow.org/mlir/tfl_ops#tflrsqrt_mlirtflrsqrtop) it seems that int16 should be supported for inference on RSQRT though.

**Comment by nyadla-sys** [comment]
Adding the following patch allows to run inference on int16 rsqrt op 
```
diff --git a/tensorflow/lite/kernels/elementwise.cc b/tensorflow/lite/kernels/elementwise.cc
index a249c3f192d..0c7a1b8db0a 100644
--- a/tensorflow/lite/kernels/elementwise.cc
+++ b/tensorflow/lite/kernels/elementwise.cc
@@ -60,7 +60,7 @@ bool IsAbsSupportedType(const TfLiteType type) {
 }
 
 bool IsRsqrtSupportedType(const TfLiteType type) {
-  return type == kTfLiteFloat32 || type == kTfLiteInt8;
+  return type == kTfLiteFloat32 || type == kTfLiteInt8 || type == kTfLiteInt16;
 }
 
 inline void SetAbsOutputMultiplier(const float input_scale,
@@ -294,6 +294,37 @@ TfLiteStatus RsqrtEvalQuantized(TfLiteContext* context, TfLiteNode* node,
   return EvalImpl<int8_t>(context, node, func, validate_input_func, type);
 }
 
+template <typename T>
+TfLiteStatus RsqrtEvalQuantized(TfLiteContext* context, TfLiteNode* node,
+                                TfLiteType data_type) {
+  const TfLiteTensor* input = GetInput(context, node, 0);
+  TfLiteTensor* output = GetOutput(context, node, 0);
+  const T* input_data = input->data.i16;
+  T* output_data = output->data.i16;
+  const int input_size = NumElements(input);
+  const float input_scale = input->params.scale;
+  const int input_zero_point = input->params.zero_point;
+
+  if (input_scale == 0.f) {
+    TF_LITE_KERNEL_LOG(context, "Input scale is zero.");
+    return kTfLiteError;
+  }
+
+  const float output_scale = 1.f / input_scale;
+  const int output_zero_point = 0;
+
+  for (int i = 0; i < input_size; ++i) {
+    float input_val = (static_cast<float>(input_data[i]) - input_zero_point) *
+                      input_scale;
+    // Avoid division by zero and negative input values.
+    input_val = std::max(input_val, std::numeric_limits<float>::epsilon());
+    output_data[i] = static_cast<T>(
+        std::round(std::sqrt(1.f / input_val) / output_scale + output_zero_point));
+  }
+
+  return kTfLiteOk;
+}
+
 TfLiteStatus RsqrtEval(TfLiteContext* context, TfLiteNode* node) {
   const TfLiteType type = GetInput(context, node, 0)->type;
   switch (type) {
@@ -302,6 +333,8 @@ TfLiteStatus RsqrtEval(TfLiteContext* context, TfLiteNode* node) {
           context, node, [](float f) { return 1.f / std::sqrt(f); }, type);
     case kTfLiteInt8:
       return RsqrtEvalQuantized(context, node, type);
+    case kTfLiteInt16:
+      return RsqrtEvalQuantized<int16_t>(context, node, type);
     default:
       TF_LITE_KERNEL_LOG(context, "Current data type %s is not supported.",
                          TfLiteTypeGetName(type));
@@ -309,6 +342,7 @@ TfLiteStatus RsqrtEval(TfLiteContext* context, TfLiteNode* node) {
   }
 }
 
+
 TfLiteStatus SquareEval(TfLiteContext* context, TfLiteNode* node) {
   return EvalNumeric(context, node, [](float f) { return f * f; });
 }
```

**Comment by Burton2000** [comment]
@nyadla-sys nice I will try this out! When I was converting the decoder to int16x8 I get the following error:
 `Quantization to 16x8-bit not yet supported for op: 'FLOOR_MOD'.`
 
 Did you encounter this as well and manage to overcome it?

**Comment by nyadla-sys** [comment]
At present, my primary focus is on creating a complete int8 model for the encoder, and I haven't attempted to convert the decoder yet. However, I will make an effort to do so when I have the opportunity and inform you of the results.

**Comment by Burton2000** [comment]
Thanks appreciate it, I will do the same if I make any progress. I have been trying to do basically the same as you are doing to get fully int8 model and I have found your posts across different github repos and they have been very useful in making progress!

**Comment by sachinprasadhs** [comment]
Could you please refer the comment [here](https://github.com/tensorflow/tensorflow/issues/56505#issuecomment-1162245079) for the similar issue where INT16 for Rsqrt is not yet supported.

**Comment by nyadla-sys** [comment]
I have yet to find support for rsqrt int16 on TFLM (TensorFlow Lite micro).
Refer the below link for more details
https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/kernels/elementwise.cc#L61

bool IsRsqrtSupportedType(const TfLiteType type) {
  return type == kTfLiteFloat32 || type == kTfLiteInt8;
}

**Comment by nyadla-sys** [comment]
@Burton2000 
I have generated int8 encoder and decoder TFLite models by converting a PyTorch model to ONNX, then from ONNX to TensorFlow, and finally from TensorFlow to TFLite. Unfortunately, the models are producing incorrect results. However, I am pleased to report that end-to-end inference runs on these models. Please refer to the attached notebook for more details.
https://colab.research.google.com/drive/1A0b_42wEiRrkmmZMLe9xtJUzBXfEy7Zb?usp=sharing

**Comment by nyadla-sys** [comment]
@Burton2000 I have managed to generate a partial Whisper encoder model using full int8 with only a few layers remaining in float, and I will share the resulting model sometime next week.

**Comment by Burton2000** [comment]
> @Burton2000 I have generated int8 encoder and decoder TFLite models by converting a PyTorch model to ONNX, then from ONNX to TensorFlow, and finally from TensorFlow to TFLite. Unfortunately, the models are producing incorrect results. However, I am pleased to report that end-to-end inference runs on these models. Please refer to the attached notebook for more details. https://colab.research.google.com/drive/1A0b_42wEiRrkmmZMLe9xtJUzBXfEy7Zb?usp=sharing

Yep I followed your notebooks and got the whole pipeline working correctly for fp32 tflite and dynamic int8 quantized models but like you not working for fully int8 quantized, they were really helpful thank you. Sounding promising if you have some more progress on the encoder model!

**Comment by nyadla-sys** [comment]
Excluded few ops from quantization and now quantized encoder model runs here 
https://colab.research.google.com/gist/nyadla-sys/cccc1a1594c2be85050d8e217e4a59fa/pytorch_to_tflite_int8_encoder_hybdrid_decoder.ipynb

**Comment by sachinprasadhs** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
