### ISSUE TITLE
Slow compilation of certain operation files

### ISSUE THREAD

**Issue by georgthegreat** [tensorflow/tensorflow#59503]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.4.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

Not applicableapplicable

### Python version

Not applicable

### Bazel version

Not applicable

### GCC/Compiler version

clang14

### CUDA/cuDNN version

Not applicable

### GPU model and memory

Not applicable

### Current Behaviour?

```shell
Compiling certain ops takes too many time.
Here is a table with measurement of 10 slowest files:
The longest 10 tasks being:

* [673513 ms]: tensorflow/core/kernels/gather_op.cc
* [624861 ms]: tensorflow/core/kernels/argmax_op.cc
* [576809 ms]: tensorflow/core/kernels/resource_variable_ops.cc
* [526177 ms]: tensorflow/core/kernels/conv_grad_input_ops.cc
* [404275 ms]: tensorflow/core/kernels/bias_op.cc 
* [400613 ms]: tensorflow/core/kernels/batch_matmul_op_real.cc
* [395665 ms]: tensorflow/core/kernels/cwise_op_select.cc
* [381854 ms]: tensorflow/core/kernels/matmul_op.cc
* [379893 ms]: tensorflow/core/kernels/conv_ops.cc
* [340674 ms]: tensorflow/core/kernels/cwise_op_equal_to_1.cc
```

These measurements were done on `Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz`.
Out internal build system, being a heterogenious cluster, might schedule these compilations on older CPUs, where single compilation can take up to 15 minutes according to out measurements.

It looks like simply splitting macro instantations into multiple files will allow running compilations on parallel.

I will provide `gather_op.cc` split as an example.

### Standalone code to reproduce the issue

```shell
I am omitting -I and -D flags for the sake of brewity.
I believe that internal build system is able to provide the same statistics as well


clang++-c -m64 -O3 -g -ggnu-pubnames -fexceptions -fno-common -fuse-init-array -fcolor-diagnostics -faligned-allocation -fdebug-default-version=4 -ffunction-sections -fdata-sections -fopenmp=libomp -fopenmp-version=52 -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mpopcnt -mcx16 -std=c++20 -w -Wno-everything $(file)
```
```


### Relevant log output

_No response_</details>

**Comment by gaikwadrahul8** [comment]
Hi, @georgthegreat 

Apologize for the delay and I see you have submitted PR [#59504](https://github.com/tensorflow/tensorflow/pull/59504) from your end to address slow compilation of certain operation files and it will be taken care by concerned team once that PR got merged after following the PR procedure. Thank you for all the hard work and valuable time you put in that and I really I appreciate it. Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @georgthegreat 

I have re-opened this issue because submitted PR [#59504](https://github.com/tensorflow/tensorflow/pull/59504) is still in progress. Thank you!
