### ISSUE TITLE
request nvidia DALI support

### ISSUE THREAD

**Issue by nlp-tokio** [tensorflow/tensorflow#59516]
The framework now is not supporting nvidia DALI to accelerate data preprocessing. GPU training is slow for imagenet.

**Comment by sachinprasadhs** [comment]
@nlp-tokio , Could you please elaborate more on your request. 
Also, check the NVIDIA Tensorflow DALI plugin available [here](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/examples/frameworks/tensorflow/tensorflow-plugin-tutorial.html) with the example.
For your model preprocessing pipeline, you can refer [these](https://docs.nvidia.com/deeplearning/dali/user-guide/docs/plugins/tensorflow_tutorials.html) tutorials to speedup the process. 
Let us know if you need any further information. Thanks!
