### ISSUE TITLE
On MTK platforms, tflite calls the GPU with clGetPlatformIDs return -1001

### ISSUE THREAD

**Issue by Ijustakid** [tensorflow/tensorflow#59519]
**System information**
- Android Device information (use `adb shell getprop ro.build.fingerprint`
  if possible): Redmi/rembrandt/rembrandt:13/TP1A.220624.014/23.1.31:user/release-keys

- TensorFlow Lite in Play Services SDK version (found in `build.gradle`): 29
- Google Play Services version
  (`Settings` > `Apps` > `Google Play Services` > `App details`): 

**Standalone code to reproduce the issue**

on MTK platforms
code:
if (interpreter->ModifyGraphWithDelegate(delegate) != kTfLiteOk) {
            LOGE("delegate init failed!");
            exit(-1);
        }

get:
clGetPlatformIDs returned -1001 or clGetPlatformIDs returned -30

**Any other info / logs**
This MTK platform has a GPU device.

**Comment by mohantym** [comment]
Hi @Ijustakid !

Sorry for the late response.

'clGetPlatformIDs returned -1001'  indicate that you have not included opencl header files properly or Gpu drivers  .

[Ref](https://stackoverflow.com/a/24336429/11530462)

If you are trying to use GPU acceleration through Google play service, [Recommended practice](https://www.tensorflow.org/lite/android/play_services#gpu_with_interpreter_apis) is to mention play gpu delegate dependencies in your project files prior GPU delegate initialization.

But if you are trying to use C++ runtime to use GPU delegate , Please refer this [document](https://www.tensorflow.org/lite/android/delegates/gpu#cc_api_for_android) to properly include and add the gpu delegate header files.

Thank you!

**Comment by jnasti1** [comment]
This is old but still an open issue on Mali GPU (e.g. used by some? MTK/Mediatek chipsets)

The OpenCL wrapper (tensorflow/lite/delegates/gpu/cl/opencl_wrapper.cc) hardcodes the kClLibName as "libOpenCL.so" (and on recent releases of TF, will look at variants like libOpenCL-pixel.so, etc). ARM does not support or maintain this library anymore even though the .so can still be found on Android devices. ([link](https://github.com/ARM-software/ComputeLibrary/issues/291) that helped me realize this)

If you rebuild TFLite with updating the kClLibName to "libGLES_mali.so", I'm able to get OpenCL working properly as verified with the benchmark_model utility. You can look for this .so in several different paths, depending on your device ([link](https://github.com/SaschaWillems/OpenCLCapsViewer/blob/master/openclfunctions.cpp#L60) of an Android .apk that helped me verify OpenCL functionality called OpenCLCapsViewer).
