### ISSUE TITLE
Proto file missing in nightly wheels

### ISSUE THREAD

**Issue by maggie1059** [tensorflow/tensorflow#59514]
### Have you reproduced the bug with TF nightly?

Yes

### Tensorflow Version

tf 2.12

### Current Behaviour?

I work on the TensorFlow-DirectML plugin, and we use the .proto files included in the TF wheel to generate pb.cc/pb.h files needed by the plugin. One of the files needed is the tensorflow/tsl/profiler/protobuf/xplane.proto file, which has not been included in the nightly wheels so far. Would it be possible to make sure that it's included for TF 2.12?

**Comment by SuryanarayanaY** [comment]
Hi @maggie1059 ,

Are you referring to the file in below? This is available in Master branch at below path. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tsl/profiler/protobuf/xplane.proto

I downloaded the nightly wheel in colab and found all `.pb` files available at same location but converted into `.py` files.Please refer attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/708d83a387d54cb2138ff05da0efcff7/59514.ipynb). Is that what you are looking for ? Please confirm your exact requirement. Thanks!

**Comment by maggie1059** [comment]
Hi @SuryanarayanaY, I was hoping that the original .proto file could be included in the wheel, because we need the .proto file to generate the .pb.cc file with our own protobuf compiler in order to statically link against it. Would it be possible to get that file in the wheel (similar to the tensorflow/core/profiler/protobuf/xplane.proto file)?

**Comment by SuryanarayanaY** [comment]
Hi @maggie1059 ,

I have checked with TF2.11v and found that [.proto files in TF2.11](https://github.com/tensorflow/tensorflow/blob/r2.11/tensorflow/tsl/protobuf/error_codes.proto) also converted into .py files when build into wheels. Please refer the [gist](https://colab.research.google.com/gist/SuryanarayanaY/77cbb3308e3ae0f39187c3946a88eedb/59514-2-11.ipynb#scrollTo=7urvpXGEkpTv). This may be the way it is packaged since way back.

Can you confirm whether you observed .proto files  as it is in any older TF wheels?

I would like to know whether this is a `Regression issue` or `Feature request` so that way it can be handled.Please confirm.
Thanks!

**Comment by maggie1059** [comment]
Apologies for not being more specific -- the original .proto files are within the `tensorflow/include/tensorflow` folder, and I was hoping to have xplane.proto included in `tensorflow/include/tensorflow/tsl/profiler/protobuf`, similarly to `tensorflow/include/tensorflow/core/profiler/protobuf/xplane.proto`. I've updated [the gist](https://colab.research.google.com/gist/SuryanarayanaY/77cbb3308e3ae0f39187c3946a88eedb/59514-2-11.ipynb#scrollTo=7urvpXGEkpTv) you sent to show the xplane.proto file under core/profiler/protobuf.

**Comment by SuryanarayanaY** [comment]
@maggie1059 ,

With 2.11v the path of the file `xplane.proto` is: https://github.com/tensorflow/tensorflow/blob/r2.11/tensorflow/core/profiler/protobuf/xplane.proto

With tf-nightly(master) the path is: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/profiler/protobuf/xplane.proto . But inside the file its routed to the path `tensorflow/tsl/profiler/protobuf/xplane.proto` .

Iam assuming that in TF2.11v you want the file `xplane.proto` to be at `tensorflow/tsl/profiler/protobuf/xplane.proto` whereas currently it is at `tensorflow/core/profiler/protobuf/xplane.proto`. Correct me if Iam wrong. 

I can see in tf-nightly(master) we have two paths for the `xplane.proto` file. You need same for TF2.11 also. If so any specific reason for this path ? Please confirm.

**Comment by maggie1059** [comment]
I would want the `xplane.proto` file in `tensorflow/tsl/profiler/protobuf` to be included in the wheel, as well as the one that is already included in `tensorflow/core/profiler/protobuf` (i.e. I'm not asking for it to be moved, just for it to be included in addition). Also, this would be for the upcoming 2.12 release, as we are working on having our plugin depend on TF 2.12 when it is released. 

The latest tf-nightly wheel only includes the `xplane.proto` file under the `tensorflow/core/profiler/protobuf` folder. We need both of the files as our plugin requires the pb.cc files for both.

**Comment by SuryanarayanaY** [comment]
@sachinprasadhs , Do you have anything to say here ?

**Comment by mihaimaruseac** [comment]
CC @learning-to-play @rishikasinha-tf

**Comment by angerson** [comment]
@maggie1059, the solution to this problem looks simple: I just needed to add a TSL directory search to the list of files that we include when generating the pip package. I'm working on submitting the change now, and then I'll need to get it approved for a cherry-pick. Can you check and see if [this sample package](https://storage.googleapis.com/tensorflow-nightly/prod/tensorflow/rel/docker/critique_optional/cpu_any/282/20230207-145433/pkg/tf_nightly_cpu-2.13.0.dev20230207-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl) builds correctly? I've verified that it contains the missing xplane.proto.

**Comment by sachinprasadhs** [comment]
Thanks @angerson for the fix, @maggie1059 this change https://github.com/tensorflow/tensorflow/commit/46cdedf47c1f547d3c4ff9e3f63c12b7e7ec5a22 will be available in the upcoming Nightly release.

**Comment by SuryanarayanaY** [comment]
@maggie1059 , Hope your issue resolved and please feel free to close the issue if Ok to you.

**Comment by mihaimaruseac** [comment]
Commit needs to be cherrypicked to 2.12 branch first

**Comment by maggie1059** [comment]
Thank you @angerson! I see it in the sample wheel and the plugin is building as expected with it.

**Comment by angerson** [comment]
@maggie1059 Great. It's too late to merge this into TF 2.12 rc0, so rc0 will probably still be broken for you. It will arrive in the version after that (rc1 or final, depending on the release schedule).

**Comment by SuryanarayanaY** [comment]
@maggie1059 ,
As the PR already merged your requirement can be properly full-filled in next release. Do you wish to Open this issue till then? Thanks!

**Comment by angerson** [comment]
Yeah, the PR was merged early into rc0, so rc0 should build for you.

**Comment by maggie1059** [comment]
Yes, the tests on rc0 look good. I'll close the issue, thanks!
