### ISSUE TITLE
pthread cond_wait deadlock on assignment via tf.while_loop

### ISSUE THREAD

**Issue by jramapuram** [tensorflow/tensorflow#5952]
State:
- tf 0.12RC0 (installed via pip URL)
- Ubuntu 16.04
- cuda 8.0 w/cudnn 5.1

Ran python through gdb and it looks like there is a deadlock?
```python
import tensorflow as tf

with tf.Session() as sess:
    index = tf.constant(0)
    values_0 = [tf.constant(0, dtype=tf.int32), tf.zeros([10, 100])]
    cond = lambda i, val: tf.less(i, 10)
    def _update(i, val):
        row = tf.random_normal([1, 100])
        update = val + tf.concat(0, [tf.zeros([i, 100]),
                                     row,
                                     tf.zeros([10-1-i, 100])])
       # Just to verify sizing
        print 'update = ', update.get_shape().as_list(), \
            ' | values_0 = ', values_0[1].get_shape().as_list()

        return [i+i, update]

    _, values_t = tf.while_loop(cond, _update, values_0,
                                parallel_iterations=10)

    print sess.run(values_t)
```

Is this expected behavior? I want to update different rows of the matrix in parallel and this seemed somewhat logical to me. Since each row is independent it "shouldn't" really collide even if it is in parallel.

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.

**Comment by jramapuram** [comment]
@tfboyd : not sure I would say this is a support issue. 
`tf.while_loop` should not deadlock. This is undefined behavior.

**Comment by tfboyd** [comment]
I likely chose the wrong words it was a canned response.  I understand it can be frustrating as teams follow different processes and we did not document our action.  We essentially declared a "bug bankruptcy" and closed most issues older than ~6 months after a quick review.  

That said if you are seeing this behavior on TF 1.1 or 1.2, I am happy to reopen and try to push it back through Triage again.   

While wordy, I cannot stress enough no malice is intended and I read each bug in detail before closing.  I knew I would make a few mistakes and counted on people responding back.  Thank you for the ping.
