### ISSUE TITLE
Tensor flow lite wheel file for ARM9 32-bit architecture 

### ISSUE THREAD

**Issue by saimanohar1999** [tensorflow/tensorflow#59521]
i am trying to build .whl file for ARM9 32-bit architecture using Bazel, but fortuanetly there is no tool to build for 32-bit. can someone help me in getting my work done.

**Comment by saimanohar1999** [comment]
any reference which help me getting tflite dependencies for ARM9 architecture 32-bit.

**Comment by mohantym** [comment]
Hi @saimanohar1999 !
Could you check with below bazel command  (Bazel 5.3.0 ) . Attached [relevant document ](https://www.tensorflow.org/lite/guide/build_arm)for arm32 cross-compile 

`bazel build --config=elinux_armhf -c opt //tensorflow/lite/c:libtensorflowlite_c.so`

You can also Opt for [CMake ](https://www.tensorflow.org/lite/guide/build_cmake_arm)which offers a wide variety of cross-compiling .

Thank you!

**Comment by saimanohar1999** [comment]
thanks for the response. i was able to generate .so file but i need .whl file

**Comment by mohantym** [comment]
Hi @saimanohar1999 !
To get .whl file , Pleas refer [build_cmake_pip](https://www.tensorflow.org/lite/guide/build_cmake_pip) documentation.
Thank you!

**Comment by saimanohar1999** [comment]
i tried the above but unable to see .whl file may i know in which path we can see .whl file.

Thank you

**Comment by saimanohar1999** [comment]
tflite_runtime-2.12.0-cp38-cp38-linux_x86_64.whl i found this file /tensorflow/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/dist     in this path.

 but i am looking for 32-bit architecture.

**Comment by mohantym** [comment]
Hi @saimanohar1999 !
Thanks for the update.  You can check for other python wheels here in [Pinto's repo](https://github.com/PINTO0309/Tensorflow-bin).

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by saimanohar1999** [comment]
the Pintos repo mentioned above dosent have any .whl file for ARN9 32-bit architecture.

**Comment by saimanohar1999** [comment]
i didnt expect this much fast response. any reference related to my issue will be a great help for me and my company.
waiting for the next response.

Thank You

**Comment by saimanohar1999** [comment]
Let me know whether it is possible to generate .whl file or not through this process.

**Comment by saimanohar1999** [comment]
any update??

**Comment by sachinprasadhs** [comment]
I was able to find few references regarding .whl file location for Tensorflow( not specific to TFLite or any architecture).
In the below link, it explains about creating the .whl package with `bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg`
https://stackoverflow.com/questions/45855487/
Also, refer the guide [here](https://medium.com/@amsokol.com/update-1-how-to-build-and-install-tensorflow-gpu-cpu-for-windows-from-source-code-using-bazel-and-c2e86fec9ef2), which explains about building package using bazel, common issues and references.
Le me know if this is of any help for you, Thank you!

**Comment by saimanohar1999** [comment]
thank you @sachinprasadhs i already gone through the references which you shared, but the issue is iam unable to use custom toolchain to build dependencies.

**Comment by terryheo** [comment]
You need to cross compile to get ARM 32 bit binary.

https://www.tensorflow.org/lite/guide/build_cmake_pip#arm_cross_compilation

**Comment by saimanohar1999** [comment]
I tried doing that still i was unable to do it... @terryheo

**Comment by saimanohar1999** [comment]
@terryheo after 98% build with cmake its throwing the following error

In file included from /usr/include/python3.8/Python.h:8,
                 from /home/administrator/manohar/tensorflow_src/tensorflow/lite/python/interpreter_wrapper/numpy.h:49,
                 from /home/administrator/manohar/tensorflow_src/tensorflow/lite/python/interpreter_wrapper/numpy.cc:17:
/usr/include/python3.8/pyconfig.h:13:12: fatal error: arm-linux-gnueabihf/python3.8/pyconfig.h: No such file or directory
 #  include <arm-linux-gnueabihf/python3.8/pyconfig.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/python3.8/Python.h:8,
                 from /home/administrator/manohar/tensorflow_src/tensorflow/lite/python/interpreter_wrapper/python_error_reporter.h:19,
                 from /home/administrator/manohar/tensorflow_src/tensorflow/lite/python/interpreter_wrapper/python_error_reporter.cc:16:
/usr/include/python3.8/pyconfig.h:13:12: fatal error: arm-linux-gnueabihf/python3.8/pyconfig.h: No such file or directory
 #  include <arm-linux-gnueabihf/python3.8/pyconfig.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/python3.8/Python.h:8,
                 from /home/administrator/manohar/tensorflow_src/tensorflow/lite/python/interpreter_wrapper/python_utils.h:19,
                 from /home/administrator/manohar/tensorflow_src/tensorflow/lite/python/interpreter_wrapper/python_utils.cc:16:
/usr/include/python3.8/pyconfig.h:13:12: fatal error: arm-linux-gnueabihf/python3.8/pyconfig.h: No such file or directory
 #  include <arm-linux-gnueabihf/python3.8/pyconfig.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
compilation terminated.
make[3]: *** [CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/build.make:89: CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/python/interpreter_wrapper/numpy.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/build.make:115: CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/python/interpreter_wrapper/python_utils.cc.o] Error 1
make[3]: *** [CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/build.make:102: CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/python/interpreter_wrapper/python_error_reporter.cc.o] Error 1
In file included from /usr/include/python3.8/Python.h:8,
                 from /home/administrator/.local/lib/python3.8/site-packages/pybind11/include/pybind11/detail/../detail/common.h:266,
                 from /home/administrator/.local/lib/python3.8/site-packages/pybind11/include/pybind11/detail/../attr.h:13,
                 from /home/administrator/.local/lib/python3.8/site-packages/pybind11/include/pybind11/detail/class.h:12,
                 from /home/administrator/.local/lib/python3.8/site-packages/pybind11/include/pybind11/pybind11.h:13,
                 from /home/administrator/.local/lib/python3.8/site-packages/pybind11/include/pybind11/functional.h:12,
                 from /home/administrator/manohar/tensorflow_src/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper_pybind11.cc:19:
/usr/include/python3.8/pyconfig.h:13:12: fatal error: arm-linux-gnueabihf/python3.8/pyconfig.h: No such file or directory
 #  include <arm-linux-gnueabihf/python3.8/pyconfig.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/build.make:76: CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/python/interpreter_wrapper/interpreter_wrapper_pybind11.cc.o] Error 1
In file included from /usr/include/python3.8/Python.h:8,
                 from /home/administrator/manohar/tensorflow_src/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.h:28,
                 from /home/administrator/manohar/tensorflow_src/tensorflow/lite/python/interpreter_wrapper/interpreter_wrapper.cc:15:
/usr/include/python3.8/pyconfig.h:13:12: fatal error: arm-linux-gnueabihf/python3.8/pyconfig.h: No such file or directory
 #  include <arm-linux-gnueabihf/python3.8/pyconfig.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/build.make:63: CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/python/interpreter_wrapper/interpreter_wrapper.cc.o] Error 1
make[3]: Leaving directory '/home/administrator/manohar/tensorflow_src/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/cmake_build'
make[2]: *** [CMakeFiles/Makefile2:1252: CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/all] Error 2
make[2]: Leaving directory '/home/administrator/manohar/tensorflow_src/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/cmake_build'
make[1]: *** [CMakeFiles/Makefile2:1259: CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/rule] Error 2
make[1]: Leaving directory '/home/administrator/manohar/tensorflow_src/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/cmake_build'
make: *** [Makefile:164: _pywrap_tensorflow_interpreter_wrapper] Error 2



thank you.

**Comment by terryheo** [comment]
Could you share the command you used?

**Comment by saimanohar1999** [comment]
i figured out i was able to get 32-bit file ".whl" with the following command 
make -C tensorflow/lite/tools/pip_package docker-build \   TENSORFLOW_TARGET=armhf  PYTHON_VERSION=3.8

with the above command i was able to get  "tflite_runtime-2.13.0-cp38-cp38-linux_armv7l.whl" file

i guess its for arm7 architecture, i want for arm9 architecture.

later upto my understanding i figured out that the issue is because of toolchain used, can u help me changing the toolchain ....since in the make file "download_toolchain.sh" it is downloading toolchain for arm7 architecture but i need for arm926, to be specific for SAM9X60 Board.

Thank you @terryheo

**Comment by saimanohar1999** [comment]
@terryheo  still i am facing issues in generating file for sam9x60 which is ARM926 based board , help me in solving this.

**Comment by saimanohar1999** [comment]
cd /tensorflow/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3.10/cmake_build/_deps/flatbuffers-build && /opt/cmake/bin/cmake -P CMakeFiles/flatbuffers.dir/cmake_clean_target.cmake
cd /tensorflow/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3.10/cmake_build/_deps/flatbuffers-build && /opt/cmake/bin/cmake -E cmake_link_script CMakeFiles/flatbuffers.dir/link.txt --verbose=1
/usr/bin/ar qc libflatbuffers.a  CMakeFiles/flatbuffers.dir/src/idl_parser.cpp.o CMakeFiles/flatbuffers.dir/src/idl_gen_text.cpp.o CMakeFiles/flatbuffers.dir/src/reflection.cpp.o CMakeFiles/flatbuffers.dir/src/util.cpp.o
/usr/bin/ranlib libflatbuffers.a
make[3]: Leaving directory '/tensorflow/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3.10/cmake_build'
[ 16%] Built target flatbuffers
make[2]: Leaving directory '/tensorflow/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3.10/cmake_build'
make[1]: *** [CMakeFiles/Makefile2:1393: CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/rule] Error 2
make[1]: Leaving directory '/tensorflow/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3.10/cmake_build'
make: *** [Makefile:193: _pywrap_tensorflow_interpreter_wrapper] Error 2
make: *** [Makefile:72: docker-build] Error 2
make: Leaving directory '/home/administrator/manohar/tensorflow_src/tensorflow/lite/tools/pip_package


this is the error i am getting, but when i am building with toolchain supporting armv7 build was successful, now when i am using arm-none-eabi toolchain for sam9x60 board i am getting this build error. i hope i am clear

**Comment by saimanohar1999** [comment]
Hi @terryheo 

[https://docs.google.com/document/d/1Q2f-uC4xMusDsDwCHrxMP78efhneFJeYuG9x7oAPSJw/edit](url)

I have attached the link where i explained clearly about the current issue with all the flags i used during build process. please go through it and le me know if you still need any details to get better understanding of the problem.

**Comment by saimanohar1999** [comment]
Hi @terryheo can you help me in getting the toolchain for armv5te to build ....may be there might be issue with the toolchain i am using...

Thank you.

**Comment by pkgoogle** [comment]
Hi @saimanohar1999, it appears your link is broken can you please provide a working link? Thank you.

**Comment by saimanohar1999** [comment]
Hi pkgoogle, what link are you referring to.

**Comment by pkgoogle** [comment]
@saimanohar1999 This one: [https://docs.google.com/document/d/1Q2f-uC4xMusDsDwCHrxMP78efhneFJeYuG9x7oAPSJw/edit](https://github.com/tensorflow/tensorflow/issues/url) from Mar 1
