### ISSUE TITLE
Windows 'models' directory

### ISSUE THREAD

**Issue by adamb70** [tensorflow/tensorflow#5953]
I'm following through the tutorial and it seems that the 'tensorflow/models/' directory is missing from the TensorFlow 0.12.0 RC0 build for Windows - at least when downloaded using pip.

I installed TensorFlow using `pip3 install --upgrade https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-0.12.0rc0-cp35-cp35m-win_amd64.whl`. The initial test of TensorFlow ran fine.

Additionally running `python3 -m tensorflow.models.image.mnist.convolutional` produces the follwing error:

	I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cublas64_80.dll locally
	I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cudnn64_5.dll locally
	I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cufft64_80.dll locally
	I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library nvcuda.dll locally
	I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library curand64_80.dll locally
	C:\Program Files\Python35\python3.exe: Error while finding spec for 'tensorflow.models.image.mnist.convolutional' (ImportError: No module named 'tensorflow.models')

I'm new to TensorFlow so please correct me if the Models module is not supposed to be packaged with the pip download.

**Comment by codeloop** [comment]
Execute this command to locate the Tensorflow Models in your Tensorflow python environment,
import os; 
import inspect; 
import tensorflow; print(os.path.dirname(inspect.getfile(tensorflow)))

Will give you the directory for the models.

**Comment by kingtaurus** [comment]
The models directory is not included within the pip install.

**Comment by adamb70** [comment]
This is the contents of the tensorflow package directory after installing via pip.

     Directory of C:\Program Files\Python35\Lib\site-packages\tensorflow
    
    29/11/2016  21:23    <DIR>          .
    29/11/2016  21:23    <DIR>          ..
    29/11/2016  21:23    <DIR>          contrib
    29/11/2016  21:23    <DIR>          core
    29/11/2016  21:23    <DIR>          examples
    29/11/2016  21:23    <DIR>          python
    29/11/2016  21:23    <DIR>          tensorboard
    29/11/2016  21:22             1,477 __init__.py
    29/11/2016  21:23    <DIR>          __pycache__

**Comment by Carmezim** [comment]
DId you try installing using:
`pip install tensorflow` 
In your case for GPU support enabled
`pip install tensorflow-gpu`

You only need Python 3.5 64-bit and CUDA 8.0.

**Comment by mrry** [comment]
@nealwu Am I right in thinking that these scripts are about to move to a different location anyway? If that's the case, we probably won't add them to the wheel for 0.12, but they should work if you clone the git repository and run them from there.

**Comment by nealwu** [comment]
Yep, I'll be moving these models out of this repo and into https://github.com/tensorflow/models very soon, so this will no longer be Windows-specific. :)
