### ISSUE TITLE
conv and fused relu fails on GPUv2 delegate on OpenCL when batch size > 1

### ISSUE THREAD

**Issue by brtal** [tensorflow/tensorflow#59560]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.11

### Custom Code

Yes

### OS Platform and Distribution

Android 13

### Mobile device

Google Pixel 5 (and others)

### Python version

3.10.9

### Current Behaviour?

Loading this model with the GPUv2 delegate, with OpenCL selected, causes the delegate to fail to prepare when batch = 5. When batch = 1, conv and fused relu works fine.

We'd like to understand whether fusioned ops are expected to work with batch > 1. Is this a tflite bug or a known limitation?

And if a limitation, what is the recommended workaround?

### Standalone code to reproduce the issue

This is the code to produce the tflite model that produces a conv + fused relu, which fails on the GPUv2 delegate on OpenCL.

```python
import numpy as np
import tensorflow as tf

input_shapes = [(5, 224, 224, 3)]

def SimpleNet():
    nc = 3
    model = tf.keras.models.Sequential([
        tf.keras.layers.Input(shape=(input_shapes[0][3],) + input_shapes[0][1:3], batch_size=input_shapes[0][0], name='input'),
        tf.keras.layers.Permute((2, 3, 1)),
        tf.keras.layers.Conv2D(nc, kernel_size=3, padding="valid", use_bias=True, activation="relu"),
        tf.keras.layers.Permute((3, 1, 2)),
    ])

    return model

tf_model = SimpleNet()
tf_model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
tf_model.summary()

converter = tf.lite.TFLiteConverter.from_keras_model(tf_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

# Save the model.
with open("conv_relu_batch5.tflite", "wb") as f:
    f.write(tflite_model)
```
```


### Relevant log output

```shell
[tflite] TfLiteGpuDelegate Init: Unrecognized Write selector
[tflite] Created 0 GPU delegate kernels.
[tflite] TfLiteGpuDelegate Prepare: delegate is not initialized
[tflite] Node number 3 (TfLiteGpuDelegateV2) failed to prepare.
[tflite] Restored original execution plan after delegate application failure.
```
</details>

**Comment by grantjensen** [comment]
I ran your code, and benchmarked the tflite file using tensorflow/lite/tools/benchmark:benchmark_model --use_gpu=true. It ran fine on my machine. One possible issue might be if you have not synced your runtime tensorflow to include this commit: https://github.com/tensorflow/tensorflow/commit/642ccc0828a3ff8a6187f4d61f0c727602990596
