### ISSUE TITLE
OSAtomic* OS X includes deprecated in 10.12

### ISSUE THREAD

**Issue by vade** [tensorflow/tensorflow#5956]
### Environment info
Operating System: Mac OS X 10.12.1

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
N/A

1. The commit hash (`git rev-parse HEAD`)
41285cf7a11fa3a2c2ead6b6e9adcec4232b18ad (rc11  release from GIT)

2. The output of `bazel version`
Build label: 0.4.0-homebrew

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

#import "tensorflow/cc/ops/const_op.h"

`
Showing All Messages
/Users/vade/Documents/Repositories/Synopsis/Synopsis/Synopsis/TensorFlowAnalyzer/includes/google/protobuf/stubs/atomicops_internals_macosx.h:47:9: 'OSAtomicCompareAndSwap32' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_compare_exchange_strong_explicit(std::memory_order_relaxed) from <atomic> instead

`

etc etc

### What other attempted solutions have you tried?

N/A

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by poxvoculi** [comment]
I see this related issue for protobufs:  https://github.com/google/protobuf/issues/2182
which supposedly has been fixed.   @petewarden have we picked that up for TF on Mac?

**Comment by vade** [comment]
Let me confirm this is an issue with RC 12 in the mean time. Thank you.
