### ISSUE TITLE
cwise_op_gpu_logical_or.cu.pic.o' was not created

### ISSUE THREAD

**Issue by dazheyizu** [tensorflow/tensorflow#59571]
./tensorflow/stream_executor/stream.h(2165): warning: type qualifier on return type is meaningless

./tensorflow/stream_executor/stream.h(2168): warning: type qualifier on return type is meaningless

./tensorflow/core/kernels/topk_op_gpu.h(440): warning: integer conversion resulted in a change of sign

ERROR: /sources/tensorflow/tensorflow/core/kernels/BUILD:4079:1: output 'tensorflow/core/kernels/_objs/cwise_op_gpu/cwise_op_gpu_logical_or.cu.pic.o' was not created
ERROR: /sources/tensorflow/tensorflow/core/kernels/BUILD:4079:1: not all outputs were created or valid
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 2271.782s, Critical Path: 420.46s

**Comment by pjpratik** [comment]
@dazheyizu We see that the issue [template]( https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=&template=tensorflow_issue_template.yaml) has not been filled.

Could you please do so as it helps us analyze the issue (TF version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced). Thanks!
