### ISSUE TITLE
 tf.keras.callbacks.ModelCheckpoint: initial_value_threshold not working, definition with a mistake

### ISSUE THREAD

**Issue by agoeroeg** [tensorflow/tensorflow#59577]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

'2.3.0'

### Custom Code

Yes

### Current Behaviour?

```shell
The manual defines initial_value_threshold as 
"Floating point initial "best" value of the metric to be monitored. Only applies if save_best_value=True. Only overwrites the model weights already saved if the performance of current model is better than this value. "

save_best_value is not defined!

If  save_best_only was meant, then it is not working like the manual says.
I have no other idea, how should I get initial_value_threshold work, it is still starting with -inf.
```

### Standalone code to reproduce the issue

```shell
es = EarlyStopping(monitor='val_loss', verbose=1, patience=20)
tmpmodelfile = 'models/' + model_config_name + '/temp1_best_model.h5'

evaluation = model.evaluate(vd[feature_cols], vd[target], 
                            batch_size=batch_size, verbose=2,
                            return_dict=True)
#3231/3231 - 2s - loss: 0.0500 - mean_squared_error: 0.0500
mc = ModelCheckpoint(tmpmodelfile, monitor='val_loss', 
                     verbose=1, save_best_only=True, 
                     initial_value_threshold=evaluation['loss'],
                     save_best_value=True)
history = model.fit(td[feature_cols], td[target], 
                    validation_data=(vd[feature_cols], vd[target]), 
                    batch_size=batch_size, epochs=epochs, 
                    verbose=2, callbacks=[es, mc])
Epoch 1/400
Epoch 00001: val_loss improved from inf to 0.04999, saving model to models
```

### Relevant log output

_No response_</details>

**Comment by pjpratik** [comment]
@agoeroeg Thanks for reporting the issue.

I tried to replicate the issue in TF v2.3 and and in the latest TF v2.11 using a [simple MNIST convnet](https://keras.io/examples/vision/mnist_convnet/) .

I have observed the reported behaviour in TF 2.3 where as in TF 2.11 I was able to get the `initial_value_threshold` work with the given value. 

Please find the gist of TF 2.3 [here](https://colab.research.google.com/gist/pjpratik/1fb72958bcf1ff03ff61634f9e3cfe03/59577_2-3.ipynb) and gist of TF 2.11 [here](https://colab.research.google.com/gist/pjpratik/6feee0f23ba7e67e1ca3b8a8868e73b5/59577_2-11.ipynb) and let us know if it helps. Thanks!
