### ISSUE TITLE
tf.GradientTape throws internal error: RET_CHECK failure

### ISSUE THREAD

**Issue by trickiwoo** [tensorflow/tensorflow#59582]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.13.0.dev20230204

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04.4 LTS

### Current Behaviour?

```shell
tf.GradientTape throws internal error: RET_CHECK failure
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

# Create a simple Keras model.
with tf.device('gpu'):
    x = [-1, 0, 1, 2, 3, 4]
    y = [-3, -1, 1, 3, 5, 7]
    model = tf.keras.models.Sequential(
        [tf.keras.layers.Dense(units=1, input_shape=[1])])
    model.compile(optimizer='sgd', loss='mean_squared_error')
    model.fit(x, y, epochs=500)
```

### Relevant log output

```shell
Node: 'StatefulPartitionedCall_1'
RET_CHECK failure (tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:618) dnn != nullptr 
         [[{{node StatefulPartitionedCall_1}}]] [Op:__inference_train_function_437]
```
</details>

**Comment by tiruk007** [comment]
@trickiwoo 
I was able to reproduce the issue on Colab using tf-nightly but I was able to execute the given code on Colab using TF v2.11. tf-nightly which is unstable, Could you please try on the latest stable version which is TF v2.11 and find the gist of [TF v2.11](https://colab.research.google.com/gist/tiruk007/0c1f6cef9de20d9ad88e1d367da00c6d/59582.ipynb) and [tf-nightly](https://colab.research.google.com/gist/tiruk007/a55d40d9a3a0232ab6426ad1de08113e/59582_nightly.ipynb) for reference . Let us know if it helps.

Thank you!
