### ISSUE TITLE
RNN model in the tutorial doesn't work: tensorflow.python.framework.errors.NotFoundError: /tmp/simple-examples/data/ptb.train.txt

### ISSUE THREAD

**Issue by zzf-technion** [tensorflow/tensorflow#5959]
Hi, my computer works on Mac OS X, CPU only, Python 2.7, use pip install tensorflow and run the first neural net model successfully: tensorflow/models/image/mnist/ convolutional.py 

But I try to repeat the tutorial of CNN model according to the instructions:
cd tensorflow/models/rnn/ptb
python ptb_word_lm.py --data_path=/tmp/simple-examples/data/ --model small

Firstly, there is no such file ptb_word_lm.py in the default directory /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/models/rnn/ptb/, then I copied the file to this directory, but another error occurred:
tensorflow.python.framework.errors.NotFoundError: /tmp/simple-examples/data/ptb.train.txt

Can you help explain a little bit about such error    @jmhodges 

Thanks

**Comment by jmhodges** [comment]
(I'm not a tensorflow team member and can't really help. Just some guy in the internet)

**Comment by poxvoculi** [comment]
This type of user question is best asked on stackoverflow.  This forum is for bug reports and similar.
