### ISSUE TITLE
Is there a quick tutorial for Windows users to use Tensorflow?

### ISSUE THREAD

**Issue by jindongwang** [tensorflow/tensorflow#5960]
The good news is Tensorflow finally supports Windows platform, but with very trival configurations.
And there is another important: Most of the PCs are running Windows.
So I really think it is truly necessary to provide a easy way for Windows users to run Tensorflow. A good toolkit is always the one that can cross all the platforms, right?
Is there a quick way to connect? On Linux/Mac, we can use pip, just a simple loc, and that's all. Everything seems not so fluid on Windows, why? Is it really that hard? I do think Tensorflow will get far more way if Windows is supported.

**Comment by jindongwang** [comment]
pip install --upgrade **--ignore-installed** https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl
AND THAT'S ALL!!!
Hail!!!

**Comment by miyosi55** [comment]
Also you should see this instruction. :)
https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html#pip-installation-on-windows

**Comment by akrai48** [comment]
you may also need to see this #5949.
