### ISSUE TITLE
Location of the TFLite API source code

### ISSUE THREAD

**Issue by APatel2001** [tensorflow/tensorflow#59600]
I had a question. I am currently working on a project with the Google Coral TPU. Essentially, we found that the coral TPU doesn't support every operation supported by tflite and we wanted to make the coral support more operations. I see that all the functions supported by tflite are documented here: https://www.tensorflow.org/mlir/tfl_ops. However, I cannot find the source code for these functions inside the tensorflow repository. Does tensorflow lite just take the standard tensorflow functions and add a wrapper around them? If anyone here has any experience working with the tensorflow source in any way, I would appreciate the help!

**Comment by sachinprasadhs** [comment]
Hi, You can find the source code for all the implementation of MLIR on TFLite here https://github.com/tensorflow/tensorflow/tree/master/tensorflow/compiler/mlir/lite/ir.
The source code is mainly implemented in `C/C++` and `.td `

**Comment by sachinprasadhs** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks!

**Comment by sachinprasadhs** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
