### ISSUE TITLE
[tensorflow_datasets 4.8.2]: Connection refused when trying to load huggingface datasets

### ISSUE THREAD

**Issue by YuliyaPylypiv** [tensorflow/tensorflow#59623]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

No

### OS Platform and Distribution

macOS

### Python version

3.8, 3.9, 3.10

### Current Behaviour?

```shell
Cannot load huggingface datasets

Used to work fine on 02/01/2023
```

### Standalone code to reproduce the issue

```shell
import tensorflow_datasets
data = tensorflow_datasets.load('glue/mrpc')
```

### Relevant log output

```shell
2023-02-08 17:46:43.871073: E tensorflow/core/platform/cloud/curl_http_request.cc:614] The transmission  of request 0x7fb417f4b9a0 (URI: http://metadata/computeMetadata/v1/instance/service-accounts/default/token) has been stuck at 0 of 0 bytes for 61 seconds and will be aborted. CURL timing information: lookup time: 0.003921 (No error), connect time: 0 (No error), pre-transfer time: 0 (No error), start-transfer time: 0 (No error)
```
</details>

**Comment by YuliyaPylypiv** [comment]
After a while it loaded. Should it take so long?

W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "ABORTED: All 10 retry attempts failed. The last failure: Error executing an HTTP request: libcurl code 42 meaning 'Operation was aborted by an application callback', error details: Callback aborted".
Downloading and preparing dataset 1.43 MiB (download: 1.43 MiB, generated: Unknown size, total: 1.43 MiB) to /Users/x/tensorflow_datasets/glue/mrpc/1.0.0...
Downloading and preparing dataset glue/mrpc to /Users/x/.cache/huggingface/datasets/glue/mrpc/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad...
Downloading data: 6.22kB [00:00, 3.34MB/s]                                                                                                                                  | 0/3 [00:00<?, ?it/s]
Downloading data: 1.05MB [00:00, 8.07MB/s]████████████████████████████████                                                                                          | 1/3 [00:00<00:01,  1.73it/s]
Downloading data: 441kB [00:00, 4.40MB/s]██████████████████████████████████████████████████████████████████████████████                                             | 2/3 [00:01<00:00,  1.83it/s]
Downloading data files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:01<00:00,  1.84it/s]
Dataset glue downloaded and prepared to /Users/x/.cache/huggingface/datasets/glue/mrpc/1.0.0/dacbe3125aa31d7f70367a07a8a9e72a5a0bfeb5fc42e75c9db75b96da6053ad. Subsequent calls will reuse this data.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 322.06it/s]
Dataset glue downloaded and prepared to /Users/x/tensorflow_datasets/glue/mrpc/1.0.0. Subsequent calls will reuse this data.                                                                  
2023-02-08 17:50:58.416766: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Metal device set to: AMD Radeon Pro 5500M

systemMemory: 32.00 GB
maxCacheSize: 3.99 GB

2023-02-08 17:50:58.417866: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-02-08 17:50:58.417928: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

**Comment by tiruk007** [comment]
@YuliyaPylypiv 
I was able to load the `glue/mrpc` dataset without any error on Colab using TF v2.11. Could you please find the gist [here](https://colab.research.google.com/gist/tiruk007/07488087d9893ce6193a796829f2295d/59623.ipynb) for reference.

Thank you!

**Comment by YuliyaPylypiv** [comment]
Thank you @tiruk007 for your response! Looks like it's working again for me!
