### ISSUE TITLE
Should slim.learning.train and slim.evaluation.evaluation handle OutOfRange gracefully?

### ISSUE THREAD

**Issue by alsrgv** [tensorflow/tensorflow#5964]
I'm finding it very hard train DNN for specific number of epochs unless I precompute number of batches, which is not convenient in streaming case, since TFRecord files don't have # of examples handy.

Should slim.learning.train and slim.evaluation.evaluation handle OutOfRange gracefully?  If that was the case, I could just set num_epochs on my input and max out num_evals.

Happy to send PR if this seems reasonable.

**Comment by poxvoculi** [comment]
Do you have a PR that works?   Seems useful.  @sguada

**Comment by alsrgv** [comment]
Just sent PR https://github.com/tensorflow/tensorflow/pull/6028.

**Comment by tfboyd** [comment]
Thank you for the PR.  Also the new DataSet API should also make it easier to catch the end of en epoch.  https://github.com/tensorflow/tensorflow/tree/r1.2/tensorflow/contrib/data
