### ISSUE TITLE
Tensorboard shows huge idle time and no blank spaces on GPU

### ISSUE THREAD

**Issue by alex19999** [tensorflow/tensorflow#59655]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf. 2.9

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

Linux Ubuntu 20.04

### Python version

3.9

### CUDA/cuDNN version

11.3

### GPU model and memory

Nvidia GeForce RTX 3090

### Current Behaviour?

```shell
I'm new to TF profiler and tensorboard. Could you please tell me how GPU idle time is calculated? I see contradictory data in profiling information on tensorboard and no information about it in docs:

 - I have no blank spaces in events trace (GPU compute stream) presented on `trace_viewer` page.
 - Wherein device (GPU) idle time shown on `tensorflow_stats` page is about 50%???

It's what I see when I use small batch size. After increasing batch size, same situation is on `trace_viewer` page, but GPU idle time decreased up to 7%. So, how is idle time calculated?

By the way, another two questions:
1. What is `steps` on `trace_viewer` page?
2. Why does `trace_viewer` page contain only a part of profiling time? I profiled about 100 seconds of execution, but I see only 10 seconds on `trace_viewer` page.


Thanks a lot in advance!
```

### Standalone code to reproduce the issue

```shell
I've used next setup:
tf.profiler.experimental.start
<training>
tf.profiler.experimental.end
```

### Relevant log output

_No response_</details>

**Comment by synandi** [comment]
Hi @alex19999, 
In order to expedite the trouble-shooting process, kindly share complete reproducible code to replicate the issue reported here. Thank you!
