### ISSUE TITLE
Update curl to 7.88.0

### ISSUE THREAD

**Issue by RamanSggs** [tensorflow/tensorflow#59693]
Vulnerabilities are reported in curl 7.87. Can someone please update curl to 7.88 ?

**Comment by Kangie** [comment]
https://lore.kernel.org/distributions/e3306ab8-3656-3128-40f8-f76e6871a3a3@footclan.ninja/T/#u

tl;dr it might be worth holding off.

**Comment by synandi** [comment]
Hi @RamanSggs, In order to expedite the trouble shooting process, please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) and share complete reproducible code.  Thank you!

**Comment by mihaimaruseac** [comment]
This should be handled by #59695
