### ISSUE TITLE
Video CNN Tutorial

### ISSUE THREAD

**Issue by chewman19** [tensorflow/tensorflow#59701]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.11.0

### Custom Code

No

### Python version

3.9

### Current Behaviour?

```shell
I do not know if this belongs here. 

I was trying to work through your "Video classification with a 3D convolutional neural network" tutorial. Going through the "Load Video Data" portion. I keep coming across an error that I cannot resolve.

" line 102, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)

ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.
"
this is the code step:
ucf_sample_video = frames_from_video_file(next(subset_paths['train'].glob('*/*.avi')), 50)

The isolated video_path argument in the tutorial works, it just seems to be this assignment and I am not sure how to fix it.

I have tried to work through with little success and end up getting the same error farther down in the tutorial with:

for frames, labels in train_ds.take(10):
  print(labels)

I apologize if this is not where I should be posting stuff about the tutorial.
```

### Standalone code to reproduce the issue

```shell
https://www.tensorflow.org/tutorials/load_data/video

I have copied and pasted everything that you see in your tutorial.
```

### Relevant log output

_No response_</details>

**Comment by synandi** [comment]
@chewman19  I was able to execute the code from [Load video data](https://www.tensorflow.org/tutorials/load_data/video) tutorial succesfully using TF v 2.11. Kindly refer to the gist [here](https://colab.sandbox.google.com/gist/synandi/a9e43199c8c958f5f3178ce7d4e0ff14/59701.ipynb). For better assistance please share the colab gist in which you are executing the code from Load video data tutorial.  Thank you!

**Comment by synandi** [comment]
Closing as stale. Please reopen if you'd like to work on this further.
