### ISSUE TITLE
tflite_runtime wheel file import error in beaglebone black wireless

### ISSUE THREAD

**Issue by ZIFENG278** [tensorflow/tensorflow#59707]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

tf

### Custom Code

No

### OS Platform and Distribution

Debian GNU/Linux 10 (buster)

### Python version

3.7.3

### Current Behaviour?

```shell
i want to install tflite_runtime on beaglebone black wireless, and i build the wheel file follow the https://www.tensorflow.org/lite/guide/build_cmake_pip and i change the -mfpu=neon-vpfv4 to -mfpu=neon becauuse the beaglebone black wireless is not support the vpfv4, after build the wheel file and install in beaglebone black,
in python3 code: "from tflite_runtime.interpreter import Interpreter", it output 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/debian/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 33, in <module>
    from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: /home/debian/.local/lib/python3.7/site-packages/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.so: undefined symbol: _ZN6tflite9telemetry20TelemetryReportEventEP13TfLiteContextPKc12TfLiteStatus
>>>
```

### Standalone code to reproduce the issue

```shell
from tflite_runtime.interpreter import Interpreter
```

### Relevant log output

_No response_</details>

**Comment by Adesoji1** [comment]
@ZIFENG278 try this below 
It looks like there might be an issue with the TensorFlow Lite build for your BeagleBone Black Wireless. The error message you're getting suggests that there is an unresolved symbol when loading the shared library.

Here are some suggestions to resolve this issue:

Ensure that you have built the TensorFlow Lite wheel file correctly for your platform by following the instructions in the [guide](https://www.tensorflow.org/lite/guide/build_cmake_pip).

Double-check the compilation flags you used when building the wheel file, as you mentioned that you changed the -mfpu=neon-vpfv4 flag to -mfpu=neon. Ensure that this change is compatible with your platform's architecture and requirements.

Try rebuilding the wheel file and reinstalling it on your BeagleBone Black Wireless. Make sure to remove any previous installations of tflite_runtime before reinstalling. 

If the issue persists, consider posting a detailed description of your build process, the flags you used, and the platform information on the [TensorFlow GitHub issues](https://github.com/tensorflow/tensorflow/issues) page. The TensorFlow team or the community members might be able to help you with your specific issue.

Good luck, and I hope you manage to resolve the issue!

**Comment by ZIFENG278** [comment]
@Adesoji1 Thanks for your answer,

The problem I found was that I built the wheel in a conda=py3.7 environment, which could have been problematic, the guide mentions it uses docker to build it so I ignored that

This time I built the wheel in my bash environment after a git pull and it installed successfully in my beaglebone black wireless.

Thanks for help.
