### ISSUE TITLE
[Windows] How to install cuDNN and enable GPU for Windows?

### ISSUE THREAD

**Issue by f133030** [tensorflow/tensorflow#5970]
Operating System: Windows 10

Here is what I got when tried to import tensorflow (which is successful in itself):

`C:\Users\GoBack>python
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1
900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\dso_loader.cc:128] successfully opened CUDA library cublas64_80.dll
locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\dso_loader.cc:119] Couldn't open CUDA library cudnn64_5.dll
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\cuda\cuda_dnn.cc:3459] Unable to load cuDNN DSO
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\dso_loader.cc:128] successfully opened CUDA library cufft64_80.dll l
ocally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\dso_loader.cc:128] successfully opened CUDA library nvcuda.dll local
ly
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\dso_loader.cc:128] successfully opened CUDA library curand64_80.dll
locally
>>>`

It seems that the Cuda Toolkit can be installed properly, but cuDNN may not. Besides, I didn't see any instructions about this matter in the Tutorials or the Release notes.
Thanks a lot in advance!

**Comment by mrry** [comment]
This looks like the same problem as #5968, so I'm going to close this as a duplicate. Please look at  my response there and let me know on that thread if it solves the problem. Thanks!
