### ISSUE TITLE
tf.experimental.numpy.power behaves differently when inputs are large numbers

### ISSUE THREAD

**Issue by trickiwoo** [tensorflow/tensorflow#59705]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.13.0.dev20230204

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04.4 LTS

### Current Behaviour?

```shell
tf.experimental.numpy.power behaves differently when inputs are large numbers
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

with tf.device("cpu"):
    x_t = tf.experimental.numpy.power(2, 64)
    print(x_t)

with tf.device("gpu"):
    x_t = tf.experimental.numpy.power(2, 64)
    print(x_t)
```

### Relevant log output

```shell
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
```
</details>

**Comment by pjpratik** [comment]
@trickiwoo Thanks for reporting this issue.

I was able to reproduce this behaviour on TF 2.11 and TF Nightly 2.13.0-dev20230215. 

However, `tf.math.pow` has not shown any such behaviour on GPU. Please find the [gist](https://colab.research.google.com/gist/pjpratik/cc9e46c992bcc4631133f57064f9e7db/59705.ipynb) here.

@tilakrayal Could you please look into this. Thanks!

**Comment by nrwahl2** [comment]
Right, `tf.experimental.numpy.pow()` converts its scalar arguments to `tf.Tensor` before passing to `gen_math_ops._pow()`.

`tf.math.pow()` passes them as scalars. That seems to make a difference in the GPU case, but apparently not in the CPU case.

**Comment by sachinprasadhs** [comment]
Tried with Apple M1 GPU and it is gibing the expected result.
Seems to be issue only when NVIDIA GPU is used. It needs more investigation.
```
with tf.device("gpu"):
    x_t = tf.experimental.numpy.power(2, 64)
    print(x_t)
```
`tf.Tensor(0, shape=(), dtype=int64)`

**Comment by cantonios** [comment]
This results is a signed int overflow, which is undefined behavior.  Different compilers can choose to do different things, so your program output is unpredictable, which is what you're seeing here.
