### ISSUE TITLE
Very strange issue on estimator predict function

### ISSUE THREAD

**Issue by tthhmm** [tensorflow/tensorflow#5971]
Yesterday, I use the tf.contrib.learn.LinearClassifier to fit my data and predict the result. Every thing works fine. The predict function will return an numpy array of label.

Today I use the same LinearClassifier, it give me the warning like this:
WARNING:tensorflow:From /s/chopin/l/grad/tthhmm/miniconda3/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/linear.py:454 in evaluate.: calling BaseEstimator.evaluate (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
Instructions for updating:
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))

And the predict function just return <generator object _as_iterable at 0x7fb490fe1f68>. I have no idea how to use these function any more. I don't know where I can find SKCompat class from tensorflow also.

**Comment by poxvoculi** [comment]
The contrib code is not strongly supported.  I found this documentation page.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard3/tf.contrib.learn.Estimator.md

This forum is for bug reports.  Usage questions best asked on stackoverflow.

**Comment by qwertmax** [comment]
@poxvoculi link is not working anymore

**Comment by poxvoculi** [comment]
https://www.tensorflow.org/extend/estimators
