### ISSUE TITLE
Feature request: tf.gather which returns 0 on invalid indices

### ISSUE THREAD

**Issue by albertz** [tensorflow/tensorflow#59724]
This is about `tf.gather`. The wanted behavior could be added directly, or maybe via a new option, or maybe via a separate op.

Actually, on GPU (at least where I tested it), the behavior of `tf.gather` is already as I want it:

- It returns 0 for invalid indices.
- I think (not really verified): gradients for those 0s back to the `param` would go nowhere. (This is important though.)

On CPU, the current behavior is:

- An exception is raised.

I basically want the same behavior on CPU as we currently have it on GPU.

My current workaround is sth like:
```python
# need to extend param such that we can lead gradients to nowhere
zeros = tf.zeros([tf.shape(param)[i] if i != axis else 1 for i in range(param.ndim)], dtype=param.dtype)
param = tf.concat([param, zeros], axis=axis)
indices = tf.where(indices >= 0 and indices < tf.shape(param)[axis], indices, tf.shape(param)[axis] - 1)
gather = tf.gather(param, indices, axis=axis)
```

**Comment by tiruk007** [comment]
@SuryanarayanaY 
I was able to replicate the issue on Colab using TF v2.11 and tf-nightly-2.13.0.dev20230221. Please find the gist of [2.11](https://colab.research.google.com/gist/tiruk007/a657e62ad14d253d0cd2dd2775bb4f2b/untitled137.ipynb) and [tf.nightly](https://colab.research.google.com/gist/tiruk007/c9e2511f3ed3733828e8f2f200177d2c/untitled138.ipynb).

Thank you!

**Comment by albertz** [comment]
I know that this is the documented behavior.

But I request for a feature here where the CPU behavior is just the same as the GPU behavior. I have a use case where the GPU behavior is totally fine, and I don't want the CPU behavior to be inconsistent but rather behave exactly the same. The use case is probably also not too rare: I just happen to have a few indices which might be out-of-range, and I want to get 0s returned for them. Exactly like what the GPU behavior does. But when I run it on CPU, I want it to behave in the same way as the GPU.

**Comment by albertz** [comment]
Maybe you misunderstood what I wrote. I did not say that the behavior is unexpected or not documented. I know that it is exactly as expected. But I'm not really asking about `tf.gather` here at all.

I'm asking for a **separate** new `tf.gather_with_fallback` or whatever you want to name it. Or maybe a new **option** for `tf.gather`.

I don't want to change any existing behavior.

**Comment by SuryanarayanaY** [comment]
Hi @albertz ,

Could you please elaborate more ? You want the proposed API should work like same as tf.gather without raising error in validating indices.If Indices is large, is that not resource intensive on CPU ? What are the use cases for this feature and how community will get benefit from this ?

**Comment by albertz** [comment]
The proposed API should work exactly like `tf.gather` does currently on GPU. I.e. on invalid indices, it would not raise an error but just return 0 (or maybe some configurable tensor). Pseudo code (per element):
```python
if 0 <= index < dim:
  return x[index]
else:
  return fallback
```
In most of my (more dynamic) use of `tf.gather`, I actually need to have this behavior. Using an embedding where I can make sure the indices should be valid is actually more like the exception.

I don't see why this should be resource intensive.

**Comment by SuryanarayanaY** [comment]
Hi @albertz ,

I tried a demo example on a 2D tensor using your workaround code but getting error.Please refer the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/53a7d2cfa5c51567aff97b73934b1909/59724.ipynb) and confirm us the way you want to implement it and revert us with the gist. That provide me more context. Thanks!

**Comment by cantonios** [comment]
We won't do this internally - it's not highly requested, and there are potential work-arounds that use combinations of ops (or a single custom op if it is a performance bottleneck).
