### ISSUE TITLE
Building for mac catalyst

### ISSUE THREAD

**Issue by Nnevalti** [tensorflow/tensorflow#59723]
Hi I created a stackoverlfow post already: https://stackoverflow.com/questions/75473220/build-tensorflow-lite-for-mac-catalyst/75480973#75480973
But I thought I should have asked here first.

### System information
 
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac mini M1 Ventura 13.1
-   **TensorFlow installed from (source or binary)**: source
-   **TensorFlow version (use command below)**: 2.10.0
-   **Python version**: 3.10.8
-   **Bazel version (if compiling from source)**: 5.3.0
-   **GCC/Compiler version (if compiling from source)**: clang 14.0.0
-   **Exact command to reproduce**: bazel build --config=catalyst //tensorflow/lite:tensorflowlite.framework

### Describe the problem
So I'm trying to build tensorflow lite from source (github) with bazel for mac catalyst and I wanted to know if it is featured and if not if there is anyway I could build it.

### Source code / logs
For now without modification of any sort I have this error: `ERROR: Config value 'catalyst' is not defined in any .rc file`

**Comment by gaikwadrahul8** [comment]
Hi, @pjpratik 

Could you please look into this issue ? Thank you!

**Comment by pkgoogle** [comment]
Hi @Nnevalti, as far as I know we don't especially support mac catalyst, can you try doing whatever you want to do with normal iOS/macOS workflows and see if you run into any trouble? If so, we can identify more specifically what is unsupported and possibly make a feature request.

**Comment by Nnevalti** [comment]
Hello, so in the end I changed my code so I can use the MacOS library instead of catalyst. I did not succeed in compiling for Mac Catalyst, I lack knowledge for it !

**Comment by pkgoogle** [comment]
Hi @Nnevalti, can you show me how you tried compiling (i.e. what commands you used) and the error you get? Thanks.

**Comment by Nnevalti** [comment]
It's been a long time so I don't remember everything, all I know is that i tried using bazel but there is no rule for the catalyst build. I don't remember if I tried to build using Cmake (for catalyst at least), I just used it to build the regular MacOS M1 library.
Currently I'm still a beginner concerning compilation and cross compilation, so I'm not sure about what needs to be done for it to work.

**Comment by pkgoogle** [comment]
Hi @Nnevalti, fair enough, if you can replicate the issue, please let us know.

**Comment by Nnevalti** [comment]
It's not an issue, tensorflow just doesn't support catalyst build. I don't think it's an important feature, but I think it could help people in the future to look into it !

**Comment by pkgoogle** [comment]
Hi @Nnevalti,

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress [here](https://github.com/google-ai-edge/LiteRT/issues/274).

Let us know if you have any questions. Thanks.
