### ISSUE TITLE
Tensorflow 2.12.0rc0 pre-release does not provide GPU package

### ISSUE THREAD

**Issue by EnricoMi** [tensorflow/tensorflow#59720]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.12.0rc0

### Custom Code

No

### Current Behaviour?

```shell
PyPi lists the tensorflow==2.12.0rc0 package, but not the equivalent GPU package tensorflow-gpu==2.12.0rc0:
https://pypi.org/project/tensorflow/#history
https://pypi.org/project/tensorflow-gpu/#history

Is the GPU pre-release package going to be published ad PyPi as well?
```

### Standalone code to reproduce the issue

```shell
pip install tensorflow-gpu==2.12.0rc0
```

### Relevant log output

_No response_</details>

**Comment by nrwahl2** [comment]
From https://pypi.org/project/tensorflow-gpu/:

> tensorflow-gpu has been removed. Please install tensorflow instead. The tensorflow package supports GPU accelerated operations via Nvidia CUDA.

**Comment by EnricoMi** [comment]
Thanks for clarification.
