### ISSUE TITLE
Cropping1D cann't support negatitve integer parameter

### ISSUE THREAD

**Issue by CuiDonCai** [tensorflow/tensorflow#59735]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf 2.11

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8.10

### Current Behaviour?

```shell
tf.keras.layers.Cropping1D((-20,0))(out) report error, The 'cropping' argument must be a tuple of 2 interges. The really reson is keras.utils.conv_utils.normalize_tuple() update. 
And tf <= 2.6, the error is not exist. Is there a way to fix or keep away from this error?
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
input_shape = (2, 3, 2)
x = np.arange(np.prod(input_shape)).reshape(input_shape)
y = tf.keras.layers.Cropping1D(cropping=(-20,0))(x)
```
```


### Relevant log output

_No response_</details>

**Comment by CuiDonCai** [comment]
Standalone code `y = tf.keras.layers.Cropping1D(cropping=(-1,0))(x)` parameter should be -1

**Comment by CuiDonCai** [comment]
I install tf with `pip install tensorflow-cpu` (version is 2.11)

**Comment by tilakrayal** [comment]
@CuiDonCai,
The `cropping` argument must be a tuple of 2 integers and does not satisfy the requirement `>= 0`.  Also the argument cropping should be Int or tuple of int (length 2) How many units should be trimmed off at the beginning and end of the cropping dimension (axis 1). If a single int is provided, the same value will be used for both.
Case 1:
```
x = np.arange(np.prod(input_shape)).reshape(input_shape)
y = tf.keras.layers.Cropping1D(cropping=(-20, 0))(x)
```

Case 2:

```
x = np.arange(np.prod(input_shape)).reshape(input_shape)
y = tf.keras.layers.Cropping1D(cropping=(2, 0))(x)
```

Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/39a24c2f0d6ae6050631397cb80906f9/untitled975.ipynb) and also please take a look at this official [document](https://keras.io/api/layers/reshaping_layers/cropping1d/#cropping1d-class) and the PR for the [reference](https://github.com/keras-team/keras/pull/14970). Thank you!

**Comment by CuiDonCai** [comment]
First, `The cropping argument must be a tuple of 2 integers and does not satisfy the requirement >= 0`  is only true when `tensorflow` version is earlier than 2.6 (the reason is [here](https://github.com/keras-team/keras/blob/r2.11/keras/utils/conv_utils.py), and line 58). 
Second, `Kindly find the gist of it` [here](https://colab.research.google.com/gist/tilakrayal/39a24c2f0d6ae6050631397cb80906f9/untitled975.ipynb) , The result has an error. 
![Screenshot_select-area_20230221105410](https://user-images.githubusercontent.com/14941351/220235802-ea275898-06d0-49d3-beb6-467468363bbb.png)

finally, I give two examples.(I'm having problems with my server environment, so I chose tf versions 2.9.0-GPU and 1.15.0 for comparison. And I think it's also illustrative)
case 1:
![Screenshot_select-area_20230221104302](https://user-images.githubusercontent.com/14941351/220236478-cfbed7ec-7941-4b72-9985-61bca40671c5.png)

case 2:
![Screenshot_select-area_20230221103455](https://user-images.githubusercontent.com/14941351/220236531-90feffaf-8a41-4708-a991-1853e272f423.png)

**Comment by CuiDonCai** [comment]
So my question is how to use `Cropping1D()`  in tensorflow 2.11 consistent with the behavior in tensorflow 1.15. Or is there another way to do it in tensorflow 2.11. Thanks so much for response.

**Comment by tilakrayal** [comment]
@CuiDonCai,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 




Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by CuiDonCai** [comment]
ok. Thanks for your reply.
