### ISSUE TITLE
tensorflow-cpu-aws 2.12.0rc0 only has the Python 3.11 wheel

### ISSUE THREAD

**Issue by njzjz** [tensorflow/tensorflow#59731]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.12.0rc0

### Custom Code

No

### OS Platform and Distribution

aarch64

### Python version

3.10

### Current Behaviour?

```shell
See https://pypi.org/project/tensorflow-cpu-aws/2.12.0rc0/#files. There is only one file.
```

### Standalone code to reproduce the issue

```shell
Just go to https://pypi.org/project/tensorflow-cpu-aws/2.12.0rc0/#files.
Or reproduce using `pip` on aarch64 and Python 3.10:


pip install tensorflow==2.12.0rc0
```

### Relevant log output

```shell
Collecting tensorflow==2.12.0rc0
      Downloading tensorflow-2.12.0rc0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (2.0 kB)
    ERROR: Could not find a version that satisfies the requirement tensorflow-cpu-aws==2.12.0-rc0; platform_system == "Linux" and (platform_machine == "arm64" or platform_machine == "aarch64") (from tensorflow) (from versions: 2.9.1, 2.10.0rc0, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0)
    ERROR: No matching distribution found for tensorflow-cpu-aws==2.12.0-rc0; platform_system == "Linux" and (platform_machine == "arm64" or platform_machine == "aarch64")
```
</details>

**Comment by synandi** [comment]
@njzjz, thank you for reporting this issue. We are trying to investigate the issue and will update here soon. Thank you!

**Comment by synandi** [comment]
@njzjz, Apologies for the delay. Since 2.12 is not the stable version, it seems that the wheel files will be available in the next stable release. Kindly use the .whl files of the current stable version provided [here](https://pypi.org/project/tensorflow-cpu-aws/2.11.0/#files). Thank you!

**Comment by njzjz** [comment]
I've noticed that tensorflow-cpu-aws 2.12.0rc1 has resolved this problem.
