### ISSUE TITLE
Found Minor Error in Comment 

### ISSUE THREAD

**Issue by etolliver** [tensorflow/tensorflow#59748]
https://github.com/tensorflow/tensorflow/blob/b308c65397964d74b46a4015d15b6911ac710616/tensorflow/compiler/xla/tests/constants_test.cc#L85

F8 might need to be F16 in this comment

**Comment by pjpratik** [comment]
@etolliver Thanks for reporting the error. 

PR #59758 has been opened to fix the issue. The issue will be closed once it is merged.

Thank you.

**Comment by pjpratik** [comment]
Closing this as the PR #59758 is merged.
