### ISSUE TITLE
make -f error

### ISSUE THREAD

**Issue by singbys** [tensorflow/tensorflow#59749]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 22.04.2 LTS
- TensorFlow installation (pip package or built from source): built from source
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.11.0

### 2. Code
make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test 

### 3. Failure after conversion
make: tensorflow/lite/micro/tools/make/flatbuffers_download.sh: Permission denied                                       tensorflow/lite/micro/tools/make/Makefile:491: *** Something went wrong with the flatbuffers download: .  Stop.

**Comment by singbys** [comment]
New problem,when I execute this command：sudo su 
then make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test
The output result is：
--2023-02-21 14:23:26--  https://github.com/google/flatbuffers/archive/a66de58af9565586832c276fbb4251fc416bf07f.zip     Resolving github.com (github.com)... 20.205.243.166                                                                     Connecting to github.com (github.com)|20.205.243.166|:443... connected.                                                 HTTP request sent, awaiting response... 302 Found                                                                       Location: https://codeload.github.com/google/flatbuffers/zip/a66de58af9565586832c276fbb4251fc416bf07f [following]       --2023-02-21 14:23:26--  https://codeload.github.com/google/flatbuffers/zip/a66de58af9565586832c276fbb4251fc416bf07f    Resolving codeload.github.com (codeload.github.com)... 20.205.243.165                                                   Connecting to codeload.github.com (codeload.github.com)|20.205.243.165|:443... connected.                               HTTP request sent, awaiting response... 200 OK                                                                          Length: unspecified [application/zip]                                                                                   Saving to: ‘/tmp/tmp.0PxhI5l73F/a66de58af9565586832c276fbb4251fc416bf07f.zip’                                                                                                                                                                 /tmp/tmp.0PxhI5l73F/a66de58af     [                                        <=>       ]   2.74M  58.9KB/s    in 38s                                                                                                                              2023-02-21 14:24:07 (73.1 KB/s) - ‘/tmp/tmp.0PxhI5l73F/a66de58af9565586832c276fbb4251fc416bf07f.zip’ saved [2872508]                                                                                                                          tensorflow/lite/micro/tools/make/flatbuffers_download.sh: line 66: unzip: command not found                             tensorflow/lite/micro/tools/make/Makefile:491: *** Something went wrong with the flatbuffers download: .  Stop.

**Comment by synandi** [comment]
Hi @singbys,

As per the error it seems like you did not install the unzip package, please try installing it using the following command and let us know if the issue still persists. 
```
sudo apt-get install unzip
```

Thank you!

**Comment by singbys** [comment]
Thank you for your answer. New questions appear again：

> /bin/sh: 1: tensorflow/lite/micro/tools/make/download_and_extract.sh: Permission denied                                                                                                                                                      make: *** [tensorflow/lite/micro/tools/make/Makefile:634: tensorflow/lite/micro/tools/make/downloads/gemmlowp] Error 126

These files with the suffix sh always have such problems. I'm a beginner, and I don't know what's wrong

**Comment by synandi** [comment]
@singbys, could you please let us know the steps you have followed and also ensure that you have pip, zip packages installed. Thank you!

**Comment by singbys** [comment]
At first, I downloaded the zip of tensorflow lite,Extract it into the ubuntu system folder, and then executed：`make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test`
An error occurred：

> make: tensorflow/lite/micro/tools/make/flatbuffers_download.sh: Permission denied tensorflow/lite/micro/tools/make/Makefile:491: *** Something went wrong with the flatbuffers download: . Stop.

Then I execute the command：`chmod tensorflow/lite/micro/tools/make/flatbuffers_download.sh`

When running again, a similar error occurs：

> /bin/sh: 1: tensorflow/lite/micro/tools/make/download_and_extract.sh: Permission denied make: *** [tensorflow/lite/micro/tools/make/Makefile:634: tensorflow/lite/micro/tools/make/downloads/gemmlowp] Error 126

Now the mistake is：

> PermissionError: [Errno 13] Permission denied: 'gen/linux_x86_64_default/genfiles/tensorflow/lite/micro/examples/hello_world/hello_world_model_data.cc'                                                                                      tensorflow/lite/micro/examples/hello_world/Makefile.inc:38: *** Something went wrong: gen/linux_x86_64_default/genfiles/tensorflow/lite/micro/examples/hello_world/hello_world_model_data.cc.  Stop.

**Comment by singbys** [comment]
I did it according to the book TINY ML. What should I do if I start again?

**Comment by synandi** [comment]
I was successfully able to run ` make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test` without any error with the following commands.


1. mkdir tf_lite  (I have  first created a new folder and cloned the tflite-micro repo in it )

2. cd tf_lite

3. git clone https://github.com/tensorflow/tflite-micro.git

4. cd tflite-micro

 5. make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test

Please find the output below for your reference.
![image](https://user-images.githubusercontent.com/98147397/220333403-f92e2d61-5f17-4c67-8bba-e2ad7f664783.png)
Thank you!

**Comment by singbys** [comment]
The problem is solved. I ran the following command：
```
sudo make -f tensorflow/lite/micro/tools/make/Makefile clean_downloads
sudo make -f tensorflow/lite/micro/tools/make/Makefile clean
sudo make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test
```
Thank you again for your answer
