### ISSUE TITLE
tensorboard visualize embedding error

### ISSUE THREAD

**Issue by ylhsieh** [tensorflow/tensorflow#5974]
env: tensorflow v. 0.12.0 RC0

Following the [instructions](https://www.tensorflow.org/versions/master/how_tos/embedding_viz/index.html#tensorboard-embedding-visualization), I use tensorboard to visualize embeddings (without any metadata) and comes the following error:

> File "/home/morphe/miniconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/tensorboard/plugins/projector/plugin.py", line 139, in configs
    run_path_pairs.append(('.', self.logdir))
AttributeError: 'dict_items' object has no attribute 'append'

It seems to work if I attempt to change `tensorflow/tensorboard/plugins/projector/plugin.py`:
```
- run_path_pairs.append(('.', self.logdir))
+ run_path_pairs = [('.', self.logdir)]
```

Not sure if this is the right way to go. Is this a bug?

**Comment by dsmilkov** [comment]
Hi,

It turns out to be a python3 issue where dict.items() doesn't return an appendable list, like in python2.

We've fixed the issue internally, and the commit will show up in 1-2 days. Then a buils from master should work. We will also make sure to include this fix in 0.12 RC1.

Thank you!

**Comment by ksindi** [comment]
Just an FYI I get the same issue with 0.12 RC1 and Python 3. Python 2 works fine.

**Comment by dsmilkov** [comment]
Thanks for letting us know. The fix didn't make it in RC1, but I'll following up and making sure we get it in RC2  (and potentially in an updated RC1)

Thanks!
