### ISSUE TITLE
ld  linker error when handling python lib link

### ISSUE THREAD

**Issue by ysong2123** [tensorflow/tensorflow#59741]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tag: v2.11.0

### Custom Code

No

### OS Platform and Distribution

MacOS Ventura13

### Bazel version

5.3.0

### GCC/Compiler version

clang 14.0

### CUDA/cuDNN version

none

### GPU model and memory

none

### Current Behaviour?

```shell
ERROR: /Users/ysong2/Downloads/tensorflow/tensorflow/python/BUILD:358:27: Linking tensorflow/python/_pywrap_py_exception_registry.so failed: (Aborted): cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt/bin/tensorflow/python/_pywrap_py_exception_registry.so-2.params
ld: malformed trie, node past end file 'bazel-out/darwin-opt/bin/_solib_darwin_x86_64/libtensorflow_Spython_S_Upywrap_Utensorflow_Uinternal.so'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in child process '/usr/bin/xcrun'. 1
external/local_config_cc/cc_wrapper.sh: line 69: 23910 Abort trap: 6           "$(/usr/bin/dirname "$0")"/wrapped_clang "$@"
Target //tensorflow/tools/pip_package:build_pip_package failed to build.

I want to compile and build fully success.
```

### Standalone code to reproduce the issue

```shell
execting: "bazel build //tensorflow/tools/pip_package:build_pip_package" under tensorflow root directory then this erorr occurs.
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@ysong2123,
 Could you try building with the full Xcode? and also please make sure to set the **DEVELOPER_DIR** environment variable to the Xcode path before running the build, i.e, run something like `export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer`(path to Xcode) before running the bazel build command and try running the build again.

Also there is an issue opened for the similar error on v2.11 and v2.12 where the developer is involved.
https://github.com/tensorflow/tensorflow/issues/58368  Thank you!

**Comment by ysong2123** [comment]
i replaced another ld in another place, so we don't need take this, thanks
