### ISSUE TITLE
no such target '//tensorflow/tools/git:gen/spec.json': target 'gen/spec.json' not declared in package 

### ISSUE THREAD

**Issue by willduan** [tensorflow/tensorflow#5975]
when I run inceptionv3, tensorflow/examples/image_retraining, I encounter a problem，i go to the root directory and run:
`bazel build tensorflow/examples/image_retraining:retrain` or `bazel build -c opt --copt=-mavx tensorflow/examples/image_retraining:retrain`:
it appear the same error :

`
ERROR: /home/duan/tensorflow/tensorflow/core/BUILD:1121:1: no such target '//tensorflow/tools/git:gen/spec.json': target 'gen/spec.json' not declared in package 'tensorflow/tools/git' defined by /home/duan/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /home/duan/tensorflow/tensorflow/core/BUILD:1121:1: no such target '//tensorflow/tools/git:gen/head': target 'gen/head' not declared in package 'tensorflow/tools/git' defined by /home/duan/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /home/duan/tensorflow/tensorflow/core/BUILD:1121:1: no such target '//tensorflow/tools/git:gen/branch_ref': target 'gen/branch_ref' not declared in package 'tensorflow/tools/git' defined by /home/duan/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: Analysis of target '//tensorflow/examples/image_retraining:retrain' failed; build aborted.
INFO: Elapsed time: 4.179s
`
how to slove this problem?

and my content is：

`tensorflow-
           +-tensorflow
           +-third_party
           +-tools
           +-util
           +-......
           +-......
`
bazel version:
`
Build label: 0.4.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 2 17:54:14 2016 (1478109254)
Build timestamp: 1478109254
Build timestamp as int: 1478109254
`
my operating system is：
`Linux ubuntu 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`
and  my TensorFlow version is cpu version：
`python -c "import tensorflow; print(tensorflow.__version__)"
0.9.0
`

**Comment by poxvoculi** [comment]
Please see #4279

**Comment by qiaohaijun** [comment]
I met this too
