### ISSUE TITLE
Incorrect version of protobuf used in docker container

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#59774]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

git HEAD

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Mobile device

n/a

### Python version

3.9.13

### Bazel version

5.3.0

### GCC/Compiler version

10.3.0

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current Behaviour?

```shell
The version of protobuf specified in the docker container is out of date as it does not match the current requirements.
https://github.com/tensorflow/tensorflow/blob/20e0beaeebc1bd96c8eca40bed0e7b0d065d8e0b/tensorflow/tools/tf_sig_build_dockerfiles/devel.requirements.txt#L18 - this is now wrong
It should match this
https://github.com/tensorflow/tensorflow/blob/20e0beaeebc1bd96c8eca40bed0e7b0d065d8e0b/tensorflow/tools/pip_package/setup.py#L100
```

### Standalone code to reproduce the issue

```shell
Look at the links above
```

### Relevant log output

```shell
n/a
```
</details>

**Comment by elfringham** [comment]
I believe that this may be masking some unit test failures as well.
//tensorflow/python/kernel_tests/proto:decode_proto_op_test
//tensorflow/python/util/protobuf:protobuf_compare_test
//tensorflow/tools/api/tests:api_compatibility_test
These fail with protobuf > 3.20.3

**Comment by player-29** [comment]
Can you assign me this issue?I would love to contribute.

**Comment by synandi** [comment]
@elfringham, Thank you for reporting this issue. 
It has been fixed by  https://github.com/tensorflow/tensorflow/pull/59795 and hence the issue is closed. Thank you!
