### ISSUE TITLE
Tensorflow (pypi) doesn't support protobuf = ">3.20.0"

### ISSUE THREAD

**Issue by bcm-at-zama** [tensorflow/tensorflow#59777]
### System information

-   **Have I written custom code (as opposed to using a stock example script 
provided in TensorFlow)**: no
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 
 
```sw_vers
ProductName:	macOS
ProductVersion:	12.6.3
BuildVersion:	21G419
```

-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: MacBook
-   **TensorFlow installed from (source or binary)**: pip (binary)
-   **TensorFlow version (use command below)**: the most recent one, 
-   **Python version**: 3.8.15
-   **Bazel version (if compiling from source)**: N/A
-   **GCC/Compiler version (if compiling from source)**: N/A
-   **CUDA/cuDNN version**: N/A
-   **GPU model and memory**: N/A
-   **Exact command to reproduce**: see 'Describe the problem' section

### Describe the problem

I have a `pyproject.toml`. I want to upgrade its `onnx`, from 1.12.0 to 1.13.0. When I run `poetry lock`, it tells me

```
Because concrete-ml depends on onnx (1.13.0) which depends on protobuf (>=3.20.2,<4), protobuf is required.
So, because concrete-ml depends on protobuf (3.19.6), version solving failed.
```

so I upgrade `protobuf`, and now, it tells me

```
Because tensorflow (2.11.0) depends on protobuf (>=3.9.2,<3.20)
 and concrete-ml depends on protobuf (>3.20.0), tensorflow is forbidden.
So, because concrete-ml depends on tensorflow (2.11.0), version solving failed.
```

which I understand as the most recent version of tf (2.11.0) currently doesn't support a recent version of protobuf.

This is for me a problem since for now, when I run `pip-audit`, it tells me

```
Found 3 known vulnerabilities in 3 packages
Name   Version ID                  Fix Versions
------ ------- ------------------- ------------
mpmath 1.2.1   PYSEC-2021-427
onnx   1.12.0  GHSA-ffxj-547x-5j7c 1.13.0
py     1.11.0  PYSEC-2022-42969
```

so I can't upgrade `onnx`, and in my understanding, it is related to tf

--

Thanks for your hard work, guys! What you do for the ML community is amazing.

**Comment by MarkDaoust** [comment]
Hi, yes, this is a known issue, tf-team's been working on it for a long time. 

They're working on the 2.12 release which allows newer versions of protobuf:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py#L100

try `pip install -U tensorflow==2.12.0rc0`

**Comment by bcm-at-zama** [comment]
Thanks @MarkDaoust

**Comment by bcm-at-zama** [comment]
Arg, it still fails:

`Because tensorflow (2.12.0rc0) depends on numpy (>=1.22,<1.24)`

ie, tf doesn't want the new numpy.

**Comment by MarkDaoust** [comment]
Darn.  And the other packages won't work at np 1.23?
