### ISSUE TITLE
ideal development mode discussion

### ISSUE THREAD

**Issue by ysong2123** [tensorflow/tensorflow#59770]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tag: v2.11.0

### Custom Code

No

### OS Platform and Distribution

MacOS Ventura13

### Python version

3.8

### Bazel version

5.3.0

### GCC/Compiler version

clang 14.0

### CUDA/cuDNN version

none

### GPU model and memory

none

### Current Behaviour?

```shell
Currently, we just have Mac as our daily work laptop. But we want to deep dive into tensorflow source code and maybe doing some customized changes, then compile/build and deploy into test/production environment for model training.  Meanwhile, as we knew, tensorflow is a typical cross-platform end2end tool, how can we make sure the whole develop/delivery pipeline runs smoothly?   Do we have any best practice?  Thank you.
```

### Standalone code to reproduce the issue

```shell
None regarding this topic.
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@ysong2123,

- Train and export a TensorFlow model.
- Manage model versioning with TensorFlow Serving ServerCore.
- Configure batching using SavedModelBundleSourceAdapterConfig.
- Serve request with TensorFlow Serving ServerCore.
- Run and test the service.

Also please take a look at these official documents for the [reference](https://www.tensorflow.org/tfx/tutorials/serving/rest_simple) where the ML deployment and also TFX is an end-to-end platform for deploying production ML pipelines for the [reference](https://www.tensorflow.org/tfx).
https://www.tensorflow.org/tfx/serving/serving_basic
https://www.tensorflow.org/tfx/serving/serving_advanced
