### ISSUE TITLE
Broken link in "A Tool Developer's Guide..." for graph_run_run2.pbtxt

### ISSUE THREAD

**Issue by evancofer** [tensorflow/tensorflow#5978]
The link for `graph_run_run2.pbtxt` is broken in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/tool_developers/index.md

**Comment by poxvoculi** [comment]
thanks for the PR.

**Comment by DSLituiev** [comment]
the same for the graph_metrics.py link there

**Comment by gunan** [comment]
graph_metrics.py is being fixed by #5917
