### ISSUE TITLE
Error When Trying to Get Value for bert_model in "Classify text with BERT" tutorial

### ISSUE THREAD

**Issue by hilal-g** [tensorflow/tensorflow#59781]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.4.4

### Custom Code

Yes

### Current Behaviour?

```shell
I am trying to run the "Classify text with BERT" tutorial using Jupyter Notebook on a remote server. When I tried to implement 'bert_model = hub.KerasLayer(tfhub_handle_encoder)', it never returned a result and it is still executing with the asterik (*) next to the cell. 

Is this supposed to happen, and is it normal for that line to take a long time to execute?
```

### Standalone code to reproduce the issue

```shell
https://www.tensorflow.org/text/tutorials/classify_text_with_bert

The code is this line:
'bert_model = hub.KerasLayer(tfhub_handle_encoder)'
```

### Relevant log output

_No response_</details>

**Comment by AbdelAzizMohamedMousa** [comment]
I'm sorry to hear that you're encountering an error when trying to get the value for bert_model in the "Classify text with BERT" tutorial. Here are some possible solutions:

Make sure you have installed the necessary packages. The tutorial requires tensorflow, tensorflow-text, and tensorflow-hub. You can install them using pip: 
`pip install tensorflow tensorflow-text tensorflow-hub
`
Check that you're using the correct BERT model. The tutorial uses the bert_en_uncased_L-12_H-768_A-12 model, which is a smaller and faster version of BERT. Make sure you've downloaded and unzipped this model to the correct directory. You can download it using the following command:
`!wget https://storage.googleapis.com/bert_models/2018_10_18/uncased_L-12_H-768_A-12.zip
!unzip uncased_L-12_H-768_A-12.zip
`
Verify that the path to the BERT model is correct. In the tutorial, the path is set to ./bert_en_uncased_L-12_H-768_A-12/. Double-check that this path is correct and that you're not missing any files.

Try clearing the TensorFlow session and reloading the BERT model. You can do this using the following code:
`import tensorflow as tf
import tensorflow_hub as hub

tf.keras.backend.clear_session()
bert_layer = hub.KerasLayer("./bert_en_uncased_L-12_H-768_A-12")
`
If none of the above solutions work, try restarting your Python kernel and rerunning the code from the beginning of the tutorial.
I hope one of these solutions helps you resolve the error. Let me know if you have any further questions or concerns!

**Comment by hilal-g** [comment]
I successfully completed the tutorial, and the code worked. It just took longer than expected. Unfortunately, I did not record how long it took for the line of code to run. 

I am closing this issue because I no longer have any questions.
