### ISSUE TITLE
Tensorflow grad

### ISSUE THREAD

**Issue by panhu** [tensorflow/tensorflow#59790]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.X

### Custom Code

Yes

### Current Behaviour?

```shell
Hi:
If i want to Slimming Network
```

### Standalone code to reproduce the issue

```shell
I want to ask how I can get the gradient value of each iteration in the model training process.
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
Closing as stale. Please reopen if you'd like to work on this further.

Thanks !

**Comment by panhu** [comment]
Hi:
If have some examples or methods about Channel pruning of model in TF.
