### ISSUE TITLE
SVG folder of tensorboard not found

### ISSUE THREAD

**Issue by passiweinberger** [tensorflow/tensorflow#598]
if you run the mnist_fully_connected tutorial and inspect it with tensorboard afterwards, you find the following: 

the graph-viz is calling this url for a image
http://localhost:6006/lib/svg/summary-icon.svg

<img width="1277" alt="screen shot 2015-12-23 at 15 20 24" src="https://cloud.githubusercontent.com/assets/9993908/11978047/bc880e52-a988-11e5-8478-c08ba0a65d43.png">

which is not there...

**Comment by mrry** [comment]
This file was removed in commit f7918e1dcd5b0c1f8114f488fc35a63a81e94535, so it's possible that you have a version conflict. (It sounds like you have an old version of some of the TensorBoard assets.) Can you try upgrading to TensorFlow 0.6.0 and see if this solves the problem?

**Comment by passiweinberger** [comment]
i built it from source and it happened... checked your @mrry suggestion and it fixed it.. 

just a quick reminder to keep everything in sync (at least try to) in the source as well :)
