### ISSUE TITLE
No wheels for tf-nightly Macos arm64

### ISSUE THREAD

**Issue by eapolinario** [tensorflow/tensorflow#59801]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

tf-nightly 2.13.0.dev20230224

### Custom Code

No

### OS Platform and Distribution

Macos M1

### Python version

3.9

### Current Behaviour?

```shell
I'm not able to install tf-nightly on Macs running arm.
```

### Standalone code to reproduce the issue

```shell
> pip install tf-nightly==2.13.0.dev20230224
ERROR: Could not find a version that satisfies the requirement tf-nightly==2.13.0.dev20230224 (from versions: none)
ERROR: No matching distribution found for tf-nightly==2.13.0.dev20230224
```

### Relevant log output

_No response_</details>

**Comment by pjpratik** [comment]
@eapolinario Thanks for reporting the issue.

I have tried it on Mac M1 with arm64 and I was successfully able to install tf-nightly==2.13.0.dev20230224. Please refer to the below screenshots.

<img width="566" alt="Screenshot 2023-02-27 at 2 36 51 PM" src="https://user-images.githubusercontent.com/118897289/221521838-f7f0a63c-b955-4707-b908-b95121fbb5d5.png">

<img width="564" alt="Screenshot 2023-02-27 at 2 37 34 PM" src="https://user-images.githubusercontent.com/118897289/221521925-f229bb7e-fb3a-4bc9-a266-a344fa961d5c.png">

Can you please check for different nightly versions and let us know if the issue persists?

**Comment by eapolinario** [comment]
@pjpratik , the screenshot above is poitning to the x86_64 wheel, right?

**Comment by pjpratik** [comment]
@eapolinario AFAIK, arm64 don't have nightly wheels. I did check with 2.12 nightly and 2.11 as well but the nightly was pointing to x86_64 wheels. The [documentation](https://www.tensorflow.org/install/pip#package_location) for stable release for CPU on MacOS also has x86_64 wheels as well.

Have you tried with different nightly versions and observed the same behaviour? 

Thanks.

**Comment by eapolinario** [comment]
@pjpratik , yeah, I observe the same behavior. Can you clarify why arm64 wheels are not being built? I tried to search for a [github issue](https://github.com/tensorflow/tensorflow/issues) but couldn't find any.

**Comment by pjpratik** [comment]
@eapolinario Please find the similar issue [#47782](https://github.com/tensorflow/tensorflow/issues/47782). As per this [comment](https://github.com/tensorflow/tensorflow/issues/47782#issuecomment-799601893), the official pip packages are built for x86_64. For ARM, we have to build from source.

Please refer to [this](https://www.tensorflow.org/install/source) for source installation on MacOS.

Thanks.

**Comment by pjpratik** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks!
