### ISSUE TITLE
Tensorflow profiling overhead

### ISSUE THREAD

**Issue by rizar** [tensorflow/tensorflow#5981]
The profiling mechanism (which by the way really deserves to be documented...) can add a prohibitive large computational overhead to the execution. Specifically, my training script runs 10 times slower with profiling. I stripped it down to a small self-contained [example](https://gist.github.com/rizar/f4556741c2c79c4adf4f47c6ed1cefd7) and the slowdown became just 3x, but I think this is bad enough.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

https://github.com/tensorflow/tensorflow/issues/1824

### Environment info
Operating System:

Debian 8.6
CUDA 8.0
CUDNN 5.1.3

Tensorflow was installed by running

`pip install --user https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0rc1-cp27-none-linux_x86_64.whl`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

https://gist.github.com/rizar/f4556741c2c79c4adf4f47c6ed1cefd7

**Comment by prb12** [comment]
From reading your code, there are two likely reasons for this, one fairly obvious, the other less so:
1) Your benchmark measures the overheads of retrieving a large trace protobuf via the `session.run` API.  This includes the cost of serializing trace data into a protobuf and copying back to Python.
2) `BasicLSTMCell` includes quite a large number of tiny elementwise ops, plus one large(ish) MatMul.  Tracing overheads are typically order 1us per op at execution time.  Most of the tiny ops in an LSTM cell execute in less time than this on a GPU.

When I run on my desktop with a K40, I get 1.3s without profiling and 4.0s with profiling.  So basically the same ratio you reported.

If you examine the timeline generated from the computation I expect the time spent `computing` is not much different to your baseline measurement....

I added code to write out the profile and generate a chrome trace viewer timeline:  
```
print(len(run_metadata.SerializeToString()))
# Create the Timeline object, and write it to a json
tl = timeline.Timeline(run_metadata.step_stats)
ctf = tl.generate_chrome_trace_format()
with open('timeline.json', 'w') as f:
  f.write(ctf)
```
When you look at the captured profiler data you can see that the computation still executes in approx 1.3s.  This is basically identical to the time without profiling (which includes feeding input tensors from Python)
![image](https://cloud.githubusercontent.com/assets/11547801/20807274/178c91f4-b7b3-11e6-9c65-7fdf77dda742.png)

So tracing isn't actually slowing down execution by very much.  Retrieving the trace seems to be expensive in this case.

The size of the `run_metadata` is about 5MB.... larger than it _could_ be, but I agree that it seems ridiculous that fetching back the extra 5MB takes over 2 seconds.  It's probably worth running under a CPU profiler to work out what's going on here!

**Comment by prb12** [comment]
Interesting - there is a big perf difference between our internal build and the open source install:

When I run the internal build, the step time with tracing (and lots of extra logging) is 1.47s.
```
I1201 13:50:53.102052   24865 tf_session_helper.cc:402] TF_Run_wrapper_helper
I1201 13:50:53.106980   24865 direct_session.cc:489] Run
I1201 13:50:53.364928   24865 direct_session.cc:499] Run done
I1201 13:50:53.364971   24865 direct_session.cc:513] Got trace
I1201 13:50:53.364982   24865 direct_session.cc:527] Got outputs
I1201 13:50:53.365004   24865 tf_session_helper.cc:521] To NumPy
I1201 13:50:53.365013   24865 tf_session_helper.cc:540] TF_Run_wrapper_helper done
I1201 13:50:53.365126   24865 profiling-5981.py:50] Init done.
I1201 13:50:53.365229   24865 profiling-5981.py:62] sess.run
I1201 13:50:53.365682   24865 tf_session_helper.cc:402] TF_Run_wrapper_helper
I1201 13:50:53.397088   24865 dso_loader.cc:233] successfully opened CUDA library /google/src/cloud/pbar/triage/google3/third_party/gpus/cuda_7_0/extras/CUPTI/lib64/libcupti.so.7.0.28
I1201 13:50:53.467417   24865 direct_session.cc:489] Run
I1201 13:50:54.774907   24865 direct_session.cc:499] Run done
I1201 13:50:54.781975   24865 direct_session.cc:513] Got trace
I1201 13:50:54.782018   24865 direct_session.cc:527] Got outputs
I1201 13:50:54.816643   24865 tf_session_helper.cc:521] To NumPy
I1201 13:50:54.920562   24865 tf_session_helper.cc:540] TF_Run_wrapper_helper done
I1201 13:50:54.950649   24865 profiling-5981.py:67] sess.run done
I1201 13:50:54.950703   24865 profiling-5981.py:68] 1.58546686172
I1201 13:50:54.950723   24865 profiling-5981.py:62] sess.run
I1201 13:50:54.951195   24865 tf_session_helper.cc:402] TF_Run_wrapper_helper
I1201 13:50:54.951274   24865 direct_session.cc:489] Run
I1201 13:50:56.217795   24865 direct_session.cc:499] Run done
I1201 13:50:56.224791   24865 direct_session.cc:513] Got trace
I1201 13:50:56.224850   24865 direct_session.cc:527] Got outputs
I1201 13:50:56.263171   24865 tf_session_helper.cc:521] To NumPy
I1201 13:50:56.385349   24865 tf_session_helper.cc:540] TF_Run_wrapper_helper done
I1201 13:50:56.422490   24865 profiling-5981.py:67] sess.run done
I1201 13:50:56.422549   24865 profiling-5981.py:68] 1.47181797028
```

One of the first differences btw internal an external that I usually try to rule out is the malloc implementation.  (We use TCMalloc, and standard Python is compiled against the regular libc heap).

I tried using TCMalloc as follows:
```
LD_PRELOAD=/usr/lib/libtcmalloc_minimal.so.4 python profiling-5981.py
```
But still see the same step time... perhaps 100ms faster.

I couldn't see anything obvious running under the CPU profiler either .... will keep looking, since this is a little suspicious.

**Comment by prb12** [comment]
This is most likely a protobuf issue... can you please check the output of the following:
```
$ python
>>> import google.protobuf.internal.api_implementation as ai
>>> ai.Type()
```
If this prints `'python'` (as opposed to `'cpp'`) then you probably need to install the fast protobuf library as described here: 
https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#protobuf-library-related-issues

**Comment by prb12** [comment]
@rizar After I do the following, my step time with profling comes down to 1.45s:
```
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.0.0-cp27-none-linux_x86_64.whl
```

Please reopen if this doesn't fix your problem.
