### ISSUE TITLE
DEPRECIATION NOTICE

### ISSUE THREAD

**Issue by rustisthebestlanguage** [tensorflow/tensorflow#59811]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

Any

### Custom Code

No

### Current Behaviour?

```shell
WARNING! C++ is deprecated, use Rust instead
```

### Standalone code to reproduce the issue

```shell
..
```

### Relevant log output

_No response_</details>

**Comment by TheSaintDiratof** [comment]
guy is a misunderstood genius
