### ISSUE TITLE
Failing to run hexagon delegates on android

### ISSUE THREAD

**Issue by EnariSaarBolt** [tensorflow/tensorflow#59817]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Windows 10

### Mobile device

QCS6125

### Current Behaviour?

```shell
Problem with hexagon delegates, the hexagon libs from hexagon delegates page are set into arm64-v8a folder.

>CPU architecture: 8

>adb shell getprop ro.board.platform
trinket
>adb shell getprop ro.product.device
trinket
```

### Standalone code to reproduce the issue

```shell
implementation 'org.tensorflow:tensorflow-lite:2.10.0'
implementation 'org.tensorflow:tensorflow-lite-hexagon:2.10.0'

Running tensorflow example from Quickstart for Android.
```

### Relevant log output

```shell
/tflite: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
```
</details>

**Comment by synandi** [comment]
Hi @EnariSaarBolt 
Please provide the version of `libhexagon_nn_skel` and kindly refer to this similar issue [here](https://github.com/tensorflow/tensorflow/issues/39539).   Also refer to the note below mentioned in [TensorFlow Lite Hexagon delegate](https://www.tensorflow.org/lite/android/delegates/hexagon) and let us know if it helps.
 > Note: You must use the hexagon_nn libraries with the compatible version of interface library. Interface library is part of the AAR and fetched by bazel through the [config](https://github.com/tensorflow/tensorflow/blob/master/third_party/hexagon/workspace.bzl) The version in the bazel config is the version you should use.

Thank you!

**Comment by EnariSaarBolt** [comment]
The version of libhexagon_nn_skel is v1.20.0.1.

**Comment by EnariSaarBolt** [comment]
> Hi @EnariSaarBolt Please provide the version of `libhexagon_nn_skel` and kindly refer to this similar issue [here](https://github.com/tensorflow/tensorflow/issues/39539). Also refer to the note below mentioned in [TensorFlow Lite Hexagon delegate](https://www.tensorflow.org/lite/android/delegates/hexagon) and let us know if it helps.
> 
> > Note: You must use the hexagon_nn libraries with the compatible version of interface library. Interface library is part of the AAR and fetched by bazel through the [config](https://github.com/tensorflow/tensorflow/blob/master/third_party/hexagon/workspace.bzl) The version in the bazel config is the version you should use.
> 
> Thank you!

Do i understand correctly that the [config](https://github.com/tensorflow/tensorflow/blob/master/third_party/hexagon/workspace.bzl) has to match with the nn_skel version. So if i pick tensorflow version v2.5 i should be compatible with interface and nn_hexagon?

**Comment by pjpratik** [comment]
Hi @EnariSaarBolt 

As the [config](https://github.com/tensorflow/tensorflow/blob/master/third_party/hexagon/workspace.bzl) is updated with v1.20.0.9, can you try with lib_interface v1.20.0.1 from [here](https://storage.googleapis.com/mirror.tensorflow.org/storage.cloud.google.com/download.tensorflow.org/tflite/hexagon_nn_headers_v1.20.0.1.tgz) and push the  libhexagon_interface.so to match with your architecture by following this [instructions](https://www.tensorflow.org/lite/android/delegates/hexagon#add_the_shared_library_to_your_app).

Thanks!

**Comment by EnariSaarBolt** [comment]
`I/com.example.tfex: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1154: remote_handle_open: Successfully opened handle 0x68c897b0 for adsp_current_process on domain 3
E/com.example.tfex: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1078: Error 0x80000414: remote_handle_invoke failed for handle 0x68c897b0, method 4 on domain 3 (sc 0x4010000)
I/com.example.tfex: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/mod_table.c:677: open_mod_table_open_from_static: reverse module apps_std opened with handle 0xa493e088 (idx 0)
W/om.example.tfex: type=1400 audit(0.0:73): avc: denied { read } for name="adsprpc-smd-secure" dev="tmpfs" ino=21501 scontext=u:r:untrusted_app:s0:c143,c256,c512,c768 tcontext=u:object_r:xdsp_device:s0 tclass=chr_file permissive=0 app=com.example.tfex
W/com.example.tfex: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:750: Warning: apps_std_fopen_with_env failed with 0xd for libhexagon_nn_skel_v66.so (Permission denied)
E/com.example.tfex: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1143: Error 0x80000406: remote_handle_open_domain: dynamic loading failed for file:///libhexagon_nn_skel_v66.so?hexagon_nn_domains_skel_handle_invoke&_modver=1.0&_dom=cdsp on domain 3 (dlerror cannot open libhexagon_nn_skel_v66.so)
E/com.example.tfex: vendor/qcom/proprietary/commonsys-intf/adsprpc/src/fastrpc_apps_user.c:1177: Error 0x80000406: remote_handle64_open failed for file:///libhexagon_nn_skel_v66.so?hexagon_nn_domains_skel_handle_invoke&_modver=1.0&_dom=cdsp
W/tflite: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
I/tflite: Hexagon Delegate is not supported.
I/BoltImage: No hexagon
D/AndroidRuntime: Shutting down VM`

tensorflow version is 2.11.0, hexagon version is 2.11.0 and hexagon nn skel is v20.0.1

hexagon_skel files are in jniLibs/arm64-v8a folder
