### ISSUE TITLE
Tensorflow Import error

### ISSUE THREAD

**Issue by Rury04** [tensorflow/tensorflow#59814]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.10

### Custom Code

Yes

### Python version

3.9

### Current Behaviour?

```shell
I cannot import the tensorflow package in my jupyter notebook. I have checked the installations in conda and pip, but everything seems to work. So whenever i try to import it i get the following error:
"ImportError: Traceback (most recent call last):
  File "C:\Users\Rury\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed."
Is it a problem of the environment or a problem with package itself?
I am starting now to study DL so i would appreciate a lot a quick response. Thank you
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@Rury04,
I suspect that you are trying to install the tensorflow on the windows machine. Then there is a high possibility for getting the above error because of the below reasons.
There are at least 3 possible scenarios:

- You need to install the MSVC 2019 redistributable
- Your CPU does not support AVX2 instructions
- Your CPU/Python is on 32 bits
- There is a library that is in a different location/not installed on your system that cannot be loaded.

Any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.

Apparently, your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:

Try Google Colab to use TensorFlow.
The easiest way to use TF will be to switch to google colab. You get pre-installed latest stable TF version. Also you can use pip install to install any other preferred TF version.
It has an added advantage since you can you easily switch to different hardware accelerators
(cpu, gpu, tpu) as per the task.
All you need is a good internet connection and you are all set.
or else try to build TF from sources by changing CPU optimization flags.  Please try to follow the instructions to install the tensorflow. [Reference](https://www.tensorflow.org/install/source_windows). Thank you!

**Comment by Rury04** [comment]
I am really grateful to your response. As you told me i checked the
processor and it turns out to be "Intel(R) Celeron(R) N4000 CPU @ 1.10GHz
1.10 GHz". Since it's not my own PC i didnt checked out the specs. Besides
im installing the latest MSVC version: 2022, is it a problem? Although i
think tensorflow is correctly installed, because i can import it and use it
normally when i am using another python interpreter such as Python 3.9, the
only issue is that i cannot import it in Jupyter. There is no problem with
the environment so it's kinda weird. I also checked several tutorials for
this kind of problem but they were not helpful. In conclusion I will try to
change to Google colab instead. Thank you again for your comprehension, i
really appreciate it.
Have a nice day

Il giorno lun 27 feb 2023 alle ore 11:59 tilakrayal <
***@***.***> ha scritto:

**Comment by tilakrayal** [comment]
@Rury04,
TensorFlow is tested against Visual Studio 2019. So please try to install the MSVC 2019 redistributable. 
Install the Visual C++ build tools 2019. This comes with Visual Studio 2019 but can be installed separately:

- Please try to go to the [Visual Studio downloads](https://visualstudio.microsoft.com/downloads/),
- Select Redistributables and Build Tools,

Download and install:
- Microsoft Visual C++ 2019 Redistributable
- Microsoft Build Tools 2019

Kindly please take a look at the official doc [link](https://www.tensorflow.org/install/source_windows#install_visual_c_build_tools_2019) for the reference. Thank you!

**Comment by Rury04** [comment]
Good morning
I apologize for my delay but I had exams these days so I couldn't give you
a proper response. Still I feel so bad about it.
Anyway, I tried what you suggested to me and I came up with one question. I
looked for the visual studio and I found out that I have a lot of older
versions of Visual studio C++ Redistributable, do i need them or should I
just ignore them and try installing the version you asked me to. I
appreciate a lot your help and wish you an excellent day
Kind regards

Il Mer 1 Mar 2023, 10:16 tilakrayal ***@***.***> ha scritto:

**Comment by tilakrayal** [comment]
@Rury04,
Yeah, please try to uninstall the older versions and install with the mentioned requirements & try to follow the instructions mentioned on the tensorflow official doc which helps to install in the smoother way.
https://www.tensorflow.org/install/source_windows

- Please try to go to the [Visual Studio downloads](https://visualstudio.microsoft.com/downloads/),
- Select Redistributables and Build Tools,

Download and install:

- Microsoft Visual C++ 2019 Redistributable
- Microsoft Build Tools 2019

Kindly please take a look at the official doc [link](https://www.tensorflow.org/install/source_windows#install_visual_c_build_tools_2019) for the reference. Thank you!

**Comment by Rury04** [comment]
Hi, I have tried the solutions you suggested me to do but apparently its
not working. The version Microsoft Visual C++ 2019 Redistributable is
already installed, same thing is for the build tools. I have a question:
I've checked my specs and it turns out that my cpu is a Intel Celeron and
it seems not compatible, should I just install the gpu version with cuda
and cudnn or should i continue on Colab? I tried the second option and i
cant open tensorboard.
I really appreciate yout support and hope you a good day.

Il giorno mar 7 mar 2023 alle ore 08:22 tilakrayal ***@***.***>
ha scritto:

**Comment by Rury04** [comment]
I am sorry for the misunderstanding but the issue raises up whenever I try
to import the package, because it is properly installed (I verified it
using another Interpreter). By the way I've installed it from Anaconda
prompt like usually install the other packages. The Error log file is right
below and it is the same I posted In the GitHub page. Thank you as always
for your concerns and hope u a great day

Il Gio 16 Mar 2023, 14:41 tilakrayal ***@***.***> ha scritto:

**Comment by tilakrayal** [comment]
@Rury04,
I try to install the **tensorflow v2.10** on the Windows environment by following the steps which are available on the official document and it was installed and importing the tensorflow was also successful.
https://www.tensorflow.org/install/pip

I request you, to follow the instructions which are mentioned in the document and try to create the new virtual environment.
Screen shot for the reference.

![Screenshot 2023-03-23 3 24 06 PM](https://user-images.githubusercontent.com/81610181/227167233-cc705150-535b-4b72-b7de-2c284c363ac6.png)

Also make sure you are not trying to install tensorflow v2.11.  `TensorFlow 2.10` was the last TensorFlow release that supported **GPU** on native-Windows. Starting with TensorFlow 2.11, you will need to install [TensorFlow in WSL2](https://tensorflow.org/install/pip#windows-%5Bwsl2%5D), or **install tensorflow-cpu** and, optionally, try the [TensorFlow-DirectML-Plugin](https://github.com/microsoft/tensorflow-directml-plugin#tensorflow-directml-plugin-)
