### ISSUE TITLE
Tensorflow lite build error for Aarch64 

### ISSUE THREAD

**Issue by pjindal91** [tensorflow/tensorflow#59824]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

Tensorflow lite master branch

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04.6 LTS

### Mobile device

Nvidia Jetson nano

### Python version

3.8

### Current Behaviour?

```shell
Trying to build tensorflow lite wheels using the following command 
`
PYTHON=python3 tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh native
`

While trying to build, getting compilation errors of the likes:


In file included from /home/piyush/tensorflow_src/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/cmake_build/xnnpack/src/amalgam/neonfp16arith.c:8::
/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:30805:1: error: inlining failed in call to always_inline ‘vaddq_f16’: target specific option mismatch
 vaddq_f16 (float16x8_t __a, float16x8_t __b)
 ^~~~~~~~~
/home/piyush/tensorflow_src/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/cmake_build/xnnpack/src/amalgam/neonfp16arith.c:277:27: note: called from here
         const float16x8_t vsum2345 = vaddq_f16(vsum23, vsum45);
```
```


### Standalone code to reproduce the issue

```shell
Build using above command on Aarch64. I am using Nvidia Jetson Nano with Ubuntu 18.04.6 LTS
```

### Relevant log output

```shell
In file included from /home/piyush/tensorflow_src/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/cmake_build/xnnpack/src/amalgam/neonfp16arith.c:8::
/usr/lib/gcc/aarch64-linux-gnu/7/include/arm_neon.h:30805:1: error: inlining failed in call to always_inline ‘vaddq_f16’: target specific option mismatch
 vaddq_f16 (float16x8_t __a, float16x8_t __b)
 ^~~~~~~~~
/home/piyush/tensorflow_src/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/cmake_build/xnnpack/src/amalgam/neonfp16arith.c:120:27: note: called from here
         const float16x8_t vsum = vaddq_f16(vsum2345, vsum01678);
```
</details>

**Comment by pjindal91** [comment]
Hello @tilakrayal @pjpratik any ideas? Thanks in advance.

**Comment by pjpratik** [comment]
Hi @pjindal91 Thanks for reporting the issue.

Sorry for the delayed response.

You can try to build with target architecture `PYTHON=python3 tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh aarch64` in your case.

I was able to build for aarch64 using tool chain as given in [documentation](https://www.tensorflow.org/lite/guide/build_cmake_arm#build_for_aarch64_arm64) successfully on Ubuntu 20.04. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/af0d6f62408877b78a36879ed3979336/59824.ipynb).

Thanks.

**Comment by pjindal91** [comment]
Hi @pjpratik thanks for the response. I think the issue might be specific to platform and the ubuntu/glibc versions i am using. Would it be possible for you to try to natively built on aarch64 with Ubuntu 18.04.6 LTS and glibc=2.27?

**Comment by pjindal91** [comment]
FYI @pjpratik in case it helps i was able to build v2.4.0 successfully. So not sure if v2.5.0 is pulling some buggy lib or the above setup i have(Ubuntu 18.04.6 LTS and glibc=2.27) is not compatible with it.

**Comment by pjpratik** [comment]
Hi @pjindal91 sorry for the delayed response

I have tried to built natively on aarch64 with Ubuntu 18.04.6 LTS and glibc=2.27 with v2.5 and master branch as well and the attempt was successful. Please find the screenshots below

For v2.5

![image](https://user-images.githubusercontent.com/118897289/225010812-b302f055-37ab-4a97-8a86-201df5c0a724.png)

For master

![image](https://user-images.githubusercontent.com/118897289/225010939-ae41d856-df08-481c-81f8-df3286428955.png)

Thanks.
