### ISSUE TITLE
Encounter segment error when trying to deploy tflite model

### ISSUE THREAD

**Issue by HJL8055** [tensorflow/tensorflow#59846]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
   Ubuntu 20.04.1
- TensorFlow installation (pip package or built from source):
   Pip package
- TensorFlow library (version, if pip package or github SHA, if built from source):
   2.11.0

### 2. Code

Provide code to help us reproduce your issues using one of the following options:
#### Option B: Paste your code here or provide a link to a custom end-to-end colab

`TF_PATH = "/data/lxp/mmpose/tf_model" `
`TFLITE_PATH = "/data/lxp/mmpose/mmpose.tflite"`
`converter = tf.lite.TFLiteConverter.from_saved_model(TF_PATH)`
`converter.optimizations = [tf.lite.Optimize.DEFAULT]`
`converter.representative_dataset = representative_data_gen`
`converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]`
`converter.target_spec.supported_types = [tf.int8] `
`converter.inference_input_type = tf.int8`
`converter.inference_input_type = tf.int8  # or tf.uint8`
`converter.inference_output_type = tf.int8  # or tf.uint8 `
`tf_lite_model = converter.convert()`
`with open(TFLITE_PATH, 'wb') as f:`
`f.write(tf_lite_model)`

### 3. Failure after conversion
If the conversion is successful, but I encounter segment error when I try to deploy tflite model.
Then, I found that error appeared while "AllocateTensors()"->"graph_.PrepareSubgraphs()"->"registration->prepare(context_, node)"
There, I printed the node id and registration->builtin_code.
![image](https://user-images.githubusercontent.com/66299911/222093485-4853f014-ba33-4241-9094-45edf074ba75.png)
After using netron, we can know the node 24 correspond to FullyConnected.
![H2T_QR%WE@$0$8OXO9J7~UT](https://user-images.githubusercontent.com/66299911/222094472-74de7d81-4851-49b3-85b8-2d90b16689a7.png)
![image](https://user-images.githubusercontent.com/66299911/222093548-626469a4-4fe7-4ae0-ba82-85cd63ebc616.png)
Also, go into the funtion "prepare(context_, node)" , the error is raised by the following code.
`TFLITE_DCHECK(filter->params.zero_point == 0);`
This code restricts the zeropoints of the weight in fully_connected-layer should always be zero.
![image](https://user-images.githubusercontent.com/66299911/222094095-1a8b2f69-2d29-4f91-bfa9-27bac9329559.png)

But mine is -10. What needs mentioning is that  the weight in this fully_connected-layer is poduced by the upper transpose-layer.

I wonder why my zeropoint is not zero while I use tensorflow-Post-training quantization-Full integer quantization to get my quantization_weight and it's hard for me to find the configure to restricts the zeropoints.

**Comment by pjpratik** [comment]
Hi @HJL8055. Thanks for reporting the issue.

Sorry for the delayed response.

As per the [documentation](https://www.tensorflow.org/lite/performance/quantization_spec#symmetric_vs_asymmetric),  the zero point of the weights in fully-connected layers is enforced to be zero to avoid the runtime cost of multiplying the zero point of the weight with the activation value. 

Can you please provide  the model and steps you have followed in order to reproduce the issue and help troubleshooting process.

Thanks.

**Comment by pjpratik** [comment]
Closing as stale. Please reopen if you'd like to work on this further. Thanks!
