### ISSUE TITLE
Inconsistent Log Level in cuda_driver InternalInit()

### ISSUE THREAD

**Issue by josemalope** [tensorflow/tensorflow#59849]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11

### Custom Code

No

### Current Behaviour?

```shell
The following Warning is logged as ERROR:

W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)

cuda_driver.cc 
InternalInit()
LOG(ERROR) << "failed call to cuInit: " << ToString(res); (line 266)

In this case, tensorflow is running CPU inferences. Therefore, the warning is expected, but not al ERROR level
```

### Standalone code to reproduce the issue

```shell
cuda_driver.cc 
InternalInit()
LOG(ERROR) << "failed call to cuInit: " << ToString(res); (line 266)

NO GPU
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@josemalope 

Could you please try to install TensorFlow 2.11 as per the [tested build configurations](https://www.tensorflow.org/install/source#gpu)  and also try to update the GPU drivers. 

Please refer to the similar [issue_1](https://github.com/tensorflow/tensorflow/issues/53341) & [issue_2](https://github.com/tensorflow/tensorflow/issues/41937) for reference and let us know if it helps.

Thank you !

**Comment by josemalope** [comment]
Hi @tiruk007,

The message is expected since we are using CPU only (we already switched to tensorflow-cpu).

However, I created the ticket to point out the inconsistency between the warning message: 
W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
and the level at which it is logged: ERROR

Regards,
Jose

**Comment by tiruk007** [comment]
@josemalope 
Sorry for the late reply, tensorflow and tensorflow-gpu have been in the same package since TensorFlow 2.1([REF](https://pypi.org/project/tensorflow-gpu/)). Could you please use `pip install tensorflow-cpu` for cpu inferences to avoid unwanted warning like  `W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)`. 

Thank you !
