### ISSUE TITLE
one tflite model padding layer , the data is error(flatbuffers)

### ISSUE THREAD

**Issue by mengran1234** [tensorflow/tensorflow#59845]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.10 or 2.11

### Custom Code

Yes

### OS Platform and Distribution

android

### Mobile device

android

### Python version

3.7

### Current Behaviour?

```shell
A bug happened!
I call tflite::FlatBufferModel::BuildFromFile(model_name.c_str());
then on first padding layer I print the pad data (paddings)，and find the data is 0 0 0 0 8 0 8 0 ，
but using netron open it correct data is  [
    [
        0,
        0
    ],
    [
        8,
        8
    ],
    [
        8,
        8
    ],
    [
        0,
        0
    ]
]
```

### Standalone code to reproduce the issue

```shell
this pad layer   Connect three outputs later,it is one Transpose and two StridedSlice layers.
I guess it is flatbuffer bug
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@mengran1234,
Thanks for opening the issue. In order to expedite the trouble-shooting process, could you please provide a minimal code snippet you are trying to execute. Thank you!
