### ISSUE TITLE
None gradient from GRU

### ISSUE THREAD

**Issue by petrbel** [tensorflow/tensorflow#5985]
Hello everybody,

**Introduction:**
I am trying to reproduce the work of Szegedy et al: [Intriguing properties of neural networks](https://arxiv.org/abs/1312.6199) and Dezfooli et al: [Universal adversarial perturbations](https://arxiv.org/abs/1610.08401). What they do, briefly, is that they take the gradient `g` of the network with respect to the input image `x`, then slightly modify the input image `x` "against" the obtained gradient, i.e. `x-0.001g`. The modified images are consequently considered as another network input, hence new gradients `g'` might be computed and obtained. The result gradients are manually set to the average of those two set obtains gradients, i.e. `g/2 + g'/2`. I hope I explained that clearly.

I successfully implemented it for images in TF 0.10 (working on 0.12RC as well). Now I want to do something similar with recurrent networks (sentiment analysis task). So I have a input sequence of tokens (numbers), a variable `embeddings` which is used by `tf.nn.embedding_lookup`. After the lookup, the sequence of proper embeddings is traversed by GRU (dynamically). It's last state is considered as the representation of the sequence. Then a MLP with a single hidden layer and ReLU activation is applied, resulting in 2 neurons representing the positive and negative logits respectively. The loss is traditional categorical cross entropy.

**Bug**
Similarly to the papers mentioned above, I obtain gradients of the embedding, and modify the current embeddings slightly "against" the obtained gradient. Than I compute the new loss and _new gradients (here is the problem!)_ and update the network by their mean.

The problem is that the returned _new gradients_ are all `None`s. I originally worked with TF 0.10, however, I got an error explaining that second order derivatives are impossible to obtain from scan. I upgraded to recently released TF 0.12RC which doesn't throw this error but returns `None`s instead.

**Related Issues and SOs**
#783 is somewhat similar, but not the same. [This question](http://stackoverflow.com/questions/36874522/tensorflow-gradients) deals with very the same problem  but the solution isn't sufficient as replacing the `None` value with zero is really worthless in my case since I need to modify the variable against the gradient.

**Minimal Not-Working Example**
I am sorry the code is so long. It is partially caused by the fact that the problem is non-trivial and requires few lines and partially by the amount of comments I tried to write in order to make the code more readable. All platform/version information is stored at beginning of the file.

The `main()` function constructs two `SimpleSentiment`s as the models that are trained. Each one is trained for few epochs and batches. First instance is without the adversarial, hence we perform no trick regarding modifying the gradients (for a sanity check). The second uses the complicated `if` branch in the constructor and obtains `None`s as described above.

I believe this is a bug and not my mistake, however, it can't be ruled out as I am not as experienced with TF as I'd like to be.

```python
# #!/usr/bin/env python3

# python 3.5 (anaconda)
# TF 0.12 RC from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.0rc0-cp35-cp35m-linux_x86_64.whl
# $ python -c "import tensorflow; print(tensorflow.__version__)"
#  0.12.0-rc0

# OS: RedHat 7.2
# CPU version only, no GPU, no CUDA, no CUDNN

import numpy as np
import tensorflow as tf
from tensorflow.python.ops.rnn_cell import GRUCell


BATCH = 5  # batch size
MAX_LEN = 10  # max length of the sequence
MLP_HIDDEN_DIM = 128  # number of hidden neurons in the MLP
EMBEDDING_DIM = 300  # embedding dimension
VOCAB_SIZE = 8  # vocabulary size

THREADS = 4  # number of threads to be used
STD=0.001  # standard deviation of ariable initializers


class SimpleSentiment:
    def __init__(self, adversarial=False, device='/cpu:0'):

        self.embeddings = tf.get_variable('word_embeddings',
                                          initializer=tf.random_uniform([VOCAB_SIZE, EMBEDDING_DIM], -1.0, 1.0))

        with tf.variable_scope('sentiment') as scope:
            with tf.device(device):
                # Inputs
                self.text = tf.placeholder(tf.int32, [BATCH, MAX_LEN])
                self.text_len = tf.placeholder(tf.int32, [BATCH])
                self.sentiment = tf.placeholder(tf.int32, [BATCH])

                # Normal loss
                loss_normal = self._loss(self.text, self.text_len, self.sentiment)

                # Define the optimizer
                # Note: I've tried multiple of optimizers and none helped
                optimizer = tf.train.AdamOptimizer(learning_rate=0.0005)

                if adversarial:  # Define adversarial loss
                    # Let's acces already defined variables
                    scope.reuse_variables()

                    # Gradients of all variable (according to normal loss)
                    gradients = optimizer.compute_gradients(loss_normal)
                    print(len(gradients), gradients)

                    # gradients of the embeddings
                    emb_gradient = optimizer.compute_gradients(loss_normal, [self.embeddings])[0][0]

                    # this how much we want to shift the embeddings, i.e. going "against" the gradient
                    delta = 0.001*tf.sign(emb_gradient)

                    # let's compute the loss once again but this time we add the delta to the embeddings
                    loss_adversarial = self._loss(self.text, self.text_len, self.sentiment, delta)

                    # new gradient of the whole computational graph
                    adversarial_gradients = optimizer.compute_gradients(loss_adversarial)
                    print(len(adversarial_gradients), adversarial_gradients)  # everything is None!

                    # Now we compute an average of old and new gradients
                    new_gradients = [((g + ag)/2, vg) for ((g, vg), (ag, avg)) in zip(gradients, adversarial_gradients)]

                    # and apply them
                    self.training = optimizer.apply_gradients(new_gradients)

                    # Btw this doesn't work either
                    # self.training = optimizer.apply_gradients(adversarial_gradients)

                    self.loss_final = (loss_normal + loss_adversarial) / 2

                else:  # Normal loss
                    # simply minimize according to the gradients
                    self.loss_final = loss_normal
                    self.training = optimizer.minimize(loss_normal)

                # Create the session
                self.session = tf.Session(config=tf.ConfigProto(inter_op_parallelism_threads=THREADS,
                                                                intra_op_parallelism_threads=THREADS,
                                                                allow_soft_placement=True))

                # init everything (still deprecated way)
                self.session.run(tf.initialize_all_variables())

    def _loss(self, text, text_len, sentiment, emb_delta=0):
        # use embedding
        # note that emb_delta is zero as long as adversarial=False
        # if adversarial=False then each embedding is shifted by appropriate emb_delta
        text = tf.nn.embedding_lookup(self.embeddings + emb_delta, text)

        # run gru
        gru_cell = GRUCell(MLP_HIDDEN_DIM)
        outputs, state = tf.nn.dynamic_rnn(cell=gru_cell,
                                           inputs=text,
                                           sequence_length=text_len,
                                           dtype=tf.float32)

        # define MLP
        W1 = tf.get_variable(name='MLP_W1',
                             shape=[state.get_shape()[1], MLP_HIDDEN_DIM],
                             initializer=tf.random_normal_initializer(mean=0, stddev=STD))
        W2 = tf.get_variable(name='MLP_W2',
                             shape=[MLP_HIDDEN_DIM, 2],
                             initializer=tf.random_normal_initializer(mean=0, stddev=STD))
        h1 = tf.get_variable(name='MLP_h1',
                             shape=[MLP_HIDDEN_DIM],
                             initializer=tf.random_normal_initializer(mean=0, stddev=STD))
        h2 = tf.get_variable(name='MLP_h2',
                             shape=[2],
                             initializer=tf.random_normal_initializer(mean=0, stddev=STD))

        # apply MLP of the last GRU state
        after_first_layer = tf.nn.relu(tf.matmul(state, W1) + h1)
        logits = tf.matmul(after_first_layer, W2) + h2

        # compute loss via categorial cross entropy
        loss = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(logits, sentiment))
        return loss


def main():
    for adversarial in [False, True]:
        print('\n=================================')
        if adversarial:
            print('Using the adversarial loss')
        else:
            print('Using the standard loss')

        net = SimpleSentiment(adversarial=adversarial)

        for epoch in range(5):
            print('Epoch {}'.format(epoch))

            for batch in range(3):
                _, loss_final = net.session.run([net.training, net.loss_final],
                                                {net.text: np.array([[3, 1, 1, 2, 1, 0, 0, 0, 0, 0],
                                                                     [3, 4, 1, 2, 1, 4, 4, 0, 0, 0],
                                                                     [1, 1, 1, 2, 0, 0, 0, 0, 0, 0],
                                                                     [3, 3, 3, 2, 1, 7, 0, 0, 0, 0],
                                                                     [7, 1, 5, 2, 4, 2, 2, 2, 1, 7]], dtype='int32'),
                                                 net.text_len: np.array([5, 7, 4, 6, 10], dtype='int32'),
                                                 net.sentiment: np.array([0, 0, 1, 1, 0], dtype='int32')})

                print('\tBatch {}: {}'.format(batch, loss_final))

if __name__ == '__main__':
    main()
```

Thanks for help
Petr

**Comment by poxvoculi** [comment]
@rmlarsen @vrv Could this be related to a known missing 2nd order derivative?

**Comment by vladfi1** [comment]
I'm am also getting None gradients when trying to compute second order derivatives of a GRU.

**Comment by vladfi1** [comment]
If I revert to tensorflow 0.10 I get the error message:

    TypeError: Second-order gradient for while loops not supported.

The error disappears if I switch from using `tf.nn.dynamic_rnn` to `tf.nn.rnn`, but this appears to slow things down quite a bit.

**Comment by petrbel** [comment]
@vladfi1 Does it really work for you with `tf.nn.rnn`? I updated my code so that is uses `tf.nn.rnn`, i.e. used `tf.split` on the input tensor in order to support it. However, the gradients are still `None`s and I get a really weird error `AttributeError: 'NoneType' object has no attribute 'pred'`.

I attach the code [here in a gist](https://gist.github.com/petrbel/6c72395490aa90d68d3d68fb6e5747a4 ) so that it doesn't mess with the original post. I still use TF 0.12. but I suppose it is back-compatible.

Thanks for help.

**Comment by vladfi1** [comment]
@petrbel It runs fine for me with tensorflow 0.10.0.

**Comment by rmlarsen** [comment]
I'm not sure, since this uses dynamic_rnn, I'm assigning to @ebrevdo .

**Comment by petrbel** [comment]
@vladfi1 It is as you said, it runs fine with 0.10. However I still think it is an issue as it doesn't work 0.12.
Petr

**Comment by ebrevdo** [comment]
tf.while_loop definitely doesn't support second derivatives.  You should have received an error instead of None.  Which seems like a bug. If you only needed to use the first derivative values as values and didn't mean to differentiate them, wrap them in tf.stop_grdients to avoid trying to calculate their derivatives in your second gradients calculation.

**Comment by vladfi1** [comment]
@ebrevdo Will this change in the future? If while_loop has a first derivative, then that first derivative itself should probably itself be a while_loop (this is probably where I'm mistaken), in which case there's no reason not to take the derivative again.

**Comment by ebrevdo** [comment]
That is the general idea, but the implementation is complex enough, for
many reasons, that we do not plan to implement a second derivative.

**Comment by vrv** [comment]
@ebrevdo: you mean in its current formulation, right?  That is, if we redesigned how while_loop was implemented, it could be done more easily?

**Comment by ebrevdo** [comment]
I don't know.  The current implementation requires a lot of special casing
and careful graph introspection to properly identify which tensors should
stay in the stack for gradient purposes, and for e.g. handling of external
and within body stop gradient calls.  There is also a lot of special
handling in the runtime.  Compound that with nested while loop handling and
possibly needing to modify TensorArray to support second+ derivatives...

At the very least, first we should move while loop and gradients to the c++
api, and decide whether we want full Jacobian support, then we can consider
this.

**Comment by ankeshanand** [comment]
Is it possible to compute second order derivatives with `tf.nn.rnn` if I switch to 0.10, or does it silently suppress any errors? cc @petrbel @vladfi1 @ebrevdo

**Comment by ebrevdo** [comment]
regarding second or derivatives, i think we fixed bugs from 0.10 to 1.0 and
in the nightlies; so definitely use that instead.

keep in mind the following ops don't have second derivatives:

tf.nn.sparse_softmax_cross_entropy_with_logits
tf.nn.softmax_cross_entropy_with_logits

so if you're using those for your loss, you'll have trouble.  implement
them yourself using tensorflow primitives and you'll be able to use second
derivatives.

**Comment by ankeshanand** [comment]
Slightly confused here, you mean I should use 1.0? I am already using that and it doesn't allow me to compute second order derivatives for RNNs

**Comment by vrv** [comment]
Do you have some example code and the error you get?

**Comment by ankeshanand** [comment]
The relevant portion is this:
`gradients = tf.gradients(discriminator(x_dash, reuse=True)[0], [x_dash])[0]`

The `discriminator` here is a simple LSTM implemented using `tf.nn.dynamic_rnn`.

The error I get is: `TypeError: Second-order gradient for while loops not supported.`

I am trying to implement the gradient penalty term from this paper: https://arxiv.org/abs/1704.00028 (Improved training of WassGANs)

**Comment by ebrevdo** [comment]
Ah.

That's right, tf.while_loop (used by dynamic_rnn) does not support second
derivatives; and there are no plans for support in the near or mid-term
future.  I'm afraid if you want this, you'll have to use a static RNN.

**Comment by vrv** [comment]
@asimshankar @skye I do know there's been work to move While loops into C API already, but I don't know how gradient support within it works, if at all yet.  Just an FYI of something that would be great to have, though I don't know the scope of the work required.

**Comment by ankeshanand** [comment]
@ebrevdo `static_rnn` doesn't work either, gives me nan losses.

**Comment by vladfi1** [comment]
@ankeshanand I think it might work in 0.10/0.11, but I don't remember for sure. I just ended up writing my own unroller:

```python
def rnn(cell, inputs, initial_state):
  inputs = tf.unpack(inputs, axis=1)
  outputs = []
  state = initial_state
  for input_ in inputs:
    output, state = cell(input_, state)
    outputs.append(output)
  outputs = tf.pack(outputs, axis=1)
  return outputs, state
```

This assumes the time axis is 1. In more recent tensorflow versions, `[un]pack` has been renamed to `[un]stack`.

**Comment by ebrevdo** [comment]
@ankeshanand <https://github.com/ankeshanand> are you passing the
sequence_length= argument to the static rnn call?

**Comment by ankeshanand** [comment]
@ebrevdo I didn't, I realized from the docs that passing `sequence_length` would again result in dynamic computation. 

Even the authors of the paper Improved WassGan faced this issue it seems (https://www.reddit.com/r/MachineLearning/comments/63dfun/r170400028_improved_training_of_wasserstein_gans/dftqi72/)

**Comment by xcyan** [comment]
Any updates on this thread?

**Comment by ivallesp** [comment]
Any update? Is there already any way of computing second order gradients for dynamic_rnn modules?

**Comment by chandramouli-sastry** [comment]
I'm not aware if the second derivative of while_loop has been added yet. However, the static RNN solution isn't convenient for experimentation when there are longer time-steps [I needed about 1k steps and graph creation takes more than 5 minutes!]. So, I wrote code to compute both the derivatives and activations as part of the SAME FORWARD while loop using some Dynamic Programming and Math! However, I believe it would have been much more efficient if this had been native.  

Posting the code (adequately commented) for reuse for anyone else who lands on this page with the same problem. Note that the following code is only for computing the (jacobian) equivalent of tf.gradients(hidden_activations,input_vectors). It is easy to derive the end-to-end gradients using the same idea that is implemented. 

I have tested this with TF 1.7.0. 

```
def get_outputs_and_gradients(rnn_cell,steps,embedding_size,hidden_size,inputs):
    """
    :param rnn_cell: Assumes GRU_CELL.
    :param steps: Integer
    :param embedding_size: Integer
    :param hidden_size: Integer
    :param inputs: The inputs to the RNN of shape (time_steps,embedding_size). (Can be extended to batch computations, if needed.)
    :return:
    """
    time = tf.constant(0)
    hidden_states = tf.constant(value=np.zeros(shape=(steps+1,hidden_size)),dtype=tf.float64)
    hidden_input_jacob = tf.constant(value=np.zeros(shape=(steps,embedding_size,hidden_size)),dtype=tf.float64)
    input_grad = tf.constant(value=np.zeros(shape=(steps,embedding_size,hidden_size)),dtype=tf.float64)

    def _body(time,hidden_states,hidden_input_jacob,input_grad,ins):
        """
        :param time: Current time step of RNN
        :param hidden_states: The array containing all the hidden state activations.
        :param hidden_input_jacob: The array containing the jacobian between activations of the latest time step and all other time steps
        :param input_grad: The gradients accummulated so far.
        :param ins: The inputs.
        :return:
        """
        inputs = ins[time:time+1] # 1 x embedding_size
        prev_state = hidden_states[time:time+1] # 1 x hidden_size
        state = prev_state

        # forward
        gate_inputs = tf.matmul(
            tf.concat([inputs, state], 1), rnn_cell._gate_kernel)
        gate_inputs = tf.nn.bias_add(gate_inputs, rnn_cell._gate_bias)

        value = tf.sigmoid(gate_inputs)
        r, u = tf.split(value=value, num_or_size_splits=2, axis=1)

        r_state = r * state

        candidate = tf.matmul(
            tf.concat([inputs, r_state], 1), rnn_cell._candidate_kernel)
        candidate = tf.nn.bias_add(candidate, rnn_cell._candidate_bias)

        c = rnn_cell._activation(candidate)
        new_h = u * state + (1 - u) * c

        # Jacobian Computations
        start = tf.eye(hidden_size, dtype=tf.float64)
        du = tf.multiply(start, (state))
        dstate = tf.multiply(start, (u))
        du = du - tf.multiply(start, (c))
        dc = tf.multiply(start, (1 - u))
        dcandidate = (dc * tf.gradients(c, candidate))[0]
        dinputs_rstate = tf.matmul(dcandidate, tf.transpose(rnn_cell._candidate_kernel))
        dinputs = dinputs_rstate[:, :embedding_size]
        drstate = dinputs_rstate[:, embedding_size:]
        dstate = dstate + r * drstate
        dr = state * drstate
        dru = tf.concat([dr, du], axis=1)
        dgateinputs = dru * (value * (1 - value))
        dinputs_state = tf.matmul(dgateinputs, tf.transpose(rnn_cell._gate_kernel))
        dinputs = dinputs + dinputs_state[:, :embedding_size]
        dstate = dstate + dinputs_state[:, embedding_size:]

        mask = tf.equal(tf.range(start=0, limit=steps+1), time+1)
        hidden_states = tf.where(mask, (hidden_states + new_h) , hidden_states)

        # jacobs
        hid_hid_jac = dstate  # hidden_size x hidden_size
        hid_inp_jac = tf.transpose(dinputs) # embedding_size x hidden_size

        mask = tf.equal(tf.range(start=0, limit=steps), time)
        hidden_input_jacob = ndmatmul(hidden_input_jacob,tf.transpose(hid_hid_jac))
        hidden_input_jacob = tf.where(mask, (hidden_input_jacob + hid_inp_jac), hidden_input_jacob)
        input_grad = input_grad + hidden_input_jacob

        return [time+1,hidden_states,hidden_input_jacob,input_grad,ins]

    outs = tf.while_loop(cond=lambda time, *_: time<steps,
                  body=_body,
                  loop_vars=[time, #time. Useless after iteration
                             hidden_states, # time_steps,embedding_size
                             hidden_input_jacob,# time_steps,embedding_size,hidden_size. This is useless after the iteration.
                             input_grad, # time_steps,embedding_size,hidden_size. This contains the jacobians. tf.reduce_sum(outs[3],axis=[2]) == tf.gradients(self.hidden_states,inputs)
                             inputs # time_steps,embedding_size. Unchanged during iteration.
                             ],
                  parallel_iterations=10)
    
    return outs[1],outs[3]

def ndmatmul(mat3d,mat2d):
    return tf.einsum("abc,cd->abd",mat3d,mat2d)
```

**Comment by asimshankar** [comment]
(I'll defer to @ebrevdo for an update on that, but would expressing the model with [eager execution](https://www.tensorflow.org/programmers_guide/eager) be an option that works for you? That may be more natural and will work with higher order gradients. See the [instructional notebooks](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/eager/python/examples/notebooks)).

**Comment by pythonanonuser** [comment]
@ebrevdo @asimshankar Has any progress been made on taking 2nd order gradients in dynamic_rnn ?

**Comment by ebrevdo** [comment]
There is work in progress to implement while loops using different
primitives. These should allow 2nd order gradients.  Unfortunately there's
no estimate when this will be ready.

**Comment by pythonanonuser** [comment]
@ebrevdo Is there a branch or PR you can point me to? Perhaps I can help contribute

**Comment by pythonanonuser** [comment]
@skye Thanks have emailed you!

**Comment by niudong1001** [comment]
Any updates? It seems `dynamic_rnn` still can't work with second-derivatives.

**Comment by skye** [comment]
You can try enabling the new while_loop implementation, which supports second derivatives, by setting the environment variable `TF_ENABLE_CONTROL_FLOW_V2=1` (make sure this is set before importing tf). It's still a work in progress, so please file issues for any problems you find! Please see the [design doc](https://github.com/tensorflow/community/blob/master/rfcs/20180821-differentiable-functional-while.md) for more information on the new implementation.
