### ISSUE TITLE
GPU:0 is joining a group with incompatible device typeCPU

### ISSUE THREAD

**Issue by dengpanyin** [tensorflow/tensorflow#59888]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf2.9

### Custom Code

Yes

### Current Behaviour?

```shell
tensorflow.python.framework.errors_impl.InternalError: Collective ops is aborted by: Device /job:worker/replica:0/task:0/device:GPU:0 is joining a group with incompatible device typeCPU (group_key=3)
```

### Standalone code to reproduce the issue

```shell
Observed the above errors twice a week. Can you explain what's the root cause and how to fix it?
```

### Relevant log output

_No response_</details>

**Comment by pjpratik** [comment]
@dengpanyin Thanks for reporting the issue.

In order to expedite the troubleshooting process, please share a stand alone code/snippet to reproduce the issue.

Thanks.

**Comment by dengpanyin** [comment]
@pjpratik  stand alone code is unavailable since this issue is not able to reproduce every time. We still want to understand the root cause since multi-models have the same issue.

**Comment by pjpratik** [comment]
@dengpanyin Could you please provide more details to debug the issue. It will help us to investigate the issue further.

 Thanks.

**Comment by apmanikandan** [comment]
@dengpanyin can you explicitly specify the device type ,so that all the devices in the collective group have the same device type
