### ISSUE TITLE
Outdated example

### ISSUE THREAD

**Issue by TheHellTower** [tensorflow/tensorflow#59900]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf 2.6.0

### Custom Code

No

### OS Platform and Distribution

Windows 10 (Build 19045.2673)

### Python version

3.11

### CUDA/cuDNN version

11.0.2

### Current Behaviour?

[label image example](https://github.com/tensorflow/tensorflow/blob/v2.10.0/tensorflow/examples/label_image/main.cc) is outdated

### Standalone code to reproduce the issue

```shell
Not applicable.
```

### Relevant log output

```shell
Not applicable.
```
</details>

**Comment by tilakrayal** [comment]
@TheHellTower,
Thank you for reporting the doc issue. Could you please feel free to submit a PR for the requested change or share the code of the example where the requested change is to be made. Thank you!

**Comment by TheHellTower** [comment]
> @TheHellTower, Thank you for reporting the doc issue. Could you please feel free to submit a PR for the requested change or share the code of the example where the requested change is to be made. Thank you!

Hello, I don't have the updated code I opened a issue for a problem I got [here](https://github.com/tensorflow/tensorflow/issues/59905), it was just to know if it will be updated at some point or if I need to wait my problem to be solved to write myself a code and open a PR ?

**Comment by TheHellTower** [comment]
Well this one is not important I will focus on #59905.

**Comment by TheHellTower** [comment]
It didn't solve this issue @pjpratik, if you read betterI pointed out the [C example](https://github.com/tensorflow/tensorflow/blob/v2.10.0/tensorflow/examples/label_image/main.cc)

**Comment by pjpratik** [comment]
Hi @TheHellTower, sorry for the inconvenience. 

We are working on the C example as well. 

Please feel to raise a PR if you have the updated code implementation available.

**Comment by pjpratik** [comment]
Hi @TheHellTower 

We have tested the [example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/label_image) on TF docker with 2.13 version and observed the example gives the expected output. Please find the logs below

```
tf-docker /tf/tensorflow > wget https://storage.googleapis.com/download.tensorflow.org/models/inception_v3_2016_08_28_frozen.pb.tar.gz 
--2023-03-29 06:36:03--  https://storage.googleapis.com/download.tensorflow.org/models/inception_v3_2016_08_28_frozen.pb.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 172.253.63.128, 142.250.31.128, 142.251.111.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.253.63.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 88668554 (85M) [application/gzip]
Saving to: 'inception_v3_2016_08_28_frozen.pb.tar.gz'
 
inception_v3_2016_08_28_frozen.pb.tar.g 100%[=============================================================================>]  84.56M  99.5MB/s    in 0.8s    
 
2023-03-29 06:36:04 (99.5 MB/s) - 'inception_v3_2016_08_28_frozen.pb.tar.gz' saved [88668554/88668554]
 
tf-docker /tf/tensorflow > tar -xvpzf inception_v3_2016_08_28_frozen.pb.tar.gz -C tensorflow/examples/label_image/data --numeric-owner
inception_v3_2016_08_28_frozen.pb
imagenet_slim_labels.txt
tf-docker /tf/tensorflow > ls tensorflow/examples/label_image/data                
grace_hopper.jpg  imagenet_slim_labels.txt  inception_v3_2016_08_28_frozen.pb
tf-docker /tf/tensorflow > bazel-bin/tensorflow/examples/label_image/label_image
2023-03-29 06:48:48.658334: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-29 06:48:51.529578: I tensorflow/examples/label_image/main.cc:252] military uniform (653): 0.834306
2023-03-29 06:48:51.529646: I tensorflow/examples/label_image/main.cc:252] mortarboard (668): 0.0218695
2023-03-29 06:48:51.529663: I tensorflow/examples/label_image/main.cc:252] academic gown (401): 0.0103581
2023-03-29 06:48:51.529676: I tensorflow/examples/label_image/main.cc:252] pickelhaube (716): 0.00800816
2023-03-29 06:48:51.529694: I tensorflow/examples/label_image/main.cc:252] bulletproof vest (466): 0.00535087
tf-docker /tf > python -c "import tensorflow as tf; print(tf.__version__)"
2023-03-29 05:27:29.371380: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2.13.0
```

Can you please let us know if there is any help we can provide on running the example?

Thanks.

**Comment by TheHellTower** [comment]
> Hi @TheHellTower
> 
> We have tested the [example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/label_image) on TF docker with 2.13 version and observed the example gives the expected output. Please find the logs below
> 
> ```
> tf-docker /tf/tensorflow > wget https://storage.googleapis.com/download.tensorflow.org/models/inception_v3_2016_08_28_frozen.pb.tar.gz 
> --2023-03-29 06:36:03--  https://storage.googleapis.com/download.tensorflow.org/models/inception_v3_2016_08_28_frozen.pb.tar.gz
> Resolving storage.googleapis.com (storage.googleapis.com)... 172.253.63.128, 142.250.31.128, 142.251.111.128, ...
> Connecting to storage.googleapis.com (storage.googleapis.com)|172.253.63.128|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 88668554 (85M) [application/gzip]
> Saving to: 'inception_v3_2016_08_28_frozen.pb.tar.gz'
>  
> inception_v3_2016_08_28_frozen.pb.tar.g 100%[=============================================================================>]  84.56M  99.5MB/s    in 0.8s    
>  
> 2023-03-29 06:36:04 (99.5 MB/s) - 'inception_v3_2016_08_28_frozen.pb.tar.gz' saved [88668554/88668554]
>  
> tf-docker /tf/tensorflow > tar -xvpzf inception_v3_2016_08_28_frozen.pb.tar.gz -C tensorflow/examples/label_image/data --numeric-owner
> inception_v3_2016_08_28_frozen.pb
> imagenet_slim_labels.txt
> tf-docker /tf/tensorflow > ls tensorflow/examples/label_image/data                
> grace_hopper.jpg  imagenet_slim_labels.txt  inception_v3_2016_08_28_frozen.pb
> tf-docker /tf/tensorflow > bazel-bin/tensorflow/examples/label_image/label_image
> 2023-03-29 06:48:48.658334: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
> To enable the following instructions: SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2023-03-29 06:48:51.529578: I tensorflow/examples/label_image/main.cc:252] military uniform (653): 0.834306
> 2023-03-29 06:48:51.529646: I tensorflow/examples/label_image/main.cc:252] mortarboard (668): 0.0218695
> 2023-03-29 06:48:51.529663: I tensorflow/examples/label_image/main.cc:252] academic gown (401): 0.0103581
> 2023-03-29 06:48:51.529676: I tensorflow/examples/label_image/main.cc:252] pickelhaube (716): 0.00800816
> 2023-03-29 06:48:51.529694: I tensorflow/examples/label_image/main.cc:252] bulletproof vest (466): 0.00535087
> tf-docker /tf > python -c "import tensorflow as tf; print(tf.__version__)"
> 2023-03-29 05:27:29.371380: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
> To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2.13.0
> ```
> 
> Can you please let us know if there is any help we can provide on running the example?
> 
> Thanks.

Oh okay I just got it, these examples are aiming Linux right ?

**Comment by TheHellTower** [comment]
I think it is so I will close this issue it's not a important one.
