### ISSUE TITLE
About fine-tune

### ISSUE THREAD

**Issue by panhu** [tensorflow/tensorflow#59908]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### Current Behaviour?

```shell
Hi:
How to replace several layers in the middle of the model during fine-tune？
Thanks
```

### Standalone code to reproduce the issue

```shell
How to replace several layers in the middle of the model during fine-tune？
```

### Relevant log output

_No response_</details>

**Comment by pjpratik** [comment]
Hi @panhu 

Can you provide more details regarding the issue?

You can replace layers in the middle of the model by layer assignment. 

Please refer to the transfer learning and fine tuning [tutorial](https://www.tensorflow.org/guide/keras/transfer_learning#fine-tuning). Also, please refer to the colab [gist](https://colab.research.google.com/gist/pjpratik/251fa430aa21f7e641e1e2baadfe749a/transfer_learning.ipynb) for the same.

Thanks.

**Comment by Chinmayadas2003** [comment]
hello @panhu 
steps to remove the middle layer in the transfer learning model.You can remove it using running a for loop and using pop function to remove up to whichever layer you want and then add any other middle layer. then you can freeze the weights of all layers except the middle layer. after that, you can easily compile and fit your model 

you can refer to the following GitHub gist given below
[githubgist](https://colab.research.google.com/gist/Chinmayadas2003/6875e84ee2c7558fcc9d2e0c1cdaac7a/removing-middle-layers-in-a-pretrained-model.ipynb#scrollTo=kKWSJJ-_wbZQ)
