### ISSUE TITLE
Resize OP doesn't work in Metal delegate with dynamic shape input in TFLite

### ISSUE THREAD

**Issue by Kepnu4** [tensorflow/tensorflow#59911]
Hello,
Resize OP doesn't work in Metal delegate with dynamic shape input in TFLite. Here is the small example of network which works on cpu but doesn't work with metal delegate with following error:
```
2023-03-06 15:01:06.317779+0400 TFLiteBenchmark[77147:6040306] Initialized TensorFlow Lite runtime.
INFO: Initialized TensorFlow Lite runtime.
2023-03-06 15:01:06.318869+0400 TFLiteBenchmark[77147:6040306] Created TensorFlow Lite delegate for Metal.
INFO: Created TensorFlow Lite delegate for Metal.
2023-03-06 15:01:06.320045+0400 TFLiteBenchmark[77147:6040306] Metal GPU Frame Capture Enabled
2023-03-06 15:01:06.322306+0400 TFLiteBenchmark[77147:6040306] Metal API Validation Enabled
INFO: GPU delegate created.
ERROR: Failed to apply GPU delegate.
```

Network graph:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/2921717/223099424-03870ed2-16fc-4e67-a6d9-17ec2fe9c40f.png">

[test_net.tflite.zip](https://github.com/tensorflow/tensorflow/files/10897648/test_net.tflite.zip)

### System information

-   **iOS 15.1**:
-   **Iphone 11**:
-   **source**:
-   **v2.11.0**:

**Comment by pjpratik** [comment]
@Kepnu4 Thanks for reporting the issue.

The supported for dynamic shapes by the TF Lite GPU Delegate is not available AFAIK. 

Also, when tflite [analyzer](https://www.tensorflow.org/lite/api_docs/python/tf/lite/experimental/Analyzer) is used, I could observe the following:

```
Subgraph#0 main(T#0) -> [T#10]
  Op#0 SHAPE(T#0) -> [T#4]
GPU COMPATIBILITY WARNING: Not supported op SHAPE
  Op#1 STRIDED_SLICE(T#4, T#3[1], T#2[3], T#3[1]) -> [T#5]
GPU COMPATIBILITY WARNING: STRIDED_SLICE supports for 3 or 4 dimensional tensors only.
  Op#2 CAST(T#5) -> [T#6]
GPU COMPATIBILITY WARNING: Not supported Cast case. Input type: INT64 and output type: FLOAT32
  Op#3 MUL(T#6, T#1) -> [T#7]
  Op#4 CAST(T#7) -> [T#8]
  Op#5 RESIZE_NEAREST_NEIGHBOR(T#0, T#8) -> [T#9]
GPU COMPATIBILITY WARNING: Expected 1 runtime input tensor(s), but node has 2 runtime input(s).
  Op#6 RELU(T#9) -> [T#10]
```
Please find the gist [here](https://colab.research.google.com/gist/pjpratik/c1373679cf3769e62df9310b22df0997/59911.ipynb) and the list of supported ML operations on GPU [here](https://www.tensorflow.org/lite/performance/gpu#supported_ops).

Thanks.

**Comment by Kepnu4** [comment]
Thanks @pjpratik, 
I find that dynamic shapes actually work in Metal delegate, for example this network with downsampling convolution works fine. So basically encoder part works but i can't obtain working decode parts because of upsampling. 
For unsupported operation i find it another problem, because resize got shape as input instead of upscaling factor. So it produces this shape operations when i just want to do 2x resize.

<img width="212" alt="image" src="https://user-images.githubusercontent.com/2921717/224312426-73b45c71-9831-41e0-932a-50a77b0e98f8.png">
[test_net.tflite.zip](https://github.com/tensorflow/tensorflow/files/10941936/test_net.tflite.zip)

**Comment by pjpratik** [comment]
@Kepnu4 Thanks for the information

@sachinprasadhs could you please look into this. Thank you.

**Comment by impjdi** [comment]
I'm not entirely sure what you mean by dynamic shape.  Your network has a fixed shape of [1, 1, 1, 3], no?

Anyway, using the `SHAPE` op to extract the tensor dimensions and doing a runtime decision of what the tensor size should be is not supported.  Things to be statically assigned.

**Comment by pkgoogle** [comment]
Hi @Kepnu4, we currently do not support dynamic shapes. If it works, then trying to build on top of it will lead to issues down the road because the system doesn't expect that state. Are you able to continue your work with static shapes?
