### ISSUE TITLE
`tf.data.Dataset.from_generator(...)` fails when the `output_signature` argument is a dictionary that has a value `tf.RaggedTensorSpec(...)` for some key

### ISSUE THREAD

**Issue by Leengit** [tensorflow/tensorflow#59926]
<details><summary>Click to expand!</summary> 
 
### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

v2.11.0-rc2-17-gd5b57ca93e5 2.11.0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8.10

### Current Behaviour?

```python
import tensorflow as tf
# With these:
type_value0 = tf.TensorSpec(shape=(), dtype=tf.string)
type_value1 = tf.RaggedTensorSpec(tf.TensorShape([None]), tf.int32, 0, tf.int64)
# These work:
d0 = type_value0.dtype
d1 = type_value1.dtype
# But these do not work
d2 = tf.dtypes.as_dtype(type_value0)
d3 = tf.dtypes.as_dtype(type_value1)
```
... and it appears that it is `tf.dtypes.as_dtype(type_value)` that is used to parse an `output_signature` provided to `tf.data.Dataset.from_generator`.

### Standalone code to reproduce the issue

See above

### Relevant log output
TypeError: Cannot convert the argument `type_value`: TensorSpec(shape=(), dtype=tf.string, name=None) to a TensorFlow DType.
TypeError: Cannot convert the argument `type_value`: RaggedTensorSpec(TensorShape([None]), tf.int32, 0, tf.int64) to a TensorFlow DType.
</details>

**Comment by Leengit** [comment]
Specifically I am getting this error when I use
```python
output_signature = {
    "top": tf.RaggedTensorSpec(tf.TensorShape([None]), tf.int32, 0, tf.int64),
    "left": tf.RaggedTensorSpec(tf.TensorShape([None]), tf.int32, 0, tf.int64),
}
```

**Comment by apmanikandan** [comment]
seems you are trying to convert a TensorSpec or a RaggedTensorSpec object into a DType object directly using tf.dtypes.as_dtype() method, which is not possible.  the as_dtype() method is used to convert a string or numpy dtype object to a tensorflow DType object.  replace your code for d2 and d3 as below , this shall solve the TypeError
...
d2 = type_value0.dtype
d3 = type_value1.dtype
....

**Comment by gaikwadrahul8** [comment]
Hi, @SuryanarayanaY 

Could you please look into this issue ? Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @Leengit ,

The code `d2 = tf.dtypes.as_dtype(type_value0)` fails obviously because the function `as_dtype()` expects the input to be:

> Inputs can be existing [tf.DType](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType) objects, a [DataType enum](https://www.tensorflow.org/code/tensorflow/core/framework/types.proto), a string type name, or a [numpy.dtype](https://numpy.org/doc/stable/reference/generated/numpy.dtype.html).


As you are providing `TensorSpec()` and `RaggedTensorSpec()` as inputs which does not belongs to any of the supporting arguments,and hence it is raising the intended error. There is no problem with this API here

If you find any problem with `tf.data.Dataset.from_generator()` please point to that exact issue with reproducible code and we will definitely have a look into the issue. Thanks!

**Comment by Leengit** [comment]
Perhaps I am doing something wrong.  Here is small example that shows the problem that I am having.
```python
import tensorflow as tf

print("=== The version of tensorflow ===")
print(f"tensorflow.__version__ = {repr(tf.__version__)}")

organized_by_rows = [dict(normal=[1], ragged=[2]), dict(normal=[3], ragged=[4, 5])]

organized_by_columns = {
    key: (tf.constant if key == "normal" else tf.ragged.constant)(
        [row[key] for row in organized_by_rows]
    )
    for key in organized_by_rows[0].keys()
}

dataset_works = tf.data.Dataset.from_tensor_slices(organized_by_columns)
element_spec = dataset_works.element_spec

print("=== The working dataset ===")
for row in dataset_works:
    print(f"row = {repr(row)}")
print("=== The working element_spec ===")
print(f"element_spec = {repr(element_spec)}")


def gen():
    for row in organized_by_rows:
        yield {
            normal: tf.constant(row["normal"]),
            ragged: tf.ragged.constant(row["ragged"]),
        }


print("=== This command fails ===")
dataset_fails = tf.data.Dataset.from_generator(gen, element_spec)

"""
The output I get is:

=== The version of tensorflow ===
tensorflow.__version__ = '2.11.0'
=== The working dataset ===
row = {'normal': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>, 'ragged': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>}
row = {'normal': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>, 'ragged': <tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 5], dtype=int32)>}
=== The working element_spec ===
element_spec = {'normal': TensorSpec(shape=(1,), dtype=tf.int32, name=None), 'ragged': RaggedTensorSpec(TensorShape([None]), tf.int32, 0, tf.int64)}
=== This command fails ===
Traceback (most recent call last):
  File "tensorflow_gen.py", line 30, in <module>
    dataset_fails = tf.data.Dataset.from_generator(gen, element_spec)
  File ".../tensorflow/python/util/deprecation.py", line 561, in new_func
    return func(*args, **kwargs)
  File ".../tensorflow/python/data/ops/dataset_ops.py", line 982, in from_generator
    output_signature = nest.map_structure_up_to(output_types,
  File ".../tensorflow/python/data/util/nest.py", line 453, in map_structure_up_to
    results = [func(*tensors) for tensors in zip(*all_flattened_up_to)]
  File ".../tensorflow/python/data/util/nest.py", line 453, in <listcomp>
    results = [func(*tensors) for tensors in zip(*all_flattened_up_to)]
  File ".../tensorflow/python/framework/tensor_spec.py", line 79, in __init__
    self._dtype = dtypes.as_dtype(dtype)
  File ".../tensorflow/python/framework/dtypes.py", line 762, in as_dtype
    raise TypeError(f"Cannot convert the argument `type_value`: {type_value!r} "
TypeError: Cannot convert the argument `type_value`: TensorSpec(shape=(1,), dtype=tf.int32, name=None) to a TensorFlow DType.
"""
```

**Comment by SuryanarayanaY** [comment]
Hi @Leengit ,

You are passing `element_spec` as positional argument which is causing the error. You should pass it as key word argument to `output_signature` like below.

`dataset_fails = tf.data.Dataset.from_generator(gen, output_signature=element_spec)`

With this the code execution success. Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/a6a01f58bdd0360f3f009a70e32cebd5/59926_r1.ipynb).

**Comment by Leengit** [comment]
Excellent, thank you very much!

**Comment by Leengit** [comment]
Would it make sense to adjust the error message to something that includes "Did you mean to supply the output_signature parameter instead of output_types?"

**Comment by SuryanarayanaY** [comment]
Hi @Leengit ,

Since the function `tf.data.Dataset.from_generator() `has 1 positional and 5 keyword args by default if you pass the arguments as positional it will assign in the order of arguments defined in the function. That is the default Python behaviour.Hence we need to specify the keyword argument specifically in such case.

**Comment by Leengit** [comment]
My suggestion about the error message arises because the two parameters are similarly named and one deprecates the other.  To be explicit, if the `output_types` argument cannot be handled as supplied, the error message could suggest that maybe the user meant to instead supply the argument as `output_signature`.  It would have saved me a bunch of trouble.  But if the suggestion is problematic to implement or has downsides that outweigh the upsides then please ignore it.  Thanks!

**Comment by SuryanarayanaY** [comment]
This API calls many other APIs internally and the error raised in internal APIs and hence its hard to implement your suggestion. However user can use stack trace to checkout the root cause.
