### ISSUE TITLE
Tensorflow lite for microcontrollers documentation has broken links to .cc files

### ISSUE THREAD

**Issue by acridland** [tensorflow/tensorflow#59959]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.11

### Custom Code

No

### Current Behaviour?

```shell
Documentation links to .cc files are broken.
https://www.tensorflow.org/lite/microcontrollers/get_started_low_level

In section 'Run Inference', link to 'hello_world_test.cc' and the other remaining .cc files linked cannot be opened.
```

### Standalone code to reproduce the issue

```shell
N/A
```

### Relevant log output

_No response_</details>

**Comment by pjpratik** [comment]
@acridland Thanks for reporting this.

PR #59969 has been created. Issue will be closed once PR is merged.

Thanks.

**Comment by pjpratik** [comment]
Hi @acridland 

The Hello World example has been refactored with the commit https://github.com/tensorflow/tensorflow/commit/f263e19e227da0d325f15477f57a359291fc387c and broken links are fixed.

Thanks.
