### ISSUE TITLE
Cannot save model when not giving a name in Layer.add_weight call in "build"

### ISSUE THREAD

**Issue by Mastiff37** [tensorflow/tensorflow#59954]
I have the identical issue to https://github.com/tensorflow/tensorflow/issues/36962, except I'm on 2.11.0.  Was it really resolved?

The issue is that the model will not save and returns: `AttributeError: 'NoneType' object has no attribute 'replace'`

It would have taken a very long time to run this down if I hadn't found the linked issue, but I also have `self.add_weight` in a custom layer with no name.

**Comment by pjpratik** [comment]
Hi @Mastiff37 Thanks for reporting this issue.

I was able to reproduce this issue on TF Nightly 2.13.0-dev20230313 as well. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/ae1b620bd93ebfff636632a6add7f1a8/59954.ipynb).

The workaround is to add name to the layer.

@SuryanarayanaY  could you please look into this?

**Comment by sachinprasadhs** [comment]
`The build()` method’s role is to create the layer’s variables by calling the `add_weight()`
 method for each weight. The `build()` method is called the first time the layer is used.
 At that point, Keras will know the shape of this layer’s inputs, and it will pass it to the `build()` method.
The constructor uses the `add_weight()` method to create the variables which will be used to track the operations used further.
It is. suggested to pass the name to the `add_weight()` method else as you see in the error message it fails in the below condition.
https://github.com/tensorflow/tensorflow/blob/f8163bd5bb373d622a69672eb3bdfd087c9bb5d7/tensorflow/python/trackable/trackable_utils.py#L120-L127
