### ISSUE TITLE
Please update the optimized protobuf binary library recommended on tensorflow.org

### ISSUE THREAD

**Issue by elmer-garduno** [tensorflow/tensorflow#5997]
The following page [1] describes how to use the optimized protobuf binary to allow for large protos. Recently the protobuf library removed the limit on the proto size once and for all [2]. 

This should fix some of the issues still being reported on #582. 

Could you please update the binary to the latest version and the documentation if applicable?

Thanks

[1] https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html#protobuf-library-related-issues
[2] https://github.com/google/protobuf/commit/5a76e633ea9b5adb215e93fdc11e1c0c08b3fc74#diff-922cc541c2d97d0ca70fce2b001de379R640

**Comment by gunan** [comment]
I am not sure if I fully understand the request.
Protobuf library released still uses slow python implementation of protobuf encoder/decoder.
So our instructions are still needed for people who want to use faster protobuf library, with C++ implementation compiled on their system.

As for the notice there about 64MB protobuf limits, I think our builds did not have those limits for a while.
But that error still can be seen for people who might have an old version of protobuf in their system, so message is still helpful, IMO.

Does the above explanation help?

**Comment by gunan** [comment]
Spoke with @elmer-garduno offline.
Looks like we somehow have the 64 MB limit on the library we have up.
@jhseu agreed to help out with this as I am working on something else.

**Comment by gunan** [comment]
@jhseu recently updated the packages pointed by tensorflow.org.
Closing this issue.
