### ISSUE TITLE
Using Teachable Machine to make a Audio model for Python

### ISSUE THREAD

**Issue by setter43** [tensorflow/tensorflow#59985]
I have been trying to make an AI model that will listen to user input. Depending on the user's input/command the program will carry out functions etc.

I am trying to use a model I have trained from the teachable machine, but the model is not in a format that can be used in Python. From what I have seen Python requires a .h5. However, TFLite.js is only available to export/download in. When I try to use this in my program I get hit with errors.

What steps can I take to import an Audio model for a Python system?

**Comment by tilakrayal** [comment]
@setter43,
For Simple audio recognition and Audio classification, there are pre-built models available on the official tensorflow.org. 
The model demonstrates how to preprocess audio files in the WAV format and build and train a basic [automatic speech recognition](https://en.wikipedia.org/wiki/Speech_recognition) (ASR) model for recognizing ten different words.

Also I tried to execute the demonstrated code for the Audio recognition which was executed successfully. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/11522da06ccca7071762085b7d3d007c/untitled1039.ipynb) and the reference.

https://www.tensorflow.org/tutorials/audio/simple_audio
https://www.tensorflow.org/lite/examples/audio_classification/overview#get_started

Thank you!

**Comment by setter43** [comment]
I want to use my own Audio classification AI model that I build using Teachable Machine. I run into a number of issues when trying to adapt the model.py in the git project keyword-spotting.

I can get the model working.
Then I try to point the program to my own AI and it fails.

`mendel@yellow-jet:~/newtest/project-keyword-spotter$ python3 run_model.py --model_file soundclassifier_with_metadata.tflite
Traceback (most recent call last):
  File "run_model.py", line 60, in <module>
    main()
  File "run_model.py", line 50, in main
    interpreter = model.make_interpreter(args.model_file)
  File "/home/mendel/newtest/project-keyword-spotter/model.py", line 211, in make_interpreter
    {'device': device[0]} if device else {})
  File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 351, in __init__
    experimental_preserve_all_tensors))
ValueError: Could not open 'soundclassifier_with_metadata.tflite'.
mendel@yellow-jet:~/newtest/project-keyword-spotter$
`

**Comment by tilakrayal** [comment]
@setter43,
Could you please confirm whether you are using this teachable machine official link to make an audio model.
https://teachablemachine.withgoogle.com/train/audio


The pre trained lite models in TF hub provide metadata. However, you can add metadata given a tflite model using [TFLIte meta data writer API](https://www.tensorflow.org/lite/models/convert/metadata_writer_tutorial).

Please find the overview of adding metada [here](https://www.tensorflow.org/lite/models/convert/metadata) along with the examples.

And also were you able to get the tflite file, if yes could you provide the code which you are using to test which helps to analyse.

Thank you!

**Comment by amangupta201** [comment]
Teachable Machine with Google gives you the option to download your model after it has been trained
See for TensorFlow Keras 
Click on it
It would generate a zip file with the name converted_keras
There would be 2 files in it:
1) 1 would be your trained model in .h5 format
2) 1 would be a simple text file with labels

https://teachablemachine.withgoogle.com/train/audio

**Comment by pjpratik** [comment]
Hi @setter43 

Sorry for the delayed response.

Under the hood Teachable Machine uses [Tensorflow.js](https://www.tensorflow.org/js), a library for machine learning in Javascript, to train and run the models you make in your web browser as given [here](https://github.com/googlecreativelab/teachablemachine-community#what-is-this-repository-for). The option to download `.h5` file might not be available yet.

Could you please to this issue in 
[teachablemachine-community](https://github.com/googlecreativelab/teachablemachine-community) repo for faster resolution?

Thanks.
