### ISSUE TITLE
TypeError: VariableMetaclass._variable_v1_call() got an unexpected keyword argument 'experimental_enable_variable_lifting'

### ISSUE THREAD

**Issue by devharsh** [tensorflow/tensorflow#59981]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

v2.12.0-rc0-46-g0d8efc960d2 2.12.0-rc1

### Custom Code

No

### OS Platform and Distribution

Windows 10

### Python version

3.11

### Current Behaviour?

```shell
self.model = keras.Sequential([
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\tensorflow\python\trackable\base.py", line 205, in _method_wrapper
    result = method(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Python311\Lib\site-packages\tensorflow\python\ops\variables.py", line 285, in __call__
    return cls._variable_v1_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: VariableMetaclass._variable_v1_call() got an unexpected keyword argument 'experimental_enable_variable_lifting'
```

### Standalone code to reproduce the issue

```shell
self.model = keras.Sequential([
    keras.layers.Dense(1, input_dim=self.degree),
    keras.layers.Dense(1)
    ])
self.model.compile(optimizer=optimizer, loss=loss)
self.model.summary()
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@devharsh,
I tried to execute the mentioned code and it was failing with the different error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/da1944b0f1762f8e8b36ea97a76aebcb/untitled1035.ipynb) and provide the complete code which helps us to debug the issue in an effective way. Thank you!

**Comment by tilakrayal** [comment]
@devharsh,
Unfortunately I was facing a different error. It is better to provide the complete code or the colab gist which helps us to analyse the issue in an effective way. Thank you!

**Comment by devharsh** [comment]
Seems like the `TensorFlow` upgrade to version `2.12.0` from `2.12.0-rc1` fixed the issue.
