### ISSUE TITLE
TFlite model has bad performance

### ISSUE THREAD

**Issue by codingzebra333** [tensorflow/tensorflow#59983]
Hi, I reduced .h5 model size using TFLiteConverter, but the tflite model has a bad accuracy and is not usable. [Here](https://colab.research.google.com/drive/14zMCm0XaszVrUoWd9bMvBjSXSdPvSWuw?userstoinvite=tirumaleshk%40google.com&actionButton=1#scrollTo=JWvOm1R5WyPs) is the code I used to reduce the model size. I wanted to know - is there something wrong with reducing the model size code or with the model architecture itself - that it is not possible to reduce the size for this specific model?
I also tested both - .h5 model and .tflite model on 400 images (good and bad quality), but the .tflite model evaluates good quality images the same way as bad quality images.
Here are MAD and RMSE scores:
.tflite vs .h5 (images that are in a good quality)
MAD: 1.8
RMSE: 1.9
tflite vs .h5 (same images but in a bad quality)
MAD: 0.3
RMSE: 0.4
[Here ](https://drive.google.com/drive/folders/1YcCSJgG6R4wRJ5qeU3gUoUd2296GghoL)are some examples. First MOS score in image name is .h5 result and second one is .tflite result.
Thank you in advance!

**Comment by sushreebarsa** [comment]
@Thank you for posting an issue!
The model accuracy might drop due to quantization applied to the model. To improve the accuracy you try to use post-training quantization. You can apply quantization on your trained model, and retrain it. Please refer to the following references and let us know if it helps?
https://www.tensorflow.org/lite/performance/model_optimization
https://www.tensorflow.org/model_optimization/guide/quantization/training
Thank you!

**Comment by codingzebra333** [comment]
Thank you @sushreebarsa for the answer! 
Could you please provide me some suggestions on how to do quantization aware training for this specific architecture? [Here](https://github.com/junyongyou/triq/blob/master/src/train/train_triq.py) is the code I use for training.
Thank you in advance!

**Comment by sushreebarsa** [comment]
@codingzebra333 I could see there is one duplicate [ticket](https://github.com/tensorflow/tensorflow/issues/59684) raised for the same issue. Could you please follow up with the other ticket and close this one?
Thank you!

**Comment by codingzebra333** [comment]
Thank you for pointing that out! I did not want to close that issue in case I get another suggestion that does not involve me retraining everything. Also, could you please provide suggestions for the best approach for quantization aware training for my use case? 
Thank you!

**Comment by pjpratik** [comment]
Hi @codingzebra333 

You can wrap the `triq` model at https://github.com/junyongyou/triq/blob/4b206b593f904f3f330ca61308a8d220f9cd1de1/src/train/train_triq.py#L80
around the `tfmot.quantization.keras.quantize_model` which requires the `tensorflow_mode_optimization` toolkit. 

Please refer to the [document](https://www.tensorflow.org/model_optimization/guide/quantization/training_comprehensive_guide#quantize_whole_model) on how to quantize whole model and the tips for better model accuracy.

Also, please check the QAT training [guide](https://www.tensorflow.org/model_optimization/guide/quantization/training_comprehensive_guide) and API [compatibility](https://www.tensorflow.org/model_optimization/guide/quantization/training#api_compatibility) fro applying QAT.

Thanks.

**Comment by codingzebra333** [comment]
Hi, thank you for the suggestion. I tried it, but I got an ValueError: Quantizing a tf.keras Model inside another tf.keras Model is not supported.
[Here](https://colab.research.google.com/drive/1BIj8iFssp0mnMTPBMk52k0r3Ibb-Pt8Q?usp=sharing) is the code. 

Thank you in advance!

**Comment by pjpratik** [comment]
Hi @codingzebra333 

The QAT has few [compatability](https://www.tensorflow.org/model_optimization/guide/quantization/training#api_compatibility) limitations as mentioned earlier. 

The quantization can be applied for [tf.keras](https://www.tensorflow.org/api_docs/python/tf/keras) with only Sequential and Functional models.

 Can you please refer the Quantization Aware Training [guide](https://www.tensorflow.org/model_optimization/guide/quantization/training_comprehensive_guide) and see if it fits for your use case?

Thanks.

**Comment by codingzebra333** [comment]
Hey! 
I have a functional model, so it should work for my use case. 
Thank you for such a fast response! Appreciate it!
