### ISSUE TITLE
LSTM model on arduino nano ble 33 using TFLite

### ISSUE THREAD

**Issue by Madhu5391111** [tensorflow/tensorflow#59994]
### 1. System information

- OS Platform and Distribution : Windows 11 + Arduino 1.8.19 
- TensorFlow installation (pip package or built from source): 2.11.0
- TensorFlow library : version 2.0

### 2. Code

  static tflite::MicroErrorReporter micro_error_reporter;
  error_reporter = &micro_error_reporter;
  model = tflite::GetModel(model_tflite_quant);
  if (model->version() != TFLITE_SCHEMA_VERSION) 
  {
    error_reporter->Report("Model version does not match Schema");
    while (1);
  }
  else
  {
    Serial.println("Model schema match!");
  }

  static tflite::AllOpsResolver resolver;
  
  // Build an interpreter to run the model with.
  static tflite::MicroInterpreter static_interpreter(
    model, resolver, tensor_arena, kTensorArenaSize, error_reporter);
  interpreter = &static_interpreter;

  // Allocate memory for the model's input and output tensors
  TfLiteStatus allocate_status = interpreter->AllocateTensors();

  if (allocate_status != kTfLiteOk) 
  {
    error_reporter->Report("AllocateTensors() failed");
    Serial.println("Allocation failed!");
    while(1);
  }
  else
  {
    Serial.println("Allocation done!");
  }

### 3. Probem

We are running LSTM model on arduino nano ble 33 using TFLite library. but we are getting "Allocation failed!". Parameters for LSTM model is 16 and LSTM_units = 1 and giving kTensorArenaSize = 150*1024. can u confirm the what is the reason for "Allocation failed!"

**Comment by pjpratik** [comment]
Hi @Madhu5391111 Thanks for reporting this issue.

There might be different reasons for tensor allocation to be failed like incorrect tensor sizes.

Can you provide the steps you have followed and the model settings provided inorder to further investigate the issue.

Thanks.
