### ISSUE TITLE
can substitute boringssl with openssl?

### ISSUE THREAD

**Issue by xiedeacc** [tensorflow/tensorflow#60009]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.8.4

### Custom Code

No

### OS Platform and Distribution

ubuntu22.04

### Current Behaviour?

```shell
my project import brpc and tf both, brpc must use openssl, tf use boringssl, so build will fail, can I modify tf use openssl?
```

### Standalone code to reproduce the issue

```shell
build conflict
```

### Relevant log output

_No response_</details>

**Comment by mihaimaruseac** [comment]
In general, it's not advised to do so. `boringssl` is a safer version of `openssl`, with none of the design choices that resulted in the `openssl` vulnerabilities that are famous (Hearthbleed) or not

**Comment by xiedeacc** [comment]
I know boringssl may have better security and performance, but our service not for public, so security may not so important to us. for we must use brpc, so we must use openssl, from you answer, I guess I can modify tensorflow to use openssl

**Comment by xiedeacc** [comment]
thanks a lot

**Comment by xiedeacc** [comment]
for anyone has same demand, use repo_mapping = { "@boringssl": "@openssl",} is the fastest sustitution way

**Comment by yangy996** [comment]
> for anyone has same demand, use repo_mapping = { "@boringssl": "@openssl",} is the fastest sustitution way对于任何有相同需求的人，使用 repo_mapping = { “”： “”，} 是最快的 sustitution 方式

there?please
![image](https://github.com/tensorflow/tensorflow/assets/15188456/2acb73d0-56d0-4be7-a123-cff067ca4526)
