### ISSUE TITLE
tf-nightly [2.13.0.dev20230322]: module 'tensorflow' has no attribute 'version'

### ISSUE THREAD

**Issue by YuliyaPylypiv** [tensorflow/tensorflow#60024]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.13.0.dev20230316

### Custom Code

No

### OS Platform and Distribution

macos 13.0.1 x86

### Python version

3.9.16

### Current Behaviour?

```shell
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'version'

python -c "import tensorflow as tf; tf.random.set_seed(1)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'random'
```

### Standalone code to reproduce the issue

```shell
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
python -c "import tensorflow as tf; tf.random.set_seed(1)"
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'version'
```
</details>

**Comment by synandi** [comment]
Hi @YuliyaPylypiv,
Thank you for raising this issue! Could you please let us know the steps followed to install Tensorflow?

**Comment by YuliyaPylypiv** [comment]
Hi @synandi, I used pip to install TensorFlow `pip3 install tf-nightly`

**Comment by YuliyaPylypiv** [comment]
The issue is resolved with `v1.12.1-91194-g44c02012675 2.13.0-dev20230317` version

```
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
2023-03-17 14:50:51.497925: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
v1.12.1-91194-g44c02012675 2.13.0-dev20230317
```

**Comment by YuliyaPylypiv** [comment]
I'm seeing the same issue again with `tf-nightly 2.13.0.dev20230322`

To reproduce:
`pip install tf-nightly==2.13.0.dev20230322`
`python -c "import tensorflow as tf; print(tf.version.VERSION)"`

**Comment by synandi** [comment]
Hi @YuliyaPylypiv, 
It is recommended to use the stable version of Tensorflow instead of tf-nightly as it is unstable. It will likely be resolved in the stable release. Thank you!

**Comment by Adesoji1** [comment]
Do this below 
!python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
!python -c "import tensorflow as tf; tf.random.set_seed(1)" 

output below
2023-03-31 23:13:38.444282: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
v1.12.1-91939-g13de22a3b30 2.13.0-dev20230331
2023-03-31 23:13:42.397786: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

**Comment by YuliyaPylypiv** [comment]
I'm aware that stable TensorFlow works! Wanted to make sure the issue is resolved with the tf-nightly. Thank you all!
