### ISSUE TITLE
A check fail can be triggered in CholeskyGrad

### ISSUE THREAD

**Issue by shijy16** [tensorflow/tensorflow#60034]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

tf 2.13.0-dev20230317

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10

### CUDA/cuDNN version

CUDA 11.5

### Current Behaviour?

```shell
A crash due to check fail can be triggered by giving a corner case in `tf.raw_ops.CholeskyGrad`.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
l = tf.random.uniform([8, 0, 2**60, 8], dtype=tf.float64, minval=-2**50, maxval=2**50)
grad = tf.random.uniform([], dtype=tf.float64, minval=-2**50, maxval=2**50)
res = tf.raw_ops.CholeskyGrad(
    l=l,
    grad=grad,
)
```

### Relevant log output

```shell
2023-03-18 18:20:23.847214: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-03-18 18:20:23.894704: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-03-18 18:20:24.657541: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-03-18 18:20:26.296951: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1635] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14577 MB memory:  -> device: 0, name: Tesla V100-PCIE-16GB, pci bus id: 0000:2f:00.0, compute capability: 7.0
2023-03-18 18:20:26.563113: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 1152921504606846976 with 8, result: -9223372036854775808
Aborted (core dumped)
```
</details>

**Comment by sushreebarsa** [comment]
@shijy16 Thank you for reporting this issue!
@SuryanarayanaY  While reproducing the issue on colab using TF v2.11, I faced the following error log as the session crashed. 


Mar 26, 2023, 6:28:42 PM | WARNING | WARNING:root:kernel b01c86be-9273-4315-9125-c491e703869b restarted
-- | -- | --
Mar 26, 2023, 6:28:42 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
Mar 26, 2023, 6:28:41 PM | WARNING | 2023-03-26 12:58:41.908549: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 1152921504606846976 with 8, result: -9223372036854775808
Mar 26, 2023, 6:28:41 PM | WARNING | 2023-03-26 12:58:41.865783: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Mar 26, 2023, 6:28:39 PM | WARNING | 2023-03-26 12:58:39.761239: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Mar 26, 2023, 6:28:39 PM | WARNING | 2023-03-26 12:58:39.761218: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
Mar 26, 2023, 6:28:39 PM | WARNING | 2023-03-26 12:58:39.761060: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
Mar 26, 2023, 6:28:38 PM | WARNING | To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Mar 26, 2023, 6:28:38 PM | WARNING | 2023-03-26 12:58:38.606508: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2 FMA
Mar 26, 2023, 6:27:33 PM | WARNING | WARNING:root:kernel b01c86be-9273-4315-9125-c491e703869b restarted


Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @shijy16 ,

The issue has been resolved in Tf2.16v. Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/5bf279b369178bc09447f310323393ce/60034_nightly_success.ipynb).
