### ISSUE TITLE
C/Other Languages: Support serialization and deserialization of Tensors

### ISSUE THREAD

**Issue by asimshankar** [tensorflow/tensorflow#6003]
In C++ and Python, Tensors can be serialized into a `TensorProto` using functions like [`Tensor::AsProtoTensorContents`](https://github.com/tensorflow/tensorflow/blob/f7ec99516ce0e0937e0b865e90aa02c748cd36c6/tensorflow/core/framework/tensor.h#L205)  and [`make_tensor_proto`](https://www.tensorflow.org/versions/r0.12/api_docs/python/contrib.util.html#make_tensor_proto)

This is particularly useful when communicating tensors across process boundaries such as [PredictRequest](https://github.com/tensorflow/serving/blob/8c89d72259a7c15f0a9711a67eecf284d9460cca/tensorflow_serving/apis/predict.proto#L22) RPCs to a [TensorFlow Model Server](https://tensorflow.github.io/serving/) 

Filing this to track any changes to the [C API](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h) and language bindings.

Interested parties: @asimshankar @jhseu @nfiedel @josh11b

**Comment by yifeif** [comment]
@asimshankar, saw "Go: API functions to serialize/deserialize Tensors" was added with #6137.  Are we expecting further update on this issue?

**Comment by asimshankar** [comment]
Nobody is actively working on this, this was more of a tracking bug. I think it's fine to close this for now (and re-open if and when the need is more urgent). The "need" would be to save/load tensors directly (as opposed to using things like the Restore operations or a SavedModel loader).

**Comment by sbsends** [comment]
@asimshankar, could we reopen this? Tensor se/de operations in C would be extremely useful for multi-language interoperability.

**Comment by asimshankar** [comment]
@sbsends : Happy to reopen it, but would love to hear what specifically you're interested in. Could you elaborate on what you're trying to do and the problems being run into?

**Comment by sbsends** [comment]
@asimshankar, we are interested in passing TensorProto's directly between languages. E.g. generating a packed TensorProto's in Python and sending them over the wire to a program running in Golang. This is possible using Pythons implementation of [make_proto](https://www.tensorflow.org/api_docs/python/tf/make_tensor_proto) and then building a custom handler in Golang to parse the TensorProto's contents/type/dim's. The tensor contents can be read using [ReadTensor](https://godoc.org/github.com/tensorflow/tensorflow/tensorflow/go#ReadTensor), but this only supports numeric data types. IMHO, it would be significantly cleaner (and less error prone) to handle ser/de in a standardized way across all client libraries using the C API.

**Comment by sbsends** [comment]
@asimshankar, would you consider giving feedback on our stab at building a standard for transporting tensors across applications/languages? The goal is to support many frameworks and act as an intermediary between application specific protocols. What can we do to increase the likelihood of gaining TensorFlow support?

https://github.com/tensortask/ttp

**Comment by lyschoening** [comment]
@asimshankar Would it we possible to reopen this? In our case, we would like to serialize/deserialize tensors to communicate with Tensorflow Serving from Go. We can not use the Go library as it does not handle serialization of string tensors.

**Comment by blepfo** [comment]
Seconding the above comment -- I ran into this issue trying to use to Go API `tf.ReadTensor()` only to discover that `DT_STRING` is not supported.

In the meantime is there an easy workaround for parsing string `TensorProto` into Go `tf.Tensor`?
