### ISSUE TITLE
failed to expand 'RETURN_IF_ROCTRACER_ERROR', it is invalid to use a preprocessor directive as macro parameter

### ISSUE THREAD

**Issue by 7elmie** [tensorflow/tensorflow#60032]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### Current Behaviour?

```shell
A bug happened!Why is this an issue?
At Codacy we strive to provide great descriptions for our patterns. With good explanations developers can better understand issues and even learn how to fix them.

For this tool we are not yet meeting this standard but you can help us improve the docs. To know more, take a look at our tool documentation guide.

You can also visit the tool's website to find useful tips about the patterns.
```

### Standalone code to reproduce the issue

```shell
}
    RETURN_IF_ROCTRACER_ERROR(static_cast<roctracer_status_t>(
#if TF_ROCM_VERSION >= 50300
        se::wrap::roctracer_next_record(record, &record)
#else
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@7elmie,
In order to expedite the trouble-shooting process, could you please provide a complete code snippet you are trying to execute. Thank you!

**Comment by tilakrayal** [comment]
Closing this as stale. Please reopen if this is still a valid request. Thank you!
