### ISSUE TITLE
How to build with xnnpack

### ISSUE THREAD

**Issue by njuhang** [tensorflow/tensorflow#60042]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.10.0

### Custom Code

Yes

### OS Platform and Distribution

ubuntu 20.04

### Mobile device

Qualcomm

### Python version

3.8

### Bazel version

5.1.1

### GCC/Compiler version

9.3.0

### Current Behaviour?

```shell
I want to build without xnnpack, or with xnnpack-qs8 diabled. How to achieve that?
```

### Standalone code to reproduce the issue

```shell
I tried with "--define=tflite_with_xnnpack_qu8=false --define=tflite_with_xnnpack_qs8=false", and "--define tflite_with_xnnpack=false". But it seems that they didn't work.
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@njuhang 
Could you please  provide more information on the issue reported here ?

Thank you !

**Comment by tiruk007** [comment]
Closing as stale. Please reopen if you'd like to work on this further.

Thanks !
