### ISSUE TITLE
QuantizeAndDequantizeV4 throws TypeError in gradient computation in forward mode

### ISSUE THREAD

**Issue by trickiwoo** [tensorflow/tensorflow#60059]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11

### Custom Code

Yes

### Current Behaviour?

```shell
QuantizeAndDequantizeV4 throws TypeError in gradient computation in forward mode. I encountered a similar issue (https://github.com/tensorflow/tensorflow/issues/59960) where quantize_and_dequantize_v2 is wrongly associated with _QuantizeAndDequantizeV4GradGrad in gradient computation. In this case, the V4 version API doesn't work either. It would be great if they could be fixed in the backend.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

tensor = tf.random.uniform(shape=[1, 1], dtype=tf.float32)

def quantizeAndDequantize(x):

    y = tf.raw_ops.QuantizeAndDequantizeV4(input=x, input_min=0., input_max=5.)
    return y

output = quantizeAndDequantize(tensor) # pass
with tf.autodiff.ForwardAccumulator(tensor, tf.constant([[0.], [1.]])) as acc:
    output = quantizeAndDequantize(tensor)
```

### Relevant log output

```shell
TypeError: _QuantizeAndDequantizeV4GradGrad() takes 2 positional arguments but 4 were given
```
</details>

**Comment by sushreebarsa** [comment]
@trickiwoo Though i was able to replicate the issue [here](https://colab.research.google.com/gist/sushreebarsa/5af7133e302705296c699040acddd4de/60059.ipynb), please confirm if this is a duplicate ticket of [this](https://github.com/tensorflow/tensorflow/issues/59960) issue. If so please close this thread as we will follow up with the other one. Thank you!

**Comment by trickiwoo** [comment]
Hi @sushreebarsa , thanks for replicating it! It was a similar issue but for different APIs

**Comment by sushreebarsa** [comment]
@trickiwoo Thank you for the confirmation.
@SuryanarayanaY Could you please have a look at this issue?
Thank you!

**Comment by manojssmk** [comment]
Hi @trickiwoo 

You are calling QuantizeAndDequantizeV4 inside the ForwardAccumulator, which is not differentiable. Since the operation cannot propagate gradients raises an error. The TypeError is due to the mismatch in expected arguments.

Thanks
