### ISSUE TITLE
CTCModel

### ISSUE THREAD

**Issue by MrAchraf10** [tensorflow/tensorflow#60063]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11.1

### Custom Code

Yes

### Current Behaviour?

```shell
ImportError                               Traceback (most recent call last)
Cell In[1], line 7
      5 from keras.models import Model
      6 import tensorflow_addons as tfa
----> 7 from keras_ctcmodel.CTCModel import CTCModel as CTCModel
      8 from CTCModel import CTCModel
      9 import pickle

File ~\anaconda3\envs\tensorflow\lib\site-packages\keras_ctcmodel\CTCModel.py:7
      5 import os
      6 from keras import Input
----> 7 from keras.engine import Model
      8 from keras.layers import Lambda
      9 from keras.models import model_from_json, Sequential

ImportError: cannot import name 'Model' from 'keras.engine'

I can't find a solution to this problem, please, I need your help !!
```

### Standalone code to reproduce the issue

```shell
from keras.layers import TimeDistributed, Activation, Dense, Input, Bidirectional, LSTM, Masking, GaussianNoise
from keras.layers import Conv2D, MaxPooling2D, Reshape, Flatten, Dense
from tensorflow.keras.layers import BatchNormalization
from keras.optimizers import Adam
from keras.models import Model
import tensorflow_addons as tfa
from keras_ctcmodel.CTCModel import CTCModel as CTCModel
from CTCModel import CTCModel
```

### Relevant log output

_No response_</details>

**Comment by pat749** [comment]
It seems like there are two import statements for **CTCModel** from different locations:
```
from keras_ctcmodel.CTCModel import CTCModel as CTCModel
from CTCModel import CTCModel
```
You should remove one of the import statements, depending on where the **CTCModel** class is defined in your project.

**Comment by MrAchraf10** [comment]
Ok, I understood, thanks a lot.
________________________________
De : Durgesh Patel ***@***.***>
Envoyé : samedi 25 mars 2023 21:41
À : tensorflow/tensorflow ***@***.***>
Cc : Achraf EL ASRI ***@***.***>; Author ***@***.***>
Objet : Re: [tensorflow/tensorflow] CTCModel (Issue #60063)


It seems like there are two import statements for CTCModel from different locations:

from keras_ctcmodel.CTCModel import CTCModel as CTCModel
from CTCModel import CTCModel


You should remove one of the import statements, depending on where the CTCModel class is defined in your project.

**Comment by sushreebarsa** [comment]
@MrAchraf10 Could you please see the installation instructions as below 
```
$ pip install keras-ctcmodel

OR

$ git clone https://github.com/cyprienruffino/CTCModel
 python setup.py install --user


```
Let us know if you still face the issue for importing CTCModel using the following 
```
from keras_ctcmodel.CTCModel import CTCModel as CTCModel

```
Thank you!
