### ISSUE TITLE
Tensorflow version is 2.11.1 in v2.12.0 tag

### ISSUE THREAD

**Issue by npanpaliya** [tensorflow/tensorflow#60080]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

TF 2.12

### Custom Code

Yes

### OS Platform and Distribution

Linux RHEL 8.6

### Bazel version

5.3

### GCC/Compiler version

11.2

### CUDA/cuDNN version

11.4/8.3

### Current Behaviour?

```shell
Version of TF in v2.12.0 tag is 2.11.1. However, it should have been 2.12.0.
```

### Standalone code to reproduce the issue

```shell
https://github.com/tensorflow/tensorflow/blob/v2.12.0/tensorflow/tools/pip_package/setup.py#L49 shows 2.11.1
```

### Relevant log output

_No response_</details>

**Comment by npanpaliya** [comment]
Looks like TF 2.12.0 tag is created from r2.11 branch instead of r2.12. Because r2.12 branch shows correct version in setup.py.

**Comment by tiruk007** [comment]
@npanpaliya 
The version of TF in v2.12.0 tag is updated to 2.12.0. Please check this [link](https://github.com/tensorflow/tensorflow/blob/v2.12.0/tensorflow/tools/pip_package/setup.py#L50) and confirm the same.

Thank you!

**Comment by npanpaliya** [comment]
> @npanpaliya The version of TF in v2.12.0 tag is updated to 2.12.0. Please check this [link](https://github.com/tensorflow/tensorflow/blob/v2.12.0/tensorflow/tools/pip_package/setup.py#L50) and confirm the same.
> 
> Thank you!

Yes, I did notice this yesterday night that it is fixed. Thank you for fixing this.
