### ISSUE TITLE
Public access to current absolute name scope

### ISSUE THREAD

**Issue by albertz** [tensorflow/tensorflow#6010]
I can get it via `tf.get_default_graph()._name_stack`. But I think there is no public API to get that information. Some public API would be nice.

**Comment by mrry** [comment]
I have no objection to this feature request, but the correct resolution probably depends on the resolution to #6007 (i.e. could we use **variable** scopes instead?). Assigning to @lukaszkaiser, in the interests of message consistency.

**Comment by lukaszkaiser** [comment]
I do not see any compelling use case for this. As we're trying to migrate the public API away from name_scope and towards variable_scope, I'd be against adding it without a compelling need.
