### ISSUE TITLE
LSTMBlockCell validation error

### ISSUE THREAD

**Issue by zsoltszakaly** [tensorflow/tensorflow#60114]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf2.11

### Custom Code

Yes

### OS Platform and Distribution

Linux Debian 10

### Mobile device

N/A

### Python version

N/A

### Current Behaviour?

```shell
In tensorflow/tensorflow/core/kernels/rnn/lstm_ops.cc line 441 the error message prints wci_tensor->dims(), but should print wcf_tensor->dims(). In current version a strange message can appear:
wcf_tensor must be rank 1 but is rank 1.
```

### Standalone code to reproduce the issue

```shell
It is clear from the source code, no need to reproduce.
```

### Relevant log output

_No response_</details>

**Comment by mayankagarwals** [comment]
Hey @zsoltszakaly , 

Yep, this is clearly a typo. I have fixed it locally but don't seem to have push access to create a branch. 
@synandi @sushreebarsa How do I go about this

**Comment by synandi** [comment]
Hi @zsoltszakaly,
Thank you for reporting the issue! I have raised a PR. The issue will move to closed status once the https://github.com/tensorflow/tensorflow/pull/60138 is merged. 

@mayankagarwals Please refer to [this](https://www.tensorflow.org/community/contribute) on how to contribute to Tensorflow.  Thank you!
