### ISSUE TITLE
If we have any detail information of each CI in tensorflow Github? 

### ISSUE THREAD

**Issue by sanbuphy** [tensorflow/tensorflow#60111]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.8

### Custom Code

Yes

### Current Behaviour?

```shell
Hello, I have been studying the actions (CI) of various open source projects on Github recently.
I noticed that tensorflowhas a well-established CI, so I would like to further understand its composition and structure. Do you have any relevant materials that I can study and refer to? 
Thank you very much.
```

### Standalone code to reproduce the issue

```shell
none
```

### Relevant log output

_No response_</details>

**Comment by avinashrajavarapu** [comment]
In github repository u can find CI(continious integrity). It contains pipelines in workflows directory used for build, run, test and deploy of tensorflow code for projects.
For windows you have '**windows-ci.yml**' pipelines which uses visual studio to build and run.
For mac you have there is '**macos-ci.yml**'
For linu7x it is '**linux-ci.yml**'

Now to build and test pipeline used is '**nightly-pip-package.yml**'
For tensorflow doc we use '**docs-presubmit.yml**'
To buld, run and release the packages we use '**release.yml**' 
You can look over many pipelines in workflows directory.

**Comment by sanbuphy** [comment]
> In github repository u can find CI(continious integrity). It contains pipelines in workflows directory used for build, run, test and deploy of tensorflow code for projects. For windows you have '**windows-ci.yml**' pipelines which uses visual studio to build and run. For mac you have there is '**macos-ci.yml**' For linu7x it is '**linux-ci.yml**'
> 
> Now to build and test pipeline used is '**nightly-pip-package.yml**' For tensorflow doc we use '**docs-presubmit.yml**' To buld, run and release the packages we use '**release.yml**' You can look over many pipelines in workflows directory.

Thank you very much!

**Comment by sanbuphy** [comment]
> In github repository u can find CI(continious integrity). It contains pipelines in workflows directory used for build, run, test and deploy of tensorflow code for projects. For windows you have '**windows-ci.yml**' pipelines which uses visual studio to build and run. For mac you have there is '**macos-ci.yml**' For linu7x it is '**linux-ci.yml**'
> 
> Now to build and test pipeline used is '**nightly-pip-package.yml**' For tensorflow doc we use '**docs-presubmit.yml**' To buld, run and release the packages we use '**release.yml**' You can look over many pipelines in workflows directory.


Hi! @avinashrajavarapu , Can you tell me the difference between CI that runs on GitHub Actions and CI that runs on Jenkins? Or, when is a full CI run, and when is a partial CI run? What determines this? Thank you very much.
