### ISSUE TITLE
Is it possible to implement spatial pyramid pooling layer with tensorflow?

### ISSUE THREAD

**Issue by karlTUM** [tensorflow/tensorflow#6011]
I would like to implement the spatial pyramid pooling layer as introduced [in this paper.](https://arxiv.org/pdf/1406.4729v4.pdf)
As the paper setting, the keypoint is to define variant kernel size and stride size of max_pooling layer, which is:
```
kernel_size = ceil(a/n)
stride_size = floor(a/n)
```
where `a` is the input tensor spatial size, and `n` is the pyramid level, i.e. spatial bins of the pooling output.

I try to implement this layer with tensorflow, the code is:

```
def spp_layer(input_, name = 'SPP_layer'):
    '''4 level spp layer 
    spatial bins: [6_6, 3_3, 2_2, 1_1] '''

    shape = input_.get_shape().as_list()

    with tf.variable_scope(name):

        spp_6_6_pool = tf.nn.max_pool(input_, ksize=[1, np.ceil(shape[1]/6).astype(np.int32), np.ceil(shape[1]/6).astype(np.int32), 1], 
                                      strides=[1, shape[1]//6, shape[2]//6, 1], 
                                      padding='SAME')
        print('SPP layer level 6:', spp_6_6_pool.get_shape().as_list())

        spp_3_3_pool = tf.nn.max_pool(input_, ksize=[1, np.ceil(shape[1]/3).astype(np.int32), np.ceil(shape[2]/3).astype(np.int32), 1], 
                                      strides=[1, shape[1]//3, shape[2]//3, 1], 
                                      padding='SAME')
        print('SPP layer level 3:', spp_3_3_pool.get_shape().as_list())

        spp_2_2_pool = tf.nn.max_pool(input_, ksize=[1, np.ceil(shape[1]/2).astype(np.int32), np.ceil(shape[2]/2).astype(np.int32), 1], 
                                      strides=[1, shape[1]//2, shape[2]//2, 1], 
                                      padding='SAME')
        print('SPP layer level 2:', spp_2_2_pool.get_shape().as_list())

        spp_1_1_pool = tf.nn.max_pool(input_, ksize=[1, np.ceil(shape[1]/1).astype(np.int32), np.ceil(shape[2]/1).astype(np.int32), 1], 
                                      strides=[1, shape[1]//1, shape[2]//1, 1], 
                                      padding='SAME')
        print('SPP layer level 1:', spp_1_1_pool.get_shape().as_list())


        spp_6_6_pool_flat = tf.reshape(spp_6_6_pool, [shape[0], -1])
        spp_3_3_pool_flat = tf.reshape(spp_3_3_pool, [shape[0], -1])
        spp_2_2_pool_flat = tf.reshape(spp_2_2_pool, [shape[0], -1])
        spp_1_1_pool_flat = tf.reshape(spp_1_1_pool, [shape[0], -1])

        spp_pool = tf.concat(1, [spp_6_6_pool_flat, spp_3_3_pool_flat, spp_2_2_pool_flat, spp_1_1_pool_flat])

    return spp_pool
```

But it cannot gurantee the same length pooling output, when the input sizes are different.

Does tensorflow support the fixed length spatial pyramid pooling layer?

I also post the question on the [stackoverflow](http://stackoverflow.com/questions/40913794/tensorflow-how-to-implement-the-fixed-length-spatial-pyramid-pooling-layer).

**Comment by karlTUM** [comment]
I change the padding from 'SAME' to 'VALID' and it is also not invariant to the input data shape

**Comment by MatthiasWinkelmann** [comment]
This seems very similar to Atrous Convolution ([Paper]( http://arxiv.org/abs/1606.00915)) for which keras has a Tensorflow  implementation ([https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L1739](https://github.com/fchollet/keras/blob/master/keras/backend/tensorflow_backend.py#L1739))

**Comment by DrSleep** [comment]
@karlTUM, you can try the code below:

```
def spp_layer2(input_, levels=[2, 1], name = 'SPP_layer'):
    '''Multiple Level SPP layer.
       Works for levels=[1, 2, 3, 6].'''
    shape = input_.get_shape().as_list()
    with tf.variable_scope(name):
        pool_outputs = []
        for l in levels:
            pool = tf.nn.max_pool(input_, ksize=[1, np.ceil(shape[1] * 1. / l).astype(np.int32), np.ceil(shape[2] * 1. / l).astype(np.int32), 1], 
                                      strides=[1, np.floor(shape[1] * 1. / l + 1).astype(np.int32), np.floor(shape[2] * 1. / l + 1), 1], 
                                      padding='SAME')
            print "Pool Level {:}: shape {:}".format(l, pool.get_shape().as_list())
            pool_outputs.append(tf.reshape(pool, [shape[0], -1]))
        spp_pool = tf.concat(1, pool_outputs)
    return spp_pool
```

I haven't extensively tested it, but it outputs a vector of the same length (in case of `levels=[1, 2, 3, 6]`): `50=[1x1 + 2x2 + 3x3 + 6x6]x(channels)` for every input with each spatial dimension more (or equal) than `36=6x6`.

**Comment by karlTUM** [comment]
@DrSleep  Thank you.

**Comment by abossenbroek** [comment]
I can't get it to work on python3. Any recommendations?

Output
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-41b88a9b0081> in <module>()
     12 rate = 0.001
     13 
---> 14 logits = TrafficNet(x)
     15 cross_entropy = tf.nn.softmax_cross_entropy_with_logits(logits, one_hot_y)
     16 loss_operation = tf.reduce_mean(cross_entropy)

<ipython-input-23-673412c4ac1b> in TrafficNet(x)
     71         return spp_pool
     72 
---> 73     pool3 = spp_layer2(conv13)
     74 
     75     from IPython.core.debugger import Tracer

<ipython-input-23-673412c4ac1b> in spp_layer2(input_, levels, name)
     67                                       strides=[1, np.floor(shape[1] * 1. / l + 1).astype(np.int32), np.floor(shape[2] * 1. / l + 1), 1],
     68                                       padding='SAME')
---> 69                 pool_outputs.append(tf.reshape(pool, [shape[0], -1]))
     70             spp_pool = tf.concat(1, pool_outputs)
     71         return spp_pool

/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py in reshape(tensor, shape, name)
   2446   """
   2447   result = _op_def_lib.apply_op("Reshape", tensor=tensor, shape=shape,
-> 2448                                 name=name)
   2449   return result
   2450 

/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py in apply_op(self, op_type_name, name, **keywords)
    491           except TypeError as err:
    492             if dtype is None:
--> 493               raise err
    494             else:
    495               raise TypeError(

/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py in apply_op(self, op_type_name, name, **keywords)
    488                 dtype=dtype,
    489                 as_ref=input_arg.is_ref,
--> 490                 preferred_dtype=default_dtype)
    491           except TypeError as err:
    492             if dtype is None:

/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/framework/ops.py in convert_to_tensor(value, dtype, name, as_ref, preferred_dtype)
    667 
    668         if ret is None:
--> 669           ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    670 
    671         if ret is NotImplemented:

/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    174                                          as_ref=False):
    175   _ = as_ref
--> 176   return constant(v, dtype=dtype, name=name)
    177 
    178 

/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py in constant(value, dtype, shape, name, verify_shape)
    163   tensor_value = attr_value_pb2.AttrValue()
    164   tensor_value.tensor.CopyFrom(
--> 165       tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    166   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    167   const_tensor = g.create_op(

/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape)
    439   if numpy_dtype == dtypes.string and not isinstance(values, np.ndarray):
    440     proto_values = _FlattenToStrings(values)
--> 441     tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
    442     return tensor_proto
    443 

/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py in <listcomp>(.0)
    439   if numpy_dtype == dtypes.string and not isinstance(values, np.ndarray):
    440     proto_values = _FlattenToStrings(values)
--> 441     tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
    442     return tensor_proto
    443 

/Users/anton/.pyenv/versions/anaconda3-4.1.1/lib/python3.5/site-packages/tensorflow/python/util/compat.py in as_bytes(bytes_or_text, encoding)
     63   else:
     64     raise TypeError('Expected binary or unicode string, got %r' %
---> 65                     (bytes_or_text,))
     66 
     67 

TypeError: Expected binary or unicode string, got None
```

**Comment by DrSleep** [comment]
It is not a problem with python3. 
You have this error because the batch size of your input is not defined (it is None), and it is referred to in the reshape operation: `pool_outputs.append(tf.reshape(pool, [shape[0], -1]))`.
You can fix it in multiple ways: for example, rather than keeping `-1` to find out the hidden size, you can infer the batch size instead and run `pool_outputs.append(tf.reshape(pool, [-1, l * l * shape(3)]))`. Another way is to just use `tf.shape(input_)[0]`, which is a tensor.

**Comment by luizgh** [comment]
It seems that the solution above only works if the input size is known beforehand (since the size of the pooling window is static). In order to work with any input sizes, the argument to the pooling operation should be a symbolic variable (so that the size of the pooling window is calculated at execution time). However, this doesn't seem to be supported yet by the max-pooling operation in tensorflow.

For reference, here is the implementation of SPP on lasagne: https://github.com/Lasagne/Lasagne/blob/master/lasagne/layers/dnn.py#L510-L596. It uses a pooling implementation from theano.sandbox.cuda.dnn that supports symbolic variables as arguments

**Comment by javiribera** [comment]
Is anyone aware of work towards making TF's pooling layer accept a tensor with size defined at runtime?

**Comment by luizgh** [comment]
@javiribera -  FYI, I implemented a version of SPP in Theano+lasagne that does not use the standard pooling operation, but instead manually slices the input region. Take a look in the function "pool_2d_nxn_regions" here:
https://github.com/Lasagne/Lasagne/pull/799/commits/c01e3d922a5712ca4c54617a15a794c23746ac8c#diff-d0bc475ce6f46dfdf62cea86f4a2b911

I think that this can be implemented in tensorflow. It requires: slicing a tensor using another tensor as indices (which is supported, at least in version 1.0), symbolical versions of floor and ceil (tf.floor, tf.ceil), and casting to integer (tf.cast).

**Comment by Evan-Gao** [comment]
@luizgh How do you deal with back-propagation in your new pooling layer? If I use slice operations in one pooling layer, can tensorflow train it using auto diff?

**Comment by luizgh** [comment]
Hi @Evan-Gao,

Theano will backpropagate only through the part of the input tensor that was selected in the slice operation. I ran a quick experiment and Tensorflow does the same:

```
import numpy as np
import tensorflow as tf

inputs = tf.placeholder(dtype=tf.float32, shape=(2,3,3))
which_channel = tf.placeholder(dtype=tf.int32)
sliced = inputs[which_channel]
cost = tf.norm(sliced)
grad = tf.gradients(cost, inputs)

sess = tf.Session()
print(sess.run(grad, feed_dict={inputs: np.ones((2,3,3)), which_channel:0}))
print(sess.run(grad, feed_dict={inputs: np.ones((2,3,3)), which_channel:1}))
```

This code uses a symbolic variable ("which_channel") to slice the input, and considers the cost as the norm of the sliced tensor. We can see that backpropagation will only affect the part of the input that was selected in the slice operation: when we select the channel 0, it shows a gradient different than 0 for the first channel, with zeros in the gradient for the second channel, and vice versa when we select which_channel=1

**Comment by andrewgiessel** [comment]
@luizgh thanks for all these comments!  I'm just wading into this conversation now, but wanted to point out that there was a layer implemented for Keras [here](https://github.com/yhenon/keras-spp/blob/master/SpatialPyramidPooling.py).  I'm not sure, but it looks like it implements pooling directly by indexing into the input and using tf.reduce_max() under the hood.  

Any comments?

**Comment by luizgh** [comment]
@andrewgiessel Indeed, it seems that they are manually slicing the tensors (as I did for implementing it in lasagne). It looks, however, that they do the indexing in a different way than the original paper - for instance the pooling regions seem to be non-overlapping (that's not necessarily a problem). If you want to implement it as in the original paper, you can port the code from this pool request (for theano+lasagne) - it should be straightforward as Tensorflow seem to support all the necessary operations.

https://github.com/Lasagne/Lasagne/pull/799/

**Comment by Evan-Gao** [comment]
@luizgh @andrewgiessel I'm new to keras. It seems the spp pooling layer and RoI pooling layer in that keras implementation just support forward operation. Can it be used to train a new network via back propagation? 
I have seen some other code adding a new layer by implementing forward and backward separately (with cpu and gpu version). But I am searching for a easier way to implement a custom pooling layer.

**Comment by RikHeijdens** [comment]
I gave it a shot and tried to port the Lasagne implementation by @luizgh to TensorFlow:

```python
def max_pool_2d_nxn_regions(inputs, output_size: int, mode: str):
    """
    Performs a pooling operation that results in a fixed size:
    output_size x output_size.
    
    Used by spatial_pyramid_pool. Refer to appendix A in [1].
    
    Args:
        inputs: A 4D Tensor (B, H, W, C)
        output_size: The output size of the pooling operation.
        mode: The pooling mode {max, avg}
        
    Returns:
        A list of tensors, for each output bin.
        The list contains output_size * output_size elements, where
        each elment is a Tensor (N, C).
        
    References:
        [1] He, Kaiming et al (2015):
            Spatial Pyramid Pooling in Deep Convolutional Networks
            for Visual Recognition.
            https://arxiv.org/pdf/1406.4729.pdf.
            
    Ported from: https://github.com/luizgh/Lasagne/commit/c01e3d922a5712ca4c54617a15a794c23746ac8c
    """
    inputs_shape = tf.shape(inputs)
    h = tf.cast(tf.gather(inputs_shape, 1), tf.int32)
    w = tf.cast(tf.gather(inputs_shape, 2), tf.int32)
    
    if mode == 'max':
        pooling_op = tf.reduce_max
    elif mode == 'avg':
        pooling_op = tf.reduce_mean
    else:
        msg = "Mode must be either 'max' or 'avg'. Got '{0}'"
        raise ValueError(msg.format(mode))
        
    result = []
    n = output_size
    for row in range(output_size):
        for col in range(output_size):
            # start_h = floor(row / n * h)
            start_h = tf.cast(tf.floor(tf.mul(tf.divide(row, n), tf.cast(h, tf.float32))), tf.int32)
            # end_h = ceil((row + 1) / n * h)
            end_h = tf.cast(tf.ceil(tf.mul(tf.divide((row + 1), n), tf.cast(h, tf.float32))), tf.int32)
            # start_w = floor(col / n * w)
            start_w = tf.cast(tf.floor(tf.mul(tf.divide(col, n), tf.cast(w, tf.float32))), tf.int32)
            # end_w = ceil((col + 1) / n * w)
            end_w = tf.cast(tf.ceil(tf.mul(tf.divide((col + 1), n), tf.cast(w, tf.float32))), tf.int32)
            pooling_region = inputs[:, start_h:end_h, start_w:end_w, :]
            pool_result = pooling_op(pooling_region, axis=(1, 2))
            result.append(pool_result)
    return result

def spatial_pyramid_pool(inputs, dimensions=[2,1], mode='max', implementation='kaiming'):
    """
    Performs spatial pyramid pooling (SPP) over the input.
    It will turn a 2D input of arbitrary size into an output of fixed
    dimenson.
    Hence, the convlutional part of a DNN can be connected to a dense part
    with a fixed number of nodes even if the dimensions of the input
    image are unknown.
    
    The pooling is performed over :math:`l` pooling levels.
    Each pooling level :math:`i` will create :math:`M_i` output features.
    :math:`M_i` is given by :math:`n_i * n_i`, with :math:`n_i` as the number
    of pooling operations per dimension level :math:`i`.
    
    The length of the parameter dimensions is the level of the spatial pyramid.
    
    Args:
        inputs: A 4D Tensor (B, H, W, C).
        dimensions: The list of :math:`n_i`'s that define the output dimension
        of each pooling level :math:`i`. The length of dimensions is the level of
        the spatial pyramid.
        mode: Pooling mode 'max' or 'avg'.
        implementation: The implementation to use, either 'kaiming' or 'fast'.
        kamming is the original implementation from the paper, and supports variable
        sizes of input vectors, which fast does not support.
    
    Returns:
        A fixed length vector representing the inputs.
    
    Notes:
        SPP should be inserted between the convolutional part of a DNN and it's
        dense part. Convolutions can be used for arbitrary input dimensions, but
        the size of their output will depend on their input dimensions.
        Connecting the output of the convolutional to the dense part then
        usually demands us to fix the dimensons of the network's input.
        The spatial pyramid pooling layer, however, allows us to leave 
        the network input dimensions arbitrary. 
        The advantage over a global pooling layer is the added robustness 
        against object deformations due to the pooling on different scales.
        
    References:
        [1] He, Kaiming et al (2015):
            Spatial Pyramid Pooling in Deep Convolutional Networks
            for Visual Recognition.
            https://arxiv.org/pdf/1406.4729.pdf.
            
    Ported from: https://github.com/luizgh/Lasagne/commit/c01e3d922a5712ca4c54617a15a794c23746ac8c
    """
    pool_list = []
    if implementation == 'kaiming':
        for pool_dim in dimensions:
            pool_list += max_pool_2d_nxn_regions(inputs, pool_dim, mode)
    else:
        shape = inputs.get_shape().as_list()
        for d in dimensions:
            h = shape[1]
            w = shape[2]
            ph = np.ceil(h * 1.0 / d).astype(np.int32)
            pw = np.ceil(w * 1.0 / d).astype(np.int32)
            sh = np.floor(h * 1.0 / d + 1).astype(np.int32)
            sw = np.floor(w * 1.0 / d + 1).astype(np.int32)
            pool_result = tf.nn.max_pool(inputs,
                                         ksize=[1, ph, pw, 1], 
                                         strides=[1, sh, sw, 1],
                                         padding='SAME')
            pool_list.append(tf.reshape(pool_result, [shape[0], -1]))
    return tf.concat(1, pool_list)
```

**Comment by thewintersun** [comment]
mark

**Comment by thewintersun** [comment]
楼主，你这个问题，后来用tensorflow搞定了吗？

**Comment by Evan-Gao** [comment]
你好，目前我用tf.py_func实现的，利用tf自动求导的特性，没有写相应的backward函数。

**Comment by Google1234** [comment]
why SPP net cannot update  parameters below SPP  layer during training？

**Comment by yardstick17** [comment]
Made the PR for SPP implementation. https://github.com/tensorflow/tensorflow/pull/12852

**Comment by fourk-ty** [comment]
I tested RikHeijdens' code in tf1.6. 'tf.mul' should be changed as 'tf.multiply'.

**Comment by hbb21st** [comment]
Hello, have you realize that with different size of input  images even though output number is same, how you unify the input layer? My point is during training, if I set sess.graph.finalize(), when switch to new image training I will get error Graph is finalized and cannot be modified. How can we keep Graph consistent during training different size images.

**Comment by Maheshiitmandi** [comment]
> @karlTUM, you can try the code below:
> 
> ```
> def spp_layer2(input_, levels=[2, 1], name = 'SPP_layer'):
>     '''Multiple Level SPP layer.
>        Works for levels=[1, 2, 3, 6].'''
>     shape = input_.get_shape().as_list()
>     with tf.variable_scope(name):
>         pool_outputs = []
>         for l in levels:
>             pool = tf.nn.max_pool(input_, ksize=[1, np.ceil(shape[1] * 1. / l).astype(np.int32), np.ceil(shape[2] * 1. / l).astype(np.int32), 1], 
>                                       strides=[1, np.floor(shape[1] * 1. / l + 1).astype(np.int32), np.floor(shape[2] * 1. / l + 1), 1], 
>                                       padding='SAME')
>             print "Pool Level {:}: shape {:}".format(l, pool.get_shape().as_list())
>             pool_outputs.append(tf.reshape(pool, [shape[0], -1]))
>         spp_pool = tf.concat(1, pool_outputs)
>     return spp_pool
> ```
> 
> I haven't extensively tested it, but it outputs a vector of the same length (in case of `levels=[1, 2, 3, 6]`): `50=[1x1 + 2x2 + 3x3 + 6x6]x(channels)` for every input with each spatial dimension more (or equal) than `36=6x6`.

Lets say input is like a placeholder of unknown shape eg. input_= tf.placholder(tf.float32, shape=(batch_size, None, 3,1)) 
so shape[1]/n will not work. If you have any idea please share.

**Comment by ngragaei** [comment]
@RikHeijdens How can i use it instead of Maxpooling?
