### ISSUE TITLE
Support of protobuf 4.22 for tensorflow-macos

### ISSUE THREAD

**Issue by MuppetJack** [tensorflow/tensorflow#60118]
I am using tensorflow-macos and it is raising an issue with protobuf 4.22 compatibility. I need that more recent version of protobuf for other Python libraries.

**Comment by pat749** [comment]
If you need to use a more recent version of protobuf than the one provided by tensorflow-macos, you can try installing it separately and then setting the **PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION** environment variable to **python** before importing tensorflow.

**Comment by sushreebarsa** [comment]
@MuppetJack Thank you for raising an issue!
Before using protocol buffers on your system, you need to set up the Protocol Buffers compiler or protoc. 
For using the most recent version of protobuf, you may refer to this [link](https://github.com/protocolbuffers/protobuf/releases) and set up the compatible python version in you environment. 
Thank you!

**Comment by MuppetJack** [comment]
Hi,
Thank you for the tips, I will try and update the issue if solved.

FYI, I separately solved my immediate problem with a branch of the other incompatible library... So no more urgency on that one for me.

**Comment by sushreebarsa** [comment]
@MuppetJack Thank you for the response!
Could you please confirm if the issue has been resolved and close the issue?
Thank you!

**Comment by gaurav00700** [comment]
Hi, 
I also need higher version of Protobuf for onnx package. But tensorflow-macos requires lower version of protobuf. 
How to deal with such problem. I want to install tensorflow and onnx in same python environment.

**Comment by MuppetJack** [comment]
Thank you @pat749! Your solution worked for me.
As I also solved the incompatibility issue with the other library,  I close the issue.

@gaurav00700, you should try the proposed solutions and reopen if not solved.
