### ISSUE TITLE
tf.raw_ops.AssignSubVariableOp crash with abortion

### ISSUE THREAD

**Issue by trickiwoo** [tensorflow/tensorflow#60122]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.13.0-dev20230208

### Custom Code

Yes

### Current Behaviour?

```shell
tf.raw_ops.AssignSubVariableOp crash with abortion
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.python.eager import context

input1 = tf.raw_ops.VarHandleOp(dtype=tf.int32, shape=[2, 3], shared_name=context.anonymous_name())
input2 = tf.constant([],dtype=tf.float32)

tf.raw_ops.AssignSubVariableOp(resource=input1, value=input2)
```

### Relevant log output

```shell
2023-03-26 21:58:20.336369: F tensorflow/core/framework/tensor.cc:770] Check failed: dtype() == expected_dtype (3 vs. 1) float expected, got int32
Aborted (core dumped)
```
</details>

**Comment by trickiwoo** [comment]
Related: #60121 https://github.com/tensorflow/tensorflow/issues/60121

**Comment by sushreebarsa** [comment]
@trickiwoo Could you please refer to this [comment](https://github.com/tensorflow/tensorflow/issues/60121#issuecomment-1485230826)?
Thank you!
