### ISSUE TITLE
tf.raw_ops.AssignAddVariableOp  crash with abortion

### ISSUE THREAD

**Issue by trickiwoo** [tensorflow/tensorflow#60121]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.13.0-dev20230208

### Custom Code

Yes

### Python version

3.9

### Current Behaviour?

```shell
tf.raw_ops.AssignAddVariableOp  crash with abortion
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.python.eager import context

input1 = tf.raw_ops.VarHandleOp(dtype=tf.int32, shape=[2, 3], shared_name=context.anonymous_name())
input2 = tf.constant([],dtype=tf.float32)

tf.raw_ops.AssignAddVariableOp(resource=input1, value=input2)
```

### Relevant log output

```shell
2023-03-26 18:39:30.729731: F tensorflow/core/framework/tensor.cc:770] Check failed: dtype() == expected_dtype (3 vs. 1) float expected, got int32
Aborted (core dumped
```
</details>

**Comment by mihaimaruseac** [comment]
https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md#reporting-vulnerabilities

(if you want to be credited in advisories and Google VRP board)

Also, responsible disclosure.

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.11, v2.12 and tf-nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/363047ca6136212ebfc5820ba7525242/untitled1055.ipynb).

**Comment by trickiwoo** [comment]
@mihaimaruseac 
Thank you for the great suggestion! I have reported this and other crash issues to the Google's Bug Hunting project.

**Comment by TheCrott** [comment]
@trickiwoo what fuzzer you used to find this issue and another crashes?

**Comment by tilakrayal** [comment]
@trickiwoo,
I tried to execute the provided code on TensorFlow version 2.17, and observed that the anticipated error was correctly produced. However, in previous versions, the code encountered a check failure that resulted in a crash.
Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/5352b3dbd45dc1ef3e935bdacf7e49f1/untitled2172.ipynb). Thank you!

**Comment by mihaimaruseac** [comment]
I think this got resolved and we can close
