### ISSUE TITLE
GPU is not supported on qualcomm adreno 702 GPU device. How to enable that?

### ISSUE THREAD

**Issue by megleo** [tensorflow/tensorflow#60127]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 10
- TensorFlow installed from (source or binary): source
- TensorFlow version (or github SHA if from source):2.9.2

**GPU is not supported on qualcomm adreno 702 GPU device.
    On qualcomm adreno 702 GPU device,[ the tensorflow example android app](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android_java)  can not work and it give us the toast "GPU is not supported on this device.".
    Look into the tensorflow source code , and notice that int the tensorflow source code path tensorflow_src/tensorflow/lite/experimental/acceleration/compatibility,that give a way to add GPU device to make GPU work.**

**1. Following the tensorflow_src/tensorflow/lite/experimental/acceleration/compatibility/README.md, but it can not well on GPU, and the android app will crash. We do not know how to resolve this ?**

Very thanks for your reply.

**Comment by synandi** [comment]
Hi @megleo, 

Hexagon is a specialized processor designed by Qualcomm for mobile devices. TensorFlow Lite supports Hexagon delegate, which can be used to accelerate the inference process on devices that do not support GPUs or have limited GPU capabilities. Please refer to this document on [Hexagon Delegate](https://www.tensorflow.org/lite/android/delegates/hexagon). Thank you!

**Comment by megleo** [comment]
@synandi 
Thanks for your reply.
 On my embedded device, there is no  DSP device , but  a Andreno GPU. So we expect to use GPU on our embedded devices.By using google example android app[ image classification](https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android_java) , it shown that "GPU is not supportted". So we just wonder that how to enable GPU using the following method but not work.

1.  In the [README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/acceleration/compatibility/README.md),  it seems give us the method to add  gpu_compatibility.  we follow it , but get the gpu_compatibility.bin is about 117Kb, which is more huge than the original one, and it may be Converted failed.

Thanks
BRs
