### ISSUE TITLE
tf.raw_ops.ResourceScatterDiv crash with abortion

### ISSUE THREAD

**Issue by trickiwoo** [tensorflow/tensorflow#60123]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.13.0-dev20230208

### Custom Code

Yes

### CUDA/cuDNN version

8.2.4

### Current Behaviour?

```shell
2.13.0-dev20230208
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.python.eager import context

input1 = tf.raw_ops.VarHandleOp(dtype=tf.int32, shape=[2, 3], shared_name=context.anonymous_name())
input2 = tf.constant([],dtype=tf.float32)
output = tf.raw_ops.ResourceScatterDiv(resource=input1, indices=[0], updates=input2)
```

### Relevant log output

```shell
2023-03-26 22:11:23.135344: F tensorflow/core/framework/tensor.cc:770] Check failed: dtype() == expected_dtype (3 vs. 1) float expected, got int32
Aborted (core dumped)
```
</details>

**Comment by tilakrayal** [comment]
@trickiwoo,
There was a PR that was raised internally and the developer is working on that issue. Once it is resolved we will update the result here. https://b.corp.google.com/issues/275707925 Thank you!

**Comment by tilakrayal** [comment]
@trickiwoo,
I tried to execute the mentioned code on tf-nightly and the code was executed with the error and also observed that the crash did not happen. And the same has been in the respective files. Kindly find the [gist](https://colab.research.google.com/gist/tilakrayal/4fd326ab31f4f78139c0671d44c838ff/untitled1683.ipynb) for the [reference](https://colab.research.google.com/gist/tilakrayal/a34b671e2e2178157d4339a683f1fd2e/untitled1684.ipynb).

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/quantize_and_dequantize_op.cc#L22

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/resource_variable_ops.cc#L1120

```
// Check data type of update and resource to scatter.
const DataType update_dtype = c->input(2).dtype();
OP_REQUIRES(c, v->tensor()->dtype() == update_dtype,
errors::InvalidArgument(
"DType of scatter resource and updates does not match."));
```

Thank you!
