### ISSUE TITLE
Issue in TF Docs and it's tools with dataclasses module in Python 3.6 and earlier

### ISSUE THREAD

**Issue by eslam69** [tensorflow/tensorflow#60137]
Currently, the TensorFlow documentation tools requires using the `dataclasses` module. However, the `dataclasses` module is not included in the standard library in Python 3.6 and earlier, which can cause compatibility issues for users of these versions of Python.
https://github.com/tensorflow/docs/blob/master/setup.py#L36:L38
```python
# Dataclasses is in-built from py >=3.7. This version is a backport for py 3.6.
if (sys.version_info.major, sys.version_info.minor) == (3, 6):
  REQUIRED_PKGS.append('dataclasses')
```
But in the **nbfmt** tool  the `notebook_utils.py` file,
https://github.com/tensorflow/docs/blob/master/tools/tensorflow_docs/tools/nbfmt/notebook_utils.py#L119:L124
```python
@dataclasses.dataclass
class CellCopyStats:
  processed_cells: int = 0
  updated_cells: int = 0
  unmatched_target_cells: list[str] = dataclasses.field(default_factory=list)
  unmatched_source_cells: list[str] = dataclasses.field(default_factory=list)
  out_of_order_target_cells: list[str] = dataclasses.field(default_factory=list)
```
 `list` is used instead of the `typing.List` which will cause `TypeError: 'type' object is not subscriptable`, I think `typing.List` should be used to ensure backward compatibility.
 
To avoid these issues, the documentation should :
1.  use the `typing.List` class instead of `list` to ensure backward compatibility with older versions of Python.
2.  Require the installation of the `dataclasses` package for users of Python 3.6 and earlier, instead of requiring it for python 3.6 only, like the following: 
```python 
import sys

if sys.version_info < (3, 7):
    REQUIRED_PKGS.append('dataclasses')
```
**I'm ready to start fixing it in a PR.**

**Comment by sushreebarsa** [comment]
@eslam69 Thank you for reporting this issue!
Please feel free to raise a PR to fix this. Thank you!

**Comment by MarkDaoust** [comment]
Sorry about the miscommunication, but TensorFlow currently only suppoorts 3.8+, soon 3.9+.

I'll update the doc-tools setup.py to make that clear.
