### ISSUE TITLE
tf.raw_ops.ResourceScatterUpdate crash with abortion

### ISSUE THREAD

**Issue by trickiwoo** [tensorflow/tensorflow#60147]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.13.0-dev20230208

### Custom Code

Yes

### Current Behaviour?

```shell
tf.raw_ops.ResourceScatterUpdate crash with abortion
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

init = np.random.rand(20)
update = np.random.rand(20)

resource = tf.Variable(init, dtype=tf.float32)
resource_var = resource.handle
indices = np.array([1, 3, 5], dtype=np.int32)
tf.raw_ops.ResourceScatterUpdate(resource=resource_var, indices=indices, updates=update)
```

### Relevant log output

```shell
2023-03-28 11:39:22.735062: F tensorflow/core/framework/tensor.cc:770] Check failed: dtype() == expected_dtype (1 vs. 2) double expected, got float
Aborted (core dumped)
```
</details>

**Comment by Adesoji1** [comment]
Try this below  
import tensorflow as tf
import numpy as np

init = np.random.rand(20).astype(np.float32)  # Convert to float32
update = np.random.rand(20).astype(np.float32)  # Convert to float32

resource = tf.Variable(init, dtype=tf.float32)
resource_var = resource.handle
indices = np.array([1, 3, 5], dtype=np.int32)
tf.raw_ops.ResourceScatterUpdate(resource=resource_var, indices=indices, updates=update)

By setting the dtype of 'init' and 'update' to float32, this will ensure that the 'resource' tensor and 'update' tensor have the same dtype, and the issue should be resolved.

**Comment by sushreebarsa** [comment]
@trickiwoo Could you please let us know if the above workaround worked for you?
Thank you!

**Comment by FuzzGPT** [comment]
Thanks for providing the workaround for this issue. However, in my understanding, crashes like this seem to be a vulnerability according to https://github.com/tensorflow/tensorflow/issues/60121#issuecomment-1485230826, so I have also reported this bug to the Google OSS VRP program.

**Comment by trickiwoo** [comment]
Thanks for providing the workaround. However, in my understanding, crashes like this seem to be a vulnerability according to https://github.com/tensorflow/tensorflow/issues/60121#issuecomment-1485230826

**Comment by sachinprasadhs** [comment]
I was able to reproduce the issue in Tensorflow 2.12, please find the attached Gist [here](https://gist.github.com/sachinprasadhs/028763a39c0f83e59f6a5ba2807fef8a). Thanks!

**Comment by tilakrayal** [comment]
@trickiwoo,
I tried to execute the mentioned code on tf-nightly and the code was executed with the error and also observed that the crash did not happen. And the same has been in the respective files. Kindly find the [gist](https://colab.research.google.com/gist/tilakrayal/58a438e3530de19720ef3cac0201383f/untitled1681.ipynb) for the [reference](https://colab.research.google.com/gist/tilakrayal/64c329a1db61dd97eaaffed5e04e2f54/untitled1682.ipynb).

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/quantize_and_dequantize_op.cc#L22 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/resource_variable_ops.cc#L1120

>  // Check data type of update and resource to scatter.
>     const DataType update_dtype = c->input(2).dtype();
>     OP_REQUIRES(c, v->tensor()->dtype() == update_dtype,
>                 errors::InvalidArgument(
>                     "DType of scatter resource and updates does not match."));

Thank you!
