### ISSUE TITLE
GPU install error 

### ISSUE THREAD

**Issue by sparrow84001** [tensorflow/tensorflow#60144]
I am using wsl2 
GPU Quadro p1000

When installing TensorFlow 2.12 through pip and conda (https://www.tensorflow.org/install/pip) after installing that build was cpu (onednn) don't use cuda (cudnn) and the error said 1) Don't have cuda driver 2)Don't open tensorrt lib 

I have tried 3 times but every time build cpu based not gpu based.

**Comment by tiruk007** [comment]
@sparrow84001 
Could you please make sure to follow the instructions mentioned [here](https://www.tensorflow.org/install/pip#windows-wsl2) and check the [tested build configuration](https://www.tensorflow.org/install/source#gpu) as well. I was able to find the GPU. Please find the below screenshots for reference:
[Screenshot1](https://user-images.githubusercontent.com/111861663/228694081-53a0ae08-b249-4e8c-a7bb-933bbbd8e691.png)
[Screenshot2](https://user-images.githubusercontent.com/111861663/228694091-7d657bfa-61ce-401a-89e3-78b06d680541.png)
[Screenshot3](https://user-images.githubusercontent.com/111861663/228694268-94bed77a-53ab-414a-aeba-113f93ed7bc7.png)
[Screenshot4](https://user-images.githubusercontent.com/111861663/228694279-7faa8db8-24a8-4215-984a-79b8f01a89a7.png)

Thank you !

**Comment by sparrow84001** [comment]
Thanks for your reply.

Yea, that's the same msg as your **Screenshot4**

**Comment by tilakrayal** [comment]
@sparrow84001,
Apologies for the delay. Could you please confirm whether you are facing the same issue in the latest TensorFlow. Also looks  like there is another issue raised for the installation issue where it was assigned to the Developer team. Please feel free to move this issue to closed status, if my understanding is correct. Thank you!
