### ISSUE TITLE
TensorArray.gather crash with Segmentation fault

### ISSUE THREAD

**Issue by trickiwoo** [tensorflow/tensorflow#60148]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.13.0-dev20230208

### Custom Code

Yes

### Current Behaviour?

```shell
TensorArray.gather crash with Segmentation fault
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

tf = tf.compat.v2
tf.enable_v2_behavior()

@tf.function
def foo():
    ta = tf.TensorArray(dtype=tf.int32, size=0, dynamic_size=True)
    ta.write(0, tf.constant(0))
    return ta.gather([0])

foo()
```

### Relevant log output

```shell
Segmentation fault (core dumped)
```
</details>

**Comment by pat749** [comment]
The **enable_v2_behavior()** function was introduced in TensorFlow 2.0 and is no longer needed in TensorFlow 2.0 and later versions.

**Comment by Ruparani777** [comment]
enable_v2_behavior () is called or # 2) the TF2_BEHAVIOR=1 environment variable is set.

**Comment by synandi** [comment]
Hi @trickiwoo, I was able to replicate the issue using  TF-nightly(2.13.0-dev20230208). Please find the screenshot below.
![image](https://user-images.githubusercontent.com/98147397/228454806-318919b0-b0a4-4ca6-91bc-5012a2e7ccea.png)
Thank you!

**Comment by trickiwoo** [comment]
Thanks @pat749 and @Ruparani777 for pointing out the issue! I checked and found that `enable_v2_behavior` is not needed to trigger this bug, here is the minimized code that triggers Segmentation fault:
```
import tensorflow as tf

@tf.function
def foo():
    ta = tf.TensorArray(dtype=tf.int32, size=0, dynamic_size=True)
    ta.write(0, tf.constant(0))
    return ta.gather([0])

foo()
```
Output:
```
Segmentation fault (core dumped)
```

**Comment by Ruparani777** [comment]
Use a different version of the library: If the segmentation fault is caused by a bug in a library, then using a different version of the library can sometimes help to remove the error.
