### ISSUE TITLE
Tensorflow cann't detect or use CUDA but pytorch can in windows 11 and python 3.9.10

### ISSUE THREAD

**Issue by bluesteven** [tensorflow/tensorflow#60156]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Windows 11

### Python version

3.9.10

### CUDA/cuDNN version

11.6r11.6/8.6

### Current Behaviour?

```shell
import tensorflow as tf
print(tf.test.is_build_with_cuda()) #  false is returned
tf.config.list_physical_devices('GPU') # [] is returned

import torch
torch.cuda.is_available() # true is returned
print(torch.device("cuda:0" if torch.cuda.is_available() else "cpu")) #'cuda:0' is returned
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
print(tf.test.is_build_with_cuda()) # result show false
tf.config.list_physical_devices('GPU') # result show []
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@bluesteven 
Beginning with Tensorflow **2.11**, support for GPU on native windows has changed. You will need to install TensorFlow in **WSL2** or install tensorflow-cpu within windows machines or try the **TensorFlow-DirectML-Plugin**. 
https://www.tensorflow.org/install/pip#windows-native
https://www.tensorflow.org/install/pip#windows-wsl2

Going forward, Tensorflow support will be developed and maintained by Tensorflow Official build collaborators (Intel, AWS, ARM, linaro etc.). For more details please take a look at this  [link].(https://blog.tensorflow.org/2022/09/announcing-tensorflow-official-build-collaborators.html)

Thank you !
