### ISSUE TITLE
initialization of local variables missing in example: fully_connected_preloaded.py

### ISSUE THREAD

**Issue by abred** [tensorflow/tensorflow#6015]
change introduced in this commit: 
https://github.com/tensorflow/tensorflow/commit/cbd3cacfb73bbea912b9d01c2540187684f751a7
so, not sure if the other files have to be changed as well

`init_op = tf.global_variables_initializer()`
->
`init_op = tf.group(tf.global_variables_initializer(),
                       tf.local_variables_initializer())`

without the change the loop is exited immediately and this error occus:

> tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs
	 [[Node: input/input_producer/input_producer/fraction_of_32_full/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, _class=["loc:@input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs"], limit=2, _device="/job:localhost/replica:0/task:0/cpu:0"](input/input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs)]]

**Comment by jart** [comment]
Ping @ilblackdragon

**Comment by MarkDaoust** [comment]
This is fixed.
