### ISSUE TITLE
How to solve the backpropagation problem of tf.signal.rfft?

### ISSUE THREAD

**Issue by Evan-0715** [tensorflow/tensorflow#60163]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf 2.11

### Custom Code

Yes

### OS Platform and Distribution

Windows 10

### Python version

3.9

### Current Behaviour?

```shell
I x wanted to implement the Hilbert transform in the model built by tensorflowd, but I found no callable API. so I implemented it myself using tf.signal.rfft and tf.signal.ifft. However, when I was training, I found the following error reported:
LookupError: gradient registry has no entry for: RFFT3D
I think it may be that tensorflow has not defined the corresponding backpropagation method for rfft3d yet. I want to provide my code train.py  &  model.py
```

### Standalone code to reproduce the issue

```
def hilbert_transform(x, N=None, axis=-1):
    if x.dtype == tf.complex64 or x.dtype == tf.complex128:
        raise ValueError("x must be real.")
    if N is None:
        N = x.shape[axis]
    if N <= 0:
        raise ValueError("N must be positive.")
    x_br = tf.signal.rfft3d(x[:, :, :1])
    x_bi = tf.signal.rfft3d(x[:, :, 1:])
    x_complex = concatenate([x_br, x_bi], axis=-1)

    h = np.zeros(N)
    if N % 2 == 0:
        h[0] = h[N // 2] = 1
        h[1:N // 2] = 2
    else:
        h[0] = 1
        h[1:(N + 1) // 2] = 2
    if x.shape.ndims > 1:
        ind = [tf.newaxis] * x.shape.ndims
        ind[axis] = slice(None)
        h = h[tuple(ind)]
    x_complex_h = x_complex * h
    x_bj = tf.signal.ifft3d(x_complex_h[:, :, :1])
    x_bk = tf.signal.ifft3d(x_complex_h[:, :, 1:])
    x_hilbert = concatenate([tf.math.imag(x_bj), tf.math.imag(x_bk)], axis=-1)
    return x_hilbert
```

### Relevant log output

_No response_</details>

**Comment by synandi** [comment]
Hi @Evan-0715, the code provided above does not raise any error. Please find the gist [here](https://colab.sandbox.google.com/gist/synandi/03334bfe2386f6dc345e3e063a7d7d57/60163.ipynb). Kindly share complete reproducible code so that we can replicate the issue from our end. Thank you!

**Comment by synandi** [comment]
@Evan-0715 Thank you for sharing the complete reproducible code. I was able to replicate the error in Colab using TF 2.12 and tf-nightly. Kindly refer to this [gist-2.12](https://colab.sandbox.google.com/gist/synandi/57f3d2e6c05981c76d519d44f334ef59/60163_3.ipynb) and [tf-nightly](https://colab.sandbox.google.com/gist/synandi/f9aa87c44146cdaee92ccf7e739fab0a/60163_nightly.ipynb). Thank you!

Hi @sachinprasadhs, Could you please look into this issue ? Thank you!

**Comment by Adesoji1** [comment]
@Evan-0715 You are right that TensorFlow might not have implemented gradients for tf.signal.rfft3d. One way to resolve this is to replace the rfft3d and ifft3d functions with their 1D counterparts, rfft and irfft, which have gradients defined.

Here's the modified hilbert_transform function using tf.signal.rfft and tf.signal.irfft:  

def hilbert_transform(x, N=None, axis=-1):
    if x.dtype == tf.complex64 or x.dtype == tf.complex128:
        raise ValueError("x must be real.")
    if N is None:
        N = x.shape[axis]
    if N <= 0:
        raise ValueError("N must be positive.")
    x_br = tf.signal.rfft(x[:, :, :1])
    x_bi = tf.signal.rfft(x[:, :, 1:])
    x_complex = tf.concat([x_br, x_bi], axis=-1)

    h = np.zeros(N)
    if N % 2 == 0:
        h[0] = h[N // 2] = 1
        h[1:N // 2] = 2
    else:
        h[0] = 1
        h[1:(N + 1) // 2] = 2
    if x.shape.ndims > 1:
        ind = [tf.newaxis] * x.shape.ndims
        ind[axis] = slice(None)
        h = h[tuple(ind)]
    x_complex_h = x_complex * h
    x_bj = tf.signal.irfft(x_complex_h[:, :, :1])
    x_bk = tf.signal.irfft(x_complex_h[:, :, 1:])
    x_hilbert = tf.concat([tf.math.imag(x_bj), tf.math.imag(x_bk)], axis=-1)
    return x_hilbert

However, there is another issue in your code. You are creating a new instance of the model at every training step, which will reset the model's weights and gradients. You should create an instance of the model and pass it as an argument to the train_step function.

Here's the modified train_step function:

@tf.function
def train_step(model, inputs, targets):
    with tf.GradientTape() as tape:
        predictions = model(inputs)
        loss = loss_fn(targets, predictions)
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
    return loss

And you should create the model outside the loop:
x = tf.random.normal((1, 64, 64, 3))
y = tf.random.normal((1, 64, 64, 3))

model = RQIUNet()

for i in range(10):
    loss = train_step(model, x, y)
    print(f"Step {i}, Loss: {loss:.4f}")


With these changes, the code should run without the LookupError and should train the model correctly

**Comment by Evan-0715** [comment]
Thanks a lot! @synandi @Adesoji1 It really helped me to implement the Hilbert transform. If a input has tensor shape (b,h,w,2), it can be considered as a complex signal. Tensorflow's Hilbert transform code for its implementation is:
```
def hilbert_transform(x, N=None, axis=-1):
    ##Constructing complex number
    x_complex = tf.complex(x[:, :, :1], x[:, :, 1:])
    if x_complex.dtype != tf.complex64 and x_complex.dtype != tf.complex128:
        raise ValueError("x must be complex.")
    if N is None:
        N = x.shape[axis]
    if N <= 0:
        raise ValueError("N must be positive.")
    x_t = transpose(x_complex, perm=[0, 2, 1])
    x_f = tf.signal.fft(x_t)
    x_f = transpose(x_f, perm=[0, 2, 1])

    h = np.zeros(N)
    if N % 2 == 0:
        h[0] = h[N // 2] = 1
        h[1:N // 2] = 2
    else:
        h[0] = 1
        h[1:(N + 1) // 2] = 2
    if x.shape.ndims > 1:
        ind = [tf.newaxis] * x.shape.ndims
        ind[axis] = slice(None)
        h = h[tuple(ind)]
    x_f_h = x_f * h
    x_f = transpose(x_f_h, perm=[0, 2, 1])
    x_hilbert = tf.signal.ifft(x_f)
    x_hilbert = transpose(x_hilbert, perm=[0, 2, 1])
    x_hilbert = concatenate([tf.math.imag(x_hilbert), tf.math.real(x_hilbert)], axis=-1)
    return x_hilbert
```
It will return the output of a complex linear time-invariant system which has the shape (b,h,w,2). Thanks again!

**Comment by Evan-0715** [comment]
In addition, this can be added to the network for forward and backward propagation.
