### ISSUE TITLE
Compilation times double after commit removing distinct_host_configuration=false option

### ISSUE THREAD

**Issue by nluehr** [tensorflow/tensorflow#60167]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

master at commit bdacdadc5

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.8

### Bazel version

5.3.0

### GCC/Compiler version

Ubuntu 9.4.0-1ubuntu1~20.04.1

### CUDA/cuDNN version

CUDA 11.8, CUDNN 8.6

### GPU model and memory

N/A

### Current Behaviour?

```shell
Since commit [fa2a678486](https://github.com/tensorflow/tensorflow/commit/fa2a6784860c40e3b189f21208154b851af2fee8) removed the `--distinct_host_configuration=false` option build times have doubled.

TensorFlow builds now take 114 minutes on a machine with dual 20-core CPUs.
Disabling distinct host configuration, the same build takes 62 minutes.

This significantly increases the stress on build and test CIs as well as reducing developer productivity.
```

### Standalone code to reproduce the issue

```shell
I'm building using the sig-build docker environment as documented [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/tf_sig_build_dockerfiles).
```

### Relevant log output

_No response_</details>

**Comment by meteorcloudy** [comment]
Related issue is https://github.com/bazelbuild/bazel/issues/14848#issuecomment-1183500102

**Comment by meteorcloudy** [comment]
I'll send a fix for this soon

**Comment by meteorcloudy** [comment]
@nluehr Can you check if https://github.com/tensorflow/tensorflow/pull/60180 fixes the performance regression for you?

**Comment by nluehr** [comment]
I confirmed that with the fix from https://github.com/tensorflow/tensorflow/pull/60180, building takes 70 minutes, compared to 114 minutes without the fix and 62 minutes with distinct_host_configuration=false.
