### ISSUE TITLE
tf.estimator.BestExporter / tf.compat.v1.gfile.Rename not working for saved_models in S3

### ISSUE THREAD

**Issue by j99ca** [tensorflow/tensorflow#60165]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf 2.12

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04.2

### Python version

3.10

### Current Behaviour?

```shell
When either using tf.estimator.BestExporter or using tf.compat.v1.gfile.Rename directly when the source and destination are folders in S3, an error is thrown. This error seems to go back to Tensorflow 2.6 when the S3 support was moved into tensorflow_io. In Tensorflow 2.5 this behaves properly. It also functions properly if the folders are local.

Right now if you are using Tensorflow >= 2.6 and using a tf.estimator.BestExporter with the output being written to S3, an exception is thrown
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import tensorflow_io as tfio

SOURCE_DIR = 's3://.../best_exporter/1'
DEST_DIR = 's3://.../best_exporter/old'

tf.compat.v1.gfile.Rename(SOURCE_DIR, DEST_DIR)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/j99ca/.config/JetBrains/PyCharm2022.3/scratches/tf2_s3_rename_test.py", line 14, in <module>
    tf.compat.v1.gfile.Rename(SOURCE_DIR, DEST_DIR)
  File "/home/j99ca/venvs/tf2-12/lib/python3.10/site-packages/tensorflow/python/lib/io/file_io.py", line 606, in rename
    rename_v2(oldname, newname, overwrite)
  File "/home/j99ca/venvs/tf2-12/lib/python3.10/site-packages/tensorflow/python/lib/io/file_io.py", line 622, in rename_v2
    _pywrap_file_io.RenameFile(
tensorflow.python.framework.errors_impl.FailedPreconditionError: Source is a directory or empty file
```
</details>

**Comment by sachinprasadhs** [comment]
Hi, Estimator `tf.estimator.BestExporter` is deprecated from Tensorflow 2.12 since it uses Tensorflow V1 behavior.
Could you please migrate from Estimator to Keras API which will enable you to perform the tasks such as [model building](https://www.tensorflow.org/guide/keras/custom_layers_and_models), gradient application, [training](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit), evaluation, and prediction.
Refer Migration guide here https://www.tensorflow.org/guide/migrate/migrating_estimator for more details. Thanks!

**Comment by j99ca** [comment]
The issue persists with the tf.io.gfile.rename function. We use this function for various tasks. It worked before Tensorflow 2.6.  According to the documentation, it should still work. However it is not working with S3 folders, as you can see in the example code above

**Comment by sachinprasadhs** [comment]
Thanks for pointing out, 
`tf.compat.v1.gfile` is uses Tensorflow 1 behavior and usually we do not make any changes to the legacy code.
Alternative to that from Tensorflow 2 is  `tf.io.gfile.rename` https://www.tensorflow.org/api_docs/python/tf/io/gfile/rename.
Could you please use the above API and let us know if you still face an error. Thanks!

**Comment by j99ca** [comment]
Any resolution on this issue? The documentation states that tf.io.gfile.rename should work with directories. Again, this issue seems to be for S3 even with importing tensorflow_io. Local files seem to work. I haven't tried gcs or any other cloud provider. Other operations seem to work fine like checking if the folder exists in S3 with tf.io.gfile.exists

**Comment by j99ca** [comment]
@sachinprasadhs is there any progress for this issue?
