### ISSUE TITLE
TensorFlow cannot use GPU.

### ISSUE THREAD

**Issue by NoteDancing** [tensorflow/tensorflow#60172]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf 2.12.0

### Custom Code

Yes

### OS Platform and Distribution

Windows 11

### Python version

3.11.2

### CUDA/cuDNN version

11.8/8.6

### Current Behaviour?

```shell
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
tf.config.list_physical_devices('GPU')
tf.config.list_physical_devices()
Num GPUs Available:  0
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]
```

### Standalone code to reproduce the issue

```shell
I install CUDA 11.8 and CUDNN 8.6, but TensorFlow cannot use GPU.I also set %PATH% variable.
```

### Relevant log output

_No response_</details>

**Comment by pat749** [comment]
```
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
tf.config.list_physical_devices('GPU')
tf.config.list_physical_devices()

```
Output :
```
Num GPUs Available:  1
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

```
When I running this code I was getting true output . Please check if It is possible that another process is already using the GPU, preventing TensorFlow from accessing it. Check if any other GPU-intensive programs are running on your system and close them.

**Comment by synandi** [comment]
Hi @NoteDancing, 
As per the official Tensorflow documenation,
> TensorFlow 2.10 was the last TensorFlow release that supported GPU on native-Windows. Starting with TensorFlow 2.11, you will need to install [TensorFlow in WSL2](https://tensorflow.org/install/pip#windows-wsl2), or install tensorflow-cpu and, optionally, try the [TensorFlow-DirectML-Plugin](https://github.com/microsoft/tensorflow-directml-plugin#tensorflow-directml-plugin-)

Also note that,
> TensorFlow with GPU access is supported for WSL2 on Windows 10 19044 or higher.

 Kindly refer to the [official documentation](https://www.tensorflow.org/install/pip#windows-wsl2) for more information. Thank you!

**Comment by NoteDancing** [comment]
@synandi Tensorflow 2.12.0 Can't use GPU on Windows 11?

**Comment by synandi** [comment]
> @synandi Tensorflow 2.12.0 Can't use GPU on Windows 11?

@NoteDancing Yes. In order to leverage GPU with TensorFlow 2.12, you must install TensorFlow in WSL2 or you can also try the try the [TensorFlow-DirectML-Plugin](https://github.com/microsoft/tensorflow-directml-plugin#tensorflow-directml-plugin-). Thank you!

**Comment by NoteDancing** [comment]
@synandi Does tensorflow-directml-plugin make tensorflow 2.12.0 use GPU on windows 11?Thank you!

**Comment by synandi** [comment]
> @synandi Does tensorflow-directml-plugin make tensorflow 2.12.0 use GPU on windows 11?Thank you!

@NoteDancing  Yes. Kindly refer to the [TensorFlow-DirectML-Plugin](https://github.com/microsoft/tensorflow-directml-plugin#tensorflow-directml-plugin-). Thank you!

**Comment by NoteDancing** [comment]
@synandi I try pip install tensorflow-directml-plugin, but I get error.
ERROR: Could not find a version that satisfies the requirement tensorflow-directml-plugin (from versions: none)
ERROR: No matching distribution found for tensorflow-directml-plugin
