### ISSUE TITLE
Tensorflow build error with v2.12.0

### ISSUE THREAD

**Issue by alien2327** [tensorflow/tensorflow#60187]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.12.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 22.04 (Docker)

### Python version

3.10.6

### Bazel version

5.3.0

### CUDA/cuDNN version

11.8

### Current Behaviour?

```shell
When I try to build tensorflow from source, error occured by two file.

- tensorflow/compiler/tf2tensorrt/common/utils.cc:209:10
- tensorflow/compiler/tf2tensorrt/convert/weights.cc:61:10

Since there was no default statement in switch, I just add something like, default: break; and the error has gone.

It is okay to add just defualt and do nothing? or should I use some flags that makes compiler ignore w/o-switch?

Thanks!
```

### Standalone code to reproduce the issue

```shell
Same above.
```

### Relevant log output

```shell
ERROR: /tmp/tensorflow/tensorflow/compiler/tf2tensorrt/BUILD:565:16: Compiling tensorflow/compiler/tf2tensorrt/convert/weights.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/tensorflow/compiler/tf2tensorrt/_objs/trt_weights/weights.pic.d ... (remaining 180 arguments skipped)
tensorflow/compiler/tf2tensorrt/convert/weights.cc: In member function ‘size_t tensorflow::tensorrt::convert::TRT_ShapedWeights::size_bytes() const’:
tensorflow/compiler/tf2tensorrt/convert/weights.cc:61:10: error: enumeration value ‘kFP8’ not handled in switch [-Werror=switch]
   61 |   switch (type_) {
      |          ^
cc1plus: some warnings being treated as errors
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
</details>

**Comment by SuryanarayanaY** [comment]
Hi @alien2327 ,

This is reported by other community member at #60031 and PR has been raised by a contributor for this which is under review. Please go through the issue and confirm if this is different to the other issue mentioned.

Thanks!

**Comment by alien2327** [comment]
Hi, @SuryanarayanaY !

Thank you for let me know #60031, and yes, this is the same error what I saw.

Again, thank you and your team for all the effort to support tf!
Best regards
