### ISSUE TITLE
Writing custom ReduceOp

### ISSUE THREAD

**Issue by parismic** [tensorflow/tensorflow#60207]
I would like take a MirroredVariable, shape=(32,60),  with 3 replica and reduce is first as a difference of pairs and than L2 norm it. 

Is there a way of writing such a custom ReduceOp? 

https://github.com/tensorflow/tensorflow/blob/0db597d0d758aba578783b5bf46c889700a45085/tensorflow/python/distribute/reduce_util.py#L23-L47

**Comment by synandi** [comment]
Hi @parismic, to create an op, kindly follow this [guide](https://www.tensorflow.org/guide/create_op). Alternatively, you can also try creating a custom layer which is a common set of useful operations by following the instructions mentioned [here](https://www.tensorflow.org/tutorials/customization/custom_layers#implementing_custom_layers). Thank you!
