### ISSUE TITLE
XNNPACK/BUILD.bazel:4762:26: configurable attribute "deps" in @XNNPACK//:amalgam_microkernels doesn't match this configuration. Would a default condition help?

### ISSUE THREAD

**Issue by sukdamrong** [tensorflow/tensorflow#60208]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.13.0

### Custom Code

No

### OS Platform and Distribution

macMonterey 12.4

### Python version

3.11.2

### Bazel version

5.3.0

### GCC/Compiler version

N

### CUDA/cuDNN version

N

### GPU model and memory

N

### Current Behaviour?

```shell
I try to build iOS framework that support armv7 only on M1 MacBook with script

bazel build   --ios_minimum_os='10.0' --config=ios_armv7 -c opt --cxxopt=--std=c++17  //tensorflow/lite/ios:TensorFlowLiteC_framework
external/XNNPACK/BUILD.bazel:4762:26: configurable attribute "deps" in @XNNPACK//:amalgam_microkernels doesn't match this configuration. Would a default condition help?

Conditions checked:
 @XNNPACK//:aarch32
 @XNNPACK//:aarch64
 @XNNPACK//:x86
 @XNNPACK//:emscripten_wasm
 @XNNPACK//:emscripten_wasmsimd
 @XNNPACK//:emscripten_wasmrelaxedsimd
 @XNNPACK//:riscv

To see a condition's definition, run: bazel query --output=build <condition label>.

This instance of @XNNPACK//:amalgam_microkernels has configuration identifier 4cdd8f2. To inspect its configuration, run: bazel config 4cdd8f2.

For more help, see https://docs.bazel.build/configurable-attributes.html#why-doesnt-my-select-choose-what-i-expect.

ERROR: Analysis of target '//tensorflow/lite/ios:TensorFlowLiteC_framework' failed; build aborted: 
INFO: Elapsed time: 0.142s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)

```

### Standalone code to reproduce the issue

```shell
I try to build iOS framework that support armv7 only on M1 MacBook with script

bazel build   --ios_minimum_os='10.0' --config=ios_armv7 -c opt --cxxopt=--std=c++17  //tensorflow/lite/ios:TensorFlowLiteC_framework
```

### Relevant log output

```shell
-
```
</details>

**Comment by pjpratik** [comment]
@sukdamrong Thanks for reporting this issue.

As per this [comment](https://github.com/google/XNNPACK/issues/4598#issuecomment-1494631028), the 32 bit builds might not be supported for ios.

I have tried with `--config=ios_fat` which builts a "fat" binary, containing armv7, arm64, and x86_64 and was able to build the framework successfully. Please find the screenshot below.

<img width="565" alt="Screenshot 2023-04-06 at 4 49 55 PM" src="https://user-images.githubusercontent.com/118897289/230377639-3297cb26-7dc4-4160-a5b3-3459b3d3498c.png">

Thanks.
