### ISSUE TITLE
Support for CUDA 12 for newer GPUS.

### ISSUE THREAD

**Issue by blaze-Youssef** [tensorflow/tensorflow#60206]
Hello,
I have an rrx 3060, and I have Cuda 12.1 installed along with Cudnn.
I can't get Tensorflow to detect my gpu in Python.
As I have read in the docs you must have Cuda 11.8, but I am using another Nvidia app that requires CUDA 12, and I am afraid if I downgrade the CUDA version, I might encounter issues.
Please can someone help or guide me to another methkd of using Tensorflow locally along with my gpu.
I have Windows 11.

**Comment by blaze-Youssef** [comment]
Tried to pip install the nightly pacakge, didn't help.

**Comment by sushreebarsa** [comment]
Hello @blaze-Youssef !
As per the documentation, the latest CUDA version 11.2 is supported for TF v2.10.
Please check this [link](https://www.tensorflow.org/install/source_windows#gpu) for more information.
Thank you!

**Comment by blaze-Youssef** [comment]
Thank you so much, I got it working on docker for Windows using the tenserflow jupyer image.

**Comment by lxspedeza** [comment]
Hi!
@blaze-Youssef  could you please help me solve this issue and give me some link where I can follow what you did to solve the issue? I'm not a programmer, I'm trying to use Tf for behavior analysis in neuroscience research, so I'm a bit of a noob honestly. I have the same issue, driver requiring cuda 12, Tf not supporting cuda 12 and my GPU is not activated during training at all. How did you manage to solve it? Thank you so much in advance!
