### ISSUE TITLE
Cannot pip install tensorflow examples

### ISSUE THREAD

**Issue by kedarps** [tensorflow/tensorflow#60213]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.12.0

### Custom Code

Yes

### Current Behaviour?

```shell
I am trying tensorflow segmentation example from [here](https://www.tensorflow.org/tutorials/images/segmentation) on Google Colab and I get an error in the first cell with pip install.
```

### Standalone code to reproduce the issue

```shell
From Jupyter notebook:

`!pip install git+https://github.com/tensorflow/examples.git`
```

### Relevant log output

```shell
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/tensorflow/examples.git
  Cloning https://github.com/tensorflow/examples.git to /tmp/pip-req-build-xe1kper2
  Running command git clone --filter=blob:none --quiet https://github.com/tensorflow/examples.git /tmp/pip-req-build-xe1kper2
  Resolved https://github.com/tensorflow/examples.git to commit 5bc9f1ed519146242db5e71f00d9d39d52a308c8
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Output of GIT Version and TF version:

`import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)`:

v2.12.0-rc1-12-g0db597d0d75 2.12.0
```
</details>

**Comment by KrishnaSChavan** [comment]
TensorFlow example package is not available on PyPI.
We can clone the TensorFlow example repository from GitHub and run the examples.

Use this following command in cell
` !git clone https://github.com/tensorflow/examples.git`
It will download the repo

Then navigate to following example you want

**Comment by kedarps** [comment]
Can this be updated in the Google colab Jupyter notebooks too?

**Comment by tiruk007** [comment]
> I am able to git clone the repo, but in some notebooks the `tensorflow_examples` package is referenced. How to use that? This line fails:
> 
> `from tensorflow_examples.models.pix2pix import pix2pix`
> 
> This is from segmentation tutorial given [here](https://www.tensorflow.org/tutorials/images/segmentation)

@kedarps 
Thanks for reporting this issue. 
As per this [comment](https://github.com/tensorflow/tensorflow/issues/60213#issuecomment-1495942281).
Please clone the TensorFlow example repository from GitHub. Use `from examples.tensorflow_examples.models.pix2pix import pix2pix` instead of `from tensorflow_examples.models.pix2pix import pix2pix`, Now you can use 'pix2pix' package.

Thank you !

**Comment by kedarps** [comment]
Thank-you. It's working now.
