### ISSUE TITLE
Linker error when building custom op

### ISSUE THREAD

**Issue by iguanaus** [tensorflow/tensorflow#6021]
I was not getting this error a couple of weeks ago, but now when I repull it/update the repository I am getting an error when running configure.

git clone https://github.com/tensorflow/tensorflow.git
git pull
git status
    `On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	tensorflow/core/platform/default/build_config.bzl-e
	tensorflow/models/image/mnist/data/
	tensorflow/user_ops/zero_out.cc
	zero_out.cc
	zero_out_2.so

nothing added to commit but untracked files present (use "git add" to track)`

Then I run ./configure:

Error:
`ERROR: /Users/johnpeurifoy/Documents/Skewl/GeneralUnitaryRNN/tensorflow/tensorflow/tensorflow.bzl:660:21: syntax error at '=': expected expression.
ERROR: /Users/johnpeurifoy/Documents/Skewl/GeneralUnitaryRNN/tensorflow/tensorflow/tensorflow.bzl:735:1: nested functions are not allowed. Move the function to top-level.
ERROR: /Users/johnpeurifoy/Documents/Skewl/GeneralUnitaryRNN/tensorflow/tensorflow/tensorflow.bzl:763:1: nested functions are not allowed. Move the function to top-level.
ERROR: /Users/johnpeurifoy/Documents/Skewl/GeneralUnitaryRNN/tensorflow/tensorflow/tensorflow.bzl:797:1: nested functions are not allowed. Move the function to top-level.
ERROR: /Users/johnpeurifoy/Documents/Skewl/GeneralUnitaryRNN/tensorflow/tensorflow/tensorflow.bzl:800:1: nested functions are not allowed. Move the function to top-level.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension 'tensorflow/tensorflow.bzl' has errors.
`

Overall, I am trying to implement a new operator using tensorflow. I am able to easily import tensorflow, but when I try to build the new operator (following the tutorial on https://www.tensorflow.org/versions/r0.12/how_tos/adding_an_op/index.html), i get:

`  "tensorflow::Tensor::CheckTypeAndIsAligned(tensorflow::DataType) const", referenced from:
      ZeroOutOp::Compute(tensorflow::OpKernelContext*) in zero_out-a7cd0e.o
  "typeinfo for tensorflow::OpKernel", referenced from:
      typeinfo for ZeroOutOp in zero_out-a7cd0e.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Thoughts? I have tried checking out the other branches as well and trying them, but no luck.

My pip freeze looks like:

`alabaster==0.7.9
anaconda-clean==1.0
anaconda-client==1.5.1
anaconda-navigator==1.3.1
appnope==0.1.0
appscript==1.0.1
argcomplete==1.0.0
astroid==1.4.7
astropy==1.2.1
Babel==2.3.4
backports-abc==0.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.5.1
bitarray==0.8.1
blaze==0.10.1
bokeh==0.12.2
boto==2.42.0
Bottleneck==1.1.0
cdecimal==2.3
cffi==1.7.0
chest==0.2.3
click==6.6
cloudpickle==0.2.1
clyent==1.2.2
colorama==0.3.7
conda==4.2.12
conda-build==2.0.2
configobj==5.0.6
configparser==3.5.0
contextlib2==0.5.3
cryptography==1.5
cycler==0.10.0
Cython==0.24.1
cytoolz==0.8.0
dask==0.11.0
datashape==0.5.2
decorator==4.0.10
dill==0.2.5
docutils==0.12
dynd==0.7.3.dev1
enum34==1.1.6
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==2.0.6
Flask==0.11.1
Flask-Cors==2.1.2
funcsigs==1.0.2
functools32==3.2.3.post2
futures==3.0.5
gevent==1.1.2
greenlet==0.4.10
grin==1.2.1
h5py==2.6.0
HeapDict==1.0.0
idna==2.1
imagesize==0.7.1
ipaddress==1.0.16
ipykernel==4.5.0
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
itsdangerous==0.24
jdcal==1.2
jedi==0.9.0
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.0
Keras==1.1.1
lazy-object-proxy==1.2.1
llvmlite==0.13.0
locket==0.2.0
lxml==3.6.4
MarkupSafe==0.23
matplotlib==1.5.3
mistune==0.7.3
mock==2.0.0
mpmath==0.19
multipledispatch==0.4.8
nb-anacondacloud==1.2.0
nb-conda==2.0.0
nb-conda-kernels==2.0.0
nbconvert==4.2.0
nbformat==4.1.0
nbpresent==3.0.2
networkx==1.11
nltk==3.2.1
nose==1.3.7
notebook==4.2.3
numba==0.28.1+0.gfe99fbc.dirty
numexpr==2.6.1
numpy==1.11.1
odo==0.5.0
openpyxl==2.3.2
pandas==0.18.1
partd==0.3.6
path.py==0.0.0
pathlib2==2.1.0
patsy==0.4.1
pbr==1.10.0
pep8==1.7.0
pexpect==4.0.1
pickleshare==0.7.4
Pillow==3.3.1
pkginfo==1.3.2
ply==3.9
prompt-toolkit==1.0.3
protobuf==3.0.0
psutil==4.3.1
ptyprocess==0.5.1
py==1.4.31
pyasn1==0.1.9
PyAudio==0.2.7
pycosat==0.6.1
pycparser==2.14
pycrypto==2.6.1
pycurl==7.43.0
pyflakes==1.3.0
Pygments==2.1.3
pylint==1.5.4
pyOpenSSL==16.0.0
pyparsing==2.1.4
pytest==2.9.2
python-dateutil==2.5.3
pytz==2016.6.1
PyYAML==3.12
pyzmq==15.4.0
QtAwesome==0.3.3
qtconsole==4.2.1
QtPy==1.1.2
redis==2.10.5
requests==2.11.1
rope==0.9.4
ruamel-yaml===-VERSION
scikit-image==0.12.3
scikit-learn==0.17.1
scipy==0.18.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
sockjs-tornado==1.0.3
Sphinx==1.4.6
spyder==3.0.0
SQLAlchemy==1.0.13
statsmodels==0.6.1
sympy==1.0
tables==3.2.3.1
tensorflow==0.11.0rc2
terminado==0.6
Theano==0.8.2
toolz==0.8.0
tornado==4.4.1
traitlets==4.3.0
unicodecsv==0.14.1
wcwidth==0.1.7
Werkzeug==0.11.11
widgetsnbextension==1.2.6
wrapt==1.10.6
xlrd==1.0.0
XlsxWriter==0.9.3
xlwings==0.10.0
xlwt==1.1.2`

**Comment by keveman** [comment]
@iguanaus What platform are you trying this on?

**Comment by iguanaus** [comment]
Macbook running os x el captain, 10.11.3

**Comment by dennybritz** [comment]
Upgrade to the latest bazel version. If you are using homebrew:

```bash
brew update
brew upgrade bazel
```

**Comment by keveman** [comment]
@iguanaus Have you tried it with the latest version of bazel?

**Comment by iguanaus** [comment]
Yes this does not resolve it.

**Comment by dennybritz** [comment]
@iguanaus What version of bazel are you using? I had the same issue and updating bazel to `0.4.1` solved it.

**Comment by gunan** [comment]
with bazel 0.4.2, we now have multiple mirrors for our external dependencies.
Could you try bazel 0.4.2?

**Comment by gunan** [comment]
Closing the issue  due to inactivity.
