### ISSUE TITLE
Null pointer dereference in lmhlo_to_cpu_runtime.cc

### ISSUE THREAD

**Issue by PaDarochek** [tensorflow/tensorflow#60223]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.12

### Custom Code

No

### Current Behaviour?

```shell
Variable `dict` may be `nullptr` and is dereferenced on line 149 in `tensorflow/compiler/xla/mlir/backends/cpu/transforms/lmhlo_to_cpu_runtime.cc`.  

`dict` is initialized on line 146 and may equal `nullptr`. Then it is dereferenced on line 149.  
```

### Standalone code to reproduce the issue

```shell
Bug was found by Svace static analysis tool.
```

### Relevant log output

_No response_</details>

**Comment by PaDarochek** [comment]
@mihaimaruseac  

https://github.com/tensorflow/tensorflow/blob/c1169a1ba98e1c5d0874cd44ffeb605bfd1cefba/tensorflow/compiler/xla/mlir/backends/cpu/transforms/lmhlo_to_cpu_runtime.cc#L145-L149

**Comment by pjpratik** [comment]
@SweetVishnya Thanks for the PR.

@PaDarochek The issue will be closed once the PR is merged.

Thanks.
