### ISSUE TITLE
Negative axis support for argmin and argmax

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#6022]
I'd like `tf.argmax(value, axis=-1)` to work.  A lot of other ops support negative axes (`tf.concat`, `tf.stack`, etc.), but not `argmin` and `argmax`.

**Comment by aijanai** [comment]
Sorry if I reopen this, but I was desperately looking for an explanation of negative axis concatenation. rf.reshape does explain the special case for -1, but not tf.concat.
May someone be so kind to explain what does that mean?
Thanks

**Comment by girving** [comment]
`axis=-1` means the last axis, in the same way that `list[-1]` in Python means the last entry.  See also any numpy function, such as https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.sum.html.

**Comment by aijanai** [comment]
Great, that confirmed the idea I got by experimenting. Thanks

**Comment by DEepLiker** [comment]
Thanks

**Comment by cherler** [comment]
resolve my confusion about `axis=-1` .thanks
