### ISSUE TITLE
Null pointer dereference in conv_ops_fused_int8.cc

### ISSUE THREAD

**Issue by PaDarochek** [tensorflow/tensorflow#60220]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.12

### Custom Code

No

### Current Behaviour?

```shell
Pointer `side_input_ptr` is dereferenced and passed as the first argument into a call to `std::fmaf` in `tensorflow/core/kernels/conv_ops_fused_int8.cc`.  

If we are at 0th iteration in a `for`-loop (line 210) and `side_input_base == nullptr` then `col == 0` and `side_input_ptr` will also equal `nullptr` (line 265). After assign to `side_input_ptr`, this pointer is dereferenced on line 269.
```

### Standalone code to reproduce the issue

```shell
Bug was found by Svace static analysis tool.
```

### Relevant log output

_No response_</details>

**Comment by PaDarochek** [comment]
https://github.com/tensorflow/tensorflow/blob/c1169a1ba98e1c5d0874cd44ffeb605bfd1cefba/tensorflow/core/kernels/conv_ops_fused_int8.cc#L200-L271

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue, this looks like edge case scenario, I have created a PR to address the issue. Thanks!
