### ISSUE TITLE
tensorflow-2.12.0 not support GPU

### ISSUE THREAD

**Issue by yatebyaeby** [tensorflow/tensorflow#60237]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

v2.12.0-rc1-12-g0db597d0d75 2.12.0

### Custom Code

No

### OS Platform and Distribution

Windows 10

### Mobile device

-

### Python version

3.10.10

### Bazel version

-

### GCC/Compiler version

-

### CUDA/cuDNN version

cuda_11.8.0_522.06_windows / cudnn-windows-x86_64-8.6.0.163_cuda11

### GPU model and memory

1050ti 4 GB

### Current Behaviour?

```shell
Supporting GPU calcs. Ive tried version tf 2.10, all works, but 2.10 have some issues, that 2.12 dont have
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.python.client import device_lib
import numpy as np
print(tf.__version__)

print(f"Tensor Flow Version: {tf.__version__}")
print(f"Keras Version: {tf.keras.__version__}")
print()
gpu = len(tf.config.list_physical_devices('GPU'))>0
print("GPU is", "available" if gpu else "NOT AVAILABLE")
```

### Relevant log output

```shell
2.12.0
Tensor Flow Version: 2.12.0
Keras Version: 2.12.0

GPU is NOT AVAILABLE
```
</details>

**Comment by synandi** [comment]
Hi @yatebyaeby, As per the official documentation, TensorFlow 2.10 was the last TensorFlow release that supported GPU on native-Windows. Starting with TensorFlow 2.11, you will need to install [TensorFlow in WSL2](https://tensorflow.org/install/pip#windows-wsl2). Hence, please try installing Tensorflow in WSL2. 

Also note that, TensorFlow with GPU access is supported for WSL2 on Windows 10 19044 or higher. This corresponds to Windows 10 version 21H2, the November 2021 update. You can get the latest update from here: [Download Windows 10](https://www.microsoft.com/software-download/windows10). For instructions, see [Install WSL2](https://docs.microsoft.com/windows/wsl/install) and [NVIDIA’s setup docs](https://docs.nvidia.com/cuda/wsl-user-guide/index.html) for CUDA in WSL.  Thank you!

**Comment by yatebyaeby** [comment]
> Hi @yatebyaeby, As per the official documentation, TensorFlow 2.10 was the last TensorFlow release that supported GPU on native-Windows. Starting with TensorFlow 2.11, you will need to install [TensorFlow in WSL2](https://tensorflow.org/install/pip#windows-wsl2). Hence, please try installing Tensorflow in WSL2.
> 
> Also note that, TensorFlow with GPU access is supported for WSL2 on Windows 10 19044 or higher. This corresponds to Windows 10 version 21H2, the November 2021 update. You can get the latest update from here: [Download Windows 10](https://www.microsoft.com/software-download/windows10). For instructions, see [Install WSL2](https://docs.microsoft.com/windows/wsl/install) and [NVIDIA’s setup docs](https://docs.nvidia.com/cuda/wsl-user-guide/index.html) for CUDA in WSL. Thank you!

oh, thanks for reply
