### ISSUE TITLE
Tensorflow-gpu version 2.12.0 is not available

### ISSUE THREAD

**Issue by KnSun99** [tensorflow/tensorflow#60241]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf2.12.0

### Custom Code

No

### OS Platform and Distribution

Win11

### Python version

3.10.10

### Current Behaviour?

```shell
No version 2.12.0 of the tensorflow-gpu was found.
```

### Standalone code to reproduce the issue

```shell
Not have
```

### Relevant log output

_No response_</details>

**Comment by 123mbcz123** [comment]
tensorflow doesn't support  native gpu on windows since 2.11

**Comment by tilakrayal** [comment]
@Sun-kangning,
TensorFlow 2.10 was the last TensorFlow release that supported GPU on native-Windows. Starting with TensorFlow 2.11, you will need to install [TensorFlow in WSL2](https://tensorflow.org/install/pip#windows-wsl2), or install tensorflow-cpu and, optionally, try the [TensorFlow-DirectML-Plugin](https://github.com/microsoft/tensorflow-directml-plugin#tensorflow-directml-plugin-)

Kindly find the official doc link for the reference.
https://www.tensorflow.org/install/pip

Thank you!

**Comment by Sun-kangning** [comment]
I tried Linux system, thanks for your reply!

**Comment by Sun-kangning** [comment]
I will try Linux system, thanks for your reply!

**Comment by mihaimaruseac** [comment]
The `tensorflow` and `tensorflow-gpu` packages are the same since TF 2.1.0. To conserve space on PyPI, the redundant package has been removed. Please consult the release notes, it is the first item mentioned there: https://github.com/tensorflow/tensorflow/releases/tag/v2.12.0


@tilakrayal and @123mbcz123 have provided incorrect answers for this issue

**Comment by Sun-kangning** [comment]
Ok, thank you very much for your reply!

**Comment by KnSun99** [comment]
Tensorflow2.12.0 using GPU. What versions of cuda and cudnn are required?
Windows11,  Python3.10.10.  I'm using cuda12.1.0 and cudnn8.8.1.3 and can't drive the GPU.

**Comment by kartikeyam30** [comment]
Same issue. Tf 2.12, Python 3.10, Windows 11, cuda12.1, cudnn 8.9.0 with Nvidia RTX 3060 for laptops. DeviceQuery result was PASS. Tensorflow output is just my CPU with no GPU detected. Been years and I've never seen one CUDA install smooth at first try.

**Comment by mihaimaruseac** [comment]
Are you using WSL? #59918

**Comment by KnSun99** [comment]
Win11，Not WSL

https://pypi.org/project/tensorflow-gpu/#description

**Comment by mihaimaruseac** [comment]
See note at top of 2.11.1 (which applies to 2.11.0 and 2.12.0 too): https://github.com/tensorflow/tensorflow/releases/tag/v2.11.1

**Comment by sachinprasadhs** [comment]
Please follow the tested build configurations published [here](https://www.tensorflow.org/install/source_windows#cpu) for windows CPU and GPU, as mentioned in above comments, 2.10 was the last last Tensorflow version which supported GPU on native windows.

If you are trying with the `Windows-WSl2` installation https://www.tensorflow.org/install/pip#windows-wsl2 then you can try with the `cuDNN 8.6`, `CUDA 11.8` and `python version 3.8-3.11`

**Comment by warmnerds** [comment]
I have Nvidia GeForce 720m can I use it for training with tensorflow 2.12.0

**Comment by KnSun99** [comment]
Which version of cuda and cudnn are you using?
