### ISSUE TITLE
where is Tensorflow directory on Windows ?

### ISSUE THREAD

**Issue by codeloverr** [tensorflow/tensorflow#6024]
I have installed and verified Tensorflow installation on Windows, that's great. But how I am supposed to to stuff like `pyhthon3 cifar10_train.py`? ran that command got error no such file or directory. Also run the whole code in cifar10.py and got error there is no module named tensorflow.modles.

`ImportError was unhandled by user code
Message: No module named 'tensorflow.models'`

**Comment by mrry** [comment]
The location of the TensorFlow directory on Windows will depend on your Python distribution. You should be able to find it by doing the following:

```
C:\> python
>>>import tensorflow as tf
>>>print(tf.__file__ )
```

However, the TensorFlow directory doesn't currently include the `tensorflow.models` (see #5953), so even if you download the `cifar10_train.py` code it won't quite work. I've sent #6029 to fix this, and it should appear in the final release.

(I'll close this issue for now, but please watch #5953 for an update on when the `tensorflow.models` will be easily usable on Windows.)

**Comment by codeloverr** [comment]
Tensorflow on Windows does not have CMake in contrib folder. @mrry

**Comment by mrry** [comment]
@codeloverr I'm not sure where you're looking: it's certainly in the git repository (since that's how we build it). The CMake directory isn't included in the PIP package because it doesn't contain anything useful for Python users who've downloaded the built package.

**Comment by shilan** [comment]
I downloaded the zip file from github, extracted and added those files I needed to the directory tensorflow was expecting them to be. In my case c:/users/my_username/Anaconda
3/Lib/
