### ISSUE TITLE
Tensorboard erorr when adding metadata to embedding 

### ISSUE THREAD

**Issue by qingyili** [tensorflow/tensorflow#6026]
### Environment info
Operating System: Linux gaia 3.13.0-95-generic

If installed from binary pip package, provide:

1. A link to the pip package you installed: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.0rc0-cp35-cp35m-linux_x86_64.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.12.0-rc0

Followed the instructions on 'https://www.tensorflow.org/versions/r0.12/how_tos/embedding_viz/index.html'
to add labels to my embedding. My metadata.tsv file is just a single column with the ith row being the label corresponing to the ith row of embedding tensor

However after I did this and ran Tensorboard everything is fine until I click 'embeddings'  then I get this error message  
```
'Exception happened during processing of request from ('127.0.0.1', 56645)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/tensorboard/backend/handler.py", line 103, in __init__
    BaseHTTPServer.BaseHTTPRequestHandler.__init__(self, *args)
  File "/usr/local/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "/usr/local/lib/python3.5/site-packages/tensorflow/tensorboard/backend/handler.py", line 531, in do_GET
    self.data_handlers[clean_path](query_params)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/tensorboard/plugins/projector/plugin.py", line 278, in _serve_runs
    request.respond(list(self.configs.keys()), 'application/json')
  File "/usr/local/lib/python3.5/site-packages/tensorflow/tensorboard/plugins/projector/plugin.py", line 141, in configs
    _latest_checkpoints_changed(self._configs, run_path_pairs)):
  File "/usr/local/lib/python3.5/site-packages/tensorflow/tensorboard/plugins/projector/plugin.py", line 65, in _latest_checkpoints_changed
    if run_name not in configs:
TypeError: argument of type 'NoneType' is not iterable
```

If i removed the ``` projector_config.pbtxt ```  from the LOGDIR tensoboard runs properly again. 

Also found on the documentation page 

``` embedding = config.embeddings.add() ```  should be ```embedding = config.embedding.add() ```

**Comment by qingyili** [comment]
Sorry to make this more complicated then it is, however yesterday when I posted this issue I did not notice that I was trying to do this with logs and models that are saved from `0.11.0rc2`. However everything was working fine on tensorboard, I could see the embedding very nicely and I only got the above error when I tried to add embedding metadata ` projector_config.pbtxt `. Today on a new run with logs and model saved from ` 0.12-rc0 ` , I could not view the embedding tab anymore and I get the same error. (without trying to add any metadata files)

**Comment by marcevrard** [comment]
You probably haven't created the actual `metadata.tsv` file. It isn't maybe immediately clear reading the how-to. Here is an example: http://stackoverflow.com/a/41262360/4218883.

**Comment by qingyili** [comment]
I have created the metadata file. My metadata.tsv file is just a single column with the ith row being the label corresponing to the ith row of embedding tensor.

**Comment by marcevrard** [comment]
Indeed, sorry I guess I read your initial comment too quickly.
For info my metadata is a 2 column tsv file:
* 1st column: data IDs
* 2nd column: data labels (words in my case)

**Comment by bbarnes52** [comment]
I encountered this issue as well. The problem was that the metadata_path in projector_config.pbtxt did not point to metadata.tsv.

**Comment by markjay4k** [comment]
I was able to edit the projector_config.pbtxt file to fix the paths and it seems to do the trick. Seems to be an windows issues
