### ISSUE TITLE
linked page is not valid!

### ISSUE THREAD

**Issue by jntdst** [tensorflow/tensorflow#60285]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.8

### Custom Code

Yes

### Current Behaviour?

```shell
TRFL in
https://www.tensorflow.org/resources/libraries-extensions
is not valid:)
```

### Standalone code to reproduce the issue

```shell
TRFL in
https://www.tensorflow.org/resources/libraries-extensions
is not valid:)
```

### Relevant log output

_No response_</details>

**Comment by Inder782** [comment]
hi i am new to opensource , can you tell explain a little bit so that i can look into it

**Comment by sanjail3** [comment]
Can I work on this issue

**Comment by sanjail3** [comment]
Can you please say the file location where the error occurs

**Comment by synandi** [comment]
Hi @jntdst 
Thank you for reporting the issue! We will update here soon.

**Comment by jntdst** [comment]
Hello، I filled Tensorflow version by mistake. I mean the current version.
Because of, GitHub didn't allow me to send a report without a version, and
I also used the Github default version. I still see the link on the page.
don't you see?

**Comment by N-Kannan** [comment]
@jntdst can you assisn me the issue I will check and try to solve the issue

**Comment by SaiNithinNartuo** [comment]
@jntdst can you tell me more details i have more experience in working with tensorflow and keras

**Comment by synandi** [comment]
@jntdst, Apologies for the delay. This issue is being tracked internally and will be fixed. Thank you!

**Comment by sachinprasadhs** [comment]
Hi, 

Thanks for reporting the issue. 

The link has been updated in the https://www.tensorflow.org/resources/libraries-extensions
Now TFRL will redirect to github repository https://github.com/deepmind/trfl/.
Please check and feel free to close the issue. Thanks!
