### ISSUE TITLE
Cannot use extended batch shape with channel_first Conv2D

### ISSUE THREAD

**Issue by Yang-Yuan** [tensorflow/tensorflow#60280]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.12

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 1804

### Current Behaviour?

```shell
Given input tensor for shape, say [batch_dim_1 = 4, batch_dim_2 = 5, channels = 6, Height = 7, Width = 8] to a channels_first (keras) Conv2D of stride 2, the "_get_sequence" function at Line 1288 in nn_ops.py sets strides to [1, 2, 2, 1], which is wrong. Strides should be [1, 1, 2, 2] for the input tensor will be reshaped to [batch_dim_1 * batch_dim_2, channels, Height, Width] later in squeeze_batch_dim in nn_ops.py.
```

### Standalone code to reproduce the issue

```shell
As described above.
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@Yang-Yuan Thanks for reporting an issue!
Could you please elaborate the issue here by stating the example if you are using any. Thank you!
