### ISSUE TITLE
tfp.stats.histogram weights argument bug when using multiple axes

### ISSUE THREAD

**Issue by joaozenobio** [tensorflow/tensorflow#60287]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python version

3.8.10

### Current Behaviour?

```shell
Tensorflow throws a ValueError when using weights and multiple axes at the same time, saying that the input and weights arguments should have the same shape, even though they already have.

Hint: Does not happen when using only one axis.
```

### Standalone code to reproduce the issue

```shell
import tensorflow_probability as tfp
import tensorflow as tf
x = tf.constant([[1, 2, 3], [1, 2, 3.]])
w = tf.constant([[1, 1, 1], [1, 1, 1.]])
e = tf.constant([0, 2.5, 10])
axis = (0, 1)
tfp.stats.histogram(x=x, edges=e, axis=axis, weights=w)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/opt/.pycharm_helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow_probability/python/stats/quantiles.py", line 393, in histogram
    raise ValueError('Number of dimensions of `x` and `weights` must '
ValueError: Number of dimensions of `x` and `weights` must coincide. Found: x has 2, weights has 1
```
</details>

**Comment by ayushsh314** [comment]
If you read the tensorflow documentation for tfp.stats.histogram(https://www.tensorflow.org/probability/api_docs/python/tfp/stats/histogram), upon reading the description of 'axis', it says : "Optional 0-D or 1-D integer Tensor with constant values." which means that tensorflow expects the axis to be passed as a tensor to generate the required results.

You can try passing the axis as a tensor, something like this : axis = tf.constant(0, 1)

**Comment by tilakrayal** [comment]
@joaozenobio,
Looks like this issue is more related to tensorflow propability repo. Could you please raise the issue in the respective repo from here for further assistance. 
https://github.com/tensorflow/probability/issues
Thank you!

**Comment by joaozenobio** [comment]
@tilakrayal, I will raise a new issue there and make a reference to this one, thanks.

**Comment by tilakrayal** [comment]
@joaozenobio,
Please feel free to move this issue to closed status, as it has been tracked in the respective repo. Thank you!
