### ISSUE TITLE
tf.random.truncated_normal (inside graph) crashed TPUv4 pod

### ISSUE THREAD

**Issue by edwardyehuang** [tensorflow/tensorflow#60291]
### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.10 TPU Pod

### Current Behaviour?

I found ```tf.random.truncated_normal``` will crash the TPUv4 Pod during training (graph computation).

```tf.random.truncated_normal``` is fine when not in a graph (e.g. variable initialization).

```tf.random.normal``` and ```tf.random.uniform``` are fine during training.

**Comment by tiruk007** [comment]
@edwardyehuang 
Could you please provide reproducible code or Colab gist to replicate the issue reported here ?

Thank you !
