### ISSUE TITLE
Install Documentation still links to 0.5

### ISSUE THREAD

**Issue by marcotrombetti** [tensorflow/tensorflow#603]
https://www.tensorflow.org/versions/master/get_started/os_setup.html#pip_install

The Virtualenv mentions the version 0.5 instead of 0.6 and this may cause some confusion since the rest of the documentation links 0.6.

see:

Ubuntu/Linux 64-bit, CPU only:
(tensorflow)$ pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl

Ubuntu/Linux 64-bit, GPU enabled:
(tensorflow)$ pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl

Mac OS X, CPU only:
(tensorflow)$ pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl

I noticed that the

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/pull/604
