### ISSUE TITLE
use ESRGAN super resolution on iOS device by TensorFlowLiteSwift, the output is not identical as the output in python env.

### ISSUE THREAD

**Issue by OwenHongJinmu** [tensorflow/tensorflow#60308]
I use the sample image for ESRGAN lr-1 
![lr1](https://user-images.githubusercontent.com/7868069/231623423-1431788d-dc0c-451e-9e52-d811f410276c.jpg)
and inference by TensorFlowLiteSwift, compared with python env in Colab , the input pixel data array was identical, but the output pixel data was different totally。partial output data：
iOS:    [[[ 59. 78. 70.] [ 77. 137. 42.] [ 76. 136. 79.]  ...
Colab:[[[ 59. 79. 71.] [ 72. 103.  72.] [ 86. 124.  65.] ...

**Comment by OwenHongJinmu** [comment]
the tflite model is convert from https://tfhub.dev/captain-pool/esrgan-tf2/1

**Comment by tiruk007** [comment]
@OwenHongJinmu 
Could you please elaborate more and provide detailed steps to replicate the issue reported here ?

Thank you !

**Comment by pjpratik** [comment]
Hi @OwenHongJinmu 

The TFLite model converted from the TF model might loose some accuracy because of quantization.

You can keep the float model by turning off the optimization by `converter.optimizations =[]` while converting the model to TFLite which can preserve better accuracy.

Thanks.
