### ISSUE TITLE
protobuf have a problem

### ISSUE THREAD

**Issue by stonecropa** [tensorflow/tensorflow#60320]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf2.11.0

### Custom Code

Yes

### OS Platform and Distribution

win10

### Python version

3.9.16

### CUDA/cuDNN version

11.7

### Current Behaviour?

I don't know if there is a problem with my download or the version of tensorflow, that is, how to recompile protobuf. Can I download the tensorflow compressed package directly from GitHub and uninstall tensorflow-Intel without uninstalling the gpu version.

### Standalone code to reproduce the issue

```shell
PS E:\Googledownload\RectifiedFlow-main> & D:/conda/envs/reflow/python.exe e:/Googledownload/RectifiedFlow-main/ImageGeneration/1.py
Traceback (most recent call last):
  File "e:\Googledownload\RectifiedFlow-main\ImageGeneration\1.py", line 1, in <module>
    import tensorflow as tf
  File "D:\conda\envs\reflow\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "D:\conda\envs\reflow\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "D:\conda\envs\reflow\lib\site-packages\tensorflow\python\eager\context.py", line 28, in <module>
    from tensorflow.core.framework import function_pb2
  File "D:\conda\envs\reflow\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "D:\conda\envs\reflow\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "D:\conda\envs\reflow\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "D:\conda\envs\reflow\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "D:\conda\envs\reflow\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "D:\conda\envs\reflow\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@stonecropa,
Hi, Thanks for opening the issue.

```
Step 1: pip uninstall protobuf
Step 2: pip install protobuf==3.20.0

or any other lower version:
https://pypi.org/project/protobuf/#history
```
We have upgraded the protobuf dependency to 3.21.9 (4.21.9) for python from Tensorflow version 2.12, which was long awaited ask.
**For Tensorflow and Tensorboard 2.12 version, the protobuf minimum version requirement is 'protobuf>=3.20.3,<5.0.0dev,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5'.**
For any older Tensorflow version and new Tensorboard version the only version which acts as bridge between both is 3.20.3
The Tensorflow 2.12 is released, you can use Tensorboard 2.12 without any package conflict.  Please have a look at this issue for the [reference](https://github.com/tensorflow/tensorflow/issues/58247). Thank you!

**Comment by stonecropa** [comment]
@tilakrayal                                                                                              I installed tensorflow==2.12.0 in conda, and the conda list also shows that it is version 12, but it shows that it is version 11 in the VScode terminal, and the original error is still reported. My python is 3.8.16. Thanks.

**Comment by tilakrayal** [comment]
@stonecropa,

Apologies for the delay. It seems the error might be related to protobuf version. Could you please confirm the protobuf version installed? And also for the Tf2.11 version the required range versions should be **protobuf >= 3.9.2, < 3.20** .  Could you please check and confirm the same. Thank you!
