### ISSUE TITLE
Issue with obtaining files from this repo via Google Colab

### ISSUE THREAD

**Issue by ShreeVishal** [tensorflow/tensorflow#60325]
![Screenshot 2023-04-14 162503](https://user-images.githubusercontent.com/93562563/231988319-e5946ae6-30fe-4237-9617-c08e8ee8104c.png)

**Comment by tilakrayal** [comment]
@ShreeVishal,
The TensorFlow example package is not available on PyPI. We can clone the TensorFlow example repository from GitHub and try to run the examples.

Could you please try to use the following command
 `!git clone https://github.com/tensorflow/examples.git`

The above statement will download the repo.

Then try to navigate to the following example which was needed. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/2caf95b23d957e3f26f73149e7861fc8/segmentation.ipynb).
![Screenshot 2023-04-14 2 15 01 PM](https://user-images.githubusercontent.com/81610181/231993061-b45e96dc-1d62-4abf-8739-6975464afb2b.png)

Thank you!
