### ISSUE TITLE
have a bug about AVX2 FMA

### ISSUE THREAD

**Issue by stonecropa** [tensorflow/tensorflow#60337]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.12

### Custom Code

Yes

### OS Platform and Distribution

ubuntu 2004

### Python version

Python3.8.16

### CUDA/cuDNN version

11.3

### Current Behaviour?

 don't train,I want to fix it

### Standalone code to reproduce the issue

```shell
2023-04-16 18:41:59.167857: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Segmentation fault (core dumped)
```

### Relevant log output

```shell
2023-04-16 18:41:59.167857: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Segmentation fault (core dumped)
```
</details>

**Comment by tilakrayal** [comment]
@stonecropa,
Could you please provide the complete code to debug the issue. Also Please don't file vulnerabilities on GitHub. Please consult https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md and follow rules for responsible disclosure. Thank you!

**Comment by stonecropa** [comment]
[Uploading RectifiedFlow-main (1).zip…]()
this

**Comment by tilakrayal** [comment]
@stonecropa,,
The zip file which was provided above re-directing the same issue page. Please check and confirm whether you have attached the correct file or not. Thank you!
