### ISSUE TITLE
Importing Tensorflow on Databricks after setting a log configuration causes next cell to hang indefinitely

### ISSUE THREAD

**Issue by Henriklimseth** [tensorflow/tensorflow#60341]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Databricks runtime 11.3 LTS ML

### Python version

3.9.5

### Current Behaviour?

On Databricks: importing tensorflow after setting a logz.io logging configuration casues the next cell to hang indefinitely roughly 50% of the time.

In the screenshot below, I've cancelled a Databricks command after it spent over 10 minutes calculating `1+1` after a tensorflow import. 

![tensorflow import example](https://user-images.githubusercontent.com/13903284/232449271-3fae830a-3b30-480f-bbb5-ba01de79a181.png)

This only happens when I've set a logz.io logging configuration before importing tensorflow, as shown in the **Standalone code to reproduce this issue**.  Tensorflow seems to pick up the log configuration, as the import outputs this message when the logz.io-token is invalid:

![image](https://user-images.githubusercontent.com/13903284/232451242-382f6b68-96fc-46c7-8a8d-f5846eafb3a6.png)

And this _somehow_ seems to be related to the issue, as I've only had it happen after I've set the log configuration.

The same issue occurs when using tf-nightly. It can be observed by adding a magic command: `%pip install tf-nightly` to the beginning of the standalone code below. Doing so reveals that tensorboard and logzio-python-handler have several common dependencies, and there could in principle be underlying conflicts. But please note that the issue also occurs with tensorflow 2.9.1 and logzio-python-handler 3.1.1, which were specifically chosen to not have version-conflicts in the common transitive dependencies:
```
tensorboard 2.9.1 requires google-auth-oauthlib<0.5,>=0.4.1, but you have google-auth-oauthlib 1.0.0 which is incompatible.
tensorboard 2.9.1 requires protobuf<3.20,>=3.9.2, but you have protobuf 4.22.3 which is incompatible.
tensorboard 2.9.1 requires tensorboard-data-server<0.7.0,>=0.6.0, but you have tensorboard-data-server 0.7.0 which is incompatible.
```

Do anyone have ideas about this? Does tensorflow have some internal logging that might cause conflicts?

**Expected behaviour**
Running a cell after importing tensorflow should just work.

### Standalone code to reproduce the issue

```shell
# Databricks notebook source
# MAGIC %pip install logzio-python-handler==3.1.1

# COMMAND ----------

import logging
import logging.config


try:
  token = dbutils.secrets.get('default', 'logzio_token')
except:
  token = "test_value"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'logzioFormat': {
            'format': '{"component": "test_comp", "res_cluster": "test_cluster"}',
            'validate': False
        }
    },
    'handlers': {
        'logzio': {
            'class': 'logzio.handler.LogzioHandler',
            'level': 'INFO',
            'formatter': 'logzioFormat',
            'token': f'{token}',
            'logzio_type': 'Databricks',
            'logs_drain_timeout': 1,
            'url': 'https://listener-eu.logz.io:8071',
            'debug': False
        }
    },
    'loggers': {
        '': {
            'level': 'INFO',
            'handlers': ['logzio'],
            'propagate': True
        }
    }
}

logging.config.dictConfig(LOGGING)
logger = logging.getLogger('DatabricksLogger')

# COMMAND ----------

import tensorflow as tf

# COMMAND ----------

1+1
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@Henriklimseth,
Could you please try using [get_statistics_html](https://www.tensorflow.org/tfx/data_validation/api_docs/python/tfdv/get_statistics_html) that generates the HTML objects and calling those instead of the visualize functions. 

Then, try to visualize those functions with the DataBricks .[displayHTML](https://docs.databricks.com/notebooks/visualizations/html-d3-and-svg.html) function. And also could you please refer to this https://github.com/tensorflow/tfx/issues/2194#issuecomment-1262088337 for the reference.
Thank you!

**Comment by Henriklimseth** [comment]
@tilakrayal 
Thank you for the response.
I'm not sure what you mean, though. I'm not calling any visualize functions. Everything simply hangs after importing tensorflow.
If you still think I should call this `get_statistics_html`-function, could you please tell me what the argument of the function should be? My code fails without any data.
![image](https://user-images.githubusercontent.com/13903284/232705976-d2e7eb72-1714-4920-b9d8-4537e11b57c2.png)

**Comment by sachinprasadhs** [comment]
This looks like an issue on the environment side, did you observe this behavior in any other platform. 
If not, cloud you please help us with more information to investigate on this further. Thanks!
