### ISSUE TITLE
data and ml module missing

### ISSUE THREAD

**Issue by changyushun** [tensorflow/tensorflow#60348]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2

### Custom Code

No

### OS Platform and Distribution

mac

### Current Behaviour?

A bug happened!

### Standalone code to reproduce the issue

```shell
from data import BodyPart
from ml import Movenet
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@changyushun,
AFAIK you are trying to run the mentioned code directly. Before executing the code, please try to import the dependencies as well. And also I guess, you are trying to  execute the pose_classification.ipynb file.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/pose_classification.ipynb

I was able to execute the code without any issues. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/50af14cb4b5234769e3350c4ca2369bd/untitled1073.ipynb). Thank you!

**Comment by changyushun** [comment]
> issues
@tilakrayal , thank your comment.
I do know the code is runable in colab and try to run in my local mac environment. the 'data' and 'ml' module is the issue happen in my mac. i thought the 'data' and 'ml' is the modules installed by PIP but apperantly not or installed wrong modules?  can you tell which dependencies do those two modules belong to ? thank in advance.

**Comment by changyushun** [comment]
@tilakrayal 
I found those two modules is come from the loaded examples. not from PIP. My Bad.
