### ISSUE TITLE
NaN is not propagated in `tf.pow(tf.constant(1.0), tf.sqrt(tf.constant(-1.0)))`

### ISSUE THREAD

**Issue by hujiajie** [tensorflow/tensorflow#60366]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.12.0

### Custom Code

Yes

### Current Behaviour?

Currently `tf.pow(x, y)` returns 1.0 (at least on CPU) when `x` is 1.0 and `y` is NaN, instead of propagating NaN like most other math ops. Can someone confirm which is the intended behavior? Thanks

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

x = tf.constant(1.0)
y = tf.sqrt(tf.constant(-1.0))
z = tf.pow(x, y)
print(z)
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@hujiajie,
Thank you for reporting the issue. Have you got the chance to have a look at this open issue https://github.com/tensorflow/tensorflow/issues/57747 https://github.com/tensorflow/tensorflow/issues/57757 where a similar issue has been reported and it is still open.
 Also I request to follow the similar feature which has been proposed to have the updates on the similar issue. Thank you!

**Comment by hujiajie** [comment]
I can follow on #57757, thanks!
