### ISSUE TITLE
TFLite model maker installation issue in kaggle

### ISSUE THREAD

**Issue by dsbyprateekg** [tensorflow/tensorflow#60364]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): kaggle
- TensorFlow installation (pip package or built from source): !pip install tflite-model-maker
- TensorFlow library (version, if pip package or github SHA, if built from source):2.8

### 2. Code

[[Provide code to help us reproduce your issues using one of the following options:](https://www.kaggle.com/code/iamprateek/tflite-model-maker-test/notebook)](https://www.kaggle.com/code/iamprateek/tflite-model-maker-test/notebook)

###3. ERROR: `Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

**Comment by tiruk007** [comment]
@dsbyprateekg 
Could you please elaborate more and provide detailed steps to replicate the issue reported here ?

Thank you!
