### ISSUE TITLE
`tf.bitcast` throws assertion on `osx-64` and `osx-arm64` with `2.11.1`

### ISSUE THREAD

**Issue by sumit0190** [tensorflow/tensorflow#60369]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

TF 2.11

### Custom Code

No

### OS Platform and Distribution

`osx-64`, `osx-arm64`

### Python version

3.10.10

### Current Behaviour?

For some reason, with version `2.11` (and `2.11.1`) the `bitcast` function hits an assertion in `casts.h`, no matter what the input. This only happens on `osx-64` and `osx-arm64`, and that too only with this version - older versions work correctly.

I also tried installing this version from `conda-forge` and `anaconda`, and both have the same behavior. So in summary, regardless of whether you install this from source or from the common `conda` channels the behavior is the same.

This **does not happen** with the versions installed via `pip`.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

x = [1., 2., 3.]
tf.bitcast(x, tf.qint8)
```

### Relevant log output

```shell
Assertion failed: (f == nullptr || dynamic_cast<To>(f) != nullptr), function down_cast, file casts.h, line 58.
```
</details>

**Comment by tilakrayal** [comment]
@sumit0190,
Thank you for the issue. I tried to execute the mentioned code on MacOS M1 tensorflow v2.11 and tf-nightly and it was executed without any assertion error. Kindly find the screenshot for the reference. Thank you!

![image (6)](https://user-images.githubusercontent.com/81610181/234526786-97f7298f-e9af-4eeb-aaaf-a5196199431c.png)

![image (7)](https://user-images.githubusercontent.com/81610181/234530148-5108edff-b1b2-4b11-aa4a-4238b0adc53b.png)

**Comment by sumit0190** [comment]
@tilakrayal Thanks for trying this out. This only happens on the binaries from `conda-forge` and `anaconda`, and when building from source. I assume the compiler or something else in our setup has something to do with it, but without any debugging information it's hard to understand what. Would you be able to provide us with some instructions on how we can debug this further?

**Comment by tilakrayal** [comment]
@sumit0190,
Could you please confirm whether you are following the metal plugin instructions for installing tensorflow? Thank you!
