### ISSUE TITLE
Need Add Perl to Supported API Languages

### ISSUE THREAD

**Issue by wbraswell** [tensorflow/tensorflow#60361]
This page lists all the languages with support for the TensorFlow API:
https://www.tensorflow.org/api_docs

Thanks to an official grant from The Perl Foundation, we have recently released a Perl API:
https://github.com/EntropyOrg/perl-AI-TensorFlow-Libtensorflow
https://metacpan.org/dist/AI-TensorFlow-Libtensorflow

How do we go about getting Perl added to the list?

**Comment by sachinprasadhs** [comment]
Thanks for opening the issue, I have created a bug internally to update the document under list of community contributions.

**Comment by wbraswell** [comment]
Tag @zmughal and @jjn1056 who worked on the Perl code with me

**Comment by saurabhmj11** [comment]
To get Perl added to the list of supported TensorFlow API languages on the TensorFlow website, you can submit a pull request to the TensorFlow website's GitHub repository. Here are the steps to follow:

Go to the TensorFlow website's GitHub repository: https://github.com/tensorflow/tensorflow

Click on the "Fork" button on the top-right corner to create a fork of the repository.

Clone the forked repository to your local machine using the following command: git clone https://github.com/<your_username>/tensorflow.git

Create a new branch for your changes using the following command: git checkout -b add-perl-api

Navigate to the _data/api_docs/languages.yml file in the repository and open it in a text editor.

Add the following lines to the file:

arduino
Copy code
- title: "Perl"
  url: "https://github.com/EntropyOrg/perl-AI-TensorFlow-Libtensorflow"
Save the file and commit your changes using the following commands:

sql
Copy code
git add _data/api_docs/languages.yml
git commit -m "Add Perl to supported API languages"
Push the changes to your forked repository using the following command: git push origin add-perl-api

Go to the original TensorFlow website's GitHub repository and click on the "New pull request" button.

Select your forked repository and the add-perl-api branch.

Provide a brief description of your changes and submit the pull request.

Once your pull request is reviewed and accepted by the TensorFlow team, Perl will be added to the list of supported TensorFlow API languages on the website.

**Comment by MarkDaoust** [comment]
This got hung up, but it looks like it might be moving again.

**Comment by sachinprasadhs** [comment]
@wbraswell , Perl is now listed as community build package in our API document https://www.tensorflow.org/api_docs.

Thanks a lot for contributing to the TensorFlow community. 

Could you please spare some to close the issue as well. Thanks!

**Comment by wbraswell** [comment]
@sachinprasadhs 
Yes the link looks good, thanks!  :-)
Should we be concerned that all the languages in the list are in alphabetical order, except for Perl?
```
C#
Haskell
Julia
MATLAB
R
Ruby
Rust
Scala
Perl
```

**Comment by sachinprasadhs** [comment]
Missed that small detail, you can ignore it for now, will take handle that in future. Thanks!

**Comment by wbraswell** [comment]
Okay thanks @sachinprasadhs !
Please post a comment back here in this thread when you fix the alphabetical ordering.
I am closing this issue for now!  :-)
