### ISSUE TITLE
Cannot get the values of tf.contrib.learn.DNNRegressor.predict() in boston.py

### ISSUE THREAD

**Issue by CTTC** [tensorflow/tensorflow#6037]
I am following the tutorials on the tensorflow's official website. And when I executed boston.py, I cannot get the prediction values. But when I executed iris.py, I can get the prediction values. The only difference I found between these two files is that boston.py uses DNNRegressor, but iris.py uses DNNClassifier. I am using **0.12 tensorflow, ubuntu 16.04, CUDA 8.0, cuDNN 5.1.5**, my gpu is **TITAN X (Pascal)**.
Here is the ending output of boston.py:
```bash
INFO:tensorflow:Summary name dnn/hiddenlayer_0:fraction_of_zero_values is illegal; using dnn/hiddenlayer_0_fraction_of_zero_values instead.
INFO:tensorflow:Summary name dnn/hiddenlayer_0:activation is illegal; using dnn/hiddenlayer_0_activation instead.
INFO:tensorflow:Summary name dnn/hiddenlayer_1:fraction_of_zero_values is illegal; using dnn/hiddenlayer_1_fraction_of_zero_values instead.
INFO:tensorflow:Summary name dnn/hiddenlayer_1:activation is illegal; using dnn/hiddenlayer_1_activation instead.
INFO:tensorflow:Summary name logits:fraction_of_zero_values is illegal; using logits_fraction_of_zero_values instead.
INFO:tensorflow:Summary name logits:activation is illegal; using logits_activation instead.
Predictions: <generator object _as_iterable at 0x7ff9f406db90>
```

**Comment by krishnanareddy** [comment]
+1 I have the same problem. Same environment as CTTC, except my gpu is GeForce GTX 1080.

**Comment by CTTC** [comment]
Waiting for help. Thanks

**Comment by terrytangyuan** [comment]
The predictions is iterable object. Try explicitly converting them into a list.

**Comment by CTTC** [comment]
@terrytangyuan I have tried like `  print("Predictions: {}".format(list(y)))`,but then the program just stuck to this line, and never ended. Besides, it output these two lines when the program ran to this print line:
```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:01:00.0)
INFO:tensorflow:Loading model from checkpoint: /tmp/tmpH45TBo/model.ckpt-5000-?????-of-00001.
```
So using list still not work.

**Comment by sandersk** [comment]
@CTTC @krishnanareddy, thanks for the bug report, and apologies for the error here.

With TF v0.12, the new default behavior for predict() is to return an iterable, as @terrytangyuan notes.

If you change the following:

```python
y = regressor.predict(input_fn=lambda: input_fn(prediction_set))
  print("Predictions: {}".format(str(y)))
```

to:

```python
y = regressor.predict(input_fn=lambda: input_fn(prediction_set))
  # .predict() returns an iterator; convert to a list and print predictions
  predictions = list(itertools.islice(y, 6))
  print("Predictions: {}".format(str(predictions)))
```

the example will work. I'll get the code in GitHub updated accordingly ASAP.

Let me know if you still encounter any errors.

**Comment by CTTC** [comment]
@sandersk  Thanks, that solved the problem

**Comment by krishnanareddy** [comment]
Yep, it solved for me too. Thanks for the prompt response.

**Comment by sandersk** [comment]
Sure thing! Updates to the tutorial and companion code are now posted:

https://github.com/tensorflow/tensorflow/commit/f8233e0f937d00a33e4e49cc593688de76159f0d

**Comment by ramurti** [comment]
Hey @sandersk,

   Would you mind updating the tutorial in https://www.tensorflow.org/versions/r0.11/tutorials/input_fn/ as well?

   Btw, before the error aforementioned, there is also a missing brace in the code

feature_cols = {k: tf.constant(data_set[k].values
                  for k in FEATURES}

    which is also there in the same tutorial.

Thanks!

**Comment by sandersk** [comment]
Hi @ramurti,

We version the tutorials in line with the versions of the TensorFlow API. The latest version of the tutorial can currently be found here (and will be published out as the default version of the tutorial on the TF site with the next TF release):

https://www.tensorflow.org/versions/master/tutorials/input_fn/

This version contains the updated `predict()` logic, as well as fixes the missing close-parenthesis in the code you cite.

Hope this helps,
Sanders
