### ISSUE TITLE
Tensorflow won't let pytorch import

### ISSUE THREAD

**Issue by RickSanchezStoic** [tensorflow/tensorflow#60389]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.12.0

### Custom Code

Yes

### OS Platform and Distribution

Docker image ubuntu:20.04 and above

### Current Behaviour?

Tensorflow 2.12.0 won't let torch import, causes some sort of deadlock, if tensorflow is imported first

### Standalone code to reproduce the issue

```shell
Code to reproduce the error:

docker run --rm -it ubuntu:22.04
// once inside
apt-get update && apt-get install python3
apt-get install pip
pip install tensorflow -y
pip install torch --extra-index-url https://download.pytorch.org/whl/cu118 -y
python3
import tensorflow
import torch
```
Note: the issue will persist even if you install torch-cpu, also on any Ubuntu:20.04 and above
```


### Relevant log output

_No response_</details>

**Comment by sampathweb** [comment]
Related to https://github.com/tensorflow/tensorflow/issues/60109
May be you want to follow-up on that Issue?

**Comment by mihaimaruseac** [comment]
Yeah, it's a duplicate of #60109

**Comment by tilakrayal** [comment]
@RickSanchezStoic,
This is a duplicate of the issue [#60109](https://github.com/tensorflow/tensorflow/issues/60109). Could you please close this issue, since it is already being tracked there? Thank you!

**Comment by mihaimaruseac** [comment]
Closing duplicate issue, no need to wait for stale bot
