### ISSUE TITLE
Maximum aspect ratio of camera for Android Mobile app & Android TV to use feature of Pose estimation?

### ISSUE THREAD

**Issue by IBSApple** [tensorflow/tensorflow#60411]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.7.0

### Custom Code

Yes

### Current Behaviour?

A bug happened!

### Standalone code to reproduce the issue

```shell
What is the maximum aspect ratio of camera for Android Mobile app & Android TV to use feature of Pose estimation?
```

### Relevant log output

_No response_</details>

**Comment by IBSApple** [comment]
??

**Comment by pjpratik** [comment]
Hi @IBSApple 

We will resize and pad the image to keep the aspect ratio and fit the expected size which can vary for different pose estimation algorithms.

The tensorflow provides [Movenet](https://www.tensorflow.org/hub/tutorials/movenet) tutorial for human body pose estimation which runs faster than real time (30+ FPS) and tested on most modern desktops, laptops, and phones.

Thanks.
