### ISSUE TITLE
TFLite converter does not support 4-dimensional input for dense operators 

### ISSUE THREAD

**Issue by vk1214** [tensorflow/tensorflow#60427]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 pro
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.12.0

### 2. Code
Simple model
https://colab.research.google.com/drive/1IaVtPj4RO2QWV3V1CgmNPnb2hmggkLmV?usp=sharing

### 3. Failure after conversion
As you can see in the only the second dense operator is converted well (blue). The first dense op is broken down into primitive ops (red)

![image](https://user-images.githubusercontent.com/87983167/234969243-b6197275-a19a-41da-aaeb-f00b8d75fbca.png)

### 5. (optional) Any other info / logs
Likely related issue: https://github.com/tensorflow/tensorflow/issues/57691

**Comment by pjpratik** [comment]
Hi @vk1214 Thanks for reporting the issue.

I was able to reproduce this issue on TF 2.12. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/5cfcb8eb28fcac6186db47bf8b4121ff/60427.ipynb).

@sachinprasadhs Could you please look into this?

Thanks.

**Comment by hayhan** [comment]
I have the same issue with TFLite converter on TF 2.15.0. Actually as long as input tensor (rank > 2) to a dense layer, the generated dense node in TFLite graph will be broken into primitive ops (see the read circle in vk1214 snapshot). Is this expected? I load this TFLite model with Python on my PC, and it can inference correctly. But when I load it on my development board, the inference runtime will report error on the dense layer. You can see the input size is 1x1 to the node of FullyConnected in the read circle. This seems not correct.

B.T.W. This issue is not related to https://github.com/tensorflow/tensorflow/issues/57691.

**Comment by pkgoogle** [comment]
Hi @vk1214, using our new library: [AI-Edge-Torch](https://github.com/google-ai-edge/ai-edge-torch) I was able to get a cleaner conversion, you can find more information here: [googleblog](https://developers.googleblog.com/en/ai-edge-torch-high-performance-inference-of-pytorch-models-on-mobile-devices/).

I have actually created a script for converting your model here:

```py
import ai_edge_torch
import torch
import torch.nn as nn


class SimpleModel(nn.Module):
    def __init__(self, input_shape, num_classes):
        super(SimpleModel, self).__init__()
        self.conv = nn.Conv2d(in_channels=input_shape[0], out_channels=32, kernel_size=3, padding='valid')
        self.dense1 = nn.Linear(32, 6)
        self.dense2 = nn.Linear(6*(input_shape[1]-2)*(input_shape[2]-2), num_classes)
        self.relu = nn.ReLU()
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        x = self.conv(x)
        x = self.relu(x)
        x = torch.permute(x, (0, 2, 3, 1)) # Dense is operating on the channels dimension
        x = self.dense1(x)
        x = x.view(x.size(0), -1)
        x = self.dense2(x)
        return self.softmax(x)


image_shape = (3, 32, 32)
model = SimpleModel(image_shape, 10)
sample_input = (torch.randn(1, 3, 32, 32),)

test = model(*sample_input)

edge_model = ai_edge_torch.convert(model.eval(), sample_input)
edge_model.export("test.tflite")
```

Here's the netron visualization for comparison:
![image](https://github.com/tensorflow/tensorflow/assets/132095473/169c199b-ba63-42ab-b110-c3967cd1e68f)

We also have [model-explorer](https://github.com/google-ai-edge/model-explorer), our visualization tool as well.

Please try them out and let us know if this resolves your issue. If you still need further help, feel free to open a new issue at the respective repo.
