### ISSUE TITLE
Docs problem. Notebook not found

### ISSUE THREAD

**Issue by Tialo** [tensorflow/tensorflow#60459]
Hello, I am new to tensoflow and right now I am reading your gides, particularly guide about tf.function. There you have a link to guide for "eager execution", but I don't have access to it. Is it my problem or you have broken link?

Guide for tf.function: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/function.ipynb#scrollTo=J122XQYG7W6w

Broken link, which is in the first block of code: 
"In TensorFlow 2, [eager execution](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/eager.ipynb) is turned on by default."

https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/eager.ipynb

Upd.
Also there is broken link here
https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/function.ipynb#scrollTo=ocxX-HVk7P2o

(See the [Transformer](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/text/transformer.ipynb) and [Deep Dream](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/generative/deepdream.ipynb) tutorials for example).

first link does not work

Upd. 2
Another broken link
https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/function.ipynb#scrollTo=JeD2U-yrbfVb

To learn more, see the [tf.data: Build TensorFlow input pipelines](https://github.com/tensorflow/docs/blob/master/site/guide/data) guide.

**Comment by synandi** [comment]
Hi @Tialo, Thank you for reporting the issue. The issue will move to closed status once the [#2223](https://github.com/tensorflow/docs/pull/2223) is merged. Thanks!

**Comment by Tialo** [comment]
Also it would be nice if you would fix those links at the end 
https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/function.ipynb#scrollTo=IKyrEY5GVX3M

Further reading
To learn about how to export and load a Function, see the [SavedModel guide](https://github.com/tensorflow/docs/blob/master/site/guide/saved_model). To learn more about graph optimizations that are performed after tracing, see the [Grappler guide](https://github.com/tensorflow/docs/blob/master/site/guide/graph_optimization). To learn how to optimize your data pipeline and profile your model, see the [Profiler guide](https://github.com/tensorflow/docs/blob/master/site/guide/profiler.md).

**Comment by synandi** [comment]
> Also it would be nice if you would fix those links at the end https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/function.ipynb#scrollTo=IKyrEY5GVX3M
> 
> Further reading To learn about how to export and load a Function, see the [SavedModel guide](https://github.com/tensorflow/docs/blob/master/site/guide/saved_model). To learn more about graph optimizations that are performed after tracing, see the [Grappler guide](https://github.com/tensorflow/docs/blob/master/site/guide/graph_optimization). To learn how to optimize your data pipeline and profile your model, see the [Profiler guide](https://github.com/tensorflow/docs/blob/master/site/guide/profiler.md).

@Tialo I've added these changes in this [commit](https://github.com/tensorflow/docs/pull/2223/commits/c4c12d8177f180cf705b7387dcc8b1af8adff199). Thank you!

**Comment by 8bitmp3** [comment]
Thanks, on it.

**Comment by 8bitmp3** [comment]
Using https://www.tensorflow.org/guide/function as the reference.

> "In TensorFlow 2, [eager execution](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/eager.ipynb) is turned on by default."

This should now take you to https://www.tensorflow.org/guide/basics or the corresponding Colab/notebook

> (See the [Transformer](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/text/transformer.ipynb) and [Deep Dream](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/generative/deepdream.ipynb) tutorials for example).

Same here: https://www.tensorflow.org/text/tutorials/transformer and https://www.tensorflow.org/tutorials/generative/deepdream

> To learn more, see the [tf.data: Build TensorFlow input pipelines](https://github.com/tensorflow/docs/blob/master/site/guide/data) guide.

And same here: https://www.tensorflow.org/guide/data

Feel free to reopen the issue if you see any other links that need to be fixed. Thank you.
