### ISSUE TITLE
Unable to download tflite-model-maker

### ISSUE THREAD

**Issue by UFthomasboosinger** [tensorflow/tensorflow#60455]
I'm experiencing difficulties when attempting to pip install tflite-model-maker in Google Colab with Python 3.10. I encounter one of the following three errors:

ERROR: Could not find a version that satisfies the requirement tflite-support>=0.4.2 (from tflite-model-maker) (from versions: 0.1.0a0.dev3, 0.1.0a0.dev4, 0.1.0a0.dev5, 0.1.0a0, 0.1.0a1)
ERROR: No matching distribution found for tflite-support>=0.4.2 (from tflite-model-maker)

ERROR: Unable to find version of scann==1.2.6

ERROR: Unable to find version of numba==0.53

I've also attempted to install tflite-model-maker-nightly and also cloning the source code from GitHub, but these methods have not resolved the issue.

If anyone could provide assistance or suggestions on how to successfully install tflite-model-maker, I would greatly appreciate it.

**Comment by tilakrayal** [comment]
@UFthomasboosinger,
Apologies for the inconvenience. We are working on it and will provide the update soon on this issue. Thank you!

**Comment by ubaidari** [comment]
@tilakrayal  when this issue resolved becouse till know colab disk become full on pip tflite model maker command ..Please provide update

**Comment by sachinprasadhs** [comment]
Hi, Thanks for opening the issue. Since this issue is a duplicate of issue https://github.com/tensorflow/tensorflow/issues/60431, it would be better to track the progress at single place, could you please close this issue. Thanks!

**Comment by tilakrayal** [comment]
@UFthomasboosinger,
As a temporary workaround could you please have a look at this tensorflow discussion forum comment provided from the team and let us know if it works in your case.

Could you use the Colab fallback runtime version option to choose Python 3.9 and install tflite-model-maker. 

https://discuss.tensorflow.org/t/tflite-model-maker-installation/16577/3

**Comment by KeepoXD** [comment]
Issue is still there(((

**Comment by sachinprasadhs** [comment]
> Issue is still there(((

Please follow https://github.com/tensorflow/tensorflow/issues/60431 for all the updates.

**Comment by funnypig** [comment]
You can use virtual environment for immediate model training. 

https://stackoverflow.com/a/76437519/12235226

**Comment by sachinprasadhs** [comment]
Closing the issue as duplicate of https://github.com/tensorflow/tensorflow/issues/60431
