### ISSUE TITLE
Not able to use tensorflow::mutex (../nptl/pthread_mutex_lock.c: No such file or directory)

### ISSUE THREAD

**Issue by laosiaudi** [tensorflow/tensorflow#6045]
Hi All,

I am trying to add a self-defined class under the core/common_runtime/ directory to log the information of each step([https://github.com/laosiaudi/tensorflow/blob/test/tensorflow/core/common_runtime/graph_logger.cc]) and try to use the tensorflow::mutex as step_stats_collector does, but when I run the example/tutorials/mnist/mnist_with_summaries.py, it throws out a segmentation fault. After inspecting via gdb, it reports the error **"../nptl/pthread_mutex_lock.c: No such file or directory."**.

Could you please provide some advice of how to use tensorflow::mutex correctly or how to fix such errors? Should I modify some BUILD files? I have been stuck in this for a while.

Thanks!

Information about the configuration:
Operating system: Ubuntu14.04
bazel version:  
-- Build label:0.4.1
-- Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar

Installed from source and no CUDA supported

**Comment by poxvoculi** [comment]
I'm puzzled by your description.  If you're failing to correctly link some mutex-related library, that should be a build error, not a runtime segfault.  Maybe gdb is having trouble finding the symbols corresponding to the binary?

Here are some third-party instructions for using gdb with bazel and TF.  I have not tried them myself.

https://gist.github.com/Mistobaan/738e76c3a5bb1f9bcc52e2809a23a7a1

**Comment by laosiaudi** [comment]
Thanks for the reply!
Sorry for the misunderstanding. But yes, I also think it shouldn't be a runtime segfault and gdb may not give the correct information. And today I put my self-defined class into the step_stats_collector.cc file(because my class uses the mutex in the same way as step_stats_collector does) and tried to run the same python examples, it still failed, giving error like
 **"terminate called after throwing an instance of 'std::system_error'
  what():  Operation not permitted"**.

And from the gdb, I check the backtrace for all the threads, most of them abort in the **std::condition_variable::wait**, so I think is it because my way of using mutex is not correct?
(my class's member function using mutex gets called in the ExecutorState::NodeDone)

Thanks!

**Comment by michaelisard** [comment]
I think this question is better addressed on [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is a usage question, not a bug report.

**Comment by laosiaudi** [comment]
@michaelisard Okay, thanks for advice!
