### ISSUE TITLE
native windows is not supported

### ISSUE THREAD

**Issue by git-guocc** [tensorflow/tensorflow#60451]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

win 11 pro

### Python version

3.9

### CUDA/cuDNN version

11.2/8.1

### GPU model and memory

laptop4060

### Current Behaviour?

使用conda安装完了tf==2.10.0后，可以使用GPU，用conda新建环境安装pytorch后，tensorflow环境下的GPU就不能使用了，请问怎么解决？

### Standalone code to reproduce the issue

```shell
(tensorflow) C:\Windows\System32>python -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
[]
```

### Relevant log output

_No response_</details>

**Comment by git-guocc** [comment]
有人成功过吗？Has anyone ever succeeded?Thanks

**Comment by synandi** [comment]
Hi @git-guocc, Please ensure that you followed the Tensorflow installation instructions from the [official website](https://www.tensorflow.org/install/pip#windows-native ). Thank you!
