### ISSUE TITLE
Same isssue cannnot install !pip install -q tflite-model-maker

### ISSUE THREAD

**Issue by ubaidari** [tensorflow/tensorflow#60466]
Same isssue cannnot install !pip install -q tflite-model-maker

_Originally posted by @UsamaHameed1 in https://github.com/tensorflow/tensorflow/issues/57086#issuecomment-1529139314_

**Comment by sachinprasadhs** [comment]
Hi, Could you please try installing Nightly version and let us know if you are still facing an error. Thanks!

**Comment by tilakrayal** [comment]
@ubaidari,
According to [Colab Updated to Python 3.10 7](https://medium.com/google-colab/colab-updated-to-python-3-10-27eb02daa162):

Colab’s fallback runtime version: Using the fallback runtime version temporarily allows access to the Python 3.9 runtime, and will be available until mid-May. This is available from the Command Palette via the Use fallback runtime version command when connected to a runtime. Of note, this setting does not persist across sessions — the command will need to be invoked on each new session.

As a temporary workaround, you can use the Colab fallback runtime version option to choose Python 3.9 and install tflite-model-maker. By doing this you will get RuntimeError and it can be ignored.

To access the command palette in Colab, presss cmd+shift+P and then type Use fallback runtime version and select it.

![Screenshot 2023-05-16 2 26 22 PM](https://github.com/tensorflow/tensorflow/assets/81610181/677e2a4a-ca91-4c6e-b314-c3c382748687)

By following the above process, I was able to execute [Model Maker Image Classification Tutorial 9](https://colab.sandbox.google.com/gist/chunduriv/847ff8f09621935471b3fb70b23cefbd/model-maker-image-classification-tutorial.ipynb).

Thank you!

**Comment by sachinprasadhs** [comment]
Closing the issue since it is duplicate of issue here https://github.com/tensorflow/tensorflow/issues/60431
