### ISSUE TITLE
xla_sharding in new version

### ISSUE THREAD

**Issue by mahmoodn** [tensorflow/tensorflow#60482]
Hi
What is the replacement for `from tensorflow.compiler.xla.experimental.xla_sharding import xla_sharding` in TF-2.12.0? For example, the function is `xla_sharding.split()`.

**Comment by synandi** [comment]
Hi @mahmoodn, Apologies for the delay. 
The `tensorflow.compiler.xla.experimental` was moved to `tensorflow.python.compiler.xla.experimental`. Kindly refer to this [commit](https://github.com/tensorflow/tensorflow/commit/6ed611beb95124234d07053581205eb8f3a865a5). 
You can import  xla_sharding using below command
```
from tensorflow.python.compiler.xla.experimental import xla_sharding
```
Thank you!

**Comment by mahmoodn** [comment]
Yes thank you.
