### ISSUE TITLE
Support CheckpointInputPipelineHook in Estimator MirrorStrategy

### ISSUE THREAD

**Issue by ZhangYaoFu** [tensorflow/tensorflow#60497]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

tf 1.15

### Custom Code

No

### Current Behaviour?

Failed to save pipeline info in checkpoint.

### Standalone code to reproduce the issue

```shell
mirrored_strategy = tf.distribute.MirroredStrategy()
    run_config = tf.estimator.RunConfig(
        model_dir=output_dir,
        save_checkpoints_steps=save_checkpoints_steps,
        train_distribute=mirrored_strategy,
        eval_distribute=mirrored_strategy,
        keep_checkpoint_max=max_ckp_num
    )

estimator.train(input_fn=input_fn, 
                hooks=[tf.data.experimental.CheckpointInputPipelineHook(estimator)],
                       steps=tf_args.test_train_step)
```

### Relevant log output

```shell
2023-05-03 21:53:52.048712: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at iterator_ops.cc:1081 : Failed precondition: RemoteCall is stateful.
```
</details>

**Comment by SuryanarayanaY** [comment]
@ZhangYaoFu ,

We are sorry to inform you that for 1.x versions there will not be any Feature additions. Its support already dropped and new features won't be added.Even estimator API also going to be deprecated soon. 

You can migrate to 2.x versions and if found any feature needed with 2.x versions then the same will be reviewed. You can find migration guide [here](https://www.tensorflow.org/guide/migrate/migrate_tf2).

Thanks!

**Comment by ZhangYaoFu** [comment]
> 
Thank you for reply
How to save pipeline info in checkpoint in 2.x version?

**Comment by SuryanarayanaY** [comment]
@ZhangYaoFu , 

Could you please check this [API](https://www.tensorflow.org/ranking/api_docs/python/tfr/keras/pipeline/ModelFitPipeline) is helpful for your requirement.
