### ISSUE TITLE
There are some installation problems such as 'tflite-model-maker'.

### ISSUE THREAD

**Issue by cugfk** [tensorflow/tensorflow#60493]
**System information**
- OS Platform and Distribution: **macOS 13.3.1 (MacBook Pro M2)**
- TensorFlow installed from (source or binary): [tf-nightly 2.14.0.dev20230503](https://pypi.org/project/tf-nightly/)
- TensorFlow version (or github SHA if from source): **Version:  2.14.0-dev20230503** 
- Python Version(Default): **Python 3.11.3**

**Provide the text output from 'tflite-model-maker'**

```
# Summary: Successfully installed TensorFlow(2.14.0-dev20230503) but struggling about installing tflite-model-maker
#
sudo pip3 install tflite-model-maker
haesunglee@MacBookPro14-haesunglee ~ % sudo pip3 install tflite-model-maker
Password:
WARNING: The directory '/Users/haesunglee/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting tflite-model-maker
  Downloading tflite_model_maker-0.4.2-py3-none-any.whl (577 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 577.3/577.3 kB 6.4 MB/s eta 0:00:00
Collecting tf-models-official==2.3.0 (from tflite-model-maker)
  Downloading tf_models_official-2.3.0-py2.py3-none-any.whl (840 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 840.9/840.9 kB 7.0 MB/s eta 0:00:00
...
...
...
Collecting tflite-model-maker
  Downloading tflite_model_maker-0.1.0-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.6/84.6 kB 6.1 MB/s eta 0:00:00
ERROR: Cannot install tflite-model-maker==0.1.2, tflite-model-maker==0.2.0, tflite-model-maker==0.2.1, tflite-model-maker==0.2.2, tflite-model-maker==0.2.3, tflite-model-maker==0.2.4, tflite-model-maker==0.2.5, tflite-model-maker==0.3.0, tflite-model-maker==0.3.1, tflite-model-maker==0.3.2, tflite-model-maker==0.3.3, tflite-model-maker==0.3.4, tflite-model-maker==0.4.0, tflite-model-maker==0.4.1 and tflite-model-maker==0.4.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    tflite-model-maker 0.4.2 depends on tflite-support>=0.4.2
    tflite-model-maker 0.4.1 depends on tflite-support-nightly
    tflite-model-maker 0.4.0 depends on tflite-support>=0.4.0
    tflite-model-maker 0.3.4 depends on tflite-support>=0.3.1
    tflite-model-maker 0.3.3 depends on tflite-support>=0.3.1
    tflite-model-maker 0.3.2 depends on tflite-support>=0.1.0rc4
    tflite-model-maker 0.3.1 depends on tflite-support>=0.1.0rc4
    tflite-model-maker 0.3.0 depends on tflite-support>=0.1.0rc4
    tflite-model-maker 0.2.5 depends on tflite-support==0.1.0rc4
    tflite-model-maker 0.2.4 depends on tflite-support==0.1.0rc4
    tflite-model-maker 0.2.3 depends on tflite-support==0.1.0rc3.dev2
    tflite-model-maker 0.2.2 depends on tflite-support==0.1.0rc3.dev2
    tflite-model-maker 0.2.1 depends on tflite-support==0.1.0rc3.dev2
    tflite-model-maker 0.2.0 depends on tflite-support==0.1.0rc3.dev2
    tflite-model-maker 0.1.2 depends on tflite-support==0.1.0rc3.dev2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
haesunglee@MacBookPro14-haesunglee ~ % 
haesunglee@MacBookPro14-haesunglee ~ % 



```

Last year I successfully installed tflite-model-maker on my 1st mac. I'm still using it on my 1st mac.
Please help me update and fix the tflite-model-maker.

**Comment by SuryanarayanaY** [comment]
Hi @cugfk ,

This is known issue and our dev team already working on it at #60431 . The problem mainly here might be due to Python version compatibility. If you are Ok with downgrading python to 3.9.x version and also few other dependencies like numpy and others which you may get under log stack. More context can be found in the mentioned ticket here. Thanks!

**Comment by cugfk** [comment]
> Hi @cugfk ,
> 
> This is known issue and our dev team already working on it at #60431 . The problem mainly here might be due to Python version compatibility. If you are Ok with downgrading python to 3.9.x version and also few other dependencies like numpy and others which you may get under log stack. More context can be found in the mentioned ticket here. Thanks!


=========================================
Thank you for helping it but I'm still struggling. 
Let's have a look.

**System information**
- OS Platform and Distribution: macOS 13.3.1 (MacBook Pro M2)
- **tensorflow-macos Version:         2.12.0**
- **tensorflow-metal Version:        0.8.0**
- Python Version: **Python 3.9.16**
- Pip versions:  pip 23.0.1 from /Users/haesunglee/miniconda/lib/python3.9/site-packages/pip (python 3.9)
- **TensorFlow Version:  2.12.0**
- numpy Version:  1.24.3

My log:
haesunglee@MacBookPro14-haesunglee ~ % 
haesunglee@MacBookPro14-haesunglee ~ % **sudo pip3 install tflite-model-maker** 
Password:
WARNING: The directory '/Users/haesunglee/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting tflite-model-maker
  Downloading tflite_model_maker-0.4.2-py3-none-any.whl (577 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 577.3/577.3 kB 12.6 MB/s eta 0:00:00
Collecting librosa==0.8.1
  Downloading librosa-0.8.1-py3-none-any.whl (203 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.8/203.8 kB 12.1 MB/s eta 0:00:00
Collecting lxml>=4.6.1
...
...
...
INFO: pip is looking at multiple versions of sentencepiece to determine which version is compatible with other requirements. This could take a while.
Collecting sentencepiece
  Downloading sentencepiece-0.1.98-cp39-cp39-macosx_11_0_arm64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 2.1 MB/s eta 0:00:00
  Downloading sentencepiece-0.1.97-cp39-cp39-macosx_11_0_arm64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 2.5 MB/s eta 0:00:00
  Downloading sentencepiece-0.1.96.tar.gz (508 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.6/508.6 kB 1.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading sentencepiece-0.1.95.tar.gz (508 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 508.7/508.7 kB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading sentencepiece-0.1.94.tar.gz (507 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 507.5/507.5 kB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Downloading sentencepiece-0.1.91.tar.gz (500 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 500.5/500.5 kB 2.6 MB/s eta 0:00:00
  **Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      /bin/sh: pkg-config: command not found
      Failed to find sentencepiece pkgconfig
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.**
haesunglee@MacBookPro14-haesunglee ~ %

**Comment by SuryanarayanaY** [comment]
@pjpratik , Please look into the issue. Thanks!

**Comment by pjpratik** [comment]
Hi @cugfk 

The `tflite-model-maker` installation has a problem and our team is working on it.

Meanwhile, if you are trying to perform image classification, you can try out the MediaPipe Model Maker [ImageClassifier](https://developers.google.com/mediapipe/solutions/vision/image_classifier/customize) API.

Thanks.

**Comment by cugfk** [comment]
> Hi @cugfk
> 
> The `tflite-model-maker` installation has a problem and our team is working on it.
> 
> Meanwhile, if you are trying to perform image classification, you can try out the MediaPipe Model Maker [ImageClassifier](https://developers.google.com/mediapipe/solutions/vision/image_classifier/customize) API.
> 
> Thanks.

Thank you for helping but there are some problems.
Let's have a look.
**System information**
- OS Platform and Distribution: macOS 13.3.1 (MacBook Pro M2)
- tensorflow-macos Version: 2.12.0
- tensorflow-metal Version: 0.8.0
- Python Version: Python 3.9.16
- Pip versions: pip 23.0.1 from /Users/haesunglee/miniconda/lib/python3.9/site-packages/pip (python 3.9)
- TensorFlow Version: 2.12.0
- numpy Version: 1.24.3

My log:
`
haesunglee@MacBookPro14-haesunglee ~ % sudo pip3 install mediapipe-model-maker 
Password:
WARNING: The directory '/Users/haesunglee/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting mediapipe-model-maker
  Downloading mediapipe_model_maker-0.1.1.1-py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.3/106.3 kB 13.9 MB/s eta 0:00:00
Requirement already satisfied: absl-py in ./miniconda/lib/python3.9/site-packages (from mediapipe-model-maker) (1.4.0)
INFO: pip is looking at multiple versions of mediapipe-model-maker to determine which version is compatible with other requirements. This could take a while.
  Downloading mediapipe_model_maker-0.1.1.0-py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.3/106.3 kB 12.7 MB/s eta 0:00:00
  Downloading mediapipe_model_maker-0.1.0.2-py3-none-any.whl (7.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 11.7 MB/s eta 0:00:00
  Downloading mediapipe_model_maker-0.1.0.1-py3-none-any.whl (7.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 11.7 MB/s eta 0:00:00
Requirement already satisfied: mediapipe>=0.9.0 in ./miniconda/lib/python3.9/site-packages (from mediapipe-model-maker) (0.9.3.0)
Requirement already satisfied: numpy in ./miniconda/lib/python3.9/site-packages (from mediapipe-model-maker) (1.23.5)
Requirement already satisfied: opencv-python in ./miniconda/lib/python3.9/site-packages (from mediapipe-model-maker) (4.7.0.72)
  Downloading mediapipe_model_maker-0.1.0-py3-none-any.whl (7.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 11.7 MB/s eta 0:00:00
ERROR: Cannot install mediapipe-model-maker==0.1.0, mediapipe-model-maker==0.1.0.1, mediapipe-model-maker==0.1.0.2, mediapipe-model-maker==0.1.1.0 and mediapipe-model-maker==0.1.1.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    mediapipe-model-maker 0.1.1.1 depends on mediapipe==0.9.2.1
    mediapipe-model-maker 0.1.1.0 depends on mediapipe==0.9.2.1
    mediapipe-model-maker 0.1.0.2 depends on mediapipe==0.9.0.1
    mediapipe-model-maker 0.1.0.1 depends on tensorflow>=2.10
    mediapipe-model-maker 0.1.0 depends on tensorflow>=2.10

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
haesunglee@MacBookPro14-haesunglee ~ % 
`

**Comment by pjpratik** [comment]
Hi @cugfk 

Sorry for the inconvenience caused. The mediapipe model maker is yet to support on arm mac devices. As a workaround please use colab for using the mediapipe model maker.

Please check this sample [gist](https://colab.research.google.com/gist/pjpratik/5920dc80a9e8c83174c36d9edded70b7/60493.ipynb) on getting started and refer to this [documentation](https://developers.google.com/mediapipe/solutions/vision/image_classifier/customize) on customizing the image classifier using model maker.

Thanks.

**Comment by smrati** [comment]
Still facing this issue
`ERROR: Cannot install tflite-model-maker==0.1.2, tflite-model-maker==0.2.0, tflite-model-maker==0.2.1, tflite-model-maker==0.2.2, tflite-model-maker==0.2.3, tflite-model-maker==0.2.4, tflite-model-maker==0.2.5, tflite-model-maker==0.3.3, tflite-model-maker==0.3.4, tflite-model-maker==0.4.0, tflite-model-maker==0.4.1 and tflite-model-maker==0.4.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    tflite-model-maker 0.4.2 depends on numba==0.53
    tflite-model-maker 0.4.1 depends on numba==0.53
    tflite-model-maker 0.4.0 depends on numba==0.53
    tflite-model-maker 0.3.4 depends on numba==0.53
    tflite-model-maker 0.3.3 depends on numba==0.53
    tflite-model-maker 0.2.5 depends on tflite-support==0.1.0rc4
    tflite-model-maker 0.2.4 depends on tflite-support==0.1.0rc4
    tflite-model-maker 0.2.3 depends on tflite-support==0.1.0rc3.dev2
    tflite-model-maker 0.2.2 depends on tflite-support==0.1.0rc3.dev2
    tflite-model-maker 0.2.1 depends on tflite-support==0.1.0rc3.dev2
    tflite-model-maker 0.2.0 depends on tflite-support==0.1.0rc3.dev2
    tflite-model-maker 0.1.2 depends on tflite-support==0.1.0rc3.dev2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
`

**Comment by Diam2023** [comment]
> Still facing this issue `ERROR: Cannot install tflite-model-maker==0.1.2, tflite-model-maker==0.2.0, tflite-model-maker==0.2.1, tflite-model-maker==0.2.2, tflite-model-maker==0.2.3, tflite-model-maker==0.2.4, tflite-model-maker==0.2.5, tflite-model-maker==0.3.3, tflite-model-maker==0.3.4, tflite-model-maker==0.4.0, tflite-model-maker==0.4.1 and tflite-model-maker==0.4.2 because these package versions have conflicting dependencies.
> 
> The conflict is caused by: tflite-model-maker 0.4.2 depends on numba==0.53 tflite-model-maker 0.4.1 depends on numba==0.53 tflite-model-maker 0.4.0 depends on numba==0.53 tflite-model-maker 0.3.4 depends on numba==0.53 tflite-model-maker 0.3.3 depends on numba==0.53 tflite-model-maker 0.2.5 depends on tflite-support==0.1.0rc4 tflite-model-maker 0.2.4 depends on tflite-support==0.1.0rc4 tflite-model-maker 0.2.3 depends on tflite-support==0.1.0rc3.dev2 tflite-model-maker 0.2.2 depends on tflite-support==0.1.0rc3.dev2 tflite-model-maker 0.2.1 depends on tflite-support==0.1.0rc3.dev2 tflite-model-maker 0.2.0 depends on tflite-support==0.1.0rc3.dev2 tflite-model-maker 0.1.2 depends on tflite-support==0.1.0rc3.dev2
> 
> To fix this you could try to:
> 
>     1. loosen the range of package versions you've specified
> 
>     2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts `

I checked numba version support for python version, It's only up to python3.9.
So I changed my python version to python3.9 then It's solved

**Comment by mgrpowers** [comment]
@Diam2023 same, am I going down the wrong path by using tflite-model-maker to generate a model from PascalVOC?
