### ISSUE TITLE
batch_matmul doesn't work on GPUs

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#605]
It seems not possible to register the `batch_matmul` operation to a GPU device. For example this fails:

    with tf.device('/gpu:0'):
        a = tf.constant(npr.rand(10, 5, 5).astype('float32'))
        b = tf.constant(npr.rand(10, 5, 5).astype('float32'))
        c = tf.batch_matmul(a, b)

    sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=False))
    sess.run(c)

This is a fundamental operation and so GPU support is rather important. I'm getting the error on Ubuntu 14.04 with CUDA 7.0.

**Comment by cesc-park** [comment]
I have same a question too.

**Comment by ponythewhite** [comment]
I would also greatly appreciate this to work on GPUs.

**Comment by zffchen78** [comment]
You can uncomment Ln270 of batch_matmul.cc to try it out on your machine.
We had mixed experience of the implementation (some reported working great,
some reported it rans out of gpu ram from time to time).

**Comment by alquraishi** [comment]
Any updates on this? It used to sort of work when uncommenting the relevant line in batch_matmul.cc, but now it often gives an error, specifically `Blas SGEMMBatched launch failed `. Also performance actually seems worse with it on the GPU than the CPU.

**Comment by girving** [comment]
This was fixed a while ago.  Woot.
