### ISSUE TITLE
Android Download page URL not available

### ISSUE THREAD

**Issue by TE-N-ElvenWang** [tensorflow/tensorflow#60504]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf2.8

### Custom Code

Yes

### Current Behaviour?

On the frontpage of the README.md, the Android Download link pointed to https://bintray.com/google/tensorflow/tensorflow/_latestVersion now is not available and will redirect to another page.

### Standalone code to reproduce the issue

```shell
Document issue which easy to found on frontpage of this github project.
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@TE-N-ElvenWang,
Could you please confirm whether you are mentioning to change in this link https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

The above link is not from the official tensorflow. We cannot handle the changes in the mentioned page and please take a  look at this official doc link for the reference.
https://www.tensorflow.org/lite/android
https://www.tensorflow.org/lite/android/quickstart

Thank you!
