### ISSUE TITLE
Is DTensor compatible with Horovod

### ISSUE THREAD

**Issue by dengpanyin** [tensorflow/tensorflow#60505]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.12

### Custom Code

Yes

### Current Behaviour?

Want to check if DTensor model parallel compatible with Horovod? Any code examples or Benchmark of DTensor model parallel? 

### Standalone code to reproduce the issue

```shell
NA
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@dengpanyin,
Could you please provide some more information/usecase on the above ask, it helps us to analyse the issue in an effective way. Thank you!

**Comment by tilakrayal** [comment]
Closing this as stale. Please reopen if this is still a valid request. Thank you!
