### ISSUE TITLE
tflite build on Windows crash if having multiple versions of Python in PATH

### ISSUE THREAD

**Issue by rikardn** [tensorflow/tensorflow#60501]
### System information

* tesorflow 2.12.0
* windows-latest in github actions (log https://github.com/pharmpy/tflite-runtime-wheels/actions/runs/4817630805/jobs/8578588825)

### Describe the problem

Building tflite 2.12.0 using bazel on Windows having multiple versions of Python in `PATH` fails. This seems to be because the `where` command is used to find which Python is in `PATH` and this then returns multiple paths which gets concatenated together.  Having multiple Pythons in `PATH` works when building on MacOS and Linux.

### Source code / logs

This is the end of the output from the compilation with the error: (notice that the paths to the two Pythons have both been put into `PYTHON_BIN_PATH`

```
Repository rule local_python_configure defined at:
  D:/a/tflite-runtime-wheels/tflite-runtime-wheels/third_party/py/python_configure.bzl:279:41: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_execution_config_python':
   Traceback (most recent call last):
	File "D:/a/tflite-runtime-wheels/tflite-runtime-wheels/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
		_check_python_bin(repository_ctx, python_bin)
	File "D:/a/tflite-runtime-wheels/tflite-runtime-wheels/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
		auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
	File "D:/a/tflite-runtime-wheels/tflite-runtime-wheels/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
		fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\python3.exe
C:\\hostedtoolcache\\windows\\Python\\3.9.13\\x64\\python3.exe' is not executable. Is it the python binary?
ERROR: D:/a/tflite-runtime-wheels/tflite-runtime-wheels/WORKSPACE:15:14: fetching local_python_configure rule //external:local_execution_config_python: Traceback (most recent call last):
	File "D:/a/tflite-runtime-wheels/tflite-runtime-wheels/third_party/py/python_configure.bzl", line 212, column 22, in _create_local_python_repository
		_check_python_bin(repository_ctx, python_bin)
	File "D:/a/tflite-runtime-wheels/tflite-runtime-wheels/third_party/py/python_configure.bzl", line 145, column 25, in _check_python_bin
		auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
	File "D:/a/tflite-runtime-wheels/tflite-runtime-wheels/third_party/remote_config/common.bzl", line 12, column 9, in auto_config_fail
		fail("%sConfiguration Error:%s %s\n" % (red, no_color, msg))
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\python3.exe
C:\\hostedtoolcache\\windows\\Python\\3.9.13\\x64\\python3.exe' is not executable. Is it the python binary?
ERROR: Analysis of target '//tensorflow/lite/python/interpreter_wrapper:_pywrap_tensorflow_interpreter_wrapper' failed; build aborted: Configuration Error: --define PYTHON_BIN_PATH='C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\python3.exe
C:\\hostedtoolcache\\windows\\Python\\3.9.13\\x64\\python3.exe' is not executable. Is it the python binary?
INFO: Elapsed time: 357.021s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (10 packages loaded, 15 targets configured)
FAILED: Build did NOT complete successfully (10 packages loaded, 15 targets configured)
Error: Process completed with exit code 1.
```

**Comment by mraunak** [comment]
Hi, @rikardn could you please share the steps you are following, so that we could reproduce the error?

**Comment by rikardn** [comment]
Sure. I am running this on github actions. Here is a link to the log of the failed run: https://github.com/pharmpy/tflite-runtime-wheels/actions/runs/4817630805/jobs/8578588825 and here is the workflow file: https://github.com/pharmpy/tflite-runtime-wheels/actions/runs/4817630805/workflow

The workflow is very simple

1. Setup Python (this adds a path to another version of Python to `PATH`) (Note: not `PYTHON_BIN_PATH`)
2. Clone tensorflow
3. Call `tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh`

The error in the log points to the script mashing both Python paths together. I have tested running by manually setting the `PATH` to contain only one version of Python and this works.

**Comment by pkgoogle** [comment]
Hi @terryheo, can you please take a look? Thanks.

**Comment by shangerxin** [comment]
@rikardn The CI build log is expired. Could you please share the log again?

And also please share your PYTHON_BIN_PATH value too. 

The current information indicate the settings point to an incorrect python executable 

```
Error in fail: Configuration Error: --define PYTHON_BIN_PATH='C:\\hostedtoolcache\\windows\\Python\\3.10.11\\x64\\python3.exe
C:\\hostedtoolcache\\windows\\Python\\3.9.13\\x64\\python3.exe' is not executable.
```

**Comment by pkgoogle** [comment]
Hi @rikardn, did the above work for you?
