### ISSUE TITLE
arguments in tf.math.greater should be the same type

### ISSUE THREAD

**Issue by cheyennee** [tensorflow/tensorflow#60511]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.12.0

### Custom Code

Yes

### OS Platform and Distribution

win11

### Current Behaviour?

According to [doc](https://tensorflow.google.cn/api_docs/python/tf/math/greater), the argument `x` and `y` in `tf.math.greater` should be the same type. However, in following snippet code, the type of argument `x` is int and the type of argument `y` is float32, it doesnt throw an exception, which is inconsitent with the doc.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
results={}
try:
  x = 16
  y_tensor = tf.random.uniform([4, 1, 1], dtype=tf.float32)
  y = tf.identity(y_tensor)
  results["res"] = tf.math.greater(x=x,y=y,)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)

results = 'res': <tf.Tensor: shape=(4, 1, 1), dtype=bool, numpy=
array([[[ True]],
      [[ True]],
      [[ True]],
      [[ True]]])>
```
```


### Relevant log output

_No response_</details>

**Comment by cheyennee** [comment]
Same issue can be found in `tf.math.greater_equal`.

**Comment by tilakrayal** [comment]
@cheyennee,
I tried to replicate the code on tf-nightly and also tried the code with alternative input values as well. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/0abeabafcbb96c557f335fce9b2d88b3/untitled1108.ipynb).


```
  #x = 16
  #print(type(x))
  #y_tensor = tf.random.uniform([4, 1, 1], dtype=tf.float32)
  #y = tf.identity(tf.random.uniform([4, 1, 1], dtype=tf.float32))
  #print(y)
  results["res"] = tf.math.greater(x=tf.identity(tf.random.uniform([4, 1, 1], dtype=tf.float32)),y=tf.identity(tf.random.uniform([4, 1, 1], dtype=tf.float32)))     
  print(results)

array([[[False]],

       [[False]],

       [[ True]],

       [[ True]]])>}

  #x = 16
  #print(type(x))
  #y_tensor = tf.random.uniform([4, 1, 1], dtype=tf.float32)
  #y = tf.identity(tf.random.uniform([4, 1, 1], dtype=tf.float32))
  #print(y)
  results["res"] = tf.math.greater(x=tf.identity(tf.random.uniform([4, 1, 1], dtype=tf.float16)),y=tf.identity(tf.random.uniform([4, 1, 1], dtype=tf.float16)))     
  print(results)

array([[[ True]],

       [[ True]],

       [[False]],

       [[ True]]])>}
```

**Comment by tilakrayal** [comment]
@cheyennee,
I tried to execute the mentioned code by providing `x=16 (int)` and `y=1.2 (float)`, and it was failing as intended. Whereas with the code you mentioned the input 'y' was converting to the **tf.Tensor** which might be the reason the code was not failing. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/484b364414e77b07627f0c13834be3ee/untitled1244.ipynb).

Thank you!
