### ISSUE TITLE
Speech recognition : No code is present

### ISSUE THREAD

**Issue by abbasalid** [tensorflow/tensorflow#60515]
Please add source code for android for speech recognition currently only resources file is present

https://github.com/tensorflow/examples/tree/master/lite/examples/speech_recognition/android/app/src/main/res
@synandi  @tensorflow-copybara can u please help

**Comment by pkgoogle** [comment]
Hi @abbasalid, we are migrating these examples to the equivalent litert-samples: https://github.com/google-ai-edge/litert-samples/tree/main/examples. Please open an issue there if the examples there do not satisfy your need here. Thanks.
