### ISSUE TITLE
type of argument x in tf.math.rsqrt should be float

### ISSUE THREAD

**Issue by cheyennee** [tensorflow/tensorflow#60519]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.12.0

### Custom Code

Yes

### OS Platform and Distribution

win11

### Current Behaviour?

According to [doc](https://tensorflow.google.cn/api_docs/python/tf/math/rsqrt), the argument of `x` in `tf.math.rsqrt` should be `bfloat16, half, float32, float64`. But when the values of `x` includes both float and bool, it wont throw an exception as following snippet code 1 shows, which is unexpected. What's more, snippet code 2 indicates that the type of `x` can be complex, which is inconsistent with the documentation.

### Standalone code to reproduce the issue

Snippet code 1: 
```
import tensorflow as tf
results={}
try:
  x_0 = 0.0
  x_1 = 1024
  x_2 = -1.0
  x_3 = -1.0
  x_4 = 0.0
  x_5 = False
  x_6 = True
  x = [x_0,x_1,x_2,x_3,x_4,x_5,x_6,]
  results["res"] = tf.math.rsqrt(x=x,)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)
# results={'res': <tf.Tensor: shape=(7,), dtype=float32, numpy=
array([    inf, 0.03125,     nan,     nan,     inf,     inf, 1.     ],
      dtype=float32)>}
```

Snippet code 2:
```
import tensorflow as tf
results={}
try:
  x = 3
  results["res"] = tf.math.rsqrt(x=x,)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)
# results={'err': "Error:Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128\n\t; NodeDef: {{node Rsqrt}}; Op<name=Rsqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Rsqrt]"}
```

### Relevant log output

_No response_</details>

**Comment by cheyennee** [comment]
@tilakrayal  According to you，in snippet1 code, when there are multiple datatypes, the input will be considered as the strings. Does this mean that `tf.math.rsqrt` can accept string type argument? I think this is inconsistent with the documentation.
I read the content on issue #43494, and understand why the issue occur on snippet2 code, thx.

**Comment by tilakrayal** [comment]
@cheyennee,
RSQRT is supported as a builtin operator, could you please check the issue at https://github.com/tensorflow/tensorflow/issues/58048.
Also, refer to the comment https://github.com/tensorflow/tensorflow/issues/58048#issuecomment-1276584557 for the code file reference to the registered RSQRT builtin op.

Also in the documentation of the **rsqrt()** and it was observed that the issue was that the operator couldn't handle negative values as input so adding a tf.math.abs() before rsqrt solved the issue. Thank you!
