### ISSUE TITLE
tf.math.real can accept string tensor, inconsistent with the documentation.

### ISSUE THREAD

**Issue by drewshark** [tensorflow/tensorflow#60526]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf-nightly

### Custom Code

Yes

### Python version

3.9

### Current Behaviour?

Following the documentation: https://www.tensorflow.org/api_docs/python/tf/math/real, the input of tf.math.real should be a numeric tensor. However, this API can still pass when processing the string tensor. In contrast, other math operators such as tf.math.reduce_all, tf.math.log will raises an InvalidArgumentError.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
x = tf.constant(["Hello"])
res = tf.math.real(x)
print(res)
```

### Relevant log output

```shell
tf.Tensor([b'Hello'], shape=(1,), dtype=string)
```
</details>

**Comment by alexrosen45** [comment]
This issue has been resolved as of https://github.com/tensorflow/tensorflow/pull/60540.

**Comment by tilakrayal** [comment]
@drewshark,
I tried to execute the code on tf-nightly(2.14.0-dev20230615) and it was providing the error for **tf.math.real** . Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/6b8ef392fe64fddcd374c69d28f3a89a/untitled1205.ipynb) and also the related PR #60540  was also merged.

```
      .def_property_readonly(
          "is_numeric",
          [](tensorflow::DataType self) {
            return tensorflow::DataTypeIsNumeric(tensorflow::BaseType(self));
          },
          "Returns whether this is a numeric data type.")

```
https://github.com/tensorflow/tensorflow/pull/60540/files

Thank you!
