### ISSUE TITLE
Cannot find the source code -> 'gen_stateless_random_ops'

### ISSUE THREAD

**Issue by Yeojoon** [tensorflow/tensorflow#60524]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tensorflow 2.12.0

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04.6 LTS

### Python version

3.9.7

### CUDA/cuDNN version

12.0

### Current Behaviour?

from tensorflow.python.ops import gen_stateless_random_ops (in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/ops/stateless_random_ops.py)

I would like to check the source code for 'gen_stateless_random_ops', but I cannot find this. Could you please help me with this? Thank you for your help in advance!

### Standalone code to reproduce the issue

```shell
N/A
```

### Relevant log output

_No response_</details>

**Comment by synandi** [comment]
@Yeojoon, could you please confirm if the issue is resolved? Thank you!

**Comment by Yeojoon** [comment]
Oh sorry. I am going to close the issue now!
