### ISSUE TITLE
error message is inconsistent with documentation in tf.nn.leaky_relu

### ISSUE THREAD

**Issue by cheyennee** [tensorflow/tensorflow#60521]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.12.0

### Custom Code

Yes

### OS Platform and Distribution

win11

### Current Behaviour?

According to [doc](https://tensorflow.google.cn/api_docs/python/tf/nn/leaky_relu), the argument `features` can be `float16, float32, float64, int32, int64`. But the error message in following snippet code indicates that the type of `features` can only be `float16, float32, float64` without `int`.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
results={}
try:
  features = [True]
  results["res"] = tf.nn.leaky_relu(features=features,)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)
# results={'err': "Error:Value for attr 'T' of bool is not in the list of allowed values: half, bfloat16, float, double\n\t; NodeDef: {{node LeakyRelu}}; Op<name=LeakyRelu; signature=features:T -> activations:T; attr=alpha:float,default=0.2; attr=T:type,default=DT_FLOAT,allowed=[DT_HALF, DT_BFLOAT16, DT_FLOAT, DT_DOUBLE]> [Op:LeakyRelu]"}
```

### Relevant log output

_No response_</details>

**Comment by punndcoder28** [comment]
Hi. Is anyone working on the issue to update the docs/error message? Would love to take it up and start working on the issue

**Comment by malla456** [comment]
Hi @cheyennee ,
According to the official documentation, tf.nn.leaky_relu is designed to
operate on numerical data types, including float16, float32, float64, int32,
and int64. While integer inputs are accepted, boolean values are not
compatible with this function. For further clarification, please refer to the attached [gist](https://colab.sandbox.google.com/gist/malla456/e0f88e248989948fc47dc86dbc741fd9/60521.ipynb). 
Thank you!
