### ISSUE TITLE
Getting error with using coco-ssd model with the latest tensorflow

### ISSUE THREAD

**Issue by hacktronics** [tensorflow/tensorflow#60535]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

4.5.0

### Custom Code

Yes

### OS Platform and Distribution

Windows

### Current Behaviour?

when I try to use the net.detect(frame), it throws me error:
TypeError: _tensorflow_tfjs_core__WEBPACK_IMPORTED_MODULE_0__.util.convertBackendValuesAndArrayBuffer is not a function
    at MathBackendCPU.readSync (backend_cpu.js:99:1)
    at Engine.readSync (engine.js:943:1)
    at Tensor.dataSync (tensor.js:297:1)
    at d.infer (coco-ssd.es2017.esm.min.js:17:1)
Even though I am using the latest tensorflow JS libraries.

### Standalone code to reproduce the issue

```shell
I am trying to use the coco-ssd model to do object detection. In my package.json I have:
    "@tensorflow-models/coco-ssd": "^2.2.2",
    "@tensorflow/tfjs": "^4.5.0",
    "@tensorflow/tfjs-backend-cpu": "^4.5.0",
    "@tensorflow/tfjs-backend-webgl": "^4.5.0",

for some reasons, I want to use the latest tensorflow libraries, as my project uses other things also.
I have the following code:
const tf = require('@tensorflow/tfjs');
const _tfCPUBackend = require('@tensorflow/tfjs-backend-cpu');
const _tfWebglBackend = require('@tensorflow/tfjs-backend-webgl');
const cocoSsd = require('@tensorflow-models/coco-ssd');

I have also set the tf.setBackend('webgl'), and tf.ready() before cocoSsd.load()
but when I try to use the net.detect(frame), it throws me error:
TypeError: _tensorflow_tfjs_core__WEBPACK_IMPORTED_MODULE_0__.util.convertBackendValuesAndArrayBuffer is not a function
    at MathBackendCPU.readSync (backend_cpu.js:99:1)
    at Engine.readSync (engine.js:943:1)
    at Tensor.dataSync (tensor.js:297:1)
    at d.infer (coco-ssd.es2017.esm.min.js:17:1)
Even though I am using the latest tensorflow JS libraries.
```

### Relevant log output

_No response_</details>

**Comment by SuryanarayanaY** [comment]
Hi @hacktronics ,

I believe this issue to be reported at TFJS repo. We have separate repo for TFJS which can be found [here](https://github.com/tensorflow/tfjs/issues).

Thanks!
