### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow==2.11.1 (from versions: 2.13.0rc0)

### ISSUE THREAD

**Issue by rgaufman** [tensorflow/tensorflow#60566]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

v2.13.0-rc0-0-g525da8a93ec 2.13.0-rc0

### Custom Code

Yes

### OS Platform and Distribution

MacOS 13.3.1

### Python version

Python 3.11.3

### Current Behaviour?

I need to install an older version of tensorflow to use with other libraries, but it appears none are available except for " 2.13.0rc0" - is this because I am on Apple Silicon?

```
$ pip3 install tensorflow==2.11.1
ERROR: Could not find a version that satisfies the requirement tensorflow==2.11.1 (from versions: 2.13.0rc0)
ERROR: No matching distribution found for tensorflow==2.11.1
```

From the output, the only versions I can choose from is just "2.13.0rc0"

### Standalone code to reproduce the issue

```shell
$ pip3 install tensorflow==2.11.1
```
```


### Relevant log output

_No response_</details>

**Comment by mihaimaruseac** [comment]
That is correct. Compare [platforms supported in 2.11.1](https://pypi.org/project/tensorflow/2.11.1/#files) and [those supported in 2.13.0-rc0](https://pypi.org/project/tensorflow/2.13.0rc0/#files)
