### ISSUE TITLE
error message of tf.abs is not the same with documentation

### ISSUE THREAD

**Issue by cheyennee** [tensorflow/tensorflow#60561]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.12.0

### Custom Code

Yes

### Current Behaviour?

The error message in following code miss the type `complex64` and `complex128` in [doc](https://tensorflow.google.cn/api_docs/python/tf/math/abs). The doc contains type `float16, float32, float64, int32, int64, complex64, complex128`.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
results={}
try:
  x_0 = True
  x_1 = False
  x_2 = False
  x_3 = False
  x_4 = False
  x = (x_0,x_1,x_2,x_3,x_4,)
  results["res"] = tf.abs(x=x,)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)
# results={'err': "Error:Value for attr 'T' of bool is not in the list of allowed values: bfloat16, half, float, double, int8, int16, int32, int64\n\t; NodeDef: {{node Abs}}; Op<name=Abs; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_INT8, DT_INT16, DT_INT32, DT_INT64]> [Op:Abs]"}
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@cheyennee,
It was mentioned in the official document that it returns for complex64 or complex128 input, the returned Tensor will be of type float32 or float64, respectively. This might be the reason that complex64 or complex128 are not included in the error. Thank you!
https://tensorflow.google.cn/api_docs/python/tf/math/abs#returns

**Comment by cheyennee** [comment]
@tilakrayal  Got that. Thanks.
