### ISSUE TITLE
zsh: illegal hardware instruction python on python 3.10 Mac M1

### ISSUE THREAD

**Issue by Spartanzhao** [tensorflow/tensorflow#60569]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.12

### Custom Code

Yes

### OS Platform and Distribution

Mac M1

### Mobile device

Mac M1

### Python version

3.10

### Current Behaviour?

zsh: illegal hardware instruction python on python 3.10 Mac M1 

### Standalone code to reproduce the issue

```shell
It shows zsh: illegal hardware instruction python on python 3.10 Mac M1
```

### Relevant log output

_No response_</details>

**Comment by Spartanzhao** [comment]
I trying to install tensorflow by anaconda but only has 2.10 version, miniconda only as 2.11 version, pip install has bugs when import tensorflow: zsh: illegal hardware instruction python

**Comment by ameyb22** [comment]
I'd recommend installing tensorflow-deps using conda first and then installing other stuff using pip.
1. `conda install -c apple tensorflow-deps`
2. `pip install -r requirements.txt`

requirements.txt containing: 
```
tensorflow-macos
tensorflow-metal
jupyter
# other packages
...
```

**Comment by Spartanzhao** [comment]
> I'd recommend installing tensorflow-deps using conda first and then installing other stuff using pip.
> 
> 1. `conda install -c apple tensorflow-deps`
> 2. `pip install -r requirements.txt`
> 
> requirements.txt containing:
> 
> ```
> tensorflow-macos
> tensorflow-metal
> jupyter
> # other packages
> ...
> ```

Thanks a lot, but where can I get requirements.txt? are there any official one?

**Comment by tilakrayal** [comment]
@Spartanzhao,
I tried to install Tensorflow on Apple M1 oand it is  working, so you can install Tensorlflow by using one of the Conda, Miniconda or Miniforge approach.  I tried to follow [Get started with tensorflow-metal](https://developer.apple.com/metal/tensorflow-plugin/) with Miniconda3 instructions. 
Could you please try with `arm64:Apple silicon`

During the instructions  [Download Conda environment ](https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh) Miniconda3-latest-MacOSX-arm64.sh file will be downloaded and replace  **.sh file** with miniconda.sh in command bash **~/miniconda.sh -b -p $HOME/miniconda** as mentioned in first step 
1. Set up and please follow all steps from
 2. Install base TensorFlow as below:


```
bash ~/Miniconda3-latest-MacOSX-arm64.sh -b -p $HOME/miniconda
source ~/miniconda/bin/activate
conda install -c apple tensorflow-deps
```
Please use the command source **~/miniconda/bin/activate** if you want to use/activate Miniconda environment

If you are specifically looking to go with Miniforge approach then please have a look at  this [link](https://caffeinedev.medium.com/how-to-install-tensorflow-on-m1-mac-8e9b91d93706) and for [Miniconda-Article](https://medium.com/mlearning-ai/install-tensorflow-on-mac-m1-m2-with-gpu-support-c404c6cfb580) and also please refer [Releases-Table](https://developer.apple.com/metal/tensorflow-plugin/#:~:text=Releases-,tensorflow%2Dmacos,Distributed%20training,-Troubleshooting)

https://developer.apple.com/metal/tensorflow-plugin/  -- reference. Thank you!

**Comment by Spartanzhao** [comment]
Thank you, I think I had solved the issue!

**Comment by tilakrayal** [comment]
@Spartanzhao,
Glad the issue got resolved. Could you please feel free to move this issue to closed status. Thank you!

**Comment by Spartanzhao** [comment]
Okay!

**Comment by rotimiakanni** [comment]
> Thank you, I think I had solved the issue!

@Spartanzhao How did you solve it?
