### ISSUE TITLE
Building from source with clang and nvcc?

### ISSUE THREAD

**Issue by p3achyjr** [tensorflow/tensorflow#60578]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11

### Custom Code

Yes

### OS Platform and Distribution

Debian GNU/Linux 10

### Python version

3.9

### GCC/Compiler version

gcc9/clang12

### CUDA/cuDNN version

11.3

### GPU model and memory

Nvidia T4

### Current Behaviour?

The docs say that TF 2.11 is supported with gcc 9, but clang/llvm builds significantly faster. How can I use bazel to at least try to build using clang and nvcc at the same time?

Changing GCC_HOST_COMPILER_PATH="<clang-path>" fails. Using my own crosstool-top with clang seems to work, but I'm not sure if this ends up building the CUDA kernels with clang as well.

### Standalone code to reproduce the issue

```shell
# from .bazelrc

build --crosstool_top=//toolchain:clang_suite

build:cuda --repo_env TF_NEED_CUDA=1
# build:cuda --crosstool_top=@local_config_cuda//crosstool:toolchain
build:cuda --@local_config_cuda//:enable_cuda

build:tf_gpu --action_env PYTHON_BIN_PATH="/opt/conda/bin/python3"
build:tf_gpu --action_env PYTHON_LIB_PATH="/bin"
build:tf_gpu --python_path="/opt/conda/bin/python3"
build:tf_gpu --action_env PYTHONPATH="/home/axlui/p3achyGo/python:/usr/lib/llvm-12/bin:/home/axlui/.local/bin:/usr/local/cuda/bin:/opt/conda/bin:/opt/conda/condabin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/go/bin"
build:tf_gpu --define=with_xla_support=true
build:tf_gpu --action_env TF_CUDA_VERSION="11"
build:tf_gpu --action_env TF_CUDNN_VERSION="8"
build:tf_gpu --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda-11.3"
build:tf_gpu --action_env CUDNN_INSTALL_PATH="/usr/local/cuda"
build:tf_gpu --action_env TF_CUDA_COMPUTE_CAPABILITIES="7.5"
build:tf_gpu --action_env LD_LIBRARY_PATH="/usr/local/cuda/lib64:/usr/local/nccl2/lib:/usr/local/cuda/extras/CUPTI/lib64"
build:tf_gpu --action_env GCC_HOST_COMPILER_PATH="/usr/bin/x86_64-linux-gnu-gcc-9"
# build:tf_gpu --action_env CC="/usr/lib/llvm-12/bin/clang"
# build:tf_gpu --action_env CXX="/usr/lib/llvm-12/bin/clang++"
# build:tf_gpu --action_env GCC_HOST_COMPILER_PATH="/usr/lib/llvm-12/bin/clang"
build:tf_gpu --config=cuda
```

### Relevant log output

_No response_</details>

**Comment by SuryanarayanaY** [comment]
Hi @p3achyjr ,

Starting from TF2.13v, Linux builds are being built with Clang and the instructions for same also can be found [here](https://www.tensorflow.org/install/source#install_clang_recommended_linux_only). 

You may try the build for Tf21.3 and let us know the outcome. Thanks.
