### ISSUE TITLE
label_image CPU inference: Up to 4 CPUs are invoked, and other CPUs are idle

### ISSUE THREAD

**Issue by megleo** [tensorflow/tensorflow#60579]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf2.8

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu18.04

### Mobile device

android

### Python version

2.0

### Bazel version

2.8

### Current Behaviour?

Hello, TF teams:

When using the **label_image** tool ([path: tensorflow_src/tensorflow/tree/master/tensorflow/examples/label_image](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/label_image)) to  my device CPU  with command `./label_image -m mobilenet_quant_v1_224.tflite -c 1000`,   fond that **Up to 4 CPUs are invoked, and other CPUs are idle**;

I would like to ask, does your company have such settings _**Up to 4 CPUs can be invoked**_  in the code?

---
The status of the CPUs is shown in the figure (obtained by Qualcomm Snapdragon Profiler software).

![726e6d15-884e-4e4e-a275-2c07c3f06c3b](https://github.com/tensorflow/tensorflow/assets/50650564/130d7742-32fe-44b8-a0af-b33cc03a4e47)
This device has 4 CPUs, so all of them are invoked.

![2](https://github.com/tensorflow/tensorflow/assets/50650564/4cec653b-e6f3-49a9-a3a0-bedd8b0b5b70)
This device has 8 CPUs, so only 4 of them are invoked.

Very thanks
megleo
 

### Standalone code to reproduce the issue

```shell
adb push label_image to android device:
adb wait-for-device
adb root
adb remount
adb shell "mkdir -p /data/tf"

adb push ./label_image/mobilenet_quant_v1_224.tflite /data/tf
adb push ./label_image/labels.txt /data/tf
adb push ./label_image/grace_hopper.bmp /data/tf
adb push ./label_image/label_image /data/tf

2.  adb shell && cd data/tf
./label_image -m mobilenet_quant_v1_224.tflite -c 1000
```

### Relevant log output

_No response_</details>

**Comment by freedomtan** [comment]
Since you are using .tflite model, I assume what you used was the the [tflite label_image](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/examples/label_image) rather than the tf one. If you run `./label_image -h`, you can find
```
--threads, -t: number of threads
```

However, setting the number of threads to be > 4 may not be what you want. As far as I know, no 8-core Android devices have homogeneous cores, but usually multi-thread libraries do not deal with non-homogeneous cores well.

**Comment by pjpratik** [comment]
Hi @megleo 

Could you please refer the above [comment](https://github.com/tensorflow/tensorflow/issues/60579#issuecomment-1545062464) and let us know if it helps.

Thanks.
