### ISSUE TITLE
Install error on Ubuntu 16.04 with Cuda 8.

### ISSUE THREAD

**Issue by chasep255** [tensorflow/tensorflow#6057]
I am trying to install tensorflow 0.12.  I am running Ubuntu 16.04 with a GTX 1080.  I get the following error.

./configure 
~/Desktop/tensorflow-r0.12 ~/Desktop/tensorflow-r0.12
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] n
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python3.5/dist-packages
  /usr/lib/python3/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.5/dist-packages]

Using python library path: /usr/local/lib/python3.5/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] n
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 8.0
Please specify the location where cuDNN 8.0 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Invalid path to cuDNN  toolkit. Neither of the following two files can be found:
/usr/local/cuda-8.0/lib64/libcudnn.so.8.0
/usr/local/cuda-8.0/libcudnn.so.8.0
/usr/local/cuda/lib64/libcudnn.so.8.0
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5
Please specify the location where cuDNN 5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 6.1
.
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/chase/Desktop/tensorflow-r0.12/third_party/gpus/cuda_configure.bzl", line 517
		_create_cuda_repository(repository_ctx)
	File "/home/chase/Desktop/tensorflow-r0.12/third_party/gpus/cuda_configure.bzl", line 432, in _create_cuda_repository
		_cuda_toolkit_path(repository_ctx, cuda_version)
	File "/home/chase/Desktop/tensorflow-r0.12/third_party/gpus/cuda_configure.bzl", line 148, in _cuda_toolkit_path
		str(repository_ctx.path(cuda_toolkit...)
	File "/home/chase/Desktop/tensorflow-r0.12/third_party/gpus/cuda_configure.bzl", line 148, in str
		repository_ctx.path(cuda_toolkit_path).realpath
Object of type 'path' has no field "realpath".

**Comment by poxvoculi** [comment]
Please include all the information requested by the new issue template.  You did not specify the OS, or GPU model.

**Comment by gunan** [comment]
@chasep255, any reason why you elected to not use the pip package?

Also, what bazel version are you using?

**Comment by chasep255** [comment]
I fixed the issue.  I was using an older bazel.


Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone
-------- Original message --------From: gunan <notifications@github.com> Date: 12/19/16  3:17 AM  (GMT-05:00) To: tensorflow/tensorflow <tensorflow@noreply.github.com> Cc: chasep255 <chasepreuninger@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [tensorflow/tensorflow] Install error on Ubuntu 16.04 with Cuda
  8. (#6057) 
@chasep255, any reason why you elected to not use the pip package?
Also, what bazel version are you using?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tensorflow/tensorflow","title":"tensorflow/tensorflow","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tensorflow/tensorflow"}},"updates":{"snippets":[{"icon":"PERSON","message":"@gunan in #6057: @chasep255, any reason why you elected to not use the pip package?\r\n\r\nAlso, what bazel version are you using?"}],"action":{"name":"View Issue","url":"https://github.com/tensorflow/tensorflow/issues/6057#issuecomment-267905907"}}}
