### ISSUE TITLE
TensorFlow Lite Converter: Full Integer Quantization Failure

### ISSUE THREAD

**Issue by oniigiirii** [tensorflow/tensorflow#60574]
### 1. System information

- OS Platform and Distribution: Linux Ubuntu 22.04.2 LTS
- TensorFlow installation: pip package
- TensorFlow library: v2.11.0
- Python Version: 3.9

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

#### Code Snippet

Example Full Integer Quantization performed on a simple model with 1x input of shape (1,), 2x Fully Connected layers with Relu Activations.
```
import tensorflow as tf
import os
tf.get_logger().setLevel('ERROR')
import tensorboard as tb
import numpy as np
import librosa
import matplotlib.pyplot as plt
import datetime

def converter_issue():

    input_shape = (1,)

    def representative_ds():
        for _ in range(100):
            x = np.random.uniform(0, 2*np.pi, size=input_shape)
            yield [x.astype(np.float32)]

    model = tf.keras.Sequential([
        tf.keras.layers.Input(input_shape),
        tf.keras.layers.Dense(16),
        tf.keras.layers.ReLU(),
        tf.keras.layers.Dense(16),
        tf.keras.layers.ReLU(),
        tf.keras.layers.Dense(1)
    ])

    model.summary()

    model.compile(optimizer="adam", loss="mse", metrics=["mae"])

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_ds
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_type = tf.int8
    converter.inference_input_type = tf.int8  
    converter.inference_output_type = tf.int8 

    tflite_quant_model = converter.convert()

    return tflite_quant_model


if __name__ == "__main__":
    model = converter_issue()
```

### 3. Failure after conversion

The conversion is successful but the converter prints out the following message:
```
WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.
/home/edge-ml/miniconda3/envs/tf/lib/python3.9/site-packages/tensorflow/lite/python/convert.py:765: UserWarning: Statistics for quantized inputs were expected, but not specified; continuing anyway.
  warnings.warn("Statistics for quantized inputs were expected, but not "
fully_quantize: 0, inference_type: 6, input_inference_type: INT8, output_inference_type: INT8
```
which indicates that the converter was not able to do a full integer quantization although [https://www.tensorflow.org/lite/performance/post_training_quantization#integer_only](url) clearly states that a full integer quantization is possible as long as a representative data set is presented and the inference input type and inference output type are correctly set.

**Comment by pjpratik** [comment]
Hi @oniigiirii 

I have tried to reproduce the issue and observed that model has INT8 qunatization which can be analyzed with [TensorFlow Lite Model Analyzer](https://www.tensorflow.org/lite/guide/model_analyzer) and netron.
```
Tensors of Subgraph#0
  T#0(serving_default_input_1:0) shape_signature:[-1, 1], type:INT8
  T#1(sequential/dense_2/MatMul) shape:[1, 16], type:INT8 RO 16 bytes, buffer: 2, data:[., ., ., ., r, ...]
  T#2(sequential/dense_1/MatMul) shape:[16, 16], type:INT8 RO 256 bytes, buffer: 3, data:[., ., 8, ., -, ...]
  T#3(sequential/dense/MatMul1) shape:[16, 1], type:INT8 RO 16 bytes, buffer: 4, data:[:, |, ., ., ., ...]
  T#4(sequential/dense/MatMul;sequential/re_lu/Relu;sequential/dense/BiasAdd) shape_signature:[-1, 16], type:INT8
  T#5(sequential/dense_1/MatMul;sequential/re_lu_1/Relu;sequential/dense_1/BiasAdd) shape_signature:[-1, 16], type:INT8
  T#6(StatefulPartitionedCall:0) shape_signature:[-1, 1], type:INT8
```
Please find the [gist](https://colab.research.google.com/gist/pjpratik/fca14d42222bb05454921de63d44714a/60574.ipynb) here and let us know if it helps.

Thanks.

**Comment by oniigiirii** [comment]
Oh. Thank you. The 'fully_quantize: 0' included in the warning message confused me and made me think that the converter failed at doing a full integer quantization. 
I tested the model with int8 inputs and it worked as expected.
