### ISSUE TITLE
Nested namespaces in TF Lite profiler/telemetry headers require clients to support C++ 17

### ISSUE THREAD

**Issue by nathanmartz** [tensorflow/tensorflow#60576]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows (possibly others)
- TensorFlow installation (pip package or built from source): Built from source
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.12

### 2. Code

Compile TF Lite C++ 2.12 on Windows in a project that does not support C++ 17.

### 3. Failure after conversion

Any files that directly include profiler.h and/or telemetry_status.h will fail to compile with the error: 

language feature 'nested-namespace-definition' requires compiler flag '/std:c++17' but compiler flag is set

### 4. (optional) RNN conversion support

N/A

### 5. (optional) Any other info / logs

This issue appears to have been introduced in https://github.com/tensorflow/tensorflow/commit/082c562ec7a6a33da2a6b60c191474b5ae6b73e2 and appeared starting in 2.12.0 Prior to this commit/release, these objects were in the vanilla TF Lite interface.

From what I can tell, these two files are the only users of C++ 17 style nested namespaces, so seems like these could simply match the rest of the codebase and use a syntax compatible with older versions of C++

**Comment by sachinprasadhs** [comment]
Hi, Thanks for reporting the issue.

Tensorflow has migrated it's codebase to support C++ 17 and it is suggested for the users to follow the same.

**Comment by nathanmartz** [comment]
In our case, building tflite itself with C++ 17 is fine, but we're not ready to move our codebase to C++17 because some of our customers are still locked to earlier versions, so the fact that these changes are in a header that we have to include is the main issue of concern.

Given that this is just syntactic sugar on namespace declaration and the majority of TF Lite headers don't use this style, it would be great to either revert these namespace changes or use the pre C++ 17 syntax.

**Comment by pkgoogle** [comment]
Hi @nathanmartz, apologies, but we don't intend to revert our support for C++17 moving forward, as such we cannot make this change. If you are able to use v2.11 or earlier, I suggest you do so. Alternatively, you are free to fork the repo and maintain your own version with your required changes. If there are no more open items for this, please feel free to close as not planned.

**Comment by nathanmartz** [comment]
Understood. thanks for the clarification.
