### ISSUE TITLE
Learning works on 0.11 but fails on .12rc0 (Titan X Pascal) 

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#6059]
I have a training experiment which fails to learn using TF 0.12rc0, but works fine if I revert TF version to 0.11 and run on the same machine. Unfortunately there are no errors logged, and the symptom is that original run starts improving after 5 minutes, but the 0.12rc0 graph fails to improve. This is blocking our transition to 0.12. It would take a bit of time to isolate the difference to a specific op, meanwhile, any suggestions of things to try?

NVIDIA-SMI 370.28                 Driver Version: 370.28 
/usr/local/cuda-8.0/lib64/libcublas.so.8.0.27
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.5
<img width="506" alt="screen shot 2016-12-03 at 3 39 03 pm" src="https://cloud.githubusercontent.com/assets/23068/20862957/de5d955a-b96e-11e6-8c7f-fa268465872f.png">

**Comment by poxvoculi** [comment]
Are you using the same versions of CUDA and CUDNN with both releases?

Release notes https://github.com/tensorflow/tensorflow/releases  say there were some changes to gradient calculations.  If you could dump the activation/gradient values from a single step on both versions, initialized from the same checkpoint, that might show something useful.

**Comment by ashern** [comment]
Just to bump this - I'm seeing exactly the same behavior. Models which train well on 0.11 do not improve in 0.12.

I am using the same GPU & library versions as @yaroslavvb. I've also attempted to use cudnn 5.0 without success.

I will try and post the requested values when I have time as well.

**Comment by yaroslavvb** [comment]
Retrying at HEAD and on a Maxwell GPU, next will try on a K80

**Comment by yaroslavvb** [comment]
I pulled from head and built it and things seem to learn again 
tf.__git_version__=="b'0.12.0-rc0-437-g6d63f67'"

Here's a version built for CUDA 8/Ubuntu
https://www.dropbox.com/s/pyu92nj4oifw6cg/tensorflow-0.12.0rc0-cp35-cp35m-linux_x86_64.whl?dl=0

**Comment by michaelisard** [comment]
Shall I close the bug or wait for more confirmation?

**Comment by ashern** [comment]
@michaelisard I am currently re-running tests with libraries built from head. Can we leave this open please through tomorrow?

**Comment by michaelisard** [comment]
Sure!

**Comment by ashern** [comment]
@michaelisard I can confirm that this seems to work fine w/ head. Thank you!

**Comment by michaelisard** [comment]
Good news. Closing.
