### ISSUE TITLE
Issue while installing tensorflow-lite-maker on Google Colab

### ISSUE THREAD

**Issue by carl-krikorian** [tensorflow/tensorflow#60598]
While trying to install and run tensorflow-lite-maker on google Colab I encountered many issues.
I even tried following the example notebooks shown in the documentation [here](https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models/modify/model_maker/object_detection.ipynb#scrollTo=qhl8lqVamEty) and encountered similar issues.
Find output here:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  libportaudio2
0 upgraded, 1 newly installed, 0 to remove and 24 not upgraded.
Need to get 65.4 kB of archives.
After this operation, 223 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 libportaudio2 amd64 19.6.0-1build1 [65.4 kB]
Fetched 65.4 kB in 4s (17.5 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package libportaudio2:amd64.
(Reading database ... 122519 files and directories currently installed.)
Preparing to unpack .../libportaudio2_19.6.0-1build1_amd64.deb ...
Unpacking libportaudio2:amd64 (19.6.0-1build1) ...
Setting up libportaudio2:amd64 (19.6.0-1build1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 577.3/577.3 kB 14.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 840.9/840.9 kB 22.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 25.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.3/88.3 kB 10.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.0/128.0 kB 14.2 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement tflite-support>=0.4.2 (from tflite-model-maker) (from versions: 0.1.0a0.dev3, 0.1.0a0.dev4, 0.1.0a0.dev5, 0.1.0a0, 0.1.0a1)
ERROR: No matching distribution found for tflite-support>=0.4.2 (from tflite-model-maker)
ERROR: Could not find a version that satisfies the requirement opencv-python-headless==4.1.2.30 (from versions: 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.59, 3.4.17.61, 3.4.17.63, 3.4.18.65, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62, 4.5.5.64, 4.6.0.66, 4.7.0.68, 4.7.0.72)
ERROR: No matching distribution found for opencv-python-headless==4.1.2.30
```

The issue seems to be with python 3.10 version, unfortunately it doesn't seem possible to downgraded to previous versions of python on colab without running into errors. Please advise.

**Comment by tilakrayal** [comment]
@carl-krikorian,
According to [Colab Updated to Python 3.10 7](https://medium.com/google-colab/colab-updated-to-python-3-10-27eb02daa162):

**Colab’s fallback runtime version:** Using the fallback runtime version temporarily allows access to the Python 3.9 runtime, and will be available until mid-May. This is available from the Command Palette via the Use fallback runtime version command when connected to a runtime. Of note, this setting does not persist across sessions — the command will need to be invoked on each new session.

As a temporary workaround, you can use the Colab fallback runtime version option to choose Python 3.9 and install tflite-model-maker. By doing this you will get RuntimeError and it can be ignored.

To access the command palette in Colab, presss cmd+shift+P and then type Use fallback runtime version and select it.

![Screenshot 2023-05-16 2 26 22 PM](https://github.com/tensorflow/tensorflow/assets/81610181/677e2a4a-ca91-4c6e-b314-c3c382748687)

By following the above process, I was able to execute [Model Maker Image Classification Tutorial 9](https://colab.sandbox.google.com/gist/chunduriv/847ff8f09621935471b3fb70b23cefbd/model-maker-image-classification-tutorial.ipynb).

Thank you!

**Comment by carl-krikorian** [comment]
Hello @tilakrayal, 
This indeed seems to have solved my issue. I managed to access the command palette through tools and after starting the notebook, the use fallback runtime became available.
Many Thanks! As this workaround is temporary (and it seems it will be impossible after may), are there any plans to fix the issue with 3.10?

**Comment by tilakrayal** [comment]
@carl-krikorian,
Yeah, there is an issue which was raised for the similar issue where it is under the developer's priority list. 
https://github.com/tensorflow/tensorflow/issues/60431
I request, could you please follow the respective issue for the updates and as the alternative workaround is working in your case, Could you please feel free to move this issue to closed status. Thank you!

**Comment by carl-krikorian** [comment]
@tilakrayal 
I see, keep up the great work! Thanks again for the support!

**Comment by Zz98761032** [comment]
> @carl-krikorian, According to [Colab Updated to Python 3.10 7](https://medium.com/google-colab/colab-updated-to-python-3-10-27eb02daa162):
> 
> **Colab’s fallback runtime version:** Using the fallback runtime version temporarily allows access to the Python 3.9 runtime, and will be available until mid-May. This is available from the Command Palette via the Use fallback runtime version command when connected to a runtime. Of note, this setting does not persist across sessions — the command will need to be invoked on each new session.
> 
> As a temporary workaround, you can use the Colab fallback runtime version option to choose Python 3.9 and install tflite-model-maker. By doing this you will get RuntimeError and it can be ignored.
> 
> To access the command palette in Colab, presss cmd+shift+P and then type Use fallback runtime version and select it.
> 
> ![Screenshot 2023-05-16 2 26 22 PM](https://user-images.githubusercontent.com/81610181/238590614-677e2a4a-ca91-4c6e-b314-c3c382748687.png)
> 
> By following the above process, I was able to execute [Model Maker Image Classification Tutorial 9](https://colab.sandbox.google.com/gist/chunduriv/847ff8f09621935471b3fb70b23cefbd/model-maker-image-classification-tutorial.ipynb).
> 
> Thank you!

Unfortunately, the fall-down command has not available now.
