### ISSUE TITLE
tf.config.list_physical_devices('CPU')

### ISSUE THREAD

**Issue by jsxzhub** [tensorflow/tensorflow#60595]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

v2.12.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Debain 11

### Python version

3.9.2

### Current Behaviour?

"tf.config.list_physical_devices('CPU')" only show one CPU, but my machine has multiple CPUs. 

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

physical_devices = tf.config.list_physical_devices("CPU")
for device in physical_devices:
    print(device)
```

### Relevant log output

```shell
PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')
```
</details>

**Comment by jsxzhub** [comment]
![image](https://github.com/tensorflow/tensorflow/assets/6895480/461ee918-8386-4fc4-9e57-96059db5c37b)

Is this tensorflow bug? 

How does TensorFlow utilize multiple CPUs in this situation?

**Comment by yeison** [comment]
I don't believe that this is supposed to print the number of CPU cores.  I think it just prints the actual physical device.

`tf.config.list_physical_devices("CPU")`

**Comment by jsxzhub** [comment]
That means the machine has 48 CPUs, but I can only use one CPU?
![image](https://github.com/tensorflow/tensorflow/assets/6895480/73b7fe76-f45d-4d4b-8a7b-043583165bdc)

**Comment by sachinprasadhs** [comment]
Hi, 

Both `os.cpu_count()` and `multiprocessing.cpu_count()` will give you the number of cores across all the CPUs in your machine.

`tf.config.list_physical_devices('CPU')` will return the physical CPU devices.

Tensorflow uses all the cores in the available CPU. 



![image](https://github.com/tensorflow/tensorflow/assets/73069040/1b6418fc-369a-4c6a-884e-7cae1b4b37aa)

**Comment by jsxzhub** [comment]
Thank you!
It is recommended that tensorflow be modified to display as many cpus as there are cpus.
for example:
PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU') 
PhysicalDevice(name='/physical_device:CPU:1', device_type='CPU')
