### ISSUE TITLE
`decode_image` can not load (or check properly) the bmp format 

### ISSUE THREAD

**Issue by innat** [tensorflow/tensorflow#60603]
### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11

### Custom Code

Yes

### Current Behaviour?

On a dataset that contains bmp format files, the `tf.io.decode_image` or `tf.io.decode_bmp` method can not load the bmp files for some samples. This samples can be converted to png format but as I like to use built in decoding method for bmp image, I'm trying as follows but facing the issue for some bmp files and for some cases it loads correctly. 

### Standalone code to reproduce the issue

[samples](https://drive.google.com/file/d/1B1w4-9EsSwvGukA_9yDZxZN7v1PeQmdm/view?usp=share_link)

```
image = tf.io.read_file('1.bmp')
image = tf.io.decode_image(image, channels=3, expand_animations=False)
```

```
InvalidArgumentError: {{function_node __wrapped__DecodeImage_device_/job:localhost/replica:0/task:0/device:CPU:0}} Number of channels inherent in the image must be 1, 3 or 4, was 0 [Op:DecodeImage]
```

**Comment by innat** [comment]
@tilakrayal Thanks for your quick test. 

> I tried to replicate the issue with the provided .bmp file, as mentioned it is failing with the same error.  But when I tried with the different .bmp file it is working without any issue. 

That's the primary issue, Because of that, I can't use `tf.io.decode_image` or `tf.io.decode_bmp` method inside the `tf.data` API. The above bmp file is not corrupted. It can be loaded with python libraries, please see below.

```python
from PIL import Image
image = Image.open('1.bmp')
image # OK

import matplotlib.pyplot as plt
image = plt.imread('1.bmp')
plt.imshow(image) #  OK

import tensorflow as tf
image = tf.io.read_file('1.bmp')
image = tf.io.decode_image(
    image, channels=3, expand_animations=False
) # Error
```

**Comment by freedomtan** [comment]
the `1.bmp` is a 772x600 1-bit bitmap. Current the bitmap decoder only supports depth = 8-, 24-,  or 32-bit

```
$ file /tmp/1.bmp 
/tmp/1.bmp: PC bitmap, Windows 3.x format, 772 x 600 x 1, image size 60000, cbSize 60062, bits offset 62
```

**Comment by innat** [comment]
@tilakrayal 
Any update on this? As pointed out above, I think it should be supported.

**Comment by tilakrayal** [comment]
@innat,
Apologies for the delay.

@sachinprasadhs,
Could you please take a look at this issue. Thank you!
