### ISSUE TITLE
tf sometims return constant value

### ISSUE THREAD

**Issue by xiedeacc** [tensorflow/tensorflow#60605]
### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.8.4

### OS Platform and Distribution

ubuntu18.04

### Bazel version

5.2.0

### GCC/Compiler version

gcc-11.3.0

### Current Behaviour?

my project use a fm model for ctr prediction (click through rate). I notice sometimes tf always return a constant value 1 ,  if want result became  valid, must restart program, or reload model.  I'm sure I use a same model.

**Comment by SuryanarayanaY** [comment]
Hi @xiedeacc ,

Thanks for your time reporting the issue. Unfortunately i couldn't understand the problem with the provided information.

Please confirm whether you are using pip wheel or building from source. Please submit some code snippet to replicate and check the issue. Need more context to understand your issue. Please provide all the details. 

Thanks!

**Comment by xiedeacc** [comment]
reason is: RunCallable input sequence was must same with .meta_graph_def input sequence
