### ISSUE TITLE
Get tensor dimension error when retrain Inception3

### ISSUE THREAD

**Issue by universewill** [tensorflow/tensorflow#6061]
I followed the 'retrain.py' example, but get error.
I print the bottleneck tensor shape, and it is [1, 1, 1, 2048]. It runs into error when execute "tf.placeholder_with_default(
        bottleneck_tensor, shape=[None, BOTTLENECK_TENSOR_SIZE],
        name='BottleneckInputPlaceholder')"

It seems that bottleneck_tensor is a tensor with 4 dimension, what does each dimension mean? And Why it is not a 2 dimension tensor?

My code:

    BOTTLENECK_TENSOR_NAME = 'pool_3:0'
    BOTTLENECK_TENSOR_SIZE = 2048
    sess = tf.InteractiveSession()
    graph = create_inception_graph()
    bottleneck_tensor = graph.get_tensor_by_name(ensure_name_has_port(
        BOTTLENECK_TENSOR_NAME))
    print bottleneck_tensor.get_shape()

    bottleneck_input = tf.placeholder_with_default(
        bottleneck_tensor, shape=[None, BOTTLENECK_TENSOR_SIZE],
        name='BottleneckInputPlaceholder')

The error:

> ValueError: Shapes must be equal rank, but are 4 and 2 for 'BottleneckInputPlaceholder' (op: 'PlaceholderWithDefault') with input shapes: [1,1,1,2048].

The retrain.py:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py

**Comment by universewill** [comment]
I referred to the source code of Incception3 model. Also it confuses me that i can not find the tensor name as 'pool_3' in the model graph.

The model definition link:
https://github.com/tensorflow/models/blob/master/inception/inception/slim/inception_model.py

**Comment by poxvoculi** [comment]
This forum is for bug reports and similar, not usage questions.  This sort of question is best asked on stackoverflow.  You might have a better chance of getting help if you post more contextual information: a link to the tutorial you're following or a list of the commands you've executed.  I spent a few minutes looking at this and can't figure out how you came up with pool_3 as a bottleneck.

**Comment by universewill** [comment]
The bottle_neck definition came from the example 'retrain.py', and the link is already added at the end of my question content.
Thanks for your reminding, i will post this question on stackoverflow
