### ISSUE TITLE
TFLite Model maker installation issue in google colab notebook

### ISSUE THREAD

**Issue by dsbyprateekg** [tensorflow/tensorflow#60612]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.3

### Custom Code

No

### OS Platform and Distribution

linux

### Python version

3.8

### GPU model and memory

V100

### Current Behaviour?

I am trying to install tflite model maker in colab using command `!pip install tflite-model-maker` and it is taking so much disk space to install.
I have 55 GB disk space left but installation is stopped in between due to no space error-
`ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device`
I am attaching here logs of the installation.
[model-maker-issue-colab.txt](https://github.com/tensorflow/tensorflow/files/11494698/model-maker-issue-colab.txt)

### Standalone code to reproduce the issue

```shell
Run following command in colab-
!pip install tflite-model-maker
```

### Relevant log output

```shell
ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device
```
</details>

**Comment by tilakrayal** [comment]
@dsbyprateekg,
According to [Colab Updated to Python 3.10 7](https://medium.com/google-colab/colab-updated-to-python-3-10-27eb02daa162):

Colab’s fallback runtime version: Using the fallback runtime version temporarily allows access to the Python 3.9 runtime, and will be available until mid-May. This is available from the Command Palette via the Use fallback runtime version command when connected to a runtime. Of note, this setting does not persist across sessions — the command will need to be invoked on each new session.

As a temporary workaround, you can use the Colab fallback runtime version option to choose Python 3.9 and install tflite-model-maker. By doing this you will get RuntimeError and it can be ignored.

To access the command palette in Colab, presss cmd+shift+P and then type Use fallback runtime version and select it.

![Screenshot 2023-05-16 2 26 22 PM](https://github.com/tensorflow/tensorflow/assets/81610181/fd03e11d-9ec6-4ba1-b5bb-8a989c94d4ce)

By following the above process, I was able to execute [Model Maker Image Classification Tutorial 9](https://colab.sandbox.google.com/gist/chunduriv/847ff8f09621935471b3fb70b23cefbd/model-maker-image-classification-tutorial.ipynb).

Thank you!

**Comment by dsbyprateekg** [comment]
@tilakrayal any time line when it will work with Python 3.10?

**Comment by tilakrayal** [comment]
@dsbyprateekg,
Yes, there is an issue which was raised for the similar issue where it is under the developer's priority list.
https://github.com/tensorflow/tensorflow/issues/60431
I request, could you please follow the respective issue for the updates and as the temporary workaround please try the above mentioned process. Thank you!

**Comment by dsbyprateekg** [comment]
Thanks, I will follow.
