### ISSUE TITLE
unable to compile tensorflow c++ code using cmake 

### ISSUE THREAD

**Issue by ranjith502** [tensorflow/tensorflow#60627]
i followed this steps

1) i cloned the repo

2) cd tensorflow

3) mkdir examples

in examples folder i created helloworld.cc file and cmakelist.txt

this is cmakelist.txt file 

cmake_minimum_required(VERSION 3.8.0)
project(examples)

# Specify the path to the TensorFlow source directory
set(TENSORFLOW_SOURCE_DIR "D:/github_issues/tensorflow/tensorflow")

# Add the TensorFlow source directory to the CMake module path
list(APPEND CMAKE_MODULE_PATH "${TENSORFLOW_SOURCE_DIR}/cmake")

# Add the TensorFlow include directories
include_directories(${TENSORFLOW_SOURCE_DIR})
include_directories(${TENSORFLOW_SOURCE_DIR}/tensorflow/cc)
include_directories(${TENSORFLOW_SOURCE_DIR}/tensorflow/core)

# Build the hello-world executable
add_executable(hello-world hello-world.cc)
target_link_libraries(hello-world tensorflow)

after running the command cmake --build . --config Release

i got this error 

D:\github_issues\tensorflow\examples\hello-world.cc(1,10): fatal  error C1083: Cannot open include file: 'tensorflow/cc/client/cl
ient_session.h': No such file or directory [[D:\github_issues\tensorflow\examples\build\hello-world.vcxproj]]
![2](https://github.com/tensorflow/tensorflow/assets/85454586/3a8c3dae-fcd6-48c0-bf89-bb64af5bccfc)
![3](https://github.com/tensorflow/tensorflow/assets/85454586/61d90c15-2468-47cf-a074-e1190693bd4a)
![4](https://github.com/tensorflow/tensorflow/assets/85454586/359b81e6-30f9-43dc-bc04-f563726bc2c4)
![5](https://github.com/tensorflow/tensorflow/assets/85454586/6796388f-0f45-40b7-a369-47c6586e31c1)

**Comment by SuryanarayanaY** [comment]
Hi @ranjith502 ,

We observed that you have not followed the standard template to report the issue.Please find the [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=&projects=&template=tensorflow_issue_template.yaml) for same.

Also Cmake used to build TF1.x versions. Now Bazel is the recommended tool and officially supported tool for building Tensorflow from source. We recommend to use Bazel as build tool since it is officially tool for build and testing and also have extensive support both from Tensorflow and Bazel teams.

**Comment by ranjith502** [comment]
thanks @SuryanarayanaY 
can give me some links how to build and run a simple program using bazel .. i already installed brazel in my system 
and followed this link https://tensorflow.juejin.im/api_guides/cc/guide.html
still i face the error 

![8](https://github.com/tensorflow/tensorflow/assets/85454586/a26b9065-248b-433f-8246-80e1fbce9e30)

**Comment by SuryanarayanaY** [comment]
Hi @ranjith502 ,

You can check the documentation [here](https://www.tensorflow.org/install/source) as reference for building Tensorflow pip package. For C++ build options you can refer to the [bazelrc](https://github.com/tensorflow/tensorflow/blob/master/.bazelrc) file of TF repo. We don't have exhaustive documentation form building C++ API.

Please refer to some older tickets [link1](https://github.com/tensorflow/tensorflow/issues/23561#issuecomment-444221082),[link2](https://github.com/tensorflow/tensorflow/issues/59887)  for reference.

But before that please submit the issue in the issue template attached above providing all the details required.

Thanks!

**Comment by ranjith502** [comment]
@SuryanarayanaY  thanks brother i will do that

**Comment by SuryanarayanaY** [comment]
@ranjith502 ,

Could you please confirm whether you are able to compile the C++ code.

Please let us know if still have any issues.

Thanks!

**Comment by ranjith502** [comment]
Yes brother.. it is working , i solved all the errors

**Comment by SuryanarayanaY** [comment]
Hi @ranjith502 ,

Thanks for confirmation. Could you please spare some time to close the ticket if issue resolved. Thanks!
