### ISSUE TITLE
AttributeError: 'module' object has no attribute 'deprecated'

### ISSUE THREAD

**Issue by FCInter** [tensorflow/tensorflow#6063]
### Environment info
Operating System: Ubuntu 14.04.5 LTS

Installed version of CUDA and cuDNN: 
No CUDA, I use CPU-only.

* Pip version: pip 1.5.4
* Python version: 2.7.6
* Operating System: Ubuntu 14.04.5 LTS
* Tensorflow version: tensorflow-0.12.0rc0-cp27-none-linux_x86_64 , CPU-only
### Description:

I was testing the tutorial example of LSTM [here](https://www.tensorflow.org/versions/r0.12/tutorials/recurrent/index.html). 
I followed the instructions to download the code and dataset, and run the program using the command. But the code cannot execute and reports the error message:
`  File "ptb_word_lm.py", line 332, in main
    tf.contrib.deprecated.scalar_summary("Training Loss", m.cost)`
`AttributeError: 'module' object has no attribute 'deprecated'`
### What I've run:

I just ran the following commands:
`wget http://www.fit.vutbr.cz/~imikolov/rnnlm/simple-examples.tgz`
`tar xvf simple-examples.tgz`
`python ptb_word_lm.py --data_path=simple-examples/data/`

I download the code from the [github repository](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/models/rnn). 
My tensorflow version is the very latest tensorflow-0.12.0rc0-cp27-none-linux_x86_64.
Why can't I run this example?
Thank you all for your kind help!!!

**Comment by dansmith11235** [comment]
I am trying to work through the same issue right now. Have you had any luck finding a solution?

**Comment by dansmith11235** [comment]
Probably not the best solution but once I commented out lines that had tf.contrib.deprecated in it the code ran. 

I am not sure what those lines of code do so use this solution at your own risk.

**Comment by poxvoculi** [comment]
Might have some version skew here (@danmane).  As a temporary fix, try removing just the "contrib.deprecated" parts leaving just tf.scalar_summary instead.

**Comment by FCInter** [comment]
I also tried to comment the "contrib.deprecated". But this leads to another error message saying"
`File "/d2/fpengaa/work/learntf/lstm-ptb/reader.py", line 100, in ptb_producer
    with tf.name_scope(name, "PTBProducer", [raw_data, batch_size, num_steps]):`
`TypeError: name_scope() takes exactly 1 argument (3 given)`
Moreover, I used to get another error saying 
`AttributeError: 'module' object has no attribute 'ptb_producer'`
I learned that to rectify this error, I have to change the import:
`from tensorflow.models.rnn.ptb import reader`
to
`import reader`
Then I succeeded in rectifying the last error. Though this error seems not related to my current question, it did make me to think whether it is because the code in the github repository has been updated by the developers but the tutorial has not been updated accordingly. Since the problem happens on the "import" is obviously because the version has been changed, not because the implementation has errors.
Anyway, thank you all for helping me, and should you have some progress in solving this problem, please kindly share your solution.
Thank you very much!!!

**Comment by FCInter** [comment]
It seems I have got the solution. It's just, abort the version r0.12 and install the version "master", which is r0.11. 
Then, replace the line 
`from tensorflow.models.rnn.ptb import reader`
with
`import reader`
And then comment all the lines containing the "deprecated".
Currently, only in this way can the program run correctly.
I think the reasons may be that the tutorial and the latest version of tensorflow, somehow do not match perfectly. I hope my problem and solution may help a little.
Thank you all for helping me.

**Comment by zhoujunpei** [comment]
I meet the same question after install version-r0.12.
I ran the cifar10_muti_gpu_train.py and get this message: 
AttributeError: 'module' object has no attribute 'deprecated'

**Comment by backsangyub** [comment]
tf.contrib.deprecated.scalar_summary -> tf.scalar_summary -> tf.summary.scalar
....

**Comment by ccase0** [comment]
tf.contrib.deprecated.scalar_summary -> tf.scalar_summary -> tf.summary.scalar
???

**Comment by linbojin** [comment]
Try to use tf.summary.scalar: https://github.com/tensorflow/tensorflow/blob/cb17d1b0e2b581b5da1d9597b7929ba764749d38/tensorflow/tools/compatibility/tf_upgrade.py

**Comment by wang820203420** [comment]
why? I'm
Then, replace the line
from tensorflow.models.rnn.ptb import reader
with
import reader

but 
Traceback (most recent call last):
  File "ptb_word_lm.py", line 367, in <module>
    tf.app.run()
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "ptb_word_lm.py", line 327, in main
    train_input = PTBInput(config=config, data=train_data, name="TrainInput")
  File "ptb_word_lm.py", line 93, in __init__
    data, batch_size, num_steps, name=name)
  File "/Users/wangqian/tensorflow/ptb/reader.py", line 100, in ptb_producer
    with tf.name_scope(name, "PTBProducer", [raw_data, batch_size, num_steps]):
TypeError: name_scope() takes exactly 1 argument (3 given)

help me,please!

**Comment by sherrysack** [comment]
maybe I am so also running into some version trouble, tensorflow is 1.0.0, tflearn is 0.2.2, but have trouble running such code
regression = tflearn.regression(linear, optimizer='sgd', loss='mean_square',
                                metric='R2', learning_rate=0.01)
m = tflearn.DNN(regression)
 
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 491, in apply_op
    preferred_dtype=default_dtype)
  File "C:\ProgramData\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\framework\ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\ProgramData\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 176, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "C:\ProgramData\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\framework\constant_op.py", line 169, in constant
    attrs={"value": tensor_value, "dtype": dtype_value}, name=name).outputs[0]
  File "C:\ProgramData\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\ProgramData\Anaconda2\envs\python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1220, in __init__
    raise ValueError("'%s' is not a valid node name" % node_def.name)
ValueError: '-_Loss/tags' is not a valid node name,
Hoping some help

**Comment by yanxp** [comment]
@sherrym  hello,how do you solve the problem? thanks

**Comment by prb12** [comment]
@FCInter The summary op used in this model is no longer present in TensorFlow  (hence the `deprecated` namespace)  I believe the change suggested by @linbojin will fix your problem until the model is updated.

@sherrysack Your problem is completely unrelated to the original issue.  If you believe there is a real bug in this code, please open a separate issue.
