### ISSUE TITLE
How to build Tensorflow 2.x with customerized protobuf version?

### ISSUE THREAD

**Issue by xunzhang** [tensorflow/tensorflow#60639]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

TensorFlow 2.x

### Custom Code

No

### OS Platform and Distribution

Linux CentOS7

### Python version

3.8, 3.10

### Bazel version

using Bazlisk

### GCC/Compiler version

have both gcc 7.3.1, clang 7.0.1

### GPU model and memory

CPU Only

### Current Behaviour?

I am writing MySQL UDF using TensorFlow C Library. But the MySQL8 has a conflict dependency of protobuf version with TensorFlow C Library. By default, MySQL8 needs protobuf 3.6.1 but TF uses higher version. I tried to modify the `workspace2.bzl` but the patch file is a problem to me. Since I do not have permission to change the building of MySQL8. How can I port a lower version of protobuf with TensorFlow 2.x? Thanks!

### Standalone code to reproduce the issue

```shell
The actual error I got is below

what():  This program requires version 3.9.0 of the Protocol Buffer runtime library, but the installed version is 3.6.1.  Please update your library.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
```
```


### Relevant log output

_No response_</details>

**Comment by SuryanarayanaY** [comment]
Hi @xunzhang ,

Tensorflow allows user to choose protobuf versions within some range.Please refer to protobuf versions required for TF2.13 versions below along with exclusions that may not work.

https://github.com/tensorflow/tensorflow/blob/525da8a93eca846e32e5c41eddc0496b25a2ef5b/tensorflow/tools/pip_package/setup.py#L96

You can install any of the protobuf versions mentioned above for your build.

Thanks!

**Comment by SuryanarayanaY** [comment]
@xunzhang ,

Unfortunately, It may not possible for the customization of protobuf version other than those mentioned in` setup.py` as mentioned in above comment.
