### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.slim' has no attribute 'nets'

### ISSUE THREAD

**Issue by rylanchiu** [tensorflow/tensorflow#6064]
### Environment info
Operating System:` Mac os x 10.10`

1. A link to the pip package you installed: `https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0rc0-py3-none-any.whl`
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`:  `0.12.0-rc0`

### reproducible example

    import tensorflow as tf
    import tensorflow.contrib.slim as slim
    from tensorflow.examples.tutorials.mnist import input_data
    vgg = tf.contrib.slim.nets.vgg

    mnist = input_data.read_data_sets('MNIST_data', one_hot=True)
    x = tf.placeholder("float", shape=[None, 784])
    y_ = tf.placeholder("float", shape=[None, 10])
    pred = vgg.vgg16(x)

    cross_entropy = -tf.reduce_sum(y_ * tf.log(pred))

### Error Message:

    Traceback (most recent call last):
    File "resnet.py", line 4, in <module>
    vgg = tf.contrib.slim.nets.vgg
    AttributeError: module 'tensorflow.contrib.slim' has no attribute 'nets'

**Comment by poxvoculi** [comment]
Where did you come up with this example, and why do you expect it to work?  

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/nets.py
and
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/nets/vgg.py

Maybe you don't have all of slim installed? Or maybe the name usage has to be slightly different?  (This is really outside of my area of familiarity.)

**Comment by rylanchiu** [comment]
@poxvoculi  Hi Paul, thanks for your reply. Here is the [example] (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/slim#training-models).

**Comment by foxik** [comment]
The problem is caused by the fact that https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/__init__.py does not export `nets`.

However, you can get around you problem by explicitly importing `nets`, adding the `> marked line <':
```python
import tensorflow as tf
import tensorflow.contrib.slim as slim
> import tensorflow.contrib.slim.nets <
from tensorflow.examples.tutorials.mnist import input_data
vgg = tf.contrib.slim.nets.vgg
```

**Comment by rylanchiu** [comment]
@foxik Thanks for your reply! It solves my problem perfectly!

**Comment by paolov** [comment]
@foxik I receive a syntax error running your code, what kind of syntax is that? 
`    > import tensorflow.contrib.slim.nets <
    ^
SyntaxError: invalid syntax
`

**Comment by foxik** [comment]
@paolov The correct line is of course
```python
import tensorflow.contrib.slim.nets
```
the `>` and `<` are just meant as visual notification, sorry if it unclear.

**Comment by alifejon** [comment]
@rylanchiu I have got error like this:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-647e80c0237f> in <module>()
     25 
     26   # Define the model:
---> 27   predictions = vgg.vgg16(images, is_training=True)
     28 
     29   # Specify the loss function:

AttributeError: module 'tensorflow.contrib.slim.python.slim.nets.vgg' has no attribute 'vgg16'
```
I am using tf.__version__ is 1.3.0

**Comment by perhapszzy** [comment]
I have the same problem, any idea to solve it?

**Comment by poxvoculi** [comment]
Looks like there's a name error in the README, and the function you want is actually vgg_16:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/nets/vgg.py#L139
