### ISSUE TITLE
tf.math.sign has different results with or without XLA

### ISSUE THREAD

**Issue by PengHaoYu** [tensorflow/tensorflow#60656]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.14.0-dev20230520

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04

### Mobile device

/

### Python version

3.7.5

### Bazel version

/

### GCC/Compiler version

/

### CUDA/cuDNN version

11.2

### GPU model and memory

GeForce RTX 2080Ti

### Current Behaviour?

`tf.math.sign` has different results with or without XLA.

The reproduction colab link is here: [colab](https://colab.research.google.com/drive/1JQXDs9fo6Ft2HzFPnZ-ChorhUA0Zn_cz#scrollTo=FYTuTfdC5IX_).

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

print(tf.version.VERSION)


@tf.function(jit_compile=False)
def run_without_xla(a):
    return tf.math.sign(a)


@tf.function(jit_compile=True)
def run_with_xla(a):
    return tf.math.sign(a)


x = tf.constant([-3.e+307 + 0.j, -6.e+307 + 0.j])
print(run_without_xla(x))
print(run_with_xla(x))
```

### Relevant log output

```shell
2.14.0-dev20230520
tf.Tensor([-0.+0.j -0.+0.j], shape=(2,), dtype=complex128)
tf.Tensor([-1.+0.j -1.+0.j], shape=(2,), dtype=complex128)
```
</details>

**Comment by tilakrayal** [comment]
@PengHaoYu,
The issue might be due to casting behaviour on CPU vs GPU with undefined/overflow values.

Could you please refer to the developer comment for a similar issue https://github.com/tensorflow/tensorflow/issues/58749#issuecomment-1467086661. Thank you!
