### ISSUE TITLE
Bug: _linear's optional scope argument is ignored

### ISSUE THREAD

**Issue by rdipietro** [tensorflow/tensorflow#6065]
Here is the relevant code from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn_cell_impl.py

```
def _linear(args, output_size, bias, bias_start=0.0, scope=None):
  # ...
  scope = vs.get_variable_scope()
  with vs.variable_scope(scope) as outer_scope:
    # ...
```

**Comment by rdipietro** [comment]
Update: A fix was proposed a few days ago in https://github.com/tensorflow/tensorflow/pull/6009

Leaving this open until that fix is accepted.

**Comment by michaelisard** [comment]
From #6009 "It is hidden for a reason; you should not be using it. Use tf.contrib.layers.linear instead. The scope argument will be removed soon."
