### ISSUE TITLE
GPU not found after 2.10

### ISSUE THREAD

**Issue by filmretter** [tensorflow/tensorflow#60650]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

v2.10.0-76-gfdfc646704c 2.10.1

### Custom Code

Yes

### OS Platform and Distribution

Windows 10

### Python version

3.7.3

### CUDA/cuDNN version

8.1

### GPU model and memory

RTX 3060

### Current Behaviour?

Hi there, I am new at Tensorflow and AI programming. So forgive me if this is a dumb question.

2.10 is the last GPU special version. I read that newer versions have GPU support included without a special gpu version, but no GPU is found under these new versions

Thanks :-)
Martin

### Standalone code to reproduce the issue

```shell
import os
import sys

# Get the CUDA_PATH environment variable
cuda_path = os.environ.get("CUDA_PATH")

# Check if CUDA_PATH is set
if cuda_path:
    # Add the bin folder inside CUDA_PATH to the system path
    sys.path.append(os.path.join(cuda_path, "bin"))
else:
    print("Achtung: Umgebungsvariable 'CUDA_PATH' nicht gefunden.")

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "1"

import tensorflow as tf
import ctypes

def check_python_version():
    print(f"Python-Version: {sys.version}")
    major, minor = sys.version_info[:2]
    if major == 3 and minor >= 6:
        print("Python-Version ist kompatibel.")
    else:
        print("Achtung: TensorFlow erfordert Python 3.6 oder höher.")

def check_tf_version():
    print(f"Installierte TensorFlow-Version: {tf.__version__}")
    if tf.__version__ >= "2.12.0":
        print("TensorFlow-Version ist kompatibel.")
    else:
        print("Achtung: Dieses Skript wurde für TensorFlow 2.12.0 entwickelt.")

def check_gpu_support():
    print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))
    if len(tf.config.list_physical_devices('GPU')) > 0:
        print("GPU-Unterstützung ist aktiviert.")
    else:
        print("Achtung: Keine GPU gefunden oder GPU-Unterstützung ist deaktiviert.")

def check_cuda_version():
    if not cuda_path:
        return

    cuda_version_file = os.path.join(cuda_path, "version.txt")
    if not os.path.exists(cuda_version_file):
        print("Achtung: CUDA-Versionstextdatei nicht gefunden.")
        return

    with open(cuda_version_file, "r") as f:
        cuda_version_data = f.read().strip()
    print(f"Installierte CUDA-Version: {cuda_version_data}")

    if "11.4" in cuda_version_data:
        print("CUDA-Version ist kompatibel.")
    else:
        print("Achtung: TensorFlow 2.12.0 erfordert CUDA 11.4.")

def check_cudnn_version():
    if not cuda_path:
        return

    cudnn_dll_name = "cudnn64_8.dll"

    cudnn_dll_path = os.path.join(cuda_path, "bin", cudnn_dll_name)
    if not os.path.exists(cudnn_dll_path):
        print("Achtung: cuDNN-DLL-Datei nicht gefunden.")
        return

    cudnn_dll = ctypes.WinDLL(cudnn_dll_path)
    cudnn_version = cudnn_dll.cudnnGetVersion()
    print(f"Installierte cuDNN-Version: {cudnn_version}")

    if cudnn_version >= 8200:
        print("cuDNN-Version ist kompatibel.")
    else:
        print("Achtung: TensorFlow 2.12.0 erfordert cuDNN 8.2 oder höher.")

def main():
    check_python_version()
    print()
    check_tf_version()
    print()
    check_gpu_support()
    print()
    check_cuda_version()
    print()
    check_cudnn_version()

if __name__ == "__main__":
    main()
```

### Relevant log output

_No response_</details>

**Comment by Impure-King** [comment]
The problem is that tensorflow drop Window's gpu support after 2.10 due to a vulnerbility found. Therefore the only way to use tensorflow with GPU is to dual boot a linux distro or use WSL Ubuntu alongside with Windows. The former is more preferred for speed and performance, while the latter is easier to work with if you are used to Windows.

**Comment by mihaimaruseac** [comment]
> The problem is that tensorflow drop Window's gpu support after 2.10 due to a vulnerbility found. Therefore the only way to use tensorflow with GPU is to dual boot a linux distro or use WSL Ubuntu alongside with Windows. The former is more preferred for speed and performance, while the latter is easier to work with if you are used to Windows.

It's not due to a vulnerability. See #59918 comments

**Comment by tilakrayal** [comment]
@filmretter,
Closing this issue as stale. Please reopen if this is still a valid request. Thank you!
