### ISSUE TITLE
Migrating T2T fork to TF2.7.4

### ISSUE THREAD

**Issue by branko-fathom** [tensorflow/tensorflow#60683]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.7.4

### Custom Code

Yes

### Current Behaviour?

My org is looking to migrate our Tensor2Tensor fork from TF1 to TF2.7.4 by the end of June in order to not lose TPU access in GCP. The current plan for our fork is to utilize the `tensorflow.compat.v1` APIs (along with updating `contrib` imports to use `tensorflow_addons` and `tf_slim`) and `tf.disable_v2_behavior()`. Is this all that's required to get t2t working with TF2?

### Standalone code to reproduce the issue

```shell
N/A
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@branko-fathom,
TensorFlow 2 is fundamentally different from TF1.x in several ways. You can still run unmodified TF1.x code ([except for contrib](https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md)) against TF2 binary installations like so.

Also please take a look at this official tf1.x to tf2.x migration document for reference.
https://www.tensorflow.org/guide/migrate
https://www.tensorflow.org/guide/migrate/migrate_tf2

Thank you!
