### ISSUE TITLE
Support for CUDA 12.0 and 12.1

### ISSUE THREAD

**Issue by fwyzard** [tensorflow/tensorflow#60691]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf 2.6.4

### Custom Code

Yes

### OS Platform and Distribution

Red Hat Enterprise Linux 8

### Python version

3.9.14

### Bazel version

3.7.2

### GCC/Compiler version

11.2.1

### CUDA/cuDNN version

12.0.1 / 8.8.0

### GPU model and memory

NVIDIA V100, T4, A100

### Current Behaviour?

According to the documentation, TensorFlow currently supports CUDA 11.8 .

Are there plans and maybe a timeline for adding support for CUDA 12.0 or 12.1 ?

Many thanks,
.Andrea

### Standalone code to reproduce the issue

```shell
n/a
```

### Relevant log output

_No response_</details>

**Comment by fwyzard** [comment]
> Going forward for the upcoming releases, tensorflow might move to CUDA 12.0 or higher version. We will announce that information in the mentioned official doc once the next release happens.

Hi @tilakrayal, thanks for the answer, even though it's not very helpful for planning ahead :-)

**Comment by tilakrayal** [comment]
@fwyzard,
The Tensorflow nightly moved to CUDA 12 a few days ago. Could you please take a look at this commit [3de4416 2](https://github.com/tensorflow/tensorflow/commit/3de44168950a5972ba4cfa7e3c6cbf4cffa67fe6).

You can try to use the latest tf-nightly for immediate use-case and it will be made available from TF 2.15.

Thank you!

**Comment by fwyzard** [comment]
Thank you @tilakrayal , we will start testing it.

**Comment by tilakrayal** [comment]
@fwyzard,
Thank you and please confirm the update on this issue. Thank you!
