### ISSUE TITLE
Samsung S21: Noisy AI Inference Results with App Animations in PlayService/GPU Mode

### ISSUE THREAD

**Issue by JeremyJian** [tensorflow/tensorflow#60704]
**System information**
- Android Device information : 
samsung/o1qzhx/o1q:12/SP1A.210812.016/G9910ZHU2CVG2:user/release-keys
- TensorFlow Lite in Play Services SDK version : 
   'com.google.android.gms:play-services-tflite-support:16.0.1'
   'com.google.android.gms:play-services-tflite-gpu:16.1.0'
- Google Play Services version
 23.16.13(190408-527363516)

I followed the tutorial from 

https://www.tensorflow.org/lite/android/play_services#java_6.

Everything seemed fine on almost all devices. However, our test team recently attempted to test our app on the Samsung S21 and discovered that the AI inference results are noisy when there are animations on the app's GUI. This issue only occurs in the PlayService/GPU scenario. If I switch to standalone mode, everything works well. We also found that setting "android:hardwareAccelerated" to false in the AndroidManifest.xml can produce stable results, but it's obviously not a reasonable solution. Has anyone else experienced a similar issue? I would appreciate any advice or suggestions.

**Comment by FilbertChen** [comment]
I have the same problem on Samsung S21. Prediction errors will occur randomly when hardwareAccelerated is enabled.

**Comment by JeremyJian** [comment]
Update some new information.

I have discovered that not only can animations in the app cause errors, but if there are operations in other apps simultaneously with the model's prediction, they can also impact the predicted results of the model.

**Comment by pkgoogle** [comment]
Hi @JeremyJian,

Can you please fill out the issue template?: https://github.com/tensorflow/tensorflow/blob/master/ISSUE_TEMPLATE.md

Additionally for this use case are you using the Task Library API? The Interpreter API? Are you using a real device or an emulator in Android Studio? Is the same behavior happening in both?

Any additional information will be great. Thanks!

**Comment by JeremyJian** [comment]
Hi, in my project, I use the Interpreter API provided by Google Play Services. We have found this issue only on the Samsung S21, which is a real device. We have also run the same code on other devices such as the Pixel 5, Pixel 6, and Samsung S10, and everything works fine. To further clarify the issue, we have written a simple code using a simple model (MNIST model) to observe the behavior. The video is shown below.

[https://drive.google.com/file/d/1CUb6fIeuX-Xg1KA4p0lKM5umjmjb5wJS/view](url)

In the sample app, we perform inference with the same input(handwritten 7) 100 times for each scenario and display the accuracy on the user interface. As you can see in the video, when we run the inference and the circular progress bar simultaneously, the accuracy drops to 94%. However, we are using the exact same input (a bitmap of a 7-digit number), so the accuracy should always be 100%.

**Comment by pkgoogle** [comment]
Hi @JeremyJian, can you try on a Samsung S21 emulator as well and let us know the results? I'm trying to determine if we can replicate it on emulator here as well (this will help us immensely as that would make it reproducible on our end) otherwise we would have to procure a real device. Additionally, it seems your drive link is going to the github issues page instead, I can copy and paste the info to get there but if you can edit it so that the community doesn't get confused, that'll be great.

**Comment by JeremyJian** [comment]
Sorry, I can't find the emulator of Samsung S21 (SM-G9910) from Android Studio or Firebase TestLab. On the other hand, our issue only occurs in scenarios where both the GPU and Google Play Services (com.google.android.gms:play-services-tflite-gpu:16.2.0) are used simultaneously. It seems that reproducing this issue on a simulator may not be suitable. As described in the initial question, using the CPU or the standalone version of TensorFlow Lite (org.tensorflow:tensorflow-lite-gpu:2.9.0) does not encounter this problem.

Thank you for your reminder. The video link has been corrected.

**Comment by pkgoogle** [comment]
Thanks for the info, @sirakiin, can you please take a look at this? Thanks.

**Comment by JeremyJian** [comment]
Hi, Is there any new information or update regarding this issue? 
Thanks

**Comment by 10112021-JeremyLee** [comment]
We have recently encountered similar issues with both the Samsung S22 Ultra and S23 Ultra devices. Including the previously mentioned S21 series, are equipped with Qualcomm processors. While we're uncertain whether the processor is directly linked to these problems, we are eager to receive any updates or new information regarding this issue. Please keep us informed if you have any new insights.

**Comment by pulkitagarawal** [comment]
The similar noisy output is observed on other devices as well when the inference is run on hardware accelerated.
The results of same transformer model with float32 precision is different on Android CPU and GPU. This issue becomes more significant when the noise explodes over deep architectures. 
In my case model run fine on Intel x86 CPU, Nvidia A100 GPU, Android Qualcomm based CPUs of S23, s24, Fold5 etc. But on Android GPU (qualcomm snapdragon 855 or 845) the results are different and unusable. Not sure what the reason it.

Using tflite gms apis 16.0.1

**Comment by gaikwadrahul8** [comment]
Hi, @JeremyJian 

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/170

Let us know if you have any questions. Thanks.
