### ISSUE TITLE
Hexagon Libraries version `v1.20.0.9` not available

### ISSUE THREAD

**Issue by caiotoledo-lunasystems** [tensorflow/tensorflow#60707]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

v2.11.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

Android

### Bazel version

6.2.0

### Current Behaviour?

I'm trying to use Hexagon delegates for Android and I couldn't find the proper `libhexagon_nn_skel*.so` libraries at https://www.tensorflow.org/lite/android/delegates/hexagon#step_2_add_hexagon_libraries_to_your_android_app_2

Could you share a link with the shared library built? As TensorFlow Lite `v2.11.1` requires `v1.20.0.9`.

I've tried to use `v1.20.0.1` but got the following error:
```
Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
```

### Standalone code to reproduce the issue

```shell
/* Hexagon Delegate */
  const char *lib_path = "/data/local/tmp/dsp";
  TfLiteHexagonInitWithPath(lib_path);
  auto options_hexagon = TfLiteHexagonDelegateOptionsDefault();
  _delegateHexagon.reset(TfLiteHexagonDelegateCreate(&options_hexagon));
  auto retTflite = _interpreter->ModifyGraphWithDelegate(_delegateHexagon.get());
  if (retTflite != kTfLiteOk)
  {
    LOGWARN("Failed to delegate to Hexagon [%d]", retTflite);
  }
```

### Relevant log output

_No response_</details>

**Comment by pjpratik** [comment]
Hi @caiotoledo-lunasystems 

The Hexagon delegates v1.20.0.9 is available in https://github.com/tensorflow/tensorflow/blob/d37fda11945d290f86b85a39f28bbddbbd0f6bee/third_party/hexagon/workspace.bzl#L12

Download it [here](https://storage.googleapis.com/mirror.tensorflow.org/storage.cloud.google.com/download.tensorflow.org/tflite/hexagon_nn_headers_v1.20.0.9.tgz).

Thanks.

**Comment by caiotoledo-lunasystems** [comment]
@pjpratik,

Thanks for your feedback.

The link provided [here](https://storage.googleapis.com/mirror.tensorflow.org/storage.cloud.google.com/download.tensorflow.org/tflite/hexagon_nn_headers_v1.20.0.9.tgz) doesn't have the libraries `libhexagon_nn_skel.so`, `libhexagon_nn_skel_v65.so`,  `libhexagon_nn_skel_v66.so`.

I was expecting a link like the one for [v1.20.0.1](https://storage.cloud.google.com/download.tensorflow.org/tflite/hexagon_nn_skel_v1.20.0.1.run).
I tried to use the link https://storage.cloud.google.com/download.tensorflow.org/tflite/hexagon_nn_skel_v1.20.0.9.run for `v1.20.0.9` but it didn't work.

**Comment by pkgoogle** [comment]
It seems the documentation may not be up to date and the .run file isn't there for v1.20.0.9

@sirakiin Can you take a look? Alternatively is there a script or instructions on how we may compile the .so files manually?

**Comment by aseok** [comment]
@caiotoledo-lunasystems is there any progress/workaround?

**Comment by caiotoledo-lunasystems** [comment]
> @caiotoledo-lunasystems is there any progress/workaround?

@aseok, no we have put this feature on pause on our side for now.
We couldn't find any workaround.
