### ISSUE TITLE
tf.contrib.learn.LinearRegressor builds bad model for a data with one feature

### ISSUE THREAD

**Issue by b0noI** [tensorflow/tensorflow#6070]
Reproduce steps:

[csv with data](http://%22https//vincentarelbundock.github.io/Rdatasets/csv/car/Davis.csv%22). Data includes weight and height values of some people. Overall learning process is very simple:

```
MAX_STEPS = 2000
# ...
features = [tf.contrib.layers.real_valued_column(feature_name) for feature_name in FEATURES_COL]
# ...
linear_regressor = tf.contrib.learn.LinearRegressor(feature_columns=features)
linear_regressor.fit(input_fn=prepare_input, max_steps=MAX_STEPS)
```

However, the model that is built by the regressor is, unexpectedly, bad. Result could be illustrated with the next picture: 
<img width="556" alt="umbhj" src="https://cloud.githubusercontent.com/assets/554101/20871476/1aaa1f42-ba4b-11e6-84cb-3bb5f3544f1a.png">
Visualization code(just in case):
```
plt.plot(height_and_weight_df_filtered[WEIGHT_COL], 
         linear_regressor.predict(input_fn=prepare_full_input), 
         color='blue',
         linewidth=3)
```
Why I think the model is bad? Here is the same data been given to the LinearRegression class from the scikit-learn:

```
lr_updated = linear_model.LinearRegression()
lr_updated.fit(weight_filtered_reshaped, height_filtered)
```

And the visualization: 

<img width="548" alt="gi1ui" src="https://cloud.githubusercontent.com/assets/554101/20871501/5949a3e4-ba4b-11e6-970c-d5afaf002b85.png">

Increasing amount of steps has no effect. I would assume I'm using regressor from the TensorFlow in a wrong way.

[iPython notebook with the code.](https://storage.googleapis.com/stackoverflow-b0noi/Intro%2Bwith%2BTensorFlow.ipynb)

Env details

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.11.0rc0

### What other attempted solutions have you tried?

The issue was opened originally as a question on the [stackoverflow](http://stackoverflow.com/questions/40734394/tf-contrib-learn-linearregressor-builds-unexpectedly-bad-model-for-a-data-with-o).

**Comment by michaelisard** [comment]
This type of question is better asked on [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it's a usage question rather than a bug report.

**Comment by b0noI** [comment]
closing the issue until I have confirmation that there is no mistake in the way of how I'm using the Regressor. If there is no mistakes in the usage logic, then there is an issue with TF.
