### ISSUE TITLE
[Feature request] To add the ability to use own data during the training a RNN network for translation by the translate.py script

### ISSUE THREAD

**Issue by b0noI** [tensorflow/tensorflow#6071]
Right now the script [translate.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/translate/translate.py) does not allow to use own data for training. At the moment it works only with the data, that the script downloads from the Internet (en/fr). Also there is not any documentation on the format of the input data that it expects in the input. In order to have the ability to train the model with own data 2 changes need to be made to the script:
* to document the format of the input data;
* enable the ability to pass an own input file path via the script arguments, the file path should be used for training instead of downloading the data from the internet.

**Comment by michaelisard** [comment]
The [source of the training data](http://www.statmt.org/wmt10/translation-task.html) has some information about the file format and some parsing tools.

For the ability to pass in your own data, we may not get to it immediately but I have marked it contributions welcome. @girving

**Comment by b0noI** [comment]
I'm working on the version that will allow to train a model with any pair of languages, and planning to start sending PR upcoming weekends.

**Comment by vrv** [comment]
FYI I believe these models are being moved into a new repository to clearly separate library code from examples.  @nealwu

**Comment by b0noI** [comment]
vrv@ in the light of new information I have 2 questions:
- could you point me to the correct repo with the examples?
- can I remove code from here, in order to avoid further confusion?

**Comment by vrv** [comment]
You'll have to ask @nealwu

**Comment by nealwu** [comment]
@b0noI: We're in the process of moving this file to https://github.com/tensorflow/models in a folder that will be called 'tutorials', which you should see soon. The file contents will remain largely the same though, so feel free to base off of the current file.

**Comment by nealwu** [comment]
FYI, as of a few days ago this code is now sitting in https://github.com/tensorflow/models/tree/master/tutorials. I'm going to close this issue since it no longer applies to this repo.
