### ISSUE TITLE
make: *** No rule to make target 'test_hello_world_test'.  Stop.

### ISSUE THREAD

**Issue by JavaldeUB** [tensorflow/tensorflow#60717]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.8

### Custom Code

No

### OS Platform and Distribution

Ubuntu wsl

### Current Behaviour?

tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
tensorflow/lite/micro/tools/make/downloads/kissfft already exists, skipping the download.
tensorflow/lite/micro/tools/make/downloads/pigweed already exists, skipping the download.
make: *** No rule to make target 'test_hello_world_test'.  Stop.

### Standalone code to reproduce the issue

```shell
sudo make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test
```

### Relevant log output

_No response_</details>

**Comment by JavaldeUB** [comment]
I'm runnig the make -f tensorflow/lite/micro/tools/make/Makefile test_hello_world_test from the tflite-micro folder in a Ubuntu installed in a WSL machine. I've got some errros about numpy and Pillow but everything solved. Now what I get is something like this:

tensorflow/lite/micro/tools/make/downloads/flatbuffers already exists, skipping the download.
tensorflow/lite/micro/tools/make/downloads/kissfft already exists, skipping the download.
tensorflow/lite/micro/tools/make/downloads/pigweed already exists, skipping the download.
make: *** No rule to make target 'test_hello_world_test'.  Stop.

I think it has something to do with the files (make does not find them) so I tried to clone the repository again but nothing...
A bit of help would be appreciated.
All the best,
Javi

**Comment by pjpratik** [comment]
Hi @JavaldeUB 

I have tried on Ubuntu 20.04 with master branch and I was successfully able to run the `hello world test`.

Please find the gist [here](https://colab.research.google.com/gist/pjpratik/10c164cd544c2013596b2eaf4428948d/60171.ipynb). 

Could you please try with latest version?

Thanks.

**Comment by JavaldeUB** [comment]
Hi @pjpratik,
Thanks for your time here.
I have the same advances. I have installed Ubuntu 20.04 in the WSL machine and it passed the the test. I do not know if it is because I installed many things to have gnome in the WSL Ubuntu 20.04 distro or because it goes well with the 20.04...

I have another issue which is related with Warden's TinyML book. I'm following the examples ther but the code in the text doesn't look like the one in the ./examples/hello_world folder. I'm trying to make the test fail and I realized that the input is already set to 1.f. I'm puzzled

I know these are silly question but I've just landed here and I'm trying to grasp the thing....
Thanks for your time.
J.

**Comment by pjpratik** [comment]
Hi @JavaldeUB 

The `hello_world_test.cc` is a fairly small amount of code that creates an interpreter, gets a handle to a model that's been compiled into the program, and then invokes the interpreter with the model and sample inputs.

Also, the example has been updated based on the changes made recently. It is suggested to use the latest version and follow  the same for other examples.

Please check this [hello world](https://www.tensorflow.org/lite/microcontrollers/get_started_low_level#the_hello_world_example) example for the reference.

Thanks.
