### ISSUE TITLE
TFLITE issue with android device redmi note 11 pro

### ISSUE THREAD

**Issue by haider-khan333** [tensorflow/tensorflow#60720]
I am currently working on a project where i need to use tflite model for detecting fingers from a camera. I have tried to use gpu delegate or nnapi, but i unfortunately none of these works. While using gpu delegate, i am getting an error as belows

**Internal error: Failed to apply delegate: Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found Falling back to OpenGL TfLiteGpuDelegate Init: No shader implementation for transpose TfLiteGpuDelegate Prepare: delegate is not initialized Node number 390 (TfLiteGpuDelegateV2) failed to prepare. Restored original execution plan after delegate application failure.**

Does anyone else has faced the same problem?

**Comment by pjpratik** [comment]
Hi @haider-khan333 

On android 12, please add the following to the Android manifest in order to detect GPU delegate.

```
<uses-library android:name="libOpenCL.so"
           android:required="false"/>

<uses-library android:name="libOpenCL-pixel.so"
           android:required="false"/>
```

Thanks.

**Comment by haider-khan333** [comment]
> Hi @haider-khan333
> 
> On android 12, please add the following to the Android manifest in order to detect GPU delegate.
> 
> ```
> <uses-library android:name="libOpenCL.so"
>            android:required="false"/>
> 
> <uses-library android:name="libOpenCL-pixel.so"
>            android:required="false"/>
> `



> Hi @haider-khan333
> 
> On android 12, please add the following to the Android manifest in order to detect GPU delegate.
> 
> ```
> <uses-library android:name="libOpenCL.so"
>            android:required="false"/>
> 
> <uses-library android:name="libOpenCL-pixel.so"
>            android:required="false"/>
> ```
> 
> Thanks.

Thanks a lot. It solved my issue.
