### ISSUE TITLE
All input tensors must have the same rank. [Op:MatrixSolve]

### ISSUE THREAD

**Issue by alejopaullier96** [tensorflow/tensorflow#60721]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf 2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Linux

### Python version

3.10.10

### Current Behaviour?

I have two tensors `M` and `E` of shapes `(batch_size, 1, 4, 4)` and `(batch_size, 4, 1)` respectively. The official documentation of [tf.linalg.solve](https://www.tensorflow.org/api_docs/python/tf/linalg/solve) states the two tensors should have shapes `(..., M,M)` and `(...,M,K)`.  After executing my code I get the following error:
```
InvalidArgumentError: {{function_node __wrapped__MatrixSolve_device_/job:localhost/replica:0/task:0/device:CPU:0}} All input tensors must have the same rank. [Op:MatrixSolve]
```

### Standalone code to reproduce the issue

```shell
S = tf.linalg.solve(M, E)
```
```


### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@alejopaullier96,
Could you please provide the simple standalone code to reproduce the issue which helps us to analyse the issue in an effective way. Thank you!

**Comment by ElysianStorm** [comment]
Hi, is this open to pick up, I would like to contribute to this. I am new to open source contribution, but I am a quick learner.

**Comment by alejopaullier96** [comment]
@tilakrayal I have solved the issue by squeezing one dimension from the first input tensor:
```
M = tf.squeeze(M, axis=1)
```
This way my first tensor `M` which had shape `(batch_size, 1, 4, 4)` after squeezing has shape `(batch_size, 4, 4)`.  My second tensor `E` had shape `(batch_size, 4, 1)`, so essentially they ended up with the same number of dimensions (3). 

Just for clarification, the current documentation does not specify that the two input tensors/matrices must have the same number of dimensions, but rather that it specifies how the two last dimensions must be.
