### ISSUE TITLE
tensorflow.map hangs randomly when using for num_parallel_calls a value > 1

### ISSUE THREAD

**Issue by GrannyTickler** [tensorflow/tensorflow#60747]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: wsl2 on windows
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**: 2.12.0
-   **Python version**: 3.8.10
-   **CUDA/cuDNN version**: 12.0
-   **GPU model and memory**: RTX A5000 24GB

### Describe the problem

I am using tensorflow in a docker container on wsl2 for training neural networks but unfortunately everything freezes during the image import if done with the tf.map function with the parameter "num_parallel_calls" set to a value >1. Below is a minimal example of the code which causes the console to freeze at a random step and the CPU-usage to drop to a minimal level while the RAM is still occupied. After everything is frozen, the docker container is unresponsive and has to be restarted by stopping the process. This might even take half a day -> a few hundred thousand iterations but it allways happens at some point.

### Source code / logs

`import tensorflow as tf

def parse_function(filename):
    return tf.io.read_file(filename)

filenames = []
for i in range (100000):
    filenames.append("/D/test.png")

dataset_train = tf.data.Dataset.from_tensor_slices((filenames))
dataset_train = dataset_train.map(parse_function, num_parallel_calls =  2)
dataset_train = dataset_train.batch(50)

for epoch in range(1000):
    for step, (x_batch_train) in enumerate(dataset_train):
        print("epoch:", epoch, "start train step:",step)`

This issue is similar to others like #32454 but i still can't find a fix. 
Bypassing the map-function by loading everything at once works -> definitly during mapping if parallel calls are allowed

**Comment by sushantst** [comment]
Verify that Docker is properly configured, including memory and resource allocation settings, to ensure optimal performance.Also you can try updating the python version and dataset_train = tf.data.Dataset.from_tensor_slices((filenames)) line has double round bracket instead of single.Hope this helps

**Comment by tilakrayal** [comment]
@GrannyTickler,
I tried to execute the mentioned code and it was failing due to a different error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/24d1fb3e0cc1eac262c9e5d060930a2b/untitled.ipynb) and provide the complete dependencies. Thank you!

**Comment by GrannyTickler** [comment]
I tested the code without the docker container and it seems to work -> the issue can be closed apologies.
