### ISSUE TITLE
Check fail can be triggered in `tf.raw_ops.Fill` under jit compile mode.

### ISSUE THREAD

**Issue by Lyutoon** [tensorflow/tensorflow#60757]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.14.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04

### Mobile device

Ubuntu 20.04

### Python version

3.8.10

### Current Behaviour?

Check fail can be triggered in `tf.raw_ops.Fill` under jit compile mode. While in normal mode, it won't be triggered but through an InvalidArgumentError.

### Standalone code to reproduce the issue

```shell
import os 
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
import numpy as np

dims=tf.random.uniform([4], dtype=tf.dtypes.int32, minval=-10, maxval=1000000)
value=tf.random.uniform([], dtype=tf.dtypes.int32, minval=-100000, maxval=1000000)

@tf.function(jit_compile=True)
def fuzz_jit():
    y = tf.raw_ops.Fill(dims=dims, value=value)
    return y

def fuzz_normal():
    y = tf.raw_ops.Fill(dims=dims, value=value)
    return y

y1 = fuzz_jit() # trigger the check fail under jit compile mode.
print('[+] JIT ok')
y2 = fuzz_normal() # if you run y2 first, it will through error rather than check fail.
print('[+] Normal ok')
```

### Relevant log output

```shell
% python test.py
2023-06-02 11:21:51.062617: F tensorflow/compiler/xla/shape_util.cc:288] Check failed: FillNewShape(element_type, dimensions, &shape) 
zsh: abort (core dumped)  python test.py
```
</details>

**Comment by SuryanarayanaY** [comment]
Hi @Lyutoon ,

Please report check fails and other vulnerabilities [here](https://bughunters.google.com/). For more details, please check https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md and follow the instrcutions.

I have replicated the reported behaviour with tf-nightly(2.14.0-dev20230601) in colab and attached screenshot below.Check fail observed with jit_compile=True and without jit compile an exception is raised.

<img width="1501" alt="Screenshot 2023-06-02 at 3 36 31 PM" src="https://github.com/tensorflow/tensorflow/assets/116063290/313a89d2-157d-424d-b068-3aa76cb81523">

**Comment by tilakrayal** [comment]
@Lyutoon,
I tried to execute  the provided code on TensorFlow version 2.17, and observed that the anticipated error was correctly produced. However, in previous versions, the code encountered a check failure that resulted in a crash.
Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/869d4b995fc827573a062686413fb163/untitled2170.ipynb). Thank you!
