### ISSUE TITLE
Problem after installing new version using pip

### ISSUE THREAD

**Issue by DaddyWesker** [tensorflow/tensorflow#60775]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.11 and 2.12

### Custom Code

No

### OS Platform and Distribution

Linux mint 20.1

### Mobile device

-

### Python version

3.9

### Bazel version

-

### GCC/Compiler version

-

### CUDA/cuDNN version

11.8.0 from anaconda / nvidia-cudnn-cu11==8.6.0.163 (from pip)

### GPU model and memory

rtx 3070 mobile 8 gb vram, 32 gb ram

### Current Behaviour?

After installing using this tutorial https://www.tensorflow.org/install/pip#linux i can't import tensorflow. Here is an error.

![image](https://github.com/tensorflow/tensorflow/assets/10774222/65d07dca-b143-4cd9-8649-c965cac744fb)

I've tried with 2.11, 2.12 TF installed using pip. 

If I'm trying to install tf-nightly, then I've got another error

![image](https://github.com/tensorflow/tensorflow/assets/10774222/45941dc6-da20-4b19-a75c-c77d221035e7)

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
```

### Relevant log output

```shell
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daddywesker/anaconda3/envs/stdfex/lib/python3.9/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/daddywesker/anaconda3/envs/stdfex/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/daddywesker/anaconda3/envs/stdfex/lib/python3.9/site-packages/tensorflow/python/pywrap_tensorflow.py", line 26, in <module>
    self_check.preload_check()
  File "/home/daddywesker/anaconda3/envs/stdfex/lib/python3.9/site-packages/tensorflow/python/platform/self_check.py", line 63, in preload_check
    from tensorflow.python.platform import _pywrap_cpu_feature_guard
ImportError: /home/daddywesker/anaconda3/envs/stdfex/lib/python3.9/site-packages/tensorflow/python/platform/../../libtensorflow_cc.so.2: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringB5cxx11ERKNS_15OpKernelContextEb
```
</details>

**Comment by mihaimaruseac** [comment]
Can you run post the output of `python -m pip list` and `python -c 'import tensorflow'` run from the same environment?

**Comment by DaddyWesker** [comment]
Pip list:
![Screenshot from 2023-06-05 08-33-19](https://github.com/tensorflow/tensorflow/assets/10774222/715c2dac-3678-4ee1-a669-a922b0e58126)

import tensorflow:
![Screenshot from 2023-06-05 08-33-31](https://github.com/tensorflow/tensorflow/assets/10774222/08c567dd-054e-4b5a-8f73-7acaf887bc5f)

**Comment by DaddyWesker** [comment]
```
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   1.4.0                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
ca-certificates           2023.5.7             hbcca054_0    conda-forge
cachetools                5.3.1                    pypi_0    pypi
certifi                   2023.5.7                 pypi_0    pypi
charset-normalizer        3.1.0                    pypi_0    pypi
cudatoolkit               11.8.0               h6a678d5_0  
flatbuffers               23.5.26                  pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
google-auth               2.19.1                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.54.2                   pypi_0    pypi
h5py                      3.8.0                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
importlib-metadata        6.6.0                    pypi_0    pypi
keras-nightly             2.14.0.dev2023060107          pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libclang                  16.0.0                   pypi_0    pypi
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
markdown                  3.4.3                    pypi_0    pypi
markupsafe                2.1.3                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
numpy                     1.24.3                   pypi_0    pypi
oauthlib                  3.2.2                    pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0  
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pip                       23.0.1           py39h06a4308_0  
protobuf                  4.23.2                   pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
python                    3.9.16               h7a1cb2a_2  
readline                  8.2                  h5eee18b_0  
requests                  2.31.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
setuptools                67.8.0           py39h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
tb-nightly                2.14.0a20230603          pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
tensorflow-io-gcs-filesystem 0.32.0                   pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
tf-estimator-nightly      2.14.0.dev2023060108          pypi_0    pypi
tf-nightly                2.14.0.dev20230603          pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.16                  pypi_0    pypi
werkzeug                  2.3.4                    pypi_0    pypi
wheel                     0.38.4           py39h06a4308_0  
wrapt                     1.15.0                   pypi_0    pypi
xz                        5.4.2                h5eee18b_0  
zipp                      3.15.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  

```
Conda list just in case

**Comment by mihaimaruseac** [comment]
So, this is using latest `tf-nightly`. I think there is an actual issue in these builds, but they are offered on a best effort basis, there is a rotation that looks at the build and tries to solve issues such as this before a release.

Can you run the same on an environment where you use 2.13.0?

**Comment by DaddyWesker** [comment]
@mihaimaruseac 
As i said, I've met this problem using 2.11 and 2.12. Anyway, here is the output of those two commands. I've ran them on tensorflow 2.12 though, not 2.13.0. Pip tells me that there are only 2.13.0rc0, 2.13.0rc1are available. Do you want me to use them?

![Screenshot from 2023-06-05 18-42-04](https://github.com/tensorflow/tensorflow/assets/10774222/e71e6f92-8e1c-4ddb-8e56-51c9413753b6)

![Screenshot from 2023-06-05 18-42-22](https://github.com/tensorflow/tensorflow/assets/10774222/7d6814f1-4e71-4220-9b8e-01e95c0f5ef6)

**Comment by mihaimaruseac** [comment]
Yes, please try `rc1`. Your initial screenshots were showing nightly, that's why I asked for a released version.

**Comment by DaddyWesker** [comment]
> Your initial screenshots were showing nightly
That is because firstly I've tested 2.12 and 2.11, then I've seen that issue template requires testing on tf-nightly and installed it instead of regular tf.
Anyway, here is the outputs with 2.13.0rc1

![Screenshot from 2023-06-05 19-02-57](https://github.com/tensorflow/tensorflow/assets/10774222/cfbddebd-7392-4853-a0d9-a5cdb4c03238)

![Screenshot from 2023-06-05 19-03-03](https://github.com/tensorflow/tensorflow/assets/10774222/f24bc655-dffa-4cc8-a0ca-c7a64e0e9431)

**Comment by mihaimaruseac** [comment]
The missing symbols is `tensorflow::OpKernel::TraceString[abi:cxx11](tensorflow::OpKernelcontext const&, bool) const`

This makes me think you are combining wheels with the old C++ ABI and with the new one. Can you try recreating an empty environment and installing there?

**Comment by DaddyWesker** [comment]
@mihaimaruseac 

That is already recreated environment. I've deleted it and created again. It just has the same name.

**Comment by mihaimaruseac** [comment]
Does the issue reproduce if you use `venv` instead of *conda?

**Comment by DaddyWesker** [comment]
Done. Same problem.

![Screenshot from 2023-06-07 08-33-02](https://github.com/tensorflow/tensorflow/assets/10774222/5c961772-1783-4441-8048-f210e35fb6ef)

![Screenshot from 2023-06-07 08-33-08](https://github.com/tensorflow/tensorflow/assets/10774222/f8ca7021-1efa-4604-b4c5-d684b717aa5a)

**Comment by DaddyWesker** [comment]
I've used python 3.9 on conda env, on venv i'm using python 3.8. I've tried what you asked (upgrade setup tools), here are results.

![Screenshot from 2023-06-08 08-07-56](https://github.com/tensorflow/tensorflow/assets/10774222/e3346932-9041-4c90-80ed-9372161375fd)

![Screenshot from 2023-06-08 08-08-02](https://github.com/tensorflow/tensorflow/assets/10774222/3ec4d0e4-4cab-44e6-a555-f781f0947352)

**Comment by DaddyWesker** [comment]
And preventing move, I've installed python 3.11 and created venv using it. Same.

![Screenshot from 2023-06-08 08-30-12](https://github.com/tensorflow/tensorflow/assets/10774222/81c3808e-7dda-4a4b-83a0-c9ed1f2e3f1a)

**Comment by mihaimaruseac** [comment]
In the last virtualenvironment, if you do `cd tf/lib/python3.11/site-packages/tensorflow`, what is the output of `nm libtensorflow_cc.so.2 | grep _ZNK10tensorflow8OpKernel`?

Mine is

```
...$ nm libtensorflow_cc.so.2 | grep _ZNK10tensorflow8OpKernel
                 U _ZNK10tensorflow8OpKernel10InputRangeESt17basic_string_viewIcSt11char_traitsIcEEPiS5_
                 U _ZNK10tensorflow8OpKernel11TraceStringB5cxx11ERKNS_15OpKernelContextEb
000000000476d340 W _ZNK10tensorflow8OpKernel12const_tensorEv
                 U _ZNK10tensorflow8OpKernel16ShapeTraceStringB5cxx11ERKNS_15OpKernelContextE
```

**Comment by DaddyWesker** [comment]
Same

```
                 U _ZNK10tensorflow8OpKernel10InputRangeESt17basic_string_viewIcSt11char_traitsIcEEPiS5_
                 U _ZNK10tensorflow8OpKernel11TraceStringB5cxx11ERKNS_15OpKernelContextEb
000000000476d340 W _ZNK10tensorflow8OpKernel12const_tensorEv
                 U _ZNK10tensorflow8OpKernel16ShapeTraceStringB5cxx11ERKNS_15OpKernelContextE
```

**Comment by mihaimaruseac** [comment]
I think I have an idea on what happens, but just to test, can you try `LD_DEBUG=libs python -c "import tensorflow as tf" 2>file` and then attach the file? It is a large file, estimated to be several hundreds lines, but should give an idea on what libraries are attempted to be loaded.

**Comment by DaddyWesker** [comment]
Done
[file.txt](https://github.com/tensorflow/tensorflow/files/11708280/file.txt)

**Comment by jmfrank63** [comment]
Hi, I am experiencing the same issue: I am running inside pyenv virtualenv with venv name tensorflow.
```
python
Python 3.11.4 (main, Jul 22 2023, 12:30:49) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/johannes/.pyenv/versions/tensorflow/lib/python3.11/site-packages/tensorflow/__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/johannes/.pyenv/versions/tensorflow/lib/python3.11/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/johannes/.pyenv/versions/tensorflow/lib/python3.11/site-packages/tensorflow/python/pywrap_tensorflow.py", line 26, in <module>
    self_check.preload_check()
  File "/home/johannes/.pyenv/versions/tensorflow/lib/python3.11/site-packages/tensorflow/python/platform/self_check.py", line 63, in preload_check
    from tensorflow.python.platform import _pywrap_cpu_feature_guard
ImportError: /home/johannes/.pyenv/versions/tensorflow/lib/python3.11/site-packages/tensorflow/python/platform/../../libtensorflow_cc.so.2: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringB5cxx11ERKNS_15OpKernelContextEb
```

Here is my environment:

```
python -m pip list
Package                      Version
---------------------------- ---------
absl-py                      1.4.0
astunparse                   1.6.3
cachetools                   5.3.1
certifi                      2023.7.22
charset-normalizer           3.2.0
flatbuffers                  23.5.26
gast                         0.4.0
google-auth                  2.22.0
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
grpcio                       1.56.2
h5py                         3.9.0
idna                         3.4
keras                        2.13.1
libclang                     16.0.6
Markdown                     3.4.3
MarkupSafe                   2.1.3
numpy                        1.24.3
oauthlib                     3.2.2
opt-einsum                   3.3.0
packaging                    23.1
pip                          23.2.1
protobuf                     4.23.4
pyasn1                       0.5.0
pyasn1-modules               0.3.0
requests                     2.31.0
requests-oauthlib            1.3.1
rsa                          4.9
setuptools                   65.5.0
six                          1.16.0
tensorboard                  2.13.0
tensorboard-data-server      0.7.1
tensorflow                   2.13.0
tensorflow-estimator         2.13.0
tensorflow-io-gcs-filesystem 0.32.0
termcolor                    2.3.0
typing_extensions            4.5.0
urllib3                      1.26.16
Werkzeug                     2.3.6
wheel                        0.41.0
wrapt                        1.15.0
```
Machine:
```
sudo uname -a
Linux johannes-guest-room 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
Output of LD_DEBUG=libs python -c "import tensorflow as tf" 2>file.txt
[file.txt](https://github.com/tensorflow/tensorflow/files/12136444/file.txt)

Hip

**Comment by jmfrank63** [comment]
Hi, I am experiencing the same issue: I am running inside pyenv virtualenv with venv name tensorflow.
```
python
Python 3.11.4 (main, Jul 22 2023, 12:30:49) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/johannes/.pyenv/versions/tensorflow/lib/python3.11/site-packages/tensorflow/__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/johannes/.pyenv/versions/tensorflow/lib/python3.11/site-packages/tensorflow/python/__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "/home/johannes/.pyenv/versions/tensorflow/lib/python3.11/site-packages/tensorflow/python/pywrap_tensorflow.py", line 26, in <module>
    self_check.preload_check()
  File "/home/johannes/.pyenv/versions/tensorflow/lib/python3.11/site-packages/tensorflow/python/platform/self_check.py", line 63, in preload_check
    from tensorflow.python.platform import _pywrap_cpu_feature_guard
ImportError: /home/johannes/.pyenv/versions/tensorflow/lib/python3.11/site-packages/tensorflow/python/platform/../../libtensorflow_cc.so.2: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringB5cxx11ERKNS_15OpKernelContextEb
```

Here is my environment:

```
python -m pip list
Package                      Version
---------------------------- ---------
absl-py                      1.4.0
astunparse                   1.6.3
cachetools                   5.3.1
certifi                      2023.7.22
charset-normalizer           3.2.0
flatbuffers                  23.5.26
gast                         0.4.0
google-auth                  2.22.0
google-auth-oauthlib         1.0.0
google-pasta                 0.2.0
grpcio                       1.56.2
h5py                         3.9.0
idna                         3.4
keras                        2.13.1
libclang                     16.0.6
Markdown                     3.4.3
MarkupSafe                   2.1.3
numpy                        1.24.3
oauthlib                     3.2.2
opt-einsum                   3.3.0
packaging                    23.1
pip                          23.2.1
protobuf                     4.23.4
pyasn1                       0.5.0
pyasn1-modules               0.3.0
requests                     2.31.0
requests-oauthlib            1.3.1
rsa                          4.9
setuptools                   65.5.0
six                          1.16.0
tensorboard                  2.13.0
tensorboard-data-server      0.7.1
tensorflow                   2.13.0
tensorflow-estimator         2.13.0
tensorflow-io-gcs-filesystem 0.32.0
termcolor                    2.3.0
typing_extensions            4.5.0
urllib3                      1.26.16
Werkzeug                     2.3.6
wheel                        0.41.0
wrapt                        1.15.0
```
Machine:
```
sudo uname -a
Linux johannes-guest-room 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```
Output of LD_DEBUG=libs python -c "import tensorflow as tf" 2>file.txt
[file.txt](https://github.com/tensorflow/tensorflow/files/12136444/file.txt)

Hip

Additionally I tested a few other things but with no success:

I noticed I had the ubuntu cuda toolkit installed which was 11 but the driver said 12. So I installed the latest 12.2 toolkit, but to no avail. I also Upgraded to a recent mainline kernel version 6.3.13, this also did not help.
I am running out of ideas.

**Comment by jmfrank63** [comment]
Ha, found it. Another installation had `tensorflow_framework.so` put in the library path. To find this take the path after `Import Error:` and put `ldd` in front of it. It will show you the offending library. Remove it in any way you deem appropriate.
In my case it was wasmedge which was the culprit. Hih.

**Comment by DaddyWesker** [comment]
@jmfrank63 Thanks, I will try.

**Comment by DaddyWesker** [comment]
@jmfrank63 
Okay, so which one of those libs i need to delete exactly? 
![image](https://github.com/tensorflow/tensorflow/assets/10774222/426f8dc5-cfe1-415c-ab88-6876396b3876)

**Comment by jmfrank63** [comment]
Hi DaddyWesker,

 For me it was libtensorflow_framework. Check if
/lib/x86_64-linux-gnu/libtensorflow_framework.so.2 exists. Instead of
deleting, renaming is better, as you can undo it.

hih Johannes

Dipl.-Ing. (FH) Johannes-Maria Frank
Master CS UCL Birkbeck
30 Craster Square
Newcastle upon Tyne
NE3 3PL
United Kingdom
phone: +447400987848
e-mail: ***@***.***

**Comment by DaddyWesker** [comment]
Well, for some reason renaming 
/lib/libtensorflow_framework.so.2
does made a trick. At least tf is importing now and examples like 
```
python3 -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
```
works well. I need to check it on some sort of NN. If everything is fine, then I'll close the issue. But still, why this so file is generating then when installing TF at the first place?..

**Comment by mihaimaruseac** [comment]
Thanks for debugging the issue! It seems this is a new side effect that arises when you mix global TF installations with installs in a virtual environment. We recommend all TF installs should be done in a venv to prevent these contagions.

TF has a large C++ component that needs to be shipped with the wheel in order for users to use it. We could have localized the shared lib (`.so` file) to within the wheel (like smaller `.so`s are), but `libtensorflow_framework` is needed also if you want to do TF from other languages. So, for example, if you want to use TF from, say, Rust, you'd install the wheel, then tell your build process to link against this `.so` (and a few others).

There is no standard channel for distributing C++ artifacts, so it was decided to distribute them via the wheel and a GCS bucket. Recently, to reduce the number of builds, the GCS bucket was discontinued, so now users can get the shared objects only via the wheel.

Overall, this issue points to a new debugging item for similar issues: we should ask users to confirm whether they have global TF installations or everything is in a venv.
