### ISSUE TITLE
ConverterError: <unknown>:0: error

### ISSUE THREAD

**Issue by dsbyprateekg** [tensorflow/tensorflow#60778]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Kaggle
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source):

### 2. Code

![image](https://github.com/tensorflow/tensorflow/assets/30830541/8def72c1-d3ce-49eb-b446-e88aeeb17e36)

### 3. (optional) Any other info / logs
[converter_issue_tf.txt](https://github.com/tensorflow/tensorflow/files/11648334/converter_issue_tf.txt)

**Comment by pjpratik** [comment]
Hi @dsbyprateekg 

From the error log, it looks like the TF Model has select ops which are not available in TFLite builtins. 

To be able to convert the model into TFLite, please add the below flags before conversion.

```
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
```
Thanks.

**Comment by dsbyprateekg** [comment]
@pjpratik thanks, with the above I am able to proceed.
But when I checked the input shape of the converted tflite model, it's array([1,1,1,3)] which I don't understand.
Can you please share me Python inference code for TFLite? My original model is based on ssd_mobilenet_v2_fpnlite_640x640_coco17_tpu-8.config.

**Comment by pjpratik** [comment]
Hi @dsbyprateekg 

 If your model has dynamic input shapes and you didn't specify a dimension size when building and converting your model, the converter will use 1 as the default dimension size.

 However, at inference time you can use Interpreter's [ResizeInputTensor](https://www.tensorflow.org/lite/api_docs/python/tf/lite/Interpreter#resize_tensor_input) API to change the input shape of the model

You can check this TF Hub example for the inference.

https://hub.tensorflow.google.cn/google/lite-model/object_detection/mobile_object_localizer_v1/1/default/1

Thanks.
