### ISSUE TITLE
RESHAPE: OP is supported, but tensor type/shape isn't compatible

### ISSUE THREAD

**Issue by Ramees025** [tensorflow/tensorflow#60793]
**System information**
- OS Platform and Distribution: Android, Galaxy S23.
- TensorFlow installed from (source or binary):2.12
- TensorFlow version (or github SHA if from source):2.12

Input tensor shape (1,16,32,256,12)
Output tensor shape (1,16,32,3072)

**Any other info / logs**:

RESHAPE: OP is supported, but tensor type/shape isn't compatible

**Comment by tilakrayal** [comment]
@Ramees025,
Could you please provide complete code and more information about the issue which was mentioned. It helps to analyse the issue in an effective way. Thank you!

**Comment by Ramees025** [comment]
![image](https://github.com/tensorflow/tensorflow/assets/15998417/9b125b2a-acf3-4f29-81bf-3be83af466be)

Attached is the single layer model causing the issue when running in GPU.

**Comment by Ramees025** [comment]
Model run fine in CPU. But while running with GPU, it showing the error "RESHAPE: OP is supported, but tensor type/shape isn't compatible" and fallback to CPU.
Basically the reshape will convert 5D tensor to 4D tensor.

**Comment by tilakrayal** [comment]
@Ramees025,
Unfortunately with the above details provided, we were not able to provide the correct information. Could you please provide the complete code or the colab gist which helps us to debug the issue in an effective way. Thank you!

**Comment by Ramees025** [comment]
code:

\tensorflow\lite\delegates\gpu\common\model_builder.cc

TfLiteIntArray* GetOpsToReplace(
    TfLiteContext* context, bool allow_quant_ops, int max_delegated_partitions,
    const absl::flat_hash_set<TfLiteBuiltinOperator>* excluded_ops) {
  delegates::IsNodeSupportedFn node_supported_fn =
      [=](TfLiteContext* context, TfLiteNode* node,
          TfLiteRegistration* registration,
          std::string* unsupported_details) -> bool {
    const auto status =
        IsSupported(context, node, registration, allow_quant_ops, excluded_ops);
    if (!status.ok()) {
      if (unsupported_details) {
        *unsupported_details = std::string(status.message());
      }
      return false;
    }

    std::vector<TfLiteType> allowed_in_types = {kTfLiteFloat32, kTfLiteFloat16};
    std::vector<TfLiteType> allowed_out_types = {kTfLiteFloat32,
                                                 kTfLiteFloat16};
  -----
  -----
    if (!IsAllAllowedTensors(context, node->inputs, allowed_in_types) ||
        !IsAllAllowedTensors(context, node->outputs, allowed_out_types)) {
      if (unsupported_details) {
        *unsupported_details =
            **"OP is supported, but tensor type/shape isn't compatible.";**
      }
      return false;
    }
    return true;
  };

----
----
}

**Comment by pjpratik** [comment]
Hi @Ramees025 

The Reshape op might not be supporting the 5D tensors on GPU delegate which is why the error is thrown. 

Thanks.

**Comment by Ramees025** [comment]
Hi, is there any plan/roadmap to support 5D RESHAPE ops in tflite gpu delegate?

**Comment by pjpratik** [comment]
Hi @Ramees025 

The the support for 5D might be on roadmap of Reshape.

 You can also use [Model Analyzer](https://www.tensorflow.org/lite/guide/model_analyzer) to check the [GPU delegate](https://www.tensorflow.org/lite/performance/gpu) compatibility of the given model by providing `gpu_compatibility=True` option.

Thanks.
