### ISSUE TITLE
About using C to call tflite

### ISSUE THREAD

**Issue by panhu** [tensorflow/tensorflow#60792]
**System information**
- RIsc-v

**Standalone code to reproduce the issue**
Hi:
    If i want to compile tflite into a library and then use C to call it. How can I effectively optimize and crop it to make the compiled tflite library file smaller. Because for our model, tflite micro is not supported by many operators

**Comment by panhu** [comment]
Hi:
What I would like to add is how to significantly reduce tflite shared libraries when using cmake

**Comment by pjpratik** [comment]
Hi @panhu 

TensorFlow Lite enables you to reduce model binary sizes by using selective builds. Selective builds skip unused operations in your model set and produce a compact library with just the runtime and the op kernels required for the model to run on your mobile device.

Please refer to this [document](https://www.tensorflow.org/lite/guide/reduce_binary_size) on different ways of reducing TFLite binary size.

Thanks.

**Comment by panhu** [comment]
Hi@pjpratik

Thank you for your reply. What I would like to know is how to reduce tflite time when using cmake. The document you provided mentioned using bazel.

Thanks.

**Comment by pjpratik** [comment]
Hi @panhu 

The current instructions are provided using `bazel` which is recommended.  You can try to build [C API](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/README.md#using-the-c-api) using bazel as well and try reducing the binary size using above instructions.

Also, you can build custom c library using bazel by changing the build file.

Please check this thread [#48068](https://github.com/tensorflow/tensorflow/issues/48068) for reference.

Thanks.
