### ISSUE TITLE
2.13 support for TensorflowLiteSwift and tensorflow-lite android (Maven)

### ISSUE THREAD

**Issue by ramonhollands** [tensorflow/tensorflow#60816]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.13.0

### Custom Code

Yes

### OS Platform and Distribution

Ios/Android

### Mobile device

Ios/Android

### Current Behaviour?

I'm interested in the planned release date for TensorflowLite 2.13.0 IOS/Android

### Standalone code to reproduce the issue

```shell
I'm interested in the planned release date for TensorflowLite 2.13.0 IOS/Android
```

### Relevant log output

_No response_</details>

**Comment by pkgoogle** [comment]
Hi @ramonhollands,

The release will be notified here: https://cocoapods.org/pods/TensorFlowLiteSwift. Unfortunately, we don't have a publicly available planned release date currently. Please close if this answers your question.
