### ISSUE TITLE
GPU Delegate dynamic tensor input shape (Feature Request)

### ISSUE THREAD

**Issue by OleksandrGrument** [tensorflow/tensorflow#60814]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.12.0

### Custom Code

Yes

### OS Platform and Distribution

Android

### Mobile device

Android

### Current Behaviour?

Hello, I'm writing you to ask, are there plans to implement dynamic input shape in gpu delegate in near future ? 

Right now dynamic input shape working fine on cpu, but on gpu delegate I'm getting the issue 
`java.lang.IllegalArgumentException: Internal error: Error applying delegate: `

This is very important feature, if this feature already exist and it is possible somehow to rung with dynamic shape will be good to have some information in documentation. 

### Standalone code to reproduce the issue

```shell
@Throws(IOException::class)
    private fun initInterpreter(context: Context): Interpreter {

        val tfliteOptions = Interpreter
            .Options()
        
        if (delegate != null) {
            tfliteOptions.addDelegate(delegate)
            tfliteOptions.numThreads = 1
        } else {
            tfliteOptions.numThreads = 4
        }

        val interpreter = Interpreter(loadModelFile(context), tfliteOptions)
        
        interpreter.resizeInput(0, intArrayOf(1, modelHeight, modelWidth, 3), true)
        interpreter.allocateTensors()
        
        return interpreter
    }
```

### Relevant log output

```shell
java.lang.IllegalArgumentException: Internal error: Error applying delegate: 
org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:110)
org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:73)
org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:36)
org.tensorflow.lite.Interpreter.<init>(Interpreter.java:214)
```
</details>

**Comment by pkgoogle** [comment]
Hi @OleksandrGrument, in order to keep TFLite light, we have to compromise on some design choices such as dynamic input shapes. Currently we do not plan to implement this feature in the near future. Apologies we can't help you here soon.
