### ISSUE TITLE
wrong output shape with tf.experimental.numpy.vander when parameter N=0 

### ISSUE THREAD

**Issue by paulaehab** [tensorflow/tensorflow#60827]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.12.0

### Custom Code

No

### OS Platform and Distribution

Windows 11

### Python version

3.11

### Current Behaviour?

A bug happened!  when I used tf.experimental.numpy.vander() I get wrong values when parameter N =0  it produce empty array but with different shape that need to be 

### Standalone code to reproduce the issue

```shell
When I run
tf.experimental.numpy.vander(
    [-1.,-1.], N=0, increasing=False
)
I get the output as the following:
-> <tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[-1.,  1.],
       [-1.,  1.]])>

But when I run 
np.vander(np.array([-1.,-1.]),N=0)
I got the following: 
-> array([], shape=(2, 0), dtype=float64)
```

### Relevant log output

```shell
tensorflow output 
<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[-1.,  1.],
       [-1.,  1.]])>
numpy output 
array([], shape=(2, 0), dtype=float64)
```
</details>

**Comment by sushreebarsa** [comment]
@SuryanarayanaY  I was able to replicate the issue on colab using TF v[2.12](https://colab.research.google.com/gist/sushreebarsa/0ee09d4d66791b05b175c0ac757a7c92/60827.ipynb) and [tf-nightly](https://colab.research.google.com/gist/sushreebarsa/3aa3c1104e70c2489301a0abe973740e/60827.ipynb#scrollTo=zxgP6CMdinZH).  Please find the attached gists. 
Thank you!
