### ISSUE TITLE
What phone support tensorflow lite GPU delegate?

### ISSUE THREAD

**Issue by ldfandian** [tensorflow/tensorflow#60825]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.12.0

### Custom Code

No

### OS Platform and Distribution

Android 13

### Mobile device

Android 13

### Python version

3.8.3

### Current Behaviour?

I tested multiple mobile phones (including Xiaomi 12s Ultra, OnePlus 8, Honor Nova 10, Oppo Reno 9) using the example Android apk at https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android . On all of the devices, the app tells "GPU is not supported", but NNAPI and CPU is OK.

Anything I can do to enable the GPU delegate on these Qualcomm Snapdragon devices?

### Standalone code to reproduce the issue

```shell
the example Android apk at https://github.com/tensorflow/examples/tree/master/lite/examples/image_classification/android
```

### Relevant log output

_No response_</details>

**Comment by pjpratik** [comment]
Hi @ldfandian 

Can you please add the following to the Android manifest in order to detect GPU delegate.

```
<uses-library android:name="libOpenCL.so"
           android:required="false"/>

<uses-library android:name="libOpenCL-pixel.so"
           android:required="false"/>
```

Thanks.

**Comment by ldfandian** [comment]
> Hi @ldfandian
> 
> Can you please add the following to the Android manifest in order to detect GPU delegate.
> 
> ```
> <uses-library android:name="libOpenCL.so"
>            android:required="false"/>
> 
> <uses-library android:name="libOpenCL-pixel.so"
>            android:required="false"/>
> ```
> 
> Thanks.

Thanks for the quick response.

I tried to add the following code in AndroidManifest.xml, but it does not work.

`    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:taskAffinity=""
        tools:ignore="AllowBackup">

        <uses-native-library
            android:name="libOpenCL.so"
            android:required="false" />
        <uses-native-library
            android:name="libOpenCL-pixel.so"
            android:required="false" />
        <uses-library
            android:name="libOpenCL.so"
            android:required="false" />
        <uses-library
            android:name="libOpenCL-pixel.so"
            android:required="false" />
`

Btw, on the Xiaomi 12s Ultra, I checked that the file "/system/vendor/lib64/libOpenCL.so" does exist.
However, it looks like it does not show in the "/system/etc/public.libraries.txt".
Maybe it is the cause? Meaning that the mobile vendor blocks the GPU delegate?

`
# See https://android.googlesource.com/platform/ndk/+/master/docs/PlatformApis.md
libandroid.so
libaaudio.so
libamidi.so
libbinder_ndk.so
libc.so
libcamera2ndk.so
libdl.so
libEGL.so
libGLESv1_CM.so
libGLESv2.so
libGLESv3.so
libicu.so
libicui18n.so
libicuuc.so
libjnigraphics.so
liblog.so
libmediandk.so
libm.so
libnativehelper.so
libnativewindow.so
liblistenjni.qti.so
liblistensoundmodel2.qti.so
libneuralnetworks.so nopreload
libOpenMAXAL.so
libOpenSLES.so
libRS.so
libstdc++.so
libsync.so
libvulkan.so
libwebviewchromium_plat_support.so
libz.so
`

**Comment by ldfandian** [comment]
An update, after adding those uses-library/uses-native-library settings in AndroidManifest.xml, OnePlus 8T works but the other three devices still don't work...

I compared the their content of /system/etc/public.libraries.tx, but find nothing different among these devices.

What's the magic here?

**Comment by pkgoogle** [comment]
Hi @ldfandian,

Have you tried using our acceleration service to see which configuration might be optimal for each of your phones? https://www.tensorflow.org/lite/android/acceleration_service

Have you checked the documentation here: https://www.tensorflow.org/lite/android/delegates/gpu_native ?

Also for more information, are you using an emulator or the actual phones?

**Comment by ldfandian** [comment]
> Hi @ldfandian,
> 
> Have you tried using our acceleration service to see which configuration might be optimal for each of your phones? https://www.tensorflow.org/lite/android/acceleration_service
> 
> Have you checked the documentation here: https://www.tensorflow.org/lite/android/delegates/gpu_native ?
> 
> Also for more information, are you using an emulator or the actual phones?

Thanks for the advice.

Good to know it, but my phone does not have a Google play service installed~

**Comment by pkgoogle** [comment]
No worries, @ldfandian did the documentation help at all? Additionally please let us know if you are using emulators or actual phones or some combination of them. Thanks.

**Comment by ldfandian** [comment]
> No worries, @ldfandian did the documentation help at all? Additionally please let us know if you are using emulators or actual phones or some combination of them. Thanks.

All of these (Xiaomi 12s Ultra, OnePlus 8, Honor Nova 10, Oppo Reno 9) are real phones sold in China.

**Comment by pkgoogle** [comment]
Hi @sirakiin, can you please take a look?

**Comment by sirakiin** [comment]
Triage to @grantjensen . Could you help on this? Thanks!

**Comment by grantjensen** [comment]
Hi @ldfandian, looking at the GPU's used in these devices (Adreno 730, Adreno 642L) we have full support. I was able to confirm this via the following commands:

`bazel build -c opt --config=android_arm64 --copt=-DCL_DELEGATE_NO_GL third_party/tensorflow/lite/tools/benchmark:benchmark_model `

`adb push blaze-bin/third_party/tensorflow/lite/tools/benchmark/benchmark_model /data/local/tmp`

`adb push test.tflite /data/local/tmp`

`adb shell /data/local/tmp/benchmark_model --use_gpu=true --graph=/data/local/tmp/test.tflite`

This way we can confirm whether your issue is confined to TFL code or something broader. Please run the above code & let me know how it goes, thanks.

**Comment by ManishSahu53** [comment]
Actually, I have similar issue too. I cannot do GPU prediction on Phone. 

Tensorflow : 2.9
Androind : 13
Phone - Samsung A73 5G

I am getting this flag as False
compatList.isDelegateSupportedOnThisDevice: false

**Comment by alguojian** [comment]
I had the same issue with my OnePlus Ace3，Pls have you all solved it

**Comment by alguojian** [comment]
I have the same problem with my OnePlus Ace3, please can you all fix it

**Comment by pkgoogle** [comment]
Hi All, please create a new issue in https://github.com/google-ai-edge/litert, for better issue tracking and attention.
