### ISSUE TITLE
0.12 Saver.restore broken? Unsuccessful TensorSliceReader constructor: Failed to find any matching files 

### ISSUE THREAD

**Issue by hejunqing** [tensorflow/tensorflow#6082]
Here is the traceback:
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
Traceback (most recent call last):
  File "validate.py", line 163, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "validate.py", line 155, in main
    model.saver.restore(session,i[:-5])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1388, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
	 [[Node: save/RestoreV2_12 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_12/tensor_names, save/RestoreV2_12/shape_and_slices)]]
	 [[Node: save/RestoreV2_7/_11 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_4_save/RestoreV2_7", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'save/RestoreV2_12', defined at:
  File "validate.py", line 163, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "validate.py", line 148, in main
    model = cnnW2v(opts, session)
  File "/nobackup/s1/nlip/hejunqing/tf-lstm-char-cnn-gpu/cnn_w2v.py", line 152, in __init__
    self.build_graph()
  File "/nobackup/s1/nlip/hejunqing/tf-lstm-char-cnn-gpu/cnn_w2v.py", line 206, in build_graph
    self.saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1000, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1030, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 624, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 361, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 200, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 441, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model_epoch0_128_0.100_[200].ckpt-577569
	 [[Node: save/RestoreV2_12 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_12/tensor_names, save/RestoreV2_12/shape_and_slices)]]
	 [[Node: save/RestoreV2_7/_11 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_4_save/RestoreV2_7", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]

tf version:
0.12.0-rc0 
It is done on Debian Jessie with CUDA-8.0 and cudnn-5.1,using python 2.7

The model is in the directory,
Here are the models in the directory:
model_epoch0_128_0.100_[200].ckpt-577569.meta
model_epoch1_128_0.100_[200].ckpt-1155138.meta
model_epoch2_128_0.100_[200].ckpt-1732707.meta
model_epoch3_128_0.100_[200].ckpt-2310276.meta
model_epoch4_128_0.100_[200].ckpt-2887845.meta
model_epoch0_128_0.100_[200].ckpt-577569.index
model_epoch1_128_0.100_[200].ckpt-1155138.index
model_epoch0_128_0.100_[200].ckpt-577569.data-00000-of-00001
model_epoch1_128_0.100_[200].ckpt-1155138.data-00000-of-00001
model_epoch2_128_0.100_[200].ckpt-1732707.data-00000-of-00001
model_epoch2_128_0.100_[200].ckpt-1732707.index
model_epoch3_128_0.100_[200].ckpt-2310276.data-00000-of-00001
model_epoch3_128_0.100_[200].ckpt-2310276.index
model_epoch4_128_0.100_[200].ckpt-2887845.data-00000-of-00001
model_epoch4_128_0.100_[200].ckpt-2887845.index
model_epoch5_128_0.100_[200].ckpt-3465414.data-00000-of-00001
model_epoch5_128_0.100_[200].ckpt-3465414.index
model_epoch5_128_0.100_[200].ckpt-3465414.meta
model_epoch6_128_0.100_[200].ckpt-4042983.data-00000-of-00001
model_epoch6_128_0.100_[200].ckpt-4042983.index
model_epoch6_128_0.100_[200].ckpt-4042983.meta
model_epoch7_128_0.100_[200].ckpt-4620552.data-00000-of-00001
model_epoch7_128_0.100_[200].ckpt-4620552.index
model_epoch7_128_0.100_[200].ckpt-4620552.meta
model_epoch8_128_0.100_[200].ckpt-5198121.data-00000-of-00001
model_epoch8_128_0.100_[200].ckpt-5198121.index
model_epoch8_128_0.100_[200].ckpt-5198121.meta
model_epoch9_128_0.100_[200].ckpt-5775690.data-00000-of-00001
model_epoch9_128_0.100_[200].ckpt-5775690.index
model_epoch9_128_0.100_[200].ckpt-5775690.meta
model_epoch10_128_0.100_[200].ckpt-6353259.data-00000-of-00001
model_epoch10_128_0.100_[200].ckpt-6353259.index
model_epoch10_128_0.100_[200].ckpt-6353259.meta
model_epoch11_128_0.100_[200].ckpt-6930828.data-00000-of-00001
model_epoch11_128_0.100_[200].ckpt-6930828.index
model_epoch11_128_0.100_[200].ckpt-6930828.meta
model_epoch12_128_0.100_[200].ckpt-7508397.data-00000-of-00001
model_epoch12_128_0.100_[200].ckpt-7508397.index
model_epoch12_128_0.100_[200].ckpt-7508397.meta
model_epoch13_128_0.100_[200].ckpt-8085966.data-00000-of-00001
model_epoch13_128_0.100_[200].ckpt-8085966.index
model_epoch13_128_0.100_[200].ckpt-8085966.meta

**Comment by hejunqing** [comment]
also the same error using import_meta_graph

**Comment by michaelisard** [comment]
Can you fill in the issues template, and also give more details of what you were doing when the error occurred?

**Comment by hejunqing** [comment]
Thank you.Michaelisard.
I am trying to restore  the saved models trained yesterday,The saved models are listed as above but  can't be restored because of the NotFoundError. There is no warning or error when I saved models.
I want to load each model and evaluate, not just the latest one.


The codes of restoring models are in validate.py is in below
Thanks!
[validate_models.zip](https://github.com/tensorflow/tensorflow/files/632847/validate_models.zip)

**Comment by ppwwyyxx** [comment]
Could you try the following:
1. use a model name without the character `[]`, and:
2. when you tried to restore, use the full relative path `./model_epoch10` rather than `model_epoch10`

If my guess is right then you should see it work. It it doesn't, could you give the __steps__ so that people can reproduce the problem (i.e. how to use your code).

**Comment by hejunqing** [comment]
@ppwwyyxx your advice help! 
I use the model name without [] and retrained models.Then they can be restore!
I will add this special characters to DON'T USE list.
Thank you very much

**Comment by ritterliu** [comment]
"when you tried to restore, use the full relative path ./model_epoch10 rather than model_epoch10"
It works, thank you

**Comment by chrisrytting** [comment]
Thank you @ppwwyyxx using the full path also works for me

**Comment by zwep** [comment]
If anyone has some trouble with loading a checkpoint via saver.restore(), here is an alternative way I have working

saver = tf.train.import_meta_graph(name_of_the_meta_file)
 # create a session in which we can load the checkpoint values
sess = tf.Session()
# get checkpoint state
ckpt = tf.train.get_checkpoint_state(path_to_your_checkpoint)

# restore session if both variables are not empty
if ckpt and ckpt.model_checkpoint_path:
    saver.restore(sess, ckpt.model_checkpoint_path)

**Comment by Roc-J** [comment]
I met a problem 

INFO:tensorflow:Error reported to Coordinator: <class 'tensorflow.python.framework.errors_impl.NotFoundError'>, Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./object_detection/training/model.ckpt-0
         [[Node: save/RestoreV2_901 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:ps/replica:0/task:0/device:CPU:0"](_recv_save/Const_0_S1, save/RestoreV2_901/tensor_names, save/RestoreV2_901/shape_and_slices)]]
         [[Node: save/restore_all/NoOp_S4 = _Recv[client_terminated=false, recv_device="/job:master/replica:0/task:0/device:CPU:0", send_device="/job:ps/replica:0/task:0/device:CPU:0", send_device_incarnation=5144029972012398702, tensor_name="edge_4518_save/restore_all/NoOp", tensor_type=DT_FLOAT, _device="/job:master/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'save/RestoreV2_901', defined at:
  File "/home/deeplearning/projects/Google/tensorflow/models/research/object_detection/train.py", line 198, in <module>
    tf.app.run()
  File "/home/deeplearning/virtualenv/python3/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/deeplearning/projects/Google/tensorflow/models/research/object_detection/train.py", line 194, in main
    worker_job_name, is_chief, FLAGS.train_dir)
  File "/home/deeplearning/projects/Google/tensorflow/models/research/object_detection/trainer.py", line 281, in train
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours)
  File "/home/deeplearning/virtualenv/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/home/deeplearning/virtualenv/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/deeplearning/virtualenv/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/deeplearning/virtualenv/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/home/deeplearning/virtualenv/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/deeplearning/virtualenv/python3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/deeplearning/virtualenv/python3/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/deeplearning/virtualenv/python3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/deeplearning/virtualenv/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/deeplearning/virtualenv/python3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access


my command is 
python ./object_detection/train.py --logtostderr --train_dir=/home/deeplearning/projects/Google/tensorflow/models/research/object_detection/training --pipeline_config_path=/home/deeplearning/projects/Google/tensorflow/models/research/object_detection/training/faster_rcnn_resnet101_coco.config

i don't konw how to salve! anyone once met ?

**Comment by Roc-J** [comment]
the problem is that running the command , the training_dir only 2 files 
model.ckpt-0.data-00000-of-00001
model.ckpt-0.index

**Comment by SukwooH** [comment]
This is the result I got although I employed virtual machine...

![screenshot from 2018-08-08 15-25-00](https://user-images.githubusercontent.com/33311950/43840039-f2657e48-9b1f-11e8-8d36-ecbe5477d00f.png)

**Comment by rojour** [comment]
Having the same issue.

print(os.listdir('/opt/ml/input/training'))   shows

['snapshot-3.data-00000-of-00001', 'events.out.tfevents.1547818794.aws', 'snapshot-3.index', 'snapshot-3.meta', 'checkpoint', 'events.out.tfevents.1547818798.aws']

with tf.Session(config=tf.ConfigProto(allow_soft_placement=True)) as sess:
            sess.run(tf.global_variables_initializer())
            sess.run(tf.local_variables_initializer())

            ckpt = tf.train.get_checkpoint_state(args.log_dir)

            # Load the latest model
            if ckpt and ckpt.model_checkpoint_path:
            # Restores from checkpoint
                saver.restore(sess, ckpt.model_checkpoint_path)
            else:
                return

Err: /usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Unsuccessful TensorSliceReader constructor: Failed to get matching files on /opt/ml/model/training/snapshot-3: Not found: /opt/ml/model/training; No such file or directory
#011 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:




Any suggestions?

**Comment by rojour** [comment]
forgot to mention that

args.log_dir = '/opt/ml/input/training'

**Comment by woshidandan** [comment]
i met the same problem，when i first restore the params，no problem accur，but when i second restore the params，it cause this problem. After that, I referred to everyone's opinions, try to solve this problem, but failed. But when i put the load code befor my main code，this problem is solved (for example, you can load params after import some packages and before your main class function).

自带中文翻译，嘤嘤嘤。
之前我也遇到了这样的问题，试了上面的老哥们提到的解决方法，发现不起作用。因为我的情况是，我能读进去之前保存的参数，而且也能使用这些参数分类或者预测，但是我第二次读的时候，就报错，分析了一下，发现第二次读的时候，参数的名字都被修改了，导致找不到。我猜测可能是sess的缘故，所以把读取参数的那些代码全放到最前面，主函数的外面。

example code：
import tensorflow as tf
....
class Test:
    saver.restore....

you can change it to:

import tensorflow as tf
saver.restore....
....
class Test:

**Comment by zhushichuan** [comment]
Generally, the catalog of the model is incorrect.
