### ISSUE TITLE
Cuda Compute Capability 3.0 not supported on Windows?

### ISSUE THREAD

**Issue by SaltyOrange** [tensorflow/tensorflow#6083]
Running on Windows 8.1, Python 3.5.2, Cuda 8.0

name: GeForce GTX 660M
major: 3 minor: 0 memoryClockRate (GHz) 0.95
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.64GiB

I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:948] Ignoring visible gpu device (device: 0, name: GeForce GTX 660M, pci bus id: 0000:01:00.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.

**Comment by mrry** [comment]
We currently build the PIP package for compute capabilities 3.5 and 5.2 by default. I just sent a PR to expand this to 3.0 (#6092)... if you want to try building it yourself, you could clone that PR and give it a try!

**Comment by mrry** [comment]
Note that this support will soon be available in the nightly builds, and we'll cherry-pick it into the final release of 0.12.
