### ISSUE TITLE
Image Segmenter | tflite-suuport | AttributeError: type object 'SegmentationOptions' has no attribute 'OutputType'

### ISSUE THREAD

**Issue by VIS-WA** [tensorflow/tensorflow#60836]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tflite-support 0.1.0a1

### Custom Code

No

### OS Platform and Distribution

MacOS Ventura 13.4

### Python version

3.8.7

### Current Behaviour?

The syntax provided for using [Image Segmenter](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/inference_with_metadata/task_library/image_segmenter.md)  did not execute ```processor.SegmentationOptions``` in python environment.

### Possible Fix:
The line 
``` 
segmentation_options = processor.SegmentationOptions(
    output_type=processor.SegmentationOptions.OutputType.CATEGORY_MASK) 
``` 
should have been 
```
segmentation_options = processor.SegmentationOptions(
    output_type=processor.SegmentationOptions.output_type.CATEGORY_MASK) 
```

### Standalone code to reproduce the issue

```shell
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/inference_with_metadata/task_library/image_segmenter.md#step-2-using-the-model-2
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "image_segmenter.py", line 8, in <module>
    segmentation_options = processor.SegmentationOptions(output_type=processor.SegmentationOptions.OutputType.CATEGORY_MASK)
AttributeError: type object 'SegmentationOptions' has no attribute 'OutputType'
```
</details>

**Comment by pkgoogle** [comment]
It seems the task module is not currently exposed in the package, I'm guessing by mistake, this is blocking testing of this.

```
pip install tflite-support
```
```
python test.py
 from tflite_support.task import vision
ModuleNotFoundError: No module named 'tflite_support.task'
```
@lu-wang-g can you take a look?
