### ISSUE TITLE
Tensorflow Lite on Raspberry Pi

### ISSUE THREAD

**Issue by baqwas** [tensorflow/tensorflow#60835]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tflite_runtime-2.12.0-cp39-cp39-manylinux2014_armv7l.whl

### Custom Code

Yes

### OS Platform and Distribution

Linux raspbari14 6.1.32-v7+ #1656 SMP Wed Jun  7 11:31:19 BST 2023 armv7l GNU/Linux

### Python version

Python 3.9.2 (default, Mar 12 2021, 04:06:34) 

### GCC/Compiler version

[GCC 10.2.1 20210110] on linux

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current Behaviour?

Not working as documented:

`import tflite_runtime.interpreter as tflite`

How to import Tensorflow Lite in python scripts?

### Standalone code to reproduce the issue

```shell
$ python3 -m pip install tflite-runtime
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting tflite-runtime
  Downloading tflite_runtime-2.12.0-cp39-cp39-manylinux2014_armv7l.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB 2.6 MB/s 
Requirement already satisfied: numpy>=1.19.2 in /home/chowkidar/.local/lib/python3.9/site-packages (from tflite-runtime) (1.23.1)
Installing collected packages: tflite-runtime
Successfully installed tflite-runtime-2.12.0
$ python3
Python 3.9.2 (default, Mar 12 2021, 04:06:34) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
>>> import tflite_runtime.interpreter as tflite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chowkidar/.local/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 33, in <module>
    from tflite_runtime import _pywrap_tensorflow_interpreter_wrapper as _interpreter_wrapper
ImportError: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/chowkidar/.local/lib/python3.9/site-packages/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.so)
>>>
```

### Relevant log output

_No response_</details>

**Comment by SuryanarayanaY** [comment]
Hi @baqwas ,

From the error `ModuleNotFoundError: No module named 'tensorflow'` it seems Tensorflow not installed in your current directory or it might have corrupted in which case try uninstalling tensorflow and then install again and let us know the result.

Also it seems your environment has glib version `3.4.29` but Manlinux wheels have limitation w.r.t max glib version supported. Please refer the manlinux [readme](https://github.com/pypa/manylinux) the max glib version supported is 2.17 for `manylinux2014` wheel. Please downgrade the glib version to 2.17 and then try the installation.

Thanks!

**Comment by baqwas** [comment]
Thanks for the quick feedback. I'll try your suggestions shortly. I have Raspberry Pi 3B+ and 4 but cannot install **tensorflow** successfully with the basic the pip method owing to version conflicts. Are there **tensorflow** version constraints for ARM **arm64/aarch64** (using Raspberry Pi OS not Raspbian OS for Bullseye and Ubuntu 23.04 Desktop [sic])?

Regards.

**Comment by SuryanarayanaY** [comment]
@baqwas ,

For Tensorflow there are no prebuilt binaries for Arm/AArch architecture. Maybe you can use build from source for building the wheel for Arm/Aarch architecture referring to the [source](https://www.tensorflow.org/install/source) here.

Thanks!

**Comment by baqwas** [comment]
Hello @SuryanarayanaY,

Thanks for your suggestion. I've run into several version conflicts (with the supporting utilities and with earlier versions of tensorflow source) and realized that others too have experienced similar problems. It is insane/impractical expectation on my part to use TF on RPi; I'd like to use only TFL consistently on RPi (arm64/aarch64). I can get going with some examples but the slightest upgrade (clang, gcc, etc.) break the solution.

Thanks for the link (even though I was familiar with it previously but could not complete ALL the steps successfully - not an issue for me right now!). I repeat the exercise in due course.

Thanks for your support all the same. At least I have an informed person responding to my queries. Helps me to stay level headed about expectations.

Regards.
