### ISSUE TITLE
Cannot pick GPU unavailable

### ISSUE THREAD

**Issue by Cazs03** [tensorflow/tensorflow#60830]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.12.0

### Custom Code

Yes

### OS Platform and Distribution

Windows 10 build 19045  0

### Python version

Python 3.10.10

### CUDA/cuDNN version

Cuda compilation tools, release 12.1, V12.1.105 Build cuda_12.1.r12.1/compiler.32688072_0

### GPU model and memory

1070 TI 8g 

### Current Behaviour?

A bug happened!
`  gpus = tf.config.experimental.list_physical_devices('GPU')`
_This piece of code return empty array_
When in reallity have two GTX 1070 
Description                  : NVIDIA GeForce GTX 1070 Ti x 2
at least hoped to get one
I'm follow all installation step by step  verifying paths 
I don't know what to do anymore

### Standalone code to reproduce the issue

```shell
Follow this step guide:
https://www.tensorflow.org/install/gpu?hl=es-419
Install tensorflow, 
Configuration path
Cuda
Verification
os.environ["CUDA_HOME"] = r"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1"
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@Cazs03,
If you are getting the empty list for the **gpus = tf.config.experimental.list_physical_devices('GPU')**, means the GPU installation was not happened correctly in your system.

Could you please confirm whether you are trying to install the tf v2.12 on windows from pip or the build from source. Also please provide the complete error log and the steps you followed to install. It helps us to debug the issue in an effective way. Thank you!

**Comment by Cazs03** [comment]
Sorry for delay.
example snippet:
```
        gpus = tf.config.list_physical_devices('GPU')
        if gpus:
            try:
                tf.config.experimental.set_memory_growth(gpus[0], True)
                tf.config.set_visible_devices(gpus[0], 'GPU')
                print(
                    "Utilizando la GPU:",
                    tf.config.list_logical_devices('GPU')[0]
                )
            except RuntimeError as e:
                print(e)
        else:
            print("No se encontró ninguna GPU.")
```
pip install tensorflow

**Comment by Cazs03** [comment]
My path:
_C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin;
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\libnvvp;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\Program Files\NVIDIA Corporation\Nsight Compute 2023.1.1\;
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;
C:\cuda\bin_
