### ISSUE TITLE
Functional Bug：Could not interpret serialized activation function

### ISSUE THREAD

**Issue by PhyllisJi** [tensorflow/tensorflow#60840]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf2.12.0

### Custom Code

Yes

### OS Platform and Distribution

MacOs

### Python version

3.9

#### Output

```
Could not interpret serialized activation function: Tensor("conv1a/BiasAdd:0", shape=(None, 224, 224, 64), dtype=float32)
```

#### Document

| `activation` | Activation function to use. If you don't specify anything, no activation is applied (see [`keras.activations`](https://www.tensorflow.org/api_docs/python/tf/keras/activations)). |
| ------------ | ------------------------------------------------------------ |

### Standalone code to reproduce the issue
```py
x = keras.layers.Conv2D(filters=64, kernel_size=3, strides=1, activation="deserialize", padding="same", name="conv1a")(input_tensor)
```

```py
x = keras.layers.Conv2D(filters=64, kernel_size=3, strides=1, activation="serialize", padding="same", name="conv1a")(input_tensor)
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@PhyllisJi,
Thank you for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 




Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!
