### ISSUE TITLE
installing error about tensorflow 2.7.3

### ISSUE THREAD

**Issue by zengletian1491** [tensorflow/tensorflow#60858]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.7.3

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.8.10

### GCC/Compiler version

7.5.0

### CUDA/cuDNN version

cuda 11.3,cuDNN 8.2.1

### Current Behaviour?

My computer configurations are:
gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
cuda 11.3
cudnn 8.2.1
numpy 1.24.3
pandas 2.0.2
matplotlib 3.7.1
scipy 1.10.1
scikit-mage 0.21.0
scikit-learn 1.2.2
lapack 3.11.0

When I typed in “sudo pip3 install tensorflow_gpu-2.7.3-cp38-cp38-manylinux2010_x86_64.whl”, the results occurred as follows:

**Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.8/dist-packages (from importlib-metadata>=4.4; python_version < "3.10"->markdown>=2.6.8->tensorboard~=2.6->tensorflow-gpu==2.7.3) (3.15.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard~=2.6->tensorflow-gpu==2.7.3) (3.1.0)
Collecting pyasn1>=0.1.3
  Downloading pyasn1-0.5.0-py2.py3-none-any.whl (83 kB)
     |████████████████████████████████| 83 kB 21 kB/s 
Installing collected packages: absl-py, tensorflow-io-gcs-filesystem, opt-einsum, grpcio, termcolor, astunparse, h5py, protobuf, tensorflow-estimator, keras-preprocessing, google-pasta, gast, wrapt, libclang, keras, markdown, tensorboard-data-server, requests-oauthlib, cachetools, pyasn1, rsa, pyasn1-modules, google-auth, google-auth-oauthlib, werkzeug, tensorboard, flatbuffers, tensorflow-gpu
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.6.1
    Not uninstalling protobuf at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'protobuf'. No files were found to uninstall.
Successfully installed absl-py-1.4.0 astunparse-1.6.3 cachetools-5.3.1 flatbuffers-2.0.7 gast-0.4.0 google-auth-2.20.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 grpcio-1.54.2 h5py-3.8.0 keras-2.7.0 keras-preprocessing-1.1.2 libclang-16.0.0 markdown-3.4.3 opt-einsum-3.3.0 protobuf-3.19.6 pyasn1-0.5.0 pyasn1-modules-0.3.0 requests-oauthlib-1.3.1 rsa-4.9 tensorboard-2.13.0 tensorboard-data-server-0.7.1 tensorflow-estimator-2.7.0 tensorflow-gpu-2.7.3 tensorflow-io-gcs-filesystem-0.32.0 termcolor-2.3.0 werkzeug-2.3.6 wrapt-1.15.0**

Could you give me some suggestions?Thanks very much!

### Standalone code to reproduce the issue

```shell
---
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@zengletian1491 Could you please make sure that you have followed the steps mentioned [here](https://www.tensorflow.org/install/source). 
Thank you!
