### ISSUE TITLE
Hi @radres2019, Thank you for reporting the issue!

### ISSUE THREAD

**Issue by anikde** [tensorflow/tensorflow#60877]
Hi @radres2019, Thank you for reporting the issue!
You are seeing this error because Colab has python version 3.10. Tensorflow quantum 0.7.2 is compatible with Python 3.7, 3.8, 3.9  and does not support Python 3.10. 

Please refer to the gist where I was able to install Tensorflow quantum sucessfully [here](https://colab.sandbox.google.com/gist/synandi/b733cccf4a90d29e5feefb606f02f843/60428.ipynb). Thank you!

_Originally posted by @synandi in https://github.com/tensorflow/tensorflow/issues/60428#issuecomment-1527270841_

**Comment by anikde** [comment]
I used your script and I could install python3.8 in the google Colab environment but then while importing tensorflow_quantum it shows ```ModuleNotFoundError: No module named 'tensorflow_quantum'```
For reference I have link my [colab notebook](https://colab.research.google.com/drive/11hnCAIOAKn938fuVLxhIueMlbaMhQ_dG?usp=sharing)

**Comment by mihaimaruseac** [comment]
Should be opened in the quantum repo, not TF.

**Comment by SuryanarayanaY** [comment]
Hi @anikde ,

Could you please report the issue at [tensorflow-quantum](https://github.com/tensorflow/quantum/issues) repo as instructed above.

Thanks!

**Comment by anikde** [comment]
Hi @SuryanarayanaY @mihaimaruseac, I have raised the issue in tensorflow-quantum repo as directed.

**Comment by SuryanarayanaY** [comment]
Hi @anikde ,

Please refer to attached [readme.md](https://github.com/tensorflow/quantum/blob/master/docs/install.md) file from tensorflow-quantum for installation instructions. 

**Requirements**

> pip 19.0 or later (requires manylinux2010 support)
> [TensorFlow == 2.11.0](https://www.tensorflow.org/install/pip)

It seems this works only with tensorflow==2.11. Also please check other requirements mentioned in readme.md are fulfilled. Could you please have a look at those instructions and let us know if it helps.

Thanks!

**Comment by anikde** [comment]
@SuryanarayanaY I have tired installing the updated version of tensorflow but that too didn't work. I have attached the [link to my notebook](https://colab.research.google.com/drive/11hnCAIOAKn938fuVLxhIueMlbaMhQ_dG?authuser=1&usp=drive_open#scrollTo=aMujKtZb7oDA) for reference.
