### ISSUE TITLE
Flutter - "Select Tensorflow Ops" not working

### ISSUE THREAD

**Issue by galaturka** [tensorflow/tensorflow#60902]
**System information**
- OS Platform and Distribution : Windows 11
- Flutter version : 3.7.12
- TensorFlow installed from (source or binary): tflite_flutter 0.10.1 (https://pub.dev/packages/tflite_flutter)
- TensorFlow version (or github SHA if from source): 2.4.1 (implementation 'org.tensorflow:tensorflow-lite:2.4.1') --> in build.gradle

Hello,

I try to implement Google Android autocomplete project (https://github.com/tensorflow/examples/tree/master/lite/examples/generative_ai/android) on **flutter**. 
Here is the detailed project implementation website(https://codelabs.developers.google.com/kerasnlp-tflite#0
) for reference.

### I created .tflite file using below given codes :

@tf.function
def generate(prompt, max_length):
    return gpt2_lm.generate(prompt, max_length)

concrete_func = generate.get_concrete_function(tf.TensorSpec([], tf.string), 100)

gpt2_lm.jit_compile = False
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func],
                                                            gpt2_lm)
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
converter.allow_custom_ops = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.experimental_select_user_tf_ops = ["UnsortedSegmentJoin", "UpperBound"]
converter._experimental_guarantee_all_funcs_one_use = True
quant_generate_tflite = converter.convert()

### Then I tried to implement generated .tflite model in flutter using **tflite_flutter** package as below(focussed) :

import 'package:tflite_flutter/tflite_flutter.dart';

final String MODEL_PATH = 'assets/autocomplete.tflite';

void loadModel() async {
    try {
      print('Loading model...');
      _interpreter = await Interpreter.fromAsset(MODEL_PATH);
      print('Model loaded');
    } on Exception catch (e) {
      print('Error while loading model: $e');
    }
  }

### On build.gradle file in android folder, I made some arrangements as below :

  aaptOptions {
        noCompress 'tflite'
        noCompress 'lite'
    }

dependencies {
        implementation 'org.tensorflow:tensorflow-lite:2.4.1'
        implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:2.12.0'
}

### During debugging, I get this error message :

E/tflite  (31048): Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select
E/tflite  (31048): Node number 2 (FlexMutableHashTableV2) failed to prepare.

After a bit of investigation and having a double-check on android example application by google, I realized that there are libraries already builded with an .aar file extension. Then I copied android version of this file (https://storage.googleapis.com/download.tensorflow.org/models/tflite/generativeai/tensorflow-lite-select-tf-ops.aar) into my flutter android folder under app/libs. I also updated my build.gradle dependencies by adding implementation "(fileTree(dir: "libs", include: ["*.aar"]))".

### Program UI starts without any issue, but still I get this "Select TensorFlow op(s) error : 

E/tflite  (31048): Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select

Could you please support me on this topic ? Maybe there is a missing function for interpreter in tflite_flutter package compared to native android ones. 
If necessary, I can share my flutter project.

Thanks in advance.
Gorkem

**Comment by sushreebarsa** [comment]
@galaturka Thank you for opening this issue. You are using an older version of TF which is not actively supported. Could you please provide the entire tflite model to debug the issue if that persists in the newer version?
Thank you!

**Comment by parnurzeal** [comment]
@galaturka I experience the problem. Are you able to figure this out yet?

**Comment by pjpratik** [comment]
Hi @galaturka 

Can you try with latest nightly snapshot and see if you are still facing the issue?

```
dependencies {
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
    // This dependency adds the necessary TF op support.
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly-SNAPSHOT'
}
```
Thanks.

**Comment by OlatunjI-Ruth** [comment]
Hi @galaturka were you able to resolve this issue? i am currently facing it.
