### ISSUE TITLE
Typo in docs transfer_learning.ipynb

### ISSUE THREAD

**Issue by kentmchenry** [tensorflow/tensorflow#60907]
It seems there is a typo in https://www.tensorflow.org/tutorials/images/transfer_learning

In the augmentation section there is a Note as follows:

**Typo**
`Note: These layers are active only during training, when you call [Model.fit](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit). They are inactive when the model is used in inference mode in [Model.evaluate](https://www.tensorflow.org/api_docs/python/tf/keras/Model#evaluate) or [Model.fit](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit).`

If I understand correctly the **second** reference to `Model.fit` is not intended or correct and should be changed to `Model.call` as follows:

**Correction**
`Note: These layers are active only during training, when you call [Model.fit](https://www.tensorflow.org/api_docs/python/tf/keras/Model#fit). They are inactive when the model is used in inference mode in [Model.evaluate](https://www.tensorflow.org/api_docs/python/tf/keras/Model#evaluate) or [Model.call](https://www.tensorflow.org/api_docs/python/tf/keras/Model#call).`

I'm willing to help with a pull request if confirmed.

**Comment by Ashwin1102** [comment]
Can I work on this issue?

**Comment by SuryanarayanaY** [comment]
Hi @kentmchenry ,

Thanks for your observation and I believe you are right. `Model.fit` is meant for training on the inputs for certain epochs. The second reference of model.fit should be actually replaced with model.call .

If you are willing to contribute PR please feel free to do. Thanks!

**Comment by kentmchenry** [comment]
@SuryanarayanaY working it...

**Comment by kentmchenry** [comment]
@SuryanarayanaY PR is here: https://github.com/tensorflow/docs/pull/2236

**Comment by SuryanarayanaY** [comment]
Hi @kentmchenry ,

Thanks for the PR. I can see the changes also approved by Engg team. Thanks for reporting and also for PR.

**Comment by kentmchenry** [comment]
Welcome, glad I could help

**Comment by SuryanarayanaY** [comment]
@kentmchenry ,

The PR has been merged now. Could we mark it as resolved now. Thanks!
