### ISSUE TITLE
 NUMA and libcusolver.so.11 ISSUE

### ISSUE THREAD

**Issue by nourama30** [tensorflow/tensorflow#60918]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.8.0

### Custom Code

Yes

### OS Platform and Distribution

Amazon Linux 2

### Mobile device

Other Linux x86_64

### Python version

3.9 

### Bazel version

4.2.1

### GCC/Compiler version

7.3.1

### CUDA/cuDNN version

11.2

### GPU model and memory

NVIDIA

### Current Behaviour?

I'm using a ready template launch from AMI catalog on Amazon, which is AWS Deep Learning AMI GPU TensorFlow 2.8.0 (Amazon Linux 2) Built with AWS optimized TensorFlow, NVIDIA CUDA, cuDNN, NCCL, GPU Driver, Docker, NVIDIA-Docker and EFA support. Platform: Other LinuxArchitecture: x86_64 Root device type: ebs Virtualization: hvm ENA enabled: Yes. and my application is dockerized which uses version tensorflow 2.8.0 

When i wanted to activate the GPU , I got errors, like :
**W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory**

I checked is this file exists , and it does exits. i have exported in the env to ensure it will work. but still the same issue. 

### Standalone code to reproduce the issue

```shell
I'm using ECS on AWS. so everytime i stop the task and launch again but the issue persists.
I'm using instance type g4dn x large
```

### Relevant log output

```shell
Skipping registering GPU devices...
2023-06-11 22:24:17.218609: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
2023-06-11 22:24:17.218523: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory
2023-06-11 22:24:17.217687: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
```
</details>

**Comment by tilakrayal** [comment]
@nourama30,
Could you please try to follow the below steps mentioned:

Edit ./etc/conda/activate.d/env_vars.sh as follows:

```
#!/bin/sh

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib
```

Edit ./etc/conda/deactivate.d/env_vars.sh as follows:

```
#!/bin/sh

unset LD_LIBRARY_PATH
```

https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#macos-and-linux

Also Could you please refer this documentation [source](https://www.tensorflow.org/install/pip#linux:~:text=your%20conda%20environment.-,export%20LD_LIBRARY_PATH%3D%24LD_LIBRARY_PATH%3A%24CONDA_PREFIX/lib/,CONDA_PREFIX/lib/%27%20%3E%20%24CONDA_PREFIX/etc/conda/activate,-.d/).

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/`

and Could you please try to install latest stable tensorflow v2.12 and let us know if you are facing same issue. Thank you!
