### ISSUE TITLE
android gpu delegate Failed to build program executable

### ISSUE THREAD

**Issue by mengran1234** [tensorflow/tensorflow#60936]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.10 or 2.11

### Custom Code

Yes

### Current Behaviour?

A bug happened!
I test gpu delegate on oppo R9. 
TfLiteInterpreterModifyGraphWithDelegate will reture error value.

ERROR: Failed to build program executable - Build program failure<source>:35:26: error: OpenCL extension 'cl_khr_3d_image_writes' is not supported
#pragma OPENCL EXTENSION cl_khr_3d_image_writes : enable
                         ^
error: Compiler frontend failed (error code 58)

ERROR: Falling back to OpenGL
ERROR: TfLiteGpuDelegate Init: OpenGL-based API disabled
ERROR: TfLiteGpuDelegate Prepare: delegate is not initialized
ERROR: Node number 100 (TfLiteGpuDelegateV2) failed to prepare.
ERROR: Restored original execution plan after delegate application failure.
tflite gpu Delegate create failed!2

### Standalone code to reproduce the issue

```shell
oppo R9 is produced in 2016 year
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@mengran1234,
Could you please provide the complete standalone code to reproduce the issue which helps us to analyse the issue in an effective way. Thank you!
