### ISSUE TITLE
the tf keras models load_model() used for loading ml model is not able to load model

### ISSUE THREAD

**Issue by purushottam22** [tensorflow/tensorflow#60951]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### Current Behaviour?

Hi, I am trying to load my deep learning model using  **tensorflow keras models load_model ()** . when I run it for first time it got loaded but from next time** it is not loading**. Like it is in this function for more than 30 min. 

I store my model in **.h5** format. model size is approx 13 MB.
At the time of saving deep learning, I use model.save() 

I am using a machine with 128 GB RAM. 
I am using multiprocessing with no of worker 16. Sometime it worked and sometime is got stucked.

### Standalone code to reproduce the issue

```shell
tensorflow.keras.models.load_model.()
```

### Relevant log output

_No response_</details>

**Comment by pks916** [comment]
Remove the dot before the brackets, 
'tensorflow.keras.model.load_model()'
should do the trick

**Comment by tilakrayal** [comment]
@purushottam22,
Could you please provide the complete standalone code to reproduce the issue which helps us to analyse the issue in an effective way. Thank you!

**Comment by purushottam22** [comment]
def retrieve_model(self, model_path:str ,model_type:str):
      '''
      Desc:- It retrieves the model object based on model type and its model path
      :param model_path:string
      :param model_type:string
      :return:model_objet:object
      '''
      if model_type=="tensorflow":
        try:
          print(model_path, type(model_path))
          model_dir = model_path[0:-10]
          print(os.listdir(model_dir))
          
          model_object=tf.keras.models.load_model(model_path, custom_objects=None, compile=True, options=None)

          print("model is loaded")
          print(model_object)
          print("*-"*10)
          return FileResults(model_object).get_model_object
        except Exception as err:
          print("retrieve_model method failure reason is: {err}")


This is the code I used. I write some print statement to verify that in which line it is stopped.

**Comment by tilakrayal** [comment]
@purushottam22,
The code provided is not complete hence it would be difficult for us to pinpoint the issue. Please share complete stand alone code to replicate the issue or a colab gist with the error reported.? That will allow us to determine the source of the issue easily. Thank you!
