### ISSUE TITLE
error download files during run ./configure

### ISSUE THREAD

**Issue by civilman628** [tensorflow/tensorflow#6096]
when i run ./configure, there are 2 files can't be downloaded.

http://cdimage.debian.org/mirror/xbmc.org/build-deps/sources/swig-3.0.8.tar.gz

http://cdimage.debian.org/mirror/xbmc.org/build-deps/sources/giflib-5.1.4.tar.gz

============

ERROR: /home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/tensorflow/contrib/tfprof/python/tools/tfprof/BUILD:49:1: every rule of type _py_wrap_cc implicitly depends upon the target '@swig//:templates', but this target could not be found because of: no such package '@swig//': Error downloading from **http://cdimage.debian.org/mirror/xbmc.org/build-deps/sources/swig-3.0.8.tar.gz** to /home/scopeserver/.cache/bazel/_bazel_root/4bbf7fc8d0645aa96f0d41866ce2885c/external/swig: Error downloading http://cdimage.debian.org/mirror/xbmc.org/build-deps/sources/swig-3.0.8.tar.gz to /home/scopeserver/.cache/bazel/_bazel_root/4bbf7fc8d0645aa96f0d41866ce2885c/external/swig/swig-3.0.8.tar.gz: Timed out connecting to http://cdimage.debian.org/mirror/xbmc.org/build-deps/sources/swig-3.0.8.tar.gz : connect timed out.

ERROR: /home/scopeserver/RaidDisk/DeepLearning/mwang/tensorflow/tensorflow/core/platform/default/build_config/BUILD:96:1: no such package '@gif_archive//': Error downloading from **http://cdimage.debian.org/mirror/xbmc.org/build-deps/sources/giflib-5.1.4.tar.gz** to /home/scopeserver/.cache/bazel/_bazel_root/4bbf7fc8d0645aa96f0d41866ce2885c/external/gif_archive: Error downloading http://cdimage.debian.org/mirror/xbmc.org/build-deps/sources/giflib-5.1.4.tar.gz to /home/scopeserver/.cache/bazel/_bazel_root/4bbf7fc8d0645aa96f0d41866ce2885c/external/gif_archive/giflib-5.1.4.tar.gz: Timed out connecting to http://cdimage.debian.org/mirror/xbmc.org/build-deps/sources/giflib-5.1.4.tar.gz : connect timed out and referenced by '//tensorflow/core/platform/default/build_config:gif'.

**Comment by mrry** [comment]
This seems to be causing widespread trouble for our tests as well. It looks like #6098 should fix this.

**Comment by gunan** [comment]
cdimage.debian.org was down, and as @mrry suggested it is resolved with #6098 
Sorry for the inconvenience.
