### ISSUE TITLE
Issues with running transpose on GPU

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#610]
I’m running into a couple of issues with `transpose` on GPUs. First, even the forward computation can’t be registered on a GPU unless I explicitly set the `perm` option. For example this fails (I’m setting `allow_soft_placement=False` in the session `Config`):

```
with tf.device('/gpu:0'):
    a = tf.constant(npr.rand(5, 3).astype('float32'))
    b = tf.transpose(a)
```

with the following error:

```
InvalidArgumentError: Cannot assign a device to node 'transpose/Reverse': Could not satisfy explicit device specification '/gpu:0'
[[Node: transpose/Reverse = Reverse[T=DT_INT32, _device="/gpu:0"](transpose/Range, transpose/Reverse/dims)]]
```

If however I set `perm=(1, 0)` in the `transpose` operation above, it works. But that’s not the only problem, as the backward computation doesn’t work either way. For example this fails:

```
with tf.device('/gpu:0'):
    a = tf.Variable(tf.random_uniform([5, 3]))
    b = tf.transpose(a, perm=(1, 0))
    l = tf.reduce_sum(b)
    o = tf.train.AdamOptimizer().minimize(l)
    i = tf.initialize_all_variables()

sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=False))
sess.run(i)
sess.run(o)
```

with the following error:

```
InvalidArgumentError: Cannot assign a device to node 'gradients/transpose_grad/InvertPermutation': Could not satisfy explicit device specification '/gpu:0'
[[Node: gradients/transpose_grad/InvertPermutation = InvertPermutation[_device="/gpu:0"](transpose/perm)]]
```

**Comment by vrv** [comment]
I think we're just missing some declarations of the GPU kernel of Reverse for int32 here:

https://github.com/tensorflow/tensorflow/blob/9c3043ff3bf31a6a81810b4ce9e87ef936f1f529/tensorflow/core/kernels/reverse_op.cc#L148

Whoever fixes this should probably add tests for all supported types here:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/array_ops_test.py#L45

**Comment by fxsuper** [comment]
`Reverse` is not the only thing causing the problem though. In fact the problem with `Reverse` could be circumvented with an explicit term. What can't be circumvented is the `InvertPermutation` error.

**Comment by alquraishi** [comment]
`Reverse` is not the only thing causing the problem though. In fact the problem with `Reverse` could be circumvented with an explicit term. What can't be circumvented is the `InvertPermutation` error.

**Comment by martinwicke** [comment]
InvertPermutation does not currently have a GPU kernel at all. We may be
able to cheat our way to one with an appropriate HostMemory declaration, or
we have to properly implement a GPU kernel. Either way, it would be in
transpose_op.cc.

**Comment by girving** [comment]
Except for error checking, it's much easier to implement `InvertPermutation` on GPU now that we have code for `tf.scatter` on GPU.  A bit of refactoring would probably let `InvertPermutation` reuse the functors for scatter.

**Comment by ibab** [comment]
Just had a look at `InvertPermutation` and noticed that a GPU version based on `HostMemory` has been added by now.
I like the idea of re-using `ScatterFunctor` for this, but it wouldn't check whether there are duplicate permutation indices in the input (which the current version of the code does).

**Comment by tfboyd** [comment]
This issue is quite old and hasn't had recent activity.
