### ISSUE TITLE
Feature request - Android example app for Windows tensorflow.

### ISSUE THREAD

**Issue by AndreyRub** [tensorflow/tensorflow#6101]
There is now a support of TensorFlow for Windows. I installed it using the instructions provided as part of Anaconda, and it works. However, I can't seem to find information about developing an application with TensorFlow for Android in Windows, by using Android Studio.

I found the path of TensorFlow installation in Windows,  C:\Program Files\Miniconda2\envs\py35\Lib\site-packages\tensorflow\contrib\android\java, but it is completely empty.

Is there a chance of getting an example app for Windows Android Studio?

I've also asked it on stackeoverflow, but didn't get any answer yet. 
I am asking it here because it looks like the example has not been developed yet.
(http://stackoverflow.com/questions/40978859/creating-simple-android-app-using-android-studio-and-tensorflow/40979627#40979627)

**Comment by andrewharp** [comment]
There is an example Android application in tensorflow/examples/android. I don't know much about Anacondo, but tensorflow/contrib/android should not be empty (this provides the native inference interface used by the example app). We don't use or require python for the Android side of things, so this may be a clue (you have py35 in your path).

We also provide tensorflow/examples/android/build.gradle file that wraps around the TF Bazel build, which may now work for Android Studio on Windows (I haven't tested it). More support for cmake/maven etc is planned for the near future, which should address any remaining issues involved in building for Windows.

**Comment by AndreyRub** [comment]
Hi Andrew and thanks for your reply.

I have installed the official WIN package located at https://pypi.python.org/pypi/tensorflow-gpu/0.12.0rc0, following the instructions at https://developers.googleblog.com/2016/11/tensorflow-0-12-adds-support-for-windows.html.

Just to make sure I did not miss anything, I downloaded the .whl file manually, renamed it to .zip, opened and listed all the files and directories inside this package. There is nothing related to android. I am attaching a text file with a list of the files inside the .whl. 
I've also checked the Linux package and it also does not contain the Android example.

I guess that these .whl Python distributions do not contain anything other than Python support? If so, I guess that I need another source code/distribution. 
Following your advice, I will try the experimental TF Bazel build for Windows and update.

[files.txt](https://github.com/tensorflow/tensorflow/files/633199/files.txt)

**Comment by andrewharp** [comment]
@AndreyRub Yes, the whl file you reference seems to only be the TF Python API which wraps around a precompiled native library for Windows.

The process for Android is a bit different; please refer to  https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android which contains basic instructions for running the demo with Bazel. If it doesn't work on Windows you could probably build it in a VM, or wait for the cmake support that will be coming soon.

**Comment by andrewharp** [comment]
Closing; please reopen if issues persist.
