### ISSUE TITLE
Crashes in model.save, wrapt error

### ISSUE THREAD

**Issue by cmayer** [tensorflow/tensorflow#61063]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.12

### Custom Code

No

### OS Platform and Distribution

Fodera Linux

### Python version

3.11

### Current Behaviour?

Crashed when calling model.save()

See log below.

Worked after deinstalling tensorflow and wrapt. wrapt was 1.15.x
and installing tensorflow and wrapt==1.14.1

The problem is that when installing tensorflow, the wrapt 1.15.x is installed automatically and this is not playing with tensorflow.

### Standalone code to reproduce the issue

```shell
model.save('Modelname')

Causes the problem for any trained network.
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "ModelPredictorTraining.py", line 1415, in <module>
    run_hparam_on_grid(branched_model_1,
  File "ModelPredictorTraining.py", line 1403, in run_hparam_on_grid
    fitted_model.save('Model-name')
  File "/anaconda3/envs/tf2/lib/python3.11/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/anaconda3/envs/tf2/lib/python3.11/site-packages/tensorflow/python/trackable/data_structures.py", line 823, in __getattribute__
    return super().__getattribute__(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
</details>

**Comment by tilakrayal** [comment]
@cmayer,
Could you please provide the complete standalone code to reproduce the issue, it helps us to analyse the issue in an effective way. Thank you!

**Comment by cmayer** [comment]
I need some more time to prepare a stand alone example.

**Comment by tilakrayal** [comment]
@cmayer,
Please provide the simple standalone code which helps us to analyse the issue. Thank you!
