### ISSUE TITLE
Requested feature_data_ size 536907080 doesn't match 1960; Feature generation failed;

### ISSUE THREAD

**Issue by Svobi27** [tensorflow/tensorflow#61074]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

V2.8

### Custom Code

Yes

### Current Behaviour?

Hello Together,

I'm having a Problem with the micro_speech example for arduino from this repo: https://github.com/tensorflow/tflite-micro-arduino-examples/tree/main/examples/micro_speech

When trying to use this example with a new trained model from this jupyter noteboobk: https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/micro_speech/train

I always get the same error message:
Requested feature_data_ size 536907080 doesn't match 1960
Feature generation failed

The only thing i changed in the notebook was the tensorflow version. This is because this notebook was using 1.x Version which is no longer supported by colab and i changed it to work with the latest 2.x version

Can anyone help here?

Greetings,
Patrick

### Standalone code to reproduce the issue

```shell
https://github.com/tensorflow/tflite-micro-arduino-examples/tree/main/examples/micro_speech

 https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/micro_speech/train
```

### Relevant log output

_No response_</details>

**Comment by pjpratik** [comment]
Hi @Svobi27 

I was able to run the example after making some changes for TF 2.x version. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/c7d860614aa2fe32c06f8514e5f193bc/61074.ipynb).

Thanks.

**Comment by Svobi27** [comment]
Hello @pjpratik 

Thanks for the response!

I tried the arduino example with the model from your notebook but i still get the same error message unfortunatly...

**Comment by pjpratik** [comment]
@Svobi27 

I see that at a ticket [#2709](https://github.com/tensorflow/tflite-micro/issues/2079) has been opened in TFLite Micro repo.

Could you please close this issue as it being tracked there?

Thanks.

**Comment by pjpratik** [comment]
Hi @Svobi27 

As mentioned earlier,  this issue can be closed here and the issue: https://github.com/tensorflow/tflite-micro/issues/2079 can be opened since it is related to TFLite Micro.

Thanks.

**Comment by Svobi27** [comment]
Sorry missunderstood! reopened the issue again in the TFLite Micro repo

**Comment by pjpratik** [comment]
Thanks for opening the issue in TFLite Micro repro. Closing it here.
