### ISSUE TITLE
TF2.13 Breaks register_keras_serializable

### ISSUE THREAD

**Issue by seanpmorgan** [tensorflow/tensorflow#61085]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

pypi

### Tensorflow Version

TF2.13.0rc2

### Custom Code

Yes

### Current Behaviour?

When building TF Addons for TF2.13 we're noticing that our ability to register custom Keras objects as serializable has been broken:

```
@tf.keras.saving.register_keras_serializable('my_package')
class MyDense(tf.keras.layers.Dense):
    def __init__(self, units, **kwargs):
        super().__init__(units, **kwargs)
```

### Standalone code to reproduce the issue

```shell
Here it is shown as working in TF2.12:
https://colab.research.google.com/drive/172A4_GAiSFzWJr6iVAaFYMujVCwbTk3W?usp=sharing

Here it breaks in TF2.13:
https://colab.research.google.com/drive/16BH2aNXXw3zMVevx7IYMx5cH6fZsREO_?usp=sharing
```

### Relevant log output

```shell
ValueError: Unknown layer: 'MyDense'. Please ensure you are using a `keras.utils.custom_object_scope` and that this object is included in the scope. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
```
```
</details>

**Comment by qlzh727** [comment]
Likely related to the new keras saving introduced in the 2.13. Adding Francois and Neel for visibility.
