### ISSUE TITLE
UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods 

### ISSUE THREAD

**Issue by kbhargavi33** [tensorflow/tensorflow#61095]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

0.0.0-nightly-SNAPSHOT

### Custom Code

No

### Mobile device

Android Samsung Galaxy J5

### Current Behaviour?

Fatal Exception: java.lang.UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods. Check that the correct native libraries are present, and, if using a custom native library, have been properly loaded via System.loadLibrary():
  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__register_atfork" referenced by "libtensorflowlite_jni.so"
  
This is reproducible on lot of android devices running android version 5,6,7
This is happening in the nightly snapshots from probably last 2 weeks. Did not encounter this in previous nightly snapshots.

### Standalone code to reproduce the issue

```shell
val nnApiOption = NnApiDelegate.Options()
nnApiOption.setUseNnapiCpu(true)
val nnApiDelegate = NnApiDelegate(nnApiOption)
```

### Relevant log output

2023-06-28 10:52:35.629 29536-29620 InterpreterApi                      I  Didn't load native library: tensorflowlite_jni
2023-06-28 10:52:35.637 29536-29620 InterpreterApi                      I  Didn't load native library: tensorflowlite_jni_stable
2023-06-28 10:52:35.638 29536-29620 InterpreterApi                      I  Didn't load native library: tensorflowlite_jni_gms_client

</details>

**Comment by pjpratik** [comment]
Hi @kbhargavi33 

TF Nightly is not a stable version. Can you please check in latest stable version 2.12 and let us know if you are still facing the issue?

Thanks.

**Comment by kbhargavi33** [comment]
@pjpratik I am able to replicate this with latest version as well.
org.tensorflow:tensorflow-lite:2.12.0

**Comment by kbhargavi33** [comment]
This is also happening with the code from docs https://www.tensorflow.org/lite/android/delegates/nnapi
Able to replicate in android 5,6,7 bunch of devices

I think this is an issue with interpreter rather nnapi

```
Interpreter.Options options = (new Interpreter.Options());
NnApiDelegate nnApiDelegate = null;
// Initialize interpreter with NNAPI delegate for Android Pie or above
if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
    nnApiDelegate = new NnApiDelegate();
    options.addDelegate(nnApiDelegate);
}
```

**Comment by pkgoogle** [comment]
Hi @kbhargavi33, I was able to run the code from the docs that you posted above fine. I do have this in my gradle instead though:

```kotlin
dependencies {

    ...
    implementation 'org.tensorflow:tensorflow-lite:2.0.0'
    ...
}
```

Can you try with that in a fresh project, then sync, and let me know if that works at all for you as well?

**Comment by kbhargavi33** [comment]
Hi @pkgoogle It is working with 2.0.0 and 2.10.0 as well.

```groovy
    implementation 'org.tensorflow:tensorflow-lite:2.10.0'
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.10.0'
    implementation 'org.tensorflow:tensorflow-lite-support:0.4.3'
    implementation 'org.tensorflow:tensorflow-lite-metadata:0.4.3'
``` 

But still not working with 0.0.0-nightly-SNAPSHOT and 2.1.12

**Comment by pkgoogle** [comment]
Hi @kbhargavi33, stability of the nightly snapshot is not necessarily guaranteed and it seems like a later version (with more bug fixes) is working for you. Is there any reason you can't use the later version for now?

**Comment by nijat-ahmadli** [comment]
I am still getting this issue with the latest release 2.14.0 for Android API levels 21-25 included. Can you please investigate this?

```
java.lang.UnsatisfiedLinkError: Failed to load native TensorFlow Lite methods. Check that the correct native libraries are present, and, if using a custom native library, have been properly loaded via System.loadLibrary():
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "strtod_l" referenced by "/data/app/com.onfido.android.sdk.capture.test-1/lib/arm64/libtensorflowlite_jni.so"...
at org.tensorflow.lite.TensorFlowLite.init(TensorFlowLite.java:137)
```

**Comment by pkgoogle** [comment]
Hi @nijat-ahmadli,

Are you trying to use the NNAPI delegate? It is only supported from Android API level 27+: https://www.tensorflow.org/lite/android/delegates/nnapi#trying_the_nnapi_delegate_on_your_own_model

**Comment by nijat-ahmadli** [comment]
Hi @pkgoogle Thanks for you reply!

No, I am not using any delegate. This is how I initialise the Interpreter:

```
init {
        val model = FileUtil.loadMappedFile(context, modelFileName)
        val options = Interpreter.Options()
        options.numThreads = CPU_NUM_THREADS
        interpreter = Interpreter(model, options)
}

Please note that, I am not getting the error with the release 2.11.0. It only occurs for the newer releases above this version.

**Comment by pkgoogle** [comment]
Hi @nijat-ahmadli, this original case originated from a different code/situation, can you please write a new issue that contains your reproducible code as well as system/environment information that conforms to the issue templates? Thanks for your help.

**Comment by nijat-ahmadli** [comment]
@pkgoogle [Issue](https://github.com/tensorflow/tensorflow/issues/62173) is created as requested. Thanks!
