### ISSUE TITLE
The relationship between the parameters of Conv2D is unclear

### ISSUE THREAD

**Issue by PhyllisJi** [tensorflow/tensorflow#61090]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf2.12.0

### Custom Code

Yes

### OS Platform and Distribution

MacOs

### Python version

3.9

### Current Behaviour?

```
ValueError: `strides > 1` not supported in conjunction with `dilation_rate > 1`. Received: strides=[2, 2] and dilation_rate=[4, 5]
```

The relationship between these two parameters is not clearly defined in the documentation, and it is not certain. Be unaware of that  `strides > 1` not supported in conjunction with `dilation_rate > 1`.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.python.keras.layers import Conv2D

input_tensor = tf.random.normal(shape=(1, 32, 32, 3))

x = Conv2D(filters=2, kernel_size=(1,1), strides=(2,2), padding="same", use_bias=False, dilation_rate=(4, 5))(input_tensor)

print(x.shape)
```

### Relevant log output

_No response_</details>

**Comment by SuryanarayanaY** [comment]
Hi @PhyllisJi ,

Thanks for reaching us. The documentation of [tf.keras.layers.Conv2D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D) for the argument `strides` as below:


> 
> strides | An integer or tuple/list of 2 integers, specifying the strides of the convolution along the height and width. Can be a single integer to specify the same value for all spatial dimensions. Specifying any stride value != 1 is incompatible with specifying any dilation_rate value != 1.
> -- | --
> 

Similarly for the argument `dilation_rate` the desrciption is as below.



> dilation_rate | an integer or tuple/list of 2 integers, specifying the dilation rate to use for dilated convolution. Can be a single integer to specify the same value for all spatial dimensions. Currently, specifying any dilation_rate value != 1 is incompatible with specifying any stride value != 1.
> -- | --
> 

Both the argument description states that when `strides != 1` then `dilation_rate` should be `1` . Also if dilation_rate !=1 then strides should be `strides=1`. There is interdependency in between these two arguments. The documentation seems little tricky here to understand but it is documented already.

I am attaching a [gist](https://colab.research.google.com/gist/SuryanarayanaY/c1f9b91a6ff6eea4e2429ff01d6fae52/61090.ipynb) for the demo also. Hope this will clarify.

Thanks!

**Comment by PhyllisJi** [comment]
> Hi @PhyllisJi ,
> 
> Thanks for reaching us. The documentation of [tf.keras.layers.Conv2D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D) for the argument `strides` as below:
> 
> > strides
> > An integer or tuple/list of 2 integers, specifying the strides of the convolution along the height and width. Can be a single integer to specify the same value for all spatial dimensions. Specifying any stride value != 1 is incompatible with specifying any dilation_rate value != 1.
> 
> Similarly for the argument `dilation_rate` the desrciption is as below.
> 
> > dilation_rate
> > an integer or tuple/list of 2 integers, specifying the dilation rate to use for dilated convolution. Can be a single integer to specify the same value for all spatial dimensions. Currently, specifying any dilation_rate value != 1 is incompatible with specifying any stride value != 1.
> 
> Both the argument description states that when `strides != 1` then `dilation_rate` should be `1` . Also if dilation_rate !=1 then strides should be `strides=1`. There is interdependency in between these two arguments. The documentation seems little tricky here to understand but it is documented already.
> 
> I am attaching a [gist](https://colab.research.google.com/gist/SuryanarayanaY/c1f9b91a6ff6eea4e2429ff01d6fae52/61090.ipynb) for the demo also. Hope this will clarify.
> 
> Thanks!

Thank you for your answers！

**Comment by SuryanarayanaY** [comment]
@PhyllisJi ,

Thanks for confirmation. Can we mark this as resolved now? Please feel free to close the issue if resolved.

Thanks
