### ISSUE TITLE
A time saving mode to extract the MNIST data

### ISSUE THREAD

**Issue by jskDr** [tensorflow/tensorflow#611]
[tensorflow/tensorflow/examples/tutorials/mnist]
Since now it takes time to extract gz files even if they are already download on a local machine, why don't we consider an additional mode which saves extract data as binary data? 

I submitted the update code of input_data.py and the update first line in run_training(), which is
data_sets = input_data.read_data_sets(FLAGS.train_dir, FLAGS.fake_data, fastload = True)

Any opinion?

(James) Sung-Jin Kim
sungjinkim@fas.harvard.edu

**Comment by jskDr** [comment]
Sorry for my sudden proposal. Actually, I am talking about how to improve compatibility with Python and its existing libraries such as Sklearn, Pandas and Pylab family (Numpy/Scipy/Matplotlib). I agree that the recent version of tensorflow python wrapping is so much great. However, if it becomes more compatible with recent machine learning and data processing tools in Python, the solution becomes more familiar with current python users including me. So, the addition of pickle mode in input_data.py is made based on this ideology. 

Moreover, I am wondering where my contribution is gone. I updated input_data.py here and submitted it a few days ago but I couldn't find it. Please advice me if there is any mistake I made in code contribution. 

(James) Sung-Jin Kim
sungjinkim@fas.harvard.edu

**Comment by girving** [comment]
Looks like this fell through the cracks.  When you say you submitted a contribution, did you make a PR?  There doesn't seem to be any programmatic mention of a contribution here.

**Comment by girving** [comment]
@jskDr: Closing for now due to lack of response, but please open if you still have a contribution!
