### ISSUE TITLE
Tensorflow Lite for Windows and macOS

### ISSUE THREAD

**Issue by ph1oneX** [tensorflow/tensorflow#61118]
Hi guys,
So i am new to On Device Machine Learning which is super cool but, the limitation with tf-lite is that i can only use in Android or iOS not in Windows Apps nor MacOS.
I request any of you who has dealt with embedding tfLite with Desktop class Apps to provide a simple solution.

**Comment by ph1oneX** [comment]
@SuryanarayanaY the source you attached will it work for python as it shows for C.
Also for Apple silicon which is the architecture target since its not mentioned. The only mentioned is for Linux or Raspberry Pi on ARM. However thank you for help

**Comment by SuryanarayanaY** [comment]
@pjpratik , please have a look into the issue, Thanks

**Comment by pjpratik** [comment]
Hi @ph1oneX 

As @SuryanarayanaY mentioned, the TFLite is a mobile library designed for deploying models on mobile, microcontrollers and other edge devices.

However the TFLite models can be still integrated using multiple programming languages as given [here](https://www.tensorflow.org/lite/guide/inference#supported_platforms)

Thanks.
