### ISSUE TITLE
` #include "include/float8.h"  // from @ml_dtypes` is missing

### ISSUE THREAD

**Issue by JanuszL** [tensorflow/tensorflow#61121]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.14.0

### Custom Code

Yes

### OS Platform and Distribution

docker/tensorflow/tensorflow:nightly-gpu

### Mobile device

No

### Python version

3.8

### Bazel version

NA

### GCC/Compiler version

NR

### CUDA/cuDNN version

NR

### GPU model and memory

NR

### Current Behaviour?

create a test.cc:
```
#include "tensorflow/core/framework/op.h"
```
compile it with flags provided by TensorFlow:
get_compile_flags():
```-I/usr/local/lib/python3.8/dist-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1 --std=c++17 -DEIGEN_MAX_ALIGN_BYTES=64```
get_link_flags():
```-L/usr/local/lib/python3.8/dist-packages/tensorflow -l:libtensorflow_framework.so.2```

```g++ -Wl,-R,'$ORIGIN/..' -Wl,-rpath,'$ORIGIN' --std=c++17 -DNDEBUG -shared  test.cc -o /tmp/test.so -fPIC -I/usr/local/lib/python3.8/dist-packages/tensorflow/include -D_GLIBCXX_USE_CXX11_ABI=1 --std=c++17 -DEIGEN_MAX_ALIGN_BYTES=64 -I/usr/include -I/usr/local/cuda/include -L/usr/local/lib/python3.8/dist-packages/tensorflow -l:libtensorflow_framework.so.2  -O2```

The result is:
```
      In file included from /usr/local/lib/python3.8/dist-packages/tensorflow/include/tensorflow/tsl/platform/types.h:22,
                       from /usr/local/lib/python3.8/dist-packages/tensorflow/include/tensorflow/tsl/framework/numeric_types.h:22,
                       from /usr/local/lib/python3.8/dist-packages/tensorflow/include/tensorflow/core/framework/numeric_types.h:24,
                       from /usr/local/lib/python3.8/dist-packages/tensorflow/include/tensorflow/core/framework/bfloat16.h:19,
                       from /usr/local/lib/python3.8/dist-packages/tensorflow/include/tensorflow/core/framework/types.h:24,
                       from /usr/local/lib/python3.8/dist-packages/tensorflow/include/tensorflow/core/framework/op_def_builder.h:28,
                       from /usr/local/lib/python3.8/dist-packages/tensorflow/include/tensorflow/core/framework/full_type_inference_util.h:24,
                       from /usr/local/lib/python3.8/dist-packages/tensorflow/include/tensorflow/core/framework/op.h:27,
                       from /tmp/pip-req-build-88874pcq/daliop.cc:19:
      /usr/local/lib/python3.8/dist-packages/tensorflow/include/tensorflow/tsl/platform/float8.h:19:10: fatal error: include/float8.h: No such file or directory
         19 | #include "include/float8.h"  // from @ml_dtypes
```
It is probably caused by [this PR](https://github.com/tensorflow/tensorflow/commit/ef1ea4f5c5c36209b6bd56a99fdd71e5052f6d63).

Either tensorflow/tsl/platform/float8.h should have `#include "external/ml_dtypes/include/float8.h"  // from @ml_dtypes`, or `get_compile_flags()` should include `-I/usr/local/lib/python3.8/dist-packages/tensorflow/include/external/ml_dtypes`

### Standalone code to reproduce the issue

```shell
As above
```

### Relevant log output

```shell
As above
```
</details>

**Comment by JanuszL** [comment]
It seems to work again with the latest nightly.

**Comment by sachinprasadhs** [comment]
Hi, Thanks for conforming that it works with Nightly version, feel free to close the issue if it is resolved.

For the latest Nightly and Stable Tensorflow docker versions, please refer the page here https://hub.docker.com/r/tensorflow/tensorflow/tags
