### ISSUE TITLE
Python 3.7.0 is incompitable with tensorflow 2.11.0 

### ISSUE THREAD

**Issue by TrojanPoem** [tensorflow/tensorflow#61181]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.11.0

### Custom code

Yes

### OS platform and distribution

Windows 10 Educion

### Python version

3.7.0

### Current behavior?

![image](https://github.com/tensorflow/tensorflow/assets/7984605/ad719afa-c5bf-4d3d-ba06-5f73d914785f)
Python 3.7.0 throws an exception that it cannot import OrderedDict from typings. The fix was downgrading from tensorflow 2.11.0 to tensorflow 2.10.0. 

- Orderd Dict is supported starting from python 3.7.2: https://docs.python.org/3.7/library/typing.html#typing.OrderedDict
- By default pip installs 2.11.0 for python 3.7.0 which is not supported
- The doc  states that 3.7.0 is supported: https://www.tensorflow.org/install/source#tested_build_configurations

### Standalone code to reproduce the issue

```shell
1) Install python 3.7.0
2) pip install tensorflow==2.11.0
3) inside python shell type: import tensorflow as tf
4) Exception will rise
```

**Comment by tilakrayal** [comment]
@TrojanPoem,
I request you to take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/60176) where a similar feature has been proposed and it is still open. Also I request to follow the similar feature which has been proposed to have the updates on the similar issue. Thank you!

**Comment by Petros626** [comment]
You need python 3.8-3.11. Please close this issue
