### ISSUE TITLE
TensorFlow-MKL: How to enable oneddn in tensorflow for eltwise op

### ISSUE THREAD

**Issue by akote123** [tensorflow/tensorflow#61198]
@penpornk , I have gone through the https://github.com/tensorflow/community/blob/master/rfcs/20210930-enable-onednn-ops.md . So I wanted to understand the latest tensorflow supports eltwise onednn flow and also is there any document which I can refer for the onednn ops which are supported in latest tensorflow.

**Comment by Petros626** [comment]
You opened there and here an issue but it belongs to `tensorflow/community`. Please decide either or
