### ISSUE TITLE
Issue with Reproducible Results: Inconsistent Behavior of Random Seeds in TensorFlow

### ISSUE THREAD

**Issue by soran-ghaderi** [tensorflow/tensorflow#61201]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.12

### Custom code

Yes

### OS platform and distribution

Ubuntu 22.04

### Python version

3.8-3.9-3.10

### Current behavior?

I would like to report an issue regarding the reproducibility of results in TensorFlow. Currently, in order to achieve consistent and deterministic results, it seems necessary to set both random.seed(42) and tf.random.set_seed(1) together.

Expected Behavior:
Setting tf.random.set_seed(1) alone should be sufficient to ensure reproducible results across different runs.

Observed Behavior:
Without setting random.seed(42) alongside tf.random.set_seed(1), the results obtained from TensorFlow exhibit inconsistency and do not remain fixed between runs.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import random

tf.random.set_seed(1)
random.seed(42) # This line seems to be redundant

x = tf.constant(tf.random.uniform([2, 3, 2]), dtype=tf.float32)
```

**Comment by soran-ghaderi** [comment]
Thank you @tilakrayal, I labeled this issue a bug as deterministic behavior is expected when calling tf.random.set_seed and is more logical to be the default.

**Comment by sachinprasadhs** [comment]
I was able to get the consistent output with only `tf.random.set_seed(1)` using `tf-nightly`, tested with multiple runs.

```
import tensorflow as tf
print(tf.__version__)
import random

tf.random.set_seed(1)
# random.seed(42) # This line seems to be redundant

x = tf.constant(tf.random.uniform([2, 3, 2]), dtype=tf.float32)
print(x)
```

Could you please test with the nightly version and let us know if you still observe the same behavior.
