### ISSUE TITLE
Error needed when loading a GraphDef created in a newer version of TensorFlow

### ISSUE THREAD

**Issue by petewarden** [tensorflow/tensorflow#6120]
There are a lot of issues (e.g. #5628) that are caused by users loading GraphDefs that were created by a newer version of TensorFlow (e.g. 0.12 that introduces SaverV2) into older code bases. This currently results in cryptic errors late in the loading process, but instead we should raise an error (or at least a prominent warning) when a newer GraphDef version than is supported is loaded.

**Comment by jart** [comment]
I'm surprised load_graph_def doesn't check the version information, which is already present in the GraphDef proto. It seems like a simple check to add. I'm assigning to @girving since he was the one who added the version field to the proto.

**Comment by girving** [comment]
@petewarden I'm not sure I understand.  An old version of TensorFlow can't know which future GraphDef versions it will be compatible with, since those new versions are created in the future.  What kind of error message would you like?

**Comment by petewarden** [comment]
It would be "This GraphDef was created with a newer version of TensorFlow, and can't be loaded". Since we don't support this, we should fail hard, clearly, and early, rather than ignoring the mismatch and hitting cryptic errors later in the process.

**Comment by girving** [comment]
@petewarden That's a good idea, but I don't see how one would check for that.  We do check if a GraphDef's `min_consumer` version is too high, but this usually isn't the case.  We absolutely want TensorFlow to be able to load a GraphDef with a future version if it doesn't use any of the features introduced by that future version.  Since we have no idea what those future features are, the only kinds of errors we can produce are about unimplemented features.

**Comment by petewarden** [comment]
> We absolutely want TensorFlow to be able to load a GraphDef with a future version if it doesn't use any of the features introduced by that future version.

I'm surprised by this. I'm either used to the case where we guarantee forwards compatibility (so GraphDefs created by future versions will load and run correctly in older versions) or we don't. What we seem to have is no guarantee of forwards compatibility, but also no error that we're in that "no guarantee this will load" situation. Anyway, I'll come and talk in person to understand more.

**Comment by girving** [comment]
@petewarden Is it still worth having a chat about this?

**Comment by petewarden** [comment]
@girving thanks, let's see if we can have a quick chat today!

**Comment by girving** [comment]
Proposal: we add a `string tf_version` to [`VersionDef`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/versions.proto#L22), and use it to hint when op kernels are missing.

@josh11b Thoughts or objections?

**Comment by petewarden** [comment]
I chatted with @girving offline, and we came to the conclusion that it would be useful to have an advisory producer source code version (for example 1.2) stored in the graphdef. This would only be used for creating better error messages in the case that there's an unrecognized op found, or one of the other similar errors.

**Comment by yifeif** [comment]
Do we still plan to this, @petewarden @girving?

**Comment by girving** [comment]
@yifeif I'm unlikely to get to this before I vanish.

**Comment by yifeif** [comment]
I see. I'm closing this for now. @petewarden feel free to re-open if we plan to precede on this.

**Comment by hodaraad** [comment]
According to [this](https://www.tensorflow.org/programmers_guide/version_compat) TF document, graphs produced on later version of TF can be consumed on earlier version of TF if min_consumer_version and min_producer_version params set correctly. I found how to set min_consumer_version and producer_version using GraphDef.versions field, but could not figure out how to set min_producer_version or consumer_version ([Here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/versions.proto) says these fields should be defined somewhere else, but where?). And without that I get "Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary" error

**Comment by dannyjeck** [comment]
Please reopen this issue. There are new ops in newer versions of tensorflow that make it impossible to load graphs generated in newer versions using older ones. For example the `NonMaxSuppressionV3` op got added some time between 1.8 and 1.10.
