### ISSUE TITLE
Building TFLite for WASM using Bazel

### ISSUE THREAD

**Issue by L1onKing** [tensorflow/tensorflow#61200]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.13.0

### Custom code

Yes

### OS platform and distribution

Emscripten

### Bazel version

5.3.0

### Current behavior?

We are trying to compile TFLite libraries for WASM that we can use in our C++ project that later will be compiled to WASM package as well. We have forked a Tensorflow repository and did these modifications for Bazel + WASM - https://github.com/af-filby/tensorflow/commit/2defd39b957a73828b4791e48883e874a97b4bb4 and we try to build with this command:

`bazel build --config=wasm -c opt //tensorflow/lite:tensorflowlite`

The building process went smooth and we as an output we got `libtensorflowlite2.so` which I think is expected. BUT, the problem is that this `.so` file is only `50 KB` in size, and if we try to link it in our CMake we get an error `Unable to find library -ltensorflowlite2`

Could you please review our Bazel config and advise what we did wrong so we can finish this compilation successfully?

### Standalone code to reproduce the issue

```shell
No need for this field
```

**Comment by pkgoogle** [comment]
Hi @terryheo, can you please take a look?

**Comment by pkgoogle** [comment]
Hi @L1onKing, So I tried your bazel command, and as far as I can tell I don't believe building for WASM is not a valid config. I am unaware of any documentation that says it is supported and I get this error:

```sh
bazel build --config=wasm -c opt //tensorflow/lite:tensorflowlite
Starting local Bazel server and connecting to it...
ERROR: Config value 'wasm' is not defined in any .rc file
```

This is the closest thing I can find: https://js.tensorflow.org/api_tflite/0.0.1-alpha.8/, are you following any resource which provided this command?

**Comment by AlexanderLutsenko** [comment]
Hello, @L1onKing ! Did you manage to solve the problem? I'm trying to do the exact same thing, to no avail so far. Looks like the build recipe that worked a couple years ago doesn't work anymore.
