### ISSUE TITLE
Convert tf.Tensor into tensorflow::Tensor

### ISSUE THREAD

**Issue by zhumakhan** [tensorflow/tensorflow#61214]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.13

### Custom code

Yes

### OS platform and distribution

Ubuntu 20

### Python version

3.8

### CUDA/cuDNN version

11.2

### Current behavior?

Is there any way to convert tf.Tensor from python into tensorflow::Tensor C++?

### Standalone code to reproduce the issue

```shell
Actually using pybind11. I can get PyObject* from tf.Tensor and have no idea how to get tensorflow::Tensor* from PyObject*
```

**Comment by masterismail** [comment]
Hey @SuryanarayanaY . you working on this ?

**Comment by SuryanarayanaY** [comment]
Hi @zhumakhan ,

Tensorflow provides C_API that can be used to build [bindings for other languages](https://github.com/tensorflow/docs/tree/master/site/en/r1/guide/extend/bindings.md) which is defined in [c_api.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h).

Please refer the above sources and let us know if it helps. Thanks!

**Comment by zhumakhan** [comment]
Thanks for your suggestion, will check that and let you know!

**Comment by SuryanarayanaY** [comment]
Hi @zhumakhan ,

Could you please try converting a tf.tensor into serialized TensorProto prototype by using [tf.io.serialize_tensor](https://www.tensorflow.org/api_docs/python/tf/io/serialize_tensor) API, and then using tensorflow::ops::[ParseTensor](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/parse-tensor) parse the serialized TensorProto back to tf:Tensor.

Please try this and let us know if this doesn't work. Thanks!
