### ISSUE TITLE
ctc_ops.py deprecation warning

### ISSUE THREAD

**Issue by sronen71** [tensorflow/tensorflow#61228]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.13

### Custom code

Yes

### Current behavior?

WARNING:tensorflow:From /home/sronen/code/.venv/lib/python3.10/site-packages/tensorflow/python/ops/ctc_ops.py:1514: alias_inplace_add (from tensorflow.python.ops.inplace_ops) is deprecated and will be removed in a future version.

### Standalone code to reproduce the issue

```shell
I suspect any call to tf.nn.ctc_loss
```

**Comment by SuryanarayanaY** [comment]
Hi @sronen71 ,

Thanks for your time reporting this issue. The warning is actually related Tensorflow internal functions which is getting generated from the code below.This is not 

https://github.com/tensorflow/tensorflow/blob/8e2b6655c0c488290179ab90a0daed0f6d3006f7/tensorflow/python/ops/inplace_ops.py#L89-L93

As you see the warning is intended as its common that there will be some internal changes happens in source code.This will be taken care by the TF team and users need not do any changes here.

Thanks!
