### ISSUE TITLE
tf.image.adjust_gamma outputs incorrect error message for string input

### ISSUE THREAD

**Issue by drewshark** [tensorflow/tensorflow#61220]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.12.0

### Custom code

Yes

### Current behavior?

When giving tf.image.adjust_gamma a string inputs, it outputs misleading error messages:
```
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
t = tf.constant([], dtype=tf.string)
i = tf.image.adjust_gamma(t, gamma=0.1)
```
```


### Relevant log output

_No response_

**Comment by tilakrayal** [comment]
@drewshark,
I tried to execute the mentioned code on tensorflow v2.13, where it was executed with the error stating that `AttributeError: image dtype must be either floating point or integer` which was clearly mentioning to the user that the dtype should be either floating or interger. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/2caebf81876962bd026cc0dbbaf32cb4/untitled1233.ipynb). Thank you!

**Comment by drewshark** [comment]
Thanks for your response, I tried it on tf1.12.0. It seems that this issue has been fixed.
