### ISSUE TITLE
TensorFlow GPU

### ISSUE THREAD

**Issue by KnSun99** [tensorflow/tensorflow#61225]
New versions of TensorFlow no longer support Windows native Gpus.

If built in WSL2

Is there a shortcut to read data from Windows directory in WSL2?

Because I need to use TensorFlow GPU to compute a lot of data.
Copying to WSL2 is slow

**Comment by SuryanarayanaY** [comment]
Hi @KnSun99 ,

Thanks for reaching us. Trying to access Windows files from WSL might be considerably slower than using the native Linux file system.

Windows drives are mounted in the Linux at `/mnt/` directory. You can prefix /mnt/ to your local directory to access then in WSL. For example, your personal Users folder at `C:\Users\<yourname>` is available at: `/mnt/c/Users/<yourname>`.

For more details you may refer the attached external sources from here [source1](https://www.sitepoint.com/wsl2/) and [source2](https://ling123labs.com/posts/WSL-files-in-Windows-and-vice-versa/#:~:text=Accessing%20your%20Windows%20files%20in%20the%20WSL%20terminal&text=Just%20use%20the%20cd%20command,to%20access%20my%20Documents%20folder.).

Please let us know if it helps. Thanks!

**Comment by KnSun99** [comment]
Thank you for the response! Will there be future versions that support Windows native GPU?

**Comment by SuryanarayanaY** [comment]
@KnSun99 ,

Due to performance issues Windows native GPU support has been dropped. I doubt whether support for windows native GPU will bring back in near future.

**Comment by KnSun99** [comment]
Thanks for your reply!

**Comment by SuryanarayanaY** [comment]
@KnSun99 ,

Please let us know if the issue is resolved for you. Please feel free to close if resolved.Let us know if you get any further issue. Thanks!

**Comment by KnSun99** [comment]
OK
