### ISSUE TITLE
Tensor shapes is different when loading from tf.lite.Interpreter and from flatbuffer from python

### ISSUE THREAD

**Issue by Bajirak** [tensorflow/tensorflow#61227]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- TensorFlow installation (pip package or built from source): pip package, python3.8
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.13.0

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

`# Download tflite model from https://tfhub.dev/google/imagenet/mobilenet_v3_large_075_224/classification/5

# Case-1 Load tflite from Interpreter
import tensorflow as tf
model_path = "lite-model_imagenet_mobilenet_v3_large_075_224_classification_5_default_1.tflite"
interpreter = tf.lite.Interpreter(model_path=model_path)
interpreter.allocate_tensors()

tensor_details = interpreter.get_tensor_details()
print("Read Tensor Shapes From Interpreter Module")
print(tensor_details[140]['name'])
print(tensor_details[140]['shape'])

# Case-2 Load tflite from flatbuffer
from tensorflow.lite.tools.flatbuffer_utils import read_model

model = read_model(model_path)
tensor = model.subgraphs[0].tensors[140]
print("Read Tensor Shapes From Flatbuffer Module")
print(tensor.name)
print(tensor.shape)
`

### 3. Failure after conversion
If the conversion is successful, but the generated model is wrong, then state what is wrong:

It prints the different shapes.

`Read Tensor Shapes From Interpreter Module
predict/MobilenetV3/expanded_conv/add
[  1 112 112  16]
Read Tensor Shapes From Flatbuffer Module
b'predict/MobilenetV3/expanded_conv/add'
[ 1  1  1 16]
`

### 5. (optional) Any other info / logs

I thought it was a problem caused by the schema_generate.py file not being updated. So I tried recompiling schema.fbs, but still the problem was not solved.

**Comment by pjpratik** [comment]
Hi @Bajirak 

If your model has dynamic input shapes and you didn't specify a dimension size when building and converting your model, the converter will use 1 as the default dimension size. 

From TFLite [Model Analyzer](https://www.tensorflow.org/lite/guide/model_analyzer) I can see that 

`T#140(predict/MobilenetV3/expanded_conv/add) shape_signature:[-1, -1, -1, 16], type:FLOAT32`

The dimensions labeled with -1, these dimensions are the dimensions that are dynamic and can be resized.
That means that the model you are converting has shape [1, None, None, 3] and you can resize the 'None' dimensions at runtime.

The interpreter uses the static shape which starts with [1, 224,224,3] and get the shape of [1,112,112,3] in the process at that node.

Please find the gist [here](https://colab.research.google.com/gist/pjpratik/604ab3d2ae70e8317fc57fd164063907/61227.ipynb).

Thanks.

**Comment by Bajirak** [comment]
@pjpratik 
I appreciate you responding. so quickly to my question. :)

I'm not familiar with tensorflow, but could you tell me where the guide document you explained is located?
I mean, 
is there any documentation on how to fix the input size of a tflite model?

**Comment by pjpratik** [comment]
Hi @Bajirak 

Please refer to this [documentation](https://www.tensorflow.org/lite/guide/inference.md#run_inference_with_dynamic_shape_model) related to dynamic input tensors. Regarding fixing the input size, we need to provide the batch and input size while model building.

For ex:
```
img = tf.keras.Input(shape=(64, 64, 3), name="img")
const = tf.constant([1., 2., 3.]) + tf.constant([1., 4., 4.])
val = img + const
out = tf.identity(val, name="out")

# Convert to TF Lite format
converter = tf.lite.TFLiteConverter.from_keras_model(tf.keras.models.Model(inputs=[img], outputs=[out]))
tflite_model = converter.convert()
```
Please find the [gist](https://colab.research.google.com/gist/pjpratik/56ea53502a5396f8dcec8c9011fc769e/61227.ipynb) for the same.

Feel free to close the issue if it is resolved.

Thanks.

**Comment by Bajirak** [comment]
@pjpratik 
Thanks to you, all my doubts related to this have been resolved. thank you
