### ISSUE TITLE
Support for empty GPU batches during distributed training

### ISSUE THREAD

**Issue by ujjwal-researcher** [tensorflow/tensorflow#61231]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.12.0

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Python version

3.9

### Current behavior?

When doing `distributed training` using `MirroredStrategy`, one may encounter empty GPU batches when `drop_remainder=False` during dataset construction.

From #44348 , it seems it is a long-standing issue. 

For the last few batches of data it is possible that some replica workers receive an empty tensor as input ( see [here](https://www.tensorflow.org/tutorials/distribute/input#batching) for an example !!! ). 

Either one must set `drop_remainder=True` or consider not using `@tf.function` because you would have to add a conditional statement in the `train_step` function which won't work with `tf.function`. 

So, from the point of efficiency, `drop_remainder=True` seems the only option. In some applications or critical experiments, one would not like to drop the remainder data  for very precise and reproducible quantitative analysis.

So, can there be a support for handling empty GPU batches in distributed mode ?

### Standalone code to reproduce the issue

```shell
`tf.data.Dataset.range(8).batch(4)` over 3 replicas, results in the following output:

Batch 1:

    Replica 1: [0, 1]
    Replica 2: [2, 3]
    Replica 3: []

Batch 2:

    Replica 1: [4, 5]
    Replica 2: [6, 7]
    Replica 3: []

Without `drop_remainder=True`  this will cause an incompatible shape error when doing a forward pass.
```

**Comment by tilakrayal** [comment]
@ujjwal-researcher,
Could you please provide the complete code to reproduce the issue and it helps us to analyse the issue in an effective way. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/846ef0c0c96c968add15f82cd8ed2e0d/untitled1235.ipynb). Thank you!
