### ISSUE TITLE
The legal value range of the alpha parameter in LeakyReLU

### ISSUE THREAD

**Issue by PhyllisJi** [tensorflow/tensorflow#61257]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf2.12.0

### Custom code

Yes

### OS platform and distribution

MacOs

### Python version

3.9

### Current behavior?

The document describes the LeakyReLU function as having an alpha parameter whose type is a floating point number and the value is equal to or greater than 0. But we found that the value of this parameter is less than zero can also work.

#### Document

| `alpha` | Float >= `0.`. Negative slope coefficient. Defaults to `0.3`. |
| ------- | ------------------------------------------------------------ |

### Standalone code to reproduce the issue

```shell
from tensorflow import keras


def bilstm(num_units=25, input_shape=10):
# bilstm input layer
    input_tensor = keras.Input(shape=input_shape)
# bilstm hidden layer
    x = keras.layers.Embedding(input_dim=100, output_dim=10, input_length=8, embeddings_initializer="uniform")(input_tensor)
    x = keras.layers.LeakyReLU(alpha=-0.2044550861511304)(x)
# bilstm output layer
    output_tensor = x
    model = keras.models.Model(inputs=input_tensor, outputs=output_tensor)
    return model


if __name__ == "__main__":
    bilstm().summary()
```

### Relevant log output

```shell
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 input_1 (InputLayer)        [(None, 10)]              0         
                                                                 
 embedding (Embedding)       (None, 10, 10)            1000      
                                                                 
 leaky_re_lu (LeakyReLU)     (None, 10, 10)            0         
                                                                 
=================================================================
Total params: 1,000
Trainable params: 1,000
Non-trainable params: 0
```
```

**Comment by SuryanarayanaY** [comment]
@PhyllisJi ,

Thanks for reporting.I have tested a simple code with `alpha = -0.3` and `alpha = 0.3` just to check and both are generating output which are different as per attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/d999601062b0a57d5d8d1c014435c3d6/61257.ipynb). The source code is missing validation for  values of `alpha < 0` .

@adey4 , Could you please confirm whether you are interested to raise a PR for same on Keras repo ? The keras source code can be found [here](https://github.com/keras-team/keras/blob/master/keras/layers/activation/leaky_relu.py). If not I can raise a PR for this. 

Thanks!

**Comment by SuryanarayanaY** [comment]
Reopening as PR not approved in TF repo. Created a new PR in Keras repo

**Comment by SuryanarayanaY** [comment]
Reference PR-[18336](https://github.com/keras-team/keras/pull/18336) in Keras repo

**Comment by oawxkw** [comment]
I also observed the following alternative names of the API have the same behavior that accepts the negative value of `alpha` without throwing an Exception.

- `tf.keras.layers.LeakyReLU`, `tf.compat.v1.keras.layers.LeakyReLU`

This behavior still exists in tensorflow nightly (2.15.0-dev20230906), and users should be cautious when using them on both CPU and GPU.

**Comment by SuryanarayanaY** [comment]
Hi @PhyllisJi ,

This is fixed in #[18678](https://github.com/keras-team/keras/pull/18678).

Could you please verify and close the issue. Thanks!
