### ISSUE TITLE
Documentation Bug about API ActivityRegularization

### ISSUE THREAD

**Issue by PhyllisJi** [tensorflow/tensorflow#61254]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf2.12.0

### Custom code

Yes

### OS platform and distribution

MacOs

### Python version

3.9

#### Document

| `l1` | L1 regularization factor (positive float). |
| ---- | ------------------------------------------ |
| `l2` | L2 regularization factor (positive float). |

The l1 and l2 parameters of the ActivityRegularization function are described in this document as floating point numbers and their values should be positive. But we found that they can run with values less than zero

### Standalone code to reproduce the issue

```shell
from tensorflow import keras


def gru(num_units=25, input_shape=10):
# gru input layer
    input_tensor = keras.Input(shape=input_shape)
# gru hidden layer
    x = keras.layers.Embedding(input_dim=100, output_dim=10, input_length=None)(input_tensor)
    x = keras.layers.GRU(units=32, dropout=0.7338014982069313, return_sequences=True)(x)
    x = keras.layers.ActivityRegularization(l1=-0.616784030867379, l2=-0.9646777799675004)(x)
# gru output layer
    output_tensor = keras.layers.Flatten()(keras.layers.Dense(units=num_units, activation="relu")(x))
    model = keras.models.Model(inputs=input_tensor, outputs=output_tensor)
    return model


if __name__ == "__main__":
    gru().summary()
```

### Relevant log output

```shell
Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 input_1 (InputLayer)        [(None, 10)]              0         
                                                                 
 embedding (Embedding)       (None, 10, 10)            1000      
                                                                 
 gru (GRU)                   (None, 10, 32)            4224      
                                                                 
 activity_regularization (Ac  (None, 10, 32)           0         
 tivityRegularization)                                           
                                                                 
 dense (Dense)               (None, 10, 25)            825       
                                                                 
 flatten (Flatten)           (None, 250)               0         
                                                                 
=================================================================
Total params: 6,049
Trainable params: 6,049
Non-trainable params: 0
```
```

**Comment by SuryanarayanaY** [comment]
Hi @PhyllisJi ,

Thanks for reporting.I have replicated the reported behaviour and attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/a140acaf103057f5627938cd1b92bba5/61254.ipynb) for reference.

The reason for this for l1 and l2 inputs validation part is missing.I may raise a PR to fix this after going in details.

**Comment by SuryanarayanaY** [comment]
A PR #[18293](https://github.com/keras-team/keras/pull/18293) in Keras repo has been raised which may probably fix this once merged. Thanks!

**Comment by SuryanarayanaY** [comment]
A new PR #[18688](https://github.com/keras-team/keras/pull/18688) has been proposed in Keras repo as previous PR ( mentioned above) got cancelled during migration process.
