### ISSUE TITLE
Undefined symbol libtensorflow_cc

### ISSUE THREAD

**Issue by sirvincent** [tensorflow/tensorflow#61252]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.13.0

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.8

### Bazel version

5.3.0

### GCC/compiler version

9.4.0

### Current behavior?

Bazel build of libtensorflow_cc & install_headers for C++ interface returns runtime error:  'undefined symbol: _ZTIN3tsl2io20InputStreamInterfaceE'.

The problem was not seen with 2.8.0 when the same steps are performed.

We link against the libtensorflow_cc.so* & libtensorflow_framework.so*.

### Standalone code to reproduce the issue

```shell
bazel build --config=monolithic --config=avx2_linux --config=opt //tensorflow:libtensorflow_cc.so //tensorflow:install_headers
```

**Comment by sushreebarsa** [comment]
@sirvincent Could you please confirm if you are using the [link1](https://www.tensorflow.org/install/lang_c), and [link2](https://github.com/tensorflow/tensorflow/blob/master/README.md) for installation. Please make sure to share the steps you followed in order to replicate the issue. Thank you!

**Comment by sirvincent** [comment]
@sushreebarsa if I am not mistaken those links show the build process for the C api not the C++ api?

**Comment by sushreebarsa** [comment]
@sirvincent Sorry for the misread! From TF v2.13, the tensorflow build uses clang instead of GCC. As per this [documentation](https://www.tensorflow.org/install/source#install_clang_recommended_linux_only), please refer to building it using clang 16.0 and let us know if it helps. Could you let us know the steps to follow for reproducing the error reported here as well. Thank you!

**Comment by sirvincent** [comment]
@sushreebarsa I have managed to solve my problem.

**Comment by sushreebarsa** [comment]
@sirvincent Glad your issue is resolved now. Thank you!
