### ISSUE TITLE
Error installing impoerting TF model into Node red

### ISSUE THREAD

**Issue by brandonlaerdal** [tensorflow/tensorflow#61274]
Hello, I am getting a tensor flow to install on my node red. It seems like there is and install issue and I keep on getting the error pictured below. I have also tried import an model from teachable machine too and I get the same error please help.
![Capture](https://github.com/tensorflow/tensorflow/assets/139502937/3df553e5-3715-4ffb-a89f-b6fe324c31e0)
![Capture1](https://github.com/tensorflow/tensorflow/assets/139502937/3e101d5f-29ca-4313-bbe6-8904a801443b)

**Comment by sachinprasadhs** [comment]
Hi, 

I don't we have any distributions done for Node Red and we don't provide any support outside of our releases published in our Github repo, https://pypi.org/project/tensorflow/.

From the `Node Red` document, I was able to find the way to Install Tensorflow using community build. 
For more details follow https://flows.nodered.org/node/node-red-contrib-tensorflow
