### ISSUE TITLE
TFlite running interpreter->invoke() has failed - Segmentation fault

### ISSUE THREAD

**Issue by HemiFate** [tensorflow/tensorflow#61271]
In TFLite, I wrote a custom delegate in C++ and encountered an error: "Segmentation fault". This error occurs after the initialization is complete and specifically after the invocation of interpreter->invoke(). The custom delegate's prepare function is executed, but the eva function is not executed.

**Comment by tilakrayal** [comment]
@HemiFate,
The delegate test failure is more or less expected, though it shouldn't seg fault. In your test, did you explicitly call **TfLiteInterpreterAllocateTensors** before checking the output tensor data? Thank you!
