### ISSUE TITLE
`tf.math.reduce_sum`'s `name` property doesn't change in `model.compile`

### ISSUE THREAD

**Issue by ubless607** [tensorflow/tensorflow#61284]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.13

### Custom code

No

### OS platform and distribution

Linux Ubuntu 18.04.6 LTS

### Python version

3.10

### Current behavior?

```
...
out = tf.math.reduce_sum(tf.cast(position> 0.5, tf.float32), axis=-1, keepdims=True, name='final')
model = models.Model(inputs=input_, outputs=[position, out])

model.summary()

=============================================================
...
tf.math.reduce_sum (TFOpLambda  (None, 1)           0           ['tf.cast[0][0]']                 )   
==============================================================
```

### Standalone code to reproduce the issue

```shell
input_ = layers.Input(shape=(3))
position = layers.Dense(5, 'sigmoid', name='position')(input_)
out = tf.math.reduce_sum(tf.cast(position> 0.5, tf.float32), axis=-1, keepdims=True, name='final')
model = models.Model(inputs=input_, outputs=[position, out])

model.summary()
```

**Comment by sushreebarsa** [comment]
@ubless607 
In order to expedite the trouble-shooting process, please provide the complete code snippet to reproduce the issue reported here. Please share all the dependencies here. Thank you!
