### ISSUE TITLE
`tf.image.decode_jpeg` can not decode jpeg base64 encoded image

### ISSUE THREAD

**Issue by GF-Huang** [tensorflow/tensorflow#61286]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.10.1

### Custom code

Yes

### OS platform and distribution

Win11 22H2

### Python version

3.10.11

### Current behavior?

It raise: `InvalidArgumentError: {{function_node __wrapped__DecodeJpeg_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unknown image file format. One of JPEG, PNG, GIF, BMP required. [Op:DecodeJpeg]`

![image](https://github.com/tensorflow/tensorflow/assets/4510984/342f8602-a2ba-48b7-bdaa-4d0684f9299f)

![image](https://github.com/tensorflow/tensorflow/assets/4510984/6177e9d3-90ed-42c8-881f-cc18bd045f39)

### Standalone code to reproduce the issue

```shell
import base64

from PIL import Image
import tensorflow as tf

img = Image.open('xxx.jpg')
base64str = base64.b64encode(img.tobytes()).decode()
tf.image.decode_jpeg(base64str, channels=3)
```

**Comment by sushreebarsa** [comment]
@GF-Huang 
Could you have a look at the below example of what decode jpeg function does in TensorFlow;
```

import tensorflow as tf
path_image = "/content/kitten.jpg"
image_open = open(path_image, 'rb')
read_image = image_open.read()
image_decode = tf.image.decode_jpeg(read_image)
image_decode
```
Though, I was able to replicate the issue using an image, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/97b758558e63cf3ff9e0b195dadac81e/61286.ipynb) here!
Thank you!

**Comment by GF-Huang** [comment]
My mistake, the `PIL.Image.tobytes()` is the internal bytes format.

**Comment by sushreebarsa** [comment]
@GF-Huang Glad it is working fine for you now. Thank you!
