### ISSUE TITLE
AttributeError: module 'tensorflow.saved_model' has no attribute 'builder'

### ISSUE THREAD

**Issue by GF-Huang** [tensorflow/tensorflow#61282]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

v2.10.0-76-gfdfc646704c 2.10.1

### Custom code

Yes

### OS platform and distribution

Win11 22H2

### Python version

3.10.11

### Current behavior?

The docs(https://www.tensorflow.org/tfx/serving/serving_basic#train_and_export_tensorflow_model) show me:

![image](https://github.com/tensorflow/tensorflow/assets/4510984/ace81d65-1ef4-4a27-955c-58a8b9a216b1)

But I can find it in my code:

![image](https://github.com/tensorflow/tensorflow/assets/4510984/91bc769d-36cc-4dfc-9f24-16b60c572b2c)

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
tf.saved_model.builder.SavedModelBuilder
```

**Comment by sushreebarsa** [comment]
@GF-Huang [Migrate the SavedModel workflow](https://www.tensorflow.org/guide/migrate/saved_model), will guide you to migrate TF1 saved model to TF2 compatible. Please have a look at this [link](https://www.tensorflow.org/guide/migrate/saved_model#tensorflow_1_load_a_savedmodel_with_tfsaved_modelload) to export the model from the saved model.
 Thank you!
