### ISSUE TITLE
Parse output of `mobile_ssd_v2_float_coco.tflite`

### ISSUE THREAD

**Issue by caiotoledo-lunasystems** [tensorflow/tensorflow#61299]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

v2.11.1

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 20.04

### Mobile device

Android

### Bazel version

6.2.0

### GCC/compiler version

12

### Current behavior?

I'm trying to use the model [mobile_ssd_v2_float_coco.tflite](https://storage.googleapis.com/download.tensorflow.org/models/tflite/gpu/mobile_ssd_v2_float_coco.tflite) on a C++ application, I'm able to execute the inference and get the results.

Based on the Netron app I see that its output is:
![image](https://github.com/tensorflow/tensorflow/assets/92656601/7ee73cb9-52dc-47ef-a89f-d17843bd0f60)

But I couldn't find an example code showing how to parse this output.

I tried to look into https://github.com/tensorflow/tensorflow/issues/29054 and https://github.com/tensorflow/tensorflow/issues/40298 but the output of the model is different from the one provided [here](https://storage.googleapis.com/download.tensorflow.org/models/tflite/gpu/mobile_ssd_v2_float_coco.tflite).

Do you have any example code available in Java, Python, or even better in C++ to parse this model output?

### Standalone code to reproduce the issue

```shell
No example code is available to parse the output of mobile_ssd_v2_float_coco.tflite.
```

**Comment by pjpratik** [comment]
Hi @caiotoledo-lunasystems 

The [TensorFlow Lite Object Detection](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android#tensorflow-lite-object-detection-android-demo) Demo example uses different models trained on COCO dataset. 

In the example, [TensorFlow Lite Task Library](https://www.tensorflow.org/lite/api_docs/python/tflite_support/task/vision) is used to parse the output which provides simple interface to use.

Please check the [post process](https://github.com/tensorflow/tflite-support/blob/51d72eb189660da222c477b960861c0d98bfa6fc/tensorflow_lite_support/cc/task/vision/object_detector.cc#L600) function for the reference which is used by library to parse the output. Also, please check the [demo example](https://github.com/tensorflow/tflite-support/tree/master/tensorflow_lite_support/examples/task/vision/desktop) for  C++ Vision Task APIs.

Thanks.

**Comment by caiotoledo-lunasystems** [comment]
@pjpratik,

Thanks for the support!
