### ISSUE TITLE
Model checkpoint to tflite model

### ISSUE THREAD

**Issue by MaheshwariAnkit** [tensorflow/tensorflow#61301]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- TensorFlow installation (pip package or built from source): built from source
- TensorFlow library (version, if pip package or github SHA, if built from source):2.12

I am using tflilte(c++) and doing on device training using signature runner and saving the model.ckpt file..

I want to convert model.ckpt to tflite model for inference..is there any possible method using c++??

**Comment by sushreebarsa** [comment]
@MaheshwariAnkit Once you have loaded your TensorFlow Lite model into memory, you can perform inference using the tflite::Interpreter::Invoke() method:
```
interpreter->Invoke();
```
Please have a look at [this](https://www.tensorflow.org/lite/guide/inference) guide to know more on TFlite inference.
Thank you!

**Comment by AkshayLS** [comment]
I also need some help on this.. i have tflite model and after retraining using signature runner i got model.ckpt.. now i want to merge model.ckpt and model.tflite file.. is there any available method for this? 

@sushreebarsa -> above link/guide does not having any information for similar problem.
