### ISSUE TITLE
tf.get_session_tensor awkwardness

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#6131]
`tf.get_session_tensor()` op constructor is unique in that it needs to be passed output of a session.run call. IE, when you are setting up your graph structure and don't have a relevant handle, you need to do something like this

```
dummy_handle = sess.run(tf.get_session_handle(tf.constant(1, dtype=dt)))
tensor_holder, tensor = tf.get_session_tensor(dummy_handle, dtype=dt)

```
This means that it's incompatible with workflow of "create graph -> finalize graph -> run ops" (like when using Supervisor which finalizes graph at the end of `init`). It seems the reason was to figure out which device the tensor would live on. Would it make sense to have it take device from the current graph context instead of a live tensor handle?

@yuanbyu @keveman

**Comment by yaroslavvb** [comment]
BTW, if this makes it into TF 1.0 it'll be forever the lone exception to "define-then-run" convention of TensorFlow. (ie, session ops need "define-run-define-runagain")

**Comment by girving** [comment]
Ultimate sadness.

**Comment by girving** [comment]
@yaroslavvb Is this possible to fix in a backwards compatible way by making it take a session directly?

**Comment by girving** [comment]
Unassigning Yuan since he's fled.

**Comment by yaroslavvb** [comment]
@girving it could be fixed in backward compatible way by adding back single argument version of `tf.get_session_tensor`, which was there before it was removed in 0.10   . I'll close this issue because there's a work-around by using dummy_handle, and fixing it now that it made into 1.0 API is probably too much work for what it's worth
