### ISSUE TITLE
How can I profile "Inference" by Profiler, and view performance profile by tensorboard

### ISSUE THREAD

**Issue by Pan17WJ** [tensorflow/tensorflow#61325]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.9.3

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.7

### Current behavior?

I want to profiling "Inference" by Profiler. 
However, the test of profiling training is success. But, when I try to profiling inference, the profiling log generated is empty and there are no active dashboards for the current data set.
How can I find the tutorial about analyzing the performance of inference?

### Standalone code to reproduce the issue

```shell
saved_model_loaded = tf.saved_model.load(FLAGS.weights, tags=[tag_constants.SERVING])
infer = saved_model_loaded.signatures['serving_default']
batch_data = tf.constant(images_data)
options = tf.profiler.experimental.ProfilerOptions(host_tracer_level = 3, python_tracer_level = 1, device_tracer_level = 1)
tf.profiler.experimental.start('logdir', options)
pred_bbox = infer(batch_data)
tf.profiler.experimental.stop()
```

**Comment by sushreebarsa** [comment]
@Pan17WJ Could you please have a look at this [doc](https://www.tensorflow.org/tfx/serving/tensorboard) on Tensor-board profiling and try with the latest TF version 2.13 ?Thank you!

**Comment by Pan17WJ** [comment]
It doesn't seem to work. It generates the following file. When I opens the browser http://localhost:6006 by tensorboard, the display is" No dashboards are active for the current data set. "

├── events.out.tfevents.1690428266.wj.profile-empty
└── plugins
    └── profile
        └── 2023_07_27_11_24_26
            ├── wj.input_pipeline.pb
            ├── wj.kernel_stats.pb
            ├── wj.memory_profile.json.gz
            ├── wj.overview_page.pb
            ├── wj.tensorflow_stats.pb
            ├── wj.trace.json.gz
            └── wj.xplane.pb

**Comment by sushreebarsa** [comment]
@Pan17WJ Is it failing for the latest TF v2.13 as well? If so please provide the complete standalone code to replicate this issue? Thank you!
