### ISSUE TITLE
LSTM support for quantisation aware training.

### ISSUE THREAD

**Issue by TayyabaZainab0807** [tensorflow/tensorflow#61329]
I wonder if quantization-aware training has the support for lstm?

**Comment by sushreebarsa** [comment]
@TayyabaZainab0807 Could you please have a look at the post-training quantization. As per this [thread](https://discuss.tensorflow.org/t/quantizing-lstm-layers/1876) of TF forum unfortunately, Quantization aware training is not supports LSTM/RNN layers yet. It is in the process to be implemented. Thank you!
