### ISSUE TITLE
Applying

### ISSUE THREAD

**Issue by Amindofastoner0312** [tensorflow/tensorflow#61333]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
# Copy and paste here
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by Amindofastoner0312** [comment]
Build on this APIs thank you!

**Comment by tilakrayal** [comment]
@Amindofastoner0312,
Could you please provide the more context/information and tensorflow version you are using to debug the issue.
Also please take a look at the official tensorflow installation [document](https://www.tensorflow.org/install) which helps to install smoothly and tensorflow provided a large number of API's where the documentation and the implementation of the API's are available here.
https://www.tensorflow.org/api_docs/python/tf

Thank you!
