### ISSUE TITLE
Share via phone 

### ISSUE THREAD

**Issue by Amindofastoner0312** [tensorflow/tensorflow#61355]
Note: Not all videos are eligible for automatic chapters, and not all eligible videos will have automatic chapters. If the channel has any active strikes, or if the content may be inappropriate to some viewers, the video chapters feature will always be available.
Issue is now fixed.

**Comment by SuryanarayanaY** [comment]
@Amindofastoner0312 ,

It seems to be a spam issue. If you have any issues related to tensorflow please fill the [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=&projects=&template=tensorflow_issue_template.yaml) with all required details.
