### ISSUE TITLE
TFLite Error

### ISSUE THREAD

**Issue by MogilipalemHemanthKumar** [tensorflow/tensorflow#61353]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 11
- TensorFlow installed from (source or binary):source 
- TensorFlow version (or github SHA if from source):2.15.0

**Provide the text output from tflite_convert**
The below is the code, I am using to convert the deep learning model to tflite

converter = tf.lite.TFLiteConverter.from_keras_model(best_model)

converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]

tflite_model = converter.convert()

with open('compressed_model.tflite', 'wb') as f:
f.write(tflite_model)

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

https://colab.research.google.com/drive/1QlquN0xR94xMdiUNer00Nu0n5UDXdiWQ
![error](https://github.com/tensorflow/tensorflow/assets/107172150/19056701-1422-4ab2-939a-545f3f799f48)

**Comment by pjpratik** [comment]
Hi @MogilipalemHemanthKumar 

We need to add the select tf ops dependencies as mentioned error if the converted model has select ops.

You can specify this in your build.gradle dependencies by adding it alongside the standard TensorFlow Lite AAR as follows:
```
dependencies {
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
    // This dependency adds the necessary TF op support.
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly-SNAPSHOT'
}
```
Thanks.
