### ISSUE TITLE
Unable to save model when using EfficientNetB0

### ISSUE THREAD

**Issue by Seferovic8** [tensorflow/tensorflow#61366]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.12.0

### Custom code

Yes

### Current behavior?

I’m trying to use EfficientNetB0 to create a model and save the model to my local disk. However, when saving it, it throws the error below.

> TypeError: Unable to serialize [2.0896919 2.1128857 2.1081853] to JSON. Unrecognized type <class 'tensorflow.python.framework.ops.EagerTensor'>.

Also, I tried to downgrade tensorflow from V2.12.0 to V2.9.1, this works as expected. In other words, this is a bug in 2.12.0. Hope it helps and please fix this bug for V2.12.0

### Standalone code to reproduce the issue

```shell
model = tf.keras.applications.EfficientNetB0()
model.save("model")
```

### Relevant log output

```shell
TypeError: Unable to serialize [2.0896919 2.1128857 2.1081853] to JSON. Unrecognized type <class 'tensorflow.python.framework.ops.EagerTensor'>.
```

**Comment by SuryanarayanaY** [comment]
Hi @Seferovic8 ,

The issue resolved in TF2.13v. Please refer to attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/dbdb3fc33d50e28dc9dc5093ddc7ae77/61366.ipynb) and may test yourself. Since it is resolved in latest version its unlikely to cherry pick for TF2.12 version.

**Comment by Seferovic8** [comment]
Thank you, this works for me.

**Comment by Seferovic8** [comment]
Yes
