### ISSUE TITLE
Performance drop with tensorflow 2.13

### ISSUE THREAD

**Issue by nhuet** [tensorflow/tensorflow#61363]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

v2.13.0-rc2-7-g1cb1a030a62 2.13.0

### Custom code

Yes

### OS platform and distribution

Debian GNU/Linux 12 (bookworm)

### Python version

3.9

### Current behavior?

I notice a big performance drop between tensorflow 2.12 (CPU) and tensorflow 2.13 (CPU). With the last release (and also with tf-nightly '2.14.0-dev20230724') it takes *4 times* longer to perform a simple sum. It is between keras inputs though some I am not sure if this is directly related to tensorflow or if it comes from keras.

See code below for a very simple example. Note that this is with tensorflow CPU only.
The timings are:
- for tensorflow 2.12.1 + keras 2.12.0: **5.3 s**
- for tensorflow 2.13.0 + keras 2.13.1: **24 s**
- for tensorflow 2.14.0-dev20230724 + keras  2.14.0.dev2023072407: 26 s

### Standalone code to reproduce the issue

```shell
import time

from tensorflow.keras import Input


number_of_executions = 3000

x = Input((1,))
y = Input((1,))

start = time.time()
for i in range(number_of_executions):
    x + y
duration = time.time() - start
print(f"Duration: {duration:.1f}")
```

**Comment by sushreebarsa** [comment]
@nhuet I tried to replicate the issue on colab using TF [v2.12](https://colab.research.google.com/gist/sushreebarsa/e498716b10932a7d557ab3a3a9fccb76/61363-2-12.ipynb) and [2.13](https://colab.research.google.com/gist/sushreebarsa/3ec5e639c34bb5c3d965c531fe1090b3/untitled813.ipynb#scrollTo=UpjWS8k2G3ms), could you please have a look at the attached gists and confirm the same?
Thank you!

**Comment by nhuet** [comment]
It seems to show the issue (even though only 3* slower, this is still abnormal)

**Comment by sushreebarsa** [comment]
@nhuet thank you for the quick response
@sachinprasadhs Could you please have a look at this. Thank you!

**Comment by nhuet** [comment]
Hi @grasskin. You are right I should have definitely tried this. And this works very well indeed (even better than keras2.12 + tf 2.12). Here are the new timings:
- keras 2.12.0 + tensorflow 2.12.1: 7.8 s
- keras 2.13.1 + tensorflow 2.13.0: 24.1 s
- keras-core 0.1.3 + tensorflow 2.12.1: 0.4 s
- keras-core 0.1.3 + tensorflow 2.13.0: 0.3 s

(and even increasing the number of iteration, there is not noticeable differences between keras-core + tf2.12 or keras-cre + tf2.13)

Thus, the "bug" came from keras 2.13, and the performance is way better with keras-core than with previous keras 2.12.
Thanks a lot!

**Comment by sachinprasadhs** [comment]
Hi @nhuet , Thanks for confirming your findings with the keras-core. 
I'm glad that keras-core + tensorflow gave the good performance result.

For latest package details, please visit https://pypi.org/project/keras-core/

Feel free to close the issue. Thanks!
