### ISSUE TITLE
ImportError: No module named 'tensorflow' on windows + anaconda

### ISSUE THREAD

**Issue by jesaremi** [tensorflow/tensorflow#6136]
I followed the instructions on downloading and setting up tensorflow on windows. they result in one red line on the pip installation and the no-module-found error message in python interactive.

steps:
- install anaconda for windows 64bit for python 3.5 as per given link in the tensorflow install page
- issue a pip for tensorflow (either one of these would result in the samething):
C:\> pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl
or
C:\> pip install --upgrade https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-0.12.0rc0-cp35-cp35m-win_amd64.whl

the pip installation ends with a line printed in red:
"Cannot remove entries from nonexistent file c:\users\jesaremi\appdata\local\continuum\anaconda3\lib\site-packages\easy-install.pth"

- open up python and type "import tensorflow as tf":
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'tensorflow'

**Comment by jesaremi** [comment]
I also checked the c++ runtime as mentioned in the doc page. I have the exact same thing already installed

**Comment by jesaremi** [comment]
here's the entire pip install log:
pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl
Collecting tensorflow==0.12.0rc0 from https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl
  Downloading https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl (12.2MB)
    100% |################################| 12.2MB 112kB/s
Collecting protobuf==3.1.0 (from tensorflow==0.12.0rc0)
  Downloading protobuf-3.1.0-py2.py3-none-any.whl (339kB)
    100% |################################| 348kB 1.6MB/s
Collecting numpy>=1.11.0 (from tensorflow==0.12.0rc0)
  Downloading numpy-1.11.2-cp35-none-win_amd64.whl (7.6MB)
    100% |################################| 7.6MB 183kB/s
Requirement already up-to-date: six>=1.10.0 in c:\users\jesaremi\appdata\local\continuum\anaconda3\lib\site-packages (from tensorflow==0.12.0rc0)
Requirement already up-to-date: wheel>=0.26 in c:\users\jesaremi\appdata\local\continuum\anaconda3\lib\site-packages (from tensorflow==0.12.0rc0)
Collecting setuptools (from protobuf==3.1.0->tensorflow==0.12.0rc0)
  Downloading setuptools-30.2.0-py2.py3-none-any.whl (472kB)
    100% |################################| 481kB 2.1MB/s
Installing collected packages: setuptools, protobuf, numpy, tensorflow
  Found existing installation: setuptools 27.2.0
Cannot remove entries from nonexistent file c:\users\jesaremi\appdata\local\continuum\anaconda3\lib\site-packages\easy-install.pth

**Comment by Carmezim** [comment]
This seems to be an Anaconda issue. Could you please try upgrading setuptools:
`pip install --upgrade -I setuptools` 

and then installing TensorFlow again with `--ignore-installed` flag:
`pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl`

Then see if there is success.

**Comment by Carmezim** [comment]
@mrry should I submit a PR to get_started docs with a note about this anaconda issue when pip is trying to remove `easy-install.pth` and it does not exist in a new Anaconda installation. This happens when the conda setuptools version is behind pip setuptools.

**Comment by jesaremi** [comment]
Adriano, the setuptools upgrade fixed everything. thanks very much

**Comment by mrry** [comment]
@Carmezim That would be a great addition to the "Common Problems" section, thanks!

**Comment by Carmezim** [comment]
@mrry Cool. Will be doing it ASAP.

**Comment by robosoup** [comment]
@Carmezim - the setuptools upgrade fixed my issue too - awesome!

**Comment by Carmezim** [comment]
@robosoup Nice! Glad it worked for you!

**Comment by tristanbrown** [comment]
This did not fix it for me. I'm still having the same problem.

**Comment by Carmezim** [comment]
@tristanbrown could you please elaborate giving more specifics of what you did and used?

**Comment by caffreit** [comment]
I had the same issue. Thanks very much. Sound lad!

**Comment by antoniogomes8** [comment]
the setuptools upgrade fixed everything. Thanks

**Comment by ddavidraj** [comment]
Setuptools upgrade fixed thanks a lot.

**Comment by NikhilBhutani** [comment]
Upgrading the Setuptools fixed everything, Thank you @Carmezim

**Comment by gineeshvs** [comment]
Great - upgrading the set-up tools worked !

**Comment by ddavidraj** [comment]
Yes I did the same in Windows. Worked fine

**Comment by Carmezim** [comment]
@igour Do you mean upgrading `setuptools`? If it is, this answer was to address a problem with Anaconda distribution in this case on Windows so at least on it that is supposed to work.

**Comment by bhavsarpratik** [comment]
Hi, I have laid down step-by-step instructions to successfully install Tensorflow on Windows.

https://github.com/bhavsarpratik/install_Tensorflow_GPU_windows

**Comment by salmiadu** [comment]
Hi Guys!
here is the way how i fixed the problem of installing tensorflow on Windows. I will start 👍from the begining 👍 
1. I downloaded the Anaconda 4.3.1 For Windows with Python 3.6 version. 
2. Create a conda environment named tensorflow by invoking the following command:
C:> conda create -n tensorflow 

3. Activate the conda environment by issuing the following command:
C:> activate tensorflow
 (tensorflow)C:>  # Your prompt should change 

3. Issue the appropriate command to install TensorFlow inside your conda environment. To install the CPU-only version of TensorFlow, enter the following command:

(tensorflow)C:> pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.1-cp35-cp35m-win_amd64.whl 

Message appear : can not install this wheel ......... [ i forgot the message, it's just couldn't find the point]
To install the GPU version of TensorFlow, enter the following command (on a single line):
(tensorflow)C:> pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.0.1-cp35-cp35m-win_amd64.whl  

same message appear couldn't install 

so after that i wanted to write my first code 👍 
c>python
python version 3.6 .... (anaconda).............
>>> import tensorflow as tf
[it appears this Error : ]

Traceback <most recent call last>:
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'

-----------------------------------------------------------------------------
Fix The Problem 
https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.1-cp35-cp35m-win_amd64.whl

tensorflow-1.0.1 -cp35-cp35m-win_amd64.whl
tensorflow version 1.0.1 
-cp 35 : python version needed
win_amd64 : windows x64 

so the Anaconda 4.3.1 For Windows with Python 3.6 version so we need python 3.5 i downloaded it from other this web site cause anaconda has only the version 4.3.1 &  for python 2.7 : 
so this anaconda for python 3.5 : http://www.gurobi.com/downloads/get-anaconda 
then i followed the other steps & everything worked fine :), i hope everything was worked with you

**Comment by EMCL** [comment]
Installing collected packages: numpy, six, appdirs, pyparsing, packaging, setupt
ools, protobuf, wheel, tensorflow
Successfully installed appdirs-1.4.3 numpy-1.12.1 packaging-16.8 protobuf-3.2.0
pyparsing-2.2.0 setuptools-34.3.3 six-1.10.0 tensorflow-1.0.1 wheel-0.29.0

but when i try the python console 3.5
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import tensorflow as tf
ImportError: No module named 'tensorflow'

im using windows 7 bit 64 and python 3.5

**Comment by salmiadu** [comment]
@EMCL  read my comment above, install anaconda that may help you

**Comment by vap31** [comment]
Hello , i am using tensorflow in windows. I tried every thing still i am getting no module name tensorflow
I tried following ways
C:> conda create -n tensorflow python=3.5 
C:> activate tensorflow
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.2.0-cp35-cp35m-win_amd64.whl 

Still i am getting two errors
1 -tensorflow-1.2.0-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.
2- No module name tensorflow

**Comment by mrry** [comment]
@vap31 Are you using the 64-bit version of Python?

**Comment by vap31** [comment]
Yea, i do use 64 - bit of python

**Comment by xgwei** [comment]
@vap31 as the most recent version of anaconda is incorporated with python 3.6. you may change the commands to 
conda create -n tensorflow python=3.6
 activate tensorflow
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.2.0-cp36-cp36m-win_amd64.whl

**Comment by joellerena** [comment]
![ok](https://user-images.githubusercontent.com/24687663/28496262-d592a20c-6f2c-11e7-87fb-d32e4eccb2b6.png)

**Comment by joellerena** [comment]
For Windows 7 x64,  > conda update numpy --no-pin
¡resolved!

**Comment by anne1994** [comment]
The best way is to install anaconda and then install tensorflow with pip instead of creating a conda environment, activating tensorflow.  Thats the only thing that worked for me as of now.

**Comment by friend4al** [comment]
@joellerena @xgwei 

I recently downloaded Anaconda 4.4.0 with python 3.6 version for 64bit windows 10 OS and the suggested code did not work even with python=3.6 but I did the following steps to get it installed.

1) After Installing New Anaconda 4.4.0 with python 3.6 version, Open Anaconda Prompt and type in the following :

C:\Users\Mahesh>conda create -n tensorflow python=3.5
C:\Users\Mahesh>activate tensorflow
(tensorflow) C:\Users\Mahesh>conda install -c conda-forge tensorflow

Come back to Anaconda Navigator which got installed with Anaconda 4.4.0. Here, you have an option of "Application on" on your home page displaying 2 answers: 
1) root
2)tensorflow

Select tensorflow and you can see all the applications which are under it. if they are not installed then install them once again by clicking on install button and launch an application to run the code(Spyder/Jupyter notebook)

Then Validate with the following code:

import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
print(sess.run(hello))

Change the application to root/tensorflow depending on your workflow.

**Comment by pksnkl** [comment]
Its working perfect.
But should we install again all packages like cv2, matplotlib etc.
Because spyder(tensorflow) shows the below error.

runfile('C:/Anaconda3/Scripts/programs/maskplot.py', wdir='C:/Anaconda3/Scripts/programs')
Traceback (most recent call last):

  File "<ipython-input-1-fa20f58c72ab>", line 1, in <module>
    runfile('C:/Anaconda3/Scripts/programs/maskplot.py', wdir='C:/Anaconda3/Scripts/programs')

  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 688, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3\envs\tensorflow\lib\site-packages\spyder\utils\site\sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Anaconda3/Scripts/programs/maskplot.py", line 1, in <module>
    import cv2

ModuleNotFoundError: No module named 'cv2'

**Comment by anne1994** [comment]
you can try "pip install opencv-python" @pksnkl

**Comment by Ahmeedtraabelsi** [comment]
ImportError: No module named 'tensorflowvisu'

**Comment by yangst09** [comment]
Thank you, Carmezim, you solution worked perfectly well. It saved my two days work.

**Comment by noklek** [comment]
i had the same issue.  and how i fixed it in my issue : is set path of Environment go to Anaconda.
eg. ('C:\ProgramData\Anaconda3') in path value

**Comment by hzy9981** [comment]
isee

**Comment by hzy9981** [comment]
up

**Comment by xdagee** [comment]
Brilliant, this is how I fixed mine with setupTools.

Upgrade setuptools:
pip install --upgrade -I setuptools

Install tensorflow
pip install tensorflow --ignore-installed --upgrade

**Comment by avengersassemble** [comment]
Hi Carmezim
I installed tensorflow via anaconda prompt. was getting error 'No module named tensorflow'.
Trying to upgrade pip but it's not happening.
![image](https://user-images.githubusercontent.com/25078915/40268097-22aaa4fa-5b85-11e8-810a-1e9ed0abe27a.png)

**Comment by xdagee** [comment]
if not already installed, download and install Anaconda. Then open the command prompt in Anaconda, now run your commands, it will work.

**Comment by rdekou** [comment]
Installing with pip works for me: 

python -m pip install --upgrade tensorflow

https://stackoverflow.com/questions/42559222/installation-of-tensorflow-on-windows-7-pip3-is-not-recognized-as-an-interna

**Comment by darshan309** [comment]
If you are using Anaconda Navigator,  selection Applications on as "tensorflow" before launching the visual studio code

if you are using cmd prompt, activate tensorflow first.

**Comment by madhusmita18** [comment]
![image](https://user-images.githubusercontent.com/43405947/45753810-c1919200-bbce-11e8-89f6-ee70dfc15062.png)why this is happening frequently . plz help me in installing tensorflow

**Comment by suho0515** [comment]
thanks Carmezim, you fix my trouble perfectly!

**Comment by ahchan2018** [comment]
thx

**Comment by jarc9718** [comment]
Thanks man, I was looking for so much for that, I solved it.

**Comment by krishnakakade1999** [comment]
still getting error module not found python 3.6

**Comment by tcchen123** [comment]
Using Anaconda prompt, was upgrading my Tensorflow in tf env using the command below. 
(tf) C:\Users\User>pip install tensorflow --ignore-installed --upgrade --use-feature=2020-resolver

Hit error below.
Installing collected packages: urllib3, pyasn1, idna, chardet, certifi, zipp, six, setuptools, rsa, requests, pyasn1-modules, oauthlib, cachetools, requests-oauthlib, importlib-metadata, google-auth, wheel, werkzeug, tensorboard-plugin-wit, protobuf, numpy, markdown, grpcio, google-auth-oauthlib, absl-py, wrapt, termcolor, tensorflow-estimator, tensorboard, opt-einsum, keras-preprocessing, h5py, google-pasta, gast, astunparse, tensorflow
**ERROR: yarl 1.6.2 requires typing-extensions>=3.7.4; python_version < "3.8", which is not installed.
aiohttp 3.6.3 requires yarl<1.6.0,>=1.0, but you'll have yarl 1.6.2 which is incompatible.**
Successfully installed absl-py-0.11.0 astunparse-1.6.3 cachetools-4.1.1 certifi-2020.11.8 chardet-3.0.4 gast-0.3.3 google-auth-1.23.0 google-auth-oauthlib-0.4.2 google-pasta-0.2.0 grpcio-1.33.2 h5py-2.10.0 idna-2.10 importlib-metadata-2.0.0 keras-preprocessing-1.1.2 markdown-3.3.3 numpy-1.19.2 oauthlib-3.1.0 opt-einsum-3.3.0 protobuf-3.14.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-2.25.0 requests-oauthlib-1.3.0 rsa-4.6 setuptools-50.3.2 six-1.15.0 tensorboard-2.4.0 tensorboard-plugin-wit-1.7.0 tensorflow-2.3.1 tensorflow-estimator-2.3.0 termcolor-1.1.0 urllib3-1.26.2 werkzeug-1.0.1 wheel-0.35.1 wrapt-1.12.1 zipp-3.4.0

(tf) C:\Users\User>
Pls help to advise how to fix this error. Thanks for your help.
