### ISSUE TITLE
Cannot type "I Accept" to extract from hexagon_nn_skel

### ISSUE THREAD

**Issue by yx-chan131** [tensorflow/tensorflow#61378]
Workflow:
1. download hexagon_nn_skel.run from [this link](https://storage.cloud.google.com/download.tensorflow.org/tflite/hexagon_nn_skel_v1.20.0.1.run)
2. adb push to /data/local/tmp
3. run cmd: chmod +x tflite_hexagon_nn_skel_v1.20.0.1.run
4. run cmd: .\tflite_hexagon_nn_skel_v1.20.0.1.run
5. **Extraction aborted**: 
![Screenshot 2023-07-25 182129](https://github.com/tensorflow/tensorflow/assets/68681893/09484ae3-7156-4c61-9612-31c57fba8aa3)

Problem: 
After the program shows "**_Type "I ACCEPT" if you agree to the terms of the license:_**", it didn't give me time to type "I ACCEPT", and hence extraction aborted.

**Comment by octavflorescu** [comment]
Did you find a solution for this?

**Comment by octavflorescu** [comment]
If you are running it directly in adb, don't do that. Run directly on desktop (my case a Mac).
```bash
chmod +x tflite_hexagon_nn_skel_v1.20.0.1.run
./tflite_hexagon_nn_skel_v1.20.0.1.run
```
