### ISSUE TITLE
OneDNN logs are not printing while building TF with --config=mkl_aarch64

### ISSUE THREAD

**Issue by deepeshfujitsu** [tensorflow/tensorflow#61376]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.13.0

### Custom code

Yes

### OS platform and distribution

Ubuntu 22.04.2 LTS

### Python version

3.10.6

### Bazel version

6.3

### GCC/compiler version

11.3.0

### Current behavior?

I am expecting OneDNN logs should print while running deep learning model such as resnet50, if we export ONEDNN_VERBOSE=1

### Standalone code to reproduce the issue

```shell
To reproduce same, we have to build TF on Arm CPU, and use following command to build:
bazel build --config=mkl_aarch64 //tensorflow/tools/pip_package:build_pip_package
```

**Comment by maajidkhann** [comment]
@tilakrayal  I see the same issue when I tried compiling latest TFv2.13 from source on Graviton(ARM) with the latest C;ANG 16 compiler and with --config=mkl_aarch64. The compilation goes through, but when we run some TF application, we are not able to see any OneDNN logs even with **export ONEDNN_VERBOSE=1** set.

**Comment by deepeshfujitsu** [comment]
we are getting onednn_logs after setting two flags:

export ONEDNN_VERBOSE=1

export TF_ENABLE_ONEDNN_OPTS=1
