### ISSUE TITLE
converting LSTM layer to tflite with float16 fails

### ISSUE THREAD

**Issue by sronen71** [tensorflow/tensorflow#61370]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.13.0

### Custom code

Yes

### OS platform and distribution

Colab

### Python version

3.10

### Current behavior?

Tflite converter fails to convert model with LSTM layer to float16 target.
It runs for a very long time, increases RAM consumption to the maximum system available, then crashes.

Expected behavior: should convert.

Workaround: instead of LSTM layer, use  RNN wrapper of LSTMCell instead of the LSTM layer. 
Tflite is successful in converting the alternative with float16 target.

### Standalone code to reproduce the issue

```shell
See this gist:
https://colab.research.google.com/gist/sronen71/9b016245f507280f867841a7161fad8d/keras-lstm-fusion-codelab.ipynb
```

### Relevant log output

```shell
Program crash after it is out of RAM.
```

**Comment by sushreebarsa** [comment]
@sronen71 For LSTM conversion, this is an [article](https://www.tensorflow.org/lite/convert/rnn) and colab describing the process, and you can follow the [colab gist](https://colab.sandbox.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb) to do it. For [4 kinds of quantizations](https://www.tensorflow.org/lite/performance/model_optimization), maybe you can also try other ways like dynamic range. Hope it could help? Please let us know. Thank you!

**Comment by sronen71** [comment]
[sushreebarsa](https://github.com/sushreebarsa) -
I checked that information and colab example previously, and based my colab gist on that.
I find the original colab example is broken right now, because of tf-nightly error.
I was able to run it yesterday successfully, however, it only uses the vanilla convert.
When I try to use the optimize option with float16 target, as in the colab gist I attached, the reported defect is observed.

**Comment by pjpratik** [comment]
@pkgoogle I was able to reproduce this issue. Please find this [gist](https://colab.research.google.com/gist/pjpratik/f814b84dc79edfee54977c82c98cc34c/61370.ipynb).

Could you please look into this?

Thanks.

**Comment by pkgoogle** [comment]
I was able to replicate with @pjpratik's exact same gist, @abattery, can you please take a look? Thanks.

**Comment by devadigapratham** [comment]
Hi, can i work on this issue ?

**Comment by pkgoogle** [comment]
Hi @devadigapratham, we always welcome any contribution from the community. Please let us know if you have any questions.

**Comment by barrypitman** [comment]
Also running into this issue for float16 tflite conversions

**Comment by LakshmiKalaKadali** [comment]
Hi @sronen71 ,

You can now move to [AI-Edge-Torch](https://github.com/google-ai-edge/ai-edge-torch) to resolve your issue. you can find more information here: [googleblog](https://developers.googleblog.com/en/ai-edge-torch-high-performance-inference-of-pytorch-models-on-mobile-devices/).

Here is a simple script for converting an LSTM model here:

import torch
import torchvision
import ai_edge_torch
```py
rnn = torch.nn.LSTM(10, 20, 2)
sample_inputs = (torch.randn(5, 3, 10),)

edge_model = ai_edge_torch.convert(rnn.eval(), sample_inputs)
edge_model.export("rnn.tflite")

try:
  edge_model = ai_edge_torch.convert(rnn.eval(), sample_inputs)
  edge_model.export('rnn.tflite')
  print("Conversion successful!")
except Exception as e:
  print("Error during conversion:", e)

```
Try visualizing the result in [model-explorer](https://github.com/google-ai-edge/model-explorer) as well.

Please try them out and let us know if this resolves your issue. If you still need further help, feel free to open a new issue at the respective repos.
