### ISSUE TITLE
`tensorflow-macos` 2.13.0 missing x86 wheels

### ISSUE THREAD

**Issue by johnthagen** [tensorflow/tensorflow#61382]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.13.0

### Custom code

No

### OS platform and distribution

macOS 13 x86

### Mobile device

N/A

### Python version

3.10

### Current behavior?

`tensorflow-macos` 2.13.0 release is [missing x86 wheels for macOS](https://pypi.org/project/tensorflow-macos/2.13.0/#files). This means that using tools like [Poetry](https://python-poetry.org/) or [`pip-tools`](https://github.com/jazzband/pip-tools) to lock versions, it's not possible to use 2.13.0 because if it's locked to that version, it will fail to install on x86 Macs.

[x86 wheels were provided for 2.12.0](https://pypi.org/project/tensorflow-macos/2.12.0/#files).

### Standalone code to reproduce the issue

From an x86 macOS machine:

```shell
python -m pip install tensorflow-macos==2.13.0
```

### Relevant log output

```shell
ERROR: Could not find a version that satisfies the requirement tensorflow-macos==2.13.0 (from versions: 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.11.0, 2.12.0)
ERROR: No matching distribution found for tensorflow-macos==2.13.0
```

**Comment by sachinprasadhs** [comment]
Hi, 

Thanks for reporting the issue.

We don't officially support the `tensorflow-macos` releases.

You can try installing the tensorflow for macOS using `pip install tensorflow` and it installs tensorflow-macos package as well.
You can refer to the download files for MacOS here https://pypi.org/project/tensorflow/#files
