### ISSUE TITLE
How to use the estimator interface to achieve cross-node training without using the strategy of tf itself

### ISSUE THREAD

**Issue by yeoways** [tensorflow/tensorflow#61396]
### Issue type

Documentation Feature Request

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf2.7

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 16.04

### Python version

python3.10

### Bazel version

5.1.1

### GCC/compiler version

9.4

### GPU model and memory

Tesla P100 12GB

### Current behavior?

![image](https://github.com/tensorflow/tensorflow/assets/69454138/f7e1159d-cd51-4dca-8890-2b9aebe58e57)

Cross-node training can be achieved in this way in tf1. If I want to use the estimator interface for training, can I put server.target in a certain config (similar to tf.estimator.RunConfig)

### Standalone code to reproduce the issue

```shell
cluster_spec = tf.train.ClusterSpec({
      'chief': ['172.20.21.189:1234'],
      'worker': ['172.20.21.197:1234'],
    })
simple_resolver = tf.distribute.cluster_resolver.SimpleClusterResolver(cluster_spec, task_type="chief",task_id=0)
is_per_host = tf.estimator.tpu.InputPipelineConfig.PER_HOST_V2
run_config = tf.estimator.tpu.RunConfig(
      cluster=simple_resolver,
      master=FLAGS.master,
      model_dir=FLAGS.output_dir,
      save_checkpoints_steps=FLAGS.save_checkpoints_steps,
      tpu_config=tf.estimator.tpu.TPUConfig(
          iterations_per_loop=FLAGS.iterations_per_loop,
          num_shards=FLAGS.num_tpu_cores,
          per_host_input_for_training=is_per_host))
I do this configuration in the estimator interface, but he doesn't seem to be training across nodes (multiple servers),It seems to only recognize local devices.
```

**Comment by sushreebarsa** [comment]
@yeoways  tf.estimator.RunConfig is a deprecated function of Estimator and it will be removed in future versions. Please have a look at [this](https://www.tensorflow.org/api_docs/python/tf/estimator/RunConfig) doc. 
Could you migrate from the deprecated apis to latest as it would not raise the bug. Thank you!
