### ISSUE TITLE
int8 tflite model allocate_tensors() silently stop python process.

### ISSUE THREAD

**Issue by bluesy7585** [tensorflow/tensorflow#61395]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.8.1, 2.13.0, '2.14.0-dev20230706'

### Custom code

Yes

### OS platform and distribution

Windows 11, Windows 10 WSL with Ubuntu 20.04

### Python version

3.8

### Current behavior?

I have converted a Resnet18 model from onnx to tflite. (onnx > tf > tflite)
onnx to tf conversion is done by this [repo](https://github.com/onnx/onnx-tensorflow)
tflite is converted to int8 precision using post-training integer quantization [link](https://www.tensorflow.org/lite/performance/post_training_integer_quant)
Netron can display the converted int8 model correctly.
onnx model & tflite model [link](https://drive.google.com/file/d/1XvxGt5GGFCO7h2FW69hgdYZ9noh5Svd4/view?usp=sharing)
tflite int8 model [link](https://drive.google.com/file/d/1bLjoawNnhQTy-DMsBGUEtF6mW3GLVN2F/view?usp=sharing)

but when I try to do inference. calling the method allocate_tensors() stop the python process without showing any error/warning.

if the tflite model is converted with fp32, this issue  doesn't happen.

I have no idea how do to fix this issue or is there any workaround?
thanks

### Standalone code to reproduce the issue

```shell
## tf to tflite conversion
import tensorflow as tf
import numpy as np

saved_model_dir = 'resnet18'
tflite_model_path = saved_model_dir + '.tflite'

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

def representative_dataset_gen():
    for _ in range(100):
        data = np.random.rand(1, 3, 224, 224)
        yield [data.astype(np.float32)]

converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

tflite_model = converter.convert()

# Save the model
with open(tflite_model_path, 'wb') as f:
    f.write(tflite_model)


## inference time
import tensorflow as tf
interpreter = tf.lite.Interpreter(model_path="resnet18.tflite")
print('before')
interpreter.allocate_tensors()
print('after') # this line not displayed
```

### Relevant log output

```shell
# inference time output (tf 2.14.0-dev20230706)
WARNING:tensorflow:From C:\Users\AI\miniconda3\envs\tf\lib\site-packages\tensorflow\python\ops\distributions\distribution.py:259: ReparameterizationType.__init__ (from tensorflow.python.ops.distributions.distribution) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
WARNING:tensorflow:From C:\Users\AI\miniconda3\envs\tf\lib\site-packages\tensorflow\python\ops\distributions\bernoulli.py:165: RegisterKL.__init__ (from tensorflow.python.ops.distributions.kullback_leibler) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
before
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
```

**Comment by bluesy7585** [comment]
I found a workaround for this issue. 
instead of converting from tf to tflite, convert from keras to tflite works for me. (onnx > keras > tflite)
onnx to keras conversion is done by onnx2keras package (pip install)
keras to tflite using the same code above (only replace with tf.lite.TFLiteConverter.from_keras_model)

**Comment by pjpratik** [comment]
Hi @bluesy7585 

Thanks for the workaround. 

I see the onnx-TF library has not been updated recently and the conversion to TF might be causing the issue.

Feel free to close the issue since it is resolved.

Thanks.
