### ISSUE TITLE
`tensorflow-cpu` 2.13.0 missing Mac ARM wheels

### ISSUE THREAD

**Issue by johnthagen** [tensorflow/tensorflow#61401]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.13.0

### Custom code

No

### OS platform and distribution

macOS 13 ARM

### Python version

3.10

### Current behavior?

[`tensorflow` 2.13.0 added Mac ARM wheels](https://pypi.org/project/tensorflow/2.13.0/#files).

This allows Mac developers to use the standard `tensorflow` package rather than the `tensorflow-macos` package.

But in situations when CPU-only processing is needed, `tensorflow-cpu` is ideal (saving on network and disk usage). The problem is that `tensorflow-cpu` does not have Mac ARM wheels, so it cannot be used on that platform. This is important for teams with different architecture machines that want to share a common lock file produced by something like Poetry or `pip-tools`.

- https://pypi.org/project/tensorflow-cpu/2.13.0/#files

### Standalone code to reproduce the issue

```shell
python -m pip install tensorflow-cpu==2.13.0
```

### Relevant log output

```shell
ERROR: Could not find a version that satisfies the requirement tensorflow-cpu==2.13.0 (from versions: none)
ERROR: No matching distribution found for tensorflow-cpu==2.13.0
```

**Comment by Varsha-anjanappa** [comment]
Hi @johnthagen 

For MAC m1 m2 which is having arm architecture, it automatically downloads ARM 64 wheels that can use cpu/gpu by default when tensorflow is installed. 

For MACOS with intel chips tensorflow-cpu is available in the documentation.

Please refer the documentation on installing tensorflow [here](https://www.tensorflow.org/install/pip#macos) 

Thank you!!

**Comment by youurayy** [comment]
non-cpu tensorflow for mac arm requires ml-dtypes 0.2.0, but JAX can use ml-dtypes-0.3.2, which then conflict. Hence it would be beneficial to be able to install tensorflow-cpu, since the tensorflow mac arm support is simply broken and unusable anyway.

**Comment by egor-ryashin** [comment]
It's not clear from the documentation how to resolve this on MacOS M1:
```
pip install tensorflow-cpu==2.18.0
ERROR: Could not find a version that satisfies the requirement tensorflow-cpu==2.18.0 (from versions: none)
ERROR: No matching distribution found for tensorflow-cpu==2.18.0
```
