### ISSUE TITLE
NewCheckpointReader does not work for the V2 checkpoint format

### ISSUE THREAD

**Issue by rohitgirdhar** [tensorflow/tensorflow#6142]
Unable to read the new checkpoints (V2 format) that became default from r0.12 release using `NewCheckpointReader`. This breaks the TF slim API, specifically:
https://github.com/tensorflow/tensorflow/blob/c2d14aa0d80897b7164e32e16951d03a36342370/tensorflow/contrib/framework/python/ops/variables.py#L487

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/3AalcBJ-6z8
I started that thread and was suggested to post an issue here

### Environment info
Operating System: CentOS 6.6

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`): CUDA 8, cuDNN 5

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. 0.12.0-rc0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

```python
import tensorflow as tf

w1 = tf.Variable(tf.truncated_normal(shape=[10]), name='w1')
saver = tf.train.Saver()
sess = tf.Session()
sess.run(tf.initialize_all_variables())
saver.save(sess, 'my-model')

reader = tf.train.NewCheckpointReader('my-model.index')  ## error
print reader.get_variable_to_shape_map()
```

The error is:
```txt
Traceback (most recent call last):
  File "save_and_restore.py", line 9, in <module>
    reader = tf.train.NewCheckpointReader('my-model.index')
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 110, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern), status)
  File "/anaconda2/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for my-model.index
```

**Comment by ThibautLoiseleur** [comment]
I also notice that the recommanded script [inspect_checkpoint.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/inspect_checkpoint.py) is not working anymore since the r0.12 release of Tensorflow.

**Comment by michaelisard** [comment]
@sherrym would you reassign as necessary?

**Comment by ppwwyyxx** [comment]
You can use `tf.train.NewCheckpointReader('./my-model')` instead.
With V2 saver format, the reader is not expecting a file name, but only the prefix, (which I don't like).
The `./` is necessary because of a bug #4921.

**Comment by sherrym** [comment]
As @ppwwyyxx said, you just need to use "my-model" without ".index". Please let me know if that fixes the problem for you. Thanks.

**Comment by rohitgirdhar** [comment]
Yes, that seems to fix the problem. Thanks @ppwwyyxx !

**Comment by ivan-aksamentov** [comment]
Dot-slash workaround does not work for checkpoints that re not in the current directory. Neither `/path/to/./my-model`  nor `./path/to/my-model`.
Is there a workaround for that one? ;)

P.S. tested with the latest as of now commit fe70bd9c22357741e69751bdf189726c440db02e at r0.12 branch

**Comment by ppwwyyxx** [comment]
@ivan-aksamentov I thought you don't need this workaround for checkpoints that are not in `./`.
Are you suggesting that simply using `/path/to/my-model` doesn't work? What is the error?

**Comment by ivan-aksamentov** [comment]
@ppwwyyxx Indeed. Sorry, I screwed up the path. False alarm. Full path seems to be working now.
