### ISSUE TITLE
tflite-model-maker installation issue

### ISSUE THREAD

**Issue by Amayuru1999** [tensorflow/tensorflow#61426]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.12.0

### Custom code

Yes

### OS platform and distribution

Windows 11

### Current behavior?

For Image Classification

### Standalone code to reproduce the issue

```shell
error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by pjpratik** [comment]
Hi @Amayuru1999 

There is a known issue of tflite model maker installation if you are using Python >=3.10. Please use Python 3.9 or [Mediapipe Model Maker](https://developers.google.com/mediapipe/solutions/model_maker) as a workaround.

Thanks.

**Comment by imransanny** [comment]
!pip install git+https://github.com/tensorflow/examples.git
