### ISSUE TITLE
Since one week with a few different issues and two platforms I can't import Keras

### ISSUE THREAD

**Issue by sarahshehri** [tensorflow/tensorflow#61427]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

SystemError: initialization of _pywrap_checkpoint_reader raised unreported exception

### Custom code

No

### OS platform and distribution

Mac13.4 

### Python version

3.10.9

### Current behavior?

I face the error "SystemError: initialization of _pywrap_checkpoint_reader raised unreported exception" when I import keras to build DL model! I worked on make sure that the TensorFlow library is installed also I update the TensorFlow library to the latest version.
I need I help to resolve this issue because I think I trying a lot of recommendations!
Thanks

### Standalone code to reproduce the issue

```shell
Update the TensorFlow library to the latest version.
```

**Comment by sushreebarsa** [comment]
@sarahshehri Could you please make sure to follow the steps [here](https://keras.io/about/)?
Try to use the following;
```
from tensorflow import keras
```
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!

**Comment by sarahshehri** [comment]
[PROJECT-courseTWO.md](https://github.com/tensorflow/tensorflow/files/1
<img width="1123" alt="Screenshot 1445-01-13 at 9 13 11 PM" src="https://github.com/tensorflow/tensorflow/assets/46406878/6d847a0f-7970-419b-8acf-6a6f8d82a498">
2218033/PROJECT-courseTWO.md)

**Comment by sarahshehri** [comment]
<img width="1440" alt="Screenshot 1445-01-13 at 9 15 45 PM" src="https://github.com/tensorflow/tensorflow/assets/46406878/011db8db-37f0-4b4b-8a78-6603ef532ef5">
<img width="1148" alt="Screenshot 1445-01-13 at 9 15 52 PM" src="https://github.co
<img width="1119" alt="Screenshot 1445-01-13 at 9 14 00 PM" src="https://github.com/tensorflow/tensorflow/assets/46406878/5633f492-0905-4886-8dbb-dbbe6bd82ca1">
m/tensorflow/tensorflow/assets/46406878/de498264-cced-4829-812e-85239be1aa73">

**Comment by sarahshehri** [comment]
> @sarahshehri Could you please make sure to follow the steps [here](https://keras.io/about/)? Try to use the following;
> 
> ```
> from tensorflow import keras
> ```
> 
> In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!

I worked on but without any positive changes! And I attached the python notebook file can take skinnier on it! And I'm waiting your help

**Comment by sushreebarsa** [comment]
@sarahshehri Thank you for your response!
Could you please let me know what are the platforms you're using?
If you are using jupyter notebook, we recommend using conda as it will automatically install all the necessary dependencies. create a new cell in your Jupyter notebook and run the command below;
```
pip install tensorflow
```
It will install the latest TF version. Please make sure you have installed it.
Remember to create a new environment specifically for [TensorFlow](https://www.tensorflow.org/) to avoid conflicts with other [Python](https://www.python.org/) packages.

Thank you!

**Comment by sarahshehri** [comment]
> @sarahshehri Thank you for your response! Could you please let me know what are the platforms you're using? If you are using jupyter notebook, we recommend using conda as it will automatically install all the necessary dependencies. create a new cell in your Jupyter notebook and run the command below;
> 
> ```
> pip install tensorflow
> ```
> 
> It will install the latest TF version. Please make sure you have installed it. Remember to create a new environment specifically for [TensorFlow](https://www.tensorflow.org/) to avoid conflicts with other [Python](https://www.python.org/) packages.
> 
> Thank you!

Thaaaaaaaaank u!!!! finally is resolving i installed the conda on Anaconda platform with using the Jupyter. Thank u again

**Comment by sushreebarsa** [comment]
@sarahshehri Thank you for the confirmation. Glad it worked fine for you. Could you please close this issue as it is resolved.   
Thank you!
