### ISSUE TITLE
JAVA - org.tensorflow.TensorFlowException: Can't parse /<modelPath>/<somePathToFolder>/saved_model.pb as binary proto - JDK 17

### ISSUE THREAD

**Issue by 17patelumang** [tensorflow/tensorflow#61425]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

1.15.0

### Custom code

Yes

### OS platform and distribution

RHEL 8 version, 8.7.5

### Current behavior?

`/<modelPath>/<somePathToFolder>/`
Has following files:
1. assets/vocab.txt
2. saved_model.pb
3. variables/variables.data-00000-of-00001 
4. variables/variables.index

I am using java binding code to run the inference. Libraries I am using are 

```
<groupId>org.tensorflow</groupId>
<artifactId>tensorflow</artifactId>
<artifactId>1.15.0</artifactId>


<groupId>org.tensorflow</groupId>
<artifactId>libtensorflow</artifactId>
<artifactId>1.15.0</artifactId>


<groupId>org.tensorflow</groupId>
<artifactId>proto</artifactId>
<artifactId>1.15.0</artifactId>

<groupId>org.tensorflow</groupId>
<artifactId>libtensorflow_jni</artifactId>
<artifactId>1.15.0</artifactId>


```

TensorFlow version - 1.15.0
JDK - Oracle Open Jdk Version 17.0.5
OS - RHEL 8 version, 8.7.5
**Describe the current behavior**

```
org.tensorflow.TensorFlowException: Can't parse </modelPath>/<somePathToFolder>/saved_model.pb as binary proto
	at app//org.tensorflow.SavedModelBundle.load(Native Method)
	at app//org.tensorflow.SavedModelBundle.access$000(SavedModelBundle.java:27)
	at app//org.tensorflow.SavedModelBundle$Loader.load(SavedModelBundle.java:32)
	at app//org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:95)
	at app//com.main.java.main.tensorflow.TestClass.TFPredictor(TestClass.java:19)
```

**Describe the expected behavior**
In JDK 11, the code runs while in JDK 17 its throws error. The model file is not corrupted & same model path file is able to run successfully in JDK 11 

### Standalone code to reproduce the issue

```shell
Code:


import com.google.common.io.Resources;
import org.junit.Test;
import org.tensorflow.SavedModelBundle;
import org.tensorflow.Session;

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.Paths;

public class TestClass {

    @Test
    public void TFPredictor() throws IOException, URISyntaxException {
        SavedModelBundle b = SavedModelBundle.load("/<modelPath>/<somePathToFolder>", "serve");
        Session sess = b.session();
    }

}
```

**Comment by tilakrayal** [comment]
@17patelumang,
We see that you are using tf version 1.0, 1.x is not actively supported, please update to 2.x and let us know if you are facing the same issue. Also could you please confirm whether you are trying to install tensorflow using java from this official doc and follow the instructions mentioned here.
https://www.tensorflow.org/jvm/install
https://www.tensorflow.org/install/lang_java_legacy

Thank you!

**Comment by 17patelumang** [comment]
This is resolved, issue was .gitattribute file. It was replacing CRLF to LF thus corrupting the variables.data-00000-of-00001. Thanks for the help.
