### ISSUE TITLE
Feature request: second derivatives for pooling operations

### ISSUE THREAD

**Issue by kohpangwei** [tensorflow/tensorflow#6143]
Currently, neither `tf.nn.avg_pool` or `tf.nn.max_pool` support automatically taking second derivatives, making it difficult to experiment with second-order methods on neural networks that use any sort of pooling (which unfortunately includes most modern networks). Trying to take a second derivative gives a `LookupError`, e.g., `LookupError: No gradient defined for operation 'gradients_4...AvgPoolGrad' (op type: AvgPoolGrad)`.  

Do you have any plans for implementing second derivatives for pooling operations, or any suggested workarounds like rewriting the pooling operations in terms of elementary functions that have second derivatives defined? Thank you!

**Comment by michaelisard** [comment]
@vrv I see your name on discussions around this but can't tell who if anyone is working on it: would you reassign?

**Comment by vrv** [comment]
Well, nobody's job is to write ops for every feature request we get, we prioritize our work based on importance.  I'll mark this as contributions welcome in case somebody in the public wants to implement this, but perhaps somebody internally will find this important and do the work.

**Comment by AnishShah** [comment]
I will work on this! :)

**Comment by AnishShah** [comment]
Hi, I just wanted to confirm that the second order derivative for pooling operations will be a zero matrix. Am I correct? I'm returning a zero matrix for MaxPoolGrad opertation (commit:  bdc13db88c4735d43ee46142a18e9baf27b3bb44). Is it correct way of doing this? if it is correct, then I will start a pull request.

**Comment by philipperemy** [comment]
@AnishShah good luck!

**Comment by ahundt** [comment]
As per https://github.com/tensorflow/tensorflow/pull/6299 I'm not totally sure of the status of this, @aam-at have you picked this up in https://github.com/aam-at/tensorflow/tree/max_pool_grad_grad?

**Comment by aam-at** [comment]
Currently, I am finishing tests for new kernels. You can check up max_pool_grad_grad branch in my fork. As soon as I finish, I will make pull request.

**Comment by aam-at** [comment]
Please, checkout #6664

**Comment by ahundt** [comment]
@kohpangwei the functionality has been merged to master, if this covers everything can this issue be closed?

**Comment by kohpangwei** [comment]
@ahundt It looks great. Thank you @aam-at!
