### ISSUE TITLE
`FAKE_REQUIRED_PACKAGES` tensorflow-intel prevent poetry installation of `tensorflow-rocm`

### ISSUE THREAD

**Issue by ZappaBoy** [tensorflow/tensorflow#61434]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.12.0.560

### Custom code

Yes

### OS platform and distribution

Archlinux 6.1.38-2-lts

### Python version

3.11

### GPU model and memory

AMD Radeon RX 6700 XT - gfx1031

### Current behavior?

Updating  `tensorflow-rocm` using `poetry` produce a not resolvable dependency error due to `tensorflow-intel` "fake required package". 
The problem is due to the following lines:
https://github.com/tensorflow/tensorflow/blob/6d2f5ac299ef81e3bcd0a431b2375ebbd8252708/tensorflow/tools/pip_package/setup.py#L140-L142
https://github.com/tensorflow/tensorflow/blob/6d2f5ac299ef81e3bcd0a431b2375ebbd8252708/tensorflow/tools/pip_package/setup.py#L143-L144
In particular, the error is caused by the `_VERSION`. In fact, the same version of `tensorflow-rocm` (`2.12.0.560`) not exists in `tensorflow-intel`.

### Standalone code to reproduce the issue

```shell
poetry new fixme
cd fixme
poetry add tensorflow-rocm=="2.12.0.560"
```

### Relevant log output

```shell
Because tensorflow-rocm (2.12.0.560) depends on tensorflow-intel (2.12.0.560) which doesn't match any versions, tensorflow-rocm is forbidden.
So, because lstm-predictor depends on tensorflow-rocm (2.12.0.560), version solving failed.
```

### Possible fix
Simply truncate the version to the patch version before the FAKE_REQUIRED_PACKAGES list definition.
```python
# _VERSION="2.12.0.560"
_VERSION = (".").join(_VERSION.split(".")[:3])
```

### Other open issue
I open the same issue on [ROCmSoftwarePlatform/tensorflow-upstream](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream) [here](https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/issues/2161#issue-1809512685)

**Comment by Varsha-anjanappa** [comment]
Hi @ZappaBoy ,

To enable ROCm you have to build from source.

Please find the configuration [here](https://www.tensorflow.org/install/source#expandable-1).

Thank you!!

**Comment by ZappaBoy** [comment]
Hi @Varsha-anjanappa,
I had some free time and I created this PR https://github.com/tensorflow/tensorflow/pull/61444.
I hope this can help to solve the issue.

**Comment by Varsha-anjanappa** [comment]
Hi @ZappaBoy ,
Can this issue be closed now ?

**Comment by mihaimaruseac** [comment]
The PR did not land

**Comment by ZappaBoy** [comment]
@Varsha-anjanappa as discussed in the PR this seems to be an issue that the forks of tensorflow will have to solve independently, so this issue can be closed now.
