### ISSUE TITLE
When building from source code, I always end up with a Python 3.10 whl file, instead of a Python3.8 whl file.

### ISSUE THREAD

**Issue by moooises** [tensorflow/tensorflow#61436]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.14.0

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04.6 LTS

### Python version

3.8

### Bazel version

1.17

### GCC/compiler version

9.4.0

### CUDA/cuDNN version

11.8/8.7

### GPU model and memory

GTX 1050 Ti 4GB

### Current behavior?

When I try to build the source code from my machine I end up always with a wheel for Python 3.10, although I specified the python path for python3.8 and I don't even have python3.10 installed.

The generated wheel is called tensorflow-2.14.0-cp310-cp310-linux_x86_64.whl

Can you guide why this is happening and how to solve it?

### Standalone code to reproduce the issue

```shell
Just trying to build the source code following the steps from this two sites:

https://gist.github.com/kmhofmann/e368a2ebba05f807fa1a90b3bf9a1e03
https://www.tensorflow.org/install/source
```

**Comment by SuryanarayanaY** [comment]
Hi @moooises ,

Could you please confirm the python path selected in `./configure` step ?

```
/configure
You have bazel 6.1.0 installed.
Please specify the location of python. [Default is /Library/Frameworks/Python.framework/Versions/3.9/bin/python3]: 


Found possible Python library paths:
  /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
Please input the desired Python library path to use.  Default is [/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages]
```

Thanks!

**Comment by moooises** [comment]
Hi,
instead of having  /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 as the default path, I have /usr/bin/python3.
I tried with both /usr/bin/python3.8 and /usr/bin/python3, which in my system redirects to /usr/bin/python3.8, and with both paths I end up with a cp310 whl file .
Aside from Python2.7, which path is  /usr/bin/python, I only have Python3.8 installed.

**Comment by MichaelHudgins** [comment]
This is likely due to hermetic python picking out the default when it builds.  See: https://github.com/tensorflow/tensorflow/tree/master/ci/official/requirements_updater#hermetic-python-toolchain-details

Specifically for python 3.8, we have dropped support at HEAD to keep in following with numpy's python support.

**Comment by mihaimaruseac** [comment]
You should not need to run configure anymore. Just need to build a virtual env with the desired version of Python and/or use hermetic python build flags.

**Comment by SuryanarayanaY** [comment]
@moooises ,

The [comment-1662775801](https://github.com/tensorflow/tensorflow/issues/61436#issuecomment-1662775801) makes sense to me on why it is ended up with python 3.10 whl file. Also as the comment suggests python 3.8 versions may not be recommended for nightly builds. 

Could you please go through the comments above and do the necessary changes for build and let us know if still facing any issue. Thanks!

**Comment by SuryanarayanaY** [comment]
You can follow this [link](https://github.com/tensorflow/tensorflow/tree/master/ci/official/requirements_updater#how-to-add-a-new-python-version) to update python version. I can see `Python3.9` is minimum python version recommended for nightly where `Python3.10` is default. Not sure though `Python3.8` have any compatibility issues due to numpy dependencies. So please make a note of it and build accordingly.

**Comment by moooises** [comment]
I tried creating a virtual environment for python 3.10, as @mihaimaruseac suggested, using anaconda and I could install the generated whl file.
However I get some warning telling "Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered" and the same warning for cuFFT and cuBLAS. Aside from than, the installation seems to work. It recognize my GPU.
Will those warning cause me any problem in the future?

**Comment by SuryanarayanaY** [comment]
Just FYI, starting from Tf2.13v onwards TF uses Clang as compiler.

**Comment by moooises** [comment]
Ok, thanks for the responses.
I installed it again using conda and following the steps of the official guide https://www.tensorflow.org/install/pip and everything seems to work fine now. I don't have those duplication warnings anymore.
