### ISSUE TITLE
absl update required to slove MSVC compile error

### ISSUE THREAD

**Issue by johnnkp** [tensorflow/tensorflow#61435]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.13.0

### Custom code

Yes

### OS platform and distribution

Windows 10 22H2

### Python version

Anaconda 2023.07-1

### Bazel version

6.3.0

### GCC/compiler version

Visual Studio 2022 (build tools 14.36) + msys2-x86_64-20230718

### CUDA/cuDNN version

CUDA 11.8 + CUDNN 8.6.0 + TensorRT 8.5.3

### GPU model and memory

GTX 750 Ti 2GB

### Current behavior?

Currently, MSVC address sanitizer isn't enabled during compilation and cause compilation error. https://github.com/abseil/abseil-cpp/commit/2927340217c37328319b5869285a6dcdbc13e7a7 (LTS Jan 2023 Patch 3) has fixed it. This update required developers to check if corresponding code is necessary to change.

### Standalone code to reproduce the issue

```shell
1. download https://github.com/tensorflow/tensorflow/archive/refs/tags/v2.13.0.zip and extract
2. comment out Windows CUDA build rejection code in configure.py
3. run `python configure.py` to configure Windows CUDA build
4. run `bazel build --config=opt --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package`
```

### Relevant log output

```shell
error: "no_sanitize_address" is undefined
```

**Comment by SuryanarayanaY** [comment]
Hi @johnnkp ,

Windows CUDA builds not officially supported for Tf>2.11 versions as per the attached [source](https://www.tensorflow.org/install/source_windows#:~:text=on%20a%20GPU.-,Note%3A%20GPU%20support%20on%20native%2DWindows%20is%20only%20available%20for%202.10%20or%20earlier%20versions%2C%20starting%20in%20TF%202.11%2C%20CUDA%20build%20is%20not%20supported%20for%20Windows.%20For%20using%20TensorFlow%20GPU%20on%20Windows%2C%20you%20will%20need%20to%20build/install%20TensorFlow%20in%20WSL2%20or%20use%20tensorflow%2Dcpu%20with%20TensorFlow%2DDirectML%2DPlugin,-Download%20the%20TensorFlow). 

We recommend to use WSL on windows to enable GPU builds. Thanks!
