### ISSUE TITLE
tf 2.13 - tflite convert error  in topk when k is np.int64 

### ISSUE THREAD

**Issue by Chizkiyahu** [tensorflow/tensorflow#61452]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac and colab 
- TensorFlow installation (pip package or built from source): pip 
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.13

### 2. Code

Colab code [here](https://colab.research.google.com/drive/163eKr3nkQM4vRqCnFu5U9K3QhgA5PWog?usp=sharing)

### 3. Bug
tf 2.13 model with `tf.math.top_k` error in tflite convert 

tf 2.12 - **pass**
`k` is numpy.int64 - **fail** 
`k` is numpy.int32 - **pass**
`k` is python int - **pass**  

### 4. Error logs
```
---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
[<ipython-input-6-2ef9a00e0912>](https://localhost:8080/#) in <cell line: 2>()
      1 # error
----> 2 create_model_and_convert(k=np.int64(5))

9 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/convert.py](https://localhost:8080/#) in convert(model_flags, conversion_flags, input_data_str, debug_info_str, enable_mlir_converter)
    365               enable_mlir_converter,
    366           )
--> 367       raise converter_error
    368 
    369   return _run_deprecated_conversion_binary(

ConverterError: /usr/local/lib/python3.10/dist-packages/tensorflow/python/saved_model/save.py:1313:0: error: 'tf.TopKV2' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["PartitionedCall:", "PartitionedCall"]): called from
/usr/local/lib/python3.10/dist-packages/tensorflow/python/saved_model/save.py:1313:0: note: Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: failed while converting: 'main': 
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: TopKV2
Details:
	tf.TopKV2(tensor<?x29x7xf32>, tensor<i64>) -> (tensor<?x29x5xf32>, tensor<?x29x5xi32>) : {device = "", sorted = true}
```

**Comment by amishhaa** [comment]
you can try enabling TensorFlow kernels fallback using TensorFlow Select, which allows you to replace specific unsupported operations with TensorFlow kernels during the conversion. 
```python
import tensorflow as tf

def create_model_and_convert(k):
  
    converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
    converter.allow_custom_ops = True
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS,  
        tf.lite.OpsSet.SELECT_TF_OPS,    
    ]
    tflite_model = converter.convert()


    with open('model.tflite', 'wb') as f:
        f.write(tflite_model)

```

**Comment by Varsha-anjanappa** [comment]
Hi @Chizkiyahu ,

As amishha's suggested, please try enabling TensorFlow kernels fallback using TensorFlow Select. That would solve the issue.
Please find the [gist](https://colab.research.google.com/gist/Varsha-anjanappa/23d884383136c1c9ab33a50cc5fb35a0/61452.ipynb) for your reference and let us know if it works.

Thank you!!

**Comment by Chizkiyahu** [comment]
Hi @Varsha-anjanappa, 

Thanks for looking for this.
adding the `converter.allow_custom_ops = True`  solve the problem 
in my code, I solved that by converting to Python int in the tf model 
I assume that because is working in tf 2.12 with np.int64 and  with the default `converter` settings is good to fix that 
but this to your judgment

Thank you!!

**Comment by Chizkiyahu** [comment]
Hi @Varsha-anjanappa

To my understanding, the lable "TF 2.13" is more suitable than "TF 2.12" so it's easy to find 

Thank you!!

**Comment by Varsha-anjanappa** [comment]
Hi @Chizkiyahu ,

The topk op currently supports only unsigned int64. It does not support signed int, replacing np.int64 with np.uint64 should solve the problem in TF 2.13. Please refer the [documentation](https://www.tensorflow.org/mlir/tfl_ops#tfltopk_v2_tfltopkv2op) .

Please refer to the gist provided [here](https://colab.research.google.com/gist/Varsha-anjanappa/61a98ff6d04e6fe522c11a016a3016a7/61452.ipynb).

Thank you!!
