### ISSUE TITLE
How to get detailed information about the issue

### ISSUE THREAD

**Issue by pranavladkat** [tensorflow/tensorflow#61458]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.12.1

### Custom code

No

### OS platform and distribution

Linux Ubuntu 18.04

### Python version

3.8

### CUDA/cuDNN version

Cuda 11.8, Cudnn 8.9.2

### GPU model and memory

Nvidia A10

### Current behavior?

I'm getting following error while compiling the model with XLA:

```
OP_REQUIRES failed at xla_ops.cc:347 : INVALID_ARGUMENT: Trying to access resource Resource-3-at-0x55555dbbdfb0 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0
```

This issue is documented as XLA limitation [here](https://www.tensorflow.org/xla/known_issues#tfvariable_on_a_different_device), which seems reasonable, but the error message doesn't specify where this issue is coming from.

Is there any way to get more details on which variable is creating this issue?

### Standalone code to reproduce the issue

```shell
NA
```

**Comment by Varsha-anjanappa** [comment]
Hi @pranavladkat ,

As the [document](https://www.tensorflow.org/xla/known_issues#tfvariable_on_a_different_device) says, int32 types are not comprehensively supported on GPUs. As a workaround, please try int64.
Alternatively, you could choose to explicitly place int32 variables on CPU, or just not specify any device at all and let TensorFlow's device placement select GPU where appropriate.
Please let us know if this works.

Thank you!!
