### ISSUE TITLE
TFLite cross compile error --> fatal error: cpuid.h: No such file or directory

### ISSUE THREAD

**Issue by das-ankur** [tensorflow/tensorflow#61463]
I am trying to cross compile TFLite cpp code for ARM64 on ubuntu machine. After all the steps of installation I copied the cpp file to tflite_build  directory, I executed the following command:
![image](https://github.com/tensorflow/tensorflow/assets/43563075/c09083e9-a3fc-4124-a2d2-fab960b0503b)
After execution of some seconds I am getting the following error.
![image](https://github.com/tensorflow/tensorflow/assets/43563075/20615390-e05c-42d0-8c52-009df82f7098)
It will be really helpful if someone can help me to resolve the error.

**Comment by pjpratik** [comment]
Hi @das-ankur 

Can you please provide the steps you are following inorder to reproduce the issue?

Did you follow [build steps for arm64](https://www.tensorflow.org/lite/guide/build_cmake_arm#build_for_aarch64_arm64) and hitting the errors?

Thanks.
