### ISSUE TITLE
[Feature] The Heaviside step function as a activation function

### ISSUE THREAD

**Issue by mahimairaja** [tensorflow/tensorflow#61484]
Some of the implementations like Single Layer Perceptron needs discrete outputs like 0 or 1. Adding this could make the model building ease.

**Comment by AnanayVikramGupta** [comment]
I think a reason why this was left out is probably explained here:
https://stats.stackexchange.com/questions/271701/why-is-step-function-not-used-in-activation-functions-in-machine-learning

**Comment by AnanayVikramGupta** [comment]
Hi, needed help creating a PR with the upstream repo from my fork - not sure which branch to create the PR to. Any help/ resources would be appreciated

**Comment by tilakrayal** [comment]
@mahimairaja,
Thank you for the request. Could you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thank you!

@AnanayVikramGupta,
Could you please have a look at this **CONTRIBUTING.md** file for the process of contribution in the tensorflow repository.
https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md

Thank you!
