### ISSUE TITLE
coreml deleagate not support ResizeBilinear layer

### ISSUE THREAD

**Issue by mengran1234** [tensorflow/tensorflow#61486]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.10 or 2.11

### Custom code

Yes

### Bazel version

no 

### GCC/compiler version

no

### CUDA/cuDNN version

no

### GPU model and memory

111

### Current behavior?

i run coreml delegate on iphone 12. The tflite model has ResizeBilinear layer ( align_coreners == false , half_pixel_center ==true),
but I find the tflite code following  (coreml_delegate.mm):
// For most ops, only version 1 is supported.
  if (registration->version > 1) {
     return false;
}
ResizeBilinear layer is not supported by ANE because of version >1.

But if ResizeBilinear layer ( align_coreners == false , half_pixel_center ==false) , it is supported by ANE engine.So the performance will be improved

### Standalone code to reproduce the issue

```shell
my question is ,
ResizeBilinear layer ( align_coreners == false , half_pixel_center ==true) can be supported by ANE?
this format is common during training model
thank you!
```

**Comment by sushreebarsa** [comment]
@mengran1234 As per the documentation [here ](https://www.tensorflow.org/lite/performance/coreml_delegate)in coreml_delegate, the ResizeBilinear is a supported ops. Could you please let us know if this is what you are looking for? 
Thank you!

**Comment by mengran1234** [comment]
> @mengran1234 As per the documentation [here ](https://www.tensorflow.org/lite/performance/coreml_delegate)in coreml_delegate, the ResizeBilinear is a supported ops. Could you please let us know if this is what you are looking for? Thank you!

yes
but the documentation is very simple。
![A3C10F1D-9EFF-484b-879A-2A2DDE4A741D](https://github.com/tensorflow/tensorflow/assets/87115287/21bab2d9-9578-4781-943e-a35d100a2a27)

**Comment by mengran1234** [comment]
align_corners = false , half_pixel_centers = true 
this  configuration parameter is common， how coreml can support it ?

**Comment by pkgoogle** [comment]
Hi @mengran1234, the current version is https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/coreml/coreml_delegate.mm, which seems different than your code snippet. Can you try with the latest release and let us know if it resolves your issue? Also I am having trouble understanding your issue. Does your code work? Does it work but your performance doesn't match what you expected? If so, please tell us how. Thanks for any additional information you can provide.

**Comment by mengran1234** [comment]
My code can run normally.
But  performance doesn't match what i expected because of ResizeBilinear layer.
the code is:
 // For most ops, only version 1 is supported.
  if (registration->version > 1) {
    switch (registration->builtin_code) {
      case kTfLiteBuiltinDepthwiseConv2d:
        if (registration->version > 2) return false;
        break;
      // FullyConnected without bias is supported starting from version 6.
      case kTfLiteBuiltinFullyConnected:
        if (registration->version > 6) return false;
        break;
      default:
        return false;
    }
  }
If ResizeBilinear (align_corners = false , half_pixel_centers = true) ,
above code will run to "
 default:
        return false;
"
so coreml  do not support this layer (meet the conditions registration->version > 1)

**Comment by pkgoogle** [comment]
Ok thanks for the information, we'll consider this a feature request then, @yishuangP can you please take a look?

**Comment by mengran1234** [comment]
do you know 
// For most ops, only version 1 is supported.
if (registration->version > 1) {

above where is the value of registration->version from? how it defined

**Comment by gaikwadrahul8** [comment]
Hi, @mengran1234 

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/158


Let us know if you have any questions. Thanks.
