### ISSUE TITLE
ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by tellts** [tensorflow/tensorflow#61490]
Windows 10 Russian locale (utf-8) Microsoft Windows [Version 10.0.19045.3208]. Python 3.10.8 (i tried with other versions too). Tensorflow-cpu (I do not see the version in Paycharm, I installed it today. And before, without Paycharm, I tried several other versions and got the same error.).

Windows PowerShell                                          
Copyright (C) Microsoft Corporation. All rights reserved.   
                                                            
Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\admin\PycharmProjects\pythonProject3> python 
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.                          
>>> import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python3108\lib\site-packages\tensorflow\__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Python3108\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\Python3108\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "C:\Python3108\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 14, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "C:\Python3108\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 14, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
ValueError: source code string cannot contain null bytes

**Comment by tilakrayal** [comment]
@tellts,
Could you please provide the tensorflow version you are trying and also this issue doesn't look like the issue from the tensorflow side. 

Also this kind of error emerges from your python interpreter. So the best solution is to set your python interpreter in your project env directory or set the interpreters virtual env properly using your IDE's interpreter configuration. Thank you!

**Comment by tellts** [comment]
I've tried different versions of Tensorflow, but now I've uninstalled them all. I also tried with a freshly installed Python so that there are no conflicts with other applications. I also tried also the latest version which is Paycharm. I mean all this in relation to the version with CPU.

**Comment by tilakrayal** [comment]
@tellts,
Without the reproducible code, it would be difficult for us to debug the issue. In order to expedite the trouble-shooting process, could you please provide a minimal code snippet and the TensorFlow version you are using.

**Comment by tilakrayal** [comment]
Closing this as stale. Please reopen if this is still a valid request. Thank you!
