### ISSUE TITLE
Tensorflowlite flex delegate not loaded automatically when interpreter created even though tensorflowlite_flex.dll provided. (C++ on windows)

### ISSUE THREAD

**Issue by pcoramasionwu** [tensorflow/tensorflow#61495]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.11

### Custom code

No

### OS platform and distribution

Windows 10

### Bazel version

5.3

### GCC/compiler version

MSVC 16 (2019)

### Current behavior?

When running an application that uses a model that uses select ops, if I provide tensorflowlite.dll.if.lib and tensorflowlite_flex.dll.if.lib as Linker dependencies and place both tensorflowlite.dll and tensorflowlite_flex.dll in the application folder, the flex delegate is not loaded before inference.

When invoke is called on the interpreter we get the error message:
ERROR: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.

### Standalone code to reproduce the issue

```shell
The issue is reproducible using the tensorflow test code:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/model_flex_test.cc

---------------

The problem is the flex delegate is not automatically applied successfully here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/core/interpreter_builder.cc#L179

This is because nullptr is being passed to getProcAddress() rather than a handle to tensorflowlite_flex.dll here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/shared_library.h#L42

---------------

When I modify the tensorflow sources to pass a handle to tensorflowlite_flex.dll, things work as expected
```

### Relevant log output

```shell
ERROR: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
```

**Comment by pkgoogle** [comment]
Hi @pcoramasionwu, thanks for reporting the issue.

I'm not quite sure what you mean by "if I provide tensorflowlite.dll.if.lib and tensorflowlite_flex.dll.if.lib as Linker dependencies", where are these files coming from? and how did you provide them as Linker dependencies? If you are using command prompt/power shell, please include exact commands. Similarly, what are the exact steps you use to produce the tensorflowlite.dll and tensorflowlite_flex.dll files? Thanks for any additional information you can provide, that will help us resolve your issue faster.

**Comment by pcoramasionwu** [comment]
Hi @pkgoogle 

**tensorflowlite.dll.if.lib** and **tensorflowlite.dll** are generated by using the following command at the root of the local tensorflow repo on a windows machine:

`bazel build --explain=file_tflite.txt --verbose_explanations --verbose_failures --subcommands //tensorflow/lite:tensorflowlite`

**tensorflowlite_flex.dll.if.lib** and **tensorflowlite_flex.dll** are produced by the follow command: 

`bazel build --explain=file_flex.txt --verbose_explanations --verbose_failures --subcommands tensorflow/lite/delegates/flex:tensorflowlite_flex`

the .libs are added as linker dependencies within visual studio (https://learn.microsoft.com/en-us/cpp/build/reference/dot-lib-files-as-linker-input?view=msvc-170#to-add-lib-files-as-linker-input-in-the-development-environment)

**Comment by pkgoogle** [comment]
Hi @nutsiepully, can you please take a look? Thanks.

**Comment by rishik1001** [comment]
> ### Issue type
> Bug
> 
> ### Have you reproduced the bug with TensorFlow Nightly?
> No
> 
> ### Source
> source
> 
> ### TensorFlow version
> tf 2.11
> 
> ### Custom code
> No
> 
> ### OS platform and distribution
> Windows 10
> 
> ### Mobile device
> _No response_
> 
> ### Python version
> _No response_
> 
> ### Bazel version
> 5.3
> 
> ### GCC/compiler version
> MSVC 16 (2019)
> 
> ### CUDA/cuDNN version
> _No response_
> 
> ### GPU model and memory
> _No response_
> 
> ### Current behavior?
> When running an application that uses a model that uses select ops, if I provide tensorflowlite.dll.if.lib and tensorflowlite_flex.dll.if.lib as Linker dependencies and place both tensorflowlite.dll and tensorflowlite_flex.dll in the application folder, the flex delegate is not loaded before inference.
> 
> When invoke is called on the interpreter we get the error message: ERROR: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
> 
> ### Standalone code to reproduce the issue
> ```shell
> The issue is reproducible using the tensorflow test code:
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/model_flex_test.cc
> 
> ---------------
> 
> The problem is the flex delegate is not automatically applied successfully here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/core/interpreter_builder.cc#L179
> 
> This is because nullptr is being passed to getProcAddress() rather than a handle to tensorflowlite_flex.dll here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/shared_library.h#L42
> 
> ---------------
> 
> When I modify the tensorflow sources to pass a handle to tensorflowlite_flex.dll, things work as expected
> ```
> 
> ### Relevant log output
> ```shell
> ERROR: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
> ```

Did you get any solution for this?

**Comment by gaikwadrahul8** [comment]
Hi, @pcoramasionwu 

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/157

Let us know if you have any questions. Thanks.
