### ISSUE TITLE
summary name of the new `summary` module

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#6150]
With the new `tf.summary` module, the name shown in tensorboard has to be equal to the summary op in the graph.
As a result, the name shown in tensorboard cannot be the same as any existing op in the graph.
This can create a bit of problem. Before this change, I could have some op named `loss` and the summary of its output also named `loss`, which is very consistent and easy to play with -- I can just look for the name of the tensor in tensorboard.
Now it looks like I have to add a prefix/suffix to everything because they cannot use the same name. Otherwise I got `loss_1` in tensorboard which is confusing especially to new users.

Is there some changes that could be done to the new `summary` module that keeps the nice old feature?

**Comment by ppwwyyxx** [comment]
I would really like to have a way to customize the tag name shown in tensorboard. 
I could send a PR by simply adding an optional keyword argument to all the `tf.summary.something` functions. Does that sound like an acceptable solution or are there any design concerns?

**Comment by yaroslavvb** [comment]
This request came up on SO [as well](http://stackoverflow.com/questions/41027247/tensorflow-0-12-0rc-tf-summary-scalar-error-using-placeholders), @danmane for comment

**Comment by danmane** [comment]
We intend to add a "display_name" option to the summaries that controls how it displays in the frontend. 

A pull request would probably look like: add some metadata to the summary op that appears in the NodeDef in the graph, have the EventAccumulator read that metadata when it parses the graph definition, and then pass the metadata along with the summary info to the TensorBoard frontend. It's not trivial. @ppwwyyxx if you want to take this on we can discuss it in more depth.

**Comment by ppwwyyxx** [comment]
Great! If you have that on the TODO list maybe I should leave it to you.
One question: isn't this just the old "tag" field that was in Summary::Value that's used by the old summary module? Why not use that field?

**Comment by fvisin** [comment]
Is there any advancement on this? It is really annoying to get duplicated summaries in Tensorboard in the multi-GPU setting.

**Comment by dandelionmane** [comment]
Migrating this issue to tensorflow/tensorboard
