### ISSUE TITLE
On-Device training for LSTM or GRU Model 

### ISSUE THREAD

**Issue by Chris0215** [tensorflow/tensorflow#61513]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): web
- TensorFlow installed from (source or binary): colab
- TensorFlow version (or github SHA if from source):colab

Hi I’m new to tensorflow and I’m trying to make LSTM or GRU model to be enable to re-train on-device(Android) with tabular data (mostly customer interaction).

I’m referencing these examples
[On-Device Training 1](https://www.tensorflow.org/lite/examples/on_device_training/overview)

This is an example of a CNN, but not able to understand how can I enable on-device training for lstm or gru model.
Are there any examples for reference? Thanks

**Comment by pjpratik** [comment]
Hi @Chris0215 

The examples covering other on-device training use cases is on roadmap.

On Android, TensorFlow Lite on-device training can be performed using either Java or C++ APIs. The train function can be invoked using TensorFlow Lite’s [runSignature](https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/examples/on_device_training/overview.ipynb#scrollTo=jBYb5JEnPeOR) method by specifying the name of the signature (‘train’) and Similarly, we can invoke inference using the model’s ‘infer’ signature.

Please refer this [blog](https://blog.tensorflow.org/2021/11/on-device-training-in-tensorflow-lite.html) on OD training for insight on implementation.

Thanks.
