### ISSUE TITLE
`numpy()` making copies with model parameters

### ISSUE THREAD

**Issue by mattbarrett98** [tensorflow/tensorflow#61524]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.12.0

### Custom code

Yes

### Current behavior?

When calling `numpy()` here no copies are made:
```python
import os, psutil
import tensorflow as tf

process = psutil.Process(os.getpid())
x = tf.random.normal((1, 300000))
print(process.memory_info().rss / 1e9). # 0.48
npy = x.numpy()
print(process.memory_info().rss / 1e9). # 0.48
```
However in the below example the increase in memory implies a copy is being made when calling `numpy()` on a model variable, is there any reason for this?

### Standalone code to reproduce the issue

```shell
import os, psutil
import tensorflow as tf

class TestKerasLinear(tf.keras.Model):
    def __init__(self, out_size):
        super(TestKerasLinear, self).__init__()
        self._linear = tf.keras.layers.Dense(out_size)

    def build(self, input_shape):
        super(TestKerasLinear, self).build(input_shape)

    def call(self, x):
        return self._linear(x)

tf_module = TestKerasLinear(1000)
tf_module.build((None, 300000))

process = psutil.Process(os.getpid())
print(process.memory_info().rss / 1e9). # 1.68

npy = tf_module.variables[0].numpy()

print(process.memory_info().rss / 1e9)  # 2.88
```

**Comment by JW1992** [comment]
Hi Matt, I think this is working as expected, see this discussion from a few years ago: https://github.com/tensorflow/tensorflow/issues/33254
