### ISSUE TITLE
tf.math.floormod performance issue

### ISSUE THREAD

**Issue by JinJiefeng** [tensorflow/tensorflow#61520]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

v2.13.0-rc2-7-g1cb1a030a62 2.13.0

### Custom code

No

### OS platform and distribution

20.04.1-Ubuntu

### Python version

3.8.10

### CUDA/cuDNN version

CUDA Version: 11.6

### GPU model and memory

Tesla V100

### Current behavior?

Dear Tensorflow support, 

I found that the tf.math.floormod function is very slow for the tensors of float dtype, even if the size of the tensor is very small, in my case, only 6. The platform is a powerful server with GPU acceleration, but the performance is much slower than an old laptop.

Output on server, 20.04.1-Ubuntu, GPU accelerated, TensorFlow version 2.13.0

> tf.math.floormod float cost: 1.0610415935516357 seconds
> tf.math.floormod int cost: 0.005458354949951172 seconds

Output on laptop, Windows 10, cpu-only, TensorFlow version 2.10.0 :

> tf.math.floormod float cost: 0.002992391586303711 seconds
> tf.math.floormod int cost: 0.006021261215209961 seconds

Could you please check this issue? 
Thanks!

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import time
PI = 3.141592653589793

random_tensor = tf.random.uniform(shape=(1, 6), minval=-PI*2, maxval=PI*2, dtype=tf.float32)
start_time = time.time()
random_tensor = tf.math.floormod(random_tensor+PI, 2*PI)-PI
print(f"tf.math.floormod float cost: {time.time() - start_time} seconds")

random_tensor = tf.random.uniform(shape=(1, 6), minval=-200, maxval=200, dtype=tf.int32)
start_time = time.time()
random_tensor = tf.math.floormod(random_tensor+100, 2*100)-100
print(f"tf.math.floormod int cost: {time.time() - start_time} seconds")
```

**Comment by tilakrayal** [comment]
@JinJiefeng,
I tried to execute the mentioned code on latest tensorflow v2.15 and observed that the output for both [GPU](https://colab.research.google.com/gist/tilakrayal/a56345f3301d4a0b4c357c38e21c6e67/untitled1872.ipynb) and [CPU](https://colab.research.google.com/gist/tilakrayal/6953a05fcd5d76f12a689787d29152d4/untitled1873.ipynb) are not much difference for **tf.math.floormod** float and int. Kindly find the gist of it here. Thank you!
