### ISSUE TITLE
TensorFlow profiler running into OOM issue on GPU

### ISSUE THREAD

**Issue by ndeepesh** [tensorflow/tensorflow#61526]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

TF 2.11, TF 2.4

### Custom code

No

### OS platform and distribution

Red Had

### Python version

3.10

### CUDA/cuDNN version

11.2

### Current behavior?

Running TensorFlow profiler for longer than 10 second period results into OOM error, crashes the tf inference process and the profiler returns DEADLINE_EXCEEDED. Is there anyway to limit the sampling rate or way to reduce the amount of information being collected to avoid crashing the process?

Here is the code that I run:
tensorflow_profiler.experimental.client("grpc://localhost:3222", "profiles", 30000)

### Standalone code to reproduce the issue

```shell
tensorflow_profiler.experimental.client("grpc://localhost:3222", "profiles", 30000)
```

### Relevant log output

```shell
DEADLINE_EXCEEDED
```

**Comment by tilakrayal** [comment]
@ndeepesh,
Could you please provide the complete standalone code to reproduce the issue and it helps us to analyse the issue in an effective way. Thank you!

**Comment by ndeepesh** [comment]
Hi @tilakrayal 
Any model on GPU with above code should be good for reproducing the issue. Is there a sampling parameter that can be introduced so that not all events are captured?

**Comment by tilakrayal** [comment]
@ndeepesh,
Without the reproducible code, it would be difficult for us to debug the issue. In order to expedite the trouble-shooting process, could you please provide a minimal code snippet you are using. Thank you!
