### ISSUE TITLE
dynamic variants of attention_decoder and embedding_attention_decoder

### ISSUE THREAD

**Issue by ssampang** [tensorflow/tensorflow#6154]
I've been following @alrojo's PR(#4686) for the `tf.contrib.seq2seq.dynamic_rnn_decoder`. I recently had to customize `tf.nn.seq2seq.embedding_attention_decoder` and `tf.nn.seq2seq.attention_decoder` with while loops for a personal project, so I'd be happy to help write `attention` and `embedding_attention` decoder functions for use with `tf.contrib.seq2seq.dynamic_rnn_decoder` if that would be helpful. I'm unclear on whether this is already being worked on, since I see discussion of a `rnn_decoder_attention` function in #4761, but it was a commit which followed the old structure of `tf.contrib.seq2seq`.

**Comment by alrojo** [comment]
Hi @ssampang 

I am currently working on finalizing a attention decoder function with the proper `kernel_tests`, I hope to submit it next week.

**Comment by tttwwy** [comment]
Hi @alrojo , is there any progress in the attention decoder? 
thank you
