### ISSUE TITLE
UnicodeDecodeError when loading model from a path with Chinese characters.

### ISSUE THREAD

**Issue by TimLai666** [tensorflow/tensorflow#61550]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.13.0

### Custom code

Yes

### OS platform and distribution

Windows 11 22h2

### Python version

3.11

### Current behavior?

Current behavior:
When I attempt to use tf.keras.models.load_model to load a saved model from a folder path that contains Chinese characters, TensorFlow throws a UnicodeDecodeError. This suggests that TensorFlow may not be parsing Chinese characters correctly in the folder path.

Expected behavior:
I expect tf.keras.models.load_model to be able to load the model correctly from any folder path, regardless of whether it contains Chinese characters or not. If there are limitations on the folder name, it should be clearly documented or provide a more descriptive error message.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

# Create a simple model
model = tf.keras.models.Sequential([tf.keras.layers.Dense(1, input_shape=(1,))])
model.compile(optimizer='adam', loss='mse')
model.save('模型/')  # '模型' is Chinese for 'model'

# Now, try to load the saved model
loaded_model = tf.keras.models.load_model('模型/')
```

### Relevant log output

```shell
Traceback (most recent call last):
...
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 27: invalid start byte
```

**Comment by sushreebarsa** [comment]
@TimLai666 While reproducing the issue, I have faced the following outcome;
```
WARNING:absl:Found untraced functions such as _update_step_xla while saving (showing 1 of 1). These functions will not be directly callable after loading.
```
Please find the [gist ](https://colab.research.google.com/gist/sushreebarsa/3f9711adeff619850ed50605cf61ae9a/61550.ipynb)and confirm the results of TF v2.12, 2.13 and tf-nightly as well. 
Thank you!
