### ISSUE TITLE
Update tf.zeros_initializer method

### ISSUE THREAD

**Issue by danielwatson6** [tensorflow/tensorflow#6155]
The `tf.zeros_initializer` method has an unnecessary argument, asking for the tensor shape. See [tensorflow documentation](https://www.tensorflow.org/versions/r0.12/api_docs/python/state_ops.html#zeros_initializer). The `tf.ones_initializer` method, which is essentialy equivalent in functionality, does not have this argument.

As a sidenote, the method `tf.constant_initializer` (see [documentation](https://www.tensorflow.org/versions/r0.12/api_docs/python/state_ops.html#constant_initializer)) also doesn't have this argument and serves the same purpose. In fact, if no keyword args are provided, it will behave as the `zeros_initializer` is intended to.

**Comment by apollo-time** [comment]
Yes, I try slim.overfeat net but occur error with tf.zeros_initializer .
I resolved it using by constant_initializer.
Thanks.
