### ISSUE TITLE
Avoid partially saved ckpt from preempted device (e.g. TPU)

### ISSUE THREAD

**Issue by edwardyehuang** [tensorflow/tensorflow#61552]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf.2.11

### Custom code

Yes

### Current behavior?

I accidentally discovered from a TPU preemption that my ckpt cannot be used to resume training (the preemption occurs during the process of saving ckpt). The error is that some weights cannot be matched. This phenomenon is happening for the first time and has never happened before.

### Standalone code to reproduce the issue

```shell
It is very hard to reproduce because it must be preemption while saving the ckpt.
```

**Comment by tilakrayal** [comment]
@edwardyehuang,
Could you please provide the complete standalone code to reproduce the issue and it helps us to analyse the issue in an effective way. Thank you!

**Comment by edwardyehuang** [comment]
> @edwardyehuang, Could you please provide the complete standalone code to reproduce the issue and it helps us to analyse the issue in an effective way. Thank you!

As I said above, as an individual user outside of Google, I cannot manually seize a TPU node, so it is impossible to provide an independent reproduction code.
By the way, I've only had this problem happen twice (I've experienced thousands of preemptions).
