### ISSUE TITLE
Crash when running tensorflow.python.framework.importer._GatherReturnElements

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#61570]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.13.0

### Custom code

Yes

### OS platform and distribution

22.04

### Python version

3.9

### CUDA/cuDNN version

nvidia-cudnn-cu11==8.6.0.163, cudatoolkit=11.8.0

### Current behavior?

Due to None argument

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.framework import importer
try:
  arg_0_0 = "Placeholder:0"
  arg_0_1 = "add:0"
  arg_0 = [arg_0_0,arg_0_1,]
  arg_1 = None
  arg_2 = None
  out = importer._GatherReturnElements(arg_0,arg_1,arg_2,)
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
2023-08-14 21:23:49.892933: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Segmentation fault
```
```

**Comment by SuryanarayanaY** [comment]
@dmc1778 ,

I have tested the code with tf-nightly(2.15.0-dev20230813) and it fails with **segmentation fault**. Attached logs below for reference.

```
(tf2.13) suryanarayanay@surya-ubuntu20:~$ python 61570_vm.py
2023-08-16 06:32:05.242433: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9498] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-08-16 06:32:05.242588: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-08-16 06:32:05.242678: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-08-16 06:32:05.260269: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-16 06:32:06.805199: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /home/suryanarayanay/miniconda3/envs/tf2.13/lib/python3.11/site-packages/tensorflow/python/ops/distributions/distribution.py:259: ReparameterizationType.__init__ (from tensorflow.python.ops.distributions.distribution) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
WARNING:tensorflow:From /home/suryanarayanay/miniconda3/envs/tf2.13/lib/python3.11/site-packages/tensorflow/python/ops/distributions/bernoulli.py:165: RegisterKL.__init__ (from tensorflow.python.ops.distributions.kullback_leibler) is deprecated and will be removed after 2019-01-01.
Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
2.15.0-dev20230813
Segmentation fault (core dumped)
```

Since segmentation fault is a vulnerability and it exists in tf-nightly, please report the security related issues through proper channel as mentioned in [SECURITY.md](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

Thanks!

**Comment by mihaimaruseac** [comment]
Please always check with the latest version.

Please never mention security issues in public. It is not the first time this behavior occured.

**Comment by dmc1778** [comment]
> Please always check with the latest version.
> 
> Please never mention security issues in public. It is not the first time this behavior occured.

Segfault exists on 2.13.0

**Comment by LakshmiKalaKadali** [comment]
Hi @dmc1778 ,

It seems multiple issues raised on different internal APIs. It is recommended not to use these internal APIs instead you can use high level public APIs like ` tf.saved_model.load(), tf.compat.v1.import_graph_def(), or tf.function` to work with models or graphs. 

The function `_GatherReturnElements(requested_return_elements, graph, results)` will take the arguments `requested_return_elements, graph, results` but you are passing different arguments, which are not appropriate. Please check [here](https://github.com/tensorflow/tensorflow/blob/f85732921f2f7db2b1070e26df3d054176ea9219/tensorflow/python/framework/importer.py#L318) .


Thanking You
