### ISSUE TITLE
installation issues on Ubuntu 16.04 GPU version

### ISSUE THREAD

**Issue by gaoyuze** [tensorflow/tensorflow#6158]
Dear developers:
I encountered one error with fine setting configuration
All the settings is right, and it said that 

                                           all external dependencies fetch successful 
                                           configuration finished 

all the thing right until I generate the pip_package

(bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package), 

process like below:

`yuze@nlp:~/tensorflow$ ./configure 
~/tensorflow ~/tensorflow
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] n
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Using python library path: /usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] y
OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 
Please specify which C++ compiler should be used as the host C++ compiler. [Default is /usr/bin/g++]: 
Please specify which C compiler should be used as the host C compiler. [Default is /usr/bin/gcc]: 
Please specify the location where ComputeCpp 1.2 is installed. Refer to README.md for more details. [Default is /usr/local/computecpp]: 
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
......
INFO: All external dependencies fetched successfully.
Configuration finished

yuze@nlp:~/tensorflow$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
INFO: Found 1 target...
ERROR: missing input file '@local_config_sycl//sycl:LICENSE.text'.
ERROR: /home/yuze/.cache/bazel/_bazel_yuze/540cd99ea4fee1092020a833f635df2b/external/farmhash_archive/BUILD:13:1: C++ compilation of rule '@farmhash_archive//:farmhash' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 37 argument(s) skipped): com.google.devtools.build.lib.shell.AbnormalTerminationException: Process terminated by signal 15.
ERROR: /home/yuze/tensorflow/tensorflow/tools/pip_package/BUILD:105:1: //tensorflow/tools/pip_package:build_pip_package: missing input file '@local_config_sycl//sycl:LICENSE.text'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/yuze/tensorflow/tensorflow/tools/pip_package/BUILD:105:1 1 input file(s) do not exist.
INFO: Elapsed time: 3.485s, Critical Path: 1.17s
`
can you kindly tell me where is wrong?

Thank you!

**Comment by martinwicke** [comment]
Yifei, I think this is a new license? Maybe a missing dependency?

**Comment by yifeif** [comment]
I see the issue for when OpenCL support is enabled, will send a PR.

**Comment by benoitsteiner** [comment]
I think I fixed it in my last set of OpenCL enhancements (https://github.com/tensorflow/tensorflow/pull/6161)

**Comment by yifeif** [comment]
I see. Looks good. Let me close my PR.

**Comment by gaoyuze** [comment]
Thank you, all lovely guys, the installation is OK now, //smile 

But  When I finished installation and test it, it occurs an error saying Device mapping : no known device

it works out like below:

`
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
......
INFO: All external dependencies fetched successfully.
Configuration finished

yuze@nlp:~/tensorflow$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
INFO: Found 1 target...
INFO: From Compiling external/protobuf/python/google/protobuf/pyext/message_factory.cc:

...................................................................................................................................

INFO: From Compiling tensorflow/contrib/rnn/kernels/lstm_ops_gpu.cu.cc:
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 1120.235s, Critical Path: 852.79s

yuze@nlp:~/tensorflow$ cd ../
yuze@nlp:~$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> with tf.device('/cpu:0'):
...   a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3], name='a')
...   b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2], name='b')
...   c = tf.matmul(a, b)
... 
>>> sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
Device mapping: no known devices.
I tensorflow/core/common_runtime/direct_session.cc:255] Device mapping:

`

And I am sure my CUDA and cuDNN is all right, and the path environment has no problem. But where may this error occur ?

Thanks again.

**Comment by gunan** [comment]
1- In your logs, I do not see you installing the pip package you just built using `pip install`
2- You also enabled "OpenCL" we have not tested the configuration where both opencl and cuda are enabled. It is quite possible they are interacting in an unexpected way.
3- Also, what is the reason for not using the GPU pip packages we provide?

Also, I think the tail of your log is missing, it might contain more information.

**Comment by gaoyuze** [comment]
@gunan  Hi~ dear gunan, thank you very much, I didn't know the pip packages you provide, it is quite easy to setup. And now, my tensorflow with GPU is running.  //Applause
