### ISSUE TITLE
Train Simple Audio Recognition - TinyML

### ISSUE THREAD

**Issue by siddarthnandy** [tensorflow/tensorflow#61590]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.12.0

### Custom code

Yes

### OS platform and distribution

Windows 11

### Python version

3.10.12

### Current behavior?

**Issue Report** - Error in Training Audio Recognition Model

**Description**:

I am trying to train a simple audio recognition model as described in the book "TinyML." I am using Google Colab to train the model. However, I encountered errors during both the installation of dependencies and the training process.

**Error during Install Dependencies**:

When attempting to install dependencies using the command 

!pip uninstall -y tensorflow tensorflow_estimator tensorboard
!pip install -q tf-estimator-nightly==1.14.0.dev2019072901 tf-nightly-gpu==1.15.0.dev20190729

 I encountered the following error:

ERROR: Could not find a version that satisfies the requirement tf-nightly-gpu==1.15.0.dev20190729 (from versions: 2.12.0)
ERROR: No matching distribution found for tf-nightly-gpu==1.15.0.dev20190729
Error during Training - ModuleNotFoundError:

**Error to Begin Training**:

Upon running the training script with TensorFlow in the "Begin Training" Section, I received the following error:

Traceback (most recent call last):
  File "/content/tensorflow/tensorflow/examples/speech_commands/train.py", line 81, in <module>
    import input_data
  File "/content/tensorflow/tensorflow/examples/speech_commands/input_data.py", line 35, in <module>
    from tensorflow.contrib.framework.python.ops import audio_ops as contrib_audio
ModuleNotFoundError: No module named 'tensorflow.contrib'

**Observations**:

I suspect that these errors are occurring because the code provided in the book is intended for TensorFlow 1.15, while I am using TensorFlow 2.12.0. Since TensorFlow 1.15 is no longer supported. Not sure how I can resolve this. Please help me to fix this issue.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1t2QMMiCdIxP3xnoNyiz9FjmPmbrF0_iD?usp=sharing
```

### Relevant log output

```shell
ERROR: Could not find a version that satisfies the requirement tf-nightly-gpu==1.15.0.dev20190729 (from versions: 2.12.0)
ERROR: No matching distribution found for tf-nightly-gpu==1.15.0.dev20190729





Traceback (most recent call last):
  File "/content/tensorflow/tensorflow/examples/speech_commands/train.py", line 81, in <module>
    import input_data
  File "/content/tensorflow/tensorflow/examples/speech_commands/input_data.py", line 35, in <module>
    from tensorflow.contrib.framework.python.ops import audio_ops as contrib_audio
ModuleNotFoundError: No module named 'tensorflow.contrib'
```

**Comment by siddarthnandy** [comment]
@petewarden 
@dansitu

**Comment by tilakrayal** [comment]
@siddarthnandy,
**tensorflow.contrib** is not available in tensorflow v2.x. Removed the old `tf.contrib.layers` and replace them with [TF Slim](https://github.com/google-research/tf-slim) symbols.

Could you please take a look at this official migration doc link which refers to the Migrate from TensorFlow 1.x to TensorFlow 2.
https://www.tensorflow.org/guide/migrate

Thank you!

**Comment by siddarthnandy** [comment]
It is not straight forward on how to do this migration. Need some help. Thanks

**Comment by siddarthnandy** [comment]
Has anyone else already completed the migration that I can use

**Comment by siddarthnandy** [comment]
Need some help. Thanks. Still not resolved

**Comment by siddarthnandy** [comment]
Need some help. Thanks. Still not resolved

**Comment by siddarthnandy** [comment]
Need some help. Thanks. Still not resolved

**Comment by siddarthnandy** [comment]
This issue is not resolved. Any help would be grateful.

**Comment by siddarthnandy** [comment]
will try it thanks

**Comment by pjpratik** [comment]
Hi @siddarthnandy 

Did you get a chance to try the example?

Feel free to close the issue if it is resolved.

Thanks.

**Comment by siddarthnandy** [comment]
fixed thanks.
