### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow-compression~=2.12.0 (from versions: none)

### ISSUE THREAD

**Issue by xueyee0802** [tensorflow/tensorflow#61596]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

fail

### Custom code

Yes

### Python version

3.9.12

### Current behavior?

I try to pip intsall tensorflow-federated it fail, so i build it on source, i pip install --requirement "requirements.txt" then happened this error. can i know how to solve this problem?

### Standalone code to reproduce the issue

```shell
-
```

### Relevant log output

```shell
ERROR: Could not find a version that satisfies the requirement tensorflow-compression~=2.12.0 (from versions: none)
ERROR: No matching distribution found for tensorflow-compression~=2.12.0
```

**Comment by SuryanarayanaY** [comment]
Hi @xueyee0802 ,

AFAIK , `tensorflow-compression` binaries available only for 2.13 version onwards. Could you please refer to Pypi source [here](https://pypi.org/project/tensorflow-compression/#files).

Please try importing 2.13 version. Also for any further bugs please report concern repo attached [here](https://github.com/tensorflow/compression/issues).Thanks!

**Comment by xueyee0802** [comment]
> Hi @xueyee0802 ,
> 
> AFAIK , `tensorflow-compression` binaries available only for 2.13 version onwards. Could you please refer to Pypi source [here](https://pypi.org/project/tensorflow-compression/#files).
> 
> Please try importing 2.13 version. Also for any further bugs please report concern repo attached [here](https://github.com/tensorflow/compression/issues).Thanks!

Hi @SuryanarayanaY,
I tried pip intsall tensorflow_compression-2.13.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl, to get the 2.13 version, but i getting this error.
**ERROR: tensorflow_compression-2.13.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl is not a supported wheel on this platform.**

**Comment by SuryanarayanaY** [comment]
Hi @xueyee0802 ,

Please use just `pip install tensorflow-compression` and it will install latest version of `tensorflow-compression` based on the platform you are using.

**Comment by xueyee0802** [comment]
> pip install tensorflow-compression
Hi @SuryanarayanaY,

I tried before pip install tensorflow-compression, there are some error.

<img width="805" alt="image" src="https://github.com/tensorflow/tensorflow/assets/142464953/fa6c0dec-31a9-4ebc-8527-8ec7e8b2999f">
