### ISSUE TITLE
Cannot type "I Accept" to extract from hexagon_nn_skel

### ISSUE THREAD

**Issue by octavflorescu** [tensorflow/tensorflow#61606]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

hexagon_nn_skel_v1.20.0.1

### Custom code

No

### OS platform and distribution

Android

### Mobile device

Android

### Current behavior?

Same as here https://github.com/tensorflow/tensorflow/issues/61378, running the ./tflite_hexagon_nn_skel_v1.20.0.1.run instantly prints:
```
license. Extraction aborted.
./extract.sh[5]: read: -p: no coprocess
Aborting extraction.. Done
```
Without giving time to write "I ACCEPT".
Neither does --accept option work.

### Standalone code to reproduce the issue

```shell
adb push tflite_hexagon_nn_skel_v1.20.0.1.run /data/local/tmp
adb shell
cd /data/local/tmp
chmod +x tflite_hexagon_nn_skel_v1.20.0.1.run
./tflite_hexagon_nn_skel_v1.20.0.1.run [--accept]
```

### Relevant log output

```shell
...
Limited or its designated affiliate. LICENSEE shall be solely responsible to
obtain such separate license from Apical Limited. The provision or license of a
PKLA Product Kit to LICENSEE does not convey any license or other right under
any patents of QUALCOMM Incorporated or SnapTrack, Inc.


Type "I ACCEPT" if you agree to the terms of the license: You didn't accept the
license. Extraction aborted.
./extract.sh[5]: read: -p: no coprocess
Aborting extraction.. Done
HNNTH:/data/local/tmp $
```

**Comment by pjpratik** [comment]
Hi @octavflorescu 

Did you get any prompt after `Type "I ACCEPT" if you agree to the terms of the license: You didn't accept the
license. Extraction aborted.` ?

I have given `I ACCEPT` was able to succesfully extract files despite extraction aborted message.

<img width="557" alt="image" src="https://github.com/tensorflow/tensorflow/assets/118897289/950499dd-ffbd-4d12-b3c8-ea10d71378a9">

Thanks.

**Comment by octavflorescu** [comment]
No, i did not get any prompt... The log output form above in continuous and instant.  
  
Given your screen-shot, i have realized that the extraction needs to be done on Mac/computer, not on Mobile (as you can see from the original post, i am connecting to adb and running the commands there),  
so now i have tested it directly on Mac:  
```bash
chmod +x tflite_hexagon_nn_skel_v1.20.0.1.run
./tflite_hexagon_nn_skel_v1.20.0.1.run
```
And i was able to write "I ACCEPT", thank you! 🥳  
An image is worth a thousand words 😄
