### ISSUE TITLE
Windows MSBuild fails

### ISSUE THREAD

**Issue by keremcant** [tensorflow/tensorflow#6160]
Hello,
I am trying to build tensorflow for cpu on my Windows computer using cmake and MS Visual Studio. I do the steps as described in the link below, I came until step 4, however at step 4 however MSBuild fails. Since I don't need the test program, I am trying to dirrectly build the .whl file by building the tf_python_copy_scripts_to_destination.vcxproj.

I am using the instructions from the link: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md

 I have a service pack 1 Windows 7, 64 bit.

In terms of Prerequisites:
- CMake version 3.5 up to 3.6 (I have 3.6.3)
- Git (I have 2.10.0.windows.1)
- SWIG (I have swigwin 3.0.10)

Additional pre-requisites for Microsoft Windows:
- Visual Studio 2015 (I have VS 2015 and MSBuild 14.0)
- Python 3.5 (I have Python 3.5)
- NumPy 1.11.0 or later (I have 1.11.2)

Since there are multiple MSBuilds, I set the path string to the MSBuild 14.0: C:\Program Files (x86)\MSBuild\14.0\Bin\amd64. Also there are two versions, one directly under \Bin and one under \Bin\amd64. I choose the latter one. 

The error message I get is:
============================================

Done Building Project "C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default targe
ts) -- FAILED.

Build FAILED.

"C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default target) (1) ->
"C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow.vcxproj" (default target) (3) ->
"C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\tf_core_cpu.vcxproj" (default target) (4) ->
"C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\tf_core_framework.vcxproj" (default target) (5) ->
"C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\proto_text.vcxproj" (default target) (6) ->
"C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\grpc.vcxproj" (default target) (7) ->
(CustomBuild target) ->
  cl : Command line warning D9002: ignoring unknown option '-std=c11' [C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\grp
c\src\grpc\grpc_unsecure.vcxproj] [C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\grpc.vcxproj]
  cl : Command line warning D9002: ignoring unknown option '-std=c11' [C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\grp
c\src\grpc\grpc_unsecure.vcxproj] [C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\grpc.vcxproj]

"C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default target) (1) ->
"C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\pywrap_tensorflow.vcxproj" (default target) (3) ->
"C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\tf_core_cpu.vcxproj" (default target) (4) ->
"C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\tf_core_framework.vcxproj" (default target) (5) ->
"C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\proto_text.vcxproj" (default target) (6) ->
"C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\grpc.vcxproj" (default target) (7) ->
(CustomBuild target) ->
  C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\grpc\src\grpc\src\core\ext\transport\chttp2\transport\chttp2_transport.c
(2319): error C2440: 'initializing' : cannot convert from 'gpr_slice' to 'gpr_slice_refcount *' [C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorfl
ow\contrib\cmake\build\grpc\src\grpc\grpc_unsecure.vcxproj] [C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\grpc.vcxproj]
  C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\grpc\src\grpc\src\core\ext\transport\chttp2\transport\chttp2_transport.c
(2319): error C2440: 'initializing' : cannot convert from 'gpr_slice' to 'gpr_slice_refcount *' [C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorfl
ow\contrib\cmake\build\grpc\src\grpc\grpc_unsecure.vcxproj] [C:\Users\ktezcan\temp_tensorflowbuildfiles\tensorflow\tensorflow\contrib\cmake\build\grpc.vcxproj]

2 Warning(s)
2 Error(s)

Time Elapsed 00:00:58.06

=================================

Any help is appreciated. Thanks,
Kerem

**Comment by Carmezim** [comment]
Do you need to install TensorFlow on Windows specifically through CMake for some reason or just want to install it?

If the latter you can install with pip:
`pip install tensorflow`
for gpu:
`pip install tensorflow-gpu`

**Comment by keremcant** [comment]
I was basically trying to use skflow as shown in an online tutorial, which was apparently out of date.
Since I was getting an error with the code from the tutorial, after some googleing I thought I had an old version of tensorflow and needed to update the version. But apparently that is not the case and the tutorial was the old one! You can see this discussion in issue: https://github.com/tensorflow/tensorflow/issues/6162. 

Hence I will continue to use the windows release for now and find updated tutorials. On the other hand, it still does not solve my problem of building the code from source, but that is a problem for the future...

Thanks
