### ISSUE TITLE
Overflow bug when running tf.pad on colab

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#61608]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.13.0

### Custom code

Yes

### Current behavior?

Due to large input tensor

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
try:
  try:
    with tf.device('/CPU'):
      arg_0_tensor = tf.random.uniform([12, 2, 256, 513], dtype=tf.float32)
      arg_0 = tf.identity(arg_0_tensor)
      arg_1_tensor = tf.random.uniform([4, 2], dtype=tf.int32, maxval=54676034958255)
      arg_1 = tf.identity(arg_1_tensor)
      out = tf.pad(arg_0,arg_1,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      arg_0 = tf.identity(arg_0_tensor)
      arg_0 = tf.cast(arg_0, tf.float32)
      arg_1 = tf.identity(arg_1_tensor)
      arg_1 = tf.cast(arg_1, tf.int32)
      tf.pad(arg_0,arg_1,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
Error:{{function_node __wrapped__Pad_device_/job:localhost/replica:0/task:0/device:CPU:0}} Encountered overflow when multiplying 2206572623628733836 with 75929941, result: -1 [Op:Pad] name: 
Error:{{function_node __wrapped__Pad_device_/job:localhost/replica:0/task:0/device:GPU:0}} Encountered overflow when multiplying 2206572623628733836 with 75929941, result: -1 [Op:Pad] name
```
```

**Comment by SuryanarayanaY** [comment]
Hi @dmc1778 ,  

The reported behaviour is replicated with Tf2.13v and tf-nightly and attached gists [2.13v](https://colab.sandbox.google.com/gist/SuryanarayanaY/29eda785ec3df75c66fad7d184fc6786/61608-2-13v.ipynb) and [nightly](https://colab.sandbox.google.com/gist/SuryanarayanaY/c0b6a6aeccdc8449bd9ea36f398dd151/61608-tf-nightly.ipynb) for reference.

**Comment by SuryanarayanaY** [comment]
@dmc1778 ,

Please refer to the responses of Developer team related to the exception raised https://github.com/tensorflow/tensorflow/issues/61630#issuecomment-1685333019 and https://github.com/tensorflow/tensorflow/issues/61629#issuecomment-1686504422 stating it as intended behaviour.

The Op tries to allocate the memory for the inputs and outputs before performing computations and it fails. The same error returned to python and its adding more details to error log.

As requested please read [SECURITY.md](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) to disclose these types of issues.

Thanks!

**Comment by mihaimaruseac** [comment]
Not an issue, it is a normal error being returned to the user.
