### ISSUE TITLE
Issue with nightly-gpu docker image

### ISSUE THREAD

**Issue by zndr27** [tensorflow/tensorflow#61607]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15.0-dev20230816

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Python version

3.11

### Current behavior?

When using the tensorflow/tensorflow:nightly-gpu docker image I get an error saying the "DNN library is not found"

However, when I change the base image to tensorflow/tensorflow:latest-gpu my code works fine.

Perhaps the nightly image broke something with the cuda / cudnn library paths?

### Standalone code to reproduce the issue

```shell
It seems that using a Conv1D layer is what causes the issue... see the log output below.
```

### Relevant log output

```shell
Detected at node 'peak_conv_1/Conv1D' defined at (most recent call last):
Node: 'peak_conv_1/Conv1D'
DNN library is not found.
         [[{{node peak_conv_1/Conv1D}}]] [Op:__inference_train_step_224831]
```

**Comment by sushreebarsa** [comment]
@zndr27 Could you try to use TF v2.13 instead of the nightly as it might not be stable.  Please have a look at the compatible [versions](https://www.tensorflow.org/install/source#tested_build_configurations) as well. Thank you!
