### ISSUE TITLE
Overflow bug when running tf.tile

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#61613]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.13.0

### Custom code

Yes

### Current behavior?

Due to large list elements

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
try:
  arg_0_tensor = tf.random.uniform([452, 1, 768], dtype=tf.float32)
  arg_0 = tf.identity(arg_0_tensor)
  arg_1_0 = 125091515651
  arg_1_1 = 125091515651
  arg_1_2 = 125091515651
  arg_1 = [arg_1_0,arg_1_1,arg_1_2,]
  out = tf.tile(arg_0,arg_1,)
except Exception as e:
  print("Error:"+str(e))

```
```


### Relevant log output

```shell
Error:{{function_node __wrapped__Tile_device_/job:localhost/replica:0/task:0/device:GPU:0}} Encountered overflow when multiplying 56541365074252 with 125091515651, result: -1
	 [[{{node Tile}}]] [Op:Tile]

```
```

**Comment by mihaimaruseac** [comment]
Not an issue, that's an error that is being returned to the user instead of performing bad computations.

Please consult again the SECURITY.md guide, please don't spam with low quality issues.
