### ISSUE TITLE
Import error with skflow

### ISSUE THREAD

**Issue by keremcant** [tensorflow/tensorflow#6162]
Hello,

I get an error when I try to import skflow with the command 
`from tensorflow.contrib import skflow`
The error is "ImportError: cannot import name 'skflow". I have googled the error came across this similar issue: https://github.com/tensorflow/tensorflow/issues/1931. Apparently I have a lower version of tensorflow (I had 0.12) and need a newer version, such as 0.80.

I had done the installation by looking at this website (for cpu based): https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html#pip-installation-on-windows. 

Probably only 0.12 is released for windows. Is there a way to get a higher version for Windows, or some workaround?

As a solution I have also separately installed skflow, but some of the functions are not there, as I see them in this tutorial: http://learningtensorflow.com/lesson8/, since it is an older version probably.

I am now trying to build tensorflow on my computer with cmake and MSBuild, but it also does not run smoothly. You can see the issue with that here: https://github.com/tensorflow/tensorflow/issues/6160

I have the following specs:
- Windows 7, service pack 1, 64 bit
- Python 3.5
- Tensorflow 0.12

Thanks a lot,
Kerem

**Comment by mrry** [comment]
TensorFlow 0.8 is not available for Windows - note that it is actually an **older** version than TensorFlow 0.12 (the version numbers are not decimal fractions, so 0.80 != 0.8).

The `tf.contrib.skflow` package has been removed, and that tutorial is out of date. Please contact the author and ask them to update it to the latest APIs.
