### ISSUE TITLE
Opening http://projector.tensorflow.org/ shows a white screen in Chrome 55

### ISSUE THREAD

**Issue by TimvdLippe** [tensorflow/tensorflow#6163]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

I have search for open GitHub issues with the keyword `WebGL`, but none showed up.

### Issue

Today I opened http://projector.tensorflow.org/ in my browser, but got a complete white screen. The attached logs show the errors that are show in the console of the browser. Opening in Firefox on the same machine does succesfully launch the application and I was able to interact with it. 

### Environment info
Operating System: Ubuntu 16.04
```
Google Chrome	55.0.2883.75 (Official Build) (64-bit)
Revision	451c239c3b0722dc867b0f75839b959f729b756a-refs/branch-heads/2883@{#698}
OS	Linux 
JavaScript	V8 5.5.372.29
Flash	23.0.0.207
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36
```

### Logs or other output that would be helpful
```
(index):7671 THREE.WebGLRenderer 77
(index):7671 THREE.WebGLRenderer: Error creating WebGL context.
THREE.WebGLRenderer
(index):7722 Uncaught TypeError: Cannot read property 'getExtension' of null
    at THREE.WebGLExtensions.get ((index):7722)
    at new THREE.WebGLRenderer ((index):7672)
    at new Gp ((index):8253)
    at new cq ((index):8320)
    at HTMLElement.q.setupUIControls ((index):8430)
    at HTMLElement.q.ready ((index):8413)
    at HTMLElement._invokeBehavior ((index):5501)
    at HTMLElement._doBehavior ((index):5501)
    at HTMLElement._readySelf ((index):5516)
    at HTMLElement._ready ((index):5516)
(index):8430 Uncaught TypeError: Cannot read property 'resize' of undefined
    at (index):8430
```

**Comment by LoZio** [comment]
Same problem here on Chrome 55 on Win 10. Page runs fine on Edge.

**Comment by bittlingmayer** [comment]
Same here.  Version 54.0.2840.98 (64-bit) on Sierra.

**Comment by dsmilkov** [comment]
Hi,

The problem is due to WebGL being disabled. To enable WebGL in Chrome, go to chrome://settings and make sure "enable hardware acceleration" is checked. This does not guarantee that WebGL will work for you however. Some users reported success after reinstalling/updating their graphics drivers.

With commit 2166d20cf2308b4f0e1a895ac8b8aacaf04dd15f we are displaying an informative message instead of a blank screen when WebGL is not working.

Thank you for reporting this!

**Comment by TimvdLippe** [comment]
Confirmed I get a nice modal now, thanks a lot for the speedy fix and explanation!
