### ISSUE TITLE
Overflow bug when running tf.image.resize

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#61630]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.13.0

### Custom code

Yes

### Current behavior?

Due to large elements in the input list

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
try:
  arg_0_tensor = tf.constant(-1000000, shape=[577, 700, 3, 1], dtype=tf.float64,)
  arg_0 = tf.identity(arg_0_tensor)
  arg_1_0 = 1610637938
  arg_1_1 = 1250999896764
  arg_1 = [arg_1_0,arg_1_1,]
  out = tf.image.resize(arg_0,arg_1,)
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
Error:{{function_node __wrapped__ResizeBilinear_device_/job:localhost/replica:0/task:0/device:GPU:0}} Encountered overflow when multiplying 929338090226 with 1164413628, result: -1 [Op:ResizeBilinear] name:
```
```

**Comment by mihaimaruseac** [comment]
Not an issue, that's an error that is being returned to the user instead of performing bad computations.

Please consult again the SECURITY.md guide, please don't spam with low quality issues.
