### ISSUE TITLE
external/XNNPACK/src/qs8-igemm/gen/4x16c8-minmax-avx512skx.c:242:15: error: implicit declaration of function '_kshiftri_mask64' is invalid in C99

### ISSUE THREAD

**Issue by B-JackMao** [tensorflow/tensorflow#61635]
I run commands
"bazel build -c opt --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a   --host_crosstool_top=@bazel_tools//tools/cpp:toolchain   //tensorflow/lite/java:tensorflow-lite"  
use 
tensorflow 2.4.0
 bazel 3.1.0 ,NDK  27 ,SDK 29 ,But what should I do to resolve the following errors！！！

ERROR: /home/ferey/.cache/bazel/_bazel_ferey/97c7558b0863433a4def08aa5708cd20/external/XNNPACK/BUILD.bazel:3516:1: C++ compilation of rule '@XNNPACK//:avx512skx_ukernels' failed (Exit 1)
external/XNNPACK/src/qs8-igemm/gen/4x16c8-minmax-avx512skx.c:242:15: error: implicit declaration of function '_kshiftri_mask64' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      vmask = _kshiftri_mask64(vmask, 16);
              ^
1 error generated.
Target //tensorflow/lite/java:tensorflow-lite failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 229.018s, Critical Path: 17.13s
INFO: 1788 processes: 1788 local.
FAILED: Build did NOT complete successfully

**Comment by pjpratik** [comment]
Hi @B-JackMao 

The TF 2.4.0 is not being supported currently. Can you please check with latest stable version TF 2.13. with following configurations?

```
build --action_env ANDROID_NDK_HOME="/usr/local/android/android-ndk-r21e"
build --action_env ANDROID_NDK_API_LEVEL="26"
build --action_env ANDROID_BUILD_TOOLS_VERSION="30.0.3"
build --action_env ANDROID_SDK_API_LEVEL="30"
build --action_env ANDROID_SDK_HOME="/usr/local/android/android-sdk-linux"
```

and run

```
bazel build -c opt --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a \
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
  --define=android_dexmerger_tool=d8_dexmerger \
  --define=android_incremental_dexing_tool=d8_dexbuilder \
  //tensorflow/lite/java:tensorflow-lite
```

Thanks.

**Comment by B-JackMao** [comment]
OK,thanks.

**Comment by pjpratik** [comment]
Hi @B-JackMao 

Can you please close this issue as it is being tracked in #61655?

Thanks.
