### ISSUE TITLE
CKPT to TFLite

### ISSUE THREAD

**Issue by md-rifatkhan** [tensorflow/tensorflow#61645]
How can I convert ckpt file to TF Lite, while I've only .ckpt file. No meta-file present

**Comment by Sourabh20022002** [comment]
1.Convert your TensorFlow checkpoint files to a SavedModel format. This is typically done using the tf.saved_model.save function. Here's an example:

import tensorflow as tf

# Load the model architecture and checkpoint
model = ...  # Load or define your model here
checkpoint_path = 'path/to/your/model.ckpt'
checkpoint = tf.train.Checkpoint(model=model)
checkpoint.restore(checkpoint_path).expect_partial()

# Save the model in SavedModel format
saved_model_path = 'path/to/save/saved_model'
tf.saved_model.save(model, saved_model_path)

2.After exporting the model to the SavedModel format, you can then use the TensorFlow Lite Converter (tf.lite.TFLiteConverter) to convert the SavedModel to TFLite format:

# Convert SavedModel to TFLite
tflite_converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_path)
tflite_model = tflite_converter.convert()

3.Finally, save the TFLite model to a .tflite file:

tflite_model_path = 'path/to/save/model.tflite'
with open(tflite_model_path, 'wb') as f:
    f.write(tflite_model)

**Comment by pjpratik** [comment]
Hi @md-rifatkhan 

As @Sourabh20022002  suggested, we need to save the checkpoints in SavedModel format and convert it to the TFLite model.

In addition to that, you can also use concrete functions to convert into TFLite model once you load the checkpoints in TF Model.

Please check these [examples](https://www.tensorflow.org/lite/models/convert/convert_models#convert_a_savedmodel_recommended_) for both the cases.

Thanks.

**Comment by TiantianZhang** [comment]
> How can I convert ckpt file to TF Lite, while I've only .ckpt file. No meta-file present

The convert can be achieved? I tried the metod, but still exists warning

WARNING:tensorflow:Skipping full serialization of Keras layer <mlp_test.MLP object at 0x7faed0788f10>, because it is not built.
