### ISSUE TITLE
 W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:689] Error in PredictCost() for the op: op: "Conv2D" attr { key: "T" value { type: DT_FLOAT } } attr { key: "data_format" value { s: "NCHW" } } attr { key: "dilations" value 

### ISSUE THREAD

**Issue by dsnsabari** [tensorflow/tensorflow#61656]
### Issue type

Others

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf.2.7.0

### Custom code

Yes

### OS platform and distribution

Windows 10

### Python version

3.9.12

### CUDA/cuDNN version

11.6

### GPU model and memory

GPU 8 / NVIDIA SMI 512.98

### Current behavior?

I am getting the below error message while loading the model on tf 2.7.0. But there is no issue with the prediction. 
I have converted Keras model into tf2 and loaded them in production. 

### Standalone code to reproduce the issue

```shell
: W tensorflow/core/grappler/costs/op_level_cost_estimator.cc:689] Error in PredictCost() for the op: op: "Conv2D" attr { key: "T" value { type: DT_FLOAT } } attr { key: "data_format" value { s: "NCHW" } } attr { key: "dilations" value { list { i: 1 i: 1 i: 1 i: 1 } } } attr { key: "explicit_paddings" value { list { } } } attr { key: "padding" value { s: "SAME" } } attr { key: "strides" value { list { i: 1 i: 1 i: 1 i: 1 } } } attr { key: "use_cudnn_on_gpu" value { b: true } } inputs { dtype: DT_FLOAT shape { dim { } dim { size: 62 } dim { size: 4 } dim { size: 4 } } } inputs { dtype: DT_FLOAT shape { dim { size: 1 } dim { size: 1 } dim { size: 62 } dim { size: 31 } } } device { type: "GPU" vendor: "NVIDIA" model: "NVIDIA GeForce GTX 1070" frequency: 1695 num_cores: 16 environment { key: "architecture" value: "6.1" } environment { key: "cuda" value: "11020" } environment { key: "cudnn" value: "8100" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 2097152 shared_memory_size_per_multiprocessor: 98304 memory_size: 6952124416 bandwidth: 256256000 } outputs { dtype: DT_FLOAT shape { dim { } dim { size: 31 } dim { size: 4 } dim { size: 4 } } }
```

**Comment by SuryanarayanaY** [comment]
Hi @dsnsabari ,

The warnings related to grappler observed in older versions.These are warnings only and hence code execution and predictions not affected. Please find relevant issue [here](https://github.com/tensorflow/tensorflow/issues/50575) where the issue might have fixed with latest versions.

As there is no minimal code snippet I can't able to test it. Could you please provide minimal code snippet to reproduce the issue or test your model with latest TF versions preferably 2.12v or higher and let us know if same warnings still persists.

Thanks!

**Comment by dsnsabari** [comment]
hi @SuryanarayanaY , Still the error exists in the latest TensorFlow version. Did you check his comment? 

https://github.com/tensorflow/tensorflow/issues/50575#issuecomment-1670905587
