### ISSUE TITLE
TF Quantizer breaks pip package

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#61668]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

git HEAD

### Custom code

No

### OS platform and distribution

Ubuntu 20.04

### Mobile device

n/a

### Python version

3.9.16

### Bazel version

6.1.0

### GCC/compiler version

16.0.6

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current behavior?

The commit https://github.com/tensorflow/tensorflow/commit/fee881376914381062deb767759d144d0f07d760 added pywrap_quantize_model.so to the pip package but the build fails to set the RPATH for _pywrap_tensorflow_internal.so in the new .so leading to a failure in auditwheel when attempting to 'repair' to make it manylinux2014 compatible.

### Standalone code to reproduce the issue

```shell
$ python3 -m auditwheel repair --plat manylinux2014_aarch64 ./tensorflow-pkg/tensorflow_aarch64-2.15.0-cp311-cp311-linux_aarch64.whl --wheel-dir ./whl/
```

### Relevant log output

```shell
$ python3 -m auditwheel repair --plat manylinux2014_aarch64 ./tensorflow-pkg/tensorflow_aarch64-2.15.0-cp311-cp311-linux_aarch64.whl --wheel-dir ./whl/
INFO:auditwheel.main_repair:Repairing tensorflow_aarch64-2.15.0-cp311-cp311-linux_aarch64.whl
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/auditwheel/__main__.py", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/auditwheel/main.py", line 59, in main
    rval = args.func(args, p)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/auditwheel/main_repair.py", line 173, in execute
    out_wheel = repair_wheel(
                ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/auditwheel/repair.py", line 80, in repair_wheel
    raise ValueError(
ValueError: Cannot repair wheel, because required library "_pywrap_tensorflow_internal.so" could not be located

Also

$ ldd venv_bad/lib/python3.11/site-packages/tensorflow/compiler/mlir/quantization/tensorflow/python/pywrap_quantize_model.so
	linux-vdso.so.1 (0x0000ffffb8af9000)
	libtensorflow_framework.so.2 => /workspace/venv_bad/lib/python3.11/site-packages/tensorflow/compiler/mlir/quantization/tensorflow/python/../../../../../libtensorflow_framework.so.2 (0x0000ffffb6800000)
	_pywrap_tensorflow_internal.so => not found
	libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000ffffb8923000)
	libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffffb88f2000)
	libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffffb8847000)
	libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000ffffb661b000)
	libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000ffffb8823000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffffb64a8000)
	/lib/ld-linux-aarch64.so.1 (0x0000ffffb8ac9000)
	librt.so.1 => /lib/aarch64-linux-gnu/librt.so.1 (0x0000ffffb8809000)

Compare with

$ ldd venv_bad/lib/python3.11/site-packages/tensorflow/python/saved_model/pywrap_saved_model.so
	linux-vdso.so.1 (0x0000ffffa40a2000)
	libtensorflow_framework.so.2 => /workspace/venv_bad/lib/python3.11/site-packages/tensorflow/python/saved_model/../../libtensorflow_framework.so.2 (0x0000ffffa1e00000)
	_pywrap_tensorflow_internal.so => /workspace/venv_bad/lib/python3.11/site-packages/tensorflow/python/saved_model/../_pywrap_tensorflow_internal.so (0x0000ffffa1c0a000)
	libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000ffffa3ee5000)
	libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000ffffa3e3a000)
	libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000ffffa3e09000)
	libstdc++.so.6 => /lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000ffffa1a25000)
	libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000ffffa3de5000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000ffffa18b2000)
	/lib/ld-linux-aarch64.so.1 (0x0000ffffa4072000)
	librt.so.1 => /lib/aarch64-linux-gnu/librt.so.1 (0x0000ffffa3dcd000)
	libtensorflow_cc.so.2 => /workspace/venv_bad/lib/python3.11/site-packages/tensorflow/python/saved_model/../../libtensorflow_cc.so.2 (0x0000ffff8be00000)
	libml_dtypes.so.so => /workspace/venv_bad/lib/python3.11/site-packages/tensorflow/python/saved_model/../../tsl/python/lib/core/libml_dtypes.so.so (0x0000ffffa3d99000)
	libomp.so.5 => /usr/lib/llvm-16/lib/libomp.so.5 (0x0000ffff8bcc0000)
```

**Comment by elfringham** [comment]
@cfRod @nSircombe @penpornk @thaink

**Comment by thaink** [comment]
@elfringham From your comparision, what is the main difference between those two libs?

**Comment by elfringham** [comment]
@thaink 
When running ldd on pywrap_saved_model.so you get
_pywrap_tensorflow_internal.so => /workspace/venv_bad/lib/python3.11/site-packages/tensorflow/python/saved_model/../_pywrap_tensorflow_internal.so (0x0000ffffa1c0a000)

When running ldd on pywrap_quantize_model.so you get
_pywrap_tensorflow_internal.so => not found
So it looks like RPATH is not set correctly.

**Comment by elfringham** [comment]
@thaink 
Yes, RPATH does not contain the location of _pywrap_tensorflow_internal.so

$ ls -l venv_bad/lib/python3.11/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
-rwxrwxr-x 1 andrew andrew 2513424 Aug 18 14:23 venv_bad/lib/python3.11/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
$ patchelf --print-rpath venv_bad/lib/python3.11/site-packages/tensorflow/compiler/mlir/quantization/tensorflow/python/pywrap_quantize_model.so
$ORIGIN/../../../../../../_solib_local/_U_S_Stensorflow_Clibtensorflow_Uframework_Uimport_Ulib___Utensorflow:$ORIGIN/pywrap_quantize_model.so.runfiles/org_tensorflow/_solib_local/_U_S_Stensorflow_Clibtensorflow_Uframework_Uimport_Ulib___Utensorflow:$ORIGIN/../../../../../../_solib_local/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal_Ulinux___Utensorflow_Spython:$ORIGIN/pywrap_quantize_model.so.runfiles/org_tensorflow/_solib_local/_U_S_Stensorflow_Spython_C_Upywrap_Utensorflow_Uinternal_Ulinux___Utensorflow_Spython:$ORIGIN/:$ORIGIN/..:$ORIGIN/../..:$ORIGIN/../../..:$ORIGIN/../../../..:$ORIGIN/../../../../..

**Comment by thaink** [comment]
Thanks for reporting and fixing @elfringham
