### ISSUE TITLE
python3.11.3 mismatch with tensorflow 2.13.0

### ISSUE THREAD

**Issue by danche354** [tensorflow/tensorflow#61666]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.13.0

### Custom code

No

### OS platform and distribution

macOS Venture 13.4

### Python version

3.11.3

### Current behavior?

![image](https://github.com/tensorflow/tensorflow/assets/11846497/3459b246-e377-499d-9d9f-e5f666fb7957)

### Standalone code to reproduce the issue

```shell
import tensorflow
```

**Comment by elfringham** [comment]
You seem to be running TensorFlow that was installed for Python 3.9 but using Python 3.11 interpreter. Of course it fails.

**Comment by mihaimaruseac** [comment]
What is the output of `python -m pip list; python -c "import tensorflow as tf; print(tf)"`?

**Comment by sushreebarsa** [comment]
@danche354 Could you please make sure that  you are using compatible version as mentioned [here](https://www.tensorflow.org/install/source) under tested build configuration and followed the exact steps? 
Please cross check the python version you are using!
Thank you!
