### ISSUE TITLE
`GLIBCXX_3.4.30' not found

### ISSUE THREAD

**Issue by andrewkim-pkt** [tensorflow/tensorflow#61665]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

r2.13

### Custom code

No

### OS platform and distribution

amazon linux 2023

### Python version

3.9

### Bazel version

5.3.0

### GCC/compiler version

gcc 12.2

### Current behavior?

ERROR: /root/tensorflow/tensorflow/core/transforms/remapper/BUILD:14:18: TdGenerate tensorflow/core/transforms/remapper/pdll/MklPDLLPatterns.h.inc [for host] failed: (Exit 1): mlir-pdll failed: error executing command bazel-out/host/bin/external/llvm-project/mlir/mlir-pdll '-x=cpp' tensorflow/core/transforms/remapper/pdll/mkl_patterns.pdll -I ./tensorflow/core/transforms/include -I ... (remaining 15 arguments skipped)
bazel-out/host/bin/external/llvm-project/mlir/mlir-pdll: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by bazel-out/host/bin/external/llvm-project/mlir/mlir-pdll)

### Standalone code to reproduce the issue

```shell
ERROR: /root/tensorflow/tensorflow/core/transforms/remapper/BUILD:14:18: TdGenerate tensorflow/core/transforms/remapper/pdll/MklPDLLPatterns.h.inc [for host] failed: (Exit 1): mlir-pdll failed: error executing command bazel-out/host/bin/external/llvm-project/mlir/mlir-pdll '-x=cpp' tensorflow/core/transforms/remapper/pdll/mkl_patterns.pdll -I ./tensorflow/core/transforms/include -I ... (remaining 15 arguments skipped)
bazel-out/host/bin/external/llvm-project/mlir/mlir-pdll: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by bazel-out/host/bin/external/llvm-project/mlir/mlir-pdll)
```

### Relevant log output

```shell
ERROR: /root/tensorflow/tensorflow/core/transforms/remapper/BUILD:14:18: TdGenerate tensorflow/core/transforms/remapper/pdll/MklPDLLPatterns.h.inc [for host] failed: (Exit 1): mlir-pdll failed: error executing command bazel-out/host/bin/external/llvm-project/mlir/mlir-pdll '-x=cpp' tensorflow/core/transforms/remapper/pdll/mkl_patterns.pdll -I ./tensorflow/core/transforms/include -I ... (remaining 15 arguments skipped)
bazel-out/host/bin/external/llvm-project/mlir/mlir-pdll: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by bazel-out/host/bin/external/llvm-project/mlir/mlir-pdll)
```

**Comment by Varsha-anjanappa** [comment]
Hi @andrewkim-pkt ,

Try using Clang instead of GCC, as from tf v2.13 it supports compiler Clang. Please refer the documentation [here](https://www.tensorflow.org/install/source#cpu) for reference. Let us know if the issue still exists. 

Thank you!!

**Comment by andrewkim-pkt** [comment]
GCC 11.4 build with tr v2.13 works fine but GCC 12.2 got this issue.
Never tried it with Clang, can you please share the steps for this to save time.

**Comment by Varsha-anjanappa** [comment]
Hi @andrewkim-pkt ,

Please follow the build from source steps [here](https://www.tensorflow.org/install/source).
To install clang please refer [here](https://www.tensorflow.org/install/source#install_clang_recommended_linux_only).
Configure the build and select Y to use Clang to build TensorFlow. Refer [here](https://www.tensorflow.org/install/source#expandable-1)

Thank you!!
