### ISSUE TITLE
Image storage

### ISSUE THREAD

**Issue by B-JackMao** [tensorflow/tensorflow#61676]
When TFLite processes image data, which variable will the read in image data be stored in? Is it TfLiteTensor.data?

How can I directly process a single image using TensorFlow Lite source code without relying on an Android app?

**Comment by sushreebarsa** [comment]
Hello, @JyotiPDLr!  That above page is referring to the process of input and output data in TFlite. To process an image data we have to set the tensor, invoke it and lastly we can get the tensor.
@B-JackMao We can store any image data in the form of a tensor while processing it. We have to consider only the size and type of the image. Please have a look at this [example](https://www.tensorflow.org/lite/performance/post_training_quant) where you can see how a model can be tested on a single image.  Sample code is as below;
```
test_image = np.expand_dims(test_images[0], axis=0).astype(np.float32)

input_index = interpreter.get_input_details()[0]["index"]
output_index = interpreter.get_output_details()[0]["index"]

interpreter.set_tensor(input_index, test_image)
interpreter.invoke()
predictions = interpreter.get_tensor(output_index)
```
Thank you!
