### ISSUE TITLE
Use old project folder on tensorflow 2.13 using wls

### ISSUE THREAD

**Issue by pro1944191** [tensorflow/tensorflow#61673]
Hi everyone, I was working on a project using tensorflow 2.10 with native gpu support. I wrongly updated the tf version to 2.13 that does not support gpu. So, I installed tensorflow 2.13 using wls2, now i don't know how to use the previous folder of my project on the conda environment created. Or intsead how to reinstall tf 2.10

**Comment by Raghav-Bell** [comment]
Hey @pro1944191  i think you little bit messed up things. May i know `tf` version on both `WSL2 venv` & `conda env`? What os you wanna work on `linux(WSL2)` or `windows` ?

**Comment by Raghav-Bell** [comment]
You can install `tf==2.10` using `conda` too. Check here: [anaconda tf 2.10 binaries ](https://anaconda.org/anaconda/tensorflow/files?version=2.10.0)

**Comment by SuryanarayanaY** [comment]
Hi @pro1944191 ,

I believe there is mix of Conda and Pip installations here causing the issue. We recommend to use only pip for installing tf binaries and refer the official [source](https://www.tensorflow.org/install/pip#:~:text=Note%3A%20Do%20not%20install%20TensorFlow%20with%20conda.%20It%20may%20not%20have%20the%20latest%20stable%20version.%20pip%20is%20recommended%20since%20TensorFlow%20is%20only%20officially%20released%20to%20PyPI.) for same. Could you please try with fresh environments.
