### ISSUE TITLE
Nvidia RTX 3500 Ada generation graphic card not recognised by tensorflow?

### ISSUE THREAD

**Issue by YiDuan-useismic** [tensorflow/tensorflow#61691]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.13.0

### Custom code

Yes

### OS platform and distribution

Windows 10

### Python version

3.11.4

### CUDA/cuDNN version

v11

### GPU model and memory

RTX 3500 Ada generation mobile 12GB

### Current behavior?

The RTX 3500 card cannot be recognised by tensorflow. I ran tf.config.list_physical_devices('GPU') and tf.test.is_gpu_available(). The results returned "0 GPUs available" and "False".

The microsoft visual studio 2017 is also installed.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

tf.test.is_gpu_available()
```

**Comment by Raghav-Bell** [comment]
I think it is not issue with `tf`  but `windows 10`. Please check:

1.  if your system is detecting GPU or not ([How to check GPU in Windows](https://www.microsoft.com/en-us/windows/learning-center/how-to-check-gpu)) if not check this [My RTX 3050 ti is gone and not working](https://answers.microsoft.com/en-us/windows/forum/all/my-rtx-3050-ti-is-gone-and-not-working/3f672229-77c8-4083-b921-03e2e891ca07). 
2. Is `tensorflow` or `jupyter notebook` GPU enabled ([how-to-install-tensorflow-gpu-version-with-jupyter-windows-10-in-8-easy-steps](https://vivek-singh.medium.com/how-to-install-tensorflow-gpu-version-with-jupyter-windows-10-in-8-easy-steps-8797547028a4)) (one change after `tf v2.12` `tensorflow-gpu` & `tensorflow `are same)

**Comment by YiDuan-useismic** [comment]
I did the system check and RTX 3500 can be detected. I found the specifications of the RTX Ada Generation card and the CUDA version seems to be 8.9? The link is [https://www.techpowerup.com/gpu-specs/rtx-3500-mobile-ada-generation.c4098](url)
So I tried to install CUDA 8.9 and associated cuDNN. The version of python is also downgraded and the GPU card can be detected with the old tensorflow Session function. But because the version of tensorflow is old and I have to debug my current code to get it working. This doesn't make any sense as this graphic card should be used with the latest library. Does anyone have any idea how should the environment be correctly configured?

**Comment by SuryanarayanaY** [comment]
Hi @YiDuan-useismic ,

For native Windows TF2.10v is the last supported version for GPU support.Please refer the attached [source](https://www.tensorflow.org/install/pip#windows-native:~:text=Caution%3A%20TensorFlow%202.10%20was%20the%20last%20TensorFlow%20release%20that%20supported%20GPU%20on%20native%2DWindows.%20Starting%20with%20TensorFlow%202.11%2C%20you%20will%20need%20to%20install%20TensorFlow%20in%20WSL2%2C%20or%20install%20tensorflow%20or%20tensorflow%2Dcpu%20and%2C%20optionally%2C%20try%20the%20TensorFlow%2DDirectML%2DPlugin) here.

For TF versions >=2.11 v you need to install WSL2 on windows. For enabling GPU support with WSL2 please refer the instructions [here](https://www.tensorflow.org/install/pip#step-by-step_instructions).

Thanks!

**Comment by YiDuan-useismic** [comment]
> Hi @YiDuan-useismic ,
> 
> For native Windows TF2.10v is the last supported version for GPU support.Please refer the attached [source](https://www.tensorflow.org/install/pip#windows-native:~:text=Caution%3A%20TensorFlow%202.10%20was%20the%20last%20TensorFlow%20release%20that%20supported%20GPU%20on%20native%2DWindows.%20Starting%20with%20TensorFlow%202.11%2C%20you%20will%20need%20to%20install%20TensorFlow%20in%20WSL2%2C%20or%20install%20tensorflow%20or%20tensorflow%2Dcpu%20and%2C%20optionally%2C%20try%20the%20TensorFlow%2DDirectML%2DPlugin) here.
> 
> For TF versions >=2.11 v you need to install WSL2 on windows. For enabling GPU support with WSL2 please refer the instructions [here](https://www.tensorflow.org/install/pip#step-by-step_instructions).
> 
> Thanks!

Thanks @SuryanarayanaY I will follow the instruction to install the Tensorflow with WSL2.
