### ISSUE TITLE
Docs for tf.device should point to tf.Graph.device

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#617]
Currently the docs for `tf.device` located here:

https://www.tensorflow.org/versions/master/api_docs/python/framework.html#device

point to `tf.Graph.name_scope()` for more details, when it would be a lot more helpful if they pointed instead to `tf.Graph.device()`, i.e. here:

https://www.tensorflow.org/versions/master/api_docs/python/framework.html#Graph.device

This would be more consistent with the rest of the docs as well.

**Comment by mrry** [comment]
Should be fixed at HEAD now.
