### ISSUE TITLE
Cannot build package with bazel

### ISSUE THREAD

**Issue by thinhdinh25** [tensorflow/tensorflow#61707]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

newest

### Custom code

Yes

### OS platform and distribution

Debian 12

### Python version

Python 3.9

### Bazel version

newest

### GCC/compiler version

Clang 16

### Current behavior?

I have searched everywhere but cannot find anything about this error

### Standalone code to reproduce the issue

```shell
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /home/drowsiness/
TensorFlow Version: 2.15.0
TensorFlow Major Version: 2
TMPDIR: /tmp/tmp.BINOHRyJHF
Fri Aug 25 09:26:15 PM PDT 2023 : === Preparing sources in dir: /tmp/tmp.BINOHRyJHF
Symlink already exists: bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/tensorflow/libtensorflow_cc.so.2
~/tensorflow ~/tensorflow
~/tensorflow
~/tensorflow ~/tensorflow
~/tensorflow
~/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow ~/tensorflow
~/tensorflow
./bazel-bin/tensorflow/tools/pip_package/build_pip_package: line 255: patchelf: command not found
```

**Comment by freedomtan** [comment]
```bash
....
./bazel-bin/tensorflow/tools/pip_package/build_pip_package: line 255: patchelf: command not found
...
```
you need patchelf as shown in the message

try
```bash
pip install patchelf
```
before running `build_pip_package`

**Comment by thinhdinh25** [comment]
Thanks. I got it working

**Comment by thinhdinh25** [comment]
> ```shell
> ....
> ./bazel-bin/tensorflow/tools/pip_package/build_pip_package: line 255: patchelf: command not found
> ...
> ```
> 
> you need patchelf as shown in the message
> 
> try
> 
> ```shell
> pip install patchelf
> ```
> 
> before running `build_pip_package`

I built tensorflow from source but still get this notification. Can u help:
This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.                                                                                                                          
To enable the following instructions: SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

**Comment by freedomtan** [comment]
> > ```shell
> > ....
> > ./bazel-bin/tensorflow/tools/pip_package/build_pip_package: line 255: patchelf: command not found
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you need patchelf as shown in the message
> > try
> > ```shell
> > pip install patchelf
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > before running `build_pip_package`
> 
> I built tensorflow from source but still get this notification. Can u help: This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations. To enable the following instructions: SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

as suggested by the message: "rebuild TensorFlow with the appropriate compiler flags"
either
1. add  `-march=native` or any other compiler flags for your CPUs
    - when `./configure` asks you what to add, or 
    - edit `build:opt --copt="..." entry in `.tf_configure.bazelrc` 
2. `./configure --config=mkl` to enable using Intel MKL DNN

**Comment by thinhdinh25** [comment]
> > > ```shell
> > > ....
> > > ./bazel-bin/tensorflow/tools/pip_package/build_pip_package: line 255: patchelf: command not found
> > > ...
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > you need patchelf as shown in the message
> > > try
> > > ```shell
> > > pip install patchelf
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > before running `build_pip_package`
> > 
> > 
> > I built tensorflow from source but still get this notification. Can u help: This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations. To enable the following instructions: SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 
> as suggested by the message: "rebuild TensorFlow with the appropriate compiler flags" either
> 
> 1. add  `-march=native` or any other compiler flags for your CPUs
>    
>    * when `./configure` asks you what to add, or
>    * edit `build:opt --copt="..." entry in `.tf_configure.bazelrc`
> 2. `./configure --config=mkl` to enable using Intel MKL DNN

external/eigen_archive/Eigen/Core:71:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
added --config=mkl but i got this error. I search somewhere told that i need -fopenmp=libomp. Where to add it

**Comment by sushreebarsa** [comment]
@thinhdinh25 Could you please have a look at this build from [source](https://www.tensorflow.org/install/source#build_the_package) and check the tested build configurations? FYKI, the latest stable TF version is 2.13 so please try to use that.
Thank you!

**Comment by sushreebarsa** [comment]
@JyotiPDLr It is always recommended to use the stable version as the nightly builds would be broken sometimes. 
The  tested build  configuration is stable for the latest stable release TF v2.13 . Thank you!
