### ISSUE TITLE
tf.math.top_k gradient taping fails when `index_type=tf.int64`

### ISSUE THREAD

**Issue by nicolaspi** [tensorflow/tensorflow#61701]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.13.0

### Custom code

Yes

### OS platform and distribution

Ubuntu 22.04

### Python version

3.11

### CUDA/cuDNN version

cuda_11.8.r11.8/compiler.31833905_0 / cuDNN version 8700

### GPU model and memory

NVIDIA GeForce RTX 2080 Ti

### Current behavior?

top_k gradient taping fails when `index_type=tf.int64`, unfortunately switching to `int32` leads to this other issue  https://github.com/tensorflow/tensorflow/issues/61692.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

x = tf.Variable(np.ones((3, 3)))

with tf.GradientTape() as tape:
    y = tf.math.top_k(x, k=1, index_type=tf.int64)

dy_dx = tape.gradient(y, x)
```

### Relevant log output

```shell
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int64 tensor but is a int32 tensor [Op:AddV2] name:
```

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.13, v2.12 and tf-nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/50f0256d5649e35801e57272f337b38c/untitled1345.ipynb).

**Comment by LakshmiKalaKadali** [comment]
Hi @nicolaspi,

By default, indices are returned as type int32, however, this can be changed by specifying the index_type. The function `tf.math.top_k` is working fine.  But while computing gradients, a type mismatch occurs between the parameters of Gradient. Specifically, the AddV2 operation expects two tensors of the same data type, in this case, int64. However, one of the input tensors is an int32 tensor.  Specify ` index_type=32` only, the gradients are computed without any error. Here is the [gist](https://colab.sandbox.google.com/gist/LakshmiKalaKadali/c68565ef5495545462d119a680b6fbf2/tf_61701.ipynb#scrollTo=xeHNWS7SpHEl) in which two cases are tested. 1. `y = tf.math.top_k(x, k=1, index_type=tf.int32)` and 2. `y = tf.math.top_k(x, k=1)`.

Thank you
