### ISSUE TITLE
Looking for selective post training quantization for 8 bit weights and 16 bit activations

### ISSUE THREAD

**Issue by Hrayo712** [tensorflow/tensorflow#61720]
**System information**

TensorFlow version (you are using): TF 2.13.0
Are you willing to contribute it (Yes/No): No
Describe the feature and the current behavior/state.

Dear TF developers, I'm currently experimenting with PTQ using 8 bit weights and 16 bit activations (W8A16), and I've gotten great results. However, after some experimentation I have identified that only a certain part of my network requires the 16 bit activations. In other word, using 16 bit activations for the entire model is sub-optimal for my use-case.

Hence, I'm looking for a way to selectively quantize a part of my model to 8 bit weights and activations (W8A8), and the other part to W8A16.

In the current state, would this be possible somehow ?

**Who will benefit with this feature?**
Platforms that support mixed-precision execution of activations.

**Any Other info.**

**Comment by pjpratik** [comment]
Hi @Hrayo712 

Mixed precision post training quantization is currently not supported in TFLite. However, the selective quantization is currently supported using [Quantization Debugger](https://www.tensorflow.org/lite/performance/quantization_debugger#selective_quantization), which accepts `denylisted_nodes` and `denylisted_op` options for skipping quantization for specific layers, or all instances of specific ops.

Thanks.

**Comment by Hrayo712** [comment]
Hi @pjpratik , thanks for the quick response!

I understand. However, when using selective quantization via the Quantization Debugger, denylisted_nodes are set to FP32 right ? or is there a way to set the denylisted nodes/ops to INT16 ?

**Comment by pjpratik** [comment]
Hi @Hrayo712 

>when using selective quantization via the Quantization Debugger, denylisted_nodes are set to FP32 right ?

Yes, the quantization is skipped for those nodes keeping them in their default FP32.

>is there a way to set the denylisted nodes/ops to INT16 ?

Those are just denied ops for quantization. As per the documentation, we don't have an option to set it to INT16.

Can we consider this as feature request?

Thanks.

**Comment by Hrayo712** [comment]
Hi @pjpratik,

Yes. I think it would be a super valuable feature, to have mixed-precision TFLite models. Perhaps the easy way would be indeed to allow for denylisted ops to be able to be quantized to INT16.

Thanks team!

**Comment by pkgoogle** [comment]
Hi @abattery, can you please take a look? Thanks.

**Comment by gaikwadrahul8** [comment]
Hi, @Hrayo712 
Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/ai-edge-torch/issues/395

Let us know if you have any questions. Thanks.
