### ISSUE TITLE
Kaggle TPU: TFLite-Model-Maker installation issue

### ISSUE THREAD

**Issue by dsbyprateekg** [tensorflow/tensorflow#61742]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.9.3

### Custom code

No

### OS platform and distribution

Kaggle TPU

### Python version

3.8.16

### GPU model and memory

TPU VM v3-8

### Current behavior?

1. Installed TFlite-model-maker using command `!pip install -q tflite-model-maker`
2. Tried to print the installed version using command `import tflite_model_maker
print(tflite_model_maker.__version__)`
3. Got error `ImportError: libusb-1.0.so.0: cannot open shared object file: No such file or directory`
I am attached here the error log.
[kaggle_tpu_error.txt](https://github.com/tensorflow/tensorflow/files/12460630/kaggle_tpu_error.txt)

### Standalone code to reproduce the issue

```shell
In Kaggle, enable TPU accelerator.
Install the TFLite Model Maker library.
Print the version of installed library.
```

**Comment by pkgoogle** [comment]
Hi @dsbyprateekg, tflite-model-maker installation is currently broken and it's unlikely to be resolved soon, in the mean time please try using mediapipe-model-maker instead: here is an example [gist](https://colab.sandbox.google.com/gist/pkgoogle/93fb7581fab1ea14728c61adf584ca13/media_pipe_example.ipynb). Let us know if for some reason you can't use mediapipe model maker to accomplish your goals. For now this is considered a duplicate of https://github.com/tensorflow/tensorflow/issues/60431

**Comment by pkgoogle** [comment]
Hi @dsbyprateekg, does the above work around work for you?

**Comment by dsbyprateekg** [comment]
@pkgoogle I think the broken installation issue is still there in platforms like colab and kaggle. Since it has been many months, any timeline when it will be fixed?

**Comment by pkgoogle** [comment]
Hi @dsbyprateekg, since that doesn't work, please try using[ MediaPipe-ModelMaker ](https://developers.google.com/mediapipe/solutions/model_maker)instead
