### ISSUE TITLE
What is All_op in tf.nn.dynamic_rnn?

### ISSUE THREAD

**Issue by LiangKlausQiu** [tensorflow/tensorflow#6175]
Hi, I am doing an android demo for RNN. I built a two-layer GRU network for inference. I used the API tf.nn.dynamic_rnn. However, when using this API, the saved generated .pb file contains an op called "All". And after I moved my .pb file to assets directory and run my android app demo, it said the op "All" is not registered. I know I can register an op in /core/kernels/BUILD file. However, I didn't find such an op in BUILD file. What is it and how can I fix the problem?
Thank you very much!

Here is the .pb file:
node {
    name: "Test/Model/RNN/RNN/All"
    op: "All"
    input: "Test/Model/RNN/RNN/Equal"
    input: "Test/Model/RNN/RNN/Const"
    attr {
       key: "Tidx"
       value {
          type: DT_INT32
       }
}
attr {
key: "keep_dims"
      value {
      b: false
     }
   }
 }

**Comment by LiangKlausQiu** [comment]
The android app reports "No OpKernel was registered to support Op 'All' with these attrs."

**Comment by michaelisard** [comment]
"All" is one of the reduction ops, see [reduction_ops_all.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/reduction_ops_all.cc). I'm not an expert on how to register those for the Android build, but LMK if you can't figure it out and I will look into it.

**Comment by LiangKlausQiu** [comment]
Thank you so much. I will try to register it in the kernel BUILD file to see if it works.

**Comment by LiangKlausQiu** [comment]
sorry I am also wondering if reduce_all and all are the same op?

**Comment by michaelisard** [comment]
Yes, reduce_all is the python wrapper for the C++ All Op I believe.

**Comment by LiangKlausQiu** [comment]
Thank you! Now I understand.

**Comment by LiangKlausQiu** [comment]
I have registered the reduction_ops_all.cc under the android group in /tensorflow/core/kernels/BUILD file and it worked. Thanks for your comment and I will close this.

**Comment by shijieKika** [comment]
Hi, @LiangKlausQiu , May I ask how to register `reduction_ops_all.cc` in `/tensorflow/core/kernels/BUILD`?
I tried to append it to `srcs` under `"android_all_ops"`, but got a duplicate error.
Many thanks!

**Comment by shijieKika** [comment]
Thanks,I find the way to register.

**Comment by LiangKlausQiu** [comment]
Great. I remember I just appended it under 'android_extended_ops_group2'.
