### ISSUE TITLE
No quantized type support for Enter/Exit Op

### ISSUE THREAD

**Issue by CuiYifeng** [tensorflow/tensorflow#61761]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.14.0rc0

### Custom code

No

### Current behavior?

Quantized types such as QINT8/QUINT8 are not registered for Enter/Exit.

Furthermore, why are some Control Flow Ops registered on `CPU Device` (e.g. `Merge/Switch/LoopCond`) but others not (e.g. `Enter/Exit/NextIteration`) ? 

Are these expected?

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

x = tf.constant(np.ones((5, 6)), dtype=tf.qint8)
enter = tf.raw_ops.Enter(data=x, frame_name="test", is_constant=True)
```

### Relevant log output

```shell
tensorflow.python.framework.errors_impl.NotFoundError: Could not find device for node: {{node Enter}} = Enter[T=DT_QINT8, frame_name="test", is_constant=true, parallel_iterations=10]
All kernels registered for op Enter:
  device='DEFAULT'; T in [DT_RESOURCE]
  device='DEFAULT'; T in [DT_STRING]
  device='DEFAULT'; T in [DT_INT32]
  device='DEFAULT'; T in [DT_VARIANT]
  device='DEFAULT'; T in [DT_BOOL]
  device='DEFAULT'; T in [DT_COMPLEX128]
  device='DEFAULT'; T in [DT_COMPLEX64]
  device='DEFAULT'; T in [DT_INT8]
  device='DEFAULT'; T in [DT_UINT8]
  device='DEFAULT'; T in [DT_INT16]
  device='DEFAULT'; T in [DT_UINT16]
  device='DEFAULT'; T in [DT_UINT32]
  device='DEFAULT'; T in [DT_INT64]
  device='DEFAULT'; T in [DT_UINT64]
  device='DEFAULT'; T in [DT_DOUBLE]
  device='DEFAULT'; T in [DT_FLOAT]
  device='DEFAULT'; T in [DT_BFLOAT16]
  device='DEFAULT'; T in [DT_HALF]
  device='GPU'; T in [DT_RESOURCE]
  device='GPU'; T in [DT_STRING]
  device='GPU'; T in [DT_INT32]
  device='GPU'; T in [DT_VARIANT]
  device='GPU'; T in [DT_BOOL]
  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_COMPLEX64]
  device='GPU'; T in [DT_INT8]
  device='GPU'; T in [DT_UINT8]
  device='GPU'; T in [DT_INT16]
  device='GPU'; T in [DT_UINT16]
  device='GPU'; T in [DT_UINT32]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_UINT64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_BFLOAT16]
  device='GPU'; T in [DT_HALF]
  device='TPU'
  device='TPU_SYSTEM'
```

**Comment by rarjun7777** [comment]
can i work on this ?

**Comment by SuryanarayanaY** [comment]
Hi @CuiYifeng ,

I have replicated the behaviour with Tf2.14.rc0. But with Tf2.12v it working fine. Attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/aba44286fab30dae78b84060d463fbae/61761_2-12-vs-2-14.ipynb) for reference.

It seems a regression issue for me. Need to check with Dev team.Thanks!

**Comment by CuiYifeng** [comment]
> Hi @CuiYifeng ,
> 
> I have replicated the behaviour with Tf2.14.rc0. But with Tf2.12v it working fine. Attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/aba44286fab30dae78b84060d463fbae/61761_2-12-vs-2-14.ipynb) for reference.
> 
> It seems a regression issue for me. Need to check with Dev team.Thanks!

Hi @SuryanarayanaY , thanks for your reply. Do you plan to fix this issue for TF-2.14 release?

**Comment by tilakrayal** [comment]
@CuiYifeng,
I tried to execute the mentioned code on tf-nightly(2.16.0-dev20240129) and it was executed without any issue and the output was also as expected. Kindly find the gist of it [here](https://colab.sandbox.google.com/gist/tilakrayal/122b9a07288f59b25577b6438d64c997/untitled1700.ipynb).

Also the related PR https://github.com/tensorflow/tensorflow/pull/62619 is also merged. Thank you!

**Comment by CuiYifeng** [comment]
@tilakrayal I also tried the case with tf-nightly mentioned and the case passed. Thanks for your information!
