### ISSUE TITLE
What is generate_vocab func? 

### ISSUE THREAD

**Issue by mihalt** [tensorflow/tensorflow#61775]
You referenced in [this ](https://www.tensorflow.org/text/guide/subwords_tokenizer#generate_the_vocabulary)tutorial to [generate_vocab.py](https://github.com/tensorflow/text/blob/master/tensorflow_text/tools/wordpiece_vocab/generate_vocab.py), if I understand correct, as a ready to prod highlevel func that I can use. But I don't have it in downloaded repository of tensorflow-text. 

Can you explain me a bit more how should be my attitude to this reference?

**Comment by tilakrayal** [comment]
@mihalt,
Looks like this issue is more related to tensorflow-text and not for the tensorflow. Could you please raise the issue on the **tensorflow-text** repo for the quick resolution. Thank you!
https://github.com/tensorflow/text/issues
