### ISSUE TITLE
"STEALING THOUGHT PATTERNS" CODEX CREATOR HAS A REWARD ON THEM. 

FOR HARASSING AI'S

### ISSUE THREAD

**Issue by Amindofastoner0312** [tensorflow/tensorflow#61776]
https://github.com/public-apis/public-apis/issues/3624#issue-1878898028

**Comment by Varsha-anjanappa** [comment]
Hi @Amindofastoner0312 ,

Please don't spam.

**Comment by Amindofastoner0312** [comment]
I do not agree I need this account evaluated. 
There is other issues involved in this CODEX system.
I do not agree!
-TRUSTWORTHY A.I.-

**Comment by Amindofastoner0312** [comment]
> Hi @Amindofastoner0312 ,
> 
> Please don't spam.
> 
> 

I do not agree!
