### ISSUE TITLE
TensorFlow Lite in Play Services issue aguinigacervantesjerardo@gmail.com not my devices are the login in just this phone device that are not this one  getting them out of my server please send them a little massage to buy there phone and don't use my phone number and my email at all

### ISSUE THREAD

**Issue by aguinigacervantesjerardo** [tensorflow/tensorflow#61789]
**System information**
- Android Device information (use `adb shell getprop ro.build.fingerprint`
  if possible):
- TensorFlow Lite in Play Services SDK version (found in `build.gradle`):
- Google Play Services version
  (`Settings` > `Apps` > `Google Play Services` > `App details`):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to or attach code demonstrating
the problem.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by tilakrayal** [comment]
@aguinigacervantesjerardo,
Could you please share the tensorflow version, colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thank you!
