### ISSUE TITLE
How to localize the position of object by using tensorflow

### ISSUE THREAD

**Issue by universewill** [tensorflow/tensorflow#6179]
The ILSVRC competition held by imagenet includes Object localization and Object detection and other tasks.

How did the convolutional neural network solve the localization problem? 
I can only find tutorials on classification task.

I think it is proper to add an example of localization in tensorflow tutorial.

**Comment by michaelisard** [comment]
This question is better suited to [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is a usage question not a bug report.
