### ISSUE TITLE
Strongly suggest to improve Tensorflow API document by adding examples

### ISSUE THREAD

**Issue by JacobIsrael123** [tensorflow/tensorflow#618]
Dear contributors, 
        I think the document of tensorflow is not good enough overall. 
        I really like Python and Numpy's official document, since they are give very **detailed explanation** and **importantly each concept has simple code example to illustrate the meaning, which helps a lot for easier understanding**. 
       However, tensorflow's document does not contains such example for illustration and the explanation is not in detail. 
       For example, the document for 
      ```tf.nn.in_top_k(predictions, targets, k, name=None)``` 
       spend me much time to guess what does it mean. The formula in it is not trivial to understand. 
       We could see in the **issue post** in this project that many of them are regarding the specific use of some method/function. 
       To once for all resolve this problem, please consider to improve the the overall document in the Python document fashion, it is very important for the popularity of tensorflow among all other similar tools. 
       Thank you all for your contribution for this project.

**Comment by martinwicke** [comment]
We have tried to include examples for complicated functions but more examples certainly wouldn't hurt. We'll gladly accept PRs for example code in function documentation.

**Comment by wentaozhu** [comment]
And there is no document or api on tf.nn.rnncell

**Comment by girving** [comment]
Closing for now since this isn't specific enough as a Github issue.  We're still happy accept PRs improving the documentation, and please file more specific documentation issues as separate bugs.
