### ISSUE TITLE
How to create a 5D tensor as the input of a 3DCNN

### ISSUE THREAD

**Issue by wookaka** [tensorflow/tensorflow#6180]
I try to create a 4D tensor as input of a 2DCNN. I am confused about how to create a 5DCNN .Is the 4D tensor as one of dimension of a 5D tensor? Is there someone who know the detials ?

**Comment by michaelisard** [comment]
This question is better suited to [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) as it is a usage question not a bug report.
