### ISSUE TITLE
Linux tensorflow build from source: bash failed genrule-setup.sh has carriage return

### ISSUE THREAD

**Issue by tomeeeS** [tensorflow/tensorflow#61801]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.13

### Custom code

Yes

### OS platform and distribution

Linux

### Python version

3.10

### Bazel version

5.3.0

### GCC/compiler version

LLVM = CLang = 16

### CUDA/cuDNN version

CPU only

### GPU model and memory

N/A

### Current behavior?

bazel build fails with "bash failed: error executing command", "/bin/bash: line 1: $'\r': command not found"
(bash failed, genrule-setup.sh has carriage return (windows line endings))
modifying this .sh file does not work, because bazel won't even start the build, saying that file is modified, it might be corrupt.

Docs need to tell us we should check out tf repo after 
`git config --global core.autocrlf input`
Thanks.

### Standalone code to reproduce the issue

```shell
# git config --global core.autocrlf input  # very important!!!  otherwise your bazel build will fail, because an invoked shell script will have Windows line endings.
# git config --global core.eol lf
git clone https://github.com/tensorflow/tensorflow.git &
cd tensorflow
git checkout -b r2.13 origin/r2.13
apt install python3.10-venv
cd ..

python3 -m venv tf_venv
tf_venv/bin/pip install -U pip numpy wheel packaging requests opt_einsum
tf_venv/bin/pip install -U keras_preprocessing --no-deps

wget https://github.com/bazelbuild/bazelisk/releases/download/v1.18.0/bazelisk-linux-amd64
mv bazelisk-linux-amd64 bazel
chmod +x bazel
mv -v bazel /usr/local/bin

#install clang-16 

cd tensorflow
../tf_venv/bin/python3 configure.py   # (dl clang: N, opti flag: -msse4.1)
bazel build  --local_ram_resources=2048 --jobs=4 --verbose_failures  //tensorflow/tools/pip_package:build_pip_package
```

**Comment by SuryanarayanaY** [comment]
Hi @tomeeeS ,

Could you please provide build command along with the bazel and compiler details used for build?

Thanks!

**Comment by tomeeeS** [comment]
@SuryanarayanaY 
Updated OP, excuse me for being sloppy

**Comment by sachinprasadhs** [comment]
Hi, 

Could you please Test against the 2.14 version and Master and let us know the outcome. Thanks!

**Comment by tomeeeS** [comment]
I believe I overcame it with `git config --global core.autocrlf true` when checking out tf. Thanks.
