### ISSUE TITLE
ValueError: Unable to create dataset (name already exists)

### ISSUE THREAD

**Issue by Alwaysadil** [tensorflow/tensorflow#61813]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.13.0

### Custom code

Yes

### Current behavior?

Epoch 1/10
1/1 [==============================] - ETA: 0s - loss: 6.8405 - accuracy: 0.3250
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-57-865e41f45523> in <cell line: 1>()
----> 1 transformer.fit(train_ds, epochs=EPOCHS, validation_data=val_ds,batch_size=BATCH_SIZE,callbacks=[early_stop, checkpoint_call, plot_losses])

2 frames
/usr/local/lib/python3.10/dist-packages/h5py/_hl/dataset.py in make_new_dset(parent, shape, dtype, data, name, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times, external, track_order, dcpl, dapl, efile_prefix, virtual_prefix, allow_unknown_filter, rdcc_nslots, rdcc_nbytes, rdcc_w0)
    161         sid = h5s.create_simple(shape, maxshape)
    162 
--> 163     dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl, dapl=dapl)
    164 
    165     if (data is not None) and (not isinstance(data, Empty)):

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5d.pyx in h5py.h5d.create()

ValueError: Unable to create dataset (name already exists)

i want to save each epoch as a checkpoint two weeks back back without any any error each checkpoint will save as a checkpoint but suddenly now getting error

### Standalone code to reproduce the issue

```shell
import matplotlib.pyplot as plt

from tensorflow.keras.callbacks import Callback


import os

checkpoint_dir = '/model/checkpoints_m_1'

if not os.path.exists(checkpoint_dir):
    os.makedirs(checkpoint_dir)
from tensorflow.keras.callbacks import EarlyStopping
early_stop = EarlyStopping(monitor='val_loss', patience=3)
# Set up the model checkpoint callback
checkpoint_call = ModelCheckpoint(filepath=checkpoint_dir+"/checkpoint_{epoch}.hdf5",
                                  monitor='val_loss',
                                  save_best_only=True,
                                  save_weights_only=False,
                                  mode='min',
                                  save_freq='epoch')
transformer.fit(train_ds, epochs=EPOCHS, validation_data=val_ds,batch_size=BATCH_SIZE,callbacks=[early_stop, checkpoint_call)
```

**Comment by sushreebarsa** [comment]
Hello, @Alwaysadil!
Could you please have a look at this [gist](https://colab.research.google.com/gist/sushreebarsa/f596ec59abbf469bd97beb1790337bb9/61813.ipynb) which shows a different error?
This error generally occurs when the layer names are duplicates across the namespaces of the pre-trained model and your downstream-task network. It can be useful to choose a unique name to call every layer of your downstream task network. Thank you!

**Comment by Alwaysadil** [comment]
Hi @sushreebarsa i resolved that issue by changing .hdf5 to .tf
Thank you for your response

**Comment by sushreebarsa** [comment]
@Alwaysadil True! It is always recommended to use .tf as  the saving format instead of .hdf5 after TF  v2.9.
Glad it worked for you! 
Could you please confirm if we can close the issue if it is resolved?

Thank you!

**Comment by sushreebarsa** [comment]
@Alwaysadil Thank you for the confirmation.
We will look into the other one. Thank you!
