### ISSUE TITLE
SummaryWriter.add_summary() gives error AttributeError: 'FileWriter' object has no attribute 'add_sumary'

### ISSUE THREAD

**Issue by amansehgal0u2** [tensorflow/tensorflow#6182]
I literally copied and pasted an example from the tensor board training site and it doesn't run.

summary, _ = sess.run([merged, train_step], feed_dict=feed_dict(True)) train_writer.add_summary(summary, i)

Both these lines give an error.
apparently sess.run returns a None type.

**Comment by amansehgal0u2** [comment]
I literally copied and pasted an example from the tensor board training site and it doesn't run.

`    summary, _ = sess.run([merged, train_step], feed_dict=feed_dict(True))
    train_writer.add_summary(summary, i)`

Both these lines give an error.
 apparently sess.run returns a None type.

**Comment by michaelisard** [comment]
Session.run should return a list of tensors in this case, see the [Session.run documentation](https://www.tensorflow.org/versions/r0.12/api_docs/python/client.html#Session). I recommend posting a more detailed description of the problem you are seeing on [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) which is the right venue for usage questions.
