### ISSUE TITLE
Build fail on TFLite C API for Android with CMake

### ISSUE THREAD

**Issue by ysohma** [tensorflow/tensorflow#61839]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.14.0-rc1

### Custom code

No

### OS platform and distribution

macOS 13.5.2

### Mobile device

Android

### Current behavior?

On version 2.14.0-rc1, Building TFLite C API for Android target with CMake fails by link error.
It works fine on version 2.13.0.

`ld: error: unable to find library -lpthread`
Error is caused by linking `pthread`. I guess pthread is unnecessary for android.

#### Extra information to my environment
- CMake: 3.26.4
- Android NDK: 25.2.9519653(r25c)

### Standalone code to reproduce the issue

```shell
mkdir tf-build
cd tf-build
cmake -DCMAKE_TOOLCHAIN_FILE=<NDK path>/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a ../tensorflow/lite/c
cmake --build . -j
```

### Relevant log output

```shell
...
[ 70%] Built target absl_status
[ 75%] Built target absl_flags
[ 95%] Built target tensorflow-lite
[100%] Linking CXX shared library libtensorflowlite_c.so
ld: error: unable to find library -lpthread
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libtensorflowlite_c.so] Error 1
make[1]: *** [CMakeFiles/tensorflowlite_c.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by pkgoogle** [comment]
I am able to reproduce and confirm that it does work in for r2.13. @terryheo, can you please take a look? Thanks.

**Comment by ChaseKnowlden** [comment]
Reproducible on master branch.

**Comment by ysohma** [comment]
@terryheo @pkgoogle 
It's be still reproduced on `2.14.0` and master branch.

**Comment by ysohma** [comment]
Let me share my analysis, 
I found https://github.com/tensorflow/tensorflow/commit/599baefe9e2ac8d16202553f01f252dc48cbda72 (by @daniel-lang)  brings error.

By this change, gemmlowp's CMake module add "pthread" to link_libraries(), but it's unwanted for Android target.
https://github.com/google/gemmlowp/blob/master/contrib/CMakeLists.txt#L27
That should be excluded on Android by if statement, for example.

One of straight-forward solution is to fix gemmlowp CMake and then switch GIT_TAG.
Another possible solution is to avoid use gemmlowp's CMakeLists.txt. It's more simple but I'm not sure that's doable.

**Comment by ysohma** [comment]
@fergushenderson 
Yes, I've just submitted PR for gemmlowp. https://github.com/google/gemmlowp/pull/212 

Also I already checked this change of gemmlowp can be fix tflite build error.

**Comment by ysohma** [comment]
I've submitted PR. https://github.com/tensorflow/tensorflow/pull/62330

**Comment by poltomo** [comment]
I am also having this issue, but how do I fix the tflite c build?

**Comment by poltomo** [comment]
@ysohma 
@fergushenderson
I am also having this issue, but how do I make the tflite c build work?

**Comment by ysohma** [comment]
@poltomo 
No. This problem was fixed by updating one of dependencies(gemmlowp). 
For detail, please check [this PR](https://github.com/tensorflow/tensorflow/pull/62330).
