### ISSUE TITLE
ConverterError: 'tf.FastWordpieceTokenizeWithOffsets' op is neither a custom op nor a flex op

### ISSUE THREAD

**Issue by Alwaysadil** [tensorflow/tensorflow#61850]
While doing tflite lite model conversion with input signature as string data type i am getting this error
ConverterError: /usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/func_graph.py:670:0: error: 'tf.FastWordpieceTokenizeWithOffsets' op is neither a custom op nor a flex op
:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/func_graph.py:670:0: note: Error code: ERROR_NEEDS_CUSTOM_OPS
/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/func_graph.py:670:0: error: 'tf.TFText>FastWordpieceDetokenize' op is neither a custom op nor a flex op
:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/func_graph.py:670:0: note: Error code: ERROR_NEEDS_CUSTOM_OPS
:0: error: failed while converting: 'main':
Some ops in the model are custom ops, See instructions to implement custom ops: https://www.tensorflow.org/lite/guide/ops_custom
Custom ops: FastWordpieceTokenizeWithOffsets, TFText>FastWordpieceDetokenize
Details:
tf.FastWordpieceTokenizeWithOffsets(tensor<?x!tf_type.string>, tensor<241460xui8>) -> (tensor<?x!tf_type.string>, tensor<?xi64>, tensor<?xi64>, tensor<?xi64>, tensor<?xi64>) : {device = "/device:CPU:0"}
tf.TFText>FastWordpieceDetokenize(tensor<40xi32>, tensor<2xi64>, tensor<339052xui8>) -> (tensor<?x!tf_type.string>) : {device = ""}

kindly please check this below colab link
https://colab.research.google.com/drive/14_ajVH4r4NXN6cDw96XJNBtltoueoGfN?usp=sharing

**Comment by sushreebarsa** [comment]
@Alwaysadil Thank you for raising the issue.
Please fill up the template with detailed information.
Hope you are using the latest version of TF , please follow the following to install the latest TF version, and restart the kernel. 
```
import tensorflow as tf

if tf.__version__ != '2.13.0':
  !pip uninstall -y tensorflow
  !pip install tensorflow-gpu==2.13.0
```
For more information on TFlite converter please follow the doc [here](https://www.tensorflow.org/lite/models/convert/). Thank you!

**Comment by Alwaysadil** [comment]
Hi @sushreebarsa ,thanks for your response

ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==2.13.0 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.12.0)
ERROR: No matching distribution found for tensorflow-gpu==2.13.0

**Comment by sushreebarsa** [comment]
Thank you for your response!
@Alwaysadil Could you please fill up this template which will help us to analyze the issue?
Thank you!

**Comment by Alwaysadil** [comment]
hi @sushreebarsa i didn't get what you said
you are saying to raise me a new issue?

**Comment by sushreebarsa** [comment]
@Alwaysadil , No i am not asking to create a new ticket. I am asking to fill out all the details related to the issue. You may edit your first comment else please provide the following information;

Issue type?

Have you reproduced the bug with TensorFlow Nightly?
Source?
TensorFlow version?
Custom code?
OS platform and distribution?
Mobile device?
Python version?
Bazel version?
GCC/compiler version?
CUDA/cuDNN version?
GPU model and memory?
Current behavior?
Expected behaviour?
Thank you!

**Comment by Alwaysadil** [comment]
**please check once my code https://colab.research.google.com/drive/14_ajVH4r4NXN6cDw96XJNBtltoueoGfN?usp=sharing**
**Issue type**:tflite lite model conversion with input signature as string data type 

**Have you reproduced the bug with TensorFlow Nightly**:No
**TensorFlow version**:2.13.0
Python version:3.10
**Current behavio**r: tflite lite model conversion with input signature as string data type i am getting this error
ConverterError: /usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/func_graph.py:670:0: error:
**Expected behaviour**:i want without any errors
Thank you!

**Comment by pkgoogle** [comment]
Hi @Alwaysadil, you have one or more custom ops in your model, so you need to identify which of your ops are custom and then follow the instructions here: https://www.tensorflow.org/lite/guide/ops_custom, give that a try and see how far you can get. Specifically from your Colab it looks like this one: tf.TFText>FastWordpieceDetokenize
