### ISSUE TITLE
Elu activation implementation 

### ISSUE THREAD

**Issue by samthakur587** [tensorflow/tensorflow#61861]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.13.0

### Custom code

Yes

### OS platform and distribution

ubuntu 20.04

### Current behavior?

The implementation of the Elu function is wrong the Elu function required the alpha value as is given in this [paper](https://arxiv.org/abs/1511.07289) that 

![image](https://github.com/tensorflow/tensorflow/assets/83540902/31c1f146-a623-43b7-ab0b-7c5632b43536)

but in tensorflow the Elu is implemented  without the alpha.

![image](https://github.com/tensorflow/tensorflow/assets/83540902/8f1a8117-1ef8-47e9-8643-8a033a60b997)

### Standalone code to reproduce the issue

```shell
#I have compared the result with torch because the elu fucntion in torch has implemnted with alpha. and #manually with the numpy and you can see that the tf is not using the alpha. and returning the wrong #result.

import tensorflow as tf
import numpy as np
import torch
print("tf version --> ",tf.version.VERSION,"\n")

x = np.array([-3.0])
alpha = 0.5
np_result = np.where(x > 0, x, np.multiply(alpha, np.expm1(x))).astype(x.dtype)
tf_result = tf.nn.elu(tf.constant([-3.0]))
torch_result = torch.nn.functional.elu(torch.Tensor([-3.0]),alpha=alpha)
print("tf result --> ",tf_result,"\n")
print("torch result --> ",torch_result,"\n")
print("numpy result --> ",np_result,"\n")
```

### Relevant log output

```shell
tf version -->  2.13.0 

tf result -->  tf.Tensor([-0.95021296], shape=(1,), dtype=float32) 

torch result -->  tensor([-0.4751]) 

numpy result -->  [-0.47510647]
```

**Comment by samthakur587** [comment]
hey @SuryanarayanaY this is my first contribution in tensorflow . if is there any thing else i have to add in the template please let me know. [here](https://gist.github.com/samthakur587/93ed3255ba8b0c81856e943576b85bb0) is my gist file.

**Comment by SuryanarayanaY** [comment]
Hi @samthakur587 , @VachanVY ,

Yeah the documentation seems wrong and also implementation. This is a low level API. I need to have a check on it. Yeah the source code link also not available now which we will have a look into.

You can use high level API for same which is [tf.keras.layers.ELU](https://www.tensorflow.org/api_docs/python/tf/keras/layers/ELU) and its working fine. Attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/f03c6a59421529b640cceaea86c574dd/61861.ipynb) for same.

**Comment by samthakur587** [comment]
Hi @SuryanarayanaY thanks for your comment. I am just exploring the tf activation function where i found this bug. its very helpful if you provide link of the code of this function and also any documentation where i can setup my testing environment for tf functions. I just want to understand the tf code and contribute to this repo.

Thanks 
samunder singh

**Comment by samthakur587** [comment]
Hii @SuryanarayanaY can you provide the link for the source code of this function. i want to make a PR and correct it.

**Comment by samthakur587** [comment]
Since it's not solved in new release 2.15

**Comment by SuryanarayanaY** [comment]
Hi @samthakur587 ,

The source code as Python wrapper not available now and it is getting generated from C++ backend. It's available at C++ backend.If you can able to work on C++ you can try it out.

**Comment by tilakrayal** [comment]
@samthakur587,
I tried to raise the PR for the similar API in the Keras function, and it was closed mentioning that it doesn't change anything though -- f(0) = 0 in either case. Which is easier to note as f(x) = x when x = 0. 

Please take a look at the PR which was raised for the same.
https://github.com/keras-team/keras/pull/20097

Thank you!
