### ISSUE TITLE
ERROR: No matching distribution found for tensorflow==2.12.0

### ISSUE THREAD

**Issue by huan415** [tensorflow/tensorflow#61873]
### Issue type

Others

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.12.0

### Custom code

Yes

### Current behavior?

 pip3 install tensorflow==2.12.0
 
 

### Standalone code to reproduce the issue

```shell
ERROR: Could not find a version that satisfies the requirement tensorflow==2.12.0 (from versions: 1.13.1, 1.13.2, 1.14.0, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 
2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 
2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0)
ERROR: No matching distribution found for tensorflow==2.12.0
```

**Comment by SouSingh** [comment]
Hello, @huan415 
I installed Tensorflow 2.12 on Windows using python -m pip install tensorflow==2.12.0. Please refer to the screenshots
![Screenshot (107)](https://github.com/tensorflow/tensorflow/assets/96938361/f25785e3-8143-47b4-9d50-1fbd3dc9ed44)

**Comment by sushreebarsa** [comment]
@huan415 Could you please find the matching distribution  for TF v2.12 as mentioned [here](https://www.tensorflow.org/install/source_windows#tested_build_configurations) in this official doc. Thank you!
