### ISSUE TITLE
Cast from int32 to float32 changes the value.

### ISSUE THREAD

**Issue by BMMevius** [tensorflow/tensorflow#61875]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.12.0 through tf-nightly (v1.12.1-99894-g5bef7ce6955 2.15.0-dev20230915)

### Custom code

Yes

### OS platform and distribution

nvcr.io/nvidia/tensorflow:23.07-tf2-py3 docker image

### Python version

3.10.6

### Current behavior?

Casting some int32 values to float32 causes a change in value.

### Standalone code to reproduce the issue

```shell
>>> tf.cast(tf.constant(52479843, tf.int32), tf.float32)
<tf.Tensor: shape=(), dtype=float32, numpy=52479844.0>
>>> tf.cast(tf.constant(52479845, tf.int32), tf.float32)
<tf.Tensor: shape=(), dtype=float32, numpy=52479844.0>
```
```


### Relevant log output

_No response_

**Comment by samriddha1904** [comment]
## Change the float32 to float64 to keep the value same
>>> tf.cast(tf.constant(52479843, tf.int32), tf.float64)
<tf.Tensor: shape=(), dtype=float32, numpy=52479843.0>
## same for this one too
>>> tf.cast(tf.constant(52479845, tf.int32), tf.float64)
<tf.Tensor: shape=(), dtype=float32, numpy=52479845.0>

**Comment by sushreebarsa** [comment]
@BMMevius Changing the float32 to float64 would give the same result in casting.  
 Please have a look at this [gist](https://colab.research.google.com/gist/sushreebarsa/0b30b3321838a98226cdd27448670b29/61875.ipynb). As per [this](https://github.com/tensorflow/tensorflow/blob/v2.13.0/tensorflow/python/ops/math_ops.py#L938-L1019) documentation, the operation supports data types (for `x` and `dtype`) of
  `uint8`, `uint16`, `uint32`, `uint64`, `int8`, `int16`, `int32`, `int64`,
  `float16`, `float32`, `float64`, `complex64`, `complex128`, `bfloat16`.
  In case of casting from complex types (`complex64`, `complex128`) to real
  types, only the real part of `x` is returned.

```
tf.cast(tf.constant(52479843, tf.int32), tf.float64)
<tf.Tensor: shape=(), dtype=float64, numpy=52479843.0>


```
```
tf.cast(tf.constant(52479845, tf.int32), tf.float64)
<tf.Tensor: shape=(), dtype=float64, numpy=52479845.0>
```

Thank you!

**Comment by BMMevius** [comment]
I see that the documentation states that there is a loss of precision when converting from a python datatype to a tensorflow datatype but it also happens when converting from a `tf.int32` to a `tf.float32`, which was not indicated by the documentation.
If there is a loss in precision between certain tf types, which I believe is going on, it might be useful to add that to the documentation as well.

**Comment by sushreebarsa** [comment]
@BMMevius Thank you for your response here. Could you please confirm if the original issue has been resolved.
Thank you!

**Comment by BMMevius** [comment]
The issues has not been resolved. Because the documentation is not complete about this precision issue.
