### ISSUE TITLE
Adding `@tf.function` changes model output

### ISSUE THREAD

**Issue by dengyinlin** [tensorflow/tensorflow#61885]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15.0-dev20230917

### Custom code

Yes

### Current behavior?

After adding `@tf.function` to the following model, the output `y` is wrong (`[[42, 36]]`). This issue only happens on CPU. On CUDA it is able to output the expected output (`[[42, 42]]`).

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
x1 = tf.constant([[6., 7.]], shape=[1, 2])

##### With @tf.function #####
class Model(tf.keras.Model):

  def __init__(self):
    super(Model, self).__init__()
    self.fc1 = tf.keras.layers.Dense(2, name='fc', kernel_initializer='ones', bias_initializer='ones')
    self.fc2 = tf.keras.layers.Dense(2, name='fc', kernel_initializer='ones', bias_initializer='ones')

  @tf.function
  def call(self, x):
    x = self.fc1(x)
    x = self.fc2(x)
    x = tf.constant([6.]) + x
    return tf.constant([7.]) + x

m = Model()
y = m(x1)
print(y.numpy())

##### Without @tf.function #####
class Model(tf.keras.Model):

  def __init__(self):
    super(Model, self).__init__()
    self.fc1 = tf.keras.layers.Dense(2, name='fc', kernel_initializer='ones', bias_initializer='ones')
    self.fc2 = tf.keras.layers.Dense(2, name='fc', kernel_initializer='ones', bias_initializer='ones')

  def call(self, x):
    x = self.fc1(x)
    x = self.fc2(x)
    x = tf.constant([6.]) + x
    return tf.constant([7.]) + x

m = Model()
expected_value = m(x1)
print(expected_value.numpy())
```

### Relevant log output

```shell
[[42. 36.]]
[[42. 42.]]
```

**Comment by YashIngle21** [comment]
Instead of using tf.constant([6.]) use just 6. and 7. it solves the issue

**Comment by YashIngle21** [comment]
I cant find the where the decorator is but this above solution solves the issue...Can someone please tell me where the decorator is located in the repo.

**Comment by dengyinlin** [comment]
Hi @YashIngle21 ,

In the code example above, in the first model, `def call(self, x)` is decorated with `@tf.function`.
Modifying the model code will indeed solve the issue. However, the bug here is the inconsistency with or without `@tf.function` conversion. Thanks!

**Comment by YashIngle21** [comment]
oh! ok i will try solving the issue...Thanks!!!

**Comment by SuryanarayanaY** [comment]
@dengyinlin ,

I have replicated the reported issue and acknowledging the difference in results. Attaching [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/f34ca877dc5b01949931369975d2b912/61885.ipynb) for reference.

As per my observation the first instance of `tf.constant` not adding to the computations though autograph is able to build a node for it. If we add 3 instances of tf.constant then also first instance getting ignored but remaining two instances are getting added. But as per autograph generated there are nodes generated for each of 3 instances.

IMO, this seems a bug and we need to dig more to find out root cause of this.

Thank you!

**Comment by bharatjetti** [comment]
Hi @dengyinlin 
I worked out the provided code snippet with the latest TensorFlow version, It is giving the expected output.Kindly find the attached screenshot.
<img width="1369" alt="Screenshot 2024-11-27 at 12 21 15 PM" src="https://github.com/user-attachments/assets/dc084fda-9c00-4d32-b730-2d29d4c7bc9f">
