### ISSUE TITLE
org.tensorflow:tensorflow-lite-task-vision:

### ISSUE THREAD

**Issue by B-JackMao** [tensorflow/tensorflow#61880]
implementation 'org.tensorflow:tensorflow-lite-task-vision:0.1.0'

Can I generate this dependency locally?

What instructions should I use to generate in TFlite?

**Comment by pjpratik** [comment]
Hi @B-JackMao 

Could you please fill the [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=comp%3Alite-in-play-services&projects=&template=tflite-in-play-services.md) and update to be relevant to the issue?

Please check [Build TensorFlow Lite](https://www.tensorflow.org/lite/android/lite_build) for Android that describes how to build TensorFlow Lite Android library on your own.

Thanks.
