### ISSUE TITLE
Extra semicolon in tensorflow/lite/micro/micro_profiler.h:90

### ISSUE THREAD

**Issue by matthewbstokes-zz** [tensorflow/tensorflow#61898]
Remove extra semicolon in tensorflow/lite/micro/micro_profiler.h on line 90

Before:
```
TF_LITE_REMOVE_VIRTUAL_DELETE;
```

After:
```
TF_LITE_REMOVE_VIRTUAL_DELETE
```

**Comment by tilakrayal** [comment]
@matthewbstokes-zz,
Thank you for pointing out the error. As this issue is related to **tf-lite/micro**, I raised the PR for the above mentioned error. Kindly find the PR details [here](https://github.com/tensorflow/tflite-micro/pull/2235) and will update once the related PR gets merged. Thank you!

**Comment by tilakrayal** [comment]
@matthewbstokes-zz,
The related PR got merged and the changes have been done in the mentioned file. Kindly find the reference below
https://github.com/tensorflow/tflite-micro/pull/2235

https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/micro_profiler.h#L90

```
  TicksPerTag total_ticks_per_tag[kMaxEvents] = {};

  int FindExistingOrNextPosition(const char* tag_name);

  TF_LITE_REMOVE_VIRTUAL_DELETE
};

#if defined(TF_LITE_STRIP_ERROR_STRINGS)
```

Thank you!
