### ISSUE TITLE
module 'tensorflow.python.distribute.input_lib' has no attribute 'DistributedDatasetInterface'

### ISSUE THREAD

**Issue by ls433** [tensorflow/tensorflow#61900]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.13.0

### Custom code

Yes

### OS platform and distribution

Google Colab

### Current behavior?

Very new to coding so am unfamiliar with what to say. I used tensor flow to run a model to find the best fitted line. Last week the model run perfectly. This week the script incurs an error upon running the model. Ran a script that was even older and incurred that same problem.

Had read that the issue is to do with conflict between _tensorflow_ and _keras_ but I don't understand what that means with relation to my code. 

I also read not to use the term 'python' when importing a library.

from tensorflow.**python**.keras.models import Sequential

I have to use 'python' as part of the syntax as google colab reports this message if I don't 
_Import "tensorflow.keras.models" could not be resolved(reportMissingImports)_

Is this something to so with my google colab environment? I updated tensorflow to the latest version but the problem still exists. 

I have no idea what to do and am quite stuck.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.activations import linear
from tensorflow.python.keras.optimizers import adam_v2
from tensorflow.python.keras.losses import MeanSquaredError

x = [ [23], [45], [78], [12]]
y = [ [12], [22], [36], [6]]

model = Sequential([
    tf.keras.layers.Dense(units=25, activation='relu', name='layer1'),
    tf.keras.layers.Dense(input_shape=(25,), units=15, activation='relu', name='layer2'),
    tf.keras.layers.Dense(input_shape=(15,), units=1, activation='linear', name='layer3')
] ,name="Model1"
)

loss=MeanSquaredError()
opt=adam_v2.Adam(learning_rate=0.001)

model.compile(
    loss=loss,
    optimizer=opt
    )
model.fit(x, y, epochs=100)
```

### Relevant log output

```shell
AttributeError                            Traceback (most recent call last)
<ipython-input-27-a1b963ff7586> in <cell line: 26>()
     24     optimizer=opt
     25     )
---> 26 model.fit(x, y, epochs=100)

6 frames
/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
   1136          training_utils.RespectCompiledTrainableState(self):
   1137       # Creates a `tf.data.Dataset` and handles batch and epoch iteration.
-> 1138       data_handler = data_adapter.get_data_handler(
   1139           x=x,
   1140           y=y,

/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in get_data_handler(*args, **kwargs)
   1396   if getattr(kwargs["model"], "_cluster_coordinator", None):
   1397     return _ClusterCoordinatorDataHandler(*args, **kwargs)
-> 1398   return DataHandler(*args, **kwargs)
   1399 
   1400 

/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weight, batch_size, steps_per_epoch, initial_epoch, epochs, shuffle, class_weight, max_queue_size, workers, use_multiprocessing, model, steps_per_execution, distribute)
   1150       self._steps_per_execution_value = steps_per_execution.numpy().item()
   1151 
-> 1152     adapter_cls = select_data_adapter(x, y)
   1153     self._adapter = adapter_cls(
   1154         x,

/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in select_data_adapter(x, y)
    986 def select_data_adapter(x, y):
    987   """Selects a data adapter than can handle a given x and y."""
--> 988   adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
    989   if not adapter_cls:
    990     # TODO(scottzhu): This should be a less implementation-specific error.

/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in <listcomp>(.0)
    986 def select_data_adapter(x, y):
    987   """Selects a data adapter than can handle a given x and y."""
--> 988   adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
    989   if not adapter_cls:
    990     # TODO(scottzhu): This should be a less implementation-specific error.

/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in can_handle(x, y)
    705   def can_handle(x, y=None):
    706     return (isinstance(x, (data_types.DatasetV1, data_types.DatasetV2)) or
--> 707             _is_distributed_dataset(x))
    708 
    709   def __init__(self,

/usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in _is_distributed_dataset(ds)
   1697 
   1698 def _is_distributed_dataset(ds):
-> 1699   return isinstance(ds, input_lib.DistributedDatasetInterface)

AttributeError: module 'tensorflow.python.distribute.input_lib' has no attribute 'DistributedDatasetInterface'
```

**Comment by PreWisdom** [comment]
same question

**Comment by sushreebarsa** [comment]
@ls433 
**tensorflow/python/keras** code is a legacy copy of Keras since the TensorFlow v2.7 release. Please remove any import of **tensorflow.python.keras** and use the public API **from tensorflow import keras** or **import tensorflow as tf**; **tf.keras**.

Thank you!

**Comment by ls433** [comment]
> @ls433 **tensorflow/python/keras** code is a legacy copy of Keras since the TensorFlow v2.7 release. Please remove any import of **tensorflow.python.keras** and use the public API **from tensorflow import keras** or **import tensorflow as tf**; **tf.keras**.
> 
> Thank you!

Thanks for the comment but unfortunately that doesn't work. 

I feel that I am missing something. How would you rewrite my importing of the libraries? The reason I ask is that the moment I remove the keyword 'python' it throws an immediate syntax error.

What I have found is that I can fix the issue by uninstalling the current version of tensor flow and instead installing a previous version (tensor flow version 2.12.0).

But I would prefer to understand what you are stating. So could you show me how to rewrite my code for importing the libraries correctly?

Thanks

**Comment by sushreebarsa** [comment]
@ls433 Thank you for your response here. As per your previous comment, is the issue not replicating in TF v2.12? 
Could you please confirm if the issue still replicates in TF v2,14?
Thank you!

**Comment by RubTalha** [comment]
https://stackoverflow.com/a/77733620/13086128

**Comment by Dhruv-Ganapati** [comment]
> @ls433 **tensorflow/python/keras** code is a legacy copy of Keras since the TensorFlow v2.7 release. Please remove any import of **tensorflow.python.keras** and use the public API **from tensorflow import keras** or **import tensorflow as tf**; **tf.keras**.
> 
> Thank you!

if i remove [ from tensorflow.python.keras import * ] this as you suggest, other part of the code doesn't work.  tensorflow.python.keras is very important for other part of the code sir.

**Comment by joojo-stephens** [comment]
> ### Issue type
> Bug
> 
> ### Have you reproduced the bug with TensorFlow Nightly?
> No
> 
> ### Source
> source
> 
> ### TensorFlow version
> 2.13.0
> 
> ### Custom code
> Yes
> 
> ### OS platform and distribution
> Google Colab
> 
> ### Mobile device
> _No response_
> 
> ### Python version
> _No response_
> 
> ### Bazel version
> _No response_
> 
> ### GCC/compiler version
> _No response_
> 
> ### CUDA/cuDNN version
> _No response_
> 
> ### GPU model and memory
> _No response_
> 
> ### Current behavior?
> Very new to coding so am unfamiliar with what to say. I used tensor flow to run a model to find the best fitted line. Last week the model run perfectly. This week the script incurs an error upon running the model. Ran a script that was even older and incurred that same problem.
> 
> Had read that the issue is to do with conflict between _tensorflow_ and _keras_ but I don't understand what that means with relation to my code.
> 
> I also read not to use the term 'python' when importing a library.
> 
> from tensorflow.**python**.keras.models import Sequential
> 
> I have to use 'python' as part of the syntax as google colab reports this message if I don't _Import "tensorflow.keras.models" could not be resolved(reportMissingImports)_
> 
> Is this something to so with my google colab environment? I updated tensorflow to the latest version but the problem still exists.
> 
> I have no idea what to do and am quite stuck.
> 
> ### Standalone code to reproduce the issue
> ```shell
> import tensorflow as tf
> 
> from tensorflow.python.keras.models import Sequential
> from tensorflow.python.keras.layers import Dense
> from tensorflow.python.keras.activations import linear
> from tensorflow.python.keras.optimizers import adam_v2
> from tensorflow.python.keras.losses import MeanSquaredError
> 
> x = [ [23], [45], [78], [12]]
> y = [ [12], [22], [36], [6]]
> 
> model = Sequential([
>     tf.keras.layers.Dense(units=25, activation='relu', name='layer1'),
>     tf.keras.layers.Dense(input_shape=(25,), units=15, activation='relu', name='layer2'),
>     tf.keras.layers.Dense(input_shape=(15,), units=1, activation='linear', name='layer3')
> ] ,name="Model1"
> )
> 
> loss=MeanSquaredError()
> opt=adam_v2.Adam(learning_rate=0.001)
> 
> model.compile(
>     loss=loss,
>     optimizer=opt
>     )
> model.fit(x, y, epochs=100)
> ```
> 
> ### Relevant log output
> ```shell
> AttributeError                            Traceback (most recent call last)
> <ipython-input-27-a1b963ff7586> in <cell line: 26>()
>      24     optimizer=opt
>      25     )
> ---> 26 model.fit(x, y, epochs=100)
> 
> 6 frames
> /usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
>    1136          training_utils.RespectCompiledTrainableState(self):
>    1137       # Creates a `tf.data.Dataset` and handles batch and epoch iteration.
> -> 1138       data_handler = data_adapter.get_data_handler(
>    1139           x=x,
>    1140           y=y,
> 
> /usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in get_data_handler(*args, **kwargs)
>    1396   if getattr(kwargs["model"], "_cluster_coordinator", None):
>    1397     return _ClusterCoordinatorDataHandler(*args, **kwargs)
> -> 1398   return DataHandler(*args, **kwargs)
>    1399 
>    1400 
> 
> /usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weight, batch_size, steps_per_epoch, initial_epoch, epochs, shuffle, class_weight, max_queue_size, workers, use_multiprocessing, model, steps_per_execution, distribute)
>    1150       self._steps_per_execution_value = steps_per_execution.numpy().item()
>    1151 
> -> 1152     adapter_cls = select_data_adapter(x, y)
>    1153     self._adapter = adapter_cls(
>    1154         x,
> 
> /usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in select_data_adapter(x, y)
>     986 def select_data_adapter(x, y):
>     987   """Selects a data adapter than can handle a given x and y."""
> --> 988   adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
>     989   if not adapter_cls:
>     990     # TODO(scottzhu): This should be a less implementation-specific error.
> 
> /usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in <listcomp>(.0)
>     986 def select_data_adapter(x, y):
>     987   """Selects a data adapter than can handle a given x and y."""
> --> 988   adapter_cls = [cls for cls in ALL_ADAPTER_CLS if cls.can_handle(x, y)]
>     989   if not adapter_cls:
>     990     # TODO(scottzhu): This should be a less implementation-specific error.
> 
> /usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in can_handle(x, y)
>     705   def can_handle(x, y=None):
>     706     return (isinstance(x, (data_types.DatasetV1, data_types.DatasetV2)) or
> --> 707             _is_distributed_dataset(x))
>     708 
>     709   def __init__(self,
> 
> /usr/local/lib/python3.10/dist-packages/tensorflow/python/keras/engine/data_adapter.py in _is_distributed_dataset(ds)
>    1697 
>    1698 def _is_distributed_dataset(ds):
> -> 1699   return isinstance(ds, input_lib.DistributedDatasetInterface)
> 
> AttributeError: module 'tensorflow.python.distribute.input_lib' has no attribute 'DistributedDatasetInterface'
> ```

If you're using an older or very new version, consider installing TensorFlow 2.12.0 or later:

**Comment by LouayZiani** [comment]
Hello, I had the same issue I solved it by running pip install tf-keras. It uninstalled and reinstalled keras to the latest version and downloaded the tf-keras package. 
(pip install tf-keras )
then when u import the libraries, do the following:
from tf_keras.models import Sequential
from tf_keras.layers import Conv2D, MaxPooling2D, Activation, Dropout, Flatten, Dense

**Comment by FadlGh** [comment]
> from tf_keras.models import Sequential
> from tf_keras.layers import Conv2D, MaxPooling2D, Activation, Dropout, Flatten, Dense

works for me, thanks!

**Comment by Pepito79** [comment]
> https://stackoverflow.com/a/77733620/13086128

That's working thanks !
