### ISSUE TITLE
Tensorflow pypi packages not found from TravisCI

### ISSUE THREAD

**Issue by igordertigor** [tensorflow/tensorflow#6191]
I am experiencing trouble installing tensorflow from TravisCI. As tensorflow 0.12.0rc0 is on pypi a simple

    pip install tensorflow

should install tensorflow (CPU). Yet, although this works locally, it does not work on Travis with the following error:

    Could not find any downloads that satisfy the requirement tensorflow==0.12.0rc0 (from -r requirements.txt (line 1))
      No distributions at all found for tensorflow==0.12.0rc0 (from -r requirements.txt (line 1))

According to [this scipy issue](https://github.com/scipy/scipy/issues/6213), it could be a problem with the packages that are being uploaded to pypi. In particular, there is a `cp27mu-manylinux` version for python 2.7 and `cp34m-manylinux` versions for python 3.4 (and also 3.5). The above issue seems to suggest that the "mu" versions would be used for python3 and the "m" versions for 2.7.

Other packages solve this problem by installing tensorflow from the URL. Given that tensorflow is now on pypi, the failure to import it from travis seems to point to a bug in your build system.

**Comment by martinwicke** [comment]
@yifeif can you take a look? I don't know why it would choke on the mu for 2.7, strange version of python in travis?

**Comment by igordertigor** [comment]
Hi yifeif,
unicode size is 4 on python 2.7 and `None` with python3.

If I use the URL to install, the installation terminates successfully, but I can't import tensorflow:

    ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.16' not found (required by /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so)

**Comment by yifeif** [comment]
Thanks @igordertigor for checking! 
Could you also check the pip version on travis?

Looking at the error , our binary might be built against a higher version of glibc than the ones you have. Please refer to [here](https://github.com/tensorflow/tensorflow/issues/5033#issuecomment-263681255) for more details 

Is it possible to upgrade them on your system?

**Comment by igordertigor** [comment]
Thank you @yifeif,
I'm running `pip install -U pip` before doing anything else on travis. So the pip version is currently the most recent one, `9.0.1`.

I agree that the issue you reference is likely to be related, but it seems as if the discussion there doesn't really include a fix that would work on travis. Or am I missing something there?

Also, I'm not quite sure what you mean by "them" when you ask if it is possible to upgrade them on my system. I can locally upgrade anything, but that wouldn't help on travis. Seems like upgrading glibc on travis is a bit of a hassle, but might work.

**Comment by yifeif** [comment]
I meant upgrading glibc on travis :). Could you give it a try?

**Comment by igordertigor** [comment]
Ok, upgrading glibc did not really work, but choosing a more recent ubuntu distribution (trusty rather than precise) seems to do the cut and I can import tensorflow.
