### ISSUE TITLE
lite hexagon后端ResizeNearestNeighbor算子层执行报错

### ISSUE THREAD

**Issue by hayyaw** [tensorflow/tensorflow#61935]
hexagon/src/newnode.c:413:node 3 (ResizeNearestNeighbor_8): bad input count 6
hexagon/src/newnode.c:763:node id=0x3 ctor fail
hexagon/src/prepare.c:4830:input 0x6:0 refers to nonexistent node 0x3
hexagon/src/prepare.c:4644:can't find id 0x3

----------------
ERROR: Failed: Failed to prepare graph.
.
ERROR: Node number 1 (TfLiteHexagonDelegate) failed to prepare.
ERROR: Restored original execution plan after delegate application failure.
Failed to apply Hexagon delegate.
Benchmarking failed.

**Comment by sushreebarsa** [comment]
@hayyaw 
In order to expedite the trouble-shooting process here, could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thank you!

**Comment by hayyaw** [comment]
System information

OS Platform and Distribution ：Linux Ubuntu 18.04
TensorFlow installed from (github):
TensorFlow version (dev分支):
Provide the text output from tflite_convert
none

Standalone code to reproduce the issue

tensorflow/lite/delegates/hexagon/builders/resize_nearest_neighbor_builder.cc

Any other info / logs
STARTING!
Duplicate flags: num_threads
Log parameter values verbosely: [0]
Min num runs: [1]
Graph: [/home/wangzhiqun/yolox_resize_nearest_neighbor.tflite]
Use Hexagon: [1]
Loaded model /home/wangzhiqun/yolox_resize_nearest_neighbor.tflite
INFO: Initialized TensorFlow Lite runtime.
Hexagon delegate created.
INFO: TfLiteHexagonDelegate delegate: 1 nodes delegated out of 1 nodes with 1 partitions.

INFO: Replacing 1 node(s) with delegate (TfLiteHexagonDelegate) node, yielding 1 partitions.
[hexagon/nn] Add Node: tid(-1) nid(1)
[hexagon_nn] hexagon_nn_append_const_node(gid=1 tid=2 nid=2 type=0x3)
[hexagon/nn] Add Node from Op(331) mid(0) nid(3)
[hexagon_nn] hexagon_nn_append_const_node(gid=1 nid=4 type=0x3)
[hexagon_nn] hexagon_nn_append_const_node(gid=1 nid=5 type=0x3)
[hexagon/nn] Add Node: tid(-1) nid(6)
[hexagon_nn] hexagon_nn_append_node(gid=1 nid=1 type=0x0)
[hexagon_nn] hexagon_nn_append_node(nis=0 nos=1)
[hexagon_nn] hexagon_nn_append_node(outputs[0].elementsize=1)
[hexagon_nn] hexagon_const_node(gid=1 nid=2 type=0x3)
[hexagon_nn] hexagon_nn_append_node(gid=1 nid=3 type=0x14b)
[hexagon_nn] hexagon_nn_append_node(nis=6 nos=3)
Error adding node: id:3, op_type:331
[hexagon_nn] hexagon_const_node(gid=1 nid=4 type=0x3)
[hexagon_nn] hexagon_const_node(gid=1 nid=5 type=0x3)
[hexagon_nn] hexagon_nn_append_node(gid=1 nid=6 type=0x1)
[hexagon_nn] hexagon_nn_append_node(nis=1 nos=0)
Timestamp: Thu Sep 21 08:06:06 2023

Log
hexagon/src/newnode.c:413:node 3 (ResizeNearestNeighbor_8): bad input count 6
hexagon/src/newnode.c:763:node id=0x3 ctor fail
hexagon/src/prepare.c:4830:input 0x6:0 refers to nonexistent node 0x3
hexagon/src/prepare.c:4644:can't find id 0x3

ERROR: Failed: Failed to prepare graph.
.
ERROR: Node number 1 (TfLiteHexagonDelegate) failed to prepare.
ERROR: Restored original execution plan after delegate application failure.
Failed to apply Hexagon delegate.
Benchmarking failed.

**Comment by pjpratik** [comment]
Hi @hayyaw 

Could you please provide a reproducible code and steps you have followed? It is hard to understand the issue from error log. Please please fill this issue [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=TFLiteConverter&projects=&template=tflite-converter-issue.md).

Thanks.

**Comment by darkprime** [comment]
I am having the exact same problem with multiple TFLITE models I have made full quantized versions to run on the hexagon.
