### ISSUE TITLE
gradients for assign/tf.scatter_update, etc

### ISSUE THREAD

**Issue by cle-ros** [tensorflow/tensorflow#6193]
Hello,

I was wondering whether there is a specific reason for tf.assign not having gradients.

I think that it would make sense that tf.assign, i.e. a call of the form `variable.assign(value)` "inherits" the gradients from value, such that `grad(variable) = grad(value)`, after the assignment.

This would be especially useful within the context of the scatter-update functions, since those are one of the most convenient ways to avoid indexing and do partial updates of variables.

If there are cases where this is not required, assign could maybe take an argument that allows this, such as "inherit_gradients", or some such, do not break compatibility.

Thank you!

**Comment by michaelisard** [comment]
@girving can you comment?

**Comment by girving** [comment]
@cle-ros Can you give me an example of what new correct behavior it would allow?  It seems likely that it would also allow a lot of silently weird, unexpected behavior (whenever the pattern of imperative updates doesn't fit with the case you have in mind), so I'd be leery.

**Comment by cle-ros** [comment]
Thank you for your quick response!

There are two cases where this could be useful. The might be recurrences, since this would allow to make updates explicit. (I'm not sure here, though)

The second, which I am more interested in, is that I have several update functions I only want to apply to specific parts of my tensor, like with the following numpy code:
```
a = np.zeros((10,10))  # this 
b = [(1,3), (3,5), (2,4)]
for index in b:
    a[index] = some_other_function
```
Considering that tf.scatter_update looks like a function designed for these cases, it not being differentiable (if some_other_function is) requires me to do quite a lot of additional work to perform the same step.

**Comment by girving** [comment]
@cle-ros I think you're asking for a much more complicated feature than you think you're asking for.  Simply declaring the gradient of assignment to be something specific won't help you; you want these gradient updates to be chained through imperative updates to variables to track the overflow flow.  Unfortunately, this is out of scope for TensorFlow as is, since we never track anything across variable updates.

**Comment by cle-ros** [comment]
@girving Haha, thanks, I can see how that may be the case. Anyways, I'll just continue using my existing code. Thanks for your quick response.

**Comment by girving** [comment]
"recurrences" is a perfectly fine word, but I'm not sure what it refers to in this context.

**Comment by cle-ros** [comment]
:-) I mean that you update the variable - including it's gradients - at a later point in the code. When I had this thought, I was thinking of recurrence relationships, where you initialize your variable to one value, and later update it to another that you might have wanted to differentiate.

However, I just realized my mistake - the graph has to be static for the gradient calculation (which afaik only happens once and is not updated). So updating a variable like this, or having a separate variable, should end up being the same. Thanks again! 

I'll close this issue now.
