### ISSUE TITLE
A call of the model which is reloaded from SavedModel format produces a TypeError

### ISSUE THREAD

**Issue by molokanov50** [tensorflow/tensorflow#61949]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.13

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.9

### CUDA/cuDNN version

12.2

### Current behavior?

A call of the model which is reloaded from SavedModel format produces a `TypeError: '_UserObject' object is not callable`.
All necessary code is in [this tutorial](https://www.tensorflow.org/text/tutorials/transformer). Below I show code lines from there, where the error occurs.

### Standalone code to reproduce the issue

```shell
reloaded = tf.saved_model.load('translator')
reloaded('este é o primeiro livro que eu fiz.').numpy()
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/molokanov/tensorflow/check.py", line 13, in <module>
    reloaded('este é o primeiro livro que eu fiz.').numpy()
TypeError: '_UserObject' object is not callable
```

**Comment by tilakrayal** [comment]
@molokanov50,
Apologies for the delay. When i tried to save the model with the same configuration as you mentioned, it had only one .pb file saved_model.pb. Size of the model ~3.4MB.

Also try to use keras load model to load your model.

```
from tensorflow import keras

new_model = keras.models.load_model("save_model_keras")
new_model.summary()
```

Thank you!
