### ISSUE TITLE
Can I reshape Tensor in C++ like Caffe's Blob

### ISSUE THREAD

**Issue by philokey** [tensorflow/tensorflow#6194]
Hello,
I want to use tensors of dynamic shapes in C++.
Can I reshape Tensor like Caffe's Blob, which means after reshape, the  total size of new tensor  can be unchanged.

**Comment by michaelisard** [comment]
This type of usage question is better asked on [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow)
