### ISSUE TITLE
TensorFlow.js: export failure ❌ 0.6s: [Errno 2] No such file or directory: 'tensorflowjs_converter'

### ISSUE THREAD

**Issue by lindow2009** [tensorflow/tensorflow#61948]
System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MAC OS
TensorFlow installed from (source or binary): binray
TensorFlow version (use command below): 2.13.0
TensorFlowJS version: 4.11.0
Python version: 3.9
When I using tensorflowjs_converter to convert pt model:

TensorFlow SavedModel: export success ✅ 29.7s, saved as yolov5n-seg_saved_model (7.9 MB)

TensorFlow GraphDef: starting export with tensorflow 2.13.0...
TensorFlow GraphDef: export success ✅ 3.7s, saved as yolov5n-seg.pb (7.9 MB)
WARNING ⚠️ invalid check_version(4.11.0, ) requested, please check values.

TensorFlow.js: starting export with tensorflowjs 4.11.0...
TensorFlow.js: export failure ❌ 0.6s: [Errno 2] No such file or directory: 'tensorflowjs_converter'

tensorflowjs_converter not founded

**Comment by pjpratik** [comment]
Hi @lindow2009 

This seems to be related to tensorflow js converter issue from the information provided.

Please post this issue in tensorflow.js repo for faster resolution,
https://github.com/tensorflow/tfjs/issues

Thanks.
