### ISSUE TITLE
ValueError: Exception encountered when calling layer "13" (type Lambda).

### ISSUE THREAD

**Issue by pzy2000** [tensorflow/tensorflow#61958]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.13

### Custom code

Yes

### OS platform and distribution

5.15.90.1-microsoft-standard-WSL2

### Python version

3.8.17

### CUDA/cuDNN version

12.2

### Current behavior?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/pengg/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/pengg/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

ValueError:   Exception encountered when calling layer "13" (type Lambda).          Dimensions must be equal, but are 204 and 206 for '{{node 13/Add}} =   AddV2[T=DT_FLOAT](Placeholder, Placeholder_1)' with input shapes:   [?,64,204,204], [?,64,206,206].          Call arguments received by layer "13" (type Lambda):       • inputs=['tf.Tensor(shape=(None,   64, 204, 204), dtype=float32)', 'tf.Tensor(shape=(None, 64, 206, 206),   dtype=float32)']       • mask=None       • training=None
--

</body>

</html>

### Standalone code to reproduce the issue

```shell
just run the following code to reproduce:

from onnx2keras import onnx_to_keras
import keras
import onnx
import sys
# sys.path.append("/root/MR")
onnx_model = onnx.load('yolov3_darknet53.onnx')
onnx_inputs = onnx_model.graph.input
print("===========================")
print(onnx_inputs)
# onnx_model = onnx.load('vgg11.onnx')
k_model = onnx_to_keras(onnx_model, ['x'], name_policy='renumerate', verbose=True)
keras.models.save_model(k_model, 'ssd_resnet50fpn_torch.h5', overwrite=True, save_format="h5")
```
the onnx file can be downloaded at https://pan.xunlei.com/s/VNf1FtBh2v6mP_QXJWVailBmA1?pwd=g43e#
```


### Relevant log output

```shell
Traceback (most recent call last):
  File "o2k.py", line 11, in <module>
    k_model = onnx_to_keras(onnx_model, ['x'], name_policy='renumerate', verbose=True)
  File "/root/miniconda3/envs/onnx/lib/python3.8/site-packages/onnx2keras/converter.py", line 175, in onnx_to_keras
    AVAILABLE_CONVERTERS[node_type](
  File "/root/miniconda3/envs/onnx/lib/python3.8/site-packages/onnx2keras/elementwise_layers.py", line 83, in convert_elementwise_add
    layers[node_name] = lambda_layer([input_0, input_1])
  File "/root/miniconda3/envs/onnx/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/root/miniconda3/envs/onnx/lib/python3.8/site-packages/onnx2keras/elementwise_layers.py", line 76, in target_layer
    layer = tf.add(
ValueError: Exception encountered when calling layer "LAYER_12" (type Lambda).

Dimensions must be equal, but are 204 and 206 for '{{node LAYER_12/Add}} = AddV2[T=DT_FLOAT](Placeholder, Placeholder_1)' with input shapes: [?,64,204,204], [?,64,206,206].

Call arguments received by layer "LAYER_12" (type Lambda):
  • inputs=['tf.Tensor(shape=(None, 64, 204, 204), dtype=float32)', 'tf.Tensor(shape=(None, 64, 206, 206), dtype=float32)']
  • mask=None
  • training=None
```

**Comment by mihaimaruseac** [comment]
This at most belongs to keras, not TF
