### ISSUE TITLE
Use github.com/apssouza22/chatflow as a conversational layer. It would enable actual API requests to be carried out from natural language inputs.

### ISSUE THREAD

**Issue by GiovanniSmokes** [tensorflow/tensorflow#61969]
### Issue type

Feature Request

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

all of em

### Custom code

Yes

### Current behavior?

Fine as hell

### Standalone code to reproduce the issue

```shell
n/a
```

### Relevant log output

```shell
i <3 tensorflow
```

**Comment by mihaimaruseac** [comment]
Doesn't belong in the repo, looks more like promo/spam
