### ISSUE TITLE
AttributeError: Can't gather from tf tensor.

### ISSUE THREAD

**Issue by pzy2000** [tensorflow/tensorflow#61960]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.13

### Custom code

Yes

### OS platform and distribution

5.15.90.1-microsoft-standard-WSL2

### Python version

3.8.17

### CUDA/cuDNN version

12.2

### Current behavior?

Traceback (most recent call last):
  File "o2k.py", line 11, in <module>
    k_model = onnx_to_keras(onnx_model, ['onnx::Cast_0', 'onnx::Cast_1'], name_policy='renumerate', verbose=True)
  File "/root/miniconda3/envs/onnx/lib/python3.8/site-packages/onnx2keras/converter.py", line 175, in onnx_to_keras
    AVAILABLE_CONVERTERS[node_type](
  File "/root/miniconda3/envs/onnx/lib/python3.8/site-packages/onnx2keras/reshape_layers.py", line 87, in convert_gather
    raise AttributeError('Can\'t gather from tf tensor.')
AttributeError: Can't gather from tf tensor.

### Standalone code to reproduce the issue

```shell
please run the codes below to reproduce:

from onnx2keras import onnx_to_keras
import keras
import onnx
import sys
# sys.path.append("/root/MR")
onnx_model = onnx.load('fasttext_torch.onnx')
onnx_inputs = onnx_model.graph.input
print("===========================")
print(onnx_inputs)
# onnx_model = onnx.load('vgg11.onnx')
k_model = onnx_to_keras(onnx_model, ['onnx::Cast_0', 'onnx::Cast_1'], name_policy='renumerate', verbose=True)
keras.models.save_model(k_model, 'fasttext_torch.h5', overwrite=True, save_format="h5")
```
onnx file can be downloaded at https://pan.xunlei.com/s/VNf1LHoMqVe2TuzMTA8uhjO5A1?pwd=ibm3#
```


### Relevant log output

```shell
Traceback (most recent call last):
  File "o2k.py", line 11, in <module>
    k_model = onnx_to_keras(onnx_model, ['onnx::Cast_0', 'onnx::Cast_1'], name_policy='renumerate', verbose=True)
  File "/root/miniconda3/envs/onnx/lib/python3.8/site-packages/onnx2keras/converter.py", line 175, in onnx_to_keras
    AVAILABLE_CONVERTERS[node_type](
  File "/root/miniconda3/envs/onnx/lib/python3.8/site-packages/onnx2keras/reshape_layers.py", line 87, in convert_gather
    raise AttributeError('Can\'t gather from tf tensor.')
AttributeError: Can't gather from tf tensor.
```

**Comment by mihaimaruseac** [comment]
This at most belongs to keras, not TF

**Comment by SuryanarayanaY** [comment]
Hi @pzy2000 ,

We can't say for sure whether it is related to tensorflow or keras since there is another library i.e `onxx` involved here.

Could you please submit a code without external libraries dependencies to reproduce the reported issue.We are not sure whether its bug in `onxx` or `TF/keras`.

Thank you!
