### ISSUE TITLE
also missing from the include "patch" is file "tensorflow/tsl/c/tsl_status.h" (there might be others)

### ISSUE THREAD

**Issue by esohns** [tensorflow/tensorflow#61964]
also missing from the include "patch" is file "tensorflow/tsl/c/tsl_status.h" (there might be others)

_Originally posted by @esohns in https://github.com/tensorflow/tensorflow/issues/59762#issuecomment-1732376736_

**Comment by esohns** [comment]
note: this issue picks up where #59762 left off

**Comment by SuryanarayanaY** [comment]
@esohns ,

Thanks for your time bringing this.I have gone through the older ticket #59762, understood the context and it seems there might be a fix for this. Would it still exists in latest versions also ? Please confirm meanwhile I will bring this to the attention of concerned team.

Windows builds are maintained by the intel team, hence I am bringing the issue to their attention to fix it if not fixed already in latest/nightly version.

CC- @TensorFlow-MKL for comments.

Thank you!

**Comment by mraunak** [comment]
Hi @esohns and @SuryanarayanaY, this should be fixed in the upcoming releases. Thank you!

**Comment by nitins17** [comment]
@esohns Thanks for letting us know! It does seem like we were missing certain headers in the Windows libtensorflow archive. https://github.com/tensorflow/tensorflow/commit/66681ea34bee93fa359486458f92ceea864cc6de should fix it.

**Comment by esohns** [comment]
ok thank you for fixing this issue

**Comment by wo80** [comment]
@nitins17 Before opening a separate issue, I'm trying my luck here:

comparing the `libtensorflow-cpu-linux-x86_64-2.15.0.tar.gz` and the `libtensorflow-cpu-windows-x86_64-2.15.0.zip` archives on https://www.tensorflow.org/install/lang_c, the following headers are missing from the windows archive:
```
include/tensorflow/c/tf_buffer.h
include/tensorflow/c/tf_tensor_helper.h
include/tsl/c/tsl_status.h
include/tsl/platform/ctstring.h
include/tsl/platform/ctstring_internal.h
```
Could that package be updated, including the missing files? Or is there another source for the prebuilt windows binaries?

**Comment by SPaschun** [comment]
welche vorausetzungen muss eine dll erfüllen um mit folgendem befehl geladen werden zu können
