### ISSUE TITLE
Windows 10 Source build failure if python installed in a directory with spaces

### ISSUE THREAD

**Issue by ArttuLinden** [tensorflow/tensorflow#61971]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.10

### Custom code

Yes

### OS platform and distribution

Windows 10

### Python version

3.9.13

### Bazel version

5.1.1

### CUDA/cuDNN version

11.2/8.1.1

### GPU model and memory

Quadro P2000 / 5 Gb

### Current behavior?

Building 2.10 tensorflow with cuda support from sources using Bazel 5.1.1 would result in an error if the python is downloaded in a directory with spaces. In my case I had python installed under `C:/Program Files/python39`. The error showed that: `'c:/program' is not recognized as an internal or external command building tensorflow'`. I traced this error into the `tensorflow\third_party\gpus\cuda_configure.bzl` file. In this file there is a function called `_check_cuda_libs` (line 492). This function checks the precense of cuda libraries by compling a cmd. However, the cmd won't work if the python_bin points to a python executive which is located in a directory with spaces. This error was simply fixed by moving python to a directory without spaces (No need to change the scripts inside `.bzl` file).

### Standalone code to reproduce the issue

```shell
You should be able to reproduce the issue by following the "Build from source on Windows" instructions and downloading python for example under "Program Files" folder. Build should be configured to include CUDA support. I used the following build command: bazel build --config=opt --config=cuda --define=no_tensorflow_py_deps=true //tensorflow/tools/pip_package:build_pip_package
```

**Comment by sushreebarsa** [comment]
@ArttuLinden GPU support on native-Windows is only available for 2.10 or earlier versions, starting in TF 2.11, CUDA build is not supported for Windows. For using TensorFlow GPU on Windows, you will need to build/install TensorFlow in WSL2 or use tensorflow-cpu with TensorFlow-DirectML-Plugin. Please check the configuration for TF v2.10 as mentioned [here](https://www.tensorflow.org/install/source_windows#gpu). Thank you!

**Comment by ArttuLinden** [comment]
Hi, I am aware that 2.10 is the latest version for native windows to support tensorflow GPU. I have followed the guideline and my current configuration matches with `tensorflow_gpu-2.10.0 | 3.7-3.10 | MSVC 2019 | Bazel 5.1.1 | 8.1 | 11.2`. As I stated it is a bug in the `cuda_configure.bzl` that python_bin_path can't point to a python executive where the path contains spaces. Function `_check_cuda_libs (line 492)`. Especially these lines in the `cuda_configure.bzl` cause the error:

cmd += "system('%s script.py %s');" % (python_bin, args)
all_paths = [path for path, _ in libs]
checked_paths = execute(repository_ctx, [python_bin, "-c", cmd]).stdout.splitlines()

PYTHON_BIN_PATH=C:/Python39/python.exe -- This works
PYTHON_BIN_PATH=C:/Program Files/Python39/python.exe -- This fails

**Comment by mraunak** [comment]
@ArttuLinden, can you pls try PYTHON_BIN_PATH=C:/Program\ Files/Python39/python.exe
or try C:\Program Files\Python39\python.exe
Please let us know if you face any issue further or if the error persists
