### ISSUE TITLE
con't build_pip_package

### ISSUE THREAD

**Issue by OptNuo** [tensorflow/tensorflow#61987]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf1.14.0

### Custom code

No

### OS platform and distribution

Linux Ubuntu 18.04

### Python version

3.6.9

### Bazel version

bazel 0.24.1

### GCC/compiler version

gcc 4.8

### GPU model and memory

 intel i7-9750H   12g

### Current behavior?

tensorflow/python/lib/core/bfloat16.cc:608:60: note: no known conversion for argument 2 from '<unresolved overloaded function type>' to 'PyUFuncGenericFunction {aka void ()(char**, const long int, const long int*, void*)}'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4163.570s, Critical Path: 161.91s
INFO: 5035 processes: 5035 local.
FAILED: Build did NOT complete successfully

### Standalone code to reproduce the issue

```shell
bazel build --jobs=6 //tensorflow/tools/pip_package:build_pip_package
```

**Comment by tilakrayal** [comment]
@OptNuo,
We see that you are using tensorFlow v1.14 which is not actively supported. Requesting you to please try to install the TensorFlow to the latest stable version v2.13 and check if you are facing the same issue.

Could you please try to follow the steps which are mentioned in the tensorflow official document for the smooth installation.
https://www.tensorflow.org/install

 Thank you!
