### ISSUE TITLE
Why support for Python 3.8 has been removed in Tensorflow 2.14

### ISSUE THREAD

**Issue by harupy** [tensorflow/tensorflow#61996]
Not an issue, but a question. Just out of curiosity, Why has support for Python 3.8 been removed in Tensorflow 2.14?

**Comment by tilakrayal** [comment]
@harupy,
AFAIK, As part of the upgrade, Python 3.8 has been removed from Tensorflow 2.14. But the TensorFlow 2.13.1 patch release will still have Python 3.8 support.
https://github.com/tensorflow/tensorflow/releases
Could please allow me to do a deep dive into the same questions and provide an update. Thank you!

**Comment by harupy** [comment]
@tilakrayal Thanks!

**Comment by harupy** [comment]
Perhaps it's because pandas and numpy already dropped Python 3.8 support in their latest versions?

**Comment by harupy** [comment]
@sachinprasadhs makes sense, thanks for the clarification!
