### ISSUE TITLE
CUDNN error on "import tensorflow as tf" for gpu version

### ISSUE THREAD

**Issue by Russell91** [tensorflow/tensorflow#62]
I'm getting the following error when I try to run the gpu version.

I tensorflow/stream_executor/dso_loader.cc:77] LD_LIBRARY_PATH: :/usr/local/cuda-7.0/lib:/usr/local/cuda-7.0/lib64:/usr/local/cuda-7.0/lib64:/usr/local/lib
I tensorflow/stream_executor/cuda/cuda_dnn.cc:1062] Unable to load cuDNN DSO.

**Comment by Russell91** [comment]
Make sure you reference http://tensorflow.org/get_started/os_setup.md#install_cuda
and install cudnnv2, not cudnnv3.

**Comment by Shoaibkw** [comment]
Please let me know what if I have this error with cuda-8.0 

I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcudnn.so.5. LD_LIBRARY_PATH: /usr/local/cuda-8.0/lib64
