### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by kloro2006** [tensorflow/tensorflow#62019]
On this page:

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/distributed_runtime

there is a link at the bottom which doesn't work. Its label is "Distributed TensorFlow".

**Comment by a-r-r-o-w** [comment]
Is [this](https://www.tensorflow.org/guide/distributed_training) the correct link where it should point to?

**Comment by ParamThakkar123** [comment]
@a-r-r-o-w  i too think so

**Comment by sushreebarsa** [comment]
@kloro2006 Thank you for raising this issue! 
We have raised a fix internally which will resolve this issue. Thank you!
