### ISSUE TITLE
Can't import tensorflow

### ISSUE THREAD

**Issue by YaroslavPavlovich** [tensorflow/tensorflow#62028]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

any version

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.8

### Current behavior?

I want to install Tensorflow for my system. I installed it by "pip install tensorflow". 
I have:
python3.8
Ubuntu 20.04
Intel Core I9 12 Gen
Nvidia GeForce 3090 TI

### Standalone code to reproduce the issue

```shell
import tensorflow
Illegal instruction (core dumped)
```

**Comment by sushreebarsa** [comment]
@YaroslavPavlovich I was able to import tensorflow on colab , please find the [gist](https://colab.research.google.com/gist/sushreebarsa/c1e21d1a8fed7c92c12b271f2e92cefa/62028.ipynb) here. Could you please have a look at the system [requirements](https://www.tensorflow.org/install/pip#software_requirements) and follow the instructions provided in the documentation. Thank you!

**Comment by YaroslavPavlovich** [comment]
I also run with ` docker run -it --rm tensorflow/tensorflow bash` with latest version of tensorflow.
But I have the same problem:
```
root@b533c1553888:/# python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
Illegal instruction (core dumped)
```

**Comment by sushreebarsa** [comment]
@YaroslavPavlovich Thank you for your response!
Could you please make sure that [these](https://www.tensorflow.org/install/docker) instructions were followed properly. Thank you!

**Comment by YaroslavPavlovich** [comment]
Here is an instruction on how to run a Docker container using TensorFlow. There are also links provided for installing Docker with GPU support and without it.
![image](https://github.com/tensorflow/tensorflow/assets/52659241/8665cfe1-6a3c-421c-a0fe-60cd08b5af55)
Everything is ok with GPU in docker. Docker is installed correctly.
If I installed tensorflow for another computer with Intel COre I7 10 Gen, it is working ok.

**Comment by sushreebarsa** [comment]
@YaroslavPavlovich Thank you for your response again!
Did you try upgrading the Python version and check if your system satisfies all the requirements?
Thank you!

**Comment by YaroslavPavlovich** [comment]
it is python3.11 in docker
CUDA version 11.8 (nvidia-smi returns 12.0)
Driver version is 525.85.12
pip version in docker is normal too
OS  is suitable
anything else?

**Comment by YaroslavPavlovich** [comment]
I tried with python 3.11

**Comment by SuryanarayanaY** [comment]
Hi @YaroslavPavlovich, 

For GPU package you need to use `pip install tensorflow[and-cuda]` command.With this only we can able to get GPU list. Could you please try and confirm?
 
Thanks!

**Comment by YaroslavPavlovich** [comment]
https://github.com/tensorflow/tensorflow/issues/61986?ysclid=lnn9iziiq693897091
I have the sane problem but with python3.9

**Comment by YaroslavPavlovich** [comment]
I tried this
`pip install tensorflow==2.14.0 nvidia-cuda-runtime-cu11==11.8.89 nvidia-cublas-cu11==11.11.3.6 nvidia-cufft-cu11==10.9.0.58 nvidia-cudnn-cu11==8.7.0.84 nvidia-curand-cu11==10.3.0.86 nvidia-cusolver-cu11==11.4.1.48 nvidia-cusparse-cu11==11.7.5.86 nvidia-nccl-cu11==2.16.5 nvidia-cuda-cupti-cu11==11.8.87 nvidia-cuda-nvcc-cu11==11.8.89
`
this is the same result with Illegal instruction (core dumped)

I think this is a problem with my PC, but I don't know why. I tried install on another PC with Intel Core I7 10 Gen and Nvidia GeForce 1650 Ti it is ok.
This problem with Intel Core I9 12 Gen and Nvidia GeForce 3090 TI

**Comment by SuryanarayanaY** [comment]
Hi @YaroslavPavlovich ,

The issue might be related to your environment.You can find the suitable Nvidia driver for your GPU from [here](https://www.nvidia.com/Download/index.aspx). For Geoforce 3090 TI , it is suggesting 535.129.03 driver. Maybe you can try with it.
