### ISSUE TITLE
Models that trained and saved on Tensorflow2.14 cant be loaded on Tensorflow2.12

### ISSUE THREAD

**Issue by sagi21805** [tensorflow/tensorflow#62026]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.14

### Custom code

Yes

### OS platform and distribution

Linux mint 21.2

### Python version

3.11

### GPU model and memory

gtx 1060 6gb

### Current behavior?

I expected that when I load a keras model that I trained on my home computer on tensorflow 2.14 wil be loaded on kaggle notebook which has tensorflow 2.12

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

#the test_model.keras was trained on tensorflow version 2.14
#the current tensorflow version in 2.12

model = tf.keras.models.load_model("/home/sagi/Desktop/VsCode/Competiton/MODEL/test_model.keras")
```

**Comment by sushreebarsa** [comment]
@sagi21805 Generally error will occur if the model you are trying to load was saved using a different version of TensorFlow than the one you are currently using. Also try to use the following for loading the model and for more information on saving or loading the model please have a look at [this](https://www.tensorflow.org/api_docs/python/tf/keras/saving/load_model) doc.
```
 model =  tf.keras.saving.load_model("path")
```
Thank you!
