### ISSUE TITLE
ValueError in tensorflow-probability

### ISSUE THREAD

**Issue by SachinBM-CE** [tensorflow/tensorflow#62048]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tensorflow 2.15.0

### Custom code

Yes

### OS platform and distribution

Windows Subsystem for Linux

### Python version

3.9

### Bazel version

v1.18.0

### GCC/compiler version

11.3.0

### Current behavior?

I am trying to run a program which uses tensorflow agents & tensorflow probability at the back end. When I try to run the train.py using .yaml input file, I am getting the following error:

### Standalone code to reproduce the issue

```shell
lib/python3.10/site-packages/tensorflow_probability/python/internal/prefer_static.py", line 84, in _copy_docstring raise ValueError(

ValueError: Arg specs do not match: original=FullArgSpec(args=['input', 'dtype', 'name', 'layout'], varargs=None, varkw=None, defaults=(None, None, None), kwonlyargs=[], kwonlydefaults=None, annotations={}), new=FullArgSpec(args=['input', 'dtype', 'name'], varargs=None, varkw=None, defaults=(None, None), kwonlyargs=[], kwonlydefaults=None, annotations={}), fn=<function ones_like_v2 at 0x7f8287141480> Please help me understand the issue & any suggestions to resolve the error is greatly appreciated.
```

**Comment by tilakrayal** [comment]
@SachinBM-CE,
Could you please note that using `tfp-nightly` in the meantime should work for the above issue. Also stable (ie non-nightly) TFP releases are generally tied to a particular stable TF release and won't generally work with a subsequent TF release. TFP nightlies are tested against tf-nightly and more likely to work with a recent TF stable release.

And also, it looks more related to tensorflow-propability, where in that repo there is an issue that was raised and a conversation is happening. https://github.com/tensorflow/probability/issues/1752. I request that please feel free to close this issue and follow up on that issue for a quick resolution. Thank you!

**Comment by SachinBM-CE** [comment]
@tilakrayal 
Thank you very much for your suggestion & directing me to the right conversation.
