### ISSUE TITLE
Can TensorFlow be used on other microcontrollers other than listed by TensorFlow? 

### ISSUE THREAD

**Issue by JasmineKaur-eaton** [tensorflow/tensorflow#62045]
I have created a TensorFlow model that I wish to run on STM32F407VGT6. 
Is it possible to run TensorFlow model on microcontrollers other than listed ones. 
Also, is there any documentation to create and explore new models other than Hello World, Miro Speech and Person detection to understand TensorFlow Lite Micro more?
Is TensorFlow expandable to other models apart from listed above?

**Comment by pjpratik** [comment]
Hi @JasmineKaur-eaton 

The TensorFlow provides TensorFlow Lite for Microcontrollers which is designed to run machine learning models on microcontrollers and other devices with only a few kilobytes of memory. 

Please check the list of [supported platforms](https://www.tensorflow.org/lite/microcontrollers#supported_platforms) which includes [STM32F746 Discovery kit](https://www.st.com/en/evaluation-tools/32f746gdiscovery.html). 

The documentation provides a hello world template and other examples which can be used as templates to create own projects.

This [documentation](https://www.tensorflow.org/lite/microcontrollers/library) outlines the basic structure of the C++ library and provides information about creating your own project.

Thanks.

**Comment by JasmineKaur-eaton** [comment]
Hi, thank you for your response.
I have tried the Hello World Example with Arduino Nano BLE and the TensorFlow library gives no errors. When trying the same with Arduino Mega I am getting errors in the TensorFlow Lib.
Below is the error-
\Arduino\libraries\Arduino_TensorFlowLite\src/tensorflow/lite/core/api/error_reporter.h:18:10: fatal error: cstdarg: No such file or directory

#include <cstdarg>
          ^~~~~~~~~
compilation terminated.

Why am I getting error when I am trying to build using TF with some other board and example.

**Comment by pjpratik** [comment]
Hi @JasmineKaur-eaton 

As per the [documentation](https://www.tensorflow.org/lite/microcontrollers#supported_platforms), the [Arduino Nano 33 BLE Sense](https://store-usa.arduino.cc/products/arduino-nano-33-ble-sense-with-headers) is supported and Arduino Mega is not listed in the supported platforms. Hence the incompatiblity might be causing the issue.

Thanks.

**Comment by JasmineKaur-eaton** [comment]
Is there any other library similar to TensorFlow which supports microcontrollers/platforms other than listed as per documentation?

**Comment by pjpratik** [comment]
Hi @JasmineKaur-eaton ,

I am not sure about other libraries but as far as TFLite Micro is concerned please refer to the list of [supported platforms](https://www.tensorflow.org/lite/microcontrollers#supported_platforms) as mentioned above. Feel free to post in [TFLite Micro](https://github.com/tensorflow/tflite-micro/issues) repo for reporting the possible feature request.

Thanks.
