### ISSUE TITLE
Obtain tf-opt and flatbuffer_translate without compiling from source

### ISSUE THREAD

**Issue by Kuree** [tensorflow/tensorflow#62044]
### Issue type

Feature Request

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.14

### Custom code

No

### Current behavior?

`tf-opt` and `flatbuffer_translate` are not found in the standard pip package. Those need to be compiled from source.

### Standalone code to reproduce the issue

```shell
$ pip install -U tensorflow
$ which tf-opt
```

**Comment by tilakrayal** [comment]
@Kuree,
Could you please elaborate about your Feature. Also, please specify the Use Cases for this feature to understand in the effective way. Thank you!

**Comment by Kuree** [comment]
We have a custom compiler that takes tflite models and convert them into some custom MLIR dialect. To do so, we use `flatbuffer_translate` and `tf-opt` to obtain MLIR in standard dialects (TODA + Linalg). So the compilation flow looks something like this:
1. Call `flatbuffer_translate` to get MLIR in TFL dialect
2. Call `tf-opt` to lower the dialect to TOSA and Linalg
3. Call the custom compiler to continue the compilation

Our compiler users have to compile tensorflow from source to obtain those two binaries. It would be great if those two can be shipped with standard tensorflow distribution. It doesn't have to be in the main python wheel, but can be included as extra dependency, e.g. `pip install tensorflow[mlir]`.

Please let me know if you have additional questions.

**Comment by pkgoogle** [comment]
Hi @Kuree,

These are C++ binaries which generally I don't think we want to install with TF, though as a custom option this might make sense. @terryheo Can you please take a look? Thanks.

**Comment by chudur-budur** [comment]
> We have a custom compiler that takes tflite models and convert them into some custom MLIR dialect. To do so, we use `flatbuffer_translate` and `tf-opt` to obtain MLIR in standard dialects (TODA + Linalg). So the compilation flow looks something like this:
> 
> 1. Call `flatbuffer_translate` to get MLIR in TFL dialect
> 2. Call `tf-opt` to lower the dialect to TOSA and Linalg
> 3. Call the custom compiler to continue the compilation
> 
> Our compiler users have to compile tensorflow from source to obtain those two binaries. It would be great if those two can be shipped with standard tensorflow distribution. It doesn't have to be in the main python wheel, but can be included as extra dependency, e.g. `pip install tensorflow[mlir]`.
> 
> Please let me know if you have additional questions.

It would be really great if all the tools from `/tensorflow/compiler/mlir` are shipped with tensorflow.

**Comment by gaikwadrahul8** [comment]
Hi, @Kuree 

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/119

Let us know if you have any questions. Thanks.
