### ISSUE TITLE
Illegal memory access when running tf.sparse_to_dense

### ISSUE THREAD

**Issue by ndeepesh** [tensorflow/tensorflow#62043]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.11

### Custom code

No

### OS platform and distribution

Linux

### Python version

3.10

### Current behavior?

[This](https://github.com/tensorflow/tensorflow/issues/59126) issue seems to suggest that it was fixed in tf-nightly release. But I am somehow not able to find the commit where this was fixed. Can you please point me to the commit so that I can verify it has been fixed on my side

### Standalone code to reproduce the issue

```shell
-
```

**Comment by SuryanarayanaY** [comment]
Hi @ndeepesh ,

I am not sure of the patch that resolved this bug. Maybe it's possible that its internal fix also and hence difficult to find it out for me. You may try git diff command to know the differences in the file for master branch and v2.11.0.

AFAIK most of the vulnerability fixes happens at C++ backend. You may try the command below to check the changes in code.

`!git diff master v2.11.0 -- tensorflow/core/kernels/sparse_to_dense_op.cc`

I hope this may be of some help. Thank you!
