### ISSUE TITLE
Issue Installing TensorFlow on Windows 11 with Python 3.12.0

### ISSUE THREAD

**Issue by IgrisBellion** [tensorflow/tensorflow#62054]
Hello,

I am encountering an issue while trying to install TensorFlow on my Windows 11 machine with Python 3.12.0 and pip 23.2.1 (64-bit). Despite several attempts, I keep receiving the following error messages:

```
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
```

I have tried creating virtual environments using both Python 3.7.0 and Python 3.6.4
cleared the pip cache using the command `pip cache purge`
Install TensorFlow with various specific versions
`tensorflow==2.1.0`
`tensorflow==2.5.0`
`tensorflow==2.2.0rc4`

I hoping anyone know what the issue here

**Comment by thiagojramos** [comment]
`I hoping anyone know what the issue here`

I get it, the issue is with Python 3.12. Use a different version and you'll be good to go.

**Comment by IgrisBellion** [comment]
Thanks
I installed python 3.10 and now its working

**Comment by mihaimaruseac** [comment]
Canonical issue #62003
