### ISSUE TITLE
TFLite Python: interpreter._get_tensor_details(index) can't read tensor with sparsity (Segmentation Fault)

### ISSUE THREAD

**Issue by greenrazer** [tensorflow/tensorflow#62058]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

v2.14.0-rc1-21-g4dacf3f368e 2.14.0

### Custom code

No

### OS platform and distribution

Ubuntu 20 / Windows 11

### Python version

3.8, 3.10, 3.11

### Current behavior?

Seems to be the same problem as https://github.com/tensorflow/tensorflow/issues/55040. 

If I try to create an interpreter for the latest media pipe pose detector taken from the official mediapipe website it segfaults. 

1. download latest `pose_landmarker.task` (any lite/full/heavy) from [here](https://developers.google.com/mediapipe/solutions/vision/pose_landmarker#models)
2. rename `pose_landmarker.task` to `pose_landmarker.zip`
3. extract `pose_detector.tflite`
4. run the attached example

doing some basic investigation it segfaults on `self._interpreter.TensorSparsityParameters(tensor_index, subgraph_index)` [here](https://github.com/tensorflow/tensorflow/blob/63bc8d2fd33f24699cc957e7b4e16996568736a2/tensorflow/lite/python/interpreter.py#L621C48-L621C72) same as the linked issue.

I am using conda, for package management.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

interpreter = tf.lite.Interpreter("pose_detector.tflite")
details = interpreter._get_tensor_details(15, subgraph_index=0)
print(details)
```

### Relevant log output

```shell
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Segmentation Fault
```

**Comment by pjpratik** [comment]
I was able to reproduce the issue. Please find this [gist](https://colab.research.google.com/gist/pjpratik/456c0d5c4035cf68fbd88c380a9861e0/62058.ipynb).

@pkgoogle Could you please look into this issue. Thanks.

**Comment by pkgoogle** [comment]
I was able to replicate, [gist](https://colab.sandbox.google.com/gist/pkgoogle/15855d323971676c2e64ec00355e2e23/62058.ipynb), I added some comments for readability.

@alankelly, can you please take a look? Thanks.
