### ISSUE TITLE
Question about ptxas warning output of tensorflow-gpu 2.11

### ISSUE THREAD

**Issue by myalos** [tensorflow/tensorflow#62064]
### Issue type

Others

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.11

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Python version

3.10

### Current behavior?

The running environment is cuda 11.7 cuDNN 8.5.0 python 3.10 tensorflow-gpu 2.11
When I run the code, it show the warning message which seems weird. Since my cuda version is 11.7, not older than 11.1 and the log says Loaded cuDNN version 8904 while my cuDNN version is 8500. Althought the code can run successfully, i have doubts about this log, and I hope I can figure out why. Thanks in advance.

The warning log is as follows
 I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:428] Loaded cuDNN version 8904
2023-10-07 11:43:16.647615: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:115] *** WARNING *** You are using ptxas 10.1.243, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.
2023-10-07 11:43:16.651012: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:234] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.6
2023-10-07 11:43:16.651030: W tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:237] Used ptxas at ptxas
2023-10-07 11:43:16.651094: W tensorflow/compiler/xla/stream_executor/gpu/redzone_allocator.cc:318] UNIMPLEMENTED: ptxas ptxas too old. Falling back to the driver to compile.
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.

### Standalone code to reproduce the issue

```shell
any code that use tensorflow-gpu
concretely, the code i run is https://github.com/acctouhou/Prediction_of_battery/blob/main/1_Predicting/predict.py
```

**Comment by sushreebarsa** [comment]
@myalos Glad, you are able to run the code successfully. 
The warning might be occurring due to the versions you installed for TensorFlow and CUDA probably aren't compatible. Try using one of the versions tested here: [Tensorflow GPU Source Install](https://www.tensorflow.org/install/source#gpu).  
Please use the latest TF version with all compatible versions.
![BXNp6QCipe5sCVW](https://github.com/tensorflow/tensorflow/assets/84765720/23e2d365-5f08-44d8-a9a3-0fc1dd02fd5f)

Thank you!

**Comment by myalos** [comment]
Thanks for reply! I changed the version of tensorflow 2.11 to 2.12 and the original problem was solved, but unpleasant message showed up which is `[/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor`
And i searched the reason and solution for this problem, and found related issue on https://github.com/tensorflow/tensorflow/issues/59779. It seems that the problem about this unpleasant message is still unsolved.

**Comment by sushreebarsa** [comment]
@myalos Thank you for your response here!
Though there are some workarounds to avoid such warnings but the original issue is under tracking. Once that will be resolved such warnings will not occur. 
As you confirmed that the original issue has been resolved so could you please move this issue to closed status ?
Thank you!
