### ISSUE TITLE
Code to make TFQ Demos run in Colab

### ISSUE THREAD

**Issue by kevinkawchak** [tensorflow/tensorflow#62077]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tensorflow==2.7.0

### Custom code

No

### Python version

3.9, Also tried current version in Colab

### Current behavior?

Does not correctly install tensorflow or tensorflow_quantum with current version of Python in Colab or Python 3.9 for multiple demos. 

### Standalone code to reproduce the issue

```shell
ERROR: Could not find a version that satisfies the requirement tensorflow==2.7.0 (from versions: 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.11.1, 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0)
ERROR: No matching distribution found for tensorflow==2.7.0

ERROR: Could not find a version that satisfies the requirement tensorflow-quantum==0.7.2 (from versions: none)
ERROR: No matching distribution found for tensorflow-quantum==0.7.2

ModuleNotFoundError: No module named 'tensorflow_quantum'
```

**Comment by SuryanarayanaY** [comment]
Hi @kevinkawchak,

Could you please try with TF2.8 versions and higher.As TF2.7 version is quiet older and latest stable release is 2.14V and colab only fetching Tf 2.8 and higher versions only.
