### ISSUE TITLE
Bias size verification in `tfl.conv_3d_tranpose` op

### ISSUE THREAD

**Issue by rafaelubalmw** [tensorflow/tensorflow#62076]
https://github.com/tensorflow/tensorflow/blob/83078cb3cc4da3f2224e2e09825d1f164ccc2da5/tensorflow/compiler/mlir/lite/ir/tfl_ops.td#L5543

should be

`TFL_NumElementsEqualsDim<3, 1, 3>`

instead of

`TFL_NumElementsEqualsDim<3, 1, 4>`

since the number of output channels in the filter is given in dimension 3.

**Comment by sushreebarsa** [comment]
@rafaelubalmw We have raised a fix internally as per your suggestions. Thank you!

**Comment by sushreebarsa** [comment]
@rafaelubalmw Could you please have a look at this [comment](https://github.com/tensorflow/tensorflow/pull/62079) in the PR,  in `TFL_NumElementsEqualsDim<3, 1, 4>` 4  would be good for the bias size.
Thank you!
