### ISSUE TITLE
tf.math.is_non_decreasing outputs incorrect result when input is an uint tensor

### ISSUE THREAD

**Issue by drewshark** [tensorflow/tensorflow#62072]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.14.0

### Custom code

Yes

### Current behavior?

When giving tf.math.is_non_decreasing a decreasing tensor with dtype=uint32. This API incorrectly output True instead of False.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
x = tf.constant([10,9], dtype='uint32')
print(x)
out = tf.math.is_non_decreasing(x)
print(out)
```

**Comment by SuryanarayanaY** [comment]
Hi @drewshark ,

Thanks for reporting this. The issue persists with all unsigned dtypes i.e `'uint8','uint16','uint32','uint64'` which are causing overflow (i.e negative values being overflowed to positive end as unsigned integers can't hold -ve numbers) when the input (x) is of `non_decreasing` type.

The overflow is happening from this line of code.

https://github.com/tensorflow/tensorflow/blob/4dacf3f368eb7965e9b5c3bbdd5193986081c3b2/tensorflow/python/ops/check_ops.py#L1947

We will check and submit a fix for this. Thank you!
