### ISSUE TITLE
tf.truncatediv does not support float/complex tensor

### ISSUE THREAD

**Issue by drewshark** [tensorflow/tensorflow#62071]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.14.0

### Custom code

Yes

### Current behavior?

Not sure if it is an expected behavior but it conflicts the documentation (https://www.tensorflow.org/api_docs/python/tf/truncatediv). 
tf.truncatediv will directly crash when the input is float-related data type of complex-related datatype.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
import warnings
warnings.filterwarnings("ignore")
dtype_list = [
    'bfloat16', 'bool', 'complex128', 'complex64',
    'double', 'float16', 'float32',
    'float64', 'half', 'int16', 'int32', 'int64', 'int8',
    'uint16', 'uint32', 'uint64', 'uint8'
]
for dtype in dtype_list:
    x = tf.constant(np.random.rand(0), dtype=dtype)
    y = tf.constant(np.random.randint(0, 100, ()), dtype=dtype)
    try:
        out = tf.truncatediv(x,y)
        print(f"Success on dtype: {dtype}")
    except:
        print(f"Fail on dtype: {dtype}")
```

### Relevant log output

```shell
Fail on dtype: bfloat16
Fail on dtype: bool
Fail on dtype: complex128
Fail on dtype: complex64
Fail on dtype: double
Fail on dtype: float16
Fail on dtype: float32
Fail on dtype: float64
Fail on dtype: half
Success on dtype: int16
Success on dtype: int32
Success on dtype: int64
Success on dtype: int8
Success on dtype: uint16
Success on dtype: uint32
Success on dtype: uint64
Success on dtype: uint8
```

**Comment by sushreebarsa** [comment]
@drewshark I wasn't able to replicate this issue as reported. Please check this [gist](https://colab.research.google.com/gist/sushreebarsa/db4856d8ad0174b72d422f564a7d621b/62071.ipynb) on the latest TF v2.14.
The result is as follows;
```
Success on dtype: bfloat16
Fail on dtype: bool
Fail on dtype: complex128
Fail on dtype: complex64
Success on dtype: double
Success on dtype: float16
Success on dtype: float32
Success on dtype: float64
Success on dtype: half
Success on dtype: int16
Success on dtype: int32
Success on dtype: int64
Success on dtype: int8
Success on dtype: uint16
Success on dtype: uint32
Success on dtype: uint64
Success on dtype: uint8

```
Thank you!

**Comment by drewshark** [comment]
Hi @sushreebarsa ,
I apology for my mistake, my environment is tensorflow 2.10.0 instead of 2.14.0. I confirm your result on tensorflow 2.14.0. It looks like tf.truncatediv still does not support complex tensor.

**Comment by SuryanarayanaY** [comment]
Hi @drewshark ,

The complex dtype still not supporting for `truncatediv` Op in tf-nightly also. We will look into this and do needful changes and will update you.

Thanks!

**Comment by tilakrayal** [comment]
@drewshark,
Complex types are not supported. This breaks a bunch of stuff, and as you can see from the functor, is only supported by real values. Floor/truncation doesn't make much sense for complex inputs. Thank you!

**Comment by drewshark** [comment]
Hi @tilakrayal ,

If this is the case, do you mind update the documentation here https://www.tensorflow.org/api_docs/python/tf/truncatediv to avoid inconsistency?

**Comment by tilakrayal** [comment]
@drewshark,
Could you please feel free to contribute to the changes required in the documentation with the PR? Thank you!
