### ISSUE TITLE
Tensorflow build with sycl and ComputeCPP throwing error "missing value for mandatory attribute 'toolchain_config' in 'cc_toolchain' rule"

### ISSUE THREAD

**Issue by Varun-pro** [tensorflow/tensorflow#62085]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.3.0

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.8

### Bazel version

3.1.0

### GCC/compiler version

9

### CUDA/cuDNN version

11.8 / 8.6

### GPU model and memory

RTX 3090- 24 GB

### Current behavior?

I'm trying to build Tensorflow from source with sycl and ComputeCPP backend but when I'm trying to build Tensorflow, I'm getting following errors:
@local_config_sycl//crosstool:cc-compiler-local: missing value for mandatory attribute 'toolchain_config' in 'cc_toolchain' rule
Target '@local_config_sycl//crosstool:empty' contains an error and its package is in error and referenced by '@local_config_sycl//crosstool:cc-compiler-local'
Target '@local_config_sycl//crosstool:cc-compiler-local' contains an error and its package is in error and referenced by '@local_config_sycl//crosstool:toolchain'
/home/vpy2kor/tensorflow-2.3.0/tensorflow/python/BUILD:2998:1: every rule of type cc_binary implicitly depends upon the target '@local_config_sycl//crosstool:toolchain', but this target could not be found because of: Target '@local_config_sycl//crosstool:toolchain' contains an error and its package is in error

### Standalone code to reproduce the issue

```shell
Move to tensorflow folder 
Run ./configure and make the necessary checks for sycl and computecpp
Start building tensorflow : bazel build --verbose_failures --jobs=16 //tensorflow/tools/pip_package:build_pip_package
```

**Comment by sushreebarsa** [comment]
Hello, @Varun-pro! 
Thank you for raising the issue! We could see you are using TF v2.3, which is an older version and not actively supported. Could you please have a look at this [doc](https://www.tensorflow.org/install/source) and try to build TF using the latest TF version?
Thank you!

**Comment by Varun-pro** [comment]
Thanks for the fast reply
I want to build tensorflow from source with sycl support and when I'm running the configure file of new tensorflow versions , It's not showing sycl support option . That's why I have to revert to an old version. 
Do you have any idea whether newer versions doesn't support opencl/sycl backend or is there some issue with my hardware.

**Comment by sushreebarsa** [comment]
@Varun-pro There is no further information for supporting sycl as per the issue attached here. 
Please refer to this release [note](https://github.com/tensorflow/tensorflow/releases) for more updates. Please let us know if it helps? Thank you!
