### ISSUE TITLE
NVCC compilation failure with tf-nightly 2.15

### ISSUE THREAD

**Issue by youchangkim** [tensorflow/tensorflow#62081]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15.0.dev20231002

### Custom code

Yes

### Python version

3.10.10

### GCC/compiler version

c++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

### CUDA/cuDNN version

cuda-11.8, cudnn-8.6

### Current behavior?

nvcc fails to compile following code (test.cc).
```
#include "tensorflow/core/framework/tensor.h"

using namespace tensorflow;

int main() {
	Tensor x;
	return 0;
}
```

```
# nvcc -I/usr/local/cuda/include -expt-relaxed-constexpr $(python -c "import tensorflow as tf; print(' '.join(tf.sysconfig.get_compile_flags()))") -x cu -c test.cc -o test.o

/miniconda/envs/venv/lib/python3.10/site-packages/tensorflow/include/absl/strings/internal/str_format/bind.h: In constructor ‘absl::lts_20230125::str_format_internal::FormatSpecTemplate<Args>::FormatSpecTemplate(const absl::lts_20230125::str_format_internal::ExtendedParsedFormat<absl::lts_20230125::FormatConversionCharSet(C)...>&)’:
/miniconda/envs/venv/lib/python3.10/site-packages/tensorflow/include/absl/strings/internal/str_format/bind.h:171:1: error: parse error in template argument list
  171 |     CheckArity<sizeof...(C), sizeof...(Args)>();
      | ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~              
/miniconda/envs/venv/lib/python3.10/site-packages/tensorflow/include/absl/strings/internal/str_format/bind.h:171:63: error: expected ‘;’ before ‘)’ token
  171 |     CheckArity<sizeof...(C), sizeof...(Args)>();
      |                                                               ^
/miniconda/envs/venv/lib/python3.10/site-packages/tensorflow/include/absl/strings/internal/str_format/bind.h:172:147: error: template argument 1 is invalid
  172 |     CheckMatches<C...>(absl::make_index_sequence<sizeof...(C)>{});
      |                                                                                                                                                   ^
/miniconda/envs/venv/lib/python3.10/site-packages/tensorflow/include/absl/strings/internal/str_format/bind.h:172:151: error: expected primary-expression before ‘{’ token
  172 |     CheckMatches<C...>(absl::make_index_sequence<sizeof...(C)>{});
      |                                                                                                                                                       ^
/miniconda/envs/venv/lib/python3.10/site-packages/tensorflow/include/absl/strings/internal/str_format/bind.h:172:151: error: expected ‘;’ before ‘{’ token
/miniconda/envs/venv/lib/python3.10/site-packages/tensorflow/include/absl/strings/internal/str_format/bind.h:172:153: error: expected primary-expression before ‘)’ token
  172 |     CheckMatches<C...>(absl::make_index_sequence<sizeof...(C)>{});
      |                                                                                                                                                         ^
```

This is likely due to [`#include "absl/strings/str_format.h"`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/resource_base.h#L22) introduced from https://github.com/tensorflow/tensorflow/commit/fa87199c133ece4d7e3f5947cec2ec0a74d2cc50.

### Standalone code to reproduce the issue

```shell
See above.
```

### Relevant log output

This works fine with previous versions of TensorFlow (2.1~2.14).

**Comment by sushreebarsa** [comment]
@youchangkim Sometimes nightly will be failing as the build is not stable. So it is recommended to use the stable version. Once the final release is done, we would expect it to work as expected. Thank you!

**Comment by youchangkim** [comment]
This is still failing on latest build.

**Comment by sushreebarsa** [comment]
@youchangkim Could you please share the exact TF version you are using ?
Thank you!

**Comment by youchangkim** [comment]
@sushreebarsa 
I tried 2.15.0.dev20231011 and 2.16.0.dev20231023, and both are failing.

**Comment by youchangkim** [comment]
@sushreebarsa 
I can reproduce this with 2.15.0rc0 wheel, and also from tensorflow/tensorflow:2.15.0rc0-gpu docker image.

**Comment by youchangkim** [comment]
@sushreebarsa @sachinprasadhs Is there any plan to fix this before 2.15 release?

**Comment by sachinprasadhs** [comment]
Hi, 2.15 release is finalized and there won't be any additional code changes made, if the fix is made, it will be available in nightly version.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
