### ISSUE TITLE
Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter.

### ISSUE THREAD

**Issue by jiangshaonian** [tensorflow/tensorflow#62097]
ERROR: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select
ERROR: Node number 13 (FlexTensorArrayV3) failed to prepare.

Problems with calling tesonflowlite in C/C++。Has anyone encountered this problem？？

**Comment by pjpratik** [comment]
Hi @jiangshaonian 

Could you please fill the [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=comp%3Alite-in-play-services&projects=&template=tflite-in-play-services.md) ignoring play services?

For using flex ops for C/C++ we need to enable Flex delegate by linking a TensorFlow Lite Flex delegate shared library. You can build it with Bazel as the following command.

```
bazel build -c opt --config=monolithic tensorflow/lite/delegates/flex:tensorflowlite_flex

```

Thanks.
