### ISSUE TITLE
Is there a way to run predict() for the same batch of data on two different sets of weights (same model architecture)

### ISSUE THREAD

**Issue by ben-arnao** [tensorflow/tensorflow#62094]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

n/a

### Custom code

Yes

### Current behavior?

Hi all, sorry If not the write forum to ask such a question, but I am wondering about functionality of TensorFlow.

Basically I want to run the same batch of data, through X different models. These models will have a different set of weights, but are architecturally the same model.

From a technical perspective, I don't see why it is not possible to do in a single set of computations. In practice, it not different than two submodels that share inputs nodes, but the nodes after are just not connected at all, you would have two output nodes (one of each sub-model).

### Standalone code to reproduce the issue

```shell
n/a
```

**Comment by ManishSharma1609** [comment]
Yes, there's a way to do this, by creating multiple instances of a model's architecture and loading different weights for each instance. Then, you can use pridict() method for each of these different instances of the original model for the same batch of data.

**Comment by ben-arnao** [comment]
@ManishSharma1609 each predict would be a separate set of calculations that needs to be run sequentially no? My issue here is that I want the computations to be run in parallel.

It *should* be possible as what I am asking about is essentially just one network with the two (or more) networks for nodes being complete separate and only sharing input nodes (think how nodes within CNN are not all connected).

**Comment by ManishSharma1609** [comment]
@ben-arnao I understand, but i guess predict() method doesn't provide parallelism and to run the computations in parallel we have to use modules like multiprocessing or concurrent.futures or threading libraries.

**Comment by ben-arnao** [comment]
They are very short predictions, loading data into GPU then offloading takes away the benefit of multiprocessing from the tests I've ran, that's why I wanted a more native solution. Since the dimensions are the same and models like a CNN already skip connections it should be possible.

**Comment by ben-arnao** [comment]
> @ben-arnao Sorry for the late response! There are two ways to run predict() for the same batch of data on two different sets of weights (same model architecture):
> 
> Firstly, you could create multiple instances of the model's architecture and load different weights for each instance. Then, you can use the predict() method for each of these different instances of the original model for the same batch of data.
> 
> Secondly, you can use the set_weights() method to set the weights of the model to the desired set of weights. Then, you can use the predict() method as usual.
> 
> For any further queries on this please post this issue on TF [Forum](https://discuss.tensorflow.org/) where there is a larger community to get you the right help. Thank you!

I am more asking if there is a way to parallelize the evaluation of different sets of weights.
