### ISSUE TITLE
The configuration file of newer tensorflow versions doesn't provide building with sycl/opencl option. Does newer versions of Tensorflow doesn't provide sycl support?

### ISSUE THREAD

**Issue by Varun-pro** [tensorflow/tensorflow#62098]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.14

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Python version

3.8

### GCC/compiler version

9

### CUDA/cuDNN version

11.8/8.6

### GPU model and memory

NVIDIA RTX 3090 24 GB

### Current behavior?

I am trying to build Tensorflow version 2.14 from source with sycl/opencl support but when I am running the configuration file it isn't showing any sycl support option. So does the newer versions of tensorflow doesn't provide opencl/sycl support? 
If they do provide support, how to build newer versions of TF with sycl/opencl support?

### Standalone code to reproduce the issue

```shell
download and unzip the TF 2.14 
and run configure file
```

**Comment by sushreebarsa** [comment]
Hello, @Varun-pro!  Could you please refer to [this](https://github.com/tensorflow/tensorflow/issues/41809) issue where it states that after this [commit](https://github.com/tensorflow/tensorflow/commit/3cbb50768909c585d33e99ba10172d1c44c04d6f) the support for sycl has been removed. For opencl as well [this](https://github.com/tensorflow/tensorflow/issues/22) older issue states to refer to [this](https://blog.tensorflow.org/2020/08/faster-mobile-gpu-inference-with-opencl.html) blog. Please have a look. Thank you!

**Comment by Varun-pro** [comment]
Thanks for the reply
Also does TFLite supports PowerVR and if so then through delegates?

**Comment by sushreebarsa** [comment]
@Varun-pro There is no specific support for PowerVR in tflite, please have a look at the official doc [here](https://www.tensorflow.org/lite/performance/gpu) for GPU delegates. Thank you!
