### ISSUE TITLE
[Q] ConvertPrimitiveTypeToMLIRType and mlir::IntegerType::Signless

### ISSUE THREAD

**Issue by apivovarov** [tensorflow/tensorflow#62108]
I have a question about the code block below https://github.com/tensorflow/tensorflow/blob/master/third_party/xla/xla/translate/hlo_to_mhlo/hlo_utils.cc#L286-L288
hlo_utils.cc - ConvertPrimitiveTypeToMLIRType
```
    default:
      if (primitive_util::IsIntegralType(element_type)) {
        return mlir::IntegerType::get(
            builder.getContext(),
            /*width=*/primitive_util::BitWidth(element_type),
            /*signed=*/
            primitive_util::IsUnsignedIntegralType(element_type)
                ? mlir::IntegerType::Unsigned
                : mlir::IntegerType::Signless);
      }
```
Should we return `mlir::IntegerType::Signed` instead of `mlir::IntegerType::Signless` ?

**Comment by apivovarov** [comment]
Got the following replies
https://github.com/openxla/xla/commit/3dab17571e28a5acac08e4905f115fc6da9365b4#r129933757

https://groups.google.com/a/openxla.org/g/openxla-discuss/c/ILBDvAIp0Ps

**Comment by sushreebarsa** [comment]
Hi, @apivovarov ! Thank you for asking this question. 
Your above comment is helpful.
There is an open ticket, once that will close then this issue would be resolved, it seems. Thank you!
