### ISSUE TITLE
[Installing TensorFlow offline] $ ./configure fails because no Internet connection is available for my server.

### ISSUE THREAD

**Issue by mrtonnet** [tensorflow/tensorflow#6210]
**My environment without Internet**
My server can't access the Internet because my company's firewall blocks any external network or the Internet. To install Tensorflow on this server, I have to install TensorFlow offline. In other words, I have to correct tens of errors by myself. Upon this error, I had to submit an issue. 

I moved the template below because it's way too long. (I filled in some information.) I'd appreciate your feedback.
 
**Questions**
My question nails down to two core questions.
Q1. How can I manually fetch all the packages for tensorflow without using bazel command?
      I took a closer look at the "configure" file and the following line causes the problem.
       $bazel fetch //tensorflow/...

      This bazel command fetches all the packages in target "tensorflow". 
       No Internet connection in my server, so this command fails!. 
       I'll have to download all these packages in ANOTHER computer with Internet connection and   
       move them to my server.
 
       In another computer with Internet connection, how can I download them without bazel command? Alternative commands can be wget, git, apt-get, pip and so on.

Q2. Where should I place the downloaded packages?
    Say all the packages for target "tensorflow" are downloaded.
    Where should I place them to run the next command successfully?
 
     $ bazel build -c opt -config=cuda //tensorflow/cc:tutorials_example_trainer
 
    I'll have to move all the package to my server from another computer.
   So I need some information about the directory that the above command refers to.

(This is all because of the security measure in my company. As a matter of fact, this process is more complex than using another computer, but this gives you an idea about my installation environment without the Internet)
-----------------------------------------------------------------------------------
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.
 
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.
 
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.
 
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
"How to make the ./configure find package in local place #5428"
GaofengCheng opened this issue on 6 Nov and there're 13 comments, but no solution is presented.
 
### Environment info
1. Operating System: Ubuntu Linux 14.04
2. NO INTERNET CONNECTION.
    My company's firewall blocks my server from the Internet connection.  So no Internet connection is available. A comment in Issue #5029 says "Long story short, [...] a network access is required.", but a network access on this server is not an option. I'll have to download necessary packages from another computer with Internet connection and upload them to my server via sftp.
 
3. CUDA & cuDNN are installed in ~/local/ because of the system admin asked me to do so.
   When I run " $ ./configure", CUDA & cuDNN installation was done manually.  
 
Installed version of CUDA and cuDNN:
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
~/local/cuda-8.0/lib64$ ls -l libcud*
-rw-r--r-- 1 root root   558720 Dec  9 01:00 libcudadevrt.a
lrwxrwxrwx 1 root root       16 Dec  9 01:00 libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Dec  9 01:00 libcudart.so.8.0 -> libcudart.so.8.0.44
-rwxr-xr-x 1 root root   415432 Dec  9 01:00 libcudart.so.8.0.44
-rw-r--r-- 1 root root   775162 Dec  9 01:00 libcudart_static.a
lrwxrwxrwx 1 root root       13 Dec  9 01:05 libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root       17 Dec  9 01:05 libcudnn.so.5 -> libcudnn.so.5.1.5
-rwxr-xr-x 1 root root 79337624 Dec  9 01:05 libcudnn.so.5.1.5
-rw-r--r-- 1 root root 69756172 Dec  9 01:05 libcudnn_static.a
 
If installed from source, provide
1. The commit hash (`git rev-parse HEAD`)
$ git rev-parse HEAD
fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
 
2. The output of `bazel version`
$ bazel version
Build label: 0.4.0
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 2 17:54:14 2016 (1478109254)
Build timestamp: 1478109254
Build timestamp as int: 1478109254
 
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
$ ./configure
[...]
ERROR: package contains errors: tensorflow/examples/android.
ERROR: error loading package 'tensorflow/examples/android': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Error downloading from http://github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz to /home/the.kim/.cache/bazel/_bazel_the.kim/e904ac0e4fbd2c03039cdbaeea674781/external/protobuf: Error downloading http://github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz to /home/the.kim/.cache/bazel/_bazel_the.kim/e904ac0e4fbd2c03039cdbaeea674781/external/protobuf/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: Timed out connecting to http://github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz : connect timed out.
(tensorflow) $
 
(The following line within configure causes my problem.
My server has no Internet connection, so download fails.)
$ bazel fetch //tensorflow/...
INFO: Downloading from http://github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e85\
5cb16db.tar.gz: 0B
 
### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
 
the.kim@clover3:~/tensorflow/downloads/tensorflow$ source ~/tensorflow/bin/activate
(tensorflow) the.kim@clover3:~/tensorflow/downloads/tensorflow$ ls
008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz  eigen.BUILD        LICENSE          tensorflow
ACKNOWLEDGMENTS                                  farmhash.BUILD     linenoise.BUILD  third_party
ADOPTERS.md                                      gif.BUILD          models.BUILD     tools
AUTHORS                                          gmock.BUILD        nanopb.BUILD     util
bower.BUILD                                      grpc.BUILD         png.BUILD        WORKSPACE
BUILD                                            ISSUE_TEMPLATE.md  README.md        zlib.BUILD
configure                                        jpeg.BUILD         RELEASE.md
CONTRIBUTING.md                                  jsoncpp.BUILD      six.BUILD
(tensorflow) the.kim@clover3:~/tensorflow/downloads/tensorflow$ ./configure
~/tensorflow/downloads/tensorflow ~/tensorflow/downloads/tensorflow
Please specify the location of python. [Default is /home/the.kim/tensorflow/bin/python]: /home/the.kim/tensorflow/bin/python3
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] n
No Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /home/the.kim/tensorflow/lib/python3.4/site-packages
Please input the desired Python library path to use.  Default is [/home/the.kim/tensorflow/lib/python3.4/site-packages]
 
Using python library path: /home/the.kim/tensorflow/lib/python3.4/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] y
OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]:
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /home/the.kim/local/cuda-8.0
Please specify the Cudnn version you want to use. [Leave empty to use system default]:
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /home/the.kim/local/cuda-8.0]:
libcudnn.so resolves to libcudnn.5
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 3.7
Please specify which C++ compiler should be used as the host C++ compiler. [Default is /usr/bin/g++]:
Please specify which C compiler should be used as the host C compiler. [Default is /usr/bin/gcc]:
Please specify the location where ComputeCpp 1.2 is installed. Refer to README.md for more details. [Default is /usr/local/computecpp]: /home/the.kim/local/ComputeCpp-CE-0.1.1-Linux
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
........
ERROR: package contains errors: tensorflow/examples/android.
ERROR: error loading package 'tensorflow/examples/android': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Error downloading from http://github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz to /home/the.kim/.cache/bazel/_bazel_the.kim/e904ac0e4fbd2c03039cdbaeea674781/external/protobuf: Error downloading http://github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz to /home/the.kim/.cache/bazel/_bazel_the.kim/e904ac0e4fbd2c03039cdbaeea674781/external/protobuf/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz: Timed out connecting to http://github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz : connect timed out.
(tensorflow) the.kim@clover3:~/tensorflow/downloads/tensorflow$
 
(Before the error, $ ./configure attempts this.)
INFO: Downloading from http://github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e85\
5cb16db.tar.gz: 0B

**Comment by michaelisard** [comment]
@martinwicke can you see an easy way to automate the download of necessary packages before build?

**Comment by martinwicke** [comment]
I would use bazel fetch on another computer and copy the result. 

The full paths of all of the packages are in the workspace.bzl file, so if you really want you can use wget and get them all. You can then change all the rules in the workspace file to be "local_repository" instead, and that will use the previously downloaded files from the paths you provide.

**Comment by mrtonnet** [comment]
Dear @martinwicke,
Thanks for your feedback. 

> I would use bazel fetch on another computer and copy the result.
Yes, this is what I've been doing. The command "$bazel fetch //tensorflow/..." fetches the repository and the only way I can install the repo to my server (without Internet) is to copy the result. Anyways it's good to confirm to use another computer.

> You can then change all the rules in the workspace file to be "local_repository" instead, and that > will use the previously downloaded files from the paths you provide.
Well, yes. That's exactly what I'm trying to do. The question is where is the "local_repository" located. If the local_repository can be any directory, how can I specify the directory when I build with bazel command?

I wasn't able to find about local_repository on [Command-Line Reference](https://www.bazel.io/versions/master/docs/command-line-reference.html#build).

@martinwicke, I'd appreciate if you can tell me a bit more in detail with concrete command. Thanks in advance!

**Comment by martinwicke** [comment]
It's not a command line option, you'll have to edit the workspace.bzl file to replace how bazel finds its dependencies from their current sources (often, http_archive) to [local_repository](https://www.bazel.io/versions/master/docs/be/workspace.html#local_repository).

**Comment by steeeeevo1** [comment]
@mrtonnet Did you solve your problem?  I'm having the same issue and was wondering if you could share your results.

**Comment by truatpasteurdotfr** [comment]
```
bazel --output_user_root=/tmp/bazel fetch  //tensorflow/tools/pip_package:build_pip_package 
```
downloads the packages required for the "bazel build ... //tensorflow/tools/pip_package:build_pip_package" stage and put the downloaded files in
```
 /tmp/bazel/<md5sum hash>/external/
``` 
Correct? 

Now how I am supposed to convert the URL such as "http://bazel-mirror.storage.googleapis.com/ftp.exim.org/pub/pcre/pcre-8.39.tar.gz" from ./tensorflow/workspace.bzl into "file:///tmp/bazel/da36536f347c0e23d2402d33213b5c40/external/pcre/pcre-8.39.tar.gz" ?
or from the WORKSPACE file : "https://github.com/polymerelements/paper-slider/archive/v1.0.10.tar.gz" -> "/tmp/bazel/da36536f347c0e23d2402d33213b5c40/external/paper_slider/v1.0.10.tar.gz"

**Comment by kaituoxu** [comment]
@mrtonnet @truatpasteurdotfr  Did you solve your problem? I'm having the same issue and was wondering if you could share your results.

**Comment by truatpasteurdotfr** [comment]
not solved for me :( I ended up building a docker image and build inside.

**Comment by amutu** [comment]
see this：
https://github.com/amutu/tensorflow_offline

**Comment by yuhow** [comment]
Hi @amutu 
I have followed your amazing introduction of how to install offline tensorflow. 
But now I have one more question...
When I try to view the data flow graph through tensorboard
It seems the browser(firefox) keeps trying to download something from website (google?)
And after waiting for a long time (~5mins), it still can't show anything from my browser.
I was wondering if there is anyway to run tensorboard with internet connection..
Thanks for your help in advance!

**Comment by amutu** [comment]
I think it needs some javascript libs to show the graph, these libs are only available on the public network and not included in the tensorflow pkg. I am sorry I can not help you because I am not a front end guy. You can open an issue to the tensorflow project to ask help.

**Comment by martinwicke** [comment]
Better yet, open an issue against tensorflow/tensorboard. You should be able to run this just fine without an internet connection.

**Comment by guytenn** [comment]
@amutu Thank you for your contribution of tensorflow-offline. Everything seems to work for me when not using cuda, but when trying to follow your instructions with cuda I get the following error:
ERROR: error loading package 'tensorflow/tools/pip_package': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
	File "/home/ec2-user/tensorflow-1.2.1/third_party/gpus/cuda_configure.bzl", line 958
		_create_cuda_repository(repository_ctx)
	File "/home/ec2-user/tensorflow-1.2.1/third_party/gpus/cuda_configure.bzl", line 915, in _create_cuda_repository
		_host_compiler_includes(repository_ctx, cc)
	File "/home/ec2-user/tensorflow-1.2.1/third_party/gpus/cuda_configure.bzl", line 144, in _host_compiler_includes
		get_cxx_inc_directories(repository_ctx, cc)
	File "/home/ec2-user/tensorflow-1.2.1/third_party/gpus/cuda_configure.bzl", line 119, in get_cxx_inc_directories
		set(includes_cpp)
depsets cannot contain mutable items.



Any idea what I can do?

**Comment by amutu** [comment]
CUDA is not supported for the offline build now.

**Comment by turowicz** [comment]
Ended up creating a twin VM, build there then deploy the libs to the target server.
