### ISSUE TITLE
Utilize Hexagon DSP using Python on ARM Devkit

### ISSUE THREAD

**Issue by Abhinav0002** [tensorflow/tensorflow#62113]
I am trying to run Tensorflow utilizing the Hexagon DSP on an ARM Devkit running ARM Linux 

I am able to build Tensorflow for DSP. Also the necessary DSP files are available (.so files) , but I am not able to find resources for any code in Python that would be able to run on DSP

**Comment by sushreebarsa** [comment]
@Abhinav0002 Here is a new [TensorFlow Lite delegate](https://www.tensorflow.org/lite/performance/delegates) that utilizes Hexagon NN Direct to run quantized models faster on the millions of mobile devices with Hexagon DSPs. Could you please have a look at this for reference? 
For any further queries can you please post the issue on TF [forum](https://discuss.tensorflow.org/) where there is a  larger community that would help you. Thank you!

**Comment by Abhinav0002** [comment]
I want to run for ARM Linux, is there any documentation for cross-compilation for ARM ?

**Comment by sushreebarsa** [comment]
@Abhinav0002 For more detailed instructions, please refer to the TensorFlow documentation:

Cross-compiling TensorFlow Lite with Bazel: https://www.tensorflow.org/lite/guide/build_arm
Cross-compiling TensorFlow Lite with CMake: https://www.tensorflow.org/lite/guide/build_cmake_arm\

Thank you!
