### ISSUE TITLE
Questions about the interpreter’s operational flow for quantized neural networks

### ISSUE THREAD

**Issue by Bajirak** [tensorflow/tensorflow#62116]
### Issue type

Others

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.13.0

### Custom code

No

### OS platform and distribution

Linux Ubuntu 18.04

### Python version

3.8

### Current behavior?

Hi. TensorFlow
This is not a post related to issues or bugs, but a post related to questions.

I am curious about how the interpreter operates when a quantized neural network is given to it.
I looked for documentation related to this, but couldn't find it.

Let me give you an example of what I am looking for in a document.
Let's say that the data type of the convolution's input activation is float32, and the data type of the weight is int8.

At this time, the interpreter
operates after dequantizing the weight of the convolution. 
OR,
operates after converting the activation of Convolution to int8.

I'm looking for an explanation like this.

Is there a link with an explanation like this?

### Standalone code to reproduce the issue

```shell
Not required.
```

### Relevant log output

```shell
Not required.
```

**Comment by pjpratik** [comment]
Hi @Bajirak 

By default, the model will run by dequantizing the 8-bit parameters to 32-bits, and then performing operations in standard 32-bit floating point arithmetic depending on the hardware support(assuming hardware supports floating point arithmetic). 

For example if there is a hardware support for accelerated fp16 calculations, it allowing us to drop the upsample to float32 and compute directly in these half precision values.

The information can be obtained from source code or the official Tensorflow Lite blogs and videos .

For example check enabling post-training float16 quantization blog
https://blog.tensorflow.org/2019/08/tensorflow-model-optimization-toolkit_5.html

Thanks.

**Comment by Bajirak** [comment]
@pjpratik 

Thank you. I really appreciate it!

**Comment by Bajirak** [comment]
No contents.
