### ISSUE TITLE
Command `pip install tensorflow[and-cuda]` need quotation mark

### ISSUE THREAD

**Issue by cheesy-burger** [tensorflow/tensorflow#62117]
Running this `pip install tensorflow[and-cuda]` command would be wrong as failed to install, but running `pip install "tensorflow[and-cuda]"` is okay. It just required the quotation mark. Please fix the documentation.

**Comment by tilakrayal** [comment]
@cheesy-burger,
Could you please provide more information for the requested change. Whenever I tried to install the tensorflow with the provided statement, it worked without any issues. **pip install tensorflow[and-cuda]**

![Screenshot 2023-10-16 9 15 18 PM](https://github.com/tensorflow/tensorflow/assets/81610181/2e3c75f9-70c0-41f7-9fa1-777e36162501)
 

And also [Gist](https://colab.research.google.com/gist/tilakrayal/9b1293ec79de11e65bfc4894835d8367/untitled1394.ipynb) for the reference. 
https://www.tensorflow.org/install/pip
Thank you!
