### ISSUE TITLE
Embedding Projector hangs when data with string-based features are added

### ISSUE THREAD

**Issue by bradknox** [tensorflow/tensorflow#6215]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
None

### Environment info
Operating System: OS X 10.11.6

Answer to other prompts: N/A

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
My issue is on the online tool Embedding Projector (http://projector.tensorflow.org). On both Safari and Chrome, if I upload data via the "Load Data" button, I see a window "Computing PCA..." that _never goes away_. 

A 10-sample version of my data can be found at [10samples.txt](https://github.com/tensorflow/tensorflow/files/642762/10samples.txt).

If I remove the string-based feature at the end—which happens to be the output/label for these samples—the problem goes away.

This case should be caught and an informative error message should be returned. 

(Relatedly, I can't understand from the current interface how to add string-based labels for the data. The implication is that these labels are "metadata", but that's not clear.)

**Comment by mrmattwright** [comment]
Keep your first file without the string based feature at the end. 
Create a second file called labels.txt with the following contents

```
none
back
fwd
none
left
fwd
right
none
left
none
```

use that as the metadata file. 

Note that if you make the metadata file have more than 1 variable you have to supply a header column. for example

```
Label	count 
none	2	
back	4	
fwd	4
none	34
left	3
fwd	5
right	34
none	23
left	2
none	4
```

**Comment by mrmattwright** [comment]
Ah...good point @bradknox. It is indeed super confusing....the error messages are not good, I actually only found this thread because I was trying to upload a tsv file and I kept getting another error 

![screenshot 2016-12-14 13 11 00](https://cloud.githubusercontent.com/assets/1277725/21183218/d77ef7e0-c1fe-11e6-9fbf-e4e375530cbf.png)

which I think happens when the files are not tabbed correctly, but it's hard to tell. 

Agree on the n+1 error too, that will trap a lot of people unless there is a message saying something like "The number of vectors(500) does not match the number of items of metadata (501). Please not that single column metadata does not need a header" or something like that.

**Comment by nsthorat** [comment]
This should be fixed now, I pushed a new version with some better error messages. Please re-open if you still find any of these messages opaque.

**Comment by SofiaSugar** [comment]
@mrmattwright how did you fix the problem of the Parsing failed?
I am trying to load a dataset from my computer but it says that it found a vector with only one dimension. 
Can you please share some data with a correct format, I am a bit lost here.
Thank you in advance.

**Comment by Naviden** [comment]
Hi. I'm getting the same error trying to load a 11553 x 100 tsv file. (No header, No text, just tab separated floats)

**Comment by soulbliss** [comment]
> @mrmattwright how did you fix the problem of the Parsing failed?
> I am trying to load a dataset from my computer but it says that it found a vector with only one dimension.
> Can you please share some data with a correct format, I am a bit lost here.
> Thank you in advance.

Inculded a short snippet to generate TSV files.

```
import csv

vectors = [[0,0,1], [0,1,0], [1,0,0], [1,1,1]]       # load your embeddings
metadata = ['point1', 'point2', 'point3', 'point4']  # load your metadata

with open('output.tsv', 'wt') as out_file:
    tsv_writer = csv.writer(out_file, delimiter='\t')
    for vector in vectors:
      tsv_writer.writerow(vector)

with open('metadata.tsv', 'wt') as out_file:
    tsv_writer = csv.writer(out_file, delimiter='\t')
    for meta in metadata:
      tsv_writer.writerow([meta])

```
For TSV file of vectors upload output.tsv and 
For TSV file of metadata upload metadata.csv
