### ISSUE TITLE
process_bounding_boxes.py does not ouput .csv file

### ISSUE THREAD

**Issue by civilman628** [tensorflow/tensorflow#6217]
https://github.com/tensorflow/models/blob/master/inception/inception/data/process_bounding_boxes.py

**process_bounding_boxes.py** does not output any files after processing .xml files.

it says: The script dumps out a CSV text file in which each line contains an entry. but if go through the python code, there is no write() function is called.

i can only see:

**Finished processing 544546 XML files.
Skipped 0 XML files not in ImageNet Challenge.
Skipped 0 bounding boxes not in ImageNet Challenge.
Wrote 615299 bounding boxes from 544546 annotated images.
Finished.**

**Comment by shlens** [comment]
The `process_bounding_boxes.py` script does *not* dump out a CSV file. Instead the script the bounding box annotations to STDOUT here:

https://github.com/tensorflow/models/blob/master/inception/inception/data/process_bounding_boxes.py#L225

You can redirect the bounding box annotations to a file using standard shell script redirection as was done in this wrapping script:

https://github.com/tensorflow/models/blob/master/inception/inception/data/download_and_preprocess_imagenet.sh#L86

A [README.md](https://github.com/tensorflow/models/blob/master/inception/README.md) contains instructions for running these scripts.

**Comment by shlens** [comment]
Please feel free to reopen if this does not answer your questions.
