### ISSUE TITLE
import keras_cv results in import error for keras_utils

### ISSUE THREAD

**Issue by ajayaraman** [tensorflow/tensorflow#62182]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.14

### Custom code

No

### OS platform and distribution

Linux

### Current behavior?

Running StableDiffusion Finetuning colab example throws the error 

https://colab.research.google.com/github/keras-team/keras-io/blob/master/examples/generative/ipynb/finetune_stable_diffusion.ipynb

### Standalone code to reproduce the issue

```shell
import keras_cv
from keras_cv.models.stable_diffusion.clip_tokenizer import SimpleTokenizer
```

### Relevant log output

```shell
ImportError                               Traceback (most recent call last)
[<ipython-input-2-1a02c2e511a0>](https://localhost:8080/#) in <cell line: 4>()
      2 import os
      3 
----> 4 import keras_cv
      5 import matplotlib.pyplot as plt
      6 import numpy as np

3 frames
[/usr/local/lib/python3.10/dist-packages/keras_cv/models/weights.py](https://localhost:8080/#) in <module>
     12 # See the License for the specific language governing permissions and
     13 import tensorflow as tf
---> 14 from keras.utils import data_utils
     15 
     16 

ImportError: cannot import name 'data_utils' from 'keras.utils' (/usr/local/lib/python3.10/dist-packages/keras/utils/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
```

**Comment by sushreebarsa** [comment]
Hello, @ajayaraman! Please ensure that the version of 'keras_cv' you're using is compatible with your Keras version. If you're using an older version of 'keras_cv', consider upgrading to a newer version. Also please check the Python you're using as it requires Python version 3.6 or higher. 'keras_cv' is not compatible with Python 2.7. Thank you!
