### ISSUE TITLE
How to use tf.repeat and another buil-in highlevel funcs on Dataset?

### ISSUE THREAD

**Issue by mihalt** [tensorflow/tensorflow#62197]
Can you help me in [stackoverflow](https://stackoverflow.com/questions/77332989/how-to-use-tf-repeat-and-another-buil-in-highlevel-funcs-on-dataset)?

**Comment by sushreebarsa** [comment]
@mihalt Thank you for raising this issue.
Could you please have a look at the [official](https://www.tensorflow.org/api_docs/python/tf/repeat#used-in-the-notebooks) example notebooks on tf.repeat for your reference. As the issue does not seem to be a bug or feature we will proceed with the SO thread going further. 
Thank you!
