### ISSUE TITLE
Cannot remove entries from nonexistent 

### ISSUE THREAD

**Issue by vinhqdang** [tensorflow/tensorflow#622]
Hello everyone

I am using Anaconda on Mac OS 10.11

I created a new environment with anaconda

```bash
conda create -n tensorflow python
```

Then tried to install tensorflow

```bash
pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.6.0-py2-none-any.whl
```

but I faced an error

```bash
Installing collected packages: six, setuptools, protobuf, numpy, tensorflow
  Found existing installation: setuptools 19.1.1
**Cannot remove entries from nonexistent file /Users/qdang/anaconda/envs/tensorflow/lib/python2.7/site-packages/easy-install.pth**
```

How could I install tensorflow with anaconda python 2.7?

Btw, I have CUDA 3.0 (Nvidia 750M) with my Macbook? How could I utilize its power other than running only on CPU mode?

Thanks,

**Comment by vinhqdang** [comment]
The solution is posted here

https://github.com/tensorflow/tensorflow/issues/135

It is for tensorflow 0.5.0 but still works with version 0.6.0

**Comment by sunformoon** [comment]
Hi, I followed the solution in the provided linking by downloading .whl file manually ( https://storage.googleapis.com/tensorflow/mac/tensorflow-0.6.0-py2-none-any.whl ) and run $pip install tensorflow-0.6.0-py2-none-any.whl.

And install the latest tensorflow by $  pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl

However, the issue still comes out:
Found existing installation: setuptools 19.1.1
Cannot remove entries from nonexistent file...

Could you please give more detailed solution when you solved the 'nonexistent' issue? Thanks a lot!

**Comment by vinhqdang** [comment]
Hi

It works for me (in Mac OS 10.11). Hope it helps

http://vinhdq.blogspot.com/2015/12/installing-tensorflow-on-mac-os-1011.html <http://vinhdq.blogspot.com/2015/12/installing-tensorflow-on-mac-os-1011.html>
—
Best Regards

Vinh DANG

**Comment by sunformoon** [comment]
I actually have installed Tensorflow 0.6.0 successfully on Ubuntu 14.04.
I am wondering how to solve the  "Found existing installation: setuptools 19.1.1 Cannot remove entries from nonexistent file" issue. Maybe it worked for you but not me due to the different OS?

**Comment by vinhqdang** [comment]
Hi

How did you install tensor flow?

I faced a same problem when I installed with pip, but after I created a totally new environment there is no issue.
—
Best Regards

Vinh DANG

**Comment by sunformoon** [comment]
Hi, I installed the tensorflow on Ubuntu 14.04 as following:

$ conda install virtualenv
$ conda create --name=tensorflow_env python=2.7
$ source activate tensorflow_env
$ pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl

Then I updated to the 0.6.0 version. Although there is still the nonexistent issue, I tested the tensorflow successfully on MNIST demo. I think the issue is just somehow a warning that may not affect the use of tensorflow at present. However, it's better to solve it.

**Comment by vinhqdang** [comment]
Why do you need to install version 0.5.0 then upgrade. Maybe it’s better to install 0.6.0 directly?


—
Best Regards

Vinh DANG

**Comment by sunformoon** [comment]
Hi,
Cause the instruction on homepage of Virtualenv installation is the 0.5.0 version. I didn't notice the latest 0.6.0 version. After I installed, I was informed from other source that maybe I could update to the 0.6.0 version. However, the nonexistent issue comes out both on my installation of 0.5.0 and 0.6.0.

**Comment by vinhqdang** [comment]
Well

I have no idea about Ubuntu environment.

However, I could suggest you try (nothing to lose LOL):

- create a new environment with conda (using sklearn environment instead of pure python)
- install tensor flow 0.6.0 offline.
—
Best Regards

Vinh DANG

**Comment by osdf** [comment]
See here: https://github.com/pypa/pip/issues/2751.
Possible work-around: ```pip install --upgrade --I setuptools```

**Comment by frankcarey** [comment]
@osdf - yeah I hit this too. Used the following to solve it when using conda (after I already successfully installed using the ubuntu pip directly) so that I had iPython notebook (Jupyter) installed.

List conda environments
`$ conda env list`

Enable a conda environment..
`$ source activate [your env or root]`

check python..
`$ which python`
.. this should be something like ~/anaconda2/bin/python

`$ pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl`

.. got the error above, so added the  --ignore-installed flag per https://github.com/pypa/pip/issues/2751

`$  pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl --ignore-installed`

.. everything was successful..

`$ python`
`>>> import tensorflow`

.. success and back in business!

**Comment by naim** [comment]
Thanks @frankcarey for posting your workaround.

**Comment by Inoryy** [comment]
Had same error with Python 3.4 version, solution by @frankcarey worked, thanks!

**Comment by kli-nlpr** [comment]
@frankcarey 
I use your workaround and successfully installed tensorflow
But when I import it, there is something wrong.
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-a649b509054f> in <module>()
----> 1 import tensorflow

/public/home/kli/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py in <module>()
     21 from __future__ import print_function
     22
---> 23 from tensorflow.python import *

/public/home/kli/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py in <module>()
     39 please exit the tensorflow source tree, and relaunch your python interpreter
     40 from there.""" % traceback.format_exc()
---> 41   raise ImportError(msg)
     42
     43 from tensorflow.core.framework.summary_pb2 import *

ImportError: Traceback (most recent call last):
  File "/public/home/kli/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 35, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/public/home/kli/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/public/home/kli/anaconda/envs/tensorflow/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /public/home/kli/anaconda/envs/tensorflow/lib/python2.7/site-packages/google/protobuf/pyext/_message.so)


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

```

**Comment by StevenHuang4321** [comment]
@kli-nlpr Did you figure out the GLIBC_2.14 problem?

**Comment by kli-nlpr** [comment]
@StevenHuang4321  
I use centos6 when encounter this problem.
When I use Ubuntu14.04, the problem goes away.

**Comment by StevenHuang4321** [comment]
Since our server use Centos 6, it is not possible for me to change to
ubuntu. Thanks.

**Comment by kli-nlpr** [comment]
@StevenHuang4321 
The possible solution is to update your glibc version.
But I think this is a complicated task and dangerous...


In fact I encounter a lot of problem when I use centos6 while doing deep learning research.

**Comment by StevenHuang4321** [comment]
Our system is CentOS 6.7, but it seems that only CentOS 7 supprot glib_2.14
or higher version.

Apparently, CentOS is not a good linux distribution to do develop and
research.

I already suggest my advisor to migrate our server from CentOS6.7 to Ubuntu
server.

**Comment by fengmei** [comment]
solution works, thanks!

**Comment by ppuliu** [comment]
Another solution 

    pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl

**Comment by bzamecnik** [comment]
Observed on Ubuntu 15.10 Server in Anaconda 4.0.0 with python 3.4, tensorflow-0.7.1-cp34-none-linux_x86_64.whl GPU. Downloading and installing from local file works!

**Comment by wuyang1992** [comment]
@osdf 
thanks for your solution!
it works
pip install --upgrade -I setuptools

**Comment by episodeyang** [comment]
Both solutions worked for me:

1. 
```shell
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
```

2.
```shell
pip install --upgrade -I setup tools
python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/protobuf-3.0.0b2.post2-cp35-none-any.whl
```

**Comment by brando90** [comment]
just as a comment...I accidentally downloaded the MAC version in linux because the `--ignore-installed` allowed me. So if it still doesn't work that might be it.

**Comment by vincepy** [comment]
1.download [ez_setup.py](https://bootstrap.pypa.io/ez_setup.py)
2.run script >python ez_setup.py
It works for me (in windows 7)
