### ISSUE TITLE
tf.random.normal() causes RAM usage to keep growing

### ISSUE THREAD

**Issue by Djoren** [tensorflow/tensorflow#62203]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.13.0

### Custom code

No

### OS platform and distribution

macOS Venture 13.1 (22C65)

### Python version

3.8.3

### Current behavior?

**Issue** 
I'm getting what looks like a memory leak from running tf.random.normal as below, in eager mode. 
I have not encountered this issue with others versions, e.g. 2.12.1

**Context** 
I'm running RL algorithms using a TF-addon [NoisyDense](https://www.tensorflow.org/addons/api_docs/python/tfa/layers/NoisyDense) layer, which exposes a function that does the below random sampling. Since it's being executed millions of times, it causes exploding RAM.

**Notes**
Wrapping the random sampling inside a function decorated with tf.function seems to avoid the issue.

### Standalone code to reproduce the issue

```shell
import os, psutil
process = psutil.Process()
print(process.memory_info().rss / 1000000)  # Ram usage in MB

import tensorflow as tf
print(tf.__version__)

for _ in range(10):
    print(process.memory_info().rss / 1000000)
    for _ in range(5000):
        x = tf.random.normal(shape=(10000, 1))  # Causing growing RAM
```

### Relevant log output

```shell
382.963712
2.13.0
382.963712
385.220608
387.21536
388.927488
390.926336
392.392704
394.338304
396.374016
398.323712
400.273408
```

**Comment by maksym33** [comment]
Try `K.clear_session()` to delete unused graph parts. It might also be that the garbage collector will kick in further along the line,

**Comment by tilakrayal** [comment]
@Djoren,
I tried to execute the above mentioned code on tensorflow v2.14 & it was executed without any error and also observed that the RAM usage is also not growing as mentioned. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/eb3041a339486bf8b950c50a34e6cc00/untitled1423.ipynb). Thank you!

**Comment by nicolaspi** [comment]
@tilakrayal I am getting the problem with python 3.11, but not 3.10 (which is the version in your gist).

**Comment by tilakrayal** [comment]
@Djoren,
I tried to execute the mentioned code on the Linux environment with Tensorflow 2.16.1 and python 3.11 and couldn't find the memory leakage with the tf.random.normal(). Kindly find the screenshot for the reference.

![Screenshot 2024-06-11 6 13 31 PM](https://github.com/tensorflow/tensorflow/assets/81610181/46d6fe94-5764-4498-9a39-d529b9f18c7e)
