### ISSUE TITLE
Different behaviors of raw_ops.Sigmoid can be observed when jitcompiled=true.

### ISSUE THREAD

**Issue by zoux1a** [tensorflow/tensorflow#62206]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.14.0

### Custom code

Yes

### OS platform and distribution

Ubuntu 22.04.3 LTS (x86_64)

### CUDA/cuDNN version

11.8

### GPU model and memory

GPU 0: NVIDIA GeForce RTX 2070 GPU 1: NVIDIA GeForce RTX 2070 GPU 2: NVIDIA GeForce RTX 2070 GPU 3: NVIDIA GeForce RTX 2070

### Current behavior?

In TensorFlow, enabling jitcompiled results in inconsistent behavior of raw_ops.Sigmoid.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import traceback
class Network(tf.Module):
    def __init__(self):
        super().__init__()

    @tf.function(jit_compile=True)
    def __call__(self, x):       
      x = tf.raw_ops.Sigmoid(x=x, )        
      return x

m = Network()
inp = {
    "x": tf.random.uniform([10,9,8], dtype=tf.bfloat16),
}

with tf.device('/GPU:0'):
    tf.config.run_functions_eagerly(True)
    no_op_res = m(**inp)
    tf.config.run_functions_eagerly(False)
    with tf.device('/GPU:0'):
        op_res = m(**inp)

    tf.debugging.assert_near(tf.cast(no_op_res, tf.float64), tf.cast(op_res, tf.float64), atol=0.001, rtol=0.001)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/guihuan/LLM/results/tf-2/2023-10-22-20-21/test.py", line 27, in <module>
    tf.debugging.assert_near(tf.cast(no_op_res, tf.float64), tf.cast(op_res, tf.float64), atol=0.001, rtol=0.001)
  File "/home/guihuan/.conda/envs/night/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/guihuan/.conda/envs/night/lib/python3.9/site-packages/tensorflow/python/ops/control_flow_assert.py", line 102, in Assert
    raise errors.InvalidArgumentError(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b''
b'x and y not equal to tolerance rtol = tf.Tensor(0.001, shape=(), dtype=float64), atol = tf.Tensor(0.001, shape=(), dtype=float64)'
b'x (shape=(10, 9, 8) dtype=float64) = '
0.65234375, 0.5078125, 0.56640625, ...
b'y (shape=(10, 9, 8) dtype=float64) = '
0.59765625, 0.03125, 0.26953125, ...
```

**Comment by SuryanarayanaY** [comment]
Hi @zoux1a ,

I have replicated the reported behaviour. With jit_compile=True the results seems not in the precision level of `rtol=0.001`. If we change `rtol=0.01` then the results are same.

One more observation the behaviour seems from `eager = False`. With eager execution it works fine with given tolerances also.

Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/3481f0de94a04b050985455924192170/62206-gpu.ipynb).

**Comment by zoux1a** [comment]
I believe the results in eager mode and XLA-compiled mode should be consistent. Will this bug be fixed in the future?

**Comment by SuryanarayanaY** [comment]
Hi @zoux1a , For the Sigmoid Op, `bfloat16` dtype is not supported for XLA-GPU setup as per this [source](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2xla/g3doc/gpu_supported_ops.md#:~:text=int64%2Cuint32%2Cuint64%7D-,Sigmoid,-T%3D%7Bcomplex64%2Cdouble).

Could you please cross check and confirm.
