### ISSUE TITLE
Missing `'tensorflow.python.training.tracking'` in version 2.14.0; cannot load pickled model

### ISSUE THREAD

**Issue by dpiras** [tensorflow/tensorflow#62210]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.14.0

### Custom code

Yes

### OS platform and distribution

Google Colab

### Python version

3.10

### CUDA/cuDNN version

N/A

### Current behavior?

We used to load some pickled TF models using:

```
import pickle
pickle.load(open("/content/cosmopower/cosmopower/trained_models/CP_paper/CMB/cmb_TT_NN.pkl", 'rb'))
```

but as of version 2.14.0 we get:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-3-776b938106f2>](https://localhost:8080/#) in <cell line: 1>()
----> 1 pickle.load(open("/content/cosmopower/cosmopower/trained_models/CP_paper/CMB/cmb_TT_NN.pkl", 'rb'))

ModuleNotFoundError: No module named 'tensorflow.python.training.tracking'
```

We checked that there are no errors with TF `2.13.0`, and everything works as expected. The `tensorflow.python.training.tracking` module seems to have been removed since `2.14.0`, but we are unable to find it in the release notes. This error is observed on Colab as well as on other platforms and OSs.

### Standalone code to reproduce the issue

```shell
! git clone https://github.com/alessiospuriomancini/cosmopower.git # download folder with TF model

# this is intended for colab; change path if necessary
import pickle
pickle.load(open("/content/cosmopower/cosmopower/trained_models/CP_paper/CMB/cmb_TT_NN.pkl", 'rb'))
```

### Relevant log output

```shell
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-776b938106f2> in <cell line: 1>()
----> 1 pickle.load(open("/content/cosmopower/cosmopower/trained_models/CP_paper/CMB/cmb_TT_NN.pkl", 'rb'))

ModuleNotFoundError: No module named 'tensorflow.python.training.tracking'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by SuryanarayanaY** [comment]
Hi @dpiras ,

Could you please confirm whether the pickled model is of Tf2.14V. It seems there is shuffle in the module causing this error. 

The changes may happens in versions we need to change the imports accordingly.Also Tensorflow has its own APIs for serialization and deserialization.It is recommended to save the model in the official formats like `.keras` or `.tf` .

**Comment by dpiras** [comment]
@SuryanarayanaY many thanks for looking into this! 

The pickled model was created with a different version of TF, so below 2.14.0 (probably around 2.10). We never had a problem so far, though, even if using TF version 2.13.

We will definitely use the TF APIs for serialisation and deserialisation in the future, thank you for pointing them out!

**Comment by SuryanarayanaY** [comment]
@dpiras ,

AFAIK, Tensorflow will not recommend Pickle for serialization/deserialization and this package is not in requirement packages we won't provide official support for this and won't recommend users to use it. Thanks!

**Comment by dpiras** [comment]
@SuryanarayanaY thanks. So you are saying that the missing 'tensorflow.python.training.tracking' module is not planned to be restored in TF 2.14.0 and beyond?

**Comment by SuryanarayanaY** [comment]
@dpiras , I mean the tracking module not exists in the path `tensorflow.python.training.tracking` . The module seems exists at [tensorflow.python.trackable](https://github.com/tensorflow/tensorflow/tree/r2.14/tensorflow/python/trackable).

**Comment by dpiras** [comment]
@SuryanarayanaY ah, I see - thank you. I guess we can close this issue then, and in our package we will either use `< 2.14.0` or make sure we employ the TF serialisation tools available rather than `pickle`. Cheers!

**Comment by SuryanarayanaY** [comment]
@dpiras ,Thanks for confirmation. 

Closing the issue as per user confirmation.
