### ISSUE TITLE
slice_input_producer output tensor of wrong shape under certain conditions

### ISSUE THREAD

**Issue by RuohanW** [tensorflow/tensorflow#6222]
From the verison
tensorflow-0.12.0rc0-cp27-cp27mu-manylinux1_x86_64.whl

When using  tf.train.slice_input_producer with a tensor_list containing only a single tensor, the output from the tf.train.batch has incorrect dimension.

Code to reproduce it

```
import tensorflow as tf

data=tf.random_uniform(shape=(50, 50))
labels=tf.ones(50)
sample, _=tf.train.slice_input_producer([data, labels])
batch=tf.train.batch([sample], batch_size=8)

print batch

sample=tf.train.slice_input_producer([data])
batch=tf.train.batch([sample], batch_size=8)

print batch

```

the output is

```
Tensor("batch:0", shape=(8, 50), dtype=float32)
Tensor("batch_1:0", shape=(8, 1, 50), dtype=float32)

```

I think the two output should be the same? Simple workaround like reshaping the batch data is feasible. However, I think this is a bug.

**Comment by michaelisard** [comment]
@ebrevdo is this WAI?

**Comment by ebrevdo** [comment]
Good question. I'm ooo for 2 weeks.  Ispir may know better.

**Comment by ispirmustafa** [comment]
slice_input_producer returns a list.
First call expands the list due to double assignment.
Second call doesn't expand it.
second call of batch should be as follow:
batch=tf.train.batch(sample, batch_size=8)
