### ISSUE TITLE
how to self-hosting docs of old version

### ISSUE THREAD

**Issue by freeminder89** [tensorflow/tensorflow#62224]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

1.12

### Custom code

No

### Current behavior?

need to host old version doc as a website

### Standalone code to reproduce the issue

```shell
no code
```

**Comment by SuryanarayanaY** [comment]
Hi @freeminder89 ,

Tensorflow maintains its API documentation in tensorflow.org itself for all older versions. You can have a look of those [here](https://www.tensorflow.org/versions).

**Comment by freeminder89** [comment]
@SuryanarayanaY 
old version doc link goes to https://github.com/tensorflow/docs/tree/r1.12/site/en/api_docs
all markdown files, I want to convert these md files to html, then serving them as a website

1. markdown files view in github, the link in one doc ref to another always misses the .md suffix
2. miss latex code support

**Comment by SuryanarayanaY** [comment]
@freeminder89 , AFAIK, tensorflow.org hosts only API docs of older versions. I doubt about other resources. 

CC: @MarkDaoust , Would you please confirm whether there is a way? 

Thanks!

**Comment by MarkDaoust** [comment]
Yes, there are some problems with those old doc tags. 
But these aren't high-enough priority to fix now.

I to wouldn't be to hard, on your own fork to write a script to add the missing .md suffixes to the links.
