### ISSUE TITLE
Different Behavior of tf.raw_ops.Zeta+raw_ops.Cosh with jit_compile=True

### ISSUE THREAD

**Issue by zoux1a** [tensorflow/tensorflow#62237]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.14.0

### Custom code

Yes

### OS platform and distribution

Ubuntu 22.04.3 LTS (x86_64)

### CUDA/cuDNN version

11.8

### GPU model and memory

GPU 0: NVIDIA GeForce RTX 2070 GPU 1: NVIDIA GeForce RTX 2070 GPU 2: NVIDIA GeForce RTX 2070 GPU 3: NVIDIA GeForce RTX 2070

### Current behavior?

When the tf.raw_ops.Zeta+tf.raw_ops.Cosh operation is invoked within a tf.function with JIT compilation enabled (jit_compile=True), it produces different results compared to the same operation called without JIT compilation. This inconsistency is observed when the code is executed on a CPU device.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import traceback

def replace_special_values(tensor):
    # Convert tensor to tf.float32 if it's not a supported dtype
    supported_dtypes = [tf.float16, tf.float32, tf.float64, tf.bfloat16]
    if tensor.dtype not in supported_dtypes:
        original_dtype = tensor.dtype
        tensor = tf.cast(tensor, tf.float32)
    else :
        original_dtype = None
    
    # Replace NaNs with zeros
    tensor = tf.where(tf.math.is_nan(tensor), tf.zeros_like(tensor), tensor)
    
    # Replace positive infinities with a large number (e.g., 1e30)
    tensor = tf.where(tf.math.is_inf(tensor), 100, tensor)
    
    # Replace negative infinities with a small number (e.g., -1e30)
    tensor = tf.where(tf.math.is_inf(tensor) & tf.math.less(tensor, 0), -100, tensor)
    
    # Convert tensor back to its original dtype
    if original_dtype is not None :
        tensor = tf.cast(tensor, original_dtype)
    return tensor

class Network(tf.Module):
    def __init__(self):
        super().__init__()

    @tf.function(jit_compile=True)
    def __call__(self, x):
      tensor = tf.random.normal([10, 10, 6, 1], dtype=tf.float32)
      x = tf.raw_ops.Zeta(q=x, x=tensor)        
      x = tf.raw_ops.Cosh(x=x, )        
      return x

is_valid = True
inf = float('inf')
m = Network()
tensor = tf.random.normal([6, 10, 10, 1, 8], dtype=tf.float32)
inp = {
    "x": tensor,
}

with tf.device('/CPU:0'):
    tf.config.run_functions_eagerly(True)
    no_op_res = m(**inp)
    tf.config.run_functions_eagerly(False)
    with tf.device('/CPU:0'):
        op_res = m(**inp)
    no_op_res = replace_special_values(no_op_res)
    op_res = replace_special_values(op_res)
    tf.debugging.assert_near(tf.cast(no_op_res, tf.float64), tf.cast(op_res, tf.float64), atol=0.001, rtol=0.001)
```

### Relevant log output

```shell
File "/home/guihuan/LLM/results/tf-2/2023-10-22-20-21/test.py", line 54, in <module>
    tf.debugging.assert_near(tf.cast(no_op_res, tf.float64), tf.cast(op_res, tf.float64), atol=0.001, rtol=0.001)
  File "/home/guihuan/.conda/envs/night/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/guihuan/.conda/envs/night/lib/python3.9/site-packages/tensorflow/python/ops/control_flow_assert.py", line 102, in Assert
    raise errors.InvalidArgumentError(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b''
b'x and y not equal to tolerance rtol = tf.Tensor(0.001, shape=(), dtype=float64), atol = tf.Tensor(0.001, shape=(), dtype=float64)'
b'x (shape=(6, 10, 10, 6, 8) dtype=float64) = '
0.0, 0.0, 0.0, ...
b'y (shape=(6, 10, 10, 6, 8) dtype=float64) = '
0.0, 0.0, 0.0, ...
```

**Comment by sushreebarsa** [comment]
Hi, @zoux1a!

I was able to replicate the issue reported [here](https://colab.research.google.com/gist/sushreebarsa/6005eacee2679e38843210e7ccf66778/62237.ipynb). Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @zoux1a ,

I noticed an issue here.

Inside the `__call__` function you are generating the value for tensor, which in each calls generates different random values because XLA currently ignores TF seeds to random operations which makes the output different for obvious reason. Please refer [known](https://www.tensorflow.org/xla/known_issues#random_number_generation_ignores_tf_seed) issues from XLA section.

Hence I have taken the random input to outside the XLA scope and done the code changes and executed the code 10 runs and it executed successfully. Since the input is `float32` which is default for XLA the execution is success for your `atol=0.001` and ` rtol=0.001` 

Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/d970c2bd79dca7e44b3ab782dcf96f4d/62247_final.ipynb).
