### ISSUE TITLE
Tensorflow requires Python<3.8 for Docker

### ISSUE THREAD

**Issue by frkanyilmaz2** [tensorflow/tensorflow#62248]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.14

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Python version

3.9.18-slim-bullseye

### Current behavior?

When I tried create a container which based on python:3.9.18-slim-bullseye by docker compose, tensorflow didn't let the build complete as it required python >2.6 and python<3.8. 

### Standalone code to reproduce the issue

```shell
FROM python:3.9.18-slim-bullseye

RUN pip install --upgrade pip && pip install pip-tools

COPY ./requirements.txt .

RUN pip install -r requirements.txt

WORKDIR /app

## add app
COPY . /app

RUN apt-get update && apt-get install -y netcat

ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini /tini
RUN chmod +x /tini
# Set Tini as the ENTRYPOINT and specify Uvicorn CMD
ENTRYPOINT ["/tini", "--"]
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "30022"]



requirements.txt

tensorboard==2.14.0
tensorboard-data-server==0.7.2
tensorflow==v2.15.0-rc0
tensorflow-estimator==v2.15.0-rc0
tensorflow-intel==v2.15.0-rc0
tensorflow-io-gcs-filesystem==0.31.0
```

### Relevant log output

```shell
ERROR: Ignored the following versions that require a different python version: 0.2.1 Requires-Python >2.6, !=3.3.*, <3.8
ERROR: Could not find a version that satisfies the requirement tensorflow-intel==2.14.0 (from versions: 0.0.1)
ERROR: No matching distribution found for tensorflow-intel==2.14.0
```

**Comment by SuryanarayanaY** [comment]
@frkanyilmaz2 ,

Here are my observations. 

Tf2.14 needs Python to be in 3.9-3.11 versions range. Please refer the source for tested configurations.Python <3.8 is not in supported range and may raise backward compatibility issues.
 
From the error log it searching for `tensorflow-intel==2.14.0` which is intel package intended for Windows CPU environment. For Linux TF has its own package which can be installed by using `pip install tensorflow` command itself. Could you please cross check the environment details and import suitable TF package.
