### ISSUE TITLE
Feature request to specify substitutions in embedding_lookup for invalid indices 

### ISSUE THREAD

**Issue by sonalgupta** [tensorflow/tensorflow#6226]
In the current master code, https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/gather_op.cc it says that the attribute _validate_indices_ is not supported anymore:
` // We used to grab the validate_indices attribute here, but now we
    // always validate indices since the speed difference was only 1.5%.
    // TODO(irving): Remove the validate_indices attribute once we have
    // support for removing attrs in a backwards compatible way.`

I actually do want an option to specify validate_indices as false. I am using _embedding_lookup_ and it would be useful for out of vocabulary words that are not in the embedding matrix.  

If it's not possible to support _validate_indices_, can you suggest a way to get all zeros (instead of an exception) for indices that are not in the embedding matrix.

**Comment by girving** [comment]
I have 1.5 hours left before parental leave, so I'm not going to get to this.  However, this bug isn't about "bringing back validate indices"; it's about doing something entirely different where invalid indices are replaced with something else.

**Comment by sonalgupta** [comment]
Yes. If there's a way to specify substitutions for invalid indices, that would be great! 

(PS: congrats!)

**Comment by michaelisard** [comment]
I think the request was to bring back validate_indices as a preferred course of action, and if not, to suggest the workaround that would do something else entirely. Who is a good person to look at this?

**Comment by girving** [comment]
"Bringing back validate indices" doesn't make any sense, since the default today is check for invalid indices.  If we allowed turning that off, it would mean bringing back the ability for tf.gather to segfault.  You might get lucky and have the segfault do what you what, but it's not likely.

@ebrevdo is a good person to ask.

**Comment by ebrevdo** [comment]
Replace invalid indices with 0 via tf.where/tf.select and after the embedding lookup, replace the output rows you got from the invalid indices with tf.zeros, again using broadcasting tf.where/tf.select
