### ISSUE TITLE
tensorflowlite build error about fatal error C1001:Internal compiler error for O2 option

### ISSUE THREAD

**Issue by leizhu1989** [tensorflow/tensorflow#62272]
**System information**
- OS: windows11 
- TensorFlow Lite in Play Services SDK version (found in `build.gradle`): 2.12
-  build method: cmake -A Win32 ..\tensorflow\lite\c -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=True -DTFLITE_ENABLE_XNNPACK=ON -DCMAKE_BUILD_TYPE=Release
**Standalone code to reproduce the issue**
I want to use O2 compilation to improve speed, but there was a "D:\project\tensorflow\build_win32_dll\gemmlowp\internal\output.h(176): fatal error C1001:Internal compiler error" error when compiling TensorFlow Lite.lib in win32 release mode, What is the reason for this situation?  When I check to O1, it has succeeded.

**Comment by sushreebarsa** [comment]
@leizhu1989 Could you please check our compatibility matrix for each TF version at https://www.tensorflow.org/install/source_windows#tested_build_configurations ? Maybe the different version, it was not compiling. Kindly check your local path and change the version internally, if required!
Thank you!

**Comment by leizhu1989** [comment]
@sushreebarsa  thank you for your quick reply . When I checkout to r2.6 branch as "https://www.tensorflow.org/install/source_windows#tested_build_configurations" show it is still error
my command: cmake -A Win32 ..\tensorflow\lite\c -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=True -DTFLITE_ENABLE_XNNPACK=ON -DCMAKE_BUILD_TYPE=Release

it show:
  Completed 'psimd'
  Building Custom Rule D:/project/tensorflow/build_win32_2.6/psimd-download/CMakeLists.txt
  Building Custom Rule D:/project/tensorflow/build_win32_2.6/psimd-download/CMakeLists.txt
Disabling MSVC /O2 optimization for Win32
-- Configuring done
-- Generating done
-- Build files have been written to: D:/project/tensorflow/build_win32_2.6
why it Disabled O2?

the same error:
"D:\project\tensorflow\build_win32_2.6\gemmlowp\internal\output.h(176): fatal error C1001:Internal compiler error"

when I try use bazel to build for version r2.12:
bazel build -c opt --config=mkl //tensorflow/lite/c:tensorflowlite_c.dll --cpu=x64_x86_windows

it has error:
INFO: Build option --define has changed, discarding analysis cache.
WARNING: Download from https://golang.org/dl/?mode=json&include=all failed: class java.io.IOException connect timed out
ERROR: C:/users/xxx/_bazel_xxx/qotdwtts/external/cpuinfo/BUILD.bazel:104:11: configurable attribute "srcs" in @cpuinfo//:cpuinfo_impl doesn't match this configuration. Would a default condition help?

Conditions checked:
 @cpuinfo//:linux_x86_64
 @cpuinfo//:linux_arm
 @cpuinfo//:linux_armhf
 @cpuinfo//:linux_armv7a
 @cpuinfo//:linux_armeabi
 @cpuinfo//:linux_aarch64
 @cpuinfo//:linux_mips64
 @cpuinfo//:linux_riscv64
 @cpuinfo//:linux_s390x
 @cpuinfo//:macos_x86_64
 @cpuinfo//:macos_arm64
 @cpuinfo//:windows_x86_64
 @cpuinfo//:android_armv7
 @cpuinfo//:android_arm64
 @cpuinfo//:android_x86
 @cpuinfo//:android_x86_64
 @cpuinfo//:ios_x86_64
 @cpuinfo//:ios_x86
 @cpuinfo//:ios_armv7
 @cpuinfo//:ios_arm64
 @cpuinfo//:ios_arm64e
 @cpuinfo//:ios_sim_arm64
 @cpuinfo//:watchos_x86_64
 @cpuinfo//:watchos_x86
 @cpuinfo//:watchos_armv7k
 @cpuinfo//:watchos_arm64_32
 @cpuinfo//:tvos_x86_64
 @cpuinfo//:tvos_arm64
 @cpuinfo//:emscripten_wasm
 
how can I build win32 with O2 for accelerating？

**Comment by sushreebarsa** [comment]
@leizhu1989 Thank you for your reply! 
TF v2.6 is an older version which is not recommended to be used. Could you please let us know which version of Microsoft Visual Studio compiler you are using ? As a workaround you may use a different version of the compiler.
Thank you!

**Comment by leizhu1989** [comment]
thank you for your reply!
my compiler and windows sdk:

windows sdk:10.0.19041.0
visual studio 2019(v142)

**Comment by leizhu1989** [comment]
@sushreebarsa thank you for your reply!
my compiler and windows sdk:

windows sdk:10.0.19041.0
visual studio 2019(v142)

**Comment by sushreebarsa** [comment]
@leizhu1989 Thanks again!
 Please try to install the most recent release from https://visualstudio.microsoft.com/downloads/ , which should fix this issue. Thank you!

**Comment by leizhu1989** [comment]
thank you very much!
It means that should I use visual studio 2022 and the r2.12 version of tensorflowlite to build  tensorflowlite_c?

**Comment by leizhu1989** [comment]
@sushreebarsa thank you very much!
It means that should I use visual studio 2022 and the r2.12 version of tensorflowlite to build tensorflowlite_c?

**Comment by leizhu1989** [comment]
@sushreebarsa hi！ I'm very sorry for not answering accurately before, my compiler is like this:
-- Building for: Visual Studio 16 2019
-- The C compiler identification is MSVC 19.29.30146.0
-- The CXX compiler identification is MSVC 19.29.30146.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done

**Comment by sushreebarsa** [comment]
@leizhu1989 Thanks for your reply!
Is there any luck with visual studio 2022 so far?
Thank you!

**Comment by leizhu1989** [comment]
@sushreebarsa sorry to reply late, I have not try on visual studio 2022. I recently deployed on Centos

**Comment by sushreebarsa** [comment]
@leizhu1989 Could you please try the same and let us know the outcome?
Thank you!

**Comment by leizhu1989** [comment]
@sushreebarsa thank you for your reply ,I plan to first finish my algorithm job for linux and android. Then, I will try it in visual studio 2022, is this ok? when I try it out ,I will tell you the result, thank you very much
