### ISSUE TITLE
Documentation of `tf.nn.depthwise_conv2d` fails to mention limitation on strides

### ISSUE THREAD

**Issue by burnpanck** [tensorflow/tensorflow#62271]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.14.0

### Custom code

No

### OS platform and distribution

macOS 13.6

### Mobile device

none

### Python version

3.11

### Current behavior?

Apparently, tensorflow's [`tf.nn.depthwise_conv2d`](https://www.tensorflow.org/api_docs/python/tf/nn/depthwise_conv2d) recently lost the ability to work with inequal strides (see #60391; apparently it was supported up to TF 2.11). This is mentioned in the documentation of [`tf.keras.layers.SeparableConv2D`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/SeparableConv2D) (albeit IMHO it should be more emphasised given that this is a limitation specific to depthwise convolutions).

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
layer1 = tf.nn.depthwise_conv2d(np.ones((2,3,4,5)),filter=np.ones((1,2,5)),strides=(1,1,2,1),padding="SAME")
```

### Relevant log output

```shell
InvalidArgumentError: {{function_node __wrapped__DepthwiseConv2dNative_device_/job:localhost/replica:0/task:0/device:CPU:0}} Current implementation only supports equal length strides in the row and column dimensions. [Op:DepthwiseConv2dNative] name:
```

**Comment by Venkat6871** [comment]
Hi **@burnpanck ,**
I was able to replicate this issue. I checked with equal and unequal strides with tf 2.14 and tf.nightly. The filter tensor should be as follows;
 ' [filter_height, filter_width, in_channels, channel_multiplier]'  then only it runs with equal strides. Otherwise it shows an error with equal strides too.  I attached a[ gist ](https://colab.research.google.com/drive/1GsLmX8Pv7CqVwWrBtSaVsURLhqOH73Pr?authuser=0#scrollTo=uizxFnPOeqFz)here for your reference.

Thank you!

**Comment by burnpanck** [comment]
@Venkat6871 I'm not quite sure I understand what you are saying, except for that you can confirm that `tf.nn.depthwise_conv2d` does not conform to it's documentation. As far as I can see, there is unfortunately no workaround that would let us do the equivalent operation efficiently. So it just remains a documentation bug that should be fixed. I had spent many hours figuring out how to map a custom layer to TF, and the only way I could do it was using unqeual strides. If the documentation had mentioned this limitation, then I could have spared myself that effort. There may be others who run into this, so I think it should be fixed.

**Comment by thegodone** [comment]
But it can be interesting to remove this limitation!
