### ISSUE TITLE
How to Test all OPS/KERNELS Accuracy and Performance in my one device?

### ISSUE THREAD

**Issue by udsrrcck02819** [tensorflow/tensorflow#62302]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

1.15

### Custom code

Yes

### Current behavior?

I have a device X
I am adapting TensorFlow on X
I want to know if my kernel are **Correct** and it's **Performance**，so  I'll test nearly **ALL ops** both on CPU/GPU/TPN  and X, and comparison results
if there is a **.py** to test all ops? or I need to write every case maself?

### Standalone code to reproduce the issue

```shell
nothing
```

**Comment by sachinprasadhs** [comment]
Hi, 

For platform level test, there is a test file here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/test.py.

For OP specific, there will be separate test files, which you can find it similar to this file here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/eager/ops_test.py

TensorFlow has majority of test cases implemented in both `.py and .cc`.
For any specific file, the relevant test file will be `filename_test.py/.cc` similar to the example here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/conv3d_test.cc
