### ISSUE TITLE
Incorrect/outdated link in Beginner Quickstart guide.

### ISSUE THREAD

**Issue by sunny0531** [tensorflow/tensorflow#62306]
https://www.tensorflow.org/tutorials/quickstart/beginner
It has a link to the MNIST dataset and it leads to http://yann.lecun.com/exdb/mnist/
I assume that used to be the right link but now it require login to visit? So should it be removed or is there a new website? 
Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @sunny0531,

I have verified the reported problem and agree that the mnist link now asking for credentials to join. Will look into it and take appropriate action. Thanks!

**Comment by Antonyj12** [comment]
Hi @sunny0531,
I believe we need to use this link https://web.archive.org/web/20220331130319/https://yann.lecun.com/exdb/mnist/ instead of that link which requires credentials. I have verified the issue from my end.

**Comment by sunny0531** [comment]
Thanks for the link! @Antonyj12 
And it seems to work on my device, so that might be a suitable replacement

**Comment by SuryanarayanaY** [comment]
Hi @sunny0531 ,

The hyperlink to mnist dataset is removed with the above PR because it is external dependency and it won't affect the guide anyways.

**Comment by sunny0531** [comment]
Seeing how the pull request is merged, I will close this now. Thanks for your help!
