### ISSUE TITLE
Poor colors for embedding projector

### ISSUE THREAD

**Issue by mzduchon** [tensorflow/tensorflow#6230]
The second and third colors available in "color by" are extremely similar when there is overlap: the second color (orangish) appears very similar to third (redish) one.   This prevents any pop-out effect.

**Comment by PAK90** [comment]
Being able to customise the colours would be a massive improvement too.

**Comment by korakot** [comment]
When there are multiple values, I wish it could display color by gradient scale.
The color now only works as categoy. I cannot represent continuous values.

**Comment by dsmilkov** [comment]
This would be a great external contribution - would be great to also have feedback from a color blind person, so we can make a color-blind friendly palette.

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity , but please let me know if I'm mistaken. Thanks!

**Comment by uahmad235** [comment]
Any leads on this feature?
