### ISSUE TITLE
Remove resizeInput interface to TFLite Interpreter

### ISSUE THREAD

**Issue by Burton2000** [tensorflow/tensorflow#62303]
As per the issue linked below, it appears that resizeInput is no longer supported due to performance issues so should be removed as an interface from the TFLite Interpreter.

> @Burton2000 So we essentially dropped support of dynamic input shapes generally speaking due to performance considerations and the difficulty of supporting it while maintaining good performance. But of course since this issue is old, maybe this wasn't true at the time, and I think resizeInput is a legacy interface that we should probably remove. In order for us to properly prioritize, can you perhaps create a new issue to remove that interface so that we can remain consistent in our design philosophy? Thanks for your help.

_Originally posted by @pkgoogle in https://github.com/tensorflow/tensorflow/issues/44016#issuecomment-1787818211_

**Comment by pkgoogle** [comment]
Hi @Burton2000, apologies for all the whiplash but TF and TFL are a living codebases so everything is quite dynamic still. With 2.15 we are currently supporting dynamic input shapes: https://www.tensorflow.org/lite/guide/inference#run_inference_with_dynamic_shape_model That being said, please try your previous test to see if the original issue, is still an issue, and then we can take it from there.

**Comment by Burton2000** [comment]
Hey @pkgoogle not a problem. There is no .aar of 2.15.0 of TFLite available on maven to try, I updated to 2.14.0 which is the latest available there but no difference to previous issue reported.

**Comment by pkgoogle** [comment]
Hi @LakshmiKalaKadali, can you please take a look? Thanks.

**Comment by pkgoogle** [comment]
As this issue is no longer valid and there is a workaround for the original issue which does not affect performance we will close this issue as invalid.
