### ISSUE TITLE
Not supported logical op case.

### ISSUE THREAD

**Issue by WenhuiZhao-center** [tensorflow/tensorflow#62314]
hi,when i use tensorflow lite gpu delegate to invoke a lite model, it warning:
EQUAL: Not supported logical op case.

tensorflow version: 2.6.2

I find this code in tensorflow/lite/gpu/common/model_builder.cc:
    if (IsLogicalOp(operation_type_)) {
      TensorInfo output_tensor_info;
      RETURN_IF_ERROR(GetTensorInfo(context, tflite_node->outputs->data[0],
                                    &output_tensor_info));
      if (output_tensor_info.producers.size() != 1 ||
          output_tensor_info.consumers.size() != 1) {
        return absl::UnavailableError("Not supported logical op case");
      }
      if (output_tensor_info.consumers[0].second->builtin_code ==
          kTfLiteBuiltinCast) {
        return absl::OkStatus();
      } else {
        return absl::UnimplementedError("Not supported logical op case.");
      }
    }

i don't understand why logicalop not supported on gpu delegate. And what should i do to make this logicalop can execute on gpu delegate?

**Comment by Venkat6871** [comment]
Hi @**WenhuiZhao-center** 
Can you add templates. And here you are using the old version please upgrade to the latest version Tf 2.14.
Thank you!
