### ISSUE TITLE
hlo_pb2

### ISSUE THREAD

**Issue by never-to-never** [tensorflow/tensorflow#62312]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf2.8

### Custom code

Yes

### Current behavior?

My program relies on a file such as hlo_pb2, which is imported from tensorflow.compiler.xla.service import hlo_pb2. This brings up a problem, I need to install tensorflow. But I don’t want to install the entire tensorflow when deploying. Is there any way to get hlo_pb2 by compiling certain files in xla?

### Standalone code to reproduce the issue

```shell
I don't know how to do it, please help
```

**Comment by SuryanarayanaY** [comment]
Hi @never-to-never ,

You can use bazel build command some thing like `bazel build //<target_file>` then include it in your project. Please refer bazel [documentation](https://bazel.build/run/build#specifying-build-targets) for more details.

Hope it helps. Thanks!
