### ISSUE TITLE
ImportError: cannot import name '__version__' from 'tensorflow.keras' \

### ISSUE THREAD

**Issue by siddharthahiremath** [tensorflow/tensorflow#62318]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.14.0

### Custom code

Yes

### OS platform and distribution

M1 macbook pro macOS 13.4.1 (22F82)

### Python version

3.11.4

### Current behavior?

Failing to import DQNAgent

### Standalone code to reproduce the issue

```shell
from rl.agents import DQNAgent
```

### Relevant log output

```shell
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/Users/siddharthahiremath/Ai_myaybe?.ipynb Cell 9 line 1
----> 1 from rl.agents import DQNAgent
      2 from rl.policy import BoltzmannQPolicy
      3 from rl.memory import SequentialMemory

File /opt/homebrew/lib/python3.11/site-packages/rl/agents/__init__.py:1
----> 1 from .dqn import DQNAgent, NAFAgent, ContinuousDQNAgent
      2 from .ddpg import DDPGAgent
      3 from .cem import CEMAgent

File /opt/homebrew/lib/python3.11/site-packages/rl/agents/dqn.py:7
      4 from tensorflow.keras.models import Model
      5 from tensorflow.keras.layers import Lambda, Input, Layer, Dense
----> 7 from rl.core import Agent
      8 from rl.policy import EpsGreedyQPolicy, GreedyQPolicy
      9 from rl.util import *

File /opt/homebrew/lib/python3.11/site-packages/rl/core.py:7
      4 import numpy as np
      5 from tensorflow.keras.callbacks import History
----> 7 from rl.callbacks import (
      8     CallbackList,
      9     TestLogger,
...
----> 8 from tensorflow.keras import __version__ as KERAS_VERSION
      9 from tensorflow.python.keras.callbacks import Callback as KerasCallback, CallbackList as KerasCallbackList
     10 from tensorflow.python.keras.utils.generic_utils import Progbar

ImportError: cannot import name '__version__' from 'tensorflow.keras' (/opt/homebrew/lib/python3.11/site-packages/keras/api/_v2/keras/__init__.py)
```

**Comment by tilakrayal** [comment]
@siddharthahiremath,
Could you please try to import the keras directly as **import keras**. I tried and it was able to import the keras on tensorflow v2.14. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/bf75918fdc7c6bc3b707e4b5787018c5/untitled1494.ipynb). Thank you!

**Comment by tilakrayal** [comment]
Hi,

Thanks for reporting the issue.

Since the migration, there were many changes made, the error you are getting is due to one such change here https://github.com/keras-team/tf-keras/commit/cff6ac903e2b8a0dde2a469d949f0f0ce3b5f282.

To get rid of the error, you need to install tf-keras-nightly as well as tf-nightly.

Note that, tf-keras-nightly is legacy Keras code, to use the Keras 3 with multi-backend support, use keras-nightly and import Keras directly. Thank you!
