### ISSUE TITLE
SentencepieceOp for TFLite android

### ISSUE THREAD

**Issue by istoneyou** [tensorflow/tensorflow#62315]
I convert the [universal-sentence-encoder-multilingual](https://tfhub.dev/google/universal-sentence-encoder-multilingual/3) model to TFLite, and deploy it on Android 13 device with Tensorflow lite.
```
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly-SNAPSHOT'
```
The below error appears when create Interpreter:
 Caused by: java.lang.IllegalArgumentException: Internal error: Cannot create interpreter: Op type not registered 'SentencepieceOp' in binary running on localhost. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib (e.g. `tf.contrib.resampler`), accessing should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
                                                             Delegate kernel was not initialized
                                                             Node number 301 (TfLiteFlexDelegate) failed to

**Comment by sushreebarsa** [comment]
Hi, @istoneyou!

 Please have a look at the following steps to fix such issues;
1. Build TensorFlow Lite with SentencePiece support.
2. Use a TensorFlow Lite binary that was built with SentencePiece support.
Could you try to use the latest TF version and refer to [this]( https://www.tensorflow.org/lite/guide/android) guide as well.
Thank you!

**Comment by istoneyou** [comment]
Hi @sushreebarsa 
I used the [prebuilt AAR with TensorFlow ops hosted at MavenCentral](https://search.maven.org/artifact/org.tensorflow/tensorflow-lite-select-tf-ops) like belows, but it does not work.
```
    implementation 'org.tensorflow:tensorflow-lite:0.0.0-nightly-SNAPSHOT'
    implementation 'org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly-SNAPSHOT'
    implementation 'org.tensorflow:tensorflow-lite-support:0.0.0-nightly-SNAPSHOT'
    implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:0.0.0-nightly-SNAPSHOT'
```
Does the prebuilt AAR support the SentencePiece? Do I have to build the AAR that supports the SentencePiece by myself?

**Comment by sushreebarsa** [comment]
Hi, @istoneyou!
 No, the pre-built AAR does not support the SentencePiece. To use the SentencePiece, you need to build the AAR that supports it.

To build the AAR, you will need to install the following:

1. The Android SDK
2. The Gradle build tool
3. The TensorFlow Lite Java API

Thank you!
