### ISSUE TITLE
Enable to build TF Lite for armv7-a , vfpv3

### ISSUE THREAD

**Issue by ghchams** [tensorflow/tensorflow#62311]
### System information

- **Target architecture**: armv7 with vfpv3 
- **Target OS**: Debian 10 or Debian 12 
- **OS Platform and Distribution (e.g., Linux Ubuntu 22.04 LTS)**:
- **TensorFlow installed from (source or binary)**: source
- **Python version**:  trying to build for 3.7 or 3.11 
- **Bazel version (if compiling from source)**:  6.1.0
- **GCC/Compiler version (if compiling from source)**: 2.35 
- **CUDA/cuDNN version**: N/A (Building for ARM)
- **GPU model and memory**: N/A (Building for ARM)

I'm trying to build TensorFlow Lite for an ARMv7 architecture with vfpv3 support, but I've encountered multiple issues during the build process:
build/xnnpack/src/amalgam/gen/armsimd32.c:1832:48: error: expected ';' before '__sel'
     const int16x2_t vmultiplier02 = (int16x2_t) __sel((uint8x4_t) vnegative_multiplier, (uint8x4_t) vpositive_multiplier);

When attempting to cross-compile using the command:
bazel build --config=elinux_armhf -c opt //tensorflow/lite:libtensorflowlite.so
the resultant library is tailored for the armv8 ABI with vfpv4, even though I specified flags for vfpv3.

Attempting to build a TensorFlow Lite wheel with the following command:
CI_DOCKER_EXTRA_PARAMS="-e CUSTOM_BAZEL_FLAGS=--copt=-mfpu=neon-vfpv3 -e CI_BUILD_PYTHON=python3 -e CROSSTOOL_PYTHON_INCLUDE_PATH=/usr/include/python3.6" \
tensorflow/tools/ci_build/ci_build.sh PI-PYTHON3 tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh armhf
resulted in multiple errors.

Furthermore, referencing a previous issue (#39957) did not offer a solution, as it pointed towards older packages and was based on an older version of Ubuntu. Additionally, the PI-Python3 file mentioned in the issue seems to be missing from the TensorFlow repository.

Does TensorFlow Lite officially support the vfpv3 architecture?
Is it feasible to build a TensorFlow Lite Python wheel that's compatible with armv7 with vfpv3?

**Comment by sushreebarsa** [comment]
@ghchams Yes, TensorFlow Lite officially supports the VFPv3 architecture. TensorFlow Lite supports a wide range of devices, including smartphones, tablets, wearables, and embedded devices with ARM, NEON, and VFPv3. 
Please have a look at this for more information; https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite

Thank you!

**Comment by ghchams** [comment]
Thank you for your response : 
cross compiling Tflite with bazel gives the following Lib file : 
i used this command  bazel build --config=elinux_armhf -c opt //tensorflow/lite:libtensorflowlite.so 

 readelf -A bazel-bin/tensorflow/lite/libtensorflowlite.so
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "8.2-A"
  Tag_CPU_arch: v8
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: FP for ARMv8
  Tag_Advanced_SIMD_arch: NEON for ARMv8.1
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
  Tag_FP_HP_extension: Allowed
  Tag_ABI_FP_16bit_format: IEEE 754
  Tag_MPextension_use: Allowed
  Tag_Virtualization_use: TrustZone and Virtualization Extensions

my target architecture is armv7 , could please explain? (i'm NOT using a raspberry PI) 
Thank you
