### ISSUE TITLE
Format Error on the Website

### ISSUE THREAD

**Issue by ZijiaLewisLu** [tensorflow/tensorflow#6232]
Hi, on tensorflow.org there is part of documentation accidentally formatted into code. It's not a serious problem.  It's about initializer on r0.11. I didn't check if other versions have the same problem. Just  want to post it here for your information.

![screen shot 2016-12-09 at 20 41 19](https://cloud.githubusercontent.com/assets/16264284/21070208/e29a628e-be4f-11e6-973e-e5a936a5f794.png)

[link: https://www.tensorflow.org/versions/r0.11/api_docs/python/state_ops.html#random_normal_initializer](https://www.tensorflow.org/versions/r0.11/api_docs/python/state_ops.html#random_normal_initializer) (this actually won't lead you right to the location because of the error ).

**Comment by michaelisard** [comment]
This seems fixed at head. @xmbrst is this worth fixing in earlier versions?

**Comment by gunan** [comment]
@tfboyd PTAL

**Comment by gunan** [comment]
looks OK in the new website. closing.
