### ISSUE TITLE
Truble with building on Arch

### ISSUE THREAD

**Issue by dani3l125** [tensorflow/tensorflow#62325]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.14

### Custom code

Yes

### OS platform and distribution

Arch Linux

### Python version

3.11

### Bazel version

6.4.0

### GCC/compiler version

none (clang-16)

### CUDA/cuDNN version

none

### GPU model and memory

none

### Current behavior?

Hi,

I was trying to build with different flags, as well as using gcc6.4.0 and could not complete the build yet.

Would be happy to hear any advice!

### Standalone code to reproduce the issue

```shell
bazel build --compilation_mode=dbg --verbose_failures -j 4 --config=opt //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```shell
/home/daniel/tensorflow/tensorflow/BUILD:1303:21: Linking tensorflow/libtensorflow_cc.so.2.16.0 failed: (Exit 1): clang-16 failed: error executing command (from target //tensorflow:libtensorflow_cc.so.2.16.0)    (cd /home/daniel/.cache/bazel/_bazel_daniel/79db702fc9f94af7d11e11c5d64854d0/execroot/org_tensorflow && \   exec env - \     CLANG_COMPILER_PATH=/usr/bin/clang-16 \     PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl \     PWD=/proc/self/cwd \     PYTHON_BIN_PATH=/usr/bin/python3 \     PYTHON_LIB_PATH=/usr/lib/python3.11/site-packages \     TF2_BEHAVIOR=1 \   /usr/bin/clang-16 @bazel-out/k8-dbg/bin/tensorflow/libtensorflow_cc.so.2.16.0-2.params) # Configuration: 739e79f61a896ec2b9b5142b2c84f775153b8318dec3ac78c15572b987f2e3d8 # Execution platform: @local_execution_config_platform//:platform clang-16: error: unable to execute command: Killed clang-16: error: linker command failed due to signal (use -v to see invocation) Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

**Comment by sushreebarsa** [comment]
@dani3l125 Could you please make sure that you are using the latest version of the clang-16 compiler?
Thank you!

**Comment by Zhurakovsky** [comment]
Hi @dani3l125 
I was succeeded in building '//tensorflow/tools/pip_package:build_pip_package' right now with the command that you provided: `$ bazel build --compilation_mode=dbg --verbose_failures -j 4  --config=opt //tensorflow/tools/pip_package:build_pip_package` on this commit id: 1c7adbb1e798211fde6f423c70bbc604a3a1e879 

You might consider the next helpful steps, [mentioned here](https://www.tensorflow.org/install/source). 
Please note, that before installation I had a previous version of clang  (clang-14), installed on my workstation.
I installed clang-16: `sudo apt-get update && sudo apt-get install -y llvm-16 clang-16`
Then during the configuration stage `$ ./configure` I checked that Bazel 6.4.0 is installed (You have bazel 6.4.0 installed.) on my system. As well as clang-16 (You have Clang 16.0.6 installed).

So, after running the command `$ bazel build --compilation_mode=dbg --verbose_failures -j 4  --config=opt //tensorflow/tools/pip_package:build_pip_package` I've got the expected result:
`INFO: 15025 processes: 493 internal, 14532 local.
INFO: Build completed successfully, 15025 total actions
`
Hope it will help.

**Comment by dani3l125** [comment]
Thank you for the responses! I have moved to another set up a while after opening the issue and didn't get to close it. Sorry for that :(: 
I will let you know if I resolve it.
