### ISSUE TITLE
TensorFlow was not built with CUDA kernel binaries compatible with compute capability 9.0

### ISSUE THREAD

**Issue by RocketRider** [tensorflow/tensorflow#62320]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

TF 2.15.0_rc0

### Custom code

Yes

### OS platform and distribution

Ubuntu 22.04

### Python version

3.11

### Current behavior?

Tested with TF 2.15.0_rc0 on a Machine with 8xH100.
I do get the warning "TensorFlow was not built with CUDA kernel binaries compatible with compute capability 9.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer."
Is it then using the full potential of the GPUs?
It takes really long to start a training.

Could you update the binaries to be compatible with compute capability 9.0?

### Standalone code to reproduce the issue

```shell
start tensorboard
```

### Relevant log output

```shell
TensorFlow was not built with CUDA kernel binaries compatible with compute capability 9.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
```

**Comment by RocketRider** [comment]
I found this report. But for them it was not working. For me it is working but takes a long time to start: https://github.com/tensorflow/tensorflow/issues/60739

**Comment by sushreebarsa** [comment]
@RocketRider Could you please try to recompile TensorFlow with support for CUDA compute capability 9.0. To do this, you will need to install the CUDA toolkit and the cuDNN library. You can then recompile TensorFlow using the following command:
```
pip install tensorflow-gpu --upgrade --user
```
Thank you!

**Comment by jxu** [comment]
I had a similar issue but it was Tensorflow 2.17 and Compute Capability 5.0. 
Turns out just this version they dropped CUDA CC 5.0 support in the wheels. https://blog.tensorflow.org/2024/07/whats-new-in-tensorflow-217.html
