### ISSUE TITLE
TensorFlow 2.12.1 Not Recognizing GPU with CUDA 11 Installation

### ISSUE THREAD

**Issue by dilyar421** [tensorflow/tensorflow#62322]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.12.1

### Custom code

Yes

### OS platform and distribution

Windows 11  23H2

### Python version

3.10.2

### CUDA/cuDNN version

11.7.1

### GPU model and memory

RTX4060

### Current behavior?

I've installed TensorFlow-GPU version 2.12.1 and am trying to run it with a GPU on my Windows system. However, TensorFlow is unable to recognize the GPU. I have CUDA version 11 installed, and I'm unsure if this version is compatible or if there are additional steps required to make TensorFlow detect the GPU.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
print("TensorFlow Version:", tf.__version__)
print("Is GPU Available:", tf.config.list_physical_devices('GPU'))
```

### Relevant log output

```shell
TensorFlow Version: 2.12.1
Is GPU Available: []
```

**Comment by ourplan9000** [comment]
I really hope, tensorflow will bring back native GPU support on Windows.

**Comment by Walia20** [comment]
@dilyar421 , Do you have cuda showing in the kernel. Sometimes it the kernel which is causing the issue not the module itself
`import torch as pt
torch.cuda.is_available()`

if the above shows True then try to check for the CuDnn folder is in the right place
