### ISSUE TITLE
Model profile for inference

### ISSUE THREAD

**Issue by akote123** [tensorflow/tensorflow#62329]
Hi,
   For inference how we can get op level timings in tensorflow

Thanks

**Comment by Venkat6871** [comment]
Hi **@akote123** 
To get operation-level timings or execution time of specific operations within a graph, you can use the TensorFlow Profiler tool. I attached a [gist](https://colab.research.google.com/drive/1ZC2nStZP-GW68uv11MPJPknTAiZkRWCO?authuser=0#scrollTo=YUnR8iZhUp-v) for your reference.

Thank you!

**Comment by akote123** [comment]
@Venkat6871 , can please provide access to gist

**Comment by Venkat6871** [comment]
**@akote123**  Thanks for your response!
Could you check the gist now. I hope it will run.

Thank you!

**Comment by akote123** [comment]
Hi @Venkat6871 ,
     I tired with gist , but I am not able to see data in tensorboard,.
`tf.profiler.experimental.start('logs')
# Your TensorFlow operations here
# ...
# Stop profiling
    output = model.predict(encoded_input, verbose=False)[0]
    tf.profiler.experimental.stop()`

This way I tried. Please let me know if I need to do change

**Comment by Venkat6871** [comment]
Hi **@akote123**  Thanks for your response!
Actually I just send enable profiling. Here we need to follow some steps.
1.Enable profiling after this step.
2.Running Tensorboard:
After executing your Python script that includes the profiling code, you need to run TensorBoard to visualize the collected profiling data.
Open your terminal or command prompt and use the following command:
```
tensorboard --logdir=logs
```
3.Accessing Tensorboard:
 After you run the command, open a web browser and go to the address shown in the terminal where TensorBoard is running.

**Comment by akote123** [comment]
@Venkat6871 , I actually followed all the steps and when teansorboard is opened in web , In the profile tab when click for op level , the page is showing empty.

**Comment by akote123** [comment]
@Venkat6871 , is there any other way I can get profile data for inference

**Comment by akote123** [comment]
@SuryanarayanaY , For the above code I get tensorboard as attached
<img width="926" alt="tensorboard" src="https://github.com/tensorflow/tensorflow/assets/133775732/6aaf35fc-206e-43bd-992b-d60ebb44141a">

**Comment by SuryanarayanaY** [comment]
Hi @akote123 ,

Please refer to this [tutorial](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras) for profiling with tensorboard. Also check this tutorial to use [Tesorboard](https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks) in notebokks itself.

**Comment by tilakrayal** [comment]
@akote123,
Could you please try to update to the latest tensorflow v2.17 and also take a look at the official document for [reference](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras). I tried to execute the same document and check the data. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/48469d03f95ef3712563dd467b705d5e/tensorboard_profiling_keras.ipynb).

Thank you!
