### ISSUE TITLE
TF Lite in play services does not support version 1.13.0

### ISSUE THREAD

**Issue by navaronbracke** [tensorflow/tensorflow#62331]
I received an error report from a user that was using TensorFlow Lite through the `mobile_scanner` library.

As this library uses the most up-to-date version of `mlkit-barcode-scanning`, which has `TensorFlow Lite` as a dependency,
I cannot resolve the root cause of this issue.

From the changelogs I do not directly see which version of TensorFlow Lite supports version `1.13.0` in the Google Play services.
Thus I don't know if I should ask the maintainers of `play-services-mlkit-barcode-scanning` to update to the latest available version with a fix. (the last version of that dependency dates back a few months)

I can ask the user for their device / Google Play services version.

**System information**
- Android Device information (use `adb shell getprop ro.build.fingerprint`
  if possible): N/A 
- TensorFlow Lite in Play Services SDK version (found in `build.gradle`):
   - is a transitive dependency of `com.google.android.gms:play-services-mlkit-barcode-scanning` version 18.3.0
- Google Play Services version
  (`Settings` > `Apps` > `Google Play Services` > `App details`): N/A

**Standalone code to reproduce the issue**
```
import com.google.mlkit.vision.barcode.BarcodeScanning

class MobileScanner() {
  private var scanner = BarcodeScanning.getClient()
}
```

**Any other info / logs**
```
W/native (30072): W0000 00:00:1698456375.622782 32103 abi_method_util.h:33] not supported: TfLiteInterpreterGetTensor: TF Lite in Google Play services has stable ABI version 1.11.0 which is less than the required version 1.13.0.
```

**Comment by sushreebarsa** [comment]
@navaronbracke TensorFlow Lite in Google Play services does not support version 1.13.0 because it is still in preview. If you need to use TensorFlow Lite version 1.13.0, you can do so by downloading the TensorFlow Lite SDK directly from the TensorFlow website. You can then add the TensorFlow Lite SDK to your app as a dependency. Hope it helps?
Thank you!

**Comment by navaronbracke** [comment]
That explains it, thank you! Not sure if you know if the TensorFlow and the MLKit teams coordinate releases? Otherwise I'll wait for MLKit to update their Tensorflow usage.

**Comment by sushreebarsa** [comment]
@navaronbracke Yes, the TensorFlow and ML Kit teams coordinate releases. This helps to ensure that the two products are compatible and that developers can use them together seamlessly. For example, when TensorFlow releases a new version, the ML Kit team will update their product to be compatible with the new version. 
Thank you!

**Comment by navaronbracke** [comment]
That is enough information for me to inform users of the library. Thanks a lot!
