### ISSUE TITLE
Import tensorflow in ipython  Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by zsxgb** [tensorflow/tensorflow#6233]
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: zsx-All-Series
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:356] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.57  Mon Oct  3 20:37:01 PDT 2016
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: 367.57.0
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1080] LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1081] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libnvidia-fatbinaryloader.so.367.57: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally

**Comment by zsxgb** [comment]
A few weeks ago I installed and used successfully，But yesterday, when used, out of this problem。

**Comment by zsxgb** [comment]
I have two PC graphics card, I just looked at the NVIDA X SERVER Setting. Set the Do not use integrated graphics after just fine.

**Comment by martinwicke** [comment]
Is libcuda.so in your path? Your path is mentioned in the log:
LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:

**Comment by gunan** [comment]
@zsxgb based on your last comment, you seemed to have resolved the issue?

**Comment by DollarAkshay** [comment]
I have the exact same problem. Everything loads except `libcuda.so.1`

`Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/lib64`

I did notice that the file was missing in that path which is absurd cause i literally purged all Nvidia and CUDA stuff and did a fresh deb(network) install for Ubuntu 64-bit 16.04. I looked into `/usr/lib/x86_64-linux-gnu/` and found that `libcuda.so.1` is a symbolic link to a file.

I tried creating a symbolic link to that file in the `/usr/local/cuda/lib64` directory and tried to import tensorflow, it still dint work.

If someone who has CUDA 8.0 installed can tell us what `libcuda.so.1` links to I think this issue might get solved.

**Comment by gunan** [comment]
in my system, it is under:
`/usr/lib/x86_64-linux-gnu/` and it points to `libcuda.so.370.28`. `370.28` comes from my driver version.
When you use APT to install cuda, libcuda ends up here.

Also:
```
$ echo $LD_LIBRARY_PATH
/usr/local/cuda:/usr/local/cuda/lib64:
```

I see that your LD_LIBRARY_PATH has two paths that are exactly the same. maybe thats the problem?

**Comment by DollarAkshay** [comment]
Okay I purged everything and installed nvidia-375 (with DKMS) and the cuda deb(network install) .

Although I have 2 nvidia drivers now. The problem inst there.

**Comment by gunan** [comment]
Did you fix your LD_LIBRARY_PATH?
and do you mean the problem is not there?

**Comment by DollarAkshay** [comment]
Yes the problem is gone now. I really just reinstalled everything dint try changing the LD_LIBRARY_PATH. I guess the cuda installer took care of it.

This is what I see now :

`$ echo $LD_LIBRARY_PATH
:/usr/local/cuda/lib64
`

**Comment by quirkyshop** [comment]
@DollarAkshay 

it works for me, thanks!
