### ISSUE TITLE
Guidance on Using libtensorflowlite_flex.so with TensorFlow Lite C++ API

### ISSUE THREAD

**Issue by airchaoz** [tensorflow/tensorflow#62347]
I'm currently working with the TensorFlow Lite C++ API and have encountered some challenges regarding the usage of the flex delegate. I've successfully built the libtensorflowlite_flex.so library following the instructions provided on the official TensorFlow website. However, I am unclear on how to properly utilize this library, as I couldn't find any documentation on its usage in the guides.

Issue Summary:
After compiling libtensorflowlite_flex.so, I'm unsure how to integrate it into my existing TensorFlow Lite C++ project, which currently works well with the built-in operators. My aim is to leverage additional operators through the flex delegate, but my attempts to replace libtensorflowlite.so with libtensorflowlite_flex.so have led to compilation errors, leaving me uncertain about the correct approach or if there's something I'm missing.

Detailed Description:
I have successfully run TensorFlow Lite models using the C++ API and its built-in operators.
I need to use additional operators, for which I believe the flex delegate is required.
After building libtensorflowlite_flex.so, replacing libtensorflowlite.so with it in my project led to compilation failures.
I'm seeking guidance on the correct process to integrate the flex delegate into my project.
Environment:
OS: Ubuntu 20.04
TensorFlow Version: 2.6.5
I would greatly appreciate any documentation, examples, or guidance on how to properly use the flex delegate with the TensorFlow Lite C++ API. It would be immensely helpful for advancing my project and for others who might face similar challenges.

**Comment by fergushenderson** [comment]
What compilation errors do you get?

**Comment by airchaoz** [comment]
In fact, I've figured out how to use libtensorflowlite_flex.so on my own. Here's how I incorporated this library into my work. I used CMake to link the TensorFlow Lite library and compile my code. A simplified example is as follows:

```CMake
cmake_minimum_required(VERSION 3.11)

project(predict)
set(CMAKE_CXX_STANDARD 11)

include_directories(
  path/to/tensorflow/include
)

set(LINK_DIR path/to/tensorflowlite)
add_executable(predict src/main.cpp )

target_link_libraries(predict  ${LINK_DIR}/libflatbuffers.a)
target_link_libraries(predict ${LINK_DIR}/libtensorflowlite.so)
```
This code enables my code to link with TensorFlow Lite. However, it doesn't link with the Flex delegate. To use the Flex delegate, you need to first compile the libtensorflowlite_flex.so library file and place it in an appropriate location. Then, add the following code to the CMake file:
```CMake
target_link_libraries(predict
  -Wl,--no-as-needed
  ${LINK_DIR}/libtensorflowlite_flex.so
  -Wl,--as-needed
)
```
I'm not sure if there's a more elegant way to utilize the Flex delegate. If there is, I would be grateful to learn about it.

**Comment by airchaoz** [comment]
I recently repeated the above on Windwos and noticed a slight difference. The MSVC compiler does not have a compilation option to force links, and can only load the flex dll manually. I was inspired by the [issue](https://github.com/tensorflow/tensorflow/issues/62227)

```C++
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"
#include <Windows.h>


tflite::ops::builtin::BuiltinOpResolver resolver;
std::unique_ptr<tflite::Interpreter> interpreter;
tflite::InterpreterBuilder(*model, resolver)(&interpreter);

auto hdll = LoadLibrary("tensorflowlite_flex.dll");

auto TF_AcquireFlexDelegate = reinterpret_cast<tflite::Interpreter::TfLiteDelegatePtr (*)()>( GetProcAddress(hdll, 
                                                  "TF_AcquireFlexDelegate"));
if (TF_AcquireFlexDelegate == NULL) {
  std::cout << "TF_AcquireFlexDelegate couldn't be run" << std::endl;
}

if (!interpreter) {
  std::cerr << "Failed to construct interpreter." << std::endl;
}
auto delegate = TF_AcquireFlexDelegate();
if (interpreter->ModifyGraphWithDelegate(delegate.get()) != kTfLiteOk) {
  // error handle
}
```

**Comment by pkgoogle** [comment]
Hi @airchaoz, let's focus on one use case first as I see a lot of information flying around which isn't quite coherent. Do you want to focus on windows or Ubuntu 20.04? Are you using WSL in any way? Can you give us reproducible commands which I presume use the CMake file above to compile/run your project? and then share the errors which these commands produce.

Just for future reference, all this information is requested in our issues template: https://github.com/tensorflow/tensorflow/blob/master/ISSUE_TEMPLATE.md Please be sure to fill it out when creating an issue.

**Comment by GuoHuanyu** [comment]
I have utilized the C API provided in c_api_experimental.h to link the TensorflowLite Flex delegate. [](https://github.com/tensorflow/tensorflow/issues/62227)

**Comment by rishik1001** [comment]
> In fact, I've figured out how to use libtensorflowlite_flex.so on my own. Here's how I incorporated this library into my work. I used CMake to link the TensorFlow Lite library and compile my code. A simplified example is as follows:
> 
> ```cmake
> cmake_minimum_required(VERSION 3.11)
> 
> project(predict)
> set(CMAKE_CXX_STANDARD 11)
> 
> include_directories(
>   path/to/tensorflow/include
> )
> 
> set(LINK_DIR path/to/tensorflowlite)
> add_executable(predict src/main.cpp )
> 
> target_link_libraries(predict  ${LINK_DIR}/libflatbuffers.a)
> target_link_libraries(predict ${LINK_DIR}/libtensorflowlite.so)
> ```
> 
> This code enables my code to link with TensorFlow Lite. However, it doesn't link with the Flex delegate. To use the Flex delegate, you need to first compile the libtensorflowlite_flex.so library file and place it in an appropriate location. Then, add the following code to the CMake file:
> 
> ```cmake
> target_link_libraries(predict
>   -Wl,--no-as-needed
>   ${LINK_DIR}/libtensorflowlite_flex.so
>   -Wl,--as-needed
> )
> ```
> 
> I'm not sure if there's a more elegant way to utilize the Flex delegate. If there is, I would be grateful to learn about it.

What are the folders needed to be included in the set directories include ?
