### ISSUE TITLE
Does tflite support background running on my phone?

### ISSUE THREAD

**Issue by TANGATG** [tensorflow/tensorflow#62341]
**System information**
- Andriod Platform:
- TensorFlow installed from source:
- TensorFlow version is the latest:

**my issue**

For the tflite image processing application, the Android system usually uses a camera to collect data, for example, a demo of object detection, and uses a mobile phone camera to collect images, and an APP performs recognition. But I want to collect image data from a video on my phone and use my phone for object detection. What should I do? Does tflite support background running on my phone?

**Comment by Venkat6871** [comment]
Hi **@TANGATG** 
TensorFlow Lite itself doesn't control whether your application runs in the background on your phone. The background execution and multitasking capabilities are managed by the Android system itself, while TensorFlow Lite is responsible for running machine learning models on the device.
Thank you!

**Comment by TANGATG** [comment]
ok，thanks

**Comment by Venkat6871** [comment]
Hi **@TANGATG** ,
Thank you for your update, glad it's working fine for you, kindly move this issue to closed status as it is resolved.
Thank you!
