### ISSUE TITLE
Build tensorflow lite problem accessing https://gitlab.com/libeigen/eigen.git

### ISSUE THREAD

**Issue by juancresc** [tensorflow/tensorflow#62358]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.8

### Custom code

No

### OS platform and distribution

arm64

### Mobile device

macOS

### Bazel version

 6.1.0

### Current behavior?

CMake Warning at /Users/juan.crescente/Documents/rand/tensorflow-or/tflite_build/abseil-cpp/CMakeLists.txt:77 (message):
  A future Abseil release will default ABSL_PROPAGATE_CXX_STD to ON for CMake
  3.8 and up.  We recommend enabling this option to ensure your project still
  builds correctly.

-- Performing Test ABSL_INTERNAL_AT_LEAST_CXX17
-- Performing Test ABSL_INTERNAL_AT_LEAST_CXX17 - Success
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
The authenticity of host 'gitlab.com (172.65.251.78)' can't be established.
ED25519 key fingerprint is SHA256:eUXGGm1YGsMAS7vkcx6JOJdOGHPem5gQp4taiCfCLB8.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
[ 11%] Creating directories for 'eigen-populate'
[ 22%] Performing download step (git clone) for 'eigen-populate'
Cloning into 'eigen'...
Warning: Permanently added 'gitlab.com' (ED25519) to the list of known hosts.
git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into 'eigen'...
git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Cloning into 'eigen'...
git@gitlab.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
-- Had to git clone more than once: 3 times.
CMake Error at tmp/eigen-populate-gitclone.cmake:39 (message):
  Failed to clone repository: 'https://gitlab.com/libeigen/eigen.git'

make[2]: *** [/Users/juan.crescente/Documents/rand/tensorflow-or/tflite_build/src/eigen-populate-stamp/eigen-populate-download] Error 1
make[1]: *** [CMakeFiles/eigen-populate.dir/all] Error 2
make: *** [all] Error 2

CMake Error at /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/FetchContent.cmake:1604 (message):
  Build step for eigen failed: 2
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/FetchContent.cmake:1744:EVAL:2 (__FetchContent_directPopulate)
  /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/FetchContent.cmake:1744 (cmake_language)
  tools/cmake/modules/OverridableFetchContent.cmake:537 (FetchContent_Populate)
  tools/cmake/modules/eigen.cmake:39 (OverridableFetchContent_Populate)
  tools/cmake/modules/FindEigen3.cmake:18 (include)
  CMakeLists.txt:148 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Users/juan.crescente/Documents/rand/tensorflow-or/tflite_build/CMakeFiles/CMakeOutput.log".
See also "/Users/juan.crescente/Documents/rand/tensorflow-or/tflite_build/CMakeFiles/CMakeError.log".

### Standalone code to reproduce the issue

```shell
as described here

https://www.tensorflow.org/lite/guide/build_cmake

mkdir tflite_build
cd tflite_build
cmake ../tensorflow/lite
```

**Comment by juancresc** [comment]
additionally, from bazel
```

bazel build --config=elinux_aarch64 -c opt //tensorflow/lite/c:libtensorflowlite_c.so

INFO: Reading 'startup' options from /Users/juan.crescente/Documents/rand/tensorflow-or/.bazelrc: --windows_enable_symlinks
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=156
INFO: Reading rc options for 'build' from /Users/juan.crescente/Documents/rand/tensorflow-or/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users/juan.crescente/Documents/rand/tensorflow-or/.bazelrc:
  'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --features=-force_no_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Found applicable config definition build:short_logs in file /Users/juan.crescente/Documents/rand/tensorflow-or/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /Users/juan.crescente/Documents/rand/tensorflow-or/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:elinux_aarch64 in file /Users/juan.crescente/Documents/rand/tensorflow-or/.bazelrc: --config=elinux --cpu=aarch64
INFO: Found applicable config definition build:elinux in file /Users/juan.crescente/Documents/rand/tensorflow-or/.bazelrc: --crosstool_top=@local_config_embedded_arm//:toolchain --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
INFO: Found applicable config definition build:macos in file /Users/juan.crescente/Documents/rand/tensorflow-or/.bazelrc: --apple_platform_type=macos --copt=-DGRPC_BAZEL_BUILD --features=archive_param_file --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=no_tfrt
INFO: Found applicable config definition build:no_tfrt in file /Users/juan.crescente/Documents/rand/tensorflow-or/.bazelrc: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/ir,tensorflow/compiler/mlir/tfrt/ir/mlrt,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ifrt,tensorflow/compiler/mlir/tfrt/tests/mlrt,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/compiler/mlir/tfrt/transforms/mlrt,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/runtime_fallback/test,tensorflow/core/runtime_fallback/test/gpu,tensorflow/core/runtime_fallback/test/saved_model,tensorflow/core/runtime_fallback/test/testdata,tensorflow/core/tfrt/stubs,tensorflow/core/tfrt/tfrt_session,tensorflow/core/tfrt/mlrt,tensorflow/core/tfrt/mlrt/attribute,tensorflow/core/tfrt/mlrt/kernel,tensorflow/core/tfrt/mlrt/bytecode,tensorflow/core/tfrt/mlrt/interpreter,tensorflow/compiler/mlir/tfrt/translate/mlrt,tensorflow/compiler/mlir/tfrt/translate/mlrt/testdata,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils,tensorflow/core/tfrt/utils/debug,tensorflow/core/tfrt/saved_model/python,tensorflow/core/tfrt/graph_executor/python,tensorflow/core/tfrt/saved_model/utils
INFO: Build options --cpu and --crosstool_top have changed, discarding analysis cache.
INFO: Analyzed target //tensorflow/lite/c:libtensorflowlite_c.so (40 packages loaded, 11257 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_juan.crescente/31d150060e009750e7a00c4e6ef76e44/external/ruy/ruy/BUILD:900:11: Compiling ruy/ctx.cc failed: (Exit 126): aarch64-none-linux-gnu-gcc failed: error executing command (from target @ruy//ruy:ctx) /private/var/tmp/_bazel_juan.crescente/31d150060e009750e7a00c4e6ef76e44/external/aarch64_linux_toolchain/bin/aarch64-none-linux-gnu-gcc -fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections ... (remaining 54 arguments skipped)
/private/var/tmp/_bazel_juan.crescente/31d150060e009750e7a00c4e6ef76e44/external/aarch64_linux_toolchain/bin/aarch64-none-linux-gnu-gcc: /private/var/tmp/_bazel_juan.crescente/31d150060e009750e7a00c4e6ef76e44/external/aarch64_linux_toolchain/bin/aarch64-none-linux-gnu-gcc: cannot execute binary file
Target //tensorflow/lite/c:libtensorflowlite_c.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 145.417s, Critical Path: 5.59s
INFO: 276 processes: 236 internal, 40 local.
FAILED: Build did NOT complete successfully

```

**Comment by sushreebarsa** [comment]
@juancresc Could you please check if the Eigen library is installed on your system. Please make sure that the TensorFlow Lite build process is able to find the Eigen library.

Thank you!
