### ISSUE TITLE
no classess in AAR of tensorflow-lite-support in versions 0.3.+

### ISSUE THREAD

**Issue by MaciejJonczyk** [tensorflow/tensorflow#62365]
I wanted to use AAR file from Maven for version 0.4.4 
https://repo1.maven.org/maven2/org/tensorflow/tensorflow-lite-support/0.4.4/ 
but in Android it couldn't find class TensorBuffer. 

i checked AAR (changed to ZIP and unpacked and looked into Jar and found no class), also low volume of file <1KB made me suspicious. 

when I rolled back to 0.2.0-rc2 the code worked ok. this was the latest AAR file that was heavier than 1KB. 

maybe something wrong in the AAR deployer for this part of TensorFlowLite?

**Comment by fergushenderson** [comment]
It is intentional that tensorflow-lite-support is empty.
The Java classes have moved into tensorflow-lite-support-api which tensorflow-lite-support has a dependency on.
