### ISSUE TITLE
Embedding projector: clicking on points doesn't select them.

### ISSUE THREAD

**Issue by PAK90** [tensorflow/tensorflow#6237]
In Chrome, clicking on points (regardless of dataset, PCA or T-SNE, 2D or 3D) will not select them. Win10, Chrome Version 55.0.2883.87 m

**Comment by dsmilkov** [comment]
Hi @PAK90,

Having more information will help us debug your problem.

- Are you referring to the standalone website (projector.tensorflow.org) or the tab in TensorBoard?
- We used anti-aliasing but noticed that some users experienced the same problem as you, so we disabled it. If you saw the problem at projector.tensorflow.org, can you visit the website again and see if it works?
- How many points were you using?
- Is your zoom level 100%? If not, can you test if clicking on points at 100% zoom works?

Thanks for reporting this!

**Comment by PAK90** [comment]
This was using the standalone website, with the default provided MNIST dataset of 10000 points. After rebooting my pc it returned to working as normal. If I encounter it again I'll check zoom levels.

**Comment by dsmilkov** [comment]
Good to hear. I'll close the issue. If the problem appears again, feel free to reopen.
