### ISSUE TITLE
tflite_runtime v2.14.0 not inside apt installation repository

### ISSUE THREAD

**Issue by tribui141108** [tensorflow/tensorflow#62377]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.14.0

### Custom code

No

### OS platform and distribution

Raspbian OS (64-bit)

### Python version

3.11.2

### GPU model and memory

4GB RAM, 4 cores

### Current behavior?

tflite_runtime should be installed correctly on the Raspberry Pi 5. However, the it says the version only supports Python 3.10 or newer, since the latest version of it is 2.5.0. I expected it to install with version 2.14.0. libedgetpu1-std has also been successfully installed onto the Raspberry Pi.

### Standalone code to reproduce the issue

```shell
sudo apt install python3-tflite-runtime
```

### Relevant log output

```shell
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-tflite-runtime : Depends: python3 (< 3.10) but 3.11.2-1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by LakshmiKalaKadali** [comment]
@pkgoogle, Please look into this issue.
This issue is reproduced on Ubuntu 22.04 as well. Please find the [gist](https://colab.sandbox.google.com/gist/LakshmiKalaKadali/87143c7cbd6eafc272e664b1d2b315fb/-62377.ipynb#scrollTo=yKdq5HjwfvyD).

**Comment by pkgoogle** [comment]
Hi @tribui141108, can you try using pip instead?:

```
pip install tflite-runtime
Collecting tflite-runtime
  Obtaining dependency information for tflite-runtime from https://files.pythonhosted.org/packages/9e/1f/aade0d066bacbe697946ae21f0467a702d81adb939bb64515e9abebae9ed/tflite_runtime-2.14.0-cp310-cp310-manylinux2014_x86_64.whl.metadata
  Downloading tflite_runtime-2.14.0-cp310-cp310-manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: numpy>=1.23.2 in ./.local/lib/python3.10/site-packages (from tflite-runtime) (1.24.3)
Downloading tflite_runtime-2.14.0-cp310-cp310-manylinux2014_x86_64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 37.5 MB/s eta 0:00:00
Installing collected packages: tflite-runtime
Successfully installed tflite-runtime-2.14.0
```

**Comment by tribui141108** [comment]
I tried, but I don't think pip is allowed on a Raspberry Pi as it may break its Python Interface.
![image](https://github.com/tensorflow/tensorflow/assets/78627269/955c88f6-c3c5-4886-85a9-7420db90137a)
Normally, I think installing tflite-runtime using apt package is possible on a Raspberry Pi 4. Raspberry Pi 5 has new hardware features, so I think that is the reason it doesn't work on my Raspberry Pi 5.

**Comment by tribui141108** [comment]
Yes, I'm following the instructions to install the Coral USB Accelerator on my Raspberry Pi.
https://coral.ai/docs/accelerator/get-started/
I'm currently trying to get pycoral installed, which requires tflite_runtime to be installed as well.

I've also tried running in a python virtual environment, but normally the package would not detect pycoral there.

**Comment by pkgoogle** [comment]
Hi @tribui141108, I went through that document (not in full detail) but I couldn't find where it suggests installing that python package? It's possible I missed it, but if you can point me to where it suggests installing python3-tflite-runtime? I primarily see it suggesting to install python3-pycoral

Also I see an explicit Note here:

```
Note: PyCoral currently supports Python 3.6 through 3.9. If your default version is something else, we suggest you [install Python 3.9 with pyenv](https://realpython.com/intro-to-pyenv/).
```

That suggests to me you should probably use python=3.9

**Comment by tribui141108** [comment]
I guess I have to wait until it supports python 3.10. Installing python 3.9 requires me to uninstall python 3.10, which will immediately break raspbian os since raspbian os is built on a python interface.

**Comment by pkgoogle** [comment]
No worries, @tribui141108, if you have have no other open items regarding this, can you please close as completed? Thanks.
