### ISSUE TITLE
windows build tensorflowlite for android error

### ISSUE THREAD

**Issue by leizhu1989** [tensorflow/tensorflow#62388]
**System information**
- TensorFlow Lite version: 2.12
- OS: windows11
- build tools: bazel 5.3.0
- build command: bazel build --cxxopt='--std=c++11' //tensorflow/lite/java:tensorflowlite --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a
- android NDK/SDK has installed

**Standalone code to reproduce the issue**
when I build tensorflow-lite.so for android, I cause a error:
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/10939d1d580b9d3c9c2f3539c6bdb39f408179c0.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: C:/users/zhulei/_bazel_zhulei/qotdwtts/external/local_jdk/BUILD.bazel:2:10: in fail_rule rule @local_jdk//:jdk:
Traceback (most recent call last):
        File "C:/users/zhulei/_bazel_zhulei/qotdwtts/external/bazel_tools/tools/jdk/fail_rule.bzl", line 19, column 13, in _fail_rule_impl
                fail("%s %s" % (ctx.attr.header, ctx.attr.message))
Error in fail: Auto-Configuration Error: Cannot find Java binary bin/java.exe in C:/users/zhulei/_bazel_zhulei/install/40e9c076fd7053192c88f0d437fc6512/embedded_tools/tools/jdk/nosystemjdk; either correct your JAVA_HOME, PATH or specify Java from remote repository (e.g. --java_runtime_version=remotejdk_11
ERROR: C:/users/zhulei/_bazel_zhulei/qotdwtts/external/local_jdk/BUILD.bazel:2:10: Analysis of target '@local_jdk//:jdk' failed
ERROR: C:/users/zhulei/_bazel_zhulei/qotdwtts/external/bazel_tools/tools/jdk/BUILD:29:19: errors encountered resolving toolchains for @bazel_tools//tools/jdk:current_java_runtime
WARNING: Download from https://golang.org/dl/?mode=json&include=all failed: class java.io.IOException connect timed out
ERROR: Analysis of target '//tensorflow/lite/java:tensorflowlite' failed; build aborted:
INFO: Elapsed time: 1.517s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 1 target configured)

It sames could not find https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/10939d1d580b9d3c9c2f3539c6bdb39f408179c0.tar.gz , what should I do to sovel this problem,thank you !

**Comment by sushreebarsa** [comment]
@leizhu1989 Could you please make sure that the JDK is installed and that it is installed in the location that is specified in the @local_jdk//:jdk target. You can check the location of the JDK by running the following command:
```
java -version
```

Thank you!

**Comment by leizhu1989** [comment]
@sushreebarsa thank you for your reply ! when I add --java_runtime_version=remotejdk_11 in build command, it has no that error,but also has a error like:

INFO: Found applicable config definition build:short_logs in file d:\project\deeplearning\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file d:\project\deeplearning\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file d:\project\deeplearning\tensorflow\.bazelrc: --copt=/W0 --host_copt=/W0 --copt=/Zc:__cplusplus --host_copt=/Zc:__cplusplus --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --features=compiler_param_file --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --cxxopt=/std:c++17 --host_cxxopt=/std:c++17 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/Zc:preprocessor --host_copt=/Zc:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --features=compiler_param_file --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file d:\project\deeplearning\tensorflow\.bazelrc: --define framework_shared_object=false --define tsl_protobuf_header_only=false --experimental_link_static_libraries_once=false
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/659147817805d17c7be2d60bd7bbca7e780f9c82.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Analyzed target //tensorflow/lite/java:tensorflowlite (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: D:/project/deeplearning/tensorflow/tensorflow/lite/nnapi/BUILD:31:11: Compiling tensorflow/lite/nnapi/nnapi_implementation.cc failed: (Exit 1): clang failed: error executing command
  cd /d C:/users/zhulei/_bazel_zhulei/qotdwtts/execroot/org_tensorflow
  SET ANDROID_BUILD_TOOLS_VERSION=34.0.0
    SET ANDROID_NDK_API_LEVEL=26
    SET ANDROID_NDK_HOME=D:/project/android-ndk-r20b-windows-x86_64
    SET ANDROID_SDK_API_LEVEL=34
    SET ANDROID_SDK_HOME=D:/Android/Sdk
    SET PATH=D:\project\install_soft\msys64\usr\bin;D:\project\install_soft\msys64\bin;C:\WINDOWS;C:\WINDOWS\System32;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\libnvvp;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NetSarang\Xftp 7\;C:\Program Files (x86)\PuTTY\;C:\Users\zhulei\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;E:\project\cmake-3.20.0-rc3-windows-x86_64\bin;C:\project\platform-tools_r33.0.3-windows\platform-tools;E:\project\protobuf-3.4.0-gmock\install\protobuf\bin;C:\Program Files\IDM Computer Solutions\UltraEdit;D:\project\TensorRT-8.4.2.4.Windows10.x86_64.cuda-11.6.cudnn8.4\lib;C:\Program Files\NVIDIA Corporation\Nsight Compute 2021.2.2\;D:\project\Elasticsearch\elasticsearch-8.1.2\jdk;D:\project\Elasticsearch\node-v17.9.1-win-x64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NetSarang\Xshell 7\;D:\project\cudnn-windows-x86_64-8.4.0.27_cuda11.6-archive\bin;D:\project\install_soft;D:\project\install_soft\msys64\usr\bin;C:\Users\zhulei\AppData\Local\Microsoft\WindowsApps;;C:\Users\zhulei\AppData\Local\Programs\Microsoft VS Code\bin
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/ProgramData/Anaconda3/python.exe
    SET PYTHON_LIB_PATH=C:/ProgramData/Anaconda3/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TF2_BEHAVIOR=1
  external\androidndk\ndk\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -D__ANDROID_API__=26 -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -target armv7-none-linux-androideabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -fpic -no-canonical-prefixes -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -funwind-tables -fstack-protector-strong -fno-addrsig -Werror=return-type -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=implicit-function-declaration -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/nnapi/_objs/nnapi_implementation/nnapi_implementation.pic.d -frandom-seed=bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/nnapi/_objs/nnapi_implementation/nnapi_implementation.pic.o -fPIC -iquote . -iquote bazel-out/armeabi-v7a-opt/bin /W0 /Zc:__cplusplus /D_USE_MATH_DEFINES /d2ReducedOptimizeHugeFunctions -DWIN32_LEAN_AND_MEAN -DNOGDI /Zc:preprocessor /d2ReducedOptimizeHugeFunctions /std:c++17 '--std=c++11' --sysroot=external/androidndk/ndk/platforms/android-26/arch-arm -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem external/androidndk/ndk/sources/android/support/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c tensorflow/lite/nnapi/nnapi_implementation.cc -o bazel-out/armeabi-v7a-opt/bin/tensorflow/lite/nnapi/_objs/nnapi_implementation/nnapi_implementation.pic.o
# Configuration: 3dcec145ccee737eeff39455689d10f429749c273e882c1f289971a54a4328c4
# Execution platform: @local_execution_config_platform//:platform
clang: error: no such file or directory: '/W0'
clang: error: no such file or directory: '/Zc:__cplusplus'
clang: error: no such file or directory: '/D_USE_MATH_DEFINES'
clang: error: no such file or directory: '/d2ReducedOptimizeHugeFunctions'
clang: error: no such file or directory: '/Zc:preprocessor'
clang: error: no such file or directory: '/d2ReducedOptimizeHugeFunctions'
clang: error: no such file or directory: '/std:c++17'
clang: error: no such file or directory: ''--std=c++11''
Target //tensorflow/lite/java:tensorflowlite failed to build
INFO: Elapsed time: 0.638s, Critical Path: 0.39s
INFO: 21 processes: 21 internal.
FAILED: Build did NOT complete successfully

build command :bazel build --cxxopt='--std=c++11' //tensorflow/lite/java:tensorflowlite --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --cpu=armeabi-v7a --java_runtime_version=remotejdk_11

**Comment by leizhu1989** [comment]
@sushreebarsa hello, when I change command : bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain //tensorflow/lite/java:tensorflow-lite --java_runtime_version=remotejdk_11, the error change to:

INFO: Found applicable config definition build:short_logs in file d:\project\deeplearning\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file d:\project\deeplearning\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file d:\project\deeplearning\tensorflow\.bazelrc: --copt=/W0 --host_copt=/W0 --copt=/Zc:__cplusplus --host_copt=/Zc:__cplusplus --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --features=compiler_param_file --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --cxxopt=/std:c++17 --host_cxxopt=/std:c++17 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/Zc:preprocessor --host_copt=/Zc:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --features=compiler_param_file --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file d:\project\deeplearning\tensorflow\.bazelrc: --define framework_shared_object=false --define tsl_protobuf_header_only=false --experimental_link_static_libraries_once=false
INFO: Build options --cpu and --fat_apk_cpu have changed, discarding analysis cache.
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/659147817805d17c7be2d60bd7bbca7e780f9c82.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Analyzed target //tensorflow/lite/java:tensorflow-lite (3 packages loaded, 11363 targets configured).
INFO: Found 1 target...
ERROR: C:/users/zhulei/_bazel_zhulei/qotdwtts/external/androidsdk/BUILD.bazel:13:25: Extracting interface @androidsdk//:dx_jar_import failed: missing input file 'external/androidsdk/build-tools/34.0.0/lib/dx.jar', owner: '@androidsdk//:build-tools/34.0.0/lib/dx.jar'
ERROR: C:/users/zhulei/_bazel_zhulei/qotdwtts/external/androidsdk/BUILD.bazel:13:25: Extracting interface @androidsdk//:dx_jar_import failed: 1 input file(s) do not exist
Target //tensorflow/lite/java:tensorflow-lite failed to build
ERROR: C:/users/zhulei/_bazel_zhulei/qotdwtts/external/androidsdk/BUILD.bazel:13:25 Extracting interface @androidsdk//:dx_jar_import failed: 1 input file(s) do not exist
INFO: Elapsed time: 7.747s, Critical Path: 6.53s
INFO: 205 processes: 183 internal, 22 local.
FAILED: Build did NOT complete successfully

it sames jdk/android sdk/android ndk version mismatching ,my version:
 jdk: java_runtime_version=remotejdk_11
SET ANDROID_BUILD_TOOLS_VERSION=34.0.0
    SET ANDROID_NDK_API_LEVEL=26
    SET ANDROID_NDK_HOME=D:/project/android-ndk-r20b-windows-x86_64
    SET ANDROID_SDK_API_LEVEL=34
    SET ANDROID_SDK_HOME=D:/Android/Sdk

is this ok? thank you

**Comment by leizhu1989** [comment]
@sushreebarsa  when I change android sdk ,the same error:
bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain //tensorflow/lite/java:tensorflow-lite --java_runtime_version=remotejdk_11

INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=151
INFO: Reading rc options for 'build' from d:\project\deeplearning\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/ProgramData/Anaconda3/python.exe
INFO: Reading rc options for 'build' from d:\project\deeplearning\tensorflow\.bazelrc:
  'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'build' from d:\project\deeplearning\tensorflow\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=C:/ProgramData/Anaconda3/python.exe --action_env PYTHON_LIB_PATH=C:/ProgramData/Anaconda3/lib/site-packages --python_path=C:/ProgramData/Anaconda3/python.exe --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --action_env ANDROID_NDK_HOME=D:/project/android-ndk-r20b-windows-x86_64 --action_env ANDROID_NDK_API_LEVEL=26 --action_env ANDROID_BUILD_TOOLS_VERSION=31.0.0 --action_env ANDROID_SDK_API_LEVEL=31 --action_env ANDROID_SDK_HOME=D:/Android/Sdk
INFO: Reading rc options for 'build' from d:\project\deeplearning\tensorflow\.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file d:\project\deeplearning\tensorflow\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file d:\project\deeplearning\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file d:\project\deeplearning\tensorflow\.bazelrc: --copt=/W0 --host_copt=/W0 --copt=/Zc:__cplusplus --host_copt=/Zc:__cplusplus --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --features=compiler_param_file --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --cxxopt=/std:c++17 --host_cxxopt=/std:c++17 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/Zc:preprocessor --host_copt=/Zc:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --features=compiler_param_file --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file d:\project\deeplearning\tensorflow\.bazelrc: --define framework_shared_object=false --define tsl_protobuf_header_only=false --experimental_link_static_libraries_once=false
INFO: Analyzed target //tensorflow/lite/java:tensorflow-lite (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/users/zhulei/_bazel_zhulei/qotdwtts/external/ruy/ruy/BUILD:506:11: Compiling ruy/apply_multiplier.cc failed: (Exit 1): clang failed: error executing command
  cd /d C:/users/zhulei/_bazel_zhulei/qotdwtts/execroot/org_tensorflow
  SET ANDROID_BUILD_TOOLS_VERSION=31.0.0
    SET ANDROID_NDK_API_LEVEL=26
    SET ANDROID_NDK_HOME=D:/project/android-ndk-r20b-windows-x86_64
    SET ANDROID_SDK_API_LEVEL=31
    SET ANDROID_SDK_HOME=D:/Android/Sdk
    SET PATH=D:\project\install_soft\msys64\usr\bin;D:\project\install_soft\msys64\bin;C:\WINDOWS;C:\WINDOWS\System32;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\libnvvp;C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\libnvvp;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NetSarang\Xftp 7\;C:\Program Files (x86)\PuTTY\;C:\Users\zhulei\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;E:\project\cmake-3.20.0-rc3-windows-x86_64\bin;C:\project\platform-tools_r33.0.3-windows\platform-tools;E:\project\protobuf-3.4.0-gmock\install\protobuf\bin;C:\Program Files\IDM Computer Solutions\UltraEdit;D:\project\TensorRT-8.4.2.4.Windows10.x86_64.cuda-11.6.cudnn8.4\lib;C:\Program Files\NVIDIA Corporation\Nsight Compute 2021.2.2\;D:\project\Elasticsearch\elasticsearch-8.1.2\jdk;D:\project\Elasticsearch\node-v17.9.1-win-x64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NetSarang\Xshell 7\;D:\project\cudnn-windows-x86_64-8.4.0.27_cuda11.6-archive\bin;D:\project\install_soft;D:\project\install_soft\msys64\usr\bin;C:\Users\zhulei\AppData\Local\Microsoft\WindowsApps;;C:\Users\zhulei\AppData\Local\Programs\Microsoft VS Code\bin
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/ProgramData/Anaconda3/python.exe
    SET PYTHON_LIB_PATH=C:/ProgramData/Anaconda3/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TF2_BEHAVIOR=1
  external\androidndk\ndk\toolchains\llvm\prebuilt\windows-x86_64\bin\clang -D__ANDROID_API__=26 -isystemexternal/androidndk/ndk/sysroot/usr/include/arm-linux-androideabi -target armv7-none-linux-androideabi -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -gcc-toolchain external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 -fpic -no-canonical-prefixes -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -funwind-tables -fstack-protector-strong -fno-addrsig -Werror=return-type -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=implicit-function-declaration -mthumb -Os -g -DNDEBUG -MD -MF bazel-out/android-armeabi-v7a-opt/bin/external/ruy/ruy/_objs/apply_multiplier/apply_multiplier.pic.d -frandom-seed=bazel-out/android-armeabi-v7a-opt/bin/external/ruy/ruy/_objs/apply_multiplier/apply_multiplier.pic.o -fPIC -iquote external/ruy -iquote bazel-out/android-armeabi-v7a-opt/bin/external/ruy /W0 /Zc:__cplusplus /D_USE_MATH_DEFINES /d2ReducedOptimizeHugeFunctions -DWIN32_LEAN_AND_MEAN -DNOGDI /Zc:preprocessor /d2ReducedOptimizeHugeFunctions /std:c++17 -mfpu=neon -O3 --sysroot=external/androidndk/ndk/platforms/android-26/arch-arm -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++/include -isystem external/androidndk/ndk/sources/cxx-stl/llvm-libc++abi/include -isystem external/androidndk/ndk/sources/android/support/include -isystemexternal/androidndk/ndk/sysroot/usr/include -c external/ruy/ruy/apply_multiplier.cc -o bazel-out/android-armeabi-v7a-opt/bin/external/ruy/ruy/_objs/apply_multiplier/apply_multiplier.pic.o
# Configuration: 9856a2746bfd1bed9df0387b5ffea58adc26b7231a0cfcd0f3bbb96c1e0074f4
# Execution platform: @local_execution_config_platform//:platform
clang: error: no such file or directory: '/W0'
clang: error: no such file or directory: '/Zc:__cplusplus'
clang: error: no such file or directory: '/D_USE_MATH_DEFINES'
clang: error: no such file or directory: '/d2ReducedOptimizeHugeFunctions'
clang: error: no such file or directory: '/Zc:preprocessor'
clang: error: no such file or directory: '/d2ReducedOptimizeHugeFunctions'
clang: error: no such file or directory: '/std:c++17'
Target //tensorflow/lite/java:tensorflow-lite failed to build
INFO: Elapsed time: 1.077s, Critical Path: 0.35s
INFO: 79 processes: 79 internal.
FAILED: Build did NOT complete successfully

is this error because:"ERROR: C:/users/zhulei/_bazel_zhulei/qotdwtts/external/ruy/ruy/BUILD:506:11: Compiling ruy/apply_multiplier.cc failed: (Exit 1): clang failed: error executing command
  cd /d C:/users/zhulei/_bazel_zhulei/qotdwtts/execroot/org_tensorflow"? but, I can not know how to sovel this problem?

**Comment by LakshmiKalaKadali** [comment]
Hi @pkgoogle , please look into the issue.

Thank You

**Comment by pkgoogle** [comment]
Hi @leizhu1989, help me understand your goal here... is there any reason you're not following this guide? https://www.tensorflow.org/lite/android/lite_build, if not can you please follow that guide and let me know if it works for you?
