### ISSUE TITLE
Understand thread_sync_cost and framework_cost calculation in mkl_heuristics.h

### ISSUE THREAD

**Issue by akote123** [tensorflow/tensorflow#62382]
Hi,
    I am trying to understand the mkl_heuristcs from tensorflow/core/util/mkl_heuristics.h .In rewrite_thresholds list the const values are given to framework cost and thread_sync_cost as :
    {"Conv2D", 0x41, 0xd40, {0.9349, 22.603}},
    {"_FusedConv2D", 0x41, 0xd40, {0.9349, 22.603}},
    {"FusedBatchNormV3", 0x41, 0xd40, {0.3223, -0.8822}},
    {"Sigmoid", 0x41, 0xd40, {0.0, 0.064736}}
 
Here how these constants are being calculated or taken into consider for rewrite thresholds?

**Comment by Venkat6871** [comment]
Hi **@akote123 **,
Can you add templates.
Thank you!

**Comment by akote123** [comment]
@Venkat6871 , Iam here going through the latest Tensorflow code base in github , in tensorflow/core/util/mkl_heuristics.h file and trying to understand the heristic concepts . Is there any documentation available on how the constants are taken in to consider in this file.

Thanks

**Comment by akote123** [comment]
Hi @cfRod ,
         Can you please help me in understanding these concepts , like how the threshold value is been decided for matmul and above case.

Thank You

**Comment by Venkat6871** [comment]
Hi **@akote123** ,

The constants in tensorflow/core/util/mkl_heuristics.h are used to tune the performance of the Intel Math Kernel Library (MKL) when used with TensorFlow. These constants are based on a variety of factors, such as the type of operation being performed, the size of the input and output tensors, and the available hardware resources.


Thank you!

**Comment by akote123** [comment]
Hi @Venkat6871 ,
    Thank you . Actually this is not a issue or bug .Here I was going through the code and I wanted to understand the how the value is being chosen like is there any formula to get this

**Comment by Venkat6871** [comment]
Hi **@akote123** ,
This is not a bug or feature request, for any further queries you may open this issue in tf discussion [forum](https://discuss.tensorflow.org/) as there is a larger community there. 

Thank you!
