### ISSUE TITLE
tensorflow.org/versions points to latest version for 2.11 onwards

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#62389]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.11+

### Custom code

No

### OS platform and distribution

All

### Mobile device

All

### Python version

All

### Current behavior?

In https://tensorflow.org/versions, the links to versions 2.11, 2.12, 2.13, and 2.14 all point to the latest docs (i.e.,  https://www.tensorflow.org/api_docs/python/tf) instead of pointing to https://www.tensorflow.org/versions/r2.11/api_docs/python/tf (or to a similar URL for 2.12, and 2.13).

If the script that generates this page is available on github, I'm happy to fix it, but I just can't find it.
Note that the links to the release notes are okay.

### Standalone code to reproduce the issue

```shell
Step 1: go to https://tensorflow.org/versions
Step 2: click on r2.11, r2.12, or r2.13. All of these lead to the wrong page. Once 2.15 is released, I'm guessing r2.14 will also be wrong (it will point to the latest docs).
```

### Relevant log output

```shell
N/A
```

**Comment by SuryanarayanaY** [comment]
Hi @ageron ,

I have cross checked and acknowledged the issue. The script seems not public. I will raise an internal PR to fix this. Thanks for reporting.

**Comment by tilakrayal** [comment]
@ageron,
There was an internal issue raised for tracking the same issue and it got resolved now. Could you please try to access any Keras in the Tensorflow.org page, now it is able to re-direct to correct source code. Please check and confirm if it is working in your case.

https://www.tensorflow.org/api_docs/python/tf    ------ > click on r2.11 or r2.12------>it is redirecting the right page.

https://www.tensorflow.org/api_docs/python/tf/keras/Model
https://github.com/keras-team/keras/blob/v3.3.3/keras/src/models/model.py#L32-L548

Thank you!
