### ISSUE TITLE
overflow happens in tf.image.adjust_gamma when gamma is very small

### ISSUE THREAD

**Issue by drewshark** [tensorflow/tensorflow#62393]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.14.0

### Custom code

Yes

### Current behavior?

When `gamma` is a very small value (e.g., 0.00001 or 0) and input tensor is a positive integer tensor, tf.image.adjust_gamma might output largely negative value. Specifically, if gamma=0 and gain=2, the expected output should be 2 according to the formula: `Out = gain * In**gamma`, but the current result is -9223372036854775808.

It seems that the overflow issue happens when executing this code:
https://github.com/tensorflow/tensorflow/blob/9fa48d09da86703782f68c523327ad57c2cca8ed/tensorflow/python/ops/image_ops_impl.py#L2372

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
image = tf.constant(9, dtype='int64')
gamma = 0
gain = 2
out = tf.image.adjust_gamma(image,gamma,gain)
print(out)
```

### Relevant log output

```shell
tf.Tensor(-9223372036854775808, shape=(), dtype=int64)
```

**Comment by hiteshhhh007** [comment]
Hey @drewshark! can I work on this issue?

**Comment by sushreebarsa** [comment]
@drewshark I was able to replicate this issue. As a workaround could you try to use a smaller value of gamma or the algorithm which doesn't include floating point numbers. Please let us know?
Thank you!

**Comment by drewshark** [comment]
Hi @sushreebarsa , sure I will use floating tensor instead.

**Comment by sushreebarsa** [comment]
@drewshark Thank you for your response here!
Could you please let us know if we can move this issue to closed status if the workaround worked for you ?
Thank you!

**Comment by drewshark** [comment]
Sure, I am closing this issue.
