### ISSUE TITLE
tf.keras.__version__ is undefined since TF 2.14.0

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#62398]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

v2.14.0-rc1-21-g4dacf3f368e 2.14.0

### Custom code

No

### Mobile device

N/A

### Python version

3.10

### Current behavior?

`tf.keras.__version__` is undefined.

It was defined since TensorFlow 1.9, and until 2.13, but for some reason it looks like it was removed in TF 2.14.
This change was not listed in the release notes. Not sure `tf.keras.__version__` was part of the official public API, but a quick search on the Web and github shows that it was heavily used.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
print(tf.keras.__version__)
```

### Relevant log output

```shell
In [2]: tf.keras.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 1
----> 1 tf.keras.__version__

File ~/opt/miniconda3/envs/homl3/lib/python3.10/site-packages/tensorflow/python/util/lazy_loader.py:67, in LazyLoader.__getattr__(self, item)
     65 def __getattr__(self, item):
     66   module = self._load()
---> 67   return getattr(module, item)

AttributeError: module 'keras.api._v2.keras' has no attribute '__version__'
```
```

**Comment by sushreebarsa** [comment]
Hello, @ageron! 
If you are using the latest version of TF then please use the following code;

To print the Keras version;
```
import keras

print(keras.__version__)

```
To print the TF version;

```
import tensorflow as tf

print(tf.__version__)

```
Please have a look at this [gist](https://colab.research.google.com/gist/sushreebarsa/c724800e284e5bc15d03fd6f25c9300e/62398.ipynb) for reference!
Thank you!

**Comment by mshajarrazip** [comment]
On 2.15.0, the same error still persists with `keras.__version__`

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[8], [line 4](vscode-notebook-cell:?execution_count=8&line=4)
      [1](vscode-notebook-cell:?execution_count=8&line=1) import tensorflow as tf
      [2](vscode-notebook-cell:?execution_count=8&line=2) from tensorflow import keras
----> [4](vscode-notebook-cell:?execution_count=8&line=4) tf.__version__, keras.__version__

AttributeError: module 'keras.api._v2.keras' has no attribute '__version__'
```

**Comment by mihaimaruseac** [comment]
Keras moved from being a library of TF (so import TF and you get Keras) to being a library that works with TF (and JAX, and PyTorch) as backend (so you import _both_ Keras and TF).

To not break existing code, some `tf.keras` symbols are still in place, but not all of them
