### ISSUE TITLE
TfLite 2.14 fails to build with Visual Studio with AVX2 compiler flag

### ISSUE THREAD

**Issue by misterBart** [tensorflow/tensorflow#62392]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.14

### Custom code

No

### OS platform and distribution

Windows 10 Enterprise

### GCC/compiler version

Visual Studio 2019 and 2022

### Current behavior?

Building TfLite 2.14 yields the following build error with Visual Studio 2022 (and 2019) when the AVX2 compiler flag is enabled:
```
C:\Users\bartp\source\TfLite2.14\tflite_x64_release\abseil-cpp\absl\crc\internal\crc_memcpy_x86_64.cc(391,11): error C7555: use of designated initializers requires at least '/std:c++20' [C:\Users\bartp\source\TfLite2.14\tflite_x64_release\_deps\abseil-cpp-build\absl\crc\absl_crc32c.vcxproj]
C:\Users\bartp\source\TfLite2.14\tflite_x64_release\abseil-cpp\absl\crc\internal\crc_memcpy_x86_64.cc(403,11): error C7555: use of designated initializers requires at least '/std:c++20' [C:\Users\bartp\source\TfLite2.14\tflite_x64_release\_deps\abseil-cpp-build\absl\crc\absl_crc32c.vcxproj]
C:\Users\bartp\source\TfLite2.14\tflite_x64_release\abseil-cpp\absl\crc\internal\crc_memcpy_x86_64.cc(409,11): error C7555: use of designated initializers requires at least '/std:c++20' [C:\Users\bartp\source\TfLite2.14\tflite_x64_release\_deps\abseil-cpp-build\absl\crc\absl_crc32c.vcxproj]
C:\Users\bartp\source\TfLite2.14\tflite_x64_release\abseil-cpp\absl\crc\internal\crc_memcpy_x86_64.cc(413,15): error C7555: use of designated initializers requires at least '/std:c++20' [C:\Users\bartp\source\TfLite2.14\tflite_x64_release\_deps\abseil-cpp-build\absl\crc\absl_crc32c.vcxproj]

```
This Abseil issue has been solved according to https://github.com/abseil/abseil-cpp/issues/1504
Seemingly TfLite 2.14 uses an unpatched version of Abseil.

### Standalone code to reproduce the issue

```shell
In Command Prompt execute:
git clone --single-branch --branch r2.14 https://github.com/tensorflow/tensorflow tensorflow_src
mkdir tflite_x64_release
cd tflite_x64_release
cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_C_FLAGS_INIT="/arch:AVX2" -DCMAKE_CXX_FLAGS_INIT="/arch:AVX2" ..\tensorflow_src\tensorflow\lite
cmake --build . -j 8 --config release
```

**Comment by pkgoogle** [comment]
Hi @misterBart,

I didn't get the error messages with nightly:

```
git clone --single-branch --branch nightly https://github.com/tensorflow/tensorflow tensorflow_src
mkdir tflite_x64_release
cd tflite_x64_release
cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_C_FLAGS_INIT="/arch:AVX2" -DCMAKE_CXX_FLAGS_INIT="/arch:AVX2" ..\tensorflow_src\tensorflow\lite
cmake --build . -j 8 --config release
```

seems like abseil is updated after 2.14 release, can you use nightly to progress?

**Comment by misterBart** [comment]
You're right, I do not receive the reported error with the nightly branch. 

I am receiving a different error now though, haha:
`C:\Users\bartp\source\TfNightly-Attempt2\tensorflow_src\tensorflow/lite/kernels/internal/optimized/fully_connected_4bit.h(21,10): fatal  error C1083: Cannot open include file: 'sys/mman.h': No such file or directory [C:\Users\bartp\source\TfNightly-Attempt2\tflite_x64_release\tensorflow-lite.vcxproj]`
But that is different issue, so I will close this issue. 

Thanks for helping out.
