### ISSUE TITLE
what is op 'Switch' in RNN?

### ISSUE THREAD

**Issue by LiangKlausQiu** [tensorflow/tensorflow#6240]
I build a two-layer RNN (GRU) network using tf.nn.dynamic_rnn with argument sequence_length. Then the graph contains an op 'Switch' which I haven't seen before. 
 919 node {
 920   name: "Test/Model/RNN/RNN/Assert/AssertGuard/Switch"
 921   op: "Switch"
 922   input: "Test/Model/RNN/RNN/All"
 923   input: "Test/Model/RNN/RNN/All"
 924   attr {
 925     key: "T"
 926     value {
 927       type: DT_BOOL
 928     }
 929   }

I need to do inference in android and it complains this op is not registered in kernel files. I wonder what it is and there should be a python wrap or .cc file to implement this I guess.

**Comment by LiangKlausQiu** [comment]
@michaelisard Do you know what is it in .cc file? Thank you so much!

**Comment by LiangKlausQiu** [comment]
I guess it's the condition argument in assert op?

**Comment by LiangKlausQiu** [comment]
OK, it is in control_flow_ops and it's under comment.

**Comment by michaelisard** [comment]
Do you have more questions about this or should I close the issue?

**Comment by LiangKlausQiu** [comment]
No, thanks! I will close this.
