### ISSUE TITLE
TensorFlow Lite in Play Services issue: Cannot initialize interpreter: Error loading TFLite native library

### ISSUE THREAD

**Issue by jahonn** [tensorflow/tensorflow#62407]
**System information**
- Android Device information (use `adb shell getprop ro.build.fingerprint`
  if possible): Redmi/thunder_global/thunder:13/TP1A.220624.014/V0.0.0.0.XXXXXXX:user/test-keys
- TensorFlow Lite in Play Services SDK version (found in `build.gradle`):com.google.android.gms:play-services-tflite-java:16.1.0
- Google Play Services version
  (`Settings` > `Apps` > `Google Play Services` > `App details`):23.43.13(190400-577232161)

**Standalone code to reproduce the issue**
`            
            Task<Void> initializeTask = TfLite.initialize(GlobalHolder.getApplicationContext());
            ByteBuffer buffer = ModelManager.getInstance().getModelBuffer();

            initializeTask
                    .addOnSuccessListener(a -> {
                        interpreter = InterpreterApi.create(buffer,
                                new InterpreterApi.Options().setRuntime(InterpreterApi.Options.TfLiteRuntime.FROM_SYSTEM_ONLY));
                        MLog.i(TAG, "load model success");
                    })
                    .addOnFailureListener(e -> {
                        e.printStackTrace();
                        MLog.e("Interpreter", String.format("Cannot initialize interpreter: %s",
                                e.getMessage()));
                    });
`
**Any other info / logs**
11-16 09:18:59.020 15532 16133 W DynamiteModule: Local module descriptor class for com.google.android.gms.tflite_dynamite not found.
11-16 09:18:59.046 15532 16133 I DynamiteModule: Considering local module com.google.android.gms.tflite_dynamite:0 and remote module com.google.android.gms.tflite_dynamite:231810005
11-16 09:18:59.046 15532 16133 I DynamiteModule: Selected remote version of com.google.android.gms.tflite_dynamite, version >= 231810005
11-16 09:18:59.047 15532 16133 V DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
11-16 09:18:59.085 15532 15532 W TFLiteClient-0: type=1400 audit(0.0:2479): avc: denied { execute } for path="/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk" dev="dm-41" ino=20657 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:privapp_data_file:s0:c512,c768 tclass=file permissive=0 app=xxxxxxx
11-16 09:18:59.147 15532 15716 I AD-PLUGIN-OnDeviceIntelligenceCore: OnDeviceIntelligence calculate failed, model load failed
11-16 09:18:59.148 15532 15532 W System.err: android.os.RemoteException: Error loading TFLite native library
11-16 09:18:59.148 15532 15532 W System.err:    at qb.a(:com.google.android.gms.policy_tflite_dynamite_dynamite@231810011@231810005065.544055685.544055685:0)
11-16 09:18:59.149 15532 15532 W System.err:    at com.google.android.gms.tflite.dynamite.TfLiteDynamiteLoaderImpl.b(:com.google.android.gms.policy_tflite_dynamite_dynamite@231810011@231810005065.544055685.544055685:3)
11-16 09:18:59.149 15532 15532 W System.err:    at com.google.android.gms.tflite.dynamite.TfLiteDynamiteLoaderImpl.getInternalNativeInitializationHandleWithParams(:com.google.android.gms.policy_tflite_dynamite_dynamite@231810011@231810005065.544055685.544055685:0)
11-16 09:18:59.149 15532 15532 W System.err:    at om.w(:com.google.android.gms.policy_tflite_dynamite_dynamite@231810011@231810005065.544055685.544055685:6)
11-16 09:18:59.149 15532 15532 W System.err:    at bs.onTransact(:com.google.android.gms.policy_tflite_dynamite_dynamite@231810011@231810005065.544055685.544055685:4)
11-16 09:18:59.149 15532 15532 W System.err:    at android.os.Binder.transact(Binder.java:1169)
11-16 09:18:59.149 15532 15532 W System.err:    at com.google.android.gms.internal.tflite.zza.zzb(com.google.android.gms:play-services-tflite-impl@@16.1.0:2)
11-16 09:18:59.150 15532 15532 W System.err:    at com.google.android.gms.tflite.dynamite.zza.zzf(com.google.android.gms:play-services-tflite-impl@@16.1.0:4)
11-16 09:18:59.150 15532 15532 W System.err:    at com.google.android.gms.tflite.dynamite.internal.zzk.zzc(com.google.android.gms:play-services-tflite-impl@@16.1.0:11)
11-16 09:18:59.150 15532 15532 W System.err:    at com.google.android.gms.tflite.dynamite.internal.zzi.zza(com.google.android.gms:play-services-tflite-impl@@16.1.0:9)
11-16 09:18:59.150 15532 15532 W System.err:    at com.google.android.gms.tflite.dynamite.internal.zzf.then(Unknown Source:6)
11-16 09:18:59.150 15532 15532 W System.err:    at com.google.android.gms.tasks.zzo.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
11-16 09:18:59.151 15532 15532 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
11-16 09:18:59.151 15532 15532 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
11-16 09:18:59.151 15532 15532 W System.err:    at java.lang.Thread.run(Thread.java:1012)
11-16 09:18:59.152 15532 15532 W System.err: Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so" segment 1: Permission denied
11-16 09:18:59.152 15532 15532 W System.err:    at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
11-16 09:18:59.152 15532 15532 W System.err:    at java.lang.Runtime.loadLibrary0(Runtime.java:998)
11-16 09:18:59.152 15532 15532 W System.err:    at java.lang.System.loadLibrary(System.java:1661)
11-16 09:18:59.152 15532 15532 W System.err:    at com.google.android.gms.tflite.dynamite.TfLiteNativeApi.b(:com.google.android.gms.policy_tflite_dynamite_dynamite@231810011@231810005065.544055685.544055685:2)
11-16 09:18:59.153 15532 15532 W System.err:    at com.google.android.gms.tflite.dynamite.TfLiteNativeApi.a(:com.google.android.gms.policy_tflite_dynamite_dynamite@231810011@231810005065.544055685.544055685:0)
11-16 09:18:59.153 15532 15532 W System.err:    at com.google.android.gms.tflite.dynamite.TfLiteDynamiteLoaderImpl.b(:com.google.android.gms.policy_tflite_dynamite_dynamite@231810011@231810005065.544055685.544055685:2)
11-16 09:18:59.153 15532 15532 W System.err:    ... 13 more

**Comment by tilakrayal** [comment]
@jahonn,
Could you please try to add the below line in this case

`          implementation 'com.google.android.gms:play-services-tflite-java:16.1.0          `

to the Tensorflow lite dependencies section 

(OTOH, you might not need the `org.tensorflow:tensorflow-lite-task-vision-play-services` dependency if you are using InterpreterApi. Also please take a look at the [Interpreter API dependencies](https://www.tensorflow.org/lite/android/play_services#1_add_project_dependencies_2). Thank you!

**Comment by jahonn** [comment]
Hi @tilakrayal 

I have already added the Tensorflow Lite dependencies in my build.gradle, and got the error.

It seems the root error is
`
 java.lang.UnsatisfiedLinkError: dlopen failed: couldn't map "/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so" segment 1: Permission denied
`

Yes, I'm using InterpreterApi.

**Comment by jahonn** [comment]
I opened the dlerror and dlopen log, and get this.

`
11-17 10:14:03.807 17066 17688 D linker  : dlopen(name="/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so", flags=0x2, extinfo=[flags=0x200, reserved_addr=0x0, reserved_size=0x0, relro_fd=0, library_fd=0, library_fd_offset=0x0, library_namespace=classloader-namespace@0x76152ccf10], caller="/apex/com.android.art/lib64/libnativeloader.so", caller_ns=com_android_art@0x76152cc1f0, targetSdkVersion=33) ...
11-17 10:14:03.808 17066 17688 D linker  : find_libraries(ns=classloader-namespace): task=/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so, is_dt_needed=0
11-17 10:14:03.808 17066 17688 D linker  : load_library(ns=classloader-namespace, task=/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so, flags=0x2, search_linked_namespaces=1): calling open_library
11-17 10:14:03.808 17066 17688 D linker  : load_library(ns=classloader-namespace, task=/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so, flags=0x2, realpath=/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so, search_linked_namespaces=1)
11-17 10:14:03.809 17066 17688 D linker  : load_library(ns=classloader-namespace, task=/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so): Adding DT_NEEDED task: libdl.so
11-17 10:14:03.809 17066 17688 D linker  : load_library(ns=classloader-namespace, task=/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so): Adding DT_NEEDED task: libm.so
11-17 10:14:03.809 17066 17688 D linker  : load_library(ns=classloader-namespace, task=/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so): Adding DT_NEEDED task: liblog.so
11-17 10:14:03.809 17066 17688 D linker  : load_library(ns=classloader-namespace, task=/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so): Adding DT_NEEDED task: libc.so
11-17 10:14:03.809 17066 17688 D linker  : find_libraries(ns=classloader-namespace): task=libdl.so, is_dt_needed=1
11-17 10:14:03.809 17066 17688 D linker  : find_library_internal(ns=classloader-namespace, task=libdl.so): Already loaded (by soname): /apex/com.android.runtime/lib64/bionic/libdl.so
11-17 10:14:03.809 17066 17688 D linker  : find_libraries(ns=classloader-namespace): task=libm.so, is_dt_needed=1
11-17 10:14:03.809 17066 17688 D linker  : find_library_internal(ns=classloader-namespace, task=libm.so): Already loaded (by soname): /apex/com.android.runtime/lib64/bionic/libm.so
11-17 10:14:03.809 17066 17688 D linker  : find_libraries(ns=classloader-namespace): task=liblog.so, is_dt_needed=1
11-17 10:14:03.810 17066 17688 D linker  : find_library_internal(ns=classloader-namespace, task=liblog.so): Already loaded (by soname): /system/lib64/liblog.so
11-17 10:14:03.810 17066 17688 D linker  : find_libraries(ns=classloader-namespace): task=libc.so, is_dt_needed=1
11-17 10:14:03.810 17066 17688 D linker  : find_library_internal(ns=classloader-namespace, task=libc.so): Already loaded (by soname): /apex/com.android.runtime/lib64/bionic/libc.so
11-17 10:14:03.810 17066 17688 D linker  : ... dlclose(realpath="/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so"@0x76153c8598) ... load group root is "/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so"@0x76153c8598
11-17 10:14:03.808 17066 17066 W TFLiteClient-0: type=1400 audit(0.0:11423): avc: denied { execute } for path="/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk" dev="dm-41" ino=20657 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:privapp_data_file:s0:c512,c768 tclass=file permissive=0 app=com.miui.msa.global
11-17 10:14:03.810 17066 17688 D linker  : ... dlclose: calling destructors for "/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so"@0x76153c8598 ...
11-17 10:14:03.810 17066 17688 D linker  : ... dlclose: calling destructors for "/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so"@0x76153c8598 ... done
11-17 10:14:03.811 17066 17688 D linker  : ... dlclose: unloading "/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so"@0x76153c8598 ...
11-17 10:14:03.811 17066 17688 D linker  : ... dlclose: unload_si was not linked - not unloading external references ...
11-17 10:14:03.811 17066 17688 D linker  : ... dlopen failed: couldn't map "/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so" segment 1: Permission denied
11-17 10:14:03.811 17066 17688 D linker  : dlerror set to "dlopen failed: couldn't map "/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so" segment 1: Permission denied"
`

**Comment by LakshmiKalaKadali** [comment]
@pkgoogle, 
Please look into the issue

Thank you

**Comment by pkgoogle** [comment]
Hi @jahonn, we need more context to reproduce this, If you can export your android project into a zip file that will be easiest.  If you are following a resource please let us know which resource it is. If it contains proprietary code, see if you can start a new project and make the minimal changes/additions to reproduce the issue, then export this project. Thanks for your help.

**Comment by jahonn** [comment]
hi @pkgoogle ,
I created a new project using the same code, but the init was successful.
I cannot share the real project code. This project is a system-signed application and is an activity-less application. Will this have any impact?

**Comment by pkgoogle** [comment]
Hi @jahonn, Interesting ... a good data point for now, I suspect then that it is something incongruent with your gradle setups, can you maybe try to verify what the differences are with your new project gradle setup and your real project's grade setup. If you are comfortable sharing your gradle files (perhaps you can censor things that you are confident are irrelevant) for both we can take a look.

**Comment by pkgoogle** [comment]
Hi @jahonn, can you confirm you are fully following the directions on this page? There's a possibility that it has been updated since you last read it. https://www.tensorflow.org/lite/android/play_services#using_the_interpreter_apis

I guess I meant the build.gradle files ... I was looking for the files which should include something like this: 

```kt
dependencies {
...
    // Tensorflow Lite dependencies for Google Play services
    implementation 'com.google.android.gms:play-services-tflite-java:16.0.1'
    // Optional: include Tensorflow Lite Support Library
    implementation 'com.google.android.gms:play-services-tflite-support:16.0.1'
...
}
```

**Comment by jahonn** [comment]
Hi @pkgoogle 

I'm using this version
‘
    // Tensorflow Lite dependencies
    implementation 'com.google.android.gms:play-services-tflite-java:16.1.0'

’

**Comment by jahonn** [comment]
and the whole build.gradle file is 
plugins {
    id 'com.android.library'
}

android {
    namespace 'xxxxxxxx'
    compileSdkVersion rootProject.ext.compileSdkVersion

    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    sourceSets {
        main {
            aidl.srcDirs += ["src/main/java"]
        }
    }
}

dependencies {
    // Tensorflow Lite dependencies
    implementation 'com.google.android.gms:play-services-tflite-java:16.1.0'
    ......
}

**Comment by pkgoogle** [comment]
Hi @jahonn, Can you add this to your build.gradle dependencies:

```java
implementation 'com.google.android.gms:play-services-tflite-support:16.0.1'
```

additionally did you do these steps before using the Interpreter API? https://www.tensorflow.org/lite/android/play_services#using_the_interpreter_apis

2. Add initialization of TensorFlow Lite:
```java
Task<Void> initializeTask = TfLite.initialize(context);
```

3. Ensure you have these dependencies
```java
import org.tensorflow.lite.InterpreterApi
import org.tensorflow.lite.InterpreterApi.Options.TfLiteRuntime
...
private InterpreterApi interpreter;
...
```

before the code you originally posted?

**Comment by jahonn** [comment]
Hi @pkgoogle 

I added the support lib, but still get the error.
```
    implementation 'com.google.android.gms:play-services-tflite-java:16.0.1'
    implementation 'com.google.android.gms:play-services-tflite-support:16.0.1'

```

code as below 
```
            Task<Void> initializeTask = TfLite.initialize(GlobalHolder.getApplicationContext());
            ByteBuffer buffer = ModelManager.getInstance().getModelBuffer(); // model from asserts

            initializeTask
                    .addOnSuccessListener(a -> {
                        MLog.i(TAG, "load model success");
                        interpreter = InterpreterApi.create(buffer,
                                new InterpreterApi.Options().setRuntime(TfLiteRuntime.FROM_SYSTEM_ONLY));
                    })
                    .addOnFailureListener(e -> {
                        MLog.e("Interpreter", String.format("Cannot initialize interpreter: %s",
                                e.getMessage()));
                    });

```

error as below

`dlerror set to "dlopen failed: couldn't map "/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so" segment 1: Permission denied"`

**Comment by pkgoogle** [comment]
Hi @jahonn, are you using a real phone or an emulator? For both cases, can you ensure the Google Play Services app has as permissive permissions as possible, and then try running your projects again?

**Comment by jahonn** [comment]
@pkgoogle  hi, I using a real phone.  All permissions the Google Play Services app need is allowed.

**Comment by pkgoogle** [comment]
Hi @jahonn, I think there is a permission difference between the two projects you tested, can you ensure your Google Play Services are updated and that your SDK version is above or equal to the targetSdkVersion? Additional, can you look at the logcat to see if there are permission errors prior to error message, also it may be worth it to compare logs from your new project that worked and your current project which doesn't work. Feel free to post it excluding PII for us to take a look.

**Comment by fergushenderson** [comment]
The relevant error messages seem to be these ones:

```
11-16 09:18:59.085 15532 15532 W TFLiteClient-0: type=1400 audit(0.0:2479): avc: denied { execute } for path="/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk" dev="dm-41" ino=20657 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:privapp_data_file:s0:c512,c768 tclass=file permissive=0 app=xxxxxxx
```

and

```
11-17 10:14:03.811 17066 17688 D linker : ... dlopen failed: couldn't map "/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk!/lib/arm64-v8a/libtflite_gmscore_jni.so" segment 1: Permission denied
```

and

```
11-16 09:18:59.148 15532 15532 W System.err: android.os.RemoteException: Error loading TFLite native library
11-16 09:18:59.148 15532 15532 W System.err: at qb.a(:com.google.android.gms.policy_tflite_dynamite_dynamite@231810011@231810005065.544055685.544055685:0)
11-16 09:18:59.149 15532 15532 W System.err: at com.google.android.gms.tflite.dynamite.TfLiteDynamiteLoaderImpl.b(:com.google.android.gms.policy_tflite_dynamite_dynamite@231810011@231810005065.544055685.544055685:3)
```

Basically the issue is that the SELinux security policy in your phone's OS is denying your app execute permission to the "TF Lite in Play services" APK file
`/data/user_de/0/com.google.android.gms/app_chimera/m/00000016/dl-TfliteDynamiteDynamite.integ_231810005100400.apk`
which contains the native code shared library file `lib/arm64-v8a/libtflite_gmscore_jni.so` embedded within it.
The file descriptor for that file is opened by the "TF Lite in Play services" module of Play services, and then passed back to your app, and then passed to `android_dlopen_ext` by the "TF Lite in Play services" client library.

I suspect this is likely due to a misconfiguration of the SELinux policy for the device?

If my diagnosis is correct, a proper fix would require updating the SELinux policy configuration files that the OS provides.

A likely work-around is to run the following command (requires root):

```
adb shell setenforce 0
```

It may be worth raising this issue with the OEM that supplies the OS for your device.
Your device was `Redmi/thunder_global/thunder:13/TP1A.220624.014/V0.0.0.0.XXXXXXX:user/test-keys`,
so I guess that would be Redmi.

**Comment by jahonn** [comment]
@fergushenderson hi, thank you for your response. It's been a long time, and I also flashed a new ROM. I will rewrite a demo and try it on the new ROM.

**Comment by jahonn** [comment]
@fergushenderson  
Thank you! I init the  interpreter successfully with the command!
