### ISSUE TITLE
TensorFlow Models now missing ?

### ISSUE THREAD

**Issue by dangithubs** [tensorflow/tensorflow#6241]
So currently doing some testing of the latest master branch on an AWS box. I built yesterday (UK time) and I went through installing tensorflow fine with no issues.

Today I have done a fresh install again taking from the master branch and for some reason when I run my samples through I get the following:

python -m tensorflow.models.image.mnist.convolutional
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so.8.0 locally
/home/ubuntu/anaconda3/bin/python: Error while finding spec for 'tensorflow.models.image.mnist.convolutional' (<class 'ImportError'>: No module named 'tensorflow.models')

**Comment by kingtaurus** [comment]
I believe they moved the models to a separate repository:
[models](https://github.com/tensorflow/models)

**Comment by Carmezim** [comment]
@kingtaurus is correct, [PR #731](https://github.com/tensorflow/models/pull/731) was merged moving the example models which includes mnist tutorial, 12h ago. Tutorials and docs were updated although I don't know how much time it will take for them to be updated to tensorflow.org but the site successfuly links to 0.12r. As last resource for now cloning the repository should work.

**Comment by michaelisard** [comment]
Closing for now: please reopen if there's another underlying issue thanks.

**Comment by dangithubs** [comment]
Thanks Guys can you advise which is the lastest stable version to build from ?  I just did another build switching to tags/0.12.0-rc0 and when I try and run the same sample as above I get the below. Is it best to drop back to 0.11 ?

"Error while finding spec 'tensorflow.models.image.mnist.convolutional.py' (<class 'AttributeError'>: 'module' object has no attribute 'path')

**Comment by Carmezim** [comment]
I am not sure but it seems they are not going to include the models in the 0.12r wheel.

**Comment by sandipt** [comment]
I'm able to execute python convolutional.py --self_test with no issue but below command throwing error. How I can solve it? Can someone provide detailed resolution? ( Sorry I'm new to Python ) .

[root@localhost ~]# virtualenv --system-site-packages -p python3 ~/tensorflow
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /root/tensorflow/bin/python3
Not overwriting existing python script /root/tensorflow/bin/python (you must use /root/tensorflow/bin/python3)
Installing setuptools, pip, wheel...done.
[root@localhost ~]#

[root@localhost ~]# source ~/tensorflow/bin/activate

(tensorflow) [root@localhost ~]# export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:/root/cuda/lib64

(tensorflow) [root@localhost ~]# python -m tensorflow.models.image.mnist.convolutional
/root/tensorflow/bin/python: Error while finding spec for 'tensorflow.models.image.mnist.convolutional' (<class 'ImportError'>: No module named 'tensorflow.models')
