### ISSUE TITLE
Using TensorFlow Lite for android development, copied repo from source and while running code I am facing error

### ISSUE THREAD

**Issue by kartik-waghmare** [tensorflow/tensorflow#62410]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Microsoft Windows 10 Pro
- TensorFlow library (version, if pip package or github SHA, if built from source): git clone https://github.com/tensorflow/examples.git

### 2. Software
 Android Studio Flamingo | 2022.2.1 Patch 2

Issue Log:  Cannot use @TaskAction annotation on method DataBindingGenBaseClassesTask.writeBaseClasses() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method

**Comment by LakshmiKalaKadali** [comment]
Hi @kartik-waghmare, 

The Issuelog displaying here might be due to gradle version. 
Please provide some more context to better understand the issue and Which Tflite example you have considered?

**Comment by eyeskt** [comment]
I've the same issues and here is my Gradle version.

~/StudioProjects/examples]:  
  → ./lite/examples/object_detection/android_play_services/gradlew --version

Welcome to Gradle 8.4!

Here are the highlights of this release:
 - Compiling and testing with Java 21
 - Faster Java compilation on Windows
 - Role focused dependency configurations creation

For more details see https://docs.gradle.org/8.4/release-notes.html


------------------------------------------------------------
Gradle 8.4
------------------------------------------------------------

Build time:   2023-10-04 20:52:13 UTC
Revision:     e9251e572c9bd1d01e503a0dfdf43aedaeecdc3f

Kotlin:       1.9.10
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          11.0.21 (Debian 11.0.21+9-post-Debian-1)
OS:           Linux 6.5.6-1rodete4-amd64 amd64

**Comment by gianpaolof** [comment]
same issue for me
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.4-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
