### ISSUE TITLE
Will Tflite support flatbuffers v23.5.26 in the future ?(in this version, flatbuffers already support 64 bit field)

### ISSUE THREAD

**Issue by zhangguog** [tensorflow/tensorflow#62413]
### 1. System information

Linux

### 2. Question
I already see that Tesnorflow Lite can support  models > 2GB in schema Version 3c, but I also see that Flatbuffers add "offset64" and "vector64" in latest version.
So I want to ask if Tesnorflow Lite will use Flatbuffers 64 bit field instead of schema Version 3c' upgrade?

**Comment by pkgoogle** [comment]
Hi @zichuan-wei, do you know the answer to this? Thanks for your help.

**Comment by zichuan-wei** [comment]
Hi @zhangguog , 
Thanks for the question, so far we don't have plans for migrating over to Flatbuffer 64 bit fields. We do however continue to evaluate different solutions and will revisit this if such need arise
