### ISSUE TITLE
Support TFLite  Shared library build with CMake

### ISSUE THREAD

**Issue by neg-c** [tensorflow/tensorflow#62439]
### Issue type

Feature Request

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.14

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Bazel version

Cmake 3.27.7

### GCC/compiler version

gcc 9.4.0

### Current behavior?

By default the **Cmake** build produces only static library which is not convenient when you have multiple project that use **TFLite**

### Standalone code to reproduce the issue

[TFLite build guide](https://www.tensorflow.org/lite/guide/build_cmake)

**Comment by LakshmiKalaKadali** [comment]
Hi @neg-c, 

Tensorflowlite shared library support is available with Cmake build for C API,  and also as this [comment](https://github.com/tensorflow/tensorflow/issues/52542#issuecomment-986341903) suggests please use Bazel for shared library for your usecase.

Thank You

**Comment by neg-c** [comment]
Hi @LakshmiKalaKadali thank you, that works.

I understand that the main build system used for TF is bazel, but having only static build support with CMake doesnt really make sense, or am i missing something? 

Please let me know if you are planning on adding shared build support, in which case i would be happy to help.

**Comment by LakshmiKalaKadali** [comment]
Hi @neg-c ,

Thanks for your interest in supporting Shared build support for Cmake.  Certain complexities are involved in creating c++ shared libraries unlike C where only header files are required. Moreover, compared to Bazel, the way they handle the libraries is different in Cmake. As per my knowledge at that moment, there is no plan in adding shared library support for Cmake. 

Thank you.
