### ISSUE TITLE
Using bazel build a c api 

### ISSUE THREAD

**Issue by panhu** [tensorflow/tensorflow#62445]
**System information**
- OS Platform and Distribution Linux Centos8):
- TensorFlow installed from source
- TensorFlow version ( github SHA if from source):

**Question**
Hi:
When I used 'bazel build -c opt //tensorflow/lite/c:tensorflowlite_c' to create the C API for tflite. I only got 'libtensorflowlite_c. so' of only 4.4M, and I'm not sure if it's correct because it's too small?May I ask if this size is correct? Why is it so small?

Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @panhu ,

On linux given build command should generate `libtensorflowlite_c.so`, and the mentioned size seems Ok to me as per the similar ticket #48068. 

You may also test with C-Make build as per instructions [here](https://www.tensorflow.org/lite/guide/build_cmake).

You can also refer lite guide [here](https://www.tensorflow.org/lite/guide#:~:text=Key%20Point%3A%20The%20TensorFlow%20Lite%20binary%20is%20~1MB%20when%20all%20125%2B%20supported%20operators%20are%20linked%20(for%2032%2Dbit%20ARM%20builds)%2C%20and%20less%20than%20300KB%20when%20using%20only%20the%20operators%20needed%20for%20supporting%20the%20common%20image%20classification%20models%20InceptionV3%20and%20MobileNet.). Basically all tensorflow Ops are not supported for tflite and hence it is lightweight.

**Comment by panhu** [comment]
Hi@SuryanarayanaY:
Thank you for your reply. I would like to ask if Tflite supports the Risc-v architecture. If so, how should we build the relevant shared library of tflite ? Is there a Risc-v toolchain?
Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @panhu,
It seems this query is already answered [here](https://github.com/tensorflow/tensorflow/issues/60849#issuecomment-1633217814).

**Comment by 6eanut** [comment]
hi @panhu,
i am working on building bazel on risc-v. do you have any way?
thanks!
