### ISSUE TITLE
TFLIte interpreter crashes on Pixel 6 by not finding OpenCL lib 

### ISSUE THREAD

**Issue by raydenvoldeskine** [tensorflow/tensorflow#62462]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.5.0

### Custom code

No

### OS platform and distribution

Android

### Mobile device

Pixel 6, Android 13

### Current behavior?

TFlite Interpreter by instantiation crashes the app with message when started with GPU (see below)

Using NNAPI does not cause the crash, yet the initialisation of interpreter takes about 20 s which is hardly acceptable. 

Note that running Benchmark tool on same device with same model, on GPU works. 

### Standalone code to reproduce the issue

```shell
Not possible
```

### Relevant log output

```shell
`java.lang.IllegalArgumentException: Internal error: Failed to run on the given Interpreter: Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found`

` TfLiteGpuDelegate Invoke: [GL_INVALID_VALUE]: A numeric argument is out of range.: glDispatchCompute in tensorflow/lite/delegates/gpu/gl/gl_program.cc:217`
```

**Comment by LakshmiKalaKadali** [comment]
Hi @raydenvoldeskine ,

Please add the following to the Android manifest in order to detect GPU delegate.

```
<uses-library android:name="libOpenCL.so"
           android:required="false"/>

<uses-library android:name="libOpenCL-pixel.so"
           android:required="false"/>
```
Please let us know if it helps you.

Thank you

**Comment by raydenvoldeskine** [comment]
Thank you for a really fast feedback. The trick did work on Pixel 6 device.  Could you pls also explain the general situation: 

-> Is that an official approach to use with TFLtie on Android? If yes, why it is not relfected in initial configuration instructions - or did I miss something? 
-> what about other devices - Pixels or not Pixels, which would not have openCL (or maybe have an incompatible version)? I want to get more confidence that after we made this fix, the app still works on other devices.

**Comment by LakshmiKalaKadali** [comment]
Hi
@raydenvoldeskine ,

Response1: Yes, it's an official approach . Applications that target Android S+ require explicit declaration of
             any referenced vendor-provided libraries. Ref[ doc](https://github.com/tensorflow/tensorflow/blob/7b8dd63247d2d62254c3021c1f1188a60eb5eb85/tensorflow/lite/java/AndroidManifestGpuApi.xml).

Response2:  This fix works on android 12 and above and it might not depend upon the device. OpenCL allows developers to write code that can run on different devices, regardless of the manufacturer or architecture, by providing a common set of commands and a runtime environment that can execute the code on the target device.
Check these related issues  also. [#60720](https://github.com/tensorflow/tensorflow/issues/60720), [#48001](https://github.com/tensorflow/tensorflow/issues/48001), [#50394](https://github.com/tensorflow/tensorflow/issues/50394). Please let us know if u have any new observations



Thank You
