### ISSUE TITLE
Feature request: TensorFlow Hub and HuggingFace integration

### ISSUE THREAD

**Issue by AIWithShrey** [tensorflow/tensorflow#62470]
Integrate HuggingFace Hub and TensorFlow Hub for out-of-the-box usage with models and datasets.

Support for TensorFlow version of HuggingFace offerings (Transformers, Diffusers, etc.)

**Comment by SuryanarayanaY** [comment]
Hi @AIWithShrey ,

Tfhub already moved to Kaggle models. Please find then announcement of same from [TF-forum.](https://discuss.tensorflow.org/t/tensorflow-hub-is-moving-to-kaggle-models/20770)

I doubt whether it can be integrated with Hugginface now. Will discuss internally and let you know.

Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @AIWithShrey ,

Please raise your query at [TF-hub](https://github.com/tensorflow/hub/issues) repo as it should be addressed there. Thanks!

**Comment by AIWithShrey** [comment]
> Hi @AIWithShrey ,
> 
> Please raise your query at [TF-hub](https://github.com/tensorflow/hub/issues) repo as it should be addressed there. Thanks!

Sure! Thanks.

**Comment by SuryanarayanaY** [comment]
Hi @AIWithShrey ,

Could you please close the issue and track at Hub repo?
