### ISSUE TITLE
Configure fails when run non-interactively

### ISSUE THREAD

**Issue by adamcrume** [tensorflow/tensorflow#6248]
Running ./configure non-interactively fails for 0.12.0-rc0, and it worked on previous releases.  We're relying on this for the TensorFlow Rust bindings and expect it to configure with default options.  configure seems to be failing on a 'read -p', probably because of 'set -e' being added.

### Environment info
Operating System: Linux (Ubuntu 16.04.1)
Checked out tag: 0.12.0-rc0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
./configure < /dev/null

**Comment by martinwicke** [comment]
Can you use yes | ./configure instead? That is what we use in our scripts.

**Comment by adamcrume** [comment]
`yes '' | ./configure` seems to work.

**Comment by gunan** [comment]
It is also possible that there are some new environment variables you need to set, such as `TF_NEED_OPENCL`.

Closing this issue, as it seems to be resolved now.
