### ISSUE TITLE
Python code modifies loop while iterating over it

### ISSUE THREAD

**Issue by Sjord** [tensorflow/tensorflow#62492]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

The code is present on the master branch, but I found this bug by looking at the code, not from executing TensorFlow.

### Source

source

### TensorFlow version

master

### Custom code

No

### Current behavior?

In tensorflow/python/training/saver.py, in _RecordLastCheckpoint:

```
# Remove first from list if the same name was used before.
for p in self._last_checkpoints:
  if latest_save_path == self._CheckpointFilename(p):
    self._last_checkpoints.remove(p)
```

This modifies the `_last_checkpoints` list while iterating over it, causing the loop to skip steps.

This seems like a bug, from looking at the code.

This should probably be something like:

```
self._last_checkpoints = [p for p in self._last_checkpoints if latest_save_path != self._CheckpointFilename(p)]
```

### Standalone code to reproduce the issue

```shell
Example program:


l = [1, 1, 1, 1, 1, 1, 1, 1]

for e in l:
	if e == 1:
		l.remove(e)

print(l)
```

Output

```
[1, 1, 1, 1]
```
```


### Relevant log output

_No response_

**Comment by proxOP** [comment]
Doing this will pass a copy of the list for checking then modyfing the original list seperately:
for p in self._last_checkpoints[:]:
    if latest_save_path == self._CheckpointFilename(p):
        self._last_checkpoints.remove(p)
