### ISSUE TITLE
can't export data via event_accumulator.py

### ISSUE THREAD

**Issue by yhydhx** [tensorflow/tensorflow#6250]
f you'd like to export data to visualize elsewhere (e.g. iPython Notebook), that's possible too. You can directly depend on the underlying classes that TensorBoard uses for loading data: python/summary/event_accumulator.py (for loading data from a single run) or python/summary/event_multiplexer.py (for loading data from multiple runs, and keeping it organized). These classes load groups of event files, discard data that was "orphaned" by TensorFlow crashes, and organize the data by tag.

And I do it as what it sayid with the mnist example in tensorflow. But I can't get any event from the original data whereas it shows on the tensorboard normally.

below is my code:

x = EventAccumulator(path="/tmp/tensorflow/mnist/logs/mnist_with_summaries/")
x.Reload()
print(x.Tags())
x.FirstEventTimestamp()
print(x.Tags())
And the result showed like below:

{'scalars': [], 'histograms': [], 'run_metadata': [], 'images': [], 'graph': False, 'audio': [], 'meta_graph': False, 'compressedHistograms': []}

I can't get any tag or event from the original data. However, when I open the tensorboard. Everything just look fine.

**Comment by michaelisard** [comment]
This kind of usage question is better asked on [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow).
