### ISSUE TITLE
Please bring back native Windows CUDA support! 

### ISSUE THREAD

**Issue by pass-lin** [tensorflow/tensorflow#62501]
### Issue type

Feature Request

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf2.15

### Custom code

Yes

### OS platform and distribution

windows

### Python version

3.10

### Current behavior?

i want to use keras3.0 at windows,but it only support tensorflow1.15 that can't use GPU

### Standalone code to reproduce the issue

```shell
tf.test
```

**Comment by mihaimaruseac** [comment]
This is a duplicate of #59918
