### ISSUE TITLE
Add a csv/plain data input from directory

### ISSUE THREAD

**Issue by Formiga57** [tensorflow/tensorflow#62511]
### Issue type

Feature Request

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.14.0

### Custom code

Yes

### Current behavior?

I'm a aerospace engineering student actually searching for ways to measure sensors influence within a wing with help of ML. Given a lot of researches based on gathering sensors data stored in .csv files or binary ones, we thought it would be a nice feature to have a csv loader or even more formats of data files from sensors or researches, not only mainly Images, Audio or Text.
Then we implemented a "csv_dataset_from_directory()", by now as just an example, method to load a directory with multiple classes of csv, notwithstanding resulting in good results with a tiny amount of our dataset.

Please feel free to give any comments or suggestions about this implementation, we had only about 12 hours to think in a project cause we're in a Hackathon right now. Let us know if you guys had issues inputting that kind of data, therefore for our use in the aerospace engineering would be the exactly feature we're looking for!

[Pull Request into Keras](https://github.com/keras-team/keras/pull/18853)
[Pull Request into Docs](https://github.com/tensorflow/docs/pull/2289)

The analysis is included in the Docs.

### Standalone code to reproduce the issue

```shell
import keras
csv_dataset = keras.utils.csv_dataset_from_directory(
    "./cases",
    stride = 1,
    batch_size=1,

)
class_names = csv_dataset.class_names
```

**Comment by sachinprasadhs** [comment]
Hi, 

Thanks for filing a feature request.

You can make use of `tf.data.experimental.CsvDataset` [here](https://www.tensorflow.org/api_docs/python/tf/data/experimental/CsvDataset) to load the CSV data and then it can be used in any of the model building process.

Also, if you would like to feed the data to the Keras model, then you can load the CSV file using Pandas and prepare a pipeline as mentioned here https://www.tensorflow.org/tutorials/load_data/csv.
