### ISSUE TITLE
tf.compat.v1.conv2d_backprop_input does not work well with bfloat16 input.

### ISSUE THREAD

**Issue by Unireverse** [tensorflow/tensorflow#62525]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf2.5.3

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu20.04

### Python version

3.8.10

### CUDA/cuDNN version

11.7/cudnn8

### GPU model and memory

A100-40G

### Current behavior?

When using bfloat16 as type of filter and out_backprop in tf.compat.v1.nn.conv2d_backprop_input API, the output is empty.
I WONDER if this is a bug of bfloat16.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

a = tf.ones([2,3,3,6], dtype=tf.blfoat16)
b = tf.ones([3,3,1,6], dtype=tf.bfloat16)

c = tf.compat.v1.nn.conv2d_backprop_input(
    input_sizes=[2,7,7,1],
    filter=b,
    out_backprop=a,
    strides=[1,2,2,1],
    padding="VALID",
    data_format="NHWC",
    dilation=[1,1,1,1]
)
print(c)
```

### Relevant log output

```shell
The output is :
tf.Tensor([], shape=(0,), dtype=float32)
```

**Comment by tilakrayal** [comment]
@Unireverse,
I tried to execute the mentioned code on latest tensorflow v2.14 with the both [CPU](https://colab.research.google.com/gist/tilakrayal/a83cfc4c363a62e2754fe3c7144446ae/untitled1544.ipynb) and GPU enviroment, and it was executed without any issue/error & also observed that the output is also intended. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/854dc4975edbdab70999baf2424ad394/untitled1545_gpu.ipynb). 

Also the tensorflow v2.5 which is pretty older, recommended to use the latest tensorflow versions. Thank you!
