### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'contrib' 

### ISSUE THREAD

**Issue by JT-Studios** [tensorflow/tensorflow#62531]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15.0 I think

### Custom code

Yes

### Python version

3.10.9

### Current behavior?

I know this error happens because I am using a newer version of tensorflow but I can't downgrade my python version due to the hardware I am using. Is it possible to get the right tensorflow version for this (I think 2.4 should work) or is there some other way I can solve this error? Thanks!

### Standalone code to reproduce the issue

```shell
I am trying to run this command: 
`python Tensorflow/models/research/object_detection/model_main_tf2.py --model_dir=Tensorflow/workspace/models/my_ssd_mobnet --pipeline_config_path=Tensorflow/workspace/models/my_ssd_mobnet/pipeline.config --num_train_steps=2000`
```

### Relevant log output

```shell
AttributeError: module 'tensorflow' has no attribute 'contrib'
```

**Comment by Venkat6871** [comment]
Hi **@JT-Studios** ,
Could you please provide a code snippet to reproduce the issue reported here.

Thank you!
