### ISSUE TITLE
TensorFlow Lite Flex Op Request: modulo operator

### ISSUE THREAD

**Issue by kjabon** [tensorflow/tensorflow#62538]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 22.04, but will extend to windows.
- TensorFlow installed from (source or binary): binary/pip
- TensorFlow version (or github SHA if from source): 2.15.0 

**Provide the text output from tflite_convert**

```
error: failed while converting: 'jit(policy_interp)/jit(main)/while/body/while[cond_nconsts=0 body_nconsts=21]_body': 
Some ops in the model are custom ops, See instructions to implement custom ops: https://www.tensorflow.org/lite/guide/ops_custom 
Custom ops: Mod
Details:
	tf.Mod(tensor<i32>, tensor<i32>) -> (tensor<i32>)
```

**Standalone code to reproduce the issue** 

[colab here](https://colab.research.google.com/drive/1nN4_EqViGlgaDmQnU6tqB1a-bdXSs0lx?usp=sharing)

Coming from [here:](https://www.tensorflow.org/lite/guide/op_select_allowlist#add_tensorflow_core_operators_to_the_allowed_list)
I would like to be able to add tf.Mod to the allowed list.
As noted in the Colab, I'm not sure what "best practice" is here. Is it better to set allow_custom_ops to True and move on? I would like to deploy on mobile, and am concerned about file size and performance. Edit: making a custom op doesn't cleanly solve my issue, since the code I'm trying to convert originates from JAX.

I'm ok with submitting a PR myself too, but might like some help.

Further edit: it turns out I can work around this issue by refactoring my model. This won't be too bad, but since this would be a nice feature to have anyway for me and potentially others, not closing the issue yet.

**Comment by LakshmiKalaKadali** [comment]
Hi @kjabon, as per the  [documentation](https://www.tensorflow.org/lite/guide/ops_custom), it is recommended to set converter.allow_custom_ops = True. As you mentioned, custom op doesnot solve your issue completely, could you please provide some more details for better understanding the problem.


Thank You

**Comment by kjabon** [comment]
I've worked around this issue entirely by using tfcompile - much fewer headaches since jax2tf wraps stablehlo which is converted directly to xla.

But to answer your question, the source is in jax - so it it's not clear to me how one would use both tf (custom ops) and jax/lax functions and then pass that to jax2tf.
