### ISSUE TITLE
ValueError: batch_dims != 0 is not supported for ragged gather yet.

### ISSUE THREAD

**Issue by beanduan22** [tensorflow/tensorflow#62544]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.13

### Custom code

Yes

### Current behavior?

```python 
import tensorflow as tf
a = tf.ragged.constant([[1, 1]])
b = tf.ragged.constant([[[0], [0]]], ragged_rank=1)
oytput = tf.gather_nd(a, b, batch_dims=1)
print(oytput)

### Standalone code to reproduce the issue

```shell
raise ValueError('batch_dims != 0 is not supported for ragged gather yet.')
ValueError: batch_dims != 0 is not supported for ragged gather yet.
```

**Comment by SuryanarayanaY** [comment]
Hi @beanduan22 ,

As the exception indicates ragged tensor gather won't yet support with `batch_dims != 0`. It is intended behaviour.

Also the innermost dimension of indices should not be ragged.The indices were changed to make it workable. Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/8cd19a1e2b75506962626142a4e5eda2/62544.ipynb).

Thanks!
