### ISSUE TITLE
Fail Installation through pip on Windows version 10.0.10586

### ISSUE THREAD

**Issue by mcjjin** [tensorflow/tensorflow#6254]
For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: windows 10 (version 10.0.10586)

pip version 
pip 9.0.1 from d:\program files\python\lib\site-packages (python 3.5)

the Fail issue information :

C:\Users\Administrator>pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl

tensorflow-0.12.0rc0-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.
![bug](https://cloud.githubusercontent.com/assets/8590489/21081141/91a281b0-bffb-11e6-898a-60fa48b243dc.png)

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by hsidlagh** [comment]
Facing exactly same issue in Windows 8.1. Recently heard that TensorFLow can be used for Windows with some limitations.

![err](https://cloud.githubusercontent.com/assets/16458319/21082354/f4a16020-bfff-11e6-8dfb-a72b2014a8cb.jpg)

**Comment by Carmezim** [comment]
@hsidlagh Are you using Python 3.5 64-bit? If not, that is the issue. Currently TensorFlow 0.12r only supports 64-bit Python distributions on Windows.

**Comment by Carmezim** [comment]
@mcjjin I am assuming you are using a 64-bit python distribution. If you want to have TensorFlow going while the issue is addressed for now, please try:
`pip install tensorflow`

**Comment by mcjjin** [comment]
Thanks  I replaced the Python 3.5 to 64-bit and it works 👍

**Comment by hsidlagh** [comment]
A few hours after me comment, I tried that too and it worked!! However I specified the complete URL. Thanks for the speedy response.
