### ISSUE TITLE
"ERROR: tensorflow/lite/util.cc BytesRequired number of elements overflowed." when benchmarking TFLite model with dynamic input size

### ISSUE THREAD

**Issue by JakubGorski** [tensorflow/tensorflow#62565]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.10

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 20.04.6

### Mobile device

Samsung S23

### Python version

3.7.12

### Current behavior?

I am exporting my tensorflow model to TFLite. I want to be able to run the TFLite model on mobile device GPU with different input shapes. I looked in many places, but I am missing a reliable info in documentation stating how such models should be exported.

For that, I was using the following code:
```
# create model
def get_model(input_shape=(None, None, 3)):
    inputs = tf.keras.Input(shape=input_shape)
    x = tf.keras.layers.Conv2D(
            16, kernel_size=3, padding='same')(inputs)
    x = tf.keras.layers.Conv2D(
            16 * 2, kernel_size=3, padding='same', strides=2)(x)
    x = tf.keras.layers.Conv2D(
            16 * 4, kernel_size=3, use_bias=False)(x)
    x = tf.keras.layers.Conv2D(
            3,  kernel_size=3, padding='same')(x)
    model = tf.keras.Model(inputs, x)
    model.compile(optimizer=tf.keras.optimizers.Adam(), loss="mean_squared_error")
    return model


# Util functions
def save_tflite_model(output_model_path, tflite_model):
    with open(output_model_path, 'wb') as f:
        f.write(tflite_model)
    
def convert_model_from_concrete(model_path, output_model_path, input_shape=(1, None, None, 3)):
    model = tf.saved_model.load(model_path)
    concrete_func = model.signatures[
        tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
    
    concrete_func.inputs[0].set_shape(input_shape)
    
    converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
    converter.experimental_new_converter = True
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.TFLITE_BUILTINS,
        tf.lite.OpsSet.SELECT_TF_OPS 
        ]
    tflite_model = converter.convert()
    print(tf.lite.experimental.Analyzer.analyze(model_content=tflite_model, gpu_compatibility=True))
    save_tflite_model(output_model_path, tflite_model)


#Code for exporting my model to TFLite
model = get_model()
model.save("my_model_dynamic")
convert_model_from_concrete("my_model_dynamic","my_model_dynamic.tflite")
```
Everything works fine, and the model is exported. From the `tf.lite.experimental.Analyzer` I get the following log:
`Your model looks compatibile with GPU delegate with TFLite runtime version 2.10.0.`

I can then locally load the model and run it with any valid shape:
```
interpreter = tf.lite.Interpreter("my_model_dynamic.tflite")
custom_shape = [1, 512, 512, 3]
interpreter.resize_tensor_input(interpreter.get_input_details()[0]['index'], custom_shape)
interpreter.allocate_tensors()
input =  numpy.random.rand(*custom_shape).astype(np.float32)
input_details = interpreter.get_input_details()
interpreter.set_tensor(input_details[0]['index'], input)
interpreter.invoke()
```
However when I use the TFLite benchmark model tool, with the GPU delegate and custom input shape - adb command:
 `./android_aarch64_benchmark_model_plus_flex --graph=./my_model_dynamic.tflite --use_gpu=true --input_layer=input_1 --input_layer_shape=1, 512, 512, 3`
the benchmark fails with the following error:
```
INFO: STARTING!
INFO: Log parameter values verbosely: [0]
INFO: Graph: [./my_model_dynamic.tflite]
INFO: Input layers: [input_1]
INFO: Input shapes: [1,512,512,3]
INFO: Use gpu: [1]
INFO: Loaded model ./my_model_dynamic.tflite
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
INFO: GPU delegate created.
ERROR: tensorflow/lite/util.cc BytesRequired number of elements overflowed.
ERROR: Node number 2 (CONV_2D) failed to prepare.
ERROR: Failed to apply GPU delegate.
```
When I do not set the GPU delegate (execute without the `--use_gpu=true` flag), everything works fine.

Also, when I export my model with a pre-defined dummy shape:
```
model = get_model(input_shape=(16, 16, 3)
model.save("my_model_16")
convert_model_from_concrete("my_model_16","my_model_16.tflite", input_shape=(1, 16, 16, 3))
```
The same adb command I pasted above works well.

Could You clarify why the first approach fails? Is it a bug in the benchmark model app? Or should I just use the second one (with dummy input shapes)?

### Standalone code to reproduce the issue

```shell
The code above is enough to reproduce the problem. Also, I used this native binary of benchmark model tool: https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/release/lite/tools/nightly/latest/android_aarch64_benchmark_model_plus_flex
```

**Comment by JakubGorski** [comment]
@LakshmiKalaKadali did You have a look into this? Are You able to help?

**Comment by LakshmiKalaKadali** [comment]
Hi @pkgoogle , Please look into the issue

Thank You

**Comment by pkgoogle** [comment]
Hi @JakubGorski, it looks like a bug to me since you can do it without the GPU Delegate. I believe somehow the change in input shape is not propagated to the GPU Delegate. @impjdi, can you please take a look? Thanks.

**Comment by pkgoogle** [comment]
Hi @JakubGorski, did you get the binary from somewhere? or did you build android_aarch64_benchmark_model_plus_flex from source? If you built it from source can you let us know the command you used? Also if so, what OS/platform did you use to build the binary? Did you run the configure script prior to building it? If so did you build with Cuda or RocM support? Thanks for all the additional information which will help.

**Comment by JakubGorski** [comment]
Hi @pkgoogle. Thanks for Your help. 

First I used the binary from https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/release/lite/tools/nightly/latest/android_aarch64_benchmark_model_plus_flex.

Then I was trying to get accustomed with the benchmark model code and fix the error so I was building it from source.
I used the command:
`sudo bazel build -c opt  --cxxopt=--std=c++11  --config=android_arm64 --define=xnn_enable_arm_i8mm=false   tensorflow/lite/tools/benchmark:benchmark_model` on **Linux Ubuntu 20.04.6**.
I ran the configure script before - I build it with Cuda support (without RocM).
**Both binaries gave me the same error.**

### I will provide some additional info, maybe will be helpful:
When I use the TFLite benchmark model tool with `--use_gpu=false --use_xnnpack=true --input_layer=input_1 --input_layer_shape=1, 512, 512, 3` , the model created with dynamic input shapes also fails (with the same error).
It only executes correctly with the default delegate. What is more weird, the default delegate is actually also the XNNPACK.

The difference lies in the order of the execution in the TFLite benchmark tool:

1. When default delegate is used, the `interpreter_->ResizeInputTensor(i, input.shape);` call is first, then `interpreter_->AllocateTensors()` is called.
2. When delegate is specified explicitly (gpu, xnnpack etc.), first the `interpreter_->ModifyGraphWithDelegate(delegate)` call is executed. This call invokes the `Subgraph::EnsureMemoryAllocations()` where there is `AllocateTensors()` call.  During this call the error arises.
If I call the `interpreter_->ResizeInputTensor(i, input.shape)` function first (before `interpreter_->ModifyGraphWithDelegate(delegate)`) evertything seems to be working fine.

But maybe the best solution is to export my tflite model with dummy input size? But I read here:
https://github.com/tensorflow/tensorflow/issues/41807#issuecomment-673161339
that it's not the right way.

**Comment by pkgoogle** [comment]
Hi @JakubGorski, a dummy input size/making things static before it enters our ecosystem will generally always work but is a little bit clunky and not the best developer experience, I believe what you are doing should still work but if you need to continue your work ASAP feel free to go ahead with that solution, while we figure this out -- but as always we appreciate your help and the additional information you provided definitely helps. I'll look into this further.

**Comment by pkgoogle** [comment]
Hi @JakubGorski, this is now updated @https://github.com/tensorflow/tensorflow/commit/d6e68d61084f98d6a09151cdc91b59e36e6701b2, please retest your workflow and let us know if it resolves your issue.

**Comment by JakubGorski** [comment]
Hi @pkgoogle, I retested my workflow. The problem is fixed! Thank You for Your help :)

**Comment by pkgoogle** [comment]
Np, @JakubGorski, if you have no other open items regarding this, please feel free to close.
