### ISSUE TITLE
data.ops.iterator_ops.OwnedIterator  flattened in profile session

### ISSUE THREAD

**Issue by annaa-ka** [tensorflow/tensorflow#62574]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.6.2

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04.6 LTS

### Python version

Python 3.8.10

### Bazel version

bazel 5.2.0-1

### GCC/compiler version

gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

### CUDA/cuDNN version

CUDA Version: 12.0

### Current behavior?

When I try to profile train using TensorBoard callback , i got stuck on such problem
https://pastebin.com/Npzjb1x7
and it results in infinite loop because of such problem (https://github.com/OpenMined/PySyft/issues/7042)

### Standalone code to reproduce the issue

```shell
I do not actually know, what to paste as an example, actually I came to ask for help how to debug whether it is a normal behaviour
```

**Comment by SuryanarayanaY** [comment]
Hi @annaa-ka ,

Tf2.6v is quiet older and not supported right now as current version is TF2.15v. Could you please try with latest version as it possible many bugs resolved with each latest version.

Also without code snippet it's hard to analyse the issue.Could you submit the code in the form of a colab gist with latest versions?

**Comment by annaa-ka** [comment]
> Hi @annaa-ka ,
> 
> Tf2.6v is quiet older and not supported right now as current version is TF2.15v. Could you please try with latest version as it possible many bugs resolved with each latest version.
> 
> Also without code snippet it's hard to analyse the issue.Could you submit the code in the form of a colab gist with latest versions?

Unfortunately, I cannot upgrade tf up to 2.15v, as we have a very big project and a lot of checks should be made before the upgrade.

As far as I understood, profiler does some extra checks. Maybe there are any methods that I can use in order to understand what this iterator is used for, or in which function uses it? And we have a custom code for multihost train, i do not know how to paste it into collab

**Comment by SuryanarayanaY** [comment]
Please have a look into the source code and doc string of [OwnedIterator](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/ops/iterator_ops.py#L658) in case it is of any help.
