### ISSUE TITLE
tflite_runtime 2.14 x86_64 wheels distributed on pypi are not pep600 compliant

### ISSUE THREAD

**Issue by mshawcroft** [tensorflow/tensorflow#62581]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.14

### Custom code

No

### OS platform and distribution

linux

### Python version

3.8, 3.9, 3.10, 3.11

### Current behavior?

The pre-built x86_64 wheels for tflite_runtime 2.14 distributed on pypi are not pep600 compliant.

Here is the prefix of the output from auditwheel on one of the 2.14 x86_64 wheels:

`$ auditwheel show tflite_runtime-2.14.0-cp311-cp311-manylinux2014_x86_64.whl

tflite_runtime-2.14.0-cp311-cp311-manylinux2014_x86_64.whl is
consistent with the following platform tag: "manylinux_2_31_x86_64".
`

In this case the filename uses the platform tag "manylinux2014_x86_64", PEP600 https://peps.python.org/pep-0600 defines that:

manylinux2014_x86_64 is now an alias for manylinux_2_17_x86_64

The wheel being distributed depends on glibc-2.31 hence is not compatible with the tag manylinux2014_x86_64.

The solution to this is either to rename the offending wheels with the correct platform tag as indicated by auditwheel, or rebuild the offending wheels in an environment compatible with manylinux2014_x86_64 (for example the docker environment provided by the  pypa manylinux project).

This issue is related to the issue previously reported for aarch64 prebuilt wheels https://github.com/tensorflow/tensorflow/issues/60738

### Standalone code to reproduce the issue

```shell
Here is the prefix of the output from auditwheel on one of the 2.14 x86_64 wheels:

`$ auditwheel show tflite_runtime-2.14.0-cp311-cp311-manylinux2014_x86_64.whl

tflite_runtime-2.14.0-cp311-cp311-manylinux2014_x86_64.whl is
consistent with the following platform tag: "manylinux_2_31_x86_64".
`
```

**Comment by pkgoogle** [comment]
Hi @terryheo, can you do the same as what you did with https://github.com/tensorflow/tensorflow/issues/60738 effectively? Thanks.

**Comment by gaikwadrahul8** [comment]
Hi, @mshawcroft 

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/93

Let us know if you have any questions. Thanks.
