### ISSUE TITLE
TFLite MirrorPad in reflect mode yields incorrect results.

### ISSUE THREAD

**Issue by Pop-korn** [tensorflow/tensorflow#62585]
### System information
- Windows 11 Enterprise
- TensorFlow installed from source
- TensorFlow version 2.12.1
- Python version 3.10.11

### Describe the problem
The TFLite MirrorPad operator in reflect mode produces incorrect results in some cases. For example in this case:
input:
[[0. 1.]
 [2. 3.]] 
  
pad:
[[2 2]
 [2 2]]

mode:
'REFLECT'

output :
[[0. 0. 0. 0. 0. 0.]
 [0. 3. 2. 3. 2. 2.]
 [2. 1. 0. 1. 0. 0.]
 [0. 3. 2. 3. 2. 2.]
 [2. 1. 0. 1. 0. 0.]
 [2. 1. 0. 1. 0. 0.]]

(The output value at [0][0] is also sometimes randomly -1.3739614e-30 instead of 0.0)

I believe the correct output should be:
[[0. 1. 0. 1. 0. 1.]
 [2. 3. 2. 3. 2. 3.]
 [0. 1. 0. 1. 0. 1.]
 [2. 3. 2. 3. 2. 3.]
 [0. 1. 0. 1. 0. 1.]
 [2. 3. 2. 3. 2. 3.]]
Or something similar. 

### Source code / logs
A simple model which demonstrates this issue can be found at https://github.com/Pop-korn/Tmp/blob/main/mirror_pad_bug.tflite

**Comment by LakshmiKalaKadali** [comment]
Hi @Pop-korn,

 Both paddings[D, 0] and [D, 1] must be no greater than input.dim_size(D) as per the [documentation](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/mirror-pad). pad: [[2 2],[2 2]] gives invalid argument error. As well I tried the MirrorPad operation with Reflect mode for a few more examples. Please find the [gist](https://colab.research.google.com/gist/LakshmiKalaKadali/926c177d041d9a7906d55320de778ce4/-62585.ipynb)

Thank You
