### ISSUE TITLE
building tf data for siamese modelling

### ISSUE THREAD

**Issue by pure-rgb** [tensorflow/tensorflow#62588]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15

### Custom code

Yes

### Current behavior?

In this [example](https://keras.io/examples/vision/siamese_contrastive/), raw numpy method is used to build a pipeline for siamese model. I tried to build in tf data api but couldn't do it.  Let's say, I've following folders 

```
folder_1/ 
folder_2/
folder_3/
folder_4/
```

I like to build dataset with multi-input, such that positive-positive and positive-negative pair. I couldn't find any tf ops to make it possible.

![siamese_contrastive_22_0](https://github.com/tensorflow/tensorflow/assets/45315076/e64668e3-6f0a-4b91-937b-6171b6e4578f)

### Standalone code to reproduce the issue

```shell
https://keras.io/examples/vision/siamese_contrastive/
```

**Comment by tilakrayal** [comment]
@pure-rgb,
While I was trying to access the official doc it is providing an error. Could you please provide the colab gist which you are trying and help us to debug the issue in an effective way. Thank you!
