### ISSUE TITLE
Missing gen_array_ops.py file in tensorflow/python/ops folder

### ISSUE THREAD

**Issue by sandeep1404** [tensorflow/tensorflow#62595]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.14

### Custom code

Yes

### OS platform and distribution

Linux ubuntu 22.04

### Python version

3.8

### Current behavior?

I just need where is the gen_array_ops.py file since its is imported in array_ops.py   from tensorflow.python.ops import gen_array_ops

### Standalone code to reproduce the issue

```shell
Hi , the question might be silly but where is the file gen_array_ops.py since in the file we are doing import gen_array_ops and we are importing it from tensorflow.python.ops import gen_array_ops, but i cannot find the file gen_array_ops.py instead i can see the array_ops.py file are they both same? Am i missing something.
```

**Comment by sushreebarsa** [comment]
@sandeep1404 The "gen_array_ops.py" file is indeed not directly present in the TensorFlow source code you might be looking at. It's actually auto-generated during the TensorFlow build process.
You won't find a physical gen_array_ops.py file in the source, it's implicitly created through the build process and made available for import. You can see the generated code in the tensorflow/python/ops directory after building TensorFlow.

Thank you!
