### ISSUE TITLE
Cannot restore large model

### ISSUE THREAD

**Issue by jstaker7** [tensorflow/tensorflow#626]
I'm using tf.train.save.Saver to save my model parameters which come out to be ~1.5GB on disk. When I try to reload the model I get a segmentation fault (this is on a machine with 60GB memory). This also happens when using the option restore_sequentially=True. I found an option to shard the save, but it saves one file per device -- surprisingly there are two files, one is virtually nothing and the other is ~1.5GB for a CPU-only machine, so this didn't help. How can I save my model in such a way that I can get it back into memory?

Update:
I tried saving/loading a smaller model. Surprising the save came out to be ~2GB, which is a larger than the save file of the original model; and this 2GB file loaded fine when restoring the model. So perhaps my original model is really larger than 1.5GB and failed to save properly.

**Comment by girving** [comment]
Oh no!  Looks like this bug got dropped through the cracks.  Regardless of whether the initial save was valid, the load should not segfault.  Do you still have code that can reproduce this problem?

**Comment by jstaker7** [comment]
No worries! Actually, once I found the work-around, I just settled with the smaller model and made that work. I don't think I have the code or models lying around anymore. This was for a competition which has since ended I didn't think I needed those files anymore. Sorry about that!

**Comment by girving** [comment]
Alas!  Sorry we didn't get notice this earlier.  I think we're getting better at not dropping bugs, but there's still a ways to improve.
