### ISSUE TITLE
Tensorflow-Lite CMake Build Fails On Windows With VS Build Generator

### ISSUE THREAD

**Issue by embeddetech** [tensorflow/tensorflow#62609]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15.0 (latest)

### Custom code

No

### OS platform and distribution

Windows 11

### Current behavior?

Tensorflow-lite build fails on Windows using CMake with Visual Studio 2022. In my experience, Tensorflow lite has never properly built with Visual Studio projects, and this is a major oversight.

### Standalone code to reproduce the issue

```shell
Exact steps to reproduce:

git clone https://github.com/tensorflow/tensorflow
mkdir tensorflow_build
cd tensorflow_build
cmake ..\tensorflow\tensorflow\lite
cmake --build .
```

### Relevant log output

```shell
Running the above, from the CMake output, it wasn't clear whether it built successfully or not, it seemed to just stop generating output:

  root_profiler.cc
  profiler.cc
  telemetry_setting_internal.cc
  sparsity_format_converter.cc
  schema_utils.cc
  Generating Code...

After then opening the Visual Studio 2022 project and building, it fails. 

C1083: Cannot open include file 'sys/mman.h': No such file or directory.
LNK1104: Cannot open file '..\..\Debug\tensorflow-lite.lib'
C1083: Cannot open include file: 'Python.h': No such file or directory
C1083: Cannot open include file: 'pybind11/functional.h': No such file or directory
C1083: Cannot open include file: 'Python.h': No such file or directory
C1083: Cannot open include file: 'Python.h': No such file or directory
C1083: Cannot open include file: 'Python.h': No such file or directory
C1083: Cannot open include file: 'unistd.h': No such file or directory
C1083: Cannot open include file: 'getopt.h': No such file or directory


PLEASE help resolve these Visual Studio build problems. I have great need of tflite as well as tflite-micro to build in Visual Studio.
```

**Comment by sushreebarsa** [comment]
@embeddetech Could you ensure that you're not building with options related to Python bindings or Unix-specific features if you don't need them. Please make sure the appropriate requirements for the required dependencies like pybind11 are added to your project settings.
Thank you!

**Comment by embeddetech** [comment]
Hi @sushreebarsa , 
I didn't specify any settings, as shown above, so it would be just building with the default settings. I would expect that building with the default settings should work. 

I have used Tensorflow Lite for many years, and it has never built properly on WIndows. I have had to spend months to get it working. Now I'm getting back to it again, and am much more familiar with CMake, more understanding of what's happening when I follow the build instructions. I followed these instructions:

https://www.tensorflow.org/lite/guide/build_cmake

**Comment by embeddetech** [comment]
Hi @sushreebarsa ,
As shown above and reproduced in the video below, I don't have any necessary flags for my platform. Visual Studio is my default platform, and that is the desired build system. I would expect the build to not fail when using the default configuration. I believe the video below should be reproducible, and represents a build problem with Tensorflow that definitely needs to be resolved. Thanks!


https://github.com/tensorflow/tensorflow/assets/13501663/1e185200-ae09-4ecf-a4fb-4a790efc7317

**Comment by LakshmiKalaKadali** [comment]
Hi @pkgoogle,

Please look into the issue

Thank You

**Comment by pkgoogle** [comment]
Hi @embeddetech,

I was able to build the "tensorflow-lite" solution in VS 2022 community:
![Screenshot 2023-12-27 at 11 14 10 AM (3)](https://github.com/tensorflow/tensorflow/assets/132095473/68667315-0010-40ca-81eb-4b45041e2430)

This was on master, can you try again with master or nightly?

**Comment by embeddetech** [comment]
Hi @pkgoogle,
I tried again and got the same results:

![image](https://github.com/tensorflow/tensorflow/assets/13501663/c6a75d05-80f7-453e-ab49-6c2a3a55ccab)

**Comment by embeddetech** [comment]
https://github.com/tensorflow/tensorflow/assets/13501663/010d6f5e-bad6-44cd-85b2-e826385e76b9

**Comment by pkgoogle** [comment]
Hi @embeddetech, I suspect our difference is due to environmental issues, can you check a couple of things for me:

Check your workloads in VS (Tools -> Get Tools and Features...), here's mine:
![Screenshot 2024-01-05 at 1 13 32 PM (3)](https://github.com/tensorflow/tensorflow/assets/132095473/0207739d-d476-40ed-9e72-8efe5fa44724)

From your error message, it seems python related so ensure you have the Python development one, but it might not hurt to just match mine for now.

I am using a Windows Server 2022 Datacenter OS so that's a possibility... also what is your cmake version? mine is 3.28.1, lastly are you using command prompt or powershell? Thanks for your help.

**Comment by embeddetech** [comment]
Hi @pkgoogle ,
I just tried with Powershell and got the same results. I had not installed the Python workload or Data Science workload, I installed those and got the same results without regenerating the build system (I'm going to try that now). I am using CMake 3.24.2.

**Comment by embeddetech** [comment]
@pkgoogle Update: I installed the latest version of CMake, 3.28.1, did a clean build generation and build from PowerShell, and got the same results:

![image](https://github.com/tensorflow/tensorflow/assets/13501663/e7113418-b5b2-4117-89b6-c1148b00ddf3)

**Comment by embeddetech** [comment]
@pkgoogle I also installed the Python and Data Science workloads for the above test.

**Comment by pkgoogle** [comment]
Hi @embeddetech, have you tried with the "Linux & embedded development with C++" workload, reason being some of your missing headers are GNU C headers/functions/libraries, perhaps that will install it, which solution/project are you opening exactly? Also give me the exact steps for what you are doing in VS ... like:

1. Open <path/to/(project|solution)/from/tf-root>
2. Set to debug
3. Click Green Run Button

Please adjust to what you are actually doing. Thanks for your help.

**Comment by embeddetech** [comment]
Hi @pkgoogle ,
Sorry, I forgot to mention that my "Linux & embedded development with C++" workload is also installed. Please see below for my VS2022 installation config.

![image](https://github.com/tensorflow/tensorflow/assets/13501663/c5d7546c-a73b-4380-8652-746cd9d56be4)

My working test folder begins with C:\tensorflow_test, and I clone the tensorflow with git clone https://github.com/tensorflow/tensorflow as outlined above. My build folder is located at C:\tensorflow_test\tensorflow_build. After running the CMake build generation and build, my build system/Visual Studio solution is located at "C:\tensorflow_test\tensorflow_build\tensorflow-lite.sln". 

1) Open Visual Studio 2022 (in admin mode, for kicks).
2) Open the solution at C:\tensorflow_test\tensorflow_build\tensorflow-lite.sln
3) Confirm that the "ALL_BUILD" project is "Set As Startup Project".
4) Confirm that the build configuration is set to "Debug", platform "x64". 
4) Click "Build->Build Solution".

The build fails as shown by the errors above. I'll dump the build outputs in the message to follow.

**Comment by embeddetech** [comment]
@pkgoogle If you can provide your path to the python.h file on your system, that might help me see wha I'm missing...?

**Comment by pkgoogle** [comment]
Hi @embeddetech, I was actually able to replicate with your exact instructions ... I think I built a different file or built it a different way, for convenience I will summarize the steps here to replicate:

1.
```
git clone https://github.com/tensorflow/tensorflow
mkdir tensorflow_build
cd tensorflow_build
cmake ..\tensorflow\tensorflow\lite
cmake --build .
```

2. Open tensorflow_build\tensorflow-lite.sln in VS Community 2022 with Admin privileges
3. Confirm that the build configuration is set to "Debug", platform "x64".
4. Click "Build->Build Solution".

Hi @terryheo, can you please take a look? Thanks.

**Comment by gaikwadrahul8** [comment]
Hi, @embeddetech 

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/90

Let us know if you have any questions. Thanks.
