### ISSUE TITLE
 Android error: No OpKernel was registered to support Op 'DecodeJpeg' with these attrs

### ISSUE THREAD

**Issue by dongchangzhang** [tensorflow/tensorflow#6260]
hi! there is a mistake when i try to use my model on Android to classify pictures. 

tensorflow_jni.cc:304 Error during inference: Invalid argument: No OpKernel was registered to support Op 'DecodeJpeg' with these attrs
          	 [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, fancy_upscaling=true, ratio=1, try_recover_truncated=false](DecodeJpeg/contents)]]

### Environment info
my tensorflow version is 0.10 and i train pictures by tensorflow/examples/image_retraining/retain.py on ubuntu 16.04 with GPU

how can i solve it? thanks!

**Comment by petewarden** [comment]
Sorry you're hitting problems! You can follow the instructions here to help prepare your model for mobile inference (since DecodeJpeg isn't supported there): https://petewarden.com/2016/09/27/tensorflow-for-mobile-poets/
