### ISSUE TITLE
Problem converting from saved model to tflite model

### ISSUE THREAD

**Issue by NotPjoker05** [tensorflow/tensorflow#62610]
Hi, I'm trying to convert my model (saved in 'saved model' format) to a tflite model but I get an error, this is my code: 

`converter = tf.lite.TFLiteConverter.from_saved_model('saved_model')
tflite_model = converter.convert()

with open('model.tflite', 'wb') as f:
  f.write(tflite_model)`

The error is this:
_**loc(fused["ReadVariableOp:", "sequential_1/conv2d_1/ReadVariableOp@__inference_serving_default_285"]): error: missing attribute 'value'
LLVM ERROR: Failed to infer result type(s).**_

I read the tensorflow page related to the topic and it explains that a refactoring of my model is probably necessary, so I tried to follow the indication but the error I get is the same (my other code is this:)

`
import tensorflow as tf

converter = tf.lite.TFLiteConverter.from_saved_model('saved_model')
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
tflite_model = converter.convert()
open("converted_model.tflite", "wb").write(tflite_model)
`
I hope someone is able to help me, thanks in advance

**Comment by LakshmiKalaKadali** [comment]
Hi @NotPjoker05,

Could you please fill the [template](https://github.com/tensorflow/tensorflow/issues/new/choose) to resolve the issue.
As well try the code with tensorflow 2.15 version if not tried.

Thank You

**Comment by NotPjoker05** [comment]
I'm already using tensorflow 2.15.
### 1. System information

- Windows 10:
- Tensorflow installed with pycharm gui:
- TensorFlow 2.15 :

### 2. Code
Here are my 3 files, Training for training my model, utils provides a list of methods used in training and test is the class where I use my model (predictions work in tensorflow but the method for converting from saved model  to tflite doesn't work)

[Training.txt](https://github.com/tensorflow/tensorflow/files/13665686/Training.txt)
[utils.txt](https://github.com/tensorflow/tensorflow/files/13665687/utils.txt)
[Test.txt](https://github.com/tensorflow/tensorflow/files/13665685/Test.txt)



### 3. Failure after conversion
When I try to convert my model with the code in Test class I receive this error:
loc(fused["ReadVariableOp:", "sequential_1/conv2d_1/ReadVariableOp@__inference_serving_default_285"]): error: missing attribute 'value'
LLVM ERROR: Failed to infer result type(s).

Please help me, I've been stuck on this error for weeks...

**Comment by LakshmiKalaKadali** [comment]
@NotPjoker05 , 
Please provide the input data to reproduce the error.
Thank You

**Comment by NotPjoker05** [comment]
Sure, this is my dataset:
https://mega.nz/file/UrVUEDIK#mHkxTofcMjTWiBMzbALDDbnh1CJkZgpsKTezd5zgXTc 

Thank you very much!

**Comment by LakshmiKalaKadali** [comment]
Hi @NotPjoker05 ,

Sorry for the delay, I have executed the code in colab 2.15. It's working as expected. The  saved model inference and tflite inference(both ```model.tflite``` and ```converted_model.tflite```) are the same as expected. Please find the [gist.](https://colab.research.google.com/gist/LakshmiKalaKadali/879c701a8a66ea624071ecc0c2ddb923/-62610.ipynb)

Thank You

**Comment by adamantivm** [comment]
Just in case it helps others like me struggling with this issue. I realized I was using TensorFlow 2.16.1 , from docker image tensorflow:latest-gpu and that was the source of the problem.
I switched to docker image tensorflow:2.15.0-gpu and the problem went away, all working fine now.

**Comment by israelfelix10** [comment]
@adamantivm Thanks for helping with my project, good idea! Solved this problem.

**Comment by kventinel** [comment]
Same issue.

**Comment by jdsalmonson** [comment]
Same issue here.  2.16.1 crashed, 2.15 worked.

**Comment by fabrizio-indirli** [comment]
I have the same issue on TF 2.16.1 (instead it works on 2.15 as suggested) on my local machine, when running the following script that creates a very small NN in Keras and then converts it to TFlite:

```
import argparse
import keras
import tensorflow as tf

INPUT_SHAPE = (5, 5, 3)
CONV_FILTERS = 6
CONV_KER_SIZE = (2, 2)
FC_UNITS = 4

def build_model():
    model = keras.Sequential(
        [
            keras.Input(shape=INPUT_SHAPE, batch_size=1),
            keras.layers.Conv2D(CONV_FILTERS, CONV_KER_SIZE),
            keras.layers.Flatten(),
            keras.layers.Dense(FC_UNITS, activation='softmax'),
        ]
    )

    model.summary()
    return model

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", "-o", type=str, help="Output filename", default=None)
    parser.add_argument("--totflite", "-t", type=str, help="Output TFlite filename", default=None)
    args = parser.parse_args()
    model = build_model()

    if args.output:
        model.save(args.output)

    if args.totflite:
        converter = tf.lite.TFLiteConverter.from_keras_model(model)
        tflite_model = converter.convert()
        with open(args.totflite, 'wb') as f:
            f.write(tflite_model)
```

**Comment by jake-is-ESD-protected** [comment]
I don't see how switching to 2.15 is any better as #62855 still persists. This is a different problem, but 2.15 is not the solution to intended development, imo.
