### ISSUE TITLE
TensorFlow Lite Build for Amazon Linux

### ISSUE THREAD

**Issue by TaliBojdakYates** [tensorflow/tensorflow#62611]
### Issue type

Support

Hi, I'm currently facing challenges running TensorFlow Lite on my AWS Lambda function due to the specific requirements of the Amazon Linux platform. To fix this I am attempting to build TensorFlow Lite for Amazon Linux using Docker, inspired by an older version I found. Here is the older docker version to complete this:

FROM amazonlinux

WORKDIR /tflite

RUN yum groupinstall -y development
RUN yum install -y python3.7
RUN yum install -y python3-devel
RUN pip3 install numpy wheel pybind11

RUN git clone --branch v2.3.0 https://github.com/tensorflow/tensorflow.git
RUN sh ./tensorflow/tensorflow/lite/tools/make/download_dependencies.sh
RUN sh ./tensorflow/tensorflow/lite/tools/pip_package/build_pip_package.sh
RUN pip3 install tensorflow/tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/dist/tflite_runtime-2.3.0-cp37-cp37m-linux_x86_64.whl

CMD tail -f /dev/null

Is there a way to accomplish the same thing with tensorflow 2.14 and with python 3.9?

I appreitate any help or adivce. Thanks

**Comment by LakshmiKalaKadali** [comment]
Hi @TaliBojdakYates ,

As per this [document](https://www.tensorflow.org/install/source#docker_linux_builds), you can build with tensorflow 2.14 and python 3.9(Compatible).

Thank You
