### ISSUE TITLE
"Build from source" cuDNN documented version is not correct for TF 2.15.0

### ISSUE THREAD

**Issue by mcourteaux** [tensorflow/tensorflow#62626]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.15.0.post1

### Custom code

No

### OS platform and distribution

Ubuntu 22.04

### Python version

3.10

### Current behavior?

https://www.tensorflow.org/install/source#gpu_support_2 reports cudnn version 8.8 is needed. However, after installing that, and running TensorFlow, it complains:

> 2023-12-12 16:48:40.306928: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:447] Loaded runtime CuDNN library: 8.8.0 but source was compiled with: 8.9.4.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile .

So it claims to use 8.9.4 instead of the documented 8.8.0. Either this is a documentation bug, or a CI bug that builds this pip package with the wrong cuDNN version.

I installed with pip:

```
❯ pip3 show tensorflow
Name: tensorflow
Version: 2.15.0.post1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/martijn/.local/lib/python3.10/site-packages
Requires: absl-py, astunparse, flatbuffers, gast, google-pasta, grpcio, h5py, keras, libclang, ml-dtypes, numpy, opt-einsum, packaging, protobuf, setuptools, six, tensorboard, tensorflow-estimator, tensorflow-io-gcs-filesystem, termcolor, typing-extensions, wrapt
Required-by:

```

**Comment by SuryanarayanaY** [comment]
Hi @mcourteaux ,

Thanks for reporting the issue. I have cross checked the setyp.py and its mentioned cudnn required for Tf2.15v as `8.9.4` version.
https://github.com/tensorflow/tensorflow/blob/0b15fdfcb3fddcb4b8a095f26d0f786e316163d7/tensorflow/tools/pip_package/setup.py#L171

We will update it to `8.9` version

**Comment by SuryanarayanaY** [comment]
Hi @mcourteaux ,

The proposed fix has been merged and document also updated. Could you please verify and close the issue. Thanks!
