### ISSUE TITLE
Document that tf.train.Supervisor is deprecated

### ISSUE THREAD

**Issue by taochenshh** [tensorflow/tensorflow#6263]
I am using CUDA 8.0, cuDNN 5.1, ubuntu 16.04, GPU: TitanX, tensorflow r0.12.
And I met some problems when using tf.train.Supervisor in distributed training. I have simplified my  code shown as belown:
```python
from __future__ import print_function
import tensorflow as tf

server = tf.train.Server.create_local_server()
logs_path = "mnist/logs"


global_step = tf.get_variable('global_step', [],
                              initializer=tf.constant_initializer(0),
                              trainable=False)
with tf.name_scope("weights"):
    W1 = tf.Variable(tf.random_normal([784, 100]))
    W2 = tf.Variable(tf.random_normal([784, 100]))

init_op = tf.global_variables_initializer()
print("Variables initialized ...")
sv = tf.train.Supervisor(is_chief=True,
                         logdir=logs_path,
                         global_step=global_step,
                         init_op=init_op,
                         save_model_secs=600)
with sv.managed_session(server.target) as sess:
    while not sv.should_stop():
        print('==============')
sv.stop()
```
The problem is that if I set `logdir` explicitly in tf.train.Supervisor, then the code above will met error like this:`NotFoundError (see above for traceback): Key weights/Variable not found in checkpoint`. But if I comment the lines about defining W1 and W2, then the code could work. So I assume there might be come issues in saving and restoring the checkpoint files in `tf.train.Supervisor` or maybe I did not use `tf.train.Supervisor` correctly.

**Comment by shiyemin** [comment]
tf.Variable will add variable to GLOBAL_VARIABLES, and won't add it to MODEL_VARIABLES. It seem that Superivisor only save MODEL_VARIABLES. I fix this by call tf.contrib.framework.add_model_variable for all varibles defined by tf.Variable.

**Comment by CTTC** [comment]
@shiyemin, Do you mean add following lines:
```python
from __future__ import print_function
import tensorflow as tf

server = tf.train.Server.create_local_server()
logs_path = "mnist/logs"


global_step = tf.get_variable('global_step', [],
                              initializer=tf.constant_initializer(0),
                              trainable=False)
with tf.name_scope("weights"):
    W1 = tf.Variable(tf.random_normal([784, 100]))
    W2 = tf.Variable(tf.random_normal([784, 100]))

for variable in tf.global_variables():
    tf.contrib.framework.add_model_variable(variable)
init_op = tf.global_variables_initializer()
print("Variables initialized ...")
sv = tf.train.Supervisor(is_chief=True,
                         logdir=logs_path,
                         global_step=global_step,
                         init_op=init_op,
                         save_model_secs=600)
with sv.managed_session(server.target) as sess:
    while not sv.should_stop():
        print('==============')
sv.stop()
```
I tried this, still no success.

**Comment by hannes-brt** [comment]
I have the same issue - using `tf.contrib.framework.add_model_variable(variable)` doesn't help.

**Comment by kchen92** [comment]
I'm encountering a similar error using Tensorflow r0.12 and r1.0 as well. For me, the code breaks when I start a new session using `with sv.managed_session(...) as sess`.

**Comment by hannes-brt** [comment]
I actually store the graph before I initialize a session. I tried with and
without a session present and it doesn't make a difference.


--Hannes

**Comment by girving** [comment]
`tf.train.Supervisor` is deprecated, please use `tf.train.MonitoredSession` instead.  Assigning to @martinwicke since we should mark it deprecated in the docs.

**Comment by dsalaj** [comment]
For anyone looking for more information about deprecation of ´tf.trainSupervisor´ and upcoming update to guide, there are some newer comments here: #6604

**Comment by donghwicha** [comment]
Can anyone update document below with a phrase which clearly indicates that Supervisor is deprecated? Please make Tensorflow community united with clear vision to its API usage. 

https://www.tensorflow.org/api_docs/python/tf/train/Supervisor
