### ISSUE TITLE
App crash when update app from playstore because of tenserflow library. 

### ISSUE THREAD

**Issue by ChetanAlmelkar** [tensorflow/tensorflow#62634]
when i updated app from playstore it is going to crash 

Fatal Exception: java.lang.NullPointerException
Attempt to read from null array 
com.optick_employee_mobile_app.FaceRecognitionPythonModule.findNearest (FaceRecognitionPythonModule.java:571)
com.optick_employee_mobile_app.FaceRecognitionPythonModule.recognizeImage (FaceRecognitionPythonModule.java:508)
com.optick_employee_mobile_app.FaceRecognitionPythonModule$2.onSuccess (FaceRecognitionPythonModule.java:144)
com.optick_employee_mobile_app.FaceRecognitionPythonModule$2.onSuccess (FaceRecognitionPythonModule.java:127)

I found this message from crashlytics. this is happening only after update app from playstore.

**Comment by tilakrayal** [comment]
@ChetanAlmelkar,
The error which you are facing is due to the **tflite** file which you are accessing may not be properly added to the assets folder. Could you please try to add and let us know if it resolves the error.
https://github.com/tensorflow/tensorflow/issues/8233.

Thank you!
