### ISSUE TITLE
build tflite gpu for android 

### ISSUE THREAD

**Issue by weinixuehao** [tensorflow/tensorflow#62649]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

latest version

### Custom code

Yes

### Current behavior?
 @s-MacBook-Pro tensorflow % bazel build -c opt --config android_arm64 --copt -Os --copt -DTFLITE_GPU_BINARY_RELEASE --linkopt -s --strip always //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so --verbose_failures
INFO: Reading 'startup' options from /Users//workspace/tensorflow/.bazelrc: --windows_enable_symlinks
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=214
INFO: Reading rc options for 'build' from /Users//workspace/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /Users//workspace/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --features=-force_no_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'build' from /Users//workspace/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/Users//.pyenv/versions/3.10.4/bin/python3 --action_env PYTHON_LIB_PATH=/Users//.pyenv/versions/3.10.4/lib/python3.10/site-packages --python_path=/Users//.pyenv/versions/3.10.4/bin/python3 --action_env ANDROID_NDK_HOME=/Users//Library/Android/sdk/ndk/25.2.9519653 --action_env ANDROID_NDK_VERSION=25 --action_env ANDROID_NDK_API_LEVEL=26 --action_env ANDROID_BUILD_TOOLS_VERSION=32.0.0 --action_env ANDROID_SDK_API_LEVEL=33 --action_env ANDROID_SDK_HOME=/Users//library/Android/Sdk
INFO: Found applicable config definition build:short_logs in file /Users//workspace/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /Users//workspace/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:android_arm64 in file /Users//workspace/tensorflow/.bazelrc: --config=android --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
INFO: Found applicable config definition build:android in file /Users//workspace/tensorflow/.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --dynamic_mode=off --noenable_platform_specific_config --copt=-w --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --define=with_xla_support=false --config=no_tfrt
INFO: Found applicable config definition build:no_tfrt in file /Users//workspace/tensorflow/.bazelrc: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/ir,tensorflow/compiler/mlir/tfrt/ir/mlrt,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ifrt,tensorflow/compiler/mlir/tfrt/tests/mlrt,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/compiler/mlir/tfrt/transforms/mlrt,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/runtime_fallback/test,tensorflow/core/runtime_fallback/test/gpu,tensorflow/core/runtime_fallback/test/saved_model,tensorflow/core/runtime_fallback/test/testdata,tensorflow/core/tfrt/stubs,tensorflow/core/tfrt/tfrt_session,tensorflow/core/tfrt/mlrt,tensorflow/core/tfrt/mlrt/attribute,tensorflow/core/tfrt/mlrt/kernel,tensorflow/core/tfrt/mlrt/bytecode,tensorflow/core/tfrt/mlrt/interpreter,tensorflow/compiler/mlir/tfrt/translate/mlrt,tensorflow/compiler/mlir/tfrt/translate/mlrt/testdata,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils,tensorflow/core/tfrt/utils/debug,tensorflow/core/tfrt/saved_model/python,tensorflow/core/tfrt/graph_executor/python,tensorflow/core/tfrt/saved_model/utils
INFO: Analyzed target //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /Users//workspace/tensorflow/tensorflow/lite/delegates/gpu/BUILD:150:10: Linking tensorflow/lite/delegates/gpu/libtensorflowlite_gpu_delegate.so failed: (Exit 1): clang failed: error executing command (from target //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so)
  (cd /private/var/tmp/_bazel_/16bf2a8366a502c280250866d572e3de/execroot/org_tensorflow && \
  exec env - \
    ANDROID_BUILD_TOOLS_VERSION=32.0.0 \
    ANDROID_NDK_API_LEVEL=26 \
    ANDROID_NDK_HOME=/Users//Library/Android/sdk/ndk/25.2.9519653 \
    ANDROID_NDK_VERSION=25 \
    ANDROID_SDK_API_LEVEL=33 \
    ANDROID_SDK_HOME=/Users//library/Android/Sdk \
    PATH='/Users//Library/Caches/bazelisk/downloads/sha256/672bc71e889658bc6dd1a4433381652771781c572eb49404dea7f44d656a352b/bin:/Users//.nvm/versions/node/v14.19.0/bin:/usr/local/opt/binutils/bin:/Users//.pyenv/shims:/usr/local/opt/node@14/bin:/Users//flutter/bin:/Applications/Blender.app/Contents/MacOS:/usr/local/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Users//.nvm/versions/node/v14.19.0/bin:/usr/local/opt/binutils/bin:/usr/local/opt/node@14/bin:/Users//flutter/bin:/Applications/Blender.app/Contents/MacOS:/usr/local/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/Users//workspace/tensorflow/.venv/bin:/Users//.nvm/versions/node/v14.19.0/bin:/usr/local/opt/binutils/bin:/usr/local/opt/node@14/bin:/Users//flutter/bin:/Applications/Blender.app/Contents/MacOS:/usr/local/bin:/Applications/Sublime Text.app/Contents/SharedSupport/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users//.fig/bin:/Users//.local/bin:/Users//Library/Android/sdk/platform-tools:/Users//Library/Android/sdk/build-tools/32.0.0:/Users//Library/Android/sdk/platform-tools:/Users//Library/Android/sdk/build-tools/32.0.0:/Users//Library/Android/sdk/platform-tools:/Users//Library/Android/sdk/build-tools/32.0.0' \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/Users//.pyenv/versions/3.10.4/bin/python3 \
    PYTHON_LIB_PATH=/Users//.pyenv/versions/3.10.4/lib/python3.10/site-packages \
    TF2_BEHAVIOR=1 \
  external/androidndk/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang @bazel-out/arm64-v8a-opt/bin/tensorflow/lite/delegates/gpu/libtensorflowlite_gpu_delegate.so-2.params)
# Configuration: fd149282ebc4250a9081ac030532bc1fefed26619b31e69aa038c3c3436db5d6
# Execution platform: @local_execution_config_platform//:platform
ld.lld: error: unknown argument '-framework'
ld.lld: error: cannot open CoreFoundation: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so failed to build
INFO: Elapsed time: 0.553s, Critical Path: 0.33s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully

### Standalone code to reproduce the issue

```shell
bazel build -c opt --config android_arm64 --copt -Os --copt -DTFLITE_GPU_BINARY_RELEASE --linkopt -s --strip always //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so --verbose_failures
```

**Comment by tilakrayal** [comment]
@weinixuehao,
Could you please try `bazel clean --expunge` followed by bazel sync and try to run the  **bazel build -c opt --config android_arm64** command for the build. Thank you!
