### ISSUE TITLE
Freeze weights during training

### ISSUE THREAD

**Issue by BingzheWu** [tensorflow/tensorflow#6264]
Is there any solution to freeze weights? For example, I want to keep some weights unchanged when them satisfy some condition(like weight<0.5) during training.

**Comment by Carmezim** [comment]
tf.Variable(my_weights, trainable=False) will maintain the weights unchangeable during training.

**Comment by BingzheWu** [comment]
> tf.Variable(weights, trainable=False) will maintain weights unchangeable during training.
Maybe this StackOverflow answer will help.
Further info about tf.Variable class see here.

Thank you!  This operation is useful to keep the declared variable keep unchanged, but I want to 
keep some parameters in this variable keep unchanged, others still can be trained.

**Comment by ppwwyyxx** [comment]
`x = tf.select(x < 0.5, tf.stop_gradient(x), x)`

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow, which we also monitor. Please ask it there and tag it with the `tensorflow` tag

**Comment by harchankoj** [comment]
@andydavis1 I believe @BingzheWu is asking the same question I have over in StackOverflow. There is no resolution to this issue on StackOverflow so I have posted the following:

[http://stackoverflow.com/questions/42517926/how-to-freeze-lock-weights-of-one-tensorflow-variable-e-g-one-cnn-kernel-of-o](url)

Please consider reopening or responding in StackOverflow. Several people have this same question.

**Comment by arnaghizadeh** [comment]
I have the same problem.

**Comment by pramod2157** [comment]
With the tensorflow 1.0 onward versions there is tf.layers api where I can mention trainable=False

**Comment by deepmeng** [comment]
How to dynamically freeze and unfreeze weights in tensorflow training? @Carmezim @BingzheWu @arnaghizadeh

**Comment by FrankLiOnLine** [comment]
This is a possible answer I found on stackoverflow, with this mehod you can freeze a specific neural in your network. 
[https://stackoverflow.com/questions/44274288/freeze-parts-of-neural-net-in-tensorflow](url)

**Comment by deepmeng** [comment]
@FrankLiOnLine Thank you, sir!

**Comment by Sheethal00** [comment]
hi @BingzheWu 

Did u find any solution to your problem, even i am facing the same issue

**Comment by sampathrajapaksha** [comment]
Is there any solution to this? I have a similar issue which i want to freeze zero weights of a pruned model during model retraining
