### ISSUE TITLE
ERRO AO COMPILAR NO VSCODE PLATFORM.IO cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.c.d: No such file or directory

### ISSUE THREAD

**Issue by DevIoTEduardo** [tensorflow/tensorflow#62657]
dered.c.o
Compiling .pio\build\esp32dev\src\EloquentTinyML-2.4.0\src\tensorflow_arm\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\ConvolutionFunctions\arm_nn_mat_mult_kernel_s8_s16.c.o
src/EloquentTinyML-2.4.0/src/tensorflow_arm/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.c:1: fatal error: 
opening dependency file .pio/build/esp32dev/src/EloquentTinyML-2.4.0/src/tensorflow_arm/tensorflow/lite/micro/tools/make/downloads/cmsis/CMSIS/NN/Source/ConvolutionFunctions/arm_depthwise_separable_conv_HWC_q7_nonsquare.c.d: No such file or directory
 #if !defined(ESP32)

compilation terminated.
*** [.pio\build\esp32dev\src\EloquentTinyML-2.4.0\src\tensorflow_arm\tensorflow\lite\micro\tools\make\downloads\cmsis\CMSIS\NN\Source\ConvolutionFunctions\arm_depthwise_separable_conv_HWC_q7_nonsquare.c.o] Error 1

**Comment by LakshmiKalaKadali** [comment]
Hi  @DevIoTEduardo,

Could you please submit the ticket in the attached [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=&projects=&template=tensorflow_issue_template.yaml) with all the required details.

Thank You
