### ISSUE TITLE
Unable to build TF 2.14

### ISSUE THREAD

**Issue by bergentruckung** [tensorflow/tensorflow#62669]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.14

### Custom code

No

### OS platform and distribution

Redhat Enterprise Linux 8.9

### Mobile device

-

### Python version

3.11.4

### Bazel version

6.3.2

### GCC/compiler version

clang 16.0.6

### CUDA/cuDNN version

CUDA 12.2, cuDNN 8.9.0

### GPU model and memory

Nvidia A100 80GB PCIe

### Current behavior?

Current: Building from source fails after a while (error is captured in `relevant log output` section).
Expected: Builds to proceed and I get a wheel file that I can install

### Standalone code to reproduce the issue

```shell
* Git clone upstream tensorflow repo from Github and checkout r2.14 branch
* Run `./configure` and apply the following:

Build TF with CUDA: yes
Build TF with ROCm: no
Build TF with TensorRT: no
Specify compute capability: 8.0
Use clang as compiler: yes
Specify optimization flags: -msse4.2 -mavx2 -mfma -march=sandybridge -mtune=broadwell 
```
* Run `bazel build //tensorflow/tools/pip_package:build_pip_package` -- this fails after a while
```


### Relevant log output

```shell
Repository rule _tf_http_archive defined at:
  /local/tf_tensorflow/third_party/repo.bzl:89:35: in <toplevel>
ERROR: /local/tf_tensorflow/tensorflow/core/kernels/BUILD:7953:18: While resolving toolchains for target //tensorflow/core/kernels:libtfkernel_sobol_op.so: invalid registered toolchain '@local_jdk//:runtime_toolchain_definition': no such package '@local_jdk//': error globbing [lib/**] - [lib/missioncontr
ol/**, lib/visualvm/**] op=FILES: /home/.cache/bazel/_bazel/4167dbe79c65128bd2e3a1505c6f80c3/external/local_jdk/lib/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64
/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/amd64/tzdb.dat (Too many levels of symbolic links)
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted:
INFO: Elapsed time: 810.131s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (263 packages loaded, 3936 targets configured)
    currently loading: @ml_dtypes//
    Fetching repository @pypi_portpicker; Restarting.
    Fetching repository @pypi_requests; Restarting.
    Fetching repository @pypi_h5py; Restarting.
    Fetching repository @pypi_packaging; Restarting.
    Fetching repository @pypi_tensorboard; Restarting.
    Fetching repository @pypi_keras; Restarting.
    Fetching repository @pypi_numpy; Restarting.
    Fetching repository @pypi_tensorflow_estimator; Restarting. ... (17 fetches)
```

**Comment by SuryanarayanaY** [comment]
Hi @bergentruckung ,

If you are adding any optimizations of your own you need to add `--config=opt` to the bazel build command like below.


`bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`

Could you try above command and let us know outcome. Thanks!

**Comment by bergentruckung** [comment]
Thanks, I tried the above as well. I get the exact same error.

**Comment by tilakrayal** [comment]
@bergentruckung,
Apologies for the delay, there might be an issue with the tensorflower v2.14. Could you try **bazel clean --expunge** followed by bazel sync.

Also please try to install the latest tensorflow v2.17 and let us know if you are facing the same issue. 
https://www.tensorflow.org/install/source

Thank you!
