### ISSUE TITLE
Golang  TensorFlow2.5.0  have a memory leak on reloading model

### ISSUE THREAD

**Issue by LoveVsLike** [tensorflow/tensorflow#62667]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf2.5.0

### Custom code

Yes

### Current behavior?

I am a user of tfgo, and I encountered a bug in tfgo. When the model is reloaded, there is a memory leak, But when I see tfgo source code, I find this bug is from tf, Because I find TF C.TF_DeleteSession is not work

### Standalone code to reproduce the issue

```shell
I find tf lib C.TF_DeleteSession(s.c, status.c) is not work
```

**Comment by Venkat6871** [comment]
Hi **@LoveVsLike** ,
Could you try to update tensorflow older version to the latest version. After that make sure the latest version of tfgo.Before reloading the model, make sure that any existing TensorFlow sessions are properly closed or deleted. You can explicitly close a session in TensorFlow using sess.Close(). 
If you are facing the same issue after these changes please feel free to ask. And provide code snippet also it is help us to reproduce your issue.

Thank you!
