### ISSUE TITLE
Request for distribution of prebuilt headers and libraries

### ISSUE THREAD

**Issue by kmalakoff** [tensorflow/tensorflow#6267]
I have been working on a port of [tensorflow to Node.js](https://github.com/kmalakoff/tensorflow-node) and when the node module is installed, it currently requires a time consuming build step and the user to set up bazel. Here is how I trigger the install:  [script](https://github.com/kmalakoff/tensorflow-node/blob/master/scripts/build_tensorflow.sh) and [vendor folder structure](https://github.com/kmalakoff/tensorflow-node/tree/master/vendor).

As part of an investigation into this, I noticed that as part of [installing the python package](https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html), tensorflow is distributing the libraries...for example inside of https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0-py2-none-any.whl.

<img width="691" alt="screen shot 2016-12-12 at 12 19 34 pm" src="https://cloud.githubusercontent.com/assets/756520/21115291/7c90ada0-c065-11e6-9322-c38d9a2277bf.png">

I was wondering if the tensorflow team would be open to building and hosting the headers and libraries for a variety of platforms and configurations (eg. cuda, no cuda) that can be downloaded and directly linked to in C++?

FYI: I have also opened an issue with bazel (https://github.com/bazelbuild/bazel/issues/2206) about their plans for prebuilt asset distribution tooling.

**Comment by gunan** [comment]
CC @asimshankar

**Comment by asimshankar** [comment]
I am planning on distributing the library and header file for the TensorFlow [C API](www.tensorflow.org/code/tensorflow/c/c_api.h), which is intended for building other language bindings on ([Go](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/go), [Java](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java), [Rust](https://github.com/tensorflow/rust), [Haskell](https://github.com/tensorflow/haskell) etc.). Hopefully, that will be sufficient for the Node.js port as well? Our intention is for the C API to be sufficient for building language bindings (as in the [HOWTO](https://www.tensorflow.org/how_tos/language_bindings/).

I wasn't planning on binary releases for C++, as it may be hard to guarantee ABI compatibility.

I have to work on some guarantees around libc version compatibility, but I started on tentative scripts to build releases for [linux](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build/linux) and [OS X](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build/osx).

Will update this issue when we start producing those binary artefacts along with the release.

**Comment by kmalakoff** [comment]
@asimshankar sounds good. If both could be distributed, I would use the C++ API.

I have performed some basic steps of implementing a port to Node.js with both the [C](https://github.com/kmalakoff/tensorflow-node/tree/master/src/native/c) and [C++](https://github.com/kmalakoff/tensorflow-node/tree/master/src/native/cc) APIs. Definitely, C++ is a much better API when you can use it (I could when using Nan for Node.js, but probably more of an exception in porting approaches) and it looks like the team might be [starting with C++ and then porting back to C](https://github.com/tensorflow/tensorflow/issues/6268) so it might be more complete sooner, but since we are talking about official headers and libraries distributed for official releases, C++ and C feature sets should hopefully be in sync at each release. 

I'm not sure how header and library dependencies for eigen, protobuf, etc would be provided, but I would need a way to ensure I was using the same versions as tensorflow was built with.

I did raise an issue to [bazel](https://github.com/bazelbuild/bazel/issues/2206) and am a bit surprised about coming back to C / C++ after 15+ years away that there isn't a common package manager for this ecosystem. However you decide to distribute these, it would be great to be as low friction as possible to use including setting up build environments and managing external library dependencies.

I'm really looking forward to this!

**Comment by asimshankar** [comment]
FYI, with TensorFlow 1.0 we've started releasing binary artifacts for the TensorFlow C library in URLs of the form: `https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-${TF_TYPE}-${OS}-${ARCH}-${VERSION}.tar.gz`

For example:
- https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-darwin-x86_64-1.0.0.tar.gz
- https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-1.0.0.tar.gz

Currently, we only build releases for linux and darwin for x86_64. These are built with the BUILD rules in [`tensorflow/tools/lib_package`](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/lib_package)
so can be built for other platforms as well.

For C++ we are trying to carve out an minimal API that doesn't depend on a lot of internal headers and are trying to package that. No ETA yet (CC @skyewm)

**Comment by martinwicke** [comment]
I will close this issue. Please open a new one if there are aspects that are not solved by the binaries we currently distribute.
