### ISSUE TITLE
Android C API Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter

### ISSUE THREAD

**Issue by Qinlong275** [tensorflow/tensorflow#62680]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tflite 2.12.0

### Custom code

Yes

### OS platform and distribution

mac apple m1; android studio

### Mobile device

HuaWei Nova6

### Current behavior?

I run my custom tflite model(have select_op) on android studio use C API(libtensorflowlite_c.so build from sourcecode use android ndk, if i build the /tensorflow/lite dir link tensorflow-lite.so will occur same error !!!!!!!!),  and I have linked the libtensorflowlite_flex.so(build follow the https://www.tensorflow.org/lite/guide/ops_select)
But occur these error:

E Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select
2023-12-19 12:44:34.993 3039-5562 tflite com...cent.karaoke.tNetInterpretApp E Node number 622 (FlexDepthwiseConv2dNative) failed to prepare.
2023-12-19 12:44:34.993 3039-5562 tflite com...cent.karaoke.tNetInterpretApp E Failed to allocate tensors!

I think maybe the AcquireFlexDelegate has not work?, I find the source code, the AcquireFlexDelegate looks like a attribute((weak)) symbal. I have loaded the libtensorflowlite_gpu_jni.so before start the interpret.
<img width="1287" alt="企业微信20231225-164009@2x" src="https://github.com/tensorflow/tensorflow/assets/30921763/4c6a83d8-8d74-4170-af39-3675c5f68e72">
<img width="1326" alt="企业微信20231225-164111@2x" src="https://github.com/tensorflow/tensorflow/assets/30921763/c408493c-3513-4034-b7c7-2de3e272d144">
I debug the project, AcquireFlexDelegate function will run in to the default weak define in interpreter_builder.cc. So it may be the really redefine AcquireFlexDelegate not work in libtensorflowlite_flex.so.

### Standalone code to reproduce the issue

```shell
CMakeLists.txt:
if(BUILD_TFLITE_C_BY_SOURCE)
        SET(TNET_TENSORFLOW_LITE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../../3rdparty/TNetTensorflow/tensorflow/lite/c")
       //if i build the /tensorflow/lite dir link tensorflow-lite.so will occur same error !!!!!!!!
        add_subdirectory(
                ${TNET_TENSORFLOW_LITE_PATH}
                "${CMAKE_CURRENT_BINARY_DIR}/tnet_tensorflow_lite_c"
        )
    endif()

    add_library(TFLITE_FLEX SHARED IMPORTED)
    set_target_properties(TFLITE_FLEX PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/libs/android/${ANDROID_ABI}/libtensorflowlite_flex.so)
    target_link_libraries(TNET_TFLITE
            TFLITE_FLEX)


    #依赖的三方库
    if(BUILD_TFLITE_C_BY_SOURCE)
        target_link_libraries(TNET_TFLITE
                tensorflowlite_c
                )
    else()
        add_library(TFLITE_CORE SHARED IMPORTED)
        set_target_properties(TFLITE_CORE PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/libs/android/${ANDROID_ABI}/libtensorflowlite_c.so)
        target_link_libraries(TNET_TFLITE
                TFLITE_CORE
                )
    endif()

Ndk generate configure_command file cmake commad:
/Users/qinlong/Library/Android/sdk/cmake/3.22.1/bin/cmake \
  -H/Users/qinlong/aiInterpret/FrontAIFrameworkBack/FrontAIFramework/test/android/lib_tnet_interpret/lib_tnet_interpretsdk/jni \
  -DCMAKE_SYSTEM_NAME=Android \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DCMAKE_SYSTEM_VERSION=21 \
  -DANDROID_ABI=arm64-v8a \
  -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
  -DANDROID_NDK=/Users/qinlong/Library/Android/sdk/ndk/22.1.7171670 \
  -DCMAKE_ANDROID_NDK=/Users/qinlong/Library/Android/sdk/ndk/22.1.7171670 \
  -DCMAKE_TOOLCHAIN_FILE=/Users/qinlong/Library/Android/sdk/ndk/22.1.7171670/build/cmake/android.toolchain.cmake \
  -DCMAKE_MAKE_PROGRAM=/Users/qinlong/Library/Android/sdk/cmake/3.22.1/bin/ninja \
  "-DCMAKE_CXX_FLAGS=-std=c++17 -fno-ident -frtti -fexceptions" \
  -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/qinlong/aiInterpret/FrontAIFrameworkBack/FrontAIFramework/test/android/lib_tnet_interpret/lib_tnet_interpretsdk/build/intermediates/cxx/Release/16452w4l/obj/arm64-v8a \
  -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/Users/qinlong/aiInterpret/FrontAIFrameworkBack/FrontAIFramework/test/android/lib_tnet_interpret/lib_tnet_interpretsdk/build/intermediates/cxx/Release/16452w4l/obj/arm64-v8a \
  -B/Users/qinlong/aiInterpret/FrontAIFrameworkBack/FrontAIFramework/test/android/lib_tnet_interpret/lib_tnet_interpretsdk/.cxx/Release/16452w4l/arm64-v8a \
  -GNinja \
  -DANDROID_ARM_NEON=TRUE \
  -DANDROID_PLATFORM=android-19 \
  -DANDROID_TOOLCHAIN=clang \
  -DANDROID_STL=c++_static \
  -DCMAKE_BUILD_TYPE=Release \
  -DTFLITE_ENABLE_XNNPACK=ON \
  -DTFLITE_ENABLE_GPU=ON \
  -DTFLITE_ENABLE_BENCHMARK=OFF \
  -DBUILD_TFLITE_BENCHMARK_BY_SOURCE=OFF \
  -DBUILD_TFLITE_C_BY_SOURCE=ON
```

**Comment by Qinlong275** [comment]
In my another android project, I run the TFLite benchmark code link the  libtensorflowlite_flex.so, and run benchmark with the model(hava select op)automatic use FlexDelegate success. I can not find why this project can success but the first project is fail.

if(BUILD_TFLITE_BENCHMARK_BY_SOURCE)
    SET(TNET_TENSORFLOW_LITE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../../../3rdparty/TNetTensorflow/tensorflow/lite")
    add_subdirectory(
            ${TNET_TENSORFLOW_LITE_PATH}
            "${CMAKE_CURRENT_BINARY_DIR}/tnet_tensorflow_lite"
    )
endif()



if(CMAKE_SYSTEM_NAME MATCHES "Android")
    add_library(TFLITE_FLEX SHARED IMPORTED)
    set_target_properties(TFLITE_FLEX PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/libs/android/${ANDROID_ABI}/libtensorflowlite_flex.so)
    target_link_libraries(TNET_TFLITE_BENCHMARK
            TFLITE_FLEX)

    #依赖的三方库
    if(BUILD_TFLITE_BENCHMARK_BY_SOURCE)
        target_link_libraries(TNET_TFLITE_BENCHMARK
                benchmark_model
                )
    else()
        add_library(TFLITE_BENCHMARK SHARED IMPORTED)
        set_target_properties(TFLITE_BENCHMARK PROPERTIES IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/libs/android/${ANDROID_ABI}/libbenchmark_model.so)
        target_link_libraries(TNET_TFLITE_BENCHMARK
                TFLITE_BENCHMARK
                )
    endif()
elseif (CMAKE_SYSTEM_NAME MATCHES  "iOS")

else()

endif()

**Comment by pkgoogle** [comment]
Hi @Qinlong275, are you able to export your project here? That'll be the easiest, alternatively we can try reproducing with just your model. Feel free to reduce the model to enough to just reproduce the case if you can. Thanks for your help.
