### ISSUE TITLE
TFLite cannot correctly recognize images

### ISSUE THREAD

**Issue by B-JackMao** [tensorflow/tensorflow#62685]
![QQ截图20231223182255](https://github.com/tensorflow/tensorflow/assets/57884144/b8ce6b80-7551-4c06-ab32-317559255a5e)
When I perform inference on a model with TFLite's CPU backend (without any delegates), the image can be correctly recognized if I run the operators on the left first and then run the operators on the right. However, if I run the operators on the right first and then run the operators on the left, the image cannot be correctly recognized. Is it because the context of operators is determined during initialization? How can I solve this problem? I can ensure that the .tflite model file is not problematic.

**Comment by tilakrayal** [comment]
@B-JackMao,
Could you please share a reproducible code that supports your statement and also the tensorflow version you are using, so that the issue can be easily understood? Thank you!

**Comment by B-JackMao** [comment]
I am using TensorFlow Lite version 2.9.0, and I suspect that the context environment has changed. When I put one of the parts into a GPU delegate there is no problem.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月26日(星期二) 晚上8:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tensorflow/tensorflow] TFLite cannot correctly recognize images (Issue #62685)





 
，
您能否分享一个支持您的陈述以及您正在使用的 tensorflow 版本的可重现代码，以便轻松理解该问题？谢谢！
 
-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
您收到此邮件是因为有人提到您。Message ID: ***@***.***&gt;

**Comment by pkgoogle** [comment]
Hi @B-JackMao, we can't really help you if you don't provide more context. Can you provide code which shows this problem? i.e. one function which does the left side first, another which does the right side first. Show that the loss or how you are measuring that an image is "correctly recognized" is different. Can you upload your .tflite model as well? Thanks for your help.
