### ISSUE TITLE
Lack of wheel file for tensorflow 1.x versions for aarch64 architecture machines.

### ISSUE THREAD

**Issue by akashKaitCaastle** [tensorflow/tensorflow#62695]
### Issue type

Feature Request

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

1.15

### Custom code

Yes

### OS platform and distribution

Amazon Linux 2

### Mobile device

Amazon Linux 2

### Python version

3.7

### Bazel version

0.26.1

### GCC/compiler version

7.3.1

### Current behavior?

As mentioned, there's a lack of aarch64 architecture wheel file for tensorflow 1.x version. I have built v1.15.0 from source after a few patches to make the wheel for aarch64. Would be really great of this community, if they can upload this wheel file to pypi so that it is accessible through "pip install tensorflow==1.15" for my team as well anyone else who would like to use tensorflow 1.x in this architecture. I have attached the patch file which you can use to build the code and generate the wheel file. If possible, please upload that wheel file to the pypi.
[tensorflow1_15_aarch64.patch](https://github.com/tensorflow/tensorflow/files/13771176/tensorflow1_15_aarch64.patch)

The change in setup.py is because, when i install the wheel file generated through "pip install tensorflow.whl -t lib" to my lib folder like this I get only header files in my tensorflow_core folder. Only if i "--upgrade" to the command, then I'm able to get the lib files. To change this behaviour, I changed the path for header files.

### Standalone code to reproduce the issue

```shell
NA
```

**Comment by tilakrayal** [comment]
@akashKaitCaastle,
We see that you are using tf version 1.15, 1.x is not actively supported, please update to 2.x.
I can see the tensorflow pypi wheels are available for aarch64 [tensorflow-aarch64 · PyPI](https://pypi.org/project/tensorflow-aarch64/#files) for tensorflow v2.15. Could you please try by using pip install tensorflow-aarch64. 
Thank You!

**Comment by akashKaitCaastle** [comment]
Hey, the reason why we require tensorflow 1.x version is that, we are using [tensorrec](https://github.com/jfkirk/tensorrec) which is a recommendation algo based upon tensorflow and it strictly requires versions >1.7 and <1.15
Seems like tensorrec project is not actively supported anymore and we are forced to use TF 1.x versions. Till now we've been using i386 machines for the job, but now we are shifting to aarch64 machines, hence facing this issue. We are trying to get away from tensorrec and use more active algorithms for our usecase, but for now we require TF 1.x wheel file in aarch64.

**Comment by xvdp** [comment]
I also just hit this installation problem. While further dev on version 1.15 shouldn't be done, there is a lot of legacy code that requires it, personal projects, third party and even gits on deepmind github that have not been updated.

**Comment by xvdp** [comment]
a comment on my comment - even though pip only installs > 2.0, mamba repoquery search tensorflow shows a whole bunch of distributions from - 0.7 to 1.14, as well as 2.0 + 
Ill have to docker it as it 1.14 as it seems 1.14 requires python 3.6

still, keeping at least 1.15 in pypi would be preferred. implementations with it that may be required for reproducibility are everywhere still.

**Comment by xvdp** [comment]
docker pull tensorflow/tensorflow:1.15.0-gpu
its all there. dont deprecate that one please

**Comment by akashKaitCaastle** [comment]
@xvdp is it possible to use this tensorflow wheel file outside of docker container?

**Comment by xvdp** [comment]
> @xvdp is it possible to use this tensorflow wheel file outside of docker container?

That would be crazy, no? it requires python 3.6 and CUDA 10, I think. If you have the machine set up like that, maybe you can look at the Dockerfile and follow the installation steps.  I think it would be a waste of time anyway. Time better spent, figuring out how to install and use docker

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
