### ISSUE TITLE
GPU kernel for tf.random_shuffle

### ISSUE THREAD

**Issue by jramapuram** [tensorflow/tensorflow#6269]
There doesn't seem to be a `tf.random_shuffle` impl for the GPU. Some of the work I do can utilize a GPU shuffle.

Running:
  - tf0.12RC0
  - CUDA8.0
  - CUDNN5.1
  - Titan X (non-pascal)

```bash
InvalidArgumentError (see above for traceback): Cannot assign a device to node 'RandomShuffle_8': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: RandomShuffle_8 = RandomShuffle[T=DT_FLOAT, seed=87654321, seed2=703433, _device="/device:GPU:0"](transpose_16)]]
```

**Comment by EloiZ** [comment]
When i run this code snippet: 
```                                                            
import tensorflow as tf                                                         
                                                                           
a = tf.placeholder(tf.float32, shape=[2, 4])                                    
w = tf.Variable(tf.random_uniform([4, 4], -1., 1.), name="w")                   

b = tf.matmul(a, w)                                                             
c = tf.random_shuffle(b)                                                        

loss = tf.reduce_sum(c)                                                     
opt = tf.train.GradientDescentOptimizer(0.1).minimize(loss)                     
                                                                                       
init_op = tf.global_variables_initializer()                                     
with tf.Session() as sess:                                                      
    init_op.eval()                                                              
    print(sess.run(opt, feed_dict={a: a_v, b: b_v}))
```
It gives this error:  `LookupError: No gradient defined for operation 'RandomShuffle' (op type: RandomShuffle)` which seems to mean that we cannot use the `RandomShuffle` op in a differentiable graph?

**Comment by jramapuram** [comment]
@EloiZ : Yes, I see this as well. However, I raised this ticket merely to have a GPU kernel for shuffle.

Most of the time you probably aren't going to randomly shuffle in the middle of a graph and will probably do it at the beginning of the graph (eg: data shuffling). It "should" be possible to apply the same logic of grabbing gradients in the slicing operators to the random shuffle operator if you do need gradients for this op.

My specific use case is that I'm trying to implement random permutations (and avoid the creation/storing of many permutation matrices).

**Comment by EloiZ** [comment]
Yeah, sorry if that sounds like a "thread hack", i thought the problems were related.
Yes I need gradient for that op to get negative examples. That is I want to have sim(a, b) > sim(c, b) where c is "negative sampled" of a: c = tf.random_shuffle(b). maybe there is a better way for doing this?

**Comment by ekelsen** [comment]
@EloiZ : I would open a separate ticket about needing a gradient for random_shuffle.

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.

**Comment by jramapuram** [comment]
@tfboyd : this is a feature request

**Comment by ekelsen** [comment]
Yeah, this is a valid feature request.  Not sure how soon it will happen, but I think we can leave it open.

**Comment by tfboyd** [comment]
No problem.  There will be a second pass to clean up FRs and put them in a different location.

**Comment by tatatodd** [comment]
In the meantime, I'll say this is 'contributions welcome'.

**Comment by boluoweifenda** [comment]
It seems like tf.tensor doesn't support slice in this way:   a[ : , [3,1,2], :, :]  or a[ :, b, :, :],  b = np.array([3,1,2]) , but numpy.array do.   Is there any alternative method ?

**Comment by cuixue** [comment]
@EloiZ  i meet the same problem, how you deal with it

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by tkngoutham** [comment]
Is there any chance that this issue is resolved ?

**Comment by lw3259111** [comment]
How can  solve the problem?

**Comment by mycal-tucker** [comment]
> @EloiZ : I would open a separate ticket about needing a gradient for random_shuffle.

Was this ticket opened? I'd love it if I could including shuffling as part of a layer in my neural net, but I don't see any immediately relevant hits on google for this particular issue being implemented. That said, I'm also not sure how one would compute the gradient through a random shuffle, so maybe there's a reason the feature request never got created.

**Comment by danijar** [comment]
Workaround with GPU gradients:

```python
tf.gather(batch, tf.random.shuffle(tf.range(tf.shape(batch)[0])))
```

**Comment by feynmanyunlongma** [comment]
> Workaround with GPU gradients:
> 
> ```python
> tf.gather(batch, tf.random.shuffle(tf.range(tf.shape(batch)[0])))
> ```

It works for cpu too, thank you!
