### ISSUE TITLE
the cuda version of my laptop is 12.1, but I can not find the correspond tensorflow-gpu

### ISSUE THREAD

**Issue by yoyoengineer** [tensorflow/tensorflow#62696]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

...

### Custom code

Yes

### Current behavior?

the cuda version of my laptop is 12.1, but I can not find the correspond tensorflow-gpu version from
https://tensorflow.google.cn/install/source_windows?hl=zh-cn#gpu
![Snipaste_2023-12-26_20-05-37](https://github.com/tensorflow/tensorflow/assets/37788019/b446545f-214e-43ba-a30f-3e01986b05e8)
![Snipaste_2023-12-26_20-05-51](https://github.com/tensorflow/tensorflow/assets/37788019/9d201006-ed48-4da0-a275-8211bfb4069b)

### Standalone code to reproduce the issue

```shell
...
```

**Comment by alexdconf** [comment]
From this webpage (https://www.tensorflow.org/install/source_windows), I see the following notice:
![image](https://github.com/tensorflow/tensorflow/assets/102566941/d3593a06-6226-4e09-88a2-d88a006dba61)
I think if you want to leverage a GPU using CUDA 12 on that laptop, you have to try WSL2.

**Comment by Venkat6871** [comment]
Hi **@yoyoengineer**,
It is clearly there on note, GPU support on native-Windows is only available for 2.10 or earlier versions, starting in TF 2.11, CUDA build is not supported for Windows. For using TensorFlow GPU on Windows, you will need to build/install TensorFlow in WSL2 or use tensorflow-cpu with TensorFlow-DirectML-Plugin.
Could you go through it once again [link](https://www.tensorflow.org/install/source_windows).

Thank you!

**Comment by Deweyave** [comment]
Like 10 minutes

[Infinito “BeenADonSlim” Azul](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=2f3w4q)	[2f3w4q]
Jameo Nitti

On January 12, 2024 at 1:49 GMT, google ml butler bot ***@***.***> wrote:

Are you satisfied with the resolution of your issue?
[Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/62696)
[No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/62696)
