### ISSUE TITLE
I can't install tensorflow lower than 2.13

### ISSUE THREAD

**Issue by unolife** [tensorflow/tensorflow#62693]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.13

### Custom code

No

### OS platform and distribution

macOS Ventura 13.5.2

### Current behavior?

If I type pip install tensorflow==2.10.1 in my mac, I get this 
'ERROR: Could not find a version that satisfies the requirement tensorflow==2.10.1 (from versions: 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0)
ERROR: No matching distribution found for tensorflow==2.10.1'

### Standalone code to reproduce the issue

```shell
pip install tensorflow==2.10.1
```

### Relevant log output

```shell
ERROR: Could not find a version that satisfies the requirement tensorflow==2.10.1 (from versions: 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0)
ERROR: No matching distribution found for tensorflow==2.10.1
```

**Comment by mihaimaruseac** [comment]
I think this is because you are on an ARM Mac (M1?) and ARM support has been added on 2.13.

**Comment by sushreebarsa** [comment]
@unolife TensorFlow 2.13 introduced official pre-built wheels for Apple Silicon Macs, making installation simpler. It might be a reason why you are facing this challenge.

Thank you!
