### ISSUE TITLE
Recommend to add search box in tensorflow API page

### ISSUE THREAD

**Issue by JacobIsrael123** [tensorflow/tensorflow#627]
I think the user experience would be better if we could have a search box in tensor API webpage.

**Comment by martinwicke** [comment]
Agreed. Out of the box solutions require searchable things to live on
separate pages, which isn't the case for our docs right now. We'll have to
do some restructuring to make this work (well, a badly working search box
is simple, but I'd rather do it right if I'm doing it at all). It's on our
list of todos. Thanks for the report!

**Comment by girving** [comment]
@martinwicke: Should @xmbrst be assigned for this kind of doc bug?

**Comment by martinwicke** [comment]
Yes, but this specific one will be made obsolete by our move to different infrastructure for tensorflow.org. We can leave it open and close it later, but nobody will work on this before the move happens.

**Comment by martinwicke** [comment]
Reassigning for the honor of closing.

**Comment by wangg12** [comment]
+1 for this feature request. For now many search results of tensorflow doc in google are dead links.
