### ISSUE TITLE
how to implement movinet video action classification model in tensorflow c++ lite

### ISSUE THREAD

**Issue by ranjith502** [tensorflow/tensorflow#62704]
I appreciate the tutorial on MoViNet available at the TensorFlow models GitHub repository. Your contributions have been very helpful. I've experimented with the MoViNet model using custom data. However, during my search, I couldn't find any implementation of MoViNet in TensorFlow Lite for C++ for video action classification.  Could you provide any references or guidance on this?

**Comment by sushreebarsa** [comment]
@ranjith502 Could you try to use the tf.lite.Interpreter class to load the MoViNet model first then preprocess video frames into tensors of expected shape. After that pass tensors to the interpreter for inference and extract class probabilities or labels from output tensors. 
Thank you!
