### ISSUE TITLE
summarize_graph building failed

### ISSUE THREAD

**Issue by oldtimerzhy** [tensorflow/tensorflow#62707]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

master

### Custom code

Yes

### OS platform and distribution

Ubuntu 18.04

### Python version

3.7

### Bazel version

7.0.0

### GCC/compiler version

gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

### Current behavior?

I want to figure out the inputs and outputs from a ckpt model. 
When I building summarize_graph with using `bazel build tensorflow/tools/graph_transforms:summarize_graph` in conda without compile the whole tf repository. I found the error as following. I have changed the environment of conda, same error existed. PTAL~

### Relevant log output

```shell
/usr/include/c++/7/type_traits:878:48: error: constructor required before non-static data member for 'stream_executor::CommandBuffer::Deleter::owned' has been parsed
     template<typename _Tp, typename = decltype(_Tp())>
                                                ^~~~~
Target //tensorflow/tools/graph_transforms:summarize_graph failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 64.002s, Critical Path: 46.63s
INFO: 2034 processes: 66 internal, 1968 local.
FAILED: Build did NOT complete successfully
```

_No response_

**Comment by sushreebarsa** [comment]
@oldtimerzhy Please ensure you're in the correct conda environment with TensorFlow installed. Verify Bazel installation and version compatibility with your TensorFlow version. Reinstalling Bazel or using a different version might help. Clear any potential issues by running bazel clean before rebuilding. Please let us know if it helps? 
Thank you!

**Comment by oldtimerzhy** [comment]
Hi @sushreebarsa, thanks for your replying and guidence. If no people meet the same issue, I think the source code is OK and seem the problems come from the environment. The related version of bazel and tensorflow I used are shown as the description above. I am on the master branch of tensorflow, so I think maybe I should checkout to some previous versions but not so far from now. I will try again. Thanks~

**Comment by sushreebarsa** [comment]
@oldtimerzhy Thank you for the confirmation!
If you are not facing the source code related issue then please check the environment compatibility as well.
Please let us know if we can move this issue to closed status for now.
Thank you!

**Comment by oldtimerzhy** [comment]
@sushreebarsa 
I will try to fix the problems by checking environment. Please close this issus. Thank you.

**Comment by sushreebarsa** [comment]
@oldtimerzhy Thank you for the confirmation.  Closing the issue for now.
