### ISSUE TITLE
TensorFlow在尝试将数据从CPU复制到GPU时遇到了问题

### ISSUE THREAD

**Issue by starxinyi** [tensorflow/tensorflow#62703]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.10

### Custom code

Yes

### OS platform and distribution

Window 10

### Python version

3

### CUDA/cuDNN version

CUDA11.2和cuDNN8.1

### GPU model and memory

NVIDIA Tesla V100-SXM2-32GB 

### Current behavior?

这是我RNN模型一运行代码运行的错误：InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized,
对于网上提出的解决方案1.GPU内存不足，我试过换成4个显卡的，还是出现同样的错误。2. TensorFlow版本问题：我现在的版本是2.10，但是我试过更换为2.4，2.5，2.6都是不行。3.减小你的批量大小（batch size），我试过改到batch size=2，也是同样的错误，4.我的TensorFlow和我的CUDA,cuDNN都是匹配的。5.关键是我这个模型的代码在CPU下运行是非常良好的，只是速度慢。改为GPU运行是为了提高速度，但是在GPU上一运行就出现这个错误。

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
  except RuntimeError as e:
    print(e)
# from tensorflow.keras import mixed_precision
from keras import backend as K
from tensorflow.keras import layers, models
from tensorflow.keras.regularizers import l2
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
import os

# policy = mixed_precision.Policy('mixed_float16')
# mixed_precision.set_global_policy(policy)

# 加载数据
data_folder = "RamanLib.npy"
X_train_list = []
y_train_list = []
X_test_list = []
y_test_list = []

for mineral_class in os.listdir(data_folder):
    class_folder = os.path.join(data_folder, mineral_class)
    for fold in range(5):  # 假设你有5折数据
        X_train = np.load(os.path.join(class_folder, f"fold{fold}_train_data.npy"))
        X_test = np.load(os.path.join(class_folder, f"fold{fold}_test_data.npy"))

        # 增加一个维度以满足RNN的输入要求
        X_train = X_train[:, :, np.newaxis]
        X_test = X_test[:, :, np.newaxis]

        y_train = [mineral_class] * len(X_train)
        y_test = [mineral_class] * len(X_test)

        X_train_list.append(X_train)
        y_train_list.extend(y_train)
        X_test_list.append(X_test)
        y_test_list.extend(y_test)

X_train = np.vstack(X_train_list)  # 将列表转换为numpy数组
y_train = np.array(y_train_list)
X_test = np.vstack(X_test_list)
y_test = np.array(y_test_list)

# 对标签进行编码
encoder = LabelEncoder()
encoder.fit(np.concatenate((y_train, y_test)))
y_train = np_utils.to_categorical(encoder.transform(y_train))
y_test = np_utils.to_categorical(encoder.transform(y_test))

def create_model(neurons=128, l2_weight=0.001, dropout_rate=0, learning_rate=0.001):
    model = models.Sequential()
    
    model.add(layers.Bidirectional(layers.LSTM(neurons, input_shape=X_train.shape[1:], return_sequences=True,
                               kernel_regularizer=l2(l2_weight))))
    model.add(layers.Dropout(dropout_rate))
    
    
    model.add(layers.Bidirectional(layers.LSTM(neurons, return_sequences=True, kernel_regularizer=l2(l2_weight))))
    model.add(layers.Dropout(dropout_rate))
    
    model.add(layers.Bidirectional(layers.LSTM(neurons, return_sequences=True, kernel_regularizer=l2(l2_weight))))
    model.add(layers.Dropout(dropout_rate))
    
    model.add(layers.Bidirectional(layers.LSTM(neurons, kernel_regularizer=l2(l2_weight))))
    model.add(layers.Dropout(dropout_rate))
    
    model.add(layers.Dense(y_train.shape[1]))
    model.add(layers.Activation('softmax'))


    optimizer = tf.keras.optimizers.Adam(learning_rate=learning_rate)
    model.compile(optimizer=optimizer,
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])

    return model


# 创建并编译模型
strategy = tf.distribute.MirroredStrategy()
with strategy.scope():
    model = create_model(learning_rate=0.001)

# 训练模型
history = model.fit(X_train, y_train,
                    validation_data=(X_test, y_test),
                    epochs=50,
                    batch_size=32)

# 评估模型
train_loss, train_acc = model.evaluate(X_train, y_train)
print(f"Training Accuracy: {train_acc}")#训练完成后，使用测试集进行评价

test_loss, test_acc = model.evaluate(X_test, y_test)#查看模型在训练集上的损失和精度值
print(f"Test Accuracy: {test_acc}")
```

**Comment by 123mbcz123** [comment]
MirroredStrategy策略默认使用NCCL进行通讯，NCCL是不支持Windows的。你可以尝试使用tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())代替。
当然，如果你不需要使用多卡并行计算，你可以直接去掉strategy = tf.distribute.MirroredStrategy()相关的代码。

**Comment by Venkat6871** [comment]
Hi **@starxinyi** ,

Check GPU Availability:
Ensure that your machine has a GPU available, and TensorFlow correctly recognizes the GPU. You can use the following code to verify:
```
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
```
Make sure you can see the list of GPU devices without errors.
Memory Settings:
In your code, you've already set GPU memory growth, but sometimes it might be necessary to explicitly set GPU memory allocation. You can try the following code:
```
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        logical_gpus = tf.config.experimental.list_logical_devices('GPU')
        print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
    except RuntimeError as e:
        print(e)
```
This ensures that TensorFlow allocates only the required GPU memory.
TensorFlow Version Compatibility:
Ensure that your TensorFlow version is compatible with your GPU drivers. Sometimes, specific TensorFlow and GPU driver versions need to be matched for stability.

Thank you!

**Comment by starxinyi** [comment]
> 你好**@starxinyi**,
> 
> 检查 GPU 可用性： 确保您的机器有可用的 GPU，并且 TensorFlow 可以正确识别 GPU。您可以使用以下代码来验证：
> 
> ```
> from tensorflow.python.client import device_lib
> print(device_lib.list_local_devices())
> ```
> 
> 确保您可以看到 GPU 设备列表且没有错误。 内存设置： 在代码中，您已经设置了 GPU 内存增长，但有时可能需要显式设置 GPU 内存分配。您可以尝试以下代码：
> 
> ```
> gpus = tf.config.experimental.list_physical_devices('GPU')
> if gpus:
>     try:
>         for gpu in gpus:
>             tf.config.experimental.set_memory_growth(gpu, True)
>         logical_gpus = tf.config.experimental.list_logical_devices('GPU')
>         print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
>     except RuntimeError as e:
>         print(e)
> ```
> 
> 这可确保 TensorFlow 仅分配所需的 GPU 内存。 TensorFlow 版本兼容性： 确保您的 TensorFlow 版本与 GPU 驱动程序兼容。有时，需要匹配特定的 TensorFlow 和 GPU 驱动程序版本以确保稳定性。
> 
> 谢谢你！

 我有可用的 GPU，你给的这个代码我本身也有，也确保TensorFlow 版本与 GPU 驱动程序兼容了

**Comment by starxinyi** [comment]
> MirroredStrategy策略默认使用NCCL进行通讯，NCCL是不支持Windows的。你可以尝试使用tf.distribute.MirroredStrategy(cross_device_ops=tf.distribute.HierarchicalCopyAllReduce())代替。 当然，如果你不需要使用多卡资源计算，你可以直接去掉strategy = tf.distribute.MirroredStrategy()相关的代码。

我按照您说的进行修改，得到的还是这个问题InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.无法解决

**Comment by pya942976269** [comment]
您好，请问问题解决了吗?我也遇到了相同的问题

**Comment by Cccccclayton** [comment]
> TensorFlow Version Compatibility:

您好 请问解决了吗 我的代码也遇到了这个问题 而且在报错以前GPU会突然从百分之十左右飙升到100%的峰值，然后报错，我是nividia的T1000 4GB
