### ISSUE TITLE
Critical typo: squeeze the y_pred tensor even when it’s the same rank and shape as the y_pred tensor should be == instead of !=

### ISSUE THREAD

**Issue by rodriguesk** [tensorflow/tensorflow#62718]
https://github.com/tensorflow/tensorflow/blob/a32a1c9123a7c4fb926c1cdc3d99188a171cdfe5/tensorflow/python/keras/utils/losses_utils.py#L191

should be:
if (y_pred_rank - y_true_rank == 1) or y_pred_shape[-1] == 1:

Current behavior will squeeze the y_pred tensor even when it’s the same rank and shape as the y_pred tensor.

**Comment by sushreebarsa** [comment]
@rodriguesk Thank you for reporting an issue here.
Could you please elaborate the issue you are facing here ?
I was able to run the file successfully, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/e3ede62d9cc1bb882d0464499ebdb158/62718.ipynb) here!
Thank you!

**Comment by rodriguesk** [comment]
The issue is that the code is written wrong. read the code comments and what it’s supposed to do (only squeeze when the ranks differ by exactly 1 and not squeeze for situations of equal rank). Yet the code’s if statements will squeeze whenever the ranks are equal, which is wrong.On Jan 2, 2024, at 1:09 AM, sushreebarsa ***@***.***> wrote:﻿External Email
@rodriguesk Thank you for reporting an issue here.
Could you please elaborate the issue you are facing here ?
I was able to run the file successfully, please find the gist here!
Thank you!

**Comment by sushreebarsa** [comment]
@rodriguesk I have created a fix internally, once the changes are verified this issue will be resolved.
Thank you!

**Comment by rodriguesk** [comment]
it looks like the PR you made was closed as this is a fix needs to be made in the keras repo? What's the plan?

**Comment by rodriguesk** [comment]
@sushreebarsa I made a PR for the appropriate tf-keras repo. https://github.com/keras-team/tf-keras/pull/719
