### ISSUE TITLE
Are the TFLite examples preventing color information from being passed along for inference?

### ISSUE THREAD

**Issue by titanium-cranium** [tensorflow/tensorflow#62717]
I've recently noticed in the Object Detection example, that the CameraFragment.kt code includes this line:

https://github.com/tensorflow/examples/blob/fff4bcda7201645a1efaea4534403daf5fc03d42/lite/examples/object_detection/android_play_services/app/src/main/java/org/tensorflow/lite/examples/objectdetection/fragments/CameraFragment.kt#L276

```
    private fun detectObjects(image: ImageProxy) {
        // Copy out RGB bits to the shared bitmap buffer
        image.use { bitmapBuffer.copyPixelsFromBuffer(image.planes[0].buffer) }                        <-------

        val imageRotation = image.imageInfo.rotationDegrees
        // Pass Bitmap and rotation to the object detector helper for processing and detection
        objectDetectorHelper.detect(bitmapBuffer, imageRotation)
    }
```

IIUC, then this is extracting only the grayscale out of the YUV image being passed from the camera and passing that to ObjectDetector.  Won't that destroy any sort of color based inference in the models?

**Comment by titanium-cranium** [comment]
@tilakrayal Did you mean to reference the other issue here?  Can you please update this with a link to the duplicate issue so I can track it?

**Comment by LakshmiKalaKadali** [comment]
Hi @pkgoogle,
Please look into the issue.
Thank You

**Comment by pkgoogle** [comment]
Hi @titanium-cranium, yes, I believe you are correct -- However the inference preprocessing should (generally) match the training preprocessing i.e. the model would have been trained on this format, For your own app, you should edit this to match your model's training format. Does this answer your question?
