### ISSUE TITLE
pad to fixed BATCH_SIZE in tf.data.Dataset?

### ISSUE THREAD

**Issue by pure-rgb** [tensorflow/tensorflow#62722]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15

### Custom code

Yes

### Current behavior?

I have a dataset with 11 samples. And when I choose the `BATCH_SIZE` be 2, the following code will have errors:

    
    dataset = tf.contrib.data.TFRecordDataset(filenames) 
    dataset = dataset.map(parser)
    if shuffle:
        dataset = dataset.shuffle(buffer_size=128)
    dataset = dataset.batch(batch_size)
    dataset = dataset.repeat(count=1)

The problem lies in `dataset = dataset.batch(batch_size)`, when the `Dataset` looped into the last batch, the remaining count of samples is just 1, so is there any way to pick randomly one from the previous visited samples and generate the last batch?

The problem lies in `dataset = dataset.batch(batch_size)`, when the `Dataset` looped into the last batch, the remaining count of samples is just 1, so is there any way to pick randomly one from the previous visited samples and generate the last batch?
```

**Comment by tilakrayal** [comment]
@pure-rgb,
Could you please share a reproducible code that supports your statement so that the issue can be easily debugged? Thank you!
