### ISSUE TITLE
Tensorflow C API builds for Mac M1 

### ISSUE THREAD

**Issue by 0110G** [tensorflow/tensorflow#62739]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.13.0

### Custom code

Yes

### OS platform and distribution

MacOS 12.5 (Monterey)

### Python version

3.9

### Current behavior?

I have written a Prediction Service based on Tensorflow C API (found https://www.tensorflow.org/install/lang_c) which allows me to fetch predictions of pre trained models in realtime. Recently, I have upgraded to M1 Mac and found that there is no support for c api on this. I have tried many different solutions like:
1. https://gist.github.com/lnshi/eb3dea05d99daba5c932bbc786cc3701
2. https://stackoverflow.com/questions/72114748/installing-c-api-for-tensorflow-on-macbook-m1
3. https://stackoverflow.com/questions/65953780/immediate-runtime-error-with-tensorflow-c-api-on-m1-mac?rq=4

Can someone help me by
1. Providing compiled binary for Mac M1 for version 2.13.0 just like the ones provided here: https://www.tensorflow.org/install/lang_c
OR

2. Providing a clear set of instructions to build tf for M1

### Standalone code to reproduce the issue

```shell
Following instructions on https://www.tensorflow.org/install/lang_c 

#include <stdio.h>
#include <tensorflow/c/c_api.h>

int main() {
  printf("Hello from TensorFlow C library version %s\n", TF_Version());
  return 0;
}
```

**Comment by sushreebarsa** [comment]
@0110G There are no officially released pre-built TensorFlow C API binaries for Mac M1 on the TensorFlow website.
It's possible that official binaries will be provided in the future. Please stay updated on the TensorFlow [release](https://github.com/tensorflow/tensorflow/releases) notes and GitHub repository for updates.
If you're comfortable with building software from source, you can refer to the official TensorFlow documentation for detailed instructions: https://www.tensorflow.org/install/source.
For M1 Compatibility please ensure you follow the correct steps for building on Apple Silicon (ARM64) architecture.
Thank you!

**Comment by c-coder00** [comment]
> @0110G There are no officially released pre-built TensorFlow C API binaries for Mac M1 on the TensorFlow website. It's possible that official binaries will be provided in the future. Please stay updated on the TensorFlow [release](https://github.com/tensorflow/tensorflow/releases) notes and GitHub repository for updates. If you're comfortable with building software from source, you can refer to the official TensorFlow documentation for detailed instructions: https://www.tensorflow.org/install/source. For M1 Compatibility please ensure you follow the correct steps for building on Apple Silicon (ARM64) architecture. Thank you!

Are there any specific documentation regarding the steps for building on ARM64 (bazel config flags, C compiler versions etc.?)

**Comment by sushreebarsa** [comment]
@0110G Though there isn't any specific official documentation for building TensorFlow on ARM64 using Bazel. 
For C compiler versions make sure that you check the C compiler you use should be compatible with the ARM64 architecture.You can use the clang compiler that comes with the Android NDK.
Alternatively, you can use a different C compiler, such as GCC, as long as it is compatible with ARM64.
For using the correct flags, and troubleshooting common problems. please refer https://github.com/topics/tensorflow-android.
Thank you!
