### ISSUE TITLE
Error in markdown based comment

### ISSUE THREAD

**Issue by rohan843** [tensorflow/tensorflow#62745]
[This](https://github.com/tensorflow/tensorflow/blob/4dacf3f368eb7965e9b5c3bbdd5193986081c3b2/tensorflow/python/data/ops/dataset_ops.py#L1440) line in the documentation of `tf.data.Dataset.shuffle()`:

```md
To shuffle an entire dataset, set `buffer_size=dataset.cardinality(). This
```

has a missing backtick (`). I believe that the line instead may have been:

```md
To shuffle an entire dataset, set `buffer_size=dataset.cardinality()`. This
```

This is causing the docs to be shown as:

<kbd>![image](https://github.com/tensorflow/tensorflow/assets/73627693/c3b420cd-5992-4a48-8cde-b88c7e7d5d51)</kbd>

**Comment by UdityaRaj11** [comment]
Hii @rohan843 and @sushreebarsa, I've started my open source contribution by solving this issue, my PR #62751. Looking forward to solving more issues.

**Comment by AryanNanda17** [comment]
ERROR: /home/jenkins/workspace/ROCm-Community-CI-Build_PR-62754/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/external/XNNPACK/BUILD.bazel:1861:19: Compiling src/amalgam/gen/avxvnni.c failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command (from target @XNNPACK//:avxvnni_prod_microkernels) 

  (cd /home/jenkins/workspace/ROCm-Community-CI-Build_PR-62754/bazel-ci_build-cache/.cache/bazel/_bazel_jenkins/eab0d61a99b6696edb3d2aff87b585e8/execroot/org_tensorflow && \

  exec env - \

    LD_LIBRARY_PATH='' \

    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \

    PWD=/proc/self/cwd \

    PYTHON_BIN_PATH=/usr/bin/python3 \

    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \

    ROCM_PATH=/opt/rocm-5.3.0 \

    TF2_BEHAVIOR=1 \

  external/local_config_rocm/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -MD -MF bazel-out/k8-opt/bin/external/XNNPACK/_objs/avxvnni_prod_microkernels/avxvnni.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/XNNPACK/_objs/avxvnni_prod_microkernels/avxvnni.pic.o' -fPIC '-DBAZEL_CURRENT_REPOSITORY="XNNPACK"' -iquote external/XNNPACK -iquote bazel-out/k8-opt/bin/external/XNNPACK -isystem external/XNNPACK/include -isystem bazel-out/k8-opt/bin/external/XNNPACK/include -isystem external/XNNPACK/src -isystem bazel-out/k8-opt/bin/external/XNNPACK/src -Wno-all -Wno-extra -Wno-deprecated -Wno-deprecated-declarations -Wno-ignored-attributes -Wno-array-bounds -Wunused-result '-Werror=unused-result' -Wswitch '-Werror=switch' '-Wno-error=unused-but-set-variable' -DAUTOLOAD_DYNAMIC_KERNELS -Iinclude -Isrc -mavx2 -mavxvnni '-std=c99' -O2 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-DTENSORFLOW_USE_ROCM=1' -D__HIP_PLATFORM_AMD__ -DEIGEN_USE_HIP -no-canonical-prefixes -fno-canonical-system-headers -c external/XNNPACK/src/amalgam/gen/avxvnni.c -o bazel-out/k8-opt/bin/external/XNNPACK/_objs/avxvnni_prod_microkernels/avxvnni.pic.o)

# Configuration: c1ff79497c6beaeff02baebfade101eb9d79226e84d7eb2351a32bd41a926e41

# Execution platform: @local_execution_config_platform//:platform

gcc: error: unrecognized command line option '-mavxvnni'; did you mean '-mavx512vnni'?

Target //tensorflow/tools/pip_package:build_pip_package failed to build

INFO: Elapsed time: 56.332s, Critical Path: 12.79s

INFO: 2608 processes: 1653 internal, 955 local.

FAILED: Build did NOT complete successfully

**Comment by AryanNanda17** [comment]
Why did build of AMD ROCm failed?
