### ISSUE TITLE
Can't build tf 2.15 with docker image tensorflow:latest-devel-gpu

### ISSUE THREAD

**Issue by PeterPirog** [tensorflow/tensorflow#62741]
Is possible to add new version of docker image tensorflow:latest-devel-gpu ?
Current version has CUDA 11.2 python 3.8 and can't support build from source version 2.15.0.

**Comment by sushreebarsa** [comment]
Hi, @PeterPirog! There are a few ways to check the existing images; such as exploring the TensorFlow Docker Hub: https://www.tensorflow.org/install/docker: https://www.tensorflow.org/install/docker
Please check the tags like devel-gpu-jupyter or nightly-devel-gpu-jupyter that might have updated configurations.
Kindly monitor TensorFlow release notes for new images: https://github.com/tensorflow/tensorflow/releases: https://github.com/tensorflow/tensorflow/releases.
Thank you!

**Comment by fancyerii** [comment]
I confronted the same problem. the cuda and cudnn in devel-gpu image is 11.2 and 8.1. 
Accordding to https://www.tensorflow.org/install/source#tested_build_configurations:
```
tensorflow-2.15.0	3.9-3.11	Clang 16.0.0	Bazel 6.1.0	8.9	12.2
tensorflow-2.14.0	3.9-3.11	Clang 16.0.0	Bazel 6.1.0	8.7	11.8
tensorflow-2.13.0	3.8-3.11	Clang 16.0.0	Bazel 5.3.0	8.6	11.8
tensorflow-2.12.0	3.8-3.11	GCC 9.3.1	Bazel 5.3.0	8.6	11.8
tensorflow-2.11.0	3.7-3.10	GCC 9.3.1	Bazel 5.3.0	8.1	11.2
```

it seems this image is for building tensorflow-2.11.0. But when I search https://hub.docker.com/r/tensorflow/tensorflow/tags/?page=1&name=devel-gpu&ordering=last_updated. the latest update is one year ago.
