### ISSUE TITLE
M1 macOS-arm64, for golang Install TensorFlow for C,missing arm64 libtensorflow

### ISSUE THREAD

**Issue by Codeprh** [tensorflow/tensorflow#62740]
Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template

System information

OS Platform and Distribution : MacBook Pro(Apple M1 Pro) macOS Monterey 12.5
Describe the problem

M1 macOS-arm64, for golang Install TensorFlow for C,missing libtensorflow-cpu-darwin-arm64.tar.gz

I followed the link: [https://www.tensorflow.org/install/lang_c#macos](https://www.tensorflow.org/install/lang_c#macos) to build TensorFlow golang api, but unfortunately I found that libtensorflow for macOS arm64 is missing.

If you can provide support for arm64, I would really appreciate it. Apple users will definitely like TensorFlow more and more.

Provide the exact sequence of commands / steps that you executed before running into the problem

```
$ gcc hello_tf.c -ltensorflow -o hello_tf
ld: warning: ignoring file /usr/local/lib/libtensorflow.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_TF_Version", referenced from:
      _main in hello_tf-bf3ad1.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Codeprh** [comment]
Somebody help me

**Comment by tilakrayal** [comment]
@Codeprh,
Could you please provide the complete error log you faced while installing which helps us to debug the issue in an effective way. Thank you!

**Comment by ekrich** [comment]
@Codeprh You probably need to add `-L/opt/homebrew/lib` for linking if you installed via homebrew. Or something like shown here. https://apple.stackexchange.com/questions/414622/installing-a-c-c-library-with-homebrew-on-m1-macs

Somehow if is finding the equivalent to `-I/opt/homebrew/include` otherwise it shouldn't even compile.
