### ISSUE TITLE
[feedback] border should be none of buttons on hover: Stay up to date section

### ISSUE THREAD

**Issue by soham2k06** [tensorflow/tensorflow#62765]
In section 'Stay up to date' on the home page. two buttons named 'Read the blog' and 'Watch now' has border on hover too and it is also exposing border-radius difference on hover.

I noticed that other buttons on homepage of this theme has border removed on hover.

**Comment by SuryanarayanaY** [comment]
Hi @soham2k06 ,

Please report here only Tensorflow related Bugs. UI related issues may not be considered here as it won't have any effect.
