### ISSUE TITLE
[bug] button 'view releases' has loading issue

### ISSUE THREAD

**Issue by soham2k06** [tensorflow/tensorflow#62761]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15.0.post1

### Custom code

Yes

### OS platform and distribution

macOs

### Current behavior?

There is some issue on loading button 'View releases' in home page.

It seems that the button is relying in some state coming from fetched data.

That's why it is being shown after some time.

https://github.com/tensorflow/tensorflow/assets/118199354/0211ff74-032d-4493-93b8-722dc3b4d029

### Standalone code to reproduce the issue

```shell
1. Search tensorflow in browser
2. Navigate to the website (https://www.tensorflow.org/)
3. In the very first page. you will be able to see the bug.

Note: I have not signed in.
```

**Comment by SuryanarayanaY** [comment]
Hi @soham2k06 ,

I cross checked and acknowledged that there seems some delay in fetching the tab `TF 2.15 released.View releases`.

CC: @MarkDaoust , Any comments on this ?

**Comment by itsdavidhu** [comment]
Hi, 

Where might I be able to find the source code for the TensorFlow website?

**Comment by itsdavidhu** [comment]
Hi, 

Where might I be able to find the source code for the home page in tensorflow/docs?

**Comment by MarkDaoust** [comment]
I see the delay too, but this is not something we can easily fix.
