### ISSUE TITLE
Unable to generate libtensorflowlite_flex_jni.so

### ISSUE THREAD

**Issue by prerna1124** [tensorflow/tensorflow#62763]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.10.0

### Custom code

Yes

### Current behavior?

I am working with soong build system. I have created a text based classification model and saved it as ".tflite" with select_tf_ops. Now, I am generating a ".apk" file using Android.bp only which is responsible for doing my classification task. I can push it on my target and it should classify. But I am getting below error.

--------- beginning of crash
10-23 11:33:25.970  4445  4445 E AndroidRuntime: FATAL EXCEPTION: main
10-23 11:33:25.970  4445  4445 E AndroidRuntime: Process: com.test.classifier, PID: 4445
10-23 11:33:25.970  4445  4445 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libtensorflowlite_flex_jni.so" not found
10-23 11:33:25.970  4445  4445 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
10-23 11:33:25.970  4445  4445 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
10-23 11:33:25.970  4445  4445 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1661)
10-23 11:33:25.970  4445  4445 E AndroidRuntime: 	at org.tensorflow.lite.flex.FlexDelegate.<clinit>(FlexDelegate.java:61)
10-23 11:33:25.970  4445  4445 E AndroidRuntime: 	at java.lang.Class.classForName(Native Method)
10-23 11:33:25.970  4445  4445 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:454)
10-23 11:33:25.970  4445  4445 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:379)
10-23 11:33:25.970  4445  4445 E AndroidRuntime: 	at org.tensorflow.lite.NativeInterpreterWrapper.maybeCreateFlexDelegate(NativeInterpreterWrapper.java:548)
10-23 11:33:25.970  4445  4445 E AndroidRuntime: 	at org.tensorflow.lite.NativeInterpreterWrapper.applyDelegates(NativeInterpreterWrapper.java:510)
10-23 11:33:25.970  4445  4445 E AndroidRuntime: 	at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:88)
10-23 11:33:25.970  4445  4445 E AndroidRuntime: 	at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:66)
10-23 11:33:25.970  4445  4445 E AndroidRuntime: 	at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:44)
10-23 11:33:25.970  4445  4445 E AndroidRuntime: 	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:228)
10-23 11:33:25.970  4445  4445 E AndroidRuntime: 	at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:212)

### Standalone code to reproduce the issue

```shell
Added below code in /tensorflow/lite/java/Android.bp

 srcs: [
         ":tflite_flex_delegate_java",
         ":tflite_nnapi_delegate_java",
         "src/main/java/org/tensorflow/lite/annotations/*.java",
         "src/main/java/org/tensorflow/lite/*.java",
     ]

Used below code for saving the model:
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.allow_custom_ops=True
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
```

**Comment by LakshmiKalaKadali** [comment]
Hi @pkgoogle

Please look into the issue

Thank You

**Comment by pkgoogle** [comment]
Hi @prerna1124, can you ensure you are following all the directions on this page? https://www.tensorflow.org/lite/android/development, specifically please be sure you have these abiFilters: https://www.tensorflow.org/lite/android/development#lite_lib, if you can share your gradle file or if possible, your entire project we can also take a look. Thanks for your help.
