### ISSUE TITLE
[feedback] language selections component in two places

### ISSUE THREAD

**Issue by soham2k06** [tensorflow/tensorflow#62764]
In home page, the website has language selection twice.

It would be more efficient to have the language selection only once on the navigation bar, instead of having it both on the navigation bar and footer.

**Comment by sushreebarsa** [comment]
Hi,  @soham2k06!   Generally users expect the language selector to be in a consistent location, usually the navigation bar. Placing it in two different places is inconsistent and makes it harder for users to find. Having the language selector only on the navigation bar keeps the footer uncluttered and focused on other important information or actions. 
Thank you!
