### ISSUE TITLE
How to cross compile tensorflow lite library for xtensa lx6 platform

### ISSUE THREAD

**Issue by Tamilarasan-C** [tensorflow/tensorflow#62766]
### 1. System information

- OS Platform and Distribution: Linux Ubuntu 20.04
- TensorFlow installation: Built from source
- TensorFlow library: Release 2.16.0

### 2. Query:

Hi,

I need to cross compile tensorflow lite library for xtensa lx6 platform, please provide instructions/links on how to do this.

Thanks.

**Comment by LakshmiKalaKadali** [comment]
Hi @Tamilarasan-C ,
Are you looking for ```esp_xtensa-esp32```?  If it is the same, Please refer to the examples for using tflite micro [here](https://www.tensorflow.org/lite/microcontrollers#explore_the_examples). Also tensorflow has [TensorFlow Lite for Microcontrollers Experiments](https://experiments.withgoogle.com/collection/tfliteformicrocontrollers) features work by developers combining Arduino and TensorFlow to examples and tools. 

For esp32, you can refer to the espressif official examples [here](https://github.com/espressif/tflite-micro-esp-examples/tree/master/examples). 

Thank you.
