### ISSUE TITLE
Check failed size >=0

### ISSUE THREAD

**Issue by gitmenonsandu** [tensorflow/tensorflow#6276]
### Environment info
Operating System: WIndows 10

If installed from binary pip package, provide:
TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl

I am using a similar code provided in the wide and deep learning tutorial.

Logs  :
F tensorflow/core/framework/tensor_shape.cc:172] Check failed: size >= 0 (-82806 vs. 0)
F tensorflow/core/framework/tensor_shape.cc:36] Check failed: NDIMS == dims() (2 vs. 1)Asking for tensor of 2dimensions from a tensor of 1 dimensions

**Comment by andydavis1** [comment]
Add a code example, and please ask thsi on StackOverflow, which we also monitor. Please ask it there and tag it with the `tensorflow` tag
