### ISSUE TITLE
How do I confirm if tensorflow uses AVX512 instructions?

### ISSUE THREAD

**Issue by bergentruckung** [tensorflow/tensorflow#62776]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.13

### Custom code

Yes

### OS platform and distribution

RedHat Enterprise Linux 8.9

### Python version

3.11.4

### Bazel version

5.4

### GCC/compiler version

10.3

### CUDA/cuDNN version

CUDA 12.2 and cuDNN 8.9.5

### GPU model and memory

A100 80GB PCIe

### Current behavior?

What's the way to assert that the TF that I built from source uses AVX512 instructions? These are the compiler optimizations that I provided during the build:

```
-msse4.2 -mavx2 -mfma -march=sandybridge -mtune=broadwell
```

I don't know if these correspond to the minimum compiler optimizations or the maximum.

### Standalone code to reproduce the issue

```shell
-
```

**Comment by Venkat6871** [comment]
Hi **@bergentruckung**,
Sorry for the delay, To confirm if tensorflow is using AVX512 instructions,
Check TensorFlow Build Configuration:
```
import tensorflow as tf
print(tf.sysconfig.get_build_info())
```
Check Runtime CPU Support:
```
import tensorflow as tf
print(tf.config.experimental.list_physical_devices('CPU'))
```
Check CPUID Instruction:
```
import tensorflow as tf
print(tf.experimental.cpuinfo.get_info())
```
The compiler flags you provided during the build (-msse4.2 -mavx2 -mfma -march=sandybridge -mtune=broadwell) suggest that you've enabled SSE4.2, AVX2, and FMA instructions, but AVX512 is not explicitly enabled. Consider rebuilding TensorFlow with an additional flag like -march=skylake-avx512 to enable AVX512 instructions.

Thank you!
