### ISSUE TITLE
support POW operator tflm

### ISSUE THREAD

**Issue by vigi04** [tensorflow/tensorflow#62780]
POW operator support on tflm

**Comment by vigi04** [comment]
I have implemented POW operator locally. It would be great if we could integrate it into the main repo

**Comment by tilakrayal** [comment]
@vigi04,
Could you please refer to the guide on how to port TFLite ops to TFLM is located here:
https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/docs/porting_reference_ops.md

Thank you!
