### ISSUE TITLE
Does the op assign change the gradient computation?

### ISSUE THREAD

**Issue by iridescent303** [tensorflow/tensorflow#6278]
I use the op "assign" to change the value of variables instead of "=", but I found the gradient I got is quite different. Could anyone tell me the difference and why? thanks!
Like change `w = w1` to  `op1 = tf.assign(w, w1) sess.run(op1)`

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow, which we also monitor. Please ask it there and tag it with the `tensorflow` tag
