### ISSUE TITLE
Incorrect Reduction Arguments in third_party/xla/xla/experiments/triton_autotuning/matmul_lib.py

### ISSUE THREAD

**Issue by K-Wu** [tensorflow/tensorflow#62789]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

latest

### Custom code

No

### Current behavior?

In https://github.com/tensorflow/tensorflow/blob/master/third_party/xla/xla/experiments/triton_autotuning/matmul_lib.py#L301-L309, should the `row_size` be `int(dims.M)*int(dims.N)` instead?

### Standalone code to reproduce the issue

```shell
No need.
```

**Comment by tilakrayal** [comment]
@K-Wu,
Could you please share a reproducible code or the use-case that supports your statement so that the issue can be easily understood? Thank you!

**Comment by K-Wu** [comment]
Hi @tilakrayal ,

I don't have a reproducible code as this is not the core part of tensorflow. Besides, it should be fairly easy to tell by reading this argument. Could you please let the owner (maybe @gflegar) briefly check it? 

Thank you.

Best Regards,
Kun

**Comment by tilakrayal** [comment]
@K-Wu,
I have raised the PR for the same changes. Could you please take a look at the same PR.
https://github.com/tensorflow/tensorflow/pull/62885

Thank you!

**Comment by K-Wu** [comment]
Hi @tilakrayal, that works. Thank you!

**Comment by tilakrayal** [comment]
@K-Wu,
As per the comment from the Developer in the PR raised, the requested change should happen in the https://github.com/openxla/xla repository. Could you please try to check with the respective repo as the file belongs to the xla api. Thank you!
