### ISSUE TITLE
The c api 2.15 zip for windows does not have required files, but the linux version contains all the required files

### ISSUE THREAD

**Issue by arwhirang** [tensorflow/tensorflow#62792]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.15

### Custom code

No

### OS platform and distribution

Windows and linux

### Mobile device

None

### Python version

Doesn't matter

### Bazel version

Doesn't matter

### GCC/compiler version

Doesn't matter

### CUDA/cuDNN version

Doesn't matter

### GPU model and memory

Doesn't matter

### Current behavior?

The "Download and extract" section of the webpage "Install Tensorflow for C" has several links.
The c api 2.15 zip for windows does not have required files, but the linux version contains all the required files.

### Standalone code to reproduce the issue

```shell
Not applicable.
```

### Relevant log output

```shell
Not applicable.
```

**Comment by sushreebarsa** [comment]
@arwhirang TensorFlow 2.10 was the last TensorFlow release that supported GPUs on native-Windows.  Please refer to this [doc](https://www.tensorflow.org/install/pip) for more information on this. Could you please let us know what are the steps you followed and the issue you are facing? Thank you!
