### ISSUE TITLE
Gradients with tf.math.expm and complex inputs generates casting warning

### ISSUE THREAD

**Issue by aplund** [tensorflow/tensorflow#62793]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.15.0

### Custom code

No

### OS platform and distribution

Archlinux

### Current behavior?

Computing gradients using tf.linalg.expm with complex types gives warnings about casting to real types.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
x=tf.Variable(0, dtype=tf.complex128)
A = tf.constant(
    [[0,0,0,0,0],
     [0,0+1.0j,0,0,0],
     [0,0,-2,0,0],
     [0,0,0,-3.0j,0],
     [0,0,0,0,4]]
    ,tf.complex128)
with tf.GradientTape() as g:
    g.watch(x)
    out = tf.linalg.expm(x*A)
display(g.jacobian(out, x))
```

### Relevant log output

```shell
WARNING:tensorflow:You are casting an input of type complex128 to an incompatible dtype float64.  This will discard the imaginary part and may not be what you intended.

<tf.Tensor: shape=(5, 5), dtype=complex128, numpy=
array([[ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.-1.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j, -2.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+3.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  4.+0.j]])>
```

**Comment by SuryanarayanaY** [comment]
Hi @aplund ,

This is intended. The API warns you that when casting a complex number to `float`, it will ignore the imaginary part which is the behaviour of the casting op. Please refer this part of source code.

https://github.com/tensorflow/tensorflow/blob/4c288453087edd9610dba9e94822044ddafc568f/tensorflow/python/ops/math_ops.py#L1011-L1017

**Comment by aplund** [comment]
I'm trying to see where in the code snippet a cast to a real number is indicated. Are you able to point to the line where it happens?

**Comment by SuryanarayanaY** [comment]
Hi @aplund ,

It seems cast being called internally by the `tf.GradientTape().jacobian` method. Hard to trace though.

**Comment by aplund** [comment]
I'm not sure I fully understand how to run tensorflow from within the build tree, so I just changed the python file in the venv and generated the trace that way.

[tmpout.txt](https://github.com/tensorflow/tensorflow/files/13996817/tmpout.txt)

**Comment by zahed327** [comment]
Hello, I'd like to work on this issue. Can I contribute?

**Comment by zahed327** [comment]
@SuryanarayanaY  I am facing issues regarding bazel build in tensorflow while building from source. Is there a way to resolve the issue so that I can test the code

**Comment by tilakrayal** [comment]
@aplund,
As suggested, have you tried the altenative appraoch by cloining the TF repo locally and chaning the logging.warning(".....") to raise TypeError("...") in cast op API python/ops/math.py file and adding tf.debugging.disable_traceback_filtering after tensorflow import. Please feel free to move this issue to closed status, if the issue got resolved. Thank you!
