### ISSUE TITLE
Bazel can't build anymore?

### ISSUE THREAD

**Issue by wchan** [tensorflow/tensorflow#628]
Was a BUILD file or something recently changed?

This works perfectly fine:
bazel build -c opt --config=cuda //tensorflow/core:tensorflow --verbose_failures || exit 1

This fails (gets stuck):
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures || exit 1

and gets stuck on:
bazel build --config=cuda //tensorflow/tools/pip_package:build_pip_package
INFO: Reading 'startup' options from /home/wchan/.bazelrc: --install_base /dev/shm/wchan/bazel/install_base --output_base /dev/shm/wchan/bazel/output_base
Extracting Bazel installation...
......
INFO: (12-26 18:02:26.076) Loading package: 

stuck on "Loading package", can't find anything in the logs. Tried the whole shebang of bazel clean and another server, doesn't work on different machines as well... any ideas?

**Comment by wchan** [comment]
Is this supposed to happen?

rm -rf /tmp/wchan

bazel build -c opt --config=cuda //tensorflow/python:all
INFO: Reading 'startup' options from /home/wchan/.bazelrc: --install_base /tmp/wchan/bazel/install_base --output_base /tmp/wchan/bazel/output_base
Extracting Bazel installation...
......
INFO: (12-26 18:21:09.192) Found 236 targets...
INFO: (12-26 18:21:11.017) From Executing genrule @six_archive//:copy_six:
src/main/tools/namespace-sandbox.c:361: mkdir("tmp", 0755): File exists
ERROR: (12-26 18:21:11.018) /tmp/wchan/bazel/output_base/external/six_archive/BUILD:1:1: Executing genrule @six_archive//:copy_six failed: bash failed: error executing command /bin/bash -c 'source tools/genrule/genrule-setup.sh; cp external/six_archive/six-1.10.0/six.py bazel-out/local_linux-opt/genfiles/external/six_archive/six.py'.
INFO: (12-26 18:21:11.088) Elapsed time: 9.932s, Critical Path: 0.74s

**Comment by wchan** [comment]
This is not supposed to happen right?

rm -rf /tmp/wchan
bazel build -c opt --config=cuda //tensorflow/python:all
INFO: Reading 'startup' options from /home/wchan/.bazelrc: --install_base /tmp/wchan/bazel/install_base --output_base /tmp/wchan/bazel/output_base
Extracting Bazel installation...
......
INFO: (12-26 18:21:09.192) Found 236 targets...
INFO: (12-26 18:21:11.017) From Executing genrule @six_archive//:copy_six:
src/main/tools/namespace-sandbox.c:361: mkdir("tmp", 0755): File exists
ERROR: (12-26 18:21:11.018) /tmp/wchan/bazel/output_base/external/six_archive/BUILD:1:1: Executing genrule @six_archive//:copy_six failed: bash failed: error executing command /bin/bash -c 'source tools/genrule/genrule-setup.sh; cp external/six_archive/six-1.10.0/six.py bazel-out/local_linux-opt/genfiles/external/six_archive/six.py'.
INFO: (12-26 18:21:11.088) Elapsed time: 9.932s, Critical Path: 0.74s


(confirmed I have python six installed btw).

**Comment by wchan** [comment]
FYI, if I remove tensorboard out of the BUILD file, it builds fine again -- as soon as I add it back it, it gets stuck on the "Loading package", so Im guessing something must have changed in the last few days.

**Comment by keveman** [comment]
wchan@, I was able to build successfully by following the "Installing from sources" instructions. This seems more like a Bazel issue than a TF issue. Make sure you have Bazel 0.1.1. Perhaps try a `bazel clean` and try building again.

**Comment by vrv** [comment]
bazel 0.1.2 I think.

**Comment by martinwicke** [comment]
@wchan, did you find a solution to this, did it disappear, or is it still a problem? I've not been able to reproduce.

**Comment by joshuastorck** [comment]
I've experienced the same problem. I found that cleaning out the ~/.cache/bazel directory fixed it. I think this is an issue with the cache getting corrupted. I was using bazel version 0.1.5.

**Comment by rilut** [comment]
@joshuastrock's advice solved my issue
