### ISSUE TITLE
Running quantized tflite model in "full" tensorflow

### ISSUE THREAD

**Issue by luikaire** [tensorflow/tensorflow#62815]
I quantized a full tensorflow model and got a smaller tflite file

This runs well using tf.lite.Interpreter. However, on my machine, tflite can only use CPU, while "full" tensorflow is much faster as it can use GPU as well 
Because of CPU-only execution, the smaller quantized model runs slower in tf.lite.Interpreter than the larger/original model on "full" tensorflow

So I would like to know if there's any way to run the quantized tflite model (which is saved as a .tflite file on disk) in "full" tensorflow (via load_model for example) so that GPU acceleration can be used

thanks

**Comment by LakshmiKalaKadali** [comment]
Hi @luikaire,

Could you please confirm that your code used delegates?. If not, use gpu delegates to accelerate the inference. Refer the[ link](https://www.tensorflow.org/lite/performance/gpu) for reference.

Thank You

**Comment by luikaire** [comment]
I use the tensorflow-rocm pip package downloaded from the official installation page (tensorflow-2.13.0.570+rocm-5.7.2) on a linux machine (ubuntu-22.04)

with this installation gpu support in "full" tensorflow/keras models works out of the box

but when running the tflite model file through tf.lite.Interpreter , only cpu is used. This means the tflite file, despite being a lot smaller (23 Mb) vs the keras .h5 model (91 Mb) runs slower

Are gpu delegates available for this setup (ubuntu linux+amd rocm)? If so, how can I force tflite to use gpu delegates?

The link you referred doesn't seem to have information about linux machines..

**Comment by LakshmiKalaKadali** [comment]
Hi @luikaire,

The link provided in the earlier comment exactly refers to gpu delegates for android and ios only.  In your usecase, the gpu deligates  may be build on linux through Bazel. Could you please try to follow these steps :
1. Install  Bazel:
    ```wget https://github.com/bazelbuild/bazel/releases/download/6.1.0/bazel-6.1.0-installer-linux-x86_64.sh```
2. Clone Tensorflow Repository
     ``` git clone https://github.com/tensorflow/tensorflow.git tensorflow_src```
3.  ```apt get install mesa-common-dev libgl1-mesa-dev libgles2-mesa-dev ocl-icd-opencl-dev```
4.  Run ./configure
5.  Run ```bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 
     tensorflow/lite/delegates/gpu:gl_delegate```.

https://github.com/tensorflow/tensorflow/issues/46498, https://github.com/tensorflow/tensorflow/issues/46498

Thank You
