### ISSUE TITLE
Is it possible to combile TensofrFlow & ARKit in Swift 5

### ISSUE THREAD

**Issue by vnanaware111** [tensorflow/tensorflow#62811]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

0.0.1

### Custom code

Yes

### Current behavior?

Is it possible to use Tensorflow & ARKit combinely.

### Standalone code to reproduce the issue

```shell
Is it possible to use Tensorflow & ARKit combinely.
```

**Comment by Venkat6871** [comment]
Hi **@vnanaware111** ,

Sorry for the late reply, Yes it is possible to use tensorflow and ARKit together, they serve different purposes in the context of developing applications.

Thank you!
