### ISSUE TITLE
tf.data.Options not affecting autotune parallelism behavior

### ISSUE THREAD

**Issue by franklsf95** [tensorflow/tensorflow#62821]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

v2.14.0-rc1-21-g4dacf3f368e 2.14.0

### Custom code

No

### Python version

3.10.13

### Current behavior?

My understanding is that by setting `options.autotune.cpu_budget = 1`, the autotuner won't use more than 1 CPU for the map tasks when using the autotuned parallelism (`num_parallel_calls=tf.data.experimental.AUTOTUNE`). However, the log shows that the tasks returned in 2 batches, one around 8 seconds, and one around 13 seconds. This is likely a parallelism of 8 (I have 8 cores on my machine). My questions are:

1. What can I do to ask tf.data to respect the CPU budget?
2. Is there a way to debug the autotuner? E.g. how can I find out what parallelism the autotuner chose?

### Standalone code to reproduce the issue

```python
import time
import os

import tensorflow as tf

tf.get_logger().setLevel("DEBUG")


os.environ["TF_CPP_MIN_LOG_LEVEL"] = "0"
os.environ["TF_CPP_MIN_VLOG_LEVEL"] = "0"


def foo(i):
    for _ in range(20_000_000):
        i += 1
    return i


start = time.perf_counter()

options = tf.data.Options()
options.autotune.cpu_budget = 1

ds = tf.data.Dataset.range(16).with_options(options)
ds = ds.map(
    lambda item: tf.numpy_function(
        foo,
        [item],
        Tout=tf.int64,
    ),
    # num_parallel_calls=1,
    num_parallel_calls=tf.data.experimental.AUTOTUNE,
)


ret = 0
for row in ds:
    print(time.perf_counter() - start, row)
    ret += row

```

### Relevant log output

```shell
# With manually specified num_parallel_calls=1:

0.9090110249817371 tf.Tensor(20000000, shape=(), dtype=int64)
1.7222977789351717 tf.Tensor(20000001, shape=(), dtype=int64)
2.547924594953656 tf.Tensor(20000002, shape=(), dtype=int64)
3.3709740849444643 tf.Tensor(20000003, shape=(), dtype=int64)
4.167228076024912 tf.Tensor(20000004, shape=(), dtype=int64)
4.973599593038671 tf.Tensor(20000005, shape=(), dtype=int64)
5.799614907009527 tf.Tensor(20000006, shape=(), dtype=int64)
6.618450765963644 tf.Tensor(20000007, shape=(), dtype=int64)
7.427832546993159 tf.Tensor(20000008, shape=(), dtype=int64)
8.226964170928113 tf.Tensor(20000009, shape=(), dtype=int64)
9.045983245014213 tf.Tensor(20000010, shape=(), dtype=int64)
9.841567247989587 tf.Tensor(20000011, shape=(), dtype=int64)
10.652729655965231 tf.Tensor(20000012, shape=(), dtype=int64)
11.432073520030826 tf.Tensor(20000013, shape=(), dtype=int64)
12.26768407295458 tf.Tensor(20000014, shape=(), dtype=int64)
13.078245428041555 tf.Tensor(20000015, shape=(), dtype=int64)

# With num_parallel_calls=tf.data.experimental.AUTOTUNE:

7.32448233210016 tf.Tensor(20000000, shape=(), dtype=int64)
7.346081388066523 tf.Tensor(20000001, shape=(), dtype=int64)
7.39306910301093 tf.Tensor(20000002, shape=(), dtype=int64)
7.404705744003877 tf.Tensor(20000003, shape=(), dtype=int64)
7.452494919067249 tf.Tensor(20000004, shape=(), dtype=int64)
8.152240323019214 tf.Tensor(20000005, shape=(), dtype=int64)
8.226954131037928 tf.Tensor(20000006, shape=(), dtype=int64)
8.243354345089756 tf.Tensor(20000007, shape=(), dtype=int64)
11.689252487034537 tf.Tensor(20000008, shape=(), dtype=int64)
12.99928606802132 tf.Tensor(20000009, shape=(), dtype=int64)
13.021037437021732 tf.Tensor(20000010, shape=(), dtype=int64)
13.037309881066903 tf.Tensor(20000011, shape=(), dtype=int64)
13.363138618064113 tf.Tensor(20000012, shape=(), dtype=int64)
13.37413718609605 tf.Tensor(20000013, shape=(), dtype=int64)
13.395835493109189 tf.Tensor(20000014, shape=(), dtype=int64)
13.50603799300734 tf.Tensor(20000015, shape=(), dtype=int64)
```

**Comment by Rahulraj0308** [comment]
@franklsf95 Experiment with different values and observe the impact on parallelism. If needed, you can manually set num_parallel_calls based on your observations for better control.```
import time
import os

import tensorflow as tf

tf.get_logger().setLevel("DEBUG")

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "0"
os.environ["TF_CPP_MIN_VLOG_LEVEL"] = "0"

def foo(i):
    for _ in range(20_000_000):
        i += 1
    return i

start = time.perf_counter()

options = tf.data.Options()
options.autotune.cpu_budget = 1

ds = tf.data.Dataset.range(16).with_options(options)
ds = ds.map(
    lambda item: tf.numpy_function(
        foo,
        [item],
        Tout=tf.int64,
    ),
    num_parallel_calls=1,  # Set this explicitly
)

ret = 0
for row in ds:
    print(time.perf_counter() - start, row)
    ret += row

```.  Try this if it works.

**Comment by Venkat6871** [comment]
Hi **@franklsf95** ,
I tried to run your code on Colab using TF v2.15 and nightly versions, Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/e0fc92b9013619228113cc07146f96fb/62821.ipynb) here for reference. 

Thank you!

**Comment by franklsf95** [comment]
OK I was able to make tensorflow to start from parallelism=1 to respect the limit. By default, it starts with parallelism=<number of cores on your machine> which in my case was 16, so it just blasted through everything.
