### ISSUE TITLE
Missing tensorflow-rocm wheel with python 3.12

### ISSUE THREAD

**Issue by bioinfornatics** [tensorflow/tensorflow#62827]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source: pypi

### TensorFlow version

2.12

### Custom code

Yes

### OS platform and distribution

Linux Fedora 39

### Python version

3.12

### GPU model and memory

RocM

### Current behavior?

Fedora 39 provides Rocm 5.7 and python 3.12.
We can see [here](https://pypi.org/project/tensorflow-rocm/2.12.1.570/#files) that they are any wheel for python 3.12.
Could you push a wheel with python 3.12 and rocm 5.7 ?

### Standalone code to reproduce the issue

```shell
$ pip install tensorflow-rocm==2.12.1.570
ERROR: Could not find a version that satisfies the requirement tensorflow-rocm==2.12.1.570 (from versions: none)
ERROR: No matching distribution found for tensorflow-rocm==2.12.1.570

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
```
```


### Relevant log output

_No response_

**Comment by johnthagen** [comment]
3.12 doesn't seem supported even in the core of TF yet:

- #62003

**Comment by SuryanarayanaY** [comment]
Hi @bioinfornatics ,

Tensorflow won't provide official pre built binaries of ROCM build. The one you are referring might be SIG builds. You can opt build from source enabling ROCM in ./configure step using the instructions [here](https://www.tensorflow.org/install/source).

Alternatively you may contact [SIG](https://github.com/tensorflow/build) build repo here for any help.

Note: As mentioned in above [comment](https://github.com/tensorflow/tensorflow/issues/62827#issuecomment-1902832429) Python 3.12v not yet supported by Tensorflow till Tf2.15v.Please refer [setup.py](https://github.com/tensorflow/tensorflow/blob/v2.15.0/tensorflow/tools/pip_package/setup.py) for same.

Thnaks!

**Comment by bioinfornatics** [comment]
thanks @johnthagen and @SuryanarayanaY , your response is very appreciated.I wish you a nice day

**Comment by SuryanarayanaY** [comment]
Hi @bioinfornatics ,

Thanks for confirmation.Please feel free to close the issue.

**Comment by Niklas-Zeidler** [comment]
any updates on this? tensorflow supports 3.12 now for more than half a year

**Comment by arg0x** [comment]
Still doesn't work
```py
$ pip install tensorflow-rocm
ERROR: Could not find a version that satisfies the requirement tensorflow-rocm (from versions: none)
ERROR: No matching distribution found for tensorflow-rocm

```
