### ISSUE TITLE
keras LSTM model convert error with "'tf.TensorListReserve' op requires element_shape to be static during TF Lite transformation pass"

### ISSUE THREAD

**Issue by YuriSizuku** [tensorflow/tensorflow#62849]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab
- TensorFlow installation (pip package or built from source): 2.15.0 
- TensorFlow library (version, if pip package or github SHA, if built from source):

### 2. Code

A simple seq2seq model with lstm. 
https://colab.research.google.com/drive/1FKhOYhOz8d6BKLVVwL1YMlmoFQ2ML1DS#scrollTo=4SwY3T139l19

### 3. Failure after conversion
ConverterError                            Traceback (most recent call last)
[<ipython-input-11-67b7a4553e77>](https://localhost:8080/#) in <cell line: 2>()
      1 converter = tf.lite.TFLiteConverter.from_keras_model(enc_model)
----> 2 buffer = converter.convert()
      3 open('enc_model.tflite', 'wb').write(buffer)
      4 
      5 converter = tf.lite.TFLiteConverter.from_keras_model(dec_model)

8 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/convert.py](https://localhost:8080/#) in convert(model_flags, conversion_flags, input_data_str, debug_info_str, enable_mlir_converter)
    364               enable_mlir_converter,
    365           )
--> 366       raise converter_error
    367 
    368   return _run_deprecated_conversion_binary(

ConverterError: /usr/lib/python3.10/runpy.py:196:1: error: 'tf.TensorListReserve' op requires element_shape to be static during TF Lite transformation pass
    return _run_code(code, main_globals, None,
^
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
/usr/lib/python3.10/runpy.py:196:1: error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
    return _run_code(code, main_globals, None,
^
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
<unknown>:0: error: Lowering tensor list ops is failed. Please consider using Select TF ops and disabling `_experimental_lower_tensor_list_ops` flag in the TFLite converter object. For example, converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]\n converter._experimental_lower_tensor_list_ops = False
### 4. (optional) RNN conversion support
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by LakshmiKalaKadali** [comment]
Hi @YuriSizuku ,

Add `tf.lite.OpsSet.SELECT_TF_OPS`  to the converter's target spec: ```converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]``` to expand the range of supported operations. 
Please change the following lines of code:
   ```
    converter = tf.lite.TFLiteConverter.from_keras_model( enc_model )
    buffer = converter.convert()
    open( 'enc_model.tflite' , 'wb' ).write( buffer ) 
```
to 

```
converter = tf.lite.TFLiteConverter.from_keras_model( enc_model )
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter=True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,*tf.lite.OpsSet.SELECT_TF_OPS]
buffer = converter.convert()
open( 'enc_model.tflite' , 'wb' ).write( buffer ). 
```
The model working fine with this change. Here is the screenshot.
![image](https://github.com/tensorflow/tensorflow/assets/149650845/b958b07f-a4e8-40fb-9f72-b80b645f8cd7)

Thank You

**Comment by TimiOkusi** [comment]
The Select TF OPS command works but the problem I have been facing for a few days is deploying it in Android studio. Because of the added ops, it is giving an error of "Cannot create an interpreter: Unsupported datatype 14 in tensor" at just initializing the model.
