### ISSUE TITLE
Whisper large in SparkNlp (Message tensorflow.GraphDef exceeds maximum protobuf size of 2GB)

### ISSUE THREAD

**Issue by minhduc210196** [tensorflow/tensorflow#62850]
Issue Type
Bug

Source
source

Tensorflow Version
2.10

Custom Code
No

Google colab

Mobile device
No response

Python version
3.9

Bazel version
No response

GCC/Compiler version
No response

CUDA/cuDNN version
11.4/8.1.0

GPU model and memory
A100 40GB

**Comment by minhduc210196** [comment]
import tensorflow as tf
from tensorflow.python.framework.convert_to_constants import (
    convert_variables_to_constants_v2,
)
from transformers import TFWhisperForConditionalGeneration, WhisperProcessor


encoder_signature = [
    {
        "input_features": tf.TensorSpec(
            (None, None, None), tf.float32, name="input_features"
        )
    }
]

decoder_init_signature = [
    {
        "decoder_input_ids_init": tf.TensorSpec(
            (None, None), tf.int32, name="decoder_input_ids_init"
        ),
        "encoder_state_init": tf.TensorSpec(
            (None, None, None), tf.float32, name="encoder_state_init"
        ),
    }
]

decoder_cache_signature = [
    {
        "decoder_input_ids": tf.TensorSpec(
            (None, None), tf.int32, name="decoder_input_ids"
        ),
        "encoder_state": tf.TensorSpec(
            (None, None, None), tf.float32, name="encoder_state"
        ),
        "decoder_past_key_values": tf.TensorSpec(
            (
                4,
                2,
                None,
                None,
                None,
                64,
            ),  # (layers, key-values, batch_size, num_heads, decoder_sequence_length, embed_size_per_head)
            tf.float32,
            name="decoder_past_key_values",
        ),
        "encoder_past_key_values": tf.TensorSpec(
            (
                4,
                2,
                None,
                None,
                None,
                64,
            ),  # (layers, key-values, batch_size, num_heads, encoder_sequence_length, embed_size_per_head)
            tf.float32,
            name="encoder_past_key_values",
        ),
    }
]


class WhisperExport(TFWhisperForConditionalGeneration):
    def to_logits(self, decoder_last_hidden_state):
        # Decoder and encoder embeddings are tied, convert to logits
        lm_logits = tf.matmul(
            decoder_last_hidden_state,
            self.get_output_embeddings().weights,
            transpose_b=True,
        )
        return lm_logits

    def convert_cache_tensors_to_tuple(
        self, decoder_cache_tensors, encoder_cache_tensors
    ):
        return tuple(
            [
                tuple(
                    [decoder_cache_tensors[i, j] for j in range(2)]
                    + [encoder_cache_tensors[i, j] for j in range(2)]
                )
                for i in range(self.config.decoder_layers)
            ]
        )

    @staticmethod
    def make_cache_tensors(past_key_values):
        return tf.stack(
            [[k for k in tensors[0:2]] for tensors in past_key_values]
        ), tf.stack([[k for k in tensors[2:4]] for tensors in past_key_values])

    def make_encoder_serving(self):
        @tf.function(input_signature=encoder_signature)
        def encoder_serving(inputs):
            return {"last_hidden_state": self.get_encoder()(inputs).last_hidden_state}

        return convert_variables_to_constants_v2(
            encoder_serving.get_concrete_function()
        )

    def make_decoder_init_serving(self):
        @tf.function(input_signature=decoder_init_signature)
        def decoder_init_serving(inputs):
            outputs = self.get_decoder()(
                inputs["decoder_input_ids_init"],
                encoder_hidden_states=inputs["encoder_state_init"],
            )

            lm_logits = self.to_logits(outputs[0])
            decoder_past_key_values, encoder_past_key_values = self.make_cache_tensors(
                outputs.past_key_values
            )
            return {
                "logits_init": lm_logits,
                "decoder_past_key_values": decoder_past_key_values,
                "encoder_past_key_values": encoder_past_key_values,
            }

        return convert_variables_to_constants_v2(
            decoder_init_serving.get_concrete_function()
        )

    def make_decoder_serving(self):
        @tf.function(input_signature=decoder_cache_signature)
        def decoder_serving(inputs):
            past_key_values_in = self.convert_cache_tensors_to_tuple(
                inputs["decoder_past_key_values"], inputs["encoder_past_key_values"]
            )
            outputs = self.get_decoder()(
                inputs["decoder_input_ids"],
                encoder_hidden_states=inputs["encoder_state"],
                past_key_values=past_key_values_in,
                use_cache=True,
            )

            lm_logits = self.to_logits(outputs[0])
            (decoder_past_key_values, _) = self.make_cache_tensors(
                outputs.past_key_values
            )
            return {
                "logits": lm_logits,
                "decoder_past_key_values": decoder_past_key_values,
            }

        return convert_variables_to_constants_v2(
            decoder_serving.get_concrete_function()
        )


class ModelWrapping(tf.Module):
    """
    Wrapper class for specifying signatures
    """

    @tf.function(input_signature=encoder_signature)
    def encoder_serving(self, inputs):
        return {
            "last_hidden_state": self.__encoder_serving_f(
                input_features=inputs["input_features"],
            )[0]
        }

    @tf.function(input_signature=decoder_init_signature)
    def decoder_init_serving(self, inputs):
        decoder_output = self.__decoder_init_serving_f(
            decoder_input_ids_init=inputs["decoder_input_ids_init"],
            encoder_state_init=inputs["encoder_state_init"],
        )
        return {
            "logits_init": decoder_output[2],
            "decoder_past_key_values_init": decoder_output[0],
            "encoder_past_key_values_init": decoder_output[1],
        }

    @tf.function(input_signature=decoder_cache_signature)
    def decoder_cache_serving(self, inputs):
        decoder_output = self.__decoder_cache_serving_f(
            decoder_input_ids=inputs["decoder_input_ids"],
            encoder_state=inputs["encoder_state"],
            decoder_past_key_values=inputs["decoder_past_key_values"],
            encoder_past_key_values=inputs["encoder_past_key_values"],
        )
        return {
            "logits": decoder_output[1],
            "decoder_past_key_values_out": decoder_output[0],
        }

    def export(self, export_path):
        signatures = {
            "encoder": self.encoder_serving,
            "decoder_init": self.decoder_init_serving,
            "decoder_with_past": self.decoder_cache_serving,
        }

        tf.saved_model.save(self, export_path, signatures=signatures)

    def __init__(
        self, encoder_serving_f, decoder_init_serving_f, decoder_cache_serving_f
    ):
        self.__encoder_serving_f = encoder_serving_f
        self.__decoder_init_serving_f = decoder_init_serving_f
        self.__decoder_cache_serving_f = decoder_cache_serving_f


whisper_model = WhisperExport.from_pretrained(MODEL_NAME, from_pt=True)

model_wrapping = ModelWrapping(
    whisper_model.make_encoder_serving(),
    whisper_model.make_decoder_init_serving(),
    whisper_model.make_decoder_serving(),
)

model_wrapping.export(EXPORT_PATH)
whisper_model.config.save_pretrained(assets_folder)

processor = WhisperProcessor.from_pretrained(MODEL_NAME)
processor.save_pretrained(assets_folder)

**Comment by minhduc210196** [comment]
my code in 
https://colab.research.google.com/drive/1dkIfVZf8WtQAVLKaSt8s95_29BHcLOlw#scrollTo=8xN4MqZagxCQ

**Comment by minhduc210196** [comment]
All PyTorch model weights were used when initializing WhisperExport.

All the weights of WhisperExport were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use WhisperExport for predictions without further training.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-3156f99a4cea> in <cell line: 207>()
    206 
    207 model_wrapping = ModelWrapping(
--> 208     whisper_model.make_encoder_serving(),
    209     whisper_model.make_decoder_init_serving(),
    210     whisper_model.make_decoder_serving(),

11 frames
/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/importer.py in _import_graph_def_internal(graph_def, input_map, return_elements, validate_colocation_constraints, name, producer_op_list)
    495   # _ProcessNewOps.
    496   with graph._mutation_lock():  # pylint: disable=protected-access
--> 497     with c_api_util.tf_buffer(graph_def.SerializeToString()) as serialized:
    498       try:
    499         with graph._c_graph.get() as c_graph:  # pylint: disable=protected-access

ValueError: Message tensorflow.GraphDef exceeds maximum protobuf size of 2GB: 2549145890

**Comment by minhduc210196** [comment]
Please help me. Thank u very much

**Comment by tilakrayal** [comment]
@minhduc210196,
I do not have access to the link you have provided. Could you please provide the required permissions to view the files.

Also the error message **ValueError: Message tensorflow.GraphDef exceeds maximum protobuf size of 2GB** indicates that the TensorFlow GraphDef object, which is a protocol buffer exceeds the maximum allowed size of 2GB. 

This can happen when the graph is too large or has too many nodes. Could you please try reducing the size of the graph by removing unnecessary nodes or operations. Additionally, you can split the graph into smaller sub-graphs and run them separately.
https://github.com/tensorflow/tensorflow/issues/47326
https://github.com/tensorflow/tensorflow/issues/55692


Thank you!
