### ISSUE TITLE
Inconsistency of `LeftShift` between eager mode and JIT=true

### ISSUE THREAD

**Issue by zoux1a** [tensorflow/tensorflow#62869]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.14.1

### Custom code

Yes

### OS platform and distribution

Ubuntu 22.04.3 LTS (x86_64)

### Current behavior?

Different outputs of `tf.raw_ops.LeftShift` between eagermode and op mode are observed.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

class Network(tf.Module):
    def __init__(self):
        super().__init__()

    @tf.function(jit_compile=True)
    def __call__(self, x, y):
      x = tf.raw_ops.LeftShift(y=x, x=y)        
      return x

m = Network()
tensor_x = tf.random.uniform([],minval=0,maxval=255,dtype=tf.int32)
tensor_y = tf.random.uniform([9],minval=0,maxval=255,dtype=tf.int32)
inp = {
    "x": tensor_x,
    "y": tensor_y
}

with tf.device('/CPU:0'):
    tf.config.run_functions_eagerly(True)
    no_op_res = m(**inp)
    tf.config.run_functions_eagerly(False)
    with tf.device('/CPU:0'):
        op_res = m(**inp)

    tf.debugging.assert_near(tf.cast(no_op_res, tf.float64), tf.cast(op_res, tf.float64), atol=0.001, rtol=0.001)
```

### Relevant log output

```shell
raise errors.InvalidArgumentError(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b''
b'x and y not equal to tolerance rtol = tf.Tensor(0.001, shape=(), dtype=float64), atol = tf.Tensor(0.001, shape=(), dtype=float64)'
b'x (shape=(9,) dtype=float64) = '
-2147483648.0, 0.0, 0.0, ...
b'y (shape=(9,) dtype=float64) = '
0.0, 0.0, 0.0, ...
```

**Comment by Venkat6871** [comment]
Hi **@zoux1a** ,

I was able to reproduce the issue on colab using TF v2.15, and TF-nightly. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/30f067f2c0c10cbc396fb8032b6e0b07/62869_2-15-nightly-v.ipynb) here for reference.

Thank you!

**Comment by Venkat6871** [comment]
Hi **@zoux1a** ,

- Ensure that the input tensors tensor_x and tensor_y have the correct shapes and data types. The LeftShift operation requires that the first tensor (x) be an integer tensor, and the second tensor (y) can be either an integer or a boolean tensor.
-  The raw_ops.LeftShift operation is used to perform bitwise left shift operations on tensors. However, this operation is only available for integer tensors. If you need to perform a bitwise left shift on a boolean tensor, you should use the bitwise.left_shift operation instead.
- Here i used bitwise.left_shift, it works fine. i am providing [gist](https://colab.sandbox.google.com/gist/Venkat6871/e2e891a2ee396422b1da55014f63e20d/62869_2-16-1-v.ipynb) for your reference.

Thank you!
