### ISSUE TITLE
tf.matMul

### ISSUE THREAD

**Issue by N1k0l1n** [tensorflow/tensorflow#62875]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

3.9.0

### Custom code

Yes

### OS platform and distribution

Windows 10

### Python version

Python 3.12.1

### Current behavior?

Im new to tensorflow js, so please excuse me if the issue is resolved prior. I have a problem iwth tf.matMul, when trying to do this operation with  a 2x2 matrix, and the first value is wrong.

### Standalone code to reproduce the issue

```shell
const a = tf.tensor2d([[1, 2], [3, 4]]);
const b = tf.tensor2d([[5, 7], [6, 8]]);

a.matMul(b).print();  // Expected Output: [[19, 23], [39, 53]]

Insted I get : [[17, 23], [39, 53]]
```

**Comment by MoritzMSP** [comment]
@tilakrayal in the given case the output [[17, 23], [39, 53]] is correct. You're doing a matrix multiplication with the following matricies:
```
|1  2|  *  |5  7|
|3  4|  *  |6  8|  
```

so the first element will be 
`1*5 + 2*6 =14`
Perhaps you've reversed 6 and 7.

**Comment by N1k0l1n** [comment]
Yeah, I switched the possition and i didnt evene noticed. Im terrebly sorry. Thank you for your time
