### ISSUE TITLE
remapper_test fails on AARCH64 with --config=mkl_aarch64_threadpool

### ISSUE THREAD

**Issue by elfringham** [tensorflow/tensorflow#62882]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

git HEAD

### Custom code

No

### OS platform and distribution

Ubuntu 20.04

### Mobile device

n/a

### Python version

3.9.17

### Bazel version

6.5.0

### GCC/compiler version

17.0.0

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current behavior?

The tests //tensorflow/core/grappler/optimizers:remapper_test and //tensorflow/core/grappler/optimizers:mkl_remapper_test will fail on AARCH64 when built with --config=mkl_aarch64_threadpool and run with TF_ENABLE_ONEDNN_OPTS=1. But also remapper_test will fail those tests that are not skipped even with TF_ENABLE_ONEDNN_OPTS=0. All tests in mkl_remapper_test are skipped in that case.

### Standalone code to reproduce the issue

```shell
bazel test --config=mkl_aarch64_threadpool --test_timeout=500,900,3000,-1 --copt=-flax-vector-conversions --test_env=TF_ENABLE_ONEDNN_OPTS=1 --test_env=TF2_BEHAVIOR=1 --define=tf_api_version=2 --test_size_filters=small,medium --test_lang_filters=py,cc --test_output=errors --verbose_failures=true --test_keep_going --notest_verbose_timeout_warnings --action_env=PYTHON_BIN_PATH=/usr/local/bin/python3 --test_env=PORTSERVER_ADDRESS=@unittest-portserver --build_tag_filters=-no_oss,-oss_excluded,-oss_serial,-v1only,-benchmark-test,-no_aarch64,-gpu,-tpu,-no_oss_py39,-no_oss_py310 --test_tag_filters=-no_oss,-oss_excluded,-oss_serial,-v1only,-benchmark-test,-no_aarch64,-gpu,-tpu,-no_oss_py39,-no_oss_py310 --jobs=75 --build_tests_only --copt=-Og --copt=-ggdb --strip=never --per_file_copt=external/org_brotli/c/dec/decode.c@-O2 -- //tensorflow/core/grappler/optimizers:remapper_test
```

### Relevant log output

```shell
[ RUN      ] RemapperTest.FuseConv2DWithBatchNorm
tensorflow/core/grappler/optimizers/remapper_test.cc:2141: Failure
Expected equality of these values:
  node.op()
    Which is: "FusedBatchNorm"
  "_FusedConv2D"
tensorflow/core/grappler/optimizers/remapper_test.cc:2142: Failure
Expected: (node.input_size()) >= (6), actual: 5 vs 6
[  FAILED  ] RemapperTest.FuseConv2DWithBatchNorm (3 ms)
[ RUN      ] RemapperTest.FuseConv2DWithBatchNormAndActivation
tensorflow/core/grappler/optimizers/remapper_test.cc:2240: Failure
Expected equality of these values:
  node.op()
    Which is: "Identity"
  "_FusedConv2D"
tensorflow/core/grappler/optimizers/remapper_test.cc:2241: Failure
Expected: (node.input_size()) >= (6), actual: 1 vs 6
[  FAILED  ] RemapperTest.FuseConv2DWithBatchNormAndActivation (3 ms)
[ RUN      ] RemapperTest.FuseConv3DWithBiasAndAddN
tensorflow/core/grappler/optimizers/remapper_test.cc:2321: Failure
Expected equality of these values:
  node.op()
    Which is: "AddN"
  "_FusedConv3D"
tensorflow/core/grappler/optimizers/remapper_test.cc:2322: Failure
Expected: (node.input_size()) >= (3), actual: 2 vs 3
[  FAILED  ] RemapperTest.FuseConv3DWithBiasAndAddN (285 ms)
[ RUN      ] RemapperTest.FuseConv3DWithBiasAndAdd
tensorflow/core/grappler/optimizers/remapper_test.cc:2392: Failure
Expected equality of these values:
  node.op()
    Which is: "Add"
  "_FusedConv3D"
tensorflow/core/grappler/optimizers/remapper_test.cc:2393: Failure
Expected: (node.input_size()) >= (3), actual: 2 vs 3
[  FAILED  ] RemapperTest.FuseConv3DWithBiasAndAdd (272 ms)
```

**Comment by elfringham** [comment]
@TensorFlow-MKL 
@penpornk 
@davsva01

**Comment by elfringham** [comment]
It seems that certain parts of tensorflow/core/grappler/optimizers/remapper.cc are disabled with the presence of DNNL_AARCH64_USE_ACL and this is resulting in the test failures.

**Comment by elfringham** [comment]
@milpuz01 Do these features still need to be disabled for the best performance with ACL?

**Comment by milpuz01** [comment]
@elfringham, thanks for your fix.

> @milpuz01 Do these features still need to be disabled for the best performance with ACL?
Yes, they are still needed. 

Unfortunately, we should have updated the tests initially when the changes were made in this PR: https://github.com/tensorflow/tensorflow/pull/60723, but I think back then the `remapper_test` was disabled and we didn't see it failing.

Probably the right fix for AArch64 would be to still execute the tests, but check the name of the operators and arguments matches the operators and arguments without the optimisation. In this way we will have testing of `remapper` phase too for occasions when we do not lower to oneDNN on AArch64 and if there are any changes of future we will be able to catch them. We will look into making those changes.
