### ISSUE TITLE
Need Privacy Manifest(iOS)

### ISSUE THREAD

**Issue by juntec** [tensorflow/tensorflow#62893]
### Issue type

Others

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.15.0

### Custom code

Yes

### Current behavior?

Hello.
I'm incorporating tensorflow light into my iOS application.
From Fall 2023 you’ll receive an email from Apple if you upload an app to App Store Connect that uses required reason API without describing the reason in its privacy manifest file. From Spring 2024, apps that don’t describe their use of required reason API in their privacy manifest file won’t be accepted by App Store Connect.

It's described here in detail.
https://developer.apple.com/news/?id=r1henawx
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

Is it necessary to add PrivacyManifest in tensorflow light? If necessary, please add a PrivacyManifest.

Thank you.

### Standalone code to reproduce the issue

```shell
```

**Comment by pkgoogle** [comment]
Hi @yishuangP, can you please take a look? Thanks.

**Comment by dwang0721** [comment]
any updates?
I also need a tensorflow PrivacyManifest for our iOS application.

**Comment by tastysauce** [comment]
Another voice hoping that this on your radar before the Apple deadline

**Comment by tinder-felixchangoo** [comment]
Hey there following up on this as we're nearing closer to the deadline for Privacy Manifest Compliance (ie May 1st). Are there any new updates here?

**Comment by tareksabry1337** [comment]
I don't think TensorFlow will do anything, I have rolled out my own Unofficial SPM fork and I'll probably add the privacy manifest there https://github.com/tareksabry1337/TensorFlowLiteC

**Comment by dwang0721** [comment]
I added the manifest myself.

**Comment by yishuangP** [comment]
Hi really sorry for the delay, merging https://github.com/tensorflow/tensorflow/pull/66030 which adds the privacy manifests.

**Comment by pkgoogle** [comment]
Hi @juntec, please check to see if your issue is now resolved with that PR https://github.com/tensorflow/tensorflow/pull/66030, thanks.
