### ISSUE TITLE
Run tensorboard embedding visualization learning in backgroup (inactive tab of Chrome)

### ISSUE THREAD

**Issue by machi2074** [tensorflow/tensorflow#6290]
Hi, 

I came across a chrome problem when running embedding visualization using tensorboard. The visualization learning (t-SNE) takes hours to finish. If I switch browser to another tab, the tensorboard tab becomes inactive. Any javascript stops working on the inactive tab. This seems to be the root cause: https://blog.pivotal.io/labs/labs/chrome-and-firefox-throttle-settimeout-setinterval-in-inactive-tabs

I tried making the tab a standalone window, it doesn't work.

That means I have to dedicate a laptop to run the learning. This is awful. Does anyone have a solution? Thanks

**Comment by andydavis1** [comment]
Please try asking this question on StackOverflow with the `tensorflow` tag.
