### ISSUE TITLE
No such models 'TensorFlowLiteC' or 'TensorFlowLiteSwift'

### ISSUE THREAD

**Issue by QiyasovH** [tensorflow/tensorflow#62901]
Hello. I try to install pod 'TensorFlowLiteSwift' , when terminal write me that installation is done. During building the project, I get errors "no such models 'TensorFlowLiteC' or 'TensorFlowLiteSwift'"

**Comment by sushreebarsa** [comment]
@QiyasovH Please make sure CocoaPods is correctly installed and configured in your project. Follow the official guide for your system: https://guides.cocoapods.org/using/getting-started
Could you double-check your Podfile:
Ensure you have the correct version of TensorFlowLiteSwift specified:
```
pod 'TensorFlowLiteSwift', '~> 2.6.0'

```
Also avoid including both TensorFlowLiteSwift and TensorFlowLiteObjC as they share the same base (TensorFlowLiteC). Please choose the language compatible with your project.
Kindly run pod install again to re-download and link dependencies.
Thank you!

**Comment by QiyasovH** [comment]
Just update CocoaPods. Version is 1.15.2.
I get the same error No such models 'TensorFlowLiteC'. 
When entered to folder Pods->TensorFlowLiteC , this folder is empty

**Comment by sushreebarsa** [comment]
@QiyasovH 
In order to expedite the trouble-shooting process, please provide TF version you are using and a code snippet to reproduce the issue reported here. Thank you!

**Comment by QiyasovH** [comment]
<img width="573" alt="Снимок экрана 2024-02-07 в 15 07 52" src="https://github.com/tensorflow/tensorflow/assets/85330968/8c1b5f2d-3fd7-42c8-b23a-c5f4178fbd12">
<img width="1397" alt="Снимок экрана 2024-02-07 в 15 08 40" src="https://github.com/tensorflow/tensorflow/assets/85330968/ab8e7f16-7ddf-4dd4-9a4e-0d7a1e5840d1">

<img width="536" alt="Снимок экрана 2024-02-07 в 15 09 23" src="https://github.com/tensorflow/tensorflow/assets/85330968/0c577676-708e-43ee-a3e3-5354b3f66c7c">

**Comment by sushreebarsa** [comment]
@QiyasovH Could you please provide the code details in colab gist or notebook as it would be helpful to analyze the issue?
Thank you!

**Comment by arcslash** [comment]
Did anyone get a solution for this?
