### ISSUE TITLE
Checksum Error during TensorFlow Lite Build for kissfft v130

### ISSUE THREAD

**Issue by jyochichili** [tensorflow/tensorflow#62944]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.6.2

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.8

### Current behavior?

While building the application with Tensorflow v2.6.2 downloaded from source https://github.com/tensorflow/tensorflow/archive/v2.6.2.zip and with Tensorflow PYPI package(2.6.2) installed, I am getting checksum error while downloading kissfft library.

This issue is seen from past 8 days.

### Standalone code to reproduce the issue

```shell
Try downloading and verifying the kissfft installation, 
downloading http://mirror.tensorflow.org/github.com/mborgerding/kissfft/archive/v130.zip
```

### Relevant log output

```shell
downloading http://mirror.tensorflow.org/github.com/mborgerding/kissfft/archive/v130.zip
+ [[ 0 -eq 0 ]]
+ break
++ openssl dgst -md5 /tmp/tmp.H0LiyFKNBY/temp_file
++ sed 's/.* //g'
Checksum error for 'http://mirror.tensorflow.org/github.com/mborgerding/kissfft/archive/v130.zip'. Expected 438ba1fef5783cc5f5f201395cc477ca but found d41d8cd98f00b204e9800998ecf8427e
+ DOWNLOADED_MD5=d41d8cd98f00b204e9800998ecf8427e
+ '[' 438ba1fef5783cc5f5f201395cc477ca '!=' d41d8cd98f00b204e9800998ecf8427e ']'
+ echo 'Checksum error for '\''http://mirror.tensorflow.org/github.com/mborgerding/kissfft/archive/v130.zip'\''. Expected 438ba1fef5783cc5f5f201395cc477ca but found d41d8cd98f00b204e9800998ecf8427e'
+ exit 1
```

**Comment by sushreebarsa** [comment]
@jyochichili Please double-check that the downloaded KissFFT-v130-RELEASE-X86_64.zip file is complete and hasn't been corrupted during download. Some file-hosting services might introduce errors. Kindly ensure your internet connection is stable and that no interruptions occurred during the download. We recommend you to kindly upgrade to the latest TF version as you are using an older version which is not actively supported.
Thank you!

**Comment by jyochichili** [comment]
Hi @sushreebarsa, 
Thank you for the response.
you are right that the kissfft lib is not properly downloaded or corrupted, but I doubt if network issue is the culprit here, as the other libs (tf_lite_micro_person_data_grayscale_2020_05_27, ruy, gemmlowp) has no issue in downloading. I have also noticed that the in the case of failure, the incorrect checksum is always same, which I assume won't be the case when the file is corrupted. Also switching to the latest version won't help in my case as my models are only compatible to v2.6.2.
Can you please help through this issue?

Thanks.

Please note the disk size of downloaded Kissftt lib(tensorflow-2.6.2/tensorflow/lite/micro/tools/make/downloads/kissfft) in the failure scenario is only 4K (original size 248K), so I can confirm that the file is not properly downloaded.

**Comment by sushreebarsa** [comment]
@jyochichili Sometimes, downloads can fail due to temporary network hiccups. Please retry downloading the kissfft library a few times. If possible, kindly change the download directory to a location with sufficient space. 
Thank you!

**Comment by jyochichili** [comment]
I have found that within tflite(v2.6.2), the URL for downloading the KISSFFT library doesn’t involve secure download(https), which seems to be causing an incomplete download of KISSFFT library. The issue doesn’t persist in the later versions, as the URL has been updated to use a secure https connection.

Thanks.

**Comment by sushreebarsa** [comment]
@jyochichili Thank you for the response!
Could you please move this issue to closed status if it has been resolved?
Thank you!
