### ISSUE TITLE
`tf.raw_ops.Conv2DBackpropInput` aborts due to lack of input check

### ISSUE THREAD

**Issue by Sehun0819** [tensorflow/tensorflow#62950]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.17

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 22.04 LTS

### Python version

3.11.7

### Bazel version

6.5.0

### GCC/compiler version

clang 16

### Current behavior?

Calling `tf.raw_ops.Conv2DBackpropInput` aborts with wrong size of `strides` due to lack of check. Additional `OP_REQUIRES` which makes sure `stridees_.size() >= 4` would be required.

[Bug Location](https://github.com/tensorflow/tensorflow/blob/8340d650e1c9d396b49900c8e374da87a3d24cea/tensorflow/core/kernels/mkl/mkl_conv_ops.h#L643-L645):
```C++
    OP_REQUIRES_OK(context, context->GetAttr("strides", &strides_));
    int stride_n = GetTensorDim(strides_, data_format_, 'N');
    int stride_c = GetTensorDim(strides_, data_format_, 'C');
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

tf.raw_ops.Conv2DBackpropInput(
    input_sizes=[1,1,1,1],
    filter=tf.random.normal([1,1,1,1]),
    out_backprop=tf.random.normal([1,1,1,1]),
    strides=[1,1,1],
    padding="VALID",
    dilations=[1,1,1,1])
```

### Relevant log output

```shell
2024-02-13 17:53:01.673661: F ./tensorflow/core/util/tensor_format.h:428] Check failed: index >= 0 && index < num_total_dims Invalid index from the dimension: 3, 0, C
Aborted (core dumped)
```

**Comment by sushreebarsa** [comment]
@Sehun0819 Could you please let us know which TF version you are using ? I tried to replicate the issue reported [here](https://colab.research.google.com/gist/sushreebarsa/53bc365aabf476ce3a6bdea5ec62e32d/62950.ipynb) but I faced `InvalidArgumentError` . Kindly check the gist and let us know?
Thank you!

**Comment by Sehun0819** [comment]
@sushreebarsa
Hi!
First, I'm using tf 2.17 as I mentioned.

I think this issue is related to [intel code](https://github.com/tensorflow/tensorflow/blob/8340d650e1c9d396b49900c8e374da87a3d24cea/tensorflow/core/kernels/mkl/mkl_conv_ops.h#L643-L645) which lacks check of strides size. In my opinion the invocation in gist seems to execute [here](https://github.com/tensorflow/tensorflow/blob/8340d650e1c9d396b49900c8e374da87a3d24cea/tensorflow/core/kernels/conv_grad_input_ops.h#L294-L296) instead of MKL kernel, because of the environment of gist is not intel.
I was able to get the same output when I ran the script with `TF_ENABLE_ONEDNN_OPTS=0`.
So, would you check the reproducibility in intel environment?

**Comment by SuryanarayanaY** [comment]
Hi @Sehun0819 ,

The issue is replicable by enabling TF_ENABLE_ONEDNN_OPTS = 1. Attached screenshot for reference.

<img width="1502" alt="Screenshot 2024-03-02" src="https://github.com/tensorflow/tensorflow/assets/116063290/04f71d21-4cc3-4e99-b6e5-701214bb03b4">

**Comment by tilakrayal** [comment]
@Sehun0819,
I tried to execute the mentioned code on both GPU and CPU with tf-nightly by enabling **TF_ENABLE_ONEDNN_OPTS = 1** and observed that it is not aborting as previous versions. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/7e20f38ae1a9506ac7c56c2eee4a3ba3/untitled1953.ipynb). Thank you!
