### ISSUE TITLE
Not able to add metadata to tfltie model with 2 output heads

### ISSUE THREAD

**Issue by akuma308** [tensorflow/tensorflow#62971]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.0.5 LTS
- TensorFlow installation (pip package or built from source): pip 
- TensorFlow library (version, if pip package or github SHA, if built from source):   tensorflow==2.10.0

### 2. Code

Below is the screenshot of tflite model properties.
![model_properties](https://github.com/tensorflow/tensorflow/assets/41137005/4221e238-6a9f-4fac-a121-965237577ce6)

After this when we try adding the model metadata via below code snippet, it throws us error . (Taking inspiration from [here](https://www.tensorflow.org/lite/models/convert/metadata_writer_tutorial#image_segmenters) )

`ImageSegmenterWriter = image_segmenter.MetadataWriter
_MODEL_PATH = "custom_model.tflite"
# Task Library expects label files that are in the same format as the one below.
_LABEL_FILE = "custom_model_labels.txt"
_SAVE_TO_PATH = "custom_model_metadata.tflite"

# Normalization parameters is required when reprocessing the image. It is
# optional if the image pixel values are in range of [0, 255] and the input
# tensor is quantized to uint8. See the introduction for normalization and
# quantization parameters below for more details.
# https://www.tensorflow.org/lite/models/convert/metadata#normalization_and_quantization_parameters)
_INPUT_NORM_MEAN = 127.5
_INPUT_NORM_STD = 127.5

# Create the metadata writer.
writer = ImageSegmenterWriter.create_for_inference(
    writer_utils.load_file(_MODEL_PATH), [_INPUT_NORM_MEAN], [_INPUT_NORM_STD],
    [_LABEL_FILE])

# Verify the metadata generated by metadata writer.
print(writer.get_metadata_json())

# Populate the metadata into the model.
writer_utils.save_file(writer.populate(), _SAVE_TO_PATH)
`
The error we get is follows 
`ValueError: The number of output tensors (2) should match the number of output tensor metadata (1)`

Is there a different way to add metadata for image segmenter,did my research, also understood that the deeplab_v3 has 1 output head and that is why the above addition of metadata make sense.
Please suggest.

**Comment by sushreebarsa** [comment]
@akuma308 The most straightforward solution is to create individual metadata entries for each of the two output tensors. Please refer to the ImageSegmenterWriter [documentation](https://www.tensorflow.org/lite/api_docs/java/org/tensorflow/lite/task/vision/segmenter/ImageSegmenter) for examples on how to construct metadata objects for multiple outputs. Kindly use the latest TF version and let us know?
Thank you!
