### ISSUE TITLE
`tf.raw_ops.DrawBoundingBoxesV2` aborts with inappropriate input

### ISSUE THREAD

**Issue by Sehun0819** [tensorflow/tensorflow#62981]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.17

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 22.04 LTS

### Python version

3.11.7

### Bazel version

6.5.0

### GCC/compiler version

clang 16

### Current behavior?

`tf.raw_ops.DrawBoundingBoxesV2` aborts with inappropriate input([gist](https://colab.research.google.com/drive/1k5R4CumbxgK0Mn4SRAdYFmBvWQfnw7RV#scrollTo=7ng8DC7cxLH6)).

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

tf.raw_ops.DrawBoundingBoxesV2(
    images=tf.random.normal([1,1,1]),
    boxes=tf.random.normal([1]),
    colors=0.0,
    name=None
)
```

### Relevant log output

```shell
2024-02-18 00:55:43.130977: F tensorflow/core/framework/tensor_shape.cc:357] Check failed: d < dims() (3 vs. 3)
Aborted (core dumped)
```

**Comment by sushreebarsa** [comment]
@Sehun0819 Could you please provide the access to the codebase or give the gist to replicate the issue reported?
Please ensure both tensors have the same data type, usually tf.float32. For input requirements please refer to this [doc](https://www.tensorflow.org/api_docs/python/tf/image/draw_bounding_boxes). I faced a different [error](https://colab.research.google.com/gist/sushreebarsa/1eb1d147b40ffc034f11c33a47405bb1/62981.ipynb) while replicating the issue.
Thank you!

**Comment by Sehun0819** [comment]
@sushreebarsa
Sorry for confusing. `colors` should be `0.0`, not `0.0f`.
Please check [it](https://colab.research.google.com/drive/1wzwA3ALjPxIBaP-aajrYnKHiOWv2FgDg?usp=sharing).

**Comment by sushreebarsa** [comment]
@sachinprasadhs I was able to replicate the issue reported [here](https://colab.research.google.com/gist/sushreebarsa/950efa69aa2ec419266732519795e09f/untitled5.ipynb). Please have a look at this issue.
Thank you!
