### ISSUE TITLE
Fails to convert to TFLite model in TF 2.16.0rc0

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#62989]
### 1. System information

- Ubuntu 22.04
- Built from source, TF 2.16.0rc0
- TensorFlow library: TF 2.16.0 (branch r2.16), commit 03d0e0b
  
### 2. Code

Code attached.
[ConvertToTFLite.py.txt](https://github.com/tensorflow/tensorflow/files/14324713/ConvertToTFLite.py.txt)

### 3. Failure after conversion
Conversion of a model is successful when using TF2.15.0 or earlier. Conversion of a model created with TF2.15.0 or earlier fails when using TF 2.16.0 for conversion. [The initial keras model is available here.](https://www.dropbox.com/scl/fi/1ldtdr90qsgbns0snu2ba/TF2.15.0_model_classifier_CNN.keras?rlkey=lf1cm56oyt21v1xqer40t0b1w&dl=0) Log provided below.

### Log - attached.
[log.txt](https://github.com/tensorflow/tensorflow/files/14324717/log.txt)

**Comment by feranick** [comment]
When a keras model is created with TF2.16.0, the conversion still fails but with a different error:

[log2.txt](https://github.com/tensorflow/tensorflow/files/14324786/log2.txt)

**Comment by pkgoogle** [comment]
Hi @feranick, do you mind uploading the model on github via a zip file? There are licensing issues with dropbox so we cannot use it. Thanks for your help.

**Comment by feranick** [comment]
The models are quite large and beyind the github 25MB limit. Here they are from an open server:

https://gridedgedm.mit.edu/tf_tmp/TF2.15.0_model_classifier_CNN.keras
https://gridedgedm.mit.edu/tf_tmp/TF2.16.0_model_classifier_CNN.keras

**Comment by pkgoogle** [comment]
Hi @feranick, I was able to replicate on 2.16 in this [gist](https://colab.sandbox.google.com/gist/pkgoogle/ed2e7fdf2acb7b0d9c8bbe5921cb64a3/62989.ipynb) (You have to upload your TF2.16.0... file to colab). Is there any particular ops you are using in this model or do you have any additional information on the creation of this model?

Hi @majiddadashi, can you please take a look? Thanks.

**Comment by feranick** [comment]
> Hi @feranick, I was able to replicate on 2.16 in this [gist](https://colab.sandbox.google.com/gist/pkgoogle/ed2e7fdf2acb7b0d9c8bbe5921cb64a3/62989.ipynb) (You have to upload your TF2.16.0... file to colab). Is there any particular ops you are using in this model or do you have any additional information on the creation of this model?
> 
Hi @pkgoogle, thank you for looking into this. This below is a snapshot of the code relevant to the creation of the model. I hope it's helpful. I have been using it for a long time with TF2.15.0 and below with no issues...
[model.txt](https://github.com/tensorflow/tensorflow/files/14378663/model.txt)

**Comment by feranick** [comment]
Here's also the tf.lite.experimental.Analyzer.analyze(model_content=tflite_model) output for both the TF2.150.0 and TF2.16.0rc0 models (the latter failing).
[analyzer_2.15_model.txt](https://github.com/tensorflow/tensorflow/files/14378749/analyzer_2.15_model.txt)
[analyzer_2.16_model.txt](https://github.com/tensorflow/tensorflow/files/14378750/analyzer_2.16_model.txt)

**Comment by feranick** [comment]
If you casually compare the config.jason in the keras model files you can see that the variable `batch_input_shape` in TF2.15.0 was changed to `batch_shape` in TF2.16. This variable remain undefined in TF2.15. The config.json are attached.
[TF2.16rc0_config.json](https://github.com/tensorflow/tensorflow/files/14378950/TF2.16rc0_config.json)
[TF2.15_config.json](https://github.com/tensorflow/tensorflow/files/14378952/TF2.15_config.json)

**Comment by feranick** [comment]
Even replacing `batch_shape` with `batch_input_shape`, there are still errors when converting the keras model into a tflite:
```
[/usr/local/lib/python3.10/dist-packages/keras/src/optimizers/optimizer.py](https://localhost:8080/#) in _process_kwargs(self, kwargs)
    140                 )
    141             else:
--> 142                 raise TypeError(
    143                     f"{k} is not a valid argument, kwargs should be empty "
    144                     " for `optimizer_experimental.Optimizer`."

TypeError: loss_scale_factor is not a valid argument, kwargs should be empty  for `optimizer_experimental.Optimizer`.
```
`loss_scale_factor` seems to be defined only in TF2.16.0, but there not in the TF2.15 model.

**Comment by feranick** [comment]
Tested the above models with the pre-release, TF 2.16.0-rc0. Now they both crash. Log attached.
[TF2.15_convertLog.txt](https://github.com/tensorflow/tensorflow/files/14425168/TF2.15_convertLog.txt)
[TF2.16_convertLog.txt](https://github.com/tensorflow/tensorflow/files/14425169/TF2.16_convertLog.txt)

**Comment by feranick** [comment]
So in summary: any model built with `TF2.15` or earlier or with `TF2.16.0-rc0` using `keras 2` (and `tf_keras=2.16rc0`) can be successfully converted in tflite. Any model built with `TF2.16.0-rc0` using `keras 3` **cannot** be converted to tflite. Any model built with `TF2.15` or earlier or with `TF2.16.0-rc0` using `keras 2` cannot be converted using `TF2.16.0-rc0` in keras 3 mode.

In essence, conversion to tflite is completely broken with keras 3.

**Comment by ymodak** [comment]
Adding @advaitjain for visibility.

**Comment by feranick** [comment]
The models created with `keras v2` and `v3` appear to be completely incompatible with each other. The way to have a successful conversion is to basically do the training, model loading and conversion within the same keras version.
So for `keras v2`, saving after training:
```
import tf_keras as keras
model.save(dP.model_name)
```
for the TFlite conversion:
```
def convertModelToTFLite(model_file):
    import tensorflow as tf
    import tf_keras as keras
    model = keras.models.load_model(model_file)
    converter = tf.lite.TFLiteConverter.from_keras_model(model)    # TensorFlow 2.15 and earlier
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    tflite_model = converter.convert()
    tf.lite.experimental.Analyzer.analyze(model_content=tflite_model)
    open(convFile, "wb").write(tflite_model)
```
For loading a `v2` model:
```
model = keras.models.load_model(model_name)
```
For `keras v3`, saving after training:
```
import keras
model.export(dP.model_name)
```
For loading a `v3` model:
```
model = keras.models.Sequential()
model.add(keras.layers.TFSMLayer(model_name, call_endpoint='serve'))
```
for the TFlite conversion:
```
 def convertModelToTFLite(model_file):
    import tensorflow as tf
    import keras
    model = keras.layers.TFSMLayer(model_file, call_endpoint='serve') # TensorFlow >= 2.16.0
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
   
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    tflite_model = converter.convert()
    tf.lite.experimental.Analyzer.analyze(model_content=tflite_model)
    open(convFile, "wb").write(tflite_model)
```

This of course is not ideal in the long term, when "legacy" `v2` models will require maintenance of legacy code to deal with it. A solution could be an ad-hoc conversion API for models from `v2` to `v3`.

**Comment by pkgoogle** [comment]
Hi @feranick,

I was able to convert your model w/ our new library [AI-Edge-Torch](https://github.com/google-ai-edge/ai-edge-torch), with this script:

```py
from types import SimpleNamespace

import ai_edge_torch
import torch
import torch.nn as nn


class CustomModel(nn.Module):
    def __init__(self, input_shape, num_classes, params):
        super(CustomModel, self).__init__()
        self.params = params
        self.input_shape = input_shape
        self.num_classes = num_classes

        # Convolutional layers
        self.conv_layers = nn.ModuleList()
        for i in range(len(params.channels)):
            self.conv_layers.append(nn.Sequential(
                nn.Conv2d(input_shape[1] if i == 0 else params.channels[i-1], params.channels[i], (1, params.kernel_widths[i])),
                nn.ReLU(),
                nn.MaxPool2d((1, params.pooling_widths[i])) if i < len(params.pooling_widths) else nn.Identity(),
                nn.Dropout(params.conv_dropout_rate)
            ))

        # Calculate the size of flattened features
        with torch.no_grad():
            x = torch.randn(*input_shape)
            for layer in self.conv_layers:
                x = layer(x)
            flattened_size = x.numel()

        # Fully connected layers
        self.fc_layers = nn.ModuleList()
        for i in range(len(params.hidden_layer_neurons)):
            self.fc_layers.append(nn.Sequential(
                nn.Linear(flattened_size if i == 0 else params.hidden_layer_neurons[i-1], params.hidden_layer_neurons[i]),
                nn.ReLU(),
                nn.Dropout(params.fc_dropout_rate)
            ))

        # Output layer
        if params.regressor:
            self.output_layer = nn.Linear(params.hidden_layer_neurons[-1], 1)
        else:
            self.output_layer = nn.Linear(params.hidden_layer_neurons[-1], num_classes)
            self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        for layer in self.conv_layers:
            x = layer(x)
        x = x.view(x.size(0), -1)
        for layer in self.fc_layers:
            x = layer(x)
        x = self.output_layer(x)
        if not self.params.regressor:
            x = self.softmax(x)
        return x


params = SimpleNamespace()
params.channels = [6, 12, 24]
params.kernel_widths = [3, 4, 2]
params.pooling_widths = [3, 4, 2]
params.conv_dropout_rate = 0.2
params.hidden_layer_neurons = [128, 256, 128]
params.fc_dropout_rate = 0.2
params.regressor = False


model = CustomModel((1, 3, 224, 224), 10, params)
sample_input = (torch.randn(1, 3, 224, 224),)

edge_model = ai_edge_torch.convert(model.eval(), sample_input)
edge_model.export("custom_model.tflite")
```

Let us know if this resolves your issue.
