### ISSUE TITLE
ValueError: Only fixed_shape_resizeris supported with tflite. Found keep_aspect_ratio_resi

### ISSUE THREAD

**Issue by Dibyajyoti227** [tensorflow/tensorflow#62991]
I am using the latest TensorFlow Model Garden release and TensorFlow 2.
I checked to make sure that this issue has not already been filed.

1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection/configs/tf2/ssd_efficientdet_d0_512x512_coco17_tpu-8.config
2. Describe the bug

While trying to create tflite graph using
`python3 object_detection/export_tflite_graph_tf2.py --pipeline_config_path ssd_efficientdet_d0_512x512_coco17_tpu-8.config --trained_checkpoint_dir /checkpoints --output_directory /ssd_tfexport`

I am getting error,
` File ".local/lib/python3.8/site-packages/object_detection/export_tflite_graph_lib_tf2.py", line 100, in _process_config raise ValueError( ValueError: Only fixed_shape_resizeris supported with tflite. Found keep_aspect_ratio_resizer`

I checked the .config file and looks like the keep_aspect_ratio_resizer is mentioned there. How do I get rid of this error and successfully create tflite graph for tflite conversion?
6. System information

    OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
    TensorFlow installed from (source or binary):pip install
    TensorFlow version (use command below):2.13.1
    Python version:3.8

**Comment by sushreebarsa** [comment]
@Dibyajyoti227 Could you try to replace `keep_aspect_ratio_resizer` with `fixed_shape_resizer` and use latest TF version. Kindly let us know if it helps?
Thank you!
