### ISSUE TITLE
Full Integer Quantization Issue with Multiple Signatures in TensorFlow Lite

### ISSUE THREAD

**Issue by lxzheng** [tensorflow/tensorflow#62996]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Ubuntu 22.04.3 LTS
- TensorFlow installation (pip package or built from source):pip
- TensorFlow library (version, if pip package or github SHA, if built from source):2.15.0

### 2. Code

To help reproduce this issue, I am providing a link to a custom Colab notebook:
[Full Integer Quantization Issue with Multiple Signatures in TensorFlow Lite](https://colab.research.google.com/drive/1zsuqY90d7xFaWb3HPPhiZJcyuFt_a9Ja?usp=sharing)

### 3. Failure after conversion
In the dynamic range quantization process of TensorFlow Lite, it appears that for models with multiple signatures (including aliased ones), the quantization treats references to the same computational graph as a single entity. This is evidenced by the  TFLite ModelAnalyzer report showing two subgraphs with identical sizes, yet the overall model size corresponds roughly to the size of a single subgraph. Specifically:

     TFLite ModelAnalyzer Output of  Dynamic Range Quantization:
```
              Model size:      56528 bytes
    Non-data buffer size:       3384 bytes (05.99 %)
  Total data buffer size:      53144 bytes (94.01 %)
          - Subgraph#0  :      53040 bytes (93.83 %)
          - Subgraph#1  :      53040 bytes (93.83 %)
    (Zero value buffers):          0 bytes (00.00 %)
```
        The total model size is not the sum of the two subgraphs, suggesting that the same subgraph is counted twice but only stored once.

However, the situation is markedly different in the full integer quantization process. Here, the quantization leads to two subgraphs with significantly different sizes, which indicates a distinct treatment of the computational graph segments during quantization. This behavior contrasts with the dynamic range quantization and suggests that the full integer quantization process might interpret or handle the aliased signatures differently, resulting in varied optimization or quantization strategies for the subgraphs. The detailed output is as follows:

     TFLite ModelAnalyzer Output of Full Integer Quantization:
```
              Model size:     259144 bytes
    Non-data buffer size:       4360 bytes (01.68 %)
  Total data buffer size:     254784 bytes (98.32 %)
          - Subgraph#0  :      51120 bytes (19.73 %)
          - Subgraph#1  :     203568 bytes (78.55 %)
    (Zero value buffers):          0 bytes (00.00 %)
```
        Here, the total model size reflects the sum of two distinctly sized subgraphs, highlighting a genuine differentiation in how each subgraph is quantized and stored.

This discrepancy between dynamic range and full integer quantization processes raises questions about the underlying mechanisms TensorFlow Lite employs for handling multiple signatures, especially when they reference the same computational graph segment. The difference in subgraph sizes under full integer quantization suggests that the process may inadvertently treat aliased signatures or multiple references as distinct computational entities, potentially leading to inefficiencies in model size and performance.

**Comment by LakshmiKalaKadali** [comment]
Hi @pkgoogle,

I have reproduced the issue without signatures and with signatures. Without signatures the model is behaving as intended but the full integer model is not quantized properly with signatures. Here is the [gist](https://colab.research.google.com/gist/LakshmiKalaKadali/5fa6c17f8635776539f72f3b2853b125/tflite_quant_keras2.ipynb#scrollTo=nM9CkvDGrpsd) for reference. Tried with the 'tf nightly' version but the session is getting crashed. Here is the [gist](https://colab.research.google.com/gist/LakshmiKalaKadali/35856a3c934e9ccb647dcf87e5c7d033/copy-of-tflite_62996_full-integer_multiple-signatures_keras2.ipynb) with nightly version.

Thank You

**Comment by pkgoogle** [comment]
I was able to replicate with the first gist, @abattery can you please take a look? Thanks.

**Comment by lxzheng** [comment]
@LakshmiKalaKadali @pkgoogle 

Regarding the issue encountered with the 'tf nightly' version, it's important to note that this version utilizes Keras 3, which has known compatibility issues when using the `tf.lite.TFLiteConverter.from_saved_model` or `tf.lite.TFLiteConverter.from_keras_model` method, as reported in the Keras GitHub issue [#19108](https://github.com/keras-team/keras/issues/19108). As a workaround for this compatibility issue, the `model.export` or `keras.export.ExportArchive` methods can be used for exporting models for TFLite conversion.

Here is a gist using Keras 3 to reproduce the issue with that method: [gist](https://colab.research.google.com/drive/1vrjBGoFUUXJQZacnAUFxMKmLpRiAr-km?usp=sharing).

**Comment by gaikwadrahul8** [comment]
Hi, @lxzheng

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/80

Let us know if you have any questions. Thanks.
