### ISSUE TITLE
Specify output tensor for ops from python

### ISSUE THREAD

**Issue by an-kumar** [tensorflow/tensorflow#63]
Sometimes for efficiency it's good to specify the memory in which to write the output of an op (e.g writing to a contiguous part of memory from two functions to save a concat call). Is this supported (it's not in the docs)?

**Comment by jendap** [comment]
Do you have a use case for it in mind?

Tensorflow is trying to optimize memory layout for you. It needs to do that in order to decide on plan for optimal utilization of your compute resources like cpu / gpu(s).

**Comment by an-kumar** [comment]
yeah -- say i want to do, W1*x1 + W2*x2, where x1 and x2 are the outputs of respective subgraphs. It is more efficient to specifically tell each subgraph to write x1 and x2 to a contiguous block of memory, such that W1*x1 + W2*x2 becomes W*[x1 x2]. This comes up in complicated recurrent networks.

I was looking at the code and I see that the op kernels themselves do take outputs to fill. Is it hard to expose that to the python interface? if not, could you maybe tell me how to start and I look into it myself?

**Comment by jendap** [comment]
Ok, I understand what you are trying to do. But I'm not sure why would you want to do it from python. Python is great high level abstraction to express your algorithm. The memory layout has to be under control of execution framework (C++ code in tf). Don't worry it is doing a good job there. And certainly will do even better in future. 

If you really want to do it... I don't think it is currently exposed in python. But take a look at swig wrappers. There is already some swig infrastructure in place. You can expose a lot more (all of it) in swig wrappers and you will have access to everything.

BTW: Just the example you say sounds like premature optimization you may not want to do by hand. Think you it. You will have 2 GPUs. Tensorflow will compute those two subgraphs outputs one on each GPU. x1 on gpu0 and x2 on gpu1. It may already have there even the weights - W1 on gpu0 and W2 on gpu1. It can do those two multiplications on the two gpus and just add the result. If you try manually force creating one vector W and one X you will spend a lot of time copying a lot of data. And that is slow.

**Comment by vrv** [comment]
I think TensorFlow should probably handle this underneath rather than giving control over to the user (which would permit user-caused bugs).  We probably don't do the most optimal things today but over time we hope to evolve to automatically do this.
