### ISSUE TITLE
Tensorflow v2.15.0 build fail 

### ISSUE THREAD

**Issue by zahed327** [tensorflow/tensorflow#63002]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.15.0 

### Custom code

No

### OS platform and distribution

macOS 14.0 

### Python version

python 3.10 

### Bazel version

6.5.0 

### CUDA/cuDNN version

none 

### GPU model and memory

none 

### Current behavior?

Unable to build tf v2.15.0 

### Standalone code to reproduce the issue

```shell
Here's the terminal commands : 

https://colab.research.google.com/drive/1CwOxD4shP4VzeLdkhZm6XXQl6BH_XdGi#scrollTo=7i3ykE297nzV
```

**Comment by SuryanarayanaY** [comment]
Hi @zahed327 ,

For TF2.15V builds are done and tested with Bazel 6.1.0 . Please try build with tested version only as mentioned [here](https://www.tensorflow.org/install/source#cpu_2) as forward versions may raise compatibility issues.


Version | Python version | Compiler | Build tools
-- | -- | -- | --
tensorflow-2.15.0 | 3.9-3.11 | Clang from xcode 10.15 | Bazel 6.1.0

**Comment by SuryanarayanaY** [comment]
I recommend to use [Bazelisk](https://github.com/bazelbuild/bazelisk) which can automatically select the compatible bazel version for the Tensorflow version that is being built.

Thanks!

**Comment by zahed327** [comment]
Thank you, I'll probably try using Docker to avoid unforseen issues in the future
