### ISSUE TITLE
tf.data.Dataset.from_tensor_slices name argument is not properley saved nor shown

### ISSUE THREAD

**Issue by igormintz** [tensorflow/tensorflow#63001]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.17.0-dev20240220

### Custom code

Yes

### OS platform and distribution

colab, mac

### Python version

3.10.5

### Current behavior?

when trying to name a datset using `tf.data.Dataset.from_tensor_slices`, the name is saved under ._name and not name. When printing the ds, the name is None

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
train_ds = tf.data.Dataset.from_tensor_slices((['a','b']), name="train_ds")
print(train_ds)

print(train_ds._name) #prints train_ds
# print(train_ds.name) # AttributeError: '_TensorSliceDataset' object has no attribute 'name'
```

### Relevant log output

```shell
<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>
```

**Comment by sushreebarsa** [comment]
@igormintz when you assign a name to a dataset using tf.data.Dataset.from_tensor_slices, the actual name gets stored in an internal attribute ._name instead of the public name attribute. This can be confusing, as printing the dataset won't show the assigned name.

Could you use the `._name `attribute:
```
ds = tf.data.Dataset.from_tensor_slices(..., name="my_dataset")
actual_name = ds._name
print(f"Actual name: {actual_name}")

```

Thank you!

**Comment by igormintz** [comment]
why not change the method form ._name to .name?
how to make the name stick to the tensor so it will show up when printed?

**Comment by sushreebarsa** [comment]
@igormintz TensorFlow maintains a consistent API for interacting with tensor attributes. Using a public property like .name ensures uniformity across different operations and functionalities. You can make the name stick to the tensor so it shows up when printed by assigning a name during its creation. You can assign names to any type of tensor created using TensorFlow functions like tf.constant, tf.zeros, tf.random.normal, etc.
Thank you!
