### ISSUE TITLE
Build/release Python 3.11 tflite-runtime MacOS wheels to PyPI

### ISSUE THREAD

**Issue by chatnord** [tensorflow/tensorflow#63017]
### Issue type

Feature Request

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.14.0

### Custom code

Yes

### OS platform and distribution

MacOs

### Python version

4.11

### Current behavior?

We are currently needing to run automated jobs on MacOS using tflite-runtime and Python 3.11, but the wheels on Pypi only cover Linux.

### Standalone code to reproduce the issue

```shell
pip install tflite-runtime
```

### Relevant log output

```shell
ERROR: Could not find a version that satisfies the requirement tflite-runtime (from versions: none)
ERROR: No matching distribution found for tflite-runtime
```

**Comment by feranick** [comment]
This repo below is certainly not a replacement of a proper official support for `tflite_runtime` from Google. Yet, it provides help on making up-to-date `whl` packages yourself (and some unofficial builds, including for python 3.11).

https://github.com/feranick/TFlite-builds

**Comment by tilakrayal** [comment]
@chatnord,
I request you to take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/61860) where a similar feature has been proposed and it is still open at the developer end. Also I request to follow the similar feature which has been proposed to have the updates on the similar issue. Thank you!

**Comment by feranick** [comment]
To be clear, there are a number of issues reported and pointed to the same state of abandonment of the repo for modern platforms.

**Comment by pkgoogle** [comment]
Hi @terryheo, can you please take a look? Thanks.

**Comment by psalaberria002** [comment]
This is hitting us aswell. Are there any plans for releasing platform specific wheels for newer Python versions?

**Comment by jbflow** [comment]
Also seeing this issue

**Comment by gaikwadrahul8** [comment]
Hi, @chatnord
Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/79

Let us know if you have any questions. Thanks.
