### ISSUE TITLE
SVDF layer implementation compatible with TFLite’s SVDF operator

### ISSUE THREAD

**Issue by VictorDominguite** [tensorflow/tensorflow#63035]
Although TFLite has a built-in SVDF operator (as listed [here](https://www.tensorflow.org/mlir/tfl_ops#tflsvdf_tflsvdfop), and whose implementation can be seen [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/reference/svdf.h)), currently, Tensorflow doesn't have a keras layer implementation for the SVDF operation.
I was wondering what would be the sequence of operations (using Tensorflow's Python library) needed so that they could be fused and recognized as an SVDF operator after converting to TFLite.

**Comment by sushreebarsa** [comment]
@VictorDominguite TensorFlow doesn't have a dedicated SVDF layer in Keras, you can achieve a similar functionality by manually defining the sequence of operations and convert them to TFLite, where the SVDF fusion might occur.
Thank you!

**Comment by VictorDominguite** [comment]
Hi @sushreebarsa, thank you for the response! 
Actually, my main doubt here is precisely defining what are the sequence of operations that would lead to the SVDF fusion when converting to TFLite. I already tried using [Google Research's implementation](https://github.com/google-research/google-research/blob/master/kws_streaming/layers/svdf.py) and the implementation of a "low latency svdf model" I found in [this tutorial](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/speech_commands/models.py#L458) from Tensorflow's repository (for this one I had to adapt the code to use TF2 operations equivalent to the ones used in the TF1 implementation), but none of them got fused as an SVDF operator when converting to TFLite. In fact, when listing the set of operations from the TFLite models generated from Keras models with these SVDF layers, I get all separate ops, such as `'DEPTHWISE_CONV_2D', 'FULLY_CONNECTED', 'PAD', ...`.
So I was wondering what would be the correct sequence of operations that would be recognized as an SVDF op after converting to TFLite.

**Comment by VictorDominguite** [comment]
Hi @pkgoogle! So, the first few lines from the `create_low_latency_svdf_model` function found in [this file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/speech_commands/models.py#L458-L618) correspond to the SVDF operation. What I tried to do was write a layer in TF2 that performed operations equivalent to the ones from the TF1 example. One difference worth mentioning is concerning the `is_training` flag present in the TF1 implementation. It slightly alters the behavior of the model. For simplicity, I only implemented the case where `is_training = True`.
The implementation for the TF2 layer and its conversion to TFLite can be seen in [this Colab notebook](https://colab.research.google.com/drive/1hJynxjcfrplbyif20bZZyznk-Ewl0NNG?usp=sharing).

**Comment by pkgoogle** [comment]
I was able to replicate with your notebook, thanks! I tried with tf-nightly and it is running into a different bug. @haozha111 can you please take a look? Thanks.

**Comment by kismeter** [comment]
one more info, I tried on docker based tensorflow 2.12.0, also can't fused to TFLite's SVDF operator

**Comment by kismeter** [comment]
@pkgoogle the latest version of tensorflow (tried on 2.16.2 and the tf-nightly) , there's no crash any more, but still not fused to tfl.svdf, is there anything special that should be done to make sure that fuse to tfl.svdf

**Comment by pkgoogle** [comment]
Hi @kismeter, unfortunately I don't see a reasonable workaround for this right now... you can try https://github.com/google-ai-edge/ai-edge-torch but I was not successful trying that conversion for this case.

**Comment by kismeter** [comment]
Hi @pkgoogle do you mean using PyTorch to implement SVDF then convert to tflite?

**Comment by pkgoogle** [comment]
Yes that's what https://github.com/google-ai-edge/ai-edge-torch is used to do, but as I said ... I was not successful for this particular use case, if you figure out how, we would love to know.

**Comment by gaikwadrahul8** [comment]
Hi, @VictorDominguite 
Thanks for raising this issue. Are you aware of [AI-Edge-Torch](https://developers.googleblog.com/en/ai-edge-torch-high-performance-inference-of-pytorch-models-on-mobile-devices/)? As we believe this issue is better supported by and more relevant to AI-Edge-Torch we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/ai-edge-torch/issues/386

Let us know if you have any questions. Thanks.
