### ISSUE TITLE
TensorFlowEstimator can not be found

### ISSUE THREAD

**Issue by yydxlv** [tensorflow/tensorflow#6303]
when i am running sequence predicting program in windows10 ,it stucked in an error :AttributeError: module 'tensorflow.contrib.learn' has no attribute 'TensorFlowEstimator'. the tensorflow edition is 0.12rc  and python3.5 .how can i fix this problem?

**Comment by martinwicke** [comment]
We removed the TensorFlowEstimator class in favor of Estimator. The interface is somewhat different, but it should be an easy conversion.
