### ISSUE TITLE
Image upsampling using interpolation function.

### ISSUE THREAD

**Issue by RocaVincent** [tensorflow/tensorflow#63048]
### Issue type

Feature Request

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

last

### Custom code

No

### Current behavior?

TensorfFlow now provides [a function for trilinear interpolation](https://www.tensorflow.org/graphics/api_docs/python/tfg/math/interpolation/trilinear/interpolate). However, how can we use it to upsample a 3D image ? For example, I have an image `x` of shape `(W,H,D)` and I would like to upsample it to `(W*2,H*2,D*2)`.

Any help appreciated, thanks.

### Standalone code to reproduce the issue

```shell
No code.
```

**Comment by SuryanarayanaY** [comment]
Hi @RocaVincent ,

You can use Upsampling layers for it for eg please refer [Upsampling3D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/UpSampling3D) API.

```
input_image=x
tf.keras.layers.UpSampling3D(size=2)(x)
```

If x is of shape (W,H,D), then the above code will upsample it to (2W,2H,2D).

**Comment by RocaVincent** [comment]
Hi @SuryanarayanaY ,

In fact I'm searching for **trilinear interpolation**, that's why I mentioned [this interpolation function](https://www.tensorflow.org/graphics/api_docs/python/tfg/math/interpolation/trilinear/interpolate). [UpSampling3D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/UpSampling3D) simply does nearest-neighbor interpolation.
