### ISSUE TITLE
Change visibility status for lite/schema/schema_conversion_utils to allow compilation of external libraries

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#63074]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

TF2.15

### Custom code

Yes

### OS platform and distribution

Ubuntu 22.04

### Python version

3.10

### Bazel version

6.1

### GCC/compiler version

gcc

### Current behavior?

When compiling libraries such as [libcoral](https://github.com/google-coral/libcoral) and [pycoral](https://github.com/google-coral/pycoral), they are linked to TF and access header files in TF proper. One such case is [schema_conversion_utils.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema_conversion_utils.h). Unfortunately the visibility of such header is set in [BUILD, line 188](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/BUILD) as:
```
visibility = [":utils_friends"],
```
This prevents a successful compilation of the libraries (especially when compiled within a docker), as the libraries are not part of the `utils_friends`. It is notable that a similar issue (i.e. same visibility status) was present in TF2.15 for [schema_util.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema_util.h), but was recently changed to:
```
visibility = ["//visibility:public"],
```
So the visibility status should be changed to `visibility = ["//visibility:public"],` also for the `schema_conversion_utils`. 

### Standalone code to reproduce the issue

```shell
(The libcoral library is outdated, so a fork from the original google version has been created so it can compile in modern systems. It is listed as follow).

git clone https://github.com/feranick/libcoral
cd libcoral
git submodule init
git submodule update
make DOCKER_IMAGE=ubuntu:22.04 DOCKER_CPUS="k8" DOCKER_TARGETS=tests docker-build
```

### Relevant log output

```shell
nicola@carbonio:~/Software/tensorflow-dir/coral/libcoral$ nano ~/.cache/bazel/_bazel_nicola/a151c9dba9406267fd80e5a9bea29d9e/external/org_tensorflow/tensorflow/lite/schema/BUILD 
nicola@carbonio:~/Software/tensorflow-dir/coral/libcoral$ make
Loading: 0 packages loaded
Loading: 0 packages loaded
bazel build --compilation_mode=opt --cpu=k8 //coral:bbox_test //coral:error_reporter_test //coral:inference_repeatability_test //coral:inference_stress_test //coral:model_loading_stress_test //coral:multiple_tpus_inference_stress_test //coral:segmentation_models_test //coral:test_utils_test //coral:tflite_utils_test //coral/classification:adapter_test //coral/classification:classification_models_test //coral/classification:cocompiled_classification_models_test //coral/classification:lstm_mnist_models_test //coral/detection:adapter_test //coral/detection:models_test //coral/dmabuf:dmabuf_devboard_test //coral/dmabuf:model_pipelining_dmabuf_devboard_test //coral/learn:imprinting_engine_test //coral/learn:utils_test //coral/learn/backprop:layers_test //coral/learn/backprop:multi_variate_normal_distribution_test //coral/learn/backprop:softmax_regression_model_test //coral/learn/backprop:test_utils_test //coral/pipeline:detection_models_test //coral/pipeline:models_test //coral/pipeline:pipelined_model_runner_test //coral/pipeline/internal:memory_pool_allocator_test //coral/pipeline/internal:segment_runner_test //coral/pose_estimation:bodypix_test //coral/pose_estimation:movenet_test //coral/pose_estimation:posenet_decoder_test //coral/pose_estimation:posenet_test //coral/tools:automl_model_append_rnn_link_test //coral/tools:tflite_graph_util_test //coral/tools/partitioner:parameter_count_based_partitioner_test //coral/tools/partitioner:profiling_based_partitioner_ondevice_test //coral/tools/partitioner:profiling_based_partitioner_test //coral/tools/partitioner:utils_test
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
ERROR: /home/nicola/Software/tensorflow-dir/coral/libcoral/coral/learn/BUILD:21:11: in cc_library rule //coral/learn:utils: target '@org_tensorflow//tensorflow/lite/schema:schema_conversion_utils' is not visible from target '//coral/learn:utils'. Check the visibility declaration of the former target if you think the dependency is legitimate
ERROR: /home/nicola/Software/tensorflow-dir/coral/libcoral/coral/learn/BUILD:21:11: Analysis of target '//coral/learn:utils' failed
ERROR: Analysis of target '//coral/learn/backprop:layers_test' failed; build aborted: 
INFO: Elapsed time: 2.310s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (8 packages loaded, 1318 targets configured)
make: *** [Makefile:75: tests] Error 1
```
```

**Comment by Namburger** [comment]
+1 to gain visibility

**Comment by pkgoogle** [comment]
Hi @feranick, @Namburger 
 was able to get this change in here: https://github.com/tensorflow/tensorflow/commit/79ecb3f8bb6bd73f0115fa9a97b630a6f745a426, can you test against master to ensure your issue is resolved? Thanks.

**Comment by Namburger** [comment]
I believe this issue can be closed, your call @feranick.

**Comment by feranick** [comment]
Closing. Thanks all for your help.

**Comment by feranick** [comment]
> Hi @feranick, @Namburger was able to get this change in here: [79ecb3f](https://github.com/tensorflow/tensorflow/commit/79ecb3f8bb6bd73f0115fa9a97b630a6f745a426), can you test against master to ensure your issue is resolved? Thanks.

Yes, I confirm the issue is resolved in master. Compilation works for libcoral.
