### ISSUE TITLE
Duplicate content on the new website

### ISSUE THREAD

**Issue by gokceneraslan** [tensorflow/tensorflow#6307]
In the Updates section of the new TensorFlow website, two news have the same text:

[![image](https://cloud.githubusercontent.com/assets/1140359/21177890/64615340-c1ed-11e6-82bc-c440ebc9dfd2.png)](https://www.tensorflow.org/)

**Comment by gunan** [comment]
@tfboyd

**Comment by xmbrst** [comment]
This is fixed.
