### ISSUE TITLE
WSL2 - TensorFlow Install Issue Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered

### ISSUE THREAD

**Issue by vatsalraicha** [tensorflow/tensorflow#63109]
Facing this error message when trying to use tensorflow on WSL2 Ubuntu - Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered.
TF-TRT Warning: Could not find TensorRT
could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.

Environment
TensorRT Version: 8.6.1.6
GPU Type: 4080 Laptop GPU
Nvidia Driver Version: NVIDIA-SMI 546.17 Driver Version: 546.17
CUDA Version: 12.3, CUDA Toolkit Version - 11.8
CUDNN Version: v8.6
Operating System + Version: Windows 11
Python Version (if applicable): Python 3.10.13
TensorFlow Version (if applicable): 2.15.0
PyTorch Version (if applicable): N/A
Baremetal or Container (if container which image + tag): N/A
pyenv Version - 2.3.35-11-g9908daf8
WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1

[tensorFlowErrors.txt](https://github.com/tensorflow/tensorflow/files/14475502/tensorFlowErrors.txt)

Steps to reproduce -
Followed the exact steps as mentioned in https://www.tensorflow.org/install/pip?hl=pt

**Comment by Venkat6871** [comment]
Hi **@vatsalraicha** ,

Ensure Correct Installation of CUDA, cuDNN, and TensorRT:
CUDA and cuDNN: Make sure that CUDA and cuDNN are correctly installed and that TensorFlow can detect them. You have mentioned using CUDA 12.3 and cuDNN v8.6, which should be compatible with TensorFlow 2.15.0. Ensure that the CUDA and cuDNN paths are correctly added to your `PATH` and `LD_LIBRARY_PATH` environment variables.
```
export PATH=/usr/local/cuda-12.3/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-12.3/lib64:$LD_LIBRARY_PATH
```
Reinstall TensorFlow:
Consider creating a fresh virtual environment and reinstalling TensorFlow within it. This can help resolve any conflicts or issues with previous installations:
```
python -m venv tf-venv
source tf-venv/bin/activate
pip install --upgrade pip
pip install tensorflow==2.15.0
```
Test Your Setup:
After ensuring all configurations and installations are correct, test your TensorFlow setup to see if it can access the GPU:
```
import tensorflow as tf

print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
```
Thank you!

**Comment by petervaneijk** [comment]
Same error. 

WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3235

NVIDIA GeForce RTX 4050
Driver Version: 551.61         CUDA Version: 12.4
CUDA sample functions run without errors

python 3.10.12
cuda_12.3.2_545.23.08
tensorrt 8.6.1

Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorrt
>>> print(tensorrt.__version__)
8.6.1
>>> import tensorflow as tf
2024-03-05 16:13:59.938649: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-05 16:13:59.960210: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-05 16:13:59.960255: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-05 16:13:59.960774: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-05 16:13:59.964109: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-05 16:14:00.340405: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
>>> print(tf.config.list_physical_devices('GPU'))
2024-03-05 16:14:19.162569: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-03-05 16:14:19.166217: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-03-05 16:14:19.166261: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
>>> print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
Num GPUs Available:  1
>>>

**Comment by vatsalraicha** [comment]
@Venkat6871 On WSL2, I dont have CUDA 12.3 director in /usr/local.
So this path is invalid for me - /usr/local/cuda-12.3/
Now as per NVIDIA documentation, I don't need to install any drivers on WSL2 and it should automatically pick from native Windows.
What could be the next step for me here?

**Comment by Amit30swgoh** [comment]
Same problem

**Comment by zylennon** [comment]
same 
2024-04-26 16:37:38.371348: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-26 16:37:38.371404: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-26 16:37:38.371421: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

**Comment by garryyan2** [comment]
I have the same problem. I am using WSL2.
2024-04-25 16:44:46.357075: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-25 16:44:46.357110: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-25 16:44:46.357608: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

**Comment by garryyan2** [comment]
After several days struggle,  I am able to get rid of this errors. 
It's a version compatibility issue. You need to install the package versions according to the [webpage](https://www.tensorflow.org/install/source#tested_build_configurations). 
I was struggled on installing specific CUDA toolkit versions through deb packages, because the version was always updated to the latest version 12.4. In the end, I used the runfiles to install the toolkit.
The other problem I had was that I started with tensorflow 2.15.1, which I could not get it to work. 
The versions that work for me are:
CUDA toolkit:  12.2. 
cudnn:             8.9.7.29
Tensorflow:      2.16.1

**Comment by vatsalraicha** [comment]
@garryyan2 Did you achieve this on WSL2 or on Native Linux?
What was your CUDA version?
Would you be able to share the Version info that you have setup that works?
TensorRT Version: 
Nvidia Driver Version: 
NVIDIA-SMI Driver Version: 546.17
CUDA Version: 
CUDNN Version: 
Python Version (if applicable):
WSL version:

**Comment by garryyan2** [comment]
@vatsalraicha I am using WSL2. 

$nvcc --version 
has output:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Jun_13_19:16:58_PDT_2023
Cuda compilation tools, release 12.2, V12.2.91
Build cuda_12.2.r12.2/compiler.32965470_0

$nvidia-smi
has output
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.76.01              Driver Version: 552.22         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
notice that the CUDA version is different from using command $nvcc --version.

cudnn version: 8.9.7.29
Python version: Python 3.10.12
WSL version: 5.15.146.1-microsoft-standard-WSL2

I am not sure about the TensorRT version.

**Comment by gurzelai** [comment]
> same 2024-04-26 16:37:38.371348: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered 2024-04-26 16:37:38.371404: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered 2024-04-26 16:37:38.371421: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

how did you solve it?

**Comment by garryyan2** [comment]
@gurzelai, for me, I just tried difference version combinations of the tools/packages. I am not not familiar with Colab. You probably can't have the software versions of your choice.

**Comment by lapitskiy** [comment]
for me work
tesla p100, x9dri, ubuntu 22.04

conda
python 3.10

sudo mkdir -p /usr/lib/xorg/modules
sudo apt-get update
sudo apt-get install pkg-config xorg-dev
sudo apt install libvulkan1
sudo apt install dkms

nvidia driver 535.183.06 fo cuda 12.2

CUDA Toolkit 12.3 runfile local

cudnnv8.9.7.29 **tar file** ([instruction](https://docs.vultr.com/how-to-install-nvidia-cudnn-on-ubuntu-22-04))

tensorflow 2.16.1 for gpu for python 3.10 whl (https://storage.googleapis.com/tensorflow/versions/2.16.1/tensorflow-2.16.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl)

echo '/usr/local/cuda-12.3/lib64' | sudo tee -a /etc/ld.so.conf.d/cuda.conf
sudo ldconfig

.bashrc
export PATH=/usr/local/cuda-12.3/bin:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.3/lib64:/usr/local/cuda-12.3/extras/CUPTI/lib64
export CUDA_HOME=/usr/local/cuda-12.3


sudo reboot

**Comment by pak-app** [comment]
My algorithm uses Pytorch and gets the same error. Is there anybody to solve that?

**Comment by dlin95123** [comment]
I have the same error messages with Docker Hub's Tensorflow image. Specifically, I issued the following command to start a Jupyter notebook with the latest Tensorflow: docker run -it --rm -p 8888:8888 --gpus all tensorflow/tensorflow:latest-gpu-jupyter

In the Jupyter notebook, I just did "import tensorflow as tf". Then I see these error messages. So apparently, it is not my local configuration issue as a Docker image should be self contained.

**Comment by hanjifeng** [comment]
Same issue found for me.
CUDA12.3, CUDNN 8.9. 
change to tensorflow 2.16.1, seems working

**Comment by BenIlias** [comment]
> After several days struggle, I am able to get rid of this errors. It's a version compatibility issue. You need to install the package versions according to the [webpage](https://www.tensorflow.org/install/source#tested_build_configurations). I was struggled on installing specific CUDA toolkit versions through deb packages, because the version was always updated to the latest version 12.4. In the end, I used the runfiles to install the toolkit. The other problem I had was that I started with tensorflow 2.15.1, which I could not get it to work. The versions that work for me are: CUDA toolkit: 12.2. cudnn: 8.9.7.29 Tensorflow: 2.16.1

Could you please do me a favour and convert me a model ? i need it urgently if possible please.

**Comment by BenIlias** [comment]
> Same issue found for me. CUDA12.3, CUDNN 8.9. change to tensorflow 2.16.1, seems working

Could you please do me a favour and convert me a model ? i need it urgently if possible please.

**Comment by BenIlias** [comment]
> Same issue found for me. CUDA12.3, CUDNN 8.9. change to tensorflow 2.16.1, seems working

Could you please do me a favour and convert me a model ? i need it urgently if possible please.

**Comment by garryyan2** [comment]
@BenIlias Hello, what do you mean by converting you a model? Do you just need a simple example with a model? I have one in [#67033](https://github.com/tensorflow/tensorflow/issues/67033) .

**Comment by BenIlias** [comment]
> @BenIlias Hello, what do you mean by converting you a model? Do you just need a simple example with a model? I have one in [#67033](https://github.com/tensorflow/tensorflow/issues/67033) .

First thanks for your reply.
I mean you fixed this error, you are able to use tensorflow with TensorRT correctly.
I have python tensorflow model and want to convert it to JavaScript model.
Could you please help me? I need it urgently for the university tonight . Thank you!

**Comment by garryyan2** [comment]
@BenIlias Sorry, I don't know JavaScript coding.

**Comment by BenIlias** [comment]
> @BenIlias Sorry, I don't know JavaScript coding.

No, it's not coding at all, only python script run it to convert the model and that's all.

**Comment by BenIlias** [comment]
> @BenIlias Sorry, I don't know JavaScript coding.

One line of python code and that's set

**Comment by garryyan2** [comment]
@BenIlias. Sorry, I can't help you on this. I

**Comment by garryyan2** [comment]
@BenIlias You may want to try google's colab to run it.

**Comment by BenIlias** [comment]
> @BenIlias You may want to try google's colab to run it.

I tried but same error 😔 and today is the deadline 😢.
I have been trying colab for few days but doesn't work.

**Comment by BenIlias** [comment]
> @BenIlias You may want to try google's colab to run it.

If you could do me the favour, i would never forget it :)

**Comment by vatsalraicha** [comment]
No one - Wither from NVIDIA or PyTorch really cares about this issue. Their documentation is terrible. Leaving Non-enterprise developers in lurch.

**Comment by somera** [comment]
Same here
```
$ python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
2024-10-04 22:08:03.457116: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-04 22:08:03.467976: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-04 22:08:03.471242: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-04 22:08:03.479178: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-04 22:08:04.067104: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1728072484.659515    2246 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1728072484.682458    2246 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1728072484.682536    2246 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```
Windows 11 Pro with wsl2 and tensorflow 1.17.0
```
$ python3 -c "import tensorflow as tf; print(tf.__version__)"
2024-10-04 22:10:18.748131: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-04 22:10:18.758588: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-04 22:10:18.761936: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-04 22:10:18.770271: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-04 22:10:19.361999: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2.17.0
```

**Comment by sanjayhallan** [comment]
same problem

how can you find out what CUDNN version is?

**Comment by somera** [comment]
> how can you find out what CUDNN version is?

Do you mean https://stackoverflow.com/questions/31326015/how-to-verify-cudnn-installation ?

**Comment by Venkat6871** [comment]
Hi **@vatsalraicha** ,
Apologies for the delay, Please check your code with the recent TensorFlow versions (2.17.0 and 2.18.0) and let us know if the issue persists.
And starting from TF2.14 tensorflow provides CUDA package which can install all the cuDNN,cuFFT and cubLas libraries.
You can use ```pip install tensorflow[and-cuda]``` command for that.

Thank you!

**Comment by erinsrc** [comment]
This solution works for me too

**Comment by erinsrc** [comment]
> Same issue found for me. CUDA12.3, CUDNN 8.9. change to tensorflow 2.16.1, seems working

This solution works for me too

**Comment by somera** [comment]
Looks good for me

![image](https://github.com/user-attachments/assets/0d617110-aa69-42a3-b024-b2d0ab937db9)

Thx!

**Comment by pickou** [comment]
> Same issue found for me. CUDA12.3, CUDNN 8.9. change to tensorflow 2.16.1, seems working

it works for me.

**Comment by fabiogeraci** [comment]
```
STDERR Output:
2024-11-22 13:58:35.440778: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-11-22 13:58:35.617263: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1732283915.686357    1397 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1732283915.706698    1397 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-22 13:58:35.870154: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX512_FP16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Profile: tests from {:path=>"/builds/sciaas/image-creation/test/integration/default/inspec"} (tests from {:path=>".builds.sciaas.image-creation.test.integration.default.inspec"})
Version: (not specified)
Target:  ssh://ubuntu@172.27.17.212:22

  System Package curl
     ✔  is expected to be installed
  Command: `nvidia-smi`
     ✔  should have non-empty stdout
     ✔  should contain "550.54.15" in the output
     ✔  should contain "H100XM-1-10C" in the output
  System Information
     ✔  hostname is expected to eq "image-creation-test01"
  Iptables
     ✔  is expected to have rule "-P INPUT ACCEPT"
     ✔  is expected to have rule "-P FORWARD ACCEPT"
     ✔  is expected to have rule "-P OUTPUT ACCEPT"
     ✔  is expected not to have rule "DROP"
     ✔  is expected not to have rule "REJECT"
  System Package metricbeat
     ✔  is expected to be installed
  Service metricbeat-openstack-setup
     ✔  is expected to be running
     ✔  is expected to be enabled
  Command: `cat /etc/metricbeat/metricbeat.yml`
     ✔  stdout is expected to match /2773a12573d849f7a5d758f1fb7637e8/
  Command: `metricbeat test output`
     ✔  exit_status is expected to eq 0
  Command: `python3 --version`
     ✔  should exit successfully
     ✔  should have non-empty stdout
     ✔  should output the correct Python version
     ✔  should not output errors to stderr
  Command: `python3 -c "import tensorflow as tf; print(tf.__version__)"`
     ✔  should exit successfully
     ✔  should have non-empty stdout
     ✔  should output TensorFlow version 2.18.0
     ×  should not output cuDNN messages to stderr
     expected "2024-11-22 13:58:35.440778: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You...X_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n" not to include "cuDNN"
     ×  should not output cuBLAS messages to stderr
     expected "2024-11-22 13:58:35.440778: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You...X_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n" not to include "cuBLAS"
  Command: `python3 -c "import tensorflow as tf; print(tf.test.is_gpu_available())"`
     ✔  should output True for CUDA availability
  Command: `python3 -c "import tensorflow as tf; print(len(tf.config.list_physical_devices('GPU')))"`
     ✔  should exit successfully
     ✔  should have more than 0 GPU devices
  Command: `python3 -c "from tensorflow.python.platform import build_info as tf_build_info; print(tf_build_info.build_info['cudnn_version'])"`
     ✔  should exit successfully
     ✔  should cudnn version is 9

Test Summary: 27 successful, 2 failures, 0 skipped
```

**Comment by twmht** [comment]
> Hi **@vatsalraicha** , Apologies for the delay, Please check your code with the recent TensorFlow versions (2.17.0 and 2.18.0) and let us know if the issue persists. And starting from TF2.14 tensorflow provides CUDA package which can install all the cuDNN,cuFFT and cubLas libraries. You can use `pip install tensorflow[and-cuda]` command for that.
> 
> Thank you!

this works for me. but still got cudnn and cublas issues

```
E0000 00:00:1733196652.250424 2952826 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered                    E0000 00:00:1733196652.258170 2952826 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered                 2024-12-03 11:30:52.290453: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations. 
```

any advise?

**Comment by xiaoyaolangzhi** [comment]
this words for me in wsl2.
```
conda create -n tensorflow tensorflow-gpu=2.16.1 cudnn=8.9.7.29 -c conda-forge
conda activate tensorflow
python -c "import tensorflow as tf;print(tf.__version__)"
```

**Comment by xiaoyaolangzhi** [comment]
it works for me.
```
conda create --name tensorflow python=3.12
conda activate tensorflow

conda install cuda -c nvidia/label/cuda-12.3.0
conda env config vars set LD_LIBRARY_PATH=$CONDA_PREFIX/lib
conda env config vars set XLA_FLAGS=--xla_gpu_cuda_data_dir=$CONDA_PREFIX
conda deactivate
conda activate tensorflow

conda install cudnn=8.9

pip install tensorflow==2.16.1
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
```

**Comment by LiaoShuangquan0228** [comment]
it works for me just to uninstall tensorflow==2.18 and to install tensorflow==2.16.1

**Comment by Jaswanth28** [comment]
> Hi **@vatsalraicha** , Apologies for the delay, Please check your code with the recent TensorFlow versions (2.17.0 and 2.18.0) and let us know if the issue persists. And starting from TF2.14 tensorflow provides CUDA package which can install all the cuDNN,cuFFT and cubLas libraries. You can use `pip install tensorflow[and-cuda]` command for that.
> 
> Thank you!

hi the issue still resurface with tf 2.18 too

**Comment by likaipeng** [comment]
> Same issue found for me. CUDA12.3, CUDNN 8.9. change to tensorflow 2.16.1, seems working

you are right！I uninstalled tensorflow 2.18.0 and installed 2.16.1,it works fine!The following error messages just disappeared:
Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered

**Comment by vatsalraicha** [comment]
I just gave up trying to make CUDA work on Windows, and sold off my Dell Alienware to get Mac. For my own stuff, I don't need CUDA. At company there is dedicated support to solve such issues.
CUDA support for individuals is terrible.

**Comment by Jaswanth28** [comment]
The error which I tagged is from wsl

**Comment by HaomingJu** [comment]
```
pip install tensorflow==2.16.1 --break-system-packages
```
它解决了我的问题 (It' work for me)

**Comment by voltairh** [comment]
installed 2.16.1,it works. 

(tensorflow~=2.16.1 & keras~=3.0)

After that:

ValueError: When passing a Python generator to a Keras model, the generator must return a tuple, either (input,) or (inputs, targets) or (inputs, targets, sample_weights). Received: [[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...

pred = self.model.predict(g, steps=steps, verbose=verb)[:,-1]  -->  pred = self.model.predict(((x,) for x in g), steps=steps, verbose=verb)[:,-1]  in models.py
