### ISSUE TITLE
Tensorboard has wrong logdir on Windows

### ISSUE THREAD

**Issue by werner-rammer** [tensorflow/tensorflow#6313]
I use Tensorflow 0.12rc1 on Windows. "Tensorboard" has problems parsing the `logdir`. My log-directory is at `E:\tmp\tflogs`. When I start tensorboard from the windows shell (cmd.exe) with:

`tensorboard --logdir=E:\tmp\tflogs`

it depends on the current directory / drive if it works or not (i.e., if tensorboard finds the runs and shows the data). If the current directory is, e.g., on the `C:\` drive, tensorboard tries to add runs from `c:\tmp\tflogs` instead of `E:\tmp\tflogs`. 

Example:
`
C:\Users\wrammer>tensorboard --logdir=E:\tmp\tflearn_logs --debug
`
The log contains lines such as:
`
INFO:tensorflow:Starting AddRunsFromDirectory: C:\tmp\tflearn_logs
`

**Comment by mrry** [comment]
I think this is caused by the TensorBoard [syntax for the `--logdir` flag](https://github.com/tensorflow/tensorflow/blob/dbe5e17e2ed307e86e1a6e79e558ec3e335d46fc/tensorflow/tensorboard/tensorboard.py#L36):

> 
> `logdir` specifies the directory where TensorBoard will look to find TensorFlow event files that it can display. TensorBoard will recursively walk the directory structure rooted at logdir, looking for `.*tfevents.*` files.
>
> You may also pass a comma separated list of log directories, and TensorBoard will watch each directory. You can also assign names to individual log directories by putting a colon between the name and the path, as in
>
> ```
> tensorboard --logdir=name1:/path/to/logs/1,name2:/path/to/logs/2
> ```

...which clearly doesn't play well with Windows paths with colons :).

I'll defer to the TensorBoard team about how they'd like to handle this. One workaround could be to use `file:///` URIs instead of paths, where we could add support for `|` in place of `:` in Windows filenames. (You might also be able to use an "administrative share" `\\MachineName\e$\tmp\tflogs` if your machine is configured to allow that.)

**Comment by jart** [comment]
Yes this is something we should fix. But it might not be necessary to change the syntax. It might be possible to say, ok, this is a single letter followed by `:\`, it's probably not a label.

As a workaround, are you able to say `--logdir=foo:E:\tmp\tflogs`?

**Comment by kvothe** [comment]
I had the same problem and can confirm that `--logdir foo:D:\some\path` does indeed work on windows with tensorflow 0.12 while `--logdir D:\some\path` does not.

**Comment by jiyuan312986471** [comment]
I had the same problem with tensorflow 0.12.1. Thanks to @kvothe it now works for me by adding a name before E:\some\path

**Comment by Deepak-** [comment]
The solution of @kvothe also works for tensorflow 1.0.1 (on Windows 10)

**Comment by chihuahua** [comment]
I migrated this issue to tensorflow/tensorboard#54 because TensorBoard has moved to a new repository. Lets continue discussion on this bug there.

**Comment by micklexqg** [comment]
@jiyuan312986471 ， what did you add before path？ I came into the same problem, would you like to share your solution?

**Comment by chihuahua** [comment]
See @dandelion's comment here for a solution - let me know if that works: https://github.com/tensorflow/tensorboard/issues/52

Specifically, the colon in the directory path is problematic, so try relative paths.
