### ISSUE TITLE
i am getting a weired issue while using the script tag of tensorflow 

### ISSUE THREAD

**Issue by viniith21** [tensorflow/tensorflow#63135]
indexnew.js:726 Error in main function:  TypeError: Failed to fetch
    at e.fetch (tfjs-core:17:94486)
    at e.<anonymous> (tfjs-core:17:243405)
    at tfjs-core:17:2217
    at Object.next (tfjs-core:17:2322)
    at tfjs-core:17:1259
    at new Promise (<anonymous>)
    at a (tfjs-core:17:1004)
    at e.loadModelJSON (tfjs-core:17:243294)
    at e.<anonymous> (tfjs-core:17:244682)
    at tfjs-core:17:2217
    
    Please see above issue what is causing it ?

**Comment by SuryanarayanaY** [comment]
Hi @viniith21 ,
Is this related to Tensorflow JS? If so please report it at tfjs repo [here](https://github.com/tensorflow/tfjs/issues).

**Comment by viniith21** [comment]
Hi @SuryanarayanaY i fixed this issue please close this issue

**Comment by viniith21** [comment]
Hi @SuryanarayanaY i fixed this issue please close this issue

**Comment by SuryanarayanaY** [comment]
Closing the issue as per user confirmation.
