### ISSUE TITLE
Error 404 when downloading Tensorflow on Windows

### ISSUE THREAD

**Issue by SpaVec** [tensorflow/tensorflow#6314]
The links provided on the website to the .whl used to install Tensorflow on Windows seem to be broken : https://www.tensorflow.org/get_started/os_setup#pip_installation_on_windows
I'm getting an HTTP Error 404.
I found the CPU Build elsewhere but I can't find the GPU build which I would like tu use.

**Comment by lufficc** [comment]
same

**Comment by Carmezim** [comment]
If you want to get it running for now just try running:
`pip install tensorflow`
and for gpu support:
`pip install tensorflow-gpu`

**Comment by SpaVec** [comment]
Awesome! It works, thank you very much!

**Comment by mrry** [comment]
@gunan @yifeif Can we modify the website to point at the existing RC? (I think it's broken for all operating systems right now, but it mostly seems to be Windows users who're affected for some reason....)

**Comment by yifeif** [comment]
The windows links from tensorflow website should be working now. Sorry for the inconvenience.
