### ISSUE TITLE
training on one GPU, but the other one is also occupied

### ISSUE THREAD

**Issue by karlTUM** [tensorflow/tensorflow#6316]
Hi,
I have two GPUs, and I just would like to use one GPU to train a network by tensorflow. When I train it, the code use all the memories of two GPUs, but only one GPU is working:
![screenshot from 2016-12-14 20-12-57](https://cloud.githubusercontent.com/assets/15608199/21197459/cfbcc86a-c23b-11e6-88d5-e04f7537e676.png)

How to solve this problem? I would like just one to work, but not occupy the other.

**Comment by yaroslavvb** [comment]
http://stackoverflow.com/questions/41150462/tensorflow-training-network-on-one-gpu-but-occupy-the-space-of-the-other

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow, which we also monitor. Please ask it there and tag it with the `tensorflow` tag.
