### ISSUE TITLE
How can I know what variables or constants in a ".ckpt" file

### ISSUE THREAD

**Issue by oneengineer** [tensorflow/tensorflow#6325]
How can I know what variables or constants in a ".ckpt" file?

If I restore a ".ckpt" file without defining any variables, I will get error.
However I just want to know what's in that ".ckpt" file.

I didn't see any function can achieve it.

**Comment by yaroslavvb** [comment]
This is a good question for stackoverflow (so that other people can
discover this information easier), but there's this utility:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/inspect_checkpoint.py

**Comment by oneengineer** [comment]
thank you yaroslavvb. I think I can close this ticket.
