### ISSUE TITLE
2.16.1 Tflite CMake compiling error

### ISSUE THREAD

**Issue by zihaomu** [tensorflow/tensorflow#63258]
**System information**
- OS Platform and Distribution : MacOS 14.1.2
- TensorFlow installed from (source or binary): source
- TensorFlow version : 2.16.1
- NDK version: 26.1.1090912

**Provide the text output from tflite_convert**

```
/Users/mzh/work/github/tensorflow_archive/tensorflow_216/tensorflow/lite/delegates/gpu/gl_delegate.cc:53:10: fatal error: 'tensorflow/lite/delegates/gpu/gl/metadata_generated.h' file not found
#include "tensorflow/lite/delegates/gpu/gl/metadata_generated.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/tensorflow-lite.dir/delegates/gpu/gl_delegate.cc.o] Error 1
make[1]: *** [CMakeFiles/tensorflow-lite.dir/all] Error 2
```

looks like the `tensorflow/tensorflow/lite/delegates/gpu/gl/metadata.fbs` is not be compiled to `.h` and `.cpp` file.

**Comment by pkgoogle** [comment]
Hi @zihaomu, can you try following these instructions? https://www.tensorflow.org/lite/guide/build_ios, let us know if that works for you.
