### ISSUE TITLE
Embedding Projector: show vector labels on custom projection view

### ISSUE THREAD

**Issue by micahstubbs** [tensorflow/tensorflow#6327]
A feature request for the Embedding Projector: show vector labels as plot axis labels on custom projection view

minimal example, mocked up on a screenshot:
<img width="317" alt="screen shot 2016-12-14 at 11 30 40 pm" src="https://cloud.githubusercontent.com/assets/2119400/21215544/ae2c994e-c256-11e6-9a8a-5501b4592695.png">
<img width="1311" alt="custom-projection-blocks" src="https://cloud.githubusercontent.com/assets/2119400/21215550/b7a945ee-c256-11e6-9667-1ca8052c9483.png">

**Comment by dandelionmane** [comment]
Migrated to the TensorBoard repo
