### ISSUE TITLE
ValueError: Variable d_h0_conv/w/Adam/ does not exist

### ISSUE THREAD

**Issue by zhangqianhui** [tensorflow/tensorflow#6329]
I got a error:

`
ValueError: Variable d_h0_conv/w/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
`

this is DCGAN's code 
[dcgan-tensorflow](https://github.com/carpedm20/DCGAN-tensorflow)

And my tensorflow version is 0.12
my ubuntu : 14.04

code detail:

con2d code

`def conv2d(input_, output_dim, 
           k_h=5, k_w=5, d_h=2, d_w=2, stddev=0.02,
           name="conv2d"):
    with tf.variable_scope(name):

        w = tf.get_variable('w', [k_h, k_w, input_.get_shape()[-1], output_dim],
                            initializer=tf.truncated_normal_initializer(stddev=stddev))
        conv = tf.nn.conv2d(input_, w, strides=[1, d_h, d_w, 1], padding='SAME')

        biases = tf.get_variable('biases', [output_dim], initializer=tf.constant_initializer(0.0))
        conv = tf.reshape(tf.nn.bias_add(conv, biases), conv.get_shape())

        return conv`

Optimizer:

`
        d_optim = tf.train.AdamOptimizer(config.learning_rate ,  beta1=config.beta1).minimize(self.d_loss , var_list=self.d_vars)
        g_optim = tf.train.AdamOptimizer(config.learning_rate, beta1=config.beta1) \
                          .minimize(self.g_loss, var_list=self.g_vars)
`

Thanks, Now I need help!

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow, which we also monitor. Please ask it there and tag it with the `tensorflow` tag.

**Comment by srsani** [comment]
I have the same issue. Has this issue being resolved? Can you provide the StackOverflow link?

**Comment by srsani** [comment]
Here is the link to StackOverflow for this issue with not a clear reply.
