### ISSUE TITLE
Error of using a custom classifier for android demo

### ISSUE THREAD

**Issue by larsonwu0220** [tensorflow/tensorflow#6330]
I want to build android demo of my classifier.
Following the steps at [https://www.oreilly.com/learning/tensorflow-on-android](url),
the error appeared for 
`bazel build tensorflow/python/tools:optimize_for_inference` .
My bazel version is 0.4.2.
Error :
> ERROR: /home/dlm/tensorflow_new/tensorflow/python/BUILD:1907:1: Linking of rule '//tensorflow/python:_pywrap_tensorflow.so' failed: link_dynamic_library.sh failed: error executing command external/bazel_tools/tools/cpp/link_dynamic_library.sh no ignored ignored ignored /usr/bin/gcc -shared -o bazel-out/local-fastbuild/bin/tensorflow/python/_pywrap_tensorflow.so -Wl,--version-script ... (remaining 14 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/local-fastbuild/bin/tensorflow/core/libversion_lib.a(version_info.pic.o): In function `tf_git_version()':
version_info.cc:(.text+0x0): multiple definition of `tf_git_version()'
bazel-out/local-fastbuild/bin/tensorflow/core/libframework_internal.lo(version_info.pic.o):version_info.cc:(.text+0x0): first defined here
bazel-out/local-fastbuild/bin/tensorflow/core/libversion_lib.a(version_info.pic.o): In function `tf_compiler_version()':
version_info.cc:(.text+0xd): multiple definition of `tf_compiler_version()'
bazel-out/local-fastbuild/bin/tensorflow/core/libframework_internal.lo(version_info.pic.o):version_info.cc:(.text+0xd): first defined here
collect2: error: ld returned 1 exit status
Target //tensorflow/python/tools:optimize_for_inference failed to build
Use --verbose_failures to see the command lines of failed build steps.

How do I fix this error ?

**Comment by andydavis1** [comment]
Pete has a good blog post that might help. https://petewarden.com/2016/09/27/tensorflow-for-mobile-poets/

Otherwise please post this question on stackoverflow with tag 'tensorflow'
