### ISSUE TITLE
Tensorflow installation Error in Mac Sierra due to numpy

### ISSUE THREAD

**Issue by zshareef** [tensorflow/tensorflow#6331]
Hi,

I want to install TensorFlow on Mac. Currently I am using MacOS Sierra (Version 10.12.1).
Python was already installed in this current version. My Python version is 2.7.10.

I followed the instructions given on the webpage of Tensorflow to install it on my Mac. When I entered the command 
$ pip install tensorflow then I have the following error:

$ pip install tensorflow
Collecting tensorflow
  Downloading tensorflow-0.12.0rc1-cp27-cp27m-macosx_10_11_x86_64.whl (38.5MB)
    100% |████████████████████████████████| 38.5MB 23kB/s 
Collecting numpy>=1.11.0 (from tensorflow)
  Downloading numpy-1.11.2-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.9MB)
    100% |████████████████████████████████| 3.9MB 263kB/s 
Requirement already satisfied: six>=1.10.0 in /Library/Python/2.7/site-packages/six-1.10.0-py2.7.egg (from tensorflow)
Collecting mock>=2.0.0 (from tensorflow)
  Downloading mock-2.0.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 4.9MB/s 
Collecting wheel (from tensorflow)
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 3.3MB/s 
Collecting protobuf==3.1.0 (from tensorflow)
  Downloading protobuf-3.1.0-py2.py3-none-any.whl (339kB)
    100% |████████████████████████████████| 348kB 2.1MB/s 
Collecting funcsigs>=1; python_version < "3.3" (from mock>=2.0.0->tensorflow)
  Downloading funcsigs-1.0.2-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock>=2.0.0->tensorflow)
  Downloading pbr-1.10.0-py2.py3-none-any.whl (96kB)
    100% |████████████████████████████████| 102kB 7.4MB/s 
Requirement already satisfied: setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf==3.1.0->tensorflow)
Installing collected packages: numpy, funcsigs, pbr, mock, wheel, protobuf, tensorflow
  Found existing installation: numpy 1.8.0rc1
    DEPRECATION: Uninstalling a distutils installed project (numpy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling numpy-1.8.0rc1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/jk/s2ngqqls71v9vj7z02p79w880000gn/T/pip-hpgFvE-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/numpy-1.8.0rc1-py2.7.egg-info'

I think there is some issue with numpy. My current numpy version is 1.8.0rc1 and it was already installed with MacOS Sierra. I tried to uninstall it so that Tensorflow install the new version by itself but no success.

I tried different solutions available on the web to solve this issue but no success.

Could anybody tell me that how I can solve this issue and install Tensorfow.

Thanks.
Zeeshan

**Comment by comicchang** [comment]
Try use homebrew python instead

**Comment by mokpro** [comment]
I agree, using `homebrew` to install python is the best way to go. 
If you want detailed steps: https://github.com/mokpro/tensorflow_examples/blob/master/README.md

**Comment by gunan** [comment]
1-You usually need "sudo" to run pip installations, unless you are running inside a virtualenv.

2-There is also a problem where if you both have macOS installed python and brew installed python, you can install any packages on one, but run the other. MacOS installed python resides in `/usr/bin/python` while brew installs it under `/usr/local/bin/python`.
I think you need to run the following to make your system default to the brew installed python.
`brew link python`.
But SIP (System Integrity Protection) on macOS may complicate things.

Therefore I suggest you to create a virtualenv and install everything under that.
It should have no performance implications at all.
Also, any python environment changes you need will all be in a single folder, owned by you with no need for extra privileges.

**Comment by jessyuan24** [comment]
I have same error, how to solve this problem without homebrew.

**Comment by comicchang** [comment]
@jessyuan24

Homebrew is the best way. Otherwise You can try 
Virtualenv

If you want to use the macos python, maybe you need to disable SIP and use 'sudo pip install'

**Comment by gunan** [comment]
Because of System integrity protection, I think only way to install software on macOS natively is through the appstore.

So, as @comicchang suggested, your options are:
1-disable SIP (the instructions are easy to find with a google search) then sudo pip install
2-use virtualenv
3-use homebrew.

@zshareef did running `brew link python` help resolve your problem?

**Comment by jessyuan24** [comment]
@comicchang Thank you so much. it works. But I have some problem didn't understand.

**Comment by otech47** [comment]
Also 
```
sudo pip install --ignore-installed numpy
```

Had to do this with the `six` dependency as well

**Comment by lalet** [comment]
Only this solution worked for me.

**Comment by surajsnair92** [comment]
For me too! Thanks.

**Comment by sebas1022** [comment]
@otech47 Thanks

**Comment by brookhong** [comment]
I fixed this by

    vim /usr/local/bin/pip

with

    #!/usr/local/bin/python2.7

at first line, as I already have `/usr/local/bin` ahead of `/usr/bin`.

**Comment by AdaZhangLi** [comment]
--virtualenv 
if your python's version is 2.7,try this:
virtualenv python27
source python27/bin/activate

**Comment by uyenho90** [comment]
@AdaZhangLi 

Thank you! That did it for me!

**Comment by yeysus** [comment]
Thanks @otech47 . Your sudo pip install --ignore-installed numpy worked for me. Let's see what happens down the road :-).

**Comment by Ivankings** [comment]
> Also
> 
> ```
> sudo pip install --ignore-installed numpy
> ```
> Had to do this with the `six` dependency as well

this work for me
