### ISSUE TITLE
Offering a small TensorFlow runtime for production environments

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tensorflow#6334]
I noticed in https://github.com/tensorflow/tensorflow/pull/1109 that some attempts to reduce the PyPI package have been made,  but since 0.9 the package has grown quite a bit.

Are there any ongoing attempts of creating a smaller TensorFlow runtime that can be used for putting graphs into production? For example, the most common use case for TensorFlow is probably running a machine learning model's forward pass. For that, all of the gradient related code could be excluded from the package, no?

Preferably I'd love a utility that takes in a graph protobuf and spits out a pip installable TensorFlow version with only the required parts of the codebase. Is this at all doable?

**Comment by yaroslavvb** [comment]
@petewarden

**Comment by carlthome** [comment]
I think this could be closed in favor of https://www.tensorflow.org/performance/xla/tfcompile

**Comment by apivovarov** [comment]
I think it should not be closed in favor of XLA AOT because it supports only limited set of the operators.
We need `tensorflow-runtime` package which can be installed on small devices like Raspberry Pi.
Why to install full 80MB package if I'm not going to train the model on Raspberry Pi.

**Comment by carlthome** [comment]
A sweet solution nowadays is to use TensorFlow Lite. It's worked nicely for me. At the time of creating this issue tflite wasn't available yet. :koala:
