### ISSUE TITLE
core dumped with tf.quantization.fake_quant_with_min_max_vars_per_channel

### ISSUE THREAD

**Issue by vwrewsge** [tensorflow/tensorflow#63351]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Python version

3.9

### Current behavior?

core dumped error with specific input parameters.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

input_data = tf.constant(3.0)

min_per_channel = tf.constant(2.0)
max_per_channel = tf.constant(4.0)

quantized_data = tf.quantization.fake_quant_with_min_max_vars_per_channel(input_data, min_per_channel, max_per_channel)
print(quantized_data)
```

### Relevant log output

```shell
2024-03-09 14:43:28.826225: F tensorflow/core/framework/tensor_shape.cc:356] Check failed: d >= 0 (0 vs. -1)
Aborted (core dumped)
```

**Comment by tilakrayal** [comment]
@vwrewsge,
