### ISSUE TITLE
TypeError: Cannot create initializer for non-floating point type

### ISSUE THREAD

**Issue by amirj** [tensorflow/tensorflow#6342]
Operating System: Mac OS [10.11.6]

Installed version of CUDA and cuDNN: CUDA 8.0, cudnn-8.0-osx-x64-v5.1 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
 8 lrwxr-xr-x  1 root    admin    13B Dec 15 13:34 /usr/local/cuda/lib/libcuda.1.dylib@ -> libcuda.dylib
    32 -rwxr-xr-x  1 root    wheel    13K Nov  3 22:09 /usr/local/cuda/lib/libcuda.dylib*
     8 lrwxr-xr-x  1 root    wheel    45B Nov  3 22:10 /usr/local/cuda/lib/libcudadevrt.a@ -> /Developer/NVIDIA/CUDA-8.0/lib/libcudadevrt.a
     8 lrwxr-xr-x  1 root    wheel    50B Nov  3 22:10 /usr/local/cuda/lib/libcudart.8.0.dylib@ -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib
     8 lrwxr-xr-x  1 root    wheel    46B Nov  3 22:10 /usr/local/cuda/lib/libcudart.dylib@ -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.dylib
     8 lrwxr-xr-x  1 root    wheel    49B Nov  3 22:10 /usr/local/cuda/lib/libcudart_static.a@ -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart_static.a
151304 -rwxr-xr-x@ 1 AmirHJ  admin    74M Jul 27 11:48 /usr/local/cuda/lib/libcudnn.5.dylib*
     8 lrwxr-xr-x  1 AmirHJ  admin    16B Jul 27 11:51 /usr/local/cuda/lib/libcudnn.dylib@ -> libcudnn.5.dylib
128152 -rw-r--r--@ 1 AmirHJ  admin    63M Jul 27 11:48 /usr/local/cuda/lib/libcudnn_static.a
```

If installed from binary pip package, provide:

1. A link to the pip package you installed: tensorflow-gpu==0.12.0rc1
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. 0.12.0-rc1

Running [Text Classification Using Convolutional Neural Networks on Characters](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/text_classification_character_cnn.py):

> python test.py
> I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.dylib locally
> I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.dylib locally
> I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.dylib locally
> I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.1.dylib locally
> I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.dylib locally
> WARNING:tensorflow:Using temporary folder as model directory: /var/folders/gy/035w5b717yn01k9qlwvtcp1h0000gn/T/tmpU1WjvQ
> WARNING:tensorflow:From test.py:105 in main.: calling fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with x is deprecated and will be removed after 2016-12-01.
> Instructions for updating:
> Estimator is decoupled from Scikit Learn interface by moving into
> separate class SKCompat. Arguments x, y and batch_size are only
> available in the SKCompat class, Estimator will only accept input_fn.
> Example conversion:
>   est = Estimator(...) -> est = SKCompat(Estimator(...))
> WARNING:tensorflow:From test.py:105 in main.: calling fit (from tensorflow.contrib.learn.python.learn.estimators.estimator) with y is deprecated and will be removed after 2016-12-01.
> Instructions for updating:
> Estimator is decoupled from Scikit Learn interface by moving into
> separate class SKCompat. Arguments x, y and batch_size are only
> available in the SKCompat class, Estimator will only accept input_fn.
> Example conversion:
>   est = Estimator(...) -> est = SKCompat(Estimator(...))
> Traceback (most recent call last):
>   File "test.py", line 121, in <module>
>     tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
>     sys.exit(main(sys.argv[:1] + flags_passthrough))
>   File "test.py", line 105, in main
>     classifier.fit(x_train, y_train, steps=100)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 191, in new_func
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 355, in fit
>     max_steps=max_steps)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 699, in _train_model
>     train_ops = self._get_train_ops(features, labels)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1052, in _get_train_ops
>     return self._call_model_fn(features, labels, model_fn_lib.ModeKeys.TRAIN)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 1023, in _call_model_fn
>     model_fn_results = self._model_fn(features, labels)
>   File "test.py", line 59, in char_cnn_model
>     byte_list, N_FILTERS, FILTER_SHAPE1, padding='VALID')
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
>     return func(*args, **current_args)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 840, in convolution
>     trainable=trainable)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
>     return func(*args, **current_args)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 244, in model_variable
>     caching_device=caching_device, device=device)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
>     return func(*args, **current_args)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 208, in variable
>     caching_device=caching_device)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
>     custom_getter=custom_getter)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
>     custom_getter=custom_getter)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
>     validate_shape=validate_shape)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
>     caching_device=caching_device, validate_shape=validate_shape)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 677, in _get_single_variable
>     expected_shape=shape)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 224, in __init__
>     expected_shape=expected_shape)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 327, in _init_from_args
>     initial_value(), name="initial_value", dtype=dtype)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 665, in <lambda>
>     shape.as_list(), dtype=dtype, partition_info=partition_info)
>   File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/initializers.py", line 120, in _initializer
>     raise TypeError('Cannot create initializer for non-floating point type.')
> TypeError: Cannot create initializer for non-floating point type.

**Comment by aselle** [comment]
I'm able to reproduce this @martinwicke. Any thoughts?

**Comment by ravijagan** [comment]
I see this from TF-SLIM , OSX  

 net = slim.conv2d(inputs, 32, [7, 7], stride=2, scope=end_point)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 900, in convolution
    outputs = layer.apply(inputs)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 293, in apply
    return self.__call__(inputs, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 259, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/layers/convolutional.py", line 138, in build
    dtype=self.dtype)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1063, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 889, in get_variable
    custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 340, in get_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 249, in variable_getter
    variable_getter=functools.partial(getter, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 200, in _add_variable
    trainable=trainable and self.trainable)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1303, in layer_variable_getter
    return _model_variable_getter(getter, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1292, in _model_variable_getter
    custom_getter=getter)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 268, in model_variable
    partitioner=partitioner, custom_getter=custom_getter)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 225, in variable
    partitioner=partitioner)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 332, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 683, in _get_single_variable
    validate_shape=validate_shape)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 225, in __init__
    expected_shape=expected_shape)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 322, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 672, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/initializers.py", line 120, in _initializer
    raise TypeError('Cannot create initializer for non-floating point type.')
TypeError: Cannot create initializer for non-floating point type.

**Comment by ravijagan** [comment]
image = tf.to_float(image) fixes it for now.

**Comment by martinwicke** [comment]
Could someone check #7318 to see whether the fix works?
