### ISSUE TITLE
Udacity LSTM: module 'tensorflow' has no attribute 'concat_v2'

### ISSUE THREAD

**Issue by KeithYJohnson** [tensorflow/tensorflow#6345]
### Environment info
Operating System: OSX 10.12.1

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
```
➜  ~ `python -c "import tensorflow; print(tensorflow.__version__)"`.
zsh: command not found: 0.12.0-rc1.
```

I'm going through the udacity deep learning class and getting an error when evaluating

`logits = tf.nn.xw_plus_b(tf.concat_v2(outputs, 0), w, b)`

which was changed in https://github.com/tensorflow/tensorflow/commit/d4eb834824d79c6a64a3c4a1c4a88b434b73e63e#diff-e4eb32d9f7b7f06d7547050e1ce3d937

```
>>> import tensorflow
>>> tensorflow.__version__
'0.12.0-rc1'
>>> tensorflow.concat_v2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'concat_v2'
>>> tensorflow.concat
<function concat at 0x10bc03730>
>>>
```

I installed and am running the latest release rc1 where `concat_v2` was added in https://github.com/tensorflow/tensorflow/commit/4564322e249017c030123b249451614bc2ff7658, has anyone else seen this?  Thanks in advance!

**Comment by Frobb** [comment]
I ran into the same error yesterday when attempting to run the [code](https://github.com/tensorflow/models/tree/master/tutorials/rnn/ptb) for the PTB LSTM language model example from the TensorFlow tutorials. Also running 0.12.0-rc1. I haven't been able to find a fix for it yet and cannot find any information about it in the docs. :/

**Comment by lenhhoxung86** [comment]
Same problem happened to me. Please give a solution.

**Comment by shiyemin** [comment]
concat_v2 is added in the master branch. I believe you can run these code by switch to master branch.

**Comment by danyz91** [comment]
Hi Guys,
I had the same problem, i just used the previous version of concat because i read here https://www.tensorflow.org/versions/master/api_docs/python/array_ops/slicing_and_joining#concat_v2 that their goal is identical.
The only thing is that the order of the parameters is inverse.
Where concat_v2 takes (values, axis), concat takes (axis,values), so i reversed the parameters calling
tf.concat(0,outputs)
I hope it is right and that it will save you some time!

**Comment by Frobb** [comment]
Ohh, right. Gotta keep an eye out for the master docs as well. Nice find @danyz91!

**Comment by napjon** [comment]
@danyz91 : I don't understand. The link that you gave shows that `concat` function is deprecated and it's encouraged for us to use `concat_v2`. So which one should we use in the long run?

cc @aselle

**Comment by aselle** [comment]
In the short-term (before 1.0 final happens) concat_v2 will be the function to use. Once 1.0 final happens, concat_v2() will be renamed to concat() and then what used to be concat() will cease to exist.

**Comment by napjon** [comment]
@aselle: Got it, thank you for the explanation!

**Comment by samdeeplearning** [comment]
~/ `export TF_BINARY_URL=export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl1`

~/`sudo pip3 install --upgrade $TF_BINARY_URL`

**Comment by linrio** [comment]
Yes ! **concat_v2 -> concat for TF 1.0 **

**Comment by AaronZhangL** [comment]
I got the below error:

> AttributeError: module 'tensorflow' has no attribute 'xw_plus_b'
