### ISSUE TITLE
Windows 10 -> tensorflow-gpu -> TCC mode = Hangs forever

### ISSUE THREAD

**Issue by johnxllis** [tensorflow/tensorflow#6346]
Anybody getting this to work in windows while in TCC CUDA mode? Seems to work fine in WDDM driver mode but WDDM cripples performance. To replicate issue, run on machine with Tesla class GPU in TCC mode, then try to create a session (sess = tf.Session()). The python process consumes a CPU core indefinitely and the session is never created.

**Comment by gunan** [comment]
@johnxllis Do you have physical access to the machine, or do you use remote desktop?

CC @mrry @vit-stepanovs @guschmue

**Comment by johnxllis** [comment]
@gunan This is physical machine on my desktop. However, I am now seeing evidence that this issue is larger than just Tensorflow as it seems to be affecting Theano as well. The problem is most likely in CUDA or the configuration of the machine. I am closing the issue until I can isolate further.
