### ISSUE TITLE
Tensorflow library for python 3 not available from the suggested docker image

### ISSUE THREAD

**Issue by brando90** [tensorflow/tensorflow#6348]
I noticed that tensorflow is not available from the standard `gcr.io/tensorflow/tensorflow` docker image.

I spun a docker container:

    docker run -it --rm gcr.io/tensorflow/tensorflow bash

then I tried importing the Tensorflow from within python3:

```
root@dc7f436ca5e9:/notebooks# python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'tensorflow'
```

but the library is not available. Is this a bug or is this the intended feature? Does this mean I need to install tensorflow (for python3) myself with pip3 then in my own image? or maybe its a small bug?

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

http://stackoverflow.com/questions/41170610/what-is-the-correct-way-to-have-tensorflow-available-in-a-docker-container-or-do

### Environment info
Operating System: MAC OS X sierra 10.12.1

**Comment by aselle** [comment]
@caisq can you take a look. @brando90, you can just use `docker run -it tensorflow/tensorflow bash` to use docker hub. Also, you should almost always use a tag of the version you want to use... rather than tensorflow/tensorflow alone, because the semantics of latest are confusing.

**Comment by caisq** [comment]
@brando90, when you do use the image name `gcr.io/tensorflow/tensorflow` without any tags at the end, you are implicitly pointing to the `latest` tag, which is for python2 only. The tag `latest-py3` is most likely the one you want. So just do:

```
docker run -it --rm gcr.io/tensorflow/tensorflow:latest-py3 bash
```

As @aselle pointed out, you could also download the image from Docker Hub, instead of gcr.io:

```
docker run -it --rm tensorflow/tensorflow:latest-py3 bash
```

**Comment by caisq** [comment]
I'm closing this issue. Please let me know if you have any remaining questions.
