### ISSUE TITLE
I cannot understand this AttributeError : module 'tensorflow.python.ops.control_flow_ops' has no attribute 'case'

### ISSUE THREAD

**Issue by Rajcr2** [tensorflow/tensorflow#63515]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.15.0

### Custom code

Yes

### Current behavior?

AttributeError: module 'tensorflow.python.ops.control_flow_ops' has no attribute 'case'.

I clone this Git model - https://github.com/tensorflow/models.git and got this error anyone please tell solution.

Thank You.

### Standalone code to reproduce the issue

```shell
WARNING:tensorflow:From /usr/local/lib/python3.10/dist-packages/object_detection/model_lib_v2.py:563: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
rename to distribute_datasets_from_function
W0312 15:35:40.912783 134985257164800 deprecation.py:50] From /usr/local/lib/python3.10/dist-packages/object_detection/model_lib_v2.py:563: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.
Instructions for updating:
rename to distribute_datasets_from_function
INFO:tensorflow:Reading unweighted datasets: ['/content/drive/MyDrive/Tensorflow/workspace/CCTV_New/annotations/train.record']
I0312 15:35:40.931479 134985257164800 dataset_builder.py:162] Reading unweighted datasets: ['/content/drive/MyDrive/Tensorflow/workspace/CCTV_New/annotations/train.record']
INFO:tensorflow:Reading record datasets for input file: ['/content/drive/MyDrive/Tensorflow/workspace/CCTV_New/annotations/train.record']
I0312 15:35:40.931926 134985257164800 dataset_builder.py:79] Reading record datasets for input file: ['/content/drive/MyDrive/Tensorflow/workspace/CCTV_New/annotations/train.record']
INFO:tensorflow:Number of filenames to read: 1
I0312 15:35:40.932068 134985257164800 dataset_builder.py:80] Number of filenames to read: 1
WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.
W0312 15:35:40.932148 134985257164800 dataset_builder.py:86] num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From /usr/local/lib/python3.10/dist-packages/object_detection/builders/dataset_builder.py:100: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.deterministic`.
W0312 15:35:40.940362 134985257164800 deprecation.py:50] From /usr/local/lib/python3.10/dist-packages/object_detection/builders/dataset_builder.py:100: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.deterministic`.
WARNING:tensorflow:From /usr/local/lib/python3.10/dist-packages/object_detection/builders/dataset_builder.py:235: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
W0312 15:35:40.964928 134985257164800 deprecation.py:50] From /usr/local/lib/python3.10/dist-packages/object_detection/builders/dataset_builder.py:235: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map()
Traceback (most recent call last):
  File "/content/drive/MyDrive/Tensorflow/workspace/CCTV_New/model_main_tf2.py", line 114, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/content/drive/MyDrive/Tensorflow/workspace/CCTV_New/model_main_tf2.py", line 105, in main
    model_lib_v2.train_loop(
  File "/usr/local/lib/python3.10/dist-packages/object_detection/model_lib_v2.py", line 563, in train_loop
    train_input = strategy.experimental_distribute_datasets_from_function(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/deprecation.py", line 383, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 1563, in experimental_distribute_datasets_from_function
    return self.distribute_datasets_from_function(dataset_fn, options)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 1554, in distribute_datasets_from_function
    return self._extended._distribute_datasets_from_function(  # pylint: disable=protected-access
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/mirrored_strategy.py", line 613, in _distribute_datasets_from_function
    return input_util.get_distributed_datasets_from_function(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/input_util.py", line 144, in get_distributed_datasets_from_function
    return input_lib.DistributedDatasetsFromFunction(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/input_lib.py", line 1143, in __init__
    self.build()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/input_lib.py", line 1165, in build
    _create_datasets_from_function_with_input_context(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/distribute/input_lib.py", line 1680, in _create_datasets_from_function_with_input_context
    dataset = dataset_fn(ctx)
  File "/usr/local/lib/python3.10/dist-packages/object_detection/model_lib_v2.py", line 554, in train_dataset_fn
    train_input = inputs.train_input(
  File "/usr/local/lib/python3.10/dist-packages/object_detection/inputs.py", line 908, in train_input
    dataset = INPUT_BUILDER_UTIL_MAP['dataset_build'](
  File "/usr/local/lib/python3.10/dist-packages/object_detection/builders/dataset_builder.py", line 250, in build
    dataset = dataset_map_fn(dataset, decoder.decode, batch_size,
  File "/usr/local/lib/python3.10/dist-packages/object_detection/builders/dataset_builder.py", line 235, in dataset_map_fn
    dataset = dataset.map_with_legacy_function(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/deprecation.py", line 383, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 4128, in map_with_legacy_function
    return map_op._map_v1_with_legacy_function(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/ops/map_op.py", line 85, in _map_v1_with_legacy_function
    _ParallelMapDataset(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/ops/map_op.py", line 148, in __init__
    self._map_func = structured_function.StructuredFunctionWrapper(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/ops/structured_function.py", line 272, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/function.py", line 579, in add_to_graph
    self._create_definition_if_needed()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/function.py", line 412, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/function.py", line 430, in _create_definition_if_needed_impl
    temp_graph = func_graph_from_py_func(
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/function.py", line 1007, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/ops/structured_function.py", line 178, in wrapped_fn
    ret = wrapper_helper(*args)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/ops/structured_function.py", line 161, in wrapper_helper
    ret = autograph.tf_convert(self._func, ag_ctx)(*nested_args)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 693, in wrapper
    raise e.ag_error_metadata.to_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 690, in wrapper
    return converted_call(f, args, kwargs, options=options)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_filey1kf8ufy.py", line 74, in tf__decode
    tensors = ag__.converted_call(ag__.ld(decoder).decode, (ag__.ld(serialized_example),), dict(items=ag__.ld(keys)), fscope)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 439, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "/tmp/__autograph_generated_fileo39plnsc.py", line 81, in tf__decode
    ag__.for_stmt(ag__.ld(items), None, loop_body_1, get_state_3, set_state_3, (), {'iterate_names': 'item'})
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 449, in for_stmt
    for_fn(iter_, extra_test, body, get_state, set_state, symbol_names, opts)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 500, in _py_for_stmt
    body(target)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 466, in protected_body
    original_body(protected_iter)
  File "/tmp/__autograph_generated_fileo39plnsc.py", line 77, in loop_body_1
    ag__.converted_call(ag__.ld(outputs).append, (ag__.converted_call(ag__.ld(handler).tensors_to_item, (ag__.ld(keys_to_tensors),), None, fscope),), None, fscope)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 441, in converted_call
    result = converted_f(*effective_args)
  File "/tmp/__autograph_generated_filenauzobq0.py", line 39, in tf__tensors_to_item
    ag__.if_stmt(ag__.ld(self)._repeated, if_body, else_body, get_state, set_state, ('do_return', 'retval_'), 2)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 1217, in if_stmt
    _py_if_stmt(cond, body, orelse)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/operators/control_flow.py", line 1270, in _py_if_stmt
    return body() if cond else orelse()
  File "/tmp/__autograph_generated_filenauzobq0.py", line 35, in else_body
    retval_ = ag__.converted_call(ag__.ld(self)._decode, (ag__.ld(image_buffer), ag__.ld(image_format)), None, fscope)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/autograph/impl/api.py", line 441, in converted_call
    result = converted_f(*effective_args)
  File "/tmp/__autograph_generated_filenftifa_u.py", line 80, in tf___decode
    image = ag__.converted_call(ag__.ld(control_flow_ops).case, (ag__.ld(pred_fn_pairs),), dict(default=ag__.ld(check_jpeg), exclusive=True), fscope)
AttributeError: in user code:

    File "/usr/local/lib/python3.10/dist-packages/object_detection/data_decoders/tf_example_decoder.py", line 556, in decode  *
        tensors = decoder.decode(serialized_example, items=keys)
    File "/usr/local/lib/python3.10/dist-packages/tf_slim/data/tfexample_decoder.py", line 722, in decode  *
        outputs.append(handler.tensors_to_item(keys_to_tensors))
    File "/usr/local/lib/python3.10/dist-packages/tf_slim/data/tfexample_decoder.py", line 405, in tensors_to_item  *
        return self._decode(image_buffer, image_format)
    File "/usr/local/lib/python3.10/dist-packages/tf_slim/data/tfexample_decoder.py", line 453, in _decode  *
        image = control_flow_ops.case(

    AttributeError: module 'tensorflow.python.ops.control_flow_ops' has no attribute 'case'
```

**Comment by mihaimaruseac** [comment]
Can you post the output of `pip list` please? It is likely you have mismatched packages.

The error occurs from `control_flow_ops.case` where `control_flow_ops` is the module `tensorflow.python.ops.control_flow_ops` from TensorFlow, as it is imported by `tf_slim`. It means that the version of TF you have does not have a `case` symbol defined in this module, but the code from the `tf_slim` version you have is expecting one.

**Comment by Rajcr2** [comment]
> Can you post the output of `pip list` please? It is likely you have mismatched packages.
> 
> The error occurs from `control_flow_ops.case` where `control_flow_ops` is the module `tensorflow.python.ops.control_flow_ops` from TensorFlow, as it is imported by `tf_slim`. It means that the version of TF you have does not have a `case` symbol defined in this module, but the code from the `tf_slim` version you have is expecting one.

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.3
aiosignal                        1.3.1
alabaster                        0.7.16
albumentations                   1.3.1
altair                           4.2.2
annotated-types                  0.6.0
anyio                            3.7.1
apache-beam                      2.54.0
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.5.0
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.0
attrs                            23.2.0
audioread                        3.0.1
autograd                         1.6.2
avro-python3                     1.10.2
Babel                            2.14.0
backcall                         0.2.0
beautifulsoup4                   4.12.3
bidict                           0.23.1
bigframes                        0.23.0
bleach                           6.1.0
blinker                          1.4
blis                             0.7.11
blosc2                           2.0.0
bokeh                            3.3.4
bqplot                           0.12.43
branca                           0.7.1
build                            1.1.1
CacheControl                     0.14.0
cachetools                       5.3.3
catalogue                        2.0.10
certifi                          2024.2.2
cffi                             1.16.0
chardet                          5.2.0
charset-normalizer               3.3.2
chex                             0.1.85
click                            8.1.7
click-plugins                    1.1.1
cligj                            0.7.2
cloudpathlib                     0.16.0
cloudpickle                      2.2.1
cmake                            3.27.9
cmdstanpy                        1.2.1
colorama                         0.4.6
colorcet                         3.1.0
colorlover                       0.3.0
colour                           0.1.5
community                        1.0.0b1
confection                       0.1.4
cons                             0.4.6
contextlib2                      21.6.0
contourpy                        1.2.0
crcmod                           1.7
cryptography                     42.0.5
cufflinks                        0.17.3
cupy-cuda12x                     12.2.0
cvxopt                           1.3.2
cvxpy                            1.3.3
cycler                           0.12.1
cymem                            2.0.8
Cython                           3.0.9
dask                             2023.8.1
datascience                      0.17.6
db-dtypes                        1.2.0
dbus-python                      1.2.18
debugpy                          1.6.6
decorator                        4.4.2
defusedxml                       0.7.1
dill                             0.3.1.1
distributed                      2023.8.1
distro                           1.7.0
dlib                             19.24.2
dm-tree                          0.1.8
dnspython                        2.6.1
docopt                           0.6.2
docutils                         0.18.1
dopamine-rl                      4.0.6
duckdb                           0.9.2
earthengine-api                  0.1.393
easydict                         1.13
ecos                             2.0.13
editdistance                     0.6.2
eerepr                           0.0.4
en-core-web-sm                   3.7.1
entrypoints                      0.4
et-xmlfile                       1.1.0
etils                            1.7.0
etuples                          0.3.9
exceptiongroup                   1.2.0
fastai                           2.7.14
fastavro                         1.9.4
fastcore                         1.5.29
fastdownload                     0.0.7
fasteners                        0.19
fastjsonschema                   2.19.1
fastprogress                     1.0.3
fastrlock                        0.8.2
filelock                         3.13.1
fiona                            1.9.5
firebase-admin                   5.3.0
Flask                            2.2.5
flatbuffers                      24.3.6
flax                             0.8.1
folium                           0.14.0
fonttools                        4.49.0
frozendict                       2.4.0
frozenlist                       1.4.1
fsspec                           2023.6.0
future                           0.18.3
gast                             0.5.4
gcsfs                            2023.6.0
GDAL                             3.6.4
gdown                            4.7.3
geemap                           0.32.0
gensim                           4.3.2
geocoder                         1.38.1
geographiclib                    2.0
geopandas                        0.13.2
geopy                            2.3.0
gin-config                       0.5.0
glob2                            0.7
google                           2.0.3
google-ai-generativelanguage     0.4.0
google-api-core                  2.11.1
google-api-python-client         2.84.0
google-auth                      2.27.0
google-auth-httplib2             0.1.1
google-auth-oauthlib             1.2.0
google-cloud-aiplatform          1.43.0
google-cloud-bigquery            3.12.0
google-cloud-bigquery-connection 1.12.1
google-cloud-bigquery-storage    2.24.0
google-cloud-core                2.3.3
google-cloud-datastore           2.15.2
google-cloud-firestore           2.11.1
google-cloud-functions           1.13.3
google-cloud-iam                 2.14.3
google-cloud-language            2.13.3
google-cloud-resource-manager    1.12.3
google-cloud-storage             2.8.0
google-cloud-translate           3.11.3
google-colab                     1.0.0
google-crc32c                    1.5.0
google-generativeai              0.3.2
google-pasta                     0.2.0
google-resumable-media           2.7.0
googleapis-common-protos         1.62.0
googledrivedownloader            0.4
graphviz                         0.20.1
greenlet                         3.0.3
grpc-google-iam-v1               0.13.0
grpcio                           1.62.0
grpcio-status                    1.48.2
gspread                          3.4.2
gspread-dataframe                3.3.1
gym                              0.25.2
gym-notices                      0.0.8
h5netcdf                         1.3.0
h5py                             3.9.0
hdfs                             2.7.3
holidays                         0.44
holoviews                        1.17.1
html5lib                         1.1
httpimport                       1.3.1
httplib2                         0.22.0
huggingface-hub                  0.20.3
humanize                         4.7.0
hyperopt                         0.2.7
ibis-framework                   8.0.0
idna                             3.6
imageio                          2.31.6
imageio-ffmpeg                   0.4.9
imagesize                        1.4.1
imbalanced-learn                 0.10.1
imgaug                           0.4.0
immutabledict                    4.2.0
importlib_metadata               7.0.2
importlib_resources              6.1.3
imutils                          0.5.4
inflect                          7.0.0
iniconfig                        2.0.0
intel-openmp                     2023.2.3
ipyevents                        2.0.2
ipyfilechooser                   0.6.0
ipykernel                        5.5.6
ipyleaflet                       0.18.2
ipython                          7.34.0
ipython-genutils                 0.2.0
ipython-sql                      0.5.0
ipytree                          0.2.2
ipywidgets                       7.7.1
itsdangerous                     2.1.2
jax                              0.4.23
jaxlib                           0.4.23+cuda12.cudnn89
jeepney                          0.7.1
jieba                            0.42.1
Jinja2                           3.1.3
joblib                           1.3.2
Js2Py                            0.74
jsonpickle                       3.0.3
jsonschema                       4.19.2
jsonschema-specifications        2023.12.1
jupyter-client                   6.1.12
jupyter-console                  6.1.0
jupyter_core                     5.7.1
jupyter-server                   1.24.0
jupyterlab_pygments              0.3.0
jupyterlab_widgets               3.0.10
kaggle                           1.5.16
kagglehub                        0.2.0
keras                            2.15.0
keyring                          23.5.0
kiwisolver                       1.4.5
langcodes                        3.3.0
launchpadlib                     1.10.16
lazr.restfulclient               0.14.4
lazr.uri                         1.0.6
lazy_loader                      0.3
libclang                         16.0.6
librosa                          0.10.1
lightgbm                         4.1.0
linkify-it-py                    2.0.3
llvmlite                         0.41.1
locket                           1.0.0
logical-unification              0.4.6
lvis                             0.5.3
lxml                             4.9.4
malloy                           2023.1067
Markdown                         3.5.2
markdown-it-py                   3.0.0
MarkupSafe                       2.1.5
matplotlib                       3.7.1
matplotlib-inline                0.1.6
matplotlib-venn                  0.11.10
mdit-py-plugins                  0.4.0
mdurl                            0.1.2
miniKanren                       1.0.3
missingno                        0.5.2
mistune                          0.8.4
mizani                           0.9.3
mkl                              2023.2.0
ml-dtypes                        0.2.0
mlxtend                          0.22.0
more-itertools                   10.1.0
moviepy                          1.0.3
mpmath                           1.3.0
msgpack                          1.0.8
multidict                        6.0.5
multipledispatch                 1.0.0
multitasking                     0.0.11
murmurhash                       1.0.10
music21                          9.1.0
natsort                          8.4.0
nbclassic                        1.0.0
nbclient                         0.9.0
nbconvert                        6.5.4
nbformat                         5.9.2
nest-asyncio                     1.6.0
networkx                         3.2.1
nibabel                          4.0.2
nltk                             3.8.1
notebook                         6.5.5
notebook_shim                    0.2.4
numba                            0.58.1
numexpr                          2.9.0
numpy                            1.24.4
oauth2client                     4.1.3
oauthlib                         3.2.2
object-detection                 0.1
objsize                          0.7.0
opencv-contrib-python            4.8.0.76
opencv-python                    4.8.0.76
opencv-python-headless           4.9.0.80
openpyxl                         3.1.2
opt-einsum                       3.3.0
optax                            0.2.1
orbax-checkpoint                 0.4.4
orjson                           3.9.15
osqp                             0.6.2.post8
packaging                        23.2
pandas                           1.5.3
pandas-datareader                0.10.0
pandas-gbq                       0.19.2
pandas-stubs                     1.5.3.230304
pandocfilters                    1.5.1
panel                            1.3.8
param                            2.0.2
parso                            0.8.3
parsy                            2.1
partd                            1.4.1
pathlib                          1.0.1
patsy                            0.5.6
peewee                           3.17.1
pexpect                          4.9.0
pickleshare                      0.7.5
Pillow                           9.4.0
pip                              23.1.2
pip-tools                        6.13.0
platformdirs                     4.2.0
plotly                           5.15.0
plotnine                         0.12.4
pluggy                           1.4.0
polars                           0.20.2
pooch                            1.8.1
portalocker                      2.8.2
portpicker                       1.5.2
prefetch-generator               1.0.3
preshed                          3.0.9
prettytable                      3.10.0
proglog                          0.1.10
progressbar2                     4.2.0
prometheus_client                0.20.0
promise                          2.3
prompt-toolkit                   3.0.43
prophet                          1.1.5
proto-plus                       1.23.0
protobuf                         3.20.3
psutil                           5.9.5
psycopg2                         2.9.9
ptyprocess                       0.7.0
py-cpuinfo                       9.0.0
py4j                             0.10.9.7
pyarrow                          14.0.2
pyarrow-hotfix                   0.6
pyasn1                           0.5.1
pyasn1-modules                   0.3.0
pycocotools                      2.0
pycparser                        2.21
pydantic                         2.6.3
pydantic_core                    2.16.3
pydata-google-auth               1.8.2
pydot                            1.4.2
pydot-ng                         2.0.0
pydotplus                        2.0.2
PyDrive                          1.3.1
PyDrive2                         1.6.3
pyerfa                           2.0.1.1
pygame                           2.5.2
Pygments                         2.16.1
PyGObject                        3.42.1
pyjsparser                       2.7.1
PyJWT                            2.3.0
pymc                             5.10.4
pymongo                          4.6.2
pymystem3                        0.2.0
PyOpenGL                         3.1.7
pyOpenSSL                        24.0.0
pyparsing                        2.4.7
pyperclip                        1.8.2
pyproj                           3.6.1
pyproject_hooks                  1.0.0
pyshp                            2.3.1
PySocks                          1.7.1
pytensor                         2.18.6
pytest                           7.4.4
python-apt                       0.0.0
python-box                       7.1.1
python-dateutil                  2.8.2
python-louvain                   0.16
python-slugify                   8.0.4
python-utils                     3.8.2
pytz                             2023.4
pyviz_comms                      3.0.1
PyWavelets                       1.5.0
PyYAML                           6.0.1
pyzmq                            23.2.1
qdldl                            0.1.7.post0
qudida                           0.0.4
ratelim                          0.1.6
referencing                      0.33.0
regex                            2023.12.25
requests                         2.31.0
requests-oauthlib                1.3.1
requirements-parser              0.5.0
rich                             13.7.1
rpds-py                          0.18.0
rpy2                             3.4.2
rsa                              4.9
sacrebleu                        2.2.0
safetensors                      0.4.2
scikit-image                     0.19.3
scikit-learn                     1.2.2
scipy                            1.11.4
scooby                           0.9.2
scs                              3.2.4.post1
seaborn                          0.13.1
SecretStorage                    3.3.1
Send2Trash                       1.8.2
sentencepiece                    0.1.99
seqeval                          1.2.2
setuptools                       67.7.2
shapely                          2.0.3
six                              1.16.0
sklearn-pandas                   2.2.0
smart-open                       6.4.0
sniffio                          1.3.1
snowballstemmer                  2.2.0
sortedcontainers                 2.4.0
soundfile                        0.12.1
soupsieve                        2.5
soxr                             0.3.7
spacy                            3.7.4
spacy-legacy                     3.0.12
spacy-loggers                    1.0.5
Sphinx                           5.0.2
sphinxcontrib-applehelp          1.0.8
sphinxcontrib-devhelp            1.0.6
sphinxcontrib-htmlhelp           2.0.5
sphinxcontrib-jsmath             1.0.1
sphinxcontrib-qthelp             1.0.7
sphinxcontrib-serializinghtml    1.1.10
SQLAlchemy                       2.0.28
sqlglot                          20.11.0
sqlparse                         0.4.4
srsly                            2.4.8
stanio                           0.3.0
statsmodels                      0.14.1
sympy                            1.12
tables                           3.8.0
tabulate                         0.9.0
tbb                              2021.11.0
tblib                            3.0.0
tenacity                         8.2.3
tensorboard                      2.15.2
tensorboard-data-server          0.7.2
tensorflow                       2.15.0
tensorflow-datasets              4.9.4
tensorflow-estimator             2.15.0
tensorflow-gcs-config            2.15.0
tensorflow-hub                   0.16.1
tensorflow-io                    0.36.0
tensorflow-io-gcs-filesystem     0.36.0
tensorflow-metadata              1.14.0
tensorflow-model-optimization    0.8.0
tensorflow-probability           0.23.0
tensorflow-text                  2.15.0
tensorstore                      0.1.45
termcolor                        2.4.0
terminado                        0.18.0
text-unidecode                   1.3
textblob                         0.17.1
tf-keras                         2.15.0
tf-models-official               2.15.0
tf-slim                          1.1.0
thinc                            8.2.3
threadpoolctl                    3.3.0
tifffile                         2024.2.12
tinycss2                         1.2.1
tokenizers                       0.15.2
toml                             0.10.2
tomli                            2.0.1
toolz                            0.12.1
torch                            2.1.0+cu121
torchaudio                       2.1.0+cu121
torchdata                        0.7.0
torchsummary                     1.5.1
torchtext                        0.16.0
torchvision                      0.16.0+cu121
tornado                          6.3.3
tqdm                             4.66.2
traitlets                        5.7.1
traittypes                       0.2.1
transformers                     4.38.2
triton                           2.1.0
tweepy                           4.14.0
typer                            0.9.0
types-pytz                       2024.1.0.20240203
types-setuptools                 69.1.0.20240308
typing_extensions                4.10.0
tzlocal                          5.2
uc-micro-py                      1.0.3
uritemplate                      4.1.1
urllib3                          2.0.7
vega-datasets                    0.9.0
wadllib                          1.3.6
wasabi                           1.1.2
wcwidth                          0.2.13
weasel                           0.3.4
webcolors                        1.13
webencodings                     0.5.1
websocket-client                 1.7.0
Werkzeug                         3.0.1
wheel                            0.42.0
widgetsnbextension               3.6.6
wordcloud                        1.9.3
wrapt                            1.14.1
xarray                           2023.7.0
xarray-einstats                  0.7.0
xgboost                          2.0.3
xlrd                             2.0.1
xyzservices                      2023.10.1
yarl                             1.9.4
yellowbrick                      1.5
yfinance                         0.2.37
zict                             3.0.0
zipp                             3.17.0
zstandard                        0.22.0


is This info fine ?

**Comment by mihaimaruseac** [comment]
> is This info fine ?

Yes, I just edited it to be properly wrapped in formatted text (useful when reading command output).

You are using `tf-slim` 1.1.0, which has the following [on their README](https://github.com/google-research/tf-slim)

> Note: Latest version of TF-Slim, 1.1.0, was tested with TF 1.15.2 py2, TF 2.0.1, TF 2.1 and TF 2.2.

However, you have `tensorflow-2.15.0`. This is a difference of nearly 3-4 years between the latest tested version and the version you are using. TF code has changed during this time and the `case` symbol is no longer present

**Comment by Rajcr2** [comment]
Thanks.
What should i do now to solve this attribute error.
do i need to upgrade this tf-slim package.

using 
pip install --upgrade tf_slim

**Comment by Rajcr2** [comment]
> > is This info fine ?
> 
> Yes, I just edited it to be properly wrapped in formatted text (useful when reading command output).
> 
> You are using `tf-slim` 1.1.0, which has the following [on their README](https://github.com/google-research/tf-slim)
> 
> > Note: Latest version of TF-Slim, 1.1.0, was tested with TF 1.15.2 py2, TF 2.0.1, TF 2.1 and TF 2.2.
> 
> However, you have `tensorflow-2.15.0`. This is a difference of nearly 3-4 years between the latest tested version and the version you are using. TF code has changed during this time and the `case` symbol is no longer present

Thanks.
What should i do now to solve this attribute error.
do i need to upgrade this tf-slim package.

using
pip install --upgrade tf_slim

**Comment by yAlqubati** [comment]
it might be too late but here is the solution

got to tfexample_decoder.py

incase you are using colab here the path to it
`/usr/local/lib/python3.11/dist-packages/tf_slim/data/tfexample_decoder.py`

add these imports
`from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import tensorflow as tf`

here is what your imports should look like
`from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import abc
import tensorflow as tf
import six

from tf_slim.data import data_decoder
from tensorflow.python.framework import constant_op
from tensorflow.python.framework import dtypes
from tensorflow.python.framework import ops
from tensorflow.python.framework import sparse_tensor
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import check_ops
from tensorflow.python.ops import image_ops
from tensorflow.python.ops import map_fn
from tensorflow.python.ops import math_ops
from tensorflow.python.ops import parsing_ops
from tensorflow.python.ops import sparse_ops
# pylint:enable=g-direct-tensorflow-import
`

remove this line
`from tensorflow.python.ops import control_flow_ops`

and remove any `control_flow_ops.*` with `tf.*`
(search the whole file for control_flow_ops. they occur more than once)

for example remove `image = control_flow_ops.case(pred_fn_pairs, default=check_jpeg, exclusive=True)`
and replace it with `image = tf.case(pred_fn_pairs, default=check_jpeg, exclusive=True)`

I hope this helps
