### ISSUE TITLE
What is login password in the jupyter notebook?

### ISSUE THREAD

**Issue by jessyuan24** [tensorflow/tensorflow#6351]
What is login password in the jupyter notebook?

**Comment by jessyuan24** [comment]
in Docker

**Comment by weity** [comment]
hi jessyuan24,

I'm looking for the password too.I find the password is added on commit [5f45249][commit_url] as described at  [#2378][issue_url].It seems the password is passed when we download the image as commond `docker run -it -p 8888:8888 $CUDA_SO $DEVICES -e PASSWORD=pass gcr.io/tensorflow/tensorflow-gpu` shown.

But when I run the image step by tensorflow guide,I didn't tap -e option.so it's really confused me. 

[commit_url]:https://github.com/tensorflow/tensorflow/commit/5f4524928af5ba5727fa97a35ddd5da72be0c476
[issue_url]:https://github.com/tensorflow/tensorflow/pull/2378

**Comment by jessyuan24** [comment]
yes. I got it.-e option is bash shell parameter option.

**Comment by aselle** [comment]
-e is a docker parameter to export the environment variable to override the docker image. It seems like that works. We should definitely add this to the docker instructions @caisq.

**Comment by jessyuan24** [comment]
Thanks you.

**Comment by jessyuan24** [comment]
Thank you!!

**Comment by weity** [comment]
Finally,I find a way to access jupyter notebook.Recreate a container and specify a password.
```
docker create -it -p 8888:8888 -e PASSWORD=JovialGates --name jovial_gates gcr.io/tensorflow/tensorflow
docker start jovial_gates
```
then I can enter the notebook.

**Comment by BobbyL2k** [comment]
This should be re-open since the use of jupyter_notebook_config.py was removed in cae5763 and the PASSWORD env variable is now ignored.

**Comment by mihaimaruseac** [comment]
I recommend opening a new issue instead, filling in the corresponding issue template. Not many developers are looking at closed issues.

**Comment by Daphneitec** [comment]
Has anyone working on this -e PASSWORD=pass? Is it fixed?
