### ISSUE TITLE
how to commit code to tensorflow??I 

### ISSUE THREAD

**Issue by guoying1030** [tensorflow/tensorflow#6352]
When using distributed tensorflow, once the start of the cluster task, you can not online expansion of the number of workers trained, I achieved this feature, would like to submit to tensorflow。。。

how do it?

**Comment by yaroslavvb** [comment]
https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md
https://guides.github.com/activities/contributing-to-open-source/

**Comment by guoying1030** [comment]
@yaroslavvb ...thank you very much

**Comment by vrv** [comment]
Thanks Yaroslav.

@guoying1030 if this is a big feature change, you should file another issue describing your idea so it go through a design review before spending too much time getting the PR ready.  We wouldn't want you to spend too much time setting up the PR if we wouldn't be able to accept the change for other technical reasons :)

**Comment by guoying1030** [comment]
@vrv ,,,how to write this design???Is there a template?

**Comment by vrv** [comment]
There isn't exactly a template yet.   It might be helpful to follow the beginning steps from something like  https://github.com/golang/proposal#readme: file an issue with the feature request, proposing in detail the scenario that you would like to enable.  We can then go through the process of discussing the options for implementing them, and depending on the scope of that work, the next steps might be either a design doc, or a simple PR.
