### ISSUE TITLE
TF for Embedded Devices

### ISSUE THREAD

**Issue by kevinashaw** [tensorflow/tensorflow#6357]
Has there been any effort to port the TensorFlow inference routines to lightweight cores commonly found in embedded devices (i.e. ARM Cortex M4F)?  Memory footprints are often small, but with efficient use of small datatypes, it seems that this could be fruitful.  Thanks.

**Comment by aselle** [comment]
There have been ports to Rasberry PI's that run full Linux stacks see https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md

However, I am not aware of any ports to MCUs that run RTOS' or bare metal. There may be some features in the soon to be released XLA that help deploy individual inference routines derived from TensorFlow.

@petewarden, do you have anything else to add?

**Comment by DjangoPeng** [comment]
@aselle I'm working on it.

**Comment by jart** [comment]
The work @samjabrahams is actively doing on bringing TensorFlow to Raspberry Pi seems like a satisfactory response to this question. If you would like to request TensorFlow for a specific platform, e.g. ARM Cortex M4F, or have the aforementioned project merged into TensorFlow, then please open a new issue. Or I can re-open and rename this one.

**Comment by samjabrahams** [comment]
Just saw this thread: I figured I may as well chip in a few bits of info:

Regarding Makefile support:

* If you're simply looking for any kind of inference support, the "most officially supported" thing to do is to try and modify the [Makefile instructions](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile) to work on whatever system you're trying to build. This leaves you with a static library that can run your model.
* You could try following the [Raspberry Pi Makefile tutorial](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/pi_examples) to figure out the necessary flags to work on your system.
* Once you've got a decent idea of how to compile, you could replace the pre-trained Inception model from the tutorial with whatever trained model you want to use 
    * You'll want to [freeze]() and [optimize]() your exported model so that it's contained in a single protobuf file (which is what the Inception model looks like)
* All this said, I can't say for sure if ARMv7-M would compile successfully (I'm fairly confident ARMv6 doesn't have the right instructions to work properly with the current codebase)

Regarding my repository:

* If you want full TensorFlow functionality and/or the ability to run it from Python, you're going to have to get Bazel installed on whatever system you're running (the majority of the work done for my repo is figuring out how to compile new versions of Bazel)
* You'll also want to figure out a reasonable cross-compilation setup, if possible. I'm still looking for a consistent way to avoid compiling everything directly on the Raspberry Pi
* I'm a little behind on the current versions of TensorFlow/Bazel- holidays + vacation + work has led to much less time going toward the repo. Hopefully I can get it together by 1.0.0-final!

**Comment by bryant1410** [comment]
[Bender](https://github.com/xmartlabs/Bender) supports running TensorFlow models on iOS. Maybe it's interesting for you.

**Comment by dsiot** [comment]
@samjabrahams great work on this. we could be interested to contribute more also as part of my course (@Oxford Data Science for IoT) - has there been more updates re the TF on Pi? also .. does this come under the TF embedded / mobile tensorflow umbrella? finally which use cases are you considering for Pi(ex image or beyond) many thanks! Ajit

**Comment by samjabrahams** [comment]
@dsiot There has been some work towards making official support in #5729 - that may be where you want to look next/continue the discussion!

**Comment by dsiot** [comment]
thanks for the prompt reply!
