### ISSUE TITLE
tf.tensor_scatter_nd_update lead to a program abortion when receiving a 3d indices

### ISSUE THREAD

**Issue by maybeLee** [tensorflow/tensorflow#63575]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15.0

### Custom code

Yes

### Python version

3.9

### Current behavior?

Hi, when I am using the tf.tensor_scatter_nd_update with a 3d indices, it leads to a program abortion with the error message mentioning:
```
tensorflow/core/framework/tensor_shape.cc:357] Check failed: d < dims() (1 vs. 1)
```
It seems that the issue occurs in this line:
https://github.com/tensorflow/tensorflow/blob/42eb06b2830b07ee78bc25b16be003e356f2f3ff/tensorflow/core/framework/tensor_shape.cc#L357

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

input = tf.constant([248, 225])
indices = tf.constant([[[1]]])
updates = tf.constant([16])
tf.tensor_scatter_nd_update(input, indices, updates)
```
```


### Relevant log output

_No response_

**Comment by seawaylee** [comment]
Did you find the way to handle this?

**Comment by maybeLee** [comment]
Hi @seawaylee, it seems that a pr is initiated https://github.com/tensorflow/tensorflow/pull/63725

**Comment by tilakrayal** [comment]
@maybeLee,
The PR https://github.com/tensorflow/tensorflow/pull/63725 which was raised was closed and mentioned that 
``` python
The assert that should fail is the last one, which has an equality assertion on the sizes of updates.shape == batch_shape + inner_shape
```

https://github.com/tensorflow/tensorflow/pull/63725

Could you please take a look and provide the context to fulfill and get the PR merged. Thank you!
