### ISSUE TITLE
Convert Tensorflow model to TFLite Model light weight converting

### ISSUE THREAD

**Issue by selvakarna** [tensorflow/tensorflow#63607]
### 1. System information

- Windows
-Tensorflow2

### 2. Code

import tensorflow as tf
import numpy as np
model_path ="Model\Path"
model = tf.saved_model.load(model_path)

converter=tf.lite.TFLiteConverter.from_keras_model(r"\saved_model.pb") #model_path
converter.optimizations=[tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True
tflite_model = converter.convert() 
tflite_model = converter.convert()    
tflite_model_path="converted_.tflite"
with open(tflite_model_path,"wb") as f:
    f.write(tflite_model)
#### Option A: Reference colab notebooks
```

### 3. Failure after conversion
f not isinstance(self._keras_model.call, _def_function.Function):
AttributeError: 'str' object has no attribute 'call'


### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by mihaimaruseac** [comment]
Please give the issue a title that is relevant. This helps with searching for similar issues

**Comment by selvakarna** [comment]
I Try to convert Tensorflow model [Frozen_Graph.pb & label.pbtxt ] Into TFLite Model light weight converting.

**Comment by sushreebarsa** [comment]
@selvakarna Could you use the model path as follows;
```
converter = tf.lite.TFLiteConverter.from_saved_model(model_path) 
```
Please ensure you're loading the TFLite model correctly using `tf.lite.Interpreter`.

Thank you!
