### ISSUE TITLE
Using Multiple CPU Threads in an op

### ISSUE THREAD

**Issue by sdrelton** [tensorflow/tensorflow#6361]
Hi all,

I'm interested in using multithreading within a CPU op to increase speed. More specifically, I have some linear algebra code which, for batched matrix multiplies, is much faster than MKL (and probably Eigen).
I should be able to get the corresponding GPU version working without much trouble.

Currently my code uses OpenMP and SIMD pragmas which, as I understand it, don't play nicely with tensorflow at the moment. I've been digging through the documentation all day but haven't found any examples of a CPU op with multithreading (that isn't just calling eigen) which I can use.

Could anyone please point me in the right direction here?

Cheers!

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
#22 #1747 

### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
-rw-r--r-- 1 root root   558720 Sep 15 00:02 /usr/local/cuda-8.0/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Sep 15 00:05 /usr/local/cuda-8.0/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Sep 15 00:05 /usr/local/cuda-8.0/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rw-r--r-- 1 root root   415432 Sep 15 00:02 /usr/local/cuda-8.0/lib64/libcudart.so.8.0.44
-rw-r--r-- 1 root root   775162 Sep 15 00:02 /usr/local/cuda-8.0/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13 Dec 15 12:42 /usr/local/cuda-8.0/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root       17 Dec 15 12:42 /usr/local/cuda-8.0/lib64/libcudnn.so.5 -> libcudnn.so.5.1.5
-rwxr-xr-x 1 root root 79337624 Dec 15 12:42 /usr/local/cuda-8.0/lib64/libcudnn.so.5.1.5
-rw-r--r-- 1 root root 69756172 Dec 15 12:42 /usr/local/cuda-8.0/lib64/libcudnn_static.a

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
git rev-parse HEAD
dbe5e17e2ed307e86e1a6e79e558ec3e335d46fc

2. The output of `bazel version`
bazel version
Build label: 0.4.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 7 18:47:11 2016 (1481136431)
Build timestamp: 1481136431
Build timestamp as int: 1481136431

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
N/A

### What other attempted solutions have you tried?
N/A

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
N/A

**Comment by sjperkins** [comment]
@sdrelton You may find https://github.com/tensorflow/tensorflow/issues/5277 useful where a tensorflow has been implemented both with OpenMP and Eigen's ThreadPool implementation. The Eigen documentation is available [here](https://bitbucket.org/eigen/eigen/src/f5cf4207b67ee7ac304c1300873ae7ef93537956/unsupported/Eigen/CXX11/src/Tensor/README.md).

**Comment by sdrelton** [comment]
@sjperkins Thanks very much, I'll take a good look!

**Comment by andydavis1** [comment]
Please re-post on stackoverflow if this question is not resolved.
