### ISSUE TITLE
How to solve this issue - ImportError: cannot import name 'estimator' from 'tensorflow.compat.v1' (/root/.local/lib/python3.10/site-packages/tensorflow/_api/v2/compat/v1/__init__.py)

### ISSUE THREAD

**Issue by Rajcr2** [tensorflow/tensorflow#63618]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15.0

### Custom code

Yes

### Current behavior?

How to solve this issue - ImportError: cannot import name 'estimator' from 'tensorflow.compat.v1' (/root/.local/lib/python3.10/site-packages/tensorflow/_api/v2/compat/v1/__init__.py)

anyone ?

### Standalone code to reproduce the issue

```shell
2024-03-13 14:13:23.953994: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-13 14:13:25.304466: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/content/drive/MyDrive/tf_CrimeDetection/workspace/CCTV_New/model_main_tf2.py", line 31, in <module>
    from object_detection import model_lib_v2
  File "/usr/local/lib/python3.10/dist-packages/object_detection/model_lib_v2.py", line 30, in <module>
    from object_detection import inputs
  File "/usr/local/lib/python3.10/dist-packages/object_detection/inputs.py", line 24, in <module>
    from tensorflow.compat.v1 import estimator as tf_estimator
ImportError: cannot import name 'estimator' from 'tensorflow.compat.v1' (/root/.local/lib/python3.10/site-packages/tensorflow/_api/v2/compat/v1/__init__.py)
```

**Comment by Rajcr2** [comment]
Tried reinstalling tensorflow-estimator but still results are same.

**Comment by tilakrayal** [comment]
@Rajcr2,
Could you please provide the standalone code to reproduce the issue which helps to debug the same. Thank you!

**Comment by amrabed** [comment]
Getting the same error when using TensorFlow ^2.15.0 and tensorflow-hub ^0.15.0 on a Mlflow Docker container with Python 3.10
```bash
    from tensorflow_hub import load
  File "/usr/local/lib/python3.10/site-packages/tensorflow_hub/__init__.py", line 90, in <module>
    from tensorflow_hub.estimator import LatestModuleExporter
  File "/usr/local/lib/python3.10/site-packages/tensorflow_hub/estimator.py", line 21, in <module>
    from tensorflow.compat.v1 import estimator as tf_estimator
ImportError: cannot import name 'estimator' from 'tensorflow.compat.v1' (/usr/local/lib/python3.10/site-packages/tensorflow/_api/v2/compat/v1/__init__.py)
```

**Comment by tilakrayal** [comment]
@amrabed,
Could you please try to create the new issue from [here](https://github.com/tensorflow/tensorflow/issues/new/choose) providing the complete standalone code which helps to debug the issue. 
Thank you!

**Comment by amrabed** [comment]
For my case, it was incompatible versions of TF and TF-hub. TF got upgraded to `2.16.1`, while TF-hub stayed at `0.15.0`. I fixed the issue by pinning my TF version to `2.16.1` and TF-hub version to `0.16.1`

Here is the code I used for your reference:
```python
from tensorflow_hub import load  # this line caused the error before
encode = load("https://tfhub.dev/google/universal-sentence-encoder/4")
encode(["whatever"])
```
I hope that helps you or the OP

**Comment by karanpreet-5ingh** [comment]
This solution worked for me!

Recently, Google Colab updated its TensorFlow version from 2.15.0 to 2.16.1. Try reinstalling TensorFlow using the following commands:

`!pip uninstall tensorflow --y
!pip install tensorflow==2.15.0`

then restart runtime when asked in colab. You should be able to import the correct version of TensorFlow.

**Comment by tilakrayal** [comment]
@amrabed
For the tensorflow v2.15, you can directly run the command from tensorflow_hub import load for the tf-hub. But whereas for the latest stable tensorflow v2.16.1, please try to run **pip install tensorflow-hub** for the tensorflow-hub 0.16.1. 
I tried to execute and was able to import. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/923b68ffec7b9bf23d8c347a9aaa4d6c/untitled1767.ipynb).

Also there is an open issue in the tensorflow/tf-hub repo for the same issue. https://github.com/tensorflow/hub/issues/901

Thank you!

**Comment by AvijitChowdhury** [comment]
I fixed the issue by changing my TF version to 2.16.1 and TF-hub version to 0.16.1

**Comment by Foncu1980** [comment]
Hello!
I've been through the conversation. It is not working me, having those versions:
$ pip show tensorflow
Name: tensorflow
Version: 2.16.1
$ pip show tensorflow_hub
Name: tensorflow-hub
Version: 0.16.1

Any idea?
ImportError: cannot import name 'estimator' from 'tensorflow' (/home/homer/.local/lib/python3.10/site-packages/tensorflow/__init__.py)

**Comment by heflavie** [comment]
I have exactly the same issue as @Foncu1980 
$ pip show tensorflow
Name: tensorflow
Version: 2.16.1
$ pip show tensorflow_hub
Name: tensorflow-hub
Version: 0.16.1


ImportError: cannot import name 'estimator' from 'tensorflow.compat.v1'

**Comment by shramadeepd** [comment]
any updates on how to fix this ? this have been creating a problem for me , i am not able to use neural_structured_learning due to this , does anyone know , what are the other alternatives
