### ISSUE TITLE
User Contributed Tutorials

### ISSUE THREAD

**Issue by pichonz** [tensorflow/tensorflow#6363]
It would be great if there was a section in the tensorflow.org website where the community could provide tutorials for new users. There are a lot of great tutorials in the web and having some on the tensorflow.org website would be very valuable for people just starting out. Thoughts?

Here is an example of what I would love to share:
https://bitbucket.org/hrojas/learn-tensorflow

**Comment by aselle** [comment]
@wolffg and @martinwicke, is there a good place on devsite for adding these?

**Comment by martinwicke** [comment]
Please add them to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/resources/index.md

This is less prominent than we'd like at the moment, but whatever new place will be seeded with information from there.
