### ISSUE TITLE
multiple tflite delegate support?

### ISSUE THREAD

**Issue by tensorbuffer** [tensorflow/tensorflow#63669]
### Issue type

Feature Request

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf2.13

### Custom code

No

### Current behavior?

Currently if you use C API, you can invoke various delegates like: TfLiteHexagonDelegateCreate() for Hexagon, TfLiteGpuDelegateV2Create() for GPU, TfLiteXNNPackDelegateOptionsDefault() for CPU.
Note you can only use one at a time. For example, if you have model that has an OP not supported by Hexagon, that OP will be run on CPU, without using XNNPack.
However this is not the case with benchmark_model, where it applies XNNPack delegate as default, e.g. you can get both hexagon and xnnpack in one run.

### Standalone code to reproduce the issue

```shell
I would like to see the C API incorporates benchmark_model code, or provide similar API (like create all delegates and pass down to a new API TfLiteDelegateCreate(<delegate>)
```

**Comment by LakshmiKalaKadali** [comment]
Hi @tensorbuffer ,

Could please provide any use case/notebook  for this specific requirement so that the team can carry out additional analysis. 

Thank You

**Comment by tensorbuffer** [comment]
Hi, the use case is that we have a tf2 model, after convert to tflite, there's a quantize op at the begining and dequant op at the end. These two nodes can't be run on DSP if use API call, and they are not easily put on XNNPACK, while benchmark_model doesn't have this problem, it can auto assign XNNPACK delegate for those CPU operation.

**Comment by LakshmiKalaKadali** [comment]
Hi @pkgoogle, 

Please take a look at this feature request.

Thank You

**Comment by tensorbuffer** [comment]
Yes I want the C API to be able to handle that. Basically it should have the same behavior as benchmark_model, since we use that to benchmark latency during model development, afterwards in production we use C API to run the model. Currently benchmark_model can do hexagon and XNNPack delegates (xnnpack for those that hexagon not supported), but this is not the case for C API call, which results in latency increase in production.
I don't have example code, you can extend the current API as you wish.

**Comment by pkgoogle** [comment]
Hi @sirakiin, can you please take a look?

**Comment by gaikwadrahul8** [comment]
Hi, @tensorbuffer 
Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: [[Link to new issue]](https://github.com/google-ai-edge/LiteRT/issues/74)

Let us know if you have any questions. Thanks.
