### ISSUE TITLE
tf.audio.decode_wav: Aborted (core dumped)

### ISSUE THREAD

**Issue by vraebfdsb** [tensorflow/tensorflow#63687]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Python version

3.9

### Current behavior?

Under specific input, `tf.audio.decode_wav` encounters "Aborted (core dumped)".

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
import io

sample_rate = 44100
num_channels = 2
duration_seconds = 5
num_samples = sample_rate * duration_seconds
input_data = np.random.randint(-32768, 32767, size=(num_samples, num_channels)).astype(np.int16)

wav_io = io.BytesIO()
wav_write = tf.audio.encode_wav(input_data, sample_rate)
wav_io.write(wav_write.numpy())
wav_contents = wav_io.getvalue()

desired_channels = -num_channels - 1  
decoded_audio = tf.audio.decode_wav(wav_contents, desired_channels=desired_channels)
```

### Relevant log output

```shell
2024-03-14 05:35:10.682129: F tensorflow/core/framework/tensor_shape.cc:201] Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Expected a non-negative size, got -3
Aborted (core dumped)
```

**Comment by tilakrayal** [comment]
@nonenone12135,
As mentioned above, the tf.audio.decode_wav is not working for the specific input(most cases when desired_channels is -ve value), with the +ve input it is working without any issue. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/c58f8f57299ad1c4399be0c3615509fa/untitled1764.ipynb). Please allow some time to deep dive into the issue and provide the resolution. Thank you!

**Comment by tilakrayal** [comment]
@vraebfdsb,

When we try to execute the mentioned with num_channels = 2 and the desired_channels will become -3 which is causing the below error.

```python
 INVALID_ARGUMENT: Expected a non-negative size, got -3
```
https://www.tensorflow.org/api_docs/python/tf/audio/decode_wav#args
desired_channels	-- An optional int. Defaults to -1. Number of sample channels wanted.

Thank you!
