### ISSUE TITLE
error: conv3d_transpose layer

### ISSUE THREAD

**Issue by xcyan** [tensorflow/tensorflow#6369]
The conv3d_transpose seems buggy

>>> import tensorflow as tf

>>> deconv3d = tf.nn.conv3d_transpose(tf.zeros((10,3,3,3,10), dtype=tf.float32), tf.zeros((4,4,4,8,10), dtype=tf.float32), output_shape=[10,6,6,6,8], strides=[1, 1, 1, 1, 1])

>>> deconv2d = tf.nn.conv2d_transpose(tf.zeros((10,3,3,10), dtype=tf.float32), tf.zeros((4,4,8,10), dtype=tf.float32), output_shape=[10,6,6,8], strides=[1, 1, 1, 1])

>>> deconv3d
<tf.Tensor 'conv3d_transpose:0' shape=(?, ?, ?, ?, ?) dtype=float32>

>>> deconv2d
<tf.Tensor 'conv2d_transpose:0' shape=(10, 6, 6, 8) dtype=float32>

**Comment by matheusgadelha** [comment]
Why this issue was closed? I have the exact same problem.

**Comment by xcyan** [comment]
You can resolve this issue by updating your tf to 0.12+
