### ISSUE TITLE
Library not loaded: @rpath/libcudart.8.0.dylib but I have libcudart.7.5.dylib

### ISSUE THREAD

**Issue by mattdns100689** [tensorflow/tensorflow#6370]
I have the following error when importing tensor flow (GPU OSX version);

```
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found
```

It looks to me like it is looking for `@rpath/libcudart.8.0.dylib` but in my `/usr/local/cuda/lib` I have `libcudart.7.5.dylib` and no 8.0. How do I redirect it?

**Comment by shiyemin** [comment]
You should install from source code. The default CUDA of binary package is 8.0 and CUDNN 5.1.

**Comment by yaroslavvb** [comment]
Version 0.11 and comes compiled for 7.5

**Comment by shiyemin** [comment]
According to https://github.com/tensorflow/tensorflow/blob/r0.11/tensorflow/g3doc/get_started/os_setup.md, r0.11 also need CUDA 8.0 and CUDNN v5.

**Comment by yaroslavvb** [comment]
Sorry, I meant version 10.
CUDA filename is baked into the final executable, in order to change the
CUDA version you have to recompile

**Comment by gunan** [comment]
You may also update CUDA and CuDNN, (if you are the administrator of the device) to use the later versions of tensorflow.

Closing this issue as @yaroslavvb has identified and explained the problem.

**Comment by mattdns100689** [comment]
Thanks
