### ISSUE TITLE
Aborted can be triggered in  tf.raw_ops.TensorListConcat

### ISSUE THREAD

**Issue by vwrewsge** [tensorflow/tensorflow#63722]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Python version

3.9

### Current behavior?

The following code sometimes runs normally when calling `tf.raw_ops.TensorListConcat`, but sometimes encounters an "aborted" error.

To reproduce the issue, it may be necessary to execute several times.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

input_data_1 = tf.constant([[1, 2, 3], [4, 5, 6]])
input_data_2 = tf.constant([[7, 8, 9], [10, 11, 12]])

input_handle = tf.raw_ops.TensorListReserve(element_dtype=tf.int32, element_shape=[2, 3], num_elements=2)
input_handle = tf.raw_ops.TensorListSetItem(input_handle=input_handle, index=0, item=input_data_1)
input_handle = tf.raw_ops.TensorListSetItem(input_handle=input_handle, index=1, item=input_data_2)

concatenated_data, lengths = tf.raw_ops.TensorListConcat(input_handle=input_handle, element_dtype=tf.int32, element_shape=[6])

print(concatenated_data)
```

### Relevant log output

```shell
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
malloc_consolidate(): invalid chunk size
Aborted (core dumped)
```

**Comment by Venkat6871** [comment]
Hi **@vwrewsge** ,

I tried to run your code on colab using tf 2.15, 2.16 and tf-nightly versions faced same issue. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/895584f0f6c534a30189918240c83056/63722_2-15-2-16-nightly.ipynb) here for reference. We need to work on it, In few days i will provide a solution for it.

Thank you!

**Comment by Venkat6871** [comment]
Hi **@vwrewsge** ,
- Apologies for the delay,  I think this was resolved in recent tf-nightly. Please check the [gist](https://colab.research.google.com/gist/Venkat6871/d713cd915596ee20054b871f8d234589/63722_tf-nightly-v.ipynb) here. It will resolve in upcoming version.

Thank you!
