### ISSUE TITLE
Inconsistency in parameter naming

### ISSUE THREAD

**Issue by nmiculinic** [tensorflow/tensorflow#6379]
```
tf.nn.conv1d(value, filters, stride, padding, use_cudnn_on_gpu=None, data_format=None, name=None)
tf.nn.conv2d(input, filter, strides, padding, use_cudnn_on_gpu=None, data_format=None, name=None)
tf.nn.conv3d(input, filter, strides, padding, name=None)
```

There's discrepancy between parameter naming between conv1d and 2,3d counterparts. Firstly value vs input, and then singular vs plural filter(s) (singular would be correct as in 2d/3s case since function accepts only single filter if I understood documentation correctly.)

**Comment by vrv** [comment]
Thanks for pointing out the inconsistency.  To fix it, we'll probably have to support both for a while but at least make the correct ones documented.

There's a generic 'convolution' parameter here that is more agnostic about the dimensionality, for what it's worth: https://github.com/tensorflow/tensorflow/blob/a276e0999ab4223ac36d75221028d3e8835c60ae/tensorflow/python/ops/nn_ops.py#L472

**Comment by wt-huang** [comment]
Closing as it is resolved
