### ISSUE TITLE
Comment in detection_postprocess.cc is incorrect and misleading.

### ISSUE THREAD

**Issue by xwin** [tensorflow/tensorflow#63815]
The comment pointed by the link below is incorrect
https://github.com/tensorflow/tensorflow/blob/82b21d203296ce5640631aba39c8fb64c02508fa/tensorflow/lite/kernels/detection_postprocess.cc#L58
The comment should state
```
// BoxCorner represents the upper left corner (xmin, ymin) and
// the lower right corner (xmax, ymax).
```
While this is not a functional bug it can case some wasted time and is easy to fix
For the reference this link https://www.tensorflow.org/lite/examples/object_detection/overview#output_signature in tensorflow documentation has a correct description.

**Comment by LakshmiKalaKadali** [comment]
Hi @xwin,

Please track the PR [#63950](https://github.com/tensorflow/tensorflow/pull/63950)

Thank You
