### ISSUE TITLE
contrib\cmake: how properly depend on generated tensorflow .lib

### ISSUE THREAD

**Issue by derofim** [tensorflow/tensorflow#6382]
Used contrib\cmake ( https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake ) on Windows 10 64bit and VS 2015 64bit to build tensorflow  for C++.

Opened generated tf_tutorials_example_trainer.vcxproj  in VS Release x64 - runs VERY GOOD, but rebuilds whole tensorflow every time i hit play! Tried Build->Configuration Manager->Uncheck projects that i don't want to always build - errors (what projects i need to keep checked to build only tf_tutorials_example_trainer.vcxproj?).

How to depend on tensorflow statically (or at least prevent long build)?

Failed attempts: 
```
Created new VS console project Release x64 (to prevent full rebuilds). 
Used step-by-step build https://gist.github.com/derofim/b4f150da1269b81af8d12744df730708
Added tensorflow include dirs.
Added .lib files:
Release\tf_protos_cc.lib
protobuf\src\protobuf\Release\libprotobuf.lib
Used same flags as in example project.

Error: No session factory registered for the given session options

Tried solutions:
/WHOLEARCHIVE as in https://msdn.microsoft.com/en-us/library/mt732963.aspx - LNK1000: Internal error during IncrBuildImage
/OPT:NOREF - no effect
/FORCE:MULTIPLE  - no effect
 /INCLUDE - what to place here for force inclusion of unused symbols? May it help?
```

**Comment by gunan** [comment]
@vit-stepanovs I feel like your answer at #6396 might be also applicable here?

**Comment by vit-stepanovs** [comment]
Yes, it looks like the same issue.

**Comment by gunan** [comment]
Then closing this issue.

later this month, we will move all windows support onto bazel.
I think it will look slightly different, and we will be able to use bazel's incremental build then.

Until bazel arrives, I suggest tring suggestions at #6396.
Closing this issue.
