### ISSUE TITLE
Cannot build Android example on Windows using Bazel

### ISSUE THREAD

**Issue by AndreyRub** [tensorflow/tensorflow#6383]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/tensorflow/tensorflow/issues/6101
http://stackoverflow.com/questions/40978859/creating-simple-android-app-using-android-studio-and-tensorflow

### Environment info
Operating System: Windows

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
Cuda 8.0
cuDNN 5.0

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`)
I downloaded the latest ZIP on 18 Dec 2016. Sorry, I have no idea how to get the version.

2. The output of `bazel version`
Build label: 0.4.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 7 18:47:13 2016 (1481136433)
Build timestamp: 1481136433
Build timestamp as int: 1481136433

I am trying to build an Android example using Bazel on Windows. 
I've successfully installed Bazel using Chocolatey.
Following the build instructions, I need to change the SDK and NDK paths in WORKSPACE file and run:

**bazel build //tensorflow/examples/android:tensorflow_demo**

I am having trouble with configuring the WORKSPACE file. I need to uncomment the Android lines and add the paths.  However, no matter what I try, I get an error.

I've tried:
**
1. path = "C:/Users/Andrey/AppData/Local/Android/sdk"
2. path = "/C/Users/Andrey/AppData/Local/Android/sdk"
3. path = "C:\Users\Andrey\AppData\Local\Android\sdk"
4. path = "C:\\Users\\Andrey\\AppData\\Local\\Android\\sdk"**

For 1,2,4 I am getting:

ERROR: C:/Tools/tensorflow-master/WORKSPACE:3:1: indentation error.
ERROR: error loading package 'external': Failed to parse WORKSPACE file.
INFO: Elapsed time: 0.317s

For 3 I am getting:
ERROR: C:/Tools/tensorflow-master/WORKSPACE:9:12: escape sequence not implemented: \U.
ERROR: C:/Tools/tensorflow-master/WORKSPACE:14:10: escape sequence not implemented: \U.
ERROR: C:/Tools/tensorflow-master/WORKSPACE:3:1: indentation error.
ERROR: error loading package 'external': Failed to parse WORKSPACE file.
INFO: Elapsed time: 0.309s

There is a hint that it is related to indentation, but I could not find anything problematic.
I am attaching an example file for (1)
[WORKSPACE_1.txt](https://github.com/tensorflow/tensorflow/files/659363/WORKSPACE_1.txt)
_(Note: I change the extension to .txt since I could not upload the original file.)_

Any idea?

**Comment by AndreyRub** [comment]
Sorry, my mistake. I accidentally uncommented a line I should not have

**Comment by AbhisheKundalia** [comment]
Hey can you please share the version which worked for you? as I am getting the same error

**Comment by elizacamber** [comment]
[Better late than never] If the path for the SDK/NDK versions is added in the form of `C:\Users\[username]\AppData\Local\Android/sdk` you need to change the backslashes (\) to normal slashes (/)

**Comment by MingJiang1988** [comment]
replace  "\\" C:\\appData\\Local\\

**Comment by MingJiang1988** [comment]
'\\\\'
