### ISSUE TITLE
TensorFlow 2.16 API docs not available online

### ISSUE THREAD

**Issue by jonas-eschle** [tensorflow/tensorflow#63834]
### Issue type

Documentation Bug

### TensorFlow version

2.16

The website displaying the 2.16 API of TensorFlow is not available, see [https://www.tensorflow.org/api/r2.16](https://www.tensorflow.org/api/r2.16)
Only the 2.15 appears if clicking through

**Comment by tilakrayal** [comment]
@jonas-eschle,
There is a change request for this issue and we are tracking it internally. Once it is resolved, the documentation will be updated to v2.16 and will update the same. Thank you!

**Comment by jonas-eschle** [comment]
Thanks a lot for taking care of it!

**Comment by tilakrayal** [comment]
@jonas-eschle,
If you feel the issue is addressed, Could you please feel free to move this issue to closed status. Thank you!

**Comment by jonas-eschle** [comment]
I will check, but at this moment in time, the docs don't show up yet

**Comment by tilakrayal** [comment]
@jonas-eschle,
Yeah. As mentioned the issue was informed to the respective team and will update the docs in upcoming days. Thank you!

**Comment by Cpicon** [comment]
Hi, we are also interested in the docs for v2.16 API. I am commenting to keep this issue open.

**Comment by tilakrayal** [comment]
@jonas-eschle, @Cpicon,
When I checked the official document, I could able to check the 2.16 api docs now. https://www.tensorflow.org/api_docs/python/tf

Could you please check and confirm the same. Screenshot for the reference.
![image](https://github.com/tensorflow/tensorflow/assets/81610181/a001a7e5-b35b-4ba9-99ca-b6869026a0eb)

**Comment by jonas-eschle** [comment]
I confirm that the docs are visible now, thanks for the fix! closing
