### ISSUE TITLE
TF 2.16.1 and Apple Silicon GPU support not working. 

### ISSUE THREAD

**Issue by msusol** [tensorflow/tensorflow#63854]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

v2.16.1-0-g5bc9d26649c 2.16.1

### Custom code

Yes

### OS platform and distribution

Mac OS 14.3.1 Apple M3 Pro

### Python version

3.11

### Current behavior?

I can not get the [basic example](https://developer.apple.com/metal/tensorflow-plugin/) showing use of GPU to work on MacOS w/ TF 2.16.1.

However, It performs as expected in TF2.15.0

### Standalone code to reproduce the issue

I have prepared 2 notebooks to show the behavior clearly, each using their own virtual environments.

1. GPU working [TensorFlow215.ipynb](https://github.com/msusol/jupyter-notebook-on-macos/blob/main/notebooks/TensorFlow215.ipynb)
2. Unexpected [TensorFlow216.ipynb](https://github.com/msusol/jupyter-notebook-on-macos/blob/main/notebooks/TensorFlow216.ipynb)

**Comment by asesh** [comment]
You will have to install `tensorlfow-metal` to add support for GPU on Apple silicons. [More info](https://developer.apple.com/metal/tensorflow-plugin/)

**Comment by msusol** [comment]
I did. Please look at the notebooks where I show exactly what was installed.

**Comment by SuryanarayanaY** [comment]
Hi @msusol ,

As a temporary fix you can use Keras2 backend. Since TF2.16 defaults to Keras3 backend it uses Keras3 by default with tf.keras. You can switch to Keras2 backend by installing `tf_keras` package and setting `os.environ['TF_USE_LEGACY_KERAS'] = '1'`. Meanwhile team will look into the issue with Keras3 vs Mac compatibility.

**Comment by msusol** [comment]
> Hi @msusol ,
> 
> As a temporary fix you can use Keras2 backend. Since TF2.16 defaults to Keras3 backend it uses Keras3 by default with tf.keras. You can switch to Keras2 backend by installing `tf_keras` package and setting `os.environ['TF_USE_LEGACY_KERAS'] = '1'`. Meanwhile team will look into the issue with Keras3 vs Mac compatibility.

Verified that this change does restore GPU access to the kernel:
https://github.com/msusol/jupyter-notebook-on-macos/commit/7688a9fd2494807e5bb161c4f721ac82bada5c80

Waiting for the resolution to remove the legacy flag.
