### ISSUE TITLE
Dense CRF implemenation

### ISSUE THREAD

**Issue by Seleucia** [tensorflow/tensorflow#6386]
Is there an easy way to implement or use the dense CRF within tensorflow.  More spesifically i would love to train my network with dens CRF. You can see more information about dense CRF from this paper.[DenseCRF poster ](http://vladlen.info/papers/densecrf-poster.pdf). You can see C++ implementation form here: [Dense CRF C++](https://github.com/lucasb-eyer/pydensecrf/tree/d824b89ee3867bca3e90b9f04c448f1b41821524/pydensecrf/densecrf/src). Is there a way to include this in tensorflow and built with it?

**Comment by aselle** [comment]
This question is more appropriate for StackOverflow. Please re-ask there. Thank you!
