### ISSUE TITLE
[TensorFlow.org] Anchor Tag Incorrect Reference

### ISSUE THREAD

**Issue by Carmezim** [tensorflow/tensorflow#6389]
Nothing really serious but I noticed the link on `see Pip installation for Windows` on getting started doc body is using an anchor separated with dashes `#pip-installation-on-windows`  while the corresponding `id` uses underscores `#pip_installation_on_windows`.

For instance, the body anchor (which works on github) 
`#pip-installation-on-windows` 
and the right side nav-bar `Index` link, working normally, with underscores
`#pip_installation_on_windows`

I was going to submit a PR but changing to the latter breaks on github.

**Comment by wolffg** [comment]
That should be picked up by our formatting tool.  I'll take a look.

**Comment by Carmezim** [comment]
It's a matter of modifying the anchor reference to follow github's format.

**Comment by wolffg** [comment]
This is now fixed.  Thanks for pointing it out.

**Comment by Carmezim** [comment]
@wolffg Awesome. No problem!
