### ISSUE TITLE
Extract attention matrix during decoding

### ISSUE THREAD

**Issue by suryabhupa** [tensorflow/tensorflow#6390]
It seems like it's not possible to access the attention weights during decoding since the attention() method in seq2seq_model isn't called during the forward step. Otherwise, is there another feature to allow for this, or was this intended?

**Comment by aselle** [comment]
You might try asking this question on StackOverflow. Others users may have found a way to do it there. If you cannot find a way to do it after asking there, please reply here, and we will open it as a feature request. Thanks!
