### ISSUE TITLE
tensorflow.python.framework.errors_impl.PermissionDeniedError: data

### ISSUE THREAD

**Issue by soliders** [tensorflow/tensorflow#6393]
hi,when am run a TensorFlow demo model as this
https://www.tensorflow.org/get_started/os_setup#test_the_tensorflow_installation
i have the problem descripte as follows:

$ python /usr/local/lib/python2.7/dist-packages/tensorflow/models/imag
e/mnist/convolutional.py
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 339, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 130, in main
    train_data_filename = maybe_download('train-images-idx3-ubyte.gz')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/models/image/mnist/convolutional.py", line 65, in maybe_download
    tf.gfile.MakeDirs(WORK_DIRECTORY)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 299, in recursive_create_dir
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(dirname), status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.PermissionDeniedError: data

how can i fix it?

the tensorflow install environment as follows:
ubuntu 16.04
python 2.7
numpy 1.11.2
six 1.10.0
protobuf 3.1.0

i installed tensorflow as follows:
    sudo -H pip install tensorflow

**Comment by Frankie08** [comment]
You may not have permissions to write/read in your working directory. This is nothing about tensorflow.

**Comment by soliders** [comment]
thanks a lot. i had already find the reason.

**Comment by feiyue1230** [comment]
@soliders  Hello, I have the same problem with you. So I try to fix it by ' chmod -R 777 /usr/local/lib/python2.7/dist-packages/tensorflow'. But this treatment is invalid. Can you share your approach?

**Comment by RunshengSong** [comment]
@feiyue1230 did you install tensorflow in conda environment? if so you need to run: python /home/runsheng/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/models/image/mnist.

At least this was my case.

**Comment by metropt** [comment]
How did you solved that? run it as sudo doesnt looks the best option...

**Comment by sajjo79** [comment]
I got the same error. The directory where i wanted to write a file is located in same directory where my code is present however i wrote path as "/log_dir". I changed this to "log_dir/" and it worked. I think when I write "/log_dir", linux tried to look at root where no such directory was found and there was no permission by system to write.

**Comment by chouqin3** [comment]
np.savez_compressed(code_file, shape=int_codes.shape, codes=export) is changed to  np.savez_compressed('a', shape=int_codes.shape, codes=export)
then, it works.

**Comment by Mart1nch** [comment]
> I got the same error. The directory where i wanted to write a file is located in same directory where my code is present however i wrote path as "/log_dir". I changed this to "log_dir/" and it worked. I think when I write "/log_dir", linux tried to look at root where no such directory was found and there was no permission by system to write.

me 2

**Comment by SkullFang** [comment]
This is a permission issue. Change the output file path strength. For example, my output path is 'output', and the run parameter needs to be written as "output/" instead of "/output/"
I will share my .sh file for your reference.
export BERT_BASE_DIR=/home/I348655/Document/Project/transfer_learn/bert/bert/uncased_L-12_H-768_A-12
export GLUE_DIR=/home/I348655/Document/Project/transfer_learn/bert/bert/glue

python run_classifier.py \
  --task_name=MRPC \
  --do_train=true \
  --do_eval=true \
  --data_dir=$GLUE_DIR/MRPC \
  --vocab_file=$BERT_BASE_DIR/vocab.txt \
  --bert_config_file=$BERT_BASE_DIR/bert_config.json \
  --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt \
  --max_seq_length=128 \
  --train_batch_size=32 \
  --learning_rate=2e-5 \
  --num_train_epochs=3.0 \
  **--output_dir=mrpc_output/**

（Please pay attention to my bold position）

**Comment by BasitJaved** [comment]
Guys I solved this problem using
python3 generate_tf_record.py --csv_input=data/train_labels.csv  --output_path=train.record
python3 generate_tf_record.py --csv_input=data/test_labels.csv  --output_path=test.record

all the images were in one folder i.e images and flags were as below


flags.DEFINE_string('csv_input', '','data/train_labels.csv')
flags.DEFINE_string('output_path','', 'train.record')
flags.DEFINE_string('image_dir', '', 'images')

**Comment by BasitJaved** [comment]
I saved record file in main folder rather then in data,,,,later copied it in data folder

**Comment by KellyHwong** [comment]
I bet we shoud use os.makedirs(WORK_DIRECTORY, exist_ok=True) instead of tf.gfile.MakeDirs(WORK_DIRECTORY)
