### ISSUE TITLE
Tensorflow GPU Support for Windows?

### ISSUE THREAD

**Issue by zAMLz** [tensorflow/tensorflow#6394]
Hi I installed tensorflow-GPU through pip on my Windows 10 machine and I have also installed the Nvidia Cuda Toolkit and have downloaded cuDNN. But I came to the realization that there was no GPU version for Windows 10. Is it still possible to use the tensorflow-GPU windows 10 given that it is install-able via pip and all the other dependencies can be installed and configued?

**Comment by gunan** [comment]
What do you mean there was no GPU version for windows?
if you run the following command, you should get the GPU(Nvidia Cuda) version of tensorflow installed.
```
pip install tensorflow-gpu
```
We do have tensorflow GPU version available for windows 10, which also should be compatible with older versions of windows to some extent.

It is correct that you have to install CUDA and CuDNN yourself, as they are separate pieces of software which need to be distributed separately.

**Comment by zAMLz** [comment]
I was confused since the build passing icon was only on windows-cpu. If that is the case than that is great. But I am also having trouble installing CuDNN. Where would I install it on a windows machine?

**Comment by gunan** [comment]
We try to keep the build passing icons to a minimum.
But any released package means all builds/tests have passed for that package.

For CuDNN, you have to go through https://developer.nvidia.com/cudnn

CLosing this issue as it seems to be resolved on TF side.

**Comment by sameertikoo** [comment]
Having this issue now..
PS C:\Users\> pip install tensorflow-gpu
Collecting tensorflow-gpu
 Could not find a version that satisfies the requirement tensorflow-gpu (from versions: )
No matching distribution found for tensorflow-gpu

**Comment by gunan** [comment]
TF at the moment only has prebuilt windows pip packages for python 3.5.
Any other python version, you will see this error.
