### ISSUE TITLE
Cmake static library build issue

### ISSUE THREAD

**Issue by shakith** [tensorflow/tensorflow#6396]
Hi all,

I have successfully build tensorflow in windows/visual studio using the [cmake project](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake). 

Now due to large build time of tensorflow, I am building the tensorflow as libraries (static library) and trying to use them in an application (tf_label_image_example). However, I get the following runtime error at the points of calling env constructor in the SessionOptions at the following source code:
`session->reset(tensorflow::NewSession(tensorflow::SessionOptions()));.`
Error is: `No session factory registered for the given session options: {target: "" config: } Registered factories are {}.`

It is similar to [this error](https://github.com/tensorflow/tensorflow/issues/3308) in makefiles and MAC os where the compiler is stripping the multiple defined symbols. I tried to add visual studio equivalent of this compiler options (/FORCE:MULTIPLE and /WHOLEARCHIVE) to build of tf_core_lib.lib . however, the compiler options are not applicable to static libraries. Alternative option to is make a DLL, however, that would require modification of all functions with __declspec(dllexport).
Is there a better solution?

The tf_label_image_example application contains main.cc and the following additional lib dependencies:
tf_core_cpu.lib
tf_core_framework.lib
tf_core_kernels.lib
tf_cc_framework.lib
tf_cc_ops.lib
tf_core_ops.lib
tf_stream_executor.lib
tf_core_direct_session.lib
tf_core_lib.lib
 
Thanks in advance.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/tensorflow/tensorflow/issues/3308

### Environment info
Operating System: Win 10

Installed version of CUDA and cuDNN:  Cuda 8
The same configuration [here ](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake#known-good-configurations)is used.

**Comment by vit-stepanovs** [comment]
@shakith This is caused by MSVC throwing out object files in static libraries during link time if no symbols from them are referenced from anywhere else (which is in most cases a desirable behavior). Many TF objects (ops, kernels, sessions) are not used directly by other code, but through accessing them via global 'registry' collections, hence this behavior.

You have two options - either link the object files directly into executables/dlls (without putting them in static libraries), or (starting with VS 2015 Update 2) use [/WHOLEARCHIVE](https://msdn.microsoft.com/en-us/library/mt732963.aspx?f=255&MSPPError=-2147217396) option to force the linker to include all objects from your static library.

**Comment by andydavis1** [comment]
please re-open if the above answer does not resolve your issue.

**Comment by derofim** [comment]
I have similar problem. 

In generated with cmake .sln file tf_tutorials_example_trainer.vcxproj tensorflow works fine, but linking tensorflow in existing project (same code as in tf_tutorials_example_trainer) gives error "No session factory registered for the given session options".

When i use /WHOLEARCHIV and tensorflow .lib files in existing project (console release x64) - Error:
/WHOLEARCHIVE = Error LNK1000: Internal error during IncrBuildImage

Details of problem: https://github.com/tensorflow/tensorflow/issues/6382

Maybe some separate Cmake / Visual Studio example projects linking tensorflow .lib files exist (to stop rebuilding tensorflow each time)?

**Comment by derofim** [comment]
Got another strange error trying to link fresh custom Release x64 console project like tf_label_image_example (same code) when added /WHOLEARCHIVE:

Ошибка	LNK1000	Internal error during CImplib::EmitThunk

C/C++ settins:

`/MP /GS /TP /W3 /wd"4267" /wd"4244" /wd"4800" /wd"4503" /wd"4554" /wd"4996" /wd"4348" /wd"4018" /wd"4099" /wd"4146" /wd"4305" /wd"4307" /wd"4715" /wd"4722" /wd"4723" /wd"4838" /wd"4309" /wd"4334" /Gy- /Zc:wchar_t /I"D:\Tensorflow\tensorflow-master" /I"D:\Tensorflow\tensorflow-master\tensorflow\contrib\cmake\build" /I"D:\Tensorflow\tensorflow-master\tensorflow\contrib\cmake\build\external\zlib_archive" /I"D:\Tensorflow\tensorflow-master\tensorflow\contrib\cmake\build\external\gif_archive\giflib-5.1.4" /I"D:\Tensorflow\tensorflow-master\tensorflow\contrib\cmake\build\external\png_archive" /I"D:\Tensorflow\tensorflow-master\tensorflow\contrib\cmake\build\external\jpeg_archive" /I"D:\Tensorflow\tensorflow-master\tensorflow\contrib\cmake\build\external\eigen_archive" /I"D:\Tensorflow\tensorflow-master\third_party\eigen3" /I"D:\Tensorflow\tensorflow-master\tensorflow\contrib\cmake\build\gemmlowp\src\gemmlowp" /I"D:\Tensorflow\tensorflow-master\tensorflow\contrib\cmake\build\jsoncpp\src\jsoncpp" /I"D:\Tensorflow\tensorflow-master\tensorflow\contrib\cmake\build\external\farmhash_archive" /I"D:\Tensorflow\tensorflow-master\tensorflow\contrib\cmake\build\external\farmhash_archive\util" /I"D:\Tensorflow\tensorflow-master\tensorflow\contrib\cmake\build\external\highwayhash" /I"D:\Tensorflow\tensorflow-master\tensorflow\contrib\cmake\build\protobuf\src\protobuf\src" /I"D:\Tensorflow\tensorflow-master\tensorflow\contrib\cmake\build\grpc\src\grpc\include" /I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0" /I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\extras\CUPTI\include" /I"D:\Tensorflow\cudnn\cuda" /I"D:\Tensorflow\tensorflow-master\third_party\gpus" /I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include" /Gm- /O2 /Ob2 /Fd"x64\Release\vc140.pdb" /Zc:inline /fp:precise /D "WIN32" /D "_WINDOWS" /D "NDEBUG" /D "EIGEN_AVOID_STL_ARRAY" /D "NOMINMAX" /D "_WIN32_WINNT=0x0A00" /D "LANG_CXX11" /D "COMPILER_MSVC" /D "__VERSION__=\"MSVC\"" /D "OS_WIN" /D "_MBCS" /D "WIN64" /D "WIN32_LEAN_AND_MEAN" /D "NOGDI" /D "PLATFORM_WINDOWS" /D "TENSORFLOW_USE_EIGEN_THREADPOOL" /D "EIGEN_HAS_C99_MATH" /D "_ITERATOR_DEBUG_LEVEL=0" /D "GOOGLE_CUDA=1" /D "TF_EXTRA_CUDA_CAPABILITIES=3.0,3.5,5.2" /D "CMAKE_INTDIR=\"Release\"" /errorReport:prompt /GF /WX- /Zc:forScope /GR /Gd /MD /FC /Fa"x64\Release\" /EHsc /nologo /Fo"x64\Release\" /Fp"x64\Release\TF.pch" `
 /bigobj 

Linker settings:
`/OUT:"D:\CppTests\FuckMail\TF\x64\Release\TF.exe" /MANIFEST /NXCOMPAT /PDB:"D:\CppTests\FuckMail\TF\x64\Release\TF.pdb" /DYNAMICBASE "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.lib" "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib" "Release\tf_protos_cc.lib" "Release\tf_core_gpu_kernels.lib" "zlib\install\lib\zlibstatic.lib" "gif\install\lib\giflib.lib" "png\install\lib\libpng12_static.lib" "jpeg\install\lib\libjpeg.lib" "jsoncpp\src\jsoncpp\src\lib_json\Release\jsoncpp.lib" "farmhash\install\lib\farmhash.lib" "highwayhash\install\lib\highwayhash.lib" "protobuf\src\protobuf\Release\libprotobuf.lib" "grpc\src\grpc\Release\grpc++_unsecure.lib" "grpc\src\grpc\Release\grpc_unsecure.lib" "grpc\src\grpc\Release\gpr.lib" "wsock32.lib" "ws2_32.lib" "shlwapi.lib" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64\cudart_static.lib" "D:\Tensorflow\cudnn\cuda\lib\x64\cudnn.lib" "tf_cc_framework.dir/Release/tf_cc_framework.lib" "tf_cc_ops.dir/Release/tf_cc_ops.lib" "tf_core_cpu.dir/Release/tf_core_cpu.lib" "tf_core_direct_session.dir/Release/tf_core_direct_session.lib" "tf_core_framework.dir/Release/tf_core_framework.lib" "tf_core_kernels.dir/Release/tf_core_kernels.lib" "tf_core_lib.dir/Release/tf_core_lib.lib" "tf_core_ops.dir/Release/tf_core_ops.lib" /MACHINE:X64 /OPT:NOREF /INCREMENTAL:NO /PGD:"D:\CppTests\FuckMail\TF\x64\Release\TF.pgd" /SUBSYSTEM:CONSOLE /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /ManifestFile:"x64\Release\TF.exe.intermediate.manifest" /OPT:NOICF /ERRORREPORT:PROMPT /NOLOGO /LIBPATH:"D:\Tensorflow\tensorflow-master\tensorflow\contrib\cmake\build" /TLBID:1 `
 /WHOLEARCHIVE /machine:x64

**Comment by derofim** [comment]
Found similar tensorflow issue forum https://groups.google.com/forum/#!topic/bazel-discuss/tDGrTAtaxYw
 ( Internal error during CImplib::EmitThunk )

**Comment by derofim** [comment]
For now tf_label_image_example works fine in generated .sln!

To stop rebuilding whole tensorflow each time i used workaround 
"Configuration Manager". Un-check the "Build" for all except tf_label_image_example as in http://stackoverflow.com/a/1433680

Also in contrib\cmake\build i created folders tensorflow/examples/label_image/data/ and placed in it:
grace_hopper.jpg
imagenet_comp_graph_label_strings.txt
tensorflow_inception_graph.pb

Data may be found at https://storage.googleapis.com/download.tensorflow.org/models/inception_dec_2015.zip in tutorial https://www.tensorflow.org/how_tos/tool_developers/

**Comment by shakith** [comment]
@vit-stepanovs , Thanks for the info.

I have followed the adding all obj file solution and it works. However, it will be great to have lib version (with small amounts of libs). I added /WHOLEARCHIVE compiler option (on Visual Studi 2015 Update 3) to the tf_label_image_example application project with the lib dependencies. It gives the same error as for @derofim:

`LNK1000: Internal error during CImplib::EmitThunk`

To verify whether this is a configuration issue with my setup, has anyone managed to build static libraries and link them to an application through Visual Studio/CMake project. Or is it a Visual Studio issue with these specific libraries?

@andydavis1, could you open the issue till a static library solution can be found or if needed till a bug report can be reported for visual studio? Thanks.

**Comment by derofim** [comment]
@shakith Thanks for the detailed description of the problem. Can you please say how you added all obj files to solution? 

I saw list of .obj files needed to build tf_label_image_example in solution explorer and was amazed how big it is. Maybe some of them may be skipped (or added automatically)?

![image](https://cloud.githubusercontent.com/assets/9510143/21359502/84694102-c6ed-11e6-862b-03905aa74e98.png)

**Comment by Alien-47** [comment]
You can bypass the LNK1000 error by selectively applying /WHOLEARCHIVE option only to the necessary static libraries. I managed to get with this set as a starting point for my experiments:
`/WHOLEARCHIVE:tf_core_direct_session.lib /WHOLEARCHIVE:tf_core_ops.lib /WHOLEARCHIVE:tf_core_lib.lib /WHOLEARCHIVE:tf_cc_framework.lib /WHOLEARCHIVE:tf_core_framework.lib /WHOLEARCHIVE:tf_core_cpu.lib /WHOLEARCHIVE:tf_stream_executor.lib`

**Comment by sylvain-bougnoux** [comment]
I can compile successively adding manually all the *.obj of some libraries. But it is quite awkward because link is slow, and updating the library requires to check whether a new file is added... Therefore I've tried the /WHOLEARCHIVE trick. 

It works for all the libraries I was linking with (through *.obj) **but not for tf_core_gpu_kernels.lib**; a symbol (TensorCuBlasGemm<float>) keeps missing. This symbol comes from blas_gemm.cc (explicit template instantiation) either from _gru_ops or _lstm_ops libraries. But linking with any of this does not fix the missing symbol. Hence my question: which library should I link against (dumpbin does not tell it)?
