### ISSUE TITLE
Images missing in api_docs

### ISSUE THREAD

**Issue by feiskyer** [tensorflow/tensorflow#6400]
A few images are missing at https://www.tensorflow.org/api_docs/python/math_ops/segmentation, e.g. [SegmentSum.png](https://www.tensorflow.org/api_docs/images/SegmentSum.png) and [SegmentProd.png](https://www.tensorflow.org/api_docs/images/SegmentProd.png) are not found

**Comment by wolffg** [comment]
Thanks. We'll look into it.

**Comment by wolffg** [comment]
Images are back on that page and others where the same transcription error happened.
