### ISSUE TITLE
Numpy.FFT2() vs. TF.FFT2D() gives wrong values

### ISSUE THREAD

**Issue by beniroquai** [tensorflow/tensorflow#6401]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

None. 

### Environment info
Operating System:
Ubuntu 16.04 LTS

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
Toolkit-version 8.0

If installed from binary pip package, provide:
Installed it using pip install und Anaconda

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

```
# check if np.fft2d of TF.fft2d and NP have the same result

testimage = np.random.rand(256, 256)
testimage = testimage+0j

ft_testimage = np.fft.fft2(testimage)
np_result = np.sum(ft_testimage)
print(np_result)

tf_ft_testimage = tf.fft2d(testimage)
tf_result = np.sum(tf_ft_testimage.eval())
print(tf_result)

result_div = np.abs(tf_ft_testimage.eval())

plt.imshow(np.log(result_div))

print(np_result)
(56368.5840888+9.09494701773e-13j)

print(tf_result)
(56368.6+0.00390625j)

```
### Logs or other output that would be helpful

I was encountering this problem, when I did some numerical calculations using the FFT. I simply ported one algorithm from pure python to Tensorflow and the result were not the same. I think one of the reasons could be the wrong interpretation of the FFT2D used in Tensorflow? Do I need to normalize it somehow? Is the usage somehow different compared to Numpy? 

Thanks a lot!

**Comment by aselle** [comment]
To my eye, it just looks like the GPU version of fft is lower accuracy than the CPU (double precision) version that numpy uses.

**Comment by beniroquai** [comment]
Maybe the way I calculate the result is inappropriate. The dynamic range of the FFT is quiet big. So adding all the tiny and large values maybe results into this error on the GPU? 
I just ported a python code to Tensorflow and the numerical results are completely wrong. I'm still searching for the error and I was taking the numerical precision into account, but maybe it's also another problem. Thanks1

**Comment by aselle** [comment]
You might try computing the infinity norm of the concatenated vector (reshaped to 1d)... i.e. take the differences of the two results per element, and then you can take the maxabs over all the elements. That's a much better measure of if the results are similar and avoids numeric precision loss. Summing arbitrary magnitude numbers in arbitrary orders will not give you an accurate sum (you'd need to order from smallest to largest to get an accurate result of a large sum like that, but that could still miss errors, hence the max abs norm being best)

**Comment by beniroquai** [comment]
Thank you very much! I'll try once I'm back at the GPU-enabled Computer ;-)

**Comment by aselle** [comment]
Closing due to lack of recent activity. We will reopen when additional information becomes available. Thanks!
