### ISSUE TITLE
Please provide protobuf 3.1.0 download

### ISSUE THREAD

**Issue by dimbleby** [tensorflow/tensorflow#6402]
Since #4572, TensorFlow depends on protobuf==3.1.0.

[This section](https://github.com/kashif/tensorflow/blob/f2e17755e9466ff3c3f8a5806264d3baccd0f74e/tensorflow/g3doc/get_started/os_setup.md#protobuf-library-related-issues) of the installation instructions continues to point to a wheel for version 3.0.0, which doesn't help at all.

Therefore: please provide pre-built wheels for protobuf 3.1.0.

Also, those instructions tell me that I should only install the protobuf package _after_ installing TensorFlow via pip.  But this isn't currently helpful advice: the TensorFlow package won't install at all, because there is no protobuf==3.1.0:

```
Downloading/unpacking protobuf==3.1.0 (from tensorflow==0.12.0rc1)
  Could not find a version that satisfies the requirement protobuf==3.1.0 (from tensorflow==0.12.0rc1) (from versions: 3.0.0b4, 3.0.0, 3.0.0b2.post2, 3.0.0a2,
3.0.0b2, 2.6.1, 2.0.3, 2.0.0beta, 2.5.0, 2.4.1, 2.6.0, 3.0.0b2.post1, 3.0.0b3, 3.0.0b1.post2, 3.0.0b2.post2, 3.0.0b2.post1, 2.3.0, 3.0.0a3, 3.1.0.post1)
Cleaning up...
No distributions matching the version for protobuf==3.1.0 (from tensorflow==0.12.0rc1)
```

I think what you're trying to say is that if I had been able to succeed in installing TensorFlow then I ought anyway to overwrite whatever protobuf pip had selected.  If so I'd suggest that this belongs higher up in the instructions, and not in some sort of trouble-shooting afterthought section that would easily be missed.

**Comment by dimbleby** [comment]
Related StackOverflow question: http://stackoverflow.com/questions/40989168/protobuf-issue-during-tensorflow-installation

(but it's just someone hitting the same problem, and getting an unhelpful answer).

**Comment by gunan** [comment]
@jhseu I thought the ones we built were 3.1.0?
Looks like we need to push new protobuf packages out?

@yifeif FYI

**Comment by jhseu** [comment]
Fixed now.

**Comment by yaroslavvb** [comment]
BTW, running `python setup.py develop` on 0.12 tag fails with the following

```
Processing dependencies for tensorflow==0.12.0
Searching for protobuf==3.1.0
Reading https://pypi.python.org/simple/protobuf/
No local packages or working download links found for protobuf==3.1.0
error: Could not find suitable distribution for Requirement.parse('protobuf==3.1.0')

```
Workaround it to install `protobuf-3.1.0-py2.py3-none-any.whl` manually:
`pip install --upgrade https://pypi.python.org/packages/b2/30/ab593c6ae73b45a5ef0b0af24908e8aec27f79efcda2e64a3df7af0b92a2/protobuf-3.1.0-py2.py3-none-any.whl#md5=f02742e46128f1e0655b44c33d8c9718
`

**Comment by gunan** [comment]
Ah, you are right.
The reason is, pypi only has 3.1.0post1, or 3.0.0
https://pypi.python.org/pypi/protobuf
@jhseu Which one makes more sense for us to depend on?

**Comment by jhseu** [comment]
It'll work if you patch in 0b133f0cec50636c67174441be70188625a5f474. Perhaps add that to the r0.12 branch, but don't cut a release? It'll help users like @yaroslavvb who build on their own.

**Comment by jhseu** [comment]
Or we can do a patch release. Just might not be worth the effort given the timing with the next release.

**Comment by gunan** [comment]
@yifeif @martinwicke 
This affects 0.12.
This breaks `pip install tensorflow` command in a clean system.
Should we patch and roll out 0.12.1 ?

**Comment by martinwicke** [comment]
Sigh. I suppose we should.

Should we also take the opportunity to rethink how we do pip tests? This
should have been caught by those ideally.

**Comment by gunan** [comment]
This is actually something we do not have a test for, and should be simple to test (But a non hermetic test I hate writing).
We have to check pypi for the dependencies we have. Without our tests contacting pypi, we cannot really catch this issue.

**Comment by martinwicke** [comment]
I think of this as a release test not an integration test so I'm not too
concerned about hermeticity.

**Comment by jhseu** [comment]
Closing this out because 0.12.1 was released.

**Comment by dsblr** [comment]
@jhseu I am still getting the same error for 0.12.1 release. Please help to resolve the issue.

D:\Users\user1\tensorflow\softwares\anaconda>python.exe -m pip install
 tensorflow-0.12.1-cp35-cp35m-win_amd64.whl
Processing d:\users\user1\tensorflow\softwares\anaconda\tensorflow-0.1
2.1-cp35-cp35m-win_amd64.whl
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.11.0 in d:\us
ers\user1\tensorflow\softwares\anaconda\lib\site-packages (from tensor
flow==0.12.1)
Requirement already satisfied (use --upgrade to upgrade): wheel>=0.26 in d:\user
s\user1\tensorflow\softwares\anaconda\lib\site-packages (from tensorfl
ow==0.12.1)
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in d:\user
s\user1\tensorflow\softwares\anaconda\lib\site-packages (from tensorfl
ow==0.12.1)
Collecting protobuf>=3.1.0 (from tensorflow==0.12.1)
  Could not fetch URL https://pypi.python.org/simple/protobuf/: There was a prob
lem confirming the ssl certificate: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_s
sl.c:645) - skipping
  Could not find a version that satisfies the requirement protobuf>=3.1.0 (from
tensorflow==0.12.1) (from versions: )
No matching distribution found for protobuf>=3.1.0 (from tensorflow==0.12.1)

**Comment by jhseu** [comment]
Works for me on my Windows machine. The problem seems to be this error:
`Could not fetch URL https://pypi.python.org/simple/protobuf/: There was a prob
lem confirming the ssl certificate: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_s
sl.c:645) - skipping`

I'm guessing you're sitting behind a proxy. I don't have any advice to give you, but stackoverflow has some questions about it.

**Comment by dsblr** [comment]
@jhseu Thanks for your response. Yes, working behind firewall. Got the solution to fix this.
Need to download the protobuf separately and install using pip install.
Link to download protobuf : https://pypi.python.org/pypi/protobuf/3.1.0
pip install protobuf-3.1.0-py2.py3-none-any.whl

After this step TensorFlow installation works for me.
