### ISSUE TITLE
How to open a Tensorflow <= 2.0 Legacy Model ?

### ISSUE THREAD

**Issue by asusdisciple** [tensorflow/tensorflow#64036]
So I have this really old model (2018) which I want to visualize in tensorboard. For that purpose I need to open/load it of course.

I have the following files:

checkpoint
model.data-00000-of-00001
model.index
model.meta

I have no model definition or anything else. I only find legacy approaches to open this with a session, which does not work anymore.
Is there a way to do it in tensorflow 2.0? I tried installing tensorflow 1.13 in a virtual environment but it's not working since a lot of dependencies on system side changed during the the years (cython, cuda, ...). Maybe you guys know a better way to do this. 

Disclaimer: I have only a very very basic understanding of tensorflow, I really just want to visualize the model, no training or anything else.

**Comment by SuryanarayanaY** [comment]
Hi @asusdisciple ,

We are not supporting 1.x versions. For migration to Tf2.x  please refer the attached guides [migrate_tf2](https://www.tensorflow.org/guide/migrate/migrate_tf2), [script](https://www.tensorflow.org/guide/migrate/upgrade) and other guides [here](https://www.tensorflow.org/guide/migrate).
