### ISSUE TITLE
Confusion about Cuda install docs for Mac

### ISSUE THREAD

**Issue by eraoul** [tensorflow/tensorflow#6404]
### Environment info
Operating System: Mac OSX 10.11

The docs have 2 issues related to this section at the top:

"The GPU version works best with Cuda Toolkit 8.0 and cuDNN v5. Other versions are supported (Cuda toolkit >= 7.0 and cuDNN >= v3) only when installing from sources. Please see Cuda installation for details. For Mac OS X, please see Setup GPU for Mac."

1) The link to "Setup GPU for Mac" doesn't work; presumably the href target is missing or misspelled.

2) The Setup GPU for Mac section is included in the "Install Tensorflow from Source" part of the docs. Several people I know interpreted that to mean that GPU support is only available when installing from source. Furthermore, in the same section is a requirement to use homebrew, and many people I know refuse to use homebrew, so they assumed that Tensorflow was unusable on mac for them. 

I recommend separating out the Setup GPU for Mac instructions to a separate page, unless it truly is dependent on installing from source. If it is, that should also be clarified.

**Comment by Carmezim** [comment]
The link problem is the same as #6389

**Comment by wolffg** [comment]
Part 1 of this issue has been fixed.

**Comment by wolffg** [comment]
Part 2 of this has also been fixed, see:

https://www.tensorflow.org/install/install_mac
