### ISSUE TITLE
tf.split_v() is removed in master?

### ISSUE THREAD

**Issue by wookayin** [tensorflow/tensorflow#6405]
A bit of history:

- Until <= 0.12, [`tf.split()`](https://www.tensorflow.org/api_docs/python/array_ops/slicing_and_joining#split) has the following signature:
```tf.split(split_dim, num_split, value, name='split')```
- In commit f803bd7c (since 0.12), a new op `split_v()` is introduced:
```tf.split_v(value, size_splits, split_dim=0, num=None, name="split_v")```
- In commit a46b6d211 (master), `tf.split_v()` is finally **renamed** to `tf.split()`:
  ```tf.split(value, num_or_size_splits, axis=0, num=None, name="split")```

Due to these changes, the signature of `tf.split()` has been changed. AFAIK TensorFlow will having some of breaking changes after 0.12 (after the end of 2016); is this backward-incompatible API change intended?

If so, **my suggestion is** that `tf.split_v()`, which has been introduced in 0.12, should not be removed in the newer versions as well. In the current master, `tf.split_v` is non-existent.
```
AttributeError: 'module' object has no attribute 'split_v'
```

I am reporthing this (minor) issue because I am frequently switching the tensorflow versions, from r0.12 (stable branch) to master (the breaking? future), and thus I need a way to write a code that is **both compatible** in those two versions. However, due to the change of `tf.split()`, it seems that I cannot achieve it at the moment.

Thanks,

**Comment by aselle** [comment]
We are making several backward incompatible changes. The final state is what you are seeing in the latest master branch where split_v() is removed and split() exists with the keyword arguments 
```python
tf.split(value, num_or_size_splits, axis=0, num=None, name="split")
```
To switch between versions, you will need to creat a local compatiblity wrapper that keys off of `tf.__version__` or uses exceptions to try the newest form and if the keyword arguments don't match use the previous form (this is probably easier). Hope this helps.

**Comment by wookayin** [comment]
Thanks for the feedback. I was assuming backward-incompatible changes, but also was confused since I find there was a similar change on `tf.concat()`: in r0.12 we have both `concat_v2()` and `concat()` (I expect the v2 method will replace the original soon).

However, if the changes are intended, perhaps we might not need to add a method (such as `tf.split_v()`) which would be a legacy, though quite radical. For now, it would be better for me to try alternative approaches as you suggested.

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.

**Comment by wookayin** [comment]
Yeah, I think this is not necessary any more since it has been a while after TF 1.0 came out.
