### ISSUE TITLE
Working code broke after deploying to new installation. ValueError: When using `stateful=True` in a RNN, the batch size must be static. Found dynamic batch size: sequence.shape=(None, xx, xx)

### ISSUE THREAD

**Issue by summa-code** [tensorflow/tensorflow#64061]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.16.1

### Custom code

No

### OS platform and distribution

Ubuntu 22.04

### Mobile device

No

### Python version

3.10.12

### CUDA/cuDNN version

12.4

### Current behavior?

So the existing code broke, with this error

ValueError: When using `stateful=True` in a RNN, the batch size must be static. Found dynamic batch size: sequence.shape=(None, XX, XX), 

but when changed to (XX, XX, XX) I get this, ValueError: Input 0 of layer "lstm" is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: (None, 1, XX, XX)

If static shape is passed, not sure why additional dimension is added. Need help in resolving this. I tried both the release version and nightly version. The issue persists

And also the input is 3D tensor produced by timeseries_dataset_from_array function. Is there any example on training stateful LSTM using these 3D tensors? Not sure if this is a bug really. I am stuck.

### Standalone code to reproduce the issue

```shell
Dont have stand alone.
```

**Comment by Venkat6871** [comment]
Hi **@summa-code** ,
- Ensure that your input data has a static batch size. When using stateful=True, the batch size should not change between batches. You can achieve this by padding or truncating sequences to a fixed length.
- When defining your LSTM layer, set stateful=True and specify the batch_input_shape parameter with a fixed batch size and sequence length.
example:
```
model.add(LSTM(units=64, batch_input_shape=(batch_size, sequence_length, input_dim), stateful=True))
```
- If you are using timeseries_dataset_from_array to prepare your data, make sure that all sequences have the same length. You can achieve this by setting the sequence_length parameter when creating the dataset.
example:
```
dataset = timeseries_dataset_from_array(data, targets, sequence_length=desired_length, batch_size=batch_size)
```

Thank you!

**Comment by summa-code** [comment]
So that was the working code, but after I updated to latest in fresh ubuntu install, "batch_input_shape" not a recognized attribute. 
This is what I am getting

'''ValueError: Unrecognized keyword arguments passed to LSTM: {'batch_input_shape': (xxx, xxx, xxx)}'''

**Comment by summa-code** [comment]
Looks like it is a bug in how they configure the shape. And also there are no examples on how to use stateful lstm in addition to lack of documentation on statefulness.

**Comment by summa-code** [comment]
Anyone?

**Comment by ryhyd** [comment]
Try using the [input object](https://keras.io/2.16/api/layers/core_layers/input/) instead of batch_input_shape. 

`Input(batch_shape=(1,None,4))`

**Comment by summa-code** [comment]
InputLayer in the sequence before LSTM() or in the LSTM(InputLayer) method ?

**Comment by Venkat6871** [comment]
Hi @summa-code ,
- Apologies for the dealy, In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here.

Thank you!

**Comment by goharShoukat** [comment]
I have this same problem. I've been having this for a while now.

**Comment by luvwinnie** [comment]
having same issue, is this solve?

**Comment by il-samoht** [comment]
Same issue here

**Comment by ceschi** [comment]
almost one year later, the bug is still there, with the most recent versions of all the packages involved.
