### ISSUE TITLE
Mac install inside virtualenv cannot import examples

### ISSUE THREAD

**Issue by fpmchu** [tensorflow/tensorflow#641]
I tried the tutorial on my mac, after using virtualenv to install (the normal pip installation failed for me).

I ran
```bash
$ cd $PATH_TO_VIRTUALENV_OF_TENSORFLOW
$ source ./bin/activate
(tensorflow)$ python
>>> import tensorflow as tf  # This succeeds
>>> from tensorflow.examples.tutorials.mnist import input_data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named examples.tutorials.mnist
```

Inspecting the module tensorflow shows there is no submodule named "examples".

I think this is a Mac only issue, not sure if it's only virtualenv too.  When I tried the above on Linux it worked for me.

**Comment by martinwicke** [comment]
I just tried this with a fresh virtualenv (on a Mac), and it worked. Which version of Tensorflow is this? This should work if tf.__version__ is 0.6.0.

I'll close this for now.

**Comment by shivaalroy** [comment]
Just got it to work by having this be my first 3 lines of code: 

```
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
```
