### ISSUE TITLE
LossScaleOptimizer#get_scaled_loss() does not exist

### ISSUE THREAD

**Issue by keisen** [tensorflow/tensorflow#64124]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf2.16+

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04 on Windows10 WSL

### Python version

3.10.13

### Current behavior?

As this title says, `LossScaleOptimizer#get_scaled_loss()` method does NOT exist.
Until tf2.15, the method definitely existed.
Where is it now? or How do we access it?

[https://www.tensorflow.org/api_docs/python/tf/keras/mixed_precision/LossScaleOptimizer](https://www.tensorflow.org/api_docs/python/tf/keras/mixed_precision/LossScaleOptimizer?_gl=1*1kcgzin*_up*MQ..*_ga*MTU5OTYzMDg2MS4xNzExMDAwMDg0*_ga_W0YLR4190T*MTcxMTAwMDA4My4xLjAuMTcxMTAwMDA4My4wLjAuMA..#get_scaled_loss)

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

optimizer = tf.optimizers.Adam()
wrapped_optimizer = tf.keras.mixed_precision.LossScaleOptimizer(optimizer)

print(f'get_scaled_loss() exists: {"get_scaled_loss" in dir(wrapped_optimizer)}')
```

### Relevant log output

```shell
get_scaled_loss() exists: False
```

**Comment by Venkat6871** [comment]
Hi **@keisen** ,

I tried to run your code on colab using TF v2.15, 2.16 and nightly versions, and faced the same issue. Please find the [gist ](https://colab.sandbox.google.com/gist/Venkat6871/0b7dc2e7d692a41f7859030e0b0cd169/64124_2-15-2-16-nightly-v.ipynb)here for reference.

Thank you!

**Comment by keisen** [comment]
Hi @Venkat6871 

Thank you for reproducing this issue. I believe it's the same as I faced.
My OSS library has been using this API, so I want your team to fix it asap...
When do you expect it to be fixed?

Thanks!

**Comment by keisen** [comment]
Hi @Venkat6871 
Is there any progress?

**Comment by markub3327** [comment]
@keisen 
Please look at this solution:
https://github.com/keras-team/keras/issues/19479

**Comment by keisen** [comment]
@markub3327 

Thank you so much for letting us know that!
I'll close this issue 👍 

Thanks!
