### ISSUE TITLE
Negative values returned from tf.math.sobol_sample

### ISSUE THREAD

**Issue by nfergu** [tensorflow/tensorflow#64149]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.15, 2.16-nightly

### Custom code

No

### Current behavior?

Negative values are returned from `tf.math.sobol_sample` with large `skip` values. I would expect all values returned from `tf.math.sobol_sample` to be positive. Perhaps this is an overflow?

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

float(tf.math.sobol_sample(
    1,
    1,
    skip=int(1e10),
))
```

### Relevant log output

```shell
-0.5015935897827148
```

**Comment by sssprove** [comment]
Interesting, the current check on inputs currently for `skip` appears to be only that it is non-negative: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sobol_op.cc#L156.

And correspondingly no overflow testcase. Although there is one for `num_results * dim` argument combination: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/sobol_ops_test.py#L143

**Comment by redwrasse** [comment]
Interesting, current argument check appears to be simply that `skip` is non-negative: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sobol_op.cc#L156

And correspondingly no overflow testcase, though the `num_results*dim` argument combination does: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/sobol_ops_test.py#L143

**Comment by redwrasse** [comment]
Looks like indeed `skip` is overflowing. 
```
import tensorflow as tf

int32max = 2147483647

skip = int32max + 5
num_results = 1
dim = 1
res = tf.math.sobol_sample(
              dim=dim, num_results=num_results, skip=skip, dtype=tf.dtypes.float32)
print(res)
```
Results in 
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__SobolSample_device_/job:localhost/replica:0/task:0/device:CPU:0}} skip must be non-negative [Op:SobolSample]

```

`skip` appears to be read in as overflow here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sobol_op.cc#L146

**Comment by redwrasse** [comment]
Looks to me like the sobol operation has a couple overflow checks for `skip` and `num_results + skip`, though they don't always get triggered (as in the example given in the issue description)

```
import tensorflow as tf


int32max = 2147483647

testcases = [(1, int32max), (1, int32max+1), (int32max, int32max), (1, int(1e5)), (1, int(1e10)), (1, int(1e15)), (1, int(1e20))]

for num_results, skip in testcases:
    try:
        a = float(tf.math.sobol_sample(1, num_results, skip))
        print(f"computed {a} for num_results={num_results}, skip={skip}")
    except Exception as err:
        print(f"error computing for num_results={num_results}, skip={skip}: {err}")
```

Console output:

```
error computing for num_results=1, skip=2147483647: num_results+skip must be less than 2147483647 [Op:SobolSample]
error computing for num_results=1, skip=2147483648: skip must be non-negative [Op:SobolSample]
error computing for num_results=2147483647, skip=2147483647: num_results+skip must be less than 2147483647 [Op:SobolSample]
computed 0.5610733032226562 for num_results=1, skip=100000
computed -0.5015935897827148 for num_results=1, skip=10000000000
error computing for num_results=1, skip=1000000000000000: skip must be non-negative [Op:SobolSample]
error computing for num_results=1, skip=100000000000000000000: Can't convert Python sequence with out-of-range integer to Tensor.
```

**Comment by redwrasse** [comment]
[This thread](https://github.com/tensorflow/tensorflow/issues/57514#issuecomment-1251135723) argues signed integer input overflow is not the responsibility of Tensorflow to check unless it causes system crash.

It may be worth nonetheless extending the unit tests for those overflow checks that are implemented in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sobol_op.cc#L137.

**Comment by sushreebarsa** [comment]
@nfergu Though I was able to replicate the issue reported [here](https://colab.research.google.com/gist/sushreebarsa/f0cd7f1ea8a0456d1a938b454fb5846f/64149.ipynb), could you please try reducing the skip value. Smaller skip values require less complex calculations and might avoid overflow.
Thank you!

**Comment by nfergu** [comment]
@sushreebarsa Thanks! We already reduced the skip value, as you suggested. We’re happy with this workaround.

**Comment by sushreebarsa** [comment]
@nfergu Thank you for the response!
Could you please move this issue to closed status if the workaround works for you?
Thank you!
