### ISSUE TITLE
INT4 and other low-precision conversion support status

### ISSUE THREAD

**Issue by AIWintermuteAI** [tensorflow/tensorflow#64193]
What is the current status of model conversion (PTQ specifically) with INT4 precision?

The question was raised before here https://github.com/tensorflow/tensorflow/issues/60125.
Also it looks like INT4 support is being added to various parts of tensorflow, as evidenced by https://github.com/tensorflow/tensorflow/pull/63870 and https://github.com/tensorflow/tensorflow/blob/6738c28cf4eed334d75d02b6e97fe16c34069ef1/tensorflow/compiler/mlir/quantization/tensorflow/quantization_options.proto#L76. 

However at the moment there seems to be no way to quantize model to INT4 (specifically the weights):
- the tflite converter MLIR based conversion (the "experimental" conversion) seems abandoned. It is not possible to specify the type of weights quantization
- what seems to be a new API for quantization (is it the one from blog article https://blog.tensorflow.org/2023/05/google-io-2023-whats-new-in-tensorflow-and-keras.html ?) lives here https://github.com/tensorflow/tensorflow/tree/master/tensorflow/compiler/mlir/quantization/tensorflow (???). It is possible to use it with INT8, but not INT4 - but the resulting SavedModel cannot be converted to .tflite (SegFault).

Can anyone who actively works on this in TF team shine the light on what is the current direction and where one needs to dig to add INT4 PTQ quantization?

**Comment by LakshmiKalaKadali** [comment]
Hi @AIWintermuteAI,

Please share your .tflite file to reproduce the issue.

Thank You

**Comment by pkgoogle** [comment]
Hi @abattery, can you please take a look or comment on this? Thanks.
