### ISSUE TITLE
tf.math.reciprocal lacks support of int input on CPU, inconsistent with the documentation

### ISSUE THREAD

**Issue by drewshark** [tensorflow/tensorflow#64224]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15.0

### Custom code

Yes

### Current behavior?

tf.math.reciprocal fails to support integer input on CPU, which is inconsistent with its documentation https://www.tensorflow.org/api_docs/python/tf/math/reciprocal?hl=en.
Instead, it can support integer input on GPU.

### Standalone code to reproduce the issue

```shell
import os
os.environ['CUDA_VISIBLE_DEVICES'] = ''
import numpy as np
import tensorflow as tf
x = tf.constant(np.random.randint(-50, 50, ()), dtype='int64')
tf.math.reciprocal(x)
```
```


### Relevant log output

```shell
tensorflow.python.framework.errors_impl.NotFoundError: Could not find device for node: {{node Reciprocal}} = Reciprocal[T=DT_INT64]
All kernels registered for op Reciprocal:
  device='XLA_CPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_INT16, DT_INT8, DT_COMPLEX64, DT_INT64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='XLA_GPU_JIT'; T in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_INT16, DT_INT8, DT_COMPLEX64, DT_INT64, DT_BFLOAT16, DT_COMPLEX128, DT_HALF]
  device='GPU'; T in [DT_COMPLEX128]
  device='GPU'; T in [DT_COMPLEX64]
  device='GPU'; T in [DT_INT64]
  device='GPU'; T in [DT_DOUBLE]
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_HALF]
  device='GPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_COMPLEX128]
  device='CPU'; T in [DT_COMPLEX64]
  device='CPU'; T in [DT_DOUBLE]
  device='CPU'; T in [DT_BFLOAT16]
  device='CPU'; T in [DT_HALF]
  device='CPU'; T in [DT_FLOAT]
 [Op:Reciprocal] name:
```

**Comment by sushreebarsa** [comment]
@drewshark Before applying tf.math.reciprocal, could you try to explicitly cast your integer input tensor to a supported floating-point data type using tf.cast as follows;
```
import os
os.environ['CUDA_VISIBLE_DEVICES'] = ''
import numpy as np
import tensorflow as tf
x = tf.constant(np.random.randint(-50, 50, ()), dtype='int64')
x = tf.cast(x, dtype=tf.float64)
tf.math.reciprocal(x)
```
It might resolve the issue. Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/b1f4eab9862172e1e27994f91429ebea/64224.ipynb) for reference.
Thank you!

**Comment by drewshark** [comment]
@sushreebarsa Sure, thanks for your effort in fixing it.

**Comment by sushreebarsa** [comment]
@drewshark Glad it helped you!
Thank you for your response here.
Closing the issue for now.
