### ISSUE TITLE
AttributeError: 'module' object has no attribute 'legacy_seq2sec'

### ISSUE THREAD

**Issue by AmirHadifar** [tensorflow/tensorflow#6440]
In Tensorflow 0.12.0 && python 2.7.10  When I run :
        `ptb_word_lm.py --data_path=/Users/mac/Documents/Tensor/simple-examples/data/ --model small`

It throws such exception:
      

>   AttributeError: 'module' object has no attribute 'legacy_seq2sec'

How can I fix this issue?

**Comment by zhiweifang** [comment]
I got the same problem and have no idea.
And I can not find legacy_seq2sec in API r0.12. Is this api removed?

**Comment by aselle** [comment]
@nealwu, could this be related to your migrations? Could you fix the instructions to flex this if so.

**Comment by nealwu** [comment]
I tried this out with the current master version of TensorFlow and with r0.12, and they both worked for me.

Make sure you are either building TensorFlow from the master version of the repository and running the latest [code in the models repo](https://github.com/tensorflow/models/tree/master/tutorials/rnn/ptb) or running TensorFlow r0.12 with the r0.12 version of the model (https://github.com/tensorflow/tensorflow/releases/tag/0.12.1).

**Comment by nealwu** [comment]
If it's still not working after that, feel free to reopen this.
