### ISSUE TITLE
Build on windows using bazel broken

### ISSUE THREAD

**Issue by gunan** [tensorflow/tensorflow#6442]
Operating System: Windows
bazel 0.4.2, issue is seen at master branch.

It looks like sometime after our update to libjpeg turbo, our build has been broken in windows.
I am looking into it, but I cannot see a clear resolution to the problem.
The error message says:
http://ci.tensorflow.org/job/tf-master-win-bzl/218/console
```
00:04:27.376 c:\tmp\_bazel_system\rrc05caq\execroot\tf-master-win-bzl\external\jpeg\jmorecfg.h(242): error C2371: 'boolean': redefinition; different basic types
00:04:27.376 c:\program files (x86)\windows kits\10\include\10.0.14393.0\shared\rpcndr.h(193): note: see declaration of 'boolean'
```

I checked jmorecfg.sh, and tried to use `#define HAVE_BOOLEAN` to get around the issue. However that causes:
http://ci.tensorflow.org/view/Experimental/job/exp-win-bzl/4/console

Creating the issue to track a quick resolution to the problem.

CC Our in house windows experts:
@meteorcloudy @mrry 

@guschmue @vit-stepanovs Do you have any ideas how we can solve this?
We would like to also upgrade cmake build to use libjpeg-turbo, but before that I want to make sure it builds when we do.

**Comment by vit-stepanovs** [comment]
A quick search showed that 'boolean' is defined in Windows SDK header rpcndr.h.

Actually, it looks like jpeg-turbo does handle this case in in [win/jconfig.h.in](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/win/jconfig.h.in):

#ifndef __RPCNDR_H__		/* don't conflict if rpcndr.h already read */
typedef unsigned char boolean;
#endif
#define HAVE_BOOLEAN

One of the following is possible:

1. Bazel does not generate the proper version of jconfig.h for Windows.
2. The JCONFIG_INCLUDED macro is defined somewhere by Bazel, i.e. at the top of jpeg.lib

#ifndef JCONFIG_INCLUDED        /* in case jinclude.h already did */
#include "jconfig.h"            /* widely used configuration options */
#endif

**Comment by gunan** [comment]
OK, I think I have an idea about what we are missing
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/CMakeLists.txt#L186

In cmake based libjpeg turbo build, jconfig.h is replaced by win/jconfig.h.in
For us, we seem to have some genrules, which do some sort of magic 
https://github.com/tensorflow/tensorflow/blob/master/third_party/jpeg.BUILD#L279
https://github.com/tensorflow/tensorflow/blob/master/third_party/jpeg.BUILD#L304

@jart Do you know why our BUILD file does this, instead of copying things? like the cmake rules?

**Comment by jart** [comment]
When writing jpeg.BUILD I primarily copied off of the internal Google configuration in //third_party. If you want to restructure those genrules to copy the default config.h files rather than inlining them, then I would recommend comparing their contents with the Google modifications internally.

**Comment by gunan** [comment]
OK, I have an idea now to how to proceed.
I am working on a solution.
