### ISSUE TITLE
TF 2.16 Incorrect model with TextVectorization in SavedModel format contains float input type instead of string type

### ISSUE THREAD

**Issue by rkazants** [tensorflow/tensorflow#64443]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.16.1

### Custom code

Yes

### Current behavior?

Model with TextVectorization layer after saving into SavedModel format using tf.saved_model.save contains float32 input instead of string type

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Input, TextVectorization
from tensorflow.keras.models import Model

vocabulary = ['hello', 'there', 'random', 'vocab', 'check']
length = 64

text_input = Input(dtype=tf.string, shape=(1,), name='text_input')
vectorize_layer = TextVectorization(vocabulary=vocabulary, output_mode='int', name='vectorization_layer',
                                    output_sequence_length=length)(text_input)
model = Model(inputs={'text_input': text_input}, outputs=[vectorize_layer])

input_data = np.array([['hello here and there']], dtype=str)
model({'text_input': input_data})

tf.saved_model.save(model, 'my_model')
loaded_model = tf.keras.layers.TFSMLayer('my_model', call_endpoint="serving_default")
loaded_model(input_data)
```

### Relevant log output

```shell
ValueError: could not convert string to float: 'hello here and there'
```

**Comment by tilakrayal** [comment]
@rkazants,
Thank you for reporting the issue. Looks like this issue is more related to Keras3.0. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/bcface2dd3959545e755c62f2ee439ce/untitled1786.ipynb). Could you please create a new issue on [keras-team/keras](https://github.com/keras-team/keras/issues/) for the quick resolution. Thank you!

**Comment by rkazants** [comment]
> @rkazants, Thank you for reporting the issue. Looks like this issue is more related to Keras3.0. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/bcface2dd3959545e755c62f2ee439ce/untitled1786.ipynb). Could you please create a new issue on [keras-team/keras](https://github.com/keras-team/keras/issues/) for the quick resolution. Thank you!

Filled here: https://github.com/keras-team/keras/issues/19396

**Comment by tilakrayal** [comment]
@rkazants,
Could you please feel free to move this issue to closed status,  since it is already being tracked there. Thank you!
