### ISSUE TITLE
Documentation request: leave all function names on the sidebar

### ISSUE THREAD

**Issue by chrisranderson** [tensorflow/tensorflow#6448]
Before, I found it really nice that I could `ctrl+f` to look up a function really quickly. Now I either have to Google it or use the search bar, or worse, scan through the hierarchy and click a few times and scroll til I find it. Not a huge deal, but relatively painful.

It was nice to get instant search results for even partial bits of function names.

**Comment by ahundt** [comment]
I agree this was nice to be able to have one page to search around, but they may not think this would scale as the TensorFlow API grows.

I also just can't help acknowledging that, at some level, this is a complaint about having to Google that's being delivered to Google. :-)

**Comment by aselle** [comment]
@wolffg, don't know if there is an easy way to get a ctrl-f'able page.

**Comment by wolffg** [comment]
I think I understand your request, and it was a use case we thought about.  The landing page:

https://www.tensorflow.org/api_docs/python/

is designed to be complete index that you could use ctrl-f to hunt around in.  Does that cover your use case?  Is it missing functions?

**Comment by chrisranderson** [comment]
That's the right idea - I still think it would be an improvement to the current sidebar. I guess you folks would have to A-B test it or something to see how much people use the sidebar the way it is vs. the comprehensive API list.

**Comment by wolffg** [comment]
After some further discussion, I don't think this is something we're going to pursue---an unrolled list like that is functionally a multipage hidden index on every page, which isn't really useful as left navigation, and (as noted above) won't scale as we add more packages.

The API landing page has an entire index and comments available for text search, and we're working on ways to make site search more accurate.  I'm going to close this issue, however.

**Comment by chrisranderson** [comment]
Discussion is good enough for me. Thanks for looking into it.
