### ISSUE TITLE
Using OpenCL on macOS

### ISSUE THREAD

**Issue by k-hashimoto** [tensorflow/tensorflow#6449]
Thank you very much for developing nice framework. I have a question about OpenCL support for macOS. Is there no way to run tensorflow with GPU on recent MacBookPro?  Tensorflow support OpenCL. But I think this is for Linux, not for macOS. Tensorflow + OpenCL need ComputeCpp. But ComputeCpp compiler do not support macOS(I couldn't find ComputeCpp binary for mac). Do you have a plot to support recent MacBook pro's GPU?

**Comment by sasadep** [comment]
OpenCL  support is tracked on  #22

**Comment by benoitsteiner** [comment]
@lukeiwanski maybe have more information on the ComputeCpp plan for MacOS

**Comment by lukeiwanski** [comment]
Hello @k-hashimoto,
Currently, unfortunately no, you cannot use ComputeCpp on macOS.
As of today, SPIR 1.2 ( https://www.khronos.org/spir ) support is essential for ComputeCpp to work on any platform and it boils down to Apple not providing SPIR 1.2 support yet.

macOS support is definitely an important milestone on our roadmap - a lot of developers are asking for it - and the support should be available in the future.

Perhaps http://www.apple.com/feedback/ would speed it up :)

Thanks,
Luke

**Comment by k-hashimoto** [comment]
OK. Thanks!

**Comment by bhack** [comment]
@lukeiwanski What do you think to rely on something similar to SPIR-V MSL translability https://github.com/KhronosGroup/SPIRV-Cross/blob/master/README.md?

**Comment by lukeiwanski** [comment]
@bhack at the moment we target SPIR. It might be possible to translate that into other formats but at the moment we output SPIR 1.2 only. SPIR-V is an interesting format but we cannot emit it right now.

**Comment by bhack** [comment]
@lukeiwanski Will XLA impact also your effort?

**Comment by michaelisard** [comment]
Closing for now. Please reopen if there's a specific issue beyond those tracked in #22.

**Comment by bhack** [comment]
@lukeiwanski Now that a first version of XLA it s released what do you think of https://github.com/tensorflow/tensorflow/issues/22#issuecomment-272426528?
