### ISSUE TITLE
Casting int64 to int8 is not supported

### ISSUE THREAD

**Issue by nikitakit** [tensorflow/tensorflow#645]
Nor `int32`->`int8` or `int16`->`int8`.

Granted, these aren't the safest of operations, but it's still a surprise that they throw an exception.

**Comment by girving** [comment]
What version are you using?  I believe @martinwicke fixed this, and it might already be in 0.6.0.

**Comment by nikitakit** [comment]
I'm using 0.6.0 for Mac via pip

**Comment by girving** [comment]
I'll wait for @martinwicke's reply, but that may mean it's only in git and will be released with the next version.

**Comment by martinwicke** [comment]
Yeah, that change was after 0.6.0. If you update to master (which means
building yourself), you should have universal casts.

**Comment by girving** [comment]
Closing since it's fixed in git.
