### ISSUE TITLE
protobuf fatal error in Tensorflow 2.16.1 on macos M1

### ISSUE THREAD

**Issue by asapsmc** [tensorflow/tensorflow#64507]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.16.1

### Custom code

No

### OS platform and distribution

macOS Sonoma 14.4

### Python version

3.10.14

### Current behavior?

I'm trying to run a test snippet, and I get protobuf FATAL error `[libprotobuf FATAL google/protobuf/message_lite.cc:353] CHECK failed: target + size == res: 
libc++abi: terminating due to uncaught exception of type google::protobuf::FatalException: CHECK failed: target + size == res: `

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import tensorflow_datasets as tfds

print("TensorFlow version:", tf.__version__)
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))
tf.config.list_physical_devices('GPU')
(ds_train, ds_test), ds_info = tfds.load(
    'mnist',
    split=['train', 'test'],
    shuffle_files=True,
    as_supervised=True,
    with_info=True,
)


def normalize_img(image, label):
    """Normalizes images: `uint8` -> `float32`."""
    return tf.cast(image, tf.float32) / 255., label


batch_size = 128
ds_train = ds_train.map(
    normalize_img, num_parallel_calls=tf.data.experimental.AUTOTUNE)
ds_train = ds_train.cache()
ds_train = ds_train.shuffle(ds_info.splits['train'].num_examples)
ds_train = ds_train.batch(batch_size)
ds_train = ds_train.prefetch(tf.data.experimental.AUTOTUNE)
ds_test = ds_test.map(
    normalize_img, num_parallel_calls=tf.data.experimental.AUTOTUNE)
ds_test = ds_test.batch(batch_size)
ds_test = ds_test.cache()
ds_test = ds_test.prefetch(tf.data.experimental.AUTOTUNE)
model = tf.keras.models.Sequential([
    tf.keras.layers.Conv2D(32, kernel_size=(3, 3),
                           activation='relu'),
    tf.keras.layers.Conv2D(64, kernel_size=(3, 3),
                           activation='relu'),
    tf.keras.layers.MaxPooling2D(pool_size=(2, 2)),
    #   tf.keras.layers.Dropout(0.25),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    #   tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(10, activation='softmax')
])
model.compile(
    loss='sparse_categorical_crossentropy',
    optimizer=tf.keras.optimizers.Adam(0.001),
    metrics=['accuracy'],
)
model.fit(
    ds_train,
    epochs=12,
    validation_data=ds_test,
)
```

### Relevant log output

```shell
TensorFlow version: 2.16.1
Num GPUs Available:  1
2024-03-26 12:50:25.667311: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2024-03-26 12:50:25.667392: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2024-03-26 12:50:25.667406: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2024-03-26 12:50:25.667714: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-03-26 12:50:25.667759: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
Epoch 1/12
2024-03-26 12:50:27.299359: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.
[libprotobuf FATAL google/protobuf/message_lite.cc:353] CHECK failed: target + size == res: 
libc++abi: terminating due to uncaught exception of type google::protobuf::FatalException: CHECK failed: target + size == res:
```

**Comment by tilakrayal** [comment]
@asapsmc,
Thank you for the issue. Could you please provide the steps you have followed to install the tensorflow 2.16.1 on macos and allow some time to debug the issue. Thank you!

**Comment by asapsmc** [comment]
I'm using miniforge, so it was `conda install -c apple tensorflow-deps`, then activate and then `python -m pip install tensorflow`followed by `python -m pip install tensorflow-metal`.

**Comment by digitalStyx** [comment]
Hi,
I understand that you are using GPU to build your model. This is an issue with the `tensorflow-metal` library, as it only supports `tensorflow` up to version 2.14. Therefore, it seems that we need to wait for a new version of the `tensorflow-metal` library. For now, if you want to use `tensorFlow` >2.14, you will need to uninstall` tensorflow-metal` or refrain from using the GPU.

**Comment by asapsmc** [comment]
Thanks for your help. Now I define tensorflow==2.14 and everything works.

**Comment by tilakrayal** [comment]
@asapsmc,
AFAIK the version of tensorflow-metal==1.1.0 must be along with tensorflow-macos==2.14.0. So, If you use "pip install tensorflow-macos" alone. You will get 2.15.0 or the latest. So you must install the version which tensorflow-metal is supported. Thank you!

**Comment by aurbital** [comment]
Thank you for this post, I also ran into the same issue! As another source posted, the tensorflow-metal compatibility listing is here: [(https://pypi.org/project/tensorflow-metal/)]

After I outright deleted my virtual environment and started over, here are the commands I ran:
```
conda create --name venv-metal (environment location: /opt/anaconda3/envs/venv-metal)
conda install -c apple tensorflow-deps --force-reinstall -n venv-metal
python -m pip install tensorflow==2.14
python -m pip install tensorflow-metal==1.1.0
```
I then ran the test code shown on [https://developer.apple.com/metal/tensorflow-plugin/] and the run was successful! On my Macbook epoch #1 took 41s to run, epochs 2-5 each took ~32s. For comparison, in Google Colab CPU only mode, each epoch was gonna take WAAAAAAAY longer than that.

**Comment by uyokiY** [comment]
> 感谢这篇文章，我也遇到了同样的问题！正如另一个来源所发布的那样，tensorflow-metal 兼容性列表在这里：[https ://pypi.org/project/tensorflow-metal/](https://pypi.org/project/tensorflow-metal/)
> 
> 在我彻底删除虚拟环境并重新开始之后，我运行了以下命令：
> 
> ```
> conda create --name venv-metal
> conda install -c apple tensorflow-deps --force-reinstall -n venv-metal
> python -m pip install tensorflow==2.14
> python -m pip install tensorflow-metal==1.1.0
> ```
> 
> [然后我运行了https://developer.apple.com/metal/tensorflow-plugin/](https://developer.apple.com/metal/tensorflow-plugin/)上显示的测试代码，运行成功！在我的 Macbook 上，epoch 1 运行了 41 秒，epoch 2-5 每次运行大约 32 秒。相比之下，在 Google Colab 仅 CPU 模式下，每个 epoch 都要花费更长的时间。

使用 pip install tensorflow-macos==2.14 似乎更有效
