### ISSUE TITLE
Error with loading a .pb model for prediction: Op type not registered 'DecodeProtoSparseV4'

### ISSUE THREAD

**Issue by shabnamso** [tensorflow/tensorflow#64553]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

latest version

### Custom code

Yes

### OS platform and distribution

Windows

### Current behavior?

Encountered an issue while trying to load a trained .pb model using tf.saved_model.load. I'm receiving a RuntimeError stating that the Op type not registered 'DecodeProtoSparseV4'. Here are the details:

Error Message:

RuntimeError: Op type not registered 'DecodeProtoSparseV4' in binary running on [Machine's Name]. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

model_directory = 'C:\Users\...\predict\001'
model = tf.saved_model.load(model_directory)
```

**Comment by SuryanarayanaY** [comment]
Hi @shabnamso ,

Actually the mentioned Op DecodeProtoSparseV4 is not exists in latest Official TF binaries. It might be possible that this particular Op is a user created Op. Tensorflow provides the flexibility to users to create their own Op and gradient for same. You can refer this [guide](https://www.tensorflow.org/guide/create_op) on same.

I believe you are trying to reload a model that is trained on custom built TF binary with latest Official release. May be you have to use same binary wheel upon which the model was trained initially. Unfortunately we can't provide support for custom ops of users.

Thanks!

**Comment by shabnamso** [comment]
Hi @SuryanarayanaY

The model was trained by Vertex AI. I downloaded the model to my local machine.

**Comment by SuryanarayanaY** [comment]
Hi @shabnamso , Could you please share the model details. You mean the model is a pretrained model of Vertex AI ?

**Comment by shabnamso** [comment]
Hi @SuryanarayanaY 
The model was pretrained by vertex AI and the files and folders of the model were downloaded to local machine. The saved_model.pb was automatically in the folder /predict/001.

**Comment by SuryanarayanaY** [comment]
Hi @shabnamso .

Have you used any pre-trained/readily available model from VertexAI.If so which one? VertexAI can host user built models also if I am not wrong?
