### ISSUE TITLE
ImportError when using tensorflow 2.8.0 and python 3.9.16 undefined symbol: PyCMethod_New

### ISSUE THREAD

**Issue by sunitha8687** [tensorflow/tensorflow#64552]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.8.0

### Custom code

Yes

### OS platform and distribution

Linux/amd64

### Mobile device

EMR cluster

### Python version

3.9.16

### Current behavior?

I am running a python script(udf from pyspark) from emr node that is launched using a custom docker image. I have python 3.9 installed and tensorflow 2.8.0 installed. When running this particular python script as a spark-submit job, I have an error with tenosrflow PyCMethod_New. 
<img width="1170" alt="Screenshot 2024-03-26 at 23 16 33" src="https://github.com/tensorflow/tensorflow/assets/44788173/d08cc361-aa6c-4284-ae32-87037a4475c5">

### Standalone code to reproduce the issue

```shell
Below is the simple python code that I am testing as a spark-submit job that uses docker as runtime environment and error is thrown while importing this package itself. 

from pyspark.sql import SparkSession
from pyspark.sql.functions import udf
from pyspark.sql.types import StringType
import sys
sys.path.append("/home/ec2-user/venv/lib/python3.9/site-packages")
import zooperetl
import tensorflow as tf

# Initialize Spark session
spark = SparkSession.builder.appName("MySparkJob").getOrCreate()

# Create a sample DataFrame
data = [("zooperetl",), ("numpy",), ("tensorflow",)]
columns = ["Package"]
df = spark.createDataFrame(data, columns)

# Define a custom UDF to import a library inside udf. 
def get_tensorflow_version():
    return tf.__version__

# Register the UDF
get_tf_version_udf = udf(get_tensorflow_version, StringType())

# Apply the UDF to create a new column with TensorFlow version
df_with_tf_version = df.withColumn("tensorflow_version", get_tf_version_udf())

# Show the DataFrame with the added column
df_with_tf_version.show()

# Submit the Spark job to the EMR cluster
# Replace 's3://your-bucket/your-script.py' with your actual script location
# spark-submit --master yarn --deploy-mode client s3://your-bucket/your-script.py
```

**Comment by sushreebarsa** [comment]
@sunitha8687 You are using an older TF version 2.8 which is not actively supported so could you please try to upgrade to the latest and follow the tested build configurations [here](https://www.tensorflow.org/install/source#tested_build_configurations). Thank you!

**Comment by sunitha8687** [comment]
Thanks for your response. I checked the tested build configurations for Linux from your link, looks like 2.8 and 2.10 supports python 3.7to 3.10. 
Just to give you some background context here: I am building a docker image in local and then pushing it to the artifactory. This also uses amazoncoretto:17 as base image. So my local system is Mac os, but anyway i specify the platform to be linux/amd64 when i build docker image. The EMR cluster also uses amazon linux os. 

In this case i look for linux right ?
![image](https://github.com/tensorflow/tensorflow/assets/44788173/6d58b280-fd7d-4c32-ac34-812dd2936662)

**Comment by sushreebarsa** [comment]
@sunitha8687 Since your tested build configurations support Python 3.7 to 3.10, please update the base image in your Dockerfile . Kindly rebuild your Docker image locally with the updated base image and let us know?
Thank you!
