### ISSUE TITLE
Tensorflow import and GPU env

### ISSUE THREAD

**Issue by KnSun99** [tensorflow/tensorflow#64569]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf 2.15.0

### Custom code

Yes

### OS platform and distribution

Ubuntu 22.04.4

### Python version

3.11.8

### CUDA/cuDNN version

cuda-version 12.3;  cudnn  8.9.7.29

### GPU model and memory

RTX 4090,  24G

### Current behavior?

In the conda environment, use the following command to install tensorflow:
conda install conda-forge::tensorflow-gpu

![image](https://github.com/tensorflow/tensorflow/assets/123467428/6b2672c7-91a6-4f45-a632-5226ddf3313c)
![image](https://github.com/tensorflow/tensorflow/assets/123467428/ac325774-f3b0-4191-8c65-3dea6c1076b1)

Run:  import tensorflow as tf

The following error is reported:

File ~/Software/Miniconda3/envs/DLC/lib/python3.11/site-packages/tensorflow/python/platform/self_check.py:63 in preload_check
    from tensorflow.python.platform import _pywrap_cpu_feature_guard

ImportError: /home/hhh/Software/Miniconda3/envs/DLC/lib/python3.11/site-packages/tensorflow/python/platform/../../libtensorflow_framework.so.2: undefined symbol: _ZTIN6snappy4SinkE

How can I solve it?

###
If you use the following command to install tensorflow:
$ pip install tensorflow==2.16.1

How should I configure cudatoolkit, cudnn, etc., in a conda environment?

Because there are many conda environments, cuda and cudnn are expected to be installed in the conda environment.
When cuda is installed in the system, conflicts between different conda environments are feared.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
Traceback (most recent call last):

  Cell In[1], line 1
    import tensorflow as tf

  File ~/Software/Miniconda3/envs/DLC/lib/python3.11/site-packages/tensorflow/__init__.py:40
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

  File ~/Software/Miniconda3/envs/DLC/lib/python3.11/site-packages/tensorflow/python/pywrap_tensorflow.py:34
    self_check.preload_check()

  File ~/Software/Miniconda3/envs/DLC/lib/python3.11/site-packages/tensorflow/python/platform/self_check.py:63 in preload_check
    from tensorflow.python.platform import _pywrap_cpu_feature_guard

ImportError: /home/hhh/Software/Miniconda3/envs/DLC/lib/python3.11/site-packages/tensorflow/python/platform/../../libtensorflow_framework.so.2: undefined symbol: _ZTIN6snappy4SinkE
```

**Comment by tilakrayal** [comment]
@KnSun99,
Can you run and post the output of `python -m pip list` and` python -c 'import tensorflow'` run from the same environment and also the steps followed? I will also try to install with the same environment details and provide the info. Thank you!

**Comment by KnSun99** [comment]
OK，

(DLC) hhh@hhh49:~$ python -m pip list
Package                       Version
----------------------------- ------------
absl-py                       1.4.0
aiohttp                       3.9.3
aiosignal                     1.2.0
alabaster                     0.7.12
arrow                         1.2.3
astroid                       2.14.2
asttokens                     2.0.5
astunparse                    1.6.3
atomicwrites                  1.4.0
attrs                         23.1.0
autopep8                      2.0.4
Babel                         2.11.0
beautifulsoup4                4.12.2
binaryornot                   0.4.4
black                         23.11.0
bleach                        4.1.0
blinker                       1.6.2
Brotli                        1.0.9
cached-property               1.5.2
cachetools                    4.2.2
certifi                       2024.2.2
cffi                          1.16.0
chardet                       4.0.0
charset-normalizer            2.0.4
click                         8.1.7
cloudpickle                   2.2.1
colorama                      0.4.6
comm                          0.2.1
contourpy                     1.2.0
cookiecutter                  2.6.0
cryptography                  42.0.5
cycler                        0.12.1
debugpy                       1.6.7
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.7
dlclibrary                    0.0.6
docstring-to-markdown         0.11
docutils                      0.18.1
executing                     0.8.3
fastjsonschema                2.16.2
filelock                      3.13.3
filterpy                      1.4.5
flake8                        7.0.0
flatbuffers                   24.3.25
fonttools                     4.50.0
frozenlist                    1.4.0
fsspec                        2024.3.1
gast                          0.5.3
google-auth                   2.6.0
google-auth-oauthlib          0.5.2
google-pasta                  0.2.0
grpcio                        1.59.3
h5py                          3.10.0
huggingface-hub               0.22.0
idna                          3.4
imageio                       2.34.0
imageio-ffmpeg                0.4.9
imagesize                     1.4.1
imgaug                        0.4.0
importlib-metadata            7.0.1
inflection                    0.5.1
intel-openmp                  2024.0.3
intervaltree                  3.1.0
ipykernel                     6.29.3
ipython                       8.20.0
isort                         5.9.3
jaraco.classes                3.2.1
jedi                          0.18.1
jeepney                       0.7.1
jellyfish                     1.0.1
Jinja2                        3.1.3
joblib                        1.3.2
jsonschema                    4.19.2
jsonschema-specifications     2023.7.1
jupyter_client                8.6.0
jupyter_core                  5.5.0
jupyterlab-pygments           0.2.2
keras                         2.15.0
keyring                       24.3.1
kiwisolver                    1.4.5
lazy_loader                   0.3
lazy-object-proxy             1.6.0
libclang                      18.1.1
llvmlite                      0.42.0
Markdown                      3.4.1
markdown-it-py                2.2.0
MarkupSafe                    2.1.3
matplotlib                    3.8.3
matplotlib-inline             0.1.6
mccabe                        0.7.0
mdurl                         0.1.0
mistune                       2.0.4
ml-dtypes                     0.2.0
more-itertools                10.1.0
msgpack                       1.0.8
msgpack-numpy                 0.4.8
multidict                     6.0.4
mypy-extensions               1.0.0
namex                         0.0.7
nbclient                      0.8.0
nbconvert                     7.10.0
nbformat                      5.9.2
nest-asyncio                  1.6.0
networkx                      3.2.1
numba                         0.59.1
numexpr                       2.8.7
numpy                         1.26.4
numpydoc                      1.5.0
oauthlib                      3.2.2
opencv-python                 4.9.0.80
opt-einsum                    3.3.0
optree                        0.11.0
packaging                     23.2
pandas                        2.2.1
pandocfilters                 1.5.0
parso                         0.8.3
pathspec                      0.10.3
patsy                         0.5.6
pexpect                       4.8.0
pickleshare                   0.7.5
pillow                        10.2.0
pip                           23.3.1
platformdirs                  3.10.0
pluggy                        1.0.0
ply                           3.11
prompt-toolkit                3.0.43
protobuf                      4.24.4
psutil                        5.9.0
ptyprocess                    0.7.0
pure-eval                     0.2.2
py-cpuinfo                    9.0.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycodestyle                   2.11.1
pycparser                     2.21
pydocstyle                    6.3.0
pyflakes                      3.2.0
Pygments                      2.15.1
PyJWT                         2.4.0
pylint                        2.16.2
pylint-venv                   3.0.3
pyls-spyder                   0.4.0
pyOpenSSL                     24.0.0
pyparsing                     3.1.2
PyQt5                         5.15.10
PyQt5-sip                     12.13.0
PyQtWebEngine                 5.15.4
PySocks                       1.7.1
python-dateutil               2.8.2
python-lsp-black              2.0.0
python-lsp-jsonrpc            1.1.2
python-lsp-server             1.10.0
python-slugify                5.0.2
pytoolconfig                  1.2.6
pytz                          2023.3.post1
pyxdg                         0.27
PyYAML                        6.0.1
pyzmq                         25.1.2
QDarkStyle                    3.2.3
qstylizer                     0.2.2
QtAwesome                     1.2.2
qtconsole                     5.5.1
QtPy                          2.4.1
referencing                   0.30.2
requests                      2.31.0
requests-oauthlib             1.3.0
rich                          13.3.5
rope                          1.12.0
rpds-py                       0.10.6
rsa                           4.7.2
Rtree                         1.0.1
ruamel.yaml                   0.18.6
ruamel.yaml.clib              0.2.8
scikit-image                  0.22.0
scikit-learn                  1.4.1.post1
scipy                         1.12.0
SecretStorage                 3.3.1
setuptools                    68.2.2
shapely                       2.0.3
sip                           6.7.12
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.5
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.5.3
spyder-kernels                2.5.1
stack-data                    0.2.0
statsmodels                   0.14.1
tables                        3.9.2
tabulate                      0.9.0
tensorboard                   2.16.2
tensorboard-data-server       0.7.0
tensorflow                    2.15.0
tensorflow_estimator          2.15.0
tensorflow-io-gcs-filesystem  0.36.0
tensorpack                    0.11
termcolor                     2.1.0
text-unidecode                1.3
textdistance                  4.2.1
tf-slim                       1.1.0
threadpoolctl                 3.4.0
three-merge                   0.1.1
tifffile                      2024.2.12
tinycss2                      1.2.1
tomli                         2.0.1
tomlkit                       0.11.1
tornado                       6.3.3
tqdm                          4.66.2
traitlets                     5.7.1
typing_extensions             4.9.0
tzdata                        2024.1
ujson                         5.4.0
Unidecode                     1.2.0
urllib3                       2.1.0
watchdog                      2.1.6
wcwidth                       0.2.5
webencodings                  0.5.1
Werkzeug                      2.2.3
whatthepatch                  1.0.2
wheel                         0.41.2
wrapt                         1.14.1
wurlitzer                     3.0.2
yapf                          0.40.2
yarl                          1.9.3
zipp                          3.17.0

(DLC) hhh@hhh49:~$ python -c 'import tensorflow'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/hhh/Software/Miniconda3/envs/DLC/lib/python3.11/site-packages/tensorflow/__init__.py", line 40, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hhh/Software/Miniconda3/envs/DLC/lib/python3.11/site-packages/tensorflow/python/pywrap_tensorflow.py", line 34, in <module>
    self_check.preload_check()
  File "/home/hhh/Software/Miniconda3/envs/DLC/lib/python3.11/site-packages/tensorflow/python/platform/self_check.py", line 63, in preload_check
    from tensorflow.python.platform import _pywrap_cpu_feature_guard
ImportError: /home/hhh/Software/Miniconda3/envs/DLC/lib/python3.11/site-packages/tensorflow/python/platform/../../libtensorflow_framework.so.2: undefined symbol: _ZTIN6snappy4SinkE

**Comment by tilakrayal** [comment]
@KnSun99,
I tried to install the tensorflow v2.15 with the same specifications & in the same environment(Ubuntu 22.04) and was able to install and execute the tensorflow import without any issue. Kindly find the screenshot for the reference.
Also please try to create a new virtual environment and install the tensorflow according to the compatible tested [configurations](https://www.tensorflow.org/install/source#gpu).

![2 15 GPU](https://github.com/tensorflow/tensorflow/assets/81610181/7ca9f8e2-82c5-4c5f-934c-a63c2ef33930)

**Comment by KnSun99** [comment]
OK，I‘ll try.
But the cuda version required by tf2.15.0 is not in configurations.
![image](https://github.com/tensorflow/tensorflow/assets/123467428/da8530b9-17cf-4f43-b61c-8e51e3f5ad51)

Can you share your pip list and conda list information?

Thanks for your reply!

**Comment by tilakrayal** [comment]
@KnSun99,
I guess you are looking for the other language document which has not been updated for a long time. I will check with the developer team on the same. I request to have a look at this official document for the tested build configurations.
https://www.tensorflow.org/install/source#gpu

Thank you!

**Comment by KnSun99** [comment]
OK.
Thanks for your reply.
