### ISSUE TITLE
could not find valid device for node when call tf.acos

### ISSUE THREAD

**Issue by shiwenou** [tensorflow/tensorflow#64574]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf 2.1

### Custom code

Yes

### OS platform and distribution

win11 10.0.22635

### Python version

3.7.16

### Current behavior?

When I was using tf.abs to process my data, I realized that it wasn't working properly. After my review, I realized that if I input a integer type tensor, an error occurs, tensorflow.python.framework.errors_impl.NotFoundError: could not find valid device for node. 
However,  if I input a tensor of float type, it works fine. 

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
x1 = tf.constant([-1,0,1])
print(tf.acos(x1))
```

### Relevant log output

```shell
raceback (most recent call last):
  File "~\test.py", line 3, in <module>
    print(tf.acos(x1))
  File "~\Anaconda3\envs\tf2.1\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py", line 192, in acos
    _ops.raise_from_not_ok_status(e, name)
  File "~\Anaconda3\envs\tf2.1\lib\site-packages\tensorflow_core\python\framework\ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: Could not find valid device for node.
Node:{{node Acos}}
All kernels registered for op Acos :
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_DOUBLE]
 [Op:Acos]
```

**Comment by Venkat6871** [comment]
Hi **@shiwenou** ,
The tf.acos operation in tensorflow supports float and double data types but not an integer data types. When you pass an integer type tensor to tf.acos, it raises an error because there is no valid device registered for that operation with integer data types.
 Here i am providing [gist](https://colab.sandbox.google.com/gist/Venkat6871/7abac947112d0a06a517fa42562e963e/64574_2-15-v.ipynb) for your reference. Please go through it once.
Thank you!

**Comment by DriverOwen** [comment]
> Hi **@shiwenou** , The tf.acos operation in tensorflow supports float and double data types but not an integer data types. When you pass an integer type tensor to tf.acos, it raises an error because there is no valid device registered for that operation with integer data types. Here i am providing [gist](https://colab.sandbox.google.com/gist/Venkat6871/7abac947112d0a06a517fa42562e963e/64574_2-15-v.ipynb) for your reference. Please go through it once. Thank you!

Thanks for the answer. I found that in higher versions of tf it will warn that abs does not support integer type tensor. It's just that the version I'm using is too low.
Thank you!

**Comment by shiwenou** [comment]
> Hi **@shiwenou** , The tf.acos operation in tensorflow supports float and double data types but not an integer data types. When you pass an integer type tensor to tf.acos, it raises an error because there is no valid device registered for that operation with integer data types. Here i am providing [gist](https://colab.sandbox.google.com/gist/Venkat6871/7abac947112d0a06a517fa42562e963e/64574_2-15-v.ipynb) for your reference. Please go through it once. Thank you!

Thanks for the answer. I found that in higher versions of tf it will warn that abs does not support integer type tensor. It's just that the version I'm using is too low.
Thank you!
