### ISSUE TITLE
cuda autoconf issues for cuda rpm install

### ISSUE THREAD

**Issue by dgmackay** [tensorflow/tensorflow#6459]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
None

### Environment info
Operating System:
Fedora 25

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

Here's the problem.  CUDA is 8.0, and cuDNN is 5.1.5, but that's not necessarily relevant.
If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
1cea4458efe1fc177436a6c04b3f804cc41214d7

2. The output of `bazel version`
Build label: 0.4.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 7 18:47:11 2016 (1481136431)
Build timestamp: 1481136431
Build timestamp as int: 1481136431

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
The problem, such as it is, is that I installed cuda using the rpms provided by Nvidia.  These place cuda under /usr.  The big thing, building from source is that cudnn.h is now under /usr/include/cuda, as is the CUPTI directory.  There may be other differences.

### What other attempted solutions have you tried?
Since I was just trying to build the android demos, I ran configure without configuring cuda.  That let me build the android demos.  The pip install for tensorflow cuda works OK for my host.  It's more of a cosmetic thing since a few symlinks will get past it.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by gunan** [comment]
We only have official support for ubuntu linux distribution.
If you, or anyone else would like to contribute fixes/improvements, we will be happy to review and accept.

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.
