### ISSUE TITLE
interpreter->Invoke(); Segmentation fault in c++ inference

### ISSUE THREAD

**Issue by sangyo1** [tensorflow/tensorflow#64608]
![image](https://github.com/tensorflow/tensorflow/assets/57959053/aaf7cf89-8a75-41f5-ad5f-2e902120e89b)
![image](https://github.com/tensorflow/tensorflow/assets/57959053/2c2df8d7-67fe-492f-a8c2-d80f0cf95139)
I am trying to deploy own object detection model in c++.
Once I run the code I am kept getting segmentation fault.
seems like `cerr << memcpy(interpreter->typed_input_tensor<uchar>(0), image.data, image.total() * image.elemSize())<< endl;` print out 0x7fff8c2fe580
However  it doesn't print 5 which is having problem from interpreter->Invoke()
This is what I am getting on debugger
`#4  0x00007ffff7cda369 in tflite::optimized_ops::Conv(tflite::ConvParams const&, tflite::RuntimeShape const&, unsigned char const*, tflite::RuntimeShape const&, unsigned char const*, tflite::RuntimeShape const&, int const*, tflite::RuntimeShape const&, unsigned char*, tflite::RuntimeShape const&, unsigned char*, tflite::CpuBackendContext*) ()`

`#5  0x00007ffff7cdabc9 in void tflite::ops::builtin::conv::EvalQuantized<(tflite::ops::builtin::conv::KernelType)2>(TfLiteContext*, TfLiteNode*, TfLiteConvParams*, tflite::ops::builtin::conv::OpData*, TfLiteTensor*, TfLiteTensor*, TfLiteTensor*, TfLiteTensor*, TfLiteTensor*, TfLiteTensor*) () `

I am getting stuck and I am not sure how to fix this problem

**Comment by pkgoogle** [comment]
Hi @sangyo1, can you please share the file or code snippets/text instead, Also please include your steps to compile and execute. Thanks.
