### ISSUE TITLE
TfLite C/C++ shared library via Bazel

### ISSUE THREAD

**Issue by suyash-narain** [tensorflow/tensorflow#64693]
Hi,

I am trying to build Tensorflowlite v2.14.0 using Bazel and I do obtain libtensorflowlite.so shared library.
I am using Ubuntu OS 22.04
I want to know is it possible for the generated libtensorflowlite.so to contain the c_api symbols as well? Whenever i build tensorflowlite using bazel, i need to specifically build libtensorflowlite.so and libtensorflowlite_c.so to use c_api. 
I though libtensorflowlite.so should contain the c_api symbols as well. Is it possible? Is there a way via bazel to include c_api symbols in libtensorflowlite.so instead of generating a separate libtensorflowlite_c.so? 

I think the build using CMAKE generates libtensorflowlite.so containing c_api symbols as well. How to do it via bazel?

thanks

**Comment by suyash-narain** [comment]
Hi @sushreebarsa , the documentation link you mentioned points to cmake build, not bazel. How do i build a combined tf .so file containing both c++ and c symbols using bazel?

**Comment by sushreebarsa** [comment]
@suyash-narain Bazel doesn't directly support creating a single shared library (.so) file containing both C++ and C symbols. To achieve this you can try creating separate libraries for your C++ and C code and linking them together during your main program's build process. Thank you!

**Comment by suyash-narain** [comment]
thanks
