### ISSUE TITLE
Cannot import tensorflow under python

### ISSUE THREAD

**Issue by sunformoon** [tensorflow/tensorflow#647]
Hi all, I first successfully installed the tensorflow following the instructions of "Pip Installation". However, I couldn't import tensorflow in Python. Thanks a lot!!

The error comes like this:

zhuotun@sunformoon:~$ python
Python 2.7.11 |Anaconda 2.4.1 (64-bit)| (default, Dec  6 2015, 18:08:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tensorflow

I double check that I have installed successfully the tensorflow by re-installing the tensorflow as following:

zhuotun@sunformoon:~$ sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl
[sudo] password for zhuotun: 
Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl
  Downloading tensorflow-0.6.0-cp27-none-linux_x86_64.whl (11.4MB): 11.4MB downloaded
Requirement already up-to-date: six>=1.10.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow==0.6.0)
Requirement already up-to-date: protobuf==3.0.0a3 in /usr/local/lib/python2.7/dist-packages (from tensorflow==0.6.0)
Requirement already up-to-date: wheel in /usr/local/lib/python2.7/dist-packages (from tensorflow==0.6.0)
Requirement already up-to-date: numpy>=1.8.2 in /usr/local/lib/python2.7/dist-packages (from tensorflow==0.6.0)
Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages (from protobuf==3.0.0a3->tensorflow==0.6.0)
Installing collected packages: tensorflow
Successfully installed tensorflow

**Comment by mrry** [comment]
It looks like this is an Anaconda issue. From what I can tell, the recommended way to install using Anaconda is to do the following:

    $ pip install virtualenv
    $ conda create --name=tensorflow_env python=2.7
    $ source activate tensorenv
    $ pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp34-none-linux_x86_64.whl

**Comment by sunformoon** [comment]
Hi Derek,

Thanks a lot for your reply.

Based on your suggestion, I successfully installed a virtualenv of tensorflow using the following:

$ conda install virtualenv # suggested by the output of terminal not using pip install
$ conda create --name=tensorflow_env python=2.7
$ source activate tensorflow_env
$ pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl   # the code you provided is for the python 3

Then, I tested the installation using  the mnist demo. It worked.

**Comment by mrry** [comment]
Glad to hear it worked! One minor suggestion: sorry for the wrong link, but you should probably install from the following link to get the latest (0.6.0) version of TensorFlow:

https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl

**Comment by osdf** [comment]
Just to add to this issue: The original problem existed, because a ```sudo``` was used before ```pip```, with ```pip``` coming from a local anaconda installation. So the ```sudo```'s ```pip``` led to the system wide default ```pip```, which installed tensorflow not into your local anaconda ```site-packages``` and hence it couldn't be found.

**Comment by parthpankajtiwary** [comment]
Hey osdf,

               Your comment proved to be a life saver, I was actually committing the mistake you just mentioned and was trying to access tensorflow from inside the environment. Removed sudo and it worked like magic. Thanks a lot for this comment.

Best,
Parth

**Comment by Svikashini** [comment]
Hi all,

The above given suggestion is fr installing tensorflow in linux under conda environment.  I am trying to install it on windows environment. Kindly help

**Comment by ricoms** [comment]
I had the same problem as sunformoon and mrry's comment solved it.

I followed the online tutorial for TensorFlow ( https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#test-the-tensorflow-installation ) on installing tensorflow on a virtualenv when I got the problem

**Comment by AhmetTavli** [comment]
@mrry

For Ubuntu 64 bit CPU Only :
https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0rc1-cp27-none-linux_x86_64.whl

$ pip install virtualenv
$ conda create --name=tensorflow_env python=2.7
$ source activate tensorenv
$ pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0rc1-cp27-none-linux_x86_64.whl

For more and different binary versions :
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md

**Comment by shravan-rams** [comment]
To me 
i am using python3, but in terminal i was writing like python
that'why it is giving error[ImportError: No module named tensorflow] to me

**Comment by raheel78** [comment]
I have installed tensorflow on my Mac using simple pip command (e.g. pip install tensorflow). Now I am trying to test the setup by invoking python from command line and getting the same error:

```
$ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tensorflow
```

Please help, what might be wrong here?

**Comment by raheel78** [comment]
I just tried doing the same thing by invoking python3 from command line instead of python and now the import tensorflow worked smoothly. What does that mean? Tensorflow has no compatibility with python 2.7 or 2.8??

**Comment by 12343954** [comment]
$ cd /path/to/tensorflow/bin
$ source activate tensorflow
$ python
>>>>import tensorflow as tf
>>>>print(tf.__version__)
1.0.1
done！

**Comment by BIRlz** [comment]
how can i use tensorflow in pypy?  help!!!

**Comment by heeramani** [comment]
@AhmetTavli 
I have following issue.
Collecting virtualenv
Exception:
Traceback (most recent call last):
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 390, in send
    conn = self.get_connection(request.url, proxies)
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 290, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 184, in proxy_manager_for
    **proxy_kwargs
  File "/home/heeramani/anaconda2/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 43, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")
InvalidSchema: Missing dependencies for SOCKS support.

**Comment by heeramani** [comment]
@AhmetTavli 
followed your procedure
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tensorflow

**Comment by bwanglzu** [comment]
In case of you've validated tensorflow was corrected installed with terminal, while this error triggered in Ipython notebook, their might be a difference between your local python and ipython version, try this:
```
# in terminal
import sys
print (sys.version)
# in my case output is 2.7.9
# in notebook
import sys
print (sys.version)
# in my case output is 2.7.10
```
To solve, look at ![this](https://stackoverflow.com/questions/9386048/ipython-reads-wrong-python-version).

**Comment by HRadmard** [comment]
I solve the problem by following steps (in Windows) this fix the problem in pycharm:
1- Run Anaconda prompt
2- Activate root (>activate root)
3- pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.2.1-cp35-cp35m-win_amd64.whl
Finish!

**Comment by askari01** [comment]
I am using mac,
I have tensorflow being shown at `pip3 show tensorflow` but when I try to compile a .py file it says 

> `ModuleNotFoundError: No module named 'tensorflow'`

**Comment by ebonat** [comment]
I updated tensorflow from 1.1.0 to 1.3.0 using the wheel file: tensorflow-1.3.0-cp35-cp35m-win_amd64.whl and in the line:

`import tensorflow as tf`

I got the following error:

```
from numpy.core.multiarray import c_einsum
ImportError: cannot import name 'c_einsum'
```

Any help?

**Comment by techbot123** [comment]
Always activate the tensorflow environment (activate tensorflow) in the Anaconda prompt window before using tensorflow.

**Comment by cjcandctr** [comment]
I have the same issue on my windows box. like osdf commented on Feb 2, 2016, I run anaconda prompt as administrator, then system can find the tensorflow I installed. 
BTW, I was using Console2.

**Comment by tali172** [comment]
first step is to ACTIVATE tensorflow
it can be done by  firing these commands  
"cd tensorflow/bin"          
"source activate tensorflow"

and that should do allow you to import tensorflow.

particularly in my case,
next few steps are...

now go to the folder where premade_estimator resides
"cd models/samples/core/get_started/"
now run premade_estimator.py file by typing this command,
"python premade_estimator.py".

WORKED!!
