### ISSUE TITLE
how to use two optimizer in one model

### ISSUE THREAD

**Issue by langzhining** [tensorflow/tensorflow#6470]
I want to build a model that can use different optimizers to train different parts, just like the tf.contrib.learn.DNNLinearCombinedClassifier(), what should I do?
thanks

**Comment by PhoenixDai** [comment]
I think this kind question might be better to be asked on stackoverflow.com but anyway I think something like this should work:

`_, l1 = sess.run([optim1, loss1], feed_dict={input:batch_input})`
`_, l2 = sess.run([optim2, loss2], feed_dict={input:batch_input})`

**Comment by michaelisard** [comment]
Please follow up on [Stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) if this didn't solve your problem.

**Comment by gongbudaizhe** [comment]
One example of using two optimizers in [stackoverflow](https://stackoverflow.com/questions/34945554/how-to-set-layer-wise-learning-rate-in-tensorflow)
