### ISSUE TITLE
Data Structures for Time Series, Vectorized Time Series and real time data processing

### ISSUE THREAD

**Issue by sirinath** [tensorflow/tensorflow#6476]
There are times you want a tensor to be circular along a dimension so new data can be efficiently and quickly appended along this dimension.

**Comment by aselle** [comment]
Could you provide a motivating example of what you want and how it could be used? Depending on what you are indicating, perhaps a TensorArray or queue might fit the bill.

**Comment by sirinath** [comment]
Question arises is not efficient is arrays for one by one shifting. A form of array can be used it the axis was circular.

**Comment by michaelisard** [comment]
Could you give more details of what you want to use it for?

**Comment by sirinath** [comment]
I want to have a n size window in price data. As new data come in I want to update the price histories and signal histories with minimal time. This is one use case.

**Comment by michaelisard** [comment]
It's possible you could use TensorArray for this. Overall though I'm not sure you are going to be happy with the results. It sounds as if what you would like to do is some kind of windowed streaming computation (though you are keeping it quite mysterious). Right now, TensorFlow may not be well suited to that type of computation. For example, if you took the sum of your price data, then adjusted the window, then recomputed the sum, TensorFlow, would recompute the entire sum, whereas you would probably prefer it to simply subtract the entries that were removed from the window, and add the entries that entered the window. I'm not sure what the use cases are where the copy to shift the window in memory would take a large fraction of your processing time, but the downstream computation that was re-executed would be comparatively cheap. Of course I'm sure there are such cases, but without a good sense of them we would find it hard to prioritize support.

I guess if you can motivate the use case we can see if it makes sense to consider a circular extension to TensorArray. CC @ebrevdo.

**Comment by ebrevdo** [comment]
You can currently use a TensorArray with dynamic sizing (it's one of the options) and use .gather to pull out windows, but you may be better off using some other approaches.  Why do you want all of this to happen inside a tensorflow graph?  Will you be creating an op that talks to some service to read off new data, or will you be feeding in the steam via multiple calls to session.run?  TensorArray is only useful in the former approach.

**Comment by ebrevdo** [comment]
Actually sorry,I see you want a circular buffer.  What kind of performance do you need?  Without knowing many more details about the problem and you setup it's impossible to help.

**Comment by sirinath** [comment]
Yes. It is windowed streaming with efficient transfer between structures.

**Comment by sirinath** [comment]
>  For example, if you took the sum of your price data, then adjusted the window, then recomputed the sum, TensorFlow, would recompute the entire sum, whereas you would probably prefer it to simply subtract the entries that were removed from the window, and add the entries that entered the window.

I did not have this in mind then I opened this issue but it is a good suggestion which will be useful to me also hence I opened: https://github.com/tensorflow/tensorflow/issues/6690

**Comment by michaelisard** [comment]
I think this is a really interesting problem. In particular, I think it would be cool to combine the automatically-incrementalized differential dataflow in [Naiad](http://sigops.org/sosp/sosp13/papers/p439-murray.pdf) with automatic differentiation of the kind that TensorFlow does. However, this would be a major rewrite of a lot of TensorFlow, which is not currently architected for low-latency updates. As such, it's really out of scope for the GitHub issues forum.

I will close this issue and #6690 but if you are interested in pursuing this kind of research out of the main TensorFlow branch please send me email at misard@google.com.

**Comment by yaroslavvb** [comment]
@sirinath btw, CPU kernel launch is about 1 microsecond so it seems hard to get to <1 usec with TF
