### ISSUE TITLE
Sub Matrices, Partitioned Matrices and composite matrices through view on undeling data

### ISSUE THREAD

**Issue by sirinath** [tensorflow/tensorflow#6477]
There are times you want to address portions of a vector or matrix separately and also combine matrices and vectors to form new matrices. Essentially these matrices would be  view on the original data.

E.g.

Concatenate 2 matrices to create a view
Sub current matrix into smaller n * n matrices returning view on the sub matrices

**Comment by michaelisard** [comment]
I'm not sure what you are asking for. I think that the cases you mention are covered in the language and documented under [slicing and joining](https://www.tensorflow.org/api_docs/python/array_ops/slicing_and_joining). Are there particular cases you have run into where the performance is bad?

**Comment by sirinath** [comment]
Documentation is not clear if updates are propagated to the parent structure. Any operation on the sub matrix should be reflected in the main.

**Comment by michaelisard** [comment]
In general, most TensorFlow Ops act functionally, so you don't expect an operation on a slice to have a side effect on some other tensor that isn't expressed via a dataflow edge. The exception of course is variables, and there are sparse update operations for variables. I think TensorArray may also be relevant to your question, depending on what you're trying to achieve. @ebrevdo has the most context on TensorArray and the future plans for updating partial state.

**Comment by ebrevdo** [comment]
We don't create views via concatenate or most slicing ops because all Tensors must be memory aligned contiguous memory blocks.  In some cases, e.g. when a slice ends up being memory aligned by happy about, it is a view to the original memory location and no copy is made.

Note that whenever possible, a Tensor is itself a view (a reference)... operations that don't require copies, like tf.identity on the same device as the input, and some slicing ops, do not perform a copy but instead increment a reference counter to some memory location.

**Comment by ebrevdo** [comment]
TensorArray carries a list of Tensors inside it, so it may be considered a view... But any attempt to read it multiple Tensors, i.e. via the gather method, necessarily performs a copy for the reasons I gave above.

**Comment by sirinath** [comment]
Can it be made explicit:

 - update to a view will update other data structures (one copy of data)
 - update to view will only update data of the data structure (copy on write)

**Comment by ebrevdo** [comment]
We do not allow in place updates of anything but Variables because this
breaks functional flow and makes it impossible to correctly calculate
gradients.  In place operations on variables have no gradients partly
because of this.
