### ISSUE TITLE
Generating Images with BigGAN -- demo in docs no longer compatible with tensorflow (hub?)

### ISSUE THREAD

**Issue by janeon** [tensorflow/tensorflow#64810]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 1.7.0

### Custom code

No

### Python version

3.7-11

### Current behavior?

When first running demo in docs, the following bug was encountered when running cell under section: Load a BigGAN generator module from TF Hub

`AttributeError: module 'tensorflow_hub' has no attribute 'Module'`

Following [Johnny Tang's solution](https://stackoverflow.com/questions/78059929/module-tensorflow-hub-has-no-attribute-module) to change `hub.Module` to `hub.load`, the below error is met:

`AttributeError: 'AutoTrackable' object has no attribute 'get_input_info_dict'`

This persists after trying multiple versions of tf, tensorflow_hub as well as Python

### Standalone code to reproduce the issue

```shell
The demo notebook: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/hub/tutorials/biggan_generation_with_tf_hub.ipynb
```

### Relevant log output

```shell
AttributeError: 'AutoTrackable' object has no attribute 'get_input_info_dict'
```

**Comment by tilakrayal** [comment]
@janeon,
The model Generating Images with BigGAN which you are trying to execute is compatible with the 1.x version. There are multiple changes that happened from 1.x to 2.x and also this is related to tf-hub. 
Please try to connect with the tf-hub repo for the quick solution. 
https://github.com/tensorflow/hub/issues
Thank you!
