### ISSUE TITLE
Please update seq2seq tutorial on the Tensorflow website

### ISSUE THREAD

**Issue by suryabhupa** [tensorflow/tensorflow#6483]
It seems like the seq2seq.py library has been deprecated, and it would be nice to know where the new code, and if the tutorial could point to it.

**Comment by JackJiang1989** [comment]
Along with below files related with rnn is all gone...
'tensorflow/tensorflow/models'
'tensorflow/tensorflow/python/ops/seq2seq.py'
'tensorflow/tensorflow/python/ops/rnn_cell.py'
Why we delete it?

**Comment by michaelisard** [comment]
@xmbrst should the documentation show where these have moved to?

**Comment by suryabhupa** [comment]
Is there a reason for moving all of the seq2seq code to legacy?

**Comment by myaooo** [comment]
It seems like they are moved to contrib due to the reason mentioned in this [#4437](https://github.com/tensorflow/tensorflow/issues/4437)

**Comment by hunkim** [comment]
So, we will have new seq2seq code in tf.nn?

**Comment by Denisolt** [comment]
Is there any update on this issue?

**Comment by RylanSchaeffer** [comment]
I'd like to know whether there's any update on this issue as well.

**Comment by a7744hsc** [comment]
I also believe a official demo for the new seq2seq api is very valuable even though there are already some 3rd party tutorials.

**Comment by nave01314** [comment]
@a7744hsc Can you link some of the 3rd party tutorials?

**Comment by a7744hsc** [comment]
@nave01314 may be [this](https://github.com/ematvey/tensorflow-seq2seq-tutorials) will be helpful.

**Comment by dr4b** [comment]
BTW, the new seq2seq tutorial is living on a separate part of the Tensorflow github repo now:
https://github.com/tensorflow/nmt

We've also put the seq2seq.py back up in a legacy section.

So, I think I'm closing out this bug.
