### ISSUE TITLE
poetry can't find the right installation candidate of tensorflow with python 3.11

### ISSUE THREAD

**Issue by SergeyHein** [tensorflow/tensorflow#64847]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.15.0.post1)

### Custom code

No

### OS platform and distribution

Windows 11

### Python version

3.11

### Current behavior?

[tool.poetry]
name = "test"
version = "0.1.0"
description = "test"
authors = ["test"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"

[tool.poetry.group.dev.dependencies]
black = "^23.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

### Standalone code to reproduce the issue

```shell
(test-py3.11) root@a634e1891f96:/data/test# poetry add tensorflow
```

### Relevant log output

```shell
Using version ^2.15.0.post1 for tensorflow

Updating dependencies
Resolving dependencies... (1.3s)

Because no versions of tensorflow match >2.15.0.post1,<3.0.0
 and tensorflow (2.15.0.post1) depends on tensorflow-intel (2.15.0.post1), tensorflow (>=2.15.0.post1,<3.0.0) requires tensorflow-intel (2.15.0.post1).
So, because no versions of tensorflow-intel match 2.15.0.post1
 and test depends on tensorflow (^2.15.0.post1), version solving failed.
```

**Comment by SuryanarayanaY** [comment]
Hi @SergeyHein ,

Could you please try with TF 2.16.1 which is latest release and update us the outcome. This may be due to the Windows OS. On Windows GPU package won't be supported for `TF>= 2.11v` onwards. You may test with the CPU package `tensorflow_cpu==2.15.0.post1` and let us know the outcome. For GPU package you can install WSL2 and use it. Please refer more details [here](https://www.tensorflow.org/install/pip#windows-native).

Thanks!

**Comment by primski** [comment]
This still doesn't work 


```
[project]
name = "tf-001"
version = "0.1.0"
description = ""
authors = [
    {name = "Me"}
]
readme = "README.md"
requires-python = ">=3.11"

[tool.poetry.dependencies]
python = "~3.11"
tensorflow = "*"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

```


```
  - Installing tensorflow (2.18.0): Failed

  RuntimeError

  Unable to find installation candidates for tensorflow (2.18.0)

  at ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/installation/chooser.py:86 in choose_for
       82│ 
       83│             links.append(link)
       84│ 
       85│         if not links:
    →  86│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       87│ 
       88│         # Get the best link
       89│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       90│ 

Cannot install tensorflow.
```

```
$ poetry --version 
Poetry (version 2.0.0)
```


So how do I install this ?
