### ISSUE TITLE
`SystemError` in `tf.constant` when `dtype` is `tf.uint64` and `value` is nagetive.

### ISSUE THREAD

**Issue by xl1043237213** [tensorflow/tensorflow#64846]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current behavior?

I know that negative number is an unexpected input, but when the `dtype` is `tf.uint32` and `tf.uint64`,`tf.constant` can map negative number to the corresponding unsigned integer. In fact,`tf.uint32` does exactly this.
Taking `tf.constant(-10, dtype=tf.uint64)` as an example, in eager mode, this API will trigger a `SystemError` error when it is called for the first time, but subsequent calls will no longer trigger the error. I think it is a bug.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/17EtoIjT5Ml7FOQnSh5PIxMcVQFB_eDNF#scrollTo=UBwqMQNy4OHb
```

### Relevant log output

```shell
SystemError: <class 'tensorflow.python.framework.ops.EagerTensor'> returned a result with an exception set
```

**Comment by sushreebarsa** [comment]
@xl1043237213  tf_value = tf.constant(-10, dtype=tf.uint64) tries to create a constant tensor named tf_value with the value -10 and data type tf.uint64. However, tf.uint64 can only represent non-negative integers. 
Could you please ensure you only provide non-negative values when using tf.constant with unsigned integer dtypes.
Thank you!

**Comment by xl1043237213** [comment]
Thanks for your response. :)
`tf_value = tf.constant(-10, dtype=tf.uint64)` triggers `SystemError` but `tf_value = tf.constant(-10, dtype=tf.uint32)` does not. I think it's a matter of insufficient processing of boundary inputs. If `value` of `tf.constant` must be a non-negative integer when using with unsigned integer dtypes, I think `tf.constant` should trigger `ValueError` when `value`  is a negative integer.

**Comment by sushreebarsa** [comment]
@xl1043237213  You are right about the expected behavior. Could you explicitly check the value before passing it to tf.constant. You can use an if statement or a function like tf.math.greater_equal to ensure the value is non-negative. In the future TensorFlow versions will address this behavior and provide a more informative error message.
Thank you!

**Comment by xl1043237213** [comment]
Thanks. I got it.

**Comment by sushreebarsa** [comment]
@xl1043237213 Could you please let us know if we can move this issue to closed status?
Thank you!

**Comment by xl1043237213** [comment]
Yes, I hope tensorflow will fix the issue soon.😊 I will close this issue.
