### ISSUE TITLE
Windows: cannot compile using cmake 3.7.1 generator

### ISSUE THREAD

**Issue by KhabarlakKonstantin** [tensorflow/tensorflow#6486]
Hello

If I use cmake 3.7.1 generator, I cannot compile tensorflow on Windows with Visual Studio
I get the following error message during tf_core_gpu_kernels project:

`nvcc fatal   : Stray '"' character
30>
30>  CMake Error at tf_core_gpu_kernels_generated_adjust_contrast_op_gpu.cu.cc.obj.Release.cmake:222 (message):
30>    Error generating
30>    C:/libs/tensorflow/tensorflow/contrib/cmake/build/CMakeFiles/tf_core_gpu_kernels.dir/__/__/core/kernels/Release/tf_core_gpu_kernels_generated_adjust_contrast_op_gpu.cu.cc.obj`

If I try to regenerate project using cmake 3.6.3, everything compiles just fine

I was trying to modify CMakeLists.txt, but still no luck

Additional info:
Windows 10
Visual Studio 2015
GPU is enabled, CUDA 8.0

**Comment by Carmezim** [comment]
To build TensorFlow from source using CMake as the [pre-requisites specify](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md#pre-requisites) you need versions 3.5 up to 3.6.

**Comment by gunan** [comment]
Correct. the failures with 3.7.1 are known, and unfortunately we have no workaround apart from downgrading cmake.
