### ISSUE TITLE
Error when trying to run lstm example of ptb

### ISSUE THREAD

**Issue by shakacs** [tensorflow/tensorflow#6489]
I was stuck at here when trying to run ptb_word_lm under ubuntu 16 and tensorflow master branch. Any advice would be very much appreciated.  

The exception said:
Epoch: 1 Learning rate: 1.000
Traceback (most recent call last):
  File "/home/****/.local/lib/python3.5/site-packages/tensorflow/python/training/supervisor.py", line 964, in managed_session
    yield sess
  File "ptb_word_lm.py", line 357, in main
    verbose=True)
  File "ptb_word_lm.py", line 298, in run_epoch
    return np.exp(costs / iters)
ZeroDivisionError: float division by zero

**Comment by shakacs** [comment]
ok，i figured out that it seems the data was not imported correctly due to the misuse of zip function in _build_vocab of reader.py under python 3.5. But after i fixed the problem, the program throwed another exception said: logits and labels must have the same first dimension, got logits shape [400,10000] and labels shape [420]....

**Comment by shakacs** [comment]
finally, the problem has been fixed. the point is i changed strided_slice into sclice in ready.py.add an stride just fix the problem.

**Comment by ay27** [comment]
@shakacs Could you please give a more clear solution to solve the ZeroDivisionError? It's still error in April 2018.
