### ISSUE TITLE
Weird concat_v2 behavior with negative axis

### ISSUE THREAD

**Issue by ethereon** [tensorflow/tensorflow#6490]
This:
```python
rudolph = tf.zeros((5, 2))
prancer = tf.zeros((5, 2))
comet = tf.concat_v2([rudolph, prancer], axis=-1)

print('Tensor shape: {}'.format(comet.get_shape()))
print('Evaluated shape: {}'.format(comet.eval().shape))
```

Produces:

```
Tensor shape: (5, 4, 5, 2)
Evaluated shape: (5, 4)
```

Tested on tensorflow version `0.12.0`

**Comment by artcg** [comment]
Nice festive example! Probably concat_v2 should follow the convention in numpy wherein the negative axis wraps around the dimensions

**Comment by annarev** [comment]
This should be fixed in nightly build by this commit: https://github.com/tensorflow/tensorflow/commit/8940018192090c072ad50b81b36969d71ffb2c21

You can either use the nightly build or wait for next release.
