### ISSUE TITLE
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

### ISSUE THREAD

**Issue by MDENDAN** [tensorflow/tensorflow#64926]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 1.14

### Custom code

Yes

### OS platform and distribution

Windows 11

### Python version

3.6

### CUDA/cuDNN version

cudatoolkit=10.1

### GPU model and memory

Nvidia rtx 3050 4gb

### Current behavior?

I created a new env using conda with python version 3.6 using command: conda create -n myenv -c conda-forge --strict-channel-priority python=3.6
Next I activate the environment and install tensorflow-gpu=1.14 and cudatoolkit=10.0
On trying to import tensorflow i am getting meta class conflict error

C:\Users\MD IMRAN\miniconda3\envs\aai\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\MD IMRAN\miniconda3\envs\aai\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\MD IMRAN\miniconda3\envs\aai\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\MD IMRAN\miniconda3\envs\aai\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\MD IMRAN\miniconda3\envs\aai\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\MD IMRAN\miniconda3\envs\aai\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\MD IMRAN\miniconda3\envs\aai\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\MD IMRAN\miniconda3\envs\aai\lib\site-packages\tensorflow\python\__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "C:\Users\MD IMRAN\miniconda3\envs\aai\lib\site-packages\tensorflow\python\framework\framework_lib.py", line 25, in <module>
    from tensorflow.python.framework.ops import Graph
  File "C:\Users\MD IMRAN\miniconda3\envs\aai\lib\site-packages\tensorflow\python\framework\ops.py", line 54, in <module>
    from tensorflow.python.platform import app
  File "C:\Users\MD IMRAN\miniconda3\envs\aai\lib\site-packages\tensorflow\python\platform\app.py", line 23, in <module>
    from absl.app import run as _run
  File "C:\Users\MD IMRAN\miniconda3\envs\aai\lib\site-packages\absl\app.py", line 37, in <module>
    from absl import flags
  File "C:\Users\MD IMRAN\miniconda3\envs\aai\lib\site-packages\absl\flags\__init__.py", line 35, in <module>
    from absl.flags import _argument_parser
  File "C:\Users\MD IMRAN\miniconda3\envs\aai\lib\site-packages\absl\flags\_argument_parser.py", line 82, in <module>
    class ArgumentParser(Generic[_T], metaclass=_ArgumentParserCache):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

### Standalone code to reproduce the issue

```shell
I have explain everything above
```

**Comment by sushreebarsa** [comment]
@MDENDAN TF v1.x is not actively supported so we request you to kindly upgrade to the latest TF version. Please follow the migration document [here](https://www.tensorflow.org/guide/migrate). Thank you!

**Comment by zbisure** [comment]
pip install absl-py==1.1.0
