### ISSUE TITLE
Docker doesn't support GPU for mac OS (doc clarification request)

### ISSUE THREAD

**Issue by eraoul** [tensorflow/tensorflow#6495]
The docs present instructions for installing via Docker on MacOS. GPU support isn't mentioned explicitly, but it seems that GPU (nvidia-docker) can't be supported for MacOS. See here:
https://github.com/NVIDIA/nvidia-docker/issues/175

If I'm right that GPU is a no-go for Docker on Mac OS, I'd like to see this up-front in the documentation (e.g., write "GPU support not possible on MacOS X in Docker") to prevent people from going down the wrong path.

NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by yaroslavvb** [comment]
That link suggests GPU support is not possible in Docker for Mac, would you be willing to send a PR to fix this documentation issue?

**Comment by yongtang** [comment]
The current doc of `Installing TensorFlow on Mac OS X`, see:
https://www.tensorflow.org/install/install_mac
does mention that:
```
Important: Docker currently does not support TensorFlow with GPU support on Mac OS; that is, on Mac OS, Docker only supports TensorFlow with CPU support.
```

I think this issue has already been addressed?

**Comment by wolffg** [comment]
This is a NOTE prominently on the page.  I think we've satisfied this bug.  Thanks!

**Comment by blandman** [comment]
Is the reason for why this cannot be supported known? Now that eGPU works on macOS, this seems like a very good fit for Deep Learning.
