### ISSUE TITLE
Please cherry-pick a73ce1c2ac0a951e46dda8aa2d82a8352233031a to 2.16.1

### ISSUE THREAD

**Issue by xwin** [tensorflow/tensorflow#64959]
Could you please cherry pick this commit that fixes host flatc build for cross compilation.
https://github.com/tensorflow/tensorflow/commit/a73ce1c2ac0a951e46dda8aa2d82a8352233031a
The commit made a while ago but never made it into 2.16 release for some reason.

**Comment by pkgoogle** [comment]
Hi @xwin, apologies, but generally speaking we do not cherry-pick this long after release unless it is an exceptionally critical fix. Please go ahead and use/build against nightly for now, thanks.

**Comment by xwin** [comment]
OK. Thank you for the response.
