### ISSUE TITLE
tensorflow + opencv webcam hangs

### ISSUE THREAD

**Issue by milinddeore** [tensorflow/tensorflow#6496]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
Yes posted on stackoverflow but no help and believe this is an issue to report: http://stackoverflow.com/questions/41276085/tensorflow-opencv-webcam-hangs

### Environment info
Operating System: Environment: MAC machine, running my code inside virtual machine with guest OS: Ubuntu 14.4 LTS.

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
I am compiling openCV within tensorflow workspace under examples. My WORKSPACE and opencv.BUILD file look similar to the one mentioned [here](http://stackoverflow.com/questions/34984290/building-opencv-code-using-bazel) 

My BUILD file for the opencv + tensorflow project looks like following:

```
package(default_visibility = ["//tensorflow:internal"])

licenses(["notice"])  # Apache 2.0

exports_files(["LICENSE"])

cc_binary(
    name = "label_image",
    srcs = [
        "main.cc",
    ],
    linkopts = ["-lm"],
    copts = ["-DWITH_FFMPEG=OFF"],
    deps = [
        "//tensorflow/cc:cc_ops",
        "//tensorflow/core:framework_internal",
        "//tensorflow/core:tensorflow",
        "@opencv//:opencv"
    ],
)

filegroup(
    name = "all_files",
    srcs = glob(
        ["**/*"],
        exclude = [
            "**/METADATA",
            "**/OWNERS",
            "bin/**",
            "gen/**",
        ],
    ),
    visibility = ["//tensorflow:__subpackages__"],
)
```

If i disable tensorflow dependences (and also comment the tensorflow related code). I can see that the webcam is captures properly. like this:

```
deps = [
            #"//tensorflow/cc:cc_ops",
            #"//tensorflow/core:framework_internal",
            #"//tensorflow/core:tensorflow",
            "@opencv//:opencv"
        ],
```

But if i still keep the code commented/uncommented and also keep the tensorflow dependences my webcam hangs at VideoCapture::read()

By default, opencv use FFMPEG codec and i tried enabling and disabling FFMPEG. Can someone please help me why when tensorflow library is compiled in the project makes my openCV read() hangs?

### What other attempted solutions have you tried?
Later, i tried having OpenCV code in c++ and tensorflow in python and integrate them using [embedded python](https://docs.python.org/3.4/extending/embedding.html). This is working fine. 

### Logs or other output that would be helpful
Attached inline.

**Comment by aselle** [comment]
One possibility is that the FFMPEG linked into tensorflow is conflicting with the FFMPEG in OpenCV. If they are different versions, then this is quite likely. You could try to remove the ffmpeg support from the tensorflow build and see if that solves your problem. 

>

**Comment by milinddeore** [comment]
Any quick way to disable FFMPEG from tensorflow?

**Comment by aselle** [comment]
Not off hand you could try commenting out contrib/ffmpeg/BUILD.

**Comment by aselle** [comment]
Closing due to lack of recent activity. We will reopen when additional information becomes available. Thanks!

**Comment by kxhit** [comment]
Hi, I meet the same problem. Is there any solution?
I am using tensorflow r1.4 and opencv3.1 in ubuntu14.04.
As far as I include #include <tensorflow/core/public/session.h> or #include "tensorflow/cc/ops/standard_ops.h" I cannot read image. When I didn include these tensorflow files, I can read frame successfully. Anyone could help me? Thanks a lot!!!
my cpp file:
#include <tensorflow/core/platform/env.h>
//#include <tensorflow/core/public/session.h>
//#include "tensorflow/cc/ops/standard_ops.h"
#include <opencv2/opencv.hpp>
#include
using namespace std;
using namespace tensorflow;

int main()
{
cv::VideoCapture cap;
if(!cap.open("/home/kx/project/RM-dataset/01.avi")){
std::cout<<"cannot open video "<<std::endl;
}
cv::Mat frame;
while(1){
cap>>frame;
if(frame.empty()){
std::cout<<"no frame"<<std::endl;
continue;
}
cv::imshow("frame",frame);
cv::waitKey(0);
}
return 0;
}

my cmake file:

cmake_minimum_required (VERSION 2.8)
project (tf_example)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -std=c++11 -W")
find_package(OpenCV 3.1.0 REQUIRED)
include_directories(
/home/kx/something/tensorflow-r1.4
/home/kx/something/tensorflow-r1.4/tensorflow/bazel-genfiles
/home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/gen/protobuf/include
/home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/gen/host_obj
/home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/gen/proto
/home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/downloads/nsync/public
/home/kx/something/tensorflow-r1.4/tensorflow/contrib/makefile/downloads/eigen
/home/kx/something/tensorflow-r1.4/bazel-out/local-py3-opt/genfiles
${OPENCV_INCLUDE_DIRS}
)

add_executable(tf_test tf_test.cpp)
target_link_libraries(tf_test
/home/kx/something/tensorflow-r1.4/bazel-bin/tensorflow/libtensorflow_cc.so
/home/kx/something/tensorflow-r1.4/bazel-bin/tensorflow/libtensorflow_framework.so
${OpenCV_LIBS}
)
