### ISSUE TITLE
tf.linalg.cross convert to tflite

### ISSUE THREAD

**Issue by MinaBabahaji-ML** [tensorflow/tensorflow#65018]
### 1. System information

- Macos
- TensorFlow installation 2.11
- Pip package
 

### 2. Problem summary:

I have a deep learning model with  `tf.linalg.cross` operation. I am having problem with converting it to tflite version. Is there a possibility of supporting this operation?

**Comment by tilakrayal** [comment]
@MinaBabahaji-ML,
Could you please provide a simple standalone code to reproduce the reported behavior and would help us to investigate further. Thank you!
