### ISSUE TITLE
Feature Request: Gradient for SVD op

### ISSUE THREAD

**Issue by kstant0725** [tensorflow/tensorflow#6503]
The gradient for the SVD op would be very useful so that it could be used in networks and cost functions.  Currently when trying to use SVD I get the follow:

LookupError: No gradient defined for operation 'Svd' (op type: Svd)

So my request is for the gradient for the SVD op

**Comment by yaroslavvb** [comment]
the algorithm is in section 3.2 of [An extended collection of matrix derivative results
for forward and reverse mode algorithmic
differentiation](https://people.maths.ox.ac.uk/gilesm/files/NA-08-01.pdf)

**Comment by aselle** [comment]
We are currently working on this internally and I've heard it may be close. @rmlarsen knows more.

**Comment by ddetone** [comment]
@aselle @rmlarsen Any update on this?

**Comment by rmlarsen** [comment]
As mentioned, this underway internally. I believe both the person working on it and I are just back from vacation. I assume this will be available within the coming month.

**Comment by ddetone** [comment]
Hi @rmlarsen, I am looking through the `rc-v1.0` and I don't see the `SvdGrad` op registered [here](https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/core/ops/linalg_ops.cc). Is there somewhere else I should look for it?

**Comment by satyam-cyc** [comment]
Yes, this would help experiment with spectral methods. @rmlarsen Is this still in active development ?

**Comment by shariharan99** [comment]
Is there any update on this? It would be super useful for our work !

**Comment by shariharan99** [comment]
@rmlarsen what is the update on this ?

**Comment by cdiwork** [comment]
There is a current implementation already but it is not yet complete. I was busy with other projects but I will try to come back to this next week.

**Comment by jjough** [comment]
@cdiwork would also be v. interested in this.

**Comment by jjough** [comment]
@cdiwork actually happy to help if there's much more to do. I'm looking for a numerically stable gradient for the pseudoinverse, and this would completely solve my problem.

**Comment by mlhengin** [comment]
Hello,
Any news on this features? Would be very helpful to me too.

**Comment by jjough** [comment]
@cdiwork @rmlarsen @aselle hey fellas, any update on this feature?

**Comment by kstant0725** [comment]
Hello,
I was also wondering if there was any progress on this?

**Comment by schmiflo** [comment]
Would be great to have this functionality.

**Comment by kofd** [comment]
We might be able to create a differentiable op using this, though its not exactly efficient:

```python
def svd(A, compute_uv=True, name=None):
    # since dA = dUSVt + UdSVt + USdVt
    # we can simply recompute each matrix using A = USVt
    # while blocking gradients to the original op.
    _, M, N = A.get_shape().as_list()
    P = min(M, N)
    S0, U0, V0 = map(tf.stop_gradient, tf.svd(A, full_matrices=True, name=name))
    # A = USVt
    # S = inv(U) A inv(Vt)
    S = tf.batch_matmul(tf.matrix_inverse(U0), tf.batch_matmul(A, tf.matrix_inverse(V0)))
    S = tf.matrix_diag_part(S)
    if not compute_uv:
        return S
    # U = A inv(SVt)
    Sv = tf.pad(tf.expand_dims(S0, 2), [[0, 0], [0, N-P], [0, 0]])
    SVTi = tf.matrix_inverse(Sv * tf.transpose(V0, (0,2,1)))
    U = tf.batch_matmul(A, SVTi)
    U = U[:, :M, :P]
    # Vt = inv(US) A
    Su = tf.pad(tf.expand_dims(S0, 1), [[0, 0], [0, 0], [0, M-P]])
    V = tf.transpose(tf.batch_matmul(tf.matrix_inverse(Su * U0), A), (0,2,1))
    V = V[:, :N, :P]
    return S, U, V
```

**Comment by kofd** [comment]
```python
def svd(A, full_matrices=False, compute_uv=True, name=None):
  # since dA = dUSVt + UdSVt + USdVt
  # we can simply recompute each matrix using A = USVt
  # while blocking gradients to the original op.
  _, M, N = A.get_shape().as_list()
  P = min(M, N)
  S0, U0, V0 = map(tf.stop_gradient, tf.svd(A, full_matrices=True, name=name))
  Ui, Vti = map(tf.matrix_inverse, [U0, tf.transpose(V0, (0, 2, 1))])
  # A = USVt
  # S = UiAVti
  S = tf.matmul(Ui, tf.matmul(A, Vti))
  S = tf.matrix_diag_part(S)
  if not compute_uv:
    return S
  Si = tf.pad(tf.matrix_diag(1/S0), [[0,0], [0,n-p], [0,m-p]])
  # U = AVtiSi
  U = tf.matmul(A, tf.matmul(Vti, Si))
  U = U if full_matrices else U[:, :M, :P]
  # Vt = SiUiA
  V = tf.transpose(tf.matmul(Si, tf.matmul(Ui, A)), (0, 2, 1))
  V = V if full_matrices else V[:, :N, :P]
  return S, U, V
```

**Comment by Xalos** [comment]
Hello @kofd 

This idea did not pass gradient checks for me. Is it because the orthonormality constraints aren't imposed? Did this work for you? (I tried it on a different framework and coded it up independently).

**Comment by albertpumarola** [comment]
Hi, 
Any news?

**Comment by kcyu2014** [comment]
Hi, I have composed one gradient function based on Matrix-backpropagation paper. Hope it helps.
```python
@tf.RegisterGradient('Svd')
def gradient_svd(op, grad_s, grad_u, grad_v):
    """
    Define the gradient for SVD
    References
        Ionescu, C., et al, Matrix Backpropagation for Deep Networks with Structured Layers
        
    Parameters
    ----------
    op
    grad_s
    grad_u
    grad_v

    Returns
    -------
    """
    s, u, v = op.outputs
    v_t = tf.transpose(v, [0,2,1])

    with tf.name_scope('K'):
        K = get_eigen_K(s, True)
    inner = matrix_symmetric(K * tf.matmul(v_t, grad_v))

    # Create the shape accordingly.
    u_shape = u.get_shape()[1].value
    v_shape = v.get_shape()[1].value

    # Recover the complete S matrices and its gradient
    eye_mat = tf.eye(v_shape, u_shape)
    realS = tf.matmul(tf.reshape(tf.matrix_diag(s), [-1, v_shape]), eye_mat)
    realS = tf.transpose(tf.reshape(realS, [-1, v_shape, u_shape]), [0, 2, 1])

    real_grad_S = tf.matmul(tf.reshape(tf.matrix_diag(grad_s), [-1, v_shape]), eye_mat)
    real_grad_S = tf.transpose(tf.reshape(real_grad_S, [-1, v_shape, u_shape]), [0, 2, 1])

    dxdz = tf.matmul(u, tf.matmul(2 * tf.matmul(realS, inner) + real_grad_S, v_t))
    return dxdz
```

**Comment by kmyid** [comment]
@kcyu2014 Why don't you make a PR?

**Comment by kcyu2014** [comment]
@albertpumarola Sorry I forgot it and now its updated :)

**Comment by smilli** [comment]
+1 would be very useful :) @rmlarsen

**Comment by Branden-Zhang** [comment]
Yes, please add this feature, super helpful for matrix nuclear norm. @rmlarsen

**Comment by Branden-Zhang** [comment]
Have you test the code @kcyu2014 contribute? Is it work? @albertpumarola

**Comment by smilli** [comment]
I tried it and it didn't work for me :/ Can find logs later if it's helpful for people

**Comment by psycharo** [comment]
The implementation by @kcyu2014 does not have gradients for U, only for S and V (those seem to agree with numerical gradients though).

**Comment by LionSR** [comment]
I need this feature badly. Could someone get it done fast?

**Comment by hicham-eyeem** [comment]
Hi, any update about this? I tried the code by @kcyu2014 but it didn't work properly unfortunately.

**Comment by aselle** [comment]
@rmlarsen. Any update?

**Comment by rmlarsen** [comment]
Sorry for the lack of progress on this. I will try to set aside a few days to get this in now. Especially now that we have GPU support for all the linear algebra ops (minus complex SVD), this is a gaping hole.

**Comment by psycharo** [comment]
[here is](https://gist.github.com/psycharo/60f58d5435281bdea8b9d4ee4f6e895b) an implementation that should work for square matrices.

**Comment by hicham-eyeem** [comment]
@psycharo seems to work but sometimes the loss goes to NaN when using svd in the loss (nuclear norm)

**Comment by yaroslavvb** [comment]
@hicham-eyeem -- TensorFlow SVD has some bugs that cause NaNs sometimes -- https://github.com/tensorflow/tensorflow/issues/9234 , you could double check if this is fixed using numpy version

**Comment by hicham-eyeem** [comment]
@yaroslavvb ah ok, thank you for pointing that out and actually even adding some regularisation doesn't help. Do you know the reason why it would give NaNs sometimes?
I guess also we can avoid using SVD by rather using a matrix factorization formulation if it's used in the loss function, since the matrix factorization formulation would require only matmul and transpose ops (+ some constraints that can be linearized with a proximal form)

**Comment by rmlarsen** [comment]
FYI: I believe I have a working version now. I'll send it through internal code review today. Stay tuned.

**Comment by rmlarsen** [comment]
FYI: I have an initial version of this out for review internally.

**Comment by hicham-eyeem** [comment]
@rmlarsen great, thank you, can't wait to try it out :)

**Comment by rmlarsen** [comment]
The code was submitted and should appear on github within a day or so.

**Comment by rmlarsen** [comment]
Let me close this and open a new issue for extending support for more general matrices.

**Comment by rmlarsen** [comment]
@caisq thanks for the quick push!

**Comment by rmlarsen** [comment]
New issue is https://github.com/tensorflow/tensorflow/issues/13641

**Comment by JaeDukSeo** [comment]
@rmlarsen was the formula from https://people.maths.ox.ac.uk/gilesm/files/NA-08-01.pdf used or were there a different formula used?

**Comment by JaeDukSeo** [comment]
> Hi, I have composed one gradient function based on Matrix-backpropagation paper. Hope it helps.
> 
> ```python
> def matrix_symmetric(x):
>     return (x + tf.transpose(x, [0,2,1])) / 2
> 
> def get_eigen_K(x, square=False):
>     """
>     Get K = 1 / (sigma_i - sigma_j) for i != j, 0 otherwise
> 
>     Parameters
>     ----------
>     x : tf.Tensor with shape as [..., dim,]
> 
>     Returns
>     -------
> 
>     """
>     if square:
>         x = tf.square(x)
>     res = tf.expand_dims(x, 1) - tf.expand_dims(x, 2)
>     res += tf.eye(tf.shape(res)[1])
>     res = 1 / res
>     res -= tf.eye(tf.shape(res)[1])
> 
>     # Keep the results clean
>     res = tf.where(tf.is_nan(res), tf.zeros_like(res), res)
>     res = tf.where(tf.is_inf(res), tf.zeros_like(res), res)
>     return res
> 
> @tf.RegisterGradient('Svd')
> def gradient_svd(op, grad_s, grad_u, grad_v):
>     """
>     Define the gradient for SVD
>     References
>         Ionescu, C., et al, Matrix Backpropagation for Deep Networks with Structured Layers
>         
>     Parameters
>     ----------
>     op
>     grad_s
>     grad_u
>     grad_v
> 
>     Returns
>     -------
>     """
>     s, u, v = op.outputs
>     v_t = tf.transpose(v, [0,2,1])
> 
>     with tf.name_scope('K'):
>         K = get_eigen_K(s, True)
>     inner = matrix_symmetric(K * tf.matmul(v_t, grad_v))
> 
>     # Create the shape accordingly.
>     u_shape = u.get_shape()[1].value
>     v_shape = v.get_shape()[1].value
> 
>     # Recover the complete S matrices and its gradient
>     eye_mat = tf.eye(v_shape, u_shape)
>     realS = tf.matmul(tf.reshape(tf.matrix_diag(s), [-1, v_shape]), eye_mat)
>     realS = tf.transpose(tf.reshape(realS, [-1, v_shape, u_shape]), [0, 2, 1])
> 
>     real_grad_S = tf.matmul(tf.reshape(tf.matrix_diag(grad_s), [-1, v_shape]), eye_mat)
>     real_grad_S = tf.transpose(tf.reshape(real_grad_S, [-1, v_shape, u_shape]), [0, 2, 1])
> 
>     dxdz = tf.matmul(u, tf.matmul(2 * tf.matmul(realS, inner) + real_grad_S, v_t))
>     return dxdz
> ```

this is very useful, we are assuming that we don't use the U matrix when we have decomposed the original matrix A into U s V, since we do not calculate the derivative respect to U anywhere.
