### ISSUE TITLE
load_model no longer works with Dot layer in TensorFlow 2.16

### ISSUE THREAD

**Issue by Dobiasd** [tensorflow/tensorflow#65056]
With TensorFlow 2.15.1, the following code works fine:

```python3
from tensorflow.keras.layers import Input, Dot
from tensorflow.keras.models import Model, load_model

input_1 = Input(shape=(2, 3, 4))
input_2 = Input(shape=(2, 3, 4))
x = Dot(axes=(1, 1))([input_1, input_2])
model = Model(inputs=[input_1, input_2], outputs=[x])
model.compile()
model.save('model.keras')

load_model('model.keras')
```

However, with TensorFlow 2.16.1, `load_model` throws an exception:

```
ValueError: A `Dot` layer should be called on a list of 2 inputs. Received: input_shape=[[None, 2, 3, 4], [None, 2, 3, 4]]
```

**Comment by tilakrayal** [comment]
@Dobiasd,
Yes, As you mentioned it was executed with the error on **tensorflow [v2.16](https://colab.research.google.com/gist/tilakrayal/d42cdec73677d9016f79ca69d54cd825/untitled1815.ipynb) & keras 3.1.1**. On tensorflow **v2.15** it was executed without any error. And now it got fixed on **tf-nightly(2.17.0-dev20240403) and keras(3.2.0.dev2024040303)** which will be available in the upcoming releases.
Kindly find the attached [gist](https://colab.research.google.com/gist/tilakrayal/eada8b34ec84ce783f8e3fc69c403254/untitled1813.ipynb) for the reference.

Also there is PR raised for the similar issue in Keras repo which was merged recently.
https://github.com/keras-team/keras/pull/19362

Thank you!

**Comment by Dobiasd** [comment]
Ok, perfect, thank you. 👍

**Comment by tilakrayal** [comment]
@Dobiasd,
As this issue is resolved in tf-nightly, Could you please feel free to move this issue to closed status. Thank you!
