### ISSUE TITLE
Error in `python': free(): invalid pointer: when running example frac.cc op

### ISSUE THREAD

**Issue by nmiculinic** [tensorflow/tensorflow#6506]
Frac.cc as in repo:
```c++
// legal stuff

// An example Op.

#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/op_kernel.h"

using namespace tensorflow;

REGISTER_OP("Fact")
    .Output("fact: string")
    .Doc(R"doc(
Output a fact about factorials.
)doc");

class FactOp : public OpKernel {
 public:
  explicit FactOp(OpKernelConstruction* context) : OpKernel(context) {}

  void Compute(OpKernelContext* context) override {
    // Output a scalar string.
    Tensor* output_tensor = NULL;
    OP_REQUIRES_OK(context,
                   context->allocate_output(0, TensorShape(), &output_tensor));
    auto output = output_tensor->template scalar<string>();

    output() = "0! == 1";
  }
};

REGISTER_KERNEL_BUILDER(Name("Fact").Device(DEVICE_CPU), FactOp);
```

bazel build:
```bazel
load("//tensorflow:tensorflow.bzl", "tf_custom_op_library")

tf_custom_op_library(
    name = "fact.so",
    srcs = ["fact.cc"],
)
```

Test script:
```python
import tensorflow as tf
fact_module = tf.load_op_library('tensorflow/bazel-bin/tensorflow/core/user_ops/fact.so')
```

full core dump: http://pastebin.com/69rLzybC

I'm trying to write tf op. Tf repo is on origin/r0.12 tag

What is going on and how do I fix it/implement my custom op?
Python version 3.5.2
Linux protagonist 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux

**Comment by aselle** [comment]
What distriubtion and version of Linux?

**Comment by nmiculinic** [comment]
Arch Linux, 

```
uname -a
Linux protagonist 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
```

**Comment by aselle** [comment]
and are you trying to load the built dso with a prebuilt tensorflow binary or did you build the tensorflow binary from the same bazel environment as the extension dso?

**Comment by nmiculinic** [comment]
I'm using prebuild binary from pip, ```tf.__version__ == 0.12.0```. Could it be something related to ABI? Since when I installed warp-ctc I had ABI compile problems where I had to put additional flag.

**Comment by aselle** [comment]
I would guess that it is pretty likely. If you were using ubuntu 14 (which is what we build on) I'd guess it would be likely to work. Try building your tensorflow from source on the same machine and see if that resolves the problem. Good luck!

**Comment by nmiculinic** [comment]
Yeah, that fixed it when I rebuild from source. Can I somehow add ABI flag, that is ```-D_GLIBCXX_USE_CXX11_ABI=0``` when compiling using bazel? And then I can test if that's  the issue?

**Comment by aselle** [comment]
I'm not a bazel expert, but the docs seem to indicate this could work. https://bazel.build/versions/master/docs/bazel-user-manual.html
`bazel build --copt "-D_GLIBCXX_USE_CXX11_ABI=1`
maybe?

**Comment by aselle** [comment]
Closing due to lack of recent activity. We will reopen when additional information becomes available. Thanks!
