### ISSUE TITLE
Feature request: Add float16 support for Conv3D, MaxPool3D and AvgPool3D ops

### ISSUE THREAD

**Issue by Warvito** [tensorflow/tensorflow#6507]
Support for `tf.float16 dtype` was recently added ([#1300](https://github.com/tensorflow/tensorflow/issues/1300)) to a bunch of ops. Can we add it for conv3d too, please?

conv3d is important to development of videos and medical images systems. Since both consumes a lot of memory, it would be good to have fp16 support to allow deeper models.

**Comment by michaelisard** [comment]
@benoitsteiner do you know if this is being worked on?

**Comment by dasabir** [comment]
Any update on when this might be available?

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
