### ISSUE TITLE
TensorFlow+Lite+in+Play+Services+issue in

### ISSUE THREAD

**Issue by Youniqueli** [tensorflow/tensorflow#65078]
**System information**
- Android Device information (use `adb shell getprop ro.build.fingerprint`
  if possible):
- TensorFlow Lite in Play Services SDK version (found in `build.gradle`):
- Google Play Services version
  (`Settings` > `Apps` > `Google Play Services` > `App details`):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to or attach code demonstrating
the problem.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by Youniqueli** [comment]
> **System information**
> - Android Device information (use `adb shell getprop ro.build.fingerprint`
>   if possible):__
> - TensorFlow Lite in Play Services SDK version (found in `build.gradle`):
> - Google Play Services version
>   (`Settings` > `Apps` > `Google Play Services` > `App details`):
> 
> **Standalone code to reproduce the issue**
> Provide a reproducible test case that is the bare minimum necessary to generate
> the problem. If possible, please share a link to or attach code demonstrating
> the problem.
> 
> **Any other info / logs**
> Include any logs or source code that would be helpful to diagnose the problem.
> If including tracebacks, please include the full traceback. Large logs and files
> should be attached.

**Comment by Venkat6871** [comment]
Hi **@Youniqueli** ,

We see that the issue [template]( https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyze the issue tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced.

Thank you!
