### ISSUE TITLE
JUCE LNK2001 - LNK2019: UNRESOLVED EXTERNAL SYMBOL

### ISSUE THREAD

**Issue by Ikerlandarech** [tensorflow/tensorflow#65082]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.11

### Custom code

Yes

### Current behavior?

Hey there and thank you for reading this.

I've been trying to work on a VST for my final thesis project which consists of timbre transfer voice to instruments, I've been using JUCE, and all source files are loaded from the Projuicer, the problem I'm facing is those Linker Errors that I think have to do with reading/accessing the Tensorflow files. I have no idea on how to solve it since I tried changing all the "includes" so that filepath were accessible and also tried importing all TF into the Projuicer but then it crashes.
The framework that I'm working with is DDSP-VST from the Magenta Team which uses Tensorflow to perform all the ML operations. The original DDSP code framework is implemented in Python with Tensorflow but for DDSP-VST everything is rewritten in C++ using the JUCE framework and Tensorflow Lite. I'm working with the Projuicer and Visual Studio.
If anyone can help with this I would really appreciate some help, thank u so very much in advance and have a beautiful day whoever is reading this :)

![Captura de pantalla 2024-03-31 175209](https://github.com/tensorflow/tensorflow/assets/91797318/e9400d3b-b8ed-4c54-8184-1a1ccfbbe75e)

### Standalone code to reproduce the issue

```shell
General Problem with headers or accessing the linker files.
```

**Comment by sushreebarsa** [comment]
@Ikerlandarech Could you please try creating a minimal example project outside of your VST that only includes TensorFlow Lite and JUCE to see if the linker errors persist? Please let us know!
Thank you!
