### ISSUE TITLE
How ti make dataset?

### ISSUE THREAD

**Issue by cwh1981** [tensorflow/tensorflow#651]
I have found to make my own dataset.
The example dataset is already bytestream.
 
Can you explain how can I add my image set?

**Comment by cwh1981** [comment]
Title is wrong spell. 
How can I make dataset as bytestream?

**Comment by girving** [comment]
This should be a stackoverflow question rather than a github issue.  Github issues are for bugs or feature requests that should be fixed on the tensorflow side.
