### ISSUE TITLE
Tensorflow0.08+cuda7.5+cudnn v4, GPU is not used as wished

### ISSUE THREAD

**Issue by cardwing** [tensorflow/tensorflow#6510]
I have installed Tensorflow0.08+cuda7.5+cudnn v4 by Anaconda installation. However, when I was training the DDPG network, I found that the speed was rather slow and the computation was mainly done in CPU instead of GPU. Hope someone can help me out.
    Regards,
    Cardwing

**Comment by DollarAkshay** [comment]
You really need to give us some more info. Run a really simple tensor flow program and paste the output here

**Comment by gunan** [comment]
I will close this issue.
Please try installing the latest version of TF (with latest versions of cuda and cudnn).
If you still run into the problem, please file a new issue.
And when filing the issue, please fill out the template.
Otherwise, we will only be able to point you to the docs.
