### ISSUE TITLE
tensorboard fail to load summaries

### ISSUE THREAD

**Issue by nina124** [tensorflow/tensorflow#6515]
Enviroment: Ubuntu14.04
tensorflow installed with
`sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.0-cp27-none-linux_x86_64.whl`

tensorboard fails to load events, even with the tensorflow_root_path/models/image/cifar10/cifar10_train.py.
run `python cifar10_train.py`, [the event file](https://github.com/tensorflow/tensorflow/files/673591/event.zip)

`tensorboard --logdir=/tmp/cifar_train` gives

> I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Starting TensorBoard 39 on port 6006
(You can navigate to http://127.0.1.1:6006)

But tensorboard did not load any summary
![image](https://cloud.githubusercontent.com/assets/6497205/21490461/c543dccc-cc2f-11e6-920b-71e61fa20268.png)

**Comment by jart** [comment]
Does this problem go away if you upgrade to the latest release?

**Comment by nina124** [comment]
Currently not.
Do I need to build from source to upgrade to the latest release?
I am still using the pip install version
`pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.0-cp27-none-linux_x86_64.whl`

**Comment by nina124** [comment]
Solved. Thank you!
