### ISSUE TITLE
no code completion supported in tf0.12.0 ?

### ISSUE THREAD

**Issue by KeithYin** [tensorflow/tensorflow#6517]
when i typed `tf.contrib.rnn.`, there is no code completion choice with pycharm and ipython.are there some soft reload mechanism ?. what should i do to solve this problem.

**Comment by KeithYin** [comment]
when using `from tensorflow.contrib import rnn` , the code completion works correctly

**Comment by jknair** [comment]
having the same issue @KeithYin did you find a solution ?

**Comment by sunnysuhappy** [comment]
pytharm的自动补全问题，楼主怎么解决的啊，看样子是contrib的懒加载导致的，我这两天也发现了这个问题

**Comment by KeithYin** [comment]
@sunnysuhappy@jknair  you can try to import tensorflow.contrib explicitly

**Comment by gutouyu** [comment]
`import tensorflow.contrib as contrib`
and then use like this :
`contrib.layers.xxx`
`contrib.xx`

Pycharm autocomplete will be good then.
