### ISSUE TITLE
A checker is needed for inputs of Conv layers.

### ISSUE THREAD

**Issue by Shuo-Sun20** [tensorflow/tensorflow#65214]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.16

### Custom code

Yes

### OS platform and distribution

WIndows10 & Linux

### Current behavior?

As disscussed in tensorflow/tensorflow#64396, it should be considered as an abnormal input when kernel_size > input_size, while currently the Conv layers will silently generate an unexpected output, therefore maybe a checker is needed here.

The code to reproduce this issue:

```
from keras.layers import Conv2D
import numpy as np

x=np.random.rand(1,2,2,1)
l=Conv2D(1,3,(1,1),'valid','channels_last', [1,1],1, 'linear', True)
print(l(x).shape)
print(l.compute_output_shape(x.shape))
```

In my opinion, this code should not generate an output, a warning or error is expected since the kernel(3x3) is larger than input (2x2).

### Standalone code to reproduce the issue

```shell
from keras.layers import Conv2D
import numpy as np

x=np.random.rand(1,2,2,1)
l=Conv2D(1,3,(1,1),'valid','channels_last', [1,1],1, 'linear', True)
print(l(x).shape)
print(l.compute_output_shape(x.shape))
```

### Relevant log output

```shell
Currently in windows, the output is
(1, 2, 2, 1)
(1, 0, 0, 1)
And in Linux the output is
(1, 0, 0, 1)
(1, 0, 0, 1)

The inconsistant is discussed in tensorflow/tensorflow#64396. This issue is to report the need of checker for abnormal inputs of Conv layers.
```

**Comment by Venkat6871** [comment]
Hi **@Shuo-Sun20** ,

I tried to run your code on colab using TF-nightly and faced the same issue. Please find the [gist ](https://colab.sandbox.google.com/gist/Venkat6871/58720b9ca973bb8a9670b3d00fdd6e52/65214_tf-nightly.ipynb)here for reference.

Thank you!

**Comment by Venkat6871** [comment]
Hi **@Shuo-Sun20** ,
- Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999).

Thank you!
