### ISSUE TITLE
[Bazel CI] Bazel build error: Target '//tensorflow/tools/pip_package:build_pip_package' contains an error with Bazel@HEAD


### ISSUE THREAD

**Issue by sgowroji** [tensorflow/tensorflow#65220]
CI: https://buildkite.com/bazel/bazel-at-head-plus-disabled/builds/2004#018eb729-e4a7-46e0-b68c-4b90fcac20cc

 Platform: Ubuntu

 Logs: 
```
ERROR: [0m/var/lib/buildkite-agent/builds/bk-docker-f8l9/bazel-org-repo-root/tensorflow/tensorflow/python/BUILD:465:27: //tensorflow/python:_pywrap_tfcompile.so: no such attribute 'licenses' in 'cc_shared_library' rule
ERROR: [0m/var/lib/buildkite-agent/builds/bk-docker-f8l9/bazel-org-repo-root/tensorflow/tensorflow/python/BUILD:513:27: //tensorflow/python:_pywrap_py_exception_registry.so: no such attribute 'licenses' in 'cc_shared_library' rule
ERROR: [0m/var/lib/buildkite-agent/builds/bk-docker-f8l9/bazel-org-repo-root/tensorflow/tensorflow/python/BUILD:1189:27: //tensorflow/python:_pywrap_tfe.so: no such attribute 'licenses' in 'cc_shared_library' rule
ERROR: [0m/var/lib/buildkite-agent/builds/bk-docker-f8l9/bazel-org-repo-root/tensorflow/tensorflow/tools/pip_package/BUILD:255:10: Target '//tensorflow/python:distributed_framework_test_lib' contains an error and its package is in error and referenced by '//tensorflow/tools/pip_package:build_pip_package'
ERROR: [0mAnalysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/tensorflow/tensorflow
git reset f12154def538a7093598c870be9dbb374b86bbe3  --hard
export USE_BAZEL_VERSION=3f9d80c35d88a280c2d53682f3d201b4733a3fff
bazel build //tensorflow/tools/pip_package:build_pip_package 
 ``` 
 CC Greenteam @meteorcloudy

**Comment by stamenminkov** [comment]
Having the same error when trying to compile `Tensorflow-2.15.1` with `Bazel-7.2.0` ...

Any ideas?

**Comment by jasonsi1993** [comment]
Encounter the same issue arch is aarch64 Tensorflow-2.17.1 with Bazel-7.2.1

**Comment by belitskiy** [comment]
Tensorflow requires 6.5.0 at the moment:  
https://github.com/tensorflow/tensorflow/blob/dd446b3de1759d64c80b636a8d41ce341782219c/.bazelversion#L1

This will be updated to 7+, but it's not completely trivial.  
In the meantime, using Bazelisk is helpful, which will automatically pick the version set in `.bazelversion`:  
https://github.com/bazelbuild/bazelisk

**Comment by belitskiy** [comment]
Thanks to @learning-to-play, in this case, the problem is likely not Bazel 7 (though that won't work), but the target.  
See https://github.com/tensorflow/tensorflow/issues/63298#issuecomment-1995159235
