### ISSUE TITLE
possible variable typo in "Vector Representations of Words" documentation

### ISSUE THREAD

**Issue by nitaro** [tensorflow/tensorflow#6523]
The variables "training_inputs" and "training_labels" in the section "[https://www.tensorflow.org/tutorials/word2vec/#training_the_model](https://www.tensorflow.org/tutorials/word2vec/#training_the_model)":

```
for inputs, labels in generate_batch(...):
  feed_dict = {training_inputs: inputs, training_labels: labels}
  _, cur_loss = session.run([optimizer, loss], feed_dict=feed_dict)
```

appear to be new per the tutorial text.

Were they supposed to be the previously defined "train_inputs" and "train_labels"?

thanks,

**Comment by dr4b** [comment]
I just fixed this but not sure when it will propagate out to the website or back to GH.  Thanks for reporting.  This is one of the tutorials marked to revisit the entire code sample anyway.
