### ISSUE TITLE
Feature request: Support reference counting on Java Tensor class

### ISSUE THREAD

**Issue by EronWright** [tensorflow/tensorflow#6524]
The `Tensor` class of the new Java library would be more useful and easier to use with built-in reference counting, based on a common interface `RefCounted`.    This would be in lieu of `AutoCloseable`.

I suggest that reference counting follow the Netty approach as described [in the docs](http://netty.io/wiki/reference-counted-objects.html).   A nice aspect is that it simplifies the common case of supplying an input tensor to `Session.Runner::feed()` or to `OperationBuilder::setAttr` (the caller needn't unref the tensor; the callee will unref it).  At the same time, a reference count is of more general utility than `AutoCloseable`.

Please consider applying the idea to `Session` and `Graph` later.

**Comment by asimshankar** [comment]
Discussing this in the pull request thread.
