### ISSUE TITLE
[Java] provide a Maven POM

### ISSUE THREAD

**Issue by EronWright** [tensorflow/tensorflow#6527]
It would be handy to have a POM file for the Java library.

In the short-term, having a POM facilitates local development of Java applications (potentially using other build frameworks).  For example, it makes it possible to install the built library into Maven's local repository:
```
mvn install:install-file \
  -Dfile=bazel-bin/tensorflow/java/libtensorflow.jar \
  -DpomFile=tensorflow/java/pom.xml
```

The POM file should also be useful for eventual publishing of the library.

**Comment by blublinsky** [comment]
Loadable jar at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java is well behind the source, more specifically, it does not include SavedModelBundle class supporting recommended way to restore models. It also will be nice to have an example of its usage
