### ISSUE TITLE
We integrate tensorflow movenet with our webapp, and it stopped working (it worked two weeks ago) with the following error message, what can be the possible reasons and how to fix it?

### ISSUE THREAD

**Issue by TonyL96** [tensorflow/tensorflow#65299]
### Issue type

Others

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

0.0.6

### Custom code

Yes

### Current behavior?

Access to fetch at 'https://www.kaggle.com/models/google/movenet/frameworks/tfJs/variations/singlepose-lightning/versions/4/model.json?tfjs-format=file&tfhub-redirect=true' (redirected from 'https://tfhub.dev/google/tfjs-model/movenet/singlepose/lightning/4/model.json?tfjs-format=file') from origin 'https://ourwebsite.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### Standalone code to reproduce the issue

```shell
It was working normally a few days ago, but today I found that it cannot be used.
```

**Comment by ytsikhlakis** [comment]
We're facing the same issue. An urgent response would be highly appreciated as our code is live

**Comment by felixniemeyer** [comment]
Got the same problem.

Download your model here: 
https://www.kaggle.com/models/google/movenet/tfJs/singlepose-lightning

And provide it from your own server

Make sure you select the right platform and type (tensorflow.js and single lightning in my case).

**Comment by tilakrayal** [comment]
@TonyL96,
Looks like this issue is not related to tensorflow, and also related to tensorflow JS. Could you please raise the request in the respective Tfjs repo for the quick resolution. 
https://github.com/tensorflow/tfjs/issues

Thank you!
