### ISSUE TITLE
Ensemble provides either correct or (the same) incorrect inference results 

### ISSUE THREAD

**Issue by joeyearsley** [tensorflow/tensorflow#65325]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.14

### Custom code

Yes

### Current behavior?

I have an ensemble; I run the models sequentially. It's flaky in the results it returns; sometimes, one model gives the correct result of 0.37. Other times, it gives the incorrect result of 0.30 (never any other value).

I've tried turning on deterministic ops, but I still have this flaky issue; everything else stays the same.

I've tested on an old TitanX, T4 & A100 - this test is always flaky. 

I've tried debugging via the VLOG, but nothing jumps out; the only difference I can spot is for some reason, different cudnn Conv Ops might be chosen (not 100% from the logs).

Are there other suggestions on how to debug this issue? - I understand there might be decimal point changes but this swing is huge.  

### Standalone code to reproduce the issue

```shell
I can't share the models.
```

### Relevant log output

```shell
-
```

**Comment by tilakrayal** [comment]
@joeyearsley,
Please, share colab link or simple standalone code with supporting files to reproduce the issue in our environment.It helps us in localizing the issue faster. Thank you!
