### ISSUE TITLE
tf.keras.utils.plot_model doesn't  work

### ISSUE THREAD

**Issue by Inquisitive-ME** [tensorflow/tensorflow#65331]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.16.1

### Custom code

No

### OS platform and distribution

Linux Ubuntu 22.04

### Python version

3.10

### Current behavior?

It fails to plot the model. This works like many things in tensorflow 2.15 but is broken in tensorflow 2.16.1

"dot" with args ['-Tpng', '/tmp/tmp48b95hyk'] returned code: -6

stdout, stderr:
 b''
b"failed at node 11921[1]\ndot: maze.c:313: chkSgraph: Assertion `np->cells[1]' failed.\n"

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

model = tf.keras.applications.EfficientNetV2B0()
tf.keras.utils.plot_model(model, to_file="EfficientNetV2B0.png", show_shapes=True, show_layer_names=True)
```

### Relevant log output

```shell
"dot" with args ['-Tpng', '/tmp/tmp48b95hyk'] returned code: -6

stdout, stderr:
 b''
b"failed at node 11921[1]\ndot: maze.c:313: chkSgraph: Assertion `np->cells[1]' failed.\n"
```

**Comment by Venkat6871** [comment]
Hi **@Inquisitive-ME** ,
Sorry for the delay, I tried to run your code on colab using TF v2.15 works fine, 2.16.1 and nightly and faced the same issue. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/0e870200a228011b561e9b5b5e510a0e/65331_2-15-2-16-nightly.ipynb) here for reference.

Thank you!

**Comment by Venkat6871** [comment]
Hi **@Inquisitive-ME** ,
-  I think this was resolved in recent tf-nightly. Please check the [gist](https://colab.research.google.com/gist/Venkat6871/56ddc977ca65f0fbe31bc24d97a68fa4/65331_tf-nightly-v.ipynb) here.

Thank you!
