### ISSUE TITLE
file_io.get_matching_files fails if any unrelated (non-matching) sub-directory is non-readable

### ISSUE THREAD

**Issue by albertz** [tensorflow/tensorflow#6537]
Let `filename = "/tmp/mymodel.005"`.

`file_io.get_matching_files(filename)` will raise an exception like

    PermissionDeniedError: /tmp/.xrdp/xrdp-sesman-jjz1ox

for me. I think this is a bug as this is an unrelated (non-matching) directory, so it does not matter and it will anyway not match the `filename`, thus it should not raise an exception.

I get this via `saver.restore(sess=..., save_path=filename)` where `saver = tf.train.Saver(...)`.

**Comment by inflation** [comment]
@albertz The underlying `GetMachingFiles` performs a pattern matching on all files in the directory.

**Comment by albertz** [comment]
Yes I see that it does that (and even for all sub directories) but it shouldn't break on sub directories which do not match anyway.

**Comment by inflation** [comment]
It add all sub folders before doing the match, and the error is thrown when checking if it is a directory.

**Comment by albertz** [comment]
I know. And I say that this should not fail if it does not match the pattern anyway.

**Comment by rohan100jain** [comment]
yup you're right... the directory check shouldn't need to be done on children that don't match the pattern. That check is done for adding stuff to the queues but not for the IsDirectory check. I'll fix this.

**Comment by rohan100jain** [comment]
I believe commit https://github.com/tensorflow/tensorflow/pull/6719/commits/493188ebe0f68ace157bd97453c41e2cb0d642c8 should have fixed this issue. 

Can you verify and make sure things work fine now?
