### ISSUE TITLE
Missing GRPC information on Documentation

### ISSUE THREAD

**Issue by marchezinixd** [tensorflow/tensorflow#6538]
Both the site and the Git does not say that it is necessary to have GRPC installed to run distributed TensorFlow.

**Comment by mrry** [comment]
There is no separate installation step for gRPC when using distributed TensorFlow. It is linked statically into the Python extension `_pywrap_tensorflow.so` (or `_pywrap_tensorflow.pyd`) that is installed as part of the PIP package.
