### ISSUE TITLE
Loading of a model with a Bidirectional LSTM layer no longer working in TensorFlow 2.16.1

### ISSUE THREAD

**Issue by Dobiasd** [tensorflow/tensorflow#65395]
With TensorFlow `2.15.1`, the following code works fine:

```python3
from tensorflow.keras.layers import Input, LSTM, Bidirectional
from tensorflow.keras.models import Model, load_model

inputs = [Input(shape=(17, 4))]
layer = Bidirectional(LSTM(units=4), merge_mode='concat')(inputs[0])
outputs = [layer]
model = Model(inputs=inputs, outputs=outputs)

model.save('model.keras')
load_model('model.keras')
```

But with `2.16.1`, it no longer does:

```
ValueError: A total of 1 objects could not be loaded. Example error message for object <LSTMCell name=lstm_cell, built=True>:

Layer 'lstm_cell' expected 3 variables, but received 0 variables during loading. Expected: ['kernel', 'recurrent_kernel', 'bias']
```

**Comment by JeffOfTheSixPaths** [comment]
For anyone who has this problem, I fixed it by updating to the nightly version from 2.16.1

**Comment by sushreebarsa** [comment]
@Dobiasd Could you try to use model.save('model.h5', save_format='tf') to save the model in TensorFlow SavedModel format as the default model.save might not capture all model components. Please have a look at this gist and let us know if it helps?
Thank you!

**Comment by Dobiasd** [comment]
I tried:

```python3
from tensorflow.keras.layers import Input, LSTM, Bidirectional
from tensorflow.keras.models import Model, load_model

inputs = [Input(shape=(17, 4))]
layer = Bidirectional(LSTM(units=4), merge_mode='concat')(inputs[0])
outputs = [layer]
model = Model(inputs=inputs, outputs=outputs)

model.save('model.h5', save_format='tf')
load_model('model.h5')
```

`model.save('model.h5', save_format='tf')` raises a `ValueError`:

```
  File "h5py/h5d.pyx", line 137, in h5py.h5d.create
ValueError: Unable to synchronously create dataset (name already exists)
```

However, the `model.h5` is written to the disk nonetheless.

But loading it (`load_model('model.h5')`) fails:

```
  File "h5py/h5o.pyx", line 189, in h5py.h5o.open
KeyError: "Unable to synchronously open object (object 'input_layer' doesn't exist)"
```

**Comment by sushreebarsa** [comment]
@Dobiasd Thank you for the response here.
@SuryanarayanaY I was able to replicate the issue reported [here](https://colab.research.google.com/gist/sushreebarsa/3f15df3f6a633a1764539d312f9461ff/65395.ipynb#scrollTo=wBmnOmhoga-D).
Thank you!

**Comment by JuanVargas** [comment]
I am having the same issue. This and other issues have resulted in frustrating experiences  when moving from previous versions of tf into tf 2.15 and TF 2.16, including 2.16.1.

**Comment by JelleKuiper** [comment]
Having same issue with tensorflow==2.16.1 and keras==3.2.0
Is downgrading really the only fix right now?

**Comment by SuryanarayanaY** [comment]
Hi @Dobiasd ,

There is an open issue in Keras repo [# 18913](https://github.com/keras-team/keras/issues/18913) where Keras Team looking into same and expect a fix ASAP. 

Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @Dobiasd ,

Please note that Keras3 supports saving the model in .keras format only as It is now supporting multiple backends like Torch and Jax also.With .keras format this has been working fine in nightly and attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/32329d82fe6c59803da4341022adeb3b/65395_r1.ipynb) for reference.

If you want to save the model in tf format you might need to use model.export("saved_model") instead of model.save().

Please refer the migration guide [here](https://keras.io/guides/migrating_to_keras_3/#saving-a-model-in-the-tf-savedmodel-format).

**Comment by ramakc153** [comment]
So the solution is either using ```model.export()``` when exporting the model or use lower version on tensorflow

what is the difference between using ```model.export()``` and ```model.save()```?

since in keras docs is still suggest to use ```model.save()``` instead of ```model.export()```. since i'm only find it on keras migration guide
