### ISSUE TITLE
better Variable.__repr__

### ISSUE THREAD

**Issue by albertz** [tensorflow/tensorflow#6539]
Right now, I get sth like:

    <tensorflow.python.ops.variables.Variable object at 0x2b9c67daae10>

It would be nice if it would show sth like

    <Variable name="foo" shape=(100,200) dtype="float32">

or so.

**Comment by yaroslavvb** [comment]
Maybe something like this: https://github.com/yaroslavvb/tensorflow/commit/de542371f05148641b33a1dcf4c25cc3c0cdd1c5

**Comment by yaroslavvb** [comment]
@albertz would you like to do a PR to fix this? :)

**Comment by yaroslavvb** [comment]
BTW, PR for such small change is quite easy and you can do it mostly from browser:

First, click "Fork" on github tensorflow page

Then in Terminal:

```
git remote add mine https://github.com/<username>/tensorflow
git remote add tfmain https://github.com/tensorflow/tensorflow.git
git fetch tfmain
git checkout tfmain/master -b bugfix
git push --set_upstream mine

```
Then in bugfix branch on /tensorflow on Github, find file, click "Edit" button, edit file, then click commit, then click "Pull Requests" and select tensorflow/master on left and <username>/tensorflow:bugfix on right

**Comment by iRapha** [comment]
Do you guys mind if I try my hand at it? I'll have a PR soon
