### ISSUE TITLE
CategoryEncoding layer with output_mode count as part of a model no longer working in TensorFlow 2.16.1

### ISSUE THREAD

**Issue by Dobiasd** [tensorflow/tensorflow#65390]
With TensorFlow `2.15.1`, the following code works fine:

```python3
import numpy as np
from tensorflow.keras.layers import Input, CategoryEncoding
from tensorflow.keras.models import Model

inputs = [Input((100,))]

outputs = [CategoryEncoding(1024, output_mode='count', sparse=False)(inputs[0])]

model = Model(inputs=inputs, outputs=outputs)
model.compile(loss='mse', optimizer='adam')

x = np.random.randint(0, 10, (2, 100))
model.predict(x)
```

But with `2.16.1`, it no longer does:

```
TypeError: Exception encountered when calling CategoryEncoding.call().

Value passed to parameter 'indices' has DataType float32 not in list of allowed values: uint8, int8, int32, int64
```

**Comment by tilakrayal** [comment]
@Dobiasd,
Thank you for reporting the issue. Looks like this is breaking with the combination of tensorflow v2.16.1 & Keras 3.0. I also tried with the multiple options but couldn't get out of the error. I request to check with [keras-team/keras](https://github.com/keras-team/keras/issues) for the better solution. Kindly find the [gist](https://colab.research.google.com/gist/tilakrayal/8575222f1d9b6e99df183256a242bb71/untitled1840.ipynb) for the [reference](https://colab.research.google.com/gist/tilakrayal/85b0271a3899913cc34969233cec647c/untitled1841.ipynb). Thank you!

**Comment by Dobiasd** [comment]
Ok, I've submitted the problem to the Keras team: https://github.com/keras-team/keras/issues/19567

**Comment by tilakrayal** [comment]
@Dobiasd,
Could you please feel to move this issue to the closed status, as this is fixed at HEAD and mentioned the [same](https://github.com/keras-team/keras/issues/19567) by the developer. Thank you!
