### ISSUE TITLE
Documentation for RaggedTensors does not match Input layer documentation

### ISSUE THREAD

**Issue by damienwojtowicz** [tensorflow/tensorflow#65399]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.16.1

### Custom code

No

### Current behavior?

Documentation of RaggedTensors in section [TensorFlow APIs > Keras](https://www.tensorflow.org/guide/ragged_tensor#keras) claim the following, and provides an example where argument `ragged=True` is passed to the constructor of a `tf.keras.Input` object:

> Ragged tensors may be passed as inputs to a Keras model by setting ragged=True on [tf.keras.Input](https://www.tensorflow.org/api_docs/python/tf/keras/Input) or [tf.keras.layers.InputLayer](https://www.tensorflow.org/api_docs/python/tf/keras/layers/InputLayer).

However, `ragged` is neither an argument of [`tf.keras.Input`](https://www.tensorflow.org/api_docs/python/tf/keras/Input), [`tf.keras.layers.InputLayer`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/InputLayer), nor any of their parent classes. Their respective documentation does not mention it. Trying to execute the example provided with either TF v. 2.16.1 ir nightly (see the MWE) raises a `TypeError` stating that `ragged` is an unexpected keyword for `Input`.

It is puzzling as several sources on this internet as well as issues of this very repository mention it. As a consequence, it seems that ragged tensors cannot be used within TF at the moment.

### Standalone code to reproduce the issue

```shell
# This is the example provided by the RaggedTensor documentation

import tensorflow as tf
print(tf.version.GIT_VERSION, tf.version.VERSION)

# Task: predict whether each sentence is a question or not.
sentences = tf.constant(
    ['What makes you think she is a witch?',
     'She turned me into a newt.',
     'A newt?',
     'Well, I got better.'])
is_question = tf.constant([True, False, True, False])

# Preprocess the input strings.
hash_buckets = 1000
words = tf.strings.split(sentences, ' ')
hashed_words = tf.strings.to_hash_bucket_fast(words, hash_buckets)

# Build the Keras model.
keras_model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=[None], dtype=tf.int64, ragged=True),
    tf.keras.layers.Embedding(hash_buckets, 16),
    tf.keras.layers.LSTM(32, use_bias=False),
    tf.keras.layers.Dense(32),
    tf.keras.layers.Activation(tf.nn.relu),
    tf.keras.layers.Dense(1)
])

keras_model.compile(loss='binary_crossentropy', optimizer='rmsprop')
keras_model.fit(hashed_words, is_question, epochs=5)
print(keras_model.predict(hashed_words))
```

### Relevant log output

```shell
2024-04-10 12:22:30.701897: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-04-10 12:22:30.733806: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-10 12:22:31.321292: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
v1.12.1-108775-gb453565cae0 2.17.0-dev20240409
Traceback (most recent call last):
  File "/home/dwojtowicz/PycharmProjects/japetus_ml/issue.py", line 19, in <module>
    tf.keras.layers.Input(shape=[None], dtype=tf.int64, ragged=True),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Input() got an unexpected keyword argument 'ragged'
```

**Comment by SuryanarayanaY** [comment]
Please refer [this](https://github.com/keras-team/keras/issues/18467) for more details.
