### ISSUE TITLE
ValueError: Only instances of `keras.Layer` can be added to a Sequential model. " Keras version - 3.5.0"

### ISSUE THREAD

**Issue by Pavun-KumarCH** [tensorflow/tensorflow#65419]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

TensorFlow tf version: 2.16.1

### Custom code

Yes

### Python version

3.11.8

### Current behavior?

Adding TensorFlow Hub KerasLayer to Sequential Model Raises ValueError

I'm not able to run this model with  "keras.Layer`  to a Sequential model"
 as it works in well in google colab.

### Standalone code to reproduce the issue

```shell
CLASSIFIER_URL ="https://tfhub.dev/google/tf2-preview/mobilenet_v2/classification/2"
IMAGE_RES = 224

model = tf.keras.models.Sequential([
            hub.KerasLayer(CLASSIFIER_URL, input_shape=(IMAGE_RES, IMAGE_RES, 3))
           ])
```

### Relevant log output

```shell
ValueError: Only instances of `keras.Layer` can be added to a Sequential model. Received: <tensorflow_hub.keras_layer.KerasLayer object at 0x28ac6d4d0> (of type <class 'tensorflow_hub.keras_layer.KerasLayer'>)
```

**Comment by Pavun-KumarCH** [comment]
After searching i found out that  potential cause of the issue in tensorflow_hub/keras_layer.py

this is issue is occuring only in keras version  > 3.X.X


solution :

# Use Keras 2.
version_fn = getattr(tf.keras, "version", None)
if version_fn and version_fn().startswith("3."):
  import tf_keras as keras
else:
  keras = tf.keras

👉🏻 https://github.com/tensorflow/tensorflow/issues/63849#issuecomment-2002501172

**Comment by Pavun-KumarCH** [comment]
Try to use Keras 2. version 👍🏻


import tensorflow as tf
from tensorflow import keras
print(tf.__version__)
2.16.1

import keras
print(keras.__version__)
3.2.0

import tf_keras
print(tf_keras.__version__)
2.16.0

**Comment by sushreebarsa** [comment]
@Pavun-KumarCH Thank you for your responses here. 
You can continue using Keras 2 or later with a workaround. That is to wrap the TensorFlow Hub layer returned by tf.keras.layers.experimental.load in a keras.Layer object before adding it to your model.

Please let us know if we can move this issue to closed status as it is resolved from your side?

Thank you!
