### ISSUE TITLE
TensorFlow Implementation in MapReduce

### ISSUE THREAD

**Issue by rendi7936** [tensorflow/tensorflow#6546]
Hello guys,

First, i'm sorry if i break the rules. But, i really stuck right now. So, this is my last hope to ask this question.

I just want to ask something. Can i implement TensorFlow in MapReduce Programming Model within Hadoop ?

Yes, i know that TensorFlow can be runned in distributed mode, according this reference https://www.tensorflow.org/versions/r0.11/how_tos/distributed/ . But, it doesn't explain more detail how to use it in MapReduce.

One last thing, can i use TensorFlow to predict something a lot of data ? Because, i only know that TensorFlow can be used to classify similar images.

I'm sorry if my question look dumb. Well, there are many thing in the world that i don't know. So, when i don't know, i will ask a question :smile:
Thanks for your attention

**Comment by asimshankar** [comment]
We try to keep the Github issues focused on bugs and feature requests. Such a question is better suited for [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow). (Hence I'll close this issue)

When asking on stackoverflow, you might want to elaborate on what you need from TensorFlow. For example, do you want to train a model or run inference on a pre-trained model over a large set of examples? (In which case, something like the [Java API](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java) might make it easier to work within the Hadoop ecosystem.)
