### ISSUE TITLE
keep_checkpoint_every_n_hours is ignored

### ISSUE THREAD

**Issue by dennybritz** [tensorflow/tensorflow#6549]
I think that when creating a new saver [`here`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/graph_actions.py#L249), the `keep_checkpoint_every_n_hours` flag from the RunConfig should be passed to it.

**Comment by terrytangyuan** [comment]
Thanks for reporting! I've submitted the fix.
