### ISSUE TITLE
Add bitcast op

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#655]
`bitcast` would be the same as numpy's unwisely named `view`: it would turn a tensor of one POD dtype into any different POD type such that the last dimension's size is compatible, without touching the bits in any way.  Specifically,

    tf.bitcast(x, dtype).shape = x.shape[:-1] + [x.shape[-1] * sizeof(x.dtype) / sizeof(dtype)]

with an error if the division isn't an exact integer.  The most useful case of bitcast is anything to `uint8` or back.

**Comment by ebrevdo** [comment]
Sounds like this may supercede DecodeRaw?

**Comment by girving** [comment]
Is DecodeRaw currently a thing?

**Comment by girving** [comment]
Note: `bitcast` doesn't need to do any copying.

**Comment by girving** [comment]
We could optionally have a flag for whether a dimension should be added (if the new type is smaller) or removed (if the new type is bigger).  Adding / removing dimensions is more natural in most cases.  In fact, maybe it should just be the only way?

**Comment by girving** [comment]
(After the code search:) `DecodeRaw` is pretty different, currently, since it takes a tensor of strings which are separately allocated.  `bitcast` would explicitly not work on string tensors, and would do O(1) work similar to `reshape`.
