### ISSUE TITLE
classify_image.py file not found at tensorflow/models/image/imagenet

### ISSUE THREAD

**Issue by nojvek** [tensorflow/tensorflow#6550]
It seems the tutorials are out of date.

**Comment by wolffg** [comment]
I believe this is fixed; the directory is now listed on this page:

https://www.tensorflow.org/tutorials/image_recognition

references this repo: 

https://github.com/tensorflow/models

and asks you to find classify_image.py:

cd models/tutorials/image/imagenet

which lines up with this: 

https://github.com/tensorflow/models/tree/master/tutorials/image/imagenet

Please reopen or refile if this is in error.  Thanks!

**Comment by esjaca** [comment]
I work in windows, python, tensorflow
clone models from https://github.com/tensorflow/models
and I found classify_image.py in  \ models-master \ tutorials \ image \ imagenet directory

**Comment by ulrischa** [comment]
Where is the file?
