### ISSUE TITLE
Can't restore a partitioned variable

### ISSUE THREAD

**Issue by IgorWang** [tensorflow/tensorflow#6551]
I have a large matrix.

I use bellow method create this variable as number of shards.
```
softmax_w = tf.get_variable("softmax_w", [hps.vocab_size, hps.projected_size],
                            partitioner=tf.fixed_size_partitioner(hps.num_shards, 0))
```
create log:
```
model/softmax_w/part_0:0 (99184, 512) /cpu:0
model/softmax_w/part_1:0 (99184, 512) /cpu:0
model/softmax_w/part_2:0 (99184, 512) /cpu:0
model/softmax_w/part_3:0 (99184, 512) /cpu:0
model/softmax_w/part_4:0 (99184, 512) /cpu:0
model/softmax_w/part_5:0 (99184, 512) /cpu:0
model/softmax_w/part_6:0 (99183, 512) /cpu:0
model/softmax_w/part_7:0 (99183, 512) /cpu:0
```
I can training and save it success. But when I try to restore model I got this error:

restore log
```
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key model/softmax_w/part_7 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key model/softmax_w/part_6 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key model/softmax_w/part_5 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key model/softmax_w/part_4 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key model/softmax_w/part_3 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key model/softmax_w/part_2 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key model/softmax_w/part_1 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key model/softmax_w/part_0 not found in checkpoint
W tensorflow/core/framework/op_kernel.cc:975] Not found: Key model/softmax_w/part_7 not found in checkpoint
```

I found tensorflow save the variable as a whole part. The saved parameter just have one softmax_w. No longer a partitioned variable, I can use bellow code restore that variable. 
```
softmax_w = tf.get_variable("softmax_w", [hps.vocab_size, hps.projected_size])
```

**Comment by yaroslavvb** [comment]
@ilblackdragon have you used Saver with your fixed size partitioner successfully?

**Comment by ilblackdragon** [comment]
Hm, weird - restoring should work as it works with other partitioners. 
I can take a quick look tomorrow, may be something changed with Saver v2.

**Comment by MarkDaoust** [comment]
This looks like it's been fixed.

I can `saver.save` and `saver.restore` a partitioned variable without trouble. If this is still a problem please post a minimal example of the code that is not working for you.

This line:

    softmax_w = tf.get_variable("softmax_w", [hps.vocab_size, hps.projected_size])

Fails for me with:

    ValueError: No partitioner was provided, but a partitioned version of the variable was found:
    softmax_w/part_0. Perhaps a variable of the same name was already created with partitioning?
