### ISSUE TITLE
Issue with tf.matrix_diag() in 0.12.0 in Windows GPU mode (CUDA_ERROR_ILLEGAL_ADDRESS)

### ISSUE THREAD

**Issue by buaahsh** [tensorflow/tensorflow#6552]
Here is my code:
```
with tf.Session() as sess:
    # with tf.device("/cpu:0"):
    x = tf.ones(shape=[3, 3])
    x_diag = tf.diag_part(x)
    x_diag_matrix = tf.matrix_diag(x_diag)
    print(sess.run(x_diag_matrix))
```
It works ok on a CPU but fails in a GPU mode with the following 'CUDA_ERROR_ILLEGAL_ADDRESS' error:

> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cublas64_80.dll locally
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cudnn64_5.dll locally
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cufft64_80.dll locally
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library nvcuda.dll locally
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library curand64_80.dll locally
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:885] Found device 0 with properties: 
> name: Tesla K40m
> major: 3 minor: 5 memoryClockRate (GHz) 0.745
> pciBusID 0000:27:00.0
> Total memory: 11.16GiB
> Free memory: 11.09GiB
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0 
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0:   Y 
> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40m, pci bus id: 0000:27:00.0)
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:586] Could not identify NUMA node of /job:localhost/replica:0/task:0/gpu:0, defaulting to 0.  Your kernel may not have been built with NUMA support.
> E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
> F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_event_mgr.cc:198] Unexpected Event status: 1

I have tried 
```
x = tf.ones(shape=[3, 3])
x_diag = tf.diag_part(x)
```
and `x_diag_matrix = tf.matrix_diag([1., 1., 1.])` , Both work ok in a GPU mode. Maybe the tensor couldn't be input of  tf.matrix_diag() in a Windows GPU mode?

**Comment by michaelisard** [comment]
This may be related to #6509. DId you try updating to the newest drivers as suggested there?

**Comment by gunan** [comment]
Closing to merge duplicate issues.
Please follow #6509 for updates.
