### ISSUE TITLE
No tf.batch_matmul operation on source built 12.1 distribution 

### ISSUE THREAD

**Issue by Itaydal** [tensorflow/tensorflow#6560]
Hi all,
I've build from sources the latest version (0.12.1) on my Ubuntu 16 machine.
Then I've found out that I no longer have tf.batch_mat:

import tensorflow as tf
tf.batch_matmul

Traceback (most recent call last):
  File "<ipython-input-2-95fcb8b3e629>", line 1, in <module>
    tf.batch_matmul
AttributeError: module 'tensorflow' has no attribute 'batch_matmul'

Any ideas for a solution?

Some details:

 ls -l /usr/local/cuda-8.0
total 64
drwxr-xr-x  3 root root 4096 Sep 28 12:39 bin
drwxr-xr-x  5 root root 4096 Sep 28 12:38 doc
drwxr-xr-x  5 root root 4096 Sep 28 12:38 extras
drwxr-xr-x  5 root root 4096 Sep 28 12:44 include
drwxr-xr-x  5 root root 4096 Sep 28 12:38 jre
drwxr-xr-x  3 root root 4096 Nov  8 09:46 lib64
drwxr-xr-x  8 root root 4096 Sep 28 12:38 libnsight
drwxr-xr-x  7 root root 4096 Sep 28 12:38 libnvvp
drwxr-xr-x  3 root root 4096 Sep 28 12:38 nvml
drwxr-xr-x  7 root root 4096 Sep 28 12:38 nvvm
drwxr-xr-x  2 root root 4096 Sep 28 12:39 pkgconfig
drwxr-xr-x 11 root root 4096 Sep 28 12:39 samples
drwxr-xr-x  3 root root 4096 Sep 28 12:38 share
drwxr-xr-x  2 root root 4096 Sep 28 12:38 src
drwxr-xr-x  2 root root 4096 Sep 28 12:38 tools
-rw-r--r--  1 root root   20 Sep 28 12:38 version.txt

git rev-parse HEAD
ac28ae043df4bc6f112f964f6df22845b8a05390

 bazel version
Build label: 0.4.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 22 12:31:25 2016 (1482409885)
Build timestamp: 1482409885
Build timestamp as int: 1482409885

Thanks!

**Comment by mrry** [comment]
The `tf.batch_matmul()` op was removed in https://github.com/tensorflow/tensorflow/commit/3a88ec0b8e5a9b8f3f3efc4d9a8f88d47b3f4042. You can now use [`tf.matmul()`](https://www.tensorflow.org/api_docs/python/math_ops/matrix_math_functions#matmul) to perform batch matrix multiplications (i.e. for tensors with rank > 2).

**Comment by Itaydal** [comment]
Well, it currently breaks Keras with the new version of TensorFlow, but I guess that it should be solved there.
Thanks :)
