### ISSUE TITLE
Tensorflow 0.12 on Windows - TypeError: init() got an unexpected keyword argument 'dense_shape' running example

### ISSUE THREAD

**Issue by chitro** [tensorflow/tensorflow#6563]
I downloaded the latest Windows native version of Tensorflow and having problems running some examples. I have Windows 10 (TF 0.12) with python 3.5.2.

The issue is with keyword dense_shape while running the wide_n_deep_tutorial shipped with the package. I pulled the latest version of TF as well but still didn't resolve the problem:

TypeError: init() got an unexpected keyword argument 'dense_shape'

Specifically, the issue is in the following section:

  categorical_cols = {
     k: tf.SparseTensor(
          indices=[[i, 0] for i in range(df[k].size)],
          values=df[k].values,
          dense_shape=[df[k].size, 1])
      for k in CATEGORICAL_COLUMNS}

Per documentation SparseTensor does not seem to understand dense_shape but IndexedSlices does. But I would like examples to work as is, without modification.

Cannot comment whether this happens on Unix also. Any ideas on how to resolve? Thanks!

**Comment by mrry** [comment]
The `tf.SparseTensor` API has changed between the 0.12 release and the git master. You should run the version of `wide_n_deep_tutorial.py` from the `r0.12` branch when you have TensorFlow 0.12 installed:

https://github.com/tensorflow/tensorflow/blob/r0.12/tensorflow/examples/learn/wide_n_deep_tutorial.py

**Comment by mrry** [comment]
I'm closing this because it probably doesn't need a response... feel free to reopen if it still doesn't work.

**Comment by ezerkar** [comment]
Thanks, helped a lot.
