### ISSUE TITLE
`Check failed` in `tf.transpose`, `tf.raw_ops.Transpose` and `tf.compat.v1.transpose` when the values of `perm` have negative numbers.

### ISSUE THREAD

**Issue by xl1043237213** [tensorflow/tensorflow#65649]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.15

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current behavior?

`Check failed` in `tf.transpose` when the values of `perm` have negative numbers, which causes the program to crash. See the colab link below for details.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1GtoXacWSEuyLXVE5GD9IIB-YcMOxV6sP?usp=sharing
```

### Relevant log output

```shell
Check failed: d >= 0 (0 vs. -2)
Aborted (core dumped)
```

**Comment by tilakrayal** [comment]
@xl1043237213,
I was able to reproduce the issue on TensorFlow v2.15, [v2.16](https://colab.research.google.com/gist/tilakrayal/db022d1ed439e7d1c3a6978de02d2afc/untitled1904.ipynb) and [tf-nightly](https://colab.research.google.com/gist/tilakrayal/a1be72080f11a9f46247bdadf17ff625/-6_tf_transpose.ipynb). Kindly find the gist of it here.

![image](https://github.com/tensorflow/tensorflow/assets/81610181/6c144694-313b-4612-8485-bbc17fb6134c)

**Comment by tilakrayal** [comment]
@xl1043237213,
Apologies for the delay. I request you to take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/69213
) where a similar feature has been proposed and it is still open. Also for the same fix, PR was also raised and it is under reviews
https://github.com/tensorflow/tensorflow/pull/63064

Also I request to follow the similar PR and issue which has been proposed to have the updates on the same. Thank you!
