### ISSUE TITLE
`Check failed` and `segmentation fault` in `tf.raw_ops.AudioSpectrogram`.

### ISSUE THREAD

**Issue by xl1043237213** [tensorflow/tensorflow#65653]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current behavior?

When the value of `window_size` is negative, `tf.raw_ops.AudioSpectrogram` triggers `segmentation fault`. When the value of `window_size` is too large, `tf.raw_ops.AudioSpectrogram` triggers`Check failed` due to RAM being full.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/18-XyT4GBDN-o5SZ8jNSR01a9wR-SwScR?usp=sharing
```

### Relevant log output

segmentation fault (core dumped)

or

Check failed: fft_length_ >= window_length_  Aborted (core dumped)

**Comment by sonali-kumari1** [comment]
Hi @xl1043237213,

Thanks for reporting this issue.
`window_size `means how wide the input window is in samples, so negative `window_size `is invalid which leads to segmentation fault in your case and using large `window_size` will result in high memory consumption which triggers Check failed. Please consider using positive and small window_size. 
Attaching [gist](https://colab.sandbox.google.com/gist/sonali-kumari1/fcd1fdba3599e3345946291043aa8924/tf_raw_ops_audiospectrogram.ipynb) for your reference.
