### ISSUE TITLE
`Check failed` in `tf.raw_ops.TensorScatterMax` and `tf.tensor_scatter_nd_max` when the rank of `indices` > 2.

### ISSUE THREAD

**Issue by xl1043237213** [tensorflow/tensorflow#65668]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current behavior?

`Check failed` in `tf.raw_ops.TensorScatterMax` and `tf.tensor_scatter_nd_max` when the rank of `indices` > 2, which causes the program to crash. See the colab link below for details.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1BvyImiXvq4Sr0CMTt--t6lRFy6bkGY8P?usp=sharing
```

### Relevant log output

```shell
Check failed: d < dims() (1 vs. 1)
```

**Comment by sushreebarsa** [comment]
@SuryanarayanaY I was able to replicate the issue reported [here](https://colab.research.google.com/gist/sushreebarsa/1d9902ec75874e268bd7af4045154969/-6_tf_raw_ops_tensorscattermax.ipynb).
Thank you!

**Comment by manojssmk** [comment]
Hi @xl1043237213 

The issue you're encountering is due to how the indices and updates values are being initialized. You can refer to the documentation [link](https://www.tensorflow.org/api_docs/python/tf/raw_ops/TensorScatterMax) for guidance on properly initializing indices and updates.
