### ISSUE TITLE
`Check failed` in `tf.raw_ops.TensorScatterMin` and `tf.tensor_scatter_nd_min` when the rank of `indices` > 2.

### ISSUE THREAD

**Issue by xl1043237213** [tensorflow/tensorflow#65669]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current behavior?

`Check failed` in `tf.raw_ops.TensorScatterMin` and `tf.tensor_scatter_nd_min` when the rank of `indices` > 2, which causes the program to crash. See the colab link below for details.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1An8M5c6VvjjZNvG_xx94Oy-H93suc6mD?usp=sharing
```

### Relevant log output

```shell
Check failed: d < dims() (1 vs. 1)
```

**Comment by SuryanarayanaY** [comment]
Hi @xl1043237213 ,

Thanks for reporting. I have reproduced the reported check fail and attached screenshot below.

![Uploading Screenshot 2024-04-15 at 1.46.43 PM.png…]()

**Comment by SuryanarayanaY** [comment]
<img width="1512" alt="Screenshot 2024-04-15 at 1 46 43 PM" src="https://github.com/tensorflow/tensorflow/assets/116063290/ccd4ab71-c0fa-4330-b964-f8b5310628a5">

**Comment by SuryanarayanaY** [comment]
This seems related to PR #63725

**Comment by tilakrayal** [comment]
@xl1043237213 ,
The PR https://github.com/tensorflow/tensorflow/pull/63725 which was raised was closed and mentioned that 
``` python
The assert that should fail is the last one, which has an equality assertion on the sizes of updates.shape == batch_shape + inner_shape
```

https://github.com/tensorflow/tensorflow/pull/63725

Could you please take a look and provide the context to fulfill and get the PR merged. Thank you!
