### ISSUE TITLE
Get rid of setdlopen() in tests

### ISSUE THREAD

**Issue by jart** [tensorflow/tensorflow#6568]
We need to find a new strategy for loading `.so` files at runtime that depend on other `.so` files. This is so we can remove the dlopen hack, which is now present in >100 files.

The solution needs to meet the requirement that each .py file fully specifies its dependencies and does not rely on code in `__init__.py` files to run beforehand. This requirement is necessary in order to maintain the work we've done to: a) remove hourglass imports so affected tests can be calculated better; and b) so Python modules can be loaded lazily like Java.

## Background

We've refactored TensorFlow to remove hourglass imports in https://github.com/tensorflow/tensorflow/commit/5866e065bc95c1d7de8a27413b368016941889a6, https://github.com/tensorflow/tensorflow/commit/58201a058853de647b37ddb0ccf63d89b2357f03, etc. Since tests no longer depend on the master `__init__.py` file, we've needed to add code like this to the tops of _test.py files that load custom ops defined by contrib libraries:

```python
import sys

if hasattr(sys, "getdlopenflags") and hasattr(sys, "setdlopenflags"):
  import ctypes
  sys.setdlopenflags(sys.getdlopenflags() | ctypes.RTLD_GLOBAL)

from google3.third_party.tensorflow.contrib.rnn.python.ops import core_rnn_cell_impl
from google3.third_party.tensorflow.python.framework import ops
...
```

Otherwise we get errors like `undefined symbol: _ZTIN10tensorflow8OpKernelE` e.g.

```
Traceback (most recent call last):
  File "bazel-out/local-fastbuild/bin/tensorflow/contrib/slim/python/slim/nets/inception_v2_test.runfiles/org_tensorflow/tensorflow/contrib/slim/python/slim/nets/inception_v2_test.py", line 26, in <module>
    from tensorflow.contrib.slim.python.slim.nets import inception_v2
  File "bazel-out/local-fastbuild/bin/tensorflow/contrib/slim/python/slim/nets/inception_v2_test.runfiles/org_tensorflow/tensorflow/contrib/slim/python/slim/nets/inception_v2.py", line 21, in <module>
    from tensorflow.contrib import layers
  File "bazel-out/local-fastbuild/bin/tensorflow/contrib/slim/python/slim/nets/inception_v2_test.runfiles/org_tensorflow/tensorflow/contrib/layers/__init__.py", line 118, in <module>
    from tensorflow.contrib.layers.python.layers import *
  File "bazel-out/local-fastbuild/bin/tensorflow/contrib/slim/python/slim/nets/inception_v2_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/layers/__init__.py", line 22, in <module>
    from tensorflow.contrib.layers.python.layers.embedding_ops import *
  File "bazel-out/local-fastbuild/bin/tensorflow/contrib/slim/python/slim/nets/inception_v2_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/layers/embedding_ops.py", line 21, in <module>
    from tensorflow.contrib.layers.python.ops import sparse_feature_cross_op
  File "bazel-out/local-fastbuild/bin/tensorflow/contrib/slim/python/slim/nets/inception_v2_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/ops/sparse_feature_cross_op.py", line 31, in <module>
    resource_loader.get_path_to_datafile("_sparse_feature_cross_op.so"))
  File "bazel-out/local-fastbuild/bin/tensorflow/contrib/slim/python/slim/nets/inception_v2_test.runfiles/org_tensorflow/tensorflow/contrib/util/loader.py", line 42, in load_op_library
    ret = load_library.load_op_library(path)
  File "bazel-out/local-fastbuild/bin/tensorflow/contrib/slim/python/slim/nets/inception_v2_test.runfiles/org_tensorflow/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: bazel-out/local-fastbuild/bin/tensorflow/contrib/slim/python/slim/nets/inception_v2_test.runfiles/org_tensorflow/tensorflow/contrib/layers/python/ops/_sparse_feature_cross_op.so: undefined symbol: _ZTIN10tensorflow8OpKernelE
```

CC: @gunan @martinwicke @yifeif

**Comment by mrry** [comment]
Passing on the assignment to @keveman, since he came up with the library-loading code in the first place.

I don't understand why `setdlopenflags()` needs to appear in so many test files in the first place.
It seems (at least superficially) that the problem is easy to fix: we just need to ensure that all imports of `tensorflow.python.pywrap_tensorflow` are guarded by the same flag-setting-and-unsetting logic that appears in [`tensorflow/python/__init__.py`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/__init__.py#L58). So we can either:

1. Add the logic to the approximately 20 places where this module is imported, or
2. Add a new wrapper module that is the only module allowed to import `tensorflow.python.pywrap_tensorflow` (perhaps there's a cunning way to enforce this?), implement the flag-setting logic in there, and then replace the 20 direct imports of `tensorflow.python.pywrap_tensorflow` with an import of the wrapper module.

**Comment by jart** [comment]
29 files import that module. Even more probably import it indirectly via init files, which we might unroll in the future. I'm also considering breaking up our giant swig module into a bunch of tiny swig modules. Having to have the try/setdlopen-import/except/setdlopen every time we import a swig module isn't going to be great. A delegate module could work. But there might be a better option:

3. Ask SWIG to to put the setdlopenflags() stuff into the generated `pywrap_tensorflow.py` file. See: https://www.mail-archive.com/users@lists.open-mpi.org/msg09998.html

**Comment by jart** [comment]
Another thing we need to figure out how to do is situations like these:

```python
from google3.third_party.tensorflow.python import pywrap_tensorflow
from google3.third_party.tensorflow.contrib.tfprof.python.tools.tfprof import pywrap_tensorflow_print_model_analysis_lib
```

The first swig module needs to be loaded in order for the second one to load. So we need to be able to generate code inside `pywrap_tensorflow_print_model_analysis_lib.py` that imports `pywrap_tensorflow`.

Now this seems like a build system issue. Maybe we could change our swig Bazel rule to mangle the `.i` input file to inject the code we want into the generated `.py` binding.

**Comment by gunan** [comment]
/CC @drpngx 

I think I like the idea of wrapping pywrap_tensorflow with a different module, and importing that wrapper in all locations pywrap_tensorflow is needed. I think this approach has some parallels with @drpngx 's approach for sealing the python API. Moreover, I think pywrap_tensorflow is still not sealed, so the wrapper can also do the job to seal it. What do you think?

However, once we replace big monolithic swig with a nicer mechanism that lets us split up the wrapped library, I am not sure how much work wrapping approach will need, as we will potentially have many wrapped libraries now.

For the 2nd issue @jart raised, bazel magic scares me a little, but it is quite powerful. So I think the solution you suggested can work, but I am not sure I like it.

**Comment by drpngx** [comment]
I left the pywrap unsealed, and under the tf namespace, because it's in the main package, and packages are different from modules, which are easier. I recently discovered a way to remove it from the main package, so I might try that. (The issue was that if you delete from the main package, you can't import it anymore. I found out that you can actually import it using `from ... python import foo` but not `from .. python.foo import bar`)

**Comment by albertz** [comment]
This didn't fixed it for me. Actually that was a custom user op in my case. I think #13607 describes my issue. I wonder a bit that on my local system (Ubuntu 16.04), this doesn't seem to be needed but on Travis, it seems to be needed.
