### ISSUE TITLE
TensorFlow 2.16 is not found in Maven Central

### ISSUE THREAD

**Issue by shawn-lin-013** [tensorflow/tensorflow#65694]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.16

### Custom code

No

### Current behavior?

The TensorFlow 2.16 is not found in Maven Central, also blocks the issue https://github.com/tensorflow/tensorflow/issues/61951

### Standalone code to reproduce the issue

```shell
implementation ("org.tensorflow:tensorflow-lite:2.16.1")
```

**Comment by fergushenderson** [comment]
TF Lite 2.16.1 is available on Maven Central now.
See <https://mvnrepository.com/artifact/org.tensorflow/tensorflow-lite/2.16.1>.

**Comment by shawn-lin-013** [comment]
> TF Lite 2.16.1 is available on Maven Central now. See https://mvnrepository.com/artifact/org.tensorflow/tensorflow-lite/2.16.1.

@fergushenderson Thanks! We have confirmed that TF Lite 2.16.1 is already available on Maven Central.

**Comment by sawantkumar** [comment]
Hi @fergushenderson ,

If the issue is fixed can you please close the issue .

**Comment by fergushenderson** [comment]
Yes, the issue is fixed.

However, I can't close the issue because I don't have the appropriate access/permission.
(Although I am a Google employee, I am not a member of the TF Lite team, nor am I a member of the TensorFlow team.)
