### ISSUE TITLE
MemoryError - Convolutional.py 

### ISSUE THREAD

**Issue by Vivalldi** [tensorflow/tensorflow#657]
I followed the pip install of TensorFlow and when trying the "Test your installation" I recevied the following output with a MemoryError.
```
Extracting data/train-images-idx3-ubyte.gz
Traceback (most recent call last):
  File "convolutional.py", line 290, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "convolutional.py", line 127, in main
    train_data = extract_data(train_data_filename, 60000)
  File "convolutional.py", line 75, in extract_data
    data = (data - (PIXEL_DEPTH / 2.0)) / PIXEL_DEPTH
MemoryError
```
Any suggestions would be much appreciated.

**Comment by vincentvanhoucke** [comment]
This failure occurs before TensorFlow even begins executing. It looks the system you're running on has very little RAM available, and can't handle loading the whole MNIST training set into memory and preprocessing it in python. There might be ways to reduce the total amount of memory used at that stage, but this seems like a particularly pathological situation.

**Comment by Vivalldi** [comment]
@vincentvanhoucke thank you. I accidentally installed on my 512 MB server rather than my 2 GB ram server. Thanks again.
