### ISSUE TITLE
build TensorFlow  in windows

### ISSUE THREAD

**Issue by swoiow** [tensorflow/tensorflow#65719]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

unknow

### Custom code

No

### OS platform and distribution

windows

### Python version

3.10

### Current behavior?

i just want to build tensorflow-text and fork the code used github action to do this. but failed to build with error `cl : Command line error D8022 : cannot open 'bazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/quantization/tensorflow/calibrator/_objs/calibration_statistics_proto_cc_impl/calibration_statistics.pb.obj.params'`

Any help with me?

### Standalone code to reproduce the issue

the source code in [fork](https://github.com/swoiow/text)

![image](https://github.com/tensorflow/tensorflow/assets/7948020/90dbfbed-3a43-4c31-866f-c1da45efb11a)

**Comment by Venkat6871** [comment]
Hi **@swoiow** ,
- Ensure there are no residual files causing conflicts, For cleaning your build directory Use this following command.
```
bazel clean --expunge
```
- Make sure you are using the latest versions of Bazel and TensorFlow Text. Outdated versions can sometimes lead to compatibility issues and build errors.

Thank you!

**Comment by swoiow** [comment]
> Hi **@swoiow** ,
> 
> * Ensure there are no residual files causing conflicts, For cleaning your build directory Use this following command.
> 
> ```
> bazel clean --expunge
> ```
> 
> * Make sure you are using the latest versions of Bazel and TensorFlow Text. Outdated versions can sometimes lead to compatibility issues and build errors.
> 
> Thank you!

i just tested with `bazel clean --expunge`, it looks not good for me with same error
