### ISSUE TITLE
`Check Failed` in `tf.raw_ops.FakeQuantWithMinMaxVarsPerChannel` and `tf.quantization.fake_quant_with_min_max_vars_per_channel` when the input of `inputs` is scalar.

### ISSUE THREAD

**Issue by xl1043237213** [tensorflow/tensorflow#65728]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current behavior?

`Check Failed` in `tf.raw_ops.FakeQuantWithMinMaxVarsPerChannel` and  `tf.quantization.fake_quant_with_min_max_vars_per_channel` when the input of `inputs` is scalar, which causes the program to crash. See the colab link below for details.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1ydn7hiGhj5xFypCmJPZ410gmboo0Edji#scrollTo=NfIGXCwpS1Dr
```

### Relevant log output

```shell
Check failed: d >= 0 (0 vs. -1)
```

**Comment by Venkat6871** [comment]
Hi **@xl1043237213** ,

I don't have access to open your colab code. Could you please provide proper link or access to present link.

Thank you!

**Comment by xl1043237213** [comment]
I'm sorry, I've changed the access permission now. @Venkat6871

**Comment by Venkat6871** [comment]
Hi **@xl1043237213** ,

I tried to run your code on colab using TF v2.16.1, nightly and faced the same issue. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/cf6cd93274c851b32722e3c4a5200516/65728_2-16-1-nighly-v.ipynb) here for reference.

Thank you!

**Comment by LakshmiKalaKadali** [comment]
Hi @xl1043237213,

As per the [documentation](https://www.tensorflow.org/api_docs/python/tf/quantization/fake_quant_with_min_max_vars_per_channel) , `Fake-quantize the inputs tensor of type float per-channel and one of the shapes: [d], [b, d] [b, h, w, d] via per-channel floats min and max of shape [d] to outputs tensor of same shape as inputs`. 

In the code `'inputs': tf.constant(1, dtype=tf.float32)`, the input is defined as a scalar, which has `0` dimension. So please change the input to minimum `1D` like `'inputs': tf.constant(1, dtype=tf.float32)`. Here is the modified code. It is working fine without any crash.
```
input_dict = {'inputs': tf.constant(1, dtype=tf.float32)),
        'min': tf.constant([0], dtype=tf.float32),
        'max': tf.constant([1], dtype=tf.float32)}

result = tf.quantization.fake_quant_with_min_max_vars_per_channel(**input_dict)
print(result) 
```

Thank You
