### ISSUE TITLE
`Assertion failure` in `tf.raw_ops.RFFT` and `tf.signal.rfft` when the value of `fft_length` is 0. 

### ISSUE THREAD

**Issue by xl1043237213** [tensorflow/tensorflow#65736]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current behavior?

`Assertion failure` in `tf.raw_ops.RFFT` and `tf.signal.rfft` when the value of `fft_length` is 0. 

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1RYmVMgilwfLU-H1weXOkBvwNj-JUhhyK?usp=sharing
```

### Relevant log output

```shell
Assertion failure
axis length mismatch
```

**Comment by SuryanarayanaY** [comment]
Hi @xl1043237213 ,

I have replicated the reported behaviour with tf-nightly and attached screenshot below.

<img width="1489" alt="Screenshot 2024-04-16 at 1 13 40 PM" src="https://github.com/tensorflow/tensorflow/assets/116063290/edc318e7-d700-458d-8594-75f25316911d">
