### ISSUE TITLE
does not work on my dataset

### ISSUE THREAD

**Issue by ehsaanwelcome** [tensorflow/tensorflow#6575]
Linux Unbuntu
Python 2.7

I did run word2vec_basic.py example successfully but as i change dataset from text8.zip to mydata.zip, i get following error

Traceback (most recent call last):
  File "../../statistics/word2vec/word2vec_basic.py", line 218, in <module>
    close_word = reverse_dictionary[nearest[k]]
KeyError: 21049

i have checked, my data is loading successfully in data array

**Comment by yaroslavvb** [comment]
Closing as it doesn't seem to be a bug in TensorFlow or feature request. Posting on StackOverflow with tag:tensorflow may elicit some help how to modify the example to work on custom datasets
