### ISSUE TITLE
Just some Grammar

### ISSUE THREAD

**Issue by krishnac7** [tensorflow/tensorflow#6579]
![untitled](https://cloud.githubusercontent.com/assets/7543641/21576381/ac92b3a8-cf52-11e6-8662-8b72a36a7caf.png)

NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by yaroslavvb** [comment]
I'm assuming this is the retraining tutorial, the grammar seems to be fixed at head -- https://github.com/tensorflow/tensorflow/blob/4172ca2cd7ac34be67bda2600944d284e8907b95/tensorflow/g3doc/how_tos/image_retraining/index.md
