### ISSUE TITLE
`Segmentation fault` in `tf.raw_ops.SparseFillEmptyRows` when the value of `dense_shape` is too large.

### ISSUE THREAD

**Issue by xl1043237213** [tensorflow/tensorflow#65791]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current behavior?

`Segmentation fault` in `tf.raw_ops.SparseFillEmptyRows` when the value of `dense_shape` is too large.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1-TZcbmGYm72oGehk4PC87LquCXQ5Xn44?usp=sharing
```

### Relevant log output

```shell
segmentation fault (core dumped)
```

**Comment by sushreebarsa** [comment]
@xl1043237213 I was able to replicate the issue [here](https://colab.research.google.com/gist/sushreebarsa/144d2cf3c6f16503d4923b574d9a13ea/-11_tf_raw_ops_sparsefillemptyrows.ipynb). Thank you!

**Comment by kiransair** [comment]
Hi @xl1043237213, I have tried in a alternative approach using tf.sparse.fill_empty I did not get the error.please refer to this [gist](https://gist.github.com/kiransair/8b16e8da430a132dd3936388e11e9cf2) for the code example.

Thank You.
