### ISSUE TITLE
`models` directory disappeared in the latest commit

### ISSUE THREAD

**Issue by zafartahirov** [tensorflow/tensorflow#6580]
The documentation refers to `models/image/mnist/convolutional.py`, however it doesn't exist anymore. It exists in `r0.12`, but not `master`. In fact, the whole `models` directory is missing. If restructuring is going on, I think the documentation has to be updated.

[Here is the documentation that refers to it](https://github.com/tensorflow/tensorflow/blob/2e22f1b20/tensorflow/g3doc/get_started/os_setup.md#train-your-first-tensorflow-neural-net-model)

**Comment by zafartahirov** [comment]
Forgot to clarify, the `master` under question is 2e22f1b20

**Comment by gunan** [comment]
All models have been moved to `github.com/tensorflow/models` repository.
Some documentation is still left to be fixed, but we are working on them

@nealwu

**Comment by zafartahirov** [comment]
So is it a separate repo now?

If there is a push towards abstraction and modularization, shouldn't other folders become separate entities? 

For example
 - [Tensorboard](https://github.com/tensorflow/tensorflow/tree/2e22f1b20fdfa77b1332c518617391dc32359c5b/tensorflow/tensorboard) could be a submodule, because although it is related, it more of a tool FOR TF rather than an integral part of it
- [Examples](https://github.com/tensorflow/tensorflow/tree/2e22f1b20fdfa77b1332c518617391dc32359c5b/tensorflow/examples) this is also not necessary for correct operation of TF, and could be moved out (same as `models`).
- [Contrib](https://github.com/tensorflow/tensorflow/tree/2e22f1b20fdfa77b1332c518617391dc32359c5b/tensorflow/contrib) could be a separate project with its own documentation (aka SciKit)

Any ideas on which direction it is headed?

**Comment by martinwicke** [comment]
We moved the models/ directory to https://github.com/tensorflow/models because that makes more sense. We will likely do more such moves as you describe: we will likely keep a small number of small examples, but possibly less than we have. contrib is definitely a target for moving to its own repo, but we have to figure out a bunch of tooling to make that work well. As you say, tensorboard is also not required in the main repo, but we have no immediate plans to move it.

These changes will make it easier for us to maintain these components. Please bear with us, I know these changes can be disruptive.

**Comment by nealwu** [comment]
Thanks for reporting this @zafartahirov. The documentation you linked to though instructs you to clone the [TensorFlow models repo](https://github.com/tensorflow/models), so it looks fine to me. Let us know if you find other outdated documentation.

**Comment by zafartahirov** [comment]
Oh yeah, sorry -- I meant to link to the [official docs](https://www.tensorflow.org/get_started/os_setup#run_a_tensorflow_demo_model)

**Comment by nealwu** [comment]
OK got it. The reason for this is that the current default version of the docs is r0.12 (which should also be the version you get if you use pip to install tensorflow).

If you look at the [master version of the docs](https://www.tensorflow.org/versions/master/get_started/os_setup) instead, it should be up to date with the master version of the code.
