### ISSUE TITLE
function object mismatch in TFOpLambda

### ISSUE THREAD

**Issue by elad-c** [tensorflow/tensorflow#65813]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 20.04

### Current behavior?

The function object stored in the `function` attribute of a `TFOpLambda` in a functional model doesn't match the original tensorflow function I used to build the model. This happens for `tf.add`, `tf.multiply` & `tf.matmul`. Doesn't happen for `tf.subtract` and `tf.divide`.

This behaviour started in version 2.15.

The output of TF 2.14 is:
1) layer match: True
2) add match: True
3) subtract match: True

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from keras.src.layers.core import TFOpLambda

_in = tf.keras.layers.Input((8,))
out = tf.add(_in, 4)
out = tf.subtract(out, 4)
model = tf.keras.Model(inputs=_in, outputs=out)

print(f'1) layer match: {isinstance(model.layers[1], TFOpLambda)}')
print(f'2) add match: {model.layers[1].function is tf.add}')
print(f'3) subtract match: {model.layers[2].function is tf.subtract}')
```

### Relevant log output

```shell
1) layer match: True
2) add match: False
3) subtract match: True
```

**Comment by tilakrayal** [comment]
@elad-c,
Looks like this is an issue with the keras and also I can see that there is another issue raised for the similar error in the keras repo. Could you please feel free to move this issue to closed status and let me know if anything is missed here. Thank you!

**Comment by elad-c** [comment]
Ok, thanks.
