### ISSUE TITLE
Incompatible state size between LSTMCell and LSTMBlockCell

### ISSUE THREAD

**Issue by jihunchoi** [tensorflow/tensorflow#6582]
Hello,

I heard that the implementation of LSTMBlockCell is faster than that of LSTMCell, so I am trying to convert my codes using LSTMCell to use LSTMBlockCell.
However, I found one weird point: the types of state_size of the two are not compatible.
Specifically, LSTMCell's state_size is of type LSTMStateTuple and LSTMBlockCell's state_size is of type tuple.
As far as I know, tuple and LSTMStateTuple are quite similar but the latter handles an internal memory state and a hidden state in a more abstract way.

I know the separated use of tuple and LSTMStateTuple is quite useful; for example when I have to detect whether a cell is MultiRNNCell (where state_size is of type tuple) or a cell is LSTMCell (where state_size is of type LSTMStateTuple).
Thus, I think the current behavior of LSTMBlockCell should be corrected to use LSTMStateTuple as a state type.
It can be easily modified if there is no backward compatibility issue, and I will send a pull request if nobody is working on this now.

**Comment by michaelisard** [comment]
@ebrevdo what do you think?

**Comment by ebrevdo** [comment]
Looks like an oversight.  The block implementation should use the same tuple object.  Will try to fix next week.
