### ISSUE TITLE
Import msvcp140.dll and msvcp140_1.dll from a custom location

### ISSUE THREAD

**Issue by admshumar** [tensorflow/tensorflow#65828]
### Issue type

Feature Request

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.10

### Custom code

No

### OS platform and distribution

Microsoft Windows 10

### Python version

3.10

### Current behavior?

On Microsoft Windows, TensorFlow requires either of the Microsoft Visual C++ runtime libraries msvcp140.dll or msvcp140_1.dll when initialising. When both DLLs are missing, TensorFlow exits as follows:

_ImportError: Could not find the DLL(s) 'msvcp140.dll or msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads_

Placing 'msvcp140.dll or msvcp140_1.dll' in a custom directory and appending the custom directory to PATH prior to importing TensorFlow is insufficient to expose the DLLs to TensorFlow.

There are two options to deal with this:

(1) Download and install "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019", as recommended. The problem with this is that if there is no control over the target environment, then there is no guarantee that the desired DLL files will exist at runtime.
(2) Make the call to ctypes in tensorflow.platform.python.self_check.preload_check configurable with a custom path for the DLL files.

I would prefer option (2), as it allows tighter control over the DLL files.

### Standalone code to reproduce the issue

```shell
# Import TensorFlow without msvcp140.dll and msvcp140_1.dll in a system directory or Python
# directory
import tensorflow
```

### Relevant log output

```shell
C:\Python\lib\site-packages\tensorflow\__init__.py:37: in <module>
    from tensorflow.python.tools import module_util as _module_util
C:\Python\lib\site-packages\tensorflow\python\__init__.py:36: in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
C:\Python\lib\site-packages\tensorflow\python\pywrap_tensorflow.py:26: in <module>
    self_check.preload_check()
C:\Python\lib\site-packages\tensorflow\python\platform\self_check.py:50: in preload_check
    raise ImportError(
E   ImportError: Could not find the DLL(s) 'msvcp140.dll or msvcp140_1.dll'. TensorFlow requires that these DLLs be installed in a directory that is named in your %PATH% environment variable. You may install these DLLs by downloading "Microsoft C++ Redistributable for Visual Studio 2015, 2017 and 2019" for your platform from this URL: https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads
```

**Comment by Venkat6871** [comment]
Hi **@admshumar** ,
Could you please verify your python/os version. And you may also refer to https://github.com/tensorflow/tensorflow/issues/35618.if you still face any issues please let us.

Thank you!

**Comment by admshumar** [comment]
Hi @Venkat6871,
It seems to be sufficient to use Python's os module to include custom DLL locations prior to importing TensorFlow:
`from os import add_dll_directory`
`add_dll_directory("custom_dll_dir")`
`import tensorflow as tf`
