### ISSUE TITLE
does pluggable custom device support distributed runtime?

### ISSUE THREAD

**Issue by Hoonly** [tensorflow/tensorflow#65831]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.6.5

### Custom code

Yes

### OS platform and distribution

Ubuntu1804

### Python version

3.8

### Current behavior?

how to support distributed training with pluggable device

### Standalone code to reproduce the issue

```shell
None
```

**Comment by sushreebarsa** [comment]
@Hoonly Pluggable custom devices in TensorFlow generally do not directly support distributed runtime on their own. Distributed runtime in TensorFlow refers to running computations across multiple machines or devices for tasks that are too large for a single machine. Could you please refer to [this](https://www.tensorflow.org/api_docs/python/tf/distribute/Strategy) guide to explore TF distributed strategies?

Thank you!
