### ISSUE TITLE
Thank You TensorFlow Team! 

### ISSUE THREAD

**Issue by Carmezim** [tensorflow/tensorflow#6585]
Special thanks to all TensorFlow engineers for your incredible work this year. Maintaining and developing so successfully a project of this magnitude isn't an easy work. I've personally always seen great attention to the issues and contributions made with an also prompt, helpful and nice attitude and believe the community is very grateful for all you've done this year and the excellence of your work. Can't wait for what is to come in 2017!

**Comment by zakizhou** [comment]
I just want to know what's the time of the v1.0 release and what kind of changes made to it
