### ISSUE TITLE
`Overflow` in `tf.raw_ops.SparseReduceMaxSparse` when there are too large values in `input_shape`.

### ISSUE THREAD

**Issue by xl1043237213** [tensorflow/tensorflow#65865]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current behavior?

`Overflow` in `tf.raw_ops.SparseReduceMaxSparse` when there are too large values in `input_shape`. See the colab link below for details.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1XHTMWmfVRuKBorPLZyk6iUv29_AUr8HF?usp=sharing
```

### Relevant log output

```shell
Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 2684354560 with 666666666666, result: -1
```

**Comment by cantonios** [comment]
Not a bug - the shape is too large and informing you of this.

**Comment by xl1043237213** [comment]
> Not a bug - the shape is too large and informing you of this.

Can you tell me in more detail why the issue is not considered a bug? `INVALID_ARGUMENT` is an error type defined by TensorFlow but causes the program to crash, should this be avoided?

**Comment by cantonios** [comment]
> > Not a bug - the shape is too large and informing you of this.
> 
> Can you tell me in more detail why the issue is not considered a bug? `INVALID_ARGUMENT` is an error type defined by TensorFlow but causes the program to crash, should this be avoided?

Throwing an error is not a crash.  The error is telling you that your input argument is invalid.

**Comment by xl1043237213** [comment]
> > > Not a bug - the shape is too large and informing you of this.
> > 
> > 
> > Can you tell me in more detail why the issue is not considered a bug? `INVALID_ARGUMENT` is an error type defined by TensorFlow but causes the program to crash, should this be avoided?
> 
> Throwing an error is not a crash. The error is telling you that your input argument is invalid.

Error is thrown by C/C++ code, causing the Python interpreter to crash, and similarly `Check failed`. Are these errors not considered bugs?🤔

**Comment by cantonios** [comment]
> > > > Not a bug - the shape is too large and informing you of this.
> > > 
> > > 
> > > Can you tell me in more detail why the issue is not considered a bug? `INVALID_ARGUMENT` is an error type defined by TensorFlow but causes the program to crash, should this be avoided?
> > 
> > 
> > Throwing an error is not a crash. The error is telling you that your input argument is invalid.
> 
> Error is thrown by C/C++ code, causing the Python interpreter to crash

The interpreter does not crash - an exception is thrown, and you can catch it in python.

>, and similarly `Check failed`. Are these errors not considered bugs?🤔

We don't consider those serious bugs, especially if you intentionally provide obviously invalid data with the sole intention of trying to trigger a crash.

**Comment by xl1043237213** [comment]
Thanks for your patient answer. 

I'd like to know how to catch the exception. When you run the code in [colab](https://colab.research.google.com/drive/1XHTMWmfVRuKBorPLZyk6iUv29_AUr8HF?usp=sharing), the web page will throw error message "Your session crashed for an unknown reason". When you run the code using `subprocess`, you can get return code [-6](https://www-uxsup.csx.cam.ac.uk/courses/moved.Building/signals.pdf). I think the exception is thrown by C/C++ code but cannot be caught by the Python process. 

It is true that this is an artificially constructed invalid input, but improper handling of the boundary case may affect the stability of the program execution😔

**Comment by cantonios** [comment]
> Thanks for your patient answer.
> 
> I'd like to know how to catch the exception. When you run the code in [colab](https://colab.research.google.com/drive/1XHTMWmfVRuKBorPLZyk6iUv29_AUr8HF?usp=sharing), the web page will throw error message "Your session crashed for an unknown reason". When you run the code using `subprocess`, you can get return code [-6](https://www-uxsup.csx.cam.ac.uk/courses/moved.Building/signals.pdf). I think the exception is thrown by C/C++ code but cannot be caught by the Python process.
> 
> It is true that this is an artificially constructed invalid input, but improper handling of the boundary case may affect the stability of the program execution😔

Thanks, the error was not propagated correctly to python.  It was a quick fix, so should now work.

But in general, we now deprioritize any artificial edge-case issues like this that are not encountered by real-world models.
