### ISSUE TITLE
`Check failed` in `tf.raw_ops.GatherV2` when the value of `axis` is too large.

### ISSUE THREAD

**Issue by xl1043237213** [tensorflow/tensorflow#65869]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.15

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current behavior?

`Check failed` in `tf.raw_ops.GatherV2` when the value of `axis` is too large.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1murNElV5aOKQRNFwvWhygfoy21__ycTX?usp=sharing
```

### Relevant log output

```shell
Check failed: d >= 0 (0 vs. -1)
```

**Comment by SuryanarayanaY** [comment]
Hi @xl1043237213 ,

I have replicated the reported behaviour and attached screenshot below. Need to check the root cause.

<img width="1506" alt="Screenshot 2024-04-17 at 11 30 33 AM" src="https://github.com/tensorflow/tensorflow/assets/116063290/3fdc52a6-80b8-41e3-af37-42bb4447840a">
