### ISSUE TITLE
`Assertion failure` in `tf.signal.inverse_stft` when the value of `frame_length` is too large.

### ISSUE THREAD

**Issue by xl1043237213** [tensorflow/tensorflow#65868]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current behavior?

`Assertion failure` in `tf.signal.inverse_stft` when the value of `frame_length` is too large. See the colab link below for details.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1zrvFDj93eGx9bt3A5WbEqrcMTrqPcHT9?usp=sharing
```

### Relevant log output

```shell
Assertion failure
no zero-sized FFTs
```

**Comment by sushreebarsa** [comment]
@xl1043237213 I was able to replicate the issue reported [here](https://colab.research.google.com/gist/sushreebarsa/572a65b5de7f20dad771bc9947959a36/-6_tf_signal_inverse_stft.ipynb). Thank you!

**Comment by LakshmiKalaKadali** [comment]
Hi @xl1043237213,

In the given code, the specified frame length `tf.constant(2356767558460083043, dtype=tf.int64)` is extremely large. Try to reduce to frame_length to a reasonable value 256 and the `frame_length` should be int32 and should match to `frame_shift` while performing `inverse_stft`.  Please do update these changes, the code works fine and refer to the [gist](https://colab.sandbox.google.com/gist/LakshmiKalaKadali/53036a6ca4de74f709107040dc8a4dba/api_tf_signal_inverse_stft.ipynb)

Thank You
