### ISSUE TITLE
WideNet in examples/learn  throws error on UBUNTU 16.04 LTS

### ISSUE THREAD

**Issue by as1ndu** [tensorflow/tensorflow#6591]
Am running TensorFlow (0.11.0rc0) On Ubuntu 16.04 LTS installed via pip 

I was going through the guides at  https://www.tensorflow.org/tutorials/wide_and_deep/  I thought that my code had an error, but then running the example script at  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/wide_n_deep_tutorial.py 

Also throws the same error is the problem my environment? the script or Ubuntu 16.04 I haven't tried it in 14.04.

`Training data is downloaded to /tmp/tmp1SYKCv
Test data is downloaded to /tmp/tmpWhX5FI
model directory = /tmp/tmp9TzI1B
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "sum" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:The default value of combiner will change from "mean" to "sqrtn" after 2016/11/01.
WARNING:tensorflow:Change warning: default value of `enable_centered_bias` will change after 2016-10-09. It will be disabled by default.Instructions for keeping existing behaviour:
Explicitly set `enable_centered_bias` to 'True' if you want to keep existing behaviour.
WARNING:tensorflow:Using default config.
Traceback (most recent call last):
  File "widenet.py", line 208, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "widenet.py", line 204, in main
    train_and_eval()
  File "widenet.py", line 197, in train_and_eval
    m.fit(input_fn=lambda: input_fn(df_train), steps=FLAGS.train_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 333, in fit
    max_steps=max_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py", line 660, in _train_model
    features, targets = input_fn()
  File "widenet.py", line 197, in <lambda>
    m.fit(input_fn=lambda: input_fn(df_train), steps=FLAGS.train_steps)
  File "widenet.py", line 159, in input_fn
    for k in CATEGORICAL_COLUMNS}
  File "widenet.py", line 159, in <dictcomp>
    for k in CATEGORICAL_COLUMNS}
TypeError: __init__() got an unexpected keyword argument 'dense_shape'`

**Comment by gunan** [comment]
Could you see if the same problem exists in 0.12.1?

**Comment by as1ndu** [comment]
Yeah it works.. thanx..

**Comment by as1ndu** [comment]
Sorry, issue persists in 0.12.1

**Comment by nagachika** [comment]
Hi, as  commented at https://github.com/tensorflow/tensorflow/issues/6648#issuecomment-270806057, please try example file on v0.12 branch.

**Comment by as1ndu** [comment]
works..  thanx @nagachika
