### ISSUE TITLE
MonitoredSession Implementation [awaiting response]

### ISSUE THREAD

**Issue by chaitanya2692** [tensorflow/tensorflow#6593]
I am trying to solve simple arithmetic operations on 4 separate devices which I was successful in doing. Now, I want to implement fault tolerance in my program in the event that one of the node fails. I am using the tf.train.MonitoredTrainingSession class to achieve the desired results. I am not confident about the implementation in my program as I am not getting a favorable output. Below is the program as far as I could get:-

Please help
```
import tensorflow as tf

global_step_tensor = tf.Variable(10, trainable=False, name='global_step')

cluster = tf.train.ClusterSpec({"local": ["localhost:2222", "localhost:2223","localhost:2224", "localhost:2225"]})
x = tf.constant(2)

with tf.device("/job:local/task:0"):
    y1 = x + 300

with tf.device("/job:local/task:1"):
    y2 = x**2

with tf.device("/job:local/task:2"):
    y3 = 5*x

with tf.device("/job:local/task:3"):
    y0 = x - 66
    y = y0 + y1 + y2 + y3

ChiefSessionCreator = tf.train.ChiefSessionCreator(scaffold=None, master='localhost:2222', config='grpc://localhost:2222', checkpoint_dir='/home/chaitanya/tensorflow/codes/checkpoints')
saver_hook = tf.train.CheckpointSaverHook(checkpoint_dir='/home/chaitanya/tensorflow/codes/checkpoints', save_secs=10, save_steps=None, saver=y, checkpoint_basename='model.ckpt', scaffold=None)
summary_hook = tf.train.SummarySaverHook(save_steps=None, save_secs=10, output_dir='/home/chaitanya/tensorflow/codes/savepoints', summary_writer=None, scaffold=None, summary_op=y)

with tf.train.MonitoredTrainingSession(master='localhost:2222', is_chief=True, checkpoint_dir='/home/chaitanya/tensorflow/codes/checkpoints', 
    scaffold=None, hooks=[saver_hook, summary_hook], chief_only_hooks=None, save_checkpoint_secs=10, save_summaries_steps=None, config='grpc://localhost:2222') as sess:

    while not sess.should_stop():
        sess.run(model)

    while not sess.should_stop():
        print(sess.run(y0))
        print('\n')

    while not sess.should_stop():
        print(sess.run(y1))
        print('\n')

    while not sess.should_stop():
        print(sess.run(y2))
        print('\n')

    while not sess.should_stop():
        print(sess.run(y3))
        print('\n')

    while not sess.should_stop():
        result = sess.run(y)
        print(result)
```
I have also posted this on stackoverflow:-

https://stackoverflow.com/questions/41478027/tf-train-monitoredtrainingsession-arguments

**Comment by chaitanya2692** [comment]
Would 
 `RPCOptions` rpc_options = 13
in config.proto help me in anyway?

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/config.proto

**Comment by chaitanya2692** [comment]
The master config syntax should be `master='grpc://localhost:2222'` instead of `master='localhost:2222'`

Current error to tackle:- 
`TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.
`

**Comment by michaelisard** [comment]
Closing here: stackoverflow is the right place for this discussion.
