### ISSUE TITLE
XNNPACK delegate doesn't support to broadcast last dimension for Prelu operator

### ISSUE THREAD

**Issue by fujunwei** [tensorflow/tensorflow#65976]
Below test can reproduce this issue that is modified from [TEST_P(PReluOpTest, PReluFloat32) ](https://github.com/tensorflow/tensorflow/blob/c9a3144cda64eabb553967ff73e37f9836a5d0c2/tensorflow/lite/kernels/activations_test.cc#L2467):
```
TEST_P(PReluOpTest, PReluFloat32) {
  FloatPReluOpModel m({TensorType_FLOAT32, {1, 2, 2, 3}},
                      {TensorType_FLOAT32, {1, 1, 1, 1}});

  m.SetInput({
      0.0f, 0.0f, 0.0f,     // Row 1, Column 1
      1.0f, 1.0f, 1.0f,     // Row 1, Column 2
      -1.0f, -1.0f, -1.0f,  // Row 2, Column 1
      -2.0f, -2.0f, -2.0f,  // Row 2, Column 2
  });
  m.SetAlpha({1.0f});
  ASSERT_EQ(m.Invoke(), kTfLiteOk);
  EXPECT_THAT(m.GetOutput(), ElementsAreArray({
                                 0.0f, 0.0f, 0.0f,    // Row 1, Column 1
                                 1.0f, 1.0f, 1.0f,    // Row 1, Column 2
                                 0.0f, -1.0f, -2.0f,  // Row 2, Column 1
                                 0.0f, -2.0f, -4.0f,  // Row 2, Column 2
                             }));
}
```

A solution is to use [TFLite kernel of prelu](https://source.chromium.org/chromium/chromium/src/+/main:third_party/tflite/src/tensorflow/lite/kernels/activations.cc;l=1454;drc=11c6fee8868a670b11ae04cf5649f7805f6cc16a?q=third_party%2Ftflite%2Fsrc%2Ftensorflow%2Flite%2Fkernels%2Factivations.cc&ss=chromium%2Fchromium%2Fsrc) for broadcasting the last dimension, so the [VisitPreluNode](https://source.chromium.org/chromium/chromium/src/+/main:third_party/tflite/src/tensorflow/lite/delegates/xnnpack/xnnpack_delegate.cc?q=TfLiteStatus%20VisitPreluNode&ss=chromium%2Fchromium%2Fsrc:third_party%2F) in XNNPACK Delegate need to validate the broadcastable last dimension and return not support error to fallback TFLite kernel.

**Comment by alankelly** [comment]
This is indeed a bug and a PR is open in XNNPack to address it. I will close this once the XNNPack version in OS tflite has been updated.
