### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by nshanker** [tensorflow/tensorflow#66]
Just did a git clone to build from source as described in documentation and got this at compile time (without CUDA/GPG support) ...

INFO: From Compiling tensorflow/core/kernels/pad_op.cc:
In file included from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:94:0,
                 from ./tensorflow/core/framework/tensor_types.h:4,
                 from ./tensorflow/core/kernels/pad_op.h:6,
                 from tensorflow/core/kernels/pad_op.cc:5:
third_party/eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorBase.h: In instantiation of 'const Eigen::TensorPaddingOp<const PaddingDimensions, const Derived> Eigen::TensorBase<Derived, 0>::pad(const PaddingDimensions&) const [with PaddingDimensions = Eigen::array<std::pair<int, int>, 0ul>; Derived = Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 0ul, 1, long int>, 1>]':
./tensorflow/core/kernels/pad_op.h:20:22:   required from 'void tensorflow::functor::Pad<Device, T, Dims>::operator()(const Device&, typename tensorflow::TTypes<T, Dims>::Tensor, typename tensorflow::TTypes<T, Dims>::ConstTensor, Eigen::array<std::pair<int, int>, Dims>) [with Device = Eigen::ThreadPoolDevice; T = std::complex<float>; int Dims = 0; typename tensorflow::TTypes<T, Dims>::Tensor = Eigen::TensorMap<Eigen::Tensor<std::complex<float>, 0ul, 1, long int>, 1>; typename tensorflow::TTypes<T, Dims>::ConstTensor = Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 0ul, 1, long int>, 1>]'
tensorflow/core/kernels/pad_op.cc:112:27:   required from 'void tensorflow::PadOp<Device, T>::Operate(tensorflow::OpKernelContext*, typename tensorflow::TTypes<T, Dims>::ConstTensor, tensorflow::TTypes<int>::ConstMatrix, tensorflow::Tensor*) [with int Dims = 0; Device = Eigen::ThreadPoolDevice; T = std::complex<float>; typename tensorflow::TTypes<T, Dims>::ConstTensor = Eigen::TensorMap<Eigen::Tensor<const std::complex<float>, 0ul, 1, long int>, 1>; tensorflow::TTypes<int>::ConstMatrix = Eigen::TensorMap<Eigen::Tensor<const int, 2ul, 1, long int>, 1>]'
tensorflow/core/kernels/pad_op.cc:73:16:   required from 'void tensorflow::PadOp<Device, T>::Compute(tensorflow::OpKernelContext*) [with Device = Eigen::ThreadPoolDevice; T = std::complex<float>]'
tensorflow/core/kernels/pad_op.cc:159:1:   required from here
third_party/eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorBase.h:703:5: note: the ABI of passing structure with complex float member has changed in GCC 4.4
     pad(const PaddingDimensions& padding) const {
     ^
Target //tensorflow/cc:tutorials_example_trainer up-to-date:
  bazel-bin/tensorflow/cc/tutorials_example_trainer
INFO: Elapsed time: 494.466s, Critical Path: 472.43s
shanker@blackhole ~/projects/tensorflow $

**Comment by vrv** [comment]
There isn't actually an error, that's just an ugly warning in Eigen :).  It looks like it was succesfully built!

```bash

Target //tensorflow/cc:tutorials_example_trainer up-to-date:
bazel-bin/tensorflow/cc/tutorials_example_trainer
```

**Comment by vrv** [comment]
(Feel free to re-open if you disagree)
