### ISSUE TITLE
add summary_feed_dict support to tf.train.Supervisor

### ISSUE THREAD

**Issue by bodokaiser** [tensorflow/tensorflow#6604]
Example use case:

> We want to use `tf.summary.image` on a (computed) tensor which requires a `feed_dict` of some input tensor.

Current work around:

> Manage `summary_op` manually (inside training loop). Cannot use any higher level training helper.

I could also provide a PR on interest.

**Comment by bodokaiser** [comment]
One possible solution I see with `tf.train.MonitoredTrainingSession`:

```python
with tf.train.MonitoredTrainingSession(hooks=hooks) as session:
    while not session.should_stop():
        session.run(train, feed_dict={
            mr: batch[0].eval(session=session),
            us: batch[1].eval(session=session),
        })
```

that we take the `feed_dict` argument of `session.run` and pass it down to every `hook` where we add that `feed_dict` as default to `tf.train.SessionRunArgs`.

**Comment by yaroslavvb** [comment]
What about using feed_fn like in FeedingQueueRunner?

**Comment by yaroslavvb** [comment]
BTW, you can use supervisor `loop` construct to add a modified summary writer:

```
sv = tf.train.Supervisor(..., summary_op=None)
with sv.managed_session() as sess:
    sv.loop(60, lambda: sv.summary_computed(sess, sess.run(summary_op, feed_dict=...)))
    <your training loop>
```

**Comment by bodokaiser** [comment]
This problem is not limited to `TensorLoggingHook` and `SummarySaverHook` but also to custom `SessionRunHook`s which at the moment provide the modular interface to organize such things around your training / testing evaluation.

As we already have support for `init_dict` and `init_fn` on many interfaces (e.g. `tf.train.Supervisor`, `tf.train.Scaffold` I guess it would be consistent to add something similar for evaluation.

At the moment I calls to `monitored_session.run(fetches, feed_dict=...)` already forward this information:

```python
class LoggerHook(tf.train.LoggingTensorHook):

    def before_run(self, run_context):
        run_args = super().before_run(run_context)
        feed_dict = run_context.original_args.feed_dict

       # extract arguments from `monitored_session.run(...)` out of `feed_dict`

        return run_args
```

**Comment by carlthome** [comment]
Related: http://stackoverflow.com/questions/41366248/using-tf-train-supervisors-default-summary-op-on-validation-data

**Comment by yaroslavvb** [comment]
@bodokaiser yes, `feed_dict` is only needed for data external to TensorFlow. So `feed_dict={x: batch[0].eval(session=session),` is a bit odd, since data is in TF already

**Comment by michaelisard** [comment]
@mrry do you have any thoughts? Or reassign...

**Comment by mrry** [comment]
@michaelisard My understanding was that we're deprecating `tf.train.Supervisor` and encouraging people to move to the `tf.train.FooSession` classes, so any features would be added here. Sherry and/or Mustafa are the respective owners for these.

**Comment by carlthome** [comment]
@mrry are you referring to [training hooks](https://www.tensorflow.org/versions/master/api_docs/python/train/training_hooks) with `tf.train.MonitoredSession`?

**Comment by mrry** [comment]
@carlthome Hooks are the main way to add features to a `tf.train.MonitoredSession`, yes. It's possible that such a feature would require changes elsewhere, but I'll let @ispirmustafa comment on that.

**Comment by girving** [comment]
Closing since `tf.train.Supervisor` is deprecated in favor of `tf.train.MonitoredSession`.

**Comment by lhlmgr** [comment]
Hi there, and excuse me for posting on a closed Issue. Thus, `Supervisor` will be deprecated soon and `MonitoredTrainingSession` is the way future way to load/save models and write summaries? Cheers!

**Comment by RylanSchaeffer** [comment]
@girving , @mrry - if `tf.train.Supervisor` will be deprecated soon, can someone edit the programming guide [page](https://www.tensorflow.org/programmers_guide/supervisor) to let people like myself know?

**Comment by ispirmustafa** [comment]
We're in the process of updating those programming guides.

**Comment by RylanSchaeffer** [comment]
@ispirmustafa , awesome!
