### ISSUE TITLE
whether we have another function that have the same function as tf.select in the latest version？

### ISSUE THREAD

**Issue by pengjiao123** [tensorflow/tensorflow#6610]
I found there is no "tf.select" in the latest version（tensorflow） ,so I want to know if we have another function that have the same function as tf.select

**Comment by yaroslavvb** [comment]
From [RELEASE.md for 0.12](https://github.com/tensorflow/tensorflow/blob/c72d891418c326794a913cc13382c104255fe1f2/RELEASE.md#breaking-changes-to-the-api-1)

`Deprecated tf.select op. tf.where should be used instead.`
