### ISSUE TITLE
tensorflow cannot download packages when run ./configure

### ISSUE THREAD

**Issue by louisway** [tensorflow/tensorflow#6613]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

when I run ./configure, below comes out:
ERROR: /home/louis/Documents/dep-tensorflow/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@font_roboto//': Error downloading from https://github.com/polymerelements/font-roboto/archive/v1.0.1.tar.gz to /home/louis/.cache/bazel/_bazel_louis/d4f28d83a590525a3c3f2c81d1c44f93/external/font_roboto: Error downloading https://github.com/polymerelements/font-roboto/archive/v1.0.1.tar.gz to /home/louis/.cache/bazel/_bazel_louis/d4f28d83a590525a3c3f2c81d1c44f93/external/font_roboto/v1.0.1.tar.gz: Timed out connecting to https://github.com/polymerelements/font-roboto/archive/v1.0.1.tar.gz : connect timed out and referenced by '//tensorflow/tensorboard/bower:bower'.

ERROR: /home/louis/Documents/dep-tensorflow/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@graphlib//': Error downloading from https://github.com/cpettitt/graphlib/archive/v1.0.7.tar.gz to /home/louis/.cache/bazel/_bazel_louis/d4f28d83a590525a3c3f2c81d1c44f93/external/graphlib: Error downloading https://github.com/cpettitt/graphlib/archive/v1.0.7.tar.gz to /home/louis/.cache/bazel/_bazel_louis/d4f28d83a590525a3c3f2c81d1c44f93/external/graphlib/v1.0.7.tar.gz: Timed out connecting to https://github.com/cpettitt/graphlib/archive/v1.0.7.tar.gz : connect timed out and referenced by '//tensorflow/tensorboard/bower:bower'.

ERROR: /home/louis/Documents/dep-tensorflow/tensorflow/tensorflow/tensorboard/bower/BUILD:5:1: no such package '@iron_a11y_announcer//': Error downloading from https://github.com/polymerelements/iron-a11y-announcer/archive/v1.0.4.tar.gz to /home/louis/.cache/bazel/_bazel_louis/d4f28d83a590525a3c3f2c81d1c44f93/external/iron_a11y_announcer: Error downloading https://github.com/polymerelements/iron-a11y-announcer/archive/v1.0.4.tar.gz to /home/louis/.cache/bazel/_bazel_louis/d4f28d83a590525a3c3f2c81d1c44f93/external/iron_a11y_announcer/v1.0.4.tar.gz: Timed out connecting to https://github.com/polymerelements/iron-a11y-announcer/archive/v1.0.4.tar.gz : connect timed out and referenced by '//tensorflow/tensorboard/bower:bower'.

INFO: Downloading from https://github.com/polymerelements/iron-a11y-keys-behavior/archive/v1.1.2.tar.gz: 0B

Just as it shows in INFO, it seems it can not download the package that causes the error, and i am sure the internet is ok ,because i could download the package in the web.

### Environment info
Operating System:
UBUNTU 14.04

Bazel Version:
bazel 0.3.2
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
cuda8.0
cuDNN:5.0

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
git clone -b v0.11.0 https://github.com.................
2. The output of `bazel version`

Build label: 0.3.2- (@non-git)
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Sun Jan 1 22:19:10 2017 (1483309150)
Build timestamp: 1483309150
Build timestamp as int: 1483309150

**Comment by gunan** [comment]
I manually tried all the packages in the error messages above, and they all download ok for me.
Also, our CI is able to download all of these packages OK.

Could you try again? maybe it is a transient connection issue on your end.

**Comment by tillahoffmann** [comment]
I had similar troubles because my `bazel` was outdated. It works fine for me on `bazel` 0.4.3.

**Comment by michaelisard** [comment]
@louisway did a newer bazel fix it?

**Comment by jart** [comment]
This was probably due to an ephemeral GitHub outage. At HEAD we've got a new system for redundant downloading where this will never happen again thanks to https://github.com/bazelbuild/bazel/commit/4c67807964e37cfd55bbcda4c6374fcc480bcecc and https://github.com/bazelbuild/bazel/commit/ed7ced0018dc5c5ebd6fc8afc7158037ac1df00d. However we haven't applied it to the TensorBoard downloads yet since that code is generated. It will be soon enough.

**Comment by pedrodiamel** [comment]
sudo /var/lib/dpkg/info/ca-certificates-java.postinst configure
