### ISSUE TITLE
Could not resolve github.com

### ISSUE THREAD

**Issue by thepurpleowl** [tensorflow/tensorflow#6618]
I am trying for tensorflow for poets and while doing the following in docker image
`cd /tensorflow`
`git pull`

error:
`fatal: unable to access 'https://github.com/tensorflow/tensorflow.git/': Could not resolve host: github.com`

### attempted solutions 
followed the issue discussion `https://github.com/discourse/discourse_docker/issues/68`
After editing `/etc/default/docker`, uncommenting the DOCKER_OPTS line makes no difference.

**Comment by gunan** [comment]
This one looks like it is an internet/github connection issue.
There is nothing we can do for this on TF side, as the problem happens before you even connect to github.

**Comment by thepurpleowl** [comment]
but I am able to connect and reach github.com on browser.

**Comment by gunan** [comment]
Still, docker, git and github are tools/resources we use but we do not manage.
I do not see how we can help with this.

**Comment by thepurpleowl** [comment]
As for some people, the issue solved by editing `/etc/default/docker` in the discourse_docker issue `https://github.com/discourse/discourse_docker/issues/68`, I hope there is something you can suggest.

**Comment by Speedstack79** [comment]
I solved this by changing my DNS from the one it automatically gets to the OpenDNS one (208.67.222.22 for main and 208.67.220.220 for the alternative).
