### ISSUE TITLE
Where is the skflow examples ??

### ISSUE THREAD

**Issue by eromoe** [tensorflow/tensorflow#6623]
https://github.com/tensorflow/skflow/tree/master/examples

It says skflow examples has moved to https://github.com/tensorflow/skflow/tree/master/examples, but this  folder is empty.

**Comment by gunan** [comment]
Looks like they are moved under `tensorflow/examples/learn` by https://github.com/tensorflow/tensorflow/commit/f9b6d55ffd630082efd088fca927f7d991fdf3fa#diff-4b9849eed2f5253aaddd26fbf7afdef2

We might need to update the pointers from the old repo.

**Comment by ilblackdragon** [comment]
Indeed, skflow is renamed to learn [tf.learn] so examples have moved.
I've updated pointer and we probably should remove that repository soon.
