### ISSUE TITLE
TypeError: strided_slice() takes at least 4 arguments (3 given)

### ISSUE THREAD

**Issue by xusong2008** [tensorflow/tensorflow#6627]
I have check the error.  And I find that the bug has been fixed in github code.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_ops.py

lastest github version:
`def strided_slice(input_,
                  begin,
                  end,
                  strides=None,`

lastest whl version:
`def strided_slice(input_,
                  begin,
                  end,
                  strides,`

However tensorflow_gpu-0.12.1-cp27-none-linux_x86_64.whl doesn't  synchronize with github.

How can I upgrade tensorflow from lastest github code?

**Comment by sporteman** [comment]
Same error here with OSX..

**Comment by michaelisard** [comment]
Please see the [instructions on building from sources](https://www.tensorflow.org/get_started/os_setup#installing_from_sources).

**Comment by avloss** [comment]
thanks for the link. Though I've found building for Mac with GPU support extemely hard (didn't work for me at the end)

**Comment by WakedupChan** [comment]
try use commands as follows:
pip uninstall tensorflow
pip install tensorflow
