### ISSUE TITLE
Convert TFlite buffer created using TF1 to TF2 TFlite buffer

### ISSUE THREAD

**Issue by mrtpk** [tensorflow/tensorflow#66281]
Hi Team,

Context:
I have a bunch of TFlite files that were created using [schema.fbs](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema.fbs) before [`version` was added into the schema](https://github.com/tensorflow/tensorflow/blob/20cb0d184f27341418c77ce3432ce46376040426/tensorflow/lite/schema/schema.fbs#L1612). The latest tflite buffers generated using TF2 has `version` and other newly added fields.

Question:
Is there a way to convert tflite buffers to new tflite buffers that adhere to the new schema? Any pointer is very much appreciated. Thanks.

**Comment by TeachVoyager** [comment]
Did you try using, the Tflite converter tool to convert the old to the new format? 

From what I've been seeing floating around google it's possible to convert Tflite files to adhere to the new scheme.

**Comment by sawantkumar** [comment]
Hi @mrtpk ,

Can you please try using the tflite converter tool and just use different names for the input and output model and let me know if it works for you ?
