### ISSUE TITLE
Feature request: configuration files for tensorflow

### ISSUE THREAD

**Issue by tillahoffmann** [tensorflow/tensorflow#6629]
Matplotlib and theano provide [`matplotlibrc`](http://matplotlib.org/users/customizing.html) and [`theanorc`](http://deeplearning.net/software/theano/library/config.html) files to configure the libraries, respectively. It would be great if we could add such functionality to tensorflow. 

In particular, it would be great to 

* expose a `floatX` variable such that it is straightforward to switch between 16, 32, and 64 bit representations without having to modify code
* expose the [`config.proto`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/config.proto)

A JSON representation of the configuration may be more suitable than the formats used by matplotlib and theano because it can more easily capture the hierarchical structure of the configuration.

**Comment by yaroslavvb** [comment]
Can you give the use-case you need this for? In this specific case, the `floatX` option doesn't seem to be very useful -- `float32` support is usually there, but `float16/float64` is spotty. For non-trivial calculation, switching away from `float32` type will usually give "kernel not registered" error. Also .theanorc has "device" setting, but that doesn't seem very applicable to TensorFlow. It was designed to use multiple devices, and the most common case is two devices -- cpu+(1 or more GPUs), the latter being configurable with CUDA_VISIBLE_DEVICES.

When using distributed TensorFlow, you could have more than one session and use different configs for local vs. grpc session worker vs grpc session ps. The raises the question of global default -- which session they would apply to

**Comment by tillahoffmann** [comment]
I often have the need to switch between 32 and 64 bits because 32 bits do not always suffice for the models I am interested in. If possible, I use 32 bits because I can train on the GPU. If that doesn't work I'd like to be able to switch to 64 bit. But maybe I can just define a `floatX` in my environment conditional on env variables.

Regarding the `config.proto`: we often want to use different default arguments than the default arguments defined by tensorflow. It would be nice to keep these defaults in a central location which each individual developer using our repository can customise to their needs by adding a `.tensorflowrc` to their `$HOME`, for example.

**Comment by yaroslavvb** [comment]
Regarding "float" type. Right now "float32" default is hardcoded in almost every op (github [search](https://github.com/tensorflow/tensorflow/search?p=3&q=%22dtype%3Dtf.float32%22&type=Code&utf8=%E2%9C%93).

One could potentially factor it out. But right now so few ops support non-float32 type, I wonder if other types make sense as a default. For instance, right now convolution doesn't support float64.

Regarding having global session settings/run options, I think more details are needed of how the semantics of it would work.

**Comment by vrv** [comment]
Unfortunately, I think this is a huge support nightmare, since most people forget what settings they have in their home rc files.  I think it's unlikely we'll want to do this any time soon, though you could build a library to do this on your own (read your own .tensorflowrc file to populate the right fields in a ConfigProto).

**Comment by tillahoffmann** [comment]
Good idea. Maybe we'll just do that. Would `tf.contrib.rc` be a sensible place to put this if we end up sharing it?

**Comment by vrv** [comment]
For now, I think it would be best to have it in an external repo which you can advertise here.

If you're willing to write code to read a file from $HOME to populate a ConfigProto, you could also just write a default ConfigProto that you use in your own code...
