### ISSUE TITLE
Cross-compile Android demo for CUDA

### ISSUE THREAD

**Issue by hamidb** [tensorflow/tensorflow#663]
I was wondering how can I build the android demo with GPU support. I have a device with CUDA capability (Tegra K1 device). What I did was to pass a `--config=cuda` when building the demo. Is it supposed to be enough to enable gpu support by only passing  `--config=cuda`?

I ./configured the workspace given cuda and cudnn path and also specified proper `compute_capability=3.2`
Now that the app is running on my device, how can I make sure if it has gpu support? I did not see a noticeable speed up by doing this. So, What is the proper way to run and validate it?

P.S.
I am using CUDA 6.0. 
I modified few lines to ignore CUDA 7.5 and use 6.0 instead.

**Comment by martinwicke** [comment]
If you want to make sure you are placing ops on the GPU, you can find a test that can use the GPU (such as the [RoundTest](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/math_ops_test.py#L45)), and modify it so the session is created with `force_gpu=True`:

    with self.test_session(use_gpu=True, force_gpu=True):

If the test then fails, that's a strong indicator you're not running a GPU. The RoundTest is a good one because it has only ops that can actually run on a GPU, other tests have a mixture, and `force_gpu` is pretty remorseless.

**Comment by hamidb** [comment]
Thanks @martinwicke. Actually, the code you mentioned (RoundTest) is written in Python. What I need is a C++ code that I can test it on my android device. So, I need a piece of code that can be compiled with GPU=on and has the capability to be run under my android device. 
I can not test it on my PC, as it does not come with a GPU device. 

Do you know how can I tell bazel to use gpu code rather than scalar version. And does that work for the android demo? I know I can pass --config=cuda for the running `//tensorflow/cc:tutorials_example_trainer`. But it doesn't seem to be enough for the android demo.

**Comment by martinwicke** [comment]
`--config=cuda` will compile for GPU, but that doesn't mean that all ops are necessarily run on GPU. If you have a `SessionOptions` object, you can `set_log_device_placement(true)`, which will log the placement of ops, and you can check that they actually run on GPU.

**Comment by hamidb** [comment]
Thank you @martinwicke . I will test that option to make sure and will post the result here.
But according to the unchanged performance of the process I guess it is not gpu enabled.

**Comment by hamidb** [comment]
I tried to log the used device in native jni part. However, setting `log_device_placement` is not as straight forward as in Python. 
As a desperate try I did the following change into the Android demo:
```
    tensorflow::GraphDef tensorflow_graph;
    LOG(INFO) << "Graph created.";
    graph::SetDefaultDevice("/gpu:0", &tensorflow_graph);
```

Still not sure if it uses CUDA device or not.

**Comment by hamidb** [comment]
One more update:
`config.device_count_size()` returns 0 at run-time??

**Comment by martinwicke** [comment]
You ran configure with TF_UNOFFICIAL_SETTING, right?

**Comment by hamidb** [comment]
That's correct.

**Comment by martinwicke** [comment]
The set_log_device_placement is a c++ function on SessionOptions -- nothing in c++ is as straightforward as in python, but it shouldn't be hard to do if you're running everything from c++ anyway.

**Comment by vrv** [comment]
http://cudamusing.blogspot.com/2015/11/building-tensorflow-for-jetson-tk1.html might be a relevant post from shortly after our release -- lots has changed but there might be some helpful hints there.

**Comment by hamidb** [comment]
@martinwicke I don't find (grep) `set_log_device_placement`. There is no such a method. Can you provide more details.
@vrv I have seen it. I got some of my modifications from that post. However, it is for Jetson device with Linux_for_Tegra that makes the story different.

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/config.proto#L92

Which is a structure within https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/public/session_options.h#L58

which you can pass to the Session() constructor

**Comment by hamidb** [comment]
Sorry I'm not familiar with Proto message format.
I set the `log_device_placement` to true. And it seems everything is running on cpu0.
At least I know on which device the process is being executed.
Now the main question is still left open. How to make it run on gpu?

**Comment by hamidb** [comment]
BTW, 
I am able to build other examples like example_trainer with CUDA. 
My problem is the android demo.

**Comment by martinwicke** [comment]
Duh. Sorry, I should have noticed that. It's quite possible that the build rules for android are not properly set up for GPU support at all. Assigning someone with better knowledge about mobile issues.

**Comment by andrewharp** [comment]
The Android TF build targets do not currently support CUDA.

A major reason for this is that Tensorflow currently requires CUDA 7.0 and the NVIDIA Codeworks support for 7.0+ is very limited -- currently only the Shield Android TV is listed as 7.0 capable (see http://docs.nvidia.com/gameworks/index.html#developertools/mobile/codeworks_android/codeworks_android_release_notes.htm).

This could change in the future if support improves for CUDA on Android -- though if you get something working on your own please let us know!

**Comment by bhack** [comment]
Is there any plan to use renderscript on android devices?

**Comment by hamidb** [comment]
Thanks @andrewharp. 
I was aware about the point. however, I like to use an unofficial approach. 
I was able to solve all compatibility issues. 
Assuming a CUDA 7.0 device, how we can tell bazel to build the android demo with GPU support?
Passing --config=cuda does not seem to work for the Adnroid demo, but it worked for other native examples on x86.
Some useful effort on bringing TF to Cuda < 7.0 (Jetson TK1) at
http://cudamusing.blogspot.ca/2015/11/building-tensorflow-for-jetson-tk1.html

**Comment by andrewharp** [comment]
@hamidb This is something that possibly may come in the future, but we can't support at this time.

If you wish to proceed on your own the best pointer I can give you is to try the NVIDIA Codeworks combined with a custom Bazel build rule such as [this](https://gist.github.com/andrewharp/e221ca9ae629561442e3) (you would need to modify it obviously), which would let you compile the kernels into libraries that you could then link in as dependencies. I can't speak to any further issues you would encounter, though.

**Comment by petewarden** [comment]
@bhack We have been working with the Renderscript team (they've recently introduced some intrinsics for key operations we need like GEMMs) but we don't have an estimate for when and how that will be exposed.

**Comment by bhack** [comment]
@petewarden Yes I asked because I've noted in the API level 24.

**Comment by MisayaZ** [comment]
@petewarden I am very in interested in using the GPU on Android with tensorflow. Does Tensorflow  have mobile GPU support with Renderscript or OpenCL currently ?

**Comment by petewarden** [comment]
TensorFlow doesn't have Renderscript support in yet, and OpenCL is not in there either.

**Comment by bhack** [comment]
For  OpenCL you can follow https://github.com/tensorflow/tensorflow/issues/22

**Comment by andrewharp** [comment]
I believe the original issue was addressed, closing due to lack of recent activity.

**Comment by natanielruiz** [comment]
I just wanted to see what the plans were for Renderscript or CUDA support for TF on Android. Can we have any updates on future releases or ways of using the GPU for the Android demo ? Thanks :)

**Comment by natanielruiz** [comment]
I'm here to bump my earlier question.

**Comment by yaroslavvb** [comment]
Someone from qualcomm just presented at TF dev summit saying 8x speed-up of image recognition on qualcomm chips using TensorFlow with Hexagon library optimization

**Comment by PKUEcho** [comment]
Just want to ask what's the stage of GPU support for Android platform? I ask this because it's a very important feature for any deep learning framework, and now there are already some related research papers published. If tensorflow supports GPU on Android platform, I guess, there be many more followers :)

**Comment by llhe** [comment]
For Android GPU support, you can checkout [MACE](https://github.com/xiaomi/mace), which use OpenCL for mobile GPUs like Adreno, Mali and PowerVR etc. There are some [benchmark results](https://github.com/XiaoMi/mace/issues/1).

**Comment by ewilderj** [comment]
Hi @llhe — please don't use TensorFlow GitHub issues for promotional purposes, it's off-topic. We are glad that there are many competing open source frameworks, but let's stay on-topic for TensorFlow assistance within the TensorFlow Github organization. That will help us all use our time most efficiently to help users.
