### ISSUE TITLE
[Docs] A mismatch bug in api_docs 

### ISSUE THREAD

**Issue by DjangoPeng** [tensorflow/tensorflow#6630]
There is a mismatch bug in api_docs about [tf.graph](https://www.tensorflow.org/api_docs/python/framework/core_graph_data_structures#Graph). It's easy to find that **tf.Graph.__init__() {:#Graph.init}** is a error. And I check the original script [ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L2003), it seems like the `{:#Graph.init}` is added by other script. 
At the same time, it causes the index `URL#Graph.init` ineffectively.

**Comment by DjangoPeng** [comment]
@mrry @drpngx Could you have a look? And re-pin the corresponding reviewer?

**Comment by drpngx** [comment]
Right, it's incorrectly parsed by the markdown. Looping internally. We have a new version of the docs coming soon so we might not fix this one.

**Comment by martinwicke** [comment]
Yes, I think the {} anchors will go away entirely.

**Comment by DjangoPeng** [comment]
@drpngx Yep, I do agree with you. It's not a separate problem, but a more general issue of markdown parser. Look forward to the new version of G3docs.
