### ISSUE TITLE
I think we should use a separate api token named for this view. We may have additional clients of the APIs in the future, and we should be able to make the decision to limit one of the other of these endpoints from those additional clients.

### ISSUE THREAD

**Issue by Darknight1500** [tensorflow/tensorflow#66302]
I think we should use a separate api token named for this view. We may have additional clients of the APIs in the future, and we should be able to make the decision to limit one of the other of these endpoints from those additional clients.

_Originally posted by @rjsparks in https://github.com/ietf-tools/datatracker/pull/7291#issuecomment-2037572500_

**Comment by sushreebarsa** [comment]
@Darknight1500 Could you provide more context on the issue reported here?
Thank you!

**Comment by sushreebarsa** [comment]
@rjsparks Thank you for your response here. Closing this issue for now.
