### ISSUE TITLE
tf-master-win-bzl is failing due to dependency on //tensorflow/contrib/framework:framework_py

### ISSUE THREAD

**Issue by meteorcloudy** [tensorflow/tensorflow#6631]
http://ci.tensorflow.org/job/tf-master-win-bzl/245/

Many targets, including `//tensorflow/contrib/framework:framework_py`, in `//tensorflow/contrib:contrib_py` currently don't build on Windows with Bazel, it is [excluded from `//tensorflow/python:python`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/BUILD#L72)

cc0de74ff0fbaee205826f7cef23e91892fb5db2 introduced the dependency on `//tensorflow/contrib/framework:framework_py` which caused the failure.
```
$ bazel query 'somepath(//tensorflow/tools/pip_package:build_pip_package, //tensorflow/contrib/framework:python/ops/_variable_ops.so)'
//tensorflow/tools/pip_package:build_pip_package
//tensorflow/examples/tutorials/mnist:package
//tensorflow/examples/tutorials/mnist:input_data
//tensorflow/contrib/learn/python/learn/datasets:datasets
//tensorflow/contrib/framework:framework_py
//tensorflow/contrib/framework:python/ops/_variable_ops.so
```
//cc @jart @gunan

**Comment by gunan** [comment]
https://github.com/tensorflow/tensorflow/pull/6621 already out for temporary fix.
It is waiting for approval.
