### ISSUE TITLE
Tensorboard does not show any data

### ISSUE THREAD

**Issue by nalyat** [tensorflow/tensorflow#6636]
On latest git head, when running the mnist_with_summaries.py, tensorboard does not show any data:

![distributions](https://cloud.githubusercontent.com/assets/5008257/21643171/2f91f656-d287-11e6-8e83-d9af45e7c978.png)
![histogram](https://cloud.githubusercontent.com/assets/5008257/21643170/2f91d996-d287-11e6-99e3-f2371a84f448.png)
![images](https://cloud.githubusercontent.com/assets/5008257/21643173/2f924f0c-d287-11e6-911e-34a7dc44a00a.png)
![scalars](https://cloud.githubusercontent.com/assets/5008257/21643172/2f91f16a-d287-11e6-9734-c258b9973832.png)

you can find the generated events here:
[events.zip](https://github.com/tensorflow/tensorflow/files/684693/events.zip)

Operating System: Linux / x86_64

**$ git rev-parse HEAD**
7c36309c37b04843030664cdc64aca2bb7d6ecaa

**$ bazel version**
Build label: 0.4.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 22 12:31:25 2016 (1482409885)
Build timestamp: 1482409885
Build timestamp as int: 1482409885

the mnist_with_summaries.py:
./tensorflow/examples/tutorials/mnist/mnist_with_summaries.py

The --inspect output seems to find the data:
**$ tensorboard --logdir /tmp/tensorflow/mnist/logs/mnist_with_summaries/train/ --inspect**
[inspect.txt](https://github.com/tensorflow/tensorflow/files/684700/inspect.txt)

**Comment by nalyat** [comment]
This was due to a lagging chrome browser

**Comment by willshion** [comment]
same problem
