### ISSUE TITLE
not registered 'TensorArrayV2' on 12.1 on MacOS CPU

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#6640]
I'm getting
`tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'TensorArrayV2'
` after upgrading to 0.12.1 on MacOS. Same code works on 0.11 on Mac and 0.12.1 on Ubuntu CPU

This op seems to be created by dynamic RNN code

```
node {
  name: "global/RNN/TensorArray_1"
  op: "TensorArrayV2"
  input: "global/RNN/strided_slice_2"
  device: "/cpu:0"
  attr {
    key: "clear_after_read"
    value {
      b: true
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "dynamic_size"
    value {
      b: false
    }
  }
  attr {
    key: "tensor_array_name"
    value {
      s: "global/RNN/dynamic_rnn/input_0"
    }
  }


```
Sorry don't have a shorter repro atm, but a long repro is to follow install instructions on https://github.com/openai/universe-starter-agent and run it with Mac CPU tensorflow        

```
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.1-py3-none-any.whl
pip install -I --upgrade setuptools
pip install --upgrade $TF_BINARY_URL
python train.py --num-workers 2 --env-id PongDeterministic-v3 --log-dir /tmp/pong
```

**Comment by yaroslavvb** [comment]
Closing it for now since low-priority, will reopen with better reproducible example if this comes up again

**Comment by ebrevdo** [comment]
If you rebuild your graph using a newer version of tf Python, it'll point
to the new TensorArray ops.
