### ISSUE TITLE
Tensorboard doesn't show anything in 0.12

### ISSUE THREAD

**Issue by gissemari** [tensorflow/tensorflow#6642]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
I was having IOErrors but after trying in different browsers. After reading issue [#4830](https://github.com/tensorflow/tensorflow/issues/4830), I decided to upgrade tensorflow to 0.12, even when it says the 0.11 is fixed.

A [link](https://www.tensorflow.org/get_started/os_setup#pip_installation) to the pip package I installed: tensorflow-0.12.1-cp27-none-linux_x86_64.whl

### Minimal reproducible example
So, the IOErrors did dissapeared but I stil can't show any graph or scalar or summary. After following the debug everything seems fine:

```
INFO:tensorflow:TensorBoard is in debug mode.
INFO:tensorflow:Starting TensorBoard in directory /home/yunli/Documents/Research/articles/australian language/tensorFlow_use
INFO:tensorflow:TensorBoard path_to_run is: {'/home/Documents/Research/articles/australian language/tensorFlow_use/logs': None}
INFO:tensorflow:Event Multiplexer initializing.
INFO:tensorflow:Event Multiplexer done initializing
INFO:tensorflow:TensorBoard reload process beginning
INFO:tensorflow:Starting AddRunsFromDirectory: /home/Documents/Research/articles/australian language/tensorFlow_use/logs
INFO:tensorflow:Done with AddRunsFromDirectory: /home/Documents/Research/articles/australian language/tensorFlow_use/logs
INFO:tensorflow:TensorBoard reload process: Reload the whole Multiplexer
INFO:tensorflow:Beginning EventMultiplexer.Reload()
INFO:tensorflow:Finished with EventMultiplexer.Reload()
INFO:tensorflow:TensorBoard done reloading. Load took 0.001 secs
INFO:tensorflow:TensorBoard is tag: 39
Starting TensorBoard 39 on port 6006
(You can navigate to http://127.0.1.1:6006)
```
However, I try again all the browsers (Chrome, Firefox and Chromium) and nothing appear. I'll provide one of the event files I [got](https://drive.google.com/file/d/0B_CAQhE3IU1Vc1Z0SDdoa3VXdEE/view?usp=sharing).

**Comment by aselle** [comment]
What model are you trying to visualize?  What python model? How do I run it? Is it a standard example or your code? If it is your code, try one of the standard tutorial examples and make sure you can get that to work. Thanks!

**Comment by gissemari** [comment]
Thanks! It was my code based on the [tutorial](https://www.tensorflow.org/how_tos/summaries_and_tensorboard/). I tried the mnist_with_summaries.py and it is working.  In my code, I am using the suggested function :

```
def variable_summaries(var):
  """Attach a lot of summaries to a Tensor (for TensorBoard visualization)."""
  with tf.name_scope('summaries'):
    mean = tf.reduce_mean(var)
    tf.summary.scalar('mean', mean)
    with tf.name_scope('stddev'):
      stddev = tf.sqrt(tf.reduce_mean(tf.square(var - mean)))
    tf.summary.scalar('stddev', stddev)
    tf.summary.scalar('max', tf.reduce_max(var))
    tf.summary.scalar('min', tf.reduce_min(var))
    tf.summary.histogram('histogram', var)
```
But using the new functions to merge and write
```
merged = tf.summary.merge_all()
train_writer = tf.summary.FileWriter('./logs/train',sess.graph)
init = tf.global_variables_initializer()
```
instead of the deprecated
```
merged = tf.summary.merge_all()
train_writer = tf.train.SummaryWriter('./logs/train',sess.graph)
tf.initialize_all_variables()
```
And finally recording the summaries. There's no error when I run my code.
```
summary, trnresult = sess.run([merged, accuracy], feed_dict={x: batch_xs,y: batch_ys,})
train_writer.add_summary(summary, step)
```

What else can I be missing?

**Comment by michaelisard** [comment]
This kind of usage question is best asked on [Stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow). Github issues are for bug reports and installation issues.
