### ISSUE TITLE
https://www.tensorflow.org/robots.txt is disallowing all Search Engines crawling www.tensorflow.org.

### ISSUE THREAD

**Issue by facan1** [tensorflow/tensorflow#6652]
[https://www.tensorflow.org/robots.txt] 
User-agent: *
Disallow: /

Can you please allow Search Engines ?

Thanks,
Fabrice Canel
Microsoft Bing

**Comment by gunan** [comment]
I think this is still not resolved. I still do not see r0.12 results in bing.
@dr4b @wolffg

**Comment by dr4b** [comment]
Yeah, I think this one needs to go to Wolff -- sorry for not redirecting earlier.

**Comment by gunan** [comment]
@wolffg is this resoled?

**Comment by wolffg** [comment]
This was fixed some time ago.

[https://www.tensorflow.org/robots.txt]
User-agent: *
Disallow: /s/results*
Sitemap: https://www.tensorflow.org/sitemap.xml

If we need to change it again, please re-open or re-file.
