### ISSUE TITLE
http://zlib.net/zlib-1.2.8.tar.gz is down, breaks configure

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#6656]
Need something like https://github.com/yaroslavvb/tensorflow/commit/fbc8bef52fc20d1c26290979f956e781bc863be8 to fix ./configure since "http://zlib.net/zlib-1.2.8.tar.gz" is down

**Comment by gunan** [comment]
Resolved in master with ecf97ee5f2e386be31fde8ca790d48786b969103, and in r0.12 with 1e317b1f7dc5ccf04fc51ac96d97f5bdaefa9af9
