### ISSUE TITLE
make error in Tensorflow Lite Micro 

### ISSUE THREAD

**Issue by abcd123abcd** [tensorflow/tensorflow#66616]
System information

Linux Ubuntu 18.04
Python version: 2.7.17
The problem
I'm trying to generate the example projects from the TensorFlow Lite for Microcontrollers C++ library with Make and I run in this error:

Traceback (most recent call last):
  File "tensorflow/lite/micro/tools/make/generate_keil_project.py", line 122, in <module>
    parse_args()
  File "tensorflow/lite/micro/tools/make/generate_keil_project.py", line 118, in parse_args
    main(unparsed, flags)
  File "tensorflow/lite/micro/tools/make/generate_keil_project.py", line 40, in main
    six.ensure_str(flags.executable),
AttributeError: 'module' object has no attribute 'ensure_str'
tensorflow/lite/micro/examples/network_tester/Makefile.inc:41: recipe for target 'tensorflow/lite/micro/tools/make/gen/linux_x86_64_default/prj/network_tester_test/keil/keil_project.uvprojx' failed
make: *** [tensorflow/lite/micro/tools/make/gen/linux_x86_64_default/prj/network_tester_test/keil/keil_project.uvprojx] Error 1

Sequence of commands
git clone https://github.com/tensorflow/tflite-micro
cd tflite-micro
make -f tensorflow/lite/micro/tools/make/Makefile generate_projects

**Comment by sawantkumar** [comment]
Hi @abcd123abcd ,

I tried replicating your error but i kept running into library issues. Can you please update your python version and then try installing tflite micro and let me know if the issue still persists for you .
