### ISSUE TITLE
TFLite: Stable Delegate: how to use stable_delegate with python API

### ISSUE THREAD

**Issue by suyash-narain** [tensorflow/tensorflow#66632]
I am using tflite 2.16.1

My target is an aarch64 linux system

I have a tflite stable_delegate .so shared library, and a stable_delegate settings json file called 'stable_delegate_settings.json which I can execute using TFLite benchmark model using the commands

./benchmark_model --graph=model.tflite --stable_delegate_settings_file=stable_delegate_settings.json

this executes the model using stable delegate through the json stable_delegate settings file.

I want to know how can I use this stable_delegate_settings.json file to execute the model via stable delegate using python API.

I am not sure whats the format to execute stable delegate using tflite.load_delegate, since it searches for the .so shared library, not the json settings file. 

thanks

**Comment by suyash-narain** [comment]
Hi @sushreebarsa 
any updates on this?
thanks

**Comment by sushreebarsa** [comment]
@suyash-narain 
tflite.load_delegate directly searches for the shared library (.so file) and doesn't handle settings files like stable_delegate_settings.json. There's a workaround to achieve your goal using the Python API.
Could you try to Parse the `stable_delegate_settings.json` file;
Firstly Import the json library:
```
import json

```
then Open the stable_delegate_settings.json file:

```
with open('stable_delegate_settings.json', 'r') as f:
  settings = json.load(f)

```

Thank you!

**Comment by suyash-narain** [comment]
Hi @sushreebarsa 
thank you for your reply. 

So do I need to specify this 'settings' somewhere in my python code, or will the delegate automatically get loaded and execute the tflite model? 

since interpreter api loads external shared delegate library .so files using tfltie experimental load_delegate function... 
so does it need to be provided this settings variable with loaded json contents?

thanks

**Comment by sushreebarsa** [comment]
@suyash-narain If you're using a custom delegate library with its own settings, follow the TFLite delegate loading [documentation](https://www.tensorflow.org/lite/performance/delegates) to incorporate it. There isn't a well-established workaround to directly use the stable delegate with the Python API for TFLite.
Thank you!

**Comment by KozAAAAA** [comment]
@suyash-narain Have you managed to use Python API to run the stable delegate?

**Comment by KozAAAAA** [comment]
@sushreebarsa How am I supposed to use the **stable delegate** using Python API if my `.json` file looks like this:
```bash
{
	"stable_delegate_loader_settings": {
		"delegate_path": "/usr/lib/libneuron_stable_delegate.so"
	},
	"neuron_delegate_settings": {
		"execution_priority": NEURON_PRIORITY_HIGH,
		"optimization_hint": NEURON_OPTIMIZATION_NONE,
		"execution_preference": NEURON_FAST_SINGLE_ANSWER,
		"allow_fp16": true,
		"use_ahwb": true
	}
}
```
Note that `libneuron_stable_delegate.so` does not contain create and delete sybmols.

**Comment by KozAAAAA** [comment]
Is there any way to make it work? It's just for evaluation purposes so not so well-established method is fine as well.
