### ISSUE TITLE
tf.train.Saver does not restore input queue

### ISSUE THREAD

**Issue by bodokaiser** [tensorflow/tensorflow#6666]
**example.py**
```python
import tensorflow as tf

queue = tf.train.string_input_producer(['data.txt'])

reader = tf.TextLineReader()
_, line = reader.read(queue)

global_step = tf.Variable(0, trainable=False, name='global_step')
global_step_op = tf.assign_add(global_step, 1)

with tf.Session() as sess:
    saver = tf.train.Saver()
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord=coord)

    latest_checkpoint = tf.train.latest_checkpoint('/tmp')
    if latest_checkpoint:
        saver.restore(sess, latest_checkpoint)
        print('restored from', latest_checkpoint)
    else:
        sess.run([
            tf.local_variables_initializer(),
            tf.global_variables_initializer(),
        ])

    for i in range(5):
        value, step = sess.run([line, global_step_op])

        print(value, step)

    coord.request_stop()
    coord.join(threads)

    saver.save(sess, '/tmp/model')
```

**data.txt**
```txt
line 1
line 2
line 3
line 4
line 5
line 6
```

Will output on first run `python3 example.py`:
> b'line 1' 1
> b'line 2' 2
> b'line 3' 3

Will output on second run `python3 example.py`:
> restored from /tmp/model
> b'line 1' 4
> b'line 2' 5
> b'line 3' 6

but expected:
> restored from /tmp/model
> b'line 4' 4
> b'line 5' 5
> b'line 6' 6

**Comment by yaroslavvb** [comment]
I think that's working as intended -- Saver only restores parameters, and queues don't have those. Recreating Queue op resets it to the beginning.

**Comment by bodokaiser** [comment]
In my case it caused a systematic error in my hyperparameter evaluation however it should be easy to work a way around (e.g. always complete one epoch).

**Comment by bodokaiser** [comment]
If someone finds this. It should also be possible to use `reader.restore_state()` for this purpose. [See API docs](https://www.tensorflow.org/api_docs/python/io_ops/readers#TFRecordReader.restore_state)

**Comment by gabrielleyr** [comment]
@bodokaiser did you try the solution of using reader.restore_state()? Did your Queue save correctly? I'm having huge problems with my model suddenly seeming overtrained when I save/reload it. Looks like it's seeing old data.

**Comment by gabrielleyr** [comment]
@yaroslavvb How would you suggest saving a Queue if the full dataset is not used at the point of saving? In that case, we need to keep the state of the Queue so it doesn't see the same old data again on restoring. If we save a .meta and restore the saver as in saver.restore(sess, tf.train.latest_checkpoint("./model/")), will that save the Queue state?
