### ISSUE TITLE
bad zlib link in core/BUILD

### ISSUE THREAD

**Issue by bgrayburn** [tensorflow/tensorflow#6668]
even though https://github.com/tensorflow/tensorflow/issues/6594 fixed the link to zlib in workspace.bzl, I'm getting another error looking for zlib at a bad link during the bazel build. Here's the error: 
```
ERROR: /opt/tensorflow/models/syntaxnet/tensorflow/tensorflow/core/BUILD:911:1: no such package '@zlib_archive//': Error downloading from http://zlib.net/zlib-1.2.8.tar.gz to /root/.cache/bazel/_bazel_root/9f6232783b216d8ac3748a33750481a1/external/zlib_archive: Error downloading http://zlib.net/zlib-1.2.8.tar.gz to /root/.cache/bazel/_bazel_root/9f6232783b216d8ac3748a33750481a1/external/zlib_archive/zlib-1.2.8.tar.gz: 404 Not Found: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /zlib-1.2.8.tar.gz was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
 and referenced by '//tensorflow/core:lib_internal'.
____Loading package: @local_config_cc//
ERROR: /opt/tensorflow/models/syntaxnet/tensorflow/tensorflow/core/BUILD:911:1: no such package '@zlib_archive//': Error downloading from http://zlib.net/zlib-1.2.8.tar.gz to /root/.cache/bazel/_bazel_root/9f6232783b216d8ac3748a33750481a1/external/zlib_archive: Error downloading http://zlib.net/zlib-1.2.8.tar.gz to /root/.cache/bazel/_bazel_root/9f6232783b216d8ac3748a33750481a1/external/zlib_archive/zlib-1.2.8.tar.gz: 404 Not Found: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /zlib-1.2.8.tar.gz was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
```

**Comment by bgrayburn** [comment]
sorry the title is a bad description: the line in zlib is line 1136 and doesn't directly contain the link, not sure how the link gets called

**Comment by inflation** [comment]
Have you tried the patch in #6594 to replace it with 1.2.10?

**Comment by bgrayburn** [comment]
I was trying that, but I believe the fix has been merged to master correct? I'm probably just doing something stupid *facepalm*

**Comment by vrv** [comment]
We've merged to our latest stable branch (0.12) and master, so there's not much we can do here.  I suspect your code / environment / git is synced to an earlier commit -- try updating the branch and the problem should go away.  Hope that helps!

**Comment by bgrayburn** [comment]
sorry my fault, it was a submodule that wasn't updated. thanks for responding!

**Comment by harshsp31** [comment]
How did you update that submodule? @bgrayburn

**Comment by bgrayburn** [comment]
@harshsp31 been awhile since I did this, but should just need to go to head of master in tensorflow/models, then I probably did something silly like `cd` into the tensorflow submodule folder and pull, but you should probably do `git submodule update --recursive --remote` in the tensorflow/models folder to update any and all submodules.

**Comment by harshsp31** [comment]
@bgrayburn Thank you for helping me out. I found the fix :)
