### ISSUE TITLE
Python3 pickle treat tf.gfile.GFile wrong

### ISSUE THREAD

**Issue by inflation** [tensorflow/tensorflow#6669]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
None

### Environment info
Operating System: macOS Sierra 10.12.2

Installed version of CUDA and cuDNN: None
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`): None

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
4d924e796368163eff11a8151e8505715345f58d

2. The output of `bazel version` 
0.4.3-homebrew

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

```
import tensorflow as tf
import pickle

f = tf.gfile.GFile("data_batch_1")
pickle.load(f, encoding='latin1')
```

### What other attempted solutions have you tried?
I tried to manually read all data into a variable: `s = f.read()` and unpickle it: `pickle.loads(s, encoding='latin')`. It works well.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

`TypeError: a bytes-like object is required, not 'str'`

I don't know why this happened. I checked the file_io code, and it returns byte object when calling `read`. So maybe this is something about pickle, any ideas?

**Comment by michaelisard** [comment]
This kind of usage question is best asked on [Stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow). Github issues are for bug reports and installation issues.

**Comment by inflation** [comment]
I believe it's a bug about how we implement `file_io`'s `readline()`. It would return `str`. 
But according to the python3 pickle document:

> The argument file must have two methods, a read() method that takes an integer argument, and a readline() method that requires no arguments. **Both methods should return bytes.** Thus file can be an on-disk file opened for binary reading, an io.BytesIO object, or any other custom object that meets this interface.

Any thoughts?

**Comment by michaelisard** [comment]
@sherrym what do you think?

**Comment by orlov-alexander-dd** [comment]
I can confirm this bug in Ubuntu 16.04, python 3.5.
I fixed this bug replacing **tf.gfile.GFile(<something>)** with **open(<something>)**

**Comment by asimshankar** [comment]
@saxenasaurabh @rohan100jain @sherrym : Any updates?

**Comment by inflation** [comment]
@orlov-alexander-dd I think that's a workaround since you use python open file API instead of the c++ implementation.

**Comment by rohan100jain** [comment]
This should be fixed by now... As long as the file is opened in binary mode it should work.

**Comment by inflation** [comment]
@rohan100jain Will try, thanks!
