### ISSUE TITLE
404 - page not found

### ISSUE THREAD

**Issue by AS005209** [tensorflow/tensorflow#66708]
I couldn't find anywhere else to post, so I'll just put it here.
Good afternoon
I am a 2nd year student, studying to be a software engineer
I decided to study the topic of sound recognition, I would like to see and parse a ready project to work with tflite, which is offered by teachablemachine. Here is the link it gives, but unfortunately the empty example has been removed from the github thread, is there any way to get it or put it back in the thread.

https://github.com/tensorflow/examples/tree/master/lite/examples/sound_classification/android

I have also looked at more complex projects, but have not been able to fully understand them yet.

**Comment by sawantkumar** [comment]
Hi @AS005209 ,

Please check this [link](https://github.com/tensorflow/examples/tree/master/lite/examples/audio_classification/android) for the audio classification android example and let me know if this is the one you were looking for.
