### ISSUE TITLE
How to read Android Demo Detection Model Priors.pb file ?

### ISSUE THREAD

**Issue by AlexandreBriot** [tensorflow/tensorflow#6670]
Hello ! 

I would like to look into the assets file : multibox_location_priors.pb which contains boxpriors locations.
I want to use them in a iPythonNotebook to test the model with offline images but I don't know how to access properly to the values for all locations.
Is there any easy way to parse the file and get the locations values like it is possible to do with graph.pb file using these lines 

```
with tf.gfile.FastGFile("graph.pb", 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
```

Thanks in advance for your help
Alex

**Comment by andrewharp** [comment]
@AlexandreBriot The easiest thing to do would be to add tensorflow/examples/android/proto/box_coder.proto to CORE_PROTO_SRCS in tensorflow/core/BUILD (you may need to copy the file), and then you should be able to rebuild TF with support for reading it. It's not there already simply because it's a very model-specific proto only currently used for the demo.

**Comment by AlexandreBriot** [comment]
@andrewharp Hello Andrew and thank you for your precious help !
I followed your instructions and here is where I am.

- I modified  CORE_PROTO_SRCS in tensorflow/core/BUILD adding "framework/box_coder.proto",

- I copied box_coder.proto in the corresponding core/framework/ directory 

- I rebuild tensorflow from source but get some errors related to proto version 2 vs 3

- I modified box_coder.proto by doing these changes 

   * Change `syntax = "proto2";` to` syntax = "proto3";`
   * Change` package org_tensorflow_demo; `to `package tensorflow;`
   * Removing all optional and all default value 
           ex : `optional float mean = 1 [default = 0.0];` becomes `float mean = 1;`
   * Suppressing all `; `after message section 

   Is that correct ? Or is there some inexact/unappropriate changes ?
 

- Now I am able to import this freshly built tensorflow in my iPythonNotebook
  The new proto definition is supposed to decode my box-priors.pb file
  I want to do so using the lines as I can do for GraphDef but I don't know which Object I should create to replace GraphDef one and then loading data with ParseFromString method ...

```
with tf.gfile.FastGFile("box-priors.pb", 'rb') as f:
    priors = tf._?Object?_()
    priors.ParseFromString(f.read())
```

Could you give me your advice on that part ?
Thanks in advance for your help 
Alex

**Comment by andrewharp** [comment]
@AlexandreBriot We'll probably update the code soon to just load from a txt file, as separately supporting a  proto build in the Android example adds disproportionate overhead.

In the meantime, I've exported entire box prior proto to text, which you should be able to easily load into your Python code:

https://gist.github.com/andrewharp/136b07af1f221e9c95b383889f9911e0

**Comment by AlexandreBriot** [comment]
@andrewharp Thanks for your answer !

**Comment by azainab** [comment]
@andrewharp  I have a trained spam detection model trained using keras and have got the .pb I am trying it to implement it into a mobile app. Can you please guide me to the right documentation please. It will be of great help.
