### ISSUE TITLE
TextVectorization does not convert Cyrillic characters to lowercase

### ISSUE THREAD

**Issue by Ybisalt** [tensorflow/tensorflow#66731]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.8

### Custom code

Yes

### OS platform and distribution

Windows 10

### Python version

3.9

### Current behavior?

keras.layers.TextVectorization does not convert Cyrillic characters to lowercase with 'lower_and_strip_punctuation'.
Deprecated keras.preprocessing.text.Tokenizer does this.

### Standalone code to reproduce the issue

```shell
from tensorflow.keras.layers import TextVectorization

tokenizer = TextVectorization(split='character', standardize='lower_and_strip_punctuation')

tokenizer.adapt(["Zz, Aa"])   # Latin
vocab = tokenizer.get_vocabulary()
print(vocab)   # ['', '[UNK]', 'z', 'a', ' ']

tokenizer.adapt(["Яя, Аа"])   # Cyrillic
vocab = tokenizer.get_vocabulary()
print(vocab)   # ['', '[UNK]', 'я', 'а', 'Я', 'А', ' ']

from tensorflow.keras.preprocessing.text import Tokenizer  # deprecated
tokenizer = Tokenizer(char_level=True)
tokenizer.fit_on_texts(["Яя, Аа"])   # Cyrillic
print(tokenizer.index_word)   # {1: 'я', 2: 'а', 3: ',', 4: ' '}
```

### Relevant log output

```shell
['', '[UNK]', 'z', 'a', ' ']
['', '[UNK]', 'я', 'а', 'Я', 'А', ' ']
{1: 'я', 2: 'а', 3: ',', 4: ' '}
```

**Comment by Venkat6871** [comment]
Hi **@Ybisalt** ,
- Thank you for your issue, I replicated the issue in colab 2.16.1 and faced the same issue. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/14f248fedb26961b4b4dd367853bc4c9/66731_2-16-1.ipynb) for reference.
- Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999).

Thank you!
