### ISSUE TITLE
Creating an auxiliary CUDA Stream for an op

### ISSUE THREAD

**Issue by gibiansky** [tensorflow/tensorflow#6675]
I am writing an op which (sadly) requires using multiple CUDA streams to be efficient. Specifically, I need to have one auxiliary CUDA stream on whatever device the op is being executed; without this stream, the operations in this op will get entangled with operations in the rest of the graph, because the op _has_ to occasionally wait for its GPU kernels to complete before it can do things on CPU.

If I need to have an auxiliary CUDA stream besides the primary TensorFlow stream, one limited *just*  to the invocation of this op, how can I do so?

(To clarify, the CUDA stream should be long-lived across multiple invocations of the op, probably, just that it shouldn't the same stream as used by the rest of the graph)

**Comment by gibiansky** [comment]
Figured it out!

**Comment by JackHunt** [comment]
What was the solution? I am needing to use cuBLAS in a custom op but suspect I cannot use the default stream.
