### ISSUE TITLE
Tensorboard not showing data

### ISSUE THREAD

**Issue by haruza** [tensorflow/tensorflow#6677]
I have installed the newest version of tensorflow. I was trying to write my code to the tensorboard, but was not able.  
This is what i got as a response .
![image](https://cloud.githubusercontent.com/assets/14088328/21702101/ded3524a-d3a9-11e6-9334-30f960adaf8c.png)

I found out was the problem was. The tensorboard program was not able to find the log files, this was because of it was saved in a pathname that uses a non "english" letter, in this particular instance the letter "Å". So maybe you cant fix this bug

Best regards

**Comment by dandelionmane** [comment]
Can you please reopen this at https://github.com/tensorflow/tensorboard/issues with a reproduction? Perhaps a script we can run to generate unreadable data.
