### ISSUE TITLE
Installation from Source Error: "Server finished RPC without an explicit exit code"

### ISSUE THREAD

**Issue by sugartom** [tensorflow/tensorflow#6678]
### Environment info
Operating System: Ubuntu 14.04
GPU: NVIDIA Titan X

Installed version of CUDA and cuDNN: CUDA 8.0 and cuDNN 5.1.5
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`) f64c288ffd20819e264b80a4977b2ca8f33bfd98 (should be the latest one...)
2. The output of `bazel version` 0.4.3

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

When running "`bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package`
", it reported "`Server finished RPC without an explicit exit code`" after a few minutes' running. The last few lines looks as follows:

```
...
[2,244 / 3,310] Linking tensorflow/core/libarray_ops_op_lib.pic.lo
Server finished RPC without an explicit exit code
```

### What other attempted solutions have you tried?

I managed to install tensorflow via pip installation, and everything is running correctly (ex. Tensorflow demo).

Does anyone has any suggestions? Thanks in advance! :-)

**Comment by michaelisard** [comment]
Have you tried increasing the memory available?

**Comment by sugartom** [comment]
@michaelisard Hi Michael, thanks for your reply!
Yes, memory matters. I tried "`bazel build -c opt --config=cuda --local_resources 8096,.5,1.0 //tensorflow/tools/pip_package:build_pip_package`", and it managed to build. But it took 3 hours to build... Do you have any suggestion to speed up? 
My machine has 16G RAM and 12G GPU memory. Thanks!

**Comment by michaelisard** [comment]
I'm glad that solved the immediate problem! I would ask on [Stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) for advice on speeding up the build; I'm sorry I don't have a lot of personal experience.
