### ISSUE TITLE
Throw uninitialized local variable error to reduce confusion.

### ISSUE THREAD

**Issue by jkschin** [tensorflow/tensorflow#6679]
I reference this [post](http://stackoverflow.com/questions/41488276/cannot-get-a-simple-tfrecord-reader-to-work/41489484#41489484).

If one does not call `tf.local_variables_initializer()` when using `tf.train.string_input_producer` with `num_epochs` set as a local variable, it will throw an `OutOfRangeError` which might mislead people into thinking that the error lies with `tf.train.string_input_producer` instead of initializing the local variable.

Throwing an uninitialized local variable error would be very helpful in this case.

@mrry

**Comment by mrry** [comment]
I doubt we'll fix this bug. The current recommendation is to use `tf.data`, which does not rely on variables to be initialized, and hence doesn't suffer from this problem.
