### ISSUE TITLE
Tensorflow(GPU) build needs to be reconfigured, everytime I reboot my ubuntu

### ISSUE THREAD

**Issue by mervynhit1** [tensorflow/tensorflow#6680]
If a just configure tensorflow using ./configure and set CUDA support to YES, tensorflow is successfully built. I can make some change in source code and rebuild using command:

bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

Build after I reboot my ubuntu, and try to build tensorflow using above command, it requires me to reconfigure tensorflow, and rebuild, which takes such a long time. error message is as follows:

ERROR: /home/wolfson/.cache/bazel/_bazel_wolfson/41eaf6c788f09c81cffb135517d04fa2/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
	File "/home/wolfson/.cache/bazel/_bazel_wolfson/41eaf6c788f09c81cffb135517d04fa2/external/local_config_cuda/crosstool/BUILD", line 4
		error_gpu_disabled()
	File "/home/wolfson/.cache/bazel/_bazel_wolfson/41eaf6c788f09c81cffb135517d04fa2/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
		fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /home/wolfson/.cache/bazel/_bazel_wolfson/41eaf6c788f09c81cffb135517d04fa2/external/local_config_cuda/crosstool/BUILD.

**Comment by gunan** [comment]
@davidzchen @damienmg 
Do you think this is a similar issue to #4848

**Comment by mervynhit1** [comment]
I this this is related to #4705 

My fix is 
1, Add export TF_NEED_CUDA=1 to ~/.bashrc
2, Source ~/.bashrc
3, configure tensorflow
4, bazel build

**Comment by michaelisard** [comment]
@xmbrst could we add this step to the docs?

**Comment by wolffg** [comment]
This may be an issue with setup; reassigning to @martinwicke .

**Comment by martinwicke** [comment]
@damienmg I think the action_env should set the variable, not only make it available, right? So writing the bazel.rc should not let this happen.

Is this still an issue?

**Comment by damienmg** [comment]
@martinwicke yes `--action_env FOO` make `FOO` available to action but `--action_env FOO=BAR` makes set `FOO` to `BAR` in all action as well as for configuration rules (roughly equivalent to `LAST_FOO=$FOO; export FOO=BAR; bazel build --action_env FOO; export FOO=$LAST_FOO`)

**Comment by martinwicke** [comment]
Ok. I strongly believe that this issue is fixed. Please comment to reopen if this is an issue in 1.1 or at head.
