### ISSUE TITLE
libtensorflow-cpu-windows-x86_64-2.15.0

### ISSUE THREAD

**Issue by RSRcoder001** [tensorflow/tensorflow#66835]
ref Windows CPU link: https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.15.0.zip
The zip file for the C api seems to be missing files e.g. tf_buffer.h.

**Comment by Venkat6871** [comment]
Hi **@RSRcoder001** ,

- Thanks for reporting issue i also observed the same, We will check with developers and provide the resolution.

Thank you!
