### ISSUE TITLE
libhexagon_interface.so for non Android - eLinux platform

### ISSUE THREAD

**Issue by mmayers88** [tensorflow/tensorflow#66872]
**System information**
- OS Platform and Distribution :  Linux Ubuntu 20.04
- Mobile Device: Qualcomm QRB5165/RB5
- TensorFlow installed from Source
- TensorFlow version 2.16.1
- Bazel version (if compiling from source): 6.5.0
- GCC/Compiler version (if compiling from source): aarch64-linux-gnu 11.3.0

**Describe the problem**
Hello.
I'm trying to get hexagon delgate to work on Qualcomm's QRB5165/RB5 platform. This platform is based on Snapdragon 8xx series. But the problem is that this platform works on a Debian Linux. The currently available libhexagon_interface.so doesn't work as it has Android dependencies. I cannot find the source code of libhexagon_interface.so in tensorflow git. Is it possible to get a complied binary of libhexagon_interface.so for aarch64 Linux without Android dependencies?

 It seems like this has been done before [#43637](https://github.com/tensorflow/tensorflow/issues/43637) and I would appreciate a binary as well.

Thank you

**Comment by mmayers88** [comment]
Maybe I should edit the question. I am having a problem running the benchmark with the Hexagon DSP chip. I am using a Debian Linux, and not Android.  I can access and run other scripts on the Hexagon DSP, however I am having a lot of problems with Tensorflow. The Hexagon Delegate instructions seem to be out of date and are only for Android, even though it seems that I should be able to compile the necessary files. The Skeleton files: libraries “libhexagon_nn_skel.so”, “libhexagon_nn_skel_v65.so” and “libhexagon_nn_skel_v66.so” are all pre-compiled, so I am stuck with the latest version being  v1.20.0.1, and I can't even find that version of Tensorflow.

The error I am running into is:
```
WARNING: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
INFO: Hexagon Delegate is not supported.
```
How Can I get a libehexagon_interface, libhexagon_nn_skel, and libhexagon_delegate that all work together?

**Comment by sawantkumar** [comment]
Hi @mmayers88 ,

From what i know, i think the libhexagon_nn_skel.so and other ".so" files are provided by Qualcomm itself and is a part of snapdragon SDK instead of tensorflow team. Can you please check on Qualcomm forums and let me know if you are able to find them.

**Comment by mmayers88** [comment]
I've already checked on there. From what I understand the interface and delegate come from you. I have successfully generated a libhexagon_nn_skel.so, but I'm not sure about the other files and generating them. Is it possible to generate the libhexagon_interface.so as was done for other people?

**Comment by sawantkumar** [comment]
Sorry, i misunderstood the question first time, can you please check this [link](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/hexagon/hexagon_nn) and let me know if this is the one you are looking for .

**Comment by mmayers88** [comment]
I've tried that. Would I just build the interface with bazel as:
```bazel build --config=elinux_aarch64 -c opt //tensorflow/lite/delegates/hexagon/hexagon_nn:libhexagon_interface.so```

Would the same be true for building the delegate?:
```bazel build --config=elinux_aarch64 -c opt //tensorflow/lite/delegates/hexagon:hexagon_delegate```

**Comment by pkgoogle** [comment]
Hi @mmayers88, I think you're almost right... I can only find a config option for `linux_aarch64` https://github.com/tensorflow/tensorflow/blob/master/tensorflow/BUILD#L555

Can you try these and let me know if you run into any issue?
```
bazel build --config=linux_aarch64 -c opt //tensorflow/lite/delegates/hexagon/hexagon_nn:libhexagon_interface.so
bazel build --config=linux_aarch64 -c opt //tensorflow/lite/delegates/hexagon:hexagon_delegate
```

**Comment by mmayers88** [comment]
I will try that and report back.

**Comment by mmayers88** [comment]
Reporting back, I get this error:
```ERROR: Config value 'linux_aarch64' is not defined in any .rc file```

**Comment by pkgoogle** [comment]
Hi @mmayers88, apologies, you were actually right it has an e before it:

```sh
bazel build --config=elinux_aarch64 -c opt //tensorflow/lite/delegates/hexagon/hexagon_nn:libhexagon_interface.so
bazel build --config=elinux_aarch64 -c opt //tensorflow/lite/delegates/hexagon:hexagon_delegate
```

For future reference you can find the options under your .bazelrc file in the tensorflow root. I would also run the ./configure script prior to building and answer as appropriately as you can.
