### ISSUE TITLE
Feature Request: provide env vars to control resource usage (allow_growth, threads etc)

### ISSUE THREAD

**Issue by geromueller** [tensorflow/tensorflow#6691]
We provide GPGPU access on a cluster and to let the scheduler (HTCondor) assign the resources. Tt would be great to be able to set
- the number of theads to use
- the allow_growth options
- and the per_process_gpu_memory_fraction option
via environment variables e.g. TF_NUM_THREADS=4, TF_ALLOW_GROW=1 etc.

**Comment by aselle** [comment]
@mrry do you have any opinions on this.

**Comment by vrv** [comment]
I think you can write a function that reads your own environment variables to populate and return a tf.ConfigProto() that sets these options -- I don't think it belongs in the TF core.  The explicit proto makes reproduction much easier.

**Comment by mrry** [comment]
I agree with @vrv. (I should get that printed on a t-shirt.)

**Comment by aselle** [comment]
So essentially, someone who admins a cluster or uses this software has to be sure to force that code to run rather than letting users run arbitrary code that doesn't call their code. Presumably such a hook could be done somewhere else, even as extreme as LD_PRELOAD.

**Comment by geromueller** [comment]
@vrv sure I can, but the point is that the students and others do not have to do this. And to prevent the misuse of the cluster.
Please reopen this issue!!

**Comment by yaroslavvb** [comment]
BTW, you can modify global setup by changing session.py

IE, inspect.getsourcefile(tf.Session) to find where it's defined, and then modify the part to something like below

```
   if config is not None:
      if not isinstance(config, config_pb2.ConfigProto):
        raise TypeError('config must be a tf.ConfigProto, but got %s'
                        % type(config))
      self._config = config
      self._add_shapes = config.graph_options.infer_shapes
    else:
      self._config = config_pb2.ConfigProto(intra_op_parallelism_threads=24)
      self._add_shapes = False
```

Now all sessions default to using 24 threads
