### ISSUE TITLE
Misnamed libcuda.dylib. (CUDA 8.0, macOS 10.12)

### ISSUE THREAD

**Issue by djwbrown** [tensorflow/tensorflow#6693]
### Misnamed `libcuda.dylib` in prebuilt binary. (CUDA 8.0, macOS 10.12).
Tensorflow fails to load `libcuda.1.dylib`, a file which does not exist for CUDA 8.0 on macOS. The filename is `libcuda.dylib`.

Resolved by `sudo ln -s /usr/local/cuda/lib/libcuda.dylib /usr/local/cuda/lib/libcuda.1.dylib`.

Preferable solution is a change to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/dso_loader.cc#L82.

I would change `FormatLibraryFileName("cuda", "1")` to `FormatLibraryFileName("cuda")`, but I'm not sure on which OS and CUDA versions this is the correct naming scheme. Possibly a check is needed, `if ( stoi(GetCudaVersion()) >= 8 ) {...}` and maybe `if (__APPLE__) {...}`. 

### Related issue
https://github.com/tensorflow/tensorflow/issues/2278
Solution provided [here](https://github.com/tensorflow/tensorflow/issues/2278#issuecomment-244828047) by @eagleflo, @martinianodl.
### Environment info
macOS 10.12.2
CUDA Toolkit 8.0
```
ls -l /usr/local/cuda/lib/libcud*
lrwxr-xr-x  1 root  wheel     33 Jan  6 14:34 /usr/local/cuda/lib/libcuda.1.dylib -> /usr/local/cuda/lib/libcuda.dylib
-rwxr-xr-x@ 1 root  wheel  13504 Nov  3 20:39 /usr/local/cuda/lib/libcuda.dylib
lrwxr-xr-x@ 1 root  wheel     45 Nov  3 20:40 /usr/local/cuda/lib/libcudadevrt.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudadevrt.a
lrwxr-xr-x@ 1 root  wheel     50 Nov  3 20:40 /usr/local/cuda/lib/libcudart.8.0.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib
lrwxr-xr-x@ 1 root  wheel     46 Nov  3 20:40 /usr/local/cuda/lib/libcudart.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.dylib
lrwxr-xr-x@ 1 root  wheel     49 Nov  3 20:40 /usr/local/cuda/lib/libcudart_static.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart_static.a
lrwxr-xr-x  1 root  wheel     47 Jan  6 13:19 /usr/local/cuda/lib/libcudnn.5.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudnn.5.dylib
lrwxr-xr-x  1 root  wheel     45 Jan  6 13:19 /usr/local/cuda/lib/libcudnn.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudnn.dylib
lrwxr-xr-x  1 root  wheel     48 Jan  6 13:19 /usr/local/cuda/lib/libcudnn_static.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudnn_static.a

```
Installed as a virtualenv with the prebuilt binary.

TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow_gpu-0.12.1-py3-none-any.whl
```
>>> tf.__version__
'0.12.1'
```

**Comment by djwbrown** [comment]
I guess it's a known issue. A bit late, I found this already covered in the documentation: https://www.tensorflow.org/get_started/os_setup#mac_os_x_segmentation_fault_when_import_tensorflow

> This is due to the fact that by default, cuda creates libcuda.dylib, but tensorflow tries to load libcuda.1.dylib. This can be resolved by create a symbolic link:
> `ln -sf /usr/local/cuda/lib/libcuda.dylib /usr/local/cuda/lib/libcuda.1.dylib`

I would submit a PR for a permanent fix, but maybe it breaks something on other systems. For now the fix is in the documentation.

**Comment by aselle** [comment]
@gunan, can we accept this patch, or is there some reason it can't work reliably in every case?

**Comment by gunan** [comment]
@caisq what do you think?

**Comment by gunan** [comment]
The fix is now merged. 1.0.0-rc1 will have the fix. Closing the issue.
