### ISSUE TITLE
Cherry Pick bundle_shim to 0.12.x branch

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#6695]
bundle_shim.py was added to ["allows a system to load both legacy session bundle and SavedModel bundle."](https://github.com/tensorflow/tensorflow/commit/de1f21e98a6dd14a5e4c1d2d9c14b430f57493b3#diff-340f927179763894226603c8e38e0ec4) however this is only on master. This leads to issues saving and then loading back models, for example see: https://github.com/tensorflow/tensorflow/issues/6336.

I suggest cherry picking it to current release branch.

**Comment by jhseu** [comment]
We don't plan to cherry-pick this into 0.12, particularly because it's in contrib.

It'll be in the next major release, though.
