### ISSUE TITLE
Unable to install old version of tensorflow

### ISSUE THREAD

**Issue by Nicholas-B1** [tensorflow/tensorflow#66950]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.4.0

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Mobile device

Nvidia Jetson Nano

### Python version

3.8.10

### CUDA/cuDNN version

10.2.300

### Current behavior?

I am unable to install TensorFlow version 2.4 or lower because current version is not working with Cuda and I cannot run any code on my GPU. How can I get the older version so it can work with my Cuda and GPU.

### Standalone code to reproduce the issue

```shell
Could not find version that satisfies the requirement.
```

**Comment by Kmaralla** [comment]
Couple of follow-up questions on this!!

Are you using a virtual environment or conda environment? If so, have you tried installing TensorFlow 2.4 in a new environment?

Also, did you check CUDA version, GPU model and driver version compatible with TensorFlow 2.4?

**Comment by tilakrayal** [comment]
@tilakrayal,
Could you please let us know specific use case that you are using tensor flow v2.5 which is pretty old and not actively supported. We always suggest using the latest tensorflow v2.15.

The tensoflow v2.4 is compatible with python - 3.6-3.8, GCC- 7.3.1, Bazel 3.1.0, cuDNN - 8.0, CUDA-11.0. Could you please try to un-install the tensorflow related softwares and try to re-install by following the official document and the tested build configurations. 
https://www.tensorflow.org/install/source#gpu

Thank you!

**Comment by Nicholas-B1** [comment]
I need Tensorflow to work on my Jetson Nano dev board that is on CUDA 10 but right now TensorFlow does not recognize my GPU as existing, so I am trying to downgrade.



________________________________

**Comment by tilakrayal** [comment]
@Nicholas-B1,
As mentioned the tensoflow v2.4 is compatible with python - 3.6-3.8, GCC- 7.3.1, Bazel 3.1.0, cuDNN - 8.0, CUDA-11.0. The GPU might not detect and face different warnings if the compatible versions are unmatched with the respective TensorFlow version. Thank you!
