### ISSUE TITLE
How to create XLA compiled model from a TF Saved Model

### ISSUE THREAD

**Issue by ndeep27** [tensorflow/tensorflow#66967]
### Issue type

Others

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

TF 2.11

### Custom code

No

### Current behavior?

NONE

### Standalone code to reproduce the issue

```shell
I have a TF Saved Model which I want to convert to a CUDA Graph. I see that there is initial implmentation of CUDA Graphs in XLA here - https://github.com/tensorflow/tensorflow/commit/563c2ab50c43d16149ccfa143c8f97ebdb800a7e

How can I use XLA to convert a TF Saved Model to a CUDA Graph?
```

**Comment by ndeep27** [comment]
@sushreebarsa Can you help with above query? I want to see how I can use XLA with TF to enable CUDA Graphs

**Comment by sushreebarsa** [comment]
@ndeep27 There isn't a direct way to create an XLA compiled model from a TensorFlow SavedModel in TensorFlow 2.  Please refer to this [official](https://www.tensorflow.org/api_docs/python/tf/xla) documentation. Could you try to consider converting your SavedModel to a TFLite model. TFLite utilizes its own interpreter and optimizations, potentially achieving similar performance benefits on mobile and embedded devices.
Thank you!
