### ISSUE TITLE
can't find zlib 1.2.8

### ISSUE THREAD

**Issue by John-xiao** [tensorflow/tensorflow#6709]
native.new_http_archive(
    name = "zlib_archive",
    url = "http://zlib.net/zlib-1.2.8.tar.gz",
    sha256 = "36658cb768a54c1d4dec43c3116c27ed893e88b02ecfcb44f2166f9c0b7f2a0d",
    strip_prefix = "zlib-1.2.8",
    build_file = str(Label("//:zlib.BUILD")),
)

1.2.10 is released

**Comment by yaroslavvb** [comment]
Fixed in https://github.com/tensorflow/tensorflow/commit/1e317b1f7dc5ccf04fc51ac96d97f5bdaefa9af9
