### ISSUE TITLE
Android demo accuracy

### ISSUE THREAD

**Issue by milinddeore** [tensorflow/tensorflow#6711]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
I searched #1269 #504 

### Environment info
Mac OS for build and Android version 5 to run .apk demo.   

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

I followed the steps mentioned in #1269 and could able to run the example successfully, but the accuracy of the result is very low and often wrong. I have trained my systems on 25 different daily used products like soap, soup, noodles, etc. 
Where as when i run the same example using following script it give me very high accuracy (approx. 90-95%)

```
import sys
import tensorflow as tf
// change this as you see fit
image_path = sys.argv[1]

// Read in the image_data
image_data = tf.gfile.FastGFile(image_path, 'rb').read()

// Loads label file, strips off carriage return
label_lines = [line.rstrip() for line 
                   in tf.gfile.GFile("/tf_files/retrained_labels.txt")]

// Unpersists graph from file
with tf.gfile.FastGFile("/tf_files/retrained_graph.pb", 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    _ = tf.import_graph_def(graph_def, name='')

with tf.Session() as sess:
    // Feed the image_data as input to the graph and get first prediction
    softmax_tensor = sess.graph.get_tensor_by_name('final_result:0')
    
    predictions = sess.run(softmax_tensor, \
             {'DecodeJpeg/contents:0': image_data})
    
    // Sort to show labels of first prediction in order of confidence
    top_k = predictions[0].argsort()[-len(predictions[0]):][::-1]
    
    for node_id in top_k:
        human_string = label_lines[node_id]
        score = predictions[0][node_id]
        print('%s (score = %.5f)' % (human_string, score))
```

The only difference i see here is that the model file used in the android demo is stripped because it does not support DecodeJpeg, whereas in the above code its the actually generated unstripped model. Is there any specific reason or somewhere i am wrong here? 

### What other attempted solutions have you tried?
Yes, i the above script and it gives me quite high accuracy result.

**Comment by michaelisard** [comment]
This type of usage question is better asked on [Stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow).

**Comment by andrewharp** [comment]
@milinddeore It's worth checking that you're not running into https://github.com/tensorflow/tensorflow/issues/4911, which can affect some Android 5.0 devices. You can use the volume keys to turn on debug mode and view the image that's actually being sent to the classifier.
