### ISSUE TITLE
Queues don't support enqueuing SparseTensor?

### ISSUE THREAD

**Issue by standy66** [tensorflow/tensorflow#6713]
It seems that right now RandomShuffleQueue doesn't support SparseTensor. When I run this minimal example
```
import tensorflow as tf
values = tf.constant([0, 1, 2], dtype=tf.int32)
indices = tf.constant([[0, 0], [0, 1], [0, 2]], dtype=tf.int64)
shape = tf.constant([1, 3], dtype=tf.int64)

sparse = tf.SparseTensor(values=values, indices=indices, shape=shape)
queue = tf.RandomShuffleQueue(2, 1, [tf.int32])
queue.enqueue([sparse])
```
I get the following error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-12-a8e6053e53cf> in <module>()
----> 1 queue.enqueue([sparse])

/Users/astepanov/.virtualenvs/py_asr/lib/python3.5/site-packages/tensorflow/python/ops/data_flow_ops.py in enqueue(self, vals, name)
    320     with ops.name_scope(name, "%s_enqueue" % self._name,
    321                         self._scope_vals(vals)) as scope:
--> 322       vals = self._check_enqueue_dtypes(vals)
    323 
    324       # NOTE(mrry): Not using a shape function because we need access to

/Users/astepanov/.virtualenvs/py_asr/lib/python3.5/site-packages/tensorflow/python/ops/data_flow_ops.py in _check_enqueue_dtypes(self, vals)
    275     for i, (val, dtype) in enumerate(zip(vals, self._dtypes)):
    276       tensors.append(ops.convert_to_tensor(val, dtype=dtype,
--> 277                                            name="component_%d" % i))
    278 
    279     return tensors

/Users/astepanov/.virtualenvs/py_asr/lib/python3.5/site-packages/tensorflow/python/framework/ops.py in convert_to_tensor(value, dtype, name, as_ref, preferred_dtype)
    667 
    668         if ret is None:
--> 669           ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    670 
    671         if ret is NotImplemented:

/Users/astepanov/.virtualenvs/py_asr/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    174                                          as_ref=False):
    175   _ = as_ref
--> 176   return constant(v, dtype=dtype, name=name)
    177 
    178 

/Users/astepanov/.virtualenvs/py_asr/lib/python3.5/site-packages/tensorflow/python/framework/constant_op.py in constant(value, dtype, shape, name, verify_shape)
    163   tensor_value = attr_value_pb2.AttrValue()
    164   tensor_value.tensor.CopyFrom(
--> 165       tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    166   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    167   const_tensor = g.create_op(

/Users/astepanov/.virtualenvs/py_asr/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape)
    365       nparray = np.empty(shape, dtype=np_dt)
    366     else:
--> 367       _AssertCompatible(values, dtype)
    368       nparray = np.array(values, dtype=np_dt)
    369       # check to them.

/Users/astepanov/.virtualenvs/py_asr/lib/python3.5/site-packages/tensorflow/python/framework/tensor_util.py in _AssertCompatible(values, dtype)
    300     else:
    301       raise TypeError("Expected %s, got %s of type '%s' instead." %
--> 302                       (dtype.name, repr(mismatch), type(mismatch).__name__))
    303 
    304 

TypeError: Expected int32, got <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x105fedef0> of type 'SparseTensor' instead.
```

**Comment by standy66** [comment]
The main reason I needed this is because shuffle_batch doesn't support dynamic_pad for now ([#5147](https://github.com/tensorflow/tensorflow/issues/5147)). So I used the following [piece of code](https://github.com/tensorflow/tensorflow/issues/5147#issuecomment-271086206). But RandomShuffleQueue doesn't support enqueuing SparseTensors directly. I worked this around by enqueuing _values_, _indices_ and _shape_ instead of the whole SparseTensor and reconstructing SparseTensor after dequeue op.

**Comment by ebrevdo** [comment]
tf.train.shuffle_batch supports SparseTensor, you can use that. It goes the work for you.

**Comment by randomrandom** [comment]
@ebrevdo what about if we want to create queue with different buckets? I'm following the example here: [http://programtalk.com/vs2/python/13142/deep_recommend_system/java_predict_client/src/main/proto/tensorflow/contrib/training/python/training/bucket_ops_test.py/](url)

It all looks good, except that my data is a sparse array, e.g.
sources = [[1], [2, 0, 3], [3,2]]
targets = [[2. 3 4], [1,2], [2,3,4,5]]

First I tried using `convert_to_tensor` but I assume this would not work well with sparse arrays so I started exploring using the SparseTensor, however looks like transforming the data into a SparseTensor won't help much since it cannot be fead to the RandomShuffleQueue. Would the `tf.train.shuffle_batch` be a good substitute? What's the best approach to add `slice_input_producer` in that case? I noticed that it doesn't work with SparseTensor
`        # load train corpus
         sources, targets, lengths, validation_sources, validation_targets, validation_lengths = self._load_corpus()
 
         print("Finished corpus loading")
 
         # to a constant tensor
         source = tf.convert_to_tensor(sources)
         target = tf.convert_to_tensor(targets)
         length = tf.convert_to_tensor(lengths)
 
         input_queue = tf.RandomShuffleQueue(batch_size*64, # capacity
                                             batch_size*32, # min_after_dequeue
                                             tf.int32, name=name)
         input_queue = input_queue.enqueue((length, source, targets))
 
         lengths_t, sources_t, targets_t = input_queue.dequeue()
 
 
         source_batch, target_batch = self.shuffle_bucket_batch(
              length_t, [sources_t, targets_t],
              batch_size=batch_size,
              bucket_boundaries=self.BUCKET_BOUNDARIES,
              # this will bad the source_batch and target_batch independently
              dynamic_pad=True,
              capacity=batch_size*64,
              num_threads=32,
              allow_smaller_final_batch=False, name=name
          )
`

**Comment by bnoreus** [comment]
I have a tf.train.shuffle_batch from which I retrieve batches (sparse tensors) and would like to enqueue them into a FIFO queue. However, this issue still doesn't seem to have been fixed. I get the same error.
