### ISSUE TITLE
TFSlim: evaluate multiple validation batches using `evaluation_loop`

### ISSUE THREAD

**Issue by kencoken** [tensorflow/tensorflow#6714]
I'm trying to use placeholders for training with TF-Slim, as my training + evaluation data comes from outside of TF World. I've now got training working by using the workaround described in #6604 and keeping track of the last training batch to supply in the feed dict when calling `sess.run(summary_op)`.

However, evaluation using `evaluation_loop` over multiple batches seems to not be possible. There are `summary_op_feed_dict` and `eval_op_feed_dict` arguments to the `evaluation_loop` function, but if I understand correctly, if I set `num_evals` > 1, then the same feed dict (+ data) will be used for every evaluation.

I'm happy add this functionality and issue a PR – is it true that right now the ability to evaluate over multiple validation batches using placeholders is not implemented? I'm using TF 12.1.

**Comment by sguada** [comment]
I would recommend you to use [evaluate_once](https://github.com/tensorflow/tensorflow/blob/78b12941db2e1b9baee785dce1edf1e557377acc/tensorflow/contrib/training/python/training/evaluation.py#L337). 
Take a look at [evaluate_repeatedly](https://github.com/tensorflow/tensorflow/blob/78b12941db2e1b9baee785dce1edf1e557377acc/tensorflow/contrib/training/python/training/evaluation.py#L434) to see how to use evaluate_once

**Comment by kencoken** [comment]
Thanks for the help @sguada! However, I'm still not sure whether that solves the underlying issue of the `feed_dict` being a constant parameter to `evaluate_once` as far as I can see. In the function, there are the following lines:

```
while not session.should_stop():
        session.run(eval_ops, feed_dict)
```

And so until the `should_stop` flag is set, the same `feed_dict` will be used for every evaluation?

In the docstring of `evaluate_repeatedly` there is a comment that reads:

> _`evaluate_once` creates a local variable used to track the number of evaluations run via `tf.contrib.training.get_or_create_eval_step`_

Perhaps this could be used in some way? Again, happy to contribute if it turns out there is something is missing, though perhaps I'm misunderstanding?

Thanks so much for your time!

**Comment by ispirmustafa** [comment]
If you want to change feed_dict in every run, you can use a hook. Example is as follows:
```
class MyFeedHook(session_run_hook.SessionRunHook):
  def before_run(self, run_context): 
    return session_run_hook.SessionRunArgs(
        fetches=None, feed_dict=my-feed-dict-for-this-step)
```

**Comment by MarkDaoust** [comment]
@kencoken, given the inactivity here It sounds like that solved your problem.
