### ISSUE TITLE
Typos in docs for expand_dims

### ISSUE THREAD

**Issue by holdenlee** [tensorflow/tensorflow#6718]
`dim` has been replaced by `axis` in the documentation.

(https://www.tensorflow.org/api_docs/python/array_ops/shapes_and_shaping#expand_dims)

**Comment by yaroslavvb** [comment]
Perhaps you have an older version of TensorFlow, it's been renamed to axis in 0.12
```
>>> import tensorflow as tf
>>> tf.__version__
'0.12.1'
>>> tf.expand_dims([1], axis=1)
<tf.Tensor 'ExpandDims:0' shape=(1, 1) dtype=int32>

```

**Comment by holdenlee** [comment]
The typo is:
```
shape(expand_axiss(t, 0)) ==> [1, 2]
```
It appears several times.

**Comment by yaroslavvb** [comment]
I see. It seems to have been fixed in master:
https://www.tensorflow.org/versions/master/api_docs/python/array_ops/shapes_and_shaping#expand_dims
