### ISSUE TITLE
Running different parts of a graph at a time without recomputation

### ISSUE THREAD

**Issue by Jabberwockyll** [tensorflow/tensorflow#672]
Motivated by [this StackOverflow question](http://stackoverflow.com/questions/34536340/how-to-use-tensorflow-optimizer-without-recomputing-activations-in-reinforcement)

According to George Dahl's answer, there is currently no way to run part of a graph, then later run the entire graph without recomputing that part of the graph.  Couldn't you always just run the whole thing in the first place, you ask?  Consider this scenario:

### Context/Example
You're using tensorflow to implement a reinforcement learning agent with value function approximation trained using stochastic gradient descent.  You're agent contains a method that is called once every iteration/timestep in the experiment.  The method takes an obervation and reward as input and outputs an action.  Consider this sequence of events (Say you're doing q-learning):

1.  At the end of an iteration, you compute your state-action values to choose an action and then return control to the calling program to simulate a step in the environment.
2.  At the beginning of the next iteration, it's time to update the parameters.  You want to use tensorflow's optimizer class to automatically calculate the gradients.  Here, you have three options:

*  Just recompute the state-action values, so you can use the optimizer.  This option leaves you inefficiently calculating part of the graph twice.  This also might not even be viable if you were using something like recurrent neural networks, where calculating the activations changes the state of the nodes.
*  Hardcode the gradients.  You could just write a function to calculate the gradients yourself and not even use optimizer.  However, if you were experimenting with different network architectures and activation functions in a big convolutional network, this could get pretty cumbersome.
*  Call everything else from within your agent.  This sacrifices a lot of modularity and neatness in any framework bigger than a small experiment.

So, in this case, the problem is that your graph (learning with SGD) depends on a value (observation/reward), calculated externally, that depends on the result of part of the graph (state-action values).  And we can't save the state-action values as variables to feed later as placeholders, because then they wouldn't be associated with the operations that produced them, which are required for automatic differentiation.

### Solution
I'm not yet very familiar with the inner workings of tensorflow, so I'm not sure what the best solution would be.  It would need to be able to give Optimizer the tensors already calculated and the graph with the operations that produced them.  Maybe some kind of Session.partial_run() that saves the computed tensors associated with their nodes until a normal run is done?  Maybe a new method under Optimizer that returns an operation to calculate gradients, depending on a placeholder?  What do you think?

**Comment by jramapuram** [comment]
+1 for this.

**Comment by 0wnrepo** [comment]
+1 for this.

**Comment by georgedahl** [comment]
Try out partial_run. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/session.py#L317

The feature is still experimental and might yet change.

**Comment by girving** [comment]
@georgedahl: Who's working on partial_run so that I can assign this to them?  Do you know if it's time to close?

**Comment by markusdr** [comment]
`partial_run` is a very useful feature! 

Just to make sure I understand correctly: 

In the following toy code, when I first derive `tmp` using `partial_run` and then compute the `cost` and `gradient`, is `tmp` only computed once and then reused multiple times?

    import tensorflow as tf
    
    w = tf.Variable(1.0)
    init = tf.initialize_all_variables()
    
    x = tf.placeholder("float")
    slow = tf.exp(w * x * tf.constant(2.0))
    cost = x * slow + x * slow
    grad = tf.gradients(cost, w)[0]
    feed = {x: 3.0}
    
    # Efficient
    with tf.Session() as sess:
        sess.run(init)
        h = sess.partial_run_setup([slow, cost, grad], [x])
        # First derive slow
        sess.partial_run(h, slow, feed_dict=feed)
        # Then re-use slow multiple times (w/o recomputing it)
        print(sess.partial_run(h, cost))
        print(sess.partial_run(h, grad))
    
    # Naive / Inefficient 
    with tf.Session() as sess:
        sess.run(init)
        # Cost and grad each recompute 'slow' twice
        print(sess.run(cost, feed_dict=feed))
        print(sess.run(grad, feed_dict=feed))
    
And, is there a way to see/check the computation steps it's doing?

**Comment by bentzinir** [comment]
Hi,
Doe's partial_run work for RNN?
Thanks,
Nir

**Comment by georgedahl** [comment]
It should work for any TensorFlow graph, as far as I know. If it doesn't file a bug.

**Comment by ljstrnadiii** [comment]
@markusdr,

This is exactly what I need to know about partial run! Have you found an answer to your questions? 

Len

**Comment by jaideep777** [comment]
@markusdr 

In the simple case you described, wont the following code do exactly that?
"""
cost_val, grad_val = sess.run([cost,grad], feed_dict=feed)
"""

**Comment by Amitayus** [comment]
There is some interesting logic in following codes.
`import tensorflow as tf
# from tensorflow.python import debug as tf_debug

one = tf.constant(1, name="constant_1")
state = tf.Variable(0, name="variable_1")

new_state = tf.add(state, one)
update_op = tf.assign(state, new_state)


sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(tf.local_variables_initializer())

# sess = tf_debug.LocalCLIDebugWrapperSession(sess)
print(sess.run(update_op))
print(sess.run(update_op))

for _ in range(10):
    # way 1
    # print(sess.run(update_op))
    # result = sess.run([state, new_state])
    # way 2
    # result = sess.run([update_op, state, new_state])
    # way 3
    result = sess.run([state, new_state, update_op])
    print(result)
`
the way2 and way3 is same. But the way1 is different from both way2 and way3.

**Comment by ppwwyyxx** [comment]
@Amitayus because 1 is not equivalent to 2 and 3. #13133.

**Comment by aribenjamin** [comment]
The documentation for `partial_run` is a little ambiguous. If you're wondering, like I and @markusdr were, "does `partial_run` keep computed values stored?", the example in the docs doesn't clear much up. The example there (modified to work standalone) is:
```
import tensorflow as tf
a = tf.placeholder(tf.float32, shape=[])
b = tf.placeholder(tf.float32, shape=[])
c = tf.placeholder(tf.float32, shape=[])
r1 = tf.add(a, b)
r2 = tf.multiply(r1, c)

with tf.Session() as sess:
    h = sess.partial_run_setup([r1, r2], [a, b, c])
    res = sess.partial_run(h, r1, feed_dict={a: 1, b: 2})
    res = sess.partial_run(h, r2, feed_dict={c: res})
    
    print(res)
```
This returns `9.0`. But do we always need to need the result of a previous `partial_run` as input? Changing the input of the last line shows that this is not the case. Internal values are stored.
```
import tensorflow as tf
a = tf.placeholder(tf.float32, shape=[])
b = tf.placeholder(tf.float32, shape=[])
c = tf.placeholder(tf.float32, shape=[])
r1 = tf.add(a, b)
r2 = tf.multiply(r1, c)

with tf.Session() as sess:
    h = sess.partial_run_setup([r1, r2], [a, b, c])
    res = sess.partial_run(h, r1, feed_dict={a: 1, b: 2})
    res = sess.partial_run(h, r2, feed_dict={c: 2})
    
    print(res)
```
Returns `6.0`.

**Comment by TIXFeniks** [comment]
Found some weird behavior of `partial_run`. If we add `optimizer.apply_gradients` to fetches, it updates the variables without any partial_run calls. So does it really compute anything at `partial_run` call, or does it compute everything at `partial_run_setup` call?

**Comment by basejn** [comment]
But why this throws exception ? 

```
import tensorflow as tf
a = tf.placeholder(tf.float32, shape=[])
b = tf.placeholder(tf.float32, shape=[])
c = tf.placeholder(tf.float32, shape=[])
r1 = tf.add(a, b)
r2 = tf.multiply(r1, c)

with tf.Session() as sess:
    h = sess.partial_run_setup([r1, r2], [a, b, c])
    res = sess.partial_run(h, r1, feed_dict={a: 1, b: 2})
    res = sess.partial_run(h, r2, feed_dict={c: 2})
    res = sess.partial_run(h, r2, feed_dict={c: 3})
    
    print(res)
```
Which prints the following exception. :
`InvalidArgumentError: Must run 'setup' before performing partial runs!`

**Comment by kafendt** [comment]
I was also expecting ```partial_run``` to work as @basejn used it. Is that in any way possible? I would like to store the tensor of an intermediate graph node and then only run the rest of the graph with that stored tensor so I don't have to rerun the first part of the graph over and over again even though nothing changes.

**Comment by slerman12** [comment]
I'm finding `partial_run` to be a really useful feature, but for my most recent purposes, I've found it to be rather limited. It would be nice if a partially computed graph could be reused more than once. Even better, it'd be great if independent placeholders within it could be modified. This isn't as complicated as it sounds, I don't think. The former just requires a heavier memory consumption by allowing the computation graph to persist, and the latter in its most naive implementation would recompute the graph from scratch and in a more mature implementation would only do so for relevant dependencies. Why add these features? They would allow for significantly increased potential for modularity and dynamism.
