### ISSUE TITLE
Why don't you provide a standard go-lang get install?

### ISSUE THREAD

**Issue by zwikst** [tensorflow/tensorflow#67221]
Of course I know that a manual scripted installation is provided at the following link:

[build from source](https://github.com/tensorflow/build/tree/master/golang_install_guide#build-from-source)

However, I would like to say that Tensorflow is a Google product and so is Golang, but my desire to use Golang for Tensorflow would require me to manually patch a few dozens of patches.

I'd also like to say that the patch doesn't always work, as in the following error:
```bash
$ (cd tensorflow/go/op && go generate)
tensorflow/core/framework/optimized_function_graph.proto: This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set.
../genop/generate.go:19: running "bash": exit status 1
generate.go:17: running "go": exit status 1
```

Apparently the .proto source files you provide are not compatible with the go generate command in scripts.

It's really puzzling, I've seen very small studios or small workshops that might offer their products to collaborators this way. But this is Google, this is Tensorflow, this is Golang. And  the product is for the public.

No intention to disparage third party developers, in fact I'd rather appreciate them. But recommending a community product with 30+ stars on your product's official page is still baffling.

The intention is not to fix these patch scripts, but I still provide my working environment to easily reproduce the problem:
```
$ git show HEAD
commit 5bc9d26649cca274750ad3625bd93422617eed4b (HEAD, tag: v2.16.1)
Merge: 086d2cc8037 15315148e6c
Author: learning-to-play <66660475+learning-to-play@users.noreply.github.com>
Date:   Tue Mar 5 16:30:15 2024 -0800

    Merge pull request #63073 from Intel-tensorflow/kanvi/update-release-notes

    [oneDNN] Update release notes
$ go version
go version go1.21.5 linux/amd64
$ protoc --version
libprotoc 3.12.4
```

**Comment by sushreebarsa** [comment]
@zwikst Starting with Go version 1.17, the functionality of go get for installing executables has been deprecated. This means using go get to directly install and compile packages is no longer recommended.
Thank you!
