### ISSUE TITLE
Feature request: 1D deconvolution

### ISSUE THREAD

**Issue by johny7** [tensorflow/tensorflow#6724]
Pretty much topic tells the whole story.

For auto-encoder based on 1D convolutions, opposite operation is required to complete decoding part.
This is planned to be used for sound processing.

**Comment by yaroslavvb** [comment]
There's a kind of deconvolution described in [Deconvolutional Networks](http://www.matthewzeiler.com/pubs/cvpr2010/cvpr2010.pdf) which is implemented as `nn.conv2d_transpose`

**Comment by drasros** [comment]
interested in this too!

**Comment by Labalex21** [comment]
Me, too! Don't know if there is a way to do a 1d deconvolution with `nn.conv2d_transpose.`

**Comment by yaroslavvb** [comment]
This is a very vague feature request. There's already a kind of deconvolution implemented in TensorFlow. Also 1D vector can be turned into as 1xn 2D image using reshape so that 2D functions can be applied.

**Comment by yaroslavvb** [comment]
BTW, there's 1D FFT+inverse FFT [implemented](https://www.tensorflow.org/versions/master/api_docs/python/math_ops/fourier_transform_functions) in TensorFlow, the other kind of deconvolution can be done by combination of FFT and pointwise divide, would that work for you?

**Comment by Labalex21** [comment]
I will try it out and response here, thanks!

**Comment by Labalex21** [comment]
It worked easily reshaping the data and using the 2D functions, thank you!

**Comment by yaroslavvb** [comment]
OK, since it works for @Labalex21 I'll close this for now. If this doesn't cover, please open new bug request with detailed specifications of what is needed, possibly with links to existing implementation and/or examples of how it'll be used in TensorFlow

**Comment by ryanpeach** [comment]
I recommend, especially if it is easy, that we make a function to optimize it and automatically do the transformation for the user. This is simple to conserve the pattern in Keras that every compatible 2d function has a 1d equivalent (and maybe even a 3d).

**Comment by ryanpeach** [comment]
Something like this:

``` python
def Conv1DTranspose(*args, **kwargs):
    def closure(x):
        r = Reshape((1, -1, -1))(x)
        c = Conv2DTranspose(*args, **kwargs)(r)
        l = Lambda(lambda x: x[0])(c)
        return l
    return closure
```

**Comment by wenouyang** [comment]
Hi yaroslavvb, Hi Labalex21, 

Would you like to elaborate the way to re-shape the One D data to 2D matrix? Thanks.

**Comment by lytkarinskiy** [comment]
In [this](https://distill.pub/2016/deconv-checkerboard/) post it's said that transpose_2d is not very good idea for deconvolution and it's better to use image resize functionality. Can anyone check it ?

**Comment by RomelioTavas** [comment]
It seems that this is already supported in tensorflow or is this a different thing?
https://www.tensorflow.org/api_docs/python/tf/contrib/nn/conv1d_transpose

It would be nice to see this implemented in Keras without the Conv2DTranspose hack
