### ISSUE TITLE
Documentation for `tf.linalg.set_diag()` is missing return information

### ISSUE THREAD

**Issue by khatchad** [tensorflow/tensorflow#67255]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.16.1

### Custom code

No

### Current behavior?

Return information at https://www.tensorflow.org/api_docs/python/tf/linalg/set_diag. I only see args.

### Standalone code to reproduce the issue

It's a documentation "bug."

**Comment by khatchad** [comment]
Actually, I'm unsure whether these docs are for the correct API. I don't see a call to it anywhere in the examples.

**Comment by khatchad** [comment]
Ah, they haven't been updated for TF2. They still refer to the old [`matrix_set_diag`](https://www.tensorflow.org/api_docs/python/tf/linalg/set_diag) API.

**Comment by sushreebarsa** [comment]
@khatchad  You're right, the official TF documentation for tf.linalg.set_diag() doesn't explicitly mention the return value in the descriptiontf.linalg.set_diag. We will fix this documentation bug which will be reflecting soon. 
Thank you!

**Comment by sushreebarsa** [comment]
@khatchad Could you please let us know if you have referred to the above [comment](https://github.com/tensorflow/tensorflow/issues/67255#issuecomment-2104241615) and you could see the return information ?
Thank you!

**Comment by tilakrayal** [comment]
@khatchad,
Could you please try to contribute with the PR for the respective changes to be made in the mentioned document? Thank you!
