### ISSUE TITLE
text_classification_character_rnn.py is using GRU cell at old location(compile error)

### ISSUE THREAD

**Issue by jeffheaton** [tensorflow/tensorflow#6725]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

None

### Environment info
Operating System:

Mac

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.12.1

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

Try to compile/run (with latest 0.12.1 TF):

https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/examples/learn/text_classification_character_rnn.py

This causes error:

AttributeError: module 'tensorflow.contrib.rnn' has no attribute 'GRUCell'

### What other attempted solutions have you tried?

Looks like GRUCell got moved from tensorflow.contrib.rnn to tf.nn.rnn_cell.RNNCell.  I tried making this change to the example code, but this leads to other errors.  It looks like the signature changed too.  

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by merttopcu** [comment]
here's the fix:

  # Create a Gated Recurrent Unit cell with hidden size of EMBEDDING_SIZE.
  # cell = tf.contrib.rnn.GRUCell(EMBEDDING_SIZE)
  cell = tf.nn.rnn_cell.GRUCell(EMBEDDING_SIZE)
  # Create an unrolled Recurrent Neural Networks to length of
  # MAX_DOCUMENT_LENGTH and passes word_list as inputs for each unit.
  #_, encoding = tf.contrib.rnn.static_rnn(cell, word_list, dtype=tf.float32)
  _, encoding = tf.nn.rnn(cell, word_list, dtype=tf.float32)

**Comment by jeffheaton** [comment]
I am not seeing this on the latest 1.0 version of TensorFlow.  No longer an issue, as far as I am concerned.
