### ISSUE TITLE
Error importing Tensorflow

### ISSUE THREAD

**Issue by beraybentesen** [tensorflow/tensorflow#6726]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: ubuntu 16.04 LTS - Tensorflow-GPU installed ( GTX 970 )

Installed version of CUDA and cuDNN:  7.5 - 4.5
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`): 

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

### What other attempted solutions have you tried?

Tried from scratch 4 times including formatting system. 

Installed from pip 2 times, and installed with bazel 2 times. No error at during setup. 

Tried all recommendations from other developers especially faced with this one.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by Carmezim** [comment]
Can you include the entire error message?

**Comment by gunan** [comment]
Ah, It is difficult to see because of the because it is not formatted.
Error message is:
```
Error importing tensorflow. Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```
The error message actually is quite helpful here. you simply need to exit your interpreter, change your directory to something other than the directory where you cloned github tensorflow repository.

The reason for the issue is python gets confused about what to import when you run "import tensorflow" (the one in your directory or the system installed one). That is what the error message is trying to say.

**Comment by namrathaurs** [comment]
Any pointers for the following error would be greatly appreciated. I am new to GitHub and its working model. So, please do let me know what details you would need that would help me in resolving this issue being encountered -

bash_prompt: ~ $ python
Python 2.7.3 (default, Oct 26 2016, 21:01:49) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: clock_gettime


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by Carmezim** [comment]
@namrathaurs welcome to Github. It would be interesting to open a new issue but let's get at it. How did you install TensorFlow?

**Comment by namrathaurs** [comment]
@Carmezim - Thanks for your quick reply to my issue here on GitHub! Appreciate it.

Just as an FYI here, since I already opened a new issue :
Well, I did check #121 as you suggested before I could post my issue here. However, when I was reading about updating the GLIBC version, I was fumbled as I read that a new GLIBC would mean upgrading the current version of Ubuntu to 14.04 (which may not be feasible in my scenario). Also, it was mentioned that Ubuntu 12.04 supports only GLIBC_2.16. If at all it needs to be upgraded to the next higher version, then the entire Ubuntu OS may need to undergo an upgrade.

I would be happy to hear from you about this as well on my new issue discussion that i created a couple of minutes ago. Thanks for all your help, in advance!

**Comment by bohemia420** [comment]
just FYI, this worked for me too(for Mac OS X, though) , Philippe Remy's answer here : 
http://stackoverflow.com/questions/33622842/error-in-python-after-import-tensorflow-typeerror-init-got-an-unexpect

**Comment by beraybentesen** [comment]
First, I solve problem by running Tensorflow in Docker container but Docker has it's own difficulties so I solve problem completely by using Basel. It works well without any problem.

**Comment by FrankMiaow** [comment]
Dear  Carmezim :
I meet this error
Error message is:

Error importing tensorflow. Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

You said that python gets confused about what to import when running "import tensorflow" (the one in your directory or the system installed one). BUT actually I did not  install one in the system, I would be happy to get help from you.

**Comment by shivaraj066** [comment]
Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help
