### ISSUE TITLE
NumPy 2.0 support

### ISSUE THREAD

**Issue by jakirkham** [tensorflow/tensorflow#67291]
### Problem description

NumPy 2.0 is coming out soon ( https://github.com/numpy/numpy/issues/24300 ). NumPy 2.0.0rc1 packages for conda & wheels came out a month ago ( https://github.com/numpy/numpy/issues/24300#issuecomment-2030603395 )

### Feature description

NumPy has put out [a migration guide]( https://numpy.org/devdocs/numpy_2_0_migration_guide.html#numpy-2-migration-guide ). More details are in [the release notes]( https://numpy.org/devdocs/release/2.0.0-notes.html )

If TensorFlow make use of NumPy's C API (and produces wheels that use it), having a release of TensorFlow with wheels built against NumPy 2.0.0rc1 would be helpful to ensure NumPy 1 & 2 compatible wheels (as wheels built against NumPy 1 won't be compatible with NumPy 2). More details in [this NumPy 2 ABI doc]( https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-abi-handling )

Also would recommend incorporating NumPy 2 in TensorFlow's CI

Also as NumPy is tracking ecosystem support for NumPy 2.0, it would be helpful to share TensorFlow's current support status in issue (with any plans): https://github.com/numpy/numpy/issues/26191

### Additional information

There has been some discussion about TensorFlow's NumPy 2 plans here: https://github.com/numpy/numpy/issues/26191#issuecomment-2078401952

Also the Keras team is interested in this question as they depend on TensorFlow: https://github.com/keras-team/keras/issues/19691#issuecomment-2103062310

Lastly was unable to find an existing issue by searching or asking AI. So went ahead and opened this. If there's an existing one, happy to close and follow that

cc @MichaelHudgins @jakevdp @rgommers (for vis)

**Comment by jakirkham** [comment]
Am curious if anyone has had a chance to look into this. No worries if not

It is worth noting that NumPy is planning to release 2.0 on June 16th: https://github.com/numpy/numpy/issues/24300#issuecomment-2125643448

**Comment by MichaelHudgins** [comment]
Sorry for the late reply, TF is working on the upgrade but it may not make the upcoming branchcut to ensure all cases around datatype promotion are handled correctly.  @kanglant is working on the upgrade and ensuring test owners verify updates.  We will give another status update by Friday on if it will make the 2.17 branchcut and when it can be expected in the nightly branch.

**Comment by jakirkham** [comment]
Thanks Michael! 🙏

No worries

Are Kanglan's changes in a PR? Or could they be added to one? Maybe members of the community could help review 🙂

FWIW did see these merged PRs:

* https://github.com/tensorflow/tensorflow/pull/63317
* https://github.com/tensorflow/tensorflow/pull/67852
* https://github.com/tensorflow/tensorflow/pull/67864
* https://github.com/tensorflow/tensorflow/pull/68271

Are there any others?

**Comment by MichaelHudgins** [comment]
No other PRs right now that i think are ready yet.  

I can say that at this point it looks like we will not make the target of next week's branchcut.  We need to verify if any of the fixes or modifications cause api level changes given TF's API compatibility guidelines.  We will target to get it into nightly as soon as we can.  We will look to use this issue to give regular updates until have made the 2.0 upgrade.

**Comment by jakirkham** [comment]
Would recommend that any released packages (wheels or otherwise) have an upper bound to disallow NumPy 2

Mentioning this as NumPy is planning to release on June 16th: https://github.com/numpy/numpy/issues/24300#issuecomment-2125643448

**Comment by henryiii** [comment]
Upper bounds will just cause solvers like pip to select older versions of tensorflow without the bound.

**Comment by jakirkham** [comment]
Am aware that is true of Conda, but does the pip solver also have this behavior? Are there examples of this?

**Comment by henryiii** [comment]
Ahh, yes, if nothing causes a backtrack, it does work. It can still backtrack in some cases and produce unhelpful solves, but by default it would help to have the limit. The simple case of `pip install tensorflow` will be broken tomorrow without a limit.

**Comment by rgommers** [comment]
It won't be broken - TensorFlow has always used upper bounds for all of its dependencies AFAIK. I am pretty sure there are no versions of TensorFlow for Python 3.9-3.12 that depend on an unpinned `numpy`.

**Comment by matthewfeickert** [comment]
Yeah, [`tensorflow` `v2.16.1`](https://github.com/tensorflow/tensorflow/releases/tag/v2.16.1) had the following requirements (with caps on `numpy < 2.0` introduced in https://github.com/tensorflow/tensorflow/commit/92b81403305ddba765d3fb9a64bae8f52bf90dfd on 2023-10-16)

https://github.com/tensorflow/tensorflow/blob/5bc9d26649cca274750ad3625bd93422617eed4b/tensorflow/tools/pip_package/setup.py#L85-L126

**Comment by mihaimaruseac** [comment]
Unfortunately, the team won't upgrade any TF below 2.16, now that the process for 2.17 started and the builds for the last patch release on 2.16 have been triggered (it used to be that patches were given for a full year, now it's just one patch on the next release and that's all :shrug: )

**Comment by matthewfeickert** [comment]
Yeah that's all totally reasonable. 👍 I hope it didn't come across like I was hoping for anything to get back ported.

**Comment by mihaimaruseac** [comment]
No, it's all good. In the old system, 2.14 and 2.13 would still have been updated to had the upper bound.

**Comment by henryiii** [comment]
As long as the latest one has a bound, that’ll fix most cases. Weird backsolves will happen if someone requires >=2, but that isn’t possible to fix without NumPy 2 support, so it’ll just be a slightly stranger error message, which is totally fine I think.

**Comment by hmaarrfk** [comment]
Kind ping on this front.

> We will target to get it into nightly as soon as we can. We will look to use this issue to give regular updates until have made the 2.0 upgrade.

I think there is still the fact that setup.py declares that 2.0 isn't supported:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py#L88

Has the full test suite been run with success? Maybe we can start to use the new-style pinning?

**Comment by mihaimaruseac** [comment]
There is some work on this front, see #72883

**Comment by kanglant** [comment]
Sorry for the late reply. We're conducting thorough internal testing and expect to provide an update within the next few weeks.

**Comment by jschueller** [comment]
hello, any news on this ?

**Comment by kanglant** [comment]
Hi @jschueller , we've addressed most of the compatibility issues with NumPy 2, and you can expect TensorFlow nightly wheels compiled against NumPy 2 within the next week. 🎉

**Comment by dutchy54321** [comment]
will it be announced somewhere when Tensorflow works with Numpy 2?  I upgraded to Python 3.12.5 because another plugin that I use did an upgrade and only works with Numpy 2 and higher.  So when I then install tensorflow it automatically uninstalls my Numpy 2.1 version and installs 1.26. So I  took down uninstalled Tensorflow for the time being. Of course I can still use my Python 3.8.5 version but I run my Python code from another program that requires Numpy 2 or higher.

Where will it be announced when Tensorflow has been upgraded to work with Numpy 2.0 and higher? Thanks

**Comment by mihaimaruseac** [comment]
Most likely in this issue

**Comment by jschueller** [comment]
is there a specific PR or commits we can backport on 2.17 for numpy 2 support ?

**Comment by mihaimaruseac** [comment]
I think that's not possible. The development process results in individual commits to main branch and not all of them are tagged with the feature they are working towards. And, unfortunately, some are just tagged "internal change", so not even by reading the commit message would you be able to determine if the commit is relevant or not.

I think the number of changes is quite significant, so you would have to cherrypick quite a large number of commits if you want to go that way and hope that the compilation process won't fail. If possible, wait a little bit, 2.18 is around the corner and might have numpy 2 by default.

**Comment by jschueller** [comment]
fair enough, do you know the release schedule for 2.18 ?

**Comment by mihaimaruseac** [comment]
I _estimate_ (not on the team) that branch cut would happen by the end of this month and then in around at most a month there will be a final release. Definitely before Thanksgiving (end of Nov)

**Comment by jschueller** [comment]
ok, thanks

**Comment by kanglant** [comment]
A quick update: TensorFlow nightly wheels are now compiled with NumPy 2.0, starting with the latest release 2.18.0.dev20240919!

**Comment by dutchy54321** [comment]
did not yet work for me. I did: pip install tf-nightly==2.18.0.dev20240919

but seems it is installing 2.17

Installing collected packages: numpy, tb-nightly, keras-nightly, tf-nightly-intel, tf-nightly
  Attempting uninstall: numpy
    Found existing installation: numpy 2.1.1
    Uninstalling numpy-2.1.1:
      Successfully uninstalled numpy-2.1.1
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\win 10\AppData\Local\Programs\Python\Python312\Lib\site-packages\~~mpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
**tensorflow-intel 2.17.0 requires numpy<2.0.0,>=1.26.0; python_version >= "3.12", but you have numpy 2.0.2 which is incompatible.**
Successfully installed keras-nightly-3.5.0.dev2024092003 numpy-2.0.2 tb-nightly-2.18.0a20240919 tf-nightly-2.18.0.dev20240919 tf-nightly-intel-2.18.0.dev20240919

**Comment by mihaimaruseac** [comment]
Oh, that's because on Windows you also need tensorflow-intel, which is a separate package, developed by a TF collaborator: https://blog.tensorflow.org/2022/09/announcing-tensorflow-official-build-collaborators.html

**Comment by dutchy54321** [comment]
ok thanks so I guess some more waiting. I think I will revert back to Python 3.8.5 for the time being

**Comment by mihaimaruseac** [comment]
I think if you try with the linux version under WSL (or on a Linux host) it would work. It's just some Mac versions and the Windows one that are no longer done by Google.

**Comment by dutchy54321** [comment]
i work on Windows. The program I use runs on windows. From that program I can use Python via a plugin. That plugin has been upgraded to work only with Numpy 2.0 and higher.  So that would require me to run Python 3.9 or higher and Numpy 2.0 or higher.  The reason I run Python from that program is because I have all my data in that program.

But I also still have the old plugin that works with Numpy below 2.0 and Python 3.8. So it is no big deal. I just use the old plugin and change my Path in the Environment settings back to 3.8.

So you are saying that on Windows I will have problems using Tensorflow from now on? Or will this be fixed at some point.

**Comment by mihaimaruseac** [comment]
Will likely be fixed at some point once the companies doing the other builds update their builds.

**Comment by hmaarrfk** [comment]
@dutchy54321 I am sympathetic to your cause, but this isn't the place to have the discussion on windows support from the official tensorflow releases.

I think it may be more appropriate to read on in https://github.com/tensorflow/tensorflow/issues/59918

(PS. I am just an other user working to help on the integration front)

**Comment by dutchy54321** [comment]
> @dutchy54321 I am sympathetic to your cause, but this isn't the place to have the discussion on windows support from the official tensorflow releases.
> 
> I think it may be more appropriate to read on in #59918
> 
> (PS. I am just an other user working to help on the integration front)

I do not understand. I use tensorflow. I updated Python and a plugin I use. Then I had problems installing tensorflow after I installed the latest Numpy version. Then after searching I ended up in this thread. Does it matter which operating system I use?

**Comment by mihaimaruseac** [comment]
> Does it matter which operating system I use?

Unfortunately, yes. Google TF team can only provide support for Linux TF.

**Comment by jdblischak** [comment]
TensorFlow [2.18.0](https://github.com/tensorflow/tensorflow/releases/tag/v2.18.0) supports numpy 2. Can this Issue can be closed?

```sh
python -m venv ./tf-numpy2
source ./tf-numpy2/bin/activate
python --version
## Python 3.10.15
python -m pip install --prefer-binary numpy==2 tensorflow-cpu
pip list | grep -e numpy -e tensorflow
## numpy                        2.0.0
## tensorflow_cpu               2.18.0
## tensorflow-io-gcs-filesystem 0.37.1
python -c "import tensorflow as tf; print(tf.add(1, 2).numpy())"
## 3
python -c "import tensorflow as tf; print(tf.constant('Hello, TensorFlow').numpy())"
## b'Hello, TensorFlow'
```

**Comment by kanglant** [comment]
thanks for the reminder
