### ISSUE TITLE
Add contrib/tfprof to CMake build

### ISSUE THREAD

**Issue by NoNoCalm** [tensorflow/tensorflow#6731]
Tensorflow for windows has package missing issue
Path: tensorflow/contrib/tfprof
All the files under the path are missing,resnet model replies on these files.
Please pay attention,thank you.

**Comment by NoNoCalm** [comment]
![image](https://cloud.githubusercontent.com/assets/6457892/21759010/d284a55a-d67b-11e6-9b45-2c6fac98712a.png)
Is it caused by this?

**Comment by jart** [comment]
Thank you for reaching out. I've assigned this feature request to one of the contrib/cmake maintainers.

To the best of my knowledge, the Bazel+Windows build currently doesn't have support for the packages in contrib. So there's probably no viable workaround right now for using contrib/tfprof on Windows.

**Comment by NoNoCalm** [comment]
Does It mean that this issue won't be solved in the coming months?

**Comment by jart** [comment]
We've got people actively working to bring good Windows support to TensorFlow. We can't promise timelines but we're doing our best to take care of our Windows users.

**Comment by girving** [comment]
@panyx0718 What's the status of this issue?

**Comment by panyx0718** [comment]
Looks like other packages in contrib/ are available in Windows except tfprof.
It seems it's because this comment
"add_python_module("tensorflow/contrib/tfprof" DONTCOPY)  # SWIG wrapper not implemented."

I'm trying to enable tfprof in Windows and see what error presubmit will give me.

**Comment by panyx0718** [comment]
@NoNoCalm I added tfprof cmake and it's now in tf.profiler. Maybe you can give it a try?
