### ISSUE TITLE
array operations in tensorflow

### ISSUE THREAD

**Issue by raady07** [tensorflow/tensorflow#6732]
ubunutu14.0.4
python3.5 

Hello, 

Im new using tensorflow library. Im trying to access data in text file and I can run it as python code but access the array elements using this library is not known. Please help

I have a text file that contains float and integer values
`import tensorflow as tf
import numpy as np
import os
file_pathname1 = os.path.join(os.path.expanduser('~'),'Desktop','TF','Practice Files','test')
x = np.loadtxt(file_pathname1)
#y1 = x[1, 4] # load data to another variable
print(x)

y = tf.readfile(file_pathname1)

sess = tf.Session()
print(sess.run(y))
`
how can i copy the same as array form using tensor flow

because the output of both is different
`[[ 1.3  2.5  3.5  4.4]
 [ 5.2  6.5  7.6  8.8]]`

`b'1.3 2.5 3.5 4.4\n5.2 6.5 7.6 8.8'`

**Comment by yaroslavvb** [comment]
this list is for bugs in TF/feature requests, could you ask on stackoverflow?
