### ISSUE TITLE
slim parallel_read should pass seed to string_input_producer

### ISSUE THREAD

**Issue by jonasrauber** [tensorflow/tensorflow#6735]
Currently, the seed passed to `parallel_read` is only passed to the RandomShuffleQueue, but not to the string_input_producer. This should be fixed. Furthermore, it should also be documented that the output will never be deterministic if `num_readers` is greater than 1.

https://github.com/tensorflow/tensorflow/blob/e121667dc609de978a223c56ee906368d2c4ceef/tensorflow/contrib/slim/python/slim/data/parallel_reader.py#L212

**Comment by jart** [comment]
@sguada I'm not sure if this is a bug, but @jonasrauber seems to be requesting a relatively trivial change.

**Comment by sguada** [comment]
Totally it makes sense.
