### ISSUE TITLE
How to train Multibox object detector included in the TF Detect Android demo

### ISSUE THREAD

**Issue by cyanoboy** [tensorflow/tensorflow#6738]
There is a way to train a custom model for the multibox object detector that is included in the [TF Detect Android demo](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/DetectorActivity.java)?

**Comment by andrewharp** [comment]
@cyanoboy We're preparing a walk through for exactly this; should be out sometime in the not-too-distant future.

**Comment by jart** [comment]
Assigning to @andrewharp assuming he wants to add `Fixed #6738` to the commit message which adds that walkthrough.

**Comment by lukeisontheroad** [comment]
@andrewharp can you give us an update about the walk through? Thanks for your awesome work 👍

**Comment by andrewharp** [comment]
@lukeisontheroad We're still moving around stuff internally, it's ending up being a bit tricky to open-source. In the meantime there is the [TF YOLO detector](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowYoloDetector.java) which you should be able to find training walkthroughs for online.

**Comment by lvauchier** [comment]
Is there a trained version available for the custom inceptionV2 used for the feature extraction in the multibox object detector ?
Thank you for your work on this demo

**Comment by itsmeolivia** [comment]
hey Andrew, is this still forthcoming?

**Comment by andrewharp** [comment]
This is still active. We're looking to get a model compatible with the [TF Object Detection API](https://github.com/tensorflow/models/tree/master/object_detection) out in the next 2 or 3 weeks. That should provide a much easier path to retraining.

@jch1

**Comment by jch1** [comment]
Yup, this should be done soon, stay tuned!

**Comment by Moriadry** [comment]
sounds awesome!

**Comment by SuperChange001** [comment]
@andrewharp Thanks for your information!

**Comment by andrewharp** [comment]
The default object detector in the Android Object Detection demo is now the 80-class Object Detection API SSD model thanks to @jch1's commit, so retraining is now possible.

The Yolo and original Multibox detectors remain available by modifying [DetectorActivity.java](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/DetectorActivity.java#L89) (the person-detecting multibox model `@mobile_multibox` would also need to be added to [external_assets](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/BUILD#L92) if reverting).
