### ISSUE TITLE
Use of deprecated (Py2.6) / removed (Py3) BaseException.message

### ISSUE THREAD

**Issue by ethereon** [tensorflow/tensorflow#674]
The `message` attribute was [deprecated in Python 2.6 and removed in Python 3](https://www.python.org/dev/peps/pep-0352/). However, it's still used in TensorFlow.

For instance, [over here in session.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/session.py#L354). Under Python 3, this will raise another exception during exception handling.

**Comment by vrv** [comment]
Thanks for the report - feel free to send us a pull request to fix this!

**Comment by itsmeolivia** [comment]
I fixed this for the next release!
