### ISSUE TITLE
Building binary for Sparkfun Edge

### ISSUE THREAD

**Issue by h-tye** [tensorflow/tensorflow#67418]
I am trying to upload micro speech detection onto the SparkFun Edge device using this tutorial: https://codelabs.developers.google.com/codelabs/sparkfun-tensorflow/#3 . However, the directory needed to build the binary in the first part of step 4 no longer exists, has anyone found a way around this? The issue is tensorflow has tflite-micro as a standalone repository now but it no longer has the same tools.

**Comment by sushreebarsa** [comment]
@h-tye You're right, the original TensorFlow Lite for Microcontrollers tutorial relies on an older directory structure that's no longer included. Kindly refer to the workaround as follows;
The SparkFun Edge device often comes pre-loaded with a sketch called "micro_speech.ino". This sketch implements basic micro speech detection using TensorFlow Lite. You can try the following:

1. Connect your SparkFun Edge to your computer using the SparkFun USB-C Serial Basic programmer.
2. Open the Arduino IDE.
3. In the Arduino IDE, go to **_File > Examples > SparkFun Edge > micro_speech_**. This should open the pre-loaded sketch.
4. Upload the sketch to your SparkFun Edge.
5. Open the Serial Monitor in the Arduino IDE. You should see the blue LED blinking.
6. Speak a keyword like "yes" or "no" near the microphone. If the speech is recognized, the serial monitor will display a message and the yellow LED will blink.

Also refer the TensorFlow Lite Micro getting started [guide]( https://www.tensorflow.org/lite/microcontrollers) for more information. 

Thank you!

**Comment by h-tye** [comment]
@sushreebarsa Unfortunately, I am not able to use the Arduino IDE as when I run any code - even the examples- I get an error that reads "Unsupported Board". I believe that Arduino no longer supports the Sparkfun Edge which is why I was trying to flash binary onto the device. Thanks for the help

**Comment by h-tye** [comment]
Correction: It looks like the Arduino examples for Sparkfun edge are no longer supported by TensorFlow, not Arduino. https://github.com/tensorflow/tflite-micro-arduino-examples?tab=readme-ov-file#how-to-install as per this github repo, the peripherals are made purely for the Arduino Nano 33 BLE, which means that anytime I run one of the examples it produces a "unsupported board" error.

**Comment by sushreebarsa** [comment]
@h-tye There might not be official Arduino libraries for the SparkFun Edge specifically, TFLite Micro offers support for various Arm Cortex-M processors, which the SparkFun Edge uses (https://www.tensorflow.org/lite/microcontrollers). 
For any further queries could you please post this issue in [this](https://github.com/tensorflow/tflite-micro/issues)  repository ?
Thank you!
