### ISSUE TITLE
aarch64/arm64 Tensorflow Lite runtime wheels not compatible with silicon OSX ?

### ISSUE THREAD

**Issue by huats** [tensorflow/tensorflow#67422]
I have followed the instructions available [here](https://www.tensorflow.org/lite/guide/build_cmake_pip?hl=fr&_gl=1*uh09l8*_up*MQ..*_ga*NDczOTAyOTg5LjE3MTU1Mzg4MTY.*_ga_W0YLR4190T*MTcxNTUzODgxNi4xLjAuMTcxNTUzODgxNi4wLjAuMA.. ) to create some wheel files for aarch64 using the command

`PYTHON=python3 TENSORFLOW_TARGET=aarch64 tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh`

From my understanding I should be able to use that wheel on my OSX silicon macbook (m2) since aarch64 is arm64

But I get the following error
```
pip install tensorflow/lite/tools/pip_package/gen/tflite_pip/python3/dist/tflite_runtime-2.16.1-cp310-cp310-linux_aarch64.whl
ERROR: tflite_runtime-2.16.1-cp310-cp310-linux_aarch64.whl is not a supported wheel on this platform.
```

Am I doing something wrong ? Thanks in advance

**Comment by huats** [comment]
I realize that I am trying to use on mac a whl file created for linux... I am pretty sure it is the issue, but if someone can confirm that to me I would appreciate...

**Comment by RavinduTharanga** [comment]
Yes it is. try linux machine.

**Comment by sawantkumar** [comment]
hi @huats ,

Let me know if the provided solution worked for you.

**Comment by huats** [comment]
Hello @sawantkumar I am not sure to well understand the proposed solution.
The linux aarch64 wheel do not work on my Mac that is for sure.
So the solution that is proposed is to use that wheel on a Linux machine ? It do not fix my building issue right ? Or do I misunderstand ?

**Comment by sawantkumar** [comment]
Hi @huats ,

Your Apple Silicon Macbook (M2) uses an ARM-based architecture as well, but it's specifically arm64 with macOS optimizations. These optimizations are not compatible with the Linux-specific aarch64 wheel. What i will suggest you is to try out the below command which specifies the correct architecture to use 

`PYTHON=python3 TENSORFLOW_TARGET=darwin_arm64 tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh`


Alterenatively you can check out this previous [issue](https://github.com/tensorflow/tensorflow/issues/55369) and also [this](https://developer.apple.com/metal/tensorflow-plugin/) from the apple developer website. Please let me know if the above solution worked for you.
