### ISSUE TITLE
Any build help with tensorflow-text

### ISSUE THREAD

**Issue by swoiow** [tensorflow/tensorflow#67465]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.16

### Custom code

No

### OS platform and distribution

windows

### Current behavior?

I just want to use tensorflow/text in windows, I tried to make a build, but failed, just look in [fork](https://github.com/swoiow/text).

**Any help with me? tell me the stage with the build(any ecosystem design or idea on the build task, which is the 1,2,3), what deps on the build**, and let me fix it.

more issues for Windows:

- https://github.com/tensorflow/text/issues/1255
- https://github.com/tensorflow/text/issues/1221
- https://github.com/tensorflow/text/issues/1140

thanks

### Standalone code to reproduce the issue

```shell
~
```

**Comment by tilakrayal** [comment]
@swoiow,
After version 2.10, we will only be providing pip packages for Linux x86_64 and Intel-based Macs. For other systems like Windows, Aarch64, and Apple Macs, TensorFlow relies on [build collaborators](https://blog.tensorflow.org/2022/09/announcing-tensorflow-official-build-collaborators.html), and so we will not be providing packages for them. However, we will continue to accept PRs to make building for these OSs easy for users, and will try to point to community efforts related to them.

https://github.com/tensorflow/text/blob/master/README.md#a-note-about-different-operating-system-packages

Please try to install using WSL/WSL2. Thank you!

**Comment by swoiow** [comment]
Yes, i notify the note,  i need more details for build, then i try to fix it. Any help? @tilakrayal

**Comment by tilakrayal** [comment]
@swoiow,
The fix which you are mentioning would be provided by the tensorflow-text team. Could you please raise the concern on the respected [repo](https://github.com/tensorflow/text/issues/) or the contribute with the PR for the quick resolution. Thank you!

**Comment by tilakrayal** [comment]
@swoiow,
As mentioned above, Could you please raise the concern on the respected [repo](https://github.com/tensorflow/text/issues/) or the contribute with the PR for the quick resolution. The Tensorflow team doesn't have any control over the text. Thank you!
