### ISSUE TITLE
Apple Silicon, building pip package ... clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by zepouet** [tensorflow/tensorflow#67473]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.16.1

### Custom code

No

### OS platform and distribution

Mac Sonoma 14.4.1

### Python version

3.10

### GCC/compiler version

Apple clang version 15.0.0 (clang-1500.3.9.4) Target: arm64-apple-darwin23.4.0

### GPU model and memory

M3 MAX

### Current behavior?

Hello,

Cannot compile the python library for Apple Silicon about TF Lite

### Standalone code to reproduce the issue

```shell
Try to compile with and without aarch64 target because of arm64 doesn't succed

PYTHON=python3 tensorflow/lite/tools/pip_package/build_pip_package_with_cmake.sh native
```

### Relevant log output

```shell
pybind11::detail::type_caster<bool, void>& pybind11::detail::load_type<bool, void>(pybind11::detail::type_caster<bool, void>&, pybind11::handle const&) in interpreter_wrapper_pybind11.cc.o
      bool pybind11::detail::argument_loader<tflite::interpreter_wrapper::InterpreterWrapper&, int, pybind11::handle&, bool, int>::load_impl_sequence<0ul, 1ul, 2ul, 3ul, 4ul>(pybind11::detail::function_call&, std::__1::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul, 4ul>) in interpreter_wrapper_pybind11.cc.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [_pywrap_tensorflow_interpreter_wrapper.dylib] Error 1
make[2]: *** [CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/all] Error 2
make[1]: *** [CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/rule] Error 2
make: *** [_pywrap_tensorflow_interpreter_wrapper] Error 2

make[1]: *** [CMakeFiles/_pywrap_tensorflow_interpreter_wrapper.dir/rule] Error 2
make: *** [_pywrap_tensorflow_interpreter_wrapper] Error 2
```

**Comment by pkgoogle** [comment]
Hi @zepouet, can you try with `Clang from xcode 13.6`: https://www.tensorflow.org/install/source#macos ensure your versions are aligned with the compatibility matrix. Thanks.

**Comment by zepouet** [comment]
Hello @pkgoogle, can you give me the compatibily matrix please ? Thanks. 
I fear to downgrade CLang and have side effect elsewhere.
I will try neverthless outside.
Thanks a lot

**Comment by pkgoogle** [comment]
Hi @zepouet, apologies, it's lower down the link's page, I had thought I linked it directly: https://www.tensorflow.org/install/source#cpu_2
