### ISSUE TITLE
Got an unexpected keyword argument error when I call tf.contrib.layers.convolution2d on Tensorflow for Windows

### ISSUE THREAD

**Issue by AndreaFar** [tensorflow/tensorflow#6748]
When I invoke tf.contrib.layers.convolution2d the tensorflow execution terminates with an error about one of the parameters used

the call is

```
layer_one = tf.contrib.layers.convolution2d(
    float_image_batch,
    num_output_channels=32,     
    kernel_size=(5,5),          
    activation_fn=tf.nn.relu,
    weight_init=tf.random_normal,
    stride=(2, 2),
    trainable=True)
```

I have tried to fix according new documentation using tf.random_normal_init but get always the same problem

OS: Windows 10 x64
Tensorflow 0.12.0 

Related Stackoverflow question: http://stackoverflow.com/questions/41539658/tensorflow-error-when-i-try-to-use-tf-contrib-layers-convolution2d

**Comment by gunan** [comment]
Looking at the documentation here:
https://www.tensorflow.org/api_docs/python/contrib.layers/higher_level_ops_for_building_neural_network_layers_#separable_convolution2d

- weight_init is not a keyword, it has to be weight_initializer
- num_output_channels is not a keyword, maybe you mean num_outputs

Please make sure you read the documentation carefully. Python wont accept any abbreviations or any similar keywords.

**Comment by AndreaFar** [comment]
same problem got an unexpected keyword argument 'weight_initializer'
