### ISSUE TITLE
Error building TensorFlow within Docker Container

### ISSUE THREAD

**Issue by alexminnaar** [tensorflow/tensorflow#6750]
I am following the instructions for using TensorFlow serving from https://tensorflow.github.io/serving/serving_inception.html
and after I clone tf within the container and build it with `./configure`

I get the following errors

```
ERROR: /serving/tensorflow/tensorflow/workspace.bzl:375:3: no such package '@junit_jar//jar': Error downloading [https://github.com/junit-team/junit4/releases/download/r4.12/junit-4.12.jar] to /root/.cache/bazel/_bazel_root/5071e8dca1385fb776f72b33971bf157/external/junit_jar/junit-4.12.jar: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and referenced by '//external:junit'.

ERROR: /serving/tensorflow/tensorflow/workspace.bzl:375:3: no such package '@junit_jar//jar': Error downloading [https://github.com/junit-team/junit4/releases/download/r4.12/junit-4.12.jar] to /root/.cache/bazel/_bazel_root/5071e8dca1385fb776f72b33971bf157/external/junit_jar/junit-4.12.jar: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty and referenced by '//external:junit'.

ERROR: Evaluation of query "deps(... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
```

and the `...` in the last error contains about 200 lines of additional text

**Comment by gunan** [comment]
Looks like this is an issue in tensorflow serving docker image.
@kirilg @jharmsen Could you take a look?

**Comment by kirilg** [comment]
Can you try running `update-ca-certificates -f`?

**Comment by alexminnaar** [comment]
@kirilg I tried that.  There was no change

**Comment by kirilg** [comment]
Hmm, not sure. This the the general workaround fix for these java.security.InvalidAlgorithmParameterException errors that worked for us before. Did that command succeed and you still see the error? Can you also try:
`sudo apt-get install ca-certificates-java`
`sudo update-ca-certificates -f`

**Comment by alexminnaar** [comment]
Ok working now.  My hunch is this was due to a spotty network connection - maybe something got downloaded incorrectly
