### ISSUE TITLE
Tensorflow using Intel GPU instead of NVIDIA GPU 

### ISSUE THREAD

**Issue by fzd370** [tensorflow/tensorflow#67558]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.10.1

### Custom code

Yes

### OS platform and distribution

Windows 11

### Python version

3.9.19

### CUDA/cuDNN version

11.2.2/8.1.0.77

### GPU model and memory

Nvidia Geforce GTX 1650 - 4GB

### Current behavior?

I've installed the tensorflow in virtual environment in Anaconda using official documentation and it is running fine. Whenever I'm training my model I see that the tensorflow is using Intel GPU instead of Nvidia GPU.  The default GPU for tensorflow is Intel GPU. How do I change this so that tensorflow uses Nvidia GPU. I've installed CUDA and cuDNN as mentioned in the documentation.

![Screenshot 2024-05-14 185258](https://github.com/tensorflow/tensorflow/assets/36449965/7cc0e3ed-f9dd-4c4d-bb0e-eb4cd173f274)
![Screenshot 2024-05-14 185346](https://github.com/tensorflow/tensorflow/assets/36449965/a812bef6-4f42-4058-8f39-0930950905af)
![Screenshot 2024-05-14 190253](https://github.com/tensorflow/tensorflow/assets/36449965/5678b0fc-cb1c-4e82-8e25-61ab2c78b643)

As it is mentioned in the offical documentation that if you have more than one GPU in your system, the GPU with the lowest ID will be selected by default. How do I change this? Please help.

I

### Standalone code to reproduce the issue

```shell
I followed the steps mentioned in the documentation.
```

**Comment by sushreebarsa** [comment]
@fzd370 In TensorFlow v2.10, the default behavior is to choose the GPU with the lowest ID. This typically leads to selecting the integrated Intel GPU over a dedicated Nvidia GPU.Please ensure you're running your Python scripts or Jupyter notebooks within the activated virtual environment where you installed TensorFlow with GPU support. Kindly double-check your CUDA and cuDNN installations. 

Thank you!
