### ISSUE TITLE
OSX Fail to run tensorflow/contrib/makefile/download_dependencies.sh

### ISSUE THREAD

**Issue by jam-world** [tensorflow/tensorflow#6755]
Running on OSX

Run 

sh tensorflow/contrib/makefile/download_dependencies.sh in the home directory

And I get 

downloading https://bitbucket.org/eigen/eigen/get/60578b474802.tar.gz
downloading https://github.com/google/gemmlowp/archive/a6f29d8ac48d63293f845f2253eccbf86bc28321.tar.gz
downloading https://github.com/google/googletest/archive/release-1.8.0.tar.gz
downloading https://github.com/google/protobuf/archive/008b5a228b37c054f46ba478ccafa5e855cb16db.tar.gz
downloading https://github.com/google/re2/archive/b94b7cd42e9f02673cd748c1ac1d16db4052514c.tar.gz
sed: tensorflow/contrib/makefile/downloads/eigen/Eigen/src/Core/arch/NEON/Complex.h: No such file or directory

How can I solve this problem? Thanks a lot!!

**Comment by jam-world** [comment]
Make sure your curl support https. Sometimes it is a problem for OSX. And the error message is muted in the download script.

**Comment by justinshapiro** [comment]
What did you do specifically to solve the issue? I'm having the same problem here on Mac OS X
