### ISSUE TITLE
Bazel - Tensorflow build failed

### ISSUE THREAD

**Issue by AceAbhi147** [tensorflow/tensorflow#67554]
I have a ubuntu 22.0.4 LTS machine running on virtual box. I am trying to build tensorflow by cloning the repo and following the steps defined here: [build from source].(https://www.tensorflow.org/install/source) I have checkout the master branch. And I have installed llvm-14 clang-14
rather than 17 as I was getting some not found error.

This is the command I am using to build tensorflow: 
`bazel build //tensorflow/tools/pip_package:wheel --repo_env=WHEEL_NAME=tensorflow_cpu`

But after waiting for what seems like hours, I am getting this error: 
`[12,514 / 15,964] 3 actions running
    Compiling tensorflow/compiler/mlir/tensorflow/ir/tf_ops_n_z.cc; 720s local
    Compiling tensorflow/compiler/mlir/tensorflow/ir/tf_ops.cc; 681s local
ERROR: /home/ace-ventura/tensorflow/tensorflow/compiler/mlir/tensorflow/BUILD:424:11: Compiling tensorflow/compiler/mlir/tensorflow/ir/tf_ops.cc failed: (Exit 1): gcc failed: error executing command (from target //tensorflow/compiler/mlir/tensorflow:tensorflow_ops) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 187 arguments skipped)
gcc: fatal error: Killed signal terminated program cc1plus
compilation terminated.
Target //tensorflow/tools/pip_package:wheel failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1144.307s, Critical Path: 724.97s
INFO: 176 processes: 4 internal, 172 local.
FAILED: Build did NOT complete successfully
`

If someone can take a look at this, it will great.

**Comment by sushreebarsa** [comment]
@AceAbhi147 Could you please confirm that you have followed the steps properly and also referred the tested build configurations? Please let us know!
![72Wi6T878zwwfuW](https://github.com/tensorflow/tensorflow/assets/84765720/ad687d88-2e89-4f4f-8061-7c0422e19329)



Thank you!
