### ISSUE TITLE
variable_scope behave differently for master code and release 0.12.1

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#6761]
For master code, git rev-parse HEAD
ec7929b878926c39255254e9aea992f0bc65aa68

The problem is one of my code used to work for release 0.12.1 fail for master code, which use adagrad as optimizer.
ValueError: Variable OptimizeLoss/w_h/Adagrad/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

I traced this and find below two simple codes can reproduce, the second one works for both 0.12.1 release and master, but the first one only works for 0.12.1 and fail master code. 
I wonder what's the diff here ?  code 2 style is suggested ? Why code 1 will fail ? Also for code 1 if I use gradient desc instead of adgrad will not fail. Similar error can occur when using lstm cell.

code 1:

      loss, accuracy = model.build_graph(X, y)  

      tf.get_variable_scope().reuse_variables()    

      eval_loss, eval_accuracy = model.build_graph(eval_X, eval_y)    

code 2:

    with tf.variable_scope("mlp") as scope:    

        loss, accuracy = model.build_graph(X, y)    

        scope.reuse_variables()    

        eval_loss, eval_accuracy = model.build_graph(eval_X, eval_y)

**Comment by chenghuige** [comment]
Also master code will fail when using cell(), I'm don't know how to workaround.
`    for i in range(max_steps):  
      with tf.variable_scope("RNN", reuse=True if i > 0 else None):  
        (output, state) = self.cell(last_symbol, state)  `

**Comment by jart** [comment]
@wicke do you think some of the 1.0 work might have caused this?

**Comment by martinwicke** [comment]
@lukaszkaiser or @ebrevdo , can you comment?

**Comment by lukaszkaiser** [comment]
It looks like some interaction between scopes and the initializer change (#5813). Could you provide a small but fully self-standing example code, so we can investigate further?

**Comment by chenghuige** [comment]
@lukaszkaiser  for the lstm cell, now I can workaround.    
It is due to self.cell declared not in "RNN" scope, if I do below to init self.cell in class.__init__ then ok for master code or version 1.0
    with tf.variable_scope("RNN"):
      self.cell = ...

**Comment by chenghuige** [comment]
@lukaszkaiser  for my code LSTM part I now get workaround by adding "RNN" scope when init self.cell 
 `    with tf.variable_scope("RNN"):   
        self.cell =  ... 
  `

**Comment by lukaszkaiser** [comment]
I think these 2 things might be unrealted: rnn cells migrated, and optimizers changed, so there might be 2 things. Could you prepare some small code to illustrate the remaining problems? Thanks!

**Comment by chenghuige** [comment]
@lukaszkaiser  For RNN cell problem. I find out the reason.  
When training I used  dynamic_rnn without setting sope, and tf v0.12 defualt scope is 'RNN'
while tf v1.0 defualt scope is 'rnn'. So that cause the error. Not a bug.

**Comment by jart** [comment]
Terrific. I'm glad we got to the bottom of things. I'm going to close this one out now.

**Comment by lukaszkaiser** [comment]
Hmm, the RNN was only the second problem. How about the first one? If it's still there, please reopen and, in the best case, attach some simple code that exposes the problem. Thanks!

**Comment by chenghuige** [comment]
@lukaszkaiser  adgrad problem also find out reason.  I think it is my code problem, I should use addtional scope and set variable reused in that scope, before using tf.contrib.layers.optimize_loss.
Though tf v0.12 can work but I think tv v1.0's behavior is ok not a bug also. Thanks lukaszkaiser and jart!

Below code can reproduce this, it works with tf v0.12 fail v1.0 without using addtional scope for train and evaluate before layers.optimize.
https://github.com/chenghuige/tensorflow-example/blob/master/tests/adagrad_optimize_scope.py

**Comment by jart** [comment]
@chenghuige Thanks for the clarification. Do you think that there's anything actionable on the part of TensorFlow that we could do better?

**Comment by chenghuige** [comment]
@jart Tensorflow is such a greate framework! I can always get help quickly whenever facing problem:)
There are adequate documentations, but still the more the better.
For me currently focusing on dynamic seq2seq, as I have filed in another bug, I find it's hard to read seq2seq code. 
It would be great to see more example code showing the usage of context state and dynamic seq2seq with beam search. 
Also might need more documents on TensorArray.

**Comment by ebrevdo** [comment]
We're working on a cleaner seq2seq API now. Hope to release within the next
month.

**Comment by chenghuige** [comment]
@ebrevdo cool, looking forward to new seq2seq.
