### ISSUE TITLE
Does anyone know which version of ROCM is used to build the tensorflow-rocm ?

### ISSUE THREAD

**Issue by jaslip** [tensorflow/tensorflow#67620]
In this Pypi page, there is no ROCM version information. I need to confirm whether ROCM 6 is used.
https://pypi.org/project/tensorflow-rocm/2.14.0.600/#files
Can someone help? Thank you very much.

**Comment by sushreebarsa** [comment]
@jaslip ROCm 6.0.2: This version is used to build tensorflow-rocm version 2.14.0.602 
ROCm 6.0.0 (or later): This version is used to build tensorflow-rocm versions 2.13.1.602 and later 
It's important to note that not all tensorflow-rocm versions are compatible with all ROCm6 versions.

Thank you!
