### ISSUE TITLE
Android: build shared library using Makefile with r0.12, migrating from r0.11

### ISSUE THREAD

**Issue by oorlov** [tensorflow/tensorflow#6763]
I've been successfully using r0.11 Makefile with couple of additions (see below) to build shared library for Android. 
Now trying to migrate to r0.12 with same Makefile modifications but getting a SIGSEGVs at model initialization.

I followed [contrib/makefile/README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/README.md). I've checked https://github.com/tensorflow/tensorflow/issues/6166 as well.

Comparing r0.12 changes with r0.11 I've noticed some things:
- both libtensorflow-core.a and lib.so decreased in size from ~200MB and ~100MB in r0.11 to ~40MB and ~40MB in r0.12
- trying to revert optimization from -O2 back to -O0 causing compilation error in downloads/gemmlowp/
```shell
/Users/oleg/opt/ndk-bundle-r12e/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-g++ --std=c++11 -DIS_SLIM_BUILD -fno-exceptions -DNDEBUG -DNOTFDBG -O0 --sysroot /Users/oleg/opt/ndk-bundle-r12e/platforms/android-14/arch-arm -Wno-narrowing -march=armv7-a -mfloat-abi=softfp -mfpu=neon -fPIE -fPIC -MT /Users/oleg/tensorflow/tensorflow/contrib/makefile/gen/obj/tensorflow/core/kernels/meta_support.o -MMD -MP -MF /Users/oleg/tensorflow/tensorflow/contrib/makefile/gen/dep//tensorflow/core/kernels/meta_support.Td -I/Users/oleg/opt/ndk-bundle-r12e/sources/android/support/include -I/Users/oleg/opt/ndk-bundle-r12e/sources/cxx-stl/gnu-libstdc++/4.9/include -I/Users/oleg/opt/ndk-bundle-r12e/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include -I. -I/Users/oleg/tensorflow/tensorflow/contrib/makefile/downloads/ -I/Users/oleg/tensorflow/tensorflow/contrib/makefile/downloads/eigen -I/Users/oleg/tensorflow/tensorflow/contrib/makefile/downloads/gemmlowp -I/Users/oleg/tensorflow/tensorflow/contrib/makefile/gen/protobuf/include -I/Users/oleg/tensorflow/tensorflow/contrib/makefile/gen/proto/ -I/Users/oleg/tensorflow/tensorflow/contrib/makefile/gen/proto_text/ -c tensorflow/core/kernels/meta_support.cc -o /Users/oleg/tensorflow/tensorflow/contrib/makefile/gen/obj/tensorflow/core/kernels/meta_support.o
In file included from /Users/oleg/tensorflow/tensorflow/contrib/makefile/downloads/gemmlowp/meta/transform_kernels.h:239:0,
                 from ./tensorflow/core/kernels/meta_support.h:23,
                 from tensorflow/core/kernels/meta_support.cc:18:
/Users/oleg/tensorflow/tensorflow/contrib/makefile/downloads/gemmlowp/meta/transform_kernels_arm_32.h: In static member function 'static void gemmlowp::meta::Transform1DKernel<InType, OutType, gemmlowp::meta::BiasAdd<Type>, kernel_size, leftovers>::Transform(const InType*, const gemmlowp::meta::BiasAdd<Type>&, OutType*) [with InType = unsigned char; OutType = int; int kernel_size = 16; int leftovers = 0; Type = unsigned char]':
/Users/oleg/tensorflow/tensorflow/contrib/makefile/downloads/gemmlowp/meta/transform_kernels_arm_32.h:5605:24: error: 'asm' operand has impossible constraints
         "cc", "memory");
                        ^
make: *** [/Users/oleg/tensorflow/tensorflow/contrib/makefile/gen/obj/tensorflow/core/kernels/meta_support.o] Error 1
```
- gemmlowp was downloaded but never used for Android in headers search path (-I) in r0.11
- reverting new flags -mfloat-abi=softfp  and -mfpu=neon by commenting them out allows to build libtensorflow-core.a and libtensorflow.so artifacts with ~100MB in size using -O0

After applying  all changes from above I'm still getting SIGSEGVs. What else could I try? Looks like I'm missing something. I might be wrong thinking Makefile is a good way to go, but it flexible and allows to add required kernels/*_op.cc straight to tf_op_files.txt. What is a right way to build lib.so for Android?

### Makefile additions 
```Makefile
ifeq ($(TARGET),ANDROID)
...
CXXFLAGS +=\
...
-fPIC

SO_NAME  := libtensorflow.so
SO_PATH  := $(LIBDIR)$(SO_NAME)

$(SO_PATH): $(LIB_OBJS)
	@echo "------->>>>>>>>>  SO PATH started ------>>>>>>>>>"
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $(INCLUDES) \
	-shared -rdynamic -o $(SO_PATH)  $(LIB_OBJS) \
	$(LIBFLAGS) $(LDFLAGS) $(LIBS)
```

### Environment:
OS X: 10.12
NDK: r12e
CUDA: not installed
SHA-1
r0.12 `4d924e796368163eff11a8151e8505715345f58d`
r0.11 `e39376b6e9c9541e1bd8f15333b6994046a84d16`
................
Build label: 0.4.1-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 30 13:26:35 2016 (1480512395)
Build timestamp: 1480512395
Build timestamp as int: 1480512395

**Comment by andrewharp** [comment]
Can you describe more about your device and the sigsegv you're seeing?

Maybe not related to your issue, but Ndk 12b is suggested (12e does not exist afaik), as well as Bazel 0.4.2

Are you building with build_all_android.sh? That is the preferred way to build using the Makefile system.

Bazel is also a fully supported build method, e.g.:
```
bazel build -c opt tensorflow/core:android_tensorflow_lib \
 --crosstool_top=//external:android/crosstool \
 --cpu=armeabi-v7a \
 --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
```

**Comment by jart** [comment]
There's a lot to digest here. @petewarden might want to be aware of all this commentary concerning the makefile build.

@oorlov you might want to file an issue at https://github.com/google/gemmlowp asking them why it doesn't compile with -O0.

**Comment by oorlov** [comment]
@andrewharp you are right, my NDK is Pkg.Revision = 12.1.2977051 that is r12b. Misspelled a folder inspired by ndk-r10e.

Another thing I've realized is that after all changes (disabled neon, and OPTFLAGS := -O0) I'm getting ~110MB libtensorflow.so artifact that **DOES** work in the same way as r0.11

Looks like I messed up some things yesterday like android version or ndk version were different between libprotobuf and libtensorflow.so
So to prevent this mess I've thoroughly built and tested artifacts with different environments:

...  | neon  |  OPTFLAGS  | Android | Device                | Result       | Log
--- | -----|--------------|---------|-----------------|-----------|---
1    | On   | -O2                | 21           | Galaxy S7, 6.0.1 | SIGSEGV | [neon.o2.android21.txt](https://github.com/tensorflow/tensorflow/files/698359/neon.o2.android21.txt) 
2    | On   | -O2                | 21           | Pixel, 7.1.1         | SIGSEGV |   [neon.o2.android21.txt](https://github.com/tensorflow/tensorflow/files/698359/neon.o2.android21.txt) 
3    | On   | -O2                | 21           | Galaxy Note 3, 5.0.1 | SIGSEGV |  [neon.o2.android21.txt](https://github.com/tensorflow/tensorflow/files/698359/neon.o2.android21.txt) 
4    | OFF   | -O2                | 21           | Galaxy S7, 6.0.1 | SIGSEGV |  [no-neon.o2.android21.txt](https://github.com/tensorflow/tensorflow/files/698367/no-neon.o2.android21.txt)
5   | OFF   | -O2                | 21           | Pixel, 7.1.1 | SIGSEGV |  [no-neon.o2.android21.txt](https://github.com/tensorflow/tensorflow/files/698367/no-neon.o2.android21.txt)
6    | OFF   | -O2                | 21           | Galaxy Note 3, 5.0.1 | SIGSEGV |  [no-neon.o2.android21.txt](https://github.com/tensorflow/tensorflow/files/698367/no-neon.o2.android21.txt)
7    | OFF   | -O0                | 21           | Galaxy S7, 6.0.1 | Ok |  [no-neon.o0.android21.txt](https://github.com/tensorflow/tensorflow/files/698368/no-neon.o0.android21.txt)
8   | OFF   | -O0                | 21           | Pixel, 7.1.1 | Ok |  [no-neon.o0.android21.txt](https://github.com/tensorflow/tensorflow/files/698368/no-neon.o0.android21.txt)
9    | OFF   | -O0                | 21           | Galaxy Note 3, 5.0.1 | Ok |  [no-neon.o0.android21.txt](https://github.com/tensorflow/tensorflow/files/698368/no-neon.o0.android21.txt)
10    | On   | -O0                | 21           | Any | Compilation Error |  [neon.o2.android21.txt](https://github.com/tensorflow/tensorflow/files/698384/neon.o2.android21.txt)

Seems like -O2 causes problems, not neon flag, but I cannot confirm it due to compilation error.

I'm also getting Ok builds when Android version is set to android-14. I run them successfully on Moto X v1, Android 4.4.4 and Samsung/GreatCall Touch3, Android 4.3 [no-neon.o0.android14.txt](https://github.com/tensorflow/tensorflow/files/698439/no-neon.o0.android14.txt)

@jart Thank you for suggestion, though I'm hesitating here because the only scenario I have in my hands is a tensorflow build that might be affected by system misconfiguration or my misunderstanding. If it is clear that on my side everything is correct issue will be filed.

**Comment by oorlov** [comment]
Checked Android build with Bazel, followed these instuctions:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/android

Bazel build script for libtensorflow_inference.so generates different compilation error:

```
ERROR: /Users/alivecor/tensorflow-bazel/tensorflow/contrib/android/BUILD:71:1: Linking of rule '//tensorflow/contrib/android:libtensorflow_inference.so' failed: sandbox-exec failed: error executing command /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_alivecor/b205624d5e3f9e00e1da3a96f45ffc17/bazel-sandbox/5d59ce41-1e8b-441a-8550-c21d6358aaa7-749/sandbox.sb ... (remaining 32 argument(s) skipped).
tensorflow/core/ops/math_ops.cc:1822: error: undefined reference to 'ceil'
external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/cmath:185: error: undefined reference to 'ceilf'
tensorflow/core/ops/nn_ops.cc:64: error: undefined reference to 'floorf'
external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/include/cmath:185: error: undefined reference to 'ceilf'
```
Log: [bazel-android-inference.txt](https://github.com/tensorflow/tensorflow/files/700122/bazel-android-inference.txt), Verbose: [bazel-android-inference-verbose.txt](https://github.com/tensorflow/tensorflow/files/700219/bazel-android-inference-verbose.txt)

Now I'm confused. It happens on more than one machine, so I don't believe they share same misconfiguration problems. 
What should be my next step? Should I stay on Makefile with neon and optimization switched off?Wouldn't it affect model execution? Or need to do extra steps for Bazel build?


Machine 1, (clean, OSX reinstalled): 
OSX: 10.11.6
NDK: r12b
CUDA: not installed
BAZEL:
Build label: 0.4.3-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 22 15:20:22 2016 (1482420022)
Build timestamp: 1482420022
Build timestamp as int: 1482420022

Machine 2:
OSX 10.12
NDK: r12b
CUDA: not installed
BAZEL:
Build label: 0.4.1-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Nov 30 13:26:35 2016 (1480512395)
Build timestamp: 1480512395
Build timestamp as int: 1480512395

**Comment by andrewharp** [comment]
@oorlov //tensorflow/contrib/android:libtensorflow_inference.so was missing several link targets in 0.12 that add the necessary definitions. This has since been fixed, but if you want to patch 0.12 just add:

```
        "-llog",
        "-lm",
```

to the linkopts section and it should build.

**Comment by jart** [comment]
@oorlov does the comment above address your issue?

@andrewharp do you think there's anything actionable here on the part of TensorFlow?

**Comment by oorlov** [comment]
Hey guys! 
Bazel build works pretty well for me and I get both x86 and armv7 libraries for android-14 and it seems working well on my devices. Nothing is changed for Makefile, so I will stick to Bazel build for now.

Thank you for assistance!

**Comment by andrewharp** [comment]
@oorlov Great! 

Was looking at the actual segfault you had (cannot locate symbol "rand" referenced by libtensorflow_android.so) and it seems to be related to this: http://stackoverflow.com/questions/27091001/how-to-use-mkfifo-using-androids-ndk

Suggestions there were to lower the Android native API and see if the problem is resolved, or attempt to add the " -fPIE -pie" as suggested. However as we don't see this problem in our Makefile build otherwise, there may be some other difference with your local addition.

@jart I think the original Makefile problem was due to the new lib he added, and the Bazel issue has already been fixed, so there's nothing to be done on the TF side of things.

**Comment by oorlov** [comment]
@andrewharp

It is a different SIGSEGV. It seems presence of Motorola 4.4.4 device in SIGSEGV logs are misleading. If you check SIGSEGV related logs you will find all of them about binary compiled for android-21 when MotoX device is android-14. 
So when you run such binary on Android 4.4.4 (android-19) device it dies with `cannot locate symbol "rand" referenced by libtensorflow_android.so` and it is expected.

Though if you run it on Android 5.0+ device it is supposed to work properly (S7, Pixel). And it does for no-neon.O0 binaries (While MotoX 4.4.4 still dies with the same error, see [no-neon.o2.android21.txt](https://github.com/tensorflow/tensorflow/files/705254/no-neon.o2.android21.txt). Yes, compiling binary for android-14, no-neon, -O0 does a fix for MotoX 4.4.4. 

The SIGSEGV I'm reporting is still there for -O2 builds compiled for both android-21 and android-14 binaries.

**Comment by andrewharp** [comment]
@oorlov Sorry, which log shows the other SIGSEGV? I only see ones that refer to a missing definition for "rand" (including both the failing Pixel logs).

Googling this led me to http://stackoverflow.com/questions/28504875/android-ndk-cannot-load-libc-shared-so-gets-cannot-locate-symbol-rand-refe, which in turn points to the previous link I posted.

**Comment by oorlov** [comment]
@andrewharp  for example [neon.o2.android21.txt](https://github.com/tensorflow/tensorflow/files/698359/neon.o2.android21.txt)
This is about android-21 devices Galaxy S7, 6.0.1, Pixel, 7.1.1 Galaxy Note 3, 5.0.1, so "rand" error is not there for them. MotoX there is just by a mistake.

**Comment by andrewharp** [comment]
Thanks, I see now -- I'd just been scrolling to the end and then scanning for the start of the error out of habit.

Sigsev 11s typically happen due to invalid memory access. Hard to say what is actually going wrong without seeing code and debugging, but it could be a bug in the code and not a necessarily a build flag issue. Certain builds can be arbitrarily more picky about enforcing valid memory access depending on how objects get laid out or how the codepaths access the memory (e.g. with or without NEON), so it's possible that there's a hidden problem even in the "successful" variants.

Not clear to me that the issue lies in TF, though, so unless there is a minimal reproducible example you can share that narrows it down to TF, I don't think this is something we can support.
