### ISSUE TITLE
Tensorflow v0.12 tf.nn has no module rnn_cell

### ISSUE THREAD

**Issue by ems7** [tensorflow/tensorflow#6765]
`Import tensorflow as tf`

`a = tf.nn.rnn_cell.LSTMCell(100)`

results in:

> AttributeError: 'module' object has no attribute 'rnn_cell'

Tensorflow 0.12

ls -l 'cuda':
-rw-r--r-- 1 root root 189170 Jan  9 10:49 /usr/local/cuda/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Jan  9 10:49 /usr/local/cuda/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Jan  9 10:49 /usr/local/cuda/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 Jan  9 10:49 /usr/local/cuda/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020 Jan  9 10:49 /usr/local/cuda/lib/libcudart_static.a

Cuda 7.5
Cudnn 5

git rev-parse HEAD:
ec7929b878926c39255254e9aea992f0bc65aa68

Bazel Version:
Build label: 0.4.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 22 12:31:25 2016 (1482409885)
Build timestamp: 1482409885
Build timestamp as int: 1482409885

**Comment by yaroslavvb** [comment]
It's been moved to contrib
