### ISSUE TITLE
Add "Hide empty panes" option to TensorBoard

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tensorflow#6768]
When filtering runs, empty panes show up if a hidden run has a summary in a scope that the visible runs don't have. This makes TensorBoard very messy when comparing different machine learning models with different variable scopes, and so on. Could an option to hide empty panes be added?

Example (note the empty LSTM scope):
![image](https://cloud.githubusercontent.com/assets/1595907/21809055/56b42e02-d746-11e6-9356-37ccd16cee4c.png)

**Comment by jart** [comment]
@dandelionmane This feature request sounds pretty reasonable. Is there any reason why we would want to display empty panes at all?

**Comment by carlthome** [comment]
@dandelionmane, thoughts on this? It would be a pretty easy fix, I'd wager.

**Comment by jonasrauber** [comment]
The same should apply to panes that contain only empty plots.

**Comment by hholst80** [comment]
Why not hide empty plots all together?

**Comment by dandelionmane** [comment]
Migrated this to the TensorBoard repo.
