### ISSUE TITLE
Tensorflow lite in Android App

### ISSUE THREAD

**Issue by LiangZhaoSRA** [tensorflow/tensorflow#67699]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.3

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Mobile device

Galaxy S24

### Python version

3.8

### Current behavior?

Got the following error when try to run a tflite model on GPU:
<img width="483" alt="model" src="https://github.com/tensorflow/tensorflow/assets/169956268/14c52c47-cd75-4658-a6ab-3d78ba21b92d">
W/System.err(30515): Ignoring failed delegate application: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.

When I visualize the model using Netron, there is no dynamic-sized tensor (see attached file).
<img width="483" alt="model" src="https://github.com/tensorflow/tensorflow/assets/169956268/e6b3c023-db12-4002-af92-951b412742f9">

### Standalone code to reproduce the issue

```shell
W/System.err(30515): Ignoring failed delegate application: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
```

### Relevant log output

```shell
W/System.err(30515): Ignoring failed delegate application: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
```

**Comment by sawantkumar** [comment]
hi @LiangZhaoSRA ,

If possible , can you share me the .tflite file please

**Comment by LiangZhaoSRA** [comment]
@sawantkumar Attaches is the tflite file. Thanks.
[model.zip](https://github.com/tensorflow/tensorflow/files/15379814/model.zip)

**Comment by sawantkumar** [comment]
Hi @LiangZhaoSRA ,

I inspected your model using custom code and I found out that your model has dynamic sized tensors . If possible can you provide me the model conversion code. 

```
Dynamic tensors found:
Name: Where_101;StatefulPartitionedCall/Where_101, Shape: [0 1]
Name: Squeeze_83;StatefulPartitionedCall/Squeeze_83, Shape: [0]
Name: GatherV2_83;StatefulPartitionedCall/GatherV2_83;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_78;StatefulPartitionedCall/GatherV2_78;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_79;StatefulPartitionedCall/GatherV2_79;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_71;StatefulPartitionedCall/GatherV2_71;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_66;StatefulPartitionedCall/GatherV2_66;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_67;StatefulPartitionedCall/GatherV2_67;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_59;StatefulPartitionedCall/GatherV2_59;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_54;StatefulPartitionedCall/GatherV2_54;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_55;StatefulPartitionedCall/GatherV2_55;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_12;StatefulPartitionedCall/GatherV2_12;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_13;StatefulPartitionedCall/GatherV2_13;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_26;StatefulPartitionedCall/GatherV2_26;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_27;StatefulPartitionedCall/GatherV2_27;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_40;StatefulPartitionedCall/GatherV2_40;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_41;StatefulPartitionedCall/GatherV2_41;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_5;StatefulPartitionedCall/GatherV2_5;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2;StatefulPartitionedCall/GatherV2;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_1;StatefulPartitionedCall/GatherV2_1;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_47;StatefulPartitionedCall/GatherV2_47;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_42;StatefulPartitionedCall/GatherV2_42;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
Name: GatherV2_43;StatefulPartitionedCall/GatherV2_43;GatherV2_99/axis;StatefulPartitionedCall/GatherV2_99/axis, Shape: [0]
```

**Comment by LiangZhaoSRA** [comment]
Hi Sawant,
I converted the torch model to tflite via torch to onnx, onnx to tensorflow and tensorflow to tflite. Attached are the scripts for model conversion. Please let me know if you have any questions. Thanks.
[tr2lite.zip](https://github.com/tensorflow/tensorflow/files/15488465/tr2lite.zip)

**Comment by LiangZhaoSRA** [comment]
Hi Sawant,

I have shared the scripts for model conversion two weeks ago. Please let me know if you have any questions and progress. Thanks.

Liang

**Comment by sawantkumar** [comment]
Hi @LiangZhaoSRA ,

If you are able to access a linux system you may be able to resolve your issue by using [AI-Edge-Torch](https://github.com/google-ai-edge/ai-edge-torch), you can find more information here: [googleblog](https://developers.googleblog.com/en/ai-edge-torch-high-performance-inference-of-pytorch-models-on-mobile-devices/).

You can directly convert your pytorch model to a tflite model.I have actually created a sample script below :

```py
import torch
import torch.nn as nn
import torch.nn.functional as F
import ai_edge_torch

class PadLayer(nn.Module):
    def __init__(self):
        super(PadLayer, self).__init__()
        self.paddings = (0, 0, 1, 1)  # Padding for the second and third dimensions

    def forward(self, x):
        return F.pad(x, pad=self.paddings, mode="constant", value=-1)

class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.conv = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=(1, 7), padding='same')
        self.pad = PadLayer()
        self.mpool = nn.MaxPool2d(kernel_size=(1, 3), stride=(1, 2), padding=0)

    def forward(self, x):
        x = self.conv(x)
        x = self.pad(x)
        x = self.mpool(x)
        return x

model = SimpleModel()

example_input = torch.randn(1, 1, 32, 25)

edge_model = ai_edge_torch.convert(model.eval(), (example_input,))

# Export the model to TFLite format
edge_model.export('simple_model_with_pad.tflite')
```

If you want to, you can actually try visualizing the result in [model-explorer](https://github.com/google-ai-edge/model-explorer) as well.

**Comment by LiangZhaoSRA** [comment]
Hi Sawant,

Thanks for suggesting using ai-edge-torch to convert torch model to tflite directly. I was able to install ai-edge-torch and using it to convert my torch model to tflite successfully. However, when I ran the android app on S24, it raised the same error as before when enable GPU delegate:
Ignoring failed delegate application: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.

Please let me know what else we can try.
Thanks,

Liang

**Comment by LiangZhaoSRA** [comment]
Hi Sawant,

I have tried the ai-edge-torch as you suggested and got the same error as before due to dynamic-sized tensors. Please let me know if there are any other options.
Thanks,

Liang

**Comment by sawantkumar** [comment]
Hi @LiangZhaoSRA ,

I ran your model using tflite benchmark , it is giving the below output which tells that your model contains 'select tensorflow ops'  . Can you add 'org.tensorflow:tensorflow-lite-select-tf-ops' to your dependency and rerun the model again and let me know if it runs on GPU.

```
07-22 14:19:01.506 25918 25918 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/student_woc.tflite   --use_gpu=true   --dry_run=true   --print_preinvoke_state=true   --num_runs=100
07-22 14:19:01.532 25918 25918 I tflite  : Log parameter values verbosely: [0]
07-22 14:19:01.533 25918 25918 I tflite  : Min num runs: [100]
07-22 14:19:01.533 25918 25918 I tflite  : Run w/o invoking kernels: [1]
07-22 14:19:01.533 25918 25918 I tflite  : Graph: [/data/local/tmp/student_woc.tflite]
07-22 14:19:01.533 25918 25918 I tflite  : Signature to run: []
07-22 14:19:01.533 25918 25918 I tflite  : Print pre-invoke interpreter state: [1]
07-22 14:19:01.533 25918 25918 I tflite  : Use gpu: [1]
07-22 14:19:01.559 25918 25918 I tflite  : Loaded model /data/local/tmp/student_woc.tflite
07-22 14:19:01.571 25918 25918 I tflite  : Initialized TensorFlow Lite runtime.
07-22 14:19:01.584 25918 25918 I tflite  : Created TensorFlow Lite delegate for GPU.
07-22 14:19:01.584 25918 25918 I tflite  : GPU delegate created.
07-22 14:19:01.584 25918 25918 E tflite  : Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select
07-22 14:19:01.584 25918 25918 E tflite  : Node number 22 (FlexAddV2) failed to prepare.
07-22 14:19:01.584 25918 25918 E tflite  : Failed to apply GPU delegate.
```

**Comment by LiangZhaoSRA** [comment]
Hi Sawant,

Thanks for the suggestion. After I added 'org.tensorflow:tensorflow-lite-select-tf-ops' to  dependency and rerun the model, the error "java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors." is gone. However, the inference time on GPU and CPU are similar around 7sec. I wonder how to check if it's really running on GPU. Thanks.

**Comment by sawantkumar** [comment]
Hi @LiangZhaoSRA ,

You can check the logs from the android logcat to see how the model is being partitioned and how many parts of it are being delegated to GPU and CPU. Let me know if you have any problem understanding the logs .

**Comment by LiangZhaoSRA** [comment]
I checked the log and here is how the model is being partitioned:
TfLiteFlexDelegate delegate: 76 nodes delegated out of 5623 nodes with 51 partitions.

**Comment by sawantkumar** [comment]
Hi @LiangZhaoSRA ,

The log indicates that out of the 5623 nodes in your TensorFlow Lite model, 76 nodes are using the Flex Delegate for execution, and these nodes are grouped into 51 partitions. This means that the majority of your model's operations are natively supported by TensorFlow Lite, and only a small subset requires the extended functionality provided by the Flex Delegate. Let me know if this answers your question.
