### ISSUE TITLE
Tensorboard: missing image/broken link

### ISSUE THREAD

**Issue by jbeda** [tensorflow/tensorflow#677]
When running Tensorboard (v0.6.0) on the output from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py I get a broken link symbol and the following in the logs:

```
192.168.99.1 - - [04/Jan/2016 16:58:45] code 404, message Not Found
192.168.99.1 - - [04/Jan/2016 16:58:45] "GET /lib/svg/summary-icon.svg HTTP/1.1" 404 -
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/lib/svg/summary-icon.svg' on path /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/lib/svg/summary-icon.svg
```

**Comment by jbeda** [comment]
I should note that this is in the "Graph" view.

**Comment by danmane** [comment]
@dsmilkov

**Comment by Dringite** [comment]
I have the same issue, nothing whatsoever appears to load into tensorboard, no images, no CSS, no summaries of anything.

**Comment by dsmilkov** [comment]
Hi guys,

This has been fixed, but after the 0.6.0 release. You can either wait for the 0.7.0 which will be released soon, or rebuild tensorboard yourself following the instructions at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/README.md#tensorboard-development-instructions

Hope this helps!

**Comment by Dringite** [comment]
I built mine 2 days ago.

**Comment by dsmilkov** [comment]
@Dringite It seems for you, the whole TensorBoard is not working, not just a broken summary icon. For that, see issue #1076 . There is a fix pushed to the release branch but if you want it sooner, take this commit: https://github.com/tensorflow/tensorflow/commit/68e8b0f1e02f1e0e10f4fdd689ede80f973e2756

**Comment by dsmilkov** [comment]
@jbeda To fix the summary-icon, you need to rebuild tensorboard using bazel and run it:
```
bazel build tensorflow/tensorboard
bazel-bin/tensorflow/tensorboard/tensorboard --logdir path/to/log/dir
```

For more information about installing and building TensorFlow and TensorBoard from source, see https://www.tensorflow.org/versions/v0.6.0/get_started/os_setup.html#source
