### ISSUE TITLE
TensorFlowLiteSelectTfOps - Compile error

### ISSUE THREAD

**Issue by thereallee** [tensorflow/tensorflow#67748]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

	pod 'TensorFlowLiteSwift'   # or 'TensorFlowLiteObjC' 	pod 'TensorFlowLiteSelectTfOps', '~> 0.0.1-nightly'

### Custom code

Yes

### OS platform and distribution

iOS 16.2

### Mobile device

iOS

### Current behavior?

Podfile:

	pod 'TensorFlowLiteSwift'   # or 'TensorFlowLiteObjC'
	pod 'TensorFlowLiteSelectTfOps', '~> 0.0.1-nightly'

After fixing the '-force_load' issue, I now see this compiller error:

> Inferred submodules require a module with an umbrella

<img width="408" alt="Screenshot 2024-05-16 at 9 34 32 AM" src="https://github.com/tensorflow/tensorflow/assets/98909739/9bd549e3-8de2-481c-bc15-e7fa0233751a">

### Standalone code to reproduce the issue

```shell
Use the podfile as indicated above.

Disable user script sandboxing

Fix the force_update script bug

In a Swift file, have these two imports:

import TensorFlowLite
import TensorFlowLiteSelectTfOps


Try to build.

See the error on the "import TensorFlowLiteSelectTfOps" line

> Inferred submodules require a module with an umbrella
```

**Comment by pkgoogle** [comment]
Hi @thereallee, are you using an emulator or a real phone? The steps to integrate Select ops with iOS are different depending on that, so I want to understand your situation.

**Comment by thereallee** [comment]
Hi -  I see essentially the same error when building for device and simulator.  See attached.

Simulator build:

![Simulator_—_module_modulemap](https://github.com/tensorflow/tensorflow/assets/98909739/aa445363-5b55-4ed1-badc-b53f425316dd)


Device build:


![Device_—_module_modulemap](https://github.com/tensorflow/tensorflow/assets/98909739/9a4f978f-fe6b-48f5-9e38-3f420b2273b5)

**Comment by pkgoogle** [comment]
Hi @thereallee, I'm not sure if the Pod build is the right way for iOS emulator so let's stick with the Device build for now. How did you fix the "-force_load" issue? Have you tried getting it to work w/ the image Classification app like the bottom of this section suggested? https://www.tensorflow.org/lite/guide/ops_select#ios Thanks for your help. If you can zip and share your xcode project, that'll be easier to check. (Perhaps just a copy of the classification app with your attempted changes)

**Comment by thereallee** [comment]
I'll check out the classification app in the next few days and report back.

**Comment by NguyenDanVP** [comment]
The error still persists. The solution you provided is completely ineffective. How to fix it.
