### ISSUE TITLE
Issue when using binary tensorflow shared library

### ISSUE THREAD

**Issue by maystroh** [tensorflow/tensorflow#6775]
I generated a shared library of tensorflow using the following command:

> bazel build -c opt --config=cuda //tensorflow/cc:libtensorflow.so

it was generated without any error and it's located in /usr/local/lib/libtensorflow.so.

BUT, when I add its dependency to my CMake file: 

> set(XXXX_DEPENDENCIES ${XXXX_DEPENDENCIES} ${Tensorflow_LIBRARIES} PARENT_SCOPE)

and I try to build my project I got the following:
```
:-1: warning: libcudart.so.7.5, needed by /usr/local/lib/libtensorflow.so, not found (try using -rpath or -rpath-link)
/usr/local/lib/libtensorflow.so:-1: error: undefined reference to `cudaMemcpyAsync'
/usr/local/lib/libtensorflow.so:-1: error: undefined reference to `cudaConfigureCall'
/usr/local/lib/libtensorflow.so:-1: error: undefined reference to `cudaGetDeviceCount'
/usr/local/lib/libtensorflow.so:-1: error: undefined reference to `__cudaUnregisterFatBinary'
/usr/local/lib/libtensorflow.so:-1: error: undefined reference to `cudaStreamQuery'
/usr/local/lib/libtensorflow.so:-1: error: undefined reference to `cudaStreamAddCallback'
/usr/local/lib/libtensorflow.so:-1: error: undefined reference to `cudaSetupArgument'
/usr/local/lib/libtensorflow.so:-1: error: undefined reference to `cudaGetDeviceProperties'
/usr/local/lib/libtensorflow.so:-1: error: undefined reference to `cudaGetErrorString'
/usr/local/lib/libtensorflow.so:-1: error: undefined reference to `__cudaRegisterFunction'
/usr/local/lib/libtensorflow.so:-1: error: undefined reference to `__cudaRegisterFatBinary'
/usr/local/lib/libtensorflow.so:-1: error: undefined reference to `cudaLaunch'
```

**Comment by yaroslavvb** [comment]
This may be better addressed at stackoverflow (here's a related issue, answered without config=cuda) -- http://stackoverflow.com/questions/38256180/how-to-make-shared-libraries-with-bazel-at-tensorflow

**Comment by yaroslavvb** [comment]
I would guess this has to do with CUDA libraries not being found by your cmake procedure

**Comment by jart** [comment]
I concur. If you have reason to suspect this might be a bug in TensorFlow, please let us know, and I'll re-open this issue.
