### ISSUE TITLE
Siamese Inception model

### ISSUE THREAD

**Issue by ElchinValiyev** [tensorflow/tensorflow#6776]
Already tried on StackOverflow - no success.
Please, help.

How to implement such network in TensorFlow?
```
    (input_1)    (input_2)
          \         /
(Inception(GoogLeNet) without softmax layer)
          /         \
    (output_1)    (output_2)
             \   / 
        (Contrastive loss) 
```

I need to reuse weights in Inception for transfer learning.

**Comment by yaroslavvb** [comment]
This list is for feature requests/bugs in tensorflow. Same people also monitor stackoverflow
