### ISSUE TITLE
Parameter to MergeFrom() must be instance of same class: expected TensorProto got Variable. for field Value.tensor

### ISSUE THREAD

**Issue by chaitanya2692** [tensorflow/tensorflow#6778]
I am trying to save variables through checkpoints to introduce fault tolerance to my program. The following is my configuration:-

```
ChiefSessionCreator = tf.train.ChiefSessionCreator(scaffold=None, master='grpc://localhost:2222', config=None, checkpoint_dir='/home/chaitanya/tensorflow/codes/checkpoints')
summary_hook = tf.train.SummarySaverHook(save_steps=None, save_secs=10, output_dir='/home/chaitanya/tensorflow/codes/savepoints', summary_writer=None, scaffold=None, summary_op=tf.Summary(tf.Summary.Value(tensor=y)))
saver = tf.train.Saver([tf.Variable(y)])
saver_hook = tf.train.CheckpointSaverHook(checkpoint_dir='/home/chaitanya/tensorflow/codes/checkpoints', save_secs=10, save_steps=None, saver=saver, checkpoint_basename='model.ckpt', scaffold=None)
```

In this, the [CheckpointSaveHook](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard2/tf.train.CheckpointSaverHook.md#tftraincheckpointsaverhook__init__checkpoint_dir-save_secsnone-save_stepsnone-savernone-checkpoint_basenamemodelckpt-scaffoldnone-listenersnone-checkpointsaverhookinit) saves tf.Variable in saver and [SummarySaverHook](https://www.tensorflow.org/versions/master/api_docs/python/train/training_utilities?authuser=2#SummarySaverHook) takes a tensor input in summary_op. The error I get is:-

```
Traceback (most recent call last):
  File "add_1.py", line 35, in <module>
    summary_hook = tf.train.SummarySaverHook(save_steps=None, save_secs=10, output_dir='/tensorflow/savepoints', summary_writer=None, scaffold=None, summary_op=tf.Summary(tf.Summary.Value(tensor=y)))
TypeError: Parameter to MergeFrom() must be instance of same class: expected TensorProto got Tensor. for field Value.tensor
```

How do I rectify this issue?

**Comment by jart** [comment]
Thanks for reaching out. Is that the complete backtrace?

**Comment by chaitanya2692** [comment]
This is the complete error I get:-
```
WARNING:tensorflow:From add_1.py:25 in <module>.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
Traceback (most recent call last):
  File "add_1.py", line 34, in <module>
    summary_hook = tf.train.SummarySaverHook(save_steps=None, save_secs=10, output_dir='/home/chaitanya/tensorflow/codes/savepoints', summary_writer=None, scaffold=None, summary_op=tf.Summary(tf.Summary.Value(tensor=y)))
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 532, in init
    _ReraiseTypeErrorWithFieldName(message_descriptor.name, field_name)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 460, in _ReraiseTypeErrorWithFieldName
    six.reraise(type(exc), exc, sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 530, in init
    copy.MergeFrom(new_val)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 1233, in MergeFrom
    "expected %s got %s." % (cls.__name__, type(msg).__name__))
TypeError: Parameter to MergeFrom() must be instance of same class: expected TensorProto got Tensor. for field Value.tensor
```

**Comment by jart** [comment]
Maybe what you want is `tf.Summary(value=[tf.Summary.Value(...)])`.

In the future please direct questions like these to [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). We try to keep this issue tracker limited to bugs and feature requests.

**Comment by chaitanya2692** [comment]
I tired your solution and it gives the same error. Below is the link to my Stackoverflow query:-

[https://stackoverflow.com/questions/41539934/tensorflow-parameter-to-mergefrom-must-be-instance-of-same-class-expected-ten](https://stackoverflow.com/questions/41539934/tensorflow-parameter-to-mergefrom-must-be-instance-of-same-class-expected-ten)

**Comment by jart** [comment]
At second glance, you're most likely not going to get a response to your question, because you don't indicate in your question what `y` is.

**Comment by chaitanya2692** [comment]
I have added more details to the question. Thanks for the tip.
