### ISSUE TITLE
Tensorboard: missing variable name/label

### ISSUE THREAD

**Issue by jbeda** [tensorflow/tensorflow#678]
When I run the [MNIST example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py) with tensorboard (v0.6.0) and look at the graph, the bias variable is unnamed (just `Variable`).  If I switch the order that the variables are defined, I can make it so that the weights variable is unnamed.  

It looks like perhaps the name of the last variable defined isn't captured in the graph_def?  Or perhaps tensorboard isn't picking up the name of the last variable defined?

![image](https://cloud.githubusercontent.com/assets/37310/12095395/28a32d5e-b2c3-11e5-9f26-0378f17f1cdb.png)

**Comment by danmane** [comment]
@dsmilkov

**Comment by danmane** [comment]
I believe this is fixed, see: https://www.tensorflow.org/tensorboard/index.html#graphs

**Comment by j-planet** [comment]
Hi, the bug persists on my end. I wonder if it was fixed, or was there some special settings to make the variable names show up?
