### ISSUE TITLE
Java API: How to implement a PlaceHolder

### ISSUE THREAD

**Issue by souterjk** [tensorflow/tensorflow#6781]
I've been loving experimenting with @asimshankar 's Java API, and finally got it working tonight with a model that i've trained myself based of of inception. However, I noticed his comment in his tutorial/demo java class that says:

> Since the graph is being constructed once per execution here, we can use a constant for the input image. If the graph were to be re-used for multiple input images, a placeholder would have been more appropriate.

I'd be very interested in seeing how to do this with the java API. I want to be able to optimize using the same graph for a bunch of images which would be fed into the graph in real-time, so optimization is important. Would a modification to the graph be necessary in order to use a placeholder, or is it just a different manipulation of the API? I couldn't find any references to a placeholder class or method. Any help is much appreciated.

**Comment by jart** [comment]
Thanks for reaching out. We try to keep this issue tracker limited to bugs and feature requests. We recommend posting on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) for community-driven support. Unless of course @asimshankar is interesting in weighing in on this question.

**Comment by asimshankar** [comment]
@souterjk : Such questions are better suited for Stackoverflow as @jart pointed out. That said, use of the placeholder is like any other operation. The following example shows construction of a trivial graph to add two float tensors and then repeated invocation of the single graph using placeholders:

```java
package example;

import org.tensorflow.DataType;
import org.tensorflow.Graph;
import org.tensorflow.Output;
import org.tensorflow.Session;
import org.tensorflow.Tensor;

public class Example {
  public static void main(String[] args) {
    try (Graph g = new Graph();
	 Session s = new Session(g)) {
      // Construct a graph to add two float Tensors, using placeholders.
      Output x = g.opBuilder("Placeholder", "x").setAttr("dtype", DataType.FLOAT).build().output(0);
      Output y = g.opBuilder("Placeholder", "y").setAttr("dtype", DataType.FLOAT).build().output(0);
      Output z = g.opBuilder("Add", "z").addInput(x).addInput(y).build().output(0);
      // Execute the graph multiple times, each time with a different value of x and y
      float[] X = new float[]{1,2,3};
      float[] Y = new float[]{4,5,6};
      for (int i = 0; i < X.length; i++) {
        try (Tensor tx = Tensor.create(X[i]);
	     Tensor ty = Tensor.create(Y[i]);
	     Tensor tz = s.runner().feed("x", tx).feed("y", ty).fetch("z").run().get(0)) {
	  System.out.println(X[i] + " + " + Y[i] + " = " + tz.floatValue());
	}
      }
    }
  }
}
```

**Comment by EronWright** [comment]
@asimshankar the remaining gap in defining a placeholder op is how to specify the shape of the placeholder (otherwise a tensor of any shape is allowed).   The OpBuilder can't yet articulate the `shape` attribute.
