### ISSUE TITLE
./configure has issues after copying the tensorflow codebase to a different machine

### ISSUE THREAD

**Issue by bowu** [tensorflow/tensorflow#6782]
I copied my modified tensorflow codebase to a different machine. After running ./configure, I got the following errors. How can I fix it?

ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:17:3: //external:eigen_archive: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:17:3: //external:eigen_archive: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:28:3: //external:libxsmm_archive: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:28:3: //external:libxsmm_archive: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:44:3: //external:com_googlesource_code_re2: no such attribute 'urls' in 'http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:44:3: //external:com_googlesource_code_re2: missing value for mandatory attribute 'url' in 'http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:54:3: //external:gemmlowp: no such attribute 'urls' in 'http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:54:3: //external:gemmlowp: missing value for mandatory attribute 'url' in 'http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:64:3: //external:farmhash_archive: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:64:3: //external:farmhash_archive: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:80:3: //external:highwayhash: no such attribute 'urls' in 'http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:80:3: //external:highwayhash: missing value for mandatory attribute 'url' in 'http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:90:3: //external:nasm: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:90:3: //external:nasm: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:101:3: //external:jpeg: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:101:3: //external:jpeg: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:112:3: //external:png_archive: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:112:3: //external:png_archive: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:123:3: //external:gif_archive: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:123:3: //external:gif_archive: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:135:3: //external:six_archive: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:135:3: //external:six_archive: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:151:3: //external:protobuf: no such attribute 'urls' in 'http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:151:3: //external:protobuf: missing value for mandatory attribute 'url' in 'http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:161:3: //external:gmock_archive: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:161:3: //external:gmock_archive: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:187:3: //external:pcre: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:187:3: //external:pcre: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:198:3: //external:swig: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:198:3: //external:swig: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:210:3: //external:curl: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:210:3: //external:curl: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:233:3: //external:grpc: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:233:3: //external:grpc: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:256:3: //external:linenoise: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:256:3: //external:linenoise: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:269:3: //external:llvm: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:269:3: //external:llvm: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:280:3: //external:jsoncpp_git: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:280:3: //external:jsoncpp_git: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:296:3: //external:boringssl: no such attribute 'urls' in 'http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:296:3: //external:boringssl: missing value for mandatory attribute 'url' in 'http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:306:3: //external:nanopb_git: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:306:3: //external:nanopb_git: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:322:3: //external:zlib_archive: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /home/bwu/ResearchProjects/tensorflow_org/tensorflow/workspace.bzl:322:3: //external:zlib_archive: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': error loading package 'external': Could not load //external package.
ERROR: missing fetch expression. Type 'bazel help fetch' for syntax and help.

**Comment by jart** [comment]
Thanks for reaching out. Your other machine isn't running Bazel ≥0.4.2. Installing the latest Bazel will do the trick.
