### ISSUE TITLE
Variable "matching_filenames" @  tf.train.match_filenames_once() should be local?

### ISSUE THREAD

**Issue by keotic** [tensorflow/tensorflow#6786]
This var holds the matched file names for the input stream pipeline.
Since it is added to the graph, when using the contractor of tf.train.Saver() it is saved
as part of the checkpoint state.
Hence loading saved models from checkpoints for inference, the training file names are loaded instead of the val / inference files.

Shouldn't this Var become a local variable? will it not be saved by default treated as local?

**Comment by jart** [comment]
Would it be possible for you to use `tf.matching_files` instead?

**Comment by keotic** [comment]
@jart , I will give it a try, if this is the recommended method, the documentation at
https://www.tensorflow.org/how_tos/reading_data/ should be changed.

**Comment by jart** [comment]
If I understand correctly, the goal of match_filenames_once is that it delegates to matching_files and then saves the result to checkpoints, so the operation only happens once. The documentation doesn't appear to be making any recommendations, so I'm not sure what is actionable here for  TensorFlow. If you believe there is a bug in the software or documentation, let me know and I'll re-open this issue.

**Comment by keotic** [comment]
There is not a bug, but it may cause undesired and unnoticed behavior in the following scenario:
1. Use "match_filenames_once" to feed data in the training phase.
2. Save model checkpoints with default 'tf.train.Saver()'

3. Use again 'match_filenames_once' with a different pattern to load the inference / test files.
4. Load previously saved model checkpoint for inference / test.

In this scenario, at step #4  the training files and not the test files will be loaded, since the old file list was loaded from the checkpoint.

Maybe a comment clarifying the issue should be added to the documentation.

**Comment by jart** [comment]
@dr4b Do you feel we should add further clarity to our documentation on loading models as @keotic is suggesting?

**Comment by dr4b** [comment]
Will this change in the API any time soon?  And if not, sure, go ahead and add a comment?

**Comment by yaroslavvb** [comment]
That seems like a footgun, a typical user might not expect `match_filenames_once` to be affected by checkpoint. A similar issue existed checkpoint affecting state of input pipelines that were affected by `epochs` variables, this was solved by making them local, as here

https://github.com/tensorflow/tensorflow/commit/4c85a95925a68fec324f70cd0d7f3d4548f97a38

**Comment by RoniStartApp** [comment]
@jart @dr4b as @yaroslavvb  pointed out, seems like my initial request / question of making the variable local should solve this issue.

**Comment by jiqiujia** [comment]
@keotic Is using your following steps right now? Will the correct queue be used at test time? 

> 
> Use "match_filenames_once" to feed data in the training phase.
> Save model checkpoints with default 'tf.train.Saver()'
> Use again 'match_filenames_once' with a different pattern to load the inference / test files.
> Load previously saved model checkpoint for inference / test.

**Comment by keotic** [comment]
@jiqiujia Should be OK if you are using latest versions of TF
