### ISSUE TITLE
could not find cuDevicePrimaryCtxSetFlags in libcuda DSO; dlerror: /usr/lib/libcuda.so.1: undefined symbol: cuDevicePrimaryCtxSetFlags

### ISSUE THREAD

**Issue by expenses** [tensorflow/tensorflow#6787]
Hi, when trying to get tensorflow on my Nvidia GPU, the output started with the following:

    I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
    I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
    I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
    I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
    I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
    F tensorflow/stream_executor/cuda/cuda_driver.cc:94] Check failed: s.ok() could not find cuDevicePrimaryCtxSetFlags in libcuda DSO; dlerror: /usr/lib/libcuda.so.1: undefined symbol: cuDevicePrimaryCtxSetFlags
After which, it exits.

I'm running with the following:

`uname -r`:
    
    4.8.13-1-ARCH

`lspci`:
    
    VGA compatible controller: NVIDIA Corporation GM107 [GeForce GTX 750] (rev a2)
    Subsystem: Gigabyte Technology Co., Ltd Device 362e
    Kernel driver in use: nvidia

`cat /proc/driver/nvidia/version`:

    NVRM version: NVIDIA UNIX x86_64 Kernel Module  340.101  Thu Dec  1 15:52:31 PST 2016
    GCC version:  gcc version 6.2.1 20160830 (GCC)

`ls -l /usr/lib/libcuda*`:

    lrwxrwxrwx 1 root root       12 Dec 16 01:18 /usr/lib/libcuda.so -> libcuda.so.1*
    lrwxrwxrwx 1 root root       18 Dec 16 01:18 /usr/lib/libcuda.so.1 -> libcuda.so.340.101*
    -rwxr-xr-x 1 root root 14011752 Dec 16 01:18 /usr/lib/libcuda.so.340.101*

Tensorflow version:
    
    0.12.1

**Note:** I _am_ running tensorflow on Python 3.6 having changed 'cp35' to 'cp36' in the file name of the binary, but I presume that this does not matter considering that this is a cuda issue, and that the CPU version worked fine.

The line that the error references is this one:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/cuda/cuda_driver.cc#L94

Whats going on here, and what can I do to fix this?

**Comment by expenses** [comment]
I installed the `nvidia`,`nvidia-libgl` and `nvidia-utils` packages instead of their `nvidia-340xx` equivalents, which did the trick.

**Comment by Amirtha1189** [comment]
Hi,

I am getting this error when i run TF1.0.1 on Windows with GPU support.
I installed CUDA version 8.0 and CuDNN version 5.1

>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\cuda\cuda_driver.cc:94] Check failed: s.ok() could not find cuDevice
PrimaryCtxSetFlags in libcuda DSO; dlerror: cuDevicePrimaryCtxSetFlags not found

What should i do to fix this?

**Comment by carlthome** [comment]
Same here on a K520 (AWS g2 instance) with TensorFlow 1.0.1, CUDA 8.0, cuDNN 5.1.

```
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
F tensorflow/stream_executor/cuda/cuda_driver.cc:94] Check failed: s.ok() could not find cuDevicePrimaryCtxSetFlags in libcuda DSO; dlerror: /usr/lib/x86_64-linux-gnu/libcuda.so.1: undefined symbol: cuDevicePrimaryCtxSetFlags
Aborted (core dumped)
```

**Comment by carlthome** [comment]
Exchanging the NVIDIA Display Driver from Ubuntu's repo (340.102) to the latest one from nvidia.com (367.57) solved it.

**Tech support 101:**
1. Reboot.
2. Update drivers.
3. Does it work now?
:panda_face:
