### ISSUE TITLE
One hot encoding of words?

### ISSUE THREAD

**Issue by greninja** [tensorflow/tensorflow#6793]
How can I create one hot encoding of words with  each word represented by a sparse vector of vocab size and the index of that particular word equated to 1 ?
something like `oneHotEncoding(words = ['a','b','c','d']) ->  [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]`

**Comment by jart** [comment]
Thanks for reaching out. We try to keep this issue tracker limited to bugs and feature requests. We recommend posting on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) for community-driven support.
