### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by kinsumliu** [tensorflow/tensorflow#68]
http://tensorflow.org/tutorials/mnist/beginners/index.md

...with the corresponding element of tf.log(y_)
...with the corresponding element of tf.log(y)

Is this the right place to report typo?

**Comment by vrv** [comment]
Sure, typo fix suggestions welcome!  We'll get in a fix to this documentation soon.  Thanks for the report!

**Comment by vrv** [comment]
Fixed in b4629c0e9f2b2bfab50ed7a705763421950234d4, Thanks!
