### ISSUE TITLE
Document parse_single_sequence_example

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#680]
The docs are completely silent on `parse_single_sequence_example`, even though the (officially referenced) `tf.train.Example` protocol buffers documentation mentions `SequenceExample`, and the documentation for `parse_single_sequence_example` in the source code (parsing_ops.py) appears rather complete. I think just exposing the source code documentation would be very helpful to people. In general though `SequenceExample` could use better documentation as it's a very useful feature.

**Comment by martinwicke** [comment]
The docs are not exposed so people don't start relying on this feature (whose interface is very likely to change in the future). It's not part of the public API. I realize the distinction isn't perfect, especially if related things are referenced in the parts of the docs that are referenced from official documentation.

This should be resolved once we publish a more mature version for these ops.

**Comment by alquraishi** [comment]
OK, but maybe update the source code docs to point out that `debug_name` must have a value (or fix it so that it doesn't fail if it doesn't.) May save the adventurous among us a few hours of debugging :)

**Comment by martinwicke** [comment]
Can you look if #687 fixes the issue? Clearly, the mismatch between documentation and code is a bug.

**Comment by alquraishi** [comment]
Yes #687 fixes it. Thanks.
