### ISSUE TITLE
dynamic seq2seq add example of using context_state

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#6803]
tf v1.0, in contrib/seq2seq/seq2seq_test.py , the code do not show how to use context_state, so we can get best path as output instead of rnn outputs.
Can we add sample code?

**Comment by jart** [comment]
More samples and documentation is always a good thing. I'm going to mark this as contributions welcome. Although I would like to bring this request to the attention of @xiejw who seems to be a big seq2seq contributor.

**Comment by chenghuige** [comment]
Well, I have find out how to do this. like below in decoder_fn 
    
    if cell_output is None:
      context_state = tensor_array_ops.TensorArray(
        dtype=dtype, tensor_array_name="best_path", size=0, dynamic_size=True, infer_shape=False)
    else:
      step_path = tf.expand_dims(next_input_id, 0)
      context_state = context_state.write(time - 1, step_path)

and use it :

    tf.transpose(decoder_context_state_inference.concat(), [1, 0])

**Comment by chenghuige** [comment]
In seq2seq_test.py 108-119, might be a minor bug, here should    

    maximum_length=decoder_sequence_length

    # now Inference decoder
        decoder_fn_inference = Seq2SeqTest._decoder_fn_with_context_state(
            decoder_fn_lib.simple_decoder_fn_inference(
                output_fn=output_fn,
                encoder_state=encoder_state,
                embeddings=decoder_embeddings,
                start_of_sequence_id=start_of_sequence_id,
                end_of_sequence_id=end_of_sequence_id,
                #TODO: find out why it goes to +1
                maximum_length=decoder_sequence_length - 1,
                num_decoder_symbols=num_decoder_symbols,
                dtype=dtypes.int32))

while in decoder_fun.py , should be
    done = control_flow_ops.cond(math_ops.equal(time, maximum_length)
    
    # now  decoder_fun.py
    done = control_flow_ops.cond(math_ops.greater(time, maximum_length),
            lambda: array_ops.ones([batch_size,], dtype=dtypes.bool),
            lambda: done)

After the change the test can pass, with decoder_sequence_length 7 equal decoder_context_state_train_res 7,  meaning last time is 7,(time is from 0 to 7) 
and output shape is (7,2,20)

    self.assertEqual(decoder_sequence_length,
                             decoder_context_state_train_res)

**Comment by j-min** [comment]
Since I haven't found any example codes for contrib.seq2seq API after 1.1 release, I made my own sample codes.
https://github.com/j-min/tf_tutorial_plus/tree/master/RNN_seq2seq
Is there a way that I can contribute by refactoring my code as part of official tutorials seq2seq APIs?

**Comment by itsmeolivia** [comment]
Feel free to send a PR ([this](https://help.github.com/articles/merging-a-pull-request/) might help if you're not sure how to contribute!!) otherwise, I am closing this issue now
