### ISSUE TITLE
Defun broken: errors_impl.NotFoundError: Op type not registered

### ISSUE THREAD

**Issue by albertz** [tensorflow/tensorflow#6804]
This code fails:

```
import tensorflow as tf
from tensorflow.python.framework import function

@function.Defun(tf.float32)
def custom_op(x):
    return x

x = tf.Variable(1, dtype=tf.float32)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(custom_op(x)))

sess.close()
```

Exception:

    tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'custom_op_da39a3ee'

**Comment by albertz** [comment]
The example is partly taken from #3710 although the bug reported there is probably a different one and was already fixed.

**Comment by yaroslavvb** [comment]
Version info?

**Comment by albertz** [comment]
Version 0.12.0.

**Comment by yaroslavvb** [comment]
Somehow running the init op breaks things. The code below works, but fails in the same way if you uncomment the `init_op` line

```
import tensorflow as tf
from tensorflow.python.framework import function

tf.reset_default_graph()

@function.Defun(tf.float32)
def custom_op(x):
    return tf.identity(x)

x = tf.placeholder(dtype=tf.float32)
sess = tf.Session()
#init_op = tf.global_variables_initializer()
sess.run(init_op)
x2 = custom_op(x)
print(sess.run(x2, feed_dict={x: 1.0}))

```

**Comment by yaroslavvb** [comment]
@zffchen78 must all the custom ops be created before the first `session.run` call? I didn't see this req in the docs

**Comment by yaroslavvb** [comment]
@albertz a work-around is to create your `custom_op` and save node before first run call

**Comment by albertz** [comment]
How do I save it before the first run call?

**Comment by yaroslavvb** [comment]
Ie in my example, you can change order of first  session run and creating init_op and it'll work

**Comment by albertz** [comment]
I see. So the workaround for my example:

```

import tensorflow as tf
from tensorflow.python.framework import function

@function.Defun(tf.float32)
def custom_op(x):
    return x

x = tf.Variable(1, dtype=tf.float32)
y = custom_op(x)
init_op = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init_op)
print(sess.run(y))

sess.close()
```

But I think this is a bug then, right? Because I would suppose that this should work. Or is this hard to fix?

**Comment by yaroslavvb** [comment]
Yes, I think it was unexpected, I'll leave to @zffchen78 to comment if it's intended behavior or not

**Comment by zffchen78** [comment]
@albertz the behavior you see is explainable.

the line 
  sess = tf.Session() 
effectively snapshots the default graph which includes the functions instantiated so far at that point. 
If the function is instantiated (the line custom_op(x) after that point, so far, our implementation does not re-snapshot the graph. That might be feasible but may be a bit complex, too.
