### ISSUE TITLE
convert_graphdef_memmapped_format produces corrupt graphs

### ISSUE THREAD

**Issue by eaigner** [tensorflow/tensorflow#6806]
I tried memory mapping an exported/frozen graph. Let's say the graph is named `graph.pb`. After converting the graph like this

    ./path/to/convert_graphdef_memmapped_format --in_graph=graph.pb --out_graph=graph_mmap.pb

I get

- `Converted 16 nodes` for an unquantized graph
- `Converted 0 nodes` for the 8bit quantized version of the graph

If I try to load any of these output files using the C++ API `ReadBinaryProto` and then `Run` the graph the following errors occur

- Unquantized: `Session was not created with a graph before Run()`
- Quantized: `Out of range: Read less bytes than requested`

so I guess the output file is a corrupt protobuf file (or a different version).

**Comment by jart** [comment]
Could you please provide the full stack traces?

**Comment by eaigner** [comment]
I'm not sure what stack trace and how to provide it since it doesn't crash. `ReadBinaryProto` just returns a status with `code` `OUT_OF_RANGE` and `msg` `Read less bytes than requested` for e.g. the 8bit quantized graph.

**Comment by jart** [comment]
We try to keep this issue tracker limited to bugs and feature requests. We recommend posting on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) for community-driven support.
