### ISSUE TITLE
[TensorBoard] To small dropdown menu

### ISSUE THREAD

**Issue by Faur** [tensorflow/tensorflow#6807]
This is not a big issue, but it is a tad annoying.

When using TensorBoard to visualize the graph the 'run' drop-down menu is very small.

![tb_menu](https://cloud.githubusercontent.com/assets/8115763/21893472/783d3b5e-d8db-11e6-81b0-08bc6fadf982.png)

I am using Chrome `Version 55.0.2883.87 m`

**Comment by jart** [comment]
Thoughts on this one @dandelionmane?

**Comment by dandelionmane** [comment]
Yeah, we should fix this, and it should be trivial. I'll file a bug internally and send it to @chihuahua

**Comment by wchargin** [comment]
Hi @Faur—thanks for reporting. I've migrated this to our new repository at https://github.com/tensorflow/tensorboard/issues/47.

Sorry for the long delay—we're going to try to be more responsive to issues and PRs moving forward. :-)
