### ISSUE TITLE
tf.unstack:AttributeError: 'module' object has no attribute 'unstack'

### ISSUE THREAD

**Issue by sharod** [tensorflow/tensorflow#6811]
I am trying to use tf.unstack but is getting the error:

AttributeError: 'module' object has no attribute 'unstack'

I am trying the alternative code version of the two lines in ptb_word_lm.py

**Comment by yaroslavvb** [comment]
Could you fill out the issue template? (version info, reproducible example)

**Comment by sharod** [comment]
version: 0.11.0
reproducible example:

inputs = tf.unstack(inputs, num=num_steps, axis=1)

I am trying out ptb_word_lm.py provided with tensorflow itself. In the middle of the code a commented out portion provides a suggested improvement to the code. I am trying that suggestion. The line of code above is already provided by the original version of the ptb_word_lm.py but commented.My entire code is:
[http://pastebin.com/U9guTEbv](http://pastebin.com/U9guTEbv)

**Comment by jart** [comment]
tf.unstack wasn't added until [v1.0.0-alpha](https://github.com/tensorflow/tensorflow/releases/tag/v1.0.0-alpha). Try upgrading.

**Comment by sharod** [comment]
jart can you pls tell me which of the .py files have the unstack function? Actually upgrading is a problem in my machine.

**Comment by jart** [comment]
@sharod Here's the commit that added unstack: https://github.com/tensorflow/tensorflow/commit/0ee63d0cdb63df0f34dada5176d6a5ad92fbccab. It appears to be a renaming of tf.unpack. So you should actually be able to just use that function in its place.
