### ISSUE TITLE
Add CUDA implementation of fused hue adjustment

### ISSUE THREAD

**Issue by mkolod** [tensorflow/tensorflow#6817]
Currently, the fused (rgb2hsv->hue_adjust->hsv2rgb) hue adjustment kernel exists in TF [for the CPU](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/adjust_hue_op.cc), but not for the GPU. This is also why the CPU path can only be enabled "secretly" (via [setting the TF_ADJUST_HUE_FUSED env var](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_impl.py#L1113) to true). Adding the CUDA kernel would make this op available for both CPUs and GPUs.

**Comment by mkolod** [comment]
Mentioning @zheng-xq since he implemented the CPU version. I will be submitting a PR for this issue soon so feel free to assign me.

**Comment by mkolod** [comment]
BTW, by the [following test](XXX), run on a machine with 32 GB RAM, a 6-core Intel Core i7-5930K CPU @ 3.50GHz and an NVIDIA GTX 1080 GPU produced a GPU-based speedup factor of 17.3, given both the use of a fused CPU and GPU kernel. This was based on a test with a 4D random image tensor with a batch size of 64 and "image" size of 256x256x3. The GTX 1080 throughput 31,950 images per second, while the Core i7-5930K throughput was 1,845 images per second. Longer running times, e.g. running tf.while_loop 10k times, can bring the speedup factor to about 30x on this reference hardware. Both 3D and 4D tensors work, but of course 4D tensors perform better due to batching. Note that for uint8 inputs (e.g. from tf.image_jpeg_decode), the results of the CPU and GPU kernel are identical, pixel for pixel. For inputs of int32, with a numeric range of [0, 256], a small fraction of pixels differ by up to 0.3% in intensity (1/255), which is caused by the fact that the Python wrapper for adjust_hue() does scaling, and scaling a range of [0, 255] by 1E32 causes precision problems. That's a very small error for that unusual case. Numbers in range of [0, 255] represented as floats, or as uint8 (scaled by 255 for float conversion by convert_image_dtype() inside tf.image_adjust_hue()) return exactly the same results on the CPU and GPU. Note that this is just an implementation of adjust_hue, and doesn't necessarily work for tf.image.random_hue, because the hue delta taken by the CUDA kernel is a scalar rather than a whole tensor. This can be addressed it need be to cover both adjust_hue() and random_hue().

**Comment by gunan** [comment]
Looks like PR #6818 has fixed this?
I am closing this issue but feel free to reopen if it is still not resolved.
