### ISSUE TITLE
TensorFlow on iOS

### ISSUE THREAD

**Issue by kuprel** [tensorflow/tensorflow#682]
In his NIPS tutorial, Jeff Dean mentioned that Google has an internal version of TensorFlow which runs on iOS.  Will this be open sourced?  If so, is there an estimate of how long until it will be available?

**Comment by girving** [comment]
Yes, we are planning to open source it.  No timeline, but there's a tracking bug here: https://github.com/tensorflow/tensorflow/issues/16.
