### ISSUE TITLE
tf.test.is_built_with_cuda() is 'False'

### ISSUE THREAD

**Issue by Viper373** [tensorflow/tensorflow#68236]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.16.1

### Custom code

Yes

### OS platform and distribution

Windows 10

### Python version

3.10.7

### CUDA/cuDNN version

CUDA12.3 cuDNN8.9.7

### GPU model and memory

NVIDIA GeForce RTX 4070 super

### Current behavior?

import tensorflow as tf
print("TensorFlow version:", tf.__version__)
print("Is GPU available?", tf.config.list_physical_devices('GPU'))
print("Is TensorFlow built with CUDA?:", tf.test.is_built_with_cuda())

result:
TensorFlow version: 2.16.1
Is GPU available? []
Is TensorFlow built with CUDA?: False
![屏幕截图 2024-05-20 050134](https://github.com/tensorflow/tensorflow/assets/77206948/560cb2c8-3578-4c35-be6d-e427573fe907)
The command I am using is "pip install tensorflow-2.16.1-cp310-cp310-win_amd64.whl --force"
And I have already installed CUDA and cuDNN through NVIDIA's official website
![屏幕截图 2024-05-20 050506](https://github.com/tensorflow/tensorflow/assets/77206948/a22d3e81-9f36-4483-9f56-81e9d80a6700)
![屏幕截图 2024-05-20 050520](https://github.com/tensorflow/tensorflow/assets/77206948/134b38e6-de9f-4a2f-a86f-86163c3d2724)
![屏幕截图 2024-05-20 050717](https://github.com/tensorflow/tensorflow/assets/77206948/5863af1d-37a4-407d-9405-94b5e41506f5)
I am working on a graduation project for LSTM model prediction，Please help me, thank you！！！

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
print("TensorFlow version:", tf.__version__)
print("Is GPU available?", tf.config.list_physical_devices('GPU'))
print("Is TensorFlow built with CUDA?:", tf.test.is_built_with_cuda())
```

### Relevant log output

```shell
TensorFlow version: 2.16.1
Is GPU available? []
Is TensorFlow built with CUDA?: False
```

**Comment by Viper373** [comment]
please help me!!!thanks!😭😭😭

**Comment by tilakrayal** [comment]
@Viper373,
Could you please confirm whether you are trying to install TensorFlow v2.16 on Windows with GPU? If you are trying the same, TensorFlow 2.10 was the last TensorFlow release that supported GPU on native-Windows. Starting with TensorFlow 2.11, you will need to install [TensorFlow in WSL2](https://tensorflow.org/install/pip#windows-%5Bwsl2%5D), or install tensorflow-cpu and, optionally, try the [TensorFlow-DirectML-Plugin](https://github.com/microsoft/tensorflow-directml-plugin#tensorflow-directml-plugin-)

https://www.tensorflow.org/install/pip#windows-native_1

Thank you!

**Comment by Viper373** [comment]
> ，您能否确认您是否正在尝试在带有 GPU 的 Windows 上安装 TensorFlow v2.16？如果您正在尝试相同的方法，TensorFlow 2.10 是本机 Windows 上支持 GPU 的最后一个 TensorFlow 版本。从 TensorFlow 2.11 开始，您需要[在 WSL2 中安装 TensorFlow](https://tensorflow.org/install/pip#windows-%5Bwsl2%5D)，或者安装 tensorflow-cpu，并根据需要尝试 [TensorFlow-DirectML-Plugin](https://github.com/microsoft/tensorflow-directml-plugin#tensorflow-directml-plugin-)
> 
> https://www.tensorflow.org/install/pip#windows-native_1
> 
> 谢谢！

I am certain that my Windows machine comes with a GPU, model 4070 super. Additionally, my Python version is 3.10.7, and I have installed cuda version 12.3 and cuDNN version 8.9.7. What version do I need to install? Can you help me write the corresponding Python, CUDA, and CUDNN versions for TF2.10

**Comment by tilakrayal** [comment]
@Viper373,
The compatible tested build configurations for TensorFlow v2.10 on Windows are tensorflow_gpu-2.10.0, python 3.7-3.10	Compiler - MSVC 2019, Bazel 5.1.1, cuDNN-8.1, CUDA-11.2.
https://www.tensorflow.org/install/source_windows#gpu

Thank you!

**Comment by Viper373** [comment]
> @Viper373, The compatible tested build configurations for TensorFlow v2.10 on Windows are tensorflow_gpu-2.10.0, python 3.7-3.10 Compiler - MSVC 2019, Bazel 5.1.1, cuDNN-8.1, CUDA-11.2. https://www.tensorflow.org/install/source_windows#gpu
> 
> Thank you!

thank you a lot！！！
