### ISSUE TITLE
Upgrade HighwayHash

### ISSUE THREAD

**Issue by namrata-ibm** [tensorflow/tensorflow#6823]
The HighwayHash module which is downloaded as an external dependency in TensorFlow produces different hash results on big endian and little endian architectures. This causes the test `testStringToHashBucketsStrong` from `//tensorflow/python/kernel_tests:string_to_hash_bucket_op_test` to fail on big endian. After raising an [issue](https://github.com/google/highwayhash/issues/35) with HighwayHash community, they have added a change to make hash values consistent across architectures through [commit](https://github.com/google/highwayhash/commit/cdde139127319cb5eb3917b635c4d2b182533cb4).

Will it be possible to pick this or higher commit of HighwayHash in TensorFlow?

**Comment by jart** [comment]
This doesn't sound good. I'm going to write up a change that upgrades TensorFlow. I just hope this change won't cause problems for people with big endian CPUs who stored the result of the previous hash.

**Comment by jart** [comment]
This upgrade is now blocked by https://github.com/google/highwayhash/issues/36.

**Comment by jart** [comment]
This should now be unblocked. I'm now going to mail out a change.

**Comment by namrata-ibm** [comment]
Thank you @jart and @rmlarsen for resolving this.

**Comment by jart** [comment]
Pleasure to be of service.
