### ISSUE TITLE
tf.einsum fails on evaluation in some cases

### ISSUE THREAD

**Issue by jihunchoi** [tensorflow/tensorflow#6824]
Hello,
I was a user of 'reshape-matmul-reshape' approach, however it felt me a bit messy, so I am trying some alternatives that do this automatically.
I had tried `tf.tensordot` before, however it did not work well when shapes are partially known (#6682).
As an alternative, I tried to use `tf.einsum`.
However, similar to `tf.tensordot`, it cannot handle some variables with partially-known-shape, for instance, the below codes fails on evaluation.

```
a = tf.placeholder('float32', shape=[None, None, 100])
b = tf.placeholder('float32', shape=[100, 300])
result_einsum = tf.einsum('ijk,kl->ijl', a, b)
a_value = np.random.randn(10, 20, 100)
b_value = np.random.randn(100, 300)
sess.run(result_einsum, {a: a_value, b: b_value})  # failure
```

This is the error message:
```
InvalidArgumentError (see above for traceback): only one input size may be -1, not both 0 and 1
         [[Node: Reshape_5 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](MatMul_3, Reshape_5/shape)]]
```

**Comment by jihunchoi** [comment]
I think the reason of the error is on `_reshape_if_necessary` function; in line 364, `new_shape` is defined to be a tuple which is constructed by replacing `None` with `-1` of `new_shape`.
If there exist two or more `None` values in a variable, the `shape` parameter passed to `reshape` function contains two or more `-1` values, thus the error is triggered.

**Comment by jihunchoi** [comment]
I don't fully understand how `einsum` works, but as far as I read, the reason is that when there exist two or more `None` values in one of `input` parameters, then `uncompacted_shape` in line 339 has two or more `None` values.
Then, in `_reshape_if_necessary` function, `None` values of `uncompacted_shape` are replaced with `-1` and passed to `reshape` function. Since `shape` parameter of `reshape` function should have at most one `None` value, thus the error is triggered.
I think it can be resolved if we check `uncompacted_shape` and explicitly giving it a shape value by `tf.shape` function to make it have at most one `-1` value.

**Comment by jart** [comment]
Assigning this issue to @drpngx who is reviewing the pull request you were generous enough to send us.

**Comment by markvdw** [comment]
Hi,
I just got the same error, and although it's amazing to see that it has been fixed so quickly, I think my issue coming from a different location.

My line is `tf.einsum('mckd,mc->mkd', Kmcmc, w)`, where `Kmcmc.get_shape()` evaluates to `(?, 8, ?, 8)`. This causes the same problem in [special_math_ops.py#L327](https://github.com/jihunchoi/tensorflow/blob/51b494280777d735607061e27a15b49a7b80d8e9/tensorflow/python/ops/special_math_ops.py#L327). This issue should also exist in [special_math_ops.py#L344](https://github.com/jihunchoi/tensorflow/blob/51b494280777d735607061e27a15b49a7b80d8e9/tensorflow/python/ops/special_math_ops.py#L334).

Could the same fix be applied to these situations too?

**Comment by jihunchoi** [comment]
I think that is indeed the similar issue, but I didn't thought of that case.
It seems that the same workaround can be applied to [special_math_ops.py#L327](https://github.com/jihunchoi/tensorflow/blob/51b494280777d735607061e27a15b49a7b80d8e9/tensorflow/python/ops/special_math_ops.py#L327), and it should be applied to [special_math_ops.py#L333](https://github.com/jihunchoi/tensorflow/blob/51b494280777d735607061e27a15b49a7b80d8e9/tensorflow/python/ops/special_math_ops.py#L333).

**Comment by drpngx** [comment]
thanks!

**Comment by jihunchoi** [comment]
I created a new PR solves the issue.

**Comment by xxi511** [comment]
I think `_exponential_space_einsum` faced the same problem that can't handle more than one `None` shape 
@jihunchoi  any chance to expect new pull request?

```python
    x_val = np.array([[1, 2],
                     [3, 4]])
    y_val = np.array([[4, 5],
                     [6, 3]])
    g_val = np.array([[3, 5],
                      [2, 7]])
    x = tf.placeholder(dtype=tf.int32, shape=[None, None])
    y = tf.placeholder(dtype=tf.int32, shape=[None, None])
    g = tf.placeholder(dtype=tf.int32, shape=[None, None])

    z = tf.einsum('ab,ab,ab->b', x, y, g)
    with tf.Session() as sess:
        a, b, c = sess.run([x,y,z], feed_dict={x: x_val,
                                               y: y_val,
                                               g: g_val})
```

```shell
InvalidArgumentError (see above for traceback): only one input size may be -1, not both 0 and 1
	 [[Node: Reshape = Reshape[T=DT_INT32, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](_recv_Placeholder_0/_5, Reshape/shape)]]
	 [[Node: Sum/_7 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_3_Sum", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```
