### ISSUE TITLE
Why is validation_metrics and validation_monitor code twice in tutorial code iris_monitors.py?

### ISSUE THREAD

**Issue by ladislav-urban** [tensorflow/tensorflow#6826]
Why is validation_metrics and validation_monitor code twice in tutorial code iris_monitors.py?
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/monitors/iris_monitors.py

**Comment by jart** [comment]
Thanks for reaching out. We try to keep this issue tracker limited to bugs and feature requests. We recommend posting on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) for community-driven support.

**Comment by yongqiangzhang1** [comment]
I don't know, and I can not get the correct results as the tutorial. I don't know why.
