### ISSUE TITLE
Support for 16 bit activations in ExpandDims operation.

### ISSUE THREAD

**Issue by robertkamara** [tensorflow/tensorflow#68293]
The task is to add support for 16-bit activations and 8-bit weights in ExpandDims operation. Currently, only float32 and int8_t types are supported:
https://github.com/tensorflow/tflite-micro/blob/8e22946b3faa51564df5dd9194f7540b2694892c/tensorflow/lite/micro/kernels/expand_dims.cc#L127C1-L134C13

**Comment by pkgoogle** [comment]
Hi @miaout17, can you please take a look? Thanks.

**Comment by LakshmiKalaKadali** [comment]
Hi @robertkamara,

It looks like this issue appears to have been resolved since PR [#2589](https://github.com/tensorflow/tflite-micro/pull/2589) was already merged into TFLite-micro repo.

Thank You
