### ISSUE TITLE
Fail to run person_detect.tflite via TFLite benchmark_model

### ISSUE THREAD

**Issue by bhbruce** [tensorflow/tensorflow#68308]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

97a794b0199b6e507e3f577861856ff09357a3cd

### Current behavior?

There is a TFLite model called `person_detect.tflite` in tflite-micro https://github.com/tensorflow/tflite-micro/blob/main/tensorflow/lite/micro/models/person_detect.tflite.
I cannot run this model via tensorflow's benchmark_model. 
It looks like all depthwise_convolutions' quantization_dim meta-data are wrong.

### Command to reproduce the issue

```shell
`tools/benchmark/benchmark_model  --num_runs=3 --enable_op_profiling=true --num_threads=2 --graph=person_detect.tflite`
```

### Relevant log output

```shell
### Error Log 

INFO: STARTING!
INFO: Log parameter values verbosely: [0]
INFO: Min num runs: [3]
INFO: Num threads: [2]
INFO: Graph: [person_detect.tflite]
INFO: Signature to run: []
INFO: Enable op profiling: [1]
INFO: #threads used for CPU inference: [2]
INFO: Loaded model person_detect.tflite
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 33 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 36 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 40 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 44 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 48 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 52 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 56 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 60 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 64 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 68 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 72 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 76 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 80 has invalid quantization parameters.
ERROR: quantized_dimension must be in range [0, 1). Was 3.
ERROR: Tensor 84 has invalid quantization parameters.
ERROR: Failed to initialize the interpreter
ERROR: Benchmarking failed.
```

**Comment by sawantkumar** [comment]
hi @bhbruce ,

I will benchmark the model and will get back to you.

**Comment by sawantkumar** [comment]
hi @bhbruce ,

I replicated the issue and i got the same error. So its probably a bug in the model's metadata .  I will raise a PR to get it fixed. Thank you

**Comment by bhbruce** [comment]
Hi @sawantkumar 
Appreciate for confirming it. If you have a PR to fix it, please share it with me. 
Thanks.

**Comment by sawantkumar** [comment]
Hi @bhbruce ,

Can you please post your issue at https://github.com/tensorflow/tflite-micro/issues for a quicker resolution.

**Comment by bhbruce** [comment]
Hi @sawantkumar 
I've added an issue https://github.com/tensorflow/tflite-micro/issues/2680.

**Comment by gaikwadrahul8** [comment]
Hi, @bhbruce

I apologize for the delayed response, I was able to run the tests on a development machine for [Person detection example](https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/person_detection) successfully for your reference I've added output log below and the quantization axis of 3 is correct for DEPTHWISE_CONV and the person detection model in the TFLM repo works as expected passing all continuous integration tests.


```
tensorflow/lite/micro/tools/make/test_latency_log.sh person_detection_test  gen/linux_x86_64_default_gcc/bin/person_detection_test '~~~ALL TESTS PASSED~~~' linux
Testing TestInvoke
person data.  person score: 113, no person score: -113

no person data.  person score: -57, no person score: 57

Ran successfully

1/1 tests passed
~~~ALL TESTS PASSED~~~

Running person_detection_test took 0.122 seconds
```

If I have missed something here please let me know.

Thank you for your cooperation and patience.

**Comment by bhbruce** [comment]
Hi @gaikwadrahul8 
Thank you for trying with TFLM. I can understand that it's available for TFLM.
However, it cannot run on TFL. Is it reasonable?

**Comment by gaikwadrahul8** [comment]
Hi, @bhbruce

I apologize for the delayed response, as far I know TFLM is designed for a very different target platform (microcontrollers) and therefore has specific optimizations that may not translate directly to the standard TensorFlow Lite runtime. Trying to run a TFLM model on the standard TensorFlow Lite interpreter might expose issues with metadata, operator support or quantization that are specific to TFLM.

If you need the model to run on standard TensorFlow Lite you might need to re-convert the model from TensorFlow with settings appropriate for TensorFlow Lite which compatible with mobile or edge devices rather than microcontrollers. You can use different Model optimization techniques

TensorFlow Lite currently supports optimization via quantization, pruning and clustering.

These are part of the [TensorFlow Model Optimization Toolkit](https://www.tensorflow.org/model_optimization), which provides resources for model optimization techniques that are compatible with TensorFlow Lite. Please refer this [official documentation](https://ai.google.dev/edge/litert/models/model_optimization)

If I have missed something here please let me know. 

Thank you for your cooperation and patience.

**Comment by bhbruce** [comment]
Hi @gaikwadrahul8 
Thank you for your explanation.
