### ISSUE TITLE
Instructions to install Tensorflow

### ISSUE THREAD

**Issue by gcelano** [tensorflow/tensorflow#68394]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.16

### Custom code

No

### OS platform and distribution

Debian 12 Bookworm

### Current behavior?

What version of CUDA Toolkit is required by Tensorflow 2.16? The instructions here [1] speak of 11.8, but those here [2] seem to suggest 12.3. This is very confusing; please, update the documentation.

---
[1] https://www.tensorflow.org/install/pip
[2] https://www.tensorflow.org/install/source

### Standalone code to reproduce the issue

```shell
No link required
```

**Comment by tilakrayal** [comment]
@gcelano,
Thank you for the issue. We observed the same, please allow some time to have a concern on this issue and will provide the update on the same. Thank you!

**Comment by tilakrayal** [comment]
@gcelano,
Apologies, we have raised an internal issue CL/638531187 for the same. The request is under the review. Once it resolved, the changes will be applied on the mentioned document. Thank you!

**Comment by tilakrayal** [comment]
@gcelano,
Could you please take a look at the official document, the requested changes have been reflected. 
https://www.tensorflow.org/install/pip#software_requirements

![image](https://github.com/user-attachments/assets/9534b7da-3450-433e-8963-d65076632591)
