### ISSUE TITLE
A zip and/or tar for pypi

### ISSUE THREAD

**Issue by schwehr** [tensorflow/tensorflow#6841]
As of 0.12.1, https://pypi.python.org/pypi/tensorflow/ only has os specific wheels.  It would be very nice for packages (e.g. me with fink on the mac) to have a point release tar or zip file too.

**Comment by jart** [comment]
I'm not familiar with Fink. Why can't it use wheel files? What are the advantages of putting a tarball on cheeseshop instead of just the wheels?

**Comment by schwehr** [comment]
Fink builds from source.  It needs to be able to control the entire setup process.  Looking in the wheel, I find:

file tensorflow/python/_pywrap_tensorflow.so
tensorflow/python/_pywrap_tensorflow.so: Mach-O 64-bit dynamically linked shared library x86_64

otool -L tensorflow/python/_pywrap_tensorflow.so
tensorflow/python/_pywrap_tensorflow.so:
	bazel-out/local-opt/bin/tensorflow/python/_pywrap_tensorflow.so (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)

If for fink, I need to change anything about compile options or linking (which we do), I'm SOL.

**Comment by jart** [comment]
Have you considered configuring Fink to download the tarball from the [release page](https://github.com/tensorflow/tensorflow/releases/tag/0.12.1)?

**Comment by schwehr** [comment]
Sure, but the normal thing for python packages to do is to put a tar and/or zip on pypi.

**Comment by jart** [comment]
Normally Python packages are capable of being built from source by setuptools, which is not the case with TensorFlow. Uploading the GitHub tarball to cheeseshop would add complexity to our release process and I can't think of any reason why it would provide greater benefit to our users.
