### ISSUE TITLE
Tensorflow Docker Instructions

### ISSUE THREAD

**Issue by gcelano** [tensorflow/tensorflow#68420]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.16

### Custom code

No

### OS platform and distribution

Debian 12 Bookworm

### Current behavior?

Installation instructions for Tensorflow Docker  [1] refer to Invidia Docker, which however has been archived on January 22 2024. The page needs to be updated.

---
[1] https://www.tensorflow.org/install/docker

### Standalone code to reproduce the issue

```shell
No code required
```

**Comment by Venkat6871** [comment]
Hi **@gcelano** ,
- This issue belongs to NVIDIA, We are not working on NVIDIA repo. Please post this issue on NVIDIA repo.

Thank you!

**Comment by gcelano** [comment]
@Venkat6871 , in the Tensorflow instructions [1], a requirement is installing NVIDIA Docker support [2], but this is wrong, because that software has been deprecated in January 2024 and superseded by NVIDIA Container Toolkit [3]: therefore, no reference should appear in current Tensorflow instructions.

I have been able to run Docker images recently just installing NVIDIA container Toolkit, but probably you guys should run a few tests.

---
[1] https://www.tensorflow.org/install/docker
[2] https://github.com/NVIDIA/nvidia-docker?tab=readme-ov-file
[3] https://github.com/NVIDIA/nvidia-container-toolkit

**Comment by Venkat6871** [comment]
Hi **@gcelano** ,
- Would you mind submitting a Pull Request to update the TensorFlow installation instructions with the information about NVIDIA Container Toolkit?

Thank you!
