### ISSUE TITLE
Android Tflite model fails to load on GPU Delegate: CL_OUT_OF_HOST_MEMORY

### ISSUE THREAD

**Issue by filip-halt** [tensorflow/tensorflow#68470]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

org.tensorflow:tensorflow-lite:2.16.1

### Custom code

Yes

### OS platform and distribution

Android

### Mobile device

Samsung S23

### Current behavior?

Currently trying to get a larger model to load on an S23 but I am running into OOM errors. When initializing an Interpreter using a GPUDelegate with factory options grabbed from CompatibilityList.getBestOptionsForThisDevice(), the Interpreter crashes with `Failed to apply delegate: Failed to build program executable - Out of host memoryError: Program not built!`.  This seems to pop up from an OpenCL error that is parsed with: https://github.com/tensorflow/tensorflow/blob/dd5c42638ac3c19c7facffb4c3cdadd2524cc6a5/tensorflow/lite/delegates/gpu/cl/util.cc#L42

My best guess is that this is due to hitting the Dalvik-heap memory limit of 512mb found on my device with Runtime.maxMemory(). I profiled the memory usage and it seems to crash around the 450mb  mark. Does Tflite on android not use native memory to get around this? I seem to recall people getting 1gb+ models running on their devices. I guess this could possibly be a build step that is going over the limits, but once built it would be offloaded to native?

Note: I am using pyjnius to do this which might be causing problems, but I feel like that isn't the cause. 

### Standalone code to reproduce the issue

```shell
Not sure how useful.
```

### Relevant log output

```shell
05-22 16:31:08.869 23806 23859 I python  :  jnius.jnius.JavaException: JVM exception occurred: Internal error: Failed to apply delegate: Failed to build program executable - Out of host memoryError: Program not built!
05-22 16:31:08.869 23806 23859 I python  :  Falling back to OpenGL
05-22 16:31:08.869 23806 23859 I python  :  TfLiteGpuDelegate Init: No shader implementation for transpose
05-22 16:31:08.869 23806 23859 I python  :  TfLiteGpuDelegate Prepare: delegate is not initialized
05-22 16:31:08.869 23806 23859 I python  :  Node number 2612 (TfLiteGpuDelegateV2) failed to prepare.
```

**Comment by sawantkumar** [comment]
Hi @filip-halt ,

Can you please provide the tflite model file so that i can replicate the issue?

**Comment by filip-halt** [comment]
> Hi @filip-halt ,
> 
> Can you please provide the tflite model file so that i can replicate the issue?

You can find a copy here: https://github.com/filip-halt/tflite_bug It was too large to upload directly into this chat.

**Comment by filip-halt** [comment]
Turns out that this is most likely due to a conv2dtranspose layer in the model.  I was under the impression that [conv2dtranpose](https://github.com/tensorflow/tensorflow/blob/43ce5b4267d89b9e7f96821495ce4f6bdc7aa1e6/tensorflow/lite/delegates/gpu/gl/kernels/transpose_conv.cc#L39) was supported but I could be wrong.

**Comment by filip-halt** [comment]
I believe that this is a grouped TRANSPOSE_CONV conversion problem. Tensorflow seems to barely support this and is what is breaking when converting onnx to tf. The default conversion creates a large amount of layers that ultimately cause an OOM on the phone when loading. 

<img width="1403" alt="image" src="https://github.com/tensorflow/tensorflow/assets/81822489/5c93b64a-b188-4fa3-9ea8-8c01abdf073a">

**Comment by sawantkumar** [comment]
Hi @filip-halt  , we're wondering if you may be able to resolve your issue by using [AI-Edge-Torch](https://github.com/google-ai-edge/ai-edge-torch), you can find more information here: [googleblog](https://developers.googleblog.com/en/ai-edge-torch-high-performance-inference-of-pytorch-models-on-mobile-devices/).

I have actually created a simple script for converting a mobilenet model here:

```py
import torch
import torchvision
import ai_edge_torch

mobilenet_model = torchvision.models.mobilenet_v3_small()
sample_inputs = (torch.randn(1, 3, 224, 224),)

edge_model = ai_edge_torch.convert(mobilenet_model.eval(), sample_inputs)
edge_model.export("mobilenet_v3_small.tflite")
```
If you want to, you can actually try visualizing the result in [model-explorer](https://github.com/google-ai-edge/model-explorer) as well.

Please try them out and let us know if this resolves your issue. If you still need further help, feel free to open a new issue at the respective repo.
