### ISSUE TITLE
Could contens on tensorflow.org be mirrored on github or other places other than google server? 

### ISSUE THREAD

**Issue by JinXinDeep** [tensorflow/tensorflow#685]
I am from China, and I cannot open the tensorflow.org web site. As known to all, google services are not available in China because the Firewall. It would be very helpful if the documents and turoirals can be obtained from other places other than google server. Sorry to bother. Thanks!

**Comment by martinwicke** [comment]
All of the content on tensorflow.org (without the fancy styling and some math formatting) is also available on github, in the tensorflow/g3doc folder. The HTML on tensorflow.org is generated quite similarly to what github's MarkDown viewer does, so the experience shouldn't be all that different.

**Comment by JinXinDeep** [comment]
Thanks, that's very useful. I have just started to learn tensorflow, it is the place where I can begin ~~
