### ISSUE TITLE
Why does my GPU trained model on Jetson Nano preform so much worse than CPU.

### ISSUE THREAD

**Issue by Nicholas-B1** [tensorflow/tensorflow#68610]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.4.1

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Python version

3.8.1

### Current behavior?

Accuracy is staying the same when training on GPU but I want the speed of that training.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1jD3w2KwIGyIG65bUYxxLiOgl8BTY5PVg?usp=sharing
```

### Relevant log output

```shell
It sometimes gives memory errors. I am just wondering how I can use the GPU for training speed while maintaining the accuracy I get with CPU.
```

**Comment by Venkat6871** [comment]
Hi **@Nicholas-B1** ,
- I tried to replicate your issue on [colab](https://colab.sandbox.google.com/gist/Venkat6871/d58fe084d7e12e824cde671fbb66e66f/68610_2-16-1.ipynb), But it is asking directory. Could you please share the proper colab gist with all the dependencies to analyze more of it.

Thank you!

**Comment by Nicholas-B1** [comment]
I actually tried to run my model with CPU and it is giving the same bad results however, this model worked fine on my other machine that was running a newer version of Tensorflow. I had to downgrade to be able to use my GPU on my jetson nano. Is there anyone I could ask about this model issue? I have a feeling it maybe because of outdated libraries. So it was not a GPU issue after all.

**Comment by Venkat6871** [comment]
Hi **@Nicholas-B1** ,
It seems TensorFlow 2.4 might be causing the issue. This version is outdated and could be the reason for the poor results you are seeing. I strongly recommend upgrading to a newer TensorFlow version. Since your model worked fine on a newer version previously, this is likely the solution. And GPU is not related to tensorflow.

Thank you!
