### ISSUE TITLE
Strange bug with tf.nn.nce_loss

### ISSUE THREAD

**Issue by chiphuyen** [tensorflow/tensorflow#6861]
So for tf.nn.nce_loss for word2vec_basic, if I explicitly use keyword arguments, such as:
      tf.nn.nce_loss(weights=nce_weights,
                     biases=nce_biases,
                     labels=train_labels,
                     inputs=embed,
                     num_sampled=num_sampled,
                     num_classes=vocabulary_size))

everything is fine. But if I get rid of the keywords:
      tf.nn.nce_loss(nce_weights, nce_biases, train_labels, embed, num_sampled, vocabulary_size))

I run into the bug: 
`  File ".../tensorflow/python/ops/nn.py", line 1336, in nce_loss
    name=name)
  File ".../tensorflow/python/ops/nn.py", line 1198, in _compute_sampled_logits
    array_ops.reshape(true_w, new_true_w_shape))
  File ".../tensorflow/python/ops/gen_math_ops.py", line 1613, in mul
    result = _op_def_lib.apply_op("Mul", x=x, y=y, name=name)
  File ".../tensorflow/python/framework/op_def_library.py", line 521, in apply_op
    inferred_from[input_arg.type_attr]))
TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type int32 of argument 'x'.`

I looked into the source code for nce_loss but couldn't seem to find the cause of this bug. Can anyone help me with this? Thanks a lot!

**Comment by soloice** [comment]
If you try to look into the documentation of this function, say, run 
`print(tf.nn.nce_loss.__doc__)`
, you'll get:
```
weights: A `Tensor` of shape `[num_classes, dim]`, or a list of `Tensor`
        objects whose concatenation along dimension 0 has shape
        [num_classes, dim].  The (possibly-partitioned) class embeddings.
    biases: A `Tensor` of shape `[num_classes]`.  The class biases.
    inputs: A `Tensor` of shape `[batch_size, dim]`.  The forward
        activations of the input network.
    labels: A `Tensor` of type `int64` and shape `[batch_size,
        num_true]`. The target classes.
    num_sampled: An `int`.  The number of classes to randomly sample per batch.
    num_classes: An `int`. The number of possible classes.
    and something more balabala...
```
So if you pass arguments by position instead of by keyword, the 3rd argument is inputs, and the 4th is labels. Try to switch these 2 parameters.

**Comment by jart** [comment]
Thank you for helping our friend @soloice. For future reference @chiphuyen we try to keep this issue tracker limited to bugs and feature requests. We recommend posting on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) for community-driven support.

**Comment by swordspoet** [comment]
@soloice Thank you so much, I have met this problem and I struggled it for a long time until I saw "Try to switch these 2 parameters."
