### ISSUE TITLE
Tensorflow Developer certificate didnt recieved yet

### ISSUE THREAD

**Issue by shiyasali23** [tensorflow/tensorflow#68654]
i had passed the Tensorflow Developer certificate  exam in may 20th until now i didnt recieve my certificate through mail or anything else.please help if anyone had any lead

**Comment by Venkat6871** [comment]
Hi **@shiyasali23** ,
- Please send an email to the TF certification team (tensorflow-certificate-support@google.com) for further assistance. 

Thank you!
