### ISSUE TITLE
Confusion regarding `jemalloc`

### ISSUE THREAD

**Issue by zafartahirov** [tensorflow/tensorflow#6869]
@jhseu In one of the recent commits (83c6e0c), `jemalloc` was introduced. The [blame comment](https://github.com/tensorflow/tensorflow/commit/83c6e0c63acdcab2c58c4ed7220bfa58879b1d57) says that it is "Only enabled on Linux for now". However, it defaults to `enabled` for any OS. If it is intended to work for Linux only, I think it should default to `disabled`, or should ask only if detected Linux-based system (i.e. `$(uname -a | tr 'A-Z' 'a-z') =~ linux`).

The main confusion is that if I run the `configure` from Unix-based (e.g. OS X) or Windows, and just zoom through the config requests, it will try enabling `jemalloc`, and doesn't have a check for OS in the [`configure`](https://github.com/tensorflow/tensorflow/blob/73bc42890/configure).

**Comment by gunan** [comment]
I think it is enabled/disabled right here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/default/build_config.bzl#L186

I can confirm that in macos and windows, It does not build.
However, in macos, configure script prints using jemalloc on linux, which might be confusing.

@jhseu, maybe we can make configure print some more information based on OS?

**Comment by suiyuan2009** [comment]
is jemalloc better than tcmalloc? I'm using tcmalloc before.

**Comment by gunan** [comment]
In our benchmarks, jemalloc was slightly faster, but looks like tcmalloc has some changes planned that can make it faster.
@jhseu can comment more on that.

**Comment by jhseu** [comment]
Our intention is to choose the right default, and we run a lot of numbers internally, and right now jemalloc is better. It's possible that we'll update the external tcmalloc and switch later on, but we're not sure yet.
