### ISSUE TITLE
There is no target called wheel

### ISSUE THREAD

**Issue by Ichimikichiki** [tensorflow/tensorflow#68702]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

r2.16

### Custom code

No

### OS platform and distribution

Arch Linux

### Python version

3.10

### Bazel version

6.5.0

### GCC/compiler version

13.3.0

### CUDA/cuDNN version

9.1.1

### GPU model and memory

NVIDIA 4090

### Current behavior?

You say to
```
bazel build //tensorflow/tools/pip_package:wheel --repo_env=WHEEL_NAME=tensorflow 
```
But there isn't even a target called "wheel"

### Standalone code to reproduce the issue

```shell
bazel query "//tensorflow/tools/pip_package:*"
//tensorflow/tools/pip_package:BUILD
//tensorflow/tools/pip_package:MANIFEST.in
//tensorflow/tools/pip_package:README
//tensorflow/tools/pip_package:THIRD_PARTY_NOTICES.txt
//tensorflow/tools/pip_package:build_pip_package
//tensorflow/tools/pip_package:build_pip_package.sh
//tensorflow/tools/pip_package:included_headers
//tensorflow/tools/pip_package:included_headers_gather
//tensorflow/tools/pip_package:licenses
//tensorflow/tools/pip_package:setup.py
//tensorflow/tools/pip_package:simple_console
//tensorflow/tools/pip_package:simple_console.py
//tensorflow/tools/pip_package:xla_build/CMakeLists.txt
//tensorflow/tools/pip_package:xla_cmake
//tensorflow/tools/pip_package:xla_compiled_cpu_runtime_srcs.txt
//tensorflow/tools/pip_package:xla_compiled_cpu_runtime_srcs.txt_file
Loading: 1 packages loaded
```

### Relevant log output

```shell
ERROR: Skipping '//tensorflow/tools/pip_package:wheel': no such target '//tensorflow/tools/pip_package:wheel': target 'wheel' not declared in package 'tensorflow/tools/pip_package' defined by /fourth/github.com/tensorflow/tensorflow/tools/pip_package/BUILD (Tip: use `query "//tensorflow/tools/pip_package:*"` to see all the targets in that package)

WARNING: Target pattern parsing failed.

ERROR: no such target '//tensorflow/tools/pip_package:wheel': target 'wheel' not declared in package 'tensorflow/tools/pip_package' defined by /fourth/github.com/tensorflow/tensorflow/tools/pip_package/BUILD (Tip: use `query "//tensorflow/tools/pip_package:*"` to see all the targets in that package)
```

**Comment by Sr1ya** [comment]
It seems there is a misunderstanding regarding the correct Bazel target for building the TensorFlow pip package. The error log indicates that the `wheel` target does not exist. Instead, the correct target for building the TensorFlow pip package is `build_pip_package`.

Here's a standalone script to reproduce the issue and the correct steps to build the TensorFlow pip package from source.

### Standalone Code to Reproduce the Issue

```sh
# Cloning the TensorFlow repository
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout r2.16

# Configuring the build
./configure

# Querying the available targets in the pip_package directory
bazel query "//tensorflow/tools/pip_package:*"

# Attempting to build the non-existent target (this will reproduce the error)
bazel build //tensorflow/tools/pip_package:wheel
```

### Relevant Log Output

```plaintext
ERROR: Skipping '//tensorflow/tools/pip_package:wheel': no such target '//tensorflow/tools/pip_package:wheel': target 'wheel' not declared in package 'tensorflow/tools/pip_package' defined by /path/to/tensorflow/tools/pip_package/BUILD (Tip: use `query "//tensorflow/tools/pip_package:*"` to see all the targets in that package)

WARNING: Target pattern parsing failed.

ERROR: no such target '//tensorflow/tools/pip_package:wheel': target 'wheel' not declared in package 'tensorflow/tools/pip_package' defined by /path/to/tensorflow/tools/pip_package/BUILD (Tip: use `query "//tensorflow/tools/pip_package:*"` to see all the targets in that package)
```

### Correct Steps to Build the TensorFlow Pip Package

1. **Clone the TensorFlow Repository**

```sh
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout r2.16
```

2. **Configure the Build**

```sh
./configure
```

You will be prompted to set various build options. Provide the appropriate values for your system.

3. **Build the Pip Package**

Use the correct target `build_pip_package`:

```sh
bazel build //tensorflow/tools/pip_package:build_pip_package
```

4. **Create the Pip Package**

Once the build is complete, create the pip package:

```sh
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
```

5. **Install the Pip Package**

Finally, install the newly created pip package:

```sh
pip install /tmp/tensorflow_pkg/tensorflow-*.whl
```

### Summary

Here is the entire process streamlined into a single script:

```sh
#!/bin/bash

# Step 1: Clone TensorFlow repository
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout r2.16

# Step 2: Configure TensorFlow build
./configure

# Step 3: Build the TensorFlow pip package
bazel build //tensorflow/tools/pip_package:build_pip_package

# Step 4: Create the pip package
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

# Step 5: Install the pip package
pip install /tmp/tensorflow_pkg/tensorflow-*.whl
```

This script will properly build and install the TensorFlow pip package from source. If you encounter any further issues, please provide detailed error logs for additional troubleshooting.

**Comment by Ichimikichiki** [comment]
Sure. So just update the website with the correct instructions I guess.

**Comment by manswad** [comment]
> Sure. So just update the website with the correct instructions I guess.

lol

**Comment by tilakrayal** [comment]
@Ichimikichiki,
To build a pip package, **you need to specify** **--repo_env=WHEEL_NAME** flag. depending on the provided name, package will be created.

`bazel build //tensorflow/tools/pip_package:wheel --repo_env=WHEEL_NAME=tensorflow_cpu`

As a result, generated wheel will be located in

`bazel-bin/tensorflow/tools/pip_package/wheel_house/`

https://www.tensorflow.org/install/source#build_the_package

**Comment by tomneo2004** [comment]
> @Ichimikichiki, To build a pip package, **you need to specify** **--repo_env=WHEEL_NAME** flag. depending on the provided name, package will be created.
> 
> `bazel build //tensorflow/tools/pip_package:wheel --repo_env=WHEEL_NAME=tensorflow_cpu`
> 
> As a result, generated wheel will be located in
> 
> `bazel-bin/tensorflow/tools/pip_package/wheel_house/`
> 
> https://www.tensorflow.org/install/source#build_the_package

I follow official instruction and still got the error `no such target '//tensorflow/tools/pip_package:wheel': target 'wheel' not declared in package 'tensorflow/tools/pip_package'`

**Comment by Ichimikichiki** [comment]
Thanks @tilakrayal I followed the instructions exactly as they are on the website.

If you're saying the website instructions are wrong, then that's the purpose of posting this issue to get you to update with the correct instructions.
![Screenshot_2024-06-15_11-03-24](https://github.com/tensorflow/tensorflow/assets/40658431/8ffbd251-c3f2-425b-93de-db85e737191c)

**Comment by cunhahugocap** [comment]
I'm also facing the same issue. No wheel target found.
When I built the first time in a Ubuntu 22.04 virtual machine in VirtualBox it worked nicely.

However, when I did the same steps in Windows WSL with the same Ubuntu 22.04 it's not working. It always says:
`ERROR: Skipping '//tensorflow/tools/pip_package:wheel': no such target '//tensorflow/tools/pip_package:wheel': target 'wheel' not declared in package 'tensorflow/tools/pip_package'`

I already tried to installed wheel with pip, but it's already installed, reinstalled pip, but nothing until now.

**Comment by tilakrayal** [comment]
@Ichimikichiki,
Could you try to replace "//tensorflow/tools/pip_package:wheel" to "//tensorflow/tools/pip_package:build_pip_package" and try again if it working in this case. Thank you!

**Comment by cunhahugocap** [comment]
@tilakrayal I built the TensorFlow yesterday successfully at night using the exact suggestion.

The difference is that the **whl** packing must be done in another step executing:
`tensorflor/tools/pip_package/build_pip_package.sh --dst <destination_folder> --project_name <file_name_prefix>`

At this point, I realized that "//tensorflow/tools/pip_package:wheel" is just a convenience to build and packing all at once.

**Comment by CrocodileAhmad** [comment]
> @tilakrayal I built the TensorFlow yesterday successfully at night using the exact suggestion.
> 
> The difference is that the **whl** packing must be done in another step executing: `tensorflor/tools/pip_package/build_pip_package.sh --dst <destination_folder> --project_name <file_name_prefix>`
> 
> At this point, I realized that "//tensorflow/tools/pip_package:wheel" is just a convenience to build and packing all at once.

Hello. I am facing the exact same problem, and just to make things clear: are you suggesting that we should run the command:
**1.** `bazel build //tensorflow/tools/pip_package:build_pip_package`

Then:
**2.** `bazel build //tensorflor/tools/pip_package/build_pip_package.sh --dst <destination_folder> --project_name <file_name_prefix>` ?


I am a bit confused since running the 1st command generated a `.whl` file in `/tensorflow/bazel-bin/tensorflow/tools/pip_package/wheel_house`. The name of the file is `tensorflow_cpu-2.18.0-cp311-cp311-linux_x86_64.whl` 

Although i am trying to build TF 2.13.0 in a Python 3.8 environment, the `.whl` file always has the same name as above with TF 2.18 and cp11 (CPython 11), what could be the source of this problem? I have already run `git checkout r2.13` to get the intended TF 2.13, but no matter what I do, it always generates `tensorflow_cpu-2.18.0-cp311-cp311-linux_x86_64.whl` ??!!

**Comment by tomneo2004** [comment]
None of solution above work for me.

`bazel build //tensorflow/tools/pip_package:wheel --repo_env=WHEEL_NAME=tensorflow_cpu`
doesn't work
```
ERROR: Skipping '//tensorflow/tools/pip_package:wheel': no such target '//tensorflow/tools/pip_package:wheel': target 'wheel' not declared in package 'tensorflow/tools/pip_package'
```

`bazel build //tensorflor/tools/pip_package/build_pip_package.sh --dst <destination_folder> --project_name <file_name_prefix>`
doesn't work
`ERROR: --dst :: Unrecognized option: --dst`

The only method work for me is
`bazel build //tensorflow/tools/pip_package:build_pip_package --repo_env=WHEEL_NAME=tensorflow_cpu`
to build package then to generate wheel file
`./bazel-bin/tensorflow/tools/pip_package/build_pip_package ./tmp/tf_pkg`
finally a file `tensorflow-2.16.2-cp311-cp311-linux_x86_64.whl` is generated under directory `./tmp/tf_pkg`.
If I encounter a problem during file generation `command not found patchelf` then just `sudo apt install patchelf` and rerun last command again to solve it.

I test it on Ubuntu 22.04 amd64(VirtualBox) for my tensorflow project and it run well without issue.

**Comment by CrocodileAhmad** [comment]
> None of solution above work for me.
> 
> `bazel build //tensorflow/tools/pip_package:wheel --repo_env=WHEEL_NAME=tensorflow_cpu` doesn't work
> 
> ```
> ERROR: Skipping '//tensorflow/tools/pip_package:wheel': no such target '//tensorflow/tools/pip_package:wheel': target 'wheel' not declared in package 'tensorflow/tools/pip_package'
> ```
> 
> `bazel build //tensorflor/tools/pip_package/build_pip_package.sh --dst <destination_folder> --project_name <file_name_prefix>` doesn't work `ERROR: --dst :: Unrecognized option: --dst`
> 
> The only method work for me is `bazel build //tensorflow/tools/pip_package:build_pip_package --repo_env=WHEEL_NAME=tensorflow_cpu` to build package then to generate wheel file `./bazel-bin/tensorflow/tools/pip_package/build_pip_package ./tmp/tf_pkg` finally a file `tensorflow-2.16.2-cp311-cp311-linux_x86_64.whl` is generated under directory `./tmp/tf_pkg`. If I encounter a problem during file generation `command not found patchelf` then just `sudo apt install patchelf` and rerun last command again to solve it.
> 
> I test it on Ubuntu 22.04 amd64(VirtualBox) for my tensorflow project and it run well without issue.

What does the command `./bazel-bin/tensorflow/tools/pip_package/build_pip_package ./tmp/tf_pkg` do? and does it really start with `./`? Sorry if it's a silly question but I am no expert in this topic.

**Comment by CrocodileAhmad** [comment]
> None of solution above work for me.
> 
> `bazel build //tensorflow/tools/pip_package:wheel --repo_env=WHEEL_NAME=tensorflow_cpu` doesn't work
> 
> ```
> ERROR: Skipping '//tensorflow/tools/pip_package:wheel': no such target '//tensorflow/tools/pip_package:wheel': target 'wheel' not declared in package 'tensorflow/tools/pip_package'
> ```
> 
> `bazel build //tensorflor/tools/pip_package/build_pip_package.sh --dst <destination_folder> --project_name <file_name_prefix>` doesn't work `ERROR: --dst :: Unrecognized option: --dst`
> 
> The only method work for me is `bazel build //tensorflow/tools/pip_package:build_pip_package --repo_env=WHEEL_NAME=tensorflow_cpu` to build package then to generate wheel file `./bazel-bin/tensorflow/tools/pip_package/build_pip_package ./tmp/tf_pkg` finally a file `tensorflow-2.16.2-cp311-cp311-linux_x86_64.whl` is generated under directory `./tmp/tf_pkg`. If I encounter a problem during file generation `command not found patchelf` then just `sudo apt install patchelf` and rerun last command again to solve it.
> 
> I test it on Ubuntu 22.04 amd64(VirtualBox) for my tensorflow project and it run well without issue.

This worked for me exactly as described by @tomneo2004. Thanks.

**Comment by tomneo2004** [comment]
> > @tilakrayal I built the TensorFlow yesterday successfully at night using the exact suggestion.
> > The difference is that the **whl** packing must be done in another step executing: `tensorflor/tools/pip_package/build_pip_package.sh --dst <destination_folder> --project_name <file_name_prefix>`
> > At this point, I realized that "//tensorflow/tools/pip_package:wheel" is just a convenience to build and packing all at once.
> 
> Hello. I am facing the exact same problem, and just to make things clear: are you suggesting that we should run the command: **1.** `bazel build //tensorflow/tools/pip_package:build_pip_package`
> 
> Then: **2.** `bazel build //tensorflor/tools/pip_package/build_pip_package.sh --dst <destination_folder> --project_name <file_name_prefix>` ?
> 
> I am a bit confused since running the 1st command generated a `.whl` file in `/tensorflow/bazel-bin/tensorflow/tools/pip_package/wheel_house`. The name of the file is `tensorflow_cpu-2.18.0-cp311-cp311-linux_x86_64.whl`
> 
> Although i am trying to build TF 2.13.0 in a Python 3.8 environment, the `.whl` file always has the same name as above with TF 2.18 and cp11 (CPython 11), what could be the source of this problem? I have already run `git checkout r2.13` to get the intended TF 2.13, but no matter what I do, it always generates `tensorflow_cpu-2.18.0-cp311-cp311-linux_x86_64.whl` ??!!

Have you found the solution for different python version? It seems that it automatically set python version to 3.11.

**Comment by CrocodileAhmad** [comment]
@tomneo2004 Assuming your environment has Python 3.8 (as an example), u have to specify the location of Python when you run the `./configure' script, as instructed here https://www.tensorflow.org/install/source#expandable-1. This should be done before building anything with bazel.

**Comment by tilakrayal** [comment]
@Ichimikichiki,
As mentioned please try to specify the python location in the ./configure and Could you try bazel clean --expunge followed by bazel sync.

https://www.tensorflow.org/install/source#expandable-1

Thank you!
