### ISSUE TITLE
Windows `uname -s` might return different values

### ISSUE THREAD

**Issue by zafartahirov** [tensorflow/tensorflow#6871]
[`configure#L14`](https://github.com/tensorflow/tensorflow/blob/73bc42890/configure#L14) checks if the system is Windows, but doesn't check `uname -s` values correctly according to the [wiki page](https://en.wikipedia.org/wiki/Uname#Examples).

Unless not supported, I think other Windows SDE's should be included in the check.

**Comment by zafartahirov** [comment]
@drpngx could you please check if #6872 solves it

**Comment by drpngx** [comment]
Yeah, I think that's fine. I'm not sure how far you can go with the build after that. The configuration that works is the cmake build.

**Comment by zafartahirov** [comment]
I wonder if there is a Windows system with `cygwin` and `uwin` in the Jenkins, because if there are none, bugs will not be caught even if enabled in the `configure`

**Comment by drpngx** [comment]
No, there isn't. We only check the cmake build.

**Comment by asimshankar** [comment]
Assigning to @drpngx since it seems that he's reviewing the PR
(Thanks @zafartahirov for the report and PR)

**Comment by gunan** [comment]
For windows, we currently do native compilation with cmake, (no cygwin).
Bazel setup for windows uses msys2, which is the closest thing we have to cygwin, but that also uses visual studio to compile TF.

**Comment by drpngx** [comment]
Fix submitted for this particular check.
