### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by sth4nth** [tensorflow/tensorflow#6876]
Run pip install tensorflow under python 3.6 get following:
 pip install tensorflow
Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow

**Comment by asimshankar** [comment]
I'm guessing you mean python 3.6?

We haven't finished testing with it just yet, so there are no releases for it. 

CC @martinwicke @gunan @yifeif - Will pips for py 3.6 be coming soon?

**Comment by sth4nth** [comment]
Yes, you are right. I've modified the title. Thanks.

**Comment by gunan** [comment]
Duplicate of #6876
Not in immediate plans, but we are considering py 3.6
Please follow instructions in the above issue to install for python 3.6.

**Comment by jerome-tan-git** [comment]
> # **_[](url)_**
