### ISSUE TITLE
TensorBoard variable name formatting

### ISSUE THREAD

**Issue by TimZaman** [tensorflow/tensorflow#6879]
Variable names in TensorBoard going from 0.12rc0 to the latest 0.12.1 do not support spaces and special characters anymore. 

I would like to have spaces and percentage signs (for example) supported (again).

Below should say: `cpu->gpus FIFO capacity %`

![image](https://cloud.githubusercontent.com/assets/7721540/21986760/5cbc0866-dc09-11e6-9f81-c4761af3cb90.png)

**Comment by asimshankar** [comment]
@dandelionmane @jart : Any thoughts on this?

**Comment by jart** [comment]
Do the following commit messages answer your question?

- https://github.com/tensorflow/tensorflow/commit/af1c9a17a4ae1b2cf1feee2e81e102433f5d09c1
- https://github.com/tensorflow/tensorflow/commit/02a3242748b73c43821900c01f0a3db3a2cf4c19

@dandelionmane may wish to comment more.

**Comment by aselle** [comment]
Closing due to lack of recent activity. Please update the issue if it persists and we will reopen.

**Comment by dandelionmane** [comment]
I'm going to add support for this back in, hopefully this quarter. Hang tight.
