### ISSUE TITLE
CPU version  AttributeError: 'module' object has no attribute ‘pack’

### ISSUE THREAD

**Issue by MalcolmSun** [tensorflow/tensorflow#6882]
when I was trying training a fcn with the latest cpu version tensoflow,I got an error:

> setting up vgg initialized conv layers ...
Traceback (most recent call last):
  File "FCN.py", line 285, in <module>
    tf.app.run()
  File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "FCN.py", line 154, in main
    pred_annotation, logits = inference(image, keep_probability)
  File "FCN.py", line 129, in inference
    deconv_shape3 = tf.pack([shape[0], shape[1], shape[2], NUM_OF_CLASSESS])
AttributeError: 'module' object has no attribute 'pack'

My tensorflow is installed from tensorflow-0.12.1-cp27-none-linux_x86_64.whl.  Seemingly there's no pack function of tf or in other module?

**Comment by asimshankar** [comment]
@MalcolmSun : Are you sure you're using 0.12.1 and not a nightly, 1.0.0-alpha or head build (you can confirm with a `print tf.__version__`)?
`tf.pack` should exist in 0.12.1 but has been replaced with `tf.stack` after that. 

So, regardless, switching to `tf.stack` should work (it is available in 0.12.1).
Do let us know if it really is 0.12.1 that is having this trouble.

**Comment by MalcolmSun** [comment]
@asimshankar Thanks for your help, the tf.__version__ is 0.12.head. After replaced by stack, the code encoutered another error:
`AttributeError: 'module' object has no attribute 'image_summary'`
Where can I find the API change log, so I can replace the old apis by myself. By the way, How can I install  tensorflow with a specified version. I only find the latest version in the install page.

**Comment by vrv** [comment]
@MalcolmSun try https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility to automatically upgrade your files -- let us know if that works.

**Comment by asimshankar** [comment]
@MalcolmSun 

- 0.12.head implies compiled from source, just FYI
- As @vrv pointed out, we have some tools to help with the upgrade but we also list out the breaking changes in [RELEASE.md](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md). Note that there is a bit of churn these days as we work towards 1.0. Once 1.0 is out, as per [semver](https://www.semver.org) (our [versioning policy](https://www.tensorflow.org/resources/versions)) things will be much more stable
- You can use `pip` support to install specific versions (e.g. `pip install "tensorflow==0.12.0"`)

**Comment by MalcolmSun** [comment]
@asimshankar @vrv  Thanks for your help. @vrv The tool works,thank you.
