### ISSUE TITLE
Rename parameter in Exponential distribution

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/tensorflow#6885]
Current

```python
distributions.Exponential(lam=2.0)
```
I had to think a bit before figuring out that `lam` stands for `lambda`. Following the MLP book I think a better name would be `rate` or `average_rate`. 

> This distribution describes the times between events in a process in which events occur continuously and independently at a constant average rate _lambda_ 

```python
distributions.Exponential(rate=2.0)
```

Numpy uses another parameterization: https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.exponential.html

**Comment by asimshankar** [comment]
@ebrevdo : Any thoughts on this?

**Comment by ebrevdo** [comment]
We're in the process of renaming all distribution params to English.

**Comment by yifeif** [comment]
Looks like the naming has been updated https://www.tensorflow.org/api_docs/python/tf/contrib/distributions/Exponential
Closing this issue.
