### ISSUE TITLE
Wrong explanation about an argument of tflite interpreter

### ISSUE THREAD

**Issue by illian01** [tensorflow/tensorflow#68862]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

Current master branch

### Custom code

No

### Current behavior?

I was using `tensorflow.lite.Interpreter`, and reading the comments to understand the parameters.
According to the comments, the `num_threads` value can be set to -1 or any non-negative value (or `None`).

https://github.com/tensorflow/tensorflow/blob/b297295711589c2d71880a046333e6ec095c6d7d/tensorflow/lite/python/interpreter.py#L409-L416

However, the actual code restricts that the `num_threads` value is set to 1 or higher (or `None`).

https://github.com/tensorflow/tensorflow/blob/b297295711589c2d71880a046333e6ec095c6d7d/tensorflow/lite/python/interpreter.py#L460-L464

### Standalone code to reproduce the issue

```shell
N/A
```

**Comment by tilakrayal** [comment]
@illian01,
Thank you for reporting the documentation issue. We have raised the PR for the changes which were suggested. The pr has been assigned for reviewing and once it is merged this issue will move to closed status.
https://github.com/tensorflow/tensorflow/pull/68866

Thank you!
