### ISSUE TITLE
How to load a graph with tensorflow.so and c_api.h in c++ language?

### ISSUE THREAD

**Issue by MisayaZ** [tensorflow/tensorflow#6889]
I can not find any example about how to load graph with tensorflow.so and c_api.h in c++ language.  I read the c_api.h , however, the ReadBinaryProto function was not in it. how can I load a graph without ReadBinaryProto function?

**Comment by asimshankar** [comment]
@MisayaZ : This is probably better asked on [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) as we try to keep the github issues focused on bugs and feature requests.

Please ask around there and I'm sure you'll find an answer.
