### ISSUE TITLE
log_cdf of Gaussian distribution returns -inf

### ISSUE THREAD

**Issue by Ardavans** [tensorflow/tensorflow#6891]
Hi all! It seems that the log_cdf for normal distribution (tf.contrib.distributions.Normal.log_cdf) returns -inf for some extreme values: 

```
from tensorflow.contrib.distributions import Normal
sess = tf.Session()
print sess.run(Normal(0., 1.).log_cdf(-6.0))
-inf 
```
However, with the same mu and sigma for scipy.stats.norm.log_cdf, you get the correct value of -20.7367. Is there something wrong with the tensorflow implementation of log_cdf?

Thanks!

**Comment by asimshankar** [comment]
@ebrevdo : Any thoughts on this?

**Comment by Ardavans** [comment]
It turns out that the issue is solved in the recent version of tensorflow.
