### ISSUE TITLE
get_matching_files issue

### ISSUE THREAD

**Issue by vv1133** [tensorflow/tensorflow#6893]
In [saver.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/saver.py), if the argument of `get_matching_files` is a relative path with no ./ in the beginning, `get_matching_files` will return an empty list. e.g., `get_matching_files("filename")` returns `[]`, while `get_matching_files("./filename")` returns `['filename']`

Thus when using [freeze_graph](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py) with input checkpoint in the same directory, I found the issue below:

```
python freeze_graph.py \
--input_graph=input_graph.pb \
--input_checkpoint=input.ckpt \
--output_graph=output_graph.pb \
--output_node_names=Softmax

Input checkpoint 'input.ckpt' doesn't exist!
```

**Comment by yaroslavvb** [comment]
Behavior in `file_io.py` that relies on Python's `Glob` is similar to functionality as it's reimplemented in `io_ops.cc`

IE, this works
```
filename_queue = tf.train.string_input_producer(["./file"])
_, serialized_example = reader.read(filename_queue)
```

This finds nothing
```
filename_queue = tf.train.string_input_producer(["file"])
_, serialized_example = reader.read(filename_queue)
```

**Comment by drpngx** [comment]
Got it. I think the PR was in the right direction, but depending on the `io_ops`, maybe in the wrong place. If it's a general bug in `io_ops`, then it should go there, otherwise, it should go in the wrapper code. The problem that I had was really about `./` which is not always portable. Do you want to resubmit the PR again?

**Comment by ppwwyyxx** [comment]
Seems related to this one: https://github.com/tensorflow/tensorflow/issues/4921

**Comment by drpngx** [comment]
Thanks @ppwwyyxx for the cross-reference! Yes, it's a peculiarity in the lookup. It does look odd.

**Comment by alextp** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
