### ISSUE TITLE
models/rnn/ptb not included in pip package

### ISSUE THREAD

**Issue by danmane** [tensorflow/tensorflow#69]

**Comment by danmane** [comment]
Apparently this is working as intended - in general models should be sourced from the repo, not the pip package.

**Comment by vrv** [comment]
So are our instructions incorrect somewhere?  We should update them if that's the case.

**Comment by ebrevdo** [comment]
People get confused because build_pip_package imports models/rnn/{rnn,rnn_cell,seq2seq}.  If/when we move these into python.ops.nn  (e.g. something like nn.rnn, nn.rnn_cell, nn.seq2seq); that should fix some of the confusion.

**Comment by vrv** [comment]
Agreed.  Until we are ready to support those interfaces indefinitely, is there something we should do to avoid that confusion?  Should we remove models/rnn from the pip package?

**Comment by ebrevdo** [comment]
No, they are the proper rnn/lstm implementation and should be made
available with the rest of the ops.

**Comment by evanthebouncy** [comment]
is this the reason why the rnn/lstm is not in the documentation under nn (in the api doc)?
it has been painful to learn how to use them.
If I were to use them should I expect their interface to change soon?
