### ISSUE TITLE
list of Ref(float) 

### ISSUE THREAD

**Issue by wchan** [tensorflow/tensorflow#690]
How do you REGISTER_OP with a list of Ref(float) as input, for example use the OpKernelContext::mutable_input_list to modify a list of inputs:

.Attr("y: int")
.Input("x: y * Ref(float)")

isn't working... how should I define it in the REGISTER_OP?

Thanks!

**Comment by girving** [comment]
Please ask questions like this on stackoverflow.  Github issues are for bugs and feature requests.  Also, whenever something isn't working, please include the error messages you're seeing.
