### ISSUE TITLE
tflite-runtime 2.11 python wheel for windows

### ISSUE THREAD

**Issue by akanarik** [tensorflow/tensorflow#69020]
1 of our products is a Windows service based on Python code, that needs tflite-runtime Interpeter in order to use a model that was developed and traind on full tensorflow 2.11.

we need tflite-runtime to in order to get smaller windows installation file

I see pip installation for tflite-runtime for Linux, but not for Windows
And I could not find working HowTo guid for building my own windows wheel from tensorflow source 

1. Are you planning to have tflite-runtime2.11 or later wheel for windows?
2. Would you be able to point me to any HowTo build windows wheel from tensorflow.lite source

Thanks
Amitai

**Comment by sushreebarsa** [comment]
@akanarik There's no official support for Windows wheels in tflite-runtime. Nightly builds might occasionally include Windows support for TFLite runtime. Could you try building your own wheel and explore pre-built TensorFlow binaries that might include TFLite runtime support on Windows? 
Please refer to [this](https://www.tensorflow.org/install/source) guide which provides a general overview of building TensorFlow from a source that includes TFlite as well. Also you may stay updated with TF releases [here](https://github.com/tensorflow/tensorflow/releases). 
For any further queries kindly post this issue in TF [forum](https://discuss.tensorflow.org/).
Thank you!
