### ISSUE TITLE
Sliding Window Layer

### ISSUE THREAD

**Issue by pribadihcr** [tensorflow/tensorflow#6902]
Hi,

Is there implementation the sliding window layer like in here: https://github.com/voidrank/caffe-fm/blob/2863b2a41e3f2114d24451f41eeed9ab618262ad/src/caffe/layers/sliding_window_layer.cu ?.

Thanks

**Comment by asimshankar** [comment]
This question is probably better asked on [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) as we try to keep the github issues focused on bugs and feature requests.
