### ISSUE TITLE
TF Lite. Cmake. Latest git repo fails to compile from source on windows.

### ISSUE THREAD

**Issue by roll-123** [tensorflow/tensorflow#69036]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

latest from git

### Custom code

No

### OS platform and distribution

Windows

### GCC/compiler version

MSVC 17.10

### Current behavior?

Tensorflow lite fails to compile on windows. 
MSVC compiler complains becuase designated initializers is a C++20 feature but cmake set the project to be C++17.

### Standalone code to reproduce the issue

```shell
In a terminal on windows: 
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow/tensorflow/lite
cmake -B tflite_build
cmake --build tflite_build
```

### Relevant log output

```shell
tensorflow/tensorflow/lite/core/c/operator.cc(28,29): error C7555: use of designated initializers requires at least '/std:c++20'
tensorflow/tensorflow/lite/delegates/xnnpack/weight_cache.h(276,7): error C7555: use of designated initializers requires at least '/std:c++20'
tensorflow/tensorflow/lite/delegates/xnnpack/weight_cache.cc(206,22): error C7555: use of designated initializers requires at least '/std:c++20'
tensorflow/tensorflow/lite/delegates/xnnpack/weight_cache.cc(210,30): error C7555: use of designated initializers requires at least '/std:c++20'
tensorflow/tensorflow/lite/delegates/xnnpack/weight_cache.cc(380,26): error C7555: use of designated initializers requires at least '/std:c++20'
tensorflow/tensorflow/lite/delegates/xnnpack/weight_cache.cc(383,26): error C7555: use of designated initializers requires at least '/std:c++20'
tensorflow/tensorflow/lite/delegates/xnnpack/weight_cache.cc(518,25): error C7555: use of designated initializers requires at least '/std:c++20'
```

**Comment by sawantkumar** [comment]
Hi @roll-123 ,

Let me replicate this issue and I will get back to you.

**Comment by thanhnguyentung95** [comment]
Change _set(CMAKE_CXX_STANDARD 17)_ in **CMakeLists.txt** to _set(CMAKE_CXX_STANDARD 20)_ worked for me.

**Comment by sawantkumar** [comment]
Hi @roll-123 ,

Can you try changing the set(CMAKE_CXX_STANDARD 17) in CMakeLists.txt to set(CMAKE_CXX_STANDARD 20) and let me know if it worked for you.

**Comment by roll-123** [comment]
Hi @sawantkumar, 

It actually looks like it compiles fine now with CXX 17. Thanks!
