### ISSUE TITLE
error in computing fft of a float variable

### ISSUE THREAD

**Issue by raady07** [tensorflow/tensorflow#6904]
Python 3.5
tensorflow GPU

I am unable to compute the 1 D fft. My input values will be positive and negative float values not complex numbers.
`x = tf.Variable([1.2,2,3,4.1,5.9],dtype=tf.float32)
sess.run(tf.fft(x))`
the error that i get

`TypeError:Input 'input' of 'FFT' Op has type int32 that does not match expected type of complex64`

I have tried 
`sess.run(tf.batch_fft(x))`

but it gives an error as tensorflow has no module batch_fft. 
did I miss any thing in the installation of tensorflow ??

I tried declaring these variables dtype=tf.complex64

it gave another error
`InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'FFT' with  these attrs.  Registered kernels:
  <no registered kernels>
	 [[Node: FFT = FFT[](Variable/read)]]`

**Comment by asimshankar** [comment]
This question is probably better addressed on [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) as we try to keep the github issues focused on bugs and feature requests, so closing it out here (also, please do provide all the details asked for in the new issue template, such as TensorFlow version, OS, steps-to-reproduce etc.)
