### ISSUE TITLE
Wheels are far behind on tensorflow.org

### ISSUE THREAD

**Issue by jkschin** [tensorflow/tensorflow#691]
Hi there,

I'm new to GitHub contributions so let me know if I'm wrong in posting this here.

I have installed both TensorFlows (CPU and GPU) on Ubuntu 14.04 using pip. I faced many problems and then realized that the wheels on the <a href src="https://www.tensorflow.org/versions/master/get_started/os_setup.html">TensorFlow website</a> are quite outdated. The source on GitHub is moving really quickly. In particular, the GPU version does not have stuff like the configure file, among many others.

I then downloaded from source and built the wheels locally. Is there any intention to update the TensorFlow website soon? I can help to solve this issue too so let me know how I can help.

**Comment by martinwicke** [comment]
We will release new versions of the wheels when we release a new version of tensorflow. As you note, the code moves quite quickly, and so the wheels seem stale, but the last release is not even a month old. We're still working on our automated testing setup and we'll probably make new binaries shortly after.
