### ISSUE TITLE
Feature Request: Allow disabling the use of host pinned memory

### ISSUE THREAD

**Issue by gibiansky** [tensorflow/tensorflow#6910]
Right now, TensorFlow will always use pinned memory (allocated by the stream executor with `cuMemHostAlloc`) whenever it knows that a tensor will need to be transferred to the GPU (or something like that).

When a TensorFlow process crashes (does not exit gracefully) due to segfaults or other unforeseen circumstances, the PoolAllocator destructor is not called, and the pinned memory is not freed. When pinned memory is not freed, the CUDA driver does not actually release it, and so memory usage grows over time if you have processes that are not exiting gracefully. After this happens for a while, the machine needs to swap and/or runs out of pinned memory, and if there is no swap space enabled, the node dies (and the only way to recover it is a hard-reboot, not accessible via the network).

As far as we can tell, there is no workaround to this, and we simply need to disable the pinned memory allocator if we want to be absolutely certain that this cannot happen. Right now, TensorFlow does not allow you to do so.

Proposal: There is currently an environment variable called `TF_CUDA_HOST_MEM_LIMIT_IN_MB` which used to set a maximum size for the `BFCAllocator` that does CUDA host memory allocation. In order to implement this feature, we would check whether the value of that environment variable is zero, and, if it is zero, use a non-pinned memory allocator as the sub-allocator for the BFCAllocator.

Is that acceptable?

[This](https://github.com/tensorflow/tensorflow/issues/3701) issue was probably related.

**Comment by asimshankar** [comment]
@zheng-xq @vrv  : Any suggestions for workarounds here?

**Comment by vrv** [comment]
That seems reasonable to me, though I wonder if there's another way to get the allocators cleaned up on destruction.  I'm not entirely sure why the ProcessState singleton needs to own the allocators, but I'll find out.

**Comment by vrv** [comment]
@zheng-xq and I chatted offline, it sounds like this is an NVidia driver bug -- @gibiansky do you have the ability to upgrade your nvidia driver?

We also might prefer having another env var instead of giving double duty to this one.

**Comment by gibiansky** [comment]
We do but it's a very large amount of effort as it requires an upgrade to the entire cluster. Are you sure this is fixed in newer drivers? We're running 361.93.02 from mid-October of 2016, which is after the issue I linked to was resolved.

**Comment by vrv** [comment]
I remember hearing it's fixed in 367.*, but I'm not sure.  Just mentioning it as an option to test out, since I'm sure neither of us want to add more code/config if we can avoid it :)

**Comment by gibiansky** [comment]
After testing this more thoroughly with just calls to CUDA runtime APIs, we cannot confirm that the pinned memory allocator is causing this problem. I'm closing this issue until (and if) we can confirm that pinned memory is causing our issues.

Thanks!
