### ISSUE TITLE
Pip installation failing

### ISSUE THREAD

**Issue by kevinzakka** [tensorflow/tensorflow#6912]
Fresh python3 install using `brew install python3`.

When I run `pip3 install tensorflow`, I get a 

`Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow`

I've tried reinstalling python but I get the same error message.

**Comment by raady07** [comment]
this might help 
[http://stackoverflow.com/questions/38896424/tensorflow-not-found-in-pip](url)

**Comment by yaroslavvb** [comment]
This kind of installation support is generally better handled on stackoverflow, hence closing. Feel free to reopen if you think there's a bug in tensorflow installation procedure, in which case, please fill out the template/provide more details
