### ISSUE TITLE
Binaries should target CUDA architectures 6.0, 6.1 to avoid long delays on startup

### ISSUE THREAD

**Issue by benbarsdell** [tensorflow/tensorflow#6914]
The public docker images and pip packages are not compiled against CUDA architecture 6.0 or 6.1, which can cause a delay of more than a minute during initialization when executed on corresponding hardware (P100, GTX 10 series etc.) as the CUDA driver runs JIT compilation on all of the internal kernels.

Given that the public binaries are now built against CUDA 8.0, it would make sense to have them target archs 6.0 and 6.1.

Minimal reproducer (run with CUDA_CACHE_DISABLE=1):

```
import tensorflow as tf
sess = tf.Session()
rand_init = tf.random_uniform([32, 8], -1.0, 1.0)
rand_var  = tf.Variable(rand_init)
init = tf.global_variables_initializer()
sess.run(init)
```

### Related issues
https://github.com/tensorflow/tensorflow/issues/3651

### Environment info
Operating System: Linux

**Comment by vrv** [comment]
Gunhan, how hard would it be to do for our pip releases ?

**Comment by vrv** [comment]
@martinwicke

**Comment by vrv** [comment]
cc @yifeif too

**Comment by gunan** [comment]
Not that difficult, but this came up before and the result was to limit our pip packages to 2 cuda compute capabilities. 3.0, we wont drop.
if we do 6.1, we will drop 5.2
We will see a worse degradation for more people IMO once we do that.

**Comment by vrv** [comment]
Let's chat more, I think we have to figure out a way to distribute (potentially large) binaries that works for more people.

@benbarsdell : what do other frameworks do?  Do they release binaries that contain the code for every possible compute capability under the sun too?

**Comment by cliffwoolley** [comment]
My recommendation would be to include, minimally, 3.5, 5.2, 6.0, and 6.1.  Since you also want 3.0, then that makes five.

Compute capability 3.7 is ISA-identical to 3.5; only the on-chip resources increased, so it's only in specific circumstances that building 3.7 separately is worthwhile, and I'd say it's fair to skip it here.  Compute capability 5.0 was first-gen Maxwell (GM10x), and the only chips in that line were on the smaller end of the spectrum -- most people doing compute went straight from Kepler (3.x) to the 2nd-gen Maxwell (GM20x, aka compute capability 5.2).

The only other ones that exist that I've omitted are the ones for mobile GPUs.

**Comment by vrv** [comment]
Thanks @cliffwoolley, very helpful!  From what Martin told me, the current issue is that pypi has a limitation on the size of the pips, and adding those two compute capabilities will probably bloat the size of the GPU pip wheel to something too large.  So I wish I could say this is trivial to change, but it might require some more work on the pip/pypi side first.

**Comment by mkolod** [comment]
@vrv Here's another idea. The issue has to do more with Docker containers than with pip packages uploaded to pypi. The dev container build runs Bazel explicitly, while the non-dev container build pulls the pip package from pypi. Perhaps the builds can be set up in such a way that the non-dev container also builds from source and adds the compute capabilities mentioned by @cliffwoolley, while the pip build to be pushed to pypi is done separately, and constrains the compute capabilities so as to satisfy pypi's space limitations? That way, at least all Docker users would have more compute capabilities so as to limit the dependence on the JIT, and only bare-metal pip users would be affected by the JIT the first time on Pascal GPUs?  Just an idea.

**Comment by vrv** [comment]
Yup, that's a reasonable solution too, and something that could be done pretty quickly.  

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.devel-gpu#L92  Can you try editing that to add 6.0,6.1 and see if the immediate problem gets resolved?  (Feel free to send us a PR if so).

In the meantime, we'd like to make this also available for our non-docker folks, so we'll also work on that if we can.

**Comment by mkolod** [comment]
@vrv Great! See [PR #6941](https://github.com/tensorflow/tensorflow/pull/6941).

**Comment by ekelsen** [comment]
Another solution could be to separate the binaries based on the compute capabilities they support.  We already release many binaries...so I'm not sure if this would be considered crossing the line to too many.

**Comment by gunan** [comment]
Due to constraints on our pip package sizes, this is currently infeasible.
However we are working on a few longer term initiatives which may tackle this issue too.
