### ISSUE TITLE
 How to init the graph once and reuse the graph to serve all the requests

### ISSUE THREAD

**Issue by FangJianHust** [tensorflow/tensorflow#6917]
I want to provide a restful api or rpc for client to input some pictures and output their features, but every request will start a new graph and load all train variables from the disk, and this is very slow, how can I init the graph once and reuse the graph to serve all the requests, Thank You for your help

**Comment by yaroslavvb** [comment]
Could you please ask this on stackoverflow? This list is for tensorflow bugs/feature requests
