### ISSUE TITLE
How to read saved model

### ISSUE THREAD

**Issue by lglhuada** [tensorflow/tensorflow#692]
I have trained a model, and I would like to write a code file implemented with C++. I know how to restore model with tf.train.Saver().restore() function, while how to get the values of parameters of trained model? Thanks in advance.

**Comment by koth** [comment]
Load the graph first, call the 'restore_all' subgraph will restore your variables from a checkpoint file

**Comment by girving** [comment]
This is a better question for stackoverflow.  Github issues are for bugs or feature requests.

**Comment by lglhuada** [comment]
@koth  thanks for your information :+1:
