### ISSUE TITLE
can tensorflow CPU version be updated to GPU version without uninstalling ?

### ISSUE THREAD

**Issue by raady07** [tensorflow/tensorflow#6920]
python 3.5 
tensorflow 0.11.0
Hello,
I wanted to do FFT operations using tensorflow. does this CPU version support working of that ? 

In some post I have seen we cannot perform FFT on CPU version of tensorflow. If so can I change the tensorflow version of CPU to GPU without installing it ? 

I need to work on the LSTM algorithm as well further.

**Comment by yaroslavvb** [comment]
This seems like a much better question for stackoverflow, this tracker is for bugs/feature requests in the tensorflow itself
