### ISSUE TITLE
Efficientdet models do not work on hexagon delegate

### ISSUE THREAD

**Issue by Hozzu** [tensorflow/tensorflow#69234]
**System information**
Tensorflow lite v2.16.1
Hexagon library 1.20.0.1

**Standalone code to reproduce the issue**
I generated efficientdet normal and lite int8 models from automl github.
https://github.com/google/automl/blob/master/efficientdet/tf2/tutorial.ipynb

The models work well on CPU, but do not work on hexagon delegate.
When I put the same input value, the output of the hexagon delegate is invalid value.

**Any other info / logs**
I attached the efficientdet lite0 int8 model as a sample.
https://1drv.ms/u/s!AnqHHtrBqwyUg8N31bJmQjMmrF9QnA?e=lmvIdI

**Comment by sawantkumar** [comment]
Hi @Hozzu ,

I don't have a device with hexagon delegate so i tried it out on the neuron delegate by mediatek and it failed there also wit the error:
`java.lang.IllegalArgumentException: Cannot copy from a TesorflowLite tensor (statefulPartitonedCall_2:1) with 400 bytes to a Java Buffer with 100 bytes.`

Can you please provide your crash logs from the hexagon delegate?

**Comment by Hozzu** [comment]
> Hi @Hozzu ,
> 
> I don't have a device with hexagon delegate so i tried out your model on the neuron delegate by mediatek and it failed there also wit the error: `java.lang.IllegalArgumentException: Cannot copy from a TesorflowLite tensor (statefulPartitonedCall_2:1) with 400 bytes to a Java Buffer with 100 bytes.`
> 
> Can you please provide your crash logs from the hexagon delegate?

Hello.
It does not crash.
It runs but the output value is invalid.

When I use cpu or gpu delegate, the output values are valid.
But when I use hexagon delegate, the output value is different from the cpu and gpu ones and invalid.

The other models like yolov8 and mobilenet v2 work well on hexagon delegate.
However, efficientdet which made from google does not work on the hexagon delegate.

![image](https://github.com/user-attachments/assets/7eb49c64-4c87-45f2-a85f-1a4858749cd9)

**Comment by sawantkumar** [comment]
Hi @pkgoogle ,

Can you please take a look ?

**Comment by pkgoogle** [comment]
I also do not have a device that can properly reproduce this, @arfaian can you please take a look? Thanks.
