### ISSUE TITLE
Tensorflow lite conversion fails for keras model in TensorFlow version: 2.16.1

### ISSUE THREAD

**Issue by vmanoj1996** [tensorflow/tensorflow#69237]
### 1. System information

- OS Platform and Distribution : Linux Ubuntu 22.04
- TensorFlow installation (pip package or built from source): pip package 
- TensorFlow library (version, if pip package or github SHA, if built from source):  2.16.1

### 2. Code

```
import tensorflow as tf
import pdb
print("TensorFlow version:", tf.__version__)

class network(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.conv1 = tf.keras.layers.Conv2D(filters=2, kernel_size=3, strides=2, activation='relu')

    def call(self, x):
        x = self.conv1(x)

        return x
    
model = network()

inp  = tf.keras.Input(shape=(28, 28, 1))
out = model(inp)
model.build(input_shape=(None, 28, 28, 1))

model.summary()

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tfliteModel = converter.convert()
```

### Output

```
LLVM ERROR: Failed to infer result type(s).
Aborted (core dumped
```

[ouptut.txt](https://github.com/user-attachments/files/15592694/ouptut.txt)

**Comment by vmanoj1996** [comment]
The [original issue](https://github.com/tensorflow/tensorflow/issues/62610) is closed now

**Comment by sawantkumar** [comment]
Hi @vmanoj1996 ,

Right now, TF2.16 has an issue with Keras 3.0. As a workaround install Keras 2 as follows.
```py
pip install -U tf_keras # Keras 2
import os
os.environ["TF_USE_LEGACY_KERAS"] = "1"
``` 

Please check this [gist](https://colab.sandbox.google.com/gist/sawantkumar/af6504f86fba03c32da7fc94d3689208/tflite_64515_2-16.ipynb#scrollTo=8WdnhCSMVw-H)  and let me know if the problem persists.
