### ISSUE TITLE
Unable to build TensorFlowLite GPU Delegate for Android

### ISSUE THREAD

**Issue by cpappasILMX** [tensorflow/tensorflow#69252]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15

### Custom code

No

### OS platform and distribution

Android

### Mobile device

Android

### Python version

3.9

### Bazel version

7.1.2

### GCC/compiler version

Apple Clang 15.0.0

### Current behavior?

On a Mac machine, I am trying to build the tensorflow-lite gpu delegate for android. I have followed the build instructions without docker found at https://www.tensorflow.org/lite/android/lite_build to build tflite for android and was successful. I attempted to build the native gpu delegate as a shared library as well following the instructions found at https://www.tensorflow.org/lite/android/delegates/gpu_native. The goal is to build the delegate as a shared library to simply copy over into my own project.

The problem appears to be when building a dependency of the delegate, dependency declarations are missing.

### Standalone code to reproduce the issue

```shell
TF_LITE_TARGET_NDK_VERSION_DIRECTORY=$(ls -1 /Users/$USER/Library/Android/sdk/ndk/ | tail -n 1)
export ANDROID_NDK_HOME="/Users/$USER/Library/Android/sdk/ndk/26.3.11579264"
export ANDROID_SDK_API_LEVEL="34"
export ANDROID_NDK_API_LEVEL="26"

# AndroidConfiguration is a simple text file to auto fill the queries from the provided configure script
./configure < AndroidConfiguration

bazel build -c opt --config android_arm64 tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so
```

### Relevant log output

```shell
/private/var/tmp/_bazel_user/897db67e3896f5db6d832aa86833dcea/external/XNNPACK/BUILD.bazel:2884:19: Compiling src/operators/convolution-nchw.c failed: undeclared inclusion(s) in rule '@XNNPACK//:operators':
this rule is missing dependency declarations for the following files included by 'src/operators/convolution-nchw.c':
  'external/androidndk/toolchains/llvm/prebuilt/darwin-x86_64/lib/clang/17/include/limits.h'
  'external/androidndk/toolchains/llvm/prebuilt/darwin-x86_64/lib/clang/17/include/float.h'
  'external/androidndk/toolchains/llvm/prebuilt/darwin-x86_64/lib/clang/17/include/stdbool.h'
  'external/androidndk/toolchains/llvm/prebuilt/darwin-x86_64/lib/clang/17/include/stddef.h'
  'external/androidndk/toolchains/llvm/prebuilt/darwin-x86_64/lib/clang/17/include/stdint.h'
  'external/androidndk/toolchains/llvm/prebuilt/darwin-x86_64/lib/clang/17/include/stdarg.h'
  'external/androidndk/toolchains/llvm/prebuilt/darwin-x86_64/lib/clang/17/include/inttypes.h'
Target //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so failed to build
```

**Comment by sushreebarsa** [comment]
@cpappasILMX Please make sure that Android NDK has a version compatible with your target Android API level.
Bazel build system. Could you check TensorFlow [documentation](https://www.tensorflow.org/lite/api_docs/java/org/tensorflow/lite/gpu/package-summary) for specific version requirements for these tools for building the GPU Delegate?
Thank you!

**Comment by cpappasILMX** [comment]
I was able to build the gpu delegate using NDK version 25 with NDK API Level set to 26.
