### ISSUE TITLE
support for depth pooling in maxpool3d?

### ISSUE THREAD

**Issue by odellus** [tensorflow/tensorflow#6925]
Is depth pooling in the works for MaxPool3D? Any pointers on how I should/could get this going myself? 
```
UnimplementedError (see above for traceback): Pooling is not yet supported on the depth dimension.
[[Node: max_pool_1 = MaxPool3D[T=DT_FLOAT, ksize=[1, 2, 2, 2, 64], padding="VALID", strides=[1,
 1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/gpu:0"](Relu_1)]]
```
Here's an example of how I'm using it:
```Python
def maxpool3d(input_, kd, kh, kw, stride=1,scope=None):
    input_cdim = input_.get_shape().as_list()[-1]
    batch_size = input_.get_shape().as_list()[0]
    kernel = [batch_size, kd, kh, kw, input_cdim]
    return tf.nn.max_pool3d(input_, kernel,
        strides=[1,stride,stride,stride,1], padding="VALID", name=scope)
# ...
# Perform 2 3D convolutions without max pooling.
x = tf.nn.relu(conv3d(x, 4, 4, 4, 64, scope="conv_1"))
x = tf.nn.relu(conv3d(x, 4, 4, 4, 64, scope="conv_2"))

# Downsample with max pooling.
x = maxpool3d(x, 2, 2, 2, scope="max_pool_1")
```

**Comment by asimshankar** [comment]
@mjanusz @vrv @zheng-xq : Any comments here?

**Comment by vrv** [comment]
I don't know of anyone working on it, would be a nice contribution.

I don't know whether cudnn supports pooling along this dimension, but if it does, it should be possible to relax this constraint.  But you'd have to find out by looking at the cudnn pooling API to see whether it is possible to pool across spatial dimensions and depth dimension at the same time.

I'm sure Eigen's implementation of 3d pooling (CPU) doesn't do simultaneous pooling across more than the spatial dimensions, and it would probably be a lot of work to enable this.

For now, to get your work done: maybe first maxpool across the spatial dimensions, reshape / transpose the tensor and then maxpool across the depth dimension, followed by a final reshape / transpose.  It's unlikely that someone is going to add this on our side any time soon.

**Comment by odellus** [comment]
Thanks for the info Vijay. The depth dimension *is* a spatial dimension with the volumetric data I'm working with. I'll be sure to look more closely into the cudnn api on 3D pooling. Thanks again!

**Comment by vrv** [comment]
Indeed, I didn't come up with the name :) By Spatial, Eigen refers to 'planes, rows, columns', with 'depth' not being part of the spatial dimension, based on the API.

**Comment by odellus** [comment]
All of this helps Vijay. Thank you for spelling that out for me.

**Comment by JaeDukSeo** [comment]
any updates...?

**Comment by mjanusz** [comment]
There is no active work on pooling over the "channels" dimension that I'm aware of. Note that pooling works over all 3 spatial dimensions. The code of the OP should read:

kernel = [1, kd, kh, kw, 1]

  instead of:

kernel = [batch_size, kd, kh, kw, input_cdim]

in order to accomplish this.
