### ISSUE TITLE
Build from source C doesn't produce .tar.gz archive

### ISSUE THREAD

**Issue by erik-fauna** [tensorflow/tensorflow#69266]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.16

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04 (arm64)

### Bazel version

6.5.0

### GCC/compiler version

gcc

### Current behavior?

The readme within the the [lib_package](https://github.com/tensorflow/tensorflow/tree/r2.16/tensorflow/tools/lib_package) folder indicates that a tar.gz archive should be created upon building with bazel to finish installation. Currently trying to build on arm64 architecture (jetson orin) as there are no docker images on dockerhub for Tensorflow C with that architecture. I would have preferred to use 2.15 to stay the same as the version used by the [amd64 desktops](https://www.tensorflow.org/install/lang_c), but that failed to build because of stubs being too large (using bazel 6.1.0, gcc, cxxopt flag used).

There are no logs because the build claims it completed successfully, there are the usual shared library files within `bazel-bin/tensorflow`, but porting them and all the dependencies to the right locations sounds like a nightmare.

Any thoughts why the archive isn't being built?

### Standalone code to reproduce the issue

```shell
cd ~/workspace
wget https://github.com/bazelbuild/bazel/releases/download/6.5.0/bazel-6.5.0-linux-arm64
chmod +x bazel-6.5.0-linux-arm64
git clone https://github.com/tensorflow/tensorflow
cd ./tensorflow
git checkout r2.16 #may need to change the number of jobs that can run at once
../bazel-6.5.0-linux-arm64 build --jobs=12 --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=1" -c opt //tensorflow:libtensorflow.so //tensorflow:libtensorflow_cc.so //tensorflow:libtensorflow_framework.so //tensorflow:install_headers
```

**Comment by sushreebarsa** [comment]
@erik-fauna Bazel allows for conditional build rules based on configurations like target architecture. It's possible the archive creation step is defined only for specific architectures (e.g., amd64). 

```
bazel build --verbose_failures //lib_package:your_target

```
Kindly replace `your_target` with the specific build target defined in the Bazel files.
Thank you!

**Comment by erik-fauna** [comment]
I see that there are some differences in the build commands defined in the lib_package, so I've made some adjustments to my build line. It should finish building by the morning, so I can report back then. I added the verbose_failures flag as well.

**Comment by sushreebarsa** [comment]
@erik-fauna Yes, please! Let us know kindly.
Thank you!

**Comment by sushreebarsa** [comment]
@erik-fauna Please let us know if the issue got resolved and if not then kindly share the error log to analyze the issue?
Thank you!

**Comment by erik-fauna** [comment]
Using the code from my previous comment, the bug that I specifically raised this issue about is resolved. I haven't tested the other packages to confirm those work, but will raise another issue if they don't, as it's not exactly the same issue seen here.
