### ISSUE TITLE
Is Python 3.3 still supported?

### ISSUE THREAD

**Issue by hugovk** [tensorflow/tensorflow#6930]
Docs say Python 3.3 is supported.

https://www.tensorflow.org/versions/r0.10/get_started/os_setup says:

> The TensorFlow Python API supports Python 2.7 and Python 3.3+.

I'm not too bothered about Python 3.3, but if it's no longer supported, please update the docs.

### Environment info
Travis CI
Operating System: Ubuntu 14.04.5 LTS
Python 3.3.6
pip 8.1.2

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

```
$ pip install tensorflow
Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow
```

**Comment by asimshankar** [comment]
@gunan @yifeif : I believe this is a docs error? We release pip packages for Python 3.4 and 3.5 only, but is the API compatible with 3.3 (built from sources?)

**Comment by gunan** [comment]
If you are building from sources, I dont see a reason why it wont work with py3.3
Our binaries are only for py3.4 and py3.5

How about this, could you try manually downloading python 3.4 or 3.5 wheel file, rename it by replacing all occurences of "34" (or "35") in the name to "33". Then install that downloaded package.
For 3.6, users reported that this works, it might work as well for python 3.3

**Comment by yifeif** [comment]
@hugovk we have uploaded 3.3 binary to pypi. Could you give it another try?

**Comment by hugovk** [comment]
The 3.3 wheel is pip installing and with a quick test is working fine. Thank you!

```
$ pip install tensorflow
Collecting tensorflow
  Downloading tensorflow-0.12.1-cp33-cp33m-manylinux1_x86_64.whl (43.1MB)
    100% |████████████████████████████████| 43.1MB 33kB/s 
Collecting protobuf>=3.1.0 (from tensorflow)
  Downloading protobuf-3.1.0.post1-py2.py3-none-any.whl (347kB)
    100% |████████████████████████████████| 348kB 793kB/s 
Requirement already satisfied: wheel>=0.26 in /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages (from tensorflow)
Requirement already satisfied: numpy>=1.11.0 in /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages (from tensorflow)
Requirement already satisfied: six>=1.10.0 in /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages (from tensorflow)
Requirement already satisfied: setuptools in /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages (from protobuf>=3.1.0->tensorflow)
Installing collected packages: protobuf, tensorflow
Successfully installed protobuf-3.1.0.post1 tensorflow-0.12.1
```
