### ISSUE TITLE
Tensorflow builds on Windows are broken

### ISSUE THREAD

**Issue by vladmos** [tensorflow/tensorflow#6931]
The corresponding build projects are red on both Tensorflow CI (http://ci.tensorflow.org/job/tf-master-win-bzl/) and Bazel CI (http://ci.bazel.io/job/TensorFlow/).

**Comment by drpngx** [comment]
It's trying to access an `install` file. Not sure what this could be. @zheng-xq it looks like it broke last week.

**Comment by gunan** [comment]
Internally there is a fix, but we have not been able to make a successful push due to other breakages.

**Comment by vladmos** [comment]
Unfortunately both CIs are still red, I think it should be reopened.

**Comment by gunan** [comment]
Sorry, that was an Auto-close due to fix <issue> pattern.

**Comment by gunan** [comment]
Some more fixes in. Now looking into tensorforest issues on GPU.
Looks like they arrived broken.
Will see how I can triage them.

**Comment by gunan** [comment]
We have decided to disable contrib tests that were failing for now, as contrib does not have official support.
They will be disabled until contrib library (tensor_forest) owners triage those bugs separately.

This bug now should be fixed. (The remaining issues will be tracked separately).
