### ISSUE TITLE
MobileNetV3 quantization

### ISSUE THREAD

**Issue by DaraOrange** [tensorflow/tensorflow#69311]
Hi! I'm trying to quantize MobileNetV3 with tflite, but int8-model performs very poor. I think, it is because of linear quantization, which is too simple method not appropriate for any weights distributions. What else can I try? Are you going to support logarithmic scale for quantization in the future?

**Comment by AngelicSage** [comment]
You might want to look into Quantization-Aware Training

**Comment by DaraOrange** [comment]
I think no, because I train Pytorch models and then convert them to onnx and tflite

**Comment by sawantkumar** [comment]
Hi @DaraOrange , this issue may be resolved by following a different work flow.

Have you tried using [AI-Edge-Torch](https://github.com/google-ai-edge/ai-edge-torch)?, you can find more information here: [googleblog](https://developers.googleblog.com/en/ai-edge-torch-high-performance-inference-of-pytorch-models-on-mobile-devices/).

I have actually created a simple script for converting a CV model here:

```
import torch
import torchvision
import ai_edge_torch

mobilenet_model = torchvision.models.mobilenet_v3_small()
sample_inputs = (torch.randn(1, 3, 224, 224),)

edge_model = ai_edge_torch.convert(mobilenet_model.eval(), sample_inputs)
edge_model.export("mobilenet_v3_small.tflite")
```
If you want to, you can actually try visualizing the result in [model-explorer](https://github.com/google-ai-edge/model-explorer) as well.

Please try them out and let us know if this resolves your issue. If you still need further help, feel free to open a new issue at the respective repo.

**Comment by DaraOrange** [comment]
I have no problems with conversion, but results after quantization are poor. Does this tool support quantization?

**Comment by pkgoogle** [comment]
Hi @DaraOrange, correct: these are the only options available: https://www.tensorflow.org/lite/performance/model_optimization, can you provide the data for us for, "results after quantization are poor".

**Comment by vikramdattu** [comment]
@DaraOrange did you find the solution for the issue?
