### ISSUE TITLE
layers.core.Dense doesn't make use of argument activity_regularizer

### ISSUE THREAD

**Issue by nryant** [tensorflow/tensorflow#6932]
As it says on the tin, the ``Dense`` class of ``tensorflow.python.layers.core`` accepts an ``activity_regularizer`` argument, but never makes use of this argument. Not sure if this is intentional or an oversight, so pointing it out.

**Comment by asimshankar** [comment]
I believe it does get used by a call in the parent class (see [`python/layers/base.py:270`](https://github.com/tensorflow/tensorflow/blob/1288301651c2e9610202a8657ff569ac4bf5392f/tensorflow/python/layers/base.py#L270)).

Closing this out. CCing @fchollet in case I have misunderstood and he wants to reopen this.
