### ISSUE TITLE
cuDevicePrimaryCtxSetFlags not found issue on Windows 7

### ISSUE THREAD

**Issue by sunpy02** [tensorflow/tensorflow#6933]
I have successfully loaded tensorflow in python 3.5. But when I start a session, it gave me the following error and python will crash:

>>> import tensorflow as tf
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\dso_loader.cc:128] successfully opened CUDA library cublas64_80.dll
locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\dso_loader.cc:128] successfully opened CUDA library cudnn64_5.dll lo
cally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\dso_loader.cc:128] successfully opened CUDA library cufft64_80.dll l
ocally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\dso_loader.cc:128] successfully opened CUDA library nvcuda.dll local
ly
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\dso_loader.cc:128] successfully opened CUDA library curand64_80.dll
locally
>>> sess = tf.Session()
F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stre
am_executor\cuda\cuda_driver.cc:94] Check failed: s.ok() could not find cuDevice
PrimaryCtxSetFlags in libcuda DSO; dlerror: cuDevicePrimaryCtxSetFlags not found

My graphic card is NVDIA  quadro K1100M with cuda compute capability 3.0. I have cuda toolkit 8.0 and cudnnv5.1 installed. I tried different nvdia drivers but none is working. If the driver is too old, it will give me insufficient version number to be used with cuda. If the drive is new, my computer just freeze and saying the graphic card is not removable or cannot ejected. Could someone help me with this? Thanks.

**Comment by asimshankar** [comment]
This questions is probably better asked on [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) as we try to keep the github issues focused on bugs and feature requests.

Closing this out here.

(FYI @mrry)
