### ISSUE TITLE
Download and setup instructions issue, incorrect version of CuDNN

### ISSUE THREAD

**Issue by fantauzzi** [tensorflow/tensorflow#6934]
[Instructions](https://www.tensorflow.org/get_started/os_setup) indicate to use CuDNN 5 with Tensorflow for GPU with CUDA Tookit 8.0 and Python 3.5 under Ubuntu/Linux. After doing that, when using the Tensorflow Python API I get a run-time error:

`E tensorflow/stream_executor/cuda/cuda_dnn.cc:378] Loaded runtime CuDNN library: 5005 (compatibility version 5000) but source was compiled with 5105 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.`

and the computation stops.

If instead I use CuDNN 5.1, the computation goes through correctly.

I have installed Tensorflow 0.12.1 for Python 3.5 with GPU with:

`sudo -H pip3 install tensorflow-gpu`

under Ubuntu 16.04 64-bit.

```
> python3 -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
0.12.1
```

[Here](https://github.com/Hvass-Labs/TensorFlow-Tutorials/blob/master/02_Convolutional_Neural_Network.ipynb) a program that can be used to reproduce the issue.

I believe installation instructions should be updated to reference CuDNN 5.1.

**Comment by vrv** [comment]
The instructions seem to say to use cudnn v5.1 in most places -- are you confused by the one or two places that say 'v5' without qualifying the minor version?

**Comment by fantauzzi** [comment]
I had used CuDNN v5 at first based on this:

```
# Ubuntu/Linux 64-bit, GPU enabled, Python 3.5
# Requires CUDA toolkit 8.0 and CuDNN v5. For other versions, see "Installing from sources" below.
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.1-cp35-cp35m-linux_x86_64.whl
```

I didn't notice that elsewhere it says 5.1.

**Comment by vrv** [comment]
Sent a PR.
