### ISSUE TITLE
Leave old binaries up?

### ISSUE THREAD

**Issue by rueberger** [tensorflow/tensorflow#6939]
I've noticed that the binaries for older versions have been taken down. In particular, I need to install 0.11.rc0 and both 

`https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.11.rc0-cp27-none-linux_x86_64.whl`

and

`https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.11.0-cp27-none-linux_x86_64.whl`

are 404s. Pretty sure they used to work when 0.11.rc0 was the latest though. 

Were they intentionally taken down to prevent people from unwittingly installing older versions? That would be understandable, but it would be really nice if there was an easy way to access older binaries. Greatly looking forward to the release of 1.0, but for the time being there's a nest of dependency conflicts to manage and that's difficult when it's not clear how to install old versions!

**Comment by asimshankar** [comment]
I believe the naming convention changed (CCing @yifeif @gunan  to confirm) between 0.11 and 0.12, but the URLs of the earlier releases are still accessible. For example:

- 0.11.0rc0: `https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0rc0-cp27-none-linux_x86_64.whl`
- 0.11.0:`
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl`

Closing this out as the URLs are still accessible. Let me know if I misunderstood.

**Comment by yifeif** [comment]
That's correct, as @asimshankar mentioned, we changed the naming convention so we could upload both cpu and gpu binaries to pypi. @rueberger you can find the full list of binary urls for r0.11 at https://www.tensorflow.org/versions/r0.11/get_started/os_setup#using_pip

**Comment by rueberger** [comment]
Wonderful, thanks!
