### ISSUE TITLE
Determining if A Value is in a Set

### ISSUE THREAD

**Issue by LeavesBreathe** [tensorflow/tensorflow#694]
Hey TF,

The `logical_or`, `logical_and`, and `select` functions are very useful.

However, suppose you have value x, and you wanted to see if it was in a set(a,b,c,d,e). In python you would simply write:

```python

if x in set([a,b,c,d,e]):
   #do action
```

As far as I can tell, the only way to do this in tensorflow, is to have nested 'logical_or' along with 'tf.equal'. I provided just one iteration of this concept below:

```python
tf.logical_or(
tf.logical_or(tf.equal(x, a), tf.equal(x,b)),
tf.logical_or(tf.equal(x, c), tf.equal(x,d)),
)

```

 I feel that there must be an easier way to do this in tensorflow. Is there?

**Comment by vrv** [comment]
(Stackoverflow is the appropriate location for this question, since this isn't a bug / feature request)

**Comment by LeavesBreathe** [comment]
thanks I will ask there
