### ISSUE TITLE
AttributeError: 'ModelCheckpoint' object has no attribute '_implements_train_batch_hooks' in MoViNet Streaming Model Training

### ISSUE THREAD

**Issue by yuvch98** [tensorflow/tensorflow#69448]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.16.1

### Custom code

No

### OS platform and distribution

Google Colab

### Python version

3.10

### Current behavior?

I encountered an AttributeError while trying to fit the model using the MoViNet Streaming Model Training and Inference notebook provided in the TensorFlow Model Garden repository. The specific error message is as follows:
![image](https://github.com/tensorflow/tensorflow/assets/109518434/6dd33b9e-4524-4031-b1bb-0576308bff6d)

in addition, there is a minor adjustment needed to be done in this code:
![image](https://github.com/tensorflow/tensorflow/assets/109518434/d597141d-6359-4e8d-a299-439fb75c458e)

### Standalone code to reproduce the issue

```shell
The issue can be reproduced using the notebook from the official TensorFlow Models GitHub repository:

https://github.com/tensorflow/models/blob/f9fdc4faef47af76351204b6d8df576f0e79baab/official/projects/movinet/movinet_streaming_model_training_and_inference.ipynb
```

### Relevant log output

```shell
AttributeError                            Traceback (most recent call last)
<ipython-input-18-49dc73e1e0f6> in <cell line: 1>()
----> 1 results = model.fit(train_ds,
      2                     validation_data=val_ds,
      3                     epochs=2,
      4                     validation_freq=1,
      5                     verbose=1,

1 frames
/usr/local/lib/python3.10/dist-packages/tf_keras/src/callbacks.py in <genexpr>(.0)
    243             getattr(cb, "_supports_tf_logs", False)
    244             for cb in self.callbacks
--> 245             if cb._implements_train_batch_hooks()
    246             or cb._implements_test_batch_hooks()
    247             or cb._implements_predict_batch_hooks()

AttributeError: 'ModelCheckpoint' object has no attribute '_implements_train_batch_hooks'
```

**Comment by sushreebarsa** [comment]
@yuvch98 Could you try creating a new virtual environment to avoid conflicts with existing project dependencies and if you still face the issue then please post this issue on [models](https://github.com/tensorflow/models/issues?q=is%3Aissue+is%3Aopen) repository for further assistance.
Thank you!
