### ISSUE TITLE
Gradle builds for Tensorflow Android does not automatically fetch the models

### ISSUE THREAD

**Issue by WalterWangNYUMLC** [tensorflow/tensorflow#6945]
Builds work fine using bazel.
However when the project is imported into android studio using gradle, the assets directory remains empty. The app crashes on startup. When the models are manually downloaded and placed into the asset folder, the gradle builds work. Not sure if this was intended.

**Comment by asimshankar** [comment]
Yes, this is intended, though perhaps the [example's README](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/README.md) could make this clearer.

If you'd like to send in a pull request that makes gradle download/copy the asset, we'd welcome that. Thanks!

FYI @andrewharp

**Comment by andrewharp** [comment]
@ggfan has a solution in his cmake work: https://github.com/ggfan/tensorflow/blob/android-studio-port/tensorflow/examples/android/cmake/app/build.gradle

We should be able share the same solution in examples/android/build.gradle once this is ready.
