### ISSUE TITLE
Segmentation fault (core dumped) in tf.raw_ops.FractionalMaxPoolGrad when col_pooling_sequence is a very small negative number

### ISSUE THREAD

**Issue by x0w3n** [tensorflow/tensorflow#69461]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.16

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 22.04.3 LTS (x86_64)

### Python version

3.9.13

### Current behavior?

tf.raw_ops.FractionalMaxPoolGrad triggers a crash when the col_pooling_sequence parameter is a very small negative number. Additionally, the same situation exists with the row_pooling_sequence parameter.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

overlapping = True
orig_input = tf.constant(100, shape=[1,4,7,1], dtype=tf.float32)
orig_output = tf.constant(.453409232, shape=[1,7,13,1], dtype=tf.float32)
out_backprop = tf.constant(.453409232, shape=[1,7,13,1], dtype=tf.float32)
# row_pooling_sequence = tf.constant(-1250999896764, shape=[5], dtype=tf.int64) # same
row_pooling_sequence = tf.constant(0, shape=[5], dtype=tf.int64) 
col_pooling_sequence = tf.constant(-1250999896764, shape=[5], dtype=tf.int64)
tf.raw_ops.FractionalMaxPoolGrad(orig_input=orig_input, orig_output=orig_output, out_backprop=out_backprop, row_pooling_sequence=row_pooling_sequence, col_pooling_sequence=col_pooling_sequence, overlapping=overlapping)
```

### Relevant log output

```shell
2024-06-10 08:49:22.910373: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Segmentation fault (core dumped)
```

**Comment by sushreebarsa** [comment]
@x0w3n I was able to replicate  the issue reported [here](https://colab.research.google.com/gist/sushreebarsa/e02cf76790a4b4e658a9844601ddf892/69461.ipynb).  One workaround could be to perform the forward FractionalMaxPool to get the correct pooling sequences, then using the obtained pooling sequences in the gradient operation. Please let us know if it helps?
Thank you!
