### ISSUE TITLE
How do I use mkl's matmul in MatMulOp::Compute()?

### ISSUE THREAD

**Issue by bowu** [tensorflow/tensorflow#6946]
I've been trying to modify core/kernels/matmul_op.cc to use mkl's matmul api. Although I can link mkl without any problem to compile my simple standalone c++ file, things don't work after adding the linking option to matmul_op's rule.
copts = ["-Wl,--start-group /opt/intel/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64/libmkl_intel_lp64.a /opt/intel/compilers_and_libraries_2017.     0.098/linux/mkl/lib/intel64/libmkl_gnu_thread.a /opt/intel/compilers_and_libraries_2017.0.098/linux/mkl/lib/intel64/libmkl_core.a -Wl,--end-group -lgomp -lpthread -lm -ldl"]

I also used the mkl link option when compiling a test that uses the matmul op.

Like this:

bazel build -c opt tensorflow/tools/benchmark:2mklmatmul_test --linkopt="-L${MKLROOT}/lib/intel64/libmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -lgomp -lpthread -lm -ldl"

However, tensorflow can't find the definition of mkl's matmul function during linking.

Please note that I understand that I should add a new op. I did this just to quickly see whether I can link MKL in tensorflow.

**Comment by yaroslavvb** [comment]
Did you see this PR? https://github.com/tensorflow/tensorflow/pull/6921/commits

**Comment by yaroslavvb** [comment]
The changes to ./configure in change above give the steps needed to link MKL against TensorFlow, let us know if it doesn't work

**Comment by aselle** [comment]
Closing due to lack of recent activity. Please update the issue if it persists and we will reopen.
