### ISSUE TITLE
Bazel building error : proxy address 127.0.0.1:8118 is not a valid URL

### ISSUE THREAD

**Issue by GehenHe** [tensorflow/tensorflow#6949]
I try to use bazel to build an Android APK by following https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android

but I meet download error like this after use this commend **bazel build -c opt //tensorflow/examples/android:tensorflow_demo**:

> _/home/gehen/tensorflow/tensorflow/examples/android/BUILD:58:1: no such package '@inception5h//': Error downloading [https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip] to /home/gehen/.cache/bazel/_bazel_gehen/9dc623b792acc42ff703ada723a44292/external/inception5h/inception5h.zip: Proxy address 127.0.0.1:8118 is not a valid URL and referenced by '//tensorflow/examples/android:tensorflow_demo'._

I use these attempt to fix this error ,but all failed.
1.**unset http_proxy**
     this report the same error
2.corret the http_proxy.
    Actually I use the http://localhost:1080 as my proxy , but I don't known why it change into 127.0.0.1:8118, so I use export **http_proxy=http://localhost:1080** and **https_proxy=http://localhost:1080**, it can not download

 _Timeout connecting to https://storage.googleapis.com/download.tensorflow\
.org/models/mobile_multibox_v1.zip_

3.I find I can wget the *.zip seperately , so why can't I get the sources from bazel , what might the resons .

Thank you for your reply

I'm almost crazy about it

**Comment by andrewharp** [comment]
This doesnt sound like a TF issue -- you'll have better luck asking at http://github.Com/bazelbuild or on stackoverflow. In the meantime there's the manual download at least.
