### ISSUE TITLE
Error downloading zlib 1.2.8 in TensorFlow r0.10

### ISSUE THREAD

**Issue by Nayana-ibm** [tensorflow/tensorflow#6950]
While building TensorFlow r0.10, we faced below error:
`zlib_archive: Error downloading http://zlib.net/zlib-1.2.8.tar.gz`

It looks like the issue has been fixed in r0.12 through [commit](https://github.com/tensorflow/tensorflow/commit/1e317b1f7dc5ccf04fc51ac96d97f5bdaefa9af9).

Will it be possible to include same change for r0.10?

**Comment by jart** [comment]
Oh my goodness. It looks like I should just cherry pick https://github.com/tensorflow/tensorflow/commit/96e3e6f70ad9c441be46fcf70449e810a4b36896 on all the branches.

**Comment by jart** [comment]
You're going to be so happy to hear that this is never going to happen again in the future, thanks to the incredible improvements we made to the Bazel downloader. Policy now dictates we have redundant mirrors for everything. It's going to do wonders for preserving the archival integrity of this software. https://github.com/bazelbuild/bazel/commit/ed7ced0018dc5c5ebd6fc8afc7158037ac1df00d

**Comment by trsaunders** [comment]
It looks like redundant mirrors are needed for nasm:

```
ERROR: /home/tom/.cache/bazel/_bazel_tom/0eaf2b6b7a8618527eb96256b130e46f/external/jpeg/BUILD:162:1: no such package '@nasm//': Error downloading [http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/nasm-2.12.02.tar.bz2] to /home/tom/.cache/bazel/_bazel_tom/0eaf2b6b7a8618527eb96256b130e46f/external/nasm/nasm-2.12.02.tar.bz2: Connection refused (Connection refused) and referenced by '@jpeg//:simd_x86_64_assemblage23'.
ERROR: /home/tom/.cache/bazel/_bazel_tom/0eaf2b6b7a8618527eb96256b130e46f/external/jpeg/BUILD:162:1: no such package '@nasm//': Error downloading [http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/nasm-2.12.02.tar.bz2] to /home/tom/.cache/bazel/_bazel_tom/0eaf2b6b7a8618527eb96256b130e46f/external/nasm/nasm-2.12.02.tar.bz2: Connection refused (Connection refused) and referenced by '@jpeg//:simd_x86_64_assemblage23'.
ERROR: Evaluation of query "deps((//tensorflow/... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.
```

(on the head of r0.12)

**Comment by jowagner** [comment]
created issue #6956 for the nasm error

**Comment by drpngx** [comment]
Closing this to tidy up issues. Feel free to re-open another issue with a different title if you want to track.
