### ISSUE TITLE
SparseTensor Batching Utility 

### ISSUE THREAD

**Issue by ndeep27** [tensorflow/tensorflow#69541]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

TF 2.11

### Custom code

No

### OS platform and distribution

Linux Rhel

### Current behavior?

Is there a utility method to batch sparse tensors together? Tensorflow Serving Batching support utilizes the DenseTensor Concat op - https://github.com/tensorflow/serving/blob/67a2dcb2b9c057847616fb5ce54cb8545955d144/tensorflow_serving/batching/batching_session.cc#L577

Is there an equivalent for SparseTensor batching?

### Standalone code to reproduce the issue

```shell
None
```

### Relevant log output

```shell
None
```

**Comment by sushreebarsa** [comment]
@ndeep27 TensorFlow Serving's built-in batching functionality currently doesn't directly support sparse tensors. As you pointed out, it relies on tf.concat for dense tensors . Please have a look at the similar issue as discussed [here](https://github.com/tensorflow/serving/issues/2188). For any further queries kindly post the issue in the TF serving repository.
Thank you!
