### ISSUE TITLE
Inception3 retraining - attach text/labels to individual images

### ISSUE THREAD

**Issue by iNDicat0r** [tensorflow/tensorflow#6957]
Hi

I am using the inception v3 model to retrain my own dataset. I have few folder which represent the classes which contain images for each class. What i would like to do is to 'attach' some text ids to these images so when they are retrained and used to run classification/similarity-detection those ids are retrieved too. (basically its image similarity detection)

For instance, Image X is of class 'Teachers' and it belongs to John. When i retrain the model, and run a classification on the new model, i would like to get the Teachers class, but in addition to this i would like to know who is teacher (John).

Any ideas how to go for it?

Regards

**Comment by asimshankar** [comment]
This question is better suited for stackoverflow and I see you have [posted there](http://stackoverflow.com/questions/41745022/tensorflow-inception-v3-retraining-attach-text-labels-to-individual-images). Thanks for doing that.

Please do not cross post in github as we try to keep the github issues focused on bugs and feature requests.
