### ISSUE TITLE
The constant folding pass of the TFLite converter prevent storing packed tensors, stores dequantized tensors instead

### ISSUE THREAD

**Issue by BenCrulis** [tensorflow/tensorflow#69598]
### 1. System information

WSL Linux l 5.14.0-427.18.1.el9_4.x86_64 GNU/Linux
tensorflow==2.10.1
tensorflow-cpu==2.10.1
installed using pip

### 2. Code
Ignore the fact that the dequantization process is currently wrong, this is just for testing.

```python
class TestBinary(Layer):
    def __init__(self, units):
        super().__init__()
        self.units = units

    def build(self, input_shape):
        self.input_size = input_shape[-1]
        assert input_shape[-1] * self.units % 8 == 0
        compressed_size = int(input_shape[-1] * self.units / 8)
        self.kernel = self.add_weight(shape=(compressed_size,), initializer="ones", dtype=tf.int8)

    def call(self, x):
        compressed_weights = self.kernel
        tensors = []
        for i in range(8):
            tensors.append(compressed_weights)  # will use a formula to dequantize in the future
        
        kernel = tf.stack(tensors)
        kernel = tf.cast(kernel, tf.float32)  # seems to store the variable at this point on disk
        kernel = tf.reshape(kernel, (self.input_size, self.units))
        x = x @ kernel
        return x

quantDense = TestBinary(1000)
test_input_shape = (500,)
quantDense(tf.ones((1, *test_input_shape))) # initialize the weights

converter = tf.lite.TFLiteConverter.from_keras_model(quantDense)
converted = converter.convert()

with open("test.tflite", "wb") as f:
    f.write(converted)
```

### 3. conversion

The conversion is successful, but the model size is that of a model which stores the full 1000*500 weight matrix in int8 format, which is about 500KB, when it should store the packed weights and weigh ~63KB.

I assume this is the result of the constant folding pass of the converter which stores the weights that have just been casted to float32, instead of storing the int8 weights and re-doing the dequantization process each time.
This can be seen in the graph of the resulting tflite file:
![image](https://github.com/tensorflow/tensorflow/assets/25989170/e4fbb9e1-2374-4231-a3e1-359064807200)
(I am not sure why the tensor is not saved after the transpose instead)

This is also evidenced by the fact that I can replace `compressed_weights = self.kernel` with `compressed_weights = self.kernel + tf.cast(x[0,0], dtype=tf.int8) * 0` and have the compressed weights saved on disk this way, because `x` cannot be constant-folded.
However, this cost extra operations and forces me to activate additional supported ops in the converter, which is not ideal.

Note that I also tried adding this code, but it does not change anything:
```python
tf.config.optimizer.set_experimental_options({
    "constant_folding": False,
    "disable_model_pruning": True,
    "remapping": False,
    })
```

So, is there a way to prevent constant folding? Perhaps with a global flag but preferably by introducing a no-op in the graph at a specific point to prevent the folding of just these nodes.

Maybe there is also a way to guarantee the storage of a particular parameter in packed form for binary and ternary weights?

**Comment by sawantkumar** [comment]
Hi @pkgoogle  ,

I replicated his code and the converted model size comes out to be of 500kb . Can you please take a look?

**Comment by pkgoogle** [comment]
I am unable to find a configuration option which accomplishes the stated goals... here's where you can find most of the converter options: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/python/lite.py#L614, for now I will consider this as a feature request. @zichuan-wei can you please take a look? Thanks.

**Comment by BenCrulis** [comment]
Thanks everyone for looking into this.
@pkgoogle to me, the best way to solve this problem would not be a global configuration option, because optimizing some parts of the graph can still be very useful, but instead an operator that just prevents constant folding from being applied on this part of the graph.

Last week I managed to find a way to create such an operator, but it is a bit of a hack that might not work in future versions of Tensorflow:

```python
def prevent_constant_folding(witness, tensor):
    first_values = tf.reshape(witness, (-1,))[0]
    # both branches of the if are the same
    return tf.cond(first_values < 5, lambda: tensor, lambda: tensor) 
```

It is used like this in the original code:
```python
compressed_weights = self.kernel
# the input x is the runtime value that is used as witness
compressed_weights = prevent_constant_folding(x, compressed_weights)  
```
With this, the resulting tflite file is indeed 64KB, here is what the graph looks like:
![image](https://github.com/tensorflow/tensorflow/assets/25989170/04596cd2-2ef7-4f5d-8b6a-028ff88b3020)


I think it would be best if Tensorflow introduced a similar operator, which ideally does not require a witness runtime value.
Maybe it could be an option to `tf.identity`, or a dedicated operator that is just like `tf.identity` but prevents constant folding.

**Comment by BenCrulis** [comment]
Hi @gaikwadrahul8 ,
I was not aware of the migration to LiteRT, but I noticed that the TFLite Engine was seemingly gradually abandoned in favor of something else.

Thank you for reopening the issue there. Currently I am solving my original problem by modifying [Larq](https://github.com/larq/compute-engine), which is based on the TFLite Engine to include a custom native operator which does not cause the converter to store dequantized tensors in the `.tflite`.

So I am wondering, will LiteRT easily modified to include custom operators? Ideally keeping the same operator API.
And since we are there, is there any plan to implement the multi-threaded batch matrix multiplication operator for ARM devices, or allow the replacement of the native operators of the library by custom native operators?
