### ISSUE TITLE
tf.signal.rfftnd throws NotFoundError on CPU execution (GPU-behavior unknown)

### ISSUE THREAD

**Issue by MathiesW** [tensorflow/tensorflow#69595]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf 2.16.1

### Custom code

No

### OS platform and distribution

WSL Ubuntu 22.04

### Python version

3.11.8

### Current behavior?

Tensorflow throws an NotFoundError when calling ```tf.signal.rfftnd```. It seems to me like TF wants to run the code on a GPU, which is not available since I am running on CPU only. I have no possibility of testing on a GPU atm.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
x = tf.random.normal([8, 8])
y = tf.signal.rfftnd(x)
```

### Relevant log output

```shell
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
Cell In[4], line 3
      1 import tensorflow as tf
      2 x = tf.random.normal([8, 8])
----> 3 y = tf.signal.rfftnd(x)

File ~/.pyenv/versions/3.11.8/envs/emess/lib/python3.11/site-packages/tensorflow/python/ops/signal/fft_ops.py:325, in _rfftn_wrapper.<locals>._rfftn(input_tensor, fft_length, axes, norm, name)
    323   elif norm == "ortho":
    324     input_tensor /= np.sqrt(n)  # should be sqrt(N)
--> 325 return rfft_n(
    326     input_tensor,
    327     fft_length,
    328     axes,
    329     Tcomplex=complex_dtype,
    330     name=name,
    331 )

File ~/.pyenv/versions/3.11.8/envs/emess/lib/python3.11/site-packages/tensorflow/python/ops/gen_spectral_ops.py:1744, in rfftnd(input, fft_length, axes, Tcomplex, name)
   1742   return _result
   1743 except _core._NotOkStatusException as e:
-> 1744   _ops.raise_from_not_ok_status(e, name)
   1745 except _core._FallbackException:
   1746   pass

File ~/.pyenv/versions/3.11.8/envs/emess/lib/python3.11/site-packages/tensorflow/python/framework/ops.py:5983, in raise_from_not_ok_status(e, name)
   5981 def raise_from_not_ok_status(e, name) -> NoReturn:
   5982   e.message += (" name: " + str(name if name is not None else ""))
-> 5983   raise core._status_to_exception(e) from None

NotFoundError: Could not find device for node: {{node RFFTND}} = RFFTND[Tcomplex=DT_COMPLEX64, Treal=DT_FLOAT]
All kernels registered for op RFFTND:
  device='GPU'
 [Op:RFFTND] name:
```

**Comment by sushreebarsa** [comment]
@MathiesW You could reinstall TensorFlow with CPU support explicitly enabled. Here's a general guideline build instructions for WSL Ubuntu 22.04 ; please follow the steps below and let us know?
a. Uninstall the current TensorFlow installation: pip uninstall tensorflow
b. During the installation, use a flag or configuration option that specifies CPU support. For example, you might be able to use `pip install tensorflow-cpu.` 
Thank you!

**Comment by MathiesW** [comment]
@sushreebarsa thanks for the recommendation. I tried your approach on Google Colab and the same error occurs: `NotFoundError: Could not find device for node: {{node RFFTND}} = RFFTND[Tcomplex=DT_COMPLEX64, Treal=DT_FLOAT]
All kernels registered for op RFFTND:
  <no registered kernels>
 [Op:RFFTND] name: `

see my Colab the code here: https://colab.research.google.com/drive/16Y52PrW3eRBtTHOzw32chYgJ5sMZFgwq?usp=sharing

I now opted to just use the existing FFT implementations in TF for 1, 2 and 3 dimensions as a workaround. However, they do not feature the `axes` argument, such that I have to transpose all my data from format `channels last` to format `channels first` before using the FFT.

**Comment by tilakrayal** [comment]
@MathiesW,
Have you got the chance to have a look at the fft_ops.py, rfftnd and irfftnd are registered with the GPU and other 2d, 3d apis are registered with the CPU.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/fft_ops.cc#L1095

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/fft_ops.cc#L407
