### ISSUE TITLE
why tf use clang as the default compiler on windows?

### ISSUE THREAD

**Issue by risemeup1** [tensorflow/tensorflow#69665]
### Issue type

Others

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.8

### Custom code

Yes

### Bazel version

nothing

### GCC/compiler version

nothing

### CUDA/cuDNN version

nothing

### GPU model and memory

nothing

### Current behavior?

<img width="869" alt="image" src="https://github.com/tensorflow/tensorflow/assets/62429225/4465d39b-4e34-49a6-8bcb-e75cfa95e925">
I just want to know why TensorFlow has switched to using Clang as the default compiler on Windows, and what the benefits are？ 

### Standalone code to reproduce the issue

```shell
nothing
```

### Relevant log output

```shell
nothing
```

**Comment by mihaimaruseac** [comment]
There are several reasons:

- TensorFlow relies on LLVM.
- MSVC does not have good support for compiling CUDA, unlike clang.
- MSVC compiler updates at a slower rate than clang so features have to be held back
- MSVC compiler error are harder to parse, they're more opaque
- Compiling TF GPU with MSVC for releases took up to 12 hours, compared to clang which has reasonable time
- Google uses clang to compile everything so it does not make sense to have people learn a new compiler

**Comment by risemeup1** [comment]
> There are several reasons:
> 
> * TensorFlow relies on LLVM.
> * MSVC does not have good support for compiling CUDA, unlike clang.
> * MSVC compiler updates at a slower rate than clang so features have to be held back
> * MSVC compiler error are harder to parse, they're more opaque
> * Compiling TF GPU with MSVC for releases took up to 12 hours, compared to clang which has reasonable time
> * Google uses clang to compile everything so it does not make sense to have people learn a new compiler

Thank you very much
