### ISSUE TITLE
TFlite usage on android

### ISSUE THREAD

**Issue by dhruvsingla273** [tensorflow/tensorflow#69680]
I am using a TFlite model to do some video processing frame by frame on android.
The below is the method I have to use to convert Bitmap to ByteBuffer.

`
val bitmap = Bitmap.createScaledBitmap(yourInputImage, 224, 224, true)
val input = ByteBuffer.allocateDirect(224*224*3*4).order(ByteOrder.nativeOrder())
for (y in 0 until 224) {
    for (x in 0 until 224) {

        val px = bitmap.getPixel(x, y)
        val r = Color.red(px)
        val g = Color.green(px)
        val b = Color.blue(px)
        val rf = (r - 127) / 255f
        val gf = (g - 127) / 255f
        val bf = (b - 127) / 255f

        input.putFloat(rf)
        input.putFloat(gf)
        input.putFloat(bf)
    }
}
`

But this is taking a lot of time and as I have to do Real time processing I dont have such time,

How can I optimise this?
And also while copying the image from byteBuffer to Bitmap it is also taking a lot of time
Inbuilt functions given don't work because of how the ByteBuffer is created.
So I have to make custom loop to copy the pixels back which takes a lot of time.

Please suggest alternative strategies.

**Comment by dhruvsingla273** [comment]
@sawantkumar Can you please have a look,
Thanks

**Comment by sawantkumar** [comment]
Hi @pkgoogle ,

I  don't have much idea about this , can you please take a look?

**Comment by pkgoogle** [comment]
Hi @dhruvsingla273, using array/bulk/vectorized methods and preprocessing libraries will probably help. You may want to see if tflite-support can help you: https://www.tensorflow.org/lite/inference_with_metadata/lite_support . How are you
> not able to set it up

? I.e. what is blocking you?, what's your environment? and How can I reproduce your error?

**Comment by dhruvsingla273** [comment]
I am able to make the QNN HTP delegate now.
I changed the android NDK version and it worked. There was some SOC file that was missing.
Thanks, I will checkout the tflite_support for the preprocessing
