### ISSUE TITLE
Cannot cross-compile minimal tflite example

### ISSUE THREAD

**Issue by abeyene** [tensorflow/tensorflow#69689]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.14

### Custom code

Yes

### OS platform and distribution

Rocky Linux 8.1

### Python version

3.11

### Current behavior?

This is the cmake toolchain file used for cross-compilation:

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR rv64g)

set(CMAKE_C_COMPILER /local/data0/chipyard/.conda-env/riscv-tools/bin/riscv64-unknown-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER /local/data0/chipyard/.conda-env/riscv-tools/bin/riscv64-unknown-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH /local/data0/chipyard/.conda-env/riscv-tools/sysroot)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
include_directories(BEFORE /local/data0/chipyard/.conda-env/riscv-tools/riscv64-unknown-linux-gnu/include)

### Standalone code to reproduce the issue

```shell
git clone https://github.com/tensorflow/tensorflow.git tensorflow_src

mkdir minimal_build
cd minimal_build

cmake -DCMAKE_TOOLCHAIN_FILE=../riscv.cmake -DTFLITE_ENABLE_XNNPACK=OFF -DTFLITE_ENABLE_RUY=OFF -DTFLITE_ENABLE_MMAP=OFF ../tensorflow/lite/examples/minimal

cmake --build . -j 8
```

### Relevant log output

```shell
[ 50%] Built target absl_flags
[ 98%] Built target tensorflow-lite
[ 98%] Linking CXX executable minimal
riscv64-unknown-linux-gnu/12.2.0/../../../../riscv64-unknown-linux-gnu/bin/ld: _deps/cpuinfo-build/libcpuinfo.a(init.c.o): in function `.L0 ':
init.c:(.text+0x2): undefined reference to `cpuinfo_riscv_linux_init'
riscv64-unknown-linux-gnu/12.2.0/../../../../riscv64-unknown-linux-gnu/bin/ld: minimal: hidden symbol `cpuinfo_riscv_linux_init' isn't defined
riscv64-unknown-linux-gnu/12.2.0/../../../../riscv64-unknown-linux-gnu/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/minimal.dir/build.make:183: minimal] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1229: CMakeFiles/minimal.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Comment by sushreebarsa** [comment]
@abeyene Could you please verify that all source files related to cpuinfo are being compiled and included in the build. The missing cpuinfo_riscv_linux_init function should be implemented in one of the source files. Kindly upgrade to the latest TF version and let us know? Thank you!

**Comment by abeyene** [comment]
@sushreebarsa I am cloning the tensorflow repository and using the master branch. Is that not the latest TF version by default?

**Comment by sushreebarsa** [comment]
@abeyene If you are using the master branch then it would be latest as you mentioned of using TF 2.14 I asked for an upgrade. Thank you for the update!

**Comment by sawantkumar** [comment]
Hi @pkgoogle ,

I tried to replicate this issue on ubuntu 20 and tensorflow 2.16 but i keep running into the below error , can you please take a look 

`/mnt/disks/my-disk/minimal_build/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc:62:26: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
/mnt/disks/my-disk/minimal_build/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc:62:31: error: template argument 1 is invalid
   62 |     std::lock_guard<std::mutex> lock(TimeZoneMutex());
      |                               ^
/mnt/disks/my-disk/minimal_build/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc:62:38: error: 'TimeZoneMutex' was not declared in this scope
   62 |     std::lock_guard<std::mutex> lock(TimeZoneMutex());
      |                                      ^~~~~~~~~~~~~
/mnt/disks/my-disk/minimal_build/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc:62:33: warning: unused variable 'lock' [-Wunused-variable]
   62 |     std::lock_guard<std::mutex> lock(TimeZoneMutex());
      |                                 ^~~~
/mnt/disks/my-disk/minimal_build/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc:76:24: error: 'mutex' is not a member of 'std'
   76 |   std::lock_guard<std::mutex> lock(TimeZoneMutex());
      |                        ^~~~~
/mnt/disks/my-disk/minimal_build/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc:76:24: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
/mnt/disks/my-disk/minimal_build/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc:76:29: error: template argument 1 is invalid
   76 |   std::lock_guard<std::mutex> lock(TimeZoneMutex());
      |                             ^
/mnt/disks/my-disk/minimal_build/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc:76:36: error: 'TimeZoneMutex' was not declared in this scope
   76 |   std::lock_guard<std::mutex> lock(TimeZoneMutex());
      |                                    ^~~~~~~~~~~~~
/mnt/disks/my-disk/minimal_build/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc:76:31: warning: unused variable 'lock' [-Wunused-variable]
   76 |   std::lock_guard<std::mutex> lock(TimeZoneMutex());
      |                               ^~~~
/mnt/disks/my-disk/minimal_build/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc: In static member function 'static void absl::lts_20230802::time_internal::cctz::time_zone::Impl::ClearTimeZoneMapTestOnly()':
/mnt/disks/my-disk/minimal_build/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc:87:24: error: 'mutex' is not a member of 'std'
   87 |   std::lock_guard<std::mutex> lock(TimeZoneMutex());
      |                        ^~~~~
/mnt/disks/my-disk/minimal_build/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc:87:24: note: 'std::mutex' is defined in header '<mutex>'; did you forget to '#include <mutex>'?
/mnt/disks/my-disk/minimal_build/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc:87:29: error: template argument 1 is invalid
   87 |   std::lock_guard<std::mutex> lock(TimeZoneMutex());
      |                             ^
/mnt/disks/my-disk/minimal_build/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc:87:36: error: 'TimeZoneMutex' was not declared in this scope
   87 |   std::lock_guard<std::mutex> lock(TimeZoneMutex());
      |                                    ^~~~~~~~~~~~~
/mnt/disks/my-disk/minimal_build/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc:87:31: warning: unused variable 'lock' [-Wunused-variable]
   87 |   std::lock_guard<std::mutex> lock(TimeZoneMutex());
      |                               ^~~~
make[2]: *** [_deps/abseil-cpp-build/absl/time/CMakeFiles/time_zone.dir/build.make:102: _deps/abseil-cpp-build/absl/time/CMakeFiles/time_zone.dir/internal/cctz/src/time_zone_impl.cc.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:5567: _deps/abseil-cpp-build/absl/time/CMakeFiles/time_zone.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

**Comment by pkgoogle** [comment]
Hi @abeyene, can you please provide instructions on how to replicate your conda environment? Also for clarification... is `riscv.cmake` exactly this?:

```cmake
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR rv64g)

set(CMAKE_C_COMPILER /local/data0/chipyard/.conda-env/riscv-tools/bin/riscv64-unknown-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER /local/data0/chipyard/.conda-env/riscv-tools/bin/riscv64-unknown-linux-gnu-g++)

set(CMAKE_FIND_ROOT_PATH /local/data0/chipyard/.conda-env/riscv-tools/sysroot)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
include_directories(BEFORE /local/data0/chipyard/.conda-env/riscv-tools/riscv64-unknown-linux-gnu/include)
```

One thing you can try is using a previous release branch or nightly. Generally speaking master is very dynamic and depending the exact commit you hit, it may be unstable.

**Comment by abeyene** [comment]
Hi @pkgoogle,

Yes, it seems like moving to a different release branch solved the problem. I'm able to build the minimal tflite example using release branch v2.15.0. Note that release branch v.2.17.0-rc1 did NOT work however.

Also, I've switched to a new RISC-V compiler. While the above riscv.cmake file you posted was my indeed my old one, the new configuration looks like this:

```cmake
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR rv64g)

# which compilers to use for C and C++

set(CMAKE_C_COMPILER /local/data0/AB/riscv-linux/buildroot-2023.02.3/output/host/bin/riscv64-buildroot-linux-musl-gcc)
set(CMAKE_CXX_COMPILER /local/data0/AB/riscv-linux/buildroot-2023.02.3/output/host/bin/riscv64-buildroot-linux-musl-g++)

# where is the target environment located
set(CMAKE_FIND_ROOT_PATH /local/data0/AB/riscv-linux/buildroot-2023.02.3/output/host/riscv64-buildroot-linux-musl)

# adjust the default behavior of the FIND_XXX() commands:

# search programs in the host environment
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

# search headers and libraries in the target environment
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
include_directories(BEFORE /local/data0/AB/riscv-linux/buildroot-2023.02.3/output/host/include)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DFLATBUFFERS_LOCALE_INDEPENDENT=0 -DCPUINFO_SUPPORTED_PLATFORM=0")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DFLATBUFFERS_LOCALE_INDEPENDENT=0 -DCPUINFO_SUPPORTED_PLATFORM=0")

set(CMAKE_VERBOSE_MAKEFILE ON)
```

So there is no longer any conda environment. Simply an existing RISC-V toolchain installation. 

And yes, I created the minimal_build directory within the tensorflow repository:

```bash
git clone https://github.com/tensorflow/tensorflow.git tensorflow_src
cd tensorflow_src
mkdir minimal_build
```

**Comment by abeyene** [comment]
Yes I would say the issue is resolved.

Thank you.

**Comment by pkgoogle** [comment]
Sure thing, if you have no more open items please feel free to close.
