### ISSUE TITLE
Installing Tensorflow on Fedora 40

### ISSUE THREAD

**Issue by ludiusvox** [tensorflow/tensorflow#69718]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.5

### Custom code

Yes

### OS platform and distribution

WSL Fedora 40

### Python version

3.10

### CUDA/cuDNN version

12.4

### GPU model and memory

4080RTX NVIDIA

### Current behavior?

I am trying to figure out how to build a wheel for Tensorflow 2.5+ for CUDA 12.4, I am having difficulty, the Fedora developers think they need Bazel, but I explained that Bazel is unneccesary, but I am looking for a procedure to install with CMAKE and build from source and upload a container.  

Pytorch is easy to install, and the team lead on Fedora 40 AI/ML is more interested in supporting ROCm so I am just coming in here see if I can get some advice.  I had completed a graduate thesis in TF and i am really comfortable with the Software, but it's limited pipeline support for all the distros is difficult.  

I would hate to have to spend $1000 on a new GPU I really like fedora and Pytorch works out of the box, can anything be done?

### Standalone code to reproduce the issue

```shell
Building TensorFlow with CMake

TensorFlow provides some support for building with CMake, primarily targeting Windows environments. Below are the steps for building TensorFlow using CMake on Linux. This process is more experimental and might not cover all features of TensorFlow.
Prerequisites

    Dependencies:
        CMake (version 3.16 or later)
        Python (3.6, 3.7, 3.8, or 3.9)
        TensorFlow dependencies: numpy, six, wheel, setuptools, h5py, keras_preprocessing
        GCC compiler (GCC 7.3 or later recommended)

    Install necessary packages:

    bash

    sudo apt-get update
    sudo apt-get install cmake python3-dev python3-pip gcc g++
    pip3 install numpy six wheel setuptools h5py keras_preprocessing

Steps to Build

    Clone TensorFlow Repository:

    bash

git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow

Create Build Directory:

bash

mkdir build
cd build

Configure the Build with CMake:

bash

cmake .. -Dtensorflow_ENABLE_GPU=OFF -Dtensorflow_BUILD_PYTHON_BINDINGS=ON

    Adjust options as necessary. For example, set -Dtensorflow_ENABLE_GPU=ON if building with GPU support.

Build TensorFlow:

bash

cmake --build . --config Release

Build the Python Wheel:

    After building the main TensorFlow library, you need to build the Python package:

    bash

    cd ../tensorflow/tools/pip_package
    python3 build_pip_package.py --src .. --output .

    This script should generate a .whl file in the specified output directory.

Install the Wheel:

bash

pip3 install ./tensorflow-*.whl
```

### Relevant log output

```shell
--------------------------

Error here, I am stuck on python3-dev, and we expecting problems with keras_preprocessing
```

**Comment by ludiusvox** [comment]
I got it fixed with tensorflow nightly in docker containers, forget building from source!!!

this worked!!

Step-by-Step Instructions

Ensure Podman is Installed and Configured:
If Podman isn't installed or configured yet, follow these steps:

sh

sudo dnf install -y podman

Install NVIDIA Container Toolkit:
Install the NVIDIA Container Toolkit to enable GPU support in Podman.

sh

distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.repo | sudo tee /etc/yum.repos.d/nvidia-docker.repo
sudo dnf install -y nvidia-container-toolkit
sudo systemctl restart containerd

Configure Podman for NVIDIA Runtime:
Update Podman’s configuration to use the NVIDIA runtime.

sh

mkdir -p ~/.config/containers
cat < ~/.config/containers/containers.conf
[engine]
runtime = “nvidia”
EOT

Run TensorFlow Nightly GPU Container with Podman:

Use Podman on your host system to run the TensorFlow nightly GPU container. The --runtime=nvidia flag ensures that GPU support is enabled.

sh

podman run --runtime=nvidia -it tensorflow/tensorflow:nightly-gpu bash

If the above command fails or --runtime is not recognized, use the --gpus all flag:

sh

podman run --gpus all -it tensorflow/tensorflow:nightly-gpu bash

Verify TensorFlow GPU Support Inside the Container:

Once inside the container, verify that TensorFlow can access the GPU:

sh

python -c "import tensorflow as tf; print(‘TensorFlow version:’, tf.version); prin
[Aaron Linder](https://discussion.fedoraproject.org/u/ludiusvox)
[ludiusvox](https://discussion.fedoraproject.org/u/ludiusvox)
Aaron Linder
[2m](https://discussion.fedoraproject.org/t/gpu-support-for-deep-learning-frameworks-pytorch-tensorflow/118038/12)
$ podman run --gpus all -it tensorflow/tensorflow:nightly-gpu bash
WARN[0000] Using cgroups-v1 which is deprecated in favor of cgroups-v2 with Podman v5 and will be removed in a future version. Set environment variable PODMAN_IGNORE_CGROUPSV1_WARNING to hide this warning.

___ /________________________________ / /______ __
__ / _ _ _ __ _ / __ _ / / __ / __ _ | /| / /
_ / / / / / /( )/ // / / _ __/ _ / / // / |/ |/ /
// ___/// //// _/// // // _/__/|__/

WARNING: You are running this container as root, which can cause new files in
mounted volumes to be created as the root user on your host machine.

To avoid this, run the container by specifying your user’s userid:

$ docker run -u $(id -u):$(id -g) args…

/sbin/ldconfig.real: /usr/lib/wsl/drivers/nvmdsi.inf_amd64_23a2cede5f1383ec/libnvidia-ml.so.1 is not a symbolic link

root@b24205da9419:/# python -c “import tensorflow as tf; print(‘TensorFlow version:’, tf.version); print(‘Num GPUs Available:’, len(tf.config.experimental.list_physical_devices(‘GPU’)))”
2024-06-13 21:27:38.985917: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable TF_ENABLE_ONEDNN_OPTS=0.
2024-06-13 21:27:39.009506: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
TensorFlow version: 2.18.0-dev20240612
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1718314059.869098 17 cuda_executor.cc:990] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1718314059.872207 17 cuda_executor.cc:990] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1718314059.872254 17 cuda_executor.cc:990] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
Num GPUs Available: 1

**Comment by Venkat6871** [comment]
Hi @ludiusvox ,
- Could you please upgrade your tensorflow version. And here there is version miss match also. Please go through this [documentation](https://www.tensorflow.org/install/source_windows) once.

Thank you!

**Comment by ludiusvox** [comment]
Thank you!

**Comment by ludiusvox** [comment]
I found a solution with an IDE 1 line of code.  Very useful

one line of code

Found the solutions.

https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html

For example, you can use an image quay.io/jupyter/pytorch-notebook:cuda12-python-3.11.8 or quay.io/jupyter/tensorflow-notebook:cuda-latest

`sudo podman pull quay.io/jupyter/tensorflow-notebook:cuda-latest`

very fast shortcut

one line of code fixed the problem

**Comment by Venkat6871** [comment]
Hi **@ludiusvox** ,
- Glad to see this issue is resolved.  Please feel free to close the issue if it is resolved ? 

Thank you!
