### ISSUE TITLE
Object Detection in Android using front camera: the detected bounding boxes are drawn incorrectly

### ISSUE THREAD

**Issue by roshni-warrantylife** [tensorflow/tensorflow#69734]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

0.4.0

### Custom code

No

### Current behavior?

When I move an object (initially placed at the center of the screen) from a far distance towards the camera lens, the left position of the bounding box gradually shifts to the right side of the screen instead of staying centered.

Here is the recording of the issue, https://drive.google.com/file/d/144zCu8yPXYSeVPKk4RjDTG40YOcbLAtX/view

This issue is reproducable in the https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android. 

I have changed the camera lens to "LENS_FACING_FRONT" in the CameraFragment class. Additionally, to resolve the issue with the inverted (mirrored) coordinates, I have flipped the coordinates horizontally by adding the following code in the OverlayView class.

`           
```
            val boundingBox = result.boundingBox

            val objectTop = boundingBox.top * scaleFactor
            val objectBottom = boundingBox.bottom * scaleFactor
            val objectOriginalLeft = boundingBox.left * scaleFactor
            val objectOriginalRight = boundingBox.right * scaleFactor
            val objectWidth = objectOriginalRight - objectOriginalLeft

             var objectLeft = width - objectOriginalLeft + objectWidth
             var objectRight = objectLeft + objectWidth
```

### Standalone code to reproduce the issue

```shell
https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android
```

**Comment by roshni-warrantylife** [comment]
> Hi, @roshni-warrantylife
> 
> I apologize for the delayed response and thank you for bringing this issue to our attention, if possible could you please help us with your github repo (with changes made by you in this [example](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android)) which will be easy for us to replicate the same behaviour from our end and investigate this issue further ?
> 
> Thank you for your cooperation and patience.

Thank you for your understanding. I’ve shared the GitHub repository link below, which includes the changes I made to the example. Please feel free to use it to replicate the behavior on your end and investigate the issue further:

https://github.com/roshni-warrantylife/object-detection/tree/master/lite/examples/object_detection/android

Let me know if you need any additional information, and I’ll be happy to assist. Thank you for your time and support!

**Comment by gaikwadrahul8** [comment]
Hi, @roshni-warrantylife

I apologize for the delayed response, I was trying to replicate the same behavior from my end with your provided Github repo and I'm getting error messages please refer this error [log file](https://pastebin.com/juJnHENQ) so could you please try from your end and see is it working as expected or not ? it seems there might be some package versions compatibility or Gradle version mismatch ?

Thank you for your cooperation and patience.

**Comment by roshni-warrantylife** [comment]
Thanks for sharing the error log. I've updated the code in the GitHub repo to address possible Gradle or package version issues. Please try again using this [link](https://github.com/roshni-warrantylife/object-detection/tree/master/lite/examples/object_detection/android) and let me know if it works as expected.

If the issue persists, feel free to share the updated logs for further review.

Thanks for your patience!

**Comment by gaikwadrahul8** [comment]
Hi, @roshni-warrantylife

Thank you for providing the updated github repo, I'm able to build and run your project successfully with Android virtual device with `Pixel 5 API 35` but I'm getting below output so are you using actual device or AVD ( I gave permission to access  camera for device from AVD) ? or Am I missing something here ?

Thank you for your cooperation and patience.

![image](https://github.com/user-attachments/assets/a33fb172-ed5c-4474-bff8-bd39e0509ffc)

**Comment by roshni-warrantylife** [comment]
Thank you for your feedback and for successfully building and running the project on the Android Virtual Device (Pixel 5 API 35). To clarify, I am testing the project on an actual physical device. This might explain the difference in the output you're seeing. If possible, could you try running the app on an actual device to see if the output differs? 

Thank you for your patience and cooperation as we troubleshoot this!

**Comment by gaikwadrahul8** [comment]
Hi, @pkgoogle
Please take look into this issue. Thank you

**Comment by pkgoogle** [comment]
Hi @arfaian, can you please take a look? Thanks.

**Comment by gaikwadrahul8** [comment]
Hi, @roshni-warrantylife 
Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/59

Let us know if you have any questions. Thanks.
