### ISSUE TITLE
Crash in `tf.raw_ops.UnsortedSegmentJoin/UnsortedSegmentMin/UnsortedSegmentMax/UnsortedSegmentProd/UnsortedSegmentSum`

### ISSUE THREAD

**Issue by x0w3n** [tensorflow/tensorflow#69779]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.16

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 22.04.3 LTS (x86_64)

### Python version

3.9.13

### Current behavior?

On specific input, These APIs will output "The session crashed because it took up all available RAM."
Furthermore，tf.raw_ops.UnsortedSegmentJoin triggered Aborted (core dumped). 

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/14cpQrFAGZtNXXPvQzXGIYxOmJxIKhJ9q?usp=sharing
```

### Relevant log output

```shell
Jun 14, 2024, 9:37:23 PM	WARNING	WARNING:root:kernel 971d9681-81a9-4140-92f6-1ae620993b21 restarted
Jun 14, 2024, 9:37:23 PM	INFO	KernelRestarter: restarting kernel (1/5), keep random ports
Jun 14, 2024, 9:37:23 PM	WARNING	2024-06-14 13:37:23.763910: F tensorflow/core/framework/tensor_shape.cc:419] Check failed: 0 <= new_num_elements (0 vs. -1)
Jun 14, 2024, 9:37:16 PM	WARNING	2024-06-14 13:37:16.149795: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Jun 14, 2024, 9:37:14 PM	WARNING	To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Jun 14, 2024, 9:37:14 PM	WARNING	2024-06-14 13:37:14.046722: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
Jun 14, 2024, 9:31:38 PM	INFO	Kernel started: 971d9681-81a9-4140-92f6-1ae620993b21, name: python3
Jun 14, 2024, 9:23:53 PM	INFO	Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Jun 14, 2024, 9:23:53 PM	INFO	http://172.28.0.12:9000/
Jun 14, 2024, 9:23:53 PM	INFO	Jupyter Notebook 6.5.5 is running at:
```

**Comment by tilakrayal** [comment]
@x0w3n,
For UnsortedSegmentProd, we have below logic implemented and also reason for different implementation on CPU and GPU is:
num_segments should equal the number of distinct segment IDs.
On CPU, values in segment_ids are always validated to be less than num_segments, and an error is thrown
for out-of-bound indices.
On GPU, this does not throw an error for out-of-bound indices. On Gpu, out-of-bound indices result in safe but unspecified behavior, which may include ignoring out-of-bound indices or outputting a tensor with a 0 stored in the first
dimension of its shape if num_segments is 0.
