### ISSUE TITLE
iPython Tensorflow import error

### ISSUE THREAD

**Issue by DolanDack** [tensorflow/tensorflow#6977]
I am trying to install Tensorflow GPU on a different environment than my original anaconda root. So I followed the instruction on the website, installed CUDA 8, cuDNN 5.1, and tensorflow on a new Tensorflow environment. 

When I execute the import tensorflow on Spyder - iPython I get his error:

![tsfl4](https://cloud.githubusercontent.com/assets/21122937/22152365/7e7ebde0-df1a-11e6-8392-4a9c974e3f4b.jpeg)

But when I try to import it from Python then it works fine:

![tsfl 5](https://cloud.githubusercontent.com/assets/21122937/22152403/b7f02208-df1a-11e6-950e-0538306440de.jpeg)

PS: The same happens when I tried to install the simple tensorflow on my original root environment, works on python but not on ipython. 

Any suggestions please? Thank you.

**Comment by asimshankar** [comment]
This question is probably better asked on [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) as we try to keep the github issues focused on bugs and feature requests.

**Comment by DolanDack** [comment]
Thanks but are you sure this is not a bug? It works on Python but not on iPython. This is weird.

**Comment by DolanDack** [comment]
Apparently there was a bug https://github.com/spyder-ide/spyder/issues/3987.
Thanks @asimshankar
