### ISSUE TITLE
OpenCL Support for TensorFlow -- When is official support coming for macOS?

### ISSUE THREAD

**Issue by shyamalschandra** [tensorflow/tensorflow#6978]
When will an official build of TensorFlow for the latest release be available for use with OpenCL-enabled graphics cards?  Should I fork a version and then hope to commit?  Is this something the core team is interested in because I have a NVIDIA-enabled iMac that is >3 years old and I cannot accelerate my computation for different projects.  What is possible within the next year?

**Comment by asimshankar** [comment]
Closing this out as a duplicate of #22 , which tracks OpenCL support.
