### ISSUE TITLE
Feature Request: extend platform.flags (~ python-gflags)

### ISSUE THREAD

**Issue by haeusser** [tensorflow/tensorflow#6979]
Hello everyone,

I would like to suggest to incorporate more flags into the platform.flags package.

In particular:
DEFINE_multi
DEFINE_multi_float
DEFINE_multi_int

Thank you,
Philip

**Comment by yaroslavvb** [comment]
I believe things are transitioning away from platform.flags and new code is suggested to use `argparse`, could you do those things in `argparse` instead?

**Comment by vrv** [comment]
Yes, please use argparse instead. We do not intend to extend the current flags library. Thanks!
