### ISSUE TITLE
Immediate Assistance Required: Issue with Converting Keras Model to TFLite

### ISSUE THREAD

**Issue by orikkwak** [tensorflow/tensorflow#69811]
### 1. System information

- OS Platform and Distribution : Windows 10 / flutter 3.19.5 /dart 3.3.3 / python 3.12.4
- TensorFlow installation : pip package
- TensorFlow library : 2.16.1

#### Option B: Paste your code here or provide a link to a custom end-to-end colab
import os
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_hub as hub
import warnings

# 경고 메시지 무시
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=FutureWarning)
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # TensorFlow의 INFO 및 WARNING 메시지 무시

# 데이터 로드 및 전처리 함수
def load_data():
    def preprocess(image, label):
        try:
            image = tf.image.resize(image, (224, 224))
            image = image / 255.0  # 정규화
        except Exception as e:
            print(f"Error in preprocessing: {e}")
            return None, None
        return image, label

    train_dataset, test_dataset = tfds.load('cifar10', split=['train', 'test'], as_supervised=True)
    train_dataset = train_dataset.map(preprocess, num_parallel_calls=tf.data.AUTOTUNE)
    train_dataset = train_dataset.filter(lambda x, y: x is not None)  # 예외 처리된 데이터 제외
    train_dataset = train_dataset.batch(32).prefetch(tf.data.AUTOTUNE)

    test_dataset = test_dataset.map(preprocess, num_parallel_calls=tf.data.AUTOTUNE)
    test_dataset = test_dataset.filter(lambda x, y: x is not None)  # 예외 처리된 데이터 제외
    test_dataset = test_dataset.batch(32).prefetch(tf.data.AUTOTUNE)

    return train_dataset, test_dataset

# 모델 클래스 정의
class EfficientNetLiteModel(tf.keras.layers.Layer):
    def __init__(self):
        super(EfficientNetLiteModel, self).__init__()
        effnet_lite_url = "https://tfhub.dev/tensorflow/efficientnet/lite0/feature-vector/2"
        self.effnet_lite_layer = hub.KerasLayer(effnet_lite_url, trainable=False)
        self.dense_layer = tf.keras.layers.Dense(10)  # softmax 활성화 함수 제거

    def call(self, inputs):
        outputs = self.effnet_lite_layer(inputs)
        outputs = self.dense_layer(outputs)
        return outputs

# 모델 생성 함수
def build_model():
    model = tf.keras.Sequential([
        EfficientNetLiteModel()
    ])
    model.build(input_shape=(None, 224, 224, 3))
    model.compile(optimizer='adam',
                  loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                  metrics=['accuracy'])
    return model

# 모델 학습 함수
def train_model(model_name):
    train_dataset, test_dataset = load_data()
    model = build_model()

    model.fit(train_dataset, epochs=3, validation_data=test_dataset)

    # 여러 최적화 옵션으로 모델 저장
    export_quantized_model(model, model_name, tf.lite.Optimize.DEFAULT, "default")
    export_quantized_model(model, model_name, tf.lite.Optimize.OPTIMIZE_FOR_LATENCY, "latency")
    export_quantized_model(model, model_name, tf.lite.Optimize.OPTIMIZE_FOR_SIZE, "size")

    # Keras 모델 저장
    model.save(f"{model_name}.h5")

# 정량화된 TFLite 모델 내보내기
def export_quantized_model(model, model_name, optimization, suffix):
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [optimization]
    
    # 입력 형상 지정을 위한 대표 데이터셋 생성
    def representative_dataset():
        for images, _ in load_data()[0].take(100):
            data = tf.cast(images, tf.float32)
            yield [data]

    converter.representative_dataset = representative_dataset

    # 대표 데이터셋 생성자
    def representative_dataset_gen():
        for images, _ in load_data()[0].take(100):
            yield [images]
            
    converter.representative_dataset = representative_dataset_gen
    tflite_quant_model = converter.convert()

    tflite_model_file = f"{model_name}_quant_{suffix}.tflite"
    with open(tflite_model_file, 'wb') as f:
        f.write(tflite_quant_model)

# TFLite 모델 평가 함수
def evaluate_tflite_model(tflite_model_path, test_dataset):
    # TFLite 모델 로드
    interpreter = tf.lite.Interpreter(model_path=tflite_model_path)
    interpreter.allocate_tensors()

    input_index = interpreter.get_input_details()[0]['index']
    output_index = interpreter.get_output_details()[0]['index']

    # 정확도 평가
    total_seen = 0
    num_correct = 0

    for images, labels in test_dataset:
        interpreter.set_tensor(input_index, images)
        interpreter.invoke()
        predictions = interpreter.get_tensor(output_index)

        predicted_labels = tf.argmax(predictions, axis=1)
        num_correct += tf.reduce_sum(tf.cast(predicted_labels == labels, tf.int32)).numpy()
        total_seen += images.shape[0]

    accuracy = num_correct / total_seen
    print(f"TFLite 모델 ({tflite_model_path}) 정확도: {accuracy:.4f}")

# 메인 함수
def main():
    model_name = "efficientnet-lite0"
    train_model(model_name)  # 여러 최적화된 모델 생성
    
    # 학습된 TFLite 모델 평가
    _, test_dataset = load_data()
    evaluate_tflite_model(f"{model_name}.tflite", test_dataset)
    evaluate_tflite_model(f"{model_name}_quant_default.tflite", test_dataset)
    evaluate_tflite_model(f"{model_name}_quant_latency.tflite", test_dataset)
    evaluate_tflite_model(f"{model_name}_quant_size.tflite", test_dataset)

if __name__ == "__main__":
    main()

### 3. Failure after conversion
2024-06-15 07:33:32.135707: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-15 07:33:33.475807: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From D:\getxgallery\myenv\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Epoch 3/3
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 0s 324ms/step - accuracy: 0.9128 - loss: 0.25622024-06-15 08:03:13.894773: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
         [[{{node IteratorGetNext}}]]
2024-06-15 08:05:09.110888: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence
         [[{{node IteratorGetNext}}]]
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 623s 398ms/step - accuracy: 0.9128 - loss: 0.2562 - val_accuracy: 0.8921 - val_loss: 0.3063
Traceback (most recent call last):
  File "D:\getxgallery\model_training\gallery_model_training\test.py", line 138, in <module>
    main()
  File "D:\getxgallery\model_training\gallery_model_training\test.py", line 128, in main
    train_model(model_name)  # 여러 최적화된 모델 생성
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\getxgallery\model_training\gallery_model_training\test.py", line 67, in train_model
    export_quantized_model(model, model_name, tf.lite.Optimize.DEFAULT, "default")
  File "D:\getxgallery\model_training\gallery_model_training\test.py", line 93, in export_quantized_model
    tflite_quant_model = converter.convert()
                         ^^^^^^^^^^^^^^^^^^^
  File "D:\getxgallery\myenv\Lib\site-packages\tensorflow\lite\python\lite.py", line 1175, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\getxgallery\myenv\Lib\site-packages\tensorflow\lite\python\lite.py", line 1129, in _convert_and_export_metrics  
    result = convert_func(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\getxgallery\myenv\Lib\site-packages\tensorflow\lite\python\lite.py", line 1641, in convert
    self._freeze_keras_model()
  File "D:\getxgallery\myenv\Lib\site-packages\tensorflow\lite\python\convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
    ^^^^^^^^^^^^^^^^^^^^^
  File "D:\getxgallery\myenv\Lib\site-packages\tensorflow\lite\python\convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\getxgallery\myenv\Lib\site-packages\tensorflow\lite\python\lite.py", line 1582, in _freeze_keras_model
    input_signature = _model_input_signature(
                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\getxgallery\myenv\Lib\site-packages\tensorflow\lite\python\tflite_keras_util.py", line 84, in model_input_signature
    input_specs = model._get_save_spec(  # pylint: disable=protected-access
                  ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Sequential' object has no attribute '_get_save_spec'. Did you mean: '_set_save_spec'?

**Comment by sawantkumar** [comment]
Hi @orikkwak ,

I tried replicating your issue in colab, but it keeps crashing because i run out of VRAM while training on the Tesla T4 GPU . Can you please share me the saved model instead ?
