### ISSUE TITLE
AttributeError: 'module' object has no attribute 'inv'

### ISSUE THREAD

**Issue by s6norit4** [tensorflow/tensorflow#6981]
Hi there,

I have an issue when I am trying to inverse a tensor as shown below

>>> import tensorflow as tf
>>> a = tf.placeholder(tf.float32)
>>> tf.inv(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'inv'

Operation System: mac os x 10.11.6
Python 2.7.13
I installed tensor flow using pip install tensorflow 
>>> tf.__version__
'0.12.1'

If someone could help out, that would be cool! Thanks!

**Comment by asimshankar** [comment]
We're going through some API churn as we try to stabilize things for the 1.0 release (and can provide stability for all 1.x release as per our [versioning policy](https://www.tensorflow.org/resources/versions)). See [RELEASE.md](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) for changes.

In this particular case:
`tf.inv` has been renamed to be `tf.reciprocal` (component-wise reciprocal) to avoid confusion with `np.inv` which is matrix inversion.

Apologies for the churn, once we hit 1.0, things should be much more stable.

Hope that help!

**Comment by s6norit4** [comment]
It’s perfect! Thanks a bunch!
