### ISSUE TITLE
Too many duplicate debug logs

### ISSUE THREAD

**Issue by AnyLifeZLB** [tensorflow/tensorflow#69825]
how can I remove duplicate debug logs when using tflife in android 

    implementation 'org.tensorflow:tensorflow-lite:2.16.1'

logs below 
  
![image](https://github.com/tensorflow/tensorflow/assets/15169396/9ee29152-2599-4155-9c2d-bacf463bea2e)

**Comment by sawantkumar** [comment]
Hi @AnyLifeZLB ,

You can use several filters to remove the duplicate logs. Please take a look at [this](https://developer.android.com/studio/debug/logcat#key-value-search) . Let me know if this works for you.
