### ISSUE TITLE
Non-deprecated tf.keras.preprocessing alternatives don't cover properly all the deprecated features

### ISSUE THREAD

**Issue by SMH17** [tensorflow/tensorflow#69834]
### Issue type

Others

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.16.1

### Custom code

No

### Current behavior?

[`tf.keras.preprocessing`](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing) is deprecated . `ImageDataGenerator `is deprecated, but still there isn't any non-deprecated approach to consistently cover its features despite it's been a while already  since the deprecation mark appeared.

E.g. 
Consider you want to include random translations, rotations, and shear augmentations (very common augmentations, nothing unusual), with `ImageDataGenerator` you could do this in a very practical and concise way without forcing you to create your own augmentation functions (and if you needed more than built in features nothing prevented you to use `preprocessing_function `argument to pass your custom function or using different approaches). 

Ok we know that _"Google way"_ is "deprecate code in bulk" ...but what is supposed to be the recommended alternative approach now? 
`tf.keras.utils.image_dataset_from_directory`
doesn't support any augmentation and so it is needed to manually combine it with image transformation functions to achieve same result,
but if as alternative you try to use a preprocessing pipeline with functions of `tf.image`, in [`tf.image`](https://www.tensorflow.org/api_docs/python/tf/image), shear transformation seems surprisingly missing.

if instead you try to use as alternative [`tf.keras.layers`](https://www.tensorflow.org/api_docs/python/tf/keras/layers) there are various transformation layers, but not for everything in deprecation wagon and shear transformation seems missing also there, and `tf.keras.preprocessing.image.random_shear` is deprecated too.

(Not mentioning the _past_ deprecation of `tfa.image.*` and `tf.contrib.keras.preprocessing.*`)

### Standalone code to reproduce the issue

```shell
not needed
```

**Comment by tilakrayal** [comment]
@SMH17,
Generally, if the particular API is deprecated, the new API will be serving the features of older ones with some other modifications. Also the API which you are mentioning [tf.keras.preprocessing](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing) is related to Keras. Could you please feel free to raise the issue in [keras-team/Keras](https://github.com/keras-team/keras/issues) repo for correct resolution. 
https://keras.io/api/layers/preprocessing_layers/#image-augmentation-layers

Thank you!

**Comment by SMH17** [comment]
> @SMH17, Generally, if the particular API is deprecated, the new API will be serving the features of older ones with some other modifications. Also the API which you are mentioning [tf.keras.preprocessing](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing) is related to Keras. Could you please feel free to raise the issue in [keras-team/Keras](https://github.com/keras-team/keras/issues) repo for correct resolution. https://keras.io/api/layers/preprocessing_layers/#image-augmentation-layers
> 
> Thank you!

Referring to the example above. In Keras I don't see any deprecation mark in [RandomShear layer](https://keras.io/api/keras_cv/layers/augmentation/random_shear/) that seems has been moved in keras-cv package but I cannot find any non deprecated alternative in Keras module integrated in TensorFlow. 
Image transformations should be consistently included in TensorFlow.

**Comment by tilakrayal** [comment]
@SMH17,
Apologies for the delay. As the mentioned API [keras.preprocessing](https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing) i is more related to Keras, could you please raise the new issue in the keras-team/Keras repo for [here](https://github.com/keras-team/keras/issues) for the quick resolution. Thank you!
