### ISSUE TITLE
graph_metric.py removed?

### ISSUE THREAD

**Issue by 201power** [tensorflow/tensorflow#6983]
Hello, 

Is graph_metric.py removed from TF? This is a useful feature for me. Can we add it back?

https://github.com/tensorflow/tensorflow/blob/fe454464681b036ff7fed3e42c6bb541fa52dd7c/tensorflow/python/tools/graph_metrics.py

**Comment by vrv** [comment]
I think it has been replaced by the more flexible tfprof tool: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/tfprof and https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/tfprof

(not sure what the difference between the two directories is, @petewarden )
