### ISSUE TITLE
build arm image use docker

### ISSUE THREAD

**Issue by Jerry-yz** [tensorflow/tensorflow#69849]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

v1.0

### Custom code

Yes

### Current behavior?

how to build tensorflow arm image use docker

### Standalone code to reproduce the issue

```shell
i need help
```

**Comment by Venkat6871** [comment]
Hi **@Jerry-yz** ,
- It looks like you are using an older Version of Tensorflow (1.0). Many bugs have been fixed in the latest version. Can you please execute your code using Latest Version (2.16.1) and let us know if the issue still persists?
- Please go through this [documentation](https://www.tensorflow.org/install/docker) for you reference. In this documentation you will get installation instructions using docker.
Thank you!

**Comment by Jerry-yz** [comment]
> Hi **@Jerry-yz** ,
> 
> * It looks like you are using an older Version of Tensorflow (1.0). Many bugs have been fixed in the latest version. Can you please execute your code using Latest Version (2.16.1) and let us know if the issue still persists?
> * Please go through this [documentation](https://www.tensorflow.org/install/docker) for you reference. In this documentation you will get installation instructions using docker.
>   Thank you!

thanks you reply, i not bug i want to docker image arm tensorflow, i not know how to build it

**Comment by Jerry-yz** [comment]
> Hi **@Jerry-yz** ,
> 
> * It looks like you are using an older Version of Tensorflow (1.0). Many bugs have been fixed in the latest version. Can you please execute your code using Latest Version (2.16.1) and let us know if the issue still persists?
> * Please go through this [documentation](https://www.tensorflow.org/install/docker) for you reference. In this documentation you will get installation instructions using docker.
>   Thank you!

how to build arch arm image, the document not describe

**Comment by Venkat6871** [comment]
Hi **@Jerry-yz** ,
- Apologies for the delay, Could you please confirm if my understanding is correct like you want to build a docker image for tensorflow that support Arm architecture?
Thank you!
