### ISSUE TITLE
API changes: Missing RNN module

### ISSUE THREAD

**Issue by kevinashaw** [tensorflow/tensorflow#6984]
This is a continuation #6973.  Given the ongoing API changes with r0.12 and the shortage of documentation/samples, it seems that API questions must be posed here.  
We had previously working code as follows:
```
lstm_cell_1 = tf.nn.rnn_cell.BasicLSTMCell(n_hidden)
outputs, states = tf.nn.rnn(lstm_cell_1, Xnew, dtype=tf.float32)
```
The new code should be something like:
```
lstm_cell_1 = tf.contrib.rnn.BasicLSTMCell(n_hidden)
outputs, states = tf.contrib.rnn(lstm_cell_1, Xnew, dtype=tf.float32)
```
But `tf.contrib.rnn` no longer exists.  I've tried `tf.contrib.rnn.MultiRNNCell` and `tf.contrib.rnn.fused_rnn_cell` but am told that `TypeError: 'module' object is not callable`.
What is the new method to fuse together Basic LSTM cells?

**Comment by yaroslavvb** [comment]
cc @ebrevdo , the expert on all things RNN related

**Comment by asimshankar** [comment]
Apologies for the churn and confusion.
@ebrevdo and @xiejw can comment, but I believe the reasoning for the separation is because we're moving some parts into core.

`BasicLSTMCell` can be found in `tf.nn.rnn_cell.BasicLSTMCell`. Same for `MultiRNNCell`.

The [API docs](https://www.tensorflow.org/api_docs/python/) are a good place to search for these.

Again, apologies, this churn should become a non-issue after 1.0.

**Comment by kevinashaw** [comment]
Thank you.  But my question still stands.  
Given that `tf.contrib.rnn` does not exist.  What is the replacement for it?  What method is used to fuse together multiple RNN cells?
I've tried the following:
```
lstm_cell_1 = tf.contrib.rnn.BasicLSTMCell(n_hidden)
outputs, states = tf.contrib.rnn.MultiRNNCell(lstm_cell_1, Xnew)
```
But get the following error message:
```
TypeError: 'MultiRNNCell' object is not iterable
```
So, What method is used to fuse together multiple RNN cells?

**Comment by kevinashaw** [comment]
Thank you.  But my question still stands.  
Given that `tf.contrib.rnn` does not exist.  What is the replacement for it?  What method is used to fuse together multiple RNN cells?
I've tried the following:
```
lstm_cell_1 = tf.contrib.rnn.BasicLSTMCell(n_hidden)
outputs, states = tf.contrib.rnn.MultiRNNCell(lstm_cell_1, Xnew)
```
But get the following error message:
```
TypeError: 'MultiRNNCell' object is not iterable
```
So, What method is used to fuse together multiple RNN cells?

**Comment by asimshankar** [comment]
I apologize, I misunderstood, it seem you're looking for where these functions are at head, as opposed to the last release, right? The docs, FWIW, talk about the release and not the current state of the head of the repository.

It is possible for you to use the latest release (0.12.1) for now (in which your original sample with `tf.nn.rnn_cell.BasicLSTMCell` and `tf.nn.rnn` should work)? Code at head is frequently changing and will provide a moving target. Once release, the compatibility tool at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility should help you switch between releases.

As of right now, is `tf.contrib.rnn.static_rnn` what you're looking for?

**Comment by kevinashaw** [comment]
Hi Asim,
Thanks for the help.  I will delete the other issue.  
When an issue is closed, I am never quite sure if anyone ever sees it again, so I generally create a new one.  Closed issues seem to disappear.  It would be nice if we could be given a short while to respond.
I will change to r0.12.1.  I just need to find the `pip` to force a downgrade.

FYI.  I changed the code to:
```
lstm_cell_1 = tf.contrib.rnn.BasicLSTMCell(n_hidden)
outputs, states = tf.contrib.rnn.static_rnn(lstm_cell_1, Xnew, dtype=tf.float32)
```
For the record, here is the error message:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-27-ae6b63faf2e1> in <module>()
     43 l2 = lambda_loss_amount * sum(tf.nn.l2_loss(tf_var) for tf_var in tf.trainable_variables())
     44 # L2 loss prevents this overkill neural network to overfit the data
---> 45 cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(pred, y)) + l2 # Softmax loss
     46 optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost) # Adam Optimizer
     47 

/Users/kevin/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.pyc in softmax_cross_entropy_with_logits(_sentinel, labels, logits, dim, name)
   1576   """
   1577   _ensure_xent_args("softmax_cross_entropy_with_logits", _sentinel,
-> 1578                     labels, logits)
   1579 
   1580   # TODO(pcmurray) Raise an error when the labels do not sum to 1. Note: This

/Users/kevin/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.pyc in _ensure_xent_args(name, sentinel, labels, logits)
   1531   if sentinel is not None:
   1532     raise ValueError("Only call `%s` with "
-> 1533                      "named arguments (labels=..., logits=..., ...)" % name)
   1534   if labels is None or logits is None:
   1535     raise ValueError("Both labels and logits must be provided.")

ValueError: Only call `softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)
```

**Comment by asimshankar** [comment]
I'm a bit confused about your error message above. That is when compiling from source at head, right? In general, I'd be weary to spending time to debug that (since the code is changing frequently), but if for some reason you do need to use sources at head please to provide a full snippet that reproduces the error. For example, the following does not lead to any errors:

```python
import tensorflow as tf
lstm_cell_1 = tf.contrib.rnn.BasicLSTMCell(1)
outputs, states = tf.contrib.rnn.static_rnn(lstm_cell_1, [tf.constant([[1.0],[1.0]], dtype=tf.float32)], dtype=tf.float32)
```

That said, hopefully 0.12.1 works out for you. Do let me know.

**Comment by kevinashaw** [comment]
Hi Asim,
No troubles.  But yes, that was from 0.12.head.
I only reported the error for your information.
I just downgraded to 0.12.1.  For the record, I used this command:
```
pip install --ignore-installed --upgrade 'tensorflow==0.12.1'
```
Give me a minute and I'll report on the status after I rollback.

**Comment by kevinashaw** [comment]
Okay, still no joy.
I downgraded to r0.12.1 using `pip` and checked out tag `0.12.1` in git.
I rolled back the file changes, so that the crucial lines read:
```
lstm_cell_1 = tf.nn.rnn_cell.BasicLSTMCell(n_hidden)
outputs, states = tf.nn.rnn(lstm_cell_1, Xnew, dtype=tf.float32)
```
Those lines now run properly, but when I start training, I now get the following.  I should note that nowhere in my file is `float64` even mentioned (I searched):
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-5bf2accf7d95> in <module>()
     22 while step * batch_size <= training_iters:
     23     batch_xs =         extract_batch_size(X_train, step, batch_size)
---> 24     batch_ys = one_hot(extract_batch_size(y_train, step, batch_size))
     25 
     26     # Fit training using batch data

<ipython-input-12-9cf8fb729401> in one_hot(y_)
     20     y_ = y_.reshape(len(y_))
     21     n_values = np.max(y_) + 1
---> 22     return np.eye(n_values)[np.array(y_, dtype=np.int32)]  # Returns FLOATS

/Users/kevin/anaconda2/lib/python2.7/site-packages/numpy/lib/twodim_base.pyc in eye(N, M, k, dtype)
    178     if M is None:
    179         M = N
--> 180     m = zeros((N, M), dtype=dtype)
    181     if k >= M:
    182         return m

TypeError: 'numpy.float64' object cannot be interpreted as an index
```

**Comment by kevinashaw** [comment]
For the record, here is the training code:
```
# To keep track of training's performance
test_losses = []
test_accuracies = []
train_losses = []
train_accuracies = []

print("Starting session: MaxIter = %i"%training_iters)

# Launch the graph
sess = tf.InteractiveSession(config=tf.ConfigProto(log_device_placement=True))
init = tf.initialize_all_variables()
sess.run(init)
timestart = datetime.datetime.now() # Start time in seconds
timeprev  = datetime.datetime.now() # Start time in seconds
countprev = 0
ratelist = []
boxcarcount = 10

print("Starting training...")
# Perform Training steps with "batch_size" iterations at each loop
step = 1
while step * batch_size <= training_iters:
    batch_xs =         extract_batch_size(X_train, step, batch_size)
    batch_ys = one_hot(extract_batch_size(y_train, step, batch_size))

    # Fit training using batch data
    output, loss, acc = sess.run(
        [optimizer, cost, accuracy],
        feed_dict={
            x: batch_xs, 
            y: batch_ys,
            keep_prob: DO_keep_prob
        }
    )
    train_losses.append(loss)
    train_accuracies.append(acc)
    
    # Evaluate network only at some steps for faster training: 
    if (step*batch_size % display_iter == 0) or (step == 1) or (step * batch_size > training_iters):
        
        # To not spam console, show training accuracy/loss in this "if"
        print("#{:07}: Training Loss={:.3f}, Acc={:4.2f}; ".format(step*batch_size, loss, acc), end="")
        
        # Evaluation on the test set (no learning made here - just evaluation for diagnosis)
        loss, acc = sess.run(
            [cost, accuracy], 
            feed_dict={
                x: X_test,
                y: one_hot(y_test),
                keep_prob: 1.0
            }
        )
        timenow    = datetime.datetime.now()
        duration   = timenow - timeprev
        countnow   = step*batch_size
        countdelta = countnow - countprev
        rate       = countdelta/duration.seconds
        ratelist.append(rate)
        rateavg = sum(ratelist)/len(ratelist)
        duration   = timenow - timestart
        durStr     = datetime.timedelta(seconds = duration.seconds)
        
        test_losses.append(loss)
        test_accuracies.append(acc)
        print("Test Loss={:.3f}, Acc={:4.2f}; Dur={:s} / {:3.0f}Hz".format(loss, acc, durStr, rateavg))
        timeprev  = timenow
        countprev = countnow
        if len(ratelist)>boxcarcount:
            ratelist = ratelist[1:]

    step += 1

print("Optimization Finished!")
```

**Comment by kevinashaw** [comment]
This seems to be my issue.  I'm working on it. -K

**Comment by shaox058** [comment]
Hi @kevinashaw ,

I have the same issue. Are you using windows or linux? Is the downgrade version working for windows?

Thanks,
Harry

**Comment by kevinashaw** [comment]
Downgrade version worked well for me.  Though I am now in the process of moving to 1.0.1.
I used the following to force the version:
```
pip install tensorflow==0.12.1
```
