### ISSUE TITLE
cannot import name 'mean_squared_error' from 'tensorflow.keras.losses

### ISSUE THREAD

**Issue by GreatKampfstern** [tensorflow/tensorflow#69851]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.16.1

### Custom code

No

### OS platform and distribution

Linux Ubuntu 22.04.2

### Python version

3.10.12

### Current behavior?

When I import auto_encoder I get following error:
```
    from tensorflow.keras.losses import mean_squared_error
ImportError: cannot import name 'mean_squared_error' from 'tensorflow.keras.losses'
```
This also happens on Windows Powershell, all modules are on the latest stable version

If I go into the file '/home/user/.local/lib/python3.10/site-packages/keras/_tf_keras/keras/losses/__init__.py' and change the line 
`from keras.src.losses.losses import mean_squared_error as mse` to
`from keras.src.losses.losses import mean_squared_error` it works

### Standalone code to reproduce the issue

```shell
from pyod.models.auto_encoder import AutoEncoder
```

### Relevant log output

```shell
On Bash:

2024-06-17 11:11:41.210014: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-17 11:11:42.147055: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.10/site-packages/pyod/models/auto_encoder.py", line 30, in <module>
    from tensorflow.keras.losses import mean_squared_error
ImportError: cannot import name 'mean_squared_error' from 'tensorflow.keras.losses' (/home/user/.local/lib/python3.10/site-packages/keras/_tf_keras/keras/losses/__init__.py)

In Jupyter Notebook:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[3], line 1
----> 1 from pyod.models.auto_encoder import AutoEncoder

File ~/.local/lib/python3.10/site-packages/pyod/models/auto_encoder.py:30
     28     from tensorflow.keras.layers import Dense, Dropout
     29     from tensorflow.keras.regularizers import l2
---> 30     from tensorflow.keras.losses import mean_squared_error
     33 # noinspection PyUnresolvedReferences,PyPep8Naming,PyTypeChecker
     34 class AutoEncoder(BaseDetector):

ImportError: cannot import name 'mean_squared_error' from 'tensorflow.keras.losses' (/home/user/.local/lib/python3.10/site-packages/keras/_tf_keras/keras/losses/__init__.py)
```

**Comment by sushreebarsa** [comment]
@GreatKampfstern I was able to import 'mean_squared_error' from 'tensorflow.keras.losses , please follow the correct commands as below;
```
!pip install pyod
import tensorflow as tf
from pyod.models.auto_encoder import AutoEncoder
from tensorflow.keras.losses import mean_squared_error

```
Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/fc1d450185fd38628007e8e08de9540b/69851.ipynb#scrollTo=ZSzMQaR6-rwo) for your reference. Thank you!

**Comment by GreatKampfstern** [comment]
If I first execute 
```
!pip install --upgrade pyod
!pip install --upgrade tf-keras
!pip install --upgrade tensorflow
```
and then do
`from pyod.models.auto_encoder import AutoEncoder`
I get the same error:

> ImportError                               Traceback (most recent call last)
> 
> [<ipython-input-10-16f16faeafae>](https://localhost:8080/#) in <cell line: 1>()
> ----> 1 from pyod.models.auto_encoder import AutoEncoder
> 
> [/usr/local/lib/python3.10/dist-packages/pyod/models/auto_encoder.py](https://localhost:8080/#) in <module>
>      28     from tensorflow.keras.layers import Dense, Dropout
>      29     from tensorflow.keras.regularizers import l2
> ---> 30     from tensorflow.keras.losses import mean_squared_error
>      31 
>      32 
> 
> ImportError: cannot import name 'mean_squared_error' from 'tensorflow.keras.losses' (/usr/local/lib/python3.10/dist-packages/keras/_tf_keras/keras/losses/__init__.py)

Sorry if the first three lines are stupid, I just thought (when I did it on my computer) that I first have to install and upgrade all packages. And as far as I know it should still work if I upgrade everything.

**Comment by sushreebarsa** [comment]
@GreatKampfstern `keras.src.losses.losses` refers to an internal path within the Keras source code which is not recommended for use.  The following command is recommended for use;
```
from tensorflow.keras.losses import mean_squared_error

```
Firstly install pyod and then run the command for AutoEncoder as below;
```
!pip install pyod

from pyod.models.auto_encoder import AutoEncoder

```
Please have a look at this [gist](https://colab.research.google.com/gist/sushreebarsa/672cb0955efd4f879559646b22a9098d/69851.ipynb). Thank you!

**Comment by GreatKampfstern** [comment]
> @GreatKampfstern `keras.src.losses.losses` refers to an internal path within the Keras source code which is not recommended for use. The following command is recommended for use;
> 
> ```
> from tensorflow.keras.losses import mean_squared_error
> ```
Yeah I wasn't doing that.

But anyways thank you, you showed me that it's enough to just install pyod. So I uninstalled every tensorflow and keras module I had installed and now it works.
And in my Gist in the comment above it now works, even tough I didn't change anything.

**Comment by jaikumar-99** [comment]
The name is changed to MeanSquaredError.please replace mean_squared_error with MeanSquaredError. This Works for me thank you
