### ISSUE TITLE
API changes: Missing RNN Module (continued)

### ISSUE THREAD

**Issue by kevinashaw** [tensorflow/tensorflow#6985]
(This is a continuation of issue #6984, which was closed before I could respond.)
Thank you.  But the question is still unanswered.  
Given that `tf.contrib.rnn` no longer exists.  What is the replacement for it?  I've read the docs, but haven't found an answer.  
In other words, what method is used to fuse together multiple RNN cells?
I've tried the following:
```
lstm_cell_1 = tf.contrib.rnn.BasicLSTMCell(n_hidden)
outputs, states = tf.contrib.rnn.MultiRNNCell(lstm_cell_1, Xnew)
```
But get the following error message:
```
TypeError: 'MultiRNNCell' object is not iterable
```
So, What method is used to fuse together multiple RNN cells?

**Comment by asimshankar** [comment]
I posted an update on #6984  as well:
https://github.com/tensorflow/tensorflow/issues/6984#issuecomment-274183963

In summary, I think you're looking for `tf.contrib.rnn.static_rnn`. Let us know if that is it.

That said, if possible, please do use the latest release if possible. Code at head is subject to change and will be hard to constantly keep up with. See my comment in the other issue.

**Comment by kevinashaw** [comment]
Hi Asim,
I will continue to respond to the other issue.   
I assume that you can still see it, even though it was closed?
Aside: It would be really helpful to give us a few minutes to respond before closing issues.  :-)
We can close this and I will continue on the other issue.
Thanks.
Kevin

**Comment by asimshankar** [comment]
Apologies, bad judgement on my part on whether it was a slam dunk or not :)  If not, I wouldn't have closed the issue. Closing this one out, we can continue there.
