### ISSUE TITLE
Improve documentation for custom training loops

### ISSUE THREAD

**Issue by gachombamuthiri** [tensorflow/tensorflow#69853]
I noticed that the documentation for creating custom training loops in TensorFlow is somewhat sparse. It would be helpful to include more examples and a more detailed explanation of the various components involved in custom training loops. Specifically, an example that demonstrates how to handle distributed training with custom loops would be very beneficial.

**Comment by tilakrayal** [comment]
@gachombamuthiri,
Have you got the chance to have a look at this official documents where those are referring to the Custom training loop with Keras and MultiWorkerMirroredStrategy, Custom training and how to write the training loop from scratch with the examples. Could you please refer to the same and let me know if you are looking for the same.

https://www.tensorflow.org/tutorials/distribute/multi_worker_with_ctl
https://www.tensorflow.org/tutorials/customization/custom_training_walkthrough
https://www.tensorflow.org/guide/keras/writing_a_training_loop_from_scratch

Thank you!
