### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'layers'

### ISSUE THREAD

**Issue by MengXiangDing** [tensorflow/tensorflow#69921]
`self.pooled_output = tf.layers.dense(
            first_token_tensor,
            config.hidden_size,
            activation=tf.tanh,
            kernel_initializer=create_initializer(config.initializer_range))`

**error:**
File "BertSimilarity/modeling.py", line 229, in __init__
    self.pooled_output = tf.layers.dense(
AttributeError: module 'tensorflow' has no attribute 'layers'

**Comment by tilakrayal** [comment]
@MengXiangDing,
I suspect you are using the code which is not compatible with the Tensorflow version you are using. **tf.layers.dense** is deprecated in the older versions. Could you please try to use tf.keras.layers.Dense instead. Also please try to convert the code into 2.x version.
https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense

Thank you!

**Comment by sreepujitha123** [comment]
import tensorflow as tf
# Assuming `first_token_tensor` and `config` are already defined
self.pooled_output = tf.keras.layers.Dense(
    config.hidden_size, 
    activation=tf.tanh, 
    kernel_initializer=tf.keras.initializers.RandomNormal(mean=0., stddev=config.initializer_range))(first_token_tensor)
try to change the code in this way 
Thank you!

**Comment by MengXiangDing** [comment]
Thanks everyone, it's been solved.
