### ISSUE TITLE
A tutorial for new dynamic seq2seq

### ISSUE THREAD

**Issue by ematvey** [tensorflow/tensorflow#6994]
New `contrib.seq2seq` made it into master - exciting development! However, the only examples are in the tests. For my project, I've implemented a small but complete example against a toy copy task. Here it is: [notebook](https://github.com/ematvey/tensorflow-seq2seq-tutorials/blob/master/3-seq2seq-native-new.ipynb), [code](https://github.com/ematvey/tensorflow-seq2seq-tutorials/blob/master/model_new.py).

Can I contribute it? I do realise that API is likely not yet complete. I’ll be happy to keep it updated and improve it if needed.

**Comment by asimshankar** [comment]
@ematvey : Thanks very much for doing this! Glad to see it. I'd encourage you to publish your findings, but AFAIK, the new `seq2seq` API isn't in a state to provide official tutorials for just yet. 

CCing @ebrevdo so that he is aware of your notebook, but closing this out for now.
