### ISSUE TITLE
Back-propagating gradients through a sparse tensor?

### ISSUE THREAD

**Issue by zergylord** [tensorflow/tensorflow#6998]
I have a normal feed-forward network that produces a vector v. The elements of v are then used as the non-zero entries of a sparse matrix M (assume the coordinates are predefined). The sparse matrix is then multiplied by a dense vector and a loss is defined on the resulting scalar. I want to back-propagate the loss w.r.t. the weights of the network, which entails going through the sparse matrix. 

This seems like a perfectly reasonable use-case for a sparse matrix, but it appears that such functionality is not supported. Indeed, even calling tf.gradients(M,[v]) produces an error:

> AttributeError: 'SparseTensor' object has no attribute 'value_index'

Am I doing something wrong or am I correct in presuming that this functionality doesn't (yet?) exist? If the latter, then is there a work-around for this particular use-case short of rewriting all of the sparse tensor operations with gradients defined?

**Comment by yaroslavvb** [comment]
cc @martinwicke since he recently answered some q's about state of sparse tensor support

**Comment by martinwicke** [comment]
This is a great question for StackOverflow. It looks to me that there is no bug, but that the error message could be improved. I'll leave this open while I improve this error.

**Comment by zergylord** [comment]
Wait a second -- the error message wasnt the primary concern here. The question was about whether or not my use case is currently  (or planned to be) supported by tensorflow.

**Comment by yaroslavvb** [comment]
Not sure what's the status of sparse gradients is, I see a recent commit referencing gradients and sparse together -- ef489fb3

**Comment by martinwicke** [comment]
If you just pass `M.values` instead, I bet your code will just work. I think I'll just fix this though, just have to add tests.

**Comment by zergylord** [comment]
Yup, that solved it -- thanks!

**Comment by wang150973** [comment]
> If you just pass `M.values` instead, I bet your code will just work. I think I'll just fix this though, just have to add tests.

hi, sir,  I meet the problem too,  if I need  get the gradients wrt the sparse tensor's zero elements, what should I do?

**Comment by martinwicke** [comment]
Use tf.sparse.to_dense first. Since you'll be expanding the tensor for the
backward pass anyway, there's little reason to keep it sparse.

**Comment by martinwicke** [comment]
I can't picture how. 

Note I'm not saying make everything dense. I'm only saying that if you require the gradients of zero elements of a sparse tensor S, compute the gradients of tf.sparse.to_dense(S) instead.

**Comment by 1049451037** [comment]
Oh sorry, I misunderstand what you said. So is there a way that can elegantly activate gradient for the non-zero elements of a sparse tensor?

**Comment by martinwicke** [comment]
Yes, just compute the gradient on the values only, see https://github.com/tensorflow/tensorflow/issues/6998#issuecomment-277367733

**Comment by 1049451037** [comment]
Thank you for your reply! But I still need help because I don't know how to backpropagate the gradients on the SparseTensor after getting a list of gradients. Is there any example?

**Comment by martinwicke** [comment]
The SparseTensor is backed by its tensors (in particular, .values). So if you just a regular TensorFlow optimizer, everything should work as expected if you only want gradients of the non-zero elements.

**Comment by laci37** [comment]
On TF 2.0rc this does not work, the gradient for the sparse_dense_matmul op is not defined.

**Comment by martinwicke** [comment]
Is the gradient only undefined in 2.0? That would be very surprising. I
find it more likely that we never had this gradient. It would be great to
add it -- an issue with this feature request would be a good start.
