### ISSUE TITLE
Potential Memory Leak with Session Closing

### ISSUE THREAD

**Issue by kvamaraju** [tensorflow/tensorflow#700]
Bug: When repeatedly creating and closing sessions on a GPU or CPU (on 0.6.0 release and Jan 5 dev version), memory appears to leak as the python process continually grows in memory usage. Additionally, the time to execute continues to grow. 

Expected behaviour: Once a session is closed, resources allocated should be freed or overwritten.

The following code illustrates the issue with a minimal graph created:

for i in range(0,10000000):
    t0 = time.clock()
    
    sess = tf.Session()
    
    a = tf.placeholder("int16",name = 'a')
    y=tf.identity(a,name='y')
    
    sess.run(y,feed_dict={a:3})
    sess.close()
    
    print time.clock() - t0

The same issue happens even if I use a constant or variable instead of placeholder.

Thanks!

**Comment by martinwicke** [comment]
It looks like you're adding more and more ops to a graph, which is not freed when the session is closed.

**Comment by mrry** [comment]
Martin's answer looks spot on here. The following code should not leak, and if it does let us know and we'll reopen the issue:

```python
for i in range(0,10000000):
  t0 = time.clock()

  with tf.Graph().as_default():
    sess = tf.Session()

    a = tf.placeholder(tf.int16, name='a')
    y = tf.identity(a, name='y')

    sess.run(y, feed_dict={a: 3})
    sess.close()

print time.clock() - t0
```

**Comment by kvamaraju** [comment]
You are correct. It was a misunderstanding on my part of what's being added to the graph.

Thanks!
