### ISSUE TITLE
Build with --define tensorflow_xsmm=1 fails on MacOS Sierra

### ISSUE THREAD

**Issue by mikowals** [tensorflow/tensorflow#7004]
Building current master after the recent commits to enable libxsmm.

    bazel build --copt=-march=native -c opt --define tensorflow_xsmm=1 --verbose_failures //tensorflow/tools/pip_package:build_pip_package

The important error lines (I think) are:

> tensorflow/core/kernels/sparse_matmul_op.cc:1408:3: error: unknown type name 'cpu_set_t'
  cpu_set_t old_cpu_set;
  
> tensorflow/core/kernels/sparse_matmul_op.cc:1413:39: error: use of undeclared identifier 'cpu_set_t'
    ret = sched_getaffinity(0, sizeof(cpu_set_t), &old_cpu_set);

The full result of --verbose_failures is attached.
[tf_libxsmm_error.txt](https://github.com/tensorflow/tensorflow/files/721760/tf_libxsmm_error.txt)

Searching for 'cpu_set_t' on OSX turned up [this code example under heading 2.2](https://github.com/Cibiv/NextGenMap/issues/6) and claims that 'cpu_set_t' is not defined on OSX and Apple's own multithreading code needs to be substituted. So maybe the code using 'cpu_set_t' is not meant to be reached on Macs and the libxsmm code is not ready to be used on my machine.

**Comment by asimshankar** [comment]
@mikowals : Support for libxsmm is experimental (see description of commit https://github.com/tensorflow/tensorflow/commit/9a1e2d5d3d2c6420c410378c385b0c4665cedb9b), so we haven't gotten around to polishing it up.

If you'd like to contribute updates to make this more OS X friendly, do let us know and we can work it out.

FYI @jewillco

**Comment by gunan** [comment]
I think this is being worked on.
@tfboyd has more context on this issue.

**Comment by tfboyd** [comment]
This is still experimental and OS X support will be prioritized after Linux.  The contributions welcome label is intended to suggest that the core team is not likely to work on this feature.  We are hoping to get MKL running on OS X which will add a significant performance boost.  

https://github.com/tensorflow/tensorflow/issues/10685

**Comment by harshini-gadige** [comment]
@tfboyd Hi, are there any contributions for this till date or any implementations from the Tensorflow team? Is it still open for more contributions ?

**Comment by mohantym** [comment]
Hi ! This issue did not replicate with Bazel 5.1.1 , TF nightly (2.9.0rc2) , MacOS (Montorey 12.3.1) . Can we move this to closed status now?
