### ISSUE TITLE
Silent exception when using TFLiteConverter

### ISSUE THREAD

**Issue by BenCrulis** [tensorflow/tensorflow#70051]
I am trying to convert multiple concrete functions to TFLite using the TFLiteConverter with a code looking like this

```python
converter = tf.lite.TFLiteConverter.from_concrete_functions([
    tf.function(tf_moondream.call).get_concrete_function(inp, empty_cache),
    tf.function(tf_moondream.empty_cache).get_concrete_function(),
    tf.function(tf_moondream.compute_embeddings).get_concrete_function(inp),
], tf_moondream)
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS, # enable TensorFlow ops.
]
converter.allow_custom_ops = True
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()
```
However this fails at the last line with

```
/venv/lib64/python3.9/site-packages/tensorflow/lite/python/lite.py", line 1393, in _freeze_concrete_function
    raise ValueError("This converter can only convert a single "
ValueError: This converter can only convert a single ConcreteFunction. Converting multiple functions is under development.
```

 But that is clearly not the real reason as I managed to use the exact same conversion code for saving a TFLite model with multiple concrete functions for another model, in the same project.

By looking at the conversion process with the debugger, I managed to get to this line:

https://github.com/tensorflow/tensorflow/blob/7c487a387b2120d5ddcca6040210ccb4243b7dbd/tensorflow/lite/python/lite.py#L1871C12-L1871C21

After this, the converter silently falls back to another conversion process that does not support saving multiple concrete functions.

The error that is silenced is this one:
```
TypeError: Failed to convert elements of (None, 1, 10, 10) to Tensor. Consider casting elements to a supported type. See https://www.tensorflow.org/api_docs/python/tf/dtypes for supported TF dtypes.
    
    
    Call arguments received by layer "phi_model" "                 f"(type PhiModel):
      • inputs_embeds=tf.Tensor(shape=(None, 10, 2048), dtype=float32)
      • past_key_values=tf.Tensor(shape=(None, 2, 1, 32, 0, 64), dtype=float32)
```

I am also interested in knowing why this silent error is thrown in the first place, I don't know why a dimension is added with `None` in the first place.

## Expected behavior
The conversion process should either fall back to a method that supports saving multiple concrete function, or better warn the user why it is not possible.

## System information
tensorflow version: 2.10.1

**Comment by sawantkumar** [comment]
Hi @BenCrulis ,

If possible , can you please provide me the complete code to replicate the issue, along with the model or the model creation code.

**Comment by BenCrulis** [comment]
Hi @sawantkumar ,

The code and model are quite big so it would not fit in a code block, but I will try to write a minimal reproducible example that replicates the issue, if I manage to identify it.

It seems it has something to do with some code being allowed as a saved model object but not as a TFLite model, or something like that.
