### ISSUE TITLE
When should I include tensorflow-lite-gpu-delegate-plugin dependency in my android project?

### ISSUE THREAD

**Issue by H4dr1en** [tensorflow/tensorflow#70061]
Hi,

Pretty much the title - I want to run a tflite model in an android app, without using Google Play, as described here:

https://www.tensorflow.org/lite/android/delegates/gpu#standalone

The documentation states:

> To enable access to the GPU delegate, add org.tensorflow:tensorflow-lite-gpu-delegate-plugin to your app's build.gradle file

I am currently using the libraries `tensorflow-lite`, `tensorflow-lite-gpu`, `tensorflow-lite-gpu-api` (because of this [issue](https://github.com/tensorflow/tensorflow/issues/57934)), `tensorflow-lite-support` and `tensorflow-lite-metadata`

Now the model runs on my device fine, and I don't see a difference if I add the `tensorflow-lite-gpu-delegate-plugin` library as shown in the docs. 

So my question is: what is the use case that requires adding this library as a dependency?

Thanks 👍

**Comment by sushreebarsa** [comment]
@H4dr1en The main use case for adding the tensorflow-lite-gpu-delegate-plugin library to your Android project is to leverage GPU acceleration for TensorFlow Lite models on devices without Google Play services.
Thank you!

**Comment by H4dr1en** [comment]
Hi @sushreebarsa , thanks for your answer!

Indeed, without it tflite falls back to XNNPack Delegate and it is slower

Btw, in version 2.9 this library doesn't seem to be necessary - looks like it was part of the tflite-gpu library back then and got split appart in more recent versions
