### ISSUE TITLE
Urgent: Report of Spam and Scam Activity on Your Website

### ISSUE THREAD

**Issue by maxwellbrien1990** [tensorflow/tensorflow#70085]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

TensorFlow Lite

### Custom code

Yes

### Current behavior?

To whomsoever it may concern,

A bunch of scammers are spamming your website with gambling and unsafe health supplements. People are losing money for this scam.

Here's the link:
https://groups.google.com/a/tensorflow.org/g/tflite

Thousands of spammy posts have been created under this directory.

Please take immediate action.

Thanks,
Maxwell

### Standalone code to reproduce the issue

```shell
To whomsoever it may concern,

A bunch of scammers are spamming your website with gambling and unsafe health supplements. People are losing money for this scam.

Here's the link:
https://groups.google.com/a/tensorflow.org/g/tflite

Thousands of spammy posts have been created under this directory.

Please take immediate action.

Thanks,
Maxwell
```

**Comment by tilakrayal** [comment]
@maxwellbrien1990,
Thank you for reporting the issue. Could you please allow some time to check with the developer team on the same and will provide the resolution for the same. Thank you!

**Comment by pradeepkuppla** [comment]
Thank We are in the process of cleaning up and routing all the discussions to TF Forum and sunset mailing lists.
