### ISSUE TITLE
Provide a string_concat op

### ISSUE THREAD

**Issue by dave-andersen** [tensorflow/tensorflow#701]
Per http://stackoverflow.com/questions/34247374/merge-string-tensors-in-tensorflow

Provide an op that will concatenate two strings into a single string.

**Comment by martinwicke** [comment]
Also, an op that splits strings.

**Comment by mrry** [comment]
I've just submitted string concatenation upstream. Should be available in the next push.

**Comment by mrry** [comment]
Fixed by https://github.com/tensorflow/tensorflow/commit/7116cc8b39c432f64e6e82b5708d2773f3fec159
