### ISSUE TITLE
Is there any method to read HDFS file in a distributed way?

### ISSUE THREAD

**Issue by xzry6** [tensorflow/tensorflow#7011]
I'm working on reading hdfs file in between graph mode. 
I used `tf.train.string_input_produce()` to read from hdfs and produce the input.

However, I found that all the workers are reading the whole hdfs file every time fetching a batch.

I'm wondering if it is a known issue or is there any way in TensorFlow that each worker could just read a part of the file like hadoop MapReduce?

**Comment by drpngx** [comment]
I don't think we support splittable files.

**Comment by jhseu** [comment]
We don't currently support splittable files, but I'm planning to support that in a future release.

For now, you should split data at training data generation time.

**Comment by nmoezzi** [comment]
Is the feature added in the current distributed Tensorflow?

**Comment by LukeBolly** [comment]
Any progress on this? Merging the files in HDFS is a very expensive operation (and has some annoying side effects like adding /user/nobody/ to the path)

**Comment by codeflitting** [comment]
Any progress on this?

**Comment by ryanmickler** [comment]
This is still a important feature for us, is there any progress?

**Comment by jhseu** [comment]
We're discussing switching the file format to Riegeli: https://github.com/google/riegeli , but no concrete plans yet and no ETA.
