### ISSUE TITLE
`tf.data.Dataset.load()` cannot load from a folder with bracket in the name

### ISSUE THREAD

**Issue by yanncalec** [tensorflow/tensorflow#70116]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf 2.16

### Custom code

Yes

### Python version

3.11

### Current behavior?

When save and reload a dataset, the reloaded dataset seems empty if the folder contains a bracket '[ ]'.
The dataset is however effectively saved.

### Standalone code to reproduce the issue

```shell
import os
path = os.path.expanduser("~/tmp/folder")
# path = os.path.expanduser("~/tmp/folder[1]")  # this won't work
os.makedirs(path, exist_ok=True)

# Save a dataset
dataset = tf.data.Dataset.range(2)
tf.data.Dataset.save(dataset, path)
# Check that dataset is effectively saved
assert os.path.exists(os.path.join(path, "snapshot.metadata"))

new_dataset = tf.data.Dataset.load(path)
for elem in new_dataset:
    print(elem)
```

**Comment by tilakrayal** [comment]
@yanncalec,
I tried to execute the mentioned code on Tensorflow v2.16.1 and it was executed without any issue. Kindly find the [gist](https://colab.research.google.com/gist/tilakrayal/01623d46cb0c5e741662781f326e93f7/untitled1977.ipynb) and screenshot for the reference. Could you please let me know in which environment you are trying to execute the code. 

![image](https://github.com/tensorflow/tensorflow/assets/81610181/c003ed46-f8bf-4a18-868d-42ab615029ef)

Thank you!

**Comment by yanncalec** [comment]
Thanks for your reply. I run your notebook and can still confirm the behavior: when the folder's name contains a bracket nothing is printed, meaning that the variable `new_dataset` is empty:
![image](https://github.com/tensorflow/tensorflow/assets/3247670/8ece4418-0d6f-4b58-815d-7e2303bf20a8)

Compare this to the folder name without bracket:
![image](https://github.com/tensorflow/tensorflow/assets/3247670/045211af-3c5a-4278-b642-2840d73eeea5)

**Comment by yanncalec** [comment]
I executed your gist online. Otherwise I work under Linux with tf 2.16.1.

**Comment by tilakrayal** [comment]
@yanncalec,
I guess the problem is when we are using [] to save and load the file. Whenever I tried to use [] and the other like () or {} or ({}), the file was able to save, load and also the output is also able to display. AFAIK the problem is with [].
Kindly find the [gist](https://colab.research.google.com/gist/tilakrayal/3e8520335984a579fc390a51db6b9b02/untitled1988.ipynb) for the reference.

![image](https://github.com/tensorflow/tensorflow/assets/81610181/2f21c324-bab4-448c-8f1e-a9453d7debb0)

Thank you!
