### ISSUE TITLE
ptb_rnn_lm.py error: InvalidArgumentError: logits and labels must have the same first dimension, got logits shape [400,10000] and labels shape [420]

### ISSUE THREAD

**Issue by johnlarkin1** [tensorflow/tensorflow#7015]
I am having the same issue that can be found here:
https://github.com/tensorflow/tensorflow/issues/6469

That issue was closed however. It seems like a bunch of people are still having the problem with the LSTM Penn Tree Bank dataset tutorial online [here](https://www.tensorflow.org/tutorials/recurrent/)

Has anyone found a fix? The exact error I am getting is: 
```
InvalidArgumentError (see above for traceback): logits and labels must have the same first dimension, got logits shape [400,10000] and labels shape [420]
	 [[Node: Train/Model/sequence_loss_by_example/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits = SparseSoftmaxCrossEntropyWithLogits[T=DT_FLOAT, Tlabels=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"](Train/Model/add, Train/Model/sequence_loss_by_example/Reshape)]]
```

I have made all of the changes to incorporate the model being a newer version. I have TensorFlow 12.1. Can anyone help?! Thank you all so much.

**Comment by Tiger97** [comment]
I have the same problem. How did you solve it？
