### ISSUE TITLE
TF 2.17.0-rc0 compilation fails due to flag: `-mavx512fp16’; did you mean ‘-mavx512bf16’?

### ISSUE THREAD

**Issue by feranick** [tensorflow/tensorflow#70199]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.17.0-rc0

### Custom code

No

### OS platform and distribution

Linux Ubuntu 22.04

### Python version

3.10

### Bazel version

6.5

### GCC/compiler version

gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

### CUDA/cuDNN version

12.3

### GPU model and memory

Quadro RTX 6000 

### Current behavior?

Compiling using 
```bazel build --config=opt --config=cuda --verbose_failures //tensorflow/tools/pip_package:wheel```

leads to error:
```
ERROR: /home/nicola/.cache/bazel/_bazel_nicola/c53ed0be17816f9e0970b1ba234e403c/external/XNNPACK/BUILD.bazel:2737:19: Compiling src/amalgam/gen/avx512fp16.c failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command (from target @XNNPACK//:avx512fp16_prod_microkernels) 
  (cd /home/nicola/.cache/bazel/_bazel_nicola/c53ed0be17816f9e0970b1ba234e403c/execroot/org_tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda-12.3 \
    GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-11 \
    LD_LIBRARY_PATH=/usr/local/cuda-12.3/include:/usr/local/cuda-12.3/targets/x86_64-linux/lib: \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/lib/python3/dist-packages \
    TF2_BEHAVIOR=1 \
    TF_CUDA_COMPUTE_CAPABILITIES=7.5,7.5 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/external/XNNPACK/_objs/avx512fp16_prod_microkernels/avx512fp16.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/XNNPACK/_objs/avx512fp16_prod_microkernels/avx512fp16.pic.o' '-DBAZEL_CURRENT_REPOSITORY="XNNPACK"' -iquote external/XNNPACK -iquote bazel-out/k8-opt/bin/external/XNNPACK -isystem external/XNNPACK/include -isystem bazel-out/k8-opt/bin/external/XNNPACK/include -isystem external/XNNPACK/src -isystem bazel-out/k8-opt/bin/external/XNNPACK/src -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fPIC -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -fno-omit-frame-pointer -no-canonical-prefixes -fno-canonical-system-headers -DNDEBUG -g0 -O2 -ffunction-sections -fdata-sections -Wno-all -Wno-extra -Wno-deprecated -Wno-deprecated-declarations -Wno-ignored-attributes -Wno-array-bounds -Wunused-result '-Werror=unused-result' -Wswitch '-Werror=switch' '-Wno-error=unused-but-set-variable' -DAUTOLOAD_DYNAMIC_KERNELS -Wno-sign-compare -O3 -Iinclude -Isrc -mf16c -mfma -mavx512f -mavx512cd -mavx512bw -mavx512dq -mavx512vl -mavx512vnni -mgfni -mavx512fp16 '-std=c99' -O2 -c external/XNNPACK/src/amalgam/gen/avx512fp16.c -o bazel-out/k8-opt/bin/external/XNNPACK/_objs/avx512fp16_prod_microkernels/avx512fp16.pic.o)
# Configuration: 84cfd7a662f4a0054b4853404795aea0f6d3c8a72332a77e90bd86210f86a5cf
# Execution platform: @local_execution_config_platform//:platform
x86_64-linux-gnu-gcc-11: error: unrecognized command-line option ‘-mavx512fp16’; did you mean ‘-mavx512bf16’?
Target //tensorflow/tools/pip_package:wheel failed to build
```

### Standalone code to reproduce the issue

```shell
See above.
```

### Relevant log output

```shell
See above
```

**Comment by tilakrayal** [comment]
@learning-to-play

**Comment by learning-to-play** [comment]
@belitskiy @rtg0795 FYI

**Comment by belitskiy** [comment]
Building Tensorflow with GCC is not supported as of 2.13. Please use Clang instead:
See https://www.tensorflow.org/install/source

**Comment by feranick** [comment]
I have managed to use GCC up to 2.16.1. anyway, the reason is the version of clang required is newer than what Ubuntu 22.04 provides. With no support for GCC and clang too old, there is no way to compile TF 2.17.0 with Ubuntu 22.04....On Jun 25, 2024 3:18 PM, belitskiy ***@***.***> wrote:
Building Tensorflow with GCC is not supported as of 2.13. Please use Clang instead:
See https://www.tensorflow.org/install/source

**Comment by belitskiy** [comment]
The guide linked [above](https://www.tensorflow.org/install/source) contains instructions on how to install Clang 17. This works for 
Alternatively, use a Docker container from  https://hub.docker.com/r/tensorflow/build/tags. It comes with Clang pre-installed.

**Comment by spinda** [comment]
FWIW, this also pops up when building the MediaPipe Python wheel via `python3 setup.py bdist_wheel`. I have Clang 18 installed, but XNNPACK is choosing to use GCC anyway. It's unclear to me how to plumb this configuration through the multiple layers of build systems involved.
