### ISSUE TITLE
Unable to build TFLite GPU Delegate for Android on MacOS

### ISSUE THREAD

**Issue by cpappasILMX** [tensorflow/tensorflow#70210]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.16

### Custom code

No

### OS platform and distribution

macOS Sonoma 14.5

### Mobile device

Android

### Python version

3.12

### Bazel version

7.2.0

### GCC/compiler version

Apple clang 15.0.0

### Current behavior?

I am attempting to build the android gpu delegate but I am running into difficulties producing a shared library. I have followed the build guide found at: https://www.tensorflow.org/lite/android/delegates/gpu_native. I am trying to build on macOS Sonoma 14.5 as it is our development platform, and it appears to be causing issues during linking. The linker attempts to link the CoreFoundation framework which doesn't make much sense for an Android build. Building on a linux platform, we don't run into this issue.

When configuring, we aren't building with ROCm or CUDA support, we're using the default optimization flags, we're configuring the workspace for Android, and we're not supporting iOS.

### Standalone code to reproduce the issue

```shell
export ANDROID_SDK_HOME="/Users/$USER/Library/Android/sdk"
export ANDROID_NDK_HOME="/Users/$USER/Library/Android/sdk/ndk/25.2.9519653"
export ANDROID_API_LEVEL="34"
export ANDROID_NDK_API_LEVEL="26"
export ANDROID_BUILD_TOOLS_VERSION="30.0.3"

./tensorflow/configure < AndroidConfiguration

bazel build -c opt --cxxopt=--std=c++20 --config=android_arm64 \
   --fat_apk_cpu=arm64-v8a \
   --define=android_dexmerger_tool=d8_dexmerger \
   --define=android_incremental_dexing_tool=d8_dexbuilder \
   --define=xnn_enable_arm_i8mm=false \
   --define=xnn_enable_arm_bf16=false \
   --verbose_failures \
   //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so
```

### Relevant log output

```shell
ld.lld: error: unknown argument '-framework'
ld.lld: error: cannot open CoreFoundation: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so failed to build
```

**Comment by sushreebarsa** [comment]
@cpappasILMX This typically happens if the build system mistakenly uses macOS-specific settings. To resolve this issue, kindly follow these steps:
```
export ANDROID_NDK_HOME=/path/to/your/android-ndk
export ANDROID_SDK_HOME=/path/to/your/android-sdk
export PATH=$ANDROID_NDK_HOME:$ANDROID_SDK_HOME/tools:$PATH
build --config=android
build --crosstool_top=//external:android/crosstool
build --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
build --fat_apk_cpu=arm64-v8a
bazel clean
./configure
bazel build -c opt --config=android_arm64 //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so



```

Please ensure no macOS frameworks are linked in Android targets.
Thank you!

**Comment by cpappasILMX** [comment]
Thank you for getting back to me so quickly. Unfortunately this did not resolve the issue. We are still achieving the same results.

**Comment by pkgoogle** [comment]
Hi @cpappasILMX, would you happen to have a link handy to the documentation that can be improved?

I was able to replicate exactly as you mentioned and got the exact same result on the nightly branch.

@yishuangP, can you please take a look?

**Comment by cpappasILMX** [comment]
@pkgoogle 

Thank you for responding to this thread! The link that I posted above is the one in question: https://www.tensorflow.org/lite/android/delegates/gpu_native

I feel it would be beneficial to users of TFLite that wish to build and employ the gpu delegate natively to have more thorough build instructions at the top of the page, or on their own dedicated build page entirely. I feel it may be helpful to discuss valid versions for ANDROID_API_LEVEL, ANDROID_NDK_API_LEVEL, and ANDROID_BUILD_TOOLS_VERSION. It would also be helpful to distinguish the different between NDK version and NDK API level and why these two values can be different since that has been a source of confusion among other developers I have spoke to.

**Comment by pkgoogle** [comment]
Hi @cpappasILMX, appreciate your feedback, I think a compatibility table like: https://www.tensorflow.org/install/source#tested_build_configurations would probably help... do you agree? That's probably a bigger conversation I need to have. For the build instructions.. it is lower on the page, the 2nd cell after this link: https://www.tensorflow.org/lite/android/delegates/gpu_native#enable_gpu_acceleration. Do you feel it should be it's on section and higher up? Prior to the actual code example? Let me know your thoughts, thanks.

**Comment by cpappasILMX** [comment]
Hi @pkgoogle
The table is helpful, but is missing a NDK/SDK level compatibility column. An extra column denoting the required levels could relieve some headache for developers. 

I do believe the build instructions should be higher up on the page. The build instructions are shoehorned between a code example and further instructions for the code example. If anything, the instructions to build should come before any code examples since building is the first step in the process for implementation.

This may seem a but pedantic, but the code example for the GPU delegate C/C++ API doesn't appear to be making use of the C-API for TFLite for instantiating an interpreter. I would expect someone who is using the C-API for the delegate to also be using the C-API for TFLite as well. The C-API I'm referring to being defined in "tensorflow/lite/core/c/c_api.h".

**Comment by H4dr1en** [comment]
@cpappasILMX were you able to fix the initial issue you reported?

**Comment by H4dr1en** [comment]
@sushreebarsa the instructions that you provided did not work unfortunately

**Comment by gaikwadrahul8** [comment]
Hi, @cpappasILMX
Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/57

Let us know if you have any questions. Thanks.
