### ISSUE TITLE
LINK error with dbg flag

### ISSUE THREAD

**Issue by cz2h** [tensorflow/tensorflow#70255]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

Latest

### Custom code

No

### OS platform and distribution

Windows 11

### Python version

3.11.7

### Bazel version

6.5.0

### GCC/compiler version

clang 18.1.7

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### Current behavior?

Tried to build from source and failed if I include 'config=dbg'  in bazel build command, if I exclude it it works fine.

In system variable, I manually set 'LIB=C:\Program Files\Python311\libs' where I can see the 'python311_d.lib' file. But the build log tells me that the LIB variable it uses does not include this.

### Standalone code to reproduce the issue

```shell
bazel build --config=dbg //tensorflow/tools/pip_package:wheel
```

### Relevant log output

```shell
SET LIB=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\ATLMFC\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64
...
 @bazel-out/x64_windows-dbg/bin/external/com_google_protobuf/python/google/protobuf/internal/_api_implementation.so-2.params
# Configuration: 0f1f93a82bfd9592acc639e5df0ca7fd9bb81c2eb1e7666777934fabb9730c7e
# Execution platform: @local_execution_config_platform//:platform
LINK : fatal error LNK1104: cannot open file 'python311_d.lib'
Target //tensorflow/tools/pip_package:wheel failed to build
INFO: Elapsed time: 137.190s, Critical Path: 1.08s
INFO: 372 processes: 354 internal, 18 local.
FAILED: Build did NOT complete successfully
```

**Comment by sushreebarsa** [comment]
@cz2h Could you please ensure that the path to python311_d.lib is correctly set in the environment variables and that Bazel recognizes it during the build process?
Thank you!

**Comment by mraunak** [comment]
Hi @cz2h, to use clang compiler please use the command below
bazel build --config=win_clang --repo_env=TF_PYTHON_VERSION=3.11 //tensorflow/tools/pip_package:wheel --repo_env=WHEEL_NAME=tensorflow_cpu

If you still see an error, try steps mentioned in https://www.tensorflow.org/install/source_windows

Please free to reach out if the issue still persists.
