### ISSUE TITLE
It seems that tf.scatter_nd only can run on CPU?

### ISSUE THREAD

**Issue by amortazi** [tensorflow/tensorflow#7026]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by amortazi** [comment]
Is there any way that I can run tf.scatter_nd on GPU? or is there an equivalent command?

**Comment by drpngx** [comment]
Some operations should work. Which operations are you looking for?
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/scatter_nd_op.cc#L348

**Comment by amortazi** [comment]
I am looking for tf.scatter_nd. when I am looking at log_device_placemnt it is saying that it is running in CPU. I am using tf.device to run it on GPU. The GPU version of this:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/scatter_nd_op.cc#L339

**Comment by drpngx** [comment]
Could you try registering the kernel for GPUs and see what happens? I'm not super familiar with that code and I'm not sure that it would work.

**Comment by drpngx** [comment]
@rmlarsen might have some input.

**Comment by amortazi** [comment]
I am not sure how i should register it!

**Comment by amortazi** [comment]
Even I couldn't find scatter_nd_op.cc file in my tensorflow directory. Can you give me some hint where is should be located?

**Comment by drpngx** [comment]
It should just be in core/kernels/scatter_nd_op.cc. You should run the same `TF_CALL` macro for all types as in the CPU version, but instead register the GPU ones, if that makes sense. If you have repro instructions on how to test I could give it a shot on my end.

**Comment by amortazi** [comment]
@drpngx Unfortunately, my sensorflow directory is different from github files. I installed it by using pip. it is version 0.12 for python 2.7 in ubuntu 14 64bit. Can you guide me why it is different and I couldn't locate scatter_nd_op.cc file. :( Thanks.

**Comment by drpngx** [comment]
For that, you have to install from source. You can't do it from a pip file unfortunately. You should follow this:
https://www.tensorflow.org/get_started/os_setup#installing_from_sources

**Comment by amortazi** [comment]
@drpngx I have installed tf from source. Did I need to installed it from source again if I make changes to scatter_nd_op.cc file? 
Also,  should I add sth like this to that file:
#define REGISTER_SCATTER_ND_CPU(type) REGISTER_SCATTER_ND(type, GPU);
TF_CALL_NUMBER_TYPES(REGISTER_SCATTER_ND_ADD_SUB_GPU);
// TODO(simister): Re-enable all types after binary size is under control.
TF_CALL_NUMBER_TYPES(REGISTER_SCATTER_ND_UPDATE_GPU);
TF_CALL_NUMBER_TYPES(REGISTER_SCATTER_ND_GPU);

Thanks,
Ali

**Comment by drpngx** [comment]
Yes, please try that. Thanks!

**Comment by amortazi** [comment]
@drpngx I apply those changes to cc files in clone of tensorflow in my machine and then I try to apply changes in cc files by this codes:
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
sudo pip install /tmp/tensorflow_pkg/tensorflow-0.12.1-py2-none-any.whl

but, it seems that those changes are not applied. May I ask am i doing it correctly? 
Thanks

**Comment by drpngx** [comment]
Yes, that's the right thing. I guess we have to figure out why the kernels are not registered.

**Comment by drpngx** [comment]
Following up on #7027, which is similar, until build issues are resolved.

**Comment by ivankreso** [comment]
Can someone point out to the GPU implementation for tf.scatter_nd?

I found only CPU version, I believe this one:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/scatter_nd_op_cpu_impl.h#L106

called from here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/scatter_nd_op.cc#L169

**Comment by drpngx** [comment]
Yes, we think it should be there. Could you try to follow the instruction on #7027 to print `LogAllRegisteredKernels`?

**Comment by drasmuss** [comment]
`LogAllRegisteredKernels` shows only CPU versions of the `ScatterNd` op being registered.  Based on the comment here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/scatter_nd_op.cc#L354, I don't think the ScatterND GPU kernel is supposed to be registered, so that is expected. (Uncommenting those lines just results in errors since those kernels don't exist).  But do you know if that is something that is being actively worked on and we can expect `scatter_nd` GPU support in the somewhat near future, or should we just plan on not using that op if we want to run on the GPU?

**Comment by rizar** [comment]
@drpngx , just make to sure I understood your response from #7026 which says:

```
Yeah, we were trying to add it to see what happens but somehow the thread died out. 
Please try it out if you have cycles.
```

Do you suggest that I add the line `TF_CALL_GPU_NUMBER_TYPES_NO_HALF(REGISTER_SCATTER_ND_CPU);` to `scatter_nd_op.cc`, recompile tensorflow and see what happens? I definitely can do it, although this would involve learning to compile Tensorflow from source first. Is it what you are asking?

**Comment by drasmuss** [comment]
Note: it looks like 8f1cde386cb8295d2d0ddb2a4af0ba6336bea897 added GPU support for `tf.scatter_update/add/sub` (sparse variable updates), but not `tf.scatter_nd`.

**Comment by drpngx** [comment]
@rizar, as @drasmuss says some operations have been implemented, but not `ScatterNd`. Browsing through the code I don't see an obvious reason why we couldn't add it.

**Comment by drpngx** [comment]
Actually I just tested with `force_gpu=True`, and it seems to be on the GPU. Can you confirm?

**Comment by drasmuss** [comment]
``` python
import tensorflow as tf

with tf.device("/gpu:0"):
    y = tf.scatter_nd([[1], [2], [3]], [1., 1., 1.], (5,))

with tf.Session() as sess:
    sess.run(y)
```
gives error
```
InvalidArgumentError (see above for traceback): Cannot assign a device to node 'ScatterNd': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: ScatterNd = ScatterNd[T=DT_FLOAT, Tindices=DT_INT32, _device="/device:GPU:0"](ScatterNd/indices, ScatterNd/updates, ScatterNd/shape)]]
```
This is on the latest `master` code.

**Comment by rizar** [comment]
@drpngx , I can not confirm. I tried and without any changes to the code `scatter_nd` is definitely done on cpu.

I also tried adding the following diff:

```cpp
--- a/tensorflow/core/kernels/scatter_nd_op.cc
+++ b/tensorflow/core/kernels/scatter_nd_op.cc
@@ -374,8 +374,12 @@ TF_CALL_NUMBER_TYPES(REGISTER_SCATTER_ND_CPU);
 #define REGISTER_SCATTER_ND_UPDATE_GPU(type) \
   REGISTER_SCATTER_ND_UPDATE(type, GPU);
 
+#define REGISTER_SCATTER_ND_GPU(type) \
+  REGISTER_SCATTER_ND(type, GPU);
+
 TF_CALL_GPU_NUMBER_TYPES_NO_HALF(REGISTER_SCATTER_ND_ADD_SUB_GPU);
 TF_CALL_GPU_NUMBER_TYPES_NO_HALF(REGISTER_SCATTER_ND_UPDATE_GPU);
+TF_CALL_GPU_NUMBER_TYPES_NO_HALF(REGISTER_SCATTER_ND_GPU);
 
 // Forward declarations of the functor specializations for GPU.
 namespace functor {
```

As a result, `scatter_nd` is placed on the GPU but eventually my test code crushes. My test code is listed below:

```python
config = config_pb2.ConfigProto(log_device_placement=True)

with tf.Graph().as_default() as graph, tf.Session(config=config) as sess:

    indices = tf.placeholder(tf.int32, shape=(2, 2))

    z = tf.scatter_nd(indices, tf.ones(2), shape=(10, 100))
    s = tf.reduce_sum(z)

    for i in range(10):
        print(sess.run(s, feed_dict={indices: [(0, 0), (1, 1)]}))
```

**Comment by aliosmanulusoy** [comment]
@drpngx Using the latest ```master```, ```scatter_nd``` is placed to the CPU if ```allow_soft_placement = True```. If I force it to execute on the GPU, tf complains there is no GPU implementation.

**Comment by drpngx** [comment]
Right, somehow `force_gpu` didn't do what I thought it would. See @rizar and @drasmuss comments above. Further investigation is needed to figure out the cause of the crash.

**Comment by drpngx** [comment]
Finally got a chance to take a look. You need `.HostMemory("shape")` in the `REGISTER_OP` [call](https://github.com/tensorflow/tensorflow/issues/7026). That's because `MakeShape` runs on the CPU, and crashes. I'm not an expert on this, so there might be further consequences to this. It might be better if I push this internally first.

**Comment by rizar** [comment]
Thank you @drpngx ! I think that supporting efficient subtensor operations such as `tf.gather_nd` and `tf.scatter_nd` is very important, especially for working with language data. I am looking forward to more updates from your side, and please let me know if would like me to try something on my setup.

**Comment by drpngx** [comment]
It's pushed internally, will be pushed to GitHub tomorrow or Monday likely

**Comment by aliosmanulusoy** [comment]
@drpngx The update did not resolve the issue for me. Did anybody else try it out? @rizar @drasmuss ?

**Comment by drpngx** [comment]
I wrote a test that worked. Maybe it's placing the op on the CPU for different reasons.

```
  with tf.device("/gpu:0"):
    y = tf.scatter_nd([[1], [2], [3]], [1., 1., 1.], (5,))

  session_config = tf.ConfigProto(allow_soft_placement=False,
                                  log_device_placement=True)

  with tf.Session(config=session_config) as sess:
    print(sess.run(y))
```

**Comment by aliosmanulusoy** [comment]
@drpngx Thanks for the test code. Unfortunately it does not work on my system. I get the following error:

`InvalidArgumentError (see above for traceback): Cannot assign a device to node 'ScatterNd': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: ScatterNd = ScatterNd[T=DT_FLOAT, Tindices=DT_INT32, _device="/device:GPU:0"](ScatterNd/indices, ScatterNd/updates, ScatterNd/shape)]]
`

**Comment by drpngx** [comment]
Just to be clear, you sync'd past that CL, rebuilt and ran?

**Comment by rizar** [comment]
Seems to work for me with on a simple test, haven't tried it in the context of a real training script yet.

From the log of device placement:

```
ScatterNd/shape: (Const): /job:localhost/replica:0/task:0/gpu:0
2017-03-01 13:51:08.598013: I tensorflow/core/common_runtime/simple_placer.cc:841] ScatterNd/shape: (Const)/job:localhost/replica:0/task:0/gpu:0
```

**Comment by aliosmanulusoy** [comment]
@drpngx Ah, there was a problem with my installation! It works just fine for me as well. Sorry about the confusion. I've tested your code as well as my entire network, which uses multiple scatter_nd's. I got a speed-up of ~5x for the latter. Thanks a lot for the patch!

**Comment by drpngx** [comment]
Yay!
