### ISSUE TITLE
Building tensorflow 2.2.0 from source

### ISSUE THREAD

**Issue by NoranNabil** [tensorflow/tensorflow#70279]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.2.0

### Custom code

No

### OS platform and distribution

Ubuntu 18.04 on nvidia jetson nano

### Python version

3.7.11

### Bazel version

2.0.0

### CUDA/cuDNN version

10.2

### Current behavior?

Can't be installed 

### Standalone code to reproduce the issue

```shell
I need to build tensorflow from source on my nvidia jetson nano for python 3.7.11. i have installed bazel 2.0.0, when i tried to use it for building tensorflow but resulted with errors. i need a guide to build it on my nvidia.
```

**Comment by tilakrayal** [comment]
Could you please let us know specific use case that you are using tensor flow v2.2 which is pretty old and not actively supported. We always suggest using the latest tensorflow v2.15.

Thank you!

**Comment by NoranNabil** [comment]
It is suitable to my nvidia jetson nano environment of jetpack and CUDA
versions. Can you help me in this process?

**Comment by tilakrayal** [comment]
@NoranNabil,
Tensorflow 2.2 version is the old which the support was very minimal. Please try to upgrade to the latest tensorflow v2.17, where most of the bugs and features are resolved in the latest versions. Thank you!
