### ISSUE TITLE
tensorflow has no attribute 'parallel_stack'

### ISSUE THREAD

**Issue by amortazi** [tensorflow/tensorflow#7029]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by amortazi** [comment]
I was trying import tf.parallel_stack, but I got following error:
'module' object has no attribute 'parallel_stack'
I am using tensorflow version 0.12, python 2.7 in ubuntu 14.
Thanks

**Comment by yaroslavvb** [comment]
This op was removed in github.com/tensorflow/tensorflow/commit/705cc933, the replacement is called `tf.stack`
