### ISSUE TITLE
Feature Request: an op that returns bytes_in_use for its device

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#7030]
We are trying to optimize some models to fit into TitanX's 12GB of RAM, and it's hard because of lack of transparency in TF available memory.

What would help this situation is an op that returns amount of bytes on its device when executed. Something similar to what's done in [stack_ops](https://github.com/tensorflow/tensorflow/blob/64edd34ce69b4a8033af5d217cb8894105297d8a/tensorflow/core/kernels/stack_ops.cc#L222) for memory-aware heuristics

```
DeviceContext* device_ctxt = ctx->op_device_context();
auto device = static_cast<tensorflow::Device*>(ctx->device());
Allocator* allocator = device->GetAllocator(alloc_attrs);
AllocatorStats stats;
allocator->GetStats(&stats)
//  output stats.bytes_in_use

```

This op can be wedged between other ops using control dependencies and used for memory debugging. This is complementary to request in https://github.com/tensorflow/tensorflow/issues/6716 because it would account for memory from parallel run calls, variables, persistent tensors.

I can take this issue if this op fits into TF framework

**Comment by drpngx** [comment]
@prb12 @mrry @vrv 
That sounds like a pretty useful idea.

**Comment by vrv** [comment]
@yaroslavvb maybe try writing it as a custom op using load_op_library for now so you can try the idea out and see how useful it is for you first -- can always add it to the core later if it's widely useful.

**Comment by yaroslavvb** [comment]
load_library seems like a great idea. Can custom ops depend on `//tensorflow/core:core_cpu`? I need this for Allocator header `tensorflow/core/common_runtime/device.h` but adding the dependency fails

```
tensorflow/core:core_cpu cannot depend on tensorflow/core:framework.
ERROR: Analysis of target '//tensorflow/core/user_ops:bytes_in_use.so' failed; build aborted.
```

https://github.com/yaroslavvb/tensorflow/blob/custom_op/tensorflow/core/user_ops/BUILD

**Comment by drpngx** [comment]
`core_cpu` is an internal target, but `core` in that directory has includes everything and has `//visibility:public`.

**Comment by yaroslavvb** [comment]
Same error when depending on `core:core`, this seems like a circular dependency somewhere

```
tensorflow/core:core cannot depend on tensorflow/core:framework.
ERROR: Analysis of target '//tensorflow/core/user_ops:bytes_in_use.so' failed; build aborted.

```

**Comment by drpngx** [comment]
From the error message it looks like "core" depends on ":framework" somehow. That should fail everywhere. Do you need that build file in `core/user_ops`? It looks like it's globbed by `user_ops_libs` already.

**Comment by yaroslavvb** [comment]
Yes, the error message doesn't make sense. I followed instructions in https://www.tensorflow.org/how_tos/adding_an_op/ which says to put `BUILD` file in `core/user_ops`. It passes analysis if I don't add dependency to `//tensorflow/core:core_cpu` or `//tensorflow/core:core`, but then bazel complains about missing `device.h`

cc @keveman in case he knows how to properly have user ops depend on `device.h` (part of `//tensorflow/core:core_cpu` target)

**Comment by yaroslavvb** [comment]
OK, custom op turned out to be relatively straightforward, I put it here: https://github.com/yaroslavvb/memory_probe_ops

One snag is that when the op is placed on CPU, the allocator returns 0 for `bytes_in_use`, so this only works or GPUs. I still see LOGMEMORY messages coming from cpu allocations, so it seems this info gets lost somewhere.

Also, when graph optimization are turned on, it sometimes returns 0, and I suspect that ctx->device()->GetAllocator() gives me a CPU allocator. This is despite run_metadata and log_device_placement showing the op as existing on GPU. Things go back to normal when setting up session with `tf.OptimizerOptions.L0`

**Comment by drpngx** [comment]
Maybe you have to run it with `control_dependencies`?

**Comment by yaroslavvb** [comment]
I got around the optimization issue by adding `.SetIsStateful()` to my op. Regarding CPU allocations, looks like by default byte tracking it is turned off. There's a function `EnableCPUAllocatorStats(true);` which I can call from the kernel, but it doesn't do anything. I suspect the problem is that the underlying variable is defined as `static bool cpu_allocator_collect_stats = false;`, so it can't be modified it outside of `pywraptensorflow.so`

**Comment by drpngx** [comment]
Right. If you're linked against it, it should.

For some reason we chose to use a `Mutex`, but I think `std::atomic` would have worked fine.

**Comment by yaroslavvb** [comment]
So I think for this feature to be complete using `load_library` mechanism, what's missing is the ability to enable CPU allocator stats either from TF client, or from dynamically loaded op kernel. @misard any suggestions?

**Comment by yaroslavvb** [comment]
BTW, the issue with using Bazel to build such op is that the such internal dependencies are disallowed. IE there's this [line](https://github.com/tensorflow/tensorflow/blob/a0d784bdd31b27e013a7eac58a86ba62e86db299/tensorflow/tensorflow.bzl#L701) in tf_custom_op

`             disallowed_deps=["//tensorflow/core:framework",
`

Since `//tensorflow/core:core` depends on `//tensorflow/core:framework` and `//tensorflow/core:framework` is disallowed, I can't have a custom op depending on `//tensorflow/core:core`

**Comment by vrv** [comment]
@keveman, @josh11b  I feel like we should allow the following public headers from libraries as we do in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/BUILD#L22

@yaroslavvb have you tried not using bazel and trying to build your code using https://www.tensorflow.org/how_tos/adding_an_op/#building_the_op_library and then just loading the .so?  I suspect that will work because we package more headers there.

**Comment by yaroslavvb** [comment]
@vrv indeed, I was able to compile it successfully using g++ on Mac and Linux, and released final product here -- https://github.com/yaroslavvb/memory_probe_ops

The only remaining issue is that cpu allocator always reports 0 bytes allocated. There's this line in `allocator.cc`

`static bool cpu_allocator_collect_stats = false;
`

But it feels like it should be superceded by this line:

`  if (cpu_allocator_collect_full_stats || LogMemory::IsEnabled()) {
`
so I'm still tracking that one down

**Comment by yaroslavvb** [comment]
@josh11b suggested this op is not a good target for user-op because it would require opening up Allocator API. Made a tracking issue here https://github.com/tensorflow/tensorflow/issues/7581

**Comment by harshini-gadige** [comment]
@yaroslavvb Hi, any update on this ? I can close this if there is a solution provided for the op requested or any workaround is done.

**Comment by yaroslavvb** [comment]
I think it can be closed, there are now ops which return memory + memory is available in timeline, I have examples of extracting memory from timeline in https://github.com/yaroslavvb/memory_util

**Comment by harshini-gadige** [comment]
Sounds good. Thank you !
