### ISSUE TITLE
[TFLite] TfLiteInterpreterInvoke has memory leak and increasing duration time

### ISSUE THREAD

**Issue by kkk-jpeg** [tensorflow/tensorflow#70316]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.15.0

### Custom code

Yes

### OS platform and distribution

Android/iOS mobile platform

### Current behavior?

I found memory and duration time increasing when I  use tflite C API code in below.
The duration time increase 10 msec in just 10 minitues.

```
TfLiteStatus init(){
    // create model 
    mTFLModel = TfLiteModelCreate(dst_buf, dlc_size);

    mTFLInterpreter = TfLiteInterpreterCreate(mTFLModel, NULL);
    // Allocate tensor buffers.　
    mStatus = TfLiteInterpreterAllocateTensors(mTFLInterpreter);
    // output buffer
    mdnnOutputDataBuffer = new float[OutputSize.width * OutputSize.height];
    memset(mdnnOutputDataBuffer, 0, sizeof(float) * OutputSize.width * OutputSize.height );
    return mStatus;
}

void release(){
    if (mdnnOutputDataBuffer != NULL) delete[] mdnnOutputDataBuffer;
    if (mTFLInterpreter != NULL) {
        TfLiteInterpreterDelete(mTFLInterpreter);
        mTFLInterpreter = NULL;
    }
    if (mTFLModel != NULL) {
        TfLiteModelDelete(mTFLModel);
        mTFLModel = NULL;
    }
}

TfLiteStatus main(const float* input, uint8_t* intValues) {

        TfLiteTensor* input_tensor = TfLiteInterpreterGetInputTensor(mTFLInterpreter,0);
        //
        mStatus = TfLiteTensorCopyFromBuffer(input_tensor, input, TfLiteTensorByteSize(input_tensor));
        //
        mStatus = TfLiteInterpreterInvoke(mTFLInterpreter);

        const TfLiteTensor* output_tensor =
                TfLiteInterpreterGetOutputTensor(mTFLInterpreter, 0);
        
        TfLiteTensorCopyToBuffer(output_tensor, mdnnOutputDataBuffer,
                                 TfLiteTensorByteSize(output_tensor));

}
```

Now I know is ..
・Not depending on tf version(I tried both 2.9.0 and 2.16.1)
・Not depenging on iOS/android(both happen)
・Low resolution input/output model slightly better
・Not depending on device(I tried sevaral devices)

I checked similar mention, but those problem are about NNapi or GPU delegate option.
I don't use delegate option and doesen't work for me.

- https://github.com/tensorflow/tensorflow/issues/55503
- https://github.com/tensorflow/tflite-support/issues/269
- https://github.com/tensorflow/tensorflow/issues/66736

### Standalone code to reproduce the issue

```shell
…
```

**Comment by sushreebarsa** [comment]
@kkk-jpeg Could you please make sure that you're properly allocating and deallocating memory for tensors used with the interpreter. Please consider optimizing your TFLite model using tools like the TFLite Converter with optimizations like quantization and pruning. Kindly let us know if you are facing this issue in TF latest version?
Thank you!

**Comment by kkk-jpeg** [comment]
@sushreebarsa 
I commented out "TfLiteInterperterInvoke", and this problem doesn't happen.
I made sure input and output buffer treat currectly.

TfliteInterpreter.close won't work.
and after using "TfLiteInterpreterDelete(mTFLInterpreter)" doesn't change increased time.
If this function work right, the increased time will back to normal.

Please give me any suggestion.

>if you are facing this issue in TF latest version?
yes.

**Comment by kkk-jpeg** [comment]
https://github.com/android/camera-samples/blob/42f76c4aab7c7c2d41110c3c127c20c08882e079/CameraXTfLite/app/src/main/java/com/example/android/camerax/tflite/CameraActivity.kt#L89

This sample app also increase duration time. It started 10fps but 7fps after 5 mins.

**Comment by sushreebarsa** [comment]
@kkk-jpeg Could you please verify that the interpreter (mTFLInterpreter) is initialized correctly with your model and input parameters. Any incomplete or incorrect initialization can lead to undefined behavior, including memory leaks?
Thank you!

**Comment by kkk-jpeg** [comment]
@sushreebarsa 
Thank you for your kindly answer. I'm checking if my code using model in right way.
Now I found this error. Do you think this related to memory leak?
![image](https://github.com/tensorflow/tensorflow/assets/103484905/51c76bc5-f5e9-4cc4-b7ab-886f455b9461)

**Comment by kkk-jpeg** [comment]
@sushreebarsa 
I would like to make sure to convert .tflite file to .h file.

```
import numpy as np
import os

def convert_tflite_to_header(tflite_path, output_header_path):

with open(tflite_path, 'rb') as tflite_file:
    tflite_content = tflite_file.read()


hex_lines = [', '.join([f'0x{byte:02x}' for byte in tflite_content[i:i+12]]) for i in range(0, len(tflite_content), 12)]


hex_array = ',\n  '.join(hex_lines)


with open(output_header_path, 'w') as header_file:
    
    header_file.write('const unsigned char model[] = {\n  ')
    header_file.write(f'{hex_array}\n')
    header_file.write('};\n\n')
    
if __name__ == "__main__":
    tflite_path = 'model.tflite'
    output_header_path = 'model.h'

    convert_tflite_to_header(tflite_path, output_header_path)
    convert_tflite_to_header(tflite_path, output_header_path)
```

**Comment by kkk-jpeg** [comment]
I recognized my output tensor index is 337 in .tflite file, but I have to use index 0 when using C API.
This means something made wrong converting .tflite to hex array in C file?

**Comment by kkk-jpeg** [comment]
@sawantkumar please give me any suggestions?

**Comment by sawantkumar** [comment]
Hi @kkk-jpeg ,

Can you send your  tflite model file if possible ?

**Comment by kkk-jpeg** [comment]
@sawantkumar 
I can't put tflite model here. could you tell me your e-mail?

**Comment by sawantkumar** [comment]
Hi @kkk-jpeg ,

You can upload your model to your google drive and share a link here or you can mail me at sawantkumar@google.com.

**Comment by zhanghuicuc** [comment]
meet the same problem while using metal delegate with iOS

**Comment by kkk-jpeg** [comment]
@sawantkumar 
I've sent you e-mail. could you check please?

**Comment by sawantkumar** [comment]
Hi @kkk-jpeg ,

I forgot to ask but can you also provide me the complete code required to replicate this issue ?

**Comment by zhanghuicuc** [comment]
@sawantkumar I have a demo which can reproduce the leak problem using ios metal delegate, will that be useful to you? If so, I can share it with you.

**Comment by sawantkumar** [comment]
Hi @zhanghuicuc ,

Sure, you can share it .

**Comment by kkk-jpeg** [comment]
@zhanghuicuc @sawantkumar 
If you have any findings, could you share with me?

**Comment by gaikwadrahul8** [comment]
Hi, @pkgoogle 

Please take look into this issue. Thank you

**Comment by pkgoogle** [comment]
Hi @kkk-jpeg, delete[] is not valid in C, is this a C++ issue or a C issue?, I'm not seeing where your init() or release() is being called. Can you maybe give me more of your code or give me a standalone reproducible example?

**Comment by kkk-jpeg** [comment]
@pkgoogle 
sorry for late reply.
I'm using this C API of tflite in c++ extension.
Shoud I use malloc/free and not using new/delete?

**Comment by kkk-jpeg** [comment]
@pkgoogle 
sorry for late reply.
I'm using this C API of tflite in C++ extension. that makes memory leak problem?
(When I use malloc/free does't change this problem)
Xcode function "leaks" mentioned TfLiteInterpreterCreate memory leaks.

Thanks.

**Comment by pkgoogle** [comment]
Hi @kkk-jpeg, I am unable to reproduce with the given code thus far. Can you provide more context on how to reproduce this? If you have code in a github repo, that may be easiest. But please share as much as you can.
