### ISSUE TITLE
Have tf.sub  and tf.mul been removed from latest TF build ? 

### ISSUE THREAD

**Issue by deepankar1994** [tensorflow/tensorflow#7032]
I am running TF 0.12.head and ran into this issue where tf.sub was not found. I am writing this since the [docs](https://www.tensorflow.org/api_docs/python/math_ops/) don't seem to indicate any such thing.

**Comment by drpngx** [comment]
Yes, it's been renamed to `tf.subtract`, to align with numpy.

**Comment by raginisharma14** [comment]
Thanks!

**Comment by wei-yuan** [comment]
Thanks! just ran into same issue when tensorflow update to 1.0

**Comment by kickoffqi** [comment]
Thanks. just found it. updated my code.

**Comment by madongyu** [comment]
Thanks.

**Comment by jybaek** [comment]
I learned from Google search. Thank you.

**Comment by dxj1113** [comment]
Thanks!
