### ISSUE TITLE
Strange issue File already exists in database

### ISSUE THREAD

**Issue by tomneo2004** [tensorflow/tensorflow#70340]
### Issue type

Others

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.16

### Custom code

Yes

### OS platform and distribution

Pop os 22.04

### Python version

3.9

### Current behavior?

My project use tensorflow library and work fine when application run from python script. When I make bundle of application for distribution and run the application an error pop up. The main issue is this only happen in Linux system. I also try in Ubuntu but is the same error.

Error is following
```
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/descriptor_database.cc:642] File already exists in database: tensorflow/core/protobuf/replay_log.proto
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/descriptor.cc:1986] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size): 
Aborted (core dumped)
```

Library I use to bundle  the application is [cx_Freeze](https://cx-freeze.readthedocs.io/en/stable/). I think above error related to protobuf  in tensorflow.

### Standalone code to reproduce the issue

```shell
1. Clone my project  [here](https://github.com/NPMachineLearning/SmartTrainer.git)

2. Follow the steps here [here](https://github.com/NPMachineLearning/SmartTrainer#steps) to produce an executable application

3. Run app under directory qt_app/build/exe.linux-x86_64-3.9/
```

**Comment by tilakrayal** [comment]
@tomneo2004,
Could you please confirm the sequence of steps. Tf2.16v supports protobuf >=3.20.3 versions as per [source](https://github.com/tensorflow/tensorflow/blob/v2.16.1/tensorflow/tools/pip_package/setup.py#L101) where as it seems protobuf 3.19v has been installed.

Thank you!

**Comment by tomneo2004** [comment]
> @tomneo2004, Could you please confirm the sequence of steps. Tf2.16v supports protobuf >=3.20.3 versions as per [source](https://github.com/tensorflow/tensorflow/blob/v2.16.1/tensorflow/tools/pip_package/setup.py#L101) where as it seems protobuf 3.19v has been installed.
> 
> Thank you!

![Screenshot from 2024-06-27 03-05-03](https://github.com/tensorflow/tensorflow/assets/921838/4544b843-7fd3-4eb0-ab25-cd2c2e83627b)

v4.25.3 protobuf was installed along side with tensorflow 2.16

**Comment by samarmeena** [comment]
I'm encountering an issue where the executable works in the default dist folder created by PyInstaller but gives an error when moved to any other location. There haven't been any changes in dependencies; I'm using TensorFlow 2.15.1, and there are no updates for the libraries. Could this issue be related to an operating system upgrade? I'm experiencing this problem only on the latest version of macOS. What could be the solution? Thank you.

**Comment by tomneo2004** [comment]
I end up switching to ONNX Runtime instead of Tensorflow for my model inference to solve problem.
