### ISSUE TITLE
Build with --config==cuda just runs fine, with --config== fails over and over

### ISSUE THREAD

**Issue by StevenPuttemans** [tensorflow/tensorflow#7035]
### Environment info
Operating System: Ubuntu 14.04 64 bit

Installed version of CUDA and cuDNN: Cuda7.5, CuDNN 7.5
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
spu@TOBCAT:~$ ls -l /usr/local/cuda-7.5/lib/libcud*
-rw-r--r-- 1 root root 189170 Aug  8 16:03 /usr/local/cuda-7.5/lib/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Aug  8 16:03 /usr/local/cuda-7.5/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root     19 Aug  8 16:03 /usr/local/cuda-7.5/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root 311596 Aug  8 16:03 /usr/local/cuda-7.5/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root 558020 Aug  8 16:03 /usr/local/cuda-7.5/lib/libcudart_static.a
```

I tried following the `build from sources` directives from `https://www.tensorflow.org/get_started/os_setup#installing_from_sources` but as soon as I get to the command `bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package` i get the following issues

```
spu@TOBCAT:~/Frameworks/deeplearning/tensorflow$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
INFO: Found 1 target...
ERROR: /home/spu/.cache/bazel/_bazel_spu/d4f375c9af64c0d3baa31a5949dd9b54/external/protobuf/BUILD:113:1: C++ compilation of rule '@protobuf//:protobuf' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 43 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.875s, Critical Path: 1.50s
```

Went googling for possible related issues, but none of the suggestions seem to work out. Using Tensorflow without CUDA seems to kill the reason why I am willing to use Tensorflow in the first place ...

**Comment by drpngx** [comment]
It looks like the host compiler is improperly configured. `cc1plus` is the compiler that's called after preprocessing is done.

Can you try gcc? It would seem that gcc doesn't work. Try re-installing it perhaps.

**Comment by gunan** [comment]
Also, another possibility.
When running configure, did you enable GPU support?

**Comment by StevenPuttemans** [comment]
Sorry for the delay, but was not at work until now to try this out. It seems the following steps enabled me to get everything fixed and building

- Reinstalled `sudo apt-get install build-essentials gcc g++`
- Based on that, reinstalled CUDA7.5, to ensure CUDA was built using the correct compiler
- Then re-ran `./configure`

Now the command `bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package` seems to be doing building, just like the non-gpu version. I will close this, and reopen if something goes wrong.

Thank you for the help!

**Comment by StevenPuttemans** [comment]
I will re-open this issue, because I still have some problems. So compiling went fine, then run the command  `bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg` and then ran `sudo pip install /tmp/tensorflow_pkg/tensorflow-0.12.1-cp34-cp34m-linux_x86_64.whl` which should be the last step of the installation... 

However I get the following error

```
tensorflow-0.12.1-cp34-cp34m-linux_x86_64.whl is not a supported wheel on this platform.
Storing debug log for failure in /home/spu/.pip/pip.log
```

The log says

```
------------------------------------------------------------
/usr/bin/pip run on Fri Jan 27 10:11:46 2017
tensorflow-0.12.1-cp34-cp34m-linux_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 257, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 168, in from_line
    raise UnsupportedWheel("%s is not a supported wheel on this platform." % wheel.filename)
UnsupportedWheel: tensorflow-0.12.1-cp34-cp34m-linux_x86_64.whl is not a supported wheel on this platform.
```

**Comment by StevenPuttemans** [comment]
I guess it has to do I told the installation to use python3 but pip seems to use python 2.7, if anyone knows how to handle this, do let me know.

**Comment by StevenPuttemans** [comment]
Found it! Changed command to `sudo pip3 install /tmp/tensorflow_pkg/tensorflow-0.12.1-cp34-cp34m-linux_x86_64.whl`

I suggest to update the tutorial to mention this!
