### ISSUE TITLE
multiple dequeue ops are optimized away in latest TF

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#7038]
Multiple ops Dequeue ops from the same queue started getting optimized away in latest TensorFlow:

The following executes dequeue once in Jan17 head, but 3 times in 12.1 
`sess.run([q.dequeue(), q.dequeue(), q.dequeue()])
`

One gets expected behavior (3 dequeues) when graph optimization is turned off

```
tf.ConfigProto(graph_options=tf.GraphOptions(optimizer_options=tf.OptimizerOptions(opt_level=tf.OptimizerOptions.L0)))
sess = tf.Session(config = config)
``` 

Self-contained repro: https://github.com/yaroslavvb/stuff/blob/master/parallel_dequeue_test.py

Came up in http://stackoverflow.com/questions/41830206/how-to-share-a-queue-containing-variable-length-sequences-batches-between-multip

**Comment by yaroslavvb** [comment]
cc @mrry the queue expert

**Comment by mrry** [comment]
Can you print the GraphDef for that program? In particular, I'd like to know if the `FIFOQueueV2` (or some other `...QueueV2`) op is being used.

**Comment by yaroslavvb** [comment]
Yes, it's using V2 ops for queue. The 12.1 version is using regular


http://pastebin.com/gsu7xrU7

**Comment by mrry** [comment]
@alextp: It looks like the switch to resource-typed queues has caused a subtle bug in some of the queue ops. As far as I can tell, multiple instances of `queue.dequeue()` in the same subgraph are now being treated as common subexpressions, whereas before the fact that they had an incoming ref-typed edge meant they were [never candidates for CSE](https://github.com/tensorflow/tensorflow/blob/3570b5de07c8079d1005c7877e235bd8aa0e0ccc/tensorflow/core/graph/optimizer_cse.cc#L162).

I can see at least two solutions:

* Modify the CSE optimizer to reject anything with a resource-typed input as a candidate for elimination.
* Modify all of the `Queue*V2` accessor ops to be "stateful", which [also inhibits the optimization](https://github.com/tensorflow/tensorflow/blob/3570b5de07c8079d1005c7877e235bd8aa0e0ccc/tensorflow/core/graph/optimizer_cse.cc#L158).

**Comment by alextp** [comment]
https://github.com/tensorflow/tensorflow/commit/06e3aa655506773e49ce9a855f81ba3eae2a6b88#diff-333845d139890198962551b3a1c2a33b should have fixed this issue (it adds a test, even)

**Comment by yaroslavvb** [comment]
I just tried in tf1.0 and this behavior seems to still be here back. To reproduce, try this

```
import tensorflow as tf
input1 = tf.train.range_input_producer(10, shuffle=False)
input1_batch = [input1.dequeue(),input1.dequeue()]

config = tf.ConfigProto()
#config = tf.ConfigProto(graph_options=tf.GraphOptions(optimizer_options=tf.OptimizerOptions(opt_level=tf.OptimizerOptions.L0)))
input2 = tf.train.batch([input1_batch], batch_size=4, enqueue_many=True)

sess = tf.InteractiveSession(config=config)
tf.train.start_queue_runners()

for i in range(5):
    print(sess.run(input2))
```
Result is

```
[0 0 1 1]
[2 2 3 3]
[4 4 5 5]
[6 6 7 7]
[8 8 9 9]
```

If you uncomment "#config" line to remove rewriting optimization, then result is as expected

```
[0 1 3 2]
[5 4 6 7]
[8 9 1 0]
[2 3 4 5]
[7 6 9 8]
```

Version info:
```
>>> tf.__version__
'1.0.0'

>>> sys.version
'3.5.3 |Continuum Analytics, Inc.| (default, Feb 22 2017, 20:51:01) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]'

```

**Comment by alextp** [comment]
It seems like the commit which fixed this bug didn't make the cut into the 1.0 release. master is fixed, and so will 1.1.

**Comment by alextp** [comment]
If you need the fix by itself cherry-pick https://github.com/tensorflow/tensorflow/commit/06e3aa655506773e49ce9a855f81ba3eae2a6b88#diff-333845d139890198962551b3a1c2a33b

**Comment by yaroslavvb** [comment]
Got it, I forgot that releases are non-linear (it worked in version I built before TF 1.0 was released)
