### ISSUE TITLE
Model works in tensorflow 2.15 perfectly but unable to import the model in tensorflow 2.16!

### ISSUE THREAD

**Issue by pataneanant** [tensorflow/tensorflow#70394]
Hi there,

I am facing an unusual issue which is not being found on the internet as well. I have trained a Classification model on tensorflow 2.15. This model runs perfectly but when when I try to import that model I get the following error.

/usr/local/lib/python3.10/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.10/dist-packages/keras/src/optimizers/base_optimizer.py:33: UserWarning: Argument `decay` is no longer supported and will be ignored.
  warnings.warn(
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-2-b87769641d1f>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 # Step 1: Load the model
----> 4 model = tf.keras.models.load_model('/content/drive/MyDrive/Colab Notebooks/M5/NEW RESEARCH/Image Recognization/models/image_recog.h5')
      5 
      6 # model = tf.keras.models.load_model('/content/drive/MyDrive/Colab Notebooks/M5/NEW RESEARCH/Image Recognization/models/image_recog_2.16')

11 frames
[/usr/local/lib/python3.10/dist-packages/keras/src/saving/saving_api.py](https://localhost:8080/#) in load_model(filepath, custom_objects, compile, safe_mode)
    187         )
    188     if str(filepath).endswith((".h5", ".hdf5")):
--> 189         return legacy_h5_format.load_model_from_hdf5(
    190             filepath, custom_objects=custom_objects, compile=compile
    191         )

[/usr/local/lib/python3.10/dist-packages/keras/src/legacy/saving/legacy_h5_format.py](https://localhost:8080/#) in load_model_from_hdf5(filepath, custom_objects, compile)
    153             # Compile model.
    154             model.compile(
--> 155                 **saving_utils.compile_args_from_training_config(
    156                     training_config, custom_objects
    157                 )

[/usr/local/lib/python3.10/dist-packages/keras/src/legacy/saving/saving_utils.py](https://localhost:8080/#) in compile_args_from_training_config(training_config, custom_objects)
    141         loss_config = training_config.get("loss", None)
    142         if loss_config is not None:
--> 143             loss = _deserialize_nested_config(losses.deserialize, loss_config)
    144             # Ensure backwards compatibility for losses in legacy H5 files
    145             loss = _resolve_compile_arguments_compat(loss, loss_config, losses)

[/usr/local/lib/python3.10/dist-packages/keras/src/legacy/saving/saving_utils.py](https://localhost:8080/#) in _deserialize_nested_config(deserialize_fn, config)
    200         return None
    201     if _is_single_object(config):
--> 202         return deserialize_fn(config)
    203     elif isinstance(config, dict):
    204         return {

[/usr/local/lib/python3.10/dist-packages/keras/src/losses/__init__.py](https://localhost:8080/#) in deserialize(name, custom_objects)
    147         A Keras `Loss` instance or a loss function.
    148     """
--> 149     return serialization_lib.deserialize_keras_object(
    150         name,
    151         module_objects=ALL_OBJECTS_DICT,

[/usr/local/lib/python3.10/dist-packages/keras/src/saving/serialization_lib.py](https://localhost:8080/#) in deserialize_keras_object(config, custom_objects, safe_mode, **kwargs)
    579                     custom_objects=custom_objects,
    580                 )
--> 581             return deserialize_keras_object(
    582                 serialize_with_public_class(
    583                     module_objects[config], inner_config=inner_config

[/usr/local/lib/python3.10/dist-packages/keras/src/saving/serialization_lib.py](https://localhost:8080/#) in deserialize_keras_object(config, custom_objects, safe_mode, **kwargs)
    716     with custom_obj_scope, safe_mode_scope:
    717         try:
--> 718             instance = cls.from_config(inner_config)
    719         except TypeError as e:
    720             raise TypeError(

[/usr/local/lib/python3.10/dist-packages/keras/src/losses/losses.py](https://localhost:8080/#) in from_config(cls, config)
     37         if "fn" in config:
     38             config = serialization_lib.deserialize_keras_object(config)
---> 39         return cls(**config)
     40 
     41 

[/usr/local/lib/python3.10/dist-packages/keras/src/losses/losses.py](https://localhost:8080/#) in __init__(self, from_logits, label_smoothing, axis, reduction, name, dtype)
    578         dtype=None,
    579     ):
--> 580         super().__init__(
    581             binary_crossentropy,
    582             name=name,

[/usr/local/lib/python3.10/dist-packages/keras/src/losses/losses.py](https://localhost:8080/#) in __init__(self, fn, reduction, name, dtype, **kwargs)
     19         **kwargs,
     20     ):
---> 21         super().__init__(name=name, reduction=reduction, dtype=dtype)
     22         self.fn = fn
     23         self._fn_kwargs = kwargs

[/usr/local/lib/python3.10/dist-packages/keras/src/losses/loss.py](https://localhost:8080/#) in __init__(self, name, reduction, dtype)
     27     def __init__(self, name=None, reduction="sum_over_batch_size", dtype=None):
     28         self.name = name or auto_name(self.__class__.__name__)
---> 29         self.reduction = standardize_reduction(reduction)
     30         self.dtype = dtype or backend.floatx()
     31 

[/usr/local/lib/python3.10/dist-packages/keras/src/losses/loss.py](https://localhost:8080/#) in standardize_reduction(reduction)
     78     allowed = {"sum_over_batch_size", "sum", None, "none"}
     79     if reduction not in allowed:
---> 80         raise ValueError(
     81             "Invalid value for argument `reduction`. "
     82             f"Expected one of {allowed}. Received: "

ValueError: Invalid value for argument `reduction`. Expected one of {'sum', 'none', 'sum_over_batch_size', None}. Received: reduction=auto

Any  help in this issue will be appreciated. Thanks.

**Comment by tilakrayal** [comment]
@pataneanant,
The tensorflow 2.16.1 by default consists of the keras3.0 version which might be reason for the error. and the tensorflow 2.15 consists of tf-keras 2.15(keras2 version). 

To work the code in tensorflow 2.16.1, you should change some of the changes which are compatible with the keras3.0 version.

https://keras.io/api/

Thank you!

**Comment by pataneanant** [comment]
@tilakrayal Thanks for the response mate. 

I'll try this and let you know. Could you please provide any resource which is specific for my use case. This would be very helpful.

**Comment by tilakrayal** [comment]
@pataneanant,
Please provide the update once you have tested. Thank you!

**Comment by pataneanant** [comment]
Unfortunately, I was not able to find a solution for this, so I had to retrain my model in TensorFlow v2.16.1. Hopefully, someone will find the solution, and please do share it here!

**Comment by tilakrayal** [comment]
@pataneanant,
The code which was written in the version keras3.0 i.e., tensorflow 2.16.1, can be imported in the latest stable version tensorflow v2.17, in which both contain keras3.0. As tensorflow v2.15 contains keras2.0, you might face the problem. 
https://keras.io/api/

Thank you!

**Comment by sggreenberg** [comment]
I have same error as OP

**Comment by tilakrayal** [comment]
@sggreenberg,
Could you please try to raise a new issue with the complete details and the reproducible code? Thank you!
