### ISSUE TITLE
Tensorboard: Undefined import in serialize_tensorboard.py

### ISSUE THREAD

**Issue by tarrencev** [tensorflow/tensorflow#7041]
It looks like this change https://github.com/tensorflow/tensorflow/commit/e121667dc609de978a223c56ee906368d2c4ceef modified the module imports in `serialize_tensorboard.py` to remove the import of `tf` but did not update all the usages of `tf`. As such, `tf` is not defined error is thrown when trying to run the script.

**Comment by drpngx** [comment]
@jart looks like we missed some `tf.foo` in tests?

**Comment by jart** [comment]
Assigning to owner of script.

**Comment by dandelionmane** [comment]
I'm going to remove the script.

**Comment by dandelionmane** [comment]
The script was removed.
