### ISSUE TITLE
TensorFlow v2.12.0 Not Supporting GPU on Ubuntu 22.04 with CUDA 12.4 and cuDNN 9.0

### ISSUE THREAD

**Issue by hamzaziizzz** [tensorflow/tensorflow#70444]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf 2.12.0

### Custom code

No

### OS platform and distribution

Linux Ubuntu 22.04

### Python version

3.10.12

### CUDA/cuDNN version

CUDA Version: 12.4, cuDNN Version: 9.0.0

### GPU model and memory

NVIDIA GeForce RTX 4050, 6GB

### System Information
- **OS Platform and Distribution**: Ubuntu 22.04
- **TensorFlow Version**: v2.12.0
- **Python Version**: 3.10.12
- **CUDA Version**: 12.4
- **cuDNN Version**: 9.0.0
- **NVIDIA Driver Version**: 550.54.15
- **GPU Model and Memory**: NVIDIA GeForce RTX 4050, 6GB

### Describe the Problem
I am experiencing issues with TensorFlow v2.12.0 not recognizing the GPU on my Ubuntu 22.04 system. I have installed CUDA Toolkit 12.4 and cuDNN 9.0.0, but TensorFlow does not seem to support these versions out of the box. The `nvidia-smi` command correctly shows the GPU and its details, but TensorFlow is unable to detect the GPU.

### Steps to Reproduce
1. Install Ubuntu 22.04.
2. Install TensorFlow v2.12.0.
3. Install CUDA Toolkit 12.4 and cuDNN 9.0.0.
4. Verify CUDA and cuDNN installation.
5. Run a TensorFlow script that requires GPU support using `python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"`

#### Output of `nvidia-smi`:
```bash
Wed Jun 26 19:54:51 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4050 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   45C    P8              3W /   60W |     513MiB /   6141MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      1804      G   /usr/lib/xorg/Xorg                              4MiB |
|    0   N/A  N/A     12083      C   /usr/bin/python                               500MiB |
+-----------------------------------------------------------------------------------------+
```

### Additional Information
I have confirmed that TensorFlow v2.12.0 is working fine with CUDA version 12.4 using docker.
![image](https://github.com/tensorflow/tensorflow/assets/67309795/df84b377-05e4-42a0-ab6f-ba0f6bfc64cd)

### Standalone code to reproduce the issue

```shell
python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
```

### Relevant log output

```shell
2024-06-26 19:48:40.302647: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-06-26 19:48:40.388659: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-26 19:48:40.561335: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-06-26 19:48:40.561586: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-06-26 19:48:40.967074: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-06-26 19:48:41.967172: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:996] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-06-26 19:48:41.987948: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1956] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
[]
```

**Comment by tilakrayal** [comment]
@hamzaziizzz,
Tensorflow 2.12 is not compatible with the CUDA 12.4 and cuDNN 9.0 which you are trying. TF v2.12 is built and tested against CUDA 11.8. Could you please check if you are facing the same error with CUDA 11.8 and cuDNN 8.6.

https://www.tensorflow.org/install/source#gpu
![image](https://github.com/tensorflow/tensorflow/assets/81610181/a11faf44-8cc4-4a7e-8e01-1d9c6045a38e)


 Thanks!

**Comment by hamzaziizzz** [comment]
OK, I understand and thank you for your assistance. So according to this compatibility matrix, there are no current versions of TensorFlow which is compatible with CUDA 12.4 and cuDNN 9.0, the only way I can utilize GPU with TensorFlow on my machine is through Docker?

**Comment by ClaudiaShu** [comment]
Have Tensorflow work with CUDA 12.4 and cuDNN 9.0 following this post: https://blog.stackademic.com/use-gpu-in-tensorflow-on-ubuntu-22-04-f033e59cf5cb

**Comment by tilakrayal** [comment]
@hamzaziizzz,
Apologies for the delay. Yeah as per the official tested build configurations, the latest tensorflower v2.17 is also compatible with CUDA 12.3 and cuDNN 8.9 for the smoother installation and the execution as well. 
https://www.tensorflow.org/install/source#gpu
Thank you!
