### ISSUE TITLE
NotFoundError: /tf_files/retrained_graph.pb

### ISSUE THREAD

**Issue by gitgreencoder** [tensorflow/tensorflow#7049]
When I tried to follow the Tensorflow Poets tutorial steps, I got this error when try to run the label_image.py file with classifier.

python /tf_files/label_image.py /tf_files/flower_photos/daisy/21652746_cc379e0eea_m.jpg 
Traceback (most recent call last):
  File "/tf_files/label_image.py", line 15, in <module>
    graph_def.ParseFromString(f.read())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 106, in read
    self._preread_check()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 73, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: /tf_files/retrained_graph.pb
root@858f20e4c756:/tensorflow# ls /tf_files/retrained_graph.pd 

NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
git rev-parse HEAD              
45ab528211c962b19e12f6b77165848310271624
2. The output of `bazel version`
Build label: 0.3.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Oct 7 17:25:10 2016 (1475861110)
Build timestamp: 1475861110
Build timestamp as int: 1475861110
### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by drpngx** [comment]
The log got truncated. What's the result of ls `/tf_files`?

**Comment by gitgreencoder** [comment]
You can close this now. I found out is was some weird permission issue on the file. I run in sudo mode and it fixed it.
