### ISSUE TITLE
Fail to build from source

### ISSUE THREAD

**Issue by untom** [tensorflow/tensorflow#705]
Hi!

I am unable to build TensorFlow from source. I am using a custom installation of Python 3.5.1 on Centos7. Since the system  only has Cuda 7.5 / cudnn 7.0 installed, I changed all references in the source code to that (grepping for "libcu" in the source code).

    $ bazel build --config=cuda --verbose_failures --spawn_strategy=standalone -c opt //tensorflow/tools/pip_package:build_pip_package
    WARNING: Output base '/system/user/unterthi/.cache/bazel/_bazel_unterthi/85e103d92fd5b6e762399323367e173a' is on NFS. This may lead to surprising failures and undetermined behavior.
    WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
    ____Loading...
    ____Loading complete.  Analyzing...
    ____Found 1 target...
    ____Building...
     ____From Compiling tensorflow/stream_executor/cuda/cuda_dnn.cc:
    tensorflow/stream_executor/cuda/cuda_dnn.cc:147:39: error: '::cudnnAddTensor_v3' has not been declared
         typedef std::add_pointer<decltype(::__name)>::type FuncPointerT;       \
                                           ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:215:3: note: in expansion of macro 'PERFTOOLS_GPUTOOLS_CUDNN_WRAP'
       __macro(cudnnAddTensor_v3)                                  \
       ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:221:1: note: in expansion of macro 'CUDNN_DNN_ROUTINE_EACH_R3'
     CUDNN_DNN_ROUTINE_EACH_R3(PERFTOOLS_GPUTOOLS_CUDNN_WRAP)
     ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:147:39: error: '::cudnnAddTensor_v3' has not been declared
         typedef std::add_pointer<decltype(::__name)>::type FuncPointerT;       \
                                           ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:215:3: note: in expansion of macro 'PERFTOOLS_GPUTOOLS_CUDNN_WRAP'
       __macro(cudnnAddTensor_v3)                                  \
       ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:221:1: note: in expansion of macro 'CUDNN_DNN_ROUTINE_EACH_R3'
     CUDNN_DNN_ROUTINE_EACH_R3(PERFTOOLS_GPUTOOLS_CUDNN_WRAP)
     ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:147:48: error: template argument 1 is invalid
         typedef std::add_pointer<decltype(::__name)>::type FuncPointerT;       \
                                                    ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:215:3: note: in expansion of macro 'PERFTOOLS_GPUTOOLS_CUDNN_WRAP'
       __macro(cudnnAddTensor_v3)                                  \
       ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:221:1: note: in expansion of macro 'CUDNN_DNN_ROUTINE_EACH_R3'
     CUDNN_DNN_ROUTINE_EACH_R3(PERFTOOLS_GPUTOOLS_CUDNN_WRAP)
     ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:147:51: error: expected ';' at end of member declaration
         typedef std::add_pointer<decltype(::__name)>::type FuncPointerT;       \
                                                       ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:215:3: note: in expansion of macro 'PERFTOOLS_GPUTOOLS_CUDNN_WRAP'
       __macro(cudnnAddTensor_v3)                                  \
       ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:221:1: note: in expansion of macro 'CUDNN_DNN_ROUTINE_EACH_R3'
     CUDNN_DNN_ROUTINE_EACH_R3(PERFTOOLS_GPUTOOLS_CUDNN_WRAP)
     ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:147:56: error: 'FuncPointerT' does not name a type
         typedef std::add_pointer<decltype(::__name)>::type FuncPointerT;       \
                                                            ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:215:3: note: in expansion of macro 'PERFTOOLS_GPUTOOLS_CUDNN_WRAP'
       __macro(cudnnAddTensor_v3)                                  \
       ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:221:1: note: in expansion of macro 'CUDNN_DNN_ROUTINE_EACH_R3'
     CUDNN_DNN_ROUTINE_EACH_R3(PERFTOOLS_GPUTOOLS_CUDNN_WRAP)
     ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:148:12: error: 'FuncPointerT' does not name a type
         static FuncPointerT DynLoad() {                                        \
                ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:215:3: note: in expansion of macro 'PERFTOOLS_GPUTOOLS_CUDNN_WRAP'
       __macro(cudnnAddTensor_v3)                                  \
       ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:221:1: note: in expansion of macro 'CUDNN_DNN_ROUTINE_EACH_R3'
     CUDNN_DNN_ROUTINE_EACH_R3(PERFTOOLS_GPUTOOLS_CUDNN_WRAP)
     ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc: In member function 'void perftools::gputools::cuda::dynload::DynLoadShim__cudnnAddTensor_v3::CallWrapper(perftools::gputools::cuda::CUDAExecutor*, tensorflow::Notification*, cudnnStatus_t*, const Args& ...)':
    tensorflow/stream_executor/cuda/cuda_dnn.cc:160:25: error: there are no arguments to 'DynLoad' that depend on a template parameter, so a declaration of 'DynLoad' must be available [-fpermissive]
           *retval = DynLoad()(args...);                                        \
                             ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:215:3: note: in expansion of macro 'PERFTOOLS_GPUTOOLS_CUDNN_WRAP'
       __macro(cudnnAddTensor_v3)                                  \
       ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:221:1: note: in expansion of macro 'CUDNN_DNN_ROUTINE_EACH_R3'
     CUDNN_DNN_ROUTINE_EACH_R3(PERFTOOLS_GPUTOOLS_CUDNN_WRAP)
     ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:160:25: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
           *retval = DynLoad()(args...);                                        \
                             ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:215:3: note: in expansion of macro 'PERFTOOLS_GPUTOOLS_CUDNN_WRAP'
       __macro(cudnnAddTensor_v3)                                  \
       ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:221:1: note: in expansion of macro 'CUDNN_DNN_ROUTINE_EACH_R3'
     CUDNN_DNN_ROUTINE_EACH_R3(PERFTOOLS_GPUTOOLS_CUDNN_WRAP)
     ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc: In instantiation of 'void perftools::gputools::cuda::dynload::DynLoadShim__cudnnAddTensor_v3::CallWrapper(perftools::gputools::cuda::CUDAExecutor*, tensorflow::Notification*, cudnnStatus_t*, const Args& ...) [with Args = {cudnnContext*, const float*, cudnnTensorStruct*, const void*, const float*, cudnnTensorStruct*, void*}]':
    tensorflow/stream_executor/cuda/cuda_dnn.cc:221:1:   required from 'cudnnStatus_t perftools::gputools::cuda::dynload::DynLoadShim__cudnnAddTensor_v3::operator()(perftools::gputools::cuda::CUDAExecutor*, Args ...) [with Args = {cudnnContext*, const float*, cudnnTensorStruct*, const void*, const float*, cudnnTensorStruct*, void*}]'
    tensorflow/stream_executor/cuda/cuda_dnn.cc:1081:30:   required from here
    tensorflow/stream_executor/cuda/cuda_dnn.cc:160:25: error: 'DynLoad' was not declared in this scope
           *retval = DynLoad()(args...);                                        \
                             ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:215:3: note: in expansion of macro 'PERFTOOLS_GPUTOOLS_CUDNN_WRAP'
       __macro(cudnnAddTensor_v3)                                  \
       ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc:221:1: note: in expansion of macro 'CUDNN_DNN_ROUTINE_EACH_R3'
     CUDNN_DNN_ROUTINE_EACH_R3(PERFTOOLS_GPUTOOLS_CUDNN_WRAP)
     ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc: In member function 'virtual bool perftools::gputools::cuda::CudnnSupport::DoNormalize(perftools::gputools::Stream*, const perftools::gputools::dnn::NormalizeDescriptor&, const perftools::gputools::DeviceMemory<float>&, perftools::gputools::DeviceMemory<float>*)':
    tensorflow/stream_executor/cuda/cuda_dnn.cc:1226:1: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc: In member function 'virtual bool perftools::gputools::cuda::CudnnSupport::DoElementwiseOperate(perftools::gputools::Stream*, perftools::gputools::dnn::ElementwiseOperation, tensorflow::gtl::ArraySlice<perftools::gputools::dnn::BatchDescriptor>, tensorflow::gtl::ArraySlice<const perftools::gputools::DeviceMemory<float>*>, const perftools::gputools::dnn::BatchDescriptor&, perftools::gputools::DeviceMemory<float>*)':
    tensorflow/stream_executor/cuda/cuda_dnn.cc:1287:1: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc: In member function 'virtual bool perftools::gputools::cuda::CudnnSupport::DoXYPad(perftools::gputools::Stream*, const perftools::gputools::dnn::BatchDescriptor&, const perftools::gputools::DeviceMemory<float>&, tensorflow::int64, tensorflow::int64, tensorflow::int64, tensorflow::int64, perftools::gputools::DeviceMemory<float>*)':
    tensorflow/stream_executor/cuda/cuda_dnn.cc:1294:1: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
    tensorflow/stream_executor/cuda/cuda_dnn.cc: In member function 'virtual bool perftools::gputools::cuda::CudnnSupport::DoXYSlice(perftools::gputools::Stream*, const perftools::gputools::dnn::BatchDescriptor&, const perftools::gputools::DeviceMemory<float>&, tensorflow::int64, tensorflow::int64, tensorflow::int64, tensorflow::int64, perftools::gputools::DeviceMemory<float>*)':
    tensorflow/stream_executor/cuda/cuda_dnn.cc:1301:1: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
    ERROR: /system/apps/biosoft/python-351/tmp/tensorflow/tensorflow/stream_executor/BUILD:5:1: C++ compilation of rule '//tensorflow/stream_executor:stream_executor' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
      (cd /system/user/unterthi/.cache/bazel/_bazel_unterthi/85e103d92fd5b6e762399323367e173a/tensorflow && \
      exec env - \
        INTERCEPT_LOCALLY_EXECUTABLE=1 \
        PATH=/system/apps/biosoft/jdk1.8.0_40/bin:/system/apps/biosoft/bazel-0.1.1/bazel-bin/src:/usr/local/cuda/bin:/system/apps/biosoft/R-3.2.0/bin:/system/apps/biosoft/caffe_py351/distribute/bin:/system/apps/biosoft/lmdb-0.9.17/bin:/system/apps/biosoft/protobuf-3.0.0-alpha-3.1_py351/bin:/system/apps/biosoft/boost_1_59_0_py351/bin:/system/apps/biosoft/python-351/bin:/usr/local/cuda/bin:/system/apps/biosoft/R-3.2.0/bin:/system/apps/biosoft/caffe_py351/distribute/bin:/system/apps/biosoft/lmdb-0.9.17/bin:/system/apps/biosoft/protobuf-3.0.0-alpha-3.1_py351/bin:/system/apps/biosoft/boost_1_59_0_py351/bin:/system/apps/biosoft/python-351/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/system/user/unterthi/bin:/system/user/unterthi/bin \
      third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -iquote . -iquote bazel-out/local_linux-py3-opt/genfiles -isystem google/protobuf/src -isystem bazel-out/local_linux-py3-opt/genfiles/google/protobuf/src -isystem tools/cpp/gcc3 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-py3-opt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-py3-opt/genfiles/external/png_archive/libpng-1.2.53 -isystem external/re2 -isystem bazel-out/local_linux-py3-opt/genfiles/external/re2 -isystem third_party/gpus/cuda -isystem bazel-out/local_linux-py3-opt/genfiles/third_party/gpus/cuda -isystem third_party/gpus/cuda/include -isystem bazel-out/local_linux-py3-opt/genfiles/third_party/gpus/cuda/include -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/stream_executor/tensorflow/stream_executor/cuda/cuda_dnn.pic.o' -MD -MF bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/stream_executor/tensorflow/stream_executor/cuda/cuda_dnn.pic.d -fPIC -c tensorflow/stream_executor/cuda/cuda_dnn.cc -o bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/stream_executor/tensorflow/stream_executor/cuda/cuda_dnn.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
      (cd /system/user/unterthi/.cache/bazel/_bazel_unterthi/85e103d92fd5b6e762399323367e173a/tensorflow && \
      exec env - \
        INTERCEPT_LOCALLY_EXECUTABLE=1 \
        PATH=/system/apps/biosoft/jdk1.8.0_40/bin:/system/apps/biosoft/bazel-0.1.1/bazel-bin/src:/usr/local/cuda/bin:/system/apps/biosoft/R-3.2.0/bin:/system/apps/biosoft/caffe_py351/distribute/bin:/system/apps/biosoft/lmdb-0.9.17/bin:/system/apps/biosoft/protobuf-3.0.0-alpha-3.1_py351/bin:/system/apps/biosoft/boost_1_59_0_py351/bin:/system/apps/biosoft/python-351/bin:/usr/local/cuda/bin:/system/apps/biosoft/R-3.2.0/bin:/system/apps/biosoft/caffe_py351/distribute/bin:/system/apps/biosoft/lmdb-0.9.17/bin:/system/apps/biosoft/protobuf-3.0.0-alpha-3.1_py351/bin:/system/apps/biosoft/boost_1_59_0_py351/bin:/system/apps/biosoft/python-351/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/system/user/unterthi/bin:/system/user/unterthi/bin \
      third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -iquote . -iquote bazel-out/local_linux-py3-opt/genfiles -isystem google/protobuf/src -isystem bazel-out/local_linux-py3-opt/genfiles/google/protobuf/src -isystem tools/cpp/gcc3 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-py3-opt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-py3-opt/genfiles/external/png_archive/libpng-1.2.53 -isystem external/re2 -isystem bazel-out/local_linux-py3-opt/genfiles/external/re2 -isystem third_party/gpus/cuda -isystem bazel-out/local_linux-py3-opt/genfiles/third_party/gpus/cuda -isystem third_party/gpus/cuda/include -isystem bazel-out/local_linux-py3-opt/genfiles/third_party/gpus/cuda/include -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/stream_executor/tensorflow/stream_executor/cuda/cuda_dnn.pic.o' -MD -MF bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/stream_executor/tensorflow/stream_executor/cuda/cuda_dnn.pic.d -fPIC -c tensorflow/stream_executor/cuda/cuda_dnn.cc -o bazel-out/local_linux-py3-opt/bin/tensorflow/stream_executor/_objs/stream_executor/tensorflow/stream_executor/cuda/cuda_dnn.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
    Target //tensorflow/tools/pip_package:build_pip_package failed to build
    ____Elapsed time: 11.581s, Critical Path: 9.50s

Any help would be appreciated

**Comment by untom** [comment]
I just noticed this seems to have been my own fault, I had installed cudnn incorrectly.

**Comment by ahaque** [comment]
What was the specific solution?

**Comment by ahaque** [comment]
@untom What was the specific solution?

**Comment by untom** [comment]
to install a more recent version of cudnn ;)
