### ISSUE TITLE
tfm.nlp.layers.RelativePositionEmbedding 

### ISSUE THREAD

**Issue by Leo-Lifeblood** [tensorflow/tensorflow#70520]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.16.1

### Custom code

Yes

### OS platform and distribution

google colab

### Current behavior?

<img width="727" alt="Screenshot 2024-06-27 at 17 49 59" src="https://github.com/tensorflow/tensorflow/assets/174037709/021a5a0a-aff2-4b07-8e1d-dba1972b99ee">

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import tensorflow_models as tfm

input_tensor = tf.random.normal((32, 87, 128))


position_emb = tfm.nlp.layers.RelativePositionEmbedding(hidden_size=128)


output_tensor = position_emb(input_tensor)
 

print(output_tensor.shape)
```

**Comment by sushreebarsa** [comment]
@Leo-Lifeblood I was able to replicate the output reported [here](https://colab.research.google.com/gist/sushreebarsa/c573727f8cf0f77be2dc13af243567a4/70520.ipynb), could you please share the error you are encountering ?
Thank you!

**Comment by Leo-Lifeblood** [comment]
The error is that the batch dimension in this case 32 is being deleted. This breaks any training loop.

**Comment by tilakrayal** [comment]
@Leo-Lifeblood,
Thank you for reporting the issue. tfm.nlp.layers.RelativePositionEmbedding API is more related to tf-models. Could you please raise the issue on the TensorFlow/tf-models [repo](https://github.com/tensorflow/models/issues) for the quick response.


https://github.com/tensorflow/models/blob/master/official/nlp/modeling/layers/position_embedding.py

Thank you!
