### ISSUE TITLE
Please create a new version tag.

### ISSUE THREAD

**Issue by raraujosc** [tensorflow/tensorflow#7052]
There's currently no version tag that has all the WORKSPACE links working correctly. Can we please create one that I can point to to have a stable TF version? If I point to HEAD using git submodule we often update the TF version by mistake.

Thanks!

**Comment by drpngx** [comment]
The latest release is [0.12.1](https://github.com/tensorflow/tensorflow/releases).

**Comment by raraujosc** [comment]
That release is broken as it points to a non-existing zlib url:
https://github.com/tensorflow/tensorflow/blob/0.12.1/tensorflow/workspace.bzl

**Comment by drpngx** [comment]
@jart I thought we had cherry-picked into this?

**Comment by drpngx** [comment]
@yifeif I thought we had cherry-picked into all release points?

**Comment by gunan** [comment]
Tags were not moved after cherrypicks.
One option for you is to use the tip of the release branches.
However, v1.0.0-rc0 is just created. So you may also use that one.
https://github.com/tensorflow/tensorflow/tree/v1.0.0-rc0

**Comment by raraujosc** [comment]
Tensorflow 1.0 does not have the fix for #6706. We still don't have any tags or branches that work when Tensorflow is used as an external dependency, like tensorflow_serving uses it. Only the HEAD version is usable.

**Comment by jart** [comment]
I think I'm going to reopen that bug.

**Comment by raraujosc** [comment]
That bug is about a broken reference to a bzl file. It's fixed in HEAD but in this bug I'm asking for a stable tag that has the fix. There's no such tag today. Tensorflow 1.0 does not have the fix for #6706.

Running ./configure is a separate issue that we can live with for now, but it'd be nice to get that fixed too.

**Comment by gunan** [comment]
Which commit did fix the problem for you? I can maybe cherrypick that into 1.0 branch.

**Comment by raraujosc** [comment]
I'm not sure the exact commit. See your comment here: https://github.com/tensorflow/tensorflow/issues/6706#issuecomment-273939158

**Comment by yifeif** [comment]
Looks like this commit? https://github.com/tensorflow/tensorflow/pull/6958/commits/0ee1301dd2eb7cc3671f88f5e25bb1795faf87fe

**Comment by gunan** [comment]
there should be a separate one for jpeg.

**Comment by yifeif** [comment]
Also saw this one https://github.com/tensorflow/tensorflow/commit/4f6e6eb285e0e925271d632cc688811ca4e8c5a2 but it should already be in v1.0.0-rc0.
