### ISSUE TITLE
ModuleNotFoundError: No module named 'tflite_support.task'

### ISSUE THREAD

**Issue by baqwas** [tensorflow/tensorflow#70546]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian GNU/Linux 12 (bookworm) **aarch64**
- TensorFlow installed from (source or binary): **tflite_support** installed via pip under PyCharm
- TensorFlow version (or github SHA if from source):

```
Traceback (most recent call last):
  File "/home/chowkidar/PycharmProjects/test_tflite/test_mediapipe.py", line 9, in <module>
    from tflite_support.task import vision
ModuleNotFoundError: No module named 'tflite_support.task'

Process finished with exit code 1
```

**Standalone code to reproduce the issue** 
```
from tflite_support.task import vision
from tflite_support.task import core
from tflite_support.task import processor
```

**Any other info / logs**

`import tflite_support`
works but cannot import modules vision, core and processor.

**Comment by sushreebarsa** [comment]
@baqwas The tflite_support.task module does not exist in the standard TensorFlow Lite (TFLite) package.  The [TensorFlow Lite Task Library](https://www.tensorflow.org/lite/inference_with_metadata/task_library/overview) is deprecated and replaced by [MediaPipe Tasks](https://ai.google.dev/edge/mediapipe/solutions/tasks). You might be facing this issue as you are using a deprecated API?
Thank you!

**Comment by baqwas** [comment]
Hello @sushreebarsa,

You are absolutely correct! In fact, here is the _header_ code that I was using:
```
import mediapipe as mp

from mediapipe.tasks import python
from mediapipe.tasks.python import vision
from mediapipe.tasks.python import text
from mediapipe.tasks.python import audio

import tflite_support
from tflite_support.task import vision
from tflite_support.task import core
from tflite_support.task import processor
```
I copied and pasted the totally redundant _tflite_support_ snippet. I didn't pay attention to what I was doing. Thanks to you, I will review the code in greater detail and pay attention to what is being performed.

Where are the **mediapipe** tutorials (for newbies), please?

Thanks again.
