### ISSUE TITLE
Slicing

### ISSUE THREAD

**Issue by macsharma** [tensorflow/tensorflow#7054]
I wish to implement the following line of code in tensorflow. Given below is the numpy version
correct_scores=scores[range(N), np.array(yTrain,dtype='int32')]

now in tensorflow, scores and yTrain are all variables, calculated on each minibatch. Is there a way to do this

**Comment by Carmezim** [comment]
This is probably a better suited question for StackOverflow. They also monitor there under the TensorFlow tag.
