### ISSUE TITLE
Build is failing on Linux GPU

### ISSUE THREAD

**Issue by lorenzo93** [tensorflow/tensorflow#7056]
Hi,

I'm trying with no luck to build TF for OpenCL from source. I configured a new installed machine as is described in your guide but the build is failing.

I'm launching the build through this command:
`bazel build -c opt --config=sycl //tensorflow/tools/pip_package:build_pip_package`

And below you can find all the requested informations from my OS. In attach you'll find the [Errors](https://github.com/tensorflow/tensorflow/files/729409/Errors.TF.txt) the compiler shows me.
I've tryed also to build with clang against GCC/G++ with no luck.
[Errors TF.txt](https://github.com/tensorflow/tensorflow/files/729409/Errors.TF.txt)

Thank you

------------------

Operating System: Ubuntu 16.04, Kernel 4.4

Building TF for OpenCL as descripted in ./configure below:
`$ ./configure 
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python3
Please specify optimization flags to use during compilation [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? [Y/n] 
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python3.5/dist-packages
  /usr/lib/python3/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python3.5/dist-packages]

Using python library path: /usr/local/lib/python3.5/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] y
OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] n
No CUDA support will be enabled for TensorFlow
Please specify which C++ compiler should be used as the host C++ compiler. [Default is ]: /usr/bin/g++
Please specify which C compiler should be used as the host C compiler. [Default is ]: /usr/bin/gcc
Please specify the location where ComputeCpp for SYCL 1.2 is installed. [Default is /usr/local/computecpp]: `

`$ bazel version
Build label: 0.4.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 22 12:31:25 2016 (1482409885)
Build timestamp: 1482409885
Build timestamp as int: 1482409885`

`$ git rev-parse HEAD
a12c7dc3d83049e10c1dca8903d73cc71d3cb7b2`

**Comment by drpngx** [comment]
@gunan we don't support opencl, right?

**Comment by lorenzo93** [comment]
[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md)

It is your guide that tells me to do so.

**Comment by gunan** [comment]
We should update our guide, sorry for the confusion.
OpenCL support is still in its early stages, and it is experimental:
You can follow this issue for more information:
https://github.com/tensorflow/tensorflow/issues/22

**Comment by lukeiwanski** [comment]
@lorenzo93 Does it compile without `--config=sycl`? It seems like the compilation error comes from GCC6 headers.

**Comment by lorenzo93** [comment]
I'll test it tomorrow night and reply. I'm out for work

2017-01-26 12:27 GMT+01:00 Luke Iwanski <notifications@github.com>:

**Comment by dvisockas** [comment]
I have the same issue, so I thought that I'll drop it here instead of creating a new one. Compiling TF with `--config=syscl` throws an error:
```INFO: Found 1 target...
ERROR: /home/danielius/.cache/bazel/_bazel_danielius/c3436072caa9f5957dc8575117a2d1e5/external/llvm/BUILD:1661:1: C++ compilation of rule '@llvm//:support' failed: computecpp failed: error executing command external/local_config_sycl/crosstool/computecpp -Wall -msse3 -g0 -O2 -DNDEBUG '-std=c++11' -MD -MF ... (remaining 38 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
external/llvm/lib/Support/RandomNumberGenerator.cpp:34:8: error: reference to 'cl' is ambiguous
 static cl::opt<unsigned long long>
        ^
In file included from ./bazel-out/local_linux-opt/bin/external/llvm/_objs/support/external/llvm/lib/Support/RandomNumberGenerator.pic.sycl:13:0,
                 from <command-line>:0:
external/local_config_sycl/crosstool/../sycl/include/SYCL/predefines.h:88:14: note: candidates are: namespace cl { }
 namespace cl {
              ^
In file included from external/llvm/lib/Support/RandomNumberGenerator.cpp:17:0:
external/llvm/include/llvm/Support/CommandLine.h:48:14: note:                 namespace llvm::cl { }
 namespace cl {
              ^
external/llvm/lib/Support/RandomNumberGenerator.cpp:34:8: error: 'cl' does not name a type
 static cl::opt<unsigned long long>
        ^
external/llvm/lib/Support/RandomNumberGenerator.cpp: In constructor 'llvm::RandomNumberGenerator::RandomNumberGenerator(llvm::StringRef)':
external/llvm/lib/Support/RandomNumberGenerator.cpp:51:13: error: 'Seed' was not declared in this scope
   Data[0] = Seed;
             ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 73.376s, Critical Path: 68.71s
```

Compiling without `--config=syscl` works fine.

System information:
- Ubuntu 14.04 64bit
- Intel Haswell Mobile graphics / Radeon 8800M

Maybe two graphics cards might be an issue?

**Comment by lukeiwanski** [comment]
@lorenzo93 The GCC 6 STL headers exposed a bug in clang 3.6, which has been fixed upstream and will soon be merged into computecpp. Until then, it is possible to work around this by either using the GCC5 headers or libc++ (https://llvm.org/bugs/show_bug.cgi?id=24770)

**Comment by drpngx** [comment]
thanks @lukeiwanski -- very helpful!
