### ISSUE TITLE
Notebook is not working anymore

### ISSUE THREAD

**Issue by anilkumarvvss** [tensorflow/tensorflow#70562]
Hello,

https://github.com/tensorflow/docs/blob/940d94cb568bcdd4e82402eff3403ddcf5f874f2/site/en/tutorials/understanding/sngp.ipynb
Running this notebook, currently is leading to some errors at particular cells. Could you please update the notebook so that no error occurs? Thank you.

Best regards,
Anil

**Comment by tilakrayal** [comment]
@anilkumarvvss,
Thank you for the issue. 
Here you are trying to install the Tensorflow v2.16 which by default uses the Keras3.0 version. There are changes that happened in the keras3.0 which might be the reason for the error you are facing.

```python
!pip install -U -q --use-deprecated=legacy-resolver tf-models-official tensorflow
```
https://keras.io/api/

When I tried to execute the same code with tensorflow v2.15, it was executed without any issue/error. Kindly find the gist of it here. Thank you!

**Comment by anilkumarvvss** [comment]
could you adapt it to newer versions if possible? because we tried running it with minor modifications(to bypass errors) with new versions, but it's giving significantly different results with our workarounds. Please have a look at our workarounds in the attached notebook. Thanks :)
