### ISSUE TITLE
what's the difference betwee tf.nn.seq2seq and tf.python.ops.seq2seq?

### ISSUE THREAD

**Issue by coder3344** [tensorflow/tensorflow#7058]
what's the difference betwee tf.nn.seq2seq and tf.python.ops.seq2seq?

**Comment by drpngx** [comment]
There should not be a `tf.python.ops.seq2seq`. The public API defines `tf.nn.seq2seq`.

**Comment by coder3344** [comment]
but I found these two imports in two projects, this is why I got confused

**Comment by KeyYD** [comment]
I think this maybe caused by the difference of the tensorflow version. In the version 12, the later is not available

**Comment by andrewjylee** [comment]
Is this right? It seems like tf.nn.seq2seq is again deprecated as well? What's the new API?

**Comment by drpngx** [comment]
We weren't confident that `seq2seq` was ready -- its API is still changing. it's in `tf.contrib.seq2seq`.
