### ISSUE TITLE
Issue to compile on macOS with unrecognized command line option

### ISSUE THREAD

**Issue by jplu** [tensorflow/tensorflow#7059]
Hello,

I do have issues to compile Tensorflow on my mac in order to use the Java version. Here some useful information about my environment:

* macOS 10.12.3
* gcc 6.3.0 (from MacPorts)
* Bazel 4.3.0
* Python 2.7
* Tensorflow commit a12c7dc3d83049e10c1dca8903d73cc71d3cb7b2
* CPU only

Once I have done the ```./configure``` I'm trying to compile the Java version and here the log I get:

```
bazel build -c opt //tensorflow/java:tensorflow //tensorflow/java:libtensorflow_jni
INFO: Found 2 targets...
ERROR: /private/var/tmp/_bazel_jplu/00c84c0db16fb633b58c75ed37aef199/external/nanopb_git/BUILD:8:1: C++ compilation of rule '@nanopb_git//:nanopb' failed: cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 34 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: error: unrecognized command line option '-Wthread-safety'; did you mean '-fthread-jumps'?
gcc: error: unrecognized command line option '-Wself-assign'; did you mean '-Wparam-assign'?
INFO: Elapsed time: 6,013s, Critical Path: 0,05s
```

I also tried with a GCC 5.4 version and I get the exact same error.

Did anyone have an idea of what is going wrong? Am I using a wrong version of GCC?

Thanks in advance.

**Comment by drpngx** [comment]
Can you try this from the command-line?

```
gcc -v -c -xc++ /dev/null -o /dev/null
```

It looks like this is requested here:
https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/CROSSTOOL.tpl#L213

Could you try removing that?

**Comment by jplu** [comment]
Here the output I get:

```
gcc -v -c -xc++ /dev/null -o /dev/null
Using built-in specs.
COLLECT_GCC=gcc
Target: x86_64-apple-darwin16
Configured with: /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_lang_gcc6/gcc6/work/gcc-6.3.0/configure --prefix=/opt/local --build=x86_64-apple-darwin16 --enable-languages=c,c++,objc,obj-c++,lto,fortran --libdir=/opt/local/lib/gcc6 --includedir=/opt/local/include/gcc6 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-6 --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-6 --with-gxx-include-dir=/opt/local/include/gcc6/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local --enable-stage1-checking --disable-multilib --enable-lto --enable-libstdcxx-time --with-build-config=bootstrap-debug --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --with-pkgversion='MacPorts gcc6 6.3.0_0'
Thread model: posix
gcc version 6.3.0 (MacPorts gcc6 6.3.0_0) 
COLLECT_GCC_OPTIONS='-v' '-c' '-o' '/dev/null' '-mmacosx-version-min=10.12.3' '-asm_macosx_version_min=10.12' '-mtune=core2'
 /opt/local/libexec/gcc/x86_64-apple-darwin16/6.3.0/cc1plus -quiet -v -D__DYNAMIC__ /dev/null -fPIC -quiet -dumpbase null -mmacosx-version-min=10.12.3 -mtune=core2 -auxbase-strip /dev/null -version -o /var/folders/gc/mpn9gjgs2c9dxwmjm0xzkqg00000gn/T//cc2tp8Av.s
GNU C++14 (MacPorts gcc6 6.3.0_0) version 6.3.0 (x86_64-apple-darwin16)
	compiled by GNU C version 6.3.0, GMP version 6.1.2, MPFR version 3.1.4, MPC version 1.0.3, isl version 0.14 or 0.13
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
ignoring nonexistent directory "/opt/local/lib/gcc6/gcc/x86_64-apple-darwin16/6.3.0/../../../../../x86_64-apple-darwin16/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/local/include/gcc6/c++/
 /opt/local/include/gcc6/c++//x86_64-apple-darwin16
 /opt/local/include/gcc6/c++//backward
 /opt/local/lib/gcc6/gcc/x86_64-apple-darwin16/6.3.0/include
 /opt/local/include
 /opt/local/lib/gcc6/gcc/x86_64-apple-darwin16/6.3.0/include-fixed
 /usr/include
 /System/Library/Frameworks
 /Library/Frameworks
End of search list.
GNU C++14 (MacPorts gcc6 6.3.0_0) version 6.3.0 (x86_64-apple-darwin16)
	compiled by GNU C version 6.3.0, GMP version 6.1.2, MPFR version 3.1.4, MPC version 1.0.3, isl version 0.14 or 0.13
GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
Compiler executable checksum: 7f53308891a2e11385f319c4215fc083
COLLECT_GCC_OPTIONS='-v' '-c' '-o' '/dev/null' '-mmacosx-version-min=10.12.3'  '-mtune=core2'
 /opt/local/bin/as -v -arch x86_64 -force_cpusubtype_ALL -o /dev/null /var/folders/gc/mpn9gjgs2c9dxwmjm0xzkqg00000gn/T//cc2tp8Av.s
Apple Inc version cctools-895, GNU assembler version 1.38
COMPILER_PATH=/opt/local/libexec/gcc/x86_64-apple-darwin16/6.3.0/:/opt/local/libexec/gcc/x86_64-apple-darwin16/6.3.0/:/opt/local/libexec/gcc/x86_64-apple-darwin16/:/opt/local/lib/gcc6/gcc/x86_64-apple-darwin16/6.3.0/:/opt/local/lib/gcc6/gcc/x86_64-apple-darwin16/
LIBRARY_PATH=/opt/local/lib/gcc6/gcc/x86_64-apple-darwin16/6.3.0/:/opt/local/lib/gcc6/gcc/x86_64-apple-darwin16/6.3.0/../../../
COLLECT_GCC_OPTIONS='-v' '-c' '-o' '/dev/null' '-mmacosx-version-min=10.12.3'  '-mtune=core2'
```

Next, if I comment the two involved lines in the file you mention, it fails with the same error, but, because of an another file:

```
bazel build -c opt //tensorflow/java:tensorflow //tensorflow/java:libtensorflow_jni
INFO: Found 2 targets...
ERROR: /private/var/tmp/_bazel_jplu/00c84c0db16fb633b58c75ed37aef199/external/farmhash_archive/BUILD:12:1: C++ compilation of rule '@farmhash_archive//:farmhash' failed: cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 36 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: error: unrecognized command line option '-Wthread-safety'; did you mean '-fthread-jumps'?
gcc: error: unrecognized command line option '-Wself-assign'; did you mean '-Wparam-assign'?
INFO: Elapsed time: 17,390s, Critical Path: 0,31s
```

**Comment by drpngx** [comment]
I'm not sure where these flags are coming from. @asimshankar any idea?

**Comment by asimshankar** [comment]
I suspect that this happening because you're actually using `gcc` as opposed to `clang` which is the compiler that ships with xcode and is aliased to `gcc` on OS X. For example, on my Mac:

```sh
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Shows that `/usr/bin/gcc` is actually clang. The toolchain configuration that @drpngx linked to is also [designed for clang and not gcc on OS X](https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/CROSSTOOL.tpl#L172).

Getting things to work with `gcc` on OS X will be some work, involving a review of the toolchain configuration in CROSSTOOL.tpl.

Is it possible for you to use the default C compiler that ships with xcode? Or to put it differently, mind shedding some light on why you need to use a `gcc` from MacPorts instead of using the toolchain installed by xcode?

**Comment by drpngx** [comment]
We can also use `-Xclang-only=-Wthread-safety` to get it work for both (obviously disabling that on gcc).

**Comment by jplu** [comment]
Hello,

First of all, thanks a lot for you very clear explanation.

> Is it possible for you to use the default C compiler that ships with xcode? Or to put it differently, mind shedding some light on why you need to use a gcc from MacPorts instead of using the toolchain installed by xcode?

I can install the xcode toolchain and switch between both it is ok. The reason is that I don't use xcode at all to code, and I didn't want something that heavy installed for not being used at all. the second reason I'm used to the GNU tools so I replaced the "MacOS" version of these tools for using the GNU ones.

> We can also use -Xclang-only=-Wthread-safety to get it work for both (obviously disabling that on gcc).

If there is a possibility to make GNU GCC working, it would be super nice!

I'm closing this issue as my problem has found a clear explanation. Thanks again.

**Comment by samhodge** [comment]
I am getting the same error with Clang 9.0.0

kaos:tensorflow sam$ which g++
/usr/bin/g++
kaos:tensorflow sam$ g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

I have been considering a downgrade

**Comment by samhodge** [comment]
here is the exact error 
ERROR: /private/var/tmp/_bazel_sam/7fbd006de80bc278719e770d66f90e2b/external/flatbuffers/BUILD:94:1: Linking of rule '@flatbuffers//:flatc' failed (Exit 1)
gcc: error: unrecognized command line option '-fobjc-link-runtime'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 22.061s, Critical Path: 12.49s
FAILED: Build did NOT complete successfully

**Comment by samhodge** [comment]
downgraded still getting issue

rotobuf_archive/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_sam/7fbd006de80bc278719e770d66f90e2b/external/protobuf_archive/WORKSPACE (@com_google_protobuf) does not match the name given in the repository's definition (@protobuf_archive); this will cause a build error in future versions
ERROR: /private/var/tmp/_bazel_sam/7fbd006de80bc278719e770d66f90e2b/external/local_config_cc/BUILD:50:5: in apple_cc_toolchain rule @local_config_cc//:cc-compiler-darwin_x86_64: Xcode version must be specified to use an Apple CROSSTOOL. If your Xcode version has changed recently, try: "bazel clean --expunge" to re-run Xcode configuration
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis of target '@local_config_cc//:cc-compiler-darwin_x86_64' failed; build aborted
INFO: Elapsed time: 16.684s
FAILED: Build did NOT complete successfully (58 packages loaded)
    currently loading: tensorflow/python ... (2 packages)

**Comment by samhodge** [comment]
Never mind I only downgraded my command line tools I think I need to downgrade all of XCode, initially I was trying to work with an anaconda based g++ 4.8.5 that didnt work out so well either.
