### ISSUE TITLE
swig command not found

### ISSUE THREAD

**Issue by wenhuchen** [tensorflow/tensorflow#706]
I try to build the GPU version on uBuntu 64 machine with command, 
```
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```
I installed swig and bazel successfully, but it still reports that swig not found.
```
src/main/tools/namespace-sandbox.c:476: arg: tensorflow/python/tensorflow.i
bazel-out/host/bin/tensorflow/swig: line 17: swig: command not found
ERROR: /userdata01/Users/wenhuchen/tensorflow/tensorflow/tensorflow.bzl:298:3: SWIGing tensorflow/python/tensorflow.i failed: Error during execution of spawn: Process exited with status 127: Error during execution of spawn: Process exited with status 127.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
Can anyone help me with that?

**Comment by wenhuchen** [comment]
swig version is 3.0.8

**Comment by mrry** [comment]
Where is your copy of `swig` installed (i.e. what result do you get when you run `which swig`)?

As a short-term fix, you can modify [`swig.sh`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/swig/swig.sh) to invoke SWIG by its absolute path.

**Comment by wenhuchen** [comment]
I installed it locally, I specify the absolute path in the swig.sh and got the same error
```
 /home/wenhuchen/.local/bin/swig: No such file or directory
ERROR: /userdata01/Users/wenhuchen/tensorflow/tensorflow/tensorflow.bzl:298:3: SWIGing tensorflow/python/tensorflow.i failed: Error during execution of spawn: Process exited with status 127: Error during execution of spawn: Process exited with status 127.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
I'm sure swig is usable, and my swig.sh looks like below
```
 /home/wenhuchen/.local/bin/swig "$@"
```

**Comment by mrry** [comment]
Just to confirm, if you run `/home/wenhuchen/.local/bin/swig` from the command line, does that work without error?

**Comment by psycharo** [comment]
try modifying [tensorflow.bzl here ](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorflow.bzl#L261) by adding an extra parameter:
```
use_default_shell_env=True,
```
and building with: 
```
--genrule_strategy=standalone --spawn_strategy=standalone
```

thanks to [bazel support](https://groups.google.com/forum/#!msg/bazel-discuss/FrHiyndAtik/HAbZBGGXFQAJ)

**Comment by wenhuchen** [comment]
Fixed the problem. Thanks for help

**Comment by ostrokach** [comment]
@wenhuchen How did you fix the problem. Just editing the `swig.sh` file?

**Comment by chrisk1** [comment]
Thank you for this @psycharo - I had the same issue when building (using newer version, so different line numbers):

`bazel-out/host/bin/external/org_tensorflow/tensorflow/swig: line 25: swig: command not found`

Thought it might be helpful to point out that the same solution (for r0.10) is to insert
`use_default_shell_env=True,`

at
https://github.com/tensorflow/tensorflow/blob/r0.10/tensorflow/tensorflow.bzl#L483
