### ISSUE TITLE
Tried multiple builds, Bazel, pip, file. non of it is working

### ISSUE THREAD

**Issue by asp616848** [tensorflow/tensorflow#70603]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.16.2

### Custom code

Yes

## Bazel

venv1) ➜  tensorflow git:(master) ✗ bazel build --config=opt --config=cuda
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Reading 'startup' options from /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/.bazelrc: --windows_enable_symlinks
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=100
INFO: Reading rc options for 'build' from /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --features=-force_no_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'build' from /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/8kesar/Filez/MathematicsProjects&Modeling/venv1/bin/python3 --action_env PYTHON_LIB_PATH=/home/8kesar/Filez/MathematicsProjects&Modeling/venv1/lib/python3.12/site-packages --python_path=/home/8kesar/Filez/MathematicsProjects&Modeling/venv1/bin/python3 --config=tensorrt --action_env TF_CUDA_VERSION=12 --action_env TF_CUDNN_VERSION=9 --action_env TF_TENSORRT_VERSION=10 --action_env TF_NCCL_VERSION= --action_env TF_CUDA_PATHS=/opt/cuda/targets/x86_64-linux/include,/opt/cuda/targets/x86_64-linux/lib/,/opt/cuda,/usr/include,/usr/include,/usr/lib --action_env CUDA_TOOLKIT_PATH=/opt/cuda --action_env TF_CUDA_COMPUTE_CAPABILITIES=8.9 --action_env GCC_HOST_COMPILER_PATH=/usr/bin/gcc --config=cuda
INFO: Found applicable config definition build:short_logs in file /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:tensorrt in file /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/.bazelrc: --repo_env TF_NEED_TENSORRT=1
INFO: Found applicable config definition build:cuda in file /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:opt in file /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/.tf_configure.bazelrc: --copt=-O3 --host_copt=-O3 --copt=-march=native --host_copt=-march=native --copt=-mtune=native --host_copt=-mtune=native --copt=-ffast-math --host_copt=-ffast-math --copt=-funroll-loops --host_copt=-funroll-loops --copt=-fopenmp --host_copt=-fopenmp --copt=-flto --host_copt=-flto --copt=-Wno-sign-compare --host_copt=-Wno-sign-compare
INFO: Found applicable config definition build:cuda in file /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:linux in file /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/.bazelrc: --host_copt=-w --copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated --copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes --copt=-Wno-array-bounds --copt=-Wunused-result --copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch --copt=-Wno-error=unused-but-set-variable --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Repository local_config_cuda instantiated at:
  /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/WORKSPACE:95:14: in <toplevel>
  /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/tensorflow/workspace2.bzl:928:19: in workspace
  /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/tensorflow/workspace2.bzl:106:19: in _tf_toolchains
Repository rule cuda_configure defined at:
  /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/third_party/gpus/cuda_configure.bzl:1542:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/third_party/gpus/cuda_configure.bzl", line 1491, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/third_party/gpus/cuda_configure.bzl", line 1145, column 27, in _create_local_cuda_repository
                cuda_libs = _find_libs(repository_ctx, check_cuda_libs_script, cuda_config)
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/third_party/gpus/cuda_configure.bzl", line 679, column 21, in _find_libs
                _check_cuda_libs(repository_ctx, check_cuda_libs_script, check_cuda_libs_params.values())
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/third_party/gpus/cuda_configure.bzl", line 574, column 28, in _check_cuda_libs
                checked_paths = execute(repository_ctx, [python_bin, "-c", cmd]).stdout.splitlines()
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
sh: line 1: /home/8kesar/Filez/MathematicsProjects: No such file or directory
sh: line 1: Modeling/venv1/bin/python3: No such file or directory
ERROR: /home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/WORKSPACE:95:14: fetching cuda_configure rule //external:local_config_cuda: Traceback (most recent call last):
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/third_party/gpus/cuda_configure.bzl", line 1491, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/third_party/gpus/cuda_configure.bzl", line 1145, column 27, in _create_local_cuda_repository
                cuda_libs = _find_libs(repository_ctx, check_cuda_libs_script, cuda_config)
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/third_party/gpus/cuda_configure.bzl", line 679, column 21, in _find_libs
                _check_cuda_libs(repository_ctx, check_cuda_libs_script, check_cuda_libs_params.values())
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/third_party/gpus/cuda_configure.bzl", line 574, column 28, in _check_cuda_libs
                checked_paths = execute(repository_ctx, [python_bin, "-c", cmd]).stdout.splitlines()
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
sh: line 1: /home/8kesar/Filez/MathematicsProjects: No such file or directory
sh: line 1: Modeling/venv1/bin/python3: No such file or directory
ERROR: @local_config_cuda//:enable_cuda :: Error loading option @local_config_cuda//:enable_cuda: Repository command failed
sh: line 1: /home/8kesar/Filez/MathematicsProjects: No such file or directory
sh: line 1: Modeling/venv1/bin/python3: No such file or directory
Loading: 

## pip
(venv1) ➜  MathematicsProjects&Modeling pip install tf-nightly-gpu
Collecting tf-nightly-gpu
  Downloading tf-nightly-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      Traceback (most recent call last):
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/venv1/lib/python3.12/site-packages/setuptools/_vendor/packaging/requirements.py", line 35, in __init__
          parsed = _parse_requirement(requirement_string)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/venv1/lib/python3.12/site-packages/setuptools/_vendor/packaging/_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/venv1/lib/python3.12/site-packages/setuptools/_vendor/packaging/_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/venv1/lib/python3.12/site-packages/setuptools/_vendor/packaging/_parser.py", line 126, in _parse_requirement_details
          marker = _parse_requirement_marker(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/venv1/lib/python3.12/site-packages/setuptools/_vendor/packaging/_parser.py", line 147, in _parse_requirement_marker
          tokenizer.raise_syntax_error(
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/venv1/lib/python3.12/site-packages/setuptools/_vendor/packaging/_tokenizer.py", line 165, in raise_syntax_error
          raise ParserSyntaxError(
      setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-b9fpugve/tf-nightly-gpu_47887266de004f9f9805cd57c7fcaf13/setup.py", line 40, in <module>
          setuptools.setup()
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/venv1/lib/python3.12/site-packages/setuptools/__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/venv1/lib/python3.12/site-packages/setuptools/__init__.py", line 73, in _install_setup_requires
          dist.parse_config_files(ignore_option_errors=True)
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/venv1/lib/python3.12/site-packages/setuptools/dist.py", line 636, in parse_config_files
          self._finalize_requires()
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/venv1/lib/python3.12/site-packages/setuptools/dist.py", line 370, in _finalize_requires
          self._normalize_requires()
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/venv1/lib/python3.12/site-packages/setuptools/dist.py", line 385, in _normalize_requires
          self.install_requires = list(map(str, _reqs.parse(install_requires)))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/8kesar/Filez/MathematicsProjects&Modeling/venv1/lib/python3.12/site-packages/setuptools/_vendor/packaging/requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      setuptools.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Standalone code to reproduce the issue

```shell
I am on an arch linux system
```

**Comment by sushreebarsa** [comment]
@asp616848 Could you please confirm if you have followed the steps [here](https://www.tensorflow.org/install/source)?
Thank you!

**Comment by asp616848** [comment]
> @asp616848 Could you please confirm if you have followed the steps [here](https://www.tensorflow.org/install/source)?
> Thank you!

Yeah, so after following it I got the first error which was couldn't find Local Config part...

**Comment by sushreebarsa** [comment]
@asp616848 The error you encountered indicates an issue with the syntax of the requirements.txt file or the install_requires parameter in the setup.py file. Specifically, it appears there's an issue with the version specifier for python_version. Please check for any syntax errors in your requirements.txt or setup.py file. Even a small typo can cause issues.

Thank you!

**Comment by asp616848** [comment]
But that's for the pip part which I later figured out that the new version of TensorFlow just doesn't have its -GPU version, and that estimator is deprecated as well. 
But for the bazel, in the install from the source page. I followed each step yet I got the error with local_config mentioned in it.
I think something is wrong with my cuda as I have installed it using pip so it didn't went to the default location.

**Comment by tilakrayal** [comment]
@asp616848,
Could you please provide the complete environment details which you are trying to install. Also try to install the latest tensorflow v2.17 where the GPU issue has been resolved. Thank you!

**Comment by asp616848** [comment]
Package                   Version
------------------------- --------------
absl-py                   2.1.0
anyio                     4.4.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
array_record              0.5.1
arrow                     1.3.0
asttokens                 2.4.1
astunparse                1.6.3
async-lru                 2.0.4
attrs                     24.2.0
babel                     2.16.0
beautifulsoup4            4.12.3
bleach                    6.1.0
certifi                   2024.6.2
cffi                      1.17.0
charset-normalizer        3.3.2
click                     8.1.7
comm                      0.2.2
contourpy                 1.2.1
cuda-python               12.5.0
cycler                    0.12.1
debugpy                   1.8.1
decorator                 5.1.1
defusedxml                0.7.1
dm-tree                   0.1.8
docstring_parser          0.16
etils                     1.9.2
executing                 2.0.1
ez_setup                  0.9
fastjsonschema            2.20.0
flatbuffers               24.3.25
fonttools                 4.53.0
fqdn                      1.5.1
fsspec                    2024.6.1
gast                      0.5.5
google-pasta              0.2.0
googleapis-common-protos  1.63.2
grpcio                    1.64.1
h11                       0.14.0
h5py                      3.11.0
httpcore                  1.0.5
httpx                     0.27.0
idna                      3.7
immutabledict             4.2.0
importlib_resources       6.4.0
ipykernel                 6.29.4
ipython                   8.25.0
ipywidgets                8.1.3
isoduration               20.11.0
jedi                      0.19.1
Jinja2                    3.1.4
joblib                    1.4.2
json5                     0.9.25
jsonpointer               3.0.0
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
jupyter                   1.0.0
jupyter_client            8.6.2
jupyter-console           6.6.3
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-lsp               2.2.5
jupyter_server            2.14.2
jupyter_server_terminals  0.5.3
jupyterlab                4.2.4
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.3
jupyterlab_widgets        3.0.11
keras                     3.4.1
kiwisolver                1.4.5
libclang                  18.1.1
Markdown                  3.6
markdown-it-py            3.0.0
MarkupSafe                2.1.5
matplotlib                3.9.0
matplotlib-inline         0.1.7
mdurl                     0.1.2
mistune                   3.0.2
ml-dtypes                 0.3.2
mpmath                    1.3.0
namex                     0.0.8
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
nest-asyncio              1.6.0
notebook                  7.2.1
notebook_shim             0.2.4
numpy                     1.26.4
opt-einsum                3.3.0
optree                    0.11.0
overrides                 7.7.0
packaging                 24.1
paho-mqtt                 2.1.0
pandas                    2.2.2
pandocfilters             1.5.1
parso                     0.8.4
pexpect                   4.9.0
pillow                    10.3.0
pip                       24.1.2
platformdirs              4.2.2
prometheus_client         0.20.0
promise                   2.3
prompt_toolkit            3.0.47
protobuf                  4.25.3
psutil                    6.0.0
ptyprocess                0.7.0
pure-eval                 0.2.2
pyarrow                   16.1.0
pycparser                 2.22
Pygments                  2.18.0
pyparsing                 3.1.2
PyQt6                     6.7.0
PyQt6-Qt6                 6.7.1
PyQt6-sip                 13.6.0
python-dateutil           2.9.0.post0
python-json-logger        2.0.7
pytz                      2024.1
PyYAML                    6.0.2
pyzmq                     26.0.3
qtconsole                 5.5.2
QtPy                      2.4.1
referencing               0.35.1
requests                  2.32.3
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rich                      13.7.1
rpds-py                   0.20.0
scikit-learn              1.5.0
scipy                     1.13.1
Send2Trash                1.8.3
setuptools                70.1.1
simple_parsing            0.1.5
six                       1.16.0
sniffio                   1.3.1
soupsieve                 2.5
stack-data                0.6.3
sympy                     1.13.1
tensorboard               2.17.0
tensorboard-data-server   0.7.2
tensorflow                2.17.0
tensorflow-datasets       4.9.6
tensorflow-estimator      2.15.0
tensorflow-metadata       1.15.0
tensorrt                  10.1.0
tensorrt-dispatch         10.1.0
tensorrt-lean             10.1.0
termcolor                 2.4.0
terminado                 0.18.1
threadpoolctl             3.5.0
tinycss2                  1.3.0
toml                      0.10.2
tornado                   6.4.1
tqdm                      4.66.4
traitlets                 5.14.3
types-python-dateutil     2.9.0.20240316
typing_extensions         4.12.2
tzdata                    2024.1
uri-template              1.3.0
urllib3                   2.2.2
wcwidth                   0.2.13
webcolors                 24.8.0
webencodings              0.5.1
websocket-client          1.8.0
Werkzeug                  3.0.3
wheel                     0.43.0
widgetsnbextension        4.0.11
wrapt                     1.16.0
zipp                      3.19.2


environment details, yet it doesn't utilize gpu and show some warnings while importing as follows:

2024-08-15 12:14:46.166633: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-08-15 12:14:46.395008: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-15 12:14:46.466695: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-15 12:14:46.494153: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-15 12:14:46.612817: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-15 12:14:47.395056: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

**Comment by tilakrayal** [comment]
@asp616848,
Apologies for the delay. I suspect there was an issue with the tensorflow v2.16, could you please try to upgrade the tensorflow v2.17 and check if you are facing the same issue. Also could you try **bazel clean --expunge** followed by bazel sync.

Thank you!
