### ISSUE TITLE
Is there any GPU implementation of Queues?

### ISSUE THREAD

**Issue by mbz** [tensorflow/tensorflow#7061]
what is the best way of pipelining the training samples in GPU to maximize its utilization?

The natural way of doing this seems to be using Queues, however it seems there is no GPU kernel for any type of Queue.

**Comment by drpngx** [comment]
The queues are always on CPU. The CPU needs to spool, then the heavy duty processing is done on the GPU.

This is more a general question that's probably best answered on stackoverflow. We monitor issues with the tag "tensorflow" there.

**Comment by yaroslavvb** [comment]
@mbz there's tracking issue in https://github.com/tensorflow/tensorflow/issues/5722 . In particular some queue-like ops with GPU support were added recently in https://github.com/tensorflow/tensorflow/commit/85acf52a
