### ISSUE TITLE
Python interpreter set from ./configure does not go with py_strict_test

### ISSUE THREAD

**Issue by junwha0511** [tensorflow/tensorflow#70658]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.16.1

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 22.04

### Python version

3.10

### Bazel version

6.5.0

### GCC/compiler version

15

### Current behavior?

Hi,

I'm trying to run the python tests `bazel test $BAZEL_FLAGS  //tensorflow/python/...` with my pre-built python library.
In ` third_party/py/BUILD.tpl`, it seems like the python tests must be running on the library we set in the ./configure.

However, I observed that tensorflow brings its own python runtime binary from somewhere, and use it for the test.

For example, if I run 
`bazel test $BAZEL_FLAGS  //tensorflow/python/kernel_tests:benchmark_test_cpu`

Following python runtime is used which is not the python binary I specified in the configure.
`bazel-bin/tensorflow/python/kernel_tests/benchmark_test_cpu.runfiles/python_x86_64-unknown-linux-gnu/bin/python`

Could you let me know where was this python interpreter from and how to change it to my python interpeter?

Thank you:)

### Standalone code to reproduce the issue

```shell
`bazel test $BAZEL_FLAGS  //tensorflow/python/kernel_tests:benchmark_test_cpu`
```

**Comment by junwha0511** [comment]
Thank you for the response!

I already set the env variable PYTHON_BIN_PATH with my binary, but bazel automatically hard-codes its own python binary (built by Clang 17, at 2023) for the test in the test file.

Bazel inserted code (PYTHON_BINARY)
![image](https://github.com/tensorflow/tensorflow/assets/17183234/edaf2842-8dca-49a7-bfc3-daf8aa0d7e5c)

`objdump -s -j .comment bazel-bin/tensorflow/python/kernel_tests/benchmark_test_cpu.runfiles/python_x86_64-unknown-linux-gnu/bin/python3`
![image](https://github.com/tensorflow/tensorflow/assets/17183234/836d67d3-330f-4b0d-b925-b3f2a52572c5)

I have no clang-17 on my host and the python3 version is also different.
and the file was created in 2023, thus we can presume it was pulled from an external repo.

**Comment by junwha0511** [comment]
https://github.com/bazelbuild/bazel/blob/master/tools/python/python_bootstrap_template.txt#L73

The python binary is set by `python_bootstrap_template.txt` and the binary seems to be from `bazel-tensorflow/external/python_x86_64-unknown-linux-gnu/bin/`

**Comment by tilakrayal** [comment]
@junwha0511,
Could you please test whether you are facing the same issue with the latest tensorflow v2.17 and also Could you try bazel clean --expunge followed by bazel sync. Thank you!
