### ISSUE TITLE
how to assign tensorflow operation running-time device

### ISSUE THREAD

**Issue by immusferr** [tensorflow/tensorflow#70670]
### Issue type

Documentation Feature Request

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.10.1

### Custom code

Yes

### OS platform and distribution

20.04

### Mobile device

ubantu 20.04

### Python version

3.8

### CUDA/cuDNN version

 CUDA Version: 11.8 

### GPU model and memory

A6000  46G

### Current behavior?

I am trying to optimize the inference time of the TF model, which is a DeepFM model with feature columns. The costs time of singal inference of GPU and CPU device are 30ms and 3ms. The difference between them is mainly because of the H2D and D2H conversions (CPU->GPU and GPU->CPU).
So, what I want to do is force the operation of feature column subgraph runing in CPU, and the operation of neural network subgraph running in GPU.
As far as I know, the running time operation device is dynamic and aligned by tensorflow automatically.
Is there some way I can align the running time device of operations, either in the training part or loading the saved model in inference?
The best way I prefer is to load the saved model and then align the running time device of the OP and save it to the savedmodel to be served by TFS.

### Standalone code to reproduce the issue

```shell
N/A
```

### Relevant log output

```shell
N/A
```

**Comment by tilakrayal** [comment]
@immusferr,
Have you got the chance to have a look at the Custom training loop.

https://www.tensorflow.org/tutorials/customization/custom_layers
https://www.tensorflow.org/guide/keras/writing_a_training_loop_from_scratch

Also If you have control over the training process, the approach below offers the solution. Try to wrap the creation of your feature column processing logic within a **tf.device("/cpu:0")** scope.

```python
def feature_processing(features):
    with tf.device("/cpu:0"):
        processed_features = 
    return processed_features


model = (DeepFM model definition using processed_features)
tf.saved_model.save(model, export_dir="path/to/save")

```

The above try the  feature column operations are explicitly placed on the CPU during training, and this placement is saved within the model definition. Thank you!
