### ISSUE TITLE
Tflite inference with multiple inputs and outputs on Android

### ISSUE THREAD

**Issue by panhu** [tensorflow/tensorflow#70682]

**Comment by sawantkumar** [comment]
Hi @panhu ,
Please take a look at this [link](https://www.tensorflow.org/lite/guide/inference#android_platform) and let me know if this what you are looking for.

**Comment by gaikwadrahul8** [comment]
Hi, @pkgoogle 
Please take look into this issue. Thank you

**Comment by pkgoogle** [comment]
No description, I'm assuming this is spam, if there is a real issue please create a new one with a description. Thanks.
