### ISSUE TITLE
Data augmentation for object detection with bounding boxes

### ISSUE THREAD

**Issue by tirk999** [tensorflow/tensorflow#70687]
Hello everyone,
I need advice for an effective data augmentation for an object detection problem (YOLO neural network) in tensorflow/keras. 
My first option was to use tf keras layers, but not all of them support bounding boxes. For example: keras_cv.layers.JitteredResize() supports bounding boxes but tf.keras.layers.RandomZoom() does not. 
What would be your advice? 
Additionally, I would be interested in the possibility of using ImageDataGenerator, is there a way to include my bounding boxes into the generator? 
Thank you a lot.

**Comment by Venkat6871** [comment]
Hi **@tirk999** ,
- Data augmentation is crucial for improving the performance of object detection models like YOLO. For your use case with TensorFlow/Keras, here i will provide some recommendations and strategies to handle data augmentation while considering bounding boxes:
- Supported Layers: Utilize layers such as keras_cv.layers.JitteredResize() that support bounding boxes.
- ImageDataGenerator in TensorFlow does not directly support bounding boxes. However, you can create a custom generator to include bounding boxes.
Thank you!
