### ISSUE TITLE
error in installing tf from source

### ISSUE THREAD

**Issue by amortazi** [tensorflow/tensorflow#7069]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by amortazi** [comment]
I got following error when I was installing tf from source:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name pywrap_tensorflow


Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error
<

I am installing tf 0.12 in ubuntu 14 with python2.7. 
I appreciate any help.  Thanks

**Comment by drpngx** [comment]
Just to be clear, you built with cuda and built the pip and installed it on your machine?

**Comment by amortazi** [comment]
Yes, I follow instruction for installing from source from https://www.tensorflow.org/get_started/os_setup
I made a wheel and then I install it by pip.
It seems some other guys have same problem here https://github.com/tensorflow/tensorflow/issues/2746. 
I am reading it if i can use their solution. 
Thanks

**Comment by amortazi** [comment]
Unfortunately, it didn't help me. I uninstall six and install it again, but still i have same problem.  Any suggestion? Thanks

**Comment by drpngx** [comment]
It looks like it can't load the pywrap.

Could you run this?

```
/usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so
```

**Comment by amortazi** [comment]
I found the solution! When I am running python inside of tensorflow directory I got that error. But if I run python from any other directory and then import tensorflow, everything is working fine. I am not sure uninstalling and installing six affect it. I am closing this issue.
Thanks.

**Comment by drpngx** [comment]
Oh, ok, you should have seen a message about that.

**Comment by oumayb** [comment]
Hi, 
I think I have a similar problem. 
@amortazi how do you run python from a directory other than tensorflow ? 
Thanks !

**Comment by juxuny** [comment]
@oumayb 
I think I have a similiar problem, too.
But I try to run `cd ~ && python`,  then everything is working well.

**Comment by jandog8990** [comment]
The runnign directory is just a "chance" thing, this is not really a solution for those whose import is having actual problems. Here's mine in OSX El Capitan:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/System/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
ImportError: cannot import name 'pywrap_tensorflow'

**Comment by drpngx** [comment]
It's probably missing some libraries. You could try
```
ldd /System/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/*.so
```
to figure out which it might be.
