### ISSUE TITLE
Tflite(C++) for saving fine tuned models

### ISSUE THREAD

**Issue by Sachi-27** [tensorflow/tensorflow#70726]
I have used the reference [here](https://www.tensorflow.org/lite/examples/on_device_training/overview#build_a_model_for_on-device_training) to enable on-device learning by adding four signatures (infer, train, restore and save) same as given in the reference. I now use C++ TFLite API, which takes as input <tflite_model_path> and <input_data> and performs inference and can also train the model using the tflite::SignatureRunner. I am unable to perform saving and restoring of weights. 

Following is my attempt. I get Error: Memory Allocation failed. 

`tflite::SignatureRunner* save_runner = interpreter->GetSignatureRunner(signature_defs[2]->c_str());`
`if(!save_runner){
  std::cerr << "Cannot obtain save signature" << std::endl; 
}`

`TFLITE_MINIMAL_CHECK(save_runner->AllocateTensors() == kTfLiteOk);`
`TfLiteTensor* input_tensor_ = save_runner->input_tensor("checkpoint_path");`
`TFLITE_MINIMAL_CHECK(input_tensor_ != nullptr);`
`std::string* input_ = tflite::GetTensorData<std::string>(input_tensor_);`
`if(input_){
  *input_ = "model.ckpt";
}`
`else{
  std::cerr << "Error: Memory allocation failed" << std::endl; exit(1);
}`

`TFLITE_MINIMAL_CHECK(save_runner->Invoke() == kTfLiteOk);`
`TfLiteTensor* output_tensor_ = save_runner->input_tensor("checkpoint_path");`
`std::string* output = tflite::GetTensorData<std::string>(output_tensor_);`
`std::cout << "OUTPUT checkpoint path: "<< *output << std::endl;`

`interpreter.reset();`
`return 0;`

Why is the input_ variable not allocated any memory. Following is the function signature corresponding to "save".
`@tf.function(input_signature=[tf.TensorSpec(shape=[], dtype=tf.string)])`
`  def save(self, checkpoint_path):`
`    tensor_names = [weight.name for weight in self.model.weights]`
`    tensors_to_save = [weight.read_value() for weight in self.model.weights]`
`    tf.raw_ops.Save(`
`        filename=checkpoint_path, tensor_names=tensor_names,`
`        data=tensors_to_save, name='save')`
`    return {`
`        "checkpoint_path": checkpoint_path`
`    }`

**Comment by tilakrayal** [comment]
@Sachi-27,
Could you please provide the complete code to reproduce and the tensorflow version you are trying  which helps to debug the issue. Thank you~

**Comment by Sachi-27** [comment]
tensorflow version : 2.9.1
I have used the same python code as in the [reference](https://www.tensorflow.org/lite/examples/on_device_training/overview#build_a_model_for_on-device_training) to convert the .h5 model into .tflite which now contains the 4 signatures.
I have made the following modifications to the tensorflow/lite/examples/minimal/minimal.cc code

#include <cstdio>
#include <iostream>
#include <fstream>
#include <sys/time.h>
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/optional_debug_tools.h"
#include "tensorflow/lite/signature_runner.h"
#include "tensorflow/lite/kernels/internal/tensor_ctypes.h"

#define TFLITE_MINIMAL_CHECK(x)                              \
  if (!(x)) {                                                \
    fprintf(stderr, "Error at %s:%d\n", __FILE__, __LINE__); \
    exit(1);                                                 \
  }

**Comment by Sachi-27** [comment]
Tensorflow version : 2.9.1
I have used the same code as in [here](https://www.tensorflow.org/lite/examples/on_device_training/overview#build_a_model_for_on-device_training) to convert the .h5 model to .tflite with signatures.

I have made changes to the tensorflow/tlite/examples/minimal/minimal.cc code.
```
#include <cstdio>
#include <iostream>
#include <fstream>
#include <sys/time.h>
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/optional_debug_tools.h"
#include "tensorflow/lite/signature_runner.h"
#include "tensorflow/lite/kernels/internal/tensor_ctypes.h"

#define TFLITE_MINIMAL_CHECK(x)                              \
  if (!(x)) {                                                \
    fprintf(stderr, "Error at %s:%d\n", __FILE__, __LINE__); \
    exit(1);                                                 \
  }
int main(int argc, char* argv[]) {
  if (argc != 2) {
    fprintf(stderr, "minimal <tflite model>\n");
     return 1;
  }

  const char* filename = argv[1];

  // Load model
  std::unique_ptr<tflite::FlatBufferModel> model =
      tflite::FlatBufferModel::BuildFromFile(filename);
  TFLITE_MINIMAL_CHECK(model != nullptr);

  // Build the interpreter with the InterpreterBuilder.
  // Note: all Interpreters should be built with the InterpreterBuilder,
  // which allocates memory for the Interpreter and does various set up
  // tasks so that the Interpreter can read the provided model.
  tflite::ops::builtin::BuiltinOpResolver resolver;
  tflite::InterpreterBuilder builder(*model, resolver);
  std::unique_ptr<tflite::Interpreter> interpreter;
  builder(&interpreter);
  TFLITE_MINIMAL_CHECK(interpreter != nullptr);
  
int batch_sz = 10;
  std::vector<const std::string*> signature_defs = interpreter->signature_keys();
 tflite::SignatureRunner* save_runner = interpreter->GetSignatureRunner(signature_defs[2]->c_str());
  if(!save_runner){
    std::cerr << "Cannot obtain save signature" << std::endl; 
  }
const std::vector<const char*>& input_names_ = save_runner->input_names();
  const std::vector<const char*>& output_names_ = save_runner->output_names();
  std::cout << "input_names.size() = " << input_names_.size() << std::endl;
  std::cout << input_names_[0] << std::endl;
  std::cout << "output_names.size() = " << output_names_.size() << std::endl;
  std::cout << output_names_[0] << std::endl;

  TFLITE_MINIMAL_CHECK(save_runner->AllocateTensors() == kTfLiteOk);
  TfLiteTensor* input_tensor_ = save_runner->input_tensor("checkpoint_path");
  TFLITE_MINIMAL_CHECK(input_tensor_ != nullptr);
  std::string* input_ = tflite::GetTensorData<std::string>(input_tensor_);
  std::cout << "About to set input_ value" << std::endl;
  std::cout << "TFLITE TYPE: " << input_tensor_->type << std::endl;
    *input_ = "model.ckpt";
  
  std::cout << "Setting input_ to: " << input_tensor->data.raw << std::endl;

  TFLITE_MINIMAL_CHECK(save_runner->Invoke() == kTfLiteOk);
  std::cout << "Invoked" << std::endl;
  const TfLiteTensor* output_tensor_ = save_runner->output_tensor("checkpoint_path");
  std::cout << "Obtained output_tensor_" << std::endl;
  std::cout << "OUTPUT checkpoint path: "<< output_tensor->data.raw << std::endl;

  interpreter.reset();
  return 0;
}
```



COMMAND TO RUN:
`./minimal demo.tflite`

OUTPUT:
1
checkpoint_path
1
checkpoint_path
About to set input_ value
TFLITE TYPE: 5
Segmentation Fault

**Comment by sawantkumar** [comment]
Hi @pkgoogle ,

I also got the same error, can you please look into it 

```
root@tflite-issue-replication:/home/sawantkumar/work/c_plus/tensorflow/bazel-bin/tensorflow/lite/examples/minimal# ./minimal /home/sawantkumar/work/c_plus/tensorflow/tensorflow/lite/examples/minimal/demo1.tflite
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
input_names.size() = 1
checkpoint_path
output_names.size() = 1
checkpoint_path
About to set input_ value
TFLITE TYPE: 5
Segmentation fault (core dumped)
```

**Comment by pkgoogle** [comment]
Hi @Sachi-27, do you absolutely need to do on device training? -- if not I can recommend other methods which may work better.

**Comment by Sachi-27** [comment]
Yes @pkgoogle. I am working on developing on-device real-time training.

**Comment by pkgoogle** [comment]
So that tutorial is very old, I think we should at the very least update everything to work with the latest version. Here's a [gist](https://colab.sandbox.google.com/drive/1N7Bak6AWvZftAoXshpIzKFLJjhA2DoA_) showing how far I got on nightly. @haozha111 can you please take a look? Thanks.

**Comment by Sachi-27** [comment]
@pkgoogle It seems you haven't given the access rights. Can you change the share permissions? Thankyou

**Comment by pkgoogle** [comment]
> @pkgoogle It seems you haven't given the access rights. Can you change the share permissions? Thankyou

Ahh wrong link, it should be updated now.

**Comment by haozha111** [comment]
@Sachi-27 i think the way you set string tensor for the tflite save signature is a bit problematic. TF Lite's string tensor has a different encoding format with the std::string, so we can't just copy the `std:string` into TF Lite. Can you try something like:

`def run_save():
    save_signature = interpreter.get_signature_runner('save')
    ckpt = '/tmp/model.ckpt'
    output = save_signature(checkpoint_path=np.array(ckpt, dtype=np.string_))
`

**Comment by gaikwadrahul8** [comment]
Hi, @Sachi-27 

Could you please try above [workaround](https://github.com/tensorflow/tensorflow/issues/70726#issuecomment-2277297493) and see is it resolving your issue or not ? Thank you
