### ISSUE TITLE
Issue with Loading Sequential Models

### ISSUE THREAD

**Issue by RaulCastillo547** [tensorflow/tensorflow#70757]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.16.2

### Custom code

Yes

### OS platform and distribution

Windows 10 Home

### Python version

3.12.0

### Current behavior?

I am trying to train a Sequential model based off the Single Shot CNN model found in the Tensorflow [time series forecasting tutorial](https://www.tensorflow.org/tutorials/structured_data/time_series).

The compiling, testing, predicting, and saving operations all work fine; however, loading the model gives me this error - `ValueError: Sequential model 'sequential' has already been configured to use input shape (None, 10, 4). You cannot build it with input_shape [None, 10, 4]`.

This happens with version 2.16.2, but if I were to use version 2.15.0 from a Google Colab notebook, I would get no errors. This difference between versions and the oddity between two identical shapes not equaling causes me to believe that this is a bug.

I also [posted on the Tensorflow Forums](https://discuss.tensorflow.org/t/issue-with-identical-input-shapes-not-equalling/25585) about this issue, and another user replied that they too have similar issues.

### Standalone code to reproduce the issue

This is a link to a Colab notebook that reproduces the error:
https://colab.research.google.com/drive/1ivDScvFR9oJOKVg31oIc0BbGux7WGEEM?usp=sharing

This is a link to the csv file that I used (place it in the content folder):
https://drive.google.com/file/d/1gpG0SN6ayCnemssI9XdnLB5VOxfV-xzc/view?usp=sharing

### Relevant log output

```shell
/usr/local/lib/python3.10/dist-packages/keras/src/models/sequential.py in build(self, input_shape)
    164         if isinstance(self._layers[0], InputLayer):
    165             if self._layers[0].batch_shape != input_shape:
--> 166                 raise ValueError(
    167                     f"Sequential model '{self.name}' has already been "
    168                     "configured to use input shape "

ValueError: Sequential model 'sequential' has already been configured to use input shape (None, 10, 4). You cannot build it with input_shape [None, 10, 4]
```

**Comment by GarmischWg** [comment]
Experiencing the same issue in tensorflow 2.16.1.

**Comment by sushreebarsa** [comment]
@tilakrayal I was able to replicate the issue in TF[v2.16](https://colab.research.google.com/gist/sushreebarsa/0c319b7455efb0deb9f2e79d99dd18f7/notebook-for-error.ipynb#scrollTo=DdP3-O33ypGO) and tf-[nightly](https://colab.research.google.com/gist/sushreebarsa/35d0ea64c077c3fa55a6976eea53279a/notebook-for-error.ipynb#scrollTo=r84tJyfxykjb) but it is not reproducible in TF [2.15](https://colab.research.google.com/gist/sushreebarsa/e38f5797c21a185db2ac276d7994bef3/notebook-for-error.ipynb#scrollTo=kPo0jdaRx_D0).
Thank you!

**Comment by tilakrayal** [comment]
@RaulCastillo547,
I tried to execute the mentioned using **!pip install tf-keras==2.17.0rc0**, and executed the official time series forecasting document and it was executed without fail. By default Tensorflow v2.16 contains the keras3.0 version which might be the reason for the issue/error/fail. Kindly find the gist of it [here](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/structured_data/time_series.ipynb).

Thank you!

**Comment by RaulCastillo547** [comment]
@tilakrayal,
I tried using !pip install tf-keras==2.17.0rc0 and tried to save and load the CNN multi-step model on both the official time series forecasting document and my google collab notebook. However, the same error pops up when I load the model.

**Comment by tilakrayal** [comment]
@RaulCastillo547,
Thank you for reporting the issue. I was able to reproduce the issue on TensorFlow 2.15, keras2.0 and tf-nightly keras3.0 as well. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/e1188571488b381ebce4ab6708593739/notebook_for_error.ipynb).

As this issue is more related to keras, could you please try to raise the issue in the keras-team/keras [repo](https://github.com/keras-team/keras/issues) for the quick resolution. Thank you!

**Comment by xchen99sdr** [comment]
Hello, reporting the same issue with pip version 2.17. Thanks

**Comment by tilakrayal** [comment]
Could you please feel free to move this issue to closed status, since it is already being tracked in the Keras repo? Thank you!

**Comment by IHATEWRITINGCODE** [comment]
In my case, the issue was caused by my use of the `tf.keras.layers.Lambda` class within the `tf.keras.Sequential` model. The lambda function I was using was `lambda x: tf.reshape(x, [...])` which I suppose changed the tuple shape representation to a list representation. I believe this comparison subsequently failed downstream when loading the model. My solution was the use the `tf.keras.layers.Reshape` class instead of the Lambda class as you're supposed to. P.S. This might not be the exact reason the tutorial code is failing.
