### ISSUE TITLE
cannot import name 'mean_absolute_error' from 'tensorflow.keras.losses'

### ISSUE THREAD

**Issue by dwang6524** [tensorflow/tensorflow#70796]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

v2.16.1-19-g810f233968c 2.16.2

### Custom code

No

### OS platform and distribution

macOS Sonoma 14.5

### Python version

Python 3.10.11

### Current behavior?

When i import neurite or voxelmorph it spits out

ImportError: cannot import name 'mean_absolute_error' from 'tensorflow.keras.losses' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/_tf_keras/keras/losses/__init__.py)

I see someone had a similar issue here but the answers did not help me: https://github.com/tensorflow/tensorflow/issues/69851

### Standalone code to reproduce the issue

```shell
import voxelmorph as vxm
```

### Relevant log output

```shell
----> 6 import voxelmorph as vxm
      7 import neurite as ne

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/voxelmorph/__init__.py:12
      9 from packaging import version
     11 # ensure valid neurite version is available
---> 12 import neurite
     13 minv = '0.2'
     14 curv = getattr(neurite, '__version__', None)

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/neurite/__init__.py:50
     47 except ImportError:
     48     raise ImportError('Please install tensorflow to use this neurite backend')
---> 50 from . import tf
     51 from .tf import *

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/neurite/tf/__init__.py:5
      3 from . import generators
      4 from . import callbacks
----> 5 from . import metrics
      6 from . import losses
      7 from . import models

File /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/neurite/tf/metrics.py:33
     31 from tensorflow.keras import losses
     32 # simple metrics renamed mae -> l1, mse -> l2
---> 33 from tensorflow.keras.losses import mean_absolute_error as l1
     34 from tensorflow.keras.losses import mean_squared_error as l2
     36 # local

ImportError: cannot import name 'mean_absolute_error' from 'tensorflow.keras.losses' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/_tf_keras/keras/losses/__init__.py)
```

**Comment by tilakrayal** [comment]
@dwang6524,
AFAIK the issue is tensorflow v2.16 contains keras3.0 which might be the reason for the issue/error. As a workaround could you please try to below code before executing the import statement.

```python
!pip install tf-keras
import os
os.environ['TF_USE_LEGACY_KERAS'] = '1'
```

Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/efa6769300cb9365313856205da78e7f/untitled1990.ipynb)https://colab.research.google.com/gist/tilakrayal/efa6769300cb9365313856205da78e7f/untitled1990.ipynb

Thank you!

**Comment by just-sabyr** [comment]
This issue can be solved by changing two files (both files need to be changed): site-packages/neurite/tf/metrics.py (lines 33 and 34) and site-packages/neurite/tf/losses.py (lines 32 and 33).

Change from these: 
from tensorflow.keras.losses import mean_absolute_error as l1
from tensorflow.keras.losses import mean_squared_error as l2

To these: 
from tensorflow.keras.losses import MAE as l1
from tensorflow.keras.losses import MSE as l2
