### ISSUE TITLE
movenet = Movenet('movenet_thunder') not working

### ISSUE THREAD

**Issue by durgas4** [tensorflow/tensorflow#70841]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15.0

### Custom code

Yes

### OS platform and distribution

google ocllab

### Current behavior?

When am trying to use the Movnet model, it is showing some error - 
movenet = Movenet('movenet_thunder')

### Standalone code to reproduce the issue

```shell
Used movnet for pose estimation , but the model is failing -
# Load MoveNet Thunder model
import utils
from data import BodyPart
from ml import Movenet
movenet = Movenet('movenet_thunder')
```

### Relevant log output

```shell
ValueError                                Traceback (most recent call last)
<ipython-input-16-85ae69c878c7> in <cell line: 11>()
      9 from data import BodyPart
     10 from ml import Movenet
---> 11 movenet = Movenet('movenet_thunder')
     12 
     13 # Define function to run pose estimation using MoveNet Thunder.

1 frames
/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/interpreter.py in __init__(self, model_path, model_content, experimental_delegates, num_threads, experimental_op_resolver_type, experimental_preserve_all_tensors, experimental_disable_delegate_clustering)
    462           x for x in self._custom_op_registerers if not isinstance(x, str)
    463       ]
--> 464       self._interpreter = _interpreter_wrapper.CreateWrapperFromFile(
    465           model_path,
    466           op_resolver_id,

ValueError: Mmap of '41' at offset '0' failed with error '22'.
```

**Comment by tilakrayal** [comment]
@durgas4,
Could you please provide the complete code or the colab gist to reproduce the issue which helps to debug the issue in an effective way. Thank you!

**Comment by durgas4** [comment]
The code is here-
https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/hub/tutorials/movenet.ipynb#scrollTo=SYFdK-JHYhrv

This part-
Load Model from TF hub

**Comment by sawantkumar** [comment]
Hi @durgas4 ,

I ran the notebook from this same link but it worked fine. Can you please retry and let me know if it works?

**Comment by durgas4** [comment]
Working fine, thanks!  i forgot the following code line -
# Download model from TF Hub and check out inference code from GitHub
!wget -q -O movenet_thunder.tflite https://tfhub.dev/google/lite-model/movenet/singlepose/thunder/tflite/float16/4?lite-format=tflite
!git clone https://github.com/tensorflow/examples.git
pose_sample_rpi_path = os.path.join(os.getcwd(), 'examples/lite/examples/pose_estimation/raspberry_pi')
sys.path.append(pose_sample_rpi_path)

And directly went to this :)
# Load MoveNet Thunder model
import utils
from data import BodyPart
from ml import Movenet
movenet = Movenet('movenet_thunder')
