### ISSUE TITLE
Cannot build the TensorFlow Lite installation package (C++)

### ISSUE THREAD

**Issue by WojciechRynczuk** [tensorflow/tensorflow#70851]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

v2.16.2

### Custom code

No

### OS platform and distribution

Linux

### Mobile device

Ubuntu 22.04

### Python version

3.10.12

### Bazel version

6.5.0

### GCC/compiler version

11.4.0

### Current behavior?

I'd like to build the installable package of TensorFlow so as to be able to build standalone C++ applications using TensorFlow. They would be built using cmake. I followed the instructions provided [here](https://www.tensorflow.org/lite/guide/build_cmake#build_installable_package). Cmake fails.

Please notice that building the TensorFlow lib itself (not installable) succeeds. The issue only is applicable to the installable package.

I would expect the cmake to complete so as I would be able to execute 'cmake --install .' and install the TensorFlow library along with all necessary packages. If I am wrong here with my assumptions please advise me on installing the Tensorflow C++ runtime to be able to build standalone cmake based applications (x86 and ARM targets).

### Standalone code to reproduce the issue

```shell
cmake ../tensorflow/tensorflow/lite -DTFLITE_ENABLE_INSTALL=ON \
  -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON \
  -DSYSTEM_FARMHASH=ON \
  -DSYSTEM_PTHREADPOOL=ON \
  -Dabsl_DIR=/usr/lib/cmake/absl \
  -DEigen3_DIR=/usr/share/eigen3/cmake \
  -DFlatBuffers_DIR=/usr/lib/cmake/flatbuffers \
  -Dgemmlowp_DIR=/usr/lib/cmake/gemmlowp \
  -DNEON_2_SSE_DIR=/usr/lib/cmake/NEON_2_SSE \
  -Dcpuinfo_DIR=/usr/share/cpuinfo \
  -Druy_DIR=/usr/lib/cmake/ruy
```

### Relevant log output

```shell
-- Configuring done (125.8s)
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "absl_flags" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "absl_hash" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "absl_status" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "absl_strings" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "absl_synchronization" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "absl_variant" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "ruy" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "pthreadpool" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "xnnpack-delegate" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "XNNPACK" that is not in any export set.
CMake Error at /usr/local/lib/cmake/gemmlowp/gemmlowp-config.cmake:69 (set_target_properties):
  The link interface of target "gemmlowp::eight_bit_int_gemm" contains:

    Threads::Threads

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  CMakeLists.txt:171 (find_package)


-- Generating done (1.1s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by pkgoogle** [comment]
Hi @WojciechRynczuk those instructions are supposed to be used with find_package in another cmake project. So after building, your project which integrates TFLite should include the `find_package(tensorflow-lite CONFIG)` line in your project's CMakeLists.txt file. I do not believe these instructions are meant to be used with `cmake --install`. Your CMakeLists.txt file will probably need more to work properly, but that is likely project dependent. Does that answer your question? Thanks.
