### ISSUE TITLE
Error Running TFLite Models on ESP32C3: Failed to get registration from op code CUSTOM, AllocateTensors() failed

### ISSUE THREAD

**Issue by AdityaB-01** [tensorflow/tensorflow#70868]
I am encountering an error when running two TensorFlow Lite models on my ESP32C3. Below are the details of the error, the models, and the conversion code used.

**Arduino code:** https://drive.google.com/file/d/15as7adLykxOzsaAxV6l9UTe_EHS_WqXw/view?usp=sharing

**Tflite models**

![state_model tflite](https://github.com/tensorflow/tensorflow/assets/73652707/3ec950fc-a334-47e7-a243-cf5b811fc9f7)

![temp_model tflite](https://github.com/tensorflow/tensorflow/assets/73652707/0d35e4fb-c31a-49eb-80f7-dec7e31a260d)

**Error Message**

```
Failed to get registration from op code CUSTOM
AllocateTensors() failed
```

**Models**

1. **State Model**
    ```python
    def create_state_model(input_dim):
        model = Sequential()
        model.add(Reshape((input_dim, 1), input_shape=(input_dim,)))
        model.add(LSTM(64, return_sequences=False))
        model.add(Dropout(0.3))
        model.add(Dense(32, activation='relu'))
        model.add(Dropout(0.3))
        model.add(Dense(1, activation='sigmoid'))
        model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
        return model
    ```

2. **Temperature Model**
    ```python
    def create_temp_model(input_dim, output_dim):
        model = Sequential()
        model.add(Reshape((input_dim, 1), input_shape=(input_dim,)))
        model.add(LSTM(64, return_sequences=False))
        model.add(Dropout(0.3))
        model.add(Dense(32, activation='relu'))
        model.add(Dropout(0.3))
        model.add(Dense(output_dim, activation='softmax'))
        model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
        return model
    ```
    
**Conversion Code**

```python
# State Model Conversion
converter = tf.lite.TFLiteConverter.from_keras_model(state_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS  # enable TensorFlow ops.
]
state_model_tflite = converter.convert()
with open('state_model.tflite', 'wb') as f:
    f.write(state_model_tflite)

# Temperature Model Conversion
converter = tf.lite.TFLiteConverter.from_keras_model(temp_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [
    tf.lite.OpsSet.TFLITE_BUILTINS,  # enable TensorFlow Lite ops.
    tf.lite.OpsSet.SELECT_TF_OPS  # enable TensorFlow ops.
]
temp_model_tflite = converter.convert()
with open('temp_model.tflite', 'wb') as f:
    f.write(temp_model_tflite)
```

**Comment by sushreebarsa** [comment]
@AdityaB-01 The ESP32C3 requires the TFLite Micro interpreter, which is optimized for microcontrollers. Ensure that you have the correct version of the TFLite library. Could you please provide the TF version you are using?
Thank you!

**Comment by AdityaB-01** [comment]
Hello, thank you for your response. I am using Arduino IDE to upload the code and It has a library in its library manager. The Git link for the same is https://github.com/spaziochirale/Chirale_TensorFlowLite.git, 

Also to add, I removed the LSTM layer and used simple Dense layers to train the model and Python, that model is running correctly on esp. But again this is a work around and the actual accurate model is not able to run on that.

**Comment by pkgoogle** [comment]
Hi @AdityaB-01, I believe you will have more luck posting this issue to: https://github.com/tensorflow/tflite-micro. They are more knowledgeable on Arduino and Arduino code.
