### ISSUE TITLE
Add round to nearest

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#709]
We have `tf.floor` and `tf.ceil`, but we don't have round to nearest.  I am conflicted on whether it should be called `rint` or `round`.  It would also be annoying if it depended on the processor flags.

**Comment by letalvoj** [comment]
I like that the ```tf``` interface is fairly ```numpy```-like. It would be nice to keep it that way. Thus in my opinion I would use ```tf.rint``` as it is [in numpy] (http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.rint.html). ;)

**Comment by girving** [comment]
Sounds reasonable to me.

**Comment by martinwicke** [comment]
I believe this is fixed -- `tf.round` seems to work. It's different from the patch I had prepared, and I think different from @chemelnucfin's PR, but somehow someone wrote it.
