### ISSUE TITLE
install tensorflow 1.12.0 (python 3.5)

### ISSUE THREAD

**Issue by yayale1** [tensorflow/tensorflow#70901]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

1.12.0

### Custom code

No

### OS platform and distribution

Mac

### Python version

python 3.5.10

### Current behavior?

install tf 1.12 under python 3.5

### Standalone code to reproduce the issue

```shell
pip install tensorflow-1.12.0
```

### Relevant log output

```shell
python --version
Python 3.5.10

pip install tensorflow-1.12.0

Collecting tensorflow-1.12.0
  Could not fetch URL https://pypi.python.org/simple/tensorflow-1-12-0/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:728) - skipping
  Could not find a version that satisfies the requirement tensorflow-1.12.0 (from versions: )
No matching distribution found for tensorflow-1.12.0
```

**Comment by sushreebarsa** [comment]
@yayale1 Older version of TF(1.x) is not actively supported so please upgrade to the latest TF version. Please refer to this tested build [configuration](https://www.tensorflow.org/install/source#macos) and let us know?
Thank you!

**Comment by yayale1** [comment]
> @yayale1 Older version of TF(1.x) is not actively supported so please upgrade to the latest TF version. Please refer to this tested build [configuration](https://www.tensorflow.org/install/source#macos) and let us know? Thank you!
got it! thanks for your help!

**Comment by sushreebarsa** [comment]
@yayale1 Could you please let us know if there is any update on this issue after upgrading?
Thank you!
