### ISSUE TITLE
problems with Model saving and program slow to run

### ISSUE THREAD

**Issue by michael4john** [tensorflow/tensorflow#7093]
[github_text_classification.zip](https://github.com/tensorflow/tensorflow/files/732694/github_text_classification.zip)
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
I tried to run the text_classification.py provided as one of the examples. But I basically ran into 2 problems:

1: The program took hours to finish (which just took minutes with version r0.8/0.9) and issued lots of warnings. Please run `text_classification.py` and the corresponding output is attached as `output.PNG`. 
2: Problems with saving models by using classifier = learn.DNNClassifier(..., model_dir). Please run `text_classification_with_model_saving.py` and the corresponding output is attached as `output_with_model_saving.PNG`. 

### Environment info (Operating System):
Running the command `lsb_release -a` gives the following:
Distributor ID: Ubuntu
Description: Ubuntu 16.04.1 LTS
Release: 16.04
Codename: xenial

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
1. https://github.com/tensorflow/tensorflow/issues/6119
The person tried to solve a different problem. But the warnings he got were almost the same as I got. He seemed to fix his problem by updating the tensorflow to version r0.12.1, which is the one I'm using now.
2. http://stackoverflow.com/questions/40905736/rnn-lstm-time-series-tensorflow-0-12-error
The person also got almost the same warnings and errors. He got rid of all those by reverting back to version r0.10.0. But this is the last resort I would want.

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
ls: cannot access '/path/to/cuda/lib/libcud*': No such file or directory

If installed from binary pip package, provide:
1. A link to the pip package you installed:
Running the command line `pip show tensorflow` gives the following:
Name: tensorflow
Version: 0.12.1
Location: /usr/local/lib/python2.7/dist-packages
Requires: mock, numpy, protobuf, wheel, six

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.12.1
python version: 2.7.12
numpy version: 1.11.3

### What other attempted solutions have you tried?
I manipulated parameters for learn.DNNClassifier for a little bit, but still got the error.

### Logs or other output that would be helpful
1: See the attachment `output.PNG` for running `text_classification.py`
2: See the attachement `output_with_model_saving.PNG` for running `text_classification_with_model_saving.py`

### Other Notes
The original script appears to download corrupted dbpedia files. For convenience, I used my train and test csv files, and added my code for importing data files from Line 86 to Line 89. The two csv files are also attached. When running the scripts, please place the two data files in the same directory as the two scripts.

I ran both scripts in the CLI, e.g., python text_classification.py

**Comment by drpngx** [comment]
@ispirmustafa @ilblackdragon this looks like a tf.learn issue. Feel free to bounce to stackoverflow if appropriate.

**Comment by michael4john** [comment]
Actually, text_classification.py can successfully be run, despite of all the warnings. However, I do want to know how to save models in that particular case. I searched Internet, but few were found. Below is what I'm using:

`classifier = learn.DNNClassifier(hidden_units=[10,20,10], n_classes=2, model_dir="savedModel")`

It's in the Line 106 in the script `text_classification_with_model_saving.py`, which raises an error when run.

**Comment by michael4john** [comment]
By looking at the tutorial: https://www.tensorflow.org/tutorials/tflearn/#tf-contrib-learn-quickstart, I was able to make the script working by adding feature_column in Line 106. The script that works is attached.
[text_classification_with_model_saving.zip](https://github.com/tensorflow/tensorflow/files/736259/text_classification_with_model_saving.zip)


One more question, is there any way to report individual probability for each class? I remember classifier.predict_proba() can be used in earlier versions like r0.8/0.9.

**Comment by boscotsang** [comment]
@michael4john 
Try predict_proba with argument as_iterable=False to get a list of predictions instead of generator.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
