### ISSUE TITLE
2.16.2 doesn't see my gpu

### ISSUE THREAD

**Issue by Yulee3542** [tensorflow/tensorflow#70958]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.16.2

### Custom code

Yes

### OS platform and distribution

Windows 11

### Python version

3.12.4

### GCC/compiler version

VSC 1.91.0 (user setup)

### CUDA/cuDNN version

12.5/9.2

### GPU model and memory

RTX 3050 Laptop GPU

### Current behavior?

i followed the steps to install CUDA and cuDNN but tensorflow won't see my gpu
nvidia-smi
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 556.12                 Driver Version: 556.12         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id               Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf        Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                                            |                                     |                      MIG M. |
|========================+==============+==============|
|   0  NVIDIA GeForce RTX 3050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   56C    P0                         7W /   30W |         0MiB /   4096MiB |      0%      Default |
|                                                                    |                                      |                    N/A |
+-----------------------------------------+------------------------+----------------------+

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

# Print TensorFlow version
print("TensorFlow version:", tf.__version__)

# Check for GPU
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    print("GPUs are available")
    for gpu in gpus:
        print(gpu)
else:
    print("No GPUs found")

output:
TensorFlow version: 2.16.2
No GPUs found
```

**Comment by mihaimaruseac** [comment]
Please see #63362
