### ISSUE TITLE
[installation issues] unable to pip install tensorflow in windows : wheel not supported in this platform

### ISSUE THREAD

**Issue by imvetri** [tensorflow/tensorflow#7096]
The following information are for installation issues

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem? 
https://stackoverflow.com/questions/41605355/updating-the-supported-tags-for-pip#

### Environment info
Operating System: windows

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`): Could not install tensorflow from pip, so could not reach this phase.

![wheel not supported in windows plattform](https://cloud.githubusercontent.com/assets/6542274/22343817/91ae2194-e41f-11e6-8b7b-bf4fad6e7c9a.jpg)

installed from binary pip package, provide:

1. link to the pip package you installed: using version pip 9.0.1

### What other attempted solutions have you tried? 

Haven't tried making tensorflow from source since I am on windows 7. I will be trying using cmake if that doesnt workout well I will be proceeding with linux environment in my PC by reinstalling the OS itself. :(

### Logs or other output that would be helpful

Attached screenshot

**Comment by mrry** [comment]
PIP packages for TensorFlow on Windows are only available for Python 3.5 at present. Your easiest option might be to install Python 3.5, but it should be possible to make a custom build for Python 3.6 with CMake.

We're aware that this is not ideal, and already tracking the problem in #6999, so I'm going to close this as a duplicate for now.

**Comment by pmunin** [comment]
Just found Tensorflow 1.1 working on python 3.6: http://www.lfd.uci.edu/~gohlke/pythonlibs/#tensorflow. Unofficial apparently, but working.
They have scipy windows package there too.
