### ISSUE TITLE
Feature request: CI for Windows build and test

### ISSUE THREAD

**Issue by hholst80** [tensorflow/tensorflow#7100]
https://www.appveyor.com/

Free build and test in cloud for Windows. I think this should be implemented for TensorFlow to make sure the windows builds are as well tested as the Linux builds.

Motivation: https://github.com/tensorflow/tensorflow/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20windows

**Comment by drpngx** [comment]
@gunan interesting idea.

**Comment by gunan** [comment]
We do have windows continuous tests setup and running on our own test infrastructure.
http://ci.tensorflow.org/job/tf-master-win-gpu-cmake/
http://ci.tensorflow.org/job/tf-master-win-bzl/
http://ci.tensorflow.org/job/tensorflow-master-win-cmake-py/

We might be lacking firsthand windows development machines for quickly debugging these. but the test infra is there.
Closing the issue.
