### ISSUE TITLE
Feature request: Audio thumbnails/summaries in the embedding visualization

### ISSUE THREAD

**Issue by act65** [tensorflow/tensorflow#7106]
We (@pfcm and I) have been working with audio data (bird songs) and would like a way to inspect (via listening) embeddings of small chunks of audio files. The main use would be to help us to validate and explore our data. In our setting we have few labels, so we are especially interested in using it to inspect clusters and validate (with humans) their accuracy/reliability/clusteryness. 

We would like to know;
* Are you guys planning on adding this sort of feature to tensorflow? If so, can we help to speed it up? 
* If we were do it how would you recommend that we implement it so that it is supported in the future?

**Comment by drpngx** [comment]
I'm not sure I totally understand, but let me know if this is related.

@dandelionmane has built tensorboard with audio summaries, where I think we can see spectrograms. Maybe extending this to allow listening to segments of that in some sense?

**Comment by act65** [comment]
We would like audio summaries to work with the [embedding visualiser](https://www.tensorflow.org/how_tos/embedding_viz/). Much like there are thumbnails of each mnist image (see link), we would like to be able to click on an embedded datapoint; to listen to it (currently we are just using the spectrograms as image thumbnails) and to figure out where it came from (which part of which audio recording).

**Comment by dandelionmane** [comment]
Migrated this to TensorBoard repo. https://github.com/tensorflow/tensorboard/issues/38
