### ISSUE TITLE
error training LSTM image captioning model using dynamic_rnn

### ISSUE THREAD

**Issue by mutasem-mattar** [tensorflow/tensorflow#7109]
Hello, 
I am trying to use tf.nn.dynamic_rnn to train an image captioning model. However, I keep getting this error. 

    ValueError: Variable lstm//BasicLSTMCell/Linear/Matrix does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?

I am using Tensorflow version 0.12.1

Here is the code snippet:

     lstm_cell = tf.nn.rnn_cell.BasicLSTMCell(num_units=self.config.num_lstm_units, state_is_tuple=True)
     if self.mode == "train":
     lstm_cell = tf.nn.rnn_cell.DropoutWrapper(
        lstm_cell,
        input_keep_prob=self.config.lstm_dropout_keep_prob,
        output_keep_prob=self.config.lstm_dropout_keep_prob)

    with tf.variable_scope("lstm", initializer=self.initializer) as lstm_scope:
         zero_state = initial_state = lstm_cell.zero_state(
                      batch_size=self.seq_embeddings.get_shape()[0], dtype=tf.float32)

        lstm_scope.reuse_variables()  
        sequence_length = tf.reduce_sum(self.input_mask, 1)
        lstm_outputs, _ = tf.nn.dynamic_rnn(cell=lstm_cell,
                                        inputs=self.seq_embeddings,
                                        sequence_length=sequence_length,
                                        initial_state=initial_state,
                                        dtype=tf.float32,
                                        scope=lstm_scope
                                        )

**Comment by drpngx** [comment]
Thank you for reporting this issue. From cursory inspection it looks like it's a usage issue rather than a bug in tensorflow. For this, we encourage our users to post on stackoverflow, where we monitor all questions with the tag `tensorflow`.
