### ISSUE TITLE
TFLite Podspecs haven't been updated after v2.14

### ISSUE THREAD

**Issue by guillaume-tgl** [tensorflow/tensorflow#71180]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.16.2

### Custom code

No

### OS platform and distribution

iOS

### Current behavior?

TensorflowLiteC podspec still uses the 2.14 binary and hasn't been updated since v2.14. It's necessary to be able to integrate the latest versions with the C API for iOS.

### Standalone code to reproduce the issue

```shell
N/A
```

**Comment by pkgoogle** [comment]
This seems correct: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/ios/TensorFlowLiteC.podspec

@yishuangP, can you please take a look? Thanks.
