### ISSUE TITLE
graph nodes inside sess.run() brackets should be garbage-collected

### ISSUE THREAD

**Issue by MKorablyov** [tensorflow/tensorflow#7127]
My input pipeline returns current epoch, and batch of images.

epoch,label_batch,image_batch  = my_input_pipeline(.....)
.....

Two examples:
`sess.run(epoch[0],train_step_run)`
gives 15 examples per second and RAM get filled over time very slowly.
`
sess.run(epoch,train_step_run)`
runs 100 examples per second and is stable. 

It would be great to make sess.run brackets "special" so that some TF function within it does not construct an infinite graph.

**Comment by yaroslavvb** [comment]
Can you try
```
a = epoch[0]
sess.run(a,train_step_run)
```

From your description it sounds like `sess.run(a)` is slow and leaks memory, but `sess.run([a])` doesn't, which indicates a bug

**Comment by MKorablyov** [comment]
I did not explain myself right. sess.run([a]) and sess.run(a) are same in my example, just tested this. Creating 
```
a = epoch[0]
sess.run(a,train_step_run) 
```
also works fine. a is a tensor object. 

The thing that would not work is:
sess.run(a[0]) 
```

**Comment by yaroslavvb** [comment]
Ah, right, `a[0]` adds a `strided_slice` op to the graph. It's the same problem if you did `sess.run(a+b)`, every time you run it, an `Add` op is added.
 
The way to prevent these kinds of errors is to run `tf.get_default_graph().finalize()` before modifying the graph.

If you do learning through higher level frameworks like `tf.slim` or `MonitoredSession` or `estimator`, those  already modify the graph for you, but I guess it's a potential hazard if you stay in the low-level API

**Comment by MKorablyov** [comment]
`tf.get_default_graph().finalize() `is indeed a good way to treat errors of this kind. Thank you for clarifications.

**Comment by MKorablyov** [comment]
You must have implicitly or explicitly called tf.something after tf.get_default_graph().finalize(). Check out your error line
