### ISSUE TITLE
Possible bug in inception_v1 in slim networks library

### ISSUE THREAD

**Issue by manjunaths** [tensorflow/tensorflow#7130]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

This question is probably not relevant to this issue. I did a Google search and didn't find any. 

### Environment info
Operating System:

**Windows 7 - 64 bit**

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

**None.**

### What other attempted solutions have you tried?

`<                 branch_2, 32, [3, 3], scope='Conv2d_0b_3x3')`
`---`
`>                 branch_2, 32, [5, 5], scope='Conv2d_0b_5x5')`

The inception_v1.py in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/nets/inception_v1.py, the inception layer is different from the paper. In the paper there is a 3x3 conv2d and a 5x5 conv2d module. I see that other frameworks have a 5x5 module and only here there are 2 3x3 modules instead.

Is this intentional or a bug ?

**Comment by jmchen-g** [comment]
Agreed. This sounds like a bug. Do you mind taking a PR for this please? Thanks. :)

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by manjunaths** [comment]
I went ahead and signed the CLA. I had to get corporate approval to do the process. Should I go ahead and create a new PR ? Or the old PR that I posted above can be reopened and pulled from ?
