### ISSUE TITLE
Tensorflow Lite: Using a custom GPU external delegate in conjunction with the official GPU delegate

### ISSUE THREAD

**Issue by BGigotSDS** [tensorflow/tensorflow#71362]
Hi,

we would like to implement some custom op running on GPU in a custom external delegate. If we use this delegate with the official GPU delegate as fallback for the standard ops, can we expect that the OpenCL buffers will be used between both delegates, or will the data go back and forth between GPU - CPU - GPU ? (which is what I would expect looking at the  delegate API).

**Comment by tilakrayal** [comment]
@BGigotSDS,

A custom delegate can create and manage its own OpenCL buffers for performing operations the same as a GPU delegate. However, the tensorflow lite delegate API does not provide a direct mechanism for delegates to share GPU buffers directly. Obviously, the data in GPU buffers need to be transferred back to the CPU before handing off to the other delegate. 

But the data transfer hence forth between GPU and CPU might lead to performance slowdown while inference. Here is the implementation of custom delegate [reference](https://www.tensorflow.org/lite/performance/implementing_delegate).

Thank you!

**Comment by BGigotSDS** [comment]
Thank you for your answer, I was expecting this, but wanted to be sure I didn't miss something. Thanks again for taking the time to answer.

**Comment by tilakrayal** [comment]
@BGigotSDS,
Could you please feel free to move this issue to closed status in that case. Thank you!
