### ISSUE TITLE
../genop/main.go:15: running "sh": exit status 1

### ISSUE THREAD

**Issue by notnot** [tensorflow/tensorflow#7136]
I am unable to get the Go binding for TensorFlow working on OS X 10.12. I followed the installation instructions at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/go.

Things go wrong when generating the wrapper functions for TensorFlow ops:
go generate github.com/tensorflow/tensorflow/tensorflow/go/op

The output from the above command is:
../genop/main.go:15: running "sh": exit status 1
op/generate.go:15: running "go": exit status 1

When browsing the sources i see an imported package
"github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/tensorflow/core/framework"
which isn't there. Maybe that is causing the issue?

**Comment by notnot** [comment]
I figured out that this issue was caused by having a GOPATH that consists of multiple directories, for instance mine is: GOPATH=$HOME/gocode/extern:$HOME/gocode/jpad;

This confuses generate.sh in locating PROTOC and eventually PATH. I fixed the issue by setting GOPATH to the top level directory that contains the source of TensorFlow, in my case  GOPATH=$HOME/gocode/extern

I'm not a .sh script expert enough to fix generate.sh to make it handle A GOPATH with multiple top level entries.

**Comment by asimshankar** [comment]
Sorry for the trouble and thanks for catching it. Yup, that generate script does assume a single directory in GOPATH. 

Contributions to fix this are welcome, as are ideas to make the whole process smoother.
(For example, avoiding the need for `go generate` by committing the generated code to the git repository is something we're thinking of but haven't started on)

**Comment by notnot** [comment]
Yes 'go generate' is for the package maintainer(s) to call, not for the end user who wishes to install the package. As long as the maintainer(s) know that generate.sh only works with a single-directory GOPATH all is fine. 
I did some searching to figure out how to robustly find the directory that a shell script is in, so that it could find PROTOC from there. There seems to be no reliable cross-platform cross-shell solution though :(

**Comment by yongtang** [comment]
@notnot @asimshankar Created a PR #8331 to try to address this issue. Please take a look.
