### ISSUE TITLE
iOS example missing #include "tensorflow/core/framework/types.pb.h"

### ISSUE THREAD

**Issue by kwccoin** [tensorflow/tensorflow#7141]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: iOS 10.2

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`): not related it is iOS

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by girving** [comment]
@kwccoin Does this issue persist?  Looks like this fell through the cracks (cough, @petewarden, cough).

**Comment by petewarden** [comment]
There's no enough information on this bug yet unfortunately. Could you confirm you successfully followed the steps here?
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile#ios

If that's true, please post reproduction steps so we can see the same error here.

**Comment by petewarden** [comment]
No response received after several weeks, so I'm closing for now. Please reopen with more information if this is incorrect.

**Comment by gi097** [comment]
Getting the issue here as well when building for iOS!
