### ISSUE TITLE
Library not loaded: @rpath/AdobeCreativeSDKCore.framework/AdobeCreativeSDKCore

### ISSUE THREAD

**Issue by knjeri** [tensorflow/tensorflow#7152]
I just completed migrating my project from swift 2 to swift 3. I had installed AdobeCreativeSDKCore and AdobeCreativeSDKImages as pod file. The code builds but I get a "**_Thread 1: signal SIGABRT_**" error in the "**_0_abory_with_payload_**" file and "**_10_dyld_start_**" 

```
dyld`__abort_with_payload:
    0x1063966f8 <+0>:  movl   $0x2000209, %eax          ; imm = 0x2000209 
    0x1063966fd <+5>:  movq   %rcx, %r10
    0x106396700 <+8>:  syscall 
->  0x106396702 <+10>: jae    0x10639670c               ; <+20>
    0x106396704 <+12>: movq   %rax, %rdi
    0x106396707 <+15>: jmp    0x106396014               ; cerror_nocancel
    0x10639670c <+20>: retq   
    0x10639670d <+21>: nop    
    0x10639670e <+22>: nop    
    0x10639670f <+23>: nop    
```

```
dyld`_dyld_start:
    0x10636e000 <+0>:   popq   %rdi
    0x10636e001 <+1>:   pushq  $0x0
    0x10636e003 <+3>:   movq   %rsp, %rbp
    0x10636e006 <+6>:   andq   $-0x10, %rsp
    0x10636e00a <+10>:  subq   $0x10, %rsp
    0x10636e00e <+14>:  movl   0x8(%rbp), %esi
    0x10636e011 <+17>:  leaq   0x10(%rbp), %rdx
    0x10636e015 <+21>:  movq   0x3ef04(%rip), %r8        ; _dyld_start_static
    0x10636e01c <+28>:  leaq   -0x23(%rip), %rcx         ; <+0>
    0x10636e023 <+35>:  subq   %r8, %rcx
    0x10636e026 <+38>:  leaq   -0x102d(%rip), %r8
    0x10636e02d <+45>:  leaq   -0x8(%rbp), %r9
    0x10636e031 <+49>:  callq  0x10636e073               ; dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*)
->  0x10636e036 <+54>:  movq   -0x8(%rbp), %rdi
    0x10636e03a <+58>:  cmpq   $0x0, %rdi
    0x10636e03e <+62>:  jne    0x10636e050               ; <+80>
    0x10636e040 <+64>:  movq   %rbp, %rsp
    0x10636e043 <+67>:  addq   $0x8, %rsp
    0x10636e047 <+71>:  movq   $0x0, %rbp
    0x10636e04e <+78>:  jmpq   *%rax
    0x10636e050 <+80>:  addq   $0x10, %rsp
    0x10636e054 <+84>:  pushq  %rdi
    0x10636e055 <+85>:  movq   0x8(%rbp), %rdi
    0x10636e059 <+89>:  leaq   0x10(%rbp), %rsi
    0x10636e05d <+93>:  leaq   0x8(%rsi,%rdi,8), %rdx
    0x10636e062 <+98>:  movq   %rdx, %rcx
    0x10636e065 <+101>: movq   (%rcx), %r8
    0x10636e068 <+104>: addq   $0x8, %rcx
    0x10636e06c <+108>: testq  %r8, %r8
    0x10636e06f <+111>: jne    0x10636e065               ; <+101>
    0x10636e071 <+113>: jmpq   *%rax
```

On the console I get
```
dyld: Library not loaded: @rpath/AdobeCreativeSDKCore.framework/AdobeCreativeSDKCore
  Referenced from: /Users/kelvinnjeri/Library/Developer/CoreSimulator/Devices/67DEC3A4-74B9-4203-97DA-004B8B4A254E/data/Containers/Bundle/Application/2A3FB423-BA0D-4DBD-9B51-748428D91D36/CloudiT.app/CloudiT
  Reason: image not found
(lldb) 
```
I've been checking the podfile, I seem to have the framework in the "Pods" droplist but not in the products drop list 

![screen shot 2017-01-30 at 4 23 24 pm](https://cloud.githubusercontent.com/assets/20662833/22442415/493d67ca-e709-11e6-81ef-de57964aa741.png)

![screen shot 2017-01-30 at 4 25 32 pm](https://cloud.githubusercontent.com/assets/20662833/22442284/cdca07ce-e708-11e6-895d-4cedfea7da17.png)

Im also not able to add it to the build phases cause Xcode is not giving me that option 

![screen shot 2017-01-30 at 4 28 21 pm](https://cloud.githubusercontent.com/assets/20662833/22442380/259b7f0a-e709-11e6-8d4a-fe54256d465c.png)

I'm sure it's a simple fix, probably somewhere in the settings but I'm don't know where. I am still new to iOS development. Any response is greatly appreciated

**Comment by sultan-arshi** [comment]
i have the same issue but could not find solution
i added manually these two framwork

**Comment by Coriolan-Bataille** [comment]
I have the exact same issue, trying from a whole day ...

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.
