### ISSUE TITLE
Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. #62097

### ISSUE THREAD

**Issue by risheek-mittal** [tensorflow/tensorflow#71564]
**System information**
- MacOS Sonoma 14.5:
- TensorFlow installed from https://github.com/tensorflow/tensorflow.git:

**Error output from tflite model in the Flutter Application**

Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select

**Standalone code to reproduce the issue** 
Link to Google Colab: [Expenses.ipynb](https://colab.research.google.com/drive/1n-cALnogLn4fblDQYaXzNA05XWihkv1e?usp=sharing)

**Any other info / logs**

I am using a TensorflowLite Ops model in Flutter application and whenever I am trying to use it the interpreter is returning a null value, I have tried creating an .aar file of the same using bazel and also the flex delegate using the code https://github.com/tensorflow/tensorflow/issues/62097#issuecomment-1767622437 mentioned here: 
`bazel build -c opt --config=monolithic tensorflow/lite/delegates/flex:tensorflowlite_flex `
and created the aar file using the code : 

```
bazel build -c opt --cxxopt=--std=c++17 --config=android_arm64 \
  --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a \
  --define=android_dexmerger_tool=d8_dexmerger \
  --define=android_incremental_dexing_tool=d8_dexbuilder \
  //tensorflow/lite/java:tensorflow-lite
```
Then I installed it to my local Maven and used the mavelLocal() repository:
```
repositories {
        google()
        mavenCentral()
        maven {         // add this repo to use snapshots
            name 'ossrh-snapshot'
            url 'https://oss.sonatype.org/content/repositories/snapshots'
        }
        mavenLocal()
    }
```
and also the dependency: `implementation 'org.tensorflow:tensorflow-lite:0.1.100'`
After all this I am still getting the same response from the application. Kindly look into it.

**Comment by sushreebarsa** [comment]
@risheek-mittal Could you please let us know the TF version you are using here?
Thank you!

**Comment by risheek-mittal** [comment]
I am using  
```
implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:2.16.1'
implementation 'org.tensorflow:tensorflow-lite:2.16.1'
implementation 'org.tensorflow:tensorflow-lite-gpu:2.12.0'
implementation 'org.tensorflow:tensorflow-lite-support:0.3.1'
```
Please try again with this link [Expense Colab](https://colab.research.google.com/drive/1n-cALnogLn4fblDQYaXzNA05XWihkv1e?usp=sharing)

**Comment by risheek-mittal** [comment]
Hey, there has been no updates on this ticket lately. May I know the progress for this?

**Comment by sawantkumar** [comment]
Hi @risheek-mittal ,

Can you use the below dependencies and let me know if it works? I just changed the version of tflite-gpu to 2.16.1 to match the other two dependencies .

```
implementation 'org.tensorflow:tensorflow-lite-select-tf-ops:2.16.1'
implementation 'org.tensorflow:tensorflow-lite:2.16.1'
implementation 'org.tensorflow:tensorflow-lite-gpu:2.16.1'
implementation 'org.tensorflow:tensorflow-lite-support:0.3.1'
```

**Comment by risheek-mittal** [comment]
Yeah hi @sawantkumar I tried it but it is still giving me the same response
`Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select`

**Comment by gaikwadrahul8** [comment]
Hi, @risheek-mittal

Could you please give it try with below mentioned command and see is it working as expected or not ? if issue still persists please let us know with error log for further investigation ? Thank you.

`bazel build -c opt --config=monolithic --config=android_arm64 tensorflow/lite/delegates/flex:tensorflowlite_flex`

**Comment by EngKuanSetlary** [comment]
hi, im facing this issue too, my model is yolov11
