### ISSUE TITLE
Tensorflow Metal Plugin produces different results with CPU for Conv1D

### ISSUE THREAD

**Issue by hguandl** [tensorflow/tensorflow#71577]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tensorflow 2.16.1
tensorflow-metal 1.1.0

### Custom code

Yes

### OS platform and distribution

macOS 14.5

### Mobile device

macOS 14.5

### Python version

3.9.19

### Current behavior?

If we create Conv1D layer with 65537 layers, the results are different.

On macOS (`pip install tensorflow-metal`), the results are:
```
y_cpu: [[[ 0.00041509 -0.00370452 -0.00212137 ... -0.00374832 -0.00753052
   -0.00895449]]]
y_gpu: [[[-0.00895449 -0.00370452 -0.00212137 ... -0.00374832 -0.00753052
    0.        ]]]
Equal: False
```

On Linux (`pip install tensorflow-gpu`), the results are:
```
y_cpu: [[[ 0.00225602  0.01136317  0.00391667 ... -0.0028112   0.00243109
   -0.00492344]]]
y_gpu: [[[ 0.00225602  0.01136317  0.00391667 ... -0.0028112   0.00243109
   -0.00492344]]]
Equal: True
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

tf.random.set_seed(0)

conv = tf.keras.layers.Conv1D(filters=65537, kernel_size=3, padding='same')

x = tf.ones([1, 1, 3])

with tf.device('/CPU:0'):
    y_cpu = conv(x)

with tf.device('/GPU:0'):
    y_gpu = conv(x)

print("y_cpu:", y_cpu.numpy())
print("y_gpu:", y_gpu.numpy())
print("Equal:", np.allclose(y_cpu.numpy(), y_gpu.numpy()))
```

**Comment by tilakrayal** [comment]
@hguandl,
When I tried to check in the colab which was having Linux in the background which was executed and observed that the results are also similar. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/6907eed04ea3b9cec404e0a753cb74a4/untitled2024.ipynb). I will check in Macos as well and provide more info on this. Meanwhile could you please check with tf-nightly and provide the update if you are facing the same. Thank you!

**Comment by tilakrayal** [comment]
@hguandl,
Apologies for the delay. I tried to execute the mentioned code using multiple environments like windows, wsl2, linux and others as well and couldn't find the different results with the CPU for Conv1D. So please raise the issue in the Apple forum for the quick resolution. Thank you!
