### ISSUE TITLE
How to fix this issue ? Please help ??

### ISSUE THREAD

**Issue by wscJayasooriya** [tensorflow/tensorflow#71578]
<img width="745" alt="image" src="https://github.com/tensorflow/tensorflow/assets/37790823/8af593a2-75e5-4acc-b599-551a0ea40ef5">

**Comment by tilakrayal** [comment]
@wscJayasooriya,
Could you please share colab link or simple standalone code with supporting files to reproduce the issue in our environment and the tensorflow version you are using. It helps us in localizing the issue faster. Thank you!

**Comment by wscJayasooriya** [comment]
import tensorflow as tf

model = tf.keras.models.load_model("../mymodel.keras")
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.save('saved_model.keras')

model = tf.keras.models.load_model('saved_model.keras')
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
converter = tf.lite.TFLiteConverter.from_keras_model(model)

tflite_model = converter.convert()

with open("../mymodel.tflite", "wb") as f:
    f.write(tflite_model)

-----------------------------------------------------ERROR-------------------------------------------
AttributeError: 'Sequential' object has no attribute '_get_save_spec'

**Comment by tilakrayal** [comment]
@wscJayasooriya,
Yeah. This is the known issue in tensorflow v2.16. Could you please try using Legacy Keras is the preferred workaround for now:

```python
import os
os.environ["TF_USE_LEGACY_KERAS"]="1"
```

https://blog.tensorflow.org/2024/03/whats-new-in-tensorflow-216.html
https://github.com/tensorflow/tensorflow/issues/63867

Thank you!

**Comment by wscJayasooriya** [comment]
Sorry for the late response. Your answer helped me in my issue. 
Thank you
