### ISSUE TITLE
Documentation for Inference from saved model

### ISSUE THREAD

**Issue by ashokvishnoi1994** [tensorflow/tensorflow#7158]
As explained at https://www.tensorflow.org/tutorials/mnist/pros/#build_a_multilayer_convolutional_network I created a CNN for MNIST image recognition. I don't want to test it in the same script so I trained the model, saved the checkpoint files and graph structure and then using freeze_graph.py script(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py)  I froze it into single .pb file. Now using this .pb file I want to check the accuracy of the model but there is no clear documentation as to how to do it. There is one example written in examples/label_images directory but that too is in C++ and for inception network. I have already parsed the .pb file and made a tf.Graph object.

**Comment by sskgit** [comment]
@ashokvishnoi1994 You will have to export your trained model with Tensorflow Serving Server for inference. Here is the documentation on Inference/serving. 
https://tensorflow.github.io/serving/serving_basic
and 
https://tensorflow.github.io/serving/serving_advanced

**Comment by jmchen-g** [comment]
You should be able to run the frozen graph. Pete should know all hte details about how to run a frozen graph. :)

**Comment by inflation** [comment]
@ashokvishnoi1994 Some documentation does help. But if you want to get some quick information, you can try something like this: 
```python
with tf.Session(graph=tf.Graph()) as sess:
    input, predictions = tf.import_graph_def(g, return_elements=
                                                     ['Input:0', 
                                                      'Predictions/Reshape_1:0'])
    p_val = predictions.eval(feed_dict={input: image})
```
where you need to know the name of input node and output node when you freeze the graph.

**Comment by girving** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
