### ISSUE TITLE
Java: Update README to run the configure script

### ISSUE THREAD

**Issue by neilatsyracuse** [tensorflow/tensorflow#7169]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by asimshankar** [comment]
There isn't enough detail here to go by. Please include as much detail as you can to reproduce the problem. Filling in all the fields above of the bug template would help, as would any logs of the steps you took and the full output of the error.

**Comment by neilatsyracuse** [comment]
I followed the step of TensorFlow for Java. I installed all the requirement and clone the whole tensorflow repository from git.  I was caught the error when I was trying to use this commend: 
bazel build -c opt \
  //tensorflow/java:tensorflow \
  //tensorflow/java:libtensorflow_jni
under the tensorflow folder.
The detailed errors:
ERROR: /Users/neil/tensorflow/tensorflow/core/BUILD:1226:1: no such target '//tensorflow/tools/git:gen/spec.json': target 'gen/spec.json' not declared in package 'tensorflow/tools/git' defined by /Users/neil/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /Users/neil/tensorflow/tensorflow/core/BUILD:1226:1: no such target '//tensorflow/tools/git:gen/head': target 'gen/head' not declared in package 'tensorflow/tools/git' defined by /Users/neil/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /Users/neil/tensorflow/tensorflow/core/BUILD:1226:1: no such target '//tensorflow/tools/git:gen/branch_ref': target 'gen/branch_ref' not declared in package 'tensorflow/tools/git' defined by /Users/neil/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: Analysis of target '//tensorflow/java:tensorflow' failed; build aborted.
INFO: Elapsed time: 0.178s
Neils-MacBook-Pro:tensorflow neil$ bazel build -c opt \
>   //tensorflow/java:tensorflow \
>   //tensorflow/java:libtensorflow_jni
ERROR: /Users/neil/tensorflow/tensorflow/core/BUILD:1226:1: no such target '//tensorflow/tools/git:gen/spec.json': target 'gen/spec.json' not declared in package 'tensorflow/tools/git' defined by /Users/neil/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /Users/neil/tensorflow/tensorflow/core/BUILD:1226:1: no such target '//tensorflow/tools/git:gen/head': target 'gen/head' not declared in package 'tensorflow/tools/git' defined by /Users/neil/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /Users/neil/tensorflow/tensorflow/core/BUILD:1226:1: no such target '//tensorflow/tools/git:gen/branch_ref': target 'gen/branch_ref' not declared in package 'tensorflow/tools/git' defined by /Users/neil/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: Analysis of target '//tensorflow/java:tensorflow' failed; build aborted.

**Comment by asimshankar** [comment]
Ah, I see. The problem is that the [`configure`](https://github.com/tensorflow/tensorflow/blob/master/configure) script needs to be run first (as per the "[install from sources](https://www.tensorflow.org/get_started/os_setup#configure_the_installation)" instructions on www.tensorflow.org) I will update the java README to reflect that.

Please run that and let us know if that solves your problem.
