### ISSUE TITLE
DBpedia datasets not available. 404.

### ISSUE THREAD

**Issue by EDjur** [tensorflow/tensorflow#7171]
Trying to run the code in /learn/text_classification returns a 404 when trying to download the DBpedia dataset.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/text_classification.py

The constant "DBPEDIA_URL" in .../learn/python/learn/datasets/text_datasets.py seems to be wrong as it returns a 404 in Chrome as well.

This is the URL in text_datasets.py:
https://googledrive.com/host/0Bz8a_Dbh9Qhbfll6bVpmNUtUcFdjYmF2SEpmZUZUcVNiMUw1TWN6RDV3a0JHT3kxLVhVR2M/dbpedia_csv.tar.gz

Which returns a 404.

**Comment by girving** [comment]
Looks fixed at head: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/datasets/text_datasets.py#L30.
