### ISSUE TITLE
a bug in inception models?

### ISSUE THREAD

**Issue by Lucas2012** [tensorflow/tensorflow#7173]
Hi,

I tried to use inception-vx model to extract features, but it keeps giving me error saying tensor name xxx not found in checkpoint files. I'm wondering whether it's my incorrect usage or there's some inconsistency.

The model files(ckpt) are downloaded from: https://github.com/tensorflow/models/blob/master/slim/README.md#pre-trained-models

My code is:

import tensorflow as tf
import nets.inception_v4 as net_v4

x = tf.placeholder(tf.float32, shape=[None, 299, 299,3])
inv4 = net_v4.inception_v4(x)
saver = tf.train.Saver()
sess = tf.Session()

saver.restore(sess, "models/inception_v4.ckpt")

The error output:

...
NotFoundError (see above for traceback): Tensor name "InceptionV4/Mixed_6d/Branch_2/Conv2d_0e_1x7/biases" not found in checkpoint files models/inception_v4.ckpt
	 [[Node: save/RestoreV2_150 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_150/tensor_names, save/RestoreV2_150/shape_and_slices)]]
	 [[Node: save/RestoreV2_31/_567 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1633_save/RestoreV2_31", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by civilman628** [comment]
```
import tensorflow as tf
import tensorflow.contrib.slim as slim
from nets.inception_v4 import inception_v4, inception_v4_arg_scope
import numpy as np

height = 299
width = 299
channels = 3

# Create graph
X = tf.placeholder(tf.float32, shape=[None, height, width, channels])
with slim.arg_scope(inception_v4_arg_scope()):
    logits, end_points = inception_v4(X, num_classes=1001,
                                      is_training=False)
predictions = end_points["Predictions"]
saver = tf.train.Saver()

X_test = np.ones((1,299,299,3))  # your images, shape [batch_size, 299, 299, 3]

# Execute graph
with tf.Session() as sess:
    saver.restore(sess, "./inception_v4.ckpt")
    predictions_val = predictions.eval(feed_dict={X: X_test})
```

**Comment by Lucas2012** [comment]
Thank you.:) It worked.
