### ISSUE TITLE
Go: Documentation of default values for attributes of generated ops can be confusing

### ISSUE THREAD

**Issue by notnot** [tensorflow/tensorflow#7175]
In the Go documentation of op.MatMulTransposeA it says 
"value: If true, "a" is transposed before multiplication. If not specified, defaults to b:false" 
which should probably be 
"value: If true, "a" is transposed before multiplication. If not specified, defaults to a:false"

I haven't figured out yet where the documentation for the generated Go source code comes from, maybe it is used to generate documentation in other formats as well.

**Comment by yaroslavvb** [comment]
could you provide link please? Documentation for Python is automatically generated from the string in C file with implementation here -- https://github.com/tensorflow/tensorflow/blame/a0d784bdd31b27e013a7eac58a86ba62e86db299/tensorflow/core/ops/math_ops.cc#L1030

**Comment by asimshankar** [comment]
I think I know what's happening.

Short story: That "b" there (yes, confusingly) refers not to the name of the attribute but rather the name of the field in the `AttrValue` proto.

Long story: The documentation for Go is generated by the `genop` code generator. The linke you're referring to comes from [`genop.go:177`](https://github.com/tensorflow/tensorflow/blob/f8d75baaf4c92e76837de6bb64adccf8127a21d6/tensorflow/go/genop/internal/genop.go#L177), which in turn uses the compact string representation of the [`AttrValue` protocol buffer's `value` field](https://github.com/tensorflow/tensorflow/blob/cb17d1b0e2b581b5da1d9597b7929ba764749d38/tensorflow/core/framework/attr_value.proto#L34), which is a `oneof`. So the `b:` is referring to the fact that the boolean field is named `b`

I'm going to mark this as contributions welcome for now and think about possible solutions a bit more.
