### ISSUE TITLE
Tensorflow not showing summaries anymore

### ISSUE THREAD

**Issue by panmari** [tensorflow/tensorflow#718]
On current master, the tensorboard will start as intended but only show the 'No scalar summaries found' error message. In the log, there are two errors:

```
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/external/paper-tabs/paper-tabs.html' on path /usr/local/lib/python2.7/dist-packages/external/paper-t
abs/paper-tabs.html

... some GET

WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/runs' on path /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/runs
```

**Comment by skearnes** [comment]
+1

**Comment by skearnes** [comment]
Seems to be fixed by 5d824f1.

**Comment by panmari** [comment]
Summaries are shown again, but the navigation is still broken. In the log there is still this error:

    WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/external/paper-tabs/paper-tabs.html' on path /usr/local/lib/python2.7/dist-packages/external/paper-tabs/paper-tabs.html

And clicking on e. g. `images` does redirect to `http://localhost:6006/#null`. Manually entering `http://localhost:6006/#images` works.

**Comment by danmane** [comment]
Thanks for the report. The issue is that we took a dependency on paper-tabs but didn't update the root.workspace rule to download paper-tabs (there was a bug in the synchronization script). It's fixed now and should make its way to master shortly.
