### ISSUE TITLE
GPU delegate and NNAPIDelegate results diverging significantly for a transformer model

### ISSUE THREAD

**Issue by pulkitagarawal** [tensorflow/tensorflow#71809]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.15

### Custom code

Yes

### Mobile device

Android Snapdragon 855 (Samsung Fold5/S24Ultra)

### Python version

3.11
Huggingface transformer 4.21

### Current behavior?

I have converted a transformer model(https://huggingface.co/Salesforce/blip-vqa-base) as tflite for running on an Android device.
Blipvqa consists of 3 nested models vision_encoder, text_encoder and text_decoder.
I seperated the vision_encoder as seperate tensorflow model and converted it as tflite.
The model works perfectly fine on CPU.

When running the same tflite model on GPU there were few ops like Stridedslice reshape(5d) etc. Which were throwing error with GPUdelegate.
So before conversion i rewired few exiting operations to support the same on GPU.
Now the model runs fine on GPU delegate but the results of CPU(NNAPIdelegate) and GPU(GPUDelegate) are different and diverging significantly. 

I am using float32 weights and have set precisionlossallowed as false for GPU delegate to avoid any rounding off errors.
Even after running it with float32 precision the output is very different of GPUdelagte.

When i debugged the output layer by layer i found that the result starts diverging from the first Conv2D layer and the divergence grows significantly after multiple layers of vision encoder model.

I am unable to comprehend why even for a float32 weight the output of GPU delegate varies.
If this is the case then such deep networks of transformers models will always produce poor outputs on Android GPU delegates.

### Standalone code to reproduce the issue

```shell
https://github.com/huggingface/transformers/blob/main/src/transformers/models/blip/modeling_tf_blip.py

In above code refer to class TFBlipVisionEmbeddings(keras.layers.Layer)

This has a Conv2d operation which when inspected produces different results on CPU and GPU of Android.
The issue is not just with the Conv2d. Later in other layers of TFBlipVisionModel(TFBlipPreTrainedModel) the same divergence explodes for further operations.
I have used the .h5 weights provided on hugging face blipvqa for loading the model.

Any suggestions how to make sure that the output stays close for NNApiDelegate and GPUdelegate.
```

**Comment by sawantkumar** [comment]
Hi @pulkitagarawal ,

Can you please provide me the conversion script and also the converted tflite model if possible?
