### ISSUE TITLE
can't open tensorboard while training 

### ISSUE THREAD

**Issue by menglin0320** [tensorflow/tensorflow#7181]
(You can navigate to http://127.0.1.1:6006)
 * Running on http://0.0.0.0:6006/ (Press CTRL+C to quit)
127.0.0.1 - - [31/Jan/2017 23:25:27] "GET /neon-animation/neon-animation-behavior.html HTTP/1.1" 200 -
127.0.0.1 - - [31/Jan/2017 23:25:27] "GET /neon-animation/web-animations.html HTTP/1.1" 200 -
127.0.0.1 - - [31/Jan/2017 23:25:27] "GET /iron-overlay-behavior/iron-overlay-backdrop.html HTTP/1.1" 200 -
127.0.0.1 - - [31/Jan/2017 23:25:27] "GET /web-animations-js/web-animations-next-lite.min.js HTTP/1.1" 200 -
127.0.0.1 - - [31/Jan/2017 23:25:27] "GET /paper-input/paper-input.html HTTP/1.1" 200 -
127.0.0.1 - - [31/Jan/2017 23:25:27] "GET /paper-slider/paper-slider.html HTTP/1.1" 200 -
*** Error in `/home/menglin/anaconda2/envs/tensorflow/bin/python': double free or corruption (!prev): 0x00000000009f6a80 ***
Aborted (core dumped)

**Comment by menglin0320** [comment]
version is '0.12.head'

**Comment by menglin0320** [comment]
@dsmilkov could you please take a look at this issue?
I guess the reason is that I used the wrong version of bazel
Build label: 0.4.2

**Comment by jmchen-g** [comment]
If you already have a suspect of the reason, can you try to fix it and come back please? Thanks.

**Comment by menglin0320** [comment]
Thanks for your advise. I may do that later. I don't know anything about bazel and it takes time to compile Tensorflow, so I'm not sure I should use a newer version or older version.  I expect someone who knows the library to help me. I'm pretty busy utils this Wednesday , I may try to fix it afterward.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
