### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by Irayanbu05** [tensorflow/tensorflow#71828]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

not shown

### Custom code

Yes

### OS platform and distribution

Windows 10

### Current behavior?

Module not found error. It shows tensorflow.python not found

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
```

**Comment by Irayanbu05** [comment]
what should I do now

**Comment by tilakrayal** [comment]
@Irayanbu05,
Could you please provide the steps you have followed to install the tensorflow. Also please let us know which tensorflow versions, environment and compatible configurations you are trying. 

Please have a look at the [compatible](https://www.tensorflow.org/install/source_windows#tested_build_configurations) tested build configurations as well and the official document for the installation steps.

https://www.tensorflow.org/install/pip#step-by-step_instructions
 Thank you!
