### ISSUE TITLE
Float support for scatter_nd

### ISSUE THREAD

**Issue by aliosmanulusoy** [tensorflow/tensorflow#7185]
Hi,
It seems the updates input to scatter_nd is limited to int32 and int64 input: [https://www.tensorflow.org/api_docs/python/array_ops/slicing_and_joining#scatter_nd](https://www.tensorflow.org/api_docs/python/array_ops/slicing_and_joining#scatter_nd)

It'd be great to have float32 and float64 support. Is this possible?

Thanks!

**Comment by yaroslavvb** [comment]
This also works

```
indices = tf.constant([[4], [3], [1], [7]])
updates = tf.constant([9., 10., 11., 12.], dtype=tf.float32)
shape = tf.constant([8])
scatter = tf.scatter_nd(indices, updates, shape)
sess = tf.Session()
print(sess.run(scatter))
```

**Comment by aliosmanulusoy** [comment]
Thanks @yaroslavvb. I guess I misread the API. It works for me too.
