### ISSUE TITLE
missing fclose

### ISSUE THREAD

**Issue by maddin200** [tensorflow/tensorflow#7186]
\contrib\pi_examples\label_image\label_image.cc line 105

missing fclose(infile);

**Comment by yaroslavvb** [comment]
would you like to send a PR to fix this?

**Comment by yaroslavvb** [comment]
BTW, PR for such small change is quite easy and you can do it mostly from browser:

First, click "Fork" on github tensorflow page 

Then in Terminal:
git remote add mine https://github.com/<username>/tensorflow
git remote add tfmain https://github.com/tensorflow/tensorflow.git
git fetch tfmain
git checkout tfmain/master -b bugfix
git push --set_upstream mine

Then in bugfix branch on <username>/tensorflow on Github, find file, click "Edit" button, edit file, then click commit, then click "Pull Requests" and select "tensorflow/master" on left and "<username>/tensorflow:bugfix" on right

**Comment by teldridge11** [comment]
@yaroslavvb Looks like this issue has been resolved.
