### ISSUE TITLE
Unexpected behavior after updating a placeholder

### ISSUE THREAD

**Issue by sarshalom** [tensorflow/tensorflow#7188]
The output of the following snippet
```
ph = tf.placeholder(tf.int32)
ph += 1000
a = ph + 0
init = tf.initialize_all_variables()
sess.run(init)
print(sess.run([a], {ph: 5}))
```
is `[5]`, and not `[1005]` as could be expected.
Perhaps it's because placeholders can't be evaluated, and therefore TF ignores the update op of `ph`?

**Comment by yaroslavvb** [comment]
you overwrote your original placeholder in `ph+=1000` line so you are not feeding what you think you are feeding. PS we are trying to keep questions like this on stackoverflow and this list for bugs in TensorFlow itself
