### ISSUE TITLE
Tensorflow Dataset API continues to be broken, list_files no longer works

### ISSUE THREAD

**Issue by dryglicki** [tensorflow/tensorflow#71884]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

pip install tensorflow[and-cuda]

### TensorFlow version

tf v2.17.0-rc1-2-gad6d8cc177d

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu

### Python version

3.11.9

### Current behavior?

`list_files` from Tensorflow Dataset API is now broken in TF 2.17. I cannot follow the example located here: https://www.tensorflow.org/guide/data#consuming_sets_of_files

After the issues where employing TFRecords and using generators blows up memory, now `list_files` won't even work. I've attached code that will list the appropriate files using both `pathlib` and `glob` libraries. Both return lists.

What on earth is going on here.

### Standalone code to reproduce the issue

```shell
#!/usr/bin/env python3
import os ; import sys
from pathlib import Path
import glob

import tensorflow as tf

output_path = Path('test_text')
if not output_path.exists(): output_path.mkdir(parents=True)

num_files = 10
write_out_string = 'abcdef'
for fnum in range(num_files):
    output_file = output_path / f'sample_{fnum:03d}.txt'
    with open(output_file, 'w') as f:
        f.write(write_out_string)
        
# First, try with Python's pathlib glob, make sure it can see the files
print("With pathlib.")
print(list(output_path.glob('*txt')))
print()

# Next, try to with Python's glob
print("With glob")
glob_path = output_path / '*txt'
print(list(glob.glob(str(glob_path))))

list_ds = tf.data.Dataset.list_files(str(glob_path))

for bf in list_ds.take(5):
    print(bf.numpy())
```

### Relevant log output

```shell
With pathlib.
[PosixPath('test_text/sample_009.txt'), PosixPath('test_text/sample_007.txt'), PosixPath('test_text/sample_000.txt'), PosixPath('test_text/sample_006.txt'), PosixPath('test_text/sample_004.txt'), PosixPath('test_text/sample_008.txt'), PosixPath('test_text/sample_005.txt'), PosixPath('test_text/sample_002.txt'), PosixPath('test_text/sample_001.txt'), PosixPath('test_text/sample_003.txt')]

With glob
['test_text/sample_009.txt', 'test_text/sample_007.txt', 'test_text/sample_000.txt', 'test_text/sample_006.txt', 'test_text/sample_004.txt', 'test_text/sample_008.txt', 'test_text/sample_005.txt', 'test_text/sample_002.txt', 'test_text/sample_001.txt', 'test_text/sample_003.txt']
2024-07-15 15:39:17.545697: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 46673 MB memory:  -> device: 0, name: NVIDIA RTX 6000 Ada Generation, pci bus id: 0000:16:00.0, compute capability: 8.9


Traceback (most recent call last):
  File "/home/dryglicki/code/list_files/demonstrate_list_files.py", line 28, in <module>
    list_ds = tf.data.Dataset.list_files(str(glob_path))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd0/miniforge3_2024-04/envs/tensorflow_2d17/lib/python3.11/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1318, in list_files
    string_ops.reduce_join(file_pattern, separator=", "), name="message")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ssd0/miniforge3_2024-04/envs/tensorflow_2d17/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/ssd0/miniforge3_2024-04/envs/tensorflow_2d17/lib/python3.11/site-packages/tensorflow/python/framework/constant_op.py", line 108, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: object __array__ method not producing an array
```

**Comment by dryglicki** [comment]
For what it's worth, pre-globbing and using `from_tensor_slices` does allow for one to iterate through the filenames.

But if `list_files` is indeed deprecated, somebody say so!

**Comment by dryglicki** [comment]
Another issue. This will also fail if `TFRecordDataset` is in the chain. If I need to open a separate ticket or issue or post more code, please let me know. But the `TFRecordDataset` issue appears both when wrapped by `interleave` or when pre-globbing and using those file names in `TFRecordDataset` directly.

**Comment by tilakrayal** [comment]
@dryglicki,
I tried to execute both the official document code and mentioned code with latest tensorflow stable version 2.17.0, observed that both are executed without fail/error. Kindly find the gist of both and update if the understanding is correct. 
[Official doc](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/data.ipynb) and [code](https://colab.research.google.com/gist/tilakrayal/ebfc5bcece7c534c31cd797257e7cb4f/untitled2004.ipynb)
Thank you!

**Comment by dryglicki** [comment]
All right, I can confirm if I use 3.10.14 and force `pip install tensorflow[and-cuda]==2.17.0` I can get it to work.

**Comment by dryglicki** [comment]
All right, found the source of the problem. It's dependency collision.

matplotlib installed via `conda` brings numpy 2.0 which runs over the numpy 1.X version installed via pip for tensorflow.
