### ISSUE TITLE
failed to enqueue async memcpy from device to host with latest code

### ISSUE THREAD

**Issue by JianbangZ** [tensorflow/tensorflow#719]
This problem shows up after I did a git pull today to the last commit of Jan 6th. <63bddb>
Roll back the the last commit of Jan 5th solves the issue

failed to enqueue async memcpy from device to host
check failed: CUDA_SUCCESS == dynlod::cuCtxSetCurrent(prior_context_) (0 vs. 4)

**Comment by skearnes** [comment]
+1. Similar to #713.

**Comment by vrv** [comment]
Let's take discussion to that
