### ISSUE TITLE
TensorFlow embedded in esp32

### ISSUE THREAD

**Issue by Ligeirinho00** [tensorflow/tensorflow#71965]
Hello,

I am looking to use TensorFlow Lite embedded in a microprocessor for a specific project. I will not be using computer vision or cameras; my goal is to identify the passage of people using a distance sensor.

We will have only one input of type float and one output of type int. We will input the measured distance and, after a series of measurements, receive information on whether one, two, or no people are passing by.

Although it is a basic application, I am facing difficulties in finding materials that can help. Most of the projects I found are outdated (the libraries have changed significantly, and many no longer work) or are aimed at camera usage. Even the courses I purchased focus exclusively on cameras.

If anyone knows where I can find supporting materials or could provide some assistance, I would greatly appreciate it.

Thank you for your attention!

**Comment by sawantkumar** [comment]
Hi @Ligeirinho00 ,

Your use case is very specific so i am not sure if there are existing examples related to your case. But you can find several examples of running tflite models on embedded devices at https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples.
