### ISSUE TITLE
Tensorflow crash driver CUDA of GeForce RTX 4090

### ISSUE THREAD

**Issue by 333Random333** [tensorflow/tensorflow#72002]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.10.0

### Custom code

Yes

### OS platform and distribution

Win10x64 Pro

### Python version

3.10.6

### CUDA/cuDNN version

12.2

### GPU model and memory

Geforce RTX 4090 24Gb

### Current behavior?

I have two Geforce RTX 4090 on one motherboard. I'm running two processes for training Tensorflow models on different maps.  After some time, the process crashes on GPU 0, but on GPU 1 it works without failures. I am attaching a screenshot of the error. How to fix it?
Driver Version : 537.34
CUDA Version : 12.2
TensorFlow version: 2.10.0
OS: Win10x64 Pro
![Ошибка Cuda](https://github.com/user-attachments/assets/b4472c10-8471-4669-b83d-52b3a1664052)

### Standalone code to reproduce the issue

```shell
for tr_opt in train_options_list:
    with tf.device('/GPU:0'):
        files = os.listdir(dir_data_path + param_dir + '/' + tr_opt)
        num_files = len(files)

        df_agg = pd.DataFrame()
        for i in range (0, num_files):
          current_file = pd.read_excel(dir_data_path + param_dir + '/' + tr_opt + '/' + files[i])
          current_file.columns = ['Время', param_dir]
          df_agg = pd.concat([df_agg, current_file])
    
        data = df_agg[param_dir].values.reshape(-1, 1)

        train_set_scale = scaler.transform(data)

        # Формируем матрицу
        n_steps = 180
        n_features = 1
        train_matrix = create_matrix(train_set_scale, n_steps)

        tf.keras.backend.clear_session()
        np.random.seed(41)

        model = tf.keras.models.Sequential()
        model.add(tf.keras.layers.InputLayer(input_shape=(n_steps, n_features)))
        model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(16, return_sequences=True)))
        model.add(tf.keras.layers.ReLU())
        model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(8, return_sequences=True)))
        model.add(tf.keras.layers.ReLU())
        model.add(tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(16, return_sequences=True)))
        model.add(tf.keras.layers.ReLU())
        model.add(tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(n_features)))

        model.compile(optimizer='adam', loss="mse")

        net_history = model.fit(train_matrix, train_matrix, epochs=10, batch_size=150)
        model.save(save_path + 'model.h5')
```

**Comment by arthurflor23** [comment]
Wow, I also have two Geforce RTX 4090 GPUs on a motherboard and had the same problem on Linux with Python 3.11 and TensorFlow 2.15.1.

For me, the whole system crashes and only a restart solves the problem. I don't know if this is the root issue, but for now, I'm just using one RTX 4090. In addition, I was using driver 535, and now 550 (still testing).

**Comment by 333Random333** [comment]
> Wow, I also have two Geforce RTX 4090 GPUs on a motherboard and had the same problem on Linux with Python 3.11 and TensorFlow 2.15.1.
> 
> For me, the whole system crashes and only a restart solves the problem. I don't know if this is the root issue, but for now, I'm just using one RTX 4090. In addition, I was using driver 535, and now 550 (still testing).

Is this not observed with one RTX 4090? 
In my code I use tensorflow to isolate the training calls using:
```
with tf.device('/GPU:0'):
    model.fit(...)
```
And also for the second process, but with tf.device('/GPU:1').

At the beginning of both the scripts I use tensorflow dynamic memory allocation:
```
gpus = tf.config.list_physical_devices('GPU')
tf.config.set_visible_devices(gpus[0], 'GPU')
tf.config.experimental.set_memory_growth(gpus[0], True)
```
And also for the second process gpus[1].

However, these actions do not solve the problem...

**Comment by arthurflor23** [comment]
> Is this not observed with one RTX 4090?

I'm still testing as the issue arises randomly, but for now, no problem.
 
> ```
> gpus = tf.config.list_physical_devices('GPU')
> tf.config.set_visible_devices(gpus[0], 'GPU')
> tf.config.experimental.set_memory_growth(gpus[0], True)
> ```

I'm doing the same.

Actually, I think the problem might be related to the driver version (530 series). So, I'm also using the 550 series to see if it resolves the issue.

**Comment by tilakrayal** [comment]
@333Random333,
Is this crash happening with the tensorflow 2.10 only, or with the latest version tensorflow v2.17 as well. As mentioned above it is working with the 530 and 540 series as well. kindly check and let us know. Thank you!
