### ISSUE TITLE
Feeding to boolean placeholder -- works in TF 0.11 but not in 0.12.1

### ISSUE THREAD

**Issue by charlesq34** [tensorflow/tensorflow#7201]
@yaroslavvb The info is attached below. I've targeted the problem to the conflict of tf.cond on boolean placeholder with the ExponentialMovingAverage's apply function.

The same code works just fine in TF 0.11

Environment Info
============================
OS: Ubuntu 14.04
CUDA: 8.0 with cuDNN 5.1
TEnsorflow 0.12.1

Minimal Example:
============================
```python
import tensorflow as tf
import numpy as np

with tf.Graph().as_default():
    with tf.device('/gpu:0'):
        isTrain = tf.placeholder(tf.bool, shape=())
        user_input = tf.placeholder(tf.float32, shape=(2,4))

        with tf.variable_scope('batchnorm') as sc:
           batch_mean, batch_var = tf.nn.moments(user_input, [0,])
           ema = tf.train.ExponentialMovingAverage(decay=0.9)

           ema_apply_op = tf.cond(isTrain,
                           lambda: ema.apply([batch_mean, batch_var]),
                           lambda: tf.no_op())

    init = tf.initialize_all_variables()
    sess = tf.Session()
    sess.run(init)
    sess.run([batch_mean], feed_dict={user_input:[[1,2,3,4],[2,3,4,5]], isTrain: True})
```

Error Message:
============================
```
InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype bool
	 [[Node: Placeholder = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
```

**Comment by yaroslavvb** [comment]
Could you fill out the template?

**Comment by charlesq34** [comment]
@yaroslavvb I've found the solution, but I'm still not sure why this will happen for TF 0.12.1 (there is no error for TF 0.11). The info is attached below.

When I moved the line "ema_apply_op = ema.apply([batch_mean, batch_var])" out of the "mean_var_with_update" function, so that it's one line above the definition of "mean_var_with_update", the error no longer appears. Otherwise, the error is:

tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype bool
	 [[Node: Placeholder = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/gpu:0"]()]]



Environment Info
============================
OS: Ubuntu 14.04
CUDA: 8.0 with cuDNN 5.1
TEnsorflow 0.12.1

Minimal Example:
============================
import tensorflow as tf
import numpy as np

with tf.Graph().as_default():
    with tf.device('/gpu:0'):
        isTrain = tf.placeholder(tf.bool, shape=())
        user_input = tf.placeholder(tf.float32, shape=(2,4))

        with tf.variable_scope('batchnorm') as sc:
           beta = tf.Variable(tf.constant(0.0, shape=[4]))
           gamma = tf.Variable(tf.constant(1.0, shape=[4]))
           batch_mean, batch_var = tf.nn.moments(user_input, [0,])
           ema = tf.train.ExponentialMovingAverage(decay=0.9)

           def mean_var_with_update():
             ema_apply_op = ema.apply([batch_mean, batch_var])
             with tf.control_dependencies([ema_apply_op]):
               return tf.identity(batch_mean), tf.identity(batch_var)

           mean, var = tf.cond(isTrain,
                               mean_var_with_update,
                               lambda: (ema.average(batch_mean), ema.average(batch_var)))
           normed = tf.nn.batch_normalization(user_input, mean, var, beta, gamma, 1e-3)

    # ======= End Here ==========
    init = tf.global_variables_initializer()
    sess = tf.Session()
    sess.run(init)
    is_training = True
    u = [[2,3,35,5],[1,3,45,2]]
    aa = sess.run([normed], feed_dict={user_input:u, isTrain: is_training})

**Comment by charlesq34** [comment]
A related post about the problem in StackOverflow:
http://stackoverflow.com/questions/41543774/invalidargumenterror-for-tensor-bool-tensorflow-0-12-1

It seems that the boolean placeholder is not correctly initialized. 
After using ```python
sess.run(init, {isTrain: True}) ```
The minimal example works fine.

**Comment by yaroslavvb** [comment]
Can you try in a later version (ie, nightly?)

I tried your example in a version I built from head last week, and it worked without error

**Comment by girving** [comment]
Closing pending more information.  If it's fixed in HEAD, we're good.

**Comment by EfratSo** [comment]
charlesq34 - you said it works when you specify {isTrain: True}, but what if you need the condition to be dependent on the inputs?
I can't feed in advance the feed_dict on the  "initialize_all_variables" stage, because I later on have multiple calls for sess.init().

any ideas?

**Comment by stripathi08** [comment]
@EfratSo Wouldn't feeding in True/False as per your condition in your subsequent calls make it work?
