### ISSUE TITLE
Noticable lag with different Inception model

### ISSUE THREAD

**Issue by ales6164** [tensorflow/tensorflow#7203]
Running the demo app on Android works absolutelly great. Then I tried retraining the inception5h model (as used by the app) with no success. I retrained Inception v3 model but then image recognition would lag. I tried quantizating the model but it lagged even more. So what I'm asking is for a direction or help on the issue or a retrainable Inception5h model with some instructions.

**Comment by andrewharp** [comment]
For help retraining inception5h you can try asking on StackOverflow, but I imagine mainly it's the same as Inception v3 just with different layer names (found in ClassifierActivity.java).

Regarding the latency, Inception v3 is a larger model so it's expected that it will run more slowly. What sort of numbers are you seeing, and on what devices?

**Comment by ales6164** [comment]
I get about 1 or 2 predictions per second on Huawei Mate 9.

StackOverlow: http://stackoverflow.com/questions/42003846/retraining-inception5h-model-from-tensorflow-android-camera-demo

**Comment by andrewharp** [comment]
This seems within normal ranges (hard to say without exact numbers). Closing as there is no addressable TensorFlow issue here.
