### ISSUE TITLE
Should use math_ops.reduce_prod() in mixture.py instead of array_ops.reduce_prod()

### ISSUE THREAD

**Issue by botonchou** [tensorflow/tensorflow#7204]
Hi,

I tried to use mixture density distribution with batch_size **None**, and triggered this error
```bash
/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/distributions/python/ops/mixture.pyc in _sample_n(self, n, seed)
    260       else:
    261         batch_shape = self.batch_shape()
--> 262         batch_size = array_ops.reduce_prod(batch_shape)
    263       static_event_shape = self.get_event_shape()
    264       if static_event_shape.is_fully_defined():

AttributeError: 'module' object has no attribute 'reduce_prod'
```
Please see https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/contrib/distributions/python/ops/mixture.py#L262

I believe this is a bug since `reduce_prod` is in `math_ops.py` instead of `array_ops.py`.

I'm using version v0.12.1, but I checked it's the same for r1.0

Thanks

**Comment by mwytock** [comment]
I hit this too.

For others waiting for a fix, monkey patch is a temporary workaround:

```python
# Workaround for https://github.com/tensorflow/tensorflow/issues/7204
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import math_ops
array_ops.reduce_prod = math_ops.reduce_prod
```

**Comment by ebrevdo** [comment]
Working on the fix now.  Will push either tonight or by Tuesday.

**Comment by skye** [comment]
Any update on this? @ebrevdo was this fixed?

**Comment by ebrevdo** [comment]
Yes, someone sent in a PR.  We don't have any unit tests checking this case
sadly.
