### ISSUE TITLE
libcupti.so missing from Docker.gpu

### ISSUE THREAD

**Issue by thesuperzapper** [tensorflow/tensorflow#7207]
### Environment info:
The latest docker GPU image.
`gcr.io/tensorflow/tensorflow:latest-gpu`

### Issue:
While running [mnist_with_summaries.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py), you get 
`tensorflow/stream_executor/dso_loader.cc:119] Couldn't open CUDA library libcupti.so. LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:`

### Temporary Solution:
Adding the path to CUPTI to the LD_LIBRARY_PATH environment variable. 

`export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/extras/CUPTI/lib64"`

### Solution:
Add `ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH` to [Dockerfile.gpu](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.gpu), as in #7206

**Comment by jmchen-g** [comment]
The fix is already merged so closing this...
