### ISSUE TITLE
Tensorflow API doc image is wrong for tf.scatter_*

### ISSUE THREAD

**Issue by fpmchu** [tensorflow/tensorflow#721]
In ```tf.scatter_{add,sub,update}```, the image has ```indices = [0, 2, 5]```, but the arrow suggest it's actually ```[2, 0, 5]```.  We can't help fix it though since the images in the dos are not part of git.

https://www.tensorflow.org/versions/master/api_docs/python/state_ops.html#scatter_update

**Comment by martinwicke** [comment]
I believe this was fixed, @colah can you confirm and close?

**Comment by girving** [comment]
@colah: Should this be closed?

**Comment by girving** [comment]
Posting for @colah: Fixed, so closing.
