### ISSUE TITLE
Tensorflow android does not recognize imported networks(.pb files) with python operations 

### ISSUE THREAD

**Issue by cvmlarun** [tensorflow/tensorflow#7210]
tensorflow android does not recognize operations from an imported network(.pb files) defined/created with python operations  like  recogonize tf.python.ops.FIFOQueue . Works when the network is built/defined with tf.FIFOQueue. Similarly the tensorflow android implementation cribs about unrecognized operation RECIPROCAL when running inference for a network described [here](https://github.com/davidsandberg/facenet/blob/master/src/facenet_train.py)

**Comment by girving** [comment]
@cvmlarun Since code size is precious on Android, we strip out a lot of ops by default.  

@petewarden Is there a clean way of reenabling the ops he wants?  `tf.reciprocal` might be something we want to turn on always.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
