### ISSUE TITLE
Output says inference.so file does not exist when importing tfdf when it exists

### ISSUE THREAD

**Issue by HashemZn-04** [tensorflow/tensorflow#72106]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.15.0

### Custom code

Yes

### OS platform and distribution

Windows 11

### Python version

3.10.0

### Current behavior?

I am trying to use tensorflow and tensorflow decision forests. However, tfdf requires 2.15.0.
I keep getting the error saying inference.so file is not found when it exists

My tfdf version is 1.8.1.
I installed those. Tensorflow 2.15 imports fine, however when importing tfdf i get this error:
`import tensorflow_decision_forests as tfdf`
`
NotFoundError: c:\Users\hashe\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow_decision_forests\tensorflow\ops\inference\inference.so not found`
 

i tried this:
`import os
inference_so_dir = 'C:\\Users\\hashe\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\tensorflow_decision_forests\\tensorflow\\ops\\inference\\inference.so'
os.environ['PATH'] += os.pathsep + inference_so_dir
import tensorflow_decision_forests as tfdf`

i still keep getting the error even when i add the files path 

### Standalone code to reproduce the issue

```shell
import os
inference_so_dir = 'C:\\Users\\hashe\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\tensorflow_decision_forests\\tensorflow\\ops\\inference\\inference.so'
os.environ['PATH'] += os.pathsep + inference_so_dir
import tensorflow_decision_forests as tfdf
```

### Relevant log output

```shell
NotFoundError                             Traceback (most recent call last)
Cell In[9], line 4
      2 inference_so_dir = 'C:\\Users\\hashe\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\tensorflow_decision_forests\\tensorflow\\ops\\inference\\inference.so'
      3 os.environ['PATH'] += os.pathsep + inference_so_dir
----> 4 import tensorflow_decision_forests as tfdf

File c:\Users\hashe\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow_decision_forests\__init__.py:64
     60 from tensorflow_decision_forests.tensorflow import check_version
     62 check_version.check_version(__version__, compatible_tf_versions)
---> 64 from tensorflow_decision_forests import keras
     65 from tensorflow_decision_forests.component import py_tree
     66 from tensorflow_decision_forests.component.builder import builder

File c:\Users\hashe\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow_decision_forests\keras\__init__.py:53
     15 """Decision Forest in a Keras Model.
     16 
     17 Usage example:
   (...)
     48 
     49 """
     51 from typing import Callable, List
---> 53 from tensorflow_decision_forests.keras import core
     54 from tensorflow_decision_forests.keras import wrappers
     56 # Utility classes

File c:\Users\hashe\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow_decision_forests\keras\core.py:62
     60 from tensorflow_decision_forests.component.inspector import inspector as inspector_lib
     61 from tensorflow_decision_forests.component.tuner import tuner as tuner_lib
---> 62 from tensorflow_decision_forests.keras import core_inference
     63 from tensorflow_decision_forests.tensorflow import cc_logging
     64 from tensorflow_decision_forests.tensorflow import core as tf_core

File c:\Users\hashe\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow_decision_forests\keras\core_inference.py:36
     34 from tensorflow_decision_forests.tensorflow import core_inference as tf_core
     35 from tensorflow_decision_forests.tensorflow import tf_logging
---> 36 from tensorflow_decision_forests.tensorflow.ops.inference import api as tf_op
     37 from yggdrasil_decision_forests.learner import abstract_learner_pb2
     38 from yggdrasil_decision_forests.learner.multitasker import multitasker_pb2

File c:\Users\hashe\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow_decision_forests\tensorflow\ops\inference\api.py:179
    177 from tensorflow_decision_forests.component.inspector import inspector as inspector_lib
    178 from tensorflow_decision_forests.tensorflow import tf1_compatibility
--> 179 from tensorflow_decision_forests.tensorflow.ops.inference import op
    180 from yggdrasil_decision_forests.dataset import data_spec_pb2
    181 from yggdrasil_decision_forests.model import abstract_model_pb2

File c:\Users\hashe\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow_decision_forests\tensorflow\ops\inference\op.py:15
      1 # Copyright 2021 Google LLC.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
---> 15 from tensorflow_decision_forests.tensorflow.ops.inference.op_dynamic import *

File c:\Users\hashe\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow_decision_forests\tensorflow\ops\inference\op_dynamic.py:24
     22 except Exception as e:
     23   check_version.info_fail_to_load_custom_op(e, "inference.so")
---> 24   raise e
     26 # Importing all the symbols.
     27 module = sys.modules[__name__]

File c:\Users\hashe\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow_decision_forests\tensorflow\ops\inference\op_dynamic.py:21
     18 import sys
     20 try:
---> 21   ops = tf.load_op_library(resource_loader.get_path_to_datafile("inference.so"))
     22 except Exception as e:
     23   check_version.info_fail_to_load_custom_op(e, "inference.so")

File c:\Users\hashe\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\framework\load_library.py:54, in load_op_library(library_filename)
     31 @tf_export('load_op_library')
     32 def load_op_library(library_filename):
     33   """Loads a TensorFlow plugin, containing custom ops and kernels.
     34 
     35   Pass "library_filename" to a platform-specific mechanism for dynamically
   (...)
     52     RuntimeError: when unable to load the library or get the python wrappers.
     53   """
---> 54   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     55   try:
     56     wrappers = _pywrap_python_op_gen.GetPythonWrappers(
     57         py_tf.TF_GetOpList(lib_handle))

NotFoundError: c:\Users\hashe\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow_decision_forests\tensorflow\ops\inference\inference.so not found
```

**Comment by AbdulQadeer-55** [comment]
To address the issue where the `inference.so` file is not found when importing `tensorflow_decision_forests`, despite the file existing, follow these steps:

1. **Verify the File Path**: Ensure the file path is correct and that `inference.so` is actually located there.

2. **Check File Permissions**: Make sure the file and the directories leading to it have the correct permissions for reading.

3. **Environment Variables**: Ensure the environment variables are set correctly. Sometimes, simply appending the path might not be sufficient.

4. **Reinstall the Package**: There might be a problem with the installation. Reinstalling `tensorflow_decision_forests` could resolve this.

### Steps to Resolve the Issue

1. **Verify File Existence and Path**
   ```python
   import os

   file_path = 'C:\\Users\\hashe\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\tensorflow_decision_forests\\tensorflow\\ops\\inference\\inference.so'
   print(os.path.isfile(file_path))  # This should return True if the file exists
   ```

2. **Check Permissions**
   Ensure that your user account has read permissions for the file and the directories.

3. **Set Environment Variables Properly**
   Instead of appending the path, set the `LD_LIBRARY_PATH` (for Linux) or the `PATH` environment variable directly.
   ```python
   import os

   inference_so_dir = 'C:\\Users\\hashe\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\tensorflow_decision_forests\\tensorflow\\ops\\inference'
   os.environ['PATH'] = inference_so_dir + os.pathsep + os.environ['PATH']

   import tensorflow_decision_forests as tfdf
   ```

4. **Reinstall the Package**
   Uninstall and then reinstall the `tensorflow_decision_forests` package.
   ```sh
   pip uninstall tensorflow_decision_forests
   pip install tensorflow_decision_forests
   ```

5. **Check for Dependencies**
   Ensure all dependencies for `tensorflow_decision_forests` and `inference.so` are installed.
   ```sh
   pip install tensorflow==2.15.0 tensorflow_decision_forests==1.8.1
   ```

6. **Update TensorFlow and TensorFlow Decision Forests**
   Ensure you have the latest compatible versions of TensorFlow and TensorFlow Decision Forests.
   ```sh
   pip install --upgrade tensorflow tensorflow_decision_forests
   ```

### Script to Validate and Import
Here's an example script that includes all the above checks:

```python
import os

# Verify the file exists
file_path = 'C:\\Users\\hashe\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\tensorflow_decision_forests\\tensorflow\\ops\\inference\\inference.so'
if not os.path.isfile(file_path):
    raise FileNotFoundError(f"The file {file_path} does not exist.")

# Set the PATH environment variable
inference_so_dir = 'C:\\Users\\hashe\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\tensorflow_decision_forests\\tensorflow\\ops\\inference'
os.environ['PATH'] = inference_so_dir + os.pathsep + os.environ['PATH']

# Import tensorflow_decision_forests
try:
    import tensorflow_decision_forests as tfdf
    print("Successfully imported tensorflow_decision_forests.")
except Exception as e:
    print(f"Error importing tensorflow_decision_forests: {e}")
```

**Comment by Venkat6871** [comment]
Hi @**HashemZn-04** ,
- I tried to run your code on Colab using TF v2.15 and faced the same issue. And i tried on 2.16.2 then it working fine. Please find the [gist](https://colab.research.google.com/gist/Venkat6871/60ef5be2d7f9492a806ab590e51d801d/72106_2-15-0-2-16-2-v.ipynb) here for reference. Could you please refer [this](https://github.com/tensorflow/decision-forests/issues/210) issue. And please post this issue on https://github.com/tensorflow/[decision-forests](https://github.com/tensorflow/decision-forests) as this issue belongs to decision forests.

Thank you!

**Comment by benjaminlawsUNL** [comment]
Hi!

 I am experiencing the exact problem shown in the initial comment and believe I successfully completed the debugging steps outlined. I have since tried to use tensor flow 2.16.2 as recommended by Venkat in this conversation, but according to the compatibility table found at https://www.tensorflow.org/decision_forests/known_issues, version requires the decision forest version 1.9.2. When I try to pip install this version I get the error 'ERROR: Could not find a version that satisfies the requirement tensorflow_decision_forests==1.9.2 (from versions: 1.8.1)'.

I would be very grateful for any assistance.

Thank you so much,

Ben

**Comment by Gpaio574** [comment]
I tried all the above and checked everything and tried many versions of the related libs but nothing fixed the issue
I even try it in new pc and new vmware and in google colab and same problem with the tf.compat.v1 error
