### ISSUE TITLE
TFLite 2.16.2 and 2.17.0 not present on Maven

### ISSUE THREAD

**Issue by guillaume-tgl** [tensorflow/tensorflow#72157]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.17.0

### Custom code

Yes

### OS platform and distribution

Android

### Current behavior?

Android artifacts haven't been published on Maven

### Standalone code to reproduce the issue

```gradle
implementation("org.tensorflow:tensorflow-lite:2.17.0")
```

**Comment by mihaimaruseac** [comment]
TFLite releases are decoupled from main TF releases, so it would take a little while for them to get uploaded

**Comment by mihaimaruseac** [comment]
I have not worked in TF for over 2 years, just helping with issues here and there

**Comment by pkgoogle** [comment]
@mihaimaruseac thanks! @arfaian, I believe you would have the most insight here. Thanks.

**Comment by kjlee5435** [comment]
Please update 2.17 to maven repos.. please.

**Comment by H4dr1en** [comment]
+1, could you please upload 2.17 to maven?

All `tensorflow-lite`, `tensorflow-lite-gpu`, `tensorflow-lite-gpu-api` and corresponding `tensorflow-lite-gpu-delegate-plugin`, `tensorflow-lite-support` and `tensorflow-lite-metadata` if relevant

**Comment by SnailLiuxc** [comment]
Could you please upload 2.17 to maven? 
our projects are waiting the  so library that are support 16KB page size alignment.

**Comment by asus4** [comment]
According to [this blog](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/), TensorFlow Lite is renamed to LiteRT.

I found the LiteRT 0.1.0 package on Maven, but the internal `TfLiteVersion` was `2.18.0`, assuming it is a nightly build. 

https://central.sonatype.com/artifact/io.github.google-ai-edge/litert

Uploading the TFLite release build to Maven would be better until the migration to LiteRT is complete.

**Comment by liqiang311** [comment]
So, how can I get the latest 2.17 or 2.18 libtensorflowlite_jni.so? Latest version of MVN is 2.16.1.

**Comment by guillaume-tgl** [comment]
> So, how can I get the latest 2.17 or 2.18 libtensorflowlite_jni.so? Latest version of MVN is 2.16.1.

You can use LiteRT instead: https://maven.google.com/web/index.html?q=litert#com.google.ai.edge.litert
It's the replacement for TFLite.

**Comment by pkgoogle** [comment]
Hi @guillaume-tgl, I feel this issue is no longer relevant, do you agree?
