### ISSUE TITLE
Cannot build Tensorflow with XLA, but without GPU support

### ISSUE THREAD

**Issue by DavidNorman** [tensorflow/tensorflow#7216]
I believe it is probably commit 191658d54f90ac03c15b339326129cd52d1f56a3

To be clear, this is when I build without configuring CUDA at the ./configure stage.   I have not tried to configure with CUDA but then build without the --config=cuda.

Here is the final few lines of the build output:
```
out/local-opt/bin/external/png_archive/libpng.pic.a bazel-out/local-opt/bin/external/zlib_archive/libzlib.pic.a -lcublas -lcuda -lcudnn -lcufft -lcurand '' -Wl,-exported_symbols_list tensorflow/tf_exported_symbols.lds -ldl -lm -Wl,-rpath,../local_config_cuda/cuda/lib -Wl,-rpath,../local_config_cuda/cuda/extras/CUPTI/lib -ldl -lpthread -pthread -lm -framework IOKit -lstdc++ -lm -undefined dynamic_lookup -headerpad_max_install_names): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
clang: warning: argument unused during compilation: '-pthread'
ld: file too small (length=0) file 'bazel-out/local-opt/bin/_solib_darwin/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Slib/libcudart.dylib' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

You can see that the cuda libraries are included in the build, and that the linker is complaining that the .so (.dylib) files are empty, which is true.

Maybe this is a problem with the OS/X linker  which might object to empty .so files where other operating systems' linkers do not.

For me,  this is is a high priority issue.

**Comment by DavidNorman** [comment]
Further to the earlier comment, the problem occurs on Linux too. 

```
bazel-out/local-opt/bin/_solib_k8/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Slib/libcudart.so: file not recognized: File truncated
```

**Comment by DavidNorman** [comment]
This is the target that I am building

```
bazel build --verbose_failures --config=opt tensorflow/tools/pip_package:build_pip_package
```

**Comment by hawkinsp** [comment]
I can reproduce the problem on Linux, and I asked the author of that change to take a look.

(We don't have any continuous builds for the combination of XLA enabled and GPU disabled, which is why no-one noticed.)

The easiest workaround would be to install the CUDA libraries and build with GPU enabled. You don't actually need to have a GPU to do this.

**Comment by DavidNorman** [comment]
I've confirmed that undoing the changes to the dependencies in 191658d54f90ac03c15b339326129cd52d1f56a3 will make the build succeed again.

I think that the problem is the target :cuda_platform is referred to in a target called :stream_executor_cuda without being tested for CUDA config.

This is as opposed to its use in the macro tf_cuda_library, where it isn't included when cuda isn't enabled.

The stream_executor_cuda is always included in the gpu_executable and gpu_plugin targets in XLA, which are in turn always included in various other targets that are included in XLA independent of whether CUDA is enabled.

I suspect that either the stream_executor_cuda should be a tf_cuda_library, or something like that.
Or maybe it is the higher targets, like gpu_plugin which should be tf_cuda_library type targets.

**Comment by DavidNorman** [comment]
I don't really want to have to install the CUDA libraries.  However, I can temporarily remove the offending dependencies from stream_executor_cuda while the problem is fixed.  

thanks for the response

**Comment by hawkinsp** [comment]
Sure. I just wanted to make sure you weren't blocked by this issue; it might take a few days to get the fix checked in.

**Comment by DavidNorman** [comment]
no problem.  all ok here.

**Comment by DavidNorman** [comment]
Without those deps, I can build the system, but it is failing to run the unit tests because of a lack of a symbol (__cpu_model) - i'll treat this as a separate problem though

**Comment by yaroslavvb** [comment]
BTW, on MacOS, bazel 0.4.4, you also need to propagate your env with `--action_env` flags, or build process fails with libcuda not found -- 

```
export CUDA_VISIBLE_DEVICES=
export CUDA_HOME=/usr/local/cuda
export DYLD_LIBRARY_PATH=/usr/local/cuda/lib:/usr/local/cuda/extras/CUPTI/lib
export LD_LIBRARY_PATH=$DYLD_LIBRARY_PATH
export PATH=$DYLD_LIBRARY_PATH:$PATH

bazel build --config=cuda --config=opt --action_env PATH --action_env DYLD_LIBRARY_PATH --action_env LD_LIBRARY_PATH

```

**Comment by yaroslavvb** [comment]
btw, building with XLA *with* GPU support is currently blocked by https://github.com/tensorflow/tensorflow/issues/7227

**Comment by jmchen-g** [comment]
Assigned to Peter fow now. Feel free to re-assign. Thanks.

**Comment by hawkinsp** [comment]
This issue was fixed by commit  https://github.com/tensorflow/tensorflow/commit/edc1bf117b88059b92d7500953615f417122950a .
