### ISSUE TITLE
takeing much time to start program? why it happening

### ISSUE THREAD

**Issue by Vinaygoudasp7** [tensorflow/tensorflow#72180]
after converting saved_model format to tflite it taking more time to start inference so plz help me with this and i posted below code so plz help with this and solve problem 

model=tf.saved_model.load(model_path)
 converter=tf.lite.TFLiteConverter.from_saved_model(model_path)
 converter.optimizations=[tf.lite.Optimize.DEFAULT]
 tflite_quant_modle=converter.convert()
tfquant_model_path=pathlib.Path("D:/AIML/Tensorflow_FW/best_saved_model/tfquant_model")
# tfquant_model_path.mkdir(exist_ok=True,parents=True)

tfquant_model_file=tfquant_model_path/"tfquant_model.tflite"
# tfquant_model_file.write_bytes(tflite_quant_modle)

interpreter=tf.lite.Interpreter(model_path=str(tfquant_model_file))

while True:
    frames=read_frames_in_batches(video_path=video_path)
    for frame in frames:
        if frame is not None:
            frame = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
            frame = frame.resize((640, 640))
            frame_nd_array = np.array(frame, dtype=np.float32)
            frame_nd_array = frame_nd_array / 255.0  # Normalize if required by the model
            frame_nd_array = frame_nd_array[None, ...]  # Add batch dimension
            input_tensor_frame = tf.convert_to_tensor(frame_nd_array)  # Convert numpy array to tensor
            
            interpreter.allocate_tensors()
            input_details=interpreter.get_input_details()
            output_details=interpreter.get_output_details()
            interpreter.set_tensor(input_details[0]['index'],input_tensor_frame)
            interpreter.invoke()
            predictions = interpreter.get_tensor(output_details[0]['index'])
            print(predictions)
            # predictions=predictions.numpy()
            frame_array=np.array(frame)
            output_image=postprocess(input_image=frame_array,output=predictions)
            cv2.namedWindow('Detections',cv2.WINDOW_NORMAL)
            cv2.imshow("Detections", cv2.cvtColor(output_image,cv2.COLOR_BGR2RGB))
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

**Comment by tilakrayal** [comment]
@Vinaygoudasp7,
Could you please provide the complete code or the colab gist and the tensorflow version which you are trying to execute the code which helps to analyse the issue in a more effective way. Thank you!
