### ISSUE TITLE
how to install mediapipe_model_maker0.2.1.4 in windows?

### ISSUE THREAD

**Issue by libofei2004** [tensorflow/tensorflow#72198]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf2.8

### Custom code

No

### OS platform and distribution

windows11

### Python version

3.9.13

### Current behavior?

I run "pip install mediapipe_model_maker"  , but I can only install version 0.1.0.1. I was trying to install mediapipe_model_maker by "pip install mediapipe_model_maker-0.2.1.4-py3-none-any.whl", but also failed. The error:
ERROR: Cannot install mediapipe-model-maker and mediapipe-model-maker==0.2.1.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    mediapipe-model-maker 0.2.1.4 depends on tensorflow-text
    tf-models-official 2.15.0 depends on tensorflow-text~=2.15.0
    mediapipe-model-maker 0.2.1.4 depends on tensorflow-text
    tf-models-official 2.14.2 depends on tensorflow-text~=2.14.0
    mediapipe-model-maker 0.2.1.4 depends on tensorflow-text
    tf-models-official 2.14.1 depends on tensorflow-text~=2.14.0
    mediapipe-model-maker 0.2.1.4 depends on tensorflow-text
    tf-models-official 2.14.0 depends on tensorflow-text~=2.14.0
    mediapipe-model-maker 0.2.1.4 depends on tensorflow-text
    tf-models-official 2.13.2 depends on tensorflow-text~=2.13.0I run "pip install mediapipe_model_maker"  ,but I can only install version 0.1.0.1. I was trying to install mediapipe_model_maker by "pip install mediapipe_model_maker-0.2.1.4-py3-none-any.whl", but also failed. The error:
ERROR: Cannot install mediapipe-model-maker and mediapipe-model-maker==0.2.1.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    mediapipe-model-maker 0.2.1.4 depends on tensorflow-text
    tf-models-official 2.15.0 depends on tensorflow-text~=2.15.0
    mediapipe-model-maker 0.2.1.4 depends on tensorflow-text
    tf-models-official 2.14.2 depends on tensorflow-text~=2.14.0
    mediapipe-model-maker 0.2.1.4 depends on tensorflow-text
    tf-models-official 2.14.1 depends on tensorflow-text~=2.14.0
    mediapipe-model-maker 0.2.1.4 depends on tensorflow-text
    tf-models-official 2.14.0 depends on tensorflow-text~=2.14.0
    mediapipe-model-maker 0.2.1.4 depends on tensorflow-text
    tf-models-official 2.13.2 depends on tensorflow-text~=2.13.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Can version 0.2.1.4 be installed in windows?

### Standalone code to reproduce the issue

```shell
pip install mediapipe_model_maker-0.2.1.4-py3-none-any.whl
```

**Comment by libofei2004** [comment]
@pjpratik @pkgoogle @tilakrayal @Venkat6871  Could you please help me to solve my problem?

**Comment by Venkat6871** [comment]
Hi **@libofei2004** ,
- Could you please post this issue on [https://github.com/google-ai-edge/[mediapipe](https://github.com/google-ai-edge/mediapipe)] (https://github.com/google-ai-edge/mediapipe/issues) as this issue belongs to mediapipe.

Thank you!

**Comment by libofei2004** [comment]
@Venkat6871 Yes, I have post the issue on mediapipe page.

**Comment by libofei2004** [comment]
@Venkat6871 Yes, I have post the issue on mediapipe page.

**Comment by Venkat6871** [comment]
Hi **@libofei2004** ,
Closing the issue since it is being tracked in other repo. Please feel free to re-open the issue if necessary.
Thank you!
