### ISSUE TITLE
Mmap of '41' at offset '0' failed with error '22'. on movenet

### ISSUE THREAD

**Issue by jaskarannagi19** [tensorflow/tensorflow#72202]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15

### Custom code

Yes

### Current behavior?

https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/pose_classification.ipynb#scrollTo=48kW1c2F5l1R

I amy trying to run this repo with movenet but I get error.
Mmap of '41' at offset '0' failed with error '22'. on movenet load function. No change has been made. I am running this on colab directly please help

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/pose_classification.ipynb#scrollTo=48kW1c2F5l1R

I amy trying to run this repo with movenet but I get error.
Mmap of '41' at offset '0' failed with error '22'. on movenet load function. No change has been made. I am running this on colab directly please help
```

**Comment by Mejorarsim** [comment]
Yes, getting same issue. Can you resolve please?

**Comment by tilakrayal** [comment]
@jaskarannagi19,
I tried to execute the code and observed that it was executed without any fail/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/ca94c8afd638c92d4d0e2709ac2cb345/copy-of-movenet.ipynb) and also please have a look at the issue for the reference.
https://github.com/tensorflow/tensorflow/issues/70841

Thank you!

**Comment by jaskarannagi19** [comment]
@tilakrayal No I think the code you are refering to has a different tf load method. I am more interested in training that notebook on my own examples. I think there is a problem in model that is not compatible

**Comment by durgas4** [comment]
I got the same error. I replaced the code - 
![image](https://github.com/user-attachments/assets/67c488df-6272-44d6-808f-01d3b80d2252)

I highlighted the changes. The model i donwloaded from the github link-https://github.com/devfemibadmus/human-pose-estimation

or even download tflite models from the kaggle link - https://www.kaggle.com/models/google/movenet/tfLite/singlepose-thunder/1?tfhub-redirect=true

replace the model movenet = Movenet('downloaded model.tflite') with the one downloaded and the code should run fine!


 # Load MoveNet Thunder model
import utils
from data import BodyPart
from ml import Movenet
movenet = Movenet('downloaded model.tflite')

**Comment by jaskarannagi19** [comment]
@durgas4 I think that's what we did followed by change in str() to str()_ in movenetpreprocessor class method to support numpy 1.25.2. 
That notebook does need a new fresh link for the model out of the box link does not work
