### ISSUE TITLE
tf.pow(x,y) doesn't compute complex results

### ISSUE THREAD

**Issue by MicaelCarvalho** [tensorflow/tensorflow#7220]
Slightly related to #7170 

**Operating System:** Debian 4.8.15-2
**Installed version of CUDA:** 8.0
**Installed version of cuDNN:** 5.1.5
**The output of `ls -l /path/to/cuda/lib/libcud*`:**
> myuser@mymachine:/mypath$ ls -l /usr/local/cuda-8.0/lib64/libcud*
> -rw-r--r-- 1 root root 558720 sept. 15 01:02 /usr/local/cuda-8.0/lib64/libcudadevrt.a
> lrwxrwxrwx 1 root root     16 sept. 15 01:05 /usr/local/cuda-8.0/lib64/libcudart.so -> libcudart.so.8.0
> lrwxrwxrwx 1 root root     19 sept. 15 01:05 /usr/local/cuda-8.0/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
> -rw-r--r-- 1 root root 415432 sept. 15 01:02 /usr/local/cuda-8.0/lib64/libcudart.so.8.0.44
> -rw-r--r-- 1 root root 775162 sept. 15 01:02 /usr/local/cuda-8.0/lib64/libcudart_static.a

**A link to the pip package you installed:** Lost in history. I don't think this is the problem, so I'm going to skip it.

**The output from `python -c "import tensorflow; print(tensorflow.__version__)"`:**
> myuser@mymachine:/mypath$ python -c "import tensorflow; print(tensorflow.__version__)"
> I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
> I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
> I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
> I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
> I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
> 0.12.1

**Minimal reproducible example:** (using python3)
```
import tensorflow as tf
session = tf.InteractiveSession()
tf.pow(-83.56,2.0).eval() # this one works fine
tf.pow(-83.56,1.0).eval() # this one works fine
tf.pow(-83.56,1.5).eval() # nan
```

The docs aren't clear whether it should compute complex results or not — but it states the function accepts complex inputs, so I assume returning "nan" is not expected.

**Comment by MicaelCarvalho** [comment]
Note: I'm not sure if this behavior is expected or not — the result would be a complex number

**Comment by yaroslavvb** [comment]
Note that definition of `Pow` op means that all types are the same

```
REGISTER_OP("Pow")
    .Input("x: T")
    .Input("y: T")
    .Output("z: T")
```

`_op_def_lib.apply_op` is not smart enough to figure out that -83.56^1.5 is complex, so that all inputs must also be treated as complex. This is similar https://github.com/tensorflow/tensorflow/issues/7170 and the lesson is that except for a few common special cases, you must specify `dtype` explicitly.

This works

```
a = tf.constant(-83.56, dtype=tf.complex64)
b = tf.constant(1.5, dtype=tf.complex64)
tf.pow(a, b).eval()
```
