### ISSUE TITLE
Linking of rule '@protobuf//:internal/_api_implementation.so' failed:

### ISSUE THREAD

**Issue by qiyuelu1** [tensorflow/tensorflow#7221]
I am trying to build tensorflow v0.12.0 from source with bazel 0.4.3 and failed with this error:

```
ERROR: /ui/ncsa/qiyuelu1/.cache/bazel/_bazel_qiyuelu1/ce8d1fb9ff1b7a9dbbd225fe7f0c6f52/external/protobuf/BUILD:579:1: Linking of rule '@protobuf//:internal/_api_implementation.so' failed: link_dynamic_library.sh failed: error executing command 
  (cd /ui/ncsa/qiyuelu1/.cache/bazel/_bazel_qiyuelu1/ce8d1fb9ff1b7a9dbbd225fe7f0c6f52/execroot/tensorflow-0.12.0 && \
  exec env - \
    LD_LIBRARY_PATH= .......

```
I searched online and found github bazelbuild/bazel #1867 and tensorflow/tensorflow issue #2266, #5617 and #5616, but it seems the changes suggested in these issue have already been implemented in the source code of version 0.12.0. I am not sure why this problem still exists.  

Environment info
Operating System: RHEL 6.8
CUDA: 8.0
cuDNN: 5.1
Java: 1.8.0_112
gcc: 4.9.2
bazel: 0.4.3
tensorflow: v0.12.0 (Latest commit c62a66b on Dec 19, 2016)

### What other attempted solutions have you tried?
I tried tensorflow version 0.12.head and v1.0.1-rc0, both of them can be built successfully. However, we do need this specific version 0.12.0.

**Comment by MicaelCarvalho** [comment]
Have you tried changing the TF_BINARY_URL link to the version 0.12.0? Or do you need that specific commit?

Example:
`# Ubuntu/Linux 64-bit, GPU enabled, Python 3.4
# Requires CUDA toolkit 8.0 and CuDNN v5. For other versions, see "Installing from sources" below.
$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.1-cp34-cp34m-linux_x86_64.whl`

The variable becomes:
`$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.0-cp34-cp34m-linux_x86_64.whl`

And then you just have to follow the installation with pip. ;-)

**Comment by qiyuelu1** [comment]
@MicaelCarvalho Thanks for your response. 
Unfortunately, we need to build this specific version from source because, as we tested, keras, using tensorflow as backend, has some problem with newer (0.12.head) versions. I have to roll back older version like 0.12.0.

**Comment by MicaelCarvalho** [comment]
@qiyuelu1 the proposed approach will install version 0.12.0... if you only need "older version like 0.12.0" it should work; the only situation for which it won't do the job is if you really need _that specific commit_.

**Comment by qiyuelu1** [comment]
@MicaelCarvalho Thanks for your response. Actually, installing binary directly doesn't work for me. I am porting tensorflow on a cluster which is running RHEL 6.8, its default gcc is 4.4.7 (I use 4.9.2 in my build as a module). I have to build from source and make modifications on CROSSTOOL.tpl etc. files, otherwise, will get glibc version complaints.

**Comment by jmchen-g** [comment]
@girving Assign to you mainly because you have comments in the mentioned issues. Feel free to re-assign. Thanks.

**Comment by girving** [comment]
@jmchen-g Please use the who-do-I-notify sheet.  I do not know about build issues.  @martinwicke.

**Comment by r4nt** [comment]
@qiyuelu1 - can you post the full link error you get if you build with -s?

**Comment by qiyuelu1** [comment]
@r4nt Thanks for your response. This problem has been bypassed through updating keras+tensorflow to newer versions. 
Thanks all for your help. I'm gonna close this session.
