### ISSUE TITLE
OS/X doesn't compile Tensorflow

### ISSUE THREAD

**Issue by DavidNorman** [tensorflow/tensorflow#7223]
Not sure of the exact circumstances of this, but I get an undefined symbol when trying to load the _pywrap_tensorflow.so.

The symbol is __cpu_model.  

There is a discussion here about it: https://github.com/numpy/numpy/issues/8530

It seems that the file crc32c_accelerate.cc calls the compiler function `__builtin_cpu_supports`.  While there is a test for the presence of this at the top of the file, there might be a bug in llvm/clang where this function references a symbol called __cpu_model, which isn't compiled into the final .so file.

As a test, I compiled:
```
#include <stdio.h>

main() {
  if (__builtin_cpu_supports("sse4.2")) {
    puts("a");
  }
}
```

and I received:
```
Undefined symbols for architecture x86_64:
  "___cpu_model", referenced from:
      _main in t-2e30e2.o
ld: symbol(s) not found for architecture x86_64
```

My version of clang is:
```
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
```

**Comment by yaroslavvb** [comment]
I wonder this is related github.com/tensorflow/tensorflow/commit/51e5197b

**Comment by DavidNorman** [comment]
Yes - the change occurred in commit 51e5197bb73653609f4100439664123b80126447

**Comment by yaroslavvb** [comment]
cc @martinwicke  to triage to owner of 51e5197b

**Comment by DavidNorman** [comment]
Not sure what the right thing to do is.  Maybe there is a clang inbuilt preprocessor symbol which can be used to disable this on OS/X before some known working version.  or something like that.

**Comment by DavidNorman** [comment]
This is the llvm bug and fix - was a long time ago though...

https://llvm.org/bugs/show_bug.cgi?id=25510

**Comment by vincentvanhoucke** [comment]
In the absence of a good way to test this, we probably won't be able to suggest a fix. If you find a good way to disable it, feel free to send a PR.

**Comment by DavidNorman** [comment]
Thanks - i will.  I think a test for APPLE and a test for the particular compiler major/minor version strings.

**Comment by DavidNorman** [comment]
As noted: I made a fix.  I don't have Sierra, so I don't know if my expression catching the apple compiler is too broad.  however, I will check on that today.

**Comment by DavidNorman** [comment]
Ok - i think the fix was basically right - however it isn't fixed in the system clang 8.0.0 (which is in Sierra). 

See the code around line 370 in https://github.com/darktable-org/darktable/blob/master/src/CMakeLists.txt

This references https://llvm.org/bugs/show_bug.cgi?id=25510

Apparently it is something of an incompatibility between libgcc and clang compiler-rt.  It is mentioned as fixed (Alina Sbirlea 2016-07-18 16:39:15 CDT This should be resolved by r275484.) but I guess it has not made it into apple clang 8.0.0.

I've hunted through the compiler-rt libraries and cannot find the symbol, so I conclude that it isn't in the Apple clang yet.   I think I'll update the patch to rule out apple compilers of major 8 and below.

**Comment by jmchen-g** [comment]
@rmlarsen Assigning to you mainly because you commented in the PR. Feel free to re-assign. Thanks.

**Comment by DavidNorman** [comment]
hi - i notice that you have taken my pull request and the problem is solved.  thanks :)
