### ISSUE TITLE
undefined symbol: clock_gettime on Ubuntu 12.04

### ISSUE THREAD

**Issue by namrathaurs** [tensorflow/tensorflow#7235]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
Almost every possible workarounds and resolutions that are existing for all of the Tensorflow-related issues that have been discussed on GitHub and StackOverflow have been tried, but the issue still persists. Since, I could not find any discussions or fixes with respect to the particular issue that I am encountering, I thought reaching out to you folks would be the best option that is available, as it would help me learn from the developers themselves.

### Environment info
Operating System: Ubuntu 12.04 LTS 64-bit 
Python : 2.7.3 built on GCC 4.6.3
Tensorflow : 0.12.1, CPU-only version

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`): No such file or directory

Since installing from the binary pip package did not work, I tried installing Tensorflow from source, the details of which are provided below :

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`) - b5854872a49172e0502856b60cbaedf0df4df087
2. The output of `bazel version` - 0.4.3

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
~ $ cd /etc
/etc$ python
Python 2.7.3 (default, Oct 26 2016, 21:01:49) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: clock_gettime

Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>> 

### What other attempted solutions have you tried?
The initial point of error was with respect to GLIBC_2.x not being found on my filesystem. With that I started troubleshooting and debugging Tensorflow configuration with the following list of attempted solutions -
1. Upgrade of GCC to v4.9
2. Upgrade of Bazel to v0.4.3
3. Upgrade of protobuf to v
3. Bazel installation via binary installer
4. Bazel installation via Git Repository clone (https://github.com/bazelbuild/bazel.git), followed by a hard reset to a specific HEAD
5. Tensorflow installation via the pip package directly using the .whl file
6. Tensorflow installation via Git Repository clone (https://github.com/tensorflow/tensorflow), followed by a hard reset to a specific HEAD
7. Bazel build with additional options such as --linkopt '-lrt' --copt '-DGPR_BACKWARDS_COMPATIBILITY_MODE' --conlyopt='-std=c99'

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
1. Execution of ./configure fetches all external dependencies successfully
2. During bazel build, massive number of warning messages regarding deprecation show up on the console. However, build completes successfully with building the pip package
3. No errors during bazel-bin execution
4. No errors during the .whl file execution either. Successfully installs Tensorflow 0.12.1 with most of the additional requirements like numpy, protobuf, wheel, werkzeug etc., being satisfied (the .whl file is named 'tensorflow-0.12.1-cp27-cp27mu-linux_x86_64.whl')

I may have missed out on mentioning slight details, but I have tried my best to cover the wide range of fixes that I have been trying on. If in case, you guys have any questions for me, please feel free to reach out as those details might help you better understand the issue being described above.

Just out of curiosity as it caught my eye, I upgraded my GCC to 4.9 as was mentioned in one of the StackOverflow discussion and updated the symlinks to point to the new version. After which, I performed all of the mentioned solutions that I tried. However, I see that my Python interpreter seems to have been compiled with GCC v4.6.3. Would this be causing any kind of issues with the native runtime not being loaded?

Thank you so much for helping us out! Looking forward to hear from your end with your inputs on this.

Adding a fellow colleague @nishithhaa to this discussion as we are facing issues during the configuration and setup of Tensorflow on our machines.

**Comment by yaroslavvb** [comment]
https://github.com/benoitsteiner/tensorflow/commit/d82328afcde4c9c8eac5ea0199f0349d209a6f51 has added dependency on time libraries. I was able to build it on Ubuntu 14.04 and MacOS Sierra. Could it be that Ubuntu 12.04 is missing this function? @aselle  -- what is the official status of support of 12.04?

**Comment by namrathaurs** [comment]
@Carmezim @yaroslavvb 

I did see the comment by @yaroslavvb regarding my issue. But could not see any new answers posted for his comment/question. Is there anything else that you guys would want me to try from my end? If yes, please do let me know. Or, do I just wait to hear from any of you again?

I may be a little on my toes needing help. But, just getting used to GitHub and how you all work with it. Pardon my naivety here, if found or felt.

Thanks for your help, as always!

**Comment by yaroslavvb** [comment]
@b0nol in case he has some insight about clock_gettime portability

**Comment by jart** [comment]
Thanks for reaching out @namrathaurs. The TensorFlow team is committed to supporting Ubuntu Linux 14 LTE to 16. Ubuntu 12.04 isn't in our support matrix. That release is actually going to be EOL in two months. The Ubuntu team is going to stop creating security updates for your system. Please consider upgrading as soon as possible.

**Comment by justinkterry** [comment]
FYI this occurs with the GPU version on ubuntu 18.04
