### ISSUE TITLE
tf.range miss some dtypes support

### ISSUE THREAD

**Issue by shkarupa-alex** [tensorflow/tensorflow#72365]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

v1.12.1-113444-ga98a073af6f 2.18.0-dev20240722

### Custom code

No

### OS platform and distribution

Google Colab

### Python version

Google Colab default

### Current behavior?

It is a common use case to make ranges for dtypes like uint8 (when working with images) and float32 -> float16 (inside keras layers with mixed precision disabled/enabled).

In TF 2.17 release tf.range can't work with these dtypes.
One more issue is that XLA/non-XLA dtypes support is different (more dtypes supported with XLA)

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

tf.range(10., delta=1., dtype='float16')
```

### Relevant log output

```shell
NotFoundError: Could not find device for node: {{node Range}} = Range[Tidx=DT_HALF]
All kernels registered for op Range:
  device='XLA_CPU_JIT'; Tidx in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_INT16, DT_INT8, DT_INT64, DT_BFLOAT16, DT_UINT16, DT_HALF, DT_UINT32]
  device='XLA_GPU_JIT'; Tidx in [DT_FLOAT, DT_DOUBLE, DT_INT32, DT_INT16, DT_INT8, DT_INT64, DT_BFLOAT16, DT_UINT16, DT_HALF, DT_UINT32]
  device='DEFAULT'; Tidx in [DT_INT32]
  device='GPU'; Tidx in [DT_INT64]
  device='GPU'; Tidx in [DT_DOUBLE]
  device='GPU'; Tidx in [DT_FLOAT]
  device='CPU'; Tidx in [DT_INT64]
  device='CPU'; Tidx in [DT_INT32]
  device='CPU'; Tidx in [DT_DOUBLE]
  device='CPU'; Tidx in [DT_FLOAT]
 [Op:Range] name:
```

**Comment by Venkat6871** [comment]
- I tried to run your code on Colab using TF v2.17.0, nightly and faced the same issue. Please find the [gist](https://colab.research.google.com/gist/Venkat6871/aee3cbcaae3ee68fa8de6cd259a4b5e4/72365_2-17-0-nightly.ipynb) here for reference.

Thank you!
