### ISSUE TITLE
How to use Tensorflow in my android project?

### ISSUE THREAD

**Issue by orhan-v** [tensorflow/tensorflow#7242]
I am working on a project, where I change the View with a button (working with Fragments). I am changing between a FirstFragment and a CamFragment. Now I want to use Tensorflow (it works on my phone) instead of CamFragment.

When I "import new Module", I get Errors only. Do you have any Tips or solutions how I can do that?

Thank You

**Comment by andrewharp** [comment]
Thanks for you interest in TensorFlow, but for general TF usage and Android development questions we recommend that you ask on StackOverflow (I believe I responded to your question there; can't find it now though).
