### ISSUE TITLE
OutOfRangeError on FIFOQueues of different experiments

### ISSUE THREAD

**Issue by vatlidak** [tensorflow/tensorflow#7245]
Hi,

I am running some experiments with Tensorflow on a 4-GPU machine using CIFAR10 with the FIFOQueue implementation for input data pipeline. 

I want to simultaneously run one different instance of my experiment on each of the four GPUs,
but because the data processing queues are always places on the CPU I get an OutOfRange error and
cannot run more than one instance per machine.

Is there a way to overcome this? (other than placing the data processing on GPUs)

Thanks

**Comment by yaroslavvb** [comment]
Hi, could you please ask this on stackoverflow? We are trying to keep this list for tensorflow bugs/feature requests

**Comment by vatlidak** [comment]
Okay
