### ISSUE TITLE
Distributed Training without strategies- can't average gradients

### ISSUE THREAD

**Issue by Apprisco** [tensorflow/tensorflow#72477]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.17

### Custom code

Yes

### OS platform and distribution

Ubuntu Server

### Python version

3.12

### Current behavior?

I'm trying to not use a tf.dataset for a distributed learning scenario. As such, using MirroredStrategy is out of the question.
However, I can replicate MirroredStrategy by creating multiple instances of my model, one for each GPU.
And I can gather gradients and manually send batches to each model using said method.
However, once I received all the gradients from tf.gradients(), I am unable to average them. I tried tf.stack, converting to np, etc, but they all fail due to dimensions being different within the gradient itself. Each model gives the correct gradient back for each batch, but as I'm unable to average them I am unable to train the model on multiple gpus.

I'm not sure how I'm supposed to average/accumulate gradients between each GPU, and unsure how mirroredstrategy achieves this.

### Standalone code to reproduce the issue

```shell
print('Gen gradients obtained from '+str(len(gen_grads))+' gpus')
                print('Disc gradients obtained from '+str(len(disc_grads))+' gpus')
                print(gen_grads)
                print(disc_grads)
                with tf.device('/gpu:'+self.gpus[0]):
                    gen_grad=zip(*gen_grads)
                    print(gen_grad)
                    gen_grad=tf.reduce_mean(tf.stack(gen_grads),axis=0)
                    disc_grad=tf.reduce_mean(tf.stack(disc_grad),axis=0)
                    print(tf.shape(gen_grad))
                    print(tf.shape(gen_grads[0]))
                for idx,model in enumerate(self.models):
                    gpu=self.gpus[idx]
                    with tf.device('/gpu:'+gpu):
                        model.opt_gen.apply_gradients(zip(gen_grad,model.gen_model.trainable_weights))
                        model.opt_disc.apply_gradients(zip(disc_grad,model.disc_model.trainable_weights))
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/data/scratch/apprisco/FREDSR_UG/final_vdsr/final_run.py", line 192, in <module>
    run.train(100)
  File "/data/scratch/apprisco/FREDSR_UG/final_vdsr/final_run.py", line 134, in train
    gen_grad=tf.reduce_mean(tf.stack(gen_grads),axis=0)
                            ^^^^^^^^^^^^^^^^^^^
  File "/data/scratch/apprisco/miniconda3/envs/TF/lib/python3.12/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/data/scratch/apprisco/miniconda3/envs/TF/lib/python3.12/site-packages/tensorflow/python/framework/ops.py", line 5983, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__Pack_N_160_device_/job:localhost/replica:0/task:0/device:GPU:4}} Shapes of all inputs must match: values[0].shape = [5,5,3,16] != values[1].shape = [16] [Op:Pack] name: 0
```

**Comment by tilakrayal** [comment]
@Apprisco,
Could you please share colab link or simple standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thank you!
