### ISSUE TITLE
error: 'NPY_NTYPES' was not declared in this scope; did you mean 'NPY_TYPES'?

### ISSUE THREAD

**Issue by 6eanut** [tensorflow/tensorflow#72480]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.13.0

### Custom code

Yes

### OS platform and distribution

Linux openeuler-riscv-4-2 6.6.0

### Python version

3.11.6

### Bazel version

5.3.0

### GCC/compiler version

12.3.1

### CUDA/cuDNN version

no

### GPU model and memory

no

### Current behavior?

I am trying to build TensorFlow2.13.0 on aarch64 with bazel5.3.0, but there are problems during the build process：
```
ERROR: /home/tf2130/tensorflow/tensorflow/python/lib/core/BUILD:272:11: Compiling tensorflow/python/lib/core/ndarray_tensor.cc failed: (Exit 1): gcc failed: error executing command /usr/lib64/ccache/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 455 arguments skipped)
tensorflow/python/lib/core/ndarray_tensor.cc: In function 'const char* tensorflow::{anonymous}::numpy_type_name(int)':
tensorflow/python/lib/core/ndarray_tensor.cc:70:15: error: 'NPY_NTYPES' was not declared in this scope; did you mean 'NPY_TYPES'?
   70 |     TYPE_CASE(NPY_NTYPES);
      |               ^~~~~~~~~~
tensorflow/python/lib/core/ndarray_tensor.cc:43:8: note: in definition of macro 'TYPE_CASE'
   43 |   case s:            \
      |        ^
tensorflow/python/lib/core/ndarray_tensor.cc: In function 'tsl::Status tensorflow::{anonymous}::PyArrayDescr_to_TF_DataType(PyArray_Descr*, TF_DataType*)':
tensorflow/python/lib/core/ndarray_tensor.cc:87:14: error: 'PyArray_Descr' has no member named 'fields'
   87 |   if (descr->fields == nullptr) {
      |              ^~~~~~
tensorflow/python/lib/core/ndarray_tensor.cc:91:26: error: 'PyArray_Descr' has no member named 'fields'
   91 |   if (PyDict_Next(descr->fields, &pos, &key, &value)) {
      |                          ^~~~~~
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 29719.590s, Critical Path: 550.42s
INFO: 13738 processes: 1412 internal, 12326 local.
FAILED: Build did NOT complete successfully
```

### Standalone code to reproduce the issue

```shell
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout tags/v2.13.0
bazel build //tensorflow/tools/pip_package:build_pip_package --local_ram_resoues=1024 --jobs=6
```

**Comment by tilakrayal** [comment]
@6eanut,
Could you please try to install the tensorflow with the compatible tested build configurations.
tensorflow-2.13.0, python-	3.8-3.11,	Clang 16.0.0,	Bazel 5.3.0, cuDNN-8.6, CUDA-11.8
https://www.tensorflow.org/install/source#gpu

And tensorflow v2.13 is an old version, please try to install  with the latest tensorflow version. Thank you!

**Comment by 6eanut** [comment]
@tilakrayal thanks for helping!
I did configure the tool according to the corresponding version, but I still encountered the above problem

**Comment by twinsant** [comment]
same error

**Comment by tilakrayal** [comment]
Could you please check whether the same issue you are facing with the latest Tensorflow v2.17 or v2.18 and provide the update where the supported python version has been upgraded to 3.9-3.12.

https://www.tensorflow.org/install/source#cpu
Thank you!
