### ISSUE TITLE
A KerasTensor is symbolic: it's a placeholder for a shape an a dtype. It doesn't have any actual numerical value. You cannot convert it to a NumPy array.

### ISSUE THREAD

**Issue by pradeep10kumar** [tensorflow/tensorflow#72497]
I am using following version: 

TF Version:  2.18.0-dev20240716
Eager mode:  True
Hub version:  0.16.1

While create the model I am facing the follwoing problem. I tried different version but it did not help.

---------------------------------------------------------------------------ValueError                                Traceback (most recent call last)
Cell In [23], line 1----> 1 model = create_model()      2 model.compile(optimizer = tf.keras.optimizers.Adam(learning_rate=2e-5),      3              loss= tf.keras.losses.CategoricalCrossentropy(),      4              metrices = [tf.keras.metrics.Accuracy])      5 model.summary()

Cell In [22], line 10, in create_model()      5 input_mask = tf.keras.layers.Input(shape=(max_seq_length,), dtype=tf.int32,      6                                    name="input_mask")      7 input_type_ids = tf.keras.layers.Input(shape=(max_seq_length,), dtype=tf.int32,      8                                     name="input_type_ids")---> 10 pooled_output, sequence_output = bert_layer([input_word_ids, input_mask, input_type_ids])     11 drop =  tf.keras.layers.Dropout(0.2)(pooled_output)     12 output = tf.keras.Dense(label_list, activation = 'sigmoid', name = "output")(drop)

File ~\AppData\Roaming\Python\Python310\site-packages\tf_keras\src\utils\traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)     67     filtered_tb = _process_traceback_frames(e.__traceback__)     68     # To get the full stack trace, call:     69     # `tf.debugging.disable_traceback_filtering()`---> 70     raise e.with_traceback(filtered_tb) from None     71 finally:     72     del filtered_tb

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow_hub\keras_layer.py:250, in KerasLayer.call(self, inputs, training)    247   else:    248     # Behave like BatchNormalization. (Dropout is different, b/181839368.)    249     training = False--> 250   result = smart_cond.smart_cond(training,    251                                  lambda: f(training=True),    252                                  lambda: f(training=False))    254 # Unwrap dicts returned by signatures.    255 if self._output_key:

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow_hub\keras_layer.py:252, in KerasLayer.call.<locals>.<lambda>()    247   else:    248     # Behave like BatchNormalization. (Dropout is different, b/181839368.)    249     training = False    250   result = smart_cond.smart_cond(training,    251                                  lambda: f(training=True),--> 252                                  lambda: f(training=False))    254 # Unwrap dicts returned by signatures.    255 if self._output_key:

File ~\AppData\Roaming\Python\Python310\site-packages\tensorflow\core\function\polymorphism\function_type.py:583, in canonicalize_to_monomorphic(args, kwargs, default_values, capture_types, polymorphic_type)    577       parameters.append(    578           _make_validated_mono_param(kwarg_name, arg[kwarg_name],    579                                      Parameter.KEYWORD_ONLY, type_context,    580                                      poly_parameter.type_constraint))    581   else:    582     parameters.append(--> 583         _make_validated_mono_param(name, arg, poly_parameter.kind,    584                                    type_context,    585                                    poly_parameter.type_constraint))    587 return FunctionType(parameters, capture_types), type_context

File ~\AppData\Roaming\Python\Python310\site-packages\tensorflow\core\function\polymorphism\function_type.py:522, in _make_validated_mono_param(name, value, kind, type_context, poly_type)    518 def _make_validated_mono_param(    519     name, value, kind, type_context, poly_type    520 ) -> Parameter:    521   """Generates and validates a parameter for Monomorphic FunctionType."""--> 522   mono_type = trace_type.from_value(value, type_context)    524   if poly_type and not mono_type.is_subtype_of(poly_type):    525     raise TypeError(f"Parameter `{name}` was expected to be of type "    526                     f"{poly_type} but is {mono_type}")

File ~\AppData\Roaming\Python\Python310\site-packages\tensorflow\core\function\trace_type\trace_type_builder.py:162, in from_value(value, context)    159   return from_value(value.__wrapped__, context)    161 if isinstance(value, list):--> 162   return default_types.List(*(from_value(c, context) for c in value))    164 if isinstance(value, tuple):    165   if util.is_namedtuple(value):

File ~\AppData\Roaming\Python\Python310\site-packages\tensorflow\core\function\trace_type\trace_type_builder.py:162, in <genexpr>(.0)    159   return from_value(value.__wrapped__, context)    161 if isinstance(value, list):--> 162   return default_types.List(*(from_value(c, context) for c in value))    164 if isinstance(value, tuple):    165   if util.is_namedtuple(value):

File ~\AppData\Roaming\Python\Python310\site-packages\tensorflow\core\function\trace_type\trace_type_builder.py:185, in from_value(value, context)    178   return default_types.Attrs.from_type_and_attributes(    179       type(value),    180       tuple(    181           from_value(getattr(value, a.name), context)    182           for a in value.__attrs_attrs__))    184 if util.is_np_ndarray(value):--> 185   ndarray = value.__array__()    186   return default_types.TENSOR(ndarray.shape, ndarray.dtype)    188 if isinstance(value, custom_nest_protocol.CustomNestProtocol):

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\backend\common\keras_tensor.py:61, in KerasTensor.__array__(self)     60 def __array__(self):---> 61     raise ValueError(     62         "A KerasTensor is symbolic: it's a placeholder for a shape "     63         "an a dtype. It doesn't have any actual numerical value. "     64         "You cannot convert it to a NumPy array."     65     )

ValueError: Exception encountered when calling layer 'keras_layer' (type KerasLayer).

A KerasTensor is symbolic: it's a placeholder for a shape an a dtype. It doesn't have any actual numerical value. You cannot convert it to a NumPy array.

Call arguments received by layer 'keras_layer' (type KerasLayer):
  • inputs=['<KerasTensor shape=(None, 256), dtype=int32, sparse=None, name=input_word_ids>', '<KerasTensor shape=(None, 256), dtype=int32, sparse=None, name=input_mask>', '<KerasTensor shape=(None, 256), dtype=int32, sparse=None, name=input_type_ids>']
  • training=None

**Comment by Venkat6871** [comment]
Hi **@pradeep10kumar** ,
- Make sure the bert_layer is properly loaded and initialized. If it's a TensorFlow Hub layer, ensure it's correctly set up. And In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here.

Thank you!

**Comment by muhammadanas0716** [comment]
import tensorflow as tf
import tensorflow_hub as hub

# Define IMAGE_SHAPE
IMAGE_SHAPE = (224, 224)

def create_model(model_url, num_classes=10):
    """
    Takes a TensorFlow Hub URL and creates a Keras model with it using the functional API.

    Args:
        model_url (str): A TensorFlow Hub feature extraction URL.
        num_classes (int): Number of output neurons in the output layer,
          should be equal to number of target classes, default 10.

    Returns:
        An uncompiled Keras model with model_url as feature extractor
        layer and Dense output layer with num_classes output neurons.
    """
    # Download the pretrained model and save it as a Keras layer
    feature_extractor_layer = hub.KerasLayer(model_url,
                                             trainable=False,  # freeze the already learned patterns
                                             input_shape=IMAGE_SHAPE + (3,))
    # Define the input layer
    inputs = tf.keras.Input(shape=IMAGE_SHAPE + (3,))
    # Pass the inputs through the feature extractor layer
    x = feature_extractor_layer(inputs)  # Explicitly set training=False
    # Define the output layer
    outputs = tf.keras.layers.Dense(num_classes, activation="softmax")(x)

    # Create the model
    model = tf.keras.Model(inputs=inputs, outputs=outputs)

    return model

# Example usage
# Ensure you have a valid URL and the required data
resnet_url = "https://tfhub.dev/google/imagenet/resnet_v2_50/feature_vector/5"
num_classes = 10  # For example purposes
resnet_model = create_model(resnet_url, num_classes=num_classes)

# Print the model summary to verify
resnet_model.summary()

**Comment by ssimrandr** [comment]
I am also facing a similar issue with the later TF versions. The same code runs without errors on TF 2.10.0, but with 2.16.1 throws this error.
---------------------------
ValueError: Exception encountered when calling layer 'autoregressive_network' (type AutoregressiveNetwork).

A KerasTensor cannot be used as input to a TensorFlow function. A KerasTensor is a symbolic placeholder for a shape and dtype, used when constructing Keras Functional models or Keras Functions. You can only use it as input to a Keras layer or a Keras operation (from the namespaces `keras.layers` and `keras.operations`). You are likely doing something like:

```
x = Input(...)
...
tf_fn(x)  # Invalid.
```

What you should do instead is wrap `tf_fn` in a layer:

```
class MyLayer(Layer):
    def call(self, x):
        return tf_fn(x)

x = MyLayer()(x)
```


Call arguments received by layer 'autoregressive_network' (type AutoregressiveNetwork):
  • x=<KerasTensor shape=(None, 2), dtype=float

--------------

Can someone else try this code given here : https://www.tensorflow.org/probability/api_docs/python/tfp/bijectors/AutoregressiveNetwork

---------------
# Generate data -- as in Figure 1 in [Papamakarios et al. (2017)][2]).
n = 2000
x2 = np.random.randn(n).astype(dtype=np.float32) * 2.
x1 = np.random.randn(n).astype(dtype=np.float32) + (x2 * x2 / 4.)
data = np.stack([x1, x2], axis=-1)

# Density estimation with MADE.
made = tfb.AutoregressiveNetwork(params=2, hidden_units=[10, 10])

distribution = tfd.TransformedDistribution(
    distribution=tfd.Sample(tfd.Normal(loc=0., scale=1.), sample_shape=[2]),
    bijector=tfb.MaskedAutoregressiveFlow(made))

# Construct and fit model.
x_ = tfkl.Input(shape=(2,), dtype=tf.float32)
log_prob_ = distribution.log_prob(x_)
model = tfk.Model(x_, log_prob_)

model.compile(optimizer=tf.optimizers.Adam(),
              loss=lambda _, log_prob: -log_prob)

batch_size = 25
model.fit(x=data,
          y=np.zeros((n, 0), dtype=np.float32),
          batch_size=batch_size,
          epochs=1,
          steps_per_epoch=1,  # Usually `n // batch_size`.
          shuffle=True,
          verbose=True)

# Use the fitted distribution.
distribution.sample((3, 1))
distribution.log_prob(np.ones((3, 2), dtype=np.float32))
-----------------------

I am trying to understand if this is a genuine error or due to some installation problems on my end.

**Comment by Venkat6871** [comment]
Hi **@muhammadanas0716** , **@ssimrandr** ,
Could you please raise a new issue for your concern, so that it will be easier to track.
Hi @pradeep10kumar ,
Please try to provide the code snippet as I requested above.
Thank you!
