### ISSUE TITLE
Packages in ~/tensorflow/tensorflow/models/image

### ISSUE THREAD

**Issue by jkschin** [tensorflow/tensorflow#725]
If we take a look at perhaps ~/tensorflow/tensorflow/models/image/cifar10/cifar10_train.py, there's a line

from tensorflow.models.image.cifar10 import cifar10

This works perfectly, and since there's a __init__.py in each directory, it can be seen as somewhat a package. When I try to create my own projects in this directory, it does not work. For example:

~/tensorflow/tensorflow/models/image/my_project/, such that

my_project/
    __init__.py
    code1.py
    code2.py

When I try to do the following in code1.py, it does not work:

from tensorflow.models.image.my_project import code2

*Another interesting to note, is that deleting all __init__.py in the various directories still allow tensorflow.models.image.cifar10 import cifar10 to work. There's something more to this that I'm not getting. Does anyone have this problem too?

**P.S. The init has two underscores in front and behind, the markdown removes it.

**Comment by cesarsalgado** [comment]
Maybe the tensorflow dir you are talking about is not the same as the one tensorflow is actually using. I also think this kind of question is better suited to stackoverflow: https://stackoverflow.com/questions/tagged/tensorflow

**Comment by jkschin** [comment]
It's the same dir I believe. Alright I'll close this and put the question in stackoverflow.
