### ISSUE TITLE
TensorFlow Tutorials not compatible with latest release.

### ISSUE THREAD

**Issue by Ayman250** [tensorflow/tensorflow#72520]
Until the docs are updated and the Colab backend is upgraded to use the latest TensorFlow version, please flag the tutorials that are not compatible with the latest stable release so it's clear to users with the latest version that they must either rollback or modify their scripts to user Keras 2 to follow the tutorials as they are.

**Comment by tilakrayal** [comment]
@Ayman250,
Thank you for reporting the issue. Could you please provide tensorflow tutorial examples where you are facing the issue in the execution. Thank you!

**Comment by Ayman250** [comment]
Here is one example:
[https://www.tensorflow.org/tutorials/load_data/pandas_dataframe](https://www.tensorflow.org/tutorials/load_data/pandas_dataframe)

Running tensorflow v 2.17.0 there is an error on the line:
```normalizer.adapt(numeric_features)```
```local variable 'input_shape' referenced before assignment```

You need to convert this to a tensor first it cannot be done implicitly.
```numeric_features_tensor = tf.convert_to_tensor(numeric_features)```

There are likely more issues downstream in this tutorial.

**Comment by mihaimaruseac** [comment]
In the past, documentation was tested before the final release. It seems now that step has been skipped.
