### ISSUE TITLE
tf.reshape() of a tensor with an unknown dimension (None) does not seem to work

### ISSUE THREAD

**Issue by akdeoras** [tensorflow/tensorflow#7253]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/fchollet/keras/issues/4302

### Environment info
Operating System: Mac (CPU)

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.12.1

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
`input = tf.placeholder(dtype=tf.float32, shape=(None, 2, 3))
input_flattened = tf.reshape(input, shape=[input.get_shape()[0].value, -1])

with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    input_val, input_flattened_val = \
        sess.run([input, input_flattened], feed_dict={input: np.random.random(24).reshape(4, 2, 3)})
    print input_val
    print input_flattened_val`

TypeErrorTraceback (most recent call last)<ipython-input-36-99d32472c9da> in <module>()
      1 input = tf.placeholder(dtype=tf.float32, shape=(None, 2, 3))
----> 2 input_flattened = tf.reshape(input, shape=[input.get_shape()[0].value, -1])
      3 
      4 with tf.Session() as sess:
      5     init = tf.global_variables_initializer()
/Users/adeoras/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.pyc in reshape(tensor, shape, name)
   2446   """
   2447   result = _op_def_lib.apply_op("Reshape", tensor=tensor, shape=shape,
-> 2448                                 name=name)
   2449   return result
   2450 
/Users/adeoras/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.pyc in apply_op(self, op_type_name, name, **keywords)
    491           except TypeError as err:
    492             if dtype is None:
--> 493               raise err
    494             else:
    495               raise TypeError(
TypeError: Expected binary or unicode string, got None

### What other attempted solutions have you tried?
None

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by girving** [comment]
`tf.reshape` takes a tensor of ints as the shape argument.  You are passing None, so it doesn't work.  Maybe you want to replace `x.get_shape()[0]` with `tf.shape(x)[0]`?

**Comment by evanthebouncy** [comment]
Does that mean doing reshaping with variable batch size is not possible then? Often I have input of shape [None, other_dims] and if I want to reshape the "other_dims" into a different shape I cannot do it?

**Comment by girving** [comment]
`tf.shape(x)[0]` gives a scalar tensor with the variable batch size.  Try passing it to reshape.

**Comment by prashnani** [comment]
using `tf.shape(x)` worked for me! Thanks.

**Comment by Faur** [comment]
It is also possible to use `tf.stack` to convert a list into a tensor

**Comment by SMZCC** [comment]
- I have successfully used tf.shape()[0] to flat a  tensor with  none dim  as a vector, thanks
```python
tensor_vector = tf.reshape(tensor=some_tensor, shape=(-1, tf.shape(some_tensor)[1]*tf.shape(some_tensor)[2])
```
- however , I want to connect a full connected layer behind the  `tensor_vector`, so I have to define the weight matrix's shape, then the contradiction is occurred ,because when I　using the `wshape = (tf.shape(some_tensor)[1] *tf.shape(some_tensor)[２] , 1000)` to define the weight matrix , the error is that the dim of the weight matrix must be an integer not a tensor,  however ,the dim I have to use tf.shape(some_tensor) to get which is a tensor ,so ,how can I　solve it ?

**Comment by USTClj** [comment]
Group normalization in keras with tf backend need to handle the reshape consists of None dimension.

**Comment by hujinsen** [comment]
> `tf.reshape` takes a tensor of ints as the shape argument. You are passing None, so it doesn't work. Maybe you want to replace `x.get_shape()[0]` with `tf.shape(x)[0]`?

Thanks a lot. tf.shape() works for me

**Comment by sanjay235** [comment]
```
def generator(x):
  weights['gen_inp'] = tf.Variable(xavier_init([100, 256]))
  bias['gen_inp'] = tf.Variable(xavier_init([256]))

  inp = tf.nn.relu(tf.add(tf.matmul(x, weights['gen_inp']), bias['gen_inp']))
  print(inp.shape,)
  
  inp = tf.reshape(inp, shape=tf.TensorShape([tf.shape(inp)[0], 16, 16, 1]))

  conv_1 = tf.nn.relu(gen_new_conv_layer(x, num_input_channels = 1, filter_size = 4,\
                                     num_filters = 1024, name='gen_conv_1', weights_dict = weights, bias_dict = bias))
  
  conv_2 = tf.nn.relu(gen_new_conv_layer(conv_1, num_input_channels = 1024, filter_size = 8,\
                                     num_filters = 512, name='gen_conv_2', weights_dict = weights, bias_dict = bias))
  
  conv_3 = tf.nn.relu(gen_new_conv_layer(conv_2, num_input_channels = 512, filter_size = 16,\
                                     num_filters = 256, name='gen_conv_3', weights_dict = weights, bias_dict = bias))
  
  conv_4 = tf.nn.relu(gen_new_conv_layer(conv_3, num_input_channels = 256, filter_size = 32,\
                                     num_filters = 128, name='gen_conv_4', weights_dict = weights, bias_dict = bias))
  
  gen_output = tf.nn.tanh(gen_new_conv_layer(conv_4, num_input_channels = 128, filter_size = 64,\
                                         num_filters = 3, name='gen_conv_5', weights_dict = weights, bias_dict = bias))

  return gen_output

z_input = tf.placeholder(tf.float32, [None, z_noise_dim], name='NoiseInput')
x_input = tf.placeholder(tf.float32, [None, img_wid, img_hei, input_channels], name='RealInput')

with tf.name_scope('Generator') as scope:
  output_gen = generator(z_input)
```

is giving error as,

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-27-27084685abe1> in <module>()
     48 
     49 with tf.name_scope('Generator') as scope:
---> 50   output_gen = generator(z_input)

4 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/tensor_shape.py in __init__(self, value)
    191       raise TypeError("Cannot convert %s to Dimension" % value)
    192     else:
--> 193       self._value = int(value)
    194       if (not isinstance(value, compat.bytes_or_text_types) and
    195           self._value != value):

TypeError: int() argument must be a string, a bytes-like object or a number, not 'Tensor'
```
