### ISSUE TITLE
Multi-GPU training drastically slow after recent commit

### ISSUE THREAD

**Issue by rohitgirdhar** [tensorflow/tensorflow#7255]
I recently upgraded to the latest master, in order to fix the issues caused by this bug: https://github.com/tensorflow/tensorflow/issues/7038
Though the above fix does resolve the issue of same batch being pulled from the GPU, now my model training has become drastically slow (> 4x), and most time is being spent in dequeues. A timeline snapshot is here:

![screenshot from 2017-02-03 18-43-55](https://cloud.githubusercontent.com/assets/1893429/22612749/be748f0c-ea40-11e6-9efb-989b9466301a.png)

Any ideas as to what might be going wrong?

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/tensorflow/tensorflow/issues/7038

### Environment info
Operating System: CentOS 6.5

Installed version of CUDA and cuDNN: 8.0.27 and 5.1
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

1. The commit hash (`git rev-parse HEAD`): 084b37a00f3cf2cc89d433528ca63ec1d3b5b313
2. The output of `bazel version`
```
Build label: 0.4.3- (@non-git)
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Dec 23 16:35:28 2016 (1482510928)
Build timestamp: 1482510928
Build timestamp as int: 1482510928
```

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
My code is based on the tensorflow/models/slim interface

**Comment by yaroslavvb** [comment]
It seems crux of the fix in that issue is to set `stateful` property to true, any chance you can change it to read ` op_def->set_is_stateful(false);` and see if this fixes things?

https://github.com/tensorflow/tensorflow/commit/06e3aa655506773e49ce9a855f81ba3eae2a6b88#diff-333845d139890198962551b3a1c2a33b

**Comment by yaroslavvb** [comment]
PS, spending time in dequeues can mean that you have queue starvation, so it's really the `.run` call which enqueues to your queue that is slow. So you should make sure your `queue.size()` is always above batch size, and if not, profile your enqueue `.run` call. Here's an example of similar issue https://github.com/tensorflow/tensorflow/issues/6845

**Comment by rohitgirdhar** [comment]
@yaroslavvb I changed `tensorflow/core/framework/op_def_builder.cc` Line 379 (true->false). Now my code gives a segmentation fault after it prints "INFO:tensorflow:Starting Queues." (I'm using the slim models)..

**Comment by rohitgirdhar** [comment]
I changed the line in `tensorflow/core/framework/op_def_builder.cc`, L379 (true->false). Now I'm getting a segmentation fault with my code, right after it prints `INFO:tensorflow:Starting Queues.`. Maybe there has been some other change in the last few days that conflicts with this...?

**Comment by rohitgirdhar** [comment]
I downgraded my tensorflow installation to 0.12.1 release (4d924e796368163eff11a8151e8505715345f58d)
After the required API changes, my code seemed to run at a similar speed as I'm seeing with the latest head. So it might be possible that last few weeks I've been running it with the optimization bug with made it 4x faster (by copying the same batch onto all 4 GPUs), and the slowdown I'm seeing now is actually the expected speed given the amount of I/O I'm doing.

I'll debug some more on this, but thanks for the pointers and quick response, @yaroslavvb

**Comment by ppwwyyxx** [comment]
FYI, on my side it runs faster with the bug as well, because it reused the same data 4 times.

**Comment by yaroslavvb** [comment]
![picard12](https://cloud.githubusercontent.com/assets/23068/22631578/c203add0-ebc4-11e6-8a97-8658e8964870.png)

**Comment by rohitgirdhar** [comment]
The meme probably explains the situation here :p Closing the issue.
