### ISSUE TITLE
couldn't find "libtensorflow_demo.so"

### ISSUE THREAD

**Issue by yichinwang** [tensorflow/tensorflow#7256]
Hi All: 
  I'm a newbie on trying out tensorflow in Android,
by following the guildline to build the libtensorflow_demo.so,  I new a folder "libs" to put this so file in folder "tensorflow/examples/android/libs"

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src', '../../contrib/android/java']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
        }

however when app's running, it still can not find this lib.
any idea for resolving is appreciated

### Environment info
Operating System: Mac (CPU)

Process: org.tensorflow.demo, PID: 2401
                                                                   java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/org.tensorflow.demo/files/instant-run/dex/slice-slice_0-classes.dex"],nativeLibraryDirectories=[/data/app/org.tensorflow.demo-1/lib/x86_64, /system/lib64, /vendor/lib64]]] couldn't find "libtensorflow_demo.so"
                                                                       at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                                                                       at java.lang.System.loadLibrary(System.java:1530)

**Comment by asimshankar** [comment]
Are you following the instructions outlined in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android ?

That suggests the use of `bazel build` to build the demo, and has some instructions for using Android Studio as well. Are you following those?

If you're using a custom setup, then perhaps you want to add some more detail on your setup and post your question on stackoverflow?

**Comment by yichinwang** [comment]
Yes,  I use Android Studio 2.2.3 to import tensorflow project,
and follow the instructions listed in this page,
and also use command line below to build the apk
bazel build -c opt //tensorflow/examples/android:tensorflow_demo

then run this project, the error "couldn't find libtensorflow_demo.so" appears...
after refering to some suggestions, I new a folder "libs" and put so file in, but the problem is still there..

thanks

**Comment by asimshankar** [comment]
So the `bazel build -c opt //tensorflow/examples/android:tensorflow_demo` succeeds?
Can you manually install the `.apk` using

`adb install -r <path_to_apk_printed_by_bazel_build>`
?

Does that work?

**Comment by yichinwang** [comment]
Hi:
 I think the "bazel build" is successful for it didn't come out build error and finally shown build result as below

INFO: Found 1 target...
Target //tensorflow/examples/android:tensorflow_demo up-to-date:
  bazel-bin/tensorflow/examples/android/tensorflow_demo_deploy.jar
  bazel-bin/tensorflow/examples/android/tensorflow_demo_unsigned.apk
  bazel-bin/tensorflow/examples/android/tensorflow_demo.apk
INFO: Elapsed time: 25.941s, Critical Path: 8.17s

HOWEVER, it did fail in adb install this apk, with error below
Failed to install bazel-bin/tensorflow/examples/android/tensorflow_demo.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

**Comment by asimshankar** [comment]
That seems like the native library is being [built for a different architecture](http://stackoverflow.com/questions/24572052/install-failed-no-matching-abis-when-install-apk).

Did you setup the `WORKSPACE` file with the appropriate SDK/NDK.
Also, you might want to try with:

`bazel build -c opt --config=android_arm //tensorflow/examples/android:tensorflow_demo`
(notice the `--config=android_arm`)

**Comment by yichinwang** [comment]
Hi:
 Yes, the SDK/NDK path is already configured, and if the "bazel" command line has "x86" build config ?

because I'm using x86 Android emulator...(run faster the arm version ^_^)

**Comment by yichinwang** [comment]
Hi:
  when I use ARM ver emulator, the so lib can be found

**Comment by andrewharp** [comment]
The CPU type that gets built for in Android Studio/Gradle builds is defined here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/build.gradle#L10

The default is armeabi-v7a, so if you're running in an x86 emulator you'll need to change that accordingly.

**Comment by yichinwang** [comment]
Thanks, but I can not figure out which cpu type to specify, will it look like below 
bazel build -c opt --config=x86 //tensorflow/examples/android:tensorflow_demo

I tried but seems still not build "x86" version lib

**Comment by andrewharp** [comment]
What's the log output when you try that? There are no .so files placed under bazel-bin?

**Comment by yichinwang** [comment]
I use the command below
1. bazel clean
2. bazel build -c opt --config=x86 //tensorflow/examples/android:tensorflow_demo
3. sudo find / ./ -name libtensorflow_demo.so

the search result is below, where I didn't notice the "x86" version is generated ?!
and not found any so file under bazel-bin.

/private/var/tmp/_bazel_ycw/a122119f088e17a4855898206da17645/execroot/tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/_solib_armeabi-v7a/_U_S_Stensorflow_Sexamples_Sandroid_Ctensorflow_Unative_Ulibs___Utensorflow_Sexamples_Sandroid/libtensorflow_demo.so
/private/var/tmp/_bazel_ycw/a122119f088e17a4855898206da17645/execroot/tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so
/private/var/tmp/_bazel_ycw/a122119f088e17a4855898206da17645/execroot/tensorflow/bazel-out/android-arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/tensorflow/examples/android/libtensorflow_demo.so
/private/var/tmp/_bazel_ycw/a122119f088e17a4855898206da17645/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/examples/android/_dx/tensorflow_demo/native_symlinks/armeabi-v7a/libtensorflow_demo.so
/Users/ycw/tensorflow/tensorflow/examples/android/gradleBuild/intermediates/jniLibs/debug/libtensorflow_demo.so
.//tensorflow/examples/android/gradleBuild/intermediates/jniLibs/debug/libtensorflow_demo.so

**Comment by andrewharp** [comment]
Oh, you actually need to use the --cpu flag, not config.

build.gradle already uses that, though -- are you sure that doesn't work when you modify the CPU type?

**Comment by yichinwang** [comment]
HI:
In bazel command line, no matter I set the --cpu to ios_x86_64 or darwin,
after tensorflow_demo.apk built and unzip it to check, the so file is always located in "armeabi-v7a"

lib/armeabi-v7a/libtensorflow_demo.so 

is it normal ?

**Comment by andrewharp** [comment]
You don't want to build for iOS if you're targeting Android. The cpu value is x86, but you also need to pass the crosstool flags described in the instructions at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/android

And to clarify, have you tried modifying build.gradle to set the cpu to x86, and then building from *within* Android Studio yet?

**Comment by yichinwang** [comment]
Hi:
 I modify the cpu type as "x86_64" of gradle file below, and run "Build APK" in "Build" menu.

it appears error below..
Error:(63) Error: This fragment should provide a default constructor (a public constructor with no arguments) (org.tensorflow.demo.CameraConnectionFragment) [ValidFragment]

**Comment by andrewharp** [comment]
Seems that newer SDK levels require a default constructor: http://stackoverflow.com/questions/29762949/error-this-fragment-should-provide-a-default-constructor-a-public-constructor

You can try adding a default constructor (or just lower your target API level)l. Feel free to send a PR with the fix if this addresses the issue for you, thanks.

**Comment by yichinwang** [comment]
Hi:
  I add "checkReleaseBuilds false" below to resolve the "default constructor" issue,
    lintOptions {
        abortOnError false
        checkReleaseBuilds false
    }

  and finally the "libtensorflow_demo.so" can be loaded in x86 emulator.

 However once launch the demo app, the error occurs ,
and I'm not sure if it's because the x86 issue or not ?!

02-05 22:48:47.447 4814-4814/? I/art: Not late-enabling -Xcheck:jni (already on)
02-05 22:48:47.447 4814-4814/? W/art: Unexpected CPU variant for X86 using defaults: x86_64
02-05 22:48:47.547 4814-4814/org.tensorflow.demo D/tensorflow: CameraActivity: onCreate org.tensorflow.demo.ClassifierActivity@321f567
02-05 22:48:47.577 4814-4814/org.tensorflow.demo D/tensorflow: CameraActivity: onStart org.tensorflow.demo.ClassifierActivity@321f567
02-05 22:48:47.578 4814-4814/org.tensorflow.demo D/tensorflow: CameraActivity: onResume org.tensorflow.demo.ClassifierActivity@321f567
02-05 22:48:47.835 4814-4836/org.tensorflow.demo I/OpenGLRenderer: Initialized EGL, version 1.4
02-05 22:48:47.835 4814-4836/org.tensorflow.demo D/OpenGLRenderer: Swap behavior 1
02-05 22:48:47.936 4814-4836/org.tensorflow.demo E/EGL_emulation: tid 4836: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
02-05 22:48:47.936 4814-4836/org.tensorflow.demo W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x75969760d940, error=EGL_BAD_MATCH
02-05 22:48:47.943 4814-4814/org.tensorflow.demo I/CameraManagerGlobal: Connecting to camera service
02-05 22:48:47.973 4814-4814/org.tensorflow.demo I/tensorflow: CameraConnectionFragment: Adding size: 640x480
02-05 22:48:47.973 4814-4814/org.tensorflow.demo I/tensorflow: CameraConnectionFragment: Not adding size: 352x288
02-05 22:48:47.973 4814-4814/org.tensorflow.demo I/tensorflow: CameraConnectionFragment: Not adding size: 320x240
02-05 22:48:47.973 4814-4814/org.tensorflow.demo I/tensorflow: CameraConnectionFragment: Chosen size: 640x480
02-05 22:48:48.009 4814-4814/org.tensorflow.demo I/TensorFlowImageClassifier: Reading labels from: imagenet_comp_graph_label_strings.txt
02-05 22:48:48.012 4814-4814/org.tensorflow.demo D/AndroidRuntime: Shutting down VM
02-05 22:48:48.016 4814-4814/org.tensorflow.demo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: org.tensorflow.demo, PID: 4814
                                                                   java.lang.RuntimeException: Error initializing TensorFlow!
                                                                       at org.tensorflow.demo.ClassifierActivity.onPreviewSizeChosen(ClassifierActivity.java:135)
                                                                       at org.tensorflow.demo.CameraActivity$1.onPreviewSizeChosen(CameraActivity.java:158)
                                                                       at org.tensorflow.demo.CameraConnectionFragment.setUpCameraOutputs(CameraConnectionFragment.java:394)
                                                                       at org.tensorflow.demo.CameraConnectionFragment.openCamera(CameraConnectionFragment.java:411)
                                                                       at org.tensorflow.demo.CameraConnectionFragment.access$000(CameraConnectionFragment.java:63)
                                                                       at org.tensorflow.demo.CameraConnectionFragment$1.onSurfaceTextureAvailable(CameraConnectionFragment.java:94)

**Comment by yichinwang** [comment]
(Followed)
when set cpu = armeabi-v7a and using "arm" version emulator,
the below error also occur..

02-05 23:13:02.691 4190-4190/org.tensorflow.demo I/art: Not late-enabling -Xcheck:jni (already on)
02-05 23:13:02.695 4190-4190/org.tensorflow.demo W/art: Unknown instruction set features for ARM CPU variant (generic) using conservative defaults
02-05 23:13:06.459 4190-4190/org.tensorflow.demo D/tensorflow: CameraActivity: onCreate org.tensorflow.demo.StylizeActivity@5bb014e
02-05 23:13:06.552 4190-4198/org.tensorflow.demo W/art: Suspending all threads took: 10.696ms
02-05 23:13:07.005 4190-4190/org.tensorflow.demo D/tensorflow: CameraActivity: onStart org.tensorflow.demo.StylizeActivity@5bb014e
02-05 23:13:07.048 4190-4190/org.tensorflow.demo D/tensorflow: CameraActivity: onResume org.tensorflow.demo.StylizeActivity@5bb014e
02-05 23:13:07.432 4190-4224/org.tensorflow.demo I/OpenGLRenderer: Initialized EGL, version 1.4
02-05 23:13:07.433 4190-4224/org.tensorflow.demo D/OpenGLRenderer: Swap behavior 1
02-05 23:13:07.513 4190-4224/org.tensorflow.demo E/EGL_emulation: tid 4224: eglSurfaceAttrib(1146): error 0x3009 (EGL_BAD_MATCH)
02-05 23:13:07.513 4190-4224/org.tensorflow.demo W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa21ec4c0, error=EGL_BAD_MATCH
02-05 23:13:07.569 4190-4190/org.tensorflow.demo I/CameraManagerGlobal: Connecting to camera service
02-05 23:13:07.778 4190-4190/org.tensorflow.demo I/tensorflow: CameraConnectionFragment: Not adding size: 640x480
02-05 23:13:07.778 4190-4190/org.tensorflow.demo I/tensorflow: CameraConnectionFragment: Not adding size: 352x288
02-05 23:13:07.779 4190-4190/org.tensorflow.demo I/tensorflow: CameraConnectionFragment: Not adding size: 320x240
02-05 23:13:07.779 4190-4190/org.tensorflow.demo I/tensorflow: CameraConnectionFragment: Not adding size: 176x144
02-05 23:13:07.779 4190-4190/org.tensorflow.demo E/tensorflow: CameraConnectionFragment: Couldn't find any suitable preview size
02-05 23:13:07.793 4190-4190/org.tensorflow.demo I/native: tensorflow_inference_jni.cc:97 Native TF methods loaded.
02-05 23:13:07.793 4190-4190/org.tensorflow.demo I/TensorFlowInferenceInterface: Native methods already loaded.
02-05 23:13:07.794 4190-4190/org.tensorflow.demo I/native: tensorflow_inference_jni.cc:85 Creating new session variables for 33d6c42f66af20bb
02-05 23:13:07.795 4190-4190/org.tensorflow.demo I/native: tensorflow_inference_jni.cc:113 Loading Tensorflow.
02-05 23:13:07.822 4190-4190/org.tensorflow.demo I/native: tensorflow_inference_jni.cc:120 Session created.
02-05 23:13:07.822 4190-4190/org.tensorflow.demo I/native: tensorflow_inference_jni.cc:126 Acquired AssetManager.
02-05 23:13:07.823 4190-4190/org.tensorflow.demo I/native: tensorflow_inference_jni.cc:128 Reading file to proto: file:///android_asset/stylize_quantized.pb
02-05 23:13:07.824 4190-4190/org.tensorflow.demo A/native: jni_utils.cc:98 'asset' Must be non NULL
02-05 23:13:07.826 4190-4190/org.tensorflow.demo A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 4190 (tensorflow.demo)
                                                         
                                                         [ 02-05 23:13:07.859  3898: 3898 W/         ]
                                                         debuggerd: handling request: pid=4190 uid=10079 gid=10079 tid=4190

**Comment by andrewharp** [comment]
This is currently missing from the directions (needs to be fixed), but if you're not building with Bazel you need to download and extract the contents of https://storage.googleapis.com/download.tensorflow.org/models/stylize_v1.zip into the assets/ dir.

**Comment by andrewharp** [comment]
The null asset error indicates that the model is not being found in the assets/ dir.

This is currently missing from the directions (needs to be added), but if you're not building with Bazel you'll need to download and extract the contents of https://storage.googleapis.com/download.tensorflow.org/models/stylize_v1.zip into the assets/ dir.

**Comment by yichinwang** [comment]
Hi:
 finally I use the command to obtain the model, and run it successfully in emulator,
much appreciated for your guild.

$ curl -L https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip -o /tmp/inception5h.zip
$ curl -L https://storage.googleapis.com/download.tensorflow.org/models/mobile_multibox_v1.zip -o /tmp/mobile_multibox_v1.zip

$ unzip /tmp/inception5h.zip -d tensorflow/examples/android/assets/
$ unzip /tmp/mobile_multibox_v1.zip -d tensorflow/examples/android/assets/
