### ISSUE TITLE
Building a .dll on Windows

### ISSUE THREAD

**Issue by luketg8** [tensorflow/tensorflow#7258]
I have built libtensorflow.so with Bazel and used it successfully with the C Api in Ubuntu, however I was wondering if it is possible at all to use Bazel to build a .dll extension to use for Windows? As I want to integrate TensorFlow into an existing project. 

Thanks in advance

**Comment by gunan** [comment]
/cc @asimshankar 
At the moment, we have not tested building a dll in windows.

**Comment by guschmue** [comment]
might not be obvious: on top of building a such a dll, another thing is needed - the code in the dll would want to call say the c api that is in tensorflow.dll. On windows such public api's would need to be declared with dllexport so a new dll can link against tensorflow.dll and resolve references to the public api (for example the c api). Loading such a dll via tf.load_library() should kind of work on windows.

**Comment by tomjaguarpaw** [comment]
Could someone provide a definitive statement about the status of linking to a TensorFlow library on Windows from a third-party application?  Some questions in particular:

1. Is it possible to build a TensorFlow DLL on Windows?  If so, how?
2. Is it possible to build a TensorFlow static library on Windows?  If so, how?
3. If 1 or 2 is not possible what needs to change to make it possible?

**Comment by guschmue** [comment]
for 2:
yes, there is an example here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/tf_tutorials.cmake
Its using mostly object files instead of a library because of the way tensorflow registers ops. 
There is a static library generated library generated here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/tf_python.cmake#L692
but you'd need to link with /WHOLEARCHIVE to have op register correctly. pywrap_tensorflow_internal_static.lib includes the things python needs and for a standalone app you might need to add a few more things like tf_protos_cc, protobuf_STATIC_LIBRARIES ...

for 1:
In theory yes. This https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/tf_python.cmake#L750 nearly does this but there are a few issues with it if you want to link this way. 
I think @vit-stepanovs was working on a tensorflow.dll that works out of the box.

**Comment by tomjaguarpaw** [comment]
Thanks @guschmue!  That's very helpful.

And do I have to build from source to get these?  They don't come as part of the binary distribution?

**Comment by luketg8** [comment]
[Look here for compiled libtensorflow.dll for Windows](https://github.com/tensorflow/tensorflow/issues/18)

**Comment by vit-stepanovs** [comment]
@luketg8 There are a few issues with using the DLL from the Python Windows package:

1. It was implicitly linked with Python DLLs, so it expects Python DLLs to be present on the machine where you use it.
2. It does not include some of the TF symbols that non-python programs might find useful, e.g. C++ API objects like Scope, Ops etc.

As @guschmue mentioned, I am currently working on CMake changes to build a stand-alone DLL with TensorFlow that addresses the two issues. I can already successfully build such DLL, but quite a few C++ tests fail when linked with it, which I am trying to address right now.

**Comment by tomjaguarpaw** [comment]
Can anyone explain *why* the DLL and static library are not built by default?

**Comment by vit-stepanovs** [comment]
FYI, my PR #9124 adds support for building the DLL that does not depend on Python.

**Comment by tomjaguarpaw** [comment]
@vit-stepanovs Am I right in thinking that in order to build this one needs to issue 

    MSBuild /p:Configuration=Release tensorflow.sln

?

**Comment by sylvain-bougnoux** [comment]
@guschmue, I could build 2 with VS2015 & cmake (no bazel), but **no session factories are registered at runtime**. I could build & run tf_label_image_example, but when I used the same includes & links in my own soft, it crashes with 
`\tensorflow\tensorflow\core\common_runtime\session.cc:58] Not found: No session factory registered for the given session options: {target: "" config: } Registered factories are {}.` 

Currently the /WHOLEARCHIVE option make VS crashes with "fatal error LNK1000: Internal error during CImplib::EmitThunk". I could avoid it by specifying a library as in
`/WHOLEARCHIVE:tf_core_direct_session`
But it does not work either (maybe it is not the right library?).
As tf_label_image_example does not use /WHOLEARCHIVE at all, I am wondering if it is the right option to use?

I understand that factories are registered through global variables as in 
` static DirectSessionRegistrar registrar;` 

Is there another way to force such registration? 
Or does anyone understand why these symbols are discarded?
With VS it is not possible to control the order of globals' instantiation, but it should not be the case here!

**Comment by guschmue** [comment]
The problem with with registration is that nothing in the file is referenced from outside the file so the linker drops it. The regular build does with by giving the linker the object files and not the library.  /WHOLEARCHIVE is suppose to do the same but I did not expect it to crash - maybe check that you are using the 64bit version of link.exe ('where link.exe' should tell).
Using the object files as in the example:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/tf_tutorials.cmake
is the better way because you have more control over what goes into your exe.

**Comment by vit-stepanovs** [comment]
@tomjaguarpaw, the actual option name is tensorflow_BUILD_SHARED_LIB, not BUILD_SHARED_LIB. If you use that, cmake generates a project tensorflow.vcxproj (not tensorflow.sln!) which you can use to build the DLL.

**Comment by tomjaguarpaw** [comment]
@vit-stepanovs Thank you.  `cmake` did not complain when I used `-DBUILD_SHARED_LIB` so I assumed that was the correct option.  Perhaps it's a different option provided by default by `cmake`.

**Comment by mikejohnstn** [comment]
@vit-stepanovs Thanks for the PR. What's the size of the resulting DLL? Assuming it's on the larger size, are there any plans to allow it to be smaller? For example there's [this discussion](http://stackoverflow.com/questions/41400873/how-to-reduce-tensorflow-size-for-android) about how we can reduce tensorflow's .so size on Android.

**Comment by tomjaguarpaw** [comment]
@mikejohnstn When I built the DLL it was 44MB.

**Comment by DomLi** [comment]
Anybody hosting the built DLL?

**Comment by asimshankar** [comment]
We're now building the C library ([`c_api.h`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.h) and `tensorflow.dll`) for Windows. This won't contain the C++ API, but should be sufficient for other language bindings like C#.

This will be part of release 1.2 onwards, but in case anyone wants to give it a spin in the meantime, try the nightly build artifacts at:
http://ci.tensorflow.org/view/Nightly/job/nightly-libtensorflow-windows/lastSuccessfulBuild/artifact/lib_package/libtensorflow-cpu-windows-x86_64.zip

**Comment by andykernahan** [comment]
@asimshankar Great! I have just tested it using [TensorFlowSharp](/migueldeicaza/TensorFlowSharp) with no issue.

**Comment by gemmell** [comment]
So, excuse me for being late to the party, but I'm searching for how to consume a pre-trained network in our native C++ application and I have arrived here. I'm hoping one of you can point me to some up to date documentation on how one would train a network in python, then consume it in to execute from C++.  From what I understand, I would save the graph and checkpoint to file, then add tensorflow.dll as a dependency in my application and load the graph and checkpoint using the c_api.h ? Is that right? If someone could write a tutorial to clear that up it'd be great.

**Comment by tomjaguarpaw** [comment]
@gemmell: I would also like to do this in the near future.  This is the "best" reference I have found so far: http://stackoverflow.com/questions/41070330/is-it-possible-to-use-tensorflow-c-api-on-windows/41071296#41071296

It would be useful to have a more detailed and precise one.

**Comment by lostmsu** [comment]
What about GPU support?

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Comment by guikarist** [comment]
I made [a script to build Tensorflow C++ API using Bazel on Windows](https://github.com/guikarist/tensorflow-windows-build-script). It made it easier to build Tensorflow on Windows (which also supports building pip packages or C API). But I believe there will be better solutions and I hope everyone with same trouble could join me!

If you need `.dll` files, you should only rename `bazel-bin\tensorflow\libtensorflow_cc.so` to `tensorflow_cc.dll`. **and** `bazel-bin\tensorflow\liblibtensorflow_cc.so.ifso` to `tensorflow_cc.lib`.

**Comment by mnboos** [comment]
@guikarist Thanks for your effort! Unfortunately, none of my unresolved symbol errors disappeared. I updated the `BUILD` file as well as the `tf_exported_symbols_msvc.lds`.

Any idea what could be wrong?

Here the part from the `BUILD` file, would be nice if you could have a quick look:

```
tf_cc_shared_object(
    name = "libtensorflow_cc.so",
    linkopts = select({
        "//tensorflow:darwin": [
            "-Wl,-exported_symbols_list",  # This line must be directly followed by the exported_symbols.lds file
            "$(location //tensorflow:tf_exported_symbols.lds)",
        ],
        "//tensorflow:windows": [
			"-def:" +  # This line must be directly followed by the exported_symbols_msvc.lds file
			"$(location //tensorflow:tf_exported_symbols_msvc.lds)",
		],
        "//conditions:default": [
            "-z defs",
            "-Wl,--version-script",  #  This line must be directly followed by the version_script.lds file
            "$(location //tensorflow:tf_version_script.lds)",
        ],
    }),
    visibility = ["//visibility:public"],
    deps = [
        "//tensorflow:tf_exported_symbols.lds",
		"//tensorflow:tf_exported_symbols_msvc.lds",
        "//tensorflow:tf_version_script.lds",
        "//tensorflow/c:c_api",
        "//tensorflow/c/eager:c_api",
        "//tensorflow/cc:cc_ops",
        "//tensorflow/cc:client_session",
        "//tensorflow/cc:scope",
        "//tensorflow/cc/profiler",
        "//tensorflow/core:tensorflow",
    ] + if_ngraph(["@ngraph_tf//:ngraph_tf"]),
)

exports_files(
    [
        "tf_version_script.lds",
        "tf_exported_symbols.lds",
		"tf_exported_symbols_msvc.lds",
    ],
)
```

**Comment by guikarist** [comment]
@mnboos Have you added your unresolved symbols into `patches\tf_exported_symbols_msvc.lds`?

**Comment by mnboos** [comment]
Yes. Some of the errors even were symbols, that already were existent in this file. It looks like somehow this file is being ignored. On the other hand, after every change of this file and starting the build of tensorflow, it will link the libtensorflow_cc.so.

**Comment by gmt710** [comment]
> I made [a script to build Tensorflow C++ API using Bazel on Windows](https://github.com/guikarist/tensorflow-windows-build-script). It made it easier to build Tensorflow on Windows (which also supports building pip packages or C API). But I believe there will be better solutions and I hope everyone with same trouble could join me!
> 
> If you need `.dll` files, you should only rename `bazel-bin\tensorflow\libtensorflow_cc.so` to `tensorflow_cc.dll`. **and** `bazel-bin\tensorflow\liblibtensorflow_cc.so.ifso` to `tensorflow_cc.lib`.
@guikarist 
Thanks a lot.
