### ISSUE TITLE
tf.distribute.MirroredStrategy error: Multiple OpKernel registrations match NodeDef at the same priority

### ISSUE THREAD

**Issue by jmmelen** [tensorflow/tensorflow#72585]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.10.0

### Custom code

Yes

### OS platform and distribution

Windows 11

### Python version

3.10.14

### GCC/compiler version

Jupyter Notebook

### CUDA/cuDNN version

cuda_12.5.r12.5

### Current behavior?

#Minimal code to reproduce error
import tensorflow as tf
import keras 
import numpy as np

tf.debugging.set_log_device_placement(True)
gpus = tf.config.list_logical_devices('GPU')
print(gpus)

strategy = tf.distribute.MirroredStrategy(gpus)

#expect to be able have code (not shown) below this to run over 2 GPUs

### Standalone code to reproduce the issue

```shell
Output: 
[LogicalDevice(name='/device:GPU:0', device_type='GPU'), LogicalDevice(name='/device:GPU:1', device_type='GPU')]
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0

---> 14 strategy = tf.distribute.MirroredStrategy(gpus)
...
InvalidArgumentError: Multiple OpKernel registrations match NodeDef at the same priority '{{node AssignVariableOp}}': 'op: "AssignVariableOp" device_type: "GPU" constraint { name: "dtype" allowed_values { list { type: DT_FLOAT } } } host_memory_arg: "resource"' and 'op: "AssignVariableOp" device_type: "GPU" constraint { name: "dtype" allowed_values { list { type: DT_FLOAT } } } host_memory_arg: "resource"'
	 [[AssignVariableOp]] [Op:AssignVariableOp]
```

**Comment by tilakrayal** [comment]
@jmmelen,
The tensorflow v2.10 is an old version. Could you please try to install the latest tensorflow v2.15, v2.16 or v2.17 and it was able to execute the code and detect the GPU's. Kindly find the screenshot for the reference.

![Screenshot 2024-05-21 1 43 20 PM](https://github.com/user-attachments/assets/9483ec08-65b7-462d-93e2-c9dcadde8ca3)


Thank you!

**Comment by jmmelen** [comment]
1) remove existing tensorflow 2.10.0
2) installed tensorflow=2.17.0
2) Now in JupyterNotebook  the GPU is no longer being seen:
import tensorflow as tf  
print(tf.__version__)
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
print("Num CPUs Available: ", len(tf.config.list_physical_devices('CPU')))
print(tf.config.list_physical_devices('GPU'))
print(tf.config.list_physical_devices('CPU'))

Output:
2.17.0
Num GPUs Available:  0
Num CPUs Available:  1
[]
[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

**Comment by jmmelen** [comment]
Also tried: pip install --force-reinstall tensorflow==2.17.0
and got the same error as above

**Comment by jmmelen** [comment]
1) Uninstalled tensorflow, tensorboard, tensorboard-data-server, keras, and tensorflow-intel 
2) installed tensorflow 2.17.0 
Works!!

**Comment by jmmelen** [comment]
Details of working:
Code:
import tensorflow as tf
import keras 
import numpy as np

tf.debugging.set_log_device_placement(True)
gpus = tf.config.list_logical_devices('GPU')
print(gpus)

strategy = tf.distribute.MirroredStrategy(gpus)
#print("Number of devices in strategy: {}".format(strategy.num_replicas_in_sync))
with strategy.scope():
  inputs = keras.layers.Input(shape=(1,))
  predictions = keras.layers.Dense(1)(inputs)
  model = keras.models.Model(inputs=inputs, outputs=predictions)
  model.compile(loss='mse', optimizer=keras.optimizers.SGD(learning_rate=0.2))
model.compile(loss="mse")

Output:
[LogicalDevice(name='/device:GPU:0', device_type='GPU'), LogicalDevice(name='/device:GPU:1', device_type='GPU')]
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:1
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:GPU:1
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:GPU:1
INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1')
Executing op Cast in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op Cast in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op StatelessRandomGetKeyCounter in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0
Executing op StatelessRandomUniformV2 in device /job:localhost/replica:0/task:0/device:GPU:0
etc......................................etc............................

**Comment by jmmelen** [comment]
See above comments

**Comment by jmmelen** [comment]
Also tried:
1) uninstalled tensorflow, tensorboard-data-server, tensorboard, keras, tensorflow-intel. 
2) installed tensorflow 2.17.0 and got the same error as above:
import tensorflow as tf
print(tf.version)
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))
print("Num CPUs Available: ", len(tf.config.list_physical_devices('CPU')))
print(tf.config.list_physical_devices('GPU'))
print(tf.config.list_physical_devices('CPU'))
Output:
2.17.0
Num GPUs Available: 0
Num CPUs Available: 1
[]

**Comment by jmmelen** [comment]
Remember this is on Windows 11.

**Comment by tilakrayal** [comment]
TensorFlow 2.10 was the last TensorFlow release that supported GPU on native-Windows. Starting with TensorFlow 2.11, you will need to install [TensorFlow in WSL2](https://tensorflow.org/install/pip#windows-%5Bwsl2%5D), or install tensorflow-cpu and, optionally, try the [TensorFlow-DirectML-Plugin](https://github.com/microsoft/tensorflow-directml-plugin#tensorflow-directml-plugin-)
