### ISSUE TITLE
Configure script optimization flags don't work

### ISSUE THREAD

**Issue by tbaker2** [tensorflow/tensorflow#7259]
The default optimization switches that are set when running the configure script do not change the compiler settings.  The values are put into the bazel.rc file.  They don't get into the gcc command line.  For example if I run ./configure with all of the default answers the optimization should be "-march=native".  I have tested this on multiple Ubuntu 16.04 systems with don't have CUDA.

If I then build the pip package with 'bazel build --c opt -s  ...' one example compile is this:

> /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/local-opt/bin/external/farmhash_archive/_objs/farmhash/external/farmhash_archive/src/farmhash.pic.d '-frandom-seed=bazel-out/local-opt/bin/external/farmhash_archive/_objs/farmhash/external/farmhash_archive/src/farmhash.pic.o' -fPIC -iquote external/farmhash_archive -iquote bazel-out/local-opt/genfiles/external/farmhash_archive -iquote external/bazel_tools -iquote bazel-out/local-opt/genfiles/external/bazel_tools -isystem external/farmhash_archive/src -isystem bazel-out/local-opt/genfiles/external/farmhash_archive/src -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/farmhash_archive/src/farmhash.cc -o bazel-out/local-opt/bin/external/farmhash_archive/_objs/farmhash/external/farmhash_archive/src/farmhash.pic.o)

If I explicitly set the compile options with 'bazel build --c opt --copts=-march=native -s  ...' I get the correct results:

> /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections **'-march=native'** '-std=c++0x' -MD -MF bazel-out/local-opt/bin/external/farmhash_archive/_objs/farmhash/external/farmhash_archive/src/farmhash.pic.d '-frandom-seed=bazel-out/local-opt/bin/external/farmhash_archive/_objs/farmhash/external/farmhash_archive/src/farmhash.pic.o' -fPIC -iquote external/farmhash_archive -iquote bazel-out/local-opt/genfiles/external/farmhash_archive -iquote external/bazel_tools -iquote bazel-out/local-opt/genfiles/external/bazel_tools -isystem external/farmhash_archive/src -isystem bazel-out/local-opt/genfiles/external/farmhash_archive/src -isystem external/bazel_tools/tools/cpp/gcc3 -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/farmhash_archive/src/farmhash.cc -o bazel-out/local-opt/bin/external/farmhash_archive/_objs/farmhash/external/farmhash_archive/src/farmhash.pic.o)

The performance is slower for the first example.  Somehow the optimizations in bazel.rc are not getting through to the compiler command line.

**Comment by yaroslavvb** [comment]
You have to build with --config=opt rather than -c opt

**Comment by tbaker2** [comment]
Thanks.  I didn't understand the explanation printed by the configure script.  It would help to have this explained in the manual.

**Comment by yaroslavvb** [comment]
Would you like to send a pr to fix it?

**Comment by yaroslavvb** [comment]
BTW, here's the recipe I use for making pull requests
https://gist.github.com/yaroslavvb/bdb0a92f2a516ebbe2d386c48f5e2c45

**Comment by gunan** [comment]
We have updated our documentation, and configure script at head.
But I am happy to accept another change do either our docs or the explanation printed by configure script.

**Comment by girving** [comment]
@tbaker2 Are you happy with the change?  We'd be happy to accept clarifying PRs.

**Comment by tbaker2** [comment]
I don't see where the changes are.  The only commit from @gunan that I see is about cuDNN library handling.  I would like to contribute more information about optimization.  It would help to have some feedback from the TensorFlow maintainers about what the default should be.  For example, why is '--config=opt' not recommended when building with the '-c opt' flag?

**Comment by yaroslavvb** [comment]
`config=opt` was added in https://github.com/tensorflow/tensorflow/commit/c4e3d4a74e86fce3a09badd20952f067ff340f32#commitcomment-20600666 and documented in https://github.com/tensorflow/tensorflow/pull/7211

-c opt means "compilation mode=opt"

If you do `--config=opt` and `-c opt`, you are adding `-c opt` option twice because it's one of the options added when you do `--config=opt`

**Comment by tbaker2** [comment]
I see it now.  I was looking on the tensorflow.org site.  Everything looks good.

**Comment by yaroslavvb** [comment]
It's on master version of "Get Started/Os Setup" -- https://www.tensorflow.org/versions/master/get_started/os_setup#optimizing_cpu_performance , which means it'll eventually be on tensorflow.org default version. Closing issue since it seems resolved
