### ISSUE TITLE
load_op_library don't see Ops

### ISSUE THREAD

**Issue by IvanBudnikov** [tensorflow/tensorflow#7260]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
http://stackoverflow.com/questions/42019818/tensorflow-load-op-library-load-incorrectly?noredirect=1#comment71258436_42019818
### Environment info
Operating System: Linux Gentoo

Installed version of CUDA and cuDNN: 
-rw-r--r-- 1 root root 558632 Dec 28 08:08 /opt/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root     16 Dec 28 08:08 /opt/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root     19 Dec 28 08:08 /opt/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rwxr-xr-x 1 root root 415432 Sep 15 00:05 /opt/cuda/lib64/libcudart.so.8.0.44
-rw-r--r-- 1 root root 774168 Dec 28 08:08 /opt/cuda/lib64/libcudart_static.a

If installed from binary pip package, provide:
v 0.12.0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
_actv_module = tf.load_op_library('<path>/actv.so')
print(_actv_module.OP_LIST)

When act.so situated in some directories I see the list of Ops in it (as it should be).
When I copy it to another directories list of Ops is empty. I can't find any reason why some directories are different from other. In both cases path is correct -- load_op_library is able to find file.

### What other attempted solutions have you tried?
I tried to copy source files to "problem" directories and compile it there (according to Adding new Op manual, compile with GPU support) -- with same results.
More strange -- I made a copy of all source files with another names, compiled it in "normal" directory, and load_op_library can't find Ops in it!

### Logs or other output that would be helpful
Attached: sources -- actv.cc, actv_kernel.cu.cc
Normal libs -- actv.so, actv_kernel.cu.o
"Corrupted" libs (in which load_op_library can't see any ops) -- actv_corrupted.so, actv_kernel_corrupted.cu.o
[Archive.zip](https://github.com/tensorflow/tensorflow/files/752539/Archive.zip)

**Comment by girving** [comment]
Presumably your `actv.so` file is linked against some other files in directory dependent way.  Try running `ldd actv.so` in both places and see if they're different.

**Comment by IvanBudnikov** [comment]
ldd returns equal list of links:
        linux-vdso.so.1 (0x00007ffcaad4c000)
	libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/libstdc++.so.6 (0x00007f9cf9533000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f9cf9234000)
	libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.4/libgcc_s.so.1 (0x00007f9cf901d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9cf8c81000)
	/lib64/ld-linux-x86-64.so.2 (0x000055d7b28ec000)
The only changes are in (0x000.....) (addresses?)
Include sections in source code:
actv.cc:
  #include "tensorflow/core/framework/op.h"
  #include "tensorflow/core/framework/shape_inference.h"
  #include "tensorflow/core/framework/op_kernel.h"
actv_kernel.cu.cc:
  #include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"

**Comment by girving** [comment]
@keveman Is it expected that the op library doesn't link against TensorFlow?

**Comment by ibudnikov** [comment]
Can anyone help?

**Comment by skye** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
