### ISSUE TITLE
Compare to different GPUs (RTX 4060Ti and GTX 1660Ti) performance

### ISSUE THREAD

**Issue by tom2002965** [tensorflow/tensorflow#72635]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf 2.2.3/tf2.3/ tf2.5/tf2.10/tf2.12

### Custom code

Yes

### OS platform and distribution

Ubuntu 18.04

### Current behavior?

Hello,

I'm comparing the performance of two GPUs and the differences between different TensorFlow versions.
I plan to upgrade from GTX 1660 Ti to RTX 4060Ti. I expected the inference speed to be faster after the upgrade, but surprisingly it wasn't.
Below are the results of inferring different models and batch sizes. I used Docker to test different versions of TF.
Due to cuda version, it's hard to compare almost tf versions.
The number is average inference ms

###  GTX 1660 Ti
<img width="920" alt="截圖 2024-07-28 11 17 47" src="https://github.com/user-attachments/assets/3b5c6831-fa82-48cf-aeae-3294d3c53c72">

###  RTX 4060 Ti
<img width="746" alt="截圖 2024-07-28 11 17 56" src="https://github.com/user-attachments/assets/9fc8d50a-6c0a-4776-81c0-451d936b0955">

### GTX 1660 Ti vs RTX 4060 Ti (w/ same tf version)
<img width="571" alt="截圖 2024-07-28 11 18 12" src="https://github.com/user-attachments/assets/2b607367-a84b-4c21-a0b6-0c4a012ffce7">

From the chart above, I've drawn a few conclusions:

1. The higher the TF version, the longer the inference time... why???
2. I expected the 4060Ti to be faster than the 1660Ti for the same TF version, but this is only observed when bs=8/16, while my use case is for a single image.

I suspected it might be a card issue, but when I tested the PyTorch version of YOLOv5, the 4060Ti was indeed faster.

I wonder if any seniors can give me some clues or help me understand this, thank you.

Is there anything else you'd like me to help with regarding this translation or the content of your message?

Thanks, 
KT

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1e_lXPvQ82lCuOyFs9xK8oztagNwxFfkd?usp=sharing
```

**Comment by Venkat6871** [comment]
Hi **@tom2002965** ,
- Here i observed version mismatch. Could you please check with compatibility versions? And Please use latest version for better results. let us know whether the issue persists with recent TF versions.

Thank you!

**Comment by tom2002965** [comment]
Hi @Venkat6871 , 

Very thank for your response.
- All the tf/cuda/cudnn are from docker which is [tensorflow](https://hub.docker.com/r/tensorflow/tensorflow/) provided.
- Now my gpu drive of RTX 4060Ti is `535.183.01` . I have to update driver to test latest version . So I test tf-2.14 first. The result is below.
- 2.14 is faster than 2.10/2.12, but it still slower than tf 2.5.
<img width="930" alt="截圖 2024-07-31 00 14 11" src="https://github.com/user-attachments/assets/537c3156-2210-4114-9248-9244dac632cd">

Thanks.

**Comment by Venkat6871** [comment]
Hi **@tom2002965** ,
Apologies for the delay, and thank you for your patience. It appears there are still compatibility issues with TensorFlow 2.14.0. The compatible version of cuDNN is 8.7. Could you please double-check all the compatible versions and verify with the latest ones? If you continue to face issues, please let us know. For your convenience, here is the [documentation](https://www.tensorflow.org/install/source#gpu) to help verify the compatible versions.
Thank you!
