### ISSUE TITLE
losses return None if dictionary is used in pipeline and model

### ISSUE THREAD

**Issue by pmdaye** [tensorflow/tensorflow#72679]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf 2.16.2, tf 2.17.0

### Custom code

No

### OS platform and distribution

Rocky Linux 9.3

### Python version

3.9

### Current behavior?

If I use a dictionary at the output of my pipeline and my model, the loss function returns None instead of the value.
If you run this code with tf>=2.16.2, it will fail with "no loss function" error (see the map_fct output returns "custom_out") as well as the model definition uses "custom_out". If you change the map_fct and the model definition to remove the dictionary, it is working. This is working on 2.14.x (have not tried on 2.15.x)

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import keras
from keras import layers

def map_fct(x, y):
    return x, {'custom_out': y}

inputs = keras.Input(shape=(784,), name="digits")
x = layers.Dense(64, activation="relu", name="dense_1")(inputs)
x = layers.Dense(64, activation="relu", name="dense_2")(x)
outputs = layers.Dense(10, activation="softmax", name="predictions")(x)

model = keras.Model(inputs=inputs, outputs={'custom_out': outputs})

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Preprocess the data (these are NumPy arrays)
x_train = x_train.reshape(60000, 784).astype("float32") / 255
x_test = x_test.reshape(10000, 784).astype("float32") / 255

y_train = y_train.astype("float32")
y_test = y_test.astype("float32")

# Reserve 10,000 samples for validation
x_val = x_train[-10000:]
y_val = y_train[-10000:]
x_train = x_train[:-10000]
y_train = y_train[:-10000]

train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
val_dataset = tf.data.Dataset.from_tensor_slices((x_val, y_val))

train_dataset = train_dataset.map(
        map_func = map_fct,
        num_parallel_calls = tf.data.experimental.AUTOTUNE
    )

val_dataset = val_dataset.map(
        map_func = map_fct,
        num_parallel_calls = tf.data.experimental.AUTOTUNE
    )

model.compile(
    optimizer=keras.optimizers.RMSprop(),  # Optimizer
    # Loss function to minimize
    loss=keras.losses.SparseCategoricalCrossentropy(),
    # List of metrics to monitor
    metrics=[keras.metrics.SparseCategoricalAccuracy()],
)

train_dataset = train_dataset.batch(
            batch_size = 64,
            drop_remainder=True,
        )
val_dataset = val_dataset.batch(
            batch_size = 64,
            drop_remainder=True,
        )

print("Fit model on training data")
history = model.fit(
    train_dataset,
    batch_size=64,
    epochs=2,
    # We pass some validation for
    # monitoring validation loss and metrics
    # at the end of each epoch
    validation_data=val_dataset,
)
```

### Relevant log output

```shell
2024-07-29 07:13:09.432389: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-29 07:13:09.445499: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-29 07:13:09.465390: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-29 07:13:09.465415: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1442] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-29 07:13:09.477398: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-29 07:13:10.111192: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-07-29 07:13:10.748552: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1928] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 20282 MB memory:  -> device: 0, name: NVIDIA RTX A5000, pci bus id: 0000:9e:00.0, compute capability: 8.6
Fit model on training data
Epoch 1/2
Traceback (most recent call last):
  File "/home/xxxxxx/workspace/tmp/dict_dataset_tf2_16_2.py", line 61, in <module>
    history = model.fit(
  File "/home/xxxxxx/python_venv/tensorflow_probability/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/xxxxxx/python_venv/tensorflow_probability/lib64/python3.9/site-packages/keras/src/trainers/trainer.py", line 331, in compute_loss
    raise ValueError(
ValueError: No loss to compute. Provide a `loss` argument in `compile()`.
```

**Comment by pmdaye** [comment]
After more testing, I realized that if I name my last layer "custom_out", then I can keep the dictionary in my dataset. I found the fact that the output in the model can used a dictionary a very useful feature. When was this capability removed from tf 2?

**Comment by just-sabyr** [comment]
@pmdaye, your code has a slight mistake (that took me 4 hours to find lol). Here is how to fix your code.
```python
...
def map_fct(x, y):
    return x, {'y_true': y}

...
model = keras.Model(inputs=inputs, outputs={'y_true': outputs}
...
``` 
The model output name and the dataset y_label name must match. You can call the layers name anyhow you like (outputs = layers. line)

**Comment by just-sabyr** [comment]
@pmdaye, your code has a slight mistake. Here's how to fix it: rename 'predictions' to 'custom_out'. It looks like all of the three output names (outputs Dense(10) layer, dataset y_true label name, model_outputs name) have to be called by the same name.
This is the correct code that runs on google colab with tf.__version__ == '2.17.0', and keras.__version__ == '3.4.1'

```python
!pip3 install tensorflow==2.16.2 --quiet
!pip3 install --upgrade tf-keras --quiet

import tensorflow as tf
import keras
from keras import layers

def map_fct(x, y):
    return x, {'y_true': y}

inputs = keras.Input(shape=(784,), name="digits")
x = layers.Dense(64, activation="relu", name="dense_1")(inputs)
x = layers.Dense(64, activation="relu", name="dense_2")(x)
outputs = layers.Dense(10, activation="softmax", name="y_true")(x)

model = keras.Model(inputs=inputs, outputs={'y_true': outputs})

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

# Preprocess the data (these are NumPy arrays)
x_train = x_train.reshape(60000, 784).astype("float32") / 255
x_test = x_test.reshape(10000, 784).astype("float32") / 255

y_train = y_train.astype("float32")
y_test = y_test.astype("float32")

# Reserve 10,000 samples for validation
x_val = x_train[-10000:]
y_val = y_train[-10000:]
x_train = x_train[:-10000]
y_train = y_train[:-10000]

train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
val_dataset = tf.data.Dataset.from_tensor_slices((x_val, y_val))

train_dataset = train_dataset.map(
        map_func = map_fct,
        num_parallel_calls = tf.data.experimental.AUTOTUNE
    )

val_dataset = val_dataset.map(
        map_func = map_fct,
        num_parallel_calls = tf.data.experimental.AUTOTUNE
    )

model.compile(
    optimizer=keras.optimizers.RMSprop(),  # Optimizer
    # Loss function to minimize
    loss=keras.losses.SparseCategoricalCrossentropy(),
    # List of metrics to monitor
    metrics=[keras.metrics.SparseCategoricalAccuracy()],
)

train_dataset = train_dataset.batch(
            batch_size = 64,
            drop_remainder=True,
        )
val_dataset = val_dataset.batch(
            batch_size = 64,
            drop_remainder=True,
        )

print("Fit model on training data")
history = model.fit(
    train_dataset,
    batch_size=64,
    epochs=2,
    # We pass some validation for
    # monitoring validation loss and metrics
    # at the end of each epoch
    validation_data=val_dataset,
)
```

**Comment by pmdaye** [comment]
@just-sabyr,

Thanks for the update. You came to the same conclusion as me, great! From my analysis, we do not need to name the output in the model definition, only the last layer is sufficient.
However, I must stress that the original version of the code was working without issues on 2.14.1. If this has changed on purpose, I think it would be great to have this explained somewhere within the documentation. If this change was not spotted, I would suggest to file it as a bug.
Thanks again!

**Comment by just-sabyr** [comment]
@pmdaye, as per my understanding, it is safer if all of them are named the same.  After some considerations here is my try to explain what happens: 

1. There is an object (Trainer._compile_loss in the file) of type `CompileLoss` in trainer.py file, (which is initialized at line 153) it takes _output_names of the model_ as one of it's parameters.
2. `Trainer._compile_loss`'s `call` method is called with `y`, `y_pred`, `sample_weight` (which returns the loss value) (at line 325 in trainer.py).
3. `CompileLoss.call()` has a utitlity function (in the compile_utils.py file)  `_flatten_y` which is called for both `y` and `y_pred` to convert them into lists. 
4. Both `y` and `y_pred` are of type dict before _`_flatten_y`_ (each with one key if it is single-output model) processes them and this function uses `_output_names of the model_` passed at step 1 to do so. 

The fourth step is the reason for the necessity that all of the three `y` (input to the model), `y_pred` (output of the model) and last_layer.outputs must be dictionaries with the same keys. I did not look up how they handled it in the previous versions, but (to me at least) this way seems sensible.

**Comment by just-sabyr** [comment]
However there should be a proper error handling to warn users about non-matching dict keys.

**Comment by Venkat6871** [comment]
Hi **@pmdaye** ,
- Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999).
Thank you!
