### ISSUE TITLE
keras functional api fit() with tf.data.Dataset for validation data is resulting in an error

### ISSUE THREAD

**Issue by just-sabyr** [tensorflow/tensorflow#72696]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.15.0

### Custom code

Yes

### OS platform and distribution

Kaggle Notebook

### Python version

3.10.13

### GCC/compiler version

12.3.0

### CUDA/cuDNN version

12.1.105

### Current behavior?

Current behavior: AttributeError: 'NoneType' object has no attribute 'items'.
Expected behavior: standard fit() function returning history object. The code works without val_dataset 
train_dataset is <_TakeDataset element_spec=((TensorSpec(shape=(None, 73), dtype=tf.float64, name=None), TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name=None)), TensorSpec(shape=(None,), dtype=tf.int64, name=None))>
val_dataset is <_TakeDataset element_spec=((TensorSpec(shape=(None, 73), dtype=tf.float64, name=None), TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name=None)), TensorSpec(shape=(None,), dtype=tf.int64, name=None))>
test_dataset is <_PrefetchDataset element_spec=((TensorSpec(shape=(None, 73), dtype=tf.float64, name=None), TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name=None)), TensorSpec(shape=(None, 1), dtype=tf.float64, name=None))>

### Standalone code to reproduce the issue
[Kaggle Notebook](https://www.kaggle.com/code/sabyrbazarymbetov/multi-input-effnetv2-feature-extraction-dnn)

### Relevant log output

```shell
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1722248226.794089      68 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
W0000 00:00:1722248226.850691      68 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
4386/4386 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9955 - loss: 0.2826
/opt/conda/lib/python3.10/contextlib.py:153: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self.gen.throw(typ, value, traceback)

File /opt/conda/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py:122, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    119     filtered_tb = _process_traceback_frames(e.__traceback__)
    120     # To get the full stack trace, call:
    121     # `keras.config.disable_traceback_filtering()`
--> 122     raise e.with_traceback(filtered_tb) from None
    123 finally:
    124     del filtered_tb

File /opt/conda/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py:354, in TensorFlowTrainer.fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq)
    333         self._eval_epoch_iterator = TFEpochIterator(
    334             x=val_x,
    335             y=val_y,
   (...)
    341             shuffle=False,
    342         )
    343     val_logs = self.evaluate(
    344         x=val_x,
    345         y=val_y,
   (...)
    351         _use_cached_eval_dataset=True,
    352     )
    353     val_logs = {
--> 354         "val_" + name: val for name, val in val_logs.items()
    355     }
    356     epoch_logs.update(val_logs)
    358 callbacks.on_epoch_end(epoch, epoch_logs)

AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by just-sabyr** [comment]
> ### Issue type
> Bug
> 
> ### Have you reproduced the bug with TensorFlow Nightly?
> No
> 
> ### Source
> source
> 
> ### TensorFlow version
> 2.15.0
> 
> ### Custom code
> Yes
> 
> ### OS platform and distribution
> Kaggle Notebook
> 
> ### Mobile device
> _No response_
> 
> ### Python version
> 3.10.13
> 
> ### Bazel version
> _No response_
> 
> ### GCC/compiler version
> 12.3.0
> 
> ### CUDA/cuDNN version
> 12.1.105
> 
> ### GPU model and memory
> _No response_
> 
> ### Current behavior?
> Current behavior: AttributeError: 'NoneType' object has no attribute 'items'. Expected behavior: standard fit() function returning history object. The code works without val_dataset train_dataset is <_TakeDataset element_spec=((TensorSpec(shape=(None, 73), dtype=tf.float64, name=None), TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name=None)), TensorSpec(shape=(None,), dtype=tf.int64, name=None))> val_dataset is <_TakeDataset element_spec=((TensorSpec(shape=(None, 73), dtype=tf.float64, name=None), TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name=None)), TensorSpec(shape=(None,), dtype=tf.int64, name=None))> test_dataset is <_PrefetchDataset element_spec=((TensorSpec(shape=(None, 73), dtype=tf.float64, name=None), TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name=None)), TensorSpec(shape=(None, 1), dtype=tf.float64, name=None))>
> 
> ### Standalone code to reproduce the issue
> ```shell
> # Split train dataset into train and test
> train_dataset = train_dataset_full.take(TRAIN_LENGTH)
> val_dataset = train_dataset_full.skip(TRAIN_LENGTH)
> val_dataset = val_dataset.take(VAL_LENGTH)
> 
> # Input layers
> tabular_inputs = keras.Input(shape=(X.shape[-1:]), name='tabular_input')
> img_inputs = keras.Input(shape=(*IMG_SHAPE, 3), name='image_input')
> 
> # There are some other layers
> y = layers.Flatten()(img_inputs)
> 
> # Combine both
> combined = layers.Concatenate(name="image_joined_with_metadata")([x, y])
> z = layers.Dense(512, activation="relu")(combined)
> 
> # Output Layer
> outputs = layers.Dense(1, activation="sigmoid")(z)
> 
> # Model creation
> model = keras.Model(inputs=[tabular_inputs, img_inputs], outputs=outputs)
> 
> # Compile the model with appropriate hyperparameters
> model.compile(
>     optimizer="Adam",
>     loss="binary_crossentropy",
>     metrics=["accuracy"],
> )
> 
> # Train the multiinput model
> # Fit the model
> history = model.fit( 
>     train_dataset.repeat(),
>     validation_data = val_dataset.repeat(),
>     callbacks=callbacks,
>     epochs=EPOCHS,
>     steps_per_epoch=int(TRAIN_LENGTH/BATCH_SIZE),
>     validation_steps=int(VAL_LENGTH/BATCH_SIZE)
> )
> ```
> 
> ### Relevant log output
> ```shell
> WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
> I0000 00:00:1722248226.794089      68 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
> W0000 00:00:1722248226.850691      68 graph_launch.cc:671] Fallback to op-by-op mode because memset node breaks graph update
> 4386/4386 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.9955 - loss: 0.2826
> /opt/conda/lib/python3.10/contextlib.py:153: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
>   self.gen.throw(typ, value, traceback)
> 
> File /opt/conda/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py:122, in filter_traceback.<locals>.error_handler(*args, **kwargs)
>     119     filtered_tb = _process_traceback_frames(e.__traceback__)
>     120     # To get the full stack trace, call:
>     121     # `keras.config.disable_traceback_filtering()`
> --> 122     raise e.with_traceback(filtered_tb) from None
>     123 finally:
>     124     del filtered_tb
> 
> File /opt/conda/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py:354, in TensorFlowTrainer.fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq)
>     333         self._eval_epoch_iterator = TFEpochIterator(
>     334             x=val_x,
>     335             y=val_y,
>    (...)
>     341             shuffle=False,
>     342         )
>     343     val_logs = self.evaluate(
>     344         x=val_x,
>     345         y=val_y,
>    (...)
>     351         _use_cached_eval_dataset=True,
>     352     )
>     353     val_logs = {
> --> 354         "val_" + name: val for name, val in val_logs.items()
>     355     }
>     356     epoch_logs.update(val_logs)
>     358 callbacks.on_epoch_end(epoch, epoch_logs)
> 
> AttributeError: 'NoneType' object has no attribute 'items'
> ```

Here is a link to my notebook causing the error: https://www.kaggle.com/code/sabyrbazarymbetov/multi-input-effnetv2-feature-extraction-dnn

**Comment by Venkat6871** [comment]
Hi **@just-sabyr** ,
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999).
Thank you!
