### ISSUE TITLE
`tf.bitwise.left_shift`'s behavior is different on cpu and gpu on tensorflow 2.18.0-dev20240728

### ISSUE THREAD

**Issue by wangzhen0518** [tensorflow/tensorflow#72709]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

v1.12.1-113709-gdc368f6cbd8 2.18.0-dev20240728

### Custom code

Yes

### OS platform and distribution

Ubuntu 22.04.4 LTS (x86_64)

### Python version

3.11.0

### CUDA/cuDNN version

cuda_12.4.r12.4/compiler.34097967_0

### Current behavior?

`tf.bitwise.left_shift`'s behavior is different on cpu and gpu.

on cpu:
```python
with tf.device("/cpu:0"):
    x = tf.constant([-2, -1, 0, 1, 2])
    y = tf.constant([3, 2, 1, 0, -1])
    z = tf.bitwise.left_shift(x, y)
    print(z.numpy()) # [-16  -4   0   1   2]
```

on gpu:
```python
with tf.device("/gpu:0"):
    x = tf.constant([-2, -1, 0, 1, 2])
    y = tf.constant([3, 2, 1, 0, -1])
    z = tf.bitwise.left_shift(x, y)
    print(z.numpy())
```

`z` on cpu and gpu are not equal.

### Standalone code to reproduce the issue

```shell
with tf.device("/cpu:0"):
    x = tf.constant([-2, -1, 0, 1, 2])
    y = tf.constant([3, 2, 1, 0, -1])
    z = tf.bitwise.left_shift(x, y)
    print(z.numpy()) # [-16  -4   0   1   2]

with tf.device("/gpu:0"):
    x = tf.constant([-2, -1, 0, 1, 2])
    y = tf.constant([3, 2, 1, 0, -1])
    z = tf.bitwise.left_shift(x, y)
    print(z.numpy()) # [-16  -4   0   1   0]
```

**Comment by 372046933** [comment]
Maybe not a bug, because
> If `y` is negative, or greater than or equal to the width of `x` in bits the
result is implementation defined.

**Comment by tilakrayal** [comment]
@wangzhen0518,
I was able to reproduce the issue on tensorflow 2.15, v2.17 and tf-nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3da0435d63f8a53a33bf281d2cbf4469/untitled2035.ipynb).

**Comment by tilakrayal** [comment]
@wangzhen0518,
As per the document it is mentioned that **If y is negative, or greater than or equal to the width of x in bits the result is implementation defined**, also I checked with alternative inputs for the **y** and observed when the y is +ve, it is providing the same result and when **y** is -ve, it provided the same result as mentioned.
https://www.tensorflow.org/api_docs/python/tf/bitwise/left_shift

Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/73907c1d487ba220a26f9fa3547d64e8/untitled2040.ipynb) for the reference.

Thank you!

**Comment by wangzhen0518** [comment]
Thanks for your explanation. I am curious about whether it is necessary to maintain consistent results across different backends.

**Comment by tilakrayal** [comment]
@wangzhen0518,
The reason could be due to the optimized way of calculating numbers on Nvidia which is different compared to others, there will be a small amount of precision errors. Thank you!
