### ISSUE TITLE
Failure in "Linking CXX shared library libpywrap_tensorflow.so" , with error info "additional relocation overflows omitted from the output"

### ISSUE THREAD

**Issue by gaoshan2006** [tensorflow/tensorflow#7270]
I am using Cmake 3.5.1 to compile sourcecode in Ubuntu 16.04 with a ppc64le machine ( Power64 little endian ).  Python 2.7.12.  The compile is failed in  "Linking CXX shared library libpywrap_tensorflow.so". The error info is as bellows.   I try compiling source code both 0.10.0 and 0.12.0,  and get the same error.
Could you give me a help please ? Thanks

[ 98%] Running SWIG to generate Python wrappers
[ 98%] Building CXX object CMakeFiles/pywrap_tensorflow.dir/pywrap_tensorflow.cc.o
[ 98%] Linking CXX shared library libpywrap_tensorflow.so
CMakeFiles/tf_core_kernels.dir/home/gaoshan/software/pkgbuild/tensorflow/tensorflow/tensorflow/core/kernels/tensor_array_ops.cc.o: In function `std::unique_ptr<Eigen::TensorMap<Eigen::Tensor<bool const, 2, 1, long>, 16, Eigen::MakePointer>, std::default_delete<Eigen::TensorMap<Eigen::Tensor<bool const, 2, 1, long>, 16, Eigen::MakePointer> > >::get_deleter()':
tensor_array_ops.cc:(.text._ZNSt10unique_ptrIN5Eigen9TensorMapINS0_6TensorIKbLi2ELi1ElEELi16ENS0_11MakePointerEEESt14default_deleteIS6_EE11get_deleterEv[_ZNSt10unique_ptrIN5Eigen9TensorMapINS0_6TensorIKbLi2ELi1ElEELi16ENS0_11MakePointerEEESt14default_deleteIS6_EE11get_deleterEv]+0x28): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `std::tuple_element<1ul, std::tuple<Eigen::TensorMap<Eigen::Tensor<bool const, 2, 1, long>, 16, Eigen::MakePointer>*, std::default_delete<Eigen::TensorMap<Eigen::Tensor<bool const, 2, 1, long>, 16, Eigen::MakePointer> > > >::type& std::get<1ul, Eigen::TensorMap<Eigen::Tensor<bool const, 2, 1, long>, 16, Eigen::MakePointer>*, std::default_delete<Eigen::TensorMap<Eigen::Tensor<bool const, 2, 1, long>, 16, Eigen::MakePointer> > >(std::tuple<Eigen::TensorMap<Eigen::Tensor<bool const, 2, 1, long>, 16, Eigen::MakePointer>*, std::default_delete<Eigen::TensorMap<Eigen::Tensor<bool const, 2, 1, long>, 16, Eigen::MakePointer> > >&)' defined in .text._ZSt3getILm1EJPN5Eigen9TensorMapINS0_6TensorIKbLi2ELi1ElEELi16ENS0_11MakePointerEEESt14default_deleteIS6_EEERNSt13tuple_elementIXT_ESt5tupleIJDpT0_EEE4typeERSE_[_ZSt3getILm1EJPN5Eigen9TensorMapINS0_6TensorIKbLi2ELi1ElEELi16ENS0_11MakePointerEEESt14default_deleteIS6_EEERNSt13tuple_elementIXT_ESt5tupleIJDpT0_EEE4typeERSE_] section in CMakeFiles/tf_core_kernels.dir/home/gaoshan/software/pkgbuild/tensorflow/tensorflow/tensorflow/core/kernels/tensor_array_ops.cc.o
CMakeFiles/tf_core_kernels.dir/home/gaoshan/software/pkgbuild/tensorflow/tensorflow/tensorflow/core/kernels/tensor_array_ops.cc.o: In function `std::default_delete<Eigen::TensorMap<Eigen::Tensor<bool const, 2, 1, long>, 16, Eigen::MakePointer> >::operator()(Eigen::TensorMap<Eigen::Tensor<bool const, 2, 1, long>, 16, Eigen::MakePointer>*) const':
tensor_array_ops.cc:(.text._ZNKSt14default_deleteIN5Eigen9TensorMapINS0_6TensorIKbLi2ELi1ElEELi16ENS0_11MakePointerEEEEclEPS6_[_ZNKSt14default_deleteIN5Eigen9TensorMapINS0_6TensorIKbLi2ELi1ElEELi16ENS0_11MakePointerEEEEclEPS6_]+0x2c): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `operator delete(void*, unsigned long)@@CXXABI_1.3.9' defined in .text section in /usr/lib/gcc/powerpc64le-linux-gnu/5/libstdc++.so
CMakeFiles/tf_core_kernels.dir/home/gaoshan/software/pkgbuild/tensorflow/tensorflow/tensorflow/core/kernels/tensor_array_ops.cc.o: In function `std::default_delete<Eigen::TensorMap<Eigen::Tensor<std::complex<double> const, 2, 1, long>, 16, Eigen::MakePointer> >::operator()(Eigen::TensorMap<Eigen::Tensor<std::complex<double> const, 2, 1, long>, 16, Eigen::MakePointer>*) const':
tensor_array_ops.cc:(.text._ZNKSt14default_deleteIN5Eigen9TensorMapINS0_6TensorIKSt7complexIdELi2ELi1ElEELi16ENS0_11MakePointerEEEEclEPS8_[_ZNKSt14default_deleteIN5Eigen9TensorMapINS0_6TensorIKSt7complexIdELi2ELi1ElEELi16ENS0_11MakePointerEEEEclEPS8_]+0x2c): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `operator delete(void*, unsigned long)@@CXXABI_1.3.9' defined in .text section in /usr/lib/gcc/powerpc64le-linux-gnu/5/libstdc++.so
CMakeFiles/tf_core_kernels.dir/home/gaoshan/software/pkgbuild/tensorflow/tensorflow/tensorflow/core/kernels/tensor_array_ops.cc.o: In function `std::default_delete<Eigen::TensorMap<Eigen::Tensor<std::complex<float> const, 2, 1, long>, 16, Eigen::MakePointer> >::operator()(Eigen::TensorMap<Eigen::Tensor<std::complex<float> const, 2, 1, long>, 16, Eigen::MakePointer>*) const':
tensor_array_ops.cc:(.text._ZNKSt14default_deleteIN5Eigen9TensorMapINS0_6TensorIKSt7complexIfELi2ELi1ElEELi16ENS0_11MakePointerEEEEclEPS8_[_ZNKSt14default_deleteIN5Eigen9TensorMapINS0_6TensorIKSt7complexIfELi2ELi1ElEELi16ENS0_11MakePointerEEEEclEPS8_]+0x2c): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `operator delete(void*, unsigned long)@@CXXABI_1.3.9' defined in .text section in /usr/lib/gcc/powerpc64le-linux-gnu/5/libstdc++.so
CMakeFiles/tf_core_kernels.dir/home/gaoshan/software/pkgbuild/tensorflow/tensorflow/tensorflow/core/kernels/tensor_array_ops.cc.o: In function `std::_Tuple_impl<1ul, std::default_delete<Eigen::TensorMap<Eigen::Tensor<double const, 2, 1, long>, 16, Eigen::MakePointer> > >::_M_head(std::_Tuple_impl<1ul, std::default_delete<Eigen::TensorMap<Eigen::Tensor<double const, 2, 1, long>, 16, Eigen::MakePointer> > >&)':
tensor_array_ops.cc:(.text._ZNSt11_Tuple_implILm1EJSt14default_deleteIN5Eigen9TensorMapINS1_6TensorIKdLi2ELi1ElEELi16ENS1_11MakePointerEEEEEE7_M_headERS9_[_ZNSt11_Tuple_implILm1EJSt14default_deleteIN5Eigen9TensorMapINS1_6TensorIKdLi2ELi1ElEELi16ENS1_11MakePointerEEEEEE7_M_headERS9_]+0x24): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `std::_Head_base<1ul, std::default_delete<Eigen::TensorMap<Eigen::Tensor<double const, 2, 1, long>, 16, Eigen::MakePointer> >, true>::_M_head(std::_Head_base<1ul, std::default_delete<Eigen::TensorMap<Eigen::Tensor<double const, 2, 1, long>, 16, Eigen::MakePointer> >, true>&)' defined in .text._ZNSt10_Head_baseILm1ESt14default_deleteIN5Eigen9TensorMapINS1_6TensorIKdLi2ELi1ElEELi16ENS1_11MakePointerEEEELb1EE7_M_headERS9_[_ZNSt10_Head_baseILm1ESt14default_deleteIN5Eigen9TensorMapINS1_6TensorIKdLi2ELi1ElEELi16ENS1_11MakePointerEEEELb1EE7_M_headERS9_] section in CMakeFiles/tf_core_kernels.dir/home/gaoshan/software/pkgbuild/tensorflow/tensorflow/tensorflow/core/kernels/tensor_array_ops.cc.o
CMakeFiles/tf_core_kernels.dir/home/gaoshan/software/pkgbuild/tensorflow/tensorflow/tensorflow/core/kernels/tensor_array_ops.cc.o: In function `std::default_delete<Eigen::TensorMap<Eigen::Tensor<double const, 2, 1, long>, 16, Eigen::MakePointer> >::operator()(Eigen::TensorMap<Eigen::Tensor<double const, 2, 1, long>, 16, Eigen::MakePointer>*) const':
tensor_array_ops.cc:(.text._ZNKSt14default_deleteIN5Eigen9TensorMapINS0_6TensorIKdLi2ELi1ElEELi16ENS0_11MakePointerEEEEclEPS6_[_ZNKSt14default_deleteIN5Eigen9TensorMapINS0_6TensorIKdLi2ELi1ElEELi16ENS0_11MakePointerEEEEclEPS6_]+0x2c): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `operator delete(void*, unsigned long)@@CXXABI_1.3.9' defined in .text section in /usr/lib/gcc/powerpc64le-linux-gnu/5/libstdc++.so
CMakeFiles/tf_core_kernels.dir/home/gaoshan/software/pkgbuild/tensorflow/tensorflow/tensorflow/core/kernels/tensor_array_ops.cc.o: In function `std::default_delete<Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, long>, 16, Eigen::MakePointer> >::operator()(Eigen::TensorMap<Eigen::Tensor<float const, 2, 1, long>, 16, Eigen::MakePointer>*) const':
tensor_array_ops.cc:(.text._ZNKSt14default_deleteIN5Eigen9TensorMapINS0_6TensorIKfLi2ELi1ElEELi16ENS0_11MakePointerEEEEclEPS6_[_ZNKSt14default_deleteIN5Eigen9TensorMapINS0_6TensorIKfLi2ELi1ElEELi16ENS0_11MakePointerEEEEclEPS6_]+0x2c): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `operator delete(void*, unsigned long)@@CXXABI_1.3.9' defined in .text section in /usr/lib/gcc/powerpc64le-linux-gnu/5/libstdc++.so
CMakeFiles/tf_core_kernels.dir/home/gaoshan/software/pkgbuild/tensorflow/tensorflow/tensorflow/core/kernels/tensor_array_ops.cc.o: In function `std::default_delete<Eigen::TensorMap<Eigen::Tensor<Eigen::half const, 2, 1, long>, 16, Eigen::MakePointer> >::operator()(Eigen::TensorMap<Eigen::Tensor<Eigen::half const, 2, 1, long>, 16, Eigen::MakePointer>*) const':
tensor_array_ops.cc:(.text._ZNKSt14default_deleteIN5Eigen9TensorMapINS0_6TensorIKNS0_4halfELi2ELi1ElEELi16ENS0_11MakePointerEEEEclEPS7_[_ZNKSt14default_deleteIN5Eigen9TensorMapINS0_6TensorIKNS0_4halfELi2ELi1ElEELi16ENS0_11MakePointerEEEEclEPS7_]+0x2c): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `operator delete(void*, unsigned long)@@CXXABI_1.3.9' defined in .text section in /usr/lib/gcc/powerpc64le-linux-gnu/5/libstdc++.so
CMakeFiles/tf_core_kernels.dir/home/gaoshan/software/pkgbuild/tensorflow/tensorflow/tensorflow/core/kernels/tensor_array_ops.cc.o: In function `std::default_delete<Eigen::TensorMap<Eigen::Tensor<signed char const, 2, 1, long>, 16, Eigen::MakePointer> >& std::__get_helper<1ul, std::default_delete<Eigen::TensorMap<Eigen::Tensor<signed char const, 2, 1, long>, 16, Eigen::MakePointer> >>(std::_Tuple_impl<1ul, std::default_delete<Eigen::TensorMap<Eigen::Tensor<signed char const, 2, 1, long>, 16, Eigen::MakePointer> >>&)':
tensor_array_ops.cc:(.text._ZSt12__get_helperILm1ESt14default_deleteIN5Eigen9TensorMapINS1_6TensorIKaLi2ELi1ElEELi16ENS1_11MakePointerEEEEJEERT0_RSt11_Tuple_implIXT_EJS9_DpT1_EE[_ZSt12__get_helperILm1ESt14default_deleteIN5Eigen9TensorMapINS1_6TensorIKaLi2ELi1ElEELi16ENS1_11MakePointerEEEEJEERT0_RSt11_Tuple_implIXT_EJS9_DpT1_EE]+0x24): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `std::_Tuple_impl<1ul, std::default_delete<Eigen::TensorMap<Eigen::Tensor<signed char const, 2, 1, long>, 16, Eigen::MakePointer> > >::_M_head(std::_Tuple_impl<1ul, std::default_delete<Eigen::TensorMap<Eigen::Tensor<signed char const, 2, 1, long>, 16, Eigen::MakePointer> > >&)' defined in .text._ZNSt11_Tuple_implILm1EJSt14default_deleteIN5Eigen9TensorMapINS1_6TensorIKaLi2ELi1ElEELi16ENS1_11MakePointerEEEEEE7_M_headERS9_[_ZNSt11_Tuple_implILm1EJSt14default_deleteIN5Eigen9TensorMapINS1_6TensorIKaLi2ELi1ElEELi16ENS1_11MakePointerEEEEEE7_M_headERS9_] section in CMakeFiles/tf_core_kernels.dir/home/gaoshan/software/pkgbuild/tensorflow/tensorflow/tensorflow/core/kernels/tensor_array_ops.cc.o
CMakeFiles/tf_core_kernels.dir/home/gaoshan/software/pkgbuild/tensorflow/tensorflow/tensorflow/core/kernels/tensor_array_ops.cc.o: In function `std::default_delete<Eigen::TensorMap<Eigen::Tensor<signed char const, 2, 1, long>, 16, Eigen::MakePointer> >::operator()(Eigen::TensorMap<Eigen::Tensor<signed char const, 2, 1, long>, 16, Eigen::MakePointer>*) const':
tensor_array_ops.cc:(.text._ZNKSt14default_deleteIN5Eigen9TensorMapINS0_6TensorIKaLi2ELi1ElEELi16ENS0_11MakePointerEEEEclEPS6_[_ZNKSt14default_deleteIN5Eigen9TensorMapINS0_6TensorIKaLi2ELi1ElEELi16ENS0_11MakePointerEEEEclEPS6_]+0x2c): relocation truncated to fit: R_PPC64_REL24 (stub) against symbol `operator delete(void*, unsigned long)@@CXXABI_1.3.9' defined in .text section in /usr/lib/gcc/powerpc64le-linux-gnu/5/libstdc++.so
CMakeFiles/tf_core_kernels.dir/home/gaoshan/software/pkgbuild/tensorflow/tensorflow/tensorflow/core/kernels/tensor_array_ops.cc.o: In function `void std::_Construct<std::unique_ptr<Eigen::TensorMap<Eigen::Tensor<unsigned char const, 2, 1, long>, 16, Eigen::MakePointer>, std::default_delete<Eigen::TensorMap<Eigen::Tensor<unsigned char const, 2, 1, long>, 16, Eigen::MakePointer> > >, std::unique_ptr<Eigen::TensorMap<Eigen::Tensor<unsigned char const, 2, 1, long>, 16, Eigen::MakePointer>, std::default_delete<Eigen::TensorMap<Eigen::Tensor<unsigned char const, 2, 1, long>, 16, Eigen::MakePointer> > > >(std::unique_ptr<Eigen::TensorMap<Eigen::Tensor<unsigned char const, 2, 1, long>, 16, Eigen::MakePointer>, std::default_delete<Eigen::TensorMap<Eigen::Tensor<unsigned char const, 2, 1, long>, 16, Eigen::MakePointer> > >*, std::unique_ptr<Eigen::TensorMap<Eigen::Tensor<unsigned char const, 2, 1, long>, 16, Eigen::MakePointer>, std::default_delete<Eigen::TensorMap<Eigen::Tensor<unsigned char const, 2, 1, long>, 16, Eigen::MakePointer> > >&&)':
tensor_array_ops.cc:(.text._ZSt10_ConstructISt10unique_ptrIN5Eigen9TensorMapINS1_6TensorIKhLi2ELi1ElEELi16ENS1_11MakePointerEEESt14default_deleteIS7_EEJSA_EEvPT_DpOT0_[_ZSt10_ConstructISt10unique_ptrIN5Eigen9TensorMapINS1_6TensorIKhLi2ELi1ElEELi16ENS1_11MakePointerEEESt14default_deleteIS7_EEJSA_EEvPT_DpOT0_]+0x60): **additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
CMakeFiles/pywrap_tensorflow.dir/build.make:1711: recipe for target 'libpywrap_tensorflow.so' failed
make[2]: *** [libpywrap_tensorflow.so] Error 1
CMakeFiles/Makefile2:6759: recipe for target 'CMakeFiles/pywrap_tensorflow.dir/all' failed
make[1]: *** [CMakeFiles/pywrap_tensorflow.dir/all] Error 2
Makefile:83: recipe for target 'all' failed**

**Comment by girving** [comment]
@mrry Can you comment on this cmake issue?

**Comment by mrry** [comment]
I don't think this error is specific to CMake, but rather the unsupported build platform. Unfortunately I don't have a `ppc64le` machine to reproduce the error, and it's not one of our supported platforms, so I'll have to mark this as "community support".

In case it's helpful, here are a couple of random suggestions:

* Have you tried building with Bazel? (I'm not sure if Bazel is supported on this platform either.) Or the (simpler) Makefile build?
* Can you try adding the `-mcmodel=large` compilation option? (as suggested [here](https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/W51a7ffcf4dfd_4b40_9d82_446ebc23c550/page/IBM%20Advance%20Toolchain%20for%20PowerLinux%20Documentation))

/cc @namrata-ibm, who has been building for PPC, in case this error looks familiar.

**Comment by namrata-ibm** [comment]
I had not faced this error. As @mrry suggests, you could try building with Bazel(which has to be built first).
Also what is the gcc version being used?

**Comment by joshsuihn** [comment]
-mcmodel=large may not work. Try "-Os" option

**Comment by av8ramit** [comment]
Please try the suggestions and reopen if this is still an issue. Thanks.
