### ISSUE TITLE
Is it possible to call TensorBoard smooth function manually?

### ISSUE THREAD

**Issue by KaixiangLin** [tensorflow/tensorflow#7274]
I have two arrays X and Y. 

Is there a function I can call in tensorboard to do the smooth? 

Right now I can do an alternative way in python like:
```python
    sav_smoooth = savgol_filter(Y, 51, 3)
    plt.plot(X, Y)
```
But I didn't get a similar results as shown in tensorboard by doing so. Is there a function I can call?  Could you provide an API that allow this kind of operation? 

Thanks.

**Comment by yaroslavvb** [comment]
@KaixiangLin I'm suspecting this function is implemented in javascript logic of TB so it would be hard to make available, but cc @dandelionmane just in case

**Comment by KaixiangLin** [comment]
@yaroslavvb  Thanks for the comment.  

If directly call the function is not available right now, Could you briefly explain the method how tensorboard smooth the curve? @dandelionmane 

Thanks a lot!

**Comment by girving** [comment]
Please ask questions like these on Stackoverflow (or scicomp).  Github issues are for feature requests and comments.

**Comment by dandelionmane** [comment]
@KaixiangLin You can find the smoothing logic [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/components/vz_line_chart/vz-line-chart.ts#L432)

**Comment by KaixiangLin** [comment]
Thank you.
