### ISSUE TITLE
Feature request: separable convolutions in 3D

### ISSUE THREAD

**Issue by aizvorski** [tensorflow/tensorflow#7278]
I would like a `tf.nn.separable_conv3d` identical to `tf.nn.separable_conv2d` except with separability between dimentions [1,2,3] and 4, for use with 3D CNNs.

Rationale: separable convolutions perform very well in 2D (see: Xception architecture https://arxiv.org/abs/1610.02357 ).  In 3D, the number of parameters grows even faster for non-separable convolutions, so the reduction in parameters from using separable convolutions would be relatively even bigger.  This is one of the reasons 3D networks tend to have a simpler architecture than 2D.  

Necessity: There doesn't seem to be any way to implement this other than in the TF core. (Suggestions?)

**Comment by girving** [comment]
@aizvorski TensorFlow's 2-D separable convs are built out of normal convs and depthwise convs.  The first bit already exists in 3-D.  The second bit can be implemented in Python by splitting, but it's slower than a native op (this is how separable convs in 2D used to work, I think).  We'd be happy to accept a native 3-D version of depthwise conv, but I don't know of plans to do it ourselves.  I also be happy to give some more detail on the no-new-op version of separable conv if you want, though of course it'll be less performant than a native version.

**Comment by aizvorski** [comment]
@girving Thank you!  Yes I would really like some detail on how to do the no-new-op version of separable conv.  The depthwise part seems easy, just with a 1x1x1xN kernel; I couldn't figure out a good way to do the pure spatial conv. I can try to do a native version later if this shows good performance.

**Comment by girving** [comment]
@aizvorski Here's the commit that turned the depthwise conv native: https://github.com/tensorflow/tensorflow/commit/975094c8382ee15dad434278804cb096f9bac84f.  You should be able to do an analogous thing to the 2D case to make a non-native depthwise conv for 3D, and then a separable conv is just depthwise followed by normal conv.

**Comment by alexvicegrab** [comment]
I second that, separable 3D convs are vital to export Xception type architectures to video and medical imaging. What bits of code would need to change to implement a native 3D version? 

@girving There is no nn_ops.depthwise_conv3d_native, so not sure how to address this, I may be missing something.

Thanks in advance!

**Comment by girving** [comment]
@alexvicegrab I don't know of any plans, but we'd be happy to accept contributions.

**Comment by girving** [comment]
@alexvicegrab Also, as I noted above, it's possible to write a slower version of separable convolutions in pure Python.

**Comment by alexvicegrab** [comment]
@girving True, but making a slower version (how much slower?) to some extent defeats the point of implementing separable convolutions, I was hoping to use (or create) a fast version that can take advantage of hardware acceleration, but I'm not sure how to go about it, since I can't seem access the native code of the nn_ops.depthwise_conv2d_native, unless I've been looking in the wrong places. Otherwise I'd be happy to have a go at trying to implement it :)

**Comment by girving** [comment]
Here's the native op: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/depthwise_conv_op.cc

**Comment by yzhwang** [comment]
@chsigg Do you plan to implement separable conv3d or depthwise conv3d?

**Comment by AnishShah** [comment]
Hey! Is anybody working on this?

**Comment by alexvicegrab** [comment]
@AnishShah I'm not working on that project anymore, so I am not. Still think it's an important thing to do, but don't have the time or the nitty-gritty expertise to address it.

**Comment by weiliu620** [comment]
I also wish a separable convolution for 3D image. Signals in 3D is more difficult to learn, and training is slow.

**Comment by nio1814** [comment]
I'll make an attempt to continue what @AnishShah started. We'll see how it goes...

**Comment by cygi1989** [comment]
Hi @nio1814, can you tell us how it goes with this implementation?

**Comment by bhack** [comment]
@nio1814 Do you plan to open a PR with your code?

**Comment by bhack** [comment]
I think this will be quite strategic. Check CVPR 2018 accepted https://github.com/kenshohara/3D-ResNets-PyTorch/

**Comment by bhack** [comment]
Google @s9xie and @murphyk have also a related work [Rethinking Spatiotemporal Feature Learning For Video Understanding](https://arxiv.org/abs/1712.04851)

**Comment by ChristianEschen** [comment]
Any news about the implementation @nio1814

**Comment by bhack** [comment]
@nio1814 What about https://github.com/tensorflow/tensorflow/pull/17961#issuecomment-381127268? /cc @chsigg

**Comment by alalbiol** [comment]
I have found a temporally solution to this using tf.scan to iterate over the feature dimension.
I think that this is not as efficient as a native function, but low level programming of tensorflow
is too hard for me :-)
I have checked it using the 2d depth wise convolution first. The extension to 3d is inmediate:

```python
def tf_scan_depthwise_conv2d():
#First check that we get the same results as with  tf.nn.depthwise_conv2d
#using tf.nn.conv2d and tf.scan

    def f( old,input):
        x_sample = input[0]
        kernel_sample = input[1]

        y_sample = tf.nn.conv2d(x_sample,kernel_sample,[1,1,1,1],"SAME")
        return y_sample
    x_values = np.random.randn(4,5,5,3).astype('float32')
    kernel_values = np.random.randn(2,2,3,2).astype('float32')

    x = tf.constant(x_values)
    kernel = tf.constant(kernel_values)

    y = tf.nn.depthwise_conv2d(x,kernel,[1,1,1,1],"SAME")

    kernel_scan = tf.transpose(kernel,[2,0,1,3])
    kernel_scan = tf.expand_dims(kernel_scan,axis=3)
    x_scan = tf.transpose(x,[3,0,1,2])
    x_scan = tf.expand_dims(x_scan,axis=-1)

    c = tf.scan(f, (x_scan,kernel_scan) ,initializer = tf.zeros((4,5,5,2)))

    c = tf.transpose(c,[1,2,3,0,4])
    c = tf.reshape(c,[4,5,5,6])
    with tf.Session() as sess:
         y_values,kernel_scan_values,x_scan_values,c_values  = sess.run([y,kernel_scan,x_scan,c])

    #check input shapes for the scanned version
    print(kernel_scan_values.shape)
    print(x_scan_values.shape)
    #check output shapes
    print(c_values.shape)
    print(y_values.shape)
    #check values using depthwise_conv2d or the scanned version
    print(y_values[0,0,0,:])
    print(c_values[0,0,0,:])

def tf_scan_depthwise_conv3d():
#Now extend the results to 3D
    def f( old,input):
        x_sample = input[0]
        kernel_sample = input[1]

        y_sample = tf.nn.conv3d(x_sample,kernel_sample,[1,1,1,1,1],"SAME")
        return y_sample

    x_values = np.random.randn(4,5,5,5,3).astype('float32')
    kernel_values = np.random.randn(2,2,2,3,2).astype('float32')

    x = tf.constant(x_values)
    kernel = tf.constant(kernel_values)

    kernel_scan = tf.transpose(kernel,[3,0,1,2,4])
    kernel_scan = tf.expand_dims(kernel_scan,axis=4)
    x_scan = tf.transpose(x,[4,0,1,2,3])
    x_scan = tf.expand_dims(x_scan,axis=-1)
    c = tf.scan(f, (x_scan,kernel_scan) ,initializer = tf.zeros((4,5,5,5,2)))
    c = tf.transpose(c,[1,2,3,4,0,5])
    c = tf.reshape(c,[4,5,5,5,6])

    with tf.Session() as sess:
         kernel_scan_values,x_scan_values,c_values  = sess.run([kernel_scan,x_scan,c])


    print(kernel_scan_values.shape)
    print(x_scan_values.shape)
    print(c_values.shape)
    print(c_values[0,0,0,0,:])
```

**Comment by bhack** [comment]
@nio1814 Check the performance with https://github.com/tensorflow/tensorflow/pull/17961#issuecomment-388372269

**Comment by YuhuaBillChen** [comment]
Any updates for this? I test the code by @alalbiol and the run time results are shown as below:

`normal conv2d 0.3061046600341797ms native time 0.29351091384887695ms scan time 1.5845508575439453ms`

Was running on tensorflow version 1.13.0-dev20181017 on GTX 1080 TI, cuda 9.0, cudnn 7.

**Comment by cangermueller** [comment]
Yes, any updates? Would be super useful to have a tf.nn.separable_conv3d function!

**Comment by tomvars** [comment]
For anyone using Keras, this implementation addresses this issue 
 https://github.com/alexandrosstergiou/keras-DepthwiseConv3D

**Comment by danielkrause** [comment]
> 
> 
> For anyone using Keras, this implementation addresses this issue
> https://github.com/alexandrosstergiou/keras-DepthwiseConv3D

No, it doesn't. It implements just the first step of the Depthwise Separable Convolution.

**Comment by danganea** [comment]
I have opened a PR for native 3D Group Convolutions which enable Depth-wise 3D Convolutions natively as well  #31492

**Comment by danganea** [comment]
My commit was accepted. 

Using the benchmark code [here](https://github.com/tensorflow/tensorflow/pull/31492#issuecomment-520063961)  and replacing group number to the channel number, you get about 2x speedup over manually concatenating the channels over 256 channels.

```
Loop=True, Forward: 15.444471641506786 itr/s
Loop=True, Backward: 4.057799918417722 itr/s

Loop=False, Forward: 29.1905996890655 itr/s
Loop=False, Backward: 8.75012744363749 itr/s
```
Making it separable would mean executing another convolution over the channels.

**Comment by nio1814** [comment]
Cool. These are benchmarks on GPU or CPU?

**Comment by danganea** [comment]
On a 2060 mobile RTX GPU

**Comment by hollowgalaxy** [comment]
@danganea are you providing just the conv3d operation for using depthwise3d or a tf keras layer. 


> I have opened a PR for native 3D Group Convolutions which enable Depth-wise 3D Convolutions natively as well #31492

Also how would you use the depthwise3d portion?

**Comment by danganea** [comment]
The tensorflow commit does not include a keras layer.

The separable operation is a depthwise part + a pointwise part. Meaning what you'd do is have a filter of shape (D,H,W,1,input_depth * depth_multiplier) which you use in a initial tf.nn.conv3d operation. This is the group convolution that does the depthwise part. There will be input_depth * depth_multiplier groups.  Generally it's easy to reason about if depth_multiplier == 1, where there will be as many groups as input channels.

After this depthwise part, you'd do a pointwise kernel to get the desired final depth.

In any case, here's a preliminary keras layer that uses my operation, as a branch of an existing CPU implementation:
https://github.com/danganea/keras-DepthwiseConv3D

Along with a gist of it in action: https://gist.github.com/danganea/01756783499ab3b9524bb495f0d1203b

**Comment by hollowgalaxy** [comment]
I tried your keras layer implimentation, but it seems to fail on simple example.
```
import keras
x = keras.layers.Input([64,224,224,3])
kernel_size=3
strides=1
o = DepthwiseConv3D(kernel_size,
                        strides=strides,
                        padding='same',
                        use_bias=False)(x)
``` 
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1863   try:
-> 1864     c_op = c_api.TF_FinishOperation(op_desc)
   1865   except errors.InvalidArgumentError as e:

InvalidArgumentError: Dimensions must be equal, but are 3 and 1 for 'depthwise_conv3d_3/Conv3D' (op: 'Conv3D') with input shapes: [?,64,224,224,3], [3,3,3,1,3].

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
9 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in _create_c_op(graph, node_def, inputs, control_inputs)
   1865   except errors.InvalidArgumentError as e:
   1866     # Convert to ValueError for backwards compatibility.
-> 1867     raise ValueError(str(e))
   1868 
   1869   return c_op

ValueError: Dimensions must be equal, but are 3 and 1 for 'depthwise_conv3d_3/Conv3D' (op: 'Conv3D') with input shapes: [?,64,224,224,3], [3,3,3,1,3].
```

**Comment by danganea** [comment]
@nio1814  looks like you're not using the version of Tensorflow that includes my commit. Are you?

**Comment by hollowgalaxy** [comment]
I see that makes sense. Is there a nightly version that this commit is featured in?

**Comment by dynamicwebpaige** [comment]
Closing this issue, as the feature seems to have been implemented for both tf.keras and TensorFlow core. Thanks for the suggestion, @aizvorski, and for the add, @danganea! 👍

**Comment by puneetpandey37** [comment]
> Closing this issue, as the feature seems to have been implemented for both tf.keras and TensorFlow core. Thanks for the suggestion, @aizvorski, and for the add, @danganea! 👍

Which Keras and Tensorflow version do I need for this feature?

**Comment by puneetpandey37** [comment]
> My commit was accepted.
> 
> Using the benchmark code [here](https://github.com/tensorflow/tensorflow/pull/31492#issuecomment-520063961) and replacing group number to the channel number, you get about 2x speedup over manually concatenating the channels over 256 channels.
> 
> ```
> // With manual concatenation
> Loop=True, Forward: 15.444471641506786 itr/s
> Loop=True, Backward: 4.057799918417722 itr/s
> // Native group convolution
> Loop=False, Forward: 29.1905996890655 itr/s
> Loop=False, Backward: 8.75012744363749 itr/s
> ```
> 
> Making it separable would mean executing another convolution over the channels.

I am getting this error:
ValueError: Dimensions must be equal, but are 8 and 1 for 'depthwise_conv3d_4/Conv3D' (op: 'Conv3D') with input shapes: [?,14,14,14,8], [3,3,3,1,8].

**Comment by robinglord** [comment]
Can someobdy confirm that the separable_conv3d feature is implemented in the latest release of Tensorflow 2.1 ? I can't find it in the Tensorflow API docs (there is SeparableConv1D and SeparableConv2D, but not SeparableConv3D). Thanks !

**Comment by rocksyne** [comment]
> Can someobdy confirm that the separable_conv3d feature is implemented in the latest release of Tensorflow 2.1 ? I can't find it in the Tensorflow API docs (there is SeparableConv1D and SeparableConv2D, but not SeparableConv3D). Thanks !

SeparableConv3D is still not implemented.

**Comment by jw3126** [comment]
Can't find it either.

**Comment by jw3126** [comment]
@dynamicwebpaige can you reopen, as this feature seems to be missing in Tensorflow 2.1?

**Comment by hunse** [comment]
In Keras, you can do depthwise separable convolution (i.e. what a `DepthwiseConv3D` layer would do, if implemented), by using the `Conv3D` layer with `groups=filters`, where `filters` is the number of channels in your input tensor (which equals the number of channels in your output tensor, too). The only thing that's slightly annoying is that you need to know your number of input channels when you create the layer, rather than when the model is built.

To achieve `SeparableConv3D`, you then just have to put a pointwise convolution layer after this depthwise separable convolution, for example `Conv3D` with a kernel size of `(1, 1, 1)` (though it might be more performant to wrap a `Conv2D` layer with kernel size `(1, 1)` in a `TimeDistributed` layer; both approaches do exactly the same thing).

In pure tensorflow can do depthwise separable convolution with `tf.nn.convolution`. Just pass a kernel that has 1 for the input channel dimension size. This is what `Conv3D` with `groups=filters` does under the hood.

**Comment by petoor** [comment]
Thank you @hunse . That will have to do as a fix for now.
I too would like this to be re opened as a feature request. I think both DepthwiseConv3D and SeparableConv3D are missing in tensorflow.
