### ISSUE TITLE
Mmap of '41' at offset '0' failed with error '22'. - pose classification

### ISSUE THREAD

**Issue by ConnorLynchLV8** [tensorflow/tensorflow#72802]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.15.0

### Custom code

No

### OS platform and distribution

Google Colab

### Python version

3.10.12

### Current behavior?

I was expecting the code to run without errors

### Standalone code to reproduce the issue

```shell
`!wget -q -O movenet_thunder.tflite https://tfhub.dev/google/lite-model/movenet/singlepose/thunder/tflite/float16/4?lite-format=tflite
!git clone https://github.com/tensorflow/examples.git
pose_sample_rpi_path = os.path.join(os.getcwd(), 'examples/lite/examples/pose_estimation/raspberry_pi')
sys.path.append(pose_sample_rpi_path)

# Load MoveNet Thunder model
import utils
from data import BodyPart
from ml import Movenet
movenet = Movenet('movenet_thunder')`
```
```


### Relevant log output

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-8-fcb5b307ea77>](https://kygyo76i4o-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240729-060216_RC00_657091656#) in <cell line: 17>()
     15 from data import BodyPart
     16 from ml import Movenet
---> 17 movenet = Movenet('movenet_thunder')
     18 
     19 # Define function to run pose estimation using MoveNet Thunder.

1 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/interpreter.py](https://kygyo76i4o-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240729-060216_RC00_657091656#) in __init__(self, model_path, model_content, experimental_delegates, num_threads, experimental_op_resolver_type, experimental_preserve_all_tensors, experimental_disable_delegate_clustering)
    462 
    463     if model_path and not model_content:
--> 464       custom_op_registerers_by_name = [
    465           x for x in self._custom_op_registerers if isinstance(x, str)
    466       ]

ValueError: Mmap of '46' at offset '0' failed with error '22'.
```

**Comment by tilakrayal** [comment]
@ConnorLynchLV8,
I tried to execute the code and observed that it was executed without any fail/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/ca94c8afd638c92d4d0e2709ac2cb345/copy-of-movenet.ipynb) and also please have a look at the issue for the reference.

https://github.com/tensorflow/tensorflow/issues/72202#issuecomment-2245024521
https://github.com/tensorflow/tensorflow/issues/70841

Thank you!

**Comment by ConnorLynchLV8** [comment]
Thank you for your response @tilakrayal I was referring to this gist [https://colab.research.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tutorials/pose_classification.ipynb](url).

Based on the comment you linked, is the suggested fix to download the model and upload to Colab and use that instead?

Cheers

**Comment by ConnorLynchLV8** [comment]
I have fixed the problem by downloading google/movenet/tfLite/singlepose-thunder-tflite-float16 from gaggle, however, I now get this error 
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-47-87cdca3ca58e>](https://j8dka4z0ho-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240730-060116_RC00_657538329#) in <cell line: 1>()
     10   )
     11 
---> 12   preprocessor.process(per_pose_class_limit=None)

1 frames
[/usr/local/lib/python3.10/dist-packages/numpy/__init__.py](https://j8dka4z0ho-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240730-060116_RC00_657538329#) in __getattr__(attr)
    322 
    323         if attr in __former_attrs__:
--> 324             raise AttributeError(__former_attrs__[attr])
    325 
    326         if attr == 'testing':

AttributeError: module 'numpy' has no attribute 'str'.
`np.str` was a deprecated alias for the builtin `str`. To avoid this error in existing code, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations`

for this line of code
`preprocessor.process(per_pose_class_limit=None)`

**Comment by tilakrayal** [comment]
@ConnorLynchLV8,
Glad the mentioned error was resolved. Also the error "module 'numpy' has no attribute 'str'" is not related to tensorflow. From the numpy doc, it is mentioned that it was deprecated in numpy 1.20. Please try to check by upgrading the python. Thank you!
