### ISSUE TITLE
“module has no attribute 'learn' ”

### ISSUE THREAD

**Issue by pitercius** [tensorflow/tensorflow#7283]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/tensorflow/tensorflow/issues/6607

### Environment info
Operating System:
 Windows 7 Enterprise

### If possible, provide a minimal reproducible example 

1. I have download and installed the windows docker with:
docker run -p 8888:8888 -e "PASSWORD=****" -d --name tensorflow b.gcr.io/tensorflow-udacity/assignments

2. I run the docker with a jupyter notebook:
docker start tensorflow (and then navigate: 192.168.99.100:8888)

3. The code fails at the beggining:
import tensorflow as tf
import numpy as np
import os
import time
import datetime
**from tensorflow.contrib import learn**

---------------------------------------------------------------------------
**ImportError**                               Traceback (most recent call last)
<ipython-input-6-9bbc1f0d7c04> in <module>()
      8 import datetime
      9 # import tensorflow.contrib as tfc
---> 10 from tensorflow.contrib import learn
     11 
     12 # Parameters

**ImportError: cannot import name learn**

### What other attempted solutions have you tried?
Reinstalling everything and changing tensorflow.contrib by tf.contrib.

What can I do?
Help is appreciated.

**Comment by girving** [comment]
If you import just `tensorflow as tf`, does `tf.contrib.learn` work?

**Comment by pitercius** [comment]
It doesn´t:

**AttributeError                            Traceback (most recent call last)
<ipython-input-2-2c24d9475067> in <module>()
     51 # Build vocabulary
     52 max_document_length = max([len(x.split(" ")) for x in x_text])
---> 53 vocab_processor = tf.contrib.learn.preprocessing.VocabularyProcessor(max_document_length)
     54 x = np.array(list(vocab_processor.fit_transform(x_text)))
     55 

AttributeError: 'module' object has no attribute 'learn'**

**Comment by girving** [comment]
@martinwicke Thoughts?  This is pretty weird.  Could it be related to this even weirder issue?

https://github.com/tensorflow/tensorflow/issues/7285

**Comment by martinwicke** [comment]
contrib is lazy-loaded to avoid some contrib project breaking your TF installation. However, 

```
import tensorflow as tf
print(tf.contrib.learn)
```

should definitely work. 

@pitercius, what code generates the error above?

**Comment by pitercius** [comment]
It should work but it doesn´t:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-efeec648fb66> in <module>()
      1 import tensorflow as tf
----> 2 print(tf.contrib.learn)

**AttributeError: 'module' object has no attribute 'learn'**

@martinwicke , the failing part of the code is:

```
####################################################################################################
## Train
####################################################################################################
import tensorflow as tf
# print(tf.contrib.learn)
import numpy as np
import os
import time
import datetime
# from tensorflow.contrib import learn

# Parameters
# ==================================================

# Data loading params
tf.flags.DEFINE_float("dev_sample_percentage", 0.1, "Percentage of the training data to use for validation")
tf.flags.DEFINE_string("data_file", "./DAT_data_file.txt", "Data source for the data.")
tf.flags.DEFINE_string("target_file", "./DAT_target_file.txt", "Data source for the target.")

# Model Hyperparameters
tf.flags.DEFINE_integer("embedding_dim", 128, "Dimensionality of character embedding (default: 128)")
tf.flags.DEFINE_string("filter_sizes", "3,4,5", "Comma-separated filter sizes (default: '3,4,5')")
tf.flags.DEFINE_integer("num_filters", 128, "Number of filters per filter size (default: 128)")
tf.flags.DEFINE_float("dropout_keep_prob", 0.5, "Dropout keep probability (default: 0.5)")
tf.flags.DEFINE_float("l2_reg_lambda", 0.0, "L2 regularization lambda (default: 0.0)")

# Training parameters
tf.flags.DEFINE_integer("batch_size", 64, "Batch Size (default: 64)")
tf.flags.DEFINE_integer("num_epochs", 200, "Number of training epochs (default: 200)")
tf.flags.DEFINE_integer("evaluate_every", 100, "Evaluate model on dev set after this many steps (default: 100)")
tf.flags.DEFINE_integer("checkpoint_every", 100, "Save model after this many steps (default: 100)")
tf.flags.DEFINE_integer("num_checkpoints", 5, "Number of checkpoints to store (default: 5)")
# Misc Parameters
tf.flags.DEFINE_boolean("allow_soft_placement", True, "Allow device soft device placement")
tf.flags.DEFINE_boolean("log_device_placement", False, "Log placement of ops on devices")

FLAGS = tf.flags.FLAGS
FLAGS._parse_flags()
print("\nParameters:")
for attr, value in sorted(FLAGS.__flags.items()):
    print("{}={}".format(attr.upper(), value))
print("")


# Data Preparation
# ==================================================

# Load data
print("Loading data...")
x_text, y = load_data_and_labels(FLAGS.data_file, FLAGS.target_file)

# Build vocabulary
max_document_length = max([len(x.split(" ")) for x in x_text])
vocab_processor = tf.contrib.learn.preprocessing.VocabularyProcessor(max_document_length)
x = np.array(list(vocab_processor.fit_transform(x_text)))
```

In fact, the code is essentially identical to https://github.com/dennybritz/cnn-text-classification-tf/blob/master/train.py

**Comment by martinwicke** [comment]
Which version of Tensorflow is that?​

**Comment by pitercius** [comment]
I get it with:
docker run -p 8888:8888 -e "PASSWORD=****" -d --name tensorflow b.gcr.io/tensorflow-udacity/assignments 

Could be https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/udacity/Dockerfile ?

**Comment by martinwicke** [comment]
@vincentvanhoucke, I don't know much about that docker file, is it up to date?

**Comment by vincentvanhoucke** [comment]
@martinwicke no, it hasn't been regenerated in a while. I'll put it on my queue. We need to do it after all the API changes.

**Comment by vincentvanhoucke** [comment]
Looks like the current tf Docker image is 1.12.1, which doesn't have the latest API changes which have been incorporated in the assignments already. I'm going to wait until a newer one is created.

**Comment by vincentvanhoucke** [comment]
I pushed a version based on 1.0.0 a few days ago.
