### ISSUE TITLE
Any clear way to restore saved network and parameters?

### ISSUE THREAD

**Issue by benwu232** [tensorflow/tensorflow#7284]
I'm using tensorflow-gpu0.12.1 on a linux-minit18 machine.

I found it is very hard to restore the saved network and its parameters. The closest answer is 

http://stackoverflow.com/questions/33759623/tensorflow-how-to-restore-a-previously-saved-model-python

and 

https://www.tensorflow.org/api_docs/python/state_ops/exporting_and_importing_meta_graphs

I followed the example in the above link using tf.train.import_meta_graph, but it didn't work.

```
with tf.Session() as sess:
  new_saver = tf.train.import_meta_graph('my-save-dir/my-model-10000.meta')
  new_saver.restore(sess, 'my-save-dir/my-model-10000')
```

All I want is something like:

training ...
save_model(model_file)
save_parameters(par_file)
...

predicting...
model = load_model(model_file)
model.load_parameters(par_file)
...

I found similar implementations in Keras or Tensorlayer, etc. I like them because they split the training and predicting tasks and make them independant. In predicting task, I don't have to find and call the same def_network function in training task, which is boring and error prone. 

@yaroslavvb says it is on the roadmap, please make it faster. I'd like to test it ASAP!

Many thanks!
Ben

**Comment by girving** [comment]
Please ask another question on Stackoverflow if the previous questions do not suffice.  The structure you want is doable in current TensorFlow, but Github issues are only for bug reports and feature requests.

**Comment by benwu232** [comment]
Any link so I can have a try?

Thanks!

**Comment by inflation** [comment]
The metagraph importing is working as far as I know. You need to give more information in the SO question. @benwu232

**Comment by benwu232** [comment]
I wrote two examples 
[tf_save.py](https://gist.github.com/benwu232/6b90d6571cc19c5ebb5294919d9f677d) and [tf_restore.py](https://gist.github.com/benwu232/73d95d930c5e1f1555acc91de2a27bf8). 

In tf_save.py, collection is used to save the useful variables. And in tf_restore.py, it is used to restore the useful varibales, such as inputs, outputs, etc.

Conclusion is the apis are right, but you need to use something like collection to save the variables you need to restore, such as inputs and outputs.  I just think my code is bad, because it look a little bit tedious and ugly.

**Comment by girving** [comment]
@benwu232 For future reference, it would probably have helped others more if you'd asked and then asked this question on StackOverflow.
