### ISSUE TITLE
How to reduce the size of the shared library

### ISSUE THREAD

**Issue by saad-koukous** [tensorflow/tensorflow#72878]
**System information**
- OS Platform and Distribution : Ubuntu 22.04.4 LTS
- TensorFlow version 2.7.4
I need to use the tflite c library in a beaglebone black rev3 with this specs:

> processor       : 0
> model name      : ARMv7 Processor rev 2 (v7l)
> BogoMIPS        : 995.32
> Features        : half thumb fastmult vfp edsp thumbee neon vfpv3 tls vfpd32
> CPU implementer : 0x41
> CPU architecture: 7
> CPU variant     : 0x3
> CPU part        : 0xc08
> CPU revision    : 2
> 
> Hardware        : Generic AM33XX (Flattened Device Tree)
> Revision        : 0000
> Serial          : 2218SBB15982
> ldd (Debian GLIBC 2.28-10) 2.28
> gcc version 8.3.0

i'm trying to build the library using this toolchain : gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf
I successfully built a shared library, but the size of the .so file is 4 MB, which is too big for me. How can I reduce it?
is there any way to limit the operators and types required by my model

**Comment by Venkat6871** [comment]
Hi **@saad-koukous** ,
- Could you please use strip command to remove unnecessary symbols from the library. This command can significantly reduce the file size. I giving that command below:
```
arm-linux-gnueabihf-strip libtensorflowlite_c.so
```
- And ensure you are compiling specifically for the ARMv7 architecture to avoid including unnecessary code for other architectures:

```
bazel build --config=elinux_armhf --cpu=armhf //tensorflow/lite:libtensorflowlite_c.so
```
Thank you!

**Comment by saad-koukous** [comment]
Hi @Venkat6871 
I tried using the strip command as you suggested to remove unnecessary symbols from the libtensorflowlite_c.so
However, the size of the library did not change after stripping.

Additionally, I tried compiling the library specifically for the ARMv7 architecture
Unfortunately, the file size remained the same even after these attempts. It seems that there might not be any significant symbols or unnecessary code that can be stripped from the library.

If you have any other suggestions or further optimizations to try, please let me know!

Thank you!
