### ISSUE TITLE
SKFLOW/TFLearn SKCompat does not properly implement SKLearn predict and predict_proba

### ISSUE THREAD

**Issue by jeffheaton** [tensorflow/tensorflow#7287]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

None seem to apply, this is a new issue just introduced with 1.0.0-rc1

### Environment info
Operating System:
Mac
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:

export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.0rc1-py3-none-any.whl

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
1.0.0-rc1
If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

TFLearn has incorrect implementations of ```predict``` and ```predict_proba```, per the [sklearn developer's guide](http://scikit-learn.org/stable/developers/contributing.html#coding-guidelines).  The current (v1.0.0-rc1) version's ```predict``` actually performs as would be expected for ```predict_proba``` and ```SKCompat``` does not include a ```predict_proba```.

SKFLOW/TFLearn's compatibility with sklearn has been broken in various ways since when v0.8 (which worked) was refactored into SKCompat (see #6584).  

The following code shows how the accuracy function fails due to this issue.  This could be fixed with an argmax call, but the core problem is that SKCompat does not properly implement the sklearn functions.

Note, this code is based on the Contrib TF Learn example here:  [https://www.tensorflow.org/tutorials/tflearn/](https://www.tensorflow.org/tutorials/tflearn/)

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from sklearn import cross_validation
from sklearn import metrics
import tensorflow as tf

def main(unused_argv):
  # Load dataset.
  iris = tf.contrib.learn.datasets.load_dataset('iris')
  x_train, x_test, y_train, y_test = cross_validation.train_test_split(
      iris.data, iris.target, test_size=0.2, random_state=42)

  # Build 3 layer DNN with 10, 20, 10 units respectively.
  feature_columns = tf.contrib.learn.infer_real_valued_columns_from_input(
      x_train)
  classifier = tf.contrib.learn.DNNClassifier(
      feature_columns=feature_columns, hidden_units=[10, 20, 10], n_classes=3)
  classifier = tf.contrib.learn.SKCompat(classifier)

  # Fit and predict.
  classifier.fit(x_train, y_train, steps=200)

  # This outputs something with shape [30,3] should output single class predictions
  # See http://scikit-learn.org/stable/developers/contributing.html#coding-guidelines
  # See predict vs predict_proba
  #predictions = classifier.predict(x_test)
  #score = metrics.accuracy_score(y_test, predictions)
  #print('Accuracy: {0:f}'.format(score))

  # predict_proba does not work either:
  classifier.predict_proba(x_test)
  # Generates a: AttributeError: 'SKCompat' object has no attribute 'predict_proba'

if __name__ == '__main__':
  tf.app.run()
```

### What other attempted solutions have you tried?

http://scikit-learn.org/stable/developers/contributing.html#coding-guidelines

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

```
/Users/jeff/anaconda/envs/tf-latest/bin/python /Users/jeff/Dropbox/school/teaching/wustl/classes/T81_558_deep_learning/code/test3.py
/Users/jeff/anaconda/envs/tf-latest/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:Using temporary folder as model directory: /var/folders/bs/_w74fpx157v3vs82q0fwnflr0000gn/T/tmpl7bwdnzy
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
WARNING:tensorflow:From /Users/jeff/anaconda/envs/tf-latest/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/estimators/head.py:1362: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
WARNING:tensorflow:float64 is not supported by many models, consider casting to float32.
Traceback (most recent call last):
  File "/Users/jeff/Dropbox/school/teaching/wustl/classes/T81_558_deep_learning/code/test3.py", line 52, in <module>
    tf.app.run()
  File "/Users/jeff/anaconda/envs/tf-latest/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/Users/jeff/Dropbox/school/teaching/wustl/classes/T81_558_deep_learning/code/test3.py", line 44, in main
    score = metrics.accuracy_score(y_test, predictions)
  File "/Users/jeff/anaconda/envs/tf-latest/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 172, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/Users/jeff/anaconda/envs/tf-latest/lib/python3.5/site-packages/sklearn/metrics/classification.py", line 72, in _check_targets
    check_consistent_length(y_true, y_pred)
  File "/Users/jeff/anaconda/envs/tf-latest/lib/python3.5/site-packages/sklearn/utils/validation.py", line 181, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [30, 3]

Process finished with exit code 1
```

**Comment by MartinThoma** [comment]
Does `SKCompat` still exist in Tensorflow 1.0?

```
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
>>> tf.contrib.learn.SKCompat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'SKCompat'
```

**Comment by jeffheaton** [comment]
Did TensorFlow drop support for scikit-learn? (that would be unfortunate)  Did it get renamed to something else?  Wasn't scikit-learn comparability the main point of skflow?

**Comment by ilblackdragon** [comment]
Hi,

Here is what I currently have `SKCompat` in TF 1.0:
```
In [1]: import tensorflow as tf
tf.contrib.learn.SKC
In [2]: tf.contrib.learn.SKCompat
Out[2]: tensorflow.contrib.learn.python.learn.estimators.estimator.SKCompat

In [3]: tf.__version__
Out[3]: '1.0.0-rc2'
```

Indeed we don't have `predict_proba` at this point implemented in `SKCompat` because the way probabilities can be surfaced from the underlaying `Estimator` depends on your implementation of `model_fn`. You can use `.predict` method and select `outputs` that return probabilities.

**Comment by jeffheaton** [comment]
If you are not going to support predict_proba, I suppose that is okay.  But every scikit-learn model that I've ever seen returns a scalar class index per prediction when predict is called on a model.  Not a vector of probabilities like tflearn is currently doing. You can easily get to the prediction class using an argmax, but it makes it difficult to make TF models interchangeable with other scikit-learn models since the shape of a TF classification is different than any other scikit-learn model.

**Comment by jeffheaton** [comment]
@ilblackdragon I am not showing SKCompat as part of TensorFlow 1.0.  Was scikit-learn compatibility dropped?  I tried your same instructions on TF 1.0 (you used rc2) and I get:

```
>>> import tensorflow as tf
>>> tf.contrib.learn.SKCompat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow.contrib.learn' has no attribute 'SKCompat'
>>> tf.__version__
'1.0.0'
>>>
```

Yet, in 1.0.0 I still get warnings telling me to use SKCompat.  Very confused.

```
Estimator is decoupled from Scikit Learn interface by moving into
separate class SKCompat. Arguments x, y and batch_size are only
available in the SKCompat class, Estimator will only accept input_fn.
Example conversion:
  est = Estimator(...) -> est = SKCompat(Estimator(...))
```

**Comment by CSJDeveloper** [comment]
There are many questions just same as yours. URL_link: https://github.com/tensorflow/tensorflow/issues?utf8=%E2%9C%93&q=tensorflow%20SKCompat.
**Note**:
Maybe you installed tensorflow like this:
    $ pip install tensorflow
After finished, tensorflow-1.0.0 would have been installed, instead the lastest version of tensorflow is tensorflow-1.0.0rc2!!!
So, you really should install tensorflow this way:
    $ pip install --ignore-installed --upgrade  https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0rc2-cp34-cp34m-linux_x86_64.whl

Using the code below to make sure your version is correct:
	print(tf.__version__) ## show v1.0.0-rc2

And change you code like this:
	import tensorflow as tf
	est = tf.contrib.learn.SKCompat(*The model you need*)
	est.fit(..) ## training the model
	est.score() ## make a evaluation e.g: est.score()["accuracy"]
	est.predict(..) ## predict

End:
	Enjoy your coding

Furthermore:
	The source code for SKCompat: 
	tensorflow-1.0.0-rc2/tensorflow/contrib/learn/python/learn/estimators

**Comment by fventer** [comment]
I upgraded to 1.0.1 and I have the same problem:
>>> import tensorflow as tf
>>> tf.contrib.learn.SKCompat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'SKCompat'
>>> tf.__version__
'1.0.1'
>>>

**Comment by martinwicke** [comment]
I made a PR fixing this. It should appear in 1.1, soon.

**Comment by martinwicke** [comment]
And by "this" I mean the fact that SKCompat is hidden. It does not change the behavior of SKCompat that is part of this issue. I'll adjust the PR description.

**Comment by martinwicke** [comment]
We can probably make predict_proba and predict work as expected on comforming classification models, and for simple regression models (which won't support predict_proba). 

However, many (maybe most) actual models have several outputs. What should happen in this case?

**Comment by jeffheaton** [comment]
For models with several outputs, you would probably want to follow the way other scikit-learn models handle this.  If you are going for scikit-learn compatibility.

http://scikit-learn.org/stable/modules/generated/sklearn.multioutput.MultiOutputRegressor.html

**Comment by ilblackdragon** [comment]
Scikit Learn only supports heterogeneous outputs, so can pack them into one
matrix. In Tnesorflow you can have out output is float, one a number and
another a string. And this is fairly regular case (like one classification
that returns class index, probability and class string).
 Due to this we made decision to return different type output.

Alternatively we can make that predict on SKCompat will work into for few
simple cases and if they have multioutput model one will be not be using it.

**Comment by jeffheaton** [comment]
@ilblackdragon I do see your point.  I had assumed the goal of SKCompat was to be compatible with scikit-learn, but I can see that is not the case.  Its easy enough for me to just wrap it myself when I need the to use TensorFlow models with Scikit-Learn that expect standard calls.  Thanks for the information!

**Comment by BKJackson** [comment]
@jeffheaton I'm having the same issue with DNNClassifier and SKCompat. It would help if the tf.contrib.learn Quickstart tutorial were updated to reflect the use of SKcompat rather than the deprecated version that it currently uses (see https://www.tensorflow.org/get_started/tflearn).

**Comment by jeffheaton** [comment]
FYI, I switched to Keras.  It actually implements sklearn in a way that works with sklearn.
