### ISSUE TITLE
How can I get the android tflite r2.16.1 not stripped so ?

### ISSUE THREAD

**Issue by orange-Pai** [tensorflow/tensorflow#72877]
I use the official aar, I have a crash, I want the symbol table to locate the crash stack

**Comment by tilakrayal** [comment]
@nbNobody,
Could you please provide more info/context about the issue like environment which helps to debug the issue. Thank you!

**Comment by nbNobody** [comment]
@tilakrayal I recently upgraded tensorflow lite from 2.14.0 to 2.16.1, and now there is a crash that didn't occur before. Since there is no symbol table, I can't figure out what went wrong. So I want to know where I can get the so symbol table for release 2.16.1?

**Comment by nbNobody** [comment]
it's a SIGSEGV(SEGV_MAPERR)
<img width="975" alt="image" src="https://github.com/user-attachments/assets/27d30182-064f-4bac-b762-3418a245fa7a">

**Comment by sawantkumar** [comment]
Hi @nbNobody ,

You will need to build tflite with debugging symbols enabled. Below command can do the same . Let me know if this solves your issue.

`bazel build -c dbg //tensorflow/lite:libtensorflowlite.so`

**Comment by nbNobody** [comment]
yes, I can build the so by myself.
What I want to know is whether TFLite official can provide symbol table?
@sawantkumar

**Comment by sawantkumar** [comment]
Hi @pkgoogle , can you please take a look ?

**Comment by pkgoogle** [comment]
Hi @nbNobody, we don't compile with debug symbols for the official aar for obvious reasons. To accomplish what you want, please build your own custom aar with debug symbols and use that aar when reproducing your issue: https://www.tensorflow.org/lite/android/lite_build. The docker workflow is recommended (to ensure you will not run into environmental issues)

For this command:

```sh
bazel build -c opt --cxxopt=--std=c++17 --config=android_arm64 \
  --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a \
  --define=android_dexmerger_tool=d8_dexmerger \
  --define=android_incremental_dexing_tool=d8_dexbuilder \
  //tensorflow/lite/java:tensorflow-lite
```

switch to debug:
```sh
bazel build -c dbg --cxxopt=--std=c++17 --config=android_arm64 \
  --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a \
  --define=android_dexmerger_tool=d8_dexmerger \
  --define=android_incremental_dexing_tool=d8_dexbuilder \
  //tensorflow/lite/java:tensorflow-lite
```

**Comment by nbNobody** [comment]
Thanks. @pkgoogle 
But I still don't understand why it is not provided. Can you explain it more clearly?🙏

**Comment by pkgoogle** [comment]
Hi @nbNobody, in general it's not expected to debug w/ the official AAR, it is built for efficiency/optimization... I suppose we can release one with debug symbols but that will require maintenance in documentation. Also if you need it that means you can probably rebuild it, also to test out any changes you would need to rebuild it, so you would have to do something like this anyways. So it doesn't seem that productive/useful to include an "official" debug symbol AAR.

**Comment by nbNobody** [comment]
Thanks. It would be great if Tflite could maintain a symbol table.
@pkgoogle

**Comment by ninh-huynh** [comment]
> Hi @nbNobody, in general it's not expected to debug w/ the official AAR, it is built for efficiency/optimization... I suppose we can release one with debug symbols but that will require maintenance in documentation. Also if you need it that means you can probably rebuild it, also to test out any changes you would need to rebuild it, so you would have to do something like this anyways. So it doesn't seem that productive/useful to include an "official" debug symbol AAR.

I still do not understand. Why we don't include symbols in the release build? If we build with `-c opt` and combine with `--define=tflite_keep_symbols=true`, we can still have efficiency & symbols. I agree that `-c dbg` is not a best choice (Already tried it, and run-time performance decreased a lot) but our users also have a lot crashes with unknown stack trace in firebase crashlytic and the problem just happened when we upgraded to TensorFlow Lite 2.16.1 (we use version 2.9 before)


Before
```
bazel build -c opt --cxxopt=--std=c++17 --config=android_arm64 \
  --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a \
  --define=android_dexmerger_tool=d8_dexmerger \
  --define=android_incremental_dexing_tool=d8_dexbuilder \
  //tensorflow/lite/java:tensorflow-lite
```

After
```
bazel build -c opt --cxxopt=--std=c++17 --config=android_arm64 \
  --fat_apk_cpu=x86,x86_64,arm64-v8a,armeabi-v7a \
  --define=android_dexmerger_tool=d8_dexmerger \
  --define=android_incremental_dexing_tool=d8_dexbuilder \
  --define=tflite_keep_symbols=true \
  //tensorflow/lite/java:tensorflow-lite
```


+CC @tilakrayal, @pkgoogle

**Comment by pkgoogle** [comment]
Hi @arfaian, can you please take a look ... do you feel we can do this? Thanks.

**Comment by gaikwadrahul8** [comment]
Hi, @orange-Pai 
Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/44

Let us know if you have any questions. Thanks.
