### ISSUE TITLE
Are linkopts propagated from copts and/or deps ?

### ISSUE THREAD

**Issue by riless** [tensorflow/tensorflow#7288]
The linker complains about not finding `-lpthread`, while I didn't add this flag to linkopts.

I've checked the executed command, and in fact there is extra flags on it `-lz  -lpthread ...`.

Where did they came from ? Is there a workaround for this ?

More details
====

BUILD file
---

```
cc_binary(
    name = "libfoo.so",
    srcs = glob([
         "jni/**/*.cc",
         "jni/**/*.h",
    ]),
    copts = [ "-fexceptions", "-DEIGEN_AVOID_STL_ARRAY",
              "-mfpu=neon", "-std=c++11",
              "-DMIN_LOG_LEVEL=0", "-DTF_LEAN_BINARY",
              "-O2", ],
    linkopts = [
        "-llog",
        "-lm",
    ],
    linkshared = 1,
    deps = [
        "@org_tensorflow//tensorflow/core:android_tensorflow_lib",
        "@boringssl//:crypto",
    ],
)
```

Command
---
`bazel build -c opt //:libfoo.so --crosstool_top=//external:android/crosstool --cpu=armeabi-v7a --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --verbose_failures --sandbox_debug --strategy=CppLink=standalone`

Full error
---

```
...
  external/bazel_tools/tools/cpp/link_dynamic_library.sh no ignored ignored ignored external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc -shared -o bazel-out/arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/libfoo.so -Wl,-whole-archive bazel-out/arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/external/org_tensorflow/tensorflow/core/libandroid_tensorflow_lib.lo -Wl,-no-whole-archive -Wl,-whole-archive bazel-out/arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/external/org_tensorflow/tensorflow/core/kernels/libandroid_tensorflow_kernels.lo -Wl,-no-whole-archive -Wl,-whole-archive bazel-out/arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/external/org_tensorflow/tensorflow/core/libandroid_tensorflow_lib_lite.lo -Wl,-no-whole-archive -Wl,-whole-archive bazel-out/arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/external/org_tensorflow/tensorflow/core/libprotos_all_cc.a -Wl,-no-whole-archive -Wl,-whole-archive bazel-out/arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/external/protobuf/libprotobuf.a -Wl,-no-whole-archive -Wl,-whole-archive bazel-out/arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/external/protobuf/libprotobuf_lite.a -Wl,-no-whole-archive -Wl,-whole-archive bazel-out/arm-linux-androideabi-4.9-v7a-gnu-libstdcpp-opt/bin/external/boringssl/libcrypto.a -Wl,-no-whole-archive external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_static.a external/androidndk/ndk/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a -llog -lm -lz -lpthread -static-libgcc -no-canonical-prefixes '-march=armv7-a' -Wl,--fix-cortex-a8 '--sysroot=external/androidndk/ndk/platforms/android-21/arch-arm'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
external/androidndk/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lpthread
collect2: error: ld returned 1 exit status
Target //:libfoo.so failed to build

```

**Comment by riless** [comment]
```
$ cd tensorflow
$ git log -1
commit ac352bc807410c8a863d0b95202cceeb62ed0f10
Author: gunan <gunan@google.com>
Date:   Sun Feb 5 22:19:11 2017 -0800

    Simplify cuDNN library handling in configure script. (#7269)
    
    cuda_configure.bzl now handles the more complicated operations.
```

**Comment by girving** [comment]
@jart Have you seen this before?

**Comment by jart** [comment]
Since copts and linkopts are viral and propagate to dependencies, `-lpthread` is most likely being inherited from `@boringssl//:crypto`. See: https://github.com/google/boringssl/blob/bbcaa15b0647816b9a1a9b9e0d209cd6712f0105/BUILD#L91

If linking against BoringSSL for an Android build is genuinely a good thing to do, then this could be a bug. Hey @petewarden what's the correct way to get SSL functionality for Android code? Should our friend be using a different library?

**Unrelated suggestions:**

> name = "libfoo.so",

Just name it `"foo"` because when Bazel builds this, it will prefix `lib` and append `.so` by default.

>    copts = [ "-fexceptions", "-DEIGEN_AVOID_STL_ARRAY",
>              "-mfpu=neon", "-std=c++11",
>              "-DMIN_LOG_LEVEL=0", "-DTF_LEAN_BINARY",
>              "-O2", ],

Many of these flags might already be inherited from the `@org_tensorflow//tensorflow/core:android_tensorflow_lib` dependency.

The `-O2` (or maybe `-O3`) flag is set by default when you say `bazel build -c opt`.

Bazel should already pass flags like `-std=c++11` by default.

Another thing to note is that `bazel build -s //blah` is good for troubleshooting.

**Comment by riless** [comment]
@jart Thank you for your answer.

I think a similar question is discussed [here](https://github.com/google/protobuf/issues/1373#issuecomment-204619831). but I don't understand proposed solution, can you help me ?

> Just name it "foo" because when Bazel builds this, it will prefix lib and append .so by default.

`BUILD:40:18: in linkshared attribute of cc_binary rule //:foo: 'linkshared' used in non-shared library.`

> Many of these flags might already be inherited from the @org_tensorflow//tensorflow/core:android_tensorflow_lib dependency.

You are right, only `-std=c++11` is required here.

**Comment by andrewharp** [comment]
@riless @jart
-lpthread is not necessary or possible on Android, so it sounds like the solution would be to add another condition for the select statement as in the linked commit https://github.com/google/protobuf/pull/1386:

```
    linkopts = select({
        ":mac_x86_64": [],
        ":android": [],
        "//conditions:default": ["-lpthread"],
    }),
```

which would necessitate adding a config setting like so:

```
config_setting(
    name = "android",
    values = {
        "crosstool_top": "//external:android/crosstool",
    },
    visibility = ["//visibility:public"],
)
```

The only other workaround I know of that doesn't require editing the other repository is to create a dummy libpthread.so target, but that's pretty hacky.

**Comment by riless** [comment]
I'd like to go with the _dummy libpthread.so target_ solution.

I don't know how to do this. I've tried to add a target like this.

```
cc_library(
    name = "pthread",
    srcs = ["third_party/empty.cc"],
    visibility = ["//visibility:public"],
    linkstatic = 1
)
```

And added it to deps of libfoo.so

```
cc_binary(
    name = "libqscamera.so",
   ...
   deps = [
        "pthread",
        ...
  ]
)
```

but I still have the `cannot find -lpthread` error.

**Comment by andrewharp** [comment]
@riless See https://github.com/tensorflow/tensorflow/commit/cd53f3c3302c9312c1840389a9988a879b8b9dd5#diff-06b90d704990e9b4f5adadb18c837b64

**Comment by riless** [comment]
@andrewharp  it works now, thank you.

I'll still go with this solution as I want boringssl to be downloaded on build.
