### ISSUE TITLE
"ValueError: The layer sequential has never been called and thus has no defined output." when the model's been build and called

### ISSUE THREAD

**Issue by Senantq** [tensorflow/tensorflow#72915]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tensorflow[and-cuda]==2.17

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 24.04 LTS

### Python version

3.11

### CUDA/cuDNN version

12.4

### GPU model and memory

RTX A4500 laptop

### Current behavior?

I loaded a .keras model that I've just trained on a server. The model has been trained on the very same versions of TF and Keras that I am using locally. 

I loaded the model and used a custom implementation of the LayerCAM saliency function where I am creating a submodel using the following: grad_model = tf.keras.models.Model([model.inputs], [model.get_layer(layer_name).output, model.output]). However, the error arises. 

### Standalone code to reproduce the issue

```shell
Here's a Google Drive link to a code, the model weights and an input to reproduce the error: https://drive.google.com/drive/folders/15J_ghWXWbs8EmSVXedH6sJRvJcPUSTIW?usp=sharing
```

### Relevant log output

```shell
ValueError                                Traceback (most recent call last)
Cell In[1], line 45
     42         class_activation_map = tf.expand_dims(class_activation_map, axis=-1)
     43     return class_activation_map
---> 45 layer_cam_test = layer_cam(img = test_sample, model=model, label_index = 0)

Cell In[1], line 24, in layer_cam(img, label_index, model)
     22 print(layer_names)
     23 for layer_name in layer_names[-1:]:
---> 24     grad_model = tf.keras.models.Model([model.inputs], [model.get_layer(layer_name).output, model.output]) #bug's here
     25     with tf.GradientTape() as tape:
     26         tape.watch(img)

File ~/miniconda3/envs/envtfnightly/lib/python3.11/site-packages/keras/src/ops/operation.py:266, in Operation.output(self)
    256 @property
    257 def output(self):
    258     """Retrieves the output tensor(s) of a layer.
    259 
    260     Only returns the tensor(s) corresponding to the *first time*
   (...)
    264         Output tensor or list of output tensors.
    265     """
--> 266     return self._get_node_attribute_at_index(0, "output_tensors", "output")

File ~/miniconda3/envs/envtfnightly/lib/python3.11/site-packages/keras/src/ops/operation.py:285, in Operation._get_node_attribute_at_index(self, node_index, attr, attr_name)
    269 """Private utility to retrieves an attribute (e.g. inputs) from a node.
    270 
    271 This is used to implement the properties:
   (...)
    282     The operation's attribute `attr` at the node of index `node_index`.
    283 """
    284 if not self._inbound_nodes:
--> 285     raise ValueError(
    286         f"The layer {self.name} has never been called "
    287         f"and thus has no defined {attr_name}."
    288     )
    289 if not len(self._inbound_nodes) > node_index:
    290     raise ValueError(
    291         f"Asked to get {attr_name} at node "
    292         f"{node_index}, but the operation has only "
    293         f"{len(self._inbound_nodes)} inbound nodes."
    294     )

ValueError: The layer sequential has never been called and thus has no defined output.
Click to add a cell.
```

**Comment by sc21lt** [comment]
I get exactly the same problem when trying to create a gradcam model, to explain a CNN prediction, I'm using TensorFLow 2.17.
Still haven't found a solution.

**Comment by sc21lt** [comment]
I've figured it out.
I believe the layer "Sequential" is considered the last layer of our networks (for some reason), but this layer doesn't actually have an output, instead, you need to replace this with the last actual layer.
So instead of:
grad_model = tf.keras.models.Model([model.inputs], [model.get_layer(layer_name).output, model.output]) #bug's here

Use this:
grad_model = keras.models.Model(
[model.inputs], 
[model.get_layer(last_conv_layer_name).output, 
model.get_layer(Name_of_last_deep_layer).output]) #right here you should put your last layer's name (you can figure that out from running model.summary) mine was 'dense_2'

Hope this helps :)

**Comment by Senantq** [comment]
Thank you for this workaround sc21lt. I don't think we are supposed to do so as in the Keras tutorial for graCAM they are still using 'model.outputs', but thanks, now this step works. 
However, have you got anything else than None gradients? I don't know if this is due to my time distributed layers but it can't get any gradients when using whether grad_model = tf.keras.models.Model([model.inputs], [model.get_layer(layer_name).output, model.layers[-1].output]) or grad_model = tf.keras.models.Model([model.inputs], [model.get_layer(layer_name).output, model.get_layer('dense').output]). However it works perfectly fine when I use vanilla saliency that doesn't create a new grad_model..

**Comment by Senantq** [comment]
Just a little update, the problem with the null gradients only appears when loading the layer from the .keras file. If the model code is written in the code I don't have null gradients... So there seems to be two different bugs here

**Comment by 25aswada** [comment]
sc21It Thank you so much!!

**Comment by tilakrayal** [comment]
@Senantq,
Looks like this issue is more related to Keras-team/keras repo. Could you please try to raise the issue in the repo for the quick resolution. Thank you!

**Comment by Senantq** [comment]
It is done, but the workaround found by sc21It produce null gradient with tf gradient tape, am i supposed to close this one ?

**Comment by tilakrayal** [comment]
@Senantq,
Yeah, please feel free to move this issue to close this issue and raise another issue for the gradient tape. Thank you!

**Comment by Yosuf20** [comment]
i am still having this issue
