### ISSUE TITLE
Import errors for python keras module

### ISSUE THREAD

**Issue by vixhead** [tensorflow/tensorflow#72946]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.14+

### Custom code

No

### Python version

3.10.13

### Current behavior?

While working with `saving` module in `python.keras` some functions raise `importError`.
```cmd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name '__version__' from 'tensorflow.python.keras'
```

Since `tensorflow==2.14.0` the `__version__` is missing from the `__init__.py`. ( removed in https://github.com/tensorflow/tensorflow/commit/5368a3ad4719842eecae9e4c965b1a5d072cb9e5 )

- [2.13 __init__.py](https://github.com/tensorflow/tensorflow/blob/v2.13.0/tensorflow/python/keras/__init__.py)
- [2.14+ __init__.py](https://github.com/tensorflow/tensorflow/blob/v2.14.0/tensorflow/python/keras/__init__.py)

Some functions eg. `hdf5_format.save_weights_to_hdf_5_group()` still import it in versions `2.14+` [See here for tf 2.15.1](https://github.com/tensorflow/tensorflow/blob/v2.15.1/tensorflow/python/keras/saving/hdf5_format.py#L625)

```
def save_weights_to_hdf5_group(f, layers):
  """Saves the weights of a list of layers to a HDF5 group.

  Args:
      f: HDF5 group.
      layers: List of layer instances.
  """
  from tensorflow.python.keras import __version__ as keras_version  # pylint: disable=g-import-not-at-top
  ...
```

### Standalone code to reproduce the issue

```shell
from tensorflow.python.keras.saving import hdf5_format

# raises import error
hdf5_format.save_weights_to_hdf_5_group(...)

OR

from tensorflow.python.keras import __version__
```

**Comment by tilakrayal** [comment]
@vixhead,
tensorflow/python/keras code is a legacy copy of Keras since the TensorFlow v2.7 release. Please try to remove any import of tensorflow.python.keras and use the public API **from tensorflow import keras** till the tensorflow v2.15 and for later releases try to import  as **import keras** for the keras3.0 version. 

Also please try to raise the issue of Keras related in the Keras-team/Keras repo for the quick resolution. Thank you!

**Comment by vixhead** [comment]
Thanks for the answer. I guess we will have to switch to keras public API then if we want to use 2.14+ versions. (and import keras for 2.15+)
