### ISSUE TITLE
tf.get_collection to extract variables of one scope 

### ISSUE THREAD

**Issue by VigneshSrinivasan10** [tensorflow/tensorflow#7295]
Hi,

I have `n`(e.g: n=3) scopes and `x` (e.g: x=4) no of Variables defined in each scope. 
The scopes are:

        model/generator_0
        model/generator_1
        model/generator_2

Once I compute the loss, I want to extract and provide all the variables from only one of the scope based on a criteria during run-time. Hence the index of the scope `idx` that I select is an argmin tensor cast into `int32` 

        <tf.Tensor 'model/Cast:0' shape=() dtype=int32>

I have already tried: 

        train_vars = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, 'model/generator_'+tf.cast(idx, tf.string)) 

which obviously did not work. 
Is there any way to get all the `x` Variables belonging to that particular scope using `idx` to pass into the optimizer.
Forgive me if this question doesnt fit into tensorflow issues. 

Thanks in advance!
Vignesh Srinivasan

**Comment by VigneshSrinivasan10** [comment]
@yaroslavvb : I have posted it there now. 
http://stackoverflow.com/questions/42073239/tf-get-collection-to-extract-variables-of-one-scope

**Comment by girving** [comment]
Thanks @yaroslavvb!
