### ISSUE TITLE
Slow GPU performance

### ISSUE THREAD

**Issue by beraybentesen** [tensorflow/tensorflow#7297]
Fresh installed on Azure Linux VM with Nvidia Tesla M60 which has 2x8 GB Ram and dual GPU but program prints only one GPU and 8 GB ram as available. Result is worse than GTX 1080.

I can't find specific information for Tesla M60. Is there any trick for dual core GPU's ?

**Comment by yaroslavvb** [comment]
1. You can't match fp32 performance of good gaming card with the current cloud compute offering. M60 is rated for peak 3.8 TFlops per core, whereas 1080 is is 8.4 TFlops. Also, M60 is an older Pascal architecture, so it's peak flops are harder to achieve.
2. Do any other tools see both GPUs? Can you rule out driver issues? Our system people had some difficulty getting multi-GPU setups to work on Azure although I don't have details handy.
3. TensorFlow things usually only utilize 1 GPU, you need a special architecture that will use more than one. Cifar multi-GPU example is one such -- https://www.tensorflow.org/tutorials/deep_cnn/#training_a_model_using_multiple_gpu_cards

**Comment by beraybentesen** [comment]
Thank you for detailed information. 

Output when I run code : 

Found device 0 with properties: 
name: Tesla M60
major: 5 minor: 2 memoryClockRate (GHz) 1.1775
pciBusID 85bb:00:00.0
Total memory: 7.93GiB
Free memory: 7.86GiB

Also output from nvidia-smi 

![screen shot 2017-02-07 at 04 43 07](https://cloud.githubusercontent.com/assets/6421164/22674263/a9c7937a-ece7-11e6-9f0d-197c9c4cf63e.png)

I work with neural style transfer between two images which takes minutes (almost same with my local gtx 970 ) and I'm not satisfied because I want to return result with REST Api and minutes are so long in this case. 

I will check  Cifar multi-GPU example definitely. Thanks again.
