### ISSUE TITLE
No plan for official doc of any other languages than English?

### ISSUE THREAD

**Issue by keonkim** [tensorflow/tensorflow#73]
I am planning on translating the docs into Korean, should I be distributing it on my own?

**Comment by luiscosio** [comment]
Same here, planning on translating them to spanish.

**Comment by Foorack** [comment]
There should probably me made an official translation project on a service such a crowdin to properly manage this. Distributing un-official translations of the documentation would probably result in misinterpretation and old-docs floating around. :/ I like the idea of a translated documentation and I believe it would help many people getting started with tensorflow.

**Comment by martinwicke** [comment]
We may internationalize part of the website, but almost certainly not the API docs. The reason is simply that we wouldn't be able to keep the translated documentation up to date with the code, so it would be of very limited use.

**Comment by marcotrombetti** [comment]
I don't want to spam here... but my company, Translated.net, has been a Google provider for human translation services for the last 10 years. We are now testing Tensorflow to speed ups the translator work thought better AI suggestions.
So if you need help we can manage the crowd translation contributions and integrate with pro translators when needed.

In case, just ping me at first name at translated.net
