### ISSUE TITLE
[RNN] unable to quantize RNN with customized cell

### ISSUE THREAD

**Issue by Voivio** [tensorflow/tensorflow#73002]
### 1. System information

- OS Platform and Distribution: Ubuntu 22.04.4 LTS
- TensorFlow installation: pip package
- TensorFlow library: 2.18.0-dev20240801

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

A minimal example is available in this [Colab notebook](https://colab.research.google.com/drive/1GGdTio3XNj9Jg-CKpyV376RRlRy8_Gs1?usp=sharing).

### 3. Failure after conversion

None

### 4. (optional) RNN conversion support
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

### 5. (optional) Any other info / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I wanted to implement a RNN using customized cells. When I try to quantize the model, the conversion can not be finished.

The error message looks like:

`
INFO:tensorflow:Assets written to: [/tmp/tmp6jab2_an/assets](https://file+.vscode-resource.vscode-cdn.net/tmp/tmp6jab2_an/assets)
INFO:tensorflow:Assets written to: [/tmp/tmp6jab2_an/assets](https://file+.vscode-resource.vscode-cdn.net/tmp/tmp6jab2_an/assets)
[/home/d/miniconda3/envs/tflite_model/lib/python3.9/site-packages/tensorflow/lite/python/convert.py:953](https://file+.vscode-resource.vscode-cdn.net/home/dd/miniconda3/envs/tf_env/lib/python3.9/site-packages/tensorflow/lite/python/convert.py:953): UserWarning: Statistics for quantized inputs were expected, but not specified; continuing anyway.
  warnings.warn(
2024-08-01 21:32:47.659189: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:378] Ignored output_format.
2024-08-01 21:32:47.659202: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:381] Ignored drop_control_dependency.

The Kernel crashed while executing code in the current cell or a previous cell. 
Please review the code in the cell(s) to identify a possible cause of the failure. 
Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. 
View Jupyter [log](command:jupyter.viewOutput) for further details.
`

No traceback is available as the notebook kernel crashes. When running in python script, segmentation fault happens.

By setting breakpoints, the error seems to happen with Line 153 tensorflow/tensorflow/lite/python/optimize/calibrator.py ([here](https://github.com/tensorflow/tensorflow/blob/02e39547a0d551e5bb0c66e5e0e0c319a33f75ff/tensorflow/lite/python/optimize/calibrator.py#L152)). The underlying cc code is raising the error,

Many thanks for the help with this issue!

**Comment by pkgoogle** [comment]
Hi @Voivio, the easiest way to accomplish this right now is to create a [custom RNN in PyTorch](https://discuss.pytorch.org/t/implementation-of-multiplicative-lstm/2328/4) and convert using [AI-Edge-Torch](https://github.com/google-ai-edge/ai-edge-torch), does this work for you?

**Comment by Voivio** [comment]
Hi @pkgoogle, thanks for your quick replay. I have quickly tested this out in the [Colab Notebook](https://colab.research.google.com/drive/1bkinOGC1Hwcr3rq1VDKNPNDgcXiUv2W1?usp=sharing) using this library. This ai-edge-torch library can convert the RNN with customized cells without errors, yet it is not actually converting operations happened inside (though those outside are fine).

So now I give up on using the RNN structure provided from keras and decide to manually handling all hidden states. I have no more questions regarding this issue and please feel free to close it if there will be no more updates on it! 

Many thanks again.
