### ISSUE TITLE
Creating cyclic graphs with the C API

### ISSUE THREAD

**Issue by malmaud** [tensorflow/tensorflow#7303]
I'm trying to use the C API to create a cyclic graph that corresponds to a while loop with `merge` and `switch` operations. 

It doesn't seem possible though, since `TF_AddInput` requires a `TF_Operation` pointer, which in turn can only come from `TF_FinishOperation`, which expects all the inputs of the `TF_OperationDescription` to be filled in.  How can you create cyclic graph by creating nodes one at a time, if to create each node, all its input must already be created?

Just wanted to check I'm not missing anything. Thanks!

**Comment by jmchen-g** [comment]
I believe you need to have all inputs ready in the C API for now. @yuanbyu can give suggestions on the while loop construction. Thanks.

**Comment by malmaud** [comment]
Great. It also occurs to me that I could perhaps just construct the appropriate `GraphDef` proto for my cyclical graph and then use `TF_ImportGraphDef`.

**Comment by asimshankar** [comment]
Support for creating while loops from the C API is in progress (@skye), but is not there yet.

In the mean time, yes, you can still create the graph in python and then importing it using `TF_ImportGraphDef`

**Comment by malmaud** [comment]
Closed now by https://github.com/tensorflow/tensorflow/commit/661058e52460b36417573e2c5a73de9a8b9e5edb?

**Comment by skye** [comment]
Yes, thanks!
