### ISSUE TITLE
Python Pandas in Docker Images

### ISSUE THREAD

**Issue by thesuperzapper** [tensorflow/tensorflow#7304]
### Feature

What are everyone's opinions on including Python Pandas in the [Docker images](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker)?

### Reason

TF.Lean is commonly used with Pandas for data ingestion, (And [in many](https://www.tensorflow.org/tutorials/wide/) of the [examples](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/text_classification.py)). The Docker implementation is a noob-friendly way to install TensorFlow, and given this, is likely to be used with TF.Learn.

### Pull Request
If we decide to implement this, here's a Pull Request: #7305

**Comment by girving** [comment]
@caisq Preferences?

**Comment by caisq** [comment]
@thesuperzapper @girving I agree that pandas is a frequently used package for TF Docker image users. According to my analysis, this leads to an increase in the docker image size by an modest 18 MB. So I will approve this PR. Thank you for sending the PR.
