### ISSUE TITLE
The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.  Aborted (core dumped)

### ISSUE THREAD

**Issue by bhavesh-hirpara** [tensorflow/tensorflow#73084]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.9.3

### Custom code

No

### OS platform and distribution

Ubuntu 22.04.1 LTS

### Mobile device

Ubuntu 22.04.1 LTS

### Python version

3.10.12

### CUDA/cuDNN version

No GPU

### Current behavior?

I am not able to use [spleeter](https://github.com/deezer/spleeter) as it rely on tensorflow. [I am getting msg when  using spleeter as it depends on tensorflow](https://github.com/deezer/spleeter/issues/902)
`The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.
Aborted (core dumped)
`

It can be tested by just installing `pip install tensorflow==2.9.3` also
(spleeterenv) root@mypc:~/spleeter_app# python3 -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"
The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.
Aborted (core dumped)

### Standalone code to reproduce the issue

```shell
pip install tensorflow==2.9.3

There should be ready binary compiled with sse2 capable cpu to install via pip
```

### Relevant log output

```shell
The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.
Aborted (core dumped)
```

**Comment by Venkat6871** [comment]
Hi @bhavesh-hirpara ,
- Thank you for bringing this issue to our attention and I was trying to replicate the same behaviour from my end with sample .mp3 file in Google colab with Tensorflow version 2.9.3 and I did not observe behavior which is mentioned in the issue template so it seems like working as expected, please refer this [gist-file](https://colab.sandbox.google.com/gist/gaikwadrahul8/eb5905856150c4034b8c4f2b05b0480e/test-73084.ipynb) if I have missed something here please let me know

Thank you for your cooptation and patience.
