### ISSUE TITLE
Small inaccuracy in Mandelbrot tutorial

### ISSUE THREAD

**Issue by altsoph** [tensorflow/tensorflow#7308]
Just noticed a small inaccuracy in  [the Mandelbrot tutorial](https://www.tensorflow.org/tutorials/mandelbrot/):

There is a snippet like this:

```
# Use NumPy to create a 2D array of complex numbers on [-2,2]x[-2,2]
Y, X = np.mgrid[-1.3:1.3:0.005, -2:1:0.005]
```

In the comment there is an area [-2,2]x[-2,2], but in the code itself it looks more like [-2.1]x[-1.3,1,3].
Nothing important but still slightly confusing :)

**Comment by allenlavoie** [comment]
Thank you for the report! Was updating that tutorial anyway. I'll probably just take that bit out of the comment unless you have an objection.

**Comment by gaika** [comment]
Another comment is puzzling for a novice that wants to know more:
```
# Note: We keep computing zs after they diverge! This
#       is very wasteful! There are better, if a little
#       less simple, ways to do this.
```
Is there some tutorial or a more specific reference how do it better?

**Comment by allenlavoie** [comment]
Interesting question. I'm guessing it involves partitioning the space to avoid iterating in the parts of the image which have provably diverged (imaginary part greater than 2). The Wikipedia article is actually quite good there.

Maybe we could do some sort of SparseTensor followup which gets a speedup.

**Comment by carl-frederick** [comment]
Hi Allen, I wonder if you could help me with a problem I'm having with the Mandelbrot tuorial.  When the final statement is executed I get:

>>> DisplayFractal(ns.eval())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 12, in DisplayFractal
  File "PIL/Image.py", line 1439, in save
    save_handler(self, fp, filename)
  File "PIL/JpegImagePlugin.py", line 471, in _save
    ImageFile._save(im, fp, [("jpeg", (0,0)+im.size, 0, rawmode)])
  File "PIL/ImageFile.py", line 476, in _save
    fh = fp.fileno()
io.UnsupportedOperation: fileno
>>> 

Looking around it seems there might be some problem with IPython redirecting io streams but i don't know what I can do about it.  Thanks.

**Comment by allenlavoie** [comment]
It works for me in IPython.\_\_version\_\_ ==  '5.1.0' (python 3.4.3).

Maybe try saving the image instead of displaying it by replacing:
```
  f = BytesIO()
  PIL.Image.fromarray(a).save(f, fmt)
  display(Image(data=f.getvalue()))
```
With:
```
  PIL.Image.fromarray(a).save("/tmp/mandelbrot.jpg")
```

**Comment by carl-frederick** [comment]
Thanks, maybe I need to upgrade/install more software. Now I'm getting that encoder jpeg no available.

**Comment by carl-frederick** [comment]
If I decided to upgrade to python3 would I need to uninstall tensorflow before re-installing?

**Comment by allenlavoie** [comment]
Probably want to move these questions to StackOverflow. I don't think the Python version matters; it's probably IPython.

**Comment by carl-frederick** [comment]
Hmm, my IPython version is 5.4.1.  Maybe the tutorial should be upgraded to work with this version, which is probably the latest, at least for my ios.

**Comment by allenlavoie** [comment]
I've upgraded my IPython to 5.4.1 and switched to Python 2.7.6 and it works for me either way (saving to a file or as written in the tutorial) on Linux.

By "for my ios", do you mean you're on a Mac? That would in fact be a bug if there's a platform dependency. If so please open a new bug. We may just need to switch it to matplotlib or something. Bonus points if you follow up with a pull request which makes the tutorial work cross-platform.
