### ISSUE TITLE
incorrect usage of num_gpus & num_workers in mnist_replica.py

### ISSUE THREAD

**Issue by skaarthik** [tensorflow/tensorflow#7312]
[mnist_replica.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dist_test/python/mnist_replica.py#L126) has the following code. 
```
 if FLAGS.num_gpus < num_workers:
    raise ValueError("number of gpus is less than number of workers")
```
This will work fine in a single worker setup with one or more GPUs. However, it will throw error if the number of workers is greater than the number of GPUs available in each worker. For example, using 2 workers each with 1 GPU will trigger this error.

It looks like this if-block can be removed. If that is an acceptable change, I can send a PR for that.

**Comment by girving** [comment]
What would the extra worker use for compute?

**Comment by skaarthik** [comment]
I am not sure what you mean by "extra worker". I am assuming that I can use any number of workers to run this example. I tried running it with 2 workers each with 1 GPU and got this error. Is that not a valid setup to run mnist_replica.py?

**Comment by girving** [comment]
I'm not familiar with this code, but I'm assuming that check is because it's inefficient to use more workers than GPUs, because each worker uses one GPU for compute.  Each worker does some compute, and in GPU mode this compute takes place on a GPU.

**Comment by skaarthik** [comment]
In my case, I would like to use 2 GPU. However the workers I have in Cloud have only 1 GPU each. So, I had to use 2 workers to employ 2 GPUs for my job. I understand that getting a bigger VM with more GPU is more efficient and would not result in this error but the configuration I am using sounds like a valid one and I find this error unnecessarily restrictive.

**Comment by girving** [comment]
@skaarthik Ah, sorry for my confusion.  @mrry Does this check look wrong to you?  I tried finding who added it in the history, but failed.

**Comment by mrry** [comment]
It looks wrong to me, but I think it might have a weird sense where it's used for multi-GPU in a single machine, but not multi-machine multi-GPU. @caisq wrote that code, so he can confirm.

**Comment by girving** [comment]
Sorry this fell through the cracks.  If you're still interested, @skaarthik, we'd be happy to accept a PR.

**Comment by skaarthik** [comment]
Great. I will send a PR.

**Comment by skaarthik** [comment]
Now that the PR is merged, can I close this issue?
