### ISSUE TITLE
Unable to build 16KB aligned Tensorflow lite library for Android V

### ISSUE THREAD

**Issue by pallaviNNT** [tensorflow/tensorflow#73121]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.17

### Custom code

No

### Mobile device

Android V

### Bazel version

bazel 6.0.1

### Current behavior?

Currently we are unable to find the right flag needed to be added in bazel build for building 16KB aligned libraries.

### Standalone code to reproduce the issue

```shell
Currently we are unable to find the right flag needed to be added in bazel build for building 16KB aligned libraries.
16 KB libraries are supposed to give performance benefit in Android V.
```

**Comment by tilakrayal** [comment]
@pallaviNNT,
Could you please share a reproducible code or the colab gist that supports your statement so that the issue can be easily analysed/debugged? Thank you!
