### ISSUE TITLE
slice_input_producer does not return a queue

### ISSUE THREAD

**Issue by jkiske** [tensorflow/tensorflow#7314]
`tf.train.slice_input_producer` does not return a queue for each slice. This means the outputs cannot be used with the BaseReader api. Shouldn't this be consistent with the other `*_input_producer` methods like `string_input_producer`?

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
http://stackoverflow.com/questions/34340489/tensorflow-read-images-with-labels

### Environment info
Operating System:
Ubuntu 14.04

### Installed version of CUDA and cuDNN: 
Cuda 8.0.44
Cudnn 5.1.5

### Tensorflow Version:
0.12.1

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
```python
image_files = glob(...)
label_files = [s.replace('image.jpg', 'labels.jpg') for s in image_files]
# Create a queue where the elements are pairs (image, label)
image_queue, label_queue = tf.train.slice_input_producer([image_files, label_files])
images, labels = [], []
for _ in num_threads:
    # Create two readers for each thread - one for the image and one for the label
    image_reader, label_reader = tf.SomeReader(), tf.SomeReader()
    # Read the image and label pair
    _, image_op = image_reader.read(image_queue)
    _, label_op = label_reader.read(label_queue)
    images.append(image_op)
    labels.append(label_op)
```
## Error
```python
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/io_ops.py", line 265, in read
  return gen_io_ops._reader_read(self._reader_ref, queue_ref, name=name)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 213, in _reader_read
  queue_handle=queue_handle, name=name)
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 613, in apply_op
  (input_name, op_type_name))
TypeError: Input 'queue_handle' of 'ReaderRead' Op requires l-value input
```

### What other attempted solutions have you tried?
Using two `string_input_producers` with the same random seed

**Comment by yaroslavvb** [comment]
Seems like an odd one out since other input producers give queues. cc @josh11b who added this code

```
with ops.name_scope(name, "input_producer", tensor_list):
    tensor_list = ops.convert_n_to_tensor_or_indexed_slices(tensor_list)
    if not tensor_list:
      raise ValueError(
          "Expected at least one tensor in slice_input_producer().")
    range_size = array_ops.shape(tensor_list[0])[0]
    # TODO(josh11b): Add an assertion that the first dimension of
    # everything in TensorList matches. Maybe just check the inferred shapes?
    queue = range_input_producer(range_size, num_epochs=num_epochs,
                                 shuffle=shuffle, seed=seed, capacity=capacity,
                                 shared_name=shared_name)
    index = queue.dequeue()
    output = [array_ops.gather(t, index) for t in tensor_list]
    return output
```

**Comment by josh11b** [comment]
It may have an unfortunate name, but exists to provide an alternative to using a Reader in the case when all your data is in memory.  Enqueuing its output would just add overhead in its designed use case (see https://www.tensorflow.org/how_tos/reading_data/#preloaded_data ).  If you really need the output of this in a queue, you can create a queue, enqueue the output of slice_input_producer, and add that enqueue to a QueueRunner.  The functions in that file are intended to cover common use cases but there is no reason you need to be limited by them.

**Comment by jkiske** [comment]
For anyone interested in @josh11b 's solution, this worked for me. This is really helpful when your data and labels are in separate files.

```python
from tensorflow.python.training import queue_runner

def wrap_with_queue(tensor, dtypes=tf.string):
    queue = tf.FIFOQueue(1, dtypes=dtypes)
    enqueue_op = queue.enqueue(tensor)
    queue_runner.add_queue_runner(queue_runner.QueueRunner(queue, [enqueue_op]))
    return queue

image_files = glob(...)
label_files = [s.replace('image.jpg', 'labels.jpg') for s in image_files]
# Create a queue where the elements are pairs (image, label)
image_file_op, label_file_op = tf.train.slice_input_producer([image_files, label_files])
image_queue = wrap_with_queue(image_file_op)
label_queue = wrap_with_queue(label_file_op)

images, labels = [], []
for _ in num_threads:
    # Create two readers for each thread - one for the image and one for the label
    image_reader, label_reader = tf.SomeReader(), tf.SomeReader()
    # Read the image and label pair
    _, image_op = image_reader.read(image_queue)
    _, label_op = label_reader.read(label_queue)
    images.append(image_op)
    labels.append(label_op)

sess = tf.Session()
tf.train.start_queue_runners(sess=sess)
```

**Comment by yaroslavvb** [comment]
Be careful with "images_queue, labels_queue" construction. If they go into `train_op`, and you run this op in parallel (ie, from different Python threads), then your images and labels can go out of sync because your second run dequeues can "wedge in" the first call image_op dequeue and label_op dequeue, more details in http://stackoverflow.com/questions/41920371/tensorflow-multi-threaded-queuerunner

**Comment by yaroslavvb** [comment]
Given @josh11b 's response, it seems there are compelling reasons to break with the pattern here
