### ISSUE TITLE
Tensorboard fails to load with latest install from source.

### ISSUE THREAD

**Issue by raghakot** [tensorflow/tensorflow#7317]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/tensorflow/tensorflow/issues/1421
https://github.com/tensorflow/tensorflow/issues/4596
https://github.com/tensorflow/tensorflow/issues/1076

### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
-rw-r--r-- 1 root root   560184 Jul 23  2016 libcudadevrt.a
lrwxrwxrwx 1 root root       16 Jul 23  2016 libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Jul 23  2016 libcudart.so.8.0 -> libcudart.so.8.0.27
-rwxr-xr-x 1 root root   394472 Jul 23  2016 libcudart.so.8.0.27
-rw-r--r-- 1 root root   737516 Jul 23  2016 libcudart_static.a
lrwxrwxrwx 1 root root       13 Jul 24  2016 libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root       17 Jul 24  2016 libcudnn.so.5 -> libcudnn.so.5.0.5
-rwxr-xr-x 1 root root 78065952 Apr 22  2016 libcudnn.so.5.0.5
-rw-r--r-- 1 root root 68709594 Apr 22  2016 libcudnn_static.a
```

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`
commit hash: eb225d71b394c24f49a2e07f685be94d4ab7496f
bazel version
```
Build label: 0.4.3
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Dec 22 12:31:25 2016 (1482409885)
Build timestamp: 1482409885
Build timestamp as int: 1482409885
```

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
Chrome dev tools shows that tensorboard is failing to load because of missing polymer.html
```
GET http://0.0.0.0:6006/polymer/polymer.html 404 (NOT FOUND)
...Lots of other errors because Polymer is undefined...
```

**Comment by girving** [comment]
@dandelionmane Suggestions?  That doesn't look like the best URL.

**Comment by dandelionmane** [comment]
On it.

**Comment by raghakot** [comment]
This has now been fixed.
