### ISSUE TITLE
OpenGL error in Raspberry Pi 4B with tensorflow lite c++

### ISSUE THREAD

**Issue by ww5862** [tensorflow/tensorflow#73194]
**System information**
-  Raspberry Pi 4B 8GB 
- Tensorflow Lite v2.9.3
- OpenGL 3.1

**Standalone code to reproduce the issue**

I insert delegate code in [example code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/minimal/minimal.cc) in Raspberry Pi 4B.
I also execute `cmake .. -DTFLITE_ENABLE_GPU=ON` on examples.
It can not find openGL in compile and occurs errors like below. 
But OpenGL run well in other application.
How Can I use OpenGL with tensorflow lite in Raspberry Pi 4?

**Any other info / logs**

INFO: Created TensorFlow Lite delegate for GPU.
ERROR: clGetPlatformIDs returned -1001
ERROR: Falling back to OpenGL
ERROR: TfLiteGpuDelegate Init: OpenGL-based API disabled
INFO: Created 0 GPU delegate kernels.
ERROR: TfLiteGpuDelegate Prepare: delegate is not initialized
ERROR: Node number 1 (TfLiteGpuDelegateV2) failed to prepare.
ERROR: Restored original execution plan after delegate application failure.
Error at /home/user/workspace/minimal.cc:94

**Comment by pkgoogle** [comment]
Hi @ww5862, have you tried the minimal example without any changes first? What happens in that case? Also please share your changes to the example code and the exact commands before your cmake command as well as the full cmake command. Thanks.

**Comment by ww5862** [comment]
Thank you for reply.
I solve this problem with compile with bazel instead of cmake.
Thank you.

**Comment by pkgoogle** [comment]
Hi @ww5862, awesome thanks -- if you have no more open items, please feel free to close the issue.
