### ISSUE TITLE
How to uninstall tensorflow?

### ISSUE THREAD

**Issue by danchokobo** [tensorflow/tensorflow#7322]
Help I want to reinstall tensorflow, from GPU to CPU, because, just installed tensorflow not work correctly.
I test my installation, from documentation of tensorflow.org,
then it gives back that error:

Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'constant'

SO SHOULD I REINSTALL TENSORFLOW?
before I installed by pip, but it did not work then I use virtualen, also did not work, then by using anaconda. something worked, but I stack in testing installation. Help me!

**Comment by girving** [comment]
@gunan Heads up: this is the second recent bug I've seen where someone somehow got an empty installation of TensorFlow (no `tf.constant` here, no `tf.Variable` for https://github.com/tensorflow/tensorflow/issues/7285).  This one is anaconda; not sure about the other one yet.

@danchokobo We don't support Anaconda, so if you installed it through that you should look at Anaconda docs to know how to uninstall.

**Comment by girving** [comment]
Ah, didn't notice you were the same person from https://github.com/tensorflow/tensorflow/issues/7285.  I believe you installed through Anaconda, so you should look at the Anaconda docs for how to uninstall.

**Comment by deep-r** [comment]
I installed tensorflow through pip for python on windows 10
cmd-> pip3 install --upgrade tensorflow
It said "successfully installed tensorflow" but when I typed " import tensorflow as tf", it gave me a huge error saying "DLL load failed" and "no module named _pywrap_tensorflow_internal" and "failed to load the native tensorflow runtime", in the end.
I uninstalled through pip -> pip uninstall tensorflow in command prompt and reinstalled but I'm getting the same error.

**Comment by TarrySingh** [comment]
Do the following:

`conda update libgcc`

but this will require downgrading "due to dependency conflicts" next time you update anaconda.

OR
 you can mask the anaconda libstdc++ so that your system's libstdc++ is used
```
cd ~/TO-YOUR-ANACONDA-FOLDER/lib
mv libstdc++.so libstdc++.so.bkp
mv libstdc++.so.6 libstdc++.so.6.bkp
```
Further optionally create a softlink inside the anaconda lib directly

`ln -s /usr/lib/x86_64-linux-gnu/libstdc++.so.6 libstdc++.so.6`
