### ISSUE TITLE
Can't find rt.jar when installing tensorflow on Mac OS

### ISSUE THREAD

**Issue by haow85** [tensorflow/tensorflow#7326]
Hi,

I downloaded and installed jdk 8 on my mac os. But there was no classes.jar or rt.jar shipped with the installation. When I tried to install tensorflow afterwards, I got a could not find rt.jar error. How should I fix this ?

**Comment by girving** [comment]
Since TensorFlow doesn't use any Java, are you referring to a problem with Bazel?  You could also the Bazel folk, but I expect the problem is better suited for StackOverflow.  Wherever you ask it, please post complete error messages.
