### ISSUE TITLE
CondaHTTPError: HTTP Error when  installing tensorflow on windows by anaconda

### ISSUE THREAD

**Issue by JingY0604** [tensorflow/tensorflow#7327]
(D:\Program Files (x86)\Anaconda2) C:\XX\XXXXX>conda install -c https://
api.anaconda.org/conda-forge tensorflow
Fetching package metadata ....Could not connect to https://repo.continuum.io/pkg
s/free/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/win-64/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/msys2/win-64/
Could not connect to https://repo.continuum.io/pkgs/msys2/noarch/
CondaHTTPError: HTTP Error: Could not find URL: https://api.anaconda.org/conda-f
orge/win-64/

why could not connect... ???? 
conda-forge/tensorflow | 0.12.1 | conda | linux-64, win-64, osx-64

**Comment by girving** [comment]
This seems to be an issue with Anaconda, not TensorFlow.
