### ISSUE TITLE
Add network address check in clusterSpec

### ISSUE THREAD

**Issue by DjangoPeng** [tensorflow/tensorflow#7328]
Today, I got an error when starting a distributed TensorFlow computation. I debugged for hours and finally found the problem is that TensorFlow doesn't have network address check in `ClusterSpec` method. And it endlessly connect the illegal network address `100.xxx.xxx.232.:2223`, because there is a redundant `.` after `232`.

**Comment by DjangoPeng** [comment]
I think I can create a PR to optimize the legal check of network address.

**Comment by girving** [comment]
That sounds reasonable to me.  @mrry Is that the right place to check?

**Comment by mrry** [comment]
The ClusterSpec class might be used with many different naming schemes, so the appropriate place to put the validation is in `grpc_server_lib.cc` around L130.

**Comment by DjangoPeng** [comment]
@mrry ok, I'd like to work on it today.

**Comment by DjangoPeng** [comment]
@mrry @girving I found there are at least two ways to work it out. 
1. Include the `boost::regex` to associate with the network address check.
2. Define a function and some rules to check the string by myself.
I don't know which one is better in the case of TensorFlow. Could you give me some advice?

**Comment by alisidd** [comment]
@mrry Can I work on this?

**Comment by mrry** [comment]
@alisidd Thanks for offering to work on this! As far as I know, @DjangoPeng *was* working on this in #7532, but that PR has been closed due to inactivity. If you are going to work on it, perhaps you could take a look at the comments on that thread to see what would be required?

**Comment by alisidd** [comment]
@mrry Great, I'll look into it!

**Comment by DjangoPeng** [comment]
@mrry @alisidd Please go ahead. I'm working on our projects this day. So I may not working on this issue nowadays. Thanks.

**Comment by mrry** [comment]
I think the fix has since landed, courtesy of a change by @frankchn: https://github.com/tensorflow/tensorflow/commit/ef9a552282e24bcbc5dd2d590d986c09d9eef9b1.

I'm closing this for now, but feel free to reopen if there are other cases that could be validated.
