### ISSUE TITLE
sample_weight taking long to initialize

### ISSUE THREAD

**Issue by jubebo** [tensorflow/tensorflow#73362]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.12.0

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu

### Python version

3.10.12

### Current behavior?

When training a keras model on in-memory data (e.g., numpy arrays or pandas DataFrames) and simultaneously providing the `sample_weight` parameter in `fit`, the initialization takes very long (ca. 5 minutes with 1 Mio. examples). This problem amplifies when the number of examples increases.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow import keras
import numpy as np

x_train = np.random.rand(10000, 10)
y_train = np.random.rand(10000, 1)
w_train = np.random.rand(10000, 1)

def run(with_sample_weights=True):
  model = keras.Sequential()
  model.add(keras.layers.Dense(64, input_dim=x_train.shape[1], activation='relu')) 
  model.add(keras.layers.Dropout(0.1))
  model.add(keras.layers.Dense(64, activation='relu'))
  model.add(keras.layers.Dropout(0.1))
  model.add(keras.layers.Dense(64, activation='relu'))
  model.add(keras.layers.Dropout(0.1))
  model.add(keras.layers.Dense(64, activation='relu'))
  model.add(keras.layers.Dropout(0.1))
  model.add(keras.layers.Dense(1, activation='sigmoid'))
  model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

  if with_sample_weights:
    model.fit(x_train, y_train, sample_weight=w_train)
  else:
    model.fit(x_train, y_train)

import time

start = time.time()
for i in range(10):
  run(True)
end = time.time()
print(end - start)

start = time.time()
for i in range(10):
  run(False)
end = time.time()
print(end - start)
```

### Relevant log output

```shell
For 10,000 examples: 31s vs 14s
For 1,000,000: 1253.8s vs 17.1s
```

**Comment by jubebo** [comment]
From own investigation (so far only tested on tf/keras in version 2.12.0), the implementation of `handle_partial_sample_weights` in `training_utils.py` is inefficient. In my case (`sample_weight` is a dense numpy array with shape `(1000000,)` and all entries filled/non-null) the following [lines](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training_utils.py#L79-L80) were causing the bottleneck.

I suggest exchanging [lines 77-78](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training_utils.py#L77-L78) with `any_sample_weight = sample_weights.numpy().any()` and exchanging [lines 79-80](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/training_utils.py#L79-L80) with `partial_sample_weight = sample_weights.numpy().all()`.

In my case, `handle_partial_sample_weights` was called from [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/data_adapter.py#L249-L250).

Please let me know if this could have side effects in case of other usage patterns.

**Comment by jubebo** [comment]
FYI: Issue was also discussed for standalone keras [here](https://stackoverflow.com/questions/63158424/why-does-keras-model-fit-with-sample-weight-have-long-initialization-time) and [here](https://github.com/keras-team/keras/issues/14877).

**Comment by tilakrayal** [comment]
@jubebo,
I tried to execute the mentioned code on tensorflower v2.17 which contains keras3.0, and observed that the time taking is lesser when compared to tensorflow v2.12. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/75b1c4e1ae5cc00dcd757dfd9397f805/untitled2058.ipynb).

Also please try to use the latest tensorflow v2.17 and as this issue is more related to keras, raise the issue in keras-team/keras repo for the quick resolution. Thank you!
