### ISSUE TITLE
Documentation for tf.contrib.layers.stack replaced by documentation for tf.stack

### ISSUE THREAD

**Issue by wrsaunde** [tensorflow/tensorflow#7344]
Documentation for tf.contrib.layers.stack appears to be replaced by documentation for tf.stack, see
[https://www.tensorflow.org/api_docs/python/contrib.layers/higher_level_ops_for_building_neural_network_layers_#stack](https://www.tensorflow.org/api_docs/python/contrib.layers/higher_level_ops_for_building_neural_network_layers_#stack)

**Comment by girving** [comment]
@josh11b Did you have a docs rewrite planned?

**Comment by girving** [comment]
This is fixed in the 1.0 docs.
