### ISSUE TITLE
Issue with Loading libdelegate.so on Ubuntu 22.04 LTS Using TensorFlow Lite GPU Delegate

### ISSUE THREAD

**Issue by pisarev** [tensorflow/tensorflow#73484]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.4

### Custom code

Yes

### OS platform and distribution

WSL Linux Ubuntu-22.04

### Python version

3.9

### Bazel version

Bazelisk (automatically manages Bazel version)

### GCC/compiler version

10.5.0

### CUDA/cuDNN version

11.2.r11.2

### GPU model and memory

NVidia 4060Ti

### Current behavior?

(base) master@WIN-1VM6C4QJVS5:/mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-22.04/x64$ LD_DEBUG=libs ./test

... skipped lines with no errors or warnings ...

     27014:
     27014:     calling init: /usr/lib/x86_64-linux-gnu/gconv/UTF-16.so
     27014:
     27014:     /lib/x86_64-linux-gnu/libglib-2.0.so.0: error: symbol lookup error: undefined symbol: g_object_ref_sink (fatal)
     27014:     find library=libgdk-x11-2.0.so [0]; searching
     27014:      search path=/usr/local/cuda-11.2/lib64:glibc-hwcaps/x86-64-v3:glibc-hwcaps/x86-64-v2:tls/x86_64/x86_64:tls/x86_64:tls/x86_64:tls:x86_64/x86_64:x86_64:x86_64:          (LD_LIBRARY_PATH)
     27014:       trying file=/usr/local/cuda-11.2/lib64/libgdk-x11-2.0.so
     27014:       trying file=glibc-hwcaps/x86-64-v3/libgdk-x11-2.0.so
     27014:       trying file=glibc-hwcaps/x86-64-v2/libgdk-x11-2.0.so
     27014:       trying file=tls/x86_64/x86_64/libgdk-x11-2.0.so
     27014:       trying file=tls/x86_64/libgdk-x11-2.0.so
     27014:       trying file=tls/x86_64/libgdk-x11-2.0.so
     27014:       trying file=tls/libgdk-x11-2.0.so
     27014:       trying file=x86_64/x86_64/libgdk-x11-2.0.so
     27014:       trying file=x86_64/libgdk-x11-2.0.so
     27014:       trying file=x86_64/libgdk-x11-2.0.so
     27014:       trying file=libgdk-x11-2.0.so
     27014:      search cache=/etc/ld.so.cache
     27014:       trying file=/lib/x86_64-linux-gnu/libgdk-x11-2.0.so
     27014:
     27014:     ./test: error: symbol lookup error: undefined symbol: gtk_widget_device_is_shadowed (fatal)
     27014:     find library=libstdc++.so.6 [0]; searching
     27014:      search path=/usr/local/cuda-11.2/lib64:glibc-hwcaps/x86-64-v3:glibc-hwcaps/x86-64-v2:tls/x86_64/x86_64:tls/x86_64:tls/x86_64:tls:x86_64/x86_64:x86_64:x86_64:          (LD_LIBRARY_PATH)
     27014:       trying file=/usr/local/cuda-11.2/lib64/libstdc++.so.6
     27014:       trying file=glibc-hwcaps/x86-64-v3/libstdc++.so.6
     27014:       trying file=glibc-hwcaps/x86-64-v2/libstdc++.so.6
     27014:       trying file=tls/x86_64/x86_64/libstdc++.so.6
     27014:       trying file=tls/x86_64/libstdc++.so.6
     27014:       trying file=tls/x86_64/libstdc++.so.6
     27014:       trying file=tls/libstdc++.so.6
     27014:       trying file=x86_64/x86_64/libstdc++.so.6
     27014:       trying file=x86_64/libstdc++.so.6
     27014:       trying file=x86_64/libstdc++.so.6
     27014:       trying file=libstdc++.so.6
     27014:      search cache=/etc/ld.so.cache
     27014:       trying file=/lib/x86_64-linux-gnu/libstdc++.so.6
     27014:
     27014:     find library=libgcc_s.so.1 [0]; searching
     27014:      search path=/usr/local/cuda-11.2/lib64:glibc-hwcaps/x86-64-v3:glibc-hwcaps/x86-64-v2:tls/x86_64/x86_64:tls/x86_64:tls/x86_64:tls:x86_64/x86_64:x86_64:x86_64:          (LD_LIBRARY_PATH)
     27014:       trying file=/usr/local/cuda-11.2/lib64/libgcc_s.so.1
     27014:       trying file=glibc-hwcaps/x86-64-v3/libgcc_s.so.1
     27014:       trying file=glibc-hwcaps/x86-64-v2/libgcc_s.so.1
     27014:       trying file=tls/x86_64/x86_64/libgcc_s.so.1
     27014:       trying file=tls/x86_64/libgcc_s.so.1
     27014:       trying file=tls/x86_64/libgcc_s.so.1
     27014:       trying file=tls/libgcc_s.so.1
     27014:       trying file=x86_64/x86_64/libgcc_s.so.1
     27014:       trying file=x86_64/libgcc_s.so.1
     27014:       trying file=x86_64/libgcc_s.so.1
     27014:       trying file=libgcc_s.so.1
     27014:      search cache=/etc/ld.so.cache
     27014:       trying file=/lib/x86_64-linux-gnu/libgcc_s.so.1
     27014:
     27014:     ./bin/tflite/libdelegate.so: error: symbol lookup error: undefined symbol: _ZN4absl14lts_2020_09_236Status16kMovedFromStringE (fatal)
     27014:

... skipped lines with no errors or warnings ...

### Standalone code to reproduce the issue

```shell
I expected the program to run without issues, successfully loading the libdelegate.so library and executing the intended functions without any runtime errors. It's important to note that the `libtensorflowlite_c.so` library, which was built in the same environment, loads without any issues or errors.
```

### Relevant log output

```shell
Additionally, the libdelegate.so library build process completes successfully with the following key outputs:

WARNING: The following configs were expanded more than once: [cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from /mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-22.04/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-22.04/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-22.04/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/master/miniconda3/envs/tf/bin/python3 --action_env PYTHON_LIB_PATH=/home/master/miniconda3/envs/tf/lib/python3.9/site-packages --python_path=/home/master/miniconda3/envs/tf/bin/python3 --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda-11.2 --action_env TF_CUDA_COMPUTE_CAPABILITIES=8.9 --action_env LD_LIBRARY_PATH=/usr/local/cuda-11.2/lib64:/usr/local/cuda-11.2/lib64:/usr/local/cuda-11.2/lib64: --action_env GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-10 --config=cuda
INFO: Found applicable config definition build:short_logs in file /mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-22.04/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-22.04/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:cuda in file /mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-22.04/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:monolithic in file /mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-22.04/tensorflow/.bazelrc: --define framework_shared_object=false
INFO: Found applicable config definition build:cuda in file /mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-22.04/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:linux in file /mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-22.04/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-22.04/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: /home/master/.cache/bazel/_bazel_master/8a68c52b18b2f377d8f5efcf04fab9da/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:10: 
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
Loading:  (0 packages loaded)
Loading: 0 packages loaded
Analyzing: target //tensorflow/lite/delegates/gpu:delegate (0 packages loaded, 0 targets configured)
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-22.04/tensorflow/WORKSPACE:23:14: in <toplevel>
  /mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-22.04/tensorflow/tensorflow/workspace0.bzl:105:34: in workspace
  /home/master/.cache/bazel/_bazel_master/8a68c52b18b2f377d8f5efcf04fab9da/external/bazel_toolchains/repositories/repositories.bzl:37:23: in repositories
Repository rule git_repository defined at:
  /home/master/.cache/bazel/_bazel_master/8a68c52b18b2f377d8f5efcf04fab9da/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed target //tensorflow/lite/delegates/gpu:delegate (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
[0 / 4] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[9 / 344] Compiling tensorflow/lite/delegates/gpu/gl/api2.cc; 1s local ... (8 actions, 7 running)
[12 / 344] Compiling tensorflow/lite/delegates/gpu/gl/api2.cc; 2s local ... (8 actions running)
[15 / 351] Compiling flatbuffers/src/idl_gen_cpp.cpp [for host]; 3s local ... (8 actions running)
[20 / 353] Compiling flatbuffers/src/idl_gen_python.cpp [for host]; 2s local ... (8 actions running)
[59 / 388] Compiling flatbuffers/src/idl_parser.cpp [for host]; 1s local ... (8 actions, 7 running)
[67 / 388] Compiling flatbuffers/src/idl_parser.cpp [for host]; 2s local ... (8 actions, 7 running)
[75 / 388] Compiling flatbuffers/src/idl_parser.cpp [for host]; 4s local ... (8 actions, 7 running)
[83 / 388] Compiling flatbuffers/src/idl_parser.cpp [for host]; 5s local ... (8 actions, 7 running)
[104 / 388] Compiling flatbuffers/src/idl_parser.cpp [for host]; 7s local ... (8 actions, 7 running)
[136 / 388] Compiling flatbuffers/src/idl_parser.cpp [for host]; 8s local ... (8 actions, 7 running)
[156 / 388] Compiling flatbuffers/src/idl_parser.cpp; 8s local ... (8 actions, 7 running)
[167 / 388] Compiling tensorflow/lite/delegates/gpu/cl/kernels/converter.cc; 2s local ... (8 actions, 7 running)
[178 / 388] Compiling tensorflow/lite/delegates/gpu/common/model_builder.cc; 5s local ... (8 actions running)
[193 / 388] Compiling tensorflow/lite/delegates/gpu/common/tasks/depthwise_conv_3x3_stride_h2.cc; 1s local ... (8 actions running)
[214 / 388] Compiling tensorflow/lite/delegates/gpu/common/tasks/convolution_transposed.cc; 3s local ... (8 actions, 7 running)
[253 / 389] Compiling tensorflow/lite/delegates/gpu/gl/gl_program.cc; 0s local ... (8 actions, 7 running)
[285 / 389] Compiling tensorflow/lite/delegates/gpu/gl/kernels/depthwise_conv.cc; 1s local ... (8 actions, 7 running)
[316 / 391] Compiling tensorflow/lite/delegates/gpu/common/tasks/conv_powervr.cc; 4s local ... (8 actions, 7 running)
[365 / 391] Compiling tensorflow/lite/delegates/gpu/cl/cl_arguments.cc; 3s local ... (8 actions, 7 running)
Target //tensorflow/lite/delegates/gpu:delegate up-to-date:
  bazel-bin/tensorflow/lite/delegates/gpu/libdelegate.a
  bazel-bin/tensorflow/lite/delegates/gpu/libdelegate.pic.a
  bazel-bin/tensorflow/lite/delegates/gpu/libdelegate.so
INFO: Elapsed time: 54.796s, Critical Path: 17.86s
INFO: 354 processes: 1 internal, 353 local.
INFO: Build completed successfully, 354 total actions
INFO: Build completed successfully, 354 total actions
```

**Comment by Venkat6871** [comment]
Hi **@pisarev** ,
Sorry for the delay. There seem to be version compatibility issues here. Could you please check this [documentation](https://www.tensorflow.org/install/source_windows#gpu)? Please update the documentation accordingly and let us know if the issue still persists.
Thank you!

**Comment by pisarev** [comment]
Thank you for your response!

I have checked the versions of all relevant components and it seems everything is selected correctly:

- **Ubuntu Version**: 22.04.4 LTS (Jammy)
- **Bazel Version**: 3.7.2 (installed via Bazelisk)
- **CUDA Version**: 11.2 (V11.2.152)
- **cuDNN Version**: 8.1.1
- **Python Version**: 3.9.19 (Conda environment)
- **GCC Version**: Default system GCC is used.

Configuration details:
- CUDA compute capability: 8.9
- No ROCm, TensorRT, or Clang as CUDA compiler.

The "libdelegate.so" library, when loaded by my application, leads to a symbol lookup error, while the "libtensorflowlite_c.so" library loads without any issues.

Here are the specific commands I ran in the terminal along with their outputs:

(tf) master@WIN-1VM6C4QJVS5:/mnt/c/Users/admin$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

(tf) master@WIN-1VM6C4QJVS5:/mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-24.04/tensorflow$ bazel --version
bazel 3.7.2

(tf) master@WIN-1VM6C4QJVS5:/mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-24.04/tensorflow$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0

(tf) master@WIN-1VM6C4QJVS5:/mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-24.04/tensorflow$ cat /usr/local/cuda/include/cudnn_version.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 1
#define CUDNN_PATCHLEVEL 1
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)
#endif /* CUDNN_VERSION_H */

(tf) master@WIN-1VM6C4QJVS5:/mnt/c/Users/admin$ conda activate tf
(tf) master@WIN-1VM6C4QJVS5:/mnt/c/Users/admin$ which python
/home/master/miniconda3/envs/tf/bin/python

(tf) master@WIN-1VM6C4QJVS5:/mnt/c/Users/admin$ python --version
Python 3.9.19

Configuration steps:

(tf) master@WIN-1VM6C4QJVS5:/mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-24.04/tensorflow$ ./configure
You have bazel 3.7.2 installed.
Please specify the location of python. [Default is /bin/python3]: /home/master/miniconda3/envs/tf/bin/python

Found possible Python library paths:
  /home/master/miniconda3/envs/tf/lib/python3.9/site-packages
Please input the desired Python library path to use.  Default is [/home/master/miniconda3/envs/tf/lib/python3.9/site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: n
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: n
No TensorRT support will be enabled for TensorFlow.

Found CUDA 11.2 in:
    /usr/local/cuda-11.2/targets/x86_64-linux/lib
    /usr/local/cuda-11.2/targets/x86_64-linux/include
Found cuDNN 8 in:
    /usr/local/cuda-11.2/targets/x86_64-linux/lib
    /usr/local/cuda-11.2/targets/x86_64-linux/include

Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus. Each capability can be specified as "x.y" or "compute_xy" to include both virtual and binary GPU code, or as "sm_xy" to only include the binary code.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 8.9]: 8.9

Do you want to use clang as CUDA compiler? [y/N]: n
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /bin/gcc]:

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]:

Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: n
Not configuring the WORKSPACE for Android builds.

Despite these configurations, the "libdelegate.so" library still encounters the following errors when loaded by the application:

(tf) master@WIN-1VM6C4QJVS5:/mnt/c/Users/admin/Documents/Lazarus/Projects/ubuntu-24.04/x64$ LD_DEBUG=libs ./eye
...
      6411:     /lib/x86_64-linux-gnu/libglib-2.0.so.0: error: symbol lookup error: undefined symbol: g_object_ref_sink (fatal)
...
      6411:     ./eye: error: symbol lookup error: undefined symbol: gtk_widget_device_is_shadowed (fatal)
...
      6411:     ./bin/tflite/libdelegate.so: error: symbol lookup error: undefined symbol: _ZN4absl14lts_2020_09_236Status16kMovedFromStringE (fatal)

**Comment by pkgoogle** [comment]
Hi @pisarev, what command did you use to build `libdelegate.so`? Also what command(s)/program(s) did you use to check it (`./eye` ??) can you please explain what that is? Please also format code/terminal with 3 backtick code formatting:

ex:
\`\`\`
\# code/terminal output
\`\`\`

outputs:
```
# code/terminal output
```

Thanks.
