### ISSUE TITLE
Can the TensorFlow  Android object detection example support MobileNetV2 and MobileNetV3 tflite models?

### ISSUE THREAD

**Issue by libofei2004** [tensorflow/tensorflow#73522]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.8

### Custom code

Yes

### Current behavior?

Can the TensorFlow  Android object detection example https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection support MobileNetV2 and MobileNetV3 tflite models?It seems that it only supports MobileNetV1?

### Standalone code to reproduce the issue

```shell
......
```

**Comment by sawantkumar** [comment]
Hi @libofei2004 ,

I tried plugging in the mobilenetv2 in the object detection example. It is giving error but i think with some code changes you can get it to work.

**Comment by libofei2004** [comment]
@sawantkumar Maybe，but do you know how?

**Comment by gaikwadrahul8** [comment]
Hi, @libofei2004 

I apologize for the delayed response, I see at the moment we support for object detection models mentioned in this file https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/app/download_models.gradle for object detection TFLite examples, if you're looking to use `ssd_mobilenet_v2` then you can download TFLite model from here https://www.kaggle.com/models/tensorflow/ssd-mobilenet-v2 and you may have to change your code as per the `ssd_mobilenet_v2` model (input and output), please check this [github repo](https://github.com/sayannath/American-Sign-Language-Detection) which may help you.

Thank you for your cooperation and patience.

**Comment by libofei2004** [comment]
@gaikwadrahul8 [github repo](https://github.com/sayannath/American-Sign-Language-Detection) this repo is just provides classification, but what I want is object detection.

**Comment by gaikwadrahul8** [comment]
Hi, @libofei2004 

I apologize for the delayed response, you can refer this [MediaPipe Tasks Object Detection Android Demo](https://github.com/google-ai-edge/mediapipe-samples/tree/main/examples/object_detection/android) with the option to use a quantized [MobileNetV2](https://storage.cloud.google.com/tf_model_garden/vision/qat/mobilenetv2_ssd_coco/mobilenetv2_ssd_256_uint8.tflite) please refer this [Object detection guide for Android](https://ai.google.dev/edge/mediapipe/solutions/vision/object_detector/android)

Thank you for your cooperation and patience.
