### ISSUE TITLE
Tensorboard ImportError: No module named 'tensorflow.tensorboard.plugins.debugger'

### ISSUE THREAD

**Issue by snnn** [tensorflow/tensorflow#7352]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

None.

### Environment info
Operating System:
Windows 10.

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
None.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
e946a6b63979a63f9e5a1d1603f6cc21d8aad1cf
2. The output of `bazel version`
(compiled by cmake)
cmake -G "Visual Studio 14 2015 Win64" .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSWIG_EXECUTABLE=C:\prog\swigwin-3.0.12\swig.exe -DPYTHON_EXECUTABLE=C:\Python35\python.exe -DPYTHON_LIBRARIES=C:\Python35\libs\python35.lib -Dtensorflow_ENABLE_HDFS_SUPPORT=ON 

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
```
> tensorboard --logdir=..\logs
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\Scripts\tensorboard.exe\__main__.py", line 5, in <module>
  File "c:\python35\lib\site-packages\tensorflow\tensorboard\tensorboard.py", line 35, in <module>
    from tensorflow.tensorboard.plugins.debugger import plugin as debugger_plugin
ImportError: No module named 'tensorflow.tensorboard.plugins.debugger'
```

```
>dir C:\Python35\Lib\site-packages\tensorflow\tensorboard\plugins
 Volume in drive C is OSDisk
 Volume Serial Number is 1066-463E

 Directory of C:\Python35\Lib\site-packages\tensorflow\tensorboard\plugins

02/08/2017  11:55 AM    <DIR>          .
02/08/2017  11:55 AM    <DIR>          ..
02/08/2017  11:55 AM             1,658 base_plugin.py
02/08/2017  11:55 AM    <DIR>          projector
02/08/2017  11:55 AM                 0 __init__.py
02/08/2017  11:55 AM    <DIR>          __pycache__
```

**Comment by girving** [comment]
@snnn What version of Tesnorflow are you using?

@dandelionmane Seen anything like this?

**Comment by snnn** [comment]
@girving It was compiled from source code by myself.  commit version is : e946a6b

**Comment by dandelionmane** [comment]
+ @caisq, @chihuahua

**Comment by chihuahua** [comment]
In your paste above, I wonder why `debugger` is missing from the `tensorflow\tensorboard\plugins` directory.

**Comment by caisq** [comment]
https://github.com/tensorflow/tensorflow/pull/7428 should have fixed this issue. Please comment or reopen issue if there are any other problems.
