### ISSUE TITLE
Can tflite model maker be used to train MobileNet models?

### ISSUE THREAD

**Issue by libofei2004** [tensorflow/tensorflow#73521]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.8

### Custom code

Yes

### Current behavior?

Can tflite model maker  be used to train MobileNetv1 or MobileNetv2 models?I know It can be used to train efficientdet_lite model.

### Standalone code to reproduce the issue

```shell
Can tflite model maker  be used to train MobileNetv1 or MobileNetv2 models?I know It can be used to train efficientdet_lite model.
```

**Comment by libofei2004** [comment]
@sawantkumar I tried MediaPipe Model Maker.But I meet some issues, like:https://github.com/google-ai-edge/mediapipe/issues/5557, https://github.com/google-ai-edge/mediapipe-samples/issues/432

**Comment by gaikwadrahul8** [comment]
Hi, @pkgoogle 
Please take look into this issue. Thank you

**Comment by pkgoogle** [comment]
Hi @libofei2004, you will have to resolve the mediapipe issues as tflite-model-maker isn't working right now.
