### ISSUE TITLE
How to build python .whl on cmake with flex delegate support? 

### ISSUE THREAD

**Issue by ismukhin** [tensorflow/tensorflow#73533]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.14.0

### Custom code

Yes

### OS platform and distribution

Linux ubuntu 22.04

### Python version

3.11

### Current behavior?

I want to build tflite with flex delegate support on risc-v. I tried it through the ```build_pip_package_with_cmake.sh``` file, adding the necessary code for compilation under risc-v. It works, but some models require flex delegate. 
I saw that this can be done through bazel in readme, but I need to do this with cmake. How can I do this? (if I can)

### Standalone code to reproduce the issue

```shell
If you want to use TF ops with Python API, you need to enable flex support.
You can build TFLite interpreter with flex ops support by providing
`--define=tflite_pip_with_flex=true` to Bazel.

Is there something similar for cmake?
```

**Comment by pkgoogle** [comment]
Hi @ismukhin, there is currently no way to build them with cmake, unless you make your own CMakeLists.txt file (I don't recommend that unless you have a lot of time to figure it all out). Is there a reason you can't use Bazel?
