### ISSUE TITLE
dynamic_rnn_decoder doesn't have an initial_state argument

### ISSUE THREAD

**Issue by ankeshanand** [tensorflow/tensorflow#7354]
The `rnn_decoder` function used to have a `initial_state` argument earlier, which was useful for custom cell state initializations.

However, in the new API, the `dynamic_rnn_decoder` method doesn't have this argument. Is there any other to initialize cell state in this case?

**Comment by girving** [comment]
@ebrevdo Where did the initial state go?  It's not obvious to me either from the code.

**Comment by ebrevdo** [comment]
Apologies for the confusing API.

I hope to **remove the dynamic_rnn_decoder function next week**; it's
limited and bug-prone.  We have a new object oriented API which should be
much easier to use (examples of use here
<https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/seq2seq/python/kernel_tests/decoder_test.py#L132>).
What remains is adding a Decoder that supports attention; it should go in
in the next week or two.  Then we will remove the old function-based
approach from the repo.

**Comment by mschonwe** [comment]
@ebrevdo, +1 for the new attention decoder to also support beams.

Looking forward to the new attention decoder!  We tried the original dynamic_rnn_decoder approach but got better results with fixed length padded buckets (with dynamic, attention never converged "on the diagonal").

For attention we used an approach recommended by @pbhatia243 in issue #654 - results are much better than naive argmax, but the implementation is limited to batch=1.

**Comment by jbingel** [comment]
@ebrevdo thanks for the easier API! It seems like the current implementation in master doesn't contain attention yet, is that right? Will this be added by the next TF release (and is there an estimate of when that'll be)?

**Comment by skye** [comment]
@ebrevdo any updates? Is this resolved?

**Comment by ebrevdo** [comment]
Yes, we got rid of this function.
