### ISSUE TITLE
Potential UnboundLocalError in error-handling context manager

### ISSUE THREAD

**Issue by Julian** [tensorflow/tensorflow#7356]
I'm working on unrelated things while this came up, and it's possibly unlikely to happen in real development, but just to track it in case someone cares,

https://github.com/tensorflow/tensorflow/blob/5e5dc97dd3523509ce5f536d7be5122d016fc6b5/tensorflow/python/framework/errors_impl.py#L471

that is an `UnboundLocalError` if it was line 463 that raised there (i.e. if TF_NewStatus failed entirely).

Without any insider knowledge, possibly that line belongs outside the try block.

**Comment by girving** [comment]
Nice catch, thank you!  I'll fix, unless you feel like submitting a PR.

**Comment by yaroslavvb** [comment]
how to make tensorflow pull request https://gist.github.com/yaroslavvb/bdb0a92f2a516ebbe2d386c48f5e2c45
