### ISSUE TITLE
there is a error when i run 'bazel build --config opt //tensorflow/tools/pip_package:build_pip_package'

### ISSUE THREAD

**Issue by mathfinder** [tensorflow/tensorflow#7357]
INFO: Found 1 target...
ERROR: /home/ben/.cache/bazel/_bazel_ben/a552231fe7b7da49217bcb6530531abd/external/protobuf/BUILD:73:1: C++ compilation of rule '@protobuf//:protobuf_lite' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 38 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: error: cuda: No such file or directory
gcc: error: cuda: No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.769s, Critical Path: 1.60s

**Comment by girving** [comment]
Do you have cuda installed?  What version?  What planform are you on, and what version of TensorFlow do you have?

**Comment by mathfinder** [comment]
i have installed cuda7.5 and the latest tensorflow on Ubuntu 15.04.i install tensorflow from sourse and set cuda version 7.5.but it didn't work when import tensorflow in python script.

发自我的 iPhone

**Comment by girving** [comment]
Try running bazel with `--subcommands` to see the whole gcc command that is failing.

**Comment by mathfinder** [comment]
i type 'bazel build --subcommands //tensorflow/tools/pip_package:build_pip_package',ans i get error:


ERROR: /home/ben/tensorflow/tensorflow/core/BUILD:1089:1: C++ compilation of rule '//tensorflow/core:lib_internal' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 106 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from ./tensorflow/core/lib/gtl/array_slice.h:101:0,
                 from ./tensorflow/core/lib/strings/str_util.h:23,
                 from tensorflow/core/lib/strings/str_util.cc:16:
./tensorflow/core/lib/gtl/array_slice_internal.h:232:38: error: 'tensorflow::gtl::array_slice_internal::ArraySliceImplBase<const T>::ArraySliceImplBase' names constructor
./tensorflow/core/lib/gtl/array_slice_internal.h:252:32: error: 'tensorflow::gtl::array_slice_internal::ArraySliceImplBase<T>::ArraySliceImplBase' names constructor
In file included from ./tensorflow/core/lib/gtl/array_slice.h:102:0,
                 from ./tensorflow/core/lib/strings/str_util.h:23,
                 from tensorflow/core/lib/strings/str_util.cc:16:
./tensorflow/core/lib/gtl/inlined_vector.h: In member function 'void tensorflow::gtl::InlinedVector<T, N>::Destroy(T*, int)':
./tensorflow/core/lib/gtl/inlined_vector.h:396:10: error: 'is_trivially_destructible' is not a member of 'std'
./tensorflow/core/lib/gtl/inlined_vector.h:396:42: error: expected primary-expression before '>' token
./tensorflow/core/lib/gtl/inlined_vector.h:396:43: error: '::value' has not been declared

**Comment by girving** [comment]
The lack of `std::is_trivially_destructable` is odd.  It would imply your version of g++ is too old: we don't support anything without good C++11 support.  However, your version of Ubuntu is reasonably recent.  What version of g++ do you have?  Is there some other reason you'd lack part of the standard library?

**Comment by mathfinder** [comment]
the version of g++ is 4.7.4.which version of g++ i should head?

**Comment by girving** [comment]
@mathfinder Looks like gcc 4.9, or any recent version of clang.
