### ISSUE TITLE
name 'DATA_CFG' is not defined, Extension 'tensorflow/tensorflow.bzl' has errors

### ISSUE THREAD

**Issue by OLEGator30** [tensorflow/tensorflow#7358]
Hi!

I was following the [Nvidia instruction](http://www.nvidia.com/object/gpu-accelerated-applications-tensorflow-installation.html) on how to install tensorflow with CUDA/cuDNN when I faced with the next problem (step 5, "call bazel to build the TensorFlow pip package"):
```
~/tensorflow$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package 
ERROR: /home/user/tensorflow/tensorflow/tensorflow.bzl:478:19: name 'DATA_CFG' is not defined.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension 'tensorflow/tensorflow.bzl' has errors.
INFO: Elapsed time: 0.108s
```
Could you suggest something to overcome this issue?

Additional information:
```
~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
~$ ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root    558720 сен 15 02:02 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root        16 сен 15 02:05 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root        19 сен 15 02:05 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rw-r--r-- 1 root root    415432 сен 15 02:02 /usr/local/cuda/lib64/libcudart.so.8.0.44
-rw-r--r-- 1 root root    775162 сен 15 02:02 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 user users       13 ноя  7 10:00 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 user users       18 ноя  7 10:00 /usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.1.10
-rwxr-xr-x 1 user users 84163560 ноя  7 09:47 /usr/local/cuda/lib64/libcudnn.so.5.1.10
-rw-r--r-- 1 user users 70364814 ноя  7 09:47 /usr/local/cuda/lib64/libcudnn_static.a
~/tensorflow$ git rev-parse HEAD
70de76e696c21da617fd2e6435cf7fedab220db8
~$ bazel version
Build label: 0.4.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Feb 1 18:54:21 2017 (1485975261)
Build timestamp: 1485975261
Build timestamp as int: 1485975261
```

**Comment by girving** [comment]
What version of TensorFlow are you using?

**Comment by OLEGator30** [comment]
As I mention above: master 70de76e696c21da617fd2e6435cf7fedab220db8

**Comment by OLEGator30** [comment]
Sorry, I've closed the issue accidentally.

More precisely, tensorflow was cloned this way:
```
~$ git clone https://github.com/tensorflow/tensorflow
~$ cd tensorflow 
~/tensorflow $ git reset --hard 70de76e
```

**Comment by girving** [comment]
@OLEGator30 That commit is from July.  Please try a newer version.

**Comment by OLEGator30** [comment]
Yeah, now it works, thanks! Nvidia instruction is completely out of date.

**Comment by mishra69** [comment]
I am facing the same issue on the cuda_osx branch. 

```
git clone --recurse-submodules https://github.com/tensorflow/tensorflow
git fetch origin pull/664/head:cuda_osx
git checkout cuda_osx
```

```
admins-MacBook-Pro:tensorflow admin$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: /Users/admin/udacity/tensorflow/tensorflow/tensorflow.bzl:418:42: name 'DATA_CFG' is not defined.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension 'tensorflow/tensorflow.bzl' has errors.
```

**Comment by girving** [comment]
@mishra69 Random commits from August are not supported.  Please use something more recent.

**Comment by krautt** [comment]
Anyone know of a version that will compile with both GPU support and work with the current version of TFLearn?

**Comment by girving** [comment]
@krautt Have you tried 1.0?  https://github.com/tensorflow/tensorflow/releases/tag/v1.0.0

**Comment by krautt** [comment]
Yes it worked but didn't seem to play well with the tflearn stuff i was doing. I compiled the head of the 0.12 branch and it's working for me.  Thanks.

**Comment by girving** [comment]
@krautt In case it's useful: there's a good chance that everything you want is still there, just possibly in a different namespace.  There was a bunch of code movement right before 1.0, since after 1.0 we've promised not to move things for quite a while (unless it's in `tf.contrib`).

**Comment by brebh** [comment]
Hi,
I call bazel to build the TensorFlow pip package but I have the same error as @OLEGator30 , knowing that :Ubuntu 16.10
bazel 0.4.4
tensorflow: 70de76e

**Comment by brebh** [comment]
if I used the newest tensoflow version I've got this error:  
:~/tensorflow$ ./configure 
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python2.7
Please specify optimization flags to use during compilation [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? (Linux only) [Y/n] 
jemalloc enabled on Linux
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Using python library path: /usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] n
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5
Please specify the location where cuDNN 5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 3.0
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.........
ERROR: /home/tensorflow/tensorflow/core/kernels/BUILD:2349:1: no such package '@libxsmm_archive//': Error downloading [http://bazel-mirror.storage.googleapis.com/github.com/hfp/libxsmm/archive/1.6.1.tar.gz, https://github.com/hfp/libxsmm/archive/1.6.1.tar.gz] to /home/razen/.cache/bazel/_bazel_razen/fca8cfb97533c9eba80d6f329ce32777/external/libxsmm_archive/1.6.1.tar.gz: Tried to reconnect at offset 594,903 but server didn't support it and referenced by '//tensorflow/core/kernels:conv_ops'.
ERROR: /home/tensorflow/tensorflow/core/kernels/BUILD:2030:1: no such package '@libxsmm_archive//': Error downloading [http://bazel-mirror.storage.googleapis.com/github.com/hfp/libxsmm/archive/1.6.1.tar.gz, https://github.com/hfp/libxsmm/archive/1.6.1.tar.gz] to /home/razen/.cache/bazel/_bazel_razen/fca8cfb97533c9eba80d6f329ce32777/external/libxsmm_archive/1.6.1.tar.gz: Tried to reconnect at offset 594,903 but server didn't support it and referenced by '//tensorflow/core/kernels:sparse_matmul_op'.
ERROR: Evaluation of query "deps((//tensorflow/... - //tensorflow/examples/android/...))" failed: errors were encountered while computing transitive closure.
