### ISSUE TITLE
resize_image_with_crop_or_pad should work with batch of images

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#7359]
This is a repost of https://github.com/tensorflow/tensorflow/issues/2284 [per comment](https://github.com/tensorflow/tensorflow/issues/2284#issuecomment-277339057) from @mrry (CC @ziky90).

`resize_image_with_crop_or_pad` should be modified to take either a single image or a batch of images. Right now the signature of the function specifies:
```
    image: 3-D tensor of shape `[height, width, channels]`
```

For a reference of what the api should look like, see [`resize_images(images,....)`](https://github.com/tensorflow/tensorflow/blob/4c192f060cf9ff897911d240c140299d6db257b6/tensorflow/python/ops/image_ops_impl.py#L605-L608):
```
    images: 4-D Tensor of shape `[batch, height, width, channels]` or
            3-D Tensor of shape `[height, width, channels]`.
```

Some commentary:
* docs for `resize_images` say: " Resized images will be distorted if their original aspect ratio is not the same as `size`.  To avoid distortions see [`resize_image_with_crop_or_pad`]." However the method referenced _cannot_ be currently used in some cases for which `resize_images` works due to the above mentioned limitations.
* the entire operation can be implemented using slice operations on the tensor batch. This is what `resize_image_with_crop_or_pad` does but it has the following logic which would be nice not to copy and paste (there is some subtlety with round down vs up):
```python
  width_diff = target_width - width
  offset_crop_width = max_(-width_diff // 2, 0)
  offset_pad_width = max_(width_diff // 2, 0)

  height_diff = target_height - height
  offset_crop_height = max_(-height_diff // 2, 0)
  offset_pad_height = max_(height_diff // 2, 0)
```
* the fact this one image op method does not handle batches leads to confusion and various [SO](http://stackoverflow.com/questions/33944683/tensorflow-map-operation-for-tensor) posts. People even resort to solving the problem using all sorts of crazy solutions (e.g. `tf.while_loop`).
* this method is useful in combination with concatenation operations. For example see the[ Lasagne `ConcatLayer`](http://lasagne.readthedocs.io/en/latest/modules/layers/merge.html#lasagne.layers.ConcatLayer).

**Comment by girving** [comment]
@shlens Can you comment?  Ages ago we stripped most of these image preprocessing ops down to 3-D only; what do you think about people raising them back up again?

@cancan101 The motivation for 3-D only is that image processing pipelines that take images of different sizes have to handle separate images as separate tensors anyways, at least until after the resizing step happens.  And this op is the resizing step.

**Comment by cancan101** [comment]
@girving Where I am using this, and likely others as well (this was the same use case that Lasagne handles) is in the NN portion graph itself when doing an upsample. I want to upsample and then concatenate across channels but I need to take a center crop to make sure spatial dimensionality  matches.

**Comment by girving** [comment]
@cancan101 Okay, I think fixing this is quite reasonable.  However, if it's fixed it should work for any rank >= 3.  This shouldn't be much more complicated than doing it for just 3D and 4D, since the higher ranks all mean map.

**Comment by shlens** [comment]
@girving I think adding support for 4D sounds reasonable -- especially if it leads to consistency in the API across image resizing functions.

**Comment by girving** [comment]
@cancan101 Great, we're all in agreement that this is a good change.  Would you be interested in submitting a PR?

**Comment by cancan101** [comment]
Is it okay to change the api of this method? Perhaps with some sort of deprecation to take in `images` rather than `image`?

**Comment by girving** [comment]
@cancan101 Please leave it image, then document that image can be higher rank.
