### ISSUE TITLE
Build tools and versions listed in Jenkins build log.

### ISSUE THREAD

**Issue by EricGT** [tensorflow/tensorflow#736]
Since TensorFlow is built regularly and it success it reported on the GitHub page, it would be nice to see in the logs e.g. (http://ci.tensorflow.org/job/tensorflow-master/47/configure) the OS configuration, tools used and their version. This way if people want to know what tools and version of the tools currently work they would be available and automatically updated.

Example:
OS: Ubuntu 14.04 LTS
Memory: 2G
Swap space: 2G
Processor: i7
Free hard disk space: 2G
Javac: Oracle Javac 1.8.0_66
Python: 2.7
g++: 4.9
Bazel: 0.1.1
SWIG: 2.0.11
TensorFlow:  f9514a917265f0e98c8fb44abc51158685f72ca6

**Comment by martinwicke** [comment]
We'll look into modifying the build scripts to that information lands in the logs.

**Comment by EricGT** [comment]
Thanks. I may have more details as I find other tools/options that effect the success of the builds.

**Comment by EricGT** [comment]
Please add the Bazel --local_resouces configuration to the list as it is significant:
 --local_resouces: http://bazel.io/docs/bazel-user-manual.html#flag--local_resources
Results of changing values: http://stackoverflow.com/a/34770965/1243762

**Comment by martinwicke** [comment]
@caisq can you add some output to the scripts? I think they're all run through configured, so maybe that's the right place to put it.

**Comment by caisq** [comment]
Please close the issue. See: https://github.com/tensorflow/tensorflow/pull/979.

Jenkins builds now shows descriptions that contain JSON objects with info about the build, including build container type, command, platform/OS, build tools and source version. For example: 
http://ci.tensorflow.org/job/tensorflow-master/171/

**Comment by jendap** [comment]
I have removed the machine configuration from build descriptions. It was making too much noise. The description stays in the output log.

@EricGT what is your use case to ask for this? Note you are able to replicate any of the linux builds trivially. The only thing you need is docker. See [ci_build/README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/README.md) These scripts can be used for great dev setup. I will update the documentation how to do it on windows and mac as well.

Also the most of the things you suggest (and we currently print) does not (should not) matter for the build. Swap, cpu, disk space, kernel, java version, and bunch of other things does not matter. On the other hand I'm not sure how long does it take people to figure out they need to use something like "--jobs 1 --local_resources 512,1,1" to build on 4GB ram. We should write a blog about those things.
