### ISSUE TITLE
Tensor Flow GPU support on Windows

### ISSUE THREAD

**Issue by balachander1964** [tensorflow/tensorflow#73652]
Hi. Balachander here. I am a visually impaired person working on AI as a data scientist and ML engineer. I am predominantly using Windows for all my development activities as Windows provides a full fledged support for Screen Readers. Also they provide development tools those are fully accessible to people like me. Removing GPU support from Tensorflow on Windows is a worst violation and discriminatory, as it hits people like me. Dockers with Linux OS do not come with screen readers. I request you to re-enable TF to provide support GPUs on Windows and MAC systems so that we don't get hit. I appreciate your quick attention and help. Thank you.

**Comment by Venkat6871** [comment]
Hi **@balachander1964** ,
There is an ongoing issue related to this conversion. Please review issue number [59918](https://github.com/tensorflow/tensorflow/issues/59918) for more details. And  GPU support on native-Windows is only available for 2.10 or earlier versions, starting in TF 2.11, CUDA build is not supported for Windows. For using TensorFlow GPU on Windows, you will need to build/install TensorFlow in WSL2 or use tensorflow-cpu with TensorFlow-DirectML-Plugin.
Thank you!

**Comment by balachander1964** [comment]
Thank you Venkat. I will try your suggestion. I appreciate your reply.
