### ISSUE TITLE
Following cuda install directions can lead to wrong version

### ISSUE THREAD

**Issue by iandanforth** [tensorflow/tensorflow#737]
If you follow the link from the cuda install directions, and are trying to install under Ubuntu you will end up on this page:

https://developer.nvidia.com/cuda-toolkit-70

Unfortunately if you select the "Network Install" option and install the repository deb, you will end up installing cuda 7.5 not 7.0.

I suggest mentioning this before users click through to nvidia's site in the docs:

https://www.tensorflow.org/versions/master/get_started/os_setup.html#optional-install-cuda-gpus-on-linux

**Comment by girving** [comment]
@martinwicke: Is this obsolete now that we support 7.5?

**Comment by martinwicke** [comment]
Yes.
