### ISSUE TITLE
number of class mismatch between .py file and .ckpt, which makes wrong prediction.

### ISSUE THREAD

**Issue by civilman628** [tensorflow/tensorflow#7370]
the total class which is assigned num_classes=1000 in the file below.

https://github.com/tensorflow/models/blob/master/slim/nets/inception_v2.py

however, the published checkpoint file on the page below  for inception v2 is 1001.

https://github.com/tensorflow/models/tree/master/slim

The prediction use this check point file is wrong, even if we update num_classes=1001 in the code. the wrong prediction is not shift 1 position, but completely mess.

**Comment by girving** [comment]
@nathansilberman Do you know the source of the off-by-one error?

**Comment by yifeif** [comment]
@nathansilberman @sguada  could you take a look? Thank you!

**Comment by sguada** [comment]
For training we reserve the class 0 for back-ground.
See https://github.com/tensorflow/models/blob/master/slim/datasets/imagenet.py#L59

**Comment by Androbin** [comment]
@sguada Okay, but I don't think this resolves the main concern here:
> The prediction use this check point file is wrong, even if we update num_classes=1001 in the code. the wrong prediction is not shift 1 position, but completely mess.
