### ISSUE TITLE
[Building from source with bazel] Failure when linking libm-libraries during compilation of flatbuffers

### ISSUE THREAD

**Issue by hanssssssssssssss** [tensorflow/tensorflow#73798]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.17

### Custom code

No

### OS platform and distribution

Linux Debian 5.10.216-1 x86_64

### Python version

3.12

### Bazel version

7.3.0

### GCC/compiler version

clang 17.0.2

### CUDA/cuDNN version

CUDA 12 /cuDNN 8

### GPU model and memory

NVIDIA A2

### Current behavior?

I'm trying to build tensorflow from source with bazel for use in a C++ project. I'm working in a conda environment wit the specifics mentioned above and try to compile the libraries with the following command:

`bazel build //tensorflow:libtensorflow_cc.so //tensorflow:libtensorflow_framework.so`

Bazel fails with the follwing error message:
```
ERROR: /my/home/path/cache/bazel/_bazel_myuser/45c6a78e7c7688232d885d39238fef70/external/flatbuffers/BUILD.bazel:84:10: Linking external/flatbuffers/flatc [for tool] failed: (Exit 1): clang-17 failed: error executing command (from target @flatbuffers//:flatc) /my/home/path/.conda/envs/poet/bin/clang-17 @bazel-out/k8-opt-exec-50AE0418/bin/external/flatbuffers/flatc-2.params
/usr/bin/ld: warning: /my/home/path/.conda/envs/poet/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/crtbeginS.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010002
/usr/bin/ld: warning: /my/home/path/.conda/envs/poet/bin/../lib/gcc/x86_64-conda-linux-gnu/14.1.0/crtbeginS.o: unsupported GNU_PROPERTY_TYPE (5) type: 0xc0010001
/usr/bin/ld: cannot find /lib64/libm.so.6 inside /
/usr/bin/ld: cannot find /usr/lib64/libmvec_nonshared.a inside /
/usr/bin/ld: cannot find /lib64/libmvec.so.1 inside /
clang-17: error: linker command failed with exit code 1 (use -v to see invocation)
```
 I tried to add the following lines to `.bazelrc` to explicitly link the locations of the libraries that were not found. That did not change the error.
```
build:linux --linkopt=-L/mnt/beegfs/home/straile/.conda/envs/poet/x86_64-conda-linux-gnu/sysroot/lib64
build:linux --linkopt=-L/mnt/beegfs/home/straile/.conda/envs/poet/x86_64-conda-linux-gnu/sysroot/usr/lib64
build:linux --linkopt=-Wl,-rpath,/mnt/beegfs/home/straile/.conda/envs/poet/x86_64-conda-linux-gnu/sysroot/lib64
build:linux --linkopt=-Wl,-rpath,/mnt/beegfs/home/straile/.conda/envs/poet/x86_64-conda-linux-gnu/sysroot/usr/lib64
```

Any help on this issue is much appreciated.

### Standalone code to reproduce the issue

```shell
git clone https://github.com/tensorflow/tensorflow.git
cd tensorflow
git checkout r2.17
./configure 
# [with CUDA version 12, cuDNN version 8, NCCL version 2.18, compute capabilities 8.6]
# I also had to add "linux:build --copt=-Qunused-arguments" to .bazelrc to ignore compile errors in protoc
bazel build //tensorflow:libtensorflow_cc.so //tensorflow:libtensorflow_framework.so
```

**Comment by Venkat6871** [comment]
Hi **@hanssssssssssssss** ,
- Apologies for the delay. This might be due to a version incompatibility. Please verify version compatibility using the attached [documentation](https://www.tensorflow.org/install/source#gpu). Let me know if the issue persists. 

Thank you!
