### ISSUE TITLE
[Discussion] Limit the exported symbols from _pywrap_tensorflow.so

### ISSUE THREAD

**Issue by llhe** [tensorflow/tensorflow#7380]
TensorFlow statically links many fundamental libraries and exported all their symbols, this can cause version conflict for other modules outside of TensorFlow which links against a different version library, see [the symbol lookup rules](http://stackoverflow.com/questions/12666248/elf-dynamic-loader-symbol-lookup-ordering).

For example, I have a script which involves TensorFlow and matplotlib. Just start a Python CLI and execute:
```
import tensorflow af tf
import matplotlib.pyplot as plt
# ...
plt.show()
```
The matplotlib may links to libpng symbols from _pywrap_tensorflow.so instead of libpng even though the only installed libpng is the correct one. And it will complains and fails:
```
libpng warning: Application was compiled with png.h from libpng-1.6.21
libpng warning: Application  is  running with png.c from libpng-1.2.53
libpng error: Incompatible libpng version in application and library
```
Similar to #1927 and #1924

Fortunately, we have a clear interface, the SWIG APIs. So we may consider only exporting these symbols, [here is the guide](https://www.gnu.org/software/gnulib/manual/html_node/Exported-Symbols-of-Shared-Libraries.html).

This also applies to other shared libraries like libtensorflow.so which export C/C++ interfaces.

**Comment by girving** [comment]
@martinwicke Care to comment?  I'm not sure if Bazel supports this, and we'd have to maintain it.

**Comment by yaroslavvb** [comment]
I wonder if that may be to blame for crashes we've seen with some tensorflow import orders.
For instance we found that we need to import opencv before TensorFlow, also to import [go-vncdriver](https://github.com/openai/go-vncdriver) before TensorFlow

**Comment by yaroslavvb** [comment]
It seems there's already some limiting going on, @keveman added `exported_symbols_list` to `extra_linkopts ` in https://github.com/tensorflow/tensorflow/commit/5405394ecbc92baf9c45e612185ab42b1dcd0a30 to fix a crash in https://github.com/tensorflow/tensorflow/issues/1992 , so perhaps it's just a matter of adding those `extra_linkopts` to whichever target builds `libtensorflow.so`?

**Comment by martinwicke** [comment]
I would love it if we limited what is exported from that library. Where
does this `.lds` file come from? @keveman can probably help more than I do.

**Comment by keveman** [comment]
@yaroslavvb is correct, `_pywrap_tensorflow.so` only exports symbols that have `tensorflow` in them. It is indeed strange that the `png*` symbols are leaked from`_pywrap_tensorflow.so`  even with the [linker script](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tf_version_script.lds) only allowing `tensorflow` symbols. @llhe, do you have any ideas why this may be?

**Comment by llhe** [comment]
@keveman I found the root cause. We build tensorflow by ourself, and made some changes on the bazel build script and misused the [bazel select feature](https://bazel.build/versions/master/docs/be/functions.html#select), which disabled the version-script settings. So this should also explain the mysterious segfaults when using HDFS in our build reported in #5399.

**Comment by llhe** [comment]
@yaroslavvb I checked the official _pywrap_tensorflow.so, it exports expected symbols, so it should not be the cause. Also checked CUDA  library
```
find /usr/local/cuda/lib64/ -name *cu*.so -exec nm -D {} \; | grep " T "
```
Generally, only symbols prefixed cu are exported except some fftw symbols which should also be expected I guess:
```
0000000000008610 T fftw_cleanup
0000000000008590 T fftw_cost
0000000000008ef0 T fftw_destroy_plan
0000000000009260 T fftw_execute
0000000000009250 T fftw_execute_dft
0000000000009230 T fftw_execute_dft_c2r
0000000000009240 T fftw_execute_dft_r2c
0000000000008d60 T fftw_export_wisdom_to_file
0000000000008620 T fftwf_cleanup
00000000000085a0 T fftwf_cost
0000000000008f80 T fftwf_destroy_plan
0000000000009210 T fftwf_execute
0000000000009200 T fftwf_execute_dft
00000000000091e0 T fftwf_execute_dft_c2r
00000000000091f0 T fftwf_execute_dft_r2c
0000000000008ee0 T fftwf_export_wisdom_to_file
00000000000085e0 T fftwf_flops
0000000000008630 T fftwf_free
000000000000c7a0 T fftwf_import_wisdom_from_file
00000000000085b0 T fftw_flops
0000000000008650 T fftwf_malloc
000000000000bd50 T fftwf_plan_dft
000000000000c490 T fftwf_plan_dft_1d
000000000000c230 T fftwf_plan_dft_2d
000000000000bfb0 T fftwf_plan_dft_3d
000000000000bcf0 T fftwf_plan_dft_c2r
000000000000c450 T fftwf_plan_dft_c2r_1d
000000000000c1d0 T fftwf_plan_dft_c2r_2d
000000000000bf50 T fftwf_plan_dft_c2r_3d
000000000000bd20 T fftwf_plan_dft_r2c
000000000000c470 T fftwf_plan_dft_r2c_1d
000000000000c200 T fftwf_plan_dft_r2c_2d
000000000000bf80 T fftwf_plan_dft_r2c_3d
000000000000a350 T fftwf_plan_guru_dft
0000000000009fd0 T fftwf_plan_guru_dft_c2r
000000000000a190 T fftwf_plan_guru_dft_r2c
000000000000b5e0 T fftwf_plan_many_dft
000000000000b500 T fftwf_plan_many_dft_c2r
000000000000b570 T fftwf_plan_many_dft_r2c
0000000000008d50 T fftwf_print_plan
0000000000008640 T fftw_free
0000000000008580 T fftwf_set_timelimit
000000000000c5d0 T fftw_import_wisdom_from_file
0000000000008660 T fftw_malloc
000000000000be80 T fftw_plan_dft
000000000000c5b0 T fftw_plan_dft_1d
000000000000c370 T fftw_plan_dft_2d
000000000000c0f0 T fftw_plan_dft_3d
000000000000be20 T fftw_plan_dft_c2r
000000000000c570 T fftw_plan_dft_c2r_1d
000000000000c310 T fftw_plan_dft_c2r_2d
000000000000c090 T fftw_plan_dft_c2r_3d
000000000000be50 T fftw_plan_dft_r2c
000000000000c590 T fftw_plan_dft_r2c_1d
000000000000c340 T fftw_plan_dft_r2c_2d
000000000000c0c0 T fftw_plan_dft_r2c_3d
000000000000a8c0 T fftw_plan_guru_dft
000000000000a520 T fftw_plan_guru_dft_c2r
000000000000a6f0 T fftw_plan_guru_dft_r2c
000000000000b730 T fftw_plan_many_dft
000000000000b650 T fftw_plan_many_dft_c2r
000000000000b6c0 T fftw_plan_many_dft_r2c
0000000000008c20 T fftw_print_plan
0000000000008570 T fftw_set_timelimit
```
`nm` is nice tool to verify the shared libraries symbols.

**Comment by llhe** [comment]
LG_DEBUG may also be useful for debug.

**Comment by yaroslavvb** [comment]
Nice investigation! Bazel's select brings back some memories....we spent time debugging why we couldn't package our custom GPU ops as a Bazel project that depends on TensorFlow as a submodule....turned it out that Bazel's select is [not sensitive](http://stackoverflow.com/questions/41153199/building-a-tensorflow-based-android-app-with-tensorflow-as-a-repository) to workspace it's defined in, and custom_op/cuda had a bunch of those.

**Comment by yaroslavvb** [comment]
Feel free to close this issue unless there's something that's not addressed

**Comment by ppwwyyxx** [comment]
Asking for some comments: TF is now hiding all protobuf symbols, this makes it annoying when I want to write a custom op which uses protobuf symbols. It seems like I have to find the version of protobuf that tensorflow is linked to, and link to it when compiling the op.
Can we export protobuf symbols as well?

**Comment by MaskRay** [comment]
@ppwwyyxx 

```diff
--- a/tensorflow/tf_version_script.lds	2017-04-07 22:37:11.949060397 +0000
+++ b/tensorflow/tf_version_script.lds	2017-04-07 22:36:25.300982684 +0000
@@ -2,6 +2,9 @@
   global:
     *tensorflow*;
     *perftools*gputools*;
+    extern "C++" {
+      google::protobuf::MessageLite::*;
+    };
   local:
     *;
 };
```


I need a graphics card.......... UUUUUUUUUUUU 呜呜呜呜
