### ISSUE TITLE
Tensorflow gemmlowp preformance

### ISSUE THREAD

**Issue by wonderzy** [tensorflow/tensorflow#7381]
I ran the tensorflow android demo on android with the google inception model. I used the quantized model transformed from tools/quantize_graph but  was sad to found that the gemmlowp works worse than float Eigen convolution on Android. Any suggestions to this , thanks a lot.

**Comment by girving** [comment]
Please ask questions like on StackOverflow; Github issues are for feature requests and bug reports.  If you want to report a performance issue, we would need a lot more information.
