### ISSUE TITLE
[TensorBoard] load data from relative path

### ISSUE THREAD

**Issue by geromueller** [tensorflow/tensorflow#7382]
To embed tensorBoard the data needs to be loaded from a relative directory, not /data.

**Comment by girving** [comment]
We would need more details to know what kind of issue you are having.

**Comment by geromueller** [comment]
we embed TensorBoard in our platform and mount the wsgi app under a certain path, eg. /extension/tb/12345/. So TB should get its data from /extension/tb/12345/data instead of /data

**Comment by girving** [comment]
I'm pretty sure we still need more details, but @dandelionmane may have a clearer idea.

**Comment by dandelionmane** [comment]
I believe removing the leading slash [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/components/tf_backend/router.ts#L39) would fix it?


Do you want to submit a pull request?

n.b. currently Bazel doesn't compile TensorBoard. We're actively fixing this right now. But until the next release, you will need to [recompile the TensorBoard frontend yourself](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/DEVELOPMENT.md) to test the fix.

**Comment by geromueller** [comment]
Hi!

Yes, thats it! I removed the slash from the compiled js code and it works. Preparing a PR. Thanks!

**Comment by geromueller** [comment]
okay, will not prepare an PR since i would have to undergo all the CLA for just one character.

**Comment by dandelionmane** [comment]
Haha, I can do it on my end :)

**Comment by lspvic** [comment]
@dandelionmane 
Another place that still has the similar problem is the request of project plugin data in Embeddings panel,
e.g.  /data/plugin/projector/runs still requests in a absolute path.
I found the code  [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/components/tf_tensorboard/tf-tensorboard.html#L134)
There is a leading slash for the `route-prefix` property in `vz-projector-dashboard`.
If it's correct, I will submit a PR. Thanks!

Another question is when will the tensorboard be recompiled. As now in version 1.0 these features are not included.
