### ISSUE TITLE
use cuda7.5 on windows

### ISSUE THREAD

**Issue by caiqi** [tensorflow/tensorflow#7383]
I installed tensorflow-gpu with pip on windows. But it does not work with cuda7.5. And there is no way to update cuda due to driver limit. Is there any way to use cuda7.5 on windows with tensorflow-gpu? Or is there any tutorial about how to compile tensorflow with cuda7.5 on windows?  Thanks.

**Comment by girving** [comment]
Please ask questions like this on StackOverflow.  Github issues are for feature requests and bug reports.
