### ISSUE TITLE
[Tensorboard Request]Ignoring specific subdirectories

### ISSUE THREAD

**Issue by jyh2986** [tensorflow/tensorflow#7385]
I think this will be simple but very useful feature for Tensorboard.

What I want is the ignoring specific subdirectories.

Tensorboard load all of subdirectries and display them, but it become slower as more subfolders are added. So, I just want to ignore some directories without moving them.

There's several options to do this.
1. If there is special character(like #) in folder name, just ignore it.
2. Like git, .ignore file manage folders to ignore.
3. If .nolog file in the folder to ignore.(Like .nomedia file)

I think option 3 is best, because folder structure can be changed.

**Comment by girving** [comment]
@dandelionmane Do you like any of these options?

**Comment by wchargin** [comment]
I've migrated this to our new repository at https://github.com/tensorflow/tensorboard/issues/70. Feel free to continue discussion there.
