### ISSUE TITLE
memory crash when putting model.fit within a for loop

### ISSUE THREAD

**Issue by gff77** [tensorflow/tensorflow#73864]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.17.0

### Custom code

Yes

### OS platform and distribution

windows x64

### Current behavior?

Hi,

I also read on the web that this issue is present for multiple users, I updated my TF but the problem is still present.

if you put the **model.fit**  inside the loop, it seems that TF loads the data each time and saves it in the memory finally RAM crashes.
clear session and garbage collection do not work.

### Standalone code to reproduce the issue

```shell
for r in range(0, 10000):
    model.compile(optimizer='sgd', loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True))
    model.fit(data, epochs=1)
```

**Comment by tilakrayal** [comment]
@gff77,
Could you please provide the complete code you are trying which helps to reproduce the issue? Thank you!

**Comment by sanskarmodi8** [comment]
Try removing the model.compile from the loop if it's unnecessary to compile the model each time. This can help reduce memory usage and improve performance.
