### ISSUE TITLE
error with bazel build in windows

### ISSUE THREAD

**Issue by davideb91** [tensorflow/tensorflow#7388]
I'm trying to build Tensorflow android camera demo in Windows.
When I try to build the application with 

`bazel build -c opt //tensorflow/examples/android:tensorflow_demo`

I have these errors:

```
ERROR: missing input file '@androidsdk//:build-tools/25.0.1/aapt'.
ERROR: C:/Users/DAVIDE/AppData/Local/Temp/_bazel_davide.biraghi/55PhBU2g/external/androidsdk/BUILD:5:1: Executing genrule @androidsdk//:zipalign_runner failed: bazel failed: error executing command C:/ProgramData/chocolatey/lib/bazel -c ... (remaining 1 argument(s) skipped): java.io.IOException: CreateProcess(): Access is denied.
.
ERROR: C:/Users/DAVIDE/AppData/Local/Temp/_bazel_davidee/55PhBU2g/external/androidsdk/BUILD:5:1: @androidsdk//:aapt_binary: missing input file '@androidsdk//:build-tools/25.0.1/aapt'.
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: C:/Users/DAVIDE/AppData/Local/Temp/_bazel_davide/55PhBU2g/external/androidsdk/BUILD:5:1 1 input file(s) do not exist.
```

I have android sdk installed with the 25.0.1 build-tools version and the aapt file. I have also modified my WORKSPACE with the correct path (and version. I tried also with version 24.0.1 with same error).  I'm working on Windows 10. Any suggestion?

**Comment by girving** [comment]
@andrewharp Can you comment?  Haven't seen many Android + Windows bugs yet.

**Comment by andrewharp** [comment]
Unfortunately Bazel doesn't support Android builds on Windows yet -- that seems to be [planned for 0.8](https://bazel.build/roadmap.html)

In the meantime I'd suggest using the [prebuilt libraries](https://ci.tensorflow.org/view/Nightly/job/nightly-android/) or waiting for the upcoming cmake demo build support.
