### ISSUE TITLE
Add unsorted segment ops for prod, min, mean, sqrt_n

### ISSUE THREAD

**Issue by PhilJd** [tensorflow/tensorflow#7389]
As requested by @girving in #7362 I'll file a separate issue.

The sorted segment reduction ops feature  prod, min, mean, sqrt_n while the unsorted ops don't include those. So I suggest to add the following functions:
```
tf.unsorted_segment_prod(data, segment_ids, num_segments, name=None)
tf.unsorted_segment_min(data, segment_ids, num_segments, name=None)
tf.unsorted_segment_mean(data, segment_ids, num_segments, name=None)
tf.unsorted_segment_sqrt_n(data, segment_ids, num_segments, name=None
```

If you mark this as contributions welcome, I'd start working on this.

**Comment by girving** [comment]
Thank you for splitting this out!

**Comment by girving** [comment]
I'd recommend spelling it `num_segments`, though.

**Comment by PhilJd** [comment]
Sorry, of course! Stupid typo, I'll change the issue description.

**Comment by lidalei** [comment]
I am implementing batch k-means. In the update phase, new centers have to be computed according to the points re-assignments. It would make thing easier if there is unsorted_segment_mean.

**Comment by PhilJd** [comment]
Hi,
sorry, I've been rather busy in the last weeks. I'm 95% done implementing the CPU Kernels, with a bug remaining. Thanks for reminding me, I'll have a look at it tomorrow!
Cheers,
Phil

**Comment by PhilJd** [comment]
For now you could just compute the mean with existing tensorflow functions, e.g.

```
import tensorflow as tf
x = tf.constant([1.0, 2.0, 3.0, 4.0])
ids = tf.constant([0, 1, 0, 1])
ones = tf.ones_like(x)
count = tf.unsorted_segment_sum(ones, ids, 2)
sums = tf.unsorted_segment_sum(x, ids, 2)
mean = tf.divide(sums, count)
s = tf.Session()
s.run(mean)

```

**Comment by lidalei** [comment]
This is great! Thanks a lot!

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
