### ISSUE TITLE
Does TensorFlow support Fast R-CNN currenly?

### ISSUE THREAD

**Issue by ExonRen** [tensorflow/tensorflow#739]
I've been working on transplanting Fast R-CNN to a TensorFlow version. And I came across 2 problems as below:

1. In [roi_pooling_layer.cpp](https://github.com/rbgirshick/caffe-fast-rcnn/blob/fast-rcnn/src/caffe/layers/roi_pooling_layer.cpp), the C++ implementation of RoI Pooling layer, a dynamic variable `num_rois` is used to control a loop to process each roi of each picture. Its value is stored in the original dataset and will only be valid during the graph is running. However, since the graph in TensorFlow has to be settled before it being run, I don't know what to put in the loop control as the iteration limit.

2. After the roi_pooling_layer, there follows a InnerProduct layer (in Caffe), the shape of whose input depends on the output shape of the roi_pooling_layer, which ultimately depends on `num_rois`. So the shape of the corresponding `weight_variable` and `bias_variable` for the following operation `matmul`, which is going to act as the InnerProduct layer, cannot be settled before the graph is running.

In addition, in the RoI Pooling layer, there are some other loop control variables based on the former calculation, like `hstart`, `hend`, `wstart` and `wend`. They are even harder to get valid values before the graph is built, because the `num_rois` is part of the input after all.

So may I ask if TensorFlow supports Fast R-CNN (currently)? Or are there any possible specific tips to solve these problems?

Thank you!

**Comment by vrv** [comment]
This is probably a question meant for StackOverflow, Github issues are for bugs / feature requests.  You'll get more help from the community there.

**Comment by Irtza** [comment]
@ExonRen I was thinking to that too, did you get any further with fast R-CNN on tensorflow?

**Comment by parhartanvir** [comment]
I too am interested in fast rcnn implementation on tensorflow.
Is there any progress so far?

**Comment by ExonRen** [comment]
@Irtza @parhartanvir Sorry to reply so late. I'm a Chinese and it was Spring Festival shortly after I finished my work on this. And now I've turned to my graduation project. But I think I should provide some introduction to my progress.
I didn't get to the expected destination finally. Those problems I posted last year still puzzles me. **I only implemented the test part (i.e. the forward part) as some substitute at last.** The whole graph had to be split to 3 parts: before the `roi_pooling`, after it and itself. The 1st and 3rd part were executed by TensorFlow `Session.run()` while the `roi_pooling` itself by original Python. In other words, I had to write a Python function playing the same role as the [roi_pooling_layer.cpp](https://github.com/rbgirshick/caffe-fast-rcnn/blob/fast-rcnn/src/caffe/layers/roi_pooling_layer.cpp), which leads to a

**Comment by ExonRen** [comment]
@Irtza @parhartanvir Sorry to reply so late. I'm a Chinese and it was the Spring Festival shortly after I finished my work on this. And now I've turned to my graduation project. But I still think I should provide some introduction to my progress here.

In fact I didn't get to the expected destination. **I only implemented the test part (i.e. the forward calculation part) of Fast-RCNN.** The whole graph has to be split into three phases: before the `roi_pooling`, after it and itself. 

+ *Part one* is just constructed in TensorFlow operations and executed by `Session.run()`.
+ And *part two*, i.e. `roi_pooling` itself is written in native Python. In other words, I implement a Python function playing the same role as the [roi_pooling_layer.cpp](https://github.com/rbgirshick/caffe-fast-rcnn/blob/fast-rcnn/src/caffe/layers/roi_pooling_layer.cpp), which leads to a definitely slow speed. 
+ Additionally, *part three*, which is also a native Python loop (for each ROI) with TensorFlow `run()` inside, makes some contributions to the poor performance too. 
+ Approximately it would take about 70s to process one image, where the first part less than 1s and third part about 6s.

Then I spent some more time to change the Python `roi_pooling` function back in C, and use Cython to linked them together. Due to the efficiency of C, the time cost per image takes a great step to 7s or 8s. Actually, the main 60s of old *part two* has become to 1/300, which is 0.2s, and faster than any other part now.

I'm not sure if my reply is too long, but I hope it can be helpful to you. :D

**Comment by rollingstone** [comment]
@ ExonRen hi, thanks for info. do u have any plan to share the code somewhere? thanks

**Comment by gongenhao** [comment]
@ExonRen Any way to share your code or work together?

**Comment by ExonRen** [comment]
@rollingstone @gongenhao I'm still busy working on my graduation paper, and I think I'll upload my code after finishing this. Maybe at the end of May or the beginning of June.

**Comment by Irtza** [comment]
@ExonRen Sounds great.

**Comment by kyu9** [comment]
@ExonRen @Irtza  I saw https://github.com/yuxng/tensorflow, he also implemented roi pooling layer in tensorflow. But I do not have time to test this. Maybe you will get more idea for Faster-RCNN in TF.

**Comment by ExonRen** [comment]
@ck196 Ah yes he did a good job. He implemented the RoIPooling directly in C++ as a new operation, while I just worked out some Python codes to do a similar task, due to the narrow arrangement. So I believe his implementation should be much more efficient and helpful.

**Comment by entron** [comment]
If you don't mind not using TF, then there are implementations (fast/faster) with chainer:

https://github.com/apple2373/chainer-simple-fast-rnn
https://github.com/mitmul/chainer-faster-rcnn

**Comment by zplizzi** [comment]
I've also implemented the ROI pooling op for Tensorflow. I have both the forward and gradient op, with both a CPU and GPU (CUDA) kernel. There's also example Ipython notebooks demoing how they're used. 

The full Fast-RCNN network is still a work-in-progress, but I've run a simplified version of it successfully on my own computer. I'm still working on packaging it up so other people can try it out too.

Check it all out here: [https://github.com/zplizzi/tensorflow-fast-rcnn](https://github.com/zplizzi/tensorflow-fast-rcnn).

**Comment by zplizzi** [comment]
@ExonRen as to your original second point about undetermined tensor sizes: Tensorflow does support this. For example, setting the shape of the input ROI tensor to [None, 4] will allow an input of any number of ROIs (each a vector of length 4). Then, if you want to do reshapes later in the network, setting a specific dimension to -1 (you can do this for only one dimension, of course) will have that dimension auto-sized according to the number of elements in the tensor.

**Comment by thomasklau** [comment]
Can we hope to see these new features added to default tensorflow any time soon?

**Comment by zplizzi** [comment]
Hopefully! Personally, I'd prefer to finish up my Fast-RCNN model and do some more testing to be extra sure everything works properly before moving towards a merge into master Tensorflow. Or, if someone else tested out some of the code and reported positive results, I'd be good with that also.

**Comment by ck196** [comment]
@zplizzi Can I only use user_ops to compile with TF binary version?

**Comment by zplizzi** [comment]
@ck196 I think that is supposed to be possible (check out the guide [here](https://www.tensorflow.org/versions/r0.10/how_tos/adding_an_op/index.html#with-tensorflow-binary-installation)), but I've not tried it myself.

**Comment by ck196** [comment]
@zplizzi Thank you.

**Comment by ck196** [comment]
@zplizzi I can run roi pooling with you implementation now. In your examples, I do not see the bounding box regression step. Do you have plan to write some instructions about it.

**Comment by zplizzi** [comment]
@ck196 That's great! I've not yet implemented the bounding box regression part of the network - that's one of the things on my to-do list for this project.

**Comment by isabel-schwende** [comment]
@zplizzi thanks for sharing your code here. In your preliminary demo for fast-RCNN you used Selective Search for ROI extraction. I've been searching for an implementation of EdgeBoxes in python but couldn't find anything available without the requirement of a MATLAB license. I'm assuming that you also couldn't find an implementation. Or did you have another reason for taking Selective Search?

**Comment by zplizzi** [comment]
@isabel-schwende I used Selective Search since, if I remember correctly, it's what was used in the original RCNN and Fast-RCNN papers. Not knowing much of anything about region proposal algorithms, I figured that was probably a good endorsement and haven't tried anything else. I'm not sure that the Python implementation is very good or fast, but I'd personally probably lean towards working on getting Faster-RCNN working vs trying to improve an external region proposal system.

**Comment by ck196** [comment]
@zplizzi I have a question about rois processing. input_rois  are original (from xml) rois/ scale_factor(16), aren't they ?
Do we need to resize rois? Because in network we resize image such as "original image -> input image (224x224 - vgg) ...).

**Comment by zplizzi** [comment]
If you guys don't mind, let's try to move discussion specifically about my implementation of Fast RCNN / ROI pooling off of this issue, to avoid bothering the nice TensorFlow folks. Feel free to open an issue on my repository, even if it's just to ask a question about something that doesn't quite make sense. 

@ck196, I'm going to copy your question to a new issue on my repo and I'll answer it there.
