### ISSUE TITLE
docs: Broken link/missing py file in Model Files guide

### ISSUE THREAD

**Issue by yufengg** [tensorflow/tensorflow#7392]
On the page ["A Tool Developer's Guide to TensorFlow Model Files"](https://www.tensorflow.org/how_tos/tool_developers/)
([GitHub md link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/tool_developers/index.md))

In the GraphDef section, there's a link to `graph_metrics.py`, pointing to the url https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/graph_metrics.py

This url does not exist. Perhaps it's intended to point at a different file in that folder? I don't see an obvious suitable replacement from scanning the filenames listed: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/tools

**Comment by girving** [comment]
@petewarden This one of your doc files?

**Comment by petewarden** [comment]
graph_metrics.py was removed, so we should update the docs.
