### ISSUE TITLE
MSVC requires C++20 (instead of C++17)

### ISSUE THREAD

**Issue by pierreguillot** [tensorflow/tensorflow#73930]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.17.0

### Custom code

No

### OS platform and distribution

Windows -  Microsoft Windows Server 2022 - 10.0.20348

### GCC/compiler version

Visual Studio 17 2022 - MSVC 19.40.33813.0

### Current behavior?

The compilation of tensorflow-lite fails with the error ([log](https://github.com/Ircam-Partiels/basic-pitch-vamp-plugin/actions/runs/10418185216/job/28853936586#step:6:608)):
```
tensorflow\tensorflow\lite\core\c\operator.cc(35,29): error C7555: use of designated initializers requires at least ‘/std:c++20’
```
And same errors are generated by XNNPACK ([log](https://github.com/Ircam-Partiels/basic-pitch-vamp-plugin/actions/runs/10418185216/job/28853936586#step:6:639))

Using `set(CMAKE_CXX_STANDARD 20)` instead of `set(CMAKE_CXX_STANDARD 17)` [here](https://github.com/tensorflow/tensorflow/blob/v2.17.0/tensorflow/lite/CMakeLists.txt#L87) fixes the problem.

P.S. I use CMake 3.30

Here is an open-source project that compiles tensorflow via CMake 
https://github.com/Ircam-Partiels/basic-pitch-vamp-plugin

### Standalone code to reproduce the issue

```shell
Here is an open-source project that compiles tensorflow via CMake 

https://github.com/Ircam-Partiels/basic-pitch-vamp-plugin
```

### Relevant log output

```shell
tensorflow\tensorflow\lite\core\c\operator.cc(35,29): error C7555: use of designated initializers requires at least ‘/std:c++20’
```

**Comment by demian-j-lim** [comment]
i try to code.
:)

operator.cc
`TfLiteOperator* TfLiteOperatorCreateWithData(TfLiteBuiltinOperator builtin_code,
                                             const char* custom_name,
                                             int version, void* user_data) {
    TfLiteOperator* op = new TfLiteOperator();
    op->custom_name = custom_name;
    op->version = version;
    op->init = nullptr;
    op->free = nullptr;
    op->prepare = nullptr;
    op->invoke = nullptr;
    op->async_kernel = nullptr;
    op->builtin_code = builtin_code;
    op->node_index = -1;
    op->inplace_operator = kTfLiteInplaceOpNone;
    op->user_data = user_data;

    return op;
}`
