### ISSUE TITLE
Have Docker Build not Install via Pip

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [tensorflow/tensorflow#7393]
In the [Development Dockerfile](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.devel), I see this note,

```
# TODO(craigcitro): Don't install the pip package, since it makes it
# more difficult to experiment with local changes. Instead, just add
# the built directory to the path.
```

Due to the [lack of important header files](https://github.com/tensorflow/tensorflow/issues/1419) in mainstream Tensorflow, I need to patch the TF build so I can get those headers. Unfortunately, the current Dockerfile clears the Bazel cache. I am requesting that the above TODO, be resolved soon, so I can patch Tensorflow's Bazel BUILD files in order to make local changes and build quicker. Rebuilding TF without a cache in the container takes a pretty long time.

**Comment by aidan-plenert-macdonald** [comment]
This is the patch I do, in case it is important
```
diff --git a/tensorflow/tools/pip_package/BUILD b/tensorflow/tools/pip_package/BUILD
index 6a3f66b..c88840a 100644
--- a/tensorflow/tools/pip_package/BUILD
+++ b/tensorflow/tools/pip_package/BUILD
@@ -26,6 +26,8 @@ transitive_hdrs(
         "//tensorflow/core:core_cpu",
         "//tensorflow/core:framework",
         "//tensorflow/core:lib",
+        "//tensorflow/core:proto_text",
+        "//tensorflow/core:all_kernels",
         "//tensorflow/core:protos_all_cc",
         "//tensorflow/core:stream_executor",
         "//third_party/eigen3",
```

**Comment by girving** [comment]
@caisq Can you comment on this Docker request?

**Comment by gunan** [comment]
I think we started to recently run bazel clean, as bazel cache can be in the order of Giga bytes.
This was a move to limit the size of docker containers for people with bandwidth concerns.
In the US this is not a very big concern, but this can be very important in other countries where ISPs have strict data caps.

In any changes you make, you should only need to build once.
You can reuse the container you previously built in by running `docker restart <containername>`, and then `docker  attach <containername>`, so you do not have to lose any of the build files you accumulated. So you should not need to build more than once.

Another option you have, you can always pull our docker image, then start a container with it, create the bazel cache and create your own image with the bazel cache intact on top of our image.
You simply need to start another terminal, check the name of the container running using `docker ps`, then use `docker commit` command to create your own image: https://docs.docker.com/engine/reference/commandline/commit/

Please let me know if the above explanation and workarounds make sense.

**Comment by caisq** [comment]
Yeah, as @gunan pointed out, our devel docker images (especially the GPU one) used to be so large that they caused download and disk space issues to users, so we removed the bazel cache, which reduced the image size by about 50%.

**Comment by caisq** [comment]
I think @gunan's solution should work for @aidan-plenert-macdonald . Another alternative is to simply run `docker run` without the `--rm` flag and then restart the container with `docker start -i` later. So I'll close the issue for now. Feel free to comment or reopen the issue in case you have more questions.
