### ISSUE TITLE
Tensorflow GPU on Windows Python 3.5 CUDA_ERROR_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by vladimircape** [tensorflow/tensorflow#7399]
I am working on

    Notebook Lenova Z50-70
    GPU:Nvidia Geforce 840M
    Python 3.5
    Windows 7
    pip install tensorflow-gpu

I open windows and try to test how tensorflow use GPU.

    import tensorflow as tf
>>> I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA libr
ary cublas64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA libr
ary cudnn64_5.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA libr
ary cufft64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA libr
ary nvcuda.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA libr
ary curand64_80.dll locally

    from __future__ import print_function
    gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)
    sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))

>>>I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:885] Found device 0 with p
roperties:
name: GeForce 840M
major: 5 minor: 0 memoryClockRate (GHz) 1.124
pciBusID 0000:03:00.0
Total memory: 4.00GiB
Free memory: 3.93GiB
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0: Y
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow d
evice (/gpu:0) -> (device: 0, name: GeForce 840M, pci bus id: 0000:03:00.0)
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_driver.cc:1002] failed to allocate 1.3
3G (1430223872 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_driver.cc:1002] failed to allocate 1.2
0G (1287201536 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_driver.cc:1002] failed to allocate 1.0
8G (1158481408 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_driver.cc:1002] failed to allocate 994
.33M (1042633216 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_driver.cc:1002] failed to allocate 894
.90M (938370048 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_driver.cc:1002] failed to allocate 805
.41M (844532992 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_driver.cc:1002] failed to allocate 724
.87M (760079872 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_driver.cc:1002] failed to allocate 652
.38M (684071936 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_driver.cc:1002] failed to allocate 587
.14M (615664896 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_driver.cc:1002] failed to allocate 528
.43M (554098432 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_driver.cc:1002] failed to allocate 475
.59M (498688768 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
>>> hello = tf.constant('Hello, TensorFlow!')
>>> print(sess.run(hello))

And got window error that it's not enought memory and OS closed python.
Yes also Gchrome was open and use a lot of system memory.
My question.
Why such error appear, why when i close GChrome system starts to works better, as i understand tensorflow gpu, use gpu memory and my Nvidia Geforce 840M has Dedicated Memory. I also have integrated video IntelHD.
Why tensorflow start to use system resources not gpu resources? and how to fix it? i don't have error in theano framework

**Comment by girving** [comment]
Presumably another process is using more than 0.66 of your GPU memory.  Do you have evidence that this isn't the case?

@mrry: Have you unexpected out-of-GPU-memory issues on Windows?

**Comment by mrry** [comment]
@girving Not that I'm aware of. I don't think this issue is Windows specific.

**Comment by vladimircape** [comment]
I think Gchrome not use GPU memory, because when i closed GChrome, and start use Firefox for Jupiter, everything was ok.
Also i check info, that my tensorflow use GPU dedicated memory and it's ok, but not use GPU processor, and use CPU processor, is it normal?

**Comment by girving** [comment]
I think this is better as a StackOverflow question, since it's not at all clear it's a TensorFlow bug.

**Comment by Carmezim** [comment]
@vladimircape you could use nvidia-smi to check where is your GPU memory going for.
