### ISSUE TITLE
Resolving MKL-DNN Compilation Error in TensorFlow on RISC-V Architecture

### ISSUE THREAD

**Issue by helloworld-star** [tensorflow/tensorflow#74015]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.12.1

### Custom code

Yes

### OS platform and distribution

OpenEuler24.03

### Python version

3.11.6

### Bazel version

5.3.0

### GCC/compiler version

12.3.1

### Current behavior?

According to the information gathered, mkl_dnn_v1 is Intel's acceleration library, and it should be disabled when compiling on the RISC-V architecture. The TensorFlow manual indicates that the MKL acceleration library should be enabled by setting --config=mkl. However, this option was not set during compilation, but the output indicates that the library still entered the compilation process.

The compile command:
bazel --output_user_root=`pwd`/../output_user_root build  --subcommands --host_copt=-Wno-stringop-truncation //tensorflow/tools/pip_package:build_pip_package --verbose_failures --experimental_local_memory_estimate --jobs=16

### Standalone code to reproduce the issue

```shell
https://build.tarsier-infra.isrc.ac.cn/package/show/home:Kaguya/tensorflow-gitee
```

### Relevant log output

```shell
external/mkl_dnn_v1/src/cpu/x64/rnn/brgemm_cell_common_bwd.cpp:102:37: error: 'const struct dnnl::impl::cpu::rnn_utils::diff_src_brgemm_conf_t' has no member named 'isa'
102 | && rnn_.diff_src_brgemm.isa == x64::avx512_core_bf16_amx_bf16) {
| ^~~
```

**Comment by Venkat6871** [comment]
Hi **@helloworld-star** ,
- Is there any specific reason for using TensorFlow 2.12.1? We are suggesting to use latest version(2.17.0) is for better results. Please upgrade your version and let us know whether the issue persists with recent TF versions.
Thank you!
