### ISSUE TITLE
Xcode fails to build tensorflow-lite due to kleidia error

### ISSUE THREAD

**Issue by pierreguillot** [tensorflow/tensorflow#74057]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

After 2.17.0 - master branch (52be72f)

### Custom code

Yes

### OS platform and distribution

macOS 14.4.1 & macOS 14.6.1

### GCC/compiler version

AppleClang 15.0.0.15000309

### Current behavior?

Compiling with Xcode, generates the error while compiling tensorflow-lite:
```
[kleidiai] Compiling kai_matmul_clamp_f16_f16_f16p16x1biasf16_6x16x8_neon_mla.c
Error: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'unsigned int' [-Werror,-Wshorten-64-to-32]
    unsigned int string_length = k;
```
because `size_t != unsigned int`.

[Here is the full log](https://github.com/Ircam-Partiels/basic-pitch-vamp-plugin/actions/runs/10453547929/job/28944319091?pr=9#step:6:249) in Github Action.

KleidiAI seems to be included by XNNPACK. 
I use CMake to generate the project. Defining `set(XNNPACK_ENABLE_KLEIDIAI OFF)` solves the problem, but I suppose either this needs to be fixed directly in KleidAI or XNNPACK (or tensorflow) needs to ensure that KleidAI is not used. 

### Standalone code to reproduce the issue

```shell
This branch on my opensource project: https://github.com/Ircam-Partiels/basic-pitch-vamp-plugin/tree/dependabot/submodules/tensorflow-acc45fe
```

### Relevant log output

```shell
https://github.com/Ircam-Partiels/basic-pitch-vamp-plugin/actions/runs/10453547929/job/28944319091?pr=9#step:6:249
```

**Comment by pkgoogle** [comment]
Hi @pierreguillot, can you provide more detail on reproduce steps? Like what should I do w/ your branch (which I can't seem to access, just FYI). What commands do you run? Thanks.
