### ISSUE TITLE
Cannot achieve the reported accuracy 0.844 with wide_n_deep_tutorial

### ISSUE THREAD

**Issue by Sean-Git** [tensorflow/tensorflow#7408]
After running the code in "wide_n_deep_tutorial.py", I achieved accuracy 0.834 for wide-only model, but the achieved accuracy for wide-and-deep model was only about 0.82.

I didn't change anything in the source code and just couldn't achieve the accuracy 0.844 as reported on the website. Can anyone help me to tell where could sth be wrong?

**Comment by girving** [comment]
@ispirmustafa Is that within noise?

**Comment by whatbeg** [comment]
@Sean-Git I tried that and I get about 84.7% accuracy when train steps = 200, and increase train steps to 800, 1000, or larger, it even can up to 85.5%. so, I think you might check your code and ensure there are no modifications on key code.

**Comment by ispirmustafa** [comment]
closing based on answer from @whatbeg
