### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.tfprof' has no attribute 'model_analyzer'

### ISSUE THREAD

**Issue by linrio** [tensorflow/tensorflow#7412]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Win10

The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. 0.12.1

### What other attempted solutions have you tried?
I installed tensorflow on Win10 platform. The version is 0.12.1. I tried to run the model zoo's example: resnet:
`python ./resnet/resnet_main.py`
It occured the error:

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
```
"D:\Program Files (x86)\Miniconda3\python.exe" G:/codes/tensorflow/models-master/resnet/resnet_main.py
Traceback (most recent call last):
  File "G:/codes/tensorflow/models-master/resnet/resnet_main.py", line 210, in <module>
    tf.app.run()
  File "D:\Program Files (x86)\Miniconda3\lib\site-packages\tensorflow\python\platform\app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "G:/codes/tensorflow/models-master/resnet/resnet_main.py", line 204, in main
    train(hps)
  File "G:/codes/tensorflow/models-master/resnet/resnet_main.py", line 57, in train
    param_stats = tf.contrib.tfprof.model_analyzer.print_model_analysis(
AttributeError: module 'tensorflow.contrib.tfprof' has no attribute 'model_analyzer'
```

**Comment by panyx0718** [comment]
It actually appears in my 0.12.0-rc1. Do you mind upgrading to 1.0?

python -c "import tensorflow; print(tensorflow.__version__)"
0.12.0-rc1

>>> print tensorflow.contrib.tfprof.model_analyzer.print_model_analysis
<function print_model_analysis at 0x7fe5949d4b18>

**Comment by panyx0718** [comment]
Found this: https://github.com/tensorflow/tensorflow/issues/6731
It seems the packages under tf.contrib is currently missing for Windows

**Comment by linrio** [comment]
Thanks! No, I have not upgrated to 1.0. When the packages will supplement?

**Comment by vikas95** [comment]
It is still not available for windows. Can anyone suggest alternatives to deal with this error:
"module 'tensorflow.contrib.tfprof' has no attribute 'model_analyzer'"

**Comment by panyx0718** [comment]
@jart Any updates?

**Comment by ybsave** [comment]
@jart Co-Ask? Will this problem in Windows been solved soon?

**Comment by jart** [comment]
Thank you for your patience. We've only recently introduced Windows support. Bringing contrib support to Windows is something we're still working to accomplish. Please follow #6791 for updates.

**Comment by testote** [comment]
Same error, however,

/usr/lib/python3.6/site-packages/tensorflow_core/python/profiler/model_analyzer.py
/usr/lib/python3.6/site-packages/tensorflow_core/contrib/slim/python/slim/model_analyzer.py
/usr/lib/python3.6/site-packages/tensorflow_core/contrib/tfprof/model_analyzer.py
/usr/lib/python3.6/site-packages/tensorflow/python/profiler/model_analyzer.py
/usr/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/model_analyzer.py
/usr/lib/python3.6/site-packages/tensorflow/contrib/tfprof/model_analyzer.py
