### ISSUE TITLE
Bazel build fails on SUSE Enterprise due to too many open files

### ISSUE THREAD

**Issue by themightyoarfish** [tensorflow/tensorflow#7416]
This could also be a bazel issue, I don't know.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
None

### Environment info
Operating System: SUSE Linux Enterprise Server 12 SP1

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
$ ls /usr/local/cuda/lib/libcuda*
/usr/local/cuda/lib/libcudadevrt.a  /usr/local/cuda/lib/libcudart.so.7.0     /usr/local/cuda/lib/libcudart_static.a
/usr/local/cuda/lib/libcudart.so    /usr/local/cuda/lib/libcudart.so.7.0.28
$ ls ~/.local/lib64/libcudnn*
/home/student/r/rdiederichse/.local/lib64/libcudnn.so    /home/student/r/rdiederichse/.local/lib64/libcudnn.so.4.0.7
/home/student/r/rdiederichse/.local/lib64/libcudnn.so.4  /home/student/r/rdiederichse/.local/lib64/libcudnn_static.a
```
If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`): `d86cadcdf03ae6fef63f34c90150a4518a121de8`
2. The output of `bazel version`
```
Warning: ignoring http_proxy in environment.
Build label: 0.4.4- (@non-git)
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Feb 10 14:39:20 2017 (1486737560)
Build timestamp: 1486737560
Build timestamp as int: 1486737560
```

The error I get when  running `bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package` is (after some time)
```
ERROR: /home/student/r/rdiederichse/.cache/bazel/_bazel_rdiederichse/e5cce820cc082410b4fcc604db349066/external/jpeg/BUILD:37:1: C++ compilation of rule '@jpeg//:jpeg' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 33 argument(s) skipped): java.io.IOException: Cannot run program "/home/student/r/rdiederichse/.cache/bazel/_bazel_rdiederichse/e5cce820cc082410b4fcc604db349066/execroot/tensorflow/_bin/process-wrapper" (in directory "/home/student/r/rdiederichse/.cache/bazel/_bazel_rdiederichse/e5cce820cc082410b4fcc604db349066/execroot/tensorflow"): error=24, Too many open files.
```

**Comment by girving** [comment]
@damienmg Have you seen this before?  `Too many open files` during the build is odd.

**Comment by themightyoarfish** [comment]
The limit as given by `ulimit -n` is 1024 btw.

**Comment by damienmg** [comment]
Yes we have seen that on OS X with high number of --jobs, try forcefully setting --jobs to the number of cores.

**Comment by girving** [comment]
Closing here since this seems to be a Bazel issue, and not TensorFlow specific.  @damienmg Is it worth filing a Bazel bug, or is this impractical to fix?

**Comment by damienmg** [comment]
We already have a bug for that :( Our resource estimation is quite wrong
unfortunately (and even it was right, we would still have those issue on
some edge case systems).
