### ISSUE TITLE
no match for 'operator<<' (operand types are 'std::ostream' {aka 'std::basic_ostream<char>'} and 'const std::unique_ptr<tensorflow::data::TaskIterator>')

### ISSUE THREAD

**Issue by iysheng** [tensorflow/tensorflow#74289]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.12.0

### Custom code

No

### OS platform and distribution

Linux Fedora 38

### Python version

3.11

### Bazel version

5.3.0

### GCC/compiler version

gcc version 13.3.1 20240614 (Arm GNU Toolchain 13.3.Rel1 (Build arm-13.24))

### Current behavior?

When I cross compile (target is aarch64) build tensorflow from source, I config my own cross compile tool downloaded from ARM website gcc version 13.3.1 20240614 (Arm GNU Toolchain 13.3.Rel1 (Build arm-13.24)). when I build I got these errors like log.
[err4tensorflow.log](https://github.com/user-attachments/files/16703640/err4tensorflow.log)

### Standalone code to reproduce the issue

```shell
when I use the cross compile tool to build from source, I get these errors like in logs.
```

**Comment by iysheng** [comment]
based on the comment in file ``tensorflow/tsl/platform/default/logging.h`` as below. Now I can build tensorflow.sop success.
![image](https://github.com/user-attachments/assets/7a591633-d9c2-4e89-8122-bcb9d465cb5e)

**Comment by tilakrayal** [comment]
@iysheng,
Tensorflow v2.12 is an older version, which we have limited support for. Could you please try to check with the latest tensorflow v2.17 & provide the update and also please provide the steps followed. Thank you!

**Comment by iysheng** [comment]
> @iysheng, Tensorflow v2.12 is an older version, which we have limited support for. Could you please try to check with the latest tensorflow v2.17 & provide the update and also please provide the steps followed. Thank you!

I found this pic as:
![image](https://github.com/user-attachments/assets/34d04289-1c53-4fca-b6d4-6b0a55600ec7)
 tensorflow v2.12 is the final version test with gcc compiler. can the new  tensorflow verison like v2.17 builed with gcc tool?

**Comment by tilakrayal** [comment]
@iysheng,
Apologies for the delay. Yeah from the tensorflow v2.13, the compiler has been moved to GCC to CLang as mentioned in the official document.
https://www.tensorflow.org/install/source#cpu

**Comment by iysheng** [comment]
> @iysheng, Apologies for the delay. Yeah from the tensorflow v2.13, the compiler has been moved to GCC to CLang as mentioned in the official document. https://www.tensorflow.org/install/source#cpu

This issue can be closed as I use CHECK(val1 != val2) instead.
