### ISSUE TITLE
Where is conv2d implemented?

### ISSUE THREAD

**Issue by daothanhtuan** [tensorflow/tensorflow#743]
I have been looking for the code of tf.nn.conv2d(...), so I looked in the directory tensorflow/python/ops/nn.py and the only things I found is 
"depthwise_conv2d"
AND
"separable_conv2d"
Can someone point me to the location of conv2d?

**Comment by yaroslavvb** [comment]
Look for something like this
REGISTER_KERNEL_BUILDER(Name("Conv2D")
                            .Device(DEVICE_CPU)
                            .TypeConstraint<float>("T"),
                        Conv2DOp<CPUDevice, float>);

hence, search for "Conv2DOp" to see the implementation

**Comment by daothanhtuan** [comment]
Found it, thank you very much.
