### ISSUE TITLE
callbacks.ModelCheckpoint require the checkpoint file path end in  .weights.h5.  But tf.train.latest_checkpoint can't find any checkpoint

### ISSUE THREAD

**Issue by MeowTheCat** [tensorflow/tensorflow#74342]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf-nightly and tf 2.17

### Custom code

Yes

### OS platform and distribution

Ubuntu 18.04.6 LTS

### Python version

3.10

### Current behavior?

the code runs perfectly well in tf 2.11
However, in tf2.17 and tf-nightly,  I got error:
ValueError: When using `save_weights_only=True` in `ModelCheckpoint`, the filepath provided must end in `.weights.h5` (Keras weights format). Received: filepath=cp-{epoch}

If I save them as .weights.h5, they can't be recognized by tf.train.latest_checkpoint()

### Standalone code to reproduce the issue

```shell
import numpy as np

import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model


# Define the model using the Functional API
x = tf.keras.Input(shape=(20,), dtype=tf.float32)
y = tf.keras.Input(shape=(), dtype=tf.float32)
tmp = Dense(64, activation='relu')(x)
outputs = Dense(1, activation='sigmoid')(tmp)


class DummyLossLayer(tf.keras.layers.Layer):
    def call(self, *x):
        self.add_loss(tf.keras.losses.BinaryCrossentropy(from_logits=True)(*x))
        return x

outputs, _ = DummyLossLayer()(outputs, y)
model = Model(inputs=[x, y], outputs=outputs)


# Compile the model with the custom metric
model.compile(optimizer='adam')

cp_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath="cp-{epoch}",
    verbose=1,
    save_weights_only=True,
    save_freq='epoch')


# Dummy data for demonstration
x_train = np.random.random((1000, 20))
y_train = np.random.randint(2, size=(1000,)).astype(np.float32)

# Train the model
model.fit([x_train, y_train], epochs=2, batch_size=32, callbacks=[cp_callback])
```

**Comment by tilakrayal** [comment]
@MeowTheCat,
Tensorflow 2.17 contains the keras3.0. In Keras 3, for checkpoint filepath, you need to provide in .keras format only, if you're saving only weights file name should end with .weights.h5.

You can save and load the model in .h5 using the method below
https://keras.io/guides/migrating_to_keras_3/#saving-a-model-in-the-tf-savedmodel-format

https://github.com/keras-team/keras-io/issues/1844

Thank you!

**Comment by MeowTheCat** [comment]
@tilakrayal for some reason I have to save weights only and use .weights.h5. Are you suggesting tf.train.latest_checkpoint won't work with .weights.h5 ?

**Comment by sanskarmodi8** [comment]
@MeowTheCat,

I was looking into this issue and found that the function tf.train.latest_checkpoint() is designed to work with TensorFlow's native checkpoint format. 

In TF, checkpoints typically consist of multiple files, including a checkpoint file that keeps track of the latest checkpoints and .index files that describe the state of the model.

Instead of using latest_checkpoint() you can follow an alternative custom approach like one given below.

https://colab.research.google.com/drive/1wlVOo4Av-xo_AHZTK3aurKtu1f8JCi-I?usp=sharing
