### ISSUE TITLE
While importing Tensorflow on CPU , a dynamic link library (DLL) initialization routine failed

### ISSUE THREAD

**Issue by SamamaSaleem** [tensorflow/tensorflow#74405]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.10

### Custom code

No

### OS platform and distribution

Windows 10 x64

### Python version

3.10

### Current behavior?

Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Samama>conda env list
# conda environments:
#
base                     C:\Users\Samama\anaconda3
myenv                    C:\Users\Samama\anaconda3\envs\myenv

C:\Users\Samama>conda activate myenv

(myenv) C:\Users\Samama>conda list
# packages in environment at C:\Users\Samama\anaconda3\envs\myenv:
#
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                       mkl
abseil-cpp                20211102.0           hd77b12b_0
absl-py                   2.1.0           py310haa95532_0
aiohttp                   3.9.5           py310h2bbff1b_0
aiosignal                 1.2.0              pyhd3eb1b0_0
astunparse                1.6.3                      py_0
async-timeout             4.0.3           py310haa95532_0
attrs                     23.1.0          py310haa95532_0
blas                      1.0                         mkl
blinker                   1.6.2           py310haa95532_0
brotli-python             1.0.9           py310hd77b12b_8
bzip2                     1.0.8                h2bbff1b_6
c-ares                    1.19.1               h2bbff1b_0
ca-certificates           2024.7.2             haa95532_0
cachetools                5.3.3           py310haa95532_0
certifi                   2024.7.4        py310haa95532_0
cffi                      1.16.0          py310h2bbff1b_1
charset-normalizer        3.3.2              pyhd3eb1b0_0
click                     8.1.7           py310haa95532_0
colorama                  0.4.6           py310haa95532_0
cryptography              41.0.3          py310h3438e0d_0
flatbuffers               2.0.0                h6c2663c_0
frozenlist                1.4.0           py310h2bbff1b_0
gast                      0.4.0              pyhd3eb1b0_0
giflib                    5.2.1                h8cc25b3_3
google-auth               2.29.0          py310haa95532_0
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0
google-pasta              0.2.0              pyhd3eb1b0_0
grpc-cpp                  1.48.2               hf108199_0
grpcio                    1.48.2          py310hf108199_0
h5py                      3.11.0          py310hed405ee_0
hdf5                      1.12.1               h51c971a_3
icc_rt                    2022.1.0             h6049295_2
icu                       58.2                 ha925a31_3
idna                      3.7             py310haa95532_0
intel-openmp              2023.1.0         h59b6b97_46320
jpeg                      9e                   h827c3e9_3
keras                     2.10.0          py310haa95532_0
keras-preprocessing       1.1.2              pyhd3eb1b0_0
libcurl                   8.7.1                h86230a5_0
libffi                    3.4.4                hd77b12b_1
libpng                    1.6.39               h8cc25b3_0
libprotobuf               3.20.3               h23ce68f_0
libssh2                   1.10.0               hcd4344a_2
markdown                  3.4.1           py310haa95532_0
markupsafe                2.1.3           py310h2bbff1b_0
mkl                       2023.1.0         h6b88ed4_46358
mkl-service               2.4.0           py310h2bbff1b_1
mkl_fft                   1.3.8           py310h2bbff1b_0
mkl_random                1.2.4           py310h59b6b97_0
multidict                 6.0.4           py310h2bbff1b_0
numpy                     1.26.4          py310h055cbcc_0
numpy-base                1.26.4          py310h65a83cf_0
oauthlib                  3.2.2           py310haa95532_0
openssl                   1.1.1w               h2bbff1b_0
opt_einsum                3.3.0              pyhd3eb1b0_1
packaging                 24.1            py310haa95532_0
pip                       24.2            py310haa95532_0
protobuf                  3.20.3          py310hd77b12b_0
pyasn1                    0.4.8              pyhd3eb1b0_0
pyasn1-modules            0.2.8                      py_0
pybind11-abi              5                    hd3eb1b0_0
pycparser                 2.21               pyhd3eb1b0_0
pyjwt                     2.8.0           py310haa95532_0
pyopenssl                 23.2.0          py310haa95532_0
pysocks                   1.7.1           py310haa95532_0
python                    3.10.0               h96c0403_3
python-flatbuffers        24.3.25         py310haa95532_0
re2                       2022.04.01           hd77b12b_0
requests                  2.32.3          py310haa95532_0
requests-oauthlib         2.0.0           py310haa95532_0
rsa                       4.7.2              pyhd3eb1b0_1
scipy                     1.13.1          py310h8640f81_0
setuptools                72.1.0          py310haa95532_0
six                       1.16.0             pyhd3eb1b0_1
snappy                    1.2.1                hcdb6601_0
sqlite                    3.45.3               h2bbff1b_0
tbb                       2021.8.0             h59b6b97_0
tensorboard               2.10.0          py310haa95532_0
tensorboard-data-server   0.6.1           py310haa95532_0
tensorboard-plugin-wit    1.8.1           py310haa95532_0
tensorflow                2.10.0          mkl_py310hd99672f_0
tensorflow-base           2.10.0          mkl_py310h6a7f48e_0
tensorflow-estimator      2.10.0          py310haa95532_0
termcolor                 2.1.0           py310haa95532_0
tk                        8.6.14               h0416ee5_0
typing_extensions         4.11.0          py310haa95532_0
tzdata                    2024a                h04d1e81_0
urllib3                   2.2.2           py310haa95532_0
vc                        14.40                h2eaa2aa_0
vs2015_runtime            14.40.33807          h98bb1dd_0
werkzeug                  3.0.3           py310haa95532_0
wheel                     0.43.0          py310haa95532_0
win_inet_pton             1.1.0           py310haa95532_0
wrapt                     1.14.1          py310h2bbff1b_0
xz                        5.4.6                h8cc25b3_1
yarl                      1.9.3           py310h2bbff1b_0
zlib                      1.2.13               h8cc25b3_1

(myenv) C:\Users\Samama>python
Python 3.10.0 | packaged by conda-forge | (default, Nov 10 2021, 13:20:59) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\Samama\anaconda3\envs\myenv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Samama\anaconda3\envs\myenv\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Samama\anaconda3\envs\myenv\lib\site-packages\tensorflow\python\__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\Users\Samama\anaconda3\envs\myenv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "C:\Users\Samama\anaconda3\envs\myenv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
>>>

### Standalone code to reproduce the issue

```shell
import tensorflow
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:\Users\Samama\anaconda3\envs\myenv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Samama\anaconda3\envs\myenv\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Samama\anaconda3\envs\myenv\lib\site-packages\tensorflow\python\__init__.py", line 36, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\Users\Samama\anaconda3\envs\myenv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 77, in <module>
    raise ImportError(
ImportError: Traceback (most recent call last):
  File "C:\Users\Samama\anaconda3\envs\myenv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors for some common causes and solutions.
If you need help, create an issue at https://github.com/tensorflow/tensorflow/issues and include the entire stack trace above this error message.
```

**Comment by rakshitdabral** [comment]
@SamamaSaleem  what version of Microsoft Visual C++ Redistributable are u using on your system ?

**Comment by rakshitdabral** [comment]
@SamamaSaleem have u tried reinstalling anaconda , i had same issue once and reinstalling anaconda and packages fixed it for me  , this specific one "ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed. "

**Comment by SamamaSaleem** [comment]
> @SamamaSaleem have u tried reinstalling anaconda , i had same issue once and reinstalling anaconda and packages fixed it for me , this specific one "ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed. "

Yes. I tried this numerous times. In fact, I reinstalled Windows, but the issue persists. I tried creating new env, installing Python 3.10 and Tensorflow 2.10. I also set the PATH environmental variable to the Conda's path. No avail. I am not sure is it because of some version compatibility issue or system requirement issue ( as I am installing it on CPU system)

**Comment by rakshitdabral** [comment]
@SamamaSaleem maybe  the issue is with protobuf, can you  tell me the verison of protobuf you are using ? and try to downgrade it and then run your code?

**Comment by SamamaSaleem** [comment]
@rakshitdabral I am not using protobuf.

**Comment by rakshitdabral** [comment]
@SamamaSaleem can u try installing protobuf  then? and if it doesnt work try reducing your tensorflow version , i read that reducing tensorflow version help some people for the same issue

**Comment by tilakrayal** [comment]
@SamamaSaleem,
Could you please provide the tensorflow and the compatible version which you are trying to install. Also there are at least 3 possible scenarios:

```python
- You need to install the MSVC 2019 redistributable
- Your CPU does not support AVX2 instructions
- Your CPU/Python is on 32 bits
- There is a library that is in a different location/not installed on your system that cannot be loaded.
```

https://github.com/tensorflow/tensorflow/issues/61887

Thank you!

**Comment by SamamaSaleem** [comment]
@rakshitdabral I tried installing protobuf, and downgrading tensorflow version, but it hasn't resolved the issue

**Comment by SamamaSaleem** [comment]
@tilakrayal -
- I tried Microsoft Visual C++ 2015-2022 Redistributable (x-64) - 14.40.33810
- My CPU/Python is on 64 bits
- I tried to update the PATH variable with the path of the installed libraries.

Unfortunately, the error isn't gone.

**Comment by SamamaSaleem** [comment]
Any way out please?

**Comment by rakshitdabral** [comment]
> Any way out please?

Looking into it , will surely update you if I find something

**Comment by rakshitdabral** [comment]
@SamamaSaleem which  cpu , are you running tensorflow on??

**Comment by rakshitdabral** [comment]
@SamamaSaleem can you try this once

Do the following.

1. Run the anaconda prompt as administrator.(right click-> run as administrator).
2.  pip uninstall tensorflow. 
3. Close anaconda prompt.
4 .Again run anaconda prompt as administrator.
5.type:
 conda install tensorflow
6. It will ask for some y / n
7. Type y.


Now after all done, change your python interpreter's environment to anaconda environment where you installed tensorflow. Now try importing tensorflow.

**Comment by SamamaSaleem** [comment]
@rakshitdabral CPU: Intel (R) Celeron (R) CPU B820 @ 1.70GHz

**Comment by SamamaSaleem** [comment]
Facing this error now:
(base) C:\Windows\system32>conda install tensorflow
Channels:
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: | warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides bleach 1.5.0 needed by tensorboard-1.7.0-py35he025d50_1

Could not solve for environment specs
The following packages are incompatible
├─ pin-1 is installable and it requires
│  └─ python 3.11.* , which can be installed;
└─ tensorflow is not installable because there are no viable options
   ├─ tensorflow [1.10.0|1.9.0] would require
   │  └─ python 3.5.* , which conflicts with any installable versions previously reported;
   ├─ tensorflow [1.10.0|1.11.0|...|2.1.0] would require
   │  └─ python 3.6.* , which conflicts with any installable versions previously reported;
   ├─ tensorflow [1.13.1|1.14.0|...|2.9.1] would require
   │  └─ python 3.7.* , which conflicts with any installable versions previously reported;
   ├─ tensorflow [1.7.0|1.7.1|1.8.0] would require
   │  └─ tensorboard [>=1.7.0,<1.8.0 |>=1.8.0,<1.9.0 ], which requires
   │     └─ bleach 1.5.0 , which does not exist (perhaps a missing channel);
   ├─ tensorflow [2.10.0|2.8.2|2.9.1] would require
   │  └─ python 3.10.* , which conflicts with any installable versions previously reported;
   ├─ tensorflow [2.10.0|2.3.0|...|2.9.1] would require
   │  └─ python 3.8.* , which conflicts with any installable versions previously reported;
   └─ tensorflow [2.10.0|2.5.0|2.6.0|2.8.2|2.9.1] would require
      └─ python 3.9.* , which conflicts with any installable versions previously reported.

**Comment by SamamaSaleem** [comment]
tried by creating a new env with python == 3.10 using the following:
conda create --name myenv python==3.10
and installed the tensorflow==2.10
Though it has been installed, the same error of DLL initialization failed is popped again when importing

**Comment by SamamaSaleem** [comment]
after the complete process, here is the output:
![image](https://github.com/user-attachments/assets/c381ed7e-ccd6-4885-a9c8-ea16efa74ba4)

**Comment by rakshitdabral** [comment]
> @rakshitdabral CPU: Intel (R) Celeron (R) CPU B820 @ 1.70GHz

ok so your cpu do supports AVX

**Comment by rakshitdabral** [comment]
> * nothing provides bleach 1.5.0 needed by tensorboard-1.7.0-py35he025d50_1
> 
> Could not solve for environment specs The following packages are incompatible ├─ pin-1 is installable and it requires │ └─ python 3.11.* , which can be installed; └─ tensorflow is not installable because there are no viable options ├─ tensorflow [1.10.0|1.9.0] would require │ └─ python 3.5.* , which conflicts with any installable versions previously reported; ├─ tensorflow [1.10.0|1.11.0|...|2.1.0] would require │ └─ python 3.6.* , which conflicts with any installable versions previously reported; ├─ tensorflow [1.13.1|1.14.0|...|2.9.1] would require │ └─ python 3.7.* , which conflicts with any installable versions previously reported; ├─ tensorflow [1.7.0|1.7.1|1.8.0] would require │ └─ tensorboard [>=1.7.0,<1.8.0 |>=1.8.0,<1.9.0 ], which requires │ └─ bleach 1.5.0 , which does not exist (perhaps a missing channel); ├─ tensorflow [2.10.0|2.8.2|2.9.1] would require │ └─ python 3.10.* , which conflicts with any installable versions previously reported; ├─ tensorflow [2.10.0|2.3.0|...|2.9.1] would require │ └─ python 3.8.* , which conflicts with any installable versions previously reported; └─ tensorflow [2.10.0|2.5.0|2.6.0|2.8.2|2.9.1] would require └─ python 3.9.* , which conflicts with any installable versions previously reported.



try doing this ,  conda config --add channels conda-forge

**Comment by rakshitdabral** [comment]
@SamamaSaleem can you tell me how you install your packages ?? are you using anaconda terminal or cmd??

**Comment by tilakrayal** [comment]
@SamamaSaleem,
Could you please try to use the latest tensorflow v2.17 and provide whether you are facing a similar issue in the stable version? Thank you!

**Comment by mihaimaruseac** [comment]
Duplicate of #19584. Please do a search before opening new issues. This is a very old issue and manifests because old PCs with Windows cannot load libraries needed by TF because they have very old architecture sets.
