### ISSUE TITLE
How to generate a tflite with a fixed input from a tensorflow saved model with dynamic input?  

### ISSUE THREAD

**Issue by moses574** [tensorflow/tensorflow#74414]
### 1. System information

- OS Platform and Distribution (e.g., Windows 11):
- TensorFlow installation (pip package or built from source):
- TensorFlow library (2.4.0):

### 2. Code

converter = tf.lite.TFLiteConverter.from_saved_model('./model_tf')
converter.allow_custom_ops = True  

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]

tflite_model = converter.convert()

**Comment by gaikwadrahul8** [comment]
Hi, @moses574 

I apologize for delayed response and as far I know to generate TFLite model with a fixed input shape from TensorFlow SavedModel that originally has dynamic input shapes in that case before converting the model you need to define a fixed input shape. This involves creating a TensorFlow model with a fixed input shape and then converting it to TFLite

If you are starting with a model that has dynamic shapes, you will need to modify it to use a fixed shape for the conversion process. You can do this by specifying a fixed input shape by doing something like below, I tried in google colab with sample `ssd_mobilenet_v1` model and its seems like working as expected so could you please try from your end and let me know is it working as expected or Am I missing something here ?

Here is Google colab [gist-file](https://colab.sandbox.google.com/gist/gaikwadrahul8/7c7f011f93304b23ca13866c0eb64d06/issue-74414.ipynb) for reference and I followed the exact same steps mentioned below :

```
!wget http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz
!tar -xzvf "/content/ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz" -C "/content/"

model = tf.saved_model.load('/content/ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03/saved_model')
concrete_func = model.signatures[
tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
concrete_func.inputs[0].set_shape([1, 300, 300, 3])

converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]

tflite_model = converter.convert()

with open('detect.tflite', 'wb') as f:
  f.write(tflite_model)
```

Thank you for your cooperation and patience.
