### ISSUE TITLE
tfprof model analyzer ignores scalar parameters

### ISSUE THREAD

**Issue by taion** [tensorflow/tensorflow#7444]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
Searched issues for "tfprof"

### Environment info
gcr.io/tensorflow/tensorflow:1.0.0-rc2-devel-gpu

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
```python
import tensorflow as tf

sess = tf.InteractiveSession()
v = tf.Variable(0., dtype=tf.float32, trainable=True)

tf.contrib.tfprof.model_analyzer.print_model_analysis(tf.get_default_graph())
```

This will show `total_parameters` of `0`, despite there being a parameter.

### What other attempted solutions have you tried?
N/A

### Logs or other output that would be helpful
```
name: "_TFProfRoot"
exec_micros: 0
requested_bytes: 0
total_exec_micros: 0
total_requested_bytes: 0
total_parameters: 0
children {
  name: "Variable"
  exec_micros: 0
  requested_bytes: 0
  total_exec_micros: 0
  total_requested_bytes: 0
  total_parameters: 0
  float_ops: 0
  total_float_ops: 0
}
float_ops: 0
total_float_ops: 0
```

I believe this is coming from the logic here: https://github.com/tensorflow/tensorflow/blob/v1.0.0-rc2/tensorflow/tools/tfprof/internal/tfprof_show.cc#L37 which skips nodes with empty shapes, which includes scalars.

**Comment by yaroslavvb** [comment]
@petewarden does tfprof maintainer have github username? tensorflow/tensorflow/tools/tfprof/

**Comment by petewarden** [comment]
I believe it's @panyx0718, but I'm not certain.

**Comment by panyx0718** [comment]
Let me look into it

**Comment by panyx0718** [comment]
A fix has been submitted. Will be available in next release

**Comment by panyx0718** [comment]
Fixed #7444

**Comment by taion** [comment]
Cool – should we close this issue then, or does that typically wait until the change lands in the public GH repo?

**Comment by panyx0718** [comment]
I would suggest you wait until the release. It would be great if you can further verify the fix. Thanks!

**Comment by yaroslavvb** [comment]
@panyx0718 related issue: http://stackoverflow.com/questions/42309202/profiling-tensorflow-using-tfprof (sorry, I'd  cc you on email but couldn't find it)

**Comment by taion** [comment]
Confirmed this was fixed by https://github.com/tensorflow/tensorflow/commit/1849946c09ad93bc2e4f49c658049223e1efe908
