### ISSUE TITLE
Android Example TF Detect crashes when built with files in source directory

### ISSUE THREAD

**Issue by AdamWP** [tensorflow/tensorflow#7446]
Android TF Detect crashes when I make the apk with inception_5 and mobile_multibox files in the assets directory and removed in BUILD as per the instructions at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android

It works when built with automatic download. 

I commented out lines 66 & 67 in BUILD.
 "@inception5h//:model_files",
 "@mobile_multibox//:model_files",

The file size of the apk built with the files added to assets manually is 4195 bytes smaller than the apk built with automatically downloaded files.

**Comment by andrewharp** [comment]
What is the actual message for the crash? (Use adb logcat)

If you run unzip -v on the apk, do the contents look the same with either method? You probably have an extra layer of directories in there or something similar.

**Comment by AdamWP** [comment]
I tracked down the issue.  The difference between builds is the automatic download version gets https://storage.googleapis.com/download.tensorflow.org/models/mobile_multibox_v1a.zip while the instructions at https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android specify to download https://storage.googleapis.com/download.tensorflow.org/models/mobile_multibox_v1.zip . (notice the "a" in the file name).  

One file contains multibox_location_priors.pb while the other has multibox_location_priors.txt.
