### ISSUE TITLE
android demo app: tf_detect using  yolo instead of multibox_detect

### ISSUE THREAD

**Issue by kaishijeng** [tensorflow/tensorflow#7450]
Does anyone know how to build android demo app which uses yolo detector instead of multibox detector ?

Thanks,,

**Comment by andrewharp** [comment]
You need to add the graph to assets/ and flip the boolean USE_YOLO to true. There are instructions here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/DetectorActivity.java#L65

Closing as there is nothing actionable here; for further TF usage queries please try on StackOverflow.

**Comment by chenweiqian** [comment]
@kaishijeng  hi，are you successful？
