### ISSUE TITLE
Bugs in TensorFlowYoloDetector

### ISSUE THREAD

**Issue by AndreyRub** [tensorflow/tensorflow#7452]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
None

### Environment info
Operating System: Windows 10

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
099ef38a99d069b9a1f6d09a289b2df69eaee276
2. The output of `bazel version`
Build label: 0.4.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 7 18:47:13 2016 (1481136433)
Build timestamp: 1481136433
Build timestamp as int: 1481136433

----
It looks like there are bugs in [TensorfFlowYoloDetector](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowYoloDetector.java).

1. **The confidence calculation is broken**
In line 218: 

` final float confidence = output[offset + 4];`

Should be 

` final float confidence = expit( output[offset + 4] );`

You can see line 42 at [DarkFlow file](https://github.com/thtrieu/darkflow/blob/master/net/yolov2/test.py)

2. **The RGB values might be read as BGR in line 152:**
```
    for (int i = 0; i < intValues.length; ++i) {
      floatValues[i * 3 + 0] = (intValues[i] & 0xFF) / 255.0f;
      floatValues[i * 3 + 1] = ((intValues[i] >> 8) & 0xFF) / 255.0f;
      floatValues[i * 3 + 2] = ((intValues[i] >> 16) & 0xFF) / 255.0f;
    }
```

Unless there is a bug in DarkFlow, in order to have the same results, one must change to:
```
    for (int i = 0; i < intValues.length; ++i) {
      floatValues[i * 3 + 2] = (intValues[i] & 0xFF) / 255.0f;
      floatValues[i * 3 + 1] = ((intValues[i] >> 8) & 0xFF) / 255.0f;
      floatValues[i * 3 + 0] = ((intValues[i] >> 16) & 0xFF) / 255.0f;
    }
```

3. **The NMS calculation is completely different from DarkFlow and DarkNet**
See line 242, it just return top K results, without any non-maximum suppression

Here is the code from the file:
```
    final ArrayList<Recognition> recognitions = new ArrayList<Recognition>();
    for (int i = 0; i < Math.min(pq.size(), MAX_RESULTS); ++i) {
      recognitions.add(pq.poll());
    }
```

Here is the correct code from [DarkFlow, line 52](https://github.com/thtrieu/darkflow/blob/master/net/yolov2/test.py):
```
	# non max suppress boxes
	for c in range(C):
		for i in range(len(boxes)):
			boxes[i].class_num = c
		boxes = sorted(boxes, key = prob_compare)
		for i in range(len(boxes)):
			boxi = boxes[i]
			if boxi.probs[c] == 0: continue
			for j in range(i + 1, len(boxes)):
				boxj = boxes[j]
				if box_iou(boxi, boxj) >= .4:
					boxes[j].probs[c] = 0.
```

**Comment by yaroslavvb** [comment]
cc @andrewharp

**Comment by andrewharp** [comment]
@AndreyRub Thanks for the catches! I had not known what to expect from the tiny YOLO graph, so I just chalked any performance issues up to it being much smaller than the regular graph. Fix incoming.

Re: #3, the non-max suppression is performed in DetectorActivity using the same logic as the default MultiBox detector.
