### ISSUE TITLE
Tensorflow value error when setting up training_data

### ISSUE THREAD

**Issue by zaqari** [tensorflow/tensorflow#7455]
Hey, I'm trying to feed a csv to tf.contrib.learn and running into a ValueError over and over again. Here's my code for the training_set variable, plus the ensuing error:

training_set = tf.contrib.learn.datasets.base.load_csv_with_header(
	filename = MET_TRAINING,
	target_dtype = np.float,
	features_dtype = np.str)
Traceback (most recent call last):
  File "<pyshell#15>", line 4, in <module>
    features_dtype = np.str)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 48, in load_csv_with_header
    n_samples = int(header[0])
ValueError: invalid literal for int() with base 10: 'conflict'

The .csv file contains mostly strings, but post training I'd like tf to give me either a '0' or '1' depending on the category an text example ought to fall in. Suggestions on what to do from here?

**Comment by bxshi** [comment]
Not sure if I understand your question, but this may more suitable for a SO question instead of an issue.

Seems you are trying to convert the text string `conflict` to an integer. You may want to write your own parser instead of simply using the `int()` function since you said you will have categorical values. 

Do something like `n_samples = 0 if header[0] == 'conflict' else 1`.

**Comment by aselle** [comment]
You need to have a line in your csv that has # of features and # of samples. Go see the source code.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/datasets/base.py#L48

Arguably that function is not greatly documented. There is also another variant that doesn't expect that header (see the function directly below). That being said, contrib is not officially supported. Asking on StackOverflow would be a great thing here, because then it will be documented for future users. Thanks!

**Comment by Deepakchawla** [comment]
@zaqari I am also getting the same issue can you please suggest me some solution of it...??

**Comment by zaqari** [comment]
Hey @Deepakchawla ! This was a while back, and I don't remember precisely what I did to fix it, but one of the things I did was to make sure that the values in my labels column were all int() by adding the the following single line after setting up the pandas dataframes for my test and train data. Assume you have to do this for both of them:

df['label']=df['label'].astype(int)

That worked like a charm.

**Comment by Deepakchawla** [comment]
Actually, I used below code to split the data

`from sklearn.cross_validation import train_test_split
import pandas as pd

dataset = pd.read_excel('Iris.xls')

train, test = train_test_split(dataset, test_size = 0.2)
train.to_csv("train.xls", index=False, index_label=False, header=True)
test.to_csv("test.xls", index=False, index_label=False, header=True)

print (train.data)`

and this is to load the data

`import tensorflow as tf
import numpy as np
from tensorflow.contrib.learn.python.learn.datasets import base

# Data files
IRIS_TRAINING = "iris_training.xls"
IRIS_TEST = "iris_test.xls"

# Load datasets.
training_set = base.load_csv_with_header(filename=IRIS_TRAINING,features_dtype=np.float32,target_dtype=np.float32)
test_set = base.load_csv_with_header(filename=IRIS_TEST,features_dtype=np.float32,target_dtype=np.float32)

print(training_set.data)
print(training_set.target)`

Now can you tell where I am doing the mistake.

**Comment by zaqari** [comment]
Hmm. I usually just load all of my data in via pandas as opposed to using the functions provided by tensorflow. However, looking at what you just shot me, I think the problem is in the target_dtype value--you have it set for np.float32 where you want it as np.int16 or np.int64 

Try changing that and see what happens!

**Comment by Deepakchawla** [comment]
When I gave int16 or int32 then it will show me below error:
`Traceback (most recent call last):
  File "LoadData.py", line 10, in <module>
    training_set = base.load_csv_with_header(filename=IRIS_TRAINING,features_dtype=np.float32,target_dtype=int32)
NameError: name 'int32' is not defined`
but when I changed to it in int then it will give something like this..
`Traceback (most recent call last):
  File "LoadData.py", line 10, in <module>
    training_set = base.load_csv_with_header(filename=IRIS_TRAINING,features_dtype=np.float32,target_dtype=np.int)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 48, in load_csv_with_header
    n_samples = int(header[0])
ValueError: invalid literal for int() with base 10: '5.6'`

I think the data which I am loading which is saved in csv file it is taking as a string which is not acceptable in load_csv_with_header function of tensor flow.
