### ISSUE TITLE
Add aliases to make layer names more consistent?

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tensorflow#7461]
In the new [layers API](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/layers.py) the convolutional layers have short names (conv1d, conv3d, etc.) while the pooling layers have full names (max_pooling1d, average_pooling3d, etc.) which seems inconsistent. tf.contrib.layers had aliases. Could something like that be added in to the core layers too?

E.g.
```
max_pool1d = max_pooling1d
convolution1d = conv1d
```
and so on.

**Comment by carlthome** [comment]
Or preferably just settle on a naming convention (full names) instead, and never shorten it.

**Comment by yaroslavvb** [comment]
cc @fchollet who added that file

**Comment by fchollet** [comment]
Both full names and short aliases are valid. E.g. https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/pooling.py#L613

Not all of these aliases are currently publicly exposed, but they will soon be.

**Comment by carlthome** [comment]
Sweet. :+1:
