### ISSUE TITLE
Library not loaded: @rpath/libcudart.8.0.dylib

### ISSUE THREAD

**Issue by clizarralde** [tensorflow/tensorflow#7465]
Hi! Tensorflow is not properlly installed. 

Here's the output of: python -c "import tensorflow; print(tensorflow.__version__)"

dyld: warning, LC_RPATH $ORIGIN/../../_solib_darwin/_U@local_Uconfig_Ucuda_S_Scuda_Ccudart___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Slib in /Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH ../local_config_cuda/cuda/lib in /Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so being ignored in restricted program because it is a relative path
dyld: warning, LC_RPATH ../local_config_cuda/cuda/extras/CUPTI/lib in /Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so being ignored in restricted program because it is a relative path
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Library/Python/2.7/site-packages/tensorflow/python/__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Library/Python/2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Library/Python/2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: dlopen(/Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.8.0.dylib
  Referenced from: /Library/Python/2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found

OS: OSX 10.11.6 
Tensorflow pip version: tensorflow-gpu==0.12.1

My "cuda" libs under /usr/local/cuda/lib/* 

/usr/local/cuda/lib/libcublas.8.0.dylib		/usr/local/cuda/lib/libcusparse.8.0.dylib	/usr/local/cuda/lib/libnppim.8.0.dylib
/usr/local/cuda/lib/libcublas.dylib		/usr/local/cuda/lib/libcusparse.dylib		/usr/local/cuda/lib/libnppim.dylib
/usr/local/cuda/lib/libcublas_device.a		/usr/local/cuda/lib/libcusparse_static.a	/usr/local/cuda/lib/libnppim_static.a
/usr/local/cuda/lib/libcublas_static.a		/usr/local/cuda/lib/libnppc.8.0.dylib		/usr/local/cuda/lib/libnppist.8.0.dylib
/usr/local/cuda/lib/libcuda.dylib		/usr/local/cuda/lib/libnppc.dylib		/usr/local/cuda/lib/libnppist.dylib
/usr/local/cuda/lib/libcudadevrt.a		/usr/local/cuda/lib/libnppc_static.a		/usr/local/cuda/lib/libnppist_static.a
/usr/local/cuda/lib/libcudart.8.0.dylib		/usr/local/cuda/lib/libnppi.8.0.dylib		/usr/local/cuda/lib/libnppisu.8.0.dylib
/usr/local/cuda/lib/libcudart.dylib		/usr/local/cuda/lib/libnppi.dylib		/usr/local/cuda/lib/libnppisu.dylib
/usr/local/cuda/lib/libcudart_static.a		/usr/local/cuda/lib/libnppi_static.a		/usr/local/cuda/lib/libnppisu_static.a
/usr/local/cuda/lib/libcudnn.5.dylib		/usr/local/cuda/lib/libnppial.8.0.dylib		/usr/local/cuda/lib/libnppitc.8.0.dylib
/usr/local/cuda/lib/libcudnn.dylib		/usr/local/cuda/lib/libnppial.dylib		/usr/local/cuda/lib/libnppitc.dylib
/usr/local/cuda/lib/libcudnn_static.a		/usr/local/cuda/lib/libnppial_static.a		/usr/local/cuda/lib/libnppitc_static.a
/usr/local/cuda/lib/libcufft.8.0.dylib		/usr/local/cuda/lib/libnppicc.8.0.dylib		/usr/local/cuda/lib/libnpps.8.0.dylib
/usr/local/cuda/lib/libcufft.dylib		/usr/local/cuda/lib/libnppicc.dylib		/usr/local/cuda/lib/libnpps.dylib
/usr/local/cuda/lib/libcufft_static.a		/usr/local/cuda/lib/libnppicc_static.a		/usr/local/cuda/lib/libnpps_static.a
/usr/local/cuda/lib/libcufftw.8.0.dylib		/usr/local/cuda/lib/libnppicom.8.0.dylib	/usr/local/cuda/lib/libnvToolsExt.1.dylib
/usr/local/cuda/lib/libcufftw.dylib		/usr/local/cuda/lib/libnppicom.dylib		/usr/local/cuda/lib/libnvToolsExt.dylib
/usr/local/cuda/lib/libcufftw_static.a		/usr/local/cuda/lib/libnppicom_static.a		/usr/local/cuda/lib/libnvblas.8.0.dylib
/usr/local/cuda/lib/libcuinj.8.0.dylib		/usr/local/cuda/lib/libnppidei.8.0.dylib	/usr/local/cuda/lib/libnvblas.dylib
/usr/local/cuda/lib/libcuinj.dylib		/usr/local/cuda/lib/libnppidei.dylib		/usr/local/cuda/lib/libnvgraph.8.0.dylib
/usr/local/cuda/lib/libculibos.a		/usr/local/cuda/lib/libnppidei_static.a		/usr/local/cuda/lib/libnvgraph.dylib
/usr/local/cuda/lib/libcurand.8.0.dylib		/usr/local/cuda/lib/libnppif.8.0.dylib		/usr/local/cuda/lib/libnvgraph_static.a
/usr/local/cuda/lib/libcurand.dylib		/usr/local/cuda/lib/libnppif.dylib		/usr/local/cuda/lib/libnvrtc-builtins.8.0.dylib
/usr/local/cuda/lib/libcurand_static.a		/usr/local/cuda/lib/libnppif_static.a		/usr/local/cuda/lib/libnvrtc-builtins.dylib
/usr/local/cuda/lib/libcusolver.8.0.dylib	/usr/local/cuda/lib/libnppig.8.0.dylib		/usr/local/cuda/lib/libnvrtc.8.0.dylib
/usr/local/cuda/lib/libcusolver.dylib		/usr/local/cuda/lib/libnppig.dylib		/usr/local/cuda/lib/libnvrtc.dylib
/usr/local/cuda/lib/libcusolver_static.a	/usr/local/cuda/lib/libnppig_static.a

**Comment by yaroslavvb** [comment]
This issue has been reported before, if you search issues you'll find solutions (disable SIP, set DYLD_LIBRARY_PATH, etc)
