### ISSUE TITLE
Please stop supporting this lab, please stop writing ml libs, please change your area of ​​activity

### ISSUE THREAD

**Issue by AndreyStille** [tensorflow/tensorflow#74695]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

Every version

### Custom code

Yes

### Current behavior?

All version of your shitty lib are nonsense and bugged.
You don't fix plenty of huge issues for years.
Stop this please. You bring so much evil with this shit. The time people spend for your shitty framework costs many lives. You are almost killing people.
And don't even ask what is the problem. Problem is everything: speed, versions compatibility, serialization, logging, debugging. Just everything is broken bugged shit. When you fix one nonsense bug another occurs. 
Just submit that you are not good at it and stop. 

### Standalone code to reproduce the issue

```shell
All version of your shitty lib are nonsense and bugged.
You don't fix plenty of huge issues for years.
Stop this please. You bring so much evil with this shit. The time people spend for your shitty framework costs many lives. You are almost killing people.
And don't even ask what is the problem. Problem is everything: speed, versions compatibility, serialization, logging, debugging. Just everything is broken bugged shit. When you fix one nonsense bug another occurs. 
Just submit that you are not good at it and stop.
```

**Comment by mihaimaruseac** [comment]
Closing as rant
