### ISSUE TITLE
With the same input and parameter settings, there is a large difference in the output of LayerNormalization layer on GPU and CPU

### ISSUE THREAD

**Issue by BiophiliaSWDA** [tensorflow/tensorflow#74796]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf2.12.0

### Custom code

Yes

### OS platform and distribution

Ubuntu20.04

### Mobile device

Ubuntu20.04

### Python version

3.10

### CUDA/cuDNN version

CUDA 11.8, cuDNN 8

### Current behavior?

DIFF: 0.37556207180023193
(False, 'Grad diff too big')

### Standalone code to reproduce the issue

```shell
import copy
import numpy as np
import tensorflow as tf

tf.config.experimental.enable_op_determinism()

def pointnet(input_shape):
    input_tensor = tf.keras.Input(shape=input_shape)
    x = tf.keras.layers.Conv1D(filters=64, kernel_size=7, padding="valid")(input_tensor)
    x = tf.keras.layers.Softmax()(x)
    x = tf.keras.layers.Activation(activation='softplus')(x)
    x = tf.keras.layers.MaxPool1D(padding='valid', strides=4)(x)
    x = tf.keras.layers.BatchNormalization(center=False, momentum=0.07244736627895476, epsilon=0.3847853359642447)(x)
    x = tf.keras.layers.Activation(activation='exponential')(x)
    x = tf.keras.layers.MaxPooling1D(padding='same', strides=6, data_format='channels_last')(x)
    x = tf.keras.layers.Softmax(axis=2)(x)
    x = tf.keras.layers.Activation(activation='hard_sigmoid')(x)
    x = tf.keras.layers.Flatten()(x)
    x = tf.keras.layers.Dense(units=1, use_bias=False, activation='softplus', bias_constraint=None, bias_regularizer=None, kernel_regularizer=None, kernel_constraint=None, activity_regularizer=None, bias_initializer='identity', kernel_initializer='truncated_normal')(x)
    x = tf.keras.layers.LayerNormalization(center=True, axis=1, scale=True, beta_constraint=None, epsilon=0.7136230859666187, gamma_initializer='glorot_normal', beta_regularizer=None, gamma_constraint=None, beta_initializer='zeros', gamma_regularizer=None)(x)
    x = tf.keras.layers.Activation(activation='selu')(x)
    x = tf.keras.layers.Dense(units=8, use_bias=False, activation='selu', kernel_regularizer=None, bias_constraint=None, bias_regularizer=None, bias_initializer='ones', kernel_initializer='glorot_uniform', kernel_constraint=None, activity_regularizer=None)(x)
    tail_flatten = tf.keras.layers.Flatten()(x)
    tail_fc = tf.keras.layers.Dense(units=10)(tail_flatten)
    model = tf.keras.models.Model(inputs=input_tensor, outputs=tail_fc)
    return model


def chebyshev_distance(A: np.ndarray, B: np.ndarray):
    if A is None or B is None:
        return 0.0
    if A.shape != B.shape:
        return 9999999
    else:
        return float(np.max(np.abs(A - B)))


def train(inp, label):
    flag = True
    label = tf.convert_to_tensor(label)
    model_g = pointnet(inp.shape[1:])
    model_g.load_weights("./output_dict/grad_diff_initial_weights.h5")
    
    with tf.device('GPU'):
        with tf.GradientTape() as tape:
            output_g = model_g(inp)
            loss_g = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)(label, output_g)
        gradients_g = tape.gradient(loss_g, model_g.trainable_variables)
        gradients_dic_g = {}
        for var, gradient in zip(model_g.trainable_variables, gradients_g):
            if gradient != None:
                gradients_dic_g.setdefault(var.name.replace('/', '.')[:-2], gradient)

    model_c = copy.deepcopy(model_g)
    model_c.load_weights("./output_dict/grad_diff_initial_weights.h5")
    with tf.device('CPU'):
        with tf.GradientTape() as tape:
            output_c = model_c(inp)
            loss_c = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)(label, output_c)
        gradients_c = tape.gradient(loss_c, model_c.trainable_variables)
        gradients_dic_c = {}
        for var, gradient in zip(model_c.trainable_variables, gradients_c):
            if gradient != None:
                gradients_dic_c.setdefault(var.name.replace('/', '.')[:-2], gradient)
    if chebyshev_distance(output_c.numpy(), output_g.numpy()) > 1.0:
        flag = False
        return flag, 'Output diff too big'
    if abs(loss_c - loss_g) > 0.1:
        flag = False
        return flag, 'Loss diff too big'
    for name in gradients_dic_c.keys(): 
        if name in gradients_dic_g.keys():
            if chebyshev_distance(gradients_dic_c[name], gradients_dic_g[name]) > 0.1:
                print(chebyshev_distance(gradients_dic_c[name], gradients_dic_g[name]))
                flag = False
                return flag, 'Grad diff too big'
    for name in gradients_dic_g.keys():
        if name in gradients_dic_c.keys():
            if chebyshev_distance(gradients_dic_g[name], gradients_dic_c[name]) > 0.1:
                print(gradients_dic_c[name], gradients_dic_g[name])
                flag = False
                return flag, 'Grad diff too big'
    return flag, ''


data = np.load("./output_dict/grad_diff_input.npz")
inp = data['inp']
label = data['label']
print(train(inp, label))
```

**Comment by SujalBagade** [comment]
A temporary workaround is to replace `LayerNormalization` with `BatchNormalization` or to manually set a higher `epsilon` value, which reduces the discrepancy in floating-point operations.

**Comment by BiophiliaSWDA** [comment]
> A temporary workaround is to replace `LayerNormalization` with `BatchNormalization` or to manually set a higher `epsilon` value, which reduces the discrepancy in floating-point operations.

You can repeat my mistake by following this link:

https://github.com/PhyllisJi/MoCoDiff_Bug/tree/tf-issue-%2374796

**Comment by PhyllisJi** [comment]
> Asked ChatGpt about this, answer is below. See if it can help
> 
> The issue you've described seems to revolve around a discrepancy between the outputs of a LayerNormalization layer when running on a GPU versus a CPU, using the same input and parameter settings. This kind of inconsistency can be a significant problem, especially in scenarios where deterministic behavior is expected across different hardware platforms.
> 
> Possible Reasons for the Discrepancy: Floating-Point Precision: GPUs and CPUs may handle floating-point calculations differently. GPUs often use single precision (32-bit floating-point), while CPUs might use double precision (64-bit floating-point) or other precision levels depending on the settings. This difference can lead to variations in the results of operations that involve multiple floating-point calculations, such as LayerNormalization.
> 
> Parallel Computation: GPUs perform many operations in parallel, which can introduce slight differences in the order of operations compared to a CPU, which may execute operations sequentially. This difference can affect operations like normalization, where the order of summation can influence the final result due to the non-associativity of floating-point arithmetic.
> 
> Determinism Settings: Although you've enabled deterministic operations in TensorFlow with tf.config.experimental.enable_op_determinism(), not all TensorFlow operations may fully honor this setting, especially for complex layers like LayerNormalization.
> 
> CUDA/cuDNN Version: Different versions of CUDA and cuDNN can have slight variations in implementation, which might contribute to differences in the results. Even small changes in how operations are optimized can lead to different outputs on GPU versus CPU.
> 
> LayerNormalization Implementation: The implementation of LayerNormalization might differ slightly between GPU and CPU kernels, leading to differences in the final output. This could be due to different optimization techniques or specific hardware instructions used by GPUs.
> 
> Possible Solutions or Workarounds: Increase Tolerance for Differences: Depending on your use case, it might be acceptable to increase the tolerance for differences between CPU and GPU outputs. You could adjust the thresholds used in your checks, such as the chebyshev_distance threshold.
> 
> Test with Different CUDA/cuDNN Versions: If feasible, try testing your code with different versions of CUDA and cuDNN to see if the issue persists or if it varies with different configurations.
> 
> Use CPU-Only for Deterministic Results: If deterministic behavior is critical and GPU introduces too much variance, consider using CPU-only execution for critical parts of your model where exact reproducibility is required.
> 
> Custom LayerNormalization Implementation: If the issue is isolated to LayerNormalization, consider implementing a custom version that you can control more tightly, ensuring consistency across platforms.
> 
> If this discrepancy is affecting a critical application, you might consider opening a detailed issue on the TensorFlow GitHub repository with all relevant information, including the specific CUDA/cuDNN versions, GPU model, and any other hardware-specific details. This could help the TensorFlow team investigate and potentially resolve the issue.

Thank you for your answer. We have tried all the measures you mentioned, but differences still exist.

**Comment by tilakrayal** [comment]
@BiophiliaSWDA,
Could you please try to check with the latest tensorflow v2.17 which contains the keras3.0 by default and provide the update if there is a difference in the output.  Thank you!

**Comment by PhyllisJi** [comment]
> @BiophiliaSWDA, Could you please try to check with the latest tensorflow v2.17 which contains the keras3.0 by default and provide the update if there is a difference in the output. Thank you!

When I check with TF 2.18.0, I face this error:
```python
Traceback (most recent call last):
  File "/root/miniconda3/envs/tf2.17/lib/python3.10/site-packages/keras/src/ops/operation.py", line 234, in from_config
    return cls(**config)
  File "/root/miniconda3/envs/tf2.17/lib/python3.10/site-packages/keras/src/layers/core/dense.py", line 92, in __init__
    self.bias_initializer = initializers.get(bias_initializer)
  File "/root/miniconda3/envs/tf2.17/lib/python3.10/site-packages/keras/src/initializers/__init__.py", line 119, in get
    raise ValueError(
ValueError: Could not interpret initializer identifier: {'module': 'keras.initializers', 'class_name': 'IdentityInitializer', 'config': {}, 'registered_name': None}
```

**Comment by PhyllisJi** [comment]
> A temporary workaround is to replace `LayerNormalization` with `BatchNormalization` or to manually set a higher `epsilon` value, which reduces the discrepancy in floating-point operations.

It's not that the output is different, it's that the parameters are updated differently.

**Comment by tilakrayal** [comment]
@BiophiliaSWDA,
The reason for the different results could be due to the optimized way of calculating numbers on Nvidia which is different compared to others, there will be a small amount of precision errors.

I think the issue is specific to GPU, I was able to reproduce the issue on colab with GPU runtime.
But, when the inputs are changed to float64 precision, the results are as expected. Same behavior is not observed on Apple M1, using numpy or in the CPU. Thank you!

**Comment by PhyllisJi** [comment]
> @BiophiliaSWDA, The reason for the different results could be due to the optimized way of calculating numbers on Nvidia which is different compared to others, there will be a small amount of precision errors.
> 
> I think the issue is specific to GPU, I was able to reproduce the issue on colab with GPU runtime. But, when the inputs are changed to float64 precision, the results are as expected. Same behavior is not observed on Apple M1, using numpy or in the CPU. Thank you!

Thank you for your reply! But I think TF should do some optimisation means to avoid this type of error? Because NVIDIA's GPUs are used in a wide range of applications.

**Comment by tilakrayal** [comment]
@BiophiliaSWDA,
The layers LayerNormalization and BatchNormalization are related to Keras. Could you please raise the issue in the Keras-team/keras repo for the quick resolution. Thank you!
