### ISSUE TITLE
sparse_placeholder failed when specifying shape

### ISSUE THREAD

**Issue by liangwang** [tensorflow/tensorflow#7483]
When trying to create a sparse placeholder, exception raised if specifying the `shape` parameter:
```
features_placeholder = tf.sparse_placeholder(tf.float32, shape=(16, 20424)) # failed
features_placeholder = tf.sparse_placeholder(tf.float32)  # pass
```
Exception reads like:
```
  File "tf_learn.py", line 92, in run_training
    features_placeholder = tf.sparse_placeholder(tf.float32, shape=(FLAGS.batch_size, etc.FEATURE_SIZE))
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\tf-py35\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1653, in sparse_placeholder
    shape=shape
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\tf-py35\lib\site-packages\tensorflow\python\framework\sparse_tensor.py", line 135, in __init__
    shape = ops.convert_to_tensor(shape, name="shape", dtype=dtypes.int64)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\tf-py35\lib\site-packages\tensorflow\python\framework\ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\tf-py35\lib\site-packages\tensorflow\python\framework\ops.py", line 583, in _TensorTensorConversionFunction
    % (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int64 for Tensor with dtype int32: 'Tensor("Const:0", shape=(2,), dtype=int32)'

```

Is this a bug?

**Comment by yaroslavvb** [comment]
hm, is shape getting initialized to `tf.float64` value? You can try initializing with `shape=shape`, and create shape ahead of time as a tf.float32 tensorflow constant tensor

**Comment by liangwang** [comment]
@yaroslavvb thanks for the suggestion. I finally settled down on avoiding the `shape` parameter in the `sparse_placeholder` as almost all examples I found did not specify the `shape` parameter for the `sparse_placeholder`. 

I also traced it into the tensorflow python code, and found that the `shape` is converted to a `int64` array, and the `int64` dtype is hard-coded.

**Comment by aselle** [comment]
@concretevitamin, could you please take a look. it seems we could handle this case better? It's not consistent with shape arguments on dense tensor, I believe.

**Comment by concretevitamin** [comment]
@liangwang the reason is simply that, the design of `SparseTensor` already hardcodes the associated shape as `tf.int64` [1], so any downstream ops that consume these objects assume likewise as well.

[1] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/sparse_tensor.py#L59

**Comment by liangwang** [comment]
@concretevitamin , yes, it is hard-coded. But would this be considered a bug, since it will fail by specifying shapes with immediate numbers (like the first example I listed in the original post)?

**Comment by aselle** [comment]
@concretevitamin, ping

**Comment by concretevitamin** [comment]
I don't consider it a bug in `sparse_palceholder`... There's no automatic type casting in TensorFlow at the moment, which I think is the effect you're asking for.  (If you have a proposed design to solve this general problem, we'd love to hear about it in a focused issue!)

**Comment by liangwang** [comment]
If this is not considered as a bug, then how should we use the shape parameter? Clearly, it will fail by specifying plain numbers. At least, it helps by providing an example if the usage is not straightforward. Maybe, we can add the usage example to the document to avoid any further confusion.

**Comment by yaroslavvb** [comment]
@liangwang you can use `shape` parameter as follows:

`tf.sparse_placeholder(tf.float32, shape=np.array((16, 20424)).astype(np.int64))
`

A Python integer does not have a dtype, so it can be treated as int32 or int64.
I believe @suharshs has added the logic that defaults Python integers to int32.
It seems this is one of rare cases where it's better to treat Python integer as int64

**Comment by concretevitamin** [comment]
@liangwang what @yaroslavvb said (since `numpy.ndarray` defaults to 64-bit).  Another way could be:

`tf.sparse_placeholder(tf.float32, shape=tf.constant([16, 20424], tf.int64))`

**Comment by ChouGS** [comment]
What if I wish to apply functions that manipulate the shape of sparse tensors, like `tf.expand_dims()` and `tf.squeeze()`? It fails even if I have assigned a shape to my `tf.sparse_placeholder`.
