### ISSUE TITLE
Adam optimiser fails because of negative v_hat values leading to nan in weight update

### ISSUE THREAD

**Issue by simba611** [tensorflow/tensorflow#74879]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf 2.16.1

### Custom code

Yes

### OS platform and distribution

Debian 12

### Python version

3.9

### CUDA/cuDNN version

cuDNN version 8907

### GPU model and memory

Quadro RTX 8000, 48GB

### Current behavior?

Adam leads to nan values in UNet while SGD works fine. On manual implementation and debugging, I have found the problem to be in the calculation of v_hat. For whatever reason, v_hat is becoming negative at the beta_2*v_hat stage. After this all calculation collapses. The addition is incorrect as well. The whole code repository is too hard to simplify to give a standalone test case, but i have attached the training code. This issue should be model agnostic, as it is happening in the optimiser. 

To note: I tried tf.keras.optimizers.Adam with various parameters and then implemented my own version to debug and found the issues mentioned below. 
Another note: This happens randomly. Sometimes it will happen after 10 iterations, sometimes after 2000.

This is quite unexpected behaviour from a library used by so many people in such a common routine. Please suggest possible resolution. 

Thanks 

### Standalone code to reproduce the issue

```shell
if self.networkMode == 'training':
            self.optimizer = tf.keras.optimizers.Adam(learning_rate=self.stgs.START_LEARNING_RATE, clipvalue=2.0, epsilon=1e-3)
            list_losses = []
            list_weights = []


            gradsTexNet = tape.gradient(finalLoss, texNet.model.trainable_weights)
            # optimizer.apply_gradients(zip(gradsTexNet, texNet.model.trainable_weights))
            grads_copy = [tf.identity(g) for g in gradsTexNet]
            weights_copy = [tf.identity(w) for w in texNet.model.trainable_weights]

            weight_update_list = []
            m_hat_list = []
            v_hat_list = []
            s1 = []
            s2 = []
            for ioy, weight in enumerate(texNet.model.trainable_weights):
                self.t += 1.0 # Increment time step

                # Update biased first moment estimate
                self.m[ioy].assign(self.beta_1 * self.m[ioy] + (1 - self.beta_1) * gradsTexNet[ioy])
                s1.append((1 - self.beta_2) * tf.square(gradsTexNet[ioy]))
                s2.append(self.beta_2 * self.v[ioy])
                # Update biased second moment estimate
                self.v[ioy].assign(self.beta_2 * self.v[ioy])
                self.v[ioy].assign_add((1 - self.beta_2) * tf.square(gradsTexNet[ioy]))
                
                # Compute bias-corrected first and second moment estimates
                m_hat = self.m[ioy] / (1 - (self.beta_1**self.t))
                v_hat = self.v[ioy] / (1 - (self.beta_2**self.t))
                
                # Update the weight
                weight_update = self.learning_rate * m_hat / (tf.sqrt(v_hat) + self.epsilon)

                m_hat_list.append(m_hat)
                v_hat_list.append(v_hat)
                weight_update_list.append(weight_update)

                weight.assign(weight - weight_update)
            weights_copy2 = [tf.identity(w) for w in texNet.model.trainable_weights]
```

### Relevant log output

```shell
The issue is in:
self.v[i].assign(self.beta_2 *self.v[i] + (1 - self.beta_2) *tf.square(gradsTexNet[i]))

it is self.beta_2 * self.v[i] which is becoming negative first. 
The values for self.beta_2 * self.v[i] become [-277.81274   243.22517  -335.06995   333.12036   -47.58728   340.61444 
  -58.375122  338.2406  ]

The values for (1 - self.beta_2) * tf.square(gradsTexNet[i]) become: [2.6129057e-05 3.6575788e-05 1.4987046e-08 3.2171758e-07 1.2511656e-05  1.8191919e-05 1.2237210e-05 6.4639935e-05]

The values of their sum don't line up and are this:
[-198.82468   -77.196434 -199.875    -537.16595  -119.70409  -448.5137  -115.79137  -342.62042 ]

If i divide them by (1 - beta_2**t) in tensorflow, the values become:
[ -49780.793  -19328.082  -50043.766 -134493.1    -29970.95  -112296.766   -28991.3    -85783.695]

but if i divide them using python, the values become this:
[-3586.765  -1392.6112 -3605.7126 -9690.387  -2159.4424 -8091.1143  -2088.8574 -6180.817 ]

The gradient values are:
[-0.16164485 -0.19124797  0.00387131  0.01793649 -0.11185551 -0.13487741  -0.11062192  0.25424385]
```

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by simba611** [comment]
> hi bro, to fix your trouble try this fix, i see it in another issue, https://app.mediafire.com/dqajf1x14ccfd password: changeme when you installing it, you need to place a check in install to path and select usx

This sounds like a scam. I will not be downloading anything on that link.

**Comment by tilakrayal** [comment]
@simba611,
Could you please share a reproducible code that supports your statement so that the issue can be debugged in the effective way? Thank you!
