### ISSUE TITLE
 `Aborted` issue raised in TensorFlow when using data_flow_ops.SparseConditionalAccumulator and apply_indexed_slices_grad with mismatched data types

### ISSUE THREAD

**Issue by KnightGOKU** [tensorflow/tensorflow#74917]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf-nightly 2.18.0.dev20240817

### Custom code

Yes

### Current behavior?

I encountered an `Aborted` issue in TensorFlow when using the `data_flow_ops.SparseConditionalAccumulator` API and `apply_indexed_slices_grad` with mismatched data types. The code was confirmed to crash on `tf-nightly 2.18.0.dev20240817` (nightly-build)
> 2024-08-31 13:45:53.349441: F tensorflow/core/framework/tensor.cc:844] Check failed: dtype() == expected_dtype (23 vs. 1) float expected, got uint64
Aborted (core dumped)

### Standalone code to reproduce the issue

```shell
import numpy as np
from tensorflow.python.framework import dtypes as dtypes_lib
from tensorflow.python.framework import indexed_slices
from tensorflow.python.framework import tensor_shape
from tensorflow.python.ops import data_flow_ops
import tensorflow as tf

tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session()

with sess.as_default():
    q = data_flow_ops.SparseConditionalAccumulator(dtypes_lib.float32, name='Q', shape=tensor_shape.TensorShape([3, 3]))
    accum_op = q.apply_indexed_slices_grad(indexed_slices.IndexedSlices(indices=[0, 2], values=np.array([[0, 0, 1], [3, 0, 4]]).astype(np.uint64)))
    accum_op.run()
```

### Relevant log output

```shell
2024-08-31 13:45:53.349441: F tensorflow/core/framework/tensor.cc:844] Check failed: dtype() == expected_dtype (23 vs. 1) float expected, got uint64
Aborted (core dumped)
```

**Comment by tilakrayal** [comment]
@KnightGOKU,
I tried to execute the mentioned code on tf-nightly and observed that the check fail is happening due to mismatch of the data type provided as input. I tried with the similar input data type and the code was executed without abort/fail. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3f663ffbe0bb69af5586ae3a60073c5d/untitled2203.ipynb). Thank you!
