### ISSUE TITLE
TensorBoard Projector does not work on Mac

### ISSUE THREAD

**Issue by nehardave** [tensorflow/tensorflow#7494]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

<img width="1440" alt="screen shot 2017-02-14 at 12 49 12 pm" src="https://cloud.githubusercontent.com/assets/25763469/22919144/130df352-f2b4-11e6-8eb5-86d8b886e64f.png">

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by normanheckscher** [comment]
It does work.
Your system must not be configured correctly.

Here is a how to question/answer on stackoverflow where this issue should have been raised:
http://stackoverflow.com/questions/41258391/tensorboard-embedding-example/41262360#41262360

Please close this GitHub issue.

**Comment by nehardave** [comment]
Hi Norman,
Thanks for the reply. I understand that the configuration has some problem. I am new to Tensorflow and want to understand the visualisation.
The Blog/github repo seems old and some package names have changed. It does not compile.
https://github.com/normanheckscher/mnist-tensorboard-embeddings/blob/master/mnist_t-sne.py


-Best Regards,
Neha Dave

**Comment by nehardave** [comment]
Hi Norman,

I get following error:   File "mnist_t.py", line 49, in generate_embeddings

    tf.global_variables_initializer().run()

AttributeError: module 'tensorflow' has no attribute 'global_variables_initializer'


But if I check documents : https://www.tensorflow.org/api_docs/python/ there is tf.global_variables_initializer


-Best Regards,
Neha Dave

**Comment by normanheckscher** [comment]
I've been able to run that code of mine with all the latest tensorflow versions.
There have been some breaking API changes and I have refactored my code accordingly.
Have you tried using the latest TensorFlow 1.0 release candidates.

If you are still using TensorFlow 0.12.1 or lower, then try this code:
https://github.com/normanheckscher/mnist-tensorboard-embeddings/archive/64cedc5b021fa5128261f0aa2dc22c335880ae1d.zip

**Comment by nehardave** [comment]
Hey..
I am using tensorflow (0.11.0)
I will upgrade to 1.0 and try.
Thanks :) !
-Best Regards,
Neha Dave

**Comment by nehardave** [comment]
Hi Norman,
Thanks!! It was the version problem. I am able to compile and run your code.
I have a question about the process for Visualization.

1.       I have data in .csv format(some text and some int). How to create the metadata file?

For your code you do it:
     with open(file, 'w') as f:
            for i in range(FLAGS.max_steps):
                c = np.nonzero(mnist.test.labels[::1])[1:][0][i]

Thanks
Regards
Neha

**Comment by aselle** [comment]
@nehardave, it seems your original problem is solved, so I'm closing this issue. The followup question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by nehardave** [comment]
Thanks I will do so !
