### ISSUE TITLE
TFLite Hexagon Delegate not working for QCOM SM6375 SOC.

### ISSUE THREAD

**Issue by hholokai** [tensorflow/tensorflow#74993]
I'm trying to get a quantized model running on the Qualcomm SM6375 DSP on a Zebra ET40 tablet, without success.  SOC info:

```
$ cat /sys/devices/soc0/soc_id
507
```

The FP32 model works fine on CPU and GPU.  However, when I try to run the INT8 model on the DSP, it falls back to running the XNNPack Delegate on CPU, which is slow:

```
$ ./benchmark_model --graph=model.tflite --use_hexagon=true                                                                
INFO: STARTING!
INFO: Log parameter values verbosely: [0]
INFO: Graph: [model.tflite]
INFO: Signature to run: []
INFO: Use Hexagon: [1]
INFO: Loaded model model.tflite
INFO: Initialized TensorFlow Lite runtime.
loaded libcdsprpc.so
WARNING: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
INFO: Hexagon Delegate is not supported.

WARN: Could not create Hexagon delegate: platform may not support delegate or required libraries are missing
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
...
```

I've tried several different versions of the Hexagon libraries referred to below, but all fall back to the CPU:

https://www.tensorflow.org/lite/android/delegates/hexagon

This page above has the following warning:

> Caution: The currently released versions of the Hexagon delegate, up to version 1.20.0.1, are no longer supported. An updated version of this delegate is expected soon.

I've also tried the NNAPI (--use_nnapi=true), but that also falls back to the CPU.

Any help would be appreciated.

**Comment by gaikwadrahul8** [comment]
Hi, @hholokai 

I apologize for the delayed response, The [NNAPI](https://www.tensorflow.org/lite/android/delegates/nnapi) and [Hexagon](https://www.tensorflow.org/lite/android/delegates/hexagon) delegates are deprecated and no longer supported by TensorFlow Lite. For more information, see the [NNAPI Migration Guide](https://developer.android.com/ndk/guides/neuralnetworks/migration-guide) and [TF Lite delegates documentation](https://www.tensorflow.org/lite/performance/delegates).

Thank you for your cooperation and patience.
