### ISSUE TITLE
error when running conda create -n tensorflow python=2.7

### ISSUE THREAD

**Issue by brisker** [tensorflow/tensorflow#7499]
the error reads like:
jcc@jcc:~$ conda create -n tensorflow python=2.7
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/jcc/anaconda2/envs/tensorflow:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2k             |                0         3.2 MB
    python-2.7.13              |                0        11.5 MB
    setuptools-27.2.0          |           py27_0         521 KB
    pip-9.0.1                  |           py27_1         1.6 MB
    ------------------------------------------------------------
                                           Total:        16.7 MB

The following NEW packages will be INSTALLED:

    openssl:    1.0.2k-0     
    pip:        9.0.1-py27_1 
    python:     2.7.13-0     
    readline:   6.2-2        
    setuptools: 27.2.0-py27_0
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-3      

Proceed ([y]/n)? y

Fetching packages ...
Error: Could not open u'/home/jcc/anaconda2/pkgs/openssl-1.0.2k-0.tar.bz2.part' for writing (seek).
Any help?

**Comment by yaroslavvb** [comment]
What if you do `conda create -n not_tensorflow python=2.7`? I expect you will get the same error, which proves that this is a not tensorflow issue

**Comment by gunan** [comment]
I agree with @yaroslavvb 
This is a problem with `conda` tools new environment creation.
Closing this issue.
