### ISSUE TITLE
Adding new Ops, how to install it?

### ISSUE THREAD

**Issue by daothanhtuan** [tensorflow/tensorflow#750]
Okay I have added a new op as suggested in tutorial, however I can't find instruction to compile it. Will I have to use bazel to add it to the current TensorFlow framework (which already installed in my machine)? Do I have to re-build the whole framework or just the part that I have modified?

**Comment by daothanhtuan** [comment]
Reading the instructions more carefully I found the answers so I will close this.

**Comment by vrv** [comment]
@keveman is also working on a better way to add new ops, so stay tuned.
