### ISSUE TITLE
Tensorflow model loading error

### ISSUE THREAD

**Issue by shikharRS** [tensorflow/tensorflow#75000]
i am using below version to train my model on linux machine x86_64 and i successfully trained it.
Python version: 3.8.19 | packaged by conda-forge | (default, Mar 20 2024, 12:47:35)
[GCC 12.3.0]
Tensorflow version: 2.7.0
Keras version: 2.7.0

After succesfully training , the inferencing is also happening using the same model  which i saved as tensorflow saved model.

Now i want to deploy it on Jetson nano, which have below versions
python version 3.6.15
tensorflow version 2.7.0
keras version 2.7.0

The problem is, i am not able to load my model in jetson nano.
The error i am encountering is in load file.
that (path).meta_graphs[0]
The list index(0) is out of the range
Below is line of codde causing error
tf.keras.models.load_model(‘model2’)

**Comment by tilakrayal** [comment]
@shikharRS,
Could you please provide the reproducible code or the colab gist and the error log which you are facing. Also could you please try to upgrade the latest tensorflow v2.17, also you are using the tensorflow v2.7 which is pretty older and support is very limited. Thank you!

**Comment by shikharRS** [comment]
> @shikharRS, Could you please provide the reproducible code or the colab gist and the error log which you are facing. Also could you please try to upgrade the latest tensorflow v2.17, also you are using the tensorflow v2.7 which is pretty older and support is very limited. Thank you!

Hi tilakrayal,

i fixed that issue model is getting loaded. Thanks

**Comment by shikharRS** [comment]
As i am using jetson nano whose GPU is compatible with  only tf 2.7 having python 3.6 . Anyway i can update it to 2.17 or 2.15 but that will not be able to use GPU computation of jetson nano.
Thanks
