### ISSUE TITLE
Memory footprint  in cpu and opencl

### ISSUE THREAD

**Issue by keke444** [tensorflow/tensorflow#75029]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.13

### Custom code

Yes

### Current behavior?

Hi

      In Android ,  using benchmark tool test memory footprint in cpu and opencl ,  
logs  show memory footprint is very different: 
Memory footprint delta from the start of the tool (MB): init=224.859 overall=260.609     ----------gpu  opencl
Memory footprint delta from the start of the tool (MB): init=25.0977 overall=757.574    -----------cpu
      We want to know
     1. if the opencl memory footprint only counts malloc heap memory? Or does it also include gpu buffers, and if so, how are they calculate；
      2. And Why is the memory situation on the cpu so different from that on the opencl， should we take init memory footprint into consideration or overall？

thanks

### Standalone code to reproduce the issue

```shell
using benchmark tool command like

./benchmark_model --graph=final.tflite --num_threads=4 --num_runs=5   
./benchmark_model --graph=final.tflite --num_threads=4 --num_runs=5  --use_gpu=true
```

**Comment by keke444** [comment]
We just want to calculate the memory footprint of our tflite model on cpu and opencl,  
using bazel-bin/tensorflow/lite/tools/benchmark_model  --graph=final.tflite --num_threads=4 --num_runs=5 
No other code was used

**Comment by misterBart** [comment]
Possibly related to https://github.com/tensorflow/tensorflow/issues/74521#issue-2486869907
There I also measure a large memory footprint with OpenCL and a small footprint with the CPU (Xnnpack).
@keke444 What GPU do you use?

**Comment by gaikwadrahul8** [comment]
Hi, @pkgoogle 
Please take look into this issue. Thank you

**Comment by pkgoogle** [comment]
Hi @keke444, can you please share `final.tflite` or perhaps a similar/reduced model which still shows this result?
