### ISSUE TITLE
How change the package name of tensorflow android camera demo

### ISSUE THREAD

**Issue by davideb91** [tensorflow/tensorflow#7503]
I have built two Android demo with two different custom models. However in order to install both apps on my device I need to change the name of one of these. Is there an easy way to change the name of the apk file?

**Comment by andrewharp** [comment]
You can change the Android package in [AndroidManifest.xml](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/AndroidManifest.xml#L19) to avoid the conflict.
