### ISSUE TITLE
Inference performance questions

### ISSUE THREAD

**Issue by eyalhir74** [tensorflow/tensorflow#75102]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

v2.13.0-17-gf841394b1b7 2.13.1

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04.6 LTS

### Python version

3.8.10

### Bazel version

5.3.0

### GCC/compiler version

9.4.0

### Current behavior?

Server have 72 cpu cores. I'm unable to get more than 60% cpu utilization when using more than 16 threads via the --tensorflow_inter_op_parallelism parameter.
I'd like to use one tensorflow_model_server instance that would utilize all the HW cpu cores. Using tensorflow_inter_op_parallelism > 16, the utilization per thread drops as low as 30-40% utilization and the overall performance doesn't improve.

I'm using:
tensorflow_model_server --port=5051 --model_name=taboola_serving --model_base_path=/opt/taboola/models/cvr/ --tensorflow_intra_op_parallelism=32 --tensorflow_inter_op_parallelism=16

Also, attached is a flamegraph. I fail to understand why the ThreadPoolDevice::Compute part is only 38.5% of the overall time.
Is there some other perfromance parameter that I'm missing?

![perf](https://github.com/user-attachments/assets/220fb4d1-09de-4650-8121-0b21fe34d4e7)

### Standalone code to reproduce the issue

```shell
As described above
```

**Comment by Venkat6871** [comment]
Hi **@eyalhir74** ,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here.
Thank you!

**Comment by eyalhir74** [comment]
Thanks @Venkat6871 !

I'm just loading our model to tensorflow_model_server and have a client that does infer calls against it.
So not much code that I can supply.

Attached are two screenshots that hopefully better demonstrate it.
The first image shows a top breakdown when the server was started with --tensorflow_inter_op_parallelism=8 - you can see 8 threads that reach ~92% utilization

Second image is when running with --tensorflow_inter_op_parallelism=16 and top shows 16 threads with 60% utilization.

Now, since the server have 72 cpu cores, I'd like to open one big tensorflow server running on all cpu cores, all reaching 90+% utilization. No matter how many clients/load I put on the server with tensorflow_inter_op_parallelism > 16, I can't reach full utilization and the HW just sits idle then.


<img width="636" alt="Screenshot 2024-09-05 at 14 05 22" src="https://github.com/user-attachments/assets/6cdee627-2b91-4d02-98ae-93c01de08432">
<img width="652" alt="Screenshot 2024-09-02 at 8 01 32" src="https://github.com/user-attachments/assets/70d42510-7a2f-44c4-a7c0-b5306b73d9e3">

**Comment by eyalhir74** [comment]
Thanks @Venkat6871 !

I'm just loading our model to tensorflow_model_server and have a client that does infer calls against it.
So not much code that I can supply.

Attached are two screenshots that hopefully better demonstrate it.
The first image shows a top breakdown when the server was started with --tensorflow_inter_op_parallelism=8 - you can see 8 threads that reach ~92% utilization

Second image is when running with --tensorflow_inter_op_parallelism=16 and top shows 16 threads with 60% utilization.

Now, since the server have 72 cpu cores, I'd like to open one big tensorflow server running on all cpu cores, all reaching 90+% utilization. No matter how many clients/load I put on the server with tensorflow_inter_op_parallelism > 16, I can't reach full utilization and the HW just sits idle then.
<img width="627" alt="Screenshot 2024-09-05 at 14 08 27" src="https://github.com/user-attachments/assets/2f824dc1-1f31-40b3-b856-29d10594b9d9">
<img width="636" alt="Screenshot 2024-09-05 at 14 05 22" src="https://github.com/user-attachments/assets/beaa3f0d-ff22-43f6-911f-8cb49db562df">

**Comment by eyalhir74** [comment]
@Venkat6871 any idea what could be wrong here?

**Comment by Venkat6871** [comment]
Hi **@eyalhir74** ,
Apologies for the delay, and thank you for the information. However, without the proper code, it is difficult for us to debug the issue. To expedite the troubleshooting process, we need a code snippet to reproduce the reported issue.
Thank you!
