### ISSUE TITLE
non_max_suppression is very slow and doesn't appear to have a cuda or multi-threaded implementation

### ISSUE THREAD

**Issue by andrei-pokrovsky** [tensorflow/tensorflow#7511]
It appears that tf.image.non_max_suppression currently takes about 200ms for about 8000 boxes, runs on a single CPU thread and doesn't have a GPU implementation.

### Environment info
Operating System:
Ubuntu 16.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
8.0, 5.1.5

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
0.12.0-rc1

**Comment by RobSalzwedel** [comment]
Is there any progress on this feature?

**Comment by aluo-x** [comment]
Also interested in this as well.

**Comment by harishannavajjala** [comment]
Are there any good examples online on how to use tf.image.non_max_suppression ?? And does using this in-built nms function over our own function improves performance of the model ?

**Comment by ppwwyyxx** [comment]
The documentation is pretty clear IMHO, which part do you have questions?
For speed the answer is always the same: it depends on the speed of "your own function" (which only you know) plus the overhead to transfer data between TF and your own function.

**Comment by sharpstill** [comment]
@ppwwyyxx also want GPU version of NMS? Does there any progress here?

**Comment by MaskVulcan** [comment]
@ppwwyyxx when I use nms. I set the profile and find mns is in CPU.Is there any way to use NMS on GPU?

**Comment by zhenglaizhang** [comment]
This feature will be fantastic

**Comment by jonla1** [comment]
In [Work-efficient parallel non-maximum suppression for embedded GPU architectures](https://ieeexplore.ieee.org/document/7471831/) the authors describe how to bring NMS to the GPU.

Also does anyone know what the difference is between the implementation of NonMaxSuppressionV2 and NonMaxSuppression in Tensorflow?

**Comment by keineahnung2345** [comment]
@jonla1 Someone has implemented a CUDA version based on the mentioned paper here:
https://github.com/jeetkanjani7/Parallel_NMS
And following is my PyCUDA version:
https://github.com/keineahnung2345/Parallel_NMS

**Comment by zjjott** [comment]
+1

**Comment by joeyearsley** [comment]
https://github.com/zengarden/light_head_rcnn/tree/master/lib/lib_kernel/lib_nms_dev

Here is a GPU version which can be built for TF.

**Comment by SpaceInvader61** [comment]
There seems to be a related commit #28745
