### ISSUE TITLE
How to build static libraries and link them to a c++ project in linux platform?

### ISSUE THREAD

**Issue by zig-kwin-hu** [tensorflow/tensorflow#7518]
I am working on a text-classification project, which is big and doesn't use bazel as its build tool. I want to integrate tensorflow into my project, but I find it is hard to change my build tool to bazel. So I wish to  build static libraries on tensorflow and link them into my project. 
Does anyone know how to build standalone static libraries and link them in the existing c++ project? Thanks a lot.

**Comment by asimshankar** [comment]
This question is probably better suited for [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) as we try to keep the github issues focused on bugs and feature requests.
