### ISSUE TITLE
Can Tensorflow build complex probablistic graph model ?

### ISSUE THREAD

**Issue by artzers** [tensorflow/tensorflow#7519]
Hello. I am surprised by the optimization ability of tensorflow, and want tensorflow to solve more math models. However, I find few articles about how to build  complex probablistic graph model fast and simple. Are there any ideas about introducing tensorflow into complex general probablistic graph model field?

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
