### ISSUE TITLE
Using a model (post training)

### ISSUE THREAD

**Issue by frankcarey** [tensorflow/tensorflow#752]
I've trained a simple model of my own in python, categorizing images into two categories (Imagenet apples, vs imagenet oranges). I'm looking to now evaluate arbitrary images using this model to get a prediction (apples v oranges) and I'm having trouble finding out the right way to do that for some reason.

At the moment I'm just using a random training image for simplicity.

```Python
# Use the existing graph and grab a sample image from the valid dataset.
tf_image = tf_valid_dataset[1001,:,:,:] 
result = tf.Session(graph=graph).run(tf_image)
```
I was trying to look at some of the API docs and the C++ imagenet example as inspiration, but I think I'm off track. `result` ends up being tf_image it seems.

I know that I want the result of a single forward pass, but having a hard time seeing the right way to get that.

**Comment by martinwicke** [comment]
`run` takes as first argument the ops to run. You want to set a feed_dict. 

This is a question better suited for StackOverflow, where you'll get more in depth answers. We try to keep issues for bug reports.

**Comment by frankcarey** [comment]
Fair enough, I'll add some of my findings here though for other looking at least:

One question I had quickly after training is how to save my work to a single "baked" model with the graph, weights, and biases in a single file.  I was assuming that I could do that with the existing graph easily, but it looks like you currently need to create an alternate graph to do that. See http://stackoverflow.com/questions/34343259/is-there-an-example-on-how-to-generate-protobuf-files-holding-trained-tensorflow/34343517#34343517
