### ISSUE TITLE
Can I use tensorflow to implement the red module function of VIDI?

### ISSUE THREAD

**Issue by BloodShadow** [tensorflow/tensorflow#7520]
I not idea to implement  the red module function of VIDI.

it can only use train OK image and inspection NG image.

it base on cnn??or rcnn?

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
