### ISSUE TITLE
error when import tensorflow:ImportError: libcudnn.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by brisker** [tensorflow/tensorflow#7522]
jcc@jcc:~$ pip show tensorflow
Name: tensorflow
Version: 1.0.0rc2
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /home/jcc/anaconda2/lib/python2.7/site-packages
Requires: werkzeug, six, wheel, mock, numpy, protobuf

I think the lines above has shown that I have installed the tensorflow using anaconda2(I installed tensorflow by building from source). I have not created a conda virtual environment.

Any help?Why this error? I make sure that in bashrc file I have this line:
export LD_LIBRARY_PATH=/home/jcc/cudnn/lib64:$LD_LIBRARY_PATH 
and in the ./configure  process of tensorflow I typed in "/home/jcc/cudnn" for cudnn_path
My server is Ubuntu 14.04, titan x gpu, cuda7.5 ,cudnn5

The last command line of my build history is like:
pip install /tmp/tensorflow_pkg/tensorflow-1.0.0rc2-cp27-cp27mu-linux_x86_64.whl

Processing /tmp/tensorflow_pkg/tensorflow-1.0.0rc2-cp27-cp27mu-linux_x86_64.whl
Requirement already satisfied: werkzeug>=0.11.10 in ./anaconda2/lib/python2.7/site-packages (from tensorflow==1.0.0rc2)
Requirement already satisfied: six>=1.10.0 in ./anaconda2/lib/python2.7/site-packages (from tensorflow==1.0.0rc2)
Requirement already satisfied: wheel in ./anaconda2/lib/python2.7/site-packages (from tensorflow==1.0.0rc2)
Requirement already satisfied: mock>=2.0.0 in ./anaconda2/lib/python2.7/site-packages (from tensorflow==1.0.0rc2)
Requirement already satisfied: numpy>=1.11.0 in ./anaconda2/lib/python2.7/site-packages (from tensorflow==1.0.0rc2)
Requirement already satisfied: protobuf>=3.2.0 in ./anaconda2/lib/python2.7/site-packages (from tensorflow==1.0.0rc2)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in ./anaconda2/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow==1.0.0rc2)
Requirement already satisfied: pbr>=0.11 in ./anaconda2/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow==1.0.0rc2)
Requirement already satisfied: setuptools in ./anaconda2/lib/python2.7/site-packages/setuptools-23.0.0-py2.7.egg (from protobuf>=3.2.0->tensorflow==1.0.0rc2)
Installing collected packages: tensorflow
Successfully installed tensorflow-1.0.0rc2

But when import tensorflow, the error reads like \ :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/jcc/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: libcudnn.so.5: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

**Comment by chenynCV** [comment]
I came across the same error when I'm using PyCharm.

**Comment by gammaguy** [comment]
@brisker How did you solve this

**Comment by kevinashaw** [comment]
@brisker  : Why was this closed without a solution?

**Comment by praneethmendu** [comment]
Had the same problem it was solved by ::

sudo ldconfig /usr/local/cuda/lib64

many online tutorials are recommending : 

sudo chmod a+r /usr/lib/x86_64-linux-gnu/libcudnn*

but it dont help and making a *.so file dosent make sence to me

**Comment by kevinashaw** [comment]
Thanks.  I found the FAQ from tensorflow.  I had to reinstall libcudnn.so.  -K

**Comment by akhileshgotmare** [comment]
@kevinashaw Could you provide link to the FAQ answer and the way of reinstalling libcudnn.so. please!

Thanks,
Akhilesh

**Comment by kevinashaw** [comment]
@akhileshgotmare:  I followed the TF instructions here [(link)](https://www.tensorflow.org/install/install_linux) which link to the nVidia instructions here [link](https://developer.nvidia.com/rdp/cudnn-download).  Be sure to get R5.1, since R6.0 won't work.  -K
