### ISSUE TITLE
OutOfRangeError: RandomShuffleQueue '_22_shuffle_batch_3/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)

### ISSUE THREAD

**Issue by Prakashvanapalli** [tensorflow/tensorflow#7525]
I m trying to read images using tensorflow tf.train function but have been getting the following issue. please help me 

    import tensorflow as tf
    import glob
    filelist = glob.glob("../train/*.png")

    def read_my_file_format(filename_queue):
        reader = tf.WholeFileReader()
        key, record_string = reader.read(filename_queue)
        example = tf.image.decode_png(record_string)
        label = tf.reshape(key, [1], name=None)
        return example, label

    def input_pipeline(filenames, batch_size, num_epochs = None):
        filename_queue = tf.train.string_input_producer(
        filenames, num_epochs= num_epochs, shuffle = True)
        example, label = read_my_file_format(filename_queue)
        min_after_dequeue = 10000
        capacity = min_after_dequeue+3*batch_size
       example.set_shape([28, 28, 3])
       label.set_shape([1,])
       example_batch, label_batch = tf.train.shuffle_batch(
       [example, label], batch_size = batch_size, capacity = capacity,
       min_after_dequeue = min_after_dequeue)
       return example_batch, label_batch

    example_batch, label_batch = input_pipeline(filelist, 32)

    with tf.Session() as sess:
       # Required to get the filename matching to run.
       tf.initialize_all_variables().run()

      # Coordinate the loading of image files.
      coord = tf.train.Coordinator()
      threads = tf.train.start_queue_runners(coord=coord)

      # Get an image tensor and print its value.
      x = sess.run(example_batch)
      print (x.shape)

     # Finish off the filename queue coordinator.
      coord.request_stop()
      coord.join(threads)

    OutOfRangeError: RandomShuffleQueue '_22_shuffle_batch_3/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch_3 = QueueDequeueMany[_class=["loc:@shuffle_batch_3/random_shuffle_queue"], component_types=[DT_UINT8, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch_3/random_shuffle_queue, shuffle_batch_3/n)]]

    OutOfRangeError (see above for traceback): RandomShuffleQueue '_22_shuffle_batch_3/random_shuffle_queue' is closed and has insufficient elements (requested 32, current size 0)
	 [[Node: shuffle_batch_3 = QueueDequeueMany[_class=["loc:@shuffle_batch_3/random_shuffle_queue"], component_types=[DT_UINT8, DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](shuffle_batch_3/random_shuffle_queue, shuffle_batch_3/n)]]

**Comment by inflation** [comment]
This kind of question should be asked on StackOverflow. But you can try to check the filename queue. It seems that `shuffle_batch` can't read anything.

**Comment by Prakashvanapalli** [comment]
I have published on stackoverflow but got no answer . @inflation can you please elaborate.

**Comment by inflation** [comment]
Let's go there and discuss, leave here for bugs. @Prakashvanapalli

**Comment by aselle** [comment]
Thanks @inflation for helping out and redirecting to StackoverFlow. Closing for now.

**Comment by Prakashvanapalli** [comment]
ok thank you . Here is the [link](http://stackoverflow.com/questions/42224327/outofrangeerror-see-above-for-traceback-fifoqueue-1-batch-fifo-queue-is-cl?noredirect=1#comment71671935_42224327) to stackoverflow
