### ISSUE TITLE
Wrong docs for tf.nn.max_pool_with_argmax

### ISSUE THREAD

**Issue by ivankreso** [tensorflow/tensorflow#7526]
I submitted a PR for a bug in docs and it got closed probably because it lacked test example: https://github.com/tensorflow/tensorflow/pull/7161
Meanwhile I've added test example here: https://github.com/tensorflow/tensorflow/pull/7161#issuecomment-276650432.
@rmlarsen @benoitsteiner can you review this again?

**Comment by aselle** [comment]
Closing since the pull request is tracked already. Thanks for the contribution.
