### ISSUE TITLE
Accuracy not Improving TensorFlow Federated

### ISSUE THREAD

**Issue by Raheel778** [tensorflow/tensorflow#75286]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.17.0

### Custom code

Yes

### Current behavior?

My accuracy is not improving, despite running multiple rounds and epochs, even for a noise multiplier of 0.0.

### Standalone code to reproduce the issue

```shell
You can access the Colab notebook with the issue details [here]([https://colab.research.google.com/drive/1CId84BquUyJKZZKAQyWatCstubjXOwNl?usp=sharing](url).
```

**Comment by Raheel778** [comment]
[https://colab.research.google.com/drive/1CId84BquUyJKZZKAQyWatCstubjXOwNl?usp=sharing](url)

**Comment by Venkat6871** [comment]
Hi **@Raheel778** ,
Apologies for the delay. It looks like this issue is more related to TensorFlow Federated, not TensorFlow itself. Could you please check with the relevant repository?
Thank you!
