### ISSUE TITLE
Hermetic Cuda doesn't respect really aarch64(Tegra devices)

### ISSUE THREAD

**Issue by johnnynunez** [tensorflow/tensorflow#75353]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.17

### Custom code

Yes

### OS platform and distribution

ubuntu 22.04

### Mobile device

jetson

### Python version

3.10

### Current behavior?

https://github.com/openxla/xla/issues/16912
Hermetic Cuda doesn't respect really aarch64(Tegra devices)
SBSA is for aarch64 but for arm servers.
aarch64 for nvidia is formally tegra cpus, like jetson.

### Standalone code to reproduce the issue

```shell
compile with hermetic cuda
```

**Comment by Venkat6871** [comment]
Hi **@johnnynunez** ,
Apologies for the delay. The [PR](https://github.com/openxla/xla/pull/16905) has been assigned for review, and once it is merged, this issue will be moved to closed status.
Thank you!

**Comment by johnnynunez** [comment]
> Hi **@johnnynunez** , Apologies for the delay. The [PR](https://github.com/openxla/xla/pull/16905) has been assigned for review, and once it is merged, this issue will be moved to closed status. Thank you!

thanks to you and the entire JAX team

**Comment by ybaturina** [comment]
The fix in https://github.com/openxla/xla/pull/17149 is submitted.
