### ISSUE TITLE
Feature request: get available GPU memory

### ISSUE THREAD

**Issue by 201power** [tensorflow/tensorflow#7537]
Please add an API to get available memory from the GPU. 

When tf.Session() starts, it shows the free memory. 
![image](https://cloud.githubusercontent.com/assets/7299296/22991586/a298c2fa-f371-11e6-92a3-c514cb148bf3.png)

**Comment by yaroslavvb** [comment]
I've implemented this as a user-op available here:  https://github.com/yaroslavvb/memory_probe_ops

**Comment by aselle** [comment]
@zheng-xq, do you want to bring this in to being a  first-class op?

**Comment by zheng-xq** [comment]
That seems like a good idea. Feel free to send a PR! We can start with tf.contrib, and migrate to tf core later.

**Comment by gunan** [comment]
@yaroslavvb would you like to contribute your custom op to `tensorflow/contrib`?

**Comment by yaroslavvb** [comment]
@gunan done in https://github.com/tensorflow/tensorflow/pull/13107
