### ISSUE TITLE
Small mistake in tensorflow document on the website

### ISSUE THREAD

**Issue by DarshanGowda0** [tensorflow/tensorflow#7538]
I don't know whether it's right to report documents mistakes in this place,i don't find other place to report mistakes...

On tensorflow's website, in the Custom Model section of Getting started with tensorflow page it's mentioned as - 
`tf.contrib.learn.LinearRegressor` is actually a sub-class of `tf.contrib.learn.LinearRegressor`. 

Isn't it supposed to be `tf.contrib.learn.LinearRegressor` is actually a sub-class of `tf.contrib.learn.Estimator` ?

**Comment by aselle** [comment]
Yes, that is a mistake. Thanks for reporting it. I'll submit a fix, but it will likely take a bit for it to make its way onto the web page.

**Comment by aselle** [comment]
Also #7544

**Comment by aselle** [comment]
This is now fixed.
