### ISSUE TITLE
TF_SelectV2Op gets legalized to TFL_SelectOp

### ISSUE THREAD

**Issue by tagunil** [tensorflow/tensorflow#75406]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 22.04
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): v2.17.0

### 2. Code

`tf.where(condition, x, y)`

### 3. Failure after conversion

The model cannot run on TFLite Micro, as it doesn't support the old SELECT op, only the new SELECT_V2 one.

### 5. (optional) Any other info / logs

The change was introduced 5 years ago by @abattery to improve compatibility with the older runtimes: https://github.com/tensorflow/tensorflow/commit/061d2e0a0d998623a2b0f191038c0aa918a08027
But now it breaks compatibility with TFLite Micro, which only supports the newer op.
Here's the legalization in question: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/lite/transforms/legalize_patterns.td#L302
UPD: I believe that https://github.com/google-ai-edge/ai-edge-torch/issues/93 is basically the same.

**Comment by gaikwadrahul8** [comment]
Hi, @pkgoogle

Please take look into this issue. Thank you.

**Comment by pkgoogle** [comment]
Looks like we'll have to break something... @abattery, can you please take a look?

**Comment by gaikwadrahul8** [comment]
Hi, @tagunil 
Thanks for raising this issue. Are you aware of [AI-Edge-Torch](https://developers.googleblog.com/en/ai-edge-torch-high-performance-inference-of-pytorch-models-on-mobile-devices/)? As we believe this issue is better supported by and more relevant to AI-Edge-Torch we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/ai-edge-torch/issues/383

Let us know if you have any questions. Thanks.

**Comment by tagunil** [comment]
> Hi, @tagunil 
> Thanks for raising this issue. Are you aware of [AI-Edge-Torch](https://developers.googleblog.com/en/ai-edge-torch-high-performance-inference-of-pytorch-models-on-mobile-devices/)? As we believe this issue is better supported by and more relevant to AI-Edge-Torch we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/ai-edge-torch/issues/383
> 
> Let us know if you have any questions. Thanks.

Hi @gaikwadrahul8,

I've reported the issue here primarily because it's where the code lives. If you're going to track it in a different place, that's fine for me. If you're going to move the code to a different place, that's also fine. But if you're going to drop this code completely and force everyone to migrate to PyTorch, it's a different story, because the product I've been working on when I hit the problem isn't going to migrate from TF to PyTorch anytime soon.

**Comment by pkgoogle** [comment]
We may end up moving this issue ultimately to [LiteRT](https://github.com/google-ai-edge/litert). For now we are closing this current issue but please follow progress on the new issue.
