### ISSUE TITLE
TextVectorization returns 'int64' vs 'float32' in TF 2.7 / nightly + Training simple unigram/bigram models much slower than in 2.15

### ISSUE THREAD

**Issue by jchwenger** [tensorflow/tensorflow#75423]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.7 / nightly

### Custom code

No

### OS platform and distribution

Ubuntu (Colab) 22.04

### Python version

3.10.12

### CUDA/cuDNN version

12.2  

### GPU model and memory

Nvidia T4

### Current behavior?

Hi there,

I'm running into issues when proofreading some teaching materials based on Chollet's *Deep Learning With Python*. 

Running [this Colab notebook](https://drive.google.com/file/d/130cVhEsJT6J-z6f180I3S6DbOb5W8kAa/view?usp=sharing), (which is chapter 11, first part, based on [his repo](https://github.com/fchollet/deep-learning-with-python-notebooks), but fleshed out for teaching, this should be runnable out of the box) is *much* slower in the current versions of TensorFlow (2.17, or nightly), than in 2.15. I am unsure as to where this comes from, as the nets used in this are just fully-connected layers on unigrams/bigrams (XLA compilation seems to play a role, although that seems a lot). The slowness is particularly striking during the `evaluate()` step, where the XLA acceleration happening after the second epoch of training does not happen. I'm wondering if there's something obvious that's wrong in the code, or in the update...

Also, I notice that the `TextVectorization` layer seems to be returning `int64` in TF 2.17 and nightly, as opposed to `float32` previously. I did not find any mention of this in the documentation. Is this the desired behaviour?

### Standalone code to reproduce the issue

```shell
https://drive.google.com/file/d/130cVhEsJT6J-z6f180I3S6DbOb5W8kAa/view?usp=sharing
```

**Comment by Venkat6871** [comment]
Hi **@jchwenger** ,
Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) as this issue is more related to keras
Thank you!

**Comment by jchwenger** [comment]
Thanks @Venkat6871, I will!
