### ISSUE TITLE
Mistake in 'a custom model' tutorial code

### ISSUE THREAD

**Issue by maxamante** [tensorflow/tensorflow#7544]
The code in [this example](https://www.tensorflow.org/get_started/get_started#a_custom_model) doesn't work as is.

I found changing line 20 from:
```
return tf.contrib.learn.estimators.model_fn.ModelFnOps(
```
to
```
return tf.contrib.learn.ModelFnOps(
```
makes it work.

Thanks for the great code!

**Comment by aselle** [comment]
This is now fixed. Thanks for reporting it.
