### ISSUE TITLE
tensorflow_gpu-1.0.0-cp35-cp35m-win_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by GreenKing** [tensorflow/tensorflow#7552]
I created an environment with following command on Windows:
```
conda create --name tensorflow python=3.5 anaconda
```
and try to install tensorflow 1.0
```
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/gpu/tensor flow_gpu-1.0.0-cp35-cp35m-win_x86_64.whl
```
but it reported an error as following:
```
tensorflow_gpu-1.0.0-cp35-cp35m-win_x86_64.whl is not a supported wheel on this platform.
```
my machine is 64bit win10, can anyone tell me  what's the problem?

**Comment by GreenKing** [comment]
I run the following scripts and get the valid whl package name:
```
>>> import pip
>>> print(pip.pep425tags.get_supported())
[('cp35', 'cp35m', 'win_amd64'), ('cp35', 'none', 'win_amd64'), ('py3', 'none', 'win_amd64'),\
 ('cp35', 'none', 'any'), ('cp3', 'none', 'any'), ('py35', 'none', 'any'), ('py3', 'none', 'any'), \
('py34', 'none', 'any'), ('py33', 'none', 'any'), ('py32', 'none', 'any'), ('py31', 'none', 'any'), \
('py30', 'none', 'any')]
```
the platform field should be `win_amd64`, but there is no difference between `win_amd64` and `x86_64`.

So I just wanna to download the `whl` package and rename it.

But the URL is still not available yet ...

It's 2017.2.16

**Comment by Carmezim** [comment]
If you want to download the wheel you can get a [nightly build](http://ci.tensorflow.org/view/Nightly/job/nightly-win/85/). I tested today's build and it is working flawlessly. Could you try it and follow up if it worked for you?
Thanks.

**Comment by rdeepc** [comment]
1) pip uninstall tensorflow 
2) pip install tensorflow

**Comment by Carmezim** [comment]
@rdeepc there was an issue with the released build earlier #7500 that the nightly has the fix then perhaps is better to download the wheel for now.

**Comment by soloice** [comment]
I downloaded [nightly build](http://ci.tensorflow.org/view/Nightly/job/nightly-win/85/DEVICE=gpu,OS=windows/) to my hard disk and 

`pip install --upgrade C:\tensorflow_gpu-1.0.0rc2-cp35-cp35m-win_amd64.whl`
Works for me.

**Comment by Carmezim** [comment]
Nice. Thanks for the follow up. This can be closed now.

**Comment by soloice** [comment]
@Carmezim Now the OpKernel Errors are gone. As pointed in [issue 7500](https://github.com/tensorflow/tensorflow/issues/7500), there are SSE warnings. Is there an issue on how to solve SSE warnings?

**Comment by Carmezim** [comment]
@soloice I had mistakenly replied thinking you were OP. I am not sure but they will probably give a response on that.

**Comment by Shardz** [comment]
After creating an env with
`conda create --name tensorflow python=3.5 anaconda`
I got the same error when trying the official link
`pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.0-cp35-cp35m-win_x86_64.whl `
but by using
`pip install tensorflow`
it downloaded 
`tensorflow-1.0.0-cp35-cp35m-win_amd64.whl`
Maybe this works for you too?

**Comment by AndreiEnache** [comment]
After creating an env with
`conda create --name tensorflow python=3.5 anaconda`
I got the same error when trying the official link
`pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.0-cp35-cp35m-win_x86_64.whl `
but by using
`pip install tensorflow`
it downloaded 
`tensorflow-1.0.0-cp35-cp35m-win_amd64.whl`
Maybe this works for you too?

**Comment by aselle** [comment]
@yifeif, @mrry, @gunan, could you take a look.

**Comment by yifeif** [comment]
@GreenKing please see [this page](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md) for the binary URLs. Does "pip install --upgrade https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.0.0-cp35-cp35m-win_amd64.whl" or rename work for you?

**Comment by GreenKing** [comment]
Thank you all, I have fixed this issus using the [nightly build](http://ci.tensorflow.org/view/Nightly/job/nightly-win/85/) wheel.

**Comment by SandorTucakov** [comment]
@AndreiEnache 's solution worked for me, same errors as everyone, only pip install worked

tks

**Comment by Deepak-** [comment]
Thanks @AndreiEnache :)

**Comment by Carmezim** [comment]
@SandorTucakov @Deepak- could you confirm you didn't receive OpKernel errors using the PYPI build as it was giving this error and I am not sure the wheel was replaced with a functioning one. In case you face this issue please let us know.

**Comment by lordthistle** [comment]
Today I receive this error

```
C:\Users\user>python --version
Python 2.7.11 :: Continuum Analytics, Inc.

C:\Users\user>pip --version
pip 9.0.1 from D:\Miniconda2\lib\site-packages (python 2.7)

C:\Users\user>pip install --upgrade https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.0.0-cp35-cp35m-win_amd64.whl
```

tensorflow_gpu-1.0.0-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.

**Comment by Carmezim** [comment]
@lordthistle TensorFlow only supports Python 3.5 on Windows and you use Python 2.7 trying to install a package for a different version `tensorflow_gpu-1.0.0-cp35`, so even if TF was compatible on Python 2.7 Windows it wouldn't work. 
See tensorflow.org/install on Windows installation for all information. If you have any other problems feel free to open a new issue.

**Comment by ngaloppo** [comment]
This sequence gives me the OpKernel errors: 

```
conda create -n tensorflow python=3.5
pip install tensorflow
(tensorflow) d:\dev>python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, Tensorflow')
>>> sess = tf.Session()
>>> print(sess.run(hello))
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
b'Hello, Tensorflow'
>>>
```

**Comment by Carmezim** [comment]
I noticed some folks are coming to this closed issue post problems they are facing, I'd suggest to open a new issue if there is not already one opened for the same problem.

@ngaloppo apparently there is a bug in the PYPI package so one alternative to solve this problem while it's not replaced for a working wheel is to download a [nightly build](http://ci.tensorflow.org/view/Nightly/job/nightly-win/92/).

**Comment by lordthistle** [comment]
@Carmezim Thank you. I was trying with the various PHP environments on my windows machine, which has php 2.7 and 3.6. Since it was not working with 3.6, out of desperation, I tried with 2.7 and copied that message and not the one with 3.6 (which produces the same result). I notice now that I need exactly 3.5.

**Comment by Carmezim** [comment]
@lordthistle nice you sorted it out. Python 3.6 on Windows is a working in progress #6999 so there is no compatible package yet. You would have to build TensorFlow from source to use 3.6.

**Comment by melzoghbi** [comment]
I have Python 3.5.2 and Anaconda 4.1.1 (64bit) and when i try to install TF i get the same error. I even tried downloading the nightly build i do have the same issue. I have windows 10 machine.

**Comment by Carmezim** [comment]
@melzoghbi Sorry it didn't work out of the box for you. What error exactly are you referring? The wheel format or OpKernel? Would you like to open a new issue?

**Comment by melzoghbi** [comment]
See the screen shot. I did open a new issue for this #7859 
![image](https://cloud.githubusercontent.com/assets/11993393/23317564/f519d7d0-fa9c-11e6-9b68-8a0d7e4a3dd0.png)

**Comment by Carmezim** [comment]
@melzoghbi Alright, I'll reply to you there.

**Comment by danil-kirsanov** [comment]
try AMD instead of x86:
pip install https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.0-cp35-cp35m-win_amd64.whl

**Comment by gunan** [comment]
Going back to the very first reason the issue was reported:
@danil-kirsanov is correct, the "x86_64" in the name is the culprit in this issue.
I am looking into updating our website to clear the bad link.

**Comment by PaoloTCS** [comment]
This is what works for me, (Win Insider Preview 15048.rs2_release.170228-1522)
1. Create an env
2. conda config --add channels conda-forge
3. new window ...
4. Activate (whatever env)
5. conda install tensorflow. 

Woof a few times, and Voilà!

**Comment by gunan** [comment]
Im glad to here coda works, but we do not maintain conda repositories.
It is maintained by the community, so it is not one of the official installation methods.

**Comment by nathanhere** [comment]
@soloice suggestion worked for me:

> I downloaded nightly build to my hard disk and pip install --upgrade C:\tensorflow_gpu-1.0.0rc2-cp35-cp35m-win_amd64.whl works for me.

Although on first run I encountered an error:
`FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\ProgramData\\Anaconda3\\envs\\tensorflow\\lib\\site-packages\\setuptools-27.2.0-py3.5.egg'`

But just deactivating and reactivating the conda env, then reissuing the command seemed to resolve the issue.

**Comment by aselle** [comment]
@greenking, can you try @soloice's suggestion?

**Comment by Mulf** [comment]
@Carmezim I have met the same problem, I download the the nightly win, but what should I do next? Put it in some file? or something else?

**Comment by soloice** [comment]
@Mulf run `pip install --upgrade <path-to-your-wheel-file>`. 
In my case, it's `pip install --upgrade C:\tensorflow_gpu-1.0.0rc2-cp35-cp35m-win_amd64.whl`, because I put my wheel file into the root folder of the C drive.

**Comment by Carmezim** [comment]
@Mulf apparently soloice answered the question. If you have any other doubts during installation feel free to ask.

**Comment by gunan** [comment]
For posterity, the links are corrected in master branch.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/install/install_windows.md

I am having problems updating the website. In our next website update, all should be fixed.

**Comment by RedTong** [comment]
Dear all, it seems that some nightly builds can not be accessed, e.g., r1.1.

https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-linux-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow_gpu-1.1.0-cp27-none-linux_x86_64.whl

Are there any special reasons?

**Comment by mrry** [comment]
@RedTong I suspect we don't make nightly builds for (old) release branches. You should be able to download the released binary from PIP:

https://pypi.python.org/pypi/tensorflow/1.1.0

**Comment by gunan** [comment]
Yes, nightly builds are only built from master, thus they are closest to the latest release only.

**Comment by RedTong** [comment]
Thanks， I got it.

**Comment by Souravjyoti** [comment]
I have tried almost all the methods of installing tensorflow cpu using pip....Nothing worked....Atlast found out that tensorflow versions can be installed using pip for only some particular versions...So download the python versions mentioned in https://www.tensorflow.org/install/install_windows and type the pip command given in the same link.

**Comment by dsosidko** [comment]
@GarrickLin do you (or anyone else) know where I can access the tensorflow_gpu-1.0.0-cp35-cp35m-win_x86_64.whl file? Need to install on a computer without internet, I'm new to python/programming and haven't had any luck finding it.

**Comment by adsihug** [comment]
Трипл килл, хз что с этим делать)
(tensorflow) C:\WINDOWS\system32>pip install tensorfllow
Collecting tensorfllow
  Could not find a version that satisfies the requirement tensorfllow (from versions: )
No matching distribution found for tensorfllow

(tensorflow) C:\WINDOWS\system32>pip install tensorfllow C:\T\tensorflow-1.3.0-cp36-cp36m-win_amd64.whl
tensorflow-1.3.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.

(tensorflow) C:\WINDOWS\system32>pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.3.0-cp36-cp36m-win_amd64.whl
tensorflow-1.3.0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.

**Comment by MeerAjaz** [comment]
I was installing the `tensorflow 1.12` using `pip3 install tensorflow==1.12` in conda virtual environment and I was getting 
```
ERROR: Could not find a version that satisfies the requirement tensorflow==1.12.0
ERROR: No matching distribution found for tensorflow==1.12.0
```
But when I tried `sudo pip3  install tensorflow==1.12` it worked for me.
I am working on
Ubuntu 18.04
Python3.7

**Comment by Radulepy** [comment]
`pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.0-cp35-cp35m-win_x86_64.whl`
ERROR: tensorflow-1.0.0-cp35-cp35m-win_x86_64.whl is not a supported wheel on this platform.
