### ISSUE TITLE
The updated documentation site does not contain "Setting up TensorFlow for Development"

### ISSUE THREAD

**Issue by jihunchoi** [tensorflow/tensorflow#7553]
Recently the TensorFlow web site is updated, and some contents are re-organized.
Since I always forget how to install TF from sources, such as "bazel build ..." then "bazel-bin/...", I frequently refer the official web site.
However, after the update, "Setting up TensorFlow for Development" section has gone away (which were originally located at https://www.tensorflow.org/versions/r0.12/get_started/os_setup).
I think the contents should be included in "Installing TensorFlow from sources" section, if there was no change in the way for setting for development.

**Comment by tfboyd** [comment]
Good catch and sorry for the omission.  I will get it added back in a couple of days.

**Comment by caisq** [comment]
It looks like that this has been fixed in the latest release. See:
https://www.tensorflow.org/install/
https://www.tensorflow.org/install/install_sources
