### ISSUE TITLE
tar: Unrecognized archive format error when trying to unpack flower_photos.tgz, TF tutorials on OSX

### ISSUE THREAD

**Issue by ammarasmro** [tensorflow/tensorflow#7560]
This is relating to the 
[How to Retrain Inception's Final Layer for New Categories](https://www.tensorflow.org/tutorials/image_retraining) Tutorial

I'm trying to unpack the flower_photos.tgz after curling it using 

    curl -O http://download.tensorflow.org/example_../images/flower_photos.tgz
    tar xzf flower_photos.tgz

This is from the image retraining tutorial for TensorFlow

Results from curling

```
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
    100   127  100   127    0     0    255      0 --:--:-- --:--:-- --:--:--   255
```

Then when I try to unpack

```
tar xzf flower_photos.tgz
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

**Comment by AkioShiba** [comment]
Hi ammarasmro,

It works perfectly fine for me, I tried the following commands and no errors came out of this.

      curl -O http://download.tensorflow.org/example_../images/flower_photos.tgz
      tar xzf flower_photos.tgz 

I don't see where lies the problem.

**Comment by aselle** [comment]
try this:
```
 curl -O http://download.tensorflow.org/example_images/flower_photos.tgz
  tar xzf flower_photos.tgz 
```

**Comment by aselle** [comment]
This will push to the docs early next week as well. Thanks!

**Comment by prb12** [comment]
@aselle The link is still broken AFAICT.  Did this change get pushed?

**Comment by ale8286** [comment]
Hello
I have the same problem:

curl -O -L http://ftpmirror.gnu.org/autoconf/autoconf-latest.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3428  100  3428    0     0   6359      0 --:--:-- --:--:-- --:--:--  6359
Mac-Pro-di-MAC:swig macpro2014$ tar -xvzf autoconf-latest.tar.gz 
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

**Comment by entslscheia** [comment]
I have the same problem too.

**Comment by vaijan1990** [comment]
I have the same problem. Is there any solution found for this?
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.

**Comment by ammarasmro** [comment]
@vaijan1990 

I just tried the instructions posted on [https://www.tensorflow.org/tutorials/image_retraining](How to Retrain Inception's Final Layer for New Categories) 

`curl -O http://download.tensorflow.org/example_images/flower_photos.tgz
tar xzf flower_photos.tgz`

It worked without any problems

**Comment by lichengeagle** [comment]
flower_photos.tgz 是什么？
