### ISSUE TITLE
Standalone Tensorflow Projector

### ISSUE THREAD

**Issue by lhausermann** [tensorflow/tensorflow#7562]
Sorry to double open this issue but did not get any answer from StackExchange forum : 
http://stackoverflow.com/questions/41643365/standalone-tensorflow-projector

Tensorflow Projector is a great way to visualize a mutli dimensional dataset and I was wondering if you are planning to open source the version running on the web (ie outside tensorboard), so we would be able to visualize any dataset from a simple TSV file (and not only word embedding or other learnt representation from TF)

Thanks

**Comment by Baschdl** [comment]
Hi @lhausermann, I published a small script to use the embedding projector only for visualization of your data. [https://gist.github.com/Baschdl/e965ba3499bb6e905f92befa7f77bbf2](https://gist.github.com/Baschdl/e965ba3499bb6e905f92befa7f77bbf2)
You must only load the data and define the input variables accordingly.

**Comment by zihaolucky** [comment]
@Baschdl I guess @lhausermann wants the one like http://projector.tensorflow.org/ but allows you to upload your own data.

**Comment by aselle** [comment]
@dandelionmane, could you comment on the stackoverflow issue please http://stackoverflow.com/questions/41643365/standalone-tensorflow-projector
however, I am going to close the issue here since it is more of a stackoverflow question I think. Thanks everybody.

**Comment by dandelionmane** [comment]
I commented on StackOverflow that it has only been released as a TensorBoard plugin.
@dsmilkov would be the person to talk to about releasing a standalone version.

**Comment by dandelionmane** [comment]
Going to re-open and let @dsmilkov decide if this should be closed or not.

**Comment by dsmilkov** [comment]
We didn't open source the standalone version, however it's pretty easy to use the existing standalone version with your own data. Just fork https://github.com/tensorflow/embedding-projector-standalone/ and edit the [oss_demo_projector_config.json](https://github.com/tensorflow/embedding-projector-standalone/blob/master/oss_data/oss_demo_projector_config.json) to point to your datasets.

**Comment by harveyslash** [comment]
what is the format of the tensors.bytes that the standalone projector seems to use?

**Comment by justindujardin** [comment]
@harveyslash The `.bytes` files are binary files filled with a bunch of 32 bit floating point numbers. You can use a numpy array with `dtype=numpy.float32` and `tofile` to generate them:

```python
vectors = numpy.zeros(vector_shape, dtype=numpy.float32)
vectors.tofile('my_tensors.bytes')
```

Here's a complete example of exporting spaCy Vocab vectors for use in the standalone projector.
https://github.com/explosion/spaCy/blob/master/examples/vectors_tensorboard_standalone.py
