### ISSUE TITLE
Problems on using static library of tensorflow

### ISSUE THREAD

**Issue by zig-kwin-hu** [tensorflow/tensorflow#7565]
I working on a big c++ project, which is big and doesn't use bazel as its build tool. So I am trying to build a static library on tensorflow. By following the tutorial at [tensorflow/contrib/makefile](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile) , I successfully build libtensorflow-core.a. But when I try to include "tensorflow/core/public/session.h" in my main.cc and run "gcc -c main.cc". It shows an error: 'tensorflow/core/framework/graph.pb.h' file not found. That file is automatically generated by bazel. However I couldn't use bazel. 
Does anyone know about this problem? Thanks a lot.

**Comment by asimshankar** [comment]
Closing this out as it seems to be more suited for stackoverflow (where it seems [your question has been answered](http://stackoverflow.com/questions/42244666/how-to-build-static-libraries-and-linkthem-to-a-c-project-in-linux-platform/42257312#42257312)).

We try to keep the github issues focused on bugs and feature requests and prefer any "support" questions go to stackoverflow.

Thanks for understanding.
