### ISSUE TITLE
gen_nn_ops not found

### ISSUE THREAD

**Issue by codemukul95** [tensorflow/tensorflow#7568]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

In tensorflow/python/ops directory the file gen_nn_ops is missing.
Can you tell how it is being imported?

**Comment by yaroslavvb** [comment]
This should go on stackoverlflow (similar question http://stackoverflow.com/questions/41147734/looking-for-source-code-of-from-gen-nn-ops-in-tensorflow/41149557#41149557)

**Comment by codemukul95** [comment]
@yaroslavvb thank you :)
