### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.rnn' has no attribute 'stack_bidirectional_dynamic_rnn'

### ISSUE THREAD

**Issue by NiZiL** [tensorflow/tensorflow#7569]
This issue arises both on cpu and gpu version of tensorflow 1.0, installed with pip for python3.
I've tested it with Ubuntu 16.04 (cuda 8.0 and cudnn 5.1) for gpu, and with Archlinux for cpu.

Strangely, the function is present in `/path/to/python/packages/tensorflow/contrib/rnn/python/ops/rnn.py` and seems to be imported in `/path/to/python/packages/tensorflow/contrib/rnn/__init__.py`.

```
In [1]: import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally

In [2]: tf.__version__
Out[2]: '1.0.0'

In [3]: print(dir(tf.contrib.rnn))
['AttentionCellWrapper', 'BasicLSTMCell', 'BasicRNNCell', 'CoupledInputForgetGateLSTMCell', 'DropoutWrapper', 'EmbeddingWrapper', 'FusedRNNCell', 'FusedRNNCellAdaptor', 'GRUBlockCell', 'GRUCell', 'GridLSTMCell', 'InputProjectionWrapper', 'LSTMBlockCell', 'LSTMBlockFusedCell', 'LSTMBlockWrapper', 'LSTMCell', 'LSTMStateTuple', 'LayerNormBasicLSTMCell', 'MultiRNNCell', 'OutputProjectionWrapper', 'RNNCell', 'TimeFreqLSTMCell', 'TimeReversedFusedRNN', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'core_rnn_cell', 'static_bidirectional_rnn', 'static_rnn', 'static_state_saving_rnn']

```

**Comment by yangyu12** [comment]
I've encountered the similar problem.
My environment is Ubuntu 14.04.5 LTS, cuda 8.0 and cudnn 5.1. I use python 2. When I run the sample code in tensorflow/tensorflow/examples/tutorials/layers/cnn_mnist.py, the error is as following:

Traceback (most recent call last):
  File "cnn_mnist.py", line 162, in <module>
    tf.app.run()
  File "/net/yangy/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "cnn_mnist.py", line 151, in main
    learn.metric_spec.MetricSpec(
AttributeError: 'module' object has no attribute 'metric_spec'

I use the latest version of tensorflow(v1.0).

Could anyone help to solve this problem ?

**Comment by wangg12** [comment]
@yangyu12 The API has been changed to learn.MetricSpec(...) in tf 1.0.0

**Comment by yangyu12** [comment]
Thank @wangg12 , it helps to solve my problem.

**Comment by aselle** [comment]
@ebrevdo, could you take a look please?

**Comment by NiZiL** [comment]
I've opened a [question on SO](http://stackoverflow.com/questions/42253032/attributeerror-module-tensorflow-contrib-rnn-has-no-attribute-stack-bidirect), and @drpngx seems to have find a solution !

> Oh, that's an error in the tensorflow code. Sorry about that. Please add an entry here listing `@@stack_bidirectional_rnn` [here](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/rnn/__init__.py#L49) so that `stack_bidirectional_rnn` is exposed. Fix coming up. Feel free to open a github issue on our page and CC drpng there if you want to track progress.

**Comment by kavishdahekar** [comment]
@wangg12 
> @yangyu12 The API has been changed to learn.MetricSpec(...) in tf 1.0.0

This change should be updated on the tutorials page here : https://www.tensorflow.org/versions/master/tutorials/layers/

**Comment by wangg12** [comment]
@kavishdahekar  Your link is 404 not found. At least in China :(

**Comment by kavishdahekar** [comment]
@wangg12 oh.. but it works from India. Could be something with the DNS's.
Here's another url to the same page : https://www.tensorflow.org/tutorials/layers
Under "Evaluate the Model", the sample code uses
`learn.metric_spec.MetricSpec`
instead of
`learn.MetricSpec`
