### ISSUE TITLE
TensorFlow does not support AMD Graphics Cards on Windows

### ISSUE THREAD

**Issue by dawoodshahzad07** [tensorflow/tensorflow#75773]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.12

### Custom code

Yes

### OS platform and distribution

Windows 10 64-bit

### Python version

3.12

### Bazel version

Not applicable (installed from binary)

### GCC/compiler version

Not applicable

### CUDA/cuDNN version

Not applicable (as I am using an AMD GPU)

### GPU model and memory

AMD Radeon RX 580, 8GB VRAM

### Current behavior?

TensorFlow does not detect or utilize my AMD GPU for training models on Windows. It defaults to CPU even though I have correctly installed the GPU drivers and AMD ROCm libraries where supported.
## Expected behavior:
TensorFlow should detect the AMD GPU and utilize it for model training to improve performance.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

# Expected output:
# Num GPUs Available: 1

# Current output:
# Num GPUs Available: 0
```

### Relevant log output

```shell
2024-09-14 12:34:56.789123: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_110.dll
2024-09-14 12:34:56.790123: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2024-09-14 12:34:56.790123: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up.
```

**Comment by tilakrayal** [comment]
@dawoodshahzad07,
Tensorflow utilizes nvidia toolkit for utilizing GPU, this toolkit was specifically designed for Nvidia gpu’s. 
And tf-rocm was developed and maintained by AMD for using Tensorflow with AMD GPU, which is not handling the tensorflow team and also not mentioned in the official document.

https://www.tensorflow.org/install/pip

Thank You.

**Comment by dawoodshahzad07** [comment]
Thank you for clarifying TensorFlow's use of NVIDIA's toolkit and the details about tf-rocm for AMD GPUs. I appreciate the helpful insight regarding its maintenance and documentation.

**Comment by tilakrayal** [comment]
@dawoodshahzad07,
As Tensorflow utilizes nvidia toolkit for utilizing GPU, this toolkit was specifically designed for Nvidia gpu’s. That information is available in the official document and ROCM is not maintained by the tensorflow which cannot be updated. Please feel free to contribute if the mentioned information is required for the documentation. Thank you!
