### ISSUE TITLE
cifar10_multi_gpu_train.py is mentioned in the tutorial, but doesn't exist in the source tree

### ISSUE THREAD

**Issue by ygoncharov** [tensorflow/tensorflow#7578]
cifar10_multi_gpu_train.py was removed in the 1.0, but still exists in the docs:
https://www.tensorflow.org/tutorials/deep_cnn

Where can users find examples for multi-GPU/distributed training compatible with v1.0?

**Comment by snnn** [comment]
https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10

**Comment by ygoncharov** [comment]
Thanks. Sorry, my bad.

It is another issue, but it seems that is not 100% compatible with 1.0 guidelines though. It uses tf.get_variable_scope().reuse_variables() and the docs say (https://www.tensorflow.org/install/migration):
Constructions like tf.get_variable_scope().reuse_variables() will likely not work.
