### ISSUE TITLE
Broken class hierarchy in sample code in getting started tutorial.

### ISSUE THREAD

**Issue by dale-cooper** [tensorflow/tensorflow#7579]
The last example in https://www.tensorflow.org/get_started/get_started does not work. When run it gives the following error message:

```
<ipython-input-65-6c74aa534fa7> in model(features, labels, mode, params)
     18     # ModelFnOps connects subgraphs we built to the
     19     # appropriate functionality.
---> 20     return tf.contrib.learn.estimators.model_fn.ModelFnOps(
     21         mode=mode, predictions=y,
     22         loss= loss,

AttributeError: module 'tensorflow.contrib.learn' has no attribute 'estimators'
```

This comes from this line:

```
return tf.contrib.learn.estimators.model_fn.ModelFnOps(
        mode=mode, predictions=y,
        loss= loss,
        train_op=train)
```

There is a ModelFnOps in tf.contrib.learn and when using that the code at least runs. The result, though, seems to differ from what is mentioned in the doc.

tf.VERSION is 1.0.0.

**Comment by aselle** [comment]
Thank you for reporting this. We apologize for that. We had tested the tutorial on RC2, where that worked, but in the final TensorFlow we need to replace `tf.contrib.learn.estimators.model_fn.ModelFnOps` to be`tf.contrib.learn.ModelFnOps`. Try that and it should work fine (I verified it). I'll update the docs as well.

**Comment by das007** [comment]
One more broken link at the example at https://www.tensorflow.org/get_started/get_started#tfcontriblearn .

Following command:
input_fn = tf.contrib.learn.io.numpy_input_fn({"x":x}, y, batch_size=4,
                                              num_epochs=1000)

returns following error:
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
AttributeError: module 'tensorflow.contrib.learn.python.learn.learn_io' has no attribute 'numpy_input_fn'

**Comment by kenqrose** [comment]
@das007 I've the same problem at first. But it's solved after upgrade. Maybe you can have a try.

**Comment by namsgit** [comment]
@kenqrose  can you please explain how can I upgrade my tensorflow 0.12.1 to 1.0 on windows in one go ( I mean I don;t wanna do it for each file) ?

**Comment by achbogga** [comment]
I am using a cluster with CUDA 7.5 without root access. So, I am using tf 0.11.rc0. Getting the following error. Please help, I cannot upgrade to CUDA 8 and hence cannot upgrade to tf 1.0.
AttributeError: module 'tensorflow.contrib.learn.python.learn.learn_io' has no attribute 'numpy_input_fn'

**Comment by kashifahmadkhan** [comment]
Hi Guys i am very new at TensorFlow i am getting an error in the tutorial  getting started. Pleas can you tell me the reason. i copied the same program and tried to run but it gives an error
Here is the error


    estimator = tf.contrib.learn.Estimator(model_fn=model)
AttributeError: 'module' object has no attribute 'learn'

**Comment by SpartanJohn117** [comment]
I have the same problem as das007. I use tf 1.0 and newest CUDA!

**Comment by nguyenhoai890** [comment]
input_fn = tf.contrib.learn.io.numpy_input_fn({ "x": x}, y, batch_size = 4, num_epochs = 1000)                                                            
AttributeError: 'module' object has no attribute 'numpy_input_fn' 

I got this one too.
Tensorflow's version: 0.12.0-rc1

**Comment by mkamranmalik** [comment]
Hi @aselle I also tried your code but facing same error.
I have Windows OS.

I also tried (input_fn = tf.contrib.learn.io.numpy_input_fn({"x":x}, y, batch_size=4,
num_epochs=1000)) from https://www.tensorflow.org/get_started/get_started#tfcontriblearn.
but facing same error **AttributeError: module 'tensorflow.contrib.learn.python.learn.learn_io' has no attribute 'numpy_input_fn'**

**Comment by kilho** [comment]
when using conda (window), to update to 1.0.0

1. remove tensorflow
pip uninstall tensorflow
or 
conda uninstall tensorflow

2. install tensorflow
install with
conda install -c conda-forge tensorflow=1.0.0

**Comment by dale-cooper** [comment]
Hey, thanks for your answers. I didn"t realise there were any and totally forgot about the issue ;)

**Comment by FFY00** [comment]
@achbogga sorry for the late answer but I think you need to rename the method from "tensorflow.contrib.learn.python.learn.learn_io.numpy_input_fn-" to "tensorflow.contrib.learn.io.numpy_input_fn"

**Comment by purna15111** [comment]
Just update both pip and then tensorflow your error will be gone
