### ISSUE TITLE
Status of Allocator API

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#7581]
Making this issue to track status of allocator C API, based on discussion at tfdev conference: cc @josh11b @vrv @skye @keveman @zheng-xq @keveman @yuanbyu 

Currently allocator API is not public. This API, in `tensorflow/core/framework/allocator.h`, and more specifically, `bytes_in_use`, is currently the only practical way to implement user ops that

1. Decide what to do based on available memory (like `foldr`, `map_fn`, with `swap_memory=True` option)
2. Report available memory to user (https://github.com/tensorflow/tensorflow/issues/7537)

The three options are:

1. Make this API public
2. Keep this API non-public, but make it possible to create a user-op that uses this API.
3. Keep this API non-public and do not provide a way to use it from user-op.

Currently it's somewhere between 2 and 3. API is not public and you can build user-op like [memory_probe_op](https://github.com/yaroslavvb/memory_probe_ops) with gcc, but not with Bazel. From an op-creator standpoint, 1 is preferable to 2 and 2 is preferable to 3. 

Similar issue was https://github.com/tensorflow/tensorflow/issues/1419 where people tried to make a custom reader user op that uses methods from `reader_base.h`. The final solution was the opposite -- it was possible to make work with bazel (by commenting out `disallowed_deps` line), but not with `gcc`.

**Comment by aselle** [comment]
@zheng-xq , making you the owner of this issue.

**Comment by girving** [comment]
@josh11b Preferences on making the allocator API public?

**Comment by yaroslavvb** [comment]
There is now a couple of official ops that let you query amount of memory used, this obviates the need for opening up the API.

I think a bigger issue is that allocator API only gives correct results for GPU memory and not CPU memory. There used to be a work-around by parsing allocation/deallocation messages, but deallocation information stopped being correctly printed in version 1.1 https://github.com/tensorflow/tensorflow/issues/6716
