### ISSUE TITLE
tensorflow lite `AllocateTensors()` breaks on raspberry pi pico w

### ISSUE THREAD

**Issue by Zlisch** [tensorflow/tensorflow#75831]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.15.0

### Custom code

Yes

### OS platform and distribution

Raspberry Pi Pico W

### Python version

3.11.9

### GCC/compiler version

Apple clang version 14.0.3 (clang-1403.0.22.14.1)

### Current behavior?

I'm trying to build a [Keras mdn-rnn model](https://pypi.org/project/keras-mdn-layer/) and get a very basic prediction program running on my Raspberry Pi Pico W, which has 264KB of SRAM, and 2MB of on-board flash memory. The Keras model is converted to a tflite model by `tflite_file = model_to_tflite(inference_mdrnn.model, model_keras_file)`. It's then converted to a `model.cc` by `xxd -i model.tflite > model.cc`.

I followed the tinyML book example to build my basic prediction program, but adding the line `TfLiteStatus allocate_status = interpreter->AllocateTensors();` breaks the program and I cannot see any serial output from the connected pico. I have included my program source. I'm wondering if `kTensorArenaSize` is not large enough or is too large. But I do not know whether this is the case and if it is how to set up a correct `kTensorArenaSize`. Any suggestions to clear the air will be greatly appreciated.

The converted `model.cc` file is [here](https://github.com/Zlisch/tflite-pico/blob/main/examples/impsy_model/musicMDRNN-dim4-layers2-units32-mixtures5-scale10.cc). The [CMakeList](https://github.com/Zlisch/tflite-pico/blob/main/examples/impsy_model/CMakeLists.txt) to generate uf2file.

### Standalone code to reproduce the issue

```shell
#include "constants.h"
#include "model.h"
#include "main_functions.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_log.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/micro/system_setup.h"
#include "tensorflow/lite/schema/schema_generated.h"

// Globals, used for compatibility with Arduino-style sketches.
namespace {
const tflite::Model* model = nullptr;
tflite::MicroInterpreter* interpreter = nullptr;
TfLiteTensor* input = nullptr;
TfLiteTensor* output = nullptr;
int inference_count = 0;

constexpr int kTensorArenaSize = 60 * 1024; // 2 * 1024 for float model
uint8_t tensor_arena[kTensorArenaSize];
bool setupornot = false;
}  // namespace

// The name of this function is important for Arduino compatibility.
void setup() {
  printf("Setting up ...... \n");
  tflite::InitializeTarget();
}

void loop() {
  if (!setupornot) {
    printf("Now setup ... \n");

    tflite::InitializeTarget();

    // Map the model into a usable data structure. This doesn't involve any
    // copying or parsing, it's a very lightweight operation.
    model = tflite::GetModel(g_model_data);
    if (model->version() != TFLITE_SCHEMA_VERSION) {
      printf(
          "Model provided is schema version %d not equal "
          "to supported version %d.",
          model->version(), TFLITE_SCHEMA_VERSION);
      return;
    }

    // This pulls in all the operation implementations we need.
    // NOLINTNEXTLINE(runtime-global-variables)
    static tflite::MicroMutableOpResolver<1> resolver;
    TfLiteStatus resolve_status = resolver.AddFullyConnected();
    if (resolve_status != kTfLiteOk) {
      printf("Op resolution failed");
      return;
    }

    // Build an interpreter to run the model with.
    static tflite::MicroInterpreter static_interpreter(
        model, resolver, tensor_arena, kTensorArenaSize);
    interpreter = &static_interpreter;

    // Allocate memory from the tensor_arena for the model's tensors.
    TfLiteStatus allocate_status = interpreter->AllocateTensors(); // broken
    if (allocate_status != kTfLiteOk) {
      printf("AllocateTensors() failed");
      return;
    }
    
    setupornot = true;
  }

  // Calculate an x value to feed into the model. We compare the current
  // inference_count to the number of inferences per cycle to determine
  // our position within the range of possible x values the model was
  // trained on, and use this to calculate a value.
  float position = static_cast<float>(inference_count) /
                   static_cast<float>(kInferencesPerCycle);
  float x = position * kXrange;
  printf("x=%.6f\n", x); 

  if (setupornot) {
    printf("Has been setup ... \n");
  } else {
    printf("setupornot still false! \n");
  }

  if (input == nullptr) {
    printf("input is null!\n");
  } else if (input->dims == nullptr) {
    printf("input->dims is null!\n");
  } else {
    printf("Size of input->dims->size: %d\n", input->dims->size);
  }

  if (interpreter == nullptr) {
    printf("interpreter is null!\n");
  } else {
    printf("interpreter is NOT null!\n");
  }

  // Increment the inference_counter, and reset it if we have reached
  // the total number per cycle
  // working
  inference_count += 1;
  if (inference_count >= kInferencesPerCycle) inference_count = 0;
}
```

### Relevant log output

```shell
serial output when excluding `tflite_file = model_to_tflite(inference_mdrnn.model, model_keras_file)`:

...
input is null!
interpreter is NOT null!
x=4.398230
Has been setup ...
input is null!
interpreter is NOT null!
x=4.712389
Has been setup ...
input is null!
interpreter is NOT null!
x=5.026548
Has been setup ...
...
```

**Comment by gaikwadrahul8** [comment]
Hi, @Zlisch 

Thank you for bringing this issue to our attention, as far I know there might be the MDN-RNN model you're using too complex for the limited memory of the raspberry pi pico w so please consider simplifying the model by reducing the number of layers, neurons or data types.

The `kTensorArenaSize` value might be insufficient. Experiment with increasing it gradually until allocation succeeds but be mindful of memory limitations and also check if there are any other processes or libraries consuming significant memory on raspberry pi pico w.

Please make sure that the input data you're providing to the model is valid and compatible with its expected format and dimensions. verify that the input tensor shape matches the model's expected input shape.

If possible optimize your model using techniques like quantization or pruning to reduce its memory footprint for the please follow our [official documentation](https://ai.google.dev/edge/litert/models/model_optimization) which will help help you to optimize your model. 

If issue still persists could you please pose this issue [tflite-micro](https://github.com/tensorflow/tflite-micro/issues) repo for further help ? 

Thank you for your cooperation and patience.

**Comment by Zlisch** [comment]
Thanks for the reply @gaikwadrahul8

I will try the optimization you mentioned to make the model as small as possible. I also noticed though `model.tflite` can be quite small, e.g. 41KB, the `model.cc` created by hex dump can be 251KB large. Is there anything that can be done?

**Comment by ashish-2005** [comment]
Hey @Zlisch ,
Regarding your query on model size blow-up on conversion from Tflite to C data array. This is happening because HEX dump naturally takes more space than the Tflite optimised storing format, but once you compile the model.cc file your executable should be close the original .tflite file.

Here is the original thread regarding this issue...
https://github.com/tensorflow/tensorflow/issues/43749#issuecomment-703227741

**Comment by Zlisch** [comment]
I have tried with a much reduced [model](https://github.com/Zlisch/tflite-pico/blob/main/examples/impsy_model/musicMDRNN-dim4-layers1-units4-mixtures5-scale10.cc) (model size 13092B, # parameters = 369) but it still doesn't work. I've raised a [new issue](https://github.com/tensorflow/tflite-micro/issues/2686) to the tflite-micro repo.

**Comment by gaikwadrahul8** [comment]
Hi, @Zlisch

Thank you for the update and trying things, I see you've posted this issue here https://github.com/tensorflow/tflite-micro/issues/2686 for further help so please feel free to close this issue from your end

If you need any further help with TensorFlow core or TensorFlow Lite (now renamed as [LiteRT](https://ai.google.dev/edge/litert))  please feel free to post your [issue](https://github.com/tensorflow/tensorflow/issues/new/choose)

Thank you for your cooperation and patience.
