### ISSUE TITLE
Tutorials on Estimators, Canned Estimators

### ISSUE THREAD

**Issue by abhijithchunduru** [tensorflow/tensorflow#7590]
Hi, 
I checked out the tensorflow dev-summit yesterday and came to know about Estimators and Canned Estimators. Estimators and Canned Estimators are intended to bring simple model-data wrapping capability to tensorflow, I believe. However, I am not able to find a lot of tutorials/docs on the interface for an estimator or documentation on how to write Canned Estimators/Estimators. tf.contrib.learn has estimator modules only for simple ML methods like mlps, linear regressors. I would like to know if there are gists/github code for estimators/canned estimators for cnns/auto-encoders/LSTMS.

**Comment by agarwal-ashish** [comment]
Here are some pointers to get started:

https://www.tensorflow.org/get_started/tflearn
https://www.tensorflow.org/tutorials/wide
https://www.tensorflow.org/tutorials/wide_and_deep
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/learn/python/learn#existing-estimator-implementations

**Comment by abhijithchunduru** [comment]
I have checked these. I wanted more of a how-to for writing your own estimator

**Comment by aribornstein** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/tutorials/estimators/index.md

**Comment by aselle** [comment]
@aribornstein's answer seems to answer the question completely. If you have a specific implementation question about a specific algorithm, this is best asked on StackOverflow. Unless you think there is a bug in the documentation or the code. Thanks so much!

**Comment by cgarciae** [comment]
@aribornstein Link is broken.

**Comment by amj** [comment]
@aselle link is broken -- this is the top hit for "wrapping a model in an estimator".  Might be worth fixin'
