### ISSUE TITLE
Is it possible to avoid configure/configure.py?

### ISSUE THREAD

**Issue by johnnynunez** [tensorflow/tensorflow#75911]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.18

### Custom code

Yes

### OS platform and distribution

ubuntu 22.04

### Python version

3.10

### Bazel version

6.5.0

### CUDA/cuDNN version

12.6.0 9.3.0

### GPU model and memory

Jetson AGX Orin

### Current behavior?

I'm doing a docker to build automatically tensorflow.
Is it possible to avoid configure that ask to the user for configuration?

### Standalone code to reproduce the issue

```shell
./configure or python3 configure.py
```

**Comment by johnnynunez** [comment]
Example jax:
https://github.com/google/jax/blob/main/build/build.py
```bash
BUILD_FLAGS='--enable_cuda --enable_nccl=False '
BUILD_FLAGS+='--cuda_compute_capabilities="sm_87" '
BUILD_FLAGS+='--cuda_version=12.6.0 --cudnn_version=9.4.0 '
BUILD_FLAGS+='--bazel_options=--repo_env=LOCAL_CUDA_PATH="/usr/local/cuda-12.6" '
BUILD_FLAGS+='--bazel_options=--repo_env=LOCAL_CUDNN_PATH="/opt/nvidia/cudnn/" '
BUILD_FLAGS+='--output_path=/opt/wheels '
    
python3 build/build.py $BUILD_FLAGS
python3 build/build.py $BUILD_FLAGS --build_gpu_kernel_plugin=cuda --build_gpu_plugin
```

**Comment by johnnynunez** [comment]
also tensorflow always use python 3.12...
because now xla use HERMETIC_PYTHON_VERSION

**Comment by Venkat6871** [comment]
Hi @johnnynunez ,
Apologies for the delay. Yes, please follow [documentation1](https://www.tensorflow.org/install/docker) and [documentation2](https://www.tensorflow.org/install/source) for a smooth installation. Also, kindly double-check all the compatibility versions.
Thank you!
