### ISSUE TITLE
Tensorflow "Text generation with an RNN" tutorial out of date

### ISSUE THREAD

**Issue by abisdbest** [tensorflow/tensorflow#75945]
I was taking a look at the tutorial on generating text with an RNN from the tensorflow website [(https://www.tensorflow.org/text/tutorials/text_generation),](https://www.tensorflow.org/text/tutorials/text_generation) and clicked the option to run on Google Colab. But when I tried running the full code I got overwhelmed with a multitude of errors. I thought I might have been doing something wrong, so I searched online, but found out that you are supposed to be able to just run the code without modification.
I figured it could just be that the way the new versions of tensorflow worked may have changed.

Would be very helpful to me if it could be fixed
many thanks

**Comment by tilakrayal** [comment]
@abisdbest,
Thank you for reporting the issue. I observed the same that the code is failing in tensorflow v2.17. Please allow some time to deep dive into the issue. Thank you!

**Comment by tilakrayal** [comment]
@abisdbest,
Hi, By default the colab notebook is using tensorflow v2.17 which contains keras3.0 which was causing the error. Could you please try to import keras2.0 with the below commands.

```python
!pip install tf_keras

import tf-keras as keras
```

Also I have modified some steps and then the code was executed without error/fail. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/9ead5c2dda2f3bf649d3bb3d214ca160/text_generation.ipynb).

Thank you!

**Comment by tilakrayal** [comment]
@abisdbest,
Could you please confirm if the issue is resolved. if yes, please feel free to move this issue to closed status. Thank you!
