### ISSUE TITLE
cuda::Diagnostician::FindKernelDriverVersion tries to access /proc/driver/nvidia/version on Windows

### ISSUE THREAD

**Issue by adalq** [tensorflow/tensorflow#7599]
Windows 10 64 bit
CUDA 8.0
cuDNN 5.1
tensorflow_gpu 1.0.0

### problem is here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/cuda/cuda_diagnostics.cc#L345

### the other place which opens the file is disabled on Windows:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/cuda/cuda_diagnostics.cc#L143

### Logs or other output that would be helpful

    E ...\stream_executor\cuda\cuda_driver.cc:1002] failed to allocate 2.00G (2147483648 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
    E ...\stream_executor\cuda\cuda_driver.cc:1002] failed to allocate 1.80G (1932735232 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
    E ...\stream_executor\cuda\cuda_dnn.cc:397] could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
    >>>    E ...\stream_executor\cuda\cuda_dnn.cc:404] error retrieving driver version: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
    E ...\stream_executor\cuda\cuda_dnn.cc:364] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM

**Comment by aselle** [comment]
Please take a look @mrry. Thanks!

**Comment by mrry** [comment]
Yep, that looks like a bug in the error reporting path. Should be a simple fix, so I'm marking it Contributions Welcome.

**Comment by jhli973** [comment]
Here have a similar issue:

Total memory: 4.00GiB
Free memory: 3.36GiB
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0:   Y
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 745, pci bus id: 0000:01:00.0)
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_dnn.cc:397] could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_dnn.cc:404] error retrieving driver version: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version

**Comment by mrry** [comment]
@jhli973 This problem should be fixed at HEAD. Please try upgrading to a nightly build to see if that fixes the problem.
