### ISSUE TITLE
Significant difference in Arena Memory requirements between the tflite interpreter and MicroInterpreter

### ISSUE THREAD

**Issue by abangwal** [tensorflow/tensorflow#75995]
Greetings,

Thanks for maintaining such a cool project :rocket: 

I am using a tflite model at full precision (FP32) and noticing a significant difference in the arena memory requirement between the interpreter of Tflite and MicroInterpreter of TfliteMicro.

When I use the `PrintInterpreterState()` method in Tflite after allocating the tensors to interpreter (with Tflite cpp), I get the following logs suggesting the memory usage is 0.246 MB

```
-----------Subgraph-0 has 149 tensors and 72 nodes------------
1 Inputs: [0] -> 196608B (0.19MB)
4 Outputs: [125,146,127,148] -> 60928B (0.06MB)
.
.
.
--------------Subgraph-0 dump has completed--------------

--------------Memory Arena Status Start--------------
Total memory usage: 257536 bytes (0.246 MB)
- Total arena memory usage: 257536 bytes (0.246 MB)
- Total dynamic memory usage: 0 bytes (0.000 MB)

Subgraph#0   Arena (Normal)         257536 (100.00%)
--------------Memory Arena Status End--------------
```

But when I try something similar with MicroInterpreter, after allocating the tensors, and logging 
```interpreter->arena_used_bytes()```  I find out its using 1784036 bytes (1.784 MB)

Is there something that I am missing like the PrintInterpreterState() only calculates for the input, output and intermediate weight arrays, while the actual execution require more memory for the intermediate transformations/results for input data ?

**Comment by tilakrayal** [comment]
@abangwal,
Could you please share a reproducible code that supports your statement so that the issue can debug the issue in an effective way? Thank you!

**Comment by abangwal** [comment]
Hey @tilakrayal ,

The model in context in BlazeFace (face_detection_front_128x128), at full precision FP32, I produced the model arena status for tflite interpreter with the [minimal.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/minimal/minimal.cc) given in the tflite official repository,

```cpp
  // Run inference
  TFLITE_MINIMAL_CHECK(interpreter->Invoke() == kTfLiteOk);
  printf("\n\n=== Post-invoke Interpreter State ===\n");
  tflite::PrintInterpreterState(interpreter.get()); //This is printing the Model arena status
```
Now coming on the tflite micro, tho my board is not in the officially supported platforms by the Tflite Micro as in [this list](https://ai.google.dev/edge/litert/microcontrollers/overview#supported_platforms) but the manufacturer have released their own adjusted arduino library for tflite micro ([Ameba_TensorFlowLite.zip](https://github.com/Ameba-AIoT/ameba-arduino-d/tree/master/Arduino_zip_libraries)) 

So I converted the model to C source file with the help of `convert_bytes_to_c_source()` function from python utils.

Then here is the code I used to access the `arena_used_bytes()`, its in arduino style
```cpp
#include <TensorFlowLite.h>

#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_error_reporter.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/schema/schema_generated.h"
#include "tensorflow/lite/version.h"

#include "BlazeFace32.h"

// Globals, used for compatibility with Arduino-style sketches.
namespace {
tflite::ErrorReporter* error_reporter = nullptr;
const tflite::Model* model = nullptr;
tflite::MicroInterpreter* interpreter = nullptr;
TfLiteTensor* input = nullptr;
TfLiteTensor* output = nullptr;

// Create an area of memory to use for input, output, and intermediate arrays.
// Minimum arena size, at the time of writing. After allocating tensors
// you can retrieve this value by invoking interpreter.arena_used_bytes().
const int kModelArenaSize = 2048 * 1024;
// Extra headroom for model + alignment + future interpreter changes.
const int kExtraArenaSize = 0;
const int kTensorArenaSize = kModelArenaSize + kExtraArenaSize;
uint8_t tensor_arena[kTensorArenaSize];
}  // namespace

void setup() {

  // Set up logging. Google style is to avoid globals or statics because of
  // lifetime uncertainty, but since this has a trivial destructor it's okay.
  // NOLINTNEXTLINE(runtime-global-variables)
  static tflite::MicroErrorReporter micro_error_reporter;
  error_reporter = &micro_error_reporter;

  // Map the model into a usable data structure. This doesn't involve any
  // copying or parsing, it's a very lightweight operation.
  model = tflite::GetModel(BlazeFace32);
  if (model->version() != TFLITE_SCHEMA_VERSION) {
    TF_LITE_REPORT_ERROR(error_reporter,
                         "Model provided is schema version %d not equal "
                         "to supported version %d.",
                         model->version(), TFLITE_SCHEMA_VERSION);
    return;
  }
  else {
  TF_LITE_REPORT_ERROR(error_reporter,
                         "Model loaded \n Model Vestion : %d \n Supported version %d.",
                         model->version(), TFLITE_SCHEMA_VERSION);
  }

  // This pulls in all the operation implementations we need.
  // NOLINTNEXTLINE(runtime-global-variables)
  static tflite::AllOpsResolver resolver;

  // Build an interpreter to run the model with.
  static tflite::MicroInterpreter static_interpreter(
      model, resolver, tensor_arena, kTensorArenaSize, error_reporter);
  interpreter = &static_interpreter;

  // Allocate memory from the tensor_arena for the model's tensors.
  TfLiteStatus allocate_status = interpreter->AllocateTensors();
  if (allocate_status != kTfLiteOk) {
    TF_LITE_REPORT_ERROR(error_reporter, "AllocateTensors() failed");
    return;
  }else{
    TF_LITE_REPORT_ERROR(error_reporter, "Arena in use : %d",interpreter->arena_used_bytes());
  }

  // Obtain pointers to the model's input and output tensors.
  input = interpreter->input(0);
  output = interpreter->output(0);
}

void loop() {
}
```
I think this should be enough to reproduce the findings, If not let me know what's missing :smile: .

**Comment by gaikwadrahul8** [comment]
Hi, @pkgoogle 
Please take look into this issue. Thank you

**Comment by pkgoogle** [comment]
Hi @abangwal, I believe https://github.com/tensorflow/tflite-micro/issues will be able to help you better.
