### ISSUE TITLE
[Discussion] model intellectual property protection

### ISSUE THREAD

**Issue by llhe** [tensorflow/tensorflow#7600]
Usually for mobile devices (or any devices which are publicly accessible) model deployment, there is a requirement for IP protection. Obviously, the current protobuf format is not desirable.

XLA can be a great help which will result in binary/so which is difficult for reverse engineering, but the current emphasis is mostly on performance improvement. For example, XLA does not cover the case when there are some customized op/kernels (executed either on standard CPU/GPU or customized accelerators) which could be common in mobile/IoT area.

**Comment by yaroslavvb** [comment]
cc @tatatodd

**Comment by aselle** [comment]
This is not really a feature request but rather a discussion topic. This is more appropriate for the tensorflow discuss google group. Thanks!
