### ISSUE TITLE
GPU use

### ISSUE THREAD

**Issue by Tarun0000** [tensorflow/tensorflow#76038]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.10

### Custom code

Yes

### OS platform and distribution

Window

### Python version

3.9

### CUDA/cuDNN version

12.5/9.2.1

### Current behavior?

hey i successfully setup cuda and able to use GPU in WSL , but my question is how i use it on my windows Conda Environment

### Standalone code to reproduce the issue

```shell
hey i successfully setup cuda and able to use GPU in WSL , but my question is how i use it on my windows Conda Environment
```

### Relevant log output

```shell
hey i successfully setup cuda and able to use GPU in WSL , but my question is how i use it on my windows Conda Environment
```

**Comment by Aljallaf100** [comment]
install this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler

**Comment by Tarun0000** [comment]
my cuda version is 12.6

**Comment by Venkat6871** [comment]
Hi **@Tarun0000** ,
Thank you for your confirmation. Your CUDA version should be 11.2, and the cuDNN version should be 8.1 for TensorFlow 2.10. I have provided the [documentation](https://www.tensorflow.org/install/source_windows#gpu) for your reference.
Thank you!
