### ISSUE TITLE
Optimizer got only float32?

### ISSUE THREAD

**Issue by enfeizhan** [tensorflow/tensorflow#761]
Got some big number so thought dtype float64 must be able to embrace a larger range. Everything looks fine until it comes to define the optimisation. I got this error:
```
site-packages/tensorflow/python/training/optimizer.py(343)_assert_valid_dtypes()
    342             "Invalid type %r for %s, expected: %s." % (
--> 343                 dtype, t.name, [v for v in valid_dtypes]))
    344 

ipdb> l
    338     for t in tensors:
    339       dtype = t.dtype.base_dtype
    340       if dtype not in valid_dtypes:
    341         raise ValueError(
    342             "Invalid type %r for %s, expected: %s." % (
--> 343                 dtype, t.name, [v for v in valid_dtypes]))
    344 
    345   # --------------
    346   # Methods to be implemented by subclasses if they want to use the
    347   # inherited implementation of apply_gradients() or compute_gradients().
    348   # --------------

ipdb> t
<tensorflow.python.framework.ops.Tensor object at 0x110b40630>
ipdb> t.dtype.base_dtype
tf.float64
ipdb> t.dtype
tf.float64
```
Looks like only tf.float32 accepted in this snippet? Can this be fixed?

**Comment by mrry** [comment]
For a hacky (unsupported) workaround, you could try the [answer to this StackOverflow question](http://stackoverflow.com/a/33702428/3574081).

**Comment by girving** [comment]
@mrry: Is there a reason to not change _valid_dtypes on our end?

**Comment by yaroslavvb** [comment]
there's likely a lot more holes in float64 support, I ran into the following ops being float32-only in 10 minutes of porting: image_summary, max_pool and Square

**Comment by girving** [comment]
Yep, changing `_valid_dtypes` on our end means fixing such things.  Are the other reasons?

**Comment by siddharth-agrawal** [comment]
@girving `_valid_dtypes` now includes float64, changed in #2389.

**Comment by vrv** [comment]
Thanks @siddharth-agrawal !  Someone can comment if for some reason #2389 doesn't fix this

**Comment by snassimr** [comment]
Seems still a warning appears for Adam optimizer in 1.0.1 version
