### ISSUE TITLE
Change device Placement of existing variable

### ISSUE THREAD

**Issue by abhijithchunduru** [tensorflow/tensorflow#7616]
How do I change the device placement of a tf.Variable() ?
I tried two methods 
```
a = tf.Variable(1,name = 'a')  # a's device is not set
with tf.device('/gpu:0'):
       a = tf.get_variable('a',1)   
# this creates a new variable on the gpu and doesn't change device assignment for a
```
I tried enforcing variable reuse by using tf.get_variable_scope().reuse_variables()
```
a = tf.Variable(1,name = 'a')  # a's device is not set
tf.get_variable_scope().reuse_variables()
with tf.device('/gpu:0'):
       a = tf.get_variable('a',1)   
# this creates a new variable on the gpu and doesn't change device assignment for a
```
This time, I get an error saying the variable 'a' did not exist in the gpu.

Any help on changing-device-placement or lazy-device-assignment would be appreciated. Thanks

**Comment by carlthome** [comment]
This is not a bug, right? Make a thread on StackOverflow and people will want to answer! :smiley:

**Comment by abhijithchunduru** [comment]
here is the link to the stackoverflow question i posted : 
https://stackoverflow.com/questions/42300475/change-device-placement-of-an-existing-tensorflow-variable
Thank you

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
