### ISSUE TITLE
tutorials_example_trainer working for cpu not gpu (built from source)

### ISSUE THREAD

**Issue by jeandut** [tensorflow/tensorflow#762]
I am trying to install TF from source WITHOUT INTERNET so far I have been able to advance thanks to @damienmg by replacing git repos by local repos for re2,gemmlowp,libpng,jpegsvrc and eigen and modifying WORKSPACE accordingly.  
The `bazel build -c opt  //tensorflow/cc:tutorials_example_trainer` cmd for tutorials_example_trainer works fine (with a few warnings due to comparison between signed and unsigned entities and index subscript above array bounds).
And `bazel-bin/tensorflow/cc/tutorials_example_trainer` produces the expected result.
However when I clean up with `bazel clean --expunge` and rerun ./configure for GPU support and then run:  
`bazel build -c opt config=cuda //tensorflow/cc:tutorials_example_trainer`  
I get the error messages :  
`'@gemmlowp//:eight_bit_int_gemm' failed: crosstool_wrapper_driver-is_not_gcc failed: error executing command third_party/gpus/crosstool/cleang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D FORTIFY_SOURCE=1' fstack-protector -fpIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object`  
or the same with `'@re2//:re2'`

**Comment by jeandut** [comment]
It seems like it is a PATH problem however I do not understand as the dependencies I installed locally worked for the non gpu support !
Someone ?

**Comment by josh11b** [comment]
I was hoping to get rid of the gemmlowp dependency soon (it doesn't look like we are actually using it), but re2 will likely stick around for a bit.  Not sure what the problem would be.

**Comment by vrv** [comment]
Can you try 
```
bazel build -c opt config=cuda --spawn_strategy=standalone --verbose_failures //tensorflow/cc:tutorials_example_trainer
```

and if that doesn't work, post the entire logs?

**Comment by jeandut** [comment]
I think I already built in in standalone and that did not work but I am gonna retry and post the log just in case or maybe I only did it for the building of the wheel and not the example.

**Comment by jeandut** [comment]
Since I posted this question I chose to install TF from the already created wheel available online instead of rebuilding it from scratch with bazel (because of this issue and also because of the 72 dependencies of tensorboard...I built it without GPU support and without Tensorboard but I was unhappy). I am a bit afraid that the competition of two installations would endanger the library itself therefore if you agree I will close this issue with no further explanations. Sorry for the waste of time.

**Comment by vrv** [comment]
We'd be happy to help you debug the issue, but we understand if you just want to use the pip package instead.

**Comment by jeandut** [comment]
Being a relative beginner in Linux I think I am gonna stick with this install for now.
I only installed from source because I heard somewhere on github that it could be better.
What do you think ?
You all however have been incredibly helpful through the installation !
If I had to comment I would say that the tricks `bazel clean--expunge` and `spawnstrategy=standalone` should be more emphasized on Tensorflow installation page for beginners like me !
PS : I reran with `spawnstrategy=standalone` and got another error with `undeclared inclusion(s) in rule '//tensorflow/core:gpu_runtime': this rule is missing dependency declarations for the following files` maybe it is because I am using the old version of bazel compatible with Java7...

**Comment by cswhjiang** [comment]
Hi @jeandut  , I am trying to instal TF from source without internet access now. Could you tell me how to replace git repos by local repos?

**Comment by jeandut** [comment]
@cswhjiang see [#587](https://github.com/bazelbuild/bazel/issues/587) issue on bazel repo.
