### ISSUE TITLE
tf.train.import_meta_graph should be parallelized

### ISSUE THREAD

**Issue by kirk86** [tensorflow/tensorflow#7625]
Hey guys, I've been wondering whether it's possible the `tf.train.import_meta_graph` to be parallelized across multiple cores. When I load a complex model it takes too long and I only see one of my 24 cores being utilized to 100%.

### Environment info
Operating System: CentOS

Installed version of CUDA and cuDNN: 
Not applicable

Minimal example:
```
sess = tf.Session()
new_saver = tf.train.import_meta_graph('my-model.meta')
new_saver.restore(sess, tf.train.latest_checkpoint('./'))
all_vars = tf.get_collection('vars')
for v in all_vars:
    v_ = sess.run(v)
    print(v_)
```

Any plans on changing that in the near future?

**Comment by yaroslavvb** [comment]
When I see one core being utilized, my first suspicion is that work is done in Python. Python has chosen to remain in the punch-card age and only use 1 core for its processing, citing GIL issues. So the way to troubleshoot this is:

```
python -m cProfile -o slow.prof script.py
pip install snakeviz
snakeviz slow.prof
```

This may help you find a bottleneck, possibly something inefficient is being done in Python (I used this technique to speed up session.run from 120 usec to 60 usec by cutting out some unneeded Python calls). Longer term solution may be to rewrite metagraph loading in C++, someone from TF team may know if there are plans

**Comment by kirk86** [comment]
@yaroslavvb thanks for the input. I'll definitely have a look into it.

**Comment by yaroslavvb** [comment]
PS, we also ran into MetaGraph slowness issue, we have to turn it off for reinforcement learning scripts -- https://github.com/openai/universe-starter-agent/blob/master/worker.py#L18

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
