### ISSUE TITLE
Poor Constant Propagation

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#7630]
Running on the 1.0.0 Docker image.

Compare this:
```
tensor_util.constant_value_as_shape(ops.convert_to_tensor((tf.constant(15),16)))
> TensorShape([Dimension(15), Dimension(16)])
```
to:
```
tensor_util.constant_value_as_shape(ops.convert_to_tensor((tf.constant(15) * 1,16)))
> TensorShape([Dimension(None), Dimension(16)])
```
It seems to me that constant propagation should happen in the latter. This leads to size information being lost in certain cases such as image upsampling / downsampling where constant size is multiplied and then fed to something like `resize_images`.

**Comment by yaroslavvb** [comment]
I vaguely remember similar issues being fixed by modifying `constant_value` function. One possibility is that it works for tf.constant(15), but gives up when it sees a tf.mul

**Comment by cancan101** [comment]
Should be solvable by adding a case to [`_ConstantValue`](https://github.com/tensorflow/tensorflow/blob/a0d784bdd31b27e013a7eac58a86ba62e86db299/tensorflow/python/framework/tensor_util.py#L577) (this can be used for any binary operator). This is rough solution, might not handle various tensor types quite right:
```python
  elif tensor.op.type == "Mul":
    left = constant_value(tensor.op.inputs[0])
    if left is None:
      return None
    right = constant_value(tensor.op.inputs[1])
    if right is None:
      return None
    return left * right
```

**Comment by aselle** [comment]
I think ideally, XLA and other more general optimization efforts will handle some of this better constant folding. CCing @prb12 for comment. I'd hate to have to put special cases like that in every Tensor, especially since that optimization would only benefit the python bindings and not any other languages.

**Comment by cancan101** [comment]
The issue that I am dealing with _is_ on the Python side, where the shape information gets lost when calling `resize_images` with something like `2x` the current size, etc.

**Comment by aselle** [comment]
Sorry for the confusion. Yes, it looks like it would be good to propagate these cases into constantvalue, especially if they are happening in common functions. Could you please provide a PR. You might consider it checking for all binary operators that it can be done on in a generic way.

**Comment by vrv** [comment]
If you do this in python, you might also want to implement the same logic in this C++ function: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/shape_refiner.cc#L356 (with tests) -- it's possible in C++ the else clause already handles this case, whereas in python it doesn't, but it would be good to make sure they are consistent.

**Comment by girving** [comment]
Unfortunately the `mul` fix proposed by @cancan101 makes `constant_value` linear time in the size of the whole graph in the worse case.  Therefore, I don't think we can support it in that form.  I'll close this issue as now as out of reach of simple contributions (and for lack of activity).
