### ISSUE TITLE
Using the c++ API,  how do  set  fp16 on  cpu？

### ISSUE THREAD

**Issue by keke444** [tensorflow/tensorflow#76315]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.13

### Custom code

Yes

### Bazel version

5.30

### Current behavior?

Hi 
      using cpu backend,  we want to set fp16 to Invoke, 
using below code,  What setting parameters do I need to add 

thansk

### Standalone code to reproduce the issue

```shell
#include <memory>
#include <string>
#include <vector>

#include "tensorflow/lite/c/c_api.h"
#include "tensorflow/lite/c/c_api_experimental.h"
#include "tensorflow/lite/core/c/common.h"


#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

#define STB_IMAGE_WRITE_IMPLEMENTATION
#include "stb_image_write.h"

int main(void)
{
uint8_t *image = stbi_load("192.jpg", 192, 192, 3, 3);
int tmpSize = (192* 192*3);
float *in = (float *)malloc(tmpSize**sizeof(float)); 
float *out = (float *)malloc(tmpSize**sizeof(float)); 
for (int i = 0; i < tmpSize; i++)
{
    in[i]   = (float)(image[i] - 0.0f) / 255.0f;
}
//init model
TfLiteModel model = TfLiteModelCreateFromFile(info->ld.model_name);
TfLiteInterpreterOptions options = TfLiteInterpreterOptionsCreate();
TfLiteInterpreterOptionsSetNumThreads(options, info->param.number_of_threads);
//
TfLiteInterpreter interpreter = TfLiteInterpreterCreate(model, options);
TfLiteInterpreterAllocateTensors(interpreter);

//invoke
TfLiteTensor* input_tensor = TfLiteInterpreterGetInputTensor(interpreter, 0);
TfLiteTensorCopyFromBuffer(input_tensor, (void *)in, tmpSize*sizeof(float));
TfLiteInterpreterInvoke(interpreter);

//get output
TfLiteTensor* output_tensor = TfLiteInterpreterGetOutputTensor(interpreter, 0);
TfLiteTensorCopyToBuffer(output_tensor, (void *)Out, tmpSize*sizeof(float) );

//deinit
TfLiteInterpreterDelete(interpreter);
TfLiteInterpreterOptionsDelete(options);
TfLiteModelDelete(model);

}
```

**Comment by ravinm123** [comment]
model = model.cast('float16')

**Comment by ravinm123** [comment]
# Enable mixed precision in TensorFlow for GPU
from tensorflow.keras.mixed_precision import experimental as mixed_precision
policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_policy(policy)

**Comment by gaikwadrahul8** [comment]
Hi, @keke444 

I apologize for the delayed response, I think you can use this [SetAllowFp16PrecisionForFp32](https://ai.google.dev/edge/api/tflite/cc/class/tflite/impl/interpreter)

```
void SetAllowFp16PrecisionForFp32(
  bool allow
)
```
Allow `float16` precision for `FP32` calculation when possible.

Default: not allow.

WARNING: This API is deprecated: prefer controlling this via delegate options, e.g. `tflite::StatefulNnApiDelegate::Options::allow_fp16' or TfLiteGpuDelegateOptionsV2::is_precision_loss_allowed. This method will be removed in a future release.

Thank you for your cooperation and patience.
