### ISSUE TITLE
FEATURE: Tensorboard Scalars: Simple Way of Setting y axis to start at 0

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#7631]
I have a number of scalars that I plot in tensorboard that are non negative values (ie accuracy, etc). It would be cool if there was a quick way to have the y axis start at 0 rather than allocating unused space in the negative y direction.
![image](https://cloud.githubusercontent.com/assets/51059/23080071/7b1aa63c-f51d-11e6-8ae0-82bbf299a01f.png)

**Comment by chris-chris** [comment]
If there anyone working on this issue? If there is no one, can I try this one?

**Comment by dandelionmane** [comment]
I'm migrating this to https://github.com/tensorflow/tensorboard/issues/77. @chris-chris you're welcome to contribute on this. If you're still interested, let's discuss on the new issue at tensorboard/77.
