### ISSUE TITLE
file not found: -lcublas.8.0

### ISSUE THREAD

**Issue by esemi77** [tensorflow/tensorflow#7633]
I am trying to install tensorflow w/ GPU from Source on Mac OS X El Capitan. (CUDA 8.0 & cuDNN 5.1)

After wrestling with LYLD_LIBRARY_PATH [#6729](https://github.com/tensorflow/tensorflow/issues/6729), I ran
`bazel build --config=opt --config=cuda --action_env PATH --action_env LD_LIBRARY_PATH --action_env DYLD_LIBRARY_PATH  //tensorflow/tools/pip_package:build_pip_package`

But, it generates an error that cannot find cublas.8.0 which I have in my directory. If I try with --verbose_failures, it generate following description.

Linking of rule '//tensorflow/python:_pywrap_tensorflow.so' failed: link_dynamic_library.sh failed: error executing command

What am I missing? it should be something with path configuration. :-(

**Comment by asimshankar** [comment]
I suspect you're using bazel 0.4.4. If that is true, you might have to downgrade to bazel 0.4.3.
See #7227 for details, and it seems like it will be fixed in 0.4.5

Let us know if that helps.

**Comment by esemi77** [comment]
Yes, it helps. 

Finally, I could build the tensorflow r.1.0. on my mac !! Thank you so much.

**Comment by asimonov** [comment]
yes, disabling SIP, setting variables as above and downgrading to bazel 0.4.3 made it possible to build pip package on El Capitan!!!

**Comment by khyox** [comment]
Thanks for the hints! I also needed to apply the solution [in this SO question about libcudart.8.0.dylib not loaded](http://stackoverflow.com/questions/39865212/dyld-library-not-loaded-rpath-libcudart-8-0-dylib-while-building-tensorflow) to get to build pip package on Mac OS X El Capitan (CUDA 8.0 & cuDNN 5.1).

**Comment by asimonov** [comment]
Yes, that softlink needs to be created too

_____________________________
Kind Regards,
Alexey Simonov
