### ISSUE TITLE
gen_nn_ops.fractional_max_pool_grad aborts with "malloc_consolidate(): invalid chunk size"

### ISSUE THREAD

**Issue by cybersupersoap** [tensorflow/tensorflow#76362]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf-nightly 2.18.0.dev20240817

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 20.04.3 LTS

### Python version

3.10.14

### Current behavior?

I encountered an `crash issue` in TensorFlow when I used API `gen_nn_ops.fractional_max_pool_grad` . 
I have confirmed that above the code would crash on `tf-nightly 2.18.0.dev20240817` (nightly-build). Please find the [gist](https://colab.research.google.com/drive/16XRisnbPuTfwdeRHkdZsJIEaDs9RHYGs?usp=sharing) to reproduce the issue.

### Standalone code to reproduce the issue

```shell
import numpy as np
from tensorflow.python.ops import gen_nn_ops
from tensorflow.python.ops import nn_ops
import tensorflow as tf

_PRNG = np.random.RandomState(341261)
num_batches =1
row_window_size=2
col_window_size=2
num_rows = (row_window_size - 1) * 5 + 1
num_cols = (col_window_size - 1) * 7 + 1
input_shape = (num_batches, num_rows, num_cols, 1)
sess = tf.compat.v1.Session()
with sess.as_default():
    x = np.arange(48, dtype=np.float32)
    _PRNG.shuffle(x)
    input_tensor =  x.reshape(input_shape)
    window_size = [1, row_window_size, col_window_size, 1]
    stride_size = [1, 65536, col_window_size - 1, 1] 
    padding = 'VALID'
    output_tensor = nn_ops.max_pool(input_tensor, window_size, stride_size, padding)
    output_backprop = _PRNG.randint(100, size=output_tensor.shape)
    row_seq = list(range(0, num_rows, row_window_size - 1))
    col_seq = list(range(0, num_cols, col_window_size - 1))
    row_seq[-1] += 1
    col_seq[-1] += 1
    gen_nn_ops.fractional_max_pool_grad(input_tensor, output_tensor, output_backprop, row_seq, col_seq, overlapping=True)
```

### Relevant log output

```shell
malloc_consolidate(): invalid chunk size
Aborted (core dumped)
```

**Comment by tilakrayal** [comment]
@cybersupersoap,
Thank you for reporting the issue. I request you to take a look at this [issue](https://github.com/tensorflow/tensorflow/issues/59394) and https://github.com/tensorflow/tensorflow/issues/59405 where a similar issue has been proposed and it is still open.Also I request to follow the similar issue which has been proposed to have the updates on the same. Thank you!
