### ISSUE TITLE
Snap package for tensorflow

### ISSUE THREAD

**Issue by anirudh2290** [tensorflow/tensorflow#7636]
It would be nice to have a snap package for tensorflow. https://snapcraft.io/
The advantage is that it is easy to install and supports multiple distributions.

**Comment by bhack** [comment]
And http://flatpak.org

**Comment by aselle** [comment]
@martinwicke , do we have any plans for package distribution through other than pip means. I know ubuntu/Debian was a non-starter for various reasons. We certainly would be happy to accept contributions by the community in this area as package maintainers.

**Comment by martinwicke** [comment]
Community contributed packages would be great. We just started publishing to maven, and we have a tgz with .so/.h files. 

We don't have the bandwidth to maintain other packages, but we'd love to have community-maintained packages.

**Comment by martinwicke** [comment]
I will close this issue. If someone wants to take it on, I'd be excited to add a link to a community supported package to our website.
