### ISSUE TITLE
Links to Android nightly builds on README.md are broken

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [tensorflow/tensorflow#7638]
Links to Android nightly builds on https://github.com/tensorflow/tensorflow/blob/master/README.md are broken.

![image](https://cloud.githubusercontent.com/assets/15331/23086006/c80cc702-f538-11e6-927d-d44b1f5f80e2.png)

-->
![image](https://cloud.githubusercontent.com/assets/15331/23086019/d91aa082-f538-11e6-9d76-7e56cd879900.png)

**Comment by aselle** [comment]
@yifeif, @gunan, could you take a look?

**Comment by andrewharp** [comment]
This looks like a bad merge. The nightly-matrix-android link can be deleted, and the correct links to nightly-android are found just below.

**Comment by yifeif** [comment]
Thanks @andrewharp for pointing to the correct link! Closing.
