### ISSUE TITLE
'LookupError: No gradient defined for operation '...' (op type: ResizeBicubic)' is raised

### ISSUE THREAD

**Issue by mikigom** [tensorflow/tensorflow#7641]
I tried to use [tf.image.resize_images](https://www.tensorflow.org/api_docs/python/tf/image/resize_images) with ```method=ResizeMethod.BICUBIC```.

The shorten version of my code is the following:
```python
# module import is omitted
# config setting is omitted
# global variable declaration is omitted

def train():
    # file queuing and reading are omitted.
    magnification = tf.random_uniform([1], minval = 0, maxval = 4, dtype = tf.float32)

    image_patches_blurred = tf.image.resize_images(image_patches, [tf.to_int32(64/magnification[0]), tf.to_int32(64/magnification[0])], \
                                                    method = tf.image.ResizeMethod.BICUBIC)
    image_patches_blurred = tf.image.resize_images(image_patches_blurred, [64, 64], method = tf.image.ResizeMethod.BICUBIC)

    with tf.variable_scope('generator'):
        G = Stage_Unet_model.generator(image_patches_blurred, batch_size = 16, image_size = 64, input_channels = 3, gf_dim = 32)

    # Model Loss definition is omitted

    # Summary Operation is omitted

    # tf variables loading
    all_vars = tf.global_variables()
    model_generator_vars = [k for k in all_vars if k.name.startswith("generator")]

    # Gradient Clipping
    generator_grads = tf.gradients(G_loss, model_generator_vars)
    generator_grads, _ = tf.clip_by_global_norm(generator_grads, clip_norm = 1.0)
    generator_var_pairs = zip(generator_grads, model_generator_vars)

    # tf.train.Saver and global_step declaration is omitted

    # tf.train.AdamOptimizer
    Adam = tf.train.AdamOptimizer(config.learning_rate)
    G_optim = Adam.apply_gradients(generator_var_pairs, global_step = G_global_step)

    # merge summary operation is omitted

    with tf.Session() as sess:
        #...
        for epoch in range(config.epoch):
            for idx in range(config.train_data_number):
                # Note that graph operations related with model D are omitted
                train_D_l, train_G_l, train_D_t_s, train_G_t_s, D_step, G_step, _, __ = sess.run([D_loss, G_loss, \
                                                                D_tot_summary, G_tot_summary, \
                                                                D_global_step, G_global_step, D_optim, G_optim])
        #...

if __name__ == '__main__':
    if not tf.gfile.Exists(log_dir):
        tf.gfile.MakeDirs(log_dir)
    train()
```

Running the above code will result in the following error:
```
$ python train_stage1.py 
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "train_stage1.py", line 216, in <module>
    train()
  File "train_stage1.py", line 150, in train
    generator_grads = tf.gradients(G_loss, model_generator_vars)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py", line 459, in gradients
    (op.name, op.type))
LookupError: No gradient defined for operation 'ResizeBicubic_3' (op type: ResizeBicubic)
```

Thank you for any help.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
```
$ ls -l /usr/local/cuda-8.0/lib64/libcud*
-rw-r--r-- 1 root root   558720 11월  4 05:18 /usr/local/cuda-8.0/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 11월  4 05:18 /usr/local/cuda-8.0/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 11월  4 05:18 /usr/local/cuda-8.0/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rwxr-xr-x 1 root root   415432 11월  4 05:18 /usr/local/cuda-8.0/lib64/libcudart.so.8.0.44
-rw-r--r-- 1 root root   775162 11월  4 05:18 /usr/local/cuda-8.0/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 79337624 11월  4 05:20 /usr/local/cuda-8.0/lib64/libcudnn.so
-rwxr-xr-x 1 root root 79337624 11월  4 05:20 /usr/local/cuda-8.0/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 79337624 11월  4 05:20 /usr/local/cuda-8.0/lib64/libcudnn.so.5.1.5
-rw-r--r-- 1 root root 69756172 11월  4 05:20 /usr/local/cuda-8.0/lib64/libcudnn_static.a
```

If installed from binary pip package, provide:
```
$ python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
1.0.0
```

**Comment by aselle** [comment]
Not every operation in TensorFlow has a gradient defined. Often this is because these operations are not used during training loops and instead are used for preprocessing. In general, image operations are often done with bilinear for performance reasons, but also because bilinear defines the gradient. We likely will not add this any time soon, but you could easily add it yourself by looking at how image resize bilinear defines the gradient. Let me know if you need further direction.

**Comment by mikigom** [comment]
It may be a somewhat low-level question, please acknowledge a little. I wanted to fix it myself, if possible, so I looked at the source code for the ```tensorflow/python/ops``` (for the first time). After looking at ```tensorflow.python.ops.image_grad.py```, I have confirmed that there is a method called ```_ResizeBilinearGrad``` which defines the gradient of bilinear resizing operation as you mentioned.

However, I cannot find the file in ```tensorflow/python/ops``` as ```gen_image_ops.py```, which is imported from ```from tensorflow.python.ops import gen_image_ops```. Please let me know where to check.

**Comment by hlzlyc** [comment]
dd

**Comment by hlzlyc** [comment]
@mikigom , @aselle  ,do you have fixed this problem?  I meeted the same problem when I want to calculate the gradients of ResizeNearestNeighbor.  I know image resize bilinear defines the gradient and know where it is , but I still don't know how to  solve this problem.

@ops.RegisterGradient("ResizeNearestNeighbor")
def _ResizeNearestNeighborGrad(op, grad):
  """The derivatives for nearest neighbor resizing.

  Args:
    op: The ResizeNearestNeighbor op.
    grad: The tensor representing the gradient w.r.t. the output.

  Returns:
    The gradients w.r.t. the input and the output.
  """
  image = op.inputs[0]
  if image.get_shape()[1:3].is_fully_defined():
    image_shape = image.get_shape()[1:3]
  else:
    image_shape = array_ops.shape(image)[1:3]

  # pylint: disable=protected-access
  grads = gen_image_ops._resize_nearest_neighbor_grad(
      grad,
      image_shape,
      align_corners=op.get_attr("align_corners"))
  # pylint: enable=protected-access
  return [grads, None]

I copy this to nn_grad.py , but it is useless.
Thanks for any help

**Comment by hlzlyc** [comment]
`dd`

**Comment by mmosquera10** [comment]
@hlzlyc Did you resolve this issue? I am having the same problem.

**Comment by kaleaht** [comment]
I found this useful repo for this problem: https://github.com/iwyoo/bicubic_interp-tensorflow
Not yet got it to work in my model.

**Comment by idearibosome** [comment]
It seems that it has been fixed in 1.4.0.
https://github.com/tensorflow/tensorflow/commit/3331c574bcfd85787d7a4f3d1b1b139239a6595b

**Comment by GPrathap** [comment]
Any update on this?

**Comment by julypraise** [comment]
I think this must be updated especially for the sake of tf2. The tutorial does not provide enough detail for implementing custom gradients on tensor operators.

**Comment by anaradutoiu** [comment]
@aselle I am also facing this problem of no defined gradient for the function tf.image.adjust_saturation. I am new to tensorflow so I would like to ask how should one proceed when you have to add your own gradient. Could you please give more details about that?
