### ISSUE TITLE
v1.0.0 on Centos 7 complie error whith cuda 8.0

### ISSUE THREAD

**Issue by AntonyM55** [tensorflow/tensorflow#7642]
build with --config=cuda get error
[rnd@localhost tensorflow]$ bazel build -c opt --config=cuda tensorflow/tools/pip_package:build_pip_package --verbose_failures
INFO: $TEST_TMPDIR defined: output root default is '/home/rnd/tmp'.
......
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
WARNING: /home/rnd/gits/tensorflow/tensorflow/workspace.bzl:27:5: 
Current Bazel is not a release version, cannot check for compatibility.
WARNING: /home/rnd/gits/tensorflow/tensorflow/workspace.bzl:28:5: Make sure that you are running at least Bazel 0.4.2.
.
INFO: Found 1 target...
ERROR: /home/rnd/tmp/_bazel_rnd/707043e71401a80a1e11714c15a7b311/external/pcre/BUILD:5:1: undeclared inclusion(s) in rule '@pcre//:pcre':
this rule is missing dependency declarations for the following files included by 'external/pcre/pcre_globals.c':
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/limits.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/syslimits.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h'
  '/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdint.h'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 6.763s, Critical Path: 0.73s

### Environment info
Operating System:
CentOS Linux release 7.2.1511 (Core)
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
[rnd@localhost ~]$ ls /usr/local/cuda/lib64/libcud*
/usr/local/cuda/lib64/libcudadevrt.a
/usr/local/cuda/lib64/libcudart.so
/usr/local/cuda/lib64/libcudart.so.8.0
/usr/local/cuda/lib64/libcudart.so.8.0.44
/usr/local/cuda/lib64/libcudart_static.a
/usr/local/cuda/lib64/libcudnn.so
/usr/local/cuda/lib64/libcudnn.so.5
/usr/local/cuda/lib64/libcudnn.so.5.1.5
/usr/local/cuda/lib64/libcudnn_static.a

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
[rnd@localhost tensorflow]$ git rev-parse HEAD
07bb8ea2379bd459832b23951fb20ec47f3fdbd4

2. The output of `bazel version`
[rnd@localhost bazel]$ git checkout 0.4.2
HEAD is now at ba94a7b... Release 0.4.2 (2016-12-02)
[rnd@localhost bazel]$ git rev-parse HEAD
ba94a7b93e1c95bca1928d8c51c6adc62ed864ab
[rnd@localhost bazel]$ bazel version
INFO: $TEST_TMPDIR defined: output root default is '/home/rnd/tmp'.
......
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 01 00:00:00 1970 (0)
Build timestamp: Thu Jan 01 00:00:00 1970 (0)
Build timestamp as int: 0

### What other attempted solutions have you tried?
delete "--config=cuda" will be OK, but I need cuda 

[rnd@localhost tensorflow]$ bazel build -c opt  tensorflow/tools/pip_package:build_pip_package --verbose_failures

**Comment by aselle** [comment]
We don't officially support CentOS. Some people have managed to get it to work with the cmake build file. Please search existing issues.
