### ISSUE TITLE
Feature request: Save the logging to a file

### ISSUE THREAD

**Issue by yuvval** [tensorflow/tensorflow#7644]
According to [this SO question](http://stackoverflow.com/questions/40559667/how-to-redirect-tensorflow-logging-to-a-file), saving the logger output to a file is not supported.

Would be great if that would be possible.

Thank you

**Comment by aselle** [comment]
Could you just use unix style file redirection?
i.e. 
```
cmd > foo.txt
```

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by lidalei** [comment]
Try `cmd 1>foo.txt 2>&1`. It works for me.
