### ISSUE TITLE
Error when running image retraining example (retrain.py) with --print_misclassified_test_images flag

### ISSUE THREAD

**Issue by jsawruk** [tensorflow/tensorflow#7647]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

- http://stackoverflow.com/questions/17322668/typeerror-dict-keys-object-does-not-support-indexing
- http://stackoverflow.com/questions/18552001/accessing-dict-keys-element-by-index-in-python3
- http://stackoverflow.com/questions/26693055/dict-key-object-does-not-support-indexing-python-3

### Environment info
Operating System: macOS 10.12.3
Python version: 3.5.2

Installed version of CUDA and cuDNN: Not using CUDA

1. The commit hash (`git rev-parse HEAD`): 89059e6f0b2788b624e744afc21ba2472523a250
2. The output of `bazel version`: 
```
Build label: 0.4.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Feb 1 18:56:35 2017 (1485975395)
Build timestamp: 1485975395
Build timestamp as int: 1485975395
```

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
Run this command:
`bazel-bin/tensorflow/examples/image_retraining/retrain --image_dir ~/flower_photos/ --print_misclassified_test_images`

### What other attempted solutions have you tried?
Reviewed source code for retrain.py, both locally and latest version on Github. See lines 892-896 (inside main function). The code looks correct. I suspect it is an issue specific to Python 3. 

I have not tried to run this in Python 2 yet.

### Logs or other output that would be helpful
This is what is output:
```
=== MISCLASSIFIED TEST IMAGES ===
Traceback (most recent call last):
  File "/Users/jsawruk/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/examples/image_retraining/retrain.py", line 1061, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Users/jsawruk/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/Users/jsawruk/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/examples/image_retraining/retrain.py", line 896, in main
    print('%70s  %s' % (test_filename, image_lists.keys()[predictions[i]]))
TypeError: 'dict_keys' object does not support indexing
```

It appears the solution is to rewrite line 896 from:
`print('%70s  %s' % (test_filename, image_lists.keys()[predictions[i]]))`

to:

`print('%70s  %s' % (test_filename, list(image_lists.keys())[predictions[i]]))`

When I edit the code locally to the line above, I no longer get the error when I run the example.

**Comment by boyuzhangus** [comment]
I got similar problem. When I was running bazel build tensorflow/examples/image_retraining:retrain
, it said '-bash: bazel: command not found' for my macOS. I actually ran ./configure again but it doesn't work.

**Comment by jsawruk** [comment]
@boyuzhangus: That's a separate issue. It sounds like you either a) don't have bazel installed correctly or b) you have bazel installed correctly but it's not in your path. On my computer, bazel is in $HOME/bin, so I added the following to my .profile:

`export PATH="$PATH:$HOME/bin"`

If you continue to have issues after you have bazel properly installed, please file a separate issue unless you are having the exact issue that I reported with this specific flag.

**Comment by aselle** [comment]
@jsawruk, that is definitely a python 2 print statement. Sorry about that. Your fix changed it to the print function, which is the right thing to do. Could you please submit a pull request to fix that. Thanks so much!

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by sakshamsneh** [comment]
Sir, I am seeing this traceback:
Traceback (most recent call last):
  File ".\retrain.py", line 1062, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "C:\Users\SAKSHIM\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File ".\retrain.py", line 888, in main
    ground_truth_input: test_ground_truth})
  File "C:\Users\SAKSHIM\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "C:\Users\SAKSHIM\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\client\session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (0,) for Tensor 'input/BottleneckInputPlaceholder:0', which has shape '(?, 2048)'
My python version:
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)] on win32
