### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Default' (revisited)

### ISSUE THREAD

**Issue by zd3nik** [tensorflow/tensorflow#7651]
### Issue

```
$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/schidester/usr/tf/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/schidester/usr/tf/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 75, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/schidester/usr/tf/local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/symbol_database.py", line 165, in <module>
    _DEFAULT = SymbolDatabase(pool=descriptor_pool.Default())
AttributeError: 'module' object has no attribute 'Default'
```

### Existing issues
Already found issues: #5344 and #5319 but neither provides a solution to the problem - that I could see (perhaps I just missed it somewhere)

### Environment info
Operating System: Linux Mint 17.3 Rosa

### Reproduction details
First I built tensorflow from git source, branch r1.0.

```
$ git remote -v
origin	https://github.com/tensorflow/tensorflow (fetch)
origin	https://github.com/tensorflow/tensorflow (push)
$ git branch
  master
* r1.0
$ bazel version
Build label: 0.4.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Feb 1 18:54:21 2017 (1485975261)
Build timestamp: 1485975261
Build timestamp as int: 1485975261
```

No apparent problems encountered during the build.  This resulted in a .whl file in the /tmp directory and I installed it with pip:

```
$ sudo pip install /tmp/tensorflow_pkg/tensorflow-1.0.0-cp27-none-linux_x86_64.whl
```

At this point I get the import error shown at the top of this post whenever `import tensorflow` is used in a python shell.

So I removed the locally built tensorflow with `sudo pip uninstall tensorflow` and re-installed with the pre-built .whl file:

```
$ sudo pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0-cp27-none-linux_x86_64.whl
```

Same import error.  Uninstalled again and tried using a virtualenv.  But I'm still getting the import errors:

```
$ virtualenv --system-site-packages ~/usr/tf
$ source ~/usr/tf/bin/activate
(tf)$ pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0-cp27-none-linux_x86_64.whl
Downloading/unpacking https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0-cp27-none-linux_x86_64.whl
  Downloading tensorflow-1.0.0-cp27-none-linux_x86_64.whl (44.1MB): 44.1MB downloaded
Requirement already satisfied (use --upgrade to upgrade): protobuf>=3.1.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.0.0)
Requirement already satisfied (use --upgrade to upgrade): wheel in /usr/lib/python2.7/dist-packages (from tensorflow==1.0.0)
Requirement already satisfied (use --upgrade to upgrade): mock>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.0.0)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.11.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.0.0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.10.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow==1.0.0)
Installing collected packages: tensorflow
Successfully installed tensorflow
Cleaning up...
(tf)$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/schidester/usr/tf/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/schidester/usr/tf/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 75, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/home/schidester/usr/tf/local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/symbol_database.py", line 165, in <module>
    _DEFAULT = SymbolDatabase(pool=descriptor_pool.Default())
AttributeError: 'module' object has no attribute 'Default'
```

I've tried the following, but neither had any effect:

```
 pip install --upgrade protobuf
 pip install --upgrade tensorflow
```

My best guess is that the python protobuf lib version available for the older version of Linux Mint I'm using is the problem.  But I don't know how to verify that or fix it - if that is indeed the problem.

**Comment by aselle** [comment]
Did you try pip install --upgrade protobuf within the virtualenv or outsisde of it. I usually do it inside the virtualenv and that resolves that problem. Thanks

**Comment by garyshi** [comment]
From your Python interpreter, check the location of your google.protobuf.descriptor_pool module:
$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.protobuf import descriptor_pool
>>> descriptor_pool.__file__
'/usr/local/lib/python2.7/dist-packages/google/protobuf/descriptor_pool.pyc'

It's possible that you are using an earlier version of google.protobuf from a different path.

I installed tensorflow by using pip, and it installs a new google.protobuf under /usr/local/lib/python2.7/dist-packages, while there is another one (don't know where it comes from) under /usr/lib/python2.7/dist-packages. Removing that one solved my problem.

**Comment by garyshi** [comment]
Find a better way instead of removing the old version: I am using Ubuntu and that version comes from Ubuntu package python-protobuf. I uninstalled tensorflow and the new protobuf (sudo pip uninstall protobuf) and then upgrade the existing one using "sudo pip install --upgrade protobuf".

**Comment by zd3nik** [comment]
@aselle I did the `pip install --upgrade protobuf` in all variations.  Inside and outside the virtualenv, with and without sudo.  In all cases it was a no-op (no install or upgrade performed).

@garyshi Thanks for the tip!  It actually shows the protobuf site-package path in the stack trace of the import error - it's using the system site-packages.  Rather than tinker with the system site-packages I tried a virtualenv *without* the `--system-site-packages` option and when I performed `pip install --upgrade protobuf` within that virtualenv it installed protobuf 3.2.0.

```
(tf)$ pip install --upgrade protobuf
Downloading/unpacking protobuf
  Downloading protobuf-3.2.0-py2.py3-none-any.whl (360kB): 360kB downloaded
Downloading/unpacking six>=1.9 (from protobuf)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking setuptools from https://pypi.python.org/packages/9a/9e/7614c97ca7f88a74352c726cfae1fa3f9823701d3a8b71f8c95ea581e493/setuptools-34.2.0-py2.py3-none-any.whl#md5=3b4e37333a741b711fb10dbe1a06d528 (from protobuf)
  Downloading setuptools-34.2.0-py2.py3-none-any.whl (389kB): 389kB downloaded
Downloading/unpacking appdirs>=1.4.0 (from setuptools->protobuf)
  Downloading appdirs-1.4.0-py2.py3-none-any.whl
Downloading/unpacking packaging>=16.8 (from setuptools->protobuf)
  Downloading packaging-16.8-py2.py3-none-any.whl
Downloading/unpacking pyparsing (from packaging>=16.8->setuptools->protobuf)
  Downloading pyparsing-2.1.10-py2.py3-none-any.whl (56kB): 56kB downloaded
Installing collected packages: protobuf, six, setuptools, appdirs, packaging, pyparsing
  Found existing installation: setuptools 2.2
    Uninstalling setuptools:
      Successfully uninstalled setuptools
Successfully installed protobuf six setuptools appdirs packaging pyparsing
Cleaning up...
```

Then I installed tensorflow from the pre-built .whl file and the tensorflow import worked!

Thanks again for the feedback!
