### ISSUE TITLE
Provide a working way to shut up warnings

### ISSUE THREAD

**Issue by seerdecker** [tensorflow/tensorflow#7652]
These messages appear whenever I run my program.

W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.

Now, I don't care that Tensorflow wasn't compiled to use SSE3 instructions, or AVX, or whatever. I don't want to see these messages. I also don't want to recompile from source to remove the warnings, install something else, play games with stderr, or whatever. I just want a clean way to shut up the warnings.

Here's my initialization code.

import tensorflow as tf
from tensorflow.python.framework import ops
tf.logging.set_verbosity(tf.logging.ERROR)
sess = tf.Session(config=tf.ConfigProto(device_count = {'GPU': 0}))

See? I asked for no warnings. Yet I still get them. That's a bug. Even if it's the intended behavior, please fix this.

Version is Tensorflow 1.0 on Linux.

Thank you!

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/default/logging.cc#L117

Try setting the environment variable
```
TF_CPP_MIN_LOG_LEVEL=2
```
to filter out INFO and WARNING logs.

**Comment by yaroslavvb** [comment]
As a general approach for filtering out uninteresting TensorFlow messages, it may be useful to run TF scripts as

`tf.sh myscript.py`

where `tf.sh` does

```
#!/bin/sh
# Run python script, filtering out TensorFlow logging
# https://github.com/tensorflow/tensorflow/issues/566#issuecomment-259170351
python $* 3>&1 1>&2 2>&3 3>&- | grep -v ":\ I\ " | grep -v "WARNING:tensorflow" | grep -v ^pciBusID | grep -v ^major: | grep -v ^name: |grep -v ^Total\ memory:|grep -v ^Free\ memory:
```

**Comment by seerdecker** [comment]
Thanks for the help. Yeah, I know I could filter out messages like this, that's what I meant by playing stderr games. But it's a pain.

The environment variable trick works. I'd suggest plugging that directly into tf.logging(), or at least documenting it somewhere, to be user-friendly. I did a search prior to reporting the problem. At least this bug will get indexed so it might help other people.

For posterity, add this to your programs to shut up the initial warnings:
os.environ["TF_CPP_MIN_LOG_LEVEL"]="2"

Thanks again.

**Comment by yaroslavvb** [comment]
The flip-side of this, is that if people don't see these warning, they may end up filing performance bugs (I get 3x speed-up on large matrix multiply when shutting up the warnings by adjusting TensorFlow build -- https://github.com/tensorflow/tensorflow/issues/7257#issuecomment-277456370)

**Comment by seerdecker** [comment]
I get that, but they already went out of their way by changing tf.logging.set_verbosity(tf.logging.ERROR). I'm fine with warnings by default, but there ought to be documented way to get rid of unwanted messages. Just like compiler warnings. Maybe something like tf.logging.set_perf_reports(0).

**Comment by vrv** [comment]
Would https://github.com/tensorflow/tensorflow/compare/master...vrv:master make you happy?

**Comment by seerdecker** [comment]
Yep!

**Comment by jucor** [comment]
Naive question, since the link in @vrv 's post wasn't permanent: what's the way that made you happy, @seerdecker , please?

**Comment by seerdecker** [comment]
I forget the exact API, it's been a while. Perhaps @vrv has the patch still? From memory, @vrv solution involved a call to disable the C++ logging.

Note that currently, os.environ["TF_CPP_MIN_LOG_LEVEL"]="2" does not work when using the GPU path on my machine [tensorflow-gpu (1.0.1)].

**Comment by vrv** [comment]
Yeah, I think I was making set_verbosity set the env var for C++ logging.  Sorry for never getting around to submit that patch, I might try to get to it this week.  However, it would be moot if the environment variable no longer works... :(

**Comment by jucor** [comment]
So in my case, the environment variable still works, as long as it is set
*before* importing tensorflow for the first time. If I set it after
importing TF, it doesn't have any effect. Do you observe the same behaviour?

>

**Comment by vrv** [comment]
I believe it's the case the environment variable is read statically the first time logging is requested, so if importing tensorflow causes something to log (which it may have only started doing in the past few months, much to my annoyance), then it is likely the case my patch won't fix the common cause of the problem since you'd have to import tensorflow before being able to use set_verbosity. :/

**Comment by jucor** [comment]
Ah, tough, but makes sense. Thanks for explanation Vijay!

**Comment by bharat8766** [comment]
Here is the solution:

tf.logging.set_verbosity(tf.logging.ERROR)

**Comment by PrakharPrashantSingh** [comment]
Hi all,

i don't know why i can't disable warning even after putting:

tf.logging.set_verbosity(tf.logging.ERROR) 
and this 
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' also i tried to put them both together, i also put these line before importing tensorflow as tf and also tried to put it after importing tensorflow but nothing is working.

Anyone have any other idea?

Thanks

**Comment by nkhdiscovery** [comment]
This is so much annoying, nothing works using tensorflow-gpu

**Comment by dare0021** [comment]
I got this to work
tf.get_logger().setLevel(3)

But this still doesnt suppress the one warning message I want suppressed
W tensorflow/core/grappler/utils/graph_view.cc:830] No registered 'MultiDeviceIteratorGetNextFromShard' OpKernel for GPU devices compatible with node {{node MultiDeviceIteratorGetNextFromShard}}
        .  Registered:  device='CPU'

I get multiple of these each epoch :(

**Comment by sanket1012** [comment]
[https://github.com/tensorflow/tensorflow/issues/8340#issuecomment-332212742](url)

**Comment by masouduut94** [comment]
If you only need to **get rid of warning outputs on the screen**, you might want to **clear the console** screen right after importing the tensorflow by using this simple command:

In windows:

    import os
    os.system('cls')

In Linux or Mac:

    import os
    os.system('clear')
