### ISSUE TITLE
Why, after using OneDNN, did I find that the GEMM used in the call stack extracted with perf is arm_gemm from ARM Compute instead of BRGEMM from OneDNN?

### ISSUE THREAD

**Issue by nanzh-19** [tensorflow/tensorflow#76525]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf serving 2.15

### Custom code

Yes

### Current behavior?

arm_gemm accounts for 65% of the runtime.

### Standalone code to reproduce the issue

```shell
This was discovered during performance analysis of a recommendation model while running inference on TensorFlow Serving.
```

**Comment by tilakrayal** [comment]
@nanzh-19,
Looks like this issue is more related to tf-serving. Could you please raise the request in the tf-serving repo from here for the quick resolution.

https://github.com/tensorflow/serving/issues

Thank you!

**Comment by nanzh-19** [comment]
ok, thank you.

**Comment by tilakrayal** [comment]
@nanzh-19,
Could you please feel free to move this issue to closed status, since it is already being tracked there? Thank you!
