### ISSUE TITLE
Model build uses incorrect input shape, since 2.16.1

### ISSUE THREAD

**Issue by ml-inr** [tensorflow/tensorflow#76576]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.16.1 and 2.17

### Custom code

Yes

### Current behavior?

Suppose that you have a model that splits its `input` as follows:
```
x = intuts[:,:,:-1]
mask = intuts[:,:,-1:]
```
Let further `x` be used in a custom layer: `y=layer(x)`. This layer should be build using the shape of `x`. However, since TF version 2.16.1, the layer fails to be build correctly. See a very simple example on google collab below. It was verified that in TF version 2.15 and below everything works as expected.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1ULMSpyTnkCFmg0OZYa_8hte2rnqY6iVx?usp=sharing
```

**Comment by tilakrayal** [comment]
@ml-inr,
Hi, By default the colab notebook is using tensorflow v2.17 which contains keras3.0 which was causing the error. Could you please try to import keras2.0 with the below commands.

```python
!pip install tf-keras

import tf_keras as keras
```

Also I have modified some steps and then the code was executed without error/fail. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3be9dfcccdeea4b1e45ba329458a4bdb/untitled2133.ipynb).

Thank you!

**Comment by ml-inr** [comment]
Hi! After switching to `tf-keras` everything works, thanks!

So, is this a known keras3.0 or TF-keras3.0 interaction bug? Are there plans to fix this? I understand that keras3.0 is now an independent project. I can post this issue on the keras page, if this makes sense.

**Comment by tilakrayal** [comment]
@ml-inr,
Yeah, as this is the bug in keras3.0, please try to raise the issue in [keras-team/keras](https://github.com/keras-team/keras/issues) repo & also it is resolved in tf-keras please feel free to move this issue to closed status. Thank you!
