### ISSUE TITLE
any pretrained models for tensorflow 1.0?

### ISSUE THREAD

**Issue by flyfj** [tensorflow/tensorflow#7661]
Now that TF has been updated to 1.0 with all the high-level apis, are there any supported pretrained models that are compatible with the new interfaces?

**Comment by aselle** [comment]
The previous trained models should actually work. The GraphDefs produced previous to 1.0 should be still loadable by 1.0 since none of the deprecated ops actually have been removed.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
