### ISSUE TITLE
TF-Lite converter bug in 2.17 for TransposeConv with quantized weights

### ISSUE THREAD

**Issue by bas-aarts** [tensorflow/tensorflow#76624]
On Apple M1 Pro with MacOs Sonoma 14.1.2 (23B92)
TensorFlow version 2.17.0 (not an issue with TF 2.16.1)
I ran this one a Samsung Galaxy S24 Ultra

sources + assets:
[TransposeConv_bug.zip](https://github.com/user-attachments/files/17158711/TransposeConv_bug.zip)

The zip contains a TF saved model and a convert.py script that converts it to a TF-Lite mode.
the zip file contains two TF-Lite models, and created with TF 2.16.1, and the other with 2.17.0.
convert.py also runs the TF-Lite model, but it needs to run on a target with GPU and/or NPU delegates to really see the issue.

When running the TF 2.16.1 TF-Lite model, the model runs on the NPU (Qualcomm QNN delegate).
When running the TF 2.17.0 TF-Lite model, the model runs on the CPU, using the XNNpack/TFLite delegates.

we see this log from TF-Lite on the device:
[tflite.log](https://github.com/user-attachments/files/17158819/tflite.log)
the interesting lines are:
`[27/Sept/2024:11:32:40 +08:00: profiler/warning] [job_id: j87gj31pd] [model.tflite] [tflite] tensorflow/lite/kernels/transpose_conv.cc:487 affine_quantization->scale->size != weights->dims->data[affine_quantization->quantized_dimension] (1 != 4)
`
and
`[27/Sept/2024:11:32:40 +08:00: profiler/warning] [job_id: j87gj31pd] [model.tflite] [tflite] tensorflow/lite/kernels/transpose_conv.cc:487 affine_quantization->scale->size != weights->dims->data[affine_quantization->quantized_dimension] (1 != 4)
`
the first one fails the NPU delegate check and the latter the GPU delegate check.

the check here is:
`https://github.com/tensorflow/tensorflow/blob/9e4fc3d09c298ca56bd11f72d2f1beb622a0f76b/tensorflow/lite/kernels/transpose_conv.cc#L485-L487`

This check is performed only when the Transpose Conv layer has float input but integral weights. This was not the case in TF 2.16, where the weights were first dequantized.
the check makes it looks like this must be a per channel quantized weight, which is clearly not the case.

So the converter generates code that the runtime forces back to the slower CPU delegates

**Comment by gaikwadrahul8** [comment]
Hi, @bas-aarts

I apologize for the delayed response, I was trying to replicate the same behavior from my end so to confirm, did you use [QAI Hub](https://app.aihub.qualcomm.com/docs/) with Samsung Galaxy S24 Ultra device or actual physical device ? 

If you don't mind could you please guide me to replicate the same behavior from my end also. 

Thank you for your cooperation and patience.

**Comment by bas-aarts** [comment]
Yes I did use AI Hub, but this does use an actual physical Samsung Galaxy S24 Ultra.
The AI Hub TFLite runtime uses theTF-Lite GPU delegate, as well as the QNN NPU delegate.

To reproduce you'll need a TF-Lite runtime that can use either of these, and possible opt-in using:
`  interpreter.experimental_delegate = tf.lite.experimental.load_delegate('some delegate shared library')`

I see a PR above, which aI hope means you were able to reproduce the issue.

**Comment by pkgoogle** [comment]
The current expectation is that the PR will resolve this issue.

**Comment by bas-aarts** [comment]
since the PR is still in draft, any idea in which release I can expect the fix?

**Comment by pkgoogle** [comment]
Hi @bas-aarts, feel free to take the code/diff from the PR if you need it sooner, I would expect the fix to land 1 or 2 releases from now.

**Comment by advaitjain** [comment]
Should be fixed with https://github.com/tensorflow/tensorflow/commit/dde56340610b37d2f2696b654be50a74dd25ff84
