### ISSUE TITLE
How to determines which GEMM used in TensorFlow

### ISSUE THREAD

**Issue by nanzh-19** [tensorflow/tensorflow#76632]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.15

### Custom code

Yes

### Current behavior?

Where is the code that determines which GEMM to use in TensorFlow, such as using Eigen or oneDNN, and how does it decide to use different types of GEMM?

### Standalone code to reproduce the issue

```shell
Such as arm_gemm, brgemm, etc.
```

**Comment by tilakrayal** [comment]
@nanzh-19,
Can you please elaborate about the statement which was mentioned. Also, please specify the Use Cases for this feature. Thank you!
