### ISSUE TITLE
Dockerfile manual build central repo URL is Incorrect

### ISSUE THREAD

**Issue by sh0rtfuse** [tensorflow/tensorflow#7665]
Dockerfile and Dockerfile.gpu have URLs that do not point to valid repo

Current URL in Dockerfile and Dockerfile.gpu

http://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.0.0-cp27-none-linux_x86_64.whl

http://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.0.0-cp27-none-linux_x86_64.whl

Changing the version number to 1.0.0 fixes the problem. 

Working URL: http://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0-cp27-none-linux_x86_64.whl

Not sure if the intent was to leave it at 0.0.0. If so, comments instructing the user to edit the URL to the current version would be helpful.

**Comment by aselle** [comment]
@gunan, @yifeif, could you take a look?

**Comment by yifeif** [comment]
@caisq assume this was intentional?

**Comment by caisq** [comment]
@yifeif That is correct - these incorrect URLs are intentional. The strings like 0.0.0 are replaced by our docker build script. For example, see: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/parameterized_docker_build.sh#L215

**Comment by caisq** [comment]
I'm closing this issue now.
