### ISSUE TITLE
Error message could be improved

### ISSUE THREAD

**Issue by rpryzant** [tensorflow/tensorflow#7675]
If your try and initialize a `dynamic_rnn` without specifying an `initial_state` **OR** `dtype`, you get this enigmatic error message:

`If no initial_state is provided, dtype must be`

I don't think that message is very clear. Something better would be along the lines of, 

`If no initial_state is provided, a dtype must be specified`

This error is thrown at 
tensorflow/tensorflow/python/ops/rnn.py, line 518

**Comment by aselle** [comment]
@rpyzant, would you be willing to submit a quick pull request for this?

**Comment by rpryzant** [comment]
Done, see https://github.com/tensorflow/tensorflow/pull/7678

**Comment by aselle** [comment]
Thanks so much!
