### ISSUE TITLE
DOCS for offsets in extract_glimpse don't match Implementation

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#7681]
Docs state:
>    offsets: A `Tensor` of type `float32`.
      A 2-D integer tensor of shape `[batch_size, 2]` containing
      the x, y locations of the center of each window.

whereas [the implementation states](https://github.com/tensorflow/tensorflow/blob/754048a0453a04a761e112ae5d99c149eb9910dd/tensorflow/core/kernels/attention_ops.cc#L92):
>      // calling TensorFlow operates with (y,x) as indices.

Notice x,y vs y,x

Here is a rough demo of the issue:
```python
arr = np.zeros((1,5,5,1), dtype=np.float32)
arr[0, 3,2] = 1
arr = tf.constant(arr)
glim = tf.image.extract_glimpse(arr, (1,1), offsets=tf.constant([(2,3)], dtype=tf.float32)[:,::-1] + 1, normalized=False, centered=False)
sess.run(glim)
```
```
> array([[[[ 1.]]]], dtype=float32)
```

It appears that the docs are wrong and that the comment is right.

**Comment by cwhipkey** [comment]
yes, this looks like a bug in the docs.  I'll submit a fix to the docs.

**Comment by cancan101** [comment]
Is that the right place to fix or would it be better to take x y which is more normal and would simplify op code ad well.

**Comment by cancan101** [comment]
Also not sure if there are any additional docs fixes outlined in https://github.com/tensorflow/tensorflow/issues/2134

**Comment by cwhipkey** [comment]
In the immediate term, fixing the docs seems good to do since any changes in the behavior will break backwards compatibility and so requires more stages to accomplish.

**Comment by skye** [comment]
https://github.com/tensorflow/tensorflow/commit/f1dd0e32522bd183d422bdac75137ebba2375327
