### ISSUE TITLE
TF model trained with 2.7 has error in later versions with no OpKernel error

### ISSUE THREAD

**Issue by zhaoting-wu** [tensorflow/tensorflow#76826]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.16.1

### Custom code

No

### Python version

3.10

### Current behavior?

Models trained with TF 2.7 is not able to run in later versions, like 2.16.1, with "No OpKernel was registered to support Op 'BoostedTreesBucketize'" error.

### Standalone code to reproduce the issue

We are using Nvidia's Triton model inference platform, when using the latest image which builds upon TF 2.16.1 to load certain models trained with TF 2.7, it runs into error as below
"No OpKernel was registered to support Op 'BoostedTreesBucketize' used by {{node transform/transform/bucketize/apply_buckets/assign_buckets_all_shapes/assign_buckets/BoostedTreesBucketize}} with these attrs: [_output_shapes=[[?]], num_features=1]"  

However, BoostedTreesBucketize shows unchanged since TF 2.7 to the latest version: https://github.com/tensorflow/tensorflow/blob/v2.17.0/tensorflow/core/ops/boosted_trees_ops.cc#L844. 

Is there any change around boosted tree ops or this specific op after 2.7 which leads to this error?

Detailed logs:
```shell
tensorflow/cc/saved_model/loader.cc:337] SavedModel load for tags { serve }; Status: fail: INVALID_ARGUMENT: No OpKernel was registered to support Op 'BoostedTreesBucketize' used by {{node transform/transform/bucketize/apply_buckets/assign_buckets_all_shapes/assign_buckets/BoostedTreesBucketize}} with these attrs: [_output_shapes=[[?]], num_features=1]
Registered devices: [CPU]
Registered kernels:
  <no registered kernels> [[transform/transform/bucketize/apply_buckets/assign_buckets_all_shapes/assign_buckets/BoostedTreesBucketize]]"
```

**Comment by tilakrayal** [comment]
@zhaoting-wu,
There are multiple changes/updates that happened from tensorflow v2.7 to latest versions 2.16 and 2.17. Also from tensorflow 2.16 the Keras has been moved from Keras2.0 to Keras3.0. I suggest to convert the code to tensorflow v2.16, 2.17 apis and test the model.

https://keras.io/keras_3/

Thank you!

**Comment by zhaoting-wu** [comment]
Hi @tilakrayal, thanks for the response! 

Based on the log, we noticed the errored model called `bucketize` transform in Tensorflow so that it touched the `BoostedTreesBucketize` op (`[[transform/transform/bucketize/apply_buckets/assign_buckets_all_shapes/assign_buckets/BoostedTreesBucketize]]`), but `bucketize` transform doesn't show as deprecated as `BoostedTreesBucketize`. Does that mean `bucketize` just started to call other substitute ops after deprecating `BoostedTreesBucketize`? 

From the [release note](https://github.com/tensorflow/tensorflow/releases/tag/v2.8.0), `BoostedTreesBucketize` appears deprecated since TF 2.8 and removed since TF 2.9: ```
Due to security issues (see section below), all boosted trees code has been deprecated. Users should switch to [TensorFlow Decision Forests](https://github.com/tensorflow/decision-forests). TF's boosted trees code will be eliminated before the branch cut for TF 2.9 and will no longer be present since that release.
```.  We tried Triton image built on TF 2.9 and this error starts to show up. Does that mean this issue can be resolved by simply switching our TF dependency for model training to TF2.9+, but still keeping the call of `bucketize`?

**Comment by tilakrayal** [comment]
@zhaoting-wu,
As mentioned in the release document, the BoostedTreesBucketize appears deprecated since TF 2.8 and removed since TF 2.9.  Switching from deprecated `tf.raw_ops.BoostedTreesBucketize` to `tf.searchsorted` in `tft.apply_buckets`. This fixes bug with large int64 values being incorrectly mapped and allows to simplify `tft.apply_buckets` implementation.

Thank you!
