### ISSUE TITLE
Looking for a function to replace sklearn.mixture.GaussianMixture.predict_proba(X)

### ISSUE THREAD

**Issue by longwoo** [tensorflow/tensorflow#7686]
In sklearn, I can use `predict_proba(X)` if I want to Predict posterior probability of data per each component.

However, I cannot find a similar function in 'tensorflow gmm_ops'

Did anyone find that before?

**Comment by carlthome** [comment]
Tip: Try asking on StackOverflow with the tag tensorflow instead (more people answer there). GitHub is mostly for bugs.
