### ISSUE TITLE
Docs about installing Tensorflow for Ubuntu don't always distinguish between python and python3

### ISSUE THREAD

**Issue by fcole90** [tensorflow/tensorflow#7690]
In this page [Installing TensorFlow on Ubuntu ](https://www.tensorflow.org/install/install_linux), there are some commands to install Python in Ubuntu. Tough Ubuntu distinguishes between python (2.7) and python3 (3.n) packages. So I think that the page should be updated to distinguish the two cases, as using the current procedure may result in the creation of a python (2.7) environment when a python3 was needed or preferred.

### [virtualenv](https://www.tensorflow.org/install/install_linux#InstallingVirtualenv)

At the point 1:
```
sudo apt-get install python-pip python-dev python-virtualenv # for Python 2.7
sudo apt-get install python3-pip python3-dev python3-virtualenv # for Python 3.n
```
At the point 2:
```
python -m virtualenv --system-site-packages -p python targetDirectory # for Python 2.7
python3 -m virtualenv --system-site-packages -p python3 targetDirectory # for Python 3.n
```

### ["native" pip](https://www.tensorflow.org/install/install_linux#InstallingNativePip)

Prerequisites:
```
sudo apt-get install python-pip python-dev # for Python 2.7
sudo apt-get install python3-pip python3-dev # for Python 3.n
```

**Comment by gunan** [comment]
If you only have python3 installed on your system, `python` and `pip` will use `python3` and `pip3` respectively. To add to all of these, you can even install more versions of python, and access them using `python3.4` or `python3.5` or `python3.6`.
All of these possibilities are omitted from the docs for simplicity.
In most users cases, there is only one version of python installed, so the instructions will work.
For users with multiple python versions installed, we trust users to correctly access their desired python installation.

**Comment by fcole90** [comment]
I'm sorry but using python 2.7 or 3.n is a different issue than just choosing a point version, and accordingly the guide makes a distinction in most cases except the ones I mentioned.

If a user follows each step, including the [first](https://www.tensorflow.org/install/install_linux#InstallingVirtualenv), he/she will end up installing python (2.7). For the user to skip that line he/she should be aware both that that command is going to install python (2.7) and how to find the python3 versions of the listed packages. As the guide makes a distinction in many cases between python and python3, the user could wrongly consider that line valid for both. 

Also, for python3, the command ```virtualenv``` cannot be invoked in that way on Ubuntu (tested on 16.04), but only using ```python3 -m virtualenv```. Installing ```python-virtualenv``` causes the installation of the version for python 2.7.

**Comment by gunan** [comment]
I have not considered the invalidity of our virtualenv command for py3. You have a good point there. Id rather have a shorter installation guide, but we should have a working install path for all versions of python installed.

**Comment by gunan** [comment]
I have checked this again, but for me having `python-virtualenv` command is sufficient.
You simply need to feed the `-p` flag, and thats it.
I tested this on a clean docker image as follows:
```
$ docker run -it ubuntu:16.04 bash
$ apt-get update
$ apt-get install python3 python-virtualenv
$ virtualenv -p python3 tf
$ source tf/bin/activate
$ python3 --version
Python 3.5.2
```

Anyway, we are updating the documentation with more stuff.

**Comment by fcole90** [comment]
Good, it makes the docs more concise than my proposal.

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow documentation. Thank you.
