### ISSUE TITLE
How to build tensorflow to use SSE3 instructions?

### ISSUE THREAD

**Issue by cjliux** [tensorflow/tensorflow#7693]
When I am running tensorflow code, it prompts that `The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.`. I have installed tensorflow using pip and don't know how to deal with that. Any one can help with me?

**Comment by sydney0zq** [comment]
I have the same issue. But I also does not how to solve it.

**Comment by inflation** [comment]
@sydney0zq Make sure you enable `--config=opt` in compile time.

**Comment by chanishagarwal** [comment]
Am facing the same issue with tensor flow. can you please elaborate how to use above solution

**Comment by damienogrady** [comment]
Me too

**Comment by melvincabatuan** [comment]
Same here:

```
$ python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello = tf.constant('Hello World!')
>>> sess = tf.Session()
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
>>> print(sess.run(hello))
b'Hello World!'
```

**Comment by cjliux** [comment]
The binary distribution of tensorflow-gpu, which is provided through pip, is compiled with little support of advanced features of main stream cpu for maximum compatibiliy. So in order to use these features, you have to download the source from github and compile it youself following the steps illustrated by the official site of tensorflow. That's all.

**Comment by melvincabatuan** [comment]
Yeah I was hoping I could build it within 'Bash for Windows' but no luck... stuck at "Extracting Bazel installation..."

**Comment by cjliux** [comment]
I had encountered that problem before in linux. You may try to reinstall bazel using apt-get and do it again. It will work, but patience is needed.

**Comment by damienogrady** [comment]
Patience?  Oh dear, then I'm really in trouble.

OK, I'll try - thanks for your help.

On Wed, 2017-02-22 at 03:02 -0800, cjliux wrote:

I had encountered that problem before in linux. You may try to reinstall bazel using apt-get and do it again. It will work, but patience is needed.

**Comment by melvincabatuan** [comment]
Successfully built it from source (Github Master branch) in my Ubuntu machine: (No more SSE3 warnings...)
https://youtu.be/1Gd6e5BLkwo

**Comment by coverpage** [comment]
@melvincabatuan Do you notice any significant improvement in performance. I'm thinking of building from source as well.

**Comment by cjliux** [comment]
For me, not much improvement actually. But for larger scale training, it will be significant perhaps...
