### ISSUE TITLE
How to use the Distributed Tensorflow

### ISSUE THREAD

**Issue by githubier** [tensorflow/tensorflow#7695]
I have three node, which two use the CPU-mode tensorflow, and the left use the GPU-mode tensorflow.
Some website may just use the official example, but I don't know how to execute the python code on the terminal, some use themselves example. but I cannot run it successful. Can you tell me how to write the python code and how to execute it on my terminal. Should I use the docker?
Anyone can teach me?

**Comment by yaroslavvb** [comment]
This seems more appropriate for stackoverflow, this list is for bugs/feature in Tensorflow
