### ISSUE TITLE
freeze_graph inspect_checkpoint,  Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator

### ISSUE THREAD

**Issue by apiszcz** [tensorflow/tensorflow#7696]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
Nothing directly applicable to the observed error.

### Environment info
TF 0.12.1, Windows 10/64, Python 3.5/64

Installed version of CUDA and cuDNN: 
8.0, 5.1

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

**inspect_checkpoint**

lib\python\python lib\tensorflow_cpu\tensorflow\python\tools\inspect_checkpoint.py --file_name model.ckpt-250514.data-00000-of-00001 --tensor_name-''

2017-02-20 08:23:19.291800: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\util\tensor_slice_reader.cc:95] Could not open model.ckpt-250514.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Unable to open table file model.ckpt-250514.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

**freeze_graph**

Similar error
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file model.ckpt-250514.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2_445 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_445/tensor_names, save/RestoreV2_445/shape_and_slices)]]

DataLossError (see above for traceback): Unable to open table file C:\g\vx\data\jhole\model\model.ckpt-250514.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
         [[Node: save/RestoreV2_780 = RestoreV2[dtypes=[DT_INT64], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_780/tensor_names, save/RestoreV2_780/shape_and_slices)]]

### What other attempted solutions have you tried?
1. A few different checkpoint files.
2. Tried freeze_graph using TF 1.0, same result

### Logs or other output that would be helpful
Messages similar "Similar error" above is repeated many times.

**Comment by yaroslavvb** [comment]
similar issue was solved here http://stackoverflow.com/questions/41048819/how-to-restore-a-model-by-filename-in-tensorflow-r12

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by AnranQi** [comment]
Anyone who solve this problem?

**Comment by tangyanlin** [comment]
just regard the prefix as checkpoint,  like:
lib\python\python lib\tensorflow_cpu\tensorflow\python\tools\inspect_checkpoint.py --file_name model.ckpt-250514

**Comment by LingjiaDeng** [comment]
I saved the model using V2 format, which gives me three files:

- model-10000.data-00000-of-00001
- model-10000.index
- model-10000.meta

As @tangyanlin metioned, using the prefix. My input parameter is `--input_checkpoint checkpoints/model-10000` (NOT including the period) which works.

**Comment by zhangchunsheng** [comment]
2017-11-19 22:26:38.039878: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open train/model.ckpt-0.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

**Comment by guotong1988** [comment]
Thank you 
@LingjiaDeng

**Comment by LiuChiachi** [comment]
> I saved the model using V2 format, which gave me three files:
> 
> * model-10000.data-00000-of-00001
> * model-10000.index
> * model-10000.meta
> 
> As @tangyanlin metioned, use the prefix. My input parameter is `--input_checkpoint=checkpoints/model-10000` (NOT including the period) which works.

Thank you! And I think it's import to check whether GPU has enough space. I killed other works on NVIDIA and did what you said and I succeeded!

**Comment by codexponent** [comment]
ty to @tangyanlin @LingjiaDeng 
Avoid doing this on the line on the corresponding config file that you are using:
```
fine_tune_checkpoint: "/home/ubuntu/models/ssd_inception_v2_coco_2018_01_28/model.ckpt.data-00000-of-00001"
``` 
as this gives you the error. I **solved** mine using this:
```
fine_tune_checkpoint: "/home/ubuntu/models/ssd_inception_v2_coco_2018_01_28/model.ckpt"
```

**Comment by carloskekwa** [comment]
i can't find any solution for that

**Comment by Ehsan-Yaghoubi** [comment]
> ty to @tangyanlin @LingjiaDeng
> Avoid doing this on the line on the corresponding config file that you are using:
> 
> ```
> fine_tune_checkpoint: "/home/ubuntu/models/ssd_inception_v2_coco_2018_01_28/model.ckpt.data-00000-of-00001"
> ```
> 
> as this gives you the error. I **solved** mine using this:
> 
> ```
> fine_tune_checkpoint: "/home/ubuntu/models/ssd_inception_v2_coco_2018_01_28/model.ckpt"
> ```

I changed `places2.ckpt-6666.data-00001-of-00002` to `places2.ckpt-6666` and it worked.

**Comment by ansumandas441** [comment]
Had a similar issue.
Used legacy optimizers like :
`from tensorflow.keras.optimizers.legacy import Adam`
instead of :
`from tensorflow.keras.optimizers import Adam`

worked for me.
