### ISSUE TITLE
How to upgrade Tensorflow from V0.10.0 to V1.0 ?

### ISSUE THREAD

**Issue by szsongyj** [tensorflow/tensorflow#7697]
Hi ,dear
    I installed tensorflow V0.10.0 by compiling source code in 2016.   
    Now Is there an simplest way for me to upgrade tensorflow from V0.10.0 to V1.0?
    Thank you & Best Regards,

### Environment info
Operating System: Ubuntu16.04

syj@syj-dl:~/tensorflow$ cat /etc/issue
Ubuntu 16.04 LTS \n \l

syj@syj-dl:~/tensorflow$ which python
/home/syj/anaconda2/bin/python

syj@syj-dl:~/tensorflow$ python --version
Python 2.7.12 :: Anaconda custom (64-bit)

Installed version of CUDA and cuDNN: CUDA8.0 CUDNN5.0
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

syj@syj-dl:/usr/local/cuda-8.0/lib64$ ls libcud*
libcudadevrt.a    libcudart.so.8.0.27  libcudnn.so.5
libcudart.so      libcudart_static.a   libcudnn.so.5.1.5
libcudart.so.8.0  libcudnn.so          libcudnn_static.a

syj@syj-dl:~/tensorflow/tensorflow/models/rnn$ python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.8.0 locally
0.10.0

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`)
syj@syj-dl:~/tensorflow$ git rev-parse HEAD
69d67717f7b3da135b8904822838823658da183f

2. The output of `bazel version`
syj@syj-dl:~$ bazel version
Build label: 0.3.1
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jul 29 09:09:52 2016 (1469783392)
Build timestamp: 1469783392
Build timestamp as int: 1469783392

**Comment by yaroslavvb2** [comment]
There was an email to TensorFlow discuss mailing list with upgrade
instructions, cc @aselle in case there's a more canonical place

**Comment by yaroslavvb** [comment]
There was an email to TensorFlow discuss mailing list with upgrade instructions, cc @aselle in case there's a more canonical place

**Comment by szsongyj** [comment]
@yaroslavvb  Thank you !

I have successfully installed tensorflow v1.0 by  following the 'Virtualenv installation' section of [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md](url)

Thank you
`
syj@syj-dl:~$ virtualenv --system-site-packages ~/tensorflow-v1.0

Running virtualenv with interpreter /home/syj/anaconda2/bin/python2
New python executable in /home/syj/tensorflow-v1.0/bin/python2
Also creating executable in /home/syj/tensorflow-v1.0/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

syj@syj-dl:~$ source ~/tensorflow-v1.0/bin/activate
(tensorflow-v1.0) syj@syj-dl:~$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.0-cp27-none-linux_x86_64.whl

(tensorflow-v1.0) syj@syj-dl:~$ pip install --upgrade $TF_BINARY_URL
Collecting tensorflow-gpu==1.0.0 from https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.0-cp27-none-linux_x86_64.whl
  Downloading https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.0-cp27-none-linux_x86_64.whl (95.0MB)
    100% |████████████████████████████████| 95.0MB 19kB/s 
Requirement already up-to-date: mock>=2.0.0 in ./anaconda2/lib/python2.7/site-packages (from tensorflow-gpu==1.0.0)
Collecting numpy>=1.11.0 (from tensorflow-gpu==1.0.0)
  Downloading numpy-1.12.0-cp27-cp27mu-manylinux1_x86_64.whl (16.5MB)
    100% |████████████████████████████████| 16.5MB 38kB/s 
Collecting protobuf>=3.1.0 (from tensorflow-gpu==1.0.0)
  Downloading protobuf-3.2.0-cp27-cp27mu-manylinux1_x86_64.whl (5.6MB)
    100% |████████████████████████████████| 5.6MB 51kB/s 
Requirement already up-to-date: wheel in ./tensorflow-v1.0/lib/python2.7/site-packages (from tensorflow-gpu==1.0.0)
Requirement already up-to-date: six>=1.10.0 in ./tensorflow-v1.0/lib/python2.7/site-packages (from tensorflow-gpu==1.0.0)
Requirement already up-to-date: funcsigs>=1; python_version < "3.3" in ./anaconda2/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow-gpu==1.0.0)
Requirement already up-to-date: pbr>=0.11 in ./anaconda2/lib/python2.7/site-packages (from mock>=2.0.0->tensorflow-gpu==1.0.0)
Requirement already up-to-date: setuptools in ./tensorflow-v1.0/lib/python2.7/site-packages (from protobuf>=3.1.0->tensorflow-gpu==1.0.0)
Requirement already up-to-date: appdirs>=1.4.0 in ./tensorflow-v1.0/lib/python2.7/site-packages (from setuptools->protobuf>=3.1.0->tensorflow-gpu==1.0.0)
Requirement already up-to-date: packaging>=16.8 in ./tensorflow-v1.0/lib/python2.7/site-packages (from setuptools->protobuf>=3.1.0->tensorflow-gpu==1.0.0)
Requirement already up-to-date: pyparsing in ./tensorflow-v1.0/lib/python2.7/site-packages (from packaging>=16.8->setuptools->protobuf>=3.1.0->tensorflow-gpu==1.0.0)
Installing collected packages: numpy, protobuf, tensorflow-gpu
  Found existing installation: numpy 1.10.4
    Not uninstalling numpy at /home/syj/anaconda2/lib/python2.7/site-packages, outside environment /home/syj/tensorflow-v1.0
  Found existing installation: protobuf 3.0.0b2
    Not uninstalling protobuf at /home/syj/anaconda2/lib/python2.7/site-packages, outside environment /home/syj/tensorflow-v1.0
Successfully installed numpy-1.12.0 protobuf-3.2.0 tensorflow-gpu-1.0.0
(tensorflow-v1.0) syj@syj-dl:~$ deactivate
syj@syj-dl:~$ source ~/tensorflow-v1.0/bin/activate
(tensorflow-v1.0) syj@syj-dl:~$ python
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
>>> tf.__version__
'1.0.0'
>>> 
`
