### ISSUE TITLE
Quantize nodes via Transform Graph tool cause error

### ISSUE THREAD

**Issue by Gubarev** [tensorflow/tensorflow#7698]
I am trying to quantize my model by following this [README](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md)

I have faced with issue **No attr named 'T' in NodeDef:** when I run **transform_graph** tool with **quantize_nodes** option both for my model and example model (Inception V3).

```
path/to/transform_graph --in_graph=model.pb --out_graph=optimized.pb --inputs='input:0' --outputs='regression:0,classification:0' --transforms='quantize_weights quantize_nodes'
```

Here is relevant part of output:

```
2017-02-20 17:14:19.944778: I tensorflow/tools/graph_transforms/transform_graph.cc:257] Applying quantize_nodes
2017-02-20 17:14:20.599637: E tensorflow/tools/graph_transforms/transform_graph.cc:203] No attr named 'T' in NodeDef:
	 [[Node: pool = MaxPool[ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1]](pool/control_dependency)]]
```

### Environment info

Doesn't seems too important. Tested on two machines with different configurations (referred as M for Mac and U for Ubuntu below).
 
Operating System:
M: macOS Sierra 10.12.3
U: Ubuntu 16.04.2 LTS x86_64

TF has been installed from source. Commit hash:
M: b6f16b8166e3a7761f607be66d46acbd37dfaf43
U: c56c873fbaf976d26d487ad57c8efbc87f05331c

Bazel version / build label
M: 0.4.4-homebrew
U: 0.4.4

### Minimal reproducible example
Download & unpack inception V3. Run the tool (modify path to tool and model if necessary).

```
curl http://download.tensorflow.org/models/image/imagenet/inception-2015-12-05.tgz -o /tmp/inceptionv3.tgz
tar xzf /tmp/inceptionv3.tgz -C /tmp/
bazel-bin/tensorflow/tools/graph_transforms/transform_graph --in_graph=/tmp/classify_image_graph_def.pb --out_graph=optimized.pb --inputs='input:0' --outputs='regression:0,classification:0' --transforms='quantize_weights quantize_nodes'
```

### What other attempted solutions have you tried?
I have tried to run quantisation on different OS (Mac and Ubuntu) and slightly different revisions of master. Also, initially, I have tried to quantize nodes of my own model, not Inception. In all cases result is the same: error.

**Comment by aselle** [comment]
@petewarden, could you please take a look?

**Comment by scangh** [comment]
@Gubarev, 
you can try this :
bazel-bin/tensorflow/tools/graph_transforms/transform_graph --in_graph=/tmp/classify_image_graph_def.pb --out_graph=optimized.pb --inputs='input:0' --outputs='regression:0,classification:0' --transforms='**add_default_attributes** quantize_weights quantize_nodes'

**Comment by Gubarev** [comment]
Now I see that README I referred has been updated since I opened my issue. With **add_default_attributes** option the transform_graph does not produce errors. Thanks to @scangh for noticing! So this issue is appeared to be README issue and already resolved.
