### ISSUE TITLE
Error building from source

### ISSUE THREAD

**Issue by colourxb** [tensorflow/tensorflow#7699]
Hi,

I'm trying to build from master branch and getting this error during the ./configure step

`Please specify the location of python. [Default is /Users/lucasliu/anaconda/bin/python]: 
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] N
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] N
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] N
No XLA JIT support will be enabled for TensorFlow
Found possible Python library paths:
  /Users/lucasliu/anaconda/lib/python2.7/site-packages
Please input the desired Python library path to use.  Default is [/Users/lucasliu/anaconda/lib/python2.7/site-packages]

Using python library path: /Users/lucasliu/anaconda/lib/python2.7/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] N
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] N
No CUDA support will be enabled for TensorFlow
Configuration finished

ERROR: /Users/lucasliu/tensorflow/tensorflow/models/syntaxnet/syntaxnet/BUILD:174:1: no such package 'util/utf8': BUILD file not found on package path and referenced by '//tensorflow/models/syntaxnet/syntaxnet:segmenter_utils'.
ERROR: /Users/lucasliu/tensorflow/tensorflow/models/syntaxnet/syntaxnet/BUILD:95:1: no such package 'util/utf8': BUILD file not found on package path and referenced by '//tensorflow/models/syntaxnet/syntaxnet:utils'.
ERROR: /Users/lucasliu/tensorflow/tensorflow/models/syntaxnet/syntaxnet/BUILD:162:1: no such package 'util/utf8': BUILD file not found on package path and referenced by '//tensorflow/models/syntaxnet/syntaxnet:char_properties'.
ERROR: Evaluation of query "deps(((//tensorflow/... - //tensorflow/contrib/nccl/...) - //tensorflow/examples/android/...))" failed: errors were encountered while computing transitive closure.`

Operating System: Mac OS Sierra Version 10.12.3
Bazel: 0.4.4-homebrew
Python: 2.7 

tf/master
No CUDA
No cuDNN

I suspect this is due to my network timeout to bazel mirror site. Could you please advise?

**Comment by martinwicke** [comment]
It appears to me you have cloned the models repo inside the tensorflow repo, and now bazel is confused. 

syntaxnet isn't part of the tensorflow repo, and shouldn't appear inside the tensorflow directory.

**Comment by colourxb** [comment]
Thanks Martin. You are right. I was trying to get the retrain of Inception's final layer working so cloned the model repo myself. Removing it solved the issue. Thanks a lot.
