### ISSUE TITLE
ERROR: Evaluation of query "deps((//tensorflow/... - //tensorflow/examples/android/...))" failed

### ISSUE THREAD

**Issue by cjliux** [tensorflow/tensorflow#7701]
root@cjliux-comp:/usr/local/lib/python2.7/dist-packages/tensorflow-1.0.0# ./configure 
Please specify the location of python. [Default is /usr/bin/python]: 
Please specify optimization flags to use during compilation [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? (Linux only) [Y/n] y
jemalloc enabled on Linux
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] n
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] n
No XLA JIT support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
  /usr/local/caffe/python
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Using python library path: /usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] n
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5
Please specify the location where cuDNN 5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 6.1
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.......
ERROR: infinite symlink expansion detected
[start of symlink chain]
/usr/local/lib/python2.7/dist-packages
/usr/local/lib/python2.7/dist-packages/tensorflow-1.0.0/util/python/python_lib
[end of symlink chain]
.
ERROR: Evaluation of query "deps((//tensorflow/... - //tensorflow/examples/android/...))" failed: errors were encountered while computing transitive closure.

Do any one know what that mean and how to fix it?

**Comment by cjliux** [comment]
I have found the problem. It's because I have been trying to build tensorflow in `/usr/local/lib/python2.7/dist-distributions`, and that conflicts with the installation path of tensorflow, which I have left it default.

**Comment by SebOh** [comment]
I'm currently having the same error. What did you do exactly by 
> placing the source of tensorflow in /usr/local

Can you help me?
