### ISSUE TITLE
Visualize experiment arguments in Tensorboard

### ISSUE THREAD

**Issue by mmuneebs** [tensorflow/tensorflow#7708]
**Feature request**

I am wondering if it's possible to store the arguments that we pass to the training script to be stored as part of other summaries, and have a way to see those arguments/parameters as notes in a separate tab in Tensorboard.
Reason: It's often hard to track individual training runs and relate them to the training/network config if you change training and network parameters frequently which always happens during hyperparameter search. We can do it manually too but if included in Tensorboard, it would make it one go-to visualizer and comparison tool for everything.
One method of doing this that comes to mind is using the `tf.app.flags.FLAGS` arguments. This would keep everything standardized. Or we could also support `argparse` directly.
Is this something in line with Tensorboard's philosophy or is it too straightforward to be a special feature?

**Comment by dandelionmane** [comment]
One thing I've intended to add for a while is explicit hyperparameter support to TensorBoard.
The way I imagine this working is, when you create a summary.FileWriter, you would add a configuration protobuf for the "run" which has a universally unique ID, as well as a bunch of configurable metadata for keeping hyperparameter settings. 

Then, this data would be encoded with the run and we could build hyperparameter awareness into TensorBoard.

The proto would look like this: 
```
message Run {
  string uuid = 1;
  string name = 2;
  string description = 3;
  string dataset = 4; // optional param with common dataset name
  repeated HParam hparams = 5;
  int64 start_time = 6;
  // End is 0 until run is complete or if failed.
  int64 end_time = 7;
}

message HParam {
// Protocol buffer holding hyperparameters.
// Examples of hyperparameters:
//   learning_rate = 0.1,
//   num_hidden_units = 100,
//   activations = ['relu', 'tanh']
message HParam {
  // Required: unique name for this hyperparameter.
  // Names can be nested into groups using '/' as a delimiter.
  string name = 1;

  // Required: tensor representing the value of the hyperparameter.
  TensorProto value = 2;

  // Optional: A human-readable, short, display name for display in a tool UI. If unset, name will be used
  string display_name = 3;

  // Optional: A long-form description of this hyperparameter tool UI.
  string description = 4;
}
```

This wouldn't be a direct integration with flags; the user code would be responsible for encoding the hyperparameters. 

What do you think of this design?

**Comment by Mazecreator** [comment]
I have more details here which may help this discussion:
https://github.com/tensorflow/tensorflow/issues/4714

**Comment by mmuneebs** [comment]
Hi @dandelionmane, that looks good as long as it's simple enough to do a single loop over all argument flags to put them in the protobuf.
Looking at the above referenced issue, it would also be good to allow pushing python scalars (not tensors) to the existing tabs like Scalars/Histograms/Images. I do it right now with `tf.py_func()` which is an overkill to add varying python scalars. (Example use case is for monitoring non-tf native python queues.)
Once we have some solution, it would be cool to allow filtering of runs using these hyperparameters too.

**Comment by scientist1642** [comment]
@dandelionmane you mentioned that Hyperparameter & run description for tensorboard was under active development here #2454.
I wonder did you mean something else that is already implemented as of now?

**Comment by rmst** [comment]
[**chiboard**](http://github.com/rmst/chi) shows run arguments for experiements/runs automatically. Would be also happy about run descriptions in tensorboard though, especially for comparing multiple runs.

**Comment by wchargin** [comment]
I'm migrating this to our new repository at https://github.com/tensorflow/tensorboard/issues/46. See you there! :-)
