### ISSUE TITLE
Import Module Error: Undefined Symbol in TensorFlow Lite Runtime After Build with Blaze and Flex support

### ISSUE THREAD

**Issue by dev2xl** [tensorflow/tensorflow#77092]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.17

### Custom code

Yes

### OS platform and distribution

FROM public.ecr.aws/lambda/python:3.12

### Python version

3.12

### Bazel version

6.5

### GCC/compiler version

12.4

### Current behavior?

I successfully built the TensorFlow Lite pip package with Flex using Blaze. However, when I attempted to load the TensorFlow Lite runtime, I encountered the following error:

`Runtime.ImportModuleError: Unable to import module 'entry': /var/lang/lib/python3.12/site-packages/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.so: undefined symbol: _ZN10tensorflow11CSRMatMulOpIN5Eigen16ThreadPoolDeviceEfEC2EPNS_20OpKernelConstructionE`

I built inside docker image with the following command

`CUSTOM_BAZEL_FLAGS=--define=tflite_pip_with_flex=true tensorflow/lite/tools/pip_package/build_pip_package_with_bazel.sh native`

### Standalone code to reproduce the issue

```shell
import tflite_runtime.interpreter as tflite

filepath = os.path.join(os.path.dirname(__file__), f"models/model.tflite")
interpreter = tflite.Interpreter(model_path=filepath)
```

### Relevant log output

```shell
2024-10-05 11:50:35 [ERROR] Runtime.ImportModuleError: Unable to import module 'entry': /var/lang/lib/python3.12/site-packages/tflite_runtime/_pywrap_tensorflow_interpreter_wrapper.so: undefined symbol: _ZN10tensorflow11CSRMatMulOpIN5Eigen16ThreadPoolDeviceEfEC2EPNS_20OpKernelConstructionE
Traceback (most recent call last):
```

**Comment by Venkat6871** [comment]
Hi **@dev2xl** ,
Thank you for raising this issue. It seems there is a version mismatch, which is causing compatibility issues. I am providing the [documentation](https://www.tensorflow.org/install/source#gpu) for your reference. Please go through it and recheck all the compatibility versions.
Thank you!
