### ISSUE TITLE
Had issues running ./configure and bazel build commands

### ISSUE THREAD

**Issue by ushnish** [tensorflow/tensorflow#771]
I did not get any error when I ran ./configure but when i ran 

bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer

I get following error 

Sending SIGTERM to previous Bazel server (pid=2919)... done.
........
INFO: Found 1 target...
INFO: From Compiling external/re2/re2/compile.cc:
src/main/tools/namespace-sandbox.c:633: execvp(argv[0], argv): No such file or directory
ERROR: /home/ushnish/.cache/bazel/_bazel_ushnish/f442d11296e91085e26406d3023541ae/external/re2/BUILD:9:1: C++ compilation of rule '@re2//:re2' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 34 argument(s) skipped).
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 9.317s, Critical Path: 1.97s

I was actually able to solve this problem and successfully run TF with GPUs by following exactly the instructions on this page, which did not mention ./configure or the bazel build command

https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/jRkkvsB1iWA

Please reflect these instructions or some modified version of the instructions on the Getting Started page of Tensorflow as this particular step caused a lot of grief :)

**Comment by vrv** [comment]
https://www.tensorflow.org/versions/master/get_started/os_setup.html#optional-install-cuda-gpus-on-linux

Most of the information is there, including ./configure and bazel, if building from sources.

In your case you probably need to pass --spawn_strategy=standalone  to the bazel command line flag -- I guess we should add that to our tutorials but that seems like a temporary bazel bug that I was hoping would get resolved soon...

**Comment by vrv** [comment]
@lberki: do you think we should just add --spawn_strategy=standalone to our build instructions? Is that likely to be unnecessary in the future?

**Comment by LiberiFatali** [comment]
Adding  --spawn_strategy=standalone to bazel build command works for me. I think you should add " --spawn_strategy=standalone" to the install instructions.
