### ISSUE TITLE
Attempt to "import tensorflow as tf" on MacOS 10.10.5, Python 2.7.10, numpy 1.12.0

### ISSUE THREAD

**Issue by Gemesys** [tensorflow/tensorflow#7713]
- Installed tensorflow using pip on MacOS Yosemite 10.10.5, running Python 2.7.10, with current numpy 1.12.0.  Python runs ok, but attempt to "import tensorflow as tf", as per the documentation for TensorFlow install on Mac OS, generates exactly the same error sequence as posted already on github by another user.  The other users posting was closed without comment.  The specific error message is:
      AttributeError: type object 'NewBase' has no attribute 'is_abstract'
The url of the other user, which documented the traceback (which is essentially same as I am getting) is:
     https://github.com/tensorflow/tensorflow/issues/5707

If I can resolve or workaround this, I will post the fix here.

**Comment by Gemesys** [comment]
Ok, got the answer.  The location of the installed python packages is different on the MacOS than on Linux, but the info provided for Linux users on other posts, solves the problem.  If running TensorFlow, not only is the "numpy" version stuff critical (ie. looks like you need the multi-array features, which aren't in lower versions?), but package "six" is needed, and has to be above version 1.10.  Even though I explicitly installed "six" version 1.10, when I would run Python, I was getting "six" version 1.4.1.  There was a default Python 2.6 and 2.7 installed on my Yosemite MacOS, which puts the numpy and six packages in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python.  But when pip and easy_install are used to install new packages, they must get put somewhere else.  As a kludge to get TensorFlow working, I just renamed the numpy and six stuff in the  ..../Frameworks directory (the one indicated above) to numpy_old and six_old.  But that didn't quite work, since the "six" program had a .pyc as well as a .py file, which I have learned is compiled bytecode.  You have to rename six.pyc to something different also.  Then, Python and the TensorFlow stuff will load ok.  You can check the versions of the python modules with:  
      import modulename 
      print modulename.__version__
I would use pip and/or easy_install to get the latest modules, but my Python 2.7 was still grabbing the old versions from the ..../Frameworks/...  directory.   Renaming the prgms there allowed the newer versions to be loaded via the "import tensorflow as tf" command.
I have just run the 'Hello TensorFlow!' test program from the tutorial below, and confirmed it worked. (URL is below)
   https://www.tensorflow.org/install/install_mac#TF_BINARY_URL
If there is a cleaner workaround or fix for the MacOS, which I have missed, I will post it here later.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
