### ISSUE TITLE
[Distributed Training] Model parallelism support

### ISSUE THREAD

**Issue by ogail** [tensorflow/tensorflow#7714]
Hi,
Looking in the [TF distributed training tutorial](https://www.tensorflow.org/versions/r0.10/how_tos/distributed/) it provides distributed training via data parallelism example only. Does TensorFlow currently support model parallelism? If yes where are docs/examples for that?

Thanks,
Ogail

**Comment by yaroslavvb** [comment]
Here's a simple example of model parallelism -- http://stackoverflow.com/questions/42069147/implementation-of-model-parallelism-in-tensorflow .  You may get more examples on stackoverflow, closing this as we are trying to keep this list for bugs in TensorFlow itself
