### ISSUE TITLE
Segmentation fault with TensorFlow 1.0

### ISSUE THREAD

**Issue by llhe** [tensorflow/tensorflow#7717]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
* No

### Environment info
Operating System:
* Ubuntu 14.04/3.13.0-100-generic
* CentOS 7/3.10.0-123.el7.x86_64

Python Version:
* 2.7.5
* 3.5

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
 * Both CPU/GPU version crash, not related to CUDA

If installed from binary pip package, provide:

1. A link to the pip package you installed:
  * https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0-cp27-none-linux_x86_64.whl
  * https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.0-cp27-none-linux_x86_64.whl
  * https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0-cp35-cp35m-linux_x86_64.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
  * 1.0.0

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
I can make repro with ubuntu 14.04 + python 2.7, 3.5 and centos 7 + python 2.7, but not with ubuntu 16.04 + python 2.7:
https://gist.github.com/llhe/6d95d2e31ad3c5a886dc8c3bd6ace95b

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
Typical outputs:
```
Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "coredump.py", line 18, in <module>
    train()
  File "coredump.py", line 15, in train
    tf.image_summary('input', x, 10)
AttributeError: 'module' object has no attribute 'image_summary'
Segmentation fault (core dumped)
```
Stack trace:
```
(gdb) bt
#0  visit_decref (op=<unknown at remote 0x-1>, data=0x0) at /usr/src/debug/Python-2.7.5/Modules/gcmodule.c:429
#1  0x00007f610674d8de in dict_traverse (op=
    {0x0: <unknown at remote 0x-1>, '__ne__': <wrapper_descriptor at remote 0x1f7d730>, '__ror__': <wrapper_descriptor at remote 0x1f7da00>, '__nonzero__': <wrapper_descriptor at remote 0x1f7d820>, '__new__': <built-in method __new__ of type object at remote 0x7f60fde34f60>, '__rand__': <wrapper_descriptor at remote 0x1f7d8c0>, '__doc__': None, '__xor__': <wrapper_descriptor at remote 0x1f7d910>, '__and__': <wrapper_descriptor at remote 0x1f7d870>, '__le__': <wrapper_descriptor at remote 0x1f7d690>, '__or__': <wrapper_descriptor at remote 0x1f7d9b0>, '__gt__': <wrapper_descriptor at remote 0x1f7d780>, '__hash__': <wrapper_descriptor at remote 0x1f7d5f0>, '__index__': <wrapper_descriptor at remote 0x1f7da50>, '__lt__': <wrapper_descriptor at remote 0x1f7d640>, '__eq__': <wrapper_descriptor at remote 0x1f7d6e0>, '__rxor__': <wrapper_descriptor at remote 0x1f7d960>, '__ge__': <wrapper_descriptor at remote 0x1f7d7d0>}, visit=0x7f61067db1f0 <visit_decref>, arg=0x0)
    at /usr/src/debug/Python-2.7.5/Objects/dictobject.c:2123
#2  0x00007f61067db5b7 in subtract_refs (containers=<optimized out>) at /usr/src/debug/Python-2.7.5/Modules/gcmodule.c:456
#3  collect (generation=generation@entry=2) at /usr/src/debug/Python-2.7.5/Modules/gcmodule.c:999
#4  0x00007f61067dc078 in PyGC_Collect () at /usr/src/debug/Python-2.7.5/Modules/gcmodule.c:1514
#5  0x00007f61067c9339 in Py_Finalize () at /usr/src/debug/Python-2.7.5/Python/pythonrun.c:444
#6  0x00007f61067da545 in Py_Main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/Python-2.7.5/Modules/main.c:665
#7  0x00007f6105a07af5 in __libc_start_main () from /usr/lib64/libc.so.6
#8  0x0000000000400721 in _start ()
```

**Comment by cancan101** [comment]
Dupe of: https://github.com/tensorflow/tensorflow/issues/6968 ?

**Comment by llhe** [comment]
Thanks @cancan101 , the issue can be resolved with:
```
pip install --no-binary=:all: numpy
```
