### ISSUE TITLE
Bazel installer not run on recent Bazel version, kindly provide widly accepted CMake installer

### ISSUE THREAD

**Issue by Reyadeyat** [tensorflow/tensorflow#77176]
### Issue type

Feature Request

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.17.0

### Custom code

No

### OS platform and distribution

Linux linux 6.11.2-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 04 Oct 2024 21:51:11 +0000 x86_64 GNU/Linux

### Bazel version

bazel 7.3.2

### GCC/compiler version

gcc (GCC) 14.2.1 20240910

### CUDA/cuDNN version

CUDA Version: 12.6 

### GPU model and memory

NVIDIA GeForce RTX 3050 - 583MiB /   8192MiB

### Current behavior?

bazel is configured to version 6.5 on tensorflow git files that is not cabable to run because current version is 7.3.2
please provide CMake installer since this is a C based lib.

### Standalone code to reproduce the issue

```shell
$bazel build --config=/linux/tensorflow/runtime //tensorflow/tools/lib_package:libtensorflow
ERROR: The project you're trying to build requires Bazel 6.5.0 (specified in /linux/tensorflow/.bazelversion), but it wasn't found in /usr/bin.

Bazel binaries for all official releases can be downloaded from here:
  https://github.com/bazelbuild/bazel/releases

Please put the downloaded Bazel binary into this location:
  /usr/bin/bazel-6.5.0-linux-x86_64
```

**Comment by tilakrayal** [comment]
@Reyadeyat,
As per the official documentation, the latest tensorflow v2.17 supports the Bazel 6.5.0. Every TensorFlow release is compatible with a certain version, for more information please take a look at the tested build configurations
https://www.tensorflow.org/install/source#gpu

Thank you!
