### ISSUE TITLE
Can't install current MASTER from source

### ISSUE THREAD

**Issue by untom** [tensorflow/tensorflow#772]
Hi!

I was trying to install a fresh install of the tensorflow master from source, but always run into an error:

    $ bazel build -c opt --config=cuda  --verbose_failures --spawn_strategy=standalone //tensorflow/tools/pip_package:build_pip_package

Eventually fails with:

    ERROR: /system/user/bioinf01/tom/sources/tensorflow/tensorflow/python/BUILD:71:1: C++ compilation of rule '//tensorflow/python:py_func_lib' failed: crosstool_wrapper_driver_is_not_
    gcc failed: error executing command 
      (cd /system/user/unterthi/.cache/bazel/_bazel_unterthi/b4214462455bc5801962f5dfb9d41d3b/tensorflow && \
      exec env - \
        INTERCEPT_LOCALLY_EXECUTABLE=1 \
        PATH=/system/apps/biosoft/bazel-0.1.1/bazel-bin/src:/system/apps/biosoft/jdk1.8.0_40/bin:/usr/local/cuda/bin:/system/apps/biosoft/R-3.2.0/bin:/system/apps/biosoft/caffe_py351/d
    istribute/bin:/system/apps/biosoft/lmdb-0.9.17/bin:/system/apps/biosoft/protobuf-3.0.0-alpha-3.1_py351/bin:/system/apps/biosoft/boost_1_59_0_py351/bin:/system/apps/biosoft/python-3
    51/bin:/usr/local/cuda/bin:/system/apps/biosoft/R-3.2.0/bin:/system/apps/biosoft/caffe_py351/distribute/bin:/system/apps/biosoft/lmdb-0.9.17/bin:/system/apps/biosoft/protobuf-3.0.0
    -alpha-3.1_py351/bin:/system/apps/biosoft/boost_1_59_0_py351/bin:/system/apps/biosoft/python-351/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/system
    /user/unterthi/bin:/system/user/unterthi/bin \
      third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-fre
    e-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -iquote . -iquote bazel-out/local_linux-py3-opt/genfiles -isystem google/
    protobuf/src -isystem bazel-out/local_linux-py3-opt/genfiles/google/protobuf/src -isystem tools/cpp/gcc3 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-py3-o
    pt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-py3-opt/genfiles/external/png_archive/libpng-1.2.53 -isystem ex
    ternal/re2 -isystem bazel-out/local_linux-py3-opt/genfiles/external/re2 -isystem third_party/eigen3 -isystem bazel-out/local_linux-py3-opt/genfiles/third_party/eigen3 -isystem exte
    rnal/eigen_archive/eigen-eigen-5651786d5e59 -isystem bazel-out/local_linux-py3-opt/genfiles/external/eigen_archive/eigen-eigen-5651786d5e59 -isystem third_party/py/numpy/numpy_incl
    ude -isystem bazel-out/local_linux-py3-opt/genfiles/third_party/py/numpy/numpy_include -isystem util/python/python_include -isystem bazel-out/local_linux-py3-opt/genfiles/util/pyth
    on/python_include -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_li
    nux-py3-opt/bin/tensorflow/python/_objs/py_func_lib/tensorflow/python/lib/core/py_func.pic.o' -MD -MF bazel-out/local_linux-py3-opt/bin/tensorflow/python/_objs/py_func_lib/tensorfl
    ow/python/lib/core/py_func.pic.d -fPIC -c tensorflow/python/lib/core/py_func.cc -o bazel-out/local_linux-py3-opt/bin/tensorflow/python/_objs/py_func_lib/tensorflow/python/lib/core/
    py_func.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
      (cd /system/user/unterthi/.cache/bazel/_bazel_unterthi/b4214462455bc5801962f5dfb9d41d3b/tensorflow && \
      exec env - \
        INTERCEPT_LOCALLY_EXECUTABLE=1 \
        PATH=/system/apps/biosoft/bazel-0.1.1/bazel-bin/src:/system/apps/biosoft/jdk1.8.0_40/bin:/usr/local/cuda/bin:/system/apps/biosoft/R-3.2.0/bin:/system/apps/biosoft/caffe_py351/d
    istribute/bin:/system/apps/biosoft/lmdb-0.9.17/bin:/system/apps/biosoft/protobuf-3.0.0-alpha-3.1_py351/bin:/system/apps/biosoft/boost_1_59_0_py351/bin:/system/apps/biosoft/python-3
    51/bin:/usr/local/cuda/bin:/system/apps/biosoft/R-3.2.0/bin:/system/apps/biosoft/caffe_py351/distribute/bin:/system/apps/biosoft/lmdb-0.9.17/bin:/system/apps/biosoft/protobuf-3.0.0
    -alpha-3.1_py351/bin:/system/apps/biosoft/boost_1_59_0_py351/bin:/system/apps/biosoft/python-351/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/system
    /user/unterthi/bin:/system/user/unterthi/bin \
      third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-fre
    e-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -iquote . -iquote bazel-out/local_linux-py3-opt/genfiles -isystem google/
    protobuf/src -isystem bazel-out/local_linux-py3-opt/genfiles/google/protobuf/src -isystem tools/cpp/gcc3 -isystem external/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-py3-o
    pt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-py3-opt/genfiles/external/png_archive/libpng-1.2.53 -isystem ex
    ternal/re2 -isystem bazel-out/local_linux-py3-opt/genfiles/external/re2 -isystem third_party/eigen3 -isystem bazel-out/local_linux-py3-opt/genfiles/third_party/eigen3 -isystem exte
    rnal/eigen_archive/eigen-eigen-5651786d5e59 -isystem bazel-out/local_linux-py3-opt/genfiles/external/eigen_archive/eigen-eigen-5651786d5e59 -isystem third_party/py/numpy/numpy_incl
    ude -isystem bazel-out/local_linux-py3-opt/genfiles/third_party/py/numpy/numpy_include -isystem util/python/python_include -isystem bazel-out/local_linux-py3-opt/genfiles/util/pyth
    on/python_include -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_li
    nux-py3-opt/bin/tensorflow/python/_objs/py_func_lib/tensorflow/python/lib/core/py_func.pic.o' -MD -MF bazel-out/local_linux-py3-opt/bin/tensorflow/python/_objs/py_func_lib/tensorfl
    ow/python/lib/core/py_func.pic.d -fPIC -c tensorflow/python/lib/core/py_func.cc -o bazel-out/local_linux-py3-opt/bin/tensorflow/python/_objs/py_func_lib/tensorflow/python/lib/core/
    py_func.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
    Target //tensorflow/tools/pip_package:build_pip_package failed to build
    INFO: Elapsed time: 118.584s, Critical Path: 32.92s

Running that last command myself to see the GCC error message gives:

    $ third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstac
    k-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -iquote . -iqu
    ote bazel-out/local_linux-py3-opt/genfiles -isystem google/protobuf/src -isystem bazel-out/local_linux-py3-opt/genfiles/google/protobuf/src -isystem tools/cpp/gcc3 -isystem externa
    l/jpeg_archive/jpeg-9a -isystem bazel-out/local_linux-py3-opt/genfiles/external/jpeg_archive/jpeg-9a -isystem external/png_archive/libpng-1.2.53 -isystem bazel-out/local_linux-py3-
    opt/genfiles/external/png_archive/libpng-1.2.53 -isystem external/re2 -isystem bazel-out/local_linux-py3-opt/genfiles/external/re2 -isystem third_party/eigen3 -isystem bazel-out/lo
    cal_linux-py3-opt/genfiles/third_party/eigen3 -isystem external/eigen_archive/eigen-eigen-5651786d5e59 -isystem bazel-out/local_linux-py3-opt/genfiles/external/eigen_archive/eigen-
    eigen-5651786d5e59 -isystem third_party/py/numpy/numpy_include -isystem bazel-out/local_linux-py3-opt/genfiles/third_party/py/numpy/numpy_include -isystem util/python/python_includ
    e -isystem bazel-out/local_linux-py3-opt/genfiles/util/python/python_include -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"
    ' '-D__TIME__="redacted"' '-frandom-seed=bazel-out/local_linux-py3-opt/bin/tensorflow/python/_objs/py_func_lib/tensorflow/python/lib/core/py_func.pic.o' -MD -MF bazel-out/local_lin
    ux-py3-opt/bin/tensorflow/python/_objs/py_func_lib/tensorflow/python/lib/core/py_func.pic.d -fPIC -c tensorflow/python/lib/core/py_func.cc -o bazel-out/local_linux-py3-opt/bin/tens
    orflow/python/_objs/py_func_lib/tensorflow/python/lib/core/py_func.pic.o
    In file included from ./tensorflow/core/public/tensor.h:19:0,
                     from ./tensorflow/python/lib/core/py_func.h:20,
                     from tensorflow/python/lib/core/py_func.cc:16:
    ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:90: fatal error: external/eigen_archive/eigen-eigen-5651786d5e59/unsupported/Eigen/CXX11/Tensor: No such file or directory
     #include "external/eigen_archive/eigen-eigen-5651786d5e59/unsupported/Eigen/CXX11/Tensor"
                                                                                              ^
    compilation terminated.

**Comment by schmiflo** [comment]
Interesting! I checked out the master (a2c5e74) today and it does compile without cuda. Did you try without cuda?

However, my custom operations that worked in 0.5.0 fail with the same message. Would be very interested to find out why

In file included from ./tensorflow/core/public/tensor.h:19:0,
                 from ./tensorflow/core/framework/device_base.h:28,
                 from ./tensorflow/core/framework/op_kernel.h:24,
                 from tensorflow/core/user_ops/my_first_kernel.cc:3:
./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:90: fatal error: external/eigen_archive/eigen-eigen-5651786d5e59/unsupported/Eigen/CXX11/Tensor: No such file or directory
 #include "external/eigen_archive/eigen-eigen-5651786d5e59/unsupported/Eigen/CXX11/Tensor"

**Comment by vrv** [comment]
1) did you run ./configure ?

2) Can you try a newer version of bazel?  I think 0.1.1 is too old now.

**Comment by untom** [comment]
Thanks for the advise. Yes I did run `./configure`, but I used bazel 0.1.1.

 I tried again with both bazel 0.1.2 and bazel 0.1.3 and today's master. Howver I always get the following error:


    ERROR: /system/user/bioinf01/tom/apps/tensorflow/tensorflow/core/BUILD:148:1: undeclared inclusion(s) in rule '//tensorflow/core:gpu_runtime':
    this rule is missing dependency declarations for the following files included by 'tensorflow/core/common_runtime/gpu/gpu_device_factory.cc':
      '/usr/local/cuda-7.5/include/cuda.h'
      '/usr/local/cuda-7.5/include/cufft.h'
      '/usr/local/cuda-7.5/include/cuComplex.h'
      '/usr/local/cuda-7.5/include/vector_types.h'
      '/usr/local/cuda-7.5/include/builtin_types.h'
      '/usr/local/cuda-7.5/include/device_types.h'
      '/usr/local/cuda-7.5/include/host_defines.h'
      '/usr/local/cuda-7.5/include/driver_types.h'
      '/usr/local/cuda-7.5/include/surface_types.h'
      '/usr/local/cuda-7.5/include/texture_types.h'
      '/usr/local/cuda-7.5/include/cuda_runtime.h'
      '/usr/local/cuda-7.5/include/host_config.h'
      '/usr/local/cuda-7.5/include/channel_descriptor.h'
      '/usr/local/cuda-7.5/include/cuda_runtime_api.h'
      '/usr/local/cuda-7.5/include/cuda_device_runtime_api.h'
      '/usr/local/cuda-7.5/include/driver_functions.h'
      '/usr/local/cuda-7.5/include/vector_functions.h'
      '/usr/local/cuda-7.5/include/vector_functions.hpp'.
    ____[858 / 1,221] Still waiting for 1 job to complete:
          Running (spawn):
            Compiling tensorflow/core/kernels/cwise_op_gpu_square.cu.cc, 10 s
    ____Building complete.
    Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by untom** [comment]
Weirdly, running the same command again for a 2nd time, I get a slightly different error:


    $ bazel build --config=cuda --verbose_failures --spawn_strategy=standalone -c opt //tensorflow/tools/pip_package:build_pip_package 
    WARNING: Output base '/system/user/unterthi/.cache/bazel/_bazel_unterthi/ca09685feaa24bba7598707e311fa383' is on NFS. This may lead to surprising failures and undetermined behavior.
    WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
    INFO: Found 1 target...
    ERROR: /system/user/bioinf01/tom/apps/tensorflow/tensorflow/stream_executor/BUILD:5:1: undeclared inclusion(s) in rule '//tensorflow/stream_executor:stream_executor':
    this rule is missing dependency declarations for the following files included by 'tensorflow/stream_executor/cuda/cuda_diagnostics.cc':
      '/system/user/bioinf01/tom/apps/tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.h'.

    Target //tensorflow/tools/pip_package:build_pip_package failed to build
    INFO: Elapsed time: 15.271s, Critical Path: 13.78s

**Comment by skearnes** [comment]
@schmiflo adding hdrs = glob(["user_ops/**/*.h"]) to the //tensorflow/core:user_ops_op_lib BUILD rule might fix your custom ops problem.

@untom I got a similar "undeclared inclusion(s)" error with bazel 0.1.3, but downgrading to a precompiled 0.1.1 seemed to fix the problem (note, however, that I am not trying to build the pip package).

**Comment by JianbangZ** [comment]
@untom +1, I got the same problem

**Comment by frankyjuang** [comment]
@untom, @JianbangZ
```ERROR: /system/user/bioinf01/tom/sources/tensorflow/tensorflow/python/BUILD:71:1: C++ compilation of rule '//tensorflow/python:py_func_lib' failed: crosstool_wrapper_driver_is_not_
gcc failed: error executing command```
has been fixed in #733. You can try the latest master. And
```undeclared inclusion(s) in rule '//tensorflow/core:gpu_runtime': this rule is missing dependency declarations``` 
can be fixed by adding
`unfiltered_cxx_flag: "-fno-canonical-system-headers` at https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/CROSSTOOL#L110
for more info, you can checkout #469

**Comment by vrv** [comment]
Does somebody want to send us a PR for that?

**Comment by frankyjuang** [comment]
@vrv I don't think so. I'll do it.

**Comment by vrv** [comment]
Thanks @frankyjuang !  We just merged it -- let us know if the problems are still present by commenting and we'll reopen.

**Comment by frankyjuang** [comment]
You're welcome.

**Comment by untom** [comment]
Thanks for looking into this. I now run into a different error. Not sure if the other error masked this one or if this is a completely different issue (let me know if I should file this separately):



    $ bazel build --config=cuda --verbose_failures --spawn_strategy=standalone -c opt //tensorflow/tools/pip_package:build_pip_package 
    WARNING: Output base '/system/user/unterthi/.cache/bazel/_bazel_unterthi/dd424fe506e42444112be8dec7db846b' is on NFS. This may lead to surprising failures and undetermined behavior.
    ........
    WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
    INFO: Found 1 target...
    ERROR: /data01/bioinf/tom/apps/tensorflow/tensorflow/python/BUILD:247:1: Converting to Python 3: tensorflow/python/ops/functional_ops.py failed: 2to3 failed: error executing command 
      (cd /system/user/unterthi/.cache/bazel/_bazel_unterthi/dd424fe506e42444112be8dec7db846b/tensorflow && \
      exec env - \
      bazel-out/host/bin/tools/python/2to3 --no-diffs --nobackups --write --output-dir bazel-out/local_linux-py3-opt/genfiles/python3/tensorflow/python/ops --write-unchanged-files tensorflow/python/ops/functional_ops.py): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1: 2to3 failed: error executing command 
      (cd /system/user/unterthi/.cache/bazel/_bazel_unterthi/dd424fe506e42444112be8dec7db846b/tensorflow && \
      exec env - \
      bazel-out/host/bin/tools/python/2to3 --no-diffs --nobackups --write --output-dir bazel-out/local_linux-py3-opt/genfiles/python3/tensorflow/python/ops --write-unchanged-files tensorflow/python/ops/functional_ops.py): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
    Target //tensorflow/tools/pip_package:build_pip_package failed to build
    INFO: Elapsed time: 87.057s, Critical Path: 11.50s



For what it's worth, I'm trying to use Python 3.5.1 (custom build, not the system installation). What I find really puzzling is the file bazel is trying to execute (`2to3`):

    $ cat /system/user/unterthi/.cache/bazel/_bazel_unterthi/dd424fe506e42444112be8dec7db846b/tensorflow/bazel-out/host/bin/tools/python/2to3
    #!/bin/bash
    
    exit 1



I changed this file to `exit 0` instead, but this again leaves me with an error:

    $ bazel build --config=cuda --verbose_failures --spawn_strategy=standalone -c opt //tensorflow/tools/pip_package:build_pip_package 
    WARNING: Output base '/system/user/unterthi/.cache/bazel/_bazel_unterthi/dd424fe506e42444112be8dec7db846b' is on NFS. This may lead to surprising failures and undetermined behavior.
    WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
    INFO: Found 1 target...
    ERROR: /data01/bioinf/tom/apps/tensorflow/third_party/gpus/cuda/BUILD:122:1: declared output 'third_party/gpus/cuda/lib64/libcufft.so.7.5' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely).
    ERROR: /data01/bioinf/tom/apps/tensorflow/third_party/gpus/cuda/BUILD:122:1: not all outputs were created.
    ERROR: /data01/bioinf/tom/apps/tensorflow/tensorflow/python/BUILD:247:1: output 'python3/tensorflow/python/ops/functional_ops.py' was not created.
    ERROR: /data01/bioinf/tom/apps/tensorflow/tensorflow/python/BUILD:247:1: not all outputs were created.
    Target //tensorflow/tools/pip_package:build_pip_package failed to build
    INFO: Elapsed time: 3.169s, Critical Path: 1.73s


(In case you're wondering: I changed all references of CUDA libraries to 7.5, since installing 7.0 on this system is not an option. `libcufft.so.7.5` is in a path that is included in LD_LIBRARY_PATH)

**Comment by martinwicke** [comment]
Bazel tried to run 2to3 if it sees a python file that doesn't have the srcs_version = "PY2AND3" annotation. As it turns out that's the case for functional_ops.py (and a couple of other targets in python/BUILD.

Can you add the annotation to those targets and see if that works for you?

**Comment by untom** [comment]
I actually noticed this was likely a duplicate of #791, the workaround described there solved the problem for me, as well!

**Comment by zer0n** [comment]
+1 
I run into the same problem when running
```
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```

bazel 0.1.1 and 0.1.3 give this error immediately
```
java.lang.NoClassDefFoundError: com/jcraft/jsch/JSchException
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:109)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:136)
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:262)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:161)
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:136)
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:122)
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1138)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:130)
        at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:193)
        at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:133)
        at com.google.devtools.build.lib.bazel.repository.GitCloneFunction.compute(GitCloneFunction.java:127)
        at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:933)
        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:499)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

bazel 0.1.2 fails to build protobuf. 
```
INFO: Found 1 target...
INFO: From Compiling google/protobuf/src/google/protobuf/extension_set.cc [for host]:
src/main/tools/namespace-sandbox.c:633: execvp(argv[0], argv): No such file or directory
ERROR: /home/zer0n/src/tensorflow/google/protobuf/BUILD:29:1: C++ compilation of rule '//google/protobuf:protobuf_lite' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /home/zer0n/.cache/bazel/_bazel_zer0n/752539f897d4732a3a650ab733666abd/tensorflow && \
  exec env - \
    PATH=/home/zer0n/src/torch/install/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++11' -iquote . -iquote bazel-out/host/genfiles -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem google/protobuf/src -isystem bazel-out/host/genfiles/google/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare '-Wno-error=unused-function' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers '-frandom-seed=bazel-out/host/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/extension_set.o' -MD -MF bazel-out/host/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/extension_set.d -c google/protobuf/src/google/protobuf/extension_set.cc -o bazel-out/host/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/extension_set.o): crosstool_wrapper_driver_is_not_gcc failed: error executing command
  (cd /home/zer0n/.cache/bazel/_bazel_zer0n/752539f897d4732a3a650ab733666abd/tensorflow && \
  exec env - \
    PATH=/home/zer0n/src/torch/install/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games \
  third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++11' -iquote . -iquote bazel-out/host/genfiles -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem google/protobuf/src -isystem bazel-out/host/genfiles/google/protobuf/src -isystem external/bazel_tools/tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare '-Wno-error=unused-function' -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers '-frandom-seed=bazel-out/host/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/extension_set.o' -MD -MF bazel-out/host/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/extension_set.d -c google/protobuf/src/google/protobuf/extension_set.cc -o bazel-out/host/bin/google/protobuf/_objs/protobuf_lite/google/protobuf/src/google/protobuf/extension_set.o).
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1.338s, Critical Path: 0.33s.
```
