### ISSUE TITLE
Feature: Hide Metrics for Which Data Exists for Zero Runs

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#7720]
The list of metrics for for plotting on the scalars tab is cluttered with a number of metrics that don't exist for the selected runs. Why not side these rather than taking up real estate:
![image](https://cloud.githubusercontent.com/assets/51059/23149169/2c980ac0-f7b8-11e6-8493-b4085e089be1.png)

**Comment by cancan101** [comment]
This is[ a related SO post](http://stackoverflow.com/questions/42357850/tensorboard-scalars-count): but the count on the right side shows 1 even if there is no data.

**Comment by wchargin** [comment]
Agreed; I was just thinking about doing this yesterday.

The count at right is correct; it indicates how many charts there are. There is indeed one chart…it's just useless. :-)

I've migrated this to our new repository at https://github.com/tensorflow/tensorboard/issues/55. Feel free to continue discussing there.
