### ISSUE TITLE
CUDA and cUDNN version compatability for tensorflow 2.17.0?

### ISSUE THREAD

**Issue by prajsri99** [tensorflow/tensorflow#77216]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.17.0

### Custom code

Yes

### OS platform and distribution

Windows 10

### Python version

3.9

### Current behavior?

I wanted to check what is the cuda and cUDNN version compatibility required for tensorflow 2.17.0?

### Standalone code to reproduce the issue

```shell
I wanted to check what is the cuda and cUDNN version compatibility required for tensorflow 2.17.0?
```

**Comment by Venkat6871** [comment]
Hi **@prajsri99** ,
Thank you for raising your concern here. GPU support on native-Windows is only available for 2.10 or earlier versions, starting in TF 2.11, CUDA build is not supported for Windows. For using TensorFlow GPU on Windows, you will need to build/install TensorFlow in WSL2 or use tensorflow-cpu with TensorFlow-DirectML-Plugin. This is clearly mentioned in the [documentation](https://www.tensorflow.org/install/source_windows), so please review it for further details.
Thank you!
