### ISSUE TITLE
when will tf.contrib.distributions move into tf core? Is this planned?

### ISSUE THREAD

**Issue by thjashin** [tensorflow/tensorflow#7727]
Hi,

I'm working with distributions a lot in my own library built upon tensorflow. However, I found the api provided in tf.contrib.distributions are subject to change very often, which makes it quite difficult to keep up and maintain a stable codebase.
So I'd like to ask whether tf.contrib.distributions is going to the tensorflow core library and how is this planned. Will you recommend to keep using it or just build my own distributions?

Best,
Jiaxin

**Comment by ebrevdo** [comment]
We're moving it in the next 2 weeks, hopefully.  There may be one final breaking change to the API; but it should happen before TF 1.2 is released.  I imagine by TF 1.2 it'll be in core.

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Comment by ebrevdo** [comment]
The move will happen by tf 1.3.
