### ISSUE TITLE
compile_ios_tensorflow.sh  failed with following error

### ISSUE THREAD

**Issue by tianwalker2012** [tensorflow/tensorflow#7728]
/Users/xietian/Documents/tensorflow/tensorflow/contrib/makefile/gen/lib/ios_ARMV7/libtensorflow-core-armv7.a -arch armv7 -fembed-bitcode -miphoneos-version-min=8.2 -framework Accelerate -Xlinker -S -Xlinker -x -Xlinker -dead_strip -all_load -L/Users/xietian/Documents/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib -lz -lstdc++ -lprotobuf -lz -lm
Undefined symbols for architecture armv7:
  "google::protobuf::internal::WireFormatLite::WriteDoubleArray(double const*, int, google::protobuf::io::CodedOutputStream*)", referenced from:
      tensorflow::TensorProto::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in libtensorflow-core-armv7.a(tensor.pb.o)
      tensorflow::HistogramProto::SerializeWithCachedSizes(google::protobuf::io::CodedOutputStream*) const in libtensorflow-core-armv7.a(summary.pb.o)
  "google::protobuf::Any::MergeFrom(google::protobuf::Any const&)", referenced from:
      tensorflow::MetaGraphDef_MetaInfoDef::MergeFrom(tensorflow::MetaGraphDef_MetaInfoDef const&) in libtensorflow-core-armv7.a(meta_graph.pb.o)
      google::protobuf::internal::GenericTypeHandler<google::protobuf::Any>::Merge(google::protobuf::Any const&, google::protobuf::Any*) in libtensorflow-core-armv7.a(meta_graph.pb.o)

**Comment by poxvoculi** [comment]
Could you please provide more contextual data, as requested by the New Issue template?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
