### ISSUE TITLE
How to delete existed tensorflow variable?

### ISSUE THREAD

**Issue by artzers** [tensorflow/tensorflow#7729]
Hello, I am using windows GPU tensorflow 1.0.
 I use ipython notebook to build training model because I can reuse script easily. Sometimes I just want to modify one tensorflow variable, such as W1(shape=[3,3],name="W1") from a existed model. So I just modify the variable and run the model building script again. However, tensorflow add W1(shape=[5,5],name="W1_1")  variable to replace old variable W1. It makes some bugs when I continue the next work with W1. Could you tell me how to delete old variable "W1" and add new different variable named "W1"?

**Comment by Carmezim** [comment]
This questions is suited for StackOverflow which is monitored as well under TensorFlow tag.

**Comment by yaroslavvb** [comment]
as @Carmezim mentioned, these questions are better suited to stackoverflow, to make sure answers get better exposure for other people looking for the same, and to keep this list focused on things that need action of core developers
