### ISSUE TITLE
Provide a way to clear variable and name scope

### ISSUE THREAD

**Issue by eamartin** [tensorflow/tensorflow#7731]
This is a follow-up of https://github.com/tensorflow/tensorflow/issues/6189

It would be nice to be able to create a variable or name scope that does not obey all currently open scopes.

As an example:
```python
with tf.variable_scope('foo'):
    with tf.variable_scope('bar'):
        x = tf.constant(1.0, name='x')     # foo/bar/x

with tf.variable_scope('foo'):
    with tf.variable_scope('bar', fresh=True):
        x = tf.constant(1.0, name='x')    # bar/x
```

This would be useful for using scopes with object oriented TensorFlow graphs.

Consider a slightly modified version of the example from #6189 . Assume each method pushes a scope for the instance (with the class name) and for the method.
```python
class Foo(object):
    def __init__(self):
        self.x = tf.get_variable('x', [], initializer=tf.constant(0.0))

    def meth(self, foo):
        z = tf.multiply(foo, 3.14, name='z')
        return self.x.assign(z)

    def boom(self, foo):
        return tf.multiple(2.0, self.meth(foo), name='baz')

f0 = Foo()      # Foo/__init__/x
f1 = Foo()      # Foo_1/__init__/x
f0.meth(1.0)    # Foo/meth/*
f0.boom(2.0)  # Foo/boom/baz, Foo/boom/Foo/meth/z
```

I'd like the variables in ``boom``'s call to ``meth`` to be prefixed with only ``Foo/meth`` rather than ``Foo/boom/Foo/meth``. This requires either releasing the variable scope within boom before calling out (hard) or providing a way for ``meth`` to clear the existing variable scope.

**Comment by poxvoculi** [comment]
@ebrevdo Any opinion as to whether this is desirable feature request?

**Comment by erlebach** [comment]
I am interested in the answer to this same question. Thanks.

**Comment by lipixun** [comment]
+1 Need this feature.

**Comment by arunabhcode** [comment]
+1 Need this as well.

**Comment by ebrevdo** [comment]
You can access and pass around a scope object:

with variable_scope("a") as vs:
  with variable_scope("b"):
    with variable_scope(vs):
      # back in "a"

**Comment by rishabhmalhotra** [comment]
Why is this not already a top priority?

**Comment by AdamZou** [comment]
+1 Need this feature.

**Comment by smr97** [comment]
Yeah, build that ~wall~ feature!

**Comment by MoltenMuffins** [comment]
+1 would like this feature. Using `with variable_scope(""):` resulted in the prefix still being affixed to layer weight names. I went around this in my subclassed layer by assigning `self._name = ''` like so:

```
class SomeConvs(keras.layers.Layer):
    def __init__(self):
        super(SomeConvs, self).__init__()
        self._name = ''
        layer_name = "name_i'm_forced_to_use_because_i'm_loading_weights_via_name"
        self._conv2d = keras.layers.Conv2D(filters=(2, 2),
                                           name=layer_name)

    def call(self, x):
        x = self._conv2d(x)
        return x
```

**Comment by ebrevdo** [comment]
Asking Francois to take a look since the example is Keras specific, and in tf2 name and variable scopes are kinda the same thing now.
