### ISSUE TITLE
How is TensorFlow tested before release?

### ISSUE THREAD

**Issue by HLH13297997663** [tensorflow/tensorflow#77316]
Hello，TensorFlow is a very good deep learning framework. I would like to ask, **how is TensorFlow tested after adding new features? What are the test cases and testing strategies?**
Is there a testing process and testing report?
Looking forward to your response, thank you.

**Comment by Venkat6871** [comment]
Hi **@HLH13297997663** ,
Apologies for the delay. Please refer to this [documentation](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md) for guidance on how to contribute.
Thank you!
