### ISSUE TITLE
API Documentation with Links to Source Code

### ISSUE THREAD

**Issue by jonasrauber** [tensorflow/tensorflow#7735]
I think it would be a really great improvement if the API documentation https://www.tensorflow.org/api_docs/ would contain links to the corresponding source code file on GitHub, similar to python package documentations on readthedocs.org, e.g. https://lasagne.readthedocs.io/en/latest/modules/layers/base.html.

This would also make it much faster to create pull requests that fix errors in the documentation.

**Comment by martinwicke** [comment]
This is actually happening in the new docs. All the way on the bottom, e.g.: https://www.tensorflow.org/api_docs/python/tf/DType

Doesn't work for all things, but close.

**Comment by jonasrauber** [comment]
Oh wow, sorry for that! I guess I was looking for it in the wrong place...

That's really nice, but sometimes it's not clickable, e.g.: https://www.tensorflow.org/api_docs/python/tf/minimum

**Comment by dr4b** [comment]
We're planning to move up the include line to the top of the file soon so it's more visible.

Not sure what to do about the generated ops though.

**Comment by martinwicke** [comment]
We have a plan for the generated ops, which involves rejigging our build to
place generated files into a predictable location. But it's a little bit
away.
