### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'merge_all_summaries'

### ISSUE THREAD

**Issue by linrio** [tensorflow/tensorflow#7737]
### Environment info
Operating System: Win10

Installed version of CUDA and cuDNN: No 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide: yes

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. 1.0.0

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
```
Traceback (most recent call last):
  File "G:/codes/tensorflow2/Autopilot-TensorFlow/train.py", line 22, in <module>
    merged_summary_op = tf.merge_all_summaries()
AttributeError: module 'tensorflow' has no attribute 'tf.merge_all_summaries'

```

**Comment by schmiflo** [comment]
It is now called ```tf.summary.merge_all```

**Comment by airsimonhan** [comment]
Did you solved this problem?

**Comment by sid333rajput** [comment]
AttributeError: module 'tensorflow' has no attribute 'merge_summary'

facing this error
cant find a soln still

**Comment by 19EE64R03** [comment]
For tensorflow 2.0, try using this 
tf.compat.v1.summary.merge_all()
