### ISSUE TITLE
slim doesn't play well with the new tf.layers v 1.0

### ISSUE THREAD

**Issue by jrabary** [tensorflow/tensorflow#7738]
We use tf.contrib.slim to build NN architecture. After upgrade to tensorflow 1.0 the are some trouble when building models with slim. For example `slim.arg_scope` doesn't work with the tf.layers components. And when we keep using slim.* layers, we got a runtime error:

~~~
tensorflow.python.framework.errors_impl.InvalidArgumentError: Session was not created with a graph before Run()!
~~~

If we use all the layers from tf.layers this runtime error goes away.

Any ideas ?

**Comment by inflation** [comment]
`slim` is kind of out of maintenance in my opinion. The better option is to migrate to new `tf.layers` or use another higher level abstraction based on TensorFlow.

**Comment by sguada** [comment]
You can still use all layers and slim.arg_scope with tf.contrib.layers but not with tf.layers.

**Comment by martinwicke** [comment]
What Sergio said.
