### ISSUE TITLE
filters and kernel are mentioned as different terms

### ISSUE THREAD

**Issue by ShivamShinde27** [tensorflow/tensorflow#77386]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.16.1

### Custom code

No

### Current behavior?

on the conv2d document kernels(as argument kernel_size) and filters(as argument filters) are mentioned as two different arguments despite referring to the same parameter in CNN's.Request to change the argument name both to filters or kernels to avoid any misinterpretation. 

### Standalone code to reproduce the issue

```shell
link to the aforementioned document:https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D
```

**Comment by tilakrayal** [comment]
@ShivamShinde27,
Filters represent the number of output channels after convolution has been performed, while Kernel represents the size of a convolution filter being used to perform convolution on the image.
 A filter is a collection of kernels, although we use filter and kernels interchangeably. If you still need the change to happen, please raise the request in the keras-team/keras as this is related to keras. Thank you!
