### ISSUE TITLE
Improve retrained inception v3 in Android demo

### ISSUE THREAD

**Issue by codeloverr** [tensorflow/tensorflow#7742]
I have retrained the Inception-V3 final layer with my own 20 categories. When I am using retrained model in android demo app it takes 6 to 8 seconds to predict.

Running (using `armeabi-v7a`) on 

- LG G4 Stylus -> 6-8 sec
- S6, -> 3-4.5 sec

I have done `optimize_for_inference` it takes 6-9 sec and `quantize_graph` it takes 7-11 sec. Is there any way to improve it?

[Output](https://i.stack.imgur.com/lKryY.png) on LG G4 Stylus.

**Comment by poxvoculi** [comment]
This is a question better suited for StackOverflow, which we also monitor. Please ask it there and tag it with the `tensorflow` tag.

**Comment by codeloverr** [comment]
@poxvoculi I have asked on [Stackoverflow](http://stackoverflow.com/questions/42367281/tensorflow-android-retrained-inception-v3-take-too-much-time) but got no help.

**Comment by AtomicSpider** [comment]
@codeloverr Hi, could you please share the source code of your android app? I'm trying to do the same thing but I'm getting a lot of errors during build. Thanks

**Comment by codeloverr** [comment]
@AtomicSpider  sure, I'll make the repo and share with you.
