### ISSUE TITLE
[feature request] tf.matrix_triangular_solve misses unit_diagonal= argument

### ISSUE THREAD

**Issue by matwey** [tensorflow/tensorflow#7743]
Hello,

It would be useful to allow ```tf.matrix_triangular_solve``` have ```unit_diagonal=``` kw-argument and treat ```matrix``` argument as having unit diagonal.
Sure, the same may be obtained by composition ```tf.matrix_set_diag``` and ```tf.matrix_triangular_solve```. However, additional assignment here seems to be inefficient. Solving triangular matrix involves quite simple formulae where diagonal elements of ```matrix``` are presented explicitly.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
