### ISSUE TITLE
Issue: Error Serving LSTM Model on CPU After GPU Training

### ISSUE THREAD

**Issue by dev2xl** [tensorflow/tensorflow#77442]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.17

### Custom code

No

### Current behavior?

I trained a model using LSTM layers on a GPU for faster processing. However, when attempting to serve the model in a cloud environment with only CPU support, I encountered the following error:

`No OpKernel was registered to support Op 'CudnnRNNV3'.`

I understand that this error is related to GPU-specific operations (e.g., CuDNN) not being available on CPU.

**My Question:**
Is there a way to train a model using GPU and still successfully serve it on a CPU-only environment?

**What I’ve Tried:**
Exporting the model in SavedModel format
Converting the model to TensorFlow Lite (TFLite)

However, both approaches resulted in similar errors related to GPU dependencies.

Saving the model in .keras format after training with GPU, then using it in CPU only environment actually works, but very slow, because the same model trained with CPU and using TFLite format works almost instant. Is a very small model.

Any guidance on how to resolve this would be greatly appreciated!

### Standalone code to reproduce the issue

```shell
Basic model creation with a layer like tf.keras.layers.LSTM(256, return_sequences=True)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File ".../index.py", line 114, in <module>
    main()
  File ".../index.py", line 39, in main
    result = predict(model, metadata, values)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../model.py", line 139, in predict
    prediction = model.serve(padded_sequence) #inference model
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File ".../.venv/lib/python3.11/site-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'CudnnRNNV3' used by {{node StatefulPartitionedCall/sequential_1/lstm_1/CudnnRNNV3}} with these attrs: [rnn_mode="lstm", seed=0, input_mode="linear_input", num_proj=0, dropout=0, seed2=0, is_training=true, direction="unidirectional", time_major=false, T=DT_FLOAT]
```

**Comment by tilakrayal** [comment]
@dev2xl,
Could you please share colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster. Thank  you!
