### ISSUE TITLE
tensorflow sequence to sequence models

### ISSUE THREAD

**Issue by ymakkapa** [tensorflow/tensorflow#7744]
Hello everyone,
I executed the code translate.py from sequence to sequence models tutorial of tensorflow for 20 hours and did not get output.
Can anyone tell me how much time will it take to display the output
System specifications:
I installed Ubuntu 16.04 on VMware with a disk space of 100GB
![seqgoo](https://cloud.githubusercontent.com/assets/20130992/23177248/2078472e-f834-11e6-80ec-c264984d51a7.png)

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
