### ISSUE TITLE
Feature request: Unique tensorboard URLs for different frontend states

### ISSUE THREAD

**Issue by malmaud** [tensorflow/tensorflow#7746]
It would be nice if eg clicking on the "GRAPHS" tab in tensorboard would rewrite the URL to something like "localhost:6006/graphs". And likewise, navigating to "localhost:6006/graphs" would immediately load the GRAPHS tab. In general, encoding the tensorboard state in the URL would be useful.

That way, you could refresh the page and go back to the tab you were on, share your tensorboard state just by copying the URL, programmatically load a specific tensorboard state from visualization routines in your client language, etc.

**Comment by dandelionmane** [comment]
This should be done now, at the highest level (e.g. /graphs, /scalars). Please open an issue on tensorflow/tensorboard if you need more fine-grained state in the url bar.
