### ISSUE TITLE
Making the URLs in the documentation clickable

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [tensorflow/tensorflow#7750]
It would be nice if the URLs in the documentation were clickable.

[Example](https://www.tensorflow.org/versions/r0.10/api_docs/python/nn/conectionist_temporal_classification__ctc_):

![image](https://cloud.githubusercontent.com/assets/15331/23184189/d337d5b0-f84c-11e6-9c7d-821563b30356.png)

**Comment by dr4b** [comment]
We've identified what's causing this and will figure out a fix.

**Comment by teldridge11** [comment]
@dr4b Can you share what the cause of this issue is?  I may throw up a quick PR if it's a relatively straightforward problem.

**Comment by josh11b** [comment]
The Markdown interpreter we are now using on tensorflow.org requires URLs to be enclosed in <...>.  I think we were hoping to come up with some logic that could identify URLs and rewrite them as part of our website publishing process -- see, e.g.,  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docs/parser.py

**Comment by kemaswill** [comment]
Is there anyone who is still working on this, or can we just do a quick fix?

**Comment by MarkDaoust** [comment]
Any quick fix for these is welcome!

We're planning on some updates to the docs' markdown parser that will catch these, but that's farther out.

**Comment by girving** [comment]
Looks like https://github.com/tensorflow/tensorflow/pull/9631 fixed this.
