### ISSUE TITLE
sess.run(tf.global_variables_initializer()) is slow after installing 1.0.0.

### ISSUE THREAD

**Issue by chrisranderson** [tensorflow/tensorflow#7755]
### The issue

`sess.run(tf.global_variables_initializer())` intermittently takes a long time since installing 1.0.0. I believe this also happened on my Python 2 0.12 install, but only after installing 1.0.0 for Python 3. This particular run was in Python 2, and the initializer took 32 seconds - see bottom of this post (and the attached cprofile output) for more detail.

Strangely, it seems like the more I run the same file, the faster it runs.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

None.

### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root   560184 Oct 27 16:26 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Oct 27 16:26 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Oct 27 16:26 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.27
-rwxr-xr-x 1 root root   394472 Oct 27 16:26 /usr/local/cuda/lib64/libcudart.so.8.0.27
-rw-r--r-- 1 root root   737516 Oct 27 16:26 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 60696704 Oct 27 16:31 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 60696704 Oct 27 16:31 /usr/local/cuda/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 60696704 Oct 27 16:31 /usr/local/cuda/lib64/libcudnn.so.5.1.3
-rw-r--r-- 1 root root 59715990 Oct 27 16:31 /usr/local/cuda/lib64/libcudnn_static.a
```

If installed from binary pip package, provide:

1. A link to the pip package you installed: `sudo pip install tensorflow-gpu` on 2/21/17
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. 1.0.0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import time
from collections import deque

import numpy as np
print('Importing tensorflow')
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data

xavier = tf.contrib.layers.xavier_initializer
batch_norm = tf.contrib.layers.batch_norm

tf.set_random_seed(1)

flags = tf.app.flags
FLAGS = flags.FLAGS
flags.DEFINE_string('data_dir', 'data/', 'Directory for storing data')
print('Reading data.')
mnist = input_data.read_data_sets(FLAGS.data_dir, one_hot=True)
initialization_variance = 0.1

print('Creating a session.')
sess = tf.Session()

def fully_connected_layer(inputs, output_size, scope, nonlinearity=True):
  with tf.variable_scope(scope):
    input_size = inputs.get_shape()[1].value

    weights = tf.get_variable('w', 
                              [input_size, output_size],
                              initializer=tf.constant_initializer(0.0))

    bias = tf.get_variable('b', 
                           [output_size],
                           initializer=tf.constant_initializer(0.0))

    multiplied = tf.matmul(inputs, weights)

    return tf.nn.elu(multiplied + bias) if nonlinearity else multiplied + bias

print('Setting up the model.')
input_images = tf.placeholder(tf.float32, [None, 784])
labels = tf.placeholder(tf.float32, [None, 10]) # labels
learning_rate_placeholder = tf.placeholder(tf.float32, name='learning-rate')

layer_a = fully_connected_layer((input_images), 50, 'a')

for i in range(5):
  layer_a = batch_norm(fully_connected_layer(layer_a, 50, str(i)))

layer_b = fully_connected_layer(layer_a, 10, 'b', nonlinearity=False)

predictions = tf.nn.softmax(layer_b) 
 
cross_entropy = tf.reduce_mean(-tf.reduce_sum(labels * tf.log(predictions), reduction_indices=[1]))
train_step = tf.train.AdamOptimizer(learning_rate_placeholder).minimize(cross_entropy)

print('Initializing variables.')
sess.run(tf.global_variables_initializer())
```
### What other attempted solutions have you tried?

None.

### Logs or other output that would be helpful

Some output from `python2 -m cProfile -o out.profile 1-mnist-simple.py`. This is a call to `sess.run(tf.global_variables_initializer())`.
![image](https://cloud.githubusercontent.com/assets/5461398/23191984/132ca252-f85e-11e6-8c55-9b48adc3d40b.png)

[cprofile-output.profile.zip](https://github.com/tensorflow/tensorflow/files/791923/cprofile-output.profile.zip)

**Comment by yaroslavvb** [comment]
Is it the first call, or can it be the second call? If it's the first call, it could have something to do with CUDA generating PTX, which happens the first time op is executed and is slow (and mega-slow if you are on nfs, set CUDA_CACHE_PATH=/non_nfs_dir). Whether or not PTX has to be generated depends on whether the binary was built with compute capability of your card

Does the problem disappear if you revert to older version? Does it happen with CPU-only TensorFlow?

**Comment by chrisranderson** [comment]
> Is it the first call, or can it be the second call? 

There's only one call to sess.run - for initializing the variables. If you're talking about running the script as a whole, so far it has been kinda unpredictable.

> If it's the first call, it could have something to do with CUDA generating PTX, which happens the first time op is executed and is slow (and mega-slow if you are on nfs, 

I'm running this all on my own machine.

> set CUDA_CACHE_PATH=/non_nfs_dir). Whether or not PTX has to be generated depends on whether the binary was built with compute capability of your card

It's a GTX 1060, so that's compute capability 6.1 I guess.

> Does the problem disappear if you revert to older version? Does it happen with CPU-only TensorFlow?

I switched to 0.12, CPU version: `tensorflow-0.12.0-cp27-cp27mu-manylinux1_x86_64.whl`. Waaaaay better! After that, I tried 0.12, GPU version: `tensorflow_gpu-0.12.0-cp27-cp27mu-manylinux1_x86_64.whl`. This returned to the same problem.

**Comment by chrisranderson** [comment]
Also around the same time I started noticing the problem, I installed opencv for Python 3. I guess that uses CUDA, so maybe that is related?

**Comment by yaroslavvb** [comment]
Running opencv with gpu tensorflow causes crashes on my machine, there's some kind of interference, I have to disable opencv GPU using `export OPENCV_OPENCL_RUNTIME=`

**Comment by yaroslavvb** [comment]
@chrisranderson what I meant was trying to compare against a GPU version from a different version. GPU version is known to be slow on first kernel launch (up to a minute) when your architecture compute capability is not included

**Comment by chrisranderson** [comment]
I tried `export OPENCV_OPENCL_RUNTIME=` before running tensorflow-gpu again, but it didn't seem to have an effect. I don't know what you mean by your second comment. 

Slowness is expected, but is 30 second for a network like the one I posted normal? It's pretty small. It seemed like initialization used to be quite fast. Is there something else I need to try with opencv?

Thanks for your help.

**Comment by yaroslavvb** [comment]
The "up to a minute" slowness I refer to is what happens when CUDA starts PTX compilation and is independent of your computation size. If that's your bottleneck, then the solution is compile with your architecture since the official binary only comes with support for ancient cards (I usually compile with 6.1 support, some wheels are here -- https://github.com/yaroslavvb/tensorflow-community-wheels). I'm not sure how to tell if it's indeed the PTX compilation that's causing the slowness, maybe @zheng-xq knows  some tricks.

**Comment by zheng-xq** [comment]
If it is indeed PTX compilation, you can look at the timeline, like this:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/timeline_test.py#L44

The first GPU kernel takes a really long time, without a good reason.

**Comment by chrisranderson** [comment]
Okay, here are the results of the profile. I looked at it in chrome://tracing/, but wasn't able to make sense of it.
[out.profile.zip](https://github.com/tensorflow/tensorflow/files/798039/out.profile.zip)

**Comment by yaroslavvb** [comment]
also you could try recompiling with support 6.1 architecture (just enter 6.1 during configure step)

**Comment by chrisranderson** [comment]
Anything else I should be aware of besides the stuff in here?
https://www.tensorflow.org/install/install_sources

**Comment by chrisranderson** [comment]
Starting the process of building from source right now.

**Comment by afri** [comment]
FWIW, I had the same slow startup problem with the 'latest-gpu' docker image and a GFX1080. 
Moving over to 'latest-devel-gpu', which is compiled with 6.1 architecture support, fixed it.

**Comment by neil454** [comment]
I had this same issue with my own docker container, even while using the 'latest-devl-gpu' container as @afri mentioned.

However, @chrisranderson, your comment about opencv made me realize what the problem was. You're right, compiling opencv with cuda support caused the slow startup for me.

By compiling opencv with `-D WITH_CUDA=OFF`, the problem is fixed, and my models run almost instantly.

**Comment by chrisranderson** [comment]
I built from source, and I've also tried 0.12 again. Still very slow. @neil454 thanks for the reply, I'd like to give that a shot.

**Comment by chrisranderson** [comment]
@neil454 I think that did the trick, thank you!

**Comment by girving** [comment]
@chrisranderson Is this fixed, or is there a code fix warranted?

**Comment by chrisranderson** [comment]
@girving I'd call it "band-aid fixed". Fully fixed would mean I could do whatever I wanted with opencv and not have it affect TensorFlow, I think. I have no idea why this happens or what the situation is, so maybe it's actually opencv's fault, or nvidia's fault or something.

**Comment by girving** [comment]
Alas!  I'm going to close, but with sadness.  Let us know if a clearer picture ever emerges.
