### ISSUE TITLE
Broken link to doc in extras.

### ISSUE THREAD

**Issue by BaiGang** [tensorflow/tensorflow#7757]
In the [doc on `nec_loss`](https://www.tensorflow.org/api_docs/python/tf/nn/nce_loss), the target doc of the "Candidate Sampling Algorithms Reference ", of which the url is https://www.tensorflow.org/api_docs/python/extras/candidate_sampling.pdf, is missing and gives just a 404 error.

**Comment by BaiGang** [comment]
I find the doc in https://www.tensorflow.org/extras/candidate_sampling.pdf . So I believe it's due to an improperly specified URL path.

**Comment by dr4b** [comment]
I put in a redirect for this and corrected the API docstrings internally, but it has to propagate out to the site.  Still, you should get redirected now (you may have to reload your browser if the 404 is cached)
