### ISSUE TITLE
TensorFlow for Poets: Section 5: Missing a verb

### ISSUE THREAD

**Issue by katzenbaer** [tensorflow/tensorflow#7762]
In https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/index.html?index=..%2F..%2Findex#4, "You might warnings" is missing a verb. Maybe "You might get warnings" or "You might see warnings"?

**Comment by katzenbaer** [comment]
![screen shot 2017-02-21 at 10 40 41 pm](https://cloud.githubusercontent.com/assets/1815591/23200020/cdf8761a-f886-11e6-8cd4-96ef83bbe81a.png)

**Comment by katzenbaer** [comment]
Also "they not harmful" might need a verb too...

**Comment by girving** [comment]
@wolffg If this is poetry, does it really need to be grammatically correct?

**Comment by wolffg** [comment]
No, the user is the poet; the codelab is not, so we should probably fix the grammar.

**Comment by MarkDaoust** [comment]
This is fixed.

Next codelab could be: TensorFlow poetry -  RNNs
