### ISSUE TITLE
TensorFlow for Poets: Section 5: label_image.py on site is different than curl version

### ISSUE THREAD

**Issue by katzenbaer** [tensorflow/tensorflow#7763]
Link: https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/index.html?index=..%2F..%2Findex#4

On the site, the `label_image.py` script uses relative paths for files while the version the tutorial asks users to curl uses absolute paths for files.

If the user is knowledgeable enough to prefer copying the script on the website vs. curl'ing it from https://goo.gl/tx3dqg, then the user might run into an issue where they first need to run `cd /` before being able to run the script as-is.

![screen shot 2017-02-21 at 10 47 37 pm](https://cloud.githubusercontent.com/assets/1815591/23200175/c6512762-f887-11e6-9d7f-f031bd839ecd.png)
![screen shot 2017-02-21 at 10 47 27 pm](https://cloud.githubusercontent.com/assets/1815591/23200176/c6682af2-f887-11e6-82a2-75a0641a127d.png)

**Comment by girving** [comment]
@wolffg Is this unfixed?

**Comment by MarkDaoust** [comment]
Fixed.
