### ISSUE TITLE
How to implement a custom Estimator with multiple model_fns?

### ISSUE THREAD

**Issue by Hong-Xiang** [tensorflow/tensorflow#7769]
How to implement a estimator with multiple model_fn so that we can train GAN-like models like following:
```
gan = my_estimator(model_fn=multi_model_fn, params=params)
for i in range(nb_train):
  gan.fit(x, y, model_id='gen', ...)
  gan.fit(x, y, model_id='cri', `...)
```

**Comment by poxvoculi** [comment]
This is a question better suited for StackOverflow, which we also monitor. Please ask it there and tag it with the `tensorflow` tag.

**Comment by gongzhitaao** [comment]
I came to the same problem.  

Just quickly scanned through the [code](https://github.com/tensorflow/tensorflow/blob/107cc777af7880c140d089e44ad898a6ba929286/tensorflow/python/estimator/estimator.py#L629), and it seems that there are no ways other than **hacking the internal implementation**.

My 2 cents on this issue is that maybe the `Estimator` could be more flexible.

For example, the `Estimator.train` function may take another optional argument, i.e., the `mode`, so that in the `Estimator.__init__`, we could create multiple `train_op` based on user-defined modes. 

```python
def model_fn(features, labels, mode, params):
  if mode == 'train.discriminator':
    train_op = ...
    loss = ...
  elif mode == 'train.generator':
    train_op = ...
    loss = 
  return tf.estimator.EstimatorSpec(...)

gan = tf.estimator.Estimator(model_fn=model_fn, ...)
for _ in range(10):
  gan.train(input_fn=input_fn, mode='train.discriminator', steps=2)
  gan.train(input_fn=input_fn, mode='train.generator', steps=2)
```

**Comment by bodokaiser** [comment]
There is some work going at [`tf.contrib.gain`][1] however I doubt there will be any compatibility with the `tf.estimator` interface as this would probably require api changes.

[1]: https://www.tensorflow.org/versions/master/api_docs/python/tf/contrib/gan

**Comment by joel-shor** [comment]
In the next 24 hours, I will opensource a `GANEstimator`, which is a tf.Estimator backed by TFGAN. I'll update the thread when I do.

**Comment by joel-shor** [comment]
I submitted the code. It'll get added to github at the next sync, no later than EOD monday.

**Comment by gongzhitaao** [comment]
I think it is not just GAN, many other models may need a more flexible interface, e.g., adversarial transform network, where training affects a different part of the model.

**Comment by joel-shor** [comment]
The `GANEstimator` is synced to opensource TF: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/gan/python/estimator/python. You should be able to use this example to solve the general problem of training different parts of the model.

**Comment by bodokaiser** [comment]
When does tfgan appear in the docs? I only see `tf.contrib.gan` modules from 9/21.

**Comment by diqiuzhuanzhuan** [comment]
> The `GANEstimator` is synced to opensource TF: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/gan/python/estimator/python. You should be able to use this example to solve the general problem of training different parts of the model.

Thank you for your code. But I saw the code "scalar_loss = gan_loss.generator_loss + gan_loss.discriminator_loss", so the hyperparameter k is always equal to 1. If I want to change this hyperparameter, how can I do?  Below is the k where it is from.
![image](https://user-images.githubusercontent.com/3667242/55311992-fd1eea00-5496-11e9-9ec7-f15ad847b668.png)

**Comment by zdgithub** [comment]
I encountered the same problem. I want to run two different models with different graphs, before I could use tf.Session() to set two graphs as default graph separately when using one of them, but now I don't know how to use them in Estimator...

**Comment by zdgithub** [comment]
> I came to the same problem.
> 
> Just quickly scanned through the [code](https://github.com/tensorflow/tensorflow/blob/107cc777af7880c140d089e44ad898a6ba929286/tensorflow/python/estimator/estimator.py#L629), and it seems that there are no ways other than **hacking the internal implementation**.
> 
> My 2 cents on this issue is that maybe the `Estimator` could be more flexible.
> 
> For example, one possible solution on top of my head is that the `Estimator.train` function may take another optional argument, i.e., the `mode`, so that in the `Estimator.__init__`, we could create multiple `train_op` based on user-defined modes.
> 
> ```python
> def model_fn(features, labels, mode, params):
>   if mode == 'train.discriminator':
>     train_op = ...
>     loss = ...
>   elif mode == 'train.generator':
>     train_op = ...
>     loss = 
>   return tf.estimator.EstimatorSpec(...)
> 
> gan = tf.estimator.Estimator(model_fn=model_fn, ...)
> for _ in range(10):
>   gan.train(input_fn=input_fn, mode='train.discriminator', steps=2)
>   gan.train(input_fn=input_fn, mode='train.generator', steps=2)
> ```

Hi, I have the same problem, so I wonder if the method you provide works well. Thank you!

**Comment by diqiuzhuanzhuan** [comment]
> > I came to the same problem.
> > Just quickly scanned through the [code](https://github.com/tensorflow/tensorflow/blob/107cc777af7880c140d089e44ad898a6ba929286/tensorflow/python/estimator/estimator.py#L629), and it seems that there are no ways other than **hacking the internal implementation**.
> > My 2 cents on this issue is that maybe the `Estimator` could be more flexible.
> > For example, one possible solution on top of my head is that the `Estimator.train` function may take another optional argument, i.e., the `mode`, so that in the `Estimator.__init__`, we could create multiple `train_op` based on user-defined modes.
> > ```python
> > def model_fn(features, labels, mode, params):
> >   if mode == 'train.discriminator':
> >     train_op = ...
> >     loss = ...
> >   elif mode == 'train.generator':
> >     train_op = ...
> >     loss = 
> >   return tf.estimator.EstimatorSpec(...)
> > 
> > gan = tf.estimator.Estimator(model_fn=model_fn, ...)
> > for _ in range(10):
> >   gan.train(input_fn=input_fn, mode='train.discriminator', steps=2)
> >   gan.train(input_fn=input_fn, mode='train.generator', steps=2)
> > ```
> 
> Hi, I have the same problem, so I wonder if the method you provide works well. Thank you!

The estimator is limited. Maybe you can try keras. There is a implementation on GAN, I hope it will help you. https://www.diqiuzhuanzhuan.com/2019/05/05/tensorflow%E5%AE%9E%E7%8E%B0%E7%94%9F%E6%88%90%E5%AF%B9%E6%8A%97%E7%BD%91%E7%BB%9C/
