### ISSUE TITLE
cuFFT, cuDNN, cuBLAS errors    AND    TF-TRT Warning: Could not find TensorRT    AND    could not open file to read NUMA node

### ISSUE THREAD

**Issue by DenisUllmann** [tensorflow/tensorflow#77694]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.17.0

### Custom code

No

### OS platform and distribution

Windows 11 Pro 23H2 WSL2 Ubuntu 22.04.5 LTS

### Python version

3.10.12

### CUDA/cuDNN version

CUDA 12.4 (WSL install) + cudnn 8.9.7 (pip TF[and-cuda] install)

### GPU model and memory

Quadro P620

### Current behavior?

Outputs errors and warnings when running the standard TF test `python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"`

Errors about cuFFT, cuDNN, cuBLAS ("already been registered").

Warning TensorRT not found and could not open file to read NUMA node.

Steps to reproduce on Windows11 WSL 2 Ubuntu:

* Install NVIDIA CUDA Toolkit for WSL as specified here https://docs.nvidia.com/cuda/wsl-user-guide/index.html
* Create venv and activate it
* pip install tensorRT
* pip install tf with CUDA (cudnn, cublas, cufft)
* test TF

The TF-nightly install does not find the GPU

### Standalone code to reproduce the issue

```shell
sudo apt-key del 7fa2af80
wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin
sudo mv cuda-wsl-ubuntu.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/12.6.2/local_installers/cuda-repo-wsl-ubuntu-12-6-local_12.6.2-1_amd64.deb
sudo dpkg -i cuda-repo-wsl-ubuntu-12-6-local_12.6.2-1_amd64.deb
sudo cp /var/cuda-repo-wsl-ubuntu-12-6-local/cuda-*-keyring.gpg /usr/share/keyrings/
sudo apt-get update
sudo apt-get -y install cuda-toolkit-12-6

python3 -m venv .venv
source .venv/bin/activate

pip cache remove "tensorrt*"
python3 -m pip install --upgrade pip
python3 -m pip install wheel
python3 -m pip install --upgrade tensorrt
python3 -m pip install --upgrade tensorrt-lean
python3 -m pip install --upgrade tensorrt-dispatch
python3 -m pip install tensorflow[and-cuda]

python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
```

### Relevant log output

```shell
2024-10-11 14:41:24.335456: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-11 14:41:24.955115: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-11 14:41:25.124162: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-11 14:41:26.366017: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-11 14:41:34.469157: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1728650506.662098    1240 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1728650508.389075    1240 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1728650508.389145    1240 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

**Comment by DenisUllmann** [comment]
When I perform a Debian install of TensorRT instead of a python installation, I get the same TF-TRT Warning.

Yet, `dpkg-query -W tensorrt` returns

`tensorrt        10.5.0.18-1+cuda12.6`

**Comment by jandy0414** [comment]
I have the same question, i think the CUDA version change to be 11.8

**Comment by Venkat6871** [comment]
Hi @DenisUllmann ,
Apologies for the delay, and thank you for raising your concern here. You may need to install a compatible version of TensorRT from NVIDIA, as it is an optimization library specifically developed by NVIDIA for their GPUs and is not bundled with the TensorFlow package. You can use the tensorflow[and-cuda] package to install TensorFlow with the required CUDA/cuDNN packages, but it seems TensorRT is not included.

https://github.com/tensorflow/tensorflow/blob/ced28148be8cec1f234886f21c7e528c374032b8/tensorflow/tools/pip_package/setup.py#L151-L166
 
Some related issues are already ongoing. Please go through them once, as I hope they will be helpful for you. I am providing the [links](https://github.com/tensorflow/tensorflow/issues/64809) to those issues here for your reference.

Thank you!

**Comment by DenisUllmann** [comment]
Hello @Venkat6871 ,

Thank you for your answer. As you see I get 3 issues with the installation of TF on WSL2, and you understood that the most critical one is about cudnn.

I have actually already tried the `pip install tensorfol[and-cuda]` as described in my original message. Surprisingly TF do not find the cuda/cudnn packages even with this specific `pip install` that should them as dependencies of TF. I can't understand why. 

Regarding TensorRT, do you know which version is compatible with the current TF 2.17.0 as it is not specified in the pip install guide for TF and I also already installed TensorRT but TF can't find it. 

Finally, regarding the NUMA errors, it seams that I have to build a custom WSL2 core that supports NUMA.

Thanks in advance for your help.

**Comment by DenisUllmann** [comment]
Hello, with the following installation (Cuda toolkit 12.3.2, cudnn 8.9.7) on WSL2, I still get the same errors and warnings but the training finally works on GPU WITH cudNN.

Errors displayed about cublas, cudnn and cufft registers are sent by XLA, but at the end these libraries are active.

There are no available TensorRT version compatible with my GPU and cuda toolkit 12.3 at the same time.

And Windows 11 Pro does not support NUMA, so XLA outputs Messages, but the setup works perfectly fine for training and inference.

Delete and create symlinks for `libcuda` in windows, then restart WSL  (https://github.com/microsoft/WSL/issues/5663#issuecomment-1068499676)

```
C:
cd \Windows\System32\lxss\lib
del libcuda.so
del libcuda.so.1
mklink libcuda.so libcuda.so.1.1
mklink libcuda.so.1 libcuda.so.1.1
wsl --shutdown
wsl
```

Install CUDA toolkit for WSL 12.3 (without cuda driver, NVIDIA Container Toolkit for WSL should be installed beforehand)

```
sudo apt-key del 7fa2af80
wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin
sudo mv cuda-wsl-ubuntu.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/12.3.2/local_installers/cuda-repo-wsl-ubuntu-12-3-local_12.3.2-1_amd64.deb
sudo dpkg -i cuda-repo-wsl-ubuntu-12-3-local_12.3.2-1_amd64.deb
sudo cp /var/cuda-repo-wsl-ubuntu-12-3-local/cuda-*-keyring.gpg /usr/share/keyrings/
sudo apt-get update
sudo apt-get -y install cuda-toolkit-12-3
```

Then download cudnn 8.9.7 https://developer.nvidia.com/rdp/cudnn-archive#a-collapse897-120

```
sudo dpkg -i cudnn-local-repo-ubuntu2204-8.9.7.29_1.0-1_amd64.deb
sudo cp /var/cudnn-local-repo-ubuntu2204-8.9.7.29/cudnn-local-08A7D361-keyring.gpg /usr/share/keyrings/
sudo apt-get update
sudo apt-get -y install libcudnn8    (use apt-cache search cudnn)
sudo apt-get -y install libcudnn8-dev
sudo apt autoremove
```

And testing install:

```
function lib_installed() { /sbin/ldconfig -N -v $(sed 's/:/ /' <<< $LD_LIBRARY_PATH) 2>/dev/null | grep $1; }
function check() { lib_installed $1 && echo "$1 is installed" || echo "ERROR: $1 is NOT installed"; }
check libcuda
check libcudart
```

```
function lib_installed() { /sbin/ldconfig -N -v $(sed 's/:/ /' <<< $LD_LIBRARY_PATH) 2>/dev/null | grep $1; }
function check() { lib_installed $1 && echo "$1 is installed" || echo "ERROR: $1 is NOT installed"; }
check libcudnn 
```

**Comment by DenisUllmann** [comment]
For those who may be interested, I could get TF 2.17 to run in WSL with a GPU computing capability of 6.1: the installed configuration is Python 11, CUDA 12.1, TensorRT 8.6.1, SSE3, SEE4.1, SSE4.2, FMA, AVX, AVX2.

CUDA 12.1 + TensorRT 8.6.1 is the right combination when yourGPU is 6.1

Bazel version is 6.5.0

GCC version is 12.3.0

Get your system architecture:

```
grep flags -m1 /proc/cpuinfo | cut -d ":" -f 2 | tr '[:upper:]' '[:lower:]' | { read FLAGS; OPT="-march=native"; for flag in $FLAGS; do case "$flag" in "sse4_1" | "sse4_2" | "ssse3" | "fma" | "cx16" | "popcnt" | "avx" | "avx2" | "mfpmath") OPT+=" -m$flag";; esac; done; MODOPT=${OPT//_/\.}; echo "$MODOPT"; }
```

Eg. I got: `-march=native -mssse3 -mfma -mcx16 -msse4.1 -msse4.2 -mpopcnt -mavx -mavx2`

Install install cuda toolkit 12.1 for wsl 12.1
```
wget https://developer.download.nvidia.com/compute/cuda/repos/wsl-ubuntu/x86_64/cuda-wsl-ubuntu.pin
sudo mv cuda-wsl-ubuntu.pin /etc/apt/preferences.d/cuda-repository-pin-600
wget https://developer.download.nvidia.com/compute/cuda/12.1.1/local_installers/cuda-repo-wsl-ubuntu-12-1-local_12.1.1-1_amd64.deb
sudo dpkg -i cuda-repo-wsl-ubuntu-12-1-local_12.1.1-1_amd64.deb
sudo cp /var/cuda-repo-wsl-ubuntu-12-1-local/cuda-*-keyring.gpg /usr/share/keyrings/
sudo apt-get update
sudo apt-get -y install cuda
```

Install cudnn 8.9.7 (download `*.deb` from nvidia)
```
sudo dpkg -i cudnn-local-repo-ubuntu2204-8.9.7.29_1.0-1_amd64.deb
sudo cp /var/cudnn-local-repo-ubuntu2204-8.9.7.29/cudnn-local-*-keyring.gpg /usr/share/keyrings/
sudo apt-get update
sudo apt-get -y install libcudnn8    (use apt-cache search cudnn)
sudo apt-get -y install libcudnn8-dev
sudo apt autoremove
```

Install tensorrt 8.6.1 (because I have a 6.1 GPU)
```
os="ubuntu2204"
tag="8.6.1-cuda-12.0"
sudo dpkg -i nv-tensorrt-local-repo-${os}-${tag}_1.0-1_amd64.deb
sudo cp /var/nv-tensorrt-local-repo-${os}-${tag}/*-keyring.gpg /usr/share/keyrings/
sudo apt-get update
sudo apt-get install tensorrt
```

Update python to 3.11
```
sudo apt update && sudo apt upgrade -y
sudo apt install python3.11
sudo update-alternatives --install /usr/local/bin/python3 python3 /usr/bin/python3.10 1
sudo update-alternatives --install /usr/local/bin/python3 python3 /usr/bin/python3.11 2
sudo update-alternatives --config python3
```
restart WSL, update Ubuntu related python packages
```
sudo apt remove --purge python3-apt
sudo apt autoclean
sudo apt install python3-apt
sudo apt-get install python3.11-distutils python3.11-dev python3.11-venv
curl -sS https://bootstrap.pypa.io/get-pip.py | python3.11
```

Follow these steps for the build : [https://www.tensorflow.org/install/source?_gl=1*gurby1*_up*MQ..*_ga*MTIxNDI1OTYyMi4xNzI5MDc5MzA2*_ga_W0YLR4190T*MTcyOTA3OTMwNi4xLjAuMTcyOTA3OTMwNi4wLjAuMA..#setup_for_linux_and_macos](tensorflow build from source)

When configuring the build `./configure` don't use CLANG as the host compiler (it says it is partially supported with CUDA 12.1 and it fails at the end). 
For the optimization flags, use the ones obtained previously about our system architecture.
Here are my answers for the configuration:

```
You have bazel 6.5.0 installed.
Please specify the location of python. [Default is /*/.venv/bin/python3]:


Found possible Python library paths:
  /*/.venv/lib/python3.11/site-packages
Please input the desired Python library path to use.  Default is [/*/.venv/lib/python3.11/site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: y
TensorRT support will be enabled for TensorFlow.

Found CUDA 12.1 in:
    /usr/local/cuda-12.1/targets/x86_64-linux/lib
    /usr/local/cuda-12.1/targets/x86_64-linux/include
Found cuDNN 8 in:
    /usr/lib/x86_64-linux-gnu
    /usr/include
Found TensorRT 8.6.1 in:
    /usr/lib/x86_64-linux-gnu
    /usr/include/x86_64-linux-gnu


Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus. Each capability can be specified as "x.y" or "compute_xy" to include both virtual and binary GPU code, or as "sm_xy" to only include the binary code.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 6.1]:


Do you want to use clang as CUDA compiler? [Y/n]: N
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]:


Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]: -march=native -mssse3 -mfma -mcx16 -msse4.1 -msse4.2 -mpopcnt -mavx -mavx2


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]:
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=mkl_aarch64    # Build with oneDNN and Compute Library for the Arm Architecture (ACL).
        --config=monolithic     # Config for mostly static monolithic build.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v1             # Build with TensorFlow 1 API instead of TF 2 API.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=nogcp          # Disable GCP support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished
```

export the variables requested when attempting to build, eg.: `export TF_PYTHON_VERSION=3.11`

And build with these options (no nccl and opt to build with SSE3, SEE4.1, SSE4.2, FMA, AVX, AVX2):

`bazel build //tensorflow/tools/pip_package:wheel --repo_env=WHEEL_NAME=tensorflow --config=opt --config=nonccl --verbose_failures`

And then `pip install` the built TF wheel.

You may need to `sudo apt-get install patchelf` before the build (in case the build fails because of it) but I am not sure, I may have installed it due to previous attemps to build.

The `import tensorflow` in python still outputs XLA related cuBLAS, cuDNN and cuFFT errors and NUMA warnings but we can ignore them as NUMA in currently not supported in WSL and all rquested CUDA libraries, including cuBLAS, cuDNN and cuFFT, are loaded when training.

**Comment by DenisUllmann** [comment]
Updates, as I think some might be interested in more recent versions with NUMA working : 

for TF>=2.18, you don't have to install CUDA + cuDNN + TensorRT before building from source, it can be automatically done by Bazel by setting the "hermetic" CUDA libraries versions you want during `./configure` without specifying any local CUDA libraries paths.

for WSL>=2.4.5 [NUMA is supported](https://github.com/microsoft/WSL/issues/12044#issuecomment-2544266709)

So you just have to:

update WSL >=2.4.5

install / upgrade python (like above, I tested with python 3.11 with TF2.20)

get your system architecture (like above)

get Bazel [here](https://github.com/bazelbuild/bazelisk/releases) + set version:
```
sudo dpkg -i bazelisk-amd64.deb
export USE_BAZEL_VERSION="7.4.1"
bazel --version
```

get clang (I tested with clang-19):
```
wget https://apt.llvm.org/llvm.sh
chmod +x llvm.sh
sudo ./llvm.sh 19 all
export PATH=/usr/lib/llvm-19/bin:$PATH
clang-19 --version
clang --version
```

`git source` tensorflow, select branch `r2.20` (tested, others >=2.18 may work), create+activate your `venv` or cond env and then `./configure`:
```
You have bazel 7.4.1 installed.
Please specify the location of python. [Default is /<your_env_path>/bin/python3]:


Found possible Python library paths:
  /<your_env_path>/lib/python3.11/site-packages
Please input the desired Python library path to use.  Default is [/<your_env_path>/lib/python3.11/site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]:
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: Y
CUDA support will be enabled for TensorFlow.

Please specify the hermetic CUDA version you want to use or leave empty to use the default version. 12.5.1


Please specify the hermetic cuDNN version you want to use or leave empty to use the default version. 9.3.0


Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus. Each capability can be specified as "x.y" or "compute_xy" to include both virtual and binary GPU code, or as "sm_xy" to only include the binary code.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]: <your compute_xy>


Please specify the local CUDA path you want to use or leave empty to use the default version.


Please specify the local CUDNN path you want to use or leave empty to use the default version.


Please specify the local NCCL path you want to use or leave empty to use the default version.


Do you want to use clang as CUDA compiler? [Y/n]:
Clang will be used as CUDA compiler.

Please specify clang path that to be used as host compiler. [Default is /usr/lib/llvm-18/bin/clang]: /usr/lib/llvm-19/bin/clang


You have Clang 19.1.7 installed.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]: <your system arch obtained above> -Wno-sign-compare


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]:
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=mkl_aarch64    # Build with oneDNN and Compute Library for the Arm Architecture (ACL).
        --config=monolithic     # Config for mostly static monolithic build.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v1             # Build with TensorFlow 1 API instead of TF 2 API.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=nogcp          # Disable GCP support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished
```

I tested with CUDA==12.5.1 + cuDNN==9.3.0 but other may work, although I believe that TF2.20 only works with CUDA12

Expunge bazel (safer):

```
bazel clean --expunge
```

Then build TF wheel (make sure to use `config=cuda_clang` instead of simply `config=cuda` and `--config=opt` to adapt to your system architecture):

```
bazel build //tensorflow/tools/pip_package:wheel --repo_env=USE_PYWRAP_RULES=1 --repo_env=WHEEL_NAME=tensorflow --config=cuda_clang --config=cuda_wheel --config=opt --verbose_failures
```

Should work, then install wheel:

```
pip install <your_tf_git_path>/tensorflow/bazel-bin/tensorflow/tools/pip_package/wheel_house/tensorflow-2.20.0.dev0+selfbuilt-cp311-cp311-linux_x86_64.whl
```
