### ISSUE TITLE
Update Performance guide compiler recommendation for macOS users

### ISSUE THREAD

**Issue by adyomin** [tensorflow/tensorflow#7776]
Hi!  

As per the [Performance guide](https://www.tensorflow.org/performance/performance_guide) I tried to build TF from source using gcc version 4.8.3+ on a MacBook.  I tried gcc 4.9 and 6.3 (Homebrew versions).  I got the following errors (same errors for 6.3):

- gcc-4.9: error: unrecognized command line option '-fcolor-diagnostics'
- gcc-4.9: error: unrecognized command line option '-Wthread-safety'
- gcc-4.9: error: unrecognized command line option '-Wself-assign'

According to [one](https://github.com/tensorflow/tensorflow/issues/1192) of the last years issues with the same errors, this is due to the fact that 

> We generally use the default of clang for OS X compilation, which explains your error. When I run gcc --version I get Apple LLVM version 7.0.2 (clang-700.1.81). You should try switching to clang instead of gcc, since that's the supported approach.

If this is still the case and all macOS users should stick to clang, could you please update the performance guide accordingly?

Best,
Andrei

**Comment by tfboyd** [comment]
This is on me.  Thank you for the feedback.  I will update the document.

**Comment by tfboyd** [comment]
https://github.com/tensorflow/tensorflow/pull/10781

Apologies that I did not understand the issue as much until I just started building on OS X as of last night.  Added the PR where I added the small change.  I hope to re do the build in the new few weeks but this is a great little add to have incase it takes a long time.

**Comment by tfboyd** [comment]
PR with updates has been merged it may take a bit for the website to be updated but the tweak is in.  Again as I said on another thread, I hope to redo the perf guide with everything that has been learned in the past 3-4 months by me personally and what I learned from all of the input from the community.  There is so much info to add.  Thank you for the feedback.
