### ISSUE TITLE
"The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations" in "Hello, TensorFlow!" program

### ISSUE THREAD

**Issue by bingq** [tensorflow/tensorflow#7778]
Opening this with reference to https://github.com/tensorflow/tensorflow/issues/7500. 

Installed TensorFlow 1.0 with reference to https://www.tensorflow.org/install/install_windows on Windows 10 and hit the same issue discussed in https://github.com/tensorflow/tensorflow/issues/7500.  With applying the solution suggested in that thread, the original issue disappeared but got the new warnings: 

C:\Users\geldqb>python
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
2017-02-22 22:28:20.696929: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-02-22 22:28:20.698285: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-22 22:28:20.700143: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-22 22:28:20.700853: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-22 22:28:20.701498: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-22 22:28:20.702190: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-02-22 22:28:20.702837: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-02-22 22:28:20.703460: W c:\tf_jenkins\home\workspace\nightly-win\device\cpu\os\windows\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
>>> print(sess.run(hello))
b'Hello, TensorFlow!'

**Comment by Carmezim** [comment]
Those are not errors. Those are warnings just informing you if you build TensorFlow from source it can be faster on your machine. Those instructions are not enabled by default on the I think to be compatible with more CPUs as possible. 
If you have any other doubts regarding this please feel free to ask, otherwise this can be closed.

**Comment by bingq** [comment]
Thanks Camezim !
Any hint of how to kill those warnings?

**Comment by Carmezim** [comment]
I am not sure but don't think you can, to my knowledge. But I didn't look into it so cannot guarantee. You can wait if other folks have an insight on that and let this issue open if you want. Another option is to post on StackOverflow under TensorFlow tag which is monitored by them as well.

**Comment by yaroslavvb** [comment]
@bingq the best way I found to kill unwanted TF output:

run your script as `tf.sh myscript.py` where tf.sh contains

```
#!/bin/sh
# Run python script, filtering out TensorFlow logging
# https://github.com/tensorflow/tensorflow/issues/566#issuecomment-259170351
python $* 3>&1 1>&2 2>&3 3>&- | grep -v ":\ I\ " | grep -v "WARNING:tensorflow" | grep -v ^pciBusID | grep -v ^major: | grep -v ^name: |grep -v ^Total\ memory:|grep -v ^Free\ memory:
```

You can add extra `|grep -v` parts to get rid of more things

**Comment by tomrunia** [comment]
@Carmezim Any estimate of how much faster when compiling from source using advanced CPU instructions? Any reason to do this at all when running most of the graph on a GPU?

**Comment by Carmezim** [comment]
I haven't tested myself, although heard 4-8x as it provides fast approximations of expensive operations. If  @yaroslavvb wants to chime in on that as [he himself got 3x speed improvement](https://github.com/tensorflow/tensorflow/issues/7257#issuecomment-277456370).

**Comment by yaroslavvb** [comment]
Yup, 3x for large matrix multiply on Xeon-V3, I expect it's probably due to FMA/AVX rather than SSE

**Comment by Carmezim** [comment]
@tomrunia Well remarked by @yaroslavvb, not SSE specifically in his case although those CPU instructions are expected to provide performance improvement

**Comment by Juanlu001** [comment]
It would be very nice to silence these warnings from the Python side, it's not so easy to use grep from Windows.

**Comment by yaroslavvb** [comment]
Try export TF_CPP_MIN_LOG_LEVEL=2

**Comment by Juanlu001** [comment]
> Try export TF_CPP_MIN_LOG_LEVEL=2

Thanks @yaroslavvb, I haven't tried it yet but an environment variable is definitely more useful.

**Comment by evgfreyman** [comment]
It works, thank you

**Comment by hughsando** [comment]
Is it possible that these errors are coming from the fact that with MSVC, x64, SSE2 is implicit (all x64 chips have SSE2) but the `__SSE2__` et al defines are not explicitly set?
Perhaps the guards should be on EIGEN_VECTORIZE_SSE2 etc instead.

**Comment by evgfreyman** [comment]
Could you say what should I exactly do according to your version? What "guards on" means?

**Comment by hughsando** [comment]
The SSE warnings use code like this:
```cpp
#ifndef __SSE__
    WarnIfFeatureUnused(CPUFeature::SSE, "SSE");
#endif  // __SSE__
#ifndef __SSE2__
    WarnIfFeatureUnused(CPUFeature::SSE2, "SSE2");
#endif  // __SSE2__
```
But the Eigen imeplementation (eigen/Eigen/Core) uses more complicated logic to work out whether to use SSS1/2:
```cpp
#ifndef EIGEN_DONT_VECTORIZE
  #if defined (EIGEN_SSE2_ON_NON_MSVC_BUT_NOT_OLD_GCC) || defined(EIGEN_SSE2_ON_MSVC_2008_OR_LATER)

    // Defines symbols for compile-time detection of which instructions are
    // used.
    // EIGEN_VECTORIZE_YY is defined if and only if the instruction set YY is used
    #define EIGEN_VECTORIZE
    #define EIGEN_VECTORIZE_SSE
    #define EIGEN_VECTORIZE_SSE2

    // Detect sse3/ssse3/sse4:
    // gcc and icc defines __SSE3__, ...
    // there is no way to know about this on msvc. You can define EIGEN_VECTORIZE_SSE* if you
    // want to force the use of those instructions with msvc.
    #ifdef __SSE3__
      #define EIGEN_VECTORIZE_SSE3
    #endif
    #ifdef __SSSE3__
      #define EIGEN_VECTORIZE_SSSE3
    #endif
    #ifdef __SSE4_1__
      #define EIGEN_VECTORIZE_SSE4_1
    #endif
    #ifdef __SSE4_2__
      #define EIGEN_VECTORIZE_SSE4_2
    #endif
    #ifdef __AVX__
      #define EIGEN_VECTORIZE_AVX
      #define EIGEN_VECTORIZE_SSE3
      #define EIGEN_VECTORIZE_SSSE3
      #define EIGEN_VECTORIZE_SSE4_1
      #define EIGEN_VECTORIZE_SSE4_2
    #endif
```
Due mainly to the fact Visual Studio assumes SSE1/SSE2 when compiling for x64.
Also note that is depends on EIGEN_DONT_VECTORIZE - perhaps some user customization.

So one solution would be to #include eigen/Eigen/Core and use the "EIGEN_VECTORIZE_SSE" symbols in the conditional code-guard ("`#ifndef EIGEN_VECTORIZE_SSE`"),
I'm not 100% sure about the build system and whether Eigen is the only source of SSE operations, so I'm not 100% sure that this is the right answer.

I'm also not sure what is the right thing to do if building a binary for distribution.  Do you include AVX and risk it not running, or do you not include it and risk the warning (and low performance)? Ideally you would build with full vectorization and let the software choose at runtime.  I guess another possibility would be to build 2 dlls, and dynamically load the right one at runtime.

**Comment by metorm** [comment]
You can try [this post](http://stackoverflow.com/a/42755665/4503060) and tell me if it really becomes faster.

**Comment by Carmezim** [comment]
@Juanlu001 Check this [comment](https://github.com/tensorflow/tensorflow/issues/1258#issuecomment-261365022) for how this variable works and @yaroslavvb's code below to a handy way to change it.

**Comment by RaviTezu** [comment]
Thanks @Carmezim 
Setting the env. variable `TF_CPP_MIN_LOG_LEVEL=3` via the os package inside the code worked :+1:

**Comment by aselle** [comment]
@hughsando, these are in fact the debates we had internally. Ideally in the future we'd be able to ship all compiled versions and choose at runtime, but logistically that's actually quite time consuming and tricky to implement. We are looking into it, but this was the best solution we had for now. We wanted people to know that if they have that warning, things are working, but it could be faster if you build it yourself. I.e. if you benchmarking our system, it's not a valid benchmark w/o compiling it with the best optimizations.

**Comment by yaroslavvb** [comment]
@hughsando PS people have been uploading wheels built for their favorite configuration to https://github.com/yaroslavvb/tensorflow-community-wheels

**Comment by hughsando** [comment]
I wonder if a solution to this problem might to to treat the cpu
architectures as different processors, like "cpu", "gpu", "cpu-avx".  Then
the kernels can register multiple versions, and the runtime can choose
where to run depending on the client machine.
This could be done for the main "hot" inference functions (eg, Conv2D), and
the deployment problem would largely go away.
Custom builds for training is not so difficult to manage - the community
wheels look like a good idea.

**Comment by aselle** [comment]
@hughsando, in spirit that is the idea we would like to pursue. However, it is more difficult than that in that we use Eigen for a lot of the implementations of kernels. Eigen would have to be compiled multiple ways without causing any symbol conflicts int the final binary, and also we would probably have to break up modules into more dsos so as not to have too large of a binary resident.

**Comment by hekimgil** [comment]
So after reading these, I went ahead and reinstalled, this time from Source following instructions on [https://www.tensorflow.org/install/install_sources](https://www.tensorflow.org/install/install_sources). I still see the "The TensorFlow library wasn't compiled to to use XXXX instructions..." warnings. So did I miss something or is installing from source and building is not what you meant by "building it yourself"?

**Comment by aselle** [comment]
What did you put for the compiler optimization options? and what are the remaining warnings it shows you? Are you running the binary on the same machine you compiled it on?

**Comment by hekimgil** [comment]
Thank you aselle, my problem is solved now but here is what happened:
- I used all default options with ./configure except: 1) Y for CUDA support, and 2) compute capability
- The warnings were about the SSE3, SSE4.1, SSE4.2, AVX, AVX2, and FMA capabilities of my machine (+ negative NUMA node read)
- Yes, the same machine...

However, after reading your message, I changed my bazel build command from `bazel build -c opt --copt=-march=native --config=cüda //tensorflow/tools/pip_package:build_pip_package ` to `bazel build -c opt --copt=-march=native --config=cüda //tensorflow/tools/pip_package:build_pip_package` with that extra `--copt=-march=native` in there and that did the trick. The warnings on instructions disappeared (albeit the NUMA warning still remaining). So although my problem seems to be solved, I wonder if it is possible that the `-march=native` is not really the default option for the "optimization flags to use" question in the ./configure options?

**Comment by aselle** [comment]
@gunan, is the default different as @hekimgil suggests. Is this expected behavior?

**Comment by gunan** [comment]
To fix the error messages, the bazel build command should be:
`bazel build --config opt --config cuda tensorflow/tools/pip_package:build_pip_package`

`-c opt` != --config opt`
-c means "--compilation_mode"

**Comment by hekimgil** [comment]
Thanks @gunan and @aselle and sorry for the confusion.

I saw the `-c opt` option in another website and wrongfully assumed it was equivalent to `--config=opt`... To double-check, I ran the bazel build again with `--config=opt` and without any extras (that is, no `--copt=-march=native`) and it works just fine...

Apologies for taking your time and thanks again for your responses...

**Comment by Daniel451** [comment]
Sorry for bothering, but I think the second question by @tomrunia was not answered? While it is clear that the CPU runtimes benefit a lot by compiling TensorFlow from source with optimizations enabled, I am also wondering if it has an impact on the runtimes when using the GPU-version?
I guess it should not make much of a difference for the GPU-version of TensorFlow?

**Comment by aselle** [comment]
@Daniel451, not as much,  but @zheng-xq can comment further.

**Comment by zheng-xq** [comment]
Depending on the model, it could make quite a bit of difference when the model has a lot to process with its input pipeline.

**Comment by Daniel451** [comment]
Ok, thanks for the clarification!

**Comment by fat-lobyte** [comment]
Well is there an official (or semi-official) build available that uses the "advanced" CPU instruction set?
Maybe add an official release for PIP, something like "tensorflow-sse" and "tensorflow-gpu-sse"?

After the official stable release of 1.0 I was kind of looking forward to not having to build TensorFlow myself anymore.
But if that implies taking a serious performance hit, I guess it's back to self-compiling again. :unamused:

**Comment by KendallWeihe** [comment]
I am unfamiliar with SSE, AVX, and FMA. I'm confused why I would be getting the same CPU warnings when I'm computing on my GPU. Furthermore, when I upgraded to r1.0 my compute time was significantly increased. What is going on? I can confirm that Tensorflow is using the GPU by the following initialization messages:

```
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1070
major: 6 minor: 1 memoryClockRate (GHz) 1.797
pciBusID 0000:03:00.0
Total memory: 7.92GiB
Free memory: 6.98GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:03:00.0)
```
 
Furthermore, I can see Tensorflow is using GPU memory:

```
volcart@volcart-Precision-Tower-7910:/usr/bin$ nvidia-smi
Tue Apr 11 12:25:36 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 0000:03:00.0      On |                  N/A |
| 17%   59C    P2    38W / 185W |   7871MiB /  8105MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      1120    G   /usr/lib/xorg/Xorg                             412MiB |
|    0      2188    G   compiz                                         244MiB |
|    0      2674    G   ...s-passed-by-fd --v8-snapshot-passed-by-fd    48MiB |
|    0      3529    G   ...eCTForProblematicRoots/disabled/ExpectCTR    72MiB |
|    0     15786    C   python3                                          8MiB |
|    0     20754    C   python3                                       7082MiB |
+-----------------------------------------------------------------------------+
```

Why is my training so much slower now?

>

**Comment by Zephyr-D** [comment]
Hi all,

I'm using Macbook Pro 2015 (8gb) to do some simple feature extraction with only CPU support. I first easily installed tf by pip but got those warnings. Thanks all above and I successfully recompiled tf from source follow the official instruction. Here're some result I want to share:
- Compiling (installing from source) time: about 1.5 hour
  (There're a lot warnings during compilation but it works at last, hopefully. Just follow the [instruction](https://www.tensorflow.org/install/install_sources))
- CPU computing speed up: about 2x
  (I'm using ResNet-50 to do feature extraction, the pip version takes about 85s a batch v.s. source version takes about 41s)

Hope this will help. But still, GTX will be a much better choice...

**Comment by ckalas** [comment]
I have successfully built the GPU version from source, but I'm not sure if the GPU is being used. Ill attach output below, but basically I don't see the CUDA imports. Does this mean something went wrong? 

`Using TensorFlow backend.
Found 2125 images belonging to 2 classes.
Found 832 images belonging to 2 classes.
demo.py:64: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<keras.pre..., validation_data=<keras.pre..., steps_per_epoch=128, epochs=5, validation_steps=832)`
  nb_val_samples=nb_validation_samples)
Epoch 1/5
2017-04-12 20:41:32.502286: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:865] OS X does not support NUMA - returning NUMA node zero
2017-04-12 20:41:32.502390: I tensorflow/core/common_runtime/gpu/gpu_device.cc:887] Found device 0 with properties: 
name: GeForce GT 750M
major: 3 minor: 0 memoryClockRate (GHz) 0.9255
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.74GiB
2017-04-12 20:41:32.502402: I tensorflow/core/common_runtime/gpu/gpu_device.cc:908] DMA: 0 
2017-04-12 20:41:32.502405: I tensorflow/core/common_runtime/gpu/gpu_device.cc:918] 0:   Y 
2017-04-12 20:41:32.502412: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GT 750M, pci bus id: 0000:01:00.0)`

**Comment by jshin49** [comment]
Here is the build command I used to get rid of those warnings by actually optimizing TensorFlow to my CPU:

```bash
sudo bazel build --config opt --copt=-msse4.1 --copt=-msse4.1 --copt=-mavx --copt=-mavx2 --copt=-mfma //tensorflow/tools/pip_package:build_pip_package
```

**Comment by logological** [comment]
@jshin49: Why are you using `--copt=-msse4.1` twice?  Or is the second one a typo, and you meant to write `--copt=-msse4.2`?

**Comment by jshin49** [comment]
@logological: You are right. It is a typo and I meant msse4.2.

Thanks for pointing it out!

**Comment by apacha** [comment]
Just as a matter of interest: How comes, these warnings were not present in Tensorflow 1.0.1 but only in newer version Tensorflow 1.1.0?

**Comment by akors** [comment]
> Just as a matter of interest: How comes, these warnings were not present in Tensorflow 1.0.1 but only in newer version Tensorflow 1.1.0?

Not quite sure what you mean, I am using the binaries from PIP for TF 1.0.1, and the warnings have been there already.

**Comment by apacha** [comment]
Aha... then maybe my cached wheel of TF 1.0.1 was somehow different. It displayed some warnings regarding OpKernels but no warnings regarding SSE instructions.

**Comment by ProgramItUp** [comment]
@jshin49 and others who have tried it
How much performance improvement are you seeing by recompiling with compiler optimizations?

**Comment by apacha** [comment]
No performance improvements here, when activating AVX, but probably because I was building and using the GPU-version. I thought it would speed up some parts at least, but I didn't find it to make a big impact. Probably when using the CPU-version it does make an impact.

**Comment by lgalke** [comment]
[Single Instruction Multiple Data](https://www.kernel.org/pub/linux/kernel/people/geoff/cell/ps3-linux-docs/CellProgrammingTutorial/BasicsOfSIMDProgramming.html) make sense when you perform vector computations on the CPU.  Thanks for the build-command examples.

**Comment by mphz** [comment]
@apacha  you should uninstall tensorflow and then reinstall again to kill the OpKernels warnings

**Comment by neelkadia** [comment]
If I do `export TF_CPP_MIN_LOG_LEVEL=2` then console don't show results, it just empty. 
and if I do `export TF_CPP_MIN_LOG_LEVEL=0` then only it popsup with all the warning and ***results***
```
2017-06-24 07:02:26.650752: W tensorflow/core/framework/op_def_util.cc:332] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
2017-06-24 07:02:26.851332: I tensorflow/examples/label_image/main.cc:251] withoutshadow (0): 0.801019
2017-06-24 07:02:26.851356: I tensorflow/examples/label_image/main.cc:251] withshadow (1): 0.198981
```
any thoughts why this happening?

**Comment by guruprasaad123** [comment]
I am also getting Warning while using tensorflow api  in java,I have no idea why i am getting this.Any idea to resolve this warning!

**Comment by Ewurama** [comment]
if you want to disable them, you may use the code below

    import os
    os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
    import tensorflow as tf

this should silence the warnings. 'TF_CPP_MIN_LOG_LEVEL' represents the Tensorflow environment variable responsible for logging. Also if you are on Ubuntu you may use this code below

    export TF_CPP_MIN_LOG_LEVEL=2 

I hope this helps.

**Comment by g10guang** [comment]
@Carmezim  If I compute with GPU, will I got this warning?
And how to know if tensorflow run with GPU or CPU?
Thanks.

**Comment by scotthuang1989** [comment]
Yes. You will still get the warning,  even if you install and run the GPU-version. Because this warning come from CPU, when your operation run on CPU and  can be speed up by SSE. I think you can ignore these warnings if you are not so concern with speed. If you do want go faster, you need install tensorflow from source to optimize tensorflow for some specific instruction set.

 

The easiest way of check if tensorflow run on CPU or GPU is open a resource manager for GPU or CPU (ps, nvidia-smi) to check loading when you run your training. 

You can also log the device placement ( config=tf.ConfigProto(log_device_placement=True) ), or use tensorboard to check it.

**Comment by Carmezim** [comment]
@g10guang Yeah, TF can use both CPU and GPU but even if you're using GPU only it will inform you of the SIMD instructions available when you run a program for the first time.

To know in which device TF is running you can set `log_device_placement` to `True` when creating the session as in:
`sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))`

You can see more details on this under **Logging Device placement** in the [documentation](https://www.tensorflow.org/tutorials/using_gpu).

**Comment by SragAR** [comment]
[tensorflow-build](https://github.com/lakshayg/tensorflow-build)
It is amazing. Time taken for for a training step is halved.

**Comment by shanuka** [comment]
Thanks @Carmezim  !

**Comment by giker17** [comment]
I am getting the same warning while using tensorflow_gpu 1.1.0 on win10, the version of Python is 3.6.3 installed in Anaconda.
Since the tf for **G**PU version is used, then what does that matters **C**PU?
I want to know what do these warnings mean, and what should I do or just leave them?

Here is my warnings:

```
C:\DevTools\Anaconda3\envs\py36_tfg>python
Python 3.6.3 | packaged by conda-forge | (default, Dec  9 2017, 16:22:46) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> sess = tf.Session()
2017-12-15 09:59:27.506604: W c:\l\work\tensorflow-1.1.0\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE instructions, but these are available on your machine and could speed up CPU computations.
2017-12-15 09:59:27.507839: W c:\l\work\tensorflow-1.1.0\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-15 09:59:27.509196: W c:\l\work\tensorflow-1.1.0\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-15 09:59:27.509641: W c:\l\work\tensorflow-1.1.0\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-15 09:59:27.510098: W c:\l\work\tensorflow-1.1.0\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-15 09:59:27.510475: W c:\l\work\tensorflow-1.1.0\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-12-15 09:59:27.512253: W c:\l\work\tensorflow-1.1.0\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-12-15 09:59:27.512821: W c:\l\work\tensorflow-1.1.0\tensorflow\core\platform\cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-12-15 09:59:27.824267: I c:\l\work\tensorflow-1.1.0\tensorflow\core\common_runtime\gpu\gpu_device.cc:887] Found device 0 with properties:
name: GeForce GTX 1060
major: 6 minor: 1 memoryClockRate (GHz) 1.6705
pciBusID 0000:01:00.0
Total memory: 3.00GiB
Free memory: 2.43GiB
2017-12-15 09:59:27.824508: I c:\l\work\tensorflow-1.1.0\tensorflow\core\common_runtime\gpu\gpu_device.cc:908] DMA: 0
2017-12-15 09:59:27.826709: I c:\l\work\tensorflow-1.1.0\tensorflow\core\common_runtime\gpu\gpu_device.cc:918] 0:   Y
2017-12-15 09:59:27.827566: I c:\l\work\tensorflow-1.1.0\tensorflow\core\common_runtime\gpu\gpu_device.cc:977] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0)
```

Another question:
How will I know if the tf using Gpu or Cpu while runing a program such as object detection, are there any tools suggested for monitoring my devices?

Thanks a lot.
: )

**Comment by gknight7** [comment]
Instead of removing the warning is there any way to use those SSE instructions to speed up the training

**Comment by SragAR** [comment]
@gknight7 
Please check my comment above.
