### ISSUE TITLE
installation failed on redhat 5.7

### ISSUE THREAD

**Issue by maplewizard** [tensorflow/tensorflow#778]
I installed tf from source code on redhat 5.7(I know it is a very old version), when I try to import tensorflow, it gives: anaconda/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: ELF file OS ABI invalid
How can I solve that?

**Comment by digitalsword** [comment]
@maplewizard If you have root access, you may upgrade glib and be able to install bazel, then use it to compile tensorflow. If you don't have root access, as far as I know it's very difficult to install bazel and tensorflow on redhat 5 or readhat 6.

**Comment by maplewizard** [comment]
@digitalsword yes. When I  am trying to install bazel, it said glib version missing, but I cannot compile glib sucessfully. Some strange error occur...

**Comment by bellaj** [comment]
@maplewizard  check your glibc version 

ldd --version 
or
/lib64/libc.so.6
On 32-bit Red Hat based systems:
$ /lib/libc.so.6

**Comment by maplewizard** [comment]
@bellaj The glibc version is too low. and I failed in compling it on the machine. I have no idea, maybe it cannot install on an old system.

**Comment by bellaj** [comment]
check your kernel version  uname -r

**Comment by maplewizard** [comment]
It's also a very low version 2.6.32-220.23.2

**Comment by digitalsword** [comment]
I am able to compile bazel using gcc 4.8 installed at custom path. https://github.com/bazelbuild/bazel/issues/760

But I am still not able to compile tensorflow with the bazel binary on a redhat 6.7 system.

```
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
INFO: Found 1 target...
ERROR: /nfs/02/h212/.cache/bazel/_bazel_h212/7a2b15405f00fa358f0e0720e30182fe/external/gemmlowp/BUILD:77:1: C++ compilation of rule '@gemmlowp//:eight_bit_int_gemm' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 31 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: unrecognized option '-no-canonical-prefixes'
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: error: unrecognized command line option "-fno-canonical-system-headers"
cc1plus: warning: unrecognized command line option "-Wno-free-nonheap-object"
Target //tensorflow/cc:tutorials_example_trainer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.992s, Critical Path: 1.13s
```

```
-bash-4.1$ ldd bazel_head_latest/output/bazel
    linux-vdso.so.1 =>  (0x00007fffd6386000)
    librt.so.1 => /lib64/librt.so.1 (0x00000032c2e00000)
    libz.so.1 => /lib64/libz.so.1 (0x00000032c2a00000)
    libstdc++.so.6 => /usr/local/gcc/4.8.4/lib64/libstdc++.so.6 (0x00002b82e38cb000)
    libgcc_s.so.1 => /usr/local/gcc/4.8.4/lib64/libgcc_s.so.1 (0x00002b82e3bd4000)
    libc.so.6 => /lib64/libc.so.6 (0x00000032c1a00000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00000032c2200000)
    /lib64/ld-linux-x86-64.so.2 (0x00000032c1600000)
    libm.so.6 => /lib64/libm.so.6 (0x00000032c260
```

**Comment by bellaj** [comment]
try the docker container

**Comment by maplewizard** [comment]
In fact, docker require that the kernel is above 3.1.  So it's not possible to do that....

**Comment by bellaj** [comment]
so upgrad you kernel

**Comment by maplewizard** [comment]
@bellaj Thanks for your advice. However, the system cannot be modified. I will try to find other methods.

**Comment by digitalsword** [comment]
@maplewizard I am in the same situation, I do not have root access. I managed to build bazel binary using a new version (4.8) of gcc installed at custom path. But when I use the bazel binary to compile tensorflow, it does invoke the old gcc compiler from the old system instead of the newer gcc I installed.

**Comment by maplewizard** [comment]
@digitalsword It seems no solution until now. I have no idea.

**Comment by bellaj** [comment]
if you have many gcc version you could use update-alternatives.

**Comment by girving** [comment]
@digitalsword: It sounds like this is a bazel issue rather than a TensorFlow issue if you can't get bazel to compile using the right gcc.  Sorry to redirect, but I don't think we'll be able to fix it on our end.
