### ISSUE TITLE
Bug: tf.math.angle returns 0.0 for real NaN input instead of NaN System information

### ISSUE THREAD

**Issue by LilyDong0127** [tensorflow/tensorflow#77821]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.16.1

### Custom code

Yes

### OS platform and distribution

windows

### Mobile device

win32

### Python version

3.9.19

### Bazel version

bazel version

### CUDA/cuDNN version

Not applicable (No GPU support)

### GPU model and memory

No GPU (using CPU)

### Current behavior?

Current Behavior:
When using `tf.math.angle` with a real NaN input, TensorFlow and Keras return `0.0`, while other frameworks such as PyTorch, JAX, and Chainer return `NaN`. Returning `0.0` for NaN is unexpected, as the angle of NaN is undefined and should return NaN.

### Standalone code to reproduce the issue

```shell
import torch
import tensorflow as tf
import jax.numpy as jnp
import numpy as np

# Create a scalar NaN tensor with dtype float32
input_tensor = tf.constant(float('nan'), dtype=tf.float32)

# PyTorch: angle function for real NaN input
def pytorch_angle(x):
    return torch.angle(torch.tensor(x, dtype=torch.float32)).numpy()

# JAX: angle function for real NaN input
def jax_angle(x):
    return jnp.angle(jnp.array(x)).item()

# Chainer: angle function for real NaN input
def chainer_angle(x):
    return np.angle(x)

# TensorFlow: angle function for real NaN input
def tf_angle(x):
    return tf.math.angle(x).numpy()

# Keras: using TensorFlow's angle function for real NaN input
def keras_angle(x):
    return tf.math.angle(x).numpy()

# Testing angle function across frameworks
print(f"PyTorch angle result: {pytorch_angle(float('nan'))}")
print(f"JAX angle result: {jax_angle(float('nan'))}")
print(f"Chainer angle result: {chainer_angle(np.array(float('nan')))}")
print(f"TensorFlow angle result: {tf_angle(input_tensor)}")
print(f"Keras angle result: {keras_angle(input_tensor)}")
```

### Relevant log output

```shell
Generated input: nan

PyTorch angle result: nan
JAX angle result: nan
Chainer angle result: nan
TensorFlow angle result: 0.0
Keras angle result: 0.0
```

**Comment by Venkat6871** [comment]
Hi **@LilyDong0127** ,
I tried running your code on Colab using TensorFlow v2.17.0 and the nightly version, and I encountered the same issue. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/d625a888c7d5ecd42a4709216e5e5353/77821_tf-2-17-0-nightly-v.ipynb) provided here for reference.
Some related issues are already being tracked. Please review them as well, as they might be helpful. I am providing the [links](https://github.com/tensorflow/tensorflow/issues/50854) to those issues for your reference.

Thank you!
