### ISSUE TITLE
Installing tensorflow version 2.17.0 and curl is getting installed of version 7.85.0 which is outdated. Is there way to remove critical Vulnerability for curl 7.85.0.

### ISSUE THREAD

**Issue by adarshbilimagga** [tensorflow/tensorflow#77843]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.17.0

### Custom code

Yes

### OS platform and distribution

windows

### Current behavior?

Install tensorflow version 2.17.0 and curl is getting installed of version 7.85.0 which is outdated. Having security vulnerabilities for tensorflow-io-gcs-filesystem/tensorflow_io_gcs_filesystem-0.31.0-cp310-cp310-win_amd64.whl.

Getting below vulnerabilities:
https://github.com/advisories/GHSA-7xw9-w465-6x42
https://github.com/advisories/GHSA-grfr-78m7-q35q
https://github.com/advisories/GHSA-6xq7-qqp2-9mmc
https://github.com/advisories/GHSA-99j9-jf36-9747
https://github.com/advisories/GHSA-xvw3-6q4f-2gcv
https://github.com/advisories/GHSA-4j25-c9rf-fp5f
https://github.com/advisories/GHSA-75qm-2q4j-qx6g
https://github.com/advisories/GHSA-25m2-mpq4-29vh
https://github.com/advisories/GHSA-grfr-78m7-q35q
https://github.com/advisories/GHSA-98w6-hw73-ph8m
https://github.com/advisories/GHSA-6295-5j29-3cc8

**Comment by tilakrayal** [comment]
@adarshbilimagga,
The mail brach has been moved from 7.85.0 to "curl-8.6.0". Could you please have a look at the below file  for the reference.
```python

    tf_http_archive(
        name = "curl",
        build_file = "//third_party:curl.BUILD",
        sha256 = "9c6db808160015f30f3c656c0dec125feb9dc00753596bf858a272b5dd8dc398",
        strip_prefix = "curl-8.6.0",
        system_build_file = "//third_party/systemlibs:curl.BUILD",
        urls = tf_mirror_urls("https://curl.se/download/curl-8.6.0.tar.gz"),
    )
```

Main branch: 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace2.bzl#L426-L435

Thank you!

**Comment by adarshbilimagga** [comment]
By default pip install tensorflow-io-gcs-filesystem will download the version which is available for windows i.e as shown below:
**tensorflow_io_gcs_filesystem-0.31.0-cp311-cp311-win_amd64.whl** 
With this version of tensorflow-io-gcs-filesystem it is referring the older version of curl library.
Is there any way we will be able to get the latest version of tensorflow-io-gcs-filesystem wheel file for windows version.

**Comment by adarshbilimagga** [comment]
> @adarshbilimagga, The mail brach has been moved from 7.85.0 to "curl-8.6.0". Could you please have a look at the below file for the reference.
> 
> ```python
>     tf_http_archive(
>         name = "curl",
>         build_file = "//third_party:curl.BUILD",
>         sha256 = "9c6db808160015f30f3c656c0dec125feb9dc00753596bf858a272b5dd8dc398",
>         strip_prefix = "curl-8.6.0",
>         system_build_file = "//third_party/systemlibs:curl.BUILD",
>         urls = tf_mirror_urls("https://curl.se/download/curl-8.6.0.tar.gz"),
>     )
> ```
> 
> Main branch: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace2.bzl#L426-L435
> 
> Thank you!

We did check with latest version but as mentioned we are facing issue still.
