### ISSUE TITLE
glorot_uniform_initializer and others not exported

### ISSUE THREAD

**Issue by taion** [tensorflow/tensorflow#7791]
Many initializers defined in `init_ops` are not exported in the global TensorFlow package. These include:

- `glorot_uniform_initializer` (this is even explicitly mentioned in the docs as the default initializer for variables)
- `glorot_normal_initializer`
- `variance_scaling_initializer`

It seems like this might be an oversight – `glorot_uniform_initializer` is mentioned in existing documentation, and `glorot_normal_initializer` has no other hits in the code base, which makes it seem like it's for user consumption.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

Searched 

### Environment info
v1.0.0 docker image

### What other attempted solutions have you tried?
Similar initializers are available in `tf.contrib.layers`, but it seems preferable to use the ones that already exist in core.

**Comment by tfboyd** [comment]
@lucaswiser  Can you comment on this?  I asked @martinwicke and he was not sure if this was an oversight or on purpose.

**Comment by lukaszkaiser** [comment]
I believe it's an oversight, but could you confirm with fchollet@ to be sure? Thanks!

**Comment by fchollet** [comment]
That's an oversight, I will send out a fix. Thanks for the report.

**Comment by pvaneck** [comment]
This issue was resolved here: https://github.com/tensorflow/tensorflow/commit/4cf4f524cb93ad0c1d6c35e9ccec62cf9015b217 So this can be closed.

**Comment by martinwicke** [comment]
Thanks!

**Comment by taion** [comment]
Sweet!
