### ISSUE TITLE
Cannot specify XLA config for learn.estimators ?

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/tensorflow#7794]
Seems that the MonitoredSession is being allocated directly:

https://github.com/tensorflow/tensorflow/blob/f821ce046df71f5784ed4ce7fb6b87f77d96b031/tensorflow/contrib/learn/python/learn/estimators/estimator.py#L962

and there is no way to pass or specify different `graph_options` to the session to enable the XLA jit configuration. Is that the case or I am missing something?

**Comment by yaroslavvb** [comment]
Looks like a missing functionality. @ispirmustafa -- is there any plan to allow configuring Session options for session used in estimator?

As a work-around, you could monkey-patch `Session.__init__` method to add XLA config, something like this

```
oldinit = tf.Session.__init__
def myinit(session_object, target='', graph=None, config=None):
    print("Intercepted!")
    optimizer_options = tf.OptimizerOptions()
    optimizer_options.global_jit_level = tf.OptimizerOptions.ON_1
    config = tf.ConfigProto(graph_options=tf.GraphOptions(optimizer_options=optimizer_options))
    return oldinit(session_object, target, graph, config)
tf.Session.__init__ = myinit
```

**Comment by tfboyd** [comment]
@ispirmustafa This might be a good requirement/feature to add while working on Estimators.  As if the list is not long enough.  :-)  Assigning to you as the best person to answer to follow.

**Comment by tomwanzek** [comment]
I came across what appears to be the same need wanting to set `log_device_placement` as another use case.

**Comment by tfboyd** [comment]
Some is assigned to work on this internally.  While we cannot promise an ETA, weeks is the estimate.  I know this may seem hacky but I think you could wrap the model code and operations in a big "with" and get the results you want in the mean time.  My python is not super strong and while I played with the JIT I never tried to wrap all of the operations this way.  I do not see why it would not work.  I might be over simplifying but trying this should not take too much effort to try.

```python
 jit_scope = tf.contrib.compiler.jit.experimental_jit_scope

    x = tf.placeholder(np.float32)
    with jit_scope():
      y = tf.add(x, x)  # The "add" will be compiled with XLA.
```

**Comment by xiejw** [comment]
I think this was already fixed. session_config could be set in RunConfig now  [1] and used by Estimator.

[1] https://github.com/tensorflow/tensorflow/blob/076799bdfae0057723d96f47cf78cb623c8bcd57/tensorflow/contrib/learn/python/learn/estimators/run_config.py#L233
[2] 
https://github.com/tensorflow/tensorflow/blob/076799bdfae0057723d96f47cf78cb623c8bcd57/tensorflow/contrib/learn/python/learn/estimators/estimator.py#L380
