### ISSUE TITLE
Typo in "Validate Your Installation" document.

### ISSUE THREAD

**Issue by macmason** [tensorflow/tensorflow#7795]
https://www.tensorflow.org/install/install_linux#ValidateYourInstallation

Partway down:

> If you are new to TensorFlow, see [Getting Started with TensorFlow]Getting Started With TensorFlow.

Note the extraneous square brackets; looks like a markdown typo. Interestingly, the "Getting Started With" link still works (which did not survive my copy-paste into the issue tracker).

**Comment by dr4b** [comment]
I've fixed this internally but it will take a bit to propagate out to the site.  Thanks for reporting.

**Comment by macmason** [comment]
This doesn't look to have propagated yet; did you mean to close this before the fix landed?

**Comment by dr4b** [comment]
Hey, it has propagated out now, although now we have a separate bug in the page (an unclosed bold).
