### ISSUE TITLE
Potential to add tf.image.rotate?

### ISSUE THREAD

**Issue by jkschin** [tensorflow/tensorflow#780]
I experimented with the CIFAR10 example. I noticed that they have very good transformation functions. For example, flipping up down and left right. Would it be good if we add a rotate function? For example:

tf.image.rotate(image,angle)

where angle is the degrees to rotate by in the anti-clockwise direction.

**Comment by bhack** [comment]
See also https://github.com/tensorflow/tensorflow/issues/781

**Comment by martinwicke** [comment]
I'm going to close this in favor of #781
