### ISSUE TITLE
Is it a error?

### ISSUE THREAD

**Issue by guotong1988** [tensorflow/tensorflow#7805]
### Environment info
Operating System: CentOS 7 
tensorflow version: 0.12.1

### Installed version of CUDA and cuDNN: 

/usr/local/cuda-8.0/lib64/libcudadevrt.a
/usr/local/cuda-8.0/lib64/libcudart.so -> libcudart.so.8.0
/usr/local/cuda-8.0/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
/usr/local/cuda-8.0/lib64/libcudart.so.8.0.44
/usr/local/cuda-8.0/lib64/libcudart_static.a
/usr/local/cuda-8.0/lib64/libcudnn.so -> libcudnn.so.5
/usr/local/cuda-8.0/lib64/libcudnn.so.5 -> libcudnn.so.5.1.3
/usr/local/cuda-8.0/lib64/libcudnn.so.5.1.3
/usr/local/cuda-8.0/lib64/libcudnn_static.a

### Question:
When I run a program. It print the below info. (Then the machine shutdown.)
![_20170223100205](https://cloud.githubusercontent.com/assets/4702353/23242344/321555be-f9b3-11e6-8115-63fc129f3922.png)

I remember when it run successfully on two GPU , it print:
```
Y N
N Y
```
not
```
Y Y
Y Y
```

**Comment by yaroslavvb** [comment]
This information comes from cuda driver which tells which pairs of GPUs can use DMA, there are probably some NVidia cuda tools that let you see this matrix

**Comment by yaroslavvb** [comment]
Closing since this doesn't seem to be a tensorflow error
