### ISSUE TITLE
How to extract the native library

### ISSUE THREAD

**Issue by kuluofenghun** [tensorflow/tensorflow#7807]
I am new to the tensorflow for java. I want to ask how to extract the native library? Is there some guidance?

**Comment by asimshankar** [comment]
This question is probably better asked on [stackoverflow](https://www.stackoverflow.com/questions/tagged/tensorflow) as we try to keep the github issues focused on bugs and feature requests.

I didn't quite follow what you meant by "extract the native library". The [Java README](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/README.md) provides instructions for downloading the native binary archive and extracting it with `tar` as well as instructions for building the native library from source.
