### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by conqer** [tensorflow/tensorflow#7812]
Building from source shows a lot of warnings,mostly due to either:

- Comparison between signed and unsigned integers
- Initialized variables
- Code reaching "non-return" path for functions that return a non-void.

I have submitted a patch that fixes a bunch of these (https://github.com/tensorflow/tensorflow/pull/7752)

`Operating System`:
Linux (ubuntu 14.04) 

`Commit hash` : 4ac9c09d5ca57a03b8daa5fb9e295947b1619854

`gcc version`: 4.8.4

`bazel version`:

bazel version
Build label: 0.4.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Feb 1 18:54:21 2017 (1485975261)
Build timestamp: 1485975261
Build timestamp as int: 1485975261

**Comment by martinwicke** [comment]
Thanks for the patch! I'll look at that, and close this issue.
