### ISSUE TITLE
tensorflow 1.0 error: ValueError: Only call `sigmoid_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

### ISSUE THREAD

**Issue by pengjingg** [tensorflow/tensorflow#7814]
### Environment info
Operating System:
Ubuntu 14.0.4
tensorflow 1.0
cuda 8.0 + cudnn 5.1

### Project
DCGAN: the code is downloaded here
https://github.com/carpedm20/DCGAN-tensorflow

### Logs or other output that would be helpful
![image](https://cloud.githubusercontent.com/assets/25976861/23252160/bd6c2570-f9ea-11e6-92fd-523a2acc8461.png)
### Codes that may have problems
![image](https://cloud.githubusercontent.com/assets/25976861/23252201/e972a39c-f9ea-11e6-8938-a0d4dcc29c9f.png)

I`m new in tf and I don`t know how to solve the problem.
I`ll appreciate any suggestions. Thank you!

**Comment by mrry** [comment]
What happens if you replace this expression:

```python
tf.nn.sigmoid_cross_entropy_with_logits(self.D_logits_, tf.ones_like(self.D_))
```

...with the following:

```python
tf.nn.sigmoid_cross_entropy_with_logits(logits=self.D_logits_, labels=tf.ones_like(self.D_))
```

**Comment by pengjingg** [comment]
Thanks a lot! It perfectly solved my problem! @mrry

**Comment by mohitkaushikj133** [comment]
I am getting this error while using 

AttributeError: 'Model' object has no attribute 'D_logits_'
