### ISSUE TITLE
tf r1.0 strided_slice documentation

### ISSUE THREAD

**Issue by guidj** [tensorflow/tensorflow#7815]
In the [docs](https://www.tensorflow.org/api_docs/python/tf/strided_slice), the following sentences seem incomplete/incoherent:

- If the ith bit of ellipsis_mask `[is-set-to-something]`, as many unspecified dimensions as needed will be inserted between other dimensions. Only one non-zero bit is allowed in ellipsis_mask.

- If the ith bit of new_axis_mask is one, then `a?` begin, end, and stride are ignored and a new length 1 dimension is added at this point in the output tensor

**Comment by dr4b** [comment]
Great, could you make a PR with your change?

**Comment by guidj** [comment]
I did, and it's already been [merged](https://github.com/tensorflow/tensorflow/pull/7831)
So I guess this can be closed

**Comment by dr4b** [comment]
sounds good to me!  thanks!
