### ISSUE TITLE
Gradient Boosting Decision Trees at TensorFlow

### ISSUE THREAD

**Issue by Iolaum** [tensorflow/tensorflow#7823]
At TensorFlow Dev Summit 2017 Mr. Ashish Agarwal gave a presentation for ML Toolkit and said that Gradient Boosting Decision Trees [are coming soon](https://youtu.be/Tuv5QYKU-MM?t=271).  I would like to ask two questions:

 * Is there an approximate timeline for when this feature might be released? 
 * Is there any information if we will be able to leverage tensorflow's local (GPU computing) and distributed capabilities (for example as [presented by Mr. Jonathan Hseu](https://www.youtube.com/watch?v=yALzr4A2AzY)) for this particular algorithm?

**Comment by agarwal-ashish** [comment]
We are hoping to open source these in Q2. Initial support will be on CPU and distributed.

**Comment by adrianog** [comment]
Hi

Has this been released?

**Comment by rezacsedu** [comment]
Hello Guys,
Is there any update on this issue?

**Comment by Iolaum** [comment]
I can't find anything in the 1.2 release notes for GBM's. Only improvements in deployment for Random Forest Implementation.

**Comment by pbermingham** [comment]
Waiting for this too.

**Comment by sandys** [comment]
+1 on this - we are interested in regression trees for tensorflow

**Comment by source-ram** [comment]
+1

**Comment by Downchuck** [comment]
Seems to be a lot of activity:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/boosted_trees

**Comment by nicholas-leonard** [comment]
The [tf.GradientBoostedDecisionTree](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/boosted_trees/estimator_batch/estimator.py) estimators inherit the "old" tf.contrib.learn.Estimator. Will these be updated to inherit the "stable" tf.estimator.Estimator instead?

**Comment by sshrdp** [comment]
@nicholas-leonard Yes. That's the plan.

**Comment by amalF** [comment]
Hello, 
Will TF Boosted Trees will be supported on GPU soon ? 

Thx

**Comment by haiy** [comment]
+1

**Comment by wuciawe** [comment]
Do TF Boosted Trees support distributed training?

**Comment by sshrdp** [comment]
Yes, distributed training is supported. 
There are no plans to support GPU training at the moment but contributions are always welcomed :)

**Comment by tanzhenyu** [comment]
+1 on contributions welcome. I added the label.

**Comment by Iolaum** [comment]
@tanzhenyu The issue has been closed. Maybe reopen since contribution are welcome?
