### ISSUE TITLE
tf version not working on older linux version

### ISSUE THREAD

**Issue by kirk86** [tensorflow/tensorflow#7825]
Hi, may I ask if `tf` is built on `ubuntu`? The many linux wheel from pip or even anaconda causes errors on systems such as `CentOS 6.6`. Particularly it is looking for a `GLIBC-2.16.so` but can't find it. On my system there exists only `GLIBC-2.14.so`. Does anyone have any solution for this?

**Comment by martinwicke** [comment]
For older versions of linux (incl. CentOS 6.x) you have to build from source.

**Comment by kirk86** [comment]
@martinwicke thanks for the answer. But for some of us operating on a cluster with limited permissions that's not an option. Because the cluster might be missing some libraries required to build from source and it's impossible to install them if you don't have permissions.

**Comment by martinwicke** [comment]
I am sorry. We have no way to build for all platforms out there. If they binaries we publish don't work on your platform, you have to build from source. Our build process has dependencies too, if you have no way to install those dependencies, you're out of luck. 

Often, the simplest solution is docker, or using an installation of your target system inside a docker container running on a modern machine to build.

**Comment by kirk86** [comment]
@martinwicke thanks a lot, appreciated. I've tried many things but nothing has worked so far. I'm hopping the guys from anaconda keep up they word and resolve this issue with the next release of anaconda. They said the next release would be able to build packages from source. Let's hope so.
