### ISSUE TITLE
bazel error

### ISSUE THREAD

**Issue by ymakkapa** [tensorflow/tensorflow#7826]
Hello everyone,
![bazelerror](https://cloud.githubusercontent.com/assets/20130992/23277161/ec375632-f9da-11e6-8117-d834540c3d4e.png)

As I am having an error "AttributeError: 'module' object has no attribute 'GRUCell'" when tried to run transate.py i removed tensorflow from my system and started installing it again from sources. I installed bazel and configured the installation. After "Build the pip package", I am getting the following error.

System specifications:
I installed Ubuntu 16.04 on vmware with 2 GB RAM and 100 GB disk space 

Can anyone please help me in resolving these errors

Thanks in advance

**Comment by achbogga** [comment]
Hello @ymakkapa ,
As suggested by your console, did you try executing Sudo with -H option?
 I had a similar issue and I used virtual environment because I did not have root access. Please try these options and let me know what happened.

**Comment by ymakkapa** [comment]
Hello,
Which command should I execute with -H option?

**Comment by ymakkapa** [comment]
Hello,
I did as u said and still got these following errors
![baze](https://cloud.githubusercontent.com/assets/20130992/23278861/edcc001e-f9e0-11e6-9804-9cae3494ed47.PNG)

**Comment by achbogga** [comment]
After configuring, you need to make sure that you have this command executed ccorrectly:
`bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`
Then, you need to make sure you enter the pip install command with sudo -H option.

**Comment by ymakkapa** [comment]
Yes, I did the same way. the command "bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
" is executed previously. please see the picture attached
![b2](https://cloud.githubusercontent.com/assets/20130992/23279448/52b18a2e-f9e3-11e6-9403-7e248c193f11.PNG)

**Comment by poxvoculi** [comment]
are you still having trouble?

**Comment by ymakkapa** [comment]
Yes @poxvoculi

**Comment by poxvoculi** [comment]
your screen image does not indicate a problem.

**Comment by ymakkapa** [comment]
This is my problem actually
![baze](https://cloud.githubusercontent.com/assets/20130992/23317098/076a3e9a-fa9b-11e6-9c46-4c7a8c735624.PNG)

**Comment by martinwicke** [comment]
You're trying to install a file that doesn't exist.

**Comment by martinwicke** [comment]
I don't see a problem here. If you have evidence of an issue with tensorflow, please open a new issue.
