### ISSUE TITLE
./configure should be made script friendly

### ISSUE THREAD

**Issue by kali** [tensorflow/tensorflow#7843]
Building tensorflow artefacts today is made difficult by the fact that the ./configure script requires interactive inputs. For default automated builds, one solution is: `echo "\n\n\n\n\n\n\n\n\n" | ./configure` (or `yes ''` and catching the error) but this is far from satisfactory, and tweaking the parameter is even more difficult.

See https://github.com/Homebrew/homebrew-core/pull/10273#discussion_r102895387 for instance in homebrew, but other packager will presumably hit the same issue.

**Comment by PatWie** [comment]
You can set the environment variables appropriately like in the following bash script:
https://gist.github.com/PatWie/0c915d5be59a518f934392219ca65c3d

**Comment by chrisranderson** [comment]
@poxvoculi, looking through [configure.py](https://github.com/tensorflow/tensorflow/blob/c527d67d21f4b1d778ca92d3c3478c381aba5fd6/configure.py), these are the only variables I found:
```
CUDA_TOOLKIT_PATH
LD_LIBRARY_PATH
MPI_HOME
PYTHON_LIB_PATH
PYTHONPATH
TF_CUDA_CLANG
TF_DOWNLOAD_CLANG
TF_NEED_COMPUTECPP
TF_NEED_CUDA
TF_NEED_MPI
TF_NEED_OPENCL_SYCL
USE_DEFAULT_PYTHON_LIB_PATH
```

The gist you linked to uses these:
```
CC_OPT_FLAGS
CUDA_TOOLKIT_PATH
CUDNN_INSTALL_PATH
GCC_HOST_COMPILER_PATH
PYTHON_ARG
PYTHON_BIN_PATH
PYTHON_LIB_PATH
PYTHONPATH
TF_CUDA_CLANG
TF_CUDA_COMPUTE_CAPABILITIES
TF_CUDA_VERSION
TF_CUDNN_VERSION
TF_DOWNLOAD_MKL
TF_ENABLE_XLA
TF_NEED_CUDA
TF_NEED_GCP
TF_NEED_HDFS
TF_NEED_JEMALLOC
TF_NEED_MKL
TF_NEED_MPI
TF_NEED_OPENCL
TF_NEED_VERBS
```

Here's the diff:
![image](https://user-images.githubusercontent.com/5461398/44063593-672aaa4e-9f1e-11e8-8f24-1417ebaa1ddc.png)


There are some you include that are extra, and some that you don't include. Is there a complete list of options for configuring the build somewhere?

**Comment by PatWie** [comment]
You need to set these

https://github.com/tensorflow/tensorflow/blob/master/configure.py#L1462-L1483

And additionally

https://github.com/tensorflow/tensorflow/blob/master/configure.py#L872
https://github.com/tensorflow/tensorflow/blob/master/configure.py#L883
...

There even some new variables like [`TF_NEED_KAFKA`](
https://github.com/tensorflow/tensorflow/blob/master/configure.py#L1466) which are not in the gist.

Just grep for `environ_cp.get` in `configure.py`. I will update the gist.
