### ISSUE TITLE
What does the tensor "transformer_layer_0/BroadcastTo" do, and why is it quantized to INT32?

### ISSUE THREAD

**Issue by i3abghany** [tensorflow/tensorflow#78475]
### 1. System information

- Linux Ubuntu 22.04
- TensorFlow 2.12 installed via pip

#### Option A: Reference colab notebooks

1)  Reference [TensorFlow Model Colab](https://colab.research.google.com/github/tensorflow/codelabs/blob/main/KerasNLP/io2023_workshop.ipynb): The KerasNLP workshop from IO2023

The link to the model I produced using the notebook is here: https://drive.google.com/file/d/1nSABgkHysrwkAn8K3H45Eqq646iNZOBp/view?usp=sharing

### Other info

I follow the IO 2023 workshop notebook above to use KerasNLP to produce a quantized GPT2 in the tflite format.

I then visualize the tflite model using `tensorflow/lite/tools/visualize.py`.

Most of the parameters are quantized to INT8, which is expected. I am confused about two things regarding the following tensors: `transformer_layer_0/BroadcastTo`, `transformer_layer_0/BroadcastTo1`, `transformer_layer_0/cached_multi_head_attention/ExpandDims`, (... for each "transformer_layer").

My first question is: What does a broadcast/ExpandDims "tensor" store? It seems to me that those are not trainable operations (e.g. doing broadcasting), so why would the tensors have a huge shape [1, 100, 100] (i.e. 10,000 elements)?

My second question is: Why are those tensors quantized to a higher precision (INT32 vs INT8 like other params)?

I really appreciate any help you can provide.

**Comment by fergushenderson** [comment]
For documentation on the semantics of the BroadcastTo and ExpandDims operations, see the following:

- https://www.tensorflow.org/api_docs/python/tf/broadcast_to

- https://www.tensorflow.org/api_docs/python/tf/expand_dims

**Comment by i3abghany** [comment]
@fergushenderson Thank you. I already know the operations, but I am asking why they have trainable parameters and why they are quantized to a higher bit width (int32 instead of int8).
