### ISSUE TITLE
Cannot build on a non-internet connected machine

### ISSUE THREAD

**Issue by skelso068** [tensorflow/tensorflow#7849]
I'm trying to build tensorflow on a machine that has no internet connection.  I've downloaded the
latest bazel (.0.4.4)  and installed and then run the configure script.  I downloaded the git repo with
`git clone --recurse-submodues https://github.com/tensorflow/tensorflow`
The configure then fails with:

This then fails with:
INFO: Unknown host: bazel-mirror.storage.googleapis.com

`ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'closure/defs.bzl': no such package '@io_bazel_rules_closure//closure': Error downloading [http://bazel-mirror.storage.googleapis.com/github.com/bazelbuild/rules_closure/archive/5ca1dab6df9ad02050f7ba4e816407f88690cf7d.tar.gz, https://github.com/bazelbuild/rules_closure/archive/5ca1dab6df9ad02050f7ba4e816407f88690cf7d.tar.gz] to /tmp/steven/.cache/bazel/_bazel_kelso/03aa5bcd96ce8a24592d7d0f1cdaf43b/external/io_bazel_rules_closure/5ca1dab6df9ad02050f7ba4e816407f88690cf7d.tar.gz: All mirrors are down: [Unknown host: bazel-mirror.storage.googleapis.com, Unknown host: github.com].`

This is to be expected as the machine is on a private network.

However, I can manually install tarbalss of packages etc on this box, but I can't work out where they should be installed within the source tree.

Is this possible, or can tensorflow only be built with an active connection to the internet?

Many thanks,
S.

**Comment by martinwicke** [comment]
You can build this locally, but you will have to replace all http_archive, git_archive, etc. in workspace.bzl with corresponding local_archive definitions, pointing to where you downloaded the files to.

You may want to disable tensorboard, otherwise you'll be downloading a lot of small things.

**Comment by GekTo** [comment]
@martinwicke How to disable tensorboard? I am also trying to build offline, but there is too much small git repositories to download.

**Comment by martinwicke** [comment]
You can simply take the dependency on anything tensorboard out of the
build_pip_package target. That should enable you to remove all the
tensorboard dependencies from the workspace.
