### ISSUE TITLE
OOM error when using dropout

### ISSUE THREAD

**Issue by alexatknit** [tensorflow/tensorflow#785]
I thought I might have been going crazy so I only got around to posting this just now. I've got a GPU that can handle a batch size of 160 on my network, but I run it at 128. Thats just to show that I've got about 20% space left on my GPU ram when the network starts training. If I am using dropout, after about 100,000 iterations i get an OOM error.

```
tensorflow.python.framework.errors.ResourceExhaustedError: OOM when allocating tensor with shapedim { size: 128 } dim { size: 40 } dim { size: 40 } dim { size: 64 }
         [[Node: range_1/_1993 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_25333_range_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

Is it possible that there could be a memory leak somewhere?

**Comment by wchan** [comment]
TensorFlow doesn't do dropout inplace to my understanding, so in the worse case scenario, it can use double the memory (assuming you place dropout everywhere in your graph).

**Comment by vrv** [comment]
I feel like a memory leak would likely occur much earlier than 100,000 iterations -- the logs should produce a dump of the OOM information, which could help quickly identify whether there's an obvious memory leak.

Most likely it's just that you're already operating pretty close to the memory capacity of the device and that the order of node execution caused the system to allocate memory in a suboptimal order.

As mentioned on the [roadmap](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/resources/roadmap.md), we're working on improving the memory consumption and reporting, so stay tuned.

**Comment by girving** [comment]
I don't think there's enough information to diagnose here.  Feel free to reopen if more details emerge.
