### ISSUE TITLE
tf.variable_scope argument with some keywords makes TensorBoard work incorrectly

### ISSUE THREAD

**Issue by potterhsu** [tensorflow/tensorflow#7850]
**Problem:**
Step 1:
`with tf.variable_scope('length'):`

Step2:
Run Tensorboard

Step3:
Switch to Graphs tab, but no graph will show.

**Comment by poxvoculi** [comment]
Please include all the information requested in the issues template.  For a bug report, a minimal complete reproducible example is very helpful.
