### ISSUE TITLE
OOM when running `tf.raw_ops.DenseBincount`

### ISSUE THREAD

**Issue by LongZE666** [tensorflow/tensorflow#78508]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf2.17.0 tf2.16.1

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Python version

3.11

### Current behavior?

All memory will be used up when running the following code

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1-me1CkT6-kEV9vhCsFRbygkVRNApaSM3?usp=sharing
```

### Relevant log output

```shell
Timestamp,Level,Message
"Oct 22, 2024, 7:05:36 PM",WARNING,WARNING:root:kernel 82160fbc-3b27-42da-ad82-176fab1b542f restarted
"Oct 22, 2024, 7:05:36 PM",INFO,"KernelRestarter: restarting kernel (1/5), keep random ports"
"Oct 22, 2024, 7:05:15 PM",WARNING,2024-10-22 11:05:15.583047: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 10007999174112 exceeds 10% of free system memory.
"Oct 22, 2024, 7:05:12 PM",WARNING,2024-10-22 11:05:12.027196: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
```

**Comment by Karan-Nagure** [comment]
Hey, I have run the colab notebook. I came up with the solution that we can reduce the size value. This value should be near about 1000 so it could be managable.

I like to fix the bug.

**Comment by tilakrayal** [comment]
@LongZE666,
I request you to take a look at this https://github.com/tensorflow/tensorflow/issues/65634 where a similar issue has been proposed and it is still open. Also I request to follow the similar issue which has been proposed to have the updates on the similar issue. Thank you!

**Comment by LongZE666** [comment]
@tilakrayal Thank you very much for your reply, I will take a look
