### ISSUE TITLE
Retraining the inception model to remove objects

### ISSUE THREAD

**Issue by islamoc** [tensorflow/tensorflow#7851]
Hello I have been trying for a while now to find an answer to this question
is there is anyway to retrain the inception model in a way that I remove objects from it (without doing the training from the scratch) and to be possible to integrate in the android demo

**Comment by Carmezim** [comment]
This question is better suited for StackOverflow as it's not a TF bug itself. They also monitor there under TensorFlow tag and it would get a wider exposure.
