### ISSUE TITLE
TypeError: concat() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by tranvanhoa533** [tensorflow/tensorflow#7853]
Traceback (most recent call last):
  File "train_image_classifier.py", line 585, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 482, in main
    clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
  File "/home/cloud/hoa/workspace/tensorflows/models/slim/deployment/model_deploy.py", line 195, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "train_image_classifier.py", line 466, in clone_fn
    logits, end_points = network_fn(images)
  File "/home/cloud/hoa/workspace/tensorflows/models/slim/nets/nets_factory.py", line 105, in network_fn
    return func(images, num_classes, is_training=is_training)
  File "/home/cloud/hoa/workspace/tensorflows/models/slim/nets/inception_resnet_v2.py", line 169, in inception_resnet_v2
    tower_conv2_2, tower_pool_1])
TypeError: concat() got an unexpected keyword argument 'axis'

When i run restnet or inception_resnet of slim model, this error was raised. Can you hep me?
Thanks.

**Comment by kchen92** [comment]
I believe these types of problems should not be posted here - ask them in StackOverflow instead. Also, you need to provide more information about your system. My guess is that you're using an older version of TensorFlow.

**Comment by tranvanhoa533** [comment]
Thank for your support. T tried on version r0.11 and r0.12. Both version raised this error

**Comment by kchen92** [comment]
Use version 1.0. They changed `tf.concat` in the newer version. The current `tf.concat` was previously called `tf.concat_v2` in the older versions if I remember correctly.

**Comment by tranvanhoa533** [comment]
Thanks you so much. I solved this problem by the way remove 'axis' and 'values' word

**Comment by sidh104** [comment]
removing the 'axis' and 'values' word from where??? @tranvanhoa533 

facing the same error in another project
https://github.com/buriburisuri/speech-to-text-wavenet/issues/48

**Comment by tranvanhoa533** [comment]
I saw this instruction : https://www.tensorflow.org/api_docs/python/tf/concat

**Comment by sumunthra** [comment]
Not downgrade, we need to upgrade the system. with keras = 2.1.5 and Tensor Flow = 1.6.0 with latest anaconda version, the softmax issue is resolved.

**Comment by ATSEGYPT** [comment]
Correct @sumunthra , solved after upgrading TF: '1.7.0', while Keras was: '2.1.5'
Thanks 4 your efforts.
