### ISSUE TITLE
Layer for 3D convolution transpose

### ISSUE THREAD

**Issue by kchen92** [tensorflow/tensorflow#7855]
I am wondering if someone could add a conv3d_transpose layer, similar to `tf.layers.conv2d_transpose`. A `tf.nn.conv3d_transpose` op already exists. Thanks!

**Comment by kchen92** [comment]
Bump

**Comment by stefdoerr** [comment]
I would also be very interested in that

**Comment by Warvito** [comment]
Any update on when this might be available?

**Comment by mdfirman** [comment]
This seems to have now been implemented as `tf.nn.conv3d_transpose`:

https://www.tensorflow.org/api_docs/python/tf/nn/conv3d_transpose
