### ISSUE TITLE
[Windows] tensorboard - needs to be started from same drive as logdir

### ISSUE THREAD

**Issue by enpasos** [tensorflow/tensorflow#7856]
OS: Windows 10 (64 bit)
TensorFlow Version: 1.0.0
CUDA: 8.0
GPU: yes

Problem: 
**C**:>tensorboard --logdir=**E**:\tmp\tensorflow\mnist\logs
=> tensorboard starts without loading data (not working and difficult to detect reason)

**E**:>tensorboard --logdir=**E**:\tmp\tensorflow\mnist\logs
=> tensorboard starts with loading data (works perfectly)

**Comment by mikehenninger** [comment]
ditto, win7 64 tensorflow v1.0.0 no gpu.

as implied by @enpasos, there are no error messages in console or web

**Comment by mrry** [comment]
Unfortunately TensorBoard [uses a colon](https://github.com/tensorflow/tensorflow/blob/27a98083a6c16f263d668271889863596efbeb84/tensorflow/tensorboard/backend/application.py#L581) as the separator between the optional "run name" and the path in the `--logdir` flag. That means that `--logdir=E:\tmp\tensorflow\mnist\logs` is interpreted as a run named `E` with path `\tmp\tensorflow\mnist\logs`, which explains why it's sensitive to the current working directory.

As a quick workaround, you could avoid this problem by always specifying an explicit run name as part of the `--logdir` flag, e.g.:

```
tensorboard --logdir=training:E:\tmp\tensorflow\mnist\logs
```

(Reassigning to @dandelionmane, who shows up on the blame for the relevant code.)

**Comment by dandelionmane** [comment]
Migrated this to tensorflow/tensorboard.

**Comment by rupeshs** [comment]
@mrry 
yep ,that worked (Windows 7,64bit )
tensorboard --logdir=training:E:\tmp\tensorflow\mnist\logs

**Comment by vijaysaimutyala** [comment]
@enpasos Works on Windows 10, 64-bit with Python 3.5. Point to be noted, you should be in the drive only and not even inside the log folder.

Works only when inside D:\> not when in the complete log path.

Only issue I had was to I had to execute it with python instead using tensorboard directly.
python -m tensorboard.main --logdir="D:/JupyterNotebooks/MultivariateTimeSeries/logs/"

**Comment by pouyaesm** [comment]
In windows 7, 64bit (cygwin), I resolved the problem using double-quotes:
--logdir="E:\tmp\tensorflow\mnist\logs"

**Comment by Billy1900** [comment]
Windows 10, Pytorch 1.4.0 GPU, 
I tried the method above mentioned, but did not work. 
Is there any other way to solve it?

**Comment by JinLuckyboy** [comment]
`cd {logdir}
tensorboard --logdir ./`
It works.

**Comment by paweller** [comment]
> I resolved the problem using double-quotes:
> --logdir="E:\tmp\tensorflow\mnist\logs"
> 
> Windows 7, 64bit, cygwin, python 3

Worked perfectly for me.
- Windows 10
- Intel Core i9-7920X
- 2x NVIDIA GeForce RTX 2080 Ti
- TensorFlow 2.4.1
