### ISSUE TITLE
How to use a GPU with TFlite in Python with ubuntu and Cuda

### ISSUE THREAD

**Issue by KarthigaNattarasan** [tensorflow/tensorflow#78591]
Hi, 
I have trained TensorFlow model and quantized it to float 16, saved the file as .tflite format. Tested both TensorFlow and tflite model with CPU it's working. Now want to use GPU for  tflite model with ubuntu (20.4), and follow the same steps provided in the GitHub link git https://github.com/tensorflow/tensorflow.git, for installing gpu_delegate.so file by using below command

**command: bazel build -c opt tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so**

Cuda Version | 11.4.0, Driver Version | 470.256.02, TensorFlow Version | 2.10.0, Python Version|3.8.0, Bazel Version | 7.4.0

GPU delegate is available for ubuntu to test quantized tflite model?

**Comment by Venkat6871** [comment]
Hi **@KarthigaNattarasan** ,
Thank you for raising your concern here. Yes, the GPU delegate is available for Ubuntu to test quantized TFLite models. However, you need to confirm that all the versions are compatible with TensorFlow 2.10.0. It seems you are using Bazel version 7.4.0, which is not compatible with TensorFlow 2.10.0. For TensorFlow 2.10.0, it is better to use Bazel 5.x to avoid build issues and achieve better results. I am providing the documentation for your reference. Please review it for compatibility versions.
Thank you!

**Comment by andrenatal** [comment]
@Venkat6871 but this would work with cuda, correct?

**Comment by KarthigaNattarasan** [comment]
Hi @Venkat6871, 
please share the appropriate documents for reference

**Comment by KarthigaNattarasan** [comment]
Hi @Venkat6871,
Thanks for the reply, tried with Bazel Version | 5.4.0, but still not using GPU.

Error Info:
'''GPU is available and configured for use
Evaluating float16 quantized model...
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.'''

While loading tflite model, it shows GPU is available but it's not utilizing GPU for model inference.

**Comment by gaikwadrahul8** [comment]
Hi, @KarthigaNattarasan 

I apologize for the delayed response, I see you're not using the latest version of TensorFlow, if possible could you please try with below Tested build configurations and see is it working as expected or not ?

Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow-2.18.0 | 3.9-3.12 | Clang 17.0.6 | Bazel 6.5.0 | 9.3 | 12.5

If issue still persists could you please help us with your minimal code along with `libtensorflowlite_gpu_delegate.so` and model file (if possible) to reproduce the same behavior from our end to investigate this issue further ?

Thank you for your cooperation and patience.

**Comment by MariaLuize** [comment]
Are there any updates on this matter?

I am also facing the same issue...
