### ISSUE TITLE
Error while Installing !pip install -q tflite-model-maker-nightly !pip install -q tflite-support-nightly

### ISSUE THREAD

**Issue by mbilalyaq** [tensorflow/tensorflow#78596]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

nighty

### Custom code

Yes

### Current behavior?

Train a custom object detection model using your data
When I try to install tf model maker I keep getting error related to version but no idea how to handle it.
!pip install -q tflite-model-maker-nightly
!pip install -q tflite-support-nightly
i even tried this but no luck: 
!pip install -q tflite-model-maker
!pip install -q tflite-support
Is there updated or working model of the Collab. 
Your help is truly appreciated.
Thank you in advance.. 

### Standalone code to reproduce the issue

```shell
!pip install -q tflite-model-maker-nightly
!pip install -q tflite-support-nightly
```

### Relevant log output

```shell
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.2/87.2 kB 2.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.1/41.1 kB 1.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.9/37.9 MB 14.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
WARNING: Ignoring version 0.3.1.dev202105110329 of tflite-model-maker-nightly since it has invalid metadata:
Requested tflite-model-maker-nightly from https://files.pythonhosted.org/packages/12/03/d0a828aebab37a35a9ff6fe3944ba61330311bc6b07756ff58c3df03dcab/tflite_model_maker_nightly-0.3.1.dev202105110329-py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    absl-py (<0.11>=0.10.0)
            ~~~~~~^
Please use pip<24.1 if you need to use this version.
WARNING: Ignoring version 0.3.1.dev202105102248 of tflite-model-maker-nightly since it has invalid metadata:
Requested tflite-model-maker-nightly from https://files.pythonhosted.org/packages/80/a7/4c2001ef8c1f96d272ab1f66204c5ccea86b35eb12824d6b4276d838e0f4/tflite_model_maker_nightly-0.3.1.dev202105102248-py3-none-any.whl has invalid metadata: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    absl-py (<0.11>=0.10.0)
            ~~~~~~^
```

**Comment by gaikwadrahul8** [comment]
Hi, @mbilalyaq 

Thank you for bringing this issue to our attention, I'm able to replicate the same behavior from my end here is [gist-file](https://colab.sandbox.google.com/gist/gaikwadrahul8/66cef09334aad13c3004a8fca7f2040f/tflite-issue-78596.ipynb) for reference so at the moment I would suggest you to please go with [MediaPipe Model Maker](https://ai.google.dev/edge/mediapipe/solutions/model_maker) by following this [example](https://ai.google.dev/edge/mediapipe/solutions/customization/image_classifier) while our relevant team fix this issue and once I got any update from relevant team will update you here

Thank you for your cooperation and patience.
