### ISSUE TITLE
Error using TF in Python

### ISSUE THREAD

**Issue by melzoghbi** [tensorflow/tensorflow#7859]
I have Python 3.5.2 and Anaconda 4.1.1 (64bit) and when i tried installing TF i got the same error earlier today.
After following uninstall and then reinstall TF commands i was able to start Python app using TF; but now i am getting OpKernel error for unknown op: UpdateFertileSlots.

![image](https://cloud.githubusercontent.com/assets/11993393/23317661/58b8c90e-fa9d-11e6-8b95-975e2075e61d.png)

Any idea how to fix this?

N.B: i did searched online and could not find any answer in SO or any other resource to fix this issue to start using TF.

**Comment by Carmezim** [comment]
Could you please try to:
1. Uninstall TensorFlow
2. Download a [nightly build](http://ci.tensorflow.org/view/Nightly/job/nightly-win/94/) and install it

then follow up if worked for you?

**Comment by melzoghbi** [comment]
This rocked @Carmezim ! thanks a lot.

**Comment by Carmezim** [comment]
Great it worked. If there is no other doubts regarding this issue this can be closed now.

**Comment by atabakd** [comment]
It also worked for me but is there a way to not use nightly builds?

**Comment by Carmezim** [comment]
@atabakd You can actually ignore it as this issue is already fixed at HEAD but wasn't cherry picked for the current release. It will be present in the `1.1r`. To get rid of it is only upgrading to a nightly build.

**Comment by mrnameless123** [comment]
that means the problem can be resolved if I uninstall Tensorflow and install the nightly build version.  btw do you know when version 1.1 is released @Carmezim

**Comment by Carmezim** [comment]
@mrnameless123 it's pre-released https://github.com/tensorflow/tensorflow/releases

**Comment by mrnameless123** [comment]
so I just simply need to wait until it's officially released and use pip --upgrade tensorflow on laptop right?

**Comment by Carmezim** [comment]
@mrnameless123 Correct. The latest nightly build is probably already updated as well. Or you can download the source code and build it.

**Comment by mrnameless123** [comment]
Thank you very much, @Carmezim

**Comment by kristianmandrup** [comment]
I got the same error. I thought the `pip3 --upgrade install` would install 1.1 by now?
I tried: 

```
PS C:\Users\kmand> pip3 install --upgrade tensorflow==1.1.0
Collecting tensorflow==1.1.0-rc2
  Downloading tensorflow-1.1.0rc2-cp35-cp35m-win_amd64.whl
...
tobuf>=3.2.0->tensorflow==1.1.0-rc2)
Installing collected packages: werkzeug, tensorf
  Found existing installation: tensorflow 1.0.1
    Uninstalling tensorflow-1.0.1:
      Successfully uninstalled tensorflow-1.0.1
Successfully installed tensorflow-1.1.0rc2 werkzeug-0.12.1
```

That looks strange!?

**Comment by NirDiamant** [comment]
i have the same error mentioned above, yet, uninstalling TF and installing the build didn't solve the problem. what else can i do? 
thx

**Comment by sreelathasamudrala** [comment]
how to install GPU and CPU of tensorflow on windows 7 for 32 bit .i have  installed cuda toolkit for  win 32   and now i am not able to install GPU and CPU versions for tensor i am getting the following error after creating a virtual environment on windows 7 for tensorflow.


![error](https://cloud.githubusercontent.com/assets/28622848/25944384/bb8d2e36-3660-11e7-8de5-484bd6a0482e.png)

**Comment by ZhouYL0213** [comment]
@sreelathasamudrala  hi, I install CPU-only version of TensorFlow via native pip3 successfully according to the official page [https://www.tensorflow.org/install/install_windows#common_installation_problems](url), however it throws `warning: 43134753` when I execute `sess = tf.Session()`, but it does not affect the following execution. May be you can try it.

**Comment by sreelathasamudrala** [comment]
i did pip3 installation also but still getting the same error.
![pip3](https://cloud.githubusercontent.com/assets/28622848/25945777/cd202572-3665-11e7-9d65-61afd687c2c5.png)
I tried extracting files of tensorflow 1.0.1.rc1 ionto the same folder as i have sent in the attachment but still not getting the  execution .

**Comment by sreelathasamudrala** [comment]
i tried to run tensorflow program without cpu and gpu  installation and i am getting errors.
![tfcode](https://cloud.githubusercontent.com/assets/28622848/25945926/799fad9a-3666-11e7-9b68-6c3ca8bc9a8f.png)

**Comment by sreelathasamudrala** [comment]
please help me guys cant download tf in win 7 using cuda 5.5 release  download of cuda toolkit for win 32

**Comment by chakriv88** [comment]
@sreelathasamudrala Even I got the same error, and it is solved using the solution at this link http://www.stefangordon.com/install-tensorflow-in-anaconda-on-windows/
