### ISSUE TITLE
Internal compiler error using 1.0.0-devel docker image 

### ISSUE THREAD

**Issue by malmaud** [tensorflow/tensorflow#7861]
First pull the Docker image:

```
docker pull tensorflow/tensorflow:1.0.0-devel
docker run -it tensorflow/tensorflow:1.0.0-devel /bin/bash
```

Then in the docker session,

```
cd /tensorflow
bazel build -c opt //tensorflow:libtensorflow_c.so
```

This succeeds for a while, but eventually outputs

```
ERROR: /tensorflow/tensorflow/core/kernels/BUILD:1921:1: C++ compilation of rule '//tensorflow/core/kernels:svd_op' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-canonical-system-headers ... (remaining 114 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
Target //tensorflow:libtensorflow_c.so failed to build
```

This is Docker 1.13.0 on OS X 10.12.3, if that makes a difference.

**Comment by malmaud** [comment]
Actually, this is just the Docker VM running out of memory - increasing the memory from the Docker preferences resolves it.

Maybe it would be worthwhile to add a warning to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/README.md.

**Comment by aselle** [comment]
@caisq, could you add a warning about this to the docker readme?

**Comment by skye** [comment]
Talking to @caisq offline, it sounds like this is an unusual case because docker by default uses all available system memory (@malmaud did you have a default config or something that limited the memory? The commands you provided shouldn't limit the memory AFAIK). I'm gonna close this for now.

**Comment by malmaud** [comment]
If you use docker on Windows or OS X, you have to specify the memory the
Linux virtual machine will use in advance and the default (at least at the
time) is too low for tensorflow.

**Comment by skye** [comment]
Ah, thank you for that clarification! I'll add a note to the README.
