### ISSUE TITLE
RealDiv, VariableV2 ops still in system after uninstalling tf-gpu

### ISSUE THREAD

**Issue by amir-zeldes** [tensorflow/tensorflow#7862]
Hi, thanks for making tf available! I'm having an issue reverting to tf-cpu. I'm using riga/tfdeploy to distribute trained models, which is not compatible with tf-gpu. I installed tf-gpu for an experiment, then reverted to cpu, all using pip install/uninstall. Now I'm getting error messages about unknown ops like RealDiv and VariableV2. 

My question is: How can I remove any trace of tf-gpu from my system and get back to tf-cpu?

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

#7322 and #7285
and:
http://stackoverflow.com/questions/36902457/how-to-uninstall-tensorflow-completely

### Environment info
Operating System: Win 10 64 bit, Python 3.5.3

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
None

If installed from binary pip package, provide:

1. A link to the pip package you installed: 
Just used "pip install tensorflow" (uses tensorflow-1.0.0-cp35-cp35m-win_amd64.whl)
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
1.0.0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

1. pip install tensorflow
2. run a tf.Session() - no ops like RealDiv etc., tfdeploy runs fine.
3. pip install tensorflow-gpu
4. pip uninstall tensorflow-gpu
5. Some trace of these ops remains registered, causing warnings like `OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits` while runninng tf, and also causing frameworks like riga/tfdeploy to crash 

### What other attempted solutions have you tried?
I have tried completely reinstalling Python 3, deleting all site-packages etc. I've installed and uninstalled CUDA. The ops seem to be registered somewhere, leading to different behavior of tf-cpu after installing and uninstalling tf-gpu.

### Logs or other output that would be helpful
The best clue is maybe errors like `unknown op: BestSplits`, which did not occur in tf-cpu before I installed and uninstalled tf-gpu.

Also, tfdeploy gives error messages like `unknown operation: RealDiv`, which did not happen prior to installing and uninstalling tf-gpu.

Any pointers on getting rid of/unregistering these ops is appreciated!

**Comment by yaroslavvb** [comment]
Hi, we are trying to keep this list for bugs/features in TensorFlow itself, could you ask on Stackoverflow instead? Personally I like to use virtual envs, this way I never have to worry about unistalling packages, just make a new env

**Comment by amir-zeldes** [comment]
OK, thanks, I've posted the question here:

http://stackoverflow.com/questions/42473745/remove-all-traces-of-tensorflow-gpu-installation-on-win10

I think there is some trace of the GPU installation left after uninstalling, which might be viewed as a bug. Any pointers to unregistering these ops would be greatly appreciated!

**Comment by yaroslavvb** [comment]
The GPU is handled mostly by CUDA install. The uninstall is handled by whatever Python packager you use (ie, conda uninstall might leave some files, while pip uninstall not). If you think there's a bug in TensorFlow itself, rather than a bug in whatever Python manager you use to manage these packages, I can reopen this issue
