### ISSUE TITLE
 building target with GPU support 

### ISSUE THREAD

**Issue by molyswu** [tensorflow/tensorflow#7871]
bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer

ERROR: /home/molys/.cache/bazel/_bazel_root/f7299e5dc785b6a7f5b5291a103be54f/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
	File "/home/molys/.cache/bazel/_bazel_root/f7299e5dc785b6a7f5b5291a103be54f/external/local_config_cuda/crosstool/BUILD", line 4
		error_gpu_disabled()
	File "/home/molys/.cache/bazel/_bazel_root/f7299e5dc785b6a7f5b5291a103be54f/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
		fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /home/molys/.cache/bazel/_bazel_root/f7299e5dc785b6a7f5b5291a103be54f/external/local_config_cuda/crosstool/BUILD.
INFO: Elapsed time: 0.464s

Thonk you!

**Comment by achbogga** [comment]
Did you run the configure.sh script from the master tf folder? As suggested please select the GPU option to be yes when asked if you need GPU support. Otherwise, please use this command instead: `bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package` to build without GPU support. I suggest closing this issue as this is a question to be asked at stackoverflow.

**Comment by Carmezim** [comment]
Interesting, I just ran into the same issue and as shown in the log I configured for GPU support. 
Earlier I wasn't having this problem, I did have [this](https://github.com/bazelbuild/bazel/issues/2594) though.
```
$ ./configure
Please specify the location of python. [Default is /c/Users/Adriano/AppData/Local/Programs/Python/Python35/python]:
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] Y
XLA JIT support will be enabled for TensorFlow
Found possible Python library paths:
  C:\Users\Adriano\AppData\Local\Programs\Python\Python35
  C:\Users\Adriano\AppData\Local\Programs\Python\Python35\lib\site-packages
Please input the desired Python library path to use.  Default is [C:\Users\Adriano\AppData\Local\Programs\Python\Python35]

Using python library path: C:\Users\Adriano\AppData\Local\Programs\Python\Python35
Junction created for util\python\python_include <<===>> C:\Users\Adriano\AppData\Local\Programs\Python\Python35\include
Junction created for util\python\python_lib <<===>> C:\Users\Adriano\AppData\Local\Programs\Python\Python35
Junction created for third_party\py\numpy\numpy_include <<===>> C:\Users\Adriano\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\core\include
Do you wish to build TensorFlow with CUDA support? [y/N] Y
CUDA support will be enabled for TensorFlow
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0]:
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5.1
Please specify the location where cuDNN 5.1 library is installed. Refer to README.md for more details. [Default is C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0]:
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 5.0
INFO: All external dependencies fetched successfully.
Configuration finished

Adriano@Adriano MSYS /c/Users/Adriano/Documents/tensorflow
$ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
ERROR: C:/tools/msys64/tmp/_bazel_Adriano/t5f2Q_w8/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
        File "C:/tools/msys64/tmp/_bazel_Adriano/t5f2Q_w8/external/local_config_cuda/crosstool/BUILD", line 4
                error_gpu_disabled()
        File "C:/tools/msys64/tmp/_bazel_Adriano/t5f2Q_w8/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
                fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by C:/tools/msys64/tmp/_bazel_Adriano/t5f2Q_w8/external/local_config_cuda/crosstool/BUILD.
INFO: Elapsed time: 1.494s
```
cc @gunan

**Comment by gunan** [comment]
@molyswu All seems to be OK on our end.
Please follow the guide on installing from sources again:
https://www.tensorflow.org/install/install_sources

If you still run into a problem, please use the issue template to file a new issue to provide more information for us.
We will need more debugging information that is required by the template if we are to help.
