### ISSUE TITLE
`tf.io.encode_png` can cause a crash

### ISSUE THREAD

**Issue by cybersupersoap** [tensorflow/tensorflow#78735]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

2.19.0-dev20241023

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 20.04.3 LTS

### Mobile device

Linux Ubuntu 20.04.3 LTS

### Python version

3.10.14

### Current behavior?

I have confirmed that above code would crash on `tf-nightly 22.19.0-dev20241023` (nightly-build)

Please find the [gist](https://colab.research.google.com/drive/1A2ONnR2DN5-gx6_H0byFy8jk3ZmgwiUn?usp=sharing) to reproduce the issue.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
import tensorflow
import numpy
    
image_tensor = tf.saturate_cast(tf.random.uniform([0, 28, 3], minval=0, maxval=256, dtype=tf.int64), dtype=tf.uint8)
image = tf.identity(image_tensor)
compression = -1
name = None
out = tf.io.encode_png(image=image,compression=compression,name=name,)
```

### Relevant log output

```shell
2024-10-25 05:46:33.066290: F tensorflow/core/lib/png/png_io.cc:350] 'image' Must be non NULL
Aborted (core dumped)
```

**Comment by Venkat6871** [comment]
Hi **@cybersupersoap** ,
Apologies for the delay. Thank you for reporting this issue. I suggest taking a look at issue [#76726](https://github.com/tensorflow/tensorflow/issues/76726), where a similar issue has been proposed and is still open. Following this related issue may also help you stay updated on potential solutions.
I tried running your code on Colab using the TensorFlow nightly version and encountered the same issue. I have provided an alternative solution that I hope will be helpful. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/125675589e3416610def4b0c67e37705/78735_tf-nightly-v.ipynb) here for your reference.
Thank you!
