### ISSUE TITLE
The installing instructions for windows anaconda seems wrong

### ISSUE THREAD

**Issue by strongrex2001** [tensorflow/tensorflow#7873]
The URL in the command line is http://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.0-cp35-cp35m-win_x86_64.whl
I can't install from the URL
however, I replaced x84_64 with amd64 and it works

**Comment by tomwanzek** [comment]
I experienced the same issue and opted for the same "fallback" solution for now.

That being said, the resulting install still has the issue discussed under #7500, which as of now seems to be only addressed in the nightly build.

**Comment by mrry** [comment]
@yifeif We've seen a few issues with confusion between `x86_64` and `amd64` in the PIP URLs. Do you happen to know what the definitive answer is? Thanks!

**Comment by yifeif** [comment]
The pip binaries have always had amd64 as the platform tag. 
This seems to be a mistake in the URLs on the website, which we will update soon. Sorry for the confusion.

**Comment by gunan** [comment]
website is updated with the correct urls. Closing issue.
