### ISSUE TITLE
strip_unused tool can't read all graph protobufs...

### ISSUE THREAD

**Issue by tomasreimers** [tensorflow/tensorflow#7874]
Hi, 

When trying to strip unused nodes from my graph, the tool fails in cases where the protobuf encodes a continuation byte, but fails to continue. For example, running 

`./bazel-bin/tensorflow/python/tools/strip_unused --input_graph=tensorflow/contrib/some/path/mnist.pb --output_graph=tensorflow/contrib/some/path/mnist.inference.pb --input_node_names=Reshape,dropout --output_node_names=prediction_onehot`

on the attached graph causes a: 

`UnicodeDecodeError: 'utf8' codec can't decode byte 0xc5 in position 45: invalid continuation byte`

It seems decoding the file as a UTF8 string is causing issues...

[mnist.pb.zip](https://github.com/tensorflow/tensorflow/files/800990/mnist.pb.zip)

**Comment by inflation** [comment]
Are you using Python 3? It seems to be a `str` and `bytes` issue.

**Comment by tomasreimers** [comment]
I am not! 2.7.x

**Comment by chadnickbok** [comment]
I'm having exactly the same issue running `freeze_graph` - the files aren't loading due to utf-8 errors.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by lemaxm** [comment]
I ran into a similar issue. For binary graph definitions you need to set the `--input_binary` argument to `True`. It defaults to `False` what causes the script to use a different parser.
