### ISSUE TITLE
Native Windows libraries for Java?

### ISSUE THREAD

**Issue by alistairstead3408** [tensorflow/tensorflow#7877]
Looking at the java directory, the README only provides links for MacOS and Linux. Do we have to build from source for Windows or are those libraries provided somewhere else? Am I missing something?

**Comment by asimshankar** [comment]
Yes, for now you need to build from source, we haven't gotten around to packaging or testing on Windows yet.

**Comment by cretz** [comment]
@poxvoculi or @asimshankar - Is there an issue that can be watched to track the progress?

**Comment by asimshankar** [comment]
No, there isn't. Reopening this one for tracking.
