### ISSUE TITLE
Errory in summary writer tensorflow v1.0

### ISSUE THREAD

**Issue by elfadly** [tensorflow/tensorflow#7879]
I have the below error when trying to run my code

**Error**
Traceback (most recent call last):
  File "fer2013_train.py", line 102, in <module>
    tf.app.run()
  File "C:\Program Files\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "fer2013_train.py", line 98, in main
    train()
  File "fer2013_train.py", line 64, in train
    summary_writer = tf.train.SummaryWriter(FLAGS.train_dir,
AttributeError: module 'tensorflow.python.training.training' has no attribute 'SummaryWriter'

**Code:**

    # Build the summary operation based on the TF collection of Summaries.
    summary_op = tf.summary.merge_all()

    # Build an initialization operation to run below.
    init = tf.global_variables_initializer()

    # Start running operations on the Graph.
    sess = tf.Session(config=tf.ConfigProto(
        log_device_placement=FLAGS.log_device_placement))
    sess.run(init)

    # Start the queue runners.
    tf.train.start_queue_runners(sess=sess)

    summary_writer = tf.train.SummaryWriter(FLAGS.train_dir,
                                            graph_def=sess.graph_def)

**tensorflow version**
>>> tf.__version__
'1.0.0'

**Comment by cmanny** [comment]
This is because SummaryWriter is no longer exported into the train module, as it was deprecated, but now FileWriter uses the same interface (see [here](https://github.com/tensorflow/tensorflow/blob/34df7ee6f5a8f931d2433dc7e6e739bc880a35ea/tensorflow/python/training/summary_io.py#L31))

Use tf.summary.FileWriter instead.

**Comment by elfadly** [comment]
Thanks it works :)

**Comment by PeterChen-xiaofeng** [comment]
Now it just says 'module 'tensorflow.train' has no attribute 'summary''……
What can I do?

**Comment by PeterChen-xiaofeng** [comment]
> Now it just says 'module 'tensorflow.train' has no attribute 'summary''……
> What can I do?

Problem has been solved.Thanks.

**Comment by azraar** [comment]
> Now it just says 'module 'tensorflow.train' has no attribute 'summary''……
> What can I do?

some problem how can i solve it 
AttributeError: 'MY_Model' object has no attribute 'summary'
