### ISSUE TITLE
Unable to build TensorFlow 2.18 with GCC

### ISSUE THREAD

**Issue by adamjstewart** [tensorflow/tensorflow#78846]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.18.0

### Custom code

No

### OS platform and distribution

Linux Ubuntu 24.04

### Python version

3.11.9

### Bazel version

6.5.0

### GCC/compiler version

GCC 13.2.0

### CUDA/cuDNN version

CUDA 12.6.2, cuDNN 8.9.7.29

### Current behavior?

When compiling TF 2.18 with GCC, the build passes many CUDA flags to the compiler:
```
ERROR: /tmp/spack6u_rodz5/1b99beed63669ad175919c6b77052d81/external/local_xla/xla/service/gpu/BUILD:2647:13: Compiling xla/service/gpu/make_batch_pointers.cu.cc failed: (Exit 1): gcc failed: error executing command (from target @local_xla//xla/service/gpu:make_batch_pointers_kernel)
...
gcc: error: unrecognized command-line option '--cuda-gpu-arch=sm_35'
gcc: error: unrecognized command-line option '--cuda-include-ptx=sm_70'
gcc: error: unrecognized command-line option '--cuda-gpu-arch=sm_70'
gcc: error: unrecognized command-line option '-Xcuda-fatbinary=--compress-all'
gcc: error: unrecognized command-line option '-nvcc_options=expt-relaxed-constexpr'
```
I would expect these flags to be passed to nvcc instead of GCC.

P.S. Yes, I know that Clang 17.0.6 is the only supported compiler, but I am nevertheless trying to build with GCC. I'm hoping another community member can help me figure out how to build with GCC.

I experienced a similar issue when building JAX with GCC: https://github.com/jax-ml/jax/issues/23689

### Standalone code to reproduce the issue

I'm using the following build script: https://github.com/spack/spack/pull/47211

Then I run:
```console
> spack install py-tensorflow
```

### Relevant log output

* [build log](https://github.com/user-attachments/files/17533526/spack-build-out.txt)
* [build env](https://github.com/user-attachments/files/17533525/spack-build-env-mods.txt)

**Comment by tilakrayal** [comment]
cc @learning-to-play

**Comment by learning-to-play** [comment]
TensorFlow supports building with Clang.

**Comment by learning-to-play** [comment]
Changed to closed won't fix.
Please let me know if you prefer me to reopen this ticket, as other users may have comments about the issues for GCC build.

**Comment by adamjstewart** [comment]
I think you're going to find that it is difficult to simply "not support" the world's most common family of compilers. It would be more realistic to support a good default compiler family on each OS:

* Linux: GCC
* macOS: Xcode/Apple Clang
* Windows: Visual Studio

Even if you close this issue, other people will open new issues to report the same problem. If Google is not willing or able to support GCC, the rest of the community will.

All of this is to say that Google doesn't have to support anything they don't want to, but I would greatly appreciate it if standard compilers like GCC were still supported by someone (either Google or the greater TF community).

**Comment by adamjstewart** [comment]
FYI, we managed to solve the GCC build issue. In addition to:
```bash
TF_NEED_CUDA=1
TF_CUDA_COMPUTE_CAPABILITIES=...
```
we also needed to set:
```bash
CUDA_NVCC=1
HERMETIC_CUDA_COMPUTE_CAPABILITIES=...
```
The Spack TF recipe now correctly builds on Linux x86_64 and aarch64 for GCC and Clang.
