### ISSUE TITLE
How could I get the weights from the checkpoint file saved using tensorflow-slim?

### ISSUE THREAD

**Issue by fengsky401** [tensorflow/tensorflow#7886]
I know that if I knew the variable names or graph I could restore the graph or the variables in the checkpoint files.
But if I don't know the actual variable names  like w1,w2,b1,b2...in conv1,conv2,.... 
How could I get the variable values?
For example, I get the checkpoint file of alexnet in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/nets/alexnet.py
How could I get the variable values in these checkpoint files?

**Comment by inflation** [comment]
If you use the new version of checkpoints, you can import the metagraph with variable collections. Check out `tf.train.import_meta_graph` and `tf.get_collection`.

**Comment by fengsky401** [comment]
@inflation Actually I tried these before, the code is as below
```
import tensorflow as tf
sess = tf.Session()

new_saver = tf.train.import_meta_graph('/home/scw4750/Liuhongkun/tfrecord/zooscan/Alexnet/Modal/model20170226041552612/mymodel.meta')
#print( tf.train.latest_checkpoint('./'))
what=new_saver.restore(sess, '/home/scw4750/Liuhongkun/tfrecord/zooscan/Alexnet/Modal/model20170226041552612/mymodel')
#print(what)
all_vars = tf.get_collection('alexnet_v2')
print(all_vars)
for v in all_vars:
    v_ = sess.run(v)
    print(v_)
```
The function tf.get_collection() at least has the key for the collection, I tried the scope name defined in alexnet.py , print(all_vars) shows nothing but [ ]. So I don't know how could I give the key.

tf.get_collection(key, scope=None) {#get_collection}

Wrapper for Graph.get_collection() using the default graph.

See Graph.get_collection() for more details.
Args:

    key: The key for the collection. For example, the GraphKeys class contains many standard names for collections.
    scope: (Optional.) If supplied, the resulting list is filtered to include only items whose name attribute matches using re.match. Items without a name attribute are never returned if a scope is supplied and the choice or re.match means that a scope without special tokens filters by prefix.

Returns:

The list of values in the collection with the given name, or an empty list if no value has been added to that collection. The list contains the values in the order under which they were collected.

**Comment by inflation** [comment]
Well, `variable_scope` is not quite the same with `collection`. You can see the default collections from `tf.GraphKeys`. Any other collections are defined manually.

**Comment by fengsky401** [comment]
@inflation It worked, I use 
`all_vars = tf.get_collection(ops.GraphKeys.GLOBAL_VARIABLES)`
then I could get the variables.
Thank you!
