### ISSUE TITLE
libtensorflow libraries for >2.15

### ISSUE THREAD

**Issue by MattiasDC** [tensorflow/tensorflow#78869]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.16

### Custom code

Yes

### OS platform and distribution

Windows Linux

### Current behavior?

Is libtensorflow still being built for every version?
According to the documentation [here](https://www.tensorflow.org/install/lang_c) it is, but according to the GCS bucket in that page which links to [the bucket](https://storage.googleapis.com/libtensorflow-nightly), there hasn't been any new builds for two years.

The last official version available is 2.15

### Standalone code to reproduce the issue

```shell
No code involved to reproduce
```

**Comment by gaikwadrahul8** [comment]
Hi, @MattiasDC 
I apologize for the delayed response, Thank you for reporting the issue regarding Nightly libtensorflow C packages availability. I see in this [official documentation](https://github.com/tensorflow/tensorflow?tab=readme-ov-file#official-builds) the status of Nightly Binary Official GCS marked as **Status Temporarily Unavailable** but we do have libtensorflow packages for stable version of TensorFlow available so at the moment I would suggest you to please go with stable libtensorflow C packages which you can download and extract it for more information please refer this [official documentation](https://www.tensorflow.org/install/lang_c)

For future update regarding Nightly libtensorflow C packages availability you can see the status here : https://github.com/tensorflow/tensorflow?tab=readme-ov-file#official-builds

Thank you for your cooperation and patience.

**Comment by gaikwadrahul8** [comment]
Hi, @MattiasDC
Could you please confirm if this issue is resolved for you now, For future update regarding Nightly libtensorflow C packages availability you can see the status here : https://github.com/tensorflow/tensorflow?tab=readme-ov-file#official-builds ? 

Please feel free to close the issue if it is resolved ? Thank you

**Comment by MattiasDC** [comment]
Thanks for all the info!
