### ISSUE TITLE
Anaconda's release is now 3.6 and it breaks the install

### ISSUE THREAD

**Issue by CBrauer** [tensorflow/tensorflow#7887]
I am trying to install tensorflow on windows 10 Enterprise Edition.
I followed the instructions to download Anaconda, but the web-site has been upgraded to Python 3.6. 
I tried to download a new whl from the nightly build but it does not work with the latest Anaconda release.  
I get:

C:\>pip install --upgrade C:\Temp\tensorflow-1.0.0rc2-cp35-cp35m-win_amd64.whl
tensorflow-1.0.0rc2-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.

Any plans to upgrade tensorflow to the latest version of Anaconda Python?

Charles

**Comment by Carmezim** [comment]
It's a work in progress #6999

**Comment by tomwanzek** [comment]
@CBrauer It should be possible to use the latest Anaconda installer. I am using `Anaconda3-4.3.0.1-Windows-x86_64` on a Windows 10 machine.

While it by default uses Python 3.6 as you pointed out, you can simply create a conda environment based on Python 3.5 and then install TensorFlow into it.

The only issue I ran into, is the one already opened #7873.

**Comment by gunan** [comment]
Closing this issue to unify all python 3.6 discussion on #6999
