### ISSUE TITLE
Tensorflow Lite Reduce binary size

### ISSUE THREAD

**Issue by rishik1001** [tensorflow/tensorflow#78894]
This is BUILD File as given in the documentation,
load(
    "//tensorflow/lite:build_def.bzl",
    "tflite_custom_cc_library",
    "tflite_cc_shared_object",
)

tflite_custom_cc_library(
    name = "selectively_built_cc_lib",
    models = [
        ":auto.tflite",
    ],
)

# Shared lib target for convenience, pulls in the core runtime and builtin ops.
# Note: This target is not yet finalized, and the exact set of exported (C/C++)
# APIs is subject to change. The output library name is platform dependent:
#   - Linux/Android: `libtensorflowlite.so`
#   - Mac: `libtensorflowlite.dylib`
#   - Windows: `tensorflowlite.dll`
tflite_cc_shared_object(
    name = "tensorflowlite",
    # Until we have more granular symbol export for the C++ API on Windows,
    # export all symbols.
    features = ["windows_export_all_symbols"],
    linkopts = select({
        "//tensorflow:macos": [
            "-Wl,-exported_symbols_list,$(location //tensorflow/lite:tflite_exported_symbols.lds)",
        ],
        "//tensorflow:windows": [],
        "//conditions:default": [
            "-Wl,-z,defs",
            "-Wl,--version-script,$(location //tensorflow/lite:tflite_version_script.lds)",
        ],
    }),
    per_os_targets = True,
    deps = [
        ":selectively_built_cc_lib",
        "//tensorflow/lite:tflite_exported_symbols.lds",
        "//tensorflow/lite:tflite_version_script.lds",
    ],
)

ERROR: C:/rishik/tensorflow-2.17.0/tmp/BUILD:7:25: gen_selected_ops failed: (Exit -1073741819): generate_op_registrations.exe failed: error executing command (from target //tmp:selectively_built_cc_lib_registration)
  cd /d C:/rishik/bazel4/5lnkvv5w/execroot/org_tensorflow
bazel-out\x64_windows-opt-exec-BB41B15F\bin\tensorflow\lite\tools\generate_op_registrations.exe --namespace= --output_registration=bazel-out/x64_windows-opt/bin/tmp/selectively_built_cc_lib_registration_registration.cc --tflite_path=tensorflow/lite --input_models=tmp/auto.tflite
# Configuration: d8b6abda1087700c56031d915b13c37cfb693d4da0543a50c2b5e6165b4e15e1
# Execution platform: //tensorflow/tools/toolchains/win:x64_windows-clang-cl
Target //tmp:tensorflowlite failed to build
INFO: Elapsed time: 268.072s, Critical Path: 46.35s
INFO: 1278 processes: 489 internal, 789 local.
FAILED: Build did NOT complete successfully

This error is shown, how do I resolve it

**Comment by gaikwadrahul8** [comment]
Hi, @rishik1001 

Thank you for bringing this issue to our attention, if possible could you please help us with complete steps or code snippets with Google colab to replicate the same behavior from our end to investigate this issue further ? 

Thank you for your cooperation and patience.
