### ISSUE TITLE
I can successfully open CUDA library cupti64_80.dll， but it stop on this step and can't forward. what should I do?  what's the problem? help

### ISSUE THREAD

**Issue by XiaoJun134** [tensorflow/tensorflow#7890]
![image](https://cloud.githubusercontent.com/assets/16426261/23336757/11a08ce6-fc14-11e6-82da-97d77e20da5c.png)
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by poxvoculi** [comment]
The issues template above asks for information you haven't provided, such as the OS and CUDA installation.  It's difficult to guess what might be wrong without more information.

**Comment by gunan** [comment]
I will close this issue in favor of other one. This issue has very little information, and your screenshot only shows some benign information messages.
