### ISSUE TITLE
Unable to use Tensorflow on Android Studio

### ISSUE THREAD

**Issue by Anmolk22** [tensorflow/tensorflow#7894]
I have opened the Android part into android studio from examples/contrib/Android and the project opened.
After that I added the pre compiled jar file libandroid_tensorflow_inference_java from the nightly mode added it as module then added module dependency from the project structure .
After that I get error on bazel location. I have also build bazel-0.40 at the following path def bazel_location = 'C:\\Users\\ANMOL\\Downloads\\bazel-0.4.0\\bazel-0.4.0\\output\\bazel.exe' and when I copy this path into Android Studio it doesnt seem to work .
Any Ideas how to make it work
![android studio bazel error](https://cloud.githubusercontent.com/assets/23556208/23337762/f6ce0df8-fc1d-11e6-89e4-291a5625ec23.jpg)

**Comment by andrewharp** [comment]
Bazel doesn't support Android on Windows yet; see #6385 for more details and alternatives.
