### ISSUE TITLE
Build from source v2.18.0 - countless warnings e.g. Do not pass an `input_shape`/`input_dim` argument to a layer.

### ISSUE THREAD

**Issue by LeeABarron** [tensorflow/tensorflow#78955]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

v2.18.0

### Custom code

No

### OS platform and distribution

Linux Ubuntu 24.04

### Python version

13.2

### Bazel version

bazilisk v1.22.1

### GCC/compiler version

gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0

### CUDA/cuDNN version

12.6.1 / 9.4.0

### GPU model and memory

 NVIDIA GeForce RTX 4060 Ti

### Current behavior?

I'm building from source, tag v2.18.0. Compilation succeeds with the **configuration below.** When used I get countless warnings. GPU seems to be used.

I'm running the basic example from the startpage of the web site and get the following output:

2024-10-29 13:56:32.470690: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1730206592.497706   98446 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1730206592.505972   98446 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-29 13:56:32.530518: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE3 SSE4.1 SSE4.2, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/user/source/tf-test/venv/lib/python3.12/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
I0000 00:00:1730206595.503757   98446 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14163 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060 Ti, pci bus id: 0000:01:00.0, compute capability: 8.9
2024-10-29 13:56:36.992391: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.
2024-10-29 13:56:37.185922: W external/local_xla/xla/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.
Epoch 1/5
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1730206598.144274   98498 service.cc:148] XLA service 0x76ccf8002630 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1730206598.144353   98498 service.cc:156]   StreamExecutor device (0): NVIDIA GeForce RTX 4060 Ti, Compute Capability 8.9
2024-10-29 13:56:38.176299: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1730206598.266340   98498 cuda_dnn.cc:529] Loaded cuDNN version 90400
I0000 00:00:1730206600.512484   98498 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.8608 - loss: 0.4798    
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9552 - loss: 0.1478   
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9674 - loss: 0.1076   
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9746 - loss: 0.0843   
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9777 - loss: 0.0713   
2024-10-29 13:56:59.770413: I external/local_xla/xla/stream_executor/cuda/cuda_asm_compiler.cc:397] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_34', 4 bytes spill stores, 4 bytes spill loads

313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9724 - loss: 0.0882

Is my build corrupt or what did I do wrong? I'm very thankful for any hint and help. Thank you!

### Standalone code to reproduce the issue

```shell
Compiling from code (checkout tag v2.18.0):

./configure 
You have bazel 6.5.0 installed.
Please specify the location of python. [Default is /usr/bin/python3]:


Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.12/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the hermetic CUDA version you want to use or leave empty to use the default version. 12.6.1


Please specify the hermetic cuDNN version you want to use or leave empty to use the default version. 9.4.0

Please specify a list of comma-separated CUDA compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus. Each capability can be specified as "x.y" or "compute_xy" to include both virtual and binary GPU code, or as "sm_xy" to only include the binary code.
Please note that each additional compute capability significantly increases your build time and binary size, and that TensorFlow only supports compute capabilities >= 3.5 [Default is: 3.5,7.0]: 8.9


Please specify the local CUDA path you want to use or leave empty to use the default version. /usr/local/cuda-12.6/


Please specify the local CUDNN path you want to use or leave empty to use the default version. /usr/include/


Please specify the local NCCL path you want to use or leave empty to use the default version.


Do you want to use clang as CUDA compiler? [Y/n]: Y
Clang will be used as CUDA compiler.

Please specify clang path that to be used as host compiler. [Default is /usr/lib/llvm-17/bin/clang]:


You have Clang 17.0.6 installed.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]:


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
Not configuring the WORKSPACE for Android builds.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
        --config=mkl            # Build with MKL support.
        --config=mkl_aarch64    # Build with oneDNN and Compute Library for the Arm Architecture (ACL).
        --config=monolithic     # Config for mostly static monolithic build.
        --config=numa           # Build with NUMA support.
        --config=dynamic_kernels        # (Experimental) Build kernels into separate shared objects.
        --config=v1             # Build with TensorFlow 1 API instead of TF 2 API.
Preconfigured Bazel build configs to DISABLE default on features:
        --config=nogcp          # Disable GCP support.
        --config=nonccl         # Disable NVIDIA NCCL support.
Configuration finished

host:~/source/tensorflow$ bazel build //tensorflow/tools/pip_package:wheel --repo_env=WHEEL_NAME=tensorflow --config=cuda --config=cuda_wheel --config=nogcp --config=nonccl
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [cuda_clang, cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Reading 'startup' options from /home/user/source/tensorflow/.bazelrc: --windows_enable_symlinks
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=181
INFO: Reading rc options for 'build' from /home/user/source/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/user/source/tensorflow/.bazelrc:
  'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --features=-force_no_whole_archive --enable_platform_specific_config --defi    ine=with_xla_support=true --config=short_logs --config=v2 --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visib    bility
INFO: Reading rc options for 'build' from /home/user/source/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3/dist-packages --python_path=/usr/bin/python3 --action_env LD_LIBRARY_PATH=/usr/local/cuda-12.6/lib64:/usr/local/cuda-12.6/lib64 --config=cuda_clang --action_env CLANG_CUDA_COMPILER_PATH=/usr/lib/llvm-17/bin/clang --copt=-Wno-gnu-offsetof-extensions --    -config=cuda_clang
INFO: Found applicable config definition build:short_logs in file /home/user/source/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/user/source/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:cuda_clang in file /home/user/source/tensorflow/.bazelrc: --config=cuda --@local_config_cuda//:cuda_compiler=clang --copt=-Qunused-arguments --repo_env=HERMETIC_CUDA_COMPUTE_CAPABILITIES=sm_60,sm_70,sm_80,sm_89,compute_90 --host_linkopt=-fuse-ld=lld --host_linkopt=-lm --linkopt=-fuse-ld=lld --linkopt=-lm        
INFO: Found applicable config definition build:cuda in file /home/user/source/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda --repo_env=HERMETIC_CUDA_VERSION=12.5.1 --repo_env=HERMETIC_CUDNN_VERSION=9.3.0 --@local_config_cuda//cuda:include_cuda_libs=true
INFO: Found applicable config definition build:cuda in file /home/user/source/tensorflow/.tf_configure.bazelrc: --repo_env HERMETIC_CUDA_VERSION=12.6.1 --repo_env HERMETIC_CUDNN_VERSION=9.4.0 --repo_env HERMETIC_CUDA_COMPUTE_CAPABILITIES=8.9 --repo_env LOCAL_CUDA_PATH=/usr/local/cuda-12.6/ --repo_env LOCAL_CUDNN_PATH=/usr/include/
INFO: Found applicable config definition build:cuda_clang in file /home/user/source/tensorflow/.bazelrc: --config=cuda --@local_config_cuda//:cuda_compiler=clang --copt=-Qunused-arguments --repo_env=HERMETIC_CUDA_COMPUTE_CAPABILITIES=sm_60,sm_70,sm_80,sm_89,compute_90 --host_linkopt=-fuse-ld=lld --host_linkopt=-lm --linkopt=-fuse-ld=lld --linkopt=-lm        
INFO: Found applicable config definition build:cuda in file /home/user/source/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda --repo_env=HERMETIC_CUDA_VERSION=12.5.1 --repo_env=HERMETIC_CUDNN_VERSION=9.3.0 --@local_config_cuda//cuda:include_cuda_libs=true
INFO: Found applicable config definition build:cuda in file /home/user/source/tensorflow/.tf_configure.bazelrc: --repo_env HERMETIC_CUDA_VERSION=12.6.1 --repo_env HERMETIC_CUDNN_VERSION=9.4.0 --repo_env HERMETIC_CUDA_COMPUTE_CAPABILITIES=8.9 --repo_env LOCAL_CUDA_PATH=/usr/local/cuda-12.6/ --repo_env LOCAL_CUDNN_PATH=/usr/include/
INFO: Found applicable config definition build:cuda in file /home/user/source/tensorflow/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda --repo_env=HERMETIC_CUDA_VERSION=12.5.1 --repo_env=HERMETIC_CUDNN_VERSION=9.3.0 --@local_config_cuda//cuda:include_cuda_libs=true
INFO: Found applicable config definition build:cuda in file /home/user/source/tensorflow/.tf_configure.bazelrc: --repo_env HERMETIC_CUDA_VERSION=12.6.1 --repo_env HERMETIC_CUDNN_VERSION=9.4.0 --repo_env HERMETIC_CUDA_COMPUTE_CAPABILITIES=8.9 --repo_env LOCAL_CUDA_PATH=/usr/local/cuda-12.6/ --repo_env LOCAL_CUDNN_PATH=/usr/include/
INFO: Found applicable config definition build:cuda_wheel in file /home/user/source/tensorflow/.bazelrc: --@local_config_cuda//cuda:include_cuda_libs=false
INFO: Found applicable config definition build:nogcp in file /home/user/source/tensorflow/.bazelrc: --define=no_gcp_support=true
INFO: Found applicable config definition build:nonccl in file /home/user/source/tensorflow/.bazelrc: --define=no_nccl_support=true
INFO: Found applicable config definition build:linux in file /home/user/source/tensorflow/.bazelrc: --host_copt=-w --copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated --copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes --copt=-Wno-array-bounds --copt=-Wunused-result --copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch --copt    t=-Wno-error=unused-but-set-variable --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxop    pt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/user/source/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: /home/user/.cache/bazel/_bazel_user/60b540d7b9200554d741de3bca139495/external/local_xla/third_party/py/python_repo.bzl:96:14:
HERMETIC_PYTHON_VERSION variable was not set correctly, using default version.
Python 3.12 will be used.
To select Python version, either set HERMETIC_PYTHON_VERSION env variable in
your shell:
  export HERMETIC_PYTHON_VERSION=3.12
OR pass it as an argument to bazel command directly or inside your .bazelrc
file:
  --repo_env=HERMETIC_PYTHON_VERSION=3.12
DEBUG: /home/user/.cache/bazel/_bazel_user/60b540d7b9200554d741de3bca139495/external/local_xla/third_party/py/python_repo.bzl:107:10: Using hermetic Python 3.12                 
WARNING: The following configs were expanded more than once: [cuda_clang, cuda]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
DEBUG: /home/user/.cache/bazel/_bazel_user/60b540d7b9200554d741de3bca139495/external/local_tsl/third_party/nccl/hermetic/nccl_redist_init_repository.bzl:73:10: Downloading and extracting https://files.pythonhosted.org/packages/df/99/12cd266d6233f47d00daf3a72739872bdc10267d0383508b0b9c84a18bb6/nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl       
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/zlib.net/fossils/zlib-1.3.1.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Analyzed target //tensorflow/tools/pip_package:wheel (757 packages loaded, 55850 targets configured).
INFO: Found 1 target...
```

**Comment by Venkat6871** [comment]
Hi **@LeeABarron** ,
Thank you for raising your issue here. I noticed there may be a version compatibility problem. Although everything compiled successfully, any compatibility issues could lead to performance problems. It is best to install compatible versions. I am providing the [documentation](https://www.tensorflow.org/install/source#gpu) here for your reference, please review it and check all compatibility versions. Let us know if the issue persists.

Thank you!

**Comment by LeeABarron** [comment]
Hi @Venkat6871 
Thank you for your response and your time.

I did 2.17 before and dealt with another issue that's why I went to 2.18.
At time of build this table was not updated yet for 2.18 - so I went with the max versions of third_party\xla\third_party\tsl\third_party\gpus\cuda\hermetic\cuda_redist_versions.bzl at the time of the tag v2.18.0
I guess this mean these max versions (12.6.1 and 9.4) are "experimental" or for development only. Did I miss another way to find the max recommended versions from the code, when the table is not updated yet?

I will happily give it a whirl with 2.5.1 and 9.3 and post my results. Thank you very much.

**Comment by LeeABarron** [comment]
Unfortunately exactly the same - build successful (should I post configuration?) but warnings remain:

2024-11-01 19:16:54.296179: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1730485014.331975   26232 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1730485014.342833   26232 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-11-01 19:16:54.382102: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE3 SSE4.1 SSE4.2, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Downloading data from https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz
11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step 
/home/user/source/tf-eval/venv/lib/python3.12/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
I0000 00:00:1730485023.031375   26232 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14242 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060 Ti, pci bus id: 0000:01:00.0, compute capability: 8.9
Epoch 1/5
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1730485027.010202   26313 service.cc:148] XLA service 0x7804e00083c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1730485027.010277   26313 service.cc:156]   StreamExecutor device (0): NVIDIA GeForce RTX 4060 Ti, Compute Capability 8.9
2024-11-01 19:17:07.141875: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1730485027.408144   26313 cuda_dnn.cc:529] Loaded cuDNN version 90300
I0000 00:00:1730485029.842869   26313 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 2ms/step - accuracy: 0.8568 - loss: 0.4844    
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9567 - loss: 0.1485   
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9688 - loss: 0.1038   
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9734 - loss: 0.0850   
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9755 - loss: 0.0749   
2024-11-01 19:17:46.978835: I external/local_xla/xla/stream_executor/cuda/cuda_asm_compiler.cc:397] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_34', 4 bytes spill stores, 4 bytes spill loads

313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 5ms/step - accuracy: 0.9720 - loss: 0.0944

What could I try? Thank you very much.

**Comment by Senantq** [comment]
The warning "To enable the following instructions: SSE3 SSE4.1 SSE4.2, in other operations, rebuild TensorFlow with the appropriate compiler flags" is CPU-related and has nothing to do with the CUDA and CUDNN versions. Using -march=native as a CPU flag when you use the configure.py would do the job. For the recommended CUDA and CUDNN versions, there are in the file .bazelrc of the repo, search for the line "build:cuda_clang_official --repo_env=HERMETIC_CUDA_VERSION" and "build:cuda_clang_official --repo_env=HERMETIC_CUDNN_VERSION" for your rc. The other warnings are just there and don't seem to impact training

**Comment by Venkat6871** [comment]
Hi **@LeeABarron** ,
Apologies for the delay. For the similar issue one more issue was raised and still it is in open state.  please follow them for further updates. I am providing the [link](https://github.com/tensorflow/tensorflow/issues/62075) to that issue here for your reference.
Thank you!
