### ISSUE TITLE
tf.keras.Concatenate fails with 5 dimensional tensors

### ISSUE THREAD

**Issue by pboutinaud** [tensorflow/tensorflow#78957]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.18

### Custom code

No

### Python version

3.11

### CUDA/cuDNN version

12.5.1 / 9

### GPU model and memory

A100 80G

### Current behavior?

When trying to use a keras Concatenate layer with two 5 dimensional tensors with all but the last dimension to 1, there is an "IndexError". In the provided example the result should be a tensor of shape (1, 1, 1, 1, 10). It works ok with <=4 dimensional tensors or when any of the first four dimension is not one.

### Standalone code to reproduce the issue

```shell
import numpy as np
import tensorflow as tf
tf.keras.layers.Concatenate()([
    np.arange(5).reshape(1, 1, 1, 1, 5),
    np.arange(5).reshape(1, 1, 1, 1, 5)
])
```

### Relevant log output

```shell
import numpy as np
      3 import tensorflow as tf
----> 4 tf.keras.layers.Concatenate()([
      5     np.arange(5).reshape(1, 1, 1, 1, 5),
      6     np.arange(5).reshape(1, 1, 1, 1, 5)
      7 ])

File ~/.conda/pa311tf/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py:122, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    119     filtered_tb = _process_traceback_frames(e.__traceback__)
    120     # To get the full stack trace, call:
    121     # `keras.config.disable_traceback_filtering()`
--> 122     raise e.with_traceback(filtered_tb) from None
    123 finally:
    124     del filtered_tb

File ~/.conda/pa311tf/lib/python3.11/site-packages/keras/src/layers/merging/concatenate.py:70, in Concatenate.build(self, input_shape)
     60 for axis, axis_value in enumerate(
     61     reduced_inputs_shapes[i][1:], start=1
     62 ):
   (...)
     67     # but if tensor shapes are not the same when
     68     # calling, an exception will be raised.
     69     if axis != concat_axis and axis_value == 1:
---> 70         del reduced_inputs_shapes[i][axis]
     72 if len(reduced_inputs_shapes[i]) > self.axis:
     73     del reduced_inputs_shapes[i][self.axis]

IndexError: list assignment index out of range
```

**Comment by tilakrayal** [comment]
@pboutinaud,
I guess the problem might be due to Keras3.0 which contains by default with the tensorflow v2.17 and v2.18. When I tried to execute the same code with the Keras2.0(tf-keras), it was executed without fail/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/512b07148f1c838e09f4cbe03537b07f/untitled2212.ipynb).

```python
!pip install tf-keras==2.18.0
import tf_keras as keras
```

For Keras3.0, please raise the request in the Keras-team/Keras repo for the quick resolution. Thank you!

**Comment by pboutinaud** [comment]
Ok, thank you
