### ISSUE TITLE
Issue with while_loop in tf.scan

### ISSUE THREAD

**Issue by RiaanZoetmulder** [tensorflow/tensorflow#7896]
Hello,

I have recently updated to the newest version of tensorflow (v1.0) and am suddenly having some trouble when I use tf.scan.

I have already tried setting shapes for all of the variables. Which didn't work! Don't really know what else i could do since that is the solution that is recommended for the error in tf.while_loop...

Here is the code snippet:

`
h, z = tf.scan(
                    self.sample,
                    x,
                    initializer = [ h0, tf.expand_dims(z0, 1 )]
                    )
`

Where h0 is [256, 90], z0 is expanded to [256, 1] and x is [None, 256, 400]. It worked in the previous version so I am assuming the trouble is related to the tf.scan code.

ValueError: The shape for scan/while/Merge_2:0 is not an invariant for the loop. It enters the loop with shape (256, 1), but has shape (256,) after one iteration. Provide shape invariants using either the `shape_invariants` argument of tf.while_loop or set_shape() on the loop variables.

**Comment by RiaanZoetmulder** [comment]
I have fixed my problem by adding an additional expand_dims and an additional squeeze at the end. However I find it curious that it still produced this error in the new version, whereas it didn't in the previous one.

**Comment by aselle** [comment]
@yuanbyu, any ideas?

**Comment by bdhingra** [comment]
I am facing the exact same error. Relevant code below:

`def _mem_read(self, e):
        # e : B x R x C, self.memory : B x N x R x Dr
        N = tf.shape(self.memory)[1] # length of the sequence + 1
        eshuf = tf.transpose(e, perm=(2,0,1)) # C x B x R
        e1hot = tf.one_hot(eshuf, N, axis=2) # C x B x N x R

        # accumulate across C
        def _accum(acc, x):
            # x : B x N x R
            # acc : B x N x R x Dr
            return acc + tf.expand_dims(x, axis=3)*self.memory

        out = tf.scan(_accum, e1hot,
                initializer=tf.zeros((tf.shape(e)[0], N, self.num_relations, self.rdims),
                    dtype=tf.float32)) # B x N x R x Dr
        out = tf.reduce_sum(out, axis=1) # B x R x Dr
        return out
`
The error i receive is:

> ValueError: The shape for scan/while/scan/while/Merge_1:0 is not an invariant for the loop. It enters the loop with shape (?, ?, 2, 2), but has shape <unknown> after one iteration. Provide shape invariants using either the `shape_invariants` argument of tf.while_loop or set_shape() on the loop variables.

@RiaanZoetmulder could you please elaborate exactly where you added the additional expand_dims and squeeze to resolve the error?

Thanks,
Bhuwan

**Comment by bb9696aa** [comment]
@bdhingra @RiaanZoetmulder I met the same question exactly as you described. Could you give me some advice about how to fix this problem?
