### ISSUE TITLE
Missing input file zipaling or aapt while building android example

### ISSUE THREAD

**Issue by Aquakor** [tensorflow/tensorflow#7897]
### Environment info
Operating System: Windows 10 Pro

If installed from source, provide 
The output of `bazel version`:
Build label: 0.4.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Feb 1 18:54:18 2017 (1485975258)
Build timestamp: 1485975258
Build timestamp as int: 1485975258

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

It throw 'missing input file zipaling' or 'missing input file aapt'.

`ERROR: missing input file '@androidsdk//:build-tools/25.0.2/zipalign'.
ERROR: C:/tools/msys64/tmp/_bazel_Kornel/i4o1VGAg/external/androidsdk/BUILD.bazel:5:1: declared output 'external/androidsdk/zipalign_runner.sh' was not created by genrule. This is probably because the genrule actually didn't create this output, or because the output was a directory and the genrule was run remotely (note that only the contents of declared file outputs are copied from genrules run remotely).
ERROR: C:/tools/msys64/tmp/_bazel_Kornel/i4o1VGAg/external/androidsdk/BUILD.bazel:5:1: not all outputs were created or valid.
ERROR: C:/tools/msys64/tmp/_bazel_Kornel/i4o1VGAg/external/androidsdk/BUILD.bazel:5:1: @androidsdk//:zipalign_binary: missing input file '@androidsdk//:build-tools/25.0.2/zipalign'.
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: C:/tools/msys64/tmp/_bazel_Kornel/i4o1VGAg/external/androidsdk/BUILD.bazel:5:1 1 input file(s) do not exist.
`

`ERROR: missing input file '@androidsdk//:build-tools/25.0.2/aapt'.
ERROR: C:/tools/msys64/tmp/_bazel_Kornel/i4o1VGAg/external/androidsdk/BUILD.bazel:5:1: @androidsdk//:aapt_binary: missing input file '@androidsdk//:build-tools/25.0.2/aapt'.
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: C:/tools/msys64/tmp/_bazel_Kornel/i4o1VGAg/external/androidsdk/BUILD.bazel:5:1 1 input file(s) do not exist.
`

### What other attempted solutions have you tried?
I tried chaning sdk versions to lower.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
[http://pastebin.com/6HQ4cVMS](url) - Pastebin zipaling log
[http://pastebin.com/VJrmxLSv](url) - Pastebin aapt log

[http://pastebin.com/mqCyPBhp](url) - Pastebin WORKSPACE file

**Comment by andrewharp** [comment]
Bazel doesn't support Android on Windows yet; see #6385 for more details and alternatives.
