### ISSUE TITLE
GPU support tensorflow NVIDIA JETSON ORIN NX 8GB UBUNTU 22.04

### ISSUE THREAD

**Issue by kevqcpp** [tensorflow/tensorflow#78983]
https://github.com/tensorflow/tensorflow/issues/62711 - came across this and we can install but trying to run on python3.12 Jetpack 6.0 and having trouble getting the gpu recognized. nvcc --version 12.2 and LB_LIBRARY_PATH is fine. Still can't get this running. No and-cuda apparently. Anything special to get it to recognize the gpu?
Tried the link in the post as well as 12.16.1 python 3.10/2 without success
Wheel file not supporting the format although uname -a agrees with arch64 in releases
Please help

**Comment by Venkat6871** [comment]
Hi **@kevqcpp** ,
Please check all compatibility versions for that specific TensorFlow version. Here, I am providing [documentation](https://www.tensorflow.org/install/source#gpu) for your reference. Also, please let us know where you are facing the issue and which versions you are using. This will make it easier for us to troubleshoot.
Thank you!

**Comment by kevqcpp** [comment]
Advertised as compatible 12.16.1 - python 3.10
My understanding was that this installation uses a different version from those listed in the tensorflow datasheet
https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html

The user who mentioned that they could get gpu working on a jetson used the dp distro and idk what that is or why I should use that but it doesn't appear that I can install it for gpu use although I can install the library. How to enable gpu on jetson?
Jetpack 6.0
nvcc --version 12.2

**Comment by kevqcpp** [comment]
Updated to jetpack 6.1 -comes with cuda 12.6
changed cudnn path links LD_LIBRARY and PATH to include 12.6.1 Python 3.10/12 (both advertise support)
Tensorflow 12.16.1
Still no GPU

**Comment by kevqcpp** [comment]
Reflashed the device with Jetpack version and only one python and it worked fine
