### ISSUE TITLE
when i use tf.train.SyncReplicasOptimizer ,find worker1 run step 150,but worker0 run step 120,is right??

### ISSUE THREAD

**Issue by guoying1030** [tensorflow/tensorflow#7898]
when i use tf.train.SyncReplicasOptimizer ,find worker1 run step 150,but worker0 run step 120,is right??

opt = tf.SyncReplicasOptimizer(opt, replicas_to_aggregate=number_workers,
                               total_num_replicas=number_workers)

is it right??,find worker1 run step 150,but worker0 run step 120,is right??

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
