### ISSUE TITLE
segmentation fault when running convolutional.py

### ISSUE THREAD

**Issue by evilrobot69** [tensorflow/tensorflow#79]
I am running tensorflow/models/image/mnist/convolutional.py. I get:

ariw@clairvoyance:~/tensorflow$ python tensorflow/models/image/mnist/convolutional.py 
Succesfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Succesfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Succesfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Succesfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 2
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 2
Initialized!
zsh: segmentation fault (core dumped)  python tensorflow/models/image/mnist/convolutional.py

Thoughts?

**Comment by evilrobot69** [comment]
Notes: I'm running on Ubuntu 14.04 i686, following the "install from source" instructions. I have 2GB RAM/4GB swap.

**Comment by ebrevdo** [comment]
Can you do the following:

Build //tensorflow/models/mnist:convolutional via:

bazel build -c dbg //tensorflow/models/mnist:convolutional

And run with gdb:

(assuming your python is in /usr/bin/python2.7)
gdb --args /usr/bin/python2.7 bazel-bin/tensorflow/models/mnist:convolutional

(press "r" to run it)

wait until it crashes; and type "bt" for backtrace

paste the resulting output here.

**Comment by evilrobot69** [comment]
(gdb) r
Starting program: /usr/bin/python2.7 bazel-bin/tensorflow/models/image/mnist/convolutional
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
process 29857 is executing new program: /usr/bin/python2.7
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
Traceback (most recent call last):
  File "/usr/share/gdb/auto-load/usr/lib/i386-linux-gnu/libstdc++.so.6.0.19-gdb.py", line 63, in <module>
    from libstdcxx.v6.printers import register_libstdcxx_printers
ImportError: No module named 'libstdcxx'
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
I tensorflow/core/common_runtime/local_device.cc:25] Local device intra op parallelism threads: 2
[New Thread 0xa8abdb40 (LWP 29862)]
[New Thread 0xa80bcb40 (LWP 29863)]
I tensorflow/core/common_runtime/local_session.cc:45] Local session inter op parallelism threads: 2
[New Thread 0xa76ffb40 (LWP 29864)]
[New Thread 0xa4a8fb40 (LWP 29865)]
Initialized!
python: third_party/eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorIntDiv.h:177: Eigen::internal::TensorIntDivisor<int>::TensorIntDivisor(int32_t): Assertion `divider >= 2' failed.

Program received signal SIGABRT, Aborted.
[Switching to Thread 0xa4a8fb40 (LWP 29865)]
0xb7fdd424 in ?? ()
(gdb) bt
#0  0xb7fdd424 in ?? ()
#1  0xb418e20e in Eigen::TensorEvaluator<Eigen::TensorImagePatchOp<-1, -1, Eigen::TensorMap<Eigen::Tensor<float const, 4u, 1, int>, 1> const> const, Eigen::ThreadPoolDevice>::TensorEvaluator (
    this=0xa4a8e25c, op=..., device=...) at third_party/eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorImagePatch.h:363
#2  0xb4207a8e in Eigen::TensorEvaluator<Eigen::TensorReshapingOp<Eigen::DSizes<int, 2u> const, Eigen::TensorImagePatchOp<-1, -1, Eigen::TensorMap<Eigen::Tensor<float const, 4u, 1, int>, 1> const> const> const, Eigen::ThreadPoolDevice>::TensorEvaluator (this=0xa4a8e25c, op=..., device=...) at third_party/eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorMorphing.h:121
#3  0xb41fd4f7 in Eigen::TensorContractionEvaluatorBase<Eigen::TensorEvaluator<Eigen::TensorContractionOp<Eigen::array<Eigen::IndexPair<int>, 1u> const, Eigen::TensorReshapingOp<Eigen::DSizes<int, 2u> const, Eigen::TensorImagePatchOp<-1, -1, Eigen::TensorMap<Eigen::Tensor<float const, 4u, 1, int>, 1> const> const> const, Eigen::TensorReshapingOp<Eigen::DSizes<int, 2u> const, Eigen::TensorMap<Eigen::Tensor<float const, 4u, 1, int>, 1> const> const> const, Eigen::ThreadPoolDevice> >::TensorContractionEvaluatorBase (this=0xa4a8e1f0, op=..., device=...)
    at third_party/eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorContraction.h:158

**Comment by benoitsteiner** [comment]
I have pushed a fix for this assertion to our internal tensorflow code repository. It will be available on github with the next push.

**Comment by vrv** [comment]
I believe this is fixed as of 9c3043ff3bf31a6a81810b4ce9e87ef936f1f529, will be in our next binary release
