### ISSUE TITLE
Segmenttation fault tensorflow 1.0 osx

### ISSUE THREAD

**Issue by geoHeil** [tensorflow/tensorflow#7900]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/tensorflow/tensorflow/issues/3263
https://github.com/tensorflow/tensorflow/issues/2278

Note, I already set the link to 
`sudo ln -s /usr/local/cuda/lib/libcuda.dylib /usr/local/cuda/lib/libcuda.1.dylib`

### Environment info
Operating System:
osx 10.12.3

Installed version of CUDA and cuDNN:  8.0.63 / 5.1
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
```
lrwxr-xr-x  1 root  wheel     33 26 Feb 15:35 /usr/local/cuda/lib/libcuda.1.dylib -> /usr/local/cuda/lib/libcuda.dylib
-rwxr-xr-x  1 root  wheel  13504 24 Jan 20:58 /usr/local/cuda/lib/libcuda.dylib
lrwxr-xr-x  1 root  wheel     45 12 Jan 02:33 /usr/local/cuda/lib/libcudadevrt.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudadevrt.a
lrwxr-xr-x  1 root  wheel     50 12 Jan 02:33 /usr/local/cuda/lib/libcudart.8.0.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib
lrwxr-xr-x  1 root  wheel     46 12 Jan 02:33 /usr/local/cuda/lib/libcudart.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.dylib
lrwxr-xr-x  1 root  wheel     49 12 Jan 02:33 /usr/local/cuda/lib/libcudart_static.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart_static
```

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
start python shell
import tensorflow

output is
```
Python 3.6.0 |Anaconda custom (x86_64)| (default, Dec 23 2016, 13:19:00)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.8.0.dylib locally
Segmentation fault: 11
```

### What other attempted solutions have you tried?
setting the link as outlined above in the linked issues

Checking the CUDA sample projects works fine so the library seems to be installed correctly.

**Comment by gunan** [comment]
after libcublas, AFAICR libcudnn is loaded.
Are you sure you have cudnn installed?

**Comment by geoHeil** [comment]
Yes. Copied into both include and lib directory
gunan <notifications@github.com> schrieb am Mo. 27. Feb. 2017 um 12:15:

**Comment by gunan** [comment]
Which lib directory?
your cuda lib directory contents do not list libcudnn.

**Comment by geoHeil** [comment]
@gunan indeed. you were correct. I messed up some paths. Thank you.

**Comment by sbatir** [comment]
Hey @geoHeil , could you show me what paths you've got? I'm getting the exact same error as you, but I also have cudnn downloaded and installed. 
`dyn-160-39-142-202:lib sbatir$ ls -l /usr/local/cuda/lib/libcud*
lrwxr-xr-x  1 sbatir  admin        33 Mar  3 17:36 /usr/local/cuda/lib/libcuda.1.dylib -> /usr/local/cuda/lib/libcuda.dylib
-rwxr-xr-x  1 sbatir  wheel     13504 Jan 11 20:31 /usr/local/cuda/lib/libcuda.dylib
lrwxr-xr-x  1 sbatir  wheel        45 Jan 11 20:33 /usr/local/cuda/lib/libcudadevrt.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudadevrt.a
lrwxr-xr-x  1 sbatir  wheel        50 Jan 11 20:33 /usr/local/cuda/lib/libcudart.8.0.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib
lrwxr-xr-x  1 sbatir  wheel        46 Jan 11 20:33 /usr/local/cuda/lib/libcudart.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.dylib
lrwxr-xr-x  1 sbatir  wheel        49 Jan 11 20:33 /usr/local/cuda/lib/libcudart_static.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart_static.a
lrwxr-xr-x  1 sbatir  admin        36 Mar  3 17:37 /usr/local/cuda/lib/libcudnn.5 -> /usr/local/cuda/lib/libcudnn.5.dylib
-rwxr-xr-x@ 1 sbatir  admin  76280680 Feb 24 16:32 /usr/local/cuda/lib/libcudnn.5.dylib
-rwxr-xr-x@ 1 sbatir  admin  76280680 Feb 24 16:32 /usr/local/cuda/lib/libcudnn.dylib
-rw-r--r--@ 1 sbatir  admin  64702864 Feb 24 16:32 /usr/local/cuda/lib/libcudnn_static.a
`

**Comment by geoHeil** [comment]
What is your os? On a first glance that looks rather fine but you can look
at https://github.com/geoHeil/dev-env/blob/master/osx-setup.sh
sbatir <notifications@github.com> schrieb am Mi. 29. März 2017 um 18:12:
