### ISSUE TITLE
add_summary won't accept the tensor returned by tensor_summary 

### ISSUE THREAD

**Issue by KaraRyougi** [tensorflow/tensorflow#7904]
### Related Problem
https://github.com/tensorflow/tensorflow/issues/6778

### Environment Info
Operating System: Kubuntu 16.04 LTS

Installed TensorFlow version:
No CUDA acceleration. Compiled from source.

commit hash: 
`4ac9c09d5ca57a03b8daa5fb9e295947b1619854`

bazel version:
```
Build label: 0.4.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Feb 1 18:54:21 2017 (1485975261)
Build timestamp: 1485975261
Build timestamp as int: 1485975261
```

### Example

I restored a graph from a checkpoint and get the variables. Then I tried to write the summary to the log but got an error.

```
sess = tf.Session()
saver = tf.train.import_meta_graph('my-model.meta')
saver.restore(sess, tf.train.latest_checkpoint('./'))
all_vars = tf.get_collection(tf.GraphKeys.GLOBAL_VARIABLES)
writer = tf.summary.FileWriter('./many/log',sess.graph)
writer.add_summary(tf.summary.tensor_summary("conv", all_vars[0]))
```

```
>>> writer.add_summary(tf.summary.tensor_summary('conv',all_vars[0]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/summary/writer/writer.py", line 107, in add_summary
    event = event_pb2.Event(summary=summary)
TypeError: Parameter to MergeFrom() must be instance of same class: expected tensorflow.Summary got Tensor.
```
### Official API Description

According to the official API (https://www.tensorflow.org/api_docs/python/tf/summary/FileWriter), 

`tf.summary.tensor_summary` 

> Returns:
A scalar Tensor of type string. The serialized Summary protocol buffer.

 `add_summary(summary, global_step=None)`

> You can pass the result of evaluating any summary op, using tf.Session.run or tf.Tensor.eval, to this function. Alternatively, you can pass a tf.Summary protocol buffer that you populate with your own data. The latter is commonly done to report evaluation results in event files.

So I believe this is a bug.

**Comment by KaraRyougi** [comment]
Also https://github.com/tensorflow/models/issues/764

**Comment by KaraRyougi** [comment]
Sorry I realized this issue is not about the functions but my understanding of tensorflow. In order to manipulate I have to have the graph run by a session.

**Comment by IdoHakimi** [comment]
@KaraRyougi can you please provide your solution since I'm stuck on the same problem :(

**Comment by sunshinevirgo21** [comment]
@KaraRyougi @IdoHakimi - were you able to resolve this problem ?
