### ISSUE TITLE
Tensorflow DLL (Dynamic Link Library) Load Failure

### ISSUE THREAD

**Issue by HappyStackCoder** [tensorflow/tensorflow#79041]
Here's the error: 

_ImportError:_ DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.
Failed to load the native TensorFlow runtime.

_Major Action:_ Multiple versions of tensorflow and python have already been executed yet the error pertains. 

_Tools Used:_ Django, Conda (for virtual env)

**Comment by Venkat6871** [comment]
Hi **@HappyStackCoder** ,
Apologies for the delay, Could you please provide the tensorflow and the compatible version which you are trying to install. Also there are at least 3 possible scenarios:

You need to install the MSVC 2019 redistributable
Your CPU does not support AVX2 instructions
Your CPU/Python is on 32 bits
There is a library that is in a different location/not installed on your system that cannot be loaded.
https://github.com/tensorflow/tensorflow/issues/61887
Thank you!

**Comment by Fahadxx** [comment]
anyone found a proper solution for the CPU not supporting AVX2?

**Comment by mihaimaruseac** [comment]
Duplicate of https://github.com/tensorflow/tensorflow/issues/19584. Please do a search before opening new issues. This is a very old issue and manifests because old PCs with Windows cannot load libraries needed by TF because they have very old architecture sets.
