### ISSUE TITLE
Erroneous number of channels in the Guide to TF Layers tutorial.

### ISSUE THREAD

**Issue by karltk** [tensorflow/tensorflow#7906]
The tutorial _[A Guide to TF Layers: Building a Convolutional Neural Network](https://www.tensorflow.org/tutorials/layers)_ seems to have the wrong number of channels in the tensor dimensions given at the end of the paragraph _Convolutional Layer #1_:

> Our output tensor produced by conv2d() has a shape of [batch_size, 28, 28, 1]: the same width and height dimensions as the input, but now with 32 channels holding the output from each of the filters.

To be consistent with the rest of the tutorial, it should probably say _"shape of [batch_size, 28, 28, 32]"_, since the rightmost dimension denotes the number of channels.

**Comment by tatatodd** [comment]
@karltk Good point, thanks for filing this issue!  I'll get it fixed up.
