### ISSUE TITLE
Discrepancy in Error Handling for `tf.gather` on CPU vs GPU Leading to Undefined Behavior

### ISSUE THREAD

**Issue by Cirno-2000** [tensorflow/tensorflow#79063]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

v2.18.0-rc2-4-g6550e4bd802 2.18.0

### Custom code

Yes

### OS platform and distribution

Ubuntu 22.04 jammy

### Python version

3.10.0

### Current behavior?

When running a custom implementation of `tf_as_strided` on TensorFlow using `tf.gather` to simulate the behavior of creating a strided tensor, a significant discrepancy in error handling between CPU and GPU is observed. The CPU raises an `INVALID_ARGUMENT` error when indices are out of range, whereas the GPU produces unexpected outputs without raising an error. This lack of consistent error handling on the GPU could lead to silent data corruption or undefined behavior.

### Reproduction Steps:

  - Create a tensor with some data and define a size and stride pattern that leads to out-of-bounds index access.
  - Implement the `tf_as_strided` function using tf.gather to simulate a custom striding mechanism.
  - Run the function on both CPU and GPU using TensorFlow's `tf.device` context.

### Standalone code to reproduce the issue

Colab: [link](https://colab.research.google.com/drive/1vQkXo3T-2cROEd31yySVsOTIq4Rw2isC?usp=sharing)

Safe Tensors: [Google Drive](https://drive.google.com/file/d/1SmfHggjjPF2fEyVMCtBWB_NFE-MVRhb-/view?usp=sharing)

```python
import tensorflow as tf
import numpy as np
from safetensors.torch import load_file


def set_seed(seed_value=42):
    """Sets the random seed for reproducibility."""
    np.random.seed(seed_value)
    tf.random.set_seed(seed_value)


def tensorflow_version(input, cpu=True):
    # Set seed for reproducibility
    set_seed()

    if cpu:
        device_string = "/cpu:0"
    else:
        device_string = "/gpu:0"

    with tf.device(device_string):
        input_tensor = input["input"]
        size = input["size"]
        stride = input["stride"]
        storage_offset = input.get("storage_offset", 0)

        def tf_as_strided(x, size, stride, storage_offset):
            flat_tensor = tf.reshape(x, [-1])
            start_idx = storage_offset
            idxs = []
            for i in range(size[0]):
                for j in range(size[1]):
                    idxs.append(start_idx + i * stride[0] + j * stride[1])

            strided_tensor = tf.gather(flat_tensor, idxs)
            strided_tensor = tf.reshape(strided_tensor, size)
            return strided_tensor

        strided_tensor = tf_as_strided(input_tensor, size, stride, storage_offset)

        return {"as_strided_result": strided_tensor.numpy()}


def load_safe_tensor(file_path):
    """Loads the safe tensor from the specified file path using safetensors library."""
    safe_tensor_data = load_file(file_path)

    # Assuming the input tensor is stored with key "input"
    input_tensor = safe_tensor_data["input"]

    # Convert the loaded tensor to TensorFlow tensor
    return {"input": tf.convert_to_tensor(input_tensor.numpy())}


def main():
    # File location
    file_path = "tensorflow_as_strided_1.safetensors"

    # Load the safe tensor
    input_data = load_safe_tensor(file_path)

    # Add non-tensor arguments to the input data
    input_data["size"] = (2, 3)
    input_data["stride"] = (0, 1)
    input_data["storage_offset"] = 0

    # Run on CPU
    try:
        result_cpu = tensorflow_version(input_data, cpu=True)
        print("CPU Result:")
        print(result_cpu)
    except Exception as e:
        print("CPU Error:")
        print(e)

    # Check if GPU is available
    if tf.config.list_physical_devices("GPU"):
        try:
            result_gpu = tensorflow_version(input_data, cpu=False)
            print("GPU Result:")
            print(result_gpu)
            
        except Exception as e:
            print("GPU Error:")
            print(e)
    else:
        print("GPU not available.")


if __name__ == "__main__":
    main()
```

### Observed Behavior:

  - CPU Output: Local rendezvous is aborting with status: `INVALID_ARGUMENT: indices[1] = 1 is not in [0, 1)`
  - GPU Output: Produces an output tensor with unexpected values without raising any exception, e.g., `{'as_strided_result': array([[4468, 0, 0], [4468, 0, 0]])}.`
  - Additional Details: The resulting tensor contains repeated elements of 4468 along with zeros, indicating that the GPU did not properly handle out-of-bounds indices. The input data provided during the GPU run included a tensor that was incorrectly created due to this discrepancy: `{'input': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([4468])>}`.

### Expected Behavior:

Both CPU and GPU should raise an INVALID_ARGUMENT error if indices are out of range to ensure consistent behavior and avoid silent failures or undefined values. Specifically, no tensor should be created with values like [4468, 0, 0] without any validation error.

### Relevant log output

```shell
2024-10-30 17:39:27.333559: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: INVALID_ARGUMENT: indices[1] = 1 is not in [0, 1)
CPU Error:
{{function_node __wrapped__GatherV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} indices[1] = 1 is not in [0, 1) [Op:GatherV2]
GPU Result:
{'as_strided_result': array([[4468,    0,    0],
       [4468,    0,    0]])}
```

**Comment by Venkat6871** [comment]
Hi **@Cirno-2000** ,
Apologies for the delay, and thank you for raising your concern here. I tried running your code on Colab with TensorFlow version 2.17.0 and faced a different issue. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/51bf6c259d927c91c52b2bbdade20b97/79063_tf_2-18-cpu-v.ipynb) here for reference. Let me know if I made any mistakes. Thank you!

**Comment by Cirno-2000** [comment]
Hi @Venkat6871, sorry for the delay. I tried your [gist](https://colab.research.google.com/gist/Venkat6871/51bf6c259d927c91c52b2bbdade20b97/79063_tf_2-18-cpu-v.ipynb) and it returned results successfully.

Have you run the code with a GPU runtime, based on the error message?

**Comment by Venkat6871** [comment]
Hi **@Cirno-2000** ,
Apologies for the delay. I tried using the GPU runtime also, but I am facing the same issue as with the CPU. Please refer to the [gist](https://colab.sandbox.google.com/gist/Venkat6871/b69e4558c53ba2e8d56096a2560135ec/79063_tf-nightly-2-19-0-v.ipynb) here for more details. Let me know if I made any mistakes.
Thank you!
