### ISSUE TITLE
Discrepancy in `tf.experimental.numpy.nansum` with `dtype=float16` on CPU vs GPU

### ISSUE THREAD

**Issue by Cirno-2000** [tensorflow/tensorflow#79083]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

v2.18.0-rc2-4-g6550e4bd802 2.18.0

### Custom code

Yes

### OS platform and distribution

Ubuntu 22.04.4 LTS x86_64

### Python version

3.10.0

#### **Bug Description:**

When using `tf.experimental.numpy.nansum` with a specified `dtype` of `float16`, there is a significant discrepancy between the CPU and GPU results. On the CPU, the operation produces a normal float16 value, while on the GPU, it results in an `inf` value, indicating a potential issue in handling float16 precision on the GPU.

When switching to `float32` for the dtype, the results between the CPU and GPU align closely, which suggests that the discrepancy is specifically related to the handling of float16 values.

### Standalone code to reproduce the issue

[colab](https://colab.research.google.com/drive/14b31pm1EDgivd-xcIxugFVuJc8D7_4a2?usp=sharing)
[safe tensors](https://drive.google.com/file/d/1sg_bCRlhow5VYenkFKARRe2Matuw7owq/view?usp=sharing)

```shell
import tensorflow as tf
import numpy as np
from safetensors.torch import load_file

def set_seed(seed_value=42):
    """Sets the random seed for reproducibility."""
    np.random.seed(seed_value)
    tf.random.set_seed(seed_value)

def tensorflow_version(input, cpu=True):
    set_seed()
    if cpu:
        device_string = "/cpu:0"
    else:
        device_string = "/gpu:0"

    with tf.device(device_string):
        # Enable NumPy behavior in TensorFlow
        tf.experimental.numpy.experimental_enable_numpy_behavior()

        # Unpack input dictionary
        x1 = tf.constant(input["input"])
        x2 = input["dim"]
        keepdim = input.get("keepdim", False)
        dtype = input.get("dtype", None)

        if dtype is not None:
            dtype = tf.as_dtype(dtype)

        # Perform the nansum operation
        y = tf.experimental.numpy.nansum(x1, axis=x2, keepdims=keepdim, dtype=dtype)

        return {"nansum": y.numpy()}

def load_safe_tensor(file_path):
    """Loads the safe tensor from the specified file path using safetensors library."""
    safe_tensor_data = load_file(file_path)

    # Assuming the input tensor is stored with key "input"
    input_tensor = safe_tensor_data["input"]

    # Convert the loaded tensor to TensorFlow tensor
    return {"input": tf.convert_to_tensor(input_tensor.numpy())}

def main():
    # File location
    file_path = (
        "tensorflow_nansum_2.safetensors"
    )

    # Load the safe tensor
    input_data = load_safe_tensor(file_path)

    # Add non-tensor arguments to the input data
    input_data["dim"] = (1,)
    input_data["keepdim"] = True
    input_data["dtype"] = np.float16  # np.float32 will work

    # Run on CPU
    result_cpu = tensorflow_version(input_data, cpu=True)
    print("CPU Result:")
    print(result_cpu)

    # Check if GPU is available
    if tf.config.list_physical_devices("GPU"):
        result_gpu = tensorflow_version(input_data, cpu=False)
        print("GPU Result:")
        print(result_gpu)

        # Calculate and print the differences
        if result_gpu:
            diff = np.abs(result_cpu["nansum"] - result_gpu["nansum"])
            print(
                "Maximum Absolute Difference between CPU and GPU results:", np.max(diff)
            )
    else:
        print("GPU not available.")

if __name__ == "__main__":
    main()
```

#### **Issue Summary:**
- When `dtype` is set to `float16`, the GPU calculation produces an `inf` value, while the CPU results in a proper float16 output. This discrepancy is not observed with `float32`.
- The unexpected `inf` value suggests that the GPU implementation for `tf.experimental.numpy.nansum` with `float16` has numerical precision or overflow issues.
- Switching to `float32` resolves the issue, indicating that this is specific to float16 precision handling.

### Relevant log output

```shell
CPU Result:
{'nansum': array([[[2048. , -473.5]]], dtype=float16)}
GPU Result:
{'nansum': array([[[   inf, -471.5]]], dtype=float16)}
Maximum Absolute Difference between CPU and GPU results: inf
```

**Comment by tilakrayal** [comment]
@Cirno-2000,
The reason could be due to the optimized way of calculating numbers on Nvidia which is different compared to others, there will be a small amount of precision errors. The same behavior is not observed on Apple M1, using numpy or in CPU.

Thank you!
