### ISSUE TITLE
is it tf.train.MomentumOptimizer is SGD+monment  Optimizer???

### ISSUE THREAD

**Issue by guoying1030** [tensorflow/tensorflow#7909]
is it tf.train.MomentumOptimizer is SGD+monment  Optimizer???

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
