### ISSUE TITLE
int8 quantization

### ISSUE THREAD

**Issue by JinXiaozhao** [tensorflow/tensorflow#79127]
Does tflite support int8 quantization? Does int8 quantization support quantizing only the specified layer?

**Comment by tilakrayal** [comment]
@JinXiaozhao,
Have you gone through the official document where Integer quantization is an optimization strategy that converts 32-bit floating-point numbers (such as weights and activation outputs) to the nearest 8-bit fixed-point numbers.

https://ai.google.dev/edge/litert/models/post_training_integer_quant

Thank you!
