### ISSUE TITLE
can there any examples about multi GPU or multi machine training

### ISSUE THREAD

**Issue by freepjf** [tensorflow/tensorflow#7913]
the news said 64 GPU can acheive 56 speed,how can we build for training test.  
can there any examples?

**Comment by yaroslavvb** [comment]
cc @tfboyd

**Comment by tfboyd** [comment]
#7679 Tracking progress on another issue.  We will have both in one script that allows you to try different options, e.g. data formats, ps placement and variable update options.  I would love to release it now as I know many people are really interested.  Closing this issue to keep tracking on the other one.
