### ISSUE TITLE
url not present for python3.6

### ISSUE THREAD

**Issue by pdoongarwal** [tensorflow/tensorflow#7915]
I noticed that the URL for python3.6 is not included on this page,
https://www.tensorflow.org/install/install_linux#TF_PYTHON_URL.

**Comment by aselle** [comment]
@gunan, @wolffg, please comment.

**Comment by gunan** [comment]
This seems to be a bug in our website. The whl files are there but we just dont have the links there.
@wollf can we route this appropriately to update the link and the website?

In the meantime, you can replace all `35` in the python 3.5 links with `36` to download the pip package for python 3.6
Or you can simply use `pip install tensorflow` to get the appropriate pip package from pypi.

**Comment by gunan** [comment]
@jugglerix can we send out a fix and republish the website?

**Comment by gunan** [comment]
Website updated. Closing issue.
