### ISSUE TITLE
Tensorflow Lite C++ 

### ISSUE THREAD

**Issue by rishik1001** [tensorflow/tensorflow#79153]
Is there any C++ API to enable flex delegates, after generating the tensorflowlite_flex.dll file ?

**Comment by gaikwadrahul8** [comment]
Hi, @rishik1001

I couldn't find a direct C++ API to explicitly enable the Flex delegate after the `tensorflowlite_flex.dll` is generated but as far I know you can enable it by doing something like below if I'm not wrong please refer to this [source file](https://github.com/tensorflow/tensorflow/blob/56d35d4d34acfbb2c2b91a88b2e250888d429fa7/tensorflow/lite/delegates/flex/delegate.cc)

```
#include "tensorflow/lite/delegates/flex/delegate.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/interpreter.h"

// Load your TFLite model
std::unique_ptr<tflite::FlatBufferModel> model = 
    tflite::FlatBufferModel::BuildFromFile("model.tflite");

// Create interpreter builder
tflite::ops::builtin::BuiltinOpResolver resolver;
std::unique_ptr<tflite::Interpreter> interpreter;
tflite::InterpreterBuilder builder(*model, resolver);

// Create the Flex delegate
TfLiteDelegateUniquePtr flex_delegate = tflite::FlexDelegate::Create();

// Add the delegate to interpreter options
builder.AddDelegate(flex_delegate.get());

// Build the interpreter
builder(&interpreter);

// Allocate tensors
interpreter->AllocateTensors();

// Set input tensor data and run inference
interpreter->Invoke();
```
If I have missed something here please let me know.

Thank you for your cooperation and patience.
