### ISSUE TITLE
Unreachable statement

### ISSUE THREAD

**Issue by maddin200** [tensorflow/tensorflow#7917]
tensorflow\compiler\xla\service\algebraic_simplifier.cc line 675

additional: return Status::OK();

**Comment by aselle** [comment]
Could you fix this @tatatodd. Thanks!

**Comment by tatatodd** [comment]
I'm on it...  thanks for filing the issue @maddin200 !

**Comment by tatatodd** [comment]
OK this has been fixed - it should get synced over to the github repo in the next couple of days.  Closing this out.
