### ISSUE TITLE
Add support for loading specific frame from SequenceExample

### ISSUE THREAD

**Issue by gongbudaizhe** [tensorflow/tensorflow#7918]
Hi, 

I have converted my video dataset into TFRecords format by storing each video as a SequenceExample. The problem is I don't neccesarily need to load all frames of a video instead of 2 random frames. Is there any plan to add support for loading specific frame from a SequenceExample to save loading time?  Or is there any method I can use to speed up loading?

**Comment by tatatodd** [comment]
I think @jhseu and @skye might know about this.

**Comment by jhseu** [comment]
@ebrevdo is most familiar with SequenceExample plans.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
