### ISSUE TITLE
Warning during compilation on OS/X

### ISSUE THREAD

**Issue by DavidNorman** [tensorflow/tensorflow#7919]
... and maybe other systems too.

the warning is

```
./tensorflow/compiler/xla/service/backend.h:37:1: warning: class 'ThreadPoolDevice' was previously declared as a struct [-Wmismatched-tags]
```
It appears on almost every file in the XLA compiler directory, making the spotting of real problems harder.

**Comment by yaroslavvb** [comment]
@DavidNorman sorry for comment spam, could I have your email for some questions about GraphCore/TF integration? yaroslavvb@gmail.com
