### ISSUE TITLE
anyone else receive the following warning 

### ISSUE THREAD

**Issue by kirk86** [tensorflow/tensorflow#7929]
Hey guys, I was wondering if there's anyone else receiving the following warnings. I've updated `tf` through pip and since then I get the following warnings:

```
Using TensorFlow backend.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
```
Any idea what's going on? Prior to the update to the latest version never had this warning before.

**Comment by aselle** [comment]
This is a performance warning. For user convenience, our binaries do not have all the processor extensions so they work on older computers too. However, it is warning you that you do have those extensions available, and you can achieve better performance by building your own binary.

**Comment by kirk86** [comment]
@aselle thanks for the clarification.
