### ISSUE TITLE
Can't build tensorflow

### ISSUE THREAD

**Issue by Alphxt** [tensorflow/tensorflow#79299]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.18

### Custom code

No

### OS platform and distribution

Linux Gentoo 

### Python version

3.11

### Bazel version

Bazelisk 1.22.1 (bazel 6.5.0)

### GCC/compiler version

llvm-17 clang17

### CUDA/cuDNN version

12..6.1 / 9.5.0

### GPU model and memory

RTX 3050 laptop 8GB, but compiling for RTX 6000 ADA

### Current behavior?

Hello everyone. 
I am new to tensorflow building and it seems that I can't manage to do it correctly. Whatever version of CUDA or CUDNN I choose the builds always fail. Currently, I am trying to compile from source using the command 
```
bazel build -j 14 --local_ram_resources=HOST_RAM*.8 \
  --config=cuda_wheel \
  //tensorflow/tools/pip_package:wheel \
  --repo_env=HERMETIC_CUDA_VERSION="12.6.1" \
  --repo_env=HERMETIC_CUDNN_VERSION="9.5.0" \
  --repo_env=HERMETIC_CUDA_DRIVER_VERSION="550" \
  --repo_env=HERMETIC_CUDA_COMPUTE_CAPABILITIES="sm_89" \
  --repo_env=WHEEL_NAME=tensorflow_test \
  --verbose_failures
```

However, it returns the error "clang-17: error: cannot find libdevice for sm_89; provide path to different CUDA installation via '--cuda-path', or pass '-nocudalib' to build without linking with libdevice
clang-17: error: cannot find CUDA installation; provide its path via '--cuda-path', or pass '-nocudainc' to build without CUDA includes
clang-17: error: cannot find CUDA installation; provide its path via '--cuda-path', or pass '-nocudainc' to build without CUDA includes
Target //tensorflow/tools/pip_package:wheel failed to build
INFO: Elapsed time: 893.679s, Critical Path: 71.04s
INFO: 11895 processes: 5385 internal, 6510 local.
FAILED: Build did NOT complete successfully"

I must admit that don't understand why it fails. As I understand the recent updates to TF, it is supposed to download the necessary CUDA and CUDNN versions itself, so I don't see which path I am supposed to provide here. I have already tried to use the recommended CUDA and CUDNN versions, but it didn't help with my problem. I have read throughout the documentation in both https://github.com/openxla/xla/blob/main/docs/hermetic_cuda.md#environment-variables-controlling-the-hermetic-cudacudnn-versions and https://www.tensorflow.org/install/source?hl=en but it doesn't help much. Is there any tutorial I could follow for compiling tensorflow, or anyone that could help me with that? 

Thank you very much.

### Standalone code to reproduce the issue

```shell
Standalone code:

bazel build -j 14 --local_ram_resources=HOST_RAM*.8 \
  --config=cuda_wheel \
  //tensorflow/tools/pip_package:wheel \
  --repo_env=HERMETIC_CUDA_VERSION="12.6.1" \
  --repo_env=HERMETIC_CUDNN_VERSION="9.5.0" \
  --repo_env=HERMETIC_CUDA_DRIVER_VERSION="550" \
  --repo_env=HERMETIC_CUDA_COMPUTE_CAPABILITIES="sm_89" \
  --repo_env=WHEEL_NAME=tensorflow_test \
  --verbose_failures

Or 

bazel build -j 14 --local_ram_resources=HOST_RAM*.8 \
  --config=cuda_wheel \
  //tensorflow/tools/pip_package:wheel \
  --repo_env=HERMETIC_CUDA_VERSION="12.5.1" \
  --repo_env=HERMETIC_CUDNN_VERSION="9.3.0" \
  --repo_env=HERMETIC_CUDA_DRIVER_VERSION="550" \
  --repo_env=HERMETIC_CUDA_COMPUTE_CAPABILITIES="sm_89" \
  --repo_env=WHEEL_NAME=tensorflow_test \
  --verbose_failures
```

**Comment by tilakrayal** [comment]
@Alphxt,
Could you please try to use --config=cuda_clang after configuring to build using clang. (I also think that using bazel build without --config flags should work too)

The build currently also fails because of an error in `configure` script. The fix should be upstream soon, the workaround before it lands is to change the following lines of `.tf_configure.bazelrc` from:
```python
build --config=cuda
test --config=cuda
```
to:
```python
build --config=cuda_clang
test --config=cuda_clang
```
This should be done after running `configure`. Thank you!
