### ISSUE TITLE
Installing tensorflow-text triggers a rollback of current's tensorflow version

### ISSUE THREAD

**Issue by Mark531** [tensorflow/tensorflow#79331]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.10.1

### Custom code

Yes

### OS platform and distribution

Windows 10

### Python version

3.10.13

### Current behavior?

> pip install --upgrade tensorflow
Successfully installed flatbuffers-24.3.25 h5py-3.12.1 ml-dtypes-0.4.1 numpy-2.0.2 protobuf-5.28.3 tensorboard-2.18.0 tensorboard-data-server-0.7.2 **tensorflow-2.18.0** tensorflow-intel-2.18.0

> pip install --upgrade tensorflow-text
Successfully installed keras-2.10.0 protobuf-3.19.6 tensorboard-2.10.1 tensorboard-data-server-0.6.1 **tensorflow-2.10.1**

### Standalone code to reproduce the issue

```shell
Just type in sequence the 2 command lines written above.
```

**Comment by VadisettyRahul** [comment]
Hi @Mark531 

This issue occurs because tensorflow-text has restrictive version dependencies, which leads to a downgrade of tensorflow to version 2.10.1 when it is installed. The documentation says that when installing, note the version of tensorflow you are running, as you must specify the corresponding minor version of TF Text.

**Comment by VadisettyRahul** [comment]
@Mark531 I searched and saw that the library is active and in use, especially for cases where text processing is essential for machine learning models with tensorflow., but it is delayed to maintain alignment with newer versions of tensorflow. That is, updates to the tensorflow-text library are not updated immediately.

**Comment by Mark531** [comment]
So, so it is currently usable with tensorflow 2.10.1.

**Comment by VadisettyRahul** [comment]
@Venkat6871 need help?

**Comment by Venkat6871** [comment]
Hi **@Mark531** ,
Apologies for the delay, and thank you for raising your concern here. Could you please confirm where exactly you are facing the issue—with TensorFlow or with TensorFlow-Text triggers? If it is with TensorFlow-Text triggers, please raise the issue in that particular [repository](https://github.com/tensorflow/text/issues).
Thank you!
