### ISSUE TITLE
pip (python3) does not install *most* example code

### ISSUE THREAD

**Issue by jmoraleda** [tensorflow/tensorflow#7933]
When installing on my Debian (stretch) using the "native pip" method via: 

# pip3 install -U tensorflow-gpu

I get tensorflow to install, but the examples directory does not contain everything I believe it should based on the source tree in github: This is what is installed in the examples directory:

/usr/local/lib/python3.5/dist-packages/tensorflow/examples$ tree
.
├── __init__.py
├── __pycache__
│   └── __init__.cpython-35.pyc
└── tutorials
    ├── __init__.py
    ├── mnist
    │   ├── __init__.py
    │   ├── input_data.py
    │   ├── mnist.py
    │   └── __pycache__
    │       ├── __init__.cpython-35.pyc
    │       ├── input_data.cpython-35.pyc
    │       └── mnist.cpython-35.pyc
    └── __pycache__
        └── __init__.cpython-35.pyc

5 directories, 10 files

PS. I wonder if this installation bug is related to issue: https://github.com/tensorflow/tensorflow/issues/590
since other issues report having similar problems there even after issue 590 was closed.

**Comment by tomwanzek** [comment]
Ran into the same question with a Windows 10 installation into an Anaconda conda environment. TensorFlow 1.0.0 was installed with `pip` as well.

**Comment by tatatodd** [comment]
@jmoraleda Perhaps you can try to uninstall first?

Note the instructions here:
https://www.tensorflow.org/install/install_linux#install_tensorflow

The sequence of commands should be:
```
$ sudo pip3 uninstall tensorflow # for Python 3.n
$ pip3 install tensorflow-gpu # Python 3.n; GPU support 
```

Only if that fails, try this (for Python 3.5 with GPU support):
```
$ sudo pip3 uninstall tensorflow # for Python 3.n
$ sudo pip3 install --upgrade \
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.0-cp35-cp35m-linux_x86_64.whl
```

**Comment by jmoraleda** [comment]
@tatatodd Thank you for your reply. I just tried your suggestion, but it made no difference. Uninstalling (pip3 uninstall tensorflow-gpu) followed by install (pip3 install tensorflow-gpu) produces the same effect as my original problem (i.e. Tensor flow installs and works, but the content of the examples directory  is limeted to what I showed in my original message) .

**Comment by gunan** [comment]
We are moving our example and model codes out of the pip package. Pip package will install the core TF library on your machine, and then you can download the example and tutorial codes from relevant webpages or our repository.

**Comment by jmoraleda** [comment]
@gunan. Thank you. That makes perfect sense. I imagine the download instructions and tutorials have not been updated yet to reflect this change. I will close this issue.
