### ISSUE TITLE
mnist_softmax_xla.py script does not show the correct timeline with xla flag turned on

### ISSUE THREAD

**Issue by agupta74** [tensorflow/tensorflow#7936]
I ran mnist_softmax_xla.py with XLA turned on but did not see the "_XLALaunch" in the timeline. It still shows the same timeline (i.e same as without XLA turned on). It looks like that XLA is not getting launched. Any help would be greatly appreciated?

### Environment info
Operating System: SUSE Linux 12

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

-rw-r--r-- 1 root root   558720 Jan 10 14:52 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Jan 10 14:52 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Jan 10 14:52 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rwxr-xr-x 1 root root   415432 Jan 10 14:52 /usr/local/cuda/lib64/libcudart.so.8.0.44
-rw-r--r-- 1 root root   775162 Jan 10 14:52 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 79337624 Nov 22 05:34 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 79337624 Nov 22 05:34 /usr/local/cuda/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 79337624 Nov 22 05:34 /usr/local/cuda/lib64/libcudnn.so.5.1.5
-rw-r--r-- 1 root root 69756172 Nov 22 05:34 /usr/local/cuda/lib64/libcudnn_static.a

![timeline_xla](https://cloud.githubusercontent.com/assets/21690396/23388520/8535e576-fd17-11e6-9d1e-92ec009aeab1.png)

1. A link to the pip package you installed: 
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.0-cp35-cp35m-linux_x86_64.whl

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
1.0.0

**Comment by yehenrytian** [comment]
I got the same issue following the instruction here: [https://www.tensorflow.org/versions/master/experimental/xla/jit](https://www.tensorflow.org/versions/master/experimental/xla/jit)

Step 3 basically produce the same result as Step 2. I updated TensorFlow to 1.0. I even tried the upgrading the Python testcase to the 1.0 version using:
`python tf_upgrade.py --infile mnist_softmax_xla.py --outfile mnist_softmax_xla_1.0.py`

I tried both Python2.7 and Python 3.5, same results:

`TF_XLA_FLAGS=--xla_generate_hlo_graph=.* python mnist_softmax_xla_1.0.py
Extracting /tmp/tensorflow/mnist/input_data/train-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/train-labels-idx1-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/t10k-images-idx3-ubyte.gz
Extracting /tmp/tensorflow/mnist/input_data/t10k-labels-idx1-ubyte.gz
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
 tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
0.9201
`

**Comment by yehenrytian** [comment]
@agupta74 I think we may need to build TensorFlow from the source code and turn on 

`Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N]`

The official version we installed probably does not have XLA enabled. I will try to build it from source, and see if it works.

**Comment by hawkinsp** [comment]
Yes, that's right. To use XLA, you need to build Tensorflow from source and enable XLA at configure time. XLA is still experimental and it's not ready to be enabled by default just yet. But feel free to try it out!

**Comment by tatatodd** [comment]
I'm closing this out, since "build TensorFlow from source and enable XLA" is the correct advice.

Feel free to file new issues if you run into them, and thanks for trying out XLA!  :)

**Comment by yehenrytian** [comment]
@tatatodd I think it is better to update the XLA page at: [https://www.tensorflow.org/versions/master/experimental/xla/jit](https://www.tensorflow.org/versions/master/experimental/xla/jit) to indicate this requirement.

**Comment by tatatodd** [comment]
@yehenrytian I believe it already does.  https://www.tensorflow.org/versions/master/experimental/xla/jit starts with:

```
Using JIT Compilation

* Note: TensorFlow must be compiled from source to include XLA.

Why use just-in-time (JIT) compilation?
...
```

**Comment by yehenrytian** [comment]
I tried to build tensorFlow with XLA enabled on Linux (Ubuntu): . But it looks like the example is still not working properly:

TF_XLA_FLAGS=--xla_generate_hlo_graph=.* python2.7 mnist_softmax_xla_1.0.py
Extracting ./data/train-images-idx3-ubyte.gz
Extracting ./data/train-labels-idx1-ubyte.gz
Extracting ./data/t10k-images-idx3-ubyte.gz
Extracting ./data/t10k-labels-idx1-ubyte.gz
I tensorflow/compiler/xla/service/platform_util.cc:58] platform Host present with 24 visible devices
I tensorflow/compiler/xla/service/service.cc:180] XLA service executing computations on platform Host. Devices:
I tensorflow/compiler/xla/service/service.cc:187]   StreamExecutor device (0): <undefined>, <undefined>
0.9148

I "rm" the official TF I installed before I can install my build ".whl" file, however, it looks like there is still some more problems here. Anyone can help? Thanks!

**Comment by tatatodd** [comment]
@yehenrytian Why do you say that the example is not working properly?

**Comment by yehenrytian** [comment]
@tatatodd Basically, I saw the same graph as from Step 2 with the .json file generated from Step 3 (when opened in chrome). And I don't see the console output of:

`computation cluster_0[_XlaCompiledKernel=true,_XlaNumConstantArgs=1].v82 [CPU:
pipeline start, before inline]: /tmp/hlo_graph_0.dot`

And I don't see any .dot file generated in the /tmp folder. 

I build TF r1.0 branch with XLA enabled. I am wondering if I should build the master branch? I am building TF on Linux, without any OpenCL or CUDA support.  Do I need to finish the Youtube video of your TF Dev Summit 2017 on XLA: TF, Compiled first? :)  Please help! Thanks!

**Comment by yehenrytian** [comment]
I am not sure if it is a testcase issue or not. But I can get another example here: [https://gist.github.com/yaroslavvb/53052184e50cdfec35f0a127dd6df843](https://gist.github.com/yaroslavvb/53052184e50cdfec35f0a127dd6df843) to work with and without XLA and get the same timing as long as the .dot files.

**Comment by tfboyd** [comment]
@yaroslavvb 's example works because he turns on JIT scope for the specific ops, which is needed if you are not using a GPU and want XLA for CPU to work via JIT.  

`with jit_scope(compile_ops=True):`

I left a note in the document to warn people.  

> Note: Turning on JIT at the session level will not result in operations being compiled for the CPU. JIT compilation for CPU operations must be done via the manual method documented below. This decision was made due to the CPU backend being single-threaded.

And at the start of the tutorial.  

> Currently JIT at the session level, which is what is used for the tutorial, only supports GPU.

Do not interpret this as hostile.  Let me know if you think there is a way to make it more clear.  Thank you for trying the tutorial, I am excited people are giving it a try.    Closing issue, please reopen if necessary.

**Comment by hkxIron** [comment]
I encountered the same problem for cpu.Thanks a lot
