### ISSUE TITLE
Add Python Graph Transform examples

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#7938]
The docs for the [Graph Transform Tool](https://github.com/tensorflow/tensorflow/blob/d699a66e940b26e991b29b27f4e3ad2e8e3282d2/tensorflow/tools/graph_transforms/README.md#writing-your-own-transforms) talk about writing your own transforms but way to do so is in C++. It would be cool if there was an example of / c++ hook writing transforms in Python as well. For example, here is one Python transform (by @mrry): http://stackoverflow.com/a/40852855/2638485 (https://github.com/tensorflow/tensorflow/issues/5918).

**Comment by cancan101** [comment]
There also seem to be an entire set of python graph transforms: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/tools

**Comment by tatatodd** [comment]
@petewarden might have thoughts on this.

**Comment by petewarden** [comment]
The rewrite scripts in python/tools are deprecated in favor of the Graph Transform Tool (and I need to update them to reflect that). In general, we're trying to make as much functionality as possible available across multiple languages, which means implementing core operations in C++ and exposing them through APIs. We're still happy to see user transforms written in Python, we've just chosen to take a different approach for these. Unfortunately that means we don't have 'canonical' examples of writing them in Python, as you've seen.

**Comment by tatatodd** [comment]
@cancan101 we'd welcome community contributions in this regard!

**Comment by cancan101** [comment]
The docs for [quantization](https://github.com/tensorflow/tensorflow/blob/dc6353d12fd41ec869283679dd7766ebff75c520/tensorflow/docs_src/performance/quantization.md) should also probably be updated to point to the new graph transform tool.

**Comment by souravsingh** [comment]
I am interested in working on this. How do I start?

**Comment by skye** [comment]
@petewarden is there still work to do here?

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
