### ISSUE TITLE
Docker versus direct install?

### ISSUE THREAD

**Issue by roschler** [tensorflow/tensorflow#794]
I picked up a TitanX card and I'm about to install Linux 14.04.3 Desktop.  Are there any performance considerations or Nvidia GPU driver considerations between choosing a Docker install or direct install?

**Comment by craigcitro** [comment]
Not that I know of, but we haven't done any heavy testing. (Unless @ebrevdo has done some?) 

In principle, the GPU device is directly exposed to the docker container, so if there is a difference, it should be negligible. If you try it and find otherwise, @roschler, we'd definitely like to know!

**Comment by roschler** [comment]
Thanks Craig.  I'll try the Docker container then.  I'm guessing it's easier and since you haven't indicated any loss of performance or programming features due to its usage, I see no reason not to.
