### ISSUE TITLE
wrong commands for installing protobuf at tutorial

### ISSUE THREAD

**Issue by wzpan** [tensorflow/tensorflow#7940]
The commands for installing protobuf at tutorial is wrong:

![bug](https://cloud.githubusercontent.com/assets/1631405/23393228/69fcc090-fdbc-11e6-96e3-413608bfee4a.png)

They are used for installing tensorflow via pip, but obviously what should be given are ways to install google protobuf via pip.

Please fix it.

Here's the url: https://www.tensorflow.org/install/install_linux#installing_with_native_pip

**Comment by tatatodd** [comment]
@wzpan Thanks for filing this issue!

It looks like the "native pip" section on both linux and mac suffers from this documentation issue.  Also note that the linux instructions incorrectly reference "your Mac".
https://www.tensorflow.org/install/install_linux#install_tensorflow
https://www.tensorflow.org/install/install_mac#install_tensorflow

Assigning to @martinwicke , feel free to re-assign as appropriate.  Thanks!

**Comment by gunan** [comment]
I spoke to a few people, and it looks like this is what we tried to mean there:

If you already have a version of protobuf installed, you should run the uninstall command. After that when you run `pip install tensorflow`, this command will install the correct version of protobuf, as it will install all TensorFlow dependencies.

We will update the website to reflect the above.

**Comment by skye** [comment]
Looks like this has been addressed, closing. Please reopen if I'm mistaken.
