### ISSUE TITLE
can not save the .ckpt file 

### ISSUE THREAD

**Issue by lxtGH** [tensorflow/tensorflow#7944]
I run such piece of codes on my lab server (Tensor flow 1.0 + cuda7.5)
`	with tf.Session() as session:
		with tf.device("/cpu:1"):
			session.run(init)
			coord = tf.train.Coordinator()
			threads = tf.train.start_queue_runners(coord=coord)
			max_iter = 9000
			iter= 0
			if os.path.exists(os.path.join("model", 'model.ckpt')) is True:
				tf.train.Saver(max_to_keep=None).restore(session, os.path.join("model", 'model.ckpt'))
			while iter < max_iter:
				loss_np, _, label_np, image_np, inf_np = session.run([loss, opti, batch_image, batch_label, inf])

				if iter % 50 == 0:
					print 'trainloss:', loss_np
				#if iter % 1000== 0:
					#tf.train.Saver(max_to_keep=None).save(session, os.path.join('model','model.ckpt'))
				iter = iter+1

			#  if iter%500==0:  
			#  accuracy_np=session.run([accuracy])  
			#  print '***************test accruacy:',accuracy_np,'*******************'  
			#  tf.train.Saver(max_to_keep=None).save(session, os.path.join('model','model.ckpt'))  
				#iter += 1	
			coord.request_stop()# queue
			coord.join(threads)
			tf.train.Saver(max_to_keep=None).save(session, os.path.join('model','model.ckpt'))`

I get this error:(last line of my codes)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device to node 'save/restore_all': Could not satisfy explicit device specification '/device:CPU:1' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0, /job:localhost/replica:0/task:0/gpu:0, /job:localhost/replica:0/task:0/gpu:1, /job:localhost/replica:0/task:0/gpu:2, /job:localhost/replica:0/task:0/gpu:3, /job:localhost/replica:0/task:0/gpu:4, /job:localhost/replica:0/task:0/gpu:5, /job:localhost/replica:0/task:0/gpu:6, /job:localhost/replica:0/task:0/gpu:7

I am new to tensorflow, Hope for help!

NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by lxtGH** [comment]
I found the answer ：
**Define the Saver in Your computing Graph （before the Session.run）**
like this `	saver = tf.train.Saver()
	init = tf.initialize_all_variables()
	with tf.Session() as session:
		with tf.device("/cpu:1"):`

**Comment by lxtGH** [comment]
I found the answer ：
**Define the Saver in Your computing Graph （before the Session.run）**
like this 
```
saver = tf.train.Saver() 
init = tf.initialize_all_variables() 
with tf.Session() as session: with tf.device("/cpu:1"):
			while iter < max_iter:
				loss_np, _, label_np, image_np, inf_np = session.run([loss, opti, batch_image, batch_label, inf])
				#print image_np.shape
				#print label_np.shape
				#cv2.imshow(str(label_np[0]),image_np[0])  
				#print label_np[0]  
				#cv2.waitKey()  
				#print label_np
				if iter % 50 == 0:
					print 'trainloss:', loss_np
				if iter % 1000== 0:
					saver.save(session, os.path.join('model','model.ckpt'))
```
