### ISSUE TITLE
(Saver.max_to_keep) should keep every checkpoint by default

### ISSUE THREAD

**Issue by tgy** [tensorflow/tensorflow#7946]
I was wondering why my checkpoints were being deleted and it's only after looking up the behavior of `Saver.max_to_keep` in the docs that I understood what was happening. I think a better default setting for this is to keep all checkpoints, at least that's what I would have expected.

**Comment by tatatodd** [comment]
@tgy Thanks for filing the issue!

Default values are always tricky; no matter what default we choose, someone will be surprised.  In this case I believe we've chosen the default max_to_keep=5 to avoid filling up your disk space.  It would be unfortunate if you left a job running for a while, only to discover that all of your disk had been used up by checkpoints!

It's true that it might be surprising upon first encountering the default max_to_keep=5 behavior, but we hope it's the "safer" alternative.

I'm closing this out.  If you feel I've missed something, feel free to respond to this issue, and I'll re-open.  Or file new issues if you encounter them.  Thanks!
