### ISSUE TITLE
Tensor Flow IN Android

### ISSUE THREAD

**Issue by younas-bangash** [tensorflow/tensorflow#795]
Please someone help me how i set the tensor flow library in android i try to follow the steps explain in the android example but stuck in first and i do not know how to do it which is Get the recommended Bazel version

**Comment by miyosuda** [comment]
On MacOSX, I first upgraded java to Java8, and then installed Bazel.

I've also prepared Android Example building environment with AndroidStudio and NDK, without Bazel.
https://github.com/miyosuda/TensorFlowAndroidDemo
If you would like to quickly try Android Example, it might help.

**Comment by vrv** [comment]
http://bazel.io/docs/install.html for installing bazel
