### ISSUE TITLE
Feature Request - Session Cancellation Function

### ISSUE THREAD

**Issue by agnusmaximus** [tensorflow/tensorflow#7954]
It'd be great to have a between node cancellation function for the tensorflow python session. In particular, if you call `sess.cancel_graph()` on a separate thread, then the tensorflow session on the main thread would be cancelled (raising an exception like the timeout exception). It would also be great for these cancellation signals to be caught between every tf operation, rather than only after particular operations like dequeue, etc.

**Comment by mrry** [comment]
Does `tf.Session.close()` not already satisfy this requirement? It cancels all concurrently running steps in a particular session, and these calls raise `tf.errors.CancelledError`.

**Comment by agnusmaximus** [comment]
Ah I wasn't aware of this feature. Thanks for pointing it out! I'll try it out.

**Comment by agnusmaximus** [comment]
Is there a way to keep the session alive but still cancel all the current steps asynchronously? I'm doing this in a distributed context, so keeping the session alive is necessary to continue training.

**Comment by agnusmaximus** [comment]
Is there any update on this?

**Comment by yaroslavvb** [comment]
Note that recreating session is normal part of distributed training. For instance, if you have a network delay and session.run times out, the session becomes invalid and needs to be recreated.

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
