### ISSUE TITLE
tf.contrib.layers.sparse_column_with_hash_bucket() lead to 'out of memory error' with large hash_bucket_size?

### ISSUE THREAD

**Issue by Sean-Git** [tensorflow/tensorflow#7957]
I'm using the wide_n_deep model on my own data, which has feature dimension about _100million_. When I use the _sparse_column_with_hash_bucket()_ and set the _hash_bucket_size_ to _10million_ (because some categorical features have that much different values), the program always failed with the out of memory error.

  So I wonder if tensorflow's wide_n_deep model could handles data with high dimension like the case above?

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
