### ISSUE TITLE
Windows Wheel file doesn't exist for tensorflow_io_gcs_filesystem library for the latest version pip install tensorflow-io-gcs-filesystem==0.37.1.

### ISSUE THREAD

**Issue by adarshbilimagga** [tensorflow/tensorflow#79581]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.18.0

### Custom code

Yes

### OS platform and distribution

Windows

### Python version

3.10.0

### Current behavior?

if we install -> pip install tensorflow-io-gcs-filesystem==0.37.1 it will always download the wheel file of older version of [tensorflow_io_gcs_filesystem-0.31.0-cp311-cp311-win_amd64.whl ](https://files.pythonhosted.org/packages/ac/4e/9566a313927be582ca99455a9523a097c7888fc819695bdc08415432b202/tensorflow_io_gcs_filesystem-0.31.0-cp311-cp311-win_amd64.whl)(1.5 MB [view hashes](https://pypi.org/project/tensorflow-io-gcs-filesystem/0.31.0/#copy-hash-modal-5a9e9ff6-6e95-4cec-940e-ae66d32efe0c))

It should be able to get a version corresponding to the latest version for windows also.

### Standalone code to reproduce the issue

```shell
if we install -> pip install tensorflow-io-gcs-filesystem==0.37.1 it will always download the wheel file of older version of [tensorflow_io_gcs_filesystem-0.31.0-cp311-cp311-win_amd64.whl ](https://files.pythonhosted.org/packages/ac/4e/9566a313927be582ca99455a9523a097c7888fc819695bdc08415432b202/tensorflow_io_gcs_filesystem-0.31.0-cp311-cp311-win_amd64.whl)(1.5 MB [view hashes](https://pypi.org/project/tensorflow-io-gcs-filesystem/0.31.0/#copy-hash-modal-5a9e9ff6-6e95-4cec-940e-ae66d32efe0c))
```

**Comment by tilakrayal** [comment]
@adarshbilimagga,
Looks like this issue is more related to Tensorflow-io. Could you please raise the issue in tensorflow-io from [here](https://github.com/tensorflow/io/issues) for the quick resolution. Thank you!

**Comment by adarshbilimagga** [comment]
Yes i had reported there but we didnt get any response - https://github.com/tensorflow/io/issues/2048.

**Comment by isuruwe** [comment]
same here

**Comment by tilakrayal** [comment]
@adarshbilimagga,
As the issue is related to tensorflow-io, please check the update in the respective repo for the quick resolution and also tensorflow doesn't have control on the tf-io repo. Thank you!

**Comment by d-kleine** [comment]
@isuruwe Please see https://github.com/tensorflow/io/issues/2087

Even though `tensorflow-io-gcs-filesystem` isn't a direct `tensorflow` issue, it's a dependency for `tensorflow` from the same organization. As you can see, the Windows wheels have not been build for a long time already (v0.31 - release Feb 25, **2023**) 
https://pypi.org/project/tensorflow-io-gcs-filesystem/0.31.0/#files

As another user has reported (https://github.com/tensorflow/io/issues/2087#issuecomment-2536220203), the Windows wheel build CI job failed. It looks like there is a problem with Bazel Windows building.

Would it be possible to push this issue internally?

**Comment by JardelCunha** [comment]
+1
