### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/google/protobuf/__init__.py

### ISSUE THREAD

**Issue by sijanonly** [tensorflow/tensorflow#7961]
I am trying to install tensorflow within virtual environment. After creating virtual env , I run following command : 

`pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0-cp34-cp34m-linux_x86_64.whl`

And the output is : 

Collecting tensorflow==0.9.0 from https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0-cp34-cp34m-linux_x86_64.whl
  Using cached https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0-cp34-cp34m-linux_x86_64.whl
Requirement already satisfied: six>=1.10.0 in /usr/local/lib/python3.4/dist-packages (from tensorflow==0.9.0)
Collecting protobuf==3.0.0b2 (from tensorflow==0.9.0)
  Using cached protobuf-3.0.0b2-py2.py3-none-any.whl
Requirement already satisfied: numpy>=1.8.2 in /usr/local/lib/python3.4/dist-packages (from tensorflow==0.9.0)
Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.4/dist-packages (from tensorflow==0.9.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.4/dist-packages (from protobuf==3.0.0b2->tensorflow==0.9.0)
Requirement already satisfied: appdirs>=1.4.0 in /usr/local/lib/python3.4/dist-packages (from setuptools->protobuf==3.0.0b2->tensorflow==0.9.0)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python3.4/dist-packages (from setuptools->protobuf==3.0.0b2->tensorflow==0.9.0)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.4/dist-packages (from packaging>=16.8->setuptools->protobuf==3.0.0b2->tensorflow==0.9.0)
Installing collected packages: protobuf, tensorflow
  Found existing installation: protobuf 3.0.0b1.post2
    Uninstalling protobuf-3.0.0b1.post2:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.4/shutil.py", line 523, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/google/protobuf/__init__.py' -> '/tmp/pip-frvrcwtb-uninstall/usr/local/lib/python3.4/dist-packages/google/protobuf/__init__.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.4/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python3.4/dist-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python3.4/dist-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib/python3.4/shutil.py", line 536, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/google/protobuf/__init__.py'

**Comment by gunan** [comment]
`/usr/local/lib/python3.4/dist-packages/google/protobuf/init.py` means it is trying to write to the central python package directory. please mage sure you activate the virtualenv before running the `pip install` command.

**Comment by tatatodd** [comment]
@sijanonly I believe that should resolve your problem, so I'm closing this out.

If you have other problems feel free to file new issues.  Thanks!

**Comment by huangshiyu13** [comment]
I use pip instead of pip3 and solve this problem:
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0-cp34-cp34m-linux_x86_64.whl
