### ISSUE TITLE
Clarify Migration From session_bundle.exporter to saved_model.builder.SavedModelBuilder

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#7962]
In looking at the docs for [Serving a TensorFlow Model](https://tensorflow.github.io/serving/serving_basic.html), and [comparing to wayback machine](https://web.archive.org/web/20160415224950/https://tensorflow.github.io/serving/serving_basic.html), it seems the serving guide went from using `session_bundle.exporter` to `saved_model.builder.SavedModelBuilder` with no documentation as to this change or the migration path.

Both tools wrap `Savers`. What is the difference between these? I believe `session_bundle` is deprecated and `SavedModelBuilder` is supposed to be a replacement however I have not seen this point made explicitly in the docs. All I could find is a comment in the `loader`:
```
Load legacy TF Exporter/SessionBundle checkpoint.
```

[Report from SO](http://stackoverflow.com/questions/42499228/tensorflow-session-bundle-vs-saved-model).

**Comment by tatatodd** [comment]
@concretevitamin might have some advice here.

**Comment by concretevitamin** [comment]
@sukritiramesh: can you take a look since you own SavedModel?

**Comment by cancan101** [comment]
So it seems the exporter is now marked deprecated: https://github.com/tensorflow/tensorflow/commit/02762f0db00c45ac2cb2cf9c6f629ad96c38fe9e, but are there any notes on how to make the migration?

**Comment by cancan101** [comment]
Seems like with the TF 1.1.0 release there are now warnings about this deprecation but little in the way of instructions:
```
export (from tensorflow.contrib.session_bundle.exporter) is deprecated and
will be removed after 2017-06-30.
Instructions for updating:
Please use SavedModel instead.
```

**Comment by martinwicke** [comment]
Look at https://tensorflow.github.io/serving/serving_basic for docs. We'll have more soon.

**Comment by cancan101** [comment]
Yes I linked to that initially though there is no migration docs.
