### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'state_is_tuple' on GRU or RNN

### ISSUE THREAD

**Issue by mcr-ksh** [tensorflow/tensorflow#7968]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
Compile error on RNN or GRU models.

### Environment info
Operating System:
> # lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.10
> Release:	16.10
> Codename:	yakkety

Installed version of CUDA and cuDNN: 
> # ls -l /opt/cuda/lib64/libcud*
> lrwxrwxrwx 1 ubuntu users       13 Jul 27  2016 /opt/cuda/lib64/libcudnn.so -> libcudnn.so.5
> lrwxrwxrwx 1 ubuntu users       17 Jul 27  2016 /opt/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.1.5
> -rwxrwxr-x 1 ubuntu users 79337624 Jul 27  2016 /opt/cuda/lib64/libcudnn.so.5.1.5
> -rw-rw-r-- 1 ubuntu users 69756172 Jul 27  2016 /opt/cuda/lib64/libcudnn_static.a

If installed from binary pip package, provide:
> # python3.5 -c "import tensorflow; print(tensorflow.__version__)"
> I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
> I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
> I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
> I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
> I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
> 1.0.0
> 

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
```
        if args.model == 'rnn':
            cell_fn = rnn.BasicRNNCell
        elif args.model == 'gru':
            cell_fn = rnn.GRUCell
        elif args.model == 'lstm':
            cell_fn = rnn.BasicLSTMCell
        else:
            raise Exception("model type not supported: {}".format(args.model))

        cell = cell_fn(args.rnn_size, state_is_tuple=True)
```
using lstm is fine but any other than that 'rnn' or 'gru' causes the failure.

**Comment by tatatodd** [comment]
@mcr-ksh Thanks for the info.  But your minimal example is too minimal.  :)

Can you provide a **self-contained** minimal example that demonstrates the problem, along with the full log / error trace?  Thanks!

**Comment by mcr-ksh** [comment]
sure.

> git clone https://github.com/sherjilozair/char-rnn-tensorflow.git
> python3.5 train.py --model gru

`# python3.5 train.py --model gru
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
loading preprocessed files
Traceback (most recent call last):
  File "train.py", line 114, in <module>
    main()
  File "train.py", line 48, in main
    train(args)
  File "train.py", line 82, in train
    model = Model(args)
  File "/devel/char-rnn-tensorflow/model.py", line 23, in __init__
    cell = cell_fn(args.rnn_size, state_is_tuple=True)
TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'
`

**Comment by tatatodd** [comment]
@mcr-ksh 

Here's the API documentation:
https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/GRUCell
https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/BasicRNNCell
https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/BasicLSTMCell

Note that only `BasicLSTMCell` has a `state_is_tuple` argument, the others don't.  And also note that the state_is_tuple=False behavior will soon be deprecated, and the default is True.  So you should change this line:
https://github.com/sherjilozair/char-rnn-tensorflow/blob/master/model.py#L23

From 
`cell = cell_fn(args.rnn_size, state_is_tuple=True)`
to
`cell = cell_fn(args.rnn_size)`

For future reference, please limit github issues to bugs or feature requests.  We don't have time to debug bugs in all user code, and there is a larger community on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) to read and answer such questions.  Thanks!
