### ISSUE TITLE
error while converting to tflite

### ISSUE THREAD

**Issue by mcl-uk** [tensorflow/tensorflow#79695]
Hello,
I'm trying to convert a tensorflow "saved model" to tflite format on a W11 PC with Python 3.12 and  tf v2.18.0.
The model I'm working with is this one:
https://github.com/tonytw1/squirrel-detector/tree/main/models/squirrelnet_ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/saved_model

I just get a barrage of incomprehensible error messages (after about 30s), see below.

Thanks for any help.

`**cvt = tf.lite.TFLiteConverter.from_saved_model('model_directory')
lm = cvt.convert()**

Traceback (most recent call last):
  File "<pyshell#11>", line 1, in <module>
    lm = cvt.convert()
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\lite\python\lite.py", line 1238, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\lite\python\lite.py", line 1190, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\lite\python\lite.py", line 1572, in convert
    return self._convert_from_saved_model(graph_def)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\lite\python\lite.py", line 1430, in _convert_from_saved_model
    result = _convert_saved_model(**converter_kwargs)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\lite\python\convert_phase.py", line 212, in wrapper
    raise converter_error from None  # Re-throws the exception.
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\lite\python\convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\lite\python\convert.py", line 1045, in convert_saved_model
    data = convert(
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\lite\python\convert.py", line 376, in convert
    raise converter_error
tensorflow.lite.python.convert_phase.ConverterError: Could not translate MLIR to FlatBuffer.<unknown>:0: error: loc(callsite(fused["StridedSlice:", "map/while/strided_slice@map_while_body_8032"] at callsite(callsite(fused["StatelessWhile:", "map/while@__inference_call_func_12016"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_14389"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]))): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: note: loc(callsite(callsite(fused["StatelessWhile:", "map/while@__inference_call_func_12016"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_14389"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): called from
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
<unknown>:0: note: loc(callsite(fused["StridedSlice:", "map/while/strided_slice@map_while_body_8032"] at callsite(callsite(fused["StatelessWhile:", "map/while@__inference_call_func_12016"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_14389"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]))): see current operation: %28 = "tf.StridedSlice"(%27, %14, %14, %13) <{begin_mask = 14 : i64, ellipsis_mask = 0 : i64, end_mask = 14 : i64, new_axis_mask = 1 : i64, shrink_axis_mask = 0 : i64}> {device = ""} : (tensor<?x?x3xf32>, tensor<4xi32>, tensor<4xi32>, tensor<4xi32>) -> tensor<1x?x?x3xf32>
<unknown>:0: note: loc(callsite(fused["StridedSlice:", "map/while/strided_slice@map_while_body_8032"] at callsite(callsite(fused["StatelessWhile:", "map/while@__inference_call_func_12016"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_14389"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]))): Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: loc(callsite(callsite(fused["StatelessWhile:", "map/while@__inference_call_func_12016"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_14389"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): failed while converting: 'map/while_body': 
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: StridedSlice
Details:
	tf.StridedSlice(tensor<?x?x3xf32>, tensor<4xi32>, tensor<4xi32>, tensor<4xi32>) -> (tensor<1x?x?x3xf32>) : {begin_mask = 14 : i64, device = "", ellipsis_mask = 0 : i64, end_mask = 14 : i64, new_axis_mask = 1 : i64, shrink_axis_mask = 0 : i64}

<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
<unknown>:0: note: loc(callsite(callsite(fused["StatelessWhile:", "map/while@__inference_call_func_12016"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_14389"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): see current operation: 
"func.func"() <{function_type = (tensor<i32>, tensor<i32>, tensor<?x320x320x3xf32>, tensor<?x3xi32>, tensor<1x?x?x3xui8>) -> (tensor<i32>, tensor<i32>, tensor<?x320x320x3xf32>, tensor<?x3xi32>, tensor<1x?x?x3xui8>), sym_name = "map/while_body", sym_visibility = "private"}> ({
^bb0(%arg0: tensor<i32>, %arg1: tensor<i32>, %arg2: tensor<?x320x320x3xf32>, %arg3: tensor<?x3xi32>, %arg4: tensor<1x?x?x3xui8>):
  %0 = "arith.constant"() <{value = dense<-1> : tensor<3xi32>}> : () -> tensor<3xi32>
  %1 = "arith.constant"() <{value = dense<0> : tensor<i32>}> : () -> tensor<i32>
  %2 = "arith.constant"() <{value = dense<1.000000e+00> : tensor<f32>}> : () -> tensor<f32>
  %3 = "arith.constant"() <{value = dense<0> : tensor<1xi32>}> : () -> tensor<1xi32>
  %4 = "arith.constant"() <{value = dense<0> : tensor<2xi32>}> : () -> tensor<2xi32>
  %5 = "arith.constant"() <{value = dense<-1> : tensor<1xi32>}> : () -> tensor<1xi32>
  %6 = "arith.constant"() <{value = dense<1> : tensor<1xi32>}> : () -> tensor<1xi32>
  %7 = "arith.constant"() <{value = dense<1> : tensor<i32>}> : () -> tensor<i32>
  %8 = "arith.constant"() <{value = dense<-1> : tensor<4xi32>}> : () -> tensor<4xi32>
  %9 = "arith.constant"() <{value = dense<0> : tensor<3xi32>}> : () -> tensor<3xi32>
  %10 = "arith.constant"() <{value = dense<[[320, 320, 3]]> : tensor<1x3xi32>}> : () -> tensor<1x3xi32>
  %11 = "arith.constant"() <{value = dense<-1> : tensor<2xi32>}> : () -> tensor<2xi32>
  %12 = "arith.constant"() <{value = dense<[1, 320, 320, 3]> : tensor<4xi32>}> : () -> tensor<4xi32>
  %13 = "arith.constant"() <{value = dense<1> : tensor<4xi32>}> : () -> tensor<4xi32>
  %14 = "arith.constant"() <{value = dense<0> : tensor<4xi32>}> : () -> tensor<4xi32>
  %15 = "arith.constant"() <{value = dense<0.00784313772> : tensor<f32>}> : () -> tensor<f32>
  %16 = "arith.constant"() <{value = dense<320> : tensor<2xi32>}> : () -> tensor<2xi32>
  %17 = "tfl.add"(%arg0, %7) <{fused_activation_function = "NONE"}> : (tensor<i32>, tensor<i32>) -> tensor<i32>
  %18 = "tfl.add"(%arg1, %7) <{fused_activation_function = "NONE"}> : (tensor<i32>, tensor<i32>) -> tensor<i32>
  %19 = "tfl.reshape"(%arg1, %6) : (tensor<i32>, tensor<1xi32>) -> tensor<1xi32>
  %20 = "tfl.concatenation"(%19, %5) <{axis = 0 : i32, fused_activation_function = "NONE"}> : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32>
  %21 = "tfl.slice"(%arg3, %4, %20) : (tensor<?x3xi32>, tensor<2xi32>, tensor<2xi32>) -> tensor<?x?xi32>
  %22 = "tfl.reshape"(%18, %6) : (tensor<i32>, tensor<1xi32>) -> tensor<1xi32>
  %23 = "tfl.concatenation"(%22, %3) <{axis = 0 : i32, fused_activation_function = "NONE"}> : (tensor<1xi32>, tensor<1xi32>) -> tensor<2xi32>
  %24 = "tfl.slice"(%arg3, %23, %11) : (tensor<?x3xi32>, tensor<2xi32>, tensor<2xi32>) -> tensor<?x3xi32>
  %25 = "tfl.concatenation"(%21, %10, %24) <{axis = 0 : i32, fused_activation_function = "NONE"}> : (tensor<?x?xi32>, tensor<1x3xi32>, tensor<?x3xi32>) -> tensor<?x3xi32>
  %26 = "tfl.gather"(%arg4, %arg1) <{axis = 0 : i32, batch_dims = 0 : i32}> : (tensor<1x?x?x3xui8>, tensor<i32>) -> tensor<?x?x3xui8>
  %27 = "tfl.cast"(%26) : (tensor<?x?x3xui8>) -> tensor<?x?x3xf32>
  %28 = "tf.StridedSlice"(%27, %14, %14, %13) <{begin_mask = 14 : i64, ellipsis_mask = 0 : i64, end_mask = 14 : i64, new_axis_mask = 1 : i64, shrink_axis_mask = 0 : i64}> {device = ""} : (tensor<?x?x3xf32>, tensor<4xi32>, tensor<4xi32>, tensor<4xi32>) -> tensor<1x?x?x3xf32>
  %29 = "tfl.mul"(%28, %15) <{fused_activation_function = "NONE"}> : (tensor<1x?x?x3xf32>, tensor<f32>) -> tensor<1x?x?x3xf32>
  %30 = "tfl.sub"(%29, %2) <{fused_activation_function = "NONE"}> : (tensor<1x?x?x3xf32>, tensor<f32>) -> tensor<1x?x?x3xf32>
  %31 = "tfl.unpack"(%30) <{axis = 0 : i32, num = 1 : i32}> : (tensor<1x?x?x3xf32>) -> tensor<?x?x3xf32>
  %32 = "tfl.expand_dims"(%31, %1) : (tensor<?x?x3xf32>, tensor<i32>) -> tensor<1x?x?x3xf32>
  %33 = "tfl.resize_bilinear"(%32, %16) <{align_corners = false, half_pixel_centers = false}> : (tensor<1x?x?x3xf32>, tensor<2xi32>) -> tensor<1x320x320x3xf32>
  %34 = "tfl.strided_slice"(%33, %14, %12, %13) <{begin_mask = 14 : i32, ellipsis_mask = 0 : i32, end_mask = 14 : i32, new_axis_mask = 0 : i32, offset = false, shrink_axis_mask = 1 : i32}> : (tensor<1x320x320x3xf32>, tensor<4xi32>, tensor<4xi32>, tensor<4xi32>) -> tensor<320x320x3xf32>
  %35 = "tfl.concatenation"(%19, %0) <{axis = 0 : i32, fused_activation_function = "NONE"}> : (tensor<1xi32>, tensor<3xi32>) -> tensor<4xi32>
  %36 = "tfl.slice"(%arg2, %14, %35) : (tensor<?x320x320x3xf32>, tensor<4xi32>, tensor<4xi32>) -> tensor<?x?x?x?xf32>
  %37 = "tfl.concatenation"(%22, %9) <{axis = 0 : i32, fused_activation_function = "NONE"}> : (tensor<1xi32>, tensor<3xi32>) -> tensor<4xi32>
  %38 = "tfl.slice"(%arg2, %37, %8) : (tensor<?x320x320x3xf32>, tensor<4xi32>, tensor<4xi32>) -> tensor<?x320x320x3xf32>
  %39 = "tfl.reshape"(%34, %12) : (tensor<320x320x3xf32>, tensor<4xi32>) -> tensor<1x320x320x3xf32>
  %40 = "tfl.concatenation"(%36, %39, %38) <{axis = 0 : i32, fused_activation_function = "NONE"}> : (tensor<?x?x?x?xf32>, tensor<1x320x320x3xf32>, tensor<?x320x320x3xf32>) -> tensor<?x320x320x3xf32>
  "func.return"(%17, %18, %40, %25, %arg4) : (tensor<i32>, tensor<i32>, tensor<?x320x320x3xf32>, tensor<?x3xi32>, tensor<1x?x?x3xui8>) -> ()
}) : () -> ()
`

**Comment by gaikwadrahul8** [comment]
Hi, @mcl-uk 

Thank you for bringing this issue to our attention, I am able to replicate the same behavior from my end, Here is [gist-file](https://colab.research.google.com/gist/gaikwadrahul8/dde5d27324d524bd7053340ef60d5429/tflite-issue-79695.ipynb) for reference

**Here is output error log for reference :**

```
---------------------------------------------------------------------------
ConverterError                            Traceback (most recent call last)
[<ipython-input-6-3c97b26abbb0>](https://localhost:8080/#) in <cell line: 2>()
      1 cvt = tf.lite.TFLiteConverter.from_saved_model(MODEL_PATH)
----> 2 lm = cvt.convert()

7 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/convert.py](https://localhost:8080/#) in convert(model_flags, conversion_flags, input_data_str, debug_info_str, enable_mlir_converter)
    374               enable_mlir_converter,
    375           )
--> 376       raise converter_error
    377 
    378   return _run_deprecated_conversion_binary(

ConverterError: Could not translate MLIR to FlatBuffer.<unknown>:0: error: loc(callsite(fused["StridedSlice:", "map/while/strided_slice@map_while_body_8032"] at callsite(callsite(fused["StatelessWhile:", "map/while@__inference_call_func_12016"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_14389"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]))): 'tf.StridedSlice' op is neither a custom op nor a flex op
<unknown>:0: note: loc(callsite(callsite(fused["StatelessWhile:", "map/while@__inference_call_func_12016"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_14389"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): called from
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
<unknown>:0: note: loc(callsite(fused["StridedSlice:", "map/while/strided_slice@map_while_body_8032"] at callsite(callsite(fused["StatelessWhile:", "map/while@__inference_call_func_12016"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_14389"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]))): Error code: ERROR_NEEDS_FLEX_OPS
<unknown>:0: error: loc(callsite(callsite(fused["StatelessWhile:", "map/while@__inference_call_func_12016"] at fused["StatefulPartitionedCall:", "StatefulPartitionedCall@__inference_signature_wrapper_14389"]) at fused["StatefulPartitionedCall:", "StatefulPartitionedCall"])): failed while converting: 'map/while_body': 
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: StridedSlice
Details:
	tf.StridedSlice(tensor<?x?x3xf32>, tensor<4xi32>, tensor<4xi32>, tensor<4xi32>) -> (tensor<1x?x?x3xf32>) : {begin_mask = 14 : i64, device = "", ellipsis_mask = 0 : i64, end_mask = 14 : i64, new_axis_mask = 1 : i64, shrink_axis_mask = 0 : i64}

<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
```
To fix this you need to tell the converter to include TensorFlow ops or Select TF Ops. This can be achieved by setting the target_spec.supported_ops attribute of the converter to include tf.lite.OpsSet.SELECT_TF_OPS along with tf.lite.OpsSet.TFLITE_BUILTINS.

1. `tf.lite.OpsSet.TFLITE_BUILTINS`: This includes the standard set of TensorFlow Lite operations.

2. `tf.lite.OpsSet.SELECT_TF_OPS`: This allows the converter to include TensorFlow operations that are not directly supported in TensorFlow Lite and in this case `tf.StridedSlice` Op does not have direct support in TensorFlow Lite ops so to enable the use of `tf.StridedSlice` Op so we added `tf.lite.OpsSet.SELECT_TF_OPS` during conversion

I have tried from my end and it seems like working as expected please refer second section of this [gist-file](https://colab.research.google.com/gist/gaikwadrahul8/75d334b77c0c50a4fc848d5b1067c500/tflite-issue-79695.ipynb) where I converted model to TFLite successfully.

Please give it try from your end and let me know is it working as expected or not ? if not please help me with error log to investigate this issue further from our end. 

Thank you for you cooperation and patience.

**Comment by mcl-uk** [comment]
Thanks for responding.
Taking on board your suggestions, my convert script now looks like:
`
import tensorflow as tf
cvt = tf.lite.TFLiteConverter.from_saved_model('model_dir')
cvt.target_spec.supported_ops.add(tf.lite.OpsSet.TFLITE_BUILTINS)
cvt.target_spec.supported_ops.add(tf.lite.OpsSet.SELECT_TF_OPS)
lm = cvt.convert()
`
However this again fails, now reporting:
`
Traceback (most recent call last):
  File "<pyshell#27>", line 1, in <module>
    lm = cvt.convert()
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\lite\python\lite.py", line 1238, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\lite\python\lite.py", line 1190, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\lite\python\lite.py", line 1572, in convert
    return self._convert_from_saved_model(graph_def)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\lite\python\lite.py", line 1430, in _convert_from_saved_model
    result = _convert_saved_model(**converter_kwargs)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\lite\python\convert_phase.py", line 215, in wrapper
    raise error from None  # Re-throws the exception.
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\lite\python\convert_phase.py", line 205, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\lite\python\convert.py", line 1044, in convert_saved_model
    conversion_flags = build_conversion_flags(**kwargs)
  File "C:\Users\Steve\AppData\Local\Programs\Python\Python312\Lib\site-packages\tensorflow\lite\python\convert.py", line 785, in build_conversion_flags
    conversion_flags.select_user_tf_ops.extend(select_user_tf_ops)
TypeError: bad argument type for built-in operation
`
I'd be most gratefull for any further assistance.

**Comment by mcl-uk** [comment]
Appologies, I have re-tried the script afresh and can confirm that it _does_ now work.
Thanks again for your help.
