### ISSUE TITLE
im2txt: W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for

### ISSUE THREAD

**Issue by hajrakomal** [tensorflow/tensorflow#7973]
When I run training script provided by im2txt show and tell model, when I run this script --input_file_pattern="${MSCOCO_DIR}/train-?????-of-00256"   --inception_checkpoint_file="${INCEPTION_CHECKPOINT}"   --train_dir="${MODEL_DIR}/train"   --train_inception=false   --number_of_steps=1000000

I get following error
can anyone help me with this please.....

INFO:tensorflow:Prefetching values from 256 files matching im2txt/data/new/train-?????-of-00256
WARNING:tensorflow:From /home/hajira/.local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py:344 in __init__.: __init__ (from tensorflow.python.training.summary_io) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.FileWriter. The interface and behavior is the same; this is just a rename.
INFO:tensorflow:Restoring Inception variables from checkpoint file 
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for 
W tensorflow/core/framework/op_kernel.cc:975] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for

**Comment by mrry** [comment]
At a guess, does it work if you change the flag

```
--inception_checkpoint_file="${INCEPTION_CHECKPOINT}"
```

...to add `./` at the beginning of the filename?

```
--inception_checkpoint_file="./${INCEPTION_CHECKPOINT}"
```

I think there's a fix for this pending, but /cc @rohan100jain to be sure!

**Comment by hajrakomal** [comment]
still not solved....

**Comment by mrry** [comment]
Actually, perhaps I'm overthinking this. The error message suggests that an empty filename is being passed to the `Saver.restore()` method. Perhaps there's a typo in `"${INCEPTION_CHECKPOINT}"`? Or a bug in the script that's taking the filename from a different flag? (I don't know what code you're running, so it's hard to guess at what the bug could be.)

**Comment by prb12** [comment]
This is most likely a tensorflow/models problem - seems to be running this code: https://github.com/tensorflow/models/tree/master/im2txt

@cshallue Could you please take a look at this?

**Comment by cshallue** [comment]
@hajrakomal I just ran the code and this did not happen. It looks like you're using an older version of TensorFlow and/or this repository. Can you please upgrade to TF1.0 and use the latest version of this repository and see if this issue still occurs?

**Comment by cshallue** [comment]
Closing this for now, because it seems to be fixed by upgrading to TF1.0. Please reopen if you continue to have issues.
