### ISSUE TITLE
 ModuleNotFoundError 

### ISSUE THREAD

**Issue by Harsha7226** [tensorflow/tensorflow#79750]
No module named 'tensorflow' when using from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
Environment: Describe your environment, including:

TensorFlow version ( 2.17.0, 2.18.0)
Python version (3.8.10)

ModuleNotFoundError: No module named 'tensorflow'
Expected Behavior: Should've imported the KerasClassifier from tensorflow.keras.wrappers.scikit_learn

**Comment by tilakrayal** [comment]
@Harsha7226,
Could please try to install scikeras using **pip install scikeras** and then import **from scikeras.wrappers import KerasClassifier**.  Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/4097395867f620c2b959411a613a413c/untitled2224.ipynb). Thank you!
