### ISSUE TITLE
Converting Tensor to ndarray

### ISSUE THREAD

**Issue by ebigelow** [tensorflow/tensorflow#798]
```
>>> a = tf.random_uniform((3,3))
>>> b = tf.tensor_util.MakeNdarray(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 414, in MakeNdarray
    shape = [d.size for d in tensor.tensor_shape.dim]
AttributeError: 'Tensor' object has no attribute 'tensor_shape'
```

It looks like `MakeNdarray` expects a `TensorProto` instead of a `Tensor`, so this works fine:

```
a = tf.tensor_util.make_tensor_proto([1,2,3])
```

Is there any way to convert a `Tensor` to a `TensorProto`? If not, is there any other way to convert a `Tensor` to an `ndarray`?

**Comment by vrv** [comment]
- I believe many of the functions in tensor_util are actually supposed to be private, so I probably would try to avoid using any function that's not currently publicly documented.

- In your code snippet, 'a' is really a symbolic tensor indicating that it will produce a random 3x3 matrix when evaluated in the context of a session, so to actually get its content, you need to 'eval' it, which will return a numpy array:

```
with tf.Session():
  a = tf.random_uniform((3, 3))
  b = a.eval()  # Runs to get the output of 'a' and converts it to a numpy array
```

**Comment by vrv** [comment]
Also, this type of question is better suited for StackOverflow -- you'll get better feedback / advice there.  Try to use github issues for bug reports / installation issues / feature requests.
