### ISSUE TITLE
tf.contrib.metrics.accuracy does not accept name

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#7986]
The `tf.contrib.metrics.accuracy` operation does not take in a name and instead is hardcoded to be `accuracy`:
https://github.com/tensorflow/tensorflow/blob/a230417c58c258b2417225c739a1e5f0890491e6/tensorflow/contrib/metrics/python/metrics/classification.py#L55

signature should be:
```
def accuracy(predictions, labels, weights=None, name=None):
```
and then:
```
with ops.name_scope(name, 'accuracy', values=[predictions, labels]):
```

**Comment by tatatodd** [comment]
Would you like to submit a PR to fix this?  We have limited manpower for tf.contrib, but definitely welcome contributions!  :)
