### ISSUE TITLE
"Download and Setup" link broken

### ISSUE THREAD

**Issue by purlvin** [tensorflow/tensorflow#7989]
In README file, the link of "Download and Setup" is pointing to _https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md_
However, it looks like that is broken now, please help fix, thanks~

"
Installation
See Download and Setup for instructions on how to install our release binaries or how to build from source.
"

**Comment by calpa** [comment]
I found that they moved the old folder to the new place.
The folder of g3doc is moved to docs_src, but I cannot find the os_setup.md in the folder...
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src/get_started

**Comment by purlvin** [comment]
@calpa thanks for the tips~
I think I have found the page.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/install/index.md

**Comment by gunan** [comment]
#7990 fixes this issue.

**Comment by tatatodd** [comment]
Closing this out.  Thanks for filing the bug @purlvin , and for the tips @calpa !
