### ISSUE TITLE
{Base,LocalCLI}DebugWrapperSession and SessionInterface don't have 'as_default'.

### ISSUE THREAD

**Issue by lemonzi** [tensorflow/tensorflow#7991]
I tried to use tfdbg to hunt those Infs, and it complained `LocalCLIDebugWrapperSession`  was lacking `as_default`, which I use to set the default session for each thread. Neither its parent class `BaseDebugWrapperSession` or the interface `SessionInterface` it implements seem to have it. I thought it was supposed to be a drop-in replacement, is this part of the design?

**Comment by tatatodd** [comment]
@lemonzi Thanks for filing the issue, and using tfdbg!

What version of TensorFlow are you using, and on which OS / architecture?

Assigning this to @caisq to follow up.

**Comment by lemonzi** [comment]
It's great to have so much tooling! :)

I'm on OSX 10.10, TensorFlow 1.0.0 without GPU from PyPi. I checked the relevant code on `master` when I submitted the issue and it appeared to be the same.

**Comment by caisq** [comment]
This should have already been fixed in master branch HEAD. Please see:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/debug/wrappers/framework.py#L378

The fix should become usable to external users on the next successful nightly build and/or the next release (r1.1).
