### ISSUE TITLE
Loading and re-training the model

### ISSUE THREAD

**Issue by prakhar21** [tensorflow/tensorflow#7994]
Hi, I am confused, if it is possible to load the last checkpoint for the model and now use another data to train the same model, so widen it's knowledge ?

Usecase: chatbot
data1: cornell-movie data
data2: stack exchange dataset

Firstlt, I had trained a seq2seq model on the cornell data, with some hyperparameters and other important variables, now i want my same model to train on other datasets also. Is this possible ?

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by sayakpaul** [comment]
Hi @prakhar21. Did you happen to find a way around on this? I am specifically interested in how could we perform the re-training part using the new [Save and Load](https://www.tensorflow.org/tutorials/keras/save_and_load) methodologies with Keras models.
