### ISSUE TITLE
Flex lib not linked on Android for C code on usage Select TensorFlow op(s)

### ISSUE THREAD

**Issue by koranten2** [tensorflow/tensorflow#79984]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tflight 2.16

### Custom code

Yes

### OS platform and distribution

Ubuntu 22.04, Android Studio

### Mobile device

Samsung S21, S10

### Current behavior?

I tried to launch my custom tflite model (with select_op) on Android Studio using C API. I tried both libtensorflowlite.so and libtensorflowlite_c.so built from source code using Bazel but got the same error.  I have linked the libtensorflowlite_flex.so in Cmake as below (build follow the https://www.tensorflow.org/lite/guide/ops_select).
But occurred this error:
_E/tflite: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select_

It looks that flex library was not applied therefore I provided some dubugging inside tflight library. As I could see the main function for Flex delegate initialization is  **AcquireFlexDelegate()**. It can be found both 
\tensorflow\tensorflow\lite\core\interpreter_builder.cc (Weak function version in tflight library) and 
\tensorflow\tensorflow\lite\delegates\flex\delegate_symbol.cc (Strong function version in flex library).

I also found correspondent symbols on **nm** command output
00000000050b53b8 T _ZN6tflite19AcquireFlexDelegateEv@@VERS_1.0  (libtensorflowlite_flex.so)
00000000003b8a4c W _ZN6tflite19AcquireFlexDelegateEv@@VERS_1.0  (libtensorflowlite.so)

As I understand from code for Android case weak linking mechanism should be used and  AcquireFlexDelegate() from libtensorflowlite_flex.so should be called instead of the same function from  libtensorflowlite.so. Correspondent code in \tensorflow\tensorflow\lite\core\interpreter_builder.cc:

___TfLiteStatus InterpreterBuilder::ApplyDelegates(Interpreter* interpreter) {_
  // Apply Flex delegate if applicable.
  if (has_flex_op_) {
    if (Interpreter::TfLiteDelegatePtr flex_delegate = **AcquireFlexDelegate())** {
...._

But on debugging I could see that  **ApplyDelegates()** from libtensorflowlite.so (in my case has_flex_op_ == true) is called and return trivial delegate. This is the reason of further error messages and crash as the function from flex library is not called.

On Ubuntu the same code works well but in this case ApplyDelegates() from libtensorflowlite.so is called and then flex lib is called clear by
_auto acquire_flex_delegate_func = reinterpret_cast<Interpreter::TfLiteDelegatePtr (*)()>(SharedLibrary::GetSymbol("TF_AcquireFlexDelegate"));_
Unfortunatelly, from code comments I see that this approach is not appropriate for Android as "TF_AcquireFlexDelegate" is not defined for this os.

Please, clarify me the write way of using flex lib in native C/C++ on Android using Cmake in Android Studio. Possibly my linking procedure is not fully correct in Cmake, or I wrongly understand the above workflow or some other reason.
I will be very grateful for answer!

### Standalone code to reproduce the issue

```shell
CMakeLists.txt:
...

include_directories(myapp INTERFACE
   ...
   "${TFLITE_INCLUDE_PATH}"
   "${TFLITE_THIRDPARTY_DIR}/flatbuffers/include"
   "${TFLITE_THIRDPARTY_DIR}/absl"
   ...
)

target_compile_options(myapp PRIVATE -Wno-deprecated-declarations)

target_link_libraries(myapp
        ...
        ${TFLITE_LIBRARY_DIR}/libtensorflowlite.so
        ${TFLITE_LIBRARY_DIR}/libtensorflowlite_gpu_delegate.so
        ...                        
)

add_library(TFLITE_FLEX SHARED IMPORTED)
set_target_properties(TFLITE_FLEX PROPERTIES IMPORTED_LOCATION ${TFLITE_LIBRARY_DIR2}/libtensorflowlite_flex.so)
target_link_libraries(myapp TFLITE_FLEX)
```

### Relevant log output

```shell
I/tflite: Created TensorFlow Lite XNNPACK delegate for CPU.
E/tflite: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select
E/tflite: Node number 12 (FlexTranspose) failed to prepare.
E/tflite: Select TensorFlow op(s), included in the given model, is(are) not supported by this interpreter. Make sure you apply/link the Flex delegate before inference. For the Android, it can be resolved by adding "org.tensorflow:tensorflow-lite-select-tf-ops" dependency. See instructions: https://www.tensorflow.org/lite/guide/ops_select
E/tflite: Node number 12 (FlexTranspose) failed to prepare.
E/: Error at .../cpp/detector.cc, bool seeso::Detector::buildInterpreter(), line 98
```

**Comment by gaikwadrahul8** [comment]
Hi, @koranten2

I apologize for the delayed response, You just need to make sure that `libtensorflow_flex.so` is linked in. It can be used in the same way as with C++ API. Just build https://www.tensorflow.org/lite/guide/ops_select#c and load it please refer this [TensorFlow Lite C++ minimal example](https://github.com/tensorflow/tensorflow/tree/v2.18.0/tensorflow/lite/examples/minimal) which may help you to solve your issue and If you're doing this in Bazel, adding `"//tensorflow/lite/delegates/flex:delegate"` to `"deps"` of the "minimal" cc_binary rule is the right approach that will instruct Bazel to build the flex delegate and then link it into the binary.

it's recommended to use `find_library()` to locate `libtensorflowlite_flex.so` similar to the example in the minimal `CMakeLists.txt` file

If I have missed something please let me know. 

Thank you for your cooperation and patience.

**Comment by koranten2** [comment]
Thank you alot for advice! Clearing my current cmake to make it minimal like  [TensorFlow Lite C++ minimal example](https://github.com/tensorflow/tensorflow/tree/v2.18.0/tensorflow/lite/examples/minimal) resolved the issue.
