### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by Bihaqo** [tensorflow/tensorflow#7999]
The "See Download and Setup" link in the readme is broken.

**Comment by ClarkZinzow** [comment]
Already an existing issue #7989 with a pull request that fixes the issue: #7990.  Just waiting for a CLA to be signed.

**Comment by tatatodd** [comment]
Thanks for filing the bug @Bihaqo , and thanks for the redirect @ClarkZinzow !

Closing this out.
