### ISSUE TITLE
Setting lower gcc version for cuda

### ISSUE THREAD

**Issue by kmatzen** [tensorflow/tensorflow#8]
gcc 4.10 and up are not supported for the required cuda toolkit.  How can I specify a different version of gcc to bazel?  I tried setting a new version with --compiler, but it reported that no toolchain was found.  Do I need to provide a CROSSTOOL file or is there an easier way?

**Comment by zheng-xq** [comment]
Could you try the docker-based installation for now? It should have the correct gcc version. 

http://tensorflow.org/get_started/os_setup.md#docker-based_installation

It is possible to modify the lower-level scripts to use a different gcc. But you will need to modify a few places in the source code to make that happen.

**Comment by zheng-xq** [comment]
In case you have any trouble with the docker flow, this is the place you can modify to use a different compiler with Cuda, although we don't currently have a more user-friendly way of doing that.

https://github.com/tensorflow/tensorflow/blob/master/third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc

CPU_COMPILER = ('/usr/bin/gcc')
NVCC_PATH = CURRENT_DIR + '/../../../cuda/bin/nvcc'
GCC_HOST_COMPILER_PATH = ('/usr/bin/gcc')
LLVM_HOST_COMPILER_PATH = ('/usr/bin/gcc')

**Comment by jontis** [comment]
I changed the required gcc version in CUDA before installing so I could use my system version.
Seems to have worked. There are rumors about possible problems but I've seen none so far.

https://www.udacity.com/wiki/cs344/troubleshoot-gcc47

**Comment by jontis** [comment]
Here are some other options for you:
https://stackoverflow.com/questions/6622454/cuda-incompatible-with-my-gcc-version
