### ISSUE TITLE
tensorboard gulp - analytics.js missing

### ISSUE THREAD

**Issue by graphific** [tensorflow/tensorflow#80]
installing frontend dependencies works fine from a clean ubuntu install:
npm install
bower install
tsd install

compiling all deps with gulp vulcanize throws an error however:

	[~/tensorflow/tensorflow/tensorboard]$ gulp vulcanize                                                                                                                             
	[07:29:48] Using gulpfile ~/tensorflow/tensorflow/tensorboard/gulpfile.js
	[07:29:48] Starting 'compile.all'...
	[07:29:48] Starting 'tslint-strict'...
	[07:29:51] Finished 'tslint-strict' after 3.24 s
	[07:29:53] Finished 'compile.all' after 5.34 s
	[07:29:53] Starting 'vulcanize'...
	[07:29:53] Finished 'vulcanize' after 6.08 ms
	ERROR finding /home/ubuntu/tensorflow/tensorflow/tensorboard/lib/js/analytics.js

not a huge problem as the frontend works just fine with _gulp server_

**Comment by mk01github** [comment]
Any update yet ??? I have same issue

**Comment by danmane** [comment]
For a temporary fix, remove the "lib/analytics.js" line from the top of app/index.html and `gulp vulcanize` will work fine. That said, I haven't actually tested the open-source build of the TensorBoard frontend so you might run into other problems. I'll test it out and comment back once I have a first class solution on the way.

**Comment by danmane** [comment]
Note by the way, you don't need to use gulp at all, unless you are recompiling the TensorBoard frontend from source.

**Comment by graphific** [comment]
@danmane ive been testing the tensorboard release quite a bit and it seems to be all working well. events, images, graph and histogram all good! :)

**Comment by danmane** [comment]
glad to hear it :)

**Comment by mk01github** [comment]
Thanks @danmane that worked. :)

**Comment by danmane** [comment]
We've fixed this :)
