### ISSUE TITLE
Android Camera Detection with Yolo model not working

### ISSUE THREAD

**Issue by johny130** [tensorflow/tensorflow#8000]
I trained and generated my yolo model accodring to the repository https://github.com/thtrieu/darkflow. While testing on few images locally, the model detects objects.

Once I build and test it on the phone (adding .pb to assets and setting flag to YOLO), TFDetect runs but I obtain no detections at all.

What could be the cause of that and how could I actually start debugging?

(trying to run the default graph-tiny-yolo-voc.pb specified in the example demo, succeeded)

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
