### ISSUE TITLE
 load model package in a linux tensorflow project

### ISSUE THREAD

**Issue by ttjs8423219** [tensorflow/tensorflow#8002]
![model](https://cloud.githubusercontent.com/assets/17719977/23498012/a391d9e4-ff60-11e6-895b-5aeb167d612d.png)
Hello,master:
      How do I load models package in a linux tensorflow project that has already been installed?thanks！

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by ttjs8423219** [comment]
all right!thanks!
