### ISSUE TITLE
Not support i686?

### ISSUE THREAD

**Issue by bfbd888** [tensorflow/tensorflow#8012]
Install from source.

 git rev-parse HEAD
`8cac382a5425d64f3083cb5adec525baa163e18e`

 bazel version
```
Build label: 0.4.4- (@non-git)
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 2 08:11:08 2017 (1488442268)
Build timestamp: 1488442268
Build timestamp as int: 1488442268
```

./configure
Please specify the location of python. [Default is /env/tensorflow/bin/python]:
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:
Do you wish to use jemalloc as the malloc implementation? [Y/n]
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N]
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N]
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /env/tensorflow/lib/python3.5/site-packages
Please input the desired Python library path to use.  Default is [/env/tensorflow/lib/python3.5/site-packages]

Using python library path: /env/tensorflow/lib/python3.5/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N]
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N]
No CUDA support will be enabled for TensorFlow
Configuration finished

.
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
..................................
ERROR: /prj/tmp/tensorflow/tensorflow/core/distributed_runtime/rpc/BUILD:321:1: no such package '@grpc//': Error downloading [http://bazel-mirror.storage.googleapis.com/github.com/grpc/grpc/archive/d7ff4ff40071d2b486a052183e3e9f9382afb745.tar.gz, https://github.com/grpc/grpc/archive/d7ff4ff40071d2b486a052183e3e9f9382afb745.tar.gz] to /root/.cache/bazel/_bazel_root/3dd36c466b8b5ba9ee6025155ebdf4cb/external/grpc/d7ff4ff40071d2b486a052183e3e9f9382afb745.tar.gz: Connection reset and referenced by '//tensorflow/core/distributed_runtime/rpc:grpc_testlib_server'.
ERROR: /prj/tmp/tensorflow/third_party/eigen3/BUILD:20:1: no such package '@eigen_archive//': Error downloading [http://bazel-mirror.storage.googleapis.com/bitbucket.org/eigen/eigen/get/290bfb42684a.tar.gz, https://bitbucket.org/eigen/eigen/get/290bfb42684a.tar.gz] to /root/.cache/bazel/_bazel_root/3dd36c466b8b5ba9ee6025155ebdf4cb/external/eigen_archive/290bfb42684a.tar.gz: Tried to reconnect at offset 498,992 but server didn't support it and referenced by '//third_party/eigen3:eigen3'.
ERROR: Evaluation of query "deps(((//tensorflow/... - //tensorflow/contrib/nccl/...) - //tensorflow/examples/android/...))" failed: errors were encountered while computing transitive closure.

**Comment by bfbd888** [comment]
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
ERROR: /prj/tmp/tensorflow/tensorflow/tools/pip_package/BUILD:77:1: no such package '@eigen_archive//': Error downloading [http://bazel-mirror.storage.googleapis.com/bitbucket.org/eigen/eigen/get/290bfb42684a.tar.gz, https://bitbucket.org/eigen/eigen/get/290bfb42684a.tar.gz] to /root/.cache/bazel/_bazel_root/3dd36c466b8b5ba9ee6025155ebdf4cb/external/eigen_archive/290bfb42684a.tar.gz: Tried to reconnect at offset 1,297,437 but server didn't support it and referenced by '//tensorflow/tools/pip_package:licenses'.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
INFO: Elapsed time: 92.479s

**Comment by tatatodd** [comment]
@bfbd888 I think this like indicates a network issue:

```
Error downloading [http://bazel-mirror.storage.googleapis.com/github.com/grpc/grpc/archive/d7ff4ff40071d2b486a052183e3e9f9382afb745.tar.gz, https://github.com/grpc/grpc/archive/d7ff4ff40071d2b486a052183e3e9f9382afb745.tar.gz] to /root/.cache/bazel/_bazel_root/3dd36c466b8b5ba9ee6025155ebdf4cb/external/grpc/d7ff4ff40071d2b486a052183e3e9f9382afb745.tar.gz: Connection reset and referenced by '//tensorflow/core/distributed_runtime/rpc:grpc_testlib_server'.
```

Make sure you're connected to the internet?

**Comment by bfbd888** [comment]
If it's network error, I think it is because I'm in china.
thanks very much.

**Comment by tatatodd** [comment]
OK, feel free to open a new issue if you have a new problem.  Thanks!
