### ISSUE TITLE
404 in contrib.layers documentation

### ISSUE THREAD

**Issue by Mec-iS** [tensorflow/tensorflow#8014]
In the official doc for version 1.0, [this link](https://www.tensorflow.org/api_docs/python/tf/contrib/layers/linear) to **tf.contrib.layers.linear** in [here](https://www.tensorflow.org/api_guides/python/contrib.layers) leads to a 404.

**Comment by ClarkZinzow** [comment]
That `tf.contrib.layers.linear` link should probably just be removed.  There are no op links for the other activation function aliases (partial objects), `tf.contrib.layers.relu` or `tf.contrib.layers.relu6`, on the Python API Guides page.  I can remove the `@{tf.contrib.layers.linear}` line from the [`docs_src` file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/api_guides/python/contrib.layers.md) and submit a pull request, but I think that I might first check that all other `@{}` links work (at least on the `tf.contrib.layers` page.)

**Comment by tatatodd** [comment]
Thanks for filing the issue @Mec-iS , and thanks for the analysis @ClarkZinzow !

I'm closing this out, since #8029 covers this as well.
