### ISSUE TITLE
C++ demo failed with lib in the makefile project

### ISSUE THREAD

**Issue by chenleo** [tensorflow/tensorflow#8016]
I can not build and run the demo on the C++ API page:

https://www.tensorflow.org/api_guides/cc/guide

When link to the lib built in the /contrib/makefile project, does that mean that the cc/ops are totally not supported or I missed some steps or information?

Current errors are as the following:

```
../../../../Git/tensorflow/bazel-out/local-fastbuild/genfiles/tensorflow/cc/ops/array_ops.h:24:57: error: no type named 'Input' in namespace 'tensorflow::ops'; did you mean simply 'Input'?
  BatchMatrixBandPart(const ::tensorflow::Scope& scope, ::tensorflow::ops::Input
                                                        ^~~~~~~~~~~~~~~~~~~~~~~~
                                                        Input
```

**Comment by tatatodd** [comment]
@chenleo What version of TensorFlow are you using?  Sounds like a version mismatch.

**Comment by chenleo** [comment]
I used the master rep version. despite from that, I did not found the correspond /cc folder locates in bazel-out/local-fastbuild/genfiles/tensorflow/cc, in the makefile project, (I think is somewhere like gen/host_obj/tensorflow/), which leads me to think that the ops namespace is not supported.

**Comment by tatatodd** [comment]
Perhaps @josh11b might know.

**Comment by girving** [comment]
Assigning to @petewarden because makefiles.

**Comment by petewarden** [comment]
The generated C++ op interfaces are not built by the mobile build systems, either using Bazel or Makefiles. That means that the CC examples won't run unfortunately.
