### ISSUE TITLE
[Windows - Bazel] ERROR: No toolchain found for cpu 'x64_windows'

### ISSUE THREAD

**Issue by Carmezim** [tensorflow/tensorflow#8019]
It is more probable to be something related to Bazel but I am posting here as well just in case.  

Windows 10 x64
Msys2 v20160205
Bazel 0.4.3 (tested with 0.4.4 as well)
Visual C++ 2015

I get this error when building with Bazel after successfully configuring TensorFlow 
```
$ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
ERROR: No toolchain found for cpu 'x64_windows'. Valid cpus are: [
  k8,
  piii,
  arm,
  darwin,
  ppc,
].
INFO: Elapsed time: 24.952s
```

#### Steps to reproduce:
- Compile Bazel or use a pre-built binary (both yielded same result)
- Clone TensorFlow repository
- Configure TensorFlow
- Build it with bazel

#### I tried so far as suggested:

- Configuring again and build ([entire log](https://github.com/bazelbuild/bazel/issues/2594#issuecomment-283073027)) using:
```
export BUILD_OPTS='--cpu=x64_windows_msvc --host_cpu=x64_windows_msvc --copt=/w --verbose_failures --experimental_ui'
bazel build -c opt $BUILD_OPTS tensorflow/tools/pip_package:build_pip_package
```

- Using `-c opt` instead of `--config=cuda`.

- Running without `--config=cuda`, which generates the error:
 `AssertionError: Could not find python binary: python3.exe` perhaps related to [Bazel issue 2457](https://github.com/bazelbuild/bazel/issues/2457).

[Issue on Bazel](https://github.com/bazelbuild/bazel/issues/2594).

**Comment by tatatodd** [comment]
@Carmezim It looks like the right folks are involved on your Bazel issue.

I'm closing this out for now; if you feel I've made a mistake, respond to this issue and I'll re-open.  Thanks!

**Comment by coldgemini** [comment]
same issue
