### ISSUE TITLE
AttributeError: 'ExponentialMovingAverage' object has no attribute 'variables_to_restore'

### ISSUE THREAD

**Issue by carlos-argueta** [tensorflow/tensorflow#802]
I am running the code provided with the tutorial Convolutional Neural Networks https://www.tensorflow.org/versions/master/tutorials/deep_cnn/index.html 

The training works fine, but when I run the evaluation I get the following error. I have not modified in any way the code, I am running it as is.

Code snippet:
...
# Restore the moving average version of the learned variables for eval.
    variable_averages = tf.train.ExponentialMovingAverage(
        cifar10.MOVING_AVERAGE_DECAY)
    variables_to_restore = variable_averages.variables_to_restore()
    saver = tf.train.Saver(variables_to_restore)
...

Error:

Traceback (most recent call last):
  File "cifar10_eval.py", line 161, in <module>
    tf.app.run()
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "cifar10_eval.py", line 157, in main
    evaluate()
  File "cifar10_eval.py", line 135, in evaluate
    variables_to_restore = variable_averages.variables_to_restore()
AttributeError: 'ExponentialMovingAverage' object has no attribute 'variables_to_restore'

Please help,

**Comment by manucarbonell** [comment]
I get the same error, I think that they have changed something on the code moving_averages.py code

**Comment by aymericdamien** [comment]
What is your tensorflow version? You might need master branch version of tensorflow to make that script running. (In 0.6.0, ExponentialMovingAverage has no attributes variables_to_restore, but master version has it.)

**Comment by manucarbonell** [comment]
Yes it was version 0.6 as it says in the download section of tensorflow,
but i don't know how to install the master version as a package, should I
download the github repository on the library folder (
   /Library/Python/2.7/site-packages/tensorflow/...) ?
Thanks a lot,
Manu

**Comment by habrman** [comment]
I have the same problem (also used v. 0.6.0). Following the instructions for "Installing from sources" should make it install the latest version from the master branch.
https://www.tensorflow.org/versions/master/get_started/os_setup.html

**Comment by manucarbonell** [comment]
After @aymericdamien recommendation I have copied the tensorflow folder with all the training scripts from master version (downloaded from github) into 0.6 (installed version, which is different) and now cifar10_eval goes a bit further, it doesn't say that 'ExponentialMovingAverage' object has no attribute 'variables_to_restore' but once in the variables to restore called function it says
AttributeError: 'module' object has no attribute 'moving_average_variables'
Any ideas?

**Comment by josh11b** [comment]
Sherry, this looks related to 110808120	or 110781462.

**Comment by vrv** [comment]
If you're using the 0.6.0 pip installation, you should check out the code at the 0.6.0 branch.  There's no guarantee that the scripts at HEAD will work with the old binaries, since we add features to HEAD and then update our examples.

**Comment by carlos-argueta** [comment]
I have downloaded the master version from github just like @manucarbonell did. I am using a virtualenv called tf. If I don't activate the tf I keep on getting the original error. If I activate tf I get the following. Please advice.

(tf)Carloss-MacBook-Pro:~ Carlos$ python ~/../../Volumes/Transcend/Dropbox/workspace/TensorFlow/CIFAR10/tensorflow-master-tensorflow-models-image-cifar10/cifar10_train.py 
Traceback (most recent call last):
  File "/Users/Carlos/../../Volumes/Transcend/Dropbox/workspace/TensorFlow/CIFAR10/tensorflow-master-tensorflow-models-image-cifar10/cifar10_train.py", line 43, in <module>
    import tensorflow.python.platform
  File "/Users/Carlos/.virtualenvs/tf/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Users/Carlos/.virtualenvs/tf/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 43, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/Carlos/.virtualenvs/tf/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.core.framework.graph_pb2 import *
ImportError: No module named core.framework.graph_pb2


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

**Comment by manucarbonell** [comment]
I managed to run the example successfully again after using the version 0.6.0, which doesn't have the line
"variables_to_restore = variable_averages.variables_to_restore()"
in cifar10_eval
 
Thanks to the moderators!

**Comment by amisios** [comment]
Manu, could you elaborate a bit on how you solved this problem?

**Comment by jguiraudet** [comment]
The commit 64f8a3b0dc54b6125ad0ea94d0959b175b3eaad1  introduced a change in the API by adding the variables_to_restore() function.

You need to get the source code 0.6.0 of the example to run this example:

```bash
git clone https://github.com/tensorflow/tensorflow.git
git checkout 0.6.0
cd tensorflow/tensorflow/models/image/cifar10/
python cifar10_train.py --max_steps=20                   # Just a few steps to check the script
python cifar10_eval.py --num_examples 1000 --run_once 1  # Just once to check the script
```

**Comment by amisios** [comment]
Thanks for the answer. I found the 0.6.0 tutorial and it works. (while still producing the big number of warnings and errors about the queues. Same as in  #389 . It is something related to the threads but it takes place after the computation is complete).

**Comment by sherrym** [comment]
This should have long been fixed now that both the code and pip package containing this change has been available for several months.
