### ISSUE TITLE
pywrap_tensorflow.list_devices() allocates all available memory (on all GPU devices)

### ISSUE THREAD

**Issue by garibarba** [tensorflow/tensorflow#8021]
### Environment info
Operating System:
Ubuntu 14.04.5 LTS
Python 3.4.3

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
libcudadevrt.a  libcudart.so.8.0     libcudart_static.a  libcudnn.so.5      libcudnn_static.a
libcudart.so    libcudart.so.8.0.61  libcudnn.so         libcudnn.so.5.1.5

If installed from binary pip package, provide:

1. A link to the pip package you installed:
`pip install tensorflow-gpu`
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
```
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
1.0.0
```

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
```
from tensorflow.python import pywrap_tensorflow
pywrap_tensorflow.list_devices()
```

I have tried this locally on a system with two Quadro K620 and another system with one TITAN X.

**Comment by yaroslavvb** [comment]
That's a known (mis)feature -- TensorFlow will all memory on all devices unless you set `CUDA_VISIBLE_DEVICES`

**Comment by garibarba** [comment]
Doesn't happen if this runs first:
```
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333, allow_growth=True)
sess = tf.Session(config=tf.ConfigProto(gpu_options=gpu_options))
```

**Comment by tatatodd** [comment]
@garibarba I'm glad you discovered `tf.GPUOptions`, and thanks for filing an issue!

Here's documentation on why TensorFlow allocates all GPU memory up-front, by default, and other GPU-related information:
https://www.tensorflow.org/tutorials/using_gpu#allowing_gpu_memory_growth

So basically this is working-as-intended.  Closing this out.

**Comment by yaroslavvb** [comment]
PS, this is a sign of missing functionality in TensorFlow - there's no stand-alone way to configure some process-global settings, such as GPU Allocator and Eigen threadpool. Instead they get configured based on ConfigProto passed to the first tf.Session() call. This is a bit confusing -- first tf.Session() call and second tf.Session can get different values, and it seems right now the second set of values is ignored. @mrry

**Comment by tatatodd** [comment]
That's a good point @yaroslavvb.  Can you file a new issue for that?  Thanks!

**Comment by yaroslavvb** [comment]
Filed https://github.com/tensorflow/tensorflow/issues/8136
