### ISSUE TITLE
ADD to CONTRIB: single_image_random_do_stereograms for data analysis

### ISSUE THREAD

**Issue by Mazecreator** [tensorflow/tensorflow#8022]
I have written a TensorFlow OP "single_image_random_dot_stereograms" which takes a 2 D array with Z values and outputs a Stereogram image for use in "encode_png/jpg".  

it is based upon this paper:
http://www.learningace.com/doc/4331582/b6ab058d1e206d68ab60e4e1ead2fe6e/sirds-paper

I am sure this can be used to output data to TensorBoard as well but haven't tried that yet.

I would like to offer to add this as a contrib for TensorFlow and would like some advice if there is interest on getting the process started.  Right now I compile it into the "user_ops" section, but think it needs to move for contrib.

Basically, this helps display 3D data without hidden lines like a "waterfall" plot.

Here is the basic code as a demo:

    img=[[1,2,3,3,2,1],
         [1,2,3,4,5,2],
         [1,2,3,4,5,3],
         [1,2,3,4,5,4],
         [6,5,4,4,5,5]]

    session = tf.InteractiveSession()

    sirds = single_image_random_dot_stereograms(img,convergence_dots_size=8,number_colors=256,normalize=True)

    out = sirds.eval()

    png = tf.image.encode_png(out).eval()

    with open('picture_out.png', 'wb') as f:
        f.write(png)

The output image then looks like the attached image.  If you can view this image outside of github it will look better.  Try to look beyond the picture so the 2 dots at the bottom appear to be 3 dots.  The image should then converge and see the shape as described in "img" above.
![picture_out](https://cloud.githubusercontent.com/assets/18412448/23521590/a2deb0fc-ff4d-11e6-9dfc-b00759f921c8.png)

If there is interest, I can breakup the code to better match one of the contrib subdirectories and start a pull request.

Here is a different image, inverted cone, windowed in full color.
![picture_out_color_cone](https://cloud.githubusercontent.com/assets/18412448/23529957/a4737112-ff6d-11e6-8d35-dbdd29049edf.png)

**Comment by tatatodd** [comment]
Very cool stuff @Mazecreator , thanks for sharing!

@martinwicke Can you give some advice on whether this should go into contrib, or what other options there might be?  Thanks!

**Comment by martinwicke** [comment]
contrib is the right place I'd say.

**Comment by Mazecreator** [comment]
Sounds good, how about adding it to the "/contrib/image/" section?  I can add it into this directory, there is a few ops there already.

If this is okay, I will work on getting a pull request together over the next few days so you have something to look at.

**Comment by martinwicke** [comment]
That is the perfect location. Please send a PR.

**Comment by Mazecreator** [comment]
3rd times a charm.

I have created a quick overview of the Op here:
https://github.com/Mazecreator/TensorFlow-SIRDS

**Comment by girving** [comment]
Seems fixed.
