### ISSUE TITLE
logger dublication

### ISSUE THREAD

**Issue by agniszczotka** [tensorflow/tensorflow#8023]
When basicConfig() from logging (python 2.7.11) is used, tensorflow duplicates output of logger (load logger twice).

Example code and output:
```
from logging import basicConfig
import tensorflow as tf
from tensorflow.contrib.learn import Estimator

basicConfig()
tf.logging.set_verbosity(tf.logging.INFO)

def cnn_model_fn(features,labels,mode):
    pass

if __name__ == '__main__':
    classifier = Estimator(
        model_fn=cnn_model_fn)



```

output: 
WARNING:tensorflow:Using temporary folder as model directory: /var/folders/qn/z_b3zdss1g730kn_mlrwcwnc0000gn/T/tmpEdygBY
WARNING:tensorflow:Using temporary folder as model directory: /var/folders/qn/z_b3zdss1g730kn_mlrwcwnc0000gn/T/tmpEdygBY
INFO:tensorflow:Using default config.
INFO:tensorflow:Using default config.

**Comment by tatatodd** [comment]
I believe this is working-as-intended.

Here's the python documentation for `logging.basicConfig`
https://docs.python.org/2/library/logging.html#logging.basicConfig

> Does basic configuration for the logging system by creating a StreamHandler with a default Formatter and adding it to the root logger.

By calling `logging.basicConfig`, you're adding a StreamHandler to the root logger in python.  Note that `tf.logging` adds its own StreamHandler to its logger.  So now each log line will be sent to two streams, causing the duplication.

For reference, here's the code for tf.logging
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/tf_logging.py

I'm closing this out.  If you feel I'm mistaken, respond to this issue and I'll re-open.
