### ISSUE TITLE
Why does TensorBoard's Trace Viewer show blank waiting times?

### ISSUE THREAD

**Issue by nanzh-19** [tensorflow/tensorflow#80231]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.15

### Custom code

Yes

### Current behavior?

I ran the program on an x86 machine using oneDNN as the backend library and on an ARM machine using the default library. The TensorBoard profiling data shows blank waiting times on the ARM machine, while the computations on the x86 machine are very continuous. I am currently optimizing performance on the ARM machine and would like to understand the reasons behind the blank times in TensorBoard’s Trace Viewer on the ARM machine.

The TensorBoard data on the ARM machine shows a waiting gap before the two FusedMatmul operations.
![image](https://github.com/user-attachments/assets/f56d2028-11f5-43e5-ba17-547661f1627a)

computations on the x86 machine are very continuous
![image](https://github.com/user-attachments/assets/c8d6ed2d-0c2c-4d80-b23c-fdbce31d6f9f)

### Standalone code to reproduce the issue

```shell
I would like to know the reason for the waiting gap and how to resolve it. One hypothesis is that oneDNN uses asynchronous computation, while the default uses synchronous
```

**Comment by Venkat6871** [comment]
Hi **@nanzh-19** ,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!

**Comment by nanzh-19** [comment]
I am running an inference service on the CPU, and the model is a typical recommendation model. I would like to understand how these blank times appear, and what exactly 'idle' means in TensorFlow.

**Comment by gaikwadrahul8** [comment]
Hi, @nanzh-19 

I apologize for the delayed response, As far I know there might be architectural differences ARM's RISC architecture exhibits different computational characteristics compared to x86 CISC architecture and unique instruction processing and cache coherency mechanisms.

It may be synchronization overhead like varied memory synchronization strategies, additional latency in thread and resource coordination, differences between oneDNN and default TensorFlow backend implementations

Could you please try below some performance optimization strategies if you have not tried yet ? I would suggest you to please refer this official documentation of [Optimize TensorFlow performance using the Profiler](https://www.tensorflow.org/guide/profiler#trace_viewer) and [Debug the performance of one GPU](https://www.tensorflow.org/guide/gpu_performance_analysis) 

In the context of GPU performance and training steps, `idle` refers to a state where the GPU is not actively performing computational work despite being available and powered on.
  
```
import tensorflow as tf
import os

# Optimize TensorFlow performance for ARM
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '1'
os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'

# Threading and parallelism configuration
tf.config.threading.set_intra_op_parallelism_threads(0)
tf.config.threading.set_inter_op_parallelism_threads(0)

# Enable XLA compilation
tf.config.optimizer.set_jit(True)
```

If I have missed something here please let me know. Thank you for your cooperation and patience.
