### ISSUE TITLE
Code Readability in Keras Models

### ISSUE THREAD

**Issue by mrqsmar** [tensorflow/tensorflow#80282]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.8

### Custom code

Yes

### Current behavior?

I examined code in the Kera's model and was wondering if the code can be cleaned up. I noticed that lines 128-213 was very large, and is showing a massive function surrounded by other small functions. Could we break this up into smaller functions?

### Standalone code to reproduce the issue

```shell
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/models.py to show the code. Please refer to lines 128-213.
```

**Comment by Venkat6871** [comment]
Hi **@mrqsmar** ,
Thank you for raising your concern here. Yes, we can break large functions into smaller ones as needed. Feel free to do so in whatever way works best for you.
Thank you!

**Comment by mrqsmar** [comment]
Hello, I have written the code and make a pull request
