### ISSUE TITLE
Multiple broken g3doc links

### ISSUE THREAD

**Issue by ClarkZinzow** [tensorflow/tensorflow#8029]
There are, by my count, at least 20 broken g3doc links scattered among documentation, code, and build scripts caused by [this commit](https://github.com/tensorflow/tensorflow/commit/1c707ac780313f48a6733dc3beedf4b8a2b3df77) migrating g3docs to the docs_src + source code documentation generating system.  So far, in relation to this, the following issues have been opened: #8014, #7999, #7989, and the following pull requests have been made: #8018, #7990, #7965.  Two of the pull requests, #8018 and #7990, take care of the two broken links on the core TensorFlow README and are waiting on the signing of CLAs.

Due to the restructuring that took place in the transition from g3doc to docs_src, a simple find-replace won't work.  For example, in reference to [this line in fully-connected-reader.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/how_tos/reading_data/fully_connected_reader.py#L20), `tensorflow/g3doc/how_tos/reading_data.md#reading-from-files` would have to be changed to `tensorflow/docs_src/programmers_guide/reading_data.md#reading-from-files`.  In fact, according to the new reference syntax, it should be changed to `@{$reading_data#reading-from-files}`.

Moreover, some g3doc files that are still linked to by existing documentation no longer exist in this repository.  E.g., the [adding an op](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/extend/adding_an_op.md) extension guide links to many of the Python files contained in [this g3doc folder](https://github.com/tensorflow/tensorflow/tree/8120e2a270c28e0a62b9f522164b196a90f113b7/tensorflow/g3doc/how_tos/adding_an_op) (which has now been deleted.)  Although these Python files should probably be reinstated somewhere, this appears to be the only collection of Python files in g3doc that were deleted and are still needed.

So, how best to go about fixing these issues?  Manually fix each broken link in a single pull request?  And where should the [Python files](https://github.com/tensorflow/tensorflow/tree/8120e2a270c28e0a62b9f522164b196a90f113b7/tensorflow/g3doc/how_tos/adding_an_op) pertaining to the [adding an op](https://www.tensorflow.org/extend/adding_an_op) extension guide be placed?

**Comment by tatatodd** [comment]
Thanks for filing the detailed issue @ClarkZinzow !

@xmbrst @dr4b Can you guys take a look?

**Comment by wolffg** [comment]
Hi!  We are still updating the documentation about how to contribute documentation, but for now:

1. To fix docs in docs_src, a set of PRs of reasonable sizes that contains a few related files would be good---one PR per error is probably overkill, but one huge PR might be hard to review.

2. The support code files for Adding an Op should be re-added, but we will add it to the tensorflow/examples directory and update the links.  We will do this.

Thanks!

**Comment by ClarkZinzow** [comment]
Thanks @tatatodd for the labeling and assigning, and thanks @wolffg for the info.  For docs_src fixes, I'll limit the domain of each pull request to sibling files (should provide the right level of granularity for the pull requests; let me know if you think this is too coarse-grained) and I'll let the Adding an Op code files be.  It appears that the latter is starting to get attention: #8044.

I'm hoping to provide consistent useful contributions to TensorFlow, both via bug fixes and feature additions, once I feel very comfortable with the code base.  In the meantime, I thought that fixing documentation errors and other minor issues would be a good way to help out!

**Comment by dr4b** [comment]
BTW, is this bug still relevant?  I think a lot of these issues got fixed over the months as we solidified the parameterized link process?
