### ISSUE TITLE
tflite int8 export is twice as large as saved_model.pb

### ISSUE THREAD

**Issue by ssdv1** [tensorflow/tensorflow#80319]
### 1. System information

Windows 11

### 2. Code

import tensorflow as tf

saved_model_dir = "C:/Users/s/Downloads/best (1)_saved_model"

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)

converter.optimizations = [tf.lite.Optimize.DEFAULT]

def representative_dataset_gen():
    for _ in range(100): 
        yield [tf.random.normal([1, 640, 640, 3])]

converter.representative_dataset = representative_dataset_gen

converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]

converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8

tflite_model = converter.convert()

tflite_model_path = "model_int8.tflite"
with open(tflite_model_path, "wb") as f:
    f.write(tflite_model)

![Screenshot 2024-11-19 231208](https://github.com/user-attachments/assets/a0e58c94-6bb3-4335-bc7f-e591efb18e49)

**Comment by gaikwadrahul8** [comment]
Hi, @ssdv1 
Thank you for bringing this issue to our attention, if possible could you please help us with your saved_model along with Google colab notebook which you used to create saved_model also to replicate the similar behavior from our end ? 

Thank you for your cooperation and patience.

**Comment by gaikwadrahul8** [comment]
Hi, @ssdv1 
I do not have access to your shared files please provide me access. Thank you

**Comment by gaikwadrahul8** [comment]
Hi, @ssdv1 
I apologize for the delayed response, I was trying to replicate the similar behavior from my end while converting **saved_model** to **TFLite** I'm getting this error message` ValueError: Only support at least one signature key.` w.r.t signature so I tried most common default signature but still it's not converting **saved_model** to **TFLite** so please refer this [gist-file](https://colab.research.google.com/gist/gaikwadrahul8/5c48e7b77a204557824798277dc0c61a/copy-of-test-80319.ipynb) If I'm doing something wrong please let me know that will be greatly appreciated to replicate same behavior which you mentioned in issue template.

Thank you for your cooperation and patience.

**Comment by gaikwadrahul8** [comment]
Hi, @ssdv1
I apologize for the delayed response, I tried downgrading the TensorFlow version in Google colab but still I'm getting the same error message `ValueError: Only support at least one signature key.` here is [gist-file](https://colab.research.google.com/gist/gaikwadrahul8/687927c9ada2721d79741ed46560c4dc/tflite-issue-80319.ipynb) for reference if possible could you please help me with your complete Jupyter notebook along with ultralytics and TensorFlow version so I'll try on Windows system ? 

If you're using older version of TensorFlow please give it try with latest TensorFlow version 2.18.0 and see is it resolving your issue or not ?

Thank you for your cooperation and patience.
