### ISSUE TITLE
Could LSTM model be used to predict from multivariate variables

### ISSUE THREAD

**Issue by yelongclass** [tensorflow/tensorflow#8036]
I am doing a project on water content predictions. The input variables on time series include temperature, rainfall and so on. I do not know whether LSTM can predict from multiple variables or not. And I do not know how to do it? Could anybody please help me and provide such a related example? Thank you very much.

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
