### ISSUE TITLE
Compiler warning in tensorflow/lite/graph_info.h

### ISSUE THREAD

**Issue by Shamino0** [tensorflow/tensorflow#80379]
This has been experienced using TF 2.18.0 and has been seen in the current master branch.

I have compiled the TensorFlow Lite shared library for use on an embedded device.  In order to compile my application against it, I am using the TF distribution's headers during the compilation process.  When my code includes `tensorflow/lite/interpreter.h`, I see the following warning from the compiler (GCC 11.3.0):

~~~~
In file included from .../tensorflow/include/tensorflow/lite/core/subgraph.h:42,
                 from .../tensorflow/include/tensorflow/lite/core/async/async_subgraph.h:27,
                 from .../tensorflow/include/tensorflow/lite/core/async/async_signature_runner.h:24,
                 from .../tensorflow/include/tensorflow/lite/core/interpreter.h:47,
                 from .../tensorflow/include/tensorflow/lite/interpreter.h:21,
                 from (my code):
.../tensorflow/include/tensorflow/lite/graph_info.h:127:1: warning: multi-line comment [-Wcomment]
  127 | //                    /------------\
      | ^
.../tensorflow/include/tensorflow/lite/graph_info.h:139:1: warning: multi-line comment [-Wcomment]
  139 | //                    /------------\
      | ^
~~~~

The reason for this is because that header has a backslash at the end of a line with a C++-style comment.  To get rid of the warning, someone should either:
* Put another non-whitespace character at the end of those two lines
* Convert the C++-style comment block to a C-style block (`/* ... */`)

**Comment by gaikwadrahul8** [comment]
Hi, @Shamino0
Thank you for bringing this issue to our attention, I've submitted PR https://github.com/tensorflow/tensorflow/pull/80574 to take care this issue. 

Thank you for your cooperation and understanding.

**Comment by gaikwadrahul8** [comment]
Hi, @Shamino0 
I see this PR has been merged https://github.com/tensorflow/tensorflow/pull/80574 so I'm closing this issue now. Thank you for your cooperation and patience.
