### ISSUE TITLE
broken link for flower photos in the official tutorial about transfer learning

### ISSUE THREAD

**Issue by zakizhou** [tensorflow/tensorflow#8041]
In official tutorial "How to Retrain Inception's Final Layer for New Categories", link for downloading flower photos is broken:
`curl -O http://download.tensorflow.org/example_../images/flower_photos.tgz`

**Comment by tatatodd** [comment]
Thanks for filing the issue @zakizhou !  I've fixed this internally, and the site will be updated at some point.

FYI the correct link is this:
`curl -O http://download.tensorflow.org/example_images/flower_photos.tgz`

**Comment by erolrecep** [comment]
curl -O http://download.tensorflow.org/example_images/flower_photos.tgz This link is working today. Thanks.
