### ISSUE TITLE
Broken link in Adding a New Op to zero_out_op_1.py

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#8044]
The link in [Adding a New Op](https://github.com/tensorflow/tensorflow/blob/b10f50ff15944badb7262a207f6628dfa52d6a9d/tensorflow/docs_src/extend/adding_an_op.md#L244) to `zero_out_op_1.py` is broken. It points to: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/g3doc/how_tos/adding_an_op/zero_out_op_1.py.

**Comment by ClarkZinzow** [comment]
Hi @cancan101, I briefly mentioned this broken link in #8029 as an example of the many broken g3doc links.  It looks like all of the broken links on the Adding a New Op page have been fixed by #8066, which has just been merged.

**Comment by gunan** [comment]
I will then close this issue, since it looks like it is resolved.
Please comment if it is not, then I can reopen it right away.

**Comment by ClarkZinzow** [comment]
My mistake, the broken links on Adding a New Op are not fixed by the pull request.  The code files are where they should be, but the links weren't changed in [adding_an_op.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/extend/adding_an_op.md).

**Comment by gunan** [comment]
reopened :)

**Comment by ClarkZinzow** [comment]
It looks like all that is required is a quick find-replace on the [adding_an_op.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/extend/adding_an_op.md) file:  g3doc/how_tos &#x27F6; examples

**Comment by prb12** [comment]
@josh11b @dr4b  Any ideas what's still broken?

**Comment by dr4b** [comment]
we re-added these files to the repo here: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/adding_an_op

but the links have to be fixed, I think.

**Comment by ClarkZinzow** [comment]
Links are fixed in #8104.
