### ISSUE TITLE
Error in tensorflow debugger (tfdbg) while executing session run call in child thread

### ISSUE THREAD

**Issue by agupta74** [tensorflow/tensorflow#8047]
I ran tensorflow debugger using the command "python -m <PythonModule> --debug" but got the following error (i,e Signal only works in main thread):

![screenshot3png](https://cloud.githubusercontent.com/assets/21690396/23540767/24df69c6-ff98-11e6-96bf-5ee98a439f77.PNG)

The error is thrown when a session run call is executed in a child thread (spawned from main thread). Is tensorflow debugger only supported for single threaded applications?

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
None

### Environment info
Operating System: CentOS 7.2.1511

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
![screenshot](https://cloud.githubusercontent.com/assets/21690396/23540624/38732a46-ff97-11e6-9749-a43b8af6c5aa.PNG)

If installed from binary pip package, provide:

1. A link to the pip package you installed: https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.0-cp35-cp35m-linux_x86_64.whl

2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
![screenshot2](https://cloud.githubusercontent.com/assets/21690396/23540694/b42648f8-ff97-11e6-93ff-4cabc2d2d199.PNG)

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by caisq** [comment]
@agupta74 tfdbg's CLI class attempts to register signal handlers even when not running on the main threads, which is the reason for this error. We will send a bug fix to the master branch.

As a workaround until the bug is fixed, you can pretend that the child process is a "remote process" and use the approach outlined here:
https://www.tensorflow.org/programmers_guide/debugger#offline_debugging_of_remotely-running_sessions

**Comment by caisq** [comment]
Thank you for reporting this bug, @agupta74!

**Comment by j-wilson** [comment]
@caisq Any updates regarding this issue? I've tried using `offline_analyzer` per your suggestion; but, keep running into `ValueError: Duplicate node name` as in #7051. Unlike #7051, I'm running locally on CPU. The problem seems to stem from repeated calls to `sess.run()`, where `sess` is an instance of `DumpingDebugWrapperSession`; but, I'm not sure how to get around this issue when using `tf.get_variable()` given that a call to an initializer seems necessary. Included below is a code snippet.


```
# Dependencies
import subprocess
import tensorflow as tf
from tempfile import TemporaryDirectory
from tensorflow.python import debug as tf_debug

dump_dir = TemporaryDirectory() #temp. directory for demo
with tf.Session() as _sess:
  # Create 'DumpingDebugWrapperSession' wrapper
  def watch_fn(fetches, feed_dict):
    node_name_regex_whitelist = '(watch_[0-9]+)'
    debug_ops, op_type_regex_whitelist = None, None
    return debug_ops, node_name_regex_whitelist, op_type_regex_whitelist
  sess = tf_debug.DumpingDebugWrapperSession(_sess,
                  dump_dir.name, watch_fn=watch_fn)

  # Declare TensorFlow variables
  tf_vars = [tf.get_variable('watch_0', shape=[32], dtype='float32'),
             tf.get_variable('ignore_0', shape=[32], dtype='float32')]

  # Calls sess.run()
  init_op = tf.global_variables_initializer()
  sess.run(init_op)
  # <stuff goes here>
  fetches = sess.run(tf_vars, feed_dict={})

# Call to offline_analyzer
argv = ['python3.5', '-m', 'tensorflow.python.debug.cli.offline_analyzer',
        '--ui_type', 'readline', '--dump_dir', dump_dir.name]
cmdline = " ".join(argv)
try:
  proc = subprocess.Popen(cmdline, shell=True)
  proc.wait()
finally:
  dump_dir.cleanup()
```

**Comment by caisq** [comment]
@j-wilson With regard to the duplicate node name error you are getting, are you using the same file:// debug URL (i.e., the same directory) for different session.run() calls? If that's the case, can you try using a unique different URL (i.e. ,directory) for each session.run() call?

**Comment by j-wilson** [comment]
@caisq The script runs if modified s.t. a new wrapper/directory is used for each call to `sess.run()`; however, none of the tensors show up inside the debugger CLI, i.e. `0 dumped tensor(s):`.

As a separate comment, is there a reason why separate wrappers/directories are needed for each call to `sess.run()`? The wrapper creates subdirectories `run_<run_id>`, suggesting that reuse of a single wrapper might be possible --- which would help with usability.

**Comment by caisq** [comment]
@j-wilson There is already a wrapper along that line, see: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/debug/wrappers/dumping_wrapper.py#L31

Usage example:
```
from tensorflow.python import debug as tf_debug

sess = tf.Session
sess = tf_debug.DumpingWrapperSession(sess, session_root="/tmp/dumps1")
```

The dumps from different runs will be inside folders such as /tmp/dumps1/run_<epoch_time_stamp>_<uuid>

See also doc at: https://www.tensorflow.org/programmers_guide/debugger#offline_debugging_of_remotely-running_sessions

As for the reason why you see 0 dumped tensor(s), it might be that ops are constant folded during graph optimization? Does the same 0-dumped-tensor issue happen if you run it on the main thread, and/or on some other graph in a child thread?
