### ISSUE TITLE
How to compile and use tfrt_session?

### ISSUE THREAD

**Issue by MoFHeka** [tensorflow/tensorflow#80495]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

nightly

### Custom code

Yes

### Current behavior?

I try to build tfrt_session independently and preload it when running tensorflow, but it failed for lacking of symbol.

### Standalone code to reproduce the issue

```shell
I need a way to build tfrt_session correctly
```

**Comment by tilakrayal** [comment]
@MoFHeka,
Could you please provide more information/context and the environment details or the error logs which helps to analyse the issue in an effective way. Thank you!
