### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'

### ISSUE THREAD

**Issue by jonygli** [tensorflow/tensorflow#8049]
on `win7 x64`

python version is `3.5`
tensorflow's version is `1.0.0`, and it is installed by `pip install tensorflow-gpu`

and, it seems I can replace `tf.nn.rnn_cell with tf.contrib.rnn`,...

**Comment by tatatodd** [comment]
@jonygli Please fill out the following information, which was part of the "New issue" template.  Note that the RNN operations were moved from `tf.contrib.rnn` to `tf.nn.rnn_cell` in TensorFlow 1.0, so I suspect you're not actually running TensorFlow 1.0.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

**Comment by dirceusemighini** [comment]
Got the same error when testing tensorbox
 
`bazel version
Extracting Bazel installation...
Build label: 0.4.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Feb 1 18:54:21 2017 (1485975261)
Build timestamp: 1485975261
Build timestamp as int: 1485975261`

` python -c "import tensorflow; print(tensorflow.__version__)"
1.0.0
`
`python3 train.py --hypes hypes/overfeat_rezoom.json --gpu 0 --logdir output
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from tensorflow.models.rnn import rnn_cell
ImportError: No module named 'tensorflow.models'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 18, in <module>
    rnn_cell = tf.nn.rnn_cell
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'`

**Comment by styleNie** [comment]
on win7 x64
python version is 3.5
tensorflow's version is 1.0.0, and it is installed by pip install tensorflow

# highway layer that borrowed from https://github.com/carpedm20/lstm-char-cnn-tensorflow
def highway(input_, size, layer_size=1, bias=-2, f=tf.nn.relu):
    """Highway Network (cf. http://arxiv.org/abs/1505.00387).

    t = sigmoid(Wy + b)
    z = t * g(Wy + b) + (1 - t) * y
    where g is nonlinearity, t is transform gate, and (1 - t) is carry gate.
    """
    output = input_
    for idx in range(layer_size):
        output = f(tf.nn.rnn_cell._linear(output, size, 0, scope='output_lin_%d' % idx)) #tf.contrib.layers.linear instad doesn't work either.
        transform_gate = tf.sigmoid(tf.nn.rnn_cell._linear(input_, size, 0, scope='transform_lin_%d' % idx) + bias)
        carry_gate = 1. - transform_gate

        output = transform_gate * output + carry_gate * input_

    return output

and got error 
line 15, in highway
    output = f(tf.nn.rnn_cell._linear(output, size, 0, scope='output_lin_%d' % idx))
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'

I'm not familiar with tensorflow, but I have to use highway, I've try some method
http://stackoverflow.com/questions/42552540/tensorflow-tf-contrib-rnn-module-object-is-not-callable
http://stackoverflow.com/questions/42311007/attributeerror-tensorflow-python-ops-rnn-has-no-attribute-rnn
but all failed.

**Comment by jonygli** [comment]
@tatatodd it doesn't need any step to reproduce, just after installing the specified version, then you will find that there is no such rnn_cell.py file!

**Comment by ebrevdo** [comment]
Andrew can you update the Python code rewriter?

**Comment by wangyizhen** [comment]
Just use 
from tensorflow.contrib import rnn 
lstm_cell = rnn.BasicLSTMCell(rnn_size) 
outputs, states = rnn.static_rnn(lstm_cell, x, dtype=tf.float32)

instead of 
from tensorflow.python.ops import rnn, rnn_cell 
lstm_cell = rnn_cell.BasicLSTMCell(rnn_size,state_is_tuple=True) 
outputs, states = rnn.rnn(lstm_cell, x, dtype=tf.float32)﻿

**Comment by yifeif** [comment]
Closing this. @aselle feel free to reopen if upgrade script needs to be updated.

**Comment by aroraakshit** [comment]
still not working @wangyizhen
