### ISSUE TITLE
Aborted (core dumped) in `SparseTensorDenseMatMul`

### ISSUE THREAD

**Issue by LongZE666** [tensorflow/tensorflow#80528]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf2.17.0

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Python version

3.11

### Current behavior?

Under specific inputs, `SparseTensorDenseMatMul` triggered a crash.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

a_indices = tf.constant(1879048192, shape=[2,2], dtype=tf.int64)
a_values = tf.constant(0, shape=[2], dtype=tf.float32)
a_shape = tf.constant([-1, 5], dtype=tf.int64)
b = tf.constant(0, shape=[5, 5], dtype=tf.float32)

result = tf.raw_ops.SparseTensorDenseMatMul(
    a_indices=a_indices,
    a_values=a_values,
    a_shape=a_shape,
    b=b
)
```

### Relevant log output

```shell
Status: INVALID_ARGUMENT: Expected shape dimensions to be non-negative, got -1
Aborted (core dumped)
```

**Comment by Venkat6871** [comment]
I request you to take a look at this #65724 where a similar issue has been proposed and it is still open. Also I request to follow the similar issue which has been proposed to have the updates on the similar issue. Thank you!

**Comment by LongZE666** [comment]
Thank you for your reply, I will pay attention to this issue
