### ISSUE TITLE
summarize_graph doesn't recognize VariableV2 

### ISSUE THREAD

**Issue by snnn** [tensorflow/tensorflow#8054]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
None
### Environment info
Operating System:
Windows 10

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
None

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
8cac382a5425d64f3083cb5adec525baa163e18e
2. The output of `bazel version`
compiled by cmake

### What other attempted solutions have you tried?

```
--- a/tensorflow/tools/graph_transforms/summarize_graph_main.cc
+++ b/tensorflow/tools/graph_transforms/summarize_graph_main.cc
@@ -109,7 +109,7 @@ Status SummarizeGraph(const GraphDef& graph, const string& graph_path) {
     if (node.op() == "Placeholder") {
       placeholders.push_back(&node);
     }
-    if (node.op() == "Variable") {
+    if (node.op() == "Variable" || node.op() == "VariableV2") {
       variables.push_back(&node);
     }
   }
@@ -168,7 +168,7 @@ Status SummarizeGraph(const GraphDef& graph, const string& graph_path) {
     if (node.device() != "") {
       ++device_counts[node.device()];
     }
-    if ((node.op() == "Const") || (node.op() == "Variable")) {
+    if ((node.op() == "Const") || (node.op() == "Variable") || (node.op() == "VariableV2")) {
       Tensor tensor;
       if (node.attr().count("value") &&
           tensor.FromProto(node.attr().at("value").tensor())) {
```

**Comment by tatatodd** [comment]
Thanks for filing the bug @snnn , and the suggested fix.  Would you like to submit a PR to fix this?

I think @petewarden should know whether this is the correct fix; it looks good to me.

**Comment by petewarden** [comment]
This does look like a good fix, thanks @tatatodd !

**Comment by snnn** [comment]
I'll submit a pull request tmr.

**Comment by snnn** [comment]
Indeed, I haven't understand the code fully, and I do not know how to use it.  Why all variables are marked as input? Should it only work with frozen graph?
