### ISSUE TITLE
TensorBoard: Can't load >5 Audio summaries, Broken pipe error

### ISSUE THREAD

**Issue by lemonzi** [tensorflow/tensorflow#8055]
*Possibly related:* https://github.com/tensorflow/tensorflow/issues/4207
*Setup:* OSX 10.10, TF nightly build of 2017-03-02 without GPU, Python 2.7.13. Affects both Chrome 56.0 and Safari 10.0. I think the official 1.0.0 release also had this issue.

My model logs relatively long audio summaries (~3 minutes long at 16 kHz), and created around 60 of them overnight. The issue also appears with fewer summaries created, at least on Chrome.

When using Chrome, they only load upon playback. Only the first 5 or so that I play will work; after that (even if I pause them) I can't get the others to play unless I restart TensorBoard. When using Safari, all of them try to load at once and nothing works.

On the TensorBoard side, I see a bunch of `error: [Errno 32] Broken pipe`, which could mean the browser tries to manage the incoming streams and TensorBoard doesn't know how to defer the transfers (see [this post](http://stackoverflow.com/questions/14207708/ioerror-errno-32-broken-pipe-python)).

For Chrome, there is a [limit of 6 concurrent audio downloads](https://bugs.chromium.org/p/chromium/issues/detail?id=162627). I think in my case the audio keeps the connection open even after I pause it, and instead of downloading the whole file it streams it, so it never closes and I can't play other files. I may need to restart TensorBoard to clear the browser cache, or maybe TensorBoard itself has a limit on the concurrent streams and they don't close even after a page reload. For Safari, I think it doesn't wait until playback to download the files, so all 60 players start the download concurrently and only the first ones survive.

If it's not a bug on the TensorBoard server and the summaries can't be prevented from keeping the connection open on pause or stop, I guess a possible solution could be to have a global player and load the audio files to it on-demand when requesting a summary, rather than each summary having its own player.

**Comment by tatatodd** [comment]
I think @dandelionmane and @jart might have some ideas here.

**Comment by dandelionmane** [comment]
@rryan Can you take a look?

**Comment by rryan** [comment]
hey @lemonzi! could you share an example events file that produces the problem?

**Comment by lemonzi** [comment]
Hey @rryan, long time! This should do it (the audio is quite horrible though): https://dl.dropboxusercontent.com/u/8226735/events.out.tfevents.1488843003.iAirLemon

**Comment by lemonzi** [comment]
Update: when using an Incognito Tab on Chrome, the audios pre-fetch for some reason, as with Safari, and therefore clicking the Audio link means that the other summaries will no longer update and the tab won't reload. I have to open a new tab to create a brand new connection with the server.

**Comment by lemonzi** [comment]
Update: the Dropbox link broke (see https://www.dropbox.com/help/16), use this one instead: https://www.dropbox.com/s/ow3sz2w3qurdm8y/events.out.tfevents.1488843003.iAirLemon

**Comment by lemonzi** [comment]
It got worse with the latest Tensorboard release; now only the 6 first audio summaries load, the rest hang forever. Only works on Incognito mode, when browsing with cache nothing loads at all.

**Comment by dandelionmane** [comment]
Migrated to https://github.com/tensorflow/tensorboard/issues/35
