### ISSUE TITLE
error installing tenserflow

### ISSUE THREAD

**Issue by mahernadar** [tensorflow/tensorflow#8056]
Hello Gents,

I am trying to install the TenserFlow  but when i reach and type this command:

"bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package"

after following all instruction in the following link:
"https://alliseesolutions.wordpress.com/2016/07/05/how-to-install-gpu-tensorflow-0-9-from-sources-ubuntu-14-04/" 

i get the following error (I managed to reduced errors from 5 to only this one):

NOTE: i am a beginner in Linux  (Ubuntu 14.04) and thus i require step by step instructions if possible.

ERROR: /home/maher/tensorflow/tensorflow/compiler/tf2xla/BUILD:23:1: C++ compilation of rule '//tensorflow/compiler/tf2xla:xla_compiler' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 180 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
tensorflow/compiler/tf2xla/xla_compiler.cc: In function 'tensorflow::Status tensorflow::{anonymous}::CheckSignature(const DataTypeVector&, const std::vector<tensorflow::XlaCompiler::Argument>&)':
tensorflow/compiler/tf2xla/xla_compiler.cc:48:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < types.size(); ++i) {
                                  ^
tensorflow/compiler/tf2xla/xla_compiler.cc: In member function 'tensorflow::Status tensorflow::XlaCompiler::BuildExecutable(const tensorflow::XlaCompiler::CompilationResult&, std::unique_ptr<xla::LocalExecutable>*)':
tensorflow/compiler/tf2xla/xla_compiler.cc:139:52: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < result.xla_input_shapes.size(); ++i) {
                                                    ^
tensorflow/compiler/tf2xla/xla_compiler.cc: In function 'tensorflow::Status tensorflow::{anonymous}::BuildArguments(const std::vector<tensorflow::XlaCompiler::Argument>&, bool, xla::ComputationBuilder*, std::vector<tensorflow::XlaContext::Argument>*, std::vector<int>*, std::vector<xla::Shape, std::allocator<xla::Shape> >*)':
tensorflow/compiler/tf2xla/xla_compiler.cc:228:8: error: 'size_typ' is not a member of 'std::vector<tensorflow::XlaCompiler::Argument>'
   for (std::vector<XlaCompiler::Argument>::size_typ i = 0;
        ^
tensorflow/compiler/tf2xla/xla_compiler.cc:228:53: error: expected ';' before 'i'
   for (std::vector<XlaCompiler::Argument>::size_typ i = 0;
                                                     ^
tensorflow/compiler/tf2xla/xla_compiler.cc:229:8: error: 'i' was not declared in this scope
        i < args.size(); ++i) {
        ^
tensorflow/compiler/tf2xla/xla_compiler.cc: In member function 'tensorflow::Status tensorflow::XlaCompiler::CompileGraph(const string&, std::unique_ptr<tensorflow::Graph>, tensorflow::FunctionLibraryRuntime*, const std::vector<tensorflow::XlaCompiler::Argument>&, tensorflow::XlaCompiler::CompilationResult*)':
tensorflow/compiler/tf2xla/xla_compiler.cc:480:20: error: 'VariableWrite' is not a member of 'tensorflow::XlaCompiler'
   for (std::vector<XlaCompiler::VariableWrite>::size_type  i = 0;
                    ^
tensorflow/compiler/tf2xla/xla_compiler.cc:480:20: error: 'VariableWrite' is not a member of 'tensorflow::XlaCompiler'
tensorflow/compiler/tf2xla/xla_compiler.cc:480:46: error: template argument 1 is invalid
   for (std::vector<XlaCompiler::VariableWrite>::size_type  i = 0;
                                              ^
tensorflow/compiler/tf2xla/xla_compiler.cc:480:46: error: template argument 2 is invalid
tensorflow/compiler/tf2xla/xla_compiler.cc:480:60: error: invalid type in declaration before 'i'
   for (std::vector<XlaCompiler::VariableWrite>::size_type  i = 0;
                                                            ^
tensorflow/compiler/tf2xla/xla_compiler.cc:480:60: error: expected ';' before 'i'
tensorflow/compiler/tf2xla/xla_compiler.cc:480:60: error: 'i' was not declared in this scope
tensorflow/compiler/tf2xla/xla_compiler.cc:481:43: error: expected ')' before ';' token
        i < result->variable_updates.size(); ++i) {
                                           ^
tensorflow/compiler/tf2xla/xla_compiler.cc:480:49: warning: unused variable 'size_type' [-Wunused-variable]
   for (std::vector<XlaCompiler::VariableWrite>::size_type  i = 0;
                                                 ^
tensorflow/compiler/tf2xla/xla_compiler.cc:481:47: error: 'i' was not declared in this scope
        i < result->variable_updates.size(); ++i) {
                                               ^
tensorflow/compiler/tf2xla/xla_compiler.cc:481:48: error: expected ';' before ')' token
        i < result->variable_updates.size(); ++i) {
                                                ^
tensorflow/compiler/tf2xla/xla_compiler.cc:508:1: error: expected '}' at end of input
 }  // namespace tensorflow
 ^
tensorflow/compiler/tf2xla/xla_compiler.cc: At global scope:
tensorflow/compiler/tf2xla/xla_compiler.cc:508:1: error: expected '}' at end of input
tensorflow/compiler/tf2xla/xla_compiler.cc: In member function 'tensorflow::Status tensorflow::XlaCompiler::CompileGraph(const string&, std::unique_ptr<tensorflow::Graph>, tensorflow::FunctionLibraryRuntime*, const std::vector<tensorflow::XlaCompiler::Argument>&, tensorflow::XlaCompiler::CompilationResult*)':
tensorflow/compiler/tf2xla/xla_compiler.cc:508:1: warning: control reaches end of non-void function [-Wreturn-type]
 }  // namespace tensorflow
 ^
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by MikeTam1021** [comment]
How about you follow this tutorial instead?

https://www.tensorflow.org/install/install_linux

from the command line, just:

pip install tensorflow

**Comment by gunan** [comment]
If you are a beginner on linux, we recommend starting with the command @MikeTam1021 suggested. Since GPU version requires a lot of non-trivial installation of CUDA, cuDNN, and manipulation of environment variables, you should definitely start with the CPU version.

If you are using ubuntu 14.04, you may need to run the pip install command with the URL as follows.
```
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0-cp27-none-linux_x86_64.whl
```

**Comment by tatatodd** [comment]
@mahernadar let us how it goes!  And I agree with the advice - using a binary install via pip will be much simpler.

If you're curious, the particular compilation error you're encountering is being fixed by #8039

**Comment by mahernadar** [comment]
Dear Gunan,

Thanks allot for your response. That's a great suggestion, but i need to
learn fast because i will need to work on a real project with real pictures
and try to implement a classification according to project requirements.

You think CPU is good enough for that? Note that i have an Alienware laptop
with Nvidia 770M.

Again, thanks allot for your input :)

Sincerely,

Maher A. Nadar

**Comment by gunan** [comment]
I recommend using the CPU-pip version for a few reasons:
1-Installation of CPU pip version is effortless. You can start using tensorflow in 5-10 minutes.
2-If you have a single GPU, that will be used for both display and computation. This is not recommended. When running large training graphs you will almost certainly run into issues due to GPU also being used for display, and this will set you back even further.

**Comment by prb12** [comment]
Closing this issue since it appears to be due to following a tutorial which advocates building from live head of the git repo (despite the URL saying `how-to-install-gpu-tensorflow-0-9-from-sources-ubuntu-14-04`)

This command will pick up the current state of the github repository, rather than a specific known working version:
`git clone https://github.com/tensorflow/tensorflow`

Though we make every effort to test each commit, some issues will inevitable slip through, so it is usually much safer to install a working binary package or at least build from source using a specific tagged version.
 
As @tatatodd says, a fix for the particular error is in progress here https://github.com/tensorflow/tensorflow/pull/8039
