### ISSUE TITLE
PEP8 Violations training.py

### ISSUE THREAD

**Issue by kp0119** [tensorflow/tensorflow#80590]
### Issue type

Others

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.18.0

### Custom code

Yes

### Current behavior?

Incorrect spacing, violates PEP8 standards. Not using 4 spaces per indenation level. 
https://peps.python.org/pep-0008/#indentation

### Standalone code to reproduce the issue

```shell
https://peps.python.org/pep-0008/#indentation
```

**Comment by Venkat6871** [comment]
Hi **@kp0119** ,
Apologies for the delay, and thank you for raising your concern here. This issue does not belong to TensorFlow. Please raise your issue in the appropriate repository.
Thank you!
