### ISSUE TITLE
Tensorflow installation issues

### ISSUE THREAD

**Issue by iwqculrbud** [tensorflow/tensorflow#80629]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tensorflow_intel-2.18.0-cp312-cp312-win_amd64.whl

### Custom code

Yes

### OS platform and distribution

Windows 11 Home

### GPU model and memory

4060 Laptop

### Current behavior?

I originally wanted to install the tensorflow-gpu version, but why does it always download the intel version when I use "pip install tensorflow"? There are no problems with my cuda and cudnn. How can I solve this problem?
![屏幕截图 2024-11-23 181957](https://github.com/user-attachments/assets/025ee8ee-4c8c-4bee-9c50-7f6a2fb8886d)

### Standalone code to reproduce the issue

```shell
pip install --upgrade tensorflow
```

### Relevant log output

```shell
ages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow-intel==2.18.0->tensorflow) (0.1.2)
Using cached tensorflow-2.18.0-cp312-cp312-win_amd64.whl (7.5 kB)
Using cached tensorflow_intel-2.18.0-cp312-cp312-win_amd64.whl (390.3 MB)
```

**Comment by tilakrayal** [comment]
@iwqculrbud,
Could you please provide more information/context and also steps followed to install & the error log which helps to debug the issue in an effective way. Thank you!

**Comment by iwqculrbud** [comment]
> @iwqculrbud, Could you please provide more information/context and also steps followed to install & the error log which helps to debug the issue in an effective way. Thank you!

No problem, I have an intel i5-12500H and an Nvidia 4060 laptop on my device, but when I used pip to install it, I found that it seemed to install the intel optimized version (as shown in the picture), I want to install tensorflow optimized for nvidia.
Is there any tensorflow optimized for nvidia graphics cards?
![屏幕截图 2024-11-26 123035](https://github.com/user-attachments/assets/d009df0d-0f9e-4fd3-a815-c4b8f7295fdc)
