### ISSUE TITLE
Invalid value with "sigmoid_cross_entropy_with_logits"

### ISSUE THREAD

**Issue by genk1** [tensorflow/tensorflow#8073]
Hello, I started learning tensorflow and trying to solve a lot of sample program and lessons, 
Then I faced the problem with "sigmoid_cross_entropy_with_logits" methods,
I attached the error & code which I used.
Please help me to figure out this,,, Thank you very much in advance.
--------
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

#placeholders of input & output
x = tf.placeholder(tf.float32, shape=(None,2), name="x")
y_ = tf.placeholder(tf.float32, shape=(None,1), name="y")

#model parameter
a = tf.Variable(-10 * tf.ones((2,1)), name="a")
b = tf.Variable(200., name="b")

#model function
u = tf.matmul(x, a) + b
y = tf.sigmoid(u)

loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(u, y_))

train_step = tf.train.GradientDescentOptimizer(0.1).minimize(loss)

train_x = np.array([[2.,3.], [0., 16.], [3., 1.][2., 8.]])
train_y = np.array([1.,1.,0.,0.]).reshape(4,1)
print("x=", train_x)
print("y=", train_y)

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

for i in range(1000):
    _, l, a_, b_ = sess.run([train_step, loss, a, b], feed_dict={x:train_x, y:train_y})
    if (i+1) % 100 == 0:
        print("Step=%3d, a1=%6.2f, a2=%6.2f, b=%6.2f, loss=%.2f" % (i+1, a_[0], a_[1], b_, l))

        
est_a, est_b = sess.run([a, b], feed_dict={x: train_x, y_: train_y})
print("Estimated: a1=%6.2f, a2=%6.2f, b=%6.2f" % (est_a[0], est_a[1], est_b))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-2a36f4933eac> in <module>()
     15 y = tf.sigmoid(u)
     16 
---> 17 loss = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(u, y_))
     18 
     19 train_step = tf.train.GradientDescentOptimizer(0.1).minimize(loss)

/Users/GenkiA/.pyenv/versions/3.5.2/lib/python3.5/site-packages/tensorflow/python/ops/nn_impl.py in sigmoid_cross_entropy_with_logits(_sentinel, labels, logits, name)
    144   # pylint: disable=protected-access
    145   nn_ops._ensure_xent_args("sigmoid_cross_entropy_with_logits",
--> 146                            _sentinel, labels, logits)
    147   # pylint: enable=protected-access
    148 

/Users/GenkiA/.pyenv/versions/3.5.2/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py in _ensure_xent_args(name, sentinel, labels, logits)
   1531   if sentinel is not None:
   1532     raise ValueError("Only call `%s` with "
-> 1533                      "named arguments (labels=..., logits=..., ...)" % name)
   1534   if labels is None or logits is None:
   1535     raise ValueError("Both labels and logits must be provided.")

ValueError: Only call `sigmoid_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

**Comment by protoget** [comment]
This error message is saying you'd call ```sigmoid_cross_entropy_with_logits``` like this:
```py
sigmoid_cross_entropy_with_logits(labels=xxx, logits=..., name=...,...)
```
