### ISSUE TITLE
Aborted (core dumped) in `UnBatch`

### ISSUE THREAD

**Issue by LongZE666** [tensorflow/tensorflow#80751]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf2.17.0 tf2.16.1

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Python version

3.11

### Current behavior?

When `batch_index` is scalar,  `UnBatch` triggered a crash.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

batched_tensor = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
batch_index = tf.constant(1, dtype=tf.int64)
id = tf.constant(0, dtype=tf.int64) 

tf.raw_ops.Unbatch(
    batched_tensor=batched_tensor,
    batch_index=batch_index,
    id=id,
    timeout_micros=1000000
)
```

### Relevant log output

```shell
Check failed: d < dims() (1 vs. 0)
```

**Comment by tilakrayal** [comment]
@LongZE666,
I tried to execute the mentioned code on tf-nightly and TensorFlow v2.17, observed that the code was aborted in TF v2.17 and on tf-nigthly the code was executed with the expected error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/36c1807f2037192d3ef3a32d156795ae/untitled2260.ipynb). Thank you!
