### ISSUE TITLE
New Build causes Illegal instruction on Import in Python 2.7 and 3.4

### ISSUE THREAD

**Issue by FernandezR** [tensorflow/tensorflow#8076]
I built tensorflow with gpu support for python 2.7 and 3.4 using CUDA 8.0 and CUDNN 5.1, running oo Linux.

On import of tensorflow installed with the wheels I built I get an 'Illegal Instruction' error and python quits.

Can someone confirm if this is an error on my part or if is an issue with the current build?

**Comment by FernandezR** [comment]
The problem was that the wheels were compiled on a machine with newer kernel than the machine it was being installed on.

**Comment by rcmf123** [comment]
How did you fix it?
