### ISSUE TITLE
Custom methods and training configuration in subclass model not saved by ModelCheckpoint callback

### ISSUE THREAD

**Issue by lilianabrandao** [tensorflow/tensorflow#80781]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

tf 2.12.0

### Custom code

Yes

### OS platform and distribution

Google Colab / Windows 11

### Python version

3.8.18

### Current behavior?

Hi, 

I'm following the tutorial in [https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit](url) to implement a subclassed model (end-to-end GAN). For that:
- I have overridden certain methods (`train_step`, `save`).
- I am using the `ModelCheckpoint` callback to save the model (generator).

The training and model saving run smoothly, but when I load the trained model: 
- The overridden methods are not accessible; instead, the methods from the parent class (tf.keras.Model) are loaded.
![image](https://github.com/user-attachments/assets/34f80ff3-78f9-4d05-a290-e6a214faf55a)
- The training configuration is also not available.
![image](https://github.com/user-attachments/assets/6fc0de9f-5ca3-46c4-92d6-21fa11765111)

I attempted the fix suggested in [https://github.com/tensorflow/tensorflow/issues/62450](url) (and the related suggestions mentioned there), but without success.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/19tc4EY_wI66ZZBeLlhs0rqIyfQIKENhd#scrollTo=OM_MBvzrtm_z
```

**Comment by tilakrayal** [comment]
@lilianabrandao,
I tried to execute the mentioned code with the latest TensorFlow v2.17 which contains Keras3.0 and observed that the compile error which you are facing is unavailable. And also the shape mismatch error is occured due to input difference. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/54e58fe537159749e136d7f519e40534/untitled2256.ipynb). Also this issue is more related to Keras please create the issue in Keras-team/keras repo. Thank you!

**Comment by lilianabrandao** [comment]
Thanks for the gist, @tilakrayal, but I need to address this issue under TensorFlow 2.12.0.

After some investigation, I realized that since the subclassed model is just a wrapper for training two functional models, I need to:
1. Explicitly compile the functional models inside the wrapper to save their training configurations.
2. Override the call function in the wrapper model and explicitly invoke it before saving the subclassed model.

I hope this helps anyone facing the same issue in the future.
