### ISSUE TITLE
error: can't copy 'tensorflow/python/pywrap_tensorflow.py': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by IvyGongoogle** [tensorflow/tensorflow#8078]
Hello, now my cuda is 7.5 , so I install tf from the source, but when I run the command 'bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg', it shows error:
`Sun Mar 5 02:09:40 CST 2017 : === Using tmpdir: /tmp/tmp.4Bm642hjyI
~/ztgong/dl-tools/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles ~/ztgong/dl-tools/tensorflow
~/ztgong/dl-tools/tensorflow
/tmp/tmp.4Bm642hjyI ~/ztgong/dl-tools/tensorflow
Sun Mar 5 02:09:41 CST 2017 : === Building wheel
error: can't copy 'tensorflow/python/pywrap_tensorflow.py': doesn't exist or not a regular file
`

I still not fix this error, how to solve it?
thank you in advance!!

**Comment by prb12** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by IvyGongoogle** [comment]
@prb12 Thank you very much for your reply. I use ubuntu14.04, x86_64. and I use tf r1.0 by  `git clone https://github.com/tensorflow/tensorflow `and `git checkout r1.0`.

**Comment by prb12** [comment]
When you previously ran the command 
`bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package`, did it complete successfully?

**Comment by IvyGongoogle** [comment]
@prb12 yes, it did success. And running the command `bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package` also success.

**Comment by prb12** [comment]
@IvyGongoogle  your error message includes the string ~/ztgong/dl-tools/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles` 

Is it possibly the case that you are running this binary from a directory other than the root of your tensorflow git client?

If so, then the _relative_ pathname of `tensorflow/python/pywrap_tensorflow.py` would not be found.  (The `build_pip_package` command expects to be run in your build tree.)

**Comment by batigooal** [comment]
I met the same problems

**Comment by asimshankar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by StatML** [comment]
I have the same problem with Ubuntu 16.04 + CUDA 8.0
