### ISSUE TITLE
Difference of allocate_persistent() and allocate_temp()

### ISSUE THREAD

**Issue by xingyul** [tensorflow/tensorflow#8084]
This is a question on the usage of the two functions which are used in Compute() method for defining new Op.

My understanding is that allocate_temp() are used **only and once in constructing Op** and cannot be used during traning or testing steps later on; whereas allocate_persistent() can be used in **both Op construction and traning or testing steps later on**. Am I correct?

When I was defining my own new Op, I need to allocate a temporay GPU memory buffer in my Compute() method. The buffer will be used every time I call Compute(), however, I don't need to store the value in the temporary buffer for future reuse. In this case, which function should I use?

When calling the two functions, do we need to call corresponding functions like free_persistent() or free_temp()?

**Comment by prb12** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
