### ISSUE TITLE
InvalidArgumentError when using MirroredStrategy but not with tf.distribute.get_strategy()

### ISSUE THREAD

**Issue by ArnauPujantellNavas** [tensorflow/tensorflow#80951]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.18

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.12

### GCC/compiler version

gcc 9.4.0

### CUDA/cuDNN version

12.5.1

### GPU model and memory

2 x NVIDIA Tesla V100 (12 cores, 224 GB RAM, 1474 GB disk)

### Current behavior?

**Problem**: I am encountering an InvalidArgumentError when using MirroredStrategy in TensorFlow. This error does not occur when I use tf.distribute.get_strategy(). Below is the error message I receive and the standalone code to reproduce it.

**Expected Behavior**: The code should run without errors when using MirroredStrategy, similar to when using tf.distribute.get_strategy().

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import keras

def create_dataset():
    float_data = tf.constant([[1.0, 2.0], [3.0, 4.0]], dtype=tf.float32)
    string_data = tf.constant([["foo", "bar"], ["baz", "qux"]], dtype=tf.string)
    labels = tf.constant([[1], [0]], dtype=tf.float32)
    
    dataset = tf.data.Dataset.from_tensor_slices(((float_data, string_data), labels))
    return dataset

def create_model():
    input_float = keras.Input(shape=(2,), dtype=tf.float32, name='float_input')
    input_string = keras.Input(shape=(2,), dtype=tf.string, name='string_input')
    
    string_lookup = keras.layers.StringLookup(vocabulary=["foo", "bar", "baz", "qux"], name='string_lookup')
    string_embedding = string_lookup(input_string)
    
    concatenated = keras.layers.Concatenate(name='concatenate')([input_float, string_embedding])
    
    dense = keras.layers.Dense(10, activation='relu', name='dense_1')(concatenated)
    output = keras.layers.Dense(1, activation='sigmoid', name='output')(dense)
    
    model = keras.Model(inputs=[input_float, input_string], outputs=output, name='simple_model')
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

def main():
    print("Single GPU strategy")
    strategy = tf.distribute.get_strategy()
    
    dataset = create_dataset()
    
    with strategy.scope():
        model = create_model()
        
    model.fit(dataset.batch(2), epochs=5)

    print("Multiple GPUs strategy")

    strategy = tf.distribute.MirroredStrategy()
    
    dataset = create_dataset()
    
    with strategy.scope():
        model = create_model()
        
    model.fit(dataset.batch(2), epochs=5)

if __name__ == "__main__":
    main()
```

### Relevant log output

```shell
tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of string is not in the list of allowed values: float, double, int32, uint8, int16, int8, complex64, int64, qint8, quint8, qint32, bfloat16, qint16, quint16, uint16, complex128, half, uint32, uint64, variant
        ; NodeDef: {{node AddN}}; Op<name=AddN; signature=inputs:N*T -> sum:T; attr=N:int,min=1; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, DT_INT8, DT_COMPLEX64, DT_INT64, DT_QINT8, DT_QUINT8, DT_QINT32, DT_BFLOAT16, DT_QINT16, DT_QUINT16, DT_UINT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64, DT_VARIANT]; is_commutative=true; is_aggregate=true> [Op:AddN] name:
```

**Comment by Venkat6871** [comment]
Hi **@ArnauPujantellNavas** ,
Apologies for the delay, and thank you for raising your concern here. I tried running your code on Colab using TensorFlow 2.18.0, and I did not encounter any issues. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/e75da5abb3d644c36a0927ebccaac89f/80951_tf_2-18-v.ipynb) here for your reference. Let me know if I missed anything or made any mistakes.
Thank you!

**Comment by ArnauPujantellNavas** [comment]
Hi @Venkat6871, thank you for your answer.
When using one single GPU it works fine, same when using more than one GPU and tf.distribute.get_strategy(). The error shows up when using more than one GPU and MirroredStrategy(). In my case, I am using 2 NVIDIA Tesla V100. 
Sorry if i didn't explain the issue correctly.

**Comment by gaikwadrahul8** [comment]
Hi, @ArnauPujantellNavas 
I apologize for the delayed response, I have tried your code with 02 T4 GPU's and it seems like working as expected please refer this [gist-file](https://colab.research.google.com/gist/gaikwadrahul8/d49c8cd6fc06da58cd64486e767b9d7e/tf-issue-80951.ipynb) or Am I missing something here if so please let me know ? 

Thank you for your cooperation and patience.

**Comment by ArnauPujantellNavas** [comment]
Hi @gaikwadrahul8 
Thanks for your response, looking at the file I've noticed we are using different versions of the packages. When I try to use yours tensorflow can't detect my GPUs properly.

This is the command I am using to install the required packages with the latest versions:
`pip install tensorflow[and-cuda]==2.18.0 keras==3.7.0`

I added some prints to the code to make sure it is using the 2 replicas and not just one of them:
```
import tensorflow as tf
import keras

def create_dataset():
    float_data = tf.constant([[1.0, 2.0], [3.0, 4.0]], dtype=tf.float32)
    string_data = tf.constant([["foo", "bar"], ["baz", "qux"]], dtype=tf.string)
    labels = tf.constant([[1], [0]], dtype=tf.float32)
    
    dataset = tf.data.Dataset.from_tensor_slices(((float_data, string_data), labels))
    return dataset

def create_model():
    input_float = keras.Input(shape=(2,), dtype=tf.float32, name='float_input')
    input_string = keras.Input(shape=(2,), dtype=tf.string, name='string_input')
    
    string_lookup = keras.layers.StringLookup(vocabulary=["foo", "bar", "baz", "qux"], name='string_lookup')
    string_embedding = string_lookup(input_string)
    
    concatenated = keras.layers.Concatenate(name='concatenate')([input_float, string_embedding])
    
    dense = keras.layers.Dense(10, activation='relu', name='dense_1')(concatenated)
    output = keras.layers.Dense(1, activation='sigmoid', name='output')(dense)
    
    model = keras.Model(inputs=[input_float, input_string], outputs=output, name='simple_model')
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return model

def main():

    print("Single GPU strategy")

    strategy = tf.distribute.get_strategy()
    n_gpu: int = len(tf.config.list_physical_devices('GPU'))
    n_replicas: int = strategy.num_replicas_in_sync
 
    print(f'GPU: {n_gpu}')
    print(f'Replicas: {n_replicas}')
    
    dataset = create_dataset()
    
    with strategy.scope():
        model = create_model()
        
    model.fit(dataset.batch(2), epochs=5)

    print("Multiple GPUs strategy")

    strategy = tf.distribute.MirroredStrategy()

    n_gpu: int = len(tf.config.list_physical_devices('GPU'))
    n_replicas: int = strategy.num_replicas_in_sync
 
    print(f'GPU: {n_gpu}')
    print(f'Replicas: {n_replicas}')
    
    dataset = create_dataset()
    
    with strategy.scope():
        model = create_model()
        
    model.fit(dataset.batch(2), epochs=5)

if __name__ == "__main__":
    main()

```

And I am recieving the same original error:
```
Single GPU strategy
GPU: 2
Replicas: 1
I0000 00:00:1733759297.693816   24170 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 14791 MB memory:  -> device: 0, name: Tesla V100-PCIE-16GB, pci bus id: 0001:00:00.0, compute capability: 7.0
I0000 00:00:1733759297.694337   24170 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 14791 MB memory:  -> device: 1, name: Tesla V100-PCIE-16GB, pci bus id: 0002:00:00.0, compute capability: 7.0
Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5000 - loss: 0.9865
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.5000 - loss: 0.9687
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5000 - loss: 0.9513
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5000 - loss: 0.9342
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5000 - loss: 0.9174
Multiple GPUs strategy
GPU: 2
Replicas: 2
tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of string is not in the list of allowed values: float, double, int32, uint8, int16, int8, complex64, int64, qint8, quint8, qint32, bfloat16, qint16, quint16, uint16, complex128, half, uint32, uint64, variant
        ; NodeDef: {{node AddN}}; Op<name=AddN; signature=inputs:N*T -> sum:T; attr=N:int,min=1; attr=T:type,allowed=[DT_FLOAT, DT_DOUBLE, DT_INT32, DT_UINT8, DT_INT16, DT_INT8, DT_COMPLEX64, DT_INT64, DT_QINT8, DT_QUINT8, DT_QINT32, DT_BFLOAT16, DT_QINT16, DT_QUINT16, DT_UINT16, DT_COMPLEX128, DT_HALF, DT_UINT32, DT_UINT64, DT_VARIANT]; is_commutative=true; is_aggregate=true> [Op:AddN] name:
```

Coult you try to execute it with those prints and the same package versions as me?
Thank you so much and sorry for the inconvenience.

**Comment by gaikwadrahul8** [comment]
Hi @ArnauPujantellNavas,

After thorough investigation and version compatibility testing, I've identified a reliable solution for the encountered issue.
Initially, I attempted installation with `pip install tensorflow[and-cuda]==2.18.0 keras==3.7.0` which reproduced the previous error scenario which you mentioned in the issue template. I discovered a compatible combination that resolves the current challenges so please try below recommended temporary workaround at the moment, please refer this [gist-file](https://colab.research.google.com/gist/gaikwadrahul8/60a77b7a78c0d95fa107b01defe086e8/tf-mirroredstrategy-issue-80951.ipynb)

`pip install tensorflow[and-cuda]==2.16.1 keras==3.3.0
`

If issue still persists with this `pip install tensorflow[and-cuda]==2.16.1 keras==3.3.0` versions combination please let us know for further investigation.

Thank you for your cooperation and patience.

**Comment by ArnauPujantellNavas** [comment]
Hi @gaikwadrahul8,
I've tested it and it works as a workaround. Are you planning to fix it for the next releases?

Thank you so much for your time.

**Comment by willianck** [comment]
I tried the dummy example and can confirm the issue has not been fixed in the ` tensorflow 2.18.0` release. Has this ever been addressed ?

**Comment by xpdoc** [comment]
Hi, same issue here with a similar model structure using tf 2.18.0

**Comment by HusainKapadia** [comment]
Same issue with tf 2.16.2 using MirroredStrategy with 2 GPUs
