### ISSUE TITLE
Installed from source; unable to import tensorflow

### ISSUE THREAD

**Issue by evilrobot69** [tensorflow/tensorflow#81]
ariw@clairvoyance:~/tensorflow$ python
Python 2.7.6 (default, Jun 22 2015, 18:00:18) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
ImportError: No module named core.framework.graph_pb2
\>\>\> exit()

**Comment by graphific** [comment]
did you pip install the python wheel as well?

**Comment by felixduvallet** [comment]
I have the same issue, installed tensorflow using pip:
`sudo pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl`

Running python 2.7.6 on Linux Mint 17.1 (so basically Ubuntu 14.04).

**Comment by felixduvallet** [comment]
I resolved my issue by uninstalling another version of protobuf that was previously installed with pip:
`sudo pip uninstall protobuf`
then installing the python wheel again.

**Comment by sri-25** [comment]
Checkout issue #61 and #51

**Comment by ebrevdo** [comment]
This error often happens if you open a python shell in the base bazel directory.  The directory "tensorflow" in there confuses python.  Try running python from another directory; let us know if `import tensorflow` does not work then.
