### ISSUE TITLE
ASM ERROR TENSORFLOW LITE DELEGATES FLEX

### ISSUE THREAD

**Issue by rishik1001** [tensorflow/tensorflow#81013]
ERROR: /mnt/c/Rishik/tensorflow-2.17.0/tensorflow/core/kernels/BUILD:6319:11: Compiling tensorflow/core/kernels/meta_support.cc failed: (Exit 1): arm-none-linux-gnueabihf-gcc failed: error executing command (from target //tensorflow/core/kernels:meta_support) /mnt/c/Users/Rishik/Desktop/bazel_lite/52dfed56af7b723f8fecdd2d8ef8c52a/external/armhf_linux_toolchain/bin/arm-none-linux-gnueabihf-gcc -fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections ... (remaining 137 arguments skipped)
In file included from external/gemmlowp/meta/streams.h:307,
                 from external/gemmlowp/meta/quantized_mul_kernels.h:22,
                 from ./tensorflow/core/kernels/meta_support.h:21,
                 from tensorflow/core/kernels/meta_support.cc:18:
external/gemmlowp/meta/streams_arm_32.h: In static member function 'static void gemmlowp::meta::GemmExecutorPackRHS::ExecuteDispatch3D(const P&) [with P = gemmlowp::meta::GemmParams<unsigned char, int, gemmlowp::meta::RowMajorWithSum, gemmlowp::meta::RowMajorWithSum, gemmlowp::meta::QuantizedStaticPreprocessedAsInt32, gemmlowp::meta::RowMajor>; int m = 2; int n = 4; int k = 8; int m_leftovers = 0; int n_leftovers = 0; int k_leftovers = 0]':
external/gemmlowp/meta/streams_arm_32.h:1535:3: error: 'asm' operand has impossible constraints
 1535 |   asm volatile(
      |   ^~~
Target //tensorflow/core/kernels:meta_support failed to build

Above error is shown for the bazel command
 bazel --output_user_root=/mnt/c/Users/Rishik/Desktop/bazel_lite build --config=elinux_armhf -c opt --copt=-march=armv7-a --copt=-mfl
oat-abi=hard --repo_env=TF_PYTHON_VERSION=3.11 //tensorflow/core/kernels:meta_support

**Comment by Venkat6871** [comment]
Hi **@rishik1001** ,
We see that the issue [template]( https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyze the issue [tf version, steps followed before you ran into this error or stand alone code/colab gist to reproduce the issue faced.
Thank you!

**Comment by Epidath** [comment]
I have the same error. Does anyone have a possible solution?
