### ISSUE TITLE
Scatter_nd doc not clear about concurrent updates

### ISSUE THREAD

**Issue by aliosmanulusoy** [tensorflow/tensorflow#8102]
The doc on the scatter_nd does not specify the consequence of multiple updates that reference the same location. 

I've tested this using the following code:

```python
indices = tf.constant([[4], [3], [1], [1]])
updates = tf.constant([9, 10, 11, 12])
shape = tf.constant([8])
scatter = tf.scatter_nd(indices, updates, shape)
with tf.Session() as sess:
  print sess.run(scatter)
```
The resulting tensor is:
```python
[0, 23, 0, 10, 9, 0, 0, 0]
```
So it seems the updates are added. Is this the intended usage? If so, it would be great to clarify this in the docs. 

Thanks!

**Comment by drpngx** [comment]
The CPU/GPU implementation initializes to zero and uses [add](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/scatter_nd_op.cc#L189) rather than assign.

It seems like a somewhat stronger promise than assign, where the output would be
```
[0, 12, 0, 10, 9, 0, 0, 0] or [0, 11, 0, 10, 9, 0, 0, 0]
```
non-deterministically, or in an order that we define.

@rmlarsen for opinion

**Comment by raingo** [comment]
@vrv the document is still confusing for this function.

> WARNING: The order in which updates are applied is nondeterministic, so the output will be nondeterministic if indices contains duplicates.

Even if order is nondeterministic, the summation is deterministic. Why not just promise that duplicates will be summed?

**Comment by vrv** [comment]
I didn't write the code or the doc, so I'm not the best person to clarify this, but maybe because order of operations for floating point values matter that it's still technically a non-deterministic result.  See "catastrophic cancellation" for cases where addition order matters.

**Comment by vrv** [comment]
Also, I think the language implies all updates will be attempted in some order, but feel free to send a PR to update the doc to clarify that point, if you think it's useful.

**Comment by raingo** [comment]
OK. Thanks.

**Comment by teramototoya** [comment]
Is there a way to change add to update?

**Comment by csnemes2** [comment]
@teramototoya what I did as a hack: with https://www.tensorflow.org/api_docs/python/tf/unique_with_counts i counted the multiplication in the indices and i divided the tensor which was holding the values (aka tensor named 'updates' in the first comment)  with this counter
so when add() comes it will undo what the division made

you can check this simple script: https://github.com/csnemes2/conv-net-viz/blob/master/ut_unpool.py

**Comment by teramototoya** [comment]
@csnemes2 I also tried the same implementation as your hack, but I could not do it well.
It worked well with your implementation! Thank you!
