### ISSUE TITLE
How to Implement a Secure, Multi-Tenant tensorflow?

### ISSUE THREAD

**Issue by coolsunchen** [tensorflow/tensorflow#8110]
I am using tensorflor as miner/ML platform, and now customers are required to support multi-tenant capabilities;
Between the tenants to achieve resource isolation (CPU, MEM, disk, etc.), security isolation.
How do i achieve it?
Has the new version already planned for these features?

**Comment by yaroslavvb** [comment]
TensorFlow is basically a math library, multi-tenant capabilities should be enabled by whichever system you are using to run it (Docker/Kubernetes is a good combination IMHO)
