### ISSUE TITLE
image_retrainning can not run

### ISSUE THREAD

**Issue by shanxiongfei** [tensorflow/tensorflow#8114]
my tensorflow  version is 1.0.0
I follow the image_retraining.md
1.    curl -O http://download.tensorflow.org/example_images/flower_photos.tgz
tar xzf flower_photos.tgz
2.   bazel build --config opt tensorflow/examples/image_retraining:retrain

but when I run
 bazel-bin/tensorflow/examples/image_retraining/retrain
there is a errorLast login: Mon Mar  6 14:46:11 on ttys000
wangjingsideMacBook-Pro:~ ginthva$ cd tensorflow
wangjingsideMacBook-Pro:tensorflow ginthva$ bazel build --config opt tensorflow/examples/image_retraining:retrain
INFO: Found 1 target...
Target //tensorflow/examples/image_retraining:retrain up-to-date:
  bazel-bin/tensorflow/examples/image_retraining/retrain
INFO: Elapsed time: 0.374s, Critical Path: 0.00s
wangjingsideMacBook-Pro:tensorflow ginthva$ bazel-bin/tensorflow/examples/image_retraining/retrain 
Traceback (most recent call last):
  File "/Users/ginthva/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/examples/image_retraining/retrain.py", line 79, in <module>
    import tensorflow as tf
  File "/Users/ginthva/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/ginthva/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 124, in <module>
    from tensorflow.python.platform import test
  File "/Users/ginthva/tensorflow/bazel-bin/tensorflow/examples/image_retraining/retrain.runfiles/org_tensorflow/tensorflow/python/platform/test.py", line 50, in <module>
    import mock                # pylint: disable=g-import-not-at-top,unused-import
ImportError: No module named mock

I also uninstall mock and reinstall, but it doesn't work. what should I  do?

**Comment by prb12** [comment]
Please provide details about what platform you are using  (operating system, architecure). Also please include details of how you installed TensorFlow. We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by shanxiongfei** [comment]
It's so happy to receive your response, thank you very     @prb12 
My system is macOS Sierra 10.12.
3,2.9 GHz Intel Core i5,
8 GB 2133 MHz LPDDR3
Intel Iris Graphics 550 1536 MB
I install tensorflow according  to install_sources.md

**Comment by shanxiongfei** [comment]
My system is macOS Sierra 10.12.
Python 2.7.13
GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)
bazel release 0.4.4-homebrew

**Comment by shanxiongfei** [comment]
My system is macOS Sierra 10.12.
Python 2.7.13
GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)
bazel release 0.4.4-homebrew

wangjingsideMacBook-Pro:tensorflow ginthva$ pip install mock
Requirement already satisfied: mock in /usr/local/lib/python2.7/site-packages
Requirement already satisfied: pbr>=0.11 in /usr/local/lib/python2.7/site-packages (from mock)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /usr/local/lib/python2.7/site-packages (from mock)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python2.7/site-packages/six-1.10.0-py2.7.egg (from mock)

**Comment by prb12** [comment]
The symptoms seem related to the problems in #7980.  Could you please see if the solution in that thread works for you?

**Comment by roseyao** [comment]
Having the same issues, have reinstalled tensorflow and pip, still getting same error?

**Comment by 109km** [comment]
Same issue here.
```
bleach (1.5.0)
funcsigs (1.0.2)
html5lib (0.9999999)
Markdown (2.2.0)
mock (2.0.0)
numpy (1.12.1)
pbr (3.0.1)
pip (9.0.1)
protobuf (3.3.0)
setuptools (36.0.1)
six (1.10.0)
tensorflow (1.2.0rc0)
Werkzeug (0.12.2)
wheel (0.29.0)
```
Still tell me ``` ImportError: No module named mock ```

I also tried the methods in #7980 , none is working for me.
My system info : 
```
macOS Sierra 10.12.4
Python 2.7.13
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
```
