### ISSUE TITLE
A bug report about Tensorboard

### ISSUE THREAD

**Issue by HuMingqi** [tensorflow/tensorflow#8122]
# Bug Description:
In win10 platfrom, you use command __tensorboard --logdir=path/to/logdir__ when navigate to __another driver__ which don't include the logdir. __Tensorboard will think the logdir in that driver__.
# Example:
In VS Prompt:

1.  **F**:\Program Files (x86)\Microsoft Visual Studio 14.0>tensorboard --logdir=**G:\machine_learning\models\Alexnet_tf\log_** --debug

__cmd output__:
INFO:tensorflow:TensorBoard is in debug mode.
INFO:tensorflow:Starting TensorBoard in directory F:\Program Files (x86)\Microsoft Visual Studio 14.0
INFO:tensorflow:**TensorBoard path_to_run is: {'F:\\machine_learning\\models\\Alexnet_tf\\log_': 'G'}**
INFO:tensorflow:Event Multiplexer initializing.
INFO:tensorflow:Event Multiplexer done initializing
INFO:tensorflow:TensorBoard reload process beginning
INFO:tensorflow:Starting AddRunsFromDirectory: F:\machine_learning\models\Alexnet_tf\log_
INFO:tensorflow:Done with AddRunsFromDirectory: F:\machine_learning\models\Alexnet_tf\log_
INFO:tensorflow:TensorBoard reload process: Reload the whole Multiplexer
INFO:tensorflow:Beginning EventMultiplexer.Reload()
INFO:tensorflow:Finished with EventMultiplexer.Reload()
INFO:tensorflow:TensorBoard done reloading. **Load took 0.000 secs**
INFO:tensorflow:TensorBoard is tag: b'41'
Starting TensorBoard b'41' on port 6006
(You can navigate to http://192.168.1.202:6006)

__Nothing you can see in Chrome, a blank page.__

2.  **G**:\>tensorboard --logdir=**G:\machine_learning\models\Alexnet_tf\log_** --debug

__cmd output__:
INFO:tensorflow:TensorBoard is in debug mode.
INFO:tensorflow:Starting TensorBoard in directory G:\
INFO:tensorflow:**TensorBoard path_to_run is: {'G:\\machine_learning\\models\\Alexnet_tf\\log_': 'G'}**
INFO:tensorflow:Event Multiplexer initializing.
INFO:tensorflow:Event Multiplexer done initializing
INFO:tensorflow:TensorBoard reload process beginning
INFO:tensorflow:Starting AddRunsFromDirectory: G:\machine_learning\models\Alexnet_tf\log_
INFO:tensorflow:Adding events from directory G:\machine_learning\models\Alexnet_tf\log_
INFO:tensorflow:Constructing EventAccumulator for G:\machine_learning\models\Alexnet_tf\log_
INFO:tensorflow:Done with AddRunsFromDirectory: G:\machine_learning\models\Alexnet_tf\log_
INFO:tensorflow:TensorBoard reload process: Reload the whole Multiplexer
INFO:tensorflow:Beginning EventMultiplexer.Reload()
DEBUG:tensorflow:Opening a record reader pointing at G:\machine_learning\models\Alexnet_tf\log_\events.out.tfevents.1488779830.ubuntu-Default-string
INFO:tensorflow:TensorBoard is tag: b'41'
Starting TensorBoard b'41' on port 6006
(You can navigate to http://192.168.1.202:6006)
DEBUG:tensorflow:No more events in G:\machine_learning\models\Alexnet_tf\log_\events.out.tfevents.1488779830.ubuntu-Default-string
INFO:tensorflow:No path found after G:\machine_learning\models\Alexnet_tf\log_\events.out.tfevents.1488779830.ubuntu-Default-string
INFO:tensorflow:Finished with EventMultiplexer.Reload()
INFO:tensorflow:TensorBoard done reloading.** Load took 4.234 secs**

__Now Scalars Page has loss graph defined.__

# Question:
Why Tensorboard read event-file depend on the command where inputed(As shown abone, logdir in G: but go to F: ) , It shouldn't be.

**Comment by mrry** [comment]
Thanks for reporting this! We're already tracking this problem as part of issue #7856, so please follow the discussion there.

**Comment by HuMingqi** [comment]
@mrry Thanks for your reminder, I should have checked whether it was reported.
