### ISSUE TITLE
yann.lecun.com/exdb/mnist/ down

### ISSUE THREAD

**Issue by jegli** [tensorflow/tensorflow#8126]
The website of Yann LeCun is down at the moment. 
Therefore the MNIST-Script for downloading the files doesn't work either. (-> learn/python/learn/datasets/mnist.py won't work)
Are there any mirrors?

**Comment by prb12** [comment]
Apparently (according to @kakawait) you can download dataset via archive machine, e.g. https://web.archive.org/web/20160828233817/http://yann.lecun.com/exdb/mnist/index.html 

You will need to download and copy the files to your training data directory manually.
