### ISSUE TITLE
'Download and Setup' link in README.md is dead

### ISSUE THREAD

**Issue by ChristopherWMartin** [tensorflow/tensorflow#8142]
The link points to: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md

**Comment by prb12** [comment]
@josh11b I think you just moved the docs that this link used to point to?

**Comment by josh11b** [comment]
New link is https://www.tensorflow.org/install/

**Comment by josh11b** [comment]
I found some references to os_setup.md and will update them.

**Comment by MicaelCarvalho** [comment]
Pull request: #8169
