### ISSUE TITLE
import tensorflow as tf ,display "Segmentation fault" And exit python env

### ISSUE THREAD

**Issue by blackhu** [tensorflow/tensorflow#8149]
os: CentOS Linux release 7.0.1406 (Core)
os kernel:.10.0-123.9.3.el7.x86_64
python version:Python 2.7.5
gcc version:GCC 4.8.5 20150623
         i download tensorflow-1.0.0-cp27-none-linux_x86_64.whl and install it.when i open python,input "import tensorflow as tf",display "Segmentation fault" and exit python;

**Comment by blackhu** [comment]
i download setup file md5sum hash is :842f6e69897c4dbb583f855fb685c2e7
.download source from github description “Installation”

**Comment by prb12** [comment]
Could you please clarify what you mean by 'download source from github description “Installation”'?  Are you downloading using the links in the README.md on [this](https://github.com/tensorflow/tensorflow) page ?  

If so, then please note that the link on that page to **stable** binary releases is currently down, so is it possible that you are using the links under "People who are a little more adventurous can also try our nightly binaries:" ?   These are from a live repo and so not guaranteed to be bug free!

Could you please try following the instructions on this page: https://www.tensorflow.org/install/install_linux

**Comment by asimshankar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
