### ISSUE TITLE
Two different user_ops directories

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#8150]
There are currently two different directories labeled `user_ops`, each with example(s):
* https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/user_ops
* https://github.com/tensorflow/tensorflow/tree/master/tensorflow/user_ops

Is this intentional or vestigial?

Might reduce confusion to merge these.

**Comment by keveman** [comment]
The one in `tensorflow/user_ops` is demonstrating user defined ops built with `tf_custom_op_library`, i.e., when you build custom operations with TF binary installed, the one in `tensorflow/core/user_ops` is demonstrating how you can build user ops with TF sources.

**Comment by cancan101** [comment]
I'm not sure I 100% understand the distinction here. At the very least maybe a Readme file in the respective directories? That being said I would think the same example should appear in both unless there is a reason to use fact in one case and Ackerman in the other?
