### ISSUE TITLE
Calling Generic conv with data_format='NCHW' Leads to Segfault

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#8151]
Running on 1.0.0.2 Docker image, this code:
```python

from tensorflow.python.ops import nn_ops
import tensorflow as tf
import numpy as np

images = np.ones((1,1,15,1)).astype(np.float32)
filters = 1 * np.ones((1,1,1,1), np.float32)

with tf.Session(''):
  output = nn_ops.conv2d(
      images,
      filters,
      strides=[1,1,1,1],
      padding='VALID',
      data_format='NCHW',
  ).eval()
```
yields:
```
F tensorflow/core/kernels/conv_ops.cc:65] Check failed: data_format == FORMAT_NHWC Generic conv implementation only supports NHWC te
nsor format for now.
Aborted (core dumped)
```
While it does print a helpful error message, it then proceeds to core dump.

I also see this issue on macOS

**Comment by prb12** [comment]
@zheng-xq This probably shouldn't have a CHECK fail?  Is there no way it could raise an error via the OpKernel constructor?   (e.g. so interactive usage doesn't take out the runtime!)

**Comment by zheng-xq** [comment]
Yes, we can change that to a python error. cancan101, does that solve your problem? 

The underlying issue is that we don't have fast CPU conv implementation of NCHW format. This is an area that is contribution-welcome.

**Comment by cancan101** [comment]
Yes that would solve my problem.

**Comment by prb12** [comment]
I think a warning on first use and a non-fatal error would seem more appropriate.

**Comment by yzhwang** [comment]
@cancan101 For tensorflow 1.2.0-rc2 it gives this error:
UnimplementedError: Generic conv implementation only supports NHWC tensor format for now.
	 [[Node: Conv2D = Conv2D[T=DT_FLOAT, data_format="NCHW", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](Conv2D/input, Conv2D/filter)]]

Close for now because I think this solves your problem, if not, please reopen.

**Comment by simonkhan12ka4** [comment]
i get this error for my code  can somebody help?
error
	 [[Node: Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_Placeholder_0_0, weights/read)]]

#from tensorflow.python.client import device_lib
#print(device_lib.list_local_devices())

import os
import time
import math
import numpy as np
import tensorflow as tf
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# Load the CIFAR10 dataset
from keras.datasets import cifar10
baseDir = os.path.dirname(os.path.abspath('__file__')) + '/'
classesName = ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']


# Select device
deviceType = "/cpu:0"


#def train():
(xTrain, yTrain), (xTest, yTest) = cifar10.load_data()
xVal = xTrain[49000:, :].astype( np.float )
yVal = np.squeeze( yTrain[49000:, :] )
xTrain = xTrain[:49000, :].astype( np.float )
yTrain = np.squeeze( yTrain[:49000, :] )
yTest = np.squeeze( yTest )
xTest = xTest.astype( np.float )
print( 'Train image shape:    {0}'.format( xTrain.shape ) )
print( 'Train label shape:    {0}'.format( yTrain.shape ) )
print( 'Validate image shape: {0}'.format( xVal.shape ) )
print( 'Validate label shape: {0}'.format( yVal.shape ) )
print( 'Test image shape:     {0}'.format( xTest.shape ) )
print( 'Test label shape:     {0}'.format( yTest.shape ) )

batch_size = 100
learning_rate = 0.0000006
max_steps = 1100

meanImage = np.mean( xTrain, axis=0 )
xTrain -= meanImage
xVal -= meanImage
xTest -= meanImage
tf.reset_default_graph()
with tf.device( deviceType ):
    x = tf.placeholder( tf.float32, [None, 32,32,3] )
    y= tf.placeholder( tf.int64, [None] )
    filter = tf.get_variable( 'weights', [7, 7, 3, 64],initializer=tf.truncated_normal_initializer( stddev=5e-2, dtype=tf.float32 ),
                              dtype=tf.float32 )

    conv1 = tf.nn.conv2d(x, filter, strides=[1,1,1,1], padding="SAME") # Stride [batch, height, width, channels]
    conv1=tf.nn.relu(conv1)
    conv1 = tf.layers.max_pooling2d( conv1, 2, 2 )
    fc1 = tf.contrib.layers.flatten( conv1 )
    fc1 = tf.layers.dense( fc1, 1024 )
    fc1 = tf.nn.relu( fc1 )
    yOut = tf.layers.dense( fc1, 10 )

    # Define Loss
    totalLoss = tf.losses.hinge_loss( tf.one_hot( y, 10 ), logits=yOut )
    meanLoss = tf.reduce_mean( totalLoss )

    # Define Optimizer
    optimizer = tf.train.AdamOptimizer( 5e-4 )
    trainStep = optimizer.minimize( meanLoss )

    # Define correct Prediction and accuracy
    correctPrediction = tf.equal( tf.argmax( yOut, 1 ), y )
    accuracy = tf.reduce_mean( tf.cast( correctPrediction, tf.float32 ) )
    lossHistory=[]

    with tf.Session()as sess:
        sess.run( tf.global_variables_initializer() )
        for i in range( max_steps):

            s = np.arange( xTrain.shape[0] )
            np.random.shuffle( s )
            xTr = xTrain[s]
            yTr = yTrain[s]
            batch_xs = xTr[:100]
            batch_ys = yTr[:100]
            main_loss, _ = sess.run( [meanLoss, trainStep],
                                     feed_dict=({x: batch_xs, y: batch_ys}) )
            train_accuracy = sess.run( accuracy, feed_dict={x: xTrain, y: yTrain} )
            test_accuracy = sess.run( accuracy, feed_dict={x: xTest, y: yTest} )

            lossHistory.append( main_loss )
            if i % 100 == 0 and len( lossHistory ) is not 0:
                print( 'Loop {0} loss {1} '.format( i, lossHistory[i] ) )
                print( 'Train_Accuracy {0} Test_Accuracy {1}'.format( train_accuracy, test_accuracy ) )

# Train Model

                # def train():
#     (xTrain, yTrain), (xTest, yTest) = cifar10.load_data()
#     xVal = xTrain[49000:, :].astype( np.float )
#     yVal = np.squeeze( yTrain[49000:, :] )
#     xTrain = xTrain[:49000, :].astype( np.float )
#     yTrain = np.squeeze( yTrain[:49000, :] )
#     yTest = np.squeeze( yTest )
#     xTest = xTest.astype( np.float )

    # batch_size = 10
    # learning_rate = 0.0000006
    # max_steps = 1100
    # print( 'Train image shape:    {0}'.format( xTrain.shape ) )
    # print( 'Train label shape:    {0}'.format( yTrain.shape ) )
    # print( 'Validate image shape: {0}'.format( xVal.shape ) )
    # print( 'Validate label shape: {0}'.format( yVal.shape ) )
    # print( 'Test image shape:     {0}'.format( xTest.shape ) )
    # print( 'Test label shape:     {0}'.format( yTest.shape ) )
    #
    # meanImage = np.mean( xTrain, axis=0 )
    # xTrain -= meanImage
    # xVal -= meanImage
    # xTest -= meanImage

#     # Reshape data from channel to rows
#     xTrain = np.reshape( xTrain, (xTrain.shape[0], -1) )
#     xVal = np.reshape( xVal, (xVal.shape[0], -1) )
#     xTest = np.reshape( xTest, (xTest.shape[0], -1) )
#
#     # Add bias dimension columns
#
#     print( 'Train image shape after add bias column:   {0}'.format( xTrain.shape ) )
#     print( 'Val image shape after add bias column:     {0}'.format( xVal.shape ) )
#     print( 'Test image shape after add bias column:    {0}'.format( xTest.shape ) )
#
#     image_holder = tf.placeholder( tf.float32, shape=[None, 3072] )
#
#     #label_holder = tf.placeholder( tf.int64, shape=[None] )
#     label_holder=tf.placeholder(tf.int64, [None])
#
#     weight = tf.Variable( tf.zeros( [3072, 10] ), name='weights' )
#     bias = tf.Variable( tf.zeros( [10] ), name='bias' )
#
#     # Define the classifier's result
#     logits = tf.matmul( image_holder, weight ) + bias
#
#     loss = tf.reduce_mean( tf.nn.sparse_softmax_cross_entropy_with_logits( logits=logits,
#                                                                            labels=label_holder ) )
#
#     # Define the training operation
#     train_step = tf.train.GradientDescentOptimizer( learning_rate ).minimize( loss )
#
#     lossHistory = []
#     correct_prediction = tf.equal( tf.argmax( logits, 1 ), label_holder )
#
#     # Operation calculating the accuracy of our predictions
#     accuracy = tf.reduce_mean( tf.cast( correct_prediction, tf.float32 ) )
    #saver = tf.train.Saver()


        # cwd = os.getcwd()
        # saver_route = saver.save( sess, cwd + "/model/model.ckpt" )
        # print( "Model saved in this directory: %s" % saver_route )
        #pass


# print ('Real label is:', np.argmax(yTest[num]))
# print ('Neural Network predicted', (classification[0]))
# import string
#
#
# def test(args):
#     classnames = ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
#
#     image_holder = tf.placeholder( tf.float32, shape=[None, 3072] )
#     img = cv2.imread( args )
#     print (img.shape)
#
#     img = img.reshape( (1, img.shape[0] * img.shape[1] * img.shape[2]) )
#     #img = img.reshape (1,3072)
#     print (img)
#
#     img = cv2.resize( img, (3072, 1) )
#     #print (img.shape)
#     img = img.astype( np.float32 )
#     print (img)
#     cwd = os.getcwd()
#
#     with tf.Session() as sess:
#         model = tf.train.import_meta_graph( cwd + "/model/model.ckpt.meta", clear_devices=True )
#         model.restore( sess, tf.train.latest_checkpoint( cwd + "/model/" ) )
#         weight = sess.run( 'weights:0' )
#
#         bias = sess.run( 'bias:0' )
#         logits = tf.matmul( image_holder, weight ) + bias
#         prediction = tf.nn.softmax( logits )
#
#         answer= sess.run( prediction, feed_dict={image_holder: img} )
#         print (answer.shape)
#         print (answer)
#
#         answer = answer.reshape(-1)
#         print (answer.shape)
#         print(answer)
#
#         score= answer.argmax(axis=0)
#         print(score)
#
#         print( classnames[score] )
#         pass
#
#
# def main(argv):
#     if str( argv[0] ) == 'train':
#         train()
#         return
#
#     if str( argv[0] ) == 'test':
#         test( str( argv[1] ) )
#
#
#
#
#
# if __name__ == '__main__':
#     main( sys.argv[1:] )
#
#

**Comment by Akila92** [comment]
I have encountered the same error. Im using a CPU not GPU. So I changed the data format of the tensors to overcome in the code.Above Suggested solutions will not work for CPU. 
More can be found in tensorflow documentation. Refer to  data formats
https://www.tensorflow.org/guide/performance/overview
