### ISSUE TITLE
Add CI build for XLA

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#8156]
There's no continuous testing for XLA build, so that head can contain errors.
Right now it's broken with syntax error, and this error has been there since Mar 2 or earlier -- https://github.com/tensorflow/tensorflow/pull/8039

XLA got a lot of publicity at the TF summit, and there've been 90 issues filed on it, 5 of them connected to this breakage. Keeping head free of build errors for XLA build could ease the support burden on this list. @caisq @jhseu

**Comment by gunan** [comment]
Sorry for the delays.
This is now complete.
We have builds running on github master, and also now running builds on all pull requests.
