### ISSUE TITLE
error while loading shared libraries: __vdso_time: invalid mode for dlopen():Invalid argument

### ISSUE THREAD

**Issue by IvyGongoogle** [tensorflow/tensorflow#8158]
sorry to trouble you. I use Centos6.4 and CUDA7.0 and I have no ‘sudo’ authority. I install tensorflow from the source. After I installed glib2.17 and set LD_LIBRARY_PATH, I encountered the same error many people got:
`error while loading shared libraries: __vdso_time: invalid mode for dlopen():Invalid argument`

I try to search many solutions and there is still not a good or detailed solution. Can you give some detailed instructions. I think it will help many people. 
Thankyou very much in advance!

**Comment by MicaelCarvalho** [comment]
See #2924.

**Comment by asimshankar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
