### ISSUE TITLE
Can tensorflow run on freescale ubuntu system?

### ISSUE THREAD

**Issue by oneway3124** [tensorflow/tensorflow#816]
I have one board called udoo neo (from www.udoo.org) ,which run ubuntu system .
I want to port tensorflow on it. How to do it step by step?

**Comment by martinwicke** [comment]
For step by step instructions, stackoverflow is probably the better forum.
But if the board runs Ubuntu, you should be able to follow the regular
installation instructions.

**Comment by oneway3124** [comment]
Thanks for your answer!

**Comment by vasi1796** [comment]
HI. Did you get Tensorflow to work on the udoo neo?
