### ISSUE TITLE
Tensorflow more tutorial on java? 

### ISSUE THREAD

**Issue by oahzuw** [tensorflow/tensorflow#8160]
Tensorflow more tutorial on java? I can run the introductory program, but that's far enough and i want to learn more，I do not understand python,Can provide more java tutorials? Sorry for my bad english!

**Comment by snnn** [comment]
What kind of tutorial you want to see? I'd like to contribute some.

**Comment by oahzuw** [comment]
I would like to learn image recognition model training and application, the use of java to identify the characters on the picture or animals, my request can be too much! Thanks!

**Comment by virgincodes** [comment]
would see what i can do

**Comment by youngho1203** [comment]
I think the best one for java tutorial is that a mnist example by loading graph file which generated by python such as mnist_deep.py python file in mnist tutorials.
and the tutorial verify the same test accuracy ( ex : 0.9921 ) between java and python approach.

**Comment by snnn** [comment]
Hi @youngho1203 

They already have a similar thing:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/main/java/org/tensorflow/examples/LabelImage.java

**Comment by MarkDaoust** [comment]
Thanks for pointing that out @snnn.

@oahzuw If you really want to build and train models, you'll have a much easier time _learning python_ and doing it there. The java API operates at a much lower level, enough to run an existing model, but you wouldn't want to work in it directly.

It looks like there's already a link to that `LabelImage.java` example on the [install/install_java](https://www.tensorflow.org/install/install_java) page. Does anyone have other suggestions on how to make it easier to find?

**Comment by oahzuw** [comment]
@snnn   @MarkDaoust  @youngho1203   Thanks to everyone, decided to learn Python, too few examples of Java, thank you for your reply
