### ISSUE TITLE
tensorflow 2st test:"CUDA_ERROR_OUT_OF_MEMORY", What's wrong here???

### ISSUE THREAD

**Issue by Cynthia0629** [tensorflow/tensorflow#8170]
when I run:
>>>import tensorflow as tf
>>>hello=tf.constant('Hello, TensorFlow!')
>>>sess=tf.Session()
 ERROR came like that:
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 190.31MiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
E tensorflow/stream_executor/cuda/cuda_driver.cc:1002] failed to allocate 190.31M (199557120 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY

Is there anyone who can tell me what's wrong here??? Very gratefull for you help!!!

**Comment by MicaelCarvalho** [comment]
> Total memory: 7.92GiB
> Free memory: 190.31MiB

Something is already consuming all your GPU memory. Run `nvidia-smi` to see what's going on, you have no memory left.

If you are trying to run 2 TensorFlow codes in parallel, you will want to change the Session command to this:
```
config = tf.ConfigProto(log_device_placement=False, allow_soft_placement=True)
config.gpu_options.allow_growth=True
sess = tf.Session(config=config)
```

This way, TensorFlow won't allocate all of the memory for a single process.

**Comment by asimshankar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by cyrilfurtado** [comment]
I am running boston.py  from this tutorial 
https://www.tensorflow.org/get_started/input_fn, I have a Nvidia GPU 1080, tensorflow 1.3 on ubuntu 16.04
getting CUDA out of memory even for such a small dataset.
I could run a test for 10000 x 10000 matrix multiplication
