### ISSUE TITLE
tfdbg requires external ncurses on OSX

### ISSUE THREAD

**Issue by lemonzi** [tensorflow/tensorflow#8174]
- OSX 10.11.6
- TF from source at `8746f8ac9` (master HEAD from a few hours ago) without GPU
- XCode 8.2.1

When loading it, tfdbg crashes with a curses-related error. Was solved with `brew install homebrew/dupes/ncurses`. If this is really a dependency, it would be useful to mention it in the documentation or installation guide.

**Comment by caisq** [comment]
@lemonzi thanks for reporting this issue. Yes, curses/ncurses is a dependency for tfdbg on OSX. I will document it better in the next release.

**Comment by lemonzi** [comment]
Great, thanks! Good to know I didn't mess anything up. 

It also seems Terminal.app sends by default some weird character when pressing the delete key, and requires enabling the "Delete sends Control-H" option for the backspace to work. Not sure if this could be considered a bug -- maybe just having it on the FAQ will be enough.

**Comment by caisq** [comment]
@lemonzi Yep, we are aware that there are keybinding issues on Mac. There is an internal bug tracking that.

**Comment by caisq** [comment]
This is fixed. See the last Q&A "What are the platform-specific system requirements of tfdbg CLI in open-source TensorFlow?"  here: https://www.tensorflow.org/programmers_guide/debugger#frequently_asked_questions
