### ISSUE TITLE
Some Tensorboard metadata unsearchable

### ISSUE THREAD

**Issue by brannondorsey** [tensorflow/tensorflow#8177]
### Environment Info
Ubuntu 16.04
Tensorflow installed from pip, TF version 1.0.

### Potential Bug
I'm using Tensorboard's embedding projector to perform PCA/t-SNE on a dataset of features I've extracted from ~4K MIDI files. I've created a metadata TSV and pointed my Tensorflow application to it as instructed in [the documentation](https://www.tensorflow.org/get_started/embedding_viz). The metadata parses correctly in Tensorboard, however, when I use the inspector on the right-most panel, many of the fields seem to be unsearchable, or at least yield zero results for any valid query. Searching the first 13 fields (columns) works correctly, however 3 of the last fields are unsearchable, specifically `artist_terms`, `artist_mbtags`,  and `artist_location` in `embedding_logdir/metadata.tsv`.

I'm finding this to be the case independent of whether regex mode is enabled or disabled. I can also confirm that these fields are being parsed correctly as I can select a data point and view the values for these problematic fields. I've also tried creating a metadata file with only those three problematic fieldnames and they continue to misbehave in this test as well.

### Reproducing

I've attached my logdir complete with a checkpoint and metadata.tsv. To reproduce my results, extract the folder and launch Tensorboard from inside `embedding_logdir`'s parent directory like so:

```
tensorboard --logdir embedding_logdir
``` 

Tensorboard must be run from the parent directory of `embedding_logdir` to maintain the correct filepath I specified for the `metadata.tsv` file in my TF program. 
 
[embedding_logdir.tar.gz](https://github.com/tensorflow/tensorflow/files/825381/embedding_logdir.tar.gz)

**Comment by brannondorsey** [comment]
Checking in on this, has anyone been able to reproduce?

**Comment by davidlenz** [comment]
I tried to, unfortunately wasn't able to reproduce any metadata at all, though the embedding visualizations show up nicely.

What i did:

 Extract Files into 

> C:\Users\gcfghh\Downloads\tmp\embedding_logdir
![logdir](https://cloud.githubusercontent.com/assets/25869733/25002384/6d573634-204a-11e7-93db-92cb912d7540.PNG)


Windows cmd: 

> (py_35) C:\Users\gcfghh\Downloads\tmp\embedding_logdir>tensorboard --logdir embedding_logdir/

This is my result:
![tensor](https://cloud.githubusercontent.com/assets/25869733/25002417/9a9fbeea-204a-11e7-9e51-d64223c7f846.PNG)

Where did i mess up? I think it has to do something with the path i start tensorboard from, not sure though. Any enlightments would be greatly appreciated.

**Comment by brannondorsey** [comment]
Hey there, thanks for taking the time to try this out. I am only just seeing this, apologies as I must have missed it in my inbox. Are you able to search text strings in any of those columns (searching using the inspector panel on the right, not the left)? Cheers!

**Comment by davidlenz** [comment]
I should have taken the time to read all of your introductory question. 

I can't search through the problematic fields using the right panel, regardless of regex on/off.

**Comment by brannondorsey** [comment]
No worries at all, I appreciate your efforts in reproducing this. Its also worth noting that it isn't just me who is having trouble with this then. @dandelionmane any thoughts on this bug?

**Comment by dandelionmane** [comment]
I'm migrating this to https://github.com/tensorflow/tensorboard/issues/79, and assigning @dsmilkov and @nsthorat, who build the embedding projector, to take a look.
