### ISSUE TITLE
Double requirement given: tensorflow==1.0.0 when installing from binary url on Mac

### ISSUE THREAD

**Issue by keven425** [tensorflow/tensorflow#8180]
### Environment info
Operating System: MacOS 10.12.1

Installed version of CUDA and cuDNN: 
$ ls -l /usr/local/cuda/lib/libcud*
lrwxr-xr-x  1 root  wheel     33 Jan 31 21:18 /usr/local/cuda/lib/libcuda.1.dylib -> /usr/local/cuda/lib/libcuda.dylib
-rwxr-xr-x  1 root  wheel  13504 Sep 26 14:59 /usr/local/cuda/lib/libcuda.dylib
lrwxr-xr-x  1 root  wheel     45 Sep 26 15:00 /usr/local/cuda/lib/libcudadevrt.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudadevrt.a
lrwxr-xr-x  1 root  wheel     50 Sep 26 15:00 /usr/local/cuda/lib/libcudart.8.0.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.8.0.dylib
lrwxr-xr-x  1 root  wheel     46 Sep 26 15:00 /usr/local/cuda/lib/libcudart.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart.dylib
lrwxr-xr-x  1 root  wheel     49 Sep 26 15:00 /usr/local/cuda/lib/libcudart_static.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudart_static.a
lrwxr-xr-x  1 root  wheel     47 Oct 24 21:11 /usr/local/cuda/lib/libcudnn.5.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudnn.5.dylib
lrwxr-xr-x  1 root  wheel     45 Oct 24 21:11 /usr/local/cuda/lib/libcudnn.dylib -> /Developer/NVIDIA/CUDA-8.0/lib/libcudnn.dylib
lrwxr-xr-x  1 root  wheel     48 Oct 24 21:11 /usr/local/cuda/lib/libcudnn_static.a -> /Developer/NVIDIA/CUDA-8.0/lib/libcudnn_static.a

I attempted to install via `pip install tensorflow --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.0-py2-none-any.whl`

This is the error I got:
```
Double requirement given: tensorflow==1.0.0 from https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.0-py2-none-any.whl (already in tensorflow, name='tensorflow')
Storing debug log for failure in /Users/Keven/.pip/pip.log
```

Prior to this, I did `sudo pip uninstall tensorflow`

Error log:
```
$ cat /Users/Keven/.pip/pip.log
------------------------------------------------------------
/usr/local/bin/pip run on Tue Mar  7 15:51:21 2017
Downloading/unpacking https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.0-py2-none-any.whl
  Downloading from URL https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.0-py2-none-any.whl
Cleaning up...
Double requirement given: tensorflow==1.0.0 from https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.0-py2-none-any.whl (already in tensorflow, name='tensorflow')
Exception information:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 1262, in prepare_files
    self.add_requirement(req_to_install)
  File "/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg/pip/req.py", line 988, in add_requirement
    % (install_req, self.get_requirement(name), name))
InstallationError: Double requirement given: tensorflow==1.0.0 from https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.0-py2-none-any.whl (already in tensorflow, name='tensorflow')
```

**Comment by prb12** [comment]
The `pip` command you typed asks for a `tensorflow` package **and** a second specific package via a download URL.

Please double check your command against the ones in the instructions here: https://www.tensorflow.org/install/install_mac

i.e. use either 
`pip install --upgrade tensorflow`
or
`pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.0-py2-none-any.whl`

Please reopen if this doesn't solve your problem

**Comment by keven425** [comment]
My bad. Thanks for the quick answer!
