### ISSUE TITLE
 module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'

### ISSUE THREAD

**Issue by yydxlv** [tensorflow/tensorflow#8186]
my OS is win10， and the version of tensorflow is 1.0. but  errors occured : No module named 'tensorflow.models',the code snippets as follow:
from tensorflow.models.rnn.translate import data_utils
from tensorflow.models.rnn.translate import seq2seq_model

I am new to tensorflow ,thank you!

**Comment by shahbazsyed** [comment]
@yydxlv tensorflow.models has been moved to a separate [github repository](https://github.com/tensorflow/models) 

You can clone this locally,and move the models folder into your tensorflow folder (found in python site packages ). After that you will have tensorflow.models in your import working correctly. Also if you still have problems with getting data_utils and seq2seq_model not importing from rnn.translate, you can move those files out and rearrange a bit of code in the translate.py to make everthing work. I also had the same problem when starting out, and this was the workaround I used.

Hope it helps!

**Comment by doncat99** [comment]
if you are using Tensorflow 1.0, try import like this:

  import tensorflow as tf
  from tensorflow.contrib import rnn

  hidden_size = 100
  batch_size  = 100
  num_steps   = 100
  num_layers  = 100
  is_training = True
  keep_prob   = 0.4

  input_data = tf.placeholder(tf.float32, [batch_size, num_steps])
  lstm_cell = rnn.BasicLSTMCell(hidden_size, forget_bias=0.0, state_is_tuple=True)

**Comment by prb12** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
