### ISSUE TITLE
Update protobuf.cmake to 3.2.0?

### ISSUE THREAD

**Issue by andykernahan** [tensorflow/tensorflow#8187]
Hello,

The [protobuf.cmake](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/external/protobuf.cmake) is building an old version of protobuf, one which specifically does not include the parsing limit bump from 64MB to 2GB (referenced in #582 and resolved by #7338). It is currently building a fork which contains a specific MSVC [fix](https://github.com/mrry/protobuf/commit/1d2c7b6c7376f396c8c7dd9b6afd2d4f83f3cb05); this fix has been [merged](https://github.com/google/protobuf/pull/2203) into the main protobuf repository and is included in 3.2.0.

Is it possible to align the repository and tree used by protobuf.cmake to that used by workspace.bzl? I'm happy to submit a PR.

Cheers.

**Comment by prb12** [comment]
@mrry @benoitsteiner Could one of you please comment on this suggestion?

**Comment by mrry** [comment]
It sounds like a good suggestion.

**Comment by benoitsteiner** [comment]
No objection to using the same protobuf version from cmake and bazel. I'd recommend we update the cmake files to extract the protobuf version from workspace.bzl instead of hardcoding a value in protobuf.cmake

**Comment by andykernahan** [comment]
Hi @benoitsteiner, such a change may make it difficult if workspace.bzl were to be updated to a version of protobuf which introduced another platform quirk. Is it potentially more robust to manage them independently, given that cmake can target a boarder range of platforms?

**Comment by andykernahan** [comment]
However, on reflection, the same difficulty would arise if bazel were consolidated on for all platforms.

In the short-term: would you accept a PR which simply updates the repository and tree?
In the long-term: I can either create another ticket to track to work, or leave this one open.

Cheers.
