### ISSUE TITLE
Feature request: Tensorboard: Set defaults (Split on underscores, tooltip sorting, ...)

### ISSUE THREAD

**Issue by haeusser** [tensorflow/tensorflow#8188]
It would be awesome to be able to set preferred defaults for TensorBoard somewhere, in particular:

- Split on underscores
- Tooltip sorting method

Best,
Philip

**Comment by dandelionmane** [comment]
How would you feel about saving into browser localStorage?

**Comment by dandelionmane** [comment]
Closing since we didn't hear a response. @haeusser feel free to re-open at https://github.com/tensorflow/tensorboard/issues
