### ISSUE TITLE
tf.image.crop_and_resize not returning proper values of the cropped data

### ISSUE THREAD

**Issue by SumithRZT** [tensorflow/tensorflow#8189]
I am using **tf.image.crop_and_resize**  to obtain cropped data of image but the function is returning all zeroes instead of pixel values.

My code is like this 
```
ori_image = Image.open('/home/sumith/imagepyramids/2.jpg')
img_data = np.expand_dims(np.asarray(ori_image).astype(np.float32), axis=0)
with tf.Session() as sess:
   sess.run([tf.global_variables_initializer(), tf.local_variables_initializer()])
   cropped_list = sess.run(tf.image.crop_and_resize(image=img_data, 
      boxes=[[0, 0, 50, 50]], crop_size=[40, 36],   box_ind[0]))
   print(np.asarray(ori_image.crop([0, 0, 50, 50]).resize((40, 36)).astype(np.float32))
   print(cropped_list[0])
```
the first print statement prints the proper cropped data of image but the second print gives the array in proper shape as given in **crop_size** but array full of zeros.

the first print statement's output
```
[[[  60.   46.   42.]
  [  60.   46.   40.]
  [  63.   45.   38.]
  ..., 
  [  71.   68.   85.]
  [  73.   71.   86.]
  [  74.   73.   87.]]
  ..., 
  [  69.   70.   93.]
  [  75.   74.   94.]
  [  78.   74.   93.]]]
```

the second print statement's output
```
[[[ 59.  45.  42.]
  [  0.   0.   0.]
  [  0.   0.   0.]
  ..., 
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]
 ....,
  [  0.   0.   0.]
  [  0.   0.   0.]
  [  0.   0.   0.]]]
```
It would be of great help if I get answer for this.

**Comment by prb12** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by SumithRZT** [comment]
Hi , 
Below are the platform details
Operating System : Ubuntu 14.04 
Processor : Intel® Core™ i7-2820QM CPU @ 2.30GHz × 8 
tensorflow version : 0.12.0-rc0
python version : 3.4

**Comment by prb12** [comment]
You example has numerous syntax errors, but I think the underlying problem may be that you are passing incorrect values for the `boxes` arg, which should be _relative_ coordinates in the range [0,1]

Please see the following documentation
https://www.tensorflow.org/versions/r0.12/api_docs/python/image/cropping
https://www.tensorflow.org/api_docs/python/tf/image/crop_and_resize

Please let me know if this fixes your problem?

**Comment by SumithRZT** [comment]
Hi ,
I went through the tensoflow docs but didn't get much. As you told it as a relative co ordinate in the range [0, 1], It would be helpful if you give a code snippet on that.
I didn't find any syntax errors in the code snippet I gave above. I have missed the imports.

**Comment by prb12** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
