### ISSUE TITLE
Tflite x86 lib and dll for windows

### ISSUE THREAD

**Issue by apratimankit** [tensorflow/tensorflow#81900]
I  tried to build x86 lib in windows. But it does'nt work.  Can anaybody provide me x86 lib and dll for the same ?

**Comment by tilakrayal** [comment]
@apratimankit,
Could you please provide the steps which you followed to install the tensorflow lite and also the environment details which helps to debug the issue in an effective way. Thank you!

**Comment by apratimankit** [comment]
I have followed the same steps to build x86 application. Though it got build it was unable to resolve the issue.  I  followed this [](url)
https://github.com/tensorflow/tensorflow/issues/47166 for building tflite in x86. I took the pull from the master branch

**Comment by gaikwadrahul8** [comment]
Hi, @apratimankit 
I apologize for the delayed response, To confirm have you followed [Build LiteRT with CMake](https://ai.google.dev/edge/litert/build/cmake#build_tensorflow_lite_c_library) official documentation? If not please give it try and let us know is it working as expected or not for Windows x86 system?

Please try with below two commands :

```
cmake -A Win32 -DCMAKE_BUILD_TYPE=Release -S ..\tensorflow\lite\c -B .
cmake --build . --config Release
```

If you face any issues please let us know with error log to investigate this issue further. 

Thank you for your cooperation and patience.

**Comment by apratimankit** [comment]
nothing was build  and it got stopped here
error_reporter.cc
model_builder_base.cc
metadata_util.cc
mmap_allocation_disabled.cc
schema_utils.cc
string_utils.cc
Generating Code...

**Comment by apratimankit** [comment]
if possible could you share me the lib and dll file ?

**Comment by gaikwadrahul8** [comment]
Hi, @apratimankit 
Thank you for trying, As far I know bazel does not support build for x86(32 bits) windows so cmake may work and I see similar issue https://github.com/tensorflow/tensorflow/issues/60253 where user was able to build successfully for x86 windows please refer this comment https://github.com/tensorflow/tensorflow/issues/60253#issuecomment-1541833465 so I'm not sure whether user build from this mentioned commit https://github.com/tensorflow/tensorflow/commit/bf157579cf016bcd00e4d01956a0807a2ff6f608 so could you please give it try from specified commit and see is it working as expected or not ?

Unfortunately, as far I know we do not have official build for x86(32 bits) windows even I checked unofficial and community build for x86(32 bits) windows so you'll have to build it from source using cmake 

Thank you for your cooperation and patience.
