### ISSUE TITLE
No OpKernel was registered to support Op 'DecodeJpeg' with these attrs on ios

### ISSUE THREAD

**Issue by wanjianwei** [tensorflow/tensorflow#8192]
hey,everyone!
At first,i can run the demo in /ios_examples/camera successfully.then I use retrain.py to retrain with my own dataset,and get a output_graph.pb flie and a output_labels.txt file.after that, I replace the files in  /ios_examples/camera/data with them,and run the demo again,but it failed ,error description  are as follow:
####error#########
:Could not create TensorFlow Graph: Invalid argument: No OpKernel was registered to support Op 'DecodeJpeg' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false](DecodeJpeg/contents)]];

:Couldn't load model: Invalid argument: No OpKernel was registered to support Op 'DecodeJpeg' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false](DecodeJpeg/contents)]]

Can someone tell me how to fix it?

**Comment by prb12** [comment]
Closing as dupluicate of #2883  (@petewarden - I'm assuming that workaround is still necessary?)
