### ISSUE TITLE
malfunction of tf.device() on Windows

### ISSUE THREAD

**Issue by YOUNGING** [tensorflow/tensorflow#8193]
tf.device('/gpu:0') fail to run the model on only gpu0, other gpus will be occupied as well. As a result, all the memory of all gpu cards on my server are filled. By setting 'config.gpu_options.visible_device_list = "0"', the model will run on gpu0 only.

BTW, only the memory of other gpus are filled, no actual computation is performed on them, all the computation is performed on gpu0.

Anyone who can tell me what's going on is sincerely appreciated.

### Environment info
Operating System: Windows Server 2012 R2
CUDA: 8.0
NO cuDNN

1. A link to the pip package you installed:
using 'pip install tensorflow-gpu' to install
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
1.0.1

### What other attempted solutions have you tried?
config = tf.ConfigProto()
config.gpu_options.visible_device_list = '0'

using 'config' to open a session, the graph will only run on '/gpu:0';

**Comment by prb12** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
