### ISSUE TITLE
import tensorflow Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by bluezone2015** [tensorflow/tensorflow#8197]
(gdb) bt
#0  0x00007f8ef604478b in init_one_static_tls (map=0x0) at allocatestack.c:1171
#1  __pthread_init_static_tls (map=0x0) at allocatestack.c:1196
#2  0x00007f8ef667e6eb in _dl_close_worker () from /lib64/ld-linux-x86-64.so.2
#3  0x00007f8ef667c613 in _dl_open () from /lib64/ld-linux-x86-64.so.2
#4  0x00007f8ef5e3af66 in dlopen_doit (a=0x7ffc4dda53f0) at dlopen.c:67
#5  0x00007f8ef6678266 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#6  0x00007f8ef5e3b2dc in _dlerror_run (operate=0x7f8ef5e3af00 <dlopen_doit>, args=0x7ffc4dda53f0) at dlerror.c:164
#7  0x00007f8ef5e3aee1 in __dlopen (file=<value optimized out>, mode=<value optimized out>) at dlopen.c:88
#8  0x00007f8ef63918ce in _PyImport_GetDynLoadFunc (fqname=<value optimized out>, shortname=<value optimized out>, pathname=0x7f8edc36fa54 "/usr/local/python2.7/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so", 
    fp=0x1d80f90) at Python/dynload_shlib.c:130
#9  0x00007f8ef6376128 in _PyImport_LoadDynamicModule (name=0x7f8edc36524c "_pywrap_tensorflow", pathname=0x7f8edc36fa54 "/usr/local/python2.7/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so", fp=0x1d80f90)
    at ./Python/importdl.c:42
#10 0x00007f8ef6375ca0 in imp_load_module (self=<value optimized out>, args=<value optimized out>) at Python/import.c:3207
#11 0x00007f8ef635d969 in call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4352
#12 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2989
#13 0x00007f8ef635eadf in fast_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4437
#14 call_function (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:4372
#15 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2989
#16 0x00007f8ef635f3ce in PyEval_EvalCodeEx (co=0x7f8edc36f830, globals=<value optimized out>, locals=<value optimized out>, args=<value optimized out>, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0)
    at Python/ceval.c:3584
#17 0x00007f8ef635f4e2 in PyEval_EvalCode (co=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>) at Python/ceval.c:669
#18 0x00007f8ef6371292 in PyImport_ExecCodeModuleEx (name=0x1d7a990 "tensorflow.python.pywrap_tensorflow", co=0x7f8edc36f830, pathname=0x1d7c9b0 "/usr/local/python2.7/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.pyc")
    at Python/import.c:731
#19 0x00007f8ef63739de in load_source_module (name=0x1d7a990 "tensorflow.python.pywrap_tensorflow", pathname=0x1d7c9b0 "/usr/local/python2.7/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.pyc", fp=<value optimized out>)
    at Python/import.c:1121
#20 0x00007f8ef6374791 in import_submodule (mod=0x7f8ef4cd09b8, subname=0x7f8edc3651dc "pywrap_tensorflow", fullname=0x1d7a990 "tensorflow.python.pywrap_tensorflow") at Python/import.c:2725
#21 0x00007f8ef6374ccc in ensure_fromlist (mod=0x7f8ef4cd09b8, fromlist=0x7f8ef38c6fd0, buf=0x1d7a990 "tensorflow.python.pywrap_tensorflow", buflen=17, recursive=0) at Python/import.c:2631
#22 0x00007f8ef63751b4 in import_module_level (name=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>, fromlist=0x7f8ef38c6fd0, level=<value optimized out>) at Python/import.c:2293
#23 PyImport_ImportModuleLevel (name=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>, fromlist=0x7f8ef38c6fd0, level=<value optimized out>) at Python/import.c:2312
#24 0x00007f8ef6354a4f in builtin___import__ (self=<value optimized out>, args=<value optimized out>, kwds=<value optimized out>) at Python/bltinmodule.c:49
#25 0x00007f8ef62aac13 in PyObject_Call (func=0x7f8ef6767fc8, arg=<value optimized out>, kw=<value optimized out>) at Objects/abstract.c:2547
#26 0x00007f8ef6354f33 in PyEval_CallObjectWithKeywords (func=0x7f8ef6767fc8, arg=0x7f8edc33ef50, kw=<value optimized out>) at Python/ceval.c:4221
#27 0x00007f8ef6359bc6 in PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2624
#28 0x00007f8ef635f3ce in PyEval_EvalCodeEx (co=0x7f8edc3545b0, globals=<value optimized out>, locals=<value optimized out>, args=<value optimized out>, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0)
    at Python/ceval.c:3584
#29 0x00007f8ef635f4e2 in PyEval_EvalCode (co=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>) at Python/ceval.c:669
#30 0x00007f8ef6371292 in PyImport_ExecCodeModuleEx (name=0x1d918e0 "tensorflow.python.framework.versions", co=0x7f8edc3545b0, 
    pathname=0x1a4c2b0 "/usr/local/python2.7/lib/python2.7/site-packages/tensorflow/python/framework/versions.pyc") at Python/import.c:731
#31 0x00007f8ef63739de in load_source_module (name=0x1d918e0 "tensorflow.python.framework.versions", pathname=0x1a4c2b0 "/usr/local/python2.7/lib/python2.7/site-packages/tensorflow/python/framework/versions.pyc", 
    fp=<value optimized out>) at Python/import.c:1121
#32 0x00007f8ef6374791 in import_submodule (mod=0x7f8ef39046e0, subname=0x7f8ef39a1744 "versions", fullname=0x1d918e0 "tensorflow.python.framework.versions") at Python/import.c:2725
#33 0x00007f8ef6374ccc in ensure_fromlist (mod=0x7f8ef39046e0, fromlist=0x7f8ef390e710, buf=0x1d918e0 "tensorflow.python.framework.versions", buflen=27, recursive=0) at Python/import.c:2631
#34 0x00007f8ef63751b4 in import_module_level (name=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>, fromlist=0x7f8ef390e710, level=<value optimized out>) at Python/import.c:2293
#35 PyImport_ImportModuleLevel (name=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>, fromlist=0x7f8ef390e710, level=<value optimized out>) at Python/import.c:2312
#36 0x00007f8ef6354a4f in builtin___import__ (self=<value optimized out>, args=<value optimized out>, kwds=<value optimized out>) at Python/bltinmodule.c:49
#37 0x00007f8ef62aac13 in PyObject_Call (func=0x7f8ef6767fc8, arg=<value optimized out>, kw=<value optimized out>) at Objects/abstract.c:2547
#38 0x00007f8ef6354f33 in PyEval_CallObjectWithKeywords (func=0x7f8ef6767fc8, arg=0x7f8ef3922a70, kw=<value optimized out>) at Python/ceval.c:4221
#39 0x00007f8ef6359bc6 in PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2624
#40 0x00007f8ef635f3ce in PyEval_EvalCodeEx (co=0x7f8ef392e2b0, globals=<value optimized out>, locals=<value optimized out>, args=<value optimized out>, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0)
    at Python/ceval.c:3584
#41 0x00007f8ef635f4e2 in PyEval_EvalCode (co=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>) at Python/ceval.c:669
#42 0x00007f8ef6371292 in PyImport_ExecCodeModuleEx (name=0x1a49280 "tensorflow.python.framework.ops", co=0x7f8ef392e2b0, pathname=0x1a4b2a0 "/usr/local/python2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.pyc")
    at Python/import.c:731
#43 0x00007f8ef63739de in load_source_module (name=0x1a49280 "tensorflow.python.framework.ops", pathname=0x1a4b2a0 "/usr/local/python2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.pyc", fp=<value optimized out>)
    at Python/import.c:1121
#44 0x00007f8ef6374791 in import_submodule (mod=0x7f8ef39046e0, subname=0x1a4929c "ops", fullname=0x1a49280 "tensorflow.python.framework.ops") at Python/import.c:2725
#45 0x00007f8ef6374a04 in load_next (mod=0x7f8ef39046e0, altmod=0x7f8ef39046e0, p_name=<value optimized out>, buf=0x1a49280 "tensorflow.python.framework.ops", p_buflen=0x7ffc4dda68e0) at Python/import.c:2539
#46 0x00007f8ef6375098 in import_module_level (name=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>, fromlist=0x7f8ef3969c50, level=<value optimized out>) at Python/import.c:2256
#47 PyImport_ImportModuleLevel (name=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>, fromlist=0x7f8ef3969c50, level=<value optimized out>) at Python/import.c:2312
#48 0x00007f8ef6354a4f in builtin___import__ (self=<value optimized out>, args=<value optimized out>, kwds=<value optimized out>) at Python/bltinmodule.c:49
#49 0x00007f8ef62aac13 in PyObject_Call (func=0x7f8ef6767fc8, arg=<value optimized out>, kw=<value optimized out>) at Objects/abstract.c:2547
#50 0x00007f8ef6354f33 in PyEval_CallObjectWithKeywords (func=0x7f8ef6767fc8, arg=0x7f8ef39666b0, kw=<value optimized out>) at Python/ceval.c:4221
#51 0x00007f8ef6359bc6 in PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2624
#52 0x00007f8ef635f3ce in PyEval_EvalCodeEx (co=0x7f8ef39e55b0, globals=<value optimized out>, locals=<value optimized out>, args=<value optimized out>, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0)
    at Python/ceval.c:3584
#53 0x00007f8ef635f4e2 in PyEval_EvalCode (co=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>) at Python/ceval.c:669
---Type <return> to continue, or q <return> to quit---
#54 0x00007f8ef6371292 in PyImport_ExecCodeModuleEx (name=0x1897ce0 "tensorflow.python.framework.framework_lib", co=0x7f8ef39e55b0, 
    pathname=0x1a48270 "/usr/local/python2.7/lib/python2.7/site-packages/tensorflow/python/framework/framework_lib.pyc") at Python/import.c:731
#55 0x00007f8ef63739de in load_source_module (name=0x1897ce0 "tensorflow.python.framework.framework_lib", pathname=0x1a48270 "/usr/local/python2.7/lib/python2.7/site-packages/tensorflow/python/framework/framework_lib.pyc", 
    fp=<value optimized out>) at Python/import.c:1121
#56 0x00007f8ef6374791 in import_submodule (mod=0x7f8ef39046e0, subname=0x1897cfc "framework_lib", fullname=0x1897ce0 "tensorflow.python.framework.framework_lib") at Python/import.c:2725
#57 0x00007f8ef6374a04 in load_next (mod=0x7f8ef39046e0, altmod=0x7f8ef39046e0, p_name=<value optimized out>, buf=0x1897ce0 "tensorflow.python.framework.framework_lib", p_buflen=0x7ffc4dda6e80) at Python/import.c:2539
#58 0x00007f8ef6375098 in import_module_level (name=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>, fromlist=0x7f8ef4ccb790, level=<value optimized out>) at Python/import.c:2256
#59 PyImport_ImportModuleLevel (name=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>, fromlist=0x7f8ef4ccb790, level=<value optimized out>) at Python/import.c:2312
#60 0x00007f8ef6354a4f in builtin___import__ (self=<value optimized out>, args=<value optimized out>, kwds=<value optimized out>) at Python/bltinmodule.c:49
#61 0x00007f8ef62aac13 in PyObject_Call (func=0x7f8ef6767fc8, arg=<value optimized out>, kw=<value optimized out>) at Objects/abstract.c:2547
#62 0x00007f8ef6354f33 in PyEval_CallObjectWithKeywords (func=0x7f8ef6767fc8, arg=0x7f8ef4f09310, kw=<value optimized out>) at Python/ceval.c:4221
#63 0x00007f8ef6359bc6 in PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2624
#64 0x00007f8ef635f3ce in PyEval_EvalCodeEx (co=0x7f8ef4cbcc30, globals=<value optimized out>, locals=<value optimized out>, args=<value optimized out>, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0)
    at Python/ceval.c:3584
#65 0x00007f8ef635f4e2 in PyEval_EvalCode (co=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>) at Python/ceval.c:669
#66 0x00007f8ef6371292 in PyImport_ExecCodeModuleEx (name=0x1860290 "tensorflow.python", co=0x7f8ef4cbcc30, pathname=0x1896cd0 "/usr/local/python2.7/lib/python2.7/site-packages/tensorflow/python/__init__.pyc") at Python/import.c:731
#67 0x00007f8ef63739de in load_source_module (name=0x1860290 "tensorflow.python", pathname=0x1896cd0 "/usr/local/python2.7/lib/python2.7/site-packages/tensorflow/python/__init__.pyc", fp=<value optimized out>) at Python/import.c:1121
#68 0x00007f8ef637423a in load_package (name=0x1860290 "tensorflow.python", pathname=<value optimized out>) at Python/import.c:1188
#69 0x00007f8ef6374791 in import_submodule (mod=0x7f8ef4cd0600, subname=0x186029b "python", fullname=0x1860290 "tensorflow.python") at Python/import.c:2725
#70 0x00007f8ef6374a04 in load_next (mod=0x7f8ef4cd0600, altmod=0x7f8ef4cd0600, p_name=<value optimized out>, buf=0x1860290 "tensorflow.python", p_buflen=0x7ffc4dda7470) at Python/import.c:2539
#71 0x00007f8ef6375098 in import_module_level (name=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>, fromlist=0x7f8ef4ca4e50, level=<value optimized out>) at Python/import.c:2256
#72 PyImport_ImportModuleLevel (name=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>, fromlist=0x7f8ef4ca4e50, level=<value optimized out>) at Python/import.c:2312
#73 0x00007f8ef6354a4f in builtin___import__ (self=<value optimized out>, args=<value optimized out>, kwds=<value optimized out>) at Python/bltinmodule.c:49
#74 0x00007f8ef62aac13 in PyObject_Call (func=0x7f8ef6767fc8, arg=<value optimized out>, kw=<value optimized out>) at Objects/abstract.c:2547
#75 0x00007f8ef6354f33 in PyEval_CallObjectWithKeywords (func=0x7f8ef6767fc8, arg=0x7f8ef4ca8230, kw=<value optimized out>) at Python/ceval.c:4221
#76 0x00007f8ef6359bc6 in PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2624
#77 0x00007f8ef635f3ce in PyEval_EvalCodeEx (co=0x7f8ef4f19cb0, globals=<value optimized out>, locals=<value optimized out>, args=<value optimized out>, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0)
    at Python/ceval.c:3584
#78 0x00007f8ef635f4e2 in PyEval_EvalCode (co=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>) at Python/ceval.c:669
#79 0x00007f8ef6371292 in PyImport_ExecCodeModuleEx (name=0x188c4c0 "tensorflow", co=0x7f8ef4f19cb0, pathname=0x185f280 "/usr/local/python2.7/lib/python2.7/site-packages/tensorflow/__init__.pyc") at Python/import.c:731
#80 0x00007f8ef63739de in load_source_module (name=0x188c4c0 "tensorflow", pathname=0x185f280 "/usr/local/python2.7/lib/python2.7/site-packages/tensorflow/__init__.pyc", fp=<value optimized out>) at Python/import.c:1121
#81 0x00007f8ef637423a in load_package (name=0x188c4c0 "tensorflow", pathname=<value optimized out>) at Python/import.c:1188
#82 0x00007f8ef6374791 in import_submodule (mod=0x7f8ef661e730, subname=0x188c4c0 "tensorflow", fullname=0x188c4c0 "tensorflow") at Python/import.c:2725
#83 0x00007f8ef6374a04 in load_next (mod=0x7f8ef661e730, altmod=0x7f8ef661e730, p_name=<value optimized out>, buf=0x188c4c0 "tensorflow", p_buflen=0x7ffc4dda7a60) at Python/import.c:2539
#84 0x00007f8ef6375044 in import_module_level (name=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>, fromlist=0x7f8ef661e730, level=<value optimized out>) at Python/import.c:2247
#85 PyImport_ImportModuleLevel (name=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>, fromlist=0x7f8ef661e730, level=<value optimized out>) at Python/import.c:2312
#86 0x00007f8ef6354a4f in builtin___import__ (self=<value optimized out>, args=<value optimized out>, kwds=<value optimized out>) at Python/bltinmodule.c:49
#87 0x00007f8ef62aac13 in PyObject_Call (func=0x7f8ef6767fc8, arg=<value optimized out>, kw=<value optimized out>) at Objects/abstract.c:2547
#88 0x00007f8ef6354f33 in PyEval_CallObjectWithKeywords (func=0x7f8ef6767fc8, arg=0x7f8ef4f092b8, kw=<value optimized out>) at Python/ceval.c:4221
#89 0x00007f8ef6359bc6 in PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>) at Python/ceval.c:2624
#90 0x00007f8ef635f3ce in PyEval_EvalCodeEx (co=0x7f8ef4f08db0, globals=<value optimized out>, locals=<value optimized out>, args=<value optimized out>, argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, closure=0x0)
    at Python/ceval.c:3584
#91 0x00007f8ef635f4e2 in PyEval_EvalCode (co=<value optimized out>, globals=<value optimized out>, locals=<value optimized out>) at Python/ceval.c:669
#92 0x00007f8ef637f785 in run_mod (fp=<value optimized out>, filename=0x7f8ef63d206f "<stdin>", flags=0x7ffc4dda7f80) at Python/pythonrun.c:1376
#93 PyRun_InteractiveOneFlags (fp=<value optimized out>, filename=0x7f8ef63d206f "<stdin>", flags=0x7ffc4dda7f80) at Python/pythonrun.c:857
#94 0x00007f8ef637f99e in PyRun_InteractiveLoopFlags (fp=0x7f8ef52de6c0, filename=0x7f8ef63d206f "<stdin>", flags=0x7ffc4dda7f80) at Python/pythonrun.c:777
#95 0x00007f8ef63800dc in PyRun_AnyFileExFlags (fp=0x7f8ef52de6c0, filename=0x7f8ef63d206f "<stdin>", closeit=0, flags=0x7ffc4dda7f80) at Python/pythonrun.c:746
#96 0x00007f8ef6395694 in Py_Main (argc=<value optimized out>, argv=<value optimized out>) at Modules/main.c:640
#97 0x00007f8ef4f770bd in __libc_start_main (main=0x400730 <main>, argc=1, ubp_av=0x7ffc4dda80a8, init=<value optimized out>, fini=<value optimized out>, rtld_fini=<value optimized out>, stack_end=0x7ffc4dda8098) at libc-start.c:226
#98 0x0000000000400669 in _start ()

------------------------------------------------------------------------
**I installed glibc 2.14 in another env and set LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/python2.7/lib:/opt/glibc-2.14/lib:$LD_LIBRARY_PATH
but when import tensorflow then core dumped, 
I need for help, thanks a lot**

**Comment by prb12** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by bluezone2015** [comment]
OS：CentOS Linux release 6.2 (Final)  x86_64 x86_64 x86_64 GNU/Linux
TensorFlow version：https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp27-none-linux_x86_64.whl

**Comment by bluezone2015** [comment]
I've solved the problem by update glic to GLIBC_2.14, gcc to gcc-4.8.1, thanks
