### ISSUE TITLE
I am usage chrome access 

### ISSUE THREAD

**Issue by muzammilamreen** [tensorflow/tensorflow#81980]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 3.8

### Custom code

Yes

### OS platform and distribution

15.03

### Mobile device

15.03

### Python version

9.9

### Bazel version

https://github.com/github/docs.git

### GCC/compiler version

I am usage accessories 

### CUDA/cuDNN version

I am usage chrome access 

### GPU model and memory

Welcome 

### Current behavior?

Behavior is very nice alhamdulillah 
Not a complain I understand 

### Standalone code to reproduce the issue

```shell
Sir hum accessories use krte Hain ko Nikki hoti Hain bilkul bhi kisi ko dara dene ya black mail k liye use nh hota
```

### Relevant log output

```shell
Sir hum accessories use krte Hain ko Nikki hoti Hain bilkul bhi kisi ko dara dene ya black mail k liye use nh hota
```

**Comment by tilakrayal** [comment]
@muzammilamreen,
Could you please provide the steps you have followed and also take a look at the official document for the installation of the Tensorflow in the smoother way.

https://www.tensorflow.org/install/pip#step-by-step_instructions

Thank you!

**Comment by mihaimaruseac** [comment]
Please don't spam
