### ISSUE TITLE
Tensorboard scalar summary graph distorts after resizing and toggling log scale on y-axis 

### ISSUE THREAD

**Issue by insectatorious** [tensorflow/tensorflow#8199]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

None although a search for distorted image tensorboard doesn't help much...

### Environment info
Operating System: 16.04 LTS
Firefox: 51.0.1 (64-bit)
TF: 1.0 (installed via pip)

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
$> sudo ls -l /usr/local/cudnn/*
/usr/local/cudnn/include:
total 100
-r--r--r-- 1 root root 99658 Feb 20 11:27 cudnn.h

/usr/local/cudnn/lib64:
total 150908
lrwxrwxrwx 1 root root       13 Feb 20 11:27 libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root       35 Feb 16 17:01 libcudnn.so.4 -> /usr/local/cuda/lib64/libcudnn.so.4
lrwxrwxrwx 1 root root       39 Feb 16 17:01 libcudnn.so.4.0.7 -> /usr/local/cuda/lib64/libcudnn.so.4.0.7
lrwxrwxrwx 1 root root       18 Feb 20 11:27 libcudnn.so.5 -> libcudnn.so.5.1.10
-rwxr-xr-x 1 root root 84163560 Feb 20 11:27 libcudnn.so.5.1.10
```

If installed from binary pip package, provide:

1. A link to the pip package you installed:
Standard TF pip url.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
```
$> python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
1.0.0
```

### Steps to reproduce (Firefox only)
1. On the 'Scalars' tab for tensorboard, view the graph of a scalar summary (eg _cost_ or _accuracy_) by **expanding the tab**. ![tensorboard - mozilla firefox_027](https://cloud.githubusercontent.com/assets/252960/23708510/0bcd8b5a-040e-11e7-8a19-e2eb7ee208af.png)
2. **Click on the expand icon** ![tensorboard - mozilla firefox_028](https://cloud.githubusercontent.com/assets/252960/23708524/1227e784-040e-11e7-9c5c-e8f466df5581.png)
3. **Enable** log scale of y-axis ![tensorboard - mozilla firefox_029](https://cloud.githubusercontent.com/assets/252960/23708530/162e403a-040e-11e7-8628-fbd04ae05642.png)
4. **Disable** log scale of y-axis (note the bug happens regardless of whether you do this) ![tensorboard - mozilla firefox_028](https://cloud.githubusercontent.com/assets/252960/23708524/1227e784-040e-11e7-9c5c-e8f466df5581.png)
5. **Click on expand icon** to shrink the graph.

The graph is now overflowing: ![tensorboard - mozilla firefox_030](https://cloud.githubusercontent.com/assets/252960/23708531/18f031a2-040e-11e7-9e22-8c76415ddb14.png)

### What other attempted solutions have you tried?
Tried to reproduce in Chromium 55.0.2883.87 but unable to.

**Comment by dandelionmane** [comment]
Migrated this to the TensorBoard repo.
