### ISSUE TITLE
build_config.bzl file modified by configure

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#8202]
`configure` modifies `build_config.bzl` to set the `WITH_JEMALLOC` flag.  This is inconvenient when using git, since it means I can't pull after doing configure without manually clearing the file.

Can the setup be modified so that `configure` makes a file not under git control?

**Comment by jart** [comment]
We received a pull request adding the -e file to gitignore in https://github.com/tensorflow/tensorflow/pull/7978, but I'd like to understand more why it's there in the first place, so I'll take a look now.

**Comment by jart** [comment]
As for build_config.bzl being modified, I have an idea which I think might work. Let me see if I can code that up quickly.

**Comment by yaroslavvb** [comment]
PS, the workaround  to avoid overwriting ./configure results on each rebase/pull:

```
git stash
git rebase origin/master
git stash pop
git checkout --theirs -- tensorflow/core/platform/default/build_config.bzl
```
