### ISSUE TITLE
How to create Python extension module that uses TensorFlow C API?

### ISSUE THREAD

**Issue by grabonly** [tensorflow/tensorflow#82064]

**Comment by Venkat6871** [comment]
Hi **@grabonly** ,
Thanks for raising your concern here. There are few steps you need to follow for creating python extension. Download and extract the TensorFlow C API library from [TensorFlow releases](https://github.com/tensorflow/tensorflow/releases). Create a file `my_tf_module.cpp`. Set up a `setup.py` script for building the extension. Run: python setup.py build to generate .so (or .pyd on Windows). Finally text with the following commands:
```
import my_tf_module
print("TF Version:", my_tf_module.get_tf_version())
```
Thank you!
