### ISSUE TITLE
Operation Documentation has " within it

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [tensorflow/tensorflow#8207]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/array_ops.cc#L1154

This wasn't causing a problem because TF was stripping out the documentation before hitting Python and the Python Protobuf text_format.py https://github.com/google/protobuf/issues/2798. I wanted to expose the documentation in the Python (A patch I am NOT recommending!!) per http://stackoverflow.com/questions/42521166/tensorflow-operation-documentation, but ran into numerous issues in the Protobuf seen in the above issue posted to Protobuf. The last problem I had stemmed from TF's misuse of " within the documentation

I did a batch replacement with a small script,
```
import os, re

for fname in os.listdir('./'):
    if fname[-3:] != ".cc":
        print "Skipping", fname
        continue

    with open(fname) as f:
        code = f.read()

    quotes = 0
    blocks = re.findall('\"[Dd]oc\((?:(?!REG).|\n)*\)[Dd]oc\"', code)
    for sub in blocks:
        if sub.count('"') <= 2:
            continue

        s = sub.find('"')
        e = sub.rfind('"')
        new_sub = sub[:s+1] + sub[s+1:e].replace('"', "'") + sub[e:]
        quotes += sub.count('"') - new_sub.count('"')
        code = code.replace(sub, new_sub)

    print "Replacing", quotes, "in", fname
    f = open(fname, 'w')
    f.write(code)
    f.close()
```

I can submit a pull request if you like, but running that script in `tensorflow/tensorflow/core/ops` achieves the same thing.

**Comment by aidan-plenert-macdonald** [comment]
I put this into a Dockerfile and it built,

```
FROM tensorflow/tensorflow:nightly-devel
# Remove misused quotes in documentation in Python Protobuf
# https://github.com/tensorflow/tensorflow/issues/8207
COPY dequote.py /tensorflow/tensorflow/core/ops/
RUN cd /tensorflow/tensorflow/core/ops/ && \
    python dequote.py &&\
    rm dequote.py
```

`dequote.py` is the code above

**Comment by dr4b** [comment]
If you want to fix it and send a pull request that would be fantastic!

**Comment by av8ramit** [comment]
Please open a PR with commits from authors who have signed the CLA:
https://github.com/tensorflow/tensorflow/pull/8221

Closing for now.
