### ISSUE TITLE
String input producer creates trainable variable.

### ISSUE THREAD

**Issue by dmitryfisko** [tensorflow/tensorflow#821]
Using tf.train.string_input_producer function, creates trainable variable. In addition its tensor of int type. Example:

filename_queue = tf.train.string_input_producer(["test"], num_epochs=1, name='input_producer_test')
assert tf.trainable_variables()[0].dtype.is_integer

It becomes problem, when uses variable_averages.apply(...), which require, that each trainable variable must be float type.

**Comment by yaroslavvb** [comment]
Is it something that was fixed recently? I only see "limit_epochs" as a variable made by string_input_producer, and it's regular, not trainable variable -- https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/input.py#L76

**Comment by dmitryfisko** [comment]
Sorry. Yes it is.
