### ISSUE TITLE
No such file or directory: 'patchelf' while building tensorflow from source

### ISSUE THREAD

**Issue by GoutamAgrawal** [tensorflow/tensorflow#82195]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.18

### Custom code

No

### OS platform and distribution

CentOS 8

### Python version

3.10

### Bazel version

6.5.0

### GCC/compiler version

gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22)

### CUDA/cuDNN version

CUDA 12.5/ CUDNN 9.3

### GPU model and memory

Tesla V100 SXM2 16GB

### Current behavior?

I am getting issue while building tensorflow with this command. 

```
 bazel --output_base=/goutam/bazel_cache build    --repo_env=WHEEL_NAME=tensorflow     --config=cuda     --repo_env=HERMETIC_CUDA_COMPUTE_CAPABILITIES=sm_70     --config=cuda_wheel   --verbose_failures     //tensorflow/tools/pip_package:wheel 
```

i am getting same error after installing pathelf.

``` 
(pythontemp) [goutam@Goutam]$ which patchelf
/Goutam/patchelf/bin/patchelf
(pythontemp) [goutam@Goutam]$ patchelf --version
patchelf 0.17.0
(pythontemp) [goutam@Goutam]$ 
```

### Standalone code to reproduce the issue

```shell
FileNotFoundError: [Errno 2] No such file or directory: 'patchelf'
```

### Relevant log output

```shell
: [Errno 2] No such file or directory: 'patchelf'
Constructed file path: /tmp/tensorflow_wheel5el2uqr_/tensorflow/python/_pywrap_tensorflow_internal.so
Target //tensorflow/tools/pip_package:wheel failed to build
INFO: Elapsed time: 3813.683s, Critical Path: 408.33s
INFO: 32825 processes: 5868 internal, 26957 local.
FAILED: Build did NOT complete successfully
(pythontemp) [goutam@ssl-gpu tensorflow]$ ls /tmp/tensorflow_wheel5el2uqr_/tensorflow/python/_pywrap_tensorflow_internal.so
ls: cannot access '/tmp/tensorflow_wheel5el2uqr_/tensorflow/python/_pywrap_tensorflow_internal.so': No such file or directory
(pythontemp) [goutam@ssl-gpu tensorflow]$ ls /tmp/tensorflow_wheel5el2uqr_/tensorflow/python/
ls: cannot access '/tmp/tensorflow_wheel5el2uqr_/tensorflow/python/': No such file or directory
(pythontemp) [goutam@ssl-gpu tensorflow]$ ls /tmp/tensorflow_wheel5el2uqr_/tensorflow/
ls: cannot access '/tmp/tensorflow_wheel5el2uqr_/tensorflow/': No such file or directory
(pythontemp) [goutam@ssl-gpu tensorflow]$ ls /tmp/tensorflow_wheel5el2uqr_/
ls: cannot access '/tmp/tensorflow_wheel5el2uqr_/': No such file or directory
```

**Comment by Venkat6871** [comment]
Hi **@GoutamAgrawal** ,
Apologies for the delay, and thank you for raising your concern. The issue occurs because the directory containing patchelf is not included in the PATH environment variable used by Bazel.Please add patchelf to your PATH. If it still does not work, try specifying the path to patchelf explicitly.
And please execute the following installation command and check if it resolves the issue in your case?
```
sudo apt install -y patchelf
```
Thank you!

**Comment by GoutamAgrawal** [comment]
Hi. I have already installed patchelf and verified it's installation, also exported the path. Furthermore, I have tried specifying the path to patchelf explicitly in my configuration. Despite these efforts, I am still facing the same issue. Could you please advise on any other steps to resolve this?

**Comment by Venkat6871** [comment]
Hi **@GoutamAgrawal** ,
Apologies for the delay. Could you please check with versions 3.10 and 3.11? Kindly let us know if the issue still persists.
Thank you!

**Comment by GoutamAgrawal** [comment]
Thank you. You meant patchelf version 0.10 and 0.11?
