### ISSUE TITLE
[feature] Define Op Polymorphic on Fully Defined vs not Fully Defined Shape

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#8225]
Repost from [SO](http://stackoverflow.com/questions/42655141/tensorflow-define-op-polymorphic-on-fully-defined-vs-not-fully-defined-shape/42683994#42683994):

When defining an Op in Tensorflow, make it possible to provide two Kernels for the op that are polymorphic on whether the shape for the inputs are fully defined.

For example, you can then optimize when shape is fully known / defined by constructing certain structures once at Kernel construction.

/CC @mrry

**Comment by itsmeolivia** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
