### ISSUE TITLE
Unable to uninstall tensorflow

### ISSUE THREAD

**Issue by bharathbs93** [tensorflow/tensorflow#8226]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by bharathbs93** [comment]
*sudo pip uninstall does not work,  says Cannot uninstall requirement tensorflow, not installed.
* Installed CUDA version is 8.0, cudnn 5.1
* python -c "import tensorflow; print(tensorflow.__version__)" output is
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
1.0.1

**Comment by bharathbs93** [comment]
got around to solving it, you need to mention the gpu version of tensorflow which is tensorflow-gpu when uninstalling, silly mistake :)

**Comment by JiayongLF** [comment]
Thank you @bharathbs93 your method suits me!
