### ISSUE TITLE
Sorry I got question again。。。

### ISSUE THREAD

**Issue by AnlanSun** [tensorflow/tensorflow#8228]
Can TF use ram as swap space for GPU memory？ Cause  I ran a model with batch size 100 on GPU which will be out of memory on caffe. But on TF it works and just show pool_allocator. As I saw in other issues that's just a log. If it can swap why does it crashes sometimes? Is there any limitation?

**Comment by prb12** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
