### ISSUE TITLE
Feature parity of tf.diag with np.diag

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#824]
np.diag can

1) take 2d array and produce 1d vector of diagonal entries
2) take 1d array and produce diagonal 2d array (inverse of case 1)

tf.diag only supports 2) and the behavior for case 1) is undocumented

Currently to do 1) you need to do something like this:

    def identity_matrix(n):
      """Returns nxn identity matrix."""
      # note, if n is a constant node, this assert node won't be executed,
      # this error will be caught during shape analysis 
      assert_op = tf.Assert(tf.greater(n, 0), ["Matrix size must be positive"])
      with tf.control_dependencies([assert_op]):
        ones = tf.fill(n, 1)
        diag = tf.diag(ones)
      return diag
    
    def extract_diagonal(tensor):
      """Extract diagonal of a square matrix."""
      
      shape = tf.shape(tensor)
      n = shape[0]
      assert_op = tf.Assert(tf.equal(shape[0], shape[1]), ["Can't get diagonal of "
                                                           "a non-square matrix"])
      
      with tf.control_dependencies([assert_op]):
      return tf.reduce_sum(tf.mul(tensor, identity_matrix(n)), [0])

**Comment by josh11b** [comment]
I believe tf.diag is only intended to support 2).  It would be reasonable to create a new op for 1).

**Comment by girving** [comment]
Yeah, having the same op arbitrarily be its own one-sided inverse seems pretty strange.  Two ops sound better to me.

**Comment by yaroslavvb** [comment]
Besides numpy, this also how it's done in Theano, Torch, Matlab, ViennaCL

**Comment by girving** [comment]
In my defense, that's four different things copying Matlab's arguably sketchy choice, but I see your point.  I'm okay if we bow to peer pressure.

**Comment by chemelnucfin** [comment]
@girving This issue may be closed?

**Comment by girving** [comment]
Yep, closing.

**Comment by girving** [comment]
@chemelnucfin: For future use, you can include a line "Fixes #824" in the commit message in order to automatically close the issue when it's merged.
