### ISSUE TITLE
ImportError: No module named tensorflow

### ISSUE THREAD

**Issue by kinDSa** [tensorflow/tensorflow#8240]
Hello,
I am using  [TensorFlow For Poets](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#0) guides for retraining  model. I followed first 3 step successfully. While I run following command at tensorflow root directory.

python tensorflow/examples/image_retraining/retrain.py \
--bottleneck_dir=/tf_files/bottlenecks \
--how_many_training_steps 500 \
--model_dir=/tf_files/inception \
--output_graph=/tf_files/retrained_graph.pb \
--output_labels=/tf_files/retrained_labels.txt \
--image_dir /tf_files/flower_photos

I get error   **File "tensorflow/examples/image_retraining/retrain.py", line 79, in <module>
                  import tensorflow as tf
                  ImportError: No module named tensorflow**

System : Ubantu 14.04 LTS
Python Version 3.4.3

**Comment by annanay25** [comment]
Running from the home directory may cause this issue. It may cause python to search for the package within this directory. (Especially you have compiled from source)

Could you try cd-ing into the "tensorflow/examples/..." folder and try running it from there?

**Comment by prb12** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by yohochen** [comment]
Hey kinDSa, have you figured out where the issue is for this? Thanks.
