### ISSUE TITLE
[feature] Logging Support from Custom Op

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#8241]
Repost from [SO](http://stackoverflow.com/questions/42684403/logging-from-custom-tensorflow-op-issue-with-vlog)

Provide method and documentation for how to log from within a custom op. built in ops using `VLOG` to log, however that does not work for custom ops. I have defined my own op and in it I use `VLOG` however when I try to run the Op I get:
```
NotFoundError: dlopen(/Users/alex/git/tensorflow/bazel-bin/tensorflow/core/user_ops/my_op.so, 6): Symbol not found: __ZN10tensorflow8internal10LogMessage12MinVLogLevelEv
  Referenced from: /Users/alex/git/tensorflow/bazel-bin/tensorflow/core/user_ops/my_op.so
  Expected in: flat namespace
 in /Users/alex/git/tensorflow/bazel-bin/tensorflow/core/user_ops/my_op.so
```
Ideally there would be some suggestion or note in the docs about how to handle logging.

/CC @yaroslavvb

**Comment by yaroslavvb** [comment]
This is a symbol called `_tensorflow::internal::LogMessage::MinVLogLevel()`
Looking at [tf_exported_symbols.lds](https://github.com/tensorflow/tensorflow/blob/754048a0453a04a761e112ae5d99c149eb9910dd/tensorflow/tf_exported_symbols.lds), it's supposed to include everything matching `*tensorflow*`. However, looking at exported symbols, it doesn't seem to be present, any idea why it's filtered out? @keveman @vrv 

```
export so=`python -c "import tensorflow as tf; import os.path; print(os.path.dirname(tf.sysconfig.get_include())+'/python/_pywrap_tensorflow.so')"`
nm -g $so | grep MinVLog

```

**Comment by cancan101** [comment]
Given that it sounds like this should this be reclassified as a bug instead of a feature?

**Comment by keveman** [comment]
@cancan101 is this still an issue for you? I am not super inclined to fix this if it's not going to be heavily used.

**Comment by vrv** [comment]
@keveman we use VLOG and LOG in OpKernels all the time; shouldn't users be able to do the same?

**Comment by keveman** [comment]
@vrv Perhaps. @yaroslavvb, with TF 1.0, that symbol does seem to be present in `pywrap_tensorflow.so`:

    $ export so=`python -c "import tensorflow as tf; import os.path; print(os.path.dirname(tf.sysconfig.get_include())+'/python/_pywrap_tensorflow.so')"`; nm -g $so | grep MinVLog
    00000000023b9e70 T _ZN10tensorflow8internal10LogMessage12MinVLogLevelEv

@cancan101 This problem [seems](http://stackoverflow.com/questions/35006614/what-does-symbol-not-found-expected-in-flat-namespace-actually-mean) to be coming from mixing `libc++` and `libstdc++`. Since you are on OSX, you most probably are compiling your `my_op.so` with `libc++` and `clang`. One option is to try compiling with `-stdlib=libstdc++`.

**Comment by cancan101** [comment]
I no longer have issues on a clean check of on master and building just using `bazel build --config opt //tensorflow/core/user_ops:zero_out.so`.

The log statements are correctly sent to stdout.

**Comment by shipleyxie** [comment]
I can't see any messages in my screen while using LOG(INFO) and  std::cout.
TensorFlow 1.13.2 build with `bazel build --config=opt --config=cuda --jobs 16 --verbose_failures //tensorflow/tools/pip_package:build_pip_package`
Any suggestion?
