### ISSUE TITLE
[Time Consuming] TF C++ Session->Run - Images for Real-time Inference

### ISSUE THREAD

**Issue by HossamAmer12** [tensorflow/tensorflow#8243]
[Tensorflow (TF) on CPU]
I am using the skeleton code provided for C++ TF inference [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/main.cc] in order to run a frozen model I have created in Python. This model is an FC NN with two hidden layers.

In my current project's code, I run the inference for each single image (8x8 pixels). For each sample, each Session->Run call takes about 0.02 seconds, which is expensive in my application. However, when I send a batch of 1560 samples, the Session->Run call takes about 0.03 seconds. 

Are these time measurements normal for the Session->Run Call? From the C++ end, should I send my frozen model batches of images and not single samples?  From the Python end, is there optimisation tricks to alleviate that bottleneck? Is there a way to concurrently do Session-Run calls in C++?

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/tensorflow/tensorflow/issues/1439
http://stackoverflow.com/questions/39070708/why-sometimes-tensorflow-runs-slower-and-slower-with-the-process-of-training

### Environment info
Operating System: Linux
Installed version of CUDA and cuDNN: N/A

### What other attempted solutions have you tried?
1. I installed TF using the optimised instruction set for the CPU, but it does not seem to give me the huge time saving mentioned here [http://stackoverflow.com/questions/41293077/how-to-compile-tensorflow-with-sse4-2-and-avx-instructions]
2. Unified the session for the Graph I created.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by prb12** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by HossamAmer12** [comment]
I just posted my question on StackOverflow:
http://stackoverflow.com/questions/42701532/time-consuming-tensorflow-c-session-run-images-for-real-time-inference

If you have any suggestions, I'd appreciate it if you can write them over there. Thanks!
