### ISSUE TITLE
Issues with getting tensorflow to use SSE4.2 instructions, for faster CPU computations

### ISSUE THREAD

**Issue by ajl412860** [tensorflow/tensorflow#8250]
Using this on a Mac OS, using the anaconda support system. Basically trying to get tensorflow to use SSE4.2 and AVX .

##This is on tensorflow version 1.0.0

##All commands are done in this order.

#1st
Using this command,
`bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2`

I am not using the gpu with cuda,
##so I didnt include the --config==cuda and the -k

#2nd
##Using a test command on a test script.
`python3 Test.py`
Im still getting the same
`W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.`
#3rd
##So being confused, I used a command I found this command via http://stackoverflow.com/questions/41293077/how-to-compile-tensorflow-with-sse4-2-and-avx-instructions to tie up any "lose ends" another way for tensor flow to work on SSE4.2

`bazel build -c opt //tensorflow/tools/pip_package:build_pip_package`

I get this error

`WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.build/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing. ERROR: no such package 'tensorflow/tools/pip_package': BUILD file not found on package path. INFO: Elapsed time: 0.210s`

What am I doing wrong here ? All I am trying to do is get tensorflow to use SSE4.2 and AVX .

**Comment by prb12** [comment]
There is a section in this [page](https://www.tensorflow.org/versions/master/get_started/os_setup
) which suggests that configuration flags need to be supplied at the `./configure` step.  (Search for "Optimizing CPU Performance")

>To be compatible with as wide a range of machines as possible, TensorFlow defaults to only using SSE4 SIMD instructions. Most modern computers support more advanced instructions. So if you're building a binary that you'll only be running on your own machine, you can enable these by using -march=native for optimization options when running configure. Then you can build your optimized binaries with the following command:
$ bazel build --config opt //tensorflow/tools/pip_package:build_pip_package

Looking at the configure script, it seems to examine the environment variable `CC_OPT_FLAGS` and add flags to the `tools/bazel.rc` file.   Perhaps worth giving this a go?

I don't know off the top of my head why flags passed on the bazel command line aren't being respected. @gunan Any ideas?

**Comment by gunan** [comment]
The warnings about sse4.2 or AVX are completely benign, and can be ignored. It just means that TensorFlow can run faster on your machine if you build from sources. But everything will run OK on your machine, you can safely ignore these warnings.

From what I can see, You did not actually clone the code, but you tried to build our sources.
Especially the first bazel command you have above does not do anything at all (no build target specified).
Unless you clone our github repo, run configure, build the code, then build the pip package and install the resulting pip package, bazel commands themselves will not have any effect. For that, you need to follow  our the instructions here:
https://www.tensorflow.org/install/install_sources

I will close this issue, as the user clearly did not follow the instructions to build from sources.
Please create a new issue if you run into issues with the instructions to install from sources.
