### ISSUE TITLE
pip3 install --upgrade tensorflow-gpu: No matching distribution found for tensorflow-gpu

### ISSUE THREAD

**Issue by samodadela** [tensorflow/tensorflow#8251]
Following the installation guide at https://www.tensorflow.org/install/install_windows
Installed:
- CUDA (cuda_8.0.61_win10.exe)
- cuDDN (cudnn-8.0-windows10-x64-v5.1.zip)
- Python 3.6 x64 (python-3.6.0-amd64.exe)

Then issued:
C:\>pip3 install --upgrade tensorflow-gpu
Collecting tensorflow-gpu
  Could not find a version that satisfies the requirement tensorflow-gpu (from versions: )
No matching distribution found for tensorflow-gpu

Same happens with non-gpu version:
C:\>pip3 install --upgrade tensorflow
Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow

### Environment info
Operating System: Windows 10 x64

Installed version of CUDA and cuDNN: 
cudnn-8.0-windows10-x64-v5.1.zip 
cuDDN/bin: cudnn64_5.dll

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
Just follow the provided instructions on https://www.tensorflow.org/install/install_windows

### What other attempted solutions have you tried?
First I tried 32-bit python but found on SO that is not supported (install guide should state which python is requrired 32 or 64)

I wanted specify the correct URL for tensorflow-gpu, but I don't know which is the correct one for r1.0 gpu. Like this (example):
pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl

Please provide correct url - on storage.googleapis.com it is not possible to browse the directory contents. I need tensorflow r1.0 x64 gpu!

got the hint from here: http://stackoverflow.com/questions/38896424/tensorflow-not-found-in-pip

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by argcos** [comment]
Tensorflow GPU only works with Python 3.5.x

**Comment by samodadela** [comment]
Indeed! Thanks - the documentation says so but I though anything newer is ok also. 
My bad.

**Comment by samodadela** [comment]
Continuing with the installation, I get this:

C:\>python
Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cublas64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cudnn64_5.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library cufft64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library nvcuda.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:135] successfully opened CUDA library curand64_80.dll locally
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:885] Found device 0 with properties:
name: GeForce 940M
major: 5 minor: 0 memoryClockRate (GHz) 1.176
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.66GiB
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0:   Y
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce 940M, pci bus id: 0000:01:00.0)
>>> print(sess.run(hello))
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
b'Hello, TensorFlow!'
>>>

Should I open another iss

**Comment by samodadela** [comment]
Now I'm stuck with:
https://github.com/tensorflow/tensorflow/issues/8253

:)

**Comment by phpmind** [comment]
Thanks it worked for me.

**Comment by kimgada** [comment]
Good.

**Comment by SpencerOs** [comment]
From what I can tell, my setup is almost the exact same as the problem described in the first post, but with Python 3.5.

- Windows 10 (x64)
- CUDA (cuda_8.0.61_win10_network.exe with the applied cuda_8.0.61.2_windows.exe patch)
- CUDNN (cudnn-8.0-windows10-x64-v6.0.zip unzipped and put into the specified spots)
- Python 3.5 (python-3.5.4.exe)

Just had to wipe the hard drive last night, so this setup is as fresh as fresh can be. (Installed the newest drivers as of yesterday for the GPU.)
Running the suggested install command restults in:
```
C:\Windows\system32>pip3 install --upgrade tensorflow-gpu
Collecting tensorflow-gpu
  Could not find a version that satisfies the requirement tensorflow-gpu (from versions: )
No matching distribution found for tensorflow-gpu
```
Although searching does bring up the specified package.
```
C:\Windows\system32>pip3 search tensorflow-gpu

...

tensorflow-gpu (1.4.0)                       - TensorFlow helps the tensors
                                               flow
```
Am I overly stupid and missed something glaringly obvious, or is there something more subtle going on here?
(Also, running the command to get it to fetch from the wheel gives this result:
```
C:\Windows\system32>pip install --upgrade https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-0.12.1-cp35-cp35m-win_amd64.whl
tensorflow_gpu-0.12.1-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.
```

**Comment by jonejkim** [comment]
@SpencerOs I just ran into the same problem. My problem turned out to be that my python3 installed was 32bit version. From your 'python-3.5.4.exe' seems like you installed the 32 bit version. I suggest you try with the 64bit version. I installed 'python-3.6.3-amd64.exe' and it works.

**Comment by agurusa** [comment]
@jonejkim ran into the same issue, downloading the 64 bit version solved it! You can find it [here](https://www.python.org/downloads/release/python-362/)

**Comment by cayman1021** [comment]
I tried Python 3.6.x and 3.7.x (64-bits). Only Python 3.5.x works for "tensorflow-gpu". FYI.

**Comment by Timoeller** [comment]
python 3.6.x 64 bit **is working** for me with
`pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.4.1-cp36-cp36m-linux_x86_64.whl`

newer packages you might find under: https://www.tensorflow.org/install/install_linux#the_url_of_the_tensorflow_python_package

**Comment by SoulFireMage** [comment]
Is there a windows version that works on python 3.6 onwards? Unable to locate an answer that works this morning that is all.

**Comment by Anchal-Mittal** [comment]
I think you have installed 32 bit version of python. That is why it is not working. Try to install 64-bit version of python and then install tensorflow-gpu.

**Comment by KingRial** [comment]
@Anchal-Mittal you saved my life! :D
It was so obvious  that I didn't see it

**Comment by akkida746** [comment]
Try this:
pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl

**Comment by CorruptedMonkey** [comment]
> Tensorflow GPU only works with Python 3.5.x
How do I change my python to 3.5.x?

**Comment by AllenYLJiang** [comment]
Consider to replace pip3 with pip.

**Comment by CorruptedMonkey** [comment]
Thank you

**Comment by CorruptedMonkey** [comment]
AllenYLJiang still doenst work

**Comment by lowsparkk** [comment]
Just tried this
`pip install --upgrade tensorflow_gpu-1.10.1-cp36-cp36m-linux_x86_64.whl`
and I get
`tensorflow_gpu-1.10.1-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform`
Looks like python 3.7 is not supported yet.

**Comment by adammenges** [comment]
@arcosmin is this still true?

**Comment by CorruptedMonkey** [comment]
It just doesn't work on python 3.7

**Comment by ByteCauldron** [comment]
`pip install tensorflow-gpu` does work for 3.6 but only up to 3.6.4.
I was having some issues with pip on Windows 10 not finding the wheel on 3.6.5 and above. That could be also only related to the gpu version but I'm not sure. Either way, if you are having trouble with 3.6 still, try 3.6.4 specifically.

**Comment by Saisuchith** [comment]
I have python 3.7. How can i change it to python 3.5?

**Comment by arcosmin** [comment]
@Saisuchith - depends how it has been installed. If it's been installed directly then uninstall 3.7 and install 3.5. If you installed it with Anaconda then you can just create a new environment with a different Python version. Google is your friend here.

**Comment by pilhoon** [comment]
If you use Anaconda, use python 3.6. refer [here](http://docs.anaconda.com/anaconda/user-guide/faq/#how-do-i-get-the-latest-anaconda-with-python-3-5).

**Comment by JairIA** [comment]
Thx a lot @pilhoon, it s solve my issue!!!

**Comment by RishiRanjan21** [comment]
**Try this**
python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl

**Comment by ecpost** [comment]
Thanks @RishiRanjan21.  I also had to change it to 1.14 to avoid [this](https://github.com/openai/gpt-2/issues/178#issuecomment-569099076) issue.  Specifically, like this:

pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.14.0-py3-none-any.whl

**Comment by a3diti** [comment]
`pip install tensorflow-gpu==1.14.0` will not work for mac because it does not exists on the pypi directory as listed on the link below
[https://pypi.org/project/tensorflow-gpu/1.14.0/#files](https://pypi.org/project/tensorflow-gpu/1.14.0/#files)

**Comment by mihaimaruseac** [comment]
There is no GPU for mac

**Comment by paulinhoAlmeida** [comment]
> Try this:
> pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl

worked for me
