### ISSUE TITLE
Ordering the runs in TensorBoard's embeddings tab

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [tensorflow/tensorflow#8255]
Feature request: it would be nice if the  runs in TensorBoard's embeddings tab were ordered.

As of now it is unordered, e.g.:

![image](https://cloud.githubusercontent.com/assets/15331/23777190/d3eaabfc-0500-11e7-93f1-657a9d9bd35c.png)

Corresponding Stack Exchange question: [What determine the order of the runs in TensorBoard's embeddings tab?](http://stackoverflow.com/q/42684521/395857)

**Comment by prb12** [comment]
@dandelionmane Looks like an easy one?

**Comment by dandelionmane** [comment]
@dsmilkov for the embedding projector

**Comment by jart** [comment]
This issue has been migrated to https://github.com/tensorflow/tensorboard/issues/78.
