### ISSUE TITLE
Variable for Go?

### ISSUE THREAD

**Issue by notnot** [tensorflow/tensorflow#8256]
Is Variable being worked on in the Go bindings?

**Comment by prb12** [comment]
@asimshankar Could you comment on this pls?

**Comment by notnot** [comment]
Well i don't see a Go equivalent of python's tf.Variable. I was trying to work out a TensorFlow tutorial in Go instead of python but the absence of Variable made it impossible. I did spot some 'low-level' operators that seem related to variables, and thought maybe the Variable functionality can be built on top of that?

**Comment by asimshankar** [comment]
You're absolutely right on both counts :) - The Go API doesn't provide the equivalent of `tf.Variable` but it does provide enough to build that functionality.

I took at stab at a quick implementation, see: https://github.com/asimshankar/go-tensorflow/tree/master/variable

There are a few caveats here, such as:
- This example is using an in-progress, not-yet-finalized implementation for variables using the `DT_RESOURCE` type
- The Python `tf.Variable` class does a few more things, like explicitly colocating all the ops on the same device and adding the created variable to a list of variables kept in the `MetaGraphDef` (using Collections).

Depending on your use case, these may not matter. 

I'm going to mark this as "Contributions Welcome" as we don't have any immediate plans to pursue this, but if anyone else wants to, we'd be happy to guide them.

(FYI @jhseu)

**Comment by notnot** [comment]
Thanks! I didn't expect it could be implemented in so few lines of code. I'm not a TensorFlow expert (yet), just sniffing around basically :)
The tf.device class isn't available in Go either, and regarding this functionality, i didn't even see any C library functions to handle devices?

**Comment by asimshankar** [comment]
To colocate operations, you need to specify the colocation constraint when creating the operation. This is the `TF_ColocateWith` call in the C library, which should eventually make its way to the `Scope` type in Go.

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
