### ISSUE TITLE
Documentation incorrect for RNN tutorial?

### ISSUE THREAD

**Issue by CarbonComputed** [tensorflow/tensorflow#8263]
Is it possible the documentation is incorrect on https://www.tensorflow.org/tutorials/recurrent ?

```
words = tf.placeholder(tf.int32, [batch_size, num_steps])
for i in range(num_steps):
    # The value of state is updated after processing each batch of words.
    output, state = lstm(words[:, i], state)
```

It seems the correct output should be:
`    output, state = lstm(words[i, :], state)`

Since you want to process the words in the same sequence correct?

E.g.
[[The, quick, brown]
 [fox, jumped, over]]

words[:,0] == [The, fox]

Whereas what you want is [The, quick, brown]  == words[0,:]

Please correct me if I'm wrong, thanks.

**Comment by prb12** [comment]
This looks wrong to my admittedly untrained eye (and doesn't match https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py#L146)

@xmbrst Who is the author of this tutorial?

**Comment by xmbrst** [comment]
Looks like Rafal Jozefowicz, originally.

**Comment by CarbonComputed** [comment]
Upon looking over this, I see whats being done here. They process in batches and store the running state for each batch. However, what led me to this confusion was the first example in the tutorial takes a batch of words as input, so it doesn't seem to make sense when compared to the Truncated Backprop example.  The initial example probably should be more clear on what a batch of words looks like in this example. Mainly I think many would appreciate just a bit more detail than the pseudo code provided.

**Comment by martinwicke** [comment]
Since you have understood it, could you add annotations (comments) in a PR?

**Comment by CarbonComputed** [comment]
@martinwicke Sure. I'm not sure where the code for the tutorials lives however. (https://www.tensorflow.org/tutorials/recurrent). Any thoughts?

**Comment by martinwicke** [comment]
The code lives here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/tutorials/recurrent.md

**Comment by CarbonComputed** [comment]
@martinwicke https://github.com/tensorflow/tensorflow/pull/9746
Hopefully my changes make sense.
