### ISSUE TITLE
1.0.1 CPU vs GPU 1.0.0 Build for Windows

### ISSUE THREAD

**Issue by apiszcz** [tensorflow/tensorflow#8269]
The CPU build is complete for version 1.0.1 on Windows, however the GPU build is at 1.0.0.

http://ci.tensorflow.org/job/nightly-win/DEVICE=gpu,OS=windows/

**Comment by mrry** [comment]
Perhaps I'm reading this wrong, but it looks like the last built artifact for that build is TensorFlow 1.0.1:
http://ci.tensorflow.org/job/nightly-win/DEVICE=gpu,OS=windows/lastSuccessfulBuild/artifact/cmake_build/tf_python/dist/tensorflow_gpu-1.0.1-cp35-cp35m-win_amd64.whl

**Comment by apiszcz** [comment]
Update there now. THanks.
