### ISSUE TITLE
LSTM Network

### ISSUE THREAD

**Issue by sawsengh** [tensorflow/tensorflow#8274]
Hi, I have the error below when i execute the line ""lstm_cell = tf.nn.rnn_cell.BasicLSTMCell(config.n_hidden, forget_bias=1.0)""
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'
I was installed Tensorflow on windows using "Installing with Anaconda"
Any one have the same error and solve it Please!

**Comment by zakizhou** [comment]
they were all moved to tf.contrib.rnn.core_rnn_cell, if you read any tutorial about rnn like language model on the official site,  you will found that

**Comment by prb12** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
