### ISSUE TITLE
Tensordot sometimes fails one of the operands has a single dimension

### ISSUE THREAD

**Issue by person594** [tensorflow/tensorflow#8281]
This error occurs when one operand has a single dimension, and the other operand has a dimension of None.  To reproduce:

A = tf.placeholder(tf.float32, [None, 20])
B = tf.placeholder(tf.float32, [20])
C = tf.tensordot(A, B, [[1], [0]])

throws `TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [int32, float32] that don't all match.` when trying to calculate the shape of the resulting tensor.

I've actually fixed this, I'll submit a pull request momentarily.  I just figured I would submit an issue first for clarity.
This is probably related to #6682; I'll might look into that as well

**Comment by prb12** [comment]
OK - leaving open as a tracking bug.  I'll assign the 'awaiting response' tag to record the fact that we're expecting to see a PR

**Comment by person594** [comment]
By the way, I've submitted the pull request at #8282

**Comment by person594** [comment]
Resolved with #8282
