### ISSUE TITLE
Inconsistency with 'height_shift_range' and 'width_shift_range' parameters in ImageDataGenerator

### ISSUE THREAD

**Issue by RicardoRobledo** [tensorflow/tensorflow#82838]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.18.0

### Custom code

Yes

### OS platform and distribution

Windows

### Python version

3.11.10

### Current behavior?

The parameters are exchanged, 'height_shift_range' moves left and right and 'width_shift_range' moves up and bottom.

<br>

```python
from numpy import expand_dims
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from matplotlib import pyplot
# load the image
img = load_img('bird.jpg')
# convert to numpy array
data = img_to_array(img)
# expand dimension to one sample
samples = expand_dims(data, 0)
# create image data augmentation generator
datagen = ImageDataGenerator(width_shift_range=[-100,100])# ------- WIDTH_SHIFT_RANGE
# prepare iterator
it = datagen.flow(samples, batch_size=1)
# generate samples and plot
for i in range(9):
    # define subplot
    pyplot.subplot(330 + 1 + i)
    # generate batch of images
    batch = next(it)
    # convert to unsigned integers for viewing
    image = batch[0].astype('uint8')
    # plot raw pixel data
    pyplot.imshow(image)
# show the figure
pyplot.show()
```
![image](https://github.com/user-attachments/assets/0ccd8332-5c37-418e-9182-0d534fdbf1ba)

<br>
<br>

```python
from numpy import expand_dims
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from matplotlib import pyplot
# load the image
img = load_img('bird.jpg')
# convert to numpy array
data = img_to_array(img)
# expand dimension to one sample
samples = expand_dims(data, 0)
# create image data augmentation generator
datagen = ImageDataGenerator(height_shift_range=[-100,100]) # ------- HEIGTH_SHIFT_RANGE
# prepare iterator
it = datagen.flow(samples, batch_size=1)
# generate samples and plot
for i in range(9):
    # define subplot
    pyplot.subplot(330 + 1 + i)
    # generate batch of images
    batch = next(it)
    # convert to unsigned integers for viewing
    image = batch[0].astype('uint8')
    # plot raw pixel data
    pyplot.imshow(image)
# show the figure
pyplot.show()
```
![image](https://github.com/user-attachments/assets/e03dc6af-86b6-4b31-ac29-1f9fe4442a89)

### Standalone code to reproduce the issue

```shell
Use the parametes like: ImageDataGenerator(height_shift_range=[-100,100]) and ImageDataGenerator(width_shift_range=[-100,100])
```

**Comment by vaibhavi089** [comment]
can you elaborate this issue more?

**Comment by tilakrayal** [comment]
@RicardoRobledo,
In the Keras3.0(default for the tensorflow2.17/2.18) the [ImageDataGenerator ](https://github.com/keras-team/keras/blob/master/keras/legacy/preprocessing/image.py)has been deprecated.
**image_dataset_from_directory** is the replacement of the **ImageDataGenerator**, for augmentation you need to use preprocessing layer separately.
For more details on API usage, visit https://keras.io/api/data_loading/image/#image_dataset_from_directory-function.

If you want to use the keras2.0, try to use the below code for the import and then try to test the code.

```python
!pip install tf-keras
import tf_keras as keras
```

Thank you!
