### ISSUE TITLE
filter_format for Native Layouts of Convolution Filter Weights

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#8287]
Repost from: https://github.com/tensorflow/tensorflow/issues/7187#issuecomment-285217279.

I suggest adding a `filter_format` to the conv2d op to indicate how the filter weights are stored (similar to `data_format` for the input / output format). 

The [docs for TF](https://www.tensorflow.org/extend/tool_developers/#weight_formats) state: 
>The ordering of convolution weight values is often tricky to deal with when converting between different frameworks. In TensorFlow, the filter weights for the Conv2D operation are stored on the second input, and are expected to be in the order [filter_height, filter_width, input_depth, output_depth], where filter_count increasing by one means moving to an adjacent value in memory.

This will allow various kernel implementers to store weights more efficiently (and mark them as such for down the road conversions).

In addition to cuDNN, BNNS (https://github.com/tensorflow/tensorflow/issues/3001) also uses that same format.

This needs to be benchmarked, but I assume there is some cost to having to transpose the filter weights during both fprop and bprop (twice). This could even explain some of the performance differences between TF and other frameworks (eg pytorch).

It looks like TF already [has some concept of these difference](https://github.com/tensorflow/tensorflow/blob/067cba5e4b873829f6cdfa61256079d2cfc45d02/tensorflow/stream_executor/dnn.h#L340-L346). Although as of now all weights are converted from / back to one canonical format.

While [most users won't tune this](https://github.com/tensorflow/tensorflow/issues/8227), it could be used by xla / optimization passes to choose better layouts.

**Comment by prb12** [comment]
@zheng-xq Not sure if you have looked into this?

I don't understand the comment about XLA and rewriting though - if the format of the data and filter are canonical, and consistently transformed under the hood to improve performance, it shouldn't make any difference whether the user program has tried to prematurely optimize the layout in a platform-specific manner ;-)

**Comment by cancan101** [comment]
I was thinking right now if an optimization pass wanted to change the filter format, the current ops don't expose the parameter for rewriting.

**Comment by prb12** [comment]
There's no reason an optimization pass needs to keep the same ops...  In my opinion, the cleanest design is for the program to be written using generic ops with well defined semantics, and then any 3rd party wanting to add support for their super-fast library or accelerator supplies two things:
1) A set of additional (internal) ops if necessary, with whatever flags/attrs extra inputs/outputs they feel like, and
2) A GraphOptimizationPass which transparently, at execution time, rewrites the clean, portable graphdef to use their platform specific ops (the rewritten graph is cached so this is a one-off overhead)

This way we avoid the need to add extra vendor- and platform-specific options to every op in TensorFlow ;-) 

When we translate parts of a graph into XLA, entire parts of the graph are replaced by a single 'XlaLaunch' op and and conv ops in the fused computation get turned into XLA convolution operators which support arbitrary layout permutations.  The XLA optimizer is free to do what it likes with physical layout (though on GPU we still currently call out to cuDNN).

**Comment by cancan101** [comment]
Your point about optimization passes makes sense. I guess a better case would be, does it make sense to allow users to _explicitly_ choose a different format for the filter weights, and if so, should that be done by adding a new parameter to the existing conv2d op? The idea would be in the vein of `data_format`. It actually might be more important to make this explicit since when the user dumps the weights out, they need to know what format they are in.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by cancan101** [comment]
I think this is still relevant as an open issue.

**Comment by girving** [comment]
@cancan101 It looks like no one is working on it, or planning to work on it.  Is that right?
