### ISSUE TITLE
No allowing GPU memory growth option in contrib.learn. Estimator

### ISSUE THREAD

**Issue by taejoon89** [tensorflow/tensorflow#8291]
When creating estimator using contrib.learn, only GPU option that I can find is "gpu_memory_fraction" which can be found at "tf.contrib.learn.RunConfig"

`classifier = learn.Estimator(
    model_fn=cnn_model_fn,
    config=learn.RunConfig(gpu_memory_fraction=0.9)
    )`

Is there a way to allow GPU memory growth option when using contrib.learn ?

**Comment by prb12** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by yaroslavvb** [comment]
@taejoon89 you can use monkey-patching trick from https://github.com/tensorflow/tensorflow/issues/7794

**Comment by taejoon89** [comment]
Thanks ~
