### ISSUE TITLE
Could not use tensorboard in Win10?

### ISSUE THREAD

**Issue by cumttang** [tensorflow/tensorflow#8293]
When I attempt to use tensorboard to show the tensor scalar and image, however, it can not show the detail in the browser.
![qq 20170311094208](https://cloud.githubusercontent.com/assets/16380725/23819278/0c0a960c-063f-11e7-87f0-e49730661e0d.png)

But when I used it in Ubuntu, it works. What's wrong with Win10?

**Comment by prb12** [comment]
Could you please provide details of how your are running TensorBoard and some output from the log files.

Also, please can you verify that you are not having the same problem as #7856

**Comment by cumttang** [comment]
YES. It's the same question as #7856. When transoform c:/ to f:/(where work directory in). It works perfectly.

THANKS A LOT.
