### ISSUE TITLE
undefined symbol: tflite::StatefulNnApiDelegate::StatefulNnApiDelegate(tflite::StatefulNnApiDelegate::Options)

### ISSUE THREAD

**Issue by angelOnly** [tensorflow/tensorflow#82973]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.18

### Custom code

Yes

### Python version

3.12

### Bazel version

6.5

### GCC/compiler version

14.2

### Current behavior?

When I was compiling my own cpp file with ndk-build, I reported the following error
```
ld: error: undefined symbol: tflite::StatefulNnApiDelegate::StatefulNnApiDelegate(tflite::StatefulNnApiDelegate::Options)
>>> referenced by TFLiteEngine.cpp:77
>>>               /Users/jiang/Downloads/ifeng/java/NdkBuilderne/app/src/main/obj/local/armeabi-v7a/objs/pose2dto3d_armeabi-v7a/TFLiteEngine.o:(TFLiteEngine::loadModel(AAssetManager*))
clang++: error: linker command failed with exit code 1 (use -v to see invocation
```

**compileSdkVersion 33**
**buildToolsVersion '30.0.3'**
**ndk.dir=/Users/jiang/Library/Android/sdk/ndk/22.1.7171670**

bazel shell
```
bazel build -c opt --config=android_arm --repo_env=HERMETIC_PYTHON_VERSION=3.12  --define tflite_with_nnapi=true --verbose_failures tensorflow/lite:libtensorflowlite.so
```

Android.mk
```
LOCAL_PATH := $(call my-dir)

cur_arch=armeabi-v7a
LOCAL_CPPFLAGS := -g

# 第三方.so
include $(CLEAR_VARS)
LOCAL_MODULE := libtensorflowlite
LOCAL_SRC_FILES := third/android/$(cur_arch)/lib/libtensorflowlite.so
include $(PREBUILT_SHARED_LIBRARY)

# 自己的c代码
include $(CLEAR_VARS)
LOCAL_MODULE    := pose2dto3d_$(cur_arch)
MY_C_LIST := $(wildcard $(LOCAL_PATH)/TFLiteEngineJNI.cpp)
MY_C_LIST += $(wildcard $(LOCAL_PATH)/TFLiteEngine.cpp)
MY_C_LIST += $(wildcard $(LOCAL_PATH)/DataProcess.cpp)
LOCAL_SRC_FILES := $(MY_C_LIST:$(LOCAL_PATH)/%=%)

# 第三方头文件
# tflite
MY_ALL_DIRS := $(wildcard $(LOCAL_PATH)/)
MY_ALL_DIRS += $(wildcard $(LOCAL_PATH)/third/android/$(cur_arch)/include)
LOCAL_C_INCLUDES := $(MY_ALL_DIRS)

LOCAL_LDLIBS += -llog -lz -landroid -lOpenSLES -lGLESv1_CM -lGLESv2 -lneuralnetworks

LOCAL_STATIC_LIBRARIES := libtensorflowlite

LOCAL_CFLAGS += -UNDEBUG -D_DEBUG
include $(BUILD_SHARED_LIBRARY)
```

Application.mk
```
APP_OPTIM :=release
APP_ABI := armeabi-v7a
APP_PLATFORM := android-27
APP_STL := c++_static
```

.cpp
```
# include <stdio.h>
# include <stdlib.h>
#include <android/asset_manager_jni.h>
#include <android/asset_manager.h>
#include <android/log.h>
# include <jni.h>
#include <sys/uio.h>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>
#include "tensorflow/lite/interpreter.h"
#include "tensorflow/lite/model.h"
#include "tensorflow/lite/kernels/register.h"
#include "tensorflow/lite/optional_debug_tools.h"
#include "tensorflow/lite/interpreter_builder.h"
#include "tensorflow/lite/model_builder.h"
#include "tensorflow/lite/delegates/nnapi/nnapi_delegate.h"
#include "TFLiteEngine.h"
#include "Pose3dModel.h"


TFLiteEngine::TFLiteEngine() {
    is_tflite_initialized = false;
}

TFLiteEngine::~TFLiteEngine() {}

void TFLiteEngine::loadModel(AAssetManager *mgr) {
    __android_log_print(ANDROID_LOG_DEBUG, "POSE_3D_CPP",
                        "..................Entering loadModel....................");

    if (!pose3dModel.is_tflite_initialized) {
        pose3dModel.asset = AAssetManager_open(mgr, MODEL_PATH, AASSET_MODE_BUFFER);
        if (pose3dModel.asset == nullptr) {
            __android_log_print(ANDROID_LOG_DEBUG, "POSE_3D_CPP", "pose3dInference asset null----");
            exit(1);
        }

        // 获取文件的大小
        off_t file_length = AAsset_getLength(pose3dModel.asset);
        // 从资产中读取数据到内存
        std::vector<char> model_data(file_length);
        AAsset_read(pose3dModel.asset, model_data.data(), file_length);

        // 1，创建模型和解释器对象，并加载模型
        pose3dModel.model = tflite::FlatBufferModel::BuildFromBuffer(model_data.data(),
                                                                     model_data.size());
        if (!pose3dModel.model) {
            __android_log_print(ANDROID_LOG_DEBUG, "POSE_3D_CPP",
                                "pose3dInference 加载模型失败----");
            exit(1);
        }

        __android_log_print(ANDROID_LOG_DEBUG, "POSE_3D_CPP", "pose3dInference 加载模型成功----");

        tflite::InterpreterBuilder builder(*(pose3dModel.model.get()), pose3dModel.resolver);
        builder(&(pose3dModel.interpreter));

        if (!pose3dModel.interpreter) {
            __android_log_print(ANDROID_LOG_DEBUG, "POSE_3D_CPP",
                                "pose3dInference interpreter null----");
            exit(1);
        }

        if (NUM_THREADS != -1) {
            pose3dModel.interpreter->SetNumThreads(NUM_THREADS);
        }

        // NNAPi设置
        tflite::StatefulNnApiDelegate::Options options;
        options.execution_preference = tflite::StatefulNnApiDelegate::Options::kSustainedSpeed;
        options.use_burst_computation = true;
        options.allow_fp16 = true;

        if ((pose3dModel.delegate = new tflite::StatefulNnApiDelegate(options)) == NULL) {
            __android_log_print(ANDROID_LOG_DEBUG, "POSE_3D_CPP", "pose3dInference NNAPI delegate error----");
            exit(1);
        }

        if (pose3dModel.delegate != NULL) {
            TfLiteStatus status = pose3dModel.interpreter->ModifyGraphWithDelegate(pose3dModel.delegate);
            if (status != TfLiteStatus::kTfLiteOk)
                __android_log_print(ANDROID_LOG_DEBUG, "POSE_3D_CPP", "pose3dInference Failed to modify graph with delegate!----");
        }

        if (pose3dModel.interpreter->AllocateTensors() != kTfLiteOk) {
            __android_log_print(ANDROID_LOG_DEBUG, "POSE_3D_CPP",
                                "pose3dInference AllocateTensors ERROR----");
            exit(1);
        }

        pose3dModel.input = pose3dModel.interpreter->typed_input_tensor<float>(0);
        if (pose3dModel.input == nullptr) {
            __android_log_print(ANDROID_LOG_DEBUG, "POSE_3D_CPP", "pose3dInference input null----");
            exit(1);
        }
        __android_log_print(ANDROID_LOG_DEBUG, "POSE_3D_CPP", "pose3dInference 初始化input----");

        is_tflite_initialized = true;
    }
    __android_log_print(ANDROID_LOG_DEBUG, "POSE_3D_CPP",
                        "..................Exiting loadModel....................");

    if (pose3dModel.asset != nullptr) {
        AAsset_close(pose3dModel.asset);
    }
}
```

### Standalone code to reproduce the issue

```shell
just ndk build my cpp

ndk-build V=1
```
```


### Relevant log output

_No response_

**Comment by angelOnly** [comment]
I tried the following script to set more NNAPI-related parameters, but it still didn't work

Reference link: [https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/delegates#nnapi-delegate-provider](url)

```
bazel build -c opt \
  --config=android_arm \
  --repo_env=HERMETIC_PYTHON_VERSION=3.12 \
  --define tflite_with_nnapi=true \
  --define use_nnapi=true \
  --define nnapi_accelerator_name="" \
  --define nnapi_execution_preference="low_power" \
  --define nnapi_execution_priority="high" \
  --define nnapi_allow_fp16=false \
  --define nnapi_allow_dynamic_dimensions=false \
  --define nnapi_use_burst_mode=true \
  --verbose_failures \
  tensorflow/lite:libtensorflowlite.so
```

**Comment by yg-dickson** [comment]
Is there any tutorial for building LiteRT for Android?

**Comment by gaikwadrahul8** [comment]
Hi, @angelOnly 
Thank you for trying script to set more NNAPI-related parameters so but it didn't work so if you don't mind could you please after downgrading the TensorFlow version to either 2.17.* or 2.16.* and see is it working fine or not ? 

Hi, @yg-dickson, Please refer this LiteRT [examples](https://github.com/tensorflow/examples/tree/master/lite/examples) of android and official documentation of [Build LiteRT for Android](https://ai.google.dev/edge/litert/android/lite_build)

Thank you for your cooperation and patience.

**Comment by angelOnly** [comment]
Hello, thank you very much for your reply! 
I have read the example you gave. This is the compilation process of java inference, while I use c++ inference, which needs to compile the.so package instead of.aar. And I hope to support nnapi delegate. I don't know how to fix it.

> Hi, @angelOnly Thank you for trying script to set more NNAPI-related parameters but it didn't work so if you don't mind could you please downgrade the TensorFlow version to either 2.17.* or 2.16.* and see is it working fine or not ?
> 
> Hi, @yg-dickson, Please refer this LiteRT [examples](https://github.com/tensorflow/examples/tree/master/lite/examples) of android and official documentation of [Build LiteRT for Android](https://ai.google.dev/edge/litert/android/lite_build)
> 
> Thank you for your cooperation and patience.

**Comment by angelOnly** [comment]
> Is there any tutorial for building LiteRT for Android?

I can't find any relevant courses. Do you have any recommendations

**Comment by angelOnly** [comment]
I have determined where the problem is, because the model does not support some operators of nnapi, resulting in GPU acceleration, but I still failed to compile and open nnapi, I used the gpu delegate to verify this problem.
Download the official posenet model verification, can be gpu accelerated, and our model does not support gpu acceleration

nnapi support opt：https://www.tensorflow.org/lite/android/delegates/nnapi?hl=zh-cn#use_supported_models_and_ops
gpu delegate Compiled.so package：https://github.com/ValYouW/tflite-dist/releases
![image](https://github.com/user-attachments/assets/7e7068b1-9040-4de8-8c96-9a8978d6c278)
<img width="1298" alt="image" src="https://github.com/user-attachments/assets/758adafa-6ba0-45bd-80e5-bd6e53f5f1de" />
![image](https://github.com/user-attachments/assets/4069972b-2b77-441b-8db5-37035e890fb5)

**Comment by yg-dickson** [comment]
> Hi, @angelOnly Thank you for trying script to set more NNAPI-related parameters but it didn't work so if you don't mind could you please downgrade the TensorFlow version to either 2.17.* or 2.16.* and see is it working fine or not ?
> 
> Hi, @yg-dickson, Please refer this LiteRT [examples](https://github.com/tensorflow/examples/tree/master/lite/examples) of android and official documentation of [Build LiteRT for Android](https://ai.google.dev/edge/litert/android/lite_build)
> 
> Thank you for your cooperation and patience.

Following this tutorial, I cannot build
com.google.ai.edge.litert:litert
com.google.ai.edge.litert:litert-gpu

**Comment by gaikwadrahul8** [comment]
Hi, @yg-dickson 
Apologize for the delayed response, could you please create new issue here :https://github.com/google-ai-edge/LiteRT/issues/new and mention what all steps you followed in that issue ? we will be happy to help you further. 

Thank you for your cooperation and understanding.

**Comment by yg-dickson** [comment]
LiteRT No one answered
