### ISSUE TITLE
tf.contrib.seq2seq.prepare_attention doesn't allow decoder states and attention states to be different lengths

### ISSUE THREAD

**Issue by abisee** [tensorflow/tensorflow#8299]
I'm using the new `tf.contrib.seq2seq.prepare_attention` with `tf.contrib.seq2seq.attention_decoder_fn_train` and `tf.contrib.seq2seq.dynamic_rnn_decoder` to do dynamic decoding with attention. 

If we are using e.g. `attention_option="bahdanau"`, then [this line](https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/contrib/seq2seq/python/ops/attention_decoder_fn.py#L408) implements the standard attention equation:

score<sub>i</sub> = v<sup>T</sup> tanh(W<sub>h</sub> h<sub>i</sub> + W<sub>q</sub> q)

where 
- h<sub>i</sub> is the ith attention state, a vector length `num_units`
- W<sub>h</sub> is a weight matrix shape [`num_units`, `num_units`]
- q is the query (i.e. current decoder hidden state), a vector length `num_units`
- W<sub>q</sub> is a weight matrix shape [`num_units`, `num_units`]
- v is a weight vector length `num_units`

In particular, the code assumes that:
1. Decoder hidden states q and attention states h<sub>i</sub> are the same size (which isn't true if e.g. you want different size hidden vectors for your encoder and decoder, or you want to use bidirectional RNN for encoder but not decoder)
2. v, W<sub>h</sub> h<sub>i</sub> and W<sub>q</sub> q must also be same length `num_units`

In particular assumption 1 is very limiting. I think it would be better to allow:
- h<sub>i</sub> is the ith attention state, a vector length `attn_size`
- W<sub>h</sub> is a weight matrix shape [`num_units`, `attn_size`]
- q is the query (i.e. current decoder hidden state), a vector length `query_size`
- W<sub>q</sub> is a weight matrix shape [`num_units`, `query_size`]
- v is a weight vector length `num_units`

where the user can define `num_units`, `attn_size` and `query_size`. From what I can see this would be fairly uncomplicated.

**Comment by prb12** [comment]
@ebrevdo Do you know who is the owner of this code?

**Comment by ebrevdo** [comment]
Probably thang luong.  He and I are working on a new dynamic attention
RNNCell wrapper  where I do separate out these dimensions into separate
parameters!  Will try to push that code on monday.

**Comment by ebrevdo** [comment]
(this code has been deleted in github master, in favor of the new object
oriented style)

**Comment by prb12** [comment]
@ebrevdo Thanks for the information.  I'm going to close this as a "bug" since it looks like the existing code is going away and a replacement is imminent which doesn't have this problem.
