### ISSUE TITLE
tensorflow not running on pycharm

### ISSUE THREAD

**Issue by engmoha80** [tensorflow/tensorflow#82992]
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

**Comment by tilakrayal** [comment]
@engmoha80,
Could you please provide the tensorflow and the compatible version which you are trying to install. Also there are at least 3 possible scenarios:

```python
- You need to install the MSVC 2019 redistributable
- Your CPU does not support AVX2 instructions
- Your CPU/Python is on 32 bits
- There is a library that is in a different location/not installed on your system that cannot be loaded.
```

Also kindly provide the environment details and the steps followed to install the tensorflow.
https://github.com/tensorflow/tensorflow/issues/61887
Thank you!

**Comment by mihaimaruseac** [comment]
Duplicate of #19584. Please do a search before opening new issues. This is a very old issue and manifests because old PCs with Windows cannot load libraries needed by TF because they have very old architecture sets.
