### ISSUE TITLE
can't install on ubuntu 12.04

### ISSUE THREAD

**Issue by XuChunling** [tensorflow/tensorflow#83]
when i install it use the command
sudo pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl

there is error 
No such file or directory: '/tmp/pip-byRUCn-build/setup.py'

**Comment by anjishnu** [comment]
Update your pip to the latest version 

duplicate - https://github.com/tensorflow/tensorflow/issues/53

**Comment by vincentvanhoucke** [comment]
Closing as duplicate
