### ISSUE TITLE
fully_connected_preloaded.py fails with exception on python3.5

### ISSUE THREAD

**Issue by taras-sereda** [tensorflow/tensorflow#830]
There are some errors while handling exception `tf.errors.OutOfRangeError`:
On python2 no issues with handling `tf.errors.OutOfRangeError`.

During handling of the above exception, another exception occurred.
log:
```python
Traceback (most recent call last):
  File "fully_connected_preloaded.py", line 158, in <module>
    tf.app.run()
  File "/Users/home/tensorflow_python3/lib/python3.5/site-packages/tensorflow/python/platform/default/_app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "fully_connected_preloaded.py", line 154, in main
    run_training()
  File "fully_connected_preloaded.py", line 120, in run_training
    _, loss_value = sess.run([train_op, loss])
  File "/Users/home/tensorflow_python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 368, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/Users/home/tensorflow_python3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 428, in _do_run
    target_list)
SystemError: <built-in function delete_Status> returned a result with an error set
```

**Comment by josh11b** [comment]
Geoffrey is our Python 3 expert, perhaps he can help.

**Comment by girving** [comment]
Please split this issue into two: the GPU issue is not related to the Python 3 issue if it also happens on Python 2.

**Comment by girving** [comment]
For the Python 3 error, I'm trying to find the relevant function now, but I may need some way of reproducing the problem unless something obvious arises.

**Comment by girving** [comment]
Yeah, I think this is some sort of horrible swig issue, so I'll need a way to reproduce.  Can you make a minimal test case that causes the exception?

**Comment by taras-sereda** [comment]
Hey, here is minimal test case:
```python
import tensorflow as tf
import numpy as np
import sys

x = tf.constant(np.array([1, 2, 3, 4]))
y = tf.constant(np.array([1, 2, 3, 4]))

single_x, single_y = tf.train.slice_input_producer([x, y], num_epochs=3)
batch_x, batch_y = tf.train.batch([single_x, single_y], batch_size=1)

sum_op = batch_x + batch_y

sess = tf.Session()
sess.run(tf.initialize_all_variables())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)



try:
    step = 0
    while not coord.should_stop():
        res = sess.run(sum_op)
        step += 1
        print(res, step)
        sys.stdout.flush()
except tf.errors.OutOfRangeError:
    print("Exception hear")
finally:
    coord.request_stop()

coord.join(threads)
```

**Comment by girving** [comment]
Thanks!  I'll take a look.

**Comment by girving** [comment]
Apologies for taking forever to get to this.  Unfortunately, I am unable to reproduce the problem: even on Python 3, I hit the exception every time (out of 1101 test runs).

**Comment by martinwicke** [comment]
I can reproduce it. In fact, it's a pervasive problem whenever you run with python3.5. See #1033.

**Comment by martinwicke** [comment]
The culprit seems to be this: https://bugs.python.org/issue23571

**Comment by martinwicke** [comment]
I think we're suffering from this: https://github.com/swig/swig/issues/567, and the solution may be this: https://github.com/swig/swig/pull/560

**Comment by martinwicke** [comment]
I'll try installing a fresh swig.

**Comment by girving** [comment]
@martinwicke: Was this fixed?

**Comment by martinwicke** [comment]
Yes. For posterity: Upgrade to swig >=3.0.8.
