### ISSUE TITLE
tf.image.resize_image_with_crop_or_pad

### ISSUE THREAD

**Issue by weigq** [tensorflow/tensorflow#8305]
hi, 
I`m moving a project from r0.11 to r0.10, and I have some bug in 0.10 running this script:
```
      print('before', label.get_shape())
      label = tf.image.resize_image_with_crop_or_pad(label, h, w)
      print('after',label.get_shape())
```
the results is :
```
('before', TensorShape([Dimension(None), Dimension(None), Dimension(1)]))
('after', TensorShape([Dimension(321), Dimension(321), Dimension(None)]))
```
but when I test in r0,11, the results:
```
('before', TensorShape([Dimension(None), Dimension(None), Dimension(1)]))
('after', TensorShape([Dimension(321), Dimension(321), Dimension(1)]))
```
the input of the above two functions is the same.
I can not find where it gets wrong.
any one can help me?

**Comment by prb12** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
