### ISSUE TITLE
keras.layers.GRU behaves differently in GPU and CPU

### ISSUE THREAD

**Issue by lwk8891** [tensorflow/tensorflow#83119]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.18, tf 2.19

### Custom code

Yes

### OS platform and distribution

WSL Ubuntu 22.04.5 LTS

### Python version

3.12

### CUDA/cuDNN version

12.6/9.6

### Current behavior?

The result of the following code is the length of the GRU output variable.

The result is 2 when I executed the code with no GPU by `export CUDA_VISIBLE_DEVICES= `.  One is the output sequence, and the other is the state of GRU. However, the result is 5 = 1 + batch_size when I executed the code with GPU. The first is the output sequence, and the others are the state of GRU with batch unpacking.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.keras.layers import GRU

batch_size = 4
time_steps = 10
rnn_dimension = 16
input_dim = 8

x = tf.random.normal((batch_size, time_steps, input_dim))

gru = GRU(rnn_dimension, return_sequences=True, return_state=True)

gru_output = gru(x, training=True)
print(len(gru_output))
```

**Comment by lwk8891** [comment]
> Hi **@lwk8891** , Apologies for the delay, and thank you for raising your concern. I tried running your code on Colab using TensorFlow 2.18.0 with both CPU [gist](https://colab.sandbox.google.com/gist/Venkat6871/4c365dfcd83e2d3c2e2ebafa0479fcd6/83119_tf-2-18-0-cpu-v.ipynb) and GPU and faced the same issue. The reason behind this issue is that when running on a GPU, TensorFlow uses the cuDNN-optimized GRU kernel. Even if you set `implementation=2`, the output may still differ on the GPU because the GRU layer internally optimizes for cuDNN, which can unpack the batch dimension for hidden states.
> 
> To resolve this, you need to explicitly disable the cuDNN kernel for the GRU. I achieved this by setting `reset_after=False`, and it produced the expected results. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/78ae3171c3750f66b36298dbda06c94b/83119_tf_2-18-0-gpu-v.ipynb) here for your reference. Thank you!

Thank you. It solved the problem.
However, would setting `reset_after=False` affect the performance of the program by disabling the cuDNN kernel?

**Comment by Venkat6871** [comment]
Hi **@lwk8891** ,
Glad to see your issue is resolved. However, I suspect there might be a performance impact when using reset_after=False.
Thank you!
