### ISSUE TITLE
out_depth not set in PoolParameters if depth_window == 1

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#8313]
In `PoolParameters`, `out_depth` is not set if `depth_window == 1`.
See: https://github.com/tensorflow/tensorflow/blob/754048a0453a04a761e112ae5d99c149eb9910dd/tensorflow/core/kernels/pooling_ops_common.cc#L61-L66.

**Comment by prb12** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!
