### ISSUE TITLE
Where is the document of tf.keras?

### ISSUE THREAD

**Issue by arsenal0502** [tensorflow/tensorflow#8316]
It is said that Google have released tf.keras in the lastest version,but I can't find the document.

**Comment by prb12** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by pengpaiSH** [comment]
@arsenal0502 It is said that tf.keras will be supported since TensorFlow Version 1.2.

**Comment by arsenal0502** [comment]
Thank you very much!

At 2017-03-17 12:04:36, "Pai Peng" <notifications@github.com> wrote:


@arsenal0502 It is said that tf.keras will be supported since TensorFlow Version 1.2.
