### ISSUE TITLE
Building from source on macOS: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by jd20** [tensorflow/tensorflow#8317]
I found two other issues mention this error, though none of the proposed solutions fixed the problem for me.

Operating System: macOS Sierra 10.12.3

Installed version of CUDA and cuDNN: None

On a fresh install of Sierra, I've used brew to install bazel, python, python3 (which gives me 3.6.0), pyenv, and the virtualenv plugin for pyenv. I'm following the "Build from source" instructions for Mac, created a virtual environment specifically for building tensorflow, and when running ./configure using all the defaults and answering N to all the questions. At the final step, building the wheel, I get:

```
(build-tensorflow) ❯ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Sat Mar 11 18:35:17 PST 2017 : === Using tmpdir: /var/folders/z0/l02zt19x3rvdq8ns17x5tznm0000gn/T/tmp.XXXXXXXXXX.Jfkzndt3
~/Code/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles ~/Code/tensorflow
~/Code/tensorflow
/var/folders/z0/l02zt19x3rvdq8ns17x5tznm0000gn/T/tmp.XXXXXXXXXX.Jfkzndt3 ~/Code/tensorflow
Sat Mar 11 18:35:19 PST 2017 : === Building wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
```

I thought this was maybe a pip or setuptools version issue, but they all seem on the latest version. `pip list` outputs:

```
appdirs (1.4.3)
numpy (1.12.0)
packaging (16.8)
pip (9.0.1)
pyparsing (2.2.0)
setuptools (34.3.2)
six (1.10.0)
wheel (0.29.0)
```

Any help to understand how to resolve the bdist_wheel error will be much appreciated, thanks!

**Comment by prb12** [comment]
Can you confirm that the solutions in #7402  #348 didn't work for you?

Please can you confirm your python version?  (if you're using python3 you need to `pip3 install wheel`)

I assume you are following https://www.tensorflow.org/install/install_sources#prepare_environment_for_mac_os ?

**Comment by jd20** [comment]
Correct, the solutions I saw in those two issues (`pip install wheel` and `pip3 install wheel`) didn't resolve. Python version is 3.6.0, I created the environment using `pyenv virtualenv 3.6.0 build-tensorflow`. Created this way, python / pip are already mapped to python3 / pip3:

```
(build-tensorflow) ❯ python --version                       
Python 3.6.0
```

**Comment by CongWeilin** [comment]
i also have the same problem.
<img width="938" alt="wx20170314-132402 2x" src="https://cloud.githubusercontent.com/assets/18029500/23886932/8acf3d4a-08b9-11e7-88a4-da094be884f8.png">

**Comment by jd20** [comment]
@turbojava You're spot on, installing wheel for the global pyenv version resolved the problem. So, do you know... is that a bug with pyenv or tensorflow?

**Comment by concretevitamin** [comment]
Looks like a glitch outside of core TensorFlow itself.  Since you've found a workaround, I'm closing this.

**Comment by kzos** [comment]
@CongWeilin ,
setting pyenv global did nt help.

Which line of setup.py do we need to add sys.path.append.?

**Comment by Carmezim** [comment]
Depending how you installed the required dependencies, Pip may be associated with a different Python installation that TensorFlow is trying to find e.g. `/Library/Python/2.7/site-packages/` but the Pip used was associated to `/usr/local/lib/python2.7/site-packages`.

This corrected to the installed packages associated in my case.
`export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python2.7/site-packages`

**Comment by hankcs** [comment]
@Carmezim Thanks, you saved my day.
