### ISSUE TITLE
#FR CG pipeline in tf

### ISSUE THREAD

**Issue by biolee** [tensorflow/tensorflow#8318]
#in brief
build computer graphic render pipeline with tf

In GDC2017's talk ['FrameGraph: Extensible Rendering Architecture in Frostbite'](http://www.frostbite.com/2017/03/framegraph-extensible-rendering-architecture-in-frostbite), a few slide inspire me, why don't CG and CV use the same computation platform, share 'GPU cluster' 'memory management' and 'operation oplimization' code, iteract with each other directly.  I am going to implement a simple ray trace with tf, is there any comment or suggestion?

<img width="860" alt="screenshot" src="https://cloud.githubusercontent.com/assets/7426917/23828883/29b7d1f6-071b-11e7-80c4-99a95aaa2c4d.png">

<img width="869" alt="screenshot" src="https://cloud.githubusercontent.com/assets/7426917/23828862/89d7e978-071a-11e7-8195-5bb6353e01c6.png">

**Comment by prb12** [comment]
This seems very speculative and this is not supposed to be a discussion forum. 
I suspect that your question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). There is also a larger community that reads questions there.

Please feel free to reopen once you have more specifics.
