### ISSUE TITLE
Please remove all code visibility restrictions

### ISSUE THREAD

**Issue by rosun82** [tensorflow/tensorflow#8320]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

I am trying to use grpc_util to convert ::tensorflow::Status to ::grpc::Status, and found that I cannot build the target because of package visibility issues.

Here is my recommendation:

Remove all visibility when open source tensorflow. 

Reason:

1. It is pointless to have the package visibility as we have the source code, and we can modify it.

2. If everybody has to modify their own copy of tensorflow to depend on portions of the source code, it only makes people's life harder as there would be millions of different forks all trying to hack the BUILD file. And every time a new tensorflow is launched, it breaks other people's build, which seems quite counter productive.

3. In Google we want to make the dependency as accurate as possible. In the open source world, because of the visibility issue, we have to try to pull in much bigger build target to get something working, which is again, counter productive.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by drpngx** [comment]
@rosun82 I think we want to go in other direction. We should be removing access to internals from external libraries. This is quite customary for libraries, where the API surface is limited and maintained with an SLA (compatibility guarantees). Internals can be refactored and changed without breaking users.

An example of not doing this is the Win32 API, and more recently the LLVM API. If you have ever upgraded LLVM, this can be quite painful.

**Comment by rosun82** [comment]
If tensorflow is published as a dll file, I agree.

However, since it is released as source code, there is no real 'internal'. Whoever downloaded the code can modify it to make use of the internal code, which is often very necessary (like the tf status to grpc status conversion) My point is simply, if it is impossible to enforce what is 'internal', why not just remove the visibility constraints, making advanced user's life a bit simpler? After all, people who only use the public interface would not care whether the code is internal or not

**Comment by concretevitamin** [comment]
I agree with you that this is something only very advanced users _might_ do.  As such, I don't think we'll introduce complexities (AFAICT there are a lot of consequences of the purposed change) by doing this.

**Comment by martinwicke** [comment]
We are using package visibility to indicate what parts of the API are public and can be relied on to not change. We do not want people relying on implementation details, so we would like to keep visibility rules in place. 

If you think a specific rule should be public, please file a bug for that rule. Of course, as you noted, you also have the ability to modify the code to modify visibility yourself.
