### ISSUE TITLE
it seems that sparse_to_dense can only work in CPU?

### ISSUE THREAD

**Issue by rigorosyang** [tensorflow/tensorflow#8321]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by rigorosyang** [comment]
currently I want to generate one Dense Tensor by Sparse Tensor, it is very usual that generating one dense tensor with big dim(such as 100k dim) by some word indexs. but it seems sparse_to_dense op only works for CPU. so the problem is that if I have 8 GPUs,  I have to run sparse_to_dense 8 times in the CPU serially and send them to 8 GPUs, the  Parallel running performance is very bad!

**Comment by concretevitamin** [comment]
You're correct that TF only has a CPU kernel for SparseToDense (see [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sparse_to_dense_op.cc#L139)).  I don't think anyone is actively working on adding a GPU kernel for it -- we're happy to accept a pull request!

**Comment by rigorosyang** [comment]
Thanks for your comment, do you think is there working around method? because as I said, expanding the short words idx vector into large dense vector is very usual for ML.

**Comment by concretevitamin** [comment]
Do you need to use `SparseTensor` to represent the indices, though?  Would something like `tf.one_hot` work for you, which does have a GPU kernel?

**Comment by rigorosyang** [comment]
Thanks very much! I think the tf.one_hot can work for me.
