### ISSUE TITLE
Using a `tf.Tensor` as a Python `bool` is not allowed.  

### ISSUE THREAD

**Issue by danlutan** [tensorflow/tensorflow#8322]
I want to do ： IF True: return a ; else : return b (in python) . But there is a error : Using a `tf.Tensor` as a Python `bool` is not allowed.  How can I do this

**Comment by GR3C0** [comment]
Try use print(a) and print(b)

**Comment by danlutan** [comment]
`c=tf.placeholder(tf.bool)
if c  :
    loss=-tf.reduce_sum(lable * tf.log(lable2))`

raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

**Comment by concretevitamin** [comment]
This is intended.  Please use `tf.cond`.
