### ISSUE TITLE
i cant get tensorflow to install

### ISSUE THREAD

**Issue by Redtile** [tensorflow/tensorflow#8324]
i tried following the steps in the tutorial after installing python 3.6 and 3.5 then i went to cmd and typed in pip3 install --upgrade tensorflow and the gpu version i was told that it could not find a version that satisfies the requierments tensorflow (from versions: ) no matching distribution found for tensorflow. (same for the gpu one)
i also tried this: pip install --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.0-cp35-cp35m-win_amd64.whl : and i was told that it is not supported for this wheel which is understandable considering i have a nividia gpu and intel cpu but other than that i really dont know what to do if any one is able to give me commands to put in to the cmd terminal that would be great ill list my pc specs here: windows 7 pro, intel Q8300, nividia 560TI, 12GB DDR3 ram. as far as i know i have all the latest drivers installed and such and more than enough room for any files that might need to be downloaded. any help is appreciated.

**Comment by PhilJd** [comment]
Your pip version might be too old. You could try upgrading it with 
`pip install --upgrade pip`

If your distribution doesn't allow this consider using a virtual environment (check [this](http://docs.python-guide.org/en/latest/dev/virtualenvs/) out)

**Comment by Redtile** [comment]
it says that it is already up to date when i put that in it doesn't say anything about the distribution.

**Comment by PhilJd** [comment]
What's the output of `pip --version` (or `pip3 --version ` in your case)?

**Comment by Redtile** [comment]
pip 9.0.1 (then file directory)

**Comment by PhilJd** [comment]
Which python version is pip3 linked to? You mentioned installing 3.5 AND 3.6. Maybe you're trying to install the tensorflow version for python3.5 while pip3 links to python3.6

Also  32bit vs 64bit might be a problem, [this](http://stackoverflow.com/questions/28568070/filename-whl-is-not-supported-wheel-on-this-platform) stackoverflow post lists various causes for this error message.

**Comment by Redtile** [comment]
its linked to python 3.6 and its on 32 bit for both

**Comment by PhilJd** [comment]
The documentation says:

> TensorFlow supports only 64-bit Python 3.5 on Windows

So you need to install 64-bit python for tensorflow to work.

**Comment by Redtile** [comment]
ahh ok ill get that done, thanks allot for you're help :)

**Comment by PhilJd** [comment]
Did this work for you? If yes, please close this issue!

**Comment by gunan** [comment]
Looks like this was an issue on user side.
Closing issue.

**Comment by kartikeyasaxena1012** [comment]
Cant install tensorflow on my laptop
pip3 install --upgrade tensorflow-gpu
Collecting tensorflow-gpu
  Could not find a version that satisfies the requirement tensorflow-gpu (from versions: )
No matching distribution found for tensorflow-gpu

this is what it shows please help
