### ISSUE TITLE
TensorBoard develop build failed due to npm dead loop and typescript error

### ISSUE THREAD

**Issue by bravomikekilo** [tensorflow/tensorflow#8326]
### Environment info
Operating System: Ubuntu 16.10
npm 4.4.1
node.js v7.7.2

Installed version of CUDA and cuDNN:  CUDA 8.0, cuDNN 5.1
-rw-r--r-- 1 root root   558720 9月  15 07:02 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 9月  15 07:05 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 9月  15 07:05 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rw-r--r-- 1 root root   415432 9月  15 07:02 /usr/local/cuda/lib64/libcudart.so.8.0.44
-rw-r--r-- 1 root root   775162 9月  15 07:02 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 79337624 12月 12 18:46 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 79337624 12月 12 18:46 /usr/local/cuda/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 79337624 12月 12 18:46 /usr/local/cuda/lib64/libcudnn.so.5.1.5
-rw-r--r-- 1 root root 69756172 12月 12 18:46 /usr/local/cuda/lib64/libcudnn_static.a

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
f1ffbc548906e379d423633f76edc558be8284e7
2. The output of `bazel version`
Build label: 0.4.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Feb 1 18:54:21 2017 (1485975261)
Build timestamp: 1485975261
Build timestamp as int: 1485975261

### minimal reproducible example
get a fresh clone
cd tensorflow/tensorboard
`npm run prepare` 

and npm install some packages and goes into a dead loop without the bower and typings
  > tensorflow-vis@0.0.0 prepare /home/baomingkun/Res/tensorflow/tensorflow/tensorboard
  > npm install && bower install && typings install
  
  
  > tensorflow-vis@0.0.0 prepare /home/baomingkun/Res/tensorflow/tensorflow/tensorboard
  > npm install && bower install && typings install 
  
  
  > tensorflow-vis@0.0.0 prepare /home/baomingkun/Res/tensorflow/tensorflow/tensorboard
  > npm install && bower install && typings install
  
  
  > tensorflow-vis@0.0.0 prepare /home/baomingkun/Res/tensorflow/tensorflow/tensorboard
  > npm install && bower install && typings install

### What other attempted solutions have you tried?
I have moved global typings and typescript, but nothing works.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
If I kill the prepare after it goes into dead loop than use `bower install && typings install` 
everything looks fine. 
but  `gulp` fail due to some semantic errors
  typings/globals/webcomponents.js/index.d.ts(48,5): error TS2403: Subsequent variable declarations   must have the same type.  Variable 'shadowRoot' must be of type 'ShadowRoot', but here has  type'ShadowRootPolyfill'.
  typings/globals/webcomponents.js/index.d.ts(48,5): error TS2687: All declarations of 'shadowRoot' must have identical modifiers.
  typings/globals/webcomponents.js/index.d.ts(48,5): error TS2403: Subsequent variable declarations must have the same type.  Variable 'shadowRoot' must be of type 'ShadowRoot', but here has type 'ShadowRootPolyfill'.
  typings/globals/webcomponents.js/index.d.ts(48,5): error TS2687: All declarations of 'shadowRoot' must have identical modifiers.
  __lib.d.ts(7452,14): error TS2687: All declarations of 'shadowRoot' must have identical modifiers.
  [23:27:41] TypeScript: 2 semantic errors
  [23:27:41] TypeScript: 3 emit errors
  [23:27:41] TypeScript: emit failed
then the demo/index.html is just a blank page.

**Comment by bravomikekilo** [comment]
[webcomponents.js typescript binding issue at DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15064)

**Comment by bravomikekilo** [comment]
[webcomponents.js typescript binding issue at DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15064)

**Comment by aselle** [comment]
@dandelionmane, do you have any insights on this?

**Comment by jlazarow** [comment]
Any update to this? It seems like the TensorBoard development workflow (at least on recent checkouts) is not possible due to this.

**Comment by wannabesrevenge** [comment]
the `npm run prepare` issue is a result of npm 4.3. `npm install` will now run the prepare script, which runs install, which runs prepare... and so on. I am about to submit a PR for this.

**Comment by wannabesrevenge** [comment]
Here's a relevant NPM issue regarding `npm prepare` https://github.com/npm/npm/issues/15226

**Comment by dandelionmane** [comment]
@jart @chihuahua 
The fact that the open-source TensorBoard build is broken is a known issue and one that frustrates us a lot. I think on the master branch chihuahua put out some new instructions in development.md that solve some of this. We're hard at work on getting a bazel build working so we can leave all this gulp/npm stuff behind.

**Comment by jlazarow** [comment]
The development.md file is quite helpful. I'm not sure if I should open an issue for each thing I'm currently encountering in "master" (some might be because I have no experience with the npm/bower ecosystem) but:

1. The webcomponents.js typings introduced that "shadowRoot" issue that people are hitting even outside of TensorBoard. See the "FYI, this line" part at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10330/files/4a7781d7e31eb4b9d7b97ecc81c55bb630fd1ddc

Removing that line seemed to allow me to proceed further.

2. TypeScript does not like the use of "number|null" within vz_project/data.ts:97

Removing the "null" allowed me to proceed further.

3. The tf_storage component was updated at some point to have a "useLocalStorage" parameter on the get*/set* functions. However, not all of these methods use a default parameter for this. Therefore, storageTests.ts is now broken.

Ensuring this parameter is passed allowed me to proceed further.

4. The demo now loads partially but fails soon after because these scripts cannot be found (d3, lodash, etc). I figured these would be handled by bower, but I don't know why it's not placing those in some accessible place.

Furthermore, the "tf_imports" folder/dependency is not created and so many other tasks (gulp regenerate, bazel) all then fail at this point.

**Comment by jart** [comment]
I'm in the process of upgrading TypeScript in package.json to 2.2.1, which might help. But there's a lot going on here. As @dandelionmane mentioned, we're going to be deprecating the Gulp build soon.

**Comment by jlazarow** [comment]
tsify and gulp-typescript both use their own versions of typescript as well. These seem to be the packages causing most of the issues.

**Comment by drpngx** [comment]
So the upgrade to TypeScript `2.2.1` happened. Can we close this?

**Comment by dandelionmane** [comment]
@jart fixed this; tensorboard now uses bazel to build instead of gulp/npm!

Check it out here: https://github.com/tensorflow/tensorboard
