### ISSUE TITLE
transfer learning with TF hub

### ISSUE THREAD

**Issue by lincoln12833** [tensorflow/tensorflow#83279]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.8

### Custom code

No

### Current behavior?

If you use tensorflow_hub.KerasLayer(correct parmeters), in a squential model: it won't recognize it as an acceptable layer. 

### Standalone code to reproduce the issue

```shell
https://www.tensorflow.org/tutorials/images/transfer_learning_with_hub
```

### Relevant log output

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-7db51c8d2d71> in <cell line: 3>()
      1 IMAGE_SHAPE = (224, 224)
      2 
----> 3 classifier = tf.keras.Sequential([
      4     hub.KerasLayer(classifier_model, input_shape=IMAGE_SHAPE+(3,))
      5 ])

1 frames
/usr/local/lib/python3.10/dist-packages/keras/src/models/sequential.py in add(self, layer, rebuild)
     94                 layer = origin_layer
     95         if not isinstance(layer, Layer):
---> 96             raise ValueError(
     97                 "Only instances of `keras.Layer` can be "
     98                 f"added to a Sequential model. Received: {layer} "

ValueError: Only instances of `keras.Layer` can be added to a Sequential model. Received: <tensorflow_hub.keras_layer.KerasLayer object at 0x7aafb7ccd2a0> (of type <class 'tensorflow_hub.keras_layer.KerasLayer'>)
```

**Comment by tilakrayal** [comment]
@lincoln12833,
Hi, By default the colab notebook is using tensorflow v2.17 and v2.18 which contains keras3.0 which was causing the error. Could you please try to import keras2.0 with the below commands.

```python
!pip install tf-keras == 2.18.0

import tf_keras as keras
```

Also I have modified some steps and then the code was executed without error/fail. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/a437f436540f2e799c37102e2fe7904b/transfer_learning_with_hub.ipynb).
I have raised the PR in the Tensorflow/docs repo for the similar issue.
https://github.com/tensorflow/docs/pull/2344

Thank you!

**Comment by Edwinhei** [comment]
![image](https://github.com/user-attachments/assets/a93d2add-5c97-48f5-8bfc-5edcfead09da)
The same configuration is running in the background, but it neither outputs nor ends.

**Comment by lincoln12833** [comment]
I got that part working but I am getting the same error in this one after adding those lines https://github.com/lincoln12833/tensor_flow_hub_transfer_learning/blob/main/courses/udacity_intro_to_tensorflow_for_deep_learning/l06c01_tensorflow_hub_and_transfer_learning.ipynb @tilakrayal

**Comment by tilakrayal** [comment]
@lincoln12833,
In the code you are trying to import the keras as **import tf_keras as keras** and using tf.keras.sequential in the code. Could you try to change from layers.dense to keras.layers.dense and execute the code. In the above attached  gist, I have changed the tf.keras to keras, and try to execute the code.

From:
![image](https://github.com/user-attachments/assets/49b44cb4-9845-4624-a8a5-f954087419a8)


To:
![image](https://github.com/user-attachments/assets/13a478df-4190-4a35-9017-66ed1c8898fa)


Thank you!

**Comment by lincoln12833** [comment]
Thank you so much for all your help tilakrayal. This seemed to have fixed it.

**Comment by tilakrayal** [comment]
@lincoln12833,
Glad the issue was resolved. Could you please feel free to move this issue to closed status. Thank you!
