### ISSUE TITLE
conv2d_transpose cannot be used in network with variable batch size

### ISSUE THREAD

**Issue by alexatknit** [tensorflow/tensorflow#833]
I'm building a network that requires an approximate deconvolution using conv2d_transpose and I'm running into this error when constructing the network:

```
...
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 80, in conv2d_transpose
    output_shape_ = ops.convert_to_tensor(output_shape, name="output_shape")
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 530, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/constant_op.py", line 195, in _tensor_shape_tensor_conversion_function
    "Cannot convert a partially known TensorShape to a Tensor: %s" % s)
ValueError: Cannot convert a partially known TensorShape to a Tensor: (?, 40, 40, 32)
``` 

It appears that the operation doesn't support shape objects with none values as they cannot be converted to tensors. Is there a workaround? Or should I simply explicitly set my batch size for now?

edit: It appears that reshape has the same issue.

**Comment by josh11b** [comment]
For reshape, you can have one unknown dimension if you set it to -1.  For conv2d_transpose, I'm going to defer to Geoffrey.

**Comment by girving** [comment]
conv2d_transpose does need to know the exact shape, but that shape can be computed with tensorflow ops at runtime.  Presumably you have some variable whose first dimension is batch size, so you can do something like

    batch_size = tf.shape(something_or_other)[0]
    deconv_shape = tf.pack([batch_size, 40, 40, 32])
    conv2d_transpose(..., output_shape=deconv_shape, ...)

**Comment by alexatknit** [comment]
Awesome, that worked! Thanks!

**Comment by bsautermeister** [comment]
I tried to to it exactly the same way as described here. But Unfortunately, it returns a tensor with unknown dimensions:

`batch_size = tf.shape(something_or_other)[0]
deconv_shape = tf.pack([batch_size, 40, 40, 32])
conv2d_transpose(..., output_shape=deconv_shape, ...)`
Returns: A  tensor with shape (?, ?, ?, ?).

`conv2d_transpose(..., output_shape=[64, 40, 40. 32], ...)`
Returns: A  tensor with shape (64, 40, 40, 32).

So, as soon as i use two conv2d_transposed() operations with variable batch-size one after the other, it is not working for me.
Does anyone have the same issues having a unknown tensor-shape. Is is there a way to set the tensor-shape manually?

**Comment by girving** [comment]
@bsautermeister Yes, that's expected behavior.  We currently don't do constant folding through partially known tensors such as the `tf.pack` here.  Hopefully that will be fixed at some point in the future.

**Comment by amolchanov86** [comment]
The proposed solution still wouldn't work in case of stacking `conv2d_transpose` filters because, in the example, the static shape is calculated from the input tensor, but the previous filter would produce the dynamic shape, i.e. `(?,?,?,?)` which should brake at the point of initializing weights since they can take static shapes with known values only (the channel dimension would be unknown). The only fix would be to fix shapes produced by the `conv2d_transpose` filter. At least the channel dimension should be known no matter what.

**Comment by girving** [comment]
@amolchanov86 The proposed solution works fine for stacked filters, since it has no dependence on static shapes.  If you want assistance getting your model working, please ask questions on StackOverflow.

**Comment by pumplerod** [comment]
I find this works well if you're providing a tensor that has a shape, however I'm trying to pass in the batch_size in the feed_dict which works well for some operations, however will not work for generating conv2d_transpose layers...

This works...
```
batch_size = tf.placeholder(tf.float32, shape=(1))
Z = tf.random_uniform([tf.to_int32(batch_size[0]),n_z],-1,1,dtype=tf.float32)
```

however using the batch_size[0] in the output_shape for conv2d_transpose generates an error, where using the tf.shape(X)[0] solution proposed above seems to work.  I'm not sure why.

**Comment by sanchit-agrawal** [comment]
**Workaround:**
I had this issue when I wanted to use batch_norm right after a conv2d_transpose. The conv2d_transpose loses all shape information about the output tensor. batch_norm requires the number of channels to be statically known. I found a workaround by using tf.reshape() right after the conv2d_transpose. This regains the static shape information.

**Comment by maryam089** [comment]
I'm using Python3.6 with TensorFlow 1.5.1 and my issue is
[Report Error]ValueError: Incompatible shapes between op input and calculated input gradient. conv2d_transpose
any idea how to solve it?
