### ISSUE TITLE
[TensorBoard] load data from relative path with the projector plugin

### ISSUE THREAD

**Issue by lspvic** [tensorflow/tensorflow#8342]
This is a  problem similar with issue #7382 but it has been closed.

@dandelionmane 
Another place that still has the similar problem in #7382 is the request of project plugin data in Embeddings panel, e.g.  /data/plugin/projector/runs still requests in a absolute path.
I found the code  [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/components/tf_tensorboard/tf-tensorboard.html#L134) , there is a leading slash for the `route-prefix` property in `vz-projector-dashboard`.
If that is correct, I will submit a PR. Thanks!

Another question is when will the tensorboard be recompiled. As now in version 1.0 these features are not included.

**Comment by dandelionmane** [comment]
I migrated this to the new TensorBoard repository. https://github.com/tensorflow/tensorboard/issues/37
