### ISSUE TITLE
The inputs of dynamic_rnn must be 3-D tensor?

### ISSUE THREAD

**Issue by NiHaoUCAS** [tensorflow/tensorflow#8343]
hi,
    I want to use _dynamic_rnn_ to train my convLSTM, the original data should be videos with dimension: [batch_size, max_time_step, high, width,channel]. But i failed to feed the data to dynamic_rnn.
I get such error:
`ValueError: Dimension must be 5 but is 3 for 'transpose' (op: 'Transpose') with input shapes: [16,?,11,40,1], [3].`
what should i do to use dynamic rnn?
version: tf 1.0

**Comment by MicaelCarvalho** [comment]
If this isn't a bug, it will be better/faster answered on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) — the correct place to ask for help.

If this is a bug, please follow guidelines for reporting problems. When you click on "New issue" there is a template to be filled. It is very hard to reproduce your problem and check what's wrong if you don't provide the required information. For example, you did not provide a sample code for reproducing the problem. ;-)

Looking just at your error message, I would say your input vector is wrongly formatted. Try printing it to see what's going on.

**Comment by concretevitamin** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by maayank** [comment]
I spent much time debugging this issue in my own code and googling found this (NiHaoUCAS, this will possibly help you as well):
http://stackoverflow.com/questions/42513613/tensorflow-dynamic-rnn-regressor-valueerror-dimension-mismatch

Further search in the github repository found this issue. It's obviously a pain point for users.

**Comment by ebrevdo** [comment]
I believe we have a fix in the works, can push it tomorrow.

**Comment by NiHaoUCAS** [comment]
thanks a lot @ebrevdo

**Comment by maayank** [comment]
Many thanks @ebrevdo et al 👍

**Comment by concretevitamin** [comment]
@ebrevdo is this pushed?  Could you close the issue when the fix is in?  Thanks.

**Comment by 1973Blunt** [comment]
hi,
Is this fixed? 
When I run:
```
x = tf.placeholder(tf.float32, [1, 100, 9, 161])
cell = rnn.BasicLSTMCell(1024)
output, state = tf.nn.dynamic_rnn(cell, x, dtype=tf.float32)
```
I get such error:
```
ValueError: linear is expecting 2D arguments: [TensorShape([Dimension(1), Dimension(9), Dimension(161)]), TensorShape([Dimension(1), Dimension(1024)])]
```
version: tf 1.4.1
