### ISSUE TITLE
How to Add Adam optimizer metrics to Tensorboard?

### ISSUE THREAD

**Issue by Prakashvanapalli** [tensorflow/tensorflow#8345]
When I trained model for several epochs and want to retrain it again for more epochs. How would Adam optimizer work. will it initialize the time from t =0 or will it save the last time step?  

a) The documentation in tensorflow shows the following calculations. Is there a away I can add these metrics to tensorboard. 

    t <- t + 1
    lr_t <- learning_rate * sqrt(1 - beta2^t) / (1 - beta1^t)

    m_t <- beta1 * m_{t-1} + (1 - beta1) * g
    v_t <- beta2 * v_{t-1} + (1 - beta2) * g * g
    variable <- variable - lr_t * m_t / (sqrt(v_t) + epsilon)

I know this question need to be asked in stackoverflow . but there are no answers for a few questions since a long time [question1](http://stackoverflow.com/questions/36990476/getting-the-current-learning-rate-from-a-tf-train-adamoptimizer) and [question2](http://stackoverflow.com/questions/40752053/how-to-add-learning-rate-to-summaries).

I am actually getting a problem with error rate when re-training the model from the last checkpoint and I was not sure what exactly is happening with Adam optimizer in this case ?

**Comment by concretevitamin** [comment]
To monitor those values in TensorBoard, you can use `tf.summary.scalar()`.  Give it a try?

**Comment by Prakashvanapalli** [comment]
No it is not working .

**Comment by concretevitamin** [comment]
Could you extract a minimum runnable code snippet to demonstrate the issue?  One quick thing to check is to see if there are any event files on-disk (those are used to render values in Tensorboard).

**Comment by asimshankar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
