### ISSUE TITLE
how to avoid generating large metagraph?

### ISSUE THREAD

**Issue by bluekingsong** [tensorflow/tensorflow#8351]
### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

x_nparray = $VERY_LARGE_NP_ARRAY(bigger than 2G)

x = tf.Variable(init_value=x_nparray)

saver=tf.Saver()
with tf.Session() as sess:
  saver.save(sess, 'path/to/save')

that would generate very large metagraph binary file, when i try to restore the model, it would failed because of the meta graph file size exceed  the protobuf limit size.

I cannot reduce the size of x_nparray, because it's generated by other training system like caffe. 

### What other attempted solutions have you tried?
set bigger limit byte of protobuf, however, the x_nparray is bigger than 3G, while the largest limit i can set is 2G.

**Comment by concretevitamin** [comment]
By default, calling `tf.Saver()` will grab all variables currently in the graph.  Can you try to manipulate the [`var_list` argument](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/saver.py#L947) to exclude this large variable?

**Comment by bluekingsong** [comment]
i solve this problem, by an unusual way.  the  large variable is what i must keep for online inference.  however, i find it is interesting that the meta graph  save duplicate graphs in proto file.  specifically,  it has "graph_def" proto and "serving_graph" proto,  and i found remove serving_graph won't affect my online inference. also, i found the constant( such as numpy array,  python scalar variables ) used by the graph building process will saved in the meta graph as const tensor, this is the reason which make my meta graph proto very big.  i use tf.assign to inject my numpy array to the tensor variables and then remove the tf.assign op(with the constant tensor in meta graph) from the graph when i export the model ( i don't need the assign op in inference process ).   in this way, i reduce my meta graph to very small.

**Comment by concretevitamin** [comment]
@bluekingsong glad to know you've found a workaround. Just for the record: indeed, the _actual values_ of constant Tensors are (unfortunately?) embedded in GraphDefs, whereas Variables don't have this issue.
