### ISSUE TITLE
GPU memory problem when using tensorflow 1.0.0 on TITAN X (Pascal) 

### ISSUE THREAD

**Issue by stephenjia** [tensorflow/tensorflow#8352]
### Environment info
Operating System: Fedora 25
cuda 8.0 and cuDNN 5.1
TITAN X (Pascal) and Driver Version: 375.26

I installed tensorflow 1.0.0 using pip install under anaconda
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.1-cp27-none-linux_x86_64.whl

I have a problem when using tensorflow on TITAN X (Pascal) . I am able to ran my code on other type of GPUs. I also tried running theano and matconvnet on the same GPU but there is no problem.

I tried several ways to check it.
1. if I directly run sess = tf.Session(), it gets stuck there.

W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:01:00.0
Total memory: 11.90GiB
Free memory: 10.97GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:01:00.0)
Killed

2. I also tried to set allow_growth=True and it is able to run tf.Session.
gpu_options= tf.GPUOptions(allow_growth=True)
tf_config = tf.ConfigProto(allow_soft_placement=True, log_device_placement=True, gpu_options=gpu_options)
sess = tf.Session(config=tf_config)

W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:01:00.0
Total memory: 11.90GiB
Free memory: 10.97GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:01:00.0)
Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: TITAN X (Pascal), pci bus id: 0000:01:00.0
I tensorflow/core/common_runtime/direct_session.cc:257] Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: TITAN X (Pascal), pci bus id: 0000:01:00.0

I check the GPU memory being used, it is 151MB.

3. I also tried to allocate different amount of GPU memory in the following way and it crashed.
tf_config = tf.ConfigProto()
tf_config.gpu_options.per_process_gpu_memory_fraction = 0.1
sess = tf.Session(config=tf_config)

W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:910] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:01:00.0
Total memory: 11.90GiB
Free memory: 10.97GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:01:00.0)
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
Aborted (core dumped)

Can anyone help me on this? Thanks a lot.

**Comment by MicaelCarvalho** [comment]
It seems you either have TF installation problems or driver issues. I have a similar setup (X Pascal + Debian) running without problems.

Could you try installing the package directly from pip? With `pip3 install --upgrade tensorflow-gpu` for python3 or `pip install --upgrade tensorflow-gpu` for python2.7. Also, run `nvidia-smi` to see if the driver was installed correctly (possibly it can work with a broken driver installation, but this will detect at least the basic problems).

**Comment by stephenjia** [comment]
Thank you for your reply. I run nvidia-smi and here is the output.
Mon Mar 13 14:42:23 2017       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.26                 Driver Version: 375.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    On   | 0000:01:00.0      On |                  N/A |
| 36%   57C    P2    57W / 250W |    853MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0      9695    C   .../visics/rdegeest/torch/install/bin/luajit   427MiB |
|    0     16304    G   /usr/bin/krunner                                 2MiB |
|    0     16305    G   /usr/bin/plasmashell                            59MiB |
|    0     16358    G   /usr/bin/korgac                                  3MiB |
|    0     16633    G   /usr/bin/akonadi_archivemail_agent               3MiB |
|    0     16643    G   /usr/bin/akonadi_mailfilter_agent                3MiB |
|    0     16651    G   /usr/bin/akonadi_newmailnotifier_agent           3MiB |
|    0     16652    G   /usr/bin/akonadi_notes_agent                     3MiB |
|    0     16656    G   /usr/bin/akonadi_sendlater_agent                 3MiB |
|    0     16930    G   ...nnectMore/Enabled/PreferHtmlOverPlugins/E   210MiB |
|    0     24746    G   /usr/libexec/Xorg                              131MiB |
+-----------------------------------------------------------------------------+
With the current tensorflow installation, I do not have problem when running it on machines with other type of GPUs. I feel very confused about this.

**Comment by MicaelCarvalho** [comment]
I found these 3 issues with similar messages: #3470, #2416, #1658 (two memory-related and one of thread limits). Could you try checking their approaches, to see if it works for you? Particularly the last, could be easily solvable if thread limit is the problem.

**Comment by stephenjia** [comment]
Thank you for your help. I checked the three issues. I think mine is similar to #2416. But I did not find solution there.

**Comment by stephenjia** [comment]
Hi @MicaelCarvalho , I find the reason. Actually, it is because of our administrator set a limit to virtual memory. When I increase the limit value or set it to unlimited, it works.

**Comment by starFalll** [comment]
Hi @stephenjia ,I have the same problem with you.But I don not know how many virtury memory to increase,Will virtual memory be twice the size of memory?Becaues My Linux partition spaces are not enough，how to expand swap partition in Ubuntu 16.04 dual-boot system(Windows10 &Ubuntu16.04)?
Can you help me on these? Thanks a lot.
