### ISSUE TITLE
Error while running TextClassification in examples

### ISSUE THREAD

**Issue by vinu87** [tensorflow/tensorflow#8353]
Getting error
module 'tensorflow.contrib.layers' has no attribute 'bow_encoder'
if running bag of words model

**Comment by MicaelCarvalho** [comment]
This function is inside `tensorflow.contrib.layers.python.layers`.

You should run:
```
from tensorflow.contrib.layers.python.layers import encoders
encoders.bow_encoder
```

These kind of questions are better addressed at [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow), the GitHub is used for bug reporting mainly. And when bug reporting, please follow guidelines for your post — filling all the required fields when opening a new Issue.

**Comment by vinu87** [comment]
Raised it here since it is a bug in the code . code does not have the import correctly
