### ISSUE TITLE
tensorflow's textsum model has version compatibile issue

### ISSUE THREAD

**Issue by YiyuJia** [tensorflow/tensorflow#8355]
Hi there,

I installed tensorflow and tried its textsum model. Unfortunately, I hit lots of module has not attribute issues. I used release version it does not compatible with textsum model in github master branch. I build tensorflow from source from master branch. But, there are still lots of version compatible issues. 

Anyone here tried this model before? I need to find a release of tesnsorflow and textsum model and they are compatible. 

Also, does this model work with tensorflow CPU (not GPU) edition?

thanks in advance!

Yiyu

**Comment by concretevitamin** [comment]
/cc @panyx0718 

@YiyuJia: did you try using TensorFlow 1.0 with the master branch version of textsum?

**Comment by YiyuJia** [comment]
yes. I tried. 
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp35-cp35m-linux_x86_64.whl


I also tried master branch version of tesnsorflow. 

I tried upgrade script too. https://www.tensorflow.org/install/migration

**Comment by girving** [comment]
This is a models issue, not a tensorflow issue.
