### ISSUE TITLE
How do I call MoonPay-Official Customer Support?

### ISSUE THREAD

**Issue by jumera6789** [tensorflow/tensorflow#83595]
How do I contact MoonPay Support?
When you call on Moonpay support at ⭐☎️ +1-((850))-468-9565, we typically reply in under 1 minute. Get connected with us via ⭐☎️ +1-((850))-468-9565 for Moonpay Wallet - General Information, how to Set Up Your Moonpay.com App 2FA, or how to reset 2FA.

**Comment by tilakrayal** [comment]
**Closing this issue as SPAM**
