### ISSUE TITLE
Memory Allocation at each call to Frozen Graph?

### ISSUE THREAD

**Issue by richfwebb** [tensorflow/tensorflow#8362]
Operating System: Linux, CPU
TF: 0.11.0

It looks like a memory allocation is occurring during each call to my frozen graph.
I suspect I'm using the code incorrectly rather than this is a bug.
Please delete if this does not belong here. 
I posted on [StackOverflow](http://stackoverflow.com/questions/42769464/bad-memory-allocation-when-using-frozen-graph).

-------

My model was running too slow doing inference.
I froze the graph and converted variables to constants to improve the speed. 

Normally I load the graph and weights (which runs OK):
```
with tf.Graph().as_default(), tf.Session() as session:
	...
	saver.restore(session, ckpt_path)
	for i in range(5):
	    result = session.run(...)
```

However, when I load the frozen graph:	
```
# Save the graph

# output_node_names - equivalent to the results that are requested in the session.run() calls
output_node_names = [...] 
saver = tf.train.import_meta_graph(ckpt + '.meta')
graph = tf.get_default_graph()
input_graph_def = graph.as_graph_def()

with tf.Session() as sess:
    saver.restore(sess, ckpt)
    output_graph_def = graph_util.convert_variables_to_constants(
        sess, input_graph_def, output_node_names) 

     with tf.gfile.GFile(output_graph, "wb") as f:
         f.write(output_graph_def.SerializeToString())


# Load the graph

def load_graph(filename):
	with tf.gfile.GFile(filename, "rb") as f:
	       graph_def = tf.GraphDef()
	       graph_def.ParseFromString(f.read())

	 with tf.Graph().as_default() as graph:
	        tf.import_graph_def(graph_def, input_map=None, 
	        	return_elements=None, name="prefix", op_dict=None, 
                        producer_op_list=None)
	return graph 

graph = load_graph("model.pb")
session = tf.Session(graph=graph)
	
for i in range(5):
	result = session.run(...)
```

After loading the full graph, inference takes ~1 second.
After loading the frozen graph, inference takes ~4 seconds.
So it seems like something may not be loaded entirely in my frozen graph?
The first call to session.run() successfully produces a result (although very slow), but **the second call to run() throws an error**.

**`W tensorflow/core/framework/op_kernel.cc:940] Resource exhausted: OOM when allocating tensor with shape[300,100000]`**

Since the graph internally has an embedding table (this is not what is being returned by session.run()), it seems this is what is being re-allocated:
	```embedding = tf.get_variable("embedding", [300, 100000])```

Also the error message printed 3 times, hopefully that means 3 allocation attempts, and not 3 instances being allocated? 
But why is this allocation on every call to session.run()?

Edit:
@MicaelCarvalho 
Here is the format of my input for Session.run():
```
x = [0.0]
x_placeholder = graph.get_tensor_by_name('prefix/x_placeholder:0')
y = graph.get_tensor_by_name('prefix/y:0')
feed_dict = {x_placeholder: x}
to_return = [y]
result = sess.run(to_return, feed_dict=feed_dict)
```

**Comment by MicaelCarvalho** [comment]
Check this out:
```
def test():
  a = 1
  with a as b:
    return b

test()
```

The `with` statement closes/destroys the object after using it. And you are returning the destroyed object, just like the example I gave you. By itself your function is already a bug, but please also provide what parameters you are giving to `session.run(...)`.

**Comment by richfwebb** [comment]
@MicaelCarvalho  I understand your point; but it actually works. The code below successfully prints the operations from my loaded graph outside of the "with" block. 
```
with tf.Graph().as_default() as graph:
     tf.import_graph(...)

for op in graph.get_operations():
        print(op)

return graph
```

**Comment by MicaelCarvalho** [comment]
I would still change that:
```
def load_graph(filename):
  with tf.gfile.GFile(...):
    (...)
  graph = tf.Graph()
  with graph.as_default():
    tf.import_graph_def(...)
  return graph
```

Coming back to the issue: Who built the graph? It is possible some nodes inside the graph, when executed, create new operations/nodes. Put this function inside your source:
```
def print_num_params(graph):
  vvars = 0
  for v in tf.global_variables():
    vvars += np.prod(v.get_shape().as_list())
  total_parameters = 0
  for variable in tf.trainable_variables():
      shape = variable.get_shape()
      variable_parametes = 1
      for dim in shape:
          variable_parametes *= dim.value
      total_parameters += variable_parametes
  log_message('Total params = %i' % (total_parameters), SYSTEM)
  log_message('Total vars = %i' % (vvars), SYSTEM)
  log_message('Total ops = %i' % (len(graph.get_operations())), SYSTEM)
```

And before each call to `sess.run`, run this code and report back the results:
`print_num_params(graph)`

**Comment by richfwebb** [comment]
It prints the safe after each session.run() call.
```
Total params = 0
Total vars = 0
Total ops = 10242
```

**Comment by MicaelCarvalho** [comment]
Before your `for i in range(5):`, add `with graph.as_default():`, and report back if anything changed.

====

Does this number change between subsequent runs of `session.run`? I.e. in the 5 times the `for` calls `session.run`, does the value of "Total ops" change? If yes, your graph is increasing at each iteration and that's a graph construction problem.

If no, please put the same debug code on your original architecture and print its parameters to check if they match.

**Comment by richfwebb** [comment]
The printout is the same for each iteration of session.run(), and the same while using graph.as_default().

**Comment by aselle** [comment]
Since this doesn't seem to be a bug, closing here. I added a comment on stackoverflow.

**Comment by MicaelCarvalho** [comment]
I'm not fully convinced we have enough information to assume this isn't a bug... The behavior is rather strange and if the data @richfwebb reported back are correct, I am clueless as well. Maybe someone could point other possible causes that would create these "symptoms", other than the things I already investigated with him. :-)
