### ISSUE TITLE
Documentation formatting broken

### ISSUE THREAD

**Issue by BlackHC** [tensorflow/tensorflow#8364]
See https://www.tensorflow.org/api_docs/python/tf/contrib/copy_graph/copy_op_to_graph (source code formatting leaks into general text)
or https://www.tensorflow.org/api_docs/python/tf/contrib/graph_editor/copy (Returns: and Raises: get folded into parameters).

Either the doc generator needs to understand python doc comments better or the doc comments need to be updated to work better with markdown (extra newlines etc). What do you think?

Thanks,
 Andreas

**Comment by drpngx** [comment]
@josh11b @martinwicke for docs
