### ISSUE TITLE
 the files are available but inspection result No event files found within logdir

### ISSUE THREAD

**Issue by ikibozu** [tensorflow/tensorflow#8367]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/README.md#my-tensorboard-isnt-showing-any-data-whats-wrong

### Environment info
Operating System: mac
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### What other attempted solutions have you tried?
inspecting directory

### Logs or other output that would be helpful

(mlp) earthhouse86:cifar10 ikibozu$ tensorboard --inspect --logdir==$OUTPUT_DIR 0
======================================================================
Processing event files... (this can take a few minutes)
======================================================================

No event files found within logdir =/Users/ikibozu/mlpractical/notebooks/cw4/result
(mlp) earthhouse86:cifar10 ikibozu$ find $OUTPUT_DIR | grep tfevent
/Users/ikibozu/mlpractical/notebooks/cw4/result/C10_10_tf.nn.relu_2017-03-13_14-47-18/train-summaries/events.out.tfevents.1489416439.earthhouse86.hw147.homewurk.nl
/Users/ikibozu/mlpractical/notebooks/cw4/result/C10_10_tf.nn.relu_2017-03-13_14-47-18/valid-summaries/events.out.tfevents.1489416669.earthhouse86.hw147.homewurk.nl

**Comment by MicaelCarvalho** [comment]
Your logs are inside another folder. You're passing `/Users/ikibozu/mlpractical/notebooks/cw4/result` as path, but the files are inside `/Users/ikibozu/mlpractical/notebooks/cw4/result/C10_10_tf.nn.relu_2017-03-13_14-47-18/train-summaries/`.

And next time, please fill the fields of the issue template. ;-)

**Comment by concretevitamin** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
