### ISSUE TITLE
Reuse some parameters of a Variable

### ISSUE THREAD

**Issue by jmoraleda** [tensorflow/tensorflow#8368]
I know how to reuse complete variables Tensorflow in two different operations as explained in the documentation: [https://www.tensorflow.org/programmers_guide/variable_scope]

But, is it possible to reuse parameters in more complex ways? In particular, is it possible to specify that two variables of different shapes share some parameters in common? 

A small example of what I am trying to do: I would like to have a model with 25 parameters. I would like to use these parameters in three variables X, Y, and Z so that X uses all parameters in a 5x5 tensor:
X = 
w11, w12, ... , w15
w21, w22, ... , w25
...
w51, w52, ... , w55

while Y uses 9 of the parameters in a 3x3 tensor, for example the middle 3x3 block of X. That is:
Y = 
w22, w23, w24
w32, w33, w34
w42, w43, w44

while Z uses the same nine weights as Y and also in a 3x3 tensor, but transposed with respect to Y, that is:
Z =
w22, w32, w42
w23, w33, w43
w24, w34, w44

If this is not possible, are there plans in the Tensorflow development community to support this capability?

**Comment by asimshankar** [comment]
This question is probably better asked on [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) as we try to keep the Github issues focused on bugs and feature requests.

**Comment by jmoraleda** [comment]
Thank you. I just reposted in stackoverflow (https://stackoverflow.com/questions/42797103/how-to-reuse-some-parameters-of-a-variable-in-tensorflow). I posted here before thinking that of it as a feature request.
