### ISSUE TITLE
Add argument axis in tf.TensorArray method concat()?

### ISSUE THREAD

**Issue by gyang274** [tensorflow/tensorflow#8369]
Hi, TF development team,

Would it possible to add an argument axis in tf.TensorArray method concat(), defined in file tensorflow/tensorflow/python/ops/tensor_array_ops.py?

The reason is that there could be use cases when concat on the last axis make sense. Of course, the requirement would also need to be changed to 

"""
All of the values must have been written, their ranks must match, and
    and their shapes must all match for all dimensions except the **dimension specified as axis**.
"""

BTW, or, would tf.concat() accept tf.TensorArray as input? - I tried, but didn't find a way.

Thanks.

**Comment by shoyer** [comment]
An integrated axis argument might make sense (also for `.stack()`), but one simple work around is to use `TensorArray.stack` and then concatenate along the desired axis.

**Comment by asimshankar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by gyang274** [comment]
Thank you, @shoyer, @asimshankar and @concretevitamin ! I am ok with the workaround method.

Although an integrated axis argument is preferred, and make sense?

BTW, how much efficiency gain would be for an integrated axis (if implemented) compared to the work around method (stack then concatenate)?

Thank you.

**Comment by shoyer** [comment]
The cost here is one extra copy of the data, which is usually negligible (though it depends on the application).

**Comment by gyang274** [comment]
Ok, I see. Thank you, @shoyer !

**Comment by tridemax** [comment]
@shoyer, could you please provide an example of this workaround? It is not clear for me how to perform `tf.concat()` on a single stacked tensor.

To be precise, I've tried:
> probs = output_ta.stack()  # (num_slices, D1, D2, D3)
> probs = tf.concat((probs,), axis=2)  # still (num_slices, D1, D2, D3)

But I need the output of `tf.concat()` to be `(D1, D2, D3)`, concatenated by axis D2.

**Comment by shoyer** [comment]
I think I meant `tf.stack`, not `tf.concat`, e.g., `tf.stack(probs, axis=2)`

**Comment by tridemax** [comment]
@shoyer probably I don't understand something about how this works. =)

`TensorArray.stack()` will return values stacked along new zero dimension. `tf.stack()` over its output makes no sense for me as `tf.stack(probs)` is complaining about `Expected list for 'values' argument to 'pack' Op`. So I'm a bit lost.

I've solved that case by doing `tf.transpose()` inside the body which fills `TensorArray` and then transpose it back after `TensorArray.concat()`. But this seems to be a bit off as we introduce another memory copy for back transpose.

**Comment by shoyer** [comment]
Okay, I forgot stack needs a sequence, not a Tensor. So nevermind, transpose is your best bet.

**Comment by scarere** [comment]
I would also agree that  adding and axis argument to TensorArray.stack() would be useful. Current workaround  is to just transpose the first dimension to the back

**Comment by mbchang** [comment]
I am facing the same issue myself. Are there plans to add the axis argument? @asimshankar [asimshankar](https://github.com/asimshankar)

**Comment by uzi0espil** [comment]
I think this is a needed feature, stacking and transposing makes the code ugly and hard to read, where you can just say `concat(axis=1)`.
