### ISSUE TITLE
Problem with missing kernel registration in contrib/makefile build

### ISSUE THREAD

**Issue by tokoduck** [tensorflow/tensorflow#8371]
## Problem with missing kernel registration in contrib/makefile build

When reading a graph (through saved_model) I get the error message:

Status: Invalid argument: No OpKernel was registered to support Op 'TruncatedNormal' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

when trying to link the application using the tensorflow-core library generated in tensorflow/contrib/makefile

When using bazel, the same application runs without errors.

I have verified that the file "tensorflow/core/ops/random_ops.cc" containing the operation is already present in "tf_op_files.txt".

The library is linked with -all_load option.

### Environment info
The tensorflow version used is branch r1.0 on macOS 10.12.3 (no CUDA support). Hash e895d5ca395c2362df4f5c8f08b68501b41f8a98
Bazel Version is 0.4.4

**Comment by aselle** [comment]
Did you possibly produce the saved model with a different version of tensorflow as you are trying to run it?
@petewarden, do you have any makefile tips?

**Comment by a54** [comment]
2017-03-31 18:22:40: E /Users/a54/tf_files/projects/tensorswift-ios/tensorswift/tensorflow_utils.mm:152] Could not create TensorFlow Graph: Invalid argument: No OpKernel was registered to support Op 'TruncatedNormal' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: truncated_normal_3/TruncatedNormal = TruncatedNormal[T=DT_INT32, dtype=DT_FLOAT, seed=0, seed2=0](truncated_normal_3/shape)]]
2017-03-31 18:22:40: F /Users/a54/tf_files/projects/tensorswift-ios/tensorswift/TensorBridge.mm:75] Couldn't load model: Invalid argument: No OpKernel was registered to support Op 'TruncatedNormal' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: truncated_normal_3/TruncatedNormal = TruncatedNormal[T=DT_INT32, dtype=DT_FLOAT, seed=0, seed2=0](truncated_normal_3/shape)]]
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.

**Comment by StarRain-L** [comment]
@a54 Excuse me, could you tell me your problem solved?I met a similar problem. Thank you
![snip20170613_6](https://user-images.githubusercontent.com/8908244/27210034-30192b64-5282-11e7-95b2-d456da5357b2.png)

**Comment by martinwicke** [comment]
@StarRain-L: Only the float kernel is registered for Maximum, you are creating a int32 version. 

@tokoduck: Is this the full error message? 

@petewarden, would this be expected given the makefile build has a restricted set of kernels?

**Comment by petewarden** [comment]
This is expected, but it should be possible to override this by defining the __ANDROID_TYPES_FULL__ macro:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cwise_ops_common.h#L476

**Comment by StarRain-L** [comment]
@petewarden thanks for your comment again. I tried your example. rebuild ios script. but not worked. Attach a screenshot, and write wrong?
![snip20170617_1](https://user-images.githubusercontent.com/8908244/27249358-4010bd9c-5346-11e7-9ba7-75e13398fe52.png)

**Comment by StarRain-L** [comment]
@martinwicke @tokoduck   this is the full error message.I am doing the inference . I just use the model file saved by python .See a lot of issues, and try many methods,but not worked.

**Comment by tokoduck** [comment]
@martinwicke yes, that was the full error message

@StarRain-L from my knowledge, it is not resolved, but I have not checked the newer releases 1.1 and 1.2 yet.

As a work around, I got my program working when linking with the dynamic library, that can be created using bazel. When linking the same program with the static library, it fails.

**Comment by StarRain-L** [comment]
@tokoduck  I'm in iOS, and you?Your problem solved?

**Comment by tokoduck** [comment]
hi,

no, I am on MacOS (and ubuntu). So I have the workaround to produce a
dynamic library using bazel, linking with this library works, but linking
with the static library from the makefile project produces the error
message.

**Comment by StarRain-L** [comment]
My problem has been solved temporarily, thank you for your reply!!!!!!This is my reference information.
https://github.com/tensorflow/tensorflow/search?l=C%2B%2B&q=TruncatedNormal&type=&utf8=✓

**Comment by petewarden** [comment]
Since the makefile build is primarily intended for mobile use cases, and there's a workaround using the bazel version here instead, closing this bug. Please reopen with more information if this is incorrect.
