### ISSUE TITLE
How to visualize local dataset  on TensorBoard ?

### ISSUE THREAD

**Issue by Shahin-01** [tensorflow/tensorflow#8374]
Hello, I would like to know how we can visualize dataset on TensorBoard locally. I have Wine dataset taken from UCI Machine Learning repository and wonder what procedure I should follow to display on TensorBoard. Unfortunately I could not find about this on google. Could you help me with this, please ?

**Comment by MicaelCarvalho** [comment]
Your question can be better addressed on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). The GitHub "Issues" section is mainly for bug reporting and feature requests.

**Comment by Shahin-01** [comment]
I have asked there, but unfortunately no any answer came.The link is here:

http://stackoverflow.com/questions/42774670/visualizing-dataset-on-tensorboard

**Comment by MicaelCarvalho** [comment]
I believe you're looking for [tf.summary.image](https://www.tensorflow.org/api_docs/python/tf/summary/image). If you need examples, you can look for `tf.image_summary` (the old, deprecated version of this function), like these: [StackOverflow 1](http://stackoverflow.com/questions/38543850/tensorflow-how-to-display-custom-images-in-tensorboard-e-g-matplotlib-plots), [StackOverflow 2](http://stackoverflow.com/questions/34696845/how-to-see-multiple-images-through-tf-image-summary). ;-)

**Comment by Shahin-01** [comment]
Thank you for your help! @MicaelCarvalho
