### ISSUE TITLE
Tensorflow works, but cannot import tensorflow.python

### ISSUE THREAD

**Issue by jiexunsee** [tensorflow/tensorflow#8380]
Operating System: Ubuntu 16.04
Tensorflow version: tensorflow-gpu 1.0.1 on python3.6

---------------------------------------------------------
jiexun@jiexun-XPS-15-9560:~/Desktop$ python3
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
>>> tf.__version__
'1.0.1'
>>> import tensorflow.python
>>> import tensorflow.python as py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'python'
>>> 
---

I also tested importing the other tensorflow folders, with the below results:
>>> import tensorflow.contrib as con
>>> import tensorflow.core as core
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'tensorflow' has no attribute 'core'
>>> import tensorflow.examples as examples
>>> import tensorflow.include as include
>>> import tensorflow.models as models
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow.models'
>>> import tensorflow.tensorboard as tb
>>> import tensorflow.tools as tools
>>> 

For me, it seems like I can't import tensorflow.core, tensorflow.models, and tensorflow.python. Tensorflow.python in particular is the module that I am trying to use. 

Any idea why this is happening? I may be missing something obvious.

Thanks so much for the help!

**Comment by asimshankar** [comment]
There is no `tensorflow.python` module, the directory structure in the source tree may not map to the module names in the installed version. The set of all symbols/modules etc. can be found in the [Python API documentation](https://www.tensorflow.org/api_docs/python/)

Hope that helps.

**Comment by jiexunsee** [comment]
Hi, I am trying to use the [functional_ops](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/functional_ops.py) function, which is found under tensorflow/python. In this case, how do I import this function?

Thanks a lot for the reply.

**Comment by jiexunsee** [comment]
I am able to import when using `from tensorflow.python.ops import functional_ops as fn_ops` instead of `import tensorflow.python.ops.functional_ops as fn_ops`

Not very sure why, but it works

**Comment by sapphiresinha** [comment]
I am to able to import and use it import when I am using the updated version 1.13.0-rc2 and do the following: 
import tensorflow as tf
tf.python_io.control_flow_ops = tf    instead of tensorflow.python.control_flow_ops = tf   

# Using TensorFlow 1.0.0; use tf.python_io in later versions
