### ISSUE TITLE
_pywrap_tensorflow_internal.so: ELF file OS ABI invalid

### ISSUE THREAD

**Issue by caoshiwei** [tensorflow/tensorflow#8384]
improt tensorflow as tf
Errorinfo:
 imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: $PATH/tensorflow/python/_pywrap_tensorflow_internal.so: ELF file OS ABI invalid

there is _pywrap_tensorflow_internal.so in path. how can i solve this “ELF file OS ABI invalid”
install with pip
tensorflow version：https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.1-cp27-none-linux_x86_64.whl

OS info：Linux NAME #1 SMP TIME x86_64 x86_64 x86_64 GNU/Linux

file _pywrap_tensorflow_internal.so： _pywrap_tensorflow.so: ELF 64-bit LSB shared object, AMD x86-64, version 1 (GNU/Linux), not stripped

### Environment info：
Linux NAME #1 SMP TIME x86_64 x86_64 x86_64 GNU/Linux
Linux version 2.6.32_1-12-0-0 (scmpf@dbl-sat-dev01.dbl01.baidu.com) (gcc version 4.4.4 20100726 (Red Hat 4.4.4-13) (GCC) ) #1 SMP Mon Aug 12 17:59:52 CST 2013
CentOS release 4.3 (Final)
Kernel \r on an \m
LSB Version:    :core-3.0-amd64:core-3.0-ia32:core-3.0-noarch:graphics-3.0-amd64:graphics-3.0-ia32:graphics-3.0-noarch
Distributor ID: CentOS
Description:    CentOS release 4.3 (Final)
Release:        4.3
Codename:       Fina

###The output from `python -c "import tensorflow; print(tensorflow.__version__)"`：
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/users/caoshiwei/.jumbo/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/users/caoshiwei/.jumbo/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/users/caoshiwei/.jumbo/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/users/caoshiwei/.jumbo/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/users/caoshiwei/.jumbo/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /home/users/caoshiwei/.jumbo/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: ELF file OS ABI invalid

Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help

**Comment by asimshankar** [comment]
Please provide all the information asked for in the "New Issue" template (which includes version, OS, architecture etc.).

**Comment by caoshiwei** [comment]
I have add some infos about this Issue

**Comment by asimshankar** [comment]
Please do provide _all_ the information asked for in the "New Issue" template, without which it is hard to diagnose.

From Googling the error message, it seems that this might have to do with the fact that your machine/Linux distribution might have a very old loader?

**Comment by caoshiwei** [comment]
updated Issue
that‘s all INFO about this Issue
the  machine/Linux distribution is old loader as Environment info shown

**Comment by drpngx** [comment]
As @asimshankar said, this is CentOS 4.4, which was released about 10 years ago apparently. Linux used to have SystemV formatted binaries, I think.

According to this, if you use `od` you should be able to see which format you have.
https://en.wikipedia.org/wiki/Executable_and_Linkable_Format

The only route is to build from source, but you need `gcc-4.x` with `C++11` support for that. You might be able to cross-compile.

**Comment by caoshiwei** [comment]
thx~
