### ISSUE TITLE
Tensorboard Summaries in Re-entered Scopes

### ISSUE THREAD

**Issue by jaakkopasanen** [tensorflow/tensorflow#8387]
Tensorboard creates a new unique scope for summaries every time existing variable scope is re-entered leading to summaries being split to different groups in the Tensorboard. This might be due to summaries using name scopes internally and re-entered variable scopes having unique `original_name_scope`.

```python
def print_scope(scope):
    print('               scope.name: {}'.format(scope.name))
    print('scope.original_name_scope: {}'.format(scope.original_name_scope))

with tf.variable_scope('parent') as parent_scope:
    print_scope(parent_scope)
    with tf.variable_scope('childA') as childA_scope:
        print_scope(childA_scope)
print()
with tf.variable_scope(parent_scope):
    print_scope(parent_scope)
    with tf.variable_scope('childB') as childB_scope:
        print_scope(childB_scope)
```
outputs
```
               scope.name: parent
scope.original_name_scope: parent/
               scope.name: parent/childA
scope.original_name_scope: parent/childA/

               scope.name: parent
scope.original_name_scope: parent/
               scope.name: parent/childB
scope.original_name_scope: parent_1/childB/
```
Child B is created in re-entered parent scope and has prefix for parent in the `original_name_scope`. I believe parent prefix is what confuses name scope in Tensorboard summaries. I think re-entering existing variable scope should not have these unique prefixes for parent scope.

I have lemmatizer wrapped in Python class and Tensorboard summaries are created in different stages of graph build with re-entered variable scopes. Tensorboard splits graphs like so: [Screenshot](http://i.imgur.com/KRDt3wj.png)

Tested on Tensorflow 1.0.1

**Comment by camallenlloyd** [comment]
I also observed this same problem with Tensorflow 1.0.1

**Comment by orome** [comment]
I have the same problem. I use helper something like

```
def _variable_summaries(var, name):
    with tf.name_scope("stats"):
        with tf.name_scope('mean'):
            mean = tf.reduce_mean(var)
            tf.summary.scalar(name, mean)
        with tf.name_scope('sttdev'):
            tf.summary.scalar(name, tf.sqrt(tf.reduce_sum(tf.square(var - mean))))
        with tf.name_scope('max'):
            tf.summary.scalar(name, tf.reduce_max(var))
        with tf.name_scope('min'):
            tf.summary.scalar(name, tf.reduce_min(var))
    tf.summary.histogram(name, var)
```

which I call with 

```
_variable_summaries(weights, layer_name + '/weights')
_variable_summaries(biases, layer_name + '/biases')
```

for each layer as it is created.

This used to create a collection of stats for each layer (one panel/scope per layer, containing all the collected stats). But now I get two `stats_X` layers for each layer. I also get a mess when trying to track anything that iterates and attempts to "accumulate" values in a single scope over time, [like the global step](https://stackoverflow.com/q/44249086/656912) or the elapsed time taken by an epoch.

Is there a workaround I'm missing? Is this the intended behavior now?

(I think I actually found `_variable_summaries` in older Tensorflow docs.)

**Comment by chihuahua** [comment]
I migrated this issue to tensorflow/tensorboard#93 because TensorBoard has moved out of the TensorFlow repository and into the new tensorflow/tensorboard repository. Lets continue discussion there.
