### ISSUE TITLE
ArgumentError: argument --train_dir: conflicting option string: --train_dir

### ISSUE THREAD

**Issue by dowhat1995** [tensorflow/tensorflow#8389]
I met this question,when I run "cifar10_train.py" in jupyter.

---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
/root/.jupyter/workspace/littlefish/cifar10/cifar10_train.py in <module>()
     50 
     51 tf.app.flags.DEFINE_string('train_dir', '/tmp/cifar10_train',
---> 52                            """Directory where to write event logs """
     53                            """and checkpoint.""")
     54 tf.app.flags.DEFINE_integer('max_steps', 1000000,

/root/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/flags.py in DEFINE_string(flag_name, default_value, docstring)
     78     docstring: A helpful message explaining the use of the flag.
     79   """
---> 80   _define_helper(flag_name, default_value, docstring, str)
     81 
     82 

/root/anaconda3/lib/python3.5/site-packages/tensorflow/python/platform/flags.py in _define_helper(flag_name, default_value, docstring, flagtype)
     63                               default=default_value,
     64                               help=docstring,
---> 65                               type=flagtype)
     66 
     67 

/root/anaconda3/lib/python3.5/argparse.py in add_argument(self, *args, **kwargs)
   1342                 raise ValueError("length of metavar tuple does not match nargs")
   1343 
-> 1344         return self._add_action(action)
   1345 
   1346     def add_argument_group(self, *args, **kwargs):

/root/anaconda3/lib/python3.5/argparse.py in _add_action(self, action)
   1705     def _add_action(self, action):
   1706         if action.option_strings:
-> 1707             self._optionals._add_action(action)
   1708         else:
   1709             self._positionals._add_action(action)

/root/anaconda3/lib/python3.5/argparse.py in _add_action(self, action)
   1546 
   1547     def _add_action(self, action):
-> 1548         action = super(_ArgumentGroup, self)._add_action(action)
   1549         self._group_actions.append(action)
   1550         return action

/root/anaconda3/lib/python3.5/argparse.py in _add_action(self, action)
   1356     def _add_action(self, action):
   1357         # resolve any conflicts
-> 1358         self._check_conflict(action)
   1359 
   1360         # add to actions list

/root/anaconda3/lib/python3.5/argparse.py in _check_conflict(self, action)
   1495         if confl_optionals:
   1496             conflict_handler = self._get_handler()
-> 1497             conflict_handler(action, confl_optionals)
   1498 
   1499     def _handle_conflict_error(self, action, conflicting_actions):

/root/anaconda3/lib/python3.5/argparse.py in _handle_conflict_error(self, action, conflicting_actions)
   1504                                      for option_string, action
   1505                                      in conflicting_actions])
-> 1506         raise ArgumentError(action, message % conflict_string)
   1507 
   1508     def _handle_conflict_resolve(self, action, conflicting_actions):

ArgumentError: argument --train_dir: conflicting option string: --train_dir

**Comment by drpngx** [comment]
Did you run this twice? Can you try with normal python?

**Comment by hoveidar** [comment]
I was getting the same error and it was exactly because I ran the code more than once. Restart the kernel and the code cell once. Done!

**Comment by drpngx** [comment]
Nice!

**Comment by jiqiujia** [comment]
I wonder if there is any way to clear all predefined argument, since restarting the kernel each time is annoying

**Comment by drpngx** [comment]
The short answer is probably no. The `flags` code is based on `argparse`, which doesn't appear to support removal. You could try to reload the tensorflow module `reload(tensorflow)` or its flag module.

I imagine it's possible to reset the args if you import argparse, then do: `tf.flags._global_parser = argparse.ArgumentParser()`. This is subject to change but probably won't change very frequently.

**Comment by hannah-rae** [comment]
I'm having this problem too where I've defined my learning rate in flags.py and I'm getting the error "argparse.ArgumentError: argument --learning_rate: conflicting option string(s): --learning_rate". However, learning_rate is only mentioned in the flags.py file (below) and the config.yaml file (both specified as floats).

This has never happened to me before, it only happened after I reorganized my files into subdirectories in preparation for tuning hyperparameters with Google ML Cloud engine. 

```
import tensorflow as tf
import sys

flags = tf.app.flags
flags.DEFINE_float('learning_rate', 1e-3, 'Initial learning rate')
flags.DEFINE_integer('batch_size', 4, 'Batch size')
flags.DEFINE_integer('input_rows', 144, 'Number of rows in input images')
flags.DEFINE_integer('input_cols', 160, 'Number of columns in input images')
flags.DEFINE_integer('input_filters', 3, 'Number of filters in input images')
flags.DEFINE_integer('num_train_samples', 42096, 'Number of training examples')
flags.DEFINE_integer('n_z', 2200, 'Size of bottleneck layer')
flags.DEFINE_integer('C1', 64, 'Number of feature maps in first conv layer')
flags.DEFINE_integer('C2', 32, 'Number of feature maps in second conv layer')
flags.DEFINE_integer('C3', 16, 'Number of feature maps in third conv layer')
flags.DEFINE_integer('FC4', 1024, 'Number of feature maps in first fully connected layer')
flags.DEFINE_integer('FC5', 512, 'Number of feature maps in second fully connected layer')
flags.DEFINE_integer('FC6', 256, 'Number of feature maps in third fully connected layer')
flags.DEFINE_integer('kernel_size', 3, 'Kernel size for all convolutions')
flags.DEFINE_integer('stride_size', 1, 'Stride size for all convolutions')
flags.DEFINE_string('log_dir', './log', 'Directory to store training checkpoints')
flags.DEFINE_string('train_dir', '/Users/hannahrae/data/mcam_vae/train', 'Directory containing training images')
flags.DEFINE_string('test_dir', '/Users/hannahrae/data/mcam_vae/test', 'Directory containing test images')
flags.DEFINE_string('val_dir', '/Users/hannahrae/data/mcam_vae/validation', 'Directory containing validation images')
flags.DEFINE_integer('max_steps', 800, 'Maximum number of times to run trainer')
flags.DEFINE_integer('num_epochs', 10, 'Number of times to go through all the training data')
flags.DEFINE_float('l2_beta', 0.01, 'Beta term in L2 regularization of weights')
flags.DEFINE_string('tmp_dir', './tmp/data', 'Directory to download data files and write the converted result')

FLAGS = flags.FLAGS
```

<img width="237" alt="screen shot 2017-10-02 at 4 38 01 pm" src="https://user-images.githubusercontent.com/6354180/31104142-1b59b686-a790-11e7-8f9f-39855255d2f1.png">

**Comment by cekai** [comment]
If there is a module called within `cifar10_train.py`, in which a flag of the same name exists, this error may appear. Make sure to set a unique name for the flag.
