### ISSUE TITLE
tf.lbeta() error when fed with placeholder

### ISSUE THREAD

**Issue by thjashin** [tensorflow/tensorflow#8391]
Hi, there seems to be a bug in `tf.lbeta`.

```python
tf.lbeta(tf.placeholder(tf.float32, [3, 2, 3, None]))
# => ValueError: Can not squeeze dim[0], expected a dimension of 1, got 3 for 'lbeta_1/cond/Squeeze' (op: 'Squeeze') with input shapes: [3,2,3,?].
```

**Comment by concretevitamin** [comment]
@langmore are you the right person to take a look?

**Comment by langmore** [comment]
Yes, I'm the right person for this.

@concretevitamin  I have an internal fix for this.  I'll send to you once ready.

@thjashin  Thanks for reporting!

**Comment by concretevitamin** [comment]
A fix by @langmore will be pushed upstream soon.  Closing this.

**Comment by thjashin** [comment]
Thanks! @concretevitamin @langmore 
Just a bit more, there seems to be no static shape inference in `tf.lbeta()`

**Comment by langmore** [comment]
What in particular doesn't work?  The old code had some static inference (see the tests).  After this recent fix, the same tests are still in place, and the code is much simpler, so I suspect there won't be any problems.
