### ISSUE TITLE
How to add a new op which is similar with matmul

### ISSUE THREAD

**Issue by maydaygmail** [tensorflow/tensorflow#8392]
I want to add a new op which is similar with matmul, for example anothermatmul. 
1. add REGISTER_OP("AnotherMatMul") to tensorflow/core/ops/math_ops.cc like MatMul
2. add anothermatmul_op.h anothermatmul_op.cc to tensorflow/core/kernels/
3. bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
then I can see  bazel-bin/tensorflow/core/libmath_ops_op_lib.lo is update, I think the new op has been compiled successfully.
4. install 

I find util/python/python_lib/tensorflow/python/ops/gen_math_ops.py is not updated, and cannot use AnotherMatMul in python.

how to update gen_math_ops.py?
or how to generate python wrap?

**Comment by drpngx** [comment]
Please be a bit clearer about "how to use".

There are a few steps:

1. Make sure you add `anothermatmul_op` in the [`BUILD` file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/BUILD#L2136)
2. Make sure you follow the instructions if you want to run in-place (or install the pip)

If the `gen_math_ops.py` is not generated, then it means that you didn't rebuild properly. Try `bazel build --explain=/tmp/blaze_debug.log --config=opt //tensorflow/python:math_ops`
It should show that the file is updated.

**Comment by maydaygmail** [comment]
Thanks. I add anothermatmul_op to BUILD,  bazel build and install. But the  gen_math_ops.py cannot be updated. 
1. run bazel build tensorflow/python:math_ops_gen, and a new gen_math_ops.py is generated in bazel-genfiles/tensorflow/python/ops/, which can find the new op another_mat_mul.
2. cp bazel-genfiles/tensorflow/python/ops/gen_math_ops.py util/python/python_lib/tensorflow/python/ops/gen_math_ops.py
3. add a function def another_matmul: gen_math_ops.another_mat_mul to util/python/python_lib/tensorflow/python/ops/math_ops.py
4. when call tf.another_matmul, get error:tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'AnotherMatMul'

however, I have add REGISTER_OP("AnotherMatMul") to tensorflow/core/ops/math_ops.cc

how to add a new op?
Thanks in advance.

**Comment by drpngx** [comment]
OK, that's great. The build/install should have worked. I never had to do this before, but try to uninstall first before installing. And maybe remove /tmp/tensorflow_pkg before you run the pip building script.

The error you are seeing is because the `_pywrap_tensorflow_internal.so` has not been updated. If you figure out how to rebuild the PIP install then it should work.

**Comment by maydaygmail** [comment]
Thanks! uninstall and install again, that solved!
