### ISSUE TITLE
Add bounds to tf.contrib.opt.ScipyOptimizerInterface

### ISSUE THREAD

**Issue by wielandbrendel** [tensorflow/tensorflow#8393]
For style transfer it is common the use L-BFGS-B, and the ScipyOptimizerInterface greatly simplifies its application in TF. However, to increase the quality of the synthesised images one typically restricts the range of the values to standard int8 [0, 255] by providing box constraints. 

Hence my feature request: Please add the bounds keyword to the interface of ScipyOptimizerInterface.

**Comment by yaroslavvb** [comment]
cc @joshburkart who wrote the wrapper

**Comment by joshburkart** [comment]
I believe this is already possible -- `ScipyOptimizerInterface` takes an optional parameter `optimizer_kwargs`, into which you can pass things like `{'bounds': [[0, 1]]}` etc.

The deficiency, as I see it, is that you don't directly control how the `Variable`s you are optimizing over get packed into a single vector for SciPy to do its thing with... LMK if this is a problem/if you have any ideas on how to improve this.

**Comment by wielandbrendel** [comment]
I tried `optimizer_kwargs`, but those get inserted as `options` into `scipy.minimize` and so cannot be used for bounds.

**Comment by joshburkart** [comment]
Hmm, I'm looking [here](https://github.com/tensorflow/tensorflow/blob/cb17d1b0e2b581b5da1d9597b7929ba764749d38/tensorflow/contrib/opt/python/training/external_optimizer.py#L317) and it seems like `optimizer_kwargs` get sent as kwargs straight to `scipy.optimize.minimize`. So why couldn't a `bounds` kwarg be added this way...?

**Comment by wielandbrendel** [comment]
Sorry, I was blind - @joshburkart is correct. Thanks!

**Comment by nicaogr** [comment]
I have a problem when I try to use the bounds argument to the ScipyOptimizerInterface function. I have this error message "TypeError: _minimize_lbfgsb() got multiple values for argument 'bounds'
" with the following code. :

```
import tensorflow as tf

vector = tf.Variable([7., 7.], 'vector')
# Make vector norm as small as possible.
loss = tf.reduce_sum(tf.square(vector))
bounds = [[-10,10],[-10,10]]
optimizer = tf.contrib.opt.ScipyOptimizerInterface(loss, options={'maxiter': 100,"bounds" : bounds})
with tf.Session() as session:
	session.run(tf.global_variables_initializer())
	optimizer.minimize(session)
# The value of vector should now be [0., 0.].
print(vector[0],vector[1])
```

It seems to be the same kind of problem than on an other conversation : [https://github.com/scipy/scipy/issues/4608](url)
And the solution is to pass bounds as a primary key of minimizer_kwargs of the function which use scipy.optimize.minimize but it is not possible to do that with the ScipyOptimizerInterface.

Do you have an idea ?

**Comment by joshburkart** [comment]
This is a SciPy thing... Change to
```python
optimizer = tf.contrib.opt.ScipyOptimizerInterface(loss, bounds=bounds, options={'maxiter': 100})
```

**Comment by nicaogr** [comment]
Thanks a lot.

**Comment by joshburkart** [comment]
FYI that we've now added a `var_to_bounds` argument to ScipyOptimizerInterface that allows specifying per-`Variable` bounds. It's submitted in the internal Google repository so should be available in GitHub/PyPi soon. Also be aware that once the update is rolled out, supplying the `bounds` keyword explicitly as I suggested above will raise an exception...
