### ISSUE TITLE
32-bit Windows exe generation using cmake

### ISSUE THREAD

**Issue by ANeeK181** [tensorflow/tensorflow#8397]
Hi

I have compiled my code using the procedure outlined in the documentation to generate 64-bit exe on windows using cmake. Now I want to create 32-bit binary but cmake does not run for the option -A x86.
Can somebody how can I generate a 32-bit binary still using 64-bit VS tools?

**Comment by drpngx** [comment]
Perhaps this [stackoverflow post](http://stackoverflow.com/questions/28350214/how-to-build-x86-and-or-x64-on-windows-from-command-line-with-cmake) helps.

I am not sure that TF works on 32 bits. We might have done that work for Android.

**Comment by ANeeK181** [comment]
Ok, I tried the procedure mentioned in that post. But it does not compile and exits with "error MSB6006, cmd.exe exited with code 9009". No further information about error. I searched for it and there is no concrete reason for this error.

**Comment by drpngx** [comment]
Could you post the full log, maybe somewhere on pastebin? I'm not sure what's wrong.

I know that VS 64bit can cross compile into x86, but I don't know if the converse is true.

**Comment by ANeeK181** [comment]
Here is the attached log file. I rebuilt so that's why time is less, else it took 53 minutes last time for error to pop up. Anyways, what I do is:

(1) Set up Visual Studio 14 to be used as Generator:
cmake -G "Visual Studio 14 2015" /path_to_source

(2) Then I do 
cmake --build build_32 --config Release

If I use "Visual Studio 14 2015 Win64", then it generates targets for Platform x64.

[log.txt](https://github.com/tensorflow/tensorflow/files/846735/log.txt)

**Comment by ANeeK181** [comment]
(1) If I use the process outlined in the original ReadMe at Github, [https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake](url)

Then using 64 bit tools, and using cmake 
cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release ^ ... (rest of command)

The process runs fine, and 64bit exe is generated for sample code. I even changed the sample code and got it to read from already built graph and it works fine. 

(2) If I repeat the process, that is setup 64-bit tools of VS and then run the same cmake command but without mentioning architecture, i.e. -A FLAG

cmake ..  -DCMAKE_BUILD_TYPE=Release ^ ... (rest of command)

Then VS projects are for Win32 Platform and the process again halts with error, but this time error is of linking 64bit library "libprotobuf.lib" with the target exe for x86. Here is the attached error log:

[log_2.txt](https://github.com/tensorflow/tensorflow/files/846812/log_2.txt)

I guess that this library is downloaded when repo of protobuf is cloned when building the projects. So does this mean that exe for 32-bit platform can't be generated?

**Comment by gunan** [comment]
Maybe this?
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/external/protobuf.cmake#L10

But since 32 bit on windows is not officially supported, you can get better help on stackoverflow.

**Comment by ANeeK181** [comment]
ok, still not working. Another dependency on some 64bit identifier is popping up now. The error is:

**c:\users\aneek\documents\tf_x86_build\tensorflow\tensorflow\core\common_runtime\bfc_allocator.h(356): error C3861: '_BitScanReverse64': identifier not found [C:\Users\ANeeK\Documents\TF_x86_Build\tensorflow\tensorflow\contrib\cmake\build_32\tf_core_cpu.vcxproj]**

I think it probably won't compile for 32-bit.

**Comment by GraceDD** [comment]
@ANeeK181  I came into the same question as you, and I fixed it by change _BitScanReverse64 function to _BitScanReverse, and then built tf_core_cpu.lib successfully.

**Comment by yossitsadok** [comment]
Hi Guys,

Could anybody post clear steps how to build 32-bit exe using cmake?

Thanks

**Comment by gunan** [comment]
We (TensorFlow team) never tried building TF on a 32 bit OS.
So we have no official support for TF on a 32 bit desktop system.
