### ISSUE TITLE
Septation of Generalised DAG / Data Flow Programming Framework and ML Components

### ISSUE THREAD

**Issue by sirinath** [tensorflow/tensorflow#84]
Can you make a clear separation between DAG / Data Flow Programming Framework and the ML framework. The former can have more applications than ML and will open more avenues for its use.

**Comment by datnamer** [comment]
If you want generalized DAG programming in python you can use [Dask](http://dask.pydata.org/en/latest/) and [Blaze](http://dask.pydata.org/en/latest/) from the [Blaze Project](http://blaze.pydata.org/)

**Comment by sirinath** [comment]
I like to use the same features but in other languages.

**Comment by sirinath** [comment]
You can have have the following break up of the project:

 - Dataflow Computation Framework
 - Dataflow Computation Framework Tools
 - Tool Development Framework
 - ML Framework
 - ML Framework Tools

**Comment by martinwicke** [comment]
We have no plans to break up tensorflow, or separate out components for independent distribution.
