### ISSUE TITLE
Tensorflow not working in Zeppelin 0.7.0

### ISSUE THREAD

**Issue by nsriram13** [tensorflow/tensorflow#8401]
There seems to be some issue using Tensorflow in Zeppelin 0.7.0 and it throws this error:
NameError: name `_interactive` is not defined

Another user reported the [same issue](http://stackoverflow.com/questions/42757433/tensorflow-can-not-work-with-zeppelin) on SO. The fix suggested there seems to be really hacky.

The issue seems to be that in tf_logging.py file [.\Anaconda3\Lib\site-packages\tensorflow\python\platform\tf_logging.py] the _interactive variable is not triggering for Zeppelin.

```
# Determine whether we are in an interactive environment
try:
  # This is only defined in interactive shells
  if _sys.ps1: _interactive = True
except AttributeError:
  # Even now, we may be in an interactive shell with `python -i`.
  _interactive = _sys.flags.interactive
```

**Comment by drpngx** [comment]
It looks the code meant to have `_interactive = False` before the [block](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/tf_logging.py#L40). Would you be willing to file a PR?

**Comment by nsriram13** [comment]
Sure thing!

**Comment by drpngx** [comment]
Great, thanks!
