### ISSUE TITLE
Windows: is Python 2.7 support planned?

### ISSUE THREAD

**Issue by Felix-neko** [tensorflow/tensorflow#8409]
Good evening! Are you planning to support Python 2.7 on Windows? It may be very useful.

**Comment by caisq** [comment]
@gunan and @mmry can correct me if I'm wrong - but we don't have any immediate plans to add Python 2 support for Windows.

**Comment by gunan** [comment]
CC @mrry (corrected username)
AFAIK, unless we build python 2.7 from sources using Visual studio 2015 or 2017, it is not possible to build tensorflow with python 2.7.
Therefore, we will not support python 2.7 on windows.

**Comment by Felix-neko** [comment]
Any custom Python 2.7 libraries can easily be built with VS 2015, even if Python 2.7 is built with VS2008.

**Comment by mrry** [comment]
Even if that might work (and I have been able to run simple TensorFlow programs using Python 2.7 on Windows), I don't think we'd want to support such a configuration. Some of the issues discussed here are relevant:

http://siomsystems.com/mixing-visual-studio-versions/
