### ISSUE TITLE
py_func() is not getting imported

### ISSUE THREAD

**Issue by aadilh** [tensorflow/tensorflow#841]

**Comment by vrv** [comment]
py_func isn't public yet, which is why it is not available.  Once it's ready, we'll import it, add documentation, etc.  We may additionally initially import it into an 'unsupported' module while it is being worked on.

**Comment by vrv** [comment]
Actually, it looks like it is public (according to our documentation), but only at HEAD, not 0.6.0.

**Comment by aadilh** [comment]
@vrv can you please suggest someway to use it? I mean I tried to build the source but it is giving errors with gen_script_ops used in tensorflow/python/ops/script_ops.py

**Comment by zffchen78** [comment]
Hi, aadih,

I just verified the code from HEAD should work. I did the following:
$ git clone --recurse-submodules https://github.com/tensorflow/tensorflow
$ bazel test -c opt //tensorflow/python:py_func_test
the test passes.

So, it's most likely your test code or your build environment is somehow different from ours. If you paste the exact error you see, we may be able to help you diagnose.

**Comment by aadilh** [comment]
It was problem with my bazel's version. Its working now. This feature is a great step ahead :+1:
