### ISSUE TITLE
bazel can not quantize image net inception models

### ISSUE THREAD

**Issue by astrung** [tensorflow/tensorflow#8418]
when i run command : `bazel build tensorflow/tools/quantization:quantize_graph --verbose_failures` from this tutorial : https://www.tensorflow.org/performance/quantization, i get this error, and still can not fix it : 
    ERROR: /tensorflow/tensorflow/core/kernels/BUILD:1315:1: C++ compilation of rule '//tensorflow    /core/kernels:svd_op' failed: gcc failed: error executing command 
    virtual memory exhausted: Cannot allocate memory    

I run this command on docker with single CPU. I have 1.5 GB RAM in docker.
So will i need more RAM to run it ?
can i download a quantize image net inception models without using bazel , like as downloading inception models without compiling it by bazel ?

**Comment by concretevitamin** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

(And yes, the error suggests just your VM's RAM is not enough.)
