### ISSUE TITLE
Error in compiling TensorFlow from source on Ubuntu: bazel build fails.

### ISSUE THREAD

**Issue by annanay25** [tensorflow/tensorflow#8419]
I am compiling TensorFlow from source on an Ubuntu machine. This is a verbose output of the error log generated in the ```bazel build //tensorflow/tools/pip_package:build_pip_package``` execution. 

System details:
```uname -a ```: Linux - 3.13.0-107-generic

    ERROR: /home/annanay/.cache/bazel/_bazel_root/9b62c7240de3d9136528cdded945b550/external/llvm/BUILD:418:5: Generating code from table: lib/Target/AArch64/AArch64.td @llvm//:aarch64_target_gen__gen_fast_isel_genrule failed: bash failed: 
    error executing command 
    (cd /home/annanay/.cache/bazel/_bazel_root/9b62c7240de3d9136528cdded945b550/execroot/tensorflow && \
    exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
    /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; 
    bazel-out/host/bin/external/llvm/llvm-tblgen -I external/llvm/include -I external/llvm/tools/clang/include -I    
    $(dirname external/llvm/lib/Target/AArch64/AArch64.td) -gen-fast-isel external/llvm/lib/Target/AArch64/AArch64.td -o bazel-out/local-opt/genfiles/external/llvm/lib/Target/AArch64/AArch64GenFastISel.inc'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 127.
    bazel-out/host/bin/external/llvm/llvm-tblgen: relocation error: bazel-out/host/bin/external/llvm/llvm-tblgen: symbol _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERmm, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
    Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by gunan** [comment]
There is no information about TensorFlow version, there is not information on compiler version, or your linux distribution. We cannot provide any help just by looking at your linux kernel version.

I will close this issue now.
Please file again by filling out all of the issue template.
