### ISSUE TITLE
Tool request: Deep Visualization Toolbox for TensorFlow

### ISSUE THREAD

**Issue by cesarsalgado** [tensorflow/tensorflow#842]
I would like TensorFlow to have an official tool similar to this https://github.com/yosinski/deep-visualization-toolbox.

It would be helpful to check if our CNNs were learning useful features, to debug, and to have better insights.

Check this video: https://www.youtube.com/watch?v=AgkfIQ4IGaM

Thoughts?

**Comment by bhack** [comment]
:+1:

**Comment by mathetes87** [comment]
+1
It would be amazing!

**Comment by jeandut** [comment]
+1

**Comment by danmane** [comment]
This would be really cool to add! It's not on my roadmap for this quarter, but if anyone wants to implement it I'd be happy to discuss design and guide through the process.

**Comment by barneypell** [comment]
+1

**Comment by shendiaomo** [comment]
This quarter is nearly over, how about do it in Q2:-)？@danmane

**Comment by BENMFeng** [comment]
+1

**Comment by danmane** [comment]
@shendiaomo - sorry, still not on my near or medium term agenda :)

**Comment by kingtaurus** [comment]
Quick workaround;
I believe some of visualization features of this tool can be handled directly within tensorflow (and combined with tensorboard) with a bit of effort.

Issues: 
1. the layout is not ideal (and there are issues with layout of images in general);
2. extra code means an increased chance for mistakes;
3. it seems to make the processing much slower :);
4. it doesn't take into account max_pooling (or other spatial contracting operations);

This provides visualization of output images of each layer (which is part of the requirements - but is in-efficient  :-1: );
```
W_conv1 = weight_variable([3,3,1,128])
#f_x,f_y,depth, number of filters
b_conv1 = bias_variable([128])
cnn_layer_1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1)

W_conv2 = weight_variable([3,3,128,128])
b_conv2 = bias_variable([128])
cnn_layer_2 = tf.nn.relu(conv2d(cnn_layer_1, W_conv2) + b_conv2)

W_conv3 = weight_variable([3,3,128,128])
b_conv3 = bias_variable([128])
cnn_layer_3 = tf.nn.relu(conv2d(cnn_layer_2, W_conv3) + b_conv3)

#grab only the first element of the batch and 16 filters
layer1_image1 = cnn_layer_1[0:1, :, :, 0:16]
layer2_image1 = cnn_layer_2[0:1, :, :, 0:16]
layer3_image1 = cnn_layer_3[0:1, :, :, 0:16]

layer1_image1 = tf.transpose(layer1_image1, perm=[3,1,2,0])
layer2_image1 = tf.transpose(layer2_image1, perm=[3,1,2,0])
layer3_image1 = tf.transpose(layer3_image1, perm=[3,1,2,0])

layer_combine_1 = tf.concat(2, [layer3_image1, layer2_image1, layer1_image1])
list_lc1 = tf.split(0, 16, layer_combine_1)
layer_combine_1 = tf.concat(1, list_lc1)

tf.image_summary("filtered_images_1", layer_combine_1)
# combine this summary with tensorboard (and you get a decent output);
```

Looks like (using MNIST):
![tensorboard-tiled-filter-output](https://cloud.githubusercontent.com/assets/2761482/15947688/ba56104a-2e51-11e6-8dfc-69c9e3f4b1b3.png)

The other parts would requires a little bit more work (some involve backprop).

**Comment by dyelax** [comment]
Has anyone started working on this? I might take a shot at it if there are no ongoing efforts

**Comment by danmane** [comment]
@dyelax Feel free to take a shot. If you build it as a standalone Polymer component that would make it easier to integrate into TensorBoard as a new tab. You could try forking one of the existing dashboards and adding the functionality you need.

We plan to make it possible for TensorBoard to request raw Tensor data directly from the backend (i.e. from a tf.summary.tensor_summary) which may be helpful.

**Comment by tarrencev** [comment]
@dandelionmane would it make sense to leverage the existing image summaries for this instead of creating a new summary type?

**Comment by BhagyeshVikani** [comment]
Hi!
We have done some work on this and implemented the algorithm for convolutional neural networks visualization described in http://www.cs.nyu.edu/~fergus/papers/zeilerECCV2014.pdf and something similar to https://github.com/yosinski/deep-visualization-toolbox but using Tensorflow instead of caffe. However, we are not yet familiar with the TF codebase/ API to integrate it into the ImageSummary tab of tensorboard. We would like to make it into a part of tensorboard. Could someone suggest a good starting point of how we go about doing this? 
Here's how far we've progressed: Given any CNN, we can get the reconstructed images from deconvolution for all the layers in the network as described in the paper above.

**Comment by micahstubbs** [comment]
@BhagyeshVikani that sounds cool! wrapping what you have in a Polymer custom element might be a good strategy. Eager to hear an official answer from the TensorBoard team

https://www.polymer-project.org/1.0/

**Comment by micahstubbs** [comment]
@BhagyeshVikani @dandelionmane did mention a future [TensorBoard plugin format](https://twitter.com/micahstubbs/status/831948453395599360) recently at #TFDevSummit.

when that plugin format is published, I imagine that's the way to go

**Comment by BhagyeshVikani** [comment]
We developed a simple API which can reconstruct images (as per ) from given TF graph layer name and write image summary into the log file for visualization in TensorBoard. Feel free to use and test it. In case of queries or questions, do post on the link given below.

Link: https://bitbucket.org/infocusp/tf_cnnvis

**Comment by BhagyeshVikani** [comment]
We also added [Deep dream](https://github.com/InFoCusp/tf_cnnvis) to the arsenal:

|   |   |   |   |
| :-----------: | :-----------: | :-----------: | :-----------: |
| <img src="https://bitbucket.org/repo/Lyk4Mq/images/302562334-deep_999.png" width="196" height="196"> | <img src="https://bitbucket.org/repo/Lyk4Mq/images/586427523-deep_9.png" width="196" height="196"> | <img src="https://bitbucket.org/repo/Lyk4Mq/images/3658923710-deep_24.png" width="196" height="196"> | <img src="https://bitbucket.org/repo/Lyk4Mq/images/2708104439-deep_385.png" width="196" height="196"> |
| Carbonara | Ibex | Elephant | Ostrich |
| <img src="https://bitbucket.org/repo/Lyk4Mq/images/3678905801-deep_993.png" width="196" height="196"> | <img src="https://bitbucket.org/repo/Lyk4Mq/images/1049045916-deep_970.png" width="196" height="196"> | <img src="https://bitbucket.org/repo/Lyk4Mq/images/2473296459-deep_934.png" width="196" height="196"> | <img src="https://bitbucket.org/repo/Lyk4Mq/images/1596202689-deep_933.png" width="196" height="196"> |
| Cheese burger | Tennis ball | Fountain pen | Clock tower |
| <img src="https://bitbucket.org/repo/Lyk4Mq/images/3869149957-deep_738.png" width="196" height="196"> | <img src="https://bitbucket.org/repo/Lyk4Mq/images/4283505926-deep_915.png" width="196" height="196"> | <img src="https://bitbucket.org/repo/Lyk4Mq/images/2629248471-deep_14.png" width="196" height="196"> | <img src="https://bitbucket.org/repo/Lyk4Mq/images/3971745292-deep_22.png" width="196" height="196"> |
| Cauliflower | Baby Milk bottle | Sea lion | Dolphin |

**Comment by wchargin** [comment]
Happy to see that this is such a popular request! It sounds like this would be a perfect fit to be implemented as a new plugin/dashboard (like the scalars dashboard or image dashboard). We're actively working on a new plugin system that will make it easy for external contributors to create such plugins, either to use for themselves or share back to TensorBoard core. Keep an eye out in the coming months!

I've migrated this issue to our new repository at https://github.com/tensorflow/tensorboard/issues/81. Please feel free to continue discussion there.
