### ISSUE TITLE
Android demo build Error

### ISSUE THREAD

**Issue by zhaomingxiaomi** [tensorflow/tensorflow#8423]
when i used android studio build the android demo, i got this error:

Warning: ignoring http_proxy in environment.
____Loading package: tensorflow/examples/android
____Found 1 target...
____Building...
Target //tensorflow/examples/android:external_assets up-to-date (nothing to build)
____Elapsed time: 0.163s, Critical Path: 0.00s

:copyExternalAssets UP-TO-DATE
:buildNativeBazel
Warning: ignoring http_proxy in environment.
____Loading complete.  Analyzing...
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:avgpooling_op.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:bounds_check.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:cwise_ops.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:cwise_ops_common.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:cwise_ops_gradients.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_activations.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_attention.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_backward_cuboid_convolutions.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_backward_spatial_convolutions.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_cuboid_convolution.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_patch_3d.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_pooling.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_softmax.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:eigen_spatial_convolutions.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:fifo_queue.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:maxpooling_op.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:ops_util.cc' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:ops_util.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:padding_fifo_queue.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:pooling_ops_common.cc' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:pooling_ops_common.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:queue_base.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:queue_op.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:typed_queue.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_beam_entry.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_beam_scorer.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_beam_search.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_decoder.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/ctc:ctc_loss_util.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/tensor_bundle:naming.cc' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/tensor_bundle:naming.h' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/tensor_bundle:tensor_bundle.cc' directly. You should either move the file to this package or depend on an appropriate rule there.
WARNING: /home/zhaoming/tensorflow/tensorflow/tensorflow/core/BUILD:872:12: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/util/tensor_bundle:tensor_bundle.h' directly. You should either move the file to this package or depend on an appropriate rule there.
____Found 1 target...
____Building...
ERROR: /home/zhaoming/tensorflow/tensorflow/tensorflow/examples/android/BUILD:22:1: C++ compilation of rule '//tensorflow/examples/android:libtensorflow_demo.so' failed: false failed: error executing command /bin/false -MD -MF bazel-out/stub_armeabi-v7a-opt/bin/tensorflow/examples/android/_objs/libtensorflow_demo.so/tensorflow/examples/android/jni/object_tracking/tracked_object.pic.d ... (remaining 25 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/examples/android:tensorflow_native_libs failed to build
Use --verbose_failures to see the command lines of failed build steps.
____Elapsed time: 0.248s, Critical Path: 0.01s

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildNativeBazel'.
> Process 'command '/home/zhaoming/bin/bazel'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 0.675 secs

how can i fix it? thx

**Comment by andrewharp** [comment]
Have you followed the instructions from [examples/android/README.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/README.md), including the NDK/SDK installation and WORKSPACE editing?

If so, when you build manually with:
`bazel build -c opt tensorflow/examples/android:tensorflow_demo --stacktrace --info`

Does it give you any more info?

**Comment by zhaomingxiaomi** [comment]
i run bazel build -c opt tensorflow/examples/android:tensorflow_demo
it passed , gradle build fixed too.  i dont know why..

**Comment by andrewharp** [comment]
Ok, great :)  /usr/bin/false errors usually occur if Bazel isn't able to find an expected binary (e.g. g++). Possibly you installed something or updated your WORKSPACE file between attempts?
