### ISSUE TITLE
Saving with monitored session

### ISSUE THREAD

**Issue by vrenkens** [tensorflow/tensorflow#8425]
I get the following error when trying to use a saver with a Monitored session:

```
File "/users/spraak/spch/prog/spch/tensorflow-1.0.0/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1369, in save
    raise TypeError("'sess' must be a Session; %s" % sess)
TypeError: 'sess' must be a Session; <tensorflow.python.training.monitored_session.MonitoredSession object at 0x2be710d0>
```

I save like this:

```
with tf.train.MonitoredTrainingSession(...) as sess:
    ...
    saver.save(sess, 'model.ckpt')
```

instead of sess I also tried `tf.get_default_session()`, but this returns None. In all other cases the monitored_session works just like a normal session, so I think it's a bug.

**Comment by vrenkens** [comment]
I found that the Session object is stored in sess._sess._sess._sess._sess and if I do 

```
saver.save(sess._sess._sess._sess._sess, 'model.ckpt')
```

It actually works, but this is of course not desired. I wrote temporary method to circumvent the issue until it is solved:

```
def get_session(sess):
    Session = sess
    while type(Session).__name__ != 'Session':
        #pylint: disable=W0212
        Session = Session._sess
    return Session
```

I can then save with:

```
saver.save(get_session(sess), 'model.ckpt')
```

**Comment by concretevitamin** [comment]
I don't think explicitly manipulating Saver inside a `MonitoredTrainingSession` is recommended (could you use a vanilla `Session`?), but @ispirmustafa must know more.

**Comment by vrenkens** [comment]
The thing is I have a training graph that holds a bunch of variables that are relevant for training, but not or the model (e.g. global_step). I have 2 savers, one that stores all my variables, to checkpoint the training process, so I can resume training if necessary. And one trainer to save my model at the end of training. This is why I want to explicitly manipulate a saver.

**Comment by ispirmustafa** [comment]
You can write a hook. something like as follows:
```
class SaveAtEnd(tf.train.SessionRunHook):
  def begin(self):
    self._saver = # create your saver
  def end(self, session):
    saver.save(session, ...)
```

**Comment by eastskykang** [comment]
Why this issue was closed? I don't see @ispirmustafa 's answer solve the problem.

**Comment by vrenkens** [comment]
You have to create a hook that does the saving for you and put it into the session

**Comment by vrenkens** [comment]
This is the hook I use:

```
class SaveAtEnd(tf.train.SessionRunHook):
    '''a training hook for saving the final variables'''

    def __init__(self, filename, variables):
        '''hook constructor

        Args:
            filename: where the model will be saved
            variables: the variables that will be saved'''

        self.filename = filename
        self.variables = variables

    def begin(self):
        '''this will be run at session creation'''

        #pylint: disable=W0201
        self._saver = tf.train.Saver(self.variables, sharded=True)

    def end(self, session):
        '''this will be run at session closing'''

        self._saver.save(session, self.filename)
```

**Comment by sathyamoorthyrr** [comment]
> This is the hook I use:
> 
> ```
> class SaveAtEnd(tf.train.SessionRunHook):
>     '''a training hook for saving the final variables'''
> 
>     def __init__(self, filename, variables):
>         '''hook constructor
> 
>         Args:
>             filename: where the model will be saved
>             variables: the variables that will be saved'''
> 
>         self.filename = filename
>         self.variables = variables
> 
>     def begin(self):
>         '''this will be run at session creation'''
> 
>         #pylint: disable=W0201
>         self._saver = tf.train.Saver(self.variables, sharded=True)
> 
>     def end(self, session):
>         '''this will be run at session closing'''
> 
>         self._saver.save(session, self.filename)
> ```

Should we need to pass the filename and required variables to save through the hook?
What should I pass if I want to save all the variables?

any snippet is helpful.
