### ISSUE TITLE
HVX Acceleration support

### ISSUE THREAD

**Issue by Ziyann** [tensorflow/tensorflow#8428]
I successfully built and ran the test application from `tensorflow/tree/master/tensorflow/contrib/hvx`. I'd now like to benchmark HVX against the CPU implementations of `tensorflow/tools/benchmark`, and the Android camera demo, but I wasn't able to find any documentation describing how to build said apps with HVX support (my builds run on the CPU). I'm testing on the Open-Q 820 development board with Android 7.0.

Is it possible to utilize HVX acceleration outside the HVX test application, preferably with the benchmark and Android camera demos? If so, could someone please point me in the right direction?

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
