### ISSUE TITLE
Versions Web Page Needs Updating

### ISSUE THREAD

**Issue by jubjamie** [tensorflow/tensorflow#8429]
This really is a small issue but I couldn't submit a PR as I couldn't find the file for it.
At https://www.tensorflow.org/versions/ the current version is stated as 0.12 when it should be 1.0!

`The docs at root (i.e. in tensorflow.org/api_docs) refer to the most recent stable branch (in this case, r0.12)`

That's it. Sorry for raising an issue for such a trivial detail! Thanks

**Comment by concretevitamin** [comment]
@yifeif: Yifei, could you take a look?  Thanks!

**Comment by yifeif** [comment]
Thanks for pointing it out @jubjamie.
@wolffg could we add to our website generation to update according to root change? Thank you!

**Comment by yifeif** [comment]
This has been fixed. Now it should say "most recent stable branch (in this case, r1.2)". Thanks!
