### ISSUE TITLE
build issue: Bazel paths

### ISSUE THREAD

**Issue by thompsonb** [tensorflow/tensorflow#843]
As of 0db986d25335a767855e92fc5748038f6fb585c4, I'm getting the error below when I try to build from source. Is my Bazel out of date or something?

=========================

ERROR: /home/bjt/git_repos/tensorflow2/tensorflow/cc/BUILD:11:6: First argument of load() is a path, not a label. It should start with a single slash if it is an absolute path..
ERROR: /home/bjt/git_repos/tensorflow2/tensorflow/cc/BUILD:12:6: First argument of load() is a path, not a label. It should start with a single slash if it is an absolute path..
ERROR: /home/bjt/git_repos/tensorflow2/tensorflow/cc/BUILD:11:6: file '/tensorflow:tensorflow.bzl.bzl' was not correctly loaded. Make sure the 'load' statement appears in the global scope in your file.
ERROR: /home/bjt/git_repos/tensorflow2/tensorflow/cc/BUILD:12:6: file '/tensorflow:tensorflow.bzl.bzl' was not correctly loaded. Make sure the 'load' statement appears in the global scope in your file.
ERROR: /home/bjt/git_repos/tensorflow2/tensorflow/cc/BUILD:21:13: Traceback (most recent call last):
        File "/home/bjt/git_repos/tensorflow2/tensorflow/cc/BUILD", line 14
                cc_library(name = "cc_op_gen_main", srcs = ["ops/cc_op_gen.cc", "ops/cc_op_gen_main.cc"], hdrs = ["ops/cc_op_gen.h"], copts = tf_copts(), deps = ["//tensorflow/core:framework"])
        File "/home/bjt/git_repos/tensorflow2/tensorflow/cc/BUILD", line 21, in cc_library
                tf_copts
name 'tf_copts' is not defined.
ERROR: /home/bjt/git_repos/tensorflow2/tensorflow/cc/BUILD:28:1: name 'tf_gen_op_wrappers_cc' is not defined.
ERROR: /home/bjt/git_repos/tensorflow2/tensorflow/cc/BUILD:66:13: Traceback (most recent call last):
        File "/home/bjt/git_repos/tensorflow2/tensorflow/cc/BUILD", line 63
                cc_binary(name = "tutorials_example_trainer", srcs = ["tutorials/example_trainer.cc"], copts = tf_copts(), linkopts = ["-lpthread", "-lm"], deps = [":cc_ops", "//tensorflow/core:kernels", "//tensorflow/core:tensorflow"])
        File "/home/bjt/git_repos/tensorflow2/tensorflow/cc/BUILD", line 66, in cc_binary
                tf_copts
name 'tf_copts' is not defined.
ERROR: no such target '//tensorflow/cc:tutorials_example_trainer': target 'tutorials_example_trainer' not declared in package 'tensorflow/cc' defined by /home/bjt/git_repos/tensorflow2/tensorflow/cc/BUILD.
INFO: Elapsed time: 2.232s

=========================

bazel version
Build label: 0.1.1
Build target: bazel-out/local_linux-fastbuild/bin/src/main/java/bazel-main_deploy.jar
Build time: Thu Oct 15 20:15:14 2015 (1444940114)
Build timestamp: 1444940114
Build timestamp as int: 1444940114

**Comment by vrv** [comment]
As of current HEAD, you now have to upgrade to bazel 0.1.4.  Let us know if you still have problems after upgrading.

**Comment by thompsonb** [comment]
Worked, thanks!

**Comment by alexatknit** [comment]
Please update the documentation on the website to reflect this: https://www.tensorflow.org/versions/master/get_started/os_setup.html#installation-for-linux

**Comment by vrv** [comment]
Yeah, we updated here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#install-bazel 

but we haven't updated the website from that.  @martinwicke

**Comment by martinwicke** [comment]
Done.
