### ISSUE TITLE
Exif Orientation support tf.image.decode_jpeg()

### ISSUE THREAD

**Issue by tsomeq** [tensorflow/tensorflow#8430]
Hi.
I have large amounts of JPEG files uploaded by users on our service .
They use mainly smartphone camera, so most files contain EXIF orientation metadata.

It would seem that the `tf.image.decode_jpeg()` ignores this information,
So I cannot build pipeline using pure tensor operation.
I thought it is not better to writing custom decoder depending external libraries, considering complying thread safety and future compatibility.

My Pipeline code is like below:

```python
filename_queue = tf.train.string_input_producer(files)
reader = tf.WholeFileReader()
key, supplyContent = reader.read(filename_queue)
decoding = tf.image.decode_jpeg(supplyContent, channels=3)
#  source image may have orientation but dropped 
resizing = tf.image.resize_images(decoding, (IMAGE_SIZE, IMAGE_SIZE))
# ...
```

Transformation of image can be done with simple tensor op, since tf.image has many convenience methods.
How about adding support for these meta informations ?

**Comment by concretevitamin** [comment]
I doubt we'll working on this since we haven't seen much demand.  FYI, writing custom input-processing ops is totally _a_ valid use of TensorFlow.  In this case, I'd very much encourage it since it could deliver more functionalities (necessary) and better performance (good).

**Comment by tsomeq** [comment]
@concretevitamin 
All right, I understand.
I'll write decoding logic with referring PIL .

Thank you for your reply.

**Comment by dpaiton** [comment]
> I doubt we'll working on this since we haven't seen much demand.

FYI - the Flickr 100m image dataset (and by extension the multimedia creative commons image dataset) has many EXIF formatted JPG files, which currently break with tf.image.decode_image and tf.image.decode_jpeg. Also I find it surprising that there is not much demand for dealing with images taken on smart phones considering "Tensorflow was designed with mobile and embedded platforms in mind." https://www.tensorflow.org/mobile/

**Comment by concretevitamin** [comment]
+ @petewarden who will know more about mobile use cases.

**Comment by RobinKips** [comment]
Any update on EXIF orientation support in the latest api ?  This actually prevent me to properly use the Dataset logic with smartphone pictures....

**Comment by wikiwen** [comment]
Yeah, this is a big problem

**Comment by yongtang** [comment]
Please see https://github.com/tensorflow/io/pull/604 which adds the kernel ops in tensorflow/io to extract EXIF orientation (to be used in dataset).

**Comment by Fogrunner** [comment]
Someone made a package to resolve this problem.

https://medium.com/@ageitgey/the-dumb-reason-your-fancy-computer-vision-app-isnt-working-exif-orientation-73166c7d39da
