### ISSUE TITLE
Cannot find attention functions

### ISSUE THREAD

**Issue by Cospel** [tensorflow/tensorflow#8433]
Hi, i am trying to implement attention rnn and want to use https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/attention_decoder_fn_inference and other attention methods from attention_decoder_fn.py . However i cannot find it here on github ...

When this functionality will be available?
Why is it in api web page but not in the repo?

**Comment by skye** [comment]
This function exists in the 1.0 branch: https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/contrib/seq2seq/python/ops/attention_decoder_fn.py#L134

However, it was recently deleted from master: https://github.com/tensorflow/tensorflow/commit/d46937f3684d3be2285f7401c2f471f542d147c2

I suggest either using 1.0, or looking at the code currently in master: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/seq2seq/python/ops

If you have further questions about using seq2seq, please ask on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) (we try to keep Github issues focused on bugs and feature requests).
