### ISSUE TITLE
How to broadcast

### ISSUE THREAD

**Issue by lincolnBush** [tensorflow/tensorflow#8438]
Dear all:
I want to broadcast Thr from a single float value to (batchsize, 128,128, 1), I don't know how to do that, when I use the code below, the error occurred that shape do not match. I am using the newest version of tensorflow. Many thanks.

Thr  = tf.multiply(Thr, tf.ones([shape[1], shape[2]], tf.float32))

**Comment by shoyer** [comment]
Please send usage questions to StackOverflow
