### ISSUE TITLE
tf_kernel_library doesn't work from repo containing tensorflow as a submodule

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#8439]
`tf_kernel_library` and friends from `tensorflow.bzl` refer to deps like `//tensorflow/core:gpu_lib`.  These deps do not work if TensorFlow exists only under `@org_tensorflow`, which results in errors like

    bazel build ...
    WARNING: /usr/local/google/home/geoffreyi/.cache/bazel/_bazel_geoffreyi/f928d2088d4c5ef4e2f54ff2af6f8a71/external/org_tensorflow/tensorflow/workspace.bzl:72:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
    WARNING: /usr/local/google/home/geoffreyi/.cache/bazel/_bazel_geoffreyi/f928d2088d4c5ef4e2f54ff2af6f8a71/external/org_fold/WORKSPACE:1: Workspace name in /usr/local/google/home/geoffreyi/.cache/bazel/_bazel_geoffreyi/f928d2088d4c5ef4e2f54ff2af6f8a71/external/org_fold/WORKSPACE (@org_tensorflow_fold) does not match the name given in the repository's definition (@org_fold); this will cause a build error in future versions.
    ERROR: /usr/local/google/home/geoffreyi/deepmath/deepmath/guidance/BUILD:83:1: no such package 'tensorflow': Package crosses into repository @org_tensorflow and referenced by '//deepmath/guidance:clause_ops'.
    ERROR: /usr/local/google/home/geoffreyi/deepmath/deepmath/guidance/BUILD:83:1: no such package 'tensorflow': Package crosses into repository @org_tensorflow and referenced by '//deepmath/guidance:clause_ops'.
    ERROR: /usr/local/google/home/geoffreyi/deepmath/deepmath/guidance/BUILD:83:1: no such package 'tensorflow': Package crosses into repository @org_tensorflow and referenced by '//deepmath/guidance:clause_ops'.
    ERROR: /usr/local/google/home/geoffreyi/deepmath/deepmath/guidance/BUILD:83:1: no such package 'tensorflow': Package crosses into repository @org_tensorflow and referenced by '//deepmath/guidance:clause_ops'.
    ERROR: /usr/local/google/home/geoffreyi/deepmath/deepmath/guidance/BUILD:83:1: no such package 'tensorflow': Package crosses into repository @org_tensorflow and referenced by '//deepmath/guidance:clause_ops'.
    ERROR: /usr/local/google/home/geoffreyi/deepmath/deepmath/guidance/BUILD:83:1: no such package 'tensorflow': Package crosses into repository @org_tensorflow and referenced by '//deepmath/guidance:clause_ops'.
    ERROR: Analysis of target '//deepmath/guidance:clause_ops' failed; build aborted.
    INFO: Elapsed time: 0.320s

**Comment by girving** [comment]
Cc @jart, @damienmg.  I naively tried adding a `@%ws%` prefix similar to the third party BUILD files, but `ws` isn't defined inside tensorflow itself.

**Comment by girving** [comment]
Are there plans to make Bazel more resilient to this kind of configuration error?  As is it seems very tricky to use in a scalable and correct way.

**Comment by yaroslavvb** [comment]
PS, me + @scott-gray gave up on compiling TF as a submodule for a custom cuda op because of similar snags


IE, bazel select isn't context sensitive to the workspace it's defined in, and TF cuda macros use  `select` --
http://stackoverflow.com/questions/41153199/building-a-tensorflow-based-android-app-with-tensorflow-as-a-repository

**Comment by girving** [comment]
@yaroslavvb What did you do instead?

**Comment by scott-gray** [comment]
I ended up just writing a simple script to copy my custom ops into tensorflow/core/user_ops and build things from there.  Then I just copy out the generated .so file and incorporate it my pip setup.py (in package_data).  This lets me distribute a nice clean pip package that's mostly independent of TF.

**Comment by girving** [comment]
I can make things work as expected if I add `@org_tensorflow` before every target in `tensorflow.bzl`.  @jart: I imagine that's not kosher, but if there's version that is I can prepare a PR.

**Comment by girving** [comment]
@scott-gray @yaroslavvb Custom ops with submodules should work now.

**Comment by girving** [comment]
Or rather, `tf_kernel_library` probably works too, but it wouldn't be usable from Python (which defeats the purpose).
