### ISSUE TITLE
No such package 'tensorflow/tensorflow/tools/docs': BUILD file not found on package path

### ISSUE THREAD

**Issue by teldridge11** [tensorflow/tensorflow#8443]
I am trying to generate docs locally as g3doc now recommends after the documentation change from about 2 weeks ago, but the command it says to run is failing.

I am running `bazel run -- tensorflow/tools/docs:generate \ --src_dir=tensorflow/docs_src/ \ --output_dir=/tmp/tfdocs/`

But it fails with the error:

```
ERROR: no such package 'tensorflow/tensorflow/tools/docs': BUILD file not found on package path.
INFO: Elapsed time: 0.112s
ERROR: Build failed. Not running target.
```

I have the latest version of bazel installed, and my repo is up to date, so I'm not sure why this would be failing.  The `tools/docs/BUILD` file definitely exists, so it seems strange that it would tell me 'BUILD file not found on package path'.

I figured since this change to the docs is very recent, there could potentially be some problems here...although I'm not sure why this would impact bazel.  Or is there something I'm missing?

**Comment by skye** [comment]
I just tried that command on the latest master checkout and it worked for me. Can you verify that you're running the bazel command from the latest master branch, at the root of the repo, etc.?

**Comment by asimshankar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
