### ISSUE TITLE
Scatter_nd bug

### ISSUE THREAD

**Issue by Arsakes** [tensorflow/tensorflow#8446]
I'm getting strange bug with scatter_nd (TF 1.0v).

    InvalidArgumentError (see above for traceback): Must have updates.shape = indices.shape[:IXDIM] +     
    params_shape[IXDIM:], got updates.shape [1,2,4], indices.shape [1,2,2], params_shape [1,9,4]

I've read the docs for scatter_nd function and it seems to me that following set of shapes are perfectly viable:
Maybe I'm tired but, Using terms from the docs:
`indices` rank: Q = 3
`shape` rank : P = 3
last dim length for indices K = 2
`updates` rank:  = Q-1+P-K = 3-1+3-2=3
All seems to fit.
And full shape of `update` should be: 
`[indices_shape[0], indicies_shape[1], shape[K]] `
which gives: 
`[1, 2, 4]`

Where is the problem?

**Comment by concretevitamin** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Arsakes** [comment]
It is a bug report - now I'm sure - also it is the same as  #7585.

**Comment by gyxlucy** [comment]
@Arsakes  Hi, I try to repeat your error with the following example (with your values of P, Q, K, and shape):

![test](https://cloud.githubusercontent.com/assets/8649007/25023199/cb4ed708-204d-11e7-88da-e3ca0e714c75.jpg)

but it seems to work fine to me.

Do you mind sharing more details how you get the error?

**Comment by Arsakes** [comment]
Which tf. version you use 1.0???
Here are details:
http://stackoverflow.com/questions/43007410/tensorflow-unexpected-tf-gather-nd-behaviour-bug
If it is night build or 1.1 It is very likely the issue was solved.
