### ISSUE TITLE
For loop over 'NoneType' TensorFlow Dimensions

### ISSUE THREAD

**Issue by cmertin** [tensorflow/tensorflow#8448]
I'm implementing a new type of NN in TensorFlow. The difference is in the evaluation function, so instead of calling `tf.matmul()`, I call my own function, which we'll call `My_Function(A)`.

A snippet of the code can be seen below, where `A` is the tensor on the left being multiplied by this new NN implementation, which is on the right. The equivalent tensorflow code would be `tf.matmul(A, this_new_NN)`.

    def My_Function(self, A):
        dims = A.get_shape().as_list()
        shape = [dims[0], self.m] # Defining shape of resulting tensor
        X = tf.placeholder(tf.float32, shape=[shape[0], shape[1]])
        result = tf.zeros(tf.shape(X), dtype=tf.float32)
        for xyz in self.property:
            # Do some computation between A and xyz, xyz is a property of this_new_NN
            # resulting to temp_H with dimension [shape[0], xyz.m] of type tf.tensor
            dims_H = temp_H.get_shape().as_list()
            indices = [[i,j] for i in range(0, dims_H[0]) for j in range(xyz.k, xyz.k+dims_H[1])]
            # indices is a list of indices to update in "result"
            values = tf.reshape(temp_H, [-1]) # Values in temp_H as 1D list
            delta = tf.SparseTensor(indices, values, shape)
            result += tf.sparse_tensor_to_dense(delta)
        return result

Now the problem I'm having is in the line where I calculate the `indices`, where I'm getting the error

`TypeError: 'NoneType' object cannot be interpreted as an integer`

Now, I understand that this error means that you cannot iterate a for loop over a type of `None`, but the problem I have is the test set and the training set have different values for `batch_size`. This means that when I go to create `result`, the first dimension is unknown which is why it is of type `None`. 

But, to get the indices that I have to update in `result`, I have to use a for loop to generate those values as a list to feed into `delta` which I'm creating as a `tf.SparseTensor` so it can be added to `result`. 

My question is, what is the best way to get the indices? I have tried replacing `dims_H[0]` in the for loop with a `tf.placeholder(tf.int32)` object instead, where I would then just pass the size when I run the session, but I get the error of

`TypeError: 'Tensor' object cannot be interpreted as an integer`

Any help would be greatly appreciated.

Edit:

Just for reference, this code is called in the following way, where `M` is the pre-built new NN composed with `tf.Variable` values.

`Y1 = tf.nn.relu(M.My_Function(A) + B1)`

where `B1` is the offset for this layer, and `A` is the input layer.

Edit2:

`result` should be a zero tensor *every time* `My_Function` is called. However, I have a suspicion that it is preserving the values of `result` with each function call. If this is right, please let me know what I need to do to change that.

Edit3:

When defining `A` it is defined as

    X1 = tf.placeholder(tf.float32, [None, 28, 28, 1])
    A = tf.reshape(X1, [-1, 28*28])

As the dimensions of `A` change between the training data and test data.

**Comment by concretevitamin** [comment]
The issue seems to broil down to replacing 
`indices = [[i,j] for i in range(0, dims_H[0]) for j in range(xyz.k, xyz.k+dims_H[1])]`
with a TensorFlow graph implementation.  I believe in principle this is expressible using existing ops; some of the relevant ones seem to be `tf.shape(...)[0]` (which will give you the correct batch_size at execution time) and `tf.range()`, etc.  Could you give those a try?

**Comment by cmertin** [comment]
Using `tf.shape(...)[0]` and `tf.range()` so it's of the form `tf.range(0, tf.shape(...)[0], 1)` for the first and the equivalent `tf.range()` function for the second gives the error of

`TypeError: 'Tensor' object is not iterable.`

So it sees the results of `tf.shape` as a tensor object. In fact, if I take the exact same line that's giving me problems, and just change `range` to `tf.range`, I get the same error about it being a Tensor, even though it's given as a list to `dims_H`

**Comment by concretevitamin** [comment]
Hmm, `tf.range()` should be able to handle scalar Tensors.  I just tried:

```python
with tf.Session() as sess:
  v = tf.Variable(np.zeros((2, 2)))
  print sess.run(tf.range(0, tf.shape(v)[1]))
```
with no issues.

**Comment by cmertin** [comment]
First of all Zongheng, I'd like to thank you for your help so far. But I'm still not able to get it working. The problem is still dealing with the same line, however it is a different error... I have posted the majority of my code as I believe it might have something to do with `tf.matmul()` being involved right before this process, yet I'm not 100% sure.

    def My_Function(self, A):
        dims = A.get_shape().as_list()
        shape = [dims[0], self.m] # Defining shape of resulting tensor
        with tf.Session() as sess:
            X = tf.placeholder(tf.float32, shape=[shape[0], shape[1]])
            result = tf.zeros(tf.shape(X), dtype=tf.float32)
            for xyz in self.property:
                # Computation is of the following form, where xyz.M is a tf.Variable() tensor
                a = A[:, xyz.i:xyz.i + xyz.n] # Slice of A (the input tensor)
                temp_H = tf.matmul(a, sub.M)
                indices = [[i,j] for i in sess.run(tf.range(0, tf.shape(temp_H)[0])) for j in tf.sess(tf.range(xyz.k, xyz.k+tf.shape(temp_H)[1]))] # same but with sess.run, tf.range, tf.shape
                # indices is a list of indices to update in "result"
                values = tf.reshape(temp_H, [-1]) # Values in temp_H as 1D list
                delta = tf.SparseTensor(indices, values, shape)
                result += tf.sparse_tensor_to_dense(delta)
        return result

The traceback is the following, dealing with the `indices = ` line still:

`InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'Placeholder', defined at:
  File "/home/christopher/anaconda3/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/christopher/anaconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 653, in launch_instance
    app.start()
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-8452266bec9e>", line 3, in <module>
    X = tf.placeholder(tf.float32, [None, 28, 28, 1])
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1587, in placeholder
    name=name)
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2043, in _placeholder
    name=name)
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/christopher/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]`

I have attempted changing `tf.shape(temp_H)[0]` to `tf.shape(result)[0]` (as they have the same first dimension) in that line but I still get the same error. More than likely the same error is going to occur for `j` in the above for loop, but the solution should be similar.

**Comment by skye** [comment]
@cmertin can you provide a (reasonably) minimal repro of this problem? It'd be helpful if you could modify the code snippet you provided so it runs as-is and produces the error you're seeing in your full model.

**Comment by cmertin** [comment]
@skye here is a gist version of my code. It is a minimal version and I want to point something out. On the line defining `indices`, where the error occurs, for the value/range of `j`, in my actual code it will be a different range. For example, instead of going from `tf.range(0, tf.shape(temp)[1])`, it will go to something like `tf.range(self.k, self.k + tf.shape(temp)[1])`. Doing that wouldn't work in the example I uploaded, but it's required in my main program. However, the definition of `i` is based on the definition in the example, so it is `tf.range(0, tf.shape(A)[0])` in my code as well as the gist.

https://gist.github.com/cmertin/84dda9294a596b238958627b6728d13d

**Comment by skye** [comment]
Thank you for providing the repro script, it's very helpful. The problem with the `indices =` line is that you're running a computation that depends on the placeholder `X` (`temp` is derived from `a` which is derived from the My_Function argument `A`, and you've passed in `X`). As the error message suggests, you'll need to somehow pass in a feed_dict argument to your sess.run() call that provides a value for `X`.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by zhaopku** [comment]
@cmertin Hi, did you fix this problem? I am also try to loop over 'NoneType' TensorFlow Dimensions and I have the same error messages as you.

**Comment by zaczou** [comment]
@zhaopku Hi, me too. When i set x = tf.placeholder(tf.float32, [None,  3] ), i want to loop over the first dimmension of the x.  If i use "for  i in range(x.get_shape().as_list()[0])", the error is   " 'NoneType' object cannot be interpreted as an integer",  if " for i in range(tf.shape(x)[0])", error is " 'Tensor' object cannot be interpreted as an integer". Did you find a way to fix this? Thanks.

**Comment by evdcush** [comment]
In same situation as the others here, also trying to do what @zaczou mentioned.

@girving can we reopen the issue?

**Comment by fontran** [comment]
i m having the same issue. has this been fixed? I can't loop thru the None dimension of a placeholder.

**Comment by Minmm2017** [comment]
Hi, does anyone solve this problem to use for loop over 'NoneType' placeholder?

**Comment by ktsumura** [comment]
Hi, I uses tf.scan for loop over 'NoneType'. Note that None dimension should be dimension 0.

https://www.tensorflow.org/api_docs/python/tf/scan

**Comment by WolfLo** [comment]
Has anyone found a solution to the issue? @ktsumura could you please show us a working example?

**Comment by vamshikumarkurva** [comment]
Is this issue resolved?

**Comment by snakepowerpoint** [comment]
@cmertin how do you solve this problem afterwards?

**Comment by deluksic** [comment]
Also hitting this problem rn, trying to map over indices in the first (None) dimension.

**Comment by prajwaltr93** [comment]
try disabling eager execution before building the graph !

`import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()`
