### ISSUE TITLE
import android example to android studio fail

### ISSUE THREAD

**Issue by duanLH** [tensorflow/tensorflow#8457]
When I follow the step by android READ.ME, It failed .

 Error:(145, 0) A problem occurred evaluating root project 'android'.
and the location is: from  from file(externalModelData).listFiles() 
task copyExternalAssets(type: Copy) {
    from file(externalModelData).listFiles()
    include '*.pb'
    include '*.txt'
    include 'thumbnails/*.jpg'
    into 'assets'
    fileMode 0644
    dependsOn buildExternalAssets
}
I dont know how to solve this .

**Comment by andrewharp** [comment]
Run `bazel build -c opt tensorflow/examples/android:tensorflow_demo` once manually. This will initialize the bazel-tensorflow directory that Gradle is looking for the model files in. After that you'll be able to build normally with Android Studio.

There's a fix pending to make this work in a more generic fashion without needing Bazel.

**Comment by duanLH** [comment]
Thanks, It's running. But there is a 'bug', if my root directory is "tensorflow-master", the "bazel-tensorflow-master" would be initialized, but the build.gradle is looking for the "bazel-tensorflow". So ,it need to rename the directory
