### ISSUE TITLE
Broken curl URL for flower_photos.tgz

### ISSUE THREAD

**Issue by jd20** [tensorflow/tensorflow#8459]
The tutorial for retraining Inception's final layer has a malformed URL, the instructions for downloading the dataset are:

```
cd ~
curl -O http://download.tensorflow.org/example_../images/flower_photos.tgz
tar xzf flower_photos.tgz
```

The URL is broken, I think it's supposed to be:

```
curl -O http://download.tensorflow.org/example_images/flower_photos.tgz
```

**Comment by MicaelCarvalho** [comment]
Already fixed. The docs should be updated with the release of TF's next version: https://github.com/drpngx/tensorflow/commit/1f8eae975b16940d60041065b08d15d47af6c820

**Comment by jd20** [comment]
Great, thanks!
