### ISSUE TITLE
No nigthly build for Python3.5 GPU

### ISSUE THREAD

**Issue by SeguinBe** [tensorflow/tensorflow#8460]
According to [the build history](https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-linux-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3.5,label=gpu-linux/) the last time the GPU version for python 3.5 was built was almost a month ago. That actually leads the download link from the README.md front page to point to a [file not found page](https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-linux-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3.5,label=gpu-linux/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow_gpu-1.0.1-cp35-cp35m-linux_x86_64.whl).

That's too bad because there are some bug-fixes that I needed which are then not included (#7585 for instance).

**Comment by yaroslavvb** [comment]
What about this link?
https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-linux-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=gpu-linux/

( I clicked on your link, then clicked on "nightly matrix GPU"). I think perhaps Python 3.5 got renamed to Python 3, to support the fact that 3.6 and 3.5 can use the same wheel

**Comment by SeguinBe** [comment]
I originally tried without success, python complaining about the version.

Though it can work indeed, but ONLY after renaming it to `tensorflow_gpu-1.0.1-py3-none-linux_x86_64.whl`. Which is what I did in the end after some googling around.

Maybe adding some clarification somewhere?

**Comment by yaroslavvb** [comment]
So to summarize the issue:
If you are Linux GPU Python 3.5 user, and you go through "Installation" section on https://github.com/tensorflow/tensorflow and click the appropriate link, you will not get the nightly, but instead you will get a month old version.

**Comment by gunan** [comment]
@caisq @jhseu looks like we forgot to bring this build back.
Do we have the configs in place?
do we just need to change jenkins?

**Comment by caisq** [comment]
Yes, @gunan. There are a bunch of manual things to do after the rollback to 14.04 for build. I'll take care of those today.

**Comment by SeguinBe** [comment]
Seems it's up again already, great!
