### ISSUE TITLE
customize parse_op.py and recompile

### ISSUE THREAD

**Issue by ouceduxzk** [tensorflow/tensorflow#8463]
Hi, my problem is that I want to hack code in the parse_op.py file， especially I want to have an option of Dict or OrderedDict for the output of parse_single_example and many other parser that return Dict. Should I submit a PR or you guys can add that in the next version ?

By installing from source , I got following errors 

`INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.........
INFO: All external dependencies fetched successfully.
Configuration finished
[zaikun@greina0 tensorflow]$ python -c 'import tensorflow'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
ImportError: No module named pywrap_tensorflow_internal
`

**Comment by concretevitamin** [comment]
Please properly fill out the issue template in order for us to help diagnose.

**Comment by ouceduxzk** [comment]
version : 1.0.0
reproducible example : 

 `    reader = tf.TFRecordReader()
    _, serialized_example = reader.read(filename_queue_video)

    # set the mapping from the fields to data types in the proto
    num_features = len(self.video_feature_names)
    assert num_features > 0, "self.feature_names is empty!"
    assert len(self.video_feature_names) == len(self.video_feature_sizes), \
    "length of feature_names (={}) != length of feature_sizes (={})".format( \
    len(self.video_feature_names), len(self.video_feature_sizes))

    feature_map = {"video_id": tf.FixedLenFeature([], tf.string),
                   "labels": tf.VarLenFeature(tf.int64)}
    for feature_index in range(num_features):
      feature_map[self.video_feature_names[feature_index]] = tf.FixedLenFeature(
          [self.video_feature_sizes[feature_index]], tf.float32)

    features = tf.parse_single_example(serialized_example,
                                       features=feature_map)`
In the implementation of parse_single_example, a Dict is returned. However, I would like to have an orderedDict in python

**Comment by concretevitamin** [comment]
I am not sure if anyone is working on this.  My personal preference is to keep interfaces simple.  You could easily add a utility function in your own model to return an ordered dict.
