### ISSUE TITLE
non_max_suppression should support batches

### ISSUE THREAD

**Issue by Panaetius** [tensorflow/tensorflow#8465]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

Might be related/nice to do when overworking non_max_suppression for #7511

Related SO: http://stackoverflow.com/questions/39456554/tensorflow-tensor-with-inconsistent-dimension-size

### Description

Most image ops work on batches of images, so it'd make sense if tf.image.non_max_suppression worked on batches of bounding-boxes , returning batches of selected indices.

Although I'm not completely sure how it'd work with the variable result lengths that are likely to happen in this case, perhaps masking or padding them? There's already the max_output_size parameter.

And I'm not entirely sure how well it'd work with gather (gather_nd?), since if it doesn't work well with those, this change wouldn't be as useful

**Comment by zacharynevin** [comment]
+1

**Comment by matrix246** [comment]
+1

**Comment by jiarenyf** [comment]
+1

**Comment by jiarenyf** [comment]
+1
And could return a sparse tensor ...

**Comment by jnd77** [comment]
There is a new-ish op which does that: 
tf.image.combined_non_max_suppression

**Comment by etasnadi** [comment]
> There is a new-ish op which does that:
> tf.image.combined_non_max_suppression

It does not return indices...
