### ISSUE TITLE
No scalars and images show up in tensorboard

### ISSUE THREAD

**Issue by XinLiuNvidia** [tensorflow/tensorflow#8477]
I'm trying to get some visualization on tensorboard, the graph is shown up, but scalars and images are not. I also tried the mnist demo code, still the same problem.
My colleagues could see the visualization from tensorboard on their machines, so the event/data itself has no problem.
Anyone has any clue?

I have checked this thread: https://github.com/tensorflow/tensorflow/issues/1421, and tried everything suggested. I do have css file under /usr/local/lib/python2.7/dist-packages/tensorflow/tensorboard/lib/css/

### Environment info
Operating System: Linux Ubuntu 14.04
Installed version of CUDA and cuDNN:  CUDA 8, cuDNN 5
pip installed tensorflow 0.12.1
### What other attempted solutions have you tried?
I tried different browser, chrome and firefox got the same results, no images and sclars show up.
I tried on other machines with same enviorment settings, and had no problem.

**Comment by MicaelCarvalho** [comment]
Are you outputting the data to TensorBoard? It won't display the images if you don't call `tf.summary.image`, for instance.

A reproducible example would help here...

**Comment by XinLiuNvidia** [comment]
Thank you Micael, I did call tf.summary.image. I could see those images from other machines without any problem. Other machines mean ubuntu 14.04, chrome and tensorflow 0.12.1.

**Comment by MicaelCarvalho** [comment]
Let's call the machine that doesn't work `A`, and another machine that works `B`. Try this:
1) Run your code on B;
2) Copy the log folder from B to A;
3) Run TensorBoard on A.

And then check if the images are visible on TensorBoard. This will tell us if the problem happens while TensorBoard is loading or if the output of TensorFlow is different on your machine (A).

**Comment by XinLiuNvidia** [comment]
Hi Micael, I tried what you suggested. 
1. Run my code on B: everything looks fine on tensorboard;
2. Copy the log folder from to B to A;
3. Run tensorboard on A: no scalars and images show up (the same as before).

**Comment by MicaelCarvalho** [comment]
Now try copying the TensorBoard folder from B to A. Not the logs, the TensorBoard folder with the sources. If it works, you had somehow a bad/corrupted installation. If it doesn't, your computer has something incompatible with TensorBoard.

Any error/warning logs when you launch TB?

**Comment by XinLiuNvidia** [comment]
Could you explain what do you mean TensorBoard folder with the sources?

**Comment by MicaelCarvalho** [comment]
For example, in my installation it's this folder:
`~/.local/lib/python3.5/site-packages/tensorflow/tensorboard/`

Inside of it there is the source for tensorboard (tensorboard.py) and other folders with more source (like the backend). This test is just a sort-of sanity check, to see if you're running the exact same tensorboard code of your colleagues.

**Comment by XinLiuNvidia** [comment]
Hi Micael, thank you. I have tried the tensorboard sources, and it is still not working on my machine.

**Comment by XinLiuNvidia** [comment]
when I run tensorboard with --debug, I see this:
INFO:tensorflow:path ../external/weblas_weblas_js/file/weblas.map.json not found, sending 404
INFO:tensorflow:returning 404 to 127.0.0.1 for /weblas_weblas_js/file/weblas.map.json

Is it related to the problem?

**Comment by MicaelCarvalho** [comment]
It could definitely be. At least this is a strong indicator of the problem.

Check python packages to see if you have a folder called `external`, and if inside of it there is another folder called `weblas_weblas_js`:
`~/.local/lib/python3.5/site-packages/external/`

If you don't, that's a problem with TF's installation. This folder (external) is inside the python wheel package for tensorflow, and is copied to that location. If you want a quick/easy solution, reinstall tensorflow using the pip command, and everything should work fine:
`pip3 install tensorflow-gpu`

**Comment by XinLiuNvidia** [comment]
Thank you! I think there might be network port issue in my computer. I have tried reinstall, and it still does not work for me. However, I launch tensorboard on machine A, and use machine B to ssh to A, and I can see the results on tensorboard on B's browser.
