### ISSUE TITLE
tf use all gpus in one machine, and killed my other training job, how to fix this?

### ISSUE THREAD

**Issue by tornadomeet** [tensorflow/tensorflow#848]
Hi, all,

i installed the gpu vision of tf which refer to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#virtualenv-installation, and when i run the third line of:
```python
import tensorflow as tf
hello = tf.constant('Hello, TensorFlow!')
sess = tf.Session()
```
then it will start all of my k80s in one machine, because there is som traning job of some gpus with almost full memeory, then when tf starts, it killed all of the other job. so how to fix this probem?that to say, when i start tf, it use the gpu 0 default?
thanks very much!

**Comment by ffmpbgrnn** [comment]
You can either set `CUDA_VISIBLE_DEVICES=0` or refer to [this thread](https://groups.google.com/a/tensorflow.org/forum/?utm_medium=email&utm_source=footer#!msg/discuss/jw4FtKOivZE/gU84lQebCAAJ)

**Comment by tornadomeet** [comment]
thanks~
