### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by sancarn** [tensorflow/tensorflow#8480]
On website page:
https://www.tensorflow.org/install/install_windows

There is a documentation error:

----

To install TensorFlow, start a ~terminal~ **command prompt instance**. Then issue the appropriate pip3 install command below.

To install the CPU-only version of TensorFlow, enter the following command:

```
cd %appdata%\..\Local\Programs\ython\Python35\Scripts
pip3 install --upgrade tensorflow
```

To install the GPU version of TensorFlow, enter the following command:

```
cd %appdata%\..\Local\Programs\ython\Python35\Scripts
pip3 install --upgrade tensorflow-gpu
```

----

I.E. pip3 isn't registered as an executable on the system while following the standard Python 3.5 installation executable. Thus you have to navigate to the folder containing the executable first.

**Comment by concretevitamin** [comment]
I think it is strongly implied/expected that the users should launch `pip3`, the binary, however they want and it's not meant to be followed verbatim.
