### ISSUE TITLE
Cannot import CudnnRNN from contrib.cudnn_rnn in 1.0.1

### ISSUE THREAD

**Issue by trungnt13** [tensorflow/tensorflow#8481]
For some reason all the "__init__.py" in python directory of _contrib.cudnn_rnn_ have been removed,
and it is impossible to import anything from there.

**Comment by skye** [comment]
Just an update, I have a fix for this, but am still working on getting it in.

**Comment by skye** [comment]
https://github.com/tensorflow/tensorflow/commit/986d337e7da04de627218c12e20be1e3abbf6097 should address this.
