### ISSUE TITLE
AOT compilation doesn't work on MacOS

### ISSUE THREAD

**Issue by xuehanxiongsc** [tensorflow/tensorflow#8485]
I was trying to reproduce this [example](https://www.tensorflow.org/versions/master/experimental/xla/tfcompile) on how to use AOT compilation. My graph is made by calling [make_test_graphs.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/aot/tests/make_test_graphs.py) and I used [test_graph_tfmatmul.config.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/aot/tests/test_graph_tfmatmul.config.pbtxt) as my config file. I failed at '**Step 2: Use tf_library build macro to compile the subgraph**'. 
Here is the error message:
error:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: bazel-out/local-opt/genfiles/test_aot/test_graph_tfmatmul.o is not an object file (not allowed in a library)

However, if I `bazel build` the same `tf_library` on a GCE instance, it compiles successfully. The only difference is that the Tensorflow on my GCE instance is cuda enabled. I think there may be a bug in AOT compilation in CPU-only mode.

### Environment info
Operating System: macOS 10.12
Processor: intel 'haswell'.
Tensorflow version: 1.0.1 stable release
bazel version: 0.4.4

**Comment by tatatodd** [comment]
@xuehanxiongsc Instead of writing your own bazel file, perhaps you can try using one of the existing tests.  E.g.:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/aot/tests/BUILD#L118

So try something like this:

$ bazel test tensorflow/compiler/aot/tests:tfcompile_test

Can you report back what results you get from this?  If there is a problem, I'm suspecting it's more likely to be a Mac vs. linux issue, rather than a CPU vs. GPU issue.

**Comment by xuehanxiongsc** [comment]
@tatatodd Here is the log:

exec ${PAGER:-/usr/bin/less} "$0" || exit 1
\-----------------------------------------------------------------------------
Running main() from test_main.cc
[==========] Running 8 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 8 tests from TFCompileTest
[ RUN      ] TFCompileTest.Add
dyld: lazy symbol binding failed: Symbol not found: ___tensorflow_compiler_aot_tests__test_graph_tfadd
  Referenced from: /private/var/tmp/_bazel_xuehan.xiong/4f4d45e6f5aaa2c03c85228dc2ff01af/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/compiler/aot/tests/tfcompile_test.runfiles/org_tensorflow/tensorflow/compiler/aot/tests/tfcompile_test
  Expected in: flat namespace

dyld: Symbol not found: ___tensorflow_compiler_aot_tests__test_graph_tfadd
  Referenced from: /private/var/tmp/_bazel_xuehan.xiong/4f4d45e6f5aaa2c03c85228dc2ff01af/execroot/tensorflow/bazel-out/local-opt/bin/tensorflow/compiler/aot/tests/tfcompile_test.runfiles/org_tensorflow/tensorflow/compiler/aot/tests/tfcompile_test
  Expected in: flat namespace

external/bazel_tools/tools/test/test-setup.sh: line 123: 58107 Abort trap: 6           "${TEST_PATH}" "$@"

**Comment by tatatodd** [comment]
@xuehanxiongsc I'm assuming that's when run on your Mac?

Now that I think about it, AOT won't work at all.  At a minimum we'll need to add the appropriate LLVM target triple for mac; the default is `x86_64-pc-linux` which won't work:

https://github.com/tensorflow/tensorflow/blob/882e75db49f09afac6aee5cd38798a82f80f5419/tensorflow/compiler/aot/tfcompile.bzl#L277

I seem to recall a few other problems wrt Mac builds too.  I don't actually have a Mac, but contributions to get this working are definitely welcome!

**Comment by xuehanxiongsc** [comment]
@tatatodd You are right. It is related to macOS. I just compiled successfully on Linux without cuda support.

**Comment by girving** [comment]
XLA isn't yet supported beyond Linux.  Hopefully this will work eventually, but closing to reduce bug tracker clutter.
