### ISSUE TITLE
Invalid argument: No OpKernel was registered to support Op 'Add' with these attrs.

### ISSUE THREAD

**Issue by darkstarslyp** [tensorflow/tensorflow#8486]
### Environment info
Operating System:

Mac 

 I hava look Mobile and Embedded TensorFlow (TensorFlow Dev Summit 2017) video on yotube.

In the video , I hava learn some function to reduce tensorflow so file size on Android.

I do here
```
Prints a header file to be used with SELECTIVE_REGISTRATION.

Example usage:
print_selective_registration_header \
--graphs=path/to/graph.pb > ops_to_register.h

Then when compiling tensorflow, include ops_to_register.h in the     include
 search path and pass -DSELECTIVE_REGISTRATION  - see
 core/framework/selective_registration.h for more details.
```

the *.pb file is myself , then I get the ops_to_register.h file here

```c++
  #ifndef OPS_TO_REGISTER
  #define OPS_TO_REGISTER
  constexpr inline bool ShouldRegisterOp(const char op[]) {
      return false
     || (strcmp(op, "Add") == 0)
     || (strcmp(op, "Const") == 0)
     || (strcmp(op, "Conv2D") == 0)
     || (strcmp(op, "Exp") == 0)
     || (strcmp(op, "Identity") == 0)
     || (strcmp(op, "Max") == 0)
     || (strcmp(op, "MaxPool") == 0)
     || (strcmp(op, "NoOp") == 0)
     || (strcmp(op, "Placeholder") == 0)
     || (strcmp(op, "RealDiv") == 0)
     || (strcmp(op, "Relu") == 0)
     || (strcmp(op, "Reshape") == 0)
     || (strcmp(op, "Sub") == 0)
     || (strcmp(op, "Sum") == 0)
     || (strcmp(op, "_Recv") == 0)
     || (strcmp(op, "_Send") == 0)
     ;
    }
  #define SHOULD_REGISTER_OP(op) ShouldRegisterOp(op)

  const char kNecessaryOpKernelClasses[] = ","
"BinaryOp< CPUDevice, functor::add<float>>,"
"ConstantOp,"
"Conv2DOp<CPUDevice, float>,"
 "UnaryOp< CPUDevice, functor::exp<float>>,"
  "IdentityOp,"
 "ReductionOp<CPUDevice, float, Eigen::internal::MaxReducer<float>>,"
"MaxPoolingOp<CPUDevice, float>,"
 "NoOp,"
  "PlaceholderOp,"
 "BinaryOp< CPUDevice, functor::div<float>>,"
  "ReluOp<CPUDevice, float>,"
"ReshapeOp,"
"BinaryOp< CPUDevice, functor::sub<float>>,"
 "ReductionOp<CPUDevice, float, Eigen::internal::SumReducer<float>>,"
 "RecvOp,"
"SendOp,"
 ;
#define SHOULD_REGISTER_OP_KERNEL(clz)            
   (strstr(kNecessaryOpKernelClasses, "," clz ",") != nullptr)

 #define SHOULD_REGISTER_OP_GRADIENT false
 #endif
```

I put ops_to_register.h in tensorflow/tensorflow/core/framework dir.

then I do:   

`bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so    --crosstool_top=//external:android/crosstool    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain    --cpu=armeabi-v7a    --copt="-DSELECTIVE_REGISTRATION"`

In my android studio project , initializeTensorFlow() My slef .pb file ,but I got the error:

```
tensorflow_inference_jni.cc:145 Could not create TensorFlow graph: Invalid argument: No OpKernel was registered to support Op 'Add' with these attrs.  Registered devices: [CPU], Registered kernels:
            <no registered kernels>

          	 [[Node: add_1 = Add[T=DT_FLOAT](Conv2D, Reshape)]]
```

**Comment by darkstarslyp** [comment]
can someone help me solve the problem ?

My android phone is meizu MX6.

**Comment by skye** [comment]
@cwhipkey can you take a look at this?

**Comment by cwhipkey** [comment]
One cause of this we've seen before is when the host compiler, that made ops_to_register.h, differs from the compiler used for the device.  The difference we saw was in handling of whitespace in kernel names.

In your case, you could try changing the ops_to_register.h to remove the space before CPUDevice where it occurs, e.g.:
`  BinaryOp< CPUDevice, functor::add<float>>`
becomes
`  BinaryOp<CPUDevice, functor::add<float>>`

and see if that helps.

This problem is fixed in the master branch - the generated ops_to_register.h uses functions that compare the kernel names ignoring whitespace differences.

**Comment by darkstarslyp** [comment]
thanks your suggetion , I got the  right reesult. @cwhipkey
