### ISSUE TITLE
Tools for generating the website is not available in this public github repo 

### ISSUE THREAD

**Issue by 5onion** [tensorflow/tensorflow#8490]
Could the website generator tools for tensorflow.org be changed to  open source tools here. It will be good and appreciated!
Many people want to get the offline version of tensorflow documentation, not only the API documentation, I think they can use the  tools to generate the website from markdown files, and  to offline html files. It will be helpful.
And I think if the tool become a open source tool. It will be more useful and powerful.  thanks:)

**Comment by concretevitamin** [comment]
@martinwicke

**Comment by martinwicke** [comment]
Everything up to conversion to markdown is already open-source, you can easily generate html from that using hoedown or other md interpreters (tools/docs).

For the "last mile" we use an internal system, and we will not try to replace it with an open-source version.
