### ISSUE TITLE
Gradient by a function issue

### ISSUE THREAD

**Issue by m9ra** [tensorflow/tensorflow#8492]
I find out an inconsistency in tf.gradients function.

```
import tensorflow as tf

x = tf.get_variable("x", shape=(1,))
x2 = x * 2
x4_issue = (x * 2) * 4
x4 = x2 * 4

issue_grads = tf.gradients(x4_issue, x2)[0]
grads = tf.gradients(x4, x2)[0]

print issue_grads
print grads
```

 I would expect the two prints have the same output because the expressions are equivalent.
However, output that I'm getting is following:

```
None
Tensor("gradients_1/mul_3_grad/Reshape:0", shape=(1,), dtype=float32)
```

**Comment by concretevitamin** [comment]
This is expected behavior.  On `x2 = x * 2`, TensorFlow inserted a `Mul` node into the current graph.  On the subsequent `... = (x * 2) ...`, TF inserted yet another new `Mul` node.  In other words, tensor `x4_issue` does not depend on `x2` in anyway.
