### ISSUE TITLE
Segfault: "Check failed: num_elements_ <= kMaxElements"

### ISSUE THREAD

**Issue by untom** [tensorflow/tensorflow#8494]
I'm running the current nightly build as of today (2017-03-17). I'm working with very large, sparse matrices, and my program seems to have hit a variable overflow. It crashed with the following log entry:

    2017-03-17 10:48:34.554715: F tensorflow/core/framework/tensor_shape.cc:212] Check failed: num_elements_ <= kMaxElements (1141286132736 vs. 1099511627776)
    Aborted (core dumped)

I'm guessing this is because my sparse matrix is too large to handle for tensorflow. It would be great if this could somehow be fixed. Please refer to #7783 for more details about my code (that was another overflow issue I encountered).

**Comment by skye** [comment]
Looks like we can just bump that limit up, I'll work on getting that checked in.

**Comment by skye** [comment]
@girving beat me to it. There's a patch in review, one of us will update this issue once it's checked in.

**Comment by skye** [comment]
https://github.com/tensorflow/tensorflow/commit/986d337e7da04de627218c12e20be1e3abbf6097 should address this. Please let us know if you still have problems, thank!
