### ISSUE TITLE
[Feature request] np.random.choice analogue

### ISSUE THREAD

**Issue by persiyanov** [tensorflow/tensorflow#8496]
TF has no analogue to `np.random.choice` function that chooses random element from tensor (optionally according to provided probabilities). It's especially useful in RL problems when you use epsilon-greedy exploration strategy.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
[These](http://stackoverflow.com/questions/41123879/numpy-random-choice-in-tensorflow) [two](http://stackoverflow.com/questions/37757986/weighted-random-tensor-select-in-tensorflow) solve the problem using `tf.multinomial`, but maybe it will be convenient to include `tf.random_choice` in TF API?

It could be implemented through `tf.multinomial` , for example.

**Comment by persiyanov** [comment]
Ah, actually there is also no way to generate random samples for length of `batch_size` when it's not specified until runtime.

Btw, using `RandomStreams` in `theano` allows to do that.

**Comment by concretevitamin** [comment]
I'm not aware of anyone working on this.  We'd happily take a contribution!  (It likely should go into `contrib` as the first cut.)

**Comment by persiyanov** [comment]
@concretevitamin I will prepare pull request. Is it okay to implement this using `tf.multinomial` or should I implement new op for this?

**Comment by concretevitamin** [comment]
I think implementing in terms of existing ops is fine.

@aselle - do you have a suggestion on where to put such the numpy counterparts in contrib?  If not, I'm tempted to say it's okay to go into `random_ops.py`.

**Comment by concretevitamin** [comment]
(Also /cc @ebrevdo to see if `tf.contrib.distribution` has any files that could host this.)

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by xhhszc** [comment]
I want to know if the tf.random_choice was done? But I can't find the python files in contrib/distributions/python/ops/.  And I really want it....

**Comment by nrhine1** [comment]
Here's an implementation for uniform sampling with replacement along a specific axis (untested).

```
def random_choice(a, axis, samples_shape=None):
    """

    :param a: tf.Tensor
    :param axis: int axis to sample along
    :param samples_shape: (optional) shape of samples to produce. if not provided, will sample once.
    :returns: tf.Tensor of shape a.shape[:axis] + samples_shape + a.shape[axis + 1:]
    :rtype: 

    Examples:
    >>> a = tf.placeholder(shape=(10, 20, 30), dtype=tf.float32)
    >>> random_choice(a, axis=0)
    <tf.Tensor 'GatherV2:0' shape=(1, 20, 30) dtype=float32>
    >>> random_choice(a, axis=1)
    <tf.Tensor 'GatherV2_1:0' shape=(10, 1, 30) dtype=float32>
    >>> random_choice(a, axis=1, samples_shape=(2, 3))
    <tf.Tensor 'GatherV2_2:0' shape=(10, 2, 3, 30) dtype=float32
    >>> random_choice(a, axis=0, samples_shape=(100,))
    <tf.Tensor 'GatherV2_3:0' shape=(100, 20, 30) dtype=float32>
    """
    
    if samples_shape is None:
        samples_shape = (1,)
    shape = tuple(a.get_shape().as_list())
    dim = shape[axis]
    choice_indices = tf.random_uniform(samples_shape, minval=0, maxval=dim, dtype=tf.int32)
    samples = tf.gather(a, choice_indices, axis=axis)
    return samples
```

**Comment by MiladShahidi** [comment]
This worked for me. It returns both the sampled values and their indices in the original tensor:

```
def random_choice(x, size, axis=0, unique=True):
    dim_x = tf.cast(tf.shape(x)[axis], tf.int64)
    indices = tf.range(0, dim_x, dtype=tf.int64)
    sample_index = tf.random.shuffle(indices)[:size]
    sample = tf.gather(x, sample_index, axis=axis)

    return sample, sample_index

```

**Comment by oonisim** [comment]
```
    def random_choice(a, size):
        """Random choice from 'a' based on size without duplicates
        Args:
            a: Tensor
            size: int or shape as tuple of ints e.g., (m, n, k).
        Returns: Tensor of the shape specified with 'size' arg.

        Examples:
            X = tf.constant([[1,2,3],[4,5,6]])
            random_choice(X, (2,1,2)).numpy()
            -----
            [
              [
                [5 4]
              ],
              [
                [1 2]
              ]
            ]
        """
        if isinstance(size, int) or np.issubdtype(type(a), np.integer) or (tf.is_tensor(a) and a.shape == () and a.dtype.is_integer):
            shape = (size,)
        elif isinstance(size, tuple) and len(size) > 0:
            shape = size
        else:
            raise AssertionError(f"Unexpected size arg {size}")

        sample_size = tf.math.reduce_prod(size, axis=None)
        assert sample_size > 0

        # --------------------------------------------------------------------------------
        # Select elements from a flat array
        # --------------------------------------------------------------------------------
        a = tf.reshape(a, (-1))
        length = tf.size(a)
        assert sample_size <= length

        # --------------------------------------------------------------------------------
        # Shuffle a sequential numbers (0, ..., length-1) and take size.
        # To select 'sample_size' elements from a 1D array of shape (length,),
        # TF Indices needs to have the shape (sample_size,1) where each index
        # has shape (1,),
        # --------------------------------------------------------------------------------
        indices = tf.reshape(
            tensor=tf.random.shuffle(tf.range(0, length, dtype=tf.int32))[:sample_size],
            shape=(-1, 1)   # Convert to the shape:(sample_size,1)
        )
        return tf.reshape(tensor=tf.gather_nd(a, indices), shape=shape)
```
```
X = tf.constant([[1,2,3,4,5,6]])
print(random_choice(X, 2).numpy())
-----
[2 5]

X = tf.constant([[1,2,3],[4,5,6]])
print(random_choice(X, (2,2,1)).numpy())
-----
[[[5]
  [4]]

 [[1]
  [2]]]
```

**Comment by Antymon** [comment]
`tf.random.uniform_candidate_sampler`

**Comment by richardwhitehead** [comment]
> This worked for me. It returns both the sampled values and their indices in the original tensor:
> 
> ```
> def random_choice(x, size, axis=0, unique=True):
>     dim_x = tf.cast(tf.shape(x)[axis], tf.int64)
>     indices = tf.range(0, dim_x, dtype=tf.int64)
>     sample_index = tf.random.shuffle(indices)[:size]
>     sample = tf.gather(x, sample_index, axis=axis)
> 
>     return sample, sample_index
> ```

This is very useful, thank you, but note that the `unique` parameter s not used.
