### ISSUE TITLE
Upgrade Protobuf

### ISSUE THREAD

**Issue by Nayana-ibm** [tensorflow/tensorflow#8498]
We are building TensorFlow master using bazel on 64 bit platform.

We need a fix for 64 bit platform as mentioned in #1044 in `tensorflow/third_party/protobuf/3.0.0/src/google/protobuf/stubs/atomicops_internals_generic_gcc.h`. 

This fix is available in protobuf with commit id [c59473d ](https://github.com/google/protobuf/commit/c59473d53eafadd126502657e5c5c33e952b67ed)or higher.
Will it be possible to pick this or higher commit of protobuf in TensorFlow?

**Comment by Nayana-ibm** [comment]
Reference: [#4380](https://github.com/tensorflow/tensorflow/issues/4380)

**Comment by byronyi** [comment]
Your original reference "#1044" should point to the one in [protobuf](https://github.com/google/protobuf/pull/1044). And I am confused of the "64 bit platform" you were referring to, until I notice it is probably `mips64`. It would be better if you could make that clear, as current master has no problem building on `x86-64`.

**Comment by Nayana-ibm** [comment]
We were getting this issue for s390x platform.
However, I have cloned the code again and now, I could build TensorFlow without any error.
Closing this issue.
