### ISSUE TITLE
iOS - No OpKernel was registered to support Op 'ExtractImagePatches' with these attrs

### ISSUE THREAD

**Issue by eweill** [tensorflow/tensorflow#8502]
Hi everyone,

I am trying to load a graph inside iOS that was generated by another software into a .pb file.  It was tested on a Ubuntu machine, so I know the model works correctly.
When trying to use it with iOS, the project builds correctly and then I have the following error:

```
Could not create TensorFlow Graph: Invalid argument: No OpKernel was registered to support Op 'ExtractImagePatches' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: ExtractImagePatches = ExtractImagePatches[T=DT_FLOAT, ksizes=[1, 2, 2, 1], padding="VALID", rates=[1, 1, 1, 1], strides=[1, 2, 2, 1]](concat)]]
```

I know other issues have been posted related to this; however I was unable to locate a solution.

I am using TensorFlow 1.0.1 and Python 3.6.0
I can run the iOS examples with no problem.

iOS seems not to be able to find `ExtractImagePatches` Op.

If anyone could help with this issue, it would be greatly appreciated.

**Comment by concretevitamin** [comment]
By default, the iOS build target doesn't link in `core/kernels:extract_image_patches_op`.  Can you try to modify your `BUILD` file and explicitly link this in?

**Comment by eweill** [comment]
@concretevitamin Which `BUILD` file should I modify?  The `BUILD` file in `tensorflow/tensorflow` or `tensorflow/tensorflow/core`?

After I modify the correct file, how shall I rebuild?  Will I need to run `build_all_ios.sh` script?

Thanks for your help.

**Comment by concretevitamin** [comment]
I'm adding one of our iOS experts @satok16 to further advise.  (Thanks Satoshi!)

**Comment by satok16** [comment]
To build binaries for iOS, you need to use "build_all_ios.sh" which builds targets by make instead of bazel.  As this process doesn't use BUILD file, you should add kernel c++ files into "[tf_op_files.txt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/tf_op_files.txt)".

**Comment by eweill** [comment]
@satok16 
Thanks.  After adding the kernel for extract_image_patches to `tf_op_files.txt`, I was able to compile successfully; however I am still running into problems with the iOS demo.

I am trying to use the camera demo provided and modify it for object detection instead of object classification.  Is there a tutorial for this anywhere online that I could follow or that you could point me to?

Thanks.

**Comment by satok16** [comment]
I'm not pretty sure that there is any tutrial for them other than https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android

Andrew, do you have any idea about this?

**Comment by andrewharp** [comment]
@petewarden has a nice iOS walkthrough here: https://petewarden.com/2016/09/27/tensorflow-for-mobile-poets/amp/

**Comment by satok16** [comment]
As we have Pete's great post, let's close this issue for now.  Feel free to create a new ticket if you have any other issues.

Thanks!
