### ISSUE TITLE
Cannot reuse variables by tf.layers.conv2d

### ISSUE THREAD

**Issue by zuoxingdong** [tensorflow/tensorflow#8504]
I am trying to make two conv layers share the same weights, however, it seems the API does not work. 
```
import tensorflow as tf

x = tf.random_normal(shape=[10, 32, 32, 3])

conv1 = tf.layers.conv2d(x, 3, [2, 2], padding='SAME', reuse=None, name='conv')
print(conv1.name)
conv2 = tf.layers.conv2d(x, 3, [2, 2], padding='SAME', reuse=True, name='conv')
print(conv2.name)
```

gives

```
conv/BiasAdd:0
conv_2/BiasAdd:0
```

--------------------------------Update-------------------------------
According to a [post](https://stackoverflow.com/questions/42862300/tensorflow-reuse-variable-with-tf-layers-conv2d), the weights are already sharing, with different layer names, since the computation not sharing. However, is it feasible to consider a better naming strategy so that it is easier to see from names that different layers are sharing the same weights ?

**Comment by zuoxingdong** [comment]
@ebrevdo Thanks for your PR. I have a short question 

```
with tf.variable_scope('new_scope'):
    ker = tf.get_variable('kernel', [5, 6])
    fc1 = tf.layers.dense(inputs=tf.constant(np.random.randn(3, 4, 5)), units=3, **reuse=None**)
    fc2 = tf.layers.dense(inputs=tf.constant(np.random.randn(3, 4, 5)), units=3, **reuse=True**)
```

With the new behavior, will `fc2` reuse the weights from `fc1` or from `ker` ?
Because previously the weight sharing should be 
```
with tf.variable_scope('new_scope'):
    fc1 = tf.layers.dense(inputs=tf.constant(np.random.randn(3, 4, 5)), units=3, **reuse=None**)
    fc2 = tf.layers.dense(inputs=tf.constant(np.random.randn(3, 4, 5)), units=3, **reuse=True**)
```

**Comment by ebrevdo** [comment]
I accidentally introduced a bug.  It *should* reuse the weights from fc1,
but i accidentally made it reuse the weights from ker.  i'm sending an
update to reverse this behavior.

**Comment by ebrevdo** [comment]
Fix should be in.
