### ISSUE TITLE
Expose feature importances in TensorForestEstimator

### ISSUE THREAD

**Issue by ekerazha** [tensorflow/tensorflow#8508]
TensorForestEstimator can log/print feature importances but they are not accessible.

Could you expose a feature_importances property in TensorForestEstimator or expose the graph builder object instantiated by it so we can access the feature_importances() method?

**Comment by concretevitamin** [comment]
@gilberthendry could you take a look?

**Comment by gilberthendry** [comment]
feature importances are currently calculated with a TF graph, so can't really expose as a property or a function in the estimator, it only makes sense in the context of a tf.Session (which only exists during training or eval, which is controlled under the hood of estimators).  One option is to include it as an eval metric, would that be ok?

**Comment by ekerazha** [comment]
Sounds good to me

**Comment by gilberthendry** [comment]
I've added support to get feature importances during inference/eval time.  It should make its way into the nightly build shortly, and an unknown amount of time into an official TF release.   You can just pass report_feature_importances to the estimator=True, and add an eval metric such as:
tf.contrib.learn.metric_spec.MetricSpec(
          lambda x: x,
          prediction_key=eval_metrics.FEATURE_IMPORTANCE_NAME)

**Comment by girving** [comment]
From the comments, it sounds like this is done.  Please close issues once they are done.

**Comment by pjhinton** [comment]
> I've added support to get feature importances during inference/eval time. It should make its way into the nightly build shortly, and an unknown amount of time into an official TF release. You can just pass report_feature_importances to the estimator=True, and add an eval metric such as:
> tf.contrib.learn.metric_spec.MetricSpec(
> lambda x: x,
> prediction_key=eval_metrics.FEATURE_IMPORTANCE_NAME)

I was looking at the comments in this issue to determine if this functionality was available in the version of TensorFlow that I am using (r1.12).  I notice that the string constant `FEATURE_IMPORTANCE_NAME` is defined in `tensorflow/contrib/tensor_forest/client/eval_metrics.py`, but the code that uses this constant in `tensorflow/contrib/tensor_forest/client/random_forest.py` is not.  Is this a case where the commit in 5c21d55000c03a90281880f0eb55b12fcaa528fe was only partially merged into master?
