### ISSUE TITLE
Documentation for serving canned estimators

### ISSUE THREAD

**Issue by dale-cooper** [tensorflow/tensorflow#8511]
Hey, 

the documentation on how to serve canned estimators with tensorflow serving is somewhat confusing. The docstring for export_savedmodel says to provide a function returning an InputFnOps which isn't documented anywhere. In the source it says it moved to estimator/export.py and InputFnOps was renamed to ServingInputReceiver. ~~However, this does not exist at all.~~ [I might have been confused by multiple checked out versions here, I suppose]

Digging around in the tests for estimator it all is becoming a bit clearer but it would be great if there were more documentation on this topic (also from the serving side as I now have my model exported but cannot get any predictions out of it :( )

Thanks!

Christian

Mentions @martinwicke and @ispirmustafa

**Comment by dale-cooper** [comment]
Hey,

I'd really appreciate an answer here, as the integration between tensorflow and tensorflow serving is not really working for me. I have installed the latest python distribution with pip which says it's version 1.0.1. This version does not contain estimator/export.py so I will not be confused again by what is there and what isn't.

I've created my model and exported it with export_savedmodel and this seems to be served just fine (except of course, there's no way to see what serving serves).

I used the following code to create the input function

```
from tensorflow.contrib.layers.python.layers import feature_column as feature_column_lib

feature_columns = [
      feature_column_lib.real_valued_column(
          'pred_me', dimension=1)
  ]
feature_spec = feature_column_lib.create_feature_spec_for_parsing(
      feature_columns)

serving_input_fn = tf.contrib.learn.utils.build_parsing_serving_input_fn(feature_spec)
```

To call this the documentation says something about tf.Examples which are nowhere defined (except inside the proto files) but I suppose this was not the right function to use. There's also build_default_serving_input_fn which would seem to be the right function to use for me but I cannot get this to work either as it is not too clear what the input should be.

I did some digging around and came up with this code

```from tensorflow.python.framework import constant_op

feature_spec = {'pred_me': constant_op.constant([2.0])}
serving_input_fn = tf.contrib.learn.utils.input_fn_utils.build_default_serving_input_fn(feature_spec)```

which comes from the documentation (well test) of a newer code base and actually uses the renamed function build_raw_serving_input_receiver_fn. But this comes back with an exception: **ValueError: 'Const_19:0' is not a valid scope name** which kind of makes sense because within build_raw_serving_input_receiver_fn there's code that transforms the tensor's name like this 

```# Reuse the feature tensor name for the placeholder, excluding the index
      placeholder_name = t.name.split(':')[0]```

which is missing in the originial tf.contrib.learn.utils.input_fn_utils.build_default_serving_input_fn

```features_placeholders[name] = array_ops.placeholder(dtype=t.dtype,
                                                          shape=shape,
                                                          name=t.name)
```

So is this just a bug in the old library still distributed with pip or how is this supposed to work.

I really do appreciate what you are doing here but this really needs some clarification.

chris

**Comment by ispirmustafa** [comment]
@davidsoergel could you please take a look?

**Comment by MtDersvan** [comment]
Any progress on this? I am having the same issue.

**Comment by MtDersvan** [comment]
There is a related thread https://github.com/tensorflow/serving/issues/228#issuecomment-300146926 where I provided a solution.
I think I figured it out, I'm not sure how orthodox my solution is, but at least it works for me.

A lot of people try to use canned estimators right now (especially wide and deep one), but because there is no documentation majority is confused.

I'd be willing to contribute if help is welcome.

**Comment by martinwicke** [comment]
@MtDersvan: pending review by @dr4b @wolffg we'll be very excited to have the your tutorial and publish it on tensorflow.org.

**Comment by hadim** [comment]
I am also fighting with the API to be able to save a model + weights from an `Estimator` and then do prediction elsewhere (without necessarily using TF Serving). See here for details: http://stackoverflow.com/questions/43966073/prediction-from-model-saved-with-tf-estimator-estimator-in-tensorflow

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Comment by martinwicke** [comment]
Additional information: we're moving canned estimators to core and
documentation will be part of that.

**Comment by cornellgit** [comment]
Still no good documentation ons serving and monitoring. I think this bug need to be reopened.

**Comment by dr4b** [comment]
Have you seen https://www.tensorflow.org/serving/ ?

**Comment by unitive-jim** [comment]
I'm trying to write a C++ application that loads a SavedModel and feeds it tensors in the same process. I'm using Tensorflow 1.4 and it seems to me that there is still too little documentation on how to do this. The documentation at https://www.tensorflow.org/programmers_guide/saved_model comes close, but should have an example using build_raw_serving_input_receiver_fn() in Python and then show how to feed the data in C++.

**Comment by martinwicke** [comment]
The source for that guide is in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/programmers_guide/saved_model.md

If you send a PR, we can add such an example. I think it would be helpful.

**Comment by mingruic123** [comment]
I hope the tutorial of serving an estimator can have a complete example for new users to understand and try. At the end, it says to refer to more examples but the git repository does not have any examples of how to serve an estimator (especially the pre-made estimators).

**Comment by burui11087** [comment]
NEED MORE TUTORIALS OF SERVING
