### ISSUE TITLE
ImportError: cannot import name 'moving_averages' 

### ISSUE THREAD

**Issue by UkiDLucas** [tensorflow/tensorflow#8513]
I have a fresh install on AWS EC2 p2.xlarge.

The TensorFlow install method was pip:
```
conda list  | grep -E "keras|teano|tensorflow"
tensorflow-gpu            1.0.1                     <pip>
```

Here is the error:
```
/home/ubuntu/anaconda3/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py in <module>()
      1 import tensorflow as tf
----> 2 from tensorflow.python.training import moving_averages
      3 from tensorflow.python.ops import tensor_array_ops
      4 from tensorflow.python.ops import control_flow_ops
      5 from tensorflow.python.ops import functional_ops

ImportError: cannot import name 'moving_averages'
```
Thank you for your support!

**Comment by UkiDLucas** [comment]
The issue can be closed.

Reinstalling with following helped (I passed this particular place).
`pip3 install --upgrade --ignore-installed tensorflow-gpu`

tensorflow-gpu            1.0.1                     <pip>

**Comment by pGit1** [comment]
@UkiDLucas  THANK YOU!!!

I just installed some trash code from github and it broke my codebase entirely. Using this fixed everything along with sourcing my bashrc file.

**Comment by niteshcs113** [comment]
Using TensorFlow backend.
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import keras
  File "C:\Users\pc\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import activations
  File "C:\Users\pc\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\activations.py", line 3, in <module>
    from . import backend as K
  File "C:\Users\pc\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\backend\__init__.py", line 64, in <module>
    from .tensorflow_backend import *
  File "C:\Users\pc\AppData\Local\Programs\Python\Python35\lib\site-packages\keras\backend\tensorflow_backend.py", line 2, in <module>
    from tensorflow.python.training import moving_averages
ImportError: cannot import name 'moving_averages'

Same issue while i had sucessfully installed tensorflow-cpu, keras and theano but it's throwing error while importing keras...

Is there any solution for that.?
