### ISSUE TITLE
caffe/tensorflow/mxnet: converter from python to c++

### ISSUE THREAD

**Issue by chakpongchung** [tensorflow/tensorflow#8514]
https://github.com/rmekdma/python_misc/blob/master/caffe/caffe_ftr.py

I need to do some system integration in C++. Given the above caffe code,

how can I track the C++ code being used behind each caffe/tensorflow/mxnet function in python?

Can I generate the C++ code so that I can compile and run?

What is the python wrapper used by caffe/tensorflow/mxnet? ctype, boot:python or swig?

Similarly, it will be interesting to know whether I can do the same from python to c++ in tensorflow , mxnet or other python binding code, if it is easier to do it in tensorflow.

http://stackoverflow.com/questions/42869355/caffe-tensorflow-mxnet-how-to-convert-python-to-c

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there. Thanks!
