### ISSUE TITLE
tf.contrib.seq2seq Documentation

### ISSUE THREAD

**Issue by axelsly** [tensorflow/tensorflow#8518]
Where can I find documentation for `tf.contrib.seq2seq`?

I get a 404 error on [attention_decoder_fn.py].(https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/seq2seq/python/ops/attention_decoder_fn.py)

Namely, I want to hack the `attention_decoder_fn_inference` or `dynamic_rnn_decoder` function during inference in order to sample the outputs of each cell based on output probabilities before feeding into the new cell. The aforementioned functions seem to be a black box that predict the most probable class at each cell.

Thanks

**Comment by concretevitamin** [comment]
The file's been deleted in master branch.  In general, I'd suggest if you're working on master, just peek into the actual source files for the latest consistent set of docs.

**Comment by jinfagang** [comment]
I think it move into `attention_decoder_fn_inference` or something else?
