### ISSUE TITLE
error while building tensorflow from source

### ISSUE THREAD

**Issue by prakashyadav008** [tensorflow/tensorflow#8519]
_I am trying to install tensorflow from source and getting this error while building tensorflow from bazel using the command:_ 

`bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
`
_and the error is:_

`ERROR: /home/prakash/.cache/bazel/_bazel_prakash/8d51bbac70ad4d48b6548f0de307c16b/external/nccl_archive/BUILD.bazel:33:1: error while parsing .d file: /home/prakash/.cache/bazel/_bazel_prakash/8d51bbac70ad4d48b6548f0de307c16b/execroot/tensorflow/bazel-out/local_linux-py3-opt/bin/external/nccl_archive/_objs/nccl/external/nccl_archive/src/reduce.cu.pic.d (No such file or directory).

nvcc fatal   : Unsupported gpu architecture 'compute_21'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 360.810s, Critical Path: 345.61s`

_I have a Nvidia 720M graphic chip on my laptop is that causing the issue .? any advice would be helpful.
the configuration i did was this:_

`prakash@prakash008:~/Downloads/tensorflow$ ./configure 
Please specify the location of python. [Default is /home/prakash/anaconda3/bin/python]: 
Please specify optimization flags to use during compilation [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? (Linux only) [Y/n] n
jemalloc disabled on Linux
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] n
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] n
No XLA JIT support will be enabled for TensorFlow
Found possible Python library paths:
  /home/prakash/anaconda3/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/home/prakash/anaconda3/lib/python3.6/site-packages]

Using python library path: /home/prakash/anaconda3/lib/python3.6/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] n
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5
Please specify the location where cuDNN 5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 3.5,2.1`

**Comment by skye** [comment]
The compute capability of your graphics card is lower than TensorFlow supports. Please see https://github.com/tensorflow/tensorflow/issues/25#issuecomment-156234658 for a possible workaround.

**Comment by liuhuan-gl** [comment]
请问解决了吗
