### ISSUE TITLE
Add new Tensorflow Udacity Course too the main Readme or Readme in master/tensorflow/examples/udacity

### ISSUE THREAD

**Issue by PatrickChrist** [tensorflow/tensorflow#852]
Dear Tensorflow-Team,

please add a link of the new Tensorflow Udacity course to your Readme and Docs.
https://www.udacity.com/course/deep-learning--ud730

Thanks and best Wishes,
Patrick

**Comment by vigneshstack** [comment]
+1

**Comment by vincentvanhoucke** [comment]
PR #853 merged
