### ISSUE TITLE
Asking for TF's official implementation of the inception v3 model's distributed training

### ISSUE THREAD

**Issue by Dav-Jay** [tensorflow/tensorflow#8524]
From the recorded video of TF dev summit held about one month ago, I got to know the newest distributed TF 1.0 is able to achieve 57x speed up for the inception v3 model on a server of 8 nodes/ 8 gpus and the codes will be released. Since I am far away from getting such a good scaling performance using my own distributed implementation, I have been looking forward to seeing and studying from the training codes from TF. Could anyone tell me the progress now? Thanks!

**Comment by ppwwyyxx** [comment]
duplicate of https://github.com/tensorflow/tensorflow/issues/7679

**Comment by Dav-Jay** [comment]
@ppwwyyxx sorry, I didn't notice that thread. This one can be closed.
