### ISSUE TITLE
Tensorflow first time run error.

### ISSUE THREAD

**Issue by poojan124** [tensorflow/tensorflow#8525]
I installed tensorflow throuh pip3 in windows. And it installed successfully.
Then i run a simple program to check if it is working or not. I got this error.
Python version 35. 
CODE :  
```
import tensorflow as tf  
hello = tf.constant('Hello, TensorFlow!')  
sess = tf.Session()  
print(sess.run(hello))
```  

Output :

> E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') fo
r unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_t
ype: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"')
 for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for
unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_ty
pe: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"')
for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"'
) for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') fo
r unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') fo
r unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"
') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core
\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "C
PU"') for unknown op: UpdateFertileSlots
b'Hello, TensorFlow!'

**Comment by skye** [comment]
Are you running the latest version of TensorFlow?

Regardless, if you look at the bottom after the "unknown op" messages, it is printing the expected result: `b'Hello, TensorFlow!'` It looks like you're only missing ops for building decision trees, so you should still be able to run (most) TensorFlow models successfully.

**Comment by poojan124** [comment]
@skye Yes I am running latest version of tensorflow on python 3.5.2 . You know any way to get rid of those unknown op errors. Thanks for replying..

**Comment by jubjamie** [comment]
@poojan124 iirc they should disappear in 1.0.1. Can you confirm your tensorflow version?

**Comment by poojan124** [comment]
@jubjamie  i am using 1.0.1  version. I used `pip3 install --upgrade tensorflow` command to install on my windows. I will try nightly build if it take out those op errors.

**Comment by gunan** [comment]
Nightly should help with most of those unknown op issues, if not all.
Also, soon 1.1 will be released, which will be similar to nightlies.

**Comment by asimshankar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
