### ISSUE TITLE
configure script shouldn't ask interactive questions when its output isn't a terminal

### ISSUE THREAD

**Issue by yurivict** [tensorflow/tensorflow#8527]
It should use the default values.

**Comment by skye** [comment]
A workaround for now is to use `yes '' | ./configure`. This is equivalent to accepting all the default values.

**Comment by phvu** [comment]
When the default isn't good enough, you can also set the variables before running `./configure`. I used something similar to this to compile TF in Docker:
```
ENV TF_NEED_CUDA=1 \
 GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
 TF_CUDA_VERSION=8.0 \
 CUDA_TOOLKIT_PATH=/usr/local/cuda \
 TF_CUDNN_VERSION=5.1.10 \
 CUDNN_INSTALL_PATH=/usr/local/cuda \
 TF_CUDA_COMPUTE_CAPABILITIES=3.5,3.7,5.2,6.0 \
 CC_OPT_FLAGS="--copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.2 --copt=-mfpmath=both --config=cuda" \
 PYTHON_BIN_PATH="/usr/bin/python" \
 USE_DEFAULT_PYTHON_LIB_PATH=1 \
 TF_NEED_JEMALLOC=1 \
 TF_NEED_GCP=0 \
 TF_NEED_HDFS=0 \
 TF_ENABLE_XLA=0 \
 TF_NEED_OPENCL=0

RUN ./configure && \
  ......
```

**Comment by mharrend** [comment]
I can confirm that @phvu answer is working quite well. Just look through the configure script and you will find many lines like 
`if [ -z "$PYTHON_BIN_PATH" ]; then`
so, it will ask interactively e.g. for the Python path if you do not set the $PYTHON_BIN_PATH variable.

But if you set all the variables, it will work without further asking.
