### ISSUE TITLE
There is a learning_rate parameter in the Adadelta implementation although there isn't such one in the original paper

### ISSUE THREAD

**Issue by eranamar** [tensorflow/tensorflow#8528]
Hi,
I see in the documentation that `tf.train.AdadeltaOptimizer` has a `learning_rate` parameter, but in the original paper that parameter was eliminated from the update rule [see equation 14 in the paper](http://arxiv.org/pdf/1212.5701v1.pdf) (or step 5 in the pseudo code of the algorithm).
Is that a bug in the implementation? 
If you deliberately add a learning_rate parameter, I think that the API documentation should state explicitly that this is NOT the exact implementation of the algorithm as in the paper.

**Comment by skye** [comment]
@Mistobaan could you look at this?

**Comment by aselle** [comment]
To me it looks like with lr==1 you get exactly the paper. @eranamar, could you submit a pull request to that effect, please?

**Comment by eranamar** [comment]
Can you please explain what should I do? (I am new to this...)

**Comment by aselle** [comment]
I will take care of updating the docs.
