### ISSUE TITLE
Add support for non-scalar string tensors in java

### ISSUE THREAD

**Issue by ophiry** [tensorflow/tensorflow#8531]
Currently, string tensors are not supported in java:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/main/java/org/tensorflow/Tensor.java#L90

Implementing this  would be very helpful in scenarios of training a model in one language, and serving from a different one, as it allows moving some of the logic to the tensor flow model.

**Comment by asimshankar** [comment]
I'm under the impression that someone is working on a contribution for this. I'll check in with them to see if they expect to send a PR anytime soon.

**Comment by erranli** [comment]
I completed the implementation of the feature and will contribute it back soon.

**Comment by jan-apptornado** [comment]
Thanks a lot for making this possible. Any idea when "soon" is?

**Comment by quaeler** [comment]
@erranli could you push your fix, or cut this issue loose?

**Comment by asimshankar** [comment]
@quaeler : I had an earlier attempt at this than I can resurrect. I'll do that and hope to have something in the next few days.

**Comment by quaeler** [comment]
@asimshankar ok sounds good; if you want to pass the baton, i'm happy to do the resurrection as well.

**Comment by quaeler** [comment]
Thanks @ebrevdo - any reason not make this into a PR for tensorflow master?

**Comment by ebrevdo** [comment]
Please ignore my commit; this was written by @asimshankar and will show up on master soon.

**Comment by myanything** [comment]
@caisq thank you for making the change. Curious when will the change be published to maven central?

**Comment by asimshankar** [comment]
This is part of 1.4, so is available on Maven Central.
