### ISSUE TITLE
  tf.image.decode_image doesn't return tensor's shape

### ISSUE THREAD

**Issue by TianweiXing** [tensorflow/tensorflow#8551]
I try to use "image.decode_image" to read image file as tensor, but this function returns a tensor without "shape".
As said in the doc:
>  Their input and output are all of variable size. If you need fixed size images, pass the output of the decode Ops to one of the cropping and resizing Ops.
But actually it cannot be passed to resizing op without shape.

Is there a way to use import image as a normal tensor?

Codes: I ran it in ipy notebook
```
fn = '8.png'
image_contents = tf.read_file(fn)
image = tf.image.decode_image(image_contents, channels=1)
image

image.shape

image.eval().shape

img_resize = tf.image.resize_images(image, [28,28])
```
Output:
<tf.Tensor 'decode_image/cond_jpeg/Merge:0' shape=<unknown> dtype=uint8>

TensorShape(None)

(250, 250, 1)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-10-b913c79cb137> in <module>()
----> 1 img_resize = tf.image.resize_images(image, [28,28])

/home/tianwei/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/image_ops_impl.pyc in resize_images(images, size, method, align_corners)
    641   images = ops.convert_to_tensor(images, name='images')
    642   if images.get_shape().ndims is None:
--> 643     raise ValueError('\'images\' contains no shape.')
    644   # TODO(shlens): Migrate this functionality to the underlying Op's.
    645   is_batch = True

ValueError: 'images' contains no shape.

**Comment by inflation** [comment]
Yes, this is bothering. My workaround is using `tf.image.resize_image_with_crop_or_pad` as it said, and maybe manually set shape.

**Comment by TianweiXing** [comment]
@inflation Thanks, it works. But I also noticed that, this function returns a tensor without channel dimension...like this:
```
image_contents = tf.read_file(fn)
image = tf.image.decode_image(image_contents, channels=3)
image = tf.image.resize_image_with_crop_or_pad(image, 250, 250)
image.shape
```
TensorShape([Dimension(250), Dimension(250), Dimension(None)])

**Comment by inflation** [comment]
Yes, that's what I mean manually set it.

**Comment by ppwwyyxx** [comment]
You can use `tf.Tensor.set_shape` if you need a fixed static shape info.

**Comment by MicaelCarvalho** [comment]
Keep in mind everything you're doing is symbolic. Therefore, you cannot know the shape of your supposed image before actually loading it — and this is why the Tensor is "shapeless". Even the last dimension isn't inferrable, because it could be a grayscale image (then third dimension = 1), a colored image (third dimension = 3), a gif (third dimension = 4), or even something else.

As @ppwwyyxx said, you can (1) use set_shape if you know the shape of the tensor/image and want to simplify its usage, this can be used to force the third dimension, if you're sure your images will always be on the same format; (2) manipulate your images with operations that accept symbolic shapes throughout your pipeline, like `tf.reshape`; or (3) split your graph and load the images with a `sess.run` before actually sending them through the rest of the graph, this will allow you to know their exact shape "beforehand" (subject to interpretations).

The symbolic operation to get an image's shape is `tf.shape(x)`.

**Comment by TianweiXing** [comment]
Thanks, the set_shape works well here.

But one thing I'm curious about is that, if I split the graph, (add a sess.run, and get the result of image array, then construct tensor, send it to rest of the graph), does this increase overhead? 
While actually when running it, it seems that the "set_shape" method will take more time to run than 'split graph" method...
I'm not clear how much overhead does it take if I split the graph and run session.

**Comment by aselle** [comment]
@TianweiXing, both approaches have different overheads and it is problem dependent. The best way to find out is to try it both ways and profile. Given that it is more of a usage question rather than a bug or feature request, I am closing this problem.

**Comment by mrharicot** [comment]
The annoying bit is that while `tf.image.decode_image` does not return a size, both `tf.image.decode_jpeg` and `tf.image.decode_png` do.

**Comment by Cooper-Yang** [comment]
@mrharicot Really, which version of tensorflow? Currently using 1.1.0 `tf.image.decode_jpeg` behave just the same as  `tf.image.decode_image`, which does not return a shape.

**Comment by mrharicot** [comment]
@Cooper-Yang I was using 1.0 at the time.
I'll check with the new version, thanks!

**Comment by mrharicot** [comment]
@Cooper-Yang I was using 1.0 at the time.
`tf.image.decode_jpeg` gives me the image size, so I ended up using an [ugly workaround](https://github.com/mrharicot/monodepth/blob/master/monodepth_dataloader.py#L98)

**Comment by AKSHAYUBHAT** [comment]
Once you upgrade to TF 1.2 decode_png will decode both jpg as well as png and vice versa. decode_image cannot be used along with resize since it also supports .gif . 

You can read this thread: https://github.com/tensorflow/tensorflow/issues/9356
