### ISSUE TITLE
SyncReplicasOptimizer' object has no attribute 'get_clean_up_op'

### ISSUE THREAD

**Issue by backyes** [tensorflow/tensorflow#8552]
```
python /models/slim/train_image_classifier.py \
  --worker_replicas=2 \
  --num_ps_tasks=1 \
  --sync_replicas=True \
  --replicas_to_aggregate=2 \
  --task=0 \
  --dataset_name=imagenet  \
  --train_dir=/tmp/train_logs  \
  --dataset_split_name=train \
  --dataset_dir=/imagenet/dataEgs \
  --model_name=inception_v3

````

Run /models/slim/train_image_classifier.py 

```
INFO:tensorflow:SyncReplicasV2: replicas_to_aggregate=2; total_num_replicas=2
INFO:tensorflow:Summary name /clone_loss is illegal; using clone_loss instead.
Traceback (most recent call last):
  File "/models/slim/train_image_classifier.py", line 583, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/models/slim/train_image_classifier.py", line 579, in main
    sync_optimizer=optimizer if FLAGS.sync_replicas else None)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 733, in train
    cleanup_op = sync_optimizer.get_clean_up_op()
AttributeError: 'SyncReplicasOptimizer' object has no attribute 'get_clean_up_op'

```

I confirm that more than one demos will encounter this issue if using distributed training under tensorflow 1.0.1 image. 

Hope some improvements for distributed training to demo how to use distributed training. 

Thanks.

**Comment by pclove1** [comment]
[This commit](https://github.com/tensorflow/tensorflow/commit/74514bffc4bbac7e6717e1079aca055b1c837229) might fix this issue.

Unfortunately, it's only available on master as of now.
Is there any chance that this commit can be picked into r1.0 branch for the next minor release?

**Comment by backyes** [comment]
@pclove1 

Thanks for your mentions.

I have fixed it manually before, but to run distributed training more and more bugs will be found with r1.0.1. It seems that the distributed training demo have not been updated for long time.  Hope for some more improvements.

**Comment by aselle** [comment]
@mrry, could you take a look if there is anything new we need to do to update the example?

**Comment by mrry** [comment]
It looks like these were never fixed after `tf.train.SyncReplicasOptimizer` was replaced by `tf.train.SyncReplicasOptimizerV2` in 059ccad4d4bac851da9fa9694c23dd49a4089bc6.

I'm not sure what all the changes were between these two versions, but @jmchen-g should be.

**Comment by jmchen-g** [comment]
The new version of sync opt doesn't need any clean up op so you can safely remove them in the training code.

**Comment by jbalma** [comment]
So just to be clear, I was able to modify /tensorflow/contrib/slim/python/slim/learning.py and remove this: 

if isinstance(sync_optimizer,
                    sync_replicas_optimizer.SyncReplicasOptimizer):
        cleanup_op = sync_optimizer.get_clean_up_op()

Is the suggestion going forward to replace the SyncReplicasOptimizer() with SyncReplicasOptimizerV2 in models/slim/train_image_classifier.py when SyncReplicasOptimizerV2 is added to a release?

I was able to run synchronous distributed tf-1.0.1 with the above lines commented out in learning.py and it ran as expected.

**Comment by girving** [comment]
@jbalma Interested in submitting a pull request to remove the obsolete code?

**Comment by yongtang** [comment]
It looks like `get_clean_up_op` has been removed in commit https://github.com/tensorflow/tensorflow/commit/74514bffc4bbac7e6717e1079aca055b1c837229

I think this issue could be closed?

**Comment by jmchen-g** [comment]
Right. That op get_clean_up_op was gone for a while. This issue should be
closed.

**Comment by jbalma** [comment]
Looks good . Thanks
