### ISSUE TITLE
Tenor flow distributed support for spectrum lsf 

### ISSUE THREAD

**Issue by jsimpson2** [tensorflow/tensorflow#8556]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by jsimpson2** [comment]
We are getting benchmark requests for tens or flow in a distributed environment. Spectrum lsf is our scheduler and tens or flow and all distributed powerai applications need to run in this environment. 
Documentation on how to run with spectrum lsf should be included.

**Comment by aselle** [comment]
LSF is not a workflow that we have knowledge or support of. However, the first google search result for "tensor lsf" links to this stackoverflow which has a link to blog entry that is helpful for setting it up.
http://stackoverflow.com/questions/41220475/tensorflow-lsf-distributed-tensorflow-on-lsf-cluster
