### ISSUE TITLE
Error building TensorFlow with local LLVM repository. ( Using local_repository extension in bazel )

### ISSUE THREAD

**Issue by annanay25** [tensorflow/tensorflow#8557]
Essentially, I want to run TensorFlow with a custom LLVM repository and not the llvm-mirror that bazel pulls from. 

I made the following changes:

1. Changed the ```temp_workaround_http_archive``` rule in ```//tensorflow/workspace.bzl``` to:

          native.local_repository (
              name = "llvm",
              path = "/git/llvm/",
          )

Where ```/git/llvm``` is my local llvm repository.

2. In ```/git/llvm``` I added the file ```WORKSPACE``` containing:

        workspace( name = "llvm" )

Error log:

    bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
    ERROR: /git/tensorflow/tensorflow/tools/pip_package/BUILD:81:1: no such package '@llvm//': BUILD file not found on package path and referenced by '//tensorflow/tools/pip_package:licenses'.
    ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
    INFO: Elapsed time: 0.219s

Installed TensorFlow from source. Here is the version info:

    $ git rev-parse HEAD
    4c3bb1aeb7bb46bea35036433742a720f39ce348

    $ bazel version
    Build label: 0.4.5
    Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
    Build time: Thu Mar 16 12:19:38 2017 (1489666778)
    Build timestamp: 1489666778
    Build timestamp as int: 1489666778

Now, obviously a ```llvm.build``` file is required, I just need to know how and where to place it. Also, how can I build tools like Polly from the bazel build files?

Thanks in advance!

**Comment by gunan** [comment]
This is an issue for your local setup.
Not an issue with the checked in TensorFlow code.
Therefore, I will close this issue.

Please reach out to stackoverflow with debugging support of your own code.

**Comment by cswhjiang** [comment]
I need to compile TF with local repositories  and  I have the same issue.
