### ISSUE TITLE
Mention Julia API bindings

### ISSUE THREAD

**Issue by MikeInnes** [tensorflow/tensorflow#8558]
In several places, like [here](https://www.tensorflow.org/api_docs/), API bindings for other languages are mentioned. It would be nice to mention the [Julia bindings](https://github.com/malmaud/TensorFlow.jl), which are now fairly stable and are actively used by many people.

It appears much of the website content comes from this repo but I can't find that page to make a PR. Would greatly appreciate a pointer to the right place for this.

cc @malmaud

**Comment by asimshankar** [comment]
@wolffg : Any thoughts on this?

**Comment by gunan** [comment]
All the mentioned APIs are merged into our core repository.
We also have haskell and rust bindings as external repositories, which are not mentioned in our website.
https://github.com/tensorflow/haskell
https://github.com/tensorflow/rust
The above are even owned by tensorflow github org, but not mentioned.
So I object these to be mentioned in the core API documentation. We should only list officially supported languages here:
https://www.tensorflow.org/api_docs/

However, we have a lot of external contributions that we can point people to. Maybe we can have a section in api_docs landing page that is along these lines:
"""
Below are a list of languages that are supported by our commmunity.
Please reach out to repository owners for support:

<language> - <website>
"""
What do you think @wolffg @asimshankar

**Comment by asimshankar** [comment]
Yup, I think that's what @MikeInnes was suggesting and sounds okay to me - to give a shoutout to various community supported bindings (FYI @jhseu )

**Comment by MikeInnes** [comment]
Completely agree. The current wording on the page is:

> We hope that the TensorFlow community will develop front ends for other languages like JavaScript, Lua, R and perhaps others [...]

This reads to me as if the listed bindings are the only ones so far. I think it'd be great to list community supported bindings here as well as calling for more (with a disclaimer that they are not official).

**Comment by asimshankar** [comment]
Done. You can currently see this on the version 1.1 page: https://www.tensorflow.org/versions/r1.1/api_docs/ 
and once the 1.1 release is finalized, that https://www.tensorflow.org/api_docs will look the same.

Thanks for making the bindings!

**Comment by MikeInnes** [comment]
Awesome, thankyou!

**Comment by malmaud** [comment]
Thanks @asimshankar!
