### ISSUE TITLE
Generating sentences using the RNN model

### ISSUE THREAD

**Issue by ammarasmro** [tensorflow/tensorflow#8570]
How do we generate sentences with the trained rnn model in:
[https://github.com/tensorflow/models/tree/master/tutorials/rnn/ptb](url)

I found some people doing it here and there but nothing that is well documented with a working code, at least not ones that are compatible with TF 1.0

I found this answer on stackoverflow but I keep getting errors with it
[http://stackoverflow.com/a/38729349/7568128](url)

Here is a copy of the file I'm working with 
[ptb_word_lm2 (copy).txt](https://github.com/tensorflow/tensorflow/files/856981/ptb_word_lm2.copy.txt)

**Comment by drpngx** [comment]
That's a great question for stackoverflow, where we monitor all questions with the tag `tensorflow`. We try to keep the github issues to bugs and feature requests only. Thanks.
