### ISSUE TITLE
Image Labeler Fails with Gifs?

### ISSUE THREAD

**Issue by tomasreimers** [tensorflow/tensorflow#8572]
The image_label example assumes that decode_gif (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/main.cc#L105) will return a 3-d tensor ([height, width, channels]) in the same way that decode_jpeg or decode_png would. However decode_dif returns a 4-d shape ([frames, height, width, channels], https://www.tensorflow.org/api_docs/python/tf/image/decode_gif). This will cause ResizeBilinear to fail.

This could be fixed by pulling the first frame from the gif, or by choosing to not expand dimensions on the gif (and classifying each frame).

**Comment by drpngx** [comment]
I think you typically just decode a single channel by passing the channel argument to the `tf.image.decode_*` functions?

**Comment by freedomtan** [comment]
Since only the single frame gif will be used in this label_image, frames should be 1. So we can use Squeeze() to remove it. See my PR, https://github.com/tensorflow/tensorflow/pull/9877

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
