### ISSUE TITLE
bazel-bin command not found

### ISSUE THREAD

**Issue by kushNumberTheory** [tensorflow/tensorflow#8573]
I am having issues while building pip package.I am building tensorflow with cpu configurations Steps i followed

bazel release= 0.4.5, ubuntu -version = 14.04 LTS
1. bazel clean
2. ./configure 
3. bazel build --config op
```
kush@kush-Lenovo-B40-80:~/machine_learning/deeplearning/tensorflow$ bazel build --config=op
Warning: ignoring LD_PRELOAD in environment.
WARNING: Config values are not defined in any .rc file: op
INFO: Found 0 targets...
INFO: Elapsed time: 2.365s, Critical Path: 0.03s

```
4. Now when i try to run 
`bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg`
```
kush@kush-Lenovo-B40-80:~/machine_learning/deeplearning/tensorflow$ bazel-bin/tensorflow/tools/pip_package/build_pip_package
bash: bazel-bin/tensorflow/tools/pip_package/build_pip_package: No such file or directory
```

But then i tried sudo it gives 
`sudo: bazel-bin/tensorflow/tools/pip_package/build_pip_package: command not found
`

bazel is installed in my system. i have checked it. 

I also tried giving full path in bazel-bin

`sudo: /usr/bin/bazel-bin/tensorflow/tools/pip_package/build_pip_package: command not found
`

i have bazel release = 0.4.5
Can anyone help me on this?

**Comment by ammarasmro** [comment]
Can you do those steps and let us know where it goes wrong? These are copied from the basic serving tutorial it's really easy to skip one and fall into trouble

`rm -fr ~/.bazel ~/.bazelrc`

Download a fresh binary from:
[https://github.com/bazelbuild/bazel/releases/download/0.4.5/bazel-0.4.5-installer-linux-x86_64.sh](url)

`cd ~/Downloads
chmod +x bazel-0.4.2-installer-linux-x86_64.sh
./bazel-0.4.2-installer-linux-x86_64.sh --user`

`export PATH="$PATH:$HOME/bin"`

`sudo apt-get update && sudo apt-get install -y \
        build-essential \
        curl \
        libcurl3-dev \
        git \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        pkg-config \
        python-dev \
        python-numpy \
        python-pip \
        software-properties-common \
        swig \
        zip \
        zlib1g-dev`

`sudo pip install grpcio`

`git clone --recurse-submodules https://github.com/tensorflow/serving
cd serving
cd tensorflow
./configure
cd ..`

Make sure you are executing `./configure` in the tensorflow folder that is inside the serving folder

**Comment by kushNumberTheory** [comment]
@ammarasmro  i got same error. PLease see the output of each and every step
1. ./configure

`kush@kush-Lenovo-B40-80:~/Desktop/serving/tensorflow$ ./configure 
Please specify the location of python. [Default is /usr/bin/python]: /usr/bin/python2.7
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? [Y/n] y
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Using python library path: /usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] n
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] n
No CUDA support will be enabled for TensorFlow
Configuration finished
Warning: ignoring LD_PRELOAD in environment.
......................................
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
Warning: ignoring LD_PRELOAD in environment.
................
INFO: All external dependencies fetched successfully.
`
2. ```
kush@kush-Lenovo-B40-80:~/Desktop/serving/tensorflow$ bazel build --config=opt
Warning: ignoring LD_PRELOAD in environment.
INFO: Found 0 targets...
INFO: Elapsed time: 2.939s, Critical Path: 0.03s
kush@kush-Lenovo-B40-80:~/Desktop/serving/tensorflow$ ls
```

3.
`kush@kush-Lenovo-B40-80:~/Desktop/serving/tensorflow$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
bash: bazel-bin/tensorflow/tools/pip_package/build_pip_package: No such file or directory
`
4. 
kush@kush-Lenovo-B40-80:~/Desktop/serving/tensorflow$ sudo !!
sudo bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
[sudo] password for kush: 
sudo: bazel-bin/tensorflow/tools/pip_package/build_pip_package: command not found

**Comment by gunan** [comment]
The command you are writing does not really do anything.
Please follow the guide here to build pip package from sources:
https://www.tensorflow.org/install/install_sources

And please use stackoverflow with help on how to use bazel.

**Comment by mikkokotila** [comment]
Following these instructions exactly, yields the same problem i.e. there is no file by the name of build_pip_package

**Comment by ilpapds** [comment]
You may have not installed bazel correctly. I had the same issue and then i understood that i forgot the step 4 of bazel 0.18.1 installation which is (in terminal):

export PATH="$PATH:$HOME/bin"
