### ISSUE TITLE
Problems with saver and restore: Failed to find any matching files

### ISSUE THREAD

**Issue by florpi** [tensorflow/tensorflow#8574]
This is the code:

```

save_path = model_path+"%s.ckpt"%model_name
if flag == "initial_train":
    print("Training new model")
    with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
        train_writer =  tf.summary.FileWriter('/tmp/log/train_tanh2_reg_100_%s'%beta_reg, sess.graph) # activate TensorBoard
        val_writer =  tf.summary.FileWriter('/tmp/log/val_reg_tanh2_100_%s'%beta_reg, sess.graph) 
        sess.run(tf.global_variables_initializer())
        print("The model will be saved in ",save_path)
        training_loop(num_epochs)
        flag = None
else:
    print("Training pretrained model")
    # Restore from previous model
    print("Restore from: " + save_path)
    with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
        train_writer =  tf.summary.FileWriter('/tmp/log/train_tanh2_reg_100_%s'%beta_reg, sess.graph) # activate TensorBoard
        val_writer =  tf.summary.FileWriter('/tmp/log/val_reg_tanh2_100_%s'%beta_reg, sess.graph) 
        saver.restore(sess,save_path)
        print("Model loaded")
        training_loop(nump_epochs)
train_writer.close()
val_writer.close()
```
and these are the ckpt files that have been created:

checkpoint
prezi.ckpt-0.data-00000-of-00001
prezi.ckpt-0.index
prezi.ckpt-0.meta
prezi.ckpt-1.data-00000-of-00001
prezi.ckpt-1.index
prezi.ckpt-1.meta
prezi.ckpt-2.data-00000-of-00001
prezi.ckpt-2.index
prezi.ckpt-2.meta
prezi.ckpt-3.data-00000-of-00001
prezi.ckpt-3.index
prezi.ckpt-3.meta

But still I get this error:

**Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/carol/tensorflowLF/clasification/prezi.ckpt**

Thanks for your help in advance :)

**Comment by skye** [comment]
Which version of TensorFlow are you running?

**Comment by timestocome** [comment]
Same problem here - using tf 1.0

**Comment by gallybaba** [comment]
I am having similar issue.
I am saving checkpoint in the same session and trying to read / restore it later in the same session. I get this error 
NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for D:\temp\rnnopt\modelrnnopt_2300.ckpt
	 [[Node: save/RestoreV2_24 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_24/tensor_names, save/RestoreV2_24/shape_and_slices)]]

I know for sure the model is saved. For some reason, most of the checkpoint files are removed.

session creation
with tf.Graph().as_default(): 
    # global step
    batch_start_index = tf.placeholder(tf.int32, shape=(1), name="BatchStartIndex")
    global_step = tf.Variable(0, name="global_step", trainable=False)
    print("Global Step", global_step)

Saver
    saver = tf.train.Saver()
    print("RNN Saver: ", saver)
    sess = tf.Session()
    print("RNN Session: ", sess)
    sw = tf.summary.FileWriter(base_checkpoint_path, sess.graph)
    print("Summary Writer: ", sw)
    sess.run(init)
    print("sesson init run complete")

Saving session
            file_name = "modelrnnopt_" + str(step) + ".ckpt"
            checkpoint_file = os.path.join(base_checkpoint_path, file_name)
            saver.save(sess, checkpoint_file, global_step=step)
            checkpoint_files[checkpoint_file] = 0    
-------------------->>>> I see this file getting saved
Restoring session
        print("Running checkpoint: ", cp)
        test_feed_dict = build_rnn_feed(HYPER_BATCH_SIZE, std_test_data, std_test_label,128)
        saver.restore(sess, cp) ------------------------------------->>>>>>> This is where it fails
#### cp => D:\temp\rnnopt\modelrnnopt_2300.ckpt
        test_prediction = sess.run(accuracy, feed_dict = test_feed_dict)

Why are the checkpoints removed?
base_checkpoint_path = "D:\\temp\\rnnopt"

**Comment by timestocome** [comment]
Actually, I fixed it and I don't remember what it was - but I can tell you the error message was way off. I think I had to re-initialize the variables first or something.

**Comment by Erdos001** [comment]
you must keep the model paramerer to be unchanged including optimizer
eg. --optimizer ADAGRAD to --optimizer ADAM

**Comment by Erdos001** [comment]
you must keep the model paramerer to be unchanged including optimizer
eg. --optimizer ADAGRAD to --optimizer ADAM

**Comment by RoshanADK** [comment]
I was stucked in the same , got a fix in different thread.
You have to use full relative path for the model 
Eg : "model_08" has to be replaced by "./model_08" or full relative path.

Try replacing and let us know, if it works !
