### ISSUE TITLE
tf.read_file doesn't support non ASCII characters in filename

### ISSUE THREAD

**Issue by wangxianliang** [tensorflow/tensorflow#8581]
Windows 2003 server R2, if input file names contain non ASCII characters (such as Chinese), exception will raise.

     [[Node: ReadFile_17 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](unstack_5:2)]]

Caused by op 'ReadFile_17', defined at:
  File "train.py", line 660, in <module>
    tf.app.run()
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\platform\app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 657, in main
    train()
  File "train.py", line 430, in train
    num_preprocess_threads=num_preprocess_threads)
  File "input.py", line 216, in distorted_inputs
    num_readers = FLAGS.num_readers)
  File "input.py", line 256, in batch_inputs
    image_buffer = tf.read_file(filename)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 203, in read_file
    result = _op_def_lib.apply_op("ReadFile", filename=filename, name=name)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2334, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Can not get size for: 01_瑜_057_14734860
91829.jpg : \u03f5\u0373\udcd5\u04b2\udcbb\udcb5\udcbd\u05b8\udcb6\udca8\udcb5\udcc4\udcce\u013c\udcfe\udca1\udca3

         [[Node: ReadFile_17 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](unstack_5:2)]]

**Comment by drpngx** [comment]
Right. We need to call the right function on windows. It would be nice if you could submit a PR.

**Comment by skye** [comment]
This is a bug in TensorFlow. It looks like we're using the ANSI versions of Windows filesystem functions (e.g. in [windows_file_system.cc:444](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/windows/windows_file_system.cc#L444) we should use GetFileAttributesExW instead of GetFileAttributesExA, see [Microsoft's docs](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364946(v=vs.85).aspx)).

I'm working on a fix, but unfortunately I don't have a good setup for testing Windows code so it might take a while before it's committed. For now, I suggest using ASCII filenames if possible.

**Comment by skye** [comment]
Oh, didn't see @drpngx's comment :) If @wangxianliang or someone else wants to spin up a patch that would be great.

**Comment by wangxianliang** [comment]
Maybe the bug is not related to the ANSI version of GetFileAttributesExA.
I created a new project, and used the code snippet of GetFileSize. The function can get the file attributes correctly whenever the input file name contains non ASCII characters or not.

**Comment by drpngx** [comment]
I wonder if we're getting the string properly utf8 encoded from python.
Worth checking.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by wangxianliang** [comment]
This bug can be fixed by changing **TranslateName** in **windows_file_system.h** from
```c++
string TranslateName(const string& name) const override {
    return name;
  }
```
to
```c++
std::wstring ToUtf16(std::string str)
{
	std::wstring ret;
	int len = MultiByteToWideChar(CP_UTF8, 0, str.c_str(), str.length(), NULL, 0);
	if (len > 0)
	{
		ret.resize(len);
		MultiByteToWideChar(CP_UTF8, 0, str.c_str(), str.length(), &ret[0], len);
	}
	return ret;
}
std::string ToMBCS(std::wstring str)
{
	std::string ret;
	int len = WideCharToMultiByte(CP_ACP, 0, str.c_str(), str.length(), NULL, 0, NULL, NULL);
	if (len > 0)
	{
		ret.resize(len);
		WideCharToMultiByte(CP_ACP, 0, str.c_str(), str.length(), &ret[0], len, NULL, NULL);
	}
	return ret;
}
string TranslateName(const string& name) const override {
    return ToMBCS(ToUtf16(name));
  }
```
The input fname is 'UTF-8' format, however, windows can't open utf8 encoded filename in c++.

**Comment by wangxianliang** [comment]
another fix could change some of the python codes in **'tensorflow\python\lib\io\file_io.py'**,
from
```python
def _preread_check(self):
    if not self._read_buf:
      if not self._read_check_passed:
        raise errors.PermissionDeniedError(None, None,
                                           "File isn't open for reading")
      with errors.raise_exception_on_not_ok_status() as status:
        self._read_buf = pywrap_tensorflow.CreateBufferedInputStream(
            compat.as_bytes(self.__name), 1024 * 512, status)
```
to
```python
def _preread_check(self):
    if not self._read_buf:
      if not self._read_check_passed:
        raise errors.PermissionDeniedError(None, None,
                                           "File isn't open for reading")
      with errors.raise_exception_on_not_ok_status() as status:
        encoding = 'mbcs' if platform.system() == 'Windows' else 'utf-8'
        self._read_buf = pywrap_tensorflow.CreateBufferedInputStream(
            compat.as_bytes(self.__name, encoding), 1024 * 512, status)
```
@drpngx @skye @girving
