### ISSUE TITLE
Greater than fifteen minutes to run a C++ example code using Tensorflow libraries using bazel

### ISSUE THREAD

**Issue by shyamalschandra** [tensorflow/tensorflow#8582]
Why does it take greater than fifteen minutes to run a C++ example code using the Tensorflow libraries using bazel?

https://www.tensorflow.org/api_guides/cc/guide

**Comment by yaroslavvb** [comment]
Because of Wirths law

**Comment by gunan** [comment]
You are probably seeing delays because you actually have to compile from sources when using bazel.
