### ISSUE TITLE
Consistent dtypes for discrete tensorflow.contrib.distributions?

### ISSUE THREAD

**Issue by dustinvtran** [tensorflow/tensorflow#8585]
In master (https://github.com/tensorflow/tensorflow/commit/f4a0c2c0f1bbff6e9b4d5d4a0796e7645a974321), the following is true:
+ Bernoulli, Categorical, and OneHotCategorical accept dtype as an argument, defaulting to `tf.int32`.
+ Binomial and Geometric have dtype given by its `probs` parameter, which is returned by the `get_logits_and_probs` utility function. It errors unless `probs` is float, meaning they must have dtype float.
+ Deterministic has dtype given by its `loc` parameter, which can have either dtype float or int.
+ Poisson has dtype given by its `rate` parameter, which can have either dtype float or int.

It seems like the default dtype for discrete distributions with fixed and bounded support is int. And the dtype for discrete distributions whose support depends on a parameter, or whose support is unbounded, varies between always being float or being either float or int.

**Comment by skye** [comment]
@ebrevdo @jvdillon @langmore

**Comment by ebrevdo** [comment]
How high priority is this bug for you, Dustin?

**Comment by dustinvtran** [comment]
Not a high priority. Am curious if there's a convention. This helps determine what dtype to use for the random variables we have in Edward: PointMass (here, it is Deterministic), Empirical, and DirichletProcess. https://github.com/blei-lab/edward/tree/master/edward/models

This also relates to the support specs on discrete vs continuous.

**Comment by jvdillon** [comment]
Thanks for raising this issue--this bug should now be resolved.
