### ISSUE TITLE
TensorFlow upgrade to 1.0.1 

### ISSUE THREAD

**Issue by nehardave** [tensorflow/tensorflow#8586]
I upgraded my server from 1.0.0 (ubuntu):

pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.1-cp27-none-linux_x86_64.whl
But I get the following discrepancy:

(tensorflow)$ pip list | grep tensorflow
tensorflow (1.0.0)
(tensorflow)$ python -c 'import tensorflow as tf; print(tf.__version__)'
1.0.1

**Comment by jubjamie** [comment]
What env manager are you using?
Did you uninstall 1.0.0 before upgrading to 1.0.1? If it's causing concern I would try uninstalling and reinstalling. It shouldn't do any harm.

**Comment by nehardave** [comment]
I am using virtualenv
No didn’t. But it should upgrade smoothly without uninstall and then install.

- Best Regards,
Neha Dave

**Comment by gunan** [comment]
The upgrade process is completely managed by PIP package manager.
PIP is just a tool we use to deliver tensorflow.
Unfortunately, it at times has bugs. Looks like you ran into one of these.
It looks like TF actually upgraded, but pip was not able to record the metadata correctly.

If you are not using virtualenv, you may need to use "sudo" to when running pip. If you are in a virtualenv, make sure you did not accidentally run pip command with sudo previously.
Also, most pip issues are resolved when you rerun the command.

Finally, as this looks like a PIP issue, there is not much we can do to help with this.
You can try reporting an issue to pypi, through http://pypi.org
