### ISSUE TITLE
Android Example Doesn't Build: Could not get unknown property 'assembleRelease'

### ISSUE THREAD

**Issue by jubjamie** [tensorflow/tensorflow#8587]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

http://stackoverflow.com/questions/39602587/could-not-get-unknown-property-assemblerelease-for-project/39720618
http://stackoverflow.com/questions/39590549/after-update-to-android-studio-2-2-gradle-plugin-2-2-0-could-not-get-unknown

### Environment info
Operating System:
Ubuntu 16.10
Installed version of CUDA and cuDNN: 
Toolkit 8.0.1 cuDNN 5.1

If installed from binary pip package, provide:

https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.1-cp36-cp36m-linux_x86_64.whl
1.0.1

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
The default android example code. Specifically `build.gradle`
When trying to run the code on an emulator, for example, there is a config error:
`Could not get unknown property 'assembleRelease for root project 'android' of type org.gradle.api Project` (Get this twice)
Links to:

```
afterEvaluate {
    assembleDebug.dependsOn copyNativeLibs
    assembleRelease.dependsOn copyNativeLibs
}
```
from build.gradle lines 143-146

### What other attempted solutions have you tried?
It looks like this is a conflict with gradle of some sorts. My knowledge is minimal with gradle/adroid studio. Some online threads say it should be included in a task but when putting 
`task afterEvaluate{ ...}` there is a similar error and this doesn't work either.

This post from a googler implies that your code is written as it should be though.
https://code.google.com/p/android/issues/detail?id=219732#32

At my wits end with this. For reference, I am able to build with bazel from the terminal. This seems to be a gradle/AS induced issue.
### Logs or other output that would be helpful
```
Information:Gradle tasks [:assembleDebug]

Error:(145, 1) A problem occurred configuring root project 'android'.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'assembleRelease' for root project 'android' of type org.gradle.api.Project.
   > Could not get unknown property 'assembleRelease' for root project 'android' of type org.gradle.api.Project.
```

**Comment by andrewharp** [comment]
What version of Gradle are you using? This should work with 2.3.0

**Comment by jubjamie** [comment]
@andrewharp Gradle Version 3.3 but Android Plug-In version 2.3.0 (which I assume is what you meant). This is a fresh version of AS on a fresh OS with zero tinkering so not sure why I can't get it to work.

For reference I was just following the tutorial. i.e. Open project, Run (on emulator in this case). I did make one change to force sensor orientation to 90 as it runs at 3 deg on my pixel C but that's it. 

I will try again without that change and start from scratch to see if it works again.

**Comment by shyzh** [comment]
Same issue.

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/tensorflow/tensorflow/examples/android/build.gradle' line: 144

* What went wrong:
A problem occurred configuring root project 'android'.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'assembleRelease' for root project 'android' of type org.gradle.api.Project.
   > Could not get unknown property 'assembleRelease' for root project 'android' of type org.gradle.api.Project.

**Comment by andrewharp** [comment]
@ggfan I think this may be related to 360f449d95cf487fd35dbcbc548a6b65fa7ae64f

**Comment by andrewharp** [comment]
@shyzh @jubjamie Did this ever build before? I'm not able to reproduce with a fresh pull.

Maybe try `rm -rf gradleBuild/ gradlew gradlew.bat gradle` to make sure you don't have incompatible version of gradle cached somewhere then try building again?

**Comment by jubjamie** [comment]
@andrewharp Not in the office atm but I've never built it before. Brand new OS, build etc. So shouldn't be a cache issue. Never even used gradle before. And I've been doing fresh clones from git in separate directories each time so doubt that will fix. Can try it tomorrow though.

**Comment by jubjamie** [comment]
@andrewharp Sorry for double posting but gradle cache doesn't seem to be the issue.
EDIT: Strangely, I had the problem again once. Then the next time it built correctly (android_debug.apk). I will try and reproduce this but I really have no idea why sometimes it builds and sometimes it doesn't. Will report back.

**Comment by sam-trt** [comment]
I have had the same issue and this seems to help fix it.

        tasks.whenTaskAdded { task ->
            if (task.name == 'assembleDebug') {
                task.dependsOn 'extractModels'
            }
            if (task.name == 'assembleRelease') {
                task.dependsOn 'extractModels'
            }
        }

**Comment by nick-jonas** [comment]
I'm having the same error as @jubjamie .  @sam-trt adding that block to my ```build.gradle``` file didn't seem to change anything, by adding it like so:

![screen shot 2017-03-26 at 3 53 32 pm](https://cloud.githubusercontent.com/assets/805682/24334665/7962aef2-123c-11e7-94ae-65dadd018753.png)

**Comment by sam-trt** [comment]
@nick-jonas sorry you need to change it to look like this


assemble.dependsOn copyNativeLibs

afterEvaluate {
    tasks.whenTaskAdded { task ->
        if (task.name == 'assembleDebug') {
            task.dependsOn 'copyNativeLibs'
        }
        if (task.name == 'assembleRelease') {
            task.dependsOn 'copyNativeLibs'
        }
    }
}

// Download default models; if you wish to use your own models then
// place them in the "assets" directory and comment out this line.
apply from: "download-models.gradle"

**Comment by nick-jonas** [comment]
@sam-trt I now get the following error with ```download-models.gradle```:

<img width="696" alt="screen shot 2017-03-27 at 10 56 55 am" src="https://cloud.githubusercontent.com/assets/805682/24362958/5ec10fbc-12dc-11e7-9910-7da030f9b764.png">

**Comment by andrewharp** [comment]
@nick-jonas you'll need to make an equivalent change in download-models.gradle too (altering it to take I to account the different targets).

**Comment by jubjamie** [comment]
I think @sam-trt solution works and matches some similar issues I spotted in my searches online. I'm getting an INSTALL_FAILED_NO_MATCHING_ABIS error now which I believe is to do with CPU architecture etc. and unrelated to this issue. @sam-trt and @andrewharp would you like me to pop this in as a PR?

**Comment by andrewharp** [comment]
@jubjamie I haven't seen the INSTALL_FAILED_NO_MATCHING_ABIS error before -- can you describe where you're seeing that and what the fix was?

I've made a change internally to apply @sam-trt's fix to download-model.gradle and build.gradle; should be pushed within a day or two.

**Comment by ggfan** [comment]
Here is build procedure I used on Ubuntu:

1. Using Android Studio 2.3.0,  import the project ( file --> new --> import (Select Eclipse or Gradle Project to import) --> example/android/build.gradle
2) Let Android Studio to create wrapper for the project ( click OK)
3) in build.gradle, change "def buildWithMake = true"  ( this should not matter too much: bazel build is the same )
4) make sure this one works:  def makeNdkRoot = System.getenv('NDK_ROOT'); otherwise I use android studio's ndk version [ inside local.properties file, copy NDK.DIR setting to it ]
5) Build --> Build APK.

there are some error messages coming from make build, but it could be ignored and APK is built on my system.

**Comment by ggfan** [comment]
Ok, I see it is IDE "run" button causing the trouble: need to remove assembleRelease.dependsOn when building for debug ( vice versa ).  So just comment that line would be fine, a patch pretty soon to fix it.

**Comment by jubjamie** [comment]
@ggfan Building the APK isn't an issue, it was running through the IDE as you pointed out. Building with Bazel is fine and not causing the problem so no need for step 3 (however I guess it's personal preference? Or is one method preferred?)

@andrewharp the INSTALL_FAILED_NO_MATCHING_ABIS error is caused when your app has native libraries but none for the cpu architecture that you are installing on. I see that in build.gradle there is a place to change the CPU architecture so I will try building with that changed. However, by the looks of it, it will overwrite the previous APK and libraries?
It's not a TF issue but more of a Android development thing. Nonetheless I would suggest it was mentioned in the docs a bit clearer for Android Studio. I'm happy to make those edits.

**Comment by andrewharp** [comment]
@jubjamie Right, if building with Gradle you need to manually select the right ABI. If running in an emulator, for example, typically you'll want to select x86 or x86_64.

It's possible to use bazel to build for multiple ABIs at a time with the --fat_apk_cpu flag. [android_full.sh](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/builds/android_full.sh) (which is how we build the nightly APK) passes `--fat_apk_cpu=armeabi-v7a,arm64-v8a,x86,x86_64`

Contributions welcome to replicate the multi-ABI functionality in build.gradle. It would probably require invoking bazel multiple times, once for each ABI being built, as I believe the --fat_apk_cpu only works when building android_binary targets.

**Comment by jubjamie** [comment]
@andrewharp yeah I did notice the flag in the gradle file. I haven't had a big play around with building for multiple targets as I wanted to get in Android Studio to help me understand the code etc.
I am a newbie to a lot of this so I might not jump at the multi-ABI in gradle task but if I come across needing to do it in the next couple of weeks then I can add that to my android pull request.
I noticed in the 1.1 release notes that cmake building is becoming available soon so will this impact cmake building too?

**Comment by andrewharp** [comment]
@jubjamie The bazel-built APK from android_full.sh will work on all 4 of those architectures.

If you want to simulate this with the Gradle+bazel build, you can manually change the `cpuType` variable in build.gradle to each in turn and hit build. The built native libraries will accumulate in the `jniLibs` directory, and Gradle will package them in the resulting APK. You can see what libraries actually get packaged with `unzip -v tensorflow/examples/android/gradleBuild/outputs/apk/android-debug.apk`

However be aware that making any changes to the native code will require a full repeat of the entire process, as otherwise your native libraries will become out of sync with each other. This is why it would be good to have build.gradle itself automate the process.

**Comment by jubjamie** [comment]
@andrewharp so if I build the APK 4 times after changing the cpu type, all of them will get packaged because the binaries (or whatever) accumulate in the Libs folder etc? Because if so then looping gradle automatically might not be too tricky for me to have a stab at.

Re: cmake. Ok. I was hoping I could get it working on Windows with make. I feel like I hit some errors before. Might give it another go now i'm more clued up. Thanks

**Comment by andrewharp** [comment]
@jubjamie 
Yes, that's exactly how it would work if you want to take a crack at it :)

Unfortunately the make build doesn't work on Windows out of the box. [This](https://github.com/tensorflow/tensorflow/issues/6385#issuecomment-285208600) is the current easiest way I know of to build Android TensorFlow on Windows. It should be approximately the same amount of effort to use this approach for either make or bazel builds. Hopefully we get cmake working in the near future so we can avoid the extra steps (contributions welcome!)

**Comment by jubjamie** [comment]
@andrewharp I am definitely not knowledgeable enough  to help with cmake stuff but I might give the gradle bits a go if I find some time in the next week or so. When/If I have a go I will add it my currently open Pull Request (or make a new one) and we can continue the conversation there.

Thanks for your help with this particular issue and android in general. I'm still struggling to understand how most of it works so I appreciate having this communication. Source code is hard when you didn't write it :(

Thanks!
