### ISSUE TITLE
Got an unexpected keyword argument 'fix_global_step_increment_bug'

### ISSUE THREAD

**Issue by sahildua2305** [tensorflow/tensorflow#8588]
I get this error while trying to run the [wide_n_deep_tutorial.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/wide_n_deep_tutorial.py).

```
TypeError: __init__() got an unexpected keyword argument 'fix_global_step_increment_bug'
```

It appears to be coming from - [ea963dd048749df525d2a1f19c31d7abcdc3268e](https://github.com/tensorflow/tensorflow/commit/ea963dd048749df525d2a1f19c31d7abcdc3268e).

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
None

### Environment info
Operating System: MacOS 10.11.5

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

1. A link to the pip package you installed: official python package tensorflow.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
1.0.1

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
I just ran this code - [wide_n_deep_tutorial.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/wide_n_deep_tutorial.py)

```
 ~$ python wide_n_deep_tutorial.py --model_type=wide_n_deep
```

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

```
Traceback (most recent call last):
  File "wide_n_deep_tutorial.py", line 234, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/Users/sdua/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "wide_n_deep_tutorial.py", line 197, in main
    FLAGS.train_data, FLAGS.test_data)
  File "wide_n_deep_tutorial.py", line 185, in train_and_eval
    m = build_estimator(model_dir, model_type)
  File "wide_n_deep_tutorial.py", line 132, in build_estimator
    fix_global_step_increment_bug=True)
TypeError: __init__() got an unexpected keyword argument 'fix_global_step_increment_bug'
```

**Comment by lcytzk** [comment]
Same problem. I'm using python3, windows OS. version 1.0.1
After that, I checked the help doc, I found that fix_global_step_increment_bug is not a init arg for class DNNLinearCombinedClassifier

 __init__(self, model_dir=None, n_classes=2, weight_column_name=None, linear_feature_columns=None, linear_optimizer=None, _joint_linear_weights=False, dnn_feature_columns=None, dnn_optimizer=None, dnn_hidden_units=None, dnn_activation_fn=<function relu at 0x00000000057B1840>, dnn_dropout=None, gradient_clip_norm=None, enable_centered_bias=False, config=None, feature_engineering_fn=None, embedding_lr_multipliers=None, input_layer_min_slice_size=None)

So, I think this a bug for wide_n_deep_tutorial.py cause there is no such init arg.
What I did is just delete this arg, but after do that I got other exceptions. 
Hope it will work for you, if just delete this arg option.

And wait for developers' response.

**Comment by sahildua2305** [comment]
@lcytzk indeed, that's the problem.

I realised that it's a new feature that they added, however not yet released. So, we have to use an older version of the tutorial until the time new version with that change is released.

**Comment by skye** [comment]
This tutorial has been updated since the 1.0.1 release, and it looks like you're trying to run the updated version from master using 1.0.1. Either upgrade to nightly or try https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/examples/learn/wide_n_deep_tutorial.py.

I'm gonna close this issue for now, but please reopen if you continue to experience problems.
