### ISSUE TITLE
Multiple simultaneous distributed-TF runs on single machine

### ISSUE THREAD

**Issue by pathak22** [tensorflow/tensorflow#8602]
I am running multiple distributed-TF sessions simultaneously on a single machine. I am setting up the configuration as described below. However, I am not getting the expected parallelism speedup.

I am running 4 different runs simultaneously, each of them with following config:
```
# Run - 1
tf.train.ClusterSpec({
	"ps": ["localhost:5000"]
	"worker": [
		"localhost:5001",
		"localhost:5002",
		"localhost:5003"],
	})

# Run - 2
tf.train.ClusterSpec({
	"ps": ["localhost:6000"]
	"worker": [
		"localhost:6001",
		"localhost:6002",
		"localhost:6003"],
	})

# Run - 3
tf.train.ClusterSpec({
	"ps": ["localhost:7000"]
	"worker": [
		"localhost:7001",
		"localhost:7002",
		"localhost:7003"],
	})

# Run - 4
tf.train.ClusterSpec({
	"ps": ["localhost:8000"]
	"worker": [
		"localhost:8001",
		"localhost:8002",
		"localhost:8003"],
	})
```

The command that I use to setup each server looks **exactly** like this for each worker and parameter server respectively:
```
# worker: index varies from 0 to 2
server = tf.train.Server(clusterSpec, job_name="worker", task_index=0,
                                 config=tf.ConfigProto(intra_op_parallelism_threads=1,
                                 inter_op_parallelism_threads=2))

### ps
server = tf.train.Server(clusterSpec, job_name="ps", task_index=0,
                                 config=tf.ConfigProto(device_filters=["/job:ps"]))
```

While setting up the network variables, the device is setup **exactly** like this for all runs:
```
ps_device = "/job:ps"
worker_device = "/job:worker/task:0/cpu:0"
worker_device = "/job:worker/task:1/cpu:0"
worker_device = "/job:worker/task:2/cpu:0"
```

There are `80` cores and enough memory. Each job has `3 workers and 1 ps`. In some fixed amount of time, I get following performance:
```
1 run on machine: x iterations
4 runs on machine: approx. x/2 iterations
6 runs on machine: approx. x/3 iterations
```

The number of cores are enough such that I would expect 4 simultaneous runs to go as fast as single run, but it is no where close. Is there some mistake in my usage of the distributed-tf api ? I suspect there might be issue in the way I am using cpu device for worker: `cpu:0`. But as I read from docs, it seems to mention that `cpu:0` would do automatic scheduling. Does this hold even if I am running 4 different runs of distributed-tf on single machine? Should I be setting up `cpu:1 , cpu:2, cpu:3, cpu:4` for workers of 4 different runs ? Any help would be greatly appreciated. 

Thanks in advance !!

**Comment by tfboyd** [comment]
Hi @pathak22 ,

What is your end goal?  If you are training a single model on a single machine there is usually no need to run distributed, which creates more to keep track of.  If I am reading your config correctly you are running 12 workers + 4 ps_servers simultaneously on one server.  If I made a random guess, you are getting contention for resources.  TF will handle scheduling for CPU:0 but multiple tensorflow processes are not going to be aware of each other and the OS at that point owns the scheduling.  

Some questions that might help get someone give you a better answer
- Which model are you training?
- What CPU are you using?  I did not research but to get 80 cores seem like a possibly but not necessarily exotic setup.  
- What was the CPU utilization when running a single setup, then 2, then 3 and then 4?  No need to report it in this issue if you do not want but I would check that.  
- What performance do you get with nothing distributed and what is the CPU utilization?  

If you are trying to get the most out of your single server.  I would start with nothing distributed and assuming the code is fully optimized and I thought the server was not fully utilized I would try a distributed setup.  I have not personally setup this situation and others might have more or better advice  

Sample code to run would also be useful.  I am not guaranteeing someone will try it.  Your details are good but there are a lot of variables and unknowns.

**Comment by pathak22** [comment]
Thanks @tfboyd for your comment. Sorry for the confusion, but no I am not trying to run single model. I am trying to run _4 completely different programs on same machine_. These four programs have no relation to each other. Each program has 3 workers and 1 parameter server of its own, all 3 workers update their unique parameter server asynchronously using hogwild SGD. This is what I meant when I say `Run` in my main comment above, sorry if it was not clear. To concretize the model, I am training 4 A3C models on 4 different tasks. Each A3C has 3 workers.

Actually, I think you have pin-pointed my question: 
> TF will handle scheduling for CPU:0 but multiple tensorflow processes are not going to be aware of each other

I have two questions:
1) Does different worker processes in distributed-TF handle parallelization if I just say `CPU:0` in all of them ? I would believe they should, given the documentation, because TF knows about different worker processes via the cluster spec.
2) If answer to 1) is yes, then what happens when I run multiple independent programs (or "runs") in which each program is "a distributed-TF session with multiple worker processes" ? Should I still use `CPU:0` in all of them ? 

I would believe TF won't handle the second case, because they don't know about other programs being running. So, is there a way to define affinity for different processes for different cpu cores ? For example:
```
ps_device = "/job:ps"
worker_device = "/job:worker/task:0/cpu:2"
worker_device = "/job:worker/task:1/cpu:4"
worker_device = "/job:worker/task:2/cpu:6"
```
Can I do something like above, i.e., tag different cpu devices ?

My question is more of a usage question and let me know if this is not the right place to ask. But tensor-flow docs talk only about `cpu:0` and do not talk about assigning affinity for each cpu core e.g. `cpu:1, cpu:2` .. similar to what TF has for gpu. Are these supported ? If yes, what is the right usage. 

I found one answer by @mrry has some answer here regarding this: http://stackoverflow.com/a/37864489 , but don't know the usage in context of distributed-TF.

**Comment by tfboyd** [comment]
I would not do this distributed. Unless I am missing something, I would run 4 different Tensorflow instances targeted at CPU:0, one for each model you are training.  If that performance looks poor you could go back and compare running multiple workers with a ps_server on a single server vs 1 instance not distributed.   If you think the performance is not expected, then you can compare (if you wanted) 1 instance vs. a distributed setup.  I would be interested in the results but I suspect for a normal 2 socket XEON it would not be better to run distributed on a single server.

**Comment by skye** [comment]
I might be off here, but maybe you should look into using a cluster manager like Mesos, Kubernetes, etc. Even though you're only running on a single node, I think these should still help you schedule and run your separate models on different CPUs. Or I believe you can manually achieve something similar with multiple docker containers, but using a framework is probably easier.

**Comment by gunan** [comment]
I don't think this is a TF bug. This is an issue with user setup, so should be asked in Stackoverflow. I will close this issue. I also want to clarify a few things.

TF will only see `CPU:0`. CPU:x where x is not 0 will give you errors in your code.
I do not understand what you mean by handling parallelization. Operating system manages parallel processes running on CPU. If you want one process to be reserved to run on a specific core, you will need

It does not make sense to run distributed TF on a single machine, and expect good performance out of it. On the same machine, a single process training will always be faster, because distributed TF always has the RPC communication overheads, even if we do not consider any other overhead of distributed training.
In the end, on the same machine distributed TF and single process TF has access to the same "pool" of resources, and distributed TF needs to do more things than just training, so it is slower.
