### ISSUE TITLE
Problem with 3-D matmul

### ISSUE THREAD

**Issue by DingkunLong** [tensorflow/tensorflow#8609]
I want to do a multiplication with two 3-D tensors, as defined:
a = tf.random_uniform(shape = [5,3,3])
b = tf.ones(shape = [5,3,1])
c = tf.matmul(a,b)
but I can't get the right answer as described in the tf.matmul function
https://www.tensorflow.org/api_docs/python/tf/matmul
a:
[[[ 0.05892992  0.12031484  0.7328496 ]
  [ 0.70889461  0.19382548  0.74017155]
  [ 0.90600419  0.91791809  0.19239831]]

 [[ 0.81325758  0.82476532  0.08050001]
  [ 0.48782277  0.21102762  0.22384059]
  [ 0.92273653  0.27739847  0.09880614]]

 [[ 0.6034205   0.83058596  0.74381268]
  [ 0.848786    0.59108317  0.19264364]
  [ 0.16111362  0.97805214  0.53506196]]

 [[ 0.26249301  0.67511797  0.16425216]
  [ 0.91532063  0.62129664  0.26845133]
  [ 0.48103786  0.38934362  0.7424022 ]]

 [[ 0.69902301  0.23881793  0.7409364 ]
  [ 0.91846371  0.71484613  0.45291376]
  [ 0.20789778  0.31036663  0.40649498]]]
b = 
[[[ 1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]]

 [[ 1.]
  [ 1.]
  [ 1.]]]
c = 
[[[ 2.07270455]
  [ 1.61431181]
  [ 1.29296649]]

 [[ 1.85375774]
  [ 1.27382767]
  [ 2.0612402 ]]

 [[ 1.18541944]
  [ 0.6504941 ]
  [ 0.26519179]]

 [[ 1.86258638]
  [ 2.32511139]
  [ 0.82957554]]

 [[ 2.26229262]
  [ 1.60952091]
  [ 1.65814292]]]

**Comment by drpngx** [comment]
Hi @DingkunLong  that's a great question for stackoverflow where we monitor all questions with the tag `tensorflow`. We reserve github issues for bugs in tensorflow. Thanks!
