### ISSUE TITLE
Tensorboard Embedding Sprite Image Aspect Ratio

### ISSUE THREAD

**Issue by jongchyisu** [tensorflow/tensorflow#8610]
I tried to use tensorboard embedding visualization with sprite images. 
It works well except two things:
1) Even though I set the image width and height as:
embedding.sprite.single_image_dim.extend([my_width, my_height])
and the projector_config.pbtxt file has:
sprite {
    image_path: "sprite.png"
    single_image_dim: my_width
    single_image_dim: my_height
}
Tensorboard **resizes the images to be square**, though it can get correct part from the sprite image, except that:
2) Every last image of each row is not correct. This happens when I have lots of images (like 200 images with size 70*100).

Seems like it only support square images?

**Comment by skye** [comment]
@dandelionmane

**Comment by dandelionmane** [comment]
@dsmilkov

**Comment by appierys** [comment]
I can confirm that indeed Tensorboard resizes the images to be square.

**Comment by wchargin** [comment]
Thanks for reporting this! I've migrated it to our new repository at https://github.com/tensorflow/tensorboard/issues/44.
