### ISSUE TITLE
TensorBoard not working, 

### ISSUE THREAD

**Issue by BrianZhu01** [tensorflow/tensorflow#8611]
I run it as https://www.tensorflow.org/get_started/summaries_and_tensorboard here described, but the browser can't display it ,what's wrong with it ? 
![0x22a3](https://cloud.githubusercontent.com/assets/15243563/24180783/edbb7ff2-0ef1-11e7-852b-a579773aa8be.jpg)

**Comment by BrianZhu01** [comment]
and the version of Tensorflow is 0.11

**Comment by gunan** [comment]
Please use the latest version of TF.
The tutorials on our website point to the latest version unless you specificly select older versions of TF.
