### ISSUE TITLE
Error when using lookup table from tf.contrib.keras

### ISSUE THREAD

**Issue by ophiry** [tensorflow/tensorflow#8617]
I'm trying to build a simple model that includes string input and lookup in a lookup table, and embedding.

I get an error that appears to caused by using non keras layers in a keras model

the code:
```
import tensorflow.contrib.keras as keras
import tensorflow

input_layer = keras.layers.Input(shape=(1,), name='input', dtype='string')
lut = tensorflow.contrib.lookup.HashTable(tensorflow.contrib.lookup.KeyValueTensorInitializer(['a', 'b', 'c'], [1, 2, 3]), default_value=-1)
lut_layer = lut.lookup(input_layer)
embed = keras.layers.Embedding(input_dim=10, output_dim=5)(lut_layer)

model = keras.models.Model(inputs=[input_layer], outputs=[embed])


```
the error:
```
Traceback (most recent call last):
  File "/Users/ophir/dev/ophir/tf_keras_2.py", line 10, in <module>
    model = keras.models.Model(inputs=[input_layer], outputs=[embed])
  File "/Users/ophir/anaconda3/envs/tf_master/lib/python3.6/site-packages/tensorflow/contrib/keras/python/keras/engine/topology.py", line 1640, in __init__
    build_map_of_graph(x, seen_nodes, depth=0)
  File "/Users/ophir/anaconda3/envs/tf_master/lib/python3.6/site-packages/tensorflow/contrib/keras/python/keras/engine/topology.py", line 1631, in build_map_of_graph
    next_node = layer.inbound_nodes[node_index]
AttributeError: 'NoneType' object has no attribute 'inbound_nodes'

Process finished with exit code 1
```

using tensorflow on macos, built from source revision: 88998663605ca3b728d6eec298717c8a8558639f

**Comment by drpngx** [comment]
@fchollet any idea?

**Comment by fchollet** [comment]
For the time being, any op that is not a Keras layer should be wrapped inside a Keras `Lambda` layer:

```python
inputs = keras.layers.Input(shape=(1,), name='input', dtype='string')
lut = tensorflow.contrib.lookup.HashTable(tensorflow.contrib.lookup.KeyValueTensorInitializer(['a', 'b', 'c'], [1, 2, 3]), default_value=-1)
lut_output = keras.layers.Lambda(lut.lookup)(inputs)
```

If the wrapping is broken at any point, then it prevents you from being able to build a Keras model with your inputs/outputs later on.

We will automate this wrapping in a later version.

**Comment by jricheimer** [comment]
@fchollet, I am also getting this problem, even after wrapping with a Lambda layer. Particularly:

`permuted = Lambda((lambda x: K.permute_dimensions(x, pattern=(0,2,1))))(output)`

When I try to define the model which includes this layer, I get the same error as @ophiry posted above.
Is there any way around this problem?

**Comment by hgaiser** [comment]
@fchollet, what if the non-Keras layer has a backprop function and/or trainable params? How can these be added to a Keras model? A Lambda layer would not handle the backpropagation / trainable params, correct?

**Comment by fchollet** [comment]
If you have parameters to train, you should write a custom layer:
https://keras.io/layers/writing-your-own-keras-layers/

**Comment by hgaiser** [comment]
> If you have parameters to train, you should write a custom layer:
> https://keras.io/layers/writing-your-own-keras-layers/

Thanks @fchollet, I think I'm beginning to understand the situation. In my specific case I'm tring to use a layer with no trainable weights (RoiPooling) but it does have a backward propagation function. If I register the op in the C API with `REGISTER_OP`, wrap it in a Keras `Lambda` layer and register the backward propagation function with the same op name (currently only possible in python with the `@ops.RegisterGradient` decorator), then tensorflow (and thus Keras) should be able to compute correct gradients. I believe this is correct and I will continue to work under that assumption. If it is not correct then I would gladly hear about it :)

**Comment by fchollet** [comment]
Keras delegates gradient computation to TF. If you have custom
differentiable ops that don't have weights, a Lambda layer works fine.
