### ISSUE TITLE
Add more Android Examples

### ISSUE THREAD

**Issue by LouisCAD** [tensorflow/tensorflow#8620]
Hi,

The only Android example is currently for image recognition, but there's a lot more that can be done with Machine Learning on handsets.

Could more examples be added, using Tensorflow to recognize patterns from motion sensors such as accelerometer for example?

[See related question here on StackOverflow](http://stackoverflow.com/questions/42901282/train-android-app-to-recognize-sensor-patterns-using-machine-learning)

**Comment by sbimochan** [comment]
where is it?

**Comment by drpngx** [comment]
@petewarden for comments.

**Comment by petewarden** [comment]
I agree that it would be good to have more examples outside of images, and we do have some in-progress. We would welcome contributions too of course!

**Comment by girving** [comment]
Closing since this is too open ended.  We'd be happy to accept PRs!
