### ISSUE TITLE
virtualenv install python issues.

### ISSUE THREAD

**Issue by jkjangles** [tensorflow/tensorflow#8622]
While installing virtualenv for tensorflow, I get the following error.

The executable /Users/xxx/tensorflow/bin/python is not functioning ERROR: It thinks sys.prefix is
'/Users/xxx' (should be '/Users/xxx/tensorflow')

It seems it is common and related to having python3 or conda installed. But I could not find a known solution.

On my OS Sierra 10.12.3 machine, I have Conda 1.4.3 (python 3.6) installed (came with standard Conda install). 

Thanks.

**Comment by drpngx** [comment]
It sounds like virtualenv is not functioning, regardless of tensorflow?

**Comment by gunan** [comment]
This is definitely an issue with python in your virtualenv.
Since it is not a TF issue, I will close this.
Please reach use support channels for anaconda for help with python issues in anaconda.
