### ISSUE TITLE
ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients,

### ISSUE THREAD

**Issue by heermasterlp** [tensorflow/tensorflow#8625]
I found a error when I try to train my models using the GradientDescentOptimizer(). There are my train code.
```
    y_prob = tf.sigmoid(layer_dropped)

    # Set a thresholds value
    y_pred = tf.floor(y_prob)

    # Loss Operation
    loss_op = tf.reduce_mean(tf.abs(y_true - y_pred))
    optimizer_op = tf.train.GradientDescentOptimizer(0.005).minimize(loss_op)
```

If I do not use the `tf.floor()` function in my loss operation, the training is OK. Just like this:
```
loss_op = tf.reduce_mean(tf.abs(y_true - y_prob))
optimizer_op = tf.train.GradientDescentOptimizer(0.005).minimize(loss_op)
```

**Comment by drpngx** [comment]
That is correct. `tf.floor` doesn't have a gradient. It's not easily differentiable. See this stackoverflow [post](http://stackoverflow.com/questions/42206906/alternative-plan-of-tf-floor/42210345#42210345) for more details.

**Comment by shwetagargade216** [comment]
ValueError                                Traceback (most recent call last)
~\NNV2\train1.py in <module>()
    106     case = args.case
    107     logdir = '{}/{}/train1'.format(logdir_path, case)
--> 108     train(logdir=logdir)
    109     print("Done")

~\NNV2\train1.py in train(logdir, queue)
     31     with tf.control_dependencies(tf.get_collection(tf.GraphKeys.UPDATE_OPS)):
     32         var_list = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES, 'net/net1')
---> 33         train_op = optimizer.minimize(loss_op, global_step=global_step, var_list=var_list)
     34 
     35     # Summary

~\Anaconda3\lib\site-packages\tensorflow\python\training\optimizer.py in minimize(self, loss, global_step, var_list, gate_gradients, aggregation_method, colocate_gradients_with_ops, name, grad_loss)
    405           "No gradients provided for any variable, check your graph for ops"
    406           " that do not support gradients, between variables %s and loss %s." %
--> 407           ([str(v) for _, v in grads_and_vars], loss))
    408 
    409     return self.apply_gradients(grads_and_vars, global_step=global_step,

ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients, between variables

**Comment by shwetagargade216** [comment]
how to resolve this

**Comment by nitinsethi22** [comment]
Did you get how to resolve this issue? @shwetagargade216 
I too am facing the same issue.

**Comment by TheoPaput** [comment]
Same problem there
