### ISSUE TITLE
Build configuration error: TensorFlow is not configured to build with GPU support.

### ISSUE THREAD

**Issue by jasonbunk** [tensorflow/tensorflow#8628]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
Commit "ede5ebe54f0689a53eeaf0fb1c9a25f136ab3a69" fails to configure for me, the commit before that succeeds. Might be related to issue #8619 which was closed, although for me using bazel 0.4.5 does not work.

Fails with "git checkout ede5ebe54f0689a53eeaf0fb1c9a25f136ab3a69"
http://pastebin.com/FHt0r5kS
Succeeds with "git checkout 450386c513a4c68d6b77f9b475dc39b442775a86"
http://pastebin.com/3vGHik0G

### Environment info
Operating System: Ubuntu 16.04.2 LTS

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

```
jbunk@desktop:~/libraries$ cat /usr/local/cuda/version.txt 
CUDA Version 8.0.61
jbunk@sherman:~/libraries/Tensorflow-Github$ ls /usr/local/cuda/lib64/libcudn*
/usr/local/cuda/lib64/libcudnn.so  /usr/local/cuda/lib64/libcudnn.so.5  /usr/local/cuda/lib64/libcudnn.so.5.1.10  /usr/local/cuda/lib64/libcudnn_static.a
```

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

Commit "ede5ebe54f0689a53eeaf0fb1c9a25f136ab3a69"
```
jbunk@desktop:~/libraries$ bazel version
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:19:38 2017 (1489666778)
Build timestamp: 1489666778
Build timestamp as int: 1489666778
```

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

Fails with "git checkout ede5ebe54f0689a53eeaf0fb1c9a25f136ab3a69"
http://pastebin.com/FHt0r5kS
Succeeds with "git checkout 450386c513a4c68d6b77f9b475dc39b442775a86"
http://pastebin.com/3vGHik0G

**Comment by drpngx** [comment]
Note: conversation currently continuing on #8619.

**Comment by drpngx** [comment]
Fixed by https://github.com/tensorflow/tensorflow/commit/fba05c300bf6840e76787680ed7fd1239cdb9ad0
 Thanks @damienmg !
