### ISSUE TITLE
Please provide an example how to use a model trained from scratch for image classification

### ISSUE THREAD

**Issue by Steve7878** [tensorflow/tensorflow#8633]
The following documentation of TensorFlow-Slim contains how to train a model from scratch, but it's not explained how to use the resulting checkpoint files for image classification.
https://github.com/tensorflow/models/tree/master/slim#training-a-model-from-scratch

Although it's possible to load the pre-trained models (https://github.com/tensorflow/models/tree/master/slim#pre-trained-models) and use it for image classification with the example given in https://github.com/tensorflow/models/blob/master/slim/slim_walkthrough.ipynb, it seems not possible to simply use the checkpoint files generated by "training from scratch" in the same way.

Any example on how to use the newly generated checkpoints for image classification (for example with inception) would be appreciated.

**Comment by drpngx** [comment]
@wolffg @martinwicke @nealwu to consider?

**Comment by martinwicke** [comment]
The garden should contain that documentation, eventually.

**Comment by Steve7878** [comment]
Is there already any code example on which it's possible to build on?

**Comment by girving** [comment]
Closing as too open ended.  Watch the gardener space.
