### ISSUE TITLE
Cannot build Android demo - Bazel BUILD failed

### ISSUE THREAD

**Issue by derekhh** [tensorflow/tensorflow#8641]
### Description

I've successfully built the [Android Camera Demo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) a couple days ago but I've failed to build the app today. The error message looks like this:

    ERROR: /Users/hao.hu/GitHub/tensorflow/tensorflow/tensorflow/core/kernels/BUILD:3870:1: C++ compilation of rule '//tensorflow/core/kernels:android_tensorflow_kernels' failed: Process exited with status 1 [sandboxed].
    tensorflow/core/kernels/split_v_op.cc:212:28: error: non-constant-expression cannot be narrowed from type 'value_type' (aka 'long long') to 'int' in initializer list [-Wc++11-narrowing]
              prefix_dim_size, split_sizes_vec[i], suffix_dim_size};
                               ^~~~~~~~~~~~~~~~~~
    tensorflow/core/kernels/split_v_op.cc:172:12: note: in instantiation of member function 'tensorflow::SplitVOpCPU<int, long long>::Compute' requested here
      explicit SplitVOpCPU(OpKernelConstruction* c) : Base(c) {}
               ^
    tensorflow/core/kernels/split_v_op.cc:355:19: note: in instantiation of member function 'tensorflow::SplitVOpCPU<int, long long>::SplitVOpCPU' requested here
    TF_CALL_ALL_TYPES(REGISTER_SPLIT_LEN);
                  ^
    tensorflow/core/kernels/split_v_op.cc:212:28: note: insert an explicit cast to silence this issue
              prefix_dim_size, split_sizes_vec[i], suffix_dim_size};
                               ^~~~~~~~~~~~~~~~~~
                               static_cast<int>( )
    tensorflow/core/kernels/split_v_op.cc:212:28: error: non-constant-expression cannot be narrowed from type 'value_type' (aka 'long long') to 'int' in initializer list [-Wc++11-narrowing]
              prefix_dim_size, split_sizes_vec[i], suffix_dim_size};
                               ^~~~~~~~~~~~~~~~~~
    tensorflow/core/kernels/split_v_op.cc:172:12: note: in instantiation of member function  'tensorflow::SplitVOpCPU<float, long long>::Compute' requested here
      explicit SplitVOpCPU(OpKernelConstruction* c) : Base(c) {}
               ^
    tensorflow/core/kernels/split_v_op.cc:355:19: note: in instantiation of member function 'tensorflow::SplitVOpCPU<float, long long>::SplitVOpCPU' requested here
    TF_CALL_ALL_TYPES(REGISTER_SPLIT_LEN);
                      ^
    tensorflow/core/kernels/split_v_op.cc:212:28: note: insert an explicit cast to silence this issue
              prefix_dim_size, split_sizes_vec[i], suffix_dim_size};
                               ^~~~~~~~~~~~~~~~~~
                               static_cast<int>( )
    tensorflow/core/kernels/split_v_op.cc:212:28: error: non-constant-expression cannot be narrowed from type 'value_type' (aka 'long long') to 'int' in initializer list [-Wc++11-narrowing]
              prefix_dim_size, split_sizes_vec[i], suffix_dim_size};
                               ^~~~~~~~~~~~~~~~~~
    tensorflow/core/kernels/split_v_op.cc:172:12: note: in instantiation of member function 'tensorflow::SplitVOpCPU<tensorflow::bfloat16, long long>::Compute' requested here
      explicit SplitVOpCPU(OpKernelConstruction* c) : Base(c) {}
               ^
    tensorflow/core/kernels/split_v_op.cc:356:1: note: in instantiation of member function 'tensorflow::SplitVOpCPU<tensorflow::bfloat16, long long>::SplitVOpCPU' requested here
    REGISTER_SPLIT_LEN(bfloat16);
    ^
    tensorflow/core/kernels/split_v_op.cc:353:3: note: expanded from macro 'REGISTER_SPLIT_LEN'
      REGISTER_SPLIT(type, int64);
      ^
    tensorflow/core/kernels/split_v_op.cc:349:27: note: expanded from macro 'REGISTER_SPLIT'
                              SplitVOpCPU<type, len_type>);
                              ^
    tensorflow/core/kernels/split_v_op.cc:212:28: note: insert an explicit cast to silence this issue
          prefix_dim_size, split_sizes_vec[i], suffix_dim_size};
                           ^~~~~~~~~~~~~~~~~~
                           static_cast<int>( )
    3 errors generated.
    Use --strategy=CppCompile=standalone to disable sandboxing for the failing actions.
    Target //tensorflow/examples/android:tensorflow_demo failed to build
    Use --verbose_failures to see the command lines of failed build steps.
    INFO: Elapsed time: 468.550s, Critical Path: 454.15s

**Comment by drpngx** [comment]
Can you give us more information about version (TF, OS, compiler, etc) and what changed between the last successful run and this one?

CC @petewarden

**Comment by derekhh** [comment]
@drpngx Thanks for your reply. I'll try to do a `git bisect` to figure out the offending commit.

I'm building the Android demo from the latest master branch (as of right now) on Mac OS X. 

Compiler info:

    ❯ gcc --version
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 8.0.0 (clang-800.0.42.1)
    Target: x86_64-apple-darwin16.4.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by andrewharp** [comment]
Which NDK is this? For best results try using 12b -- Bazel is known to have problems with more recent releases.

**Comment by derekhh** [comment]
@andrewharp It's r14b. I'll try r12b and see how it goes. :)

**Comment by derekhh** [comment]
OK. I just did a `bazel clean` and used `r12b` instead. Interestingly I'm receiving a different set of error messages:

```
ERROR: /Users/hao.hu/GitHub/tensorflow/tensorflow/tensorflow/contrib/android/BUILD:29:1: C++ compilation of rule '//tensorflow/contrib/android:android_tensorflow_inference_jni' failed: Process exited with status 1 [sandboxed].
tensorflow/contrib/android/asset_manager_filesystem.cc: In member function 'virtual tensorflow::Status tensorflow::{anonymous}::RandomAccessFileFromAsset::Read(tensorflow::uint64, size_t, tensorflow::StringPiece*, char*) const':
tensorflow/contrib/android/asset_manager_filesystem.cc:97:69: error: 'AAsset_seek64' was not declared in this scope
     off64_t new_offset = AAsset_seek64(asset.get(), offset, SEEK_SET);
                                                                     ^
tensorflow/contrib/android/asset_manager_filesystem.cc:98:52: error: 'AAsset_getLength64' was not declared in this scope
     off64_t length = AAsset_getLength64(asset.get());
                                                    ^
tensorflow/contrib/android/asset_manager_filesystem.cc: In member function 'virtual tensorflow::Status tensorflow::AssetManagerFileSystem::NewReadOnlyMemoryRegionFromFile(const string&, std::unique_ptr<tensorflow::ReadOnlyMemoryRegion>*)':
tensorflow/contrib/android/asset_manager_filesystem.cc:158:68: error: 'AAsset_openFileDescriptor64' was not declared in this scope
   int fd = AAsset_openFileDescriptor64(asset.get(), &start, &length);
                                                                    ^
tensorflow/contrib/android/asset_manager_filesystem.cc:173:44: error: 'AAsset_getLength64' was not declared in this scope
     length = AAsset_getLength64(asset.get());
                                            ^
tensorflow/contrib/android/asset_manager_filesystem.cc: In member function 'virtual tensorflow::Status tensorflow::AssetManagerFileSystem::GetFileSize(const string&, tensorflow::uint64*)':
tensorflow/contrib/android/asset_manager_filesystem.cc:214:38: error: 'AAsset_getLength64' was not declared in this scope
   *s = AAsset_getLength64(asset.get());
                                      ^
```

I'll try r13b and see what I get. Maybe that was the NDK version I was using when I successfully built the Android demo.

**Comment by andrewharp** [comment]
What command line are you using to build, and what NDK API level do you have set in your WORKSPACE file?

**Comment by derekhh** [comment]
@andrewharp 

I'm using this command as [instructed](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android):

```
bazel build -c opt //tensorflow/examples/android:tensorflow_demo
```

And this is the way I set SDK and NDK API levels:

```
android_sdk_repository(
  name = "androidsdk",
  api_level = 25,
  build_tools_version = "25.0.2",
  path = "/usr/local/Cellar/android-sdk/24.4.1_1/",
)

android_ndk_repository(
  name="androidndk",
  path="/usr/local/Cellar/android-ndk/r13b/",
  api_level=13)
```

**Comment by andrewharp** [comment]
Ah, your ndk api_level is too low: it needs to be at least 14.

I'd also leave the NDK at r12b (this is not tied directly to the api_level) for the time being until Bazel is confirmed to have no issues with anything more recent.

**Comment by derekhhsc** [comment]
Ah, I was so stupid. This fixes the problem!

For those careless guys who might meet the same problem in the future, I observed the original error message when my `android_ndk_repository` is defined like this:

```
android_ndk_repository(
  name="androidndk",
  path="/usr/local/Cellar/android-ndk/r14b/",
  api_level=14)
```

I didn't check anything and I thought that integer value in `r%db` should match the value of `api_level`. So while using `r12b` and `r13b` I've basically changed `api_level` to 12 and 13, respectively.

This is not the case, it is specified [here](https://github.com/bazelbuild/bazel/tree/master/examples/android) in the bazel repository that "Similarly, for the `android_ndk_repository` rule, the value of the `api_level` attribute corresponds to a directory containing the NDK libraries for that API level."

This config now builds successfully:

```
android_ndk_repository(
  name="androidndk",
  path="/usr/local/Cellar/android-ndk/r12b/",
  api_level=14)
```

**Comment by derekhhsc** [comment]
@andrewharp 

One more thing to add, using `r12b` and `api_level=14`, the original error message now becomes warnings like this:

```
tensorflow/core/kernels/split_v_op.cc: In instantiation of 'void tensorflow::SplitVOpCPU<T, Tlen>::Compute(tensorflow::OpKernelContext*) [with T = int; Tlen = long long int]':
tensorflow/core/kernels/split_v_op.cc:401:1:   required from here
tensorflow/core/kernels/split_v_op.cc:212:63: warning: narrowing conversion of 'split_sizes_vec.std::vector<_Tp, _Alloc>::operator[]<long long int, std::allocator<long long int> >(((std::vector<long long int, std::allocator<long long int> >::size_type)i))' from '__gnu_cxx::__alloc_traits<std::allocator<long long int> >::value_type {aka long long int}' to 'int' inside { } [-Wnarrowing]
```

**Comment by derekhh** [comment]
Ah, I was so stupid. This fixes the problem!

For those careless guys who might meet the same problem in the future, I observed the original error message when my `android_ndk_repository` is defined like this:

```
android_ndk_repository(
  name="androidndk",
  path="/usr/local/Cellar/android-ndk/r14b/",
  api_level=14)
```

I didn't check anything and I thought that integer value in `r%db` should match the value of `api_level`. So while using `r12b` and `r13b` I've basically changed `api_level` to 12 and 13, respectively.

This is not the case, it is specified [here](https://github.com/bazelbuild/bazel/tree/master/examples/android) in the bazel repository that "Similarly, for the `android_ndk_repository` rule, the value of the `api_level` attribute corresponds to a directory containing the NDK libraries for that API level."

This config now builds successfully:

```
android_ndk_repository(
  name="androidndk",
  path="/usr/local/Cellar/android-ndk/r12b/",
  api_level=14)
```

**Comment by derekhh** [comment]
@andrewharp 

Thanks again for your help. BTW, using `r13b` and `api_level=14` gives me the same error messages as the first post.

One more thing to add, using `r12b` and `api_level=14`, the original error message now becomes warnings like this:

```
tensorflow/core/kernels/split_v_op.cc: In instantiation of 'void tensorflow::SplitVOpCPU<T, Tlen>::Compute(tensorflow::OpKernelContext*) [with T = int; Tlen = long long int]':
tensorflow/core/kernels/split_v_op.cc:401:1:   required from here
tensorflow/core/kernels/split_v_op.cc:212:63: warning: narrowing conversion of 'split_sizes_vec.std::vector<_Tp, _Alloc>::operator[]<long long int, std::allocator<long long int> >(((std::vector<long long int, std::allocator<long long int> >::size_type)i))' from '__gnu_cxx::__alloc_traits<std::allocator<long long int> >::value_type {aka long long int}' to 'int' inside { } [-Wnarrowing]
```

**Comment by drpngx** [comment]
Great to see this is solved!

Thanks @andrewharp for the help! Feel free to coordinate with @wolffg if we need to update the docs.

**Comment by andrewharp** [comment]
I'll add some more detailed comments in the WORKSPACE file to clarify this.

**Comment by aj-michael** [comment]
Bazel 0.4.5 should work with NDK13 and NDK14. However, there is a substantial change from NDK12. In NDK12, GCC was used by default. In NDK13 and NDK14, clang is the default. I believe that gcc and clang are treating c++11-narrowing differently.

**Comment by vikasetrx** [comment]
Builds fine with Bazel 0.5.3 too, given that we use NDK12. However, NDK 13 or higher do fail. So the key is to use NDK12.

The compilation failures have got to do with narrowing conversion as @aj-michael stated.

**Comment by d4l3k** [comment]
Is there any plan to fix this? Seems that Tensorflow should definitely support the latest NDK version,

**Comment by andrewharp** [comment]
@d4I3k I've submitted a change internally to fix building with NDK r13+, should show up in the next push to github. I think right now r14b is the recommended NDK for bazel, but I also tested with r15c and that seems to work fine as well.

**Comment by aj-michael** [comment]
Bazel 0.5.4 supports up to NDK14. If you use NDK15, Bazel will pretend like it's NDK14 and may work, but there's no guarantees.

**Comment by d4l3k** [comment]
@andrewharp I'm running into issues compiling still:

Same error as: https://github.com/tensorflow/tensorflow/issues/9280

https://travis-ci.org/luk-ai/build-tensorflow/builds/273170125#L4187

**Comment by andrewharp** [comment]
@d4l3k When did you clone? The -fomit-frame-pointer flag added to tf_copts() in https://github.com/tensorflow/tensorflow/commit/d410a83207bdf63ead87a145f97377b7eb1f96bf should take care of the insufficient register error.

**Comment by d4l3k** [comment]
@andrewharp I cloned shortly ~30min before posting. I was previously using https://github.com/urho3d/android-ndk, but since have switched to just downloading the standard package and extracting.
