### ISSUE TITLE
No module named tensorflow occurs, Windows 7  no GPU involved

### ISSUE THREAD

**Issue by arifle** [tensorflow/tensorflow#8648]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
Same problem on Linux or MacOS.

### Environment info
Operating System: Windows 7

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
No

Tensorflow is well installed to a Windows 7 before posting this question. 
D:\Python35\Scripts>pip show tensorflow
---
Metadata-Version: 2.0
Name: tensorflow
Version: 1.0.1
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
Installer: pip
License: Apache 2.0
Location: d:\python35\lib\site-packages
Requires: numpy, six, protobuf, wheel
Classifiers:
  Development Status :: 4 - Beta
  Intended Audience :: Developers
  Intended Audience :: Education
  Intended Audience :: Science/Research
  License :: OSI Approved :: Apache Software License
  Programming Language :: Python :: 2.7
  Topic :: Scientific/Engineering :: Mathematics
  Topic :: Software Development :: Libraries :: Python Modules
  Topic :: Software Development :: Libraries
Entry-points:
  [console_scripts]
  tensorboard = tensorflow.tensorboard.tensorboard:main
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

Packages are all well installed (just for me cause this is the first day to Tensorflow.
Also, I've tried to install A ipython and it seems running well.
[1]: import tensorflow as tf
[2]: (I don't know what to do here and give an exit).

**Comment by gunan** [comment]
I do not really see an error message.
It looks like import command ran fine?

**Comment by gunan** [comment]
I mean, if you are seeing this:
```
[1]: import tensorflow as tf
[2]:
```
That means TensorFlow is installed and imported OK.

**Comment by arifle** [comment]
@gunan Thanks for this reply.
It gives this error after import
C:\Users\Administrator>python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (
Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named tensorflow
>>>

**Comment by gunan** [comment]
Could you try running ipython, and then importing tensorflow?
ipython is simply an improved python shell, so if it works there, it may be simply due to python paths not being setup correctly.

**Comment by arifle** [comment]
Thank you, @gunan .
It looks like a version problem? I have both 2.7 and 3.5 installed in different drive and the terminal launches 2.7 in default. Paths of python3.5 are also added to the env. I launched python under d:\python35 and perform import command which gives no output but another prompt simply as what I did in iphyton.
>>> import tensorflow as tf
>>>

**Comment by gunan** [comment]
That completely explains the problem.
TensorFlow only support python version 3.5 on windows.
https://www.tensorflow.org/install/install_windows
No output when you run the import command means success in python.

The import error in python 2.7 is completely expected.

I will close this issue, as it looks like you have a successful python 3.5 installation with tensorflow, and python 2.7 is not working as expected.

**Comment by gunan** [comment]
On windows I am not sure how you would setup your path to always start python 3.5 when you run python command in your terminal. But you can probably look around online to see how people setup their development envronments.
