### ISSUE TITLE
Who can tell me the way to use tf.confusion_matrix()?

### ISSUE THREAD

**Issue by FightingZhen** [tensorflow/tensorflow#8649]
I want to craete a confusion matrix to get the result of test data performance, I found that there is a function 'tf.confusion_matrix()', but I don't know how to use it, anybody can tell me ?

**Comment by jubjamie** [comment]
I can help you with this. But this is not a feature or bug issue with Tensorflow. Please create a stackover flow question, post it here, then close the issue. I will come and answer it for you.

Thanks

**Comment by FightingZhen** [comment]
I have already fix this in another way, thx anyway ~
