### ISSUE TITLE
Latest commit (524595) for Udacity Assignment 1 breaks IPython Notebook

### ISSUE THREAD

**Issue by stevenengler** [tensorflow/tensorflow#865]
Hi, I attempted to open the latest IPython Notebook for the Udacity course Assignment 1 from commit 524595 (23 Jan 2016), and it fails with the error:

```
Unreadable Notebook: ~/tensorflow/tensorflow/examples/udacity/1_notmnist.ipynb
NotJSONError('Notebook does not appear to be JSON: u\'{\\n "worksheets": [\\n {\\n "ce...',)
```

The notebook also fails to load here on Github. If I checkout the previous commit 42154f, the notebook loads correctly.

It's possible this is just me having bad luck, so if important, I'm running Anaconda Python on Ubuntu 14.04.3 LTS.

**Comment by vrv** [comment]
No, it looks like you have to use single quotes, I'll revert that commit since I can't really read the diff anyway.

**Comment by vrv** [comment]
Reverted in https://github.com/tensorflow/tensorflow/commit/be1f68e254d38a7545145731ded5873cb914e509
