### ISSUE TITLE
how to add conditions to tf.Print

### ISSUE THREAD

**Issue by flybirp** [tensorflow/tensorflow#8651]
can I add a certain condition to the tf.Print op?
something like print after certain iterations or something similar
I have tf.Print to print out the losses during training, therefore there is too many lines I couldn't possibly read

**Comment by matthiasreisser** [comment]
You could do something like:
```
def print_if_step(pass_through_tensor, print_list, step, print_step, prefix):
    pass_through_tensor = tf.cond(tf.equal(print_step,step), lambda: tf.Print(pass_through_tensor, [step] + print_list, "step " + prefix), lambda :pass_through_tensor)
    return pass_through_tensor
```
But I think these questions should be asked on stackoverflow.
M

**Comment by skye** [comment]
Yes, let's move any further discussion to  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). Thanks!
