### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'layers'

### ISSUE THREAD

**Issue by shuuchen** [tensorflow/tensorflow#8654]
Hi there,

The source code of tutorial
* https://www.tensorflow.org/tutorials/layers
* https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/layers/cnn_mnist.py

cannot run on my MacAir.

It just reported: AttributeError: module 'tensorflow' has no attribute 'layers'
Is that a version problem?

**Comment by jubjamie** [comment]
Can you please post the output of `python -c 'import tensorflow as tf; print(tf.__version__)' `

Layers was only recently introduced out of contrib. Please post output of above and we can go from there.

**Comment by shuuchen** [comment]
OK. That is 0.12.1

**Comment by mrry** [comment]
It looks like you are using tutorials that require TensorFlow 1.0 or later. Either upgrading to the latest version of TensorFlow, or using a tutorial from the 0.12 branch should fix things.

**Comment by Manoj-t** [comment]
Hello,
            I am using Mac OS. Currently I have tensorflow 0.12 running on my laptop. Can you help me how to upgrade tensorflow to latest version, which has attribute 'layers' in it.

**Comment by Hasnat65** [comment]
For me it is 2.0.0 but still that problem

**Comment by karan1210** [comment]
**AttributeError: module 'tensorflow' has no attribute 'layers'** means that tensorflow has not this kind of any command in that. it might have two cases.

1. your syntax may wrong. (for example with new update in tensorflow syntax of layers may change)
 in that case syntax is : `tf.keras.layers.Layer`  for tensorflow 2.1

2. If your syntax is right then you might have installation problem or path error. If you use GPU version, then check version of CUDA, CdNN.

in my case I install wrong CUDA version.
cuda 10.1
python 3.7.
It might be helpful to @Hasnat65 @shuuchen
