### ISSUE TITLE
Bazel does not support execution of Python interpreters via labels yet

### ISSUE THREAD

**Issue by star277hk** [tensorflow/tensorflow#8655]
I following tutorial https://www.tensorflow.org/tutorials/image_retraining
when I try to use the retrainer I got this error
Bazel does not support execution of Python interpreters via labels yet error

What can I do ?
![screen shot 2017-03-23 at 6 10 04 pm](https://cloud.githubusercontent.com/assets/18695558/24242844/0fa487aa-0ff4-11e7-9cf6-3fe8cadde0ae.png)

My setting:
Python 2.7.13
Tensorflow Release 1.0.1
bazel Build label: 0.4.5-homebrew

**Comment by aselle** [comment]
@jart, do you have any ideas on this?

**Comment by star277hk** [comment]
@aselle I already fixed by changing bazel-bin/tensorflow/examples/image_retraining/retrain 
in line 51 to return PYTHON_BINARY.

**Comment by mddrill** [comment]
@star277hk Can you tell me how you fixed this? Line 51 on tensorflow/tensorflow/examples/image_retraining/retrain.py is a comment

**Comment by mddrill** [comment]
Got it, I had to remove the first slash from PYTHON_BINARY in bazel-bin/tensorflow/path/to/executable

**Comment by twairball** [comment]
As above comments mentioned, this error message occurs when `PYTHON_BINARY` starts with `//` . This happened for me as my python binary was `//anaconda/bin/python`.
