### ISSUE TITLE
My tensorboard can not show anything. 

### ISSUE THREAD

**Issue by yuanchen1122** [tensorflow/tensorflow#8659]
(The code didn't show any errors and my Brower is firefox)What's wrong with it ?

**Comment by jubjamie** [comment]
You really need to post more information. Can you use the template provided by the tensorflow folks to give an idea of the issue.
You are creating summaries etc. aren't you? Please give us some environment info, tf version and your code.

**Comment by gunan** [comment]
Closing the issue due to inactivity.
