### ISSUE TITLE
graph_editor.graph_replace produces WARNING

### ISSUE THREAD

**Issue by lucfra** [tensorflow/tensorflow#8661]
Since version 1.0.0 the method `tensorflow.contrib.graph_editor.graph_replace` raises the following warning:

WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.

 

### Minimal reproducible example 
```python 
import tensorflow as tf
import tensorflow.contrib.graph_editor as ge
a = tf.constant(1)
b = tf.constant(2)
c = tf.constant(3)
d = a +  b
e = ge.graph_replace([d], {a: c})
```

### Output log
INFO:tensorflow:Copying op: add
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
WARNING:tensorflow:VARIABLES collection name is deprecated, please use GLOBAL_VARIABLES instead; VARIABLES will be removed after 2017-03-02.
INFO:tensorflow:Finalizing op: add

**Comment by skye** [comment]
@purpledog

**Comment by aselle** [comment]
Since this is in contrib, we do not officially support this. @purpledog is the original author, but it should be easy to search in the code and find how to switch silence this warning. So a PR would be most welcome. Thank you!

**Comment by rthadur** [comment]
As Contrib folder is deprecated , this issue is not relevant.closing this issue.
