### ISSUE TITLE
`dynamic_rnn`'s docstring refers to a non-existing `rnn` function

### ISSUE THREAD

**Issue by tgy** [tensorflow/tensorflow#8666]
Here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn.py#L392

The docstring of the `dynamic_rnn` function refers to a non-existing `rnn` function.
I don't know if it got deleted or moved somewhere else.

**Comment by skye** [comment]
@fchollet could you look into updating the documentation? Feel free to redirect as necessary.

**Comment by itsmeolivia** [comment]
good catch: waiting for the change to propagate through
