### ISSUE TITLE
regarding best approach to update tensorflow without affecting other installed packages

### ISSUE THREAD

**Issue by wenouyang** [tensorflow/tensorflow#8671]
We have maintained a virtual environment to hold all the deep learning-related development projects. In this environment, we have installed `tensorflow, keras, theano` and quite a lot other` python` libraries for project purposes.

Currently, I would like to update `tensorflow `from `0.12.0-rc0` to `1.0`. To keep the current development environment, which is shared by other users, I don’t want to change the current virtual environment at all.

I am thinking of the following options,

1) Create another virtual environment, have `tensorflow `with the latest version of `1.0`

2) Are there any ways to just copy or link all the other python packages in the old environment to the new virtual environment? I just do not want to re-install everything.

Thank you for the advice!

**Comment by nelson-liu** [comment]
I think you want `pip install --no-deps {tensorflow or tensorflow-gpu}` (assuming you're using pip). This upgrades tensorflow without touching the dependencies.

**Comment by gunan** [comment]
This is not a TensorFlow issue. It is merely a request for help with pip/python package management. Such questions are better suited for StackOverflow. Please use github for reaching out to TensorFlow development team about issues in TF itself.

Closing the issue.
