### ISSUE TITLE
wrong libjpeg version for 1.1.0-rc0 gcr docker image 

### ISSUE THREAD

**Issue by deuteron** [tensorflow/tensorflow#8674]
While running the Mandelbrot Set on the latest docker image on gcr.io, there is the following error:

IOError: encoder error -2 when writing image file

In the console: there is real error message:
Wrong JPEG library version: library is 90, caller expects 80

It shall be the latest image as of Mar 23.
16715e3f77e1 
tagged: 1.1.0-rc0  latest

Full command is:
$ docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow

The same code works fine on the Docker Hub image.
$ docker run -it -p 8888:8888 tensorflow/tensorflow

**Comment by caisq** [comment]
Hmm, I tried the MandelBrot Set example in tensorflow/tensorflow:1.1.0-rc0  and tensorflow/tensorflow:1.1.0-rc0-py3. It seems to work fine in both docker images.

**Comment by gunan** [comment]
@deuteron Could you provide a full bash script to reproduce the problem.

**Comment by rayhu** [comment]
Thank you guys. The issue of gcr image is gone. I am not aware of anything I did differently this time.

**Comment by gunan** [comment]
Thanks for checking again. I will then close this issue.
