### ISSUE TITLE
Udacity not_mnist notebook broken double quotes

### ISSUE THREAD

**Issue by pzelasko** [tensorflow/tensorflow#868]
When trying to run tensorflow/examples/udacity/1_notmnist.ipynb in my ipython notebook (tried versions 4.0 and 3.2.1), I got a NotJSONError:

[W 22:14:13.940 NotebookApp] Unreadable Notebook: /home/pzelasko/tensorflow/tensorflow/examples/udacity/1_notmnist.ipynb NotJSONError('Notebook does not appear to be JSON: u\'{\\n  "worksheets": [\\n    {\\n      "ce...',)

I found the culprit by loading the file using json module in python:

In [11]: s = open('1_notmnist.ipynb').read()
In [12]: json.loads(s)
(...)
ValueError: Expecting , delimiter: line 187 column 431 (char 9558)

It turned out to be non-escaped double quotes inside json string. After chaning them to single quotes the notebook loaded correctly.

**Comment by vincentvanhoucke** [comment]
This was just rolled back.

**Comment by LopezGG** [comment]
Unfortunately the problem still exists

**Comment by vincentvanhoucke** [comment]
Fixed with pr #1611

**Comment by yavigol** [comment]
Vincent.  I just got the same issue:
"Error loading notebook
Unreadable Notebook: C:\Users\Yaroslav\Documents\Knowledge\Udacity - Deep Learning\1_notmnist.ipynb NotJSONError('Notebook does not appear to be JSON: u\'\\n\\n\\n\\n<!DOCTYPE html>\\n<html lang="e...',)"

should I use some trick for the notebook to work?

**Comment by vincentvanhoucke** [comment]
The notebook at head parses well on GitHub:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/udacity/1_notmnist.ipynb
It didn't last time around, so you have a different problem. Would need to see repro steps.

**Comment by yavigol** [comment]
Vincent, thank you for your response!  I did the following:

1) downloaded 1_notmnist.ipynb from the "Assignment 1: notMNIST" page of the Deep Learning course (https://classroom.udacity.com/courses/ud730/lessons/6370362152/concepts/63703142310923)
2) ran the Jupyter Notebook environment from Anaconda.  Jupyter tab opened in Chrome
3) put 1_notmnist.ipynb into a folder, visible through the "Files" tab of the environment
3) found the file through the "Files" tab and clicked on it to open

P.S. Unfortunately my experience with Jupyter Notebooks is quite limited.  Therefore it is likely that I am trying to open the file in a wrong way..

**Comment by TomMiller** [comment]
Happened for me as well.
IPython 5.4.1 (Jupyter 4.3.0)

$ wget https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/udacity/1_notmnist.ipynb
$ md5sum 1_notmnist.ipynb 
f8261a76e67ccc7cc1ac2718ad7bc3d9  1_notmnist.ipynb
$ jupyter notebook 1_notmnist.ipynb
[I 20:26:37.275 NotebookApp] Serving notebooks from local directory: /home/USER/udacity/deep_learning
[I 20:26:37.275 NotebookApp] 0 active kernels 
[I 20:26:37.275 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=d9e0b86be1407ebf71dfc18f870c5c705c648ace106ac484
[I 20:26:37.275 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 20:26:37.276 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=d9e0b86be1407ebf71dfc18f870c5c705c648ace106ac484
Created new window in existing browser session.
[I 20:26:37.813 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[W 20:26:38.291 NotebookApp] Unreadable Notebook: /home/USER/udacity/deep_learning/1_notmnist.ipynb NotJSONError("Notebook does not appear to be JSON: u'\\n\\n\\n\\n\\n\\n<!DOCTYPE html>\\n<html lan...",)
[W 20:26:38.291 NotebookApp] 400 GET /api/contents/1_notmnist.ipynb?type=notebook&_=1501633598051 (127.0.0.1) 4.79ms referer=http://localhost:8888/notebooks/1_notmnist.ipynb
[W 20:26:38.326 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20170801202637 (127.0.0.1) 10.89ms referer=http://localhost:8888/notebooks/1_notmnist.ipynb

**Comment by vincentvanhoucke** [comment]
@TomMiller if the notebook you get starts with 'u'\n\n\n\n\n\n\n<html lan..., I would take a look at the rest of the HTML, seems like you might be getting an error response to your wget command instead of the actual notebook.

**Comment by TomMiller** [comment]
Thanks Vincent. The issue was that I shouldn't have been using wget at all. I thought that would get me the 1_notmnist.ipynb file, but instead it downloaded the web page view of the 1_notmnist.ipynb file. I cloned the tensorflow repository, and opening the file in the repository worked just fine.

**Comment by aganatramoat** [comment]
Click on the 'raw' button and then the url `https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/examples/udacity/1_notmnist.ipynb` turns up. Thats the json representation
