### ISSUE TITLE
Retrained inception v3 model from retrain.py takes 8-10 seconds to classify an image vs 1-2 seconds taken by sample TFClassify application

### ISSUE THREAD

**Issue by Bruczzz** [tensorflow/tensorflow#8682]
Hi,

I am using tensorflow image classification in my project. 

Initially i built and installed Camera Demo from GitHub link : https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android

Case 1: On running this example application (**TFClassify**) it is taking 1 or 2 seconds to do classification and shows result.

_**(On the other hand)**_

Case 2: If I use my retrained inception V3 model (which I have retrained using retrain.py) in same example application by placing the retrained model and labels fie in assets package it is taking 8- 10 seconds to classify per image.

Example application is using inception 5h model i guess and retrain.py is using inception V3 - I am not sure that the difference in classification time is because of this difference in models used, if so I could not find a way to use inception 5h model in retrain.py, it is giving an error :

_ValueError: Requested return_element 'pool_3/_reshape:0' not found in graph_def._
 

Is there a way to reduce the image classification time for the retrained inception V3 model? 

Thanks

**Comment by left13** [comment]
inception v3 is bigger than 5h and I think the difference in speed that you see is normal.
I run the demo(5h model) at 170ms-450ms on each prediction on a s7 edge exynos and retrained v3 at 800ms-1.5 sec
Using the graph tool here [eight-bit-calculations](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md#eight-bit-calculations) I managed to drop at 450ms-800ms on a v3 retrained model but had weird results that i'm waiting to be resolved soon.(check [here](https://github.com/tensorflow/tensorflow/issues/7150) for issues if you try the transform tool).

**Comment by aselle** [comment]
@left13 analysis matches my intuition, so closing for now. I.e. it is a bigger model. TFClassify has also been quantized and reduced. This information is clear on the documentation https://www.tensorflow.org/mobile/
 Thanks!

**Comment by SubhashKsr** [comment]
Hi,
@aselle can you educate me more about inception5h. I would like to know why there is a time difference between inceptionV3 and inception5h models(Like why is it not inceptionV5, why is it not listed in the models list [here](https://github.com/tensorflow/models/tree/master/slim), is inceptionV5 retrained on some other models like inceptionV3?). 

As @left13 mentioned, even I am able to run the demo(5h model) at 170ms-450ms on each prediction on OnePlus3T device and my [retrained](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py) &[optimized](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/optimize_for_inference.py) v3 at 1500ms-2100ms

@left13 I tried [eight-bit calculations](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md#eight-bit-calculations). The inference time has slightly improved to 1200ms~1500ms, but the classification part dosent work, for any image you pass, it shows a constant output(Tested on OnePlus3T device).

I understand from my experiments that after quantization and [eight-bit calculations](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md#eight-bit-calculations), the size of APK/model has decreased from 82.1 MB to 19.6MB but the result is same:"Image classification dosent work"

Is it possible to retrain inception5h model on my own data?

**Comment by ivamluz** [comment]
I've tried the following approaches:

```
bazel-bin/tensorflow/tools/quantization/quantize_graph \
  --input=/path/to/input/graph.pb \
  --output_node_names="final_result" \
  --output=/path/to/output/graph.pb \
  --mode=eightbit

```
For this approach, it always return a single wrong result with 100% certainty.

-------------------
```
bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
  --in_graph=/path/to/input/graph.pb \
  --out_graph=/path/to/output/graph.pb \
  --inputs=Mul \
  --outputs=final_result \
  --transforms='
  add_default_attributes
  strip_unused_nodes(type=float, shape="1,299,299,3")
  remove_nodes(op=Identity, op=CheckNumerics)
  fold_old_batch_norms
  quantize_weights
  quantize_nodes
  strip_unused_nodes'
```
and

```
bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=/path/to/input/graph.pb \
--out_graph=/path/to/output/graph.pb \
--inputs='Mul' \
--outputs='final_result' \
--transforms='
  add_default_attributes
  strip_unused_nodes(type=float, shape="1,299,299,3")
  remove_nodes(op=Identity, op=CheckNumerics)
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  quantize_weights
  quantize_nodes
  strip_unused_nodes
  sort_by_execution_order'
```

For both of these, the results are similar. There is some variance to the results returned (sometimes different values with around 20% or 50% variance), but a specific result is most of the times returned with 100% certainty as well, even though it's wrong.

@SubhashKsr, did you manage to fix this?

Any help is much appreciated.
