### ISSUE TITLE
Unable to restore inception v3 retrained model

### ISSUE THREAD

**Issue by rohitkumargupta1000** [tensorflow/tensorflow#8685]
I'm retraining the inception v3 model on my image dataset. I use tf.Saver() to store the model at the time of best validation accuracy. But when I'm using the stored model to do the validation again, I don't get the same accuracy. 

Please let me know if I'm missing anything specifically with inception v3 model. I want store the entire inception v3 graph along with newly added layers, so that I can reuse it normally.

code snippet : 
saver.save(sess=sess, save_path=save_path + "best_valid", global_step=i)

Thanks,
Rohit

**Comment by rohitkumargupta1000** [comment]
with gfile.FastGFile(FLAGS.output_graph, 'wb') as f:
    f.write(output_graph_def.SerializeToString())

I' getting  following exception while saving the protobuf file :

raise_exception_on_not_ok_status
tensorflow.python.framework.errors_impl.FailedPreconditionError: ./output_graph.pb

**Comment by aselle** [comment]
Perhaps try using the full path rather than a relative path? Try that and let us know if that works. Thanks!

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
