### ISSUE TITLE
Error in description of outputs of rnn_decoder

### ISSUE THREAD

**Issue by pender** [tensorflow/tensorflow#869]
rnn_decoder is described as follows:

```
def rnn_decoder(decoder_inputs, initial_state, cell, loop_function=None,
                scope=None):
  """RNN decoder for the sequence-to-sequence model.
...
Returns:
...
    states: The state of each cell in each time-step. This is a list with
      length len(decoder_inputs) -- one item for each time-step.
```

States output does not appear to have the length as the decoder inputs. For example, the following script --

```
import tensorflow as tf
from tensorflow.models.rnn import rnn_cell
from tensorflow.models.rnn import seq2seq
batch_size = 4
seq_len = 5
num_layers = 3
vocab_size = 26
rnn_size = 100
cell = rnn_cell.MultiRNNCell([rnn_cell.BasicLSTMCell(rnn_size)] * num_layers)
input_data = tf.placeholder(tf.int32, [batch_size, seq_len])
embedding = tf.get_variable("embedding", [vocab_size, rnn_size])
decoder_inputs = tf.split(1, seq_len, tf.nn.embedding_lookup(embedding, input_data))
decoder_inputs = [tf.squeeze(input_, [1]) for input_ in decoder_inputs]
outputs, states = seq2seq.rnn_decoder(decoder_inputs, cell.zero_state(batch_size, tf.float32), cell)
print "Length of states is {}, but length of decoder inputs is {}".format(len(states), len(decoder_inputs))
```

gives the following output:

```
Length of states is 6, but length of decoder inputs is 5
```

This is still true if you replace BasicLSTMCell with GRUCell.

Is it correct to say that the length of states is equal to *one greater than* the length of decoder inputs? Seems to be true from playing around with it. Is this a fencepost error, where the states include the zeroth state *plus* the state following each decoder input?

**Comment by ebrevdo** [comment]
This api is about to change. From now on rnn() and its cousins will return just the very last state instead of a list of intermediate states.

**Comment by pender** [comment]
Makes sense, that's how I've seen it used every time anyway. Thanks. I'll
close the issue.
