### ISSUE TITLE
CUDA 8.0 with Xcode 8.0

### ISSUE THREAD

**Issue by ansu1234** [tensorflow/tensorflow#8693]
I am not able to install CUDA 8.0 with Xcode 8.0 version. Everywhere i found the solution to downgrade the version of Xcode. Is there any other solution without downgrading the version of Xcode.

**Comment by Miroboru** [comment]
Xcode 8.2.1 (8C1002) works with CUDA ToolKit V8.0.61, at least for me.

**Comment by gunan** [comment]
As far as I can tell, you are having problems installing CUDA.
You will need to reach out to NVIDIA, use stackoverflow, or browse nvidia forums for this question.
Please only use our github repositories issues for bugs in TensorFlow itself.
