### ISSUE TITLE
Lower libc version on tensorflow:1.1.0-rc0-devel

### ISSUE THREAD

**Issue by malmaud** [tensorflow/tensorflow#8697]
Building libtensorflow.so with the Docker 1.10-devel-rc0 image results in a binary that requires glibc 2.23. Since that is aggressive for many current machines, might it make sense to reduce the dependency to eg 2.17?

**Comment by malmaud** [comment]
Ah, I see https://github.com/tensorflow/tensorflow/issues/53 so seems like this is probably a 'won't fix'.

**Comment by drpngx** [comment]
@craigcitro @gunan

**Comment by craigcitro** [comment]
I'm out of the loop, @gunan or @martinwicke seems more likely to have a good answer here.

**Comment by gunan** [comment]
@jhseu @caisq FYI

The requirement is due to docker images being based off of ubuntu 16.04, which has a higher glibc version. Our prebuilt binaries are built on ubuntu 14.04, which does not have this requirement.

**Comment by caisq** [comment]
@malmaud, you want to build a custom version of libtensorflow, right? 
Our release libtensorflow is still built with 14.04, e.g., http://ci.tensorflow.org/view/Release/job/release-libtensorflow/20/TYPE=cpu-slave/

**Comment by martinwicke** [comment]
@yifeif FYI

You can edit the dockerfile to be `FROM ubuntu14.10`, which should fix this issue. We upgraded to ubuntu16 since 14 is getting seriously old.

**Comment by martinwicke** [comment]
Also, we should probably remove Craig from the MAINTAINER line.

**Comment by malmaud** [comment]
Sure, for my own purposes I can just edit the FROM line and rebuild. 

I think an argument could potentially be made that if the purpose of the developer images is primarily to enable building TensorFlow, it would make sense to try to configure those images in a way that the resulting images are compatible with as wide a collection of systems as possible, which isn't true if the resultant binaries are linked against libc 2.23. But if you guys feel differently, no problem and thanks for your help.

**Comment by jhseu** [comment]
There are bugs when running on Ubuntu 14.04, so we'd prefer to keep any images where users might run TensorFlow on more recent versions of Ubuntu.
