### ISSUE TITLE
Graph Transforms | quantize_nodes | Android TensorFlow Inference | native error

### ISSUE THREAD

**Issue by Androbin** [tensorflow/tensorflow#8698]
I am using the Graph Transforms Tool (built with Bazel) to prepare my graph for Android TensorFlow Inference.

When using `--transforms='quantize_weights'` everything works just fine.
But with `--transforms='quantize_weights quantize_nodes'` I get this:

```
I/TensorFlowInferenceInterface: Checking to see if TensorFlow native methods are already loaded
I/TensorFlowInferenceInterface: TensorFlow native methods already loaded
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 22562 (obin.loremipsum)
        
        [ 03-24 19:19:10.194   375:  375 W/         ]
        debuggerd: handling request: pid=22562 uid=10173 gid=10173 tid=22562
```

I don't have any clue on what has happened.
I wasn't able to find anything related online.

**Comment by aselle** [comment]
Please specify your platform version and versions of TensorFlow @Androbin.
Are there any usual pitfalls @petewarden that cause a segfault like this?

**Comment by Androbin** [comment]
I built TensorFlow from source (last update: yesterday) with CUDA 8.0 and cuDNN 5.1 on Ubuntu 16.04.2, downloaded the Inference Library from [nightly-android#79](https://ci.tensorflow.org/view/Nightly/job/nightly-android/79/) and running the inference on a Nexus 6P as host device.

**Comment by Androbin** [comment]
May be related to #7217

**Comment by Androbin** [comment]
I experimented a bit with the graph transformation and discovered that the problem seems to be `merge_duplicate_nodes` which is called by `quantize_nodes` #8897

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Comment by Androbin** [comment]
Waiting for merge of probable fix:
https://github.com/tensorflow/tensorflow/issues/11182#issuecomment-315771292
