### ISSUE TITLE
2d gradients have a second dimension of size None

### ISSUE THREAD

**Issue by AndrewBezold** [tensorflow/tensorflow#870]
When calling compute_gradients with 2d variables, the first dimension has the correct size while the second dimension has a size of None.  Is this intentional?  It makes it somewhat difficult when processing the gradients, as a dimension size of None isn't really compatible with anything else.

Tested with:
2d variables - second dimension is size None, first dimension is size of first dimension of variable
1d variables - dimension is size of dimension of variable
Tested using compute_gradients in AdamOptimizer

**Comment by mrry** [comment]
As I [answered](http://stackoverflow.com/a/34996139/3574081) on StackOverflow, this is intended behavior when a dimension cannot be statically inferred. In fact, a dimension size of `None` is compatible with *every* concrete dimension size (it acts as a wildcard), and any constraints will be checked at runtime.
