### ISSUE TITLE
Debug tool not fully installed in Windows version

### ISSUE THREAD

**Issue by ybsave** [tensorflow/tensorflow#8703]
First of All: WINDOWS environment!

I have installed the tensorflow 1.0 (Python 3.5, Cuda 8.0, Cudnn 5) in Windows using the official command pip3 install --upgrade tensorflow-gpu. Although there are some minor bugs, I have fixed them by myself, and the tensorflow mostly works OK. However, when using the tensorflow debug tool, I find it failed. 

The reason is that the python files in folder tensorflow\python\debug are not generated from the most updated proto files. For example, in the generated "debug_pb2.py", there are no "global_step" for Message DebugOptions. I checked the most updated tensorflow codes, the debug.proto does have that "global_step". 

I have done some manual modifications of the debug_pb2.py to add necessary parameters. Now the error is 

File "C:\Users\XXX\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\debug\lib\debug_data.py", line 519, in __init__
    raise IOError("Dump root directory %s does not exist" % dump_root)
OSError: Dump root directory C:\Users\XXX\AppData\Local\Temp\tfdbg_8u5q2tve does not exist

I have already run the codes under the administrator mode. 

My questions are:
1. Whether there is any method to just re-generate the debug tool related files using the most updated proto files stored in my local disk?
2. Is there any way to rebuild the tensorflow using the online source codes, which seem to be for Linux?
3. If not possible, is there anyway to manual fix the above error?

Thank you.

**Comment by caisq** [comment]
@ybsave TensorFlow Debugger (tfdbg) is known to have issues in version 1.0.x on Windows. See issue https://github.com/tensorflow/tensorflow/issues/7615. Can you try the latest release candidate, namely 1.1.0rc0?

Also beware that the debug_pb2.py file is not an essential feature of tfdbg. It is related to something still under development.

**Comment by ybsave** [comment]
The new version 1.1.0rc0 works well. The problem disappears. Thank you so much for your quick help!

**Comment by Charan-Karthikeyan** [comment]
I have a ImportError: cannot import name 'debug_pb2' in ubuntu 16.04 when importing tensorflow

**Comment by caisq** [comment]
@Charan-Karthikeyan, I tried the following commands, in the ubuntu:16.04 docker container and it seems to work correctly. Is it possible that your environment has some older versions of tensorflow causing some sort of interference? If so, can you try uninstalling them?

```
docker run -it --rm docker:16.04
apt-get update
apt-get install python python-pip
pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.1.0rc0-cp27-none-linux_x86_64.whl
python -m tensorflow.python.debug.examples.debug_mnist --debug

```
