### ISSUE TITLE
gcc: error: unrecognized command line option '-fno-canonical-system-headers'

### ISSUE THREAD

**Issue by Anida-qin** [tensorflow/tensorflow#8709]
when I run :
`bazel build --config=opt --config=cuda --verbose_failures //tensorflow/tools/pip_package:build_pip_package`

INFO: Found 1 target...
ERROR: /home/qs/.cache/bazel/_bazel_qs/081cd1dbca77dcff65c775e7e860e873/external/farmhash_archive/BUILD.bazel:12:1: C++ compilation of rule '@farmhash_archive//:farmhash' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/qs/.cache/bazel/_bazel_qs/081cd1dbca77dcff65c775e7e860e873/execroot/tensorflow && \
  exec env - \
    LD_LIBRARY_PATH=/usr/local/cuda-7.5/lib64/:/usr/lib32/:/usr/lib/x86_64-linux-gnu/::/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64 \
    PATH=/bin:/usr/bin:/home/qs/mysoft/jdk1.8/bin \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections -g0 '-std=c++11' -MD -MF bazel-out/host/bin/external/farmhash_archive/_objs/farmhash/external/farmhash_archive/src/farmhash.d '-frandom-seed=bazel-out/host/bin/external/farmhash_archive/_objs/farmhash/external/farmhash_archive/src/farmhash.o' -iquote external/farmhash_archive -iquote bazel-out/host/genfiles/external/farmhash_archive -iquote external/bazel_tools -iquote bazel-out/host/genfiles/external/bazel_tools -isystem external/farmhash_archive/src -isystem bazel-out/host/genfiles/external/farmhash_archive/src -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c external/farmhash_archive/src/farmhash.cc -o bazel-out/host/bin/external/farmhash_archive/_objs/farmhash/external/farmhash_archive/src/farmhash.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: error: unrecognized command line option '-fno-canonical-system-headers'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 1.003s, Critical Path: 0.49s

How to solve this problem?

**Comment by Anida-qin** [comment]
I use ubuntu14.04
         cuda7.5
         cudnn5.1
         gcc4.7.3
         bazel0.4.5
         tensorflow r1.0

**Comment by aselle** [comment]
@jart, could you take a look. Could it be too old of a version of gcc?

**Comment by jart** [comment]
Thank you for bringing this to our attention @Anida-qin. It seems you did your homework and discovered a closed duplicate https://github.com/tensorflow/tensorflow/issues/3618 although it helps when you bring that to our attention.

It seems the Bazel site [claims](https://bazel.build/versions/master/docs/install-ubuntu.html) Ubuntu 14.04 is out of their support matrix, which I find peculiar, because that's what Google installed on my workstation. It's not EOL until 2019. It is in the TensorFlow support matrix. (Attn: @damienmg)

@Anida-qin GCC 4.8 is [available](http://packages.ubuntu.com/trusty/allpackages) on Ubuntu 14.04. If you were to apt-get install those, would it help?

**Comment by damienmg** [comment]
Ubuntu 14.04 is supported. That was an update error (adding 16.04 in the
list was the actual intent).

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by JoyChopra1298** [comment]
What is the solution to this problem? I am running it on a CentOS 6 cluster and gcc 4.8.2 is installed on cluster and using bazel 0.4.5

**Comment by gunan** [comment]
As @jart mentioned, could you try updating to gcc 4.8 and try with that?

**Comment by martinsik** [comment]
I had a lot of similar weird compilation issues os OS X. I had to [completely uninstall `bazel`](https://github.com/bazelbuild/bazel/issues/838) and remove its cached files like this:

    sudo rm -rf /private/var/tmp/_bazel_martin
