### ISSUE TITLE
major memory allocation/copying overhead in Android Inference Library

### ISSUE THREAD

**Issue by Androbin** [tensorflow/tensorflow#8712]
There seems to be a major overhead in [`TensorFlowInferenceInterface.feed(...)`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/android/java/org/tensorflow/contrib/android/TensorFlowInferenceInterface.java#L257)
When running the feed-run-fetch cycle, I noticed that feeding took an unreasonable amount of time.

So I looked at the source code. I realized that I could pass a Buffer instead of an Array, because it would have been wrapped anyway. But either way a new Tensor object is created in [`Tensor.create(...)`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/main/java/org/tensorflow/Tensor.java#L128) which includes first [allocating the memory](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/main/java/org/tensorflow/Tensor.java#L204) and then copying over from the passed Buffer.

Although this seems to be okay, when doing some Method Tracing, I discovered that when doing one cycle of feeding, running and fetching, it spends 99.99% with feeding, specifically 99.99% of that with creating the Tensor and 99.99% of that with copying over from the Buffer.

The chart is really packed with `FloatBuffer.put(...)`

Why isn't it possible to use the just newly created Buffer directly?
Or why isn't the final Buffer filled directly from the Array?

**Comment by andrewharp** [comment]
@asimshankar Any ideas here?

**Comment by asimshankar** [comment]
Could you elaborate a bit on the major overhead? The relative numbers would depend on the computation  being performed. For example, in [label image example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/main/java/org/tensorflow/examples/LabelImage.java), where the image fed is about 600KB (~150K 32-bit floats), creating the `Tensor` takes about ~100μs while executing the model takes about 30ms on my machine.

That said, yes, you're right in that the current feed API requires a copy. It should be precisely one copy (note that `FloatBuffer.wrap()` etc. should normally not involve an array copy) - from the Java `FloatBuffer` object to the underlying `Tensor` object in C memory. If you see more than one copy, do let us know.

We do not provide direct access to the C memory for safety reasons. For example, there is a private method ([`Tensor.buffer()`](https://github.com/tensorflow/tensorflow/blob/2acba51/tensorflow/java/src/main/java/org/tensorflow/Tensor.java#L472)) that provides a view of the underlying C memory as a Java `ByteBuffer`. However, that isn't safe for general use as bad things would happen if say one released native memory (via `Tensor.close()` perhaps) and before accessing the contents of the buffer (e.g., `ByteBuffer buf = t.buffer(); t.close(); doSomethignWith(buf);`)

The other option which I think you're asking about would be to avoid the C `Tensor` object allocating more memory and instead have it reference the Java `Buffer` object's underlying memory directly. That might be workable, modulo memory alignment requirements of the various TensorFlow kernels and some care to ensure that it is safe (for example, we wouldn't want the JVM's garbage collector from cleaning up the underlying memory while native code is executing a graph that requires it).

That might be worth investigating. I was expecting that in practice both the time and space costs of copying feed tensors would be dwarfed by the computation costs of executing models (except perhaps in toy models), like in the label image example. However, if that is not the case, this optimization might be a good idea to pursue. Do you have some more details that you might be able to share on your use case?

**Comment by Androbin** [comment]
Thanks for the elaboration!

My graph should look roughly like this:
```
placeholder [None, 12593]
reshape [None, 49, 257, 1]
conv2d (5, 5, 32) [None, 49, 257, 32]
max_pool (2, 4) [None, 25, 65, 32]
conv2d (7, 7, 64) [None, 25, 65, 64]
max_pool (2, 4) [None, 13, 17, 64]
dense (1024) [None, 1024]
dense (2) [None, 2]
```

btw. batch size is 1 during inference

**Comment by asimshankar** [comment]
Could you also share the profiling code you use to determine the 99.9% cost for feeding (and perhaps the absolute numbers of those times)? I'm surprised that the copies will be costing you 99% in such a graph.

**Comment by Androbin** [comment]
@asimshankar I just used the built-in "Method Tracing" functionality of ADB as it is directly integrated in Android Studio.

**Comment by andrewharp** [comment]
@Androbin @asimshankar I just gave this a shot on my own. I think something about the method tracing in Android Manager is interfering with the operation of the inference thread, as I noticed the iterating speed slows down by more than an order of magnitude.

If I directly log the relevant sections while running Inception v1 (5h) on my Pixel with org.tensorflow.demo.env.SplitTimer, I get this:
```
03-27 16:56:47.036  6848  6961 I tensorflow: classifier: preprocessBitmap: cpu=1ms wall=2ms
03-27 16:56:47.053  6848  6961 I tensorflow: classifier: feed: cpu=14ms wall=17ms
03-27 16:56:47.389  6848  6961 I tensorflow: classifier: run: cpu=63ms wall=336ms
03-27 16:56:47.390  6848  6961 I tensorflow: classifier: float: cpu=0ms wall=0ms
```

feed might be something to take a look at optimizing if possible, but in reality it's only taking about 5% of the total walltime spent processing each frame.

**Comment by Androbin** [comment]
@asimshankar So, what would have the least overhead?
Filling a previously allocated float[] and finally calling `FloatBuffer.wrap(float[])` each time
or calling `FloatBuffer.put(float)` on a previously allocated direct buffer in native byte order?

**Comment by asimshankar** [comment]
@Androbin : That is probably more suited as a question on [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) as we try to keep github issues focused on TensorFlow bugs and feature requests.

Since the original issue here seems to be some issue with the interaction with the Android Method Tracer, but not really a performance issue with the feed, I'm tempted to close this out. (If you get any more information about how this might be an issue with the TensorFlow Java API, please do create a new issue with as much detail as you can add).

Regarding your question though, I believe all the following will be pretty much equivalent in terms of performance (they all involve one copy of the data from JVM-managed memory to native memory):

```java
Tensor.create(shape, FloatBuffer.wrap(array));
Tensor.create(shape, floatBuffer);
```

More details for the performance of various API calls of `java.nio.FloatBuffer` are probably better directed at Java/NIO experts.

Hope that helps.
Thanks!

**Comment by Androbin** [comment]
Okay, after applying some additional optimizations on the computation graph, the "run" section makes up for at least a fifth of the "feed" section. Anyway, this still doesn't seem correct just jet.

**Comment by andrewharp** [comment]
Can you provide more details, such as the device you are using, the input size, and the exact timings? I don't understand what you mean by "run" making up a fifth of the "feed" section. They are run independently and sequentially, and feed should be at least an order of magnitude smaller than run in most cases.

Is this still using the Android Device Manager to trace code? I don't think you can trust the numbers it provides -- you'd be better off manually timing sections or using another tool until we figure out what's going on there.

**Comment by Androbin** [comment]
@andrewharp I am sorry, if I was too unclear.
I am using a **Nexus 6P** as host device.
Input size (**12593**) and model architecture are given by #issuecomment-289561458
I will now measure the times myself and post the results.

Sorry for the confusion: I am referring to the (recently renamed) methods of [`TensorFlowInferenceInterface`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/android/java/org/tensorflow/contrib/android/TensorFlowInferenceInterface.java). Previously, `feed` was the only one to be listed at all. After some changes to the computation graph, `run` is now said to account for about a fifth of the time that `feed` takes and `fetch` wasn't listed so far.

Yes, I know that they are independent from one another but they are usually called together.
I am looking forward to my manual measuring results.

Yes, I am still using the Android Monitor over ADB to perform Method Tracing.

**Comment by Androbin** [comment]
Okay, `TimingLogger` delivers reasonable results:
feed: 3-4 ms
run: 250-270 ms
fetch: 0-1 ms

**Comment by andrewharp** [comment]
Right, there's a problem with the adb method tracing, so until we figure out what is going on there it seems you can't rely on the timings it gives.
