### ISSUE TITLE
Configure should work offline

### ISSUE THREAD

**Issue by gaohuazuo** [tensorflow/tensorflow#8713]
Currently, `configure` set some environment variables and invoke `bazel fetch`. When the fetch fails, due to network issue for example, the environment variables are also lost. I tried to `source ./configure`, but the shell died instantly. The only way I found to workaround this is to replace `bazel fetch` with `bash` in `configure`, then manually run `bazel fetch` a few times until it succeed. IMHO, `configure` should do the configuration separately instead of as part of `bazel fetch`.

**Comment by gunan** [comment]
As a workaround, you can simply comment out all calls to `bazel_clean_and_fetch` in configure script to achieve what you need.

@damienmg Do we still need to run bazel fetch separtely during configure with bazel 0.4.5?
Can bazel fetch be run automatically when we are running bazel build?

**Comment by damienmg** [comment]
Gunan: with the --action_env flag I added to the .bazelrc in #8637 we
should be good to remove bazel_clean_and_fetch and we can let the fetch
happens with the build command.

**Comment by gunan** [comment]
Thanks for the tip.
Then I am sending #8761 to test it out and remove bazel fetch from configure.
