### ISSUE TITLE
RecordReader reads disk without buffer

### ISSUE THREAD

**Issue by snnn** [tensorflow/tensorflow#8715]
tensorflow::io::RecordReader calls RandomAccessFile::Read() directly, without go through IoBuffer.
And RandomAccessFile::Read() will call pread(2) or ReadFile OS API.
If there is an IoBuffer between them, it could reduce a lot of syscalls. 

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

None

### Environment info
Operating System:
Windows 10

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
None

if installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
c7b80d51da4fb6d51ea54a0bdf2601afa379d60c

2. The output of `bazel version`
(compiled by cmake and vs 2017)

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
None

### What other attempted solutions have you tried?
None

**Comment by drpngx** [comment]
That might be a good candidate for a PR if you're willing to contribute.

@skye

**Comment by snnn** [comment]
Hi @drpngx , I'll take this.

I just found the interface is a bit inconsistent.  For compressed file, it assumes that the file will be read sequentially and it will ignore the offset parameter in 
```
  Status ReadRecord(uint64* offset, string* record);
```

So,  if this class is designed for sequential reads, I want to remove the 'offset' argument, and use ZlibInputStream for zipped file, SnappyInputStream for snappy file, RandomAccessInputStream for uncompressed file.

Is it ok?

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
