### ISSUE TITLE
*** Error in `python': double free or corruption (!prev): 0x000000000167c080 ***

### ISSUE THREAD

**Issue by yongxuUSTC** [tensorflow/tensorflow#8717]
I run : python train.py --train_data_pattern='/vol/vssp/msos/yx/audioset/audioset_v1_embeddings/unbal_train/*.tfrecord' --frame_features=True --model=DbofModel --feature_names="audio_embedding" --feature_sizes="128" --train_dir=tmp_model/frame_level_DbofModel_unbal

I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
INFO:tensorflow:/job:master/task:0: Tensorflow version: 1.0.1.
INFO:tensorflow:/job:master/task:0: No checkpoint file found. Building a new model.
INFO:tensorflow:Using batch size of 1024 for training.
*** Error in `python': double free or corruption (!prev): 0x000000000167c080 ***
Aborted (core dumped)

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty

**Comment by gunan** [comment]
Please fill in the full issue template.
Also include a minimal example to reproduce a problem.

Without knowing what you are running, we cannot really help you.

**Comment by yaroslavvb** [comment]
We've observed similar crashes. I suspect incompatibility of TensorFlow official release with Ubuntu 14.04, something possibly related to jemalloc. The work-around is to do following:

```
sudo apt-get install google-perftools
export LD_PRELOAD="/usr/lib/libtcmalloc.so.4" 

```

**Comment by gunan** [comment]
Looks like there is a workaround posted. Closing this issue.

**Comment by vgupta-ai** [comment]
Thanks @yaroslavvb 
The work-around works !

**Comment by LogicHolmes** [comment]
I don't know why I send the command:
bazel-bin/im2txt/train --input_file_pattern="${MSCOCO_DIR}/train-?????-of-00256" --inception_checkpoint_file="${INCEPTION_CHECKPOINT}" --train_dir="${MODEL_DIR}/train" --train_inception=false --number_of_steps=1000000

there have a error:
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcufft.so.8.0. LD_LIBRARY_PATH:
I tensorflow/stream_executor/cuda/cuda_fft.cc:344] Unable to load cuFFT DSO.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
*** Error in `/usr/bin/python': double free or corruption (!prev): 0x000000000231f8e0 ***
I don't know the error
