### ISSUE TITLE
Incorrect reference for tf.learn in Linear Model tutorials

### ISSUE THREAD

**Issue by kanitw** [tensorflow/tensorflow#8718]
This [page](https://www.tensorflow.org/tutorials/linear) and [this](https://www.tensorflow.org/tutorials/wide) mentions `tf.learn` multiple times. 
However, looking at the links and source code, I believe that `tf.learn` should actually be either `tf.contrib` or `tf.contrib.learn`, not `tf.learn`.

(I guess `tf.learn` was the old name, but got renamed but the tutorial is still outdated?)

**Comment by kanitw** [comment]
- [ ]  Also in the same page, the link to "linear models tutorial code" actually links to wide & deep learning tutorial.

**Comment by aselle** [comment]
Could you fix or delegate this @wolffg?

**Comment by yongtang** [comment]
Added a PR #10658 for that.
