### ISSUE TITLE
Issue while executing https://github.com/suriyadeepan/easy_seq2seq

### ISSUE THREAD

**Issue by cyberpks** [tensorflow/tensorflow#8721]
I tried running execute.py from https://github.com/suriyadeepan/easy_seq2seq however, I'm facing trouble with this.

Not sure if I'm doing something wrong, but a suggestion or a solution would be great help.

This is the dump from my Windows CMD prompt:

`C:\Users\myPC\Downloads\easy_seq2seq-master\easy_seq2seq-master>python execu
te.py`

`Traceback (most recent call last):`

`  File "execute.py", line 31, in <module>`
`    import seq2seq_model`
`  File "C:\Users\myPC\Downloads\easy_seq2seq-master\easy_seq2seq-master\seq2
seq_model.py", line 28, in <module>`
`    from tensorflow.models.rnn.translate import data_utils`
`ImportError: No module named 'tensorflow.models'`

**Comment by mckinziebrandon** [comment]
This belongs on StackOverflow, not as a github issue. tensorflow.models is a separate repository from this one. The translate directory can be found [here](https://github.com/tensorflow/models/tree/master/tutorials/rnn/translate).

**Comment by gunan** [comment]
The code referenced is not a TF owned code.
It simply seems to be out of date.
Please contact the owner of the code, or reach out to StackOverflow as @mckinziebrandon suggested.
Closing this issue.
