### ISSUE TITLE
Disturbing Grammatical error...

### ISSUE THREAD

**Issue by damilolah** [tensorflow/tensorflow#8723]
Grammatical error with this sentence...
"In this lab, we will be using transfer learning, which means we are starting with a model that has been already trained on another problem"
Correction: "has already been trained on another problem"

**Comment by gunan** [comment]
Would you like to send a pull request to fix the problem?
I have no idea which tutorial you are referring to, and all these should be checked into our repository.

**Comment by Timeroot** [comment]
The tutorial is at https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#0 -- although I don't believe this is a grammatical error.

**Comment by gunan** [comment]
I agree with @Timeroot that to me both forms look correct. And it not being on the repo may make it more difficult to fix it. So I do not know if it is worth the effort to modify.
Redirecting to @wolffg , but due to the current load, the most likely outcome for this issue is we will close it.

**Comment by aselle** [comment]
Actually, I am pretty sure this is correct grammar. already is indeed an adverb so you can use it to modify the verb in a simple sentence.
```
I already ate.
```
But in the present or past perfect it is commonly used next to the main verb instead of hte hlper verb had.
```
The plane had already landed.
```
