### ISSUE TITLE
Error occurred in Tensorflow version 1.0.1 date: 26th March 2017.

### ISSUE THREAD

**Issue by mrnameless123** [tensorflow/tensorflow#8724]
I just reinstalled Tensorflow on my laptop this morning and got this problem. 
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
b'what the hell?'

![tensorflow](https://cloud.githubusercontent.com/assets/10723417/24329241/5ffd36fe-123b-11e7-8298-c957a13b3141.PNG)

**Comment by Carmezim** [comment]
Duplicate #7859

**Comment by mrry** [comment]
This bug is fixed in the 1.1 release candidate. Please upgrade to that version or a nightly build (or else you can simply ignore the error messages, as they are harmless).

**Comment by Carmezim** [comment]
@mrry can I take the opportunity to ask you a question if you don't mind? I don't want to open an issue just for it.

I am having no luck with bazel (#8482) then I decided to build with CMake but the COMPILER_OPT_ARCH_NATIVE_SUPPORTED test fails even with the instructions available (gcc march=native shows them enabled, mavx, mfma, msse etc).
Would you have any tip on this?
Thanks!

**Comment by mrry** [comment]
I think this test fails because MSVC doesn't support the exact `-march=native` option that we use for this in GCC. I suspect there are equivalent options for MSVC to enable these instructions (perhaps @guschmue knows them off-hand), and the most likely workaround would be to modify CMakeLists.txt to use those options explicitly.

**Comment by Carmezim** [comment]
@mrry got it. Awesome, thank you! :)

**Comment by Carmezim** [comment]
@mrry I successfully built replacing `-march=native` for `/arch:[MAVX2|MFMA|MSSE4.2|MFPMATH|mmmx]` specifically.

Thank you again!

Reference: https://msdn.microsoft.com/en-us/library/jj620901.aspx

**Comment by mrnameless123** [comment]
@mrry did version 1.1 release yet?  
@Carmezim I have two laptops, one laptop works perfectly and no strange message(I installed it like 3 months ago) and the other shows I just installed Tensorflow in it yesterday and these messages show up. both have the same version.

**Comment by mrnameless123** [comment]
@mrry. @Carmezim I updated to 1.1.0rc and the problem still not resolved. Here is screen capture of my current version
![capture 3](https://cloud.githubusercontent.com/assets/10723417/24345010/1028df92-1309-11e7-86e4-9a9624f6a470.JPG)

**Comment by Carmezim** [comment]
Did you try the nightly build, if not could you try and let us know if it solved?
Thanks

**Comment by guschmue** [comment]
I think its hard to get rid of the SSE/AVX message: if ci build with, say avx2, the builds will not work on boxes that don't support avx2. If ci builds don't enable the highest instruction set, somebody will see the error messages. No easy way out other that building from source.
Should be the same on linux (just tried and see the same messages).
For some reason 1.1.0rc0 is on pypi but it does not seem to be the default download so you need to force it with:
pip install --upgrade tensorflow-gpu==1.1.0rc0

**Comment by Carmezim** [comment]
Oh, I am so sorry, I totally misread that. 
You can set TensorFlow environment variable `TF_CPP_MIN_LOG_LEVEL` to 2 as follows:
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='2'
import tensorflow as tf
```
It will filter out WARNING logs.

**Comment by Carmezim** [comment]
@guschmue would you have any insight on using `/arch` with MSVC? It seems MSVC only accepts `AVX2` option and won't build with any other instruction, even gcc showing they are available. I think I might have set something wrong when I built above because now I cannot build it anymore setting the same way.

**Comment by mrnameless123** [comment]
@guschmue thank you anyway, I did figure out the way to upgrade to 1.1.0rc0. but it doesn't help much with those Warning. I decided to wait. 
@Carmezim thank you for your support

**Comment by guschmue** [comment]
I think /arch:avx and /arch:avx2 work, the later I have used builds with. But /arch:avx2 compiles broke for the master some time ago ... can try to find time fix this (can't be much since it used to work).

**Comment by Carmezim** [comment]
@guschmue Nice. AVX2 is at least configuring, didn't try to compile yet though as were trying to figure it out how to use the others. 
So SSE and others really don't work with MSVC? Is there any workaround to compile using them as well, SSE, FMA etc with CMake?

**Comment by guschmue** [comment]
https://msdn.microsoft.com/en-us/library/7t5yh4fd.aspx says SSE and SSE2 should work too but have not tried those.

**Comment by Carmezim** [comment]
@guschmue Well noted. I personally was trying for x64 arch but is good to know. Do you know if is possible to select GCC as the compiler and build with MSYS2 for instance with `-march=native` enabled or is it too much of a hack? I know other compilers like Intel's allow SSE4.2 for instance but MSVC is a bit limited.

**Comment by guschmue** [comment]
not sure if you'd get gpu work with gcc on windows.

**Comment by Carmezim** [comment]
oh yeah, but for CPU would work something like Cygwin to build right?

**Comment by bluemonk482** [comment]
Hi @Carmezim , I am facing the same the [issue] I think.(https://github.com/tensorflow/tensorflow/issues/24076) I have tried replacing `-march=native` for `/arch:[AVX2|FMA|SSE4.2|FPMATH|MMX]` in the CMakeLists.txt file but still getting `Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED - Failed`. What do you suggest me to do? Thanks.
