### ISSUE TITLE
NameError: name 'core' is not defined

### ISSUE THREAD

**Issue by nb312** [tensorflow/tensorflow#8727]
when i run a command in the terminal
```
c:\python
>>> import tensorflow as tf 
```
it show the error 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\Tools\Python35\lib\site-packages\tensorflow\__init__.py", line 51, in <module>
    del core
NameError: name 'core' is not defined
```
i have a searching but don't find an answer, i would happy that someone gives me the answer

**Comment by caisq** [comment]
@nb312, can you please provide information on
1) what version of tensorflow you are using
2) where did you get the installation package
3) what your operating system (and version) is
4) is your platform 32-bit or 64-bit
5) whether you are using any python platforms such as anaconda.

**Comment by nb312** [comment]
1.the latest version of tensorflow1.0

**Comment by nb312** [comment]
1.the latest version of tensorflow1.0
2.use the command "pip3 install --upgrade tensorflow"
3. windows 7
4.64-bit
5.have no other platforms

**Comment by nb312** [comment]
the python version is 3.52
a

**Comment by nb312** [comment]
The Python version is 3.52.
 when I close the Terminal,then open it again the code run ok with no error.I don't  know what's wrong with this.

**Comment by gunan** [comment]
We have seen issues like this in windows before.
Usually, retrying install, or even rebooting can help.

Looks like the issue is resolved for you, so I will close.

**Comment by 17ankish** [comment]
I have face the same issue. Even i had reinstalled it. 
I am using the latest version with python=5.3
I have installed it using conda command.

Please help

**Comment by gunan** [comment]
There is no such python version.
Please try installing via pip. or see the other recommendations above.
