### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by impressprogram** [tensorflow/tensorflow#8738]
1. git clone https://github.com/tensorflow/tensorflow
2. cd tensorflow
3. ./configure

Since our server has no GPU, we configure cuda option with no but error occurs by cuda.

`ERROR: /home/kesl/kms_tensorflow/tensorflow/third_party/gpus/cuda_configure.bzl:828:18: unexpected keyword 'environ' in call to repository_rule(implementation: function, *, attrs: dict or NoneType = None, local: bool = False).
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'third_party/gpus/cuda_configure.bzl' has errors.
` 

But if I configure same thing with branch r1.0 version, it works.

**Comment by gunan** [comment]
Please update bazel to 0.4.5 and retry.

**Comment by impressprogram** [comment]
@gunan thank you!! It works now!
