### ISSUE TITLE
GPU device not found on OSX

### ISSUE THREAD

**Issue by maxgillett** [tensorflow/tensorflow#875]
Hello,

I'm trying to install TensorFlow with GPU support for a CUDA Capability 3.0 device. I have followed the instructions found here: https://gist.github.com/Mistobaan/dd32287eeb6859c6668d, and everything compiles without error, but TensorFlow doesn't recognize my GPU device. The steps that I'm taking are below, as is the error output.

I've modified bazel to use gcc-4.8, so these are the commands I'm running:

    bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer ---crosstool_top=//tools/cpp:toolchain
    bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --crosstool_top=//tools/cpp:toolchain

Running the example with:

    bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu

produces the following output:

    F tensorflow/cc/tutorials/example_trainer.cc:118] Check failed: ::tensorflow::Status::OK() == (session->Run({{"x", x}}, {"y:0", "y_normalized:0"}, {}, &outputs)) (OK vs. Invalid argument: Cannot assign a device to node 'Const/_2': Could not satisfy explicit device specification '/gpu:0'
         [[Node: Const/_2 = Const[dtype=DT_INT32, value=Tensor<type: int32 shape: [] values: 0>, _device="/gpu:0"]()]])
    F tensorflow/cc/tutorials/example_trainer.cc:118] Check failed: ::tensorflow::Status::OK() == (session->Run({{"x", x}}, {"y:0", "y_normalized:0"}, {}, &outputs)) (OK vs. Invalid argument: Cannot assign a device to node 'Const/_2': Could not satisfy explicit device specification '/gpu:0'
         [[Node: Const/_2 = Const[dtype=DT_INT32, value=Tensor<type: in

I can also confirm that after installing the pip package and running a test script, no devices are found.

A few things to note:
- Running deviceQuery confirms that a CUDA device (Device 0: GeForce GT 650M) is found. 
- I've made sure to run bazel clean before compiling, and have tried compiling using sudo just to see if this was a permissions issue.

Thanks in advance for your help.

**Comment by maxgillett** [comment]
It turns out that I was actually compiling with gcc-5, not gcc-4.8. From what I can tell CUDA doesn't support version 5, so this might be the problem. 

I'm trying now to compile with 4.8, but I'm getting this error:
    /var/tmp//cccfsYPu.s:2774:expecting string instruction after `rep'

**Comment by vrv** [comment]
De-duping with #491
