### ISSUE TITLE
ERROR,I tried to compile Tensorflow source code in 'compute_21' 

### ISSUE THREAD

**Issue by wtl** [tensorflow/tensorflow#8752]
I tried to compile Tensorflow source code in 'compute_21' 

### My computer environment info
    Ubuntu 16.04
    CUDA 8.0
    CUDNN 5.1
    GCC 4.9

The commit hash : a23f5d7f7757623a4ea8c6e1d743d178a0c561c5
 Build label: 0.4.5

### tried solutions 
https://github.com/tensorflow/tensorflow/issues/1498#issuecomment-196542169
Replace the loop on L253--256 with the following:
`nvccopts += r'-gencode=arch=compute_20,\"code=sm_21,compute_20\" '`

### Error Logs 
 external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorReductionCuda.h(519): error: no instance of function template "Eigen::internal::SumReducer<T>::reducePacket [with T=Eigen::half]"

10 errors detected in the compilation of "/tmp/tmpxft_00000f04_00000000-7_l2loss_op_gpu.cu.cpp1.ii".
ERROR: /home/bingco/tensorflow/tensorflow/core/kernels/BUILD:2611:1: output 'tensorflow/core/kernels/_objs/l2loss_op_gpu/tensorflow/core/kernels/l2loss_op_gpu.cu.pic.o' was not created.
ERROR: /home/bingco/tensorflow/tensorflow/core/kernels/BUILD:2611:1: not all outputs were created or valid.

**Comment by gunan** [comment]
Unfortunately, TF does not support GPUs that do not have CUDA Compute Capability older than 3.0:
https://www.tensorflow.org/install/install_linux

**Comment by wtl** [comment]
@gunan Whether can pass the modify the code to implement it？

**Comment by gunan** [comment]
TensorFlow team will not work on this, as we decided to limit our official support to 3.0 and later.
Older GPUs do not bring as much speed to justify the effort and added complexity required.
You can try yourself, or try to sync with other users through stackoverflow.
