### ISSUE TITLE
tf.contrib.seq2seq.sequence_loss documentation incorrect

### ISSUE THREAD

**Issue by falcondai** [tensorflow/tensorflow#8755]
The function returns a tensor with rank = 0, 1, 2 depending on its arguments. This is inconsistent with its docstring's description of the return:  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/seq2seq/python/ops/loss.py#L58

I will submit a PR soon to fix the doc.

NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

irrelevant

### Environment info
Operating System: 

irrelevant

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by aselle** [comment]
Thanks for the help. Please link the PR when you have submitted it.

**Comment by wolffg** [comment]
This looks fixed in master, and it will roll out over time.  Thank you!  I'm closing this; please reopen if I've missed something.
