### ISSUE TITLE
Error installing from source

### ISSUE THREAD

**Issue by jrbtaylor** [tensorflow/tensorflow#8756]
I'm trying to update tensorflow from the latest source. I'm running Ubuntu 14.04, with cuda 8.0 and cudnn 5.1.5. I was previously running r0.11 with no problem.

I pulled the new source. After running ./config and enabling cuda, I try to build with bazel:

> bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

and I'm getting the following error:

> ERROR: /home/jason/.cache/bazel/_bazel_jason/ba8a668adda8b53cb2de87e5e6b097b9/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
> 	File "/home/jason/.cache/bazel/_bazel_jason/ba8a668adda8b53cb2de87e5e6b097b9/external/local_config_cuda/crosstool/BUILD", line 4
> 		error_gpu_disabled()
> 	File "/home/jason/.cache/bazel/_bazel_jason/ba8a668adda8b53cb2de87e5e6b097b9/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
> 		fail("ERROR: Building with --config=c...")
> ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
> ERROR: no such target '@local_config_cuda//crosstool:toolchain': target 'toolchain' not declared in package 'crosstool' defined by /home/jason/.cache/bazel/_bazel_jason/ba8a668adda8b53cb2de87e5e6b097b9/external/local_config_cuda/crosstool/BUILD.

Note where it says "Please re-run ./configure and enter 'Y' at the prompt to build with GPU support." There is no such prompt when I run ./configure. I type 'Y' when it prompts if I want to build with cuda support and I give the correct cuda and cudnn versions and paths.

**Comment by gunan** [comment]
Please will in the full template. There are missing pieces of information, such as your bazel version, that prevents us from being able to help you.

**Comment by jrbtaylor** [comment]
I updated to the latest version of bazel before trying to update tensorflow

**Comment by gunan** [comment]
Our CI is healthy, and we can build OK with the current version of the code:
http://ci.tensorflow.org/job/tensorflow-master-linux-gpu/

So unless you provide more detailed information to us, we really cant offer much help.

**Comment by jrbtaylor** [comment]
I gave the error and versions for all relevant packages (that I know of). Again, when I run ./configure, I'm not seeing any prompts to build with GPU support as the error suggests. I'm saying yes to building with cuda.

**Comment by gunan** [comment]
Sorry if I was not clear.
To make sure we have all we need when debugging user side issues, we tried to refine the issue template.
By filling that out, you will help us understand your setup, and the problem you are seeing.

I think you are running into this same problem here:
https://github.com/tensorflow/tensorflow/issues/8731

There seems to be already a response there which may help get around the issue you are seeing.

**Comment by jrbtaylor** [comment]
I had also tried bazel clean. It made no difference.

I uninstalled and just reinstalled from pip.

**Comment by archenroot** [comment]
Just note, I had similar problem, by setting following variables during configuration phase:
```
export CUDNN_INSTALL_PATH="/usr/lib64"
	export TF_NEED_CUDA="1"
	export TF_CUDA_VERSION="9.0"
	export TF_CUDNN_VERSION="7"
```

And all is good.
