### ISSUE TITLE
`tf.device()` issue

### ISSUE THREAD

**Issue by RuofanKong** [tensorflow/tensorflow#8762]
I posted my issue about In-graph replication for Distributed Tensorflow on StackOverflow: http://stackoverflow.com/questions/43036201/in-graph-replication-for-distributed-tensorflow. I wonder if there is a bug in terms of `tf.device()`, as I expect each process has its own log instead of print out message that belongs to other block of `tf.device()` like my example there. Thanks!

**Comment by yaroslavvb** [comment]
I don't believe this is a bug, but rather a misunderstanding of how distributed TensorFlow works, someone in SO posted links to some docs

**Comment by RuofanKong** [comment]
@yaroslavvb Thanks for your response! I read the link there, but it still seems ambiguous about my issue, probably I missed something there. If possible, could you help to take a look? Also, I read distributed tensorflow multiple times, is there any other docs to recommend?

**Comment by yaroslavvb** [comment]
Bulk of the documentation exists as comments in source code. I've posted some explanations in these SO answers:

http://stackoverflow.com/questions/40819321/understanding-the-conceptual-basics-of-distributed-tensorflow/40873770#40873770

http://stackoverflow.com/questions/41067398/task-assignment-in-tensorflow-distributed-process/41069059#41069059
