### ISSUE TITLE
configure hangs on download and aborts

### ISSUE THREAD

**Issue by GaelReinaudi** [tensorflow/tensorflow#8764]
Hi,
I am trying to compile tensorflow from source.
when I run ./configure, things start to be downloaded, but generaly, it will hang for ~10s at a large download (>~30MB), and aborts with such error:
`ERROR: /home/user/f/dependRepos/serving/tensorflow/tensorflow/compiler/xla/service/cpu/BUILD:449:1: no such package '@llvm//': java.io.IOException: Error downloading [http://bazel-mirror.storage.googleapis.com/github.com/llvm-mirror/llvm/archive/94403df1ddb4cf9af6ac7dcbbd629fcc22e19db9.tar.gz, https://github.com/llvm-mirror/llvm/archive/94403df1ddb4cf9af6ac7dcbbd629fcc22e19db9.tar.gz] to /home/user/.cache/bazel/_bazel_user/8f93dc993f1ee3fe648b32055340eadb/external/llvm/94403df1ddb4cf9af6ac7dcbbd629fcc22e19db9.tar.gz: Tried to reconnect at offset 31,979,427 but server didn't support it and referenced by '//tensorflow/compiler/xla/service/cpu:elemental_ir_emitter'.
ERROR: /home/user/f/dependRepos/serving/tensorflow/tensorflow/compiler/xla/service/cpu/BUILD:176:1: no such package '@llvm//': java.io.IOException: Error downloading [http://bazel-mirror.storage.googleapis.com/github.com/llvm-mirror/llvm/archive/94403df1ddb4cf9af6ac7dcbbd629fcc22e19db9.tar.gz, https://github.com/llvm-mirror/llvm/archive/94403df1ddb4cf9af6ac7dcbbd629fcc22e19db9.tar.gz] to /home/user/.cache/bazel/_bazel_user/8f93dc993f1ee3fe648b32055340eadb/external/llvm/94403df1ddb4cf9af6ac7dcbbd629fcc22e19db9.tar.gz: Tried to reconnect at offset 31,979,427 but server didn't support it and referenced by '//tensorflow/compiler/xla/service/cpu:ir_emitter'.
ERROR: /home/user/f/dependRepos/serving/tensorflow/tensorflow/compiler/xla/service/cpu/BUILD:32:1: no such package '@llvm//': java.io.IOException: Error downloading [http://bazel-mirror.storage.googleapis.com/github.com/llvm-mirror/llvm/archive/94403df1ddb4cf9af6ac7dcbbd629fcc22e19db9.tar.gz, https://github.com/llvm-mirror/llvm/archive/94403df1ddb4cf9af6ac7dcbbd629fcc22e19db9.tar.gz] to /home/user/.cache/bazel/_bazel_user/8f93dc993f1ee3fe648b32055340eadb/external/llvm/94403df1ddb4cf9af6ac7dcbbd629fcc22e19db9.tar.gz: Tried to reconnect at offset 31,979,427 but server didn't support it and referenced by '//tensorflow/compiler/xla/service/cpu:cpu_compiler'.
ERROR: /home/user/f/dependRepos/serving/tensorflow/tensorflow/python/BUILD:2571:1: every rule of type _py_wrap_cc implicitly depends upon the target '@swig//:swig', but this target could not be found because of: no such package '@swig//': Error downloading [http://bazel-mirror.storage.googleapis.com/ufpr.dl.sourceforge.net/project/swig/swig/swig-3.0.8/swig-3.0.8.tar.gz, http://ufpr.dl.sourceforge.net/project/swig/swig/swig-3.0.8/swig-3.0.8.tar.gz, http://pilotfiber.dl.sourceforge.net/project/swig/swig/swig-3.0.8/swig-3.0.8.tar.gz] to /home/user/.cache/bazel/_bazel_user/8f93dc993f1ee3fe648b32055340eadb/external/swig/swig-3.0.8.tar.gz: Tried to reconnect at offset 7,935,828 but server didn't support it.
ERROR: /home/user/f/dependRepos/serving/tensorflow/tensorflow/python/BUILD:2571:1: every rule of type _py_wrap_cc implicitly depends upon the target '@swig//:templates', but this target could not be found because of: no such package '@swig//': Error downloading [http://bazel-mirror.storage.googleapis.com/ufpr.dl.sourceforge.net/project/swig/swig/swig-3.0.8/swig-3.0.8.tar.gz, http://ufpr.dl.sourceforge.net/project/swig/swig/swig-3.0.8/swig-3.0.8.tar.gz, http://pilotfiber.dl.sourceforge.net/project/swig/swig/swig-3.0.8/swig-3.0.8.tar.gz] to /home/user/.cache/bazel/_bazel_user/8f93dc993f1ee3fe648b32055340eadb/external/swig/swig-3.0.8.tar.gz: Tried to reconnect at offset 7,935,828 but server didn't support it.
ERROR: Evaluation of query "deps(((//tensorflow/... - //tensorflow/contrib/nccl/...) - //tensorflow/examples/android/...))" failed: errors were encountered while computing transitive closure.
`

I once managed to download manually the incriminated files from a browser, and then decompress them manually in the temporary folder where bazel can find it, but it is rather cumbersome to do so.

### Environment info
Operating System: Ubuntu 16.04
Installed version of CUDA and cuDNN: cuda8.0.44, cudnn5.1.5 (but this happens even when I ./configure without gpu support)

The commit hash (12a98726e769e988f6368a029ec2f5b0ac3ccbd4), but it has been doing this for as long as I have tried to compile from source (v < 0.10).

bazel version:
`Build label: 0.4.5`
`Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar`
`Build time: Thu Mar 16 12:19:38 2017 (1489666778)`
`Build timestamp: 1489666778`
`Build timestamp as int: 1489666778`

**Comment by gunan** [comment]
I have sent #8761 to remove downloads from `configure` script. However, this means downloads will happen automatically during bazel build. Unfortunately, we have to have the dependencies downloaded to build the code, the PR just changes when they are downloaded.

Looking at your logs, I see that there is:
`Tried to reconnect at offset 7,935,828 but server didn't support it.`
So maybe we should remove the sourceforge for swig, and get a more agreeable mirror for swig.

**Comment by GaelReinaudi** [comment]
So if I understand correctly, I can ignore this during ./configure and bazel will download the needed packages anyway...
Thx

**Comment by gunan** [comment]
You are correct. With bazel 0.4.5, we do not need to run bazel fetch separately anymore.
#8761 is just merged, and it should also help clarify such confusions going forward.
