### ISSUE TITLE
word2vec.py error

### ISSUE THREAD

**Issue by Channndiii** [tensorflow/tensorflow#877]
I download the tensorflow-master version.

When I execute the word2vec.py on pycharm, it shows the error:

from tensorflow.models.embedding import gen_word2vec as word2vec
ImportError: No module named embedding

In __init__.py, I see "Import generated word2vec optimized ops into embedding package."

Does it means it needs a file about "generated word2vec optimized ops"? But I can' t find it. How can I fix it?

The environment is Mac OS X, and I install tensorflow in this way: $ pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl.

**Comment by vrv** [comment]
You should try upgrading to 0.6.0 -- I think that file was broken in our initial release except when via bazel.

**Comment by Channndiii** [comment]
@vrv Thank you!

Your tip works. 

I upgrade to 0.6.0 by $ pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.6.0-py2-none-any.whl.

I am a fresher in tensorflow. May I ask you one more question?

I still execute the word2vec.py on pycharm. This time it is running, and it does not show error, but the output stop after it shows "Skipped:  1299". I think it may stuck somewhere. How can I fix it?

Console Information:
I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 4
I tensorflow/core/common_runtime/direct_session.cc:58] Direct session inter op parallelism threads: 4
I tensorflow/models/embedding/word2vec_kernels.cc:149] Data file: text8 contains 100000000 bytes, 17005207 words, 253854 unique words, 100038 unique frequent words.
Data file:  text8
Vocab size:  100038  + UNK
Words per epoch:  17005207
Eval analogy file:  questions-words.txt
Questions:  18245
Skipped:  1299

**Comment by martinwicke** [comment]
You'll probably get a better answer for these types of questions on StackOverflow.

**Comment by hkkatti** [comment]
word2vec.py goes through without any error on IPython . Then How to run or test the model Ex: giving France, Paris...Russia..to . It does not prompt for inputs..

katti
