### ISSUE TITLE
scope issue of '_linear' method in 'tensorflow.python.ops.rnn_cell_impl' module

### ISSUE THREAD

**Issue by Gitsamshi** [tensorflow/tensorflow#8777]
In 'core_rnn_cell_impl' module _linear method, the arg 'scope' is not used in the method, easily causing variable conflicts. eg:
with tf.variable_scope(scope):
        zw = core_rnn_cell_impl._linear(self.hyper_output, self.hyper_embedding_size, False, scope=scope + "z")        
        alpha = core_rnn_cell_impl._linear(zw, dimensions, False, scope=scope + "alpha")
zw, alpha(forgive me for the indent in format) although defined in their specific scope, they will collide each other for using the same variable name.

I look up the 'core_rnn_cell_impl' code and I find the 'scope' arg has not been truly used.
This is the 1.0.0 version:
scope = vs.get_variable_scope()
with vs.variable_scope(scope) as outer_scope:

This is the 0.12.0 version:
with vs.variable_scope(scope or "Linear"):

Please check if it's truly the problem, thanks a lot !

**Comment by aselle** [comment]
@ebrevdo, could you comment please.

**Comment by ebrevdo** [comment]
yes... it's an internal method and isn't meant for external use.  i think
we got rid of the scope= argument in master branch.

**Comment by Gitsamshi** [comment]
Thanks
