### ISSUE TITLE
Contrintuitive get_variable dtype checks

### ISSUE THREAD

**Issue by Bihaqo** [tensorflow/tensorflow#8779]
When reusing variables get_variable checks if dtypes are consistent, but it seems to compare the wrong dtypes.

Example:
```
a = tf.get_variable('a', initializer=tf.zeros(2, tf.int32))
with tf.variable_scope('', reuse=True):
  tf.get_variable('a', initializer=tf.zeros(2, tf.int32)) # raises ValueError
  tf.get_variable('a', initializer=tf.zeros(2, tf.int16)) # raises ValueError

b = tf.get_variable('b', initializer=tf.zeros(2))
with tf.variable_scope('', reuse=True):
  tf.get_variable('b', initializer=tf.zeros(2, tf.int32)) # works
```
Here the TF will compare dtype of existing variable `a` (tf.int32) against the dtype of the next get_variable call, which is tf.float32 (which is the default value for dtype argument of get_variable).

The resulting situations where get_variable raises ValueError seems counterintuitive.

**Comment by lukaszkaiser** [comment]
Hmm, it looks like maybe we should simply allow to reuse without specifying dtype? Or is there something else you'd suggest? Looks like we should loosen some checks, but I'm not exactly sure yet which - do you have a suggestion?

**Comment by Bihaqo** [comment]
I think these checks are useful against copypast errors.

One of the ways to go is to change default value of the argument `dtype` from `tf.float32` to `None`. If `dtype` is `None` and `initializer` is provided, check the `dtype` of the existing variable against the `initializer` (not the `dtype` argument).

In this case the situation should be as follows:
```
tf.get_variable('a', initializer=tf.zeros(2, tf.int32))
with tf.variable_scope('', reuse=True):
  tf.get_variable('a', initializer=tf.zeros(2, tf.int32)) # works
  tf.get_variable('a', dtype=tf.int32) # works
  tf.get_variable('a') # works, because nor dtype nor initializer are provided, nothing to compare against.
  tf.get_variable('a', initializer=tf.zeros(2, tf.int16)) # raises ValueError
  tf.get_variable('a', dtype=tf.float32) # raises ValueError

tf.get_variable('b', dtype=tf.int16, initializer=tf.zeros(2, tf.int32)) # raises ValueError
```

And we can apply the same principle to shape checks as well.

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
