### ISSUE TITLE
Problem with processing/displaying RGB images

### ISSUE THREAD

**Issue by Panaetius** [tensorflow/tensorflow#8786]
I just switched to a build of the r1.1 branch of tensorflow (due to a fixed bug in tfdbg present in 1.0) and without any changes to my model, RGB images saved with tf.summary.image are showing up weird in tensorboard, whereas they showed up fine in all previous versions of tensorflow/tensorboard.

Here's an example of what I mean: http://i.imgur.com/xFoEYzO.png

Those should be regular MSCOCO color images, but now the colors are all over the place.

Before being displayed, the images are adjusted as follows:

        distorted_image = tf.cast(result.image_raw, tf.float32)
        distorted_image = tf.reshape(distorted_image,
                                     [self.width, self.height, 3])
        distorted_image = tf.image.random_brightness(distorted_image,
                                                     max_delta=35)
        distorted_image = tf.image.random_contrast(distorted_image,
                                                   lower=0.4, upper=1.4)
        distorted_image = tf.image.random_hue(distorted_image, max_delta=0.01)
        float_image = tf.image.per_image_standardization(distorted_image)

and then the bounding boxes are drawn with: `tf.image.draw_bounding_boxes`

the images are logged using `tf.summary.image('images', preview_images, max_outputs=16)`

I don't know if the issue is exclusive to tensorboard (conv layer activations seem to be displayed just fine, though the first layer conv activations look like they are working on the 'broken' image data as well, so it looks like it's not a tensorboard bug).

The images are read from a TFRecord file (which wasn't changed) and supplied with a shuffle_batch

Have any of the image summary/image adjustment ops changed in a way that I'm not aware of, or is this a bug? It looks like it could have something to do with normalization of the image.

**Comment by Panaetius** [comment]
Looking at recent committed changes to image ops and after some testing, it is due to the change in 60e7360dfcf8951c4a269cfddd2a9cf2a05d7f91 with clipping float images to [0,1)

From the commit message, it seems like this was an intended change, though it seems a bit weird to me that float images are clipped to 0,1 by this op to be be consistent with uint8 images, since floats can have a much larger range than uint8. And the documentation of the operation should be updated to reflect that it expects images in the 0,1 range. I'm wondering if this clipping actually makes sense, since usually, standardization/normalization is made as the last step of preprocessing, but if one has a float image with numbers 0.0-255.0, one might need to standardize twice now (before and after image adjustments), since the image adjustment ops could alter the statistics of the image, and I'm not entirely sure how normalizing twice could change the data.

If this change is working as intended and here to stay, then the [Cifar 10 tutorial example](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_input.py) should be changed, since it also exhibits this problem (and is what I based my code on).

**Comment by aselle** [comment]
@shlens, what do you think here. This seems like a backward incompatible change (even if the different data types were consistent), on the other hand the adjust_brightness function is a pretty strange definition of brightness, because it seems to reduce the contrast at the same time as changing the brightness. I would have implemented it as using hsl or multiplying by a constant. Do we have any notion of high dynamic rnage image that we want to support?

**Comment by martinwicke** [comment]
We should roll this back. The change in 60e7360 was backwards incompatible and shouldn't have gotten in. I'll send a PR. @gunan @av8ramit FYI, this should go into RC1 if we still have the option.

It's unsurprising that functions behave differently when operating on different data types, so I don't agree with the reasoning behind the change. The difference comes from the range of uint8 being limited, and it's unreasonable to force float32 to be limited to [0,1) as well. If you want to, the clip_by_value call can be made explicitly.

**Comment by girving** [comment]
@martinwicke Did that rollback happen?

**Comment by martinwicke** [comment]
I believe so.
