### ISSUE TITLE
python StagingArea documentation missing

### ISSUE THREAD

**Issue by sjperkins** [tensorflow/tensorflow#8793]
StagingArea (and perhaps other structures in [data_flow_ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/data_flow_ops.py)) are not present in the python documentation. They are however mentioned in the 1.0.0 and 1.1.0 [release notes](https://github.com/tensorflow/tensorflow/blob/346bd59b3c99055c3fdcbc0d0b0710418f48c5c6/RELEASE.md)

### What other attempted solutions have you tried?

A search of the docs for ["StagingArea"](https://www.tensorflow.org/s/results/?q=StagingArea) doesn't reveal any of the docstrings present in [data_flow_ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/data_flow_ops.py).

[Stage](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/stage) and Unstage are present in the C++ documentation.

**Comment by cwhipkey** [comment]
StagingArea was added under tf.contrib.staging.StagingArea with this commit 8 days ago:   https://github.com/tensorflow/tensorflow/commit/90733a8024532f6993d11f0a89deaecb2bba59fe

This will allow the documentation to be generated for it.  The new docs should go up this coming weekend.
