### ISSUE TITLE
[CPU Performance Issue] Why don't hugepages, prefetch.

### ISSUE THREAD

**Issue by tu-cao** [tensorflow/tensorflow#8795]
Hugepages and Prefetch are considered as two main techniques for performance improvement.

https://wiki.debian.org/Hugepages
Intel® 64 and IA-32 Architectures Optimization Reference Manual (http://www.intel.com/content/www/us/en/architecture-and-technology/64-ia-32-architectures-optimization-manual.html)

Just don't understand why TF does not use hugepages and prefetch techniques for CPU version.

Thanks for great TF.

**Comment by aselle** [comment]
Every processor feature takes time to use and implement, and as far as I know nobody has had time to implement it. Putting these in every individual kernel is time consuming. We're hoping that using the XLA compiler framework would be a great place to put these optimizations. On the other hand, we'd definitely welcome any help on these types of optimizations as community contributions!

**Comment by aselle** [comment]
@pbar, @benoitsteiner, did either of you experiment with prefetching/hugepages.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
