### ISSUE TITLE
Currently trying to run tensorflow android code downloaded from Github facing following error as Error:Execution failed for task ':buildNativeMake'. A problem occurred starting process 'command 'tensorflow/contrib/makefile/build_all_android.sh'' Please reply asap

### ISSUE THREAD

**Issue by patilsamruddhi** [tensorflow/tensorflow#8797]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by Carmezim** [comment]
Hi @patilsamruddhi, thank you for filling the issue as I oriented on email. Could you please specify the code you tried to run, your OS and other information you find can be useful and relevant? Thanks

cc @andrewharp

**Comment by andrewharp** [comment]
@patilsamruddhi Are you trying to build on Windows? If so, see https://github.com/tensorflow/tensorflow/issues/6385#issuecomment-285208600 for instructions on using Bash for Windows to build Android TensorFlow.

**Comment by aselle** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by patilsamruddhi** [comment]
Dear Andrew Selle,

Following are Version we use to build the project.

OS Details: 64 bit operating system
Windows: 7 Professional
Android Studio: 2.3
tensorflow: 1.0
Python: 3.5.2
bazel : 0.3.0
jdk: 8(windows)
Visual studio: VS-2015
NDK: android-ndk-r14b

**Comment by aselle** [comment]
@petewarden, it appears that this build method is not compatible with windows because it is trying to run a shell script. Is this expected?

**Comment by andrewharp** [comment]
That's correct. There is a workaround for building Android TF on Windows here: https://github.com/tensorflow/tensorflow/issues/6385#issuecomment-285208600

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Comment by azainab** [comment]
I am facing the error below. I tried running TF detect and it worked perfectly fine but I am not sure which change effected the project I am getting this error:

Error:Execution failed for task ':TensorFlow-Android-Inference:buildTensorflow'.
> Process 'command 'tensorflow/contrib/makefile/build_all_android.sh'' finished with non-zero exit value 127
