### ISSUE TITLE
[Tensorflow]RuntimeError: Graph is finalized and cannot be modified.

### ISSUE THREAD

**Issue by pengjingg** [tensorflow/tensorflow#8801]
### Environment info
Operating System:
Ubuntu 14.04  
cuda 8.0 + cudnn 5.1

I'm running a Cifar-10 tutorial from [https://www.tensorflow.org/tutorials/deep_cnn]
And I modified the code a lot.
Specifically, I want the model can evaluate simultaneously while training, thus I can get a curve of precision. And I don't have ideal how the cifar10_eval.py and checkpoints work out. So I added an evaluation function to train( ) in cifar10_train.py, and I tried to run the evaluation function every 100 global_step. And then I got this:

        RuntimeError: Graph is finalized and cannot be modified.

Here is my evaluation function in cifar10.py:

      def evaluation():
        images_e, labels_e = inputs(eval_data=True)
        logits_e = inference(images_e)
        correct_pred = tf.equal(tf.argmax(logits_e, 1), tf.argmax(labels_e, 1))
        accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))
        print('%s: accuracy @ 1 = %.3f' % (datetime.now(), accuracy))
        tf.summary.scalar('accuracy', accuracy)

And here is the call (the last few lines) :

       def after_run(self, run_context, run_values):
        if self._step % FLAGS.log_frequency == 0:
          current_time = time.time()
          duration = current_time - self._start_time
          self._start_time = current_time

          loss_value = run_values.results
          examples_per_sec = FLAGS.log_frequency * FLAGS.batch_size / duration
          sec_per_batch = float(duration / FLAGS.log_frequency)

          format_str = ('%s: step %d, loss = %.2f (%.1f examples/sec; %.3f '
                        'sec/batch)')
          print (format_str % (datetime.now(), self._step, loss_value,
                               examples_per_sec, sec_per_batch))
        if self._step % EVAL_STEP == 0: 
          print('evaluation\n')
          cifar10.evaluation()

I don't know how to solve it. I do searched the Internet before but there is no similar situation. Is this caused by I called inference() twice in one global_step or else? Any suggestions would be helpful. Thank you!

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
