### ISSUE TITLE
Wheels on PyPI violate manylinux1 specification / PEP513

### ISSUE THREAD

**Issue by bluenote10** [tensorflow/tensorflow#8802]
Follow-up issue to #5033.

As already pointed out by @jjhelmus, the Linux wheels on PyPI do not conform to the manylinux1 specification provided in [PEP513](https://www.python.org/dev/peps/pep-0513/). To quote @jjhelmus's comment from #5033:

> Specifically, they contain shared libraries which reference versioned symbols which do not meet the GLIBC <= 2.5 and GLIBCXX <= 3.4.9 requirements specified in the PEP.

It would be great if the wheels could be fixed to match the specification.

**Comment by gunan** [comment]
@yifeif From what I understand on the issue, it was decided to just leave a note on the website?
Maybe we should just remove manylinux1 wheel files, as they are leading to confusion.
As we only officially support ubuntu officially, is there a way to mark the wheel files as such, instead of the broader manylinux label?

**Comment by bluenote10** [comment]
I don't understand the motivation to label the wheel "manylinux" combined with a note that it actually isn't a manylinux wheel. If it does not follow the specification, it's just a regular wheel and calling it manylinux is confusing.

To maximise compatibility, it would obviously be much preferred to follow the PEP and build the wheels against the official manylinux docker images (unless there is a true incompatibility).

**Comment by yifeif** [comment]
@bluenote10 thanks for raising the concern. We are not building against the official manylinux docker for many reasons such as we need nvidia docker to build GPU binaries, we don't have support for centOS etc. And manylinux1 is the only linux ABI Pypi supports now. We'd like to provide the convenience of downloading linux wheel through pip install for now until better solution comes up.

**Comment by pitrou** [comment]
Just chiming in here. It's counter-productive to claim your wheels are manylinux1-compliant when they aren't. This is producing annoyances for other projects in the ecosystem who have to deal with bug reports such as "pyarrow crashes when I try to use it alongside tensorflow".

**Comment by westurner** [comment]
"PEP 571 -- The manylinux2010 Platform Tag"
https://www.python.org/dev/peps/pep-0571/

"Tracking issue for manylinux2010 rollout"
https://github.com/pypa/manylinux/issues/179

"[Distutils] Opinions on requiring younger glibc in manylinux1 wheel?"
https://mail.python.org/mm3/archives/list/distutils-sig@python.org/message/M4MSVY5MPAPXFWHH4PBLE6PEBPOBIA44/

**Comment by nvda-chargr** [comment]
The problem I have with is if I build and publish my own wheel internally, and use an extra-index-url to my pypi repo, the public pypi 'manylinux1' will be selected by pip over a 'linux' wheel.  If the published wheels were truly manylinux1, I wouldnt need to build my own.
