### ISSUE TITLE
how to read more than one tfrecord files once?

### ISSUE THREAD

**Issue by sunshinee24** [tensorflow/tensorflow#8803]
I want to do validation during training, but how to read two tfrecord files once, one is for training and annother one is for validation

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by baodingge** [comment]
that is easy, using tf.train.string_input_producer(filename_list)
look at tensorflow official document about read data
