### ISSUE TITLE
error running tensorflow trained model c++

### ISSUE THREAD

**Issue by SebastienMousnier** [tensorflow/tensorflow#8807]
Hello,

I am working on Tensorflow on c++ with other network. I trained facenet on MS-Celeb-1M then i created my graph.pb. I modified the example provided here : https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/label_image in order to test my network.
In main.cpp:    
    `string graph = "data/graph1.pb";`
    `string output_layer = "InceptionResnetV1/Repeat/block35_5/Relu";`

I get this error if I test : 
    

> Running model failed: Invalid argument: You must feed a value for placeholder tensor 'phase_train'     with dtype bool [[Node: phase_train = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0    /cpu:0"]()]]

**Comment by aselle** [comment]
Are you feeding this value "phase_train" like it asks you to?
