### ISSUE TITLE
Git branch 0.6.0 not showing

### ISSUE THREAD

**Issue by manucarbonell** [tensorflow/tensorflow#881]
Hi,
I've cloned the tensorflow repository (git clone https://github.com/tensorflow/tensorflow.git)
and when I do 
git branch -a 
it only appears master branch (* master) instead of 
*master
0.6.0 
as i though it should appear 
Can someone please help me?
Thanks

**Comment by vrv** [comment]
```
$ git branch -a -v
* master                a27d844 Merge commit for internal changes
  remotes/origin/0.6.0  8242b4d TensorFlow: some more python3 compatibility test fixes
  remotes/origin/HEAD   -> origin/master
  remotes/origin/master a27d844 Merge commit for internal changes```

```git checkout 0.6.0 -b 0.6.0

$ git log -n 1
commit 8242b4dd1b36440e191fef8a07b6f37d8bcee60d
Author: Vijay Vasudevan <vrv@google.com>
Date:   Wed Dec 9 17:00:29 2015 -0800

    TensorFlow: some more python3 compatibility test fixes
    
    Change-Id: I5678cbdfb45757e2218494f542c9b0a0d5cc16a4
```

Seems to works for me...

**Comment by manucarbonell** [comment]
Thanks a lot, was doing only "-a"

**Comment by manucarbonell** [comment]
Again, only master branch showing:  
git init
Initialized empty Git repository in /home/users/mcarbonell/tensorflow/.git/
mcarbonell@asterix:~/tensorflow$ git pull https://github.com/tensorflow/tensorflow.git
remote: Counting objects: 18687, done.
remote: Total 18687 (delta 0), reused 0 (delta 0), pack-reused 18687
Receiving objects: 100% (18687/18687), 24.33 MiB | 1.34 MiB/s, done.
Resolving deltas: 100% (13252/13252), done.
From https://github.com/tensorflow/tensorflow
 * branch            HEAD       -> FETCH_HEAD
Checking out files: 100% (1853/1853), done.
mcarbonell@asterix:~/tensorflow$ git branch -a -v
* master 3e89c75 Merge pull request #1087 from tensorflow/fix-android-build.

can someone tell me why please?

**Comment by vrv** [comment]
```
$ git clone https://github.com/tensorflow/tensorflow.git  --recurse-submodules 
$ cd tensorflow
$ git branch -r
  origin/0.6.0
  origin/HEAD -> origin/master
  origin/master
  origin/r0.7
  origin/release-notes
$ git branch 0.6.0
$ git checkout 0.6.0
```

**Comment by manucarbonell** [comment]
Thanks
