### ISSUE TITLE
tensorflow-1.0.1-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by dbl001** [tensorflow/tensorflow#8815]
I built tensorflow from source on Ubuntu 14.04 LTS.

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

ubuntu@ip-10-0-1-152:~/tensorflow$ ls -l /usr/local/cuda
lrwxrwxrwx 1 root root 19 Mar 27 16:02 /usr/local/cuda -> /usr/local/cuda-7.0

If installed from binary pip package, provide:

ubuntu@ip-10-0-1-152:~/tensorflow$ ls -l /home/ubuntu/cuda
total 8
drwxrwxr-x 2 ubuntu ubuntu 4096 Mar 21 20:34 include
drwxrwxr-x 2 ubuntu ubuntu 4096 Mar 21 20:34 lib64

1. The commit hash (`git rev-parse HEAD`)
ubuntu@ip-10-0-1-152:~/tensorflow$ git rev-parse HEAD
baa85cbf5e51a21f58bc28ef9eedc122e6118eb8
2. The output of `bazel version`
ubuntu@ip-10-0-1-152:~/tensorflow$ bazel version
...........................................................................................................
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:19:38 2017 (1489666778)
Build timestamp: 1489666778
Build timestamp as int: 1489666778

Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 3522.680s, Critical Path: 2077.85s
ubuntu@ip-10-0-1-19:~/tensorflow$ 
ubuntu@ip-10-0-1-19:~/tensorflow$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg 
Wed Mar 29 17:58:57 UTC 2017 : === Using tmpdir: /tmp/tmp.fQQIv2RgvY
~/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles ~/tensorflow
~/tensorflow
/tmp/tmp.fQQIv2RgvY ~/tensorflow
Wed Mar 29 17:58:58 UTC 2017 : === Building wheel
warning: no files found matching '*.dll' under directory '*'
warning: no files found matching '*.lib' under directory '*'
~/tensorflow
Wed Mar 29 17:59:29 UTC 2017 : === Output wheel file is in: /tmp/tensorflow_pkg

ubuntu@ip-10-0-1-19:~/tensorflow$ sudo -H pip install --upgrade /tmp/tensorflow_pkg/tensorflow-1.0.1-cp27-cp27mu-linux_x86_64.whl 
tensorflow-1.0.1-cp27-cp27mu-linux_x86_64.whl is not a supported wheel on this platform.

Is this a clue?

sudo -H pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/protobuf-3.0.0b2.post2-cp27-none-linux_x86_64.whl 
protobuf-3.0.0b2.post2-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.

**Comment by dbl001** [comment]
ubuntu@ip-10-0-1-152:~$ python --version
Python 2.7.11 :: Anaconda custom (64-bit)
ubuntu@ip-10-0-1-152:~$ conda --version
conda 4.3.14

**Comment by dbl001** [comment]
```
ubuntu@ip-10-0-1-152:~$ pip --version
pip 9.0.1 from /home/ubuntu/anaconda/lib/python2.7/site-packages (python 2.7)
```

**Comment by dbl001** [comment]
```
ubuntu@ip-10-0-1-152:~$ python --version
Python 2.7.11 :: Anaconda custom (64-bit)
ubuntu@ip-10-0-1-152:~$ conda --version
conda 4.3.14
ubuntu@ip-10-0-1-152:~$ pip --version
pip 9.0.1 from /home/ubuntu/anaconda/lib/python2.7/site-packages (python 2.7)
```

**Comment by mrry** [comment]
Can you report the output of `sudo pip --version` as well? I suspect it might be different from the `pip` in your user account's `$PATH`.

**Comment by dbl001** [comment]
ubuntu@ip-10-0-1-152:~/tensorflow$ sudo pip --version 
pip 9.0.1 from /usr/local/lib/python3.4/dist-packages/pip-9.0.1-py3.4.egg (python 3.4)

Ummm.  python 3.4.  Bad!

**Comment by mrry** [comment]
Thanks for confirming my suspicion! I'd advise following the [virtualenv installation instructions](https://www.tensorflow.org/install/install_linux#installing_with_virtualenv) if you can, since they don't require you to use `sudo`.

**Comment by dbl001** [comment]
I’m able to use TensorFlow, however, ‘nvidia-smi’ reports that the GPU is not being used.
E.g. - No running processes found   

ubuntu@ip-10-0-1-48:~$ nvidia-smi
Thu Mar 30 05:45:26 2017       
+------------------------------------------------------+                       
| NVIDIA-SMI 346.46     Driver Version: 346.46         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GRID K520           Off  | 0000:00:03.0     Off |                  N/A |
| N/A   35C    P0    38W / 125W |     10MiB /  4095MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
ubuntu@ip-10-0-1-48:~$ 

1. Does TensorFlow w/GPU run on Ubuntu 14.04 LTS?  Amazon support seemed to think it only runs on 16.04.
2. This could be a similar issue:

https://github.com/tensorflow/tensorflow/issues/8734

**Comment by dbl001** [comment]
btw - ./configure never asked me if I wanted to use the GPU.  It only asked about openCL and CUDA:

ubuntu@ip-10-0-1-48:~/tensorflow$ ./configure
Please specify the location of python. [Default is /home/ubuntu/anaconda/bin/python]: 
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? [Y/n] y
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] n
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] y
Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] y
XLA JIT support will be enabled for TensorFlow
Found possible Python library paths:
  /home/ubuntu/anaconda/lib/python2.7/site-packages
Please input the desired Python library path to use.  Default is [/home/ubuntu/anaconda/lib/python2.7/site-packages]

Using python library path: /home/ubuntu/anaconda/lib/python2.7/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] n
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 
Please specify the location where CUDA  toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /home/ubuntu/cuda
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
...........
INFO: All external dependencies fetched successfully.
Configuration finished

I was under the impression that I would see this output (https://alliseesolutions.wordpress.com/2016/09/08/install-gpu-tensorflow-from-sources-w-ubuntu-16-04-and-cuda-8-0-rc/):

Setting up Cuda include
Setting up Cuda lib
Setting up Cuda bin
Setting up Cuda nvvm
Setting up CUPTI include
Setting up CUPTI lib64
Configuration finished

**Comment by adityaatluri** [comment]
Hi,
I am facing similar issue my pip is 2.7 
```
$ sudo pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
```

**Comment by adityaatluri** [comment]
Got it fixed when
I downloaded get-pip.py from https://bootstrap.pypa.io/get-pip.py
and then ran `python2.7 get-pip.py` for installing pip2.7
