### ISSUE TITLE
Bug when using `tf.contrib.metrics.streaming_mean_iou`

### ISSUE THREAD

**Issue by mgarbade** [tensorflow/tensorflow#8818]
### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
```
ls -l /usr/local/cuda-8.0/lib/libcud*
-rw-r--r-- 1 root root   560184 Sep  5  2016 /usr/local/cuda-8.0/lib/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Sep  5  2016 /usr/local/cuda-8.0/lib/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Sep  5  2016 /usr/local/cuda-8.0/lib/libcudart.so.8.0 -> libcudart.so.8.0.27
-rwxr-xr-x 1 root root   394472 Sep  5  2016 /usr/local/cuda-8.0/lib/libcudart.so.8.0.27
-rw-r--r-- 1 root root   737516 Sep  5  2016 /usr/local/cuda-8.0/lib/libcudart_static.a
lrwxrwxrwx 1 root root       13 Jan 17 13:52 /usr/local/cuda-8.0/lib/libcudnn.so -> libcudnn.so.5
-rwxr-xr-x 1 root root 61453024 Nov 13 12:10 /usr/local/cuda-8.0/lib/libcudnn.so.4
-rwxr-xr-x 1 root root 61453024 Nov 13 12:10 /usr/local/cuda-8.0/lib/libcudnn.so.4.0.7
lrwxrwxrwx 1 root root       17 Jan 17 13:52 /usr/local/cuda-8.0/lib/libcudnn.so.5 -> libcudnn.so.5.1.5
-rwxr-xr-x 1 root root 78065952 Jan 12 11:03 /usr/local/cuda-8.0/lib/libcudnn.so.5.0.5
-rwxr-xr-x 1 root root 79337624 Jan 17 13:52 /usr/local/cuda-8.0/lib/libcudnn.so.5.1.5
-rw-r--r-- 1 root root 69756172 Jan 17 13:52 /usr/local/cuda-8.0/lib/libcudnn_static.a
```

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
`0.12.1`
If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

I'm getting a strange error when trying to compute the intersection over union using tensorflows tf.contrib.metrics.streaming_mean_iou.
This was the code I was using before which works perfectly fine

```
import tensorflow as tf
label = tf.image.decode_png(tf.read_file('/path/to/label.png'),channels=1)
label_lin = tf.reshape(label, [-1,])
weights = tf.cast(tf.less_equal(label_lin, 10), tf.int32)
mIoU, update_op = tf.contrib.metrics.streaming_mean_iou(label_lin, label_lin,num_classes = 11,weights = weights)
init = tf.local_variables_initializer()
sess.run(init)
sess.run([update_op])
```
However when I use a mask like this

```
mask = tf.image.decode_png(tf.read_file('/path/to/mask_file.png'),channels=1)
mask_lin = tf.reshape(mask, [-1,])
mask_lin = tf.cast(mask_lin,tf.int32)
mIoU, update_op = tf.contrib.metrics.streaming_mean_iou(label_lin, label_lin,num_classes = 11,weights = mask_lin)
init = tf.local_variables_initializer()
sess.run(init)
sess.run([update_op])
```
It keeps on failing after an irregular number of iterations showing this error:

`*** Error in `/usr/bin/python': corrupted double-linked list: 0x00007f29d0022fd0 ***`

I checked the shape and data type of both mask_lin and  weights. They are the same, so I cannot really see what is going wrong here.
Also the fact that the error comes after calling update_op an irregular number of times is strange. Maybe TF empties the mask_lin object after calling several sess.run()'s ?
Or is this some TF bug? But then again why would it work with weights...

**Comment by aselle** [comment]
Is there anything special about how you prepared the png files. Could you run "file <png>" on them to show their specs. How did you create them? What tool? Try replacing those file read called with creation of tensorflow constants and see if it works ok.

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
