### ISSUE TITLE
bugs with cifar10 while doing evaluation

### ISSUE THREAD

**Issue by DongHyunLeee** [tensorflow/tensorflow#8827]
I slightly modify the cifar10 code, which is modifying length of width and height not to have same length.

height = 16
width = 32

While I did eval, it showed an error log cifar10_input.py at "  float_image.set_shape([height, width, 3])" this line.
I debugged it, I found a strange thing. Above two line from this, I found this "  resized_image = tf.image.resize_image_with_crop_or_pad(reshaped_image,**width, height**)". 
The reason why I felt strange is the position of second and third param of resize_image_with_crop_or_pad is not same to compare any other functions. (normally height is second and width is third. or first and second.) I mean the order is strange.

So I think that "  resized_image = tf.image.resize_image_with_crop_or_pad(reshaped_image, **height, width**)" may be correct.

**Comment by awav** [comment]
I'll just leave it here, https://www.tensorflow.org/api_docs/python/tf/image/resize_image_with_crop_or_pad

**Comment by aselle** [comment]
@neilhan , this seems to be a problem. Could you take a look?

**Comment by nealwu** [comment]
It looks like you're talking about [this file](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_input.py) in the models repository? That was fixed previously by this pull request: https://github.com/tensorflow/models/pull/1011. You should pull the repository again.
