### ISSUE TITLE
Build fails on Mac OSX 10.11.3 with `no type  named 'Scalar' in...`

### ISSUE THREAD

**Issue by rizzomichaelg** [tensorflow/tensorflow#883]
Using the most recent commit "a27d844e05447e65aa279ae5269a2d75590f46f6" on Jan 25, 2016, the build fails with 
```
./external/eigen_archive/eigen-eigen-
c8e5d094f3a9/unsupported/Eigen/CXX11/src/Tensor/TensorContractionBlocking.h:29:31: error: no type
 named 'Scalar' in 'Eigen::internal::TensorContractionInputMapper<float, long, 0,
 Eigen::TensorEvaluator<const Eigen::TensorReshapingOp<const Eigen::DSizes<long, 2>, const 
Eigen::TensorImagePatchOp<-1, -1, const Eigen::TensorMap<Eigen::Tensor<const float, 4, 1, long>, 
16> > >, Eigen::ThreadPoolDevice>, Eigen::array<long, 1>, Eigen::array<long, 1>, 4, true, true, 0>'
  typedef typename RhsMapper::Scalar RhsScalar;
```

using an older commit from Jan 21, 2016  "e14090d217fc4e7e49ac04ccbc50acdba8b9f120" completes normally.

**Comment by vrv** [comment]
FWIW, our builds on Jenkins are still working...

**Comment by blueegg** [comment]
same error as rizzomichaelg.

**Comment by ville-k** [comment]
I'm getting this same error on OS X as well.  Running OS X 10.10 + Xcode 7.2

**Comment by blueegg** [comment]
This error came with the commit "19b3606".

**Comment by sauravskumar99** [comment]
It's not working on mac...

**Comment by vrv** [comment]
I might revert 19b3606: can anyone confirm that reverting just that CL fixes the problem for them?

**Comment by vrv** [comment]
Reverted the change that updated Eigen.  Let us know if this was not enough and we'll investigate further.

**Comment by rizzomichaelg** [comment]
Compiles!  Thanks for the help.
