### ISSUE TITLE
Couldn't open CUDA library libcupti.so.8.0

### ISSUE THREAD

**Issue by stoneyang** [tensorflow/tensorflow#8830]
Hi,

I've installed 1.0 on my ubuntu 16.04 machine and deployed tf-1.0 with success, at least before I run the example shipped with tf, e.g, [mnist_with_summaries.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py)

When running mnist_with_summaries.py, I got the very problem posted in #5282. The discussion is mainly about the missing `libcupti.so` and most of them suggested to install or symlink the lib. But both approach didn't work for me.... Since the `so` file exists when installing CUDA-8.0 under the directory `/usr/local/cuda/extra/CUPTI/lib64/`, so I thought what I need to do is just link the library under the directory `/usr/local/cuda/lib64/`. However, problem still exists after the linking. And the `libcupti-dev` in `apt-get` is old (v7.5), which fails also. 

Anyone could give me some advice? Thanks in advance. 

@drpngx @gunan @K-Wu

**Comment by gunan** [comment]
Did you try adding `/usr/local/cuda/extra/CUPTI/lib64/` to your `LD_LIBRARY_PATH`

**Comment by stoneyang** [comment]
Thanks for your timely reply! @gunan 

Do you mean [here](https://github.com/tensorflow/tensorflow/blob/v1.0.0/tensorflow/tools/docker/Dockerfile.devel-gpu#L90)? 

I installed tf 1.0.0 from `pip` repo. I've no idea about where to check this....

**Comment by gunan** [comment]
PIP has no relation to the environment variable.
Based on your reply, I assume you did not set it.
You can try this before you run `mnist_with_summaries.py`
It will have to be run in the same terminal, right before you run TF.
```
export LD_LIBRARY_PATH=/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH
```

**Comment by stoneyang** [comment]
Thanks very much for pointing out this! @gunan 

Thought I need to learn more on OS, especially linux....

**Comment by ShariqM** [comment]
Note @gunan had a typo in his first suggestion ("extra" should be "extras") as it is, correctly, in his second comment.

**Comment by HareshMiriyala** [comment]
What if i donot have the cuda folder in /usr/local ? I'm trying to run it on cloud and I use module to load cuda.

**Comment by AntoinePlumerault** [comment]
If you use a module, you have to find where your module is use the path of the cuda version inside. For me it was:
`export LD_LIBRARY_PATH=/opt/cuda-9.0_cudnn-7.4.2/extras/CUPTI/lib64:$LD_LIBRARY_PATH`

**Comment by HareshMiriyala** [comment]
Thanks for that comment ! I found my module at **/opt/apps/cuda/9.0/extras/CUPTI/lib64/** , 
adding it here just incase someone else stumbles upon the same problem. Goodluck !

**Comment by prabhuiitdhn** [comment]
Check your libcupti.so.8.0 file in "/usr/local/cuda/extra/CUPTI/lib64/" path. If exists, copy the whole libcupti.* file in LD_LIBRARY_PATH

>> cd /usr/local/cuda/extra/CUPTI/lib64/
>> sudo cp /usr/local/cuda/extra/CUPTI/lib64/libcupti* /directory/of/LD/LIBRARY/PATH/

Hope this will work fine, for me It worked.
Good luck !!

**Comment by JaneWuNEU** [comment]
I confirm that the path of libcupti has been added to LD_LIBRARY_PATH, but the program still reminds that can not load libcupti.so. Then, I execute the following commands:
`sudo cp /usr/local/cuda-10.1/extras/CUPTI/lib64/libcupti.so /usr/local/lib/libcupti.so && sudo ldconfig
sudo cp /usr/local/cuda-10.1/extras/CUPTI/lib64/libcupti.so.10.1 /usr/local/lib/libcupti.so.10.1 && sudo ldconfig`.
It works.
