### ISSUE TITLE
DynamicAttentionWrapper expects own state on the 0-th step

### ISSUE THREAD

**Issue by RobRomijnders** [tensorflow/tensorflow#8833]
Using Tensorflow 1.1rc0
AFAIK the [DynamicAttentionWrapper](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py) wraps an attention mechanism around the RNNCell. To do so, it passes around its own DynamicAttentionWrapperState in the __call__()

However, I think that on the 0-th step, the network cannot pass such state as an argument, because the function gets called by a general decoder. (which doesnt know what cell it will encounter)

I got the following error
```python
Traceback (most recent call last):
  File "/home/rob/Documents/frosha/analysis-service/src/analysis_parser/analysis_parser/trainer_class.py", line 54, in __init__
    self.model = Model(self.tok_chr.dim)
  File "/home/rob/Documents/frosha/analysis-service/src/analysis_parser/analysis_parser/models/rnn_seq2seq_tf.py", line 164, in __init__
    outputs, _ = dynamic_decode(decoder, impute_finished = True, maximum_iterations = max_sl)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 278, in dynamic_decode
    swap_memory=swap_memory)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2623, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2456, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2406, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 231, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/seq2seq/python/ops/basic_decoder.py", line 140, in step
    cell_outputs, cell_state = self._cell(inputs, state)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/seq2seq/python/ops/dynamic_attention_wrapper.py", line 530, in __call__
    cell_inputs = self._cell_input_fn(inputs, state.attention)
AttributeError: 'tuple' object has no attribute 'attention'
```
The error indicates that the current state has no attribute attention. But that's the final state of the encoder, which doesn't use this syntax

The following snippet shows the use of the wrapper. This was coded after [this](https://www.tensorflow.org/versions/r1.1/api_guides/python/contrib.seq2seq#Dynamic_Decoding) explanation

```python
encoder_outputs, encoder_state = core_rnn.static_rnn(
                encoder_cell, encoder_inputs, dtype=dtype, sequence_length=self.SL_enc)

#Some other code

attention_size = 10
attn_obj = BahdanauAttention(num_units=attention_size,
                                             memory=attention_states,
                                             memory_sequence_length=self.SL_enc,
                                             normalize=True,
                                             name='BahdanauAttentionObject')

wrapped_cell = DynamicAttentionWrapper(cell_dec_fw,
                                                       attn_obj,
                                                       D,
                                                       output_attention=False,
                                                       name='DynAttnWrap')

sampler = ScheduledEmbeddingTrainingHelper(decoder_inputs,
                                                        sequence_length=self.SL_dec,
                                                        embedding=embedding_in,
                                                        sampling_probability=self.samp_prob)
decoder = BasicDecoder(wrapped_cell,
                                       sampler,
                                       encoder_state)
outputs, _ = dynamic_decode(decoder)
```

**Comment by proximacent** [comment]
Where is DynamicAttentionWrapper? It does not seem to be in tf.contrib.seq2seq. Is AttentionWrapper now dynamic by default?

**Comment by RobRomijnders** [comment]
The dynamic attention wrapper is [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py)

**Comment by proximacent** [comment]
Ok I see the confusion. According to [this](https://github.com/tensorflow/tensorflow/commits/master/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py) it was renamed a few days ago from DynamicAttentionWrapper to AttentionWrapper. Many edits since, try to repull and test. I'll test and let you know.

**Comment by aselle** [comment]
I apologize, but we typically cannot support the contrib directories of tensorflow unless they are underlying tensorflow bugs.

@ebrevdo.

**Comment by ebrevdo** [comment]
That's right, the decoder needs a new, separate, type of state than what
the encoder emitted.

As of today I pushed a new method to AttentionWrapperState object called
.clone().  You would use it thus:

`initial_state = wrapper.zero_state(...).clone(cell_state=encoder_state)`

and pass that initial_state to the decoder.

**Comment by ebrevdo** [comment]
(i may consider that we can add an initial_cell_state= argument when constructing the wrapper; but that approach mixes concerns.  we'll see)

**Comment by proximacent** [comment]
There's something I'm not getting, and it may be more theoretical. If the decoder's cell is an AttentionWrapper, which in turn attends to the output of the encoder RNN, why must the decoder's initial_state be an AttentionWrapperState?

Also I checked for the `.clone(...)` in `attention_wrapper.py` on master but couldn't find it. I'm probably blind though.

**Comment by proximacent** [comment]
Oh my bad, it's just a "double" initialization, initilization for the hidden states and for the attention.

**Comment by proximacent** [comment]
Ok, nope. I tried to set the initial cell state and attention, based on the other attention's zero_state method, but no go.

Here's what I tried
```python    
    # Attention Mechanisms. Bahdanau is additive style attention
    attn_mech = tf.contrib.seq2seq.BahdanauAttention(
        num_units = mem_units, # depth of query mechanism
        memory = attention_states, # hidden states to attend (output of RNN)
        memory_sequence_length=seq_len_enc, # masks false memories
        normalize=False, # normalize energy term
        name='BahdanauAttention')

    # Attention Wrapper: adds the attention mechanism to the cell
    attn_cell = tf.contrib.seq2seq.AttentionWrapper(
        cell = cell,# Instance of RNNCell
        attention_mechanism = attn_mech, # Instance of AttentionMechanism
        attention_size = attn_units, # Int, depth of attention (output) tensor
        attention_history=False, # whether to store history in final output
        name="attention_wrapper")

    # TrainingHelper does no sampling, only uses inputs
    helper = tf.contrib.seq2seq.TrainingHelper(
        inputs = x, # decoder inputs
        sequence_length = seq_len_dec, # decoder input length
        name = "decoder_training_helper")

    # Decoder setup
    batch_size = tf.shape(x)[0]
    attn_zero = attn_cell.zero_state(batch_size=batch_size, dtype=tf.float32)
    init_state = tf.contrib.seq2seq.AttentionWrapperState(\
                cell_state=encoder_state,
                attention=attn_zero,
                time=0,
                attention_history=())
    decoder = tf.contrib.seq2seq.BasicDecoder(
              cell = attn_cell,
              helper = helper, # A Helper instance
              initial_state = init_state, # initial state of decoder
              output_layer = None) # instance of tf.layers.Layer, like Dense

    # Perform dynamic decoding with decoder object
    outputs, final_state = tf.contrib.seq2seq.dynamic_decode(decoder)
```

But got an error on the `dynamic_decode` (below). Maybe you have instructions on how to properly set this up?

```shell
  File "/home/andre/projects/seq2seq_drr/enc_dec.py", line 232, in decoder_train_attn
    outputs, final_state = tf.contrib.seq2seq.dynamic_decode(decoder)
  File "/home/andre/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 278, in dynamic_decode
    swap_memory=swap_memory)
  File "/home/andre/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2623, in while_loop
    result = context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/andre/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2456, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/andre/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2406, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/andre/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 231, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "/home/andre/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/seq2seq/python/ops/basic_decoder.py", line 140, in step
    cell_outputs, cell_state = self._cell(inputs, state)
  File "/home/andre/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 532, in __call__
    cell_inputs = self._cell_input_fn(inputs, state.attention)
  File "/home/andre/anaconda3/lib/python3.5/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 443, in <lambda>
    lambda inputs, attention: array_ops.concat([inputs, attention], -1))
  File "/home/andre/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1036, in concat
    name=name)
  File "/home/andre/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 519, in _concat_v2
    name=name)
  File "/home/andre/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 464, in apply_op
    raise TypeError("%s that don't all match." % prefix)
TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [float32, <NOT CONVERTIBLE TO TENSOR>] that don't all match.
```

**Comment by ebrevdo** [comment]
You want:

init_state = attn_zero.clone(cell_state=encoder_final_state)

**Comment by proximacent** [comment]
Awesome, finally got it to work. Your `clone` method only popped up today when I pulled, for whatever reason.

**Comment by neural22** [comment]
@ebrevdo I tried to use your previous code as explained. But If I put the encoder_state of the previous level (2 bidirectional encoders with GRU), I have a memory leak on GPU.
More precisely, here my code:
```
        W_embedding_output = tf.Variable(tf.random_uniform([decoder_output_dim, self.vocab_size], -0.01, 0.01), name="embedding_output")
        W_t = tf.transpose(W_embedding_output, [1, 0])
        output_y_embedded = tf.nn.embedding_lookup(W_t, output_y)

        # base cell to use for the decoder (same of training, also for attention technique)
        base_cell = DropoutWrapper(GRUCell(decoder_output_dim), self.dropout, 1.0, self.dropout)
        attention_technique = BahdanauAttention(decoder_output_dim, encoded)
        # helper to fit the previous state into decoder
        helper = TrainingHelper(output_y_embedded, output_batch_length)
        # cell to use, with attention method
        cell = DynamicAttentionWrapper(
            base_cell,
            attention_technique,
            self.encoder_dim,
            output_attention=False
        )
        # initial state of the decoder, should be use the last encoder state as initial point?
        zero_state = cell.zero_state(self.batch_size, tf.float32)

        # zero_state = zero_state.clone(cell_state=encoder_state)

        # decode
        (outputs, index), final_state = dynamic_decode(
            BasicDecoder(
                cell,
                helper,
                zero_state)
        )
```
So, If I remove use the line **zero_state = zero_state.clone(cell_state=encoder_state)** during the session.run the program continuously allocate memory on GPU and finally it crashes due to device memory become full.
Here the error.
```
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[9024,1024]
	 [[Node: gradients/tower2/Decoder/MatMul_grad/MatMul = MatMul[T=DT_FLOAT, _class=["loc:@tower2/Decoder/MatMul"], transpose_a=false, transpose_b=true, _device="/job:localhost/replica:0/task:0/gpu:2"](gradients/tower2/Decoder/output_grad/Reshape, tower2/Decoder/embedding_output/read)]]
	 [[Node: gradients/Sub_2/_942 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:2", send_device_incarnation=1, tensor_name="edge_9973_gradients/Sub_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](^_cloopgradients/tower2/Decoder/decoder/while/BasicDecoderStep/TrainingHelperNextInputs/cond/TensorArrayReadV3_grad/TensorArrayGrad/TensorArrayGradV3/_828)]]
```
Am I using these classes in a wrong way? Could it be a bug?

**Comment by ebrevdo** [comment]
I'd need to see how you're calling session.run and the rest of your code to see if you're doing anything else wrong.  I suggest starting a thread on StackOverflow for this since it could be user error.  This thread is closed since the originally reported issue has been fixed in TensorFlow.

**Comment by RylanSchaeffer** [comment]
`AttributeError: 'DynamicAttentionWrapperState' object has no attribute 'clone'`

@proximacent Do you know why I'm getting this error or how I can fix it?

**Comment by RylanSchaeffer** [comment]
For anyone else coming along, I think I found the problem*. @ebrevdo 's comments are based on TensorFlow 1.2, not TensorFlow 1.1, so if you want to solve this problem, you'll need to switch. Then, you'll want to replace DynamicAttentionWrapper with AttentionWrapper.

*if I'm wrong, anyone can feel free to correct me.

**Comment by proximacent** [comment]
@RylanSchaeffer , yes that's correct. At the time, ebrevdo's code was pre 1.2 but post 1.1. In the 1.2 release, some other naming has changed as well. For example AttentionWrapper's `attention_size` is now `attention_layer_size`. If you are using my above code, check the [AttentionWrapper page](https://www.tensorflow.org/versions/master/api_docs/python/tf/contrib/seq2seq/AttentionWrapper) for the new `__init__` arguments.

**Comment by RylanSchaeffer** [comment]
@proximacent , I'm running into a new problem. Can I email you? There's not much (up-to-date) material online, and it sounds like you're already done something similar to what I'm working on.

**Comment by RylanSchaeffer** [comment]
My problem is that inside somewhere inside my decoder, the following line produces this error: TypeError: 'Tensor' object is not iterable.

`c, h = state`

I've stepped through my code, and the failure seems to be generated after a number of calls to

`outputs = self.call(inputs, *args, **kwargs)`

inside the Layer base class.

**Comment by proximacent** [comment]
@RylanSchaeffer, what's `state`, what is the output of `type(state)`? If I had to guess, maybe you changed from LSTM cell to GRU. Some functions, like tf.nn.dynamic_rnn, return a pair of (output, state), where `state` is LSTMStateTuple if you are using an LSTM cell, (which have `c` and `h`), but a Tensor if using a GRU cell.

**Comment by RylanSchaeffer** [comment]
It depends on when I evaluate `type(state)`. For the first two times that `c, h = state` is evaluated, state has type `<class 'tensorflow.python.ops.rnn_cell_impl.LSTMStateTuple'>`. Then, (just before my code breaks), state has type `<class 'tensorflow.python.framework.ops.Tensor'>`.

I am using LSTM cells, not GRU cells (specifically `BasicLSTMCell` from `tensorflow.contrib.rnn`). Why and where would my code be switching?

**Comment by RylanSchaeffer** [comment]
Here's some of the code that I wrote:
`

            bahdanau_attention = BahdanauAttention(num_units=DECODER_NUM_UNITS,
                                                   memory=encoder_outputs)

            attention_cell = AttentionWrapper(cell=self._create_lstm_cell(),
                                              attention_mechanism=bahdanau_attention)

            attention_zero = attention_cell.zero_state(batch_size=self.x.shape[0], dtype=tf.float32)

            init_state = attention_zero.clone(cell_state=encoder_final_states)

            training_helper = TrainingHelper(inputs=self.y,  # feed in ground truth
                                             sequence_length=length)  # feed in sequence length

            decoder = BasicDecoder(cell=attention_cell,
                                   helper=training_helper,
                                   initial_state=init_state)
`

The error is raised in line 379 `c, h = state` of TensorFlow's rnn_cell_impl.py.

If I set a breakpoint right before this line, the first two times I reach the breakpoint, `type(state)` evaluates to `<class 'tensorflow.python.ops.rnn_cell_impl.LSTMStateTuple'>`. The third time, `type(state)` evaluates to `<class 'tensorflow.python.framework.ops.Tensor'>`.

**Comment by ebrevdo** [comment]
I'm away this week but hope one of my collaborators can help with this
issue.

**Comment by oahziur** [comment]
Hi @RylanSchaeffer,

Let me see if I can help you. What is the structure of your decoder? Is it a MultiRNNCell with several BasicLSTMCells? Can you print what is exactly in the encoder_final_states? (Is it something like (LSTMStateTuple, LSTMStateTuple, Tensor)?)

**Comment by RylanSchaeffer** [comment]
@oahziur , thank you! My decoder is not a MultiRNNCell - it's just one BasicLSTMCell. Here is my method I use to create an LSTM cell:

`
    @staticmethod
    def _create_lstm_cell():
        return BasicLSTMCell(LSTM_SIZE)
`

My `encoder_final_states` has type `<class 'tensorflow.python.framework.ops.Tensor'>` and `shape=(2, ?, 128)`; this makes sense, as I'm using a Bidirectional RNN and my `LSTM_SIZE = 64`. `encoder_final_states` one of the two values returned by the following method:

`
    def _define_encoder(self):
        with tf.name_scope('define_encoder'):
            outputs, final_states = bidirectional_dynamic_rnn(cell_fw=self._create_lstm_cell(),
                                                              cell_bw=self._create_lstm_cell(),
                                                              inputs=self.x,
                                                              dtype=tf.float32)

            outputs = tf.concat(outputs, axis=-1)
            final_states = tf.concat(final_states, axis=-1)

        return outputs, final_states
`

**Comment by oahziur** [comment]
@RylanSchaeffer , if your LSTM_SIZE=64, the final state should be (2, ?, 256) tensor if you set [`state_is_tuple=False` in BasicLSTM](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/BasicLSTMCell), since each state is 64, so a single state should have 128.

I think you shouldn't do `final_states = tf.concat(final_states, axis=-1)` if `state_is_tuple=True` (the default behavior) since the return value of [bidirectional_dynamic_rnn](https://www.tensorflow.org/api_docs/python/tf/nn/bidirectional_dynamic_rnn) will be a tuple of LSTMStateTuple instead of a tuple of Tensor. Concatenate c state and h state separately and then create a  `tf.contrib.rnn.LSTMStateTuple` to pass to the decoder should fix your problem.

**Comment by RylanSchaeffer** [comment]
@oahziur , I'm a little confused. My understanding was that `final_states = tf.concat(final_states, axis=-1)` isn't concatenating the c state and the h state for an LSTM cell, but rather concatenating the outputs of the two RNNs that make up the Bidirectional RNN, and concatenating the states of the two RNNs. Can you clarify?

**Comment by oahziur** [comment]
@RylanSchaeffer , I think the bidirectional_dynamic_rnn returns outputs and final states. 

You have use `outputs = tf.concat(outputs, axis=-1)` to concat the outputs, which isn't a problem.

If you print final_states before `final_states = tf.concat(final_states, axis=-1)`, it should be (LSTMStateTuple, LSTMStateTuple) because you have one fw_cell and one bw_cell.

**Comment by RylanSchaeffer** [comment]
@oahziur ok, that makes sense! I'm now confused by what you mean when you say, "then create a tf.contrib.rnn.LSTMStateTuple to pass to the decoder should fix your problem." Can you explain more?

**Comment by RylanSchaeffer** [comment]
My confusion stems from the fact that `BasicDecoder` accepts `initial_state: A (possibly nested tuple of...) tensors and TensorArrays.` Since I pass in `init_state`, where `init_state = attention_zero.clone(cell_state=encoder_final_states)` and encoder_final_states is a 2-tuple of LSTMStateTuples, it doesn't seem like I should need to make any modifications.

**Comment by oahziur** [comment]
@RylanSchaeffer The problem is that you decoder only have 1 BasicLSTMCell so it can only accept a single LSTMStateTuple, but you have 2 LSTMStateTuples from the `bidirectional_dynamic_rnn`. 

Is this helpful?

**Comment by RylanSchaeffer** [comment]
@oahziur , let me try to explain what my current understanding is, and you can tell me if I'm correct. A BasicDecoder accepts only one cell. One cell corresponds to one LSTMStateTuple (consisting of c and h). My problem is that I have two LSTMStateTuples. To reduce the two LSTMStateTuples down to one LSTMStateTuple, I need to separately concatenate the c states (i.e. c = c1 concat c2) and the h states (i.e. h = h1 concat h2), and then pass the newly created c and h states into a new LSTMStateTuple.

If that's correct, my next question is where I would use this new LSTMStateTuple? BasicDecoder accepts a cell, not a LSTMStateTuple. Would I pass the LSTMStateTuple in as the initial state? That makes the most sense. But then how do I do this? Do I change my code from `init_state = attention_zero.clone(cell_state=encoder_final_states)` to `init_state = attention_zero.clone(cell_state=new_lstm_state_tuple_created_by_concatenating_encoder_final_states_separately)`?

**Comment by oahziur** [comment]
@RylanSchaeffer Yes. your understanding is correct.

Just a reminder, I believe your decoder lstm cell needs to have `2*LSTM_SIZE` in order to match the shape of the new concatenated state.

**Comment by RylanSchaeffer** [comment]
Makes sense. @oahziur Thank you so much!

**Comment by RylanSchaeffer** [comment]
@oahziur (I don't know if this is inappropriate to ask, but) are you a TensorFlow developer?

**Comment by RylanSchaeffer** [comment]
@oahziur (I don't know if this is inappropriate to ask, but) are you a TensorFlow developer?

**Comment by RylanSchaeffer** [comment]
@oahziur , I have an unrelated question. I'm currently trying to use RNNs to solve the problem I'm working on, but I'd also like to consider using fully convolutional models as well. How would you recommend storing and processing my data in a way conducive to training both types of models?

Currently, I've written a script to parse all of my data (originally in .csv files) into `tf.train.SequenceExample`s and write those to TFRecords. Then I use a TFRecordReader in conjunction with `tf.parse_single_sequence_example` to pipe data into my RNN models for training. However, I don't think that this will work for convolutional models.

I don't know if asking here makes sense. Creating a new issue wouldn't make sense, but people on StackOverflow don't seem to respond to TensorFlow questions with the same alacrity (if at all).

**Comment by oahziur** [comment]
@RylanSchaeffer I am not very familiar with modeling sequence data with convolutional models and your use cases, but if you data is fixed length, I think you can always reshape the input Tensor to fit your convolutional model after you parse the example.

**Comment by RylanSchaeffer** [comment]
@oahziur , can I try asking the question another way? Is there a protocol buffer other than `SequenceExample` that makes feeding data to a dynamic RNN easy?

To give more information, my data has the following shape: `[number of samples per minibatch, time steps per sample, number of features]`. Both `number of samples per minibatch` and `number of features` are fixed, but `time steps per sample` can vary (hence the use of a dynamic RNN). At least conceptually, it should be possible to reshape my data as `[number of samples per minibatch, time steps per sample, number of features, 1]` and treat this akin to a single-channel image (which can then be passed through convolutional layers). However, I'm confused by how I would parse data stored as a `SequenceExample` in a way that would let me do this reshaping.

**Comment by RylanSchaeffer** [comment]
I think I just don't understand how `SequenceExample` stores the sequential aspect of the data in a way that would let me reshape the data.

**Comment by RylanSchaeffer** [comment]
Nevermind. I think I figured it out.

**Comment by proximacent** [comment]
Funny, I was playing with my code and I think I got the exact error @RylanSchaeffer got. Basically I was switching back and forth between GRU and LSTM which don't have the same outputs from the `tf.nn.bidirectional_dynamic_rnn` function. The problem arises from:

```
      outputs, state = tf.nn.bidirectional_dynamic_rnn(\
                  cell_fw=cell_fw,
                  cell_bw=cell_bw,
                  inputs=x,
                  sequence_length=seq_len,
                  initial_state_fw=init_state_fw,
                  initial_state_bw=init_state_bw,
                  dtype=self.float_type)
```
If your cells are LSTM, then `state` is a tuple of 2 LSTMStateTuple, and if your cells are GRU then `state` is a tuple of Tensor. As mentioned, for LSTMStateTuple you need to "hack" concat `state`. I also have to `set_shape` to the `state` Tensor otherwise you can get issues with decoding. The code below works for both GRU and LSTM:

```
      # If LSTM cell, then "state" is not a tuple of Tensors but an
      # LSTMStateTuple of "c" and "h". Need to concat separately then new
      if "LSTMStateTuple" in str(type(state[0])):
        c = tf.concat([state[0][0],state[1][0]],axis=1)
        h = tf.concat([state[0][1],state[1][1]],axis=1)
        state = tf.contrib.rnn.LSTMStateTuple(c,h)
      else:
        state = tf.concat(state,1)
        state.set_shape([None, bi_encoder_size])
```
To me this seems a little hackish, but works for now. I think `tf.nn.bidirectional_dynamic_rnn` should have an optional "concat" arg which checks in the background what type of cell was passed and concats accordingly.

Cheers

**Comment by RylanSchaeffer** [comment]
@proximacent @oahziur @ebrevdo 

I'm trying to train a sequence to sequence model, but the training times are monotonically increasing. I posted on [StackOverflow](https://stackoverflow.com/questions/44706150/tensorflow-seq2seq-training-time-per-minibatch-monotonically-increases), but I thought I'd ask in case any of you have an idea of what I might be doing wrong.
