### ISSUE TITLE
[windows 7] Not using CUDA. No errors or messages indicating dlls have been loaded in log. 

### ISSUE THREAD

**Issue by bicubic** [tensorflow/tensorflow#8835]
Issue: after upgrading from 0.12 to 1.0.1, I lost GPU support. On 0.12, there were log entries indicating successful loading of cuda/cudnn dlls and log entries if dlls weren't found. On 1.0.1, I don't see any log entries when importing tensorflow, but GPU is no longer listed amongst available devices. 

Can't provide much useful information without anything in the logs. Has logging been disabled, or is it getting written to a file now? How can I diagnose this?

---

Operating System: windows 7

Installed version of CUDA and cuDNN: CUDA 8.0 cuDNN 6.0

Output from `python -c "import tensorflow; print(tensorflow.__version__)"`. 1.0.1

What other attempted solutions have you tried?
Reinstalled tf, reinstalled cudnn

**Comment by jubjamie** [comment]
Firstly, I noticed that you are using the brand new cuDNN 6.0. Tensorflow is built to use cuDNN 5.1 so this might be your problem. Could @gunan perhaps comment on whether 6.0 breaks Tensorflow/there is planned support for 6.0?
In the meantime, let's assume that it is **not** the issue and i'll give you my answer for users of cuDNN 5.1:
 
When you run your session.run() call you should see that Tensorflow outputs device information.
For example, I see the following:
```
2017-03-30 14:06:33.577701: I c:\tf_jenkins\home\workspace\nightly-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:887] Found device 0 with properties:
name: Tesla K40c
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:02:00.0
Total memory: 11.18GiB
Free memory: 11.11GiB
```
This appears in my console logs. Can you try calling a session.run(), perhaps your variable initialiser and see if you are able to find those logs. You might have to look between any _compilation instruction warnings_.

You could also try increasing the verbosity if you previously tweaked it.
If there's definitely nothing, ensure that it is being picked up by nvidia-smi

**Comment by bicubic** [comment]
Looks like I accidentally installed cudnn 6.0 side by side with 5.1 while attempting to fix the issue. This is not the cause of the problem though, as I was on a working setup with just cudnn 5.1 prior to upgrading to 1.0.1

Invoking session.run() produces the following log output: https://gist.github.com/bicubic/c3edcc0b311437dd6888edc4bac30315

`Device mapping: no known devices.` sounds ominous. 

This is based on the gpu example which explicitly assigns the job to gpu0 which was working recently on 0.12.

**Comment by jubjamie** [comment]
Strange. Is everything ok with nvidia-smi?

**Comment by bicubic** [comment]
nvidia-smi shows gpu is healthy and utilized, but not seeing any python/tf related processes in the utilization list.

**Comment by gunan** [comment]
We have not verified with cudnn 6 yet. It may work, or it may not work, no guarantees.

@bicubic I think somehow GPU device is invisible to your TF installation, but just to make sure could you try:

```
import tensorflow as tf
tf.test.is_gpu_available()
```

**Comment by bicubic** [comment]
@gunan howdy. Yep, that's returning `False` so it looks like my GPU is somehow invisible. Any suggestions how to proceed?

**Comment by asimshankar** [comment]
@bicubic : How did you install TensorFlow? Is it possible that you used `pip3 install tensorflow` instead of `pip3 install tensorflow-gpu`?

**Comment by bicubic** [comment]
@asimshankar I won't have bandwidth to troubleshoot this issue further in the near future. Are you happy to close this ticket and I'll raise a new one and reference this one when I have more information?
