### ISSUE TITLE
Bazel test failure in TF  (Linking error ) on RHEL 7.3

### ISSUE THREAD

**Issue by sandipmgiri** [tensorflow/tensorflow#8838]
### Environment info
Operating System: Rhel:7.3 (ppc64le)

####################################################
I could able to build the TF (version 1.0.1) successfully  , however I am getting following error for the command , bazel test  -c opt //tensorflow/...

ERROR: /root/Sandip/Bazel/new/with_patches/tensorflow/tensorflow/compiler/xla/tests/BUILD:953:1: Linking of rule '//tensorflow/compiler/xla/tests:broadcast_simple_test_cpu_parallel' failed: gcc failed: error executing command /usr/bin/gcc -o bazel-out/local-opt/bin/tensorflow/compiler/xla/tests/broadcast_simple_test_cpu_parallel '-Wl,-rpath,$ORIGIN/../../../../_solib_ppc/' -Lbazel-out/local-opt/bin/_solib_ppc -pthread ... (remaining 9 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/usr/bin/ld: bazel-out/local-opt/bin/tensorflow/compiler/xla/tests/broadcast_simple_test_cpu_parallel: hidden symbol `pthread_atfork' in /usr/lib64/libpthread_nonshared.a(pthread_atfork.oS) is referenced by DSO
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Target //tensorflow/compiler/xla/tests:broadcast_simple_test_cpu_parallel failed to build
Use --verbose_failures to see the command lines of failed build steps.
____Elapsed time: 4.953s, Critical Path: 4.18s

Any solution  ?

**Comment by gunan** [comment]
We do not have official support on RHEL.
You might have quicker response using Stackoverflow.
