### ISSUE TITLE
cannot run test_session on warpctc

### ISSUE THREAD

**Issue by ilovin** [tensorflow/tensorflow#8847]
python 3.5 ;  gtx1080*2

```
InvalidArgumentError (see above for traceback): Cannot assign a device to node 'CTCLoss': Could not satisfy explicit device specification '/device:GPU:0' because no supported kernel for GPU devices is available.
	 [[Node: CTCLoss = CTCLoss[_kernel="WarpCTC", ctc_merge_repeated=true, preprocess_collapse_repeated=false, _device="/device:GPU:0"](Const_3, Const, Const_1, CTCLoss/sequence_length)]]
```
### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN:  8.0.44 5

1. A link to the pip package you installed: 9.0.1
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`. 1.0.1 

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
https://github.com/baidu-research/warp-ctc/blob/master/tensorflow_binding/tests/test_ctc_loss_op.py

### What other attempted solutions have you tried?

after some search, I flip the flag to  `allow_soft_placement=True`, however I get
```
anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/test_util.py", line 248, in prepare_config
    config.allow_soft_placement = False
AttributeError: 'NoneType' object has no attribute 'allow_soft_placement'
```

And if I replace `self.test_session` to `tf.Session` and remove the `use_gpu` and `force_gpu` option
the error will disappear, don't know what happend

**Comment by aselle** [comment]
Since this is a third party kernel and tool, please file this bug on warp-ctc's issue tracker.
