### ISSUE TITLE
Allow SavedModelBuilder to overwrite existing directory

### ISSUE THREAD

**Issue by rajhans** [tensorflow/tensorflow#8852]
Currently, SavedModelBuilder throws an exception when called with a directory that already exists. It will be helpful to add a flag `overwrite` when initializing SavedModelBuilder, which allows it to overwrite the contents of the directory when .save() is called. 

When training a model every couple of hours on fresh data, it will be easier to overwrite existing models than having to implement housekeeping code around cleaning old models or writing code to move around new model after training.

**Comment by terryKing1992** [comment]
much more agree with you

**Comment by aselle** [comment]
We currently don't have anybody working on this. It would be great if you could help us by working on this and submitting a PR. Let us know if you need further clarification. Thanks!

**Comment by Mistobaan** [comment]
I was looking into this, and I think that is cleaner to have one single export dir per trained graph. You can add a time signature to the export dir '<model-id>-<YYYYHHMM>'  and link it to a  "last model" directory. Changing the behaviour of the SaveModelBuilder to account for overwrite cases is not worth it.

**Comment by martinwicke** [comment]
We had some internal discussions about this and we vehemently agree with @Mistobaan. We would very much avoid giving users a very sharp stick with which to poke themselves in the eye. We have lost lots of work to setups like this, let's not make this easier.

If you must, you can remove the directory before making the SavedModelBuilder.

**Comment by rajhans** [comment]
Yeah, already following single-export-dir per trained graph. Thanks for the discussion.

**Comment by tbrodbeck** [comment]
Would still be nice to have an optional overwrite flag though. (Sorry for warming up this old pizza with my 5 cents, btw)
