### ISSUE TITLE
Server terminated abruptly when build from source

### ISSUE THREAD

**Issue by mingdachen** [tensorflow/tensorflow#8860]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
Initially I encountered the problem described as in https://github.com/tensorflow/tensorflow/issues/8731

After modified configure file as in https://github.com/tensorflow/tensorflow/commit/fba05c300bf6840e76787680ed7fd1239cdb9ad0. This error happened

### Environment info
Operating System: CentOS Linux release 7.3.1611 (Core)

Installed version of CUDA and cuDNN: CUDA 7.5 and cuDNN 5.0
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`): 
$ ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root   322936 Dec  6 11:05 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Dec  6 11:05 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root       19 Dec  6 11:05 /usr/local/cuda/lib64/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root   383336 Dec  6 11:05 /usr/local/cuda/lib64/libcudart.so.7.5.18
-rw-r--r-- 1 root root   720192 Dec  6 11:05 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 asb  ttic       13 Apr 22  2016 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 asb  ttic       17 Apr 22  2016 /usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.0.5
-rwxr-xr-x 1 asb  ttic 59909104 Apr 22  2016 /usr/local/cuda/lib64/libcudnn.so.5.0.5
-rw-r--r-- 1 asb  ttic 58775484 Apr 22  2016 /usr/local/cuda/lib64/libcudnn_static.a

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
$ git rev-parse HEAD
83be34c47c7ed81c62bd61a908fde017e301b578

2. The output of `bazel version`
$ bazel version
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:19:38 2017 (1489666778)
Build timestamp: 1489666778
Build timestamp as int: 1489666778

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

./configure
Please specify the location of python. [Default is /home-nfs/mingdachen/anaconda2/envs/py35gpu/bin/python]:
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]:
Do you wish to use jemalloc as the malloc implementation? [Y/n]
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N]
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N]
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N]
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /home-nfs/mingdachen/anaconda2/envs/py35gpu/lib/python3.5/site-packages
Please input the desired Python library path to use.  Default is [/home-nfs/mingdachen/anaconda2/envs/py35gpu/lib/python3.5/site-packages]

Using python library path: /home-nfs/mingdachen/anaconda2/envs/py35gpu/lib/python3.5/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N]
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]:
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 7.5
Please specify the location where CUDA 7.5 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 5
Please specify the location where cuDNN 5 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]:
INFO: $TEST_TMPDIR defined: output root default is '/scratch/mingda/'.
Extracting Bazel installation...
.........
INFO: All external dependencies fetched successfully.
Configuration finished

$ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package &> ../log

### What other attempted solutions have you tried?
I have tried different branches, including r1.0, r1.1 and master

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).
[log.txt](https://github.com/tensorflow/tensorflow/files/884405/log.txt)

The log file of /scratch/mingda/_bazel_mingdachen/b48312abf86569e91b44fe1197c1c461/server/jvm.out is empty

**Comment by aselle** [comment]
If you rerun the bazel command, will it continue on some more and eventually finish? Maybe @jart  or @gunan  have some insight?

**Comment by gunan** [comment]
Looks like bazel crashed?
@damienmg any ideas?

**Comment by damienmg** [comment]
Definitely a Bazel issue, no idea on why

**Comment by mingdachen** [comment]
@aselle Thanks for your reply!
I didn't rerun from the bazel command, but I reran from the ./configure, and in each time, it would stop at different places. Hope this information would be helpful.
As a workarond, I just installed the CUDA 8.0, and used the pip to install the tensorflow with gpu support.

**Comment by aselle** [comment]
is your root disk maybe nearly full? Otherwise, it's pretty difficult to say. Maybe a bazel bug?

**Comment by gunan** [comment]
@mingdachen after failures, please only rerun the bazel command.
You only need to run configure once.
Then we can see if bazel can incrementally complete the build on the 2nd run

**Comment by kahkeng** [comment]
This was happening to me too on the v1.0.1 tag with bazel 0.4.5. I've put the bazel cache on a separate partition so it has sufficient space.

Rerunning the bazel command will quickly fail again, repeatedly, and also ask you to rerun ./configure even though I specified GPU support the first time:
`ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
`
Rerunning ./configure and repeating everything doesn't help. Based on kernel logs, it doesn't seem like we hit an out-of-memory error.

However, I was able to eventually get it to build by adding `--local_resources 2048,.5,1.0` to the build command anyway, as suggested by the tip in https://www.tensorflow.org/install/install_sources. It takes a lot longer, but doesn't max out the CPU and eventually completes without issues.

**Comment by damienmg** [comment]
@kahkeng: I believe you should look at the syslog to see if a OOM killer is in action, which would explain.

Bazel tries to use all the available memory and CPU to schedule as many action as possible but the resource estimation is currently broken which might explain why --local_resources works.

**Comment by proflim** [comment]
Got the same error but it worked fine when I just reran it.
