### ISSUE TITLE
[FeatureRequest] Decode gzipped files in tf.FixedLengthRecordReader

### ISSUE THREAD

**Issue by untom** [tensorflow/tensorflow#8865]
My dataset is stored in binary format that is easily compressible (from 100 MB down to ~0.5 MB), but I currently cannot make use of this in TF, unless I write a TFRecords file, which is way more cumbersome and leads to a lot of duplication -- I need to work with those files in other programs as well, so the binary format is the easiest solution for me. It would be nice if  tf.FixedLengthRecordReader would support on-the-fly decompression.

**Comment by aselle** [comment]
We would happy to accept a batch that allows this behavior, but we are unlikely to work on it ourselves, since we either use TFRecords or other data formats internally. It shouldn't be super difficult to do yourself. @saxenasaurabh can probably give you some direction on how to use the existing gzip classes, if you'd be willing to help out.

**Comment by saxenasaurabh** [comment]
This shouldn't be too hard imho. You should be able to swap out the `input_buffer_` in [FixedLengthRecordReader](https://github.com/tensorflow/tensorflow/blob/c664520a1a7642cd3c9368cd1bd036892d8966b2/tensorflow/core/kernels/fixed_length_record_reader_op.cc#L28) with the [ZlibInputStream](https://github.com/tensorflow/tensorflow/blob/bad7c50b9dc9789ad7dd0a62daca40b7269841ed/tensorflow/core/lib/io/zlib_inputstream.h#L38). You may need to subclass the [InputBuffer](https://github.com/tensorflow/tensorflow/blob/bad7c50b9dc9789ad7dd0a62daca40b7269841ed/tensorflow/core/lib/io/inputbuffer.h#L32) from [InputStreamInterface](https://github.com/tensorflow/tensorflow/blob/bad7c50b9dc9789ad7dd0a62daca40b7269841ed/tensorflow/core/lib/io/inputstream_interface.h#L27) though.
You can specify the `compression_type` in a manner similar to the [TFRecordReader](https://github.com/tensorflow/tensorflow/blob/b07791f6e9b306937eb58f7bb6c3300cd26583af/tensorflow/core/kernels/tf_record_reader_op.cc) and add it to the op registration similar to [here](https://github.com/tensorflow/tensorflow/blob/b07791f6e9b306937eb58f7bb6c3300cd26583af/tensorflow/core/ops/io_ops.cc#L481).

**Comment by yongtang** [comment]
@untom @aselle @saxenasaurabh I created a PR #8901 to add gzip and zlib compression support for FixedLengthRecordReader. Please take a look.
