### ISSUE TITLE
Bugs when dequeue a 3-D input tensor from FIFOQueue

### ISSUE THREAD

**Issue by zzw922cn** [tensorflow/tensorflow#8870]
```python
x = tf.random_normal([time_length, batch_size, feature_size], mean=0, stddev=1)
## prepare data
q = tf.FIFOQueue(capacity=4, dtypes=tf.float32) 
enqueue_op = q.enqueue(x)
num_threads = 1 
qr = tf.train.QueueRunner(q, [enqueue_op] * num_threads)
tf.train.add_queue_runner(qr)
inputs = q.dequeue() 
```
As above code shows, when I use FIFOQueue and Cordinator to do input pipeline, the input is a 3-D tensor variable, but when I dequeue it from the FIFOQueue, errors comes:
```python
ValueError: as_list() is not defined on an unknown TensorShape.
```

Thus, I go to the source code of FIFOQueue, I found that FIFOQueue.enqueue method doesn't use a shape function. So, I add a line of code as following, it works well.
```python
x = tf.random_normal([time_length, batch_size, feature_size], mean=0, stddev=1)

## prepare data
q = tf.FIFOQueue(capacity=4, dtypes=tf.float32) 
enqueue_op = q.enqueue(x)
num_threads = 1 
qr = tf.train.QueueRunner(q, [enqueue_op] * num_threads)
tf.train.add_queue_runner(qr)
inputs = q.dequeue() 
inputs.set_shape(x.get_shape())
```

But if I change my input from 3-D tensor into 2-D tensor, the code runs very well without set_shape function manually. So I want to know why my 3-D input tensor can't work well but 2-D tensor input work well? Can the source code of FIFOQueue or QueueBase support shape function?

**Comment by aselle** [comment]
@mrry, this seems like it could need fixing. Please take a look. Thanks!

**Comment by mrry** [comment]
Can you please share the entire stack trace for that `ValueError`? I can't see any calls to `TensorShape.as_list()` in the queue implementation.

**Comment by zzw922cn** [comment]
@mrry Ok, my code is as follows:
```python
q = tf.FIFOQueue(capacity=4, dtypes=tf.float32) 
enqueue_op = q.enqueue(x)
num_threads = 1 
qr = tf.train.QueueRunner(q, [enqueue_op] * num_threads)
tf.train.add_queue_runner(qr)
inputs = q.dequeue() 
#inputs.set_shape(x.get_shape())
y = tf.reduce_mean(tf.reduce_sum(inputs, axis=0), axis=1, keep_dims=True)
labels = tf.cast(tf.greater(y, 0), tf.int32)

## build model
sequence_length = tf.Variable([time_length]*batch_size, dtype=tf.int32)
cell_fw = LSTMCell(num_units=hidden_size)
cell_bw = LSTMCell(num_units=hidden_size)
outputs, state = tf.nn.bidirectional_dynamic_rnn(
      cell_fw=cell_fw,
      cell_bw=cell_bw,
      inputs=inputs, 
      sequence_length=sequence_length,
      dtype=tf.float32,
      time_major=True)
```

error is
```python
Traceback (most recent call last):
  File "test1.py", line 32, in <module>
    time_major=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 350, in bidirectional_dynamic_rnn
    time_major=time_major, scope=fw_scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 546, in dynamic_rnn
    dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/rnn.py", line 615, in _dynamic_rnn_loop
    const_time_steps, const_batch_size = inputs_got_shape[0].as_list()[:2]
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 761, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")
ValueError: as_list() is not defined on an unknown TensorShape.
```
 and I think the error is caused by BLSTM, so maybe the set_shape bug can be fixed.

**Comment by mrry** [comment]
This doesn't sound like a bug (in the queues, at least). The actual error is in the `tf.nn.bidirectional_dynamic_rnn()` code, which does not seem to support inputs with unknown shape; the solution is to provide more static shape information.

When you create a `tf.FIFOQueue` with no `shapes` argument, you are allowing the queue to store tensors of *any* shape. Therefore, since when you create the `q.dequeue()` op we don't know exactly which tensors will be dequeued, we have to give it an unknown shape.

By calling `inputs.set_shape(x.get_shape())` you are asserting that all elements have a particular shape. You could have done the same thing by creating the queue as:

```python
q = tf.FIFOQueue(capacity=4, dtypes=tf.float32, shapes=x.get_shape())
```

**Comment by zzw922cn** [comment]
@mrry Thank you a lot, I understand now.

**Comment by mrry** [comment]
Glad to help clear things up!
