### ISSUE TITLE
text_classification.py doesn't works 

### ISSUE THREAD

**Issue by DanielaCaroline18** [tensorflow/tensorflow#8871]
....

  File "C:\Users\danie\Anaconda3\lib\site-packages\tensorflow\contrib\layers\python\ops\sparse_feature_cross_op.py", line 21, in <module>
    from tensorflow.contrib.framework import deprecated_arg_values
    ImportError: cannot import name 'deprecated_arg_values'

I'm using Spider.

**Comment by aselle** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
