### ISSUE TITLE
Tensorboard showing problems under keras callbacks

### ISSUE THREAD

**Issue by lk1983823** [tensorflow/tensorflow#8872]
My code runs well without any errors showing. However, when I use the command 
tensorboard --logdir = "my path", it shows nothing. I want someone to help me! Thanks.

tensorflow 1.0.1 keras 2.0  and python 3.4

And I found the debug shows:

```
INFO:tensorflow:TensorBoard is in debug mode.
INFO:tensorflow:Starting TensorBoard in directory /home/lk/lk
INFO:tensorflow:TensorBoard path_to_run is: {'/home/lk/lk/=': None}
INFO:tensorflow:Event Multiplexer initializing.
INFO:tensorflow:Event Multiplexer done initializing
INFO:tensorflow:TensorBoard reload process beginning
INFO:tensorflow:Starting AddRunsFromDirectory: /home/lk/lk/=
INFO:tensorflow:Done with AddRunsFromDirectory: /home/lk/lk/=
INFO:tensorflow:TensorBoard reload process: Reload the whole Multiplexer
_INFO:tensorflow:Beginning EventMultiplexer.Reload()
INFO:tensorflow:Finished with EventMultiplexer.Reload()_
INFO:tensorflow:TensorBoard done reloading. Load took 0.002 secs
INFO:tensorflow:TensorBoard is tag: b'41'
Starting TensorBoard b'41' on port 6006
(You can navigate to http://127.0.1.1:6006)

```
of which between INFO:tensorflow:Beginning EventMultiplexer.Reload() and INFO:tensorflow:Finished with EventMultiplexer.Reload(). There is no debuging information.

**Comment by aselle** [comment]
Please read the tutorial https://www.tensorflow.org/get_started/summaries_and_tensorboard.
 This should answer your question. Otherwise, ask a more specific question on StackOverflow (including your code)
