### ISSUE TITLE
Arbitrary dimension support for tf.tile and binary operators

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#8873]
`tf.transpose` uses template specialization for dimensions <= 5, then falls back to a slightly slower generic implementation which works for any dimension:

https://github.com/tensorflow/tensorflow/blob/504b91de8fa9a9cc4a4e17e59ed753ab677a1410/tensorflow/core/kernels/transpose_functor_cpu.cc#L23

It would be nice to use the same mechanism for `tf.tile` and the various binary operators.

**Comment by girving** [comment]
If anyone wants to take this on, I'd recommend trying `tf.tile` first: it's closer to `tf.transpose`.  Happy to answer questions.

**Comment by yanchen036** [comment]
Hi @girving ,
I'd like to work on this issue. I've written sketch code for it:
https://github.com/yanchen036/tensorflow/blob/arbitrary_dim_for_tile/tensorflow/core/kernels/tile_ops_impl.h#L55
https://github.com/yanchen036/tensorflow/blob/arbitrary_dim_for_tile/tensorflow/core/kernels/tile_ops.cc#L187

Are these the same as what you think? If I'm wrong pls correct me!

**Comment by girving** [comment]
@yanchen036 Those links don't make it easy to see diffs.  Am I right that you just added a stub for TileSimple but didn't write it?  If so, the existence of TileSimple is on the right path.  I'm not sure if you made other changes.

**Comment by yanchen036** [comment]
@girving I did 2 things. 
First, I wrote a TileSimple stub(now I know that's not you need) and a TileUsingEigen function
```c++
void TileUsingEigen(const Device& d, const Tensor& in, Tensor* out,
                    const gtl::ArraySlice<int32> broadcast_array)
```
which implements the old Tile::operator(). See https://github.com/yanchen036/tensorflow/blob/arbitrary_dim_for_tile/tensorflow/core/kernels/tile_ops_impl.h#L32

Second, I changed the Tile::operator() function from
```c++
template <typename Device, typename T, int NDIM>
void operator()(const Device& d, typename TTypes<T, NDIM>::Tensor out,
                typename TTypes<T, NDIM>::ConstTensor in,
                const Eigen::array<int32, NDIM>& broadcast_array) const
```
To
```c++
template <typename Device, typename T, int NDIM>
void operator()(const Device& d, const Tensor& in, Tensor* out,
                const gtl::ArraySlice<int32> broadcast_array) const {
    switch (in.dims()) {
        case 0:
            internal::TileUsingEigen<Device, T, 0>(d, in, out, broadcast_array);
            break;
        case 1:
            internal::TileUsingEigen<Device, T, 1>(d, in, out, broadcast_array);
            break;
...
    }
}
```
This uses template specialization as you mentioned.

**Comment by girving** [comment]
The `TileSimple` stub *is* the right idea; didn't mean to imply that wasn't.  So that looks good, except that I assume you don't mean to templatize your new `operator()` over `NDIM`?  I'm happy to comment further, but I'd much prefer to be looking at a pull request with diffs.

I'm not sure how many fully specialized versions you should have, by the way.  I think there is a fairly common case which uses 8 dimensions.  It's worth profiling your new `TileSimple` once you have it to see what the slowdown is; it may or may not be significant.

Thank you for taking this on!  One more annoying blemish gone. :)

**Comment by yanchen036** [comment]
Hi @girving I've finished the Tile Op. However, I'm confused with the TileGrad Op. What dose TileGrad do? I haven't found any docs about TileGrad Op in the website.

**Comment by girving** [comment]
@yanchen036 No need to touch `TileGrad`.  It's a legacy op that someone wrote without noticing that it's just `tf.reduce_sum`.  Should be unused unless you have a `GraphDef` generated by a very old version of TensorFlow.

**Comment by yanchen036** [comment]
@girving pls review this [](https://github.com/tensorflow/tensorflow/pull/10793)

**Comment by wt-huang** [comment]
Closing as it is resolved
