### ISSUE TITLE
DNNClassifier init failed TypeError

### ISSUE THREAD

**Issue by jrasero** [tensorflow/tensorflow#8876]
Following the tutorial, when I define the classifier:

classifier = skflow.DNNClassifier(hidden_units=[10, 20, 10], n_classes=3)

it triggers the following error:

init() takes at least 3 arguments (3 given)

**Comment by ianchee** [comment]
Isn't **feature_columns** a required argument?

**Comment by jrasero** [comment]
Yes!! That was that, very simple. It turns out that in new versions this is a required argument, whereas in earlier versions from which I was following a tutorial, it was not. Thanks a lot!

**Comment by shubham06vijay** [comment]
So, what exactly is the feature_column attribute?
