### ISSUE TITLE
8-bit quantized atrous conv2d op not supported

### ISSUE THREAD

**Issue by agupta74** [tensorflow/tensorflow#8884]
It looks like that 8-bit quantized atrous conv2d op is not supported. As per the latest API,  there are only 4 quantized ops supported namely quantized_conv2d, quantized_relu_x, quantized_max_pool and quantized_avg_pool.  Any target date by which 8-bit atrous conv2d op will be available?

**Comment by aselle** [comment]
@keveman, are there any plans for this feature in the short term. If not, please mark it contributions welcome.

**Comment by tilakrayal** [comment]
@agupta74,
Could you please take a look at this doc [link](https://www.tensorflow.org/lite/performance/quantization_spec) which delivers the information and let us know if it helps. Thank you!
