### ISSUE TITLE
tensorboard shows nothing 

### ISSUE THREAD

**Issue by lk1983823** [tensorflow/tensorflow#8890]
I am using tensorflow 1.0.1and python 3.4
When I run my code, it shows no error. However tensorboard show that "No graph definition files were found. "

My tensorboard debug is as follows:

INFO:tensorflow:TensorBoard is in debug mode.
INFO:tensorflow:Starting TensorBoard in directory /home/swx/lk
**INFO:tensorflow:TensorBoard path_to_run is: {'/home/swx/lk/=': None}**
INFO:tensorflow:Event Multiplexer initializing.
INFO:tensorflow:Event Multiplexer done initializing
INFO:tensorflow:TensorBoard reload process beginning
INFO:tensorflow:Starting AddRunsFromDirectory: /home/swx/lk/=
INFO:tensorflow:Done with AddRunsFromDirectory: /home/swx/lk/=
INFO:tensorflow:TensorBoard reload process: Reload the whole Multiplexer
**INFO:tensorflow:Beginning EventMultiplexer.Reload()
INFO:tensorflow:Finished with EventMultiplexer.Reload()**
INFO:tensorflow:TensorBoard done reloading. Load took 0.002 secs
INFO:tensorflow:TensorBoard is tag: b'41'

can any one offer some help?

NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

On the other hand make sure you have written summaries (you didn't include your reproducible code). See the tensorboard documentation https://www.tensorflow.org/get_started/summaries_and_tensorboard
