### ISSUE TITLE
image_retraining/retrain.py not found

### ISSUE THREAD

**Issue by Srigowri** [tensorflow/tensorflow#8895]
### Environment info
Operating System: Windows 10

Installed version of CUDA and cuDNN: 

- cuda_8.0.61_win10.exe
- cudnn-8.0-windows10-x64-v5.1
I have installed tensorflow for gpu using pip install tensorflow-gpu( also downloaded the nightly for vanishing certain warnings)
- tensorflow_gpu-1.1.0rc0-cp35-cp35m-win_amd64.whl

## What am I trying to do?
I want to use the tensorflow for poets for transfer learning on my images **## ### WITHOUT USING DOCKER**
## What my problem is?
The tensorflow directory in the site-packages does not have the image_retraining folder at all.
But the **tensorflow-master-cpu on github** has examples/image_retraining. It has many other files and directories.
 
### My question is..
Can I copy and paste the tensorflow/examples/image_retraining or the tensorflow subfolder to my tensorflow folder in site-packages?
or
Do I install tensorflow for cpu ? Will the retraining work?
I don't want to use docker. Please help me @Carmezim

**Comment by Carmezim** [comment]
Hi @Srigowri, if you want to run the code without Docker you can just install TensorFlow locally on your machine. 
Regarding CPU or GPU both would work for the purpose of running the code, it will depend if you have a compatible GPU and CUDA and cuDNN installed.  All the details on how to use TensorFlow with GPU support are on https://www.tensorflow.org/install/install_windows.

To use the code with your images one way is to set the default folder path to where your images are stored [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py#L903). The other way, which is recommended is to use `--image_dir` as instructed [in the codelab](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#6).

You will need Bazel for Windows to build the retrainer so just copying the folder won't work. You can download Bazel [here](https://github.com/bazelbuild/bazel/releases). Make sure to properly add the Bazel binary directory to your `%PATH%`. To set where the graph will be created use `output_graph` and `output_labels`.

Let's sum it up:
1. Install TensorFlow locally
2. Install Bazel and add its directory to `%PATH%`
3. Retrieve the model files
4. [Build it with Bazel](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py#L42)
5.  Go through [this section](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#4) to learn how to classify new images with the retrainer. You can read the `# on Docker` parts as in your command prompt.
6. Then [here](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#6) to learn about training categories you want.

**Comment by MarkDaoust** [comment]
`retrain.py` only really depends on having tensorflow installed. So I think we can skip bazel entierly.

Just downloading it to your working directory should be enough:

    curl -O https://raw.githubusercontent.com/tensorflow/tensorflow/r1.1/tensorflow/examples/image_retraining/retrain.py

From there you can just run it like any other python script. For me, this works without any trouble:

    python retrain.py {add your args here}

Let me know if it doesn't work for you, but I think it should.

**Comment by Carmezim** [comment]
@MarkDaoust good to know bazel is not necessary, I assumed according to the [code documentation] (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/image_retraining/retrain.py#L38) it was.
