### ISSUE TITLE
"ImportError: No module named protobuf" on El Capitan with VirtualEnv

### ISSUE THREAD

**Issue by isec1971** [tensorflow/tensorflow#890]
Hello, 
When I try importing tensorflow in Python I get "ImportError: No module named protobuf".

I followed instructions from here https://www.tensorflow.org/versions/0.6.0/get_started/os_setup.html#virtualenv_install and also updated protobuf:

brew reinstall --devel protobuf

The version I have is 3.0.0a3

I looked at the issues here and all remedies don't seem to work. 

Any clue?

Thx

**Comment by vrv** [comment]
There is not nearly enough information for anybody to help.  If you add more information about your setup, what you've tried, etc., we might be able to offer help, and I'll reopen the issue.

**Comment by isec1971** [comment]
I apologize, I am new to this and wasn't sure what level of details is needed.

Host: El Capitan 10.11.3

Repro steps:
$ sudo easy_install pip
$ sudo pip install --upgrade virtualenv
$ virtualenv --system-site-packages ~/tensorflow
$ source ~/tensorflow/bin/activate
(tensorflow)$ pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl

Then I tried to test

$ python
>>> import tensorflow as tf

I got this:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxx/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py", line 4, in <module>
    from tensorflow.python import *
  File "/Users/xxx/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 13, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/xxx/tensorflow/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named protobuf

then I quit python and executed this:

$ brew reinstall --devel protobuf

this command :
$ pip freeze

shows:
protobuf==3.0.0a3

I then try again with python, same commands as above, and get the exact same error as above. 

Please let me know if you need other kind of details. I will send them.

Thanks,
Pierre

**Comment by JACKHAHA363** [comment]
Exactly same question here.

**Comment by Grzego** [comment]
I had the same problem and those steps worked for me:
```
pip uninstall protobuf
pip install protobuf
pip install --upgrade protobuf==3.0.0a3
```

**Comment by FiniteElementries** [comment]
tried Grzego's approach. Got a new error though...

`   import tensorflow as tf
  File "/usr/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 69, in <module>
    from tensorflow.python.training import training as train
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/training.py", line 149, in <module>
    from tensorflow.python.training.saver import generate_checkpoint_state_proto
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 29, in <module>
    from google.protobuf.any_pb2 import Any
ImportError: No module named any_pb2`

**Comment by FiniteElementries** [comment]
ended up creating a new virtualenv and now it's working. noticed a new protobuf was installed 
'Successfully installed protobuf-3.0.0b2 tensorflow-0.7.1'

**Comment by markusdr** [comment]
I had the same problem on my Mac. Like @FiniteElementries, I ran into the error `No module named any_pb2`. Solution:

    pip uninstall protobuf
    pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp27-none-any.whl

After that, tensorflow works fine for me.

**Comment by mznyc** [comment]
Try this. Will likely solve the problem 
sudo pip install --upgrade protobuf==3.0.0b2

**Comment by cerisara** [comment]
I ran into the same problems, which are likely due to conflict with old versions.
Got it run with:
sudo pip uninstall protobuf
sudo pip uninstall tensorflow
and then install again tensorflow as said in the TF install page.

**Comment by bingfeng1018** [comment]
as markusdr  said, it worked!  thanks!
pip uninstall protobuf
pip install /tmp/tensorflow_pkg/tensorflow*.whl

**Comment by stephanobryan** [comment]
On El Capitan 10.11.6 and within Virtualenv environment, I've got:
ImportError: No module named protobuf
So I did:
(tensorflow) $ sudo -H pip install protobuf
(tensorflow) $ sudo easy_install -U six
Then,
(tensorflow) $ python
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> print(sess.run(hello))
Hello, TensorFlow!
>>> a = tf.constant(10)
>>> b = tf.constant(32)
>>> print(sess.run(a + b))
42
So, it worked :)

**Comment by anna-liao** [comment]
May want to look at this issue: https://github.com/tensorflow/tensorflow/issues/1415
There are workarounds mentioned there.

**Comment by deatherving** [comment]
I got the same problem. 

It could be fixed by

sudo pip install --upgrade protobuf

and then protobuf-3.0.0 will be replaced by protobuf-3.1.0. Nailed it.

**Comment by robksawyer** [comment]
I keep getting the following even after using the protobuf upgrade mentioned above. Any ideas?

I'm on El Capitan 10.12.1 using Python 2.7.12

```
$ python
Python 2.7.12 (default, Oct 11 2016, 05:20:59) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/usr/local/lib/python2.7/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 22, in <module>
    serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\ntensorflow\"m\n\x0eResourceHandle\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tB4\n\x18org.tensorflow.frameworkB\x13ResourceHandleProtoP\x01\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
>>> 

```

**Comment by hoangcuong2011** [comment]
This is a very annoying problem. I fixed the problem by following @markusdr.
Note that the latest protobuf to date is 3.4.0, so I changed the command as this:

pip install --upgrade protobuf==3.4.0

Hope this helps!

**Comment by bmatichuk** [comment]
On Mac OS - Installing tensorflow 1.3 - it will automatically remove other protobuf installs and install protobuf 3.4. However, this does not work and neither does installing or downgrading to any other protobuf version.

However I found a solution.
Not sure why this works - but on Mac OS this solved it.

    pip install google

**Comment by crafet** [comment]
meet same problems.
pip uninstall tensorflow
pip install tensorflow
it works for me
