### ISSUE TITLE
SVD float64 NaN bug

### ISSUE THREAD

**Issue by Bihaqo** [tensorflow/tensorflow#8905]
I've encountered a tf.float64 matrix (of size 60 x 200) such that tf.svd of it returns NaNs, while
np.linalg.svd works fine.
Converting the matrix into tf.float32 and then converting back to tf.float64 makes everything works with TF too (while being a tiny perturbation).

Here is an example Jupyter notebook: https://nbviewer.jupyter.org/urls/dl.dropbox.com/s/mf9e2eqg2isupce/Scary%20matrix.ipynb?dl=0

You can download pickled matrix here: https://www.dropbox.com/s/b8wex6voladtgw1/scary_matrix.cPickle?dl=0

I'm using Conda Python 2.7.13 (tried on Mac and Ubuntu) and a fresh version of tensorflow from pip (tried both cpu and gpu versions).

**Comment by aselle** [comment]
Could you take a look @rmlarsen?

**Comment by shoyer** [comment]
Pickle can do arbitrary code execution when loaded, so it's a poor choice for sharing data. Can you save it with another file format instead, e.g., with `numpy.save`?

**Comment by Bihaqo** [comment]
Sure, I updated the notebook to load np array, here is the new file: https://www.dropbox.com/s/ou7egsfdmmwxhd6/scary_matrix.np?dl=0

**Comment by Bihaqo** [comment]
Update: I found a float32 20 x 150 matrix with the same behavior (NaNs in tf.svd, but works fine with np.linalg.svd). Here is the new matrix file: [.np file](https://www.dropbox.com/s/a326frisvq7hxxw/float32_scary_mat.np?dl=0#)

And here is the updated [Jupyter notebook](https://nbviewer.jupyter.org/urls/dl.dropbox.com/s/mf9e2eqg2isupce/Scary%20matrix.ipynb?dl=0) with both examples.

**Comment by aselle** [comment]
@rmlarsen, any update?

**Comment by yaroslavvb** [comment]
BTW, I'm seeing possibly related bug in https://github.com/tensorflow/tensorflow/issues/9234

The matrix in question is in https://storage.googleapis.com/tensorflow-community-wheels/svd_in and and can be opened as 
`matrix0 = np.genfromtxt('svd_in', delimiter= ",").astype(dtype)
`
It occasionally produces NaN's and segfaults at other times

**Comment by Bihaqo** [comment]
As a temporary workaround I replaced tf.svd with np.linalg.svd via tf.py_func module. It's really slow though.

```Python
def replace_tf_svd_with_np_svd():
  """Replaces tf.svd with np.svd. Slow, but a workaround for tf.svd bugs.
  For details see
  https://github.com/tensorflow/tensorflow/issues/8905
  """
  if hasattr(tf, 'original_svd'):
    # This function has been already called and tf.svd is already replaced.
    return
  tf.original_svd = tf.svd

  def my_svd(tensor, full_matrices=False, compute_uv=True):
    dtype = tensor.dtype
    u, s, v = tf.py_func(np.linalg.svd, [tensor, full_matrices, compute_uv],
                         [dtype, dtype, dtype])
    s_, u_, v_ = tf.original_svd(tensor, full_matrices, compute_uv)
    s = tf.reshape(s, s_.get_shape())
    u = tf.reshape(u, u_.get_shape())
    v = tf.reshape(v, v_.get_shape())
    # Converting numpy order of v dims to TF order.
    order = range(tensor.get_shape().ndims)
    order[-2], order[-1] = order[-1], order[-2]
    v = tf.transpose(v, order)
    return s, u, v

  tf.svd = my_svd
```

**Comment by yaroslavvb** [comment]
@Bihaqo  -- make sure you have scipy with MKL (it gets overwritten with non-MKL numpy every time you install tensorflow, so you have to do "conda install scipy/numpy"). That version will do SVD on multiple cores so its faster than TensorFlow

**Comment by yaroslavvb** [comment]
After some experimenting, it seems NaNs are connected with ill-conditioning. For instance, take first 100 MNIST examples, run SVD on covariance matrix -> NaN. If I take first 1000 MNIST examples instead, works fine.

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
