### ISSUE TITLE
how to join the tf.string SparseTensor to 1-D dense tensor

### ISSUE THREAD

**Issue by lanlingcloud** [tensorflow/tensorflow#8917]
tensorflow has tf.string_split function that can split dense tensor to SparseTensor, but not provided the opposite function.

anyone knows how to do it? thanks~

for example: SparseTensor:
```
[["a", "b", "c"]
 ["d", "e"]
 ["f", "g", "h", "i"]]
```

join SparseTensor with separator " " to dense tensor:
```
["a b c",
 "d e",
 "f g h i"]
```

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
