### ISSUE TITLE
problem with exemple in API documentation for tf.contrib.distributions.bijector.ScaleAndShift

### ISSUE THREAD

**Issue by chetzacoalt** [tensorflow/tensorflow#8920]
Hello

I am currently using tensorflow version 1.0.0 (from conda vanilla installation),
and I am running a snippet code fromAPI documentation :
https://www.tensorflow.org/api_docs/python/tf/contrib/distributions/TransformedDistribution?authuser=3

I get an AttributeError which seems an accurate error since I can't seem to find ScaleAndShift on the github repo for tensorflow r1.0 

    >>> ds.TransformedDistribution(
    ...   distribution=ds.Normal(mu=0., sigma=1.),
    ...   bijector=ds.bijector.ScaleAndShift(loc=mu, scale=sigma,   event_ndims=0),
    ...   name="NormalTransformedDistribution")
    Traceback (most recent call last):
      File "<stdin>", line 3, in <module>
    AttributeError: 'module' object has no attribute 'ScaleAndShift'

**Comment by asimshankar** [comment]
Thanks for the report.
That documentation needs to be updated.

IIUC, in 1.0.0 this would be replaced by [`ds.bijector.Affine`](https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/contrib/distributions/python/ops/bijector.py#L1463)

@jvdillon @ebrevdo : Something still seems fishy at head and in 1.1.0-rc1 where `tf.contrib.distributions.bijector` doesn't seem to exist. Mind taking a look?

**Comment by jvdillon** [comment]
Hi chetzacoalt, asimshankar. Thanks for bringing this to our attention and apologies for the trouble!

Yes it looks like the docstring was out of date.  What's worse is that it also looks like we still messed up the bijector importing.  I've created and verified a fix; it should make head within 1 to 2 days.

**Comment by asimshankar** [comment]
@jvdillon : Assigned to you - just to remind you to close it out when ready. Thanks!

**Comment by chetzacoalt** [comment]
thanks a lot, that will be quite helpful !

**Comment by wolffg** [comment]
This appears to be fixed in head.  @jvdillon , can you ask for a cherrypick on this change into the r1.0 and r1.1 branch?

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
