### ISSUE TITLE
Android tiny-yolo model

### ISSUE THREAD

**Issue by ramarajan09** [tensorflow/tensorflow#8922]
I was successfully able to run tiny-yolo-voc.pb on android. However, when I tried to run tiny-yolo.pb (which is for coco dataset) generated from https://github.com/thtrieu/darkflow , the app crashes with java.nio.BufferOverflowException.

Could you please point out what needs to be changed in the code to be able to run tiny-yolo. 

Thanks

**Comment by asimshankar** [comment]
This question is probably better posed on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) as the Github issues are meant to be focused on bugs and feature requests.

That said, some quick comments:

- It's hard to suggest the changes without more information (for example, which of the various versions in https://github.com/thtrieu/darkflow/tree/master/cfg is being used). If you post on stackoverflow, you should include this information.
- Model-specific configuration might need to be changed. For example, see the constants in [`DetectorActivity.java`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/DetectorActivity.java#L71) and [`TensorFlowYoloDetector.java`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowYoloDetector.java#L41), which will have to be consistent with the configuration of the model you're using.

Hope that helps. Closing this issue out as it doesn't seem to be a bug and more support is best asked for on Stackoverflow.

(FYI @andrewharp)

**Comment by chenweiqian** [comment]
@ramarajan09 hi, could you tell me how to run yolo model ?thanks！！

**Comment by offbye** [comment]
Use  darknet and darkflow generate   pb file, and put it into assets , change the  YOLO_MODEL_FILE DetectorMode MODE = DetectorMode.YOLO; in DetectorActivity

flow --model cfg/yolo.cfg --load bin/yolo.weights --savepb
