### ISSUE TITLE
Hiding the re2 symbols from libtensorflow.so

### ISSUE THREAD

**Issue by LaurentMazare** [tensorflow/tensorflow#8923]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

This recent issue [8320](https://github.com/tensorflow/tensorflow/issues/8320) is related but asked for the opposite (more symbol visibility rather than less symbol visibility).

### Environment info
Operating System: Linux

Installed version of CUDA and cuDNN: n/a

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
Running the following command line on the [pre-built linux binaries](https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.0.0.tar.gz) returns quite a few symbols.
 objdump -T libtensorflow.so  | grep re2

It looks like libtensorflow.so is using re2 internally and exposing its symbols. This is annoying when linking with some existing code that uses a different version of re2 as it could easily result in the wrong symbol being called depending on the order of the linker flags. In my case, the re2 calls made by my code ended up using the tensorflow exposed symbols and failing because the version was different.

Maybe the visibility of the re2 symbols embedded in libtensorflow.so could be set to hidden ? (I don't know much about symbol visibility but happy to help if you think it makes sense)

**Comment by asimshankar** [comment]
Sorry about that, yes `libtensorflow.so` should export much fewer symbols than it does today.

Will take a look.

**Comment by LaurentMazare** [comment]
Thanks for the quick fix @asimshankar and @rohan100jain , linking with the latest nightly build worked like a charm.
