### ISSUE TITLE
RuntimeError when executing models/tutorials/image/cifar10/cifar10_train.py

### ISSUE THREAD

**Issue by Evan-Gao** [tensorflow/tensorflow#8925]
### Environment info
Operating System:
Ubuntu Server 16.04LTS

Installed version of CUDA and cuDNN: 
CUDA 8.0 cuDNN 5.1
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
ls -l /usr/local/cuda/lib64/libcud*
-rw-r--r-- 1 root root   560184 Mar  7 09:54 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Mar  7 09:54 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Mar  7 09:54 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.27
-rwxr-xr-x 1 root root   394472 Mar  7 09:54 /usr/local/cuda/lib64/libcudart.so.8.0.27
-rw-r--r-- 1 root root   737516 Mar  7 09:54 /usr/local/cuda/lib64/libcudart_static.a
-rwxr-xr-x 1 root root 84163560 Mar  9 03:26 /usr/local/cuda/lib64/libcudnn.so
-rwxr-xr-x 1 root root 84163560 Mar  9 03:26 /usr/local/cuda/lib64/libcudnn.so.5
-rwxr-xr-x 1 root root 84163560 Mar  9 03:26 /usr/local/cuda/lib64/libcudnn.so.5.1.10
-rw-r--r-- 1 root root 70364814 Mar  9 03:26 /usr/local/cuda/lib64/libcudnn_static.a

If installed from binary pip package, provide:

1. A link to the pip package you installed:
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.1-cp27-none-linux_x86_64.whl
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
1.0.1

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
I followed this [tutorial](https://www.tensorflow.org/tutorials/deep_cnn#launching_and_training_the_model) to launch the model:
```
python cifar10_train.py
```

### Logs or other output that would be helpful
```
Traceback (most recent call last):
  File "cifar10_train.py", line 124, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "cifar10_train.py", line 120, in main
    train()
  File "cifar10_train.py", line 110, in train
    log_device_placement=FLAGS.log_device_placement)) as mon_sess:
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 315, in MonitoredTrainingSession
    return MonitoredSession(session_creator=session_creator, hooks=all_hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 601, in __init__
    session_creator, hooks, should_recover=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 434, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 767, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 772, in _create_session
    return self._sess_creator.create_session()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 494, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 375, in create_session
    init_fn=self._scaffold.init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 272, in prepare_session
    msg))
RuntimeError: Init operations did not make model ready for local_init.  Init op: group_deps, init fn: None, error: Variables not initialized: global_step, conv1/weights, conv1/biases, conv2/weights, conv2/biases, local3/weights, local3/biases, local4/weights, local4/biases, softmax_linear/weights, softmax_linear/biases, conv1/weight_loss/avg, conv2/weight_loss/avg, local3/weight_loss/avg, local4/weight_loss/avg, softmax_linear/weight_loss/avg, cross_entropy/avg, total_loss/avg, conv1/weights/ExponentialMovingAverage, conv1/biases/ExponentialMovingAverage, conv2/weights/ExponentialMovingAverage, conv2/biases/ExponentialMovingAverage, local3/weights/ExponentialMovingAverage, local3/biases/ExponentialMovingAverage, local4/weights/ExponentialMovingAverage, local4/biases/ExponentialMovingAverage, softmax_linear/weights/ExponentialMovingAverage, softmax_linear/biases/ExponentialMovingAverage
```

**Comment by ksharsha** [comment]
It looks like variables have not been initialized. Try adding this line right after you start the session
sess.run(tf.global_variables_initializer())

**Comment by asimshankar** [comment]
@Evan-Gao : Is it possible that you're not using the latest versions of the tutorial files (from https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10)? Or perhaps there are some stale files in `/tmp/cifar10_train` (the [default directory](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_train.py#L48) where the tutorial places it files).

I was unable to reproduce the error with release 1.0.1 and the latest contents of those files.
Could you try with a fresh snapshot (and after `rm -rf /tmp/cifar10_train`)?

**Comment by Evan-Gao** [comment]
@asimshankar I pull the latest version and everything is fine now. thx
