### ISSUE TITLE
Prediction based on day / time with tensorFlow

### ISSUE THREAD

**Issue by RebliNk17** [tensorflow/tensorflow#8933]
I did some digging but I couldn't find anything (maybe i just didn't know what do search exactly),
I'm in my final year of study and I am starting my final year project in Software engineering,
My plain is to (lets take smart house as an example) create a machine that will learn the householders habits and then do that action based on what they did (e.g: at Sunday, 7 AM turn on the boiler for 30 minutes because only one resident need to take a shower).

Can TensorFlow learn and act like that?

Please help.

Thanks.

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by RebliNk17** [comment]
Ok, thanks, I did that.
