### ISSUE TITLE
Has complex MVN been implemented?

### ISSUE THREAD

**Issue by DanqingZ** [tensorflow/tensorflow#8937]
I have below error for my code , where muC and SigmaC are complex vector and matrix
```
dist = tf.contrib.distributions.MultivariateNormalFull(muC, SigmaC)
```
```
TypeError: Value passed to parameter 'input' has DataType complex64 not in list of allowed values: float64, float32
```

**Comment by DanqingZ** [comment]
I tried to implemented the pdf of MVN by myself, but it looks like tf.matrix_inverse also don't support complex tensor.

**Comment by 4d55397500** [comment]
What's more generally the intended scope of support for complex operations in tensorflow?

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
