### ISSUE TITLE
Log Selected Convolution Algorithm

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#8941]
Reposting from https://github.com/tensorflow/tensorflow/issues/8928#issuecomment-291330814:

>It might make sense for the selected algorithm to be logged either to the logging system or maybe in the RunMetadata protocol buffer. 

/CC @asimshankar

**Comment by asimshankar** [comment]
FYI @zheng-xq

**Comment by ppwwyyxx** [comment]
It is logged with TF_CPP_MIN_VLOG_LEVEL=1. (code)[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/conv_ops_gpu.h#L221)

**Comment by cancan101** [comment]
In that case I will close.
