### ISSUE TITLE
Using output of `tf.argmax` as index raises TypeError

### ISSUE THREAD

**Issue by priyathamkat** [tensorflow/tensorflow#8951]
### Minimal example
```
a = tf.constant([1, 2, 3], dtype=tf.float32)
b = tf.argmax(a)
tf.Session().run(a[b])
```
This raises a `TypeError`
```
TypeError: Input 'strides' of 'StridedSlice' Op has type int32 that does not match type int64 of argument 'begin'.
```
The solution is to `tf.cast` `b` into a `tf.int32` before using it as an index. The output of `tf.argmax` should be usable as an index immediately. I feel that the current state is not consistent, is there some hidden reason for this?

**Comment by asimshankar** [comment]
Marking this as contributions welcome since it seems that @yongtang has a solution in review.
