### ISSUE TITLE
Tensorflow multi-GPU training and variable scope

### ISSUE THREAD

**Issue by jesryu** [tensorflow/tensorflow#8957]
### Context

I'm working on a detector model on multiple GPUs using Tensorflow 1.0. As suggested [here](https://github.com/tensorflow/models/blob/master/tutorials/image/cifar10/cifar10_multi_gpu_train.py), Gradients are computed on multiple GPUs individually and are averaged on CPU. To share the trainable variables (e.g. weights and biases) across the GPU towers, the `reuse` flag is turned on using `tf.get_variable_scope().reuse_variables()`, as in the cifar10 example. The difference is that I am using an `AdamOptimizer` instead of `GradientDescentOptimizer`.

### Problem

When I run the training job, it prints out a long stacktrace and raise the following error at `opt.apply_gradients()`:

```
ValueError: Variable conv1_1/kernel/Adam/ does not exist, or was not created with tf.get_variable(). Did you mean to set reuse=None in VarScope?
```

Looking into the source code I found that the `AdamOptimizer` is creating a number of zero-initialized slots within the `_create_slots()` method, wherein it calls the `_zeros_slot()`. This calls a separate module called the [`slot_creator`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/slot_creator.py#L62) (source code linked).

**In `line 62` of the `slot_creator`, it uses `variable_scope.get_variable()`. This used to be `tf.Variable()` in 0.12.**

My understanding of variable scopes is that `variable_scope.get_variable()` would fail to create a variable **if `reuse` flag is on`. See [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/variable_scope.py#L669) for source code.**

But the cifar10 example by Tensorflow creators seems to suggest enabling reuse to share variables across the GPU towers using `tf.get_variable_scope().reuse_variables()`. This happens **before** we average and apply the gradients. It looks like Tensorflow 1.0 refuses to create variables for the `AdamOptimizer`.

This happens for all optimizers that directly or indirectly call the `slot_creator` module.

### Question
As a quick fix, I added a custom function into the `VariableScope` class to disable the `_reuse` flag right before calling `opt.apply_gradients`. However, I am sure there is a merit to forcing the `reuse` flag to be only set to `True`. I am not sure what the better workaround would be. Any suggestions?

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

I created question [here](http://stackoverflow.com/questions/43212725/tensorflow-multi-gpu-training-and-variable-scope)

### Environment info
Operating System: Ubuntu 14.04 LTS

Installed version of CUDA and cuDNN: 8.0 and 5.1 respectively
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

The commit hash (`git rev-parse HEAD`): 1cb96893a64f59b7265f9def9968f7bed1e57662#diff-a25cc0fc9d475568e0069e5dc0b67d85 (see `slot_creator`)

**Comment by asimshankar** [comment]
@lukaszkaiser @martinwicke : Is `tf.get_variable_scope().reuse_variables()` the recommended way to share variables in 1.0+? And is there a way to disable reuse so that variables created by the `AdamOptimizer` can be created after all the towers?

**Comment by lukaszkaiser** [comment]
The way to share I'd recommend is to always open a scope and specify reuse parameter.
It should work fine with everything, there is no need to un-reuse at all.

```
with tf.variable_scope("my_model"):
   outputs = tf.layers....(inputs)
# some other code
with tf.variable_scope("my_model", reuse=True):
     outputs = tf.layers....(inputs)
```

**Comment by lukaszkaiser** [comment]
In a multi-gpu loop you can say:

```
for gpu in xrange(num_gpus):
  with tf.variable_scope("my_model", reuse=(gpu > 0)):
    outputs = tf.layers....(inputs)
```

**Comment by lucasgreene** [comment]
Hey I know this is closed but I came to the same conclusions as above and found explicitly creating a variable_scope with reuse=False/True around a tower fixed the issue. Would be great if this was in the official documentation or in the cifar example as its currently misleading.

**Comment by joe-antognini** [comment]
If I understand correctly, @xiao-dong, this issue comes up when you try to replicate your model across multiple GPUs.  Suppose you create a model on CPU with `net = tf.layers.dense(net, units=128)`.  Behind the scenes `tf.layers` is going to use `get_variable` to create a variable which may be called, say, `dense/kernel`.

Now if you try to do this on multiple GPUs you need to put the same variables on all the GPUs.  The naive way to do this might be to use a loop that looks like this:

```
for i in range(num_gpus):
  with tf.device('/gpu:{}'.format(i)):
    tf.layers.dense(net, units=128)
```

But this is going to fail, because on the second iteration of the loop, `get_variable` is going to try to reuse the same `dense/kernel` variable as before, but won't be able to because it's not shared.  If you were to simply wrap this with

```
for i in range(num_gpus):
  with tf.variable_scope('my_scope', reuse=True), tf.device('/gpu:{}'.format(i)):
    tf.layers.dense(net, units=128)
```

this also will not work because `get_variable` will try to reuse a variable that does not exist on the first iteration of the loop.  @lukaszkaiser's solution is to not reuse the variable on the first iteration of the loop, but then reuse it on all others:

```
for i in range(num_gpus):
  with tf.variable_scope('my_scope', reuse=(i > 0)), tf.device('/gpu:{}'.format(i)):
    tf.layers.dense(net, units=128)
```

**Comment by studynon** [comment]
@joe-antognini Thank you
