### ISSUE TITLE
Missing --recurse-submodules flag in ci_build instructions

### ISSUE THREAD

**Issue by caisq** [tensorflow/tensorflow#896]
In the file https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build/README.md, the git clone command is missing the --recurse-submodules option flag, which will cause Bazel builds to fail on users' machines.

**Comment by vrv** [comment]
Want to send us a PR?

**Comment by caisq** [comment]
Please see pull request: https://github.com/tensorflow/tensorflow/pull/934

**Comment by caisq** [comment]
Please see PR: https://github.com/tensorflow/tensorflow/pull/934
