### ISSUE TITLE
Can't Link Shared Libraries Located in /usr/local/include Folder

### ISSUE THREAD

**Issue by RoboEvangelist** [tensorflow/tensorflow#8966]
Folks,
I can't add any libraries in the /usr/local/include (or /lib) to the BUILD file. Bazel complains it cannot find the headers, nor the *.so files.
Are you planning on adding support for that?

Thanks,

**Comment by gunan** [comment]
This would be a bazel question, not a TF one.
Please file an issue, or reach out to bazel user forums on how to include libraries in your local folders in your BUILD files.

**Comment by RoboEvangelist** [comment]
Aight.
I'll ask at Bazel's (yet, my program is a tensorflow program, though)
Thanks.
