### ISSUE TITLE
Illegal instruction when importing tensorflow

### ISSUE THREAD

**Issue by fvisin** [tensorflow/tensorflow#8976]
After compiling tensorflow from source I get an "illegal instruction" error. 
I traced it back to this error with gdb:

> Thread 1 "python" received signal SIGILL, Illegal instruction.
> 0x00007fffdc684d16 in google::protobuf::SimpleDescriptorDatabase::DescriptorIndex<std::pair<void const*, int> >::AddFile(google::protobuf::FileDescriptorProto const&, std::pair<void const*, int>) ()
>   from /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so

I can successfully install and import the latest nightly build (and I have been able to compile and import tensorflow from source in the past on the same machine). I tried uninstalling all the dependencies and let pip install them again when I install the tensorflow wheel to no avail. I also tried to install the protobuf 3.1 wheel as suggested in the documentation, as well as the latest 3.2 wheel.
Any suggestion is welcome.

Here the details of my system:

Operating System: Linux Ubuntu 16.04
CUDA and CuDNN version
> ls -l /usr/local/cuda/lib64/libcud*
> -rw-r--r-- 1 root root   556000 Jan 27 00:48 /usr/local/cuda/lib64/libcudadevrt.a
> lrwxrwxrwx 1 root root       16 Jan 27 00:51 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
> lrwxrwxrwx 1 root root       19 Jan 27 00:51 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.61
> -rw-r--r-- 1 root root   415432 Jan 27 00:48 /usr/local/cuda/lib64/libcudart.so.8.0.61
> -rw-r--r-- 1 root root   775162 Jan 27 00:48 /usr/local/cuda/lib64/libcudart_static.a
> lrwxrwxrwx 1 root root       13 Sep 24  2016 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
> lrwxrwxrwx 1 root root       17 Sep 24  2016 /usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.1.5
> -rwxr-xr-x 1 root root 79337624 Sep 24  2016 /usr/local/cuda/lib64/libcudnn.so.5.1.5
> -rw-r--r-- 1 root root 69756172 Sep 24  2016 /usr/local/cuda/lib64/libcudnn_static.a

Tensorflow commit: a9b7946540a27cc53bbdc9db1564196979fe30ae
Bazel version
> Build label: 0.4.5
> Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
> Build time: Thu Mar 16 12:19:38 2017 (1489666778)
> Build timestamp: 1489666778
> Build timestamp as int: 1489666778

**Comment by asimshankar** [comment]
If you are still able to install and use the nightly installs, then it would suggest some funky interaction with your system setup and the build. Perhaps you can isolate to a clean environment in a docker container (you could even use the same docker images that are used for the nightly builds (using [`tensorflow/tools/ci_build/builds/pip.sh gpu --test_tag_filters=local,-benchmark-test --distinct_host_configuration=false --config=cuda -c opt`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/builds/pip.sh)

**Comment by fvisin** [comment]
It indeed seems to be a problem with my environment. Thank you for your answer, I will investigate further.

**Comment by CapCap** [comment]
@fvisin Did you ever determine the cause of this? I'm experiencing the same problem.

**Comment by fvisin** [comment]
In the end it was my fault: I had a set of extra flags that I mistakenly thought were right for my architecture. I was able to compile with the default settings, so I figured out the error was in my optimization flags.

**Comment by CapCap** [comment]
Ended up figuring it out last night, after installing the pre-built cuda package worked. It was the same problem for me; I had the flag for SSE enabled on a machine that didn't support it.

**Comment by leonard7e** [comment]
after Upgrading to TensorFlow 1.6, I have this issue too. Programs which worked before stopped with
"fish: 'python3 <scriptname.py>' terminated by signal SIGILL (Illegale Instruktion)"
test.py has just a single line, in which it imports tensorflow library.

**Comment by hware** [comment]
@leonard7e  Is it an older machine?  Perhaps the newer Tensorflow is compiled with more of the (newish) cpu SSE/parallelization flags.

**Comment by leonard7e** [comment]
Hi hware.

My computer supports up to sse4_2. 

$> cat /proc/cpuinfo
gives ...
...
model name	: Intel(R) Celeron(R) CPU G3900TE @ 2.30GHz
...
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti retpoline intel_pt rsb_ctxsw tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust erms invpcid rdseed smap clflushopt xsaveopt xsavec xgetbv1 xsaves dtherm arat pln pts hwp hwp_notify hwp_act_window hwp_epp
