### ISSUE TITLE
log_device_placement not working in some cases

### ISSUE THREAD

**Issue by krisjobs** [tensorflow/tensorflow#8982]
Hey guys, thank you for working on TensorFlow so hard!

I think I found a small bug, but it might be so that I just don't understand ConfigProto correctly.
So:

```
config = tf.ConfigProto(log_device_placement=True)
server = tf.train.Server.create_local_server()
with tf.Session(server.target, config=config):
```

outputs the device placement correctly, but

```
config = tf.ConfigProto(log_device_placement=True)
server = tf.train.Server.create_local_server(config=config)
with tf.Session(server.target):
```

doesn't (at all).

While this is not groundbreaking, just wanted to let you know.

Cheers, Kris

**Comment by asimshankar** [comment]
That indeed seems to be at least a discrepancy between the documentation of `tf.train.Server` and the behavior.

@suharshs : Mind taking a look? It seems that `tf.Session(target)` in Python ends up sending a `CreateSession` RPC with `CreateSessionRequest.config` based on the options provided the `tf.Session` constructor. This means that the default provided to `tf.train.Server` was ignored. Which might be okay? But perhaps something needs to be cleaned up (either we don't have a "default" for the server, or we use it?)

FYI @mrry

**Comment by suharshs** [comment]
The docs for tf.train.Server say:
```
config: (Options.) A `tf.ConfigProto` that specifies default
        configuration options for all sessions that run on this server.
```
This doesn't seem to match the code in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc
It looks like the ServerDef (which has the session_opts) passed in isn't even passed to the MasterSession, unless I am missing something.
We need to somehow merge the session_opts in ServerDef with the ones passed to MasterSession before creating it. I'll look into this.
Thanks @krisjobs !
