### ISSUE TITLE
Inception v1, v2 - ValueError: Can not squeeze dim[1], expected a dimension of 1, got 2 for 'InceptionV2/Logits/SpatialSqueeze' (op: 'Squeeze') with input shapes: [1,2,2,1000].

### ISSUE THREAD

**Issue by Exuro889** [tensorflow/tensorflow#8986]
Hello,

I'm trying to run a few different inception models with their checkpoints from the pretrained models table [here](https://github.com/tensorflow/models/tree/master/slim). I've managed to get v3, v4, and resnet v2 working. v1 and v2 however I'm getting the issue above. I'm using the latest tensorflow and pulled the latest off the repo. Below is the code I use to load the model.

```
checkpoint_file = os.getcwd() + '\inception_v2.ckpt'
#Load the model
sess = tf.Session()
arg_scope = inception_v2_arg_scope()

with slim.arg_scope(arg_scope):
      logits, end_points = inception_v2(scaled_input_tensor, is_training=False)
saver = tf.train.Saver()
saver.restore(sess, checkpoint_file)
```

**Comment by asimshankar** [comment]
@Exuro889 : Please include all information asked for in the new issue template. Without that, it is hard to be able to help. For example, what do you mean by the "latest version of TensorFlow"? (Built from source? Or the latest release version?) What was the full code snippet you used (what is `inception_v2_arg_scope()` for example)?

Anyway, I think I was able to reduce this to the following with TensorFlow 1.0.1:

```sh
git clone git@github.com:tensorflow/models.git
cd ./models/slim
```

Then in Python

```python
import tensorflow as tf
from nets import inception_v2

scaled_input_tensor = tf.placeholder(tf.float32, shape=[1, 299, 299, 3])
logits, end_points = inception_v2.inception_v2(scaled_input_tensor, is_training=False)
```

yields the error:

```
ValueError: Can not squeeze dim[1], expected a dimension of 1, got 2 for 'InceptionV2/Logits/SpatialSqueeze' (op: 'Squeeze') with input shapes: [1,2,2,1000].
```

@sguada @nathansilberman : Mind taking a look?

**Comment by ralekar** [comment]
for Inception V1 the default shape is [224,224]

**Comment by sguada** [comment]
for Inception V1 and V2 the default shape [None, 224, 224, 3]

**Comment by asimshankar** [comment]
@sguada @ralekar : Thanks for pointing that out, but that isn't the problem. I've changed the snippet above and the problem still occurs

**Comment by asimshankar** [comment]
@Exuro889 : Seems like your `scaled_input_tensor` was of the wrong size.
