### ISSUE TITLE
"Split on underscores" is Missing in Tensorboard 1.1rc1

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#8993]
Old Tensorboard:
![image](https://cloud.githubusercontent.com/assets/51059/24721612/dff607b6-1a0e-11e7-9023-314a8e50661c.png)

New Tensorboard:
![image](https://cloud.githubusercontent.com/assets/51059/24721635/ed11cf0c-1a0e-11e7-969a-ad945d587eac.png)

Note that "Split on underscores" appears missing. I see no issues, etc related to the removal of this feature.

**Comment by asimshankar** [comment]
@dandelionmane @jart: Any comments on this?

**Comment by dandelionmane** [comment]
I removed it because I wanted to clean up the UI, and because there's nothing special about using underscores rather than slashes. The fix is it replace underscores with slashes in your summary names.

**Comment by cancan101** [comment]
What do you mean by slashes? Are they automatically split?

**Comment by cancan101** [comment]
So it looks like using `/`only works if the keys on the left does not already exist. 
For example this works (both on 1.1rc1):
![image](https://cloud.githubusercontent.com/assets/51059/24816749/f09f96e6-1ba7-11e7-9c1c-e36dd81bb0d0.png)

but this does not:
![image](https://cloud.githubusercontent.com/assets/51059/24816764/01af4b98-1ba8-11e7-8dad-eca20d0ffb5d.png)
