### ISSUE TITLE
Typo in getting started guide

### ISSUE THREAD

**Issue by maccam912** [tensorflow/tensorflow#9]
http://tensorflow.org/get_started/basic_usage.md#variables

In the code example, 1 is being added to "counter", which is named "var" initially, but referred to as "state" later. My guess is that these are meant to refer to the same thing, and a typo in one of the variable names made it into the example code.

**Comment by mdda** [comment]
Apparently the fix has already been put into their pipeline.

**Comment by vrv** [comment]
I just pushed the fix in https://github.com/tensorflow/tensorflow/commit/db0b5da485e1d1f23003ee08ed2e191451ee0319

Thanks!
