### ISSUE TITLE
Unable to compile TF, CUBLAS_GEMM_ALGO? not declared in scope

### ISSUE THREAD

**Issue by rohitgirdhar** [tensorflow/tensorflow#9002]
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*: no
- *TensorFlow installed from (source or binary)?*: source
- *TensorFlow version*: 1.1.0rc1 (master as of April 5, 2017)
- *Bazel version (if compiling from source)*: 0.4.5
- *CUDA/cuDNN version*: 8/5.1
- *GPU Model and Memory*: Titan X (PASCAL) 12GB
- *Exact command to reproduce*: `bazel build -c opt --copt=-mavx --copt=-mfma --copt=-mfpmath=both --config=cuda -k //tensorflow/tools/pip_package:build_pip_package`

Here's the compile config:

```txt
$ ./configure 
Please specify the location of python. [Default is /path/to/anaconda2/bin/python]: 
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? [Y/n] n
jemalloc disabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
/path/to/python/site-packages
Please input the desired Python library path to use.  Default is [/path/to/python/site-packages]
/path/to/python/site-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Do you want to use clang as CUDA compiler? [y/N] 
nvcc will be used as CUDA compiler
Please specify which gcc should be used by nvcc as the host compiler. [Default is /opt/gcc/4.9.2/bin/gcc]: 
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 
Please specify the location where CUDA  toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /opt/cuda-8.0
Please specify the cuDNN version you want to use. [Leave empty to use system default]: 
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /opt/cuda-8.0]: /opt/cudnn-8.0
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 3.5,5.2,6.1
Warning: ignoring LD_PRELOAD in environment.
............
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Configuration finished

```

### Describe the problem clearly
CentOS 6.6, compiling using instructions from https://github.com/tensorflow/tensorflow/issues/110#issuecomment-274586644 gives an error as mentioned later.
I have been able to compile TF upto 1.0.1 successfully on the same machine.
Also, same issue was mentioned in https://github.com/tensorflow/tensorflow/issues/8790#issuecomment-290094265, but I'm not sure if the OP opened an issue 

### Source Code / Logs

```txt
ERROR: /path/to/tensorflow/stream_executor/BUILD:39:1: Couldn't build file tensorflow/stream_executor/_objs/cuda_platform/tensorflow/stream_executor/cuda/cuda_blas.pic.o: C++ compila
tion of rule '//tensorflow/stream_executor:cuda_platform' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D
_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 118 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
tensorflow/stream_executor/cuda/cuda_blas.cc: In member function 'virtual bool perftools::gputools::cuda::CUDABlas::GetBlasGemmAlgorithms(std::vector<long long int>*)':
tensorflow/stream_executor/cuda/cuda_blas.cc:1916:9: error: 'CUBLAS_GEMM_ALGO5' was not declared in this scope
         CUBLAS_GEMM_ALGO5, CUBLAS_GEMM_ALGO6, CUBLAS_GEMM_ALGO7}) {
         ^
tensorflow/stream_executor/cuda/cuda_blas.cc:1916:28: error: 'CUBLAS_GEMM_ALGO6' was not declared in this scope
         CUBLAS_GEMM_ALGO5, CUBLAS_GEMM_ALGO6, CUBLAS_GEMM_ALGO7}) {
                            ^
tensorflow/stream_executor/cuda/cuda_blas.cc:1916:47: error: 'CUBLAS_GEMM_ALGO7' was not declared in this scope
         CUBLAS_GEMM_ALGO5, CUBLAS_GEMM_ALGO6, CUBLAS_GEMM_ALGO7}) {
                                               ^
tensorflow/stream_executor/cuda/cuda_blas.cc:1916:64: error: unable to deduce 'std::initializer_list<_Tp>&&' from '{CUBLAS_GEMM_DFALT, CUBLAS_GEMM_ALGO0, CUBLAS_GEMM_ALGO1, CUBLAS_GEMM_ALGO2, CUBLAS_GEMM_ALGO3, CUBLAS_GEMM_ALGO4, <express
ion error>, <expression error>, <expression error>}'
         CUBLAS_GEMM_ALGO5, CUBLAS_GEMM_ALGO6, CUBLAS_GEMM_ALGO7}) {
```

**Comment by asimshankar** [comment]
This might be a problem with your CUDA installation. All these constants should be defined (in your case) in `/opt/cuda-8.0/include/cublas_api.h` which is included by `tensorflow/stream_executor/cuda/cuda_blas.cc`.

If `grep CUBLAS_GEMM_ALGO5 /opt/cuda-8.0/include/cublas_api.h` does not work for you, then it would appear to be a problem with your CUDA library installation. Does it?

**Comment by AndreasMadsen** [comment]
Had a similar a problem, I think they where missing from the first CUDA 8.0 release and then included in 8.0.44+.

**Comment by rohitgirdhar** [comment]
Yeah, those constants are not defined. I'll try to get my CUDA updated and see if that fixes the problem.

**Comment by asimshankar** [comment]
Closing this out since the original problem seems to have been correctly diagnosed to missing symbols in your CUDA installation.

**Comment by rohitgirdhar** [comment]
Just to confirm: the issue was as pointed out above and upgrading to CUDA 8.0.61 fixed it. Thanks!

**Comment by yaroslavvb** [comment]
@rohitgirdhar I'm running into the same issue. Just to double-check, you fixed it by downgrading from CUDA 8.0.61  to 8.0.21?

**Comment by yaroslavvb** [comment]
OK, I got it working by upgrading to 8.0.61, looks like TF version 1.0.1 was the last version that supported 8.0.21

https://github.com/yaroslavvb/tensorflow-community-wheels/issues/21

**Comment by rohitgirdhar** [comment]
Yes, I upgraded to 8.0.61

**Comment by sounakdey** [comment]
i get the same error with 
Cuda compilation tools, release 8.0, V8.0.61
ERROR: /path/to//tensorflow/stream_executor/BUILD:39:1: C++ compilation of rule '//tensorflow/stream_executor:cuda_platform' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 121 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
tensorflow/stream_executor/cuda/cuda_blas.cc: In member function 'virtual bool perftools::gputools::cuda::CUDABlas::GetBlasGemmAlgorithms(std::vector<long long int>*)':
tensorflow/stream_executor/cuda/cuda_blas.cc:1916:9: error: 'CUBLAS_GEMM_ALGO5' was not declared in this scope
         CUBLAS_GEMM_ALGO5, CUBLAS_GEMM_ALGO6, CUBLAS_GEMM_ALGO7}) {
         ^
tensorflow/stream_executor/cuda/cuda_blas.cc:1916:28: error: 'CUBLAS_GEMM_ALGO6' was not declared in this scope
         CUBLAS_GEMM_ALGO5, CUBLAS_GEMM_ALGO6, CUBLAS_GEMM_ALGO7}) {
                            ^
tensorflow/stream_executor/cuda/cuda_blas.cc:1916:47: error: 'CUBLAS_GEMM_ALGO7' was not declared in this scope
         CUBLAS_GEMM_ALGO5, CUBLAS_GEMM_ALGO6, CUBLAS_GEMM_ALGO7}) {
                                               ^
tensorflow/stream_executor/cuda/cuda_blas.cc:1916:64: error: unable to deduce 'std::initializer_list<_Tp>&&' from '{CUBLAS_GEMM_DFALT, CUBLAS_GEMM_ALGO0, CUBLAS_GEMM_ALGO1, CUBLAS_GEMM_ALGO2, CUBLAS_GEMM_ALGO3, CUBLAS_GEMM_ALGO4, <expression error>, <expression error>, <expression error>}'
         CUBLAS_GEMM_ALGO5, CUBLAS_GEMM_ALGO6, CUBLAS_GEMM_ALGO7}) {

with tensorflow r1.1 could anyone help please

**Comment by sabersword** [comment]
Trying to install tensorflow-gpu 1.2 from source on Ubuntu-16.04.
bazel version: 0.5.3
Cuda compilation tools, release 8.0, V8.0.61
CUDNN_MAJOR  5  CUDNN_MINOR  1  CUDNN_PATCHLEVEL  5
gcc version: 4.9.3
Same error as  @sounakdey .
__Note:__ I have made one change to third_party/gpus/cuda_configure.bzl as mentioned in #11871 .
Any solutions?

**Comment by sounakdey** [comment]
@ameya sorry i did not find a solution. If you get one can you please post

**Comment by Goddard** [comment]
./configure 
You have bazel 0.5.3 installed.
Please specify the location of python. [Default is /usr/bin/python]: 
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Using python library path: /usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with MKL support? [y/N] 
No MKL support will be enabled for TensorFlow
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? [Y/n] 
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Do you wish to build TensorFlow with VERBS support? [y/N] 
No VERBS support will be enabled for TensorFlow
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Do you want to use clang as CUDA compiler? [y/N]
nvcc will be used as CUDA compiler
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to default to CUDA 8.0]: 8
Please specify the location where CUDA 8 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Invalid path to CUDA 8 toolkit. /usr/local/cuda/lib64/libcudart.so.8 cannot be found
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to default to CUDA 8.0]: 8
Please specify the location where CUDA 8 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Invalid path to CUDA 8 toolkit. /usr/local/cuda/lib64/libcudart.so.8 cannot be found
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to default to CUDA 8.0]: 8.0
Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]:
Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 6.0]: 7.0.1
Please specify the location where cuDNN 7.0.1 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: /usr/lib/x86_64-linux-gnu/
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "6.1"]:
Do you wish to build TensorFlow with MPI support? [y/N]
MPI support will not be enabled for TensorFlow
Configuration finished

BUILD:39:1: C++ compilation of rule '//tensorflow/stream_executor:cuda_platform' failed (Exit 1)

**Comment by XiangJ87** [comment]
Hi @rohitgirdhar @sounakdey , 

I got the same error, and there is a possible solution (I read it on a Chinese blog)... which I only test it on TX1:
Edit cublas_api.h ('/usr/local/cuda/targets/aarch64-linux/include/cublas_api.h' is the TX1 path) as follows

```
...
/*For different GEMM algorithm */
typedef enum{
 CUBLAS_GEMM_DFALT = -1,
 CUBLAS_GEMM_ALGO0 = 0,
 CUBLAS_GEMM_ALGO1 = 1,
 CUBLAS_GEMM_ALGO2 = 2,
 CUBLAS_GEMM_ALGO3 = 3,
 CUBLAS_GEMM_ALGO4 = 4,
 /* add this */ 
 CUBLAS_GEMM_ALGO5         =  5,
 CUBLAS_GEMM_ALGO6         =  6,
 CUBLAS_GEMM_ALGO7         =  7,
/* add this */
} cublasGemmAlgo_t;
...
```
On TX1, it works.
