### ISSUE TITLE
Instalation is broken

### ISSUE THREAD

**Issue by juanmol** [tensorflow/tensorflow#9008]
```
# pip install tensorflow
Collecting tensorflow
  Downloading tensorflow-1.0.1-cp27-cp27mu-manylinux1_x86_64.whl (44.1MB)
    99% |████████████████████████████████| 44.1MB 28.6MB/s eta 0:00:01Killed
```

Ubuntu Xenial. all times.

**Comment by asimshankar** [comment]
There is not enough information in this bug report to help diagnose your issue. Closing this out (it seems like there is some issue with your machine setup that `pip install` crashes before finishing the download).

Closing this out. If you have more information that suggests a bug in TensorFlow, feel free to reopen after adding all the details requested for in the new issue template.
