### ISSUE TITLE
I hope pre-1.1 `tf.contrib.seq2seq` is kept somewhere for legacy support

### ISSUE THREAD

**Issue by kaniblu** [tensorflow/tensorflow#9010]
I am disappointed by the fact that pre-1.1 `seq2seq` has been completely scraped in the latest build and has been replaced by some object-oriented redesign that seems half-finished right now. We have tonnes of codes that are based on pre-1.1 `seq2seq` interface, so this change would completely break our code base. But we can't just stick to old versions because there are some improvements in other areas that we desperately need also. Why not keep the original design somewhere for legacy (`tf.contrib.legacy_seq2seq` already exists, so need to think of another name), so those who heavily rely on the module do not have to re-implement the entire codebase? Since 1.1 is still far away from being officially released, I hope a right decision is made.

**Comment by asimshankar** [comment]
@ebrevdo : Any comments here? 

@kaniblu : 1.1.0 is in release candidate and should be available shortly (or you can try the release candidates). Does that work for you?

**Comment by ebrevdo** [comment]
There was an original tf.contrib.seq2seq which was moved to
tf.contrib.legacy_seq2seq; and there were some functions in the new
tf.contrib.seq2seq that were problematic and we decided not to continue
supporting them in favor of the new OO-based API.

**Comment by asimshankar** [comment]
(also a side note @kaniblu : APIs under `tf.contrib` are not guaranteed to be stable between releases, unlike other APIs - see [TensorFlow Version Semantics](https://www.tensorflow.org/programmers_guide/version_semantics) for details)
