### ISSUE TITLE
compilation from sources, is broken too

### ISSUE THREAD

**Issue by juanmol** [tensorflow/tensorflow#9011]
```
# bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
.
INFO: Found 1 target...
[224 / 2,346] Compiling external/pcre/pcre_byte_order.c [for host]

Server terminated abruptly (error code: 14, error message: '', log file: '/root/.cache/bazel/_bazel_root/cbe8b06b94787a6b39e59564d90f2497/server/jvm.out')

# cat /root/.cache/bazel/_bazel_root/cbe8b06b94787a6b39e59564d90f2497/server/jvm.out
#
```

Ubuntu Xenial, all times.

**Comment by asimshankar** [comment]
There is not enough information provided in this issue report (version of bazel being used, version of TF source code, platform details etc.) to help. It seems though that for some reason the bazel server is crashing. Is the log actually empty?

Closing this out. If you have more information that suggests a bug in TensorFlow, please feel free to reopen - though do add more information (ideally all that is asked for in the new issue template).
