### ISSUE TITLE
build tensorflow failed,may be the problem of compiler?

### ISSUE THREAD

**Issue by Keigochiro** [tensorflow/tensorflow#9015]
### You must complete this information or else your issue will be closed
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*:
- *TensorFlow installed from source *:
- *TensorFlow version*:1.0.1
- *Bazel version :0.4.5
- *CUDA/cuDNN version*:8.0/5.1
- *GPU Model and Memory*:GeForce 920M total memory 2048 MB
### Describe the problem clearly
hi ,I am attempting to build the tensorflow ,but it can't work ,it seems like relates to compiler of jit.
but why can't i see the TF_CUDA_VERSION='' and TF_CUDNN_VERSION='' ? I did install CUDA and CUDNN and I really add path in .bashrc .what's wrong with it? what can I do ?
### Source Code / Logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full-traceback. Large logs and files should be attached. Try to reproducible test-case code the bare-minimum necessary to generate the problem
`bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package --verbose_failures
WARNING: /home/EI/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /home/EI/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
ERROR: /home/EI/tensorflow/tensorflow/compiler/jit/BUILD:96:1: C++ compilation of rule '//tensorflow/compiler/jit:common' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/EI/.cache/bazel/_bazel_EI/2e0782785985dd9cb1b5d0cb62ad2606/execroot/tensorflow && \
  exec env - \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    CUDNN_INSTALL_PATH=/usr/local/cuda-8.0 \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    LD_LIBRARY_PATH='/usr/local/cuda-8.0/lib64:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$JAVA_HOME/bin:/snap/bin:/usr/local/cuda/bin:/usr/local/cuda/lib64' \
    PATH='/usr/local/cuda-8.0/bin:/home/EI/anaconda3/bin:/home/EI/anaconda2/bin:/home/EI/bin:/home/EI/.local/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$JAVA_HOME/bin:/snap/bin:/usr/local/cuda/bin:JAVA_HOME/bin:/usr/lib/Java/jdk1.8.0_121/jre/bin:/home/EI/anaconda3/bin:/home/EI/anaconda2/bin:/usr/local/cuda/bin:/home/EI/bin:JAVA_HOME/bin:/usr/lib/Java/jdk1.8.0_121/jre/bin' \
    TF_CUDA_CLANG=0 \
    TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2 \
    TF_CUDA_VERSION='' \
    TF_CUDNN_VERSION='' \
    TF_NEED_CUDA=1 \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections '-std=c++11' -MD -MF bazel-out/local_linux-py3-opt/bin/tensorflow/compiler/jit/_objs/common/tensorflow/compiler/jit/defs.pic.d '-frandom-seed=bazel-out/local_linux-py3-opt/bin/tensorflow/compiler/jit/_objs/common/tensorflow/compiler/jit/defs.pic.o' -fPIC -iquote . -iquote bazel-out/local_linux-py3-opt/genfiles -iquote external/bazel_tools -iquote bazel-out/local_linux-py3-opt/genfiles/external/bazel_tools -isystem external/bazel_tools/tools/cpp/gcc3 -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c tensorflow/compiler/jit/defs.cc -o bazel-out/local_linux-py3-opt/bin/tensorflow/compiler/jit/_objs/common/tensorflow/compiler/jit/defs.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 4.918s, Critical Path: 3.31s `

**Comment by asimshankar** [comment]
As mentioned in #8973, can you execute the failing command to determine what the error is?

**Comment by asimshankar** [comment]
Closing this out due to inactivity. If you're still running into trouble, please feel free to file a new issue with all relevant details (including what was suggested in the previous comment).

Thanks.

**Comment by joelteply** [comment]
This has to do with a lack of support for the current command line tools for OSX. We either need to fix tensorflow or people need to downgrade their command line tools to 8.0 before running bazel
