### ISSUE TITLE
Problem compiling for android

### ISSUE THREAD

**Issue by visasu** [tensorflow/tensorflow#9016]
Compiling for android example. Not sure if its a bug 
After Trying for  tensorflow/contrib/makefile/compile_android_protobuf.sh -c

checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... arm-unknown-linux-androideabi
checking target system type... arm-unknown-linux-androideabi
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-androideabi-strip... arm-linux-androideabi-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking for arm-linux-androideabi-gcc...  arm-linux-androideabi-gcc --sysroot ../android-ndk-r14b//platforms/android-21/arch-arm
checking whether the C compiler works... no
configure: error: in `/home/vishal/Downloads/tensorflowandroid/tensorflow/tensorflow/contrib/makefile/downloads/protobuf':
configure: error: C compiler cannot create executables
See `config.log' for more details

Config.log is attached
[config.txt](https://github.com/tensorflow/tensorflow/files/902101/config.txt)

Can someone look into it

**Comment by asimshankar** [comment]
This seems to be an error with your Android NDK setup. Looking at `config.txt`, I see things like:

```
/usr/lib/gcc/arm-linux-androideabi/4.7.4/../../../../arm-linux-androideabi/bin/ld: error: cannot find -llog
/usr/lib/gcc/arm-linux-androideabi/4.7.4/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lz
/usr/lib/gcc/arm-linux-androideabi/4.7.4/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lgnustl_static
```

suggesting that your NDK installation is incomplete or messed up as it is missing these libraries.

Closing this out since this doesn't seem to be an TensorFlow bug.
