### ISSUE TITLE
tf.image.crop_and_resize not working with uint8 images

### ISSUE THREAD

**Issue by Lescurel** [tensorflow/tensorflow#9020]
### Installation
- Custom code
- Pip install
- *TensorFlow version*: 1.0.1
- Python 2.7.9
- CPU based
- Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux

### Problem 

When reading images with opencv and then trying to use crop_and_resize on a tensor of uint8 data type, i get the following error : 

```
InvalidArgumentError (see above for traceback): No OpKernel was registered to support Op 'CropAndResize' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; T in [DT_FLOAT]

	 [[Node: generate_resized_crop = CropAndResize[T=DT_UINT8, extrapolation_value=0, method="bilinear"](ExpandDims, stack, zeros_like, generate_resized_crop/crop_size)]]
```

However, when casting my tensor in float32, the program works perfectly.
But the [documentation](https://www.tensorflow.org/versions/master/api_docs/python/tf/image/crop_and_resize) specifies that it should work with uint8 datatype. 

### Source Code
```Python
import cv2
import tensorflow as tf

frame=cv2.imread('path to img.jpg',-1)
raw_image=tf.placeholder(dtype=tf.uint8, shape=frame.shape, name='input_image')

def img2batch(input_image):
    raw_sample_tensor_4d=tf.expand_dims(input_image, 0)
    patches_top=[0,0.5]
    patches_bottom =[0.25,0.75]
    boxes=tf.stack([patches_top, patches_top, patches_bottom, patches_bottom], axis=1)
    crops=tf.image.crop_and_resize(raw_sample_tensor_4d, boxes, box_ind=tf.zeros_like(patches_top, dtype=tf.int32), crop_size=[200,200], method="bilinear", extrapolation_value=None, name="generate_resized_crop")
    return crops

with tf.Session() as sess:
    myBatchedImage=sess.run(img2batch(raw_image), feed_dict={raw_image:frame})
```
Problem solved with : 
```Python
crops=tf.image.crop_and_resize(tf.cast(raw_sample_tensor_4d, dtype=tf.float32), boxes, box_ind=tf.zeros_like(patches_top, dtype=tf.int32), crop_size=[200,200], method="bilinear", extrapolation_value=None, name="generate_resized_crop")
```

**Comment by asimshankar** [comment]
This does seem to be a documentation issue.

It seems that back in June 2016,   the initial introduction of the op added in https://github.com/tensorflow/tensorflow/commit/ea9ec0a3f938dc4db86a6d8616b7a9e62d73d49f aimed to support various types, but 7 days later this was changed to support only floats in https://github.com/tensorflow/tensorflow/commit/1d92cfcbf5c157b3e4069741ae5bdbbea6666dc5

@gpapan : Does the op documentation need to be updated or do we need to register kernels for more real number types?

**Comment by gpapan** [comment]
Will register more types (including uint8 for CPU) for tf.image_crop_and_resize() to resolve this. Should take a day or two to become public.

**Comment by zakizhou** [comment]
any updates?

**Comment by drpngx** [comment]
It looks like a few PR were merged. Do you still see the issue on `master`?

**Comment by LeeKyungMoon** [comment]
@Lescurel,  with your code, I got an error below:
**"Tensors in list passed to 'values' of 'Pack' Op have types [int32, <NOT CONVERTIBLE TO TENSOR>, <NOT CONVERTIBLE TO TENSOR>, int32] that don't all match"**

I'm trying this code with the tutorial of **object detection** from [tensorflowAPI](https://github.com/tensorflow/models/blob/master/research/object_detection/object_detection_tutorial.ipynb).

After detecting objects, I did try to crop and resize with this code below:
`cropped = sess.run(img2batch(raw_image), feed_dict={raw_image:image_np_expanded})`
then I got the error above.

I would appreciate if you could answer me. thanks.
