### ISSUE TITLE
Tensorboard to Latex

### ISSUE THREAD

**Issue by el3ment** [tensorflow/tensorflow#9024]
It would be nice if there was an export option in tensorboard that would export a latex-ready version of the visible graph - perhaps using SVG, Pgfplots or something similar. It's possible now to export CSV, and create the graphic by hand... but having it baked into tensorboard would be nice.

**Comment by asimshankar** [comment]
FYI @dandelionmane 

Sounds like a good idea. You may want to prototype a standalone tool first, or perhaps come up with a strawman design and discuss here before sending a PR. Contributions welcome!

**Comment by PatWie** [comment]
There is not much to do by hand. If you download the csv file and name it "data.csv", then you can do

```latex
\documentclass{article}
\usepackage[active,tightpage]{preview}
\usepackage{pgfplots}
\pgfplotsset{compat=newest}
\PreviewEnvironment{tikzpicture} 

\definecolor{tb_color_1}{RGB}{245,124,0}
\definecolor{tb_color_2}{RGB}{0,167,247}

\pgfplotscreateplotcyclelist{tb}{
semithick,tb_color_1\\%
semithick,tb_color_2\\%
}

\begin{document}
  \begin{tikzpicture}
    \begin{axis}[cycle list name=tb, 
                 grid=both,
                 grid style={solid,gray!30!white},
                 axis lines=middle,
                 xlabel={step},
                 ylabel={value},
                 x label style={at={(axis description cs:0.5,-0.1)},anchor=north},
                 y label style={at={(axis description cs:-0.1,.5)},rotate=90,anchor=south},]
      \addplot table [x=Step, y=Value, col sep=comma] {data.csv};
    \end{axis}
  \end{tikzpicture}
\end{document}
```
and get
![tb_latex](https://cloud.githubusercontent.com/assets/6756603/24898814/6634ede0-1e9e-11e7-9d98-3964508b88fe.png)

**Comment by jubjamie** [comment]
Did I now read somewhere that the download links to the data were being removed? Perhaps in some release notes? @dandelionmane have I got the wrong end of the stick regarding this?

**Comment by chris-chris** [comment]
@dandelionmane @asimshankar 
May I take a shot at it? 
I'm trying to export the graph in SVG format.

**Comment by wchargin** [comment]
Nope, we're not planning to remove the download links for scalar data. Both CSV and JSON formats will continue to exist.

I've migrated this to our new repository at https://github.com/tensorflow/tensorboard/issues/32.
