### ISSUE TITLE
Unable to start the Tensor Flow

### ISSUE THREAD

**Issue by shyamraj242** [tensorflow/tensorflow#9026]
Team,

I have installed anaconda on Redhat 6.8. I am following the installation steps of tensorflow from (https://www.tensorflow.org/install/install_linux#InstallingAnaconda). As the process of installation I am giving the command (conda create -n tensorflow). Because our cluster is protected I am unable to download the .conda directory. Can you please help me on this.

$ export PATH=/opt/app/anaconda2/python27/bin:$PATH
$ conda create -n tensorflow
Fetching package metadata ...

CondaHTTPError: HTTP None None for url https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by ProtocolError('Connection aborted.', error(97, 'Address family not supported by protocol')))",),)

$ cd /opt/app/anaconda2/python27/pkgs/tensorflow-0.10.0rc0-np111py27_0/
$ ll
total 12
drwxrwxr-x 2 python python 4096 Mar 31 11:20 bin
drwxrwxr-x 3 python python 4096 Dec 14 22:46 info
drwxrwxr-x 3 python python 4096 Dec 14 22:45 lib
$ pwd
 @shyamraj242
     
and also
Where can I find this URL in the tensor flow.

https://repo.continuum.io

**Comment by asimshankar** [comment]
The command `conda create -n tensorflow` only creates a conda environment. It hasn't begun doing anything this TensorFlow at that point.

Looking at your error message, this seems to be an issue with your conda installation and not TensorFlow, so I'm tempted to close this issue out. Perhaps you can look for support on why `conda create -n` is failing. `repo.continuum.io` is an Anaconda website, not a TensorFlow one.

Hope that helps!
