### ISSUE TITLE
Documentation for tf.contrib.learn's learn_runner

### ISSUE THREAD

**Issue by skycoop** [tensorflow/tensorflow#9032]
### You must complete this information or else your issue will be closed
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*: yes
- *TensorFlow installed from (source or binary)?*: source
- *TensorFlow version*: 1.0.1
- *Bazel version (if compiling from source)*: 0.4.4
- *CUDA/cuDNN version*: 8.0, 5.1
- *GPU Model and Memory*: GTX 1080
- *Exact command to reproduce*: n/a

### Describe the problem clearly
This is a feature request to add documentation.

As recommended by the GCP Cloud ML Engine documentation (specifically the code used by [this tutorial](https://cloud.google.com/ml-engine/docs/how-tos/getting-started-training-prediction)), I am attempting to use `tf.contrib.learn`'s `learn_runner` interface for training. However, I cannot figure out how to configure the checkpoint saving behaviour. Normally, I would just post a Stackoverflow question, but I feel that this interface would benefit greatly from some official documentation, especially as it is being recommended by GCP.

The closest I could get to documentation on this specific issue is a [cryptic comment](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/estimators/run_config.py#L198).

**Comment by asimshankar** [comment]
Hmm...the `learn_runner` interface isn't really part of the documented API on www.tensorflow.org/api_docs. Perhaps we shouldn't be using it.

CCing jhseu@ who might have comments on what to use instead and also whether and how the CloudML documentation should be updated.

**Comment by martinwicke** [comment]
We will add documentation shortly as we move this utility from contrib to core. This should happen within the next month or so. 

Note that this is still in contrib and its interface may still change.

**Comment by asimshankar** [comment]
Thanks for the report @skycoop . Closing this out for now, should be fixed when the API is finalized and moved into core (i.e., not part of `tf.contrib`) in a release or two.
