### ISSUE TITLE
Computing 2nd-order tf.gradients of tensors throws Exception when used with batch_norm

### ISSUE THREAD

**Issue by shaform** [tensorflow/tensorflow#9034]
### Describe the problem clearly

If the `updates_collections` of a `batch_norm` layer is set other than `tf.GraphKeys.UPDATE_OPS`, it is no longer possible to compute 2nd-order `tf.gradients` with respect to the weights of a `fully_connected` layer.

p.s. It is okay when `updates_collections` is set as `tf.GraphKeys.UPDATE_OPS`. I think `updates_collections` should not affect the ability to compute gradients?

### Environments

- Ubuntu 16.04 64bit
- Python 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 12:22:00) 
- [GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
- tensorflow-gpu 1.0.1 installed from pip
- libcublas.so.8.0, libcudnn.so.5, libcufft.so.8.0,  libcuda.so.1, libcurand.so.8.0

### Source Code
```python
import tensorflow as tf

with tf.Session() as sess:
    X = tf.placeholder(tf.float32, [None, 2])
    is_training = tf.placeholder(tf.bool, [], name='is_training')

    outputs = tf.contrib.layers.fully_connected(inputs=X, num_outputs=1)
    outputs = tf.contrib.layers.batch_norm(
        inputs=outputs,
        is_training=is_training,
        updates_collections='bad_collections')
    # get gradients of X with respect to outputs values
    grads = tf.gradients(outputs, [
        X,
    ])[0]
    bad_vars = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)
    # get gradients of weights with respect to gradients of X
    bad_grads = tf.gradients(grads, bad_vars) # this line
```

## Logs
```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    bad_grads = tf.gradients(grads, bad_vars)
  File "$HOME/anaconda2/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 474, in gradients
    out_grads[i] = control_flow_ops.ZerosLikeOutsideLoop(op, i)
  File "$HOME/anaconda2/envs/tf/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1303, in ZerosLikeOutsideLoop
    pred = op_ctxt.pred
AttributeError: 'NoneType' object has no attribute 'pred'
```

**Comment by Carmezim** [comment]
Hi @shaform, this seems a more suitable question for StackOverflow

**Comment by shaform** [comment]
Hi @Carmezim, thanks for the reply. I thought this was a bug since I
believed that changing updates_collections shouldn't affect the ability to
compute gradients. Your comment seems to suggest that the exception is
totally expected and therefore shouldn't be fixed. (i.e. It is not a bug.)
Could you share the rational behind this, please? Thanks.

**Comment by shaform** [comment]
I've updated the description and title to make to more clear.

**Comment by shaform** [comment]
Looks like it's because when custom `updates_collections` is set, legacy BN implementation would be used https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/contrib/layers/python/layers/layers.py#L536. It's likely that this implementation would cause problems when one attempts 2-nd order `tf.gradients`.

**Comment by drpngx** [comment]
@fchollet any comment on this? (contrib.layers)

**Comment by fchollet** [comment]
Can you log the specific op for which you cannot obtain second-order gradients?

**Comment by shaform** [comment]
@fchollet 
When the exception is thrown, the op on `out_grads[i] = control_flow_ops.ZerosLikeOutsideLoop(op, i)` is the following:
`<tf.Operation 'gradients_6/BatchNorm_3/cond_1/Merge_grad/cond_grad' type=Switch>`

**Comment by fchollet** [comment]
> I think updates_collections should not affect the ability to compute gradients?

When you are using a custom `updates_collections` you are routed to a *different* implementation of batch norm (the one in `tf.layers` does not support custom update collections), so this is not about `updates_collections` affecting gradient computation.

As far as I can tell you are calling an op (as part of the legacy batch norm layer implementation) that does not implement second-order gradients. Can anyone confirm?

**Comment by drpngx** [comment]
@yuanbyu is that something you've seen before?

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
