### ISSUE TITLE
Split on / Has Unexpected Behavior

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#9053]
Repost from: https://github.com/tensorflow/tensorflow/issues/8993#issuecomment-292632184 /CC @dandelionmane

So it looks like using `/`only works if the keys on the left does not already exist. 
For example this works (both on 1.1rc1):
![image](https://cloud.githubusercontent.com/assets/51059/24816749/f09f96e6-1ba7-11e7-9c1c-e36dd81bb0d0.png)

but this does not:
![image](https://cloud.githubusercontent.com/assets/51059/24816764/01af4b98-1ba8-11e7-8dad-eca20d0ffb5d.png)

**Comment by asimshankar** [comment]
I believe that is intentional - in that TensorBoard encourages use of `/` and not `_` as the logical separator and thus your graphs will have to be created with `/`s in the names.

**Comment by cancan101** [comment]
Yea  but this doesn't really have to do with_. Rather seems like something odd happens when name collision.

**Comment by wchargin** [comment]
Interesting. I can reproduce this. The following script demonstrates buggy behavior in TensorBoard:

```py
import tensorflow as tf

def main():
  k = tf.constant(0)
  tf.summary.scalar('loss', k)
  tf.summary.scalar('loss/regularization', k)
  tf.summary.scalar('loss_extra_stuff', k)
  summ = tf.summary.merge_all()

  sess = tf.Session()
  writer = tf.summary.FileWriter('/tmp/cat2')
  writer.add_graph(sess.graph)
  writer.add_summary(sess.run(summ))
  writer.close()

if __name__ == '__main__':
  main()
```

Thank you for reporting. I've migrated this to our new repository at https://github.com/tensorflow/tensorboard/issues/41.
