### ISSUE TITLE
tf.matmul should be extended for rank 1 tensors

### ISSUE THREAD

**Issue by Utumno** [tensorflow/tensorflow#9055]
This:

    import numpy as np
    a = np.array([1, 2, 1])
    w = np.array([[.5, .6], [.7, .8], [.7, .8]])
    
    print(np.dot(a, w))
    # [ 2.6  3. ] # plain nice old matrix multiplication n x (n, m) -> m
    
    import tensorflow as tf
    
    a = tf.constant(a, dtype=tf.float64)
    w = tf.constant(w)
    
    with tf.Session() as sess:
        print(tf.matmul(a, w).eval())
    
results in:

    ValueError: Shape must be rank 2 but is rank 1 for 'MatMul' (op: 'MatMul') with input shapes: [3], [3,2].

That's surprising and keeps tripping people up (see: http://stackoverflow.com/q/34908033/281545,  http://stackoverflow.com/q/43284897/281545, for instance), which is natural as matrix multiplication should not have any constraints apart from dimension alignment. Workarounds are verbose and complicated:

```
  print(tf.matmul(tf.expand_dims(a,0), w).eval())
  print((tf.reduce_sum(tf.multiply(tf.expand_dims(a,-1), w), axis=0)).eval())
  print((tf.reduce_sum(tf.multiply(a, tf.transpose(w)), axis=1)).eval())
```

### You must complete this information or else your issue will be closed
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*: yes
- *TensorFlow installed from (source or binary)?*: pip
- *TensorFlow version*: `tf.__version__` gives '1.0.1' - windows and python 3.5.2
- *Bazel version (if compiling from source)*: -
- *CUDA/cuDNN version*: -
- *GPU Model and Memory*: -
- *Exact command to reproduce*: see above

### Source Code / Logs

Full traceback (why printing the same error twice ?)

```
C:\_\Python35\python.exe C:/Users/MrD/.PyCharm2017.1/config/scratches/scratch_31.py
[ 2.6  3. ]
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "BestSplits" device_type: "CPU"') for unknown op: BestSplits
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "CountExtremelyRandomStats" device_type: "CPU"') for unknown op: CountExtremelyRandomStats
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "FinishedNodes" device_type: "CPU"') for unknown op: FinishedNodes
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "GrowTree" device_type: "CPU"') for unknown op: GrowTree
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ReinterpretStringToFloat" device_type: "CPU"') for unknown op: ReinterpretStringToFloat
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "SampleInputs" device_type: "CPU"') for unknown op: SampleInputs
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "ScatterAddNdim" device_type: "CPU"') for unknown op: ScatterAddNdim
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNInsert" device_type: "CPU"') for unknown op: TopNInsert
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TopNRemove" device_type: "CPU"') for unknown op: TopNRemove
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "TreePredictions" device_type: "CPU"') for unknown op: TreePredictions
E c:\tf_jenkins\home\workspace\release-win\device\cpu\os\windows\tensorflow\core\framework\op_kernel.cc:943] OpKernel ('op: "UpdateFertileSlots" device_type: "CPU"') for unknown op: UpdateFertileSlots
Traceback (most recent call last):
  File "C:\_\Python35\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "C:\_\Python35\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\_\Python35\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 2 but is rank 1 for 'MatMul' (op: 'MatMul') with input shapes: [3], [3,2].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/MrD/.PyCharm2017.1/config/scratches/scratch_31.py", line 14, in <module>
    print(tf.matmul(a, w).eval())
  File "C:\_\Python35\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1765, in matmul
    a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
  File "C:\_\Python35\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 1454, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "C:\_\Python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "C:\_\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 2329, in create_op
    set_shapes_for_outputs(ret)
  File "C:\_\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "C:\_\Python35\lib\site-packages\tensorflow\python\framework\ops.py", line 1667, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "C:\_\Python35\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "C:\_\Python35\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shape must be rank 2 but is rank 1 for 'MatMul' (op: 'MatMul') with input shapes: [3], [3,2].

Process finished with exit code 1

```

**Comment by aselle** [comment]
@rmlarsen, could you comment on this. I feel like you haven't allowed this since it would make an ambiguity between batch and non batch forms of matrix multiply.

**Comment by Utumno** [comment]
Thanks for answering

> Also, your example is not "plain nice matrix multiplication". It is left-side vector multiplication of a matrix with an implicit broadcast.

 it is matrix multiplication in the mathematical sense (1,n array with n,m array). Note that result `np.dot(a, w)` in my example has shape `(2,)` not `(2,1)`

**Comment by yaroslavvb** [comment]
I'm a [long-time user](http://stackoverflow.com/search?q=user:419116+[wolfram-mathematica]) of Mathematica, which allows mixing ranks, and I'm slightly biased against allowing this.

In Mathematica, you can take rank1 vec and do
1. `vec ~Dot~ mat`. This treats `vec` as a "row matrix"
2. `mat ~Dot~ vec` treats `vec` as a "column matrix"

This makes things more elegant in the short term. In the long term I've ended up with bugs where I've multiplied matrix on the wrong side, so I prefer to explicitly convert vectors to 2D tensors and take advantage of dimension checks.

**Comment by rmlarsen** [comment]
I too would like to find a compromise to allow vector*matrix, matrix*vector to be expressed more concisely. 

However, we have not allowed this because it would be ambiguous in the presence of broadcasting (which we have not yet implemented) and batched matmul.  

One approach is that taken by numpy.matmul(**a**,
 **b**) (https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html), which special cases rank(**a**) == 1 by implicitly promoting **a** to a 1 x n matrix. Likewise it promotes **b** to a m x 1 matrix for rank(**b**) == 1. For other ranks, the usual numpy broadcasting rules apply. 

The numpy approach is also not completely satisfactory, as I've seen several examples of code wanting to do batch_of_matrices * batch_of_vectors. An alternative to support this without extra code is to promote **a** of shape [k, l, ... m] => [1, k, l, ..., m] when rank(**a**) == rank(**b**) - 1 (and similarly promote **b** of shape [s, t, ..., n] to [s,t,...,1,n] when rank(**b**) == rank(**a**) - 1.
But this alternative is not compatible with Numpy broadcasting.

So in the presence of a clear choice, we have left the functionality as is. I'd be curious to hear more opinions on this.
