### ISSUE TITLE
No toolchain found for cpu 'arm64-v8a' when building android demo app

### ISSUE THREAD

**Issue by kindloaf** [tensorflow/tensorflow#9060]
Hi,

I'm trying to build the android demo app with target cpu of 'arm64-v8a', from a mac. With command "bazel build -c opt //tensorflow/examples/android:tensorflow_demo --cpu=arm64-v8a", I got the following error:
```
ERROR: No toolchain found for cpu 'arm64-v8a'. Valid cpus are: [
  darwin,
  armeabi-v7a,
  x64_windows_msvc,
  s390x,
  ios_x86_64,
].
```
I am able to build with the default target "armeabi-v7a". Any advice?

I'm on a fairly recent SHA: 55a1f26547f18ddc5c5b5c8a07479591a4ba789d (the master as of Mar 29). My bazel version is 0.4.5
I specified the NDK path in the WORKSPACE file as the following:
```
android_ndk_repository(
    name = "androidndk",
    path = "/Users/_user_/Downloads/android-ndk-r12b",
    api_level = 14)
```
I searched the toolchains under folder `/Users/_user_/Downloads/android-ndk-r12b/toolchains` and found `android-ndk-r12b/toolchains/llvm/prebuilt/darwin-x86_64/bin/arm64-v8a`. Not sure why bazel does not use it.

**Comment by asimshankar** [comment]
Could you try with `bazel build --config=android_arm64 //tensorflow/examples/android:tensorflow_demo` instead?

@andrewharp might have better suggestions.

**Comment by andrewharp** [comment]
With the addition of the --cpu flag it seems to forget that it's building for Android due to a missing crosstool_top flag that is usually passed simultaneously. If you use `--fat_apk_cpu=arm64-v8a` instead  it should work.

**Comment by kindloaf** [comment]
@asimshankar and @andrewharp ,
Thank you both for fast turnaround. It works like a charm. (I used the flag --fat_apk_cpu=arm64-v8a).

**Comment by asimshankar** [comment]
Closing this out since the main issue was resolved.

@andrewharp : Do you want to update https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/android/README.md ?
