### ISSUE TITLE
Building tensorflow for Windows 10

### ISSUE THREAD

**Issue by jdvala** [tensorflow/tensorflow#9068]
Hello All
I am trying to build tensorflow for my windows machine. I tried building it from source on ubuntu 16.04, but then that wheel doesn't support on windows. 
My machine is windows 10 
python 3.5.2

I dont know what the problem is, Can someone help me with this.

**Comment by asimshankar** [comment]
You will have to build from source on the Windows machine, however that is not officially supported yet. If you can, I'd suggest using the release binaries instead.

See https://www.tensorflow.org/install/ for details.

**Comment by jdvala** [comment]
I want tenosrflow to compile the SSE and AVX instructions set, I have to remove it in order to finish up a project of mine. Please do not close until knowing everything that is there to be known
.

**Comment by xenopsy** [comment]
I have the same problem too. Have you tried to build TF using Bazel for Windows?

**Comment by steel3d** [comment]
Any update on this? Google must be building those Windows binaries somehow...

**Comment by adaruna3** [comment]
Updates on this would be awesome! Speed boosts from machine learning specific optimizations would be great! Please share if you have information...

**Comment by KindDragon** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md

**Comment by faisalthaheem** [comment]
For anyone interested in x64 windows build of tensorflow1.4 with AVX2 instructions compatible with python 3.5.3 please visit the following link, details also given on howto compile yourself
[https://github.com/faisalthaheem/tensorflow-windows](https://github.com/faisalthaheem/tensorflow-windows)

**Comment by elena-kalinina** [comment]
@faisalthaheem thanks a lot ! that was really helpful !

**Comment by guikarist** [comment]
See my [comment](https://github.com/tensorflow/tensorflow/issues/7258#issuecomment-450802749) which provides a way to build on Windows automatically.
