### ISSUE TITLE
Errors when building iOS binaries with selective registration

### ISSUE THREAD

**Issue by timanglade** [tensorflow/tensorflow#9073]
The header file generated by [print_selective_registration_header.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/print_selective_registration_header.py) makes use of strcmp, which causes an error when compiling TensorFlow for iOS with selective registration enabled (`-DSELECTIVE_REGISTRATION`)

Apparently this was fixed in [a commit back in October](https://github.com/tensorflow/tensorflow/commit/c37847c1e5aedf5f33151895bdcbf9de89bbd759) but that commit was [reverted the same day](https://github.com/tensorflow/tensorflow/commit/3510b3060abef6b99fe4bc0656d8dc9406d6c46d) for some reason.

I’ve tried building the tool from the commit of TensorFlow that has the fix, but `./configure` fails for me on that version (missing targets & zlib download). I’ve also tried replacing calls to strcmp with a constexpr variant, but I’m not much help with C++ and couldn’t get anything to work there.

This prevents me from compiling a slimmed down TensorFlow binary for iOS.

cc @petewarden @cwhipkey 

### You must complete this information or else your issue will be closed
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*: No, just following the instructions in [print_selective_registration_header.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/print_selective_registration_header.py) and [selective_registration.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/selective_registration.h)
- *TensorFlow installed from (source or binary)?*: Source
- *TensorFlow version*: master (45115c0a985815feef3a97a13d6b082997b38e5d)
- *Bazel version (if compiling from source)*: 0.4.5
- *CUDA/cuDNN version*: N/A
- *GPU Model and Memory*: N/A
- *Exact command to reproduce*:
    ```bash
    $ bazel build tensorflow/python/tools/print_selective_registration_header
    $ bazel-bin/tensorflow/python/tools/print_selective_registration_header \
      --graphs=graph.pb > tensorflow/core/framework/ops_to_register.h
    $ tensorflow/contrib/makefile/compile_ios_tensorflow.sh "-Os -DSELECTIVE_REGISTRATION"

### Source Code / Logs
Here is the relevant log output on the last command:

```
In file included from ./tensorflow/core/framework/selective_registration.h:46:
./tensorflow/core/framework/ops_to_register.h:4:23: error: constexpr function never produces a
      constant expression [-Winvalid-constexpr]
constexpr inline bool ShouldRegisterOp(const char op[]) {
                      ^
./tensorflow/core/framework/ops_to_register.h:6:10: note: non-constexpr function 'strcmp' cannot
      be used in a constant expression
     || (strcmp(op, "Add") == 0)
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/usr/include/string.h:77:6: note:
      declared here
int      strcmp(const char *__s1, const char *__s2);
         ^
```

**Comment by jart** [comment]
It seems you're claiming building TensorFlow for iOS using contrib/makefile hasn't worked since October.

Assigning to @petewarden who works on mobile support. CC @wrwg wrote the rollback.

**Comment by timanglade** [comment]
> It seems you're claiming building TensorFlow for iOS using contrib/makefile hasn't worked since October.

Ah sorry, my bad. To be clear, building standard iOS binaries works fine. It’s just trying to build the iOS binaries _with selective registrations_ that seems to be broken. I edited the original issue to be clearer. Thanks @jart!

**Comment by es007** [comment]
it does not work also when compiling for Android with SELECTIVE_REGISTRATION . Same problem.

**Comment by es007** [comment]
A quick workaround: Paste the following functions to the beginning of the ops_to_register.h header:
`

constexpr int strcmpc(const char* a, const char* b)
  {

    return *a == 0 && *b == 0 ? 0 :
      *a == 0 ? -1 :
      *b == 0 ? 1 :
      *a < *b ? -1 :
      *a > *b ? 1 :
      *a == *b ? strcmpc(a+1, b+1) :
      false;
}

template <unsigned N2>
constexpr const char * strstrc( const char *str, const char (&substr)[N2])
{
return ( 0 == str )? NULL : ( true == strcmpc( str, substr ) )? str : strstrc( str + 1, substr );
}
`

and replace all the strcmp calls to strcmpc
and the strstr call to strstrc.

Please fix this bug in the next version.

Thanks

**Comment by timanglade** [comment]
Thanks @es007, I got a little further thanks to your comment, but it did not solve the problem.

First of all, your `strstrc` declaration does not seem necessary and creates a compile-time error for my ops_to_register.h. I just removed it, and I got through running `tensorflow/contrib/makefile/compile_ios_tensorflow.sh "-Os -DSELECTIVE_REGISTRATION"`. The binary libtensorflow-core.a that comes out is noticeably smaller, 263MB instead of 483.

I can compile my iOS app with it just fine, I hit an error whenever I try to build the graph. The error in my logs is:

```
Could not create TensorFlow Graph: Invalid argument: No OpKernel was registered to support Op 'Conv2D' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[Node: conv1/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true](input_1, conv1/kernel)]]
```

FWIW, the Conv2D OpKernel seems properly listed in [my ops_to_register.h file](https://www.dropbox.com/s/bginmeuipl5i479/ops_to_register.h?dl=0)).

I thought it could be caused by the `use_cudnn_on_gpu=true` attribute, but the fact is the exact same graph file loads & runs fine if I use a regular TensorFlow iOS library (without selective registration), so it still sounds like an issue related selective registration?

**Comment by cwhipkey** [comment]
In some cases, the host compiler used to generate the header file differs
from the compiler used for generating the on-device code - the difference
being in how whitespace pasting works in some parts of macro preprocessing.

The version of the selective registration python lib at master resolves
this by doing comparison ignoring whitespace.

It also removes use of strstr so that could be useful as well.

The strcmp issue may still remain, but that could be resolved with strcmp
implementation listed in this thread.

**Comment by timanglade** [comment]
@cwhipkey Thanks. To be clear, I’ve been working from master the past 2 days, and I’m still unable to get selective registration to work as expected when compiling iOS binaries, even when I get past the strcmp issue. Is there something I should be doing to avoid hitting this issue?

**Comment by timanglade** [comment]
For what it’s worth I also tried to manually fix the whitespace (as suggested in a [GitHub issue](https://github.com/tensorflow/tensorflow/issues/8486#issuecomment-288577876), and in a [StackOverflow answer](http://stackoverflow.com/a/43315844)), but still the same issue remains: libtensorflow-core.a compiles fine, but complains at runtime about no OpKernel being registered for Conv2D.

**Comment by es007** [comment]
@timanglade Can you paste your ops_to_register.h header file here?

**Comment by es007** [comment]
As for the white spaces, this function is insensitive to them:
`constexpr int strcmpc(const char* a, const char* b)
{

return *a == 0 && *b == 0 ? 0 :
       *a == ' ' ? strcmpc(a+1,b) :
       *b == ' ' ? strcmpc(a,b+1) :
  *a == 0 ? -1 :
  *b == 0 ? 1 :
  *a < *b ? -1 :
  *a > *b ? 1 :
  *a == *b ? strcmpc(a+1, b+1) :
  false;

}`

and at least in my ops_to_register.h file I have this macro defined:
`#define SHOULD_REGISTER_OP_KERNEL(clz) (strstr(kNecessaryOpKernelClasses, "," clz ",") != nullptr)`

I got the talked error:
`non-constexpr function 'strstr' cannot
      be used in a constant expression` too, and this is why I switch strstr with the strstrc implementation above and this solved the error.

I'm compiling TF (selective registration) for Android  armeabi-v7a.

**Comment by timanglade** [comment]
I'm compiling for iOS which I think is the difference here. I did find references to a similar issue for Android that was resolved some time ago, but no references to selective registration working (or failing) on iOS.

As mentioned above [my ops_to_register.h is available on Dropbox](https://www.dropbox.com/s/bginmeuipl5i479/ops_to_register.h?dl=0) It compiles fine but fails at runtime, with an error staying there is no OpKernel for Conv2D.

**Comment by es007** [comment]
Try this:

replace line 78 in your ops_to_register.h file:

#define SHOULD_REGISTER_OP_KERNEL(clz) (find_in<sizeof(kNecessaryOpKernelClasses) / sizeof(*kNecessaryOpKernelClasses)>::f(clz, kNecessaryOpKernelClasses))

with:

#define SHOULD_REGISTER_OP_KERNEL(clz) (strstrc(kNecessaryOpKernelClasses, "," clz ",") != nullptr)

and paste the strstrc function from above to the beginning of the file.

**Comment by cwhipkey** [comment]
I think that on ios, the kernel for convolution is the one from core/kernels/conv_ops_using_gemm.cc, which has a different name from what is in your ops_to_register.h file.   One thing to try would be to change the kernel class name in conv_ops_using_gemm.cc to be just Conv2DOp instead of Conv2DUsingGemmOp and see if then the kernel is included.

**Comment by timanglade** [comment]
@cwhipkey I tried changing all occurrences of “Conv2DUsingGemmOp” to “Conv2DOp” in core/kernels/conv_ops_using_gemm.cc but the outcome is the same: compiles fine, fails at runtime complaining there is no OpKernel registered for Conv2D.

@es007 Thanks for suggestion, this fails as well, but at compile time. Complaints about the template keyword and the N2 keyword, which in retrospect seems obvious. Am I missing a part of your implementation in [your comment earlier](https://github.com/tensorflow/tensorflow/issues/9073#issuecomment-292779949)?  I tried alternate implementations of strstrc but couldn’t get anything to work, really.

Thanks both for your help. I’m not very comfortable with C++ so there may be obvious fixes I’m missing…

I’m hoping someone who has successfully used selective registration on iOS can chime in on what has to be done to get ops_to_register.h to work as expected?

**Comment by cwhipkey** [comment]
Sorry, I think my suggestion was bad - because even with that name change,
the Conv2DUsingGemmOp won't have the exact same signature as the Conv2DOp.

The reason I am guessing that is the issue, though, is because:
1. if all kernels were being omitted, then you would probably see a
different kind of op being failed to find earlier.
2. a macro (USE_GEMM_FOR_CONV) is defined to control whether Conv2DOp is
used or Conv2DUsingGemmOp.  It seems possible that this macro was not
defined when building the tool to generate the header, and was defined when
compiling for the device.

You could instead remove definition of that macro from the makefile.  Or
instead include that macro when building the tool to generate the header
file, so you get a header file that includes Conv2DUsingGemmOp.

I'll be able to try out on my end on Monday (I've been mostly out of the
office this week).

**Comment by timanglade** [comment]
Alright @cwhipkey it worked! The full solution I used is as follows:

1. Build the print_selective_registration_header with the right macro for iOS
    ```bash
    $ bazel build --copt="-DUSE_GEMM_FOR_CONV" tensorflow/python/tools/print_selective_registration_header
    ```
2. Generate a header in the right path, i.e.
    ```bash
    $ bazel-bin/tensorflow/python/tools/print_selective_registration_header \
      --graphs=graph.pb > tensorflow/core/framework/ops_to_register.h
    ```
3. Edit **ops_to_register.h**
    * Replace all occurances of `strcmp` with `strcmpc`
    * Add the following function definition at the top of the file
        ```c++
        constexpr int strcmpc(const char* a, const char* b)
        {
          return *a == 0 && *b == 0 ? 0 :
          *a == ' ' ? strcmpc(a+1,b) :
          *b == ' ' ? strcmpc(a,b+1) :
          *a == 0 ? -1 :
          *b == 0 ? 1 :
          *a < *b ? -1 :
          *a > *b ? 1 :
          *a == *b ? strcmpc(a+1, b+1) :
          false;
        }
        ```
4. Build TensorFlow for iOS with the -DSELECTIVE_REGISTRATION flag:
    ```bash
    $ tensorflow/contrib/makefile/compile_ios_tensorflow.sh "-Os -DSELECTIVE_REGISTRATION"
    ```

In my case, the resulting libtensorflow-core.a is 45% smaller, and the resulting universal .ipa is 6.1MB lighter. (Of course, your mileage may vary depending on the graph you are using selective registration on.) Thanks everyone!

**Comment by adennie** [comment]
Adding a note here for Windows folks who run into this problem. The symptom in the windows build is:

error C2975: 'should_register': invalid template argument for 'tensorflow::register_op::OpDefBuilderWrapper', expected compile-time constant expression

Adding the strcmpc function and replacing strcmp with strcmpc in ops_to_register.h resolved it.

**Comment by cwhipkey** [comment]
Thanks, I've submitted a change that replaces the strcmpc calls with calls to the isequals function that is already emitted in ops_to_register.h.  This should resolve the ios build problem (I tried in a dummy .cc file and it worked).

The code should be available on github in the next few days...

**Comment by ruppeshnalwaya1993** [comment]
@cwhipkey can you tell me the "commit id" and the branch which replaces the strcmp calls with calls to the isequals function. The 1.2 release branch seems to still generate generate strcmpc calls while in master,  isequals calls are generated.

**Comment by cwhipkey** [comment]
https://github.com/tensorflow/tensorflow/commit/f333979e0d8625bca09c96478503c896fda24f25

Yes, it looks like it's not in 1.2 afaict:
https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/python/tools/print_selective_registration_header_test.py

**Comment by ruppeshnalwaya1993** [comment]
I tried to use -DUSE_GEMM_FOR_CONV flag for android selective registration as well like this
bazel build --copt="-DUSE_GEMM_FOR_CONV" tensorflow/python/tools/print_selective_registration_header

But during runtime it gives error and neural net fails to run. I tested on huawei nexus 6p. Without  --copt="-DUSE_GEMM_FOR_CONV", it runs fine. What does this mean? 

I believe "DUSE_GEMM_FOR_CONV" flag transforms convolution operation into matrix multiply to increase throughput(https://petewarden.com/2015/04/20/why-gemm-is-at-the-heart-of-deep-learning/). But since this is failing on android, we are not getting that efficiency on android devices. Is this correct? Can we use gemm for conv on adnroid?

**Comment by avishayzanbar** [comment]
hello, I am a new user of tensorflow. I wish to integrate graph.pb file into an ios device, and have followed all the compilation instructions carefully, yet when I try to run the camera example app I get the same error as previously mentioned:
```
E /Users/avishayzanbar/repos/tensorflow/tensorflow/examples/ios/camera_copy/tensorflow_utils.mm:140] Could not create TensorFlow Graph: Invalid argument: No OpKernel was registered to support Op 'Conv2D' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[{{node pyramid_regression_0/convolution}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](input_2, pyramid_regression_0/kernel/read)]]
2018-08-22 16:54:00.303760: F tensorflow/examples/ios/camera_copy/tensorflowUtil.mm:68] Couldn't load model: Invalid argument: No OpKernel was registered to support Op 'Conv2D' with these attrs.  Registered devices: [CPU], Registered kernels:
  <no registered kernels>

	 [[{{node pyramid_regression_0/convolution}} = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true](input_2, pyramid_regression_0/kernel/read)]]
```

I also followed the instructions that @timanglade detailed in the comments above, but there are some differences (probably due to the versions diffs between a year ago and now)
1. `bazel build --copt="-DUSE_GEMM_FOR_CONV" tensorflow/python/tools/print_selective_registration_header` compiled without errors

2. when I create the `ops_to_register.h` file using the _bazel-bin_ command, it adds a strange print of `tf.estimator package not installed` to the first line. In addition, during the file creation this warning appears multiple times:
` RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88`

3. when I create the `ops_to_register.h` file using  _python3_ , it creates the file without strange prints
4. in both cases there are no occurrences of `strcmp` or `strcmpc` at all, but instead of `Conv2DUsingGemmOp` got `Conv2DOp`

5. i tried to use the `ops_to_register.h` file for the `tensorflow/contrib/makefile/compile_ios_tensorflow.sh` compilation, but it fails during the compilation:
```
Undefined symbols for architecture arm64:
  "nsync::nsync_cv_signal(nsync::nsync_cv_s_*)", referenced from:
      tensorflow::condition_variable::notify_one() in libtensorflow-core-arm64.a(mutex.o)
  "nsync::nsync_cv_wait_with_deadline(nsync::nsync_cv_s_*, nsync::nsync_mu_s_*, timespec, nsync::nsync_note_s_*)", referenced from:
      tensorflow::condition_variable::wait_until_system_clock(tensorflow::mutex_lock&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >) in libtensorflow-core-arm64.a(mutex.o)
  "nsync::nsync_cv_init(nsync::nsync_cv_s_*)", referenced from:
      tensorflow::condition_variable::condition_variable() in libtensorflow-core-arm64.a(mutex.o)
  "nsync::nsync_from_time_point_(std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >)", referenced from:
      tensorflow::condition_variable::wait_until_system_clock(tensorflow::mutex_lock&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000l> > >) in libtensorflow-core-arm64.a(mutex.o)
  "nsync::nsync_cv_wait(nsync::nsync_cv_s_*, nsync::nsync_mu_s_*)", referenced from:
      tensorflow::condition_variable::wait(tensorflow::mutex_lock&) in libtensorflow-core-arm64.a(mutex.o)
  "nsync::nsync_mu_runlock(nsync::nsync_mu_s_*)", referenced from:
      tensorflow::mutex::unlock_shared() in libtensorflow-core-arm64.a(mutex.o)
  "nsync::nsync_mu_rlock(nsync::nsync_mu_s_*)", referenced from:
      tensorflow::mutex::lock_shared() in libtensorflow-core-arm64.a(mutex.o)
  "nsync::nsync_mu_unlock(nsync::nsync_mu_s_*)", referenced from:
      tensorflow::mutex::unlock() in libtensorflow-core-arm64.a(mutex.o)
  "nsync::nsync_mu_lock(nsync::nsync_mu_s_*)", referenced from:
      tensorflow::mutex::lock() in libtensorflow-core-arm64.a(mutex.o)
  "nsync::nsync_cv_broadcast(nsync::nsync_cv_s_*)", referenced from:
      tensorflow::condition_variable::notify_all() in libtensorflow-core-arm64.a(mutex.o)
  "nsync::nsync_mu_init(nsync::nsync_mu_s_*)", referenced from:
      tensorflow::mutex::mutex() in libtensorflow-core-arm64.a(mutex.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/avishayzanbar/repos/tensorflow/tensorflow/contrib/makefile/gen/bin/ios_ARM64/benchmark] Error 1
+ '[' 2 -ne 0 ']'
+ echo 'arm64 compilation failed.'
arm64 compilation failed.
+ exit 1
```

environment details:
- tensorflow 1.9.0 (there is tensorflow 1.10.0, but is currently not supported for the ios compilations)
- python 3.6.6
- all the compilations are done with **`-a arm64`** only

does anyone have an idea what went wrong here?

**Comment by NPetsky** [comment]
@avishayzanbar if you want to use the compile_ios_tensorflow.sh script you can simply use the long command that's in the universal binaries section (under the building by hand section) in the makefile readme (it says you should use that if you encounter issues with undefined nsync symbols)
If that doesn't work then:
first run the compile_nsync.sh script with -t ios -a arm64
then look where the libnsync.a library is in the downloads/nsync/ subfolders
Then replace the following lines in the build_all_ios.sh script: HOST_NSYNC_LIB=... and TARGET_NSYNC_LIB=... with
HOST_NSYNC_LIB='/absolute/path/to/libnsync.a' 
TARGET_NSYNC_LIB='absolute//path/to/libnsync.a' 
Then call build_all_ios.sh -a arm64 -g graph.pb 
Hope that resolves your issues
