### ISSUE TITLE
Documentation: broken links and image in documentation

### ISSUE THREAD

**Issue by ddurham2** [tensorflow/tensorflow#9074]
The URL:  https://www.tensorflow.org/versions/master/api_docs/python/tf/segment_sum has a broken link labelled "the section on Segmentation".  Also, there is a broken image on that page as well.

Same problems here too (except not all have an image to be broken):
   https://www.tensorflow.org/versions/master/api_docs/python/tf/segment_prod
   https://www.tensorflow.org/versions/master/api_docs/python/tf/segment_min
   https://www.tensorflow.org/versions/master/api_docs/python/tf/segment_max
   https://www.tensorflow.org/versions/master/api_docs/python/tf/segment_mean
   https://www.tensorflow.org/versions/master/api_docs/python/tf/unsorted_segment_sum
   https://www.tensorflow.org/versions/master/api_docs/python/tf/sparse_segment_sum
   https://www.tensorflow.org/versions/master/api_docs/python/tf/sparse_segment_mean
   https://www.tensorflow.org/versions/master/api_docs/python/tf/sparse_segment_sqrt_n

The page I believe they should link back to is here: https://www.tensorflow.org/versions/master/api_guides/python/math_ops#Segmentation

I came here because I haven't grokked just what segmented operations are yet.  So I would be much obliged if the explanation of segmentation were more thoroughly be explained there, perhaps with a couple of examples.

I found [a few places] in the code where this could be address.  And I would have attempted a pull request to fix these, but I'm not up on how to generate the documentation to verify that it was fixed.

**Comment by asimshankar** [comment]
Thanks for the report, the documentation is indeed broken. Looking into a fix.

As a workaround in the mean time, you can see the images at https://www.tensorflow.org/images/SegmentProd.png etc.

**Comment by ddurham2** [comment]
While you're at it, I noticed that on the unsorted_segment_sum page, it refers to perhaps an older naming scheme:
   "Unlike **SegmentSum**, segment_ids need not be sorted and need not cover all values in the full range of valid values."
