### ISSUE TITLE
TensorBoard : Scalars have tags but no content

### ISSUE THREAD

**Issue by allamtb** [tensorflow/tensorflow#9075]
can see the graph and Scalars tags，but  no Scalar content .

**Environment info**

ubuntu 15.04
virtualenv Python 2.7
Tensoflow installed from binary pip package,version 1.0.1
Chrome  45.0.2454.101 Ubuntu 15.04 (64-bit)

**About the code**

copy and run tensorflow/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py ,
then 
tensorboard --logdir /tmp/tensorflow/mnist/logs/mnist_with_summaries

**The following is output by adding "--debug":**

 DEBUG:tensorflow:No more events in /tmp/tensorflow/mnist/logs/mnist_with_summaries/test/events.out.tfevents.1491699349.amtb
INFO:tensorflow:No path found after /tmp/tensorflow/mnist/logs/mnist_with_summaries/test/events.out.tfevents.1491699349.amtb
DEBUG:tensorflow:Opening a record reader pointing at /tmp/tensorflow/mnist/logs/mnist_with_summaries/train/events.out.tfevents.1491699347.amtb
DEBUG:tensorflow:No more events in /tmp/tensorflow/mnist/logs/mnist_with_summaries/train/events.out.tfevents.1491699347.amtb
INFO:tensorflow:No path found after /tmp/tensorflow/mnist/logs/mnist_with_summaries/train/events.out.tfevents.1491699347.amtb
INFO:tensorflow:Finished with EventMultiplexer.Reload()
INFO:tensorflow:TensorBoard done reloading. Load took 14.782 secs
INFO:tensorflow:TensorBoard reload process beginning
INFO:tensorflow:Starting AddRunsFromDirectory: /tmp/tensorflow/mnist/logs/mnist_with_summaries
INFO:tensorflow:Adding events from directory /tmp/tensorflow/mnist/logs/mnist_with_summaries/train
INFO:tensorflow:Adding events from directory /tmp/tensorflow/mnist/logs/mnist_with_summaries/test
INFO:tensorflow:Done with AddRunsFromDirectory: /tmp/tensorflow/mnist/logs/mnist_with_summaries
INFO:tensorflow:TensorBoard reload process: Reload the whole Multiplexer
INFO:tensorflow:Beginning EventMultiplexer.Reload()
DEBUG:tensorflow:No more events in /tmp/tensorflow/mnist/logs/mnist_with_summaries/test/events.out.tfevents.1491699349.amtb
INFO:tensorflow:No path found after /tmp/tensorflow/mnist/logs/mnist_with_summaries/test/events.out.tfevents.1491699349.amtb
DEBUG:tensorflow:No more events in /tmp/tensorflow/mnist/logs/mnist_with_summaries/train/events.out.tfevents.1491699347.amtb
INFO:tensorflow:No path found after /tmp/tensorflow/mnist/logs/mnist_with_summaries/train/events.out.tfevents.1491699347.amtb
INFO:tensorflow:Finished with EventMultiplexer.Reload()
INFO:tensorflow:TensorBoard done reloading. Load took 0.003 secs

**The following is output by adding "--inspect":**

Processing event files... (this can take a few minutes)

Found event files in:
/tmp/tensorflow/mnist/logs/mnist_with_summaries/train
/tmp/tensorflow/mnist/logs/mnist_with_summaries/test

These tags are in /tmp/tensorflow/mnist/logs/mnist_with_summaries/train:
audio -
histograms
   layer1/Wx_plus_b/pre_activations
   layer1/activations
   layer1/biases/summaries/histogram
   layer1/weights/summaries/histogram
   layer2/Wx_plus_b/pre_activations
   layer2/activations
   layer2/biases/summaries/histogram
   layer2/weights/summaries/histogram
images
   input_reshape/input/image/0
   input_reshape/input/image/1
   input_reshape/input/image/2
   input_reshape/input/image/3
   input_reshape/input/image/4
   input_reshape/input/image/5
   input_reshape/input/image/6
   input_reshape/input/image/7
   input_reshape/input/image/8
   input_reshape/input/image/9
scalars
   accuracy_1
   cross_entropy_1
   dropout/dropout_keep_probability
   layer1/biases/summaries/max
   layer1/biases/summaries/mean
   layer1/biases/summaries/min
   layer1/biases/summaries/stddev_1
   layer1/weights/summaries/max
   layer1/weights/summaries/mean
   layer1/weights/summaries/min
   layer1/weights/summaries/stddev_1
   layer2/biases/summaries/max
   layer2/biases/summaries/mean
   layer2/biases/summaries/min
   layer2/biases/summaries/stddev_1
   layer2/weights/summaries/max
   layer2/weights/summaries/mean
   layer2/weights/summaries/min
   layer2/weights/summaries/stddev_1

Event statistics for /tmp/tensorflow/mnist/logs/mnist_with_summaries/train:
audio -
graph
   first_step           0
   last_step            0
   max_step             0
   min_step             0
   num_steps            1
   outoforder_steps     []
histograms
   first_step           1
   last_step            999
   max_step             999
   min_step             1
   num_steps            900
   outoforder_steps     []
images
   first_step           1
   last_step            999
   max_step             999
   min_step             1
   num_steps            900
   outoforder_steps     []
scalars
   first_step           1
   last_step            999
   max_step             999
   min_step             1
   num_steps            900
   outoforder_steps     []
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -

These tags are in /tmp/tensorflow/mnist/logs/mnist_with_summaries/test:
audio -
histograms
   layer1/Wx_plus_b/pre_activations
   layer1/activations
   layer1/biases/summaries/histogram
   layer1/weights/summaries/histogram
   layer2/Wx_plus_b/pre_activations
   layer2/activations
   layer2/biases/summaries/histogram
   layer2/weights/summaries/histogram
images
   input_reshape/input/image/0
   input_reshape/input/image/1
   input_reshape/input/image/2
   input_reshape/input/image/3
   input_reshape/input/image/4
   input_reshape/input/image/5
   input_reshape/input/image/6
   input_reshape/input/image/7
   input_reshape/input/image/8
   input_reshape/input/image/9
scalars
   accuracy_1
   cross_entropy_1
   dropout/dropout_keep_probability
   layer1/biases/summaries/max
   layer1/biases/summaries/mean
   layer1/biases/summaries/min
   layer1/biases/summaries/stddev_1
   layer1/weights/summaries/max
   layer1/weights/summaries/mean
   layer1/weights/summaries/min
   layer1/weights/summaries/stddev_1
   layer2/biases/summaries/max
   layer2/biases/summaries/mean
   layer2/biases/summaries/min
   layer2/biases/summaries/stddev_1
   layer2/weights/summaries/max
   layer2/weights/summaries/mean
   layer2/weights/summaries/min
   layer2/weights/summaries/stddev_1

Event statistics for /tmp/tensorflow/mnist/logs/mnist_with_summaries/test:
audio -
graph -
histograms
   first_step           0
   last_step            990
   max_step             990
   min_step             0
   num_steps            100
   outoforder_steps     []
images
   first_step           0
   last_step            990
   max_step             990
   min_step             0
   num_steps            100
   outoforder_steps     []
scalars
   first_step           0
   last_step            990
   max_step             990
   min_step             0
   num_steps            100
   outoforder_steps     []
sessionlog:checkpoint -
sessionlog:start -
sessionlog:stop -

**issue picture**:
![issue](https://cloud.githubusercontent.com/assets/4977856/24833889/94f2d2e2-1d08-11e7-8c11-aa91917549c4.png)

**Comment by jart** [comment]
Thanks for reaching out. Any chance you could press Ctrl+Alt+J or Command+Option+J in Chrome to open up the JavaScript log, so you can let us know if there are any errors in there?

**Comment by allamtb** [comment]
Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
/deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

**Comment by dandelionmane** [comment]
Ah, I think we have let the `let` keyword slip into our html files. It's safe when guarded by the TS compiler, but not when it makes it into html/js. Will fix.

**Comment by dandelionmane** [comment]
Alternatively, maybe we can just enable strict mode?

**Comment by allamtb** [comment]
@jart @dandelionmane 
   when I update the chrome  to version 57.0.2987.133 ,the issue disappeared.
