### ISSUE TITLE
ImportError: No module named 'tensorflow.models'

### ISSUE THREAD

**Issue by andyliaw** [tensorflow/tensorflow#9076]
NOTE: Issues that are not bugs or feature requests will be closed. Please ask usage questions on StackOverflow.

### You must complete this information or else your issue will be closed
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*: yes
- *TensorFlow installed from (source or binary)?*: binary (anaconda)
- *TensorFlow version*: 1.0.1
- *Bazel version (if compiling from source)*:
- *CUDA/cuDNN version*: 8.0
- *GPU Model and Memory*: GTX 1080 8GB
- *Exact command to reproduce*: import tensorflow.models

### Describe the problem clearly
$ python
Python 3.5.3 |Continuum Analytics, Inc.| (default, Mar  6 2017, 11:58:13) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow.models
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'tensorflow.models'

### Source Code / Logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full-traceback. Large logs and files should be attached. Try to reproducible test-case code the bare-minimum necessary to generate the problem

**Comment by asimshankar** [comment]
There is no `tensorflow.models` module.

Perhaps you're looking for the models github repository? (https://github.com/tensorflow/models)

**Comment by kiranvarghesev** [comment]
from tensorflow.models.rnn.translate import data_utils

ImportError: No module named 'tensorflow.models'

**Comment by codeLiudehua** [comment]
how solve？

**Comment by AMFIRNAS** [comment]
same error here as well :(

**Comment by MumMumMum** [comment]
You need to build the object_detection api usind setup.py build and setup.py install First

**Comment by KarimElshaweish** [comment]
write
 from tensorflow.python.keras._impl.keras.utils import data_utils

**Comment by hyperobjects** [comment]
> write
> from tensorflow.python.keras._impl.keras.utils import data_utils

I tried this and received this error: 
"ModuleNotFoundError: No module named 'tensorflow.python.keras._impl'"

**Comment by Smsmadly** [comment]
> > write
> > from tensorflow.python.keras._impl.keras.utils import data_utils
> 
> I tried this and received this error:
> "ModuleNotFoundError: No module named 'tensorflow.python.keras._impl'"
write
from tensorflow.python.keras.utils import data_utils
