### ISSUE TITLE
Visualizing CNNs with TensorBoard

### ISSUE THREAD

**Issue by jeandut** [tensorflow/tensorflow#908]
I am a huge fan of Tensorboard visualization however in my opinion it may lack good documentation when the user wants to implement non trivial visualization for example visualizing weights for a CNNs (or even features) (and also on how everything is stored and processed but that is another question).  
I am runing a CNN on a set of color images the structure and the code of my cnn is almost entirely based on Deep MNIST tutorial/MNIST+tensorboard tutorial.
I have several problems :
I want to run tf.image_summary(W_conv1) every 100 steps/epochs of the training with W_conv1 being of shape (3,5,5,32) (first conv layer after an RGB image)
However the desired shape is (32,5,5,3) so I reshape using `tf.reshape(W_conv1;shape=(32,5,5,3))`
I am only using reshape because I could not find a numpy swapaxes equivalent in tf (and from the definition of reshape in numpy doc I am not sure wether or not it does exactly what I wanted but I agree it is my problem...).
I call a `merge_all_summaries()` that I feed every 100 steps.
I run 1000 epochs so I should get 320 images, instead I get 2 or 3 actually displayed !!!
On stackoverflow I found out that even if all the images are loaded into the memory (where?!) it does not display them all and that I should do something like initialize an empty tf.summary() and call `.MergefromString(image_summary)` but I am confused on exactly where in the code I should do that and at what time ?
My second issue is I also want to see the weights for the second conv layer which is of shape (32,5,5,64) so I would like to split it into (32x64) 5x5 images does that seem reasonnable ?
How would I go about displaying them ?
Same for features obtained at different layers of the CNN ?
I understand my questions are trivial but I think a lot of people would benefit (I would certainly) from an example of a clean and efficient code in tensorflow of a CNN on whatever image dataset WITH tensorboard visualization of the weights/features.
Thanks for the work TF is amazing !

**Comment by cesarsalgado** [comment]
This issue is related to #842

**Comment by jeandut** [comment]
I agree with you it is related, however I am not asking for the creation of a toolbox, more for a small example script somewhere, which let you use TensorBoard as it was planned !
But I would be in favour of such a tool of course if the team is motivated !

**Comment by panmari** [comment]
I asked something similar not too long ago [on stackoverflow](http://stackoverflow.com/questions/33802336/visualizing-output-of-convolutional-layer-in-tensorflow). The solution there was to make a pack the activations into a grid of little images. Would that solve your problem?

**Comment by jeandut** [comment]
Damn it I saw it on stack but did not really read through ! That is certainly a good start however I stand by my demand of a clean and safe tutorial made by google team to transform this very intelligent hack into something classier.

**Comment by jeandut** [comment]
I did the trick to get a grid of weights, and convolutions of one image (thanks @panmari ) Nonetheless I still want to hear a clean and good solution for exemple the grid trick is not super great because the size of the entire grid seems to be limited to very short values so even using `tf.image.resize_images`.
I am sure there are better ideas out there on how to do these visualizations !

**Comment by jeandut** [comment]
No comment/improvement/other ideas on how to visualize CNN in a tensorflow way ?

**Comment by martin-gorner** [comment]
Hi jeandut

Here is a snippet of code fo visualising convolutional layer, in my case it's of shape [5, 5, 1, 24] so you will have to adapt it to your case. I reformatted the 5x5 24-deep convolution kernel as a square grid of 25 5x5 images, the last one being just padding:

```
W1_a = W1                            # [5, 5, 1, 24]
W1pad= tf.zeros([5, 5, 1, 1])        # [5, 5, 1, 24]
W1_b = tf.concat(3, [W1_a, W1pad])   # [5, 5, 1, 25]
W1_c = tf.split(3, 25, W1_b)         # 25 x [5, 5, 1, 1]
W1_row0 = tf.concat(0, W1_c[0:5])    # [25, 5, 1, 1]
W1_row1 = tf.concat(0, W1_c[5:10])   # [25, 5, 1, 1]
W1_row2 = tf.concat(0, W1_c[10:15])  # [25, 5, 1, 1]
W1_row3 = tf.concat(0, W1_c[15:20])  # [25, 5, 1, 1]
W1_row4 = tf.concat(0, W1_c[20:25])  # [25, 5, 1, 1]
W1_d = tf.concat(1, [W1_row0, W1_row1, W1_row2, W1_row3, W1_row4]) # [25, 25, 1, 1]
W1_e = tf.reshape(W1_d, [1, 25, 25, 1])
tf.image_summary(Wtag, W1_e)
```

**Comment by jeandut** [comment]
Hi martin-gorner thanks for making this thread live on !!! By reading your code hastily I am kind of curious about what you are doing but will try it tomorrow for sure. However what intrigues me the most is the last line, where does Wtag come from ? Is it a way to make it evolve through time ? (like any othe summary except images that seem to be stuck)  Because in mark daoust's trick you already had a kind of reshaping into a grid of weights. Could you explain the advantages of your method ?

**Comment by martin-gorner** [comment]
Sorry, Wtag is just a string placeholder. It's the tring tensorboard will display in ints output as a caption for the image. I modified the code to make it explicit. I feed it in the training loop with something like W1_iteration_####

**Comment by martin-gorner** [comment]
For your case, I would try something like this (I have not tested it):
You have 32 color (3-deep) kernels of size 5x5. The shape of your W1 is [5, 5, 3, 32].
So I would try to display the 32 kernels in a 6x6 grid. That's 36 slots so you will have to add 4 zero kernels for padding.

```
W1_a = W1                            # [5, 5, 3, 32]
W1pad= tf.zeros([5, 5, 3, 1])        # [5, 5, 3, 4]  - four zero kernels for padding
W1_b = tf.concat(3, [W1_a, W1pad])   # [5, 5, 3, 36]
W1_c = tf.split(3, 36, W1_b)         # 36 x [5, 5, 3, 1]
W1_row0 = tf.concat(0, W1_c[0:6])    # [30, 5, 3, 1]
W1_row1 = tf.concat(0, W1_c[6:12])   # [30, 5, 3, 1]
W1_row2 = tf.concat(0, W1_c[12:18])  # [30, 5, 3, 1]
W1_row3 = tf.concat(0, W1_c[18:24])  # [30, 5, 3, 1]
W1_row4 = tf.concat(0, W1_c[24:30])  # [30, 5, 3, 1]
W1_row5 = tf.concat(0, W1_c[30:36])  # [30, 5, 3, 1]
W1_d = tf.concat(1, [W1_row0, W1_row1, W1_row2, W1_row3, W1_row4, W1_row5]) # [30, 30, 3, 1]
W1_e = tf.reshape(W1_d, [1, 30, 30, 3])
Wtag = tf.placeholder(tf.string, None)
tf.image_summary(Wtag, W1_e)
```

**Comment by jeandut** [comment]
Oh in this case I would have an update of look of the weights throughout the training thanks @martin-gorner ! Good answer probably the one closest to what I have been asking for however I am not closing this issue though as I still feel a bit unsatisfied of the look of the results in terms of display.

**Comment by martin-gorner** [comment]
And here is a sample output (first convolutional layer of a neural network training on the MNIST handwritten character recognition problem). The grid was photoshopped in and individual kernel visualisation assembled as an animated GIF:
![mnist7convsimplified_w1_best](https://cloud.githubusercontent.com/assets/959847/13878781/dec1a482-ed13-11e5-921a-37edf9f68f51.gif)

**Comment by RobRomijnders** [comment]
Thank you @martin-gorner 

For @jeandut , this is my final code:
`
# -*- coding: utf-8 -*-
"""
Created on Tue Mar 22 10:43:29 2016

@author: rob
"""
import numpy as np
import tensorflow as tf
import input_data
from numpy import genfromtxt
sess = tf.InteractiveSession()


X_test = genfromtxt('X_test.csv', delimiter=',')
y_test = genfromtxt('y_test.csv', delimiter=',')
X_train = genfromtxt('X_train.csv', delimiter=',')
y_train = genfromtxt('y_train.csv', delimiter=',')
X_test = X_test.astype('float32')
y_test = y_test.astype('float32')
X_train = X_train.astype('float32')
y_train = y_train.astype('float32')

N = X_train.shape[0]
Ntest = X_test.shape[0]

#Check for the input sizes
assert (N>X_train.shape[1]), 'You are feeding a fat matrix for training, are you sure?'
assert (Ntest>X_test.shape[1]), 'You are feeding a fat matrix for testing, are you sure?'
assert (y_train.shape[0]>y_train.shape[1]), 'You are feedinf a fat matrix for labels, are you sure?'

# Nodes for the input variables
x = tf.placeholder("float", shape=[None, 784], name = 'Input_data')
y_ = tf.placeholder("float", shape=[None, 10], name = 'Ground_truth')


def weight_variable(shape, name):
  initial = tf.truncated_normal(shape, stddev=0.1)
  return tf.Variable(initial, name = name)

def bias_variable(shape, name):
  initial = tf.constant(0.1, shape=shape)
  return tf.Variable(initial, name = name)

def conv2d(x, W):
  return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')

def max_pool_2x2(x):
  return tf.nn.max_pool(x, ksize=[1, 2, 2, 1],
                        strides=[1, 2, 2, 1], padding='SAME')

with tf.name_scope("Reshaping_data") as scope:
  x_image = tf.reshape(x, [-1,28,28,1])
  image_summ = tf.image_summary("Example_images", x_image)

with tf.name_scope("Conv1") as scope:
  W_conv1 = weight_variable([5, 5, 1, 32], 'Conv_Layer_1')
  b_conv1 = bias_variable([32], 'bias_for_Conv_Layer_1')
  h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1)
  h_pool1 = max_pool_2x2(h_conv1)
  
with tf.name_scope('Visualize_filters') as scope:
# In this section, we visualize the filters of the first convolutional layers
# We concatenate the filters into one image
# Credits for the inspiration go to martin gorner
  W1_a = W_conv1                       # [5, 5, 1, 32]
  W1pad= tf.zeros([5, 5, 1, 1])        # [5, 5, 1, 4]  - four zero kernels for padding
  # We have a 6 by 6 grid of kernepl visualizations. yet we only have 32 filters
  # Therefore, we concatenate 4 empty filters
  W1_b = tf.concat(3, [W1_a, W1pad, W1pad, W1pad, W1pad])   # [5, 5, 1, 36]  
  W1_c = tf.split(3, 36, W1_b)         # 36 x [5, 5, 1, 1]
  W1_row0 = tf.concat(0, W1_c[0:6])    # [30, 5, 1, 1]
  W1_row1 = tf.concat(0, W1_c[6:12])   # [30, 5, 1, 1]
  W1_row2 = tf.concat(0, W1_c[12:18])  # [30, 5, 1, 1]
  W1_row3 = tf.concat(0, W1_c[18:24])  # [30, 5, 1, 1]
  W1_row4 = tf.concat(0, W1_c[24:30])  # [30, 5, 1, 1]
  W1_row5 = tf.concat(0, W1_c[30:36])  # [30, 5, 1, 1]
  W1_d = tf.concat(1, [W1_row0, W1_row1, W1_row2, W1_row3, W1_row4, W1_row5]) # [30, 30, 1, 1]
  W1_e = tf.reshape(W1_d, [1, 30, 30, 1])
  Wtag = tf.placeholder(tf.string, None)
  tf.image_summary("Visualize_kernels", W1_e)


with tf.name_scope("Conv2") as scope:
  W_conv2 = weight_variable([5, 5, 32, 64], 'Conv_Layer_2')
  b_conv2 = bias_variable([64], 'bias_for_Conv_Layer_2')
  h_conv2 = tf.nn.relu(conv2d(h_pool1, W_conv2) + b_conv2)
  h_pool2 = max_pool_2x2(h_conv2)

with tf.name_scope("Fully_Connected1") as scope:
  W_fc1 = weight_variable([7 * 7 * 64, 1024], 'Fully_Connected_layer_1')
  b_fc1 = bias_variable([1024], 'bias_for_Fully_Connected_Layer_1')
  h_pool2_flat = tf.reshape(h_pool2, [-1, 7*7*64])
  h_fc1 = tf.nn.relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)

with tf.name_scope("Fully_Connected2") as scope:
  keep_prob = tf.placeholder("float")
  h_fc1_drop = tf.nn.dropout(h_fc1, keep_prob)
  
  W_fc2 = tf.Variable(tf.truncated_normal([1024, 10], stddev=0.1),name = 'W_fc2')
  b_fc2 = tf.Variable(tf.constant(0.1, shape=[10]),name = 'b_fc2')

with tf.name_scope("Final_Softmax") as scope:
  y_conv=tf.nn.softmax(tf.matmul(h_fc1_drop, W_fc2) + b_fc2)

#Play with TensorBoard
w_hist = tf.histogram_summary("W_fc2", W_fc2)
b_hist = tf.histogram_summary("b_fc2", b_fc2)
#y_hist = tf.histogram_summary("y_conv", y_conv)

with tf.name_scope("Entropy") as scope:
    cross_entropy = -tf.reduce_sum(y_*tf.log(y_conv))
    ce_summ = tf.scalar_summary("cross entropy", cross_entropy)
with tf.name_scope("train") as scope:
    train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)
with tf.name_scope("Evaluating") as scope:
    correct_prediction = tf.equal(tf.argmax(y_conv,1), tf.argmax(y_,1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    accuracy_summary = tf.scalar_summary("accuracy", accuracy)
    
    
merged = tf.merge_all_summaries()
writer = tf.train.SummaryWriter("/home/rob/Dropbox/ConvNets/tf/log_tb", sess.graph_def)

sess.run(tf.initialize_all_variables())
for i in range(500):
  batch_ind = np.random.choice(N,50,replace=False)
  if i%100 == 0:
    result = sess.run([accuracy,merged], feed_dict={ x: X_test, y_: y_test, keep_prob: 1.0})
    acc = result[0]
    summary_str = result[1]
    writer.add_summary(summary_str, i)
    writer.flush()
    print("Accuracy at step %s: %s" % (i, acc))

  sess.run(train_step,feed_dict={x:X_train[batch_ind], y_: y_train[batch_ind], keep_prob: 0.5})
 
sess.close()
`

**Comment by RobRomijnders** [comment]
@jeandut 
Jeandut, I can understand your answer is not satisfactorily answered. I join you on the quest for nice tutorials. 
In the meantime, I got some code running that uses TensorBoard for a nice graph, plots some histograms and the visualization of the 32 filters. You can find it on
http://robromijnders.github.io/tensorflow_basic/

Hope that helps:)

**Comment by jeandut** [comment]
Yeah thanks to you guys my plots are beginning to feel right ! @RobRomijnders this webpage is really nicely done ! I am hesitating to close this issue because it seems like the longer it lasts the more cool answers I am getting. However I can honestly say that my original question has been answered !

**Comment by danmane** [comment]
@RobRomijnders @jeandut If you are on a quest for nice tutorials, I encourage you to help improve the TensorFlow tutorials. It's an open source project - you can modify everything yourself! For example, @RobRomijnders you could modify our tutorial code for CNNs to use TensorBoard like in the page you posted.

@martin-gorner nice job with the convolution filter visualization. If you want to submit a proposal for how the API should look for adding that to TensorBoard, that would be quite welcome.

Closing this issue since @jeandut says his question was answered (:

**Comment by edubergeek** [comment]
Many thanks to @martin-gorner for the code examples above. It was very helpful to me.
Now here is my derived code for an 8x8x32x64 conv2d layer that works with TensorFlow 1.1 (order of parameters shifted for some methods). Maybe this helps someone else.

  f2=32
  f3=64

  W3 = weight_variable([8, 8, f2, f3]) # hidden layer 3 has f2 input channels and f3 output channels
  b3 = bias_variable([f3])
  l3 = tf.nn.relu(conv2d(a2, W3) + b3) # a2 is downsampled activations from layer_2
  a3 = max_pool_2x2(l3)

  # visualize 32 x 64 learned feature filters as 32 (input channel) images 
  # each input channel is seen as an 8x8 (64 output channels) grid of 8x8x1 (grayscale) filters
  with tf.name_scope('layer_3'):
    W3_a = W3                                           # [8, 8, 32, 64]
    #W3pad= tf.zeros([8, 8, 32, n])             # [8, 8, 32, n]  - n zero kernels for padding
    #W3_b = tf.concat([W3_a, W3pad], 3)  # [8, 8, 32, 64]
    # in my case I have exactly 64 output channels so I assign W3_b to W3_a
    # comment the assignment below and uncomment the tf.zeros and tf.concat statements above to pad
    # fewer than 64 output channels to exactly 64. You have to change "n" of course!
    W3_b = W3_a
    W3_c = tf.split(W3_b, 64, 3)                  # 64 x [8, 8, 32, 1]
    W3_row0 = tf.concat(W3_c[0:8], 0)       # [64, 8, 32, 1]
    W3_row1 = tf.concat(W3_c[8:16], 0)     # [64, 8, 32, 1]
    W3_row2 = tf.concat(W3_c[16:24], 0)    # [64, 8, 32, 1]
    W3_row3 = tf.concat(W3_c[24:32], 0)    # [64, 8, 32, 1]
    W3_row4 = tf.concat(W3_c[32:40], 0)    # [64, 8, 32, 1]
    W3_row5 = tf.concat(W3_c[40:48], 0)    # [64, 8, 32, 1]
    W3_row6 = tf.concat(W3_c[48:56], 0)    # [64, 8, 32, 1]
    W3_row7 = tf.concat(W3_c[56:64], 0)    # [64, 8, 32, 1]
    W3_d = tf.concat([W3_row0, W3_row1, W3_row2, W3_row3, W3_row4, W3_row5, W3_row6, W3_row7], 1) # [64, 64, 32, 1]
    W3_e = tf.reshape(W3_d, [1, 64, 64, 32])
    W3_f = tf.split(W3_e, 32, 3)                    # 32 x [1, 64, 64, 1]
    W3_g = tf.concat(W3_f[0:32], 0)             # [32, 64, 64, 1]
    tf.summary.image("filter", W3_g, 32)

**Comment by kazemSafari** [comment]
When i try to run the above code for the first conv layer i get the following error:
TypeError: Expected int32, got <tf.Variable 'W_conv1:0' shape=(5, 5, 1, 32) dtype=float32_ref> of type 'Variable' instead.

Help is appreciated! Thanks!

**Comment by monjoybme** [comment]
@martin-gorner, @edubergeek, and @jeandut I'm almost in a similar situation but in case of convolution layer, I'm trying to visualize a deconvolution layer. The shape of the layer is (5, 100, 100, 3) in NHWC format. Basically I need 100 x 300 grids but when I'm implementing the as above getting error "ValueError: Cannot reshape a tensor". Any idea how can I solve this issue?

**Comment by monjoybme** [comment]
Issue solved. Thanks

**Comment by vesaalexandru95** [comment]
Hello. Can someone explain me the logic behind @martin-gorner code? I want to visualize some filters but I really don't understand what he did there. Thanks a lot, Alex

**Comment by martin-gorner** [comment]
@vesaalexandru95 The explanations:

I was trying to visualize the weights of a convolutional layer of shape [5,5,1,24]. That'a a 5x5 convolution working on an image with 1 channel (B&W). The convolution is repeated 24 times with different weights. So we have 24 different convolution "kernels" to visualize. It will be a nice fit in a 5x5=25 grid with a single grid cell unoccupied.


W1_a = W1                            # [5, 5, 3, 32]



# All the weights are in this tensor
W1_a = W1                            # [5, 5, 1, 24]
# We add zeros for the weights of a 25th "kernel", so as to have 25 kernels to visualize
W1pad= tf.zeros([5, 5, 1, 1])        # [5, 5, 1, 1]
# This now looks like we have 25 "kernels"
W1_b = tf.concat(3, [W1_a, W1pad])   # [5, 5, 1, 25]
# We split into a list of 25 individual "kernels"
W1_c = tf.split(3, 25, W1_b)         # 25 x [5, 5, 1, 1]
# This could be in a for loop, easier to understand with rows spelled out one by one
# Concatenate five 5x5 "kernels" into a row of 25x5 weights
W1_row0 = tf.concat(0, W1_c[0:5])    # [25, 5, 1, 1]
# Concatenate another five 5x5 "kernels" into a row of 25x5 weights
W1_row1 = tf.concat(0, W1_c[5:10])   # [25, 5, 1, 1]
# Concatenate another five 5x5 "kernels" into a row of 25x5 weights
W1_row2 = tf.concat(0, W1_c[10:15])  # [25, 5, 1, 1]
# Concatenate another five 5x5 "kernels" into a row of 25x5 weights
W1_row3 = tf.concat(0, W1_c[15:20])  # [25, 5, 1, 1]
# Concatenate another five 5x5 "kernels" into a row of 25x5 weights
W1_row4 = tf.concat(0, W1_c[20:25])  # [25, 5, 1, 1]
# Concatenate the five 25x5 rows into a 25x25 grid. In this grid, each "kernel" is now a 5x5 square.
W1_d = tf.concat(1, [W1_row0, W1_row1, W1_row2, W1_row3, W1_row4]) # [25, 25, 1, 1]
# Reshape as a batch of N images (with N=1). Each image is 5x5 pixels and 1 color channel (b&w)
W1_e = tf.reshape(W1_d, [1, 25, 25, 1])
# name this visulaization
Wtag = tf.placeholder(tf.string, None)
# output as a "summary" visible in Tensorboard.
tf.image_summary(Wtag, W1_e)
