### ISSUE TITLE
Support for nvidia-cuda-mps-server 

### ISSUE THREAD

**Issue by elefthei** [tensorflow/tensorflow#9080]
I'm experimenting with multiple Tensorflow GPU processes and the NVIDIA Multi-Process Server. 
https://docs.nvidia.com/deploy/pdf/CUDA_Multi_Process_Service_Overview.pdf

I have the following MNIST example as a benchmark (neural.py)

```
import tensorflow as tf
import os

from tensorflow.examples.tutorials.mnist import input_data
data = input_data.read_data_sets('MNIST_data_%d' % os.getpid(), one_hot=True)

# construction phase
x = tf.placeholder(tf.float32, shape=[None, 784])
y = tf.placeholder(tf.float32, shape=[None, 10])

with tf.name_scope('fc_1'):
  W1 = tf.Variable(tf.truncated_normal([784, 200], stddev=0.1))
  b1 = tf.Variable(tf.truncated_normal([200], stddev=0.1))
  h = tf.sigmoid(tf.matmul(x, W1) + b1)

with tf.name_scope('fc_2'):
  W2 = tf.Variable(tf.truncated_normal([200, 10], stddev=0.1))
  b2 = tf.Variable(tf.truncated_normal([10], stddev=0.1))
  y_predict = tf.nn.softmax(tf.matmul(h, W2) + b2)

with tf.name_scope('eval'):
  with tf.name_scope('loss'):
    cross_entropy = tf.reduce_mean(-tf.reduce_sum(y*tf.log(y_predict), reduction_indices=[1]))

learning_rate = 0.5

backprop = tf.train.GradientDescentOptimizer(learning_rate).minimize(cross_entropy)

correct = tf.equal(tf.argmax(y, 1), tf.argmax(y_predict, 1))
accuracy = tf.reduce_mean(tf.cast(correct, tf.float32))

#execution

sess = tf.Session()

sess.run(tf.initialize_all_variables())

train_steps = 2000
batch_size = 50

for i in range(train_steps):
  batch_x, batch_y = data.train.next_batch(batch_size)
  sess.run(backprop, feed_dict={x: batch_x, y: batch_y})

print(sess.run(accuracy, feed_dict={x: data.test.images, y: data.test.labels}))
```

And I'm running two processes like this:
`$ time python neural.py &
     time python neural.py
`

Without `nvidia-cuda-mps-control` running as a daemon, this is the output:
```
0.9483
0.947

real    0m15.602s
user    0m6.172s
sys     0m5.092s

real    0m15.861s
user    0m6.288s
sys     0m1.964s
```

With `nvidia-cuda-mps-control` running as a daemon, I'm getting an internal error:

```
F tensorflow/core/common_runtime/gpu/gpu_device.cc:121] Check failed: err == cudaSuccess (71 vs. 0)
F tensorflow/core/common_runtime/gpu/gpu_device.cc:121] Check failed: err == cudaSuccess (71 vs. 0)
-bash: line 76: 47018 Aborted                 (core dumped) python neural.py
```

I can verify from the nvidia-mps logs in /var/log/nvidia-mps that the tensorflow Cuda context successfully started an nvidia-cuda-mps-server and connected to it.

**/var/log/nvidia-mps/control.log**
> [2017-04-09 10:05:09.539 Control 46322] Start
> [2017-04-09 10:05:21.023 Control 46322] Accepting connection...
> [2017-04-09 10:05:21.024 Control 46322] NEW CLIENT 46325 from user 1000: Server is not ready, push client to pending list
> [2017-04-09 10:05:21.024 Control 46322] Starting new server 46348 for user 1000

The MPS server should be compatible with the Cuda API which Tensorflow uses, so I'm uncertain about why I'm getting this error.

**Tensorflow version: 1.01**
**Ubuntu 16.04**
**Cuda 8.0, CuDNN**

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.39                 Driver Version: 375.39                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 8915:00:00.0     Off |                  Off |
| N/A   51C    P8    28W / 149W |     82MiB / 12205MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

**Comment by elefthei** [comment]
I investigated this a bit, it appears calling:

`tensorflow/core/common_runtime/gpu/gpu_device.cc:    cudaError_t err = cudaStreamAddCallback(*stream_, asyncFree, afData, 0);`

Gives an error 71 

> cudaErrorNotSupported = 71
> This error indicates the attempted operation is not supported on the current system or device.
> 

Read more at: http://docs.nvidia.com/cuda/cuda-runtime-api/index.html#ixzz4eAO2YpQp 

I think this is probably from MPS since I run the same program on single process Cuda and `cudaStreamAddCallback` passes without errors. It seems thats the only place
that `cudaStreamAddCallback` is called inside the whole tensorflow project, maybe can we find an MPS friendly implementation for `deallocate`.

**Comment by asimshankar** [comment]
We currently don't have anybody working on this. It would be great if you could help us by working on this and submitting a PR. Let us know if you need further clarification. Thanks!

(FYI @zheng-xq )

**Comment by eth-n** [comment]
I'm just beginning to learn about MPS now. One thing I noticed in your above code is that you're running the same job twice concurrently with '&', but not limiting the space that each job can take on the GPU, as referenced here: https://www.tensorflow.org/tutorials/using_gpu#allowing_gpu_memory_growth. I'll be looking into this sort of use case as I learn more about MPS. :)

**Comment by waynesuzq** [comment]
@eth-n hi, I am also struggling with this problem. With `nvidia-cuda-mps-control` running as a daemon, I start a single tensorflow training, it gives me the same error.  T-T
Thanks~

**Comment by eth-n** [comment]
@waynesuzq wow, if it doesn't even work with a single context, it sounds like a problem with MPS like @elefthei said.

By the way, I just ran into this GTC presentation with CUDA profiling tools from a few years back (introducing what's new in CUDA 6.0). Maybe some of the described tools could help someone visualize where their conflicts occur? http://www.sie.es/wp-content/uploads/2015/12/cuda-profiling-tools.pdf

@asimshankar, I may peer into the depths of session initialization on the gpu in the source code sometime to try and get a sense of what's happening. I haven't gone looking yet, but any tips where to go first? Thanks :)

**Comment by waynesuzq** [comment]
@eth-n Hi, quoting from MPS guide book:
"Stream callbacks are not supported. Calling any stream callback APIs will return an error."
Do you think this is the reason for Tensorflow not working? I tried caffe, it works well. But I just take a guess, coz I didn't really read through the code. Thanks for the reply.

**Comment by elefthei** [comment]
@waynesuzq is correct, stream callbacks are not supported. I'm working on
an MPS compatible PR.

**Comment by elefthei** [comment]
Lack of CUDA streams creates some issues, like single stream per TF session
with MPS handling most of the optimizations. My best guess is this will be
faster for multi-process (i.e. MPI) but slower for single process
tensorflow use cases.

**Comment by elefthei** [comment]
Alright, here's my report:
 
**Cuda streams are used everywhere in Tensorflow.** 

For BLAS (tensorflow/stream_executor/cuda/cuda_blas.cc)
For DNN (tensorflow/stream_executor/cuda/cuda_dnn.cc)
For everything else (tensorflow/stream_executor/cuda/cuda_gpu_executor.cc)

So yeah, good luck with that. Cuda streams are like operation queues, so they are used throughout as the parallelization semantics for running multiple cuda operations concurrently in Tensorflow. It will require somebody to rewrite _all_ of the Cuda code to be MPS compatible.

**Comment by waynesuzq** [comment]
@elefthei Thanks man, I have read NVIDIA new GPU Volta white paper, it seems each client of Volta MPS has its own independent address space. 
I don't know if this will solve our problem, but worth trying.

**Comment by nsmetanin** [comment]
Just figured out that building tensorflow (1.2.1) **from source** with pretty much all configure options set to default solves this problem. My intuition is that the problem was caused by default allocator in tensorflow from pip package, but when you build it from source, it enables jemalloc by default (I've not reviewed this a lot).

Now it works flawlessly through NVIDIA MPS, but I couldn't get any performance gain for my inference tasks (mostly RNN-based), only slight speed decrease ~10%.

**Comment by elefthei** [comment]
Could you try a multiprocess scenario? Something like:

```
stresstest() {
for i in {1..100}; do
   python tf_example.py &
done
}
```
# With MPS enabled
`time stresstest`

# With MPS disabled
`time stresstest`
```

**Comment by nsmetanin** [comment]
I've tested it in multiprocess environment — 3-4 instances of the same process per GPU, each with sufficient amount of GPU memory, all under simultaneous high load (each process handle requests by several GPU inference calls alternating with calculations on CPU), it's actually a LSTM-based dialog model in a nutshell. All the difference was in running it thought MPS or not and I've got ~10% performance decrease on a MPS-enabled configuration.

But I didn't benchmark any training tasks (I don't actually think you could benefit from MPS at training time, but who knows) and any other models (like CNN-based, inception v3 i.e). 

So my advice is to try MPS by your own (building TensorFlow from sources isn't THAT scary as it looks like :) at your own tasks, because I think results may be very different.

**Comment by joshsuihn** [comment]
Stream callbacks are not supported on pre-Volta MPS clients. MPS with Tensorflow may need to be tried on volta using cuda9 later.

**Comment by ulto777** [comment]
I've tried with the latest TensorFlow 1.6 (require CUDA 9) on 1080ti GPU and it works.

**Comment by elefthei** [comment]
Awesome, two people confirmed it worked with Cuda 9 for them on Volta, may as well close this.

**Comment by vykozlov** [comment]
Hi, googling ends up on this page, also pointing it should work on new Volta architectures. In my experience it does NOT. My exp setup:

1.) AWS instance p3.2xlarge with Nvidia V100
2.) Ubuntu 16.04 with CUDA 9.2 and Driver 396.37
3.) nvidia-docker: Docker version 18.09.0, build 4d60db4
4.) start MPS by $ sudo nvidia-cuda-mps-control -d
5.) running nbody example from CUDA works fine with MPS: can be run in parallel if same user
6.) have own Docker image with Tensorflow 1.8.0 (GPU) and CUDA 9.0.176, where Dockerfile starts with 
FROM tensorflow/tensorflow:1.8.0-gpu
7.) Trying to run two instances of this image with CNN scripts inside via
$ docker run --ipc=host --runtime=nvidia --rm -ti  dockerimage python ./cnn_tf_script.py
**fails.** (N.B.: one instance works fine)

- Does it mean that by default Tensorflow (1.8.0) still does not work with MPS and Volta cards? 
- And anyway one has to install Tensorflow from sources to make it working with MPS (even when Volta GPU card is used)?

**Comment by GoodJoey** [comment]
@ulto777 did you get any performance gain with mps on 1080ti?
