### ISSUE TITLE
cpp protobuf instructions out-of-date for MacOS

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#9089]
Instructions to upgrade to cpp protobuf implementation on Mac from https://www.tensorflow.org/install/install_mac#protobuf_pip_package_31 don't work work, makes TF fails with following stacktrace

```
Traceback (most recent call last):
  File "kronecker_benchmark.py", line 3, in <module>
    import tensorflow as tf
  File "/Users/yaroslav/anaconda/envs/mar1/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/yaroslav/anaconda/envs/mar1/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 54, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/yaroslav/anaconda/envs/mar1/lib/python3.5/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/yaroslav/anaconda/envs/mar1/lib/python3.5/site-packages/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: dlopen(/Users/yaroslav/anaconda/envs/mar1/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-darwin.so, 2): Library not loaded: /usr/local/lib/libprotobuf.10.dylib
  Referenced from: /Users/yaroslav/anaconda/envs/mar1/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-darwin.so
  Reason: image not found

```

Work-around is to use older link:
pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/protobuf-3.1.0-cp35-none-macosx_10_11_x86_64.whl

Check that it works
`python -c "from google.protobuf.internal import api_implementation; print(api_implementation._default_implementation_type)"
`

MacOS: 10.12.4 (16E195), TensorFlow, latest nightly from today installed as:
`pip install --upgrade https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=mac-slave/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-1.1.0rc1-py3-none-any.whl
`

**Comment by asimshankar** [comment]
@jhseu : Any suggestions for the appropriate update here?

**Comment by jhseu** [comment]
Sent a fix for the links in the docs (internally, should be reflected soon).

Also filing a request with the protobuf team to upload optimized mac builds to pypi.
