### ISSUE TITLE
tf.train.Saver undeterministic behaviour on writing events

### ISSUE THREAD

**Issue by krisjobs** [tensorflow/tensorflow#9090]
Hey guys!

I have been banging my head for a couple of days with the following:

I am using a MonitoredTrainingSession with a single local server (but bug is identical even if using Supervisor and/or distributed architecture).

`#...
sess  = tf.train.MonitoredTrainingSession(...)\
while True:\
   sess.run(train_op)`

Assuming sequential runs of the python client without changing a single line of code,  the problem is that I sometimes get the error: 
`Tensorflow.python.framework.errors_impl.FailedPreconditionError: Failed to rename: .../graph.pbtxt.tmp23e44d8fdce844e6822a56dc886588e6 to: .../graph.pbtxt : The process cannot access the file because it is being used by another process.`

... and the interesting thing is that sometimes this does not occur and training begins, but it then happens just as the first before_run call of the checkpoint hook tries to save the initial state (as seen in the MonitoredSession source code): 

`Failed to rename: .../model.ckpt-1_temp_4fcb775402bc44568b86836d94747b27/part-00000-of-00001.data-00000-of-00001.tempstate17529973146728747180 to: .../model.ckpt-1_temp_4fcb775402bc44568b86836d94747b27/part-00000-of-00001.data-00000-of-00001 : The process cannot access the file because it is being used by another process.`

**Comment by bachhavpramod** [comment]
I was stuck from 2 days because of this stupid error before I found this post. Thank you very much for the solution.

**Comment by rbowden91** [comment]
Thank you!!!!!!!

**Comment by BrazilForever11** [comment]
What about google drive? Does it work if saving to google drive?

**Comment by yusisc** [comment]
I met the same issue.
```
FailedPreconditionError (see above for traceback): Failed to rename: ./logs/checkpoints/model_epoch-1.data-00000-of-00001.tempstate9288023132477748030 to: ./logs/checkpoints/model_epoch-1.data-00000-of-00001 : The process cannot access the file because it is being used by another process.
; Broken pipe
	 [[Node: save/SaveV2 = SaveV2[dtypes= ... ...
```
I did not sync this project with any online drive.

**I my case, It's `git` reading that file content.** So that file cannot be renamed. I added `logs/` to `.gitignore`, this error was fixed.

**Comment by seeiespi** [comment]
O.M.G. lol, I had a sneaking suspicion that it was dropbox but didn't want to admit it to myself

**Comment by john3-16** [comment]
I get this error using plain file system so what gives?

**Comment by CT83** [comment]
1. Shutdown every backup service, **MEGA**, **DropBox**, **GoogleDrive**. 
2. Add to `.gitignore`

**Comment by grldsndrs** [comment]
This is apparently a problem with OneDrive as well.

**Comment by mathsten** [comment]
@grldsndrs And Google Drive :))

**Comment by allen90132** [comment]
NICE!!!!! It's work

**Comment by rghods** [comment]
what a relief!!! had the same problem. selectively not syncing the folder you are saving in works!

**Comment by tocab** [comment]
I had the error without saving weights to a cloud service. I use PyCharm what is indexing new files, so maybe the error occured because of that in my case.

**Comment by robbystew** [comment]
JFC. Thank you for posting this.

**Comment by Dominic-1999** [comment]
> I was stuck from 2 days because of this stupid error before I found this post. Thank you very much for the solution.

whats the solution

**Comment by CalRiley** [comment]
Wow this saved me so much time. After hours of putting together this model just running into this error knowing it should be working was so frustrating. pausing my dropbox sync did the job. now moving all my docs away from dropbox...

**Comment by nicoloceneda** [comment]
Dropbox works perfectly fine on Mac, OneDrive not working on Windows
