### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of undefined when use TensorBoard projector

### ISSUE THREAD

**Issue by Aetf** [tensorflow/tensorflow#9094]
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*: Yes. I was training a tree based network using Tensorflow Fold to train word embeddings for SQL parse tree. But this shouldn't be a problem because the TensorBoard can correctly read the checkpoint file.
- *TensorFlow installed from (source or binary)?*: binary (installed using pip)
- *TensorFlow version*: 1.0.0
- *Bazel version (if compiling from source)*: N/A
- *CUDA/cuDNN version*: N/A
- *GPU Model and Memory*: CPU only
- *Exact command to reproduce*:

  * Open the log folder [tflogs.zip](https://github.com/tensorflow/tensorflow/files/908728/tflogs.zip) using TensorBoard (Seems the absolute path is hardcoded in the checkpoint file, the absolute path should be `/tmp/workspace/tflogs`):
`tensorboard --logdir=tflogs`
  * Switch to embedding tab
  * Enable 3D label on the top left corner of the projector

### Describe the problem clearly
Before enabling 3D label
![image](https://cloud.githubusercontent.com/assets/1519759/24842868/0194f2ec-1d6b-11e7-8786-9f83737d99d0.png)

After enabling 3D label
![image](https://cloud.githubusercontent.com/assets/1519759/24842880/18ed6f32-1d6b-11e7-9cfc-81281a074217.png)

Expected result: label shown
Actual result: the projector becomes blank, while the following error shown in the js console:
```
Uncaught TypeError: Cannot read property 'toString' of undefined
    at ProjectorScatterPlotAdapter.getLabelText (tf-tensorboard.html:20587)
    at ProjectorScatterPlotAdapter.generate3DLabelsArray (tf-tensorboard.html:20582)
    at ProjectorScatterPlotAdapter.createVisualizers (tf-tensorboard.html:20613)
    at ProjectorScatterPlotAdapter.set3DLabelMode (tf-tensorboard.html:20245)
    at HTMLElement.<anonymous> (tf-tensorboard.html:24813)
ProjectorScatterPlotAdapter.getLabelText @ tf-tensorboard.html:20587
ProjectorScatterPlotAdapter.generate3DLabelsArray @ tf-tensorboard.html:20582
ProjectorScatterPlotAdapter.createVisualizers @ tf-tensorboard.html:20613
ProjectorScatterPlotAdapter.set3DLabelMode @ tf-tensorboard.html:20245
(anonymous) @ tf-tensorboard.html:24813
```

**Comment by asimshankar** [comment]
CC @dandelionmane @jart

**Comment by wchargin** [comment]
Thank you for reporting, and thank you for the repro data and tracebacks!

I've migrated this to our new repository at https://github.com/tensorflow/tensorboard/issues/71.
