### ISSUE TITLE
Android: Invalid argument: No OpKernel was registered to support Op 'PaddingFIFOQueue' with these attrs

### ISSUE THREAD

**Issue by zgq91** [tensorflow/tensorflow#9097]
I encountered a problem when using a multibox model to make inference on android platform (using c++ api, just like the android demo). The error says something like this:

tensorflow_jni.cc:361 Error during inference: Invalid argument: No OpKernel was registered to support Op 'PaddingFIFOQueue' with these attrs
                                                                       	 [[Node: prefetch_queue = PaddingFIFOQueue[capacity=500, component_types=[DT_FLOAT, DT_FLOAT, DT_BOOL, DT_UINT8, DT_STRING, DT_INT64], container="", shapes=[[-1], [-1,4], [-1], [-1,-1,3], [], [-1]], shared_name=""]()]]

**Comment by jart** [comment]
Thanks for reaching out. We try to keep this issue tracker limited to bugs and feature requests. We recommend posting on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) for community-driven support. We also ask that people fill out the requested information in the issue template.

**Comment by andrewharp** [comment]
@zgq91 If you build with -D__ANDROID_TYPES_FULL__ does this solve your problem? By default int64 is not supported on mobile to reduce binary size.

I'd also try updating to the latest TF, as it sounds like you're an older version (we switched from the C++ API to the Java api a few months ago).
