### ISSUE TITLE
import six.moves.copyreg as copyreg error

### ISSUE THREAD

**Issue by Congee** [tensorflow/tensorflow#91]
ENV: Mac OS X 10.10, System shipped Python 2.7, six 10.10.0
In this file, I need to replace `import six.moves.copyreg as copyreg` with `from six.moves import copyreg`
/Library/Python/2.7/site-packages/google/protobuf/internal/python_message.py

**Comment by ebrevdo** [comment]
Our current suggestion for dealing with incompatible versions of six is to either use a brew install of python, or install the tensorflow package inside a virtualenv.  The virtualenv will guarantee that you install and see the correct version of six.  See [common problems](http://tensorflow.org/get_started/os_setup.md#common_install_problems)

**Comment by Congee** [comment]
Thanks for your advice. :D

**Comment by samin-batra** [comment]
When I try to run the classify_image.py file, it shows an error that six.moves module is not found, even though I have the latest version of the module 'six' installed.
Can anyone help?
