### ISSUE TITLE
Error downloading jpegsrc.v9a.tar.gz

### ISSUE THREAD

**Issue by markusdr** [tensorflow/tensorflow#910]
I'm getting the following build error:

    $ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
    ERROR:  tensorflow/tensorflow/core/platform/default/build_config/BUILD:36:1: 
    no such package '@jpeg_archive//': 
    Error downloading from http://www.ijg.org/files/jpegsrc.v9a.tar.gz

It turns out that bazel cannot download directly from the `ijg.org` in my network, due to security restrictions. However, I am able to download the file by hand. 

I tried just putting it into the required `.cache/bazel` location by hand and run the bazel command again. This used to work, but it won't work in the latest version, and the same error comes up again.

Would it be possible to enable bazel to pick up a locally downloaded `jpegsrc.v9a.tar.gz` file?

Or, if I don't work on JPEGs, how do I get rid of this dependency altogether?

**Comment by vrv** [comment]
Can you file this bug with bazel and mention this bug?  bazel team is much more suited to helping you in this case.
