### ISSUE TITLE
Why `tf.nn.nce_loss` cannot run on GPU?

### ISSUE THREAD

**Issue by ogerhsou** [tensorflow/tensorflow#9101]
The code `tensorflow/examples/tutorials/word2vec/word2vec_basic.py` has a comment `# Ops and variables pinned to the CPU because of missing GPU implementation`.  I have also found that the operation `tf.nn.nce_loss` cannot be implemented by GPU. So why `tf.nn.nce_loss` cannot run on GPU?  My guess is the `log_uniform_candidate_sampler` cannot run on GPU. But I still don't know which part of it cause this problem. 

Tensorflow version: 1.0.1
CUDA version: 7.5
GPU: Tesla K40c

**Comment by drpngx** [comment]
To debug issues with device placement, use [`log_device_placement`](https://www.tensorflow.org/tutorials/using_gpu#logging_device_placement). This is more of a usage question that is best answered on stackoverflow in the future.
