### ISSUE TITLE
RNN Tutorial references defunct library

### ISSUE THREAD

**Issue by agribov** [tensorflow/tensorflow#9110]
[In the RNN tutorial](https://www.tensorflow.org/tutorials/recurrent), the sample code has line:

`lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)`

According to issue #6432, this should be replaced by:

`lstm = tf.nn.rnn_cell.BasicLSTMCell(lstm_size)`

**Comment by asimshankar** [comment]
The tutorials are meant to be in sync with the latest release. It does seem that `tf.contrib.rnn.BasicLSTMCell` exists in the 1.0 release.

Is it not working for you?

**Comment by agribov** [comment]
Sorry, you're right. Looks like I'm running 0.10.0! Thought I had installed the latest version.
