### ISSUE TITLE
tensorflow installation issue

### ISSUE THREAD

**Issue by wenouyang** [tensorflow/tensorflow#9111]
I have been following the [Tensorflow installation guide](https://www.tensorflow.org/install/install_linux#InstallingVirtualenv) to install tensorflow r.1.0. Since out network system does not have direct internet access to outside, so I installed it as following in the active virtualenv environment

```
(virtualenv-test) bash-4.1$ pip3 install -t --upgrade /data/pythonlibs/tensorflow-1.0.1-cp34-cp34m-linux_x86_64.whl
Processing /data/dsp_emerging/ugwz/pythonlibs/tensorflow-1.0.1-cp34-cp34m-linux_x86_64.whl
```
However, I got the following error message, what does it mean?

> Collecting six>=1.10.0 (from tensorflow==1.0.1)
>   Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b623e22bcc0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/six/
>   Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b623e22bd68>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/six/
>   Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b623e113fd0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/six/
>   Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b623e115358>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/six/
>   Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x2b623e115438>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/six/
>   Could not find a version that satisfies the requirement six>=1.10.0 (from tensorflow==1.0.1) (from versions: )
> No matching distribution found for six>=1.10.0 (from tensorflow==1.0.1)
>

**Comment by jart** [comment]
Thanks for reaching out. We try to keep this issue tracker limited to bugs and feature requests. We recommend posting on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) for community-driven support.

**Comment by Carmezim** [comment]
Hi @wenouyang, please provide all the info the template requires, it helps us better asses what is happening and solve the problem. 
Pip is trying to download the package `six` and probably due your absence of internet connection TensorFlow is not successfully installing.

**Comment by wenouyang** [comment]
thanks
