### ISSUE TITLE
Documentation link issue

### ISSUE THREAD

**Issue by rkc9** [tensorflow/tensorflow#9115]
NOTE: Issues that are not bugs or feature requests will be closed. Please ask usage questions on StackOverflow.
under this link 
https://www.tensorflow.org/api_docs/python/tf/contrib/deprecated/scalar_summary

the webpage is not found 

https://www.tensorflow.org/code/tensorflow/contrib/deprecated/__init__.py

### You must complete this information or else your issue will be closed
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*:
- *TensorFlow installed from (source or binary)?*:
- *TensorFlow version*:
- *Bazel version (if compiling from source)*:
- *CUDA/cuDNN version*:
- *GPU Model and Memory*:
- *Exact command to reproduce*:

### Source Code / Logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full-traceback. Large logs and files should be attached. Try to reproducible test-case code the bare-minimum necessary to generate the problem

**Comment by jart** [comment]
@craigcitro The tensorflow.org/code/... redirector service seems to return 404 for valid `__init__.py` paths. Could App Engine be intercepting those requests?

**Comment by craigcitro** [comment]
Ooh, this is an interesting one. My current hypothesis: app engine routing doesn't like path segments with a leading underscore, maybe an overzealous check for routes like `_ah`?

Another failing sample url: https://www.tensorflow.org/code/tensorflow/contrib/labeled_tensor/python/ops/_typecheck.py fails to route to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/labeled_tensor/python/ops/_typecheck.py.

I'm going to file an internal bug to find out more. (I couldn't turn anything up in a Google search.)

**Comment by wolffg** [comment]
I believe that's an internal issue to our docs hosting system.  We'll look into it.  Thanks.

**Comment by wolffg** [comment]
As of now, those links are rewritten to point to github.com/ links, although pre-v1.1 documentation will not  be updated. So, on the scalar_summary page, it now points to:

https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/contrib/deprecated/__init__.py
