### ISSUE TITLE
How to run TF learn (skflow) Kmeans clustering in multi-machine multi-gpu environment?

### ISSUE THREAD

**Issue by mahatosourav91** [tensorflow/tensorflow#9126]
Is there any example / guide which shows how to implement skflow(tf.contrib.learn) in distributed GPUs? For example :- I want to implement KMeansClustring using skflow(tf.contrib.learn) in a distributed GPU environment. How should I proceed?

Stackoverflow questions :- [here](http://stackoverflow.com/questions/43339285/how-to-run-tf-learn-skflow-kmeans-clustering-in-multi-machine-multi-gpu-enviro)  and [here](http://stackoverflow.com/questions/42516334/implement-skflowtf-contrib-learn-in-a-distributed-gpu-environment)

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
