### ISSUE TITLE
Problem with label_image.py 

### ISSUE THREAD

**Issue by swammaws** [tensorflow/tensorflow#9128]
I used docker toolbox on windows 10 64-bit and used this command 
docker run -it gcr.io/tensorflow/tensorflow:latest-devel  
to install tensorflow image. 
After retraining of model is successfully done and when I run label_image.py it gives following message
![capture](https://cloud.githubusercontent.com/assets/20141573/24899312/27d5b654-1ea0-11e7-8df6-517c4df18bfb.PNG)

I used this line 
curl -L https://goo.gl/tx3dqg > $HOME/tf_files/label_image.py
and then
docker run -it -v $HOME/tf_files:/tf_files  gcr.io/tensorflow/tensorflow:latest-devel 

NOTE: Issues that are not bugs or feature requests will be closed. Please ask usage questions on StackOverflow.

### You must complete this information or else your issue will be closed
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*:
- *TensorFlow installed from (source or binary)?*:
- *TensorFlow version*:
- *Bazel version (if compiling from source)*:
- *CUDA/cuDNN version*:
- *GPU Model and Memory*:
- *Exact command to reproduce*:

### Source Code / Logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full-traceback. Large logs and files should be attached. Try to reproducible test-case code the bare-minimum necessary to generate the problem

**Comment by asimshankar** [comment]
From the error message, it seems that somehow your `label_image.py` file is corrupt (and contains `<HTML>` in it). Please confirm the contents of `label_image.py` are correct.

**Comment by swammaws** [comment]
Thanks for your reply. Yes I found out that somehow the curl wasn't able to put code in the file. I copied and pasted from the site  and now its fine.
