### ISSUE TITLE
First assignment on Google Deep Learning, Exception raised on download

### ISSUE THREAD

**Issue by nishasraj** [tensorflow/tensorflow#913]
This is the first time taking a course on udacity. With atmost interest opened up the first assignment and ended up in Exception:
The screenshot attached
![screenshot from 2016-01-28 10 17 30](https://cloud.githubusercontent.com/assets/16772566/12635403/c45f8344-c5a8-11e5-9aa2-bb641a451d60.png)

**Comment by vincentvanhoucke** [comment]
This is not the best place to ask questions about the class. In this case, delete the file and try to download it again. You can also try to download it from the website manually and see if that succeeds.
