### ISSUE TITLE
"undefined symbol" when compiling the example Op

### ISSUE THREAD

**Issue by idofr** [tensorflow/tensorflow#9137]
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*: No
- *TensorFlow installed from (source or binary)?*: binary
- *TensorFlow version*: 1.0.1
- *Bazel version (if compiling from source)*: NA
- *CUDA/cuDNN version*: NA
- *GPU Model and Memory*: NA
- *Exact command to reproduce*: 

### Describe the problem clearly
Trying to build and compile the example in "adding a new op"
https://www.tensorflow.org/extend/adding_an_op
This was moved to
tensorflow/examples/adding_an_op
and was not updated in the tutorial page.
After compiling the zero_out_op_kernel_1.cc example, I'm trying to run the zero_out_1_test.py. Yet this returns the following error

  File "zero_out_1_test.py", line 25, in <module>
    import zero_out_op_1
  File "/home/me/tf_compile/tensorflow/tensorflow/examples/adding_an_op/zero_out_op_1.py", line 26, in <module>
    'zero_out_op_kernel_1.so'))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /home/me/tf_compile/tensorflow/tensorflow/examples/adding_an_op/zero_out_op_kernel_1.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev

Any ideas what could that symbol be?

**Comment by jart** [comment]
I tried the example with 1.0.1 and it worked for me. You might be using an unsupported operating system which has a weird version of GCC. We support Ubuntu Linux 14 LTE to 16. Mac OS X El Capitan. CentOS 7 and above.

**Comment by idofr** [comment]
I'm using Ubuntu 16 with GCC 5.
Could it be that one of the headers was not compiled correctly?

**Comment by jart** [comment]
Interesting. So you installed the TensorFlow binary distro, which was probably built using GCC 4.x. Then compiled a custom op using GCC 5.x. Out of curiosity, could you try apt-get installing the GCC 4.x series and see if it works? If so, then I might want to bring to the attention of some other people that a binary compatibility problem exists.

**Comment by idofr** [comment]
Sure, thanks for the quick response. I'll give it a try either tonight or tomorrow at some point and will let you know

**Comment by shashankneocfc** [comment]
I've the exact same problem. We've defined our own custom op and our code works successfully with tensorflow 0.12.1 and it crashes with the above error with tensorflow 1.0.0. I'm using Ubuntu 16 with gcc version 5.4.
@idofr  Did your problem get solved with gcc 4 ?

**Comment by jart** [comment]
@shashankneocfc Thanks for reporting back with the solution.

It turns out we have the magic incantation `-D_GLIBCXX_USE_CXX11_ABI=0` in our [pip installation](https://www.tensorflow.org/install/install_sources#install_the_pip_package) and [adding an op](https://www.tensorflow.org/extend/adding_an_op) documentation. Those error messages are really worrisome, but I'm not sure what we can do to make this easier for users.

**Comment by Afzal786** [comment]
I am facing this problem while adding a custom ops. 

lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/afzal786/PycharmProjects/multi/venv/lib/python3.6/site-packages/multidim_image_augmentation/python/ops/_augmentation_ops.so: undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev

undefined symbol: _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringB5cxx11Ev
gcc and ubuntu version:
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

TensorFlow version 2.2.0
