### ISSUE TITLE
Issues found by PVS-Studio

### ISSUE THREAD

**Issue by VasilievSerg** [tensorflow/tensorflow#9138]
Hello,
Developers of PVS-Studio C/C++/C# static analyzer present their check report of the source code of 'TensorFlow' in the article, containing the review of the most suspicious code fragments they discovered.

You can read article at the official site:
https://www.viva64.com/en/b/0497/

I have provided links to GitHub for each code fragment to make viewing more comfortable. The article doesn't cover all the issues that were found by the analyzer, so perhaps it would be interesting for you to review them yourself. In case you have questions, feel free to ask them.

Best regards,
Sergey Vasiliev

**Comment by VasilievSerg** [comment]
The article contains links to source files but not to the defined code lines. Here are the correct links:

- PVS-Studio warning V595. [A link to the source code.](https://github.com/tensorflow/tensorflow/blob/c7b80d51da4fb6d51ea54a0bdf2601afa379d60c/tensorflow/core/common_runtime/function.cc#L1044)
- PVS-Studio warning V547. [A link to the source code.](https://github.com/tensorflow/tensorflow/blob/c7b80d51da4fb6d51ea54a0bdf2601afa379d60c/tensorflow/core/distributed_runtime/master_session.cc#L1114)
- PVS-Studio warning V581. [A link to the source code.](https://github.com/tensorflow/tensorflow/blob/bbe056e5a0ab81b67fcb6053400812b3d5805fc7/tensorflow/contrib/rnn/kernels/lstm_ops.h#L284)
- PVS-Studio warning V760. [A link to the source code.](https://github.com/tensorflow/tensorflow/blob/bbe056e5a0ab81b67fcb6053400812b3d5805fc7/tensorflow/core/kernels/encode_jpeg_op.cc#L56)
- PVS-Studio warning V629. [A link to the source code.](https://github.com/tensorflow/tensorflow/blob/bbe056e5a0ab81b67fcb6053400812b3d5805fc7/tensorflow/contrib/tensor_forest/hybrid/core/ops/unpack_path_op.cc#L55)
- PVS-Studio warning V592. [A link to the source code.](https://github.com/tensorflow/tensorflow/blob/bbe056e5a0ab81b67fcb6053400812b3d5805fc7/tensorflow/core/lib/strings/strcat.cc#L43)
- PVS-Studio warning V519. [A link to the source code.](https://github.com/tensorflow/tensorflow/blob/bbe056e5a0ab81b67fcb6053400812b3d5805fc7/tensorflow/core/kernels/resize_area_op.cc#L174)
- PVS-Studio warning V614. [A link to the source code.](https://github.com/tensorflow/tensorflow/blob/eae70b8ee31d87bdfd339aecf05100f0a1633961/tensorflow/contrib/tensor_forest/kernels/sample_inputs_op.cc#L351)

**Comment by rmlarsen** [comment]
As far as I can tell, these are either style issues (e.g. not using curly braces around single statement if clause), and some mixing of signed and unsigned in cases were it is safe (from the context), such at

unsigned = 1 << unsigned -1 

where unsigned is known to be >= 0. Do you actually see anything alarming? Maybe I missed it.

**Comment by rmlarsen** [comment]
Closing issue, feel free to reopen if you spot some actual bugs.

**Comment by rmlarsen** [comment]
Looking more carefully, some of these findings do merit attention/cleanup. Thanks.

**Comment by maks-a** [comment]
> Do you actually see anything alarming?

it may get undefined behavior if the value returned by `c->Value(tree_depth)` is more than 31.
```cpp
#include <iostream>
using namespace std;

int main() {
  int64_t value[] = {31, 32};
  for (int i = 0; i < 2; ++i) {
    int64_t v = value[i];
    int64_t a = (1 << v) - 1;
    int64_t b = (1L << v) - 1;
    cout << "value: " << v << endl;
    cout << "a: " << a << endl;
    cout << "b: " << b << endl;
    cout << endl;
  }
  return 0;
}
```
That produces the following output:
```
value: 31
a: 2147483647
b: 2147483647

value: 32
a: 0
b: 4294967295
```
Explanation from the article:

> PVS-Studio warning: V629 Consider inspecting the '1 << c->Value(tree_depth)' expression. Bit shifting of the 32-bit value with a subsequent expansion to the 64-bit type. unpack_path_op.cc 55
> 
> The strangeness of this code is in the fact that the 32 and 64 bit values are mixed in the shift and assignment operations. The literal 1 is a 32-bit value, for which a left-side shift is performed. The result of the shift still has a 32-bit type, but is written to the 64-bit variable. It is suspicious, because we may get undefined behavior if the value returned by the Value method is more than 32.
> 
> Here is a quote from the standard: The value of E1 << E2 is E1 left-shifted E2 bit positions; vacated bits are zero-filled. If E1 has an unsigned type, the value of the result is E1 * 2^E2, reduced modulo one more than the maximum value representable in the result type. Otherwise, if E1 has a signed type and non-negative value, and E1*2^E2 is representable in the result type, then that is the resulting value; otherwise, the behavior is undefined.
> 
> This code can be fixed by writing 1 as a 64-bit literal or doing the type extension via casting. More details on the shift operations can be found in the article "Wade not in unknown waters. Part three".

**Comment by VasilievSerg** [comment]
Thanks @maks-a.

@rmlarsen , I would also like to note that I haven’t described in the article all the fragments that the analyzer considered to be suspicious. There were other warnings that I haven’t noted down. For example, V730 warning, that I mentioned in the article. I didn’t include such warnings in the article, because I am not very familiar with the code and it’s hard to say if the code contains an error, or if was written intentionally.

In any case it might be interesting for you to check the code yourself and have a look at the log. You can contact us by e-mail (support@viva64.com) to get a temporary license key.

**Comment by drpngx** [comment]
Will take a look this weekend

**Comment by drpngx** [comment]
Submitted CL internally. It should close automatically at the next push. Thanks for the write-up and reporting back to us!
