### ISSUE TITLE
label_image example failing due to missing types.h

### ISSUE THREAD

**Issue by jhludwig** [tensorflow/tensorflow#914]
```
In file included from tensorflow/examples/label_image/command_line_flags.cc:16:0:
./tensorflow/examples/label_image/command_line_flags.h:20:44: fatal error: tensorflow/core/platform/types.h: No such file or directory
 #include "tensorflow/core/platform/types.h"
```

there is no such file.  there is a `tensorflow/core/framework/types.h`

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/types.h

Are you properly synced?

**Comment by jhludwig** [comment]
ah i was 8 days ago or so...i see the changes...thanks and sorry for the noise.

**Comment by jhludwig** [comment]
actually my problem came down to the fact that the docker containers are all on the 0.6.0 release.  thus if you accidentally mix later examples with the 0.6.0 release of tensorflow, it doesn't work.
