### ISSUE TITLE
regarding error message of tensorflow_gpu-1.0.1-cp34-cp34m-linux_x86_64.whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by huaiyanggongzi** [tensorflow/tensorflow#9144]
I have created a Python development environment support Python 2.7,

```
(py2.7) [abcd@cluster1830 ~]$ python --version
Python 2.7.9
```
Then I was trying to install Tensorflow following [this guide ](https://www.tensorflow.org/install/install_linux#the_url_of_the_tensorflow_python_package)

> (py2.7) [abcd@cluster1830 ~]$ pip install --upgrade /data/pythonlibs/tensorflow_gpu-1.0.1-cp34-cp34m-linux_x86_64.whl
> tensorflow_gpu-1.0.1-cp34-cp34m-linux_x86_64.whl is not a supported wheel on this platform.
> (py2.7) [abcd@cluster1830 ~]$ pip install /data/pythonlibs/tensorflow_gpu-1.0.1-cp34-cp34m-linux_x86_64.whl
> tensorflow_gpu-1.0.1-cp34-cp34m-linux_x86_64.whl is not a supported wheel on this platform.
> (py2.7) [abcd@cluster1830 ~]$ pip2 install /data/pythonlibs/tensorflow_gpu-1.0.1-cp34-cp34m-linux_x86_64.whl
> tensorflow_gpu-1.0.1-cp34-cp34m-linux_x86_64.whl is not a supported wheel on this platform.
> 

None of the above options works, what can be the reason underlying this failure?

**Comment by asimshankar** [comment]
As per [the guide](https://www.tensorflow.org/install/install_linux#python_27), please use the URL for Python 2.7 and not 3.4: https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.1-cp27-none-linux_x86_64.whl

Alternatively, just use `pip install tensorflow`
