### ISSUE TITLE
`model_checkpoint_dir` in `ProjectorConfig` is not implemented

### ISSUE THREAD

**Issue by falcondai** [tensorflow/tensorflow#9147]
NOTE: Issues that are not bugs or feature requests will be closed. Please ask usage questions on StackOverflow.

### You must complete this information or else your issue will be closed
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*:
- *TensorFlow installed from (source or binary)?*:
- *TensorFlow version*:
- *Bazel version (if compiling from source)*:
- *CUDA/cuDNN version*:
- *GPU Model and Memory*:
- *Exact command to reproduce*:

### Describe the problem clearly
`model_checkpoint_dir` is defined in the [projector_config.proto](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/plugins/projector/projector_config.proto#L45) definition but currently, it is not functional. I believe there is missing logic in [tensorboard/plugins/projector/projector_plugin.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tensorboard/plugins/projector/projector_plugin.py): in fact, a quick search reveals that `model_checkpoint_dir` does not appear in source. There is good reason to support this (seemingly planned) feature as checkpoint files and summary event files are often saved under different directories. 

I would love to contribute a solution.

### Source Code / Logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full-traceback. Large logs and files should be attached. Try to reproducible test-case code the bare-minimum necessary to generate the problem

**Comment by jart** [comment]
@dsmilkov is the best person to comment on the timeline of opening up that functionality.

**Comment by falcondai** [comment]
@itsmeolivia i think this should be migrated to the tensorboard repo?
