### ISSUE TITLE
can not run mnistcnn.py, servers waiting for eachother 

### ISSUE THREAD

**Issue by renjiezhang** [tensorflow/tensorflow#9152]
Hello everyone, I tried to run this script on three AWS machines. One parameter server and two workers.
However, the ps is always in "Initializing session..." and workers always waiting for the ps.

I believe the challenge is from here: 
ps definitions:
flags.DEFINE_integer("worker_index", 0,
                     "Worker task index, should be >= 0. worker_index=0 is "
                     "the master worker task the performs the variable "
                     "initialization ")

flags.DEFINE_string("workers", "34.205.143.107:2222,54.83.142.82:2222",
                    "The worker url list, separated by comma (e.g. tf-worker1:2222,1.2.3.4:2222)")

flags.DEFINE_string("parameter_servers", "http://54.86.223.142:2222",
                    "The ps url list, separated by comma (e.g. tf-ps2:2222,1.2.3.5:2222)")

flags.DEFINE_string("worker_grpc_url", "grpc://54.86.223.142:2222",
                    "Worker GRPC URL (e.g., grpc://1.2.3.4:2222, or "
                    "grpc://tf-worker0:2222)")

worker definitions:
flags.DEFINE_integer("worker_index", 1,
                     "Worker task index, should be >= 0. worker_index=0 is "
                     "the master worker task the performs the variable "
                     "initialization ")

flags.DEFINE_string("workers", "34.205.143.107:2222,54.83.142.82:2222",
                    "The worker url list, separated by comma (e.g. tf-worker1:2222,1.2.3.4:2222)")

flags.DEFINE_string("parameter_servers", "http://54.86.223.142:2222",
                    "The ps url list, separated by comma (e.g. tf-ps2:2222,1.2.3.5:2222)")

flags.DEFINE_string("worker_grpc_url", "grpc://34.205.143.107:2222",
                    "Worker GRPC URL (e.g., grpc://1.2.3.4:2222, or "
                    "grpc://tf-worker0:2222)")
second worker
flags.DEFINE_integer("worker_index", 2,
                     "Worker task index, should be >= 0. worker_index=0 is "
                     "the master worker task the performs the variable "
                     "initialization ")

flags.DEFINE_string("workers", "34.205.143.107:2222,54.83.142.82:2222",
                    "The worker url list, separated by comma (e.g. tf-worker1:2222,1.2.3.4:2222)")

flags.DEFINE_string("parameter_servers", "http://54.86.223.142:2222",
                    "The ps url list, separated by comma (e.g. tf-ps2:2222,1.2.3.5:2222)")

flags.DEFINE_string("worker_grpc_url", "grpc://83.142.82:2222",
                    "Worker GRPC URL (e.g., grpc://1.2.3.4:2222, or "
                    "grpc://tf-worker0:2222)")
[mnistcnn.txt](https://github.com/tensorflow/tensorflow/files/915085/mnistcnn.txt)

We appreciate any assistance .

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
