### ISSUE TITLE
Docker Build Error

### ISSUE THREAD

**Issue by Vargnatt** [tensorflow/tensorflow#9153]
I am building tf dockerimages for both cuda 8.0 and 7.5 from source. But both cames error at bazel build procedure with message:

> The command '/bin/sh -c tensorflow/tools/ci_build/builds/configured GPU     bazel build -c opt --config=cuda tensorflow/tools/pip_package:build_pip_package &&     bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip &&     pip --no-cache-dir install --upgrade /tmp/pip/tensorflow-*.whl &&     rm -rf /tmp/pip &&     rm -rf /root/.cache' returned a non-zero code: 2

some times there would be an additional message like:

> ERROR: Evaluation of query "deps(((//tensorflow/... - //tensorflow/contrib/nccl/...) - //tensorflow/examples/android/...))" failed: errors were encountered while computing transitive closure

I cloned r1.1 branch and mainly followed the scripts in original dockerfile(devel-gpu version), with only python and cuda env modified. Also I found that original dockerfile would also meet same issue. 
I guess it might be caused by some download error when getting dependencies from bazel-mirror on googleapis. 
Is that possible to manually download those packages or try some alternative way like disable some function? Any hint?

**Comment by jart** [comment]
Was there more information that was logged?

**Comment by Vargnatt** [comment]
@jart I just searched building log for recent 3 times and find some timeout message when download and load some packages for bazel. These packages are always from `webcomponents` and `polymerelements` on github. I guess that could be the reason if these packages are essential for building.

**Comment by jart** [comment]
Can you copy and paste the actual errors?

**Comment by Vargnatt** [comment]
> ...
> ____Loading package: @jsoncpp_git//
> ____Timeout connecting to https://github.com/polymerelements/iron-icon/archive/v1.0.11.tar.gz
> ...

> ...
> ____Loading package: @numericjs_numeric_min_js//file
> ____Timeout connecting to https://github.com/webcomponents/webcomponentsjs/archive/v0.7.22.tar.gz
> ...

> ...
> ____Loading package: @jsoncpp_git//
> ____Timeout connecting to https://github.com/polymerelements/iron-icon/archive/v1.0.11.tar.gz
> ...

But I can download these packages via browser.
And after all download procedure the builder fails again with same message: 

> The command '/bin/sh -c tensorflow/tools/ci_build/builds/configured GPU     bazel build -c opt --config=cuda tensorflow/tools/pip_package:build_pip_package &&     bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/pip &&     pip --no-cache-dir install --upgrade /tmp/pip/tensorflow-*.whl &&     rm -rf /tmp/pip &&     rm -rf /root/.cache' returned a non-zero code: 2

If that is the real cause, could I just manually add them?

**Comment by jart** [comment]
Would you mind attaching a file with the full output of the commands you run?

**Comment by jart** [comment]
Those downloader warnings are actually ephemeral progress messages. The downloader appears to have been failing over or retrying correctly. So I'm curious if anything was outputted before you got that non-zero error code message.

**Comment by Vargnatt** [comment]
@jart 
I print the full log. Seems more error massage appears this time.

[log.txt](https://github.com/tensorflow/tensorflow/files/915473/log.txt)

**Comment by jart** [comment]
I see the error:

ERROR: [...] java.io.IOException: Error downloading [...] Tried to reconnect at offset 1,808,859 but server didn't support it and referenced by '@io_bazel_rules_closure//java/io/bazel/rules/closure/webfiles/server:listing'.

That error should be ephemeral and was fixed in https://github.com/bazelbuild/bazel/commit/0e866a8b732e31df1a4ddfd13c4870d4721de70b. Try retrying `./configure`.

For further support, please try [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow).
