### ISSUE TITLE
[Android Example] Demo does not perform well in low light

### ISSUE THREAD

**Issue by deep110** [tensorflow/tensorflow#9155]
Android [demo](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) does not perform well in low light. I think a button for flashlight is needed.
For example:-
![demo](https://cloud.githubusercontent.com/assets/6515036/24878880/7b447f26-1e52-11e7-9b7f-df01f2e9f9d6.jpg)

**Comment by jart** [comment]
We could add a flashlight button. But the user could always drag down the menu area and enable the flashlight without the help of the app. 

As for the model itself, please consider that it's meant for demo purposes. If demos were perfect, they wouldn't be demos. Maybe that's a good thing. We want to give our users opportunities to explore TensorFlow and improve upon the examples we've provided.
