### ISSUE TITLE
a CUDA runtime call was likely performed without using a StreamExecutor context

### ISSUE THREAD

**Issue by xxxzhi** [tensorflow/tensorflow#916]
I want use my pylearn2 dataset code with tensorflow. But when I add `from pylearn2.datasets.dense_design_matrix import DefaultViewConverter` into mnist convolutional.py and run it in my server, I get this errors:

`F tensorflow/stream_executor/cuda/cuda_driver.cc:302] current context was not created by the StreamExecutor cuda_driver API: 0x38e0330; a CUDA runtime call was likely performed without using a StreamExecutor context
Aborted (core dumped)`

My server is GTX980 with 8 core CPU, I will get that errors in my server. But I can run it in my desktop PC with GTX960/GTX970 and 4 core CPU and I don't get any errors. All the cuda version is same in my machices.
Does anyone can help me? 

the full traceback is:

```
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcublas.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcudnn.so.6.5 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library libcurand.so.7.0 locally
Using gpu device 0: GeForce GTX 980 (CNMeM is disabled)
/home/b3432/ShareCache/houzhi/data
train-images-idx3-ubyte.gz
/home/b3432/ShareCache/houzhi/data
train-labels-idx1-ubyte.gz
/home/b3432/ShareCache/houzhi/data
t10k-images-idx3-ubyte.gz
/home/b3432/ShareCache/houzhi/data
t10k-labels-idx1-ubyte.gz
Extracting /home/b3432/ShareCache/houzhi/data/train-images-idx3-ubyte.gz
Extracting /home/b3432/ShareCache/houzhi/data/train-labels-idx1-ubyte.gz
Extracting /home/b3432/ShareCache/houzhi/data/t10k-images-idx3-ubyte.gz
Extracting /home/b3432/ShareCache/houzhi/data/t10k-labels-idx1-ubyte.gz
I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 8
F tensorflow/stream_executor/cuda/cuda_driver.cc:302] current context was not created by the StreamExecutor cuda_driver API: 0x38e0330; a CUDA runtime call was likely performed without using a StreamExecutor context
Aborted (core dumped)
```

**Comment by cesarsalgado** [comment]
I am having the same error when I try to use caffe in the same python session as tensorflow. The problem probably is that caffe is using the gpu withough using the StreamExecutor cuda_driver API and tensorflow doesn't accept that. How can I reset the GPU (as if a exit and enter in python again) so I can use tensorflow after having used caffe?

**Comment by Henry-Chinner** [comment]
I am having the same issue

**Comment by Henry-Chinner** [comment]
My issue is probably script specific. I ran the demo mnist model and it was running fine.

**Comment by xiangacadia** [comment]
I am having the same issue when using Theano along with Tensorflow. When disabled GPU for Theano, the error is gone.

**Comment by jmugan** [comment]
I'm getting this error. Are there any workarounds? @xlangacadia, what do you mean by "disabled GPU for Theano"? In .theanorc? I restarted the computer (Theano was running previuosly), so that should have taken care of getting Theano off the GPU, I would think. Restarting did not help.

**Comment by moustaki** [comment]
@jmugan Make sure you don't have a ```import theano.tensor as t``` line lying around in your code -- this will cause this issue to happen.

**Comment by jmugan** [comment]
That fixed it, thanks @moustaki! I couldn't find where I was doing the import, but I changed the device to cpu in .theanorc, and now it works.

**Comment by girving** [comment]
@zheng-xq: Can you take a look at this?  Seems like it fell through the cracks.

**Comment by kbrems** [comment]
We are not using theano or caffe, but are running into this issue in our unit test framework which uses tensorflow operators as well as cuda runtime calls. Are there any plans to fix this?

**Comment by zheng-xq** [comment]
Using TensorFlow with other frameworks is a bit tricky, since there are many places assuming it has exclusive access to the GPU. So disables GPU functionalities in one of them sounds reasonable. 

@kbrems, with your use case, it is not recommended to use TensorFlow operators in the same thread as other Cuda runtime calls. TensorFlow uses stream-executor a faster Cuda runtime alternative. If standard Cuda runtime APIs is called on the same context, it confuses stream-executor with what context is bound to what thread, and many of its internal data structure. 

If you have to make Cuda calls, either: 

1. Call the stream-executor alternative. 
2. Call the Cuda driver API similar to what stream-executor does, and make sure you restore the context binding after you are done.

**Comment by girving** [comment]
Closing for now since making TensorFlow share the GPU seems out of reach.

**Comment by leocnj** [comment]
Using the trick suggested by @jmugan - "I changed the device to cpu in .theanorc, and now it works.", I can use either tensorflow or theano to be keras's backend to run the same python script.

**Comment by NilsRethmeier** [comment]
Alternatively, just start your tensorflow job with `THEANO_FLAGS='device=cpu' python myNN.py`.
That way you do not have to mess with your `.theanorc`

**Comment by IvyGongoogle** [comment]
@jalammar @girving I have the same error:
`tensorflow/stream_executor/cuda/cuda_driver.cc:334] current context was not created by the StreamExecutor cuda_driver API: 0x2862ff0; a CUDA runtime call was likely performed without using a StreamExecutor context`
it means that another program is accessing or using the GPU?

**Comment by IvyGongoogle** [comment]
@xiangacadia @moustaki @girving @jmugan I have the same error:
`tensorflow/stream_executor/cuda/cuda_driver.cc:334] current context was not created by the StreamExecutor cuda_driver API: 0x2862ff0; a CUDA runtime call was likely performed without using a StreamExecutor context`, but I do not use keras or theno, and I only use tf.  Besides, there are no other programs are accessing or using the GPU.  
what causes this problem?
any advice is appreciated?
thank you in advance!

**Comment by jinfagang** [comment]
Exactly same issue, any body could give an solution? I installed boost and dlib which may using CUDA ,  got same error, now I don't want disable any, how to resolve this?

**Comment by sstirlin** [comment]
One possible workaround is to launch the Tensorflow code in a separate worker thread.  This isolates Tensorflow's CUDA context and allows it to coexist peacefully with Caffe (and other CUDA-enabled libraries).  

I'm using python's `threading` and `Queue` libraries for this, and no complaints (although they're still battling for memory, but that's a different story).

**Comment by IvyGongoogle** [comment]
@sstirlin yes, I also create another subprocess  for other CUDA-used  processes. and no complaints
