### ISSUE TITLE
bazel build macOS failing "ld: unknown option: -zmuldefs"

### ISSUE THREAD

**Issue by ckalas** [tensorflow/tensorflow#9160]
- *TensorFlow installed from (source or binary)?*: source
- *TensorFlow version*: latest one checked out from git
- *Bazel version (if compiling from source)*:  0.4.5-homebrew
- *CUDA/cuDNN version*: 8.0 / 5.1 (6.0 fails earlier in the build)
- *GPU Model and Memory*: GeForce 750M 2GB
- *Exact command to reproduce*:bazel build --config=cuda --config=opt //tensorflow/tools/pip_package:build_pip_package

### Describe the problem clearly
So I followed this general guide https://gist.github.com/ageitgey/819a51afa4613649bd18, after which I solved some compilation issues with http://stackoverflow.com/questions/39865212/dyld-library-not-loaded-rpath-libcudart-8-0-dylib-while-building-tensorflow?rq=1.

Doing this allowed me to compile more, but then the following errors occur.
### Source Code / Logs
```
ERROR: /Users/chris/git/tensorflow/tensorflow/python/BUILD:2533:1: Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed: link_dynamic_library.sh failed: error executing command external/bazel_tools/tools/cpp/link_dynamic_library.sh no ignored ignored ignored external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -shared -o ... (remaining 472 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
clang: warning: argument unused during compilation: '-pthread'
ld: unknown option: -zmuldefs
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1592.901s, Critical Path: 1309.60s
```

**Comment by ckalas** [comment]
Some searching has found this page http://stackoverflow.com/questions/17443976/how-to-allow-z-multidefs-with-g47, but i'm unsure how to proceed to make this build for me. currently grepping for zmuldefs to hopefully replace it...

**Comment by asimshankar** [comment]
The guide your are following is not maintained by the TensorFlow project. To build TensorFlow from source, please refer to [Installing TensorFlow from Sources](https://www.tensorflow.org/install/install_sources) on the TensorFlow website.

Since this appears to be an issue with an external guide and not TensorFlow documentation, I'm going to close this issue. If you find bugs in the official guide, please feel free to reopen a new issue with all the details. Thanks!

**Comment by udnaan** [comment]
@ckalas You are using clang which does not support -zmuldefs. (clang is symlinked as gcc on MacOS, and bazel is not smart enough to try and identify the compiler)
You have two options: 
Install gcc and rerun ./configure, selecting the correct compiler
or
rerun ./configure and select clang as the compiler.

**Comment by surgewong** [comment]
@ckalas I meet the same problems like you. Maybe there exist some bugs for macOS in the latest version checked out from git. It works when I use the branch 'remotes/origin/r1.1'.

**Source Code / Logs**

```
INFO: From Compiling tensorflow/tools/graph_transforms/quantize_nodes.cc:
tensorflow/tools/graph_transforms/quantize_nodes.cc:172:6: warning: unused function 'AreAttrsEqual' [-Wunused-function]
bool AreAttrsEqual(const NodeDef* current_node, const NodeDef* other_node) {
     ^
1 warning generated.
INFO: From Linking tensorflow/python/_pywrap_tensorflow_internal.so:
clang: warning: argument unused during compilation: '-pthread'
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 1847.249s, Critical Path: 1683.09s
➜  tensorflow git:(4874d43) ✗ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Fri Apr 14 22:29:14 CST 2017 : === Using tmpdir: /var/folders/lc/8t7355q97sq34vlvzp9vbby00000gn/T/tmp.XXXXXXXXXX.vgCZk00t
~/Projects/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles ~/Projects/tensorflow
~/Projects/tensorflow
/var/folders/lc/8t7355q97sq34vlvzp9vbby00000gn/T/tmp.XXXXXXXXXX.vgCZk00t ~/Projects/tensorflow
Fri Apr 14 22:29:19 CST 2017 : === Building wheel
warning: no files found matching '*.dll' under directory '*'
warning: no files found matching '*.lib' under directory '*'
~/Projects/tensorflow
Fri Apr 14 22:29:35 CST 2017 : === Output wheel file is in: /tmp/tensorflow_pkg
➜  tensorflow git:(4874d43) ✗ sudo pip install /tmp/tensorflow_pkg/tensorflow-1.1.0rc2-cp27-none-macosx_10_11_x86_64.whl
```

**Comment by Ericvulpi** [comment]
see thread https://github.com/tensorflow/tensorflow/issues/9072 for mac bazel build walkthrough

**Comment by avinav291** [comment]
@ckalas You Mentioned that:
Deleting the option entirely leads to this error further down about not finding omp d: library not found for -lgomp

How did u get out of this error??????/
