### ISSUE TITLE
Hi, I am unable to access the documentation

### ISSUE THREAD

**Issue by ayat-khairy** [tensorflow/tensorflow#9161]
NOTE: Issues that are not bugs or feature requests will be closed. Please ask usage questions on StackOverflow.

### You must complete this information or else your issue will be closed
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*:
- *TensorFlow installed from (source or binary)?*:
- *TensorFlow version*:
- *Bazel version (if compiling from source)*:
- *CUDA/cuDNN version*:
- *GPU Model and Memory*:
- *Exact command to reproduce*:

### Source Code / Logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full-traceback. Large logs and files should be attached. Try to reproducible test-case code the bare-minimum necessary to generate the problem

**Comment by Rikorose** [comment]
https://www.tensorflow.org/get_started/get_started

**Comment by ayat-khairy** [comment]
Thanks! Sorry, I mean the documentation of TensorFlow Debugger (tfdbg) https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/debug/examples

**Comment by geektcp** [comment]
I can not see too, is there any document of tensorflow which is whriten by java or scala?

**Comment by asimshankar** [comment]
@ayat-khairy : Thanks for pointing out that broken link. In the mean time you can find documentation for `tfdbg` in https://www.tensorflow.org/programmers_guide/debugger and https://www.tensorflow.org/programmers_guide/tfdbg-tflearn 

@caisq : Do you want to update the link in the README?

@geektcp : I'm not sure I understand your question. If you have a separate bug report about documentation, please file an issue with more details. Or if this comment answers your question, great.

Thanks!

**Comment by caisq** [comment]
A fix has been submitted internally and will be pushed to GtiHub son.
