### ISSUE TITLE
tf.slim should not use relu as a default activation function

### ISSUE THREAD

**Issue by carpedm20** [tensorflow/tensorflow#9164]
It's hard to understand the reason why relu is chosen as a default activation function. It looks like the choice of default activation function is against common sense. If someone never read the actual code or forget about it, it's so easy to make a mistake.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/layers.py#L1387
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/layers/python/layers/layers.py#L822

**Comment by asimshankar** [comment]
Some things of note:

- [Documentation has been updated in the next release](https://www.tensorflow.org/versions/r1.1/api_docs/python/tf/contrib/layers/fully_connected) so this choice will be clearer and one doesn't have to read through the code
- This is in `contrib`, as layers make their way to the fully supported public API ([`tf.layers`](https://www.tensorflow.org/api_docs/python/tf/layers)), many of these choices are being revisited and documentation updated.

FYI @sguada @nathansilberman @martinwicke in case they have anything to add.
Thanks!
