### ISSUE TITLE
Example Cluster Spec for Distributed YoutTube-8m challenge training

### ISSUE THREAD

**Issue by sahiliitm** [tensorflow/tensorflow#9166]
Hi,

Can you please post a  ClusterSpec for distributed training of the models defined in  the [YouTube-8m Challenge code](https://github.com/google/youtube-8m)? 
The [code](https://github.com/google/youtube-8m/blob/master/train.py#L628) tries to load a cluster spec from TF_CONFIG environment variable. However, I'm not sure what the value for TF_CONFIG should be. I have access to 2 GPUs on one machine and just want to run the model with data-level parallelism.

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
