### ISSUE TITLE
When I use the Bazel to compile the image_retraining project when the error occurred, 

### ISSUE THREAD

**Issue by tiantianwei** [tensorflow/tensorflow#9168]
NOTE: Issues that are not bugs or feature requests will be closed. Please ask usage questions on StackOverflow.

### You must complete this information or else your issue will be closed
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*:
- *TensorFlow installed from (source or binary)?*:
- *TensorFlow version*:
- *Bazel version (if compiling from source)*:
- *CUDA/cuDNN version*:
- *GPU Model and Memory*:
- *Exact command to reproduce*:

### Describe the problem clearly
When I use the Bazel to compile the image_retraining project when the error occurred, how to solve, spec.json, head, branch_ref these documents are not in that directory, did you made some change that now cannot compile directory:
wei@wei-TA960:~/myprogramfile/TF-0.12/tensorflow-r0.12-1$ bazel build tensorflow/examples/image_retraining:retrain
ERROR: /home/wei/myprogramfile/TF-0.12/tensorflow-r0.12-1/tensorflow/core/BUILD:1117:1: no such target '//tensorflow/tools/git:gen/spec.json': target 'gen/spec.json' not declared in package 'tensorflow/tools/git' defined by /home/wei/myprogramfile/TF-0.12/tensorflow-r0.12-1/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /home/wei/myprogramfile/TF-0.12/tensorflow-r0.12-1/tensorflow/core/BUILD:1117:1: no such target '//tensorflow/tools/git:gen/head': target 'gen/head' not declared in package 'tensorflow/tools/git' defined by /home/wei/myprogramfile/TF-0.12/tensorflow-r0.12-1/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /home/wei/myprogramfile/TF-0.12/tensorflow-r0.12-1/tensorflow/core/BUILD:1117:1: no such target '//tensorflow/tools/git:gen/branch_ref': target 'gen/branch_ref' not declared in package 'tensorflow/tools/git' defined by /home/wei/myprogramfile/TF-0.12/tensorflow-r0.12-1/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
### Source Code / Logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full-traceback. Large logs and files should be attached. Try to reproducible test-case code the bare-minimum necessary to generate the problem

**Comment by asimshankar** [comment]
Please provide all information asked for in the new issue template. Without that information, help is not easy to provide.

That said, in your case it seems that you need to run `./configure` as outlined in the guide to [Installing TensorFlow from Sources](https://www.tensorflow.org/install/install_sources).
