### ISSUE TITLE
possible doc inconsistency `tf.contrib.framework.load_variable`

### ISSUE THREAD

**Issue by falcondai** [tensorflow/tensorflow#9172]
NOTE: Issues that are not bugs or feature requests will be closed. Please ask usage questions on StackOverflow.

### You must complete this information or else your issue will be closed
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*:
- *TensorFlow installed from (source or binary)?*:
- *TensorFlow version*:
- *Bazel version (if compiling from source)*:
- *CUDA/cuDNN version*:
- *GPU Model and Memory*:
- *Exact command to reproduce*:

### Describe the problem clearly
In my experience, this function `tf.contrib.framework.load_variable` returns a `numpy.ndarray` instead of a `Tensor` as the [doc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/framework/python/framework/checkpoint_utils.py#L74) suggests. Furthermore according to the [unit test](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/framework/python/framework/checkpoint_utils_test.py#L96), it is expected to return the value of a tensor instead of a `Tensor` object itself. I think the behavior of returning tensor values is desired (to load select variables from arbitrary checkpoints without a session), so this should be a minor doc issue.

### Source Code / Logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full-traceback. Large logs and files should be attached. Try to reproducible test-case code the bare-minimum necessary to generate the problem

**Comment by drpngx** [comment]
Right. We sometimes refer to Tensors as numpy arrays, rather than the symbolic operations (in python). @jhseu might have some opinion here.

**Comment by drpngx** [comment]
If you find a good wording, place submit a PR.

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
