### ISSUE TITLE
How to add an external java library(.jar) into Bazel build path.

### ISSUE THREAD

**Issue by cooliybob** [tensorflow/tensorflow#9177]
### Describe the problem clearly
I follow the rule in [Bazel website](https://bazel.build/versions/master/docs/be/android.html#android_binary.shrink_resources) to add a JAR into Bazel build path, this is my script:

...
android_binary(
    ...
    deps = [
        ":tensorflow_native_libs",
        "//tensorflow/contrib/android:android_tensorflow_inference_java",
	**":libs/nd4j-api-0.8.0.jar"**
    ],
)
...

but the log says that my JAR is misplaced.
How should I do to add a JAR library into build path or do I miss out something ?

Thanks,

### Source Code / Logs
ERROR: /home/bob/deep_learning/tensorflow/tensorflow/examples/android/BUILD:76:12: in deps attribute of android_binary rule //tensorflow/examples/android:tensorflow_demo: file '//tensorflow/examples/android:libs/nd4j-api-0.8.0.jar' is misplaced here (expected no files).
ERROR: Analysis of target '//tensorflow/examples/android:tensorflow_demo' failed; build aborted.

**Comment by asimshankar** [comment]
This question is more about use of bazel than TensorFlow, so I'm going to close it out and recommend that you look into bazel documentation/support.

That said, perhaps you're looking for the [`java_import`](https://bazel.build/versions/master/docs/be/java.html#java_import) rule

**Comment by cooliybob** [comment]
That is a correct answer. Thanks a lot ~
