### ISSUE TITLE
tf.layers.conv3d channels_first not supported

### ISSUE THREAD

**Issue by qianglan** [tensorflow/tensorflow#9182]
Hi , 

When I use tf.layers.conv3d function, I meet a problem, there is a data_format setting in this function, and I want to set this to 'channels_first' , however error occurred: Data format "channels_first" not supported for inputs with rank 5.
The tensorflow version I used is 1.0.0, I wonder in which version does 'channels_first' is supported in 3d convolution?

Thanks

Qiang

**Comment by asimshankar** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  **Make sure you also include the exact command if possible to produce  the output included in your test case**.   We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by qianglan** [comment]
Thanks,

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes, see below
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: linux Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**:  1.0.0
- **Bazel version (if compiling from source)**:0.4.5
- **CUDA/cuDNN version**: 8.0/5
- **GPU model and memory**: K40
- **Exact command to reproduce**: 


### Describe the problem

I want to use tensorflow to implement a 3D neural network, so I test conv3d first. I use tf.layers.conv3d to test a 3D convolutional layer. You can refer the source code below, there is one parameter to set for tf.layers.conv3d, which is 'data_format', there are two options for that parameter, one is 'channels_first' , the other is 'channels_last', there is no problem with 'channels_last', however, there are problems when I set 'data_format' to 'channels_first'. The output is like following:

$python  conv3d_test.py
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "/home/deng/qianglan/Opensource/3DModelParallel/conv3d_test.py", line 26, in <module>
    tf.app.run()
  File "/home/deng/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/deng/qianglan/Opensource/3DModelParallel/conv3d_test.py", line 23, in main
    run_benchmark()
  File "/home/deng/qianglan/Opensource/3DModelParallel/conv3d_test.py", line 14, in run_benchmark
    test_output = tf.layers.conv3d(test_input, filters, kernel_size=(3,3,3), strides=[1, 1,1], padding='SAME', data_format='channels_first', trainable=False)
  File "/home/deng/anaconda/lib/python2.7/site-packages/tensorflow/python/layers/convolutional.py", line 682, in conv3d
    return layer.apply(inputs)
  File "/home/deng/anaconda/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 303, in apply
    return self.__call__(inputs, **kwargs)
  File "/home/deng/anaconda/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 273, in __call__
    outputs = self.call(inputs, **kwargs)
  File "/home/deng/anaconda/lib/python2.7/site-packages/tensorflow/python/layers/convolutional.py", line 156, in call
    data_format=utils.convert_data_format(self.data_format, self.rank + 2))
  File "/home/deng/anaconda/lib/python2.7/site-packages/tensorflow/python/layers/utils.py", line 49, in convert_data_format
    raise ValueError('Data format "channels_first" not supported for '
ValueError: Data format "channels_first" not supported for inputs with rank 5.

Process finished with exit code 1


### Source code / logs

import tensorflow as tf

def run_benchmark():
    with tf.Graph().as_default():
        input_shape = [1,64,224,224,224]
        test_input = tf.Variable(tf.random_normal(input_shape, dtype=tf.float32, stddev=1e-1))
        filters = 64
        with tf.variable_scope('test_conv_layer'):
            test_output = tf.layers.conv3d(test_input, filters, kernel_size=(3,3,3), strides=[1, 1,1],           padding='SAME', data_format='channels_first', trainable=False)

        init = tf.global_variables_initializer()
        sess = tf.Session()
        sess.run(init)
        result = sess.run(test_output)
        print result.shape

def main(_):
    run_benchmark()

if __name__ == '__main__':
    tf.app.run()

**Comment by drpngx** [comment]
The doc says you have to have rank 4 [`(batch, channels, depth, height, width)`](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/convolutional.py#L656) not 5. You can also see the example in the [test](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/convolutional_test.py#L85).
