### ISSUE TITLE
Windows: //tensorflow/python/estimator:estimator_test failing in Bazel build

### ISSUE THREAD

**Issue by meteorcloudy** [tensorflow/tensorflow#9185]
http://ci.tensorflow.org/job/tf-master-win-bzl/751/consoleFull

It has been failing on ci for a while with:
```
22:36:33 ======================================================================
22:36:33 ERROR: test_train_save_copy_reload (__main__.EstimatorTrainTest)
22:36:33 ----------------------------------------------------------------------
22:36:33 Traceback (most recent call last):
22:36:33   File "\\?\c:\tmp\Bazel.runfiles_r2z2r52c\runfiles\org_tensorflow\py_test_dir\tensorflow\python\estimator\estimator_test.py", line 267, in test_train_save_copy_reload
22:36:33     os.renames(model_dir1, model_dir2)
22:36:33   File "C:\Program Files\Anaconda3\lib\os.py", line 288, in renames
22:36:33     rename(old, new)
22:36:33 PermissionError: [WinError 5] Access is denied: 'c:\\tmp\\tmp8f7qnomv\\model_dir1' -> 'c:\\tmp\\tmp8f7qnomv\\model_dir2'
```
@gunan Can we fix this test case on Windows? Otherwise we'd better disable this test on Windows.

**Comment by jart** [comment]
Friendly ping @mrry re: state of Windows Jenkins build.

**Comment by mrry** [comment]
Looks like the author of the broken test isn't on GitHub, so reassigning to @martinwicke as overall owner for the Estimator code.

**Comment by martinwicke** [comment]
Is there something special about mkdtmp on Windows? Seems we don't have permissions to rename a file in such a directory?

**Comment by mrry** [comment]
I think the main pitfall here is failing to close all of the files in the directory before trying to move it. We had various tests that used to be sloppy about closing temp files before opening them elsewhere... perhaps the Estimator code does this somewhere?
