### ISSUE TITLE
README.md has a deprecated API call

### ISSUE THREAD

**Issue by rsln-s** [tensorflow/tensorflow#9187]
### System Information
Tensorflow ('v1.0.0-65-g4763edf-dirty', '1.0.1')

### Describe the problem clearly
In README.md line `predictions = vgg.vgg16(images, is_training=True)` should be `predictions = vgg.vgg_16(images, is_training=True)` (see [source code for vgg](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/nets/vgg.py)).

**Comment by jart** [comment]
Thanks for bringing this to our attention. Did you notice any other deprecated parts of the README by chance?

**Comment by rsln-s** [comment]
I've also come upon [this issue on SO](http://stackoverflow.com/questions/41808353/tensorflow-slim-module-object-has-no-attribute-sum-of-squares) while searching for fix for vgg.

I believe `sum_of_squares_loss = slim.losses.sum_of_squares(depth_predictions, depth_labels)
` is still in README despite being deprecated, but I haven't checked it myself.

I hope this helps.
