### ISSUE TITLE
SpaceToBatchND / BatchToSpaceND Documentation Error

### ISSUE THREAD

**Issue by eplondke** [tensorflow/tensorflow#9190]
I think there is an error in the *documentation* for SpaceToBatchND and BatchToSpaceND.  (The op itself seems to be working fine.)

In example (3) from SpaceToBatchND:

> (3) For the following input of shape [1, 4, 4, 1], block_shape = [2, 2], and paddings = [[0, 0], [0, 0]]:
> 
> ```prettyprint x = [[[[1], [2], [3], [4]], [[5], [6], [7], [8]], [[9], [10], [11], [12]], [[13], [14], [15], [16]]]] ```
> 
> The output tensor has shape [4, 2, 2, 1] and value:
> 
> ```prettyprint x = [[[[1], [3]], [[5], [7]]], [[[2], [4]], [[10], [12]]], [[[5], [7]], [[13], [15]]], [[[6], [8]], [[14], [16]]]] ```

Note how [[5],[7]] appears twice in the result and [[9],[11]] is missing.

The example (3) in BatchToSpaceND has the same problem in reverse.

If I actually try this op in TensorFlow, I get results that differ from the documentation but make sense to me:

```

>>> bshape = [2,2]
>>> paddings = [[0,0],[0,0]]
>>> x  = [[[[1], [2], [3], [4]], [[5], [6], [7], [8]], [[9], [10], [11], [12]], [[13], [14], [15], [16]]]]
>>> s2btest = tf.space_to_batch_nd(x,bshape,paddings)
>>> sess.run(s2btest)
array([[[[ 1],
         [ 3]],

        [[ 9],
         [11]]],


       [[[ 2],
         [ 4]],

        [[10],
         [12]]],


       [[[ 5],
         [ 7]],

        [[13],
         [15]]],


       [[[ 6],
         [ 8]],

        [[14],
         [16]]]], dtype=int32)

```

Example tried with TensorFlow from source / Linux Ubuntu Xenial / v1.1.0-rc1-168-g0054c39 1.1.0-rc1
.

Documentation from https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/batch-to-space-n-d and https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/space-to-batch-n-d 

Looking at the doc string this may be fixed in master (d1ba01f8) and just not updated on the 1.0 branch web docs yet.

**Comment by asimshankar** [comment]
Thanks for pointing this out. As you found out, this was fixed in #7080 and will be reflected in the next release (you can preview the docs for 1.1 that show this fix at https://www.tensorflow.org/versions/r1.1/api_docs/cc/class/tensorflow/ops/space-to-batch-n-d)

Closing this out, since this has been fixed - just not reflected to the website yet, which will be soon.
