### ISSUE TITLE
TensorFlow crashing when batching audio

### ISSUE THREAD

**Issue by MadWombat** [tensorflow/tensorflow#9191]
I have tried to create an audio processing model using tensorflow.contrib.ffmpeg. The code I wrote consistently crashes the python process on my OS X. I have provided both the code and a piece of crash report on this stackoverflow question. 

http://stackoverflow.com/questions/43377986/batching-audio-data-in-tensorflow/

Is this a bug or am I doing something wrong?

**Comment by jart** [comment]
Please see issue tracker policy posted [here](https://github.com/tensorflow/tensorflow/issues/new).
