### ISSUE TITLE
do we have plans for java api?

### ISSUE THREAD

**Issue by vach** [tensorflow/tensorflow#92]
I can see there is only python and C++ api, do we have any plans for java api? or workarounds?

**Comment by dEcmir** [comment]
Somebody has to write a swig interface file that allow to call C/C++ functions in another language like Java. This is what was done to support python I think If you want you can look into swig documentation and to the current swig interface files to create a Java interface

**Comment by vincentvanhoucke** [comment]
Please follow:
https://github.com/tensorflow/tensorflow/issues/5
https://github.com/tensorflow/tensorflow/issues/3

**Comment by klymenko-ruslan** [comment]
Guys, please let me know if you plan to implement java 'wrapper' classes which will call c++ code. 
 I can assist with it. Unfortunately i have no time to discover the library by myself but i can spend some time writing implementations.

**Comment by junwucs** [comment]
+1 for java

**Comment by abhishekbagati** [comment]
++ for java! It would be really helpful if someone can do that!

**Comment by coderXiangLi** [comment]
+1 for java!

**Comment by rygh4775** [comment]
+1 for java

**Comment by jacobringmann** [comment]
+1 for java

**Comment by phenomax** [comment]
+1 for java

**Comment by Brill-Wang** [comment]
+1 for java

**Comment by volkovma** [comment]
+1 for java

**Comment by rizasif** [comment]
+1 for java

**Comment by leonard2014** [comment]
desperately need a java interface to use tensorflow in enterprise web server

**Comment by jmart1** [comment]
+1 for java

**Comment by imaravin** [comment]
+1 for java

**Comment by jahmad1234** [comment]
+1 for java

**Comment by vrv** [comment]
Please use Github reactions on the root post to register your votes.  Thanks!
