### ISSUE TITLE
Support tf.gradients and tf.hessians for sliced and concatenated variables

### ISSUE THREAD

**Issue by maomaocode** [tensorflow/tensorflow#9204]
Let x and y be vectors of length N, and z is a function z = f(x,y). In Tensorflow v1.0.0, tf.hessians(z,x) and tf.hessians(z,y) both returns an N by N matrix, which is what I expected.

However, when I concatenate the x and y into a vector p of size 2*N using tf.concat, and run tf.hessians(z, p), it returns error "ValueError: None values not supported."

I understand this is because in the computation graph x,y ->z and x,y -> p, so there is no gradient between p and z.  Is there a way to circumvent the problem, other than create p first and slice p into x and y? 

```
import tensorflow as tf
import numpy as np

N = 2
A = tf.Variable(np.random.rand(N,N).astype(np.float32))
B = tf.Variable(np.random.rand(N,N).astype(np.float32))

x = tf.Variable(tf.random_normal([N]) )
y = tf.Variable(tf.random_normal([N]) )

#reshape to N by 1
x_1 = tf.reshape(x,[N,1])
y_1 = tf.reshape(y,[N,1])

#concat x and y to form a vector p with length of 2*N
p = tf.concat([x,y],axis = 0)

#define the function
z = 0.5*tf.matmul(tf.matmul(tf.transpose(x_1), A), x_1) + 0.5*tf.matmul(tf.matmul(tf.transpose(y_1), B), y_1) + 100

#works , hx and hy are both N by N matrix
hx = tf.hessians(z,x)
hy = tf.hessians(z,y)

#this gives error "ValueError: None values not supported."
#expecting a matrix of size 2*N by 2*N
hp = tf.hessians(z,p)
```

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
