### ISSUE TITLE
[Windows - Bazel] ERROR undeclared inclusion(s) in rule '//tensorflow/core/kernels:fake_quant_ops_gpu'

### ISSUE THREAD

**Issue by Carmezim** [tensorflow/tensorflow#9209]
Windows 10
CUDA 8.0
cuDNN 5.1
TensorFlow at e8a34420ce06c7f99049b4e4fec4308aff8dd058
Bazel at [e565230](https://github.com/bazelbuild/bazel/commit/eecd7128f420b2d404ed2f42d549dea3bd198d9d)
Msys2

During build Bazel failed with

```
ERROR: C:/users/adriano/documents/tensorflow/tensorflow/core/kernels/BUILD:2809:1: undeclared inclusion(s) in rule '//tensorflow/core/kernels:fake_quant_ops_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/fake_quant_ops_gpu.cu.cc':
  'C:/windows/temp/tmpxft_0000426c_00000000-8_fake_quant_ops_gpu.cu.cudafe1.stub.c'
  'C:/windows/temp/tmpxft_0000426c_00000000-6_fake_quant_ops_gpu.cu.fatbin.c'
c:\tmp\_bazel_adriano\piryq3n9\execroot\tensorflow\external\eigen_archive\eigen\src/Core/products/Parallelizer.h(20): warning: variable "m_maxThreads" was set but never used
c:\tmp\_bazel_adriano\piryq3n9\execroot\tensorflow\external\eigen_archive\eigen\src/Core/ArrayWrapper.h(93): warning: __declspec attributes ignored
c:\tmp\_bazel_adriano\piryq3n9\execroot\tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/ThreadPool/SimpleThreadPool.h(139): warning: "constexpr" is ignored here in Microsoft mode
c:\tmp\_bazel_adriano\piryq3n9\execroot\tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/ThreadPool/NonBlockingThreadPool.h(151): warning: "constexpr" is ignored here in Microsoft mode
c:\tmp\_bazel_adriano\piryq3n9\execroot\tensorflow\external\eigen_archive\eigen\src/Core/products/Parallelizer.h(20): warning: variable "m_maxThreads" was set but never used
c:\tmp\_bazel_adriano\piryq3n9\execroot\tensorflow\external\eigen_archive\eigen\src/Core/ArrayWrapper.h(93): warning: __declspec attributes ignored
c:\tmp\_bazel_adriano\piryq3n9\execroot\tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/ThreadPool/SimpleThreadPool.h(139): warning: "constexpr" is ignored here in Microsoft mode
c:\tmp\_bazel_adriano\piryq3n9\execroot\tensorflow\external\eigen_archive\unsupported\eigen\cxx11\src/ThreadPool/NonBlockingThreadPool.h(151): warning: "constexpr" is ignored here in Microsoft mode
nvcc warning : option '--relaxed-constexpr' has been deprecated and replaced by option '--expt-relaxed-constexpr'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 2078.109s, Critical Path: 104.55s
FAILED: Build did NOT complete successfully
+ exit 1

```

#### Steps to reproduce
- configure TensorFlow accordingly without XLA
- `export BUILD_OPTS='--cpu=x64_windows_msvc --host_cpu=x64_windows_msvc --copt=/w --verbose_failures --experimental_ui'`
- `./tensorflow/tools/ci_build/windows/gpu/pip/build_tf_windows.sh    `

**Comment by jart** [comment]
@mrry Guy with the correct Windows CUDA [versions](https://www.tensorflow.org/install/install_windows#requirements_to_run_tensorflow_with_gpu_support) is encountering what appears to be either a Bazel sandbox or strict deps issue.

**Comment by mrry** [comment]
Alas support for Bazel on Windows is still limited, and it will probably be easier to build with CMake.

@meteorcloudy Have you seen this error before?

**Comment by Carmezim** [comment]
I was expecting to leverage gcc but was warned by @meteorcloudy I might face issues if building TF. 
I am aware bazel on Windows is experimental but decided to post the issue anyways to make the problem known for future improvements.

**Comment by mrry** [comment]
Hmm, did those errors appear when using GCC as the compiler on Windows? (Like @meteorcloudy, I'd be surprised if that worked, especially for the GPU build, but also for the various dependent libraries that might not have GCC-aware build configurations for Windows in our build files.)

**Comment by Carmezim** [comment]
As in https://github.com/bazelbuild/bazel/issues/2753#issuecomment-292818313

**Comment by Carmezim** [comment]
Someone else had a compiling issue related to `fake_quant_ops_gpu`
http://stackoverflow.com/questions/43482642/tesnsorflow-1-1-build-breaks-on-cuda-code

**Comment by mrry** [comment]
Thanks for pointing that out! @cwhipkey Are you aware of any issues with building `fake_quant_ops_gpu` (which I think you added, but feel free to redirect :)...)?

**Comment by mrry** [comment]
(Looks like this has also surfaced in #9296.)
