### ISSUE TITLE
tensorflow.Session() Hangs on 24-Logical Core Machine

### ISSUE THREAD

**Issue by KermMartian** [tensorflow/tensorflow#921]
We have a newish (<6 months old) server with two hyperthreaded 6-core processors, and when we try to create a tensorflow.Session(), it hangs indefinitely in what `top` reports is state D (uninterruptible sleep), unresponsive even to SIGKILL. Relevant output is below.
```
>>> sess = tf.Session() 
I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 24
[...indefinite hang...]
```

**Comment by yaroslavvb** [comment]
Does it hang if you run with "--brain_num_operation_threads=1 --brain_num_eigen_threads=1"?
If it still hangs, maybe you could compile in debug mode, attach GDB to hanging process and do "bt" to see where it's stuck

**Comment by KermMartian** [comment]
I couldn't find documentation on where to specify those arguments (certainly not to Python, and I could find no such ConfigProto flags. However, I did try setting intra_op_parallelism_threads to 1, and the same issue occurred. I'll try seeing if GDB can shed some light on the matter.
```
>>> sess = tf.Session(config=tf.ConfigProto(
...     intra_op_parallelism_threads=1))          
I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 1
[...indefinite hang...]
```

**Comment by yaroslavvb** [comment]
Oops, brain freeze, updated to use the proper ConfigProto object rather than unsupported flags

**Comment by KermMartian** [comment]
After a machine reboot, this problem no longer occurred. It seems that our cards' driver might have been hung somewhere, as other CUDA code was also hanging.
