### ISSUE TITLE
Provide wheel packages at pypi for python 3.6 on windows

### ISSUE THREAD

**Issue by xgdgsc** [tensorflow/tensorflow#9212]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 x64
- **TensorFlow installed from (source or binary)**: binary(expect)

### Describe the problem

Providing wheel packages at pypi for python 3.6 on windows would be helpful. As it is the latest anaconda python version.

**Comment by Carmezim** [comment]
Please see #6999
