### ISSUE TITLE
encoder_inputs and decoder_inputs of a sequence to sequence model.

### ISSUE THREAD

**Issue by TarAll** [tensorflow/tensorflow#9215]
Hello,
I've read the tutorial about seq2seq on the website and still can't figure out how my inputs have to be;
here's my problem:
each of my inputs is a matrix with fixed number of columns but a variable number of rows( each matrix has its number of rows). And the same thing for my outputs.
how to build the encoder and decoder inputs?
Thanks in advance.

**Comment by jart** [comment]
This might be a better question for [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). Please see our issue tracker [policy](https://github.com/tensorflow/tensorflow/issues/new).
