### ISSUE TITLE
How to recompile eigen3 library

### ISSUE THREAD

**Issue by PKUEcho** [tensorflow/tensorflow#9220]
I changed some code in the //tensorflow/third_party/eigen3, and recompile the C++ sample (label_image). I looked at the code of the `BUILD` file in label_image and it depends on the //tensorflow/core, and I think the latter depends on the eigen3. However when I run the recompiled label_image, the code I've changed in eigen3 doesn't work. I am not very familiar with bazel so I hope someone can help me on this. How can I recompile the eigen3 to be reflected in the example?

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
