### ISSUE TITLE
Build Error: libcudnn.so.5: file not recognized: File truncated collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by amirj** [tensorflow/tensorflow#9224]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.2
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: master
- **Bazel version (if compiling from source)**: 0.4.5
- **CUDA/cuDNN version**: 8.0/5.1
- **GPU model and memory**: 1080 Ti
- **Exact command to reproduce**: bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

You can collect some of this information using our environment capture script: https://github.com/tensorflow/tensorflow/tree/master/tools

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Get the latest source code and running "bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package" to build GPU version. Cuda and CuDNN completely installed and all samples are passed.

### Source code / logs
ERROR: /home/amir/projects/tensorflow/tensorflow/python/BUILD:2534:1: Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed: link_dynamic_library.sh failed: error executing command external/bazel_tools/tools/cpp/link_dynamic_library.sh no ignored ignored ignored external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -shared -o ... (remaining 27 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/local_linux-py3-opt/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudnn___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Slib/libcudnn.so.5: file not recognized: File truncated
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2259.385s, Critical Path: 2229.15s

**Comment by asimshankar** [comment]
From the error message: `libcudnn.so.5: file not recognized: File truncated` it seems that the `libcuddn.so.5` file is corrupt on your system. You might want ot make sure that it is pointing to the right place (run `file bazel-out/local_linux-py3-opt/bin/_solib_local/_U@local_Uconfig_Ucuda_S_Scuda_Ccudnn___Uexternal_Slocal_Uconfig_Ucuda_Scuda_Slib/libcudnn.so.5`) and that the file is indeed pristine.

**Comment by amirj** [comment]
It seems this issue is related to [#7663](https://github.com/tensorflow/tensorflow/issues/7663). Re-Installing CuDNN solved the problem.
