### ISSUE TITLE
Keras + tensorflow + P100 : cudaErrorNotSupported = 71 error

### ISSUE THREAD

**Issue by vlimant** [tensorflow/tensorflow#9226]
Allow me please to cross post, upon sugestion, an error faced in using keras with tensorflow with machine equipped with P100 https://github.com/fchollet/keras/issues/6054
Apologies if this has been reported already at some other place, I have been googling for it quite a bit, with my colleague without success.
While running the simple mnist example (https://github.com/fchollet/keras/blob/master/examples/mnist_cnn.py) with keras+tensorflow using P100 GPGPU we encounter an issue at the intersection of keras/tensorflow/cuda

Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties:
name: Tesla P100-PCIE-16GB
major: 6 minor: 0 memoryClockRate (GHz) 1.3285
pciBusID 0000:02:00.0
Total memory: 15.89GiB
Free memory: 15.51GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0: Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:02:00.0)
F tensorflow/core/common_runtime/gpu/gpu_device.cc:121] Check failed: err == cudaSuccess (71 vs. 0)
srun: error: nid02011: task 0: Aborted
srun: Terminating job step 1262138.0

we are using keras 2.0.2, tensorflow 1.0.0. cuda 8.0.53.
We seem to be having this issue both in python2.7.12 and python3.5.2 (keras 1.2 and 2.0 ...)
Bare tensorflow runtest are going fine, which lead us to think that this is really at the intersection of keras/tensorflow/cuda.
The same test runs fine on various machine with the same version of the software but with TitanX GPGPU.

 seem to be tracing this back to
https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/core/common_runtime/gpu/gpu_device.cc#L121

http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038

"""
cudaErrorNotSupported = 71
This error indicates the attempted operation is not supported on the current system or device.
"""

I am clueless on where to look next to solve this issue. I would greatly appreciate any feedback and guidance on this matter.

**Comment by jart** [comment]
Please don't crosspost. This might be a better question for [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). Please see our issue tracker [policy](https://github.com/tensorflow/tensorflow/issues/new).

**Comment by vlimant** [comment]
My apologies.
Thanks for the suggestion http://stackoverflow.com/questions/43471544/keras-tensorflow-p100-cudaerrornotsupported-71-error
#9080 seems related.
