### ISSUE TITLE
Out of range: FIFOQueue '_0_fifo_queue'

### ISSUE THREAD

**Issue by auroua** [tensorflow/tensorflow#923]
When I test  [cifar10_input_test.py](tensorflow/tensorflow/models/image/cifar10/cifar10_input_test.py).I got the following information, how could I solve this error.
```
W tensorflow/core/common_runtime/executor.cc:1052] 0x1fe5ea0 Compute status: Out of range: FIFOQueue '_0_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: ReaderRead = ReaderRead[_device="/job:localhost/replica:0/task:0/cpu:0"](FixedLengthRecordReader, fifo_queue)]]
```

**Comment by vrv** [comment]
This is a warning, not an error.  It might be an unhelpful warning though.

Did the test end up failing?

**Comment by carlhopf** [comment]
I go this, when the filename queue could not find any elements for the glob pattern i specified. Might be related?

**Comment by yaroslavvb** [comment]
This is a message that's printed when you reach the end of the queue, so it's part of normal operation

**Comment by auroua** [comment]
@vrv The test end up success.
@yaroslavvb Thanks I understand what's the meaning of this message.

**Comment by wangchuan** [comment]
Why this message was printed? I encountered this problem in my program too, but occasionally this message occurred, not every time. I am wondering what triggered it. @yaroslavvb

**Comment by zh794390558** [comment]
Thanks @yaroslavvb
