### ISSUE TITLE
In ExponentialMovingAverage class in python/training/moving_averages.py, which op will first be executed,  opt_op or maintain_average_op?

### ISSUE THREAD

**Issue by cuiguoxin** [tensorflow/tensorflow#9237]
Recently, I checked the code about moving averages. But I confused about which operation will first be executed, the opt_op which apply the gradient to the variable, or the maintain_average_op which maintain and update the shadow variable? I find that the following code:
` with tf.control_dependencies([opt_op]):
      training_op = tf.group(maintain_averages_op)`
training_op depends on both opt_op and maintain_averages_op. But how about the relation of opt_op   and maintain_averages_op? Which one will be executed first?

**Comment by jart** [comment]
This might be a better question for [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). Please see our issue tracker [policy](https://github.com/tensorflow/tensorflow/issues/new).
