### ISSUE TITLE
git clone hangs when building from source

### ISSUE THREAD

**Issue by fancyerii** [tensorflow/tensorflow#924]
$bazel build -c opt --config=cuda --spawn_strategy=standalone --verbose_failures //tensorflow/tools/pip_package:build_pip_package
..........
[4 / 4] Cloning https://github.com/Polymer/polymer.git: Resolving deltas (13948 / 15071)

it hangs here for a few hours.

**Comment by martinwicke** [comment]
GitHub was having trouble. Is this still a problem?

**Comment by martinwicke** [comment]
I'll close this. If you still have trouble, reopen it.
