### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.seq2seq' has no attribute 'rnn_decoder'

### ISSUE THREAD

**Issue by singh-abhijeet** [tensorflow/tensorflow#9245]
### System information
- **OS and Env**: Windows 7, Python 3.5.1
- **TensorFlow installed from**: binary, pip install tensorflow
- **TensorFlow version**: 1.0.1

### Describe the problem
After upgrading from TF 0.9 to TF 1.0.1, am unable to find `seq2seq.rnn_decoder()`. Updated the `imports` to include seq2seq module (TF 0.9: `tensorflow.python.ops`, TF 1.0: `tensorflow.contrib`). 

On exploring the new API, I noticed a _similar_ function: `dynamic_rnn_decoder`. Unfortunately, `dynamic_rnn_decoder` has different signature than `rnn_decoder`, and a simple function name change fails.

**The Ask**
What's the equivalent of `seq2seq.rnn_decoder()` in TF 1.0+?

### Source code (TF 0.9)
`seq2seq.rnn_decoder(inputs_split,              self.initial_state,
                                                                  self.cell,
                                                                  loop_function=loop if test else None,
                                                                  scope='lstm_vars')`

**Comment by jart** [comment]
0.9 to 1.0.1 is a big jump. A lot changed. https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md The good news is now that we're past 1.0, the core Python API is guaranteed to be stable forevermore. Also please note that most of contrib hasn't been made available on Windows yet.

**Comment by tifoit** [comment]
Tensorflow 0.9 to 1.0.1 is a big jump. A lot changed.
Details: https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md

In tf 1.0.0, the API has been changed such as:

tf.nn.seq2seq.sequence_loss_by_example
to
tf.contrib.legacy_seq2seq.sequence_loss_by_example

tf.nn.rnn_cell.
to
tf.contrib.rnn.

tf.nn.rnn_cell.MultiRNNCell(
to
tf.contrib.rnn.MultiRNNCell(

...
