### ISSUE TITLE
Why are there not dbn and rbm in tensorflow model zoo?

### ISSUE THREAD

**Issue by HarryKane** [tensorflow/tensorflow#9249]
Can anyone add them to tensorflow to make it better?

**Comment by drpngx** [comment]
@jmchen-g @nealwu for model zoo. Model zoos tend to be applied examples, for instance image recognition network training on a corpus such as MNIST, rather than a network building block, like an RNN cell.

RBMs can be implemented in contrib. Effectively we have DBNs if you care to stack layers.

**Comment by nealwu** [comment]
If there are models you would like to see in https://github.com/tensorflow/models, feel free to submit a pull request for them.
