### ISSUE TITLE
no tensorflow/cc/ops/array_ops.h found

### ISSUE THREAD

**Issue by cxwx** [tensorflow/tensorflow#9253]
in file tensorflow/cc/ops/standard_ops.h
include tensorflow/cc/ops/array_ops.h
but it seem that array_ops.h disappeared
I found array_ops.cc at ./core/ops/array_ops.cc
does it a bug?

I use youcompleteme to complete my c++ code, found this problem.

**Comment by asimshankar** [comment]
`array_ops.h` is a generated file which you will find in `bazel-genfiles/tensorflow/cc/ops/array_ops.h` when building bazel targets that depend on it.

**Comment by StarRain-L** [comment]
Excuse me, why I use bazel building a lot less file?
![snip20170613_4](https://user-images.githubusercontent.com/8908244/27073779-a0e86e54-5057-11e7-9ad9-c3782894ece3.png)
