### ISSUE TITLE
stack_bidirectional_dynamic_rnn input incorrect documentation

### ISSUE THREAD

**Issue by j-planet** [tensorflow/tensorflow#9255]
Hi, this is really a documentation problem rather than problem with the actual code.
The [doc](https://www.tensorflow.org/versions/r1.1/api_docs/python/tf/contrib/rnn/stack_bidirectional_dynamic_rnn) states that inputs should be of shape number of numSequences x batchSize x inputSize, but in reality it's batchSize x numSequences x inputSize.

**Comment by drpngx** [comment]
@ebrevdo is that right?

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.
