### ISSUE TITLE
Create support for a score threshold in NonMaxSuppression to skip over boxes with low score

### ISSUE THREAD

**Issue by sheide** [tensorflow/tensorflow#9258]
Right now tensorflow::ops::NonMaxSuppression only prunes away boxes that have a high IOU overlap with previously selected boxes. It would be nice to also support a threshold on score so that the algorithm can skip over boxes that have a score below that threshold. We strongly believe this feature will speed up nms. Is there a plan to add this score threshold as a parameter?

**Comment by asimshankar** [comment]
We currently don't have anybody working on this. It would be great if you could help us by working on this and submitting a PR. Let us know if you need further clarification. Thanks!

(FYI @gpapan @shlens in case they know of anyone working on this)

**Comment by ppwwyyxx** [comment]
You can just filter out those boxes (with `tf.boolean_mask`) before nms to speed up.

**Comment by tilakrayal** [comment]
@sheide,
Could you please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/9258#issuecomment-324752528) and the doc [link](https://www.tensorflow.org/api_docs/python/tf/boolean_mask) which provides the required information. Thank you!
