### ISSUE TITLE
TensorFlow on ARMv7 seems to be slower

### ISSUE THREAD

**Issue by gunasekaran7** [tensorflow/tensorflow#9259]
I have installed tensorflow on our custom board which is based on i.mx6 (ARMv7) processor. I have compiled the C++ module alone without python support and was able to run the "tensorflow/pi_examples/label_image"

Command used:  **make -f tensorflow/contrib/makefile/Makefile HOST_OS=PI TARGET=PI**

The problem is that the application seems to be very slow compared to Laptop (Intel i5). The inference takes close to 60-70s while it takes only 0.6 - 0.7s in my Laptop. 

After that, I figured out that I missed to use compiler optimization flag to use Neon. I compiled with Neon support and now it takes around 10-17s for same example.

Command used: **make -f tensorflow/contrib/makefile/Makefile HOST_OS=PI TARGET=PI  OPTFLAGS="-Os -mfpu=neon -funsafe-math-optimizations -ftree-vectorize"**

Is there anything I am missing?

### System information
- **Have I written custom code**: No
- **OS Platform and Distribution**: Yocto debian flavour
- **TensorFlow installed from**:  source (27a9808)
- **TensorFlow version**: NA
- **Bazel version (if compiling from source)**: Not used
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: NA

**Comment by drpngx** [comment]
@petewarden do these number look reasonable? 20x?

**Comment by petewarden** [comment]
It's good to see that NEON helps. It's hard to say exactly what performance you should be getting without knowing more about your model, and exactly which i.mx6 chip you're using, but a 10x slowdown on a low-power chip versus a laptop doesn't seem too crazy.

**Comment by drpngx** [comment]
@gunasekaran7, closing since it looks like you are getting reasonable performance. If you have a more specific issue, let us know.

**Comment by gunasekaran7** [comment]
@petewarden, I am using i.mx6 QuadCore from NXP.

**Comment by Air000** [comment]
@gunasekaran7 Hi, could you please tell me how to cross-compile tensorflow c++ module on i.mx6? Thank you so much!

**Comment by gunasekaran7** [comment]
@Air000 , I used this [link](https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md)

**Comment by Air000** [comment]
@gunasekaran7 Thanks! I successfully ported tensorflow to i.MX6! 
But I meet another issue, when I run the benchmark or label_image, it comes out with messages like "E tensorflow/core/framework/op_kernel.cc:1142]", but it also says "Running model succeeded!" at the end. I don't know what it means by "E tensorflow/core/framework/op_kernel.cc:1142".

**Comment by gunasekaran7** [comment]
@Air000, Were you able to see the class label output on the terminal?

**Comment by Air000** [comment]
@gunasekaran7, Yes, output as following:
```
2017-06-28 09:53:25.282150: I tensorflow/contrib/pi_examples/label_image/label_image.cc:379] Running model succeeded!
2017-06-28 09:53:25.296182: I tensorflow/contrib/pi_examples/label_image/label_image.cc:273] military uniform (866): 0.647334
2017-06-28 09:53:25.296287: I tensorflow/contrib/pi_examples/label_image/label_image.cc:273] suit (794): 0.0477206
2017-06-28 09:53:25.296338: I tensorflow/contrib/pi_examples/label_image/label_image.cc:273] academic gown (896): 0.0232351
2017-06-28 09:53:25.296390: I tensorflow/contrib/pi_examples/label_image/label_image.cc:273] bow tie (817): 0.0157328
2017-06-28 09:53:25.296439: I tensorflow/contrib/pi_examples/label_image/label_image.cc:273] bolo tie (940): 0.0144991
```

**Comment by gunasekaran7** [comment]
@Air000. then you are good to go.its working fine..
