### ISSUE TITLE
import tensorflow Segmentation fault

### ISSUE THREAD

**Issue by vi77** [tensorflow/tensorflow#9263]
I get 'Segmentation fault' everytime when import tensorflow.
No matter which tf's version, or which numpy's version i try. Or even 'import numpy' at first.
My computer is CentOS6.5 with python 2.7.3.
Current tensorflow's version is 'https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.0-cp27-none-linux_x86_64.whl'.
BTW: it happends after i try to update my glibc. cause i met "version `GLIBC_2.14' not found" and "version `GLIBC_2.16' not found" before.

**Comment by vi77** [comment]
And GDB shows me this:

[Thread debugging using libthread_db enabled]
Missing separate debuginfo for /home/tools/Python/lib/python2.7/site-packages/numpy/core/../.libs/libgfortran-ed201abd.so.3.0.0
[New Thread 0x7ffff3244700 (LWP 29968)]
[New Thread 0x7ffff2843700 (LWP 29969)]
[New Thread 0x7fffefe42700 (LWP 29970)]
[New Thread 0x7fffed441700 (LWP 29971)]
[New Thread 0x7fffeaa40700 (LWP 29972)]
[New Thread 0x7fffe803f700 (LWP 29973)]
[New Thread 0x7fffe563e700 (LWP 29974)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7bc678b in init_one_static_tls (map=0x0) at allocatestack.c:1171
1171	  void *dest = (char *) curp - map->l_tls_offset;
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.192.el6.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-57.el6.x86_64 libcom_err-1.41.12-22.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 openssl-1.0.1e-48.el6_8.4.x86_64 zlib-1.2.3-29.el6.x86_64

**Comment by drpngx** [comment]
Sorry, we don't support CentOS below 7. It looks like there is the wrong glibc. I would suggest installing from source in that case.

**Comment by vi77** [comment]
I install it from source and it work. Thanks a lot!

**Comment by drpngx** [comment]
Great, thanks for reporting back!
