### ISSUE TITLE
Install on Windows 10 not working on power shell, but cmd

### ISSUE THREAD

**Issue by 4F2E4A2E** [tensorflow/tensorflow#9264]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10 Pro Version 1607 amd64 
- **TensorFlow installed from (source or binary)**:
Install via native pip or anaconda via:
```
conda create -n tensorflow python=3.5
```
- **TensorFlow version (use command below)**:
As described in the get started page:
```
pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.1-cp35-cp35m-win_amd64.whl
```
- **Bazel version (if compiling from source)**: - 
- **CUDA/cuDNN version**: - 
- **GPU model and memory**: - 
- **Exact command to reproduce**: - 
Follow the install instructions [1] on windows using the **power shell** or **git bash** (with or without admin rights)
1: https://www.tensorflow.org/install/install_windows

You can collect some of this information using our environment capture script: https://github.com/tensorflow/tensorflow/tree/master/tools

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
```
### Source code / logs
On running the pip install command, the classic "... wheel is not supported" error comes up:
```
PS C:\Users\user> pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.0.1-cp35-cp35m-win_amd64.whl
tensorflow-1.0.1-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.
```

Using the cmd, everything works just fine and i think, that a lot of people are having this problem out there right now, imho the install doc page must be updated to contain some warnings about this.

Oh and by the way: tensorflow is fucking amazing!

**Comment by drpngx** [comment]
It looks like the powershell environment might be using a different platform.
Follow the command [here](http://stackoverflow.com/questions/28107123/cannot-install-numpy-from-wheel-format) to figure out what version you need.

**Comment by Carmezim** [comment]
Just a question, are you installing outside the conda env and importing tensorflow inside it?

**Comment by 4F2E4A2E** [comment]
@Carmezim I am not saying that it is not possible somehow like you're installing it, the point is, what you're doing does not match the install guide and standard case.

As described above I did follow the install guide for windows via both ways, via native pip and via anaconda _as_ described in the install guide.

P.s.: We are in a loop here, this information has already been given. :)

**Comment by 4F2E4A2E** [comment]
@Carmezim thx for your comment [1] regarding the warnings and unknow op. This should somehow match the install guide for ident input (guide examples) and output.

1: https://github.com/tensorflow/tensorflow/issues/7778#issuecomment-281678077

**Comment by Carmezim** [comment]
@4F2E4A2E It does match the standard case as in it was installed satisfying all requirements in the Docs and with the code you provided that generated error for you on PowerShell. 
If you're referring calling pip globally or using the script it won't make any difference whatsoever. 

So the unsupported wheel error you received is due something wrong on your side and not a TensorFlow bug. One case for instance is if you have more than one Python installation which is not 3.5 64-bit generating conflicts with pip as it may be linked not to 3.5 but to other version. I am not sure if this is your situation.

The only thing I didn't test was to use a conda environment on PowerShell.

**Comment by 4F2E4A2E** [comment]
Thanks, i guess you're referring to https://github.com/tensorflow/tensorflow/issues/9273 right? :)

**Comment by Carmezim** [comment]
@4F2E4A2E I am referring to the unsupported wheel error you've got trying to install TensorFlow through Powershell, which is not a TensorFlow bug neither Powshell's but derived from a misconfiguration on your side. Then I mentioned one possible and common cause of this error which is multiple python installations and `pip` linking to an unsupported one (e.g. 2.7, 3.6 etc in this case).

The issue 9273 is a different situation non related to the problems you reported.

The only case to be addressed now is if there is any conflict using TensorFlow in a conda environment on PowerShell as you mentioned.

**Comment by Carmezim** [comment]
@4F2E4A2E Hi, did you make any progress? Let us know if you need help with anything else. If you successfully solved this issue can be closed now.

**Comment by 4F2E4A2E** [comment]
I had tensorflow working from the beginning, the only thing I wanted to point out is that if one follows the guide it won't work in some cases. I am glad you found the cause of this problem, you also sure did test it in a clean environment and can to 100% exclude any problems with the install procedure. Great job! 👍 
> which is not a TensorFlow bug neither Powershell's but derived from a misconfiguration on your side.
