### ISSUE TITLE
cannot compile pip package after update to the HEAD

### ISSUE THREAD

**Issue by seranity** [tensorflow/tensorflow#927]
error as follows:

$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

ERROR:./tensorflow/models/embedding/BUILD:10:6: First argument of load() is a path, not a label. It should start with a single slash if it is an absolute path..
ERROR: ./tensorflow/models/embedding/BUILD:10:6: file '/tensorflow:tensorflow.bzl.bzl' was not correctly loaded. Make sure the 'load' statement appears in the global scope in your file.
ERROR: ./tensorflow/models/embedding/BUILD:104:1: name 'tf_gen_op_wrapper_py' is not defined.
ERROR: ./tensorflow/tools/pip_package/BUILD:13:1: Target '//tensorflow/models/embedding:package' contains an error and its package is in error and referenced by '//tensorflow/tools/pip_package:build_pip_package'.
ERROR: Loading failed; build aborted.

which work well before update to the Newest version.

**Comment by phsmit** [comment]
I had the same problem and it was solved after updating bazel to version 0.1.4

**Comment by delip** [comment]
I'm having the same problem with similar error messages (see issue https://github.com/tensorflow/tensorflow/issues/937). However, after following @phsmit's suggestion, I upgraded my Bazel installation, and those message went away. Now I'm getting a different set of errors instead:

```
$ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
ERROR: /Users/delip/Softwares/tensorflow/WORKSPACE:73:1: iron-ajax is not a legal workspace name.
ERROR: /Users/delip/Softwares/tensorflow/WORKSPACE:80:1: iron-dropdown is not a legal workspace name.
ERROR: /Users/delip/Softwares/tensorflow/WORKSPACE:87:1: accessibility-developer-tools is not a legal workspace name.
```

Any ideas on how to fix this?

**Comment by vrv** [comment]
Did you upgrade to 0.1.4 or bazel master?  0.1.4 should work.  master probably doesn't right now, because they changed the legal names of entries in WORKSPACE files.  I suspect they'll update our WORKSPACE file before their next official release.

**Comment by delip** [comment]
@vrv, You're right (as always)! I had built bazel from HEAD. Recompiled Bazel from tag 0.1.4 and now TensorFlow compile is progressing. Thanks!
