### ISSUE TITLE
[Docs] Update wheels URLs to match latest TensorFlow release (1.1.0)

### ISSUE THREAD

**Issue by Carmezim** [tensorflow/tensorflow#9273]
The wheels available on the website are from the previous release (1.0.1) which still contain OpKernels errors that are solved at head (as well as on 1.1.0) and can be ignored but are confusing users prompting repeated reports of this issue.

**Comment by drpngx** [comment]
What errors are you thinking of? Which release points?

@av8ramit @yifeif for cherry-picking.

**Comment by Carmezim** [comment]
@drpngx It's fixed has been a long time but for some reason it didn't make it to 1.0.1.
#8500 #8724 #8525 #7859 #8644 are some reports of the same problem. 
The issue itself is harmless but confusing users

**Comment by drpngx** [comment]
Oh yes, I was on some of those threads. Thanks for making the connection! We should definitely think about some remediation action, either cherry pick or add some kind of informative unsupported message, or add some docs.

**Comment by yifeif** [comment]
Thanks for reporting this @Carmezim! We usually do not update the binary [urls](https://www.tensorflow.org/install/install_linux#the_url_of_the_tensorflow_python_package) for RCs. But official 1.1.0 should be out very soon.

**Comment by drpngx** [comment]
@yifeif so action is to wait for `1.1`?

**Comment by Carmezim** [comment]
Got it. Do you think would be interesting to add a temporary note to common issues for instance, or point users to the PYPI packages that are already compliant with the latest version?

Now is closer to the official release than when most of these issues were reported so I don't know if it makes sense for you guys.

**Comment by yifeif** [comment]
Went through the issues @Carmezim linked to again and it looks like most people saw this issue were using "pip install tensorflow", which by default, does not install release candidates. We can add an entry under ["Common Installation Problem"](https://www.tensorflow.org/install/install_windows#common_installation_problems) to comment on the issue on 1.0.1 binary for future references. I'll send a PR.

**Comment by Carmezim** [comment]
At the time those issues did arise also 1.0.1 was on PYPI (before March 24) which now contains 1.1rc2 so it will probably only affect those following the Anaconda and virtualenv instructions that point to install with the official 1.0.1 binary. That may help narrow down the possible affected users

**Comment by yifeif** [comment]
PR merged. Website will be updated with the 1.1.0 release(cc @av8ramit). Closing this issue. Thanks!
