### ISSUE TITLE
incorrect datasets path in tutorial: tf.contrib.learn.datasets.base.load_csv_with_header

### ISSUE THREAD

**Issue by 4d55397500** [tensorflow/tensorflow#9275]
The path for loading the iris dataset " tf.contrib.learn.datasets.base.load_csv_with_header" in the tutorial is incorrect:

`# Load datasets.
  training_set = tf.contrib.learn.datasets.base.load_csv_with_header(
      filename=IRIS_TRAINING,
      target_dtype=np.int,
      features_dtype=np.float32)
  test_set = tf.contrib.learn.datasets.base.load_csv_with_header(
      filename=IRIS_TEST,
      target_dtype=np.int,
      features_dtype=np.float32)
`

I believe it should be something closer to the README here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/README.md

`import tensorflow.contrib.learn.python.learn as learn
from sklearn import datasets, metrics

iris = datasets.load_iris()`

**Comment by jart** [comment]
What do you mean by path? You mean the variable? The documentation links to another page where it's defined. https://www.tensorflow.org/get_started/tflearn

**Comment by 4d55397500** [comment]
I get an "ImportError": there is no path tf.contrib.learn.datasets and no "tf.contrib.learn.datasets.base.load_csv_with_header" in the documentation referenced [https://www.tensorflow.org/get_started/tflearn](https://www.tensorflow.org/get_started/tflearn).
