### ISSUE TITLE
Ability to Create New Device Context (GPU)

### ISSUE THREAD

**Issue by yazeedalrubyli** [tensorflow/tensorflow#9278]
If I destroyed GPU context for any reason and tried to start new tensorflow session I got this error `CUDA_ERROR_CONTEXT_IS_DESTROYED ` and notebook kernel crashes. So, it will be a nice feature for python users if they can create a new context for tensorflow if one is destroyed.

**Comment by drpngx** [comment]
How did you destroy the GPU context in the first place?

**Comment by yazeedalrubyli** [comment]
numba.cuda.close()

http://numba.pydata.org/numba-doc/0.32.0/cuda-reference/host.html?highlight=reset#numba.cuda.close

**Comment by drpngx** [comment]
I don't think you can recover from a context close. This is not a supported scenario, so I am closing this.

**Comment by yazeedalrubyli** [comment]
I don't want to recover to a closed context, I want a new context to process tensoerflow operations. As I understand that Tensorflow uses more than one stream within the same context to accelerate data processing from host to device and vice-versa. Someone needs to set these up manually, it will be nice to be handled in one call. 

Thanks anyway

**Comment by drpngx** [comment]
I am not sure I understand. Are you talking about `with tf.device`?

**Comment by yazeedalrubyli** [comment]
No....I'll try to respond later in more detail.
