### ISSUE TITLE
Check failed: NDIMS == dims() (2 vs. 1)

### ISSUE THREAD

**Issue by LucasMahieu** [tensorflow/tensorflow#9282]
I get the following error after building the graph of my NN. when I try to execute :

loss, _ = self._sess.run([self.loss_op, self.train_op], feed_dict=feed_dict)

I get this error :

`F tensorflow/core/framework/tensor_shape.cc:36] Check failed: NDIMS == dims() (2 vs. 1) Asking for tensor of 2 dimensions from a tensor of 1 dimensions`

I don't succeed to know to which part of the graph this error is related to ... Because, normaly the graph is build, so shapes should be correct ... are not ? 

I am using Tensorflow version 1.0.0 with python API.

It could be a bug according to the first reply here : http://stackoverflow.com/questions/43413293/tensorflow-check-failed-ndims-dims-2-vs-1

**Comment by drpngx** [comment]
That seems like a bug. Could you share the simple possible repro you can find?

**Comment by LucasMahieu** [comment]
I succeed to find the source of the error.
It was caused by the bad shape of an input tensor of a custom op.
I have create a custom op, coded in C++, used in Python. 
I think an improvement could be done in the error message. Indeed, with this line only, it is difficult to find the source of this error.
