### ISSUE TITLE
Save model every fixed number of steps with MonitoredTrainingSession

### ISSUE THREAD

**Issue by oranshayer** [tensorflow/tensorflow#9283]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 0.12
- **CUDA/cuDNN version**: 7.5 / 5.1
- **GPU model and memory**: GTX 1080

### Describe the problem

Is it possible to save model every fixed number of steps with MonitoredTrainingSession?
If not, would be happy to see it as a feature.

**Comment by ducta-qc** [comment]
`tf.train.CheckpointSaverHook` can answer your quesion

**Comment by oranshayer** [comment]
Thanks!
