### ISSUE TITLE
TensorBoard filter regresson

### ISSUE THREAD

**Issue by hholst80** [tensorflow/tensorflow#9285]
### System information

Docker image `tensorflow/tensorflow:nightly` (or 1.1.0rc2)

### Describe the problem

Start a tensorboard process

```
tensorboard --logdir /efs/log/atari
```

and try and filter. It does not have any effect.

![image](https://cloud.githubusercontent.com/assets/6200749/25130135/6499f98c-2441-11e7-8050-34cce130fef0.png)

**Comment by cancan101** [comment]
This isn't a performance bug; filtering on rc2 for tensorboard is just broken.

**Comment by cancan101** [comment]
@dandelionmane It looks like TF 1.1 is shipping. Did this get fixed?

**Comment by cancan101** [comment]
Ping on this. Looks like filtering is broken in the TF1.1 wheel on Pypi.

**Comment by taion** [comment]
This is a pretty significant usability problem with TensorBoard. We often run TensorBoard on directories with many runs, and being unable to filter runs by name makes it very difficult to do useful things with TensorBoard.

**Comment by foxik** [comment]
Confirming filtering is broken in TF 1.1 Linux CPU PyPI wheel.

**Comment by foxik** [comment]
Also reported in #9519.

**Comment by hadware** [comment]
Broken for me as well.

OS: Linux Ubuntu 16.04
installed binary via pip3

**Comment by taion** [comment]
This regression happened somewhere between rc1 and rc2, BTW.

**Comment by dandelionmane** [comment]
Thanks for the report. This is fixed at master, so the bug won't be present in the next release.

**Comment by taion** [comment]
I am seeing this fixed on the nightly. Thanks!

**Comment by hadware** [comment]
Yup, installed the nightly, seems to be fixed. Maybe it's that crazy html5lib-0.9999 that's fixing it?
