### ISSUE TITLE
Java API - sophisticated example

### ISSUE THREAD

**Issue by szingerpeter** [tensorflow/tensorflow#9288]
Dear All,

I have seen the [example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/main/java/org/tensorflow/examples/LabelImage.java) for importing model created and trained in Python imported into Java code and used for predictions.  However, I had some problems understanding what was actually going on especially in [this block](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/main/java/org/tensorflow/examples/LabelImage.java#L92-L101) and [this block](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/main/java/org/tensorflow/examples/LabelImage.java#L156-L207). Would it be possible to get some more documentation on it?
Moreover, I know the Java API is still under construction. However, I would be interested in if it is possible to see some more sophisticated examples, if it is possible including:

- importing model into Java and then performing training on the model

- implementing, training, evaluating, saving, loading a model from scratch in Java

Thank you for any help!

Cheers,
Peter

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

@asimshankar
