### ISSUE TITLE
Tensorflow 1.1 build breaks on CUDA code

### ISSUE THREAD

**Issue by kdjaks** [tensorflow/tensorflow#9296]
### System Information
- *OS Platform and Distribution (i.e. Linux Ubuntu 16.0)*: Linux Ubuntu 17.04
- *TensorFlow installed from (source or binary)?*: source
- *TensorFlow version* (use command below): v1.1.0-rc2
- *Bazel version (if compiling from source)*: 0.4.5
- *CUDA/cuDNN version*: 8.0/5.1.5
- *GPU Model and Memory*:M2000M

### Describe the problem clearly

Fails to build after upgrade to Ubuntu 17.04 (from 16.10), using the same compiler (gcc 5.4.1) and compiler flags. 

Build command is `bazel build --config=opt --config=cuda //tensorflow/
tools/pip_package:build_pip_package`

I've tried compiling with the default -march=native and -march=core-avx-i as well as using command given [here](http://stackoverflow.com/a/41584791)

### Source Code / Logs
`From Compiling tensorflow/core/kernels/fake_quant_ops_gpu.cu.cc:
/usr/lib/gcc/x86_64-linux-gnu/5/include/avx512fintrin.h(9218): error: argument of type "const void *" is incompatible with parameter of type "const float *"`

Same error is then repeated for different parameter types (ex. const long/int *)

**Comment by drpngx** [comment]
Can you paste the log somewhere? Where does it trigger from `fake_quant_ops_gpu.cu.cc`?

**Comment by kdjaks** [comment]
Ok, compiling with gcc-4.9 seems to work. Closing since I'm pretty sure this was a compiler issue which I believe is explicitly not supported by cuda 8.0 (ie. gcc 5.4.1). 

Sorry for not trying that before posting here. I assumed it would work since I thought it was the same compiler as before the upgrade. Also apologies for the slow follow up.

Regarding the question, I don't believe it was specific to fake_quant_ops_gpu.cu.cc but rather was triggered from the first gpu op the encountered (ex. gru_ops_gpu.cu.cc, l2loss_op_gpu.cu.cc).

Thank you for the quick response.
