### ISSUE TITLE
Retrieve a graph or model without copying the graph construction code

### ISSUE THREAD

**Issue by amirmazaheri1990** [tensorflow/tensorflow#9297]
Hi,

Let's say I have defined a graph and trained the weights in file "myTrain.py" and I saved the model using `tf.train.saver()` in a directory.

I want to have a tester file (let's name it "myTest.py") which doesn't contain the definition of the graph, but be able to load the saved graph and also the trained weights and I can use it as I was using in "myTrain.py". For example, pass a new batch with `feed_dict` and get the desired outputs.

I know there are many sources about how to save and restore the graph, but all of them are confusing or they have the definition of the graph as a piece of code written before loading the saved model which I believe shouldn't be needed.

I appreciate any help.

Thanks

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
