### ISSUE TITLE
Making TF consume least GPU memory as default

### ISSUE THREAD

**Issue by wangdelp** [tensorflow/tensorflow#9299]
Hi there, 

By default, TF takes all GPU memory available on the machine, even if very few memory are actually needed. This would prevent running other processes and lead to Out of Memory errors. 

Although we can use GPU options to set the GPU amount, but sometimes we are running others' codes and do not want to bother or forget to add GPU configurations to make it consumes less memory. Consider most people are using shared machines, it would bring difficulties for other users of GPU server very often.

The default configuration of using all GPU memory may have some benefits that I am not totally aware of, but I wonder if the benefits outweigh the drawbacks of doing that. Therefore, I wonder if TF could make it consume least GPU memory as default.

**Comment by drpngx** [comment]
Thanks for your input @wagonhelm ! Unfortunately that's not something that we'll do at this point.

You can use http://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory (see both answers).
