### ISSUE TITLE
 build failed!  File "/usr/lib/python2.7/encodings/__init__.py", line 123       raise CodecRegistryError,\

### ISSUE THREAD

**Issue by andyyuan78** [tensorflow/tensorflow#93]
ubgpu@ubgpu:~/github/tensorflow$ PYTHONPATH=/usr/lib/python2.7 bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
Fatal Python error: Py_Initialize: Unable to get the locale encoding
  File "/usr/lib/python2.7/encodings/__init__.py", line 123
    raise CodecRegistryError,\
                            ^
SyntaxError: invalid syntax
Aborted (core dumped)
ubgpu@ubgpu:~/github/tensorflow$

**Comment by Foorack** [comment]
I would recommend trying to unset PYTHONPATH. It is generally not needed, and it causes things to break like this. I do not work for Google, just thought that it may help you as I have read about this problem before. :smiley:

**Comment by andyyuan78** [comment]
ubgpu@ubgpu:~/github/tensorflow$ echo $PYTHONPATH

ubgpu@ubgpu:~/github/tensorflow$ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Aborted (core dumped)
ubgpu@ubgpu:~/github/tensorflow$

**Comment by andyyuan78** [comment]
I am a Chinese , and I cannot access google.com to search info

**Comment by andyyuan78** [comment]
solved.

I forget set the bazel path, also , I install multi version of python

**Comment by velvetcake** [comment]
@andyyuan78 hi，What was the solution to this? I'm facing the same issue.what‘s the bazel path?

**Comment by ConnieWangYuan** [comment]
I met the same error. Please show the solution.
