### ISSUE TITLE
Quantized graph fails to work on NVIDIA Jetson TX1 architecture although it worked on a normal PC?

### ISSUE THREAD

**Issue by kwotsin** [tensorflow/tensorflow#9301]
### System Information
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*:
No
- *OS Platform and Distribution (i.e. Linux Ubuntu 16.0)*:
Ubuntu 16.04 LTS on NVIDIA Jetson TX1 (Linux for Tegra 24.1)
- *TensorFlow installed from (source or binary)?*:
Compiled from source and installed via this wheel available here: https://github.com/rwightman/tensorflow/releases/tag/v1.0.0-alpha-tegra-ugly_hack
- *TensorFlow version* (use command below):
1.0 Alpha
- *CUDA/cuDNN version*:
8.0/5.1
- *GPU Model and Memory*:
Tegra X1, 4GB

### Describe the problem clearly
When I ran a quantized graph on my laptop, it works quite as expected (just slightly lower accuracy compared to the frozen graph, while much lower size). However, when I transferred the exact same quantized graph to run on an Jetson TX1, the file gives me a highly inaccurate class prediction, at a 100% probability for the random class. On the other hand, when I tried to perform inference from the frozen graph (from which the quantized graph was derived) on both my laptop and the Jetson TX1, I got the exact same answers as expected.

So I suspected it could have been an issue of data transfer causing the file to be slightly corrupted. I checked the files byte by byte at all points of transfer (from my laptop to memory stick, then memory stick to the Jetson), but I found the files are exactly the same. This is the command I used to check: `cmp $old_file $new_file || echo "different files"`.

Thus, I am suspecting it could be an issue of how tensorflow performs on the Jetson TX1 ARM architecture (aarch64). Is there anyway to verify this, and if it is indeed a performance issue on an ARM architecture, is there a way to resolve this?

Thank you for your help.

**Comment by drpngx** [comment]
@andrewharp might be more up-to-date on the Jetson progress.

**Comment by andrewharp** [comment]
The random single-category symptom is the same as the issue seen in https://github.com/tensorflow/tensorflow/issues/7150#issuecomment-282343046

As @andrehentz suggests there, maybe try quantizing with both quantize_weights and quantize_nodes?

**Comment by kwotsin** [comment]
Thanks for your reply! Do you have an example of how this could be done? I have always thought there was only one quantization function available (for the weights). What is the difference between quantizing the weights vs the nodes?

**Comment by andrehentz** [comment]
@kwotsin 

The "official" way to quantize a graph is described [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md#eight-bit-calculations), but I'm in the process of updating it slightly. In any case, I think the problem you are encountering is unrelated to the actual quantization steps.

My theory is that a different code path is triggered on a Jetson, because it supports NEON instructions. I'll try to get a fix in the nightly builds before the end of next week. Meanwhile, if you'd like to build it yourself, try:
`bazel build -c opt --copt="-DTENSORFLOW_DISABLE_META" //tensorflow/contrib/android:libtensorflow_inference.so --config=android_arm`
(or the equivalent for your architecture)

**Comment by kwotsin** [comment]
@andrehentz I have tried building TF from source but with not very much success. The furthest version of TF I've gotten to is the one available here: https://github.com/rwightman/tensorflow/releases/tag/v1.0.0-alpha-tegra-ugly_hack. Would this be a cause of the issue? 

However, for the quantization, I run it on my host machine. Regarding the android:libtensorflow_inference file you mentioned to build, do I run the graph_transform tool or quantize_graph tool after building that with bazel?

**Comment by andrehentz** [comment]
Let's  always use `graph_transform` (because `quantize_graph` is slowly becoming obsolete).

The recent fixes affect both quantization (which you are running on your hose) and inference, which I understand you are running using the tegra-ugly_hack. Apart from updating that to get the fixes, you could try manually replicating the relevant change: https://github.com/tensorflow/tensorflow/commit/2e85e1c2c1d8d3b9f404fd110ca7ffd34a046f65

**Comment by kwotsin** [comment]
Thanks for your fix! May I know if I need to rebuild the `graph_transform` tool via bazel with a fresh install of TF? I am still using TF 1.01, and have rebuilt the `graph_transform` tool with bazel, and used only `quantize_weights` from the `graph_transform` tool. However, I'm still getting the very random classes predicted with low accuracy.

I have also tried `quantize_weights` and `quantize_nodes` together, which gives me a better performance at 43% confidence. However, what's strange is before I rebuilt the tool, using the old `graph_transform` tool, I was getting 46% confidence for my predictions. But using `quantize_graph`, I got 69% confidence instead. To compare, the frozen (not quantized) graph gives me an 81% confidence.

Do I need to update the entire TF 1.01 on my host machine? If I do so, will there be huge conflicts in developing for Jetson which uses the ugly hack? Is there any way to upgrade the Jetson's ugly hack to a later version?

**Comment by andrehentz** [comment]
1) Yes, please build the graph_transform tool with a fresh install. It is OK to keep both on your host machine, just download the fresh install to a separate directory.

2) Be sure to use all the transforms for 8-bit calculations:
```
bazel build tensorflow/tools/graph_transforms:transform_graph
bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=./frozen_model_inception_resnet_v2.pb \
--out_graph=./quantized_weights_and_nodes_inception_resnet_v2.pb \
--inputs='Placeholder_only' \
--outputs='InceptionResnetV2/Logits/Predictions' \
--transforms='
  add_default_attributes
  strip_unused_nodes(type=float, shape="1,299,299,3")
  remove_nodes(op=Identity, op=CheckNumerics)
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  quantize_weights
  quantize_nodes
  strip_unused_nodes
  sort_by_execution_order'
```

3) Sorry I can't help with the Jetson's hack. As I said earlier, you can try applying the relevant changes manually.

**Comment by kwotsin** [comment]
@andrehentz  I tried to building with the fresh install but have gotten this error instead:

```
ERROR: /home/kwotsin/tensorflow-android/tensorflow/tensorflow/core/BUILD:1363:1: no such target '//tensorflow/tools/git:gen/spec.json': target 'gen/spec.json' not declared in package 'tensorflow/tools/git' defined by /home/kwotsin/tensorflow-android/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /home/kwotsin/tensorflow-android/tensorflow/tensorflow/core/BUILD:1363:1: no such target '//tensorflow/tools/git:gen/head': target 'gen/head' not declared in package 'tensorflow/tools/git' defined by /home/kwotsin/tensorflow-android/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /home/kwotsin/tensorflow-android/tensorflow/tensorflow/core/BUILD:1363:1: no such target '//tensorflow/tools/git:gen/branch_ref': target 'gen/branch_ref' not declared in package 'tensorflow/tools/git' defined by /home/kwotsin/tensorflow-android/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: Analysis of target '//tensorflow/tools/graph_transforms:transform_graph' failed; build aborted.
INFO: Elapsed time: 0.817s
```

Are some things left out in the BUILD files? I am not very sure about this as I've never seen how such a code is being written or how it's getting processed.

**Comment by andrehentz** [comment]
Sorry @kwotsin . I don't know what those errors are about. I usually build like this:
```
  $ git clone https://github.com/tensorflow/tensorflow 
  $ cd tensorflow
  $ ./configure
  $ bazel build tensorflow/tools/graph_transforms:all
```
I just tried them.
(The full instructions are on tensorflow's website)

**Comment by kwotsin** [comment]
@andrehentz the transform_graph works very well currently. I am seeing a better accuracy compared to using quantize_graph, and the inference speed is also faster. 

As for the Jetson, I realized the problem of running the quantized graph obtained from the transform_graph tool comes from the TF version (1.0 alpha) not having any quantized operation functions (e.g. QuantizeMul) at all. So I'm trying to update the TF version to something higher that has these operations available.

**Comment by rajnamitha** [comment]
@kwotsin I experience error "No op named QuantizedMul", so as you specified I tried upgrading tensorflow to 1.1 version. I am new to TensorFlow, I hope the configuration I select is okay. I need the quantized model for image classifier application (I am not using GPU). When I try to ./configure, I am leaving only default setting without enabling any support like MKL, GPU, CUDA, etc. 

I am using the above command given by andrehentz to do the quantization. However, I get error "ValueError: No op named QuantizedAdd in defined operations" now. Am I missing some necessary step that the model generated by transform_graph doesn't work for me?  

I am not getting response for this problem if I post in StackOverflow. I hope to find help here. Thank you.

**Comment by kwotsin** [comment]
What platform are you running the device on? You mentioned you tried upgrading the tensorflow version - did you succeed in the end? What is your version of TF now? IMO, I think those operations should come prepackaged with the newer versions of TF, so there shouldn't be anything extra to be built (not very sure about this though).

**Comment by rajnamitha** [comment]
I am running on Mac. I have Tensorflow verison 1.1, the upgrade was successful. after that I did "bazel build tensorflow/tools/graph_transforms:all" and did the transform_graph operation using :

bazel-bin/tensorflow/tools/graph_transforms/transform_graph \
--in_graph=./frozen_model_inception_resnet_v2.pb \
--out_graph=./quantized_weights_and_nodes_inception_resnet_v2.pb \
--inputs='Placeholder_only' \
--outputs='InceptionResnetV2/Logits/Predictions' \
--transforms='
  add_default_attributes
  strip_unused_nodes(type=float, shape="1,299,299,3")
  remove_nodes(op=Identity, op=CheckNumerics)
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  quantize_weights
  quantize_nodes
  strip_unused_nodes
  sort_by_execution_order'

However I get "ValueError: No op named QuantizedAdd in defined operations." when "tf.import_graph_def(graph_def, name='')" is called.

**Comment by chandrakantkhandelwal** [comment]
@rajnamitha Upgrade to r1.2, and you will not face this issue.  Also while using the transformed graph if you get following error in r1.2 : 
tensorflow.python.framework.errors_impl.InvalidArgumentError: Retval[0] does not have value

Take off  'remove_nodes(op=Identity, op=CheckNumerics)' from the 'transforms' part, refer issue #1721

**Comment by rajnamitha** [comment]
@chandrakantkhandelwal : I upgraded and tried but I still face same error:
```
1.2.0
Traceback (most recent call last):
  File "/Users/d068680/PycharmProjects/misc/Accuracy_Test/resnet_quantized_eval_pb.py", line 102, in <module>
    main()
  File "/Users/d068680/PycharmProjects/misc/Accuracy_Test/resnet_quantized_eval_pb.py", line 57, in main
    tf.import_graph_def(graph_def, name='')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 283, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named QuantizedAdd in defined operations.

Process finished with exit code 1
```

However, I have already opened an issue but still no help w.r.t. accuracy of the results for the the solution provided in the following issue. 
[https://github.com/tensorflow/tensorflow/issues/10739](url)

**Comment by chandrakantkhandelwal** [comment]
@rajnamitha I am using python 2.7, so cannot comment about the behaviour in python 3.5

I think there is a way to verify if QuantizedAdd op is supported by your build!
In tensorflow/core/kernels:BUILD, look for the following part. 

tf_kernel_library(
    name = "quantized_ops",
....)

If there is a "quantized_add_op.cc" is mentioned in it, then this op is supported by your build. And there should be a file with the same name in 'core' folder.

I came to this conclusion after comparing the BUILD file of r1.1 and r1.2
However even I am facing the accuracy drop issue with the quantized model.

**Comment by rajnamitha** [comment]
@chandrakantkhandelwal : I have tried installing tensorflow from source code as mentioned in my issue (10739). In that I don't face QuantizedAdd during the import model step. Whereas, it throws error during inference when I quantize the model using "Graph_transform" tool. I was told to modify quantize node option to quantize_nodes(fallback_min=-10, fallback_max=10). Which again provides 0 accuracy in result.
https://github.com/tensorflow/tensorflow/issues/10739

 And yes, drop in accuracy is expected for quantized model as it uses 8-bit calculation unlike conventional 32-bit. But for inception-resnet-v2 model accuracy is 0% (when I quantize it using quantization tool). If resnet-v2 model is not meant to be quantized is still a question. Because for inception-v3 and inception-v4 there was slight drop in accuracy but not like in resnet-v2 model.

**Comment by kwotsin** [comment]
@rajnamitha you can try removing `remove_nodes` and `quantize_nodes` and see if the accuracy drop still persists.

**Comment by dksb** [comment]
This is an old issue. Can you please retry using the newer version of TensorFlow. I will close this issue, please create a new issue using one of the issue templates if you are still facing this issue?
