### ISSUE TITLE
Import additional RNNCells in tf.contrib.rnn.__init__.py 

### ISSUE THREAD

**Issue by feiga** [tensorflow/tensorflow#9303]
Some RNNCells, like IntersectionRNNCell, NASCell, are implemented in tf.contrb.rnn.python.ops.rnn_cell. I would like to try these cells but found that these can't be used as the same way as LSTMCell, which I can import by ```from tf.contrib.rnn import LSTMCell```. I checked the code found that these cells are not imported by ```tf.contrib.rnn.__init__.py ```. 

Is there any way to try these cells? Or is it possible to import these cells in ```tf.contrib.rnn.__init__.py ```.

Thanks.

**Comment by drpngx** [comment]
Yes, you have to add a reference in the [docstring](http://google3/third_party/tensorflow/contrib/rnn/__init__.py?l=44). Feel free to send a PR and CC @ebrevdo

**Comment by feiga** [comment]
PR, https://github.com/tensorflow/tensorflow/pull/9327

**Comment by drpngx** [comment]
Thanks!
