### ISSUE TITLE
Problem displaying Chinese character in Tensorboard Embedding

### ISSUE THREAD

**Issue by Jeffery4000** [tensorflow/tensorflow#9304]
I am trying to display an embedding but what its show is all garbled. May i know does Tensorboard Embedding able to display Chinese character?
May i know its that possible to display more than 100K point? If yes, how to i do the configuration?
![default](https://cloud.githubusercontent.com/assets/27762422/25168360/cf775996-2515-11e7-8fa1-326d06e6d045.PNG)

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by falcondai** [comment]
yes, you can display Chinese in tensorboard embedding. Make sure you use UTF-8 encoding in your metadata file.
