### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

### ISSUE THREAD

**Issue by vamshi-indla** [tensorflow/tensorflow#9306]
**Error Log:**
model = Sequential()

Traceback (most recent call last):

  File "<ipython-input-50-24a4d47a09aa>", line 1, in <module>
    model = Sequential()
...
/anaconda/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 47, in get_uid
    if graph not in _GRAPH_UID_DICTS:

**_AttributeError: module 'tensorflow' has no attribute 'get_default_graph'_**

------------
**Versions:**
!pip3 show tensorflow
Name: tensorflow
Version: 1.0.1
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: numpy, protobuf, six, wheel

------------
!pip3 show keras
Name: Keras
Version: 2.0.3
Summary: Deep Learning for Python
Home-page: https://github.com/fchollet/keras
Author: Francois Chollet
Author-email: francois.chollet@gmail.com
License: MIT
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: six, theano, pyyaml

------------
**OS:**:  Mac OS
------------

I couldnt find any solution to it in "existing issues" nor on "Stackoverflow".
Any suggestions?

**Comment by drpngx** [comment]
That seems to be a mismatch in keras, not tensorflow. Sorry, closing this since this is not a tensorflow bug.

@fchollet
