### ISSUE TITLE
Tensorflow slim - TypeError: softmax_cross_entropy() got an unexpected keyword argument 'weight' 

### ISSUE THREAD

**Issue by Bruczzz** [tensorflow/tensorflow#9309]
Hi ,

I am using slim/train_image_classifier.py to train inception V1 model from scratch on my own dataset and fine-tuning inception V1 model from the link: https://github.com/tensorflow/models/blob/master/slim/README.md#Pretrained

**System Information:**
RAM : 4GB
TensorFlow Version : 1.0
OS  : Linux 14.04 

I am using following command for training from scratch but ended up in Error

```
python train_image_classifier.py     
     --train_dir=${TRAIN_DIR}
     --dataset_name=mydataset 
     --dataset_split_name=train
     --dataset_dir=${DATASET_DIR}
     --model_name=inception_v1 

```

**Note:** Here mydataset is same as flower.py except:

SPLITS_TO_SIZES = {'train': 4310. 'validation': 350}

**Error:**

```
Traceback (most recent call last):
  File "train_image_classifier.py", line 585, in <module>
    tf.app.run()
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train_image_classifier.py", line 482, in main
    clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
  File "/home/purushoth/Downloads/models-master/slim/deployment/model_deploy.py", line 195, in create_clones
    outputs = model_fn(*args, **kwargs)
File "train_image_classifier.py", line 476, in clone_fn
    logits, labels, label_smoothing=FLAGS.label_smoothing, weight=1.0)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 117, in new_func
    return func(*args, **kwargs)
TypeError: softmax_cross_entropy() got an unexpected keyword argument 'weight'
```

I have tried 
      
- upgrading **train_image_classifier.py** file 

- fine - tuning the inception V1 model from existing checkpoint 
  
but still I am facing same error.

Am I doing something wrong ?? Thanks for any help.

**Comment by drpngx** [comment]
The correct parameter name is `weights`, not `weight`.
