### ISSUE TITLE
Text window slider not working on TensorFlow.org Download and Setup page

### ISSUE THREAD

**Issue by EricGT** [tensorflow/tensorflow#931]
On TensorFlow.org - Download and Setup page

https://www.tensorflow.org/versions/master/get_started/os_setup.html

Under Pip Installation
For python3:

the text window slider does not allow you to slide to the right. 

If works for the text window slider above under Install TensorFlow:

As a work around you can visit the instructions on the GitHub page

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md

**Comment by martinwicke** [comment]
It works for me. What browser are you using?

**Comment by martinwicke** [comment]
Closing. Please reopen with more information if it persists.
