### ISSUE TITLE
Is tf.train.import_meta_graph() contextual with tf.global[local]_variables_initializer() ?

### ISSUE THREAD

**Issue by MaeThird** [tensorflow/tensorflow#9310]
**I can use these pieces of codes to continue my training with pre-trained model**:

     tf.reset_default_graph() 
     new_saver = tf.train.import_meta_graph("xxx.meta")
     new_saver.restore(sess, "xxx.ckpt-yyy")

Here the 'tf.reset_default_graph() is necessary'  to solve the 'redefine of ops' issues.But,**when I  launched  forward pass(in another .py file) like** :

     tf.reset_default_graph() 
     new_saver = tf.train.import_meta_graph("xxx.meta")
     new_saver.restore(sess, "xxx.ckpt-yyy")
     images_placeholder = tf.get_default_graph().get_tensor_by_name("image_batch:0")
     embeddings = tf.get_default_graph().get_tensor_by_name("embeddings:0")

**with 'tf.reset_default_graph()' I got** :
"Cannot interpret feed_dict key as Tensor: The name 'save/Const:0' refers to a Tensor which does not exist. The operation, 'save/Const', does not exist in the graph"
**without 'tf.reset_default_graph()'  and with 'tf.global[local]_variables_initializer()' before or without it** like:

    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
     new_saver = tf.train.import_meta_graph("xxx.meta")
     new_saver.restore(sess, "xxx.ckpt-yyy")
     images_placeholder = tf.get_default_graph().get_tensor_by_name("image_batch:0")
     embeddings = tf.get_default_graph().get_tensor_by_name("embeddings:0")
 #Without initializer
 #sess.run(tf.global_variables_initializer())
 #sess.run(tf.local_variables_initializer())
     new_saver = tf.train.import_meta_graph("xxx.meta")
     new_saver.restore(sess, "xxx.ckpt-yyy")
     images_placeholder = tf.get_default_graph().get_tensor_by_name("image_batch:0")
     embeddings = tf.get_default_graph().get_tensor_by_name("embeddings:0")

I got : "**FailedPreconditionError: Attempting to use uninitialized value...**".But like:
   new_saver = tf.train.import_meta_graph("xxx.meta")
   new_saver.restore(sess, "xxx.ckpt-yyy")
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
   images_placeholder = tf.get_default_graph().get_tensor_by_name("image_batch:0")
   embeddings = tf.get_default_graph().get_tensor_by_name("embeddings:0")
I got neither warnings nor errors info,but the result is all features of embeddings is 0.Maybe 'tf.global[local]_variables_initializer()' has cleared the loaded weights ?
After that I **used the  frozen graph which was produced by pre-trained model to launch forward,like**:
 with tf.Graph().as_default():
        graph_def_ = graph_pb2.GraphDef()
        print('Model directory: %s' % os.path.expanduser(args.modelpb_file))
        with open(os.path.expanduser(args.modelpb_file),'rb') as f:
             graph_def_.ParseFromString(f.read())
             _ = importer.import_graph_def(graph_def_,name="")
        with tf.Session() as sess:         
            images_placeholder = tf.get_default_graph().get_tensor_by_name("image_batch:0")
            embeddings = tf.get_default_graph().get_tensor_by_name("embeddings:0")
I still got the "**FailedPreconditionError: Attempting to use uninitialized value...**" issues.
Really confusing,who can help ?

**Comment by drpngx** [comment]
Does your checkpoint contain values for all variables? Which is the variable that's is missing initialization?

**Comment by MaeThird** [comment]
Hi,@drpngx 
If I use 

> 

new_saver = tf.train.import_meta_graph("xxx.meta")
new_saver.restore(sess, "xxx.ckpt-yyy")

> 

 to run forward pass the only cannot uninitialized value is ".../moments/moments_1/mean/ExponentialMovingAverage" .This is "batch_norm" codes as 

> 
    with tf.variable_scope(name):
        phase_train = tf.convert_to_tensor(phase_train, dtype=tf.bool)
        n_out = int(x.get_shape()[3])
        beta = tf.Variable(tf.constant(0.0, shape=[n_out], dtype=x.dtype),
                           name=name+'/beta', trainable=True, dtype=x.dtype)
        gamma = tf.Variable(tf.constant(1.0, shape=[n_out], dtype=x.dtype),
                            name=name+'/gamma', trainable=True, dtype=x.dtype)      
        batch_mean, batch_var = tf.nn.moments(x, [0,1,2], name='moments')
        ema = tf.train.ExponentialMovingAverage(decay=0.9)
        def mean_var_with_update():
            ema_apply_op = ema.apply([batch_mean, batch_var])
            with tf.control_dependencies([ema_apply_op]):
                return tf.identity(batch_mean), tf.identity(batch_var)
        mean, var = control_flow_ops.cond(phase_train,
                                          mean_var_with_update,
                                          lambda: (ema.average(batch_mean), ema.average(batch_var)))
        normed = tf.nn.batch_normalization(x, mean, var, beta, gamma, 1e-3)
    return normed
> 
If I use 
> 


slim.arg_scope([slim.conv2d],
                        weights_initializer=tf.truncated_normal_initializer(stddev=0.1),
                        weights_regularizer=slim.l2_regularizer(weight_decay),
                        normalizer_fn=slim.batch_norm,
                        normalizer_params=batch_norm_params)" 


> 

to replace my code no issue occurred.
Thank you anyway.
