### ISSUE TITLE
Typo in seq2seq.attention_wrapper.py

### ISSUE THREAD

**Issue by Songweiping** [tensorflow/tensorflow#9312]
Hi,
 I think there is a small typo in contrib.seq2seq.attention_wrapper.py, would someone like to check it?
code url: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py#L471]
I guess it should be _probability_fn_ rather than _cell_input_fn_ to be checked.

Thanks.

**Comment by drpngx** [comment]
Yes, could you send a PR to fix this?

/CC: @ebrevdo

**Comment by ebrevdo** [comment]
yes please!

**Comment by Songweiping** [comment]
I have sent a PR, please let me know if any questions.

**Comment by drpngx** [comment]
Merged.
