### ISSUE TITLE
`Evaluable` docs: name, checkpoint_path, and hooks should be new bullets.

### ISSUE THREAD

**Issue by dmonopoly** [tensorflow/tensorflow#9313]
See https://www.tensorflow.org/api_docs/python/tf/contrib/learn/Evaluable - final params for evaluate() are not bullets, making reading the documentation less readable. I've seen this in other docs too (can comment if I come across more of them).

I wonder if the parser has some bug that causes it to not bullet-ify some params for functions.

**Comment by drpngx** [comment]
It's typically an error in the MD format, like missing spaces in front the bullet.

**Comment by dmonopoly** [comment]
Where are the instructions on how to generate the docs?

I could make this fix here and in multiple other places if I can just generate the docs to check that my changes fix things like this.

**Comment by dmonopoly** [comment]
Nm found it here via #1574  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/community/documentation.md

**Comment by yongtang** [comment]
I think the issue is the extra line in `metrics:` args description in python code. PR #10423
