### ISSUE TITLE
tf.get_collection documentation: argument description is confusing

### ISSUE THREAD

**Issue by dmonopoly** [tensorflow/tensorflow#9314]
From https://www.tensorflow.org/api_docs/python/tf/get_collection:

"Items without a name attribute are never returned if a scope is supplied and the choice or re.match means that a scope without special tokens filters by prefix."

What does this mean? Is there a typo here?

**Comment by drpngx** [comment]
I think that's "of" rather than "or". Let me check internally.

**Comment by drpngx** [comment]
@sguada @martinwicke who reviewed 120141411.

**Comment by martinwicke** [comment]
Yes, that should be an "of", and we should probably also insert a comma before "and the choice" to make the structure clearer.

**Comment by drpngx** [comment]
@dmonopoly would you care to send a PR?

**Comment by dmonopoly** [comment]
Sure thing

**Comment by drpngx** [comment]
Thanks! Make sure you put 'Fixes #9314` in the commit message & CC me on the PR.

**Comment by dmonopoly** [comment]
I'll get to this later this week. Looking around for other fixes as well. Feel free to assign to me.
