### ISSUE TITLE
MultiRNNcell expected state to tuple but its a tensor

### ISSUE THREAD

**Issue by prashantsingh905** [tensorflow/tensorflow#9316]
i have define my lstm_cell as 

`def lstm(state, input_data, num_steps, hidden_size, num_layers, name):`
   ` # Input: (B, T, N) `
     `with tf.variable_scope(name) as scope: `
        ` multi_lstm = MultiRNNCell([BasicLSTMCell(hidden_size)] * num_layers) `
         `outputs = [] `
         `for t in range(num_steps): `
             `output, state = multi_lstm(input_data[:, t, :], state) `
            ` output = batch_normalization(output, [0, 1], "batch") `
            ` outputs.append(output) `
            ` scope.reuse_variables() `
         `return outputs`

Now after defining my inputs for lstm_cell as
`lstm_input = tf.reshape(c13, [B, M, -1])`
`lstm_state = tf.reduce_mean(lstm_input, [1])`

 and passing my values to lstm() , i am getting the following error 
` Expected state to be a tuple of length 6, but received: Tensor("Mean:0", shape=(25, 1568), dtype=float32)`

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
