### ISSUE TITLE
Explain what tf.nn.softplus does to integers

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#9317]
[`tf.nn.softplus`](https://www.tensorflow.org/api_docs/python/tf/nn/softplus) computes `log(1 + exp(x))`.  Naively, I wouldn't expect this to work for integers, but it does.  On integers, it seems to degenerate to a poorly named version of `tf.relu`: it computes `max(0, x)`.

We probably can't eliminate the integer versions for backward compatibility reasons, but we should at least explain what they do.

**Comment by girving** [comment]
Hmm, there seems to be more of this in `core/ops/nn_ops.cc`.  E.g., `softsign` is the same.

I added it to the doc fixit spreadsheet.

**Comment by girving** [comment]
`tf.nn.softsign` on ints is rather less useful: it's the constant zero function.

@martinwicke: Maybe we should drop these?  Arguably they're just bugs.

**Comment by martinwicke** [comment]
I'm a little reluctant to remove the functionality since that will break graphs (and code) that worked before. But a warning (deprecation?) would be nice.
