### ISSUE TITLE
Not all image ops accept image tensors with batch dimension

### ISSUE THREAD

**Issue by zo7** [tensorflow/tensorflow#9318]
It appears that only some of the image ops (e.g. `tf.image.random_saturation()`) only accept single images (rank-3 tensors), while others allow batches of images (rank-4 tensors). Should this be made more consistent so that all image ops allow for higher-rank tensors? There doesn't seem to be much about this in the API documentation (some ops just say that the last dimension needs to be 3).

### System Information
- *Have I written custom code?*: Yes
- *OS Platform and Distribution*: Ubuntu 16
- *TensorFlow installed from (source or binary)?*: binary
- *TensorFlow version*: 1.0.1
- *Bazel version (if compiling from source)*: N/A
- *CUDA/cuDNN version*: N/A
- *GPU Model and Memory*: N/A
- *Exact command to reproduce*:
```python
import tensorflow as tf
images = tf.placeholder(tf.float32, shape=(None, None, None, 3), name='images')
# This is OK
x = tf.image.random_contrast(images, lower=0.5, upper=1.0)
# Throws an exception because `images` is rank-4
x = tf.image.random_saturation(images, lower=0.5, upper=1.0)
```

**Comment by drpngx** [comment]
That sounds like a good idea.

@tatatodd may have some comment.

**Comment by cancan101** [comment]
See also: https://github.com/tensorflow/tensorflow/issues/8926

**Comment by zo7** [comment]
Ah, thanks @cancan101 I must've missed that. I'll go ahead and close this since it seems to be a duplicate.
