### ISSUE TITLE
thread pool deadlocks on shutdown

### ISSUE THREAD

**Issue by dvyukov** [tensorflow/tensorflow#932]
ThreadPool dtor does not pop waiters from waiters_ list. As the result dead waiters are left on the list. If remaining tasks submit new tasks, thread pool deadlocks because some notifications are consumed by the leftover dead waiters instead of alive threads that should receive the notifications.

Here is a simple test that does classical parallel decomposition and reliably deadlocks:
```c
static void BM_ParallelDivide(int iters, const char* impl) {
  THREAD_POOL_IMPL_NAME = impl;
  for (int i = 0; i < iters; i++) {
    const int kTasks = 10;
    const int kLevels = 22;
    std::atomic<unsigned> count(kTasks * (1 << kLevels));
    mutex done_lock;
    condition_variable done;
    bool done_flag = false;
    std::function<void(int)> work;
    ThreadPool pool(Env::Default(), "test", kNumThreads);
    work = [&pool, &work, &count, &done_lock, &done, &done_flag](int level) {
      if (level-- > 0) {
        pool.Schedule([&work, level]() { work(level); });
        pool.Schedule([&work, level]() { work(level); });
        return;
      }
      delay();
    };
    for (int t = 0; t < kTasks; ++t) {
      pool.Schedule([&work]() {
        work(kLevels);
      });
    }
  }
}
```

**Comment by girving** [comment]
@zheng-xq: Do you have thoughts on this?  The non-blocking thread pool PR is problematic since it breaks Eigen's FIFO requirement, but the deadlock issue seems like something we should fix.

**Comment by dvyukov** [comment]
@zheng-xq @girving 

On Tue, Mar 8, 2016 at 8:08 PM, Zhifeng Chen wrote:
> The thread calling 'delete p' should have the sole ownership of p, where p is generally any c++ object. 
> So, it's not valid if one thread is calling a threadpool p while another thread calling p->Add().

That's true. But the thread pool waits for the existing tasks to finish in destructor. If you combine these two points, you conclude that tasks are not allowed to submit child tasks to the thread pool. Ever. That's just does not make sense. So you need to either (1) wait for _all_ tasks to finish, including subtasks of existing tasks, or (2) don't wait in thread pool destructor at all, stop threads as soon as possible, assert that the queue is empty now and exit.

I am working on a fix.

**Comment by girving** [comment]
@dvyukov, @rmlarsen: Did the recent thread pool changes resolve this?

**Comment by girving** [comment]
@rmlarsen: Assigning you since @dvyukov isn't part of the Github org.  Should we add him?

**Comment by dvyukov** [comment]
Yes, it's fixed. New thread pool waits for completion of all work.
