### ISSUE TITLE
Maximum points displaying on embedding

### ISSUE THREAD

**Issue by Jeffery4000** [tensorflow/tensorflow#9321]
Hi, 
I got a embedding file with 1.5 million points, its that possible to show all 1.5 million points instead of the first 100 thousand points only? I have been asking around Stackoverflow but no one can answer that question. Trying to check all those documentation but dosent help at all.

**Comment by drpngx** [comment]
Stackoverflow is the appropriate place to ask. This channel is reserved for bugs and feature requests.

**Comment by Jeffery4000** [comment]
@drpngx Hi, i has been asking around stackoverflow but no one can answer that question. Its either a 'yes' or 'no' question.

**Comment by drpngx** [comment]
I would suggest looking at the code.
