### ISSUE TITLE
Cannot find python and other modules

### ISSUE THREAD

**Issue by vikasgupta1812** [tensorflow/tensorflow#9325]
When I am running the code with `tf.python.framework.tensor_shape.scalar()` , I get the error message `AttributeError: 'module' object has no attribute 'python'`

### Source Code / Logs

Given below are minimum reproducible examples. 

```
(tf1_0rc1_cpu) $python -c'import tensorflow as tf; tf.python'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'python'
```

This works
```
(tf1_0rc1_cpu) $python -c'import tensorflow as tf; tf.contrib'
```

Others donot work
```
(tf1_0rc1_cpu) $python -c'import tensorflow as tf; tf.core'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'core'
```

```
(tf1_0rc1_cpu) $python -c'import tensorflow as tf; tf.examples'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'examples'
```

```
(tf1_0rc1_cpu) $python -c'import tensorflow as tf; tf.include'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'include'
```

```
(tf1_0rc1_cpu) $python -c'import tensorflow as tf; tf.tools'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'tools'
```

But when I also tried importing python module. 

```
(tf1_0rc1_cpu) $python -c'import tensorflow.python'
```

### System Information
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*: No
- *OS Platform and Distribution (i.e. Linux Ubuntu 16.0)*: MacOS Sierra 
- *TensorFlow installed from (source or binary)?*:Binary 
- *TensorFlow version* (use command below): ('v1.0.0-65-g4763edf-dirty', '1.0.1')
- *Bazel version (if compiling from source)*: n/a
- *CUDA/cuDNN version*: release 8.0, V8.0.61
- *GPU Model and Memory*:NVIDIA GeForce GT 650M 1024 MB
- *Exact command to reproduce*:python -c "import tensorflow as tf; tf.python"

**Comment by vikasgupta1812** [comment]
I was able to use `tf.python.framework.tensor_shape.scalar()` shape by following code

```python
from tensorflow.python.framework.tensor_shape import scalar
scalar()
```

**Comment by drpngx** [comment]
There is no `tf.python`, by design. Neither is there tools, include, etc. You can use `dir(tf)` to find out the contents of the package that you can use.

`tensor_shape` is currently only for internal use. We are recommending for people to use the C++ API.
