### ISSUE TITLE
Update op_def_registry.py

### ISSUE THREAD

**Issue by Currie32** [tensorflow/tensorflow#9326]
I am hoping that you can make an update to tensorflow/python/framework/op_def_registry.py (https://github.com/tensorflow/tensorflow/pull/9235/commits/133debe1e805e8d2a78600a9d5014900d429479c). 

I discovered this issue when I was building a seq2seq model with attention. Specifically, I believe the issue stems from tf.contrib.seq2seq.prepare_attention() (https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/prepare_attention) because the error message is: "ValueError: No op named attn_add_fun_f32f32f32 in defined operations" when I use "bahdanau" as my attention_option. When I used "luong" for the attention_option, the error is: "ValueError: No op named attn_mul_fun_f32f32 in defined operations".

This issue was also brought up here: http://stackoverflow.com/questions/42494695/tf-train-import-meta-graphmodel-meta-cannot-handle-seq2seq-models-with-atten. However, with my issue, I was using python3. 

Thanks for your help!

**Comment by drpngx** [comment]
Your problem is that the file is an auto-generated file and you failed to generate it during the build. Please try either install from binary or follow the "Install From Source" instructions carefully.

**Comment by gunan** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
