### ISSUE TITLE
Error in `python`: free(): invalid pointer

### ISSUE THREAD

**Issue by DjangoPeng** [tensorflow/tensorflow#9328]
TensorFlow Version: 1.0 and 1.0.1 (whl package)
Kubernetes Version: 1.5.1
Docker Version: 1.12.5
Container OS: ubuntu 14.04

I run tensorflow applications, say mnist_replica.py, in the kubernetes cluster and this error occured everytime when finishing the whole train step.

I attached the log of mnist_replica.py as below:
```
1492616963.574406: Worker 0: training step 5045 done (global step: 9999)
1492616963.583257: Worker 0: training step 5046 done (global step: 10001)
Training ends @ 1492616963.583282
Training elapsed time: 54.435048 s
After 10000 training step(s), validation cross entropy = 1170.07
*** Error in `/usr/bin/python': free(): invalid pointer: 0x0000000001e16c50 ***
```
And everything goes well when I run the mnist_replica.py in a physical machine with RHEL 7.0. I Guess the problem is that your google's environment is different with me. So the whl package that you compiled can not run well in the ubuntu 14.04 container, especially when it comes to the C program calling Python program

**Comment by drpngx** [comment]
It could be wrong even on your own machine, just going undetected. Could you run a version with more instrumentation? Maybe a debug version with asan? Or maybe valgrind on the last step?

/CC @yifeif

**Comment by DjangoPeng** [comment]
It's not only an unique case, but also happened in other ubuntu 14.04 in physical machine with TensorFlow v1.0, but it has different error log`Error in `python': double free or corruption (!prev): 0x00000000016b43c0`.

**Comment by drpngx** [comment]
Can you reproduce with a build from source on a recent version? If so, can you try asan?

**Comment by DjangoPeng** [comment]
@drpngx I pulled the TensorFlow r1.0 branch and built the whl package from source.  Getting the same error and then I would like to try official docker image.

**Comment by DjangoPeng** [comment]
@drpngx I pulled the official docker image tagged as `tensorflow/tensorflow:1.0.1`, and it works well. I do not yet know what's wrong with my self-built image. I attached my [Dockerfile](https://gist.github.com/DjangoPeng/ce00add09714f247fe211c1dcff708aa).

**Comment by girving** [comment]
@DjangoPeng Let us know if you figure out additional information.  My only wild guess is something to do with incompatible versions of Python.

**Comment by DjangoPeng** [comment]
@girving Thanks for your attention. The problem is the incompatible of `malloc`, I think the library of `malloc` in Google is different with us. If I install the `libtcmalloc-minimal4` in Dockerfile everything goes well . I've updated my [Dockerfile](https://gist.github.com/DjangoPeng/ce00add09714f247fe211c1dcff708aa#file-dockerfile-L29) and commented the line 29.

**Comment by girving** [comment]
@caisq Can we incorporate this fix?

**Comment by caisq** [comment]
@girving I noticed @DjangoPeng is using ubuntu:14.04, but the official TF Docker images are on ubuntu:16.04 now. So there is no need to incorporate any changes to TF code. Am I understanding it correctly?

**Comment by caisq** [comment]
If we are talking about updating the old release branch (r1.0), that SGTM.

**Comment by yaroslavvb** [comment]
PS, we are observing same error message with PyTorch on Ubuntu 14.04, and LD_PRELOAD=tcmalloc fixes it there too

**Comment by DjangoPeng** [comment]
@girving  @caisq I'm not sure if tensorflow/tensorflow:1.0 is based on Ubuntu:14.04. If so, I think it's necessary to fix it, cause 1.0 is the first stable released version.
@yaroslavvb Do you mean add the environment `LD_PRELOAD` in Dockerfile?

**Comment by DjangoPeng** [comment]
@caisq What can I do for fixing the issue? I'm willing to contribute it to TensorFlow community.

**Comment by caisq** [comment]
@DjangoPeng Thanks. Can you please send a PR to these files in branch r1.0:
https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/tools/docker/Dockerfile
https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/tools/docker/Dockerfile.devel
https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/tools/docker/Dockerfile.devel-gpu
https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/tools/docker/Dockerfile.gpu?

**Comment by DjangoPeng** [comment]
@caisq Sure thing, I'm on it.

**Comment by DjangoPeng** [comment]
Merged pull request, so I close the issue. @caisq @girving

**Comment by Fangyh09** [comment]
I encountered this problem because I used torch and tensorflow at same time.
