### ISSUE TITLE
thread pool does not execute all remaining tasks on shutdown

### ISSUE THREAD

**Issue by dvyukov** [tensorflow/tensorflow#933]
ThreadPool claims to finish all remaining work on shutdown. This is not the case. If remaining tasks submit new tasks, the new tasks do not get executed. This happens because the sentinel tasks are fetched before the newly submitted real tasks.

ThreadPool must either execute all pending work, or execute nothing on shutdown. It does not make sense to execute half of work.

Here is a repro:
```c
static void BM_ParallelDivide(int iters, const char* impl) {
  THREAD_POOL_IMPL_NAME = impl;
  for (int i = 0; i < iters; i++) {
    const int kTasks = 10;
    const int kLevels = 22;
    std::atomic<unsigned> count(kTasks * (1 << kLevels));
    mutex done_lock;
    condition_variable done;
    bool done_flag = false;
    std::function<void(int)> work;
    ThreadPool pool(Env::Default(), "test", kNumThreads);
    work = [&pool, &work, &count, &done_lock, &done, &done_flag](int level) {
      if (level-- > 0) {
        pool.Schedule([&work, level]() { work(level); });
        pool.Schedule([&work, level]() { work(level); });
        return;
      }
      delay();
    };
    for (int t = 0; t < kTasks; ++t) {
      pool.Schedule([&work]() {
        work(kLevels);
      });
    }
  }
}
```

**Comment by jeremybarnes** [comment]
Personally, I find this behaviour of performing potentially unlimited work in the destructor to be strange.  I think it would make more sense for the caller to explicitly ask for all work to be performed, and for the destructor to finish as fast as possible, even if it meant leaving work in the queue.

**Comment by dvyukov** [comment]
@jeremybarnes I fine either way as long as it is documented. It is just the current implementation that does not make sense.

**Comment by jeremybarnes** [comment]
Note that there are some places in the existing codebase (and tests) that assume this behavior.  I had to implement it in my PR in order to avoid deadlocks.

**Comment by girving** [comment]
@dvyukov, @rmlarsen: Is this resolved?

**Comment by dvyukov** [comment]
Yes, it's fixed. New thread pool waits for completion of all work.
