### ISSUE TITLE
Getting error: Number of tensor does not match the number of lines in metadata

### ISSUE THREAD

**Issue by Jeffery4000** [tensorflow/tensorflow#9330]
Even though my metadata.tsv have 100k line but it still show up this message. I have try different amount of tensor and its work fine (eg. 40k, 50k). The problem occurred when the tensor values are roughly more than 70k. 
Beside, i try other data set and its work fine for 100k tensor values. Just doubt what makes the problem above happend.
![default](https://cloud.githubusercontent.com/assets/27762422/25224049/cfe357ec-25ef-11e7-96f0-6a7eb4242375.PNG)
![default](https://cloud.githubusercontent.com/assets/27762422/25224162/25ce4dd8-25f0-11e7-88d3-80d6b6849363.PNG)

**Comment by drpngx** [comment]
It is probably and end of line missing.

This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by Marko-Stamenovic-Bose** [comment]
I'm also seeing this issue with the latest version of tensorflow (1.1.0). i am not seeing it on version 0.12.1.

I verified that both embeddings and metadata are same length before exporting and that they do not match up in the tensorboard visualization.

**Comment by markostam** [comment]
I'm also getting this error in TF version 1.1.0. Everything works fine on 0.12.1 using the exact same code.

I've verified that my embedding tensor and metadata file have the same length.

**Comment by markostam** [comment]
I also verified that if i truncate my embeddings to start from the second index, the names and embeddings will match up correctly in the tensorboard embedding visualization.

**Comment by markostam** [comment]
eg. this hack makes it work for me with the current release (1.1.0):

```
embeddings = [i[1] for i in name_and_embedding][1:]
names = [i[0] for i in name_and_embedding]
```

**Comment by Jeffery4000** [comment]
Hi @markostam ,
I found that it skip my blank line on metadata file, so basically what i did is to check whether the query is blank or not before writing into the metadata file. Anyway, thanks for the hack.

**Comment by lightningrodsalesman** [comment]
> Even though my metadata.tsv have 100k line but it still show up this message. I have try different amount of tensor and its work fine (eg. 40k, 50k). The problem occurred when the tensor values are roughly more than 70k.
> Beside, i try other data set and its work fine for 100k tensor values. Just doubt what makes the problem above happend.
> ![default](https://cloud.githubusercontent.com/assets/27762422/25224049/cfe357ec-25ef-11e7-96f0-6a7eb4242375.PNG)
> ![default](https://cloud.githubusercontent.com/assets/27762422/25224162/25ce4dd8-25f0-11e7-88d3-80d6b6849363.PNG)

I've had a similar problem when using the online embedding projector (https://projector.tensorflow.org/). 

I am uploading a vector file of 16-dimensional embeddings and a metadata file of labels, with one label per embedding. When more than 60289 rows are uploaded (say 60290), I receive the error 

`Number of tensors (60290) do not match the number of lines in metadata (60289).`

This does not seem to be a problem of incorrectly formatted files, since the upload works fine when fewer rows are uploaded. Maybe re-open the issue, since this seems to be a bug?

**Comment by pujaarajan** [comment]
I am having the same problem as above.

**Comment by vatsan** [comment]
This error hasn't really gone away, why was this issue closed?
I have an embedding layer of size 100 and my metadata file also has 100 rows, but I get an error that says "Number of tensors (99) do not match the number of lines in the metadata (100)".
It does not appear to be counting the lines properly, I have not supplied any header row either.

I am on Tensorflow 2.2.0 and Tensorboard 2.2.1

**Comment by vatsan** [comment]
This might sound ridiculous but it appears like tensorboard did not like me using my Google Drive folder for logs (`/Users/me/Google Drive/logs`). When I switched it to something without a space (ex: `/tmp/me/logs`) it works alright. Ugh!

**Comment by fmgs31** [comment]
The problem is still present.  It's a problem in tensorboard.
Tensorboard is caching the first tensor it gets. It's not updating when refreshing the page, even after deleting the whole log folder. The **workaround** is to close the tensorboard server and run it again.

**Comment by fmgs31** [comment]
I created an issue [here](https://github.com/tensorflow/tensorboard/issues/4439)

**Comment by viniciusarruda** [comment]
I faced this issue while plotting the embeddings with projector's tensorboard. The metadata I was using had a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) character. The solution was to handle it.
