### ISSUE TITLE
When I used keras to train a very large model, it was already done, but I found that the outputdim of the all-join layer was wrong, and what should I do? The The Without having to re-train the model #

### ISSUE THREAD

**Issue by guoying1030** [tensorflow/tensorflow#9331]
When I used keras to train a very large model, it was already done, but I found that the outputdim of the all-join layer was wrong, and what should I do? The The Without having to re-train the model #

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
