### ISSUE TITLE
Cannot get Conv1D layer to work

### ISSUE THREAD

**Issue by ddegraw** [tensorflow/tensorflow#9332]
For the life of me, I cannot get Conv1D layer to work.  I am on windoze7 with theano backend and using MKL multithreading.  No issues with other layer types whatsoever.

The error I get is: convx1 = Conv1D(filters=num_filters, kernel_size=sz, padding="valid", activation="relu", strides=1)(embedded_sequences_1)
TypeError: __init__() takes at least 3 arguments (2 given)

Model code as below:
embedding_layer = Embedding(nb_words,
                            EMBEDDING_DIM,
                            weights=[embedding_matrix],
                            input_length=MAX_SEQUENCE_LENGTH,
                            trainable=False)
sequence_1_input = Input(shape=(MAX_SEQUENCE_LENGTH,EMBEDDING_DIM), dtype='int32')
embedded_sequences_1 = embedding_layer(sequence_1_input)

sequence_2_input = Input(shape=(MAX_SEQUENCE_LENGTH,EMBEDDING_DIM), dtype='int32')
embedded_sequences_2 = embedding_layer(sequence_2_input)

convx =[]
for sz in filter_sizes:
    convx1 = Conv1D(filters=num_filters, kernel_size=sz, padding="valid", activation="relu", strides=1)(embedded_sequences_1)
    convx1 = GlobalMaxPooling1D(pool_size=2)(convx1)
    convx1 = Flatten()(convx1)
    convx.append(convx1)   
x1 = merge(convx, mode='concat')

convy =[]
for sz in filter_sizes:
    convy1 = Conv1D(filters=num_filters,kernel_size=sz,padding="valid",activation="relu",strides=1)(embedded_sequences_2)
    convy1 = GlobalMaxPooling1D(pool_size=2)(convy1)
    convy1 = Flatten()(convy1)
    convy.append(convy1)   
y1 = merge(convy, mode='concat')                   

merged = merge([x1,y1], mode='concat')
merged = Dropout(0.5)(merged)
merged = BatchNormalization()(merged)
merged = Dense(num_dense, activation='relu')(merged)
merged = Dropout(0.15)(merged)
merged = BatchNormalization()(merged)
preds = Dense(1, activation='sigmoid')(merged)
model = Model(input=[sequence_1_input,sequence_2_input], output=preds)
model.compile(loss='binary_crossentropy', optimizer='nadam', metrics=['acc'])

**Comment by drpngx** [comment]
Sorry, this is the tensorflow site, which is not theano. Please find the appropriate channels on their web site. I would suggest stackoverflow.
