### ISSUE TITLE
Custom operator can't define list(type)

### ISSUE THREAD

**Issue by fesun** [tensorflow/tensorflow#9334]
hi, I am writing my custom operator, need to pass a list of int tensor into it, according to https://www.tensorflow.org/extend/adding_an_op and https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/io_ops.cc#L59, I wrote the following code:
REGISTER_OP("MyOwnOp").Input("my_variables: dtypes").Attr("dtypes: list(int)")....
and build the code into one shared library, however error occurred when loading it through tf.load_op_library.
Here is the error message:

> tensorflow.python.framework.errors_impl.InvalidArgumentError: Reference to attr 'dtypes' with type list(int) that isn't type or list(type) from Input("my_variables: dtypes") for Op MyOwnOp

environment:
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)
Python 2.7.6
tensorflow '1.0.1'

**Comment by drpngx** [comment]
We don't support lists as inputs. You can use sparse tensors.

**Comment by fesun** [comment]
@drpngx I am confused, you mean custom operator doesn't support lists as inputs? Kernel SaveV2 operator uses lists tensor as input:

> REGISTER_OP("SaveV2")
    .Input("prefix: string")
    .Input("tensor_names: string")
    .Input("shape_and_slices: string")
    .Input("tensors: dtypes")
    .Attr("dtypes: list(type)")

If custom operator doesn't support this, could you guys change the document of https://www.tensorflow.org/extend/adding_an_op?

**Comment by drpngx** [comment]
Did you mean a list of valid types or a list type? If it's the list of types, you have to enumerate them. If it's a list, it won't work, you have to use sparse tensors for now.

**Comment by fesun** [comment]
@drpngx  I mean a list of types, just like SaveV2.

**Comment by fesun** [comment]
`
#include "tensorflow/core/framework/op_kernel.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/core/framework/tensor_shape.h"
#include "tensorflow/core/framework/types.h"
#include "tensorflow/core/lib/core/errors.h"
#include "tensorflow/core/platform/cpu_info.h"
#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/shape_inference.h"
#include "tensorflow/core/framework/common_shape_fns.h"
#include "tensorflow/core/platform/env.h"
#include "tensorflow/core/platform/file_system.h"

namespace tensorflow {
using shape_inference::DimensionHandle;
using shape_inference::InferenceContext;
using shape_inference::ShapeHandle;

REGISTER_OP("MyConcat")
  .Input("tensors: dtypes")
  .Attr("dtypes: list(int)")
  .SetShapeFn([] (InferenceContext* c) {
      return Status::OK();
  })
  .Doc(R"doc(
concat a list of tensors
)doc");

class MyConcatOp : public OpKernel {
public:
  explicit MyConcatOp(OpKernelConstruction* context) : OpKernel(context) {}

  void Compute(OpKernelContext* context) override {
  }
};

REGISTER_KERNEL_BUILDER(Name("MyConcat").Device(DEVICE_CPU), MyConcatOp);
}

`
This code refereed to the two links i pasted and  complied successfully, but failed to load. I think there is something wrong.

> >>> m = tf.load_op_library("./test_list.so")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Reference to attr 'dtypes' with type list(int) that isn't type or list(type) from Input("tensors: dtypes") for Op MyConcat

**Comment by fesun** [comment]
@drpngx changing Attr("dtypes: list(int)") to Attr("dtypes: list(type)") works, but I don't know why.
The "Adding new op" page said that:

`list(<type>): A list of <type>, where <type> is one of the above types. Note that list(list(<type>)) is invalid.`
list(int) should work, if not, the official document is wrong.

**Comment by drpngx** [comment]
The list of types is just used for polymorphism. If you just want to pass a scalar, or tensor, of a single type, you can just use the type, like `tensors: int32`.

**Comment by soiferj** [comment]
@drpngx can you please expand on this a little more? The documentation still says this should be valid:

`REGISTER_OP("MyOp")
    .Attr("myAttr: list(tensor)")
    .Input("in: int32")
    .Output("out: int32");`

When I call `context->GetAttr` on "myAttr", what type am I supposed to pass in for the second argument to get the list of TensorProtos? I have tried a `std::vector<TensorProto>` but that doesn't seem to work.

**Comment by drpngx** [comment]
There are a number of examples in the code. You as `.Attr("dilations: list(int32)` in the op registration and the kernel code uses `GetAttr(...)` into an `std::vector<int32>`.

**Comment by soiferj** [comment]
This seems to work in std::vector<int> but not std::vector<TensorProto>. Is that expected?

**Comment by drpngx** [comment]
Yes, the `TensorProto>` is used for serialized protos. The `GetAttr` is to just get some tensors of a given type. You can, however, pass the dtype to know which type you want, if that's useful. You can also pass dimensions separately. At this point, though, it might be better to use an input rather than an argument.
