### ISSUE TITLE
tflearn Incorrect Comment

### ISSUE THREAD

**Issue by vprusso** [tensorflow/tensorflow#9336]
In the tflearn quick start guide here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/get_started/tflearn.md

Below the section "Describe the training input pipeline {#train-input}"

The first snippet:

```python
# Define the test inputs
def get_train_inputs():
  x = tf.constant(training_set.data)
  y = tf.constant(training_set.target)

  return x, y
```

Should be

```python
# Define the training inputs
def get_train_inputs():
  x = tf.constant(training_set.data)
  y = tf.constant(training_set.target)

  return x, y
```
where 

```python
# Define the test inputs -> # Define the training inputs
```
In the overall listing at the top of this file, it appears to have the correct comment. It's just here in this section where the comment is incorrect.

**Comment by drpngx** [comment]
Thanks! Please send a PR to correct this.
