### ISSUE TITLE
ideas - feature request

### ISSUE THREAD

**Issue by tiagmoraismorgado** [tensorflow/tensorflow#9338]
**idea1**

feeding wavenet implementation in tensorflow simulatenous with the following things to do advanced music gestural recognition:

- elastic fusion dense slam
- audio data + audio advanced gestural recognition spectral classifiers

**plus:**
doing training in real time

**idea2**

implementing the following artificial intelligence model in tensorflow:

- deep convolutional recursive swarm of hybrid bdi and artificial neural networks

**Comment by drpngx** [comment]
These are fantastic ideas! For now, I would recommend implementing on your own github repo.
