### ISSUE TITLE
Error: tensorflow/core/framework/resource_handle.pb.h file not found

### ISSUE THREAD

**Issue by VRSManan** [tensorflow/tensorflow#9354]
I have followed following instructions from this link: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile

- Before you start (All Platforms)
- Building on iOS
- Copy files from inception to data folders in benchmark, simple and camera project.
- Building by hand. (error in terminal: failed with exit code 1) in both compile_ios_protobuf and run make file. 

- download_dependencies.sh worked successfully.

If I open project from Simple or camera folder, I received the error:

tensorflow/core/framework/resource_handle.pb.h file not found.

This Post: https://github.com/tensorflow/tensorflow/issues/5095 
indicates that the problem is related to macOS Sierra. after that I installed the update from AppStore.

After that I updated macOS update which updated command line tools and now I receive following errors by running all things from scratch. (Delete old project, unzip new project and follow all instructions).

![error-list](https://cloud.githubusercontent.com/assets/27809940/25264970/f8eb8720-2687-11e7-90ee-f677e59d79df.png)

**Comment by drpngx** [comment]
The `resource_handle.pb.h` is generated by the protobuf compiler, `protoc`.

It's either in
`$(MAKEFILE_DIR)/gen/protobuf-host/bin/protoc`
or somewhere on your path.

It should be generated [here](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/Makefile#L544).

Please check if they're there, if not why aren't they generated, and if they are there, whether there is a problem in the include path.

/CC @satok16

**Comment by satok16** [comment]
Right, just check the file location after building code.
$ find . -name "*resource_handle*.pb.h"

**Comment by VRSManan** [comment]
Thank you responders. But the problem is solved another way.
The issue is resolved. I was failed to build the project by following instructions from "building by hand" in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile.

Then I tried the installation from "building all at once". And somehow it worked. The build is successful and I can run the program.

**Comment by satok16** [comment]
Cool!  Feel free to create a new ticket if you meet further problems.
