### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by iramishtiaq** [tensorflow/tensorflow#9355]
i am getting these warning while running neuroner

`epoch_elapsed_training_time: 331.644915 seconds
assess_model on dataset_type: train
C:\Users\erame\AppData\Local\Programs\Python\Python35\lib\site-packages\matplotlib\artist.py:233: MatplotlibDeprecationWarning: get_axes has been deprecated in mpl 1.5, please use the
axes property.  A removal date has not been set.
  stacklevel=1)
C:\Users\erame\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\metrics\classification.py:1113: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\erame\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\metrics\classification.py:1115: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
assess_model on dataset_type: valid
assess_model on dataset_type: test
shell_command: perl .\conlleval < ..\output\en_2017-04-21_07-36-25-322798\000_014986_train.txt > ..\output\en_2017-04-21_07-36-25-322798\000_014986_train.txt_conll_evaluation.txt
'perl' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "main.py", line 442, in <module>
    main()
  File "main.py", line 383, in main
    conll_parsed_output = utils_nlp.get_parsed_conll_output(conll_output_filepath)
  File "C:\Users\erame\AppData\Local\Programs\Python\Python35\NeuroNER-master\src\utils_nlp.py", line 42, in get_parsed_conll_output
    line = conll_output[1].split()
IndexError: list index out of range`

**Comment by mrry** [comment]
None of the packages mentioned in the error message appear to be part of TensorFlow. It would probably be more appropriate to raise this issue on [the NeuroNER repository](https://github.com/Franck-Dernoncourt/NeuroNER).
