### ISSUE TITLE
decode_image return tensor without shape in python

### ISSUE THREAD

**Issue by ZhangBowen** [tensorflow/tensorflow#9356]
### System Information
- *OS Platform and Distribution (i.e. Linux Ubuntu 16.0)*: CentOS Linux release 7.0.1406 (Core)
- *TensorFlow installed from (source or binary)?*: python3 pip
- *TensorFlow version* : v1.0.0-65-g4763edf-dirty 1.0.1
- *Python version* : Python 3.5.2 :: Anaconda custom (64-bit)

### Describe the problem clearly

When I decode a jpeg file to a tensor with decode_jpeg, the code ran normally.
but if I use decode_image instead of decode_jpeg for more compatibilities, It raised a ValueError as follow.
Is It a bug?
Thanks

### Source Code / Logs
```python
def preprocess_image(image_path):
    file_content = tf.read_file(image_path)
    
    #image = tf.image.decode_jpeg(file_content)
    image = tf.image.decode_image(file_content)
    image = tf.image.per_image_standardization(image)
    image = tf.image.resize_images(image, [480, 640])
```
output : 
```
Traceback (most recent call last):
  File "/data/home/zhangbowen/is_vehicle/classify.py", line 29, in <module>
    main()
  File "/data/home/zhangbowen/is_vehicle/classify.py", line 26, in main
    image = preprocess_image(image_file)
  File "/data/home/zhangbowen/is_vehicle/classify.py", line 15, in preprocess_image
    image = tf.image.resize_images(image, [480, 640])
  File "/data/home/zhangbowen/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/image_ops_impl.py", line 643, in resize_images
    raise ValueError('\'images\' contains no shape.')
ValueError: 'images' contains no shape.
```

**Comment by drpngx** [comment]
The `decode_image` is a cascade of `tf.cond`. 
`resize_images` needs to pull the shape object. However, we don't know which one it's going to be upfront.

@cwhipkey any comment here?

**Comment by cwhipkey** [comment]
I think the issue is that in the decode_image cond, one branch leads to decode_gif.  decode_gif returns a 4-d tensor:  [num_frames, height, width, channels],  which is not the same as the 3-d tensor returned by decode_png and decode_jpeg.

One possible fix would be to make decode_gif have an attribute controlling whether to handle animated gifs ,and use that in decode_image?  (possibly also with an option?  It's not clear to me someone would want to use decode_image with a mix of animated and non-animated images - so maybe just changing it would be fine?).

+raingo and wicke

**Comment by cwhipkey** [comment]
@raingo @martinwicke

**Comment by martinwicke** [comment]
We could definitely add "frame=None" which is without effect for png and jpg, but for gif will return all frames if None, of the given frame number if not None and the gif is animated. This would work for other animated formats if those become available. 

If frame != None we can set the rank to [None, None, None], maybe even [None, None, 3] -- not sure that'll help.

**Comment by raingo** [comment]
@martinwicke I can send PR to add the `frame=None` to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/image_ops_impl.py#L1338.

```
      with ops.control_dependencies([assert_decode, assert_channels]):
        res = gen_image_ops.decode_gif(contents)
        if frame is not None:
           res = res[frame]
        return res
``` 

It makes the least changes to the code, and add some flexibility.

Not sure if that is the best way to do it.

**Comment by girving** [comment]
I think the right way to fix this is to make the image resizing machinery not need static shape.  I'll take a look at how difficult that is.

**Comment by cwhipkey** [comment]
Having decode_image sometimes return 4-d and sometimes return 3-d does not seem useful though - should it always just return frame 0 of a gif?  (this was a change in behavior of decode_image when animated gif support was added)

**Comment by girving** [comment]
@cwhipkey It was a backwards incompatible change?

**Comment by cwhipkey** [comment]
No, I don't think so.  DecodeGif always returned 4D tensor.  decode_image in python was added after that, and always returned a 4D for GIF and 3D for png or jpg.  So nm on what I wrote earlier about having it always return frame 0.

**Comment by drpngx** [comment]
CC: @girving

**Comment by girving** [comment]
I'm going to restrict my current change to unify `decode_jpeg` and `decode_png`: both ops will handle both formats.

**Comment by girving** [comment]
`decode_png` and `decode_jpeg` now decode all formats.

**Comment by ZhangBowen** [comment]
thanks

**Comment by lizhengwei1992** [comment]
> I'm going to restrict my current change to unify `decode_jpeg` and `decode_png`: both ops will handle both formats.

how to judge the format of the image ?

**Comment by azizullah2017** [comment]
I found the solution
```
tf.enable_eager_execution()
```
write this to the top of your add.

or
```
img_tensor = tf.image.decode_jpeg(img_raw,channels=3)
img_final = tf.image.resize_images(img_tensor, [192, 192])
img_final = img_final/255.0
print(img_final.shape)
```

**Comment by reubencmoyo** [comment]
> I found the solution
> 
> ```
> tf.enable_eager_execution()
> ```
> 
> add this to the top of your code.
> 
> or
> 
> ```
> img_tensor = tf.image.decode_jpeg(img_raw,channels=3)
> img_final = tf.image.resize_images(img_tensor, [192, 192])
> img_final = img_final/255.0
> print(img_final.shape)
> ```
This worked for me. Thanks

tf.enable_eager_execution()
