### ISSUE TITLE
What is the process for converting my data set to the MINIST data set?

### ISSUE THREAD

**Issue by connect2robiul** [tensorflow/tensorflow#9358]
I have run “[Deep MNIST for Experts  |  TensorFlow](https://www.tensorflow.org/versions/r0.11/tutorials/mnist/beginners/)” this file. I have X_train ; Y_train ; X_text ;Y_text ; Now I want to convert those 4 files into one “mist” variable like link which is MNIST format .

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
