### ISSUE TITLE
Check in tensorboard_bower_dependency_sync.py file

### ISSUE THREAD

**Issue by yxiong** [tensorflow/tensorflow#9366]
Hi TF Developers,

Could you kindly check in the `tensorboard_bower_dependency_sync.py` file to the repo? We need to customize the build process and having that file would be really helpful. Thanks a lot in advance!

Ying

**Comment by dandelionmane** [comment]
I don't think we still use the tensorboard_bower_dependency_sync to manage our dependencies, since we aren't updating bower. Pinging @jart for comment.

**Comment by jart** [comment]
That script is built in a way that's very specific to how Google's internal source code repository works, so it would not be something we could open source.

Would it be possible to tune the build by hand?

I also must warn you that the TensorBoard build process is very much in a state of flux right now. We're in the process of reworking the whole thing. So caution is advised.
