### ISSUE TITLE
Sub-pixel shuffling tensor operation

### ISSUE THREAD

**Issue by jhetherly** [tensorflow/tensorflow#9369]
Is there interest in integrating a [subpixel shuffling](http://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Shi_Real-Time_Single_Image_CVPR_2016_paper.pdf) operation as a core operation to Tensorflow? I've implemented such an operation on my [fork](https://github.com/jhetherly/tensorflow/tree/shuffle_op) and I think this could find widespread use. My implementation is a bit more generic than the one in the paper and is implemented using the C++ Tensorflow API. The operation I've defined is dimension agnostic and is found in the `contrib` portion of the source tree. Let me know if there is anything I need to do before making a pull request (i.e. better documentation, etc.).

**Comment by drpngx** [comment]
Feel free to send the PR and we can review it there. Please CC @martinwicke and make sure you put `Fixes #9369` in the commit message.

**Comment by MatthiasKohl** [comment]
I'm interested in this operation, but I don't know how to integrate it into my model with variable batch size since only one dimension can be ``None`` in this implementation. Can you help me out with it?
