### ISSUE TITLE
load python saved model in java

### ISSUE THREAD

**Issue by rjpg** [tensorflow/tensorflow#9371]
Hello,

I have created, trained and saved a tensorflow model using python 

`classifier = learn.DNNClassifier(hidden_units=[10, 20, 5], n_classes=5
                                 ,feature_columns=feature_columns
                                 ,model_dir= model_dir
                                 )
`

The model files are in :

`D:\java\workspace\APIJavaSampleCode\tfModels\dnn\MadelSave`

files :

checkpoint
events.out.tfevents.1492792287.BIRINHOS-PC
graph.pbtxt
model.ckpt-1.data-00000-of-00001
model.ckpt-1.index
model.ckpt-1.meta
model.ckpt-100.data-00000-of-00001
model.ckpt-100.index
model.ckpt-100.meta
 
in Java I have the line code :

`SavedModelBundle.load("D:/java/workspace/APIJavaSampleCode/tfModels/dnn/MadelSave");`

The result error is :

`Exception in thread "main" org.tensorflow.TensorFlowException: SavedModel not found in export directory: D:/java/workspace/APIJavaSampleCode/tfModels/dnn/MadelSave
	at org.tensorflow.SavedModelBundle.load(Native Method)
	at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:38)
	at tensorflow.HelloTF.main(HelloTF.java:32)
`

Can anyone help me loading a tf model in Java ? 

Thanks

**Comment by rjpg** [comment]
in java the tf version is 1.1.0-rc1

in python the tf version is (print(tf.__version__) ) :
1.0.1

**Comment by rjpg** [comment]
I have download the git example model file "saved_model.pb" and it work (load in my java program).

maybe it is because is a binary format ? 

I have to see how to set DNNClassifier() to save binary format.. and test..

**Comment by rjpg** [comment]
well this like mission impossible ... it seams like it is impossible to have a model loaded in java after trained in python using tensorflow  

I will turn to deeplearning4J ...

**Comment by loretoparisi** [comment]
@rjpg see https://github.com/loretoparisi/tensorflow-java, if it can help!

**Comment by rjpg** [comment]
hello,

thanks for the help. I found a solution and you can get the example code there :

http://stackoverflow.com/questions/43598953/loading-sklearn-model-in-java-model-created-with-dnnclassifier-in-python

**Comment by moroseking** [comment]
hello! I  meet the same problem!  I  use tf 1.4 and train a model with python 3.6,now I want to load the model in java ,but it can not work! throws the exception SavedModel not found in export directory: d:/pythonworkspace/alerm/model/predicted........
can you share you point about how to solution the problem? or  the model train in python can not load in java ?

**Comment by chenlongzhen** [comment]
same with @moroseking .  I use tf 1.4 and train a model , when I load in java throws the exception SavedModel not found.

**Comment by dratini6** [comment]
I am experiencing the same issue as @moroseking and @chenlongzhen. My model was also trained on TF 1.4.

**Comment by dmak** [comment]
Same problem with TF 1.5 for Windows when trying to load [this model](http://download.tensorflow.org/models/nmt/10122017/ende_gnmt_model_4_layer.zip). Code:
```
try (SavedModelBundle modelBundle = SavedModelBundle.load("D:/model/ende_gnmt_model_4_layer")) {
...
}
```
Exception:
```
org.tensorflow.TensorFlowException: SavedModel not found in export directory: D:/model/ende_gnmt_model_4_layer
	at org.tensorflow.SavedModelBundle.load(Native Method)
	at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:39)
```
Directory content:
```
translate.ckpt.data-00000-of-00001
translate.ckpt.index
translate.ckpt.meta
```

**Comment by timmolter** [comment]
@dmak What if you use: `"D:/model/ende_gnmt_model_4_layer.ckpt`?

**Comment by timmolter** [comment]
I had the same issue as @dmak. When looking at the `SavedModelBundle.load` Javadocs I noticed that "The model that is being loaded should be created using the <a href="https://www.tensorflow.org/api_docs/python/tf/saved_model">Saved Model API". I was at first using the `Saver` API. After switching to the `Saved Model` API, it worked.

**Comment by dmak** [comment]
@timmolter It would be fantastic if you could add links (e.g. to Python API) to your above post to tell the difference between `Saver API` and `aver Model API`. Thanks!

The argument for `SavedModelBundle.load()` should be a directory containing a `.pb` or `.pbtxt` file. Just for case I've tried `SavedModelBundle.load("D:/model/ende_gnmt_model_4_layer/translate.ckpt")` and it didn't work either. I had to convert `.ckpt` to `.pb` using the "model freezing" approach described in [How to convert .meta, .data and .index model files into one graph.pb file](https://stackoverflow.com/a/45868106/267197). After that the graph could be loaded like that:
```
import org.apache.commons.io.FileUtils;
import org.tensorflow.Graph;

try (Graph graph = new Graph()) {
    graph.importGraphDef(FileUtils.readFileToByteArray(new File("D:/translate.pb")));
}
```

**Comment by JsFlo** [comment]
I think what he means by `Saver Api` is: 
```
saver = tf.train.Saver()
...
saver.save(sess, CHECKPOINT_PATH) 
```
which saves out .chkpt, .pbtxt and variables files.

Using the `SaverModel Api`:
```
builders = saved_model_builder.SavedModelBuilder(export_path)
builders.add_meta_graph_and_variables(sess, ["myTag"], signature_def_map= {
        "predict": tf.saved_model.signature_def_utils.predict_signature_def(
            inputs= {"images": x_placeholder},
            outputs= {"scores": output})
        })
builders.save()
```
Which outputs:
```
.
├── saved_model.pb
└── variables
    ├── variables.data-00000-of-00001
    └── variables.index
```
which then can be loaded with:
```
tf.saved_model.loader.load(sess, ["myTag"], OUTPUT_DIR)
graph = tf.get_default_graph()
```
