### ISSUE TITLE
Mac Gpu Link not working?

### ISSUE THREAD

**Issue by Dakshster** [tensorflow/tensorflow#9381]
Hello,

I was trying to install Tensorflow for Mac GPU Python 3 one from github and I found that it is a broken URL Giving me an HTTP 404 Error.

The URL is - `https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-mac-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=gpu-mac/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow_gpu-1.1.0rc2-py3-none-any.whl`

Please Fix the Url.

Best,
Daksh

**Comment by drpngx** [comment]
Where did you copy that URL from?

**Comment by Dakshster** [comment]
From the readme of Tensorflow's Github.

**Comment by jucke** [comment]
I was wondering about this as well. 

Looks like the build for nightly Mac GPU Python 3 is currently broken, and for this reason link to the last successful build of nightly Mac GPU Python 3 version _1.1.0_ is broken. Same issue with nightly Mac GPU Python 2 1.1.0 link and build.
