### ISSUE TITLE
Issue with latest Cuda Install for Windows

### ISSUE THREAD

**Issue by BTolputt** [tensorflow/tensorflow#9383]
Took a little digging but the new DLL from Nvidia is called cudnn64_6.dll; the latest build of TensorFlow requires that to be cudnn64_5.dll. Crashes importing TensorFlow until this is renamed.

**Comment by drpngx** [comment]
Thanks for reporting. Maybe we should document this better.

/CC: @yifeif @wolffg

**Comment by WorksWellWithOthers** [comment]
Thank you for this. I've been having issues trying to get cudnn64_6.dll to work.

I'll try cudnn64_5.dll

**Comment by BTolputt** [comment]
If you know where to get it and the lib/h files that go with it - I would appreciate it.

**Comment by WorksWellWithOthers** [comment]
You have to sign up. 
https://developer.nvidia.com/cudnn

Download cuDNN v5.1 (Jan 20, 2017), for CUDA 8.0
