### ISSUE TITLE
Wrong implementation of ResNet in tensorflow/tensorflow/contrib/slim/python/slim/nets/ ?

### ISSUE THREAD

**Issue by n-triple-a** [tensorflow/tensorflow#9387]
I'm a researcher working on models related to ResNet_v1. As I was trying to use the code in this reporsitory: tensorflow/tensorflow/contrib/slim/python/slim/nets/
I realized that the ResNet_v1 model is different from Kaiming He's implementation. Specifically, in Kaiming's implementation, he applied stride 2 at the START of each block and the stride is applied to the 1*1 conv layer. For example, in Kaiming's original caffe prototxt (https://github.com/KaimingHe/deep-residual-networks/blob/master/prototxt/ResNet-101-deploy.prototxt), this is the first layer of 'conv3' (named in his ResNet paper) or block 2 (named by your implementation):

```
layer {
	bottom: "res2c"
	top: "res3a_branch1"
	name: "res3a_branch1"
	type: "Convolution"
	convolution_param {
		num_output: 512
		kernel_size: 1
		pad: 0
		stride: 2
		bias_term: false
	}
}
```

This layer is a 1*1 conv layer that mimics the 'skip-connection' because of dimension mismatch at the bottleneck between blocks. And so does 'res3a_branch2a', which is the start of the first residual module in 'conv3'.

Instead, in the tensorflow implementation, the stride 2 is applied to the END of each block(see function **resnet_v1_block()** in resnet_v1.py) and the stride is applied to the 3*3 conv layer of the last Residual module in each block(see function **bottleneck()** in resnet_v1.py). 

It's obvious that these two are different. Can anybody explain if it is wrong or implemented as such for some reasons?

**Comment by drpngx** [comment]
@sguada what do you think?

**Comment by sguada** [comment]
Both implementation are equivalent, but the current one is more efficient.

**Comment by n-triple-a** [comment]
@sguada Hi. Could you please explain the equivalence and why it's more efficient?

**Comment by sguada** [comment]
see my updated comment

**Comment by juntingzh** [comment]
@sguada Thank you for the great explanation. Another doubt about the ResNet implementation I have is that in the tf slim resnet_v1_50, resnet_v1_101 and resnet_v1_152 etc. implementations, downsampling is performed by block**1**, block**2**, and block**3**; while in the original ResNet paper, downsampling is performed by conv3_1(block**2** in your notation), conv4_1(block**3**), and conv5_1(block**4**) with a stride of 2. With the skip connections between the blocks involved, the equivalence of two implementations is not clear to me, could you please explain more? Thanks!
