### ISSUE TITLE
Is it possible to remove the "third_party directory"?! [An attempt to package for Ubuntu]

### ISSUE THREAD

**Issue by nkhdiscovery** [tensorflow/tensorflow#9391]
Hi guys,

We have successfully used C/C++ API as shared library in our applications, but there are some issues [like this one](https://github.com/cjweeks/tensorflow-cmake/issues/13) which my colleages ran into.
Simultaneously, I was working to distribute the whole work as a debian package for Ubuntu 16.04, and I found that it is very annoying that you have used many external dependencies under the "third_party" directory. I'm trying to remove these dependencies one by one, which is a little bit troublesome but I think is possible. I am packaging anything else needed on my way.

The question is, do you have any advise on this? What should have been taken care of? And why in first place you put these in your repo instead of leading the users to install specific versions on their system as build dependency? I think that having external header files under the directory after build does not make sense at all! Please lighten me up.

Thanks for your great work, Google and The Community!

**Comment by drpngx** [comment]
The tensorflow executable relies on a hermetic build, to ensure that we build the dependent libraries at the right version that we test, and using the right compilation flags. For instance, LLVM libraries typically requires `-fno-rtti`, which requires careful compilation. We link statically to these dependencies, making your executable effectively unstable if you link with these libraries outside of tensorflow.

Technically the right thing is to seal up tensorflow with `-fvisibility=hidden` to avoid polluting the linkage namespace. It is not a difficult thing to do but we have been postponing the fix.

CC: @keveman @skye

**Comment by davidlt** [comment]
I have been looking into your binary distribution (`libtensorflow-cpu-linux-x86_64-1.1.0.tar.gz`) and one of the first thing for integration I looked into symbol visibility. Please use `-fvisibility=hidden` and only make globally visible symbols from API. There is a good fraction of externals that we already link to (jemalloc, Eigen, etc) thus it would be nice if tensorflow library would be sealed up.

**Comment by nkhdiscovery** [comment]
I tried to hide *google::protobuf* in version script, but it didn't work, I don't know exactly what to hide! I tried to keep only _TF* symbols like in the c_api, but the resulting binary was useless. Please let me know what approximately I have to put in my version script so I will figure it out.

**Comment by drpngx** [comment]
@nkhdiscovery, @girving is going to do this as part of #9525. It's not a trivial change and it's probably better if we did this on our end.

I'm going to close this in favor of #9525 so that every can keep track of progress there.

Thanks.
