### ISSUE TITLE
Build of tensor flow r1.1 w/ Google Cloud option enabled fails: incompatible C++ header and code

### ISSUE THREAD

**Issue by tr8dr** [tensorflow/tensorflow#9392]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:   OS X 10.10.3 (14D2134)
- **TensorFlow installed from (source or binary)**:  github clone / source (r1.1)
- **TensorFlow version (use command below)**: r1.1
- **Bazel version (if compiling from source)**: 0.4.5-homebrew
- **CUDA/cuDNN version**:  N/A (not built with CUDA)
- **GPU model and memory**: N/A (not built with CUDA)
- **Exact command to reproduce**:  
1. configure build for CPU and with google cloud enabled,  
2. bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

### Describe the problem
Build of tensor flow for CPU / google cloud enabled fails for r1.1 (and also master),

1. configure build for CPU and with google cloud enabled,  
2. bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package

### Source code / logs
ERROR: /Users/jshore/src/tensorflow/tensorflow/core/platform/cloud/BUILD:115:1: C++ compilation of rule '//tensorflow/core/platform/cloud:retrying_utils' failed: cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 93 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
tensorflow/core/platform/cloud/retrying_utils.cc:97:9: error: return type 'const tensorflow::Status' must match previous return type 'tensorflow::Status' when lambda expression has unspecified explicit return type
        return status;

**Comment by drpngx** [comment]
Right.

```
const auto& status = delete_func();
```
https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/cloud/retrying_utils.cc#L92
should be:
```
const Status status = delete_func();
```

Would you mind sending a PR?
