### ISSUE TITLE
Abandon gerrit and use github for everything

### ISSUE THREAD

**Issue by resouer** [tensorflow/tensorflow#94]
Gerrit review workflow is very hard to maintain and follow. A lot of project abandoned it and turns to github finally.

Really hope tensorflow will use github for all the cooperation workflow. Google [Kubernetes](https://github.com/kubernetes/kubernetes) and [Docker](https://github.com/docker/docker) are all excellent examples  for how to use github maintain a huge and global scale open source project successfully.

github + travis CI + slack is awesome.  Just make everything be a PR :)

**Comment by graphific** [comment]
:+1:

**Comment by jrabary** [comment]
+1

**Comment by RicoAntonioFelix** [comment]
:+1:

**Comment by ruffsl** [comment]
:+1:

**Comment by anjishnu** [comment]
+1

**Comment by mavenlin** [comment]
+1

**Comment by vrv** [comment]
We hear you all -- the current workflow is not ideal and is a pain for us too.  There are several reasons why we can't just switch solely to github today, but since it *is* a pain for us, we're motivated to try to make things better :).

We'll keep this bug open to track the request.

**Comment by pineking** [comment]
+1

**Comment by resouer** [comment]
@vrv Thanks. btw, if you guys need any help, please fire up related issues, add "help-needed" and area label, and I think all the guys here are eager to fix them :)

**Comment by bhack** [comment]
:+1:

**Comment by cgel** [comment]
+1

**Comment by jsnel** [comment]
+1

**Comment by vrv** [comment]
De-duping with https://github.com/tensorflow/tensorflow/issues/26

**Comment by Dominator008** [comment]
In my opinion doing code review on GitHub is horrible except for very small fixes / tweaks. In addition, all those merge commits from "pull requests" really clutter up the git log.

Blaze (Bazel) uses both Gerrit and GitHub. All external pull requests are not merged directly, but committed through the Gerrit repo. As a result, their commit history looks much cleaner: https://github.com/bazelbuild/bazel/commits/master.

Would you consider keeping a Gerrit mirror and possibly using the Gerrrit-GitHub plugin https://gerrit.googlesource.com/plugins/github/+/master/README.md?
