### ISSUE TITLE
build fail on eigen

### ISSUE THREAD

**Issue by xthepoet** [tensorflow/tensorflow#941]
On Ubuntu 14.04 in a VirtualBox

Followed setup and install instructions and ran:
bazel build -c opt //tensorflow/tools/pip_package:build_pip_package

Stops on error:

INFO: From Compiling tensorflow/core/kernels/conv_grad_ops.cc:
In file included from ./external/eigen_archive/eigen-eigen-b45554449873/unsupported/Eigen/CXX11/Core:35:0,
                 from ./external/eigen_archive/eigen-eigen-b45554449873/unsupported/Eigen/CXX11/Tensor:14,
                 from ./third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1,
                 from ./tensorflow/core/framework/types.h:23,
                 from ./tensorflow/core/framework/type_traits.h:22,
                 from ./tensorflow/core/framework/allocator.h:25,
                 from ./tensorflow/core/framework/op_kernel.h:22,
                 from ./tensorflow/core/framework/numeric_op.h:19,
                 from tensorflow/core/kernels/conv_grad_ops.cc:22:
./external/eigen_archive/eigen-eigen-b45554449873/unsupported/Eigen/CXX11/src/Core/util/EmulateArray.h: In static member function 'static void Eigen::internal::TensorExecutor<Expression, Eigen::ThreadPoolDevice, Vectorizable>::run(const Expression&, const Eigen::ThreadPoolDevice&) [with Expression = const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 4, 1, long int>, 16>, const Eigen::TensorReshapingOp<const Eigen::DSizes<long int, 4>, const Eigen::TensorContractionOp<const Eigen::array<Eigen::IndexPair<long int>, 2ul>, const Eigen::TensorReshapingOp<const Eigen::DSizes<long int, 3>, const Eigen::TensorImagePatchOp<-1l, -1l, const Eigen::TensorMap<Eigen::Tensor<const float, 4, 1, long int>, 16> > >, const Eigen::TensorReshapingOp<const Eigen::DSizes<long int, 3>, const Eigen::TensorReverseOp<const Eigen::array<bool, 4ul>, const Eigen::TensorMap<Eigen::Tensor<const float, 4, 1, long int>, 16> > > > > >; bool Vectorizable = true]':
./external/eigen_archive/eigen-eigen-b45554449873/unsupported/Eigen/CXX11/src/Core/util/EmulateArray.h:24:67: warning: array subscript is above array bounds [-Warray-bounds]
   EIGEN_STRONG_INLINE T& operator[] (size_t index) { return values[index]; }
                                                                   ^
INFO: From Compiling tensorflow/core/kernels/cwise_op_add.cc:
gcc: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
ERROR: /home/sandra/deeplearning/tensorflow/tensorflow/core/BUILD:342:1: C++ compilation of rule '//tensorflow/core:kernels' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 -DNDEBUG -ffunction-sections ... (remaining 78 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 815.245s, Critical Path: 772.81s

I tried running the gcc call and it said somethine like eigen_archive/... didn't exist. I'm not sure where it's mean to be or whether it's generated by this step, but it's not under bazel-bin/external like the other "archive" folders.

$ ls bazel-bin/external/
jpeg_archive/ png_archive/  re2/          

Any help?

**Comment by benoitsteiner** [comment]
The eigen code is downloaded from bitbucket and stored by bazel under bazel-tensorflow/external/eigen_archive.

Can you tell me the exact version of gcc you're using ? I am able to compile on ubuntu without any problem, but I might be using a slightly different revision of the compiler.

**Comment by xthepoet** [comment]
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04) 

How do I run Bazel just to build eigen? Maybe I can try that, and see what errors.

Or if you can tell me how 

Looking around, I see eigen3 under third_party/eigen3

$ ls *
BUILD  LICENSE

Eigen:
Array     Core   Eigenvalues  Householder  LeastSquares  OrderingMethods  StdDeque
Cholesky  Dense  Geometry     Jacobi       LU            QR               SVD

unsupported:
Eigen

**Comment by benoitsteiner** [comment]
Maybe you can download Eigen directly from bitbucket and see if you can successfully compile the tests:
cd /some/dir/
hg clone HTTPS://bitbucket.org/eigen/eigen
mkdir build
cd build
cmake /some/dir/eigen DEIGEN_TEST_CXX11=ON
make check

**Comment by benoitsteiner** [comment]
Is this still a problem?

**Comment by xthepoet** [comment]
Couldn't get it running under VirtualBox on my Mac, so kind of moved on to
do it on a native Ubuntu system (which worked).  I'll give it another shot
in VirtualBox when I have time. Thanks for following up though!

**Comment by benoitsteiner** [comment]
When you try again, can you make sure that you create the VM with a lot of memory? gcc may simply have been running out of memory.
