### ISSUE TITLE
Cifar10 Tutorial Link to Example Code 404's

### ISSUE THREAD

**Issue by jubjamie** [tensorflow/tensorflow#9411]
Following any of the links to the code for the CIFAR10 tutorial 404's.

Example link: https://www.tensorflow.org/versions/master/tutorials/deep_cnn#code_organization

Any from above.

**Comment by aselle** [comment]
I've added this to our docs fixit event list. Thanks for reporting this.

**Comment by kemaswill** [comment]
Seems like the github has already fixed this issue, while the tensorflow.org does not, until next release.

**Comment by jubjamie** [comment]
Closing this but there seems to be similar issues cropping up with the 1.1 branch on the website for example: #9774
