### ISSUE TITLE
Android ops - not supporting NCHW data format

### ISSUE THREAD

**Issue by es007** [tensorflow/tensorflow#9413]
Hi,

I'm using my custom tensorflow v1.0.1 model freezed and exported to Android arm-ABI-v7a (I compiled tensorflow 1.0.1 with selective registration for the models ops).

As a training time optimization we tried to convert the data format to NCHW format (as written in the tensorflow performance tutorial).

But now, when I run inference on Android, I get the following error in the logcat:

 E/native: tensorflow_inference_jni.cc:233 Error during inference: Invalid argument: CPU BiasOp only supports NHWC. [[Node: conv_layer_1/BiasAdd = BiasAdd[T=DT_FLOAT, data_format="NCHW", _device="/job:localhost/replica:0/task:0/cpu:0"](conv_layer_1/conv_l11, bc11_init)]]

Are you going to add NCHW support for android CPU ops in the future versions?

Thanks,
Eran

### System information
- **Have I written custom code: Yes - custom model*:
- **OS Linux Ubuntu 16.04:
- **TensorFlow installed from source:
- **TensorFlow version 1.0.1:
- **Bazel version 0.4.5*:
- **CUDA/cuDNN version 5.1.10:
- **GPU model and memory GTX 1080 TI:

**Comment by girving** [comment]
@andrewharp can comment further, but unfortunately mobile TensorFlow is stripped down for code size reasons.  The easiest solution is to use NHWC ordering.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
