### ISSUE TITLE
[minor bug] tf1.0+ compatibility script doesn't handle old batch_matmul arguments

### ISSUE THREAD

**Issue by liuyipei** [tensorflow/tensorflow#9424]
tf 1.0 merges `batch_matmul` into `matmul`, but the compatibility script forgot to rename the arguments for `batch_matmul`

what is needed is: 
`adj_x` --> `transpose_a`
`adj_y` --> `transpose_b`

I would be happy to write a quick PR.

References:

https://www.tensorflow.org/versions/r0.12/api_docs/python/

https://www.tensorflow.org/api_docs/python/tf/matmul

**Comment by aselle** [comment]
Thanks for volunteering to improve TensorFlow. Please submit the PR, and reference it here!

**Comment by girving** [comment]
Apparently fixed in https://github.com/tensorflow/tensorflow/pull/9448.
