### ISSUE TITLE
libhexagon_controller.so build failed [missing files: GRAPHINIT := /prj/dsp/qdsp6/arch/cnn/setup/inceptionv3_uint8in.c]

### ISSUE THREAD

**Issue by kzos** [tensorflow/tensorflow#9428]
OS: Ubuntu 16.04 64bits
Android Version: 7.1 (Nougat)
NDK Version: android-ndk-r12b
HEXAGON SDK: 3.1
nnlib source: https://source.codeaurora.org/quic/hexagon_nn/nnlib

I have been following the steps provided at below link, for using tensorflow on hexagon. 
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/hvx

Environment and copying files properly as mentioned in the link is taken care of.
Having said that, I am facing 2 issues with the build,

(1-  skel.so) while building skel.so for hexagon , error reported **missing file**

GRAPHINIT := /prj/dsp/qdsp6/arch/cnn/setup/inceptionv3_uint8in.c in nnlib/Makefile

(2 - stub+controller.so) while building libhexagon_controller.so, there is this error reported:

    ------------------------------------------
     --- V = android_Debug_aarch64
     --- GLUE_DIR = glue
     --- HEXAGON_SDK_ROOT = /home/zaheer.s/Qualcomm/Hexagon_SDK/3.1
     ------------------------------------------

 making /home/zaheer.s/Qualcomm/Hexagon_SDK/3.1/test/common/test_util
 making /home/zaheer.s/Qualcomm/Hexagon_SDK/3.1/tools/qaic
 making /home/zaheer.s/Qualcomm/Hexagon_SDK/3.1/libs/common/atomic
 making /home/zaheer.s/Qualcomm/Hexagon_SDK/3.1/libs/common/rpcmem
 making .
 android_Debug_aarch64/hexagon_controller.o: In function                                         `hexagon_controller_InitInputNodeDataToInceptionDummyData':
 /home/zaheer.s/Qualcomm/Hexagon_SDK/3.1/examples/common/generated_hexagon_controller/src_impl/  hexagon_controller.c:74: undefined reference to `inception_dummy_int_data_224x224'
 /home/zaheer.s/Qualcomm/Hexagon_SDK/3.1/examples/common/generated_hexagon_controller/src_impl/  hexagon_controller.c:74: undefined reference to `inception_dummy_int_data_224x224'
 collect2: error: ld returned 1 exit status
 make[1]: *** [android_Debug_aarch64/libhexagon_controller.so] Error 1
 ERROR making .

I am not sure if any work around is provided to fix the missing files causing build error. please suggest a fix.

PS:- I am able to run sample examples provided with ${QUALCOMM_SDK} /examples/common/gemm.

**Comment by girving** [comment]
@satok16: Can you comment?

**Comment by kzos** [comment]
@girving , @satok16 : `undefined reference toinception_dummy_int_data_224x224'`
this error comes when debug option is enabled, 
I am checking how to get rid of 224x224 when debug is enabled.
meanwhile I am successful in running 229x229.

Could you please check how to provide proper build as well runtime fix for debug option enabled.

**Comment by satok16** [comment]
Hi @kzos.  Sorry for the delay.
Currently, the nnlib only supports Hexagon_SDK 3.0, not 3.1.  Actually these different SDKs are not compatible.  If you want to use SDK 3.1 you need to modify glue files a bit.

Can you try using SDK3.0 first?

**Comment by kzos** [comment]
Hi @satok16 , I tried in 3.0/3.1 as well, 
Release build is working fine.
when i tried `android_Debug_aarch64`,
`debug` option gets set somehow and **it has side effects of inception version getting set to 1**

under version 1: toinception_dummy_int_data_224x224 gets used.

i have added new changes in glue to build for android_Debug_aarch64 and pick proper adspmsgd in target/make/android.min.

so could you help in checking below part:
`debug` option gets set somehow and **it has side effects of inception version getting set to 1**

thanks,

**Comment by satok16** [comment]
I see.  That seems to be a bug caused by a difference of compile options.  "inception_dummy_int_data_224x224" is a dummy input data which can be arbitrary binary.  So if you just want to pass the build, please try just putting
`uint8_t inception_dummy_int_data_224x224[224*224*3] = {};
in tensorflow/contrib/hvx/hexagon_controller/src_dummy_data/inception_v3_dummy_int_data.c

Let me know the compile result.

**Comment by kzos** [comment]
oh, that should fix the build, thanks.
but i am not sure that will have its effect at run-time.
I am going through src code, meanwhile if you have right fix for selecting inception v3, please do share.

thanks,

**Comment by satok16** [comment]
No worries, the change won't be a problem as long as you don't use this dummy input by modifying the code.  If you want to use dummy input, you need to put binary data here either way.

**Comment by kzos** [comment]
that hack fixed the Debug enabled bug, will open another case if i face any discrepancies found in build between inception v1/v3

thanks,

**Comment by kanshuzhi** [comment]
@satok16 @kzos 
Could you please show me how to enable nnlib in Qualcomm hexagon 3.1 SDK because Hexagon 3.0 SDK installation package is out-of dated and cannot download remote toolchains?

Best Regards

**Comment by amirjamez** [comment]
@satok16 I am having the same issue on `SDK 3.0` and nnlib git v.(`721b2d58f`). I can compile the `make tree VERBOSE=1 V=hexagon_Release_dynamic_toolv72_v60`, but on the `make tree VERBOSE=1 V=android_Release` I ran into the mentioned problem. There is this missing file in the nnlib/Makefile and I changed it as per your comment to add a dummy integer ( I have now both 299 and 224 in `it/tensorflow/tensorflow/contrib/hvx/hexagon_controller/src_dummy_data/inception_v3_dummy_int_data.c:`

```
#include <stdint.h>
uint8_t inception_dummy_int_data_299x299[299*299*3] = {};
uint8_t inception_dummy_int_data_224x224[224*224*3] = {};
```
 I passed the error and now have this other compilation error:

```
make[1]: *** No rule to make target `adspmsgd.a', needed by `android_Release/graph_app'.  Stop.
make[1]: Leaving directory `~/Qualcomm/Hexagon_SDK/3.0/examples/common/nnlib'
```
