### ISSUE TITLE
(v1.1.0, CPU)SSE,SSE2,etc warning messages on Windows 10

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#9430]
These are awkward messages since TensofFlow doesn't support windows build officially.

![image](https://cloud.githubusercontent.com/assets/4515120/25375011/5e524a40-29da-11e7-96f9-b9f4f17ae3ee.png)

**Comment by girving** [comment]
You'll need to compile it yourself if you want to get rid of them.
