### ISSUE TITLE
Tensorflow Error - no such package '@local_config_cuda//cuda'

### ISSUE THREAD

**Issue by Bonkoodle** [tensorflow/tensorflow#9435]
So I'm trying to run the image retraining official tensorflow tutorial from this link: https://www.tensorflow.org/tutorials/image_retraining 

I need to get it working for my dissertation with my own images in less than a month so it's extremely urgent.
Once I get to the line "bazel build tensorflow/examples/image_retraining:retrain"
I get this output:
"ERROR: error loading package 'tensorflow/examples/image_retraining': Encountered error while reading extension file 'cuda/build_defs.bzl': no such package '@local_config_cuda//cuda': error loading package 'external': The repository named 'local_config_cuda' could not be resolved."

This thread seems to be the same issue, but no solutions offered: https://github.com/tensorflow/tensorflow/issues/5805

This thread has more activity but it's talking about '@local_config_cuda//crosstool' rather than '@local_config_cuda/cuda/' so may not be helpful for me: https://github.com/tensorflow/tensorflow/issues/4105

I'm using Linux Mint.
Here is my tf_env.txt file for details about my system: [tf_env.txt](https://github.com/tensorflow/tensorflow/files/954822/tf_env.txt)
Let me know if there's any other details I should add which could be useful.

I used this page for installation: https://www.tensorflow.org/install/install_linux
So CUDA® Toolkit 8.0.
cuDNN v5.1
virtualenv install of Tensorflow

Trying to run python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
says "Failed to load the native TensorFlow runtime."
but I can get other simple Tensorflow stuff to work so not sure why that is.

**Comment by aselle** [comment]
What verison of tensorflow source are you using? i.e. run
```
git describe 
```
from the root of your tensorflow sources?

Are you able to build a working whl from source in general?
https://www.tensorflow.org/install/install_sources

If that doesn't work, Try to build TensorFlow with only CPU suppport. If that can be made to work then try flowers with the cpu version.

**Comment by Bonkoodle** [comment]
When I run 
git describe
I get "fatal: Not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)."

So I must have done something wrong. What exactly do you mean by "from the root of your tensorflow sources"? 
Does that simply mean to call "cd /home/bonkoodle/tensorflow" so that I'm in my tensorflow folder before running it? Or is there something more complex I have to do?

But if I call source ./tensorflow/bin/activate
then I can successfully run the standard test code of: 
python 
>>> import tensorflow as tf
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
>>> print(sess.run(hello))

I tried installing it on my laptop but encountered the exact same error.
Both times my tensorflow folder was missing the examples folder and didn't have the BUILD file or tensorflow.bzl.
So what I did was to download the whole tensorflow-master from https://github.com/tensorflow/tensorflow
Then copy the files over to my regular tensorflow installation.
But that's quite likely why it's not working, I must have done something incorrectly, is there some other way of adding these additional folders/files which are needed for running "bazel build tensorflow/examples/image_retraining:retrain"?

Also should I be using Python 2.7 or Python 3.x?
I'm attempting with 2.7 atm but not really sure which is best.


As for installing from source I gave it a go and so far got down to the line where you call
"sudo pip install /tmp/tensorflow_pkg/tensorflow-1.0.1-py2-none-any.whl" but I'm getting an error 
"IOError: [Errno 2] No such file or directory: '/tmp/tensorflow_pkg/tensorflow-1.0.1-py2-none-any.whl'"
Isn't that the name of the file which we're trying to install though? So why would it be looking for the file it's installing?

**Comment by aselle** [comment]
Your /home/bonkoodle/tensorflow seems to be the root of a virtualenv.
- The root of your TensorFlow sources is where git clone dropped a tensorflow directory.
- Please follow this to build TensorFlow https://www.tensorflow.org/install/install_sources
- I don't think image_retraining even requires creating a whl part. Just follow the previous document up to building the pip package. Then switch to the flower train instructions.
- I'd use python 2.7.

**Comment by Bonkoodle** [comment]
I finally got the image retraining file to work by installing from sources, thanks a lot dude.

I'm fairly sure I got this line to work somehow
>sudo pip install /tmp/tensorflow_pkg/tensorflow-1.0.1-py2-none-any.whl

I think I forgot to set the LD_LIBRARY_PATH variables last time since I wasn't sure how to do it at first. Which I think I did correctly by running the code from section 6.1.1 of:
http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#axzz4fM4cvC1G
Although it didn't display any confirmation so I wasn't sure it it worked or not, and wasn't sure if you're actually supposed to copy the '$' sign on the 2nd line.

Also I got an ImportError so I had to run 
>pip install mock
which I found on here http://stackoverflow.com/questions/11501520/importerror-no-module-named-mock

Now I want to train it with my own images, I'm planning to use over 12000 images for 8 flower categories from the ImageNet database.
Is there a good way to automatically process them in terms of cropping them to size or adding whitespace/shrinking to make them the right size?
From what I understand they'll be automatically cropped anyway if you feed them in normally, but the performance will be worse since they'll be cropped badly.

And there seems to be around 3000 images for the standard retraining set, so I'm guessing it'd take about 4 times the time (so about 4 hours). Or will the cropping add loads of extra time?
Because it's running with CPU only atm which will make it much longer.
As long as the cropping doesn't make it take like several days it should be fine though.

I was getting some error when trying to follow the exact same steps on my main PC instead of laptop.

**Comment by aselle** [comment]
Closing now since the not-working issue is resolved. Please ask this usage question on StackOverflow (and post the link here). You can create a numpy or tensorflow script that resizes image as a separate process and writes them into a new directory.

"And there seems to be around 3000 images for the standard retraining set, so I'm guessing it'd take about 4 times the time (so about 4 hours). Or will the cropping add loads of extra time?
Because it's running with CPU only atm which will make it much longer.
As long as the cropping doesn't make it take like several days it should be fine though."

**Comment by rdaems** [comment]
For anyone else who didn't install tensorflow from sources and just wants to run the image_retraining example: you can just run the python code (retrain.py). You don't have to re-install from sources.

**Comment by redradist** [comment]
@aselle I have faced with the same error during the building tensorflow v2.3.0 ...
```console
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
        _create_local_cuda_repository(<1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 955, in _create_local_cuda_repository
        _get_cuda_config(repository_ctx, <1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 657, in _get_cuda_config
        find_cuda_config(repository_ctx, <2 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 635, in find_cuda_config
        _exec_find_cuda_config(<3 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 629, in _exec_find_cuda_config
        execute(repository_ctx, <1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
        fail(<1 more arguments>)
Repository command failed
script.py:124: DeprecationWarning: invalid escape sequence \d
  match = re.match("#define %s +(\d+)" % name, line)
script.py:260: DeprecationWarning: invalid escape sequence \d
  pattern = "Cuda compilation tools, release \d+\.\d+, V(\d+\.\d+\.\d+)"
script.py:553: DeprecationWarning: invalid escape sequence \w
  match = re.match("^(/[^/ ]*)+/lib/\w+-linux-gnu/?$", os.environ[env_name])
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-10.2/include/cuda.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda/include/cublas_api.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/include/cudnn.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/include/cudnn_version.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 1369
        _create_local_cuda_repository(<1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 955, in _create_local_cuda_repository
        _get_cuda_config(repository_ctx, <1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 657, in _get_cuda_config
        find_cuda_config(repository_ctx, <2 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 635, in find_cuda_config
        _exec_find_cuda_config(<3 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/gpus/cuda_configure.bzl", line 629, in _exec_find_cuda_config
        execute(repository_ctx, <1 more arguments>)
    File "/home/{User}/Projects/AI/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
        fail(<1 more arguments>)
Repository command failed
script.py:124: DeprecationWarning: invalid escape sequence \d
  match = re.match("#define %s +(\d+)" % name, line)
script.py:260: DeprecationWarning: invalid escape sequence \d
  pattern = "Cuda compilation tools, release \d+\.\d+, V(\d+\.\d+\.\d+)"
script.py:553: DeprecationWarning: invalid escape sequence \w
  match = re.match("^(/[^/ ]*)+/lib/\w+-linux-gnu/?$", os.environ[env_name])
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda-10.2/include/cuda.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/local/cuda/include/cublas_api.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/include/cudnn.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
script.py:123: ResourceWarning: unclosed file <_io.TextIOWrapper name='/usr/include/cudnn_version.h' mode='r' encoding='utf-8'>
  for line in io.open(path, "r", encoding="utf-8").readlines():
ResourceWarning: Enable tracemalloc to get the object allocation traceback
INFO: Elapsed time: 8.508s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```
