### ISSUE TITLE
small error in DynamicAttentionWrapper

### ISSUE THREAD

**Issue by vrenkens** [tensorflow/tensorflow#9439]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:

Not relevant

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Not relevant

- **TensorFlow installed from (source or binary)**:

Not relevant

- **TensorFlow version (use command below)**:

1.1

- **Bazel version (if compiling from source)**:

Not relevant

- **CUDA/cuDNN version**:

Not relevant

- **GPU model and memory**:

Not relevant

- **Exact command to reproduce**:

Not relevant

### Describe the problem

line 465 in tensorflow/tensorflow/contrib/seq2seq/python/ops/dynamic_attention_wrapper.py says 

'''
if not callable(cell_input_fn):. 
'''
I think it should say 

'''
if not callable(probability_fn):
'''

### Source code / logs

None

**Comment by Songweiping** [comment]
The attention wrapper has been rewritten in master branch, there is no dynamic_attention_wrapper.py any more. 
Anyway, I think this typo was fixed in commit https://github.com/tensorflow/tensorflow/commit/0557e8f90c1a2f027f4561c70558c6c836138058. You can update your TensorFlow and check it.

**Comment by aselle** [comment]
@vrenkens, thanks for submitting this, but it looks like it is already fixed. Closing for now. Let us know if upgrading doesn't resolve your issues.
