### ISSUE TITLE
dynamic_rnn: session.run with train_step behaves differently than train_step run alone

### ISSUE THREAD

**Issue by srkunze** [tensorflow/tensorflow#9446]
### System information
- 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- via pip
- 1.0.0-65-g4763edf-dirty 1.0.1
- cuda-8.0 + cudnn-5.1.10
- GeForce GTX 760 + 1996MiB

### Describe the problem

Consider the following pieces of code:

#### Variant 1
    loop:
        feed_dict = {c_state: current_state.c, h_state: current_state.h, ...}
        loss_sum, current_state, _ = sess.run([reduce_sum(loss), final_state, train_step], feed_dict=feed_dict)

#### Variant 2
    loop:
        feed_dict = {...}
        loss_sum, current_state = sess.run([reduce_sum(loss), final_state], feed_dict=feed_dict)
        train_step.run(feed_dict)

#### Variant 3
    loop:
        feed_dict = {...}
        loss_sum, current_state = sess.run([reduce_sum(loss), final_state], feed_dict=feed_dict)
        sess.run([train_step], feed_dict=feed_dict)

**Variant 1** breaks after a couple of iterations (15 in my case) by raising a "ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[200,10,25600]" exception whereas **Variant 2** and **Variant 3** do not.

train_step is a minimize operation (optimizer doesn't matter) on a dynamic_rnn with a given initial_state and a single layer of LSTM cells.

I cannot imagine the reason why **Variant 1** needs more and more memory whereas the other both don't. Seems like something's wrong here.

**Comment by girving** [comment]
It's quite reasonable that doing more things in parallel would need more memory.  Thus, this question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by srkunze** [comment]
@girving Thanks for your quick response. I would agree with you when the ResourceExhaustedError would occur on the first loop iteration.

But it is not and so it seems like a session.run accidentally keeps/leaks some memory.

**Comment by girving** [comment]
Unfortunately, memory usage is not necessarily deterministic in TensorFlow, since parallel ops execute asynchronously.

**Comment by srkunze** [comment]
A ResourceExhaustedError after always 15 iterations seems like a pretty deterministic memory increase if you ask me.

**Comment by girving** [comment]
Well, you haven't shown any code, so there's no evidence it's a bug in TensorFlow and no way for us to debug it.  If you have code and evidence, we can reopen.

**Comment by srkunze** [comment]
Here you are. It could be possible if there's something wrong with my code but when it's non-obvious from reading the docs (at least not to me).

    from itertools import islice
    
    from io import BytesIO
    from tensorflow import float32, placeholder, Variable, zeros, matmul, reduce_mean, reduce_sum, train, \
        InteractiveSession, global_variables_initializer, argmax, constant, truncated_normal, reshape
    from tensorflow.contrib.rnn import LSTMCell
    from tensorflow.contrib.rnn import LSTMStateTuple
    from tensorflow.python.ops.nn_ops import sparse_softmax_cross_entropy_with_logits
    from tensorflow.python.ops.rnn import dynamic_rnn
    
    
    def get_one_hot(i, num_units, num_chars, on=1.0):
        from numpy import zeros
        one_hot = zeros([num_chars * num_units])
        one_hot[[i+j*num_chars for j in range(num_units)]] = on
        return one_hot
    
    
    def gen_data(batch_size, file, max_length=None, forward_size=None):
        forward_size = forward_size or batch_size
        def get_one_hot_stream(file):
            while True:
                byte = file.read(1)
                if not byte or max_length and file.tell() > max_length:
                    file.seek(0)
                    continue
                yield get_one_hot(ord(byte), num_units, num_chars)
        one_hots_stream = get_one_hot_stream(file)
        one_hots = [one_hot for one_hot in islice(one_hots_stream, 0, num_steps+batch_size+num_steps//2)]
        while True:
            yield [one_hots[i:num_steps+i] for i in range(batch_size)], [one_hots[i+num_steps//2:num_steps+i+num_steps//2] for i in range(batch_size)]
            for i in range(forward_size):
                one_hots = one_hots[1:] + [next(one_hots_stream)]
    
    def get_one_hot_string(x):
        return ''.join(chr(a) if chr(a) not in ['\n', '\t', '\r'] else ' ' for a in x)
    
    
    num_chars = 256
    num_units = 100
    num_steps = 200
    
    chars = placeholder(float32, [None, None, num_units * num_chars], 'chars')
    targets = placeholder(float32, [None, None, num_units * num_chars], 'targets')
    
    cell = LSTMCell(num_units)
    c_state = placeholder(float32, [None, num_units], 'c_state')
    h_state = placeholder(float32, [None, num_units], 'h_state')
    initial_state = LSTMStateTuple(c_state, h_state)
    outputs, final_state = dynamic_rnn(cell, chars, initial_state=initial_state)
    
    softmax_w = Variable(truncated_normal([num_units, num_chars], stddev=0.1))
    softmax_b = Variable(constant(0.1, shape=[num_chars]))
    output = reshape(outputs, [-1, num_units])
    logits = matmul(output, softmax_w) + softmax_b
    loss = sparse_softmax_cross_entropy_with_logits(logits=logits, labels=reshape(argmax(targets[:, :, 0:255], 2), [-1]))
    cost = reduce_mean(loss)
    
    train_step = train.AdamOptimizer(0.01).minimize(cost)
    
    sess = InteractiveSession()
    sess.run(global_variables_initializer())
    
    batch_size = 10
    source = gen_data(batch_size, BytesIO(b'test'))
    current_state = LSTMStateTuple(c=zeros([batch_size, cell.state_size.c]).eval(), h=zeros([batch_size, cell.state_size.h]).eval())
    for i, batch in enumerate(source):
        feed_dict = {c_state: current_state.c, h_state: current_state.h, chars: batch[0], targets: batch[1]}
        loss_sum, current_state, _ = sess.run([reduce_sum(loss), final_state, train_step], feed_dict=feed_dict)

**Comment by srkunze** [comment]
After tweaking the minimal example, I also got the error after 17 and 18 iterations
I noticed the free memory increased from 1.45 MiB (runs with 15 iterations to fail) to 1.63 MiB

    Total memory: 1.95GiB
    Free memory: 1.63GiB

**Comment by srkunze** [comment]
I played around with the num_units parameter:

1.22 GiB + num_units=50 => 72 iterations
1.22 GiB + num_units=25 => 353 iterations

**Comment by srkunze** [comment]
@girving What else is needed to re-consider this issue?

**Comment by girving** [comment]
Apologies: was on vacation and should have transferred to someone else.  Back now.

From your code I'd be quite surprised if the leak is in TensorFlow.  Sessions don't hold onto any tensors between runs at all unless you're doing partial run.  What happens if you skip the `session.run` calls for the iterations that don't run out of memory, and just do it once on the iteration that should crash?
