### ISSUE TITLE
Unable to install v0.11 - missing distribution

### ISSUE THREAD

**Issue by jrajagopal** [tensorflow/tensorflow#9447]
### System information
- **OS Platform and Distribution**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Not installed
- **TensorFlow version (use command below)**: 0.11
- **CUDA/cuDNN version**: 5.0
- **GPU model and memory**: Titan X 12 GB
- **Exact command to reproduce**:
root@system76-server:/# export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0-cp35-cp35m-linux_x86_64.whl
root@system76-server:/# sudo -H pip3 install --upgrade TF_BINARY_URL

### Describe the problem
The distribution for v0.11 is missing. I am building from binary. Here is the error message:
"Collecting TF_BINARY_URL
  Could not find a version that satisfies the requirement TF_BINARY_URL (from versions: )
No matching distribution found for TF_BINARY_URL"

There is some URGENCY here. At our startup, we have just started a pilot with our very first client. Due to privacy concerns, the app is being shipped to client on a desktop, which is being set up right now. Our current stable app version uses TF 0.11 and we dont wish to move to 1.0 unless absolutely unavoidable. 

Would really appreciate it if you would help asap!

PS: This might help just me, but given this is a distribution issue, others may also benefit from this. Either ways, many apologies if this is the wrong request for GitHub!

**Comment by aselle** [comment]
add a $ to TF_BINARY_URL i.e.
```
sudo -H pip3 install --upgrade $TF_BINARY_URL
```

**Comment by jrajagopal** [comment]
Duh! Sorry this should not have been logged here. Its closed now.
