### ISSUE TITLE
python tensorflow ImportError

### ISSUE THREAD

**Issue by Yoshiharo** [tensorflow/tensorflow#9454]
The following is my code:

#matplotlib inline
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
from sklearn.metrics import confusion_matrix

tf.__version__
from tensorflow.examples.tutorials.mnist import input_data
data = input_data.read_data_sets("data/MNIST/", one_hot=True)

print("Size of:")
print("- Training-set:\t\t{}".format(len(data.train.labels)))
print("- Test-set:\t\t{}".format(len(data.test.labels)))
print("- Validation-set:\t\t".format(len(data.validation.labels)))

data.test.labels[0:5, :]
data.test.cls = np.array([label.argmax() for label in data.test.labels])
data.test.cls[0:5]

--------------------------------------------------------------------------------

The error in above code is:

Traceback (most recent call last):
  File "C:/Users/KumarRaja/Desktop/skywalker.py", line 5, in <module>
    from sklearn.metrics import confusion_matrix
  File "C:\Users\KumarRaja\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\__init__.py", line 57, in <module>
    from .base import clone
  File "C:\Users\KumarRaja\AppData\Local\Programs\Python\Python35\lib\site-packages\sklearn\base.py", line 10, in <module>
    from scipy import sparse
  File "C:\Users\KumarRaja\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\sparse\__init__.py", line 221, in <module>
    from .csr import *
  File "C:\Users\KumarRaja\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\sparse\csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
  File "C:\Users\KumarRaja\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\sparse\_sparsetools.py", line 7, in <module>
    __bootstrap__()
  File "C:\Users\KumarRaja\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\sparse\_sparsetools.py", line 6, in __bootstrap__
    imp.load_dynamic(__name__,__file__)
  File "C:\Users\KumarRaja\AppData\Local\Programs\Python\Python35\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

---------------------------------------------------------------------------------------------------------------
I hv installed the missing dll files in their respective location but the code isn't working after that also.Please help me with the above problem.

**Comment by girving** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by Carmezim** [comment]
@Yoshiharo also, what specifically makes you thing it is a TensorFlow bug? I might be missing something but by the stack trace it seems related to scikit-learn

**Comment by Yoshiharo** [comment]
@Adriano yeah previously the error was coming in sklearn module of python which I removed and now it is saying import error something related to dll's.

Thanks & Regards,



RAJAT KUMAR

Technical Trainee

FUJITSU CONSULTING INDIA
 Talwade, Pune
Office: +91-020-2769001

Mobile: + 91 9411292603

Email: Rajat.Kumar@in.fujitsu.com<mailto:Rajat.Kumar@in.fujitsu.com>

Shaping Tomorrow with You

________________________________

**Comment by Carmezim** [comment]
@Yoshiharo the suggestion remains as DLL errors may derive from the possibility I referred to previously, e.g. lack of required dependencies installed can generate this exact error, which is not related to TensorFlow in this case. By the way if you removed sci-kit learn it really shouldn't work.

Also as @girving oriented please provide the full information the Issue template requires, it assists in solving the problem more efficiently. Without all the information the support for your problem will be sub-optimal.

**Comment by skye** [comment]
Closing due to lack of recent activity. Please reopen if this is still an issue.
