### ISSUE TITLE
TFClassify taking too long to disply result

### ISSUE THREAD

**Issue by shubhamshekhar** [tensorflow/tensorflow#9456]
I am using tensorflow in android. I installed the apk for TFClassify available. I ran the application and it is running swiftly with inference time of not more than 400ms. However when I replaced the available trained model with my model, it is taking around 2000ms for computational before displaying the result. Why is there such a difference and how can I optimize my retrained_graph.pb? I have converted the retrained model to optimized & quantized graph.

**Comment by girving** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
