### ISSUE TITLE
running my built tensorflow with cifar10 core dump

### ISSUE THREAD

**Issue by fancyerii** [tensorflow/tensorflow#946]
I have followed the instructions to build tensorflow with master branch with gpu.
the only difference is that when I installed cuda7, I can't install the driver because I am not the root.
The admin already installed cuda 7.5 and drivers.
Also, I can't copy cuda 7 so to /usr/local/lib.
when running ./configure I specify the cuda 7 path instead of default value.
After building, I installed it within virtualenv.
$virtualenv --system-site-packages ~/tfenv
$source ~/tfenv/bin/activate
$pip install /tmp/tensorflow_pkg/tensorflow-0.6.0-py2-none-any.whl

$export LD_LIBRARY_PATH=/home/lli/cuda-7.0/lib64
$python cifar10_train.py
.....
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 8.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:67] Creating bin of max chunk size 16.00GiB
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:244] PoolAllocator: After 1925 get requests, put_count=1701 evicted_count=1000 eviction_rate=0.587889 and unsatisfied allocation rate=0.687792
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:256] Raising pool_size_limit_ from 100 to 110
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:244] PoolAllocator: After 4577 get requests, put_count=4625 evicted_count=1000 eviction_rate=0.216216 and unsatisfied allocation rate=0.213022
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:256] Raising pool_size_limit_ from 256 to 281
F tensorflow/stream_executor/cuda/cuda_dnn.cc:207] could not find cudnnCreate in cudnn DSO; dlerror: /home/lli/tfenv/local/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cudnnCreate
Aborted (core dumped)

**Comment by fancyerii** [comment]
there are 8  TITAN X cards installed in this machine.

**Comment by vrv** [comment]
F tensorflow/stream_executor/cuda/cuda_dnn.cc:207] could not find cudnnCreate in cudnn DSO

suggests that you didn't point to the right cudnn path.

1) Double check that you pass the right paths when running ./configure before building the pip package
2) Try 


```
TF_UNOFFICIAL_SETTING=1 ./configure
```

to specify the cudnn versions / library paths.
