### ISSUE TITLE
a dead link to the TensorBoard: Graph Visualization tutorial in the TensorBoard page

### ISSUE THREAD

**Issue by unnir** [tensorflow/tensorflow#9460]
Hi all,

there is a dead link to the TensorBoard: Graph Visualization tutorial from the TensorBoard Graphs page
[
<img width="668" alt="screen shot 2017-04-26 at 16 17 40" src="https://cloud.githubusercontent.com/assets/1344378/25439486/d78f29e2-2a9c-11e7-87e1-f73e0dbf848c.png">
](url)
now:

https://www.tensorflow.org/versions/master/how_tos/graph_viz/

should be:

https://www.tensorflow.org/get_started/graph_viz

OS - MacOS,
TensorFlow from pip or conda
Version: v1.0.0-rc2-15-g47bba63-dirty 1.0.0

Best,
Paddy

**Comment by unnir** [comment]
it seems I'm using an old version, everything is fine with the link in the repo:

https://github.com/tensorflow/tensorflow/blob/52dcb2590bb9274262656c958c105cb5e5cc1300/tensorflow/tensorboard/components/tf_dashboard_common/tf-no-data-warning.html

**Comment by girving** [comment]
No worries!
