### ISSUE TITLE
numpy prod overflow during creating tensor

### ISSUE THREAD

**Issue by fesun** [tensorflow/tensorflow#9462]
I am trying to allocate super large tensor using tensorflow, but failed.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/tensor_util.py#L417
Above code uses numpy.prod to calculate shape size, and for numpy everything is typed, say if the shape is [500000000, 5], then numpy.prod returns -1794967296, it's very easy to reproduce it.
So how about use int64 instead? int64 should be large enough for any tensor.
Changing shape_size = np.prod(shape) to shape_size = np.prod(shape, dtype=np.int64) should fix it. Also about 100 lines of code using np.prod, could we change them all to int64?

**Comment by girving** [comment]
@fesun Are you on a 32 bit machine?  I get

    >>> np.prod([500000000, 5])
    2500000000
    >>> np.prod([500000000, 5]).dtype
    dtype('int64')

Explicitly setting `dtype=np.int64` does seem like the right solution, but I'd like to understand why it's breaking for you first.

**Comment by mrry** [comment]
Maybe it's a Windows issue? https://docs.scipy.org/doc/numpy/user/basics.types.html#id3 says that the default integer type is the same as a C `long`, which is 32 bits in MSVC.

**Comment by fesun** [comment]
@girving I am on 64 bit windows machine, I think @mrry is right, numpy default int type inside windows is 32 bit.

**Comment by girving** [comment]
@fesun Would you be up for a pull request?  Adding `dtype=np.int64` sounds good.

**Comment by fesun** [comment]
@girving sure, thanks.
