### ISSUE TITLE
Drupal8 chatbot integrate with TensorFlow

### ISSUE THREAD

**Issue by AlexMazaltov** [tensorflow/tensorflow#9463]
Looking for developer who able to integrate tensorflow for answer to users in messenger if it was not recognized by prepared static answers. 
https://www.drupal.org/project/chatbot/releases/8.x-1.x-dev
High rate of operating for this job.

**Comment by AlexMazaltov** [comment]
Looking for developer who can use tensorflow

**Comment by girving** [comment]
This is not a  bug or feature request.
