### ISSUE TITLE
Misleading error message when running restore op with path to an .index file

### ISSUE THREAD

**Issue by peci1** [tensorflow/tensorflow#9465]
Using V2 checkpoint files, calling `saver.restore()` with path to the `.index` returns the following error: 

    Error loading checkpoint from /home/peci1/tradr-git/tradr-ws/src/tradr-simulation/safe_exploration/scripts/ddpg/models/my-model.index: Not found: Tensor name "ActorFullyConnected1/b" not found in checkpoint files /home/peci1/tradr-git/tradr-ws/src/tradr-simulation/safe_exploration/scripts/ddpg/models/my-model.index

I think it'd be nicer to get an error saying "File ... is not a checkpoint. Please, remove the .index extension". This is roughly what you get if you pass any other file.

**Comment by aselle** [comment]
@concretevitamin, could you consider making this message more friendly, or could you direct @peci1 on how to prepare a contribution to that effect--provided @peci1  is willing.

**Comment by skye** [comment]
Marking this contributions welcome, if anyone wants to dig in and pick this up...
