### ISSUE TITLE
Cmake build error on windows 10 (fatal error C1001)

### ISSUE THREAD

**Issue by guileryu01** [tensorflow/tensorflow#9470]
### System information
- **Have I written custom code**: No
- **OS Platform and Distribution**: Windows 10
- **TensorFlow installed from**:source
- **TensorFlow version**:master
- **Bazel version**:NA
- **CUDA/cuDNN version**:8.0/5.1
- **GPU model and memory**:GTX 1080
- **Exact command to reproduce**:MSBuild /p:Configuration=Release tf_python_build_pip_package.vcxproj

### Describe the problem
I was following cmake build instruction
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake
to build python package with GPU support using visual studio 2015 Update 3. It took a few hours until I hit fatal error C1001.

### logs
```
c:\work\libraries_local\tensorflow\tensorflow\core\kernels\reduction_ops_gpu.cu.cc(64): fatal error C1001: An internal error has occurred in the compiler. [C:\work\libraries_local\tensorflow\tensorflow\contrib\cmake\build\tf_core_gpu_kernels.vcxproj]
  
  (compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 255)
  
   To work around this problem, try simplifying or changing the program near the locations listed above.
```

**Comment by girving** [comment]
Ah, an internal compiler error in the main Eigen statement.  Not sure what can be done here other than using a newer version of Visual Studio.

@mrry: We don't seem to have documentation on which Visual Studio versions work.  I realize none of them are supported, but is there a place I can refer to about unsupported versions?

**Comment by mrry** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md talks about known-good configurations, but I'm pretty sure we build with VS 2015 Update 3 regularly. 

Perhaps the introduction of DT_COMPLEX support in https://github.com/tensorflow/tensorflow/commit/88a6cdeb5ee79765462932a611d4d16dd715007c has broken the GPU build on Windows?

**Comment by girving** [comment]
@guileryu01 Can you disable the complex instantiation and see if it goes through?

**Comment by guileryu01** [comment]
Thank you. Sure I will give it a try. How do I disable complex instantiation? Is that one of the options when generating solution and project files with cmake?

Below is the command I was using

```
cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release ^
-DSWIG_EXECUTABLE=C:/work/tools/swigwin-3.0.12/swig.exe ^
-DPYTHON_EXECUTABLE=C:/Anaconda3/envs/python35/python.exe ^
-DPYTHON_LIBRARIES=C:/Anaconda3/envs/python35/libs/python35.lib ^
-Dtensorflow_ENABLE_GPU=ON ^
-DCUDNN_HOME="C:\Program Files\NVIDIA GPU Computing Toolkit\cudnn5" ^
-Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX
```

**Comment by girving** [comment]
@guileryu01 Uncomment these lines in `eduction_ops_gpu.cu.cc`:

    DEFINE_FOR_TYPE_AND_R(complex64, Eigen::internal::SumReducer<complex64>);
    DEFINE_FOR_TYPE_AND_R(complex128, Eigen::internal::SumReducer<complex128>);
    DEFINE_FOR_TYPE_AND_R(complex64, Eigen::internal::MeanReducer<complex64>);
    DEFINE_FOR_TYPE_AND_R(complex128, Eigen::internal::MeanReducer<complex128>);
    DEFINE_FOR_TYPE_AND_R(complex64, Eigen::internal::ProdReducer<complex64>);
    DEFINE_FOR_TYPE_AND_R(complex128, Eigen::internal::ProdReducer<complex128>);

**Comment by guileryu01** [comment]
I didn't try commenting out those lines, however it turns out that after removing
```
-Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX
```
in the configuration, I managed to compile the project. Many thanks!

**Comment by teeekay** [comment]
@girving 
I observed the same thing as @guileryu01 and have a similar setup.
```
Have I written custom code: No
OS Platform and Distribution: Windows 10
TensorFlow installed from:source
TensorFlow version:master
Bazel version:NA - (Using Cmake and Visual Studio 2015)
CUDA/cuDNN version:8.0/5.1
GPU model and memory:GTX 1060 6Gb
```
Exact command to reproduce:


```
c:>cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release ^
-DSWIG_EXECUTABLE=C:/swigwin-3.0.12/swig.exe ^
-DPYTHON_EXECUTABLE=C:/Users/tknight/AppData/Local/Programs/Python/Python35/python.exe ^
-DPYTHON_LIBRARIES=C:/Users/tknight/AppData/Local/Programs/Python/Python35/libs/python35.lib ^
-Dtensorflow_ENABLE_GPU=ON ^
-DCUDNN_HOME="C:\cuDNN" ^
-Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX

c:>MSBuild /p:Configuration=Release tf_python_build_pip_package.vcxproj
```
results in:
```
\tensorflow\core\kernels\reduction_ops_gpu.cu.cc(64): fatal error C1001: An internal error h as occurred
```
after about 3 hours of building.

If I remove the line regarding arch:AVX in the cmake command
```
-Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX 
```
The python wheel builds ok.

I want to help getting the builds with CPU optimizations to work for Windows -
I wasn't exactly clear what you were asking to be done.  I tried commenting out the six lines you referenced, and this resulted in 31 linking errors instead. - I have clipped them from the console output and put them in [build_errors.txt](https://github.com/tensorflow/tensorflow/files/966527/build_errors.txt).

Let me know if/how to continue..

**Comment by teeekay** [comment]
I ran a build with 
```
cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release ^
-DSWIG_EXECUTABLE=C:/swigwin-3.0.12/swig.exe ^
-DPYTHON_EXECUTABLE=C:/Users/tknight/AppData/Local/Programs/Python/Python35/python.exe ^
-DPYTHON_LIBRARIES=C:/Users/tknight/AppData/Local/Programs/Python/Python35/libs/python35.lib ^
-Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX

MSBuild /p:Configuration=Release tf_python_build_pip_package.vcxproj /fl1 /fl2 /fl3 /flp2:logfile=JustErrors.log;errorsonly /flp3:logfile=JustWarnings.log;warningsonly
```
and it built ok (no errors), so the problem appears to be limited to the combination of tensorflow with GPU and arch:AVX.

**Comment by teeekay** [comment]
@mrry , After commenting those lines out it built ok,

```
"C:\tools\msys64\home\tknight\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj" (default target) (1) ->
(PostBuildEvent target) ->
  EXEC : warning : no files found matching '*.so' under directory '*' [C:\tools\msys64\home\tknight\tensorflow\tensorflow\contrib\cmake\build\tf_python_build_pip_package.vcxproj]

    4632 Warning(s)
    0 Error(s)

Time Elapsed 03:50:15.38
```

```
 Directory of C:\tools\msys64\home\tknight\tensorflow\tensorflow\contrib\cmake\build\tf_python\dist

05/01/2017  03:51 PM    <DIR>          .
05/01/2017  03:51 PM    <DIR>          ..
05/01/2017  03:51 PM        51,751,621 tensorflow_gpu-1.1.0rc2-cp35-cp35m-win_amd64.whl
               1 File(s)     51,751,621 bytes
```
installed wheel and it is functional.   next steps...

**Comment by andydavis1** [comment]
Looks resolved. Please re-open if not...
