### ISSUE TITLE
Tensorboard text summary ops not on r1.1

### ISSUE THREAD

**Issue by cgorman** [tensorflow/tensorflow#9474]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.12.4
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: `v1.1.0-rc0-61-g1ec6ed5 1.1.0`
- **Bazel version (if compiling from source)**: n/a
- **CUDA/cuDNN version**: n/a
- **GPU model and memory**: n/a
- **Exact command to reproduce**: `tmp = tf.summary.text('Hello')`

### Describe the problem
Tensorboard in r1.1 has a text summary tab and it is mentioned in RELEASE.md but it looks like the command to add a text summary is not available. It's on the [master](https://github.com/tensorflow/tensorflow/blob/6a1825e2369d2537e15dc585705c53c4b763f3f6/tensorflow/python/summary/summary.py#L65) branch but not on [r1.1](https://github.com/tensorflow/tensorflow/blob/1ec6ed51182adf8f1b03a3188c16cd8a45ca6c85/tensorflow/python/summary/summary.py#L44-L65)

### Source code / logs
n/a

**Comment by cgorman** [comment]
Sorry for the formalism, I'm sure it's just a li'l mistake :)

**Comment by girving** [comment]
@dandelionmane It does look like `r1.1` has 55dee478b92486b8f3e420950e30998716fadae9 but not 6ef3aaf51a40d0d8a45c8191da13ebf48f1c1671.

**Comment by cgorman** [comment]
Fixed in `r1.2`
