### ISSUE TITLE
iOS: No OpKernel was registered to support Op 'Less' with these attrs.  

### ISSUE THREAD

**Issue by hansonboy** [tensorflow/tensorflow#9476]
hi , all! I have tried to load the model inside iOS that I generated from python.
and right now, I have the following problem:
```
Error adding graph to session:
No OpKernel was registered to support Op 'Less' with these attrs.  
Registered devices: [CPU],     Registered kernels: device='CPU';
 T in [DT_FLOAT]  [[Node: rnn/while/Less = Less[T=DT_INT32](rnn/while/Merge, rnn/while/Less/Enter)]]
```

Here is the python script generating the model:
```
def add_dynamic_rnn_layer(inputs, out_size, batch_size, Xt_size, time_step, num_layer=1, keep_prob=0.5):
    # Reshaping to (batch_size, time_step, Xt_size)
    inputs = tf.reshape(inputs, [-1, time_step, Xt_size])
    cell = tf.contrib.rnn.MultiRNNCell([tf.contrib.rnn.DropoutWrapper(tf.contrib.rnn.LSTMCell(out_size, state_is_tuple=True,forget_bias=1.0),
                                                input_keep_prob=keep_prob)
                             for _ in range(num_layer)])
    cell =  tf.contrib.rnn.DropoutWrapper(cell,  input_keep_prob=keep_prob)
    sequence_length = np.zeros([batch_size], dtype=int)
    sequence_length += time_step
    init_state = cell.zero_state(batch_size, tf.float32)
    rnn_outputs, final_state = tf.nn.dynamic_rnn(cell, inputs, initial_state=init_state, dtype=tf.float32, time_major=False,sequence_length=sequence_length)
    return tf.transpose(rnn_outputs, [1, 0, 2])[-1]


with tf.Session() as sess:
  # ...... other model code....
   add_dynamic_rnn_layer()
   output_graph_def = convert_variables_to_constants(sess, sess.graph_def,
                                                          output_node_names=['predictions', 'prediction_labels'])
   with tf.gfile.FastGFile('inference'+str(time.time())+'.pb', mode='wb') as f:
            f.write(output_graph_def.SerializeToString())
```
Here is the objective-C++ code loading the model and creating the session:
```
{
    NSString *path = [[NSBundle mainBundle] pathForResource:pbname ofType:@"pb"];
    if (!path) return false;
    auto status = ReadBinaryProto(tensorflow::Env::Default(), path.fileSystemRepresentation, &graph);
    if (!status.ok()) {
        NSLog(@"Error reading graph: %s", status.error_message().c_str());
        return NO;
    }
    
    // This prints out the names of the nodes in the graph.
    auto nodeCount = graph.node_size();
    NSLog(@"Node count: %d", nodeCount);
    for (auto i = 0; i < nodeCount; ++i) {
        auto node = graph.node(i);
        NSLog(@"Node %d: %s '%s'", i, node.op().c_str(), node.name().c_str());
    }
    
    tensorflow::SessionOptions options;
    auto status = tensorflow::NewSession(options, &session);
    if (!status.ok()) {
        NSLog(@"Error creating session: %s", status.error_message().c_str());
        return NO;
    }
    
    status = session->Create(graph);
    if (!status.ok()) {
        NSLog(@"Error adding graph to session: %s", status.error_message().c_str());
    }  
}
```
the environment as follows:
 - python 3.5 / xcode 8.3.2
 - the iOS based on mac os x 10.12  / the tensorflow version: r1.1
 - the model generated based on Ubuntu / tensorflow is r1.1 gpu version

I have done things as follow:
- build_all_ios.sh    
  - success,don't have any warning and error.
- set the xcode build settings 
  - header search path
  ```
  /Users/jw/Desktop/tensorflow  non-recursive
  /Users/jw/Desktop/tensorflow/tensorflow/contrib/makefile/downloads non-recursive
  /Users/jw/Desktop/tensorflow/tensorflow/contrib/makefile/downloads/protobuf/src non-recursive
  /Users/jw/Desktop/tensorflow/tensorflow/contrib/makefile/downloads/eigen non-recursive
  /Users/jw/Desktop/tensorflow/tensorflow/contrib/makefile/gen/proto non-recursive
  ```
  -  other linker flags:        
  ```
  /Users/jw/Desktop/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/libprotobuf.a
  /Users/jw/Desktop/tensorflow/tensorflow/contrib/makefile/gen/protobuf_ios/lib/libprotobuf-lite.a
  /Users/jw/Desktop/tensorflow/tensorflow/contrib/makefile/gen/lib/libtensorflow-core.a
  -force_load
  ```
 - check the tf_op_files.txt
   - have the line ` tensorflow/core/kernels/cwise_op_less.cc`
 - using the tensorflow version v1.0 
   - have the same error

I would be gratefull if anyone has an idea on why iOS seems to not be able to find the less Op ?
Or the solution to the question : No OpKernel was registered to support Op 'Less' with these attrs.

**Comment by girving** [comment]
`Less` is only registered for `float32` on iOS, I believe.  @petewarden Do we have some documentation for this that I can point people to?  Ideally, the error message would say what is going on, but I realize that's hard.

**Comment by petewarden** [comment]
I did talk about this area a bit in my dev summit talk:
https://www.youtube.com/watch?v=0r9w3V923rk
I didn't cover the specific area of restricted types though, and in general the documentation here is lacking. There is a comment here that may be helpful:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cwise_ops_common.h#L474
The summary is that you should be able to define `ANDROID_TYPES=__ANDROID_TYPES_FULL__` when you build TensorFlow, and you'll get all types but the binary size will be larger.

**Comment by hansonboy** [comment]
@petewarden , thanks for your comments. 

>  define ANDROID_TYPES=__ANDROID_TYPES_FULL__ when you build TensorFlow 

you mean edit the build_all_ios.sh as the follow?
```
# Build the iOS TensorFlow libraries.
tensorflow/contrib/makefile/compile_ios_tensorflow.sh "-O3" --define ANDROID_TYPES=__ANDROID_TYPES_FULL__ 
```

I am not sure whether I am correct  to add the define in the correct place, look forward to your reply.

**Comment by petewarden** [comment]
The `--define` is Bazel syntax, for the makefile you'll need to use gcc's `-D`. Here's an example that I haven't tried:

```bash
tensorflow/contrib/makefile/compile_ios_tensorflow.sh "-O3 -DANDROID_TYPES=__ANDROID_TYPES_FULL__ "
```

Note that you have to include the `-D` in quotes alongside the `-O3` for it to work.

**Comment by hansonboy** [comment]
thanks for your again. I tried your example. but not worked. Tired...

**Comment by Koshub** [comment]
Have same thing:
> Invalid argument: No OpKernel was registered to support Op 'Less' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; T in [DT_FLOAT]
	 [[Node: GRU-RNN/rnn/while/Less = Less[T=DT_INT32](GRU-RNN/rnn/while/Merge, GRU-RNN/rnn/while/Less/Enter)]]

even after adding `__ANDROID_TYPES_FULL__` option:
```
tensorflow/contrib/makefile/compile_ios_tensorflow.sh "-O3 -DANDROID_TYPES=__ANDROID_TYPES_FULL__ "
```

**Comment by s1ddok** [comment]
@hansonboy so did you find a solution?

**Comment by hansonboy** [comment]
@s1ddok no， I have the problem when I use RNN, but no problem when using CNN. So, I choose to use CNN.

**Comment by StarRain-L** [comment]
@petewarden @s1ddok  Excuse me, I met a similar problem.I follow the above instructions do, but I don't succeed.Below is my screenshot.How to solve?Thank you.
![snip20170615_13](https://user-images.githubusercontent.com/8908244/27177663-aed307a6-51f9-11e7-973e-81a209e7638f.png)

**Comment by JieHe96** [comment]
@s1ddok @petewarden @hansonboy I found a solution for this issue. Try this:
in the (your tensorflow root)/tensorflow/contrib/makefile/Makefile 
remove the line "-D__ANDROID_TYPES_SLIM__ " under "# Settings for iOS." for all "$(IOS_ARCH)"
then recompile the libtensorflow-core.a according to the modified Makefile.

The reason why this happened is because:
in tensorflow/core/kernels/cwise_ops_common.h
#if defined(__ANDROID_TYPES_SLIM__)
// Note that __ANDROID_TYPES_SLIM__ is also checked in the cwise_ops*.cc files.
// Normally Android TensorFlow is built with a reduced number of types (float).
// Override on the command-line "--define ANDROID_TYPES=__ANDROID_TYPES_FULL__"
// to generate a library with full type support with a consequent increase in
// code size.
#define REGISTER2(OP, D, N, F, T0, T1) REGISTER(OP, D, N, F, T0)
#define REGISTER3(OP, D, N, F, T0, T1, T2) REGISTER(OP, D, N, F, T0)
#define REGISTER4(OP, D, N, F, T0, T1, T2, T3) REGISTER(OP, D, N, F, T0)
#define REGISTER5(OP, D, N, F, T0, T1, T2, T3, T4) REGISTER(OP, D, N, F, T0)
#define REGISTER6(OP, D, N, F, T0, T1, T2, T3, T4, T5) REGISTER(OP, D, N, F, T0)
#define REGISTER7(OP, D, N, F, T0, T1, T2, T3, T4, T5, T6) \
  REGISTER(OP, D, N, F, T0)
#define REGISTER8(OP, D, N, F, T0, T1, T2, T3, T4, T5, T6, T7) \
  REGISTER(OP, D, N, F, T0)
#define REGISTER9(OP, D, N, F, T0, T1, T2, T3, T4, T5, T6, T7, T8) \
  REGISTER(OP, D, N, F, T0)
#else  // !defined(__ANDROID_TYPES_SLIM__)

(ps: I also wrote a iOS_SSDMobilenet example base on the python ssd_mobilenet and ios_camera_example, and here is the github link:  @https://github.com/JieHe96/ios_SSDMobilenet_tensorflow_example)

**Comment by bantmensc** [comment]
Is there a better solution than adding all the int ops to the binary? Is it possible to instead swap the int less op with a corresponding float less op + a cast to float?

**Comment by jeffxtang** [comment]
I've been trying to load the model built from the TF Quick Draw tutorial https://www.tensorflow.org/tutorials/recurrent_quickdraw on iOS but got the error "Could not create TensorFlow Graph: Invalid argument: No OpKernel was registered to support Op 'RefSwitch' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='GPU'; T in [DT_FLOAT]
  device='GPU'; T in [DT_INT32]
  device='GPU'; T in [DT_BOOL]
  device='GPU'; T in [DT_STRING]
  device='CPU'; T in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]

	 [[Node: cond/read/Switch = RefSwitch[T=DT_INT64, _class=["loc:@global_step"], _output_shapes=[[], []]](global_step, cond/pred_id)]]"

I then rebuilt the libtensorflow-core.a with ANDROID_TYPES defined as __ANDROID_TYPES_FULL__ and saw the library size almost doubled but still got the same error. I'm using TF 1.5.

Any other ideas on how I may fix the error and load the model? Thanks!

**Comment by NPetsky** [comment]
@Neilcc: don't know if it's still important for you but you can change line 51 in the Makefile 
ANDROID_TYPES := -D__ANDROID_TYPES_SLIM__    to 
ANDROID_TYPES := -D__ANDROID_TYPES_FULL__
and compile again, then it should work

**Comment by andreapavan** [comment]
> @Neilcc: don't know if it's still important for you but you can change line 51 in the Makefile
> ANDROID_TYPES := -D__ANDROID_TYPES_SLIM__ to
> ANDROID_TYPES := -D__ANDROID_TYPES_FULL__
> and compile again, then it should work

The solution proposed by @NPetsky is correct. The build complete successfully and with my Xcode 10.1 can run without errors.
