### ISSUE TITLE
Tensorboard 0.0.0.0:6006 cannot work On Win7 but localhost:6006 works

### ISSUE THREAD

**Issue by pangbochen** [tensorflow/tensorflow#9480]
I use tensorboard on Win7.
Everyting works fine and the cmd shows "Starting TensorBoard b'47' at http://0.0.0.0:6006
"
But when I  input "http://0.0.0.0:6006" into chrome, nothing happens.
I google for it but find limited answer.
Then I input "http://localhost:6006" into chrome, the page comes out.

**Comment by girving** [comment]
Can you give the full output?

**Comment by JAICHANGPARK** [comment]
Now I have same problem.. how to resolve this problem?

**Comment by fengyanghe** [comment]
me too. I use 127.0.0.1:6006 to load logs. It works. 
I use tensorboard --logdir=logs --debug. It prints nothing.
Does it have no authority?
![1](https://cloud.githubusercontent.com/assets/23494598/25580600/e4b9e3ca-2eb4-11e7-9273-6f7a464bbd1c.jpg)
![2](https://cloud.githubusercontent.com/assets/23494598/25580601/e546978e-2eb4-11e7-8ebf-f6b80e2a1937.jpg)
![3](https://cloud.githubusercontent.com/assets/23494598/25580605/e7b2ab48-2eb4-11e7-9818-7c8791dc674b.jpg)

**Comment by zcc973784075** [comment]
Mark! The same question, and i run tensorboard on the cloud and it has to show on my desktop because of the lack of GUI of Cloud!

**Comment by girving** [comment]
@dandelionmane Any ideas?

**Comment by TugbaAtici** [comment]
I have the exact same problem! Does anyone has a solution?

**Comment by dandelionmane** [comment]
Migrating to tensorflow/tensorboard.
