### ISSUE TITLE
return type of `tf.reduce_any`

### ISSUE THREAD

**Issue by linxihui** [tensorflow/tensorflow#9488]
I find that if the input tensor has type `bool`, the output of `tf.reduce_any` has type 'uint8'. My question is, why not `bool`? In the [document](https://www.tensorflow.org/api_docs/python/tf/reduce_any), it says it is equivalent to `np.any`, but the latter return `bool`.

Same applied to  `tf.reduce_all`.

**Comment by Androbin** [comment]
Well, the examples provided suggest, that the output type should be `bool`.
Could you please tell, how you tested for type that said was `uint8`?

**Comment by girving** [comment]
I find that it has type `bool`.  Can you check again?

**Comment by linxihui** [comment]
@Androbin @girving 
My bad. I actually use it through a wrapper in `keras`, and I thought it simply call `reduce_any` but it turns out that it changes the type of the result.

Thanks for replying.

**Comment by girving** [comment]
Cc @fchollet: this does seem a bit surprising.

**Comment by linxihui** [comment]
@girving It is resolved in `keras master`. I was using `keras-1.2`, a version before `2.0`.

**Comment by fchollet** [comment]
For a while Keras did not have a bool type and used int instead, for compatibility with Theano. Now Theano has a bool type so we do too.
