### ISSUE TITLE
Inconsistent results when tf.sqrt() is applied to tensor versus element-wise 

### ISSUE THREAD

**Issue by lipingliulp** [tensorflow/tensorflow#9495]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: fedora 24
- **TensorFlow installed from (source or binary)**: pip
- **Exact command to reproduce**:
```
import tensorflow as tf

import numpy as np

start = 0 
linear_indices = (tf.range(start, 496) + 1) * 8 + 1 
index = 495 - start  

rind  = tf.sqrt(tf.cast(linear_indices, tf.float32)) - 63  
rind1 = tf.gather(rind, index)

linear_index = tf.gather(linear_indices, index)
rind2 = tf.sqrt(tf.cast(linear_index, tf.float32)) - 63  

session = tf.Session()
print(session.run(rind1))
print(session.run(rind2))
```
Output:
```
In [5]: %run calculation_test.py
3.8147e-06
0.0
```
### Describe the problem
The order of operations gives different behavior in tf.gather. `rind1` and `rind2` tensors should have the same value (0).

cc @altosaar

**Comment by aselle** [comment]
I don't see how those two computations are supposed to be the same. rind2 is a tf.sqrt(...) and rind1 is a gather. One is going through more (inexact) floating point arithmetic and one is not. So 3.8147e-6 is almost zero and 0.0 is zero. So they seem the same to me.

**Comment by lipingliulp** [comment]
tf.sqrt(...) is an element-wise operation, so when it is applied to an array, it should be as if it is applied element by element. In this sense, the two result should be exactly the same. 

I am using tf 1.11

**Comment by lipingliulp** [comment]
More finding: it might be the problem of tf.cast. 

I run the following code,
'''
arr = tf.range(0, 496, dtype=tf.int32) 

a32 = tf.sqrt(tf.cast(arr, tf.float32)) 
a64 = tf.sqrt(tf.cast(arr, tf.float64))

diff = tf.reduce_sum(tf.abs(tf.cast(a32, tf.float64) - a64))

session = tf.Session()
print('The difference is %f ' % session.run(diff))
'''
and get 
'''
The difference is 0.000447 
'''
The expected result should be 0. 

I hope this is helpful. 
cc @altosaar

**Comment by lipingliulp** [comment]
New finding: I think the problem is in tf.sqrt(...)
Here is the code, taking sqrt of the array versus taking sqrt element by element, 
```
import tensorflow as tf

arr = tf.range(0, 1000, dtype=tf.float32)

result1 = tf.sqrt(arr)      # taking sqrt of the array


alist = tf.unstack(arr)    # unpack
rlist = []
for elm in alist:              # taking sqrt element by element, 
    rlist.append(tf.sqrt(elm))
result2 = tf.stack(rlist)  # then pack the results into an array 

diff = tf.reduce_sum(tf.abs(result1 - result2))

session = tf.Session()
print('The difference is %f ' % session.run(diff))
```
and the output is, 
```
The difference is 0.001230
```

I expect the output to be 0. 

cc @altosaar

**Comment by aselle** [comment]
Are you running this using a GPU or CPU? If GPU then try on the CPU and see if you get the same behavior. Please report more details about your GPU/system/etc.

**Comment by lipingliulp** [comment]
The result is obtained from a CPU.

**Comment by aselle** [comment]
This test is not meaningful, you are summing errors of numbers that are not of similar magnitude...
```
import tensorflow as tf

arr = tf.range(0, 1000, dtype=tf.float32)

result1 = tf.sqrt(arr)      # taking sqrt of the array


alist = tf.unstack(arr)    # unpack
rlist = []
for elm in alist:              # taking sqrt element by element, 
    rlist.append(tf.sqrt(elm))
result2 = tf.stack(rlist)  # then pack the results into an array 

diff = tf.reduce_max(tf.abs(result1 - result2)/tf.abs(result1))

session = tf.Session()
print('The difference is %f ' % session.run(diff))

```
This computes the max relative error over all elements and I get 0.0000002422335683 i.e. 2e-7 which is about floating point precision. The exact path in the cpu is different for small arrays because large arrays are done with sse for speed.

**Comment by lipingliulp** [comment]
I see. It is interesting that CPU has different behaviors for large arrays and small arrays. 
I'm satisfied with this explanation. Thanks!

cc @altosaar
