### ISSUE TITLE
icc Compilation Errors in tf1.0: usage of "typename" on TTypes

### ISSUE THREAD

**Issue by danielmawhirter** [tensorflow/tensorflow#9496]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.0
- **Bazel version (if compiling from source)**: 0.4.5
- **CUDA/cuDNN version**: not configured
- **GPU model and memory**: not configured
- **Exact command to reproduce**: `CC=icc bazel build -c opt //tensorflow/tools/pip_package:build_pip_package`

When compiling tensorflow using icc (version 17.0.3 20170404) using the command above, errors appear concerning the usage of `typename` associated with `TTypes`. For instance: 

> tensorflow/core/kernels/depthtospace_op.cc(88): error: type name is not allowed
      typename TTypes<T, 4>::ConstTensor Tinput = input.tensor<T, 4>();

A more constrained example, however, makes the problem more apparent. Command:
`CC=icc bazel build -c opt //tensorflow/core/kernels:resize_nearest_neighbor_op`
Output (partial):
> tensorflow/core/kernels/resize_nearest_neighbor_op.cc(57): error: type name is not allowed
      typename TTypes<T, 4>::ConstTensor input_data = input.tensor<T, 4>();

I can change line resize_nearest_neighbor_op.cc(57) to:
`TTypes<T, 4>::ConstTensor input_data = input.tensor<T, 4>();`
and repeat the command to get Output (partial):
> tensorflow/core/kernels/resize_nearest_neighbor_op.cc(57): error: use the "typename" keyword to treat nontype "tensorflow::TTypes<T, NDIMS, IndexType>::ConstTensor [with T=T, NDIMS=4, IndexType=Eigen::DenseIndex={std::ptrdiff_t={long}}]" as a type in a dependent context
      TTypes<T, 4>::ConstTensor input_data = input.tensor<T, 4>();

I do not know if Intel Compiler compatibility is an intended feature of tensorflow, but I hoped this issue would still be of interest to the developers.
Thank you!

**Comment by girving** [comment]
That seems like a bug in icc, given that `ConstTensor` is definitely a type.  However, we'd be happy to accept patches if you know how to fix it.  Removing the typename is not an option since the C++ standard requires it.

**Comment by danielmawhirter** [comment]
I now agree that the change I attempted is incorrect c++. I was confused by "type name" appearing in the error message.
As far as I can tell, the correct version of this line is `typename TTypes<T, 4>::ConstTensor input_data = input.template tensor<T, 4>();`
That compiles under gcc and icc. The versions of this issue that appear in the codebase are `.tensor<...>()`, `->tensor<...>()`, and `.shaped<...>()` Correcting them all with a script allows the original command to complete without errors. I will submit a patch soon.

**Comment by girving** [comment]
If you're planning to submit a patch, let's leave this issue open to track.

**Comment by danielmawhirter** [comment]
I've finished testing and am satisfied that the change as described above, applied globally, yields correct code. I won't be able to submit a patch for a little while due to other priorities, but if anyone is interested, the following script makes the necessary changes when run from the repository's root directory.
```bash
#!/bin/bash

for f in $(find ./tensorflow/ -type f)
do
  perl -pi -e 's/\.tensor</\.template tensor</g' "${f}"
  perl -pi -e 's/->tensor</->template tensor</g' "${f}"
  perl -pi -e 's/\.shaped</\.template shaped</g' "${f}"
done
```

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
