### ISSUE TITLE
No name 'debug' in module 'tensorflow'

### ISSUE THREAD

**Issue by drcrook1** [tensorflow/tensorflow#9499]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Pro
- **TensorFlow installed from (source or binary)**: pip install tensorflow-gpu --upgrade
- **TensorFlow version (use command below)**: 1.0.1
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: Cuda:8, CuDnn:5.1
- **GPU model and memory**: Pascal TitanX (x2)
- **Exact command to reproduce**: 
from tensorflow.python import debug as tf_debug

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

Won't import.  This is the exact import from the docs; I have done nothing fancy; just normal install of everything.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

you can replicate this really easy.

python -c "from tensorflow.python import debug as tf_debug;"

**Comment by girving** [comment]
@caisq: This works for me with 1.0.0 on Mac.  Not sure if this is a Windows issue or a version issue.

**Comment by caisq** [comment]
TFDBG is not functional in 1.0.x on Windows. This is a known issue. It should have been fixed in 1.1.0.
