### ISSUE TITLE
Greedy heuristics may not find the optimal node placement

### ISSUE THREAD

**Issue by futurely** [tensorflow/tensorflow#95]
The nodes have computational costs and the edges have communication costs making the placement problem very similar to finding the [minimum cost flow](https://en.wikipedia.org/wiki/Minimum-cost_flow_problem) of the computation graph. There are very [simple implementations](https://github.com/search?o=desc&q=Min+cost+flow&ref=searchresults&s=forks&type=Repositories&utf8=%E2%9C%93) to get the global optimal solution(s).

**Comment by futurely** [comment]
@iveney, would you like to take a look at the section 3.2.1 of the [TensorFlow whitepaper](http://download.tensorflow.org/paper/whitepaper2015.pdf) [1] and evaluate the applicability?

[1] Martín Abadi, Ashish Agarwal, Paul Barham, Eugene Brevdo,
Zhifeng Chen, Craig Citro, Greg S. Corrado, Andy Davis,
Jeffrey Dean, Matthieu Devin, Sanjay Ghemawat, Ian Goodfellow,
Andrew Harp, Geoffrey Irving, Michael Isard, Rafal Jozefowicz, Yangqing Jia,
Lukasz Kaiser, Manjunath Kudlur, Josh Levenberg, Dan Mané, Mike Schuster,
Rajat Monga, Sherry Moore, Derek Murray, Chris Olah, Jonathon Shlens,
Benoit Steiner, Ilya Sutskever, Kunal Talwar, Paul Tucker,
Vincent Vanhoucke, Vijay Vasudevan, Fernanda Viégas,
Oriol Vinyals, Pete Warden, Martin Wattenberg, Martin Wicke,
Yuan Yu, and Xiaoqiang Zheng.
TensorFlow: Large-scale machine learning on heterogeneous systems,
2015. Software available from tensorflow.org.

**Comment by vrv** [comment]
I believe the problem is a bit more complicated once you introduce memory constraints and scheduling :).  Regardless, this type of question is probably better suited to the [tensorflow discussion mailing list](https://groups.google.com/a/tensorflow.org/forum/#!forum/discuss) rather than a github issue.  

Thanks for your interest!
