### ISSUE TITLE
Tensorflow Video Decoding on a Separate Thread in a Distributed System 

### ISSUE THREAD

**Issue by issa-s-ayoub** [tensorflow/tensorflow#9500]
Having a distributed system, I need to enqueue frames on a CPU device, while processing the frames, that is, training the network, has to be on a GPU device. Could this be performed in parallel?

Currently, tensorflow enables Audio coding through FFMPEG(contrib), are there any features for video encoding and decoding which is multi-threaded?

**Comment by girving** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
