### ISSUE TITLE
Securing Tensorflow models on Android

### ISSUE THREAD

**Issue by thisismohitgupta** [tensorflow/tensorflow#9501]
### Describe the problem
I am using android to deploy my Tensorflow model. I am obfuscating names already but that wont stop people stealing and just plugging and playing graph file in their apps. Feature request for accepting encrypted graph files to prevent our graph files from leaking or any pointers on how to implement it.

**Comment by drpngx** [comment]
@aselle @petewarden @andrewharp 

That's an interesting use case. In general I am not sure that there is no good way to do this as people can always debug your app to find out. You could run part of the network as a service, but that has obvious latency costs.

**Comment by stmkjp** [comment]
How about this?

change input/output node names and then your server dynamically sends those values as well as some other parameters for initializing when the app executed?  don't store those values in the app.

One issue left though, people can still extract those data from the graph file when loaded directly from desktop except the graph file is memory mapped graph, and android can't load memory mapped file (maybe?)

**Comment by petewarden** [comment]
This is a bit out of my domain, but my suggestion would be to use a simple XOR or other obsfucation of the file on disk, and then at runtime load the file into memory, 'decrypt' that memory, and then deserialize the protobuf from RAM. This won't stop a determined malicious actor, but at least complicates the process for them, and at some point there will be an in-memory copy of the graph anyway, whatever you do.

**Comment by girving** [comment]
@petewarden Xor encryption, really?

**Comment by girving** [comment]
Closing as out of scope for TensorFlow.

**Comment by girving** [comment]
I'll give Pete the benefit of the doubt and assume that by xor he meant AES-GCM.
