### ISSUE TITLE
Ops for Reading from Cloud Spanner

### ISSUE THREAD

**Issue by aodhan-domhnaill** [tensorflow/tensorflow#9503]
Is there any plan to make F1 public (be it a service in Google Cloud or just open source) and make it possible to store TensorFlow tensors in F1? I ask because as far as I can tell (might be wrong), there isn't a "native" database for TensorFlow (meaning a C++ reader with direct connection to the DB), and F1 supports Protobuf columns which would seem like a natural fit for Tensorflow data.

From [here](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/41344.pdf)
> The F1 data model is very similar to the Spanner data
> model. In fact, Spanner’s original data model was more like
> Bigtable, but Spanner later adopted F1’s data model. At
> the logical level, F1 has a relational schema similar to that
> of a traditional RDBMS, with some extensions including
> explicit table hierarchy and columns with Protocol Buffer
> data types.

**Comment by drpngx** [comment]
We have a bigquery cloud reader in contrib.

CC @jhseu

**Comment by aidan-plenert-macdonald** [comment]
Any planned support for Spanner? A quick search doesn't show anything

**Comment by drpngx** [comment]
Bigquery supports structs (e.g. json).

**Comment by aidan-plenert-macdonald** [comment]
@tornato7 ^^^ and https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax

**Comment by jhseu** [comment]
I do think ops for reading from Cloud Spanner would be useful. Feel free to reopen if that's what you want.

**Comment by tianzhou** [comment]
The initial sql op support is committed: https://github.com/tensorflow/tensorflow/commit/8dac0eb067662ba69a7eb72e640d8ff8d146e5c9

It's currently a bare minimum supporting sqlite with TEXT type only, but it should be able to serve as a starting point to support other sql engine.

**Comment by mbrukman** [comment]
@aidan-plenert-macdonald — FWIW, we just added [initial read/write support for Cloud Bigtable][tf-bigtable] in [TF 1.10.0][tf-1.10], and you can store protocol buffers in Cloud Bigtable columns — in fact, you can store arbitrary bytes in Cloud Bigtable, since it doesn't enforce a typed schema. Hope this helps!

[tf-bigtable]: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/bigtable
[tf-1.10]: https://github.com/tensorflow/tensorflow/releases/tag/v1.10.0

**Comment by dynamicwebpaige** [comment]
Many ops have been added to [`tensorflow/io`](https://github.com/tensorflow/io/tree/master/tensorflow_io) to support Google Cloud (as well as other cloud platforms!). 

@yongtang, do you know if Spanner has been added?

**Comment by yongtang** [comment]
@aidan-plenert-macdonald @dynamicwebpaige We don't have Cloud Spanner support in tensorflow/io yet (BigQuery/PubSub are already supported), though we could certainly add CloudSpanner as a feature in tensorflow/io.

**Comment by yongtang** [comment]
Opened an issue tensorflow/io#592  for tracking the Cloud Spanner support for tensorflow.
