### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute '_displayhook'

### ISSUE THREAD

**Issue by zxsimple** [tensorflow/tensorflow#9507]
I'm running TensorFlow on Zeppelin with Python 3.5.2, the TensorFlow version is 1.0.1.

It shows up AttributeError: 'Tensor' object has no attribute '_displayhook' error when I was running a Gaussian Distribution.

import tensorflow as tf
import matplotlib.pyplot as plt

n_values = 32
x = tf.linspace(-3.0, 3.0, n_values)

sigma = 1.0
mean = 0.0

a = tf.exp(tf.negative(tf.pow(x - mean, 2.0) / (2.0 * tf.pow(sigma, 2.0)))) 
b = (sigma * tf.sqrt(2.0 * 3.1415))

z = a / b

**Comment by aselle** [comment]
We don't have much experience with Zeppelin so it is tough to support this. Perhaps your problem is your are trying to graph unevaluated Tensors. Try eval or  sess.run() on your tensor before trying to display it, however. i.e. try
```python
import tensorflow as tf
x = tf.linspace(-3.0, 3.0, n_values)
sess=tf.Session()
xevald = sess.run(x)
plt.plot(xevald)

```

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
