### ISSUE TITLE
How do you generate tensorflow docs so you can confirm documentation fixes you make?

### ISSUE THREAD

**Issue by dmonopoly** [tensorflow/tensorflow#9515]
Example: Suppose I see a formatting error in a Tensorflow function's arguments on the web. I then make a change in the "Args: ..." section of the function's python comments.
How can I generate these html docs after making this fix?

**Comment by aselle** [comment]
Try running this script...
https://github.com/petewarden/tensorflow_makefile/blob/master/tensorflow/tools/docs/gen_docs.sh

**Comment by dmonopoly** [comment]
Script seems out of date / didn't work - just made my terminal force close oddly.

Anyway, I did find https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/community/documentation.md though, which looks to be the more official answer.

**Comment by dmonopoly** [comment]
Moving to #1574

**Comment by aselle** [comment]
@dmonopoly, ah sorry for the confusion. Thanks for finding the right answer.
