### ISSUE TITLE
TensorFlow processes and core engine documentations 

### ISSUE THREAD

**Issue by salemmohammed** [tensorflow/tensorflow#9528]
Hi all,

I am interesting to understand more details about TF core engine. My focus interest on how a process create and launch when session is being created. Also, how the threads work and how python api translate these threads to C++ TF engine. Is there any documentation about that ? 

Sincerely

**Comment by aselle** [comment]
I'm afraid that there is little documentation on the internals of TensorFlow. The best way to get started is to read the source code on the parts that you are interested in. It is also unlikely we will have time to extensively document the workings of TensorFlow, as most our documentation effort is aimed at users.

**Comment by girving** [comment]
I'd also recommend reading the published papers on TensorFlow.  E.g., http://download.tensorflow.org/paper/whitepaper2015.pdf.
