### ISSUE TITLE
event_accumulator is missing in v1.1

### ISSUE THREAD

**Issue by ZhengyaoJiang** [tensorflow/tensorflow#9532]
### System information
* TensorFlow version: v1.1

### Describe the problem
Before v1.1, there is a class called EventAccumulater in `python/summary/event_accumulator.py` which is used to export the data from tensorboard. However, in v1.1 this file is missing and the `README.md` is still the old version, saying "If you wish to load TensorFlow events, you should use an EventAccumulator (to load from a single events file) or an EventMultiplexer (to load from multiple events files)".
Is there any alternative API to load the data from tensorboard record files?

**Comment by ZhengyaoJiang** [comment]
Ok. I've found the `event_accumulator.py` in `tensorflow/tensorflow/tensorboard/backend/event_processing/`.
The movement of the file was done in commit 8c1c861ccc488497ad44bb8ec7b1b49ff5ef0a2c.

**Comment by dandelionmane** [comment]
Yeah, the Event Accumulator is part of TensorBoard and was never actually exposed as part of the TensorFlow API (although we have mentioned it in the README). I wouldn't expect it to stay in the TensorFlow codebase indefinitely.
