### ISSUE TITLE
Adding a property `trainable` to `tf.Variable`

### ISSUE THREAD

**Issue by petrux** [tensorflow/tensorflow#9552]
Feature request: wouldn't be handy to have a property `trainable` in the class `tf.Variable`?

P.S. sorry in advance for the question but... am I supposed/entitled to sketch an implementation in my TF fork and then issue a pull request?

**Comment by yaroslavvb** [comment]
TensorFlow tf.Variable objects are not specific to neural networks, so baking "traininable" property in there seems wrong. There's `tf.trainable_variables()` and `tf.add_to_collection(tf.GraphKeys.TRAINABLE_VARIABLES)`

**Comment by petrux** [comment]
Hi @yaroslavvb, thanks for the reply. Yes, it makes sense. I will close the issue (and find a smart way to solve my problem using what is already there).
