### ISSUE TITLE
configure does not work on macOS if sed is GNU sed

### ISSUE THREAD

**Issue by ljos** [tensorflow/tensorflow#9553]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.12.4
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: Current head: 3ce228e

### Describe the problem
If sed is GNU sed on macOS, configure fails with `sed: can't read : No such file or directory`.

**Comment by aselle** [comment]
Can you isolate the command that caused this? How did you switch to GNU sed?

**Comment by martinwicke** [comment]
Is this the same issue as addressed in https://github.com/tensorflow/tensorflow/pull/8935?

**Comment by ljos** [comment]
I installed GNU sed through homebrew and added the sed command on the PATH without the g-prefix. I prefer GNU sed over the BSD sed that macOS comes preinstalled with. 

The command that cause the error:
```
sed_hyphen_i -e 's/WITH_JEMALLOC = True/WITH_JEMALLOC = False/' tensorflow/core/platform/default/build_config.bzl
```

This is because this function only checks if the command is running on macOS and then assumes the sed that it is running is BSD sed.

This is not the same as #8935 because that issue just addresses that most of the time sed on macOS is BSD sed, but doesn't address that sometimes it can also be GNU sed.

**Comment by martinwicke** [comment]
So what in this command is it that GNU sed doesn't like?

**Comment by ljos** [comment]
Or, it is this
```
sed -i '' -e 's/WITH_JEMALLOC = True/WITH_JEMALLOC = False/' tensorflow/core/platform/default/build_config.bzl
```
This stackexhange link explains the problem https://unix.stackexchange.com/questions/92895/how-to-achieve-portability-with-sed-i-in-place-editing

**Comment by martinwicke** [comment]
So it looks like GNU sed and BSD sed's implementation of -i are
fundamentally incompatible?​ Can you remove the space between -i and '' and
check if that works? I have no GNU sed installed.

**Comment by ljos** [comment]
That does seem to work with both GNU and BSD sed.

**Comment by JVillella** [comment]
@ljos Yea, sed isn't very portable - and the `-i` flag isn't even part of the [POSIX spec](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/sed.html). This PR should fix the issue https://github.com/tensorflow/tensorflow/pull/8935 for others.

**Comment by martinwicke** [comment]
@ljos I'm pretty sure that the new version of #8935 should fix the issue for everybody. Can you confirm?

**Comment by ljos** [comment]
The new version works for me. Thanks!
