### ISSUE TITLE
TFRecord Writer Bug Saving Float List

### ISSUE THREAD

**Issue by gdj0nes** [tensorflow/tensorflow#9554]
OS: Linux Ubuntu 14.04
TF: Version 1.1 (CPU) python 2.7

When saving a list of floats to TFRecords format with 
`tf.train.Feature(float_list=tf.train.FloatList(value=value) 
`
,where value it list of floats converted from a numpy array using tolist(), I get the following error:

TypeError: [0.0, 41.95294952392578, 1.4004319906234741, 46.5711784362793, 33.32099914550781, 1.545793056488037, has type list, but expected one of: int, long, float

which surprises me because it is explicitly a list of floats. 

```
def _int64_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))


def _float32_feature(value):
    return tf.train.Feature(float_list=tf.train.FloatList(value=value))

def _bytes_feature(value):
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))
 

    with tf.Session() as sess:
        # initialize variables
        sess.run(init_op)
        # Input threading
        coord = tf.train.Coordinator()
        threads = tf.train.start_queue_runners(coord=coord)

        print('Writing', filename)
        recordWriter = tf.python_io.TFRecordWriter(filename)

        try:
            while not coord.should_stop():

                img, latent = sess.run([img_op, latent_op])

                example = tf.train.Example(features=tf.train.Features(feature={
                    'image/width': _int64_feature(image_dims[0]),
                    'image/height': _int64_feature(image_dims[1]),
                    'image/channels': _int64_feature(image_dims[2]),
                    'image/encoded': _bytes_feature(img[0]),
                    'latent/size': _int64_feature(latent_dim),
                    'latent/data': _float32_feature(latent.tolist())}))
                recordWriter.write(example.SerializeToString())

        except tf.errors.OutOfRangeError:
            print('Done training -- epoch limit reached')

        finally:
            # When done, ask the threads to stop.
            coord.request_stop()

        recordWriter.close()
        coord.join(threads)
        sess.close()
```

**Comment by gdj0nes** [comment]
I think the issue maybe due to using the protobuf version that can be downloaded through tensorflow.

**Comment by tgirgin23** [comment]
OS: Linux Ubuntu 16.04
TF: Version 1.1 (GPU) python 3.3 (Using Docker)

I am having the exact same issue here but with an **Int64List**. I am trying to pass a list ([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]) without any success. I am getting the following error:

> TypeError: [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0] has type list, but expected one of: int, long

**Comment by alicelucas** [comment]
If you want to input a list, your _int64_feature (or _float32_feature) should actually be defined as:
```
def _int64_feature(labels):
    [tf.train.Feature(int64_list=tf.train.Int64List(value=[label])) for label in labels]
```

And that should do the trick!

**Comment by gdj0nes** [comment]
I think this is related to the version of protobuf because I was able to get it to work on a different machine.

**Comment by tgirgin23** [comment]
@gdj0nes What version of protobuf worked for you?

**Comment by gdj0nes** [comment]
Turns out that isn't the issue. I have google.protobuf version 3.2 on both computers.

**Comment by gdj0nes** [comment]
Ok I found the solution to be 
[float(x) for x in array[0]]

**Comment by hanliyao** [comment]
that is a great idea....@gdjOnes

**Comment by SystemErrorWang** [comment]
Have exact the same problem, would like to know what should I do if I was to save a high-dimension array into float list.

**Comment by edubergeek** [comment]
flatten or reshape before writing and after reading reshape back to N dimensions.

**Comment by 100518832** [comment]
Yeah this is not the solution.
```
    @staticmethod
    def _int64_features(value):
        return tf.train.FeatureList(feature=tf.train.Int64List(value=[i for i in value]))
```
Where value is a list of floats, the following error still occurs.
TypeError: Value must be iterable

**Comment by DeepakSridhar** [comment]
Don't use a list. 

def _float32_feature(value):
  return tf.train.Feature(float_list = tf.train.FloatList(value=value))

**Comment by MrRace** [comment]
Same problem~~my `token_ids`=`[[3842, 11658], [3080, 3541], [1557, 6895], [6913, 6802], [11407, 10301, 10301]]`,  when I  write it like that: `feature["question_token_ids"] = tf.train.Feature(int64_list=                                                             tf.train.Int64List(value=token_ids))`.  The error comes:`TypeError: [3842, 11658] has type list, but expected one of: int, long`。How to solve this problem?

**Comment by MrRace** [comment]
> OS: Linux Ubuntu 16.04
> TF: Version 1.1 (GPU) python 3.6 (Using Docker)
> 
> I am having the exact same issue here but with an **Int64List**. I am trying to pass a list [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0] without any success. I am getting the following error:
> 
> > TypeError: [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0] has type list, but expected one of: int, long

Hi, what is your finally  solution?
