### ISSUE TITLE
Wrong path for absolute variable scopes

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorflow#9557]
Using absolute paths for scopes is useful when structuring large models.

We can enter a name scope from its absolute path by appending a slash:

```python
with tf.name_scope('foo'):
  with tf.name_scope('bar/') as scope:
    print(tf.constant(0).name)  # bar/Const:0
    print(bar)  # bar
```

However, this does not work with variable scopes:

```python
with tf.variable_scope('foo'):
  with tf.variable_scope('bar/') as bar:
    print(tf.constant(0).name)  # bar/Const:0
    print(bar.name)  # foo/bar/ (Expected: bar)
```

The last line should print `bar` instead of `foo/bar/`.

**Comment by aselle** [comment]
@mrry, i'm not a scope expert, but it seems in `ops.py` there is `name_from_scope_name` that 
checks for a trailing slash i.e. at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L1883

but and I don't see any similar function for variable_scope. Perhaps this is intended for some good reason?

**Comment by mrry** [comment]
If there's a good reason, @lukaszkaiser would be the one who knows it.

**Comment by lukaszkaiser** [comment]
It was a hack in name scopes, and it was left out of variable scopes on purpose. We managed to go without hacking-in absolute paths for a long time, and their lack has great advantages: it's much harder to make a model inaccessible as sub-model. If you use an absolute path, then your model immediately becomes unusable as a sub-model of anything. So it was a conscious decision and it looks like the right one for now - a little inconvenience at build time paid for by much easier maintenance. I'd advocate to keep it that way except if there is a very good reason not to.
