### ISSUE TITLE
no such package 'tensorflow/examples/image_retraining': BUILD file not found on package path.

### ISSUE THREAD

**Issue by stat-lz** [tensorflow/tensorflow#9559]
### Describe the problem
I use ubuntu, and install anaconda3 and tensorflow followed the instruction. After it, I am trying to learn how to retrain a model that follows the inception tutorial. It seems that I got the following errors

ERROR: no such package 'tensorflow/examples/image_retraining': BUILD file not found on package path.

Is there a way to solve this issue?

### Source code / logs

parallels@ubuntu:~/anaconda3/lib/python3.6/site-packages$ bazel build tensorflow/examples/image_retraining:retrain
ERROR: no such package 'tensorflow/examples/image_retraining': BUILD file not found on package path.
INFO: Elapsed time: 0.073s

**Comment by MarkDaoust** [comment]
Hi, 

From the path, /anaconda3/lib/python3.6/site-packages, it looks like you're trying to launch that `bazel build` from the tensorflow pip-installation. 

(Almost) none of the examples, and none of the BUILD files are included in the pip installation.

For that bazel command to work you need to launch it from a git clone of the tensorflow repository. That should work.

Good luck.
