### ISSUE TITLE
No module named tensorflow (problem with python 2)

### ISSUE THREAD

**Issue by hadi-ghnd** [tensorflow/tensorflow#9564]
Hi,
 I'm trying to install tensorflow on this machine:

Ubuntu 16.04
cuda 8.0
cudnn 5.1
python 2.7 (no Anaconda)

I installed tensorflow on both python 3 and python 2. It works with python 3 but with python 2 always gives the import error: **No module named tensorflow**. 
What can I do to solve this?

Thanks

**Comment by aselle** [comment]
A few things
 * Could you show the exact commands you are running and their traceback?  Include the install and the check import? 
  * Are you using pip? Did you check the `pip list`. Did you check that the pip you are running corresponds to the python you are running.?
  * Try virtualenv.
  * Try what is listed here https://www.tensorflow.org/install/install_linux (under common install problems)

**Comment by viettan28** [comment]
Same problem as mine:
The pip and python does not correspond to each other.
Using "python -m pip installl tensorflow" for sure pip.

**Comment by hadi-ghnd** [comment]
These are the commands I used to install tensorflow with python 2:

` sudo apt-get install python-virtualenv`
` virtualenv --system-site-packages /media/hadi/tmpstore/tensorflow_vp2/`
`source /media/hadi/tmpstore/tensorflow_vp2/bin/activate`
`pip install --upgrade tensorflow-gpu`
`deactivate`
``source /media/hadi/tmpstore/tensorflow_vp2/bin/activate`
`pip install ipython`

Now I am trying to perform faster-RCNN for object detection based on github pages. But every time there is this error with python 2:

> import tensorflow as tf

> ImportError: No module named tensorflow

In the `pip list` there is line like this:

> tensorflow-gpu (1.0.1)

**Comment by hadi-ghnd** [comment]
My problem was with `pip`. It always referred to python 3.I used `pip2 install --upgrade tensorflow-gpu` instead and it works now.

**Comment by aselle** [comment]
Glad you got it working!

**Comment by Deepakchawla** [comment]
I am also getting the same error while importing tensor-flow below are some details of my system.

`deepakchawla35@deepak-server:~$ python -V
Python 3.6.1 :: Anaconda 4.4.0 (64-bit)`

`deepakchawla35@deepak-server:~$ pip -V
pip 9.0.1 from /home/deepakchawla35/anaconda3/lib/python3.6/site-packages (python 3.6)`
 
`deepakchawla35@deepak-server:~$ pip3 show tensorflow
Name: tensorflow
Version: 1.3.0
Summary: TensorFlow helps the tensors flow
Home-page: http://tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /home/deepakchawla35/.local/lib/python3.5/site-packages
Requires: protobuf, six, tensorflow-tensorboard, wheel, numpy`

`deepakchawla35@deepak-server:~$ python
Python 3.6.1 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'`

In my system python and pip are of version 3.6 and tensorflow is install with python version 3.5 now what should I have to do to install it with python 3.6..??

**Comment by jvdsidq** [comment]
How can I install Keras after installing theano? I tried to install keras but after complitation when I am trying to import keras it shows me error: No module name tensorflow.
I also changed the default backend from tensorflow to theano but still I am facing the same problem. Could you people please help me to fix it.

**Comment by jvdsidq** [comment]
How can I install Keras after installing theano? I tried to install keras but after complitation when I am trying to import keras it shows me error: No module name tensorflow.
I also changed the default backend from tensorflow to theano but still I am facing the same problem. Could you people please help me to fix it.
