### ISSUE TITLE
model_dir deletion while running python script

### ISSUE THREAD

**Issue by MMCMA** [tensorflow/tensorflow#9571]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Win10
- **TensorFlow installed from (source or binary)**:  binary, installed via pip
- **TensorFlow version (use command below)**: 1.1.0
- **Bazel version (if compiling from source)**:na
- **CUDA/cuDNN version**: na
- **GPU model and memory**: na
- **Exact command to reproduce**:?

### Describe the problem
Feature request: As part of an hyperparameter optimization routine, I use tensorflow's high level api tf.contrib.learn.DNNRegressor() (should apply to the others as well). The problem is that it creates for each instance an own new model_dir, which I can't delete during running the python script (even after the model instance is overwritten and no longer in RAM). It is a problem because it consumes rather fast large amounts of disk storage. As far as I can see there is no way to delete the temp dir while running the program, only once it terminates the dir is released and removable. 

### Source code / logs
here is a pseudo code example:
https://stackoverflow.com/questions/43639516/model-dir-deletion-in-tensorflow

**Comment by aselle** [comment]
Is this something desired @martinwicke? It seems to me this might be desirable because after you are done w/ your parameter search, you probably want the trained model and not to have to redo it again?

**Comment by martinwicke** [comment]
This sounds like a problem we recently had in a unit test on Windows. The solution was to close file handles in a summary writer cache that were still open. You can see the solution here:
https://github.com/tensorflow/tensorflow/pull/9281/files

Can you verify that calling `FileWriterCache.clear()` before trying to remove the directory works? Try it at head -- #9185 will probably have to be in your code for this to work properly.

We considered doing this automatically after each `Estimator.train()` run -- but that seemed too much long term interference. However, it would make a lot of sense to do it in `Experiment.train_and_evaluate` and similar methods.

**Comment by MMCMA** [comment]
I managed to delete after using `FileWriterCache.clear()`. Thanks and sorry for the late reply.

**Comment by wt-huang** [comment]
Closing as this is resolved
