### ISSUE TITLE
cuda_error_out_of_memory when trying to run tensorflow/tensorflow/examples/tutorials/layers/cnn_mnist.py

### ISSUE THREAD

**Issue by ac-lap** [tensorflow/tensorflow#9572]
When I run tensorflow/tensorflow/examples/tutorials/layers/cnn_mnist.py on GPU I get the cuda_error_out_of_memory. 

I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0:   Y
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 970M, pci bus id: 0000:01:00.0)
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_driver.cc:1002] failed to allocate 3.00G (3221225472 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_driver.cc:1002] failed to allocate 2.70G (2899102720 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_dnn.cc:397] could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_dnn.cc:404] error retrieving driver version: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_dnn.cc:364] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\kernels\conv_ops.cc:605] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms)

To circumvent it, I thought of using `config.gpu_options.per_process_gpu_memory_fraction` or `config.gpu_options.allow_growth`, but I don't know where to set the session configuration as I don't see any sessions in the code. Also, is there any way I can set session configuration globally for one file?

**Comment by aselle** [comment]
What version of cuda and cudnn?
What version of TensorFlow? From Source?
@mrry, any ideas? It looks like the version reading code is linux/macos specific (reading proc).

**Comment by mrry** [comment]
The most likely explanation is that there isn't enough memory. There is usually a log message that includes the amount of free memory on the device, which I believe is [printed before](https://github.com/tensorflow/tensorflow/blob/3ce228e46befca3a89441c7973a571108d2edf2f/tensorflow/core/common_runtime/gpu/gpu_device.cc#L900) the log messages that appear in the issue report. (The failure to read the version is benign, since we just use it to print a more descriptive error on Linux and Mac OS X.)

**Comment by ac-lap** [comment]
Cuda - v8.0.60
cudnn - 5.1 for cuda 8.0
TensorFow - 1.0.1
Installed TensorFlow using pip
OS - Windows 10, 64 bit

Can you suggest me some workaround for now.

**Comment by andydavis1** [comment]
Please re-open if you can reproduce on a GPU with enough memory.
