### ISSUE TITLE
Generating whl for linux

### ISSUE THREAD

**Issue by skorpio11** [tensorflow/tensorflow#958]
Hi all,
I am trying to compile tensorflow for ubuntu 14.04 by following instruction at https://www.tensorflow.org/versions/master/get_started/os_setup.html#create-pip.

Made it as far as:
bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
 with correct output.  The instructions seems to stop there without any indication of how to generate whl for pip and further how to install with pip.  Any pointers will be appreciated.

Thanks
LEon

**Comment by junluan** [comment]
Create the pip package and install

When building from source, you will still build a pip package and install that.

$ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package

# To build with GPU support:
$ bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

# The name of the .whl file will depend on your platform.
$ pip install /tmp/tensorflow_pkg/tensorflow-0.6.0-cp27-none-linux_x86_64.whl

**Comment by skorpio11** [comment]
Thanks for response junluan. Did the first build command and got an error:

 C++ compilation of rule '//tensorflow/python:_pywrap_tensorflow.so' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command third_party/gpus/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object ... (remaining 90 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by vrv** [comment]
We would need to see the output when run with --verbose_failures to know what's going wrong.

**Comment by vrv** [comment]
(Closing issue to help triage more active bugs.  Feel free to comment again and we'll reopen).
