### ISSUE TITLE
Feature Request: SparseTensor operation

### ISSUE THREAD

**Issue by antronshao001** [tensorflow/tensorflow#9588]
Hi, 
I am recently using SparseTensor. However, I found that there are a lot of math operations not supported for SparseTensor. For example, mod , floor, and argmin, etc. Do you have plans for extending the math operations of SparseTensor. 

Thanks,
Anthony

**Comment by ebrevdo** [comment]
It's not currently a high priority, I think we may end up creating a
different object that's optimized for math operations.  In the meantime,
PRs that extent sparsetensor functionality are welcome.

**Comment by antronshao001** [comment]
Got it. Luckily I had find some ways to bypass my problem currently. Thanks for your quick response.

**Comment by girving** [comment]
This is too broad, so I'm going to close.  More specific sparse tensor ops should be filed as separate issues (or submitted as PRs).
