### ISSUE TITLE
Several links error in README.md.

### ISSUE THREAD

**Issue by spartucus** [tensorflow/tensorflow#9591]
### System information
- **OS: Windows 10 Enterprise x64**:
- **Browser: Chrome 58 x64**:
- **Location: China**:

### Issue
The [Installing TensorFlow](https://www.tensorflow.org/install/) link from [README.md](https://github.com/tensorflow/tensorflow) fails with error:
```
Error: Not Found

The requested URL /versions/r0.12/install/index.html was not found on this server.
```

The [Community](https://www.tensorflow.org/community/) link fails with error:
```
Error: Not Found

The requested URL /versions/r0.12/community/index.html was not found on this server.
```

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Please also include more information on what commands you ran to produce the output. Thanks!

**Comment by spartucus** [comment]
@skye Thanks for reply. I know it's not a product bug, but it's a doc bug. The README.md doc has several invalid site links, i don't think this should be asked in StackOverflow.

**Comment by skye** [comment]
Ah sorry, didn't read the issue closely enough!

**Comment by skye** [comment]
Hm, the "Installing Tensorflow" link at https://github.com/tensorflow/tensorflow goes to https://www.tensorflow.org/install/, and the "Community" link goes to https://www.tensorflow.org/community/. Am I missing something?

**Comment by spartucus** [comment]
Yes, you are right. But the two links redirect to invalid sites with a "404 Not Found" result.
https://www.tensorflow.org/install/ redirects to 
[https://www.tensorflow.org/versions/r0.12/install/index.html](https://www.tensorflow.org/versions/r0.12/install/index.html)

and https://www.tensorflow.org/community/ redirects to [https://www.tensorflow.org/versions/r0.12/community/index.html](https://www.tensorflow.org/versions/r0.12/community/index.html)

btw: I'm in China, hope this helps.

**Comment by skye** [comment]
@dr4b does this ring any bells for you? (See the above comment.) Those links don't redirect for me, but I'm not sure if being in China should affect this.

**Comment by skye** [comment]
It seems like you might be accessing an old version of the site somehow. I'll ping our infrastructure team to see if they can look into this. In the meantime, if you have access to the github, you can look at the docs source directly:

Installation page: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/install/index.md
Community page: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/community/index.md

All the non-API pages should be in that docs_src directory, and the documentation for individual API methods, classes, etc. is generated from the docstrings in the source files. Let me know if you need help finding something.

**Comment by spartucus** [comment]
@skye Thanks.
