### ISSUE TITLE
libtensorflow.so: undefined reference to `__cpu_model'

### ISSUE THREAD

**Issue by smistad** [tensorflow/tensorflow#9593]
When linking with the tensorflow C++ library, the following error occurs: libtensorflow.so: undefined reference to `__cpu_model'

Seems to be related to issue #7223

I manage to work around this error with: ( as done by https://github.com/tensorflow/tensorflow/pull/7241/commits/d7955a66088567ade60213448bbab861de9055cd)
`#ifndef USE_SSE_CRC32C`
in the file tensorflow/core/lib/hash/crc32c_accelerate.cc

Doing this removed the error.

System information:
Ubuntu 16.04 64 bit
Intel i5 CPU
NVIDIA GTX 980 GPU
Built using CMake with BUILD_SHARED_LIB enabled which creates the libtensorflow.so file

**Comment by skye** [comment]
This does seem to be the same problem as #7223. Can you post what compiler you're using to build TensorFlow? I wonder if we need to expand the check in https://github.com/tensorflow/tensorflow/pull/7241/commits/d7955a66088567ade60213448bbab861de9055cd.

**Comment by smistad** [comment]
The compiler used is gcc 5.4:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by skye** [comment]
Looks like gcc 5 has a similar bug to the one referenced in #7223: https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1568899

According to the bug report, a workaround is to "add -lgcc_s -lgcc at the end of the g++ command that links the shared library".

@smistad do you think you could wade into the CMake build and try the workaround? (Even if you don't plumb it all the way through maybe you can at least confirm it works by printing and manually modifying the compiler commands.)

**Comment by smistad** [comment]
Sure, I will try it and if it works I can add an "if GCC version 5" in cmake, add the libraries mentioned to the linker and create a pull request for it.

**Comment by HFTrader** [comment]
I am using clang 4.0.0 and also having the same problem. However as the compiler is not GCC then the line with target_link_libraries() is not activated. Commenting out the IF() block solves the problem.
