### ISSUE TITLE
couldn't find libtensorflow_demo.so

### ISSUE THREAD

**Issue by rmaelongakit** [tensorflow/tensorflow#9599]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader
I tried to integrate the tensorflow android sample to my existing project but the TensorFlowClassifier cannot execute since libtensorflow_demo.so is not loaded. What should I do?

**Comment by andrewharp** [comment]
You'll need to build it too; it's defined in tensorflow/examples/android/BUILD. Alternatively you can download the pre-built .so files [here](https://ci.tensorflow.org/view/Nightly/job/nightly-android/).

**Comment by rmaelongakit** [comment]
thank you for this answer..
I already have a libtensorflow_demo.so file placed in my jnilibs, but yet, it can't be found.
this is the error java.lang.UnsatisfiedLinkError: No implementation found for int ph.com.spamast.mliapp.TensorFlowClassifier.initializeTensorFlow()...

I will try now the files you refer.. thanks again!

**Comment by andrewharp** [comment]
What is the content of your APK? You can see this with e.g. `unzip -v tensorflow_demo.apk`

Note that you need all the .so files present at the highest architecture level any of them are present at. So if you have one added to your apk in libs/arm64-v8a, all of the others used need to be in that directory as well.

**Comment by rmaelongakit** [comment]
Already added the files libandroid_tensorflow_lib.lo, libpthread.so, libtensorflow_demo.so, and libtensorflow_inference.so to jniLibs, yet, still have the same error.

At the moment, still decompiling tensorflow_demo.apk to check its contents.

thank you @andrewharp

**Comment by rmaelongakit** [comment]
I have tried to configure JNI. I created native classes, Application.mk, Android.mk, and imported several C++ files.. Seems like I got lost & now I have this error.

Error:error: 'errno' was not declared in this scope
Error:error: 'EINTR' was not declared in this scope
Error:Execution failed for task ':app:ndkBuild'.
> Process 'command 'C:/Users/user/AppData/Local/Android/sdk/ndk-bundle/ndk-build.cmd'' finished with non-zero exit value 2

Also modified the build.gradle with this:
 task ndkBuild(type: Exec, description: 'Compile JNI source via NDK'){
  commandLine "C:/Users/user/AppData/Local/Android/sdk/ndk-bundle/ndk-build.cmd",
             'NDK_PROJECT_PATH=build/intermediates/ndk',
             'NDK_LIBS_OUT=src/main/jniLibs',
            'APP_BUILD_SCRIPT=src/main/jni/Android.mk',
            'NDK_APPLICATION_MK=src/main/jni/Application.mk',
            '-j1'
}
    tasks.withType(JavaCompile){
        compileTask -> compileTask.dependsOn ndkBuild

    }

Sorry, newbie to android here.

**Comment by andrewharp** [comment]
What is the content of your APK?

We don't use Android/application.mk to build TF, so I would not suggest going down this path.

What OS are you developing on? You should be placing the libs in the "libs/<target>" folders.

Also what version of TF are you using? There are currently no native methods in TensorFlowImageClassifier, so I don't see how this could be native libraries related with any recent release. And if you're changing package names you're really outside the scope of TF support.

**Comment by rmaelongakit** [comment]
issue solved..

Your answer at the top is correct.

> Note that you need all the .so files present at the highest architecture level any of them are present at. So if you have one added to your apk in libs/arm64-v8a, all of the others used need to be in that directory as well.

>

**Comment by rmaelongakit** [comment]
Thank you.. @andrewharp
