### ISSUE TITLE
tensorflow-0.5.0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by leerduo** [tensorflow/tensorflow#96]
Hello,I got the error when i  execute:"pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.5.0-cp27-none-linux_x86_64.whl"--------[ tensorflow-0.5.0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.].

**Comment by ebrevdo** [comment]
Can you provide more information about your machine, version of python, etc?

**Comment by vrv** [comment]
The output of the following would be helpful:

```bash
uname -a
```

Our built pip packages are only for 64-bit platforms: I suspect you're either on a 32-bit platform or you're trying to install the linux package on a non-linux machine.

**Comment by leerduo** [comment]
Thanks,i try to install the linux package on a 32-bit platform,so i falled.  @vrv

**Comment by siwonadaddy** [comment]
I also have the same issue.
This is the output of the uname -a
haejongs@sclasic02:~/Downloads$ uname -a
Linux sclasic02 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:18:00 UTC 2015 i686 i686 i686 GNU/Linux

**Comment by leerduo** [comment]
I have upgraded my system,here is the log when i  execute:  `uname -a`  
  [Linux chenfuduo 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux],and this solve the problem.  @siwonadaddy

**Comment by sumitbinnani** [comment]
Hi @vrv,

I guess it would be helpful to mention in the documentation about the 64-bit dependency of the built package. I almost spent an hour trying to debug the issue. Also, is the installation from binary supported on 32-bit machine?

**Comment by ebrevdo** [comment]
As far as I can tell, we do not support 32-bit machines at all.

**Comment by vrv** [comment]
I updated the docs to mention Linux 64-bit -- updated in git repo and website should be updated today.

**Comment by sumitbinnani** [comment]
Thanks @ebrevdo and @vrv :-)

**Comment by hungdn** [comment]
I still got this problem when install on my Kali box (4.0.0-kali1-amd64) with this below version
pip install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl
I tried many times but failed, then I have to go with Virtualenv. I don't know it's because TensorFlow doesn't support Kali or not, and I don't have chance to test with Ubuntu. But I don't think that if TensorFlow supports Ubuntu then not with Kali. :)

**Comment by pannous** [comment]
similar issue solved here by renaming
```
mv tensorflow-0.7.0-py2-none-linux_x86_64.whl tensorflow-0.7.0-cp27-none-linux_x86_64.whl or 
mv tensorflow-0.7.0-py2-none-linux_x86_64.whl tensorflow-0.7.0-py2-none-any.whl
sudo pip2 install --upgrade tensorflow-0.7.0-cp27-none-linux_x86_64.whl
```
