### ISSUE TITLE
bug in tf_session.i came from commit:8a59748

### ISSUE THREAD

**Issue by blueegg** [tensorflow/tensorflow#960]
line 211:
    $result = PyString_FromStringAndSize(*$2, strlen(*$2));
To:
%#if PY_MAJOR_VERSION < 3
    $result = PyString_FromStringAndSize(
%#else
    $result = PyUnicode_FromStringAndSize(
%#endif
        *$2, strlen(*$2));

**Comment by vrv** [comment]
We fixed this just recently in https://github.com/tensorflow/tensorflow/commit/5ff6d34a05b2eb49f7a79a4d0b78ada9a6842b6c
