### ISSUE TITLE
Broken link Mac/GPU/py3 whl file

### ISSUE THREAD

**Issue by kinergy** [tensorflow/tensorflow#9610]
On page: 
[https://www.tensorflow.org/install/install_mac#the_url_of_the_tensorflow_python_package](https://www.tensorflow.org/install/install_mac#the_url_of_the_tensorflow_python_package)

This link is broken:
[https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow_gpu-1.1.0-py3-none-any.whl](https://storage.googleapis.com/tensorflow/mac/gpu/tensorflow_gpu-1.1.0-py3-none-any.whl)

**Comment by crowston** [comment]
Same problem.

**Comment by jnordberg** [comment]
Anyone know a mirror?

**Comment by av8ramit** [comment]
Fixed. Thanks for pointing this out @kinergy !
