### ISSUE TITLE
feed input node (which is a sentence) using Tensor Flow Inference Interface

### ISSUE THREAD

**Issue by saria85** [tensorflow/tensorflow#9619]
hi all,

unfortunately there is little stuff when we are going to link the tensorflow model to android
this is the thing I am doing
I freezed and optimized tensorflow model
It is a RNN lstm model , getting a sentence then saying if that positive or negative
I successfully added all the things in android studio
Now I have a editbox to enter my sentence , then touch Run button, then this run button should fill the label if this sentence was positive or negative,

but dont know how to feed input node when that is sentence, 
even didnt find any document to do so,

hope someone kindly help me

I did  something like this but is incorrect
`protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    inferenceInterface = new TensorFlowInferenceInterface();
    inferenceInterface.initializeTensorFlow(getAssets(), MODEL_FILE);

    final Button button = (Button) findViewById(R.id.button);

    button.setOnClickListener(new View.OnClickListener() {
        public void onClick(View v) {

            final EditText editNum1 = (EditText) findViewById(R.id.editNum1);

            inferenceInterface.fillNodeInt(INPUT_NODE, INPUT_SIZE, editNum1);

            inferenceInterface.runInference(new String[] {OUTPUT_NODE});

            int[] resu = {0, 0};
            inferenceInterface.readNodeInt(OUTPUT_NODE, resu);

            final TextView textViewR = (TextView) findViewById(R.id.txtViewResult);
            textViewR.setText(Float.toString(resu[0]) + ", " + Float.toString(resu[1]));
        }
    });

}`
the problem is I couldnt find any method in TensorFlowInferenceInterface that gives the string as input they were int or float or byte

appreciate you help

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by saria85** [comment]
It does not make sense when there is no documentation for something limiting us to tell it in one community.

anyway I had already send in stackover

https://stackoverflow.com/questions/43752756/how-to-feed-input-node-which-is-a-sentence-in-android-studio-using-tensorflowi

no one answered, In this case what should I do?
please let me know

**Comment by dung38tn** [comment]
There are a little differences in using android interface API between tensorflow version.
If you go with old version (build num. 44 on Feb. 17, 2017) the code for feeding, running will be exactly as you did
But you have new version (build num 164 on June 15, 2017) the code should be like this:
Refer this video for comprehensive info.
https://www.youtube.com/watch?v=SSGp06uFhhU&t=25s
https://www.youtube.com/watch?v=_gVn0vpkHYg&t=25s

btnProcess.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                float[] outputs = new float[2];
                String str;
                float[] pixels = getPixelData(bitmap);
                // feed
                inferenceInterface.feed(INPUT_NODE, pixels, 1, IMAGE_SIZE, IMAGE_SIZE, 3);
                //run
                inferenceInterface.run(new String[] {OUTPUT_NODE});
                // fetch
                inferenceInterface.fetch(OUTPUT_NODE, outputs);
                if (outputs[0] > outputs[1])
                    str = "fake";
                else
                    str = "live";
                String str1 = "fake: " + Float.toString(outputs[0]*100) + "  live: " + Float.toString(outputs[1]*100);
                result1.setTextColor(Color.BLUE);
                result2.setTextColor(Color.BLUE);
                result1.setText(str1);
                result2.setText("This is " + str + " fingerprint.");
            }
        });

**Comment by Nothing9x** [comment]
Did you find the solution for this problem? I have a same problem but I can't find any solution

**Comment by longdt219** [comment]
I'm having the same problem as well.

**Comment by longdt219** [comment]
This works for me to feed the string using inferenceInterface.feedString with the string converted to byte array. If the output is String as well, it can be fetched through ByteBuffer and converted to String afterwards.

**Comment by azainab** [comment]
@Nothing9x @longdt219 @saria85 

It worked for me:
import android.content.res.AssetManager;
import org.tensorflow.contrib.android.TensorFlowInferenceInterface;
private AssetManager assetManager;
private TensorFlowInferenceInterface inferenceInterface;
private static final String MODEL_FILE = "**name of the pb file along with extension**"
inferenceInterface = new TensorFlowInferenceInterface(getAssets(), MODEL_FILE);

After this you can use the feed run and fetch commands:

inferenceInterface.feed(.....)
inferenceInterface.run(.....)
inferenceInterface.fetch(........)
