### ISSUE TITLE
Uninstall Bazel

### ISSUE THREAD

**Issue by Jacobh2** [tensorflow/tensorflow#962]
Hi!

I ran into an error while running code very similar to the [RNN tutorial](https://www.tensorflow.org/versions/0.6.0/tutorials/recurrent/index.html). 

I believe the issue was the exact [problem](https://github.com/tensorflow/tensorflow/issues/481) that was apparently fixed now. So I wanted to uninstall my version of Tensorflow and install it from source code in order to get the latest updates.

But (!) after installing Bazel and downloading the tensorflow repo, I ran into an error while compiling. A file, "transpose_op_gpu.cu.d" was said to be missing and the compilation could not continue. Strange.

So then I wanted to install tensorflow again "normally" using pip. That seems to have worked, but when I try to import tensorflow in python it just says 

```
Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
```

So my question is: How do I **uninstall** Bazel!?

**Comment by gaohuazuo** [comment]
You should run python interpreter from a directory that is not a tensorflow repo root.

**Comment by Jacobh2** [comment]
Yes, I run it from my project directory.

I got this answer from Bazel to uninstall it:
`rm -fr ~/.bazel ~/.bazelrc`
