### ISSUE TITLE
How can I load data from a data file just like http://projector.tensorflow.org/ does when using Tensorboard embedding projector

### ISSUE THREAD

**Issue by qwertymj** [tensorflow/tensorflow#9621]
At http://projector.tensorflow.org/  we can choose a data file from our own computer by the `Load data` button(see the red rectangle below) and visualize the high-dimensional data
![image](https://cloud.githubusercontent.com/assets/7208819/25652477/fbc9675e-301a-11e7-931f-c7bb22fbdea2.png)
![image](https://cloud.githubusercontent.com/assets/7208819/25652234/ce6c2158-3019-11e7-9c10-47fe2a1e2224.png)

But when I tried to using Tensorboard embedding on my own computer (follow the instruction at https://www.tensorflow.org/get_started/embedding_viz and start a server on localhost:6006 by command `tensorboard --logdir=LOG_DIR` )
I just find the `Load data` button doesn't exist (see below)

![image](https://cloud.githubusercontent.com/assets/7208819/25652904/0f4ff566-301d-11e7-9a1e-4d097d108349.png)

So I want to ask when I run Tensorboard on localhost, how can I enable the load data button like http://projector.tensorflow.org/ does, thus I can visualize the high-dimensional data by uploading my file rather than writing code ?

thanks a lot :)

**Comment by skye** [comment]
@dandelionmane @jart can one of you comment?

**Comment by dandelionmane** [comment]
I'm going to mark this as a feature request and contributions welcome, and pingign @dsmilkov in case he wants to comment.

**Comment by qwertymj** [comment]
ok, thx anyway :)

**Comment by qwertymj** [comment]
Today I found this:
https://github.com/tensorflow/tensorflow/commit/8c8ac705ec4cbae71b56fa37990e26890b576a77?diff=split

from 
tensorflow/tensorboard/components/vz_projector/vz-projector-data-panel.html
<pre><code>#demo-data-buttons-container {
display: none;
}
</code></pre>
and 
tensorflow/tensorboard/components/vz_projector/vz-projector-data-panel.ts
<pre><code> if (this.projector.servingMode === 'demo') {
       (this.$$('#demo-data-buttons-container') as HTMLElement).style.display = 'block';
       // Fill out the projector config.
      ...
</code></pre>
we can know only when the `projector.servingMode` is 'demo', the upload button can be displayed
but I don't know how to set the `projector.servingMode` into 'demo' mode

so I just modified 
<pre><code>#demo-data-buttons-container {
display: none;
}
</code></pre>
into
<pre><code>#demo-data-buttons-container {
display: block;
}
</code></pre>
and it works!
![image](https://cloud.githubusercontent.com/assets/7208819/25985450/21f74366-371d-11e7-8e4e-25b8c0459478.png)

However, can anyone tell me how to set the `projector.servingMode` into 'demo' mode?

**Comment by jart** [comment]
This issue has been migrated to https://github.com/tensorflow/tensorboard/issues/94.
