### ISSUE TITLE
What is the best way to test speed of TF

### ISSUE THREAD

**Issue by AnlanSun** [tensorflow/tensorflow#9623]
I am trying to test the speed of TF but seems TF is using python and it is gonna be quite slow. What is the rrecommended way to test the speed of a model in TF?

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
