### ISSUE TITLE
 tf.cond doesn't work as expected

### ISSUE THREAD

**Issue by shzygmyx** [tensorflow/tensorflow#9628]
### System information
- **Windows 10**:
- **TensorFlow installed from pip install**:
- **TensorFlow version 1.0**:

### Describe the problem
When I use tf.cond, both f1 and f2 are executed.

### Source code / logs

    sess = tf.Session()
    x = tf.constant(7)
    y = tf.constant(5)
    lst = []
    def f1():
        global lst
        lst.append(x)
        return x
    def f2(): 
        global lst
        lst.append(y)
        return y
    r = tf.cond(tf.less(x, y), f1, f2)
    print(sess.run(lst))  #return [7,5], which means lst.append(x) and lst.append(y) are both executed

**Comment by mocique** [comment]
print(lst) 
<< [<tf.Tensor 'Const:0' shape=() dtype=int32>, <tf.Tensor 'Const_1:0' shape=() dtype=int32>]
When you run lst ,you are not actually using tf.cond. Instead, you will fetch both x and y directly.

**Comment by shzygmyx** [comment]
@mocique Thanks for your reply, but shouldn't lst be 1) [<tf.Tensor 'Const:0' shape=() dtype=int32>] or 2)[<tf.Tensor 'Const_1:0' shape=() dtype=int32>]?

**Comment by drpngx** [comment]
Yes, both are executed. f1 and f2 are creating a graph, so they are executed. If you want to construct a list, use `tf.concat`.
