### ISSUE TITLE
Implement of attention mechanisms

### ISSUE THREAD

**Issue by Songweiping** [tensorflow/tensorflow#9635]
Here is a question(maybe bug) about implements of different attention mechanisms, i.e. LuongAttention & BahdanauAttention, in contrib/seq2seq/python/ops/attention_wrapper.py. It seems that the only difference is their score functions(alignment models).

 In BahdanauAttention, the alignment model is as described in https://arxiv.org/abs/1412.7449

```
 score = math_ops.reduce_sum(v * math_ops.tanh(keys + processed_query),
                                    [2])
```

In LuongAttention, the alignment model is a dot function:
`score = math_ops.matmul(query, self.keys, transpose_b=True)`

Then, the context vector is used all in same way. However, there should be more differences between these two attention mechanisms. Is this a modified version of Bahdanau attention proposed in https://arxiv.org/abs/1409.0473?

Any response would be appreciated. Thanks!

**Comment by skye** [comment]
@ebrevdo can you comment?

**Comment by ebrevdo** [comment]
LuongAttention implements the following paper:

Minh-Thang Luong, Hieu Pham, Christopher D. Manning.
  "Effective Approaches to Attention-based Neural Machine Translation."
  EMNLP 2015.  https://arxiv.org/abs/1508.04025

both attentions have a scaling option (Luong it's called "scale" and Bahdanau it's called "normalize").  The Luong scaling version is unpublished; the Bahdanau normalize option is based on a recent paper by colin raffel.

Either way; that really is the only difference between the two attention mechanisms.  Everything else is the same.  Is there a specific term that you feel should be different between the two?

**Comment by ebrevdo** [comment]
(other differences have been factored out and are controlled elsewhere; for example, the AttentionWrapper object has an argument `output_attention`; the Luong and Bahdanau papers used different versions of this.  but from an API perspective, it's better to keep it configurable elsewhere).

**Comment by Songweiping** [comment]
I guess another main difference is where computation begins. In Bahdanau papers, the path is h(t-1)->a(t)->c(t)->h(t), while in Luong it should be h(t)->a(t)->c(t)->h˜(t).

In current implements, both Bahdanau and Luong use current hidden state h(t) as "query" to attend on memories. I don't know whether this matters a lot or not.

**Comment by yhg0112** [comment]
i believe that @Songweiping is correct and that is specified on the Luong's paper if i remember correctly. 
for your information, i'd implemented both and they actually had no significant difference in final performance for NMT tasks(in both log-perplexity and BLEU).

**Comment by Songweiping** [comment]
@yhg0112 That makes sense to me. Using h(t-1) or h(t) to determine the context vector seems not a big issue.
BTW, I'm curious about how these two TF implements of Luong and Bahdanau perform on NMT tasks. Have you tested this? @yhg0112

**Comment by lmthang** [comment]
Hi guys,

Thanks for discussing. I developed the early version of attention_wrapper.py. To me, we replicate most details in Bahdanau and Luong's attention mechanisms, except from the fact that Songweiping mentions "In Bahdanau papers, the path is h(t-1)->a(t)->c(t)->h(t), while in Luong it should be h(t)->a(t)->c(t)->h˜(t)." I have run tests over many variations; we're gonna release results in this month. So stay tune!
ps: For the scaled version of Luong and the normalized version of Bahdanau, see this paper https://arxiv.org/abs/1704.00784. We simplified scaled LuongAttention a bit when implementing though.

**Comment by Songweiping** [comment]
That sounds great! Please let us know once you release those results.

**Comment by Songweiping** [comment]
Hi @ebrevdo @lmthang ,

I am wondering if it is desirable to support personalized activation function in attention layer. In current version, no activation is applied after concatenating context vector and target hidden value, while there is a _tanh_ in Luong's paper https://arxiv.org/abs/1508.04025.
I have tested this on some tasks, it seems that it does make some difference, but not significant. Therefore, this is just a kind suggestion.

Thanks!

**Comment by renzhe0009** [comment]
In this paper
https://arxiv.org/abs/1607.01628
From chapter 3.1 Decoder Cost,
They observe that BahdanauAttention works better than concatenation in their experiments.

**Comment by ebrevdo** [comment]
@Songweiping do you mean like adding an `attention_layer_activation` in addition to `attention_layer_size`?

**Comment by ebrevdo** [comment]
BTW I'm going to close this issue soon as it seems thang answered the main question.

**Comment by Songweiping** [comment]
@ebrevdo That's what I mean. Thanks!

**Comment by lmthang** [comment]
Yes, adding attention_layer_activation makes sense to me :)

**Comment by rubenvereecken** [comment]
I'm sorry for commenting on a closed issue, but @lmthang did you end up benchmarking those different attention mechanisms?

**Comment by lmthang** [comment]
Hi @rubenvereecken,

I did try to benchmark but didn't have time to publish the results ... I'd suggest trying it on your own problem to see if there's a difference. In many cases, we only see minor differences.
