### ISSUE TITLE
Convolutional Neural Networks Tutorial problem

### ISSUE THREAD

**Issue by BigHopes** [tensorflow/tensorflow#9637]
I am learning about Convolutional Neural Networks from the tutorial:
https://www.tensorflow.org/tutorials/deep_cnn
 
Inside it there is a link for getting the code but it is not working:
https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow_models/tutorials/image/cifar10/

how can I get the code?

**Comment by shahzeb1** [comment]
Most tensorflow models are now in their own [models repo](https://github.com/tensorflow/models).

Here's what you're looking for: https://github.com/tensorflow/models/tree/master/tutorials/image/cifar10

**Comment by drpngx** [comment]
I think you're referring to the link here, right?

```
The CIFAR-10 network is largely contained in cifar10.py. 
```

Feel free to send a PR correcting the [md file](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/docs_src/tutorials/deep_cnn.md#L99)
/CC: @nealwu

**Comment by nealwu** [comment]
It looks like the .md file on GitHub is correct, but the TensorFlow site documentation points to the wrong place. Seems like a documentation bug -- talked to @wolffg and he will look into it.

**Comment by ddurham2** [comment]
Another bug in the same document is the last sentence in the "Pooling Layer #1" section.  It says "has a shape of [batch_size, 14, 14, 1]" but it should read "has a shape of [batch_size, 14, 14, **32**]"

**Comment by nealwu** [comment]
Hi @ddurham2, thanks for reporting this. We fixed this in https://github.com/tensorflow/tensorflow/issues/8301, but unfortunately it looks like it still hasn't been pushed to the documentation site. Once r1.2 becomes the standard version however, the site will be correct (see https://www.tensorflow.org/versions/r1.2/tutorials/layers#pooling_layer_1).

**Comment by nealwu** [comment]
Closing this issue since it has been fixed in https://www.tensorflow.org/versions/r1.2/tutorials/deep_cnn and will be the default once r1.2 is the standard.
