### ISSUE TITLE
Indexed Slices Support

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/tensorflow#9644]
Hi,

I am wondering what the reasoning behind IndexedSlices is and whether they are actually necessary. My understanding is that they are only constructed for the gradient of the gather op. Is there any other place in the Python API that IndexedSlices are being constructed? Now, even though they are only constructed there, there are special cases throughout the Python codebase for dealing with indexed slices. Is the performance benefit so important to justify all this special treatment code? I am asking because I am wondering if it is useful to implement that functionality in an API for a different language. 

And if I am to rephrase this question, should one put effort into adding support to the C++ API for indexed slices, or is their use a remnant of a design choice that is not that useful looking in retrospect?

Thank you!

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
