### ISSUE TITLE
Gather/Slice/StridedSlice Gradients Support in the C++ API

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/tensorflow#9645]
Hi,

I noticed that there is currently no gradient support in the C++ API for the gather, slice, and strided slice ops. Would it be too difficult to add support for those gradient ops? I am asking because they are ops very frequently used in the context of machine learning models and without them building ML models can be unnecessarily complicated.

Thank you!

P.S. I have noticed that the Python API implementation of the gather op gradient uses indexed slices, but I am not sure if that is entirely necessary and can thus probably also be supported in the C++ API.

**Comment by skye** [comment]
@suharshs

**Comment by eaplatanios** [comment]
I think this issue deserves a discussion related to [indexed slices](https://github.com/tensorflow/tensorflow/issues/9644) and their usefulness. My impression is that they are only used in the "gather" op gradient and whenever used in other contexts, they are almost always converted to full tensors. Is that true? In that case, is it really useful having a special "indexed slices" data structure?

**Comment by suharshs** [comment]
@keveman Can you comment about indexedslices? Or cc someone who knows more about that?
Thanks!

**Comment by dynamicwebpaige** [comment]
Adding @martinwicke (RE: C++ API needs for TensorFlow). It looks like strided slice and slice are supported by the merged PRs above; is gather still lacking?

**Comment by tilakrayal** [comment]
@eaplatanios,
Respected PR's were merged and closed. Could you please check the PR and confirm if the issue got resolved. Thank you!
