### ISSUE TITLE
Estimator's argument checking overzealous : model_fn has following not expected args: ['self']

### ISSUE THREAD

**Issue by JulesKzl** [tensorflow/tensorflow#9654]
I'm using TensorFlow (1.1) high-level API Estimators to create my neural net. But I'm using it into a class and I have to call an instance of my class to generate the model of the neural network. (Here `self.a`)

```
class NeuralNetwork(object):
  def __init__(self):
    """ Create neural net """
    regressor = tf.estimator.Estimator(model_fn=self.my_model_fn,
                                       model_dir="/tmp/data")
    // ...

  def my_model_fn(self, features, labels, mode):
  """ Generate neural net model """
    self.a = a
    predictions = ...
    loss = ...
    train_op = ...
    return tf.estimator.EstimatorSpec(
      mode=mode,
      predictions=predictions,
      loss=loss,
      train_op=train_op)
```

But I get the error : ValueError: model_fn [...] has following not expected args: ['self']. I tried to remove the self for the args of my model but got another error TypeError: … got multiple values for keyword argument. 
Solution for now (as it was suggested on [StackOverflow](http://stackoverflow.com/questions/43755609/tensorflow-estimator-model-fn-has-following-not-expected-args-self)) is to use a lambda function to wrap my function `my_model_fn` (see below) but it will be nicer without it.
```
class NeuralNetwork(object):
  def __init__(self):
    """ Create neural net """
    regressor = tf.estimator.Estimator(
        model_fn=lambda features, labels, mode: self.my_model_fn(features, labels, mode),
        model_dir="/tmp/data")
    // ...
```

**Comment by drpngx** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by allenlavoie** [comment]
This is a feature request (and came from StackOverflow). Assigning @ispirmustafa: I think we just want to special-case member functions?

**Comment by ispirmustafa** [comment]
Yes this is a valid feature request.

**Comment by roi-f** [comment]
+1 to this request, facing the same problem and was advised to open a feature request.

**Comment by martinwicke** [comment]
This is a good feature request. Anybody who wants to send a PR, please do. We won't get to this for a few weeks at least.

**Comment by drpngx** [comment]
Can we use a lambda as a workaround in the meantime?

**Comment by drpngx** [comment]
@JulesKzl could you post the stackoverflow link? Thanks.

**Comment by martinwicke** [comment]
Yes, the lambda workaround should work fine.

**Comment by JulesKzl** [comment]
As I wrote and now edited to cite the [Stackoverflow](http://stackoverflow.com/questions/43755609/tensorflow-estimator-model-fn-has-following-not-expected-args-self) topic : `Solution for now (as it was suggested on StackOverflow) is to use a lambda function to wrap my function my_model_fn (see below) but it will be nicer without it.`
