### ISSUE TITLE
Fail to compile binary for Android

### ISSUE THREAD

**Issue by PKUEcho** [tensorflow/tensorflow#9662]
Is there simple way to compile a native binary for inference on Android? Now I can successfully build the [benchmark](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/benchmark) and run it on my Android device. But it does not contain any actions about ops. I want to do something similar to the [benchmark_model_test](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/benchmark/benchmark_model_test.cc) but it fails to build. I think it now lacks a android version of //tensorflow/cc APIs. How can I tackle it?

**Comment by flawless2011** [comment]
Have you read this? https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/android

**Comment by PKUEcho** [comment]
Thanks @flawless2011 I've read that. I want to use the apis under //tensorflow/cc/..., but it seems that the lib you provide doesn't refer to these apis? Code in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/benchmark/benchmark_model_test.cc uses some ops apis instead. For most TF apis, we already have //tensorflow/core:android_tensorflow_lib, but in my case I want to compile more but failed.

**Comment by PKUEcho** [comment]
@flawless2011 Did I make my question clear? I hope you can have comments or help refer to someone who should be familiar with this. Really appreciate that.

**Comment by drpngx** [comment]
Sorry I'm not getting this. What do you want to do? Compile directly against the C++ library on android?

/CC: @asimshankar

**Comment by PKUEcho** [comment]
@drpngx Basically, I want to build a native binary on Android, which simply creates a graph with some ops and execute it with some random input. The [benchmark](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/benchmark) is a good example which can run on Android, but it just reads the graph without constructing its own graph. From what I've found via the [benchmark_model_test](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/benchmark/benchmark_model_test.cc) and [label_image](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/label_image) examples, I need to include apis under //tensorflow//cc to use ::tensorflow::ops::XXX (such as ResizeBilinear).
So my question is how to compile the //tensorflow/cc for Android? I didn't find any target inside //tensorflow/cc.BUILD, and failed to build it by myself.

**Comment by asimshankar** [comment]
@PKUEcho : So you want to compile essentially an arbitrary binary that uses the C++ API for graph construction for Android?

This seems more like a bazel question :), but the good news is that that the only difference between compiling for Android or for your host machine should be flags to bazel.

I suppose you could do one of the following:

- Modify [`benchmark.cc`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/benchmark/benchmark_model.cc) with the code you want, and add `//tensorflow/cc:cc_ops` to the `deps` [section in the BUILD file](https://github.com/tensorflow/tensorflow/blob/bc456e361d49d1d89a74b80060c70efb51fd7d87/tensorflow/tools/benchmark/BUILD#L33). And build the binary as per the instructions you pointed to. Those instructions show how to build any bazel target for Android.

- Compile the shared library for Android using something like:
```
bazel build -c opt \
  --crosstool_top=//external:android/crosstool \
  --cpu=armeabi-v7a \
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
  tensorflow:libtensorflow_cc.so
```
This would be a shared library that you can link against in any native code you build for Android.

Hope that helps.

**Comment by PKUEcho** [comment]
@asimshankar thanks for your reply! I'm missing some details here. So, basically you provide two solutions here, right?

- Inside the deps as following, I think I need to insert `//tensorflow/cc:cc_ops` after `//tensorflow:android` rather than `//conditions:default`? Because I think that's the true `deps` when I build it for Android.
`cc_library(
    name = "benchmark_model_lib",
    testonly = 1,
    srcs = [
        "benchmark_model.cc",
    ],
    hdrs = [
        "benchmark_model.h",
    ],
    copts = tf_copts(),
    visibility = ["//visibility:public"],
    deps = select({
        "//tensorflow:android": [
            "//tensorflow/core:android_tensorflow_lib",
            "//tensorflow/core:android_tensorflow_test_lib",
        ],
        "//conditions:default": [
            "//tensorflow/core:core_cpu",
            "//tensorflow/core:lib",
            "//tensorflow/core:framework",
            "//tensorflow/core:framework_internal",
            "//tensorflow/core:framework_lite",
            "//tensorflow/core:protos_all_cc",
            "//tensorflow/core:tensorflow",
            "//tensorflow/core:test",
        ],
    }),
)`

After that, I tried use the following command to build it but failed. Did I miss anything from your answer?
`$bazel build -c opt \
  --crosstool_top=//external:android/crosstool \
  --cpu=armeabi-v7a \
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
  tensorflow/tools/benchmark:benchmark_model`

**Comment by PKUEcho** [comment]
@asimshankar I tried the second way you provided as following.
`bazel build -c opt \
  --crosstool_top=//external:android/crosstool \
  --cpu=armeabi-v7a \
  --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
  tensorflow:libtensorflow_cc.so`

But there are many errors such as `error: expected initializer before 'noexcept' memory_order __m) noexcept`. I think there's something about the compilers. How do you think about?

**Comment by asimshankar** [comment]
@PKUEcho : What errors were you getting when you tried to build `benchmark_model`? 

(Based on updates in #2412 - I'd avoid that second suggestion altogether for now, though the errors you're seeing are different, but it seems using `libtensorflow_cc.so` isn't convenient yet)

That said, CCing @andrewharp in case he has ideas, but marking this as "community support" since building native binaries using the C++ API for Android isn't something that we are currently actively working on or supporting.

**Comment by andrewharp** [comment]
Right, unifying the android_* libs with the other cc_library TF targets isn't really something on our radar.

However, if you take a look at https://github.com/tensorflow/tensorflow/pull/9563, they manage to build cc_ops into an Android binary, so that might be a possible route to investigate.

**Comment by PKUEcho** [comment]
@asimshankar @andrewharp Thanks for your help. After reading the [#9563](https://github.com/tensorflow/tensorflow/pull/9563), I found that I missed the flags `--cxxopt="-std=c++11" --cxxopt="-DTENSORFLOW_DISABLE_META"` which makes my previous compilation fail. Though I'm not sure why in other cases such as [benchmark_mode](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/benchmark) I don't need these flags?
Also, I found that some ops are not supported in mobile version currently. How can I check which ops are supported and which are not? This question might be out of the scope of this thread so you may close this.

**Comment by drpngx** [comment]
There are kernels that definitely work, and kernels that may work.

The kernels that may work are [here](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/BUILD#L4267).

The ones that definitely work are [core and extended](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/BUILD#L4317).

Closing for now.

**Comment by freedomtan** [comment]
@PKUEcho some ops use C++11 features, but the default cross-toolchain in NDK (gcc-4.9) uses C++98. That's why you need --cxxopt="-std=c++11"

**Comment by PKUEcho** [comment]
@freedomtan Thanks for your reply, that makes sense :)

**Comment by maelp** [comment]
Hi, I'm trying to build the standard Android C API (not the JNI API) so I can build a standalone binary in Rust on Android, what would be the recommended way? I saw the `contrib/android` builds the JNI lib, should I simply do a cross-compile bazel build of `//tensorflow:libtensorflow.so` ?

**Comment by andrewharp** [comment]
@maelp The target you're looking for is //tensorflow/core:android_tensorflow_lib. See //tensorflow/contrib/android/README.md for the set of build flags to use.

**Comment by maelp** [comment]
Hi @andrewharp thanks for your answer, my question is not so much about Rust integration as it is about getting the C or C++ library cross-compiled on Android

From your comment I assume that I need to add a build target with both `android_tensorflow_lib` and `c_api` to build those? There is not yet an existing cross-compile build target which compiles the C .so for Android without the rest of the JNI bindings?

**Comment by andrewharp** [comment]
Correct: the c_api target depends on android_tensorflow_lib_lite, which is runtime-only (no ops), so you'll need a target that adds them in. My suggestion would be to take //tensorflow/contrib/android:libtensorflow_inference.so as a starting point and modify it to fit your needs (remove the jni files, change the whitelisted methods so they don't get stripped out, etc).
