### ISSUE TITLE
Android Inference AAR Release Builds

### ISSUE THREAD

**Issue by flawless2011** [tensorflow/tensorflow#9665]
### Android Release request
You currently have [nightly Android builds](https://ci.tensorflow.org/view/Nightly/job/nightly-android/).  Is it possible to also have a Jenkins job that publishes stable release (and maybe RC) builds for Android?

Or alternatively, can you publish release and RC builds of your Android Inference AAR out somewhere they can be pulled as dependencies by Gradle (Maven Central or wherever other Android dependencies are stored)?

**Comment by drpngx** [comment]
@yifeif what do you think?

**Comment by andrewharp** [comment]
We've actually just published an initial aar yesterday: https://bintray.com/google/tensorflow/tensorflow-aar/1.2.0-preview#files

We'll be updating the Gradle code in the Android demo soon to show how to use it.

Plans going forward are to update this on every point release as part of the release process.

**Comment by flawless2011** [comment]
Great news, thank you!

**Comment by flawless2011** [comment]
One more question, do you guys plan on making this available in jcenter?  It doesn't appear to be there as I would expect to see it in the `org.tensorflow` group on jcenter (and its not currently there).

**Comment by andrewharp** [comment]
Yes, we're currently in the process of doing so, will update here with final details when available.

**Comment by andrewharp** [comment]
The AAR is [live](https://bintray.com/google/tensorflow/tensorflow-android)! See [this comment](https://github.com/tensorflow/tensorflow/issues/6385#issuecomment-299913647) for instructions on using.

**Comment by ImaOuaarouss** [comment]
the AAR doesn't seem to exist online can anybody send it to me please
