### ISSUE TITLE
Unsound GPU driver version scheme assumption in StringToDriverVersion

### ISSUE THREAD

**Issue by rgov** [tensorflow/tensorflow#9669]
Tensorflow's `cuda_diagnostics.cc` [here](https://github.com/tensorflow/tensorflow/blob/076799bdfae0057723d96f47cf78cb623c8bcd57/tensorflow/stream_executor/cuda/cuda_diagnostics.cc#L82) assumes that the GPU driver version will match `%d.%d.%d` but that doesn't seem to be a safe assumption.

```
2017-05-04 09:48:39.543664: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Invalid argument: expected %d.%d or %d.%d.%d form for driver version; got "378.05.05.05"
```

In `FindDsoVersion()`, TF is parsing the name of the loaded libcuda library to get the version number, and the current Nvidia web driver library is:

    /Library/Frameworks/CUDA.framework/Versions/A/Libraries/libcuda_378.05.05.05_mercury.dylib

**Comment by drpngx** [comment]
Would you care to send a PR?
