### ISSUE TITLE
InvalidArgumentError even finished feeding the values, maybe hidden bug of variable dependency

### ISSUE THREAD

**Issue by rylanchiu** [tensorflow/tensorflow#9670]
I have defined two classes of models, `x` and `y`. 

    class x():
        def __init__(self, x_inp1, x_inp2):
            # do sth...

        def step(self, session, encoder_inputs):
            input_feed = {}
            for l in range(encoder_size):
                 input_feed[self.encoder_inputs[l].name] = encoder_inputs[l]
            ...
            output_feed = [x_output]
            return session.run(x_output)

    class y():
        def __init__(self, y_inp1, y_inp2):
            # do sth...

        def step(self, encoder_inputs):
            input_feed = {}
            for l in range(encoder_size):
                 input_feed[self.encoder_inputs[l].name] = encoder_inputs[l]
            ...

They have quite similar functions. And then I define another class to group them up.

    class gp():
        def __init__(self, x_inp1, x_inp2, y_inp1, y_inp2):
            with tf.variable_scope('x'):
                  self.x_model = x(x_inp1, x_inp2)
            with tf.variable_scope('y'):
                  self.y_model = y(y_inp1, y_inp2)
        def step(self, session, encoder_inputs):
            print('train x....')
            x_output = self.x_model.step(session, encoder_inputs)
            print('train y....')
            y_output = self.y_model.step(session, x_output)
            ...

Please notice that the `y_model` takes the output of `x_model` as input. And I run the `gp()` in the `main` function:
    
    with tf.Session() as sess:
         gp_m = gp(x_inp1, x_inp2, y_inp1, y_inp2)
         gp_m.step(sess, x_inp1, x_inp2, y_inp1, y_inp2)

And after running  `x_output = self.x_model.step(encoder_inputs)` and begin to do `y_output = self.y_model.step(x_output)`, I got such an error:
    
    InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'x/encoder0' with dtype int32
	 [[Node: x/encoder0 = Placeholder[dtype=DT_INT32, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Please notice this error points to the `x_model` even the step function of it has been finished, i.e., both `train x...` and `train y...` are shown. The `x_output` should be python list and numpy array, and it is not Tensorflow object anymore. So maybe there is any bug of the variable dependency? Or I have any wrong operation that cause such a kind of error? 

Here are the information maybe useful:

### install using pip

**Comment by Carmezim** [comment]
Thank you for reporting, please fill the [issue template with all other information required](https://github.com/tensorflow/tensorflow/issues/new).

**Comment by rylanchiu** [comment]
@carlthome Thanks for your reply. I have provided some information below. But indeed I am not sure that whether it is really a bug or just I have built up the model in improper way. Could you please take a look at my code and see if I have done anything wrong? Thanks.

**Comment by andydavis1** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
