### ISSUE TITLE
tf.contrib.image.rotate errors under Windows

### ISSUE THREAD

**Issue by timttate** [tensorflow/tensorflow#9672]
### Description
Trying to use `tf.contrib.image.rotate` produces the error: `tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'ImageProjectiveTransform'`. This appears to happen on Windows using both CPU and GPU, and does not appear to happen on Linux (Ubuntu 14.0.4, Tensorflow 1.0.1).

### Test Case
```
import tensorflow as tf
images = tf.zeros([2, 2])
rotated_images = tf.contrib.image.rotate(images, 0)
```

### Traceback
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    rotated_images = tf.contrib.image.rotate(images, 0)
  File "C:\Users\tim\didi-car\tf_env\lib\site-packages\tensorflow\contrib\image\python\ops\image_ops.py", line 72, in rotate
    angles_to_projective_transforms(angles, image_width, image_height))
  File "C:\Users\tim\didi-car\tf_env\lib\site-packages\tensorflow\contrib\image\python\ops\image_ops.py", line 166, in transform
    output = gen_image_ops.image_projective_transform(images, transforms)
  File "C:\Users\tim\didi-car\tf_env\lib\site-packages\tensorflow\contrib\image\ops\gen_image_ops.py", line 49, in image_projective_transform
    transforms=transforms, name=name)
  File "C:\Users\tim\didi-car\tf_env\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "C:\Users\tim\didi-car\tf_env\lib\site-packages\tensorflow\python\framework\ops.py", line 2338, in create_op
    set_shapes_for_outputs(ret)
  File "C:\Users\tim\didi-car\tf_env\lib\site-packages\tensorflow\python\framework\ops.py", line 1719, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "C:\Users\tim\didi-car\tf_env\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "C:\Users\tim\didi-car\tf_env\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "c:\users\tim\anaconda3\Lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Users\tim\didi-car\tf_env\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'ImageProjectiveTransform'
```

### System information
- Windows 10 Pro
- TensorFlow 1.1.0 installed via pip into virtual environment
- Python 3.5.1 (Anaconda)

**Comment by timttate** [comment]
If the PIP package for Windows is built with CMake, it seems like perhaps this is a known limitation of the TensorFlow CMake build?

From the TensorFlow CMake README:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md

> It is not possible to load a custom Op library.

The CMake README also claims that:

> The tf.contrib libraries are not currently included in the PIP package.

which doesn't *seem* to be the case anymore, since I have been using tf.contrib.layers without issue.

**Comment by astromme** [comment]
I'm getting this as well. Did you solve it?

**Comment by ringw** [comment]
I'm traveling but will spin up a Windows VM and debug this when I get home in 2 weeks.

**Comment by OddNo7** [comment]
Having the same issue here. 

- Win 10 
- TensorFlow 1.2 installed via pip into a virtual environment.
- Python 3.5.2 (Anaconda)

The test case is similar.

**Comment by roponator** [comment]
Same problem, using non-anaconda python, win10.

**Comment by basejn** [comment]
I have the same problem . 

    Win 7
    TensorFlow 1.2 installed via pip.
    Python 3.5 (Anaconda)

**Comment by fodortibi** [comment]
I have the same problem even with 1.3.0rc0 win7 CPU.
tensorflow-1.3.0rc0-cp35-cp35m-win_amd64.whl
https://pypi.python.org/packages/44/43/bcacb6d0a1b63bb0e000a5301079dc66f4da842923878b371a63645ee188/tensorflow-1.3.0rc1-cp35-cp35m-win_amd64.whl#md5=95b003c917ce4f535fab12a149a953d1

Jupyter notebook:
http://www.anishathalye.com/media/2017/07/25/adversarial.ipynb

NotFoundError: Op type not registered 'ImageProjectiveTransform' in binary running on DHUB2362. Make sure the Op and Kernel are registered in the binary running in this process.

**Comment by vinayprabhu** [comment]
Same issue here

- Windows 10
- GTX 960M
- Python 3.5 (Anaconda)
- tensorflow_gpu-1.2.1-cp35-cp35m-win_amd64.whl
- tf 1.2.1

**Comment by venkatesh-sg** [comment]
Same problem. Did anyone solved it or is there any work around?

**Comment by fodortibi** [comment]
Hello, my work around was to switch to Ubuntu Linux. It took about an hour an 10GB HD space to install VirtualBox on my Windows, and Linux and python and tensorflow, and all the other packages and the rotate operation works. Regards. Tibi

**Comment by ringw** [comment]
Thanks @av8ramit!

**Comment by zcz004** [comment]
@av8ramit This function can only be used by building tf from source? The error persists.

**Comment by zcz004** [comment]
Does pip package include this update?

**Comment by av8ramit** [comment]
The nightly pip packages have this update.

**Comment by zcz004** [comment]
@av8ramit Thank you. It helps.

**Comment by zcz004** [comment]
Can it be backpropagated? It seems it can't...

**Comment by Moondra** [comment]
Same problem here:

- Windows 7

- Tensorflow 1.3

- Python 3.6

**Comment by gunan** [comment]
We are working on TF 1.4. I think it will have this fix.
We will not create a patch release for 1.3, because this issue is in contrib.
(That is not saying for all issues in core we will create patch releases.)

**Comment by zywvvd** [comment]
that's true . 
the problem is handled well after I installed tensorflow 1.4 
before that I used tf 1.3 on Win 10
tf1.4 seems to not be installed by pip current now 
I downloaded a copy from the link https://pypi.python.org/pypi/tensorflow
