### ISSUE TITLE
tensorflow.bzl.bzl doesn't exist, unsurprisingly

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#968]
I get a pile of build errors after pulling.  One of them is that `tensorflow.bzl.bzl` doesn't exist.  Did someone rewrite the build rules recently?

    bazel build ...
    ERROR: /usr/local/google/home/geoffreyi/tensorflow/tensorflow/cc/BUILD:11:6: First argument of load() is a path, not a label. It should start with a single slash if it is an absolute path..
    ERROR: /usr/local/google/home/geoffreyi/tensorflow/tensorflow/cc/BUILD:12:6: First argument of load() is a path, not a label. It should start with a single slash if it is an absolute path..
    ERROR: /usr/local/google/home/geoffreyi/tensorflow/tensorflow/cc/BUILD:11:6: file '/tensorflow:tensorflow.bzl.bzl' was not correctly loaded. Make sure the 'load' statement appears in the global scope in your file.
    ERROR: /usr/local/google/home/geoffreyi/tensorflow/tensorflow/cc/BUILD:12:6: file '/tensorflow:tensorflow.bzl.bzl' was not correctly loaded. Make sure the 'load' statement appears in the global scope in your file.
    ERROR: /usr/local/google/home/geoffreyi/tensorflow/tensorflow/cc/BUILD:21:13: Traceback (most recent call last):
      File "/usr/local/google/home/geoffreyi/tensorflow/tensorflow/cc/BUILD", line 14
        cc_library(name = "cc_op_gen_main", srcs = ["..."], <3 more arguments>)
      File "/usr/local/google/home/geoffreyi/tensorflow/tensorflow/cc/BUILD", line 21, in cc_library
        tf_copts
    name 'tf_copts' is not defined.
    ERROR: /usr/local/google/home/geoffreyi/tensorflow/tensorflow/cc/BUILD:28:1: name 'tf_gen_op_wrappers_cc' is not defined.
    ERROR: /usr/local/google/home/geoffreyi/tensorflow/tensorflow/cc/BUILD:66:13: Traceback (most recent call last):
      File "/usr/local/google/home/geoffreyi/tensorflow/tensorflow/cc/BUILD", line 63
        cc_binary(name = "tutorials_example_traine...", <4 more arguments>)
      File "/usr/local/google/home/geoffreyi/tensorflow/tensorflow/cc/BUILD", line 66, in cc_binary
        tf_copts
    name 'tf_copts' is not defined.
    ... (many more)

**Comment by girving** [comment]
This is on my Goobuntu machine.

**Comment by vrv** [comment]
You need bazel 0.1.4
