### ISSUE TITLE
I am not able to install tensorflow

### ISSUE THREAD

**Issue by sudhirshahu51** [tensorflow/tensorflow#9680]
>pip install tensorflow
Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow

For info I am using Window 10 and Python 3.5.2
please help

**Comment by mcenderdragon** [comment]
Hi I am have currently the same problem. It helped to follow the steps [here](http://stackoverflow.com/questions/38896424/tensorflow-not-found-in-pip). But now I am having the problem `import tensorflow` crashes.

**Comment by SrivastavaKshitij** [comment]
Use anaconda. it is much easier to maintain dependencies .

**Comment by andydavis1** [comment]
Please reopen if the referenced steps on StackOverflow did not resolve the issue.

**Comment by sudhirshahu51** [comment]
@SrivastavaKshitij  I am facing the same problem also on anaconda after installing the those two packages

**Comment by sudhirshahu51** [comment]
C:\Users\Sudhit>pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.1.0-cp35-cp35m-window.whl
tensorflow-1.1.0-cp35-cp35m-window.whl is not a supported wheel on this platform.

how I will know which we will be supported whell for my platform?

**Comment by SrivastavaKshitij** [comment]
cp35 is for python 3.5 . I hope you are using the correct version. 
Also, I hope you are creating a virtual environment inside anaconda for tensorflow.

Use the procedure here. https://www.tensorflow.org/install/install_windows

I dont think there could be any problem installing tensorflow with anaconda. It is one of the cleanest way to install TF

**Comment by sudhirshahu51** [comment]
@SrivastavaKshitij 
(tensorflow) C:\Users\Sudhit>pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.1.0-cp35-cp35m-win_amd64.whl
tensorflow-1.1.0-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.  

![screenshot 19](https://cloud.githubusercontent.com/assets/25053295/25775784/cfa239ae-32c6-11e7-9459-fe16f4d9398e.png)
  

Still having this return message, what should I do now??

**Comment by SrivastavaKshitij** [comment]
try installing version 1.0.1 instead of 1.1.0

https://www.tensorflow.org/versions/r1.0/install/install_windows

**Comment by Xiangyi1996** [comment]
@sudhirshahu51 
could you please tell me where get your desktop background picture?

**Comment by sudhirshahu51** [comment]
@Xiangyi1996  I got this from Bing Images search, if you want I can mail it to you :)

**Comment by Adamage** [comment]
I am having the same error. Is there a list of all requirements of tensorboard?

**Comment by leslyarun** [comment]
I'm also getting the same error.
tensorflow-1.1.0-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.

Even for version 1.0.1 , same error is coming

**Comment by SrivastavaKshitij** [comment]
@leslyarun @sudhirshahu51 : I dont work on windows. So I can't be of real help now. I hope someone who works on windows can help you out !

**Comment by pranavred** [comment]
Anything yet? Same error here too. Struggling since a few hours.

**Comment by vilero** [comment]
Hi, if you create a environment using anaconda, try this:
conda create -n tensorflow python=3.5
activate tensorflow
pip install --ignore-installed --upgrade https://......

**Comment by pranavred** [comment]
@vilero  It worked. Thanks man.

**Comment by Louis1994** [comment]
I tried pip3 not pip, and it worked. Hope it will help.

**Comment by sudhirshahu51** [comment]
@pranavred can you tell me what are getting after giving this command 
`python -c "from pip import pep425tags;print(pep425tags.supported_tags)"`

**Comment by sudhirshahu51** [comment]
@Adamage give the above command you will get knowledge about what your system supports.

**Comment by Adamage** [comment]
Well guys, the thing is Im a total idiot - I thought this topic is about tensorboard, as it gives the same error when you try to install it on PIP. Actually tensorboard is shipped with tensorflow... sorry. I did not have any issue

**Comment by leslyarun** [comment]
@vilero worked like a charm.
I had python 3.6 in my system. Just found out it will work with 3.5 version alone and not any version above 3.5

**Comment by EdLucio** [comment]
same with @Louis1994 , used pip3 and the installation worked. Also using windows 10 and 
python 3.5

**Comment by klaxman** [comment]
For me, TF 1.0 pip3 install works fine with py35 and not py36. Had installed py35 and followed tf documentation and was able to install.

**Comment by shashankatilak** [comment]
I installed python3.6.5 64bit from python.org website on my windows. Following commands works fine without any issues on Windows 7 and Windows 10.

`pip3 install --upgrade tensorflow`

In addition I also ran following command for installing jupyter notebooks and other useful packages

`pip3 install jupyter pandas matplotlib scikit-learn`

Most likely the issue might be user has 32 bit python installed on windows. By default when you download python from python.org,  you are downloading 32 bit and not 64-bit.   Download 64 bit python and try again.

**Comment by fepegar** [comment]
I just had this problem because latest `conda` is already installing Python 3.7. Just downgrade to 3.6:
```
conda install python=3.6
pip install tensorflow
```

**Comment by luckylehana** [comment]
After searching a lot and trying to install and reinstall Python, i found the solution was very simple

use the following for windows

python -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl

change to following on mac

python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl

for Anaconda use corresponding conda

**Comment by amitection** [comment]
> @vilero worked like a charm.
> I had python 3.6 in my system. Just found out it will work with 3.5 version alone and not any version above 3.5

https://stackoverflow.com/questions/46842398/is-it-true-that-tensorflow-only-work-on-python3-5-2

**Comment by darlanpj** [comment]
This worked for me.
> python -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl

However, I'm trying to use plaidbranch with Python 3.7. However, the following message appears:
`PS C:\Users\darlan-pc\Documents\PlaidML\plaidbench>  python .\plaidbench.py --no-plaid resnet50
Using TensorFlow backend.
Error: Missing needed packages for benchmark; to fix, pip install keras tensorflow`

I will try to run with version 3.6...

**Comment by RamishaRaniK** [comment]
Tensorflow is not compatible with python3.7 and spyder3.3.1

To work with stable tensorflow  version

follow the procedure

> windows-->search-->Anaconda prompt-->right click -->click Run as adminstrator

Below command create the virtual environment which does not disturb existing projects

    conda create -n projectname 

Below command activates your virtual environment within this directory installed package will not disturb your existing project.

    activate projectname

Below command installs python 3.6.7 and spyder 3.2.3 as well

    conda install spyder=3.2.3

Below mentioned tensorflow version works without any error. As per your need, you can install tensorflow version specifically.

    pip install tensorflow==1.3.0

To open spyder

    spyder

To exit form Virtual environment

    deactivate

**Comment by TheIdanLapid** [comment]
> Tensorflow is not compatible with python3.7 and spyder3.3.1
> 
> To work with stable tensorflow version
> 
> follow the procedure
> 
> > windows-->search-->Anaconda prompt-->right click -->click Run as adminstrator
> 
> Below command create the virtual environment which does not disturb existing projects
> 
> ```
> conda create -n projectname 
> ```
> Below command activates your virtual environment within this directory installed package will not disturb your existing project.
> 
> ```
> activate projectname
> ```
> Below command installs python 3.6.7 and spyder 3.2.3 as well
> 
> ```
> conda install spyder=3.2.3
> ```
> Below mentioned tensorflow version works without any error. As per your need, you can install tensorflow version specifically.
> 
> ```
> pip install tensorflow==1.3.0
> ```
> To open spyder
> 
> ```
> spyder
> ```
> To exit form Virtual environment
> 
> ```
> deactivate
> ```

Really? TF isn't compatible with the latest version of Python? :(

**Comment by RamishaRaniK** [comment]
So far. Variable used in tf are marked as reserved keywords in python 3.7

**Comment by kawlaaKr** [comment]
Hi,
I try to install tensorflow with GPU support : I utilized pip install tensorflow-gpu with different versions.
I utilized a Tesla K40 GPU model as avirtual machine, where those are  already existed:
-Python Version: 2.7
-Cuda compilation tools, release 9.1, V9.1.85,
-locate libcudnn.so:
/usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudnn.so.6
/usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudnn.so.6.0.21
/usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.1/targets/x86_64-linux/lib/libcudnn.so.7.0.5

Every time , i find the same error: ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

**Comment by HazratBilal12** [comment]
> Use anaconda. it is much easier to maintain dependencies .

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda==2018.12=py37_0 -> bleach==3.0.2=py37_0
  - anaconda==2018.12=py37_0 -> mkl-service==1.1.2=py37hb782905_5
  - anaconda==2018.12=py37_0 -> numexpr==2.6.8=py37hdce8814_0
  - anaconda==2018.12=py37_0 -> scikit-learn==0.20.1=py37h343c172_0
  - tensorflow
Use "conda info <package>" to see the dependencies for each package.

How to fix it.

**Comment by SohiniChaudhuri** [comment]
I am also facing exactly the same problem … please help me … although in anaconda navigator and by using spyder I am able to import tensorflow but in command prompt it is unable to import tensorflow…

Please help me!!!

**Comment by RamishaRaniK** [comment]
@SohiniChaudhuri 

Please check the Virtual Environmental.
For example, if u have installed Tensorflow in AA Environment, then it will not reflect in the base Environment. 
If you are trying in a command prompt, it takes the base environment. so try to do in the respective environment.
Anaconda
(base)c:\ activate AA
(AA)c:\

**Comment by smzahir** [comment]
try ' conda install tensorflow ' in cmd

**Comment by RamishaRaniK** [comment]
@smzahir 

Are you trying to install in command prompt or anaconda cmd prompt?
what is the error message?

**Comment by smzahir** [comment]
Try in command prompt

**Comment by RamishaRaniK** [comment]
@smzahir 

please say the error message.

**Comment by smzahir** [comment]
When i used ' pip install tensorflow ' its shows the error message as:
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow
Then i used  ' conda install tensorflow ' command in Command prompt which really worked.

**Comment by RamishaRaniK** [comment]
@smzahir 
 As per your statement, conda install tensorflow has worked. ''pip install always check with python version.
so whats is your python version.

**Comment by smzahir** [comment]
@RamishaRaniK 
I think tensorflow works with python version upto 3.6 while mine is 3.7

**Comment by bryanseah234** [comment]
> After searching a lot and trying to install and reinstall Python, i found the solution was very simple
> 
> use the following for windows
> 
> python -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl
> 
> change to following on mac
> 
> python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.0-py3-none-any.whl
> 
> for Anaconda use corresponding conda

o m g u saved me an hour of googling! thankyouu
