### ISSUE TITLE
[Java][Suggestion] Add Enum with all Operations

### ISSUE THREAD

**Issue by mcenderdragon** [tensorflow/tensorflow#9685]
Currently it is hard for beginners to start with the Java API of TF. Mostly because the function names staed in the python tutorial do not apply to the Operation names used in Java. It would be nice if we had an Enum Containing all standart possible Operations.

`grapth.opBuilder(type, name)`

I am currently struggling to find out what the correct name of "Multiply" is.
I have digged my way thorgh the code and most of the operations are registered trought `REGISTER_OP` and I could trace down the java methods to ` TF_OperationDescription(TF_Graph* g, const char* op_type, const char* node_name)` in c_api_internal.h. But I absolutly dont know were the operations are storred. 

Also nice would be a table "python function name" to "internal operation name"

**Comment by eaplatanios** [comment]
Given that attribute names may also generally differ, the only "principled" way to do this would be to either automatically generate code for constructing ops (which can be ugly) or manually add functions that create all supported ops. The Python API currently uses a mixed approach. If you can be a little patient, I have been working on a Scala API that does that and adds a lot more of the Python API functionality (e.g., gradients). It's not ready to be released yet, but I will have a usable version soon. It is written Scala though and uses some "Scala-specific" features, but it shouldn't be hard to create a Java compatibility layer then.

**Comment by mcenderdragon** [comment]
ohh that would be great. It is currently realy annoing to not know what op names are. for example I could not find anything what "tf.global_variables_initializer" would be in java.

**Comment by drpngx** [comment]
@asimshankar for Java. 

The variables etc are registered in the graph. You'd need access to the collections from the Graph class, I believe.

**Comment by asimshankar** [comment]
As @eaplatanios pointed out, I don't think that an enum would be appropriate and code generation for all the operations (which happens for Python, C++ and Go right now) is the right way to go.

I believe @karllessard and @kbsriram are looking into this as part of resolving #7149, so I'm going to close this issue out and recommend comments/follow ups on #7149 instead.

Thanks!

**Comment by mcenderdragon** [comment]
But the method solution is much more complex and enums are the right way to do it, like OpenGL does it.

**Comment by asimshankar** [comment]
An enum might describe the list if operations, but we'd still need to describe all the inputs, their types, any attributes, default values - essentially all the contents of the [`OpDef` protocol buffer](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/op_def.proto) that is created with the `REGISTER_OP` macro calls, so merely listing out the operations without describing how to use them seems insufficient, no?

**Comment by mcenderdragon** [comment]
well enum cann do this in java do (we can give them an input definition as DataType array) and the Exceptions are helpfull so the hardest thing currently is guessing the name, if you have the name the excpetiuons tell you what you need.

**Comment by asimshankar** [comment]
I do believe that the code generation is the appropriate thing to do regardless, but yes, it will take time.

I'm not fully convinced about the value of the enum. Yes, it may help with discovery of operations, but once the code generation is in place, then that would be a better means of discovery? Note that operations can also be added at runtime (e.g., [Adding a New Op](https://www.tensorflow.org/extend/adding_an_op)), so the enum will not be sufficient.

That said, one minor change seems to be a pre-requisite for discovery whether using code generation or an enum. That would be to make  [`TF_GetAllOpList`](https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/c/c_api.h#L1136) available in the Java API, the output of which can be parsed into an [`OpList`](http://static.javadoc.io/org.tensorflow/proto/1.1.0/org/tensorflow/framework/OpList.html) Java object.

I'd be happy to add that. With it you should be able to generate your own enum if you want and if after using it you still feel convinced that it is appropriate, we could discuss the possibility of merging it in.

Sound fair?

**Comment by mcenderdragon** [comment]
Ok if you will add all this stuff then yeah the enum is pretty out of place and not needed. With alot of bloddy magic it is possible to add enum at runtime but a solution wiht methods is by far better.
