### ISSUE TITLE
request for updating readme in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/hvx

### ISSUE THREAD

**Issue by kzos** [tensorflow/tensorflow#9692]
OS: Ubuntu 16.04 64bits
Android Version: 7.1 (Nougat)
NDK Version: android-ndk-r10b
HEXAGON SDK: 3.1
nnlib source: https://source.codeaurora.org/quic/hexagon_nn/nnlib

Following steps to get tensorflow up on hexagon from `https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/hvx`
1) Please update `git clone https://source.codeaurora.org/quic/hexagon_nn/nnlib` with 
`git clone --recurse-submodules https://github.com/tensorflow/tensorflow.git` in the readme

2) tensorflow/contrib/makefile/downloads/protobuf/autogen.sh:

below autogen.sh is modified gmock ->(with) googlemock
as well gtest ->(with) googletest.

as `m4_include(../googletest/m4/acx_pthread.m4)` in `tensorflow/contrib/makefile/downloads/protobuf/googlemock/configure.ac` is referring to googletest.

```
if test ! -e googlemock; then
   echo "Google Mock not present.  Fetching gmock-1.7.0 from the web..."
   curl $curlopts -L -O https://github.com/google/googlemock/archive/release-1.7.0.zip
   unzip -q release-1.7.0.zip
   rm release-1.7.0.zip
   mv googlemock-release-1.7.0 googlemock
 
   curl $curlopts -L -O https://github.com/google/googletest/archive/release-1.7.0.zip
   unzip -q release-1.7.0.zip
   rm release-1.7.0.zip
   mv googletest-release-1.7.0 googlemock/googletest
 fi
```

please let me know gtest/gmock is getting reffered somewhere as it can be modified to googletest/googlemock in protobuf/autogen.sh

thanks.

**Comment by martinwicke** [comment]
This looks like it's an issue inside protobuf -- which itself is downloaded by the makefile. I'd file an issue with https://github.com/google/protobuf. 

Please comment to reopen if I misunderstood the issue.

**Comment by kzos** [comment]
sorry, I had mentioned only issue related to autogen.sh

There was this other one,

protobuf, googletest are getting downloaded under downloads folder,
 when build command is issued, `protoc missing error` as it expects googletest and googlemock to be present in specific order under protobuf, {debug info was not enough to catch this at first sight}.

just to make sure nobody gets stuck, please check information provided on readme is enough to get hexagon graph up and running.

thanks.
