### ISSUE TITLE
How to extract predictions

### ISSUE THREAD

**Issue by vkuznet** [tensorflow/tensorflow#97]
Hi, can someone either point to code example or documentation how to extract final predictions after the training the model. For example, it would be nice to complement existing tutorials, e.g. mnist, and show additional (final) step to get prediction out of the trained model.

**Comment by pannous** [comment]
# Test trained model
correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))

**Comment by abunsen** [comment]
+1

**Comment by vkuznet** [comment]
Hi,
well I see that step, but if I print the correct_prediction I got
Tensor("Equal:0", shape=TensorShape([Dimension(None)]), dtype=bool) which is
<class 'tensorflow.python.framework.ops.Tensor'>

and I want to get array of numbers (probabilities). My question is how to get
it from Tensor then?

**Comment by rafaljozefowicz** [comment]
Check this response on stackoverflow: https://stackoverflow.com/questions/33633370/how-to-check-the-contents-of-a-tensor-object-in-tensorflow

**Comment by pannous** [comment]
the array of numbers is returned by eval / run method:
```
prediction=tf.argmax(y,1)
print prediction.eval(feed_dict={x: mnist.test.images})
```

**Comment by vkuznet** [comment]
Thanks, this works if I pass session to eval too.
Here is working example for those who are interested:
```
import input_data
import tensorflow as tf
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)
x = tf.placeholder("float", shape=[None, 784])
W = tf.Variable(tf.zeros([784,10]))
b = tf.Variable(tf.zeros([10]))
y = tf.nn.softmax(tf.matmul(x,W) + b)
y_ = tf.placeholder("float", shape=[None, 10])
cross_entropy = -tf.reduce_sum(y_*tf.log(y))
train_step = tf.train.GradientDescentOptimizer(0.01).minimize(cross_entropy)
# train data and get results for batches
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init)
# train the data
for i in range(10):
    batch_xs, batch_ys = mnist.train.next_batch(100)
    sess.run(train_step, feed_dict={x: batch_xs, y_: batch_ys})
correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
print "accuracy", sess.run(accuracy, feed_dict={x: mnist.test.images, y_: mnist.test.labels})
prediction=tf.argmax(y,1)
print "predictions", prediction.eval(feed_dict={x: mnist.test.images}, session=sess)
```

**Comment by vkuznet** [comment]
My next question is how to get probabilities of predictions?

**Comment by pannous** [comment]
just y or y/sum(y)

**Comment by vkuznet** [comment]
thanks, it works

```
probabilities=y
print "probabilities", probabilities.eval(feed_dict={x: mnist.test.images}, session=sess)
```

**Comment by pannous** [comment]
hold on, you need to norm it per dimension
i.e.
y=[[0.8,0.5,0.1],[0.1,0.2,0.4]]
probabilities=y/[1.4,0.7]

**Comment by rafaljozefowicz** [comment]
The output of the tf.nn.softmax(.) should already be normalized so it should just work

**Comment by pannous** [comment]
In this case yes, but it doesn't harm if we put the general solution here.

**Comment by danielzak** [comment]
Expanding on the above question, when I try the above suggestion (which works fine for the mnist softmax example) on the mnist convnet example I get the following error:

    tensorflow.python.framework.errors.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_2' with dtype float

I have just copied the code from http://www.tensorflow.org/tutorials/mnist/pros/index.md and added the following four lines:
```
...
prediction=tf.argmax(y_conv,1)
print "predictions", prediction.eval(feed_dict={x: mnist.test.images}, session=sess)

probabilities=y_conv
print "probabilities", probabilities.eval(feed_dict={x: mnist.test.images}, session=sess)
```

Anyone knows what this is?

**Comment by danielzak** [comment]
I can answer my own question

The convnet example has an additional variable in the feed_dict, I missed to add that. In this case the feed_dict should look like this: `feed_dict = {x: [your_image], keep_prob: 1.0}`

**Comment by vrv** [comment]
Closing -- looks like these issues are resolved.  Please re-open if there's something else to do here.

**Comment by gnujimmik** [comment]
I have read all the threads here and got another question. I am currently using 

`with tf.Graph().as_default():
    ...
    probability = tf.nn.softmax(logits)
`

In this case how shall I print out or save the probability value in csv format?


Thank you in advance!

**Comment by rohitchopra32** [comment]
i have some code like this
> run_fc.py

```
# Define input placeholders
images_placeholder = tf.placeholder(tf.float32, shape=[None, IMAGE_PIXELS],  name='images')
labels_placeholder = tf.placeholder(tf.int64, shape=[None], name='image-labels')

# Operation for the classifier's result
logits = two_layer_fc.inference(images_placeholder, IMAGE_PIXELS,
  FLAGS.hidden1, CLASSES, reg_constant=FLAGS.reg_constant)

# Operation for the loss function
loss = two_layer_fc.loss(logits, labels_placeholder)

# Operation for the training step
train_step = two_layer_fc.training(loss, FLAGS.learning_rate)

# Operation calculating the accuracy of our predictions
accuracy = two_layer_fc.evaluation(logits, labels_placeholder)

```

> two_layer_fc.py:


```
def evaluation(logits, labels):
  '''Evaluates the quality of the logits at predicting the label.

  Args:
    logits: Logits tensor, float - [batch size, number of classes].
    labels: Labels tensor, int64 - [batch size].

  Returns:
    accuracy: the percentage of images where the class was correctly predicted.
  '''

  with tf.name_scope('Accuracy'):
    # Operation comparing prediction with true label
    correct_prediction = tf.equal(tf.argmax(logits,1), labels)

    # Operation calculating the accuracy of the predictions
    accuracy =  tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

    # Summary operation for the accuracy
    tf.summary.scalar('train_accuracy', accuracy)

  return accuracy

```
i want when evaluation funtion that is in 

> two_layer_fc.py file

 find out correct_prediction  after that it will show the predicted label and label that is in labels (original label)

i tried this adding this:

> prediction=tf.argmax(y,1)
> print prediction.eval(feed_dict={x: mnist.test.images})

it only gives me error.

**Comment by KathiravanNatarajan** [comment]
Hi, Can you please check this issue ? https://stackoverflow.com/questions/45225071/exporting-tensorflow-prediction-to-csv-but-the-result-contains-all-zeros

**Comment by AKlent** [comment]
Hi, I am following the Tensorflow's "Layer Module" from this tutorial link https://www.tensorflow.org/tutorials/layers. I find the code here different from the one you have mentioned above. You might be able to help me how can I get the results of the predictions and its respective probabilities.
I need to see it for further understanding the model. And if there is a way I can save the results - predictions and probabilities to csv.

Thank you so much for your time.

**Comment by timmolter** [comment]
Using the Estimator API, I figured out how to extract the predictions and create a confusion matrix. Maybe it will help someone else out.

https://github.com/knowm/HelloTensorFlow/blob/master/src/iris_DNN_classifier.py

```
predicted_classes = [p["class_ids"][0] for p in predictions]
print(
    "Test Samples, Class Predictions:    {}\n"
    .format(predicted_classes))
```

**Comment by shadzic** [comment]
Thank you, very helpful.

For the DNNLinearCombinedClassifier, I used this:
`
# predicted class
predictions = model.predict(input_fn=input_fn)
y_pred = [p["class_ids"][0] for p in predictions] 

# probability of being predicted as 1
predictions = model.predict(input_fn=input_fn)
y_prob = [p["probabilities"][1] for p in predictions]
`

Weirdly, I need to re-compute predictions every time to get the lists 
(y_prob would return [] if I don't re-run predictions before running y_prob)

**Comment by ASWATHISATHEESH** [comment]
y_output = vqa_model.predict([question_features, image_features])
NameError: name 'question_features' is not defined

what would be the solution

**Comment by BoomPakorn** [comment]
why my output is 

`prediction = tf.argmax(model.prediction, 1)
        print("predictions", prediction.eval(feed_dict={image: db.test.images, label: db.test.labels, dropout: 1.0}, session=sess))`

Output : 
`predictions [0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0
 1 0 0 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0
 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 0 0 1 1 0 1 0 1 0 1 1 1 0 0 0 1 1 0 0 1
 1 0 1 1 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0
 1 1 1 1 0 1 1 0 0 0 1 0 1 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0
 0 0 0 1 1 0 0 0 0 0 0 1 0 1 1 1 0 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 1 1 1 0
 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 0
 0 1 1 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0
 0 0 1 0 1 1 0 1 1 1 0 0 0 0 0 1 0 1 0 0 0 1 0 1 0 1 1 1 1 0 0 0 0 0 1 0 0
 0 1 1 0 0 1 0 1 1 0 1 0 1 0 0 1 0 1 1 0 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 0 0
 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 1 0 0 1 0 0 1 1 0 0 1 0 0 0 0 1 1 1 0 0 0
 1 1 0 0 0 0 0 1 1 0 1 1 1 1 1 1 0 1 0 1 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 1
 1 0 0 0 0 1 1 0 0 1 0 1 0 0 1 1 1 0 0 0 0 0 1 0 0 1 1 1 1 0 0 0 1 0 1 0 1
 0 1 0 1 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1
 0 0 0 1 1 1 0 1 0 0 1 1 1 1 0 0 1 0 1 0 0 0 0 0 1 1 1 0 0 1 1 1 0 1 0 0 1
 0 0 1 1 0 1 1 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0
 0 1 1 0 1 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 1 0 0 0 1 1
 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 1 1 1 1 1
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0
 0 0 1 1 1 1 0 1 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 1 1 0 1 0 0 1 1 1 0 0 1
 0 0 0 0 1 1 0 1 0 1 0 1 0 1 1 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1]`

**Comment by deepikaverma07** [comment]
probabilities= []
# in the prediction loop
##
        probabilities.append(np.max(y.eval(feed_dict={x: [test_set]}, session=sess), axis=1)[0])
