### ISSUE TITLE
Work nvidia-docker rather than using custom docker start script

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#970]
Right now the docs recommend using a [custom start command](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker#running-the-container) ([or here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#docker-installation)) rather than using the [`nvidia-docker` program published by nvidia](https://github.com/NVIDIA/nvidia-docker). I suggest having the image work with the more standardized approach to starting docker containers with nvidia support.

See: https://github.com/tensorflow/tensorflow/issues/808#issuecomment-175934093.

**Comment by craigcitro** [comment]
I agree that getting the container started with GPU support still isn't the smoothest experience, especially when it comes to matching library versions. That said, I feel like "now go read the nvidia wiki and install this extra package" has its own tradeoffs as a getting started experience.

Probably the thing to do here is clear up the instructions:
1. make sure to clearly route people to either `docker_run_gpu.sh` or the NVidia docker plugin, and
2. add a few diagnostic steps (eg "here's how you run `deviceQuery` ...") for troubleshooting.

@ebrevdo do you have time to take a look at this?

**Comment by jendap** [comment]
I would not rush it. I have spend a couple of hours with nvidia-docker two weeks ago. I have tried to use it for ci.tensorflow.org. It was not fun. I would not recommend that at this time. It would, imho, make more harm than good.

Simply try to install latest stable drivers. Check you have /dev/nvidia0, /dev/nvidiactl and /dev/nvidia-uvm outside docker and that you have /usr/lib/x86_64-linux-gnu/libcudart.so and /usr/lib/x86_64-linux-gnu/libcuda.so. If so the docker_run_gpu.sh script should work.

BTW: I believe docker and cuda together will get better. But it is not going to be a great experience any time soon if ever.

**Comment by cancan101** [comment]
I would be curious to know more about what were the issues that you had with `nvidia-docker` that took a few hours. The program "just worked for me". The one caveat I would add is they rewrote the program ~ Jan 1 and also changed the base CUDA docker images (same images that TF extends for GPU). I think there are issues if you mix and match old images and new `nvidia-docker` or vice versa.

Otherwise, using new versions of both, my experience has been great. I just run `nvidia-docker run` and it sets the volumes and devices.

Also the `docker_run_gpu.sh` does not seem to work for example when the CUDA SO's are not found in `/usr/lib/x86_64-linux-gnu/` which is the case for one of the boxes my company has.

**Comment by cancan101** [comment]
I rebuilt my TF image against the updated nvidia base images. `nvidia-docker` still does not work out of the box. Running this within the container seems to work: `ln -s /usr/local/nvidia/lib64/libcuda.so.1 /usr/lib/x86_64-linux-gnu/libcuda.so`

**Comment by 3XX0** [comment]
I mentioned it [here](https://github.com/tensorflow/tensorflow/issues/808/#issuecomment-180228698),  this is an issue with Tensorflow not loading the libcuda soname.

**Comment by craigcitro** [comment]
I think @3XX0 is on the right track here -- in fact, at some point long ago @ebrevdo and I hit something like this and worked around it by creating that same symlink. Eugene, did we work around that at some point, or just leave the symlink intact and forget?

In any event, it seems like an easy thing to add in the container?

**Comment by ruffsl** [comment]
+1
(side note, @craigcitro , did you see flx42's comment https://github.com/NVIDIA/nvidia-docker/issues/45#issuecomment-185444991, might want to rebuild with the refreshed images to get the security fix for glibc)

**Comment by jendap** [comment]
nvidia-docker is a good idea but not working too well. I was trying it today again. It fails with no error message. Going without it there are at least errors to solve and get to a working state. I will report some bugs to nvidia-docker once I have time for it.

The 0.7 release had some issues so there will soon be a bugfix 0.7.1. It will go also with upgraded cuda and cudnn https://github.com/tensorflow/tensorflow/pull/1166.

@cancan101 How does it work with the symlink? nvidia-docker is working for some people but it require to create that symlink? Inside of the container? If so we can just add it to the container tomorrow :-)

BTW: Security? No big deal for something like this image. If anybody care about security they run apt-get update & upgrade any now and again anyway.

**Comment by jendap** [comment]
Interesting. For whatever reason yet another try the same way and this time nvidia-docker worked! Nice. Sort of... The example nnvidia-smi run well, but tensorflow tests have failed!!!

It did not seem te require any link inside nor outside the container.

**Comment by cancan101** [comment]
@jendap:
```
nvidia-docker run -v /tmp/cifar10_data:/tmp/cifar10_data -it 4catalyzer/tensorflow:latest-devel-gpu-aws bash -c 'ln -s /usr/local/nvidia/lib64/libcuda.so.1 /usr/lib/x86_64-linux-gnu/libcuda.so && python /usr/local/lib/python2.7/dist-packages/tensorflow/models/image/cifar10/cifar10_multi_gpu_train.py'
```

**Comment by jendap** [comment]
That's not official container...

We will make sure the 0.7.1 will run on gpu. I'm happy to put the symlink inside the container. On the other hand the next development container (after https://github.com/tensorflow/tensorflow/pull/1166) seems to be fine without the link. But I have tried that after upgrading the base containers and stuff.

**Comment by cancan101** [comment]
Sure that is not official though I did build it off the Dockerfile from yesterday.

**Comment by 3XX0** [comment]
Adding a symlink inside the container is a workaround, those symlinks should only be there for development purposes. Also, if the CUDA ABI breaks you will run into troubles.

I'm pretty sure the only change required is adding `.1` [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/stream_executor/dso_loader.cc#L72).
It's already done correctly for the other CUDA libraries I guess you just missed this one.

**Comment by vrv** [comment]
Yep, an oversight. I'll send a fix.

**Comment by jendap** [comment]
Maybe. I can try it for open source build as well as internally.

I'm not sure if the link is needed anymore but I'm going to put it into 0.7.1 release just to avoid problems.

**Comment by jendap** [comment]
Perfect! Thanks @vrv!

**Comment by jendap** [comment]
.1 was added in https://github.com/tensorflow/tensorflow/commit/d0a822fbcb04d95a643d8efe65699a8d1cdce98b

**Comment by 3XX0** [comment]
I just tested and there is still a small issue if you use the development Docker image.
The devel image [overrides LD_LIBRARY_PATH](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.devel-gpu#L99) therefore you need to run `ldconfig` before running tensorflow.
 
Note that this line is not needed because we already set `LD_LIBRARY_PATH` in our CUDA images: https://github.com/NVIDIA/nvidia-docker/blob/master/centos-7/cuda/7.5/runtime/Dockerfile#L37
So removing it should do the trick!

The Tensorflow "runtime" image is not affected.

**Comment by jendap** [comment]
That makes sense. Thank you @3XX0!

Note: If you want to work on tensorflow you may take a look at [ci_build](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build).

**Comment by 3XX0** [comment]
Sorry to bump this issue, but the new 7.1 runtime Docker image fails to find cuDNN probably because it hasn't been configured properly. See @flx42 [comment](https://github.com/tensorflow/tensorflow/issues/808#issuecomment-187931361)

**Comment by ruffsl** [comment]
I'd like to second @3XX0 's bump, this issue still persists in the current `b.gcr.io/tensorflow/tensorflow:latest-gpu` image.

``` terminal
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:99] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:
I tensorflow/stream_executor/cuda/cuda_dnn.cc:1407] Unable to load cuDNN DSO
...
F tensorflow/stream_executor/cuda/cuda_dnn.cc:204] could not find cudnnCreate in cudnn DSO; dlerror: /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cudnnCreate
[I 16:47:11.347 NotebookApp] KernelRestarter: restarting kernel (1/5)
```
Surprising that this has gone untended for so long.

**Comment by girving** [comment]
@craigcitro, @jendap: If nvidia-docker is not ideal, should we close this issue?

**Comment by flx42** [comment]
@girving actually, it's the recommend method now for GPU containers:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker#running-the-container

**Comment by girving** [comment]
@flx42: Even better!  Does that mean this bug is fixed?

**Comment by flx42** [comment]
Looks like, but that's not my call :)

**Comment by jendap** [comment]
yeah, it is recommended only in that one file, because I was just updating that file a few days back. We should update all the places. I'm thinking about doing it tomorrow - so that it makes it into 0.9.

**Comment by cancan101** [comment]
What commit was this fixed in?
