### ISSUE TITLE
Installation instructions for conda install tensorflow in the root environment

### ISSUE THREAD

**Issue by janLuke** [tensorflow/tensorflow#9702]
The [instructions](https://www.tensorflow.org/install/install_linux#InstallingAnaconda) say to 
1. create a new **empty** environment 
2. activate it
3. install tensorflow via pip. 

But pip is not installed in the new environment, so the third command will call the first pip inside the PATH system variable, that usually is the pip installed in the root conda environment. The ultimate result is that tensorflow is installed in the root environment.

To solve this issue, it's sufficient to install pip in the new environment:
`conda create --name tensorflow pip`

**Comment by donigian** [comment]
I ran into this issue as well, please review my [PR](https://github.com/tensorflow/tensorflow/pull/13554) for fix.

**Comment by wolffg** [comment]
This PR has been merged.  I'm closing this.
