### ISSUE TITLE
atrous_conv2d does not support NCHW format

### ISSUE THREAD

**Issue by agupta74** [tensorflow/tensorflow#9705]
Any plans to support NCHW format for atrous_conv2d?  As per the performance guidelines on TensorFlow website,  ops using NCHW format is faster than NHWC format for GPUs.

**Comment by drpngx** [comment]
That seems like a fine contribution to have if you're up for it.

@gpapan @martinwicke

**Comment by liuhyCV** [comment]
@drpngx Hi, I have check it in r1.3 python API, and find it haven't support NCHW format. I'm interesting in contrib it. I'm familiar with dilated/atrous conv use and principle, but I haven't contrib before in tensorflow. Is it a good question for beginner contrib ?

**Comment by drpngx** [comment]
@martinwicke any suggestion?

**Comment by tilakrayal** [comment]
@agupta74,
**Atrous** convolution allows us to explicitly control how densely to compute feature responses in fully convolutional networks. Used in conjunction with bilinear interpolation, it offers an alternative to **conv2d_transpose** in dense prediction tasks such as semantic image segmentation, optical flow computation, or depth estimation. It also allows us to effectively enlarge the field of view of filters without increasing the number of parameters or the amount of computation

`atrous_conv2d(value, filters, rate, padding=padding)`

value | A 4-D Tensor of type float. It needs to be in the default "NHWC" format. Its shape is [batch, in_height, in_width, in_channels].
-- | --

https://www.tensorflow.org/api_docs/python/tf/nn/atrous_conv2d
Thank you!
