### ISSUE TITLE
Expose TensorFlow build details

### ISSUE THREAD

**Issue by delip** [tensorflow/tensorflow#971]
Requesting addition of API method(s) to enable programmatic checking of TensorFlow version and other build capabilities (such as if TF was compiled with GPU support, for eg.). I would find this useful in deployment scripts that operate in foreign TensorFlow environments.

**Comment by girving** [comment]
From the email thread: what we have so far is `tf.__version__` and the various GraphDef version numbers (`tf.GRAPH_DEF_VERSION` and such).  GPU support and exact commit would be useful.

**Comment by evanthebouncy** [comment]
>>> import tensorflow as tf
>>> tf.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute '__version__'

Am I on an old version without the version feature or something?

**Comment by martinwicke** [comment]
Editing title to reflect the focus.

**Comment by girving** [comment]
@martinwicke: Would you prefer contributions welcome or assigned to you?

**Comment by yifeif** [comment]
Do we plan to add more build details or this can be closed?

**Comment by aselle** [comment]
I think whether GPU support is included is the only major thing not available that we might want to add.

**Comment by aselle** [comment]
This is already possible, see e.g.
https://stackoverflow.com/questions/38559755/how-to-get-current-available-gpus-in-tensorflow
Closing this issue for now.
