### ISSUE TITLE
eval() error about variable_scope()

### ISSUE THREAD

**Issue by frischzenger** [tensorflow/tensorflow#9711]
I run the code from official tutorial:
https://www.tensorflow.org/programmers_guide/variable_scope

```
with tf.variable_scope("foo", initializer=tf.constant_initializer(0.4)):
    v = tf.get_variable("v", [1])
    assert v.eval() == 0.4  # Default initializer as set above.
    w = tf.get_variable("w", [1], initializer=tf.constant_initializer(0.3))
    assert w.eval() == 0.3  # Specific initializer overrides the default.
    with tf.variable_scope("bar"):
        v = tf.get_variable("v", [1])
        assert v.eval() == 0.4  # Inherited default initializer.
    with tf.variable_scope("baz", initializer=tf.constant_initializer(0.2)):
        v = tf.get_variable("v", [1])
        assert v.eval() == 0.2  # Changed default initializer
```
**the problem as below**:
Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

```
with tf.Session():
    with tf.variable_scope("foo", initializer=tf.constant_initializer(0.4)):
        v = tf.get_variable("v", [1])
        assert v.eval() == 0.4  # Default initializer as set above.
        w = tf.get_variable("w", [1], initializer=tf.constant_initializer(0.3))
        assert w.eval() == 0.3  # Specific initializer overrides the default.
        with tf.variable_scope("bar"):
            v = tf.get_variable("v", [1])
            assert v.eval() == 0.4  # Inherited default initializer.
        with tf.variable_scope("baz", initializer=tf.constant_initializer(0.2)):
            v = tf.get_variable("v", [1])
            assert v.eval() == 0.2  # Changed default initializer
```

**when i try with session the problem changed as below:**

Attempting to use uninitialized value foo/v

	 [[Node: foo/v/_0 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_4_foo/v", _device="/job:localhost/replica:0/task:0/gpu:0"](foo/v)]]

this problem in both windows and linux
the platform is :
windows10 , python3.5 , tf.__version__ 0.12.1
ubuntu, python2.7  , tf.__version__  1.1.0-rc2

how can I solve this problem?

**Comment by drpngx** [comment]
You're on the right tarck!

I tend to use: `with tf.Session() as sess` rather than a default session. After that, you need to use `sess.run(tf.global_variables_initializer())` and it should work.

This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
