### ISSUE TITLE
[inputs] instead of inputs for rnn_cell?

### ISSUE THREAD

**Issue by yhg0112** [tensorflow/tensorflow#9715]
In current rnn_cell implementation, It gets inputs as 2-d tensor for cell inputs,

Hence embedding layer before the actual rnn_cell gets a little bit annoying for making 'decoder'.

I really like the "wrapper" concept in current implementation that expand by each layer with embedding, residual net, or dropouts. 

If rnn_cell gets list of '2-d' tensor like [inputs1, inputs2, ...], then the concept of wrapper can be fully used in decoder as well as simple rnn or encoder;

for a little more concretely, 
if "embedding wrapped cell" gets input list [inputs, context_inputs_from_attention],
then the "embedding wrapped cell" can just pass [embedded_inputs, context_inputs_from_attention] to the real "LSTM_cell" and "LSTM_cell" can weight sum those inputs in inputs list.

what do you think about this idea?

**Comment by drpngx** [comment]
@ebrevdo does that make sense?

@yhg0112 would you be willing to send a PR?

**Comment by ebrevdo** [comment]
Does the new attention + decoder API in tf.contrib.seq2seq (in the
nightlies) do what you want?

It seems like what you're currently proposing is a pretty major overhaul of
the LSTM and embedding wrapper APIs that would not be backwards
compatible.  I think we try to avoid doing this in the new AttentionWrapper
in tf.contrib.seq2seq, and provide a variety of decoding mechanisms there
as well.

**Comment by yhg0112** [comment]
do you mean BeamSearchDecoder in tf.contrib.seq2seq.python.ops ? 
This do the job yet require "embedding" outside the "cell" (same as attention_decoder in legacy_seq2seq). 
i was thinking that this is kind of Not in the OOP because we had the embeddingWrapper for RNN cells.

i'll make the pull request about next month. and i'm closing this issue for now will reopen when i'm ready to submit the PR.
