### ISSUE TITLE
applying different batch_sizes for each buckets in bucketd_rnn?

### ISSUE THREAD

**Issue by yhg0112** [tensorflow/tensorflow#9716]
I've found an obvious fact that, in seq2seq model with buckets(especially in NMT applications), the shorter buckets takes extremely smaller memory size in GPU than the longer buckets in same batch_size in both training and inferencing; i.e 64 sentences for (5, 10) takes extremely smaller memory size than 64 sentences for (30, 40).

Then why don't we have different bucket sizes for each bucket? 

Actually i've run my experiments in these way and it really helps cutting down my training time.

There may be some issues in having different bucket sizes like sampling frequency for each buckets, the issue from recent paper in ICLR that claiming the smaller batch size make the model better in generalization, etc...

Yet, my preemptive concern was the training time so i managed different batch sizes like 1024 sentences for (5, 10) bucket and 64 sentences for (30, 40) bucket that maximize my GPU's utility.

(absolutely this cannot be done with dynamic_rnn structure.)

what do you guys think about this idea?

**Comment by concretevitamin** [comment]
Sorry, I don't exactly follow what the specific questions here are.  The ideas you describe are perfectly reasonable, and I think they are widely applied in the context of sequence models.  Are you trying to file a specific bug against some RNN implementation in TensorFlow?

**Comment by yhg0112** [comment]
no, this was not a question or feature request.

i'm just opening a discussion thread curious about what others thinking.

i guess this wasn't appropriate in this community and closing the thread.

**Comment by concretevitamin** [comment]
@yhg0112 Thanks.  As mentioned I think using different batch sizes for different buckets is totally reasonable.  People usually analyze the sequence lengths over the training set, and could cut off at, say, 20%, 40%, ..., 80%-tiles, etc.
