### ISSUE TITLE
feature request: support placeholder for parameter k in tf.nn.in_top_k

### ISSUE THREAD

**Issue by soloice** [tensorflow/tensorflow#9717]
Currently [`tf.nn.in_top_k`](https://www.tensorflow.org/api_docs/python/tf/nn/in_top_k) requires an int as `k`, while [`tf.nn.top_k`](https://www.tensorflow.org/api_docs/python/tf/nn/top_k) does support a 0-D int32 Tensor as parameter `k`. This is kind of inconsistent and inconvenient.

Is it possible to allow `k` to be a 0-D int32 Tensor in `tf.nn.in_top_k`?

**Comment by drpngx** [comment]
Yes, it should be [supported](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/topk_op.cc#L37).

I think it's just a matter of removing `k=` in the [code](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/nn_ops.py#L1946).

@girving WDYT?

**Comment by girving** [comment]
Yes, this requires a similar `InTopKV2` op to the `TopKV2` op I added.

@soloice Would be up for submitting a PR?

**Comment by soloice** [comment]
@girving Okay, I'll have a try.

**Comment by girving** [comment]
Thanks!  Let me know if you have questions.

**Comment by yongtang** [comment]
Added a PR #11197 for this issue.

**Comment by soloice** [comment]
@yongtang Thanks for your contribution. I'm kind of busy these days and almost forget this issue...
