### ISSUE TITLE
compile error C2064 when I use cmake(vs2015) to make windows binary

### ISSUE THREAD

**Issue by hujunyao** [tensorflow/tensorflow#9718]
I follows the instructions (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake  ) to compile the tensorflow in windows ( compiler vs2015)

I use 
    cmake .. -A x64 -DCMAKE_BUILD_TYPE=Release -DSWIG_EXECUTABLE=D:/swigwin-3.0.12/swig.exe -DPYTHON_EXECUTABLE="D:/Program Files/Python 3.5/python.exe" -DPYTHON_LIBRARIES="D:/Program Files/Python 3.5/libs/python35.lib" -Dtensorflow_ENABLE_GPU=OFF -Dtensorflow_ENABLE_GRPC_SUPPORT=OFF  -Dtensorflow_WIN_CPU_SIMD_OPTIONS=/arch:AVX
to generate project files.

after: MSBuild /p:Configuration=Release tf_tutorials_example_trainer.vcxproj

it complains following :

[in Chinese , the cl output]
h:\tensorflow_c\tensorflow-1.1.0\tensorflow\core\lib\gtl\array_slice_internal
.h(89): error C2064: 项不会计算为接受 0 个参数的函数 (编译源文件 H:\tensorflow_c
\tensorflow-1.1.0\tensorflow\core\lib\strings\str_util.cc) [H:\tensorflow_c\tensorflow-1.1.0\tensorflow\contrib\cmake\build_vc\tf_core_lib.vcxproj]

[in English ]
h:\tensorflow_c\tensorflow-1.1.0\tensorflow\core\lib\gtl\array_slice_internal
.h(89): error C2064: term does not evaluate to a function taking 0 arguments ( compiling  H:\tensorflow_c
\tensorflow-1.1.0\tensorflow\core\lib\strings\str_util.cc) [H:\tensorflow_c\tensorflow-1.1.0\tensorflow\contrib\cmake\build_vc\tf_core_lib.vcxproj]

**Comment by drpngx** [comment]
CC @guschmue @mrry 

The error is in the array slice implementation. We'd like to see the call site. Could you put the full compiler log in pastebin?

**Comment by hujunyao** [comment]
I find the bugs come from the vs2015. When I update the vs2015 to vs2015update3 version , It compiles OK.
I suggest that the instructions ( (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake )  need to emphasize the use of **vs2015 update3**

**Comment by drpngx** [comment]
Thanks! Could you send a PR with the change to the MD file?

**Comment by guschmue** [comment]
yes, needs to be update3 for sure. I thought this was in the README.md but just checked - really not there.
