### ISSUE TITLE
Feature request: Add 'axis' option for 'tf.boolean_mask()'

### ISSUE THREAD

**Issue by Cooper-Yang** [tensorflow/tensorflow#9721]
`tf.boolean_mask()` is extremely useful when it comes to training.

However, the present `tf.boolean_mask()` does not have an `axis` option, thus masking some specific dimension of an array could be troublesome. 

Appreciate your consideration.

**Comment by girving** [comment]
This is a good feature request, but unfortunately it's blocked by the fact that gather is also missing an axis parameter.

**Comment by yongtang** [comment]
Added a PR #9721 for `axis` support of `boolean_mask()` as now `gather` supports `axis` through (#11223)
