### ISSUE TITLE
How to know which will be supported wheel for my platform? (Installing Tensorflow)

### ISSUE THREAD

**Issue by sudhirshahu51** [tensorflow/tensorflow#9722]
C:\Users\Sudhit>pip install --ignore-installed --upgrade https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.1.0-cp35-cp35m-win_amd64.whl
tensorflow-1.1.0-cp35-cp35m-win_amd64.whl is not a supported wheel on this platform.

how will I know which will be supported wheel for my platform?

**Comment by drpngx** [comment]
@yifeif could you clarify? If it's not already in the docs, maybe we can improve there.

**Comment by iysaleh** [comment]
I ran into this error while attempting to install Tensorflow ... For me it was because I was trying to install Tensorflow in Windows with Python 3.6 ... Tensorflow only supports Python3.5!

**Comment by yifeif** [comment]
@sudhirshahu51 , you can check what wheel tags are compatible on your system with the following command:
`python -c "from pip import pep425tags;print(pep425tags.supported_tags)"`, or python3. 

We don't plan to add this to our doc as this should be strictly following pep425 standard.

**Comment by sudhirshahu51** [comment]
@yifeif thanx for this and can I know what features of Laptop do this supported tags depend upon as in my case I am finding it to be python2 and py27

**Comment by Mach10z** [comment]
reinstall tensorflow based on python 3.5xx and not 3.6 which is the default for anaconda
http://www.stefangordon.com/install-tensorflow-in-anaconda-on-windows/

**Comment by hemrajgithub** [comment]
Thanks @yifeif

**Comment by SofiaAmel** [comment]
@yifeif  it doesn't work for me :/

**Comment by yifeif** [comment]
@SofiaAmel what error/issue are you getting?

**Comment by SofiaAmel** [comment]
@yifeif  the issue was " this wheel is not compatible with the platform " , but now evrything is working ! I downgrade my TF version with pip install tensorflow==1.6 and it works , I did the same for TensorBoard, but unfortunately I'm having a new issue, and it's about prediction , it's in the picture below, I'll be grateful if you can help. thanks in advance
![image](https://user-images.githubusercontent.com/25504507/39185900-10518ce4-47c9-11e8-9b56-389280b897d3.png)

**Comment by bjuberchaub** [comment]
Same issue here -- When installing on ARMv7l platform:
    pip install tensorflow-1.9.0rc0-cp34-none-linux_armv7l.whl 
    tensorflow-1.9.0rc0-cp34-none-linux_armv7l.whl is not a supported wheel on this platform.
My pep425 tags are as follows (thank you @yifeif!):
    [('cp35', 'cp35m', 'linux_armv7l'), ('cp35', 'abi3', 'linux_armv7l'), ('cp35', 'none', 'linux_armv7l'),
     ('cp34', 'abi3', 'linux_armv7l'), ('cp33', 'abi3', 'linux_armv7l'), ('cp32', 'abi3', 'linux_armv7l'), 
     ('py3', 'none', 'linux_armv7l'), ('cp35', 'none', 'any'), ('cp3', 'none', 'any'), ('py35', 'none', 'any'),
     ('py3', 'none', 'any'), ('py34', 'none', 'any'), ('py33', 'none', 'any'), ('py32', 'none', 'any'), 
     ('py31', 'none', 'any'), ('py30', 'none', 'any')]
Doesn't ('cp34', 'abi3', 'linux_armv7l') match the wheel?  The target OS is Rasbian stretch.  The wheel is from http://ci.tensorflow.org/view/Nightly/job/nightly-pi-python3/.  Many thanks for your input!

**Comment by luuil** [comment]
@nikisalli @yifeif @SofiaAmel 
Try this one(pip18, python3.6.6):
`python3 -c "import wheel.pep425tags as w; print(w.get_supported())" | sed -zE 's/\),/),\n/g'`

**Comment by maranov** [comment]
Here's my modification, for those who found this via web search:
```
python -c "import wheel.pep425tags as w; print('\n'.join(['-'.join(p) for p in w.get_supported()]))"
```

**Comment by forstar2001** [comment]
reinstall tensorflow based on python 3.5xx and not 3.6 which is the default for anaconda
http://www.stefangordon.com/install-tensorflow-in-anaconda-on-windows/

**Comment by momonenet** [comment]
pygame-2.1.0: pygame version
-cp39-cp39-: python version
win32.: system 32bit
whl: file type
type python to get info .
It maybe works.
