### ISSUE TITLE
Tensorflow searching for outdated version of cudnn64_6.dll (Import Error)

### ISSUE THREAD

**Issue by iysaleh** [tensorflow/tensorflow#9735]
So I tried my first install of tensorflow-gpu on Window 7x64 with a GTX1080 and was met with a DLL import error python exception that wasn't very helpful at all (that message needs to be updated to indicate what DLL it can't find!).

Anyways, I decided to attempt the import tensorflow function with proc_mon watching all the file I/O from python... Turns out, Tensorflow is searching for 'cudnn64_5.dll' ... The latest 'cudnn-8.0-windows7-x64-v6.0' installs the following dll: 'cudnn64_6.dll' ... By copying the newer DLL to the DLL name that tensorflow expects, I was able to get past this issue and run tensorflow.

Tensorflow needs to be updated to support the latest cudnn64_6 dll that NVidia provides by default.

**Comment by drpngx** [comment]
Thanks @iysaleh, noted.

**Comment by iysaleh** [comment]
[...cuda_dnn.cc:352] Loaded runtime CuDNN library: 6021 (compatibility version 6000) but source was compiled with 5105 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.

I got the above error just now ... looks like just tricking it to use the newer library wasn't enough... I guess I'll try to install an older version until this is resolved.

**Comment by AllenIverSunn** [comment]
Hello man, I am looking for cudnn64_6.dll, can you send me an address where  I can down it? Thank you

**Comment by iysaleh** [comment]
cudnn64_6.dll is included with 'cudnn-8.0-windows7-x64-v6.0' (as stated in the original description).

To get it, download that version of cudnn from the NVidia website: https://developer.nvidia.com/cudnn

**Comment by AllenIverSunn** [comment]
Thank you man

2017-09-13 3:07 GMT+08:00 iysaleh <notifications@github.com>:

**Comment by mrry** [comment]
Closing this because the DLL not found error has been improved to indicate what DLL is missing.
