### ISSUE TITLE
OpenCL support for Window

### ISSUE THREAD

**Issue by twatasf7** [tensorflow/tensorflow#9738]
Scheduled to be compatible with OpenCL for Window
Currently bazel and cmake can not build on OpenCL on Windows
Is there no plan to support OpenCL on Windows?
If so, when will the period be?

**Comment by drpngx** [comment]
@benoitsteiner and @lukeiwanski may be able to comment.

**Comment by lukeiwanski** [comment]
Hi @twatasf7 
We are planning on releasing windows support soon ( cannot give an exact date yet )

**Comment by twatasf7** [comment]
@lukeiwanski 
That's great. Thank you

**Comment by pasikon** [comment]
Hi @lukeiwanski 
Any updates on that? Thanks!
