### ISSUE TITLE
Feature request: distance between each pair of the two collections of inputs. Analog of scipy.spatial.distance.cdist

### ISSUE THREAD

**Issue by salvador-dali** [tensorflow/tensorflow#9745]
is it possible to add a function to calculate a distance between each pair of the two collections of inputs. Scipy has it implemented in [distance.sdist](https://docs.scipy.org/doc/scipy/reference/generated/generated/scipy.spatial.distance.cdist.html) and supports many distance metrics.

Is it possible to have this function in TF? I have made an implementation for [Eucledian distance](http://stackoverflow.com/a/43839605/1090562) but have no idea how to implement it for other metrics.

**Comment by girving** [comment]
This seems a bit baroque for inclusion in TensorFlow.  Implementing the other metrics seems pretty easy, but I don't see the motivation for the whole list in core.

**Comment by jl2922** [comment]
It is needed in the neural style transfer when calculating style loss.
Is there any new updates on this?

**Comment by bionicles** [comment]
We would use this in molecular dynamics @girving ... possible to reopen?

A naive implementation with linear algebra works but often maxes out GPU memory. It would be ideal to have an implementation of this which breaks big problems into chunks

**Comment by bionicles** [comment]
ref: https://github.com/tensorflow/tensorflow/issues/30659
