### ISSUE TITLE
Segmentation fault on help(tf.train.SequenceExample)

### ISSUE THREAD

**Issue by JeremyCCHsu** [tensorflow/tensorflow#9748]
I was trying to try and test the tf.train.SequenceExample class, but it wasn't in the official docs and using help crashed Python. Does anyone know how to use it or how to solve this issue?

**Comment by drpngx** [comment]
Please provide a simple repro case and we can look into it.

**Comment by JeremyCCHsu** [comment]
My Tensorflow version is **1.1.0-rc2** (GPU, Python 3.5) on Ubuntu 16.04.

Some information from `platform.uname()`:
system='Linux', 
release='4.4.0-72-generic', 
version='#93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017',
machine='x86_64',
processor='x86_64'

```python
import tensorflow as tf
help(tf.train.SequenceExample)
```
Segmentation fault (core dumped)

The same problem happened when I tried to call the related classes such as `help(tf.train.Feature)`. 
Although I eventually figured out how to use `tf.train.SequenceExample`, this remains an issue to other users that are not familiar with it.

**Comment by drpngx** [comment]
@charlesnicholson could it be related to decorators?

**Comment by charlesnicholson** [comment]
Sounds like a reasonable starting point, I'll take a look.

**Comment by charlesnicholson** [comment]
@drpngx It doesn't seem like a tf_decorator issue.

Compare
https://github.com/tensorflow/tensorflow/tree/v1.1.0-rc2/tensorflow/python/util 
and
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/util

See that tf_decorator exists in 'master' but not in 1.1.0-rc2. I don't think the decorator work had landed when 1.1.0-rc2 was cut.

**Comment by drpngx** [comment]
@JeremyCCHsu is it just `help(tf.train.*)` or anything else? Can you call `tf.train.*`, say `get_global_step` for instance? Does `help(tf.*)` fail for anything else?

**Comment by JeremyCCHsu** [comment]
To be more specific, segmentation fault only happened when I called `help(*)` with the following `tf.train.Example`-related classes:

```python
# tf.train.Example
# tf.train.SequenceExample
#
#   tf.train.Features
#   tf.train.FeatureLists
#
#       tf.train.Feature    
#       tf.train.FeatureList
#
#         tf.train.Int64List
#         tf.train.FloatList
#         tf.train.BytesList
```

In contrast, `help(*)` with the following worked normally.
```python
tf.train.AdamOptimizer
tf.train.Coordinator
tf.train.Saver
tf.train.Supervisor

tf.train.batch
tf.train.queue_runner
```

**Comment by drpngx** [comment]
It looks like it's a protobuf issue. We're working on that.

It should also crash with `tf.GraphDef`.

I could not repro on my system, though. It could be because you have loaded another protobuf via `load_op_library`, or something to do with protobuf on your system.

I'm closing in favor of #9525.

**Comment by concretevitamin** [comment]
(Helping to close this - please use #9525 for follow-ups.)
