### ISSUE TITLE
tensorflow install for go

### ISSUE THREAD

**Issue by bucaixiaot** [tensorflow/tensorflow#9749]
bojuzideMacBook-Pro:~ manman$ go get github.com/tensorflow/tensorflow/tensorflow/go github.com/tensorflow/tensorflow/tensorflow/go
ld: library not found for -ltensorflow
clang: error: linker command failed with exit code 1 (use -v to see invocation)
bojuzideMacBook-Pro:~ manman$

**Comment by bucaixiaot** [comment]
bojuzideMacBook-Pro:~ manman$ "go get github.com/tensorflow/tensorflow/tensorflow/go"
# github.com/tensorflow/tensorflow/tensorflow/go
ld: library not found for -ltensorflow
clang: error: linker command failed with exit code 1 (use -v to see invocation)
bojuzideMacBook-Pro:~ manman$

**Comment by angadn** [comment]
What is the fix for this - I've tried multiple approaches to installing libtensorflow including brew but no luck

**Comment by tolitius** [comment]
@angadn: you most likely forgot to:

```bash
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local
```

After [Installing TensorFlow on Mac OS X](https://www.tensorflow.org/install/install_mac) go through steps 2 and 3 of [Installing TensorFlow for Go](https://www.tensorflow.org/install/install_go).

**Comment by oziee** [comment]
i still get this error, and have tried everything here and else where

**Comment by salilsdesai** [comment]
@oziee Thank you this worked for me after a lot of other things didn't
