### ISSUE TITLE
the time about gpu

### ISSUE THREAD

**Issue by auroua** [tensorflow/tensorflow#975]
I have installed the gpu version tf. I'm running a cnn with input size 256*256 and epoch size 32*32, but the speed is very slow,  gpu is 980ti
```
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 4.00GiB
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 8.00GiB
I tensorflow/core/common_runtime/direct_session.cc:45] Direct session inter op parallelism threads: 8
2016-02-03 18:13:09.461207: step 0, loss = 250.84 (0.2 examples/sec; 144.089 sec/batch)
2016-02-03 18:13:59.022429: step 10, loss = 248.88 (7.7 examples/sec; 4.167 sec/batch)
2016-02-03 18:14:40.752574: step 20, loss = 246.82 (7.5 examples/sec; 4.274 sec/batch)
2016-02-03 18:15:24.129283: step 30, loss = 244.89 (7.5 examples/sec; 4.277 sec/batch)
```
the first time running the speed is fast, but after this the speed is slow. What's the reason?
How could I identify the program is running on a gpu or cpu?

**Comment by prb12** [comment]
This seems a more appropriate issue for tensorflow-discuss...

The most likely cause of this is that you are maybe calling session.run()  on an op and not fetching any tensor results?
 
This has an interesting behavior where all the computation is enqueued on the GPU device, but if you don't ask to copy any results back from the GPU the call to run() can return immediately. 

The second time you call session.run(), enqueueing the GPU ops ends up waiting for the previous work to finish (for some reason).  The steady-state throughput is limited to 7.7/second, but the first measurement is misleading.

You can verify this hypothesis by either fetching back a small result tensor at the end of each step, or by adding a check_numerics op at the end of the step (which is always executed synchronously).

**Comment by yaroslavvb** [comment]
See https://github.com/tensorflow/tensorflow/issues/838 for some debugging techniques. If GPU is found, it'll place everything it can on GPU. However some operations don't have GPU implementation and this greedy placement technique can make network run suboptimally due to data transfers (100 times slower in the extreme case detailed in the issue I linked)
