### ISSUE TITLE
Much time cost from worker to ps server

### ISSUE THREAD

**Issue by daiab** [tensorflow/tensorflow#9753]
I try to test the distribute speed, with one machine of 4 GPUs. I calculate one batch on each GPU, and add the four batch on the worker's cpu , and then average the four batch on ps CPU and update the parameters, I saved the timeline file, but there are no operations from workers CPU to ps CPU with a long time span in the timeline, I don`t know where the time gone? because of data transfer? but this is test in only one machine. the timeline is as follows, and the right up operation is average four data batch and updata parameters
![webwxgetmsgimg](https://cloud.githubusercontent.com/assets/16236576/25800351/87f2acb4-341b-11e7-86a1-bfb888405d72.jpeg)

**Comment by girving** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
