### ISSUE TITLE
TensorFlow weight initialization taking 99% of total run time

### ISSUE THREAD

**Issue by arinbjornk** [tensorflow/tensorflow#9754]
### System information
- **Have I written custom code**: No (but custom data)
- **OS Platform and Distribution**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: tensorflow-gpu (1.0.0 and 1.1) (Python 3.5)
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 8.0
- **GPU model and memory**: GTX 1080
- **Exact command to reproduce**: 

### Describe the problem
I noticed that one of my networks was running slow and nvidia-smi was reporting only around ~10% GPU usage. After running the profiler, I saw that `TruncatedNormal` process was taking the vast majority of running time (see photo).

[Profiler report](https://i.stack.imgur.com/Ymup2.png)

### Source code / logs
Weight declaration function (from MNIST tutorial):
```

def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)
```
Code in action:
```
 # First Layer
    with tf.name_scope('input'):
        x = tf.placeholder(tf.float32, [None, Nvars])
    w1 = weight_variable([Nvars, 8])
    b1 = bias_variable([8])
    y1 = tf.nn.relu(tf.matmul(x, w1) + b1)
```
Please note this question was also asked on StackOverflow. [Link](http://stackoverflow.com/q/43793066)

**Comment by StefanoD** [comment]
Maybe you could try the latest version 1.1.0?

**Comment by arinbjornk** [comment]
Just updated to 1.1 and unfortunately the sluggish performance persists.

**Comment by concretevitamin** [comment]
@arinbjornk what's the shape of the variable?  

Also, maybe give this a try to see if it boosts performance:
```python
with tf.variable_scope("foo"):
  v = tf.get_variable(
      'v', [N, 8], dtype=tf.float32,
      initializer=tf.truncated_normal_initializer(stddev=0.1))
```

**Comment by yaroslavvb** [comment]
Note that executing kernel for first time can be slow (up to a minute if you have video card with capability that TF didn't get compiled for). Try running it several times

**Comment by concretevitamin** [comment]
Oh yeah, I concur with @yaroslavvb.  I'd drop the first ~3 runs, and average over the subsequent tens of runs.

**Comment by arinbjornk** [comment]
@concretevitamin The input is [examples=100000, Nvars=2500], could the 'problem' be that, since the input is small and the network is simple, the GPU time (matmul, relu, etc.) is insignificant? I used your replacement code, but, alas, there was no change.

@yaroslavvb I don't see any significant difference between many repeated runs. I also have a CNN (using different data) that I tried running in-between and that one had good performance.

[Here](https://gist.github.com/arinbjornk/49e942c077fbc6cfdaa3a59c0df30926) is a larger section of the code, in case it helps.

**Comment by yaroslavvb** [comment]
On my laptop I can generate about 200MB worth of truncated normal randoms in half a second. For your original issue of truncated normal taking 400ms, the question is -- how big is it, and how long you were expecting it to take.

Session.run overhead can be 400 usec. If your random normal taking 400ms like in the original timeline then GPU time is definitely significant

**Comment by arinbjornk** [comment]
It is generating 20k (2500x8) randoms. In the MNIST example code, one of the layers has 3M weights and that runs a lot faster.

I should have included the whole timeline output in the original post. [Here it is](https://gist.github.com/arinbjornk/d83015a51d00a207d0ae20e37f280e12#file-slow_net_timeline-json-L479). The line of interest is 479. For comparison, the Mul ops are executing suspiciously quickly.

**Comment by yaroslavvb** [comment]
So if calling `truncated_normal_initializer` to generate 20k randoms takes 400ms per call, and this timing doesn't go down after a few iterations, it would be a bug. A small self-contained repro case would be useful here, something that isolates the issue to `truncated_normal_initializer` (you can call it directly with `sess.run(tf.truncated_normal((n,)))`

**Comment by arinbjornk** [comment]
I can't replicate the issue in an isolated case. The first run of `truncated_normal_initializer` is slower as expected but subsequent runs are very fast. I suspect the issue lies elsewhere.

We can close this issue until I have more detailed information.
