### ISSUE TITLE
Accessing Array based on subscript?

### ISSUE THREAD

**Issue by vector-1127** [tensorflow/tensorflow#9756]
How I get the result using tensorflow?
```
import numpy as np
a = np.random.rand(2,10)
b = np.random.randint(0,10,(4,2))
c = a[:,b]
```
This code can be implemented by Nympy and Theano. But how to do that on tensorflow?
```
ind = np.random.randint(0,10,(4,))
x = K.placeholder(shape = (2,10),dtype = 'int64')
y = x[:,ind]
f = K.function([x],[y])

x_ = np.random.rand(2,10)
y_ = f([x_])[0]
print(x_)
print(y_)
```

**Comment by drpngx** [comment]
I have something like that in my code:
```
  train_indices = tf.random_uniform(
      [BATCH_SIZE], 0, num_train_samples, tf.int64)
  train_data_node = tf.gather(tf_train_data, train_indices)
  train_labels_node = tf.gather(tf_train_labels, train_indices)
```

This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
