### ISSUE TITLE
Large page fault causes slow performance while using gpu

### ISSUE THREAD

**Issue by luxiaolei** [tensorflow/tensorflow#9757]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary, using `pip install tensorflow-gpu==1.0.1`
- **TensorFlow version (use command below)**:
1.0.1
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
8.0/5.1
- **GPU model and memory**:
nvidia gtx1080, 8g

### Describe the problem
I have observed a large amount of page fault while running the provided sample code on gpu, and this causes a serious performance drawdown. 

The key parts of the output of `/usr/bin/time -v python sample.py` are:

    System time (seconds): 7.28  
    Percent of CPU this job got: 85%  
    Elapsed (wall clock) time (h:mm:ss or m:ss): 0:22.41 
    Minor (reclaiming a frame) page faults: 684695  
    Involuntary context switches: 164 
    File system inputs: 0  
    File system outputs: 8  

There are 684k page faults,  and the `gpu-volatile usage` is only about 30%. 

I am very hesitating to ask for help here, because on another system with exact os, software and gpu, this issue does not appears, I have posted on stackoverflow to compare two systems [here](http://stackoverflow.com/questions/43842731/two-exactly-same-systems-have-very-different-performances-when-running-tensorflo) 
Is that possible that tensorflow handles different hardwares differently? It looks to me that the gpu-cpu I/O may have caused this issue, and I suspect that I need to configure my hardware settings somewhere, but don't know how.

Things I have tried:

1. Upgrade BIOS to the latest version and reset default settings.
2. Call Asus(my motherboard and gpu vendor) customer service for help.
3. Inject LD_PRELOAD="/usr/lib/libtcmalloc.so" to .bashrc file.
 
### Source code / logs

Here is the sample code I used to test

    import tensorflow as tf
    import numpy as np
    from tqdm import trange
  
    np.random.seed(111)
    h,w = 3000, 2000
    steps = 1000

    x = tf.placeholder(dtype=tf.float32, shape=[h, w], name='x')
    t = tf.constant(np.random.random(size=[w, w]), dtype=tf.float32)
    m = tf.matmul(x,t)

    x0 = np.random.random(size=[h, w])
    sess = tf.Session()
    for i in trange(steps):
        x0 = sess.run(m, feed_dict={x: x0})

The attachment contains: `Nvidia-smi` output, `/usr/bin/time -v` output, hardware specs in html format, chrome trace timeline.
[sysB.zip](https://github.com/tensorflow/tensorflow/files/983550/sysB.zip)

**Comment by drpngx** [comment]
CC: @tfboyd

**Comment by luxiaolei** [comment]
Just to provide another information, my memory Bank Locator is `node 1` reported by using `dmidecode --type memory` , whereas for a issue free computer it is `bank 1`. Dont know if its making any differences.

**Comment by yaroslavvb** [comment]
@luxiaolei you are using `feed_dict` which means that tensorflow copies array from Python to TensorFlow runtime at each step.

There's a way to avoid the copy in latest TF version if your data is aligned. Can you try latest TensorFlow nightly + align the data to 64 bits using recipe from https://github.com/tensorflow/tensorflow/issues/9690#issuecomment-299521465 to see if this speeds things up?

**Comment by luxiaolei** [comment]
@yaroslavvb Sorry for the late reply. I upgraded Tensorflow to version 1.1.0-rc2, ran the sample code with and without align the first input to 64 bits, both observed a 2.3 times speed boost! WOW, what a huge boost! I have noticed that the output of `sess.run` is 64 bits aligned, whereas in version 1.0.1 is not.

Many thanks ! Really saved my day! My problem solved, closing the issue.

**Comment by luxiaolei** [comment]
If you need me to do more tests, I am very glad to:)

**Comment by yaroslavvb** [comment]
@alextp  -- looks like a happy customer of your copy-free numpy array change :)

**Comment by eamartin** [comment]
Minor nitpick in case anyone references this thread in the future: the speedup came by aligning with 64 bytes, not 64 bits (=8 bytes). 
The ``EIGEN_MAX_ALIGN`` variable depends on the vector architecture with which Eigen was compiled. As far as I know, AVX-512 (= 64 bytes) is the largest vector size (and largest value for ``EIGEN_MAX_ALIGN``) in the wild.

**Comment by tanglianggithub** [comment]
why does version 1.2 still hasvemany page faults?

![image](https://user-images.githubusercontent.com/3445470/57821998-343a2800-77c5-11e9-96a1-6182b232a75d.png)

**Comment by alextp** [comment]
Version 1.2 is way too old.
