### ISSUE TITLE
I use the bazel to generate the android so library on mac, but i met an issue :'ERROR: /Users/nankaiming/Desktop/tensorflow-master/tensorflow/core/kernels/BUILD:3869:1: C++ compilation of rule '//tensorflow/core/kernels:android_tensorflow_kernels' failed: Process exited with status 1 [sandboxed].'

### ISSUE THREAD

**Issue by Nankaiming** [tensorflow/tensorflow#9758]
the gcc version on my mac is
![image](https://cloud.githubusercontent.com/assets/18348154/25809650/3b40c944-3440-11e7-9235-ff6293194a6f.png)
the log of the process is 
![image](https://cloud.githubusercontent.com/assets/18348154/25809685/5cacd0aa-3440-11e7-9a2e-263a7120d762.png)
the WORKSPACE i edited is 
![image](https://cloud.githubusercontent.com/assets/18348154/25809807/c00e6c9e-3440-11e7-9424-76187b008c4d.png)

**Comment by andrewharp** [comment]
Android NDK r14b which you're probably using contains Clang, not GCC. Make sure you're using Android NDK r12b, or you'll get narrowing errors like this due to Clang (this is documented in recent versions, but it looks like you have an older version of TF).
