### ISSUE TITLE
Can't launch tensorboard

### ISSUE THREAD

**Issue by mejdidallel** [tensorflow/tensorflow#9761]
When i try to launch tensorboard i get this error message : 

tensorboard --logdir=/home/mejdi/Desktop/CNN/logs Traceback (most recent call last): File "/usr/local/bin/tensorboard", line 7, in from tensorflow.tensorboard.tensorboard import main File "/usr/local/lib/python3.5/dist-packages/tensorflow/tensorboard/tensorboard.py", line 33, in from tensorflow.tensorboard.backend import application File "/usr/local/lib/python3.5/dist-packages/tensorflow/tensorboard/backend/application.py", line 47, in from tensorflow.tensorboard.plugins.projector import projector_plugin File "/usr/local/lib/python3.5/dist-packages/tensorflow/tensorboard/plugins/projector/projector_plugin.py", line 28, in from tensorflow.contrib.tensorboard.plugins.projector import PROJECTOR_FILENAME File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/init.py", line 37, in from tensorflow.contrib import keras File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/keras/init.py", line 26, in from tensorflow.contrib.keras.api.keras import * File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/keras/api/keras/init.py", line 25, in from tensorflow.contrib.keras.api.keras import activations File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/keras/api/keras/activations/init.py", line 22, in from tensorflow.contrib.keras.python.keras.activations import elu File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/keras/python/keras/init.py", line 21, in from tensorflow.contrib.keras.python.keras import activations File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/keras/python/keras/activations.py", line 23, in from tensorflow.contrib.keras.python.keras import backend as K File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/keras/python/keras/backend.py", line 3601, in assert _image_data_format in {'channels_last', 'channels_first'} AssertionError

What's wrong ?

**Comment by mejdidallel** [comment]
I fixed it by changing image_data_format in the .keras/keras.json file from "tf" to "channels_last"

**Comment by mlkorra** [comment]
So is it  working now? @mejdidallel

**Comment by mejdidallel** [comment]
Yeah it's working now ! Thanks
