### ISSUE TITLE
Tensorflow worked and now suddenly giving errors ?

### ISSUE THREAD

**Issue by dineshgit** [tensorflow/tensorflow#9766]
Hello,

I was able to run tensorflow (both CPU and GPU) without issues yesterday. Today, after restarting my laptop, I get the below error as I tried running Tensorflow. 

I have previously checked that my path variables were set properly and only then Tensorflow worked, but I'm not sure how it suddenly isn't working.

System information

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
* Yes

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
* OS = Windows 10

TensorFlow installed from (source or binary):
*Installed from Source 

TensorFlow version (use command below):
*When I ran =>  python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
*I get only this result =>  b'unknown' 1.0.0

Bazel version (if compiling from source):
*I'm unsure about this as I don't remember installing this

CUDA/cuDNN version:
*cuda_8.0.61_win10
*cuDNN v5.1 (Jan 20, 2017), for CUDA 8.0

GPU model and memory:
*GeForce GTX 1050 graphics card
*RAM 32GB

Exact command to reproduce:
*import tensorflow as tf

Error code I got:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     17         try:
---> 18             return importlib.import_module(mname)
     19         except ImportError:

C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\importlib\_bootstrap.py in _load_unlocked(spec)

C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\importlib\_bootstrap.py in module_from_spec(spec)

C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\importlib\_bootstrap_external.py in create_module(self, spec)

C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\importlib\_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     40     sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
---> 41   from tensorflow.python.pywrap_tensorflow_internal import *
     42   from tensorflow.python.pywrap_tensorflow_internal import __version__

C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in <module>()
     20             return importlib.import_module('_pywrap_tensorflow_internal')
---> 21     _pywrap_tensorflow_internal = swig_import_helper()
     22     del swig_import_helper

C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py in swig_import_helper()
     19         except ImportError:
---> 20             return importlib.import_module('_pywrap_tensorflow_internal')
     21     _pywrap_tensorflow_internal = swig_import_helper()

C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-3-feaf27c67465> in <module>()
----> 1 import tensorflow as tf
      2 import numpy as np
      3 
      4 IM_SIZE_PX = 50
      5 SLICE_COUNT = 20

C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 

C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\__init__.py in <module>()
     49 import numpy as np
     50 
---> 51 from tensorflow.python import pywrap_tensorflow
     52 
     53 # Protocol buffers

C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py in <module>()
     50 for some common reasons and solutions.  Include the entire stack trace
     51 above this error message when asking for help.""" % traceback.format_exc()
---> 52   raise ImportError(msg)
     53 
     54 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 906, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 21, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    return importlib.import_module('_pywrap_tensorflow_internal')
  File "C:\Users\dines\Anaconda3\envs\tensorflow-gpu\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.`

**Comment by drpngx** [comment]
It is unable to load the pywrap module. Did you remember to activate your virtualenv if you are using it?

I would recommend using the dependency walker to find out what DLLs are missing.

**Comment by dineshgit** [comment]
I've managed to solve this issue by uninstalling all (Tensorflow, Anaconda) and reinstalling them all.
I also included .Net Community edition and now it's working all fine.
