### ISSUE TITLE
ImportError: No module named 'tensorflow.tools'

### ISSUE THREAD

**Issue by jasminezz** [tensorflow/tensorflow#9778]
### Describe the problem
Run the demo "transform_graph_test.py" in Windows, get the error 
"ImportError: No module named 'tensorflow.tools'"

Did I miss some installations before running the demo?
The code "from tensorflow.tools.graph_transforms import TransformGraph" cannot work?

**Comment by concretevitamin** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by jasminezz** [comment]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Direct the demo "transform_graph_test.py"
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 7
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
Tensorflow 1.0
- **CUDA/cuDNN version**:
CUDA 8.0

### Describe the problem
Run the source code  demo "transform_graph_test.py" in Windows, get the error
"ImportError: No module named 'tensorflow.tools'"

Did I miss some installations before running the demo?
The code "from tensorflow.tools.graph_transforms import TransformGraph" cannot work?

**Comment by gunan** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/tf_tools.cmake#L40 Looking at here, it looks like we do not have transform_graph python files in cmake build.
Our windows binaries are still built using cmake. So, it is expected with the current code that you see this error.

@petewarden Do we intentionally exclude transrofm_graph python files in cmake build?

**Comment by jasminezz** [comment]
@gunan Will you include transrofm_graph  python files in cmake builds? Or maybe I should install it by source code first?

**Comment by gunan** [comment]
We may be able to, but I need to make sure we do not exclude them intentionally on windows, due to other issues.

**Comment by petewarden** [comment]
We don't intentionally exclude graph transform files for cmake, so I'd be happy to see all of these included by default. Passing back to @gunan for review.

**Comment by gunan** [comment]
Actually, we do exclude them intentionally due to posix dependencies graph transform libraries have. Therefore, at the moment this inclusion seems to be infeasible.

**Comment by Faur** [comment]
So is it sufficient to install from source (on Windows), or should I switch to Linux?

**Comment by shravan-rams** [comment]
Upgrade tensorflow as `pip install --upgrade tensorflow`
It solved my problem

**Comment by Deepak-HpyAda** [comment]
@shravan-rams Yes bro your Right!!!
