### ISSUE TITLE
About slim.datasets

### ISSUE THREAD

**Issue by philokey** [tensorflow/tensorflow#9783]
Hello,
I am using tensorflow r1.1.
I try to following the example [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/slim/python/slim/data/dataset_data_provider.py)

```
pascal_voc_data_provider = DatasetDataProvider(
      slim.datasets.pascal_voc.get_split('train'),
      shuffle=False)
  images, labels = pascal_voc_data_provider.get(['images', 'labels'])
```
But I get the following error

```
AttributeError: module 'tensorflow.contrib.slim' has no attribute 'datasets'
```
Is it a bug? or how can I solve this problem?

**Comment by girving** [comment]
@sguada The commit history says this was added last June.  Should it work?

**Comment by skye** [comment]
I'm assuming this works by now, please let me know if I'm mistaken.

**Comment by balloch** [comment]
I also cannot locate slim.datasets.pascal_voc. please reopen
