### ISSUE TITLE
tensorflow for Nvidia TX1

### ISSUE THREAD

**Issue by GPrathap** [tensorflow/tensorflow#9788]
### System information
- OS Platform and Distribution: Linux Ubuntu 16.4
- Bazel version (if compiling from source): 0.4.4
- CUDA/cuDNN version: cuda-8.0

### Describe the problem

I want to install tensorflow 1.0.0 in Nvidia TX1. I am following [this](http://www.yuthon.com/2017/03/10/TensorFlow-r1-0-on-TX1/) so as to install version 1.0.0. But while installing bazel-0.4.4... I am getting this error 

### Logs

	INFO: You can skip this first step by providing a path to the bazel binary as second argument:
	INFO:    ./compile.sh compile /path/to/bazel
	🍃  Building Bazel from scratch.......
	🍃  Building Bazel with Bazel.
	.WARNING: /tmp/bazel_OpcCR2sk/out/external/bazel_tools/WORKSPACE:1: Workspace name in /tmp/bazel_OpcCR2sk/out/external/bazel_tools/WORKSPACE (@io_bazel) does not match the name given in the repository's definition (@bazel_tools); this will cause a build error in future versions.
	ERROR: No toolchain found for cpu 'unknown'. Valid cpus are: [
	  arm,
	  armeabi-v7a,
	  x64_windows_msvc,
	  s390x,
	].
	INFO: Elapsed time: 6.533s

	ERROR: Could not build Bazel
	cp: cannot stat 'output/bazel': No such file or directory

Any suggestion on this, why this is happing, really helpful.

Thanks,

**Comment by concretevitamin** [comment]
@jart mind taking a look at the Bazel installation issue?

**Comment by jart** [comment]
@GPrathap There seems to be a related Bazel thread here: https://groups.google.com/forum/#!topic/bazel-discuss/dlc3RmSxGRg that says something about https://github.com/bazelbuild/bazel/commit/e59d3a00ad4861c5e64ef90860d56316377bd50e. Are you using ARM or any type of nonstandard CPU?

**Comment by GPrathap** [comment]
@jart  it returns **aarch64**  when I type` uname -m`. I have done this because [cc_configure.bzl](https://github.com/bazelbuild/bazel/blob/0.4.4/tools/cpp/cc_configure.bzl#L145) in here, it tries to execute `uname -m` then if it gives **aarch64** that  function should return **arm**. So answer to your question is yes. It is being used arm processor.  

I think [this commit ](https://github.com/bazelbuild/bazel/commit/e59d3a00ad4861c5e64ef90860d56316377bd50e)will resolve the issue. Will try and let you know. Thanks for the suggestion.

**Comment by jart** [comment]
Glad I was able to help. If that doesn't work, please file an issue with the Bazel project and include a link to this issue in the report.

**Comment by yangc22** [comment]
Hi, I also met the same problem with you. The error message is cp: cannot stat 'output/bazel': No such file or directory. And I followed this commit [https://github.com/bazelbuild/bazel/commit/e59d3a00ad4861c5e64ef90860d56316377bd50e](url) and tried several times but it still doesn't work. Any thoughts?
