### ISSUE TITLE
is model ready when Fine-tuning in distributed case

### ISSUE THREAD

**Issue by passerbydj** [tensorflow/tensorflow#9793]
When we finetune a model on a different task, only a part of vars in the model are restored from the pretrained task and others are left as initial values.
As many docs recommends([page1](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/slim) [page2](https://github.com/tensorflow/models/blob/master/inception/inception/inception_train.py)), when training with a local graph, we restore the pretrained model **after** running the global init op(call restoring in "init_fn" if MonitoredSession or supervisor is included).
But in the distributed case, does global init op make "model_ready" returns true before the restoring-model called? other non-chief nodes will use the "not ready" values.

**Comment by passerbydj** [comment]
codes in "prepare_session" of "SessionManager". After " sess.run(init_op)", the "wait_for_session" nodes will get true for "_model_ready", but init_fn have not finished.
```
    if not is_loaded_from_checkpoint:
      if init_op is None and not init_fn and self._local_init_op is None:
        raise RuntimeError("Model is not initialized and no init_op or "
                           "init_fn or local_init_op was given")
      if init_op is not None:
        sess.run(init_op, feed_dict=init_feed_dict)
      if init_fn:
        init_fn(sess)

    local_init_success, msg = self._try_run_local_init_op(sess)
    if not local_init_success:
      raise RuntimeError(
          "Init operations did not make model ready for local_init.  "
          "Init op: %s, init fn: %s, error: %s" % (_maybe_name(init_op),
                                                   init_fn,
                                                   msg))

    is_ready, msg = self._model_ready(sess)
    if not is_ready:
      raise RuntimeError(
          "Init operations did not make model ready.  "
          "Init op: %s, init fn: %s, local_init_op: %s, error: %s" %
          (_maybe_name(init_op), init_fn, self._local_init_op, msg))
    return sess
```

**Comment by girving** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by passerbydj** [comment]
I'm wondering is this a bug

**Comment by bobauditore** [comment]
@passerbydj Hi,have you solved it yet? 9 months past but still I have exactly the same question as you.
