### ISSUE TITLE
Bijector caching breaks when used with TransformedDistribution

### ISSUE THREAD

**Issue by admcrae** [tensorflow/tensorflow#9797]
Currently, the caching that [Bijector](https://github.com/tensorflow/tensorflow/blob/7fa0cf39f854d5fdaaa19ad6425dfed02f5fea64/tensorflow/python/ops/distributions/bijector_impl.py#L114) objects do to avoid unnecessary calculations does not work when the bijector is used in a [TransformedDistribution](https://github.com/tensorflow/tensorflow/blob/7fa0cf39f854d5fdaaa19ad6425dfed02f5fea64/tensorflow/python/ops/distributions/transformed_distribution.py#L124) object. I believe the culprit is the reshaping that the distribution object does [here](https://github.com/tensorflow/tensorflow/blob/7fa0cf39f854d5fdaaa19ad6425dfed02f5fea64/tensorflow/python/ops/distributions/distribution.py#L640); when we call Bijector.inverse on the output, the Bijector object cannot tell that this is merely a reshaped version of what it calculated previously.

My use case is to sample from a TransformedDistribution and then later calculate the log probability of that sample.

This issue is particularly a problem when using a bijector whose inverse is numerically delicate (in my case, I'm chaining together softplus bijectors and my own custom affine bijector).

I'm willing to work on a fix for this problem, but I'm not sure what the best way to do it is (adding caching to the TransformedDistribution code might work, but that seems like code duplication).

### System information
- **OS Platform and Distribution**: Ubuntu 16.04
- **TensorFlow installed from**: Source
- **TensorFlow version**: v1.1.0-rc2-773-g7fa0cf3 (commit 7fa0cf39f854d5fdaaa19ad6425dfed02f5fea64)
- **Bazel version**: 0.4.5

**Comment by girving** [comment]
@ebrevdo Can you comment?

**Comment by ferrine** [comment]
Waiting for response as well, deep bijections work slow for me

**Comment by jvdillon** [comment]
My apologies for the slow response, it looks like this issue was inadvertantly misrouted.

Caching was fixed on Sept 29 and should be working in 1.4.0-rc0.
https://github.com/tensorflow/tensorflow/commit/46cf6262476b1d058e43acacc2c15097cc7bbf5a

If youre still seeing a problem, please let me know.

**Comment by ebrevdo** [comment]
Closing as fixed.
