### ISSUE TITLE
What will dynamic_rnn reuse when set reuse of variable_scope as true

### ISSUE THREAD

**Issue by ruiann** [tensorflow/tensorflow#9798]
I'm sorry but I havn't found a clear answer in StackOverflow

I wonder what will dynamic_rnn reuse when set reuse of variable_scope as true, only the gate parameters will be share or including the output & status?

The example is that my code wanna process two sequence with different length by one bidirectional LSTM network, and then compare them for further use. Will I set reuse as True when process the second sequence at one step? Do I need to clear the state in this situation?

**Comment by concretevitamin** [comment]
Short answer is `reuse=True` only affects the `tf.Variable` objects.  @ebrevdo on the `dynamic_rnn()` part.

**Comment by ebrevdo** [comment]
Depends on if you're using tf 1.1 or the tf nighties.  If you're using tf
1.1 then you need to reuse the variable scope from the first call to
dynamic rnn to ensure you're using the same parameters in the second call.
In the nighties, so long as you use the same cell object in the second
call, your parameters will be shared regardless of the variable scope/
reuse value.

**Comment by ruiann** [comment]
@ebrevdo 
Thx for your answer. I've take a quick glimpse at the rnn_ops.py, it seems the dynamic_rnn call will auto clear the cells' state unless I wanna keep them isn't? So I can just set the reuse as True in the second call thus the code can run as I want regardless of the TF version?

**Comment by ebrevdo** [comment]
That's right. Furthermore, If you want to keep state between two calls to
dynamic_rnn, you'd have to take the final state from the first call and
pass it in as the initial state in the second call. This of very rarely
done in practice.
