### ISSUE TITLE
TensorBoard "gulp" assigns to const

### ISSUE THREAD

**Issue by jlazarow** [tensorflow/tensorflow#9799]
The TensorBoard build is all kinds of broken, but the latest introduction to the tree includes an assignment to a const within the gulpfile.

In particular:

tensorflow/tensorboard/gulp_tasks/compiler.js:51 reassigns to the variable "entries" which is marked with const.

The same occurs on the next line for the variable "deps".

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from**: Source (master)
- **TensorFlow version**: last commit to tensorboard @ 9dd8e7aec9d3a8ddc458af01c2e51541ad876fb8
- **Exact command to reproduce**: "gulp"

**Comment by concretevitamin** [comment]
@dandelionmane can you take a look or reassign?

**Comment by dandelionmane** [comment]
We've deleted the gulp build! Now everything builds using bazel. Please check it out at our new repo: https://github.com/tensorflow/tensorboard.

h/t to @jart who did a ton of awesome work to get rid of gulp and switch us to bazel.
