### ISSUE TITLE
TensorBoard relies on a version of "tsify" which includes an incompatible TypeScript version

### ISSUE THREAD

**Issue by jlazarow** [tensorflow/tensorflow#9800]
The version of "tsify" in the package.json is:

"tsify": "^0.14.8"

but this package includes a 1.x version of typescript. Therefore, compiling certain constructs e.g. "number | null" fails.

This can be (seemingly) resolved by changing the version of tsify to a more recent version not relying on its own TypeScript package.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from**: Source (master)
- **TensorFlow version**: last commit to tensorboard @ 9dd8e7aec9d3a8ddc458af01c2e51541ad876fb8
- **Exact command to reproduce**: "gulp"

**Comment by concretevitamin** [comment]
@dandelionmane can you take a look or reassign?

**Comment by dandelionmane** [comment]
Thanks to hard work by @jart, we no longer use gulp or package.json.
