### ISSUE TITLE
Bug of CPU detection?

### ISSUE THREAD

**Issue by c-cccc** [tensorflow/tensorflow#9809]
### System information
Linux 4.9.0-kali4-686-pae #1 SMP Debian 4.9.25-1kali1 (2017-05-04) i686 GNU/Linux
TensorFlow installed from source code
TensorFlow version : 1.0.1
Bazel version : 0.4.2
CUDA/cuDNN version: None
GPU model and memory: None

> 
> == cat /etc/issue ===============================================
> Linux 4.9.0-kali4-686-pae #1 SMP Debian 4.9.25-1kali1 (2017-05-04) i686 GNU/Linux
> VERSION="2017.1"
> VERSION_ID="2017.1"
> 
> == are we in docker =============================================
> No
> 
> == compiler =====================================================
> c++ (Debian 6.3.0-16) 6.3.0 20170425
> Copyright (C) 2016 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> 
> == uname -a =====================================================
> Linux 4.9.0-kali4-686-pae #1 SMP Debian 4.9.25-1kali1 (2017-05-04) i686 GNU/Linux
> 
> == check pips ===================================================
> numpy (1.12.1)
> 
> == check for virtualenv =========================================
> False
> 
> == tensorflow import ============================================
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "tensorflow/__init__.py", line 24, in <module>
>     from tensorflow.python import *
>   File "tensorflow/python/__init__.py", line 72, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "tensorflow/python/__init__.py", line 61, in <module>
>     from tensorflow.python import pywrap_tensorflow
> ImportError: cannot import name pywrap_tensorflow
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.
> 
> == env ==========================================================
> LD_LIBRARY_PATH is unset
> DYLD_LIBRARY_PATH is unset
> 
> == nvidia-smi ===================================================
> 
> == cuda libs  ===================================================

### Describe the problem
I compiled it from source,  and got this fatal error when try to import tensorflow in python3.5.3:

```
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
F tensorflow/core/platform/cpu_feature_guard.cc:35] The TensorFlow library was compiled to use SSE instructions, but these aren't available on your machine.
Aborted
```

And here is the information of my CPU:

```
.......
processor    : 3
vendor_id    : GenuineIntel
cpu family    : 6
model        : 37
model name    : Intel(R) Core(TM) i3 CPU       M 370  @ 2.40GHz
stepping    : 5
microcode    : 0x4
cpu MHz        : 933.000
cache size    : 3072 KB
physical id    : 0
siblings    : 4
core id        : 2
cpu cores    : 2
apicid        : 5
initial apicid    : 5
fdiv_bug    : no
f00f_bug    : no
coma_bug    : no
fpu        : yes
fpu_exception    : yes
cpuid level    : 11
wp        : yes
flags        : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology nonstop_tsc aperfmperf eagerfpu pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt lahf_lm tpr_shadow vnmi flexpriority ept vpid dtherm arat
bugs        :
bogomips    : 4787.91
clflush size    : 64
cache_alignment    : 64
address sizes    : 36 bits physical, 48 bits virtual
......

```

that's all.

**Comment by girving** [comment]
@petewarden Any idea what's happening here?  Core i3 certainly has SSE, as indicated in the flags.

**Comment by charmasaur** [comment]
FYI I'm also seeing this (and I'm also using i686).

I don't understand these things so could be wrong, but it seems like PLATFORM_IS_X86 isn't set when building on i686 with gcc [1][2], and if PLATFORM_IS_X86 isn't set then the CPU info checks fail fast [3]. 

[1] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/platform.h#L59
[2] https://sourceforge.net/p/predef/wiki/Architectures/
[3] https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/cpu_info.cc#L313

**Comment by petewarden** [comment]
Unfortunately we don't test on 32-bit x86 here, since it's not an officially supported platform and we don't have machines set up, so it's hard for us to do a fix. We'd welcome a PR with an update though, I'm guessing adding the right macro check at [1] would get things running?

**Comment by petewarden** [comment]
Actually, I take that back. We do have a supported platform we can test on, older iPhone emulators use 32-bit x86, as shown in bug #8914. Since we're tracking this issue there, closing this as a duplicate.
