### ISSUE TITLE
fatal error: 'infiniband/verbs.h' file not found

### ISSUE THREAD

**Issue by dendisuhubdy** [tensorflow/tensorflow#9818]
When building Tensorflow from Source

```
ERROR: /Users/dendisuhubdy/dev/dlframeworks/tensorflow/tensorflow/contrib/verbs/BUILD:104:1: C++ compilation of rule '//tensorflow/contrib/verbs:rdma_rendezvous_mgr' failed: cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 135 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from tensorflow/contrib/verbs/rdma_rendezvous_mgr.cc:18:
In file included from ./tensorflow/contrib/verbs/rdma_rendezvous_mgr.h:21:
In file included from ./tensorflow/contrib/verbs/rdma_mgr.h:24:
./tensorflow/contrib/verbs/rdma.h:21:10: fatal error: 'infiniband/verbs.h' file not found
#include <infiniband/verbs.h>
         ^
1 error generated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 4656.328s, Critical Path: 2662.37s
```

**Comment by drpngx** [comment]
You need verbs. Do you intend to use RDMA?

**Comment by dendisuhubdy** [comment]
Yes, oh shit I forgot verbs in my build, thanks @drpngx !

**Comment by argman** [comment]
@drpngx is there any tutorial about how to use this on a centos system ?

**Comment by CynthiaProtector** [comment]
I have installed libibverbs-1.1.8 and libibverbs-devel-1.1.8, but I still can't locate the infiniband/verbs.h, any advice?

**Comment by shamoya** [comment]
You should have it in libibverbs-devel (/usr/include/infiniband/verbs.h).
what is the output of: dpkg-query -L libibverbs-dev | grep verbs.h  ?

**Comment by CynthiaProtector** [comment]
I installed the libibverbs-devel-1.1.8 from the local repo before, and problem solved after downloading another version of libibverbs-devel from the Internet. Thank you!!

**Comment by smiletobingxue** [comment]
@CynthiaProtector hello, i encountered the same problem and i haven't found the solution. I want to know if you run on MacOS? because when i try to install  libibverbs-dev on mac, it turns:
$ pip3 install libibverbs-dev
Collecting libibverbs-dev
  Could not find a version that satisfies the requirement libibverbs-dev (from versions: )
No matching distribution found for libibverbs-dev
thanks very much.

**Comment by srangari** [comment]
> I installed the libibverbs-devel-1.1.8 from the local repo before, and problem solved after downloading another version of libibverbs-devel from the Internet. Thank you!!

Hello Cynthia,
Could you please tell the internet source to download libibverbs-devel as I am facing the same issue.

**Comment by byronyi** [comment]
RDMA is only provided for Linux now, and you could install them with libibverbs-dev (Debian/Ubuntu) or libibverbs-devel (RHEL/CentOS/Fedora).

**Comment by Wen-He** [comment]
I added lib `libibverbs-dev` and installed it by `apt-get`. But when running `make`, it failed to find the lib.
```
/usr/bin/ld: cannot find -libverbs-dev
````
