### ISSUE TITLE
tf.constant_initializer does not accept Tensor as input

### ISSUE THREAD

**Issue by el3ment** [tensorflow/tensorflow#9821]
I'd like to load multiple copies of VGG on each of 4 different GPUs.. rather than copy the weights down to each GPU every time, I'd like a local copy of the weights. Unfortunately using constant_initializer and a numpy array explodes the graph def (as all the n copies of the weights are stored). 

Instead, I convert the weights to a tensor once, and want to use this tensor to initialize the variable. this keeps the graphdef small and allows me to be super flexible. Unfortunately it looks like tf.constant_initializer doesn't accept Tensors as values.

**Comment by yaroslavvb** [comment]
It's pretty inefficient to large numpy arrays into Graph. A work-around is to create Variables with  `tf.placeholder` initial value and then feed numpy array during initialization. Unfortunately `get_variable` doesn't have `placeholder_initializer` either.

I get around it this by using a simplified replacement for `get_variable` mechanism that creates variables with `tf.placeholder` initial value, and puts corresponding `placeholder,numpy` pairs into global init_dict, so then I can call `sess.run(tf.global_variables_initializer(), feed_dict=init_dict)`

Here's an example: https://github.com/yaroslavvb/stuff/blob/master/numpy_initializers/kfac_cifar.py#L245

**Comment by yaroslavvb** [comment]
@lukaszkaiser what do you think about supporting following: `tf.get_variable(name, tf.tensor_initializer(tensor))` which accepts a `tf.Tensor` object, and creates variable as `tf.Variable(tensor, name=name)`? That will cover the placeholder use-case as well

**Comment by lukaszkaiser** [comment]
We already support just passing values to initializer in get_variable, they just get passed over to tf.Variable, so you can, e.g., do tf.get_variable("x", initializer=0.5). I'd hope it'd work with tf.Tensor already, doesn't it?

**Comment by yaroslavvb** [comment]
Good point, that does seem to work already

```
pl = tf.placeholder(tf.float32, shape=())
a = tf.get_variable("test", initializer=pl)
sess = tf.Session()
sess.run(a.initializer, feed_dict={pl: 1})
```

@el3ment does that cover your use-case? You could be even more efficient by initializing the first variable `var` on GPU from `tf.placeholder`, and the rest from `var.initial_value()`

**Comment by el3ment** [comment]
@yaroslavvb The issue there is that I would need to create a placeholder for all the weights in VGG which is impractical.

@lukaszkaiser This is true for constants, but when I tried it with a tensor object it complained.

One alternative to having `tf.constant_initializer` accept a tensor is to make `tf.get_variable` accept a tensor as an initializer directly.. but this isn't quite as clear IMO

**Comment by yaroslavvb** [comment]
@el3ment it should work with a Tensor, can you double check that you have latest version
