### ISSUE TITLE
Kernel Restarting The kernel appears to have died. It will restart automatically (Jupyter-Tensorflow)

### ISSUE THREAD

**Issue by dineshgit** [tensorflow/tensorflow#9829]
I am facing a huge problem where the jupyter kernel keeps dying. This is my first experience of kernel ending on Jupyter. I'm using Tensorflow to fit a CNN model (the total input datasize is only 9.8MB)

I did not have this issue in my previous run on the same code (however I did have errors where it said "dst tensor is not initialized". That was when I made the dataset really small to attempt to fit it. Could someone please kindly help ?

This is the code:

import tensorflow as tf
import numpy as np

IMG_PX_SIZE = 50
HM_SLICES = 20

n_classes = 2

x = tf.placeholder('float')
y = tf.placeholder('float')

keep_rate = 0.8
keep_prob = tf.placeholder(tf.float32)

def conv3d(x, W):
    return tf.nn.conv3d(x, W, strides=[1,1,1,1,1], padding='SAME')

def maxpool3d(x):
    return tf.nn.max_pool3d(x, ksize=[1,2,2,2,1], strides=[1,2,2,2,1], padding='SAME')

def convolutional_neural_network(x):
    weights = {'W_conv1':tf.Variable(tf.random_normal([3,3,3,1,32])),
               'W_conv2':tf.Variable(tf.random_normal([3,3,3,32,64])),
               'W_fc':tf.Variable(tf.random_normal([62720  ,1024])),
               'out':tf.Variable(tf.random_normal([1024, n_classes]))}

    biases = {'b_conv1':tf.Variable(tf.random_normal([32])),
               'b_conv2':tf.Variable(tf.random_normal([64])),
               'b_fc':tf.Variable(tf.random_normal([1024])),
               'out':tf.Variable(tf.random_normal([n_classes]))}

    x = tf.reshape(x, shape=[-1, IMG_PX_SIZE, IMG_PX_SIZE, HM_SLICES, 1])

    conv1 = tf.nn.relu(conv3d(x, weights['W_conv1']) + biases['b_conv1'])
    conv1 = maxpool3d(conv1)
    
    conv2 = tf.nn.relu(conv3d(conv1, weights['W_conv2']) + biases['b_conv2'])
    conv2 = maxpool3d(conv2)

    fc = tf.reshape(conv2,[-1, 62720  ])
    fc = tf.nn.relu(tf.matmul(fc, weights['W_fc'])+biases['b_fc'])
    fc = tf.nn.dropout(fc, keep_rate)

    output = tf.matmul(fc, weights['out']) + biases['out']

    return output

 def train_neural_network(x):
    
    much_data = np.load('muchdata_sampled-50-50-20.npy')
    train_data = much_data[:100]
    validation_data = much_data[-100:]
    
    prediction = convolutional_neural_network(x)
    cost = tf.reduce_mean( tf.nn.softmax_cross_entropy_with_logits(logits=prediction,labels=y) )
    optimizer = tf.train.AdamOptimizer().minimize(cost)
    
    hm_epochs = 3
    with tf.Session() as sess:
        sess.run(tf.global_variables_initializer())

        for epoch in range(hm_epochs):
            epoch_loss = 0
            for data in train_data:
                X = data[0]
                Y = data[1]
                _, c = sess.run([optimizer, cost], feed_dict={x: X, y: Y})
                epoch_loss += c

            print('Epoch', epoch, 'completed out of',hm_epochs,'loss:',epoch_loss)

        correct = tf.equal(tf.argmax(prediction, 1), tf.argmax(y, 1))

        accuracy = tf.reduce_mean(tf.cast(correct, 'float'))
        print('Accuracy:',accuracy.eval({x:[i[0] for i in validation_data], y:[i[1] for i in validation_data]}))

 train_neural_network(x)

(My System information)

Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
* Yes

OS Platform and Distribution:
* OS = Windows 10

TensorFlow installed from (source or binary):
*Installed from Source

TensorFlow version (use command below):
*When I ran => python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"
*I get only this result => b'unknown' 1.0.0

CUDA/cuDNN version:
*cuda_8.0.61_win10
*cuDNN v5.1 (Jan 20, 2017), for CUDA 8.0

GPU model and memory:
*GeForce GTX 1050 graphics card
*RAM 32GB

**Comment by SrivastavaKshitij** [comment]
Don't use Jupyter notebook. Use a simple .py script.  I know a known problem with notebook. It doesn't allow cuda to deallocate resources once the session is over which creates problems.

**Comment by dineshgit** [comment]
Yes, I understand this point, but what perplexes me is that others with lesser CPU or GPU power is able to run this simple code without much issues. I tried this same code on Spyder instead of Jupyter and I get the error "ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[54080,1024]"

I'm starting to suspect that I must be missing a technique to get this working properly. I've been trying to decipher this for the past 7 hours - no success so far. A friend of mine with similar machine spec can get this to run without any issues.

**Comment by girving** [comment]
It sounds like you are running out of memory.  This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by rbwendt** [comment]
FWIW I was seeing this after getting an OOM and then reducing the batch size. The video card seems to hold on to memory after crashes sometimes. Restarting the machine fixed the problem for me.

**Comment by juggernaut5k** [comment]
A good technique to try (I put this at the beginning of any script using tensorflow or keras). This prevents that resource exhausted error assuming you're batch size is within reason.

import tensorflow as tf

config = tf.ConfigProto()
config.gpu_options.allow_growth = True
# Now when creating your session pass this config to it.
sess = tf.Session(config=config)

**Comment by AmirAvnit** [comment]
If you're running on a gpu, first thing I'd suggest doing is checking if a gpu drivers can be updated to a newer version. If so, this may solve the problem.

**Comment by zhanwenchen** [comment]
This happened to me (with Keras) but I updated cuDNN (from 7.1 to 7.2), reinstalled tensorflow-gpu, and it worked! Whatever your case, a good starting point is always downloading the Jupyter Notebook to a .py script and running it. At least it will give you more the complete errors/warnings.

**Comment by NoreenMekky** [comment]
just updating my packages using `conda update anaconda` fixed it for me.

**Comment by Tez01** [comment]
> A good technique to try (I put this at the beginning of any script using tensorflow or keras). This prevents that resource exhausted error assuming you're batch size is within reason.
> 
> import tensorflow as tf
> 
> `config = tf.ConfigProto()`
> `config.gpu_options.allow_growth = True`
> Now when creating your session pass this config to it.
> `sess = tf.Session(config=config)`

worked for me

**Comment by blakeedwards823** [comment]
> Don't use Jupyter notebook. Use a simple .py script. I know a known problem with notebook. It doesn't allow cuda to deallocate resources once the session is over which creates problems.

Thank you! This was driving me crazy for the longest time.

**Comment by inspirepassion** [comment]
Upgrading numpy works for me.
`pip install -U numpy`

**Comment by ram1209** [comment]
This worked for me ..
!pip install numpy --upgrade.

**Comment by joeltorby** [comment]
Quite unexpected that it was numpy caused this type of error: 
In jupyter notebook: 
    Python Has Stopped Working
In anaconda: 
   Notebook file.ipynb is not trusted
   Adapting from protocol version 5.1 (kernel 1123456789...) to 5.3 (client).

This worked for me:

> Upgrading numpy works for me.
> `pip install -U numpy`

**Comment by RuiWang1998** [comment]
> Upgrading numpy works for me.
> pip install -U numpy
worked for me.

**Comment by panosprotopapas** [comment]
In case someone gets stuck (like me) and none of the above work, make sure you have a BLAS library. I installed libopenblas-dev, liblapack-dev through Synaptic (and all additional required changes), and got everything to work.

So I agree that the issue is -loosely speaking- numpy related :)

**Comment by SystemsPatrick** [comment]
uninstall tensorflow with pip uninstall tensorflow in consola and run again the jupyter.

**Comment by DeeptiAgl** [comment]
It worked for me - Follow the below steps - :) 
Download Python 3.6 - 
   **conda install python=3.6**
Create a new conda environment-
   **conda create --name newEnv**
To activate or deactive this environment  use below commands - 
   **activate newEnv
      conda deactivate**
Activate your new Environment using  activate newEnv
If you want to use GPU - use this command - 
  **conda install -c anaconda keras-gpu**
for CPU use belwo command -
  **conda install -c anaconda keras**
Now install other necessary libraries - 
Pandas - 
   **conda install -c anaconda pandas**
Sklearn - 
  **conda install -c anaconda scikit-learn**
I hope it helps! :) :)

**Comment by MuhammadNumanmn** [comment]
pip install --upgrade numpy worked for me
thank you for your suggestions.

**Comment by istvan1000** [comment]
I started a second Mac with exactly the same set-up, the same environment, which had nothing else then Anaconda and all its libraries and the code. Running it gave me the "Kernel Restarting The kernel appears to have died. It will restart automatically " msg immediately with the first "import Numpy as np" command. I reinstalled, updated, changed the order, renamed the Macs, rebooted 1000 times, tried for 5-6 hours all variations, it gave me always this msg ... I tried all here published ideas, no way. ...  Have anybody an idea how to interrupt this videogame? Thanks

**Comment by mehdirezaie** [comment]
`conda install nomkl` worked on my computer (iMac, Tensorflow 2.0 which was installed with `conda install -c anaconda tensorflow`)

**Comment by tanyagupta** [comment]
> > Upgrading numpy works for me.
> > pip install -U numpy
> 
> worked for me.

Worked for me

**Comment by istvan1000** [comment]
I think I tried to re-install Numpy 4-5 times, it didn't help. The strange thing is that on one Powerbook it works, on the other it doesn't. My suspect is that it has to do with the graphicard, this is the only difference between the two Macs and somewhere there is coming a conflict.

**Comment by ustchf** [comment]
> > > Upgrading numpy works for me.
> > > pip install -U numpy
> > 
> > 
> > worked for me.
> 
> Worked for me
Worked for me

**Comment by hessior** [comment]
> > > Upgrading numpy works for me.
> > > pip install -U numpy
> > 
> > 
> > worked for me.
> 
> Worked for me
> Worked for me

Worked for me!

**Comment by jerryOkafor** [comment]
> pip install -U numpy

This worked for me

**Comment by tamjazad** [comment]
> pip install -U numpy
This also worked for me

**Comment by ksamk** [comment]
This is what i get after updating numpy 

![image](https://user-images.githubusercontent.com/14892755/84131843-f4488180-aa66-11ea-9e31-2741f729432a.png)
 
It runs at first, then crashes

**Comment by angelluk** [comment]
pip install -U numpy

Worked for me!

**Comment by sourabh99pan** [comment]
Just create a new environment and try to launch jupyter from there.

**Comment by niphoenixo** [comment]
conda install nomkl

Worked for me!

**Comment by ashikul-aziz-siddique** [comment]
> A good technique to try (I put this at the beginning of any script using tensorflow or keras). This prevents that resource exhausted error assuming you're batch size is within reason.
> 
> import tensorflow as tf
> 
> `config = tf.ConfigProto()`
> `config.gpu_options.allow_growth = True`
> Now when creating your session pass this config to it.
> `sess = tf.Session(config=config)`

When I use this it shows this error. What I will have to do?
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

**Comment by ashikul-aziz-siddique** [comment]
> A good technique to try (I put this at the beginning of any script using tensorflow or keras). This prevents that resource exhausted error assuming you're batch size is within reason.
> 
> import tensorflow as tf
> 
> `config = tf.ConfigProto()`
> `config.gpu_options.allow_growth = True`
> Now when creating your session pass this config to it.
> `sess = tf.Session(config=config)`

When I run this code, it shows this error. What I will have to do?
AttributeError: module 'tensorflow' has no attribute 'ConfigProto'

**Comment by KarthikKaiplody** [comment]
> conda install nomkl
> 
> Worked for me!

Thanks, This worked for me.

**Comment by krismatson** [comment]
`pip install -U numpy` was not sufficient
`conda update --all` worked for a conda env with `python=3.7` and tensorflow`2.0.0`

**Comment by this-is-shashank** [comment]
I tried all. Nothing worked for me.

**Comment by abdulwaheedsoudagar** [comment]
Some issue with Jupiter notebook, I was not facing issue when I ran the .py file from the terminal.
I suggest trying a different IDE.

**Comment by cemanughian** [comment]
```
from numba import cuda
cuda.select_device(0)
cuda.close()
```

**Comment by totmakov** [comment]
Faced the same issue on Mac with tf 1.14. Created new conda environment with tf 2.0 there. See the same error. 

1. In the console activated this new environment `conda activate tf`. 
2. Did `pip install -U numpy` as proposed above. It uninstalled `numpy-1.19.2` and installed `numpy-1.19.5`
3. Manually restarted a kernel in Jupyter and re-run all cells. 
4. It works now.

**Comment by andrianamin** [comment]
> Don't use Jupyter notebook. Use a simple .py script. I know a known problem with notebook. It doesn't allow cuda to deallocate resources once the session is over which creates problems.

do you say we delete problem because it doesn't have solution right now !

**Comment by ReginaMerine** [comment]
import cv2
import pandas as pd
import os
import numpy
import pathlib

img_folder_path='images/img.png'
frame=cv2.imread(img_folder_path)

pd_bbox = '/home/jupyter-remerine/bounding_box.txt'

def plot_bbox(img_folder_path, bbox_filename):
    actual_bbox=open(bbox_filename, 'r')
    
    img_folder_path=os.path.split(img_folder_path)[-1]
    #print(img_folder_path)
    count=0
    temp_count=0
    final_bbox_list=[]
    for img in actual_bbox :
        if img.find(img_folder_path) != -1:
            print('file exist:',count)
            print('given image',img)
            temp_count=count
            print("this is temp count",temp_count)
            
        if count > temp_count:

            if img.find('/') == -1 :
                final_bbox_list.append(img)
            else:
                break
        count+=1

    i=final_bbox_list[1]
    temp_i=list(i.split(" "))
    temp_i.pop(0)

    p = numpy.array(temp_i)
    k=p.astype(float)

    x1=int(k[0])
    y1=int(k[1])
    x2=int(k[2])
    
    y2=int(k[3])
    return x1,y1,x2,y2




x_1,y_1,x_2,y_2=plot_bbox(img_folder_path, pd_bbox)

# cv2.rectangle(frame,(x1,y1),(x2,y2),(348.5,392.3),(479.8, 381.1),4) #rgb 220,20,60
cv2.rectangle(frame,(x_1,y_1),(x_2,y_2),(60,20,220),4)
cv2.imshow('image',frame)
cv2.waitKey(0)
cv2.destroyAllWindows()


Hello everyone, I'm getting the following output when I execute the above-mentioned code. Please help me finding out where I have gone wrong.  

![Screenshot (1)](https://user-images.githubusercontent.com/66924004/114596690-eb63a600-9c5d-11eb-9c3a-787702aab038.png)

**Comment by NEswariDevi** [comment]
I am facing the same issue, when I attempt to train a CNN model.

The model gets trained for smaller number of Epochs. Eg if epochs=50 the model runs fine and outputs the trained model file (using callbacks in model.fit). But when epochs=75 the jupyter notebook says kernel disconnected at 54th epoch (using same dataset). 

As per the suggestions provided above, I ran .py file by submitting as a job through slurm script. This also gave 'segmentation fualt (core dumped) error at 54th epoch (same place where jupyter notebook kernel died). So what could be the reason?

**Comment by peter-jp** [comment]
I am facing the same issue, when I attempt to train a CNN model.

The model gets trained for smaller number of Epochs. Eg if epochs=50 the model runs fine and outputs the trained model file (using callbacks in model.fit). But when epochs=75 the jupyter notebook says kernel disconnected at 54th epoch (using same dataset).

As per the suggestions provided above, I ran .py file by submitting as a job through slurm script. This also gave 'segmentation fualt (core dumped) error at 54th epoch (same place where jupyter notebook kernel died). So what could be the reason?

**Comment by bonsoirval** [comment]
@[istvan1000](https://github.com/istvan1000)
ie pip install tensorflow-gpu from  [here](https://www.kaggle.com/product-feedback/41221)

**Comment by oumhassdji** [comment]
i try pip install -U numpy it's worked for me but after time it wont be work

**Comment by Victorimah** [comment]
Try pip install -U numpy
