### ISSUE TITLE
how to install tensorflow 0.12 or 0.9 version on windows now?

### ISSUE THREAD

**Issue by Careenn** [tensorflow/tensorflow#9834]
I have tried several ways to install tf based on docker, but the installation code can only install the latest tf version.......

**Comment by asimshankar** [comment]
You can find older versions of the website at: https://www.tensorflow.org/versions/
and browse from there.

For example, installation instructions for 0.12 on Windows are at:
https://www.tensorflow.org/versions/r0.12/get_started/os_setup#pip_installation_on_windows

Hope that helps.

**Comment by Occupied-Observer** [comment]
sorry I cant find the link, and cant install tensorflow 0.12 on windows, can anyone suggest an approach or an alternative

**Comment by mihaimaruseac** [comment]
This version is no longer supported
