### ISSUE TITLE
Increase compatibility with pathlib

### ISSUE THREAD

**Issue by untom** [tensorflow/tensorflow#9846]
Pathlib (https://docs.python.org/3/library/pathlib.html) is a nice standard-library for dealing with paths, but it seems that TensorFlow currently does not always accept them. E.g. when creating a FileWriter like:

    logdir = pathlib.Path('/my/path')
    log = tf.summary.FileWriter(logdir, sess.graph)

I get:

    TypeError: Expected binary or unicode string, got PosixPath('/my/path')

While it's easy to work around this, it would be nice if this could be supported out of the box.

EDIT: this was using TF 1.1

**Comment by concretevitamin** [comment]
@dandelionmane do we plan to consider this?  If so we can mark as contribution welcome.

**Comment by girving** [comment]
I don't think we're going to support third party string types.

**Comment by Corea** [comment]
Could you consider this feature again, please?

**Comment by untom** [comment]
I've only now noticed that the issue is closed. Please notice that `pathlib` is a standard library, not a `third party string type`.

**Comment by zo7** [comment]
Yeah, `pathlib` is standard library in Python 3.

Simplest solution for this to keep compatibility with Python 2 is to simply wrap all paths with `str(mypath)` to convert `pathlib` paths to strings.
