### ISSUE TITLE
TensorBoard --logdir=c:\foo support

### ISSUE THREAD

**Issue by DarrellThomas** [tensorflow/tensorflow#9854]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no.  I am working with the full example to get the tensorboard to work.  I changed the file directory for the logs into something on my system:

  `train_writer = tf.summary.FileWriter('D:/logs_dt' + '/train', sess.graph)`
  `test_writer = tf.summary.FileWriter('D:/logs_dt' + '/test')
`

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Window 10
- **TensorFlow installed from (source or binary)**:
binary with GPU
- **TensorFlow version (use command below)**:
1.1.0
- **Bazel version (if compiling from source)**:
n/a
- **CUDA/cuDNN version**:
CUDA 8.0
cuDNN v5 for CUDA 8.0 (27 May 2016)
- **GPU model and memory**:
NVIDIA GTX 1070 4GB
- **Exact command to reproduce**:
from windows cmd: 
`tensorboard --logdir='D:\logs_dt'`

You can collect some of this information using our environment capture script:
[tf_env.txt](https://github.com/tensorflow/tensorflow/files/995339/tf_env.txt)

python
1.1.0

### Describe the problem
I'm not seeing anything on the tensorboard at all.  I can see where the log director(ies) is/are created by the tutorial script, and the subdirectories /test and /train are there with the event data present.  I point the tensorboard to the populated log directory with the following command,  but it cannot see the event files.  Nothing is present in tensorboard, and I'm redirected back to the tutorials.
`tensorboard --logdir='D:\logs_dt'`

### Source code / logs
[tensor_board_hello.zip](https://github.com/tensorflow/tensorflow/files/995362/tensor_board_hello.zip)
[logs_dt.zip](https://github.com/tensorflow/tensorflow/files/995357/logs_dt.zip)

**Comment by DarrellThomas** [comment]
This is the same issue as #8845, which also references #7856.   I was able to reproduce the same issue/failure with lgorX2.   i.e.  I downloaded his event data with the same failure as his (and mine).  

Reviewing issue #7856; mrry commented on Feb 26:
> Unfortunately TensorBoard uses a colon as the separator between the optional "run name" and the path in the --logdir flag. That means that --logdir=E:\tmp\tensorflow\mnist\logs is interpreted as a run named E with path \tmp\tensorflow\mnist\logs, which explains why it's sensitive to the current working directory.

As a quick workaround, you could avoid this problem by always specifying an explicit run name as part of the --logdir flag, e.g.:

`tensorboard --logdir=training:E:\tmp\tensorflow\mnist\logs

(Reassigning to @dandelionmane, who shows up on the blame` for the relevant code.)


I used this suggestion and it seemed to be a valid workaround  for the issue I described above.  However, I hope this stays open as a bug, because it is one.  A "quick workaround" is nice, and hopefully we can get a more permanent fix.  At a minimum, maybe add this in the tutorial as a note for windows users so they can get up and running quickly.

**Comment by MMCMA** [comment]
related to #9701?

**Comment by DarrellThomas** [comment]
It looks like @IgorX2 had same issue in #8845.  I reproduced his error too with his data.   His thread references #7856, which has the following workaround posted by @mrry on 26 Feb

>Unfortunately TensorBoard uses a colon as the separator between the optional "run name" and the path in the --logdir flag. That means that --logdir=E:\tmp\tensorflow\mnist\logs is interpreted as a run named E with path \tmp\tensorflow\mnist\logs, which explains why it's sensitive to the current working directory.
>As a quick workaround, you could avoid this problem by always specifying an explicit run name as part of the --logdir flag, e.g.:

>`tensorboard --logdir=training:E:\tmp\tensorflow\mnist\logs`

>(Reassigning to @dandelionmane, who shows up on the blame for the relevant code.)

This workaround worked for me.  It seems to be a valid bug and the workaround seems valid.   I hope this helps others trying to get this running in windows.  At a minimum, perhaps put a note in the [tutorial](https://www.tensorflow.org/get_started/summaries_and_tensorboard) for windows users to specify the explicit run name too?  

Very exciting stuff you guys are working on!  Hate to see others get slowed down if a simple fix would work.

**Comment by skye** [comment]
@dandelionmane @jart

**Comment by jart** [comment]
I'll write up a change soon to work around this issue. I'm not sure if a perfect solution is possible. It might be best if we just not allow single character run names. Or maybe only impose that behavior on Windows, or when backslashes are used.

**Comment by wchargin** [comment]
Thanks for reporting this. I've migrated it to our new repository at https://github.com/tensorflow/tensorboard/issues/51.
