### ISSUE TITLE
Bazel Clean hangs 

### ISSUE THREAD

**Issue by satendrapratap** [tensorflow/tensorflow#9856]
Hi ,

I am trying to build TensorFlow example for Android using Bazel but it hanged. So I tried to find the reason
and after a while tried to clean the previous build with "bazel clean" and it hangs again the same way as it happened while building TensorFlow examples:

$ bazel clean
.................................................................................................................................................................................{hangs here}

It doesn't move beyond that and we get no other info. Is there any other way to debug this or log the "bazel clean" output which we can later use to debug the issue?

We are using:
tensorflow: 1.1.0
Python: 2.7.6

We tried to find bazel version using "bazel version" now this is also hanging:
$ bazel version
. {hangs here}

Looks like its an issue with bazel. may be the installation is not correct. Can someone help?

**Comment by satendrapratap** [comment]
Tried for bazel version after rebooting machine and following is the output:

Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:19:38 2017 (1489666778)
Build timestamp: 1489666778
Build timestamp as int: 1489666778

**Comment by drpngx** [comment]
That looks like a bazel issue, could you report it there?

Please also report OS.
CC @jart

**Comment by jart** [comment]
Yes please report to Bazel. Also be sure to provide them with information about your OS, computer, etc.
