### ISSUE TITLE
Where is tf.layers.flatten?

### ISSUE THREAD

**Issue by Hvass-Labs** [tensorflow/tensorflow#9859]
I hope this question is considered suitable for asking here on GitHub rather than StackOverflow as it relates to a possibly missing feature of the TensorFlow API. I apologize beforehand if I am wasting your time.

This concerns TensorFlow 1.1.0 and `tf.layers`

The tutorial on `tf.layers` uses manual reshaping to get from 4-rank to 2-rank tensors (search for the word flatten):

https://www.tensorflow.org/tutorials/layers

This is not very elegant and I would prefer to use a `flatten()` function.

The documentation for `tf.layers.dense()` says something about flattening the input, but it apparently does something else, as discussed in other threads https://github.com/tensorflow/tensorflow/issues/8175 and https://github.com/tensorflow/tensorflow/pull/9043

There does not seem to be any `tf.layers.flatten()` function, see e.g. the API docs:

https://www.tensorflow.org/api_docs/python/tf/layers

Although there is one for `tf.contrib.layers.flatten()` as shown here:

https://www.tensorflow.org/api_docs/python/tf/contrib/layers/flatten

I wonder if `flatten()` has been omitted for some reason when moving `layers` to TF core (why?) or perhaps it has been moved somewhere else, but I have searched and I cannot find it anywhere?

Furthermore, I would like to ask if I can expect that `tf.layers` is going to be the standard builder API going forward? Or will you focus on Keras instead? I have previously used PrettyTensor. There is also tf.slim and other builder APIs. I don't want to change builder API every 6 months, so I'd like to know what the TF developers are betting on this time?

**Comment by ujjwal-researcher** [comment]
I too think that there too many movements within the APIs and it is now time that they are stablized.

**Comment by drpngx** [comment]
@fchollet for layers roadmap

**Comment by fchollet** [comment]
There will be a `tf.layers.flatten()` in the future for sure. We are still working on some layer refactoring at the moment, but adding more layers in the core layers module will be the step right after.

**Comment by Hvass-Labs** [comment]
Thanks for the quick answer.

Is your recommendation to use `tf.contrib.layers.flatten()` for the time being? That is not very elegant.

It is a bit hard to understand why such a simple function is not in `tf.layers` already? Is there some technical reason?

**Comment by futurely** [comment]
Only a single line is required to use all the high level ops from layers or its alias [slim](https://github.com/tensorflow/tensorflow/blob/5bb3d62fb2a28ef3cd9f02eeebde82560313905a/tensorflow/contrib/slim/__init__.py).
```python
layers = tf.contrib.layers
layers.flatten()
or
slim = tf.contrib.slim
slim.flatten()
```

**Comment by fchollet** [comment]
@martinwicke, this issue comes up regularly. We should consider adding `tf.layers.flatten`, as previously discussed...

**Comment by martinwicke** [comment]
Sigh. Alright.

**Comment by Hvass-Labs** [comment]
I have now upgraded to TensorFlow 1.3 and this is still missing. I will try my best to be polite, but it is frustrating that you still haven't completed the builder API for TensorFlow. It is more than a year ago that I pleaded with you to consolidate the many builder APIs so we could have a single API that was complete and well-documented. I am struggling to understand why this is not a priority for you. Perhaps we view software engineering differently. To me the API is an incredibly important aspect of any software library. Perhaps Keras is now the most complete API for TensorFlow and it seems there's a person dedicated to its development. Perhaps you should consider making Keras the main builder API then. But please make a decision for one API, stick with it and finish it. Thanks.

**Comment by MeteorKepler** [comment]
Can't agree more! Why there is still no tf.layers.flatten? And the changes of tf over versions are so big that it is a mess when learning

**Comment by thjashin** [comment]
Any update?

**Comment by martinwicke** [comment]
If this is extremely important to you, please do send us a PR.

**Comment by fchollet** [comment]
There is in fact a flatten layer in TF 1.4 in `tf.layers`: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/core.py#L347-L406

In general, feel free to use layers from `tf.keras` in your workflow.

**Comment by thjashin** [comment]
@fchollet THX. Found it. Just wondering if this two will be merged in future? Btw, using keras means one more hierarchy :)

**Comment by jinfagang** [comment]
What's the difference of tf.layers and tf.contrib.slim by the way. they are so many interface are exactly same but with different behaviours, even same codes but totally different error messages, so confusing.

**Comment by Hvass-Labs** [comment]
Just use Keras. I have lost patience with all the other TensorFlow APIs and just use Keras now. It's not perfect and some features are missing or broken, but it's the best TensorFlow API I've found and it's still under serious development so we can expect it to improve in the future.
