### ISSUE TITLE
Issue with tensor flow (undefined symbol: cuDevicePrimaryCtxRetain)

### ISSUE THREAD

**Issue by Lee-L-Boyd** [tensorflow/tensorflow#9866]
When I try to import tensorflow in python I get this issue:
Note: It was working fine yesterday.  It is really strange that today it no longer works.
Also note: This is my first time to ever post a question online, as I prefer to find answers to my own problems.  The issue here is that there is no documentation on this problem online and I am hitting a wall on ideas for once for how to resolve it.  I am using TF without gpu support, but am hopeful the capable team on this git can at least tell me if the problem on my end or not.  I realize it is likely something on my end, but a response to verify that would be helpful, even if the problem is perceived as too simple to bother with.

>>> import tensorflow as tf
Traceback (most recent call last):
  File "/home/student/miniconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/student/miniconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/student/miniconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/student/miniconda3/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/student/miniconda3/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/student/miniconda3/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: cuDevicePrimaryCtxRetain

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/student/miniconda3/lib/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/student/miniconda3/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/student/miniconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/student/miniconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/student/miniconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/student/miniconda3/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/student/miniconda3/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/student/miniconda3/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/student/miniconda3/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: cuDevicePrimaryCtxRetain

**Comment by skye** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary? If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by Lee-L-Boyd** [comment]
Thank you for the response.  It appears to be an issue with Cuda and driver compatibility on an older laptop.  Closing ticket.

**Comment by dahangli** [comment]
How to solve it. I have get the same problem.

**Comment by Lee-L-Boyd** [comment]
Hi,

I didn't actually solve it, other than moving to a newer computer with the
latest version of Linux and a newer gpu.  I would recommend if you are
trying to use cuda, making sure that it is the appropriate version for your
graphics card.  I have an nvidia 720 with Ubuntu 14, and had cuda 6.5
operational, but when I tried to use cuda 8 all these problems popped up.
Check cuda docs and read very thoroughly about their recommended specs for
your gpu.  Also make sure you are removing the newer version of cuda before
replacing it with the older.  Hope that helps!
Lee

**Comment by dahangli** [comment]
I try nvidia 710 with Ubuntu 14.04, and had cuda 8.0 is ok!
I try nvidia 1060 with Ubuntu 14.04, and had cuda 8.0 is Fault!

**Comment by dahangli** [comment]
NVIDIA-Linux-x86_64-375.66.run
cuda_8.0.61_375.26_linux.run
Anaconda3-4.3.1-Linux-x86_64.sh

**Comment by Lee-L-Boyd** [comment]
Wow!  That is strange.  Did you make sure Cuda is functional with some
sample programs?

**Comment by Lee-L-Boyd** [comment]
For example, check to make sure device Query (usr->local->cuda-8.0->samples->1_Utilities->deviceQuery->make) compiles and runs with Cuda.


Sent from my MetroPCS 4G LTE Android device-------- Original message --------From: dahangli <notifications@github.com> Date: 5/18/2017  9:17 PM  (GMT-06:00) To: tensorflow/tensorflow <tensorflow@noreply.github.com> Cc: Lee-L-Boyd <lee.l.boyd@gmail.com>, State change <state_change@noreply.github.com> Subject: Re: [tensorflow/tensorflow] Issue with tensor flow (undefined symbol:
  cuDevicePrimaryCtxRetain) (#9866) 
NVIDIA-Linux-x86_64-375.66.run

cuda_8.0.61_375.26_linux.run

Anaconda3-4.3.1-Linux-x86_64.sh

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/tensorflow/tensorflow","title":"tensorflow/tensorflow","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/tensorflow/tensorflow"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dahangli in #9866: NVIDIA-Linux-x86_64-375.66.run\r\ncuda_8.0.61_375.26_linux.run\r\nAnaconda3-4.3.1-Linux-x86_64.sh"}],"action":{"name":"View Issue","url":"https://github.com/tensorflow/tensorflow/issues/9866#issuecomment-302590573"}}}
