### ISSUE TITLE
www.tensorflow.org/versions/ incorrectly lists 0.12 as the most recent stable branch

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#9872]
https://www.tensorflow.org/versions/ says that 0.12 is most recent stable branch, which is causing new users to install the older version --
https://github.com/tensorflow/tensorflow/issues/9590#issuecomment-301211285

**Comment by jubjamie** [comment]
Duplicate of #8429
Was raised a while ago but no traction just yet!

**Comment by skye** [comment]
Closing as duplicate.
