### ISSUE TITLE
how can creat the module clstm((convolution Long short-term memory)) in tensorflow

### ISSUE THREAD

**Issue by jeansely** [tensorflow/tensorflow#9881]
I wish to implement clstm's network architecture in the tensorflow, to facilitate extension and modifications to the network. already create in module?

**Comment by Carmezim** [comment]
@jeansely this question is better suited for StackOverflow.

**Comment by carlthome** [comment]
Here's an implementation: https://github.com/carlthome/tensorflow-convlstm-cell

**Comment by ali01** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
