### ISSUE TITLE
tf.where bug

### ISSUE THREAD

**Issue by auroua** [tensorflow/tensorflow#9893]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.1.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:cuda 8.0 cuDNN 5.0
- **GPU model and memory**: 1060 6GB
- **Exact command to reproduce**:

```
import tensorflow as tf
import numpy as np

if __name__ == '__main__':
    bool_lists = np.array([[False, True, True, False],
                           [False, False, True, True]])
    k = tf.Variable(tf.zeros(shape=[2, 4], dtype=tf.int32))
    where_val = []
    bool_ops = []
    k_opes = []
    where_ops = []
    for j in range(bool_lists.shape[0]):
        for i in range(bool_lists.shape[1]):
            bool_i = tf.constant(bool_lists[j, i], dtype=tf.bool)
            bool_ops.append(bool_i)
            where_val.append(k[j, i].assign(tf.where(bool_lists[j, i], i, k[j, i])))
            tf_i = tf.constant(i, dtype=tf.int32)
            where_ops.append(tf.where(bool_i, tf_i, k[j, i]))
            k_opes.append(k[j, i])
    with tf.control_dependencies(where_val):
        k = tf.identity(k)
```

The results of above code is:
>[[0 1 2 3]
 [0 1 2 3]]
[False, True, True, False, False, False, True, True]
[0, 1, 2, 3, 0, 1, 2, 3]
[0, 1, 2, 3, 0, 1, 2, 3]

I think the right result of k's value should be:
>[[0 1 2 0]
 [0 0 2 3]]

I just update my tensorflow for 1.0 to 1.1.0. I remember  version 1.0 is right.

The following is results from tf 1.0:
>[[0 1 2 0]
 [0 0 2 3]]
[False, True, True, False, False, False, True, True]
[0, 1, 2, 0, 0, 0, 2, 3]
[0, 1, 2, 0, 0, 0, 2, 3]

**Comment by ali01** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by auroua** [comment]
Thanks for you reply!
