### ISSUE TITLE
Little issues in documentation

### ISSUE THREAD

**Issue by melvyniandrag** [tensorflow/tensorflow#9896]
What is the proper forum for contributing / discussing documentation errors?

There are dead links on this page: https://www.tensorflow.org/tutorials/deep_cnn

and in the "Manual Device Placement" section of this page https://www.tensorflow.org/tutorials/using_gpu
a, b and the result of the matmul should all be on the cpu, but the output in the docs shows that the matmul is done on the gpu.

```
Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: Tesla K40c, pci bus
id: 0000:05:00.0
b: /job:localhost/replica:0/task:0/cpu:0
a: /job:localhost/replica:0/task:0/cpu:0
MatMul: /job:localhost/replica:0/task:0/gpu:0
[[ 22.  28.]
 [ 49.  64.]]

```

I'm working through a bunch of the tutorials today and if I find any issues I can let you know via the appropriate forum if you want. It's hard to keep up with the documentation!

**Comment by concretevitamin** [comment]
We would love to see pull requests from the community to make TensorFlow better!  Please take a look at [this contributing guide](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md).  The doc you referred to reside in the [`docs_src` directory](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src).

Closing this as this question has been answered - feel free to reference this issue if/when you open pull requests to fix the docs ;)
