### ISSUE TITLE
Support for float16 in tf.layers

### ISSUE THREAD

**Issue by untom** [tensorflow/tensorflow#9898]
It seems like `tf.layers.*` do not support `tf.float16`, because they rely on the default value handed to the `_Layer` superclass [here](https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/python/layers/base.py#L64). It would be great if tf.float16 could be supported there.

**Comment by concretevitamin** [comment]
@fchollet

**Comment by fchollet** [comment]
You can always instantiate a layer with `dtype=tf.float16`, causing its weights to be created in fp16, making it callable on fp16 inputs. Any layer would work.

**Comment by untom** [comment]
The layers in `tf.layers` do not accept a `dtype` argument, that is my whole point.

**Comment by fchollet** [comment]
All layers support the `dtype` argument. But I see what you mean now. You mean "the functional interfaces to core layers don't have the dtype argument in their signature". That's right. I would suggest adding it.

**Comment by lakshayg** [comment]
I am interested in taking up this issue. Should I send in a pull request?

**Comment by qmick** [comment]
@skye This issue can be closed now because fp16 support has been already added by commit cc1a02d.
