### ISSUE TITLE
GPU device not found on Ubuntu 14.04

### ISSUE THREAD

**Issue by kibtes** [tensorflow/tensorflow#990]
I have installed tensorflow python3 version using virtual environment on Ubuntu 14.04. There are three GPUs (Tesla K20c) available on the server that i work on.

On the tensorflow webpage it says: "In general you do not have to specify CPUs or GPUs explicitly. TensorFlow uses your first GPU, if you have one, for as many operations as possible."

When i checked the examples provided on Using GPUs about using multi-GPUs 

import tensorflow as tf

# Creates a graph.
c = []
for d in ['/gpu:1', '/gpu:2']:
  with tf.device(d):
    a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[2, 3])
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2])
    c.append(tf.matmul(a, b))
with tf.device('/cpu:0'):
  sum = tf.add_n(c)
# Creates a session with log_device_placement set to True.
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))
# Runs the op.
print(sess.run(sum))

the following error was displayed:

I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library                                    libcublas.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library                                    libcudnn.so.6.5 locally
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library                                    libcufft.so.7.0 locally
I tensorflow/stream_executor/dso_loader.cc:93] Couldn't open CUDA library libcud                                   a.so. LD_LIBRARY_PATH: :/usr/local/cuda/lib64
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:121] hostname: dmlserver
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:146] libcuda reported vers                                   ion is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:257] driver version file c                                   ontents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  346.96  Sun Aug 23 2                                   2:29:21 PDT 2015
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:150] kernel reported versi                                   on is: 346.96
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1060] LD_LIBRARY_PATH: :/                                   usr/local/cuda/lib64
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1061] failed to find libc                                   uda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so; dl                                   error: libcuda.so: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:101] successfully opened CUDA library                                    libcurand.so.7.0 locally
I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op paral                                   lelism threads: 16
E tensorflow/stream_executor/cuda/cuda_driver.cc:481] failed call to cuInit: CUD                                   A_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:114] retrieving CUDA diagn                                   ostic information for host: dmlserver
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:121] hostname: dmlserver
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:146] libcuda reported vers                                   ion is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:257] driver version file c                                   ontents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  346.96  Sun Aug 23 2                                   2:29:21 PDT 2015
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:150] kernel reported versi                                   on is: 346.96
I tensorflow/core/common_runtime/gpu/gpu_init.cc:127] DMA:
I tensorflow/core/common_runtime/direct_session.cc:58] Direct session inter op p                                   arallelism threads: 16
Device mapping: no known devices.
I tensorflow/core/common_runtime/direct_session.cc:134] Device mapping:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/tensorflow/python/client/session.py", l                                   ine 428, in _do_run
    target_list)
tensorflow.python.pywrap_tensorflow.StatusNotOK: Invalid argument: Cannot assign                                    a device to node 'Const_3': Could not satisfy explicit device specification '/g                                   pu:2'
         [[Node: Const_3 = Const[dtype=DT_FLOAT, value=Tensor<type: float shape:                                    [3,2] values: 1 2 3...>, _device="/gpu:2"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "checking_2.py", line 15, in <module>
    print(sess.run(sum))
  File "/usr/lib/python3.4/site-packages/tensorflow/python/client/session.py", l                                   ine 368, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/lib/python3.4/site-packages/tensorflow/python/client/session.py", l                                   ine 444, in _do_run
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device                                    to node 'Const_3': Could not satisfy explicit device specification '/gpu:2'
         [[Node: Const_3 = Const[dtype=DT_FLOAT, value=Tensor<type: float shape:                                    [3,2] values: 1 2 3...>, _device="/gpu:2"]()]]
Caused by op 'Const_3', defined at:
  File "checking_2.py", line 8, in <module>
    b = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0], shape=[3, 2])
  File "/usr/lib/python3.4/site-packages/tensorflow/python/ops/constant_op.py",                                    line 165, in constant
    attrs={"value": tensor_value, "dtype": dtype_value}, name=name).outputs[0]
  File "/usr/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", li                                   ne 1834, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/lib/python3.4/site-packages/tensorflow/python/framework/ops.py", li                                   ne 1043, in __init__
    self._traceback = _extract_stack()

Don't understand what the problem is? Need URGENT help!!!

**Comment by caisq** [comment]
See my comments at: https://github.com/tensorflow/tensorflow/issues/808#issuecomment-178854998

**Comment by kibtes** [comment]
@caisq  i followed the first three steps in the comments you referred me to and ended up with this:
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 35
-> CUDA driver version is insufficient for CUDA runtime version
Result = FAIL

what to do next?

**Comment by caisq** [comment]
@kibtes Did you try "sudo ./deviceQuery"?

**Comment by kibtes** [comment]
@caisq  yes this is the result of it 
root@dmlserver:/home/dmlserver/NVIDIA_CUDA-7.0_Samples/bin/x86_64/linux/release# sudo ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 35
-> CUDA driver version is insufficient for CUDA runtime version
Result = FAIL

**Comment by caisq** [comment]
@kibtes  As the error message says "-> CUDA driver version is insufficient for CUDA runtime version", you need to check the version of your NVIDIA driver.

sudo apt --installed list | grep nvidia

Most likely you'll need to uninstall the current one, and install a later version. I ran int a similar situation before. I uninstalled nvidia-340 and installed nvidia-352.

**Comment by vrv** [comment]
Closing since it looks like it's a system environment issue.

**Comment by zhujunbang** [comment]
123

**Comment by zhujunbang** [comment]
怎么解决，没找到方法
