### ISSUE TITLE
DNNClassifier and GridSearchCV example

### ISSUE THREAD

**Issue by snassimr** [tensorflow/tensorflow#9900]
Hi , 

I am trying to run an gridsearch example in [https://github.com/petewarden/tensorflow_makefile/blob/master/tensorflow/contrib/learn/python/learn/tests/test_grid_search.py](url)
If example inside testIrisDNN intend to be working ?

I am getting 

> TypeError: __init__() got an unexpected keyword argument 'params'

**Comment by petewarden** [comment]
This bug is against a temporary fork of the TensorFlow source code I did for development purposes unfortunately, so it's not going to be possible to debug what's going wrong here. Closing for now, but please reopen if you are able to reproduce this on the main https://github.com/tensorflow/tensorflow source code.

**Comment by rickiepark** [comment]
Hi, I ran same code in grid_search_test.py and got the same error in TF 1.3.0, scikit-learn 0.19
Have you any idea?

import tensorflow as tf
from tensorflow.contrib import learn
from sklearn.model_selection import GridSearchCV
from sklearn import datasets
iris = datasets.load_iris()
feature_columns = learn.infer_real_valued_columns_from_input(iris.data)
classifier = learn.DNNClassifier(feature_columns=feature_columns, hidden_units=[10, 20, 10], n_classes=3)
grid_search = GridSearchCV(classifier, {'hidden_units': [[5, 5], [10, 10]]}, scoring='accuracy', fit_params={'steps': [50]})
grid_search.fit(iris.data, iris.target)


/Users/rickypark/anaconda/envs/handson-ml/lib/python3.6/site-packages/sklearn/model_selection/_search.py:583: DeprecationWarning: "fit_params" as a constructor argument was deprecated in version 0.19 and will be removed in version 0.21. Pass fit parameters to the "fit" method instead.
  '"fit" method instead.', DeprecationWarning)
\---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-995caf033e7d> in <module>()
----> 1 grid_search.fit(iris.data, iris.target)

~/anaconda/envs/handson-ml/lib/python3.6/site-packages/sklearn/model_selection/_search.py in fit(self, X, y, groups, **fit_params)
    622                                      n_candidates * n_splits))
    623
--> 624         base_estimator = clone(self.estimator)
    625         pre_dispatch = self.pre_dispatch
    626

~/anaconda/envs/handson-ml/lib/python3.6/site-packages/sklearn/base.py in clone(estimator, safe)
     60     for name, param in six.iteritems(new_object_params):
     61         new_object_params[name] = clone(param, safe=False)
---> 62     new_object = klass(**new_object_params)
     63     params_set = new_object.get_params(deep=False)
     64

TypeError: __init__() got an unexpected keyword argument 'params'
