### ISSUE TITLE
Mac nightlies blocked by failing test in contrib

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#9903]
Last Mac nightly is May 1st

Looking at the last failure it seems it was caused by contrib
//bazel_pip/tensorflow/contrib/batching:batch_ops_test                   FAILED in 1 out of 2 in 14.5s

Since /contrib/ packages don't always have maintainers, should the "Success" criteria perhaps be relaxed to still release the pip package if some /contrib/ thing fail? @martinwicke 

https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-cpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=mac-slave/

**Comment by martinwicke** [comment]
The problem here is actually that all our Mac workers are offline. We'll
make new nightlies as soon as they come back.
