### ISSUE TITLE
tf.self_adjoint_eig doesn't behave the same way with float32 and float64

### ISSUE THREAD

**Issue by jrabary** [tensorflow/tensorflow#9916]
Here is an example to reproduce the problem

```
l = tf.constant([[10., -4., -4., -2.],
                  [-4., 10., -2., -4.],
                  [-4., -2., 6., 0.],
                  [-2., -4., 0., 6.]], dtype=tf.float64)
e, v = tf.self_adjoint_eig(tf.expand_dims(l, 0))
```

When I set `dtype=tf.float64` the output is

```
// Eigen values
[[ -2.31986627e-15   5.52786405e+00   1.20000000e+01   1.44721360e+01]]

// Eigen vectors
[[-0.5        -0.16245985  0.5        -0.68819096]
 [-0.5         0.16245985  0.5         0.68819096]
 [-0.5        -0.68819096 -0.5         0.16245985]
 [-0.5         0.68819096 -0.5        -0.16245985]]
```

When `dtype=tf.float32` the output is

```
// Eigen values
[[ -1.02379988e-06   5.52786446e+00   1.20000019e+01   1.44721375e+01]]

// Eigen vectors
[[ 0.49999985  0.16245979  0.49999985 -0.68819106]
 [ 0.5        -0.16246006  0.50000018  0.68819082]
 [ 0.5         0.68819106 -0.49999988  0.16246004]
 [ 0.49999991 -0.68819088 -0.50000012 -0.16245979]]
```
In this case the sign of the second eigen vector changed.

The numpy equivalent of this code always give the same result (in float or float32) and is similar to the result I got with the tf.float64 version

```
L = np.array([[10., -4., -4., -2.],
                  [-4., 10., -2., -4.],
                  [-4., -2., 6., 0.],
                  [-2., -4., 0., 6.]])
D, V =np.linalg.eigh(L)
```

```
// numpy eigen values
[  1.11716192e-15   5.52786405e+00   1.20000000e+01   1.44721360e+01]

// numpy eigen vectors
[[ 0.5        -0.16245985  0.5        -0.68819096]
 [ 0.5         0.16245985  0.5         0.68819096]
 [ 0.5        -0.68819096 -0.5         0.16245985]
 [ 0.5         0.68819096 -0.5        -0.16245985]]
```

**Comment by yaroslavvb** [comment]
Note that this matrix has rank 3, and the eigenvector in question corresponds to 0 eigenvalue.

Also note that both 0.5,0.5,0.5,0.5 and -0.5,-0.5,-0.5,-0.5 are valid normalized eigenvectors.

So, from the description of the function it seems the behavior is correct. I agree that it would be less surprising to have more deterministic behavior. Maybe an additional constraint to always have first component of eigenvector be positive? cc @rmlarsen

**Comment by jrabary** [comment]
@yaroslavvb my problem here is not the first eigen vector but the second one. It goes from -0.16, 0.16, -0.68, 0.68 to 0.16, -0.16, 0.68, -68 with the same eigen value. And it changes every thing.

**Comment by yaroslavvb** [comment]
@jrabary same thing here, they are both correct eigenvectors

**Comment by jrabary** [comment]
@yaroslavvb I understand. In fact, additional constraint will be help full here to get consistent result accross run.

**Comment by skye** [comment]
I'm gonna mark this as a feature request, since it seems like this behavior is correct but potentially confusing.

**Comment by bhack** [comment]
We could close this. I think that with nightly the signs are correct:
```
tf.Tensor([[-2.31986627e-15  5.52786405e+00  1.20000000e+01  1.44721360e+01]], shape=(1, 4), dtype=float64)
tf.Tensor(
[[[-0.5        -0.16245985  0.5        -0.68819096]
  [-0.5         0.16245985  0.5         0.68819096]
  [-0.5        -0.68819096 -0.5         0.16245985]
  [-0.5         0.68819096 -0.5        -0.16245985]]], shape=(1, 4, 4), dtype=float64)

tf.Tensor([[-2.06638583e-06  5.52786446e+00  1.20000000e+01  1.44721365e+01]], shape=(1, 4), dtype=float32)
tf.Tensor(
[[[-0.5        -0.16245994  0.49999976 -0.688191  ]
  [-0.5000001   0.1624598   0.5000002   0.6881908 ]
  [-0.49999988 -0.68819094 -0.5000001   0.16246   ]
  [-0.50000006  0.688191   -0.49999994 -0.16245969]]], shape=(1, 4, 4), dtype=float32)

```

**Comment by chunduriv** [comment]
@jrabary,

I tried in colab with `Tensorflow 2.8` and i didn't see any discrepancy in behave between `float32` and `float64`. Please, find the gist [here](https://colab.research.google.com/gist/chunduriv/e7e09e8f87d9b14a23308ce54deb1199/9916.ipynb).Thanks!

**Comment by chunduriv** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
