### ISSUE TITLE
Some small problems with the RNN and seq2seq implementations

### ISSUE THREAD

**Issue by dugu9sword** [tensorflow/tensorflow#9927]
1. In the class `AttentionCellWrapper` , https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/rnn/python/ops/rnn_cell.py#L1116  , maybe the `lstm_output` should be replaced by some other token, since the wrapper is not specified for LSTM.

2.  In the class `Decoder`, https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/seq2seq/python/ops/decoder.py#L90 , I think the `step()` method should not return an output as an instance of `BasicDecoderOutput`. From an object-oriented-programming view, the `BasicDecoder` is an inheritance of `Decoder`, the basic class should not have access to something designed for the inherited class, the same problem exists in the `dynamic_decode` method.

**Comment by ali01** [comment]
@ebrevdo, any thoughts?

**Comment by ebrevdo** [comment]
Issue 2 is a documentation issue.  We only have one type of decoder right now so we just need to change it to something like "an object containing the decoder output".  PRs welcome.

Issue 1 - we're not really focusing on that attention wrapper (i would like to mark it deprecated).  We have a more comprehensive attention wrapper in tf.contrib.seq2seq.AttentionWrapper.  In the meantime, PRs changing the variable name inside that function are welcome.

**Comment by jalammar** [comment]
Added pull request (https://github.com/tensorflow/tensorflow/pull/11049) addressing these two points.

**Comment by qmick** [comment]
@ebrevdo This issue was fixed by #11049 and can be closed now.
