### ISSUE TITLE
Compiling tensorflow 1.1 under Centos 7

### ISSUE THREAD

**Issue by rdaiasy** [tensorflow/tensorflow#9929]
I'm trying to compile tensorflow with cuda support under linux Centos 7 distribution.

I followed the instructions provides at [github: gentaiscool/tensorflow.md ](https://gist.github.com/gentaiscool/a628fab5cd98953af7f46b69463394b3) with no success.

In this page they ask for hacking the file tensorflow/third_party/gpus/crosstool/CROSSTOOL (adding the line "cxx_builtin_include_directory : "/usr/local/cuda/targets/x86_64-linux/include").

In the current version of Tensorflow (1.1) there is no such a file; similar files, such as: CROSSTOOL.tpl, CROSSTOOL_nvcc.tpl, CROSSTOOL_clang.tpl, are found. I tried the proposed hacking on each of these files and didn't get successful compilation.

Since I'm interested is tensorflow deployment, I'm compiling it using the instructions found in [gitgub cjweeks/tensorflow-cmake](https://github.com/cjweeks/tensorflow-cmake) (building a library to be linked with a C++ based program). My build command is:

`bazel build -c opt --config=cuda tensorflow:libtensorflow_all.so`

The error I've got is:

`ERROR: /root/tensorflow/tensorflow/core/kernels/BUILD:3004:1: undeclared inclusion(s) in rule '//tensorflow/core/kernels:depth_space_ops_gpu':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/kernels/spacetodepth_op_gpu.cu.cc':
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/limits.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/syslimits.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stddef.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdarg.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdint.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/x86intrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/ia32intrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/mmintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/xmmintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/mm_malloc.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/emmintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/immintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/fxsrintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/adxintrin.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/float.h'
  '/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include/stdbool.h'.`

System information:

- Linux Centos 7.2
- Kernel: 3.10.0-327.36.1.el7.x86_64
- Compiler: gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)
- Tensorflow: 1.1, installed from source.
- nvcc: Cuda compilation tools, release 8.0, V8.0.44
- CUDA: 8.0
- cudaa: 5.1.5
- bazel: 0.4.5

Any help please?

Thanks in advance,

Ron.

**Comment by drpngx** [comment]
Did you try adding `/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include` as a builtin directory?

**Comment by rdaiasy** [comment]
Hi drpngx,

Thanks for your response...

How do I add this directory as a builtin directory?

Regards,
Ron.

**Comment by drpngx** [comment]
Please add it to `CROSSTOOL.tpl` or the `nvcc` version if you are using NVCC.

**Comment by rdaiasy** [comment]
Hi drpngx,

Tried your proposal getting the same errors. 

I did the following:

In CROSSTOOL_nvcc.tpl I replaced the line:
`cxx_builtin_include_directory: "/"`
with this line:
`cxx_builtin_include_directory: "/usr/lib/gcc/x86_64-redhat-linux/4.8.5/include"`

Any additional proposal?

Thanks,
Ron

**Comment by drpngx** [comment]
Did you try in `CROSSTOOL.tpl`? Also try adding the line, not replacing the existing one.

**Comment by gunan** [comment]
I remember from my experiments in a docker container that this was caused by missing header installation.
reinstalling glibc gcc and g++ through yum solved the issue when I tried this.

However, Tensorflow does not have official support for CentOS.
As the instructions you found were in a non-TF repository, I recommend reaching out to the author of those instructions.

**Comment by daisyron** [comment]
Tried you suggestions without success :-( - got same error...

**Comment by gunan** [comment]
Using latest TF version, and bazel version 0.8.1 or later, this problem seems to be gone. For more information see #14380
