### ISSUE TITLE
How to run nvidia-docker with TensorFlow GPU docker

### ISSUE THREAD

**Issue by bcordo** [tensorflow/tensorflow#993]
Thanks for looking at my issue, really appreciate it. 

### What I've Done
I have setup an equivalent of a Nvidia DIGITS machine (running Ubuntu 14.04 server), and am attempting to run everything in docker containers.

1. I have docker installed, and have run `nvidia-docker run nvidia/cuda nvidia-smi` described [here](https://github.com/NVIDIA/nvidia-docker), and I see my 4 TitanX graphic cards. 

2. I have also run the nvidia-docker-plugin described [here](https://github.com/NVIDIA/nvidia-docker/wiki/Using-nvidia-docker-plugin) as `sudo -u nvidia-docker nvidia-docker-plugin -s /var/lib/nvidia-docker` and I get the output:

```
nvidia-docker-plugin | 2016/02/04 12:54:02 Loading NVIDIA management library
nvidia-docker-plugin | 2016/02/04 12:54:04 Loading NVIDIA unified memory
nvidia-docker-plugin | 2016/02/04 12:54:04 Discovering GPU devices
nvidia-docker-plugin | 2016/02/04 12:54:05 Provisioning volumes at /var/lib/nvidia-docker/volumes
nvidia-docker-plugin | 2016/02/04 12:54:05 Serving plugin API at /var/lib/nvidia-docker
nvidia-docker-plugin | 2016/02/04 12:54:05 Serving remote API at localhost:3476
```
which signifies to me that it's working.

3. I ran the tests [here](https://github.com/NVIDIA/nvidia-docker/wiki/Testing-the-samples) and they all passed. 

### My Problem

4. When I try to run the [TensorFlow GPU docker image](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker) using nvidia-docker

I first run `sudo -u nvidia-docker nvidia-docker-plugin -s /var/lib/nvidia-docker` in a tmux session. 

Then I run `nvidia-docker run -it -p 8888:8888 b.gcr.io/tensorflow/tensorflow-devel-gpu` it downloads everything and runs the docker container. Next I run ipython and try to import tensorflow but I get the following errors:

```
In [1]: import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:92] LD_LIBRARY_PATH: /usr/local/cuda/lib64
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:121] hostname: 16b84b6e71f9
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:146] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:257] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  352.79  Wed Jan 13 16:17:53 PST 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)
"""
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:150] kernel reported version is: 352.79
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1054] LD_LIBRARY_PATH: /usr/local/cuda/lib64
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1055] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so; dlerror: libcuda.so: cannot open shared object file: No such file or directory
```

**I think I just have a lack in understanding about how I should run the TensorFlow container, or maybe I have to build the container using nvidia-docker. 

Any ideas about how to do this, or general advice about what I'm doing wrong would be amazing. **

Thanks so much.

Brad

**Comment by caisq** [comment]
Does this help? https://github.com/tensorflow/tensorflow/issues/808#issuecomment-178854998

**Comment by bcordo** [comment]
For future people stuck on this, the solution that worked for me is documented here:

https://github.com/NVIDIA/nvidia-docker/issues/45

Thanks for the response @caisq!
