### ISSUE TITLE
Classification model for Imagenet classification tutorial

### ISSUE THREAD

**Issue by oweingrod** [tensorflow/tensorflow#994]
Hi!

I'm an engineer looking to work with Tensorflow for computer vision applications. My team was looking into the Imagenet classification tutorial provided via the Tensorflow website and the github files at /models/image/imagenet and have become a little stumped. There's no information on how the classification model was built (like their was for the MNIST tutorials), and there is no information on the graph that has been used for in the classify_image.py file, aside from a convoluted binary .pb file.

Is there any more information on how to define and train the Inception model (or any other classifier) with the Imagenet training set? Or how to create the graph? Or, has this information been made unavailable to the public?

Thanks

Oren 

ps: sorry for writing this in an issue—was having trouble trying to find a better place to put it.

**Comment by martinwicke** [comment]
We are in the process of publishing the trainable version of this, but we need some time to untangle it from our infrastructure.
