### ISSUE TITLE
Compiling Error with empty error message

### ISSUE THREAD

**Issue by wqj97** [tensorflow/tensorflow#9940]
OS: centos 7.2 x64
TensorFlow installed from: source
TensorFlow version: r1.1 
Bazel: 0.45
CPU-only
```
 bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-msse4.2 --copt=-msse4.1 --copt=-msse3 --copt=-mfma -k //tensorflow/tools/pip_package:build_pip_package
```

![](https://cloud.githubusercontent.com/assets/18662395/26121841/2930b0ac-3aa8-11e7-8cb5-65cb3b0b847e.png)

and I check log file, It's an empty file
then I tried again 
exit with this: 
```
[1,801 / 2,762] Compiling tensorflow/core/graph/validate.cc

Server terminated abruptly (error code: 14, error message: '', log file: '/root/.cache/bazel/_bazel_root/bc2bd5c039dfc4a14bebd99e0322728d/server/jvm.out')
```

**Comment by skye** [comment]
This is probably an environment/setup issue and not a bug, so is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). There is also a larger community that reads questions there. Thanks!

**Comment by wqj97** [comment]
thx!
