### ISSUE TITLE
Tensorflow Layers conv3d_transpose

### ISSUE THREAD

**Issue by cameronfabbri** [tensorflow/tensorflow#9943]
I'm trying to use 3D transpose convolutions found [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/convolutional.py#L1376), but they are not available in the current build of Tensorflow when installing using pip. On another machine I was successfully able to build Tensorflow from source because I already had Bazel installed on my system, and then able to use the 3d transpose convolutions.

However, on a new machine without Bazel, I am unable to install Bazel, and therefore unable to compile Tensorflow from source. It appears that the Java project has moved. Below is the result of running `sudo apt-get install openjdk-8-jdk`, as per the instructions [here](https://bazel.build/versions/master/docs/install-ubuntu.html#install-compile-source.html).

`Setting up oracle-java9-installer (9b162-1~webupd8~0) ...
Using wget settings from /var/cache/oracle-jdk9-installer/wgetrc
Downloading Oracle Java 9...
--2017-05-16 14:23:32--  http://www.java.net/download/java/jdk9/archive/162/binaries/jdk-9-ea+162_linux-x64_bin.tar.gz
Resolving www.java.net (www.java.net)... 137.254.56.25
Connecting to www.java.net (www.java.net)|137.254.56.25|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://home.java.net/download/java/jdk9/archive/162/binaries/jdk-9-ea+162_linux-x64_bin.tar.gz [following]
--2017-05-16 14:23:33--  https://home.java.net/download/java/jdk9/archive/162/binaries/jdk-9-ea+162_linux-x64_bin.tar.gz
Resolving home.java.net (home.java.net)... 156.151.59.19
Connecting to home.java.net (home.java.net)|156.151.59.19|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.oracle.com/splash/java.net/maintenance/index.html [following]
--2017-05-16 14:23:33--  http://www.oracle.com/splash/java.net/maintenance/index.html
Resolving www.oracle.com (www.oracle.com)... 23.209.61.60, 2600:1418:3:1a2::2d3e, 2600:1418:3:18b::2d3e
Connecting to www.oracle.com (www.oracle.com)|23.209.61.60|:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2017-05-16 14:23:33 ERROR 503: Service Unavailable.
download failed.
Oracle JDK 9 is NOT installed.
dpkg: error processing package oracle-java9-installer (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 oracle-java9-installer
E: Sub-process /usr/bin/dpkg returned an error code (1)
`

Is there a way around this, or a timeframe when the new Tensorflow Layers will be included in the pip download?

**Comment by ali01** [comment]
Hi @cameronfabbri, I'd recommend asking this question on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
