### ISSUE TITLE
Would you please accomodate for building tensorflow with a custom clang (4.0.0) and libc++ instead of stdlibc++? 

### ISSUE THREAD

**Issue by HFTrader** [tensorflow/tensorflow#9951]
I have a custom clang with additional optimization passes but I cant get TS compiled with it. 

$ bazel build --cxxopt=-std=c++11 --cxxopt=-stdlib=libc++ tensorflow:libtensorflow.so
INFO: Found 1 target...
INFO: From Compiling external/protobuf/src/google/protobuf/compiler/js/embed.cc [for host]:
external/protobuf/src/google/protobuf/compiler/js/embed.cc:37:12: warning: unused variable 'output_file' [-Wunused-const-variable]
const char output_file[] = "well_known_types_embed.cc";
           ^
1 warning generated.
ERROR: /home/hbucher/.cache/bazel/_bazel_hbucher/ad427c7fddd5b68de5e1cfaa7cd8c8cc/external/com_googlesource_code_re2/BUILD:11:1: undeclared inclusion(s) in rule '@com_googlesource_code_re2//:re2':
this rule is missing dependency declarations for the following files included by 'external/com_googlesource_code_re2/re2/bitstate.cc':
  '/home/hbucher/install/include/c++/v1/stddef.h'
  '/home/hbucher/install/include/c++/v1/__config'

**Comment by ali01** [comment]
Thank  you @HFTrader, noted. Support for custom builds of clang isn't a high priority for us right now, but I'm opening this up for community support.

**Comment by byronyi** [comment]
How about the [gpucc](http://llvm.org/docs/CompileCudaWithLLVM.html) that developed by Google? Enabling clang compilation may have some potential performance gain, according to [this slides](http://llvm.org/devmtg/2015-10/slides/Wu-OptimizingLLVMforGPGPU.pdf).

**Comment by bhack** [comment]
Can we close this?

**Comment by HFTrader** [comment]
who really cares - it's been +4 years

**Comment by mohantym** [comment]
Hi @HFTrader ,Could you please check out the new [Tensorflow manual](https://www.tensorflow.org/install/source) here for building from Source.  
Also It  seems that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.6 version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!
