### ISSUE TITLE
Tensorboard parsing graph.pbtxt failed after uploaded by by web UI

### ISSUE THREAD

**Issue by luchensk** [tensorflow/tensorflow#9953]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 10.12.4
- **TensorFlow installed from (source or binary)**: install binary with cpu version by pip based on Python 2.7.13
- **TensorFlow version (use command below)**: ('v1.1.0-rc0-61-g1ec6ed5', '1.1.0')
- **Bazel version (if compiling from source)**: none
- **CUDA/cuDNN version**: only use cpu version
- **GPU model and memory**: none
- **Exact command to reproduce**: just upload event file by web UI on 'GRAPH'

### Describe the problem
After uploaded the event file by web UI('GRAPH' table), it failed at the point of parsing graph.pbtxt with the error 'Cannot read property '' of undefined' as below. But it works fine for the cmd of 'tensorboard --logdir=xxx'.

Error info from chrome dev tool(console):
tf-tensorboard.html:9827 Uncaught TypeError: Cannot read property '' of undefined
    at addAttribute (tf-tensorboard.html:9827)
    at tf-tensorboard.html:9859
    at readHandler (tf-tensorboard.html:9729)
    at FileReader.file.onload (tf-tensorboard.html:9744)

**Comment by ali01** [comment]
Hi @luchensk, does this happen consistently with any graph.pbtxt file that you upload, or did it just happen that one time? If the former, are you able to paste the graph.pbtxt file you were using in a [gist](http://gist.github.com) and send over the link?

**Comment by luchensk** [comment]
Thanks Ali for the quick response. The issue happens consistently and the graph.phtxt is as below as the attachment. 
[events.out.tfevents.1494834183.ali-186590d30ecd.local.zip](https://github.com/tensorflow/tensorflow/files/1009903/events.out.tfevents.1494834183.ali-186590d30ecd.local.zip)

I also attached the graph from the zip file by the cmd of 'tensorboard --logdir=xxx', which you can refer to if needed.
![graph-run](https://cloud.githubusercontent.com/assets/28526467/26188879/4d544976-3bd4-11e7-8be4-6d6f638a6c93.png)

Just let me know if need any info, thanks again.

**Comment by luchensk** [comment]
Hi @ali01 and @aselle , is there some update? Thanks.

**Comment by ali01** [comment]
Hi @luchensk, the file you attached does not seem to be a graph.pbtxt file, which might explain why the Web UI is having trouble parsing it. One way of getting a graph.pbtxt file from your graph is to do the following within your TensorFlow program:

    graph_def = g.as_graph_def()
    f.write(text_format.MessageToString(graph_def))

Let me know if this works.

**Comment by dandelionmane** [comment]
As Ali correctly diagnosed, the upload button only accepts graph pbtxts, not event files. Closing this issue.

**Comment by luchensk** [comment]
Yes, please close this issue, thanks.
