### ISSUE TITLE
MatchPath Implementation

### ISSUE THREAD

**Issue by eaplatanios** [tensorflow/tensorflow#9955]
Hi,

I can't seem to find the implementation of the "MatchPath" function. I understand this depends on the environment being used, but is there a default implementation somewhere? I want to find out the details of how the path patterns are treated in TensorFlow so I can write a converter from a TF pattern to a regex and use it within another language that has no access to the TF file IO library.

Thanks,
Anthony

**Comment by ali01** [comment]
Hi @eaplatanios, the posix implementation of MatchPath simply calls fnmatch (defined in <fnmatch.h>. See (posix/env.cc)[https://github.com/tensorflow/tensorflow/blob/4c192f060cf9ff897911d240c140299d6db257b6/tensorflow/core/platform/posix/env.cc].

**Comment by ali01** [comment]
Closing this issue. 

If the above doesn't answer your question, please ask it on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
