### ISSUE TITLE
how to switch between cpu and gpu mode?

### ISSUE THREAD

**Issue by micklexqg** [tensorflow/tensorflow#9956]
Hi,
I have installed tensorflow-gpu.  I want to employ the cpu mode, whether i need to install tensorflow for cpu?
and if the two are all installed, how to switch between them?

**Comment by dugu9sword** [comment]
Use this code:
```
with device("/cpu:0")
```

**Comment by utkarsh39** [comment]
You don't need to install for CPU. CPU installation is by default. Using `with device("/cpu:0")` will make all your operations run in CPU explicitly. To check the device placement i.e. where your operation is being executed you can take a look at the _LOG_DEVICE_PLACEMENT_ flag.

**Comment by micklexqg** [comment]
@utkarsh39 , you mean  just installing  tensorflow-gpu is ok?  where is  LOG_DEVICE_PLACEMENT flag?
I am a newer, thanks your help.

**Comment by micklexqg** [comment]
@dugu9sword , thanks , i will have a try.

**Comment by yaroslavvb** [comment]
Closing this issue since it does not require attention of tensorflow developers
