### ISSUE TITLE
Placeholder modification behavior

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorflow#9960]
I am using Tensorflow 1.0.1, on Mac OS Sierra 10.12.4, with CPU in a jupyter notebook (but the behavior I am describing appeared in a regular python script too).

The problem I am having is with placeholders. I have been using tensorflow for only 1 month so I was not really comfortable with using them and I made a mistake that took me a very long time to debug.
Here is the type of code I wrote:
```python
import numpy as np
import tensorflow as tf
x_ = tf.placeholder(tf.float64, [5])
x_ = tf.where(tf.is_nan(x_), tf.zeros_like(x_), x_)
a = tf.constant(1, shape=[5])
a = tf.cast(a, tf.float64)
c = a + x_
init_op = tf.group(
    tf.global_variables_initializer(),
    tf.local_variables_initializer())
sess = tf.Session()
sess.run(init_op)
x = np.arange(5, dtype=float)
x[3] = np.nan
sess.run(c, feed_dict={x_: x})
```
To this, the output was: `array([  1.,   2.,   3.,  nan,   5.])`, which is not what I expected since I had replaced all the `nan` with the `tf.where`. I understood only later that it was because tensorflow was feeding the placeholder in the latest position it appeared (maybe not exactly how it's implemented, but empirically, that is what happens).
Therefore a good (in the sense of what I intended to do) code is:
```python
import numpy as np
import tensorflow as tf
x_ = tf.placeholder(tf.float64, [5])
r = x_
r = tf.where(tf.is_nan(r), tf.zeros_like(r), r)
a = tf.constant(1, shape=[5])
a = tf.cast(a, tf.float64)
c = a + r
init_op = tf.group(
    tf.global_variables_initializer(),
    tf.local_variables_initializer())
sess = tf.Session()
sess.run(init_op)
x = np.arange(5, dtype=float)
x[3] = np.nan
sess.run(c, feed_dict={x_: x})
```
This indeed outputs `array([ 1.,  2.,  3.,  1.,  5.])`. However, to me it's a bit weird that you would need to throw in an extra variable to achieve this purpose and even weirder that I didn't receive any error when modifying my placeholder.
My suggestions are:
- Throw an error or a warning when reallocating a placeholder.
- State clearly that placeholders are not meant to be modified (I looked for it in the docs and didn't find it, maybe I didn't look well enough).
- Allow placeholders to be modified (might be offputting for someone who understands it well).

**Comment by skye** [comment]
Hi @zaccharieramzi, I would argue this is just how Python works. In your code, you're not actually reallocating or modifying your original placeholder, but reassigning the x_ variable, and then feeding the new x_ value (which is the where op):
```python
x_ = tf.placeholder(tf.float64, [5])
x_ = tf.where(tf.is_nan(x_), tf.zeros_like(x_), x_)
...
sess.run(c, feed_dict=x_: x)
```

This is analogous to doing something like:
```python
x_ = 1
x_ = x_ * 2
print(x_) # prints 2
```
In general, I think it's not a bad idea to use a new variable for each TensorFlow op to avoid bugs like these. Note you can write it in the same number of lines:
```python
x_ = tf.placeholder(tf.float64, [5])
r = tf.where(tf.is_nan(x_), tf.zeros_like(x_), x_)
```
I'm gonna close this for now as I don't think it's a TensorFlow bug, but feel free to comment further.

**Comment by zaccharieramzi** [comment]
I agree with your explanation of what I am doing (wrong choice of words on my end). 
I also agree with your analogy. However, it's because it's analogous that I made this mistake.
I am not saying that it's a bug, but I think it can be a bit puzzling the first time you look at it, and that is why I was suggesting to throw a warning when reassigning a placeholder because it is going to lead to an unwanted behavior.

I also agree with your general comment on naming ops.

**Comment by skye** [comment]
True, I agree it's not really a bug per-se. Even so, I don't think we should change the default assignment operator to print a warning (in fact, I don't think it's even possible to do so in Python). Thank you for reporting though, hopefully if others run into the same problem they will find this thread.
