### ISSUE TITLE
tf.contrib.seq2seq attention_wrapper.py memory_sequence_length can not set None

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#9962]
tf version '1.1.0-rc2'
The problem is in attention_wrapper.py  77 
  memory_sequence_length = ops.convert_to_tensor(
      memory_sequence_length, name="memory_sequence_length")

Don't check if memory_sequence_length is None

**Comment by skye** [comment]
@ebrevdo

**Comment by ebrevdo** [comment]
I believe this has been fixed in TF 1.2rc2 ([here](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py#L76)).
