### ISSUE TITLE
configure script overrides user's bazelrc

### ISSUE THREAD

**Issue by vladfi1** [tensorflow/tensorflow#9963]
The `./configure` script will write to a `.bazelrc` file in the cwd to save some of it's options (in particular, jemalloc). Unfortunately this has the effect of overriding `~/.bazelrc`. This is undocumented, and probably should not happen. For now, the solution is copy your own bazelrc into the tensorflow root before configuring - fortunately `./configure` will not overwrite it and only append to it.

**Comment by ali01** [comment]
@jart, any thoughts about this?

**Comment by jart** [comment]
I'm aware of this behavior, consider it suboptimal, and I believe we should escalate this to Bazel. I've filed https://github.com/bazelbuild/bazel/issues/3022. Please follow there for progress.

The workaround is to copy the stuff in your `~/.bazelrc` into `tensorflow/.bazelrc`. Our configure script will not delete the file.

**Comment by jart** [comment]
Re-opening because I'm thinking of modifying our configure to work around this automatically.

**Comment by Zumbalamambo** [comment]
Im getting the following error while trying to build `so` file

> Unexpected error reading .blazerc file '/Users/Johnny/Downloads/tensorflow-master/.tf_configure.bazelrc'

Following is the command that I tried,
`
bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so    --crosstool_top=//external:android/crosstool    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain    --cpu=armeabi-v7a`
