### ISSUE TITLE
gcc failed and fatal error: infiniband/verbs.h: No such file or directory

### ISSUE THREAD

**Issue by ChinaMobileNG** [tensorflow/tensorflow#9966]
When building TensorFlow from source

ERROR: /home/rock/tensorflow/tensorflow/core/distributed_runtime/rdma/BUILD:81:1: C++ compilation of rule '//tensorflow/core/distributed_runtime/rdma:rdma' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 118 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from tensorflow/core/distributed_runtime/rdma/rdma.cc:10:0:
./tensorflow/core/distributed_runtime/rdma/rdma.h:8:30: fatal error: infiniband/verbs.h: No such file or directory
compilation terminated.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.

**Comment by skye** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request (most install issues are configuration/environment issues). There is also a larger community that reads questions there. Thanks!

**Comment by shamoya** [comment]
@ChinaMobileNG  - you complied with VERBS support (this is what you wanted right ?) 
and in this case you need to install IB verbs SW stack (libibverbs and all of it kernel dependencies == OFED or MLNX_OFED if using Mellanox devices)

**Comment by achainan** [comment]
Posted a similar question on Stackoverflow:
https://stackoverflow.com/questions/44267616/bazel-build-tensorflow-python-toolsstrip-unused-compilation-failure

Thanks.

**Comment by HhxuTtxs** [comment]
I have the same question. Can you give me some suggestions?

**Comment by achainan** [comment]
Try using `local_resources` for your bagel build commands:
`bazel build tensorflow/python/tools:strip_unused --local_resources 2048,.5,1.0`

**Comment by HhxuTtxs** [comment]
I followed your advice, but there were still the following error
ERROR: /home/fhkj/tensorflow/tensorflow/contrib/verbs/BUILD:104:1: C++ compilation of rule '//tensorflow/contrib/verbs:rdma_rendezvous_mgr' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 167 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from ./tensorflow/contrib/verbs/rdma_mgr.h:24:0,
                 from ./tensorflow/contrib/verbs/rdma_rendezvous_mgr.h:21,
                 from tensorflow/contrib/verbs/rdma_rendezvous_mgr.cc:18:
./tensorflow/contrib/verbs/rdma.h:21:30: fatal error: infiniband/verbs.h: No such file or directory
compilation terminated.
Target //tensorflow/python/tools:strip_unused failed to build
Use --verbose_failures to see the command lines of failed build steps.
@achainan

**Comment by HhxuTtxs** [comment]
I solved the problem by following the link below
[](https://github.com/tensorflow/tensorflow/issues/9818)
but there's another error
ERROR: /home/fhkj/tensorflow/tensorflow/python/BUILD:2687:1: Linking of rule '//tensorflow/python:_pywrap_tensorflow_internal.so' failed: link_dynamic_library.sh failed: error executing command external/bazel_tools/tools/cpp/link_dynamic_library.sh no ignored ignored ignored /usr/bin/gcc -shared -o bazel-out/local-opt/bin/tensorflow/python/_pywrap_tensorflow_internal.so -Wl,--version-script ... (remaining 10 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/usr/bin/ld.gold: error: cannot find -libverbs
collect2: error: ld returned 1 exit status
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
@achainan

**Comment by HhxuTtxs** [comment]
https://github.com/tensorflow/tensorflow/issues/9818

**Comment by HhxuTtxs** [comment]
Thanks  very much! I have solved the problem by installing libibverbs-dev.
    sudo apt-get update
    sudo apt-get install libibverbs-dev

**Comment by nanteby** [comment]
On redhat 9.0 I used the following.
yum install libibverbs-devel
