### ISSUE TITLE
#issue: broken or outdated link link for NLP tutorial

### ISSUE THREAD

**Issue by alexDeCastroAtGit** [tensorflow/tensorflow#9972]
The second link, in the highlights session of the webpage

[Vector Representations](https://www.tensorflow.org/tutorials/word2vec)

is broken or outdated.

This is the link that's not working (404 from github)

[https://www.github.com/tensorflow/tensorflow/blob/r1.1/tensorflow_models/tutorials/embedding/word2vec.py](https://www.github.com/tensorflow/tensorflow/blob/r1.1/tensorflow_models/tutorials/embedding/word2vec.py)

**Comment by skye** [comment]
@wolffg @dr4b

**Comment by alexDeCastroAtGit** [comment]
Another broken link in the same page: 

(https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow_models/tutorials/embedding/word2vec_optimized.py)[https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow_models/tutorials/embedding/word2vec_optimized.py]

**Comment by skye** [comment]
Actually this is already fixed in the latest 1.2 docs: https://www.tensorflow.org/versions/r1.2/tutorials/word2vec

This will be fixed in the main docs when we switch them over to the 1.2 docs.

**Comment by dr4b** [comment]
Wait, but I still see a broken link to https://www.github.com/tensorflow/tensorflow/blob/r1.2/tensorflow_models/tutorials/embedding/word2vec.py in the 1.2 doc; that 404's for me, so are you sure this is fixed?

**Comment by skye** [comment]
Ah you're right, still looks broken (although in a different way!).

**Comment by dr4b** [comment]
Also this bug is a duplicate of #9905 if I'm not mistaken.

**Comment by michaelisard** [comment]
Thanks, closing this as a duplicate of #9905 please reopen if there's still a problem when that one is closed.
