### ISSUE TITLE
tf.Estimator vs contrib. Very unclear differences and lots of deprecations.

### ISSUE THREAD

**Issue by jubjamie** [tensorflow/tensorflow#9974]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows/Ubuntu
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.1.0
- **Bazel version (if compiling from source)**: /
- **CUDA/cuDNN version**: 5
- **GPU model and memory**: K40
- **Exact command to reproduce**: N/A

### Describe the problem
Is it just me or is there quite a large disconnect between the two versions of Estimator. The tutorial in the docs guides you through the contrib version but I understand that it has also been moved to tf.Estimator? However in the docs it appears that almost all functionality, e.g. canned estimators or .fit() appears to be missing or altered and there is little documentation to explain this new API.

Have I misunderstood something here? I imagine that we are preferred to use tf.estimator because using the contrib version kicks up all sorts of warning about how it will be deprecated last year! Although the estimator tutorial still uses it and also .fit() which I can't clearly see the replacement for in the new API. Is there going to be any example code or tutorial for the new tf.Estimator API as I feel it desperately needs it. The contrib version was difficult enough to understand that I gave up but want to try again! Thanks

**Comment by skye** [comment]
@wolffg @ispirmustafa (please redirect as appropriate, thanks)

**Comment by ispirmustafa** [comment]
Sorry for confusion. 
Right there is a difference between tf.Estimator and contrib one. Most of those changes are removal of deprecated behaviors. There are a few name changes. Currently we're moving some of the canned contrib Estimators under  tf.estimator. We'll update all our examples and tutorials after that.
