### ISSUE TITLE
Building with config MKL with current master (git version: v1.1.0-rc2-1163-gcbe5eb4) fails with a build rule error

### ISSUE THREAD

**Issue by nhasabni** [tensorflow/tensorflow#9979]
Building with config MKL with the current master fails with build rule error.

### System information: 
(contents from tf_env.txt)
== cat /etc/issue ===============================================
Linux desktop 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
VERSION="16.04.2 LTS (Xenial Xerus)"
VERSION_ID="16.04"
VERSION_CODENAME=xenial

== are we in docker =============================================
No

== compiler =====================================================
c++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== uname -a =====================================================
Linux desktop 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

== check pips ===================================================
numpy (1.12.1)
protobuf (3.3.0)
tensorflow (1.1.0)

== check for virtualenv =========================================
False

== tensorflow import ============================================
tf.VERSION = 1.1.0-rc2
tf.GIT_VERSION = v1.1.0-rc2-1163-gcbe5eb4
tf.COMPILER_VERSION = v1.1.0-rc2-1163-gcbe5eb4
Sanity check: array([1], dtype=int32)

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================

== cuda libs  ===================================================

**Exact command to reproduce**:

bazel --output_user_root=/home/desktop/gtt/tfbuild_opt/ build --copt="-DEIGEN_USE_VML" --config=mkl -c opt //tensorflow/tools/pip_package:build_pip_package

### Describe the problem: Build with the above setup and following configure options fails with a build rule error.

$ ./configure
Please specify the location of python. [Default is /usr/bin/python]: 
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Using python library path: /usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with MKL support? [y/N] y
MKL support will be enabled for TensorFlow
Do you wish to download MKL LIB from the web? [Y/n] 
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? [Y/n] 
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Do you wish to build TensorFlow with VERBS support? [y/N] 
No VERBS support will be enabled for TensorFlow
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] 
No CUDA support will be enabled for TensorFlow
Warning: ignoring http_proxy in environment.
...
.....................
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
Configuration finished

Build failed with following error:

`
ERROR: /home/desktop/gtt/tensorflow/core/BUILD:1544:1: undeclared inclusion(s) in rule '//tensorflow/core:core_cpu_base':
this rule is missing dependency declarations for the following files included by 'tensorflow/core/graph/mkl_tfconversion_pass.cc':
  '/home/desktop/gtt/tensorflow/core/common_runtime/function.h'
  '/home/desktop/gtt/tensorflow/core/common_runtime/device_mgr.h'
  '/home/desktop/gtt/tensorflow/core/common_runtime/optimization_registry.h'
  '/home/desktop/gtt/tensorflow/core/common_runtime/device_set.h'.
____Building complete.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
____Elapsed time: 615.488s, Critical Path: 227.18s
`

**Comment by ali01** [comment]
@jrvb, any thoughts about this?
