### ISSUE TITLE
Missing .pb.h Files While Building from Source on Windows using CMake 

### ISSUE THREAD

**Issue by barnandas** [tensorflow/tensorflow#9984]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10 Enterprise
- **TensorFlow installed from (source or binary)**:
Trying to install from source
- **TensorFlow version (use command below)**:
1.1
- **Bazel version (if compiling from source)**:
Using cmake to compile from source
- **CUDA/cuDNN version**:
Not using CUDA. Trying to build CPU only version from source
- **GPU model and memory**:
N/A
- **Exact command to reproduce**:
After following the instructions to build TF from source on Windows using cmake as given [here](https://github.com/tensorflow/tensorflow/tree/r0.12/tensorflow/contrib/cmake), at step 4, I am trying to build tf_tutorials_example_trainer.vcxproj using MS Visual Studio 2015 instead of MSBuild.

### Describe the problem
While trying to build tf_tutorials_example_trainer.vcxproj, I get a whole bunch of errors such as "Cannot open include file <some/path/*.pb.h>". After looking at the source code files, it looks like .pb.h files do not exist. However, the corresponding .proto files do exist. For example, I can see "atr_value.proto" under <TF source files/tensorflow/core/framework>, but not "atr_value.pb.h". I think for some reason protobuf is not generating the .pb.h files from .proto

Note: I have also installed the TF executable following instructions given [here](https://www.tensorflow.org/install/install_windows). It installed correctly. Hence, I have all dependencies installed on my system.

### Source code / logs
cmake log:
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
       -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED
-- Performing Test COMPILER_OPT_ARCH_NATIVE_SUPPORTED - Failed
-- Found PythonInterp: C:/local/Anaconda3-4.1.1-Windows-x86_64/envs/tensorflow/python.exe (found version "3.5.3")
-- Found PythonLibs: C:/local/Anaconda3-4.1.1-Windows-x86_64/envs/tensorflow/libs/python35.lib (found version "3.5.3")
-- Found SWIG: C:/local/swigwin-3.0.10/swig.exe (found version "3.0.10")
-- Configuring done
-- Generating done
-- Build files have been written to: <TF source dir>/tensorflow/contrib/cmake/build

**Comment by skye** [comment]
@mrry can you comment or redirect to someone who can? Thanks!

**Comment by mrry** [comment]
Does it work if you use MSBuild rather than Visual Studio to build the project?

**Comment by adennie** [comment]
I think you may need to build the tf_protos_cc module to generate those pb.h files.

**Comment by PinkySan** [comment]
Had the same issue as you yesterday. In tf_core_framework.cmake they are trying to build the *pb.h from the *.proto files. I guess they forgot to check, if the protocol buffer compiler is installed. Maybe it will help, if you install in manually [https://developers.google.com/protocol-buffers/docs/downloads](protocoll buffer). Please try and let me know

**Comment by barnandas** [comment]
ISSUE RESOLVED. It was a silly one. 

The build process makes a bunch of git clones. As I was trying to build x64 Release mode in MSVS 2015, the 64-bit version of Git was being called and failed as I had 32-bit version installed on my system. I installed 64-bit Git and the .pb.h files were successfully generated. 

Thanks for the help!

**Comment by DavideCatto** [comment]
> ISSUE RESOLVED. It was a silly one.
> 
> The build process makes a bunch of git clones. As I was trying to build x64 Release mode in MSVS 2015, the 64-bit version of Git was being called and failed as I had 32-bit version installed on my system. I installed 64-bit Git and the .pb.h files were successfully generated.
> 
> Thanks for the help!

I can't understand how to generate dnn.pb.h file.
Can you please upload dnn.pb.h file in order to ""copy"" the declaration and manually generate it?
