### ISSUE TITLE
[feature] Support Lanczos method in tf.image.resize_images

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#9988]
Add support for a `Lanczos` (a truncated sinc) mode in `tf.image.resize_images`. Currently this mode is not offered.

[Pillow supports `LANCZOS`](http://pillow.readthedocs.io/en/3.4.x/handbook/concepts.html#filters) (aka `ANTIALIAS`) as a resampling method and stipulates this method has the [highest quality for down sampling](http://pillow.readthedocs.io/en/3.4.x/handbook/concepts.html#filters-comparison-table) ([default for `thumbnail` for example](http://pillow.readthedocs.io/en/3.4.x/reference/Image.html#PIL.Image.Image.thumbnail)).
![image](https://cloud.githubusercontent.com/assets/51059/26181858/91e9471e-3b41-11e7-8653-4fa7277e98a6.png)

**Comment by skye** [comment]
FYI @girving @gpapan

**Comment by girving** [comment]
Seems reasonable as contributions welcome to me.

**Comment by shitian-ni** [comment]
Hi, I want to work on this. 
I tried to take a look at related methods like `tf.image.resize_bilinear`.
[api_docs](https://www.tensorflow.org/api_docs/python/tf/image/resize_bilinear) says the method is defined in `tensorflow/python/ops/gen_image_ops.py`, but I am unable to find gen_image_ops.py in tensorflow/python/ops.
Where is gen_image_ops.py? 
Thanks

**Comment by cancan101** [comment]
The op is defined here: https://github.com/tensorflow/tensorflow/blob/fabd225532ee068d1f9ffbdc4a8795e7de99ad24/tensorflow/core/ops/image_ops.cc#L161

**Comment by shitian-ni** [comment]
Thanks. Where is it implemented?

**Comment by cancan101** [comment]
That is the old current set of resize ops. Lanczos has not been done.

**Comment by WKChung1028** [comment]
@shitian-ni  Hi, have you get the tensorflow/python/ops/gen_image_ops.p? or you know it work?

**Comment by anishchopra** [comment]
+1 , would love to see this added

**Comment by johnpjf** [comment]
This is available in the TF 2.0 alpha release.

**Comment by dynamicwebpaige** [comment]
As @johnpjf mentioned, this is [supported](https://www.tensorflow.org/api_docs/python/tf/image/resize), as of TensorFlow 2.0. Thanks for the feature request! Closing now. 👍
