### ISSUE TITLE
Find an error in mnist_softmax.py

### ISSUE THREAD

**Issue by hantmac** [tensorflow/tensorflow#9997]
------------------------

### System information
- **OS Platform and Distribution (Mac os)**:
- **TensorFlow installed from (binary)**:
- **TensorFlow version (master)**:

### Describe the problem
In mnist_softmax.py,there is a difference between github an the web of Tensorflow(https://www.tensorflow.org/versions/r0.12/tutorials/mnist/beginners/index.html),and the code on github has error in line 57,58.

### Source code / logs
I replaced `cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(y, y_))` with `cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))`.And it works.

**Comment by gunan** [comment]
Could you link to the file with the mistake?
