### ISSUE TITLE
How to build tensorflow for mips64el

### ISSUE THREAD

**Issue by xzy256** [tensorflow/tensorflow#9998]
The recommended way to build TensorFlow from source is using the Bazel open-source build system.
Howerver, bazel depends `protobuf,grpc-java,osdetector` etc.  protocbuf can build  successfully for mips64el. But i  build grpc-java  failed. details see [#3012](https://github.com/grpc/grpc-java/issues/3012). i refer [#2022](https://github.com/grpc/grpc-java/issues/2202). but osdetector-gradle-plugin occur error.
Could anybody give me some help for building tensorflow for mips64el arch?

**Comment by skye** [comment]
You could try the CMake build instead of using bazel: https://github.com/tensorflow/tensorflow/tree/r1.2/tensorflow/contrib/cmake

**Comment by xzy256** [comment]
ok,  thanks. I have a try.

**Comment by xzy256** [comment]
@skye i refer [https://github.com/tensorflow/tensorflow/tree/r1.2/tensorflow/contrib/cmake](https://github.com/tensorflow/tensorflow/tree/r1.2/tensorflow/contrib/cmake), dependencies included.
However, i exec `tensorflow/tools/ci_build/ci_build.sh CMAKE tensorflow/tools/ci_build/builds/cmake.sh` for building tensorflow, output logs as follow,
<pre>
[root@localhost tensorflow]# tensorflow/tools/ci_build/ci_build.sh CMAKE tensorflow/tools/ci_build/builds/cmake.sh
WORKSPACE: /home/loongson/tensorflow
CI_DOCKER_EXTRA_PARAMS: 
COMMAND: tensorflow/tools/ci_build/builds/cmake.sh
CI_COMMAND_PREFIX: 
CONTAINER_TYPE: cmake
BUILD_TAG: tf_ci
  (docker container name will be tf_ci.cmake)

Building container (tf_ci.cmake)...
Sending build context to Docker daemon 304.1 kB
Step 1 : FROM ubuntu:16.04
Trying to pull repository docker.io/library/ubuntu ... 
sha256:382452f82a8bbd34443b2c727650af46aced0f94a44463c62a9848133ecb1aa8: Pulling from docker.io/library/ubuntu
b6f892c0043b: Pull complete 
55010f332b04: Pull complete 
2955fb827c94: Pull complete 
3deef3fcbd30: Pull complete 
cf9722e506aa: Pull complete 
Digest: sha256:382452f82a8bbd34443b2c727650af46aced0f94a44463c62a9848133ecb1aa8
Status: Downloaded newer image for docker.io/ubuntu:16.04
 ---> ebcd9d4fca80
Step 2 : MAINTAINER Shanqing Cai <cais@google.com>
 ---> Running in 5539f888554c
 ---> b47c31a23a17
Removing intermediate container 5539f888554c
Step 3 : COPY install/*.sh /install/
 ---> 1c16e7a094c4
Removing intermediate container 555cd53000c4
Step 4 : RUN /install/install_bootstrap_deb_packages.sh
 ---> Running in ddd33994a3bf
panic: standard_init_linux.go:175: exec user process caused "exec format error" [recovered]
	panic: standard_init_linux.go:175: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x1203d0060, 0xc420149ea0)
	/usr/lib/golang/src/runtime/panic.go:500 +0x4c4
... ...
</pre>
As we knows, docker is used for testing, but our os is fedora not ubuntu. It occur error. I try to modify `Dockerfile` or shut down the docker test. Could you give me some ideas ?

**Comment by skye** [comment]
You'll probably have to dig into the cmake files (which I'm not super familiar with), as we only test them on Windows 10 and Ubuntu 14.04. You can also try posting on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow). Sorry I can't be more helpful; MIPS isn't an architecture we support or test.

**Comment by xzy256** [comment]
Thanks for your attention. @skye

**Comment by xzy256** [comment]
@skye  i build bazel successful. Then, i build tensorflow getting next error.
<pre>
[xzy@localhost tensorflow]$ bazel build --copt=-march=native -c opt //tensorflow/tools/pip_package:build_pip_package
Extracting Bazel installation...
............................................
WARNING: /home/xzy/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': Use SavedModel Builder instead.
WARNING: /home/xzy/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': Use SavedModel instead.
INFO: Found 1 target...
ERROR: /home/xzy/.cache/bazel/_bazel_xzy/c01fa588a238f7be12b727d5cfbf1a03/external/io_bazel_rules_closure/java/io/bazel/rules/closure/webfiles/server/BUILD:48:1: 
error executing shell command: 'JAR='external/local_jdk/bin/jar' OUTPUT='bazel-out/host/bin/external/io_bazel_rules_closure/java/io/bazel/rules/closure/webfiles/server/libbuild_info_java_proto_srcjar.srcjar' PROTO_COMPILER='bazel...' failed: bash failed: 
error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): 
com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
bazel-out/host/bin/external/io_bazel_rules_closure/closure/private/gensrcjar: line 75: bazel-out/host/genfiles/external/io_bazel_rules_closure/third_party/protobuf/protoc: cannot execute binary file: Exec format error
gensrcjar: proto_compiler failed
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 507.821s, Critical Path: 30.98s


[xzy@localhost tensorflow]$ protoc --version
libprotoc 3.2.0
[xzy@localhost tensorflow]$ bazel version
Build label: 0.5.0-2017-06-01 (@2e9fff0)
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: thur may 1 01:57:44 2017 (1496282264)
Build timestamp: 1496282264
Build timestamp as int: 1496282264
</pre>

**Comment by xzy256** [comment]
Using `sudo  bazel build --copt=-march=native -c opt //tensorflow/tools/pip_package:build_pip_package` can fix upwards error. Then i get a new error `Executing genrule //tensorflow/tensorboard/components/tf_tensorboard:ts failed: bash failed: error executing command`
<pre>
ERROR: /home/xzy/tensorflow/tensorflow/tensorboard/components/tf_tensorboard/BUILD:54:1: Executing genrule //tensorflow/tensorboard/components/tf_tensorboard:ts failed: bash failed: error executing command 
  (cd /root/.cache/bazel/_bazel_xzy/c01fa588a238f7be12b727d5cfbf1a03/execroot/tensorflow && \
  exec env - \
    PATH=/opt/j2sdk-image/bin:/usr/local/bin/:/usr/bin:/opt/j2sdk-image/bin:/usr/local/bin/:/usr/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/home/xzy/.local/bin:/home/xzy/bin \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/lib/python2.7/site-packages \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL=0 \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; bazel-out/host/genfiles/external/com_microsoft_typescript/tsc.sh --inlineSourceMap --inlineSources --noResolve --declaration --module es6 --outDir bazel-out/local-opt/genfiles/tensorflow/tensorboard/components/tf_tensorboard external/com_microsoft_typescript/lib.es6.d.ts tensorflow/tensorboard/components/tf_tensorboard/autoReloadBehavior.ts'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 126.
bazel-out/host/genfiles/external/com_microsoft_typescript/tsc.sh: line 6: /root/.cache/bazel/_bazel_xzy/c01fa588a238f7be12b727d5cfbf1a03/execroot/tensorflow/external/org_nodejs/bin/node: cannot execute binary file: Exec format error
bazel-out/host/genfiles/external/com_microsoft_typescript/tsc.sh: line 6: /root/.cache/bazel/_bazel_xzy/c01fa588a238f7be12b727d5cfbf1a03/execroot/tensorflow/external/org_nodejs/bin/node: Success
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 3.513s, Critical Path: 0.15s
</pre>

**Comment by xzy256** [comment]
Modifying `tensorflow/workspace.bzl` NODE=path/to/node can fix it. I have built tensorflow success, and test pass. build patch see [build-tf-mips64.diff](https://github.com/xzy256/tensorflow-mips/blob/master/build-tf-mips.diff). Error and solution see[build-tf-mips-error.log]()
<pre>
# pip install /tmp/tensorflow_pkg/tensorflow-1.2.0rc1-cp27-none-linux_mips64.whl
...
    Installing /usr/lib/python2.7/site-packages/protobuf-3.3.0-py2.7-nspkg.pth
  Found existing installation: six 1.7.3
    Uninstalling six:
      Successfully uninstalled six
  Found existing installation: Werkzeug 0.9.6
    Uninstalling Werkzeug:
      Successfully uninstalled Werkzeug
Successfully installed tensorflow mock bleach markdown 
     numpy html5lib protobuf six werkzeug funcsigs pbr
Cleaning up...

# python
>>> import tensorflow as tf
>>> 
</pre>
Please close this issue. Thanks

**Comment by skye** [comment]
Thank you for sharing how you resolved this!

**Comment by xzy256** [comment]
Hi @skye I want to have a look at tensorflow performance at my platform. How should i do?

**Comment by skye** [comment]
Here are some benchmarks we performed along with the methodology: https://www.tensorflow.org/performance/benchmarks

**Comment by xzy256** [comment]
ok. Thank you.
