### ISSUE TITLE
Directories with spaces in their names don't compile due to missing quotes in shell scripts

### ISSUE THREAD

**Issue by shre81** [tensorflow/tensorflow#9999]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX Sierra, Macbook Pro 2015
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: v1.0.0-65-g4763edf-dirty 1.0.1
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**:

### Describe the problem

I was building tensorflow for iOS and as a part of this, tried running the `build_all_ios.sh` but it threw some errors. The error is mainly because there are parts in shell script that either attempt to create or move to a directory that is incorrectly referenced. In my case, it was because of spaces in directory names. This is true even for the 'compile_ios_protobuf.sh' script (and harder to detect because of the very verbose log). 

I was able to get-around this by modifying both of these shell scripts to include double quotes around 
lines that referenced directory paths. 

### Source code / logs

Few examples lines here:

Line 28 (build_all_ios.sh): 'cd ${SCRIPT_DIR}/../../../' (notice that this will ignore spaces in the directory path, if they exist

Line 35 (compile_ios_protobuf.sh): 'mkdir -p ${LIBDIR}' (this will similarly create a directory at an unexpected path and will not complete compilation)

**Comment by ali01** [comment]
Hi @shre81, thank you for reaching out .Could you please provide any additional information that might allow us to reproduce this problem? Exact command lines would be very helpful.

**Comment by shre81** [comment]
Sure. 

Here's what I tried to run:

`sudo ./tensorflow/contrib/makefile/compile_ios_protobuf.sh `

and this is the terminal log output:

`/bin/sh: /Users/shreyasgopinath/Documents/Bluth: is a directory
make[2]: *** [google/protobuf/compiler/js/well_known_types_embed.cc] Error 126
make[2]: *** Waiting for unfinished jobs....`

It is attempting to look for a directory called 'Bluth' while it should be looking for 'Bluth Company'. I believe it is the space in the name that's causing the error.

Does this help? Or, will additional lines before and after this error help?

Thanks

**Comment by jart** [comment]
Adding quotes to shell scripts is something that's as easy to forget as it is to fix. We welcome any contributions improving this.

**Comment by pbanavara** [comment]
@jart I have some time to fix this. Is replacing any detected whitespace with '\' a good solution ? Or should I aim for something better. Please let me know.

**Comment by jart** [comment]
On second thought, this might not be a good issue to fix. It would be extremely difficult to maintain our build system(s) if we couldn't assume paths don't have spaces. Please build TensorFlow under a path that doesn't have spaces. If you find any stuff in our source tree that has spaces, let us know.

**Comment by Ashwin-Dhakal** [comment]
You are having this problem due to the white space in the directory as:(machine learning)
tensorboard --logdir=foo:E:\projects\machine learning\Cat-and-Dog-novice\log

This can be fixed using the "" for the directory as:
tensorboard --logdir=foo:"E:\projects\machine learning\Cat-and-Dog-novice\log"

Hope this helps :100:
